### PR TITLE
U-escape sequences in string literals

### LINKED ISSUE #41365: Should `\U` always require 8 hex digits? Or up to 6?
While the first string is as expected, the second one fails.
Probably more than 6 digits are used to calculate the code point.

```
julia> "\U100000g"
"\U100000g"

julia> "\U100000f"
ERROR: syntax: invalid escape sequence
Stacktrace:
 [1] top-level scope
   @ none:1
```

### PR DESCRIPTION
**Pull request by KlausC**
fixes #41365

### CODE REVIEW

**Comment by KlausC** [comment]
This proposal allows to write U-sequences within strings be written in a better readable form.
Not easily readable code is IMO the following, where the maximal size of the the U-sequence is unintentionally consumed.

```
"10FFFFExample"
```
where the `E` leads to an invalid sequence, because `0x10ffffe` is not a valid code point. Reduction the maximal length to 6 will resolve the error in this case. That cannot be resolved, if we allow shorter than maximal sequences, because a hex character
after such a sequence will be appended to the U-sequence also if its intention was a separate character.

To support the C-style of providing exactly eight digits (of which the first two are always `0`) we continue to support up to eight digits, if the first two are `0`.

If the first digits are not both `0`, the maximal length the escape sequence is reduced to six.
This reduced maximal size allows to avoid the ugly `U00`, which is required to avaid ambiguity currently.
```
"\U10FFFFA" == "\U10FFFF" * "A"
"\U01FFFFA" == "\U01FFFF" * "A"
```

If we recommend to use `\x` and `\u` when possible, we can now write each unicode character with the unambiguous maximal size and with at most one leading `0`.

`"\01FFFFExample" ` instead of `"\U0001FFFFExample"`

**Comment by KlausC** [comment]
The change is breaking in cases like the following, where Unicode planes 16 and 01 are confused by the ambiguitiy.

`"\U010FFFFX" `  was before PR '\U10ffff' * "X"`, after PR  `'\U010FFF' * "FX"` 

The are no other cases known, which create valid code before and after.

**Comment by PallHaraldsson** [comment]
>The change is breaking in cases like the following, where Unicode planes 16 and 01

those as 1 basically non-European scripts:
https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Multilingual_Plane

while including e.g. Symbols and non-Latin European and 16 is a Private Use Area plane, I believe not much used. So is this only "technically breaking"?

**Comment by StefanKarpinski** [comment]
Aside from being a breaking change, this makes the rule significantly more complex and hard to understand — look at how awkward it is to explain in the docs. This does not strike me as an improvement.

**Pull request closed without merging**
