### PR TITLE
improve cmp performance

### PR DESCRIPTION
**Pull request by davidssmith**
20-25% performance improvement in my testing

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Cool!

What types did you test on? Do you get the same speedup for `isless(y,x) - isless(x,y)`? If so, that would be better since its behavior is more similar.

**Comment by davidssmith** [comment]
I tested on  `Float64` and `Int64`. 

For `Float64`, the symbolic approach is faster, while `isless` is slower than stock.

For `Int64`, it's about the same.

Now I'm not so sure about the `Int` timings, because my results seem highly variable as I rerun it multiple times, but this patch is always at least as good as stock. For `Float`s the improvement is consistent. So maybe this trick only works for `Float`s for some reason. In fact I was surprised to find that this works, because I thought the code gen would do it if it were faster, but oh well.

Here is my timing code:

```
N = 10000000
x = rand(N)
y = rand(N)
a = rand(1:10,N)
b = rand(1:10,N)

cmpnewfun(x,y) = isless(y,x) - isless(x,y)
cmpnewsym(x,y) = (x > y) - (x < y)

function cmp{T}(x::Vector{T}, y::Vector{T})
  z = similar(x)
  for j in 1:length(x)
    z[j] = Base.cmp(x[j],y[j])
  end
  return z
end
function cmpnewsym{T}(x::Vector{T}, y::Vector{T})
  z = similar(x)
  for j in 1:length(x)
    z[j] = cmpnewsym(x[j],y[j])
  end
  return z
end
function cmpnewfun{T}(x::Vector{T}, y::Vector{T})
  z = similar(x)
  for j in 1:length(x)
    z[j] = cmpnewfun(x[j],y[j])
  end
  return z
end

println("old cmp float")
@time z = cmp(x,y)
@time z = cmp(x,y)
@time z = cmp(x,y)
println("new cmp float sym")
@time z = cmpnewsym( x,y)
@time z = cmpnewsym( x,y)
@time z = cmpnewsym( x,y)
println("new cmp float fun")
@time z = cmpnewfun( x,y)
@time z = cmpnewfun( x,y)
@time z = cmpnewfun( x,y)
println("old cmp int")
@time c = cmp(a,b)
@time c = cmp(a,b)
@time c = cmp(a,b)
println("new cmp int sym")
@time c = cmpnewsym(a,b)
@time c = cmpnewsym(a,b)
@time c = cmpnewsym(a,b)
println("new cmp int fun")
@time c = cmpnewfun(a,b)
@time c = cmpnewfun(a,b)
@time c = cmpnewfun(a,b)
println(z[end])
println(c[end])
```

**Comment by JeffBezanson** [comment]
Well, this particular definition isn't actually called for Int64 or Float64, so those tests don't have much bearing on this patch. My main concern is that it's not always correct to replace `isless` with `<`.

**Comment by davidssmith** [comment]
Ah, I see. I forgot to burrow deep enough.

But it looks like `cmp(Float,Float)` already uses operators `(float.jl:254)`:
```
function cmp(x::AbstractFloat, y::AbstractFloat)
    (isnan(x) || isnan(y)) && throw(DomainError())
    ifelse(x<y, -1, ifelse(x>y, 1, 0))
end
```

So maybe this patch should change that function instead?

**Comment by davidssmith** [comment]
Or I wonder if my function is faster simply because I'm not checking for `NaN`s.

**Comment by davidssmith** [comment]
Nope, this is still faster:
```
function cmpnewsym(x::AbstractFloat, y::AbstractFloat)
    (isnan(x) || isnan(y)) && throw(DomainError())
    (x > y) - (x < y)
end
```

Now, whether you want to continue using `<` there instead of `isless` is a different story.

**Comment by JeffBezanson** [comment]
Yes, there is #5290. But of course that's a separate issue from this optimization.

**Comment by davidssmith** [comment]
Ok, since I didn't see a definite benefit in the `Int` case, I've changed this PR to just address `Float` comparisons, in case you want to use it.

**Comment by stevengj** [comment]
Bump.  Is this still relevant?

**Comment by davidssmith** [comment]
Doesn't appear to be.

**Comment by KristofferC** [comment]
Out of curiosity, why not?

**Comment by davidssmith** [comment]
I retested it on 0.6, and now the performance improvement is no longer there. I don't know what changed specifically.

**Comment by KristofferC** [comment]
Ok, thanks for testing it!

**Comment by davidssmith** [comment]
I should add, this is using `BenchmarkTools`.  

Now there is something strange if you want to look into it, but it is not relevant to this PR. When I `@time` these two functions on a large `Array{Float}`:
```
function cmp{T}(x::Vector{T}, y::Vector{T})
  z = similar(x)
  for j in 1:length(x)
    z[j] = Base.cmp(x[j],y[j])
  end
  return z
end
function cmpnewsym{T}(x::Vector{T}, y::Vector{T})
  z = similar(x)
  for j in 1:length(x)
    z[j] = cmpnewsym(x[j],y[j])
  end
  return z
end
```
I get that `cmpnewsym` is still faster by about 50-60%. I assume that the timing method is flawed, since `BenchmarkTools` is supposed to be better, but clearly something is happening that is not optimal.

**Pull request closed without merging**
