### PR TITLE
Correct type of `jl_lineno`

### PR DESCRIPTION
**Pull request by yuyichao**
It was my fault in https://github.com/JuliaLang/julia/pull/11311 = = .....

### CODE REVIEW

**Comment by tkelman** [comment]
did someone else get this? backport needed or not?

**Comment by yuyichao** [comment]
The issue is present in the code on 0.4. Is this not enough reason for backport?

**Comment by tkelman** [comment]
did you mean to merge instead of close? is this testable? I dislike backporting things that never go to master without a good reason

**Comment by yuyichao** [comment]
> did you mean to merge instead of close?

Yes. = =....

> is this testable?

Not easily?

**Pull request merged**
