### PR TITLE
Misc linalg tests

### PR DESCRIPTION
**Pull request by kshyatt**
We had two `expm(x::Number)` methods defined.

I moved some `Hessenberg` tests out of `dense.jl` to `qr.jl` which is a more natural place for them.

I added tests for `cholesky.jl` and `matmul.jl`.

### CODE REVIEW

**Comment by kshyatt** [comment]
We have an unrelated OOM failure and something I don't understand on OSX. Weirdly enough, I ran this locally on OSX and it's fine?

**Comment by kshyatt** [comment]
In the process of hunting I realized we were running the tests on the same matrices multiple times for no reason.

**Comment by tkelman** [comment]
And running it multiple times was causing the failure?

**Comment by kshyatt** [comment]
I honestly have no idea. When I switched the random seeds, it went away. When I didn't preset a seed, it went away. I think this situation the linalg tests are in right now where we run with a specific set of "random" matrices each time is kind of brittle.

**Comment by kshyatt** [comment]
With the CI passing and the comment to explain how to reproduce, does this look ok, @tkelman & @andreasnoack?

**Comment by andreasnoack** [comment]
Looks good to me. I''m puzzled by the the `NaN`s, but I don't feel like spending a day or two on tracking down an issue that has only been seen in a test for a specific seed.

**Pull request merged**
