### PR TITLE
improvements to push!, unshift!, append!, prepend!

### PR DESCRIPTION
**Pull request by stevengj**
This PR implements  faster `push!(a, items...)` and `unshift!(a, items...)` to `a::Vector` for splatted arguments (more than 100x speedup for 1000 items), and extends `prepend!(a, items)` to work for arbitrary iterators (matching the documentation).   It also fixes `append!(a,b)` and `prepend!(a,b)` to work when `b` is a non 1-based array.  Finally, it improves the performance of `append!(a,iter)` when `iter` is an iterator (not an array) that has `size` and not just `length`.

### CODE REVIEW

**Comment by stevengj** [comment]
I don't thing nanosoldier really tests this, but might as well:

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Review by JeffBezanson — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19943#issuecomment-271322362) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/922cc776868c5f53a42906689049d714b7a3b72e/3fe8a3b_vs_7c34d69/report.md). cc @jrevels

**Comment by oscardssmith** [comment]
Sounds tests be added to guarantee this performance died not regress in the future?

**Comment by KristofferC** [comment]
More benchmarks are always good. Willing to help out?

**Comment by oscardssmith** [comment]
Willing: yes. competent: probably not. I have no experience writing tests, and I have written almost no Julia anyway

**Comment by stevengj** [comment]
Should be ready to merge.

**Pull request merged**
