### PR TITLE
RFC: Revert "Bump Pkg to latest master (8e236a7f993f1e732ffd0ab5c15736b2594e4109)"

### PR DESCRIPTION
**Pull request by vtjnash**
Reverts JuliaLang/julia#34091 while waiting for https://github.com/JuliaLang/Pkg.jl/pull/1549

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Makes sense to me. We can update the commit of Pkg once https://github.com/JuliaLang/Pkg.jl/pull/1549 is merged

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vtjnash** [comment]
Looks like that was merged, so maybe we'll just assume someone will bump the version here soon?

**Comment by DilumAluthge** [comment]
I’ll do it now

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/34186

**Pull request closed without merging**
