### PR TITLE
interpret &(a,b) as a call expresion

### LINKED ISSUE #34693: Parse `&x`as a call expression
In https://github.com/JuliaLang/julia/issues/6080#issuecomment-327029743 @JeffBezanson wrote: 
> Deprecation is in for 0.7. For 1.0, we should change the parsing of &x to a call expression.

This doesn't seem to have happened, cf https://discourse.julialang.org/t/ampersand-operator-not-consistent-with-help/34266. Is this something that can be changed for 1.x or would it have to wait for 2.0?

### LINKED ISSUE #34748: Bad syntax error for bitwise and being used non-infix
```jl
julia> 1 & 2
0

julia> &(1,2)
ERROR: syntax: invalid syntax &(Core.tuple(1, 2))
Stacktrace:
 [1] top-level scope at REPL[9]:1
```

Showing the `Core.tuple` seems potentially confusing?

### PR DESCRIPTION
**Pull request by birm**
closes #34693
I believe that & is included in this list by accident, but I'm not exactly sure.

### CODE REVIEW

**Comment by Keno** [comment]
> I believe that & is included in this list by accident, but I'm not exactly sure.

No, `&` used to be unary operator syntax for use in ccall. There's been talk about re-using it for automatic boxing.

**Comment by birm** [comment]
Ah, it looks like this has been discussed in #34693 and earlier #6080.

**Comment by yuyichao** [comment]
Yes. #34748 is only about printing and is not at all controversial. https://github.com/JuliaLang/julia/issues/34693 is about changing the parsing and is no decided on yet.

**Comment by birm** [comment]
ok, I've changed the closes to reference #34693 instead of #34748

**Comment by birm** [comment]
This would/could also involve reverting part of 68eaec6 if merged.

**Pull request closed without merging**
