### PR TITLE
release-1.6: Backports for 1.6.5

### LINKED ISSUE #25678: `return` matters in generated function lowering
Haven't tracked this down fully, but something is up with lowering:
```
@generated function code_llvm_helper(f, args...)
    NI.code_typed(f.parameters[1], Tuple{args...})[1].first
end
@generated function code_llvm_helper2(f, args...)
    return NI.code_typed(f.parameters[1], Tuple{args...})[1].first
end

julia> typeof(first(methods(code_llvm_helper)).generator.gen(nothing, Val{x->x}, [Bool]))
Expr

julia> typeof(first(methods(code_llvm_helper2)).generator.gen(nothing, Val{x->x}, [Bool]))
CodeInfo
```

This distinction matters quite a bit of course, since `CodeInfo` returns get treated specially.
Looks like the extra Expr in the first case is a LineNumberNode.

### LINKED ISSUE #43199: Some links to source in the stdlib documentation broken
E.g.: this leads to 404 error:

- got to https://docs.julialang.org/en/v1/stdlib/Statistics/
- mouse over bottom right of the box Statistics.std
- click 'Source'

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #43090 
- [x] #43196 
- [x] #43225 
- [x] #43251 
- [x] #43226 
- [x] #42854 
- [x] #42481 
- [x] #43219 
- [x] #43264 
- [x] #43003 
- [x] #43073 
- [x] #40778 

Need manual backport:
- [ ] #42112 
- [ ] #42170 
- [ ] #42474 
- [ ] #42906 
- [ ] #42907 
- [ ] #42904 
- [ ] #43276 

Contains multiple commits, manual intervention needed:

- [ ] #42172 
- [ ] #42837 
- [ ] #43168 

Non-merged PRs with backport label:
- [ ] #43210 
- [ ] #42736 
- [ ] #42715 
- [ ] #42311 
- [ ] #41228 
- [ ] #41041 
- [ ] #40820

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43152#issuecomment-991184633) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a895768_vs_eeb1472/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlgebraOfGraphics", "BLASBenchmarksCPU", "Biplots", "ChaosTools", "CommunityDetection", "Convex1d", "GADM", "Gemini", "GeoMakie", "InteractiveDynamics", "JUDI", "JUDI4Cloud", "KissMCMC", "LightGraphs", "MaxwellFDFD", "MusicManipulations", "NEOSServer", "ReliabilityDiagrams", "Relief", "Syslogs", "TexasHoldem", "VoronoiGraph", "ZigZagBoomerang"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43152#issuecomment-991455853) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a895768_vs_eeb1472/report.md).

**Pull request merged**
