### PR TITLE
require (using, import): give a hint in error message if typo in module name

### LINKED ISSUE #38604: using - give a hint in error message when there is a typo in package name
I think it is a very common mistake with using statements. As package names are case-sensitive, a small typo in name,  eg DataFrames: Dataframes, DataFrame, Dataframe, ..., results in an error message:

> julia> using Dataframes
> ERROR: ArgumentError: Package Dataframes not found in current path:
> - Run `import Pkg; Pkg.add("Dataframes")` to install the Dataframes package.
> 
> Stacktrace:
>  [1] require(into::Module, mod::Symbol)
>    @ Base ./loading.jl:874

in the next step the user will do the suggested solution, which will not work:

> julia> import Pkg; Pkg.add("Dataframes")
>     Updating registry at `~/.julia/registries/General`
> ERROR: The following package names could not be resolved:
>  * Dataframes (not found in project, manifest or registry)
> 
> Stacktrace:
>   [1] pkgerror(msg::String)
>     @ Pkg.Types ~/projects/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:52
>   [2] ensure_resolved(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; registry::Bool)
>     @ Pkg.Types ~/projects/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:823
...

I suggest to offer a different error message if there is an installed package with an similar name (in Stdlib or in Project deps), like:

> julia> using Dataframes
> ERROR: ArgumentError: Did you mean DataFrames? Your entry Dataframes is
> not found in current path. Correct your entry and try again, or run
> `import Pkg; Pkg.add("Dataframes")` to install the Dataframes package.
> 
> Stacktrace:
>  [1] require(into::Module, mod::Symbol)
>    @ Base ./loading.jl:868

If this is ok, I can offer to open a pull request (have already a  first draft).

### PR DESCRIPTION
**Pull request by strickek**
close #38604
I tried to keep it simple and avoid deps with REPL and Pkg.
The tests cover now this exception of require - so coverage should be better a little bit.

### CODE REVIEW

**Comment by strickek** [comment]
to start CI

**Comment by strickek** [comment]
Try to start ci tests

**Comment by dpsanders** [comment]
You need to replace `modul` with `module`.

**Comment by strickek** [comment]
Thx - german :-).
I have still failures with two ci tests and dont know what the problem is.

David P. Sanders <notifications@github.com> schrieb am So., 31. Jän. 2021,
23:34:

**Comment by strickek** [comment]
@KristofferC, pls have a loop. Thx

**Comment by strickek** [comment]
The code is working local, but I find no solution to overcome this 3 failing checks. So I close this PR.

**Pull request closed without merging**
