### PR TITLE
Added tests for Base.copy!

### PR DESCRIPTION
**Pull request by AmanDoesntCode**
Testing the deep copying of Sets, Dictionaries and arrays was necessary. Added tests for Base.copy!

### CODE REVIEW

**Comment by AmanDoesntCode** [comment]
For some reason test x86_64-w64-mingw32 bash .buildkite/utilities/test_julia.sh is failing in the tests by buildkite. i686 works perfectly fine. Since this is my **first PR** I would really appreciate it if a reviewer might help me out. I closed the same PR once before because of some unwanted commits for this PR. I am enjoying the spirits over here and am looking forward to develop myself over here.

**Review by AmanDoesntCode — COMMENTED** [review]
@wookay what must I do ? To make the change happen. Kindly help me... I am really new to contributing.

**Comment by AmanDoesntCode** [comment]
Hey @shashi what must I do ? To make the change happen and add these tests. Kindly help me out here... I am really new to contributing. Is there something I overlooked/misunderstood from the contribution pathways ?

**Comment by vtjnash** [comment]
Looks like there was just some issues with the buildkite runner that don't impact your PR. Could you move these to a different test file, such as `test/copy.jl`? It doesn't look like these have anything to do with the Future's module.

**Comment by AmanDoesntCode** [comment]
Sure, would do it ASAP.

**Comment by AmanDoesntCode** [comment]
@vtjnash Seems like there already is one copy.jl that is much more able in testing the copy! but for different issues do I still add these basic tests for it ?

**Comment by vtjnash** [comment]
Yes, just append them to the end of it. Side question: how did you determine these needed tests, and is there a relevant issue that should be closed now?

**Review by inkydragon — COMMENTED** [review]
The tests for `copy!` are generally associated with the type of input, which is probably why `copy.jl` does not contain tests for `copy!`.

https://github.com/JuliaLang/julia/blob/af90dac17a2f59e68f6f6f69f48a7d21270909a7/test/abstractarray.jl#L1077-L1094
https://github.com/JuliaLang/julia/blob/af90dac17a2f59e68f6f6f69f48a7d21270909a7/test/dict.jl#L1420-L1430
https://github.com/JuliaLang/julia/blob/af90dac17a2f59e68f6f6f69f48a7d21270909a7/test/sets.jl#L179-L190

**Comment by AmanDoesntCode** [comment]
Ok then I feel like it still is kind of needed to be added in the copy.jl since there is no unit display of the usecase through tests. @inkydragon

**Comment by AmanDoesntCode** [comment]
@vtjnash I have appended the same code in copy.jl and have emptied the future test folder. Do tell me if I have to do anything else. 

Answering the side note : 
I was learning the documentation and saw the comment that says "This function has moved to Base with Julia 1.1, consider using copy!(dst, src) instead. Future.copy! will be deprecated in the future." So it just appeared to me that there should be test cases to check out the basic functioning of the method.

**Comment by vtjnash** [comment]
It looks like @inkydragon is correct that these methods appear to already be covered in the original PR: https://github.com/JuliaLang/julia/pull/29178

Is there anything there that this covers that isn't already covered? It doesn't look like we need these added tests

**Comment by AmanDoesntCode** [comment]
@vtjnash Absolutely ! The tests for a language must be concise and not confusing. I do not see any issues being covered here. I am really grateful to all of the reviewers to put their attention to my first PR towards Julia. I will try to be more aware next time.

**Pull request closed without merging**
