### PR TITLE
Fix triu/tril for partly initialized matrices

### PR DESCRIPTION
**Pull request by jishnub**
This fixes
```julia
julia> using LinearAlgebra, StaticArrays

julia> M = Matrix{BigInt}(undef, 2, 2); M[1,1] = M[2,2] = M[1,2] = 3;

julia> S = SizedMatrix{2,2}(M)
2×2 SizedMatrix{2, 2, BigInt, 2, Matrix{BigInt}} with indices SOneTo(2)×SOneTo(2):
   3     3
 #undef  3

julia> triu(S)
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex
   @ ./essentials.jl:907 [inlined]
 [2] getindex
   @ ~/.julia/packages/StaticArrays/MSJcA/src/SizedArray.jl:92 [inlined]
 [3] copyto_unaliased!
   @ ./abstractarray.jl:1086 [inlined]
 [4] copyto!(dest::SizedMatrix{2, 2, BigInt, 2, Matrix{BigInt}}, src::SizedMatrix{2, 2, BigInt, 2, Matrix{BigInt}})
   @ Base ./abstractarray.jl:1066
 [5] copymutable
   @ ./abstractarray.jl:1200 [inlined]
 [6] triu(M::SizedMatrix{2, 2, BigInt, 2, Matrix{BigInt}})
   @ LinearAlgebra ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/LinearAlgebra/src/generic.jl:413
 [7] top-level scope
   @ REPL[11]:1
```
After this PR:
```julia
julia> triu(S)
2×2 SizedMatrix{2, 2, BigInt, 2, Matrix{BigInt}} with indices SOneTo(2)×SOneTo(2):
 3  3
 0  3
```
Only the indices that need to be copied are accessed, and the others are written to without being read.

~~Something similar needs to be done for the `triu(A, k)` and `tril(A, k)` methods as well.~~

### CODE REVIEW

**Review by dkarrasch — DISMISSED** [review]

**Comment by dkarrasch** [comment]
What about

```julia
triu([randn(2,2) for _ in 1:2, _ in 1:2])
```

? Matrices whose eltype doesn't admit a `zero` method, but whose elements admit one.

**Comment by jishnub** [comment]
Oops, `triu!` does require the matrix to be initialized. Need to figure out the order of `triu!` and `copytrito!`, largely because `similar(::SymTridiagonal)` returns a `SymTridiagonal`, but this doesn't support `setindex!`. Perhaps this should be modified to return a `Tridiagonal` instead?

**Comment by dkarrasch** [comment]
Is this ready?

**Comment by jishnub** [comment]
Yes, this is ready

**Review by dkarrasch — APPROVED** [review]

**Pull request merged**
