### PR TITLE
Do not leave -1 in the backtrace if unwind fail.

### PR DESCRIPTION
**Pull request by yuyichao**
It is now used as a special marker and can corrupt the GC.

### CODE REVIEW

**Comment by vtjnash** [comment]
What’s the gc got to do with this? We already know this file generates best-effort results and is usually pretty unreliable.

**Comment by yuyichao** [comment]
`-1` is a marker telling the GC that the next pointer is an object.

https://github.com/JuliaLang/julia/blob/daa58bb183799aac11f069e5b17a689e7fb8ec1b/src/gc.c#L2447
https://github.com/JuliaLang/julia/blob/daa58bb183799aac11f069e5b17a689e7fb8ec1b/src/stackwalk.c#L158
etc.

**Comment by vtjnash** [comment]
What is bt2?

**Comment by yuyichao** [comment]
A `Vector{Any}` since there's no way to directly represent this mixing with the current array.

**Review by Keno — APPROVED** [review]

**Pull request merged**
