### PR TITLE
track already loaded modules

### LINKED ISSUE #12558: Segfault for @everywhere importall/using
When using the following code (in a file `funcd.jl`):
```jl
  module funcd
  using Compat

  export len, range

  len(a) = length(a)
  len{T,N}(a::AbstractArray{T,N}) = size(a,N)

  import Base.range
  range(a) = 1:len(a)

  end
```
by running it with `julia run.jl` with a `run.jl` file containing:
```jl
addprocs(3)
@everywhere importall funcd
```
results in a segfault: 
```
WARNING: replacing module funcd
WARNING: replacing module funcd
WARNING: replacing module funcd
exception on exception on WARNING: Method definition range(Any) in module funcd at /Users/rene/BTSync/code/git/funcd/funcd.jl:10 overwritten in module funcd at /Users/rene/BTSync/code/git/funcd/funcd.jl:10.
4: 3:
signal (11): Segmentation fault: 11
mtcache_hash_lookup at /Users/rene/local/devjulia/src/gf.c:152
jl_apply_generic at /Users/rene/local/devjulia/src/gf.c:1630
showerror at replutil.jl:72
showerror at replutil.jl:83
jlcall___showerror#160___21217 at  (unknown line)
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
julia_showerror_21216 at  (unknown line)
jlcall_showerror_21216 at  (unknown line)
showerror at replutil.jl:91
julia_showerror_21214 at  (unknown line)
jlcall_showerror_21214 at  (unknown line)
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
anonymous at client.jl:88
with_output_color at util.jl:330
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
display_error at client.jl:86
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
run_work_thunk at multi.jl:651
run_work_thunk at multi.jl:657

signal (11): Segmentation fault: 11
jlcall_run_work_thunk_21149 at  (unknown line)
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
anonymous at task.jl:11
jl_apply at /Users/rene/local/devjulia/src/task.c:233
mtcache_hash_lookup at /Users/rene/local/devjulia/src/gf.c:152
jl_apply_generic at /Users/rene/local/devjulia/src/gf.c:1630
showerror at replutil.jl:72
showerror at replutil.jl:83
jlcall___showerror#160___21221 at  (unknown line)
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
julia_showerror_21220 at  (unknown line)
jlcall_showerror_21220 at  (unknown line)
showerror at replutil.jl:91
julia_showerror_21218 at  (unknown line)
jlcall_showerror_21218 at  (unknown line)
jl_apply at /Users/rene/local/devjulia/src/gf.c:1658
anonymous at client.jl:88
with_output_color at util.jl:330
```
A git bisect points to 7207a8a43e076576d6d6a6161ac75d2ae3391a6e
```
commit 7207a8a43e076576d6d6a6161ac75d2ae3391a6e
Author: Amit Murthy <amit.murthy@gmail.com>
Date:   Wed Jun 10 21:20:12 2015 +0530

    added support for different topologies
```
When executing the following code directly (i.e. in the REPL):
```jl
  module funcd
  using Compat

  export len, range

  len(a) = length(a)
  len{T,N}(a::AbstractArray{T,N}) = size(a,N)

  import Base.range
 range(a) = 1:len(a)

 end
addprocs(3)
@everywhere importall funcd
```
the code passes. cc @amitmurthy

### PR DESCRIPTION
**Pull request by amitmurthy**
While looking in `loading.jl` in the context of https://github.com/JuliaLang/julia/issues/12558, noticed that global `package_loaded` was not being used and hence this PR.

Note that this does not fix https://github.com/JuliaLang/julia/issues/12558 , but I think it is required for proper synchronization anyways.

cc @vtjnash

### CODE REVIEW

**Comment by amitmurthy** [comment]
With the second commit, where I replaced `@spawnat` with `remotecall_fetch` and wait on async tasks, the segfault in #12558 goes away.  @rened could you test this on OSX?

I don't have an explanation for this - one difference is that the `@spawn` and `@async` macros call `localize_vars`.  I went ahead and also removed the use of `@async` macros from `@everywhere` and `preduce` (`@parallel`).

cc: @vtjnash , @JeffBezanson

**Comment by vtjnash** [comment]
> I think it is required for proper synchronization anyways.

This introduces more state into `require` which may cause issues with workspace and reload and is not required for #12558. I think the solution there is to better synchronize the implementation of require with the definition of `import`, not to add additional discrepancies.

**Comment by rened** [comment]
@amitmurthy Your commit passes for me, but strangely I can't reproduce the crash from #12558 on OSX - but as it comes from a race situation this can happen...

**Comment by amitmurthy** [comment]
@vtjnash the current code intends to synchronize using `package_locks`, but since the  `finally` block removes the `Condition` variable from `package_locks`, we will need `package_loaded` to just correct the current implementation, no?

**Comment by vtjnash** [comment]
i suspect this solution may be a special case of https://github.com/JuliaLang/julia/issues/12381#issuecomment-127182636, where making it less efficient (e.g by calling sleep) was able to hide the bug

i put the current lock there to prevent require from recursively loading the same module, although I would really prefer to make it an error to call `import Module` on something that doesn't define Module (instead of a warning). then the only state is `isdefined(Main, mod)` which is both easy to test and common across the implementation of `import` in the C code and in the Julia code (aka require).

**Comment by amitmurthy** [comment]
@rened could you test with varying number's of `addprocs(n)` ? In my local tests different number of workers caused slightly different errors.

@vtjnash replacing the `@spawnat`/`wait` combination with a single `remotecall_fetch` actually makes it a bit more efficient - that may be hiding the bug too.

**Comment by vtjnash** [comment]
> replacing the @spawnat/wait combination with a single remotecall_fetch actually makes it a bit more efficient

but you didn't actually replace it with a single remotecall_fetch, you just moved the `@spawnat` / `wait` (aka `wait(schedule(Task( () -> ... )))` to the local process

**Comment by amitmurthy** [comment]
No, `@spawnat` returns a `RemoteRef`, so `@spawnat`/`wait(::RemoteRef)` is two network calls. This has been replaced with an equivalent `wait(schedule(Task( () -> remotecall_fetch(...) )))`. The `remotecall_fetch` is a single network call.

**Comment by amitmurthy** [comment]
I'll merge this in a short while. It fixes the current implementation and speeds it up a bit too.

**Comment by vtjnash** [comment]
please don't merge this right now. it needs more review, since i don't think it fixes either issue and it adds more state which is likely to be undesirable and may cause other issues.

**Comment by amitmurthy** [comment]
OK. Will wait. I did find it more stable in my tests though.

**Comment by rened** [comment]
@amitmurthy I no longer get a crash for `@everywhere using JSON`, neither on current master (4d8ca6b) nor on this PR. Testen on OSX with `./julia -e "@everywhere using JSON" -p X` for X in 1:5

**Comment by amitmurthy** [comment]
Closing in view of alternate solutions proposed.

**Pull request closed without merging**
