### PR TITLE
Type docs

### PR DESCRIPTION
**Pull request by MikeInnes**
``` julia
julia> "This is a type"
       type Foo
           "`x` repesents the Fooness of the Foo"
           x::Int
           "`y` is magical"
           y
       end

help?> Foo
search: Foo floor ifloor pointer_from_objref OverflowError RoundFromZero

  This is a type

help?> Foo.x
  x repesents the Fooness of the Foo

help?> Foo.y
  y is magical
```

Kinda neat that we can do this without any more parser changes, I think.

### CODE REVIEW

**Comment by ScottPJones** [comment]
Nice, even though having it before messes up my mind, as every other language it is after (usually in a comment on the same line), but really good to have the ability to document type members! :+1:

**Comment by simleb** [comment]
Should `?Foo` show a list of fields as well, to facilitate discovery? (yes I know about `names`)

**Comment by johnmyleswhite** [comment]
Hard to say. There's an argument that the fields are an implementation detail that shouldn't be exposed to end users.

**Comment by simleb** [comment]
What about a list of _documented_ fields then? That seems like a great compromise!

**Comment by ScottPJones** [comment]
Hmmm... I still want a way of really making the fields themselves private (and the documentation also), but still have it available for internal developers.  (at my old work, we used a flag, so that our equivalent of class documentation would just show public interfaces, classes, methods, properties, unless the "internal developer" flag was set).

**Comment by ScottPJones** [comment]
and if I did `?Foo`, if it is a public type, then display all the fields, with just names and types, even if no documentation), if not, maybe just say that it is a private type (you might even want to keep any non-exported types/functions/method names in a module hidden, if the module itself is marked somehow "private".
```julia
julia> type foo
       bar::Int
       silly
       end

help?> foo
INFO: Loading help data...
DataType   : foo (constructor with 2 methods)
  supertype: Any
  fields   : (:bar,:silly)
```
Currently, `?` doesn't tell you the types of the fields, just the names.

**Pull request merged**
