### PR TITLE
replace broadcast with map in sparse binary op definitions

### PR DESCRIPTION
**Pull request by Sacha0**
A few elementwise operations over pairs of sparse matrices (e.g. `+`, `min`) are implemented as short children of `broadcast` preceded by a (same-)shape check. This pull request reimplements those operations in terms of `map`. Best!

~~Note: This pull request should not pass CI prior to rebasing on #19518.~~

### CODE REVIEW

**Comment by Sacha0** [comment]
Rebased with #19518 in. Should be in shape if CI approves. Best!

**Comment by Sacha0** [comment]
Absent objections or requests for time, I plan to merge this PR Sunday morning PST. Best!

**Comment by tkelman** [comment]
are mismatched-shape cases covered by existing tests?

**Comment by Sacha0** [comment]
> are mismatched-shape cases covered by existing tests?

The checks/throws in `map` and `broadcast` are. But from a brief look at `test/sparse/sparse.jl`, those checks/throws are not exercised via the operations touched in this pull request. Updating with tests. Thanks!

**Comment by Sacha0** [comment]
Now with tests of shape checks. Thanks!

**Comment by tkelman** [comment]
lgtm. the sparse broadcast tests have some loops that go through the special cases for 1-by-n and n-by-1, right? those might also be good places to throw in some test_throws to make sure we don't unintentionally change anything unexpected

**Comment by Sacha0** [comment]
> the sparse broadcast tests have some loops that go through the special cases for 1-by-n and n-by-1, right? those might also be good places to throw in some test_throws to make sure we don't unintentionally change anything unexpected

Do you mean adding tests along the lines of [these tests for the generic code](https://github.com/JuliaLang/julia/blob/ded22594ec4f4ec83d40159b3a181ca5f90915ba/test/sparse/sparse.jl#L1828) to e.g. [these tests for the binary-specialized code](https://github.com/JuliaLang/julia/blob/ded22594ec4f4ec83d40159b3a181ca5f90915ba/test/sparse/sparse.jl#L1098)? If so, absolutely, though in a separate PR? Thanks!

**Comment by tkelman** [comment]
sure, as long as it doesn't get forgotten. if these operations mistakenly went through the broadcast code path I don't think mismatched size square inputs would be enough to tell the difference between broadcast and map, since both would throw an error.

**Comment by Sacha0** [comment]
Ah, I see your concern now. Will update with sharper tests. Thanks!

**Comment by Sacha0** [comment]
The revised tests should differentiate between implementing these operations as `map` versus `broadcast`. (`map` should throw and pass, `broadcast` should not.)

Realization re. the more general sparse broadcast shape check testing discussion above: I condensed the entry points for sparse broadcast into two methods (in which lie the shape checks) in #19518. The tests for the generic code linked above exercise those methods' shape checks, thereby covering the shape check code for all sparse broadcast cases. Sufficient, or should we do more? Thanks!

**Review by tkelman — APPROVED** [review]

**Comment by tkelman** [comment]
mac travis freeze unrelated, the added tests passed there

**Comment by Sacha0** [comment]
Thanks for reviewing / merging!

**Pull request merged**
