### PR TITLE
prevent order dependency if an extension is loaded or not

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #https://github.com/JuliaLang/julia/issues/49656

There were two issues:

- The `gid.ntriggers -= 1` when inserting extension triggers happened unconditionally but needs to be consistent with the `extid.ntriggers -= 1` in the extension callbacks.
- The `extid.ntriggers += 1` that happened when a trigger could not be loaded doesn't make sense to me. If such a trigger is loaded we will never load the extension and there should never be a reason to bump this value.

cc @topolarity

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
The combination of statefullness seems awkward, since the conditionals are evaluated at such widely different points in time, against potentially entirely different environments. And then we don't even know if it needs to load that, just that it is a trigger of it

**Comment by KristofferC** [comment]
I agree, I must say liked the first implementation of extension loading more (before https://github.com/JuliaLang/julia/pull/48513) where the check of all the triggers happened in one instant.

**Comment by vtjnash** [comment]
The trouble with that one was it was re-happening constantly, instead of only at one instant. Preferably, it seems we need to find the right middle ground where it checks the is-now-loaded condition only once (when it loads), but re-checks the is-all--deps-in-environment every time that condition might have changed.

**Comment by KristofferC** [comment]
I'm gonna close this in favour of https://github.com/JuliaLang/julia/pull/49701 where this failure mode doesn't exist anymore.

**Pull request closed without merging**
