### PR TITLE
Clarifying the need for identical values

### PR DESCRIPTION
**Pull request by hpoit**

### CODE REVIEW

**Comment by KristofferC** [comment]
Pointing to an external blog for docmentation from inside the official Julia manual is not so good. If things are lacking in the manual, they should be described there,

**Comment by tkelman** [comment]
We have lots of links to blogs in the manual.

**Comment by KristofferC** [comment]
Yes

**Comment by hpoit** [comment]
I'm sorry Kris, you're right, that was lazy. But now that tkelman brought it up, perhaps putting John's link right after that sentence would be very useful for newcomers. The deleted repo was probably a fork, sorry about that too.

**Pull request closed without merging**
