### PR TITLE
Print filename and line number for deprecation warnings

### LINKED ISSUE #11050: Deprecation warning for global scope does not have filename/lineno info
When a deprecated syntax/function is used in global scope, the printed warning is not very helpful to find where the usage is.

Script
```julia
int32(1)

function f()
    int64(1)
end

f()

error()
```

Printed:
```
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in int32 at ./deprecated.jl:31
 in include_from_node1 at ./loading.jl:129
WARNING: int64(x) is deprecated, use Int64(x) instead.
 in int64 at ./deprecated.jl:31
 in f at /home/yuyichao/tmp/test_deprecated.jl:6
 in include_from_node1 at ./loading.jl:129
ERROR: LoadError: 
 in error at ./error.jl:20
 in include_from_node1 at ./loading.jl:129
while loading /home/yuyichao/tmp/test_deprecated.jl, in expression starting on line 11
```

As shown above, the `error()` in global scope prints a similar backgrace but the "while loading" message can be used to figure out where the error is generated.

Also, the `loading.jl` in the backtrace printed is quite useless and would be nice it it can be suppressed when printing the backtrace...

### PR DESCRIPTION
**Pull request by yuyichao**
Added one c global variable so #10421 needs to be updated accordingly.

@vtjnash 
Fix #11050

### CODE REVIEW

**Comment by vtjnash** [comment]
lgtm

**Comment by yuyichao** [comment]
Hmm, somehow the backtrace printed is also longer now.

**Comment by yuyichao** [comment]
> Hmm, somehow the backtrace printed is also longer now.

Ahh, everything is fine... This happens because my system installation has debug symbol striped (into a debug package) while the version I am testing is not striped...

I bet it treat those functions as `fromC` when it fails to get the symbol name....

**Comment by yuyichao** [comment]
So with a striped `sys.so`, this is the output of the script I had in #11050 .

```julia
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in int32 at ./deprecated.jl:33
 in include_from_node1 at ./loading.jl:134
while loading /home/yuyichao/tmp/test_deprecated.jl, in expression starting on line 3
WARNING: int64(x) is deprecated, use Int64(x) instead.
 in int64 at ./deprecated.jl:33
 in f at /home/yuyichao/tmp/test_deprecated.jl:6
 in include_from_node1 at ./loading.jl:134
while loading /home/yuyichao/tmp/test_deprecated.jl, in expression starting on line 9
ERROR: LoadError: 
 in error at ./error.jl:22
 in include_from_node1 at ./loading.jl:134
while loading /home/yuyichao/tmp/test_deprecated.jl, in expression starting on line 11
```

**Comment by lindahua** [comment]
+1

**Comment by timholy** [comment]
This will be a very nice improvement!

**Comment by tkelman** [comment]
this is great, thanks!

**Comment by tkelman** [comment]
We should probably add a test for `depwarn` in `test/misc.jl`, I don't see one there yet

**Pull request merged**
