### PR TITLE
Remove Errno module.

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
`errno_h.jl` is autogenerated...

**Comment by quinnj** [comment]
ah, good to know.

**Comment by tkelman** [comment]
so we should leave the include instead of hardcoding the values, which might also be platform-dependent

**Comment by quinnj** [comment]
Updated.

**Comment by ihnorton** [comment]
+1. (timeouts look unrelated)

**Pull request merged**
