### PR TITLE
Move searchsorted* functions to SortedSearch stdlib module

### LINKED ISSUE #24883: What to do with searchsorted* functions
As part of https://github.com/JuliaLang/julia/issues/10593, I have tried to find a way to unify `searchsorted`, `searchsortedfirst` and `searchsortedlast` with the rest of `find*` functions. In [the Search & Find Julep](https://github.com/JuliaLang/Juleps/blob/master/Find.md#particular-cases), I suggested replacing them with `find*` methods dispatching on a `Sorted`/`SortedVector` wrapper which would indicate that the input vector is sorted (see also https://github.com/JuliaCollections/DataStructures.jl/pull/290 for a similar but more powerful type).

For `searchsorted` itself, this plan would work quite well. It could be replaced with `find(equalto(needle), Sorted(haystack))`, which would just call a specialization of `find` which would return a range instead of a `Vector`, while still following the generic `AbstractArray` API.

The situation is more complex for `searchsortedfirst` and `searchsortedlast`. I'll detail the problems for the former, knowing that they are equivalent for the latter.  `searchsortedfirst` returns "the first value in a greater than or equal to x, according to the specified order". With the introduction of the `Sorted` wrapper, the specified order is the one passed when constructing the wrapper, which indicates how the underlying vector is sorted. So far, so good. But what kind of predicate can we use to reflect this order?
- It would be natural to replace `searchsortedfirst(needle, haystack)` with `findfirst(greaterthan(needle), Sorted(haystack))`, but then `greaterthan` cannot have any meaning on its own: it would depend on the order used by `haystack`, and "greater" could even mean "lower" if `rev=true`.
- We could use `findfirst(sortedafter(needle), Sorted(haystack))`, which would better reflect that the predicate has no intrinsic meaning. But then we lose the generality of the syntax: it cannot be used on an unsorted vector to find the first value greater than `x`, which defeats the idea of unifying functions.

Then there are other subtleties, but these are less serious:
- `greaterthan` should actually be `greaterthanorequalto` and `sortedafter` be `sortedatorafter` to accurately reflect the behavior of the function.
- `searchsortedfirst` has an internal variant which allow passing a start and end index indicating the range to be searched, but `findfirst` only accepts a start index. This feature is used by the sparse matrix code. It could be replaced with array views, or we could just have a method which is more flexible than the other `findfirst` methods.
- `searchsortedfirst(x)` returns `length(x)+1` when no match is found, while `findfirst` currently returns `0`, and may well return `nothing` in the future (https://github.com/JuliaLang/Juleps/issues/47). This doesn't sound like an issue, as the caller can easily replace `0` or `nothing` with `length(x)+1` without a significant performance cost if needed.

I would appreciate any help, especially from people who use these functions (I don't). If fixing this in time for 0.7 is too complex, we could unexport these functions (which are needed for sparse matrices), and move them e.g. to SortingAlgorithms.

### PR DESCRIPTION
**Pull request by nalimilan**
Keep them under `Base.Sorted` but unexported, since they are used in a few places in Base, in particular for sparse vectors and matrices.

Fixes  #24883.

### CODE REVIEW

**Comment by KristofferC** [comment]
In my opinion this feels way to specific to be a stdlib module.

**Comment by nalimilan** [comment]
Yeah, it's not a lot of functionality for a single module. So would you recommend moving them to a package (new or existing) instead?

**Comment by JeffBezanson** [comment]
Why do you hate these functions so much? :)
I think we should leave them alone.

**Comment by nalimilan** [comment]
It's just that they don't follow the naming pattern used for all `find*` functions, so they look really out of place (after #24673). Why use the term "search" when the API consistently uses "find" in other areas?

There's also the possibility of merging them with standard `find*` functions using a `Sorted` wrapper, whose interest hasn't been discussed yet.

**Comment by KristofferC** [comment]
If it is "just that they don't follow the naming pattern" can't they just be renamed then?

As to a sorted wrapper, if it is only used for dispatch, it seems to not solve any concrete problem but add additional ones.

**Comment by nalimilan** [comment]
Yes, renaming them as another option. (Note that I had initially made this PR in the perspective of merging all breaking changes around December 15th, considering that it was simpler to move things to sdlib when we didn't have time to discuss these issues in depth. But since we took that design discussion time, it may not be the most appropriate action now.)

**Comment by nalimilan** [comment]
I've opened https://github.com/JuliaLang/julia/pull/25414 implementing the less radical approach of renaming these functions.

**Pull request closed without merging**
