### PR TITLE
Include `HermOrSym` in character-based `mul!` dispatch

### PR DESCRIPTION
**Pull request by dkarrasch**
This extends #49806 to `HermOrSym` types. With this PR, we are down to 33 `mul!` methods. Can't wait to have -5 methods! 🤣 

This is in some parts a bit ugly due to the re-wrapping, but that happens only in the very generic paths, so shouldn't affect the fast paths.

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/49865#issuecomment-1553348969) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/aa13925_vs_ce3909c/report.md).

**Comment by dkarrasch** [comment]
@nanosoldier `runbenchmarks("linalg", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/49865#issuecomment-1553567337) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/94abfd6_vs_c99d839/report.md).

**Comment by vtjnash** [comment]
Just wanted to say that this work to get rid of all those ugly buggy slow Union dispatch has been awesome!

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/49865#issuecomment-1553348969) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/2fe6f4d_vs_3583fae/report.html).

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["MaskedArrays", "UCX", "POMDPTools", "DifferentialForms", "ExponentialUtilities", "Test", "MendelImpute", "TrajectoryOptimization", "HarmonicBalance", "DataDrivenLux"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/49865#issuecomment-1555885782) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9fe30f5_vs_3583fae/report.html).

**Pull request merged**
