### PR TITLE
Explain the usage of `[av skip]` tag.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Related to trivial edits on documentation source files. Mentioned in https://github.com/JuliaLang/julia/pull/11766#issuecomment-113630198.

### CODE REVIEW

**Comment by yuyichao** [comment]
Shouldn't this PR be a good example to use `[av skip]` ?

**Comment by Ismael-VC** [comment]
@yuyichao Indeed it is, but I wanted to make sure `av skip` is part of the title in this one, not just another intended skip, but yeah you are right! :smile:

**Comment by yuyichao** [comment]
I think you can put `[av skip]` in the commit log.

**Comment by tkelman** [comment]
This doesn't need to be in the title, it can be anywhere in the commit message. I'd rather people put it at the end of the extended message a few lines down, rather than on the title line

**Comment by Ismael-VC** [comment]
Ok I didn't know that, I will change it to suggest using the extended message instead.

**Comment by tkelman** [comment]
I would ask you to squash, but that's another thing github's web interface doesn't allow you to do. Thanks for this, I should've added some notes about this here a while ago.

**Comment by Ismael-VC** [comment]
@tkelman certainly after learning GitHub's web interface limitations today, I will try to use it only for the most trivial of changes, typos perhaps and nothing more.

I'm always on the move at work, so my idea was to use my commuting times in a better (julian) way.

**Comment by tkelman** [comment]
It's cool, running git from the command line doesn't work so well from a phone, so contribute however you can and we'll manage. I should get some practice merging a PR manually myself.

**Comment by mbauman** [comment]
This is something that's tripped me up, too, and it's not very obvious or intuitive.  My shell scripting is really rusty, but is this something we can do more automatically?  Something like:

```txt
    # If not on master and there are only doc changes, only check whitespace
    - if [ `git rev-parse --abbrev-ref HEAD` != "master" ] && git diff --name-only origin/master | grep -v 'doc/'
        make check-whitespace || exit 1
        exit 0
      fi
```

It would only happen on PRs and feature branches, but that would handle most cases.  Or could we maybe enable a custom `[doc]` tag?

**Comment by tkelman** [comment]
I think this came up a few times before (#10577 and elsewhere). Might work? Or we could filter CI webhooks and commit contents through buildbot (which has some tools for this purpose) before forwarding them to travis/appveyor.

**Comment by Ismael-VC** [comment]
@mbauman that functionality would be very useful. :+1: 

Either way I can imagine myself editing the doc files from the web interface, using a [WIP] tag in the title, and [ci skip] on the description, so that when I get home I can go and squash everything from the command line in just one tidy commit that passes the tests.

I think this way I could focus on editing the docs without disrupting anyone else workflow.

**Comment by tkelman** [comment]
I squashed and pushed in 8bc1b8ebdf0ed1bddb5795b165706829c15c3b0d. Thanks for this!

**Comment by milktrader** [comment]
If we had our own git cheat sheet in the docs, it would be awesome.

**Comment by tkelman** [comment]
I added one a while back - https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#git-recommendations-for-pull-requests

but it could always use more tips

**Comment by milktrader** [comment]
Oh cool, no more SO searches

**Comment by milktrader** [comment]
Next project, expand the squash commits section and make it our own.

**Comment by timholy** [comment]
There is http://docs.julialang.org/en/latest/manual/packages/#making-changes-to-an-existing-package, which includes squash info.

**Comment by milktrader** [comment]
@timholy what do you think about updating that section with command line examples such as this at the end of this issue?
https://github.com/JuliaLang/julia/pull/11716

I find it easiest to follow along with command line examples and often find myself going back to this
http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by timholy** [comment]
I'm all in favor of improving documentation, and if existing examples are not good enough they should definitely be improved.

**Pull request closed without merging**
