### PR TITLE
Fix portability issue

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by albap** [comment]
@yuyichao 
Good to go?

**Comment by yuyichao** [comment]
Please update the existing PR instead of opening a new one.

Otherwise, LGTM.

P.S. Expect possible backtrace related test failure.

**Comment by albap** [comment]
One of the tests failed.
What should we do about it?

**Comment by yuyichao** [comment]
The OSX travis is currently broken due to homebrew update.

**Comment by albap** [comment]
Can it be merged then?

**Comment by tkelman** [comment]
probably yes, but we usually like to leave things open for review longer than a few hours. contributors are spread across all time zones.

**Comment by carnaval** [comment]
Just echoing sentiment from the other PR, I'm afraid keeping the build working is gonna be the least of your worries. It would be great for julia to actually work with another libc, and certainly supporting two will make it a lot easier to e.g. add support for a third one. I just don't think that it's realistic to expect it to work with all libc by default given how some pieces are dependent on implementation defined details.
Maybe I'm just too pessimistic about that. In any case, when you get it to work, definitely add a CI bot for it as it's the only way to keep it working reliably.

**Comment by tkelman** [comment]
should be totally doable to run in an alpine docker container using something like circle ci or drone or shippable, etc. I'd hesitate to add another travis job to our matrix just out of queue time concerns, but something that runs in parallel (even just nightly) would be fine. That's how I check that julia stays mostly source compatible with MSVC, I rebase a branch and run it on my fork's appveyor every day or two.

**Pull request merged**
