### PR TITLE
fix #9770 (type inference error)

### LINKED ISSUE #9770: type inference bug for multi-cycle functions
I think I might have stumbled across a bug, possibly in type inference though I'm not sure.

I'd expect that running the following would print "ok" 3 times, instead it prints "ok" once then two blank lines.

```
function printit(x, _)
    if _true()
        z = id(x)
        print("")
        println(z)
        :sym
    elseif _false()
        printit("ok", :foo)
    end
end

function id(x)
    if _false()
        printit(unknowntype, :foo)
    else
        x
    end
end

_false() = false
_true() = true

printit("ok", "foo")
printit("ok", :foo)
printit("ok", :foo)
```

Making any one of the following changes results in the expected output. Perhaps this will help point someone who understands Julia's internals at the cause of the unexpected behavior.

1. Remove the `printit("ok", "foo")` line. (Results in "ok" been printed twice as expected.)
2. Remove the `:sym` line.
3. Remove the `print("")` line.
4. Remove either of the `if` expressions leaving only the non-redundant branch.
5. Replace `unknowntype` with `unknowntype::ASCIIString`.
6. Remove either of the calls to `printit` within `printit` or `id`.

I've also just noticed that replacing `println(z)` with `println(z==nothing ? "nothing" : z)` causes a seg fault.

All of this is happening with the latest nightly build, details below. I get very similar results using v0.3.4, but not the seg fault.

```
Julia Version 0.4.0-dev+2689
Commit a418672 (2015-01-14 10:05 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Core2)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by vtjnash**
here's the segfault-enhanced test case for this:

```
x9770 = false
function f9770(x)
    if x9770
        g9770(:a, :foo)
    else
        x
    end
end
function g9770(x,y)
   if isa(y,Symbol)
       f9770(x)
   else
       g9770(:a, :foo)
   end
end
@test g9770(:a, "c") === :a
@test g9770(:b, :c) === :b
```

@JeffBezanson i don't like adding all of the `typeinf` function to the "don't-infer" list, but it seemed to suffice to get through type inference

### CODE REVIEW

**Comment by vtjnash** [comment]
(also, with this change, we never cache `g9770(::Symbol,::Symbol)`, which also seems incorrect)

**Comment by vtjnash** [comment]
here's my newest attempt at breaking it:
```
julia> begin
                              @noinline _true() = true
                              @noinline _false() = false
                              function f(x)
                                 if _false()
                                   g(:a, :foo)
                                 else
                                   x
                                 end
                              end
                              function g(x,y)
                                if isa(y,Symbol)
                                  f(x)
                                elseif _true()
                                  h(g(x,y))
                                end
                              end
                              h(x::Symbol) = Int
                              h(x::ASCIIString) = Float32
                              h(x::Any) = Function
                            
       end
h (generic function with 3 methods)

julia> @code_typed g(:a, "c")
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x,:y], Any[Any[],Any[Any[:x,Symbol,0],Any[:y,ASCIIString,0]],Any[]], :(begin  # none, line 12:
        unless $(Expr(:call1, :isa, :(y::ASCIIString), :Symbol)) goto 0 # line 13:
        return $(Expr(:call1, :f, :(x::Symbol)))
        goto 2
        0:  # line 14:
        unless $(Expr(:call1, :_true)) goto 1 # line 15:
        return h($(Expr(:call1, :g, :(x::Symbol), :(y::ASCIIString))))::Union(Type{Int64},Type{Float32},Type{Function})
        goto 2
        1: 
        return
        2: 
    end::Any))))

julia> @code_typed g(:a, :c)
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x,:y], Any[Any[],Any[Any[:x,Symbol,0],Any[:y,Symbol,0]],Any[]], :(begin  # none, line 12:
        unless isa(y::Symbol,Symbol)::Bool goto 0 # line 13:
        return f(x::Symbol)::Any
        goto 2
        0:  # line 14:
        unless _true()::Bool goto 1 # line 15:
        return h(g(x::Symbol,y::Symbol)::Any)::Union(Type{Int64},Type{Float32},Type{Function})
        goto 2
        1: 
        return
        2: 
    end::Any))))

julia> @code_typed g(:a, "c")
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x,:y], Any[Any[],Any[Any[:x,Symbol,0],Any[:y,ASCIIString,0]],Any[]], :(begin  # none, line 12:
        unless isa(y::ASCIIString,Symbol)::Bool goto 0 # line 13:
        return f(x::Symbol)::Any
        goto 2
        0:  # line 14:
        unless _true()::Bool goto 1 # line 15:
        return h(g(x::Symbol,y::ASCIIString)::Any)::Union(Type{Int64},Type{Float32},Type{Function})
        goto 2
        1: 
        return
        2: 
    end::Any))))

julia> @code_typed f(:a)
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x], Any[Any[],Any[Any[:x,Symbol,0]],Any[]], :(begin  # none, line 5:
        unless _false()::Bool goto 0 # line 6:
        return g(:a,:foo)::Any
        goto 1
        0:  # line 8:
        return x::Symbol
        1: 
    end::Any))))
```

**Comment by tkelman** [comment]
Is this causing appveyor to time out with a higher-than-usual probability? OSX Travis too?

**Comment by vtjnash** [comment]
yes, even with the above patch now included, it significantly increases build times

**Comment by JeffBezanson** [comment]
Rebased. But yes, for me this took the sysimg build time (starting with inference0) from 3 minutes to 4 minutes.

**Comment by vtjnash** [comment]
that's actually not a bad as I feared. initially i think this was at least doubling the build time (appveyor went from 20minutes to > 40 minute). is it worthwhile to switch inference to a queue instead of recursion to do the much faster fix for this while we wait for the green-fairy (which i've been told already handles this case)?

**Comment by vtjnash** [comment]
also fixes #9222

**Comment by tkelman** [comment]
test? and more descriptive commit message?

**Pull request closed without merging**
