### PR TITLE
allow re-importing the same module from different owners

### LINKED ISSUE #28190: importing Compat.Libdl and Libdl gives an error
Even though `Compat.Libdl === Libdl`, Julia 0.7 gives:
```jl
julia> import Compat.Libdl

julia> import Libdl
ERROR: importing Libdl into Main conflicts with an existing identifier
```
Oddly enough, importing in the other order is fine:
```jl
julia> import Libdl

julia> import Compat.Libdl
```
This is causing an problem at JuliaPackaging/BinaryProvider.jl#90 …

I think we should fix this so that both orders work.  cc @ararslan

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #28190.

### CODE REVIEW

**Comment by vtjnash** [comment]
If it works, it seems like it should be correct. But maybe should also test the `->deprecated` flag, and see if we can clear that? (hopefully making is possible to type `Profile; using Profile`, although the error message that prints currently is different)

**Comment by stevengj** [comment]
`Profile; using Profile` works for me with no error (but a depwarn for the first statement), so I'm not sure what checking the `deprecated` flag would accomplish here?

**Comment by vtjnash** [comment]
I get:
```julia
julia> Profile; using Profile
WARNING: Base.Profile is deprecated, run `using Profile` instead
 in module Main
ERROR: importing Profile into Main conflicts with an existing identifier
```

But then every subsequent usage still gives:
```
julia> Profile 
WARNING: Base.Profile is deprecated, run `using Profile` instead
 in module Main
Profile
```

**Comment by stevengj** [comment]
With this PR?

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
No, before the PR. Does this fix it?

**Comment by stevengj** [comment]
@vtjnash, I now get
```jl
julia> Profile
WARNING: Base.Profile is deprecated, run `using Profile` instead
 in module Main
Profile

julia> using Profile

julia> Profile
WARNING: Base.Profile is deprecated, run `using Profile` instead
 in module Main
Profile
```
i.e. it doesn't give an error any more, but it doesn't clear the deprecated flag.

**Comment by stevengj** [comment]
I'll go ahead and merge this as it seems uncontroversial … additional changes to clear the deprecation flag can go into a separate PR.

**Pull request merged**
