### PR TITLE
Add patch to set PCRE2 stack size dynamically

### LINKED ISSUE #11668: PCRE2 test failure on OSX 10.10
Whenever I try to build Julia from scratch, I get an error while compiling PCRE2:

```
FAIL: RunTest
configure: summary of build options:

  Version:           GNU MP 6.0.0
  Host type:         x86_64-apple-darwin14.3.0
  ABI:               64
  Install prefix:    /Users/sabae/src/julia/usr
  Compiler:          clang -stdlib=libc++ -mmacosx-version-min=10.7 -m64
  Static libraries:  no
  Shared libraries:  yes

PASS: RunGrepTest
============================================================================
Testsuite summary for PCRE2 10.10
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
```

I'm looking into it, thought I would post it up here just in case someone else knows why this is.

### PR DESCRIPTION
**Pull request by staticfloat**
It limits itself to 16MB by default, which isn't enough on my mac mini, causing the test to segfault.  Fixes #11668.

### CODE REVIEW

**Comment by tkelman** [comment]
Seems homebrew isn't applying this? https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pcre2.rb

And yet OSX Travis was managing okay in #11622

**Comment by Keno** [comment]
I don't believe we would actually run the PCRE tests on travis, would we?

**Comment by tkelman** [comment]
Ah, right, not on OSX if we're using system pcre2 from brew. Thanks.

**Comment by staticfloat** [comment]
From my testing, it seems that this might be pretty compiler/OS version dependent.  I'm not sure what the default stack limit is on anything less recent than `OSX 10.10.3`, since all my computers are on that right now.  The limit of 16MB is also pretty close to what the actual requirement is, therefore different compilers might push the stack over or under the limit.

I took a brief look upstream, but didn't see anything related.  I guess I'll have to make an account on their issue tracker now.  :P

**Comment by staticfloat** [comment]
Reported to upstream [here](https://bugs.exim.org/show_bug.cgi?id=1642).

**Comment by tkelman** [comment]
Thanks, though file_not_specified_in_diff might be confusing.

I the patch step should run during the `pcre2-$(PCRE_VER)/configure` rule, right after extracting the tarball

**Comment by staticfloat** [comment]
Oh, I see, the bugtracker added `file_not_specified_in_diff` to the top..... weird.  I wasn't sure how to freehand the filename in there, and was too lazy to look it up.

**Comment by staticfloat** [comment]
For some reason, I thought `RunTests` was modified by `configure`.  It's not, good call.

**Comment by tkelman** [comment]
Hm, skimming the conversation at https://bugs.exim.org/show_bug.cgi?id=1642, would a better solution be to ensure we compile PCRE with `-O3`?

**Comment by staticfloat** [comment]
Yeah, I think that's the takeaway for us.

**Pull request merged**
