### PR TITLE
combinatorics coverage

### PR DESCRIPTION
**Pull request by Ismael-VC**
Test next for zero length permutation.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. Wouldn't it be more logical to use `collect(permutations([]))`, though?

**Comment by tkelman** [comment]
@nalimilan could you elaborate? how about testing both?

**Comment by nalimilan** [comment]
Why not testing both, but `next` is tested by `collect` AFAIK, and the current code depends on the implementation detail of what the iterator state is. We don't really care if it changes, as long as iteration (and thus `collect`) still works.

**Comment by Ismael-VC** [comment]
@nalimilan I will change it according to your suggestions. 

Today I will try to set up my fork of Julia to do work with CoverAlls. Since right now I don't get "immediate" feedback of whether a test actually covered some code-path or if it didn't. It seems the build-bots are only run once or twice a day.

That will make this quest easier!

**Comment by Ismael-VC** [comment]
Another option is to learn to use the "manual"command line coverage tools, but for the moment I'd rather use CoverAlls, and keep focusing in learning `git` and Julia instead of yet another command line tool.

**Comment by Ismael-VC** [comment]
@nalimilan Is this correct?

**Comment by nalimilan** [comment]
Looks good to me. AppVeyor failure is unrelated, I don't think it's worth restarting it.

@tkelman Is it fine with you?

**Comment by nalimilan** [comment]
Oh, and could you squash the commits?

**Comment by Ismael-VC** [comment]
@nalimilan squashing done!

**Comment by tkelman** [comment]
cancelled appveyor, it will probably time out due to #11818 - we can restart the build later if that gets fixed, though there's likely to be a worse-than-usual backlog for the next few days

**Comment by nalimilan** [comment]
I would just merge it, I don't see why it would fail on AppVeyor and not on Travis.

**Pull request merged**
