### PR TITLE
Sum of digits without memory allocations

### PR DESCRIPTION
**Pull request by simsurace**
Very simple but useful adaptation of `digits` that computes the sum of digits without allocating any memory, as opposed to `sum(digits(...))` which does.

### CODE REVIEW

**Comment by oscardssmith** [comment]
I'm not sure this is fundamental enough to be worth putting into `Base`. Is there a common use case for this?

**Comment by simsurace** [comment]
[See here](https://en.wikipedia.org/wiki/Digit_sum#Applications). Digit sums appear as algorithmic primitives in many different algorithms, and computing them without allocations can give significant performance benefits. If this is not suitable here, where should we put it instead?

**Comment by simsurace** [comment]
Good points. Also, I did not know about `count_ones`, so thanks for pointing that out. Indeed that is much faster than `sumdigits`.

**Comment by mcabbott** [comment]
Perhaps the doc string for `digits` wants something like ```See also: [`ndigits`](@ref), [`count_ones`](@ref).```

**Comment by jebej** [comment]
Wasn't there an issue about having `digits` be an iterator? I can't find it.

If we had instead an `Iterators.digit`, you could simply do `sum(Iterators.digits(...))`.

**Comment by crstnbr** [comment]
@jebej I also couldn't find the issue / a PR. Can someone else? Otherwise I'll might make a PR for adding such a digits iterator.

PS: https://discourse.julialang.org/t/slow-custom-digits-iterator/31367

**Comment by StefanKarpinski** [comment]
I'm going to close this since the right way to expose this functionality is to add `Iterators.digits`.

**Pull request closed without merging**
