### PR TITLE
RFC: Fix eig and svd methods and reorganize. 

### PR DESCRIPTION
**Pull request by andreasnoack**
This started out as a fix of JuliaLang/LinearAlgebra.jl#211 and indeed you'll now get.

```
julia> A = Diagonal(complex(randn(3), randn(3)))
3x3 Base.LinAlg.Diagonal{Complex{Float64}}:
 1.00963-0.133264im        0.0+0.0im           0.0+0.0im     
     0.0+0.0im       -0.862573-1.1623im        0.0+0.0im     
     0.0+0.0im             0.0+0.0im     -0.750588-0.782221im

julia> svdvals(A)
3-element Array{Float64,1}:
 1.44741
 1.08409
 1.01838
```

However, it ended up with a bit more. Most of the changes are just reorganizations such that svd and eig stuff go into their own source files. More substantially, this pr make eig, eigfact, svd and svdfact return Diagonal matrices. There is very little extra overhead in this change, it makes `A=U*S*V'` work and it generalizes nicely to the block diagonal case.

### CODE REVIEW

**Comment by ViralBShah** [comment]
This would be a breaking change for many. For people who were indexing into the vector of singular/eigen values, the indexing will now be different, and codes will break silently.

**Comment by ViralBShah** [comment]
Coming to think of it, the reconstruction with `U*S*V` is less interesting when I write code than the ease of getting all the eigenvalues simply in a vector. It is easy to do `U*diagm(S)*V` for reconstruction, in my opinion.

**Comment by andreasnoack** [comment]
This is the reason this is RFC. The problem is that `A≢U*diagm(S)*V'` when A is a block matrix, i.e. the elements are matrices. If we continue to return the singular values as a vector is will become a `Vector{Vector{T}}` in the block case.

The problem with the silent breaking of code could be fixed by removing the linear `getindex` method for `Diagonal` which shouldn't be used and, I'd guess, few people are relying on.

**Comment by ViralBShah** [comment]
Yes, removing linear indexing from `Diagonal` matrices is probably right, and will solve the silent breakage too.

**Comment by StefanKarpinski** [comment]
I generally think that special matrices should behave as much like real matrices as possible. Everything else is pretty frustrating when trying to work with these objects.

**Comment by mbauman** [comment]
(#10525 would re-instate the linear indexing as a fallback behavior.  I don't understand the issues here, though.)

**Comment by ViralBShah** [comment]
Sigh. @StefanKarpinski is right.

**Comment by ViralBShah** [comment]
I just thought that removing linear indexing would solve the issue here. @mbauman The issue is that the singular values are returned as a vector now. If they were to be returned as a `Diagonal` matrix, people who had code expecting a vector will find their code silently failing. If one was picking the second singular value with `S[2]` where S was originally a vector, now `S[2]` will just be 0 since it is not the second singular value, which is now on the diagonal, but just the second value in the matrix.

**Comment by tkelman** [comment]
I like this convention much better, returning a vector instead of a proper diagonal type is another Matlab-ism. (So's `diagm` which is just asymptotically bad, but I digress.) We're still making other breaking changes, should we just mention this in NEWS.md and get on with it?

**Comment by ViralBShah** [comment]
I don't mind breaking changes - but this one is likely to be widely used and will silently break. Perhaps we can temporarily include a warning in these functions until the 0.4 release. For the record, Matlab/Octave do not return a vector when asking for 3 arguments, and actually return a matrix. Originally, we used to do the same as well. There is some very old discussion on this somewhere, when we started returning the singular/eigen values as a vector.

**Comment by tkelman** [comment]
Ah, right, I'm not remembering the defaults very well, but generally the Matlab eig/svd/factorizations let you specify `vector` or `matrix` for these things (and similarly for the permutation outputs of pivoted factorizations). We can use more intelligent output types to accomplish what would otherwise be done by extra option-setting inputs.

**Comment by stevengj** [comment]
One option would be to temporarily include a warning message when linear indexing is used with the `Diagonal` matrix type.

**Comment by andreasnoack** [comment]
Superseded by ff1b30bf5f0956a6ec1b809a8904080719423f4f

**Pull request closed without merging**
