### PR TITLE
Add julia-mode.el and other editor support pieces to binary distribution.

### PR DESCRIPTION
**Pull request by twadleigh**
Addresses #9392, in part.

### CODE REVIEW

**Comment by tkelman** [comment]
I think somewhere under `share` would be a better place for this to go, `contrib` is fine for source code organization but a bit unconventional for binary structures. @nalimilan any input on where this should go? In most distros this would be a separate sub-package, right?

**Comment by twadleigh** [comment]
I originally had it in `share/emacs/site-lisp/julia` but then looked back at the issue and saw that `share/contrib` was the place that was talked about.

I'd also be fine with limiting this to the windows distribution, as that is the platform on which I miss it.

**Comment by twadleigh** [comment]
Added the other editor bits from `contrib`.

**Comment by tkelman** [comment]
This looks harmless. Will merge soon if no one has any objections.

**Comment by ViralBShah** [comment]
Are all those other editor modes regularly maintained too? I know that julia-mode.el is. Otherwise, a good idea.

**Comment by tkelman** [comment]
Not as well as the emacs one, but somewhat. I think there's at least one outstanding PR updating some of the other ones.

**Pull request closed without merging**
