### PR TITLE
Add --includes flag when querying github.user

### PR DESCRIPTION
**Pull request by garrison**
See discussion at http://marc.info/?l=git&m=142169753400910&w=2 for explanation.

### CODE REVIEW

**Comment by tkelman** [comment]
Any idea what minimum version of git this flag was introduced in?

**Comment by garrison** [comment]
The [commit that added include directives](https://github.com/gitster/git/commit/9b25a0b52e09400719366f0a33d0d0da98bbf7b0) follows git v1.7.9 and precedes git v1.7.10-rc0

**Comment by garrison** [comment]
So yeah, fixing this would up the minimum git version (from 1.7.3 to 1.7.10) :-/

**Comment by garrison** [comment]
I've looked a bit into whether there is any supported distribution that ships with a git version between 1.7.3 and 1.7.9.  FWIW, RHEL 6 ships with git 1.7.1 but RHEL 7 ships with git 1.8.3, so upgrading the minimum git version to 1.7.10 would not break anything for RHEL users.

**Comment by tkelman** [comment]
If RHEL6 ships with a version of git that's too old for use with Julia, then they must be getting a newer version of git from somewhere. And it's probably not by upgrading from 6 to 7, if that were as easy or common in RHEL distros as on Ubuntu then maybe we would get rid of the awfulness that is old RHEL distros sooner.

So where do RHEL6 users commonly get newer git binaries from? EPEL maybe? Having a hard time finding if/which version of git is available there. Looks like http://pkgs.repoforge.org/git/ has a wide selection of whichever 1.7.x version you might want for either RHEL 5 or 6.

**Comment by garrison** [comment]
Personally, I've always just compiled git in my home directory on the RHEL 6 machines I've used.  (It's fairly easy to compile, and it's really my only option because I only have superuser privileges on a subset of them.)

In all honesty, this "--includes" issue is a pretty obscure bug with the Julia Pkg system.  If it's not worth increasing the minimum required git version for this, perhaps I can re-open this pull request in the future once Julia's minimum git version is increased for other reasons to 1.7.10 or higher.

**Comment by tkelman** [comment]
What exactly is the bug? We plan on removing the git version requirement entirely by switching from command-line git to using libgit2, so I doubt this will be relevant at that point.

**Comment by garrison** [comment]
The bug is that the `Pkg` functions that depend on my github username fail mysteriously if I've put my username in a file that is included from `~/.gitconfig`.

For instance, my `~/.gitconfig` includes something like the following:

    [include]
    path = /home/garrison/dotfiles/git/gitconfig_common

and my github username is defined in `gitconfig_common`.  But running certain `Pkg` functions says "no GitHub user name configured".

**Comment by jakebolewski** [comment]
I don't know if libgit even supports this feature.

**Comment by garrison** [comment]
I'm going to withdraw this for now -- it doesn't make sense to merge if it's going to require a higher minimum git version that Julia currently uses.

**Pull request closed without merging**
