### PR TITLE
Shared Arrays no longer considered experimental

### PR DESCRIPTION
**Pull request by DanielArndt**
Was removed elsewhere by @timholy in #12412

### CODE REVIEW

**Comment by timholy** [comment]
Good catch.

IIRC, I think they're also not Unix-only anymore. Can anyone confirm?

**Comment by danielarndt** [comment]
If so I can rip that out as well. I was curious about that.

**Comment by tkelman** [comment]
There was a PR by twadleigh a while back with a windows implementation.

**Comment by danielarndt** [comment]
#9044 -- Is that sufficient to remove the "Unix-only" ?

**Comment by timholy** [comment]
Definitely.

**Comment by danielarndt** [comment]
Amended.

**Comment by timholy** [comment]
Thanks!

**Comment by DanielArndt** [comment]
@timholy should this be backported to 0.4.x?

**Comment by timholy** [comment]
Yup. Thanks for noticing.

**Pull request merged**
