### PR TITLE
fix scope issues #7234 and #10472

### PR DESCRIPTION
**Pull request by JeffBezanson**
This cleans up global scope a bit:
- Globals are never inherited for assignment within functions unless explicitly declared with `global` in an enclosing scope (#7234)
- `begin` and `if` now never introduce scopes, as documented. Before they could introduce scopes at the top level _if_ a `local` declaration were present inside. Use `let` if you need a local scope.
- `local` is disallowed in global scope.

A few tests used the `begin; local x = ...` construct, however this seems to be mostly older code, and we have already largely moved to `let` for this purpose.

### CODE REVIEW

**Comment by ScottPJones** [comment]
That's great!  Trying to follow the "semi-soft" scope discussion caused by the bug with `begin/if` was making my head hurt!

**Comment by StefanKarpinski** [comment]
This definitely seems cleaner. I assume that "local disallowed in global scope" means that the "each line kinda sorta has its own mini scope" business is gone with this change, right? Needs a NEWS entry, but since this seems to make the docs correct probably doesn't need documentation updates.

**Comment by MichaelHatherly** [comment]
This has broken ``@time``.

```
julia> @time 1
ERROR: syntax: local declaration in global scope
```

Found via a breakage in METADATA [here](https://travis-ci.org/JuliaLang/METADATA.jl/builds/67836581) with the source line causing it [here](https://github.com/JuliaLang/METADATA.jl/blob/eb726052e318261d8dff581dd9300d1538b60424/.test/METADATA.jl#L77).

**Comment by carnaval** [comment]
It's by design. It fixes all performance problems at once.

**Comment by StefanKarpinski** [comment]
LOL. I guess we need to define `@time` to use a `let` block?

**Comment by MichaelHatherly** [comment]
> It's by design. It fixes all performance problems at once.

Fine by me ;)

> LOL. I guess we need to define ``@time`` to use a let block?

``@timev`` and some of the other variants as well I guess?

**Comment by yuyichao** [comment]
I think we should just not use local I. It

**Comment by ScottPJones** [comment]
This is an example where a more formal process, requiring at least two reviews that receive "Approved",
and not having the Merge button pushed by the creator of the PR, might have prevented breakage...
(nothing against the change itself, as I said before, it's great...)

**Comment by nalimilan** [comment]
I'd say it's more an example of CI requiring more tests: `@time` should be tested somewhere, that's all.

**Pull request merged**
