### PR TITLE
Define Iterators.first as alias for Iterators.take

### PR DESCRIPTION
**Pull request by non-Jedi**
Two-argument `Base.first` is equivalent in meaning to a non-lazy `Iterators.take`. This commit
defines `Iterators.first` so that it mirrors `Base.first` in the same way that e.g. `Base.reverse`
is mirrored by `Iterators.reverse`. This should help with discoverability.

Technically this could be considered a breaking change for anyone who called `Base.first` as
`Iterators.first`. However searching github the only results using that pattern are things
like people's personal collection of Advent of Code solutions, so breakage should be minimal
in reality.

### CODE REVIEW

**Comment by non-Jedi** [comment]
I can't replicate the test failure locally.

**Comment by non-Jedi** [comment]
I feel like this is a nice little QoL/consistency improvement. Would appreciate if someone could take the time to have a look.

**Comment by jakobnissen** [comment]
Would it not make sense to also define single-argument `Iterators.first(it)` to mirror the most common usage of `Base.first`?

**Comment by non-Jedi** [comment]
> Would it not make sense to also define single-argument `Iterators.first(it)` to mirror the most common usage of `Base.first`?

I went back and forth on that one before ultimately deciding that since `Iterators` seems to mostly be for lazy tools for working with iterables, and there's nothing lazy/non-lazy about single-argument `first`, it doesn't make sense to define `Iterators.first(x) = Base.first(x)`. I already find it somewhat unfortunate that `Base.first(x) != Base.first(x, 1)`; no reason to add to the problem.

**Comment by non-Jedi** [comment]
Friendly bump. Would this be considered too breaking to merge?

**Comment by rfourquet** [comment]
> Would this be considered too breaking to merge?

I don't think this can be considered as a breaking change, `first` is not documented to be provided by `Iterators`.

**Comment by LilithHafner** [comment]
Triage says we don't need this because take is a standard name for this. Plus we don't want a duplicate name that could be confusing.

**Pull request closed without merging**
