### PR TITLE
Document rounding away from zero

### PR DESCRIPTION
**Pull request by TotalVerb**
This documents the behaviour in #20753. (I was initially mistaken about the rounding behaviour; it is not toward infinity, but rather away from zero.)

cc @StefanKarpinski

### CODE REVIEW

**Comment by TotalVerb** [comment]
Perhaps this wording does not make it clear that the rounding mode only applies when the number is equally close to two representable alternatives. Should we make that explicit?

**Comment by StefanKarpinski** [comment]
Yes, definitely explain that this only applies to tied rounding – i.e. rounding of numbers that are equally close to the numeric values of two different possible output strings.

**Comment by TotalVerb** [comment]
OK, I have modified the docstring to make that clear. I did this through the GitHub interface, so this will require a squash merge.

**Review by Sacha0 — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Thanks!

**Pull request merged**
