### PR TITLE
Char: delete bitwise operator methods for Char type

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Alternative to https://github.com/JuliaLang/julia/pull/11103 – just delete them all.

### CODE REVIEW

**Comment by nalimilan** [comment]
+1, but probably a deprecation phase wouldn't hurt?

**Comment by StefanKarpinski** [comment]
Yes, was going to add those pending the outcome of the discussion on https://github.com/JuliaLang/julia/pull/11103. Also, it's kind of good to go through CI without deprecations first to make sure you didn't miss any usages in tests that are hidden by having the deprecation definitions. It's happened a few times that we've discovered lingering usages that only break when we delete the deprecations.

**Comment by tkelman** [comment]
> Also, it's kind of good to go through CI without deprecations first to make sure you didn't miss any usages in tests that are hidden by having the deprecation definitions

Good idea. Best to mark as WIP at that stage then?

**Comment by jakebolewski** [comment]
+1, retaining these was an oversight of making`Char !<: Integer`.

**Comment by ScottPJones** [comment]
@StefanKarpinski What all does CI do, in addition to Base.runtests()?  I've been always doing that before pushing to GitHub... and I already had done Base.runtests() with all of the bitwise operators totally removed...  Thanks!

**Comment by StefanKarpinski** [comment]
It does that but on many platforms. Probably overkill in this case, admittedly.

**Comment by ScottPJones** [comment]
Could you merge this in to Base, and then close #11103?  Since this handles the not logical bitwise operations that I'd removed as part of #11103, I'm happy to just leave it at that...

**Pull request merged**
