### PR TITLE
deps/blastrampoline: Update source build to v5.5.0

### PR DESCRIPTION
**Pull request by stahta01**
And, do some WINNT code changes.

Tim S.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Needs https://github.com/JuliaPackaging/Yggdrasil/pull/6462 to be merged first.

**Comment by ViralBShah** [comment]
Note - I deleted the 5.5 tag on LBT and will re-tag it shortly once the compile issues get fixed. Will need the commit SHA in this PR to be updated.

**Comment by ViralBShah** [comment]
v5.5.0 is re-tagged and also published into Yggdrasil. https://github.com/JuliaPackaging/Yggdrasil/pull/6462

**Review by ViralBShah — CHANGES_REQUESTED** [review]
This file also needs a version update (and julia compat updated to 1.10).

https://github.com/JuliaLang/julia/blob/master/stdlib/libblastrampoline_jll/Project.toml

**Comment by stahta01** [comment]
> This file also needs a version update (and julia compat updated to 1.10).
> 
> https://github.com/JuliaLang/julia/blob/master/stdlib/libblastrampoline_jll/Project.toml

I really do not know what to change in toml files.

Tim S.

**Comment by inkydragon** [comment]
https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/build.md#update-the-version-number-of-a-dependency

> Update Version number in stdlib/**/Project.toml

Just google it `libblastrampoline_jll`
then you can find: https://github.com/JuliaBinaryWrappers/libblastrampoline_jll.jl
copy the version number in the latest release.

**Comment by ViralBShah** [comment]
You don't need to close this - just add one more file to this PR where the version number is updated to 5.5.0+0 in the `libblastrampoline_jll/Project.toml` file. I can't add files to your PR I think - only edit the ones already in the PR - or else I could have done that.

**Pull request closed without merging**
