### PR TITLE
fix package building

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Apparently virtual machines can't really be expected to connect to the internet. Enough CI runs pass here to be alright.

**Comment by nalimilan** [comment]
Any reason to use `repr(x, :property => value)` rather than `repr(x, property=value)`? I've been wondering for a long time why `IOContext` doesn't use keyword arguments too, as they seem perfectly suited for the task.

**Comment by StefanKarpinski** [comment]
One nice one is that you can use `:module` whereas `repr(x, module = value)` is not valid syntax.

**Comment by nalimilan** [comment]
Ah, right. But is that a sufficient reason to use a slightly non-standard pattern? We could use a different argument name, just like everywhere else.

**Comment by StefanKarpinski** [comment]
`IOContext` was added by @vtjnash based on a design worked out together with @stevengj and @JeffBezanson. Do you guys recall why this went with pairs instead of keyword args? Any feelings one way or the other? For some reason, I'm fond of the pair API, but it could just be that I'm used to it. Something in my mind is a bit uneasy with unconstrained keyword args – it feels like cramming arbitrary data into a structured API inappropriately. I feel like keyword arguments are a thing you should be able to list exhaustively, whereas I don't have the same expectation for pairs.

**Comment by nalimilan** [comment]
I think one of the reasons is that `IOContext` is based on `ImmutableDict`, so it's natural from that POV to use pairs. But for higher-level functions like `repr`, I think it's less obvious.

> I feel like keyword arguments are a thing you should be able to list exhaustively, whereas I don't have the same expectation for pairs.

Well, we allow varargs keyword arguments, which are used e.g. to create data frame columns with arbitrary names.

**Pull request merged**
