### PR TITLE
Change Dict to be ordered by default

### LINKED ISSUE #34265: Deserializing a Dict gives a different order
@bkamins  pointed out on slack:

```
julia> using Serialization;
julia> d = Dict{Symbol, Vector{Int}}(Symbol.('a':'z') .=> Ref([1]));
julia> serialize("test.bin", d);
julia> d2 = deserialize("test.bin");
julia> hcat(collect.(keys.([d, d2]))...)
26×2 Array{Symbol,2}:
 :o  :j
 :b  :x
 :p  :d
 :n  :k
 :j  :g
 :e  :u
 :c  :r
 :h  :a
 :l  :m
 :w  :y
 :x  :i
 :d  :o
 :k  :b
 :s  :p
 :v  :n
 :g  :e
 :u  :c
 :q  :h
 :r  :l
 :z  :w
 :a  :s
 :f  :v
 :m  :z
 :y  :q
 :i  :f
 :t  :t
```

But it doesn't have to be this way.

If we redefine things so it remembers how many slots it should have,
then it comes out the same as it came in.
```

hintsize(dict::AbstractDict) = length(dict)
hintsize(dict::Dict) = length(dict.keys)

function Serialization.deserialize_dict(s::AbstractSerializer, T::Type{<:AbstractDict})
    n = read(s.io, Int32)
    sz = read(s.io, Int32)
    t = T();
    sizehint!(t, sz)
    Serialization.deserialize_cycle(s, t)
    for i = 1:n
        k = deserialize(s)
        v = deserialize(s)
        t[k] = v
    end
    return t
end

function Serialization.serialize_dict_data(s::AbstractSerializer, d::AbstractDict)
    write(s.io, Int32(length(d)))
    write(s.io, Int32(length(d.slots)))
    for (k,v) in d
        serialize(s, k)
        serialize(s, v)
    end
end
```

But this is annoying because it changes the serialization format.
I would rather change `sizehint!(::Dict)` or how we call it.
The problem is that `sizehint!(Dict(), 26)` gives it 32 slots,
but the `d` had 64 slots.

---
In python this was one of thing things that really caught me out.
Because python salts its hashes wiith a random salt selected each time it starts.
But julia doesn't.

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Fixes: #34265 Supersedes my #37804. See also my argument:  https://github.com/JuliaLang/julia/issues/37761#issuecomment-699218475

[EDIT: Based on @oxinabox code, OrderedDict from OrderedCollections.jl; as changing Dict to be ordered is unworkable for me, seems proven a breaking change, this PR is abandoned.]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I can look into he non-serious docs failure, but the rest seems to be false alams, not sure why happening:

```
cp: cannot stat 'dist-extras/7z.*': No such file or directory
```

**Comment by tpapp** [comment]
As suggested in the [discussion](https://discourse.julialang.org/t/replacement-for-dict-is-anyone-using-isslotfilled/48810/), please provide motivation for this. In particular, cf the discussions in #34265 and #10116.

Benchmarks would be interesting too.

**Comment by PallHaraldsson** [comment]
The motivation is in the discussion you linked, and Jeff, Stefan and a lot of others want ordered by default, see this thread/comment:
https://github.com/JuliaLang/julia/pull/10116#issuecomment-105589664

**Comment by PallHaraldsson** [comment]
Up to "1 failing, 7 pending, and 7 successful checks" probably ready for package eval. One small commit for that doc failure.

**Comment by PallHaraldsson** [comment]
The 3 so-far buildbot/tester_* failures (and 3 more coming seem like false alarms, or something I do not understand, related to:

```
ps = _spawn(cmds, spawn_opts_inherit(args...))
success(ps) || pipeline_error(ps)
````

**Pull request closed without merging**
