### PR TITLE
Document type-piracy / type-leakage restrictions for `require_stdlib`

### PR DESCRIPTION
**Pull request by topolarity**
I was a recent offender in https://github.com/JuliaLang/Pkg.jl/issues/4017#issuecomment-2377589989

This PR tries to lay down some guidelines for the behavior that stdlibs and the callers of `require_stdlib` must adhere to to avoid "duplicate stdlib" bugs

These bugs are particularly nasty because they are experienced semi-rarely and under pretty specific circumstances (they only occur when `require_stdlib` loads another copy of a stdlib, often in a particular order and/or with a particular state of your pre-compile / loading cache) so they may make it a long way through a pre-release cycle without an actionable bug report.

### CODE REVIEW

**Comment by topolarity** [comment]
FWIW, the relevant definition of "type piracy" here is "You can dispatch to this Method even without using any types defined in the package/stdlib"

This unfortunately means that:
```julia
function Base.foo(x::Ref{T}) where T <: MyAbstractType
     # ...
end
```

is committing a (tiny slice of) type piracy even if the stdlib owns `MyAbstractType`, because `foo(::Ref{Union{}})` can dispatch to this method.

That kind of dispatch is a real (albeit rare) problem for stdlib correct-ness though, and the current fix would be to define `foo(x::Ref{Union{}})` upstream, so that it blocks dispatch to this method by specificity.

Just one example of the subtleties here...

**Review by vtjnash — APPROVED** [review]

**Comment by tecosaur** [comment]
This seems like a nicely written up description of some very useful information. Thanks for putting this together Cody!

**Comment by topolarity** [comment]
@vtjnash I was thinking about this a bit more, and I'm pretty sure this means we have to ban usage of `require_stdlib` during pre-compilation, since otherwise you can end up with call edges to things that aren't supposed to be among your dependencies?

(i.e. you can end up compiling against these "side-loaded" dependencies on accident)

Or do we need to allow that, and we just have to really hunt down these type-piracy issues?

**Comment by vtjnash** [comment]
Yep, and not just call edges, but also package edges that are already incorrect/stale even just as it finishes compiling it will need re-precompiling every time

**Pull request merged**
