### PR TITLE
store location of loop boundary

### LINKED ISSUE #485: Code locations of iteration with `break` are incorrect.
I found Debugger.jl points to a wrong code location in the following example:
```
julia> @enter stringsearch("abra", "abra")
In stringsearch(a, b) at /home/kenta/workspace/JuliaInterpreter/bug.jl:1
 1  function stringsearch(a::String, b::String)
 2      found = true
>3      for i in eachindex(a)
 4          if a[i] != b[i]
 5              found = false
 6              break
 7          end

About to run: (eachindex)("abra")
1|debug> n
In stringsearch(a, b) at /home/kenta/workspace/JuliaInterpreter/bug.jl:1
 1  function stringsearch(a::String, b::String)
 2      found = true
 3      for i in eachindex(a)
>4          if a[i] != b[i]
 5              found = false
 6              break
 7          end
 8      end

About to run: (getindex)("abra", 1)
1|debug>
In stringsearch(a, b) at /home/kenta/workspace/JuliaInterpreter/bug.jl:1
  2      found = true
  3      for i in eachindex(a)
  4          if a[i] != b[i]
  5              found = false
> 6              break  <---- WRONG: it won't break since a[i] == b[i]
  7          end
  8      end
  9      return found
 10  end

About to run: (iterate)(Base.EachStringIndex{String}("abra"), 2)
1|debug>
```

This is because the current call frame misunderstand that the iteration comes from line 6, not line 3.
```julia
function stringsearch(a::String, b::String)
    found = true
    for i in eachindex(a)
        if a[i] != b[i]
            found = false
            break
        end
    end
    return found
end

using JuliaInterpreter
frame = JuliaInterpreter.enter_call(stringsearch, "abra", "abra")
show(IOContext(stdout, :limit => false), frame)
```

```
Frame for stringsearch(a::String, b::String) in Main at /home/kenta/workspace/JuliaInterpreter/bug.jl:1
   1 2  1 ─       found = true
   2 3  │   %2  = Base.eachindex(a)
   3 3  │         @_4 = Base.iterate(%2)
   4 3  │   %4  = @_4 === nothing
   5 3  │   %5  = ($(QuoteNode(Core.Intrinsics.not_int)))(%4)
   6 3  └──       goto #6 if not %5
   7 3  2 ┄ %7  = @_4
   8 3  │         i = Core.getfield(%7, 1)
   9 3  │   %9  = Core.getfield(%7, 2)
  10 4  │   %10 = Base.getindex(a, i)
  11 4  │   %11 = Base.getindex(b, i)
  12 4  │   %12 = %10 != %11
  13 4  └──       goto #4 if not %12
  14 5  3 ─       found = false
  15 6  └──       goto #6
  16 6  4 ─       @_4 = Base.iterate(%2, %9)  <---- This originates from line 3, not line 6.
  17 6  │   %17 = @_4 === nothing
  18 6  │   %18 = ($(QuoteNode(Core.Intrinsics.not_int)))(%17)
  19 6  └──       goto #6 if not %18
  20 6  5 ─       goto #2
  21 9  6 ┄       return found
a = "abra"
b = "abra"               _
```

### PR DESCRIPTION
**Pull request by simeonschaub**
Since lowering always inserts gotos and other instructions after loop
bodies, this allows debuggers to give a more useful location for these
instructions.

fixes JuliaDebug/JuliaInterpreter.jl#485

### CODE REVIEW

**Comment by simeonschaub** [comment]
The failure in Distributed shows this could potentially be an issue for macros, so we should do a PkgEval run.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41857#issuecomment-896884439) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a98b639_vs_6469ca5/report.md).

**Comment by simeonschaub** [comment]
Ok, a lot of the failures do seem to be real. ChainRulesTestUtils and Cthulhu are probably ok, since they are testing Base internals, but Hyperopt and InteractBase seem to have similar issues as `Distributed.@distributed`.

Are we ok with just fixing those packages, or is this change a bit risky? Alternatively, we could also make the LineNumberNode part of the `for` expression itself, but that might be disruptive in a similar way.

**Comment by JeffBezanson** [comment]
Can you elaborate on why this broke the macro?

**Comment by simeonschaub** [comment]
The macros extract the loop bodies and actually use the return value of that `block` expression, which is now `nothing` because the last entry is a `LineNumberNode`.

**Comment by JeffBezanson** [comment]
vtjnash says we should probably fix those packages first, then it might be ok to do this.

**Comment by simeonschaub** [comment]
OK, all affected packages should now have been fixed. Could I get a review?

**Comment by vtjnash** [comment]
I don't think this should be backported

**Pull request merged**
