### PR TITLE
re-enable terminal's beep and use... something else!

### PR DESCRIPTION
**Pull request by rfourquet**
In the REPL, when an action cannot be done, the user can be
notified by animating the prompt - no need to use built-in
terminal's beep ('\a'), which is anyway often disabled.

Alternative to #9710, which discuss the merits of having a visual feed-back sometimes (e.g. when \<TAB\> shows no completion, is it that the current word is valid, or that there are no completion for it?) 

The idea here is to make the prompt blink. I like it sober, so it blinks once by default, alternating with `:light_black` color (can be customized). This is done asynchronously, so that it's not blocking. If a beep is requested when already "beeping", the `duration` (by default 0.2s) adds up, to a maximum of `maxduration`. `blink` sets the duration of a blink, but maybe should be changed to mean the number of blinks. 

Here is a small screenshot: first the word "qwe\<TAB\>" is typed and then it blinks because there are no completion. Then \<BACKSPACE\> is held so that blinking accumulates to the maximum value, then the repl is used (and complection used on "function") while blinking: beep3

I'm not quite sure my locking scheme is OK. Will have to check again (and I could use some advices...).

EDIT: it you want to try, it's easy to customize, e.g.
```
Base.LineEdit.beep(s::Base.LineEdit.PromptState) =
    Base.LineEdit.beep(s, 0.8, 0.1, 2.0,
                       colors=[Base.text_colors[c] for c in (:yellow, :magenta, :red)],
                       use_current=false, # don't use the current color in `colors` above
                       underline=true)
```
(Am still in awe of 265 solved...)

### CODE REVIEW

**Comment by rfourquet** [comment]
Does someone have a clue what causes the Appveyor errors? ("ArgumentError: stream is closed or unusable" in the "replcompletions" test). No such error in with Travis and on my box.

**Comment by StefanKarpinski** [comment]
Maybe they use a terminal emulator to capture output that doesn't like something this PR is printing?

**Comment by rfourquet** [comment]
So tests pass now :) I will merge in a couple of days if no objection or no more comments.

**Comment by rfourquet** [comment]
I an going to merge this without waiting for CI as it runned already yesterday, but there was now a very trivial merge conflict (see last merge commit), which doesn't warrant using CI resources. 

I decided to simplify a bit the functionality, because using two different locks for this seemed overkill: if the user makes an action when it's beeping, the beeping is canceled before executing the action. 

It's now possible to play with the options by manipulating global Ref variables, e.g.  `LineEdit.BEEP_BLINK[] = .08`. Using configuration options like in #23637 should be supported, but it's inconvenient for playing with them. Please comment here for any suggestion of better defaults or improvements.

**Comment by giordano** [comment]
This is awesome!

**Pull request merged**
