### PR TITLE
Test: run online tests together with all the other tests

### PR DESCRIPTION
**Pull request by KristofferC**
Might save some CI time to run the online tests in parallel with the other tests. I know these tests are a bit noisy now so might have to work on that.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Lets see if this #27469 happens on this branch too.

**Comment by mbauman** [comment]
Bump! I got bit by this and ended up burning through a bunch of CI time as I _thought_ I was running the Pkg tests with `make -C test Pkg`, but turns out that's not sufficient.  This seems like a good solution.

**Comment by mbauman** [comment]
https://github.com/JuliaLang/julia/pull/27443/files#diff-a30e018ffcf39b172d269459db7d9d7aR142

**Comment by KristofferC** [comment]
With Pkg not running here anymore, this doesn't really matter.

**Pull request closed without merging**
