### PR TITLE
Add a test throws an error by invalid subtyping in definition (#19414)

### PR DESCRIPTION
**Pull request by wookay**
Hello, here's about the test for the invalid subtyping in definition.

https://github.com/JuliaLang/julia/issues/19414
https://github.com/JuliaLang/julia/issues/20523

thanks.

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by tkelman** [comment]
what happened to the commits that were testing for #20523?

**Comment by JeffBezanson** [comment]
I don't know, but the code in #20523 is now rejected with an error, so it's not clear what to test (other than that error itself).

**Comment by tkelman** [comment]
The error's worth testing (and that's what https://github.com/wookay/julia/commit/64500759abf210e8de5353350614561fbea4e417 / https://github.com/wookay/julia/commit/ad2a2227948415d0fbde0176e53716fe2ab8baf3 did), if that's the correct behavior that we want to keep.

**Comment by JeffBezanson** [comment]
Aren't those tests identical to the one here?

**Comment by wookay** [comment]
hi. I have updated the test with getting the error message.

**Pull request merged**
