### PR TITLE
Simplify BLAS vendor logic and doc string

### PR DESCRIPTION
**Pull request by musm**
- update vendor logic: current logic seems unnecessarily complex.
- use the already defined `libblas` constant
- module docstring update

Note:
`vendor()` function may be deleted in preference to the ref. Let me know if this is preferred. Currently it is not, since it is used in three other locations which could instead use the reference directly:    https://github.com/JuliaLang/julia/blob/495569637715d97189ed0ca39d056551fe2fd4ba/stdlib/Distributed/test/distributed_exec.jl#L988 and  https://github.com/JuliaLang/julia/blob/5533f22d8f9a1ba8b6ed5d67eac8d54824489d6a/stdlib/LinearAlgebra/src/LinearAlgebra.jl#L418 and https://github.com/JuliaLang/julia/blob/5533f22d8f9a1ba8b6ed5d67eac8d54824489d6a/stdlib/LinearAlgebra/src/LinearAlgebra.jl#L430

### CODE REVIEW

**Comment by staticfloat** [comment]
I think this is a pretty significant change, as instead of having a compile-time constant expression, we now have a lookup into a `Ref`; I think this may slow down BLAS operations, as the vendor choice can no longer be constant-folded away.  We would definitely need to do some performance testing on this before merging.

**Comment by musm** [comment]
Thanks for the review.

Actually the reference is only used for checks/query functions: `set_num_threads` and `check`, plus setting a compile time macro.  In other words, BLAS operations remain unaffected by this change.

**Comment by staticfloat** [comment]
...ah; the deferencing happens at precompilation time, you're right, this is harmless.  Let's not remove `vendor()` since it doesn't really hurt, and is prettier than `VENDOR[]`.

**Comment by musm** [comment]
Yeah, will keep.  I'm guessing this is pretty cold code, which is why it's unnecessarily  convoluted.

**Comment by vtjnash** [comment]
I'm not sure I understand why this change is better. The behavior seems unnecessary complex in this PR, while before it was a couple simple functions and a simple constant.

**Pull request closed without merging**
