### PR TITLE
Revert some Date printings

### PR DESCRIPTION
**Pull request by KristofferC**
These commits were reverted for release 1.2 and also now on release 1.3 since AFAIU they broke some test and we are not sure we want to commit to this printing.

It is a bit annoying and fragile to have stuff on master that we keep reverting for the releases. Therefore we should either decide to go with this or revert it on master aswell.

cc @nalimilan, @JeffBezanson

### CODE REVIEW

**Comment by omus** [comment]
Are we saying printing cannot be changed until 2.0?

**Comment by KristofferC** [comment]
No. But for some reason this was supposed to be reverted for 1.2 so we should just decide to either go with this or not. Hence triage.

**Comment by JeffBezanson** [comment]
I vote for keeping it how it is on master and in 1.3. It's perhaps not perfect, but I think a big improvement. Output like `2014-01-29:1 day:2014-02-03` is kind of silly.

**Comment by nalimilan** [comment]
Well we've had the same debate for 1.2 (https://github.com/JuliaLang/julia/issues/30901), and nothing has changed since then, so I vote for reverting it again. Unless of course we can agree on a good solution and close https://github.com/JuliaLang/julia/issues/30901.

**Comment by JeffBezanson** [comment]
I'll try to summarize the state of the debate for triage (see if I have this right).

We use the `:compact` output flag to select `1 day` instead of `Day(1)`, which doesn't fully make sense, and leads to weird output like
```
julia> fill(Day(1) => Day(2), 2, 2)
2×2 Array{Pair{Day,Day},2}:
 1 day=>2 days  1 day=>2 days
 1 day=>2 days  1 day=>2 days
```
and also the lesser problem that Days in vectors look different than Days in matrices. We want to somehow get `1 day` inside pretty-printed matrices and DataFrames, but not nested inside things like `=>`. One suggestion was to add a `:repr` output flag for this. Here's a handy table of the current state:

call  |   output  | where used
------|-------------|-----------------
print | `2019-09-10`
show | `Date(2019, 9, 10)`  |   3-arg show of Vectors
repr | `Date(2019, 9, 10)`
show `:compact` | `2019-09-10`  |  in matrices/dataframes
show text/plain | `2019-09-10`   | at the prompt

As far as I know, the objection to keeping this change in 1.3 is that we're likely to make further changes, to avoid `1 day=>2 days`. @nalimilan is that correct? Or do you have other objections to the current output?

**Comment by nalimilan** [comment]
Thanks for the summary.

My main objection is that the changes go in the wrong direction, i.e. I think we will have to revert them in a future release. On 1.2, things are simple: all forms of `show` return `2019-09-10`. The changes make things much more complex, based on what appears to be an abuse of `:compact`, and the result isn't a clear improvement. Passing `:compact=>false` would give you something that is actually less compact, and less readable. So clearly we're abusing `:compact` in that case.

Introducing a `:parseable` or `:repr` `IOContext` property would also make sense, but note that @vtjnash proposed introducing `:precedence` instead, since it's not clear that parseability is at stake here: rather, the problem is to make precedence clear in `1 day=>2 days`.

Anyway, just reading the arguments in the thread takes a long time, so I don't think we should change things in a hurry. And nobody cared enough to try to improve things since we reverted the PR, so maybe what we have in 1.2 is good enough? At least it can wait for another cycle.

**Comment by JeffBezanson** [comment]
> rather, the problem is to make precedence clear in `1 day=>2 days`

I completely disagree that printing e.g. `(1 day)=>(2 days)` would be an improvement, if that's what you're referring to. Why bother with all the parens and whatnot if the result still isn't parseable?

I do understand the objection to using `:compact` for this. So I think everybody would be happy if we:
1. Always output `2019-09-10`, for every row in my table above.
2. Add some new way to select the output `Date(2019, 9, 10)` instead
?

Or, here's an alternative: implement the syntax `date"2019-09-10"`, and use that as the output format. In `:compact` mode the `date""` can be dropped, i.e. just print `2019-09-10`.

**Comment by nalimilan** [comment]
> I do understand the objection to using `:compact` for this. So I think everybody would be happy if we:
> 
>     1. Always output `2019-09-10`, for every row in my table above.
> 
>     2. Add some new way to select the output `Date(2019, 9, 10)` instead
>        ?

Sure. But how do you suggest we achieve this?

**Comment by tkf** [comment]
> Introducing a `:parseable` or `:repr` `IOContext` property would also make sense

I have a concern about this direction. Please see #33260.

**Comment by nalimilan** [comment]
Note that we're going to have to make the same decision for 1.4 soon.

**Pull request closed without merging**
