### PR TITLE
Fix #9525

### LINKED ISSUE #9525: Segmentation fault for sparse with incorrect size provided
I get a seg fault when I try to construct a sparse matrix with the incorrect size provided as shown below:

```
A = sparse([1; 2; 3], [1; 2; 5], 1.0, 3, 3)

signal (11): Segmentation fault: 11
sparse at sparse/csparse.jl:73
sparse at sparse/sparsematrix.jl:291
jlcall_sparse;19942 at  (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1418
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:59
eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:207
eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:215
eval_body at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:543
jl_interpret_toplevel_thunk_with at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:571
jl_toplevel_eval_flex at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:453
jl_f_top_eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:399
eval_user_input at REPL.jl:53
jlcall_eval_user_input;19940 at  (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1418
anonymous at task.jl:95
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/task.c:427
julia_trampoline at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/init.c:1007
Segmentation fault: 11
```
I'm on Julia 0.3.3 on OS X.

```
julia> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.3.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by IainNZ**
Haven't tested locally, so need to let Travis run. Should I add a test for this?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This does seem like it should have a test.

**Comment by IainNZ** [comment]
Test added, will wait for CI

**Comment by andreasnoack** [comment]
I tried to backport this, but it does work right away.

**Comment by tkelman** [comment]
looks like it backported cleanly this time in db3dee26e410f9807f13a771a566b81a14889abc

**Pull request merged**
