### PR TITLE
Fix Makefile not removing  debug julia lib on windows

### LINKED ISSUE #30023: libjulia-debug.dll is included even though julia-debug is not
For some reason it seems that  libjulia-debug.dll is included even though  julia-debug.exe is not

### PR DESCRIPTION
**Pull request by musm**
fix https://github.com/JuliaLang/julia/issues/30023

### CODE REVIEW

**Comment by staticfloat** [comment]
I don't think this is the correct fix; just because I run `make install` doesn't mean I want the debug version removed from the destination directory; that makes it difficult to keep the debug version around when I'm building/updating just the release version.

Rather, we should figure out why the debug library is getting built/installed when we don't want it.  Most likely there's something wrong with https://github.com/JuliaLang/julia/pull/27814 and libraries are getting copied into the destdir when they shouldn't be.

**Comment by staticfloat** [comment]
I certainly did not mean to close this PR.  Sorry about that.  :)

**Comment by musm** [comment]
@staticfloat thanks for the review and comments.

I'm confused by your review, this is only for `binary-dist` .

**Comment by staticfloat** [comment]
> I'm confused by your review, this is only for binary-dist .

It's not only for `binary-dist`; these changes are within the `install:` target, so they will apply whenever I run `make install`.  Here's why I'm confused:

If I run `make install` without `BUNDLE_DEBUG_LIBS`, the debug libraries should not get installed.  Which I believe is true.

If I run `make binary-dist`, the make system should clean out any previously-run `make binary-dist` objects (which is part of the `distclean` target), so the removal that you are doing in this PR should be having no effect anyway.  So in what situation is `make binary-dist` copying in debug libraries?

**Comment by musm** [comment]
this removes it from the bindir directory not the install directory. I've tested this locally and it fixes the bug in the linked issue by ensuring the debug julia lib is not included in the julia installer on windows.

**Comment by ViralBShah** [comment]
I believe the offending line is https://github.com/JuliaLang/julia/blob/d32b30e4f2f97a4ed68dbcc940d94142265556e2/Makefile#L342

We should remedy the real issue, rather than just deleting the libjulia-debug.dll. The rule above should just be made specific to copy only the necessary files. Should hopefully not be too difficult.

**Comment by musm** [comment]
Indeed @ViralBShah  that is the exact crux of the problem. 

I decided to `rm` the file in this PR as it seemed the simplest approach since there numerous library ddl that are copied over in the catchall `*.dll` . 

What's then the best way to specify to copy over all library dlls **except** `libjulia-debug.dll` ?

**Comment by musm** [comment]
Any thoughts on the comments above? Is this not sufficient (it does indeed work) until a better solution is proposed?

**Comment by staticfloat** [comment]
> this removes it from the bindir directory not the install directory.

I'm not sure what you mean by this; `$(DESTDIR)$(bindir)` **is** the install directory, and we should not be deleting things from there.  Imagine what happens when a user runs `sudo make install prefix=/usr/local`; we do not ever want to be deleting things from `$(DESTDIR)$(bindir)`, assuming that we control what is within there, because we do not.  We control `$(build_bindir)` but not `$(DESTDIR)$(bindir)`.

**Comment by musm** [comment]
thanks @staticfloat for the suggestion. Frustratingly it still ends up copying, is there something wrong with the filter-out and wildcard statement you posted? Looks correct, however.

**Comment by staticfloat** [comment]
You can debug this by doing things like `echo "DOES THIS LOOK RIGHT: $(filter-out libjulia-debug.dll,$(wildcard $(build_bindir)/*.dll))"` in the Makefile or whatnot.  If you want to see things in a `Makefile` that are not getting run as part of a target, you can use `$(warning blah blah blah)` within top-level Makefiles statements.

**Comment by musm** [comment]
Ok fixed! Thanks @staticfloat !

**Comment by musm** [comment]
This also needs a backport label at least for 1.1 if not 1.0.x also.

**Review by staticfloat — APPROVED** [review]

**Comment by ViralBShah** [comment]
Looks good to merge.

**Pull request merged**
