### PR TITLE
bug fixes in matrix log

### LINKED ISSUE #640: log(matrix) issue
A similar issue was discussed in [#21179](https://github.com/JuliaLang/LinearAlgebra.jl/issues/415). That issue has been fixed, as the example given calculates correctly

```julia
julia> B = [3 2; -5 -3]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> exp(log(B))
2×2 Array{Complex{Float64},2}:
  3.0+3.9276e-16im    2.0+1.30473e-16im
 -5.0-1.26787e-15im  -3.0-4.20143e-16im
```
But if we let ```C=10 B``` then we encounter a problem
```julia
julia> C = [30 20; -50 -30]
2×2 Array{Int64,2}:
  30   20
 -50  -30

julia> exp(log(C))
2×2 Array{Complex{Float64},2}:
   -30.0-8.57143im  -14.2857-17.1429im
 44.2857-17.1429im      30.0+8.57143im
```
This approach gives the correct answer
```julia
julia> using LinearAlgebra

julia> function logmat(A)
       Λ, S = eigen(A)
       return S*(log.(Complex.(Λ)).*inv(S))
   end
logmat (generic function with 1 method)

julia> exp(logmat(C))
2×2 Array{Complex{Float64},2}:
  30.0+0.0im   20.0+0.0im
 -50.0+0.0im  -30.0+0.0im
```

### LINKED ISSUE #32313: log(matrix) issue
A similar issue was discussed in [#21179](https://github.com/JuliaLang/julia/issues/21179). That issue has been fixed, as the example given calculates correctly

```julia
julia> B = [3 2; -5 -3]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> exp(log(B))
2×2 Array{Complex{Float64},2}:
  3.0+3.9276e-16im    2.0+1.30473e-16im
 -5.0-1.26787e-15im  -3.0-4.20143e-16im
```
But if we let ```C=10 B``` then we encounter a problem
```julia
julia> C = [30 20; -50 -30]
2×2 Array{Int64,2}:
  30   20
 -50  -30

julia> exp(log(C))
2×2 Array{Complex{Float64},2}:
   -30.0-8.57143im  -14.2857-17.1429im
 44.2857-17.1429im      30.0+8.57143im
```
This approach gives the correct answer
```julia
julia> using LinearAlgebra

julia> function logmat(A)
       Λ, S = eigen(A)
       return S*(log.(Complex.(Λ)).*inv(S))
   end
logmat (generic function with 1 method)

julia> exp(logmat(C))
2×2 Array{Complex{Float64},2}:
  30.0+0.0im   20.0+0.0im
 -50.0+0.0im  -30.0+0.0im
```

### PR DESCRIPTION
**Pull request by stevengj**
Fixes JuliaLang/LinearAlgebra.jl#640

### CODE REVIEW

**Comment by stevengj** [comment]
Ugh, it looks like this PR triggers another problem.  Will have to look at it more closely.

**Comment by RalphAS** [comment]
As shown in the book excerpt you posted in #32313, these algorithms specifically exclude the case where eigenvalues are on the negative real line (which applies to some of the examples in related issues). Experiments with roundoff-negligible perturbations suggest that your proposed fix sometimes succeeds but is still fragile in that regime. Since eigenvalues are trivially available from the diagonal of the `UpperTriangular,` perhaps it would be appropriate to rotate the branch cut or issue a warning in such cases?

**Comment by stevengj** [comment]
@RalphAS, where does the book say that?

**Comment by RalphAS** [comment]
In Algorithm 11.10 (and in various papers on matrix log by Higham and associates) one finds the limitation "no eigenvalues on R-".  On looking again I see that this is irrelevant to the issue you're addressing here and to the testing problems; sorry for the noise.

**Comment by RalphAS** [comment]
I think there is a sign error in Eq. (11.27); to compensate for the `atanh` variance I believe you want
`w = atanh(z) + im * pi * (unw(logAkp1-logAk) - unw(log1p(z)-log1p(-z)))`

**Comment by stevengj** [comment]
Closed by #33245.

**Comment by martinholters** [comment]
No? That was a PR into this branch, wasn't it?

**Comment by andreasnoack** [comment]
All test errors seem unrelated. cc @staticfloat

**Pull request merged**
