### PR TITLE
Add U+2AEA (⫪) and U+2AEB (⫫) to binary operators

### LINKED ISSUE #39350: Allow U+2AEB (⫫) as binary operator
I have a few questions, but as soon as they are done, I can do a PR:

1. Which operator preference would be best? I lean towards [`prec-comparison`](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm).
2. Which "tab completion" should it have? I like `\indep`.
3. How do I implement this completion?

### PR DESCRIPTION
**Pull request by jonas-schulze**
Closes #39350

### CODE REVIEW

**Comment by jonas-schulze** [comment]
I don't know what to make of the failure. It looks unrelated but critical?

**Comment by jonas-schulze** [comment]
@JeffBezanson bump 🙂

**Comment by simeonschaub** [comment]
Thanks! Mostly looks good to me. I think it would be good to add a NEWS entry for this and a test in `test/syntax.jl` to make sure this actually works as expected.

**Review by simeonschaub — APPROVED** [review]

**Comment by jonas-schulze** [comment]
Bump 🙂

**Comment by musm** [comment]
Looks like the NEWS file needs a quick rebase

**Comment by simeonschaub** [comment]
Thanks, sorry for the long wait!

**Pull request merged**
