### PR TITLE
Update spawn.jl

### PR DESCRIPTION
**Pull request by jakebolewski**
Fix stupid case-sensitive filesystem bug

### CODE REVIEW

**Comment by tkelman** [comment]
There are more substantial problems with this line that also need to be fixed - https://github.com/JuliaLang/julia/issues/10987 https://github.com/JuliaLang/julia/commit/a49ae5374a0a4475361d1f8cf42fe864e5e8daca#commitcomment-10836654

**Comment by tkelman** [comment]
any remaining case sensitivity issues after 374e0a91bb0649d03a83d56c4a47cbd599cde427 ?

**Comment by jakebolewski** [comment]
Yes the issue is still there, but a new PR needs to be made against the latest changes.

**Comment by tkelman** [comment]
Ah. Should probably use `Base.samefile` then. Could force push and reuse this PR and branch, just reopen before you do otherwise github locks the PR closed.

**Pull request closed without merging**
