### PR TITLE
VERSION: 0.7.0-DEV => 0.7.0-alpha

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Sigh, janky CI services. This fairly obviously shouldn't cause anything to fail and does pass a few.

**Comment by ViralBShah** [comment]
I've restarted the Appveyor on this PR.

**Comment by ViralBShah** [comment]
Mac and Win64 went through. Win32 seems to have a real problem. The travis linux failures can probably be ignored.

**Comment by ViralBShah** [comment]
Actually the travis `makedocs` problem is real, and we don't seem to have the issue on the 0.7 milestone.

**Comment by ViralBShah** [comment]
Merged https://github.com/JuliaLang/julia/pull/27272 and rebased this PR on master.

**Comment by ViralBShah** [comment]
Restarting Appveyor, which passed on 32-bit, but not on 64-bit. The issue seems transient, and could perhaps be a real bug.

**Comment by ViralBShah** [comment]
All green!

**Pull request merged**
