### PR TITLE
Add patches for compiler-rt on modern glibc

### PR DESCRIPTION
**Pull request by maleadt**
As encountered on Arch Linux. ref https://github.com/llvm-mirror/compiler-rt/commit/8a5e425a68de4d2c80ff00a97bbcb3722a4716da and https://github.com/llvm-mirror/compiler-rt/commit/78162497aa177b34956aee0458e09d8b97b5dd2b
Also remove a seemingly unused compiler-rt patch for 3.7. Tested to apply on LLVM 3.9, 4.0.0, and 5.0.0.

### CODE REVIEW

**Comment by vchuravy** [comment]
fixes #24574

**Comment by maleadt** [comment]
@vchuravy since CI doens't build with flags that trigger these patches, could you verify on your system?

**Comment by maleadt** [comment]
Also, should we backport these now that the window for 0.6.2 is still open? It doesn't have any impact on the binaries, but makes it possible to eg. build 0.6+ASAN without much hassle.

**Comment by vchuravy** [comment]
Yes I think we should backport since it also impacts Clang builds and thus
CXX.jl

**Review by vchuravy — APPROVED** [review]
Builds on my system with clang enabled

**Pull request merged**
