### PR TITLE
faster inference order

### LINKED ISSUE #15346: Time to run N tests grows faster than linear in N: codegen problem?
The time to run N tests using `FactCheck` (which internally uses anonymous functions heavily) grows significantly faster than linear in N, causing long generated test suites to hang. 
This apparently is due to #13412 (tested with that commit compared to the previous one; thanks to @andreasnoack). It is approximately linear on 0.4.

I have written a simple [file](https://gist.github.com/52b6599f6549c390b0e9) that generates test suites consisting of N tests of the form `@fact i-->i`:

This gives the following run-times (in seconds!) on 0.5:
0 5_test_times

[This seems to be faster than power law and slower than exponential growth. Raw data [here](https://gist.github.com/b26507550931e9a3d1d2).]

### PR DESCRIPTION
**Pull request by vtjnash**
may fix #15346

### CODE REVIEW

**Comment by vtjnash** [comment]
for the test case in #15346 with n=1000, this gave me about a 4x speedup on inference time (80s -> 20s), with a corresponding reduction in memory usage as well!

**Comment by JeffBezanson** [comment]
LGTM.

**Review by JeffBezanson — APPROVED** [review]

**Comment by tkelman** [comment]
This doesn't cherry-pick cleanly on release-0.5. Please open a PR against tk/backports-0.5.1 if this should be included in 0.5.1.

**Comment by dpsanders** [comment]
Yes please let's backport this; Base.Test on Julia v0.5 is still unbearably slow for large testsets.

**Pull request merged**
