### PR TITLE
Faster division by irrational

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
DO NOT merge (I forget I do mark as a Draft).

@oscardssmith, this is accurate for many important numbers, e.g. 1, 2, 3, 0.1, 10, but can be off in the last bit (more off?) and is anyone going to rely on perfect rounding for irrationals? Then Float64 can be excluded, I believe might be correct for the rest and all integers.

julia> bitstring(divi(0.04361112077097973, pi))
"0011111110001100011011100001011001111100100110111011001001000011"

julia> bitstring(Float64(BigFloat(0.04361112077097973)/BigFloat(pi)))
"0011111110001100011011100001011001111100100110111011001001000010"

**Comment by giordano** [comment]
> (I forget how to mark as a Draft).

image

> Faster division by irrational

I guess this claim has to substantiated more:

```
ulia> @benchmark 5.0 / $pi
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  1.355 ns … 11.922 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.374 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.409 ns ±  0.476 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   █                       ▃▄   ▁                             
  ▃█▃▂█▄▂█▃▂▆▆▂▁▂▁▁▁▁▁▁▁▁▂▃██▃▄▂█▃▁▂▂▁▂▂▁▁▁▁▁▁▁▁▂▃▂▁▂▂▂▁▂▂▁▂ ▃
  1.36 ns        Histogram: frequency by time        1.45 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> f(x, y) = x * inv(Float64(y))
f (generic function with 1 method)

julia> @benchmark f(5.0, $pi)
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  1.370 ns … 19.352 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.417 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.492 ns ±  0.747 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █  ▁▃                                                       
  █▇▁██▁██▅▂▂▁▂▁▁▂▁▂▂▂▂▁▁▂▁▁▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▃ ▃
  1.37 ns        Histogram: frequency by time        2.04 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

**Comment by PallHaraldsson** [comment]
>I guess this claim has to substantiated more:
>
>julia> @benchmark 5.0 / $pi

That code (assuming not optimized away) is:
```
	vdivsd	(%rax), %xmm0, %xmm0
; │ @ promotion.jl:391 within `/`
	retq
```

Issuing vdivsd is fast, just has slower latency than the replacement multiply. If you don't use the result (i.e. retq) then natural to be as fast, so you need to benckmark this with some real-world code where / result is used, somehow.

**Comment by giordano** [comment]
I guess I'm missing why special-casing irrationals anyway?  Either this is good for all `/` methods, or it is not.

**Comment by PallHaraldsson** [comment]
It is already special-cased for some non-rationals (by LLVM I guess). e.g. x/2, x/4.0, while x/3 is slower.

**Comment by StefanKarpinski** [comment]
Division by powers of two can be implemented exactly with multiplication, which is what LLVM is allowed to do that optimization. That is very much not true for irrationals, so this is not a valid optimization.

**Pull request closed without merging**
