### PR TITLE
Fix firstindex in replace_ref_begin_end (fixes #41630)

### LINKED ISSUE #41630: `begin` indexing vs. `replace_ref_begin_end!`
I thought `Base.replace_ref_begin_end!` is used to implement `begin` indexing, but appearently they are inconsistent?

Reading the source of it, I stumbled upon [this line](https://github.com/JuliaLang/julia/blob/9044222bfcee604610d75db25d8d1c07e51cf7f0/base/views.jl#L45) in views.jl:

```julia
exj, used = replace_ref_begin_end_!(ex.args[j], (:($firstindex($S)),:($lastindex($S,$n))))
```

Shouldn't that be `$firstindex($S, $n)`?  I tried producing a failing example using OffsetArrays, but that only showed some sort of discrepancy, which I can't explain:

```julia
julia> a
2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10:
 1  2
 3  4

julia> a[end, begin]
3

julia> Meta.@lower a[end, begin]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.lastindex(a, 1)
│   %2 = Base.axes(a, 2)
│   %3 = Base.first(%2)
│   %4 = Base.getindex(a, %1, %3)
└──      return %4
))))

julia> Base.replace_ref_begin_end!(:(a[end, begin]))
:(a[(lastindex)(a, 1), (firstindex)(a)])

julia> a[(lastindex)(a, 1), (firstindex)(a)]
ERROR: BoundsError: attempt to access 2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10 at index [-9, 1]
Stacktrace:
 [1] throw_boundserror(::OffsetArray{Int64,2,Array{Int64,2}}, ::Tuple{Int64,Int64}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] getindex(::OffsetArray{Int64,2,Array{Int64,2}}, ::Int64, ::Int64) at /home/philipp/.julia/packages/OffsetArrays/Osysv/src/OffsetArrays.jl:407
 [4] top-level scope at REPL[22]:1
```

### PR DESCRIPTION
**Pull request by phipsgabler**
I'd appreciate feedback about the tests.  I have no idea how to use Revise on Base...

fix #41630

### CODE REVIEW

**Comment by simeonschaub** [comment]
> I have no idea how to use Revise on Base...

You just need to build Julia once and when you run it, you can do `Revise.track(Base)` to pick up all changes inside `base/`. You can also run the tests with e.g. `make test-revise-subarray`.

**Review by simeonschaub — APPROVED** [review]
Thanks! Looks good to me.

**Comment by jishnub** [comment]
Instead of recreating offsetarrays in the test, would it make more sense to add the tests to test/offsetarrays.jl which already uses such an implementation? This might make debugging easier

**Comment by simeonschaub** [comment]
Yeah, didn't think of that, but that would be nice, so we don't have to duplicate this.

**Comment by phipsgabler** [comment]
Uh, great, I didn't know that exists.  So should I just move over the tests to that file?  Or `using .Main.OffsetArrays`?

**Comment by jishnub** [comment]
Perhaps moving the test to that file would make more sense, as `Main.OffsetArrays` is definitely loaded at that point. Also because this fix is specific to `OffsetArrays`, and the indexing operation (accidentally) works correctly for standard 1-indexed arrays. In any case perhaps adding an extra test for standard arrays to `test/subarray.jl` might not be a bad idea.

**Comment by phipsgabler** [comment]
I have moved the tests over to the other file.  Something weird was going on with Github merging the upstream, I hope everthing is in good shape now...

Anyway, I'll be on vacation from tomorrow on, so if this is urgent, someone else needs to take care of it now.

**Comment by simeonschaub** [comment]
Thanks!

**Pull request merged**
