### PR TITLE
multi-item append!

### PR DESCRIPTION
**Pull request by mzaffalon**
Similar to multi-item `push!`.

### CODE REVIEW

**Comment by tkelman** [comment]
add a test?

**Comment by mzaffalon** [comment]
No problem. Where should I put it? It looks out of place in `test/abstractarray.jl`. Maybe in `test/arrayops.jl`?

**Comment by tkelman** [comment]
not too important where it goes, if there are existing tests for append or push then it would make sense to add them there

**Comment by tkelman** [comment]
oh, can you reopen this PR against master instead of release-0.4? features should go to master. thanks!

**Comment by mzaffalon** [comment]
No explicit tests for `append!` as far as I can tell.

**Pull request closed without merging**
