### PR TITLE
Add test, fix bug for chol and test for tridiag

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why the `Array` -> `Matrix` changes?

**Comment by kshyatt** [comment]
Because the `Array` call then calls the `Matrix` conversion, and the pass-through was not tested.

**Comment by fredrikekre** [comment]
> Because the `Array` call then calls the `Matrix` conversion, and the pass-through was not tested.

Okay, perhaps instead add an explicit test for the `Array` call? Otherwise there is a risk of people like me that think `Matrix` is prettier change it back some day :)

**Comment by kshyatt** [comment]
I think Julia contributors are smart enough to look at the functions in
Base they're testing/making changes to the tests for before getting going
with the ripping and tearing action. I'd rather not have more duplicate
tests, I guess.

**Comment by kshyatt** [comment]
What's up with CI?

**Review by stevengj — APPROVED** [review]

**Comment by ararslan** [comment]
CI failures are unrelated. The BSD workers have been freezing occasionally, and 64-bit Linux on Circle has been getting spurious `ProcessExitedException`s.

**Pull request merged**
