### PR TITLE
lu should throw on matrix of NaNs

### PR DESCRIPTION
**Pull request by kshyatt**
It seems odd to me that:

```julia
julia> using LinearAlgebra

julia> h = Hermitian(fill(complex(NaN), 2, 2));

julia> inv(h)
2×2 Hermitian{ComplexF64, Matrix{ComplexF64}}:
 NaN+0.0im   NaN+NaN*im
 NaN+NaN*im  NaN+0.0im
```
Runs no problemo. At least for Hermitians or square matrices, if `eigen` errors shouldn't `inv` as well?

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]

**Comment by fredrikekre** [comment]
> no method matching isfinite(::Main.Test49Main_LinearAlgebra_generic.TestGeneric.ModInt{2})

**Comment by kshyatt** [comment]
Apple arch64 had a fail in `SparseArrays/spqr `

**Comment by dkarrasch** [comment]
> Apple arch64 had a fail in `SparseArrays/spqr `

I'd say it's unrelated because the change either causes a throw or does nothing.

**Comment by kshyatt** [comment]
In that case I'll squash and merge once the freebsd tests are done.

**Comment by YingboMa** [comment]
Why do we unconditionally check it? It doesn't respect the `check` keyword.

**Pull request merged**
