### PR TITLE
🤖 [master] Bump the SparseArrays stdlib from 760989e to 4aab8df

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Stdlib branch: main
Julia branch: master
Old commit: 760989e
New commit: 4aab8df
Julia version: 1.10.0-DEV
SparseArrays version: 1.10.0
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaSparse/SparseArrays.jl/compare/760989ec650761541deff039efb5b767a051c172...4aab8df5d3f0f19f16de52e92023c2971e60f9f9

```
$ git log --oneline 760989e..4aab8df
4aab8df `ambiguous` testgroup: restore original `ENV` at the end of the testgroup (#358)
4f4d8ed Install Aqua in the right place (#357)
d99fcfe Install Aqua.jl if necessary during CI (#356)
5d9b27c Test code quality, resolve ambiguities (#355)
c09f0ac Handle SuiteSparse >= 7 (#353)
f22cab0 fix doc spelling, grammar for lu (#352)
cb79e06 Clean up temporary fixes (#348)
195c470 Replace AbstractTriangular by UpperOrLowerTriangular (#329)
d938744 Fix "map does not respect sources index type" (#350) (#351)
38604c3 Fix bug where non-order keyword arguments are passed from `sort!` to `searchsortedfirst` (#335)
0d2d30a Keep `Hermitian(::Sparse) \ SparseArray` throwing (#322)
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @dkarrasch @ViralBShah

**Comment by DilumAluthge** [comment]
CI is all green now! 🎉

**Comment by DilumAluthge** [comment]
@ViralBShah @dkarrasch This is good to merge now.

**Comment by fxcoudert** [comment]
Could this be considered for a 1.9 backport? The `Handle SuiteSparse >= 7` commit in particular is interesting for distros shipping against their own/the latest suitesparse.

**Comment by dkarrasch** [comment]
Not entirely. The SuiteSparse commit might be backported. If we did, would we see potential issues by running CI on v1.9?

**Comment by fxcoudert** [comment]
I think the SuiteSparse commit (https://github.com/JuliaSparse/SparseArrays.jl/commit/c09f0ac575165ddf4d264c15284d8fc0f8ac54b0) should be safe to backport by itself: it's pretty independent from the rest, and just allows compatibility with recent versions.

**Comment by fxcoudert** [comment]
I'm unclear as to Julia testing process. Full testing can only take place once the SparseSuite 7 PR is merged in Yggdrasil, I think.

**Comment by ViralBShah** [comment]
That is indeed right. I think we can get all those merged today.

**Comment by ViralBShah** [comment]
Technically, any PR on Julia can trigger the pkgeval. But the safe path is to just get it all merged in Yggdrasil, and then run pkgeval on the PR in julia master that is bumping to SuiteSparse 7.

**Pull request merged**
