### PR TITLE
Allow anonymous typed VarArg

### LINKED ISSUE #10985: typed anonymous `VarArg`
It seems that typed `VarArg` has to have a name

```julia
julia> f(::Any...) = 1
ERROR: syntax: malformed expression

julia> f(a::Any...) = 1
f (generic function with 1 method)
```

Is there any ambiguity if the first case is allowed that I'm missing?

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #10985

### CODE REVIEW

**Comment by yuyichao** [comment]
Test done.

```julia
julia> f(::Int...) = 1
f (generic function with 1 method)                                                
                                                                                  
julia> f(1, 2, 3)
1                                                                                 
                                                                                  
julia> f(1, 2, "")
ERROR: MethodError: `f` has no method matching f(::Int64, ::Int64, ::ASCIIString) 
Closest candidates are:                                                           
  f(::Int64...)                                                                   
                                                                                  
julia> @code_lowered f(1, 2, 3)
1-element Array{Any,1}:                                                           
 :($(Expr(:lambda, Any[:(#s1::Int...)], Any[Any[],Any[Any[symbol("#s1"),:Any,0]],Any[],0], :(begin  # none, line 1:                                                 
        return 1                                                                  
    end))))                                                                      
```

**Comment by yuyichao** [comment]
P.S. is there a better REPL for lisp mode?... It doesn't support any navigation (persistent history is probably not necessary but session history would be nice). I had to type the command somewhere else and paste it over for testing....

**Comment by ihnorton** [comment]
Emacs? ;)

**Comment by yuyichao** [comment]
@ihnorton Well, that's exactly where I typed it before pasting it over...

(and just to clarify, by lisp mode I meant `julia --lisp`)

**Comment by mbauman** [comment]
Check out [`rlwrap`](http://utopia.knoware.nl/~hlub/rlwrap/) — it adds GNU readline functionality to any executable: `rlwrap ./julia --lisp`.  I installed it through Homebrew on my Mac.

**Comment by yuyichao** [comment]
@mbauman Didn't know that. Just installed from Arch's Repo and tried. It is exactly what I need!
THX!!!

**Comment by ihnorton** [comment]
Somewhat tongue-in-cheek, but I meant `M-x shell` :) @mbauman's suggestion looks perfect though (thanks on my behalf too!).

It would be fun to have an flisp mode in the REPL accessible by some magic key sequence. I'm not exactly sure how this would interact with the flisp boot image if you wanted to reload stuff, but shouldn't be too hard to create a bare environment.

**Comment by mbauman** [comment]
It does have the unfortunate side-effect of corrupting your real Julia history.  I'm not sure how to get around that, but I haven't played with it much.

**Comment by yuyichao** [comment]
`rlwrap -H /dev/null julia --lisp`

**Comment by tkelman** [comment]
This looks to me like it gets rid of a somewhat arbitrary syntax restriction, any potential downsides?

**Comment by yuyichao** [comment]
It shouldn't based on the discussion in #10985. It is certainly possible that my implementation has some flaw but I hope not if the code works the same way I think it does.

**Pull request merged**
