### PR TITLE
[OpenBLAS_jll] Bump to `v0.3.13+6`

### LINKED ISSUE #815: libopenblas: illegal instruction on master
On my computer, the `LinearAlgebra` tests fail on master due to illegal instructions in openblas:
```
Test         (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/lq  (1) |        started at 2021-03-01T12:34:19.198
Invalid instruction at 0x7f5b03e90e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8

signal (4): Illegal instruction
in expression starting at /home/sebastian/Development/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/test/lq.jl:20
zgemm_kernel_n_SANDYBRIDGE at /home/sebastian/Development/julia/usr/bin/../lib/libopenblas64_.so (unknown line)
Allocations: 122985676 (Pool: 122813719; Big: 171957); GC: 204
```
```
Julia Version 1.7.0-DEV.627
Commit e784dd010a (2021-02-28 18:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)
```

### LINKED ISSUE #39865: libopenblas: illegal instruction on master
On my computer, the `LinearAlgebra` tests fail on master due to illegal instructions in openblas:
```
Test         (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/lq  (1) |        started at 2021-03-01T12:34:19.198
Invalid instruction at 0x7f5b03e90e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8

signal (4): Illegal instruction
in expression starting at /home/sebastian/Development/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/test/lq.jl:20
zgemm_kernel_n_SANDYBRIDGE at /home/sebastian/Development/julia/usr/bin/../lib/libopenblas64_.so (unknown line)
Allocations: 122985676 (Pool: 122813719; Big: 171957); GC: 204
```
```
Julia Version 1.7.0-DEV.627
Commit e784dd010a (2021-02-28 18:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by giordano**
This version backports a fix for a `SIGILL` error on some CPUs.

Should fix JuliaLang/LinearAlgebra.jl#815.  @sostock @maleadt would you be able to test this PR on the machines where you can reproduce the issue?  CC: @ViralBShah

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Should this be backported? If so, to what version(s)?

**Comment by giordano** [comment]
#39865 has 1.7 milestone

**Comment by sostock** [comment]
For me, this PR solves the problem.

**Review by maleadt — APPROVED** [review]
Fixes the issue here too.

**Comment by ViralBShah** [comment]
Should be backported to 1.6 too.

**Comment by giordano** [comment]
Should it? Do we have reports of this issue in Julia v1.6? Julia v1.6 has a different version of openblas, I'd very wary of mixing binaries versions within a minor version of Julia

**Comment by sostock** [comment]
I don’t think it should be backported to 1.6, the error doesn’t occur in 1.6.

**Comment by ViralBShah** [comment]
Ok yes in that case backport not needed.

**Pull request merged**
