### PR TITLE
Define valtype(::Tuple) and keytype(::Tuple)

### PR DESCRIPTION
**Pull request by aplavin**
Same as https://github.com/JuliaLang/julia/pull/46555, but for Tuples

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Seems fine to me, although I'd ask triage for a quick look over just in case.

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
triage approves.

**Comment by brenhinkeller** [comment]
May just need CI to be rerun?

**Comment by oscardssmith** [comment]
nothing needed other than reminding us about it. Thanks!

**Pull request merged**
