### PR TITLE
Direct warning to io

### PR DESCRIPTION
**Pull request by timholy**
CC @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
i feel like there might also be a doctest that's related to this error

**Comment by timholy** [comment]
Not quite sure I follow---you mean something that's triggering the error that this is designed to circumvent?

**Comment by tkelman** [comment]
No, I think one of the doctests triggers this or a very similar error, with the error output captured and some explanation nearby. I don't know whether other doctests are in a passing state on master right now so this might not be the fastest thing to find.

**Comment by timholy** [comment]
OK to merge, then?

**Comment by tkelman** [comment]
yes, but should run the doctests because I suspect https://github.com/JuliaLang/julia/pull/13904 could have changed some tested-for outputs.

**Comment by timholy** [comment]
Now I get what you mean. Summary on this branch:
```
Doctest summary
===============
 1003 tests
   59 failures in tests
    0 failures in setup code
    0 failures in cleanup code
```
Master prior to #13904:
```
 1003 tests
   59 failures in tests
    0 failures in setup code
    0 failures in cleanup code
```
Seems like there's no regression, anyway.

Most of those failures are due to current julia frequently adding
```
    in eval at ./boot.jl:264
```
to the end of backtraces.

**Pull request merged**
