### PR TITLE
Fix full(X) where X is a factorization

### PR DESCRIPTION
**Pull request by Sacha0**
In https://github.com/JuliaLang/julia/pull/18850#issuecomment-253400216, `@tkelman` noticed that `full(X)` where `X` is a factorization has been incorrectly calling `convert(Array, X)` rather than `convert(AbstractArray, X)` since #17066. This PR fixes that bug, restoring `full`'s former semantics. (Not certain whether tests for this behavior would be useful given the plan to deprecate `full`. Perhaps making the tests in #18850 more strict [check some return types] would be the equivalent in spirit?) Best!

### CODE REVIEW

**Comment by tkelman** [comment]
hope this is all of them? yes, checking return types more strictly would be a good idea. thanks!

**Comment by Sacha0** [comment]
> hope this is all of them?

Hope so :). (grep'd.)

> yes, checking return types more strictly would be a good idea.

Is that to say that adding appropriate return type checks to #18850 as it evolves, rather than here, strikes you as a reasonable plan? Or would you prefer to add tests to `full` here, `full`'s forthcoming deprecation aside? Thanks!

**Comment by Sacha0** [comment]
The errors indicate that I relaxed too many `full` methods from `convert(Array, ...)` to `convert(AbstractArray, ...)`. In other words, `full`'s semantics were not consistent even among the factorization types. (The breadth and number of ambiguities we've encountered in the process of migrating away from `full` evidences the argument for replacing `full` with better defined entities.)

**Comment by andreasnoack** [comment]
> The errors indicate that I relaxed too many `full` methods from `convert(Array, ...)` to `convert(AbstractArray, ...)`. In other words, `full`'s semantics were not consistent even among the factorization types.

Some of the errors are because the `Q` types are not `Factorization`s. There is probably still inconsistencies among the old `full` methods were defined and your work will definately help to eliminate them. However, I still don't see that the semantics of `full(T<:Factorization/Symmetric/Triangular etc)` should be ill defined. At least not with my preffered definition: `full(A)=mattype(A)(A)` with e.g. `mattype{T,S}(LU{T,S})=S`. As I see it, the problem is that we decided to use explicit type conversion instead of a generic function.

**Comment by Sacha0** [comment]
Corrected version pushed. Passing linalg and sparse tests locally now.

> Some of the errors are because the Q types are not Factorizations.

Yes, I shouldn't write PRs when half asleep :). Best!

**Comment by Sacha0** [comment]
> However, I still don't see that the semantics of full(T<:Factorization/Symmetric/Triangular etc) should be ill defined. At least not with my preffered definition: full(A)=mattype(A)(A) with e.g. mattype{T,S}(LU{T,S})=S. As I see it, the problem is that we decided to use explicit type conversion instead of a generic function.

@andreasnoack, please see my response in #18850 (https://github.com/JuliaLang/julia/pull/18850#issuecomment-254006089). Best!

**Comment by Sacha0** [comment]
Apart from the few factorizations with specializations for structured matrix types (`LDLt` for `SymTridiagonal`, `LU` for `Tridiagonal`), how to test that `full` calls `convert(AbstractArray, X)` rather than `convert(Array, X)` is not clear. The trouble is that (for matrix types in base for which the factorizations succeed) the output of `convert(Array, X)` and `convert(AbstractArray, X)` is usually identical. @andreasnoack, thoughts/suggestions? Thanks!

**Comment by kshyatt** [comment]
Bumping.

**Comment by tkelman** [comment]
It looks like you're working towards deprecating full pretty soon. This will be a more correct deprecation. How to best test it is an open question, but may as well not hold up this fix.

**Comment by Sacha0** [comment]
> It looks like you're working towards deprecating full pretty soon.

Hopefully, but further work is blocked on [this decision](https://github.com/JuliaLang/julia/pull/18850#issuecomment-256214278), so completion timescale is indeterminate. Best!

**Pull request merged**
