### PR TITLE
Update module docstrings (fix #29432)

### LINKED ISSUE #29432: Updating docstrings for modules concatenates
When updating a module docstring, the old one is retained, which is probably not the behavior we want. Demo:
```julia
julia> "Outer docstring" module Outer
       "Inner docstring" module Inner
       "Inner2 docstring" module Inner2
       end
       end
       end
Main.Outer

help?> Outer
search: Outer count_zeros RoundToZero OutOfMemoryError countlines count_ones RoundNearestTiesUp RoundNearestTiesAway

  Outer docstring

help?> Outer.Inner
  Inner docstring

help?> Outer.Inner.Inner2
  Inner2 docstring

julia> "New outer docstring" Outer
Outer

help?> Outer
search: Outer count_zeros RoundToZero OutOfMemoryError countlines count_ones RoundNearestTiesUp RoundNearestTiesAway

  Outer docstring

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  New outer docstring

```

I'm not sufficiently familiar with doc system to be efficient about this, but in case it helps, here's the start of a debugging session:
```diff
diff --git a/base/docs/Docs.jl b/base/docs/Docs.jl
index d409eea9a6..b9650d7fd9 100644
--- a/base/docs/Docs.jl
+++ b/base/docs/Docs.jl
@@ -215,6 +215,7 @@ Adds a new docstring `str` to the docsystem of `__module__` for `binding` and si
 """
 function doc!(__module__::Module, b::Binding, str::DocStr, @nospecialize sig = Union{})
     initmeta(__module__)
+    @show __module__ b str sig meta(__module__)
     m = get!(meta(__module__), b, MultiDoc())
     if haskey(m.docs, sig)
         # We allow for docstrings to be updated, but print a warning since it is possible
```

```julia
julia> using Revise

julia> Revise.track(Base)

julia> "Outer docstring" module Outer
       "Inner docstring" module Inner
       "Inner2 docstring" module Inner2
       end
       end
       end
__module__ = Main.Outer.Inner.Inner2
b = Main.Outer.Inner.Inner2
str = Base.Docs.DocStr(svec("Inner2 docstring"), nothing, Dict{Symbol,Any}(:module=>Main.Outer.Inner.Inner2,:linenumber=>3,:path=>"REPL[3]"))
sig = Union{}
meta(__module__) = IdDict{Any,Any}()
__module__ = Main.Outer.Inner
b = Main.Outer.Inner
str = Base.Docs.DocStr(svec("Inner docstring"), nothing, Dict{Symbol,Any}(:module=>Main.Outer.Inner,:linenumber=>2,:path=>"REPL[3]"))
sig = Union{}
meta(__module__) = IdDict{Any,Any}()
__module__ = Main.Outer
b = Outer
str = Base.Docs.DocStr(svec("Outer docstring"), nothing, Dict{Symbol,Any}(:module=>Main.Outer,:linenumber=>1,:path=>"REPL[3]"))
sig = Union{}
meta(__module__) = IdDict{Any,Any}()
Main.Outer

help?> Outer
search: Outer count_zeros RoundToZero OutOfMemoryError countlines count_ones RoundNearestTiesUp RoundNearestTiesAway

  Outer docstring

help?> Outer.Inner
  Inner docstring

help?> Outer.Inner.Inner2
  Inner2 docstring

julia> "New outer docstring" Outer
__module__ = Main
b = Outer
str = Base.Docs.DocStr(svec("New outer docstring"), nothing, Dict{Symbol,Any}(:module=>Main,:linenumber=>1,:path=>"REPL[7]"))
sig = Union{}
meta(__module__) = IdDict{Any,Any}()
Outer

help?> Outer
search: Outer count_zeros RoundToZero OutOfMemoryError countlines count_ones RoundNearestTiesUp RoundNearestTiesAway

  Outer docstring

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  New outer docstring

julia> "New inner docstring" Outer.Inner
__module__ = Main
b = Main.Outer.Inner
str = Base.Docs.DocStr(svec("New inner docstring"), nothing, Dict{Symbol,Any}(:module=>Main,:linenumber=>1,:path=>"REPL[9]"))
sig = Union{}
meta(__module__) = IdDict{Any,Any}(Outer=>MultiDoc(Type[Union{}], IdDict{Any,Any}(Union{}=>DocStr(svec("New outer docstring"), New outer docstring
, Dict{Symbol,Any}(:typesig=>Union{},:module=>Main,:linenumber=>1,:binding=>Outer,:path=>"REPL[7]")))))
Main.Outer.Inner

help?> Outer.Inner
  Inner docstring

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  New inner docstring

julia> "This is foo" foo(x::Int) = 1
__module__ = Main
b = foo
str = Base.Docs.DocStr(svec("This is foo"), nothing, Dict{Symbol,Any}(:module=>Main,:linenumber=>1,:path=>"REPL[11]"))
sig = Tuple{Int64}
meta(__module__) = IdDict{Any,Any}(Outer=>MultiDoc(Type[Union{}], IdDict{Any,Any}(Union{}=>DocStr(svec("New outer docstring"), New outer docstring
, Dict{Symbol,Any}(:typesig=>Union{},:module=>Main,:linenumber=>1,:binding=>Outer,:path=>"REPL[7]")))),Main.Outer.Inner=>MultiDoc(Type[Union{}], IdDict{Any,Any}(Union{}=>DocStr(svec("New inner docstring"), New inner docstring
, Dict{Symbol,Any}(:typesig=>Union{},:module=>Main,:linenumber=>1,:binding=>Main.Outer.Inner,:path=>"REPL[9]")))))
foo

help?> foo
search: foo floor pointer_from_objref OverflowError RoundFromZero unsafe_copyto! functionloc StackOverflowError @functionloc OutOfMemoryError UndefKeywordError unsafe_pointer_to_objref

  This is foo

julia> "This is new foo" foo(x::Int) = 2
__module__ = Main
b = foo
str = Base.Docs.DocStr(svec("This is new foo"), nothing, Dict{Symbol,Any}(:module=>Main,:linenumber=>1,:path=>"REPL[13]"))
sig = Tuple{Int64}
meta(__module__) = IdDict{Any,Any}(Outer=>MultiDoc(Type[Union{}], IdDict{Any,Any}(Union{}=>DocStr(svec("New outer docstring"), New outer docstring
, Dict{Symbol,Any}(:typesig=>Union{},:module=>Main,:linenumber=>1,:binding=>Outer,:path=>"REPL[7]")))),foo=>MultiDoc(Type[Tuple{Int64}], IdDict{Any,Any}(Tuple{Int64}=>DocStr(svec("This is foo"), This is foo
, Dict{Symbol,Any}(:typesig=>Tuple{Int64},:module=>Main,:linenumber=>1,:binding=>foo,:path=>"REPL[11]")))),Main.Outer.Inner=>MultiDoc(Type[Union{}], IdDict{Any,Any}(Union{}=>DocStr(svec("New inner docstring"), New inner docstring
, Dict{Symbol,Any}(:typesig=>Union{},:module=>Main,:linenumber=>1,:binding=>Main.Outer.Inner,:path=>"REPL[9]")))))
foo

help?> foo
search: foo floor pointer_from_objref OverflowError RoundFromZero unsafe_copyto! functionloc StackOverflowError @functionloc OutOfMemoryError UndefKeywordError unsafe_pointer_to_objref

  This is new foo

```

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Review by MichaelHatherly — APPROVED** [review]

**Comment by fredrikekre** [comment]
CI errors with
```
��� Warning: no docs found for 'Main' in `@docs` block in src/base/base.md:92-96
��� ```@docs
��� Main
��� Core
��� Base
��� ``
```

**Comment by timholy** [comment]
Hmm, any tips about how to efficiently debug this? It happens at the end of the doctests (several minutes), and I get this:
```julia
help?> Main
search: Main DomainError maxintfloat SegmentationFault maximum maximum! Matrix BitMatrix mapslices DenseMatrix timedwait StridedMatrix AbstractMatrix

  Main

  Main is the top-level module, and Julia starts with Main set as the current module. Variables defined at the prompt go in Main, and varinfo lists variables in Main.

  julia> @__MODULE__
  Main

```
which belies the error.

**Comment by MichaelHatherly** [comment]
Probably just needs `Main` to be added to `modules` on https://github.com/JuliaLang/julia/blob/4ef8313c94c85b3e01597455cb71a60a579f632b/doc/make.jl#L211 since the docstring for `Main` is now actually in `Main` rather than `BaseDocs`.

**Comment by timholy** [comment]
Thanks both! Really appreciate the help. If this passes I'm happy to merge whenever.

**Pull request merged**
