### PR TITLE
Added stub for workflow tips in the manual.

### PR DESCRIPTION
**Pull request by twadleigh**
Attempts to record some of the collected wisdom on [this julia-users thread](https://groups.google.com/forum/?hl=en#!topic/julia-users/zhfcT1zs6Qw).

It's really little more than a stub at this point. I'd love to see this grow. If it is considered within scope for the Julia docs, I'd like to see this extended to cover everyday use of common packages, like PyPlot, Gadfly, Images, etc. It would also be great if it could include tricks for editors and other tools that can enhance the Julia experience.

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for doing this. Looks fine to me. You or someone could also point out @vtjnash's alternative suggestion of putting tests inside a module, so that you don't have to scope the calls (at the cost of not being able to re-run single test lines quite so easily).

**Comment by ViralBShah** [comment]
I am pretty sure this will get moved around and refactored as we go on - but seemed good enough to merge for now.

**Comment by twadleigh** [comment]
This is the sort of material that seems most appropriate to a wiki.

**Comment by tkelman** [comment]
Don't think anything in here is 0.4-specific, so labeling for backporting.

**Comment by tkelman** [comment]
backported in 6e0ad20390fc36449b49439a487010d79357fd23

**Pull request merged**
