### PR TITLE
replace Array{...}(shape...)-like calls in stdlib

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request replaces `Array{...}(shape...)`-like calls in stdlib. Ref. #24595. Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
The CI failures should now be fixed. Assuming CI approves and absent objections or requests for time, I plan to merge these changes this evening PT or later. Best!

**Comment by fredrikekre** [comment]
CircelCI: `Dang! We spotted something wrong with your circle.yml. These may be causing your builds to fail. We recommend that you fix them as soon as possible. You may want to look at our docs or contact us us if you’re having trouble.`

**Comment by Sacha0** [comment]
^ @ararslan, guru of all things CircleCI :).

**Comment by ararslan** [comment]
I'm hardly a guru but I'm somewhat familiar with Circle. I'll see if I can get this figured out.

**Comment by Sacha0** [comment]
Thanks all!

**Pull request merged**
