### PR TITLE
choosetests: add a couple missing tests

### PR DESCRIPTION
**Pull request by rfourquet**
Three files are not listed in `testnames` in the `choosetests` function: ["download", "filesystem", "stack_overflow"]`.
Still, the "download" test is run on CI, but not when running `Base.runtests()`. @vtjnash suggested:

> I think downloads pre-dated that and is explicitly listed in the buildbot config instead

It would seem better to me to have it in `testnames`, but this should be then removed from the buildbot config.

Jameson also suggested to leave out "stack_overflow" which is buggy.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by rfourquet** [comment]
Actually the "filesystem" test fails...

**Comment by vtjnash** [comment]
oh yikes, yeah, we truncate the file but not the text
```
diff --git a/test/filesystem.jl b/test/filesystem.jl
index b739b1ecdb..fe748325c7 100644
--- a/test/filesystem.jl
+++ b/test/filesystem.jl
@@ -12,6 +12,7 @@ mktempdir() do dir
   Base.Filesystem.truncate(file, 2)
   @test length(read(file)) == 2
   close(file)
+  text = text[1:2]
 
   # test filesystem truncate (lengthen)
   file = Base.Filesystem.open(filename, Base.Filesystem.JL_O_RDWR)
```

**Comment by rfourquet** [comment]
> oh yikes, yeah, we truncate the file but not the text

Thanks!

Even if not directly related, would you mind that, in this PR, I put the `testnames` array outside of the `choosetests` function, in the global scope? I would need to access it from a package (I currently just copy-paste it).

**Comment by vtjnash** [comment]
I think you would want to just call `choosetests`? The contents of this array don't necessarily correspond one-to-one to actual test files, as some are aliases. I'm not opposed to moving it though (just make another PR)

**Comment by rfourquet** [comment]
> I think you would want to just call `choosetests`

It's not flexible enough, e.g. I wanted to run all the tests except stdlib ones, which I think is not possible without access to the list of test names.

**Pull request merged**
