### PR TITLE
fix compile=all

### LINKED ISSUE #18080: Hang generating sys-all.o
From [julia-users](https://groups.google.com/forum/#!topic/julia-users/UHQtLgdHmRU), generating a system image containing compiled code for all functions hangs:

```
julia5l --output-o sys-all.o --sysimage /mnt/external/build/julia_0.5latest/usr/lib/julia/sys.so --startup-file=no --compile=all --eval nothing
```

### PR DESCRIPTION
**Pull request by vtjnash**
fix #18080

### CODE REVIEW

**Comment by tkelman** [comment]
can we test this somehow?

**Comment by yuyichao** [comment]
Get a new CI service working so that we can afford running a CI with compile=all enabled?

**Comment by tkelman** [comment]
we have buildbots, can add more

**Comment by tkelman** [comment]
Still needs to be tested somewhere or it'll regress again.

**Pull request merged**
