### PR TITLE
Backports for Julia-1.6.2

### LINKED ISSUE #41155: connect_w2w bug when using ssh tunnel
I've run into an issue when using remotecall to call a function that in turn remotecalls another function on a different worker.  The problem only occurs when using workers started with a SSHManager with tunnel=true.

Here is an mwe (however you do somewhere to launch the remote workers on):

```julia
using Distributed

manager = Distributed.SSHManager([("myuser@my_ip_address", 2)])
addprocs_opts = Dict(:exename=>"/path/to/julia",
                     :sshflags=>`-i /path/to/my/key.pem`,
                     :dir=>"/home/myuser",
                     :tunnel=>true)
p = addprocs(manager; addprocs_opts...)

@everywhere begin
    function get_remote_ids(w2::Int)
        caller_id = myid()
        called_id = remotecall_fetch(myid, w2)
        return [caller_id, called_id]
    end
end

remotecall_fetch(get_remote_ids, p[1], p[2])
```

This results in
```
      From worker 6:	┌ Error: Error on 7 while connecting to peer 6, exiting
      From worker 6:	│   exception =
      From worker 6:	│    TypeError: in typeassert, expected Tuple{String, Int64}, got a value of type Tuple{SubString{String}, Int64}
      From worker 6:	│    Stacktrace:
      From worker 6:	│      [1] connect_w2w(pid::Int64, config::WorkerConfig)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/managers.jl:584
      From worker 6:	│      [2] connect(manager::Distributed.DefaultClusterManager, pid::Int64, config::WorkerConfig)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/managers.jl:519
      From worker 6:	│      [3] connect_to_peer(manager::Distributed.DefaultClusterManager, rpid::Int64, wconfig::WorkerConfig)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:357
      From worker 6:	│      [4] (::Distributed.var"#117#119"{Int64, WorkerConfig})()
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:341
      From worker 6:	│      [5] exec_conn_func(w::Distributed.Worker)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl:179
      From worker 6:	│      [6] exec_conn_func(id::Int64)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl:173
      From worker 6:	│      [7] (::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}})()
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:278
      From worker 6:	│      [8] run_work_thunk(thunk::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      From worker 6:	│        @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:63
      From worker 6:	│      [9] macro expansion
      From worker 6:	│        @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:278 [inlined]
      From worker 6:	│     [10] (::Distributed.var"#105#107"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      From worker 6:	│        @ Distributed ./task.jl:411
      From worker 6:	└ @ Distributed /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:364
Worker 7 terminated.
```

I've been able to work around it for now by relaxing the type assertion on line 577 for managers.jl
https://github.com/JuliaLang/julia/blob/47f9139e88917813cb7beee5e690c48c2ac65de4/stdlib/Distributed/src/managers.jl#L576-L582
to 
```julia
     (rhost, rport) = notnothing(config.connect_at)::Tuple{AbstractString, Int}
```

### LINKED ISSUE #41416: Adding a keyword argument to a call can make a splatted default argument disappear
On 1.7 and 1.6.2 backport branch:

```jl
julia> f(a...="a"; b=true) = a
f (generic function with 2 methods)

julia> f() # ok
("a",)

julia> f(;b=false) # wut?
()
```

On 1.6.1:

```jl
julia> f(a...="a"; b=true) = a
f (generic function with 2 methods)

julia> f() # ok
("a",)

julia> f(;b=false) # ok
("a",)
```

Reduced from this PkgEval error: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4dd3346_vs_dd12291/Publish.1.6.2-pre-40f17341a28.log.
Since this is also present in the backport branch the culprit is likely to be among https://github.com/JuliaLang/julia/pull/40702/commits.

### PR DESCRIPTION
**Pull request by KristofferC**
- [x] #39975 - Fix wrong := REPL documentation
- [x] #40496 - fix %a/%A format for zeros
- [x] #40509 - Fix `kron` with `Diagonal`
- [x] #40520 - SparseArrays: add Printf to test deps.
- [x] #40549 - unexport cat_shape
- [x] #40551 - Fix rational division by zero
- [x] #40575 - [cli] Provide `.type` and `.size` annotations for symbols
- [x] #40593 - avoid excessive inlining of Ryu
- [x] #40607 - REPL: Fix incorrect docstring for .. (#40563)
- [x] #40669 - Document UInt return type of objectid
- [x] #40653 - Set ModFlag for `Debug Info Version` to Warning
- [x] #40685 - fix consistency of trimtrailingzeros (Ryu)
- [x] #40752 - Fix Win resource FILEVERSION
- [x] #40755 - do not trim trailing zeros of integral part
- [x] #40689 - make Printf's general format C11 compliant
- [x] #40785 - Fix inference of max_values(::Union)
- [x] #40487 - safepoints are required in any lock than may be used with allocations
- [x] #40608 - Fix showindices for IdentityUnitRange
- [x] #40345 - add option to `compilecache` so that Pkg precompilation can not skip different versions of loaded modules
- [x] #40512 - Sign julia.exe executable within the installer
- [x] #39005 - Use `strcmp()` to compare `f_lib` and `JL_LIBJULIA_DL_LIBNAME`
- [x] #39768 - Use copysign LLVM intrinsic rather than bithack ourselves
- [x] #39975 - Fix wrong := REPL documentation
- [x] #40345 - add option to `compilecache` so that Pkg precompilation can not skip different versions o
- [x] #40881 - restore performance of `hash` for `BigInt` and `Rational{BigInt}`
- [x] #41048 - optimizer: add missing bounds checks to avoid ICE
- [x] #40067 - fix unsoundness in fieldtype of Tuple with non-Type params
- [x] #40765 - Add support for new Manifest.toml format during code load
- [x] #41079 - TOML: fix some printing of special characters
- [x] #40526 - Fix eigvecs(:::SymTridiagonal) with longer off-diagonal vector
- [x] #41083 - Return rhs in ldiv! for SVD and add a test
- [x] #41145 - silence output from a TOML test
- [x] #41169 - Fix `in(x, ::AbstractRange)` for `NaN`/`Inf`
- [x] #41229 - Fix `Rational{T}` constructor for abstract `T`
- [x] #41203 - reverse search fix
- [x] #41256 - [buildkite] Implement secrets encryption and sandboxing
- [x] #41294 - fix preference loading for non string value
- [x] #41305 - Fix typeassert in worker-worker connection, fixes #41155.
- [x] #41345 - fix `threadcall` for new ccall lookup strategy
- [x] #41395 - backport #41363: fix equality of QRCompactWY
- [x] #41427 - fix #41416, splatted default argument lost with keyword argument

Non-merged PRs with backport label:
- [ ] #41228 - fix some issues with equality of factorizations
- [ ] #41041 - fix command literals with trailing backslashes
- [ ] #40820 - Fix log message id from at-deprecate to be a Symbol.
- [ ] #40038 - Allow the conversion of AbstractUnitRanges to OrdinalRanges

### CODE REVIEW

**Comment by carlocab** [comment]
Is there any chance for backporting ba653ecb1c81f1465505c2cea38b4f8149dd20b3 from #37723? It seems all the other commits from that PR were backported in #38949 except for that one.

**Comment by StefanKarpinski** [comment]
> Is there any chance of backporting [ba653ec](https://github.com/JuliaLang/julia/commit/ba653ecb1c81f1465505c2cea38b4f8149dd20b3) from #37723? It seems all the other commits from that PR were backported in #38949 except for that one.

Seems ok to me since it's only a build system change and arguably a bug fix.

**Comment by carlocab** [comment]
Thank you!

**Comment by IanButterworth** [comment]
Could https://github.com/JuliaLang/julia/pull/40765be backported here and this be merged early, so that Pkg backports can be tested against changes in here that need to be on the release branch

**Comment by StefanKarpinski** [comment]
I'll tag Tar v1.9.3 once it's simmered on the backports-release-1.6 branch for a while and seems to work well.

**Comment by StefanKarpinski** [comment]
Looks like several commits got force pushed away from this branch, including:

- 54ea57fff1 bump Tar from v1.9.2 to v1.9.3
- 232ac98ddb bump Downloads from v1.4.1 to v1.4.2
- 51b28a945a fix #40742, unset `has_concrete_subtype` for types like `Tuple{:x}`

I have another update to Tar that I'd like to push here but before I do that it would be good to sort out a procedure for doing this that won't get blown away again.

**Comment by KristofferC** [comment]
> I have another update to Tar that I'd like to push here but before I do that it would be good to sort out a procedure for doing this that won't get blown away again.

The best way is to open a PR against the backport release and mark it with the backport label.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = "#1.6.1")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-858567053) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/bc1ed72_vs_dd12291/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-858567235) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0c65354_vs_dd12291/report.md). cc @christopher-dG

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AprilTags", "BLASBenchmarksCPU", "BetterFileWatching", "Chron", "CodeTransformation", "FilesystemDatastructures", "GalacticOptim", "GenericSVD", "GeoDataFrames", "HomotopyContinuation", "ImarisWriter", "LazyArrays", "LoggingExtras", "Publish", "SeaPearl", "SpatialJackknife", "StatsFuns", "SymbolServer", "TarIterators"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-859399513) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/531255a_vs_dd12291/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AprilTags", "CodeTransformation", "GenericSVD", "HomotopyContinuation", "LazyArrays", "Publish", "SymbolServer"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-859505235) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/6d74a23_vs_dd12291/report.md). cc @maleadt

**Comment by KristofferC** [comment]
AprilTags looks like it needs some attention.

**Comment by vtjnash** [comment]
That is trying to eval a lookup of `AprilTags.libapriltag` at runtime, which is forbidden. The value must be constant value (e.g. `libapriltag`), not a function call (e.g. `getproperty`)

**Comment by KristofferC** [comment]
@vtjnash, That is my bad with the MWE then, the original example is as:

https://github.com/JuliaRobotics/AprilTags.jl/blob/6fc29b4c796cdcb4aaf30a8d4119faba8cfb85bb/src/wrapper.jl#L414-L416

and no `getproperty`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-870311279) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/40f1734_vs_dd12291/report.md). cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-870310938) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4dd3346_vs_dd12291/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BLASBenchmarksCPU", "BioStructures", "CopEnt", "ImarisWriter", "IncrementalInference", "KernelDensityEstimatePlotting", "KrylovMethods", "LazyArrays", "PkgCite", "Publish", "RoMEPlotting", "SDDP", "SalesForceBulkApi", "SymbolServer", "Symbolics", "YAActL"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-870925397) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4dd3346_vs_dd12291/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BLASBenchmarksCPU", "ImarisWriter", "KernelDensityEstimatePlotting", "LazyArrays", "PkgCite", "Publish", "RoMEPlotting", "SymbolServer", "Symbolics"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40702#issuecomment-872029531) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/85b9752_vs_dd12291/report.md). cc @maleadt

**Pull request merged**
