### PR TITLE
Log to stdout / stderr to fix #26798

### LINKED ISSUE #26798: redirect_stderr() and redirect_stdout() do not control logging output
```
redirect_stderr()
redirect_stdout()
@warn "should not be able to see it"
```
The output is 
```
┌ Warning: should not be able to see it
└ @ Main t.jl:3
```
Expected no output.

### PR DESCRIPTION
**Pull request by ghost**
Create new `DefaultLogger` with the same style as `SimpleLogger` but that logs `Info` to `stdout` and `Warning` / `Error` to `stderr` (even when redirected) to fix #26798

### CODE REVIEW

**Comment by gaika** [comment]
How about getting rid of `SimpleLogger`?

**Comment by fredrikekre** [comment]
> How about getting rid of `SimpleLogger`?

Can't we just fix `SimpleLogger` if it is broken?

**Comment by gaika** [comment]
`SimpleLogger` and proposed `DefaultLogger` serve different purposes: first one is for logging into one stream / file and the new one is for logging into `stdout` and `stderr`. The functionality overlap is tiny, it is easier to keep them separate. `DefaultLogger` is not even exported, so no added complexity on the user side.

**Comment by StefanKarpinski** [comment]
It seems like the names of these could be more evocative of their intentions. Perhaps `FileLogger` and `ConsoleLogger` would make more sense since that's apparently what they're intended for? There are lots of ways things can be simple and default doesn't really tell me anything either except that it's probably what I get if I don't ask for anything else. But what does it do?

**Comment by vtjnash** [comment]
I merged a slight variation of this in #40423

**Pull request closed without merging**
