### PR TITLE
Solves the inconsistency #10729 and add tests

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for getting to this so quickly!

I guess my only (minor) question is whether we need to worry about the performance. I don't have much insight into whether the increasing complexity of these functions will affect their performance in practice. Have you done any benchmarking compared to the version before #9416?

Overall, though, correctness seems more important than speed.

**Comment by lbenet** [comment]
No, I haven't done any benchmarks. I agree that this is not an elegant solution at all, and may indeed have an impact in speed. I simply put it there to avoid further problems, e.g. Winston. 

Yet, after reading #7866, I realized that according to the standard, `min` and `max` should not care about the sign of zero. This is inconsistent is present in v0.3, in the sense that `min(0.0,-0.0)` and `min(-0.0,0.0)` differ in the sign bit.

**Comment by StefanKarpinski** [comment]
Ugh. NaNs are the worst.

**Comment by StefanKarpinski** [comment]
The tests look good and correctness is more important. I'll see if I can figure out a way to make this faster.

**Comment by StefanKarpinski** [comment]
I guess we should merge this and then work on making it faster.

**Pull request merged**
