### PR TITLE
@ref error on ⊈

### PR DESCRIPTION
**Pull request by udohjeremiah**
No @ref provided on `⊆` and also `isusbset` not spaced with comma.

### CODE REVIEW

**Comment by ViralBShah** [comment]
This is leading to a `makedocs` error.

**Comment by udohjeremiah** [comment]
> This is leading to a `makedocs` error.

On what line of the changes made?

**Comment by ViralBShah** [comment]
This PR is causing the error.

**Comment by mcabbott** [comment]
The edit here describes `issubset`, `⊆`, `⊈` as being three things. That's not true, `(⊆) === issubset`, it's just an alias. Which is, I presume, why the present text has it in brackets next to the ascii name.

**Comment by udohjeremiah** [comment]
> The edit here describes `issubset`, `⊆`, `⊈` as being three things. That's not true, `(⊆) === issubset`, it's just an alias. Which is, I presume, why the present text has it in brackets next to the ascii name.

Maybe, but I was only thinking a link can be placed on `⊆` as well, so users can click on it to get to its definition.

**Comment by udohjeremiah** [comment]
> The edit here describes `issubset`, `⊆`, `⊈` as being three things. That's not true, `(⊆) === issubset`, it's just an alias. Which is, I presume, why the present text has it in brackets next to the ascii name.

Maybe, but I was only thinking a link can be placed on `⊆` as well, so users can click on it to get to its definition.

**Comment by ViralBShah** [comment]
Can we close this?

**Pull request closed without merging**
