### PR TITLE
deprecate `(;)` (#30115)

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Looks good. Do you know whether any packages are still using this? I know a few were the last time this change was discussed but I don't know whether they were fixed.

**Review by StefanKarpinski — APPROVED** [review]
❤️

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by maleadt** [comment]
This ran into some NewPkgEval/Nanosoldier bug (PkgEval stuff is still a WIP), so let's try again:
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by maleadt** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/34039#issuecomment-563912807):
```
KeyError(Nanosoldier [89f34f1a-2e6b-52eb-a20f-77051b03b735])
```
cc @maleadt

**Comment by maleadt** [comment]
> [Your test job](https://github.com/maleadt/julia/commit/1d8d9c1793b241fc3d433d2efb6c9c2a532a3fb1#commitcomment-36359783) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/59cd9039e8baa468754d3d592ab00d13fb65e895/pkgeval-1d8d9c1_vs_9babbf5/report.md). cc @maleadt

PkgEval proving it's worth, of the new failures at least [Dataflow.jl](https://github.com/maleadt/BasePkgEvalReports/blob/59cd9039e8baa468754d3d592ab00d13fb65e895/pkgeval-1d8d9c1_vs_9babbf5/logs/DataFlow/1.4.0-DEV-1d8d9c1793.log) and [Mocking.jl](https://github.com/maleadt/BasePkgEvalReports/blob/59cd9039e8baa468754d3d592ab00d13fb65e895/pkgeval-1d8d9c1_vs_9babbf5/logs/Mocking/1.4.0-DEV-1d8d9c1793.log) fail because of this PR.

**Comment by JeffBezanson** [comment]
Deprecation warning, then?

**Pull request merged**
