### PR TITLE
emit a trap instruction before an inferred unreachable function return

### PR DESCRIPTION
**Pull request by vtjnash**
@Keno as you requested

``` julia
julia> f() = f()
f (generic function with 1 method)

julia> g() = f()
g (generic function with 1 method)

julia> @code_llvm g()

; Function Attrs: noreturn
define void @julia_g_49908() #0 {
top:
  call void @julia_f_49909()
  call void @llvm.trap()
  unreachable
}
```

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Why is this desirable?

**Comment by vtjnash** [comment]
helps find inference errors / #265

**Comment by StefanKarpinski** [comment]
It would be good to have a brief note motivating the change in the commit message.

**Comment by yuyichao** [comment]
I assume this gets lowered to something cheap and small like `ud2`?

**Comment by vtjnash** [comment]
"This intrinsic is lowered to the target dependent trap instruction. If the target does not have a trap instruction, this intrinsic will be lowered to a call of the abort() function."

**Comment by Keno** [comment]
Should we only emit the trap if we build julia in debug mode?

**Comment by StefanKarpinski** [comment]
Is there a substantial cost to doing this?

**Comment by Keno** [comment]
Probably not.

**Comment by StefanKarpinski** [comment]
Then let's just do it unconditionally.

**Comment by tkelman** [comment]
If this is behavior we want, can we test for it?

**Comment by vtjnash** [comment]
The point of emitting a trap instruction is that the code path is (supposed to be) unreachable

**Pull request merged**
