### PR TITLE
Devdocs on fixing precompile hangs, take 2

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is #50914, with only the documentation changes, plus an improvement to the warning message.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by timholy** [comment]
This should be updated to recommend the Aqua test, now that https://github.com/JuliaTesting/Aqua.jl/pull/174 has merged. Though one issue is that Aqua v0.8 has not yet been released. Do you want to edit it or should I?

**Comment by timholy** [comment]
Done. I approve merging, but feel free to check the (slightly modified) description first.

**Comment by IanButterworth** [comment]
One build job failed 3 times so trying an update

**Comment by IanButterworth** [comment]
Linux x86 musl is consistently failing here. I'm trying another update

**Comment by IanButterworth** [comment]
The issues remain on musl which I've not seen elsewhere.
Either
```
LLVM ERROR: out of memory
Allocation failed
[10578] signal 6 (-6): Aborted
```
or
```
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
terminate called recursively
[10578] signal 6 (-6): Aborted
```

**Pull request merged**
