### PR TITLE
Introduce build variable SRCCACHE

### PR DESCRIPTION
**Pull request by vchuravy**
This introduces a new build variable for dependencies `SRCCACHE` that defaults to `SRCDIR/srccache`. My goal with this it to have the option to move `SRCCACHE` outside the build environment to minimise download times. I am contemplating whether we should also allow to split the raw tarballs from the extracted (and maybe patched) sources.

### CODE REVIEW

**Comment by maleadt** [comment]
+1 on a split cache for downloads and extracted sources (would [simplify](https://github.com/maleadt/julia-buildbot/blob/c4b5ed75046db5dc163232d18fc50c661d7ee2a4/julia/master.cfg#L282-L290) my CI rules).

**Comment by kshyatt** [comment]
Can we get a rebase on this?

**Review by vtjnash — APPROVED** [review]
needs a rebase

**Comment by tkelman** [comment]
Rebased since I want to use this for something. Will merge soon if no comments.

**Pull request merged**
