### PR TITLE
Missing.md updated

### PR DESCRIPTION
**Pull request by mishmanners**
Typo fixes, paragraph fixes, grammar usage, and "massage" of text.

Hopefully that makes it much easier to read and understand 😄

### CODE REVIEW

**Comment by KristofferC** [comment]
Welcome to Julia and thanks for a nice first contribution!

The removal of most of the line breaks makes it a little bit hard to see from the diff what the change are.
The contribution guide suggests a 92 character line length limit and I think that also applies to the documentation source files.

**Comment by mishmanners** [comment]
Oh I didn't remove any of the line breaks, just made it so things aren't squashed onto one side of the screen. Lots of updates, typos, and grammar fixes, but I'll fix the failed whitespace.

**Comment by KristofferC** [comment]
> just made it so things aren't squashed onto one side of the screen

I guess that is what I meant with

> The contribution guide suggests a 92 character line length limit and I think that also applies to the documentation source files.

**Comment by mishmanners** [comment]
Ahh right. All good. Did you figure out what broke?

**Comment by ViralBShah** [comment]
Would it be safe to merge this since tests are passing on linux64?

**Review by inkydragon — CHANGES_REQUESTED** [review]

**Review by mishmanners — COMMENTED** [review]
LGTM.

**Comment by mishmanners** [comment]
@KristofferC let me know if there's anything else I need to do to help get this merged.

**Review by KristofferC — APPROVED** [review]
Looks good now after the fixups by @fredrikekre. (If  you look at the diff now vs the one before you can see how much easier it is to review now).

**Pull request merged**
