### PR TITLE
Implement permutedims for general AbstractArrays

### PR DESCRIPTION
**Pull request by timholy**
In #15810, there was some concern expressed about converting to `Array` before calling `permutedims`. This PR is an alternative, implementing a ~~naive (non-cache-friendly)~~ general `permutedims` that allocates the output using `similar`, potentially preserving the type information.

Performance is not dreadful, but is about two-fold worse than the other implementation (after warmup):

``` jl
julia> A = rand(100,101,102);

julia> B = sub(A, collect(1:size(A,1)), :, :);

julia> isa(B, StridedArray)
false

julia> @time (Bc = copy(B); permutedims(Bc, [3,1,2]));
  0.018679 seconds (21 allocations: 15.720 MB, 37.47% gc time)

julia> @time permutedims(B, [3,1,2]);
  0.035161 seconds (23 allocations: 7.861 MB)
```

It is half the memory allocation, however.

### CODE REVIEW

**Comment by timholy** [comment]
I implemented a cache-friendly algorithm, and now it's faster than making a copy:
```jl
julia> @time permutedims(B, perm);
  0.016715 seconds (30 allocations: 7.861 MB, 29.33% gc time)

julia> @time (Bc = copy(B); permutedims(Bc, [3,1,2]));
  0.018182 seconds (21 allocations: 15.720 MB)
```
So let's go with this version.

**Comment by tkelman** [comment]
the block sizes, 7s and 8s would be good to give const names

**Comment by Jutho** [comment]
This is cool, strange that I have missed it 12 days ago. I tried this myself a while back, but never managed to get any proper efficiency. I'll study your implementation as soon as I have some more time. How does it compare in speed to the normal implementation for `StridedArray`s, which I see is still in place?

**Comment by timholy** [comment]
I haven't done "serious" performance tuning or comparison. Because of #9080 it can't be as good as the strided version, but hopefully #9080 will go away someday.

**Comment by Jutho** [comment]
In preparing a presentation about my package `TensorOperations.jl` today, I rerun some old Jupyter slides and think it is worth pointing out that some regressions (which I think are due to this PR) are pretty severe. We might have been willing to sacrifice some performance, but do we really want this:

```julia
A=randn(10,10,10,10,10,10,10,10);
B=zeros(10,10,10,10,10,10,10,10);
@time permutedims!(B,A,[8,7,6,5,4,3,2,1]); # -> 18 seconds
```
Yes it's a big tensor, and the worst possible permutation, but the old Julia base code was able to do it in about 2 seconds, so the current situation is almost 10 times worse. 
(TensorOperations.jl does it in about 0.26 seconds)

**Pull request merged**
