### PR TITLE
Fix #5690: Julia to parse own float format "1f0"

### PR DESCRIPTION
**Pull request by mdavezac**
Closes #5690

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This approach seems very slow.

**Comment by mdavezac** [comment]
So it is. Seems that synthesizing the second trial string is the slow part. I'll try and see what I can think of.

**Comment by mdavezac** [comment]
This new approach modifies the string in C and does not incur much of a performance penalty. I'm not sure it will cover other abstract strings though.

**Comment by mdavezac** [comment]
ping! I think this works now. I don't think the CI failure is related.

**Comment by StefanKarpinski** [comment]
Since we already ship [an implementation of `strtod`](https://github.com/JuliaLang/julia/blob/master/src/support/strtod.c#L208) it seems like we could just unconditionally use that (instead of only using it on platforms that don't have a native implementation) and then modify this one line to accept `f` and `F` as well as `e` and `E`:

https://github.com/JuliaLang/julia/blob/c31d126ac7ee425f3e121c16016844fb64a0c950/src/support/strtod.c#L208

That would have the further benefit of making us less dependent on different behaviors on different systems.

**Comment by StefanKarpinski** [comment]
Also: I'm impressed with how deep you've gone with this. Thank you for the effort and sorry to string you along.

**Comment by mdavezac** [comment]
Actually, that's not quite correct. The line you point to in strtod is about translating the french virgule, or other local variants, to a decimal point. In any case, I'll try to modify strtod to parse "f".

**Pull request closed without merging**
