### PR TITLE
TST: improve coverage of array.jl

### PR DESCRIPTION
**Pull request by catawbasam**

### CODE REVIEW

**Comment by catawbasam** [comment]
For type-related tests, I think you want someone more comfortable with the logic of the type system (see #10255).  
Shall I close this PR?

**Comment by nalimilan** [comment]
No, don't worry, you'll probably get this right, and people can help you if you hesitate. Also, tests are mostly meant to catch regressions: you can start assuming that the types of the current outputs are correct.

**Comment by catawbasam** [comment]
Ok, I'm hesitating and would appreciate some advice.

 '===' uses pointer equality for mutable objects like arrays and strings.  Given that, these results make sense:
```
julia> ca = complex([0,0,0],0)
3-element Array{Complex{Int64},1}:
 0+0im
 0+0im
 0+0im

julia> ca2=Complex{Int64}[0+0im, 0+0im, 0+0im]
3-element Array{Complex{Int64},1}:
 0+0im
 0+0im
 0+0im

julia> ca == ca2
true
julia> ca === ca2
false
```

But what is the right type check here? `typeof()`?
```
julia> ca==ca2 && typeof(ca)==typeof(ca2)
true
```
`

**Comment by jiahao** [comment]
That was what I had in mind.

**Comment by jakebolewski** [comment]
I would do  `all(map(is, ca, ca2))`.

**Comment by catawbasam** [comment]
So 
```
julia> ca3 = Complex[0+0im, 0+0im, 0+0im]
3-element Array{Complex{T<:Real},1}:
 0+0im
 0+0im
 0+0im

julia> all(map(is, ca, ca3))
true
```

Implying this test would pass even if the return type of `complex([0,0,0],0)` changed to `Array{Complex{T<:Real},1}` at some point.

Or do we need `ca==ca2 && typeof(ca)==typeof(ca2) && all(map(is, ca, ca3))`?

**Comment by catawbasam** [comment]
Is there an existing function that does the equivalent of `all(map(is, ca, ca2)) && typeof(ca)==typeof(ca2)`? 
If not, maybe there should be.

**Comment by vtjnash** [comment]
i would check the arrayops.jl tests, i know there's usage of `@test_approx_eq` with a eps=0

**Pull request closed without merging**
