### PR TITLE
RFC: IdDict{K,V} as wrapped ObjectIdDict

### PR DESCRIPTION
**Pull request by mauro3**
This adds an `IdDict{K,V}` which uses `===` and `object_id` for equality and hashing as is needed for [#24354](https://github.com/JuliaLang/julia/pull/24354#issuecomment-339856574).  It is implemented by wrapping the good old `ObjectIdDict` and using type assertions on the getters/setters.  This is an alternate implementation of #24932, as was suggested by @JeffBezanson in https://github.com/JuliaLang/julia/pull/24932#issuecomment-351434860.  Unlike #24932, this PR passes all tests locally and should be mostly ready to go.

This PR deprecates the "old" `ObjectIdDict` in favor of the new `IdDict`.  To make this work I had to rename `ObjectIdDict` to something else: `_ObjectIdDict`.  Note though that `_ObjectIdDict` is still used and needed in the core of Julia.

Performance of the `IdDict` is a bit worse (25%) than for `ObjectIdDict`, presumably because of the extra layer, as the somewhat rudimentary tests in the [gist](https://gist.github.com/mauro3/ada59b1fd9a09202631edccf255c4e1b) show.

RFCs:
- [ ] is the rename of `ObjectIdDict` necessary or could it be deprecated without rename?
- [ ] One thing I am not sure about is the, now updated, following statement in the docs: "Alternatively, you can use the `IdDict` dictionary type, which is specially handled by precompilation so that it is safe to initialize at compile-time." Is this still true? If not it probably should be made true. This needs checking by someone!

This should probably be squashed before merging.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
It seems to me `_ObjectIdDict` should be unnecessary. What goes wrong without it?

**Comment by mauro3** [comment]
Not renaming (going back to 7d4908edf9) and adding to deprecated.jl:
```
export ObjectIdDict
const _dep_message_ObjectIdDict = ", use IdDict{Any, Any} instead"
deprecate(Base, :ObjectIdDict)
```
compiles but throws dep-warns from the (legitimate) usages in Base.  Can you point me to how you would go about it?  One option could be to only have ObjectIdDict in Core, but I don't know how that works or whether that is a good strategy.  So, I need a bit of guidance for this.

**Comment by JeffBezanson** [comment]
The uses in Base can use `IdDict{Any,Any}` directly, or we could provide the `ObjectIdDict` alias without deprecation.

**Comment by mauro3** [comment]
I changed the usages of `ObjectIdDict` which are after `dict.jl` in the boot-strap to `IdDict`, but the ones before (in Core) still use `ObjectIdDict`.  To move the Core-uses to `IdDict` is beyond my skills.

I think it would be nice to deprecate `ObjectIdDict`, otherwise we provide two types with almost the same use, leading to function signatures like `f(d::Union{IdDict,ObjectIdDict}) = ...`.  One strategy could be to rename & deprecate in 0.7 and in 1.0 rename again to `ObjectIdDict` but not export anymore (to get rid of the ugly `_ObjectIdDict` name).

**Comment by JeffBezanson** [comment]
Replaced by #25210

**Pull request closed without merging**
