### PR TITLE
[RFC] deprecate falses and trues

### PR DESCRIPTION
**Pull request by fredrikekre**
Ref #24595 and especially (the apparently not so popular comment) https://github.com/JuliaLang/julia/issues/24595#issuecomment-348107176

Three distinct commits:
1. Introduce new `BitArray(::Bool, dims...)` constructors.
2. Deprecates `falses(A::AbstractArray)` in favor of `BitArray(false, size(A))` and `trues(A::AbstractArray)` in favor of `BitArray(true, size(A))` (these were tested *once* and not  used anywhere else, note that these should probably be deprecated similar to #24656, but if we don't do it the way as in this PR we have to do it the more ugly way: `@deprecate falses(A) fill!(similar(A), false)`)
3. Deprecate `falses(dims...)` in favor of `BitArray(false, dims...)` and `trues(dims...)` in favor of `BitArray(true, dims...)`.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Maybe `fill` with a Bool argument should return a BitArray.

This is a bit inconsistent with iterator arguments to array constructors, since a scalar only iterates one value.

**Comment by nalimilan** [comment]
> This is a bit inconsistent with iterator arguments to array constructors, since a scalar only iterates one value.

Yet it sounds so natural to recycle a scalar to fill the array that maybe it's worth an exception? Scalars acting like 1-element collections is so confusing...

**Comment by GunnarFarneback** [comment]
> Ref #24595 and especially (the apparently not so popular comment) #24595 (comment)

To expand on what I disliked about it:

> `falses((m,n))` -> `BitMatrix(false, (m,n))` isn't so bad

Yes, it is. E.g. in https://discourse.julialang.org/t/half-vectorization/7399 the construction `A[tril(trues(A))]` would turn into `A[tril(BitArray(true, size(A)))]` with this PR. This is not at all as readable and I truly don't care about the typename. In fact I'd rather prefer not having to remember whether I'm supposed to write `BitArray`, `BitMatrix`, `Matrix{Bool}` or something else and what performance implication choosing the wrong one might have. Just give me something that can hold my trues in a good way.

(For the record I'm on board with `A[tril(trues(size(A)))]`. It's the next step of inconvenience I'm not buying.)

**Comment by Sacha0** [comment]
Sounds like at least a variation of the second proposal, i.e. deprecating `{false|trues}(A::AbstractArray)` -> `{falses|trues}(size(A))`, might have reasonable support? Best!

**Pull request closed without merging**
