### PR TITLE
When tab completing dict keys don't fall back to complete files in current directory

### LINKED ISSUE #51481: REPL tab completion hints showing files in dict strings is a bit awkward
Screenshot 2023-09-27 at 11 36 50 AM

Is there anything that could/should be done to improve this?

If it knows it's in a dict bail out of completions before searching for current directory files? Just do that for the hint, or also stop tab completes?

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/51481

### CODE REVIEW

**Comment by oscardssmith** [comment]
imo this is the wrong approach. it would be a lot better to base this on if we're calling getindex since that would work for other types (unless you have a type representing a directory structure...)

**Comment by IanButterworth** [comment]
> unless you have a type representing a directory structure...

Seems like that would make your suggestion breaking? Or if you have an idea of how to implement it I'd be happy to try it out

**Comment by oscardssmith** [comment]
sorry for the confusion. What I meant is that the suggestion I had would break the use for an `AbstractDict` who's keys were files.

**Comment by IanButterworth** [comment]
I get that but how would I guard against that? AFAIK there isn't a `File` type in Base? Does that mean your suggestion can't be implemented?

**Comment by oscardssmith** [comment]
I still think hardcoding on `Dict` is a bad idea.

**Comment by IanButterworth** [comment]
Ok. I'll close this and https://github.com/JuliaLang/julia/issues/51481 can track the issue

**Pull request closed without merging**
