### PR TITLE
Add explanation about top-level compilation to timing macros

### PR DESCRIPTION
**Pull request by IanButterworth**
Following discussions in https://github.com/JuliaLang/julia/issues/39760

Text based on @JeffBezanson's edits in https://github.com/JuliaLang/www.julialang.org/pull/1135/commits/ef6846d9ca3eb8268e858649f0aa318c776ce2c5

### CODE REVIEW

**Comment by IanButterworth** [comment]
To illustrate the need for this note
```julia
julia> @eval function f(a)  # Expensive function to compile. (Thanks @yuyichao!)
                         $(quote $([:(a = a + a * 10 + (a > 0 ? $i : 0.2)) for i in 1:401]...) end)
                         $(quote $([:(a = a + a * 10 + (a > 0 ? $i : 0.2)) for i in 1:401]...) end)
                         return a
                     end
f (generic function with 1 method)

julia> @time f(2)
  0.000000 seconds
```

```julia
julia> @eval function f(a)  # Expensive function to compile. (Thanks @yuyichao!)
                         $(quote $([:(a = a + a * 10 + (a > 0 ? $i : 0.2)) for i in 1:401]...) end)
                         $(quote $([:(a = a + a * 10 + (a > 0 ? $i : 0.2)) for i in 1:401]...) end)
                         return a
                     end
f (generic function with 1 method)

julia> @time @eval f(2)
 13.801006 seconds (6.26 M allocations: 317.365 MiB, 3.65% gc time, 100.02% compilation time)
```

**Comment by Keno** [comment]
I wonder if there is some way that we can have the former expression hint that compile time was excluded. I guess we could have the REPL check if what you're evaling is a literal `@time ...` and give you a hint, but that might be a little out there. I'm just a big fan of in-context discovery, since I basically never read the docs ;)

**Comment by ufechner7** [comment]
Looks good to me. :)

**Comment by ufechner7** [comment]
What is the reason for the failure on linux32? Is this ready to be merged?

**Comment by ufechner7** [comment]
Bump.

**Comment by DilumAluthge** [comment]
@JeffBezanson @Keno What are your thoughts on this PR?

**Comment by ufechner7** [comment]
Can this PR get a backport label? It would be nice to have it n 1.6 .

**Pull request merged**
