### PR TITLE
Add a test for aborting a rebase

### PR DESCRIPTION
**Pull request by simonbyrne**
Let's try #21209 again, and see if we can figure out what was failing.

### CODE REVIEW

**Comment by kshyatt** [comment]
I ran this locally and it's passing after a rebase onto latest `master`???

**Comment by simonbyrne** [comment]
Sorry, I tried rebasing but that messed it up, I guess because it had been merged previously.

**Comment by tkelman** [comment]
I think it may depend on whether you have a global gitconfig set.

**Comment by simonbyrne** [comment]
I managed to fix it via `cherry-pick`.

**Comment by simonbyrne** [comment]
or were you talking about the actual problem with the PR?

**Comment by tkelman** [comment]
yeah, the test failure may depend on your global gitconfig

**Comment by kshyatt** [comment]
I'm not clear on what's going on with Travis here - @simonbyrne can you rebase on top of master or not?

**Comment by kshyatt** [comment]
Should I try force-pushing from my rebased branch?

**Comment by kshyatt** [comment]
Found and fixed the issue will push momentarily.

**Comment by kshyatt** [comment]
The problem was with another testset for simple `merge` calls, which was trying to merge the wrong branch into itself and lots of other silliness. Pretty sure I wrote those tests so 🥚  on my face...

**Comment by kshyatt** [comment]
Test failure on AV is in `pkg`. @tkelman @simonbyrne good to merge?

**Pull request merged**
