### PR TITLE
Add U+297A (`⥺`) and U+2977 (`⥷`) to binary operators

### LINKED ISSUE #45962: Why is `⥺` not an operator?
I can see `⭄` (Rightwards Arrow Through Superset) is recognized as an operator in the [parser](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm). But why is `⥺` not?

### PR DESCRIPTION
**Pull request by singularitti**
Closes #45962

### CODE REVIEW

**Review by Moelf — APPROVED** [review]

**Comment by singularitti** [comment]
Can this be merged, or does it need changes?

**Comment by singularitti** [comment]
I am sorry. This PR has existed for a long time. Is there anything blocking its merge?

**Comment by inkydragon** [comment]
You may also need to add the new symbols to `symbols_latex_canonical` (`stdlib/REPL/src/latex_symbols.jl`)

**Comment by KristofferC** [comment]
I couldn't rebase this, reopened in https://github.com/JuliaLang/julia/pull/49623

**Pull request closed without merging**
