### PR TITLE
Add `convert(Float16, BigFloat)`

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by ivarne** [comment]
`UndefVarError: r not defined`

Seems like you forgot something in the latest definition.

**Comment by eschnett** [comment]
Yes, I confused myself with `convert` and `call`. Corrected, with apologies for the noise.

**Comment by ivarne** [comment]
Actually, lots of mistakes is more noisy than a typo that gets detected by the test you just added.

Anyway, this looks like it follows a clear pattern from the lines above (and below), so next time I see this, I'll push the **`Merge pull request`** button

**Comment by eschnett** [comment]
ping

**Pull request merged**
