### PR TITLE
Bump libgit2, document libssl-dev build dep and fail earlier when missing

### LINKED ISSUE #13389: Document dependency on libssl when compiling Julia from source
On a Ubuntu 14.04 machine with Julia master and no package repo, `Pkg.init` gives an error:

```jl
julia> Pkg.init()
INFO: Initializing package repository /afs/csail.mit.edu/u/j/jiahao/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: [Code:ERROR, Class:Net]: Unsupported URL protocol
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:95
 in clone at libgit2.jl:303
 in anonymous at pkg/dir.jl:57
 in cd at file.jl:22
 in init at pkg/dir.jl:55
 in init at pkg.jl:23
```

### PR DESCRIPTION
**Pull request by tkelman**
closes #13389

The `REQUIRE_OPENSSL` flag isn't used yet but I've proposed [a PR to libgit2 upstream](https://github.com/libgit2/libgit2/pull/3450) so it wouldn't be needed as a patch in future versions.

### CODE REVIEW

**Comment by wildart** [comment]
I guess openssl requirements is a bit strict for libgit2 upstream, but for us it's a necessity. So, merge it.

**Comment by tkelman** [comment]
My patch for upstream is a little more complicated than the one here, adding a new option that's off by default so you could flag if you want the dependency to be mandatory. Let's see whether they approve of the idea.

**Comment by yuyichao** [comment]
Would be nice if there's a [`CMAKE_DISABLE_FIND_PACKAGE_<PackageName>`](https://cmake.org/cmake/help/v3.0/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html) equivalence to `REQUIRE`.

**Comment by tkelman** [comment]
Maybe we should have used that for the iconv issues on mac...

**Pull request merged**
