### PR TITLE
IRShow: pass `idx::Int` to `line_info_postprinter`

### PR DESCRIPTION
**Pull request by aviatesk**
Motivated by: <https://github.com/JuliaDebug/Cthulhu.jl/pull/225>

### CODE REVIEW

**Comment by aviatesk** [comment]
This is really not a bugfix, but I want to backport this change to v1.7 if possible -- it would ease the development cost for Cthulhu and similar code tools because we can cut off the compatibility efforts.

**Comment by simeonschaub** [comment]
The index should already be passed inside the `IOContext` (see #41828), which I did to avoid any potential breakage. Can JuliaDebug/Cthulhu.jl#225 just use that?

**Comment by aviatesk** [comment]
yeah, it works. Thanks for your pointer !

Well, I feel it's a bit strange that we pass `used` as argument while wrapping `idx` in `IOContext`. We may want to pack `used` into `IOContext` as well ?

But yeah, this refactor shouldn't confuse the v1.7 release, and I think it's better to leave it for the future for now ?

**Comment by simeonschaub** [comment]
> Well, I feel it's a bit strange that we pass `used` as argument while wrapping `idx` in `IOContext`. We may want to pack `used` into `IOContext` as well ?

I agree it feels a bit inconsistent, but I am not sure changing that is really worth it.

**Pull request closed without merging**
