### PR TITLE
Revert "@inbounds a few tuple loops"

### PR DESCRIPTION
**Pull request by KristofferC**
Reverts JuliaLang/julia#24335

Prematurely merged

### CODE REVIEW

**Review by yuyichao — APPROVED** [review]
Tuple getindex should be the case that's the easiest for LLVM to optimize so we shouldn't need these.

**Comment by KristofferC** [comment]
I dunno if we need them or not but they do remove a boundscheck:

```
julia> function isless1(t1::Tuple, t2::Tuple)
           n1, n2 = length(t1), length(t2)
           for i = 1:min(n1, n2)
               @inbounds a, b = t1[i], t2[i] # <--- inbounds
               if !isequal(a, b)
                   return isless(a, b)
               end
           end
           return n1 < n2
       end
isless1 (generic function with 1 method)

julia> function isless2(t1::Tuple, t2::Tuple)
           n1, n2 = length(t1), length(t2)
           for i = 1:min(n1, n2)
               a, b = t1[i], t2[i] # <- no inbounds
               if !isequal(a, b)
                   return isless(a, b)
               end
           end
           return n1 < n2
       end
isless2 (generic function with 1 method)

julia> @code_llvm isless1((1,2), (2,3)) # inbounds

; Function isless1
; Location: REPL[1]
define i8 @julia_isless1_62347([2 x i64] addrspace(11)* nocapture readonly dereferenceable(16), [2 x i64] addrspace(11)* nocapture readonly dereferenceable(16)) #0 {
top:
; Location: REPL[1]:3
  br label %L4

L4:                                               ; preds = %if, %top
  %"#temp#.0" = phi i64 [ 1, %top ], [ %3, %if ]
  %2 = icmp eq i64 %"#temp#.0", 3
  br i1 %2, label %L19, label %if

if:                                               ; preds = %L4
  %3 = add nuw nsw i64 %"#temp#.0", 1
; Location: REPL[1]:4
  %4 = add nsw i64 %"#temp#.0", -1
  %5 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %0, i64 0, i64 %4
  %6 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %1, i64 0, i64 %4
; Location: REPL[1]:5
  %7 = load i64, i64 addrspace(11)* %5, align 8
  %8 = load i64, i64 addrspace(11)* %6, align 8
  %9 = icmp eq i64 %7, %8
  br i1 %9, label %L4, label %if1

L19:                                              ; preds = %L4
; Location: REPL[1]:9
  ret i8 0

if1:                                              ; preds = %if
; Location: REPL[1]:6
  %10 = icmp slt i64 %7, %8
  %11 = zext i1 %10 to i8
  ret i8 %11
}

julia> @code_llvm isless2((1,2), (2,3)) # no inbounds

; Function isless2
; Location: REPL[2]
define i8 @julia_isless2_62348([2 x i64] addrspace(11)* nocapture readonly dereferenceable(16), [2 x i64] addrspace(11)* nocapture readonly dereferenceable(16)) #0 {
top:
; Location: REPL[2]:3
  br label %L4

L4:                                               ; preds = %pass2, %top
  %"#temp#.0" = phi i64 [ 1, %top ], [ %6, %pass2 ]
  %2 = icmp eq i64 %"#temp#.0", 3
  br i1 %2, label %L19, label %if

if:                                               ; preds = %L4
; Location: REPL[2]:4
  %3 = add nsw i64 %"#temp#.0", -1
  %4 = icmp ult i64 %3, 2
  br i1 %4, label %pass2, label %fail

L19:                                              ; preds = %L4
; Location: REPL[2]:9
  ret i8 0

fail:                                             ; preds = %if
; Location: REPL[2]:4
  %5 = bitcast [2 x i64] addrspace(11)* %0 to i8 addrspace(11)*
  call void @jl_bounds_error_unboxed_int(i8 addrspace(11)* %5, %jl_value_t* inttoptr (i64 4510244112 to %jl_value_t*), i64 %"#temp#.0")
  unreachable

pass2:                                            ; preds = %if
; Location: REPL[2]:3
  %6 = add nuw nsw i64 %"#temp#.0", 1
; Location: REPL[2]:4
  %7 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %0, i64 0, i64 %3
  %8 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %1, i64 0, i64 %3
; Location: REPL[2]:5
  %9 = load i64, i64 addrspace(11)* %7, align 8
  %10 = load i64, i64 addrspace(11)* %8, align 8
  %11 = icmp eq i64 %9, %10
  br i1 %11, label %L4, label %if3

if3:                                              ; preds = %pass2
; Location: REPL[2]:6
  %12 = icmp slt i64 %9, %10
  %13 = zext i1 %12 to i8
  ret i8 %13
}
```

**Comment by StefanKarpinski** [comment]
Please don't revert this or continue conversation here until we get a clear explanation of why it is wrong. This is a much bigger, more important issue than this one particular change.

**Comment by yuyichao** [comment]
Well,

```
julia> @code_llvm isless2((1,2), (2,3))

; Function isless2
; Location: REPL[1]
define i8 @julia_isless2_62283([2 x i64] addrspace(11)* nocapture readonly dereferenceable(16), [2 x i64] addrspace(11)* nocapture readonly dereferenceable(16)) {
pass2:
; Location: REPL[1]:4
  %2 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %0, i64 0, i64 0
  %3 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %1, i64 0, i64 0
; Location: REPL[1]:5
  %4 = load i64, i64 addrspace(11)* %2, align 8
  %5 = load i64, i64 addrspace(11)* %3, align 8
  %6 = icmp eq i64 %4, %5
  br i1 %6, label %pass2.1, label %if3

if3:                                              ; preds = %pass2.1, %pass2
  %.lcssa11 = phi i64 [ %4, %pass2 ], [ %11, %pass2.1 ]
  %.lcssa = phi i64 [ %5, %pass2 ], [ %12, %pass2.1 ]
; Location: REPL[1]:6
  %7 = icmp slt i64 %.lcssa11, %.lcssa
  %8 = zext i1 %7 to i8
  ret i8 %8

pass2.1:                                          ; preds = %pass2
; Location: REPL[1]:4
  %9 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %0, i64 0, i64 1
  %10 = getelementptr [2 x i64], [2 x i64] addrspace(11)* %1, i64 0, i64 1
; Location: REPL[1]:5
  %11 = load i64, i64 addrspace(11)* %9, align 8
  %12 = load i64, i64 addrspace(11)* %10, align 8
  %13 = icmp eq i64 %11, %12
  br i1 %13, label %L4.1, label %if3

L4.1:                                             ; preds = %pass2.1
; Location: REPL[1]:9
  ret i8 0
}
```

I guess we really don't want to touch LLVM version so that we'll keep the bounds check.

**Comment by yuyichao** [comment]
Also, I don't think the question about what `@inbounds` applies to is the confusion in either https://github.com/JuliaLang/julia/pull/21402 or https://github.com/JuliaLang/julia/pull/24335

**Comment by KristofferC** [comment]
> I guess we really don't want to touch LLVM version so that we'll keep the bounds check.

What does this mean?

**Comment by StefanKarpinski** [comment]
> I don't think the question about what @inbounds applies to is the confusion in either #21402 or #24335

The former, perhaps not, the latter, that was absolutely the source of confusion (for me at least).

**Comment by yuyichao** [comment]
> So you think that the correct version should be implemented for 0.7 (as in the diff I showed)

I don't mind either way. It's just very stupid that you don't get automatic bounds check ellision simply because the llvm version is too old.

**Comment by StefanKarpinski** [comment]
We will upgrade LLVM for 1.1. Upgrading LLVM is always a huge amount of work for precisely the people who we cannot afford to have doing such work right now.

**Pull request merged**
