### PR TITLE
fix shell mode interpolation & allow special chars in commands

### LINKED ISSUE #22176: REPL shell mode string interpolation regression
Originally reported on [Discourse](https://discourse.julialang.org/t/repl-shell-mode-string-interpolation-on-0-6-rc2/4028)

On v0.5.1:
```
shell> echo $("hello world")
hello world
```

On v0.6.0-rc2.0:
```
shell> echo $("hello world")
$(hello world)
```

Version info:
```
Julia Version 0.6.0-rc2.0
Commit 68e911be53 (2017-05-18 02:31 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

cc @StefanKarpinski

### PR DESCRIPTION
**Pull request by StefanKarpinski**
fixes #22176, see also #20494 and #20482

### CODE REVIEW

**Comment by tkelman** [comment]
this very badly needs a test or it will surely regress again

**Comment by StefanKarpinski** [comment]
100% agree, but let's get it into 0.6.0 now, we can add the test in 0.6.1.

**Comment by StefanKarpinski** [comment]
I screwed up the rebase onto master; pushing the corrected fix...

**Comment by Keno** [comment]
Shell mode tests are here, FWIW: https://github.com/JuliaLang/julia/blob/master/test/repl.jl#L72

**Comment by StefanKarpinski** [comment]
macOS failure is a timeout, I've tested locally on macOS so should be good to go here.

**Comment by tkelman** [comment]
I'll take a look at the Windows failure here, I have a pretty good idea what it might be.

**Comment by StefanKarpinski** [comment]
Tried testing this on Windows, but shell stuff is completely jacked on Windows, so it failed, of course. Can figure out how to test on Window at some point in the future.

**Comment by tkelman** [comment]
A test that relies on redirection won't work there since shell mode doesn't go through a shell on windows

**Pull request merged**
