### PR TITLE
string doc clarifications

### PR DESCRIPTION
**Pull request by stevengj**
Clarify that `firstindex(str)` should always be `1` for any `AbstractString`, as mentioned by @StefanKarpinski [here](https://github.com/JuliaLang/julia/pull/26133#discussion_r170899348).

Also reference `prevind` and `eachindex`.

Also introduce the "code unit" terminology and mention the `codeunit` functions.

### CODE REVIEW

**Comment by stevengj** [comment]
@StefanKarpinski, I noticed this old doc PR and updated it.   Is it still merge-worthy?

**Comment by StefanKarpinski** [comment]
Yes, definitely an improvement! I will look into the errors and get this merged.

**Comment by stevengj** [comment]
The doctest error is confusing to me; is there a missing backtick somewhere or something that is screwing up the parsing?

**Comment by StefanKarpinski** [comment]
Not sure, I've posted the error output to Slack on the #documentation channel; hopefully someone there can help out. I've also rebased this on top of master for clarity.

**Comment by StefanKarpinski** [comment]
Squashed, rebased version with an additional clarification here: https://github.com/JuliaLang/julia/pull/30682.

**Pull request closed without merging**
