### PR TITLE
modal prefix searching in REPL

### PR DESCRIPTION
**Pull request by blakejohnson**
From the discussions in #6377, #8577, and #8468, it is clear that we need a better solution for the interaction between prefix history searching and multi-line history entries. This PR implements one such solution which is a modal prefix searching behavior. The idea is that pressing up/down arrow will start a prefix search, and then will _continue_ to do prefix searching on subsequent presses until some key other than up/down is pressed. In this way, history searching is not "interrupted" by multi-line history entries. It also allows us to put the cursor at the end of the line, like the old history traversal behavior (i.e. this fixes #8577).

Reasons that this is WIP:

~~1) I seem to have re-broken down-arrow behavior in terms of continuing from a previously accepted history item. i.e. #8468 is back with this PR.~~
~~2) I need to figure out how to 'forward' a keypress to the parent REPL mode. At present, except for the arrow keys, enter/return, and ctrl+C, all other keys simply exit prefix searching mode without performing any other action. I am exploring alternatives to simply pulling in all the key bindings from the default keymap.~~
~~3) I need to rebase into a smaller number of commits.~~

### CODE REVIEW

**Comment by carlobaldassi** [comment]
This change has broken the old `history_prev_prefix` behaviour, leaving the [documentation in an outdated state](https://github.com/JuliaLang/julia/blob/38d02bd8bb2c5f3418dd4db08645e4d38de5a3c0/doc/manual/interacting-with-julia.rst#customizing-keybindings). Following the docs, the result is now that the REPL crashes:

```
ERROR: `history_prev_prefix` has no method matching history_prev_prefix(::Base.LineEdit.MIState, ::Base.REPL.REPLHistoryProvider)
```

**Comment by carlobaldassi** [comment]
Sorry, disregard the previous message, I misread the docs, they don't actually mention `hist_prev_prefix`. It's still true that `history_prev_prefix` is no longer accessible as it used to be though, meaning my keybindings are currently broken... any suggestion about what this line should be changed to:

```
"\e[5~" => (s,o...)->(LineEdit.history_prev_prefix(s, LineEdit.mode(s).hist)),
```
?

**Comment by blakejohnson** [comment]
Unfortunately, the new prefix method `enter_prefix_search` is no longer bindable in the user keymap since it depends on having access to an instance of `PrefixHistoryPrompt`. I'm not sure what to do about this at the moment. It is also the case that you cannot rebind the search prompt keys for similar reasons.

**Comment by carlobaldassi** [comment]
I suspected as much, thanks for looking into this. For the time being, I solved my problem by grabbing the old version of `history_prex_prefix` and putting it in my juliarc.

**Pull request merged**
