### PR TITLE
Allow use of 32 element tuples without dynamic allocation

### LINKED ISSUE #333: permutedims errors on high dimensional tensors
The line errors

https://github.com/JuliaGPU/GPUArrays.jl/blob/c418821b66817ec81c2c8411dec1b30da9064ece/src/host/linalg.jl#L200

```julia
julia> CUDA.permutedims(CuArray(randn(fill(2, 20)...)), randperm(20));
ERROR: InvalidIRError: compiling kernel #41(CUDA.CuKernelContext, CuDeviceArray{Float64,20,1}, CuDeviceArray{Float64,20,1}, NTuple{20,Int64}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to getindex)
Stacktrace:
 [1] macro expansion at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/device/indexing.jl:81
 [2] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:203
Reason: unsupported dynamic function invocation (call to getindex)
Stacktrace:
 [1] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:204
Reason: unsupported dynamic function invocation (call to genperm)
Stacktrace:
 [1] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:204
Reason: unsupported dynamic function invocation (call to setindex!(A::AbstractArray, v, I...) in Base at abstractarray.jl:1150)
Stacktrace:
 [1] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:204
Reason: unsupported dynamic function invocation (call to setindex!)
Stacktrace:
 [1] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:204
Reason: unsupported call through a literal pointer (call to jl_alloc_array_1d)
Stacktrace:
 [1] Array at boot.jl:406
 [2] map at tuple.jl:168
 [3] axes at abstractarray.jl:75
 [4] CartesianIndices at multidimensional.jl:264
 [5] macro expansion at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/device/indexing.jl:81
 [6] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:203
Reason: unsupported call to the Julia runtime (call to jl_f__apply_iterate)
Stacktrace:
 [1] map at tuple.jl:172
 [2] axes at abstractarray.jl:75
 [3] CartesianIndices at multidimensional.jl:264
 [4] macro expansion at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/device/indexing.jl:81
 [5] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:203
Reason: unsupported dynamic function invocation (call to CartesianIndices)
Stacktrace:
 [1] CartesianIndices at multidimensional.jl:264
 [2] macro expansion at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/device/indexing.jl:81
 [3] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:203
Stacktrace:
 [1] check_ir(::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget,CUDA.CUDACompilerParams}, ::LLVM.Module) at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/validation.jl:123
 [2] macro expansion at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:239 [inlined]
 [3] macro expansion at /home/jgliu/.julia/packages/TimerOutputs/ZmKD7/src/TimerOutput.jl:206 [inlined]
 [4] codegen(::Symbol, ::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool) at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:237
 [5] compile(::Symbol, ::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool) at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:39
 [6] compile at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/driver.jl:35 [inlined]
 [7] cufunction_compile(::GPUCompiler.FunctionSpec; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/jgliu/.julia/packages/CUDA/0p5fn/src/compiler/execution.jl:310
 [8] cufunction_compile(::GPUCompiler.FunctionSpec) at /home/jgliu/.julia/packages/CUDA/0p5fn/src/compiler/execution.jl:305
 [9] check_cache(::Dict{UInt64,Any}, ::Any, ::Any, ::GPUCompiler.FunctionSpec{GPUArrays.var"#41#42",Tuple{CUDA.CuKernelContext,CuDeviceArray{Float64,20,1},CuDeviceArray{Float64,20,1},NTuple{20,Int64}}}, ::UInt64; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/cache.jl:40
 [10] #41 at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:203 [inlined]
 [11] cached_compilation at /home/jgliu/.julia/packages/GPUCompiler/uTpNx/src/cache.jl:65 [inlined]
 [12] cufunction(::GPUArrays.var"#41#42", ::Type{Tuple{CUDA.CuKernelContext,CuDeviceArray{Float64,20,1},CuDeviceArray{Float64,20,1},NTuple{20,Int64}}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/jgliu/.julia/packages/CUDA/0p5fn/src/compiler/execution.jl:297
 [13] cufunction(::GPUArrays.var"#41#42", ::Type{Tuple{CUDA.CuKernelContext,CuDeviceArray{Float64,20,1},CuDeviceArray{Float64,20,1},NTuple{20,Int64}}}) at /home/jgliu/.julia/packages/CUDA/0p5fn/src/compiler/execution.jl:294
 [14] #launch_heuristic#852 at /home/jgliu/.julia/packages/CUDA/0p5fn/src/gpuarrays.jl:19 [inlined]
 [15] launch_heuristic at /home/jgliu/.julia/packages/CUDA/0p5fn/src/gpuarrays.jl:17 [inlined]
 [16] gpu_call(::GPUArrays.var"#41#42", ::CuArray{Float64,20}, ::CuArray{Float64,20}, ::NTuple{20,Int64}; target::CuArray{Float64,20}, total_threads::Nothing, threads::Nothing, blocks::Nothing, name::String) at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/device/execution.jl:61
 [17] permutedims!(::CuArray{Float64,20}, ::CuArray{Float64,20}, ::Array{Int64,1}) at /home/jgliu/.julia/packages/GPUArrays/ZxsKE/src/host/linalg.jl:202
 [18] permutedims(::CuArray{Float64,20}, ::Array{Int64,1}) at ./multidimensional.jl:1381
 [19] top-level scope at REPL[12]:1
```

I think this is the 16 size tuple issue. Is there some easy approach to circumvent this error?

### PR DESCRIPTION
**Pull request by kshyatt**
Fixes https://github.com/JuliaGPU/GPUArrays.jl/issues/333 and https://github.com/JuliaGPU/GPUArrays.jl/issues/340 and restores behaviour compatible with https://github.com/JuliaLang/julia/pull/27398

cc @GiggleLiu, @maleadt

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Thanks @kshyatt , your PR fixes the problem for me.

## Julia 1.6

```julia
julia> using BenchmarkTools

julia> ci = CartesianIndices((fill(2, 20)...,));

julia> @benchmark $ci[35]
BenchmarkTools.Trial: 
  memory estimate:  1.86 KiB
  allocs estimate:  31
  --------------
  minimum time:     1.617 μs (0.00% GC)
  median time:      1.666 μs (0.00% GC)
  mean time:        1.807 μs (1.25% GC)
  maximum time:     60.471 μs (95.66% GC)
  --------------
  samples:          10000
  evals/sample:     10

julia> ci0 = CartesianIndices((fill(2, 10)...,));

julia> @benchmark $ci0[35]
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     47.384 ns (0.00% GC)
  median time:      48.379 ns (0.00% GC)
  mean time:        49.057 ns (0.00% GC)
  maximum time:     74.505 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     988
```

## This branch
```julia
julia> using BenchmarkTools

julia> ci = CartesianIndices((fill(2, 20)...,));

julia> @benchmark $ci[35]
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     124.371 ns (0.00% GC)
  median time:      125.541 ns (0.00% GC)
  mean time:        127.415 ns (0.00% GC)
  maximum time:     245.769 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     898

julia> ci0 = CartesianIndices((fill(2, 10)...,));

julia> @benchmark $ci0[35]
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     46.852 ns (0.00% GC)
  median time:      47.403 ns (0.00% GC)
  mean time:        48.413 ns (0.00% GC)
  maximum time:     111.554 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     988
```

**Comment by oscardssmith** [comment]
Does this PR have notable TTFP implications?

**Comment by kshyatt** [comment]
Honestly not sure. Hopefully the extension from 16-32 does not affect compilation too harshly but we should test this/get confirmation that it's unlikely to.

**Comment by JeffBezanson** [comment]
Seems reasonable to me. 16 was pretty arbitrary anyway. I don't see any significant differences in build time, sysimg size, or TTFP.

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
I thought I'd drawn a performance plot when adding this method in #39414, but it seems I must not have uploaded it. Could you run the original benchmark (https://github.com/JuliaLang/julia/issues/39175) for different sizes of `n` (say, from 2:256)? It should show some quadratic behavior with breaks at a few different points (including this point). I think this PR should be fine, but that would help confirm it.

**Comment by GiggleLiu** [comment]
Just clarify the number 32 a bit. 32 is a good number because a double precision tensor of rank 32 with size of each dimension 2 just fits the 32GB GPU.
```julia
julia> 1<<32 * 8 / (1<<30)
32.0
```
Hence the above benchmark aims to show the allocation rather than the speed up. This PR is to fix the problem of *high order tensors can not be indexed on GPU kernels*. @kshyatt and I encounters this problem independently during researches about tensor networks.

@vtjnash I am glad to run the benchmark. But not quite understand what do you mean by the original benchmark and what is the `n` here? I just reproduced the first benchmark in the issue
```julia
julia> # on julia 1.7 (this PR)
       @btime SymmetricGroup(20)
  981.900 ns (39 allocations: 3.72 KiB)

julia> # on julia 1.6.0
       @btime SymmetricGroup(20)
  1.065 μs (39 allocations: 3.72 KiB)
```
It seems not what we are looking for?

**Comment by kshyatt** [comment]
With this PR:
```
julia>  @time @eval begin using Plots; unicodeplots(); x=plot(sin); display(x) end
29.816768 seconds (35.54 M allocations: 2.121 GiB, 4.96% gc time, 0.03% compilation time)
```
on `master`:

```
julia>  @time @eval begin using Plots; unicodeplots(); x=plot(sin); display(x) end
29.365071 seconds (35.64 M allocations: 2.122 GiB, 6.11% gc time, 0.03% compilation time)
```

**Comment by kshyatt** [comment]
@vtjnash ran the benchmarks and here are the results (all times on the y axis in microseconds)

image

Sorry for the messed up labelling. The blue is `master` and orange is this PR. The x axis is `n`.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40468#issuecomment-820869304) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/de5ce35_vs_29d5158/report.md). cc @christopher-dG

**Comment by kshyatt** [comment]
What do we think? Are the nanosoldier results concerning or can we go forward?

**Comment by vtjnash** [comment]
I don't think I see anything changed. @nanosoldier `runbenchmarks("foldl", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40468#issuecomment-821270365) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/de5ce35_vs_29d5158/report.md). cc @christopher-dG

**Comment by JeffBezanson** [comment]
It looks like if nanosoldier is run twice on the same PR, the old result gets overwritten? I don't think it used to do that, did it?

**Comment by maleadt** [comment]
Yeah that's https://github.com/JuliaCI/Nanosoldier.jl/issues/83. It used to link to a git hash, but that broke rewriting the NanosoldierReports history (which may need to happen once in a while because the repo just grows huge).

**Pull request merged**
