### PR TITLE
Revert #43641

### LINKED ISSUE #44016: Make `Test.TestLogger` and `Test.LogRecord` part of the public API
This can make writing tests that interact with functions that log a lot easier. The `@test_logs` macros are useful, but work better for small short functions that log one or two things. For end-to-end tests of larger applications, one might want to test things differently, and having access to the actual `LogRecord`s to inspect and test against is very useful. Moreover, one can do something like
```julia
using Test, Logging

function relog(r)
    return Logging.handle_message(global_logger(), r.level, r.message, r._module, r.group,
                                  r.id, r.file, r.line; r.kwargs...)
end

test_logger = Test.TestLogger()
try
    with_logger(test_logger) do
        my_complicated_function_with_a_lot_of_logging()
    end
catch
    println("Caught exception, so dumping logs:")
    foreach(relog, test_logger.logs)
    rethrow()
end
# test against `test_logger.logs`...
```
The benefit of this is you can suppress logs except when an error occurs, in which case being able to see the logs might be useful in understanding the error.

This is all doable already, but it's not part of the public API. My proposal is to simply document and export `Testlogger` and `LogRecord`, to make the above usage not-involving-internals. We could also provide an accessor for the `logs` field if we don't want the field itself to be public API.

xref https://github.com/JuliaLang/julia/pull/43641#issuecomment-1008208484

### PR DESCRIPTION
**Pull request by ericphanson**
Reverts #43641 as discussed there and in #44016

### CODE REVIEW

**Comment by vtjnash** [comment]
As you mentioned on that PR though, it seem we do expect it to support minlevel and other standard logger features such as maxlog

**Comment by ericphanson** [comment]
Hm ok :). Do we want to keep #43641 then? Do we want this additionally? I do think it's useful on it's own. Maybe I should make these two separate PRs so they can be discussed individually.

**Comment by ericphanson** [comment]
Ok, I made this PR just the revert and pulled the other commit out to https://github.com/JuliaLang/julia/pull/44080.

**Comment by fredrikekre** [comment]
> And then I guess maybe we should close this if we want a TestLogger to act kind of like a usual logger, supporting maxlog and minlevel?

Lets make respecting max log optional, just like the min level then? By default I think it should capture everything, but if you want to test something else you can configure it.

**Comment by ericphanson** [comment]
> Lets make respecting max log optional, just like the min level then?

Sure, do you think just `respect_maxlog=true` in the constructor and store the bool in the struct?

**Comment by fredrikekre** [comment]
Yea, something like that.

**Comment by ericphanson** [comment]
Closing in favor of https://github.com/JuliaLang/julia/pull/44085

**Pull request closed without merging**
