### PR TITLE
Revert "The return of the "Generate precompilation as part of build process

### PR DESCRIPTION
**Pull request by KristofferC**
While https://github.com/JuliaLang/julia/pull/28319 passes tests and provide a good REPL experience with building locally it has one problem that I failed to realize before merging.
The generator script implicitly assumes that `stdin` is a TTY in order for the record of the startup process to be the same as for a user. This works well if you build locally but the for the buildbots this is not the case (stdin is redirected to a file or something). This means that the recorded precompilation statements are non-accurate and this harms startup time and REPL startup time compared to the hardcoded precompilation statements.

It is obvious that something is off by looking at the number of precompilation statements that gets generated locally (~730) vs on the buildbots (~650).

So I think it is best to revert this and get a proper version going that creates its own TTY and have no assumptions on the building environment.

I apologize for the frequent merging / revert cycle lately :(

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Can we fix it without reverting first? This is a lot of churn.

**Comment by KristofferC** [comment]
Yeah, I apologize for it, I should have tested more carefully (gotten a full buildbot artifact from the PR and see that it had good results before merging). 

But regarding a lot of churn, it will be 4 commits that look a bit stupid but I'm not sure what the actual harm is? Right now, I just feel bad that my PR that was supposed to help load time is doing the opposite.

Regarding creating a TTY, it is likely that I can adapt the code in https://github.com/Keno/VT100.jl/blob/a13872010a92c9827e8e1d21c0eed8dadda2c895/src/VT100.jl#L557-L590 to work for this in Linux and probably Mac but getting it to work on Windows as well might take some time.

If it is ok I rather just get this revert through and then I'll make sure it is correct and good the next time.

**Comment by KristofferC** [comment]
Again, sorry for the churn and having to revert.

**Comment by JeffBezanson** [comment]
It's ok, I just feel lots of reverts make the commit history messy. It also means the repl in my locally-built version has to be slower again temporarily :-P

**Comment by vtjnash** [comment]
> Regarding creating a TTY 

That code is already present here: https://github.com/JuliaLang/julia/blob/ca7a692f9f1099ba042ed75e5d83236ec523608a/test/testhelpers/FakePTYs.jl

**Pull request merged**
