### PR TITLE
Revert "Update suitesparse url"

### PR DESCRIPTION
**Pull request by ViralBShah**
Reverts JuliaLang/julia#43046

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I agree that the revert is the correct short-term solution.

In the long-term, perhaps we could ask the SuiteSparse authors if they could set up HTTPS on their website?

**Comment by ViralBShah** [comment]
@drtimothyaldendavis - is it possible to have https://suitesparse.com work as well?

**Comment by DrTimothyAldenDavis** [comment]
I'd have to pay extra for it, on my own.  This URL is one I one personally, and is a forward to my current research page at A&M, which is https://people.engr.tamu.edu/davis/suitesparse.html .  The easiest thing to do if you need https is to just use that link instead of http://suitesparse.com.

**Comment by ViralBShah** [comment]
You can make it do free https by using GitHub pages to host it and have an http redirect to your existing page. May not be worth the effort though.

In any case we are just using your University page directly since browsers don't like http URLs nowadays.

**Pull request merged**
