### PR TITLE
`typemin`, `typemax` for irrationals

### LINKED ISSUE #36978: problem with typemin and typemax for Irrational
I think it is a bug:
```
julia> t = typeof(pi)
Irrational{:π}

julia> hasmethod(typemin, (t,))
true

julia> typemin(t)
ERROR: MethodError: no method matching typemin(::Type{Irrational{:π}})
```
The same happens with `typemax`

### PR DESCRIPTION
**Pull request by nsajko**
Fixes #36978

### CODE REVIEW

**Comment by nsajko** [comment]
Fixed conflict.

**Comment by nsajko** [comment]
Bump?

**Comment by nsajko** [comment]
Fixed another conflict.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
LGTM. Can be merged as soon as CI passes again.

**Comment by nsajko** [comment]
Test failures seem unrelated.

**Comment by nsajko** [comment]
Can someone merge?

**Comment by nsajko** [comment]
Test failures are unrelated.

**Comment by nsajko** [comment]
All checks pass, merge?

**Pull request merged**
