### PR TITLE
Method overwriting by an ambiguity should also invalidate the method cache

### LINKED ISSUE #21963: Ambiguous method callable
Ref. https://github.com/JuliaLang/julia/pull/21892#issuecomment-302704983

```julia
julia> methods(string, Tuple{Char})
# 1 method for generic function "string":
string(a::Union{Char, String}...) in Base at strings/string.jl:351

julia> Base.string(a::Union{Char, Val{:foo}}...) = "bar" # that's ambiguous!

julia> methods(string, Tuple{Char}) # let's check
# 0 methods for generic function "string":

julia> string('0') # so should throw MethodError
"0"
```

### PR DESCRIPTION
**Pull request by vtjnash**
fix #21963

~DO NOT MERGE (until https://github.com/JuliaArchive/LegacyStrings.jl/issues/8 is fixed)~

### CODE REVIEW

**Comment by martinholters** [comment]
With JuliaArchive/LegacyStrings.jl#8 fixed (and a new LegacyStrings version tagged), 
@nanosoldier `runbenchmarks(ALL, vs = ":master")` should succeed now - let's see...

**Comment by KristofferC** [comment]
Should be packported?

**Comment by martinholters** [comment]
As long as we don't backport #21892 (and I guess we won't), there AFAICT is no need to backport this. The fact that a method is still callable despite there being an ambiguity should rarely be a problem. OTOH, this can be a breaking change by uncovering bugs (as it was for LegacyStrings), which makes it an unlikely backport candidate.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21965#issuecomment-304593916) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1ad6a70d178e0d38264df0a8be5e3bf62e16e47f/535bb31_vs_96e4301/report.md). cc @jrevels

**Comment by martinholters** [comment]
The performance regressions should all be noise, and I guess the travis OSX failure is unrelated, but I don't really know what happened there.

**Pull request merged**
