### PR TITLE
make `randstring` 25% faster for ASCII

### PR DESCRIPTION
**Pull request by rfourquet**
This uses `_string_n` instead of `StringVector` in order to allocate less,
e.g.:
```julia
julia> @btime randstring() # master
  71.499 ns (2 allocations: 96 bytes)
"DZk2V5Bm"

julia> @btime randstring() # PR
  57.832 ns (1 allocation: 32 bytes)
"Hj5PINXU"
```

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by KristofferC** [comment]
Could use a rebase it seems.

**Review by vtjnash — COMMENTED** [review]
`Random.UnsafeView` perhaps really should have been deprecated a long time ago.

**Comment by rfourquet** [comment]
> Random.UnsafeView perhaps really should have been deprecated a long time ago.

There is an issue for that: #36718
But this PR is an example where it's still proves to be useful, unless I'm missing another way. As mentioned in the issue though, we could definitely try to make `UnsafeView` hold a reference to the parent and see if performance doesn't get worse  (although that would mean compiling more methods, for each parent type, instead of for each `eltype`).

**Review by LilithHafner — APPROVED** [review]
This looks good to me. I think that qualms about UnsafeView are valid but don't block this PR.

**Pull request merged**
