### PR TITLE
Update functions.md

### PR DESCRIPTION
**Pull request by pathak-ashutosh**
Add info about the use of `;` (semi-colon) at the end of a function

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Hi, thank you for the pull request! I can see how this might be confusing, but this is not specific to functions: putting a `;` at the end of input in the interactive prompt (REPL) always suppresses display of the returned value. The output `g (generic function with 1 method)` is just how generic function objects are displayed. The syntax `g (x, y)` and `hypot (x, y)` should probably be avoided as well since it is neither valid for declaring or calling functions—the space between the function name and the argument tuple is not allowed:
```jl
julia> g (x, y) = 2x + y
ERROR: syntax: space before "(" not allowed in "g ("

julia> g(x, y) = 2x + y
g (generic function with 1 method)

julia> g (2, 3)
ERROR: syntax: space before "(" not allowed in "g ("

julia> g(2, 3)
7
```

**Comment by m3rc3n4ry** [comment]
Thanks for clearing it out to me :) Can you point me towards the introduction to interactive prompt documentation?

**Comment by StefanKarpinski** [comment]
https://docs.julialang.org/en/v1/manual/getting-started/#man-getting-started-1:

> If an expression is entered into an interactive session with a trailing semicolon, its value is not shown.

There's no example of this though, which would be good to add.

**Comment by m3rc3n4ry** [comment]
Thanks, I'll surely look into it and see what I can do :)
Should I just close this PR now? I'm new to open-source.

**Comment by StefanKarpinski** [comment]
Yes, you can open a new one with a different change. Thanks for the PR nevertheless!

**Pull request closed without merging**
