### PR TITLE
fix some cases where we incorrectly removed global var accesses

### PR DESCRIPTION
**Pull request by JeffBezanson**
Possible fix for the issue identified here: https://github.com/JuliaLang/julia/pull/16090#issuecomment-215470207

### CODE REVIEW

**Comment by vtjnash** [comment]
iirc, this will cause performance regressions due to inhibiting the later optimization passes (such as tuple destructuring)

**Comment by JeffBezanson** [comment]
Which part --- the global var part or the typeassert part? I wouldn't think accessing possibly-undefined global variables was that important a case.

**Comment by vtjnash** [comment]
the typeassert. i don't know of any cases where the globals access could cause issues either

**Comment by JeffBezanson** [comment]
My thinking was that since we remove typeasserts that won't throw, any that remain indeed have effects that need to be preserved. Am I missing a case?

**Comment by vtjnash** [comment]
That would make sense (I forgot we have a custom inliner for this). I would have to look back through blame to check, but I think it was the `printf` perf test that was most noticably affected by this

**Comment by JeffBezanson** [comment]
I'll check that.

**Comment by yuyichao** [comment]
Will this fix the original issue in https://github.com/JuliaLang/julia/issues/9765? (maybe not the `isa` one)

**Comment by JeffBezanson** [comment]
Yes it fixes the original issue there, but not all the cases mentioned in the later comments.

So far I don't really see any regressions here. `meteor_contest` is slightly slower, but given #16128 it might be noise.

**Pull request merged**
