### PR TITLE
Backport #50832 to v1.10

### LINKED ISSUE #55933: Undefined typevar when it is clearly defined
On Julia 1.10.5

```julia
julia> T = (Vector{Tuple{Code}} where {Code<:Integer})
Array{Tuple{Code}, 1} where Code<:Integer

julia> eltype(T)
Any

julia> @inline ptreltype(::Type{Array{T,N}}) where {T,N} = T
ptreltype (generic function with 1 method)

julia> ptreltype(T)
ERROR: UndefVarError: `T` not defined
Stacktrace:
 [1] ptreltype(::Type{Array{Tuple{Code}, 1} where Code<:Integer})
   @ Main ./REPL[6]:1
 [2] top-level scope
   @ REPL[7]:1
```

Not entirely sure what I would expect here (actually I would expect a methoderror), but definitely not this.

cc @mofeing

### PR DESCRIPTION
**Pull request by mofeing**
fixes #55933

This backports #50832 to v1.10.

### CODE REVIEW

**Comment by mofeing** [comment]
CC @wsmoses

**Comment by mofeing** [comment]
Failed tests seem unrelated to this PR:

```
Error in testset Pkg:
Test Failed at /cache/build/tester-amdci4-10/julialang/julia-release-1-dot-10/julia-bd32e389dd/share/julia/stdlib/v1.10/Pkg/test/new.jl:803
  Expression: ((Pkg.dependencies())[exuuid]).version == v"0.5.3"
   Evaluated: v"0.5.5" == v"0.5.3"
Error in testset Pkg:
Test Failed at /cache/build/tester-amdci4-10/julialang/julia-release-1-dot-10/julia-bd32e389dd/share/julia/stdlib/v1.10/Pkg/test/pkg.jl:279
  Expression: ((Pkg.dependencies())[TEST_PKG.uuid]).version > old_v
   Evaluated: v"0.5.5" > v"0.5.5"
Error in testset Pkg:
Test Failed at /cache/build/tester-amdci4-10/julialang/julia-release-1-dot-10/julia-bd32e389dd/share/julia/stdlib/v1.10/Pkg/test/repl.jl:86
  Expression: ((Pkg.dependencies())[TEST_PKG.uuid]).version > v
   Evaluated: v"0.5.5" > v"0.5.5"
```

**Comment by giordano** [comment]
That's because you're branch is old and doesn't have the backport of Pkg.jl which fixed that.

**Comment by DilumAluthge** [comment]
@mofeing I think that this should target the `backports-release-1.10` branch.

**Comment by DilumAluthge** [comment]
Agh I changed the target branch, but Git did not like that.

**Comment by wsmoses** [comment]
Can you just reset the branch to back ports and cherry pick the commit

**Comment by giordano** [comment]
> @mofeing I think that this should target the backports-release-1.10 branch.

That doesn't exist anymore.

> Agh I changed the target branch, but Git did not like that.

Probably because it's the wrong branch.

**Comment by giordano** [comment]
Isn't it easier to label #50832 as backport to 1.10 and wait for the next v1.10 release to handle all of this automatically?

**Comment by mofeing** [comment]
> That's because you're branch is old and doesn't have the backport of Pkg.jl which fixed that.

@giordano mmm I just updated my `release-1.10` branch and cherry-picked the commit again, but same error.

> Isn't it easier to label #50832 as backport to 1.10 and wait for the next v1.10 release to handle all of this automatically?

Does it mean that I shouldn't do anything else and just close this PR?

**Comment by giordano** [comment]
> Does it mean that I shouldn't do anything else and just close this PR?

Yes

**Comment by giordano** [comment]
For the benefit of future readers, #50832 was automatically added to the list of backports for v1.10.7 in #56381

**Pull request closed without merging**
