### PR TITLE
Promote Float32 and Complex{Float32} elements to Float64 and Complex{Float64}

### LINKED ISSUE #14076: StackOverflow for `cholfact(::SparseMatrixCSC{Float32,Int})` (and the possible return of `float64`?)
```jl
julia> S = sparse([1,2],[1,2],Float32[1,1])
2x2 sparse matrix with 2 Float32 entries:
        [1, 1]  =  1.0
        [2, 2]  =  1.0

julia> cholfact(S)
ERROR: StackOverflowError:
 [inlined code] from essentials.jl:204
 in copy at array.jl:154
 in float at sparse/sparsematrix.jl:251
 in call at essentials.jl:58 (repeats 508 times)
```
The proximal cause is
```jl
julia> @which convert(Base.SparseArrays.CHOLMOD.Sparse, S)
convert{T}(::Type{Base.SparseArrays.CHOLMOD.Sparse{Tv<:Union{Complex{Float64},Float64}}}, A::Union{Hermitian{T,SparseMatrixCSC{T,Int64}},SparseMatrixCSC{T,Int64},Symmetric{T,SparseMatrixCSC{T,Int64}}}, args...) at sparse/cholmod.jl:875
```
at [this line](https://github.com/JuliaLang/julia/blob/a419fda050036ba3203dbdd93a117627d9cc9ede/base/sparse/cholmod.jl#L875): `float(A)` will just pass-through a `Float32` array, but `Sparse` insists on `Float64`:
```jl
julia> Base.SparseArrays.CHOLMOD.VTypes
Union{Complex{Float64},Float64}
```

There seem to be several potential ways to solve this:

- (challenging but awesome) Support single-precision in CHOLMOD
- (easiest but perhaps short-sighted) Don't use a `Union`, specialize that function on each type so the conversion can be written out explicitly
- (orthogonal to the first, redundant with the second) Bring back `float64` or similar, which means "I don't care what the container type is, but make sure its internal storage is always `Float64`."

On the last option, I've noticed some reason for this elsewhere; I don't really want to have to say `convert(Image{base_colorant_type(eltype(img)){Float64}}, img)` just to convert from a `UFixed8` internal representation to a `Float64` internal representation.

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #14076

### CODE REVIEW

**Comment by tkelman** [comment]
tests

**Comment by andreasnoack** [comment]
have just arrived

**Comment by timholy** [comment]
LGTM, thanks!

**Comment by timholy** [comment]
OK to add that backport label?

**Comment by tkelman** [comment]
another case of if you rely on this in any package, be sure to declare a specific patch julia version in REQUIRE

**Pull request merged**
