### PR TITLE
rational.jl: check for overflow negating typemin(::Integer)

### PR DESCRIPTION
**Pull request by JeffreySarnoff**
this is a continuation of https://github.com/JuliaLang/julia/pull/31090, which github will not reopen.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Let us know when you feel this is done and ready for review/merge.

**Comment by JeffreySarnoff** [comment]
There is an ambiguity error that I don't understand.

**Comment by JeffreySarnoff** [comment]
@stefan While I like the logic in this version, I don't where the ambiguity is!!

**Comment by JeffreySarnoff** [comment]
@StefanKarpinski this latest version passes runtests.jl on a local build of Julia

**Comment by JeffreySarnoff** [comment]
That's all -- still don't understand the ambiguous error message.

**Comment by JeffreySarnoff** [comment]
I'm ready for others to look -- don't know what else to do.

**Comment by JeffreySarnoff** [comment]
@StefanKarpinski The 2 ambiguity errors are "broken tests".  This same error occurs with the unmodified version of `rational.jl`.  AFAIK its ready.

**Comment by JeffreySarnoff** [comment]
@StefanKarpinski @simonbyrne consider this a hand-off, in the best sense.  I had been unware that all the bad tests had nothing to do with my changes, so I spent way too much time spinning wheels to fix what had not been broken.  (why there are so many changes to recover the unchanged). I have given you my best understanding of how the constructor, abs, and negation needed modification to handle `-typemin(T) == typemin(T)` for {T<:Base.BitSigned}.   thanks for the understanding.

**Comment by JeffreySarnoff** [comment]
Well, this remains helpful in intent .. long time passing.
I expect the current implementation of rational.jl has advanced and improvements there simplify reaching the goal for this PR.
So, how do I unset all prior file modifications to obtain a clean current slate?

**Pull request closed without merging**
