### PR TITLE
Apply minor wording fix in the manual

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by tkelman** [comment]
Hi! I think the intent here is that spacing convention follows precedence of the operator rather than binary vs unary. Will check git blame to see when that line was written.

**Comment by DanielRosenwasser** [comment]
Ah, gotcha. What about this?

> By convention, we tend to space operators a little more tightly if they get applied before other nearby operators.
For instance, we would generally write `-x + 2` to reflect that first `x` gets negated, and then `2` is added to that result.

**Comment by tkelman** [comment]
Sure, that sounds good, though I'd leave out "a little"

**Comment by DanielRosenwasser** [comment]
Sure thing ✅

**Pull request merged**
