### PR TITLE
Make complex sin and cos type stable

### PR DESCRIPTION
**Pull request by malmaud**
cf https://github.com/JuliaLang/julia/issues/11839

### CODE REVIEW

**Comment by yuyichao** [comment]
Would it be too much to add an specialization for `Complex{T<:Integer}` that bypass the check for infinity and nan?

**Comment by tkelman** [comment]
Could use a few `@inferred` tests

**Comment by malmaud** [comment]
@tkelman Done
@yuyichao What's the advantage?

**Comment by yuyichao** [comment]
Performance? (This is why I didn't go ahead and implement that).

See my benchmark result [here](https://github.com/yuyichao/explore/blob/a4c2836f1a6b581a25f08d1de9e5d60121f01fb0/julia/sin_complex/sin_complex.jl#L64)

Depending on the machine I use, I can see on average `1%-20%` performance improvement for `Int` and ~`1-2%` performance improvement (as well as `1%` reduction in allocation) for `BigInt`.

**Comment by malmaud** [comment]
@yuyichao What do you think of this solution?

**Comment by yuyichao** [comment]
LGTM as long as there `AbstractFloat` is the only type that can have infinity / nan....

I've also noticed that the speed up I've seen for the `Int` version might be related to https://github.com/JuliaLang/julia/issues/13551 (The results are very different with #13553 and the version that has special treatment for integers can be ~10% slower in some cases).

It's probably better to benchmark different versions and pick the best one.

**Comment by malmaud** [comment]
Hmm, maybe it would be more generic to reverse things and have the generic version check for infinity and nan and an int-specialized version bypass those checks.

**Comment by malmaud** [comment]
Alright, this is g2g.

**Pull request merged**
