### PR TITLE
Move pkg to stdlib

### PR DESCRIPTION
**Pull request by KristofferC**
This is some code movement to ease the transition to Pkg3 and pave the way for excision of LibGit2.

This will unfortunately break everyone's CI since `Pkg.test` will no longer work.
How does people feel to still import Pkg into Main and export it just to minimize breakage?

### CODE REVIEW

**Comment by KristofferC** [comment]
@iblis17 Do you know what happened at https://julia.iblis.cnmc.tw/#/builders/1/builds/4611/steps/7/logs/stdio? 

`gmake[1]: *** No rule to make target 'pkg'.  Stop.`

Do you run `make test-pkg` explicitly or something?

**Comment by iblis17** [comment]
@KristofferC yes, I run it explicitly.
https://github.com/iblis17/julia-fbsd-buildbot/blob/80b41103950c2a6df47e6e6291e66efe054d3f07/master/master.cfg#L95

So... it got removed after this PR?

**Comment by KristofferC** [comment]
It would be called `test-Pkg` after this PR. I also see that we do the same in Travis: https://github.com/JuliaLang/julia/blob/master/.travis.yml#L143.

**Comment by iblis17** [comment]
> Right now, it will be run together with the other stdlib tests but perhaps that is a problem. I'm guessing these where special cased for some reason.

well, the original reason that we do not have `pkg` related test in `make testall` is it required network access.

**Comment by ararslan** [comment]
> How does people feel to still import Pkg into Main and export it just to minimize breakage?

👍 Yes please, otherwise the fallout will be basically untenable.

**Comment by StefanKarpinski** [comment]
Note that in 0.7/1.0 the primary way to interact with the package manager will be with a REPL mode, and we can auto-load `Pkg` upon invoking the repl mode. So I'm not sure that making `Pkg` available by default in `Main` is the right thing to do.

**Comment by iamed2** [comment]
Unfortunately most Travis CI scripts use `Pkg` immediately.

**Comment by StefanKarpinski** [comment]
Ok, for now we should leave this then but we need a way to transition from Pkg2 to Pkg3 and they are not going to have 100% compatible APIs (although `Pkg.add("Name"))` should still work until there's a name conflict. It seems like a FemtoCleaner-like approach just for .travis.yml files would be feasible and easier than fully general FemtoCleaner is.

**Comment by KristofferC** [comment]
We should be able to make `clone` and `test` work which will ease things considerably.

**Comment by ViralBShah** [comment]
Are we likely to be able to make this excision happen, or will we leave it in place and have it be superseded by Pkg3? I guess it would be good to move out libgit2 along with this.

**Comment by StefanKarpinski** [comment]
@KristofferC, does it make sense to do this now or wait until we replace this with Pkg3?

**Comment by KristofferC** [comment]
I think it is easier to do this at the same time as Pkg3 is put in its place. After that, moving libgit2 out should be fairly easy.

**Comment by StefanKarpinski** [comment]
Excellent.

**Comment by KristofferC** [comment]
Closing this since it was decided this is to be done at the same time as the Pkg3 inclusion.

**Pull request closed without merging**
