### PR TITLE
release-1.6: set VERSION to 1.6-rc1

### PR DESCRIPTION
**Pull request by KristofferC**
cc @ararslan

### CODE REVIEW

**Comment by ararslan** [comment]
Is the Linux AArch64 failure known/expected?

**Comment by KristofferC** [comment]
Yeah, it's been like that for a long time.

**Comment by ararslan** [comment]
Ah, okay. I restarted it to see whether we get lucky, but if it's known to be flaky then I guess we don't need to wait for it.

**Comment by vtjnash** [comment]
That flaky test should hopefully be now fixed by https://github.com/JuliaLang/julia/pull/39482

**Pull request merged**
