### PR TITLE
Nit: Fix links in NEWS.md by running `NEWS-update.jl`

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes the out-of-date hyperlinks on NEWS.md.

It looks like that step was missed on https://github.com/JuliaLang/julia/issues/30061 and https://github.com/JuliaLang/julia/issues/30200

### CODE REVIEW

**Comment by ararslan** [comment]
It's really only necessary to do right before a release, but it's also fine to do earlier.

**Comment by stevengj** [comment]
(We don't generally do it in the PRs themselves because it creates lots of spurious conflicts between PRs.   But it is fine to have occasional separate PRs just to update the links.)

**Comment by NHDaly** [comment]
Ah, makes sense. Thanks for explaining that, @stevengj.

Should i remove that step from the CONTRIBUTING.md? It currently says:
> The news item should cross reference the pull request (PR) parenthetically, in the form `([#pr])`; **after adding this, run `./julia doc/NEWS-update.jl` from the `julia` directory to update the cross-reference links.**

**Comment by NHDaly** [comment]
Thanks @stevengj. I've changed that here: https://github.com/JuliaLang/julia/pull/30482

**Pull request merged**
