### PR TITLE
Update to LLVM 9

### PR DESCRIPTION
**Pull request by vchuravy**
We are still missing a patch [1] which I rebased recently,
but let's see how CI takes to this.

### TODO:
- [x] patch for D66657
- [x] patch for D71495
- [x] patch for D50010

[1] https://reviews.llvm.org/D50010

### CODE REVIEW

**Comment by staticfloat** [comment]
Just an FYI, I plan to merge this first: https://github.com/JuliaLang/julia/pull/34242

So this will need a bit of a rebase.

**Comment by JeffBezanson** [comment]
Adding to milestone for now, since we need this to enable the new stack/inline allocation optimization.

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
The windows failure seems potentially real:
```
Error in testset cmdlineargs:
Test Failed at D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\cmdlineargs.jl:441
  Expression: readsplit(`$exename -L $b -e 'exit(0)'`) == [realpath(b), ""]
   Evaluated: SubString{String}["C:\\Windows\\TEMP\\jl_SEGsMQ\\b.jl", ""] == ["C:\\Windows\\Temp\\jl_SEGsMQ\\b.jl", ""]
Error in testset cmdlineargs:
Test Failed at D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\cmdlineargs.jl:443
  Expression: readsplit(`$exename -L $b $a`) == [realpath(b), a, a, a, b, a]
   Evaluated: SubString{String}["C:\\Windows\\TEMP\\jl_SEGsMQ\\b.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\b.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl"] == ["C:\\Windows\\Temp\\jl_SEGsMQ\\b.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\b.jl", "C:\\Windows\\TEMP\\jl_SEGsMQ\\a.jl"]
Error in testset cmdlineargs:
```

@vtjnash mentioned offline that this might be due to alignment issue.

**Comment by staticfloat** [comment]
> Just noticed that it is `C:\\Windows\\TEMP` vs `C:\\Windows\\temp`. Who is lying here.

Both; it's actually `C:\\Windows\Temp`.  :joy:

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34418#issuecomment-578127944) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/7c1afa47cfd8e01fdd5fc3918ae35e5c4ded75ea/ed5564a_vs_4db419b/report.md). cc @ararslan

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34418#issuecomment-578129542) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/5b0850260e9c579168b755c2440899efd5204a7e/pkgeval/by_hash/a741e81_vs_4db419b/report.md). cc @maleadt

**Comment by vchuravy** [comment]
Looking at the failures in PkgEval:
- Autologistic: Different numerical answer
- FunctionOperators: Benchmark timing changed
- KernelDensityEstimatePlotting: Unsure
- KissMCMC: Different numerical answer
- PushVectors: Benchmark timing changed
- VoronoiDelaunay: Unsure

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = "@6af5f03d2ac7945b8cff3b5eee715a3d9446e42c")`

**Comment by vchuravy** [comment]
@nanosoldier `runtests(["Autologistic", "FunctionOperators", "InfiniteLinearAlgebra", "JuliaDB", "KernelDensityEstimatePlotting", "KissMCMC", "KrylovKit", "ProgressMeter", "PushVectors", "VoronoiDelaunay"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34418#issuecomment-578551910) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/b01d56fd62ce28835a68266be8a940de7b1f03ef/pkgeval/by_hash/a741e81_vs_6af5f03/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34418#issuecomment-578927225) has completed - no new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/aec71022daddfdbf933cca65b8f049e6b8d46af6/pkgeval/by_hash/a741e81_vs_a5c422f/report.md). cc @maleadt

**Pull request merged**
