### PR TITLE
Backports release 1.3.1

### LINKED ISSUE #32980: Stray icon-theme.cache file in the 1.2 Linux release
I downloaded the official Linux release of Julia 1.2 (julia-1.2.0-linux-x86_64.tar.gz). Compared to the 1.1.1 release, there is an additional file **icon-theme.cache** in the extracted archive at **share/icons/hicolor**. This file was probably shipped accidentally.

### LINKED ISSUE #33338: Random extreme slowdowns in multithreaded code
Files: https://gist.github.com/fredrikekre/dbe530ecf5fe542fad6564eba25fa0d8

Versioninfo:
```
julia> versioninfo()
Julia Version 1.4.0-DEV.77
Commit 2021d03 (2019-08-30 12:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

When run with 1 thread everything works nicely:
```
$ export JULIA_NUM_THREADS=1 && julia-master --project run.jl 
  1.232857 seconds (413.48 k allocations: 33.195 MiB)
```

with 2 threads, almost perfect scaling (consistently):
```
$ export JULIA_NUM_THREADS=2 && julia-master --project run.jl 
  0.646847 seconds (413.55 k allocations: 33.201 MiB)
```

with 3 or 4 threads you either get almost perfect scaling, or 100x slowdown:

```
$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
  0.351274 seconds (413.67 k allocations: 33.213 MiB)

$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
  0.362900 seconds (413.67 k allocations: 33.213 MiB)

$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
 36.957078 seconds (2.40 G allocations: 61.752 GiB, 52.65% gc time)

$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
 39.942106 seconds (2.40 G allocations: 61.752 GiB, 50.58% gc time)

$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
 38.238709 seconds (2.40 G allocations: 61.752 GiB, 51.50% gc time)

$ export JULIA_NUM_THREADS=4 && julia-master --project run.jl 
  0.375787 seconds (413.66 k allocations: 33.213 MiB)
```

Edit: This does not happen on Julia 1.1, but I see it on 1.2, 1.3 and master.

### LINKED ISSUE #33841: let-defined function with kwargs yields error about ifelse
If you use `let` to define a local function with keyword arguments, you will get this strange error:

```
julia> let a(; b) = b; end
ERROR: ArgumentError: ifelse: too few arguments (expected 3)
Stacktrace:
 [1] top-level scope at REPL[1]:1

julia> versioninfo()
Julia Version 1.3.0-rc4.1
Commit 8c4656b97a (2019-10-15 14:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, nehalem)
```

This also happens on julia 1.2.0, but not julia 1.1.0.

I came across this because I wanted to create an anonymous function with multiple methods, and it seemed the only way to do that was to give it a name in a local scope and then pass it out of that scope. Adapting an example from the docs, that looks like this:

```
let f(x::Float64, y::Float64) = 2x + y
  f(x::Number, y::Number) = 2x - y
  f
end
```

But it fails as above if the first method has keyword arguments.

One workaround is to use a `let` with no variable bindings, and use `local` inside it to introduce the function:

```
let
  local a(; b) = b
end
```

But it's strange that I have to do this for functions with keyword arguments when it's not necessary otherwise.

### LINKED ISSUE #33974: `filter` alters input values in arrays
Under julia 1.3, ```filter``` produces wrong output in the following example (see the tail of `vals_filt`):

```julia
n = 12000000
k = 257000000
vals = vcat(fill(0.5, n), fill(NaN, k))
vals_filt = filter(x -> x[2] < 1.0, collect(enumerate(vals)))

[Out]:
12000000-element Array{Tuple{Int64,Float64},1}:
 (1, 0.5) 
 (2, 0.5) 
 (3, 0.5) 
 (4, 0.5) 
 (5, 0.5) 
 (6, 0.5) 
 (7, 0.5) 
 (8, 0.5) 
 (9, 0.5) 
 (10, 0.5)
 (11, 0.5)
 (12, 0.5)
 (13, 0.5)
 ⋮        
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
 (0, 0.0) 
```

In contrast, the equivalent
```julia
vals_filt_lc = [x for x in collect(enumerate(vals)) if x[2] < 1.0]

[Out]:
12000000-element Array{Tuple{Int64,Float64},1}:
 (1, 0.5)       
 (2, 0.5)       
 (3, 0.5)       
 (4, 0.5)       
 (5, 0.5)       
 (6, 0.5)       
 (7, 0.5)       
 (8, 0.5)       
 (9, 0.5)       
 (10, 0.5)      
 (11, 0.5)      
 (12, 0.5)      
 (13, 0.5)      
 ⋮              
 (11999989, 0.5)
 (11999990, 0.5)
 (11999991, 0.5)
 (11999992, 0.5)
 (11999993, 0.5)
 (11999994, 0.5)
 (11999995, 0.5)
 (11999996, 0.5)
 (11999997, 0.5)
 (11999998, 0.5)
 (11999999, 0.5)
 (12000000, 0.5)
```
works correctly.

Versioninfo (path information manually removed):
```
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, westmere)
Environment:
  JULIA_PKGDIR = <removed>
  JULIA_WORKER_TIMEOUT = 3600
  JULIA_HOME = <removed>
  JULIA_NUM_THREADS = 40
```

If I do any of the following, the bug disappears:
- replace the NaNs with regular floats
- reduce the input array size, e.g. by setting `n` to 11000000 and/or `k` to 256000000
- run the code on julia 1.2

### LINKED ISSUE #33987: ``Vararg{Any}`` is not behaving the same as ``Vararg{Any, N} where N``
dear out there,

I just stumbled upon the maybe most weird julia bug I experienced so far

```
f1(args::(Vararg{Any, N} where N); kwargs...) = (args, kwargs)
f2(args::(Vararg{Any, N} where N)) = (args, 1)
f3(args::(Vararg{Any}); kwargs...) = (args, kwargs)

@show f1(1,2,3) f2(1,2,3) f3(1,2,3)
```
will print
```
f1(1, 2, 3) = (((1, 2, 3),), Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}())
f2(1, 2, 3) = ((1, 2, 3), 1)
f3(1, 2, 3) = ((1, 2, 3), Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}())
```
The core difference is that for ``f1`` the args get packed into an EXTRA level of Tuple...

Super weird, especially because 
* ``Vararg{Any} === Vararg{Any, N} where N`` gives ``true``

version: this run on julia 1.2.0

### LINKED ISSUE #34080: Behavior change in v1.3.0 regarding Symbol in a QuoteNode
I have just upgraded to v1.3.0 and I noticed a behavior change regarding `QuoteNode()`. Here is a MWE:

```julia
julia> Expr(:(.), 
           Expr(:(.), :Base, QuoteNode(Symbol("Enums"))),
           QuoteNode(Symbol("@enum")))
:(Base.Enums.var"@enum")
```

And here is what I used to get in v1.2.0:

```julia
julia> Expr(:(.), 
           Expr(:(.), :Base, QuoteNode(Symbol("Enums"))),
           QuoteNode(Symbol("@enum")))
:(Base.Enums.@enum)
```

which is the expected behavior.

My code heavily relies on this to automatically generate custom enum types. Please help. Thanks.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] JuliaLang/julia#33889 - Use `cache.julialang.org` to download `busybox.exe` at test time
- [x] JuliaLang/julia#33706 - codegen: avoid bad tbaa paths
- [x] JuliaLang/julia#33848 - fix JuliaLang/julia#33841, regression in let-bound function with kwargs
- [x] JuliaLang/julia#33942 - Fix a small number of invalid unsafe code [round 2]
- [x] JuliaLang/julia#33745 - Force `patchelf` to use 64KB page size on aarch64/powerpc64le
- [x] JuliaLang/julia#33617 - Update Mozilla CA certificate store to latest (10-16-2019) for libgit2 SSL.
- [x] JuliaLang/julia#33992 - fix JuliaLang/julia#33987, some varargs not recognized in kwarg lowering
- [x] JuliaLang/julia#34005 - fix JuliaLang/julia#33974, wrong integer types used in `jl_array_sizehint`
- [x] JuliaLang/julia#33890 - Fix colon-reshaping of OffsetVector
- [x] JuliaLang/julia#33848 - fix JuliaLang/julia#33841, regression in let-bound function with kwargs
- [x] JuliaLang/julia#34062 - ccall: report static compile-time load issues correctly
- [x] JuliaLang/julia#33926 - BUGFIX avoid silent overflow in `lcm` least common multiple function
- [x] JuliaLang/julia#33983 - Fix JuliaLang/julia#32980
- [x] JuliaLang/julia#34096 - tweak test for calling unknown libraries in --output-o mode
- [x] JuliaLang/julia#34065 - add another tuple subtyping fast path

Need manual backport:
- [ ] JuliaLang/julia#34081 - fix JuliaLang/julia#34080, regression in printing qualified macro calls

Contains multiple commits, manual intervention needed:
- [ ] JuliaLang/julia#33617 - Update Mozilla CA certificate store to latest (10-16-2019) for libgit2 SSL.

Non-merged PRs with backport label:
- [ ] JuliaLang/julia#33785 - Use UUID's to generate random tempname on Windows

### CODE REVIEW

**Comment by maleadt** [comment]
Did a manual NewPkgEval run with 1.2, 1.3 and 7704df0: https://maleadt.github.io/NewPkgEval.jl/

The following packages failed tests on this branch (a couple of others started failing with 1.3, but I've left those out):

 - [ ] [AsyPlots](https://maleadt.github.io/NewPkgEval.jl/detail/AsyPlots.html)
 - [ ] [Autologistic](https://maleadt.github.io/NewPkgEval.jl/detail/Autologistic.html)
 - [ ] [Cairo](https://maleadt.github.io/NewPkgEval.jl/detail/Cairo.html)
 - [ ] [Compose](https://maleadt.github.io/NewPkgEval.jl/detail/Compose.html)
 - [ ] [FFmpegPipe](https://maleadt.github.io/NewPkgEval.jl/detail/FFmpegPipe.html)
 - [ ] [FractionalGaussianFields](https://maleadt.github.io/NewPkgEval.jl/detail/FractionalGaussianFields.html)
 - [ ] [Gadfly](https://maleadt.github.io/NewPkgEval.jl/detail/Gadfly.html)
 - [ ] [GraphPlot](https://maleadt.github.io/NewPkgEval.jl/detail/GraphPlot.html)
 - [ ] [JuDoc](https://maleadt.github.io/NewPkgEval.jl/detail/JuDoc.html)
 - [ ] [PlanarMaps](https://maleadt.github.io/NewPkgEval.jl/detail/PlanarMaps.html)
 - [ ] [PlotMesh](https://maleadt.github.io/NewPkgEval.jl/detail/PlotMesh.html)
 - [ ] [Revise](https://maleadt.github.io/NewPkgEval.jl/detail/Revise.html)
 - [ ] [SMM](https://maleadt.github.io/NewPkgEval.jl/detail/SMM.html)
 - [ ] [StanMamba](https://maleadt.github.io/NewPkgEval.jl/detail/StanMamba.html)

**Comment by fredrikekre** [comment]
@StefanKarpinski, @staticfloat: `AsyPlots` fails with a tree hash mismatch on this branch but not on 1.3.0 :confused:  :
```
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   e80d1b7446d31c7738ed51fda764944d4bf1fcbe
│   Calculated git-tree-sha1: b37f6296f6e49bb2d602909f058cefbac9cdaa6e
└ @ Pkg.Artifacts /workspace/srcdir/julia/usr/share/julia/stdlib/v1.3/Pkg/src/Artifacts.jl:775
ERROR: Unable to automatically install 'FreeType2' from '/root/.julia/packages/FreeType2_jll/BxhKx
```

**Comment by KristofferC** [comment]
Most of them are hash errors.

**Comment by KristofferC** [comment]
Revise: passes locally
Autologistics: passed locally
SMM: passed locally
FFmpegPipe passed locally:
JuDoc: the test version guard in  https://github.com/tlienart/JuDoc.jl/commit/52f0ce2839b0170f82676bfa8f15a62a2320f56d is incorrect

**Comment by StefanKarpinski** [comment]
Looks like most failures were the tree hashing bug I introduced while fixing the other tree hashing bug. Better now?

**Comment by maleadt** [comment]
I'll rerun.

**Comment by KristofferC** [comment]
Wait, this branch isn't updated yet, no?

**Comment by maleadt** [comment]
> Wait, this branch isn't updated yet, no?

Oh right, it's only a mention not yet a commit on this branch. Thanks!

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.3")`

**Comment by fredrikekre** [comment]
Updated.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/33979#issuecomment-561218828) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/67fe78b3a2192c9d0cc92fd71730b28a818b6951/e77499c_vs_b42f4ab/report.md). cc @ararslan

**Comment by KristofferC** [comment]
Should check https://github.com/JuliaLang/julia/issues/34013 here.

**Comment by daviehh** [comment]
@KristofferC Thanks! Re: https://github.com/JuliaLang/julia/issues/34013, looks like `backports-release-1.3` is affected too:

```
using LinearAlgebra
using BenchmarkTools

ndim = 3

m1 = rand(ComplexF64,ndim,ndim);
m2 = rand(ComplexF64,ndim,ndim);
ou = rand(ComplexF64,ndim,ndim);

@btime mul!($ou, $m1, $m2);
```
returns
```
386.193 ns (1 allocation: 16 bytes)
```
with
```
julia> versioninfo()
Julia Version 1.3.1-pre.14
Commit 1a6baefb51* (2019-12-03 15:40 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
whereas release-1.3 version:
```
33.471 ns (0 allocations: 0 bytes)
```

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/33743 then maybe

**Comment by KristofferC** [comment]
I dropped those commits, they don’t seem necesasry to backport anyway.

**Comment by dkarrasch** [comment]
> I dropped those commits, they don’t seem necessary to backport anyway. This also fixed the regression.

I'm not sure this is doing justice to #33743. Dropping it temporarily is fair if there is some regression, but it was fixing other issues https://github.com/JuliaLang/julia/pull/29634#issuecomment-547922743, which are not nearly as deep as the regression "introduced" in #33743 due to failure of constant propagation. Of course, one could argue that they are not regressions because the functionality didn't exist before. But to me, it feels like a shame to advertise 5-arg `mul!`, but insist that the user must take care that coefficients have the exact same type as the matrix eltype, to avoid fallback to slow generic multiplication methods for calls like `mul!(C, A', B, -1, 0)` (with potentially big matrices). Either way, we do have serious performance issues.

**Comment by KristofferC** [comment]
We are very conservative with patch backports. It will be in 1.4 and have time to bake on master for a while.

**Comment by ViralBShah** [comment]
Would it be ok to bake it on master for longer and consider it for 1.3.2 or 1.3.3?

**Comment by StefanKarpinski** [comment]
It's unclear to me that it is "just a bug fix". It seems like it's adding functionality that didn't exist.

**Comment by dkarrasch** [comment]
I understand the concerns and the time frames, deadlines and life cycle etc., and am not advocating to blindly backport those PRs. Clearly, they do introduce a regression in some use cases as reported in #34013. Having said that, they also fix a major performance trap in generic usage of the 5-arg `mul!` that so many people have waited for so long time. Removal of the trap may be considered a "new feature", but then we should think about backporting a docstring PR in the mean time which clearly states the requirements to get dispatched to BLAS's 5-arg `mul!` in the case of dense matrices, perhaps including a note in NEWS.md. By
> the functionality didn't exist before

I was referring to "no generic 5-arg `mul!` before v1.3, so, just to be clear, #33743 did not introduce new functionality. Sorry for my potentially confusing wording.

**Comment by StefanKarpinski** [comment]
Performance fixes are fine, that's not the issue. There's the performance regression and then there's also the question of whether it adds functionality, which I'm unclear on.

**Comment by dkarrasch** [comment]
There's no added functionality there, just more dispatch away from generic mat-(vec/mat)-mul towards BLAS.

**Comment by StefanKarpinski** [comment]
Ok, then it seems fine to backport it once it doesn't introduce other regressions.

**Comment by maleadt** [comment]
w00t, the first successfull PkgEval run: https://github.com/maleadt/julia/commit/ac555be96068d5b0898f7afff01353e918b62dca#commitcomment-36287280 (on ac555be):

> [Your test job](https://github.com/maleadt/julia/commit/ac555be96068d5b0898f7afff01353e918b62dca#commitcomment-36287280) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/4f39518d0ef54c4300f7dbf618c54215e3957dba/ac555be_vs_46ce4d7/report.md). cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = "JuliaLang/julia#v1.3.0")`

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = "JuliaLang/julia#v1.3.0")`

**Comment by maleadt** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/33979#issuecomment-562924073) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/df660562b2dd1fc99b44e1ea582934701d8d421f/8639e57_vs_46ce4d7/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ApproxFunOrthogonalPolynomials" ,"BlackBoxOptim" ,"ChaosTools" ,"GlobalSensitivityAnalysis" ,"Graphics" ,"HyperDualMatrixTools" ,"IdentityRanges", "ImageCore" ,"NeuralNetDiffEq" ,"OffsetArrays" ,"PowerModels" ,"Reactive" ,"TensorNetworkAD" ,"UncertainData"], vs = "JuliaLang/julia#v1.3.0")`

**Comment by maleadt** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/33979#issuecomment-564427757) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/8e7a9e7d45897b8a4d0a8ee21757756e72b7eb81/pkgeval-8639e57_vs_46ce4d7/report.md). cc @maleadt

**Comment by KristofferC** [comment]
UncertainData.jl passed locally.

This should be good to go.

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = "JuliaLang/julia#v1.3.0")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/33979#issuecomment-566699710) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/97bd81809e489dba9d1759924d972ac4ff7ca9d7/pkgeval-480d867_vs_46ce4d7/report.md). cc @maleadt

**Comment by KristofferC** [comment]
```
Interval Intersection: Test Failed at /home/pkgeval/.julia/packages/IntervalTrees/wh2ex/test/runtests.jl:331
  Expression: !((IntervalTrees.firstintersection(t.root, Interval(4, 4), Interval(2, 2)))[1] === nothing)
   Evaluated: !(nothing === nothing)
```

I'm pretty sure I have seen this happened before, so don't think it is a regression with 1.3.1.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.3")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/33979#issuecomment-567116269) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ec64d46e2305e9c8bb1d0dceceabb0b893d66582/7b000e5_vs_ea58d3c/report.md). cc @ararslan

**Pull request merged**
