### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by MikeInnes**
Hopefully will help with https://github.com/JuliaLang/julialang.github.com/issues/463.

It may help for someone who has admin access to check the repo settings are in order (as in my screenshot on that thread).

Edit: looks like @ViralBShah set up newdocs.julialang.org to point here so I could change the cname to that to test it out.

### CODE REVIEW

**Comment by tkelman** [comment]
should this be in master or gh-pages?

**Comment by MikeInnes** [comment]
I'm not sure, I thought it was master but gh-pages does sound like it'd make more sense. It doesn't seem like this is mentioned it github's docs any more, so changing the repo's settings may be the right thing to do instead.

**Comment by ViralBShah** [comment]
I will do it on gh-pages.

**Comment by tkelman** [comment]
I'm getting a 404 now for docs.julialang.org, so it did something?

**Pull request closed without merging**
