### PR TITLE
Check sparse matrix is square before computing condition number

### LINKED ISSUE #12731: `Base.cond` and `Base.SparseMatrix.cond` don't not always check if input matrix is square
When attempting to compute the condition number of a rectangular matrix, `Base.cond` does not always fail, but when it fails it does not always fail for the right reasons:

```julia
julia> cond(randn(3,2))
1.6361841239391517

julia> cond(randn(3,2),1)
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at ./linalg.jl:179
 in cond at linalg/dense.jl:511

julia> cond(randn(3,2),Inf)
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at ./linalg.jl:179
 in cond at linalg/dense.jl:511

julia> cond(sprandn(3,2,.2))
ERROR: ArgumentError: 2-norm condition number is not implemented for sparse matrices, try cond(full(A), 2) instead
 in cond at sparse/linalg.jl:515
 in cond at sparse/linalg.jl:506

julia> cond(sprandn(3,2,.2),1)
ERROR: BoundsError: attempt to access 2x2 Array{Float64,2}:
 0.0        0.0     
 0.739339  -0.739339
  at index [1:3,1]
 in throw_boundserror at abstractarray.jl:153
 in normestinv at sparse/linalg.jl:570
 in cond at sparse/linalg.jl:508

julia> cond(sprandn(3,2,.2),Inf)
ERROR: DimensionMismatch("Q matrix size 2 and dense matrix has 3 rows")
 in qmult at sparse/spqr.jl:130
 in \ at sparse/spqr.jl:144
 in normestinv at sparse/linalg.jl:566
 in cond at sparse/linalg.jl:512
```

For rectangular matrices `cond` simply return `Inf` or raise an error (although I think `ArgumentError` would be more appropriate).

### PR DESCRIPTION
**Pull request by marcusps**
Fixes #12731

### CODE REVIEW

**Comment by stevengj** [comment]
You should put `(fixes #12731)` at the end of the commit message so that it will automatically close the issue when it is merged.

**Comment by Keno** [comment]
Putting it in the body of the pull request generally also works if it's merged through the web interface.

**Comment by marcusps** [comment]
Yep, it's there in the body (with a typo too). Should be ready to merge (now that the typo is fixed).

**Comment by andreasnoack** [comment]
I don't think we should throw the non-square exception for `p=2`.

**Comment by jiahao** [comment]
Sparse `p=2` is not implemented anyway, and `p=1,Inf` don't work correctly at the moment.

**Comment by andreasnoack** [comment]
I know that `p=2` is implemented, but this error shaddows the informative error message.

**Comment by jiahao** [comment]
Good point. I'll fix that

**Comment by marcusps** [comment]
What's wrong with sparse p=1,Inf ?

**Comment by andreasnoack** [comment]
I don't think there is anything wrong with them.

**Comment by jiahao** [comment]
I only meant that the code `p=1,Inf` doesn't work for rectangular matrices, which was the thing you were trying to fix.

**Pull request merged**
