### PR TITLE
[release-0.6] backports for 0.6.0-rc3

### PR DESCRIPTION
**Pull request by tkelman**
- [x] @nanosoldier `runbenchmarks(ALL, vs = ":release-0.6")` vs rc2
- [x] build:dog:
- [x] pkgeval

### CODE REVIEW

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/8b5a8443ba1c0a511dfd298fdee4b4e431f93045

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/8b5a8443ba1c0a511dfd298fdee4b4e431f93045

I will edit this comment as the build jobs complete.

**Comment by yuyichao** [comment]
Apparently it's not a good idea to call buildog in the top post yet...

**Comment by tkelman** [comment]
and it double-responds to edits?

@jlbuild !nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/8b5a8443ba1c0a511dfd298fdee4b4e431f93045

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/ea1cc8fe8aab22d5cc1168b5bb126dc1b593ce54

I will edit this comment as the build jobs complete.

**Comment by tkelman** [comment]
and pushes

**Comment by yuyichao** [comment]
Edited out the one in the top post. Let's see if it helps....

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22199) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/17880316bc98a8064eaa518f552acdbc25e9733e/16d3861_vs_68e911b/report.md). cc @jrevels

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/ea1cc8fe8aab22d5cc1168b5bb126dc1b593ce54

I will edit this comment as the build jobs complete.

**Comment by tkelman** [comment]
pkgeval results: https://gist.github.com/62d8d15eee91ce2332322a54fee0bffa

several 0.6-only package versions now have UndefVarErrors because of the scope change
- DeepDiffs, PortAudio, RingBuffers cc @ssfrr 
- SimilaritySearch cc @sadit (maybe already fixed on master by https://github.com/sadit/SimilaritySearch.jl/commit/c08a5c223d9e79969433bd5583907c5139d34608?)

InformationMeasures has a flaky tolerance, JuMP timed out

Unitful has an inference regression that needs bisecting

**Comment by tkelman** [comment]
The backport of #21771 broke Unitful so will get reverted unless there's a better fix proposed immediately, sorry @andyferris. It's also failing on master, so needs a fix anyway.

**Comment by tkelman** [comment]
probably no change but just in case
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.6")`
@jlbuild !nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```
I think the file test failure on some of the build workers might be if they don't have curl (or wget?) installed

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/e531c84f61182bf6c01ea1ea30abc8e1ce2ac3e7

I will edit this comment as the build jobs complete.

**Comment by andyferris** [comment]
>  The backport of #21771 broke Unitful so will get reverted unless there's a better fix proposed immediately, sorry @andyferris. It's also failing on master, so needs a fix anyway.

@vtjnash Do you understand this, Jameson? Is the Unitful problem to do with the changes to inference, or the changes to promotion?

**Comment by vtjnash** [comment]
It's a bug in Unitful that was being hidden by your fix.

**Comment by vtjnash** [comment]
Unitful bug fixed by https://github.com/ajkeller34/Unitful.jl/pull/89

**Comment by andyferris** [comment]
Awesome. Sounds like we should include #21771 here after all, @tkelman.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22199#issuecomment-306355967) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4b0eca72fde3d756d840a465e9183dafec1787bb/de540ad_vs_68e911b/report.md). cc @jrevels

**Comment by tkelman** [comment]
Ran pkgeval again with the latest few additional commits: https://gist.github.com/105a392d802f96abd017cbb747d5696d

Same scope issues in DeepDiffs, PortAudio, RingBuffers, and SimilaritySearch. ImageView failure wasn't happening in the last run, but I think the InexactError is an intermittent numerical problem that has happened on rc2 as well: https://github.com/JuliaCI/pkg.julialang.org/blob/cfad0830fc32634fa83e6c587ff9d79f0eba4ce8/logs/ImageView_0.6.log

In the interest of getting this rc out I'll merge and tag here, there are a few more backport-worthy bugfixes over the last day but some of them still need tests.

**Comment by tkelman** [comment]
DeepDiffs and RingBuffers issues were very simple fixes https://github.com/ssfrr/DeepDiffs.jl/pull/7 and https://github.com/JuliaAudio/RingBuffers.jl/pull/6, no change is needed in PortAudio it just needs the RingBuffers fix to get released

**Comment by davidanthoff** [comment]
Great! Can you post a message on discourse once the binaries are out so that lots of people will test this?

**Pull request merged**
