### PR TITLE
add rouding for DateTime to Date

### LINKED ISSUE #34782: Floor / Ceil  methods for Number and Period Inconsistency
I just noticed that the `floor` / `ceil`  methods for `Number` and `Period` have the positional arguments inverted.

```
floor(Int, 3.5)
using Dates
floor(DateTime("2000-01-31"), Month)
```

From Slack, Dates should be consistent with Base.

Related: #18574

### PR DESCRIPTION
**Pull request by Moelf**
fix #34782

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@omus or @quinnj, either of you willing to review this?

**Review by quinnj — APPROVED** [review]
LGTM

**Comment by simeonschaub** [comment]
It seems like this broke tests on master.

**Comment by fredrikekre** [comment]
Indeed
```
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.6/Dates/test/rounding.jl:198
  Expression: round(Date, now_, p) == round(Date, now_, p, RoundUp)
   Evaluated: Dates.Date("2020-09-01") == Dates.Date("2020-10-01")
```

**Comment by quinnj** [comment]
Ah, the answer has now changed since rounding up gives Oct 1 instead of Sept 1.

**Comment by quinnj** [comment]
Fix is up: https://github.com/JuliaLang/julia/pull/37528

**Pull request merged**
