### PR TITLE
Check that we don't name constants accidentally

### LINKED ISSUE #50260: Opaque pointer mode broken, throws assertion
#50094 broke `--opaque-pointers`:

```
❯ JULIA_LLVM_ARGS="--opaque-pointers" ./julia -e 'Base.compilecache(Base.identify_package("Test"))'
julia: /home/tim/Julia/src/julia/src/codegen.cpp:1810: llvm::GlobalVariable* get_pointer_to_constant(jl_codegen_params_t&, llvm::Constant*, llvm::StringRef, llvm::Module&): Assertion `val == gv->getInitializer()' failed.

[129671] signal (6.-6): Aborted
in expression starting at /home/tim/Julia/src/julia/build/dev/usr/share/julia/stdlib/v1.10/Test/src/precompile.jl:1
unknown function (ip: 0x7f181266526c)
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x7f18125fe45b)
__assert_fail at /usr/lib/libc.so.6 (unknown line)
get_pointer_to_constant at /home/tim/Julia/src/julia/src/codegen.cpp:1810
stringConstPtr at /home/tim/Julia/src/julia/src/cgutils.cpp:119
just_emit_type_error at /home/tim/Julia/src/julia/src/cgutils.cpp:1475
```

cc @pchintalapudi

### PR DESCRIPTION
**Pull request by pchintalapudi**
Fixes #50260

### CODE REVIEW

**Review by maleadt — APPROVED** [review]
LGTM, thanks!

**Comment by vtjnash** [comment]
So was the issue that we might accidentally mutate the name of a global or function?

**Comment by IanButterworth** [comment]
Worth adding the test from the issue?

**Comment by pchintalapudi** [comment]
Yeah I'm working on a bunch more opaque pointer tests, so I'll lump them all together in another PR.

**Pull request merged**
