### PR TITLE
Fix sparse checksums

### LINKED ISSUE #43896: Building in fresh git clone fails: sha512 checksum failure on SuiteSparse-5d7d1d69b9bc6597dcaee80a4c2e596237523b79.tar.gz
I am getting this on both a Mac and a Linux machine, with the current git master:
```
$ make
...
  ERROR: sha512 checksum failure on SuiteSparse-5d7d1d69b9bc6597dcaee80a4c2e596237523b79.tar.gz, should be:
      316af7423ac15c78714d2079b3a9959d49cb59f30b5b99b654714e54d0667c29
      bd3f08c1bd8e9b9890bdc22779e71e0e352ecf1a81ad61fb85ca745eea2ea855
  But `sha512sum /Users/horn/Projekte/Julia/julia/stdlib/srccache/SuiteSparse-5d7d1d69b9bc6597dcaee80a4c2e596237523b79.tar.gz | awk '{ print $1; }'` results in:
      1cce0d88be2f28c8b1d49bef65899ae6a4620e0dc18cb509deb1d248d7b0efe0
      d383be22744ace4be349f51d6ab91d7b597eccb2c38dc1690327f59d649f3be4
  This can happen due to bad downloads or network proxies, please check your
  network proxy/firewall settings and delete
  /Users/horn/Projekte/Julia/julia/stdlib/srccache/SuiteSparse-5d7d1d69b9bc6597dcaee80a4c2e596237523b79.tar.gz
  to force a redownload when you are ready
===============================================================================
make[1]: *** [SuiteSparse-5d7d1d69b9bc6597dcaee80a4c2e596237523b79/source-extracted] Error 2
make: *** [julia-stdlib] Error 2
$
```
I tried to force-redownload as advised but no change. The tarball looks fine in general (not corrupt).

### PR DESCRIPTION
**Pull request by ViralBShah**
Fix #43896

### CODE REVIEW

**Comment by ViralBShah** [comment]
This works locally for me, but it seems that there is some caching that is getting in the way.

**Comment by ViralBShah** [comment]
@DilumAluthge Is this doing all the right steps in bumping the stdlibs by hand? I need to do all the URL moves and the checksum generation by hand in one PR.

**Comment by DilumAluthge** [comment]
It looks correct to me. It's always tricky with these deps bumps, which is why I prefer to automate it.

Let's merge, since CI is happy. @fingolfin and @IanButterworth, it would be great if you could try to build the new master and make sure it works for you locally.

**Comment by fingolfin** [comment]
Works now, thanks

**Pull request merged**
