### PR TITLE
Fix TBAA tag when emitting memcpy

### LINKED ISSUE #47138: Simd regression with AoS dest on master.
Suddenly find that `a .= complex.(b, c)` could not be vectorlized on master.
I thought it might be caused by different LLVM version but bisect points to 7f2bb7df8e3bf06f81d6984c1663a61705f3b579(#45606) cc @vtjnash.
(So looks like LLVM dislikes `memcpy` for field stores in some cases?)

MWE:
```julia
julia> a = randn(ComplexF32, 1000); b = real(a); c = imag(a);        

julia> @btime $a .= complex.($b, $c)
  825.641 ns (0 allocations: 0 bytes) # 180ns before #45606
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Should fix #47138. Not sure if this is correct though. It generates the same code it did on 1.8.

### CODE REVIEW

**Comment by KristofferC** [comment]
Maybe add the tests from https://github.com/JuliaLang/julia/pull/47164?

**Comment by gbaraldi** [comment]
This is wrong somwhere. It worked when I used a prebuilt sysimg, but it seems this makes building it not work/Take a loooong time.

**Comment by N5N3** [comment]
I tried something like
```c
if (tbaa_dst == ctx.tbaa().tbaa_arraybuf)
        ctx.builder.CreateMemCpy(dst, MaybeAlign(align), src, MaybeAlign(0), sz, is_volatile, tbaa_src);
    else
        ctx.builder.CreateMemCpy(dst, MaybeAlign(align), src, MaybeAlign(0), sz, is_volatile, MDNode::getMostGenericTBAA(tbaa_dst, tbaa_src));
```
It works for `ComplexF32` and building works fine (Not tested though). But when I test something like `NTuple{3,Float32}` or `NTuple{4,Float32}` it failed.
I tested it with c, and it seems also not to work.

**Comment by KristofferC** [comment]
I think this can be closed with the new TBAA stuff merged.

**Pull request closed without merging**
