### PR TITLE
Added missing backslash in doc/stdlib/math.rst for Element-wise left …

### PR DESCRIPTION
**Pull request by justapoise**
…division operator example.

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @justapoise I think you'll need to change the doc string in the source file as well, otherwise the next time someone runs `make docs` your change will be overwritten.

**Comment by justapoise** [comment]
@kshyatt I checked just now and luckily the backlash was already there.

**Comment by kshyatt** [comment]
Yes, but there's something wrong with it there because it's not making it
through the doc build procedure

**Comment by justapoise** [comment]
I see, what I changed only fixed if someone runs make html inside doc folder. I've fixed it now, maybe I'll make another pull request.

**Comment by kshyatt** [comment]
Nice work! This should be ok once CI passes. Thanks for catching & fixing this. This looks like it's your first PR to Julia, right? Welcome to the Julia community, @justapoise :).

**Pull request merged**
