### PR TITLE
camel-case `iteratorsize` and `iteratoreltype`

### PR DESCRIPTION
**Pull request by JeffBezanson**
This matches other traits better.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by ararslan** [comment]
Will there be any possibility of a performance regression since the functions are no longer precompiled?

**Comment by JeffBezanson** [comment]
We need to update the precompile files anyway (#24666).

**Comment by nalimilan** [comment]
+1

While we're at it we should decide whether it's a good convention that traits start with `Type` as do `TypeOrder`, `TypeArithmetic` and `TypeRangeStep` in traits.jl. That convention isn't used anywhere else AFAIK, so the situation is inconsistent. Personally I don't really like these "Type" prefixes, as it's not clear what they mean.

**Comment by JeffBezanson** [comment]
Those names sound backwards to me; I'd expect `OrderType` or `OrderStyle` (to go with `IndexStyle`). But less urgent.

**Pull request merged**
