### PR TITLE
Revert #182599 "add faster done for strings"

### PR DESCRIPTION
**Pull request by KristofferC**
My bad for merging without getting a proper review.

cc @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
probably shouldn't have squashed this, worth backporting the added test

**Comment by KristofferC** [comment]
As @TotalVerb pointed out, this test might not be good because it is creating an invalid UTF8 String. Perhaps the original fix is correct for all valid strings. But someone more knowledgeable than about UTF should probably comment.

**Comment by tkelman** [comment]
okay, but while "what to do with invalid unicode" is still being worked out, I'm not going to backport any behavior changes right now

**Comment by KristofferC** [comment]
Yes, I just meant not backport the test.

**Comment by TotalVerb** [comment]
See #18280.

**Pull request merged**
