### PR TITLE
deepcopy: recurse through immutable objects with mutable fields.

### PR DESCRIPTION
**Pull request by StefanKarpinski**
I've encountered a number of cases which have caused me to believe that recursing through immutable types with mutable fields is the right thing to do. One example (currently broken on master), is OrderedDict [1] from DataStructures – this type is a lightweight, immutable wrapper around HashDict [2], which is mutable. The current deepcopy behavior means that doing `od2 = deepcopy(od1)` simply returns `od1`, which is clearly not what is wanted. This could be fixed in the DataStructures package, but I suspect wanting to copy through immutables is the rule, not the exception.

Philosophically, the only coherent way to define at a conceptual level what deepcopy _should_ do that I've come up with is that it should be functionally equivalent to serializing and then deserializing an object. That would recursively copy through immutable types with mutable fields, which is another justification for this change.

I _believe_ that not sticking immutable objects in `stackdict` is correct, but I'm not 100% sure. My reasoning is that in order for a path from the root of a data structure to have a loop, it has to have passed through a mutable object since otherwise you couldn't have constructed the structure in the first place (unless you cheated, in which case you have only yourself to blame), at which point the deepcopy recursion will stop once that mutable object is reached a second time. There may be some unnecessary copying of immutable objects, but I think it's harmless.

[1] https://github.com/JuliaLang/DataStructures.jl/blob/master/src/ordereddict.jl
[2] https://github.com/JuliaLang/DataStructures.jl/blob/master/src/hashdict.jl

### CODE REVIEW

**Comment by kmsquire** [comment]
This should be okay to backport, right?  https://github.com/JuliaLang/DataStructures.jl/issues/75 is exactly the issue @StefanKarpinski mentions in the description above.

**Comment by tkelman** [comment]
I guess. Could this conceivably break anything? Or conversely, how likely would it be that people could begin relying on changed behavior for 0.3.7-or-later without realizing it or being careful about package `REQUIRE`s?

**Comment by kmsquire** [comment]
The previous behavior is pretty sketchy, so I think it's unlikely that someone would be relying on it.  I also think that this is a bug fix, and that everything up through 0.3.6 is broken.

> Or conversely, how likely would it be that people could begin relying on changed behavior for 0.3.7-or-later without realizing it or being careful about package REQUIREs?

I guess that someone could have redefined `deepcopy` to work around this behavior in some package, notice it's been fixed, and remove that workaround, breaking the packages on v0.3.6 or earlier.  Is the better solution then, to make sure that every package who needs the correct behavior implement a workaround for `deepcopy`?  The only packages that I have installed that redefine `deepcopy` are `DataArrays` and `DataFrames`, but I don't have many packages installed right now.

I can understand either way--I just find the latter idea annoying.

**Comment by tkelman** [comment]
If a few packages are already defining workarounds, then they should either adjust their `REQUIRE` if they remove the workaround, or do a Compat-style check against `VERSION` to conditionally apply the workaround after this gets backported. As long as the relevant people are paying attention and careful about doing that, then good enough for me.

**Comment by tkelman** [comment]
squashed and backported in b55539a0fb6c39e9001f34b45f059700982754a6

**Comment by PallHaraldsson** [comment]
"added the backport pending label on Mar 3"

I was looking at NEWS (seeing what might be new in 0.3.8 and found nothing):

"squashed and backported in b55539a"

Was this supposed to say 0.3.8 not 0.3.7 in NEWS?

**Comment by tkelman** [comment]
That backport was in March, prior to the release of 0.3.7. I only modify NEWS.md on release-0.3 if the commit I'm backporting touches that file. It's very rare to backport commits that are significant enough to warrant mentioning in NEWS.md.

**Comment by StefanKarpinski** [comment]
Indeed, any commit that touches NEWS almost by definition doesn't belong in a bug-fix release.

**Comment by PallHaraldsson** [comment]
Ok. It just felt March 3 wasn't that long ago.. but it's pre-0.3.7 then.. Still, assume (non-NEWS-worthy) backports only done as I described.

**Comment by tkelman** [comment]
We might conceivably do a few more backports to release-0.3 even after 0.4.0 gets released, but only if it's fixing some especially important bug.

**Pull request merged**
