### PR TITLE
Fix missing "->" in Documentation docs

### PR DESCRIPTION
**Pull request by darwindarak**

### CODE REVIEW

**Comment by tkelman** [comment]
@one-more-minute did we get rid of the need for this?

**Comment by dpo** [comment]
See also https://groups.google.com/forum/m/?fromgroups#!topic/julia-users/L_hn3HlWqxc

**Comment by tkelman** [comment]
Bump @one-more-minute can you please take a look at this?

**Comment by tkelman** [comment]
Thanks

**Pull request merged**
