### PR TITLE
[release-0.5] Fix computation of range length in certain cases (fix 0.5/#20373)

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This is the 0.5 edition: with this change a, b, n are always hit exactly by `a:s:a+n*s` construction tests. There are two parts to the fix:

1. check that the lifted rational endpoint is exact even *after* we've reduced terms of the fractions;
2. apply the same fix that I've proposed for the length in the non-lifted case.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
@tkelman: is there a known problem with CI for 0.5, is this why you can't get 0.5.1 out?

**Comment by StefanKarpinski** [comment]
Blocked on https://github.com/JuliaLang/julia/pull/20483.

**Comment by tkelman** [comment]
I don't want to merge behavior changes onto release-0.5 without regression-testing them against pkgeval, so I'm going to change the target branch of this and pull it into a larger backport branch first

**Comment by StefanKarpinski** [comment]
I need to update this to include further fixes. Now that CI should work, I can push that.

**Comment by StefanKarpinski** [comment]
This is ready to go for 0.5, @tkelman. Feel free to merge, cherry-pick, whatever suits you.

**Comment by StefanKarpinski** [comment]
Bump.

**Pull request merged**
