### PR TITLE
Define AArch64 as "not x86"

### PR DESCRIPTION
**Pull request by ginggs**
Originally posted by @pao in #10791

[pao: fix my own username :D]

### CODE REVIEW

**Comment by nalimilan** [comment]
The original piece of code looks strange to me. Couldn't there simply be a `else` clause setting `ISX86:=0` for all other architectures? Looks like we only set BINARY for x86 anyway, and we know all possible ARCH values for this platform.

**Comment by ginggs** [comment]
@nalimilan: thanks! updated.

**Comment by nalimilan** [comment]
@ginggs Thanks, but I should have made it clearer that my comment was addressed to other developers to get their opinion about this. I hope they don't prove me wrong and that you don't have to go back to your original patch...

**Comment by ginggs** [comment]
@nalimilan No worries, that was how I understood your comment.  I figured I'd just provide both options, for comparison.

@pao Sorry for mangling your username!

**Comment by pao** [comment]
No problem! I probably should have submitted this; just didn't think about it. Thanks!

**Comment by nalimilan** [comment]
@tkelman @ViralBShah Is this OK to merge? I've just bumped into this problem, and indeed raising an error without even allowing the caller to specify the word size by hand is quite inconvenient.

**Comment by tkelman** [comment]
This is probably okay, but I do wonder what would happen with random other exotic arches that people may try to build Julia on.

**Comment by nalimilan** [comment]
It will probably fail somewhere in the build. :-)

The point is to make it possible to continue with the build, trying several build flags until it (possibly) works.

**Comment by ViralBShah** [comment]
This is good to merge to solve the immediate problem. Should ideally squash these commits though.

**Comment by ginggs** [comment]
Squashed.  Thanks for considering!

**Comment by ViralBShah** [comment]
I guess BINARY is not strictly required here, but may be required eventually to get 64-bit BLAS going and such.

**Comment by ginggs** [comment]
Could this be backported to the 0.4 series please?

**Comment by StefanKarpinski** [comment]
If it doesn't cause any problems on master for a bit this should be safe.

**Comment by IainNZ** [comment]
@tkelman I labelled it so it can at least be considered, not a vouch of confidence for backportability

**Comment by ViralBShah** [comment]
This should be safe for a backport.

**Pull request merged**
