### PR TITLE
make \minus equivalent to - operator #26193

### LINKED ISSUE #26193: Unicode: Supporting middle dot & real minus
Would be nice if you could equal `·` (`U+b7`) with the currently existing `\cdot[TAB]` (`U+22c5`), as on some keyboard layouts (like the german Neo2) you could directly produce that. You there also can produce the real minus glyph `−` (`U+2212`), which has the same width as the plus sign, but sadly isn’t supported in Julia yet, too.

### PR DESCRIPTION
**Pull request by epithet**
Add the typographically more correct minus sign `−` (`\minus`) as an alternative for the traditionally used hyphen-minus `-` (which is readilly available on all keyboard layouts).

To many, it is aesthetically more pleasing because it has the same width as `+`. But the main advantage is that it would allow for copy-pasting negative numbers (and to some degree, formulas with subtractions) from correctly typeset PDF/HTML/... documents into Julia code. Actual code snippets can also accidentally be "beautified" by CMS/blog software, word processors, e-mail clients, etc.

Fixes #26193.

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Welcome and great first PR! Seems like a good idea.

**Comment by JeffBezanson** [comment]
This should make it work as an operator, but we also parse `-` as part of negative numeric literals, so some additional changes are needed to make that work.

**Comment by JeffBezanson** [comment]
Oh wait I'm wrong, negative literals go through `parse-unary` so they're already handled. There should be a test for it though.

The remaining case is floating point exponents, e.g. `1.0e-1`; we might want to allow the minus there as well.

**Comment by JeffBezanson** [comment]
`−=` should maybe also be added.

**Comment by epithet** [comment]
@JeffBezanson very good points! I'll see what I can do.

**Comment by epithet** [comment]
@JeffBezanson 
- have I missed something? (implementation or test coverage)
- should the documentation mention all these cases?
- there seem to have been some unrelated hiccups in the CI pipeline, see commit bc48a59

**Comment by epithet** [comment]
btw: I remembered the existence of `rlwrap` only halfway through. Could be helpful to mention it here, for example: https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/doc/src/devdocs/eval.md#parsingid-dev-parsing
(seemed too insignificant for a separate PR/issue, and not entirely off-topic)

**Comment by oscardssmith** [comment]
triage approves.

**Pull request merged**
