### PR TITLE
Remove indirect dependency on system ZLIB

### PR DESCRIPTION
**Pull request by vchuravy**
IIUC we have been trying to minimise our dependency tree and one of those dependencies we previously excised was ZLIB.
I reviewed a build of mine that I had laying around and besides system libraries the only indirect dependency (e.g. that we don't provide by default and that is pulled in by one of our main dependency)
was ZLIB, which was pulled in by LLVM and libgit. This builds LLVM without ZLIB support (should be a NFC since we don't use compression) and uses the bundled ZLIB for libgit.

Indirect dependencies can cause issues for downstream users like Conda.jl so IMHO it is best to minimise them as much as possible.

### CODE REVIEW

**Comment by vtjnash** [comment]
> should be a NFC since we don't use compression

In some cases, we may try to use zlib to read debug info (dwarf dwz files). LLVM should fail gracefully here (e.g. just return "debug info not present") if it is turned off, so we'll just lose line number information for those libraries, but it's not entirely NFC.

**Comment by stevengj** [comment]
Hopefully this will resolve JuliaPy/PyPlot.jl#151, which is a longstanding issue arising from Julia linking an older version of ZLIB than the one required by Anaconda's libraries.

**Comment by ararslan** [comment]
Good to go?

**Review by stevengj — APPROVED** [review]

**Comment by ararslan** [comment]
Let's give this guy another run through CI just in case. I believe Elliot has since fixed the issue on macOS.

**Comment by ararslan** [comment]
Oh, I think the tests failed because of that httpbin thing. Let's try this again. Sorry for the close/reopen spam, Valentin.

**Comment by ararslan** [comment]
All green except 64-bit Windows, which timed out.

**Pull request merged**
