### PR TITLE
release-1.6: Backports for julia-1.6.4

### LINKED ISSUE #27184: REPL completion error: UndefVarError
Open julia with REPL, type `@nonexist.` and hit Tab:

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5138 (2018-05-19 22:52 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a465d33f6 (1 day old master)
|__/                   |  x86_64-redhat-linux

julia> @nonexist.┌ Error: Error in the keymap
│   exception =
│    LoadError: UndefVarError: @nonexist not defined
│    Stacktrace:
│     [1] top-level scope
│     [2] lower at ./meta.jl:68 [inlined]
│     [3] get_type(::Expr, ::Module) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:362
│     [4] complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##15#17"))) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:63
│     [5] completions(::String, ::Int64) at /TEST/usr/share/julia/stdlib/v0.7/REPL/src/REPLCompletions.jl:648
...

```

### LINKED ISSUE #41908: julia type inference crashes (typeerror)
my tests started crashing with the stacktrace:

```
Internal error: encountered unexpected error in runtime:
TypeError(func=:AbstractTensorMap, context="S", expected=S<:(TensorKit.ElementarySpace{𝕜} where 𝕜), got=TensorKit.HomSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}})
jl_type_error_rt at /home/maarten/julia/src/rtutils.c:119
check_datatype_parameters at /home/maarten/julia/src/jltypes.c:1229
inst_datatype_inner at /home/maarten/julia/src/jltypes.c:1392
...
```

happens at least on julia 1.6.2, and also on master.

I wasn't able to really reduce it down very far, as it's a reasonably large codebase. To run it, you need my fork of TensorKit.jl, and the planocalypse branch of MPSKit.jl . I will try to reduce it down further, but so far I didn't have much luck.

```
using TensorKit,MPSKit;

#define some new sectortype - with the property that braiding is forbidden
struct PlanarTrivial <: TensorKit.Sector end
struct 𝔹 end
Base.:^(::Type{𝔹}, d::Int) = GradedSpace(PlanarTrivial()=>d);

Base.one(::Type{PlanarTrivial})  = PlanarTrivial();
Base.conj(c::PlanarTrivial) = PlanarTrivial();
TensorKit.:⊗(c1::PlanarTrivial, c2::PlanarTrivial) = (PlanarTrivial(),)

Base.IteratorSize(::Type{TensorKit.SectorValues{PlanarTrivial}}) = TensorKit.HasLength()
Base.length(::TensorKit.SectorValues{PlanarTrivial}) = 1
Base.iterate(::TensorKit.SectorValues{PlanarTrivial}, i = 0) = i==0 ? (PlanarTrivial(),1) : nothing;
Base.getindex(::TensorKit.SectorValues{PlanarTrivial}, i::Int) = i == 1 ? PlanarTrivial() : ArgumentError("lol");
TensorKit.findindex(::TensorKit.SectorValues{PlanarTrivial}, c::PlanarTrivial)  = 1
Base.isless(::PlanarTrivial, ::PlanarTrivial) = false;
TensorKit.BraidingStyle(::Type{PlanarTrivial}) = TensorKit.NoBraiding();
TensorKit.FusionStyle(::Type{PlanarTrivial}) = TensorKit.UniqueFusion();
TensorKit.Fsymbol(args::Vararg{PlanarTrivial,6}) = 1
TensorKit.Nsymbol(args::Vararg{PlanarTrivial,3}) = 1


# use mpskit
alg = GradientGrassmann(verbosity=0,maxiter=1);
mpo = InfiniteMPO([TensorMap(rand,ComplexF64,𝔹^2*𝔹^2,𝔹^2*𝔹^2)]);
state = InfiniteMPS([𝔹^2],[𝔹^10]);
(state,envs) = leading_boundary(state,mpo,alg);

```

### LINKED ISSUE #42220: `::Type{T}=Float64` argument breaks hygiene?
If this is not a misinterpretation on my side, I find the following a bit shocking:

```julia
julia> macro test1()
           return quote
               function foo(::Type{T}=Float64) where {T}
                   return Vector{T}(undef, 10)
               end
           end
       end
@test1 (macro with 1 method)

julia> @test1()
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1

julia> function foo(::Type{T}=Float64) where {T}
           return Vector{T}(undef, 10)
       end
foo (generic function with 2 methods)

julia> foo()
10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

[Over on Zulip](https://julialang.zulipchat.com/#narrow/stream/274208-helpdesk-.28published.29/topic/Macro.20expansion.20broken.2C.20but.20macro.20works.3F.3F), someone suggested to uncomment some debug printing in `jlfrontend.scm` -- the top of the Lisp stack trace you get is (for a different example macro with variable `TV`, though):

```
(type-error car cons ())
unexpected error: #0 (caddr (:: (curly Type TV)))
#1 (resolve-expansion-vars-
 (kw (:: (curly Type TV)) (curly Vector Float64))
 ((n . |#118#n|) (|#unused#| . |#119##unused#|) (TV . |#120#TV|))
 #<julia: DynamicPPL> () #t)
```

But I'm unable to interpret that.  ([Here](https://gist.github.com/devmotion/077af8c2a35d49964fdde7d1b3a593ea)'s the full example, run on the phg/unescape branch of Turing.jl.)

### PR DESCRIPTION
**Pull request by KristofferC**
- [x] #40621 <!-- REPL: fix #27184, ensure macro existence before lowering -->
- [x] #41860 <!-- MINSIGSTKSZ is no longer constant in glibc -->
- [x] #41870 <!-- Only do NFD normalization for latex tab-completion if needed -->
- [x] #41976 <!-- fix #41908, inference error in subst_trivial_bounds -->
- [x] #42140 <!-- (#42139) Fixes _is_mailto in resolution of autolink in Markdown module -->
- [x] #42119 <!-- eagerly do boundscheck when indexing into CartesianIndices -->
- [x] #42185 <!-- `Base.julia_cmd()`: correctly forward the `--sysimage-native-code=no` flag if it is provided -->
- [x] #42221 <!-- fix #42220: macro hygiene with unary `::` -->
- [x] #42315 <!-- Slightly loosen a test so that linalg tests pass when using MKL -->
- [x] #42347 <!-- Fix problem with union spliting during inlining, add regression test -->
- [x] #42417 <!-- fix verifier to allow GlobalRef as assignment RHS -->
- [x] #42462 <!-- tests: add help and reflection abilities to choosetests option parser -->
- [x] #42499 <!-- Distributed: improve some of the tests in the Distributed test suite when multithreading is enabled -->
- [x] #42526 <!-- [buildkite] Fix env leakage of signed tokens -->
- [x] #42533 <!-- make tests ignore root more robustly -->
- [x] #42545 <!-- Add option to allow `stale_cachefile` to ignore loaded modules (for Pkg.precompile) -->
- [x] #42576 <!-- Fix libgit2 error throw -->
- [x] #42623 <!-- Base: fix `tryparse(Bool, " ")` -->
- [x] #42635 <!-- fix #42590, long attribute loop compiling `cfunction` -->
- [x] #42667 <!-- Add cryptic secret for docs deploy key -->
- [x] #42721 <!-- Disable `DL_LOAD_PATH` prepending for `@`-paths on Darwin -->
- [x] #42723 <!-- `choosetests`: return a `NamedTuple` (instead of a `Tuple`), to make it easier to add more information in the future -->
- [x] #42737 <!-- fix unique over a dimension to use `isequal` over `==` -->
- [x] #42753 <!-- Distributed test suite: increase the timeout in the `poll_while` function from 60 seconds to 120 seconds -->
- [x] #42764 <!-- Distributed test suite: if `Threads.nthreads() > 1`, skip certain tests -->
- [x] #42773 <!-- Optimize show(io::IO, m::Module) -->
- [x] #42864 <!-- Test.jl: no longer explicitly print some things in white -->
- [x] #42862 <!-- Test suite: improve the warning that we print when we skip the `Profile` tests on ARM -->
- [x] #42532 <!-- Use the module specific names in `names()` instead of the binding -->
- [x] #42889 <!-- `choosetests`: add the `--force-net` option, which will throw an error if networking is unavailable -->
- [x] #42890 <!-- `choosetests`: `Pkg/pkg` is no longer relevant -->
- [x] #42930 <!-- Eliminate `@loader_path/julia` element of `DL_LOAD_PATH` -->
- [x] #42941 <!-- Distributed test suite: mark another test as thread-unsafe -->
- [x] #41900 <!-- Update BinaryBuilder libuv to 2.0.1+4 -->
- [x] #42970 <!-- Fix libunwind segfaults from JIT frames on FreeBSD -->
- [x] #42958 <!-- Add missing type parameter to TakeWhile -->
- [x] #43012 <!-- `file` tests: in the `"tempname with parent"` test, temporarily unset the `TMPDIR` environment variable while running the test -->


<details>
<summary>Backported CI PRs:</summary>

- [x] #41934 <!-- CI: Work around registry corruption issues -->
- [x] #42118 <!-- Fix the `cmdlineargs` tests on Buildkite -->
- [x] #42193 <!-- CI (Buildkite, code coverage): increase the value of `JULIA_WORKER_TIMEOUT` on the code coverage job -->
- [x] #42213 <!-- CI (Buildkite, code coverage): Fail the code coverage job if the coverage is suspiciously low -->
- [x] #42138 <!-- CI (Buildkite, GHA): Allow any user with triage or commit permissions to retry all failed Buildkite jobs -->
- [x] #42229 <!-- CI (Buildkite): in the experimental `asan` job, remove the "Test that ASAN is enabled" step (but keep the "Build julia-debug with ASAN" step) -->
- [x] #41707 <!-- CI (Buildkite): Add `package_linux` and `tester_linux` for more Linux architectures -->
- [x] #42389 <!-- CI (GHA): Only run the `Statuses` workflow when a pull request is opened or synchronized -->
- [x] #42386 <!-- CI (GHA): update to the latest commit of the `retry-buildkite` action -->
- [x] #42470 <!-- CI (Buildkite): explicitly set the `OPENBLAS_NUM_THREADS` environment variable -->
- [x] #42475 <!-- CI (Buildkite): in the Buildkite cache, don't cache the "registries" directory in the default depot -->
- [x] #42478 <!-- CI (Buildkite): move the `asan` job from "experimental" to "main" -->
- [x] #42488 <!-- CI (Buildkite): fix the signature for the scheduled coverage pipeline -->
- [x] #42476 <!-- CI (Buildkite): add `package_musl64` and `tester_musl64` (Linux, musl libc, 64-bit, x86_64 architecture) -->
- [x] #42444 <!-- CI: add TSAN to the sanitizers pipelines -->
- [x] #42511 <!-- CI (buildkite): ensure passing --output-sync when passing -j -->
- [x] #42531 <!-- CI (Buildkite): delete an empty YAML file -->
- [x] #42514 <!-- CI (Buildkite): reorganize some of the logic in the `tester_linux.yml` file -->
- [x] #42541 <!-- CI (Buildkite): TEMPORARILY allow the `asan` job to fail -->
- [x] #42640 <!-- CI (Buildbot, GHA): Rename "Statuses" to "Create Buildbot Statuses" -->
- [x] #42641 <!-- CI (Buildkite, GHA): Rename "Retry" to "Retry Failed Buildkite Jobs" -->
- [x] #42642 <!-- CI (Buildkite, GHA): in the "Retry Failed Buildkite Jobs" workflow, remove the `labeled` trigger -->
- [x] #42592 <!-- CI (Buildkite): Add a once-daily scheduled job that builds Julia with `USE_BINARYBUILDER=0` (and runs the test suite) on linux64 -->
- [x] #42655 <!-- Add a comment trigger for rerunning failed Buildkite jobs -->
- [x] #42657 <!-- CI (Buildkite, GHA): Fix some bugs in the "Retry" workflow -->
- [x] #42479 <!-- CI (Buildkite): Run the Distributed test suite with multithreading enabled -->
- [x] #42724 <!-- CI (Buildkite): fix the timeout for the `tester_linux` job that runs under `rr` -->
- [x] #42803 <!-- CI (Buildkite): make sure to gitignore any unencrypted repo keys, regardless of where they are located in the repository -->
- [x] #42802 <!-- CI (Buildkite): Update all rootfs images to the latest versions -->
- [x] #42861 <!-- CI (Buildkite): add a separate Buildkite job that runs the tests of the network-related stdlibs (e.g. Downloads.jl), and automatically retries that job up to a maximum number of tries -->
- [x] #42859 <!-- CI (Buildkite): `choosetests`: preparations for setting up a separate Buildkite job that runs the `Pkg` test suite -->
- [x] #42885 <!-- CI (Buildkite): add Pkg, Artifacts, and LazyArtifacts to the list of "network-related stdlibs" that we test in a separate Buildkite job -->
- [x] #42954 <!-- CI (GHA, Buildbot): temporarily, don't create the `linuxaarch64` Buildbot status -->
- [x] #42953 <!-- CI (Buildkite): increase the default timeouts -->
- [x] #42976 <!-- CI (Buildkite): Fix the Buildkite once-daily scheduled job -->
- [x] #42979 <!-- CI (Buildkite): increase the timeouts for the Buildkite jobs that run under `rr` -->
- [x] #42985 <!-- CI (GHA, Buildbot): Update the list of commit statuses created by the "Create Buildbot Statuses" workflow -->
- [x] #42983 <!-- CI (Buildkite): fix another bug in the once-daily scheduled Buildkite job -->
- [x] #42994 <!-- CI (Buildkite): increase the timeout of the code coverage job -->
- [x] #42995 <!-- CI (Buildkite): use a `TMPDIR` that is backed by real storage -->
</details>

Need manual backport:
- [ ] #42112 <!-- inference: bail from const-prop if const-prop fails -->
- [ ] #42170 <!-- coverage: ensure topline is recorded during inlining -->
- [ ] #42474 <!-- External stdlibs:  Move `*_URL` stdlib definitions into `.version` files -->
- [ ] #42906 <!-- External stdlibs: stop using the unauthenticated `git://` protocol in the external stdlib URLs -->
- [ ] #42907 <!-- Remove some other uses of the unauthenticated `git://` protocol in Git URLs -->
- [ ] #42904 <!-- Running `make testall` should run all of the tests -->
- [ ] #42854 <!-- Timer: handle timeout correctly -->

Contains multiple commits, manual intervention needed:
- [ ] #42172 <!-- fix collect on stateful iterators -->
- [ ] #42837 <!-- fixed Float16 from Float64 and BigFloat -->

Non-merged PRs with backport label:
- [ ] #42918 <!-- disallow unbalanced bidirectional formatting in strings and comments -->
- [ ] #42736 <!-- Fix `@simd` for non 1 step CartesianPartition -->
- [ ] #42715 <!-- add a missing `transpose` in `LinearAlgebra.copy_transpose!` to handle matmul of isbits array-elements with non-identity transpose -->
- [ ] #42495 <!-- CI (Buildkite): upload musl64 nightly binaries to S3 -->
- [ ] #42403 <!-- CI (Buildkite): on pull request builds, build the merge commit (e.g. `refs/pull/1234/merge`) -->
- [ ] #42311 <!-- Update mbedtls to final 2.x release -->
- [ ] #41228 <!-- fix some issues with equality of factorizations -->
- [ ] #41041 <!-- fix command literals with trailing backslashes -->
- [ ] #40820 <!-- Fix log message id from at-deprecate to be a Symbol. -->

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Why isn't #41707 showing up in the list?

**Comment by DilumAluthge** [comment]
> I don't know if there is a way to get all PRs with a certain label.

Hmmm. Yeah, the GitHub API docs don't mention any such functionality.

**Comment by DilumAluthge** [comment]
> I can adjust the date or include it manually.

Yeah, set the date to something like July 20, 2021. That should be sufficient to include #41707. If for some reason #41707 doesn't backport automatically, we can set the date even earlier to look for PRs on which #41707 depended.

**Comment by DilumAluthge** [comment]
> I don't know if there is a way to get all PRs with a certain label.

Maybe using the search API? Here's an example from their docs:
```
q=windows+label:bug+language:python+state:open&sort=created&order=asc
```


https://docs.github.com/en/rest/reference/search#search-issues-and-pull-requests

**Comment by vchuravy** [comment]
Ah sorry I did #42564 against the `release-1.6` branch instead of `backports-release-1.6`, causing these conflicts.

**Comment by KristofferC** [comment]
Oops.

**Comment by vchuravy** [comment]
> Oops. Revert and push it here?

Done.

**Comment by DilumAluthge** [comment]
The Buildkite tests are failing because #42533 has not yet been backported.

**Comment by jeremiahpslewis** [comment]
Hi! (Not entirely sure if this is the right place to ask this question, please let me know.) Would it make sense for https://github.com/JuliaLang/julia/pull/39769, e.g. GMP 6.2.0 -> 6.2.1 to be added to the 1.6 backports?

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL && !("scalar") , vs=":release-1.6")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/42147#issuecomment-966325410) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0856ad3_vs_1a92e56/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42147#issuecomment-966231711) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/1a719fb_vs_1a92e56/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ADI", "AlgamesDriving", "AlgorithmsCollection", "ArrayLayouts", "BLASBenchmarksCPU", "BayesianQuadrature", "BlockArrays", "BytePairEncoding", "ClassicalOrthogonalPolynomials", "ControlSystemIdentification", "CorrelationFunctions", "Cropbox", "DIVAnd", "DataDeps", "DecisionTree", "DynamicalSystemsBase", "EmailScraper", "FSInteraction", "FilesystemDatastructures", "FlashWeave", "GigaSOM", "Graph500", "InfiniteLinearAlgebra", "KrigingEstimators", "LazyArrays", "MCIntegration", "MarketData", "MiniLoggers", "NumericalAlgorithms", "Onda", "PackageAnalyzer", "ParquetFiles", "PastaQ", "QuantumESPRESSOExpress", "QuasiArrays", "RRTMGP", "Reactive", "RoME", "SortMark", "SyntheticDatasets", "TensorKit", "Turing", "VoronoiGraph", "YAXArrayBase"], vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ADI", "AlgamesDriving", "AlgorithmsCollection", "ArrayLayouts", "BLASBenchmarksCPU", "BayesianQuadrature", "BlockArrays", "BytePairEncoding", "ClassicalOrthogonalPolynomials", "ControlSystemIdentification", "CorrelationFunctions", "Cropbox", "DIVAnd", "DataDeps", "DecisionTree", "DynamicalSystemsBase", "EmailScraper", "FSInteraction", "FilesystemDatastructures", "FlashWeave", "GigaSOM", "Graph500", "InfiniteLinearAlgebra", "KrigingEstimators", "LazyArrays", "MCIntegration", "MarketData", "MiniLoggers", "NumericalAlgorithms", "Onda", "PackageAnalyzer", "ParquetFiles", "PastaQ", "QuantumESPRESSOExpress", "QuasiArrays", "RRTMGP", "Reactive", "RoME", "SortMark", "SyntheticDatasets", "TensorKit", "Turing", "VoronoiGraph", "YAXArrayBase"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42147#issuecomment-966925343) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/1a719fb_vs_1a92e56/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42147#issuecomment-967073766) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/94d6407_vs_1a92e56/report.md).

**Pull request merged**
