### PR TITLE
Fix compilation warning on aarch64-linux

### PR DESCRIPTION
**Pull request by giordano**
This fixes the warning:
```
/cache/build/default-aws-aarch64-ci-1-3/julialang/julia-master/src/stackwalk.c: In function 'jl_simulate_longjmp':
/cache/build/default-aws-aarch64-ci-1-3/julialang/julia-master/src/stackwalk.c:995:22: warning: initialization of 'mcontext_t *' {aka 'struct sigcontext *'} from incompatible pointer type 'struct unw_sigcontext *' [-Wincompatible-pointer-types]
  995 |     mcontext_t *mc = &c->uc_mcontext;
      |                      ^
```

This is the last remaining warning during compilation on aarch64-linux.

### CODE REVIEW

**Comment by giordano** [comment]
I was kind of hoping this could be related to #54839, but based on local testing that issue still remains after this change.  Addressing a compilation warning seems worthwhile anyway though.

**Comment by giordano** [comment]
BTW, [GCC 14 no longer allows implicitly casting all pointer types to all other pointer types](https://gcc.gnu.org/gcc-14/porting_to.html#incompatible-pointer-types), promoting the above warning to an error (ref: https://github.com/JuliaLang/julia/issues/54310#issuecomment-2086730066), so fixing this issue one way or another is rather important.

**Review by topolarity — APPROVED** [review]
I remember ARMv7 having a similar issue - is it really just AArch64?

**Comment by giordano** [comment]
> I remember ARMv7 having a similar issue - is it really just AArch64?

The [code referred to in the comments](https://github.com/libunwind/libunwind/blob/e63e024b72d35d4404018fde1a546fde976da5c5/include/libunwind-aarch64.h#L193-L205) in only in aarch64.  I don't have direct experience with compiling for armv{6,7}l, so I don't know what are the warnings there.

Side note, I just noticed there's a redundant `defined(_OS_LINUX_)` guard in my code, I'll remove that.

**Comment by topolarity** [comment]
> > I remember ARMv7 having a similar issue - is it really just AArch64?
> 
> The [code referred to in the comments](https://github.com/libunwind/libunwind/blob/e63e024b72d35d4404018fde1a546fde976da5c5/include/libunwind-aarch64.h#L193-L205) in only in aarch64. 

Ah you're right - I was thinking about this piece: https://github.com/libunwind/libunwind/blob/e63e024b72d35d4404018fde1a546fde976da5c5/include/libunwind-arm.h#L261-L269

Orthogonal to this PR, in any case 🙂

**Pull request merged**
