### PR TITLE
fix doc for generator guards and add doctest

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by martinholters** [comment]
+1 for adding a doctest, although a guard that could not better be handled with an adjusted range expression might be more pedagogical. Not that I have a good idea, though...

**Comment by KristofferC** [comment]
Something that depends on the result of `f(x)` perhaps.

**Comment by KristofferC** [comment]
Anyone have a good instructive suggestion for when to use guards in generators?

**Comment by dpsanders** [comment]
I agree with @martinholters that if it can be written as a range, it should be, since that should be more efficient (right?).

A couple of simple examples where this is not the case are

```
(x for x in 1:10 if x != 3)  
(sqrt(x) for x in 1:10 if x%3 != 0)
```

**Comment by dpsanders** [comment]
Any particular reason for not using `collect` in the doctest?

**Comment by KristofferC** [comment]
Not really, just wanted to show you can easily loop over a range without forming the full vector.

**Comment by dpsanders** [comment]
Good point.

**Comment by dpsanders** [comment]
You could have one doctest with `collect` and one with a loop.

**Comment by KristofferC** [comment]
Good to go?

**Pull request merged**
