### PR TITLE
Loosen AbstractMatrix requirement in svds

### PR DESCRIPTION
**Pull request by andreasnoack**
See discussion in https://github.com/JuliaLang/julia/pull/21701

cc @Jutho

### CODE REVIEW

**Comment by Jutho** [comment]
Thanks for that. So if I understand correctly, all that is needed is to support `adjoint`, `eltype`, `size`, and of course, multiplication with a vector. Looks like something `LinearMap`s should be able to do.

**Comment by andreasnoack** [comment]
And of course multiplication with vector but I believe that LinearMaps should able to handle that as well 😛. Actually, I also had to add the multiplication method for matrix rhs and now I'm curious why. It shouldn't really be necessary. I'll check.

**Review by Sacha0 — APPROVED** [review]
Naively lgtm! :)

**Comment by andreasnoack** [comment]
Okay the reason that `*(::MyOp, ::Matrix)` is required is to construct the set of eigenvectors not produced by the eigenvalue problem and `*` doesn't fall back to a `mul!` method because it isn't an `AbstractMatrix`. I guess such fallbacks might be in place for `LinearMap`s so this is only necessary when you define an operator with no fallbacks defined through supertypes.

So this is ready. However, we might reorganize this code quite a bit and I've already filtered this directory in https://github.com/JuliaLinearAlgebra/Arpack.jl so let's wait with mergin until we know what we'll do with the ARPACK wrappers.

**Comment by andreasnoack** [comment]
Now tracked in https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/13

**Pull request closed without merging**
