### PR TITLE
Let's try mirroring OSX bottles on our own AWS server

### PR DESCRIPTION
**Pull request by staticfloat**
Let's go ahead and wait for Travis to OK this, just in case.

@tkelman surprisingly easy.

### CODE REVIEW

**Comment by tkelman** [comment]
Cool. What happens when upstream updates, and the formula doesn't match? We'll need to be really quick on https://github.com/staticfloat/julia-buildbot/issues/13, won't we?

**Comment by staticfloat** [comment]
Yeah.  The more I think about it, the more I want something a la coral cache.  Something like "cache.julialang.org" that auto-caches files from sf.net.  That shouldn't be too hard to write up.  Let's hold off on this for now, so I can see how hard that would be to do.

**Comment by staticfloat** [comment]
That seems to work pretty well.  [Super-simple source code](https://github.com/staticfloat/cache.julialang.org) to our own transparent caching redirector.  Essentially, if you ask it for a file it doesn't know about, it will forward you to sf.net and download it in the background, upload it to S3, and then redirect you to S3 next time.  Right now it's hardcoded to only look for Bottles, but we could conceivably use something similar to this for our Julia `deps/` mirroring, as well, by passing full URLs instead of just simple filenames.

@StefanKarpinski does this seem like something you are okay with us doing?  To summarize, we've been having troubles with Homebrew binary dependencies for Travis due to sourceforge.net flakiness.  We want to cache them on our S3 servers, so Tony and I came up with a method that redirects the requests to our S3 servers, but we don't want things to suddenly break when Homebrew changes a version and we haven't mirrored the latest version yet.  So I made [a little script](https://github.com/staticfloat/cache.julialang.org/blob/master/www/cache.py) that will automagically fetch new bottles when Travis asks for one it doesn't have yet, which is currently running on the MIT cloud at http://cache.e.ip.saba.us, but if you're okay with this, then I'll ask you to point something like `cache.julialang.org` at it, and I'll generate an SSL certificate for it.

**Comment by tkelman** [comment]
Will this do anything about cleaning obsolete versions? Or is that something you've been doing by hand?

**Comment by ViralBShah** [comment]
I think this is a great idea. Let's do it.

**Comment by staticfloat** [comment]
@tkelman there is the freshly updated [`cleanup_bottles.jl`](https://github.com/staticfloat/julia-buildbot/blob/master/commands/cleanup_bottles.jl) which parses version numbers and lets you delete things that have been superseded.  It's not the sharpest tool in the shed though.  For instance, I had a newer version of `suite-sparse-julia` uploaded because I was testing 4.4.1, and so when I ran it this time, I allowed it to delete `suite-sparse-julia` 4.2.1 which is the version actually being used by my tap, so I've had to rebuild those bottles.

**Comment by StefanKarpinski** [comment]
Agree – great idea. Thanks for doing it.

**Comment by tkelman** [comment]
Is this good to go, should we merge? sourceforge is down yet again so would be cool to see this in anger

**Comment by staticfloat** [comment]
I guess we can merge. I can tweak afterward. (Changing to
cache.julialang.org once that's in place, using SSL once that's in place,
etc...)

**Comment by tkelman** [comment]
I guess Stefan has to handle getting cache.julialang.org working? While you're at it, should add build.julialang.org to point to the buildbot.

**Comment by staticfloat** [comment]
We are currently reviewing our DNS situation so this won't happen for a
while yet, but its on the radar.

**Pull request merged**
