### PR TITLE
BUG: Period Accessor should support Array

### PR DESCRIPTION
**Pull request by sinhrks**
This PR makes Period Accessors work for Arrays as Field Accessors do.
#### Current master

```
Dates.Year([DateTime(2013), DateTime(2014)])
# ERROR: MethodError: Cannot `convert` an object of type Array{DateTime,1} to an object of type Base.Dates.Year
# This may have arisen from a call to the constructor Base.Dates.Year(...),
# since type constructors fall back to convert methods.
# Closest candidates are:
#   call{T}(::Type{T}, ::Any)
#   convert{T<:Base.Dates.Period}(::Type{T<:Base.Dates.Period}, ::Real)
#   convert(::Type{Base.Dates.Year}, ::Base.Dates.Month)
#   ...
#  in call at essentials.jl:58
#  in eval at ./boot.jl:264
```
#### This PR

```
Dates.Year([DateTime(2013), DateTime(2014)])
#2-element Array{Base.Dates.Year,1}:
#  2013 years
#  2014 years
```

### CODE REVIEW

**Comment by tkelman** [comment]
I like the number of tests here, but the implicit vectorization here is a bit fishy. A type constructor should return an object of that type. What's wrong with using `map` explicitly?

**Comment by sinhrks** [comment]
Thanks for the check. I've misregarded them to work as vectorized function like normal accessors reading the doc. Pls close if it doesn't meet the policy.

- https://julia-demo.readthedocs.org/en/stable/manual/dates.html#accessor-functions

**Comment by tkelman** [comment]
I could see an argument for the lowercase versions maybe accepting an array, but for example we don't allow `Int64([1.0, 2.0])`. I'm open to other opinions on this though.

**Comment by nalimilan** [comment]
Yeah, constructors shouldn't return a different type. This could be fixed by a concise vectorization syntax (https://github.com/JuliaLang/julia/issues/8450).

**Comment by quinnj** [comment]
@sinhrks, thanks for the PR!

This is a bit tricky because we currently have:
* `Year(x::TimeType) => Year`
* `year(x::TimeType) => Int`

So there's an argument that both should allow vectorization if either does.

Currently, we do support auto-vectorization for most `Dates` operations, I'm inclined to allow both these definitions until something more consistent/firm is decided in #8450. @sinhrks, could you update the PR to vectorize both lowercase accessors as well as proper-case constructors?

**Comment by tkelman** [comment]
My vote is for neither. Use map, or comprehensions.

**Comment by nalimilan** [comment]
Opening the door to constructors returning a different type really sounds like a bad idea...

**Comment by StefanKarpinski** [comment]
Agreed. We don't enforce this, but it seems really confusing.

**Comment by quinnj** [comment]
Fair enough. I think we push on #8450 then to get something more concise/convenient.

**Pull request closed without merging**
