### PR TITLE
Improve tempdir test to ensure filename generated on UNIX is valid

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
@StefanKarpinski fixes the problems and tests for the same thing based on our discussion

**Comment by musm** [comment]
unrelated Distributed test failure on MacOS

**Comment by musm** [comment]
merging later if no comments

**Comment by StefanKarpinski** [comment]
Yes, this seems like an improvement. Should hopefully make it possible to get https://github.com/JuliaLang/julia/pull/33593 to pass.

**Pull request merged**
