### PR TITLE
put back DelimitedFiles as a non-sysimage "stdlib"

### LINKED ISSUE #48161: Ship remove Stdlibs in 1.9+
The following script works on Julia 1.8.4

```julia
using DelimitedFiles
temp = tempname()
open(temp, "w") do io
    println(io, "1,2,3")
end
println(sum(readdlm(temp, ',', Int)))
```

Ideally it should work on all future Julia versions. In interactive use, once `DelimitedFiles.jl` is no longer a stdlib, the user will be prompted to install the package at the REPL. In package use, it should already be in the environment. As a scripts without a Project.toml, IIUC, the plan is to make this fail with `ERROR: ArgumentError: Package DelimitedFiles not found in current path.`.

An alternate proposal from @IanButterworth on slack is

> for scripts, if the package name cannot be resolved, and its in a special list known to Julia of names that used to be stdlibs, then auto-install it and carry on

Much like the interactive REPL prompt, but install & warn rather than prompt.

EDIT to clarify: This would be backed by downloading and loading DelimitedFiles with Pkg, not by packaging DelimitedFiles with Julia.

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/48161.

Goes together with https://github.com/JuliaLang/Pkg.jl/pull/3373.

### CODE REVIEW

**Comment by vchuravy** [comment]
You probably also want to list it in https://github.com/JuliaLang/julia/blob/master/contrib/cache_stdlibs.jl

**Comment by KristofferC** [comment]
I don't know what that file does but I added it to it :)

**Comment by vchuravy** [comment]
It creates a cachefile so that the user doesn't need to precompile DelimtedFiles from the stdlib.

**Comment by DilumAluthge** [comment]
Can you add the following checksums?

```
ERROR: The working directory is dirty.
--
  | Output of git status:
  | HEAD detached at 3186096a8eb
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  | deps/checksums/DelimitedFiles-db79c842f95f55b1f8d8037c0d3363ab21cd3b90.tar.gz/
  | stdlib/DelimitedFiles-db79c842f95f55b1f8d8037c0d3363ab21cd3b90/
  |  
  | nothing added to commit but untracked files present (use "git add" to track)
  | 🚨 Error: The command exited with status 1


```

**Comment by DilumAluthge** [comment]
Also, could we add a file `stdlib/not-stdlibs.txt` with contents:

```
DelimitedFiles
```

**Comment by KristofferC** [comment]
> Also, could we add a file stdlib/not-stdlibs.txt with contents:

I didn't really want to couple this PR with the exact way of specifying the mechanism of that. For example a `.txt` file feels strange.

**Review by vchuravy — APPROVED** [review]

**Comment by DilumAluthge** [comment]
> For example a `.txt` file feels strange.

We could have a line in `stdlib/Makefile` of the form:

```
PKG_DISREGARD = DelimitedFiles Foo Bar Baz
```

And then Pkg could look for that line?

**Comment by KristofferC** [comment]
Pkg would look in the `Makefile`? We don't ship that one do we?

**Comment by DilumAluthge** [comment]
> Pkg would look in the `Makefile`? We don't ship that one do we?

Oh whoops, you're right, Pkg can only use what's actually shipped in the final tarball.

**Comment by PallHaraldsson** [comment]
DelimitedFiles is mentioned in NEWS, or well now HISTORY. Is it outdated, and should be dropped there?

**Pull request merged**
