### PR TITLE
dump: ensure we generate the whole backedge graph

### LINKED ISSUE #45444: Segmentation fault in jl_collect_backedges
```
signal (11): Segmentation fault
in expression starting at none:0
jl_collect_backedges at /buildworker/worker/package_linux64/build/src/dump.c:1233 [inlined]
ijl_save_incremental at /buildworker/worker/package_linux64/build/src/dump.c:2682
jl_write_compiler_output at /buildworker/worker/package_linux64/build/src/precompile.c:65
ijl_atexit_hook at /buildworker/worker/package_linux64/build/src/init.c:204
jl_repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:711
main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:59
```
Seen in PkgEval in #45195 on both sides of the comparison.

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39a24eb_vs_5554676/PANDA.against.log

### PR DESCRIPTION
**Pull request by vtjnash**
The edge-restore algorithm here is pretty bad now, but this should hopefully fix #45444

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runtests(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46171#issuecomment-1195721566) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/05257f4_vs_9e22e56/report.html).

**Comment by timholy** [comment]
Does this need backporting to 1.8?

**Comment by Keno** [comment]
Should we be reverting this now that the underlying issue was tracked down to a different root cause?

**Comment by vtjnash** [comment]
If `jl_collect_backedges_to` went to find the edges for something in the hashmap and it was supposed to have edges but is found to be missing instead, that is likely a bug. That is what this PR fixes some of, and what #46375 doesn't fix.

**Pull request merged**
