### PR TITLE
Fix shell syntax in version_git.sh and remove warning.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]
LGTM, but would be good for Elliot to double-check.

**Comment by DilumAluthge** [comment]
In theory, we could look for the presence of the `CI` environment variable, and if that environment variable is present, we would print the warning (since, on CI, we expect that the `.buildkite` directory exists and is a Git repository).

**Comment by fredrikekre** [comment]
Who will read that warning though? Will CI even start if that directory doesn't exist?

**Comment by DilumAluthge** [comment]
Yeah that's a good point. You'd only see the warning if you checked the CI logs. But as you point out, if the `.buildkite` directory is missing, we expect that Buildkite CI will error.

**Comment by DilumAluthge** [comment]
It's also not really worth trying to stuff too much CI-specific stuff into this shell script in the first place. So I think just removing the warning is fine.

**Pull request merged**
