### PR TITLE
Fix out-of-tree build of docs, fix #29757.

### LINKED ISSUE #29757: `make docs` doesn't copy _build/html for out of tree builds
Running `make -C builddir docs` does not copy over `_build/html` to the `builddir` folder for out of tree builds but leaves them in the root  folder. I believe this may be causing  build errors when attempting to run `make -C builddir binary-dist` .    

Notes:
- Cross compile build for windows using Cygwin (I have not tested Ubuntu cross compiles or whether this also occurs in linux builds)

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by musm** [comment]
Great, thanks

**Comment by musm** [comment]
Hmm, I checked out this PR, and this is the output:

```
Building HTML documentation.
  Updating registry at `C:\Users\Mus\work\julia\doc\deps\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 !! Skipped doctesting.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory '/cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc'
make: Leaving directory '/cygdrive/c/Users/Mus/work/julia/build-win64-cyg'
```


yet no  `_build/html` directory exists in the path  '/cygdrive/c/Users/Mus/work/julia/build-win64-cyg'

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
It should be in `doc/_build/html/`. On an OOT build under Linux this PR works.

Can you check `/cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc/_build/html`?

**Comment by musm** [comment]
Yes it exists in that directory.

The (primary and related) issue is that an OOT `binary-dist` build fails since it searches the OOT directory for `_build/html`, which does not exist since it was not copied over during the build process.

Please see the error message below
```
# Copy documentation
cp -R -L /cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc/_build/html /cygdrive/c/Users/Mus/work/julia/build-win64-cyg/julia-2d28c88deb/share/doc/julia/
cp: cannot stat '/cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc/_build/html': No such file or directory
```

**Comment by vchuravy** [comment]
Wait this confuses me. After this PR you should have a directory `/cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc/_build/html` that contains the build documentation. So the `cp -R -L` command should succeed now. Since it looks exactly at that path.

>  is that an OOT binary-dist build fails since it searches the OOT directory for _build/html, which does not exist since it was not copied over during the build process.

Right it should be looking for `doc/_build/html`, which it seems to do?

**Comment by musm** [comment]
I think I have a fix inbound

**Comment by musm** [comment]
> Wait this confuses me. After this PR you should have a directory /cygdrive/c/Users/Mus/work/julia/build-win64-cyg/doc/_build/html that contains the build documentation. So the cp -R -L command should succeed now. Since it looks exactly at that path.

No `build-win64-cyg/doc/_build/html` does not exist only `/doc/_build/html` (root directory) exists, which is why the `cp -R -L ` command fails

**Comment by musm** [comment]
@fredrikekre  do you need to also update `make.jl` in the `docs` folder to point to the correct `builddir`?

**Comment by musm** [comment]
@fredrikekre  BTW I confirmed that `make.jl` does pick up the correct `buildroot` directory, yet the `make.jl` script fails to copy over the files

**Comment by fredrikekre** [comment]
We apparently get the same error on AV with this PR:
```
# Copy documentation
cp -R -L /cygdrive/c/projects/julia/doc/_build/html /cygdrive/c/projects/julia/julia-19a0f204e8/share/doc/julia/
cp: cannot stat '/cygdrive/c/projects/julia/doc/_build/html': No such file or directory
make: *** [Makefile:333: install] Error 1
```

**Comment by fredrikekre** [comment]
So from the output:
```
[00:20:58] buildroot = "/cygdrive/c/projects/julia"

[...]

[00:22:49] readdir(joinpath(buildroot, "doc", "_build")) = ["html"] # after doc-build

[...]

[00:33:40] # Copy documentation
[00:33:40] cp -R -L /cygdrive/c/projects/julia/doc/_build/html /cygdrive/c/projects/julia/julia-55396b96b7/share/doc/julia/
[00:33:40] cp: cannot stat '/cygdrive/c/projects/julia/doc/_build/html': No such file or directory
```
so is the directory getting wiped somewhere?

**Comment by musm** [comment]
@fredrikekre I ran a clean build and monitored the output of the `julia/builddir/doc` folder and I saw no folders not file ever created.

**Comment by mortenpi** [comment]
I was able to reproduce this.

The problem is that `BUILDROOT` is an absolute path (e.g. `BUILDROOT=/home/user/julia/build-win32`). In Cygwin the root (`/`), from the Windows file system point of view, is something like `C:\cygwin64\`, and the `BUILDROOT` actually points to `C:\cygwin64\home\user\julia\build-win32`.

However, Julia interprets `BUILDROOT` to be an absolute path relative to `C:\`, i.e. `C:\home\user\julia\build-win32`, and that's where the docs get written. I suspect this is because it is a cross-compilation build -- Julia doesn't know it's being run in Cygwin? It's using the Windows, not Cygwin filesystem APIs?

So @musm, you should also have a `C:\home\` directory, and that's where the docs went :laughing: 

Don't know how to fix this though. Should we modify the `BUILDROOT` we pass to `julia` when cross-compiling?

**Comment by musm** [comment]
> However, Julia interprets BUILDROOT to be an absolute path relative to C:\, i.e. C:\home\user\julia\build-win32, and that's where the docs get written. I suspect this is because it is a cross-compilation build -- Julia doesn't know it's being run in Cygwin? It's using the Windows, not Cygwin filesystem APIs?

This is the crux of the problem

**Comment by musm** [comment]
I updated my PR https://github.com/JuliaLang/julia/pull/29764 with a different fix

**Review by mortenpi — APPROVED** [review]
I think the keyword approach is the best here.

**Comment by musm** [comment]
Much better with now without the env variable. Can we get this backported since it prevents Cygwin builds for OOT builds?

**Pull request merged**
