### PR TITLE
temporarily disable Downloads.jl tests

### LINKED ISSUE #37947: FileWatching tests are broken on CI
For example https://build.julialang.org/#/builders/79/builds/4606/steps/5/logs/stdio

```
Error in testset FileWatching:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.6/FileWatching/test/runtests.jl:27
  Expression: 0 <= Int(Base.cconvert(Ctype, (pipe_fds[i])[2])) <= FDmax
   Evaluated: 0 <= 125 <= 80
Error in testset FileWatching:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.6/FileWatching/test/runtests.jl:26
  Expression: 0 <= Int(Base.cconvert(Ctype, (pipe_fds[i])[1])) <= FDmax
   Evaluated: 0 <= 126 <= 80
Error in testset FileWatching:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.6/FileWatching/test/runtests.jl:27
  Expression: 0 <= Int(Base.cconvert(Ctype, (pipe_fds[i])[2])) <= FDmax
   Evaluated: 0 <= 127 <= 80
```

### PR DESCRIPTION
**Pull request by KristofferC**
Might fix https://github.com/JuliaLang/julia/issues/37947. If that error goes away, I will merge this quickly.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Would it be possible to instead identify just the Downloads.jl tests that are problematic, and disable those?

**Comment by DilumAluthge** [comment]
Sounds like that is easier said than done, though.... 

I guess maybe disable all the Downloads.jl tests, and then start re-enabling the ones that pass at least?

**Comment by KristofferC** [comment]
I know which one causes the fail but:

1. The code for Downloads.jl is not in this repo.
2. It's just temporary, there isn't really any point to be surgical. Speed is more important.

**Comment by KristofferC** [comment]
Places where this used to fail passes now so merging.

**Pull request merged**
