### PR TITLE
Fixes for bitcast bugs with LLVM 17 / opaque pointers

### LINKED ISSUE #54549: LLVMPtr's address space annotation is lost with opaque pointers
MWE:

```julia
using InteractiveUtils
using Core: LLVMPtr

@inline passthrough(ptr::LLVMPtr{T,A}) where {T,A} = Base.llvmcall(("""
        define ptr addrspace(1) @entry(ptr addrspace(1) %0) #0 {
        entry:
            ret ptr addrspace(1) %0
        }

        attributes #0 = { alwaysinline }""", "entry"),
    LLVMPtr{T,A}, Tuple{LLVMPtr{T,A}}, ptr)

f(gws) = passthrough(reinterpret(LLVMPtr{UInt32,1}, gws))

code_llvm(f, Tuple{Ptr{Nothing}})
```

```
julia-debug: /workspace/srcdir/llvm-project/llvm/lib/IR/Instructions.cpp:652: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

Looks like we're somehow losing the address space property of the LLVMPtr when its bitcasted:

```
(rr) call jl_(ctx.code )
Array{Any, 1}(dims=(4,), mem=Memory{Any}(4, 0x7493e013fea0)[
  Expr(:call, Base.bitcast, Core.LLVMPtr{UInt32, 1}, Core.Argument(n=2)),
  Expr(:call, Core.tuple, "define ptr addrspace(1) @entry(ptr addrspace(1) %0) #0 {\nentry:\n    ret ptr addrspace(1) %0\n}\n\nattributes #0 = { alwaysinline }", "entry"),
  Expr(:call, Base.llvmcall, SSAValue(2), Core.LLVMPtr{UInt32, 1}, Tuple{Core.LLVMPtr{UInt32, 1}}, SSAValue(1)),
  Core.ReturnNode(val=SSAValue(3))])

(rr)
837	        jl_value_t *argi = args[4 + i];
(rr) call jl_(argi)
SSAValue(1)

(rr)
838	        jl_cgval_t arg = emit_expr(ctx, argi);
(rr) call arg.V->dump()
ptr %"gws::Ptr"
```

IR looks fine:

```
13 1 ─ %1 = Core.bitcast(LLVMPtr{UInt32, 1}, _2)::LLVMPtr{UInt32, 1}
   │   %2 = Core.tuple("define ptr addrspace(1) @entry(ptr addrspace(1) %0) #0 {\nentry:\n    ret ptr addrspace(1) %0\n}\n\nattributes #0 = { alwaysinline }", "entry")::Tuple{String, String}
   │   %3 = Base.llvmcall(%2, LLVMPtr{UInt32, 1}, Tuple{LLVMPtr{UInt32, 1}}, %1)::LLVMPtr{UInt32, 1}
   └──      return %3                                          ││
    => LLVMPtr{UInt32, 1}
```

### PR DESCRIPTION
**Pull request by maleadt**
Fixes an assertion encountered in the wild. I still think we shouldn't be adding checks like that all over the place and just have `setName` bail out, as it's hard to predict when operations will be folded.

Also fixes https://github.com/JuliaLang/julia/issues/54549; we were using `emit_bitcast` which preserves the _source_ address space, while `bitcast(LLVMPtr{T,A}, ptr)` should most definitely respect the _target_ address space.

The added test covers both issues.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by gbaraldi** [comment]
I believe this may be https://github.com/JuliaLang/julia/issues/57245, or at least related

**Comment by KristofferC** [comment]
@gbaraldi, The test here doesn't seem to work on 1.10:

```
<string>:1:8: warning: ptr type is only supported in -opaque-pointers mode
define ptr addrspace(1) @entry(ptr addrspace(1) %0) #0 {
```

**Comment by oscardssmith** [comment]
is this applicable to 1.10? I didn't think we used opaque pointers until 1.11

**Comment by gbaraldi** [comment]
Yes, this is applicable but the test isn't

**Pull request merged**
