### PR TITLE
Fixed whitespace and two typos

### PR DESCRIPTION
**Pull request by mauro3**
https://github.com/JuliaLang/julia/pull/12146

### CODE REVIEW

**Comment by simonbyrne** [comment]
Thanks for being so quick!

**Comment by mauro3** [comment]
Thanks for being so lenient!

**Comment by simonbyrne** [comment]
I've lost count of the number of times I've screwed up the whitespace check. I finally added a pre-commit hook to check for it (in fact, the sample one `.git/hooks/pre-commit.sample` does this)

**Comment by mauro3** [comment]
I added a pre-save hook to emacs.  But that was a month or so after I did that scope-doc overhaul...  I'll look into the git-hook too, thanks.

**Pull request merged**
