### PR TITLE
A[c|t]_mul_B[!] specializations for SparseMatrixCSC-StridedVecOrMat, less generalized linear indexing and meta-fu

### PR DESCRIPTION
**Pull request by Sacha0**
Towards fixing some generalized linear indexing deprecation warnings in #20040, this pull request rewrites the `A[c|t]_mul_B[!]` specializations for `SparseMatrixCSC`-`StridedVecOrMat` combinations, leveraging multiple dispatch and higher order functions to remove generalized linear indexing and meta-fu. cc @mbauman. Best!

### CODE REVIEW

**Comment by andreasnoack** [comment]
Could you explain the connection to generalized linear indexing and why it fixes the issue?

**Comment by Sacha0** [comment]
> Could you explain the connection to generalized linear indexing and why it fixes the issue?

The existing implementation uses generalized linear indexing (when indexing `B` and `C`), whereas the implementation in this PR does not (by providing separate kernels for `StridedVector` `B`/`C` and `StridedMatrix` `B`/`C`). Removing these uses of generalized linear indexing fixes some depwarns in #20040, e.g. those appearing in the `sparse/spqr` tests. Does that clarify? Best!

**Comment by andreasnoack** [comment]
So the problem is indexing a vector with two indices? I thought that generalized linear indexing was about indexing an `N` dimensional array with `n` indices where `1 < n < N`. The old behavior (which I though we called trailing singleton dimension) is pretty convenient in this case where it allows us to avoid duplication of the kernel.

**Comment by Sacha0** [comment]
> So the problem is indexing a vector with two indices? I thought that generalized linear indexing was about indexing an N dimensional array with n indices where 1 < n < N. The old behavior (which I though we called trailing singleton dimension) is pretty convenient in this case where it allows us to avoid duplication of the kernel.

`@andreasnoack`, please see #20040. Best!

**Pull request merged**
