### PR TITLE
release-1.6: Backports for 1.6.6

### LINKED ISSUE #42245: jl_setjmp is not exported on Windows, making it impossible to use the JL_TRY/JL_CATCH macros when embedding Julia
On Windows `jl_setjmp` is implemented in assembly [here (64 bit)](https://github.com/JuliaLang/julia/blob/master/src/support/_setjmp.win64.S) and [here (32 bit)](https://github.com/JuliaLang/julia/blob/master/src/support/_setjmp.win32.S). On Linux, `jl_setjmp` is an "alias" to `sigsetjmp`. The result is that if the `JL_TRY`/`JL_CATCH` macros are used when embedding Julia on Linux they work successfully because `suigsetjmp` can be found in libc, but when embedding on Windows instead it fails because `jl_setjmp` is not exported.

The easiest way to reproduce this error is to wrap the call to `jl_eval_string` in the example found [here](https://docs.julialang.org/en/v1/manual/embedding/) with `JL_TRY`/`JL_CATCH`. I've used MINGW to compile the code, the instructions for MSVC didn't work but I haven't investigated this further because I have very little experience with developing on Windows and Visual Studio.

### LINKED ISSUE #43921: Product iterator is not zipped properly
When zipping with a product iterator with no arguments (which produces only one output, the empty tuple), it seems the check for zip completion does not handle this case:
```
julia> for (z,) in zip(Iterators.product())
       @show z
       end
z = ()
ERROR: ArgumentError: tuple must be non-empty
Stacktrace:
 [1] first(#unused#::Tuple{})
   @ Base ./tuple.jl:140
 [2] _pisdone
   @ ./iterators.jl:1005 [inlined]
 [3] isdone
   @ ./iterators.jl:1012 [inlined]
 [4] _zip_isdone(is::Tuple{Base.Iterators.ProductIterator{Tuple{}}}, ss::Tuple{Tuple{Bool}})
   @ Base.Iterators ./iterators.jl:379
 [5] _zip_iterate_all
   @ ./iterators.jl:348 [inlined]
 [6] iterate
   @ ./iterators.jl:341 [inlined]
 [7] top-level scope
   @ ./REPL[79]:2
```

`versioninfo()` output:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = vim
```
EDIT: `zip([()])` works fine though:
```
julia> for (z,) in zip([()])
       @show z
       end
z = ()

julia> 
```

### LINKED ISSUE #43960: wrong evaluation order for splatted args in `ref` expression
This was pointed out on slack:

```julia
julia> Meta.@lower a[f(x), g(y)...]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = g(y)
│   %2 = f(x)
│   %3 = Core.tuple(a, %2)
│   %4 = Core._apply_iterate(Base.iterate, Base.getindex, %3, %1)
└──      return %4
))))
```

I don't see any reason why `g(y)` should be evaluated before `f(x)`, so this can probably be considered a bug in lowering.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #41000 
- [x] #43361 
- [x] #43570 
- [x] #43579 
- [x] #43647 
- [x] #43612 
- [x] #43761 
- [x] #43426 
- [x] #43884 
- [x] #43962 
- [x] #44004 
- [x] #44024 
- [x] #43571 
- [x] #44134 
- [x] #44192 
- [x] #44196 
- [x] #44194 
- [x] #44265 
- [x] #44262 
- [x] #42736 
- [x] #43291 
- [x] #44453 
- [x] #44464 
- [x] #43575 
- [x] #44212 
- [x] #44078 
- [x] #43276 
- [x] #43823 
- [x] #42358 
- [x] #43678 
- [x] #43993 
- [x] #43856 
- [x] #42906 
- [x] #42904 
- [x] #42907 

Need manual backport:
- [ ] #42112 
- [ ] #42170 
- [ ] #42267 

Contains multiple commits, manual intervention needed:
- [ ] #42172 
- [ ] #42837 
- [ ] #43168 
- [ ] #43701 
- [ ] #44252 
- [ ] #44476 

Non-merged PRs with backport label:
- [ ] #43947 
- [ ] #42715 
- [ ] #42311 
- [ ] #41228 
- [ ] #41041

### CODE REVIEW

**Comment by t-bltg** [comment]
@KristofferC, should https://github.com/JuliaLang/julia/pull/43787 be backported to `1.6.6` and also `1.7.2` ?

**Comment by KristofferC** [comment]
Not sure, could be argued it is a bug fix but it isn't really clear to me at least.

**Comment by t-bltg** [comment]
Thanks, I'd say it's a bug fix but since it's a long standing one with visual changes, maybe @JeffBezanson can make that call.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1068124364) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/79388bf_vs_7be0dcd/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1069010919):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/73c0033_vs_515a242/report.md
seems...not great?

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1069117523):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/73c0033_vs_7be0dcd/report.md
seems good

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1069010983) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c7daef8_vs_515a242/report.html).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1069117817) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c7daef8_vs_7be0dcd/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ARules", "AbstractGPs", "AbstractOperators", "Accessors", "AcousticFeatures", "AirSeaFluxes", "Arblib", "AtomicLevels", "BigBed", "BlueNoise", "BranchAndBound", "COBREXA", "CalculusWithJulia", "CartesianCutCell", "CitableAnnotations", "ClassicalCiphers", "CodeCosts", "ColPack", "CommutativeRings", "ComoniconBuilder", "ConceptnetNumberbatch", "Concorde", "ConservationLawsParticles", "ContactImplicitMPC", "CropRootBox", "CyclotomicNumbers", "Difmap", "DimensionalData", "DisjointCliqueCover", "EBayes", "EFIT", "EclipsingBinaryStars", "EconPDEs", "EfficientGlobalOptimization", "EllipsisNotation", "ExaPF", "ExaTron", "FiniteDiff", "FluxDiffUtils", "GEMPIC", "GadgetUnits", "GaussianMixtureAlignment", "GeneratorArrays", "GeoParams", "GeometricFlux", "GoogleDrive", "Graph500", "GraphMLDatasets", "HTTP", "HeartBeats", "Highlights", "HyperDualNumbers", "ISAData", "ITensorVisualizationBase", "IbnrClaims", "Infiltrator", "InteractionWeightedDIDs", "InterferometricModels", "InterpolatedPDFs", "JLD2", "KalmanFilters", "KeywordCalls", "LightPropagation", "LinRegOutliers", "LiterateTest", "Luxor", "MCMCDiagnosticTools", "MPIFiles", "MPITestImages", "Mamba", "Markovify", "Merly", "MeshViz", "Metrics", "MicroMamba", "MultiCDF", "NDTools", "NLPModels", "NMFk", "NPFinancial", "NaiveNASflux", "NestedSamplers", "NestedTuples", "NiLangCore", "OAuth", "OceanTurb", "OnlineStats", "OptimalTransport", "ParameterSpacePartitions", "Pfam", "PhyloNetworks", "PlasmaEquilibriumToolkit", "Plotly", "PlutoStaticHTML", "PlutoUI", "PolaronPathIntegrals", "PooksoftAlphaVantageDataStore", "PorousMaterials", "PowerModels", "QuantumESPRESSOExpress", "QuantumInformation", "RCall", "RadiiPolynomial", "RandomLinearAlgebraSolvers", "RandomizedNMF", "RectiGrids", "RemoteFiles", "Replay", "ReportMetrics", "Ripserer", "Run", "SDMX", "SFrontiers", "SMCExamples", "SampleChains", "Scheduling", "ScrapeSEC", "ShellModel", "SimpleCarModels", "SimpleChains", "SimpleLexica", "Simplices", "Smoothers", "Smoothing", "SpatialEcology", "StaticPolynomials", "Strapping", "SymmetryReduceBZ", "SynthControl", "TableDistances", "TensorNetworkCodes", "TerminalClock", "TopOptMakie", "TopologyPreprocessing", "Traceur", "TreeverseAlgorithm", "TwoBit", "UnfoldMakie", "UnifiedPseudopotentialFormat", "UsingMerge", "VertexFinder", "WindowFunctions"], vs = ":master")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ADCME", "AeroAcoustics", "ArrayLayouts", "AssociativeArrays", "Batsrus", "BlockArrays", "CMAEvolutionStrategy", "Causal", "CondaPkg", "CrystallographyBase", "ExtendedDates", "GLMNet", "GaussianProcesses", "GcodeParser", "Hashpipe", "ITensorGaussianMPS", "ITensorVisualizationBase", "LatticeDiracOperators", "MIToS", "MRIgeneralizedBloch", "Mamba", "NaturalES", "NotebookToLaTeX", "NumericalAlgorithms", "OceanRobots", "PlanningDomains", "QXTns", "QXTools", "QuadEig", "RoME", "SalesForceBulkApi", "SocialSolver", "SortMark", "SpectralDistances", "StructuralIdentifiability", "SynchronicBallot", "SyntheticDatasets", "SyntheticNetworks", "TensorNetworkCodes", "TraitSimulation", "UCIData", "YAActL", "YaoQX", "ZigZagBoomerang"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1072369123) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c7daef8_vs_3da4aed/report.html).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1072370285) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c7daef8_vs_7be0dcd/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ArrayLayouts", "AssociativeArrays", "BlockArrays", "ExtendedDates", "GaussianProcesses", "ITensorGaussianMPS", "ITensorVisualizationBase", "Mamba", "QXTns", "QXTools", "TensorNetworkCodes", "YAActL", "YaoQX"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1072847241) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8c43f36_vs_7be0dcd/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AssociativeArrays", "ExtendedDates", "ITensorGaussianMPS", "ITensorVisualizationBase", "QXTns", "QXTools", "TensorNetworkCodes", "YaoQX"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43735#issuecomment-1072960808) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3c8241c_vs_7be0dcd/report.html).

**Comment by KristofferC** [comment]
The one remaining Pkg eval "failure" looks like a bug fix which is for some reason is tested on the previous behavior.

**Pull request merged**
