### PR TITLE
Adds documentation for @goto and @label. Fixes #13617, Fixes #7706

### LINKED ISSUE #7706: Document goto in manual
`@goto` and `@label` are mentioned in NEWS, but conspicuously absent in the Control Flow section of the manual.

### LINKED ISSUE #13617: Document how @goto and @label work
Consider this little snippet

``` jl
while true
    @goto stop
    error()
end
@label stop
```

When run in the REPL as is or from an `include()` call, Julia returns an error

```
ERROR: syntax: label "stop" referenced but not defined
```

Putting these lines in a `function` block results in the expected no-op behavior, since it introduces local scope.

However, wrapping these five lines in a `begin... end` block, however, _also_ allows this code to work, even though no new scope is introduced within this block.

It appears that the behavior of this code depends on whether it is being interpreted in one case or compiled in another case?

Discussed with @mbauman

P.S. `@goto` is also not documented in our manual, but that's a separate issue.

### PR DESCRIPTION
**Pull request by mronian**

### CODE REVIEW

**Comment by quinnj** [comment]
+1

**Comment by tkelman** [comment]
should we maybe have this a little further down the list?

**Comment by mronian** [comment]
How about after short-circuit evaluation?

**Comment by Ismael-VC** [comment]
> The ``@goto`` cannot be used to jump to a **top-level statement**. It gives a ``referenced but not defined`` error. 

Why is this? Using `begin` at the top-level should be the same as the top-level, because it doesn't introduce a scope, `let` makes sense because it does introduce a local scope, this is confusing.

To use ``@goto`` at the **top-level**, enclose the code in ``begin`` and ``end`` statements.

If this works, then it's not because of scopes, is it just because of the block node?

**Comment by yuyichao** [comment]
The more precise statement is that `goto` cannot jump to another toplevel expression.

**Comment by mronian** [comment]
It is mentioned in #13617 that this is by design.

**Comment by mronian** [comment]
@tkelman I've moved it to the end and modified the text based on the suggestions provided. Please review.

**Comment by mronian** [comment]
@tkelman Does this need more examples?

**Comment by ararslan** [comment]
Hey @mronian, sorry for the lack of progress and merging here; this seems to have fallen through the cracks, and has since been superseded by #23656. We really appreciate the contribution nonetheless!

**Pull request closed without merging**
