### PR TITLE
Remove jldoctest setup for permutedims

### PR DESCRIPTION
**Pull request by ErikQQY**
`setup = :(using LinearAlgebra)` break the docs in REPL, also we don't need `using LinearAlgebra` in the doctest(`transpose` already in Base)

image

### CODE REVIEW

**Comment by ErikQQY** [comment]
OK, this seems to only happen on MacOS🤔

**Comment by inkydragon** [comment]
You need to update REPL output too.

Without `using LinearAlgebra`, we have:
```jl
julia> transpose(X)
2×2 transpose(::Matrix{Matrix{Int64}}) with eltype LinearAlgebra.Transpose{Int64, Matrix{Int64}}:
 [1 3; 2 4]  [9 11; 10 12]
 [5 7; 6 8]  [13 15; 14 16]


julia> using LinearAlgebra

julia> transpose(X)
2×2 transpose(::Matrix{Matrix{Int64}}) with eltype Transpose{Int64, Matrix{Int64}}:
 [1 3; 2 4]  [9 11; 10 12]
 [5 7; 6 8]  [13 15; 14 16]
```
I guess it's to make the output cleaner.

**Comment by ErikQQY** [comment]
> You need to update REPL output too.

Fixed

**Comment by LilithHafner** [comment]
I'm not sure what this fixes; is help mode broken for this docstring on mac?

**Comment by ErikQQY** [comment]
Oh, this issue is related to OhMyREPL, I will make changes there

**Pull request closed without merging**
