### PR TITLE
add `Iterators.accumulate`

### PR DESCRIPTION
**Pull request by JeffBezanson**
I was surprised we didn't have this. Even IterTools.jl doesn't seem to have it. Nice to complete the set  with map and filter.

### CODE REVIEW

**Comment by ararslan** [comment]
> Nice to complete the set with map and filter.

I'm confused, there is no `Iterators.map`.

**Review by ararslan — APPROVED** [review]

**Comment by rfourquet** [comment]
> I'm confused, there is no Iterators.map.

It just has another name: `Base.Generator` ;-)

**Review by rfourquet — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Actually it might not be a bad idea to add `Iterators.map = Base.Generator` just for uniformity.

**Comment by ararslan** [comment]
Just realized that this needs a compat annotation in the docstring

**Pull request merged**
