### PR TITLE
Backports for 1.0.4

### LINKED ISSUE #29936: Precompilation causes tuple construction error at REPL
Here's the MWE. In package `Foo`:

```julia
module Foo

const global m = Val{nothing}()
const global h = Val{:hey}()

wab = [("a", m),
       ("b", h),]

end
```

At the REPL:

```julia
julia> using Foo; [("Plan", Foo.m), ("Plan", Foo.h),]
ERROR: TypeError: in arrayset, expected Tuple{String,Val}, got Tuple{String,Val{nothing}}
Stacktrace:
 [1] setindex! at ./array.jl:769 [inlined]
 [2] copyto!(::Array{Tuple{String,Val},1}, ::Tuple{Tuple{String,Val{nothing}},Tuple{String,Val{:hey}}}) at ./abstractarray.jl:649
 [3] vect(::Tuple{String,Val{nothing}}, ::Vararg{Any,N} where N) at ./array.jl:151
 [4] top-level scope at none:0
```

On Julia 1.0.1, Linux binary. FWIW, I encountered several segfaults on the way to this MWE.

**edit**: simplified example.

### LINKED ISSUE #29983: Uncommenting unused variable assignment (or other various things) gives different results
Using the code

```jl
using ForwardDiff: Dual
using StaticArrays

v = ((1.,2.), (2.,3.))

function f(x::Vector{T}) where {T}
    x1 = SVector((x[1],)) # comment this to get correct result
    la1 = SVector((x[1],))
    f1 = zero(SVector{1}) # can also initialize with zero(SVector{1, T}) to get correct result 
    for _ in v
        f1 += la1
        @show f1
    end
    return f1
end

x = [Dual(1.0,1.0)]
@show f(x)
```

gives the erroneous output:

```jl
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(1.0,1.0)]
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(1.0,1.0)]
f(x) = Dual{Nothing,Float64,1}[Dual{Nothing}(1.0,1.0)]
```

Now, we comment out the line `x1 = SVector((x[1],))`

```jl
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(1.0,1.0)]
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(2.0,2.0)]
f(x) = Dual{Nothing,Float64,1}[Dual{Nothing}(2.0,2.0)]
```

and get the correct result.

Executing the original code in the REPL also gives the correct result

```jl
julia> let
           x1 = SVector((x[1],))
           la1 = SVector((x[1],))
           f1 = zero(SVector{1})
           for _ in v
               f1 += la1
               @show f1
           end
           f1
       end
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(1.0,1.0)]
f1 = Dual{Nothing,Float64,1}[Dual{Nothing}(2.0,2.0)]
1-element SArray{Tuple{1},Dual{Nothing,Float64,1},1,1}:
 Dual{Nothing}(2.0,2.0)
```

If we initialize `f1` to be of type `T` we also get correct result.

My guess it is something with the type instability in combination with broadcasting in combination with optimization but not sure...

### LINKED ISSUE #30006: sparse matrix with non-Int64 index type slice assignment failure
```
julia> using SparseArrays

julia> a=SparseMatrixCSC{Float64, Int32}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int32} with 0 stored entries

julia> a[:,1]=[1,2,3]
ERROR: type Slice has no field stop
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] getindex at ./range.jl:610 [inlined]
 [3] setindex!(::SparseMatrixCSC{Float64,Int32}, ::Array{Int64,1}, ::Colon, ::Int64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/sparsematrix.jl:2656
 [4] top-level scope at none:0
```

The same code with Int64 in place of Int32 succeeds
```

julia> a=SparseMatrixCSC{Float64, Int64}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int64} with 0 stored entries

julia> a[:,1]=[1,2,3]
3-element Array{Int64,1}:
 1
 2
 3
```

### LINKED ISSUE #30394: Incorrectly Inferred Return type
From [Discourse](https://discourse.julialang.org/t/incorrectly-inferred-return-type/18668)

Example code:

```
abstract type AbstractFoo end

mutable struct FooBase <: AbstractFoo
  a::Int
  # no foo_inner: terminates any recursion
end


mutable struct Foo1 <: AbstractFoo
  foo_inner::FooBase

  function Foo1()
    return new(FooBase(1))
  end
end

mutable struct Foo2 <: AbstractFoo
  foo_inner::Foo1

  function Foo2()
    return new(Foo1())
  end
end


mutable struct Foo3 <: AbstractFoo
  foo_inner::Foo2

  function Foo3()
    return new(Foo2())
  end
end


mutable struct Foo4 <: AbstractFoo
  foo_inner::Foo3

  function Foo4()
    return new(Foo3())
  end
end



# T1 <: T2 implies T1 == T2 as long as all T1 and T2 are concrete
function getInnerFoo(foo::T1, ::Type{T2}) where {T2 <: AbstractFoo, T1 <: T2}
  return foo
end

function getInnerFoo(foo::T1, ::Type{T2}) where {T1 <: AbstractFoo, T2 <: AbstractFoo}
  return getInnerFoo(foo.foo_inner, T2)
end

obj = Foo4()

obj2 = getInnerFoo(obj, Foo2)
println("typeof(obj2) = ", typeof(obj2))
@code_warntype getInnerFoo(obj, Foo2)
```

On Julia 0.6.2, the output is:

```
typeof(obj2) = Foo2
Variables:
  #self# <optimized out>
  foo::Foo4
  #unused# <optimized out>

Body:
  begin 
      return foo::Foo4
  end::Foo4
Variables:
  #self# <optimized out>
  foo::Foo4
  #unused# <optimized out>

Body:
  begin 
      return (Main.getInnerFoo)((Core.getfield)(foo::Foo4, :foo_inner)::Foo3, $(Expr(:static_parameter, 2)))::Foo3
  end::Foo3
```

The `typeof` line shows `obj2` is of type `Foo2`, but `code_warntype` infers it to be `Foo3`.  Similar result on Julia 1.0.1.

### LINKED ISSUE #30643: In iterators.jl:1092 and 1095 Stateful{T,VS} is reversed to {VS,T}
https://github.com/JuliaLang/julia/blob/34f7a4a50458594e6d72793b4f371227e8e842e3/base/iterators.jl#L1092

e.g. Stateful(cycle(itr)) claims it has length.

### LINKED ISSUE #30679: StackOverflowError when creating RemoteChannels
I have noticed some strange behavior with RemoteChannel in 1.0.3, that did not occur for me in 1.0.2. I think I have identified a MWE. The following works:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 5)
```
However, if I import some module before the struct definition, the following happens:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> using JuMP

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
ERROR: StackOverflowError:
deserialize(::Distributed.ClusterSerializer{Sockets.TCPSocket}, ::Type{RemoteChannel{Channel{A}}}) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:310 (repeats 100 times)
Stacktrace:
 [1] #remotecall_fetch#149(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:379
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:371
 [3] #remotecall_fetch#152(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Int64, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406
 [4] remotecall_fetch at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406 [inlined]
 [5] RemoteChannel(::Function, ::Int64) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:108
 [6] top-level scope at none:0
```
The error repeats consistently after consecutive attempts of `RemoteChannel(()->Channel{A}(1), 2)`, but if I run some code snippet involving the `A` type on the second node I can suddenly create channels again:
```julia
julia> @fetchfrom 2 A()
A()

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 16)
```
The error does not occur after any model import. For example, `MacroTools`, `Statistics` or seemingly any standard library does not lead to this error. Other large modules that I have tried that does lead to the error are `Plots` and `Distributions`. I have not found any common denominator between model imports that cause this error. My version info:
```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### LINKED ISSUE #30792: Keyword arguments parametric types break matching
This works on Julia 1.0.3

```julia
julia> f(a::C) where {R <: Real, C <: Union{R, Complex{R}}} = println(R)
f (generic function with 1 method)

julia> f(Float64(3))
Float64

julia> f(Float32(3)+Float32(2)im)
Float32
```

but the following does not

```julia 
julia> g(a::C; b=R(1)) where {R <: Real, C <: Union{R, Complex{R}}} = println(R)
ERROR: UndefVarError: R not defined
Stacktrace:
 [1] top-level scope at none:0
```

Discussion here: https://discourse.julialang.org/t/type-matching-with-positional-vs-keyword-arguments/19854

### LINKED ISSUE #30911: deepcopy bug in UnionAll types
Possible bug in deepcopy
```JULIA
julia> x = Array{Float32}
Array{Float32,N} where N

julia> x.var == x.body.parameters[2]
true

julia> x.var
N

julia> y = deepcopy(x)
Array{Float32,N} where N

julia> y == Array{Float32}
true

julia> y = deepcopy(Array{Float32,N} where N)
Array{Float32,N} where N

julia> y == Array{Float32} # !!!
false

julia> y.var == y.body.parameters[2]
false

julia> y.var
N

julia> y.body.parameters[2]
N

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

### LINKED ISSUE #31758: Out of bounds write in sparse broadcast
Reduced from https://discourse.julialang.org/t/signal-11-segmentation-fault-11-with-differentialequations-jl/23264/:
```julia
y = sparsevec([2,7], [1., 2.], 10)
x1 = sparsevec(fill(1.0, 10))
x2 = sparsevec([2,7], [1., 2.], 10)
x3 = sparsevec(fill(1.0, 10))
f(x, y, z) = x == y == z == 0 ? 0.0 : NaN
bc = Broadcast.broadcasted(f, x1, x2, x3)

Broadcast.materialize!(y, bc)
```
where the last line causes a segfault (`BoundsError` with `--check-bounds=yes`). The problem is here: https://github.com/JuliaLang/julia/blob/c83e31265cf6e3b3d777847a653074dd5875c6d7/stdlib/SparseArrays/src/higherorderfns.jl#L390 where we fail to expand the storage since the calculation for needed storage is wrong, and returns `1` in this particular case. From Debugger:
```
1|debug> n
In _map_zeropres!(f, C, As) at /julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:372
 382  while activerow < rowsentinel
 383      vals, ks, rows = _fusedupdate_all(rowsentinel, activerow, rows, ks, stopks, As)
 384      Cx = f(vals...)
 385      if !_iszero(Cx)
>386          Ck > spaceC && (spaceC = expandstorage!(C, Ck + min(length(C), _sumnnzs(As...)) - (sum(ks) - N)))
 387          storedinds(C)[Ck] = activerow
 388          storedvals(C)[Ck] = Cx
 389          Ck += 1
 390      end

1|debug> w
1] Ck: 7
2] spaceC: 6
3] storedinds(C): [1, 2, 3, 4, 5, 6]
4] (Ck + min(length(C), _sumnnzs(As...))) - (sum(ks) - N): 1

1|debug> n
In _map_zeropres!(f, C, As) at /julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:372
 383  vals, ks, rows = _fusedupdate_all(rowsentinel, activerow, rows, ks, stopks, As)
 384  Cx = f(vals...)
 385  if !_iszero(Cx)
 386      Ck > spaceC && (spaceC = expandstorage!(C, Ck + min(length(C), _sumnnzs(As...)) - (sum(ks) - N)))
>387      storedinds(C)[Ck] = activerow
 388      storedvals(C)[Ck] = Cx
 389      Ck += 1
 390  end
 391  activerow = min(rows...)

1|debug> w
1] Ck: 7
2] spaceC: 1                # <-- What??
3] storedinds(C): [1, 2, 3, 4, 5, 6]
4] (Ck + min(length(C), _sumnnzs(As...))) - (sum(ks) - N): 1
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #30324 - Use `JL_AArch64_crc` instead of `HWCAP_CRC32`
- [x] #30315 - fix bug with max_values in union!
- [x] #30376 - Fix reinterpret for 0-dimensional arrays
- [x] #30369 - stacktrace: prevent OOB-error in sysimage lookup
- [x] #30405 - Fix #30006, getindex accessing fields that might not exist
- [x] #30396 - fix #30394, an unsoundness in ml_matches
- [x] #30319 - generalize sparse matrix slicing to integer types
- [x] #30425 - Add custom deserialize method for UmfpackLU to avoid memory leak
- [x] #30564 - fix `lambda-optimize-vars!` with complex assignment RHSs
- [x] #30576 - Avoid having a singular matrix in deserialization test for umfpack
- [x] #30598 - Fix use counts for mutable struct SROA
- [x] #30655 - SHA,tests: cleanup tempdir
- [x] #30754 - Handle :error and :invalid expressions gracefully in REPL helpmode
- [x] #30773 - update macOS icons to be less transparent
- [x] #30798 - fix #30792, static param constraints between positional and kw args
- [x] #30804 - fix `at-everywhere using` in Distributed stdlib
- [x] #30930 - fix #30911, bug in `deepcopy` of `UnionAll`
- [x] #31047 - fix #29936, precompile should not assume UnionAlls have stable addresses
- [x] #31041 - bump MPFR to 4.0.2
- [x] #31312 - allow chop to take an empty string
- [x] #30296 - Fix 29545: Implement unaliascopy for ReinterpretArray
- [x] #31586 - build: LDFLAGS needed for FreeBSD build
- [x] #30569 - Improve REPL completions
- [x] #31642 - Fix show_vector for long offset arrays with :limit=true
- [x] #31691 - Don't modify existing MDNodes in SIMDloop pass.
- [x] #30554 - llvm: fix target triple
- [x] #30599 - Use XCode 8.3 for macOS on Travis
- [x] #31745 - Upgrade libssh2 to v1.8.2
- [x] #31615 - fix parse(ComplexF64, "inf")
- [x] #31443 - minor fixes in multiplication with Diagonals
- [x] #31763 - fix #31758: out of bounds write in sparse broadcast
- [x] #31187 - Fix `-`, `conj`, and `conj!` for sparse matrices with invalid entries  in `nzval`
- [x] #31029 - Update Mozilla CA certificate store to latest (01-23-2019) for libgit2 SSL.
- [x] #31405 - inference: fix typeof-tfunc impl
- [x] #30880 - fix #30679, call correct method for `invoke` calls in `jl_invoke` fallback

Non-merged PRs with backport label:
- [ ] #31464 - Accept both Cvoid and Ptr{Void} return type in ccall(:memcpy)
- [ ] #31064 - Fix accidental recursion in jl_concrete_subtype
- [ ] #30431 - Build: fix output directory when specified with O=
- [ ] #30357 - workaround for F_DUPFD_CLOEXEC on Linux kernel <2.6.24 before it existed

### CODE REVIEW

**Comment by cdluminate** [comment]
May I ask when Julia 1.0.4 will be released? According to Debian's release scheme, I'd better upload 1.0.4 to Debian before March 2nd.

**Comment by KristofferC** [comment]
Bisecting suggests https://github.com/JuliaLang/julia/pull/30470 as the cause of the test failures. Dropping that PR and rerunning CI.

**Comment by StefanKarpinski** [comment]
> May I ask when Julia 1.0.4 will be released?

Seems likely to be out by then but it's not a guarantee.

**Comment by fredrikekre** [comment]
Looks pretty good, lets push this over the finish line and get 1.0.4 out!

- From `tester_win64`:
  ```
  Error in testset FileWatching:
  Test Failed at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.0\FileWatching\test\runtests.jl:388
    Expression: #= C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.0\FileWatching\test\runtests.jl:388 =# @elapsed(c = watch_folder(dir, timeout)) < 0.5
     Evaluated: 1.265155767 < 0.5
  ```

- `package_freebsd64` looks like it failed building gmp, if I am reading the logs correctly:
  ```
  gmake[1]: *** [/usr/home/julia/buildbot/worker/package_freebsd64/build/deps/gmp.mk:26: scratch/gmp-6.1.2/build-configured] Error 1
  ```

I restarted both :crossed_fingers:

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.0")`

**Comment by KristofferC** [comment]
How did AV start passing... Oh well, I'll take it.

**Comment by fredrikekre** [comment]
Looks like `tester_win64` passed the restart, `package_freebsd` still fails with the same error though, @staticfloat , @ararslan any ideas about that?

**Comment by vchuravy** [comment]
The error in FreeBSD is a configure error:
```
configure: error: could not find a working compiler, see config.log for details
....
gmake[1]: *** [/usr/home/julia/buildbot/worker/package_freebsd64/build/deps/gmp.mk:26: scratch/gmp-6.1.2/build-configured] Error 1
gmake[1]: *** Waiting for unfinished jobs....
```

**Comment by vchuravy** [comment]
FreeBSD failure is likely fixed by #31586

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30954#issuecomment-483595715) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/337d97656b84b9aa51b04191e33358cff4b29c41/421e5c8_vs_5b7e8d9/report.md). cc @ararslan

**Comment by KristofferC** [comment]
Freebsd and macOS buildbots fail at some built step.

**Comment by staticfloat** [comment]
FreeBSD bot needs https://github.com/JuliaLang/julia/pull/31586 backported.  MacOS bot is a race condition in OpenBLAS 0.3.2 buildsystem; I think we can ignore that because there's no trivial fix other than upgrading OpenBLAS to 0.3.5.  (It only occurs when you build OpenBLAS 0.3.2 on a multicore system with a hot ccache)

**Comment by KristofferC** [comment]
> FreeBSD bot needs #31586 backported

I already backported that. Did it not get picked up?

**Comment by staticfloat** [comment]
Oh, so you did.  Ah, yes.  This is one of those patches that applies itself into `$(SRCDIR)` so it muddles our persistent cache and doesn't get applied cleanly sometimes.  I'll try nuking that builder and running this again.

**Comment by staticfloat** [comment]
Frustratingly, logging in and manually running the same `make` command, it configures correctly.  The error it ran into was that a `configure` test segfaulted, which I don't quite understand.  One worrying thing is that it looks like our `$$ORIGIN` escaping isn't working properly, in the configure log I see things like `-Wl,3563ORIGIN`, which is potentially not harmless fun.

**Comment by ararslan** [comment]
PkgEval says the only regressions are CategoricalArrays and StaticNumbers. Logs: https://gist.github.com/ararslan/b47e8f93e19e46cfc8a7980fe53ef727. CategoricalArrays looks like it might be okay (@nalimilan, thoughts?), no idea about StaticNumbers. Looks weird, man.

**Comment by KristofferC** [comment]
CategoricalArrays explicitly test for the bugged behavior fixed by https://github.com/JuliaLang/julia/pull/31312.

**Comment by fredrikekre** [comment]
Reverting b399294f7fe012eb8fc395fd6ef7ecace5a7da28 fixes the tests for StaticNumbers (which are also broken on Julia 1.1 and master btw). StaticNumbers have an implementation of broadcast so might also be a problem there. Can you have a look @timholy ?

**Comment by nalimilan** [comment]
Thanks. CategoricalArrays fix at https://github.com/JuliaData/CategoricalArrays.jl/pull/187.

**Comment by KristofferC** [comment]
I reverted the commit that broke StaticNumbers. Need https://github.com/JuliaLang/julia/pull/30880 manually backported, another PkgEval run, then this is good to go.

**Comment by staticfloat** [comment]
The inference fix seems to have done something naughty:

```
Error in testset compiler/compiler:
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/compiler/compiler.jl:1343
  Expression: typeof_tfunc(Union{<:T, <:Real} where T <: Complex) == Union{Type{Complex{T}} where T <: Real, Type{<:Real}}
   Evaluated: Union{Type{#s55} where #s55<:Complex{T} where T<:Real, Type{#s55} where #s55<:Real} == Union{Type{Complex{T}} where T<:Real, Type{#s607} where #s607<:Real}
Error in testset compiler/compiler:
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/compiler/compiler.jl:1346
  Expression: Base.return_types(f_typeof_tfunc, (Union{<:T, Int} where T <: Complex,)) == Any[Union{Type{Int}, Type{Complex{T}} where T <: Real}]
   Evaluated: Any[Union{Type{Int64}, Type{#s55} where #s55<:Complex{T} where T<:Real}] == Any[Union{Type{Int64}, Type{Complex{T}} where T<:Real}]
```

**Comment by KristofferC** [comment]
I'll just drop it then.

**Comment by ararslan** [comment]
Still need to figure out the macOS and FreeBSD buildbot stuff. @staticfloat, any ideas?

**Comment by ararslan** [comment]
I can't reproduce the FreeBSD buildbot failure on FreeBSD 11.2 (which is what I think the buildbot is running) with or without `USE_BINARYBUILDER=0`.

**Comment by ViralBShah** [comment]
Do we know if this will produce working arm binaries?

**Comment by ararslan** [comment]
Let's find out:

ARMv7: https://build.julialang.org/#/buildrequests/43091
AArch64: https://build.julialang.org/#/builders/59/builds/2421

**Comment by ararslan** [comment]
Looks like we have some actual test problems on macOS and FreeBSD.

**Comment by KristofferC** [comment]
> Looks like we have some actual test problems on macOS and FreeBSD.

Hmm, macOS passes on Travis. Tests that fails have to do with LibGit2 which should not be touched by this PR. Not sure what to do.,

**Comment by ararslan** [comment]
If macOS passes on Travis, we're probably fine there. I'll run the FreeBSD build and tests locally and report back.

**Comment by ararslan** [comment]
No LibGit2 failures locally on FreeBSD on this branch for me. `errorshow` fails, which is odd, as it does not seem to happen on the buildbot.

**Comment by ararslan** [comment]
PkgEval results are in: No regressions. The only difference is CategoricalArrays, which is testing incorrect behavior, as stated previously.

Regarding the buildbot failures, I'm inclined to say we're okay there. I can't reproduce the failure on FreeBSD, and macOS passed on Travis. The issue is with the tests, which aren't run as part of the packaging build, so it won't pose a problem for making release binaries.

**Comment by KristofferC** [comment]
I agree.

**Comment by ararslan** [comment]
Also, the Nanosoldier regressions look like noise to me.

**Pull request merged**
