### PR TITLE
constrain the path argument of `include` functions to `AbstractString`

### PR DESCRIPTION
**Pull request by nsajko**
Each `Module` defined with `module` automatically gets an `include` function with two methods. Each of those two methods takes a file path as its last argument. Even though the path argument is unconstrained by dispatch, it's documented as constrained with `::AbstractString`:

https://docs.julialang.org/en/v1.11-dev/base/base/#include

Furthermore, I think that any invocation of `include` with a non-`AbstractString` path will necessarily throw a `MethodError` eventually. Thus this change should be harmless.

Adding the type constraint to the path argument is an improvement because any possible exception would be thrown earlier than before.

Apart from modules defined with `module`, the same issue is present with the anonymous modules created by `evalfile`, which is also addressed.

Sidenote: `evalfile` seems to be completely untested apart from the test added here.

### CODE REVIEW

**Comment by nsajko** [comment]
I suppose it would be good to throw a PkgEval at this:

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55466#issuecomment-2282862944) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/e549b7f_vs_2e1235e/report.html) is available.

**Comment by nsajko** [comment]
bump

**Comment by nsajko** [comment]
ping

**Review by fatteneder — COMMENTED** [review]
LGTM

**Comment by Keno** [comment]
This broke Cedar, which overrides include for custom non-Julia file types. Moreover, I don't see an easy way to get the old behavior back in the package. That said, it also doesn't seem that necessary to have a separate overloadable method in each module. Perhaps we should just define the curry in Base.
```
# In Core
struct IncludeInto
m::Module
end
(this::IncludeInto)(x::AbstractString) = Core.include(this.m, x)
```

**Pull request merged**
