### PR TITLE
CI (GHA): For the `Retry Failed Buildkite Jobs` workflow, remove the `labeled` trigger and add the workflow_dispatch` trigger

### PR DESCRIPTION
**Pull request by DilumAluthge**
### Before this PR

Before this PR, if a committer wants to retry the failed Buildkite jobs on a PR, they do the following steps:
1. Go to the relevant PR on GitHub.
2. Add the `Buildkite - retry failed jobs` label to the PR.

(If the PR in question already has the `Buildkite - retry failed jobs` label, you need to first remove the `Buildkite - retry failed jobs` label, and then re-add the `Buildkite - retry failed jobs` label.)

### After this PR

After this PR, if a committer wants to retry the failed Buildkite jobs, they do the following steps:
1. Go to this URL: https://github.com/JuliaLang/julia/actions/workflows/retry.yml
2. In the section that says "This workflow has a `workflow_dispatch` event trigger", click on the `Run workflow` button.
3. Under "Use workflow from", make sure that you have selected the `master` branch.
4. Under "The number of the pull request:", enter the number of the PR for which you want to retry the failed Buildkite jobs. E.g. `12345`
5. Click on the green `Run workflow` button.

## Pros and cons

Pros of this PR:
- GitHub will no longer create a "skipped" `Retry` commit status every time someone adds a label to a PR.

Cons of this PR:
- It takes more steps for a user to trigger a retry.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat and @KristofferC could you review this?

**Comment by staticfloat** [comment]
This seems too complicated to me; it's way more preferable to have a "skipped" status than to have to type in PR numbers.

**Comment by DilumAluthge** [comment]
How about a comment? A comment:
1. Can be made directly on the PR page. No need to go to another page.
2. The user never needs to e.g. manually type a PR number.
3. GitHub does not create "skipped" statuses for comments.

**Comment by DilumAluthge** [comment]
Instead of this PR, I'm going to work on a comment trigger.

**Pull request closed without merging**
