### PR TITLE
add capacity function to query the length of the underlying buffer of a Vector

### PR DESCRIPTION
**Pull request by abraunst**
See https://github.com/JuliaLang/julia/pull/30676#issuecomment-470527569

### CODE REVIEW

**Comment by musm** [comment]
Why does this have to be exported?

**Comment by abraunst** [comment]
> Why does this have to be exported?

Good point. Should I remove the export?

**Comment by JeffBezanson** [comment]
Thanks for moving this to a separate PR. Seems reasonable to me. I think `capacity` is a good name for this.

**Comment by StefanKarpinski** [comment]
Seems good to me. I can't see any reason not to have this. Sure, people mostly shouldn't care, but where's the harm in telling them if they want to know? However, it's unclear to me from the docs (and the implementation) whether this returns the capacity in elements or bytes. I.e. what are the units of the `maxsize` field of `jl_array_t` struct (I could figure this out but it needs to go in the doc anyway).

This could also probably use a test just to make sure it's actually callable. Maybe just generate vectors of various sizes and check that `capacity(a)` is an `Int` that is at least as large as the length?

**Comment by KristofferC** [comment]
> Seems good to me. I can't see any reason not to have this.

Features should imo be put in because they are needed. Any feature start with a negative score (code and docs have to be written maintained etc), and the usefulness of the feature has to add up so the score is positive. So, what do you do with the information after calling `capacity`? Why is it needed? This isn't even really testable because we have no guarantees about any operation keeping the capacity.

**Comment by JeffBezanson** [comment]
If we have this, it should use units of elements since that's what `sizehint!` and every other function uses.

**Comment by StefanKarpinski** [comment]
Are elements the unit that `jl_array_t->maxsize` represents? Or does it represent bytes?

**Comment by quinnj** [comment]
`a->maxsize` is the maximum _length_ of the array, so `length(A) - capacity(A)` would return how many more elements could be "push!"ed w/o needing to realloc/grow.

I agree that I'm somewhat hesitant on the utility here. Personally, I'd like to see most of the grow beginning/end code moved to julia itself, which are the type of operations where knowing the capacity is important. Is the use-case here trying to reimplement growing/shrinking in a different way? or optimized for a different use-case?

**Comment by Sacha0** [comment]
> Features should imo be put in because they are needed. Any feature start with a negative score (code and docs have to be written maintained etc), and the usefulness of the feature has to add up so the score is positive. So, what do you do with the information after calling `capacity`? Why is it needed? This isn't even really testable because we have no guarantees about any operation keeping the capacity.

👍. Embracing the perspective / position that all you lovely folks taught me about during this past week's triage, this functionality doesn't seem to dance quite right with that ethos. I can also see it proving a foot-gun escape hatch for dinosaurs like me attempting to subvert the memory management system in the name of performance :).

**Comment by KristofferC** [comment]
> I can also see it proving a foot-gun escape hatch for dinosaurs like me attempting to subvert the memory management system in the name of performance :).

This doesn't even help in the case like that because e.g. `push!` is not documented not to e.g. ever shrink the capacity. Or that a gc collection doesn't shrink it.

**Comment by abraunst** [comment]
> `length(A) - capacity(A)` 

this quantity has the wrong sign :-)

> I agree that I'm somewhat hesitant on the utility here. Personally, I'd like to see most of the grow beginning/end code moved to julia itself, which are the type of operations where knowing the capacity is important. Is the use-case here trying to reimplement growing/shrinking in a different way? or optimized for a different use-case?

This code was used in #30676. The sparse broadcast code in master produces intermediate sparse matrices with `length(x.nzval) > nnz(x)` because uses the array `length` as a proxy for the buffer length (which, addidtionally, isn't correct). PR #30676 essentially replaces calls to `resize!` with calls to `sizehint!` and `length` with `capacity`, which in the end I feel more faithful to the real intention. I was asked to produce a separate PR and so I did....

The question is if the sparse broadcast code can be replaced with something which tries to do less memory micromanaging in the end can only be answered with serious profiling in my opinion. And someone has to do the work, of course. :-)

**Comment by KristofferC** [comment]
>  I was asked to produce a separate PR and so I did....

I am not saying you did anything wrong by producing the PR, I am just discussing the content of the feature on its own merit.

As long as no other function include docs about how they interact with the capacity, this function cannot be used for anything useful . We could have some argument to `resize!` that enforces no shrinking of the capacity (which is the current status quo), but even with that, this feature is not needed.

**Comment by abraunst** [comment]
> > I was asked to produce a separate PR and so I did....
> 
> I am not saying you did anything wrong by producing the PR, I am just discussing the content of the feature on its own merit.

I didn't feel personally attacked. [OT: I perceive the general ambient as positive, constructive and overall friendly]. Note that I was not responding to you in particular, I was explaining the original reasons behind this PR.

> As long as no other function include docs about how they interact with the capacity, this function cannot be used for anything useful . We could have some argument to `resize!` that enforces no shrinking of the capacity (which is the current status quo), but even with that, this feature is not needed.

I generally agree. However, note that the current code in master is currently based on many of these assumptions, so the problem will be there in any case until it is fixed (either documenting the status quo, modifying the code or both). For the record, the *status quo* which renders `capacity` useful is that `sizehint!(x, n)` allocates a buffer of `length` `>= n` and that this buffer never shrinks (especially with `>=` and not `==`).

**Comment by KristofferC** [comment]
> For the record, the status quo which renders capacity useful is that sizehint!(x, n) allocates a buffer of length >= n and that this buffer never shrinks (especially with >= and not ==).

While it is true that the buffer never shrinks could you elaborate why that makes the `capacity` function needed? How would the return value influence the logic in your program.

**Comment by abraunst** [comment]
> > For the record, the status quo which renders capacity useful is that sizehint!(x, n) allocates a buffer of length >= n and that this buffer never shrinks (especially with >= and not ==).
> 
> While it is true that the buffer never shrinks could you elaborate why that makes the `capacity` function needed? How would the return value influence the logic in your program.

It makes the `capacity` function *useful*, not *needed*. 

The point is that the sparse broadcast code maintains a parallel memory allocation scheme when growing arrays (presumably for performance). But it does so with partial information, because on `resize!` (or `sizehint!` for that matters), you don't know what would be the buffer size. When it fills up up to the `length` of the `Vector`, it makes a new educated guess about the buffer size (and then `resize!`s the `Vector`) . Having access to `capacity` would allow: 
1) to use the accurate buffer size instead of the `Vector` length, which is just a lower bound (avoiding unnecessary reallocations)
2) eventually, if `push!` becomes fast enough, to never `resize!` the `Vector` and just `sizehint!` it.

As was suggested by others, maybe all this could be replaced by something that just relies on the memory subsystem guesses. 
I introduced the `capacity` function for 2), but then benchmarking evidenced that `push!` was a bit slower and I rolled back that part.  Some time passed, so I'm not 100% sure, but possibly one could just ignore 1) and have a version without the `capacity` function. I don't have the bandwidth to do this right away though...

**Comment by chethega** [comment]
Maybe the proper API function here would be `offset, trailing_space = resize_to_buffer!(v::Vector)`, which resizes the vector to match the underlying buffer size (without relocating any elements), zeros memory that needs to be zeroed (pointers, union flags), and returns the offset: `t = v[1]; len = length(v); offset, trailing_garbage = resize_to_buffer!(v); @assert t === v[1+offset]; @assert length(v) == len + offset + trailing_garbage`. 

That would alleviate issues about future changes to capacity management (e.g. garbage collection shrinking unused overallocation)

**Comment by StefanKarpinski** [comment]
@JeffBezanson and I both think it's harmless as long as people using this API don't have any baked in expectations about what the returned answer is aside from the fact that it's ≥ the length of the array.

**Comment by StefanKarpinski** [comment]
@vtjnash: points out that libc's have a similar API so it's probably an ok thing to expose.

**Comment by KristofferC** [comment]
If the guarantee of this function literally only is that it is larger than `length(x)` and we are able to later define `capacity(x) = length(x) + rand(1:5)` without breaking any code, then what is the point of the function? If this is not the case then what extra guarantee does it provide?

**Comment by martinholters** [comment]
The way I understood this is that there is no guarantee that a certain sequence of operations will result in `capacity` returning a specific (not even bounded in any way) value. But there is a guarantee that resizing to the capacity does not incur the cost of a memory allocation. That would make `capacity(x) = length(x)` a valid implementation, but not a very helpful one.

**Comment by StefanKarpinski** [comment]
Right, that's the contract of this function: the vector won't have to resize until it gets bigger than capacity. It's a performance guarantee, not a behavioral one. In terms of behavior, it could be implemented as `rand(length(x):typemax(Int))`.

**Comment by JeffBezanson** [comment]
I believe one of the only useful things you can do with this function is resize a vector to make all of its allocated capacity visible (i.e. `resize!(v, capacity(v))`). An operation that does just that would be much safer, because any operations on `v` in between calling `capacity` and using the number could invalidate it. Our array functions could change in the future with respect to whether they affect the capacity, and potentially even the garbage collector could change the allocated capacity of a vector. So exposing just `resize_to_capacity!` might be better.

**Comment by StefanKarpinski** [comment]
Yet another triage discussion of this. The main issue here is: what do we guarantee about this number that is returned? One of the valid uses for it that I could think of was to ask for `capacity` so that you know how much memory you can pass to a C library that it can safely use. However, that use case implicitly assumes that the memory cannot be shrunk or moved "behind your back" in the time between asking for the capacity and calling the C function. In particular, it means that the GC cannot shrink the capacity of a vector—which is a thing we might want to do. An alternative API for this that was mentioned was `resize_to_capacity!(a)` or `inflate!(a)`, after which `length` would give you the capacity. This would be guaranteed to be a cheap operation.

**Pull request closed without merging**
