### PR TITLE
Force optimization for PCRE2

### PR DESCRIPTION
**Pull request by staticfloat**
A better solution to https://github.com/JuliaLang/julia/issues/11668

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Yes, way better.

**Comment by staticfloat** [comment]
Unfortunately, this is not correct either.  This actually overrides the `CFLAGS` set by `configure` and by the environment.  Fixing incoming.

**Comment by tkelman** [comment]
Was gonna ask if maybe we should set these as arguments to configure (does pcre have something like `ADD_CFLAGS` ?), but merged instead. uups

**Comment by staticfloat** [comment]
No problem, I'm taking a pass through the entire `deps/Makefile` ensuring this is all consistent everywhere.  I believe the "traditional" way of doing this is very simple; `./configure CFLAGS="$(CFLAGS) $(PCRE_CFLAGS)"`

**Comment by staticfloat** [comment]
I'm ensuring that external environment variable-based flags get passed in to all the dependencies, but I'm scared of a few places [such as this](https://github.com/JuliaLang/julia/blob/01293bd283d190670d5078d7575c9bc339073c3d/deps/Makefile). Are we intentionally blanking out the `LDFLAGS` here, or is this something left over?  I'm digging through the `git` history right now, but it's not immediately clear to me....

**Comment by tkelman** [comment]
which of the nearly 2000 lines are you intending to refer to with that link?

**Comment by staticfloat** [comment]
I just actually laughed out loud.  Apparently, I lost the anchor after canonicalizing the URL somehow. [Line 372](https://github.com/JuliaLang/julia/blob/01293bd283d190670d5078d7575c9bc339073c3d/deps/Makefile#L372).

**Comment by staticfloat** [comment]
Aha, looks like it was @vtjnash that first introduced this line, back in de0cb826c9576c2c8fcce614f147c71fe6530228.  Jameson, could you explain the `LDFLAGS=""` part to me?  Are you intentionally not letting `LDFLAGS` leak through from the environment?

**Comment by staticfloat** [comment]
I'm especially confused, since nowadays, [we've got `LLVM_LDFLAGS`](https://github.com/JuliaLang/julia/blob/01293bd283d190670d5078d7575c9bc339073c3d/deps/Makefile#L438-L441) which [always has `LDFLAGS`](https://github.com/JuliaLang/julia/blob/01293bd283d190670d5078d7575c9bc339073c3d/deps/Makefile#L349) embedded within it.

**Comment by tkelman** [comment]
Heh. My fault for harping on everyone to always canonicalize, maybe it bugs out sometimes.

The default stack space on Windows is 1 MB but we need more to bootstrap inference IIRC, it might be that LLVM sets some default LDFLAGS that would conflict by trying to keep that set to the platform defaults, but that may not be true with 3.3 or other changes that have gone on in build flags around that one.

**Comment by vtjnash** [comment]
according the the discussion in the linked PR, tkelman is correct (https://github.com/JuliaLang/julia/issues/2942): llvm applies the LDFLAGS to both the host and target binaries, which is generally not the intention.

**Comment by tkelman** [comment]
Ah, yeah, LLVM does build a whole pile of stuff for the build-system arch, and if we had any flags that were MinGW-specific in LDFLAGS that could result in a bad time when cross-compiling. Shame those gists aren't available any more.

**Comment by staticfloat** [comment]
Is it worrying then that `LLVM_LDFLAGS` has `LDFLAGS` embedded within it?

**Comment by vtjnash** [comment]
> Shame those gists aren't available any more

i don't think it was a very exciting gist. i believe i just noticed that LDFLAGS was getting to the host compiler and causing it to bail.

> Is it worrying then that LLVM_LDFLAGS has LDFLAGS embedded within it?

probably not great, but maybe the second `LDFLAGS=""` comes second and overrides it?

**Pull request merged**
