### PR TITLE
Handle `AbstractQ` in concatenation

### PR DESCRIPTION
**Pull request by dkarrasch**
Handling `AbstractQ`s in concatenation got lost in the overhaul. This brings it back (though it seemed to not be used anywhere), and even better: pre-1.9 `Q`s where handled via `AbstractMatrix` fallbacks, so elementwise. Now, it first materializes the matrix, and then copies to the right place in the destination array.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Moving the code from uniformscaling.jl to special.jl was necessary for bootstrap reasons. The only change there is appending `AbstractQ` to the union in the method signature.

**Comment by dkarrasch** [comment]
Shall we merge this? Who shall we ask for a review? @vtjnash, you looked at this stuff most recently, may I gently bump my review invitation?

**Comment by vtjnash** [comment]
Yes, this look right at a quick glance. We should probably consider trying to drop this Union entirely, if we can.

**Comment by dkarrasch** [comment]
@KristofferC Has this been included in some backport PR? Looks like #50971 hasn't.

**Pull request merged**
