### PR TITLE
[LBT] Bump to v5.2.0

### PR DESCRIPTION
**Pull request by staticfloat**
This should fix issues on i686 linux and using Accelerate on aarch64 darwin.  LBT itself is now much more thoroughly tested [0].

[0] https://buildkite.com/julialang/libblastrampoline

### CODE REVIEW

**Comment by staticfloat** [comment]
@gbaraldi just checking, did I break anything with msan here?

**Comment by gbaraldi** [comment]
Why are you asking? I don't think this should break anything. Well it's not working that well anyway :)

**Comment by staticfloat** [comment]
> Why are you asking? I don't think this should break anything. Well it's not working that well anyway :)

Because I saw commits about building LBT with `msan`, and I wanted to make sure this didn't accidentally clobber some configuration somewhere. :)

**Comment by gbaraldi** [comment]
There isn't anything merged just yet related to dependencies and it seems the msan build is there so 🥳

**Pull request merged**
