### PR TITLE
starting on #20286

### PR DESCRIPTION
**Pull request by jamesonquinn**
If this works I’ll do some more.

### CODE REVIEW

**Comment by tkelman** [comment]
should verify that the combined time of running these on separate workers isn't significantly more than the time it used to take to run the longer version

**Comment by jamesonquinn** [comment]
It was about 10% longer on my machine.

**Comment by tkelman** [comment]
shouldn't the size of the split files be roughly equivalent to the removed portion of the existing files?

**Comment by jamesonquinn** [comment]
Aren't they? Depends what you mean by "roughly", but aside from some housekeeping functions I had to copy, it's the same stuff.

**Comment by tkelman** [comment]
271 lines removed from subarray.jl, but two files added each with about that length?

**Comment by jamesonquinn** [comment]
Oh, sorry. I thought you were talking about bitarray.

Yes, the subarray change has more duplication. Essentially, the file was a suite of tests run on a variety of examples; and then some special-case stuff. I put the special-case stuff in subarray2, without much duplication; but then to split it further, I had to split up the examples, which means that subarray.jl and subarray3.jl are over 90% the same, and only differ at the end when the functions actually get called.

**Comment by JeffBezanson** [comment]
Even if we make this change, it should not be done by copy and pasting code into multiple places. Eventually some of that code will need to be updated, and then we have to remember to change it in all places. The common code can be put into a file like `subarray_test_utils.jl` that gets included by each test file.

**Comment by jamesonquinn** [comment]
I agree; common code should be factored out into a separate file. Should that file just go in tests, or should I make a subdirectory for test utils? (I'd do this for bitarray and similar cases, but probably not for subarray; I think splitting subarray is not a net good).

**Pull request closed without merging**
