### PR TITLE
Refactor of sets, IntSets, and their tests

### PR DESCRIPTION
**Pull request by IainNZ**
In the spirit of testing and coverage, I thought I'd focus on sets. This PR would
- Split the poorly named `collections.jl` test into separate dict test and set test files (as well as some orphaned range tests)
- Reorganizes the set tests to remove redundant tests, and make easier to extend if needed.
- Reorganize `base/set.jl` and `base/intset.jl` slightly to group similar methods that are currently scattered due to organic growth of codebase (I guess)
- Improves coverage for sets a bit
- ~~(this is a WIP) Improves coverage for IntSets a lot~~

~~I thought I'd throw up the PR just in case someone else was going to tackle the set tests before I got there/finished.~~

IntSet refactor better done by merging in @mbauman's work than anything I can do

### CODE REVIEW

**Comment by timholy** [comment]
Nice!

**Comment by mbauman** [comment]
Over Christmas break I had started a much bigger IntSet project.  IntSets are very poorly tested and terribly broken for lots of methods, especially with combinations of complement sets.  They also use the old `bitvector.c` code, which is about half as slow as the Julian BitVector on 64-bit machines for the operations I tested.

I broke the code out into a package to make it easier to iterate on and check coverage.  Check out https://github.com/mbauman/IntSets.jl

**Comment by IainNZ** [comment]
@mbauman thats pretty neat! I was actually thinking to myself how `IntSet` almost doesn't feel like it should even be in base, it feels like it should be in a package. I'll make a new issue for the discussion.

**Comment by StefanKarpinski** [comment]
@mbauman, this is great – I had this on my internal todo list for a long time. `inference.jl` makes heavy use of IntSets which is why it's needed in base. I would support moving this into base as soon as it has the requisite functionality.

**Comment by JeffBezanson** [comment]
+1 for moving @mbauman 's code to base.

Personally I don't need the `complement` feature, and I'd rather remove it. That would remove a lot of complexity, plus the entire `complement` function.

**Comment by IainNZ** [comment]
If we do that, this will happily no longer be a WIP as @mbauman has done everything else I wanted to do, and can be merged.

**Comment by IainNZ** [comment]
Darn, now it needs a rebase. Will merge myself after rebasing+CI pass.

**Comment by IainNZ** [comment]
Travis linux failure seems unrelated, Travis OSX and Windows both fine

**Comment by tkelman** [comment]
> Travis linux failure seems unrelated

I'm not so sure about that. The worker that failed was running the `sets` test.

**Comment by tkelman** [comment]
And multiple other unrelated Travis runs have shown the same failure in the sets test since this was merged.

**Comment by IainNZ** [comment]
Huh. I'll take your word for it, I can't lool. It didn't look like sets was the one that failed to me on the run that occurred with the force push, but I must have failed to interpret the log correctly. Revert the PR if you are sure, I'm in an immigration line at SFO so I sure can't for another 8 hours or so.

**Comment by tkelman** [comment]
```
	From worker 5:	     * sets
	From worker 3:	     * test
	From worker 3:	     * goto
	From worker 3:	     * llvmcall
	From worker 3:	     * grisu
	From worker 6:	     * nullable
	From worker 6:	     * meta
	From worker 6:	     * profile
	From worker 8:	     * libgit2
	From worker 8:	     * docs
	From worker 8:	     * base64
	From worker 8:	     * parser
	From worker 8:	     * examples
Worker 5 terminated.
ERROR: ProcessExitedException()
 in wait at ./task.jl:288
 in wait at ./task.jl:198
 in wait_full at ./multi.jl:586
 in remotecall_fetch at multi.jl:686
 in remotecall_fetch at multi.jl:691
 in anonymous at task.jl:1614
while loading /tmp/julia/share/julia/test/runtests.jl, in expression starting on line 42
```

I'll have to look at the diff more carefully to see what, if anything, is new in sets that wasn't there in collections before. And try to reproduce this locally to see whether it's something we can actually track down, or yet another only-on-CI problem.

**Comment by IainNZ** [comment]
Waiting at gate, looked through Travis, saw this:
https://travis-ci.org/JuliaLang/julia/builds/46742448
Thats a passing master build after this was merged right?

**Comment by IainNZ** [comment]
But
https://travis-ci.org/JuliaLang/julia/jobs/46765736 died on sets
https://travis-ci.org/JuliaLang/julia/jobs/46758119 died on nullable?
https://travis-ci.org/JuliaLang/julia/jobs/46750498 died on sets

D: oh man

**Comment by tkelman** [comment]
yeah, intermittent failures suck

**Comment by IainNZ** [comment]
FWIW, I just ran it on the PackageEval box:

``
[idunning@che test]$ ../julia -e 'versioninfo()'
Julia Version 0.4.0-dev+2651
Commit dfbcf50 (2015-01-12 19:02 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
[idunning@che test]$ make sets
    JULIA test/sets
     * sets
    SUCCESS
```

**Comment by ihnorton** [comment]
Are the travis workers homogeneous? If not, perhaps we should be calling `lshw -class processor` at the beginning of every run to see if there is a failure pattern. Or is this information already available somewhere?

(FWIW, I recently started getting a consistent arrayops failure when running tests locally on my linux xps 13, an i7-3537U. Will file soon if I can't track it down)

**Comment by tkelman** [comment]
here's a success https://travis-ci.org/JuliaLang/julia/jobs/46793925

and a failure https://travis-ci.org/JuliaLang/julia/jobs/46794411

both on AMD Opteron 6376 (Piledriver, according to OpenBLAS)

I'd be suprised if Intel vs AMD processors were causing the difference (do any core devs run AMD hardware?). Either limited memory in Travis VM's, or something about the PPA system libraries would be my guess.

**Comment by ihnorton** [comment]
Well, considering the oddities we saw when haswell came out, I wouldn't be
too surprised.

**Comment by IainNZ** [comment]
Should we make a new issue to discuss these intermittent linux travis failures? Or are people already on the case?

**Comment by tkelman** [comment]
I do think a more broad "stabilize the CI" issue is warranted right now, since this is just one of several ongoing problems.

**Comment by eschnett** [comment]
... beginning with "give me an error message and a backtrace".

**Comment by timholy** [comment]
Yeah, the fraction of randomly-failing tests is annoyingly high now.

But I would put the sets tests front-and-center, so those certainly deserve attention.

**Comment by tkelman** [comment]
@eschnett I don't get what you mean. There are at least 4-5 different failure modes we're hitting right now across the different platforms and CI services we test on. Some of which fail with error messages and backtraces, some don't, and almost all are not easily reproducible locally. Travis has responded nicely in the past to requests for ssh access to a representative VM (I believe @timholy has done this before), but someone who knows what they'll be looking for and would have ideas for what to fix should be the one to make the request.

**Comment by timholy** [comment]
They very readily open your a console for 24 hours. So be ready to make hay when you ask.

**Comment by IainNZ** [comment]
Made https://github.com/JuliaLang/julia/issues/9763

**Comment by eschnett** [comment]
@mbauman I looked at your `IntSet` code. I like it. What is missing are range checks -- especially if `Int` is `Int32`, there can be overflows that should be detected, and people do create sets of size 2^32 and larger (see e.g. #8570).

**Comment by mbauman** [comment]
Thanks @eschnett.  I've been working on getting BitArrays up to speed, but I'll think some about that next.  I know there are some issues with 32-bit code, especially with complement sets.  PRs and issues are welcome at IntSets.jl until it gets merged here :).

**Pull request merged**
