### PR TITLE
fix #34415, remove affinity setting code

### LINKED ISSUE #34415: Julia seems to ignore process affinity settings on Linux
Julia (tested with v1.0 and v1.3) currently seems to ignore (or escape from) process affinity settings on Linux. This is a problem in HPC computing contexts (but also in other scenarios), e.g. when trying to run one Julia process per NUMA domain.

Let's say we have a machine with 16 virtual cores (8 * 2):

```
$ numactl -s
policy: default
preferred node: current
physcpubind: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
[...]
```

Now we use `numactl` to pin a process to CPUs 1 and 2, that process being a `numactl -s` to check that the limitation is actually in effect:

```
$ numactl --physcpubind=1,2 -- numactl -s
policy: default
preferred node: current
physcpubind: 1 2 
[...]
```

Now with `numactl` running `numactl -s` via julia:

```
$ numactl --physcpubind=1,2 -- julia -E 'run(`numactl -s`)'
policy: default
preferred node: current
physcpubind: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
[...]
```

Within Julia, the pinning to CPUs 1 and 2 is gone. I see the same when running multi-threaded Julia code (Julia multi-threading or BLAS via Julia): All CPUs are used, instead of just the selected ones.

### PR DESCRIPTION
**Pull request by JeffBezanson**
This was removed before and added back apparently by mistake.

fix #34415

### CODE REVIEW

**Comment by Keno** [comment]
Test please :). This already regressed once.

**Comment by JeffBezanson** [comment]
Is it ok to use `taskset` to test this? (Linux only though I assume?)

**Comment by KristofferC** [comment]
Seems like it works. Gonna merge this so I can get it into the 1.4 branch and merge that when CI passes.

**Comment by mloubout** [comment]
Doesn't work on 1.3.1
```
This issue is still happenning

```
$ numactl --physcpubind=1,2 -- julia -E 'run(`numactl -s`)'
policy: default
preferred node: current
physcpubind: 0 1 2 3 4 5 6 7 
cpubind: 0 
nodebind: 0 
membind: 0 
Process(`numactl -s`, ProcessExited(0))
```

**Comment by Keno** [comment]
Looks like 1.4 was the first version with this fix?

**Comment by mloubout** [comment]
It looks fixed in 1.4 indeed thanks

**Pull request merged**
