### PR TITLE
Define `isnan` for AbstractTime

### LINKED ISSUE #53: Cannot compute quantile(x::Array{Millisecond,1})
```
ms = Millisecond.(1:10)
quantile(ms, 0.5)
```
gives

```
ERROR: MethodError: no method matching isnan(::Millisecond)
Closest candidates are:
  isnan(::BigFloat) at mpfr.jl:881
  isnan(::Missing) at missing.jl:100
  isnan(::Float16) at float.jl:537
  ...
Stacktrace:
 [1] _quantilesort!(::Array{Millisecond,1}, ::Bool, ::Float64, ::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:960
 [2] quantile!(::Array{Millisecond,1}, ::Float64; sorted::Bool, alpha::Float64, beta::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:943
 [3] quantile(::Array{Millisecond,1}, ::Float64; sorted::Bool, alpha::Float64, beta::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:1052
 [4] quantile(::Array{Millisecond,1}, ::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:1052
 [5] top-level scope at REPL[14]:1
 [6] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

on Julia 1.5.2.

The root issue is of course 
```
julia> isnan(Millisecond(1))
ERROR: MethodError: no method matching isnan(::Millisecond)
Closest candidates are:
  isnan(::BigFloat) at mpfr.jl:881
  isnan(::Missing) at missing.jl:100
  isnan(::Float16) at float.jl:537
```

since `_quantilesort!` calls `isnan(x[end])`

### PR DESCRIPTION
**Pull request by ianfiske**
Fix https://github.com/JuliaLang/Statistics.jl/issues/53

### CODE REVIEW

**Comment by mschauer** [comment]
Should adapt the doc string and widen the definition  of the scope (perhaps “a number l” instead of “a floating point number”)

**Comment by mschauer** [comment]
If widening `isnan` to number-likes is not welcomed, a local solution would be
```
x -> x isa AbstractFloat ? isnan(x) : false
```
but that would break code for `x` which aren't AbstractFloats but could be `NaN`-likes, for example `NaN` with units.

**Comment by nalimilan** [comment]
At https://github.com/JuliaLang/julia/pull/35989 I also felt that the absence of an `isnan(::Number)` fallback was a problem to write generic code.

But I don't think adding `isnan(::TimePeriod)` is the good fix for https://github.com/JuliaLang/Statistics.jl/issues/53, as we will keep getting an error for other types which don't define it. And if we do that manually for all types, we'd better define `isnan(::Any) = false` -- which would be inconsistent with `iszero`.

Can't we just check `applicable` or `method_exists` before calling `isnan` in `quantile`?

**Comment by ianfiske** [comment]
Good point @nalimilan -- I've opened https://github.com/JuliaLang/Statistics.jl/pull/54 instead.  Closing this.

**Pull request closed without merging**
