### PR TITLE
`stale_cachefile`: account for path separator when checking @depot 

### PR DESCRIPTION
**Pull request by fatteneder**

### CODE REVIEW

**Comment by fatteneder** [comment]
@staticfloat We overlooked that in #51989

**Comment by staticfloat** [comment]
Hmmm, I thought that the path separator was a feature, not a bug.  Don't we want to ignore something that looks like `@depotfoo` and only allow things that look like `@depot/foo`?

**Comment by fatteneder** [comment]
Somehow this is the only place where we account for the path separator.

**Comment by staticfloat** [comment]
> But then it should be joinpath("@depot","") so that it appends the OS specific path separator, no?

Yes, or the slightly faster `string("@depot", Filesystem.pathsep())`

**Comment by fatteneder** [comment]
test failures seem unrelated

**Comment by fatteneder** [comment]
@staticfloat bump

**Pull request merged**
