### PR TITLE
Always use `-Wl,--warn-unresolved-symbols` in MSAN builds

### LINKED ISSUE #48732: Build from source of 1.9.0-beta1 to beta4 broken due to suite-sparse
Pull request https://github.com/JuliaLang/julia/pull/46348 introduced linker option `--warn-unresolved-symbols`. This is supported by GNU ld, but not by the macOS system linker, so when building from source we error out with:

```
2023-02-20T09:18:13.6766340Z checking if the linker (ld) is GNU ld... /Applications/Xcode.app/Contents/Developer/usr/bin/make install INSTALL=/private/tmp/julia-20230220-10153-1cp20up/julia-1.9.0-beta4/deps/scratch/SuiteSparse-5.10.1
2023-02-20T09:18:13.6767810Z clang -mmacosx-version-min=13  -Wl,-rpath,/opt/homebrew/Cellar/julia/1.9.0-beta4/lib/julia -Wl,-rpath,/opt/homebrew/opt/curl/lib -Wl,-rpath,/opt/homebrew/opt/mbedtls@2/lib -Wl,-rpath,/opt/homebrew/opt/openblas/lib -Wl,-rpath,/opt/homebrew/opt/gcc/lib/gcc/current -Wl,-rpath,/opt/homebrew/lib -Wl,-rpath,/usr/lib -L/private/tmp/julia-20230220-10153-1cp20up/julia-1.9.0-beta4/deps/scratch/SuiteSparse-5.10.1/lib -Wl,-rpath,'@loader_path/'  -Wl,--warn-unresolved-symbols -dynamiclib -compatibility_version 5 -current_version 5.10.1 -Wl,-install_name -Wl,@rpath/libsuitesparseconfig.5.dylib -shared -undefined dynamic_lookup SuiteSparse_config.o -o /private/tmp/julia-20230220-10153-1cp20up/julia-1.9.0-beta4/deps/scratch/SuiteSparse-5.10.1/lib/libsuitesparseconfig.5.10.1.dylib -lm -rpath /private/tmp/julia-20230220-10153-1cp20up/julia-1.9.0-beta4/deps/scratch/SuiteSparse-5.10.1/lib
2023-02-20T09:18:13.6768700Z ld: unknown option: --warn-unresolved-symbols
2023-02-20T09:18:13.6768940Z clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by giordano**
One of the two ways I could think of to fix #48732.  The other one is to use `-Wl,--warn-unresolved-symbols` in suitesparse only when doing the MSAN build, but I figured that this flag might be useful for other packages as well.

CC: @fxcoudert.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I'm not sure I understand. `--warn-unresolved-symbols` is not recognised by macOS ld, so it's not clear why we should pass it to more makefiles? Unless `SANITIZE_MEMORY` is never defined on macOS?

**Comment by giordano** [comment]
> Unless `SANITIZE_MEMORY` is never defined on macOS?

I think MSAN builds (somewhat) work only on x86_64 linux.  @gbaraldi is that correct?

**Comment by gbaraldi** [comment]
MSAN only exists on linux currently so yeah.

**Comment by giordano** [comment]
Ok, according to the [docs](https://docs.julialang.org/en/v1/devdocs/sanitizers/) builds with sanitizer might work also on macOS.  I change it to add `-Wl,--warn-unresolved-symbols` only on Linux and FreeBSD.

**Comment by gbaraldi** [comment]
Sanitizers work on macos fine. Specifically ASAN and TSAN, but MSAN is Linux and some BSDs only. At least currently.

**Pull request merged**
