### PR TITLE
make sure we install the suffixed LLVM library correctly

### LINKED ISSUE #34264: Bug report: `make install` does not copy `libLLVM-8jl.so` on Linux Environment (Julia-1.5 Dev)
- Since `make install` does not copy `libLLVM-8jl.so` (which wll be generated by running `make` command) on linux environment, I can't run Julia that will be installed by `make install` .
- If I copy `libLLVM-8jl.so` manually to directory `path/to/prefix/lib/julia/` it will be alright on Linux environment.

# How to Reproduce

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    build-essential \
    libatomic1 \
    python \
    gfortran \
    perl \
    wget \
    m4 \
    cmake \
    pkg-config \
    git

ARG JL_VERSION="master"
ARG WDIR="/root"
ARG JL_BUILD_DIR=$WDIR/build
WORKDIR $JL_BUILD_DIR

RUN echo "\
CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0\n\
prefix=/usr/local/julia-$JL_VERSION\n\
USE_BINARYBUILDER = 0\n\
" > Make.user \
    && cat Make.user \
    && git clone --depth=1 -b $JL_VERSION https://github.com/JuliaLang/julia.git julia-$JL_VERSION\
    && cp Make.user $JL_BUILD_DIR/julia-$JL_VERSION \
    && cd julia-$JL_VERSION \
    && make -j $(nproc) \
    && make install

RUN rm -r $JL_BUILD_DIR && \
    apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
ENV PATH=/usr/local/julia-$JL_VERSION/bin:$PATH
# runtime test
RUN julia -e "using InteractiveUtils; versioninfo()" # it will fail

CMD ["julia"]
```

- Run the following command will occur an error.

```console
$ docker build -t buildmaster .
...
julia: error while loading shared libraries: libLLVM-8jl.so: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #34264

### CODE REVIEW

**Comment by vchuravy** [comment]
:/ Doesn't work for `LLVM_VER=svn`

```
make print-JL_PRIVATE_LIBS-0 LLVM_VER=svn
JL_PRIVATE_LIBS-0=libccalltest libllvmcalltest libsuitesparse_wrapper libamd libcamd libccolamd libcholmod libcolamd libumfpack libspqr libsuitesparseconfig libpcre2-8 libdSFMT libgmp libmpfr libssh2 libmbedtls libmbedcrypto libmbedx509 libcurl libgit2 libz libLLVM libLLVM-svn libopenlibm libopenblas64_ libgfortran libgcc_s libquadmath
```

**Review by vtjnash — CHANGES_REQUESTED** [review]
We've typically preferred auto-detection for this (via `llvm-config-host`), as exemplified in `src/Makefile`.

**Review by staticfloat — APPROVED** [review]
Nice improvement.

**Comment by vtjnash** [comment]
Build logs:
```
make: /buildworker/worker/package_linux64/build/usr/tools/llvm-config: Command not found
```

**Comment by staticfloat** [comment]
You probably need to delay expansion of it until after LLVM has been downloaded by BB.

**Comment by nalimilan** [comment]
Bump. This just hit me when building RPM packages for 1.4.0.

**Comment by nalimilan** [comment]
Actually it's fixed on master by https://github.com/JuliaLang/julia/commit/5e0cab69966eb989f380492dda7590bca3a3ba8d. Not sure whether this PR is still needed (it's more general so maybe still worth having?), but for backports the simple fix is enough: see https://github.com/JuliaLang/julia/pull/35273

**Pull request closed without merging**
