### PR TITLE
Accept IndexStyle in diagind, defaulting to IndexLinear

### PR DESCRIPTION
**Pull request by jishnub**
Partly revert and redesign #52115, with `diagind` now accepting an optional `IndexStyle`, which is `IndexLinear` by default. This should address the breakages reported in that PR. After this,
```julia
julia> D = Diagonal(1:4)
4×4 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅
 ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  4

julia> diagind(D)
1:5:16

julia> diagind(D, IndexCartesian())
StepRangeLen(CartesianIndex(1, 1), CartesianIndex(1, 1), 4)
```

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]
Are these all internal usages of `diagind`? I assume so.

**Comment by jishnub** [comment]
I didn't think of this as internal, as other matrix types such as `BandedMatrices` might benefit from a Cartesian range

**Comment by dkarrasch** [comment]
I meant the callsites, not the method definition itself. Like, have you optimized all "internal" calls to `diagind`? But since you have done that already in very different places, I was assuming that.

**Comment by jishnub** [comment]
Oh alright, yes, I've updated the internal calls. Not all of them at the moment, as this only makes a difference if the rest of the operations are also `O(N)`. As a matter of style, though, we might decide to change it everywhere. If we decide this, I'll make further changes that aren't strictly necessary for performance.

**Pull request merged**
