### PR TITLE
Remove references to the LegacyPassManager

### PR DESCRIPTION
**Pull request by gbaraldi**
This probably needs to be held up until we move master to LLVM16 to keep the idea that we support the current LLVM version and the one before.

We still keep references in a couple places because the objectfile emission still uses it.

### CODE REVIEW

**Comment by vchuravy** [comment]
I would be okay with ignoring that fiction, this code is almost not tested anymore.

**Review by maleadt — APPROVED** [review]
GPUCompiler.jl still works after this, so LGTM!

**Review by vtjnash — APPROVED** [review]
LLVM's next release comes in about 2 weeks, so I say we merge this now and then get to upgrading

**Comment by gbaraldi** [comment]
Me, mose and valentin are working on it, as always it's annoying. We also need to turn on opaque pointers for LLVM 16.

**Comment by vchuravy** [comment]
Yeah we are currently a release behind. Next release is 17, current is 16, we are on 15.

**Pull request merged**
