### PR TITLE
Allow sys.ji to not exist during `make install`

### PR DESCRIPTION
**Pull request by staticfloat**
@JeffBezanson does this look like the right fix for https://github.com/JuliaLang/julia/pull/11640#issuecomment-114574852?

### CODE REVIEW

**Comment by staticfloat** [comment]
Since the current rules will fail without a `sys.$(SHLIB_EXT)`, I don't think we need to copy over `sys.o`, right?

**Comment by tkelman** [comment]
Yeah I think we should not be putting the .o in the installed copy. We need .ji iff we need a backup option for running without a dylib. Basically only for coverage, or windows until we upgrade llvm.

**Comment by staticfloat** [comment]
Failure unrelated.  I'm going to merge this as, even though it may not be the perfect fix, it does work, and is very unlikely to break anything.  Let me know if there's a better one.

**Comment by tkelman** [comment]
This is good enough for now I think, there is a need to get updated nightlies out. I wonder why Travis didn't hit this, doesn't it do `make install`?

**Pull request merged**
