### PR TITLE
Improve bounds error for ranges

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
This prints weird result for `LinSpace` because of #11245 but should be fixed by #11246 .

**Comment by vtjnash** [comment]
fixed by 35cdca9669dbb5b46f086954eedaa50cba1fe26a

**Comment by vtjnash** [comment]
lgtm. @JeffBezanson any idea if this would cause a performance issue due to creating an unintentional gc frame in these functions?

**Comment by mbauman** [comment]
I believe it does.  I have a different fix in #10525, where I punt completely to `checkbounds` (which is carefully written to inline the check but not the object creation).

**Comment by vtjnash** [comment]
i suspect the root may be present regardless of this change however, due to the interaction of `throw(BoundsError())`, so this may be good to merge anyways (until #10525 lands)

**Comment by yuyichao** [comment]
Somehow it wasn't? Unless I'm missing it.

```julia
julia> @code_llvm getindex(a, 1)

define i64 @julia_getindex_44397(%StepRange.2, i64) {
top:
  %2 = icmp slt i64 %1, 1
  br i1 %2, label %L4, label %L1

L1:                                               ; preds = %top
  %3 = call i64 @julia_length2749(%StepRange.2 %0)
  %phitmp = icmp slt i64 %3, %1
  br i1 %phitmp, label %L4, label %L5

L4:                                               ; preds = %L1, %top
  %4 = call %jl_value_t* @alloc_2w()
  %5 = getelementptr inbounds %jl_value_t* %4, i64 -1, i32 0
  store %jl_value_t* inttoptr (i64 140711023368784 to %jl_value_t*), %jl_value_t** %5, align 8
  %6 = getelementptr inbounds %jl_value_t* %4, i64 0, i32 0
  store %jl_value_t* null, %jl_value_t** %6, align 8
  %7 = getelementptr inbounds %jl_value_t* %4, i64 1, i32 0
  store %jl_value_t* null, %jl_value_t** %7, align 8
  call void @jl_throw_with_superfluous_argument(%jl_value_t* %4, i32 350)
  br label %L5

L5:                                               ; preds = %L4, %L1
  %8 = extractvalue %StepRange.2 %0, 0
  %9 = add i64 %1, -1
  %10 = extractvalue %StepRange.2 %0, 1
  %11 = mul i64 %9, %10
  %12 = add i64 %11, %8
  ret i64 %12
}
```

**Comment by mbauman** [comment]
If I remember right, the zero-arg Error() types are global singleton constants, so they're already rooted.

**Comment by vtjnash** [comment]
it used to be, but BoundsError isn't a singleton constant anymore.

in the code above, the allocation is present, but notably, the call to throw gets properly inlined and does not result in the creation of a GC frame. this should be OK, since jl_throw_with_superflous_argument should be non-allocating.

**Comment by yuyichao** [comment]
So dies the GC stack has to be updated at the beginning of the function and does this mean that inlining can actually make unrelated code path slower?

**Comment by mbauman** [comment]
Oh, that's interesting. In that case, how does `%4` get freed?  It looks like it sets the type tag to a pointer (which resolves to the `BoundsError` type), and sets both fields to null, and then calls the internal throw method.

**Comment by yuyichao** [comment]
@mbauman AFAIK, `alloc_2w` allocated on the heap but is managed by the GC (which is why it needs to be rooted before the next allocation happens). It will be free'd if it is not reachable the next time GC fires.

**Comment by yuyichao** [comment]
@vtjnash 

In this case, would defining a
```julia
@noinline throw_with_args(typ, args...) = type(args...)
```

Solve the problem?

**Comment by carnaval** [comment]
@yuyichao Yes. But even in non managed languages inlining can definitely make code slower because of instruction cache pollution. A call instruction is extremely cheap these days so the biggest gain with inlining is the discovery of new intraprocedural optimizations, otherwise it's usually a waste.

**Comment by yuyichao** [comment]
@carnaval 
IIRC last time I benchmarked an empty function call (empty function marked with noinline gcc attribute) it is still non-negligible for a tight loop (on a Cortex-A9 though, not sure about x86).

**Comment by mbauman** [comment]
Ah, of course.  Thanks for the explanation, @yuyichao.

That general `throw_with_args` construction might be useful. It's basically the generalized version of what I've done in #10525: https://github.com/JuliaLang/julia/pull/10525/files#diff-2264bb51acec4e7e2219a3cb1c733651R146

**Comment by vtjnash** [comment]
i think what we actually want is something like:
```diff
diff --git a/base/boot.jl b/base/boot.jl
index d02cba7..5d5488d 100644
--- a/base/boot.jl
+++ b/base/boot.jl
@@ -206,12 +206,17 @@ end
 
 abstract Exception
 
+macro _noinline()
+    _expr(:meta, :noinline)
+end
+
+
 immutable BoundsError        <: Exception
     a::Any
     i::Any
     BoundsError() = new()
-    BoundsError(a::ANY) = new(a)
-    BoundsError(a::ANY, i::ANY) = new(a,i)
+    BoundsError(a::ANY) = (@_noinline; new(a))
+    BoundsError(a::ANY, i::Any) = (@_noinline; new(a,i))
 end
 immutable DivideError        <: Exception end
 immutable DomainError        <: Exception end
```

**Comment by yuyichao** [comment]
Correct me if I'm wrong but I thought `::ANY` will make it not specialize on the argument and therefore requires boxing before the arguments are passed in?

**Comment by yuyichao** [comment]
And of course for the `throw_with_args` I meant to do the `throw` in the function as well.....

**Comment by yuyichao** [comment]
Is `@noinline` and the `--inline=no` option ignored by codegen or llvm?

Or is there sth else I'm missing here

```julia
@noinline throw_with_args(typ, args...) = throw(typ(args...))

function f(a, b)
    if b == 0
        throw_with_args(BoundsError, a, b)
    end
end

println(@code_typed f(1, 2))
@code_llvm f(1, 2)
```

Running with `juila --inline=no -f`
```julia
Any[:($(Expr(:lambda, Any[:a,:b], Any[Any[],Any[Any[:a,Int64,0],Any[:b,Int64,0]],Any[],Any[]], :(begin  # /home/yuyichao/tmp/julia/throw_error.jl, line 21:
        unless $(Expr(:call1, :(==), :(b::Int64), 0)) goto 0 # line 22:
        return $(Expr(:call1, :throw_with_args, :BoundsError, :(a::Int64), :(b::Int64)))
        goto 1
        0: 
        return
        1: 
    end::Void))))]
```
```llvm
define void @julia_f_44416(i64, i64) {
top:
  %2 = alloca [5 x %jl_value_t*], align 8
  %.sub = getelementptr inbounds [5 x %jl_value_t*]* %2, i64 0, i64 0
  %3 = getelementptr [5 x %jl_value_t*]* %2, i64 0, i64 2
  %4 = bitcast [5 x %jl_value_t*]* %2 to i64*
  store i64 6, i64* %4, align 8
  %5 = getelementptr [5 x %jl_value_t*]* %2, i64 0, i64 1
  %6 = bitcast %jl_value_t** %5 to %jl_value_t***
  %7 = load %jl_value_t*** @jl_pgcstack, align 8
  store %jl_value_t** %7, %jl_value_t*** %6, align 8
  store %jl_value_t** %.sub, %jl_value_t*** @jl_pgcstack, align 8
  store %jl_value_t* null, %jl_value_t** %3, align 8
  %8 = getelementptr [5 x %jl_value_t*]* %2, i64 0, i64 3
  store %jl_value_t* null, %jl_value_t** %8, align 8
  %9 = getelementptr [5 x %jl_value_t*]* %2, i64 0, i64 4
  store %jl_value_t* null, %jl_value_t** %9, align 8
  %10 = call i1 @"julia_==256"(i64 %1, i64 0)
  br i1 %10, label %if, label %L

if:                                               ; preds = %top
  %11 = load %jl_value_t** inttoptr (i64 140186201196632 to %jl_value_t**), align 8
  store %jl_value_t* %11, %jl_value_t** %3, align 8
  %12 = call %jl_value_t* @jl_box_int64(i64 signext %0)
  store %jl_value_t* %12, %jl_value_t** %8, align 8
  %13 = call %jl_value_t* @jl_box_int64(i64 signext %1)
  store %jl_value_t* %13, %jl_value_t** %9, align 8
  %14 = call %jl_value_t* @julia_throw_with_args_44417(%jl_value_t* inttoptr (i64 140186234591696 to %jl_value_t*), %jl_value_t** %3, i32 3)
  %15 = load %jl_value_t*** %6, align 8
  store %jl_value_t** %15, %jl_value_t*** @jl_pgcstack, align 8
  ret void

L:                                                ; preds = %top
  %16 = load %jl_value_t*** %6, align 8
  store %jl_value_t** %16, %jl_value_t*** @jl_pgcstack, align 8
  ret void
}
```

**Comment by yuyichao** [comment]
So the best solution I've found so far is

```julia
@noinline throw_with_args(typ::ANY, args) = throw(typ(args...))

function f(a, b)
    throw_with_args(BoundsError, (a, b))
end

@code_llvm f(1, 2)
```

Output
```llvm
; Function Attrs: noreturn
define void @julia_f_44267(i64, i64) #-1 {
top:
  %2 = load %jl_value_t** inttoptr (i64 139784772569176 to %jl_value_t**), align 8
  %3 = insertvalue [2 x i64] undef, i64 %0, 0
  %4 = insertvalue [2 x i64] %3, i64 %1, 1
  call void @julia_throw_with_args_44268(%jl_value_t* %2, [2 x i64] %4)
  ret void
}
```

**Comment by yuyichao** [comment]
It will still need roots if one of the arguments is `jl_value_t*` so is sth like the following better?

```julia
@noinline throw_with_args(typ::ANY) = throw(typ())
@noinline throw_with_args(typ::ANY, arg1) = throw(typ(arg1))
@noinline throw_with_args(typ::ANY, arg1, arg2) = throw(typ(arg1, arg2))
@noinline throw_with_args(typ::ANY, arg1, arg2, arg3) =
    throw(typ(arg1, arg2, arg3))
@noinline throw_with_args(typ::ANY, arg1, arg2, arg3, arg4) =
    throw(typ(arg1, arg2, arg3, arg4))
throw_with_args(typ::ANY, args...) = throw(typ(args...))
```

**Comment by yuyichao** [comment]
Close as this is covered by #10525 .

**Pull request closed without merging**
