### PR TITLE
Better error for elem-wise + and - of arrays and scalars

### PR DESCRIPTION
**Pull request by jkrumbiegel**
For addition and subtraction of arrays of numbers and a scalar, the error message suggests using broadcasting.

https://github.com/JuliaLang/julia/issues/34636

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
looks like this in action
```julia
a = rand(5)

>>> 1 + a
ERROR: MethodError: no method matching +(::Int64, ::Array{Int64,1})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:529
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:53
  +(::Integer, ::Integer) at int.jl:871
  ...
Stacktrace:
 [1] top-level scope at none:0
```

or
```julia
>>> a - 1//3
ERROR: MethodError: no method matching -(::Array{Int64,1}, ::Rational{Int64})
For element-wise subtraction, use broadcasting with dot syntax: array .- scalar
Closest candidates are:
  -(::Complex{Bool}, ::Real) at complex.jl:303
  -(::Missing, ::Number) at missing.jl:115
  -(::Complex, ::Real) at complex.jl:315
  ...
Stacktrace:
 [1] top-level scope at none:0
```

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Thanks, very nice first PR! This should be quite helpful for many new users.

**Comment by StefanKarpinski** [comment]
It would be good to have a more general framework for pattern matching on errors and giving improved error messages, but this is a great addition for now.

**Comment by KristofferC** [comment]
If possible, would be good with some kind of test that hits this code path and checks that the error message ends up as expected.

And in the future, we should make this extensible so maybe packages can add stuff as well, but for now, let's just get this in.

**Comment by timholy** [comment]
Yes, this does need a test, but it's awesome.

I think you meant to link to #34636.

**Comment by jkrumbiegel** [comment]
I could add tests, but how do you test errors? By triggering the error and comparing the error string to the expected one? And where would that test go, somewhere in https://github.com/JuliaLang/julia/blob/master/test/errorshow.jl I assume?

**Comment by fredrikekre** [comment]
> I could add tests, but how do you test errors?

You can use `@test_throws` (from the `Test` stdlib).

**Comment by timholy** [comment]
I wouldn't use `@test_throws`, consider modeling it after https://github.com/JuliaLang/julia/blob/3720edfc06ee8687b54ee7fbb908c9f03f4fc557/test/errorshow.jl#L345-L374

**Comment by jkrumbiegel** [comment]
> In this specific case I wouldn't use @test_throws, consider modeling it after 

Hopefully I did this correctly, the tests ran fine on my local machine but I have zero experience with making changes in Base (well, one experience now)

**Comment by timholy** [comment]
> but I have zero experience with making changes in Base (well, one experience now)

And So It Begins. :laughing: 

Thanks for a great contribution!

**Pull request merged**
