### PR TITLE
A = nothing instead of A = 0

### PR DESCRIPTION
**Pull request by cossio**
Fix https://github.com/JuliaLang/julia/issues/24205.

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]
Just as a note for the future: if you have a fix for a problem then there is no need to open an issue for it. That splits the discussion to both the issue and the PR. But perhaps this is just my opinion ¯\\\_(ツ)\_/¯

**Comment by yuyichao** [comment]
That mention of manually calling `gc()` should be removed. Also, as I mentioned in that thread, using proper local scope is usually much better.

**Comment by djsegal** [comment]
Why did something get merged for this?

The PR just changed two lines of markdown?

**Comment by KristofferC** [comment]
See the referenced issue.

**Pull request merged**
