### PR TITLE
RFC: Parent argument for `f(::Function)` variants of `mktemp{,dir}`

### PR DESCRIPTION
**Pull request by ghost**
This makes them on par with their non-`f(::Function)` equivalents.  Most likely this functionality should have been included in f8ccca2.

"Bonus" commit: Documentation and mention in `NEWS.md`, I forgot to add this to #9017.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
:+1:

**Comment by tkelman** [comment]
I think the docstrings need to go into both helpdb.jl, and at least the signatures into the RST where you have them. Running `doc/genstdlib.jl` should result in copying the docstring content from helpdb into the RST.

**Comment by ninjin** [comment]
Thank you @tkelman, observant as always.  I added the information to `helpdb.jl` as well, but I could not get `doc/genstdlib.jl` to inject the RST properly.  Thus I added it manually to `doc/stdlib/file.rst`.  If anyone can spot any syntax issue in what I wrote in `doc/genstdlib.jl` that could confuse the script, I would be most thankful.  I think I am in line with the style used for other functions with more than one method.

**Comment by ninjin** [comment]
A gentle ping, I think this is good to go.

**Comment by tkelman** [comment]
I'm not sure what was wrong - it may be that you need to run `make clean && make` before `./julia doc/genstdlib.jl` works properly. The way you added it looks close enough, but when I rerun genstdlib it gets modified slightly - 8c0602e2ad8f26b76219562531c211519ebe8143. I'll be merging that shortly.

**Pull request merged**
