### PR TITLE
allow passing `--project=temp` to create a temporary environment

### PR DESCRIPTION
**Pull request by KristofferC**
cc @aviks

### CODE REVIEW

**Comment by vchuravy** [comment]
Maybe `@temp` or something to signify something special?

**Comment by KristofferC** [comment]
> Maybe @temp or something to signify something special?

That already means activating the "shared" environment temp (which exists in `.julia/environments`).

**Comment by jpsamaroo** [comment]
Maybe instead it could be `--project=_`, which reads as "I don't care, just give me some project"? That's super unlikely to be used as an actual project directory name, and stands out a bit more as being special behavior. Another possibility would be `--project=+`, which reads as "Give me a new project".

**Comment by KristofferC** [comment]
I think it almost has to be `temp` to make people muscle memory from Pkg kick in. I think it should be fine, there is already `--project=@shared` which can theoretically clash with folder names.

**Comment by vtjnash** [comment]
How about --temp, so it is exactly the same muscle memory, and less likely to be a file?

**Comment by Moelf** [comment]
I think `--project=temp` or `--project=@temp` are both fine -- if someone has a `./temp` or `~/.julia/environments/temp`, they probably use the folders for the same purpose anyway?

`--temp` is however IMO the best, because currently we have

```julia
pkg> activate --temp
  Activating new project at `/tmp/jl_hqDMaF`
```
the muscle memory is never `=temp`, it's always `--temp`

**Comment by vtjnash** [comment]
Replaced by https://github.com/JuliaLang/julia/pull/51149/

**Pull request closed without merging**
