### PR TITLE
Fix inference heuristic hacks

### LINKED ISSUE #13350: Inlining arithmetic can produce slowdowns
I've got an application where I'm seeing a big performance difference between
```jl
cm*vm + c*v + cp*vp
```
and
```jl
(cm*vm + c*v) + cp*vp
```
This is related to previous issues https://github.com/JuliaLang/julia/pull/6193#issuecomment-56130501 #5011 https://github.com/JuliaLang/julia/pull/7075#issuecomment-45548446 #10278. However, they're all closed, so I thought it would be better to start fresh.

This demo relies on ForwardDiff.jl, and uses the code in [this gist](https://gist.github.com/timholy/fed671c2261288e3c786). 

Timing results:
```jl
julia> include("perf_parens.jl")
Warmup @time
  0.000001 seconds (3 allocations: 144 bytes)
Without parentheses:
  0.350804 seconds (16.00 M allocations: 488.282 MB, 19.45% gc time)
With parentheses:
  0.085496 seconds (15 allocations: 624 bytes)
```

Considerably more discussion can be found [here](https://github.com/JuliaDiff/ForwardDiff.jl/pull/58).

Anything to do here? Or just tweak Interpolations.jl (which is where those functions get `@generated`) to insert the parentheses?

### PR DESCRIPTION
**Pull request by simonster**
These were broken by #11274 but no one noticed. Fixes #13350.

### CODE REVIEW

**Comment by simonster** [comment]
With this PR:

```julia
➜  ~ julia --depwarn=no perf_parens.jl 
Warmup @time
  0.000002 seconds (148 allocations: 10.151 KB)
Without parentheses:
  0.071398 seconds (15 allocations: 624 bytes)
With parentheses:
  0.073499 seconds (15 allocations: 624 bytes)
```

**Comment by tkelman** [comment]
failing an llvm assertion on osx and windows?
```
Assertion failed: (isVirtualRegister(Reg) && "Not a virtual register"), function virtReg2Index, file /private/tmp/llvm33-julia-IYf1/llvm-3.3.src/include/llvm/Target/TargetRegisterInfo.h, line 293.
signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
	From worker 3:	     * functional           Worker 3 terminated.
ERROR (unhandled task failure): EOFError: read end of file
```

**Comment by timholy** [comment]
Thanks for looking into this, @simonster!

**Comment by simonster** [comment]
The LLVM assertion failure is breaks the tests with this PR but is possible to trigger without it. Filed #13366.

**Comment by KristofferC** [comment]
Maybe it is possible to add a test for this?

**Comment by simonster** [comment]
I think it would be non-trivial to test directly and the logic is pretty simple. But we should definitely have a perf test for #5011 or #13350. I'll try to add that to @IainNZ's [collection](https://github.com/IainNZ/BasePerfTests.jl).

**Comment by JeffBezanson** [comment]
Excellent! Thanks for figuring this out.

**Comment by tkelman** [comment]
So should I be cherry-picking this into #13357 if the assertion failure is a master-only issue?

**Comment by simonster** [comment]
@tkelman Yes, I think so.

**Comment by JeffBezanson** [comment]
Bump. I think we should rebase and merge this.

**Pull request merged**
