### PR TITLE
allow redefinition of egal parametric types

### LINKED ISSUE #16424: Re-evaluating parameterized type definitions erros
I noticed this inconsistency (both in 0.4 and 0.5):

``` julia
julia> type B
       a
       end

julia> type B
       a
       end

julia> type A{T}
       a
       end

julia> type A{T}
       a
       end
ERROR: invalid redefinition of constant A
```

Would be nice if the second would not error.

### PR DESCRIPTION
**Pull request by vtjnash**
also makes TypeVar immutable, which seems to pass the core tests, and is more correct (as long as Oscar doesn't try to copy these types in his inline immutable change before Jeff's change to implement UnionAll)

github: fixes #16424

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Making TypeVar immutable, especially at this point, seems very risky to me. We definitely depend on distinguishing TypeVars with identical data (name and bounds) based on address. Since TypeVars contain references they are always heap allocated, which is why it's working, but changing this just seems to be pure asking for trouble.

**Comment by KristofferC** [comment]
Does this fix https://github.com/JuliaLang/julia/issues/16424?

**Comment by vtjnash** [comment]
yes

**Comment by vtjnash** [comment]
@JeffBezanson I know all of that. But since it will work now, and should work in the future (with UnionAll), why not do it now? (the alternative is to write a version of compare_svec for use here which computes whether they are equivalent)

**Comment by JeffBezanson** [comment]
I don't think it will work with UnionAll either. At least initially, I was planning to continue to use addresses to identify TypeVars. The only real alternative seems to be deBruijn indices, but that would be a pretty dramatic change and I'd rather not do it all at once.

On the julia side, I believe this can break `tvar_env` used in showing. Fortunately there are not many other cases in julia code where we compare TypeVars, but I'd rather not rely on luck.

**Comment by vtjnash** [comment]
ok, updated to use typeseq instead of egal

**Comment by JeffBezanson** [comment]
This allows the following:

```
julia> type A{T}
       x::T
       end

julia> type A{T}
       x::Any
       end
```

**Comment by vtjnash** [comment]
Of course. It allows a lot more than that too. Does that matter?

**Comment by JeffBezanson** [comment]
I suppose since the only effect of this is to ignore the new type definition, it's safe.

**Comment by tkelman** [comment]
does redefining types like this give warnings or is it silent?

**Comment by JeffBezanson** [comment]
It's silent, but when that decision was made we only allowed truly identical "redefinitions". However you will most often get a method-overwrite warning from the constructor being defined again.

**Comment by vtjnash** [comment]
updated to check for more typeof equivalence

**Comment by tkelman** [comment]
test?

**Comment by tkelman** [comment]
still has no test?

**Comment by cstjean** [comment]
Is there any chance that this could be backported? It would make ClobberingReload's life much easier.

**Comment by KristofferC** [comment]
This regressed, #16424

**Comment by tkelman** [comment]
This is why we shouldn't merge fixes without adding a test if at all possible.

**Pull request merged**
