### PR TITLE
Expunging @ngenerate and @nsplat

### PR DESCRIPTION
**Pull request by timholy**
This one's for you, @JeffBezanson. Happy early thesis-defense.

Now that we have `stagedfunction`s/`@generated function`s, there is no need for `@ngenerate`. (`@nsplat` still might have a purpose, but without `@ngenerate` I think we might as well ditch both at once. You can fake de-splatting with `stagedfunction`s.) This is a WIP at getting rid of them. Currently if I try to convert those last few BitArray methods, I get failures: building hangs at `primes.jl`, the first file after `multidimensional.jl`. Interestingly, they all involve `@ncall`, leading me to suspect a type-inference problem. #8504 is a likely suspect.

This is broken up in a series of small steps because it was basically murder to debug this---these functions are core infrastructure, and with multiple breakages it's hard to figure out what's happening. Given that we don't fully trust stagedfunctions yet (see https://github.com/JuliaLang/julia/pull/8501#issuecomment-63922923), I also thought it would be good to ensure that `git bisect` would be as informative as possible. But if people object, I can (reluctantly) squash. Just don't ask me to bisect any problems later :smile:.

See also https://github.com/JuliaLang/Compat.jl/pull/19, which hopefully will provide backward-compatibility. I know this wasn't an exported interface, but I still felt guilty about just yanking it. I'll also write up some docs about how to convert functions.

### CODE REVIEW

**Comment by timholy** [comment]
It seems the real obstacle to further progress on this PR was recursive staged functions (#8853), which was fixed by the merger of #9921. I've gone ahead and finished the removal of `@ngenerate` and `@nsplat` from base. I've also removed the WIP from the title. Finally, I've verified that https://github.com/JuliaLang/Compat.jl/pull/19, once merged, suffices to get Images.jl (which uses `@ngenerate` heavily, as well as `@nsplat`) to pass its tests.

**Comment by Jutho** [comment]
Looks great. As soon as this gets merged, I will revisit the problem of implementing a more general/more efficient version of `permutedims!`.

**Comment by JeffBezanson** [comment]
Nice net deletion!

**Comment by timholy** [comment]
Thanks.

I'm traveling over the next few days, so I'll hold off on merging this until I can deal with any problems that arise.

**Comment by IainNZ** [comment]
This broke an impressive amount of packages (sorry for delayed reaction), but I think it comes down to StatsBase.jl - https://github.com/JuliaStats/StatsBase.jl/issues/106

**Comment by timholy** [comment]
I'm not remotely surprised. Looks like @simonster has fixed the problem in StatsBase, and as long as a new version has been tagged things should clear out tomorrow.

Still may be some individual ones that need fixing, like https://github.com/tlycken/Interpolations.jl/issues/21#issuecomment-73430227

**Comment by IainNZ** [comment]
Certainly one of the easier fixes! Its nice to see things breaking again :D

**Comment by simonster** [comment]
This also breaks DataArrays even though it's using Compat. I haven't dug into why yet. I see some ambiguity warnings that weren't there before:

```
Warning: New definition 
    getindex(DataArrays.DataArray{T,N},Union(AbstractArray{T,1},Real)...) at /home/simon/.julia/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(DataArrays.AbstractDataArray{T,N},Real) at /home/simon/.julia/DataArrays/src/indexing.jl:104.
To fix, define 
    getindex(DataArrays.DataArray{T,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.DataArray{T,N},Union(AbstractArray{T,1},Real)...) at /home/simon/.julia/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(AbstractArray{T,N},Real) at abstractarray.jl:434.
To fix, define 
    getindex(DataArrays.DataArray{T,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Union(AbstractArray{T,1},Real)...) at /home/simon/.julia/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(DataArrays.AbstractDataArray{T,N},Real) at /home/simon/.julia/DataArrays/src/indexing.jl:104.
To fix, define 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Real)
before the new definition.
Warning: New definition 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Union(AbstractArray{T,1},Real)...) at /home/simon/.julia/Compat/src/ngenerate.jl:53
is ambiguous with: 
    getindex(AbstractArray{T,N},Real) at abstractarray.jl:434.
To fix, define 
    getindex(DataArrays.PooledDataArray{T,R<:Integer,N},Real)
before the new definition.
```

and then this throws an error (with a somewhat bogus-looking backtrace):

```
julia> DataArray(randn(100))[1:100]
ERROR: UndefVarError: I_1 not defined
 in anonymous at /home/simon/.julia/DataArrays/src/indexing.jl:30
 in _getindex at /home/simon/.julia/DataArrays/src/indexing.jl:141
 in getindex at /home/simon/.julia/DataArrays/src/indexing.jl:152
```

**Pull request merged**
