### PR TITLE
Upgrade to Documenter 0.22.1.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
cc @mortenpi

**Comment by mortenpi** [comment]
It looks like the failures are unrelated. Shoulw we just restart the builds? Although the [Travis failure](https://travis-ci.org/JuliaLang/julia/jobs/512538898#L1748-L1757), which happens only on the 64-bit Linux buildbot, is weird:

```
[ Info: CheckDocument: running document checks.
ERROR: Error while loading expression starting at /home/travis/build/JuliaLang/julia/doc/make.jl:170
caused by [exception 1]
MethodError: no method matching namemap(::Type{Main.##doctest-#760.Color})
The applicable method may be too new: running in world age 26000, while current world is 26996.
Closest candidates are:
  namemap(::Type{Main.##doctest-#760.Color}) at Enums.jl:189 (method too new to be called from this world context.)
  namemap(::Type{Base.MPFR.MPFRRoundingMode}) at Enums.jl:189
  namemap(::Type{LibGit2.Consts.OBJECT}) at Enums.jl:189
  ...
```

**Comment by fredrikekre** [comment]
Probably a bug in Documenter then.

**Comment by mortenpi** [comment]
I'll see if it happens locally too. Weird that it would only happen on 64-bit though..

**Comment by fredrikekre** [comment]
Probably we need this:
```diff
diff --git a/src/Expanders.jl b/src/Expanders.jl
index 5955d8f8..5b16a17b 100644
--- a/src/Expanders.jl
+++ b/src/Expanders.jl
@@ -573,7 +573,7 @@ function Selectors.runner(::Type{ExampleBlocks}, x, page, doc)
     # Only add content when there's actually something to add.
     isempty(input)  || push!(content, Markdown.Code("julia", input))
     if result === nothing
-        code = Documenter.DocTests.sanitise(buffer)
+        code = Base.invokelatest(Documenter.DocTests.sanitise, buffer)
         isempty(code) || push!(content, Markdown.Code(code))
     elseif !isempty(output)
         push!(content, output)
```

> Weird that it would only happen on 64-bit though..

We are only building the docs with doctests on 64-bit, so that is probably why?

**Comment by mortenpi** [comment]
Actually, I think we need an `invokelatest` for the `show` in `result_to_string`. The problem is in doctesting and `sanitise` shouldn't get outdated anyway.

> We are only building the docs with doctests on 64-bit, so that is probably why?

That would indeed explain it.

**Pull request merged**
