### PR TITLE
Cleanup `copy_oftype`-like functions in factorizations

### LINKED ISSUE #295: `lu(A::AbstractMatrix{Taylor1{T}})` method not properly inferred in Julia v1.8
`lu(A::AbstractMatrix{Taylor1{T}})` method [here](https://github.com/JuliaDiff/TaylorSeries.jl/blob/427356d25b9340d1b92405ab03861dd0aa160614/src/arithmetic.jl#L629) is not properly inferred in Julia v1.8 (currently nightly), which is the reason for [this error](https://github.com/JuliaDiff/TaylorSeries.jl/runs/4402072888?check_suite_focus=true#step:6:75) in the tests. (The error *is* silent due to [this](https://github.com/JuliaDiff/TaylorSeries.jl/blob/427356d25b9340d1b92405ab03861dd0aa160614/.github/workflows/ci.yml#L50) line.)

The following illustrates the problem:
```julia
julia> versioninfo()
Julia Version 1.8.0-DEV.1221
Commit 98b485e064 (2022-01-05 22:00 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

julia> using LinearAlgebra, SparseArrays

julia> t = Taylor1(5)
 1.0 t + 𝒪(t⁶)

julia> a = Diagonal(rand(0:10,3)) + rand(3, 3);

julia> b = Taylor1.(a, 5);

julia> @which lu(b)
lu(A::StridedMatrix{T} where T) in LinearAlgebra at /usr/local/julia/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/lu.jl:79
```

For comparison, in Julia v1.7.1, the last line yields
```julia
julia> @which lu(b)
lu(A::AbstractArray{Taylor1{T}, 2}; check) where T<:Number in TaylorSeries at /Users/benet/.julia/dev/TaylorSeries/src/arithmetic.jl:629
```

Refs: #281, #284, and older #221, #223

@dkarrasch @daanhb Maybe you have a suggestion for this...

### LINKED ISSUE #375: lufact fails for Diagonal, Bidiagonal, and SymTridiagonal
`lufact` fails for `Diagonal`, `Bidiagonal`, and `SymTridiagonal` matrices. (I realize the former two are in factored form and LDLt is a better choice for `SymTridiagonal`.) Contrast with `qrfact`, which succeeds for all such types. (The difference seems to be that [`qrfact` calls `similar` to construct necessary fully mutable containers](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/qr.jl#L176), whereas [`lufact` merely copies the input matrix](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/lu.jl#L81). The fix may be as simple as replacing the `copy` with `similar` and an appropriate type computation.) Ref. JuliaLang/LinearAlgebra.jl#136. Best!

``` julia
julia> VERSION
v"0.6.0-dev.979"

julia> lufact(Diagonal(ones(4)))
ERROR: MethodError: no method matching lufact!(::Diagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Diagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(Bidiagonal(fill(2, 4), ones(3), true))
ERROR: MethodError: no method matching lufact!(::Bidiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Bidiagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(SymTridiagonal(fill(2, 4), ones(3)))
ERROR: MethodError: no method matching lufact!(::SymTridiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::SymTridiagonal{Float64}) at ./linalg/lu.jl:81
```

### LINKED ISSUE #18970: lufact fails for Diagonal, Bidiagonal, and SymTridiagonal
`lufact` fails for `Diagonal`, `Bidiagonal`, and `SymTridiagonal` matrices. (I realize the former two are in factored form and LDLt is a better choice for `SymTridiagonal`.) Contrast with `qrfact`, which succeeds for all such types. (The difference seems to be that [`qrfact` calls `similar` to construct necessary fully mutable containers](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/qr.jl#L176), whereas [`lufact` merely copies the input matrix](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/lu.jl#L81). The fix may be as simple as replacing the `copy` with `similar` and an appropriate type computation.) Ref. #8001. Best!

``` julia
julia> VERSION
v"0.6.0-dev.979"

julia> lufact(Diagonal(ones(4)))
ERROR: MethodError: no method matching lufact!(::Diagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Diagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(Bidiagonal(fill(2, 4), ones(3), true))
ERROR: MethodError: no method matching lufact!(::Bidiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Bidiagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(SymTridiagonal(fill(2, 4), ones(3)))
ERROR: MethodError: no method matching lufact!(::SymTridiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::SymTridiagonal{Float64}) at ./linalg/lu.jl:81
```

### PR DESCRIPTION
**Pull request by dkarrasch**
Minor cleanup after JuliaLang/julia#40831. 

I don't think we need non-mutating `lu`- and `schur`-methods with `StridedMatrix` type in their signature. `copy(::StridedMatrix)` does the same as `copy_similar(::StridedMatrix)`, so that reduces the number of needed methods.

Closes https://github.com/JuliaDiff/TaylorSeries.jl/issues/295

This now also closes JuliaLang/LinearAlgebra.jl#375 in a much less verbose way than JuliaLang/julia#41288.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["TaylorSeries"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43700#issuecomment-1007361547) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/76cc034_vs_cbf6c1c/report.html).

**Comment by dkarrasch** [comment]
Pinging @daanhb @andreasnoack

**Comment by daanhb** [comment]
This looks good to me. It is definitely good to reduce the number of the copy_X functions. For the issue with TaylorSeries, I think a problem might still remain if you supply a symmetric matrix with a different eltype (see my comment in #40831, I had replied there before seeing this)?

**Comment by dkarrasch** [comment]
I picked up your proposal in the upcoming commit to this PR. I believe we will want get rid of `copy_toarray` (or, equivalently, `Array{S}(A)`), since packages that have their own array hierarchy, like CuArray, may want to obtain their own most generic array type, and not necessarily a plain `Array`.

**Review by andreasnoack — APPROVED** [review]

**Pull request merged**
