### PR TITLE
Bump LibCURL to 7.78.0

### PR DESCRIPTION
**Pull request by bluesmoon**
This is a followup to https://github.com/JuliaPackaging/Yggdrasil/pull/3575
bumping LibCURL in stdlibs as well.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
You'll need to:
1. Delete the old checksums
2. Add the new checksums
3. Use `contrib/refresh_checksums.mk` to correctly pack the checksums into the appropriate files.

**Comment by staticfloat** [comment]
Note that steps 2 and 3 are both done by running `contrib/refresh_checksums.mk`.

**Comment by bluesmoon** [comment]
Ok, that's going to be hard to do since I don't have julia checked out locally. I'm making the changes via the github web UI. I use Julia 1.5 locally which does not have LibCURL built into stdlib.

**Comment by staticfloat** [comment]
I did it for you.

**Comment by bluesmoon** [comment]
Thank you :)

**Comment by StefanKarpinski** [comment]
Thank you guys for doing this!

**Comment by ViralBShah** [comment]
We are now on 7.81.

**Pull request closed without merging**
