### PR TITLE
Upgrade to LLVM v8.0.1

### LINKED ISSUE #31921: Misattributed profile information
Reproducer:
```
using Base.Cartesian
using Profile

data = zeros(10_000, 10_000);

@generated function ohmy(data, op::Op, ::Val{N}) where {Op, N}
  return quote
    Base.@_propagate_inbounds_meta
      @nloops $N i n -> 1:size(data, n) begin
         I = CartesianIndex(@ntuple $N i)
         data[I] = op(data[I])
       end
    end
end

N=1000; @profile for i in 1:N; ohmy(data, +, Val(2)) end
```

Produces something like:

```
julia> Profile.print()
27160 ./task.jl:268; (::getfield(REPL, Symbol("##26#27")){REPL.REPLBackend})()
 27160 ...churavy/builds/julia/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:118; macro expansion
  27160 ...churavy/builds/julia/usr/share/julia/stdlib/v1.3/REPL/src/REPL.jl:86; eval_user_input(::Any, ::REPL.REPLBackend)
   27160 ./boot.jl:330; eval(::Module, ::Any)
    27160 ...y/builds/julia/usr/share/julia/stdlib/v1.3/Profile/src/Profile.jl:25; top-level scope
     27159 ./REPL[25]:1; macro expansion
      2553  ./REPL[4]:2; ohmy(::Array{Float64,2}, ::typeof(+), ::Val{2})
       2553 ./REPL[4]:4; macro expansion
        26   ./array.jl:729; macro expansion
        2348 ./cartesian.jl:64; macro expansion
         2348 ./REPL[4]:6; macro expansion
          2348 ./multidimensional.jl:486; getindex
           2348 ./array.jl:729; getindex
        177  ./cartesian.jl:65; macro expansion
         1   ./range.jl:595; iterate
          1 ./promotion.jl:403; ==
         176 ./range.jl:596; iterate
          176 ./int.jl:53; +
        2    ./int.jl:53; macro expansion
      3159  ./array.jl:0; ohmy(::Array{Float64,2}, ::typeof(+), ::Val{2})
      21428 ./cartesian.jl:65; ohmy(::Array{Float64,2}, ::typeof(+), ::Val{2})
```

The last line is attributed `./cartesian.jl` instead of `[REPL]`. So the nesting of the information got broken and so the ticks are missattributed.

cc: @peterahrens

### PR DESCRIPTION
**Pull request by staticfloat**
Upgrade to LLVM v8.0.1, with BinaryBuilder tarballs to match.

edit: closes https://github.com/JuliaLang/julia/issues/31921

### CODE REVIEW

**Comment by staticfloat** [comment]
Welp, at least the whitespace check passed.

- [ ] We need to update the `analyzegc` pass to look at the right header location, as well as change some of the source.
- [ ] The LLVM build system seems to only install `libLLVM.so`, while `libjulia` has linked against `libLLVM-8.so`.  Interesting.
- [ ] Win32 is segfaulting during bootstrap

**Comment by vchuravy** [comment]
Thanks Elliot!

> The LLVM build system seems to only install libLLVM.so, while libjulia has linked against libLLVM-8.so. Interesting.

Aren't we pulling that from `llvm-config`?

**Comment by vchuravy** [comment]
I fixed the source for `GCChecker` just now.

**Comment by vchuravy** [comment]
@Keno added three patches for wasm that we will need to pull as well.
https://github.com/JuliaLang/julia/blob/442d1599e62b1a3a453bd0c28c9a795e09e939ff/deps/llvm.mk#L442-L444

**Comment by staticfloat** [comment]
[We aren't building WASM at the moment](https://github.com/staticfloat/LLVMBuilder/blob/master/build_tarballs.jl#L158-L160) (a holdover from when LLVMBuilder was used for `LLVM.jl` and not for base Julia and having WASM enabled caused compatibility issues) but we could.  Should I rebuild tarballs with WASM enabled?

**Comment by Keno** [comment]
The wasm code generator is unlikely to be mature enough for our use until at least LLVM 9.0 (maybe 10.0). However, we do still link the LLVM support libraries, so we need those patches even absent the wasm target.

**Comment by vchuravy** [comment]
AnalyzeGC now fails in interesting ways, it finds one unrooted things and one null pointer dereference (locally it found two unrooted things). @keno can you take a look if those are genuine or false-positives?

**Comment by tshort** [comment]
It'd be nice to get in the address space patches for WebAssembly from https://github.com/JuliaLang/julia/pull/32734.

**Comment by tshort** [comment]
I'd also like to see the WASM target included.

**Comment by staticfloat** [comment]
When talking about the WASM backend with @keno and @vchuravy, I was under the impression that it's pretty broken (for our purposes) until at least LLVM v9+.  Why do you want the WASM backend for LLVM v8?

**Comment by tshort** [comment]
I'd love to hear more about what's broken and what improvements are coming. For playing with basic static compilation, what's in v8 may be sufficient. That said, waiting for v9 is fine (it'll be here pretty soon).

Note that a source compilation of master Julia has the address-space patches and the WebAssembly target for v8.

**Comment by Keno** [comment]
There were many bugs between LLVM 8 and LLVM 9. LLVM seems fairly stable, but needs at least https://reviews.llvm.org/D65463 and https://reviews.llvm.org/D65470 in addition when fed with the LLVM IR that julia generates.

**Comment by vchuravy** [comment]
The win32 is readily reproducible:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x09a50013 in japi1_top-level scope_0 ()
(gdb) bt
#0  0x09a50013 in japi1_top-level scope_0 ()
#1  0x6ca69e79 in jl_fptr_args (f=0x0, args=0x0, nargs=0, m=0x7e26590) at /home/User/julia/src/gf.c:1809
#2  0x6ca6abba in _jl_invoke (F=0x0, args=0x0, nargs=0, mfunc=0x7e36650, world=1) at /home/User/julia/src/gf.c:2049
#3  0x6ca6ac45 in jl_invoke (F=0x0, args=0x0, nargs=0, mfunc=0x7e36650) at /home/User/julia/src/gf.c:2056
#4  0x6caa6973 in jl_toplevel_eval_flex (m=0x7e40010, e=0x7e31d30, fast=1, expanded=1) at /home/User/julia/src/toplevel.c:808
#5  0x6ca7474d in jl_parse_eval_all (fname=0x6cd79bc3 <szclass_table+1411> "boot.jl", content=0x0, contentlen=0, inmodule=0x7e40010) at /home/User/julia/src/ast.c:873
#6  0x6caa6dcd in jl_load (module=0x7e40010, fname=0x6cd79bc3 <szclass_table+1411> "boot.jl") at /home/User/julia/src/toplevel.c:878
#7  0x6ca871fb in _julia_init (rel=JL_IMAGE_JULIA_HOME) at /home/User/julia/src/init.c:785
#8  0x6ca8835e in julia_init__threading (rel=JL_IMAGE_JULIA_HOME) at /home/User/julia/src/task.c:229
#9  0x00401e97 in wmain (argc=1, argv=0x6367028, envp=0x6376f70) at /home/User/julia/ui/repl.c:211
#10 0x0040139d in __tmainCRTStartup () at /usr/src/debug/mingw64-i686-runtime-6.0.0-1/crt/crtexe.c:334
#11 0x76290419 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/Windows/System32/KERNEL32.DLL
#12 0x770a662d in ntdll!RtlGetAppContainerNamedObjectPath () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#13 0x770a65fd in ntdll!RtlGetAppContainerNamedObjectPath () from /cygdrive/c/Windows/SYSTEM32/ntdll.dll
#14 0x00000000 in ?? ()
```

```
(gdb) disassemble
Dump of assembler code for function japi1_top-level scope_0:
   0x09a50000 <+0>:     push   %ebp
   0x09a50001 <+1>:     mov    %esp,%ebp
   0x09a50003 <+3>:     push   %ebx
   0x09a50004 <+4>:     push   %edi
   0x09a50005 <+5>:     push   %esi
   0x09a50006 <+6>:     and    $0xfffffff0,%esp
   0x09a50009 <+9>:     sub    $0x70,%esp
   0x09a5000c <+12>:    mov    0xc(%ebp),%eax
   0x09a5000f <+15>:    mov    0x38(%esp),%ecx
=> 0x09a50013 <+19>:    mov    0x68cc5004(%ecx),%edx
   0x09a50019 <+25>:    mov    (%edx),%edx
   0x09a5001b <+27>:    xor    %ebp,%edx
   0x09a5001d <+29>:    mov    %edx,0x68(%esp)
   0x09a50021 <+33>:    xorps  %xmm0,%xmm0
   0x09a50024 <+36>:    movaps %xmm0,0x40(%esp)
   0x09a50029 <+41>:    movl   $0x0,0x50(%esp)
   0x09a50031 <+49>:    mov    %eax,0x3c(%esp)
   0x09a50035 <+53>:    mov    $0x6cabb170,%eax
```

```
(gdb) info registers
eax            0x0      0
ecx            0xcbf820 13367328
edx            0x0      0
ebx            0x8ebde6f        149675631
esp            0xcbf7c0 0xcbf7c0
ebp            0xcbf848 0xcbf848
esi            0x76c9d8e        124558734
edi            0x358    856
eip            0x9a50013        0x9a50013 <japi1_top-level scope_0+19>
eflags         0x10206  [ PF IF RF ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x53     83
gs             0x2b     43
```

```
        0x68cc5000 - 0x68cc53b4 is .bss in /home/User/win32/usr/bin/libssp-0.dll
(gdb) p/x ($ecx +  0x68cc5004)
$22 = 0x69984824
```
which is outside a mapped region, hence the seqfault.

@vtjnash/@keno does this trigger any memories?

```

**Comment by vchuravy** [comment]
We also need to add the patches we figured out when fixing BinaryBuilder.
- [ ] https://github.com/staticfloat/LLVMBuilder/blob/master/patches/llvm_patches/0010-llvm-exegesis-mingw.patch
- [ ] https://github.com/staticfloat/LLVMBuilder/blob/master/patches/llvm_patches/0011-llvm-test-plugin-mingw.patch

Otherwise people who build from source on Mingw (e.g. me) will encounter them again

**Comment by vchuravy** [comment]
Okay now both Win32 and Win64 fail with:

```
ERROR: could not load library "C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\lib\julia\sys.dll"
%1 is not a valid Win32 application.
```

**Comment by Keno** [comment]
@vchuravy asked me to leave this here:
```
diff --git a/src/jltypes.c b/src/jltypes.c
index 66aeeae..4728e63 100644
--- a/src/jltypes.c
+++ b/src/jltypes.c
@@ -1043,7 +1043,7 @@ static void check_datatype_parameters(jl_typename_t *tn, jl_value_t **params, si
 arraylist_t partial_inst;
 int inside_typedef = 0;

-static jl_value_t *extract_wrapper(jl_value_t *t)
+static jl_value_t *extract_wrapper(jl_value_t *t JL_PROPAGATES_ROOT)
 {
     t = jl_unwrap_unionall(t);
     if (jl_is_datatype(t))
```

**Comment by vchuravy** [comment]
Yay! (We might want to consider going straight to LLVM 9 though, which was just released today)

**Comment by staticfloat** [comment]
I was talking to Keno about that; he seemed happier to be on a `X.Y.1` release than a `X.Y.0` release; less chance of bugs, and not that many things in LLVM 9 that we're interested in.  Talking to Tim though, I hear there are GPU goodies that we might be interested in.

**Comment by staticfloat** [comment]
I think something is going wrong with `sys.dll` on windows?

**Comment by staticfloat** [comment]
Huh, in the rebase I just did, a bunch of patch commits disappeared, but I suppose that is because the patches have already been merged into `master`?

**Comment by vchuravy** [comment]
> Talking to Tim though, I hear there are GPU goodies that we might be interested in.

In particular I am after decent debug-information for GPU kernels and better profiling.

> Huh, in the rebase I just did, a bunch of patch commits disappeared, but I suppose that is because the patches have already been merged into master?

Jup, x-ref #33018

> I think something is going wrong with sys.dll on windows?

I would hope not, did the BB apply `llvm7-revert-D44485`?

**Comment by staticfloat** [comment]
> I would hope not, did the BB apply `llvm7-revert-D44485` ?

```
Applying patch /workspace/srcdir/llvm_patches/0016-llvm7-revert-D44485.patch                                                                             
patching file lib/MC/WinCOFFObjectWriter.cpp                                                                                                             
Hunk #1 succeeded at 681 (offset -9 lines).
```

Looks like it did to me.

**Comment by staticfloat** [comment]
Oh, huh, the windwos buildbots made it past bootstrap this time.  I don't know what that other error message I was seeing was, let's blame buildbot.

**Comment by vchuravy** [comment]
@keno can you take another look at analyzegc?

**Comment by vtjnash** [comment]
anyone know why it can't find the c++ headers? if not, I'll just put that commit on a new PR

**Comment by vchuravy** [comment]
> anyone know why it can't find the c++ headers? if not, I'll just put that commit on a new PR

Probably better to do that, since it is unrelated from this PR.

**Review by vchuravy — APPROVED** [review]

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32712#issuecomment-555938570) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/8fb8c1a163af5029bcb280bb390c539bfd4c4b70/1201ad5_vs_0a27781/report.md). cc @ararslan

**Comment by vchuravy** [comment]
Yay! Onwards to LLVM 9.

**Comment by chriselrod** [comment]
A tangible benefit* to LLVM 9 is that while the LLVM 8 documentation mentions [expandload](https://releases.llvm.org/8.0.0/docs/LangRef.html#llvm-masked-expandload-intrinsics) and [compressstore](https://releases.llvm.org/8.0.0/docs/LangRef.html#llvm-masked-compressstore-intrinsics), both of these intrinsics caused a crash on a Haswell cluster with the message
```
LLVM ERROR: Cannot select: 0x2a43b50: v4f64,ch = masked_load<(load 32 from %ir.ptr.i)> 0x26e3c78, 0x2fb7538, 0x2a3fcf8, 0x2ed9e40, /home/c285497/.julia/dev/SIMDPirates/src/memory.jl:823 @[ /home/c285497/.julia/dev/SIMDPirates/src/memory.jl:802 ]
```
Yet these functions work on a build with LLVM 9.
```julia
julia> versioninfo()
Julia Version 1.4.0-DEV.513
Commit 8f7855a* (2019-11-21 01:58 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.0 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 24

julia> @time using SIMDPirates
  1.459145 seconds (1.64 M allocations: 88.784 MiB, 1.63% gc time)

julia> x = ntuple(Val(4)) do i Core.VecElement(randn()) end
(VecElement{Float64}(0.15844536654536248), VecElement{Float64}(1.3029855351761224), VecElement{Float64}(-0.5349914246588564), VecElement{Float64}(0.4026832110654877))

julia> y = collect(1.0:99.0);

julia> SIMDPirates.expandload!(Vec{4,Float64}, pointer(y), UInt8(5))
(VecElement{Float64}(1.0), VecElement{Float64}(0.0), VecElement{Float64}(2.0), VecElement{Float64}(0.0))

julia> SIMDPirates.compressstore!(pointer(y), x, UInt8(5))

julia> y'
1×99 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.158445  -0.534991  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0  21.0  22.0  23.0  24.0  25.0  26.0  27.0  28.0  29.0  30.0  31.0  32.0  33.0  34.0  35.0  36.0  37.0  38.0  39.0  40.0  …  60.0  61.0  62.0  63.0  64.0  65.0  66.0  67.0  68.0  69.0  70.0  71.0  72.0  73.0  74.0  75.0  76.0  77.0  78.0  79.0  80.0  81.0  82.0  83.0  84.0  85.0  86.0  87.0  88.0  89.0  90.0  91.0  92.0  93.0  94.0  95.0  96.0  97.0  98.0  99.0

julia> @code_native debuginfo=:none SIMDPirates.expandload!(Vec{4,Float64}, pointer(y), UInt8(5))
        .text
        vmovd   %edx, %xmm0
        andl    $1, %edx
        vmovd   %edx, %xmm2
        movabsq $.rodata.cst16, %rax
        vmovdqa (%rax), %xmm1
        vpbroadcastd    %xmm0, %xmm0
        vpand   %xmm1, %xmm0, %xmm0
        vpcmpeqd        %xmm1, %xmm0, %xmm0
        vpsrld  $31, %xmm0, %xmm1
        vpextrb $0, %xmm2, %eax
        testb   %al, %al
        je      L73
        vmovq   (%rsi), %xmm0           # xmm0 = mem[0],zero
        addq    $8, %rsi
        vpextrb $4, %xmm1, %eax
        cmpb    $1, %al
        jne     L101
        jmp     L87
L73:
        vpxor   %xmm0, %xmm0, %xmm0
        vpextrb $4, %xmm1, %eax
        cmpb    $1, %al
        jne     L101
L87:
        vmovhps (%rsi), %xmm0, %xmm2    # xmm2 = xmm0[0,1],mem[0,1]
        vpblendd        $15, %ymm2, %ymm0, %ymm0 # ymm0 = ymm2[0,1,2,3],ymm0[4,5,6,7]
        addq    $8, %rsi
L101:
        vpextrb $8, %xmm1, %eax
        cmpb    $1, %al
        je      L122
        vpextrb $12, %xmm1, %eax
        cmpb    $1, %al
        je      L152
L121:
        retq
L122:
        vextracti128    $1, %ymm0, %xmm2
        vmovlps (%rsi), %xmm2, %xmm2    # xmm2 = mem[0,1],xmm2[2,3]
        vinserti128     $1, %xmm2, %ymm0, %ymm0
        addq    $8, %rsi
        vpextrb $12, %xmm1, %eax
        cmpb    $1, %al
        jne     L121
L152:
        vextracti128    $1, %ymm0, %xmm1
        vmovhps (%rsi), %xmm1, %xmm1    # xmm1 = xmm1[0,1],mem[0,1]
        vinserti128     $1, %xmm1, %ymm0, %ymm0
        retq
        nopl    (%rax)

julia> @code_native debuginfo=:none SIMDPirates.compressstore!(pointer(y), x, UInt8(5))
        .text
        vmovd   %esi, %xmm1
        andl    $1, %esi
        vmovd   %esi, %xmm2
        movabsq $.rodata.cst16, %rax
        vmovdqa (%rax), %xmm3
        vpbroadcastd    %xmm1, %xmm1
        vpand   %xmm3, %xmm1, %xmm1
        vpcmpeqd        %xmm3, %xmm1, %xmm1
        vpsrld  $31, %xmm1, %xmm1
        vpextrb $0, %xmm2, %eax
        testb   %al, %al
        jne     L93
        vpextrb $4, %xmm1, %eax
        cmpb    $1, %al
        je      L111
L63:
        vpextrb $8, %xmm1, %eax
        vextractf128    $1, %ymm0, %xmm0
        cmpb    $1, %al
        je      L135
L79:
        vpextrb $12, %xmm1, %eax
        cmpb    $1, %al
        je      L153
L89:
        vzeroupper
        retq
L93:
        vmovlps %xmm0, (%rdi)
        addq    $8, %rdi
        vpextrb $4, %xmm1, %eax
        cmpb    $1, %al
        jne     L63
L111:
        vmovhps %xmm0, (%rdi)
        addq    $8, %rdi
        vpextrb $8, %xmm1, %eax
        vextractf128    $1, %ymm0, %xmm0
        cmpb    $1, %al
        jne     L79
L135:
        vmovlps %xmm0, (%rdi)
        addq    $8, %rdi
        vpextrb $12, %xmm1, %eax
        cmpb    $1, %al
        jne     L89
L153:
        vmovhps %xmm0, (%rdi)
        vzeroupper
        retq
        nopw    %cs:(%rax,%rax)
        nopl    (%rax,%rax)
```

Haswell obviously isn't one of the targets that support efficient expand loads or compress stores, but it's nice to have things work.

*Impacting approximately 0% of users.

**Comment by vtjnash** [comment]
This was only for LLVM 8. For LLVM 9, you want https://github.com/JuliaLang/julia/pull/33916.

**Pull request merged**
