### PR TITLE
[release 0.5] hack in a fix to getting the right lambda for the incremental deserializer

### LINKED ISSUE #18449: Type inference error due to precompilation
`A.jl`
```jl
__precompile__()

module A
function f1()
    warn("")
end
precompile(f1, ())
end
```

`B.jl`
```jl
__precompile__()

module B
function f2()
    warn("")
end
precompile(f2, ())
end
```

`runtests.jl` (in the same directory as `A.jl` and `B.jl`)
```jl
#

unshift!(Base.LOAD_PATH, dirname(@__FILE__))

using B
using A

B.f2()
A.f1()
```

Running on current master gives,

```
WARNING: 
WARNING: An error occurred during inference. Type inference is now partially disabled.
ErrorException("type inference data-flow error: tried to double infer a function")
rec_backtrace at /build/julia-git/src/julia-avx2/src/stackwalk.c:84
record_backtrace at /build/julia-git/src/julia-avx2/src/task.c:238
jl_throw at /build/julia-git/src/julia-avx2/src/task.c:560
abstract_eval at ./inference.jl:1186
unknown function (ip: 0x7fee9cbdb506)
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
abstract_interpret at ./inference.jl:1238
unknown function (ip: 0x7fee9cbd9c26)
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
typeinf_frame at ./inference.jl:1733
typeinf_loop at ./inference.jl:1679
unknown function (ip: 0x7fee9cbd95db)
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
typeinf_edge at ./inference.jl:1598
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
typeinf_ext at ./inference.jl:1622
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
jl_apply at /build/julia-git/src/julia-avx2/src/julia.h:1364 [inlined]
jl_type_infer at /build/julia-git/src/julia-avx2/src/gf.c:212
emit_invoke at /build/julia-git/src/julia-avx2/src/codegen.cpp:2724 [inlined]
emit_expr at /build/julia-git/src/julia-avx2/src/codegen.cpp:3190
emit_function at /build/julia-git/src/julia-avx2/src/codegen.cpp:4792
jl_compile_linfo at /build/julia-git/src/julia-avx2/src/codegen.cpp:810
jl_compile_for_dispatch at /build/julia-git/src/julia-avx2/src/gf.c:1312
jl_call_method_internal at /build/julia-git/src/julia-avx2/src/julia_internal.h:180
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
do_call at /build/julia-git/src/julia-avx2/src/interpreter.c:66
eval at /build/julia-git/src/julia-avx2/src/interpreter.c:205
jl_interpret_toplevel_expr at /build/julia-git/src/julia-avx2/src/interpreter.c:31 [inlined]
jl_toplevel_eval_flex at /build/julia-git/src/julia-avx2/src/toplevel.c:619
jl_parse_eval_all at /build/julia-git/src/julia-avx2/src/ast.c:735
jl_load at /build/julia-git/src/julia-avx2/src/toplevel.c:657
jl_load_ at /build/julia-git/src/julia-avx2/src/toplevel.c:666
include_from_node1 at ./loading.jl:541
unknown function (ip: 0x7fee9cd0864b)
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
process_options at ./client.jl:262
_start at ./client.jl:326
unknown function (ip: 0x7fee9cd2e308)
jl_apply_generic at /build/julia-git/src/julia-avx2/src/gf.c:1944
unknown function (ip: 0x40181c)
unknown function (ip: 0x401276)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 0x4012d9)
WARNING: 
```

This causes a failure in Gadfly test.
Doesn't happen on 0.4 or 0.5.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #18449
(the real, non-buggy fix is in #18413 for v0.6-dev master)

### CODE REVIEW

**Comment by yuyichao** [comment]
Note that #18449 does not trigger on 0.5.

**Comment by vtjnash** [comment]
oh, I guess this also needs https://github.com/JuliaLang/julia/pull/18415 backported first too

**Comment by tkelman** [comment]
can you add a test? I saw this error on gadfly and mamba in #18546, will upload logs soon

**Comment by tkelman** [comment]
Old travis logs backed up to
- https://gist.github.com/e7f9adec6b3f077acc11a6ffc55de68e
- https://gist.github.com/9a56907516fdf7d6366c79241ad3e1c8
- https://gist.github.com/158c194d81a2039fe71dec17cf8e832c

and restarted. May need to merge this into tk/backports-0.5.0 before @vtjnash (or @yuyichao?) wakes up and can identify if there's already an appropriate test for this on master or if a new one needs to be written. We'll still need a test for release-0.5 but I won't block starting my next pkgeval run on it.

**Comment by tkelman** [comment]
Master needs the test too, so we'll do that in a new PR and backport whenever it's ready.

**Pull request merged**
