### PR TITLE
fix #31758: out of bounds write in sparse broadcast

### LINKED ISSUE #31758: Out of bounds write in sparse broadcast
Reduced from https://discourse.julialang.org/t/signal-11-segmentation-fault-11-with-differentialequations-jl/23264/:
```julia
y = sparsevec([2,7], [1., 2.], 10)
x1 = sparsevec(fill(1.0, 10))
x2 = sparsevec([2,7], [1., 2.], 10)
x3 = sparsevec(fill(1.0, 10))
f(x, y, z) = x == y == z == 0 ? 0.0 : NaN
bc = Broadcast.broadcasted(f, x1, x2, x3)

Broadcast.materialize!(y, bc)
```
where the last line causes a segfault (`BoundsError` with `--check-bounds=yes`). The problem is here: https://github.com/JuliaLang/julia/blob/c83e31265cf6e3b3d777847a653074dd5875c6d7/stdlib/SparseArrays/src/higherorderfns.jl#L390 where we fail to expand the storage since the calculation for needed storage is wrong, and returns `1` in this particular case. From Debugger:
```
1|debug> n
In _map_zeropres!(f, C, As) at /julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:372
 382  while activerow < rowsentinel
 383      vals, ks, rows = _fusedupdate_all(rowsentinel, activerow, rows, ks, stopks, As)
 384      Cx = f(vals...)
 385      if !_iszero(Cx)
>386          Ck > spaceC && (spaceC = expandstorage!(C, Ck + min(length(C), _sumnnzs(As...)) - (sum(ks) - N)))
 387          storedinds(C)[Ck] = activerow
 388          storedvals(C)[Ck] = Cx
 389          Ck += 1
 390      end

1|debug> w
1] Ck: 7
2] spaceC: 6
3] storedinds(C): [1, 2, 3, 4, 5, 6]
4] (Ck + min(length(C), _sumnnzs(As...))) - (sum(ks) - N): 1

1|debug> n
In _map_zeropres!(f, C, As) at /julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:372
 383  vals, ks, rows = _fusedupdate_all(rowsentinel, activerow, rows, ks, stopks, As)
 384  Cx = f(vals...)
 385  if !_iszero(Cx)
 386      Ck > spaceC && (spaceC = expandstorage!(C, Ck + min(length(C), _sumnnzs(As...)) - (sum(ks) - N)))
>387      storedinds(C)[Ck] = activerow
 388      storedvals(C)[Ck] = Cx
 389      Ck += 1
 390  end
 391  activerow = min(rows...)

1|debug> w
1] Ck: 7
2] spaceC: 1                # <-- What??
3] storedinds(C): [1, 2, 3, 4, 5, 6]
4] (Ck + min(length(C), _sumnnzs(As...))) - (sum(ks) - N): 1
```

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by mbauman** [comment]
Since it took a bit to figure out, here's Fredrik's and my understanding of what this code means to do: it's trying to get a good maximum bound for the number of remaining stored entries in the array.  We're in the zero-preserving case, so anywhere that all the arguments have zeros, the function evaluation will return zero.  Now computing the exact union across all the arguments is an expensive task.  This (over) estimates it by simply looking at the _total_ number of nonzeros in all arguments; that's `_sumnnzs(As...) `.  We can further refine that estimate because we're partway through the algorithm — we know how many total stored values we've seen in the arguments and how many stored values they ended up creating.  So we add in the total number of values we've stored so far (`Ck`) and subtract out the total number of stored values in all the arguments that led to that result (`sum(ks) - N` — the `- N` accounts for the 1-based indices across the `N` arrays).  Of course this could be more than the total possible number of elements, so we ensure it's no larger than `length(C)` with a `min`.

Put that all together and you can see that the entire estimate algorithm should all go inside the same argument of that `min` call.

**Review by mbauman — APPROVED** [review]

**Comment by mbauman** [comment]
Given that this often over-allocates, I wonder how much more efficient (or not) a simple `push!` based algorithm would be.  We also wondered how much `@inbounds` actually affects performance in such a complicated algorithm.  But those can be investigations for another day — this patch is straightforward and lets not derail it by looking into other possible algorithms.

**Comment by Sacha0** [comment]
Good catch! :)

> We also wondered how much `@inbounds` actually affects performance in such a complicated algorithm.

Depends on which `@inbounds` you are thinking of; some of them impact performance substantially. I have a now-stale perf test suite for this code somewhere that I've long wanted to package up for nanosoldier in that mythical thing that is free time... 😄

**Comment by KristofferC** [comment]
I'm surprised that the inbounds annotations have a large effect since there are almost always conditionals and non `propagate_inbounds` function calls in the loop body. Do you recall any such example?

**Comment by Sacha0** [comment]
I recall perf measurements benefitting from certain inbounds annotations, but what with the many intervening months cannot recall precisely which measurements and annotations 🤷‍♀️. IIRC I started without the annotations, but found that I needed at least some subset of them to close the gap between the then-new generic implementations and the specialized implementations that existed at the time. Best!

**Pull request merged**
