### PR TITLE
Fix #16100. Allow opting out of all `@boundscheck` blocks with `--check-bounds=no`.

### LINKED ISSUE #16100: `--check-bounds=no` does not disable all bounds checks
In #16063, it came up that running julia with `--check-bounds=no` does not disable all bounds checks, it only disables bounds checks for the `Array` type.  Should it be changed to disable all bounds check?

Having a way to disable all bounds checks would be very useful for doing production runs of a code.

### PR DESCRIPTION
**Pull request by blakejohnson**
Also now properly respect `--check-bounds=yes` for such blocks. To test it, I launch two extra processes with appropriate `execflags`. I'm not familiar with the use case of the `net_on` variable in `runtests.jl`. Is that something I should be concerned about for launching these extra processes?

### CODE REVIEW

**Comment by yuyichao** [comment]
I think the test should be in `cmdlineargs` and following the convention there.

**Comment by blakejohnson** [comment]
@yuyichao The `cmdlineargs` tests seem to be *mostly* about whether the options are passed in correctly, as opposed to whether they change the behavior of julia in the expected way. I suppose that could be a reasonable place to launch the `boundscheck` tests, though.

**Comment by amitmurthy** [comment]
`net_on` was used to allow the test suite to be run on systems with all networking disabled. Tests that require a network interface will be removed if no interface (including loopback) is available.

Should not matter for this PR.

**Comment by blakejohnson** [comment]
Appveyor failure looks unrelated; retrying.

**Comment by vtjnash** [comment]
lgtm (just needs a rebase)

**Comment by tkelman** [comment]
Won't `addprocs` not be possible when `!net_on` ? I do think cmdlineargs would be a better place for these.

**Comment by amitmurthy** [comment]
Yes, `addprocs` will fail when `!net_on`. We could just spawn these out like `parallel_exec.jl` - https://github.com/JuliaLang/julia/blob/e55f726de4d900dacf65a138614a8c9bffa1adbd/test/parallel.jl#L14-L18 . Can also spawn both in parallel, i.e., the `default` and `no` cases

**Comment by blakejohnson** [comment]
Organizationally, I understand the suggestions to put these tests with `cmdlineargs`. But, from a development perspective it is somewhat brutal since `cmdlineargs` takes about 2 minutes to run on my machine, while the `boundscheck` tests run in under 1 second.

Another problem is that this kind of incantation:
```
success(`$exename test/runtests.jl boundscheck`)
```
Simplify reveals binary pass/fail as opposed to printing out complete error information, such as the line on which it failed.

**Comment by tkelman** [comment]
it should respect net_on at least, if it's going to do addprocs. though shouldn't most of the existing boundscheck tests run fine when addprocs isn't available?

**Comment by blakejohnson** [comment]
Not really, no. Now that I am respecting the command line options, you only really test the full behavior when "--check-bounds=default".

**Comment by tkelman** [comment]
It should also respect the CPU_CORES limit. What does this branch do for `make testall1` ?

**Comment by blakejohnson** [comment]
I'll figure out a way to get it to run even with `!net_on`.

I'm not sure why `CPU_CORES` is relevant, @tkelman. That logic is in `runtests.jl` presumably because adding more cores would not speed up the test suite (and potentially even slow it down). However, it is perfectly legal to have more processes than cores, and the additional processes spooled up for the new boundscheck tests are not being added to the worker pool used by the remaining tests.

**Comment by tkelman** [comment]
we shouldn't be running more processes *in parallel* than the limit set by JULIA_CPU_CORES.

**Comment by blakejohnson** [comment]
Sure, but if you notice, the added `remotecall_fetch` calls are not within an `@async` block, so these additional processes are queried sequentially.

**Comment by blakejohnson** [comment]
I believe all the comments have been addressed (organization, `net_on`, etc) by my latest commit, so I am going to go ahead and merge.

**Pull request merged**
