### PR TITLE
Show deprecation warning module when lineinfo n/a

### PR DESCRIPTION
**Pull request by ihnorton**
> [Showing the module name is a good idea. That should be much easier.](https://github.com/JuliaLang/julia/issues/16967#issuecomment-238298982)

For #16967: show module name with syntax deprecation warning if lineinfo is not available.

Second commit fixes the embedding `Makefile` to get rid of a `cowardly refusing ...` build error.

### CODE REVIEW

**Comment by ihnorton** [comment]
This doesn't help with cross-module macro expansions, but there's [not much we can do there](https://github.com/JuliaLang/julia/issues/17770#issuecomment-237134292) for now.

(Not sure where to test this, if at all. The only deprecation tests I see are in `cmdlineargs.jl`)

**Comment by timholy** [comment]
This will be a huge help fixing deprecation warnings, thanks for tackling this! Does this work for `@deprecate_binding` as well as `@deprecate`?

I do think a test would be nice.

**Comment by ihnorton** [comment]
>  Does this work for @deprecate_binding as well as @deprecate?

Neither actually :( This is only for syntax deprecations (description updated).

**Comment by ihnorton** [comment]
Hmm, I think there are too many places where this can't be accurate because `syntax-deprecation` is called during lowering, and there is no guarantee that `current-julia-module` will be accurate/useful.

**Comment by vtjnash** [comment]
Really? I figured at least knowing the module that used a macro was roughly just as good. The value of `current-julia-module` is part of the definition of lowering and tells you exactly where that code is going to end up (needed for things like resolving `GlobalRef`, `top`, and the anonymous function counter).

**Comment by kshyatt** [comment]
What's the status on this?

**Comment by ihnorton** [comment]
Oops. Didn't mean to delete the fork while rebasing. It's [here](https://github.com/ihnorton/julia/tree/for16967). This does make a small bit of difference when confronted with the most generic of syntax deprecation warnings.

**Pull request closed without merging**
