### PR TITLE
stream.jl: Remove error when server is closed while waiting for a client to connect (shutdown HttpServer gracefully)

### PR DESCRIPTION
**Pull request by EricForgy**
In reference to:

https://groups.google.com/forum/?fromgroups=#!topic/julia-dev/0eEXAGuja4U

### CODE REVIEW

**Comment by EricForgy** [comment]
Failing tests is a bummer...

Sorry I did not test beforehand, but I have little confidence in my ability to build Julia from source and was hoping this was a harmless change.

From what I can tell, the function I modified, "stream.jl:accept" appears in three places:

1. base/stream.jl, where it is defined, but not used
2. base/socket.jl, where it is extended, but not used
3. base/multi.jl, where it is used in start_work(out::IO)

Here is the test that fails:

    p, server = listenany(defaultport)
    r = Channel(1)
    tsk = @async begin
        put!(r, :start)
        @test_throws Base.UVError accept(server)
    end
    @test fetch(r) === :start
    close(server)
    wait(tsk)

Even without building from source, I can understand why this test fails. It is basically testing that an error gets thrown when a server is closed while waiting to accept a client, but that is precisely the error I was trying to suppress. I don't understand why closing a server while waiting for a client to connect should be an error and makes it difficult to shut down a running HttpServer gracefully.

Any ideas? It looks like @Keno committed the first change here

* https://github.com/JuliaLang/julia/commit/860501f669cba02789f1aa936e0665b3f4d8a629

that throws the error and @staticfloat changed it to a UV error here:

* https://github.com/JuliaLang/julia/commit/3d940e5fb0f6d3f51f9b7df8dbf820ac5c3c6956

If there is a better way to shutdown an HttpServer gracefully, with some hints, I am happy to try to work it out myself.

Any thoughts on the subject @malmaud ?

**Comment by Keno** [comment]
Why not just catch the error message and quit gracefully? `accept` can throw other errors as well which need to be handled in some way (logged perhaps or discarded), so this situation isn't all that different.

**Comment by EricForgy** [comment]
Thanks Keno. Just to make sure I understand, you are suggesting that I put my call to 

    close(stream::Union{LibuvStream, LibuvServer})

inside a "try/catch"? That will work :)

I guess I have a bit of an allergy to "try/catch", but should be ok if you don't want to remove that UV error from "accept". Thank you :)

**Comment by Keno** [comment]
I'm suggesting in HttpServer, you put the accept call in a try/catch to handle any errors that may pop up.

**Comment by EricForgy** [comment]
Understood. Thanks. Putting the `accept` call in a try/catch will involve modifying both handle_http_request and handle_https_requests. Both of those seem fine as-is and I'm a little worried about suppressing other errors that should not be suppressed. Instead, I think I'll try to write a proper `close(server::Server)`, put the try/catch in there, and submit a PR to HttpServer.jl. How does that sound?

**Comment by Keno** [comment]
Closing. I do think we eventually need to distinguish between abnormal, but expected failures (e.g. network failures) and abnormal conditions. Right now exceptions are a bit heavy for the former, but we don't yet have another mechanism. Not indicating failure would be worse here.

**Pull request closed without merging**
