### PR TITLE
Merge pull request #1 from JuliaLang/master

### PR DESCRIPTION
**Pull request by citisolo**
update

### CODE REVIEW

**Comment by martinholters** [comment]
I suppose something went wrong here?

**Comment by tkelman** [comment]
If you've been using the github web interface to update your fork (and this wound up accidentally being backwards), note that that leaves messy merge commits that never exist upstream. It's better to stick to fast-forward pushes from the command line for updating a fork.

**Comment by citisolo** [comment]
Ok thank you for that , terribly sorry for the trouble. is there a way to reverse it ?

**Comment by tkelman** [comment]
If you want to overwrite your fork's master branch with a pristine copy of upstream master, do something like
```
git remote add JuliaLang https://github.com/JuliaLang/julia
git remote add citisolo https://github.com/citisolo/julia
git fetch JuliaLang
git checkout JuliaLang/master
git branch -D master
git checkout -b master
git push --force citisolo master
```

**Comment by citisolo** [comment]
will do that , cheers

**Comment by citisolo** [comment]
Also , I have just created a patch for an issue and am trying to push the changes to my fork, however TravisCI doesn't seem to build unless I merge my patch-branch to the master repository. Am I supposed to merge the branch to master or am I missing something here?

**Comment by tkelman** [comment]
We have a `branches: only` whitelist in the `.travis.yml` file that only runs on master and release branches (and pull requests). If you'd like to test on Travis on your fork before opening a PR here, you can temporarily add your branch name to that whitelist. Just be sure to remove that yml change before opening the PR here.

**Pull request closed without merging**
