### PR TITLE
Actually show glyphs for latex or emoji shortcodes being suggested in the REPL

### PR DESCRIPTION
**Pull request by jkrumbiegel**
When a user requests a completion for a backslash shortcode, this PR adds the glyphs for all the suggestions to the output. This makes it much easier to find the result one is looking for, especially if the user doesn't know all latex and emoji specifiers by heart.

Before:

image

After:

image

### CODE REVIEW

**Comment by jkrumbiegel** [comment]
I think the implementation is not quite right yet, it's probably not allowed/expected to have the completion start differently than what is being completed. Then you get this weird behavior once the list is narrowed down to one element:

https://github.com/JuliaLang/julia/assets/22495855/888bfdbb-e9c3-4616-8a83-da770d76feee

Would appreciate if someone in the know could comment what other mechanism should be used instead.

**Comment by Keno** [comment]
You'll need to tweak the assumption that the completion being disabled and the text to be inserted are always the name. Probably the easiest way to do that is to pull the array of completions one level higher into `complete_line(s::PromptState, repeats::Int, mod::Module)` and add split the `completion_text` generic function into display and replacement completion texts.

**Comment by jkrumbiegel** [comment]
I've introduced a `NamedCompletion` struct which for most of the existing functionality just stores the same string for name and completion. Just for backslash completions, these are different. The wacky behavior from before is gone with this change:

https://github.com/user-attachments/assets/a9d11720-9b50-4d85-acb2-e78b7863e20c

**Comment by jkrumbiegel** [comment]
Looks like CI fails because an extension of Pkg uses `REPL.REPLCompletions.completion_text` which I changed. It was exported from that submodule but I'm not sure if it was intended to be public API of REPL or not. Could someone comment on that?

**Comment by Keno** [comment]
The use in Pkg predates them being separate packages. In general, REPL does not have a public API. Either way to fix this is fine (providing a fallback for the old code or fixing Pkg at the same time).

**Comment by jkrumbiegel** [comment]
Finally returned to this PR..

I've reverted some of the changes that made the Pkg extension fail, this makes the code a little uglier due to the handling of two tuple types for `complete_line`, but as I don't know how to coordinate synchronized changes to Julia and Pkg I think it's easier to get a working version in first, then potentially refactor Pkg later if that's desired. But it might as well be that other people hooked into this functionality so while it's not public we don't _have_ to break it, which is an advantage of the current changes.

It doesn't seem to me like the two build failures on CI are related to my changes, tests seem to pass otherwise.

**Comment by DilumAluthge** [comment]
@IanButterworth Would you be able to review this PR?

**Comment by DilumAluthge** [comment]
Bump @IanButterworth Would you be able to review this?

**Comment by IanButterworth** [comment]
Sorry I'm not very familiar with this code. Perhaps the blame would show someone better suited?

**Comment by DilumAluthge** [comment]
From looking at the git blame, maybe @Keno or @rfourquet?

**Review by Keno — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Thank you Keno!!

**Comment by yuyichao** [comment]
This also broke IJulia.

**Comment by palday** [comment]
This broke RCall's REPL integration

**Pull request merged**
