### PR TITLE
add Quarter period

### PR DESCRIPTION
**Pull request by matthieugomez**
Similarly to the fact that a `Week` corresponds to seven days, a `Quarter` corresponds to three months. @quinnj 

https://github.com/JuliaLang/julia/issues/35517

### CODE REVIEW

**Comment by matthieugomez** [comment]
I have not touched the `quarterofyear` function but maybe it should be deprecated (since it is equivalent to `quarter`).

**Review by quinnj — APPROVED** [review]
LGTM; no support for parsing/formatting, but it's not a very common use-case anyway.

**Comment by matthieugomez** [comment]
For now, I don't export `quarter`. This is a bit weird: accessor functions are exported for all other Periods . The reason I don't do this is that there is already a function, `quarterofyear`, that does exactly the same thing. 

So, should I still export `quarter`? If yes, should I deprecate `quarterfoyear`?

**Comment by quinnj** [comment]
Looks like this needs a rebase and can be merged

**Pull request closed without merging**
