### PR TITLE
RFC: Introduce `AdjointRotation` to avoid subtyping `AbsMat`

### PR DESCRIPTION
**Pull request by dkarrasch**
This is the analogue to #46196 for `AbstractRotation`. It is somewhat weird that `Adjoint{<:Any,<:NOTAbstractMatrix}` still subtypes to `AbstractMatrix`, which introduces many ambiguities. Typically, non-matrices like Q's and rotations should have preference over _any_ AbstractMatrix in multiplication. That is, no matter how structured/sparse the other factor is, the q-multiplication code or the rotation-code should apply, not the other way around. Technically, this is again breaking, but I expect even less friction than in #46196.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46233#issuecomment-1200440984) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/34e61ed_vs_dbae5a5/report.html).

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["ASE", "ArgoData", "Bagyo", "BugReporting", "COPT", "CVRPLIB", "CairoMakie", "Cambrian", "CellListMap", "Clang", "ClimaCorePlots", "CommunityDetection", "CompactBasisFunctions", "ControlSystems", "CountdownNumbers", "CrystalInfoFramework", "DataDeps", "DrelTools", "FameSVD", "FlameGraphs", "Folds", "Gen", "GenericLinearAlgebra", "GenericSchur", "GeometricIntegrators", "GeometricIntegratorsDiffEq", "GraphMLDatasets", "GraphNeuralNetworks", "Hashpipe", "HiddenMarkovModelReaders", "ITensorGaussianMPS", "IncrementalPruning", "InformationGeometry", "KernelEstimator", "LatticeDiracOperators", "LogicToolkit", "LoopThrottle", "LowRankIntegrators", "Lux", "MatrixMarket", "McCormick", "MultivariatePolynomials", "NEOSServer", "NNlib", "NeighbourLists", "Nonconvex", "ParameterSpacePartitions", "PerronFrobenius", "Pfam", "Pidfile", "PolaronPathIntegrals", "PoreMatMod", "ProgressiveHedging", "ProxSDP", "QuadraticToBinary", "QuadratureRules", "Quiqbox", "ReinforcementLearningExperiments", "RetroCap", "RungeKutta", "StableTrees", "StochasticDelayDiffEq", "StochasticIntegrators", "StochasticPrograms", "StrBase", "StressTest", "SymbolicRegression", "TopoPlots", "TuringGLM", "Variography", "VideoIO"], vs = ":master")`

**Comment by dkarrasch** [comment]
Shall we consider this? I'll try to run the tests once again, since earlier issues have been resolved meanwhile, I believe.

@nanosoldier `runtests(["ASE", "ArgoData", "Bagyo", "BugReporting", "COPT", "CVRPLIB", "CairoMakie", "Cambrian", "CellListMap", "Clang", "ClimaCorePlots", "CommunityDetection", "CompactBasisFunctions", "ControlSystems", "CountdownNumbers", "CrystalInfoFramework", "DataDeps", "DrelTools", "FameSVD", "FlameGraphs", "Folds", "Gen", "GenericLinearAlgebra", "GenericSchur", "GeometricIntegrators", "GeometricIntegratorsDiffEq", "GraphMLDatasets", "GraphNeuralNetworks", "Hashpipe", "HiddenMarkovModelReaders", "ITensorGaussianMPS", "IncrementalPruning", "InformationGeometry", "KernelEstimator", "LatticeDiracOperators", "LogicToolkit", "LoopThrottle", "LowRankIntegrators", "Lux", "MatrixMarket", "McCormick", "MultivariatePolynomials", "NEOSServer", "NNlib", "NeighbourLists", "Nonconvex", "ParameterSpacePartitions", "PerronFrobenius", "Pfam", "Pidfile", "PolaronPathIntegrals", "PoreMatMod", "ProgressiveHedging", "ProxSDP", "QuadraticToBinary", "QuadratureRules", "Quiqbox", "ReinforcementLearningExperiments", "RetroCap", "RungeKutta", "StableTrees", "StochasticDelayDiffEq", "StochasticIntegrators", "StochasticPrograms", "StrBase", "StressTest", "SymbolicRegression", "TopoPlots", "TuringGLM", "Variography", "VideoIO"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46233#issuecomment-1222611254) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/fce8190_vs_947c908/report.html).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46233#issuecomment-1223977711) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/fce8190_vs_df3da05/report.html).

**Comment by dkarrasch** [comment]
Since, after all, this doesn't seem to break any code, I'll merge in a few days if no objections arise. This part of the code seems to be mainly used as a blackbox, without any extensions/overloads/etc. (with ITensors.jl the only exception, which in turn doesn't use any fallback definitions but instead provides all required functions itself). @emstoudenmire @mtfishman @kshyatt

**Pull request merged**
