### PR TITLE
Document DomainError in airyaix and airyaiprimex

### PR DESCRIPTION
**Pull request by giordano**
Followup of #18050

### CODE REVIEW

**Comment by tkelman** [comment]
Thanks! Please wrap long lines in docstrings.

**Comment by giordano** [comment]
Fixed, thank you.  I usually wrap my code after 80 characters, but I noticed that docstrings in Julia's base code have a pretty inconsistent wrapping style (e.g., `airybiprimex`'s docstring is a single 169-character long line), I was not sure about what was the style to follow.

**Comment by giordano** [comment]
Thanks for the pointer, I updated the docstrings according to this style rule.

However, I repeat that this style guideline are not faithfully applied throughout Julia's code (the docstrings I corrected didn't respect the 92-character rule, for one).  How about adding to the repository setting files to ease this task?  I can do this for Emacs through a [`.dir-locals.el`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) file.  In this way it's easy to automatically enforce to all contributors running Emacs many of the style guidelines (both for Julia and C languages).  I don't know how many developers running Emacs are out there, though.

**Comment by tkelman** [comment]
some form of autoformatting would be wonderful, if we're sure it won't change the meaning. emacs is used by a decent fraction of contributors here but far from all. ideally we could set it up as a script we would run periodically.

**Comment by simonbyrne** [comment]
Thanks for that.

I actually kind of like that it is a bit flexible: there are always cases where a few extra characters can be useful.

**Comment by bramtayl** [comment]
I think that RStudio automatically wraps views of markdown when editing. It makes editing markdown a lot easier; you don't have to worry about line length at all. Because I'm indecisive I find myself constantly editting docstrings in Julia and having to realign all the text.

**Pull request merged**
