### PR TITLE
Set VERSION to 1.0.0-DEV

### PR DESCRIPTION
**Pull request by ararslan**
Now that we've branched for 0.7, any change that should be applied for RC2 should have the "backport pending 0.7" label.

And with this, master is the initial development version for Julia v1.0.

### CODE REVIEW

**Comment by Keno** [comment]
@KristofferC @StefanKarpinski Looks like both Pkg and OldPkg don't like 1.0 very much.

**Comment by fredrikekre** [comment]
For Pkg I think we need a version of Example that does not have an upper bound on julia v1.0.

**Comment by ararslan** [comment]
[Example](https://github.com/JuliaLang/Example.jl) seems to require 0.6 at a minimum? https://github.com/JuliaLang/Example.jl/blob/master/REQUIRE#L6

**Comment by fredrikekre** [comment]
> Example seems to require 0.6 at a minimum with no upper bound? https://github.com/JuliaLang/Example.jl/blob/master/REQUIRE#L6

We have new compat specifiers (https://docs.julialang.org/en/latest/stdlib/Pkg/#Caret-specifiers-1) so this: https://github.com/JuliaRegistries/General/blob/master/E/Example/Compat.toml is what Pkg3 cares about.

**Comment by ararslan** [comment]
According to Avik, the 0.7 upper bound is an artifact of the METADATA to General registry conversion.

**Comment by Keno** [comment]
Just FYI for those watching from the sidelines. Since these test failures block merging this, we'll keep master open for 0.7 changes until this is resolved, at which point we'll re-branch release-0.7 and make master 1.0 (or equivalently, we'll automatically push over all changes on master in the same order onto the 0.7 branch, since not merging this means no 1.0 changes yet).

**Comment by KristofferC** [comment]
Registry should be updated to 1.0: https://github.com/JuliaRegistries/General/commit/16921d0e9042c02301ec333e307f17ba6e06356d.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/28385 should fix freebsd error.

https://github.com/JuliaLang/julia/pull/28387 and https://github.com/JuliaLang/julia/pull/28387 should likely be merged befor RC.

**Pull request merged**
