### PR TITLE
no space within word

### PR DESCRIPTION
**Pull request by EQt**

### CODE REVIEW

**Comment by tkelman** [comment]
this might be a limitation of sphinx, I'm not sure

**Comment by nalimilan** [comment]
@EQt Thanks. Have you checked that the built documentation looks OK? You can generate it by running `make -C html` and looking at `doc/_build/html/`.

**Comment by EQt** [comment]
Oh. You were right: sphinx does not recognize the `` correctly without space.

**Comment by mbauman** [comment]
RST certainly does not make this easy.  The way to remove that space is by escaping it:

    ``export``\ ed

**Comment by EQt** [comment]
Yeah. That works! Thanks for the hint. I will reopen that issue.

**Pull request closed without merging**
