### PR TITLE
Update Statistics.jl

### LINKED ISSUE #32841: ERROR: UndefVarError: mean not defined
Hello all, 

I am trying to follow the docs [here](https://docs.julialang.org/en/v1.0/stdlib/Statistics/#Statistics.mean) to use the mean function. This is what I am getting:

```julia 
Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> mean(1:20)
ERROR: UndefVarError: mean not defined
Stacktrace:
 [1] top-level scope at none:0

julia> Statistics.mean(1:20)
ERROR: UndefVarError: Statistics not defined
Stacktrace:
 [1] top-level scope at none:0

```

### PR DESCRIPTION
**Pull request by logankilpatrick**
This needs to be fixed. Nowhere on the statistics docs (that I found with ease) does it say to run `using statistics` so when I do these examples, I was getting errors.

Will close #32841

Not 100% sure If I edited the right file but I think I did.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
@vchuravy any thoughts or suggested changes on this?

**Comment by quinnj** [comment]
This LGTM; looks like there's a whitespace error (from the buildbot/whitespace_linux32 check); once that's fixed, we can merge this.

**Comment by logankilpatrick** [comment]
Done!

**Review by fredrikekre — CHANGES_REQUESTED** [review]
This doesn't make sense, there are no example below in this docstring. You probably want to add the note in the `docs/index.md` file.

**Comment by logankilpatrick** [comment]
Made a new PR here: #32897

**Pull request closed without merging**
