### PR TITLE
[LLVM8] patch maintenance

### PR DESCRIPTION
**Pull request by vchuravy**
Backport of #35300 also includes #35273

I removed the checksums for the assert build since we traditionally don't include them, but I have yet to push the assert build with these patches since I am watinging for antarctic to be free again.

### CODE REVIEW

**Comment by ianshmean** [comment]
I can confirm that on aarch64 this fixes https://github.com/JuliaLang/julia/issues/31156 (https://github.com/JuliaLang/PackageCompiler.jl/issues/295) 🎉

**Review by staticfloat — APPROVED** [review]

**Comment by KristofferC** [comment]
Changed the base branch to be against the correct one (the one we will run Nanosolider and PkgEval on before merging it into release-1.4)

**Comment by KristofferC** [comment]
Can this be merge?

**Comment by vchuravy** [comment]
> Can this be merged?

I was just waiting for you to give me the green-light.

**Comment by KristofferC** [comment]
I didn't know if 

> but I have yet to push the assert build with these patches since I am watinging for antarctic to be free again.

was something that needed to be done first.

**Pull request merged**
