### PR TITLE
Set master version to 1.5

### PR DESCRIPTION
**Pull request by ararslan**
VERSION has been set to 1.5.0-DEV, the 1.4 NEWS items have been moved to HISTORY, and NEWS has been cleared out for 1.5 items.

Please don't merge anything to master until this is merged so that versions don't get messed up, since 1.4 has been branched.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
NEWS needs edits. I'll do a pass.

**Comment by Keno** [comment]
> Please don't merge anything to master until this is merged so that versions don't get messed up, since 1.4 has been branched.

For future releases, can we just merge this to master whenever and the create the release branch from whatever the commit before was? Trying to lock master without an enforcement mechanism seems potentially problematic.

**Comment by ararslan** [comment]
Yes, agreed.

**Comment by timholy** [comment]
I'm getting
```
$ make
WARNING: using mismatched version for Statistics-a2203d3b67f7413701be5de251622cb85c9cc69d symlink-uninstaller /home/tim/src/julia-branch/usr/share/julia/stdlib/v1.4:
  want Statistics-a2203d3b67f7413701be5de251622cb85c9cc69d symlink-uninstaller /home/tim/src/julia-branch/usr/share/julia/stdlib/v1.5
```
and
```
error during bootstrap:
LoadError("sysimg.jl", 16, ArgumentError("Package Statistics not found in current path:\n- Run `import Pkg; Pkg.add(\"Statistics\")` to install the Statistics package.\n"))
require at ./loading.jl:892
```
at the end of trying to build Julia. Related? Easy fix?

**Comment by ararslan** [comment]
Very weird, I have not gotten that on any of my systems: I've rebuilt from source with this change on Linux, macOS, and FreeBSD. Perhaps clean it out (`git clean -fdx` is what I do) and try again?

**Comment by timholy** [comment]
Worked, thanks! (Note for anyone who reads this: first save elsewhere any untracked files you don't want deleted.)

**Comment by ararslan** [comment]
`make distclean-all` might work as well and wouldn't delete your stuff.

**Comment by vtjnash** [comment]
`rm -rf usr` almost always works too, and is quick

**Comment by ViralBShah** [comment]
That would not remove the .o files right? We have too many (4) clean targets. Max level is `distcleanall`.

**Pull request merged**
