### PR TITLE
Use isb for normal cpu pause on aarch64

### PR DESCRIPTION
**Pull request by gbaraldi**
Following https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807, it seems that isb is probably best for this. `wfe` is still good for some specific spins we do because we explicitly call `jl_cpu_wake` on them, but in most cases we just call `jl_cpu_pause` which technically can take unbounded time in aarch64, though it seems to be about a microsecond in the M1 which is far too long for some things. 

In order to keep the nice `pause/wake`combo I added `jl_cpu_suspend` (Open to bikeshedding) to be the actual long wait that needs to be woken up, while pause now behaves more like x86 `pause` taking a couple nanoseconds to execute.

### CODE REVIEW

**Comment by gbaraldi** [comment]
1.9
```julia
julia> @benchmark ccall(:jl_cpu_pause, Cvoid, ())
BenchmarkTools.Trial: 3769 samples with 1000 evaluations.
 Range (min … max):  369.250 ns …  4.283 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):       1.333 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.326 μs ± 79.711 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                                                           ▂█▄
  ▃▁▁▁▃▃▁▃▁▁▁▃▁▃▁▄▄▄▁▁▃▄▃▃▁▄▁▁▁▄▃▃▁▁▃▅▄▄▄▃▁▃▅▄▄▅▄▄▄▅▆▆▆▅▇▇████ █
  369 ns        Histogram: log(frequency) by time      1.36 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

PR
```julia
julia> @benchmark ccall(:jl_cpu_pause, Cvoid, ())
BenchmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  16.449 ns … 56.696 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.575 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   16.742 ns ±  1.451 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▄▇ █▆ ▅▄              ▁ ▂                                  ▂
  ▆██▁██▁██▁█▅▁▃▃▁▆▄▁▃▃▁▇█▁██▁▇▇▄▆▆▇▁▆▆▁▆▆▁▆▆▁▆█▁▇▇▁▇▆▁▅▅▁▅▄▃ █
  16.4 ns      Histogram: log(frequency) by time      18.1 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

**Comment by gbaraldi** [comment]
.NET does some more fancier things for this https://github.com/dotnet/coreclr/pull/13670. But that can probably a separate PR.

**Comment by d-netto** [comment]
If we're changing `jl_cpu_pause`, then the exponential backoff algorithm from #48600 might need some adjustments as well.

**Comment by gbaraldi** [comment]
Maybe, this behaves a lot more like the x86 one so it's probably a bit easier to share code.

**Comment by vchuravy** [comment]
This makes sense from my side, and the fact that other languages like Rust have done that is encouraging.

I am not necessarily familiar enough with AArch64 , so I am hoping @yuyichao can share some advice.

**Review by vchuravy — APPROVED** [review]

**Comment by kpamnany** [comment]
I'm no expert on AMD architecture, but this seems like a good thing.

**Pull request merged**
