### PR TITLE
`Base.julia_cmd()`: correctly forward the `--sysimage-native-code=no` flag if it is provided

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #42173
Ref https://github.com/JuliaLang/julia/pull/41238#issuecomment-915668418

This is a replacement for #42173.

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@vtjnash @staticfloat We don't need to backport this, right? Since the motivation here is to fix the code coverage, and we only run code coverage on `master`.

**Review by vtjnash — APPROVED** [review]
oops, it was even already documented

**Comment by DilumAluthge** [comment]
Or do we need to backport this because it is a bug fix? Since it was in the docstring.

**Comment by DilumAluthge** [comment]
I'm going to mark this for backport as a bugfix. If that is not correct, please remove the backport labels.

**Comment by DilumAluthge** [comment]
@staticfloat @vtjnash This PR seems to have broken the coverage job. See e.g. https://buildkite.com/julialang/julia-master-scheduled/builds/225

**Comment by DilumAluthge** [comment]
I'm removing the backport labels until we can figure out why this broke the code coverage Buildkite job.

**Comment by vtjnash** [comment]
looks like buildkite needs to increase the timeout threshold for starting workers, as we launch a lot of them, and these are probably noisy machines

**Comment by vtjnash** [comment]
Note that it is a 32-core machine, and it looks like buildkite is mis-configured to force the launching of 16*16 (or 256) threads

**Comment by DilumAluthge** [comment]
> looks like buildkite needs to increase the timeout threshold for starting workers, as we launch a lot of them, and these are probably noisy machines

We could increase the timeout. That being said, before this PR was merged, the code coverage Buildkite job had no trouble starting all of its workers within the default timeout. See e.g. the following successful jobs:
- https://buildkite.com/julialang/julia-master-scheduled/builds/224
- https://buildkite.com/julialang/julia-master-scheduled/builds/223
- https://buildkite.com/julialang/julia-master-scheduled/builds/222
- https://buildkite.com/julialang/julia-master-scheduled/builds/221

Is it possible that this PR specifically would increase the time it takes a worker to start up?

**Comment by DilumAluthge** [comment]
To increase the timeout, I'm assuming I just need to set the `JULIA_WORKER_TIMEOUT` environment variable to something greater than 60?

**Comment by vtjnash** [comment]
Yes, but also, we need to fix that configuration bug too

**Comment by DilumAluthge** [comment]
> Yes, but also, we need to fix that configuration bug too

Ah, the 16 workers * 16 threads per worker?

For that one, I think we can just set `JULIA_NUM_THREADS=1` in the code coverage Buildkite job, right?

**Comment by DilumAluthge** [comment]
Increasing the worker timeout seems to have resolved the issue with the code coverage job, so I'm adding the backport labels back.

**Pull request merged**
