### PR TITLE
Sort the pivot, lo and hi value immediately in-place in quicksort

### PR DESCRIPTION
**Pull request by haampie**
This is a micro-optimization where one swap is eliminated by sorting three values immediately in the requested order.

### CODE REVIEW

**Comment by pabloferz** [comment]
Dup of #16583

**Comment by haampie** [comment]
Ah, nice. So why wasn't this merged yet?

**Comment by KristofferC** [comment]
Perhaps because of

> I believe I benchmarked something wrong the first time. It seems now like a insignificant improvement and more like a cosmetic change.

**Comment by haampie** [comment]
> I remember correctly, the compiler is able to optimize the order of the operations so it doesn't really make a difference.

Looking at the generated code, it seems there is fewer operations in general and 15 mov instructions rather than 19, so I guess there is some change at least!

> It seems now like a insignificant improvement and more like a cosmetic change.

I totally believe this, cause `selectpivot!` does O(n) work in an O(n lg n) algorithm, and we're only slightly improving the constant in front of the O(n) in this pr. But then the argument for merging this is that it makes Julia Base 4 lines shorter and it prevents a third person from opening a PR with the same changes in two years from now.

**Comment by JeffBezanson** [comment]
Is it possible to demonstrate any speedup at all for this? Even e.g. on a single carefully designed case? I'm not against the change, mostly just curious.

**Comment by StefanKarpinski** [comment]
A 41% speedup even only in some cases is nothing to sneeze at (which, now that I've written it out is a _really_ weird idiom; it means "not bad at all").

**Comment by haampie** [comment]
I believe this is ready then!

**Comment by Sacha0** [comment]
Absent objections, requests for time, or someone beating me to it, I plan to merge these changes this evening PT or later. Best!

**Pull request merged**
