### PR TITLE
enhance maintainability of `jl_ir_` accessors

### PR DESCRIPTION
**Pull request by aviatesk**
By allowing us to change data size at one place when we make a change to the layout of compressed IR.

### CODE REVIEW

**Review by Keno — APPROVED** [review]
Yes, this is what I had in mind, plus some asserts in the serializer that asserts that the offset matches what is being written.

**Review by vtjnash — APPROVED** [review]

**Comment by aviatesk** [comment]
> plus some asserts in the serializer that asserts that the offset matches what is being written

Do you mean something like this?
```diff
diff --git a/src/ircode.c b/src/ircode.c
index 8516cf9817..fb322a37a9 100644
--- a/src/ircode.c
+++ b/src/ircode.c
@@ -825,12 +825,16 @@ JL_DLLEXPORT jl_string_t *jl_compress_ir(jl_method_t *m, jl_code_info_t *code)
     jl_code_info_flags_t flags = code_info_flags(code->inferred, code->propagate_inbounds, code->has_fcall,
                                                  code->nospecializeinfer, code->inlining, code->constprop);
     write_uint8(s.s, flags.packed);
+    assert(sizeof(flags.packed) == ir_datasize_flags);
     write_uint8(s.s, code->purity.bits);
+    assert(sizeof(code->purity.bits) == ir_datasize_purity);
     write_uint16(s.s, code->inlining_cost);
+    assert(sizeof(code->inlining_cost) == ir_datasize_inlining_cost);
 
-    size_t nslots = jl_array_nrows(code->slotflags);
+    int32_t nslots = jl_array_nrows(code->slotflags);
     assert(nslots >= m->nargs && nslots < INT32_MAX); // required by generated functions
     write_int32(s.s, nslots);
+    assert(sizeof(nslots) == ir_datasize_nslots);
     ios_write(s.s, jl_array_data(code->slotflags, const char), nslots);
 
     // N.B.: The layout of everything before this point is explicitly referenced
```

**Comment by Keno** [comment]
Yes, although those could probably be static asserts, since they're constexpr, which would help even if you're not building in debug mode. The intention is for something to fail loudly if things get messed up.

**Comment by aviatesk** [comment]
Hmm, it looks like they aren't constexprs in the CI setup? I couldn't reproduce it locally..

**Pull request merged**
