### PR TITLE
updating diagonal.jl wref #40887

### PR DESCRIPTION
**Pull request by ArunS-tack**
Added a method so that there is no error while computing rdiv! without explicitly specifying type as mentioned in the example in JuliaLang/LinearAlgebra.jl#849 .

### CODE REVIEW

**Comment by olof3** [comment]
I guess it would be better to widen the type signature of
```julia
function rdiv!(A::AbstractMatrix{T}, D::Diagonal{T}) where {T}
```
similarly to
```julia
ldiv!(D::Diagonal, B::AbstractVecOrMat)
```
rather than adding a new method.

I guess some regression test would also be good.

**Review by ArunS-tack — COMMENTED** [review]
Removed the added method and modified rdiv! function for the same.

**Comment by ArunSanganal** [comment]
> I guess it would be better to widen the type signature of
> 
> ```julia
> function rdiv!(A::AbstractMatrix{T}, D::Diagonal{T}) where {T}
> ```
> 
> similarly to
> 
> ```julia
> function ldiv!(D::Diagonal, B::AbstractVecOrMat)
> ```
> 
> rather than adding a new method.
> 
> I guess some regression test would also be good.

is it ok now?

**Comment by olof3** [comment]
> is it ok now?

Also adding some regression tests would be customary.

> Also, how do i delete the first commit?

No worries, it will be squashed away when this is merged.

**Comment by ArunSanganal** [comment]
> > is it ok now?
> 
> Also adding some regression tests would be customary.
> 
> > Also, how do i delete the first commit?
> 
> No worries, it will be squashed away when this is merged.

not sure what do you mean by regression test.

**Comment by mcabbott** [comment]
You should have a button to re-open this one, it's less confusing if the same PR gets updated. 

Re tests, you should search this file: https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/test/diagonal.jl for "rdiv!" and "ldiv!" and figure out the best place to add something. At least one test should be something which fails before the PR, like `@test rdiv!(Diagonal([2.0,3.0]), Diagonal(2:3)) == Diagonal([1,1])`.

**Comment by ArunSanganal** [comment]
> You should have a button to re-open this one, it's less confusing if the same PR gets updated. 
> 
> Re tests, you should search this file: https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/test/diagonal.jl for "rdiv!" and "ldiv!" and figure out the best place to add something. At least one test should be something which fails before the PR, like `@test rdiv!(Diagonal([2.0,3.0]), Diagonal(2:3)) == Diagonal([1,1])`.

Actually I deleted the repository linked with this PR too (oops). So I can't reopen it again.

**Comment by mcabbott** [comment]
:( 

Also, no need to quote everyone's words.

**Comment by ArunSanganal** [comment]
I will read through the same. Thanks.

**Pull request closed without merging**
