### PR TITLE
Simplify and fix primes and primesmask [fixes #14652]

### LINKED ISSUE #14652: primes(1,10) -> BoundsError
```julia
julia> primes(1,10)
ERROR: BoundsError: attempt to access 30-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 1
 1
 1
 1
 2
 2
 3
 3
 3
 3
 4
 4
 5
 5
 5
 5
 6
 6
 6
 6
 6
 6
 7
 7
  at index [0]
 in primes at primes.jl:111
```

Build as follows...
```sh
            # Download Julia source code...
            cd /
            git clone git://github.com/JuliaLang/julia.git
            cd julia
            git checkout release-0.4

            # Configure Julia for the Xeon E5-2680 CPU used by AWS Lambda...
            cp Make.inc Make.inc.orig
            find='OPENBLAS_TARGET_ARCH=.*\$'
            repl='OPENBLAS_TARGET_ARCH=SANDYBRIDGE\\nMARCH=core-avx-i'
            sed s/\$find/\$repl/ < Make.inc.orig > Make.inc

            # Build and install Julia under /var/task...
            make -j2 prefix= DESTDIR=/var/task all
            make prefix= DESTDIR=/var/task install
```

EC2 info...
```
                    ImageId      = "ami-1ecae776",
                    InstanceType = "c3.large",
```

```
[ec2-user@ip-172-31-18-220 task]$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
stepping	: 4
microcode	: 0x415
cpu MHz		: 2793.308
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase smep erms
bogomips	: 5586.61
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
stepping	: 4
microcode	: 0x415
cpu MHz		: 2793.308
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase smep erms
bogomips	: 5586.61
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

### PR DESCRIPTION
**Pull request by p-zubieta**
This simplifies the code to compute `primes` and `primesmask` given that there was no significant speed difference between the to existing methods. Also [fixes #14652].

Moreover, there's no need to add new tests for this as the current tests cover the issue via the new definitions.

### CODE REVIEW

**Comment by tkelman** [comment]
Add #14652 as a test? And squash the commits.

**Comment by pabloferz** [comment]
I finally got to reduce the code as I have thought initially so there is no longer need to add more tests. The current ones will cover the issue via the redefinitions.

**Comment by pabloferz** [comment]
The Travis failures are unrelated.

**Comment by tkelman** [comment]
Could you amend the commit message to be more descriptive? The PR description is a good level of detail.

**Comment by pabloferz** [comment]
Is this better now? I just used the same description, buy it might be that you were thinking of something else.

**Comment by tkelman** [comment]
Better. I'm still not quite seeing why we can't just add `@test primes(1,10) == [2,3,5,7]` as a new test.

**Comment by pabloferz** [comment]
I just thought it wouldn't be necessary now that `prime(n) = prime(1,n)`. So `prime(1,n)` is tested whenever there is a `prime(n)` tested.

I can add the test if you think is better anyway.

**Comment by tkelman** [comment]
Ah okay, that makes sense then. Good enough I suppose.

**Comment by pabloferz** [comment]
No problem.

**Pull request merged**
