### PR TITLE
Try bumping JuliaSyntax to 0.4.10

### PR DESCRIPTION
**Pull request by Keno**
The last time we tried to bump JuliaSyntax (https://github.com/JuliaLang/julia/pull/53119), it didn't work out due to test failues. As a result, we haven't actually bumped JuliaSyntax in about a year and there are several syntax changes in JuliaSyntax that we haven't picked up yet (i.e. are waiting in PRs). I don't know what the current situation is, but I think we need to get back to a point where we can bump JuliaSyntax regualarly, so let's try to take the first step.

### CODE REVIEW

**Comment by Keno** [comment]
REPLCompletions issue is:
```
julia> s = "CompletionFoo.test(1, 1, "
"CompletionFoo.test(1, 1, "

julia> Base.incomplete_tag(Meta.parse(s, raise=false, depwarn=false))
:none
```
vs
```
julia> Base.incomplete_tag(Meta.parse(s, raise=false, depwarn=false))
:other
```

**Comment by KristofferC** [comment]
I think this broke Revise tests which didn't run on this PR for some reason. Maybe it needed a rebase to pick up on the new buildkite config? On https://buildkite.com/julialang/julia-master/builds/42947#0193b85a-4e0e-4101-b248-0e43faef0607 there is

```
Recipes: Test Failed at /root/.julia/packages/Revise/UvZ44/test/runtests.jl:2881
--
  | Expression: definition(m) isa Expr
  | Evaluated: nothing isa Expr
  |  
  | Stacktrace:
  | [1] top-level scope
  | @ ~/.julia/packages/Revise/UvZ44/test/runtests.jl:89
  | [2] macro expansion
  | @ /cache/build/builder-amdci5-5/julialang/julia-master/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1724 [inlined]
  | [3] macro expansion
  | @ ~/.julia/packages/Revise/UvZ44/test/runtests.jl:2869 [inlined]
  | [4] macro expansion
  | @ /cache/build/builder-amdci5-5/julialang/julia-master/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:1724 [inlined]
  | [5] macro expansion
  | @ ~/.julia/packages/Revise/UvZ44/test/runtests.jl:2881 [inlined]
  | [6] macro expansion
  | @ /cache/build/builder-amdci5-5/julialang/julia-master/usr/share/julia/stdlib/v1.12/Test/src/Test.jl:679 [inlined]
```

I'll see if I can fix it quickly on the Revise side.

**Comment by Keno** [comment]
That error happens when Revise fails to parse base. one possible reason is the include issue I fixed last week. I'm on my phone so it's hard to see if that build is on master. If it's not, them the error is unsurprising because it needs my fixes from last week. Otherwise it is indeed possible that this commit broke it and will need to look at what suppressed error revise had while parsing Base.

**Comment by KristofferC** [comment]
Maybe it is fine considering for example https://github.com/JuliaLang/julia/pull/56798 is all green which was made after this PR. The PRs that fail probably have an old base commit. (I still think it is kinda crazy not to run CI on the merge commit).

**Comment by Keno** [comment]
Yeah, old base commits will fail, because they're using Revise master, which needs a fix on julia master.

**Pull request merged**
