### PR TITLE
remove graphics.jl and Graphics module from base

### PR DESCRIPTION
**Pull request by jakebolewski**
As discussed in #9862.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Sweet!

**Comment by JeffBezanson** [comment]
Yes this is fine, but if any packages are extending these methods we need to set up a Geometry.jl package replacement right away.

**Comment by garborg** [comment]
In #9862, @timholy mentioned Color.jl, Cairo.jl, Gtk.jl, Images.jl, ImageView.jl, ProfileView.jl, Tk.jl, and Winston.jl.

**Comment by jakebolewski** [comment]
Could you create a JuliaLang/Graphics git repo for this?

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/Graphics.jl

You should have commit access too.

**Comment by JeffBezanson** [comment]
Ok, but there will still need to be some refactoring since not all graphics packages will use all of this.

**Comment by ViralBShah** [comment]
Coming to think of it, Graphics.jl was not a good name. Perhaps GraphicsFoundation.jl or GraphicsAPI.jl would have been a better name. This might mislead some newcomers.

**Comment by sjkelly** [comment]
https://github.com/juliageometry ?

**Comment by JeffBezanson** [comment]
Yes, the name is a problem, but the geometry and rendering API parts need to be separated as well.

**Pull request merged**
