### PR TITLE
mark `fieldcount` pure so it can be statically evaluated

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vtjnash** [comment]
Why's this needed? It's probably a pretty bad idea to allow `@pure` functions to throw (since that's technically a side-effect), so it would be nice to avoid adding more places were we annotate functions incorrectly (since then people might start depending on it).

**Comment by JeffBezanson** [comment]
It just makes sense that we should be able to statically evaluate this. I'm willing to write a t-function, was just hoping to avoid that.

**Comment by NHDaly** [comment]
> Why's this needed?

Sorry, i brought this up during our `@generated` discussion, when I saw our code had this function defined just to prevent the runtime cost of `fieldcount`:
```julia
"""
Statically get the fieldcount of a type. Useful to avoid runtime calls to fieldcount.
"""
@generated function evaluated_fieldcount(t::Type{T}) where T
    fieldcount(T)
end
```

----

> I'm willing to write a t-function, was just hoping to avoid that.

What's a t-function? :)

**Comment by Keno** [comment]
I feel like inter-procedural const prop should be able to figure this out if it were running on it (which it doesn't, since it's no-inline). Maybe we should just have a way to opt into aggressive const prop for functions like this?

**Comment by Keno** [comment]
Alternatively, it might make sense to introduce a `pure_or_error` concept.

**Comment by NHDaly** [comment]
Yeah that's a nice idea! And ideally this `pure_or_error` would be much
less restrictive than Base.pure currently is.. 😊 but maybe that's asking
too much.

It would be great if it could act as something more like "I the programmer
know that you should be able to statically compute this value based only on
its inputs, and if you can't that's an error."

**Comment by NHDaly** [comment]
Fwiw `pure_or_error` would be a perfect tool in our codebase, especially if it was less scary than `Base.@pure` currently is.

**Comment by NHDaly** [comment]
> Alternatively, it might make sense to introduce a `pure_or_error` concept.

We have been imagining this to be something like C++'s `constexpr`. It is sometimes very important to be able to promise that a function is computable by the compiler (such as e.g. if the result of the computation will be used to construct a `Val()`). The hardest part about this currently is that since it's entirely heuristics-driven, it may _appear_ to be working correctly for the inputs you test, but in production in fact this ends up causing type instability and surprise allocations.

To get around this, we are currently marking such functions as `Base.@pure`, which seems right, but I'm scared that A) i'm violating the strict rules around `@pure`, which technically says the function shouldn't call _any other julia functions_ (and even `+` is a function, so...), and B) I'm scared that the compiler may still change it's mind and decide this is too hard and fallback to a runtime calculation thus resulting in allocations. So an error thrown while compiling would be 1000000% preferable!! :)

**Comment by Keno** [comment]
This already works on master, presumably as part of various other inference precision improvements.

**Pull request closed without merging**
