### PR TITLE
REPL: fix a fragile test case

### PR DESCRIPTION
**Pull request by iblislin**
reproduction step:
```shell
  $ touch /tmp/test.magic
  $ (g)make -C test REPL
```

See: https://freebsdci.julialang.org/#/builders/1/builds/8658
Address https://github.com/JuliaLang/julia/pull/26696#issuecomment-378764168

### CODE REVIEW

**Comment by KristofferC** [comment]
@iblis17 Why isn't the FreeBSD runner running here?

**Comment by iblis17** [comment]
well, it's queuing: https://freebsdci.julialang.org/#/builders/1

**Comment by KristofferC** [comment]
Oh, I thought the notification would show up anyway (like for Travis and the rest)

**Comment by iblis17** [comment]
Not sure buildbot can make that or not. :thinking:

**Pull request merged**
