### PR TITLE
[release-0.7] Backport more things

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/28492 would be good as well. Passed on FreeBSD but the rest of the CI are not done.

**Comment by Keno** [comment]
#28485 also, ideally.

**Comment by ararslan** [comment]
Anything else?

**Comment by ararslan** [comment]
I'll take that as a no

**Comment by Keno** [comment]
There's #28500, but that already has a PR.

**Pull request merged**
