### PR TITLE
Test: change __META__ to META

### PR DESCRIPTION
**Pull request by MikeInnes**
Seeing what effect this has on the appveyor build.

cc @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
Yeah let's see, though I am inclined to agree with https://github.com/JuliaLang/julia/pull/12097#issuecomment-120302670 that this would be un-fixing the reported bug, whereas a gensym is a little weird/annoyingly hard to access but at least a valid fix.

**Comment by one-more-minute** [comment]
Sure, I'm not proposing this as a fix, just seeing what happens – the gensym is definitely a better solution.

It's not really even harder to access since you can just do `Docs.meta(Mod)`.

**Comment by tkelman** [comment]
looks like appveyor says no to this version. https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.6697/job/rx540tddrwa72wj7

headscratcher, since shouldn't this be equivalent to what the code used to do?

**Comment by one-more-minute** [comment]
Yes, there's a few code changes but it should be functionally equivalent.

I'll try getting rid of the `@eval`.

**Comment by tkelman** [comment]
now appveyor says yes. squash?

**Comment by one-more-minute** [comment]
Guess so, but we should treat this as a bug since it shouldn't be happening.

**Comment by tkelman** [comment]
Sure but I'd rather fix master now, so we can restart all the PR's that failed due to this. Determining and fixing the underlying cause may take some time.

**Comment by tkelman** [comment]
Thanks

**Pull request merged**
