### PR TITLE
Backports for Julia 1.8.2

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #46030 
- [x] #46183 
- [x] #46547 
- [x] #46550 
- [x] #46551 
- [x] #46618 
- [x] #46553 
- [x] #46667 
- [x] #46673 
- [x] #46732 
- [x] #46661 
- [x] #46761 
- [x] #46767 
- [x] #45173 
- [x] #46597 
- [x] #46762 
- [x] #46757 
- [x] #44918 
- [x] #45047 
- [x] #46647 
- [x] #46792 
- [x] #46605 
- [x] #46570 
- [x] #46086 
- [x] #46799

Non-merged PRs with backport label:
- [ ] #46787 
- [ ] #46373 
- [ ] #45582

### CODE REVIEW

**Comment by ranocha** [comment]
https://github.com/JuliaLang/julia/pull/46673 and https://github.com/JuliaLang/julia/pull/46661 are additional non-merged PRs with backport label.

**Comment by ufechner7** [comment]
Can this commit also be added: https://github.com/JuliaLang/julia/issues/46492 ?

**Comment by ranocha** [comment]
https://github.com/JuliaLang/julia/pull/46732

**Comment by fxcoudert** [comment]
Could I ask that https://github.com/JuliaLang/julia/pull/45411 be backported to 1.8.2? Or at least, the parts that provide forward build compatibility with libgit2 >= 1.4.0, i.e., this part:

```
diff --git a/stdlib/LibGit2/src/consts.jl b/stdlib/LibGit2/src/consts.jl
index 2bc9edaf89..55887ebe2a 100644
--- a/stdlib/LibGit2/src/consts.jl
+++ b/stdlib/LibGit2/src/consts.jl
@@ -247,6 +247,11 @@ const RESET_HARD  = Cint(3) # MIXED plus changes in working tree discarded
                             REBASE_OPERATION_FIXUP  = Cint(4),
                             REBASE_OPERATION_EXEC   = Cint(5))
 
+# git_remote_redirect_t
+const GIT_REMOTE_REDIRECT_NONE    = Cint(0)
+const GIT_REMOTE_REDIRECT_INITIAL = Cint(1)
+const GIT_REMOTE_REDIRECT_ALL     = Cint(2)
+
 # fetch_prune
 const FETCH_PRUNE_UNSPECIFIED = Cint(0)
 const FETCH_PRUNE             = Cint(1)
diff --git a/stdlib/LibGit2/src/types.jl b/stdlib/LibGit2/src/types.jl
index 9ffcaa3646..98d938df65 100644
--- a/stdlib/LibGit2/src/types.jl
+++ b/stdlib/LibGit2/src/types.jl
@@ -343,6 +343,9 @@ The fields represent:
     @static if LibGit2.VERSION >= v"0.25.0"
         proxy_opts::ProxyOptions       = ProxyOptions()
     end
+    @static if LibGit2.VERSION >= v"1.4.0"
+        follow_redirects::Cint         = Consts.GIT_REMOTE_REDIRECT_INITIAL
+    end
     @static if LibGit2.VERSION >= v"0.24.0"
         custom_headers::StrArrayStruct = StrArrayStruct()
     end
@@ -674,6 +677,9 @@ The fields represent:
     @static if LibGit2.VERSION >= v"0.25.0"
         proxy_opts::ProxyOptions       = ProxyOptions()
     end
+    @static if LibGit2.VERSION >= v"1.4.0"
+        follow_redirects::Cint         = Consts.GIT_REMOTE_REDIRECT_INITIAL
+    end
     @static if LibGit2.VERSION >= v"0.24.0"
         custom_headers::StrArrayStruct = StrArrayStruct()
     end
```

Currently, julia 1.8.x fails to build against recent libgit2 >= 1.4.0. In Homebrew, we have to patch it as above, and linux distros (like archlinux) do it as well. It would be nicer to actually provide this for source build.

In the official builds, since the dependency is not actually upgraded, it will change nothing. But it will make unpatched source builds possible for us.

**Comment by KristofferC** [comment]
You can open a PR with that as a commit against this branch or just post a commit SHA and I will push it here.

**Comment by fxcoudert** [comment]
@KristofferC I have opened a PR at https://github.com/JuliaLang/julia/pull/46795

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by maleadt** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.8")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46663#issuecomment-1251961935) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6bfa51f_vs_afb6c60/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["FHIRClient", "Flamenco", "GAP", "HydrophoneCalibrations", "SwagUI"], vs = ":release-1.8", configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46663#issuecomment-1252261720) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39ae07c_vs_afb6c60/report.html).

**Comment by maleadt** [comment]
Those results cannot be right; something was off with my `retry` logic. I've also wiped the packages store once again because there were too many failures. Let's try again:

@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/46663#issuecomment-1251961997) failed.

**Comment by maleadt** [comment]
I presume the upload was too large again? cc @vtjnash

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/fbdea1c_vs_afb6c60/report.md

**Comment by maleadt** [comment]
The most significant of these regressions seems real:

```
              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.1 (2022-09-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using BenchmarkTools

julia> v = Vector{Nothing}(undef, 100000);

julia> @benchmark Vector{Nothing}($v)
BenchmarkTools.Trial: 10000 samples with 997 evaluations.
 Range (min … max):  19.789 ns …  1.056 μs  ┊ GC (min … max): 0.00% … 96.26%
 Time  (median):     21.294 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   22.657 ns ± 25.521 ns  ┊ GC (mean ± σ):  3.47% ±  3.04%

    ▅▆▄▃▇█▇▅▅▃▂▁                            ▁▂▂▂▁▁            ▂
  ███████████████▇▇▅▅▅▄▄▁▁▁▁▁▄▁▁▁▁▄▃▁▁▄▅▆███████████▇▇▅▄▄▆▆▆▇ █
  19.8 ns      Histogram: log(frequency) by time      31.7 ns <

 Memory estimate: 48 bytes, allocs estimate: 1.
```

```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.1 (2022-09-20)
 _/ |\__'_|_|_|\__'_|  |  backports-release-1.8/39ae07ca802 (fork: 355 commits, 215 days)
|__/                   |

julia> using BenchmarkTools
[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
WARNING: method definition for dpeekbyte at /home/tim/Julia/depot/packages/Parsers/34hDN/src/utils.jl:199 declares type variable T but does not use it.

julia> v = Vector{Nothing}(undef, 100000);

julia> @benchmark Vector{Nothing}($v)
BenchmarkTools.Trial: 10000 samples with 995 evaluations.
 Range (min … max):  28.099 ns … 809.528 ns  ┊ GC (min … max): 0.00% … 94.47%
 Time  (median):     28.724 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   30.064 ns ±  20.183 ns  ┊ GC (mean ± σ):  2.05% ±  2.96%

  ▃▇██▇▆▅▄▁                               ▁▁▂▂▂▁▁▁             ▂
  █████████▇▇▇▇▆▄▄▄▄▃▃▄▃▃▄▃▁▄▃▃▁▃▃▁▃▄▄▆▆████████████▇▆▄▄▅▆▅▇▆▆ █
  28.1 ns       Histogram: log(frequency) by time      39.2 ns <

 Memory estimate: 48 bytes, allocs estimate: 1.
```

**Comment by gbaraldi** [comment]
Any idea where the extra time is cominng from?

**Comment by maleadt** [comment]
```
237c92d30e369de4152cd26c04ea79818cd0e012 is the first bad commit
commit 237c92d30e369de4152cd26c04ea79818cd0e012
Author: Hendrik Ranocha <ranocha@users.noreply.github.com>
Date:   Tue Sep 6 20:38:21 2022 +0200

    Improve dispatch of `findall(testf::F, A::AbstractArray)` (#46553)
```

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46663#issuecomment-1252341939) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39ae07c_vs_afb6c60/report.html).

**Comment by maleadt** [comment]
Hmm, maybe this is a false alarm. Even on 1.8.1 that benchmark sometimes takes 19-20us, but in some sessions (i.e. it's consistent until you restart `julia`) it regresses to 28us.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ArgoData", "BayesianQuadrature", "Flamenco", "FluxTraining", "GeometryPrimitives", "HydrophoneCalibrations", "OceanBasins", "OptimKit", "RainFARM", "SimpleFWA"], vs = ":release-1.8", configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46663#issuecomment-1253300318) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39ae07c_vs_afb6c60/report.html).

**Pull request merged**
