### PR TITLE
Faster floating point atomics

### PR DESCRIPTION
**Pull request by gbaraldi**
LLVM added atomic floating point instructions a couple of releases ago, and more will come in LLVM 15. On most targets the lowering should be similar, though locally it's about 3x faster than the current implementation. 

GPU folks will probably get a larger benefit though

### CODE REVIEW

**Comment by vtjnash** [comment]
This file is deprecated, so we should not be putting effort into this

**Comment by gbaraldi** [comment]
Where should they go then 🤔

**Comment by vtjnash** [comment]
They should be replaced by https://github.com/JuliaLang/julia/pull/45122, which should give much better performance and fewer allocations

**Comment by gbaraldi** [comment]
Yeah, the current `@atomic` code is about 20x slower than it should be :(

**Comment by vtjnash** [comment]
It shouldn't be. In this PR you said 3x, and in others I measured 2x

**Comment by gbaraldi** [comment]
I might have benchmarked it wrong, but a Threads.Atomic for a float was a lot faster than a an struct with the atomic. I didn't put too much effort in the benchmark, so there might have been an issue with it. I will make a proper one tomorrow ;)

**Pull request closed without merging**
