### PR TITLE
make REPL sticky by default

### LINKED ISSUE #6320: REPL: make shell mode sticky?
It's pretty common to type several shell commands in a row. It might be a better workflow if shell mode where sticky and required hitting escape or backspace to exit back to normal repl mode. The same could be done for help mode, but it's unclear to me that you actually want to enter multiple help queries in a row.

### PR DESCRIPTION
**Pull request by bicycle1885**
This will close #6320 and #19202.

### CODE REVIEW

**Comment by blakejohnson** [comment]
@bicycle1885 do the tests pass for you locally?

**Comment by bicycle1885** [comment]
I was too lazy to check the output carefully. The tests passed on my machine, however, some error messages were shown there. I'll investigate them later.

**Comment by bicycle1885** [comment]
Fixed tests. I guess failing tests are not related to this change.

**Comment by Roger-luo** [comment]
Do you need a new PR (or some fix) for this for v0.7/v1.0?

**Comment by musm** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/38646

**Pull request closed without merging**
