### PR TITLE
Add eachrow, eachcol, and eachslice to manual

### PR DESCRIPTION
**Pull request by mbauman**
These functions are all nicely documented but don't seem to appear in the manual.

Doesn't the documenter CI check the exports against the documented functions?  Or didn't it do that at some point in the past?  Am I missing it somewhere?  Or can we get it back?

### CODE REVIEW

**Comment by ararslan** [comment]
cc @mortenpi regarding those questions

**Review by ararslan — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]

**Comment by mortenpi** [comment]
Hmm. Documenter has the functionality, but it has actually [never checked it for the Julia manual](https://github.com/JuliaLang/julia/blame/master/doc/make.jl#L184).

We could turn it on, but I think we have plenty of docstrings attached to non-public bindings too. So I think we have two options:

1. Do `checkdocs = :exports`, which should make sure that all exported names that have docstrings are (but we'd still miss non-exported public API).
2. Maintain a hidden page with all the non-public docstrings (they would still show up in the search).

**Comment by nickrobinson251** [comment]
Shall we open an issue along the lines of "some of these might benefit from docstrings <link to list of undocumented exports>?" @mortenpi

**Comment by mbauman** [comment]
See #26919 and #31202 for the documentation efforts, but I was thinking more of the case where we already have docs and it's exported but doesn't appear in the manual — that can happen before everything gets documented.

**Comment by mortenpi** [comment]
It turns out that we already have an issue for this: #19529.

**Pull request merged**
