### PR TITLE
consolidate source files for submodules of Base

### PR DESCRIPTION
**Pull request by JeffBezanson**
This removes 8 files from base/ and takes a baby step towards making components of Base more package-like. Note that relative-to-current-file `include` only becomes available partway through sysimg.jl, so some files still need to use paths relative to base/. Still an improvement IMO.

### CODE REVIEW

**Comment by tkelman** [comment]
Sure why not. Would eventually also want to be more consistent in module-like naming/capitalization convention, but changing just the case of a file or folder without moving it can cause issues for existing clones on case-insensitive filesystems.

**Comment by JeffBezanson** [comment]
Any idea why getting the URL of a file (that didn't move) would fail only on windows?

**Comment by tkelman** [comment]
No clue, I'll build this branch and see if I can reproduce locally.

**Comment by tkelman** [comment]
Hah. `Base.url` has a bug, it's constructing part of a url from filesystem paths, but on Windows the latter are using backslashes so aren't valid url's:
```
 _/ |\__'_|_|_|\__'_|  |  (HEAD detached at origin/jb/mvfiles)/e585296* (fork: 1 commits, 0 days)
|__/                   |  i686-w64-mingw32

julia> contains(Base.url(first(methods(eigs))),"https://github.com/JuliaLang/julia/tree/$(Base.GIT_VERSION_INFO.commit)/base/linalg/arnoldi.jl#L")
false

julia> Base.url(first(methods(eigs)))
"https://github.com/JuliaLang/julia/tree/e5852964282377f8a2312a1915d6753e3d70ca20/base/linalg\\arnoldi.jl#L79"
```

**Comment by tkelman** [comment]
testing to be sure, but this should work
```diff
diff --git a/base/methodshow.jl b/base/methodshow.jl
index d1f9a0f..5ab5b35 100644
--- a/base/methodshow.jl
+++ b/base/methodshow.jl
@@ -174,6 +174,7 @@ function url(m::Method)
     file = string(m.file)
     line = m.line
     line <= 0 || ismatch(r"In\[[0-9]+\]", file) && return ""
+    is_windows() && (file = replace(file, '\\', '/'))
     if inbase(M)
         if isempty(Base.GIT_VERSION_INFO.commit)
             # this url will only work if we're on a tagged release
```

conveniently this will also fix the not-in-base LibGit2 branch of this function, since `LibGit2.path` always returns forward slashes even on windows so `startswith(file, root)` was always false.

**Comment by JeffBezanson** [comment]
Why would that affect only this PR?

**Comment by tkelman** [comment]
That file used to be included as `include("linalg/arnoldi.jl")`, so I guess the forward slash there was kept as such in the `m.file` of the `Method`. In this PR it's included as `include("arnoldi.jl")` from inside `linalg/` so I guess the file accounting uses the filesystem convention of the OS it's running on.

**Comment by JeffBezanson** [comment]
Ah yes, that makes sense. Anyway nice surprise that an extra bugfix comes out of this.

**Comment by tkelman** [comment]
Yep. And that url signature would be a good candidate for putting in a Reflection module.

**Comment by JeffBezanson** [comment]
Could you make a PR with that fix?

**Comment by tkelman** [comment]
moving things around to a module, or just the backslash 1-liner?

**Comment by JeffBezanson** [comment]
Let's do the 1-liner first.

**Comment by tkelman** [comment]
done #16858

**Comment by StefanKarpinski** [comment]
This is making rebasing all by string branches really annoying.

**Pull request merged**
