### PR TITLE
sign(::Complex): make sign of complex zero respect signs of parts

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Inspired by https://github.com/JuliaLang/julia/issues/14621.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
cc @jiahao, @andreasnoack, @stevengj

**Comment by jiahao** [comment]
I did not realize that we defined signum for complex numbers.

This doesn't seem right to me (#10000 ?):

```jl
julia> sign(-0.0im) #+0.0-0.0im? 
-0.0 - 0.0im

julia> sign(-0.0-0.0im)
-0.0 - 0.0im

julia> sign(0.0-0.0im)
0.0 - 0.0im
```

Apparently, there are [multiple extensions to complex numbers](https://en.wikipedia.org/wiki/Sign_function#Complex_signum) and we should document which one we implement (`sgn(z)` in Wikipedia's notation rather than `csgn`).

**Comment by StefanKarpinski** [comment]
Since `-0.0im === complex(-0.0,-0.0)` you're probably not testing what you think you are here.

**Comment by jiahao** [comment]
Oh, talk about subtle.

**Comment by jiahao** [comment]
My issue is orthogonal to this PR. Otherwise lgtm

**Pull request merged**
