### PR TITLE
try to get more info on Test failure

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
> `ERROR: UndefVarError: DontExistOn1 not defined`

You don't say??

**Comment by vtjnash** [comment]
You got the other common one (https://github.com/JuliaLang/julia/issues/377350)

**Comment by vtjnash** [comment]
>   [5] deserialize_fillarray!(A::Vector{Test.LogRecord}, s::Distributed.ClusterSerializer{TCPSocket})

So there's something wrong with one of the `@test_logs`?

**Comment by vtjnash** [comment]
(which does indeed have `_module::Module = Test24Main_Test` as one of the fields)

**Pull request closed without merging**
