### PR TITLE
add a reference diagram of the julia v0.4 type hierarchy details

### PR DESCRIPTION
**Pull request by vtjnash**
@JeffBezanson is this accurate? this was inspired by https://github.com/JuliaLang/julia/issues/12096, so I know that it was not entirely correct prior to that issue getting closed. i know it is also assumed to be correct by some of the datatype handling rules of codegen and the incremental serializer (#8745). this is also partially based upon the diagram you showed at JuliaCon 2014, but this is intended to additionally delve all the way down into the implementation questions as more thorough documentation of the code, rather than for users, per se.

also, @JeffBezanson when can we get a similar flowchart for section 4.3.2 of your thesis? :)

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I think several things in this are wrong, or possibly just presented confusingly.

The `typeof` arrow from Any to DataType must mean `typeof(Any)==DataType`. So far, so good. But then the arrow from Any to Type is labeled "isa/super", but `super(Any) != Type`.

It's not clear what `typeof(T<:Type)` means. It probably shouldn't point to DataType, since there are types whose `typeof` is not DataType.

I don't think "sized" is a useful classification. Every concrete type *has* a size, it just might equal zero.

Pointer-free is not a subset of immutable. Mutable types can also be pointer-free (at least in terms of the `pointerfree` field of `jl_datatype_t`.

I don't understand the "not constructible" boxes, particularly the one under isleaftype.

"Sorted cache" and "linear cache" do not only apply to concrete types. Parameters of types in the sorted part of the cache need to be egal-comparable, not necessarily pointer-comparable. At this point, presenting the kinds of types in a tree breaks down. Everything else in the diagram is about storage-related properties, but the cache works entirely with parameters.

**Comment by vtjnash** [comment]
> The typeof arrow from Any to DataType must mean typeof(Any)==DataType. So far, so good. But then the arrow from Any to Type is labeled "isa/super", but super(Any) != Type.

agreed. but i wasn't exactly sure how to label this. `includes / subtype`? or switch the direction of the arrow from Any to DataType?

> It's not clear what typeof(T<:Type) means. It probably shouldn't point to DataType, since there are types whose typeof is not DataType.

I was attempting to simplify some of the arrows from an earlier diagram, but perhaps I didn't do it quite right. I currently can't find a counterexample either, however.

> I don't think "sized" is a useful classification. Every concrete type has a size, it just might equal zero.
> Pointer-free is not a subset of immutable. Mutable types can also be pointer-free (at least in terms of the pointerfree field of jl_datatype_t).

alternative terminology would be appreciated. I had to make up a number of couple of new terms to fill out some of the diagram. agreed that "sized" is not exactly right, since "unknown size" is perhaps more appropriate for describing an incomplete type that still contains typevars. i felt it might convey nearly the right meaning, however.

pointer-free does not partition a subclass of behaviors for mutable types (other than potential optimizations), so it was not included.

> I don't understand the "not constructible" boxes, particularly the one under isleaftype.

#12096 had examples of leaf types that were not valid to construct into instances. is that fixed now? from the source-code, it looks like i may need to swap the is_pointer_comparable and is_leaf_type boxes now, based on the changes made to fix that issue.

> Everything else in the diagram is about storage-related properties, but the cache works entirely with parameters.

that's nonsense: the cache is a \*type\* cache and the end result is that a datatype gets put into one of the caches. and the layout of a type is often equally heavily influenced by its type parameters. this diagram is intended to help elucidate which cache to expect it to land in (this sometimes becomes a user-visible property due to the object_id function).

the diagram is intended to capture the visible behavioral distinctions between each type class (excluding ccall behavior, which I've captured elsewhere), of which storage properties are but one (albeit highly significant) distinction. i hope that over time, more details can be added.

> "Sorted cache" and "linear cache" do not only apply to concrete types. Parameters of types in the sorted part of the cache need to be egal-comparable, not necessarily pointer-comparable. At this point, presenting the kinds of types in a tree breaks down. 

but good point too that i'm missing any downwards arrows from "abstract" into those buckets -- excluding it from the lower half of the diagram was an oversight on my part. i'll revise my verbiage for the type parameters properties to cover the egal case. i think the properties of type parameters (egal, jl_is/has_typevars(0/1), pointer-comparable, typevar/union/tuple/abstract/leaftype will make an good supplementary diagram).

**Comment by JeffBezanson** [comment]
A type goes in the sorted cache if all its parameters satisfy

```
             (jl_is_datatype(k) && (((jl_datatype_t*)k)->uid ||
                                    k == ((jl_datatype_t*)k)->name->primary ||
                                    (!jl_has_typevars_(k,1) && !contains_unions(k)))))
```

That's not easy to express with boxes and arrows.

> that's nonsense

The problem is that the top half of the diagram breaks down types according to their representations, but then there are five downward arrows, a big horizontal line, and then four more downward arrows. All those arrows only mean that we are starting over and talking about some different properties. Obviously parameters and representations are *related*, but you can't derive one from the other. Whether a type is `isbits` is totally irrelevant to the type cache. The diagram makes it look like properties like isbits, singleton, bitstype figure in to `isleaftype` and the type cache, which they don't.

Another small point: bitstype and ghost singleton are both subsets of isbits.

**Comment by vtjnash** [comment]
i've improved the diagram to address these concerns

**Comment by jakebolewski** [comment]
@vtjnash it is great that you are documenting this (I also like that it is a diagram and not a wall of text).

**Comment by JeffBezanson** [comment]
This looks pretty good now.

**Pull request merged**
