### PR TITLE
Adjust to LLVM 3.8 API changes

### PR DESCRIPTION
**Pull request by Keno**
I tested this locally against 3.3/3.7/3.8, but let's see what CI has to say about other configurations.

### CODE REVIEW

**Comment by Keno** [comment]
What's up with Appveyor? cc @tkelman

**Comment by Keno** [comment]
Works on travis. If it's broken on Windows, I'll fix it once CI is back.

**Comment by tkelman** [comment]
strange indentation, and why is `&*` necessary?

**Comment by Keno** [comment]
The implicit conversions from iterators to pointers was removed, so `&*` is now the approved way of doing it.

**Comment by tkelman** [comment]
Wouldn't an explicit c++ cast be better?

**Comment by Keno** [comment]
I don't think that works either.

**Comment by vtjnash** [comment]
@tkelman iiuc, it isn't necessarily true that `&*I` points to the same memory as `I`, so it is not as easy as an explicit cast. Instead, it describes the memory address of the location of the object obtained by dereferencing the iterator (not pointer) `I` via operator overloading.

**Comment by tkelman** [comment]
Thanks. C++ never fails to make my head hurt and eyes bleed.

**Comment by tkelman** [comment]
That didn't last long: https://github.com/llvm-mirror/llvm/commit/8b170f7f290843dc3849eaa75b6f74a87a7a2de6

It looks like we need something to the effect of
```diff
diff --git a/src/ccall.cpp b/src/ccall.cpp
index dadd271..4bdaea8 100644
--- a/src/ccall.cpp
+++ b/src/ccall.cpp
@@ -275,7 +275,11 @@ static Value *julia_to_native(Type *to, bool toboxed, jl_value_t *jlto, const jl
                     *needStackRestore = true;
                 }
                 ai->setAlignment(16);
+#ifdef LLVM38
+                builder.CreateMemCpy(ai, builder.CreateBitCast(jvinfo.V, T_pint8), nbytes, sizeof(void*), sizeof(void*)); // minimum gc-alignment in julia is pointer size
+#else
                 builder.CreateMemCpy(ai, builder.CreateBitCast(jvinfo.V, T_pint8), nbytes, sizeof(void*)); // minimum gc-alignment in julia is pointer size
+#endif
                 return builder.CreateBitCast(ai, to);
             }
         }
```
on all of our calls to `CreateMemCpy` though I'm not sure what `SrcAlign` should be in all cases.

**Comment by tkelman** [comment]
Was apparently reverted https://github.com/llvm-mirror/llvm/commit/6d024c616a2a4959f8dfe5c64d27f89b394cf042 - will see if they take another go at it.

**Pull request merged**
