### PR TITLE
Fix #11389 Add UTF32String constructor for Vector{UInt32}

### LINKED ISSUE #11389: Documentation of `utf32` incorrectly states that an `Array` of `UInt32` is not copied by `UTF32String`
While it is true that an `Array` of `Char` is not copied, the same as an `Array` of `UInt8` for `UTF8String`, or of `UInt16` for `UTF16String`, `UTF32String` copies the array, if it is an `Array` of `UInt32`.
Either the documentation should point out this inconsistency, or else the code needs to change to have a constructor that does a `reinterpret(Char, array)` so as not to copy (which is my vote).
Either way, the documentation should be changed (to say that `Array` of `UInt32` is copied, and `Char` not, or with the code changed, that both are not copied...)
See https://groups.google.com/forum/#!topic/julia-dev/ZBSelpTlw58

### PR DESCRIPTION
**Pull request by ScottPJones**

### CODE REVIEW

**Comment by stevengj** [comment]
LGTM

**Comment by tkelman** [comment]
Does it matter whether this is an inner constructor or an outer constructor?

**Comment by ScottPJones** [comment]
Does that make any difference to the generated code?  What would be advantage of it being an outer constructor?

**Comment by nalimilan** [comment]
Basically, inner constructors cannot be bypassed, so they can be used to ensure that the data is valid. Outer constructors are just standard methods. In the present case, I'd say you'd better make `UTF32String(data::Vector{UInt32})` an outer constructor since it's just a convenience function:
> It is considered good form to provide as few inner constructor methods as possible: only those taking all arguments explicitly and enforcing essential error checking and transformation. Additional convenience constructor methods, supplying default values or auxiliary transformations, should be provided as outer constructors that call the inner constructors to do the heavy lifting.

http://julia.readthedocs.org/en/latest/manual/constructors/

**Comment by ScottPJones** [comment]
Done, and added test cases

**Pull request merged**
