### PR TITLE
deprecate (silently) Distributed `@spawn` to `@spawnat :any`

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vtjnash** [comment]
Should it be `@spawnat nextproc() expr` (the literal expansion of the functions) or `@spawnat rand expr` (i.e. the function object named `rand` 😜)?

**Review by Keno — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Maybe `@spawnat :any <expr>` since one can legitimately write
```jl
any = 5
@spawnat any <expr>
```
(Or `@spawnat ? 1+1` which is currently an "invalid identifier name" error.)

**Review by vchuravy — APPROVED** [review]

**Comment by Keno** [comment]
`@spawnat _ <expr>`, since we deprecated `_` as an identifier.

**Comment by JeffBezanson** [comment]
Hmm, nice idea.

**Comment by chethega** [comment]
This will break all current uses of `Distributed.@spawn` (which was exported). Do we have an estimate on how many people will be affected? 

What is the migration story for current users of `Distributed.@spawn`? We need to communicate a way for such users to write their code such that it runs on all 1.* versions. This can be compat code that does version detection and backports `Distributed.@spawnat` if running on up to `1.2`, and recreates the old `Distributed.@spawn` on `1.3` or later.

Stdlib is not `Base`, but this still looks sketchy: No deprecation period, minor release, breaks user code for the sake of stealing a nice name instead of necessary bugfixes, silently corrupts behavior of user code without any warning or error message.

**Comment by JeffBezanson** [comment]
This doesn't break anything; `Distributed.@spawn` is still there and exported. I think the only possible problem is if code does both `using Distributed` and `using Base.Threads`, which might both export `@spawn`. But this PR doesn't do that. If that's a serious concern, we can just avoid exporting `@spawn` from `Base.Threads` (and you can `import Base.Threads: @spawn` to use it).

**Comment by chethega** [comment]
Ok, I failed at reading comprehension. Sorry for bringing up bogus concerns.

**Comment by StefanKarpinski** [comment]
Note that code that's doing `using Distributed, Base.Threads` is technically relying on unstable internals and so breaking it is allowed. Code that only does `using Distributed` won't break.

**Pull request merged**
