### PR TITLE
Use broadcast for some operations in arraymath

### PR DESCRIPTION
**Pull request by andreasnoack**
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19746) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d2befa78663670e81505d14d0a8394669441336c/e0f6487_vs_309657f/report.md). cc @jrevels

**Comment by andreasnoack** [comment]
Couldn't reproduce the regressions locally so will assume that they are noise.

**Comment by pabloferz** [comment]
For small arrays there's going to be just a tiny overhead for things like `broadcast!(conj, A, A)` since we make sure that the shape of the arrays are compatible. We should probably have a non-size-checking `broadcast!` version.

**Comment by andreasnoack** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19746#issuecomment-269577868) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/eed2f82d5aa4f404f457a2f872c724c6dcebb620/1d187c8_vs_99fcb5b/report.md). cc @jrevels

**Comment by andreasnoack** [comment]
@nanosoldier `runbenchmarks("linalg", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19746#issuecomment-269627949) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/73446349201a788914c5949857cc529ebdba03f6/7442a89_vs_b561cfb/report.md). cc @jrevels

**Comment by KristofferC** [comment]
What changed from the previous nanosoldier run?

**Comment by andreasnoack** [comment]
`map` -> `broadcast`. I thought that `map` would be faster because it is simpler but for some reason `broadcast` is much faster. We should probably try to figure out why `map` is slower.

**Comment by andreasnoack** [comment]
Anybody knows what this test failure is https://travis-ci.org/JuliaLang/julia/jobs/187453412#L1598?

**Comment by Sacha0** [comment]
Refencing #17321 re. the `map` versus `broadcast` perf issue. Best!

**Comment by tkelman** [comment]
If someone restarted the travis job here, **please** back up the raw log to a gist before you do that next time. It looks like the error was repeatable in this case, but if it weren't, restarting Travis would have overwritten the log and we would have lost the ```julia: /home/travis/build/JuliaLang/julia/deps/srccache/llvm-3.7.1/lib/MC/MCAsmStreamer.cpp:308: virtual void {anonymous}::MCAsmStreamer::EmitLabel(llvm::MCSymbol*): Assertion `Symbol->isUndefined() && "Cannot define a symbol twice!"' failed.``` error.

**Comment by tkelman** [comment]
there's a problem in the test system right now that isn't correctly failing builds when run in parallel. that assertion failure looks real.

**Pull request merged**
