### PR TITLE
Expose constrained memory limits and have the GC use them

### LINKED ISSUE #24617: cgroup aware `Base.Sys.cpu_info` and `Base.Sys.total_memory`
Not sure if it is possible, but it will be good to have `Base.Sys.cpu_info` and `Base.Sys.total_memory` aware of linux cgroups and report cgroup info instead.

It will also be useful when Julia is being run within a docker container with cgroup limits.

### PR DESCRIPTION
**Pull request by maleadt**
This includes https://github.com/libuv/libuv/pull/3744, which should make it possible to fix https://github.com/JuliaLang/julia/issues/24617. I still need to verify this, so marking this PR draft until I do.

According to @vtjnash, it should also be safe to backport this to https://github.com/JuliaLang/libuv/pull/24#issuecomment-1244119901.

### CODE REVIEW

**Comment by maleadt** [comment]
This works as expected:

```
❯ ./julia -e '@show Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ()))'
Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())) = "62.222 GiB"
Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())) = "16384.000 PiB"

❯ systemd-run --user --scope -p MemoryLimit=3G ./julia -e '@show Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ()))'
Running scope as unit: run-r06bcd75bb4bd4648be798311727f5fb5.scope
Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())) = "62.222 GiB"
Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())) = "3.000 GiB"
```

The GC should automatically use this, but in addition I guess we want to expose this to the Julia user. Anybody any thoughts on an interface? The easiest solution would be for `Sys.total_memory` to keep on returning the total memory amount and add a `Sys.constrained_memory` to return the constrained version. Although it might be simpler/user-friendlier to just change `Sys.total_memory` to return the effective amount (i.e. the constrained one if there's a limit).

**Comment by gbaraldi** [comment]
I would be in favor of making `total_memory` reflect the constrained memory. Not sure how useful it is to know how much memory the whole machine has if one can't access it.

**Comment by KristofferC** [comment]
> Not sure how useful it is to know how much memory the whole machine has if one can't access it.

And that could always be provided with a `Sys.unconstrained_memory`

**Comment by maleadt** [comment]
Yeah I agree. I pushed a change to `Sys.total_memory()`, and added `Sys.physical_memory()` (bikeshed away).

We should probably make `free_memory` cgroup aware too, though, since it currently doesn't reflect that:

```
❯ ./julia -e '@show Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_free_memory, UInt64, ()))'
Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())) = "62.222 GiB"
Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())) = "16384.000 PiB"
Base.format_bytes(ccall(:uv_get_free_memory, UInt64, ())) = "56.181 GiB"

❯ systemd-run --user --scope -p MemoryLimit=3G ./julia -e '@show Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())); @show Base.format_bytes(ccall(:uv_get_free_memory, UInt64, ()))'
Running scope as unit: run-r369d2f0373524fef8f0cab15ec87f903.scope
Base.format_bytes(ccall(:uv_get_total_memory, UInt64, ())) = "62.222 GiB"
Base.format_bytes(ccall(:uv_get_constrained_memory, UInt64, ())) = "3.000 GiB"
Base.format_bytes(ccall(:uv_get_free_memory, UInt64, ())) = "56.123 GiB"
```

The GC also uses `uv_get_free_memory`, so this means there is more work to do.

**Comment by gbaraldi** [comment]
It would require adding something like `uv_get_free_constrained_memory` or can we just do or own calculations?

**Comment by vtjnash** [comment]
This may conflict with https://github.com/JuliaLang/julia/pull/46663, which includes https://github.com/JuliaLang/julia/pull/46086

**Comment by vtjnash** [comment]
Sorry, I read it backwards. Right, so this will conflict less with the backports, once that is merged.

**Comment by maleadt** [comment]
> It would require adding something like `uv_get_free_constrained_memory` or can we just do or own calculations?

We need to query cgroup's `memory.current`, so ideally we add that to libuv. I've pinged the maintainer about that.

**Comment by ViralBShah** [comment]
It would be great if 1.8.2 could include this.

**Comment by KristofferC** [comment]
> It would be great if 1.8.2 could include this.

We want to release 1.8.2 quite soon so the question here is what the time frame in https://github.com/JuliaLang/julia/pull/46796#issuecomment-1249457479:

> so this means there is more work to do.

Upstream libuv is moving quite slow and I don't want 1.8.2 to have to wait a significant time for them to review something. So the options I see are:

- Merge this as is and get it into 1.8.2 (even though there is still a small part left).
- Get lucky and get a fast review of the remaining task so we can quickly put it in 1.8.2.
- Leave this out of 1.8.2.

**Comment by KristofferC** [comment]
After speaking to @maleadt, it seems reasonable to put this behind a feature flag in 1.8.2 since changing the default GC behavior in a patch release is probably a bit too intrusive.

**Comment by ViralBShah** [comment]
I believe the memory utilization is way higher in many workloads compared to 1.7. This should be the default, I feel.

**Comment by maleadt** [comment]
This PR should be complete. I'll do some more testing tomorrow and create a backport version for 1.8.

The only user-visible change is the addition of `Sys.free_physical_memory` and `Sys.total_physical_memory` as counterparts to `Sys.free_memory` and `Sys.total_memory` which now respect and memory constraints. As we're kind-of rushing this change (I'd like to merge this tomorrow), now is the change to bikeshed these names!

**Comment by simonbyrne** [comment]
I'm trying this on the current nightly (f927d25f21) on our Slurm cluster which enforces memory limits via cgroups, and it doesn't seem to match with what I see:
```julia
julia> Sys.total_physical_memory() / 2^20 # physical mem (MB)
257693.1796875

julia> Sys.total_memory() / 2^20  # should be memory limit (MB)
257693.1796875

julia> mem_cgroup = match(r".*:memory:(.*)", read("/proc/$(getpid())/cgroup", String)).captures[1] # current memory cgroup
"/slurm/uid_5184/job_28896711/step_0"

julia> parse(Int, readchomp("/sys/fs/cgroup/memory/$mem_cgroup/memory.limit_in_bytes")) / 2^20 # cgroup memory limit (MB)
2048.0
```

**Comment by simonbyrne** [comment]
For reference:
```julia
julia> ccall(:uv_get_constrained_memory, UInt64, ())
0x0000000000000000
```

**Comment by simonbyrne** [comment]
Ah, okay, it looks like we're not using cgroups2. 😦

**Comment by gbaraldi** [comment]
Just as a test. Could you use Hwloc.jl to see what it prints out?

**Comment by simonbyrne** [comment]
what command in particular?
```
julia> Hwloc.topology()
Machine (251.65 GB)
    Package L#0 P#0 (125.66 GB)
        NUMANode (125.66 GB)
        L3 (35.0 MB) + L2 (256.0 kB) + L1 (32.0 kB) + Core L#0 P#0
            PU L#0 P#0
    Package L#1 P#1 (126.0 GB)
        NUMANode (126.0 GB)
```

**Comment by gbaraldi** [comment]
That was the one I was thinking of. I'm not sure they have others. But it seems it doesn't see the limit as well.

**Comment by simonbyrne** [comment]
I have a proposed fix at https://github.com/JuliaLang/libuv/pull/27, I'm not sure if it's correct though

**Pull request merged**
