### PR TITLE
DO NOT MERGE: build hang on `jl_mutex_unlock`

### PR DESCRIPTION
**Pull request by timholy**
I may have done something stupid here, but this hangs while building `subarray.jl` and gdb says it's in `jl_mutex_unlock` (the `JL_SIGATOMIC_END` call).

I can try to trim this down further, but this way I won't lose it.

### CODE REVIEW

**Comment by yuyichao** [comment]
I guess make sure you abort the CI if you expect it to hang.

**Comment by timholy** [comment]
Just did now, but thanks for reminding me!

**Comment by yuyichao** [comment]
I don't get a hang in `mutex` rather a infinite loop of method error which is typical for bootstrap error reporting (that we should fix). The original error was

```jl
LoadError(at "sysimg.jl" line 71: LoadError(at "subarray.jl" line 239: ErrorException("syntax: extra token ")" after end of expression")))
```

**Comment by timholy** [comment]
Yep, I was just stupid.

**Comment by vtjnash** [comment]
> that we should fix

agreed, patch here:
https://github.com/JuliaLang/julia/pull/17057/files#diff-53dc66d2cb199a2ea107533c1f99f57bR1066

**Comment by yuyichao** [comment]
I was going to suggest using `jl_static_show` instead. Constructing the method error directly is probably better....

**Pull request closed without merging**
