### PR TITLE
add a version of `code_typed` that accepts a function type

### PR DESCRIPTION
**Pull request by JeffBezanson**
...instead of an instance. I need this all the time; is there another convenient way to do it that I missed?

### CODE REVIEW

**Comment by Keno** [comment]
No, this is good to have. I think there's like 15 different versions of this in external packages.

**Review by vtjnash — APPROVED** [review]

**Comment by timholy** [comment]
We probably also want a variant of `which` that takes a tuple-type signature.

**Comment by yuyichao** [comment]
Does it still have to be a separate argument in this case? (Shouldn’t it just/also accept a triple type or tulle of types)

**Comment by Keno** [comment]
Maybe we should also have a version that just takes the whole signature tuple.

**Comment by JeffBezanson** [comment]
Ok, will add.

**Pull request merged**
