### PR TITLE
changes for random for the wasm target

### PR DESCRIPTION
**Pull request by SimonDanisch**
### That change is likely problematic?!
```
-               --param max-inline-insns-single=1800 -Wmissing-prototypes -Wall  -std=c99 -shared
+               -Wmissing-prototypes -Wall  -std=c99 -shared
```

### TODO 
changes need to be conditional on wasm platform but aren't yet!

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can we check that it doesn't create a performance regression?

**Comment by SimonDanisch** [comment]
This is pretty deep in the prototype world and will get merged into kf/wasm3 first ;) So I don't think we need to do any such thing!

**Comment by SimonDanisch** [comment]
I changed the title to reflect that this is for the wasm target!

**Comment by ViralBShah** [comment]
Ah ok. Carry on.

**Comment by Keno** [comment]
Awesome, let me cherry pick these changes and I'll regenerate the interpreter to include dsfmt.

**Comment by Keno** [comment]
I'm seeing
```
julia> rand(10, 10)
TypeError(func=:new, context="", expected=DataType, got=Tuple{Random.DSFMT.DSFMT_state, Ptr{T}, Int32})
```
did you see that locally?

**Comment by ViralBShah** [comment]
For wasm, why not just replace dsfmt with one of the pure Julia RNGs?

**Comment by Keno** [comment]
Probably a sensible thing to do. Worth understanding the error though, because it'll likely have a deeper underlying cause.

**Comment by Keno** [comment]
```
julia> r = Random.GLOBAL_RNG
julia> (r.state, pointer(r.vals), length(r.vals))
TypeError(func=:new, context="", expected=DataType, got=Tuple{Random.DSFMT.DSFMT_state, Ptr{T}, Int32})
```
It's a bit weird. It won't let us form that tuple.

**Comment by Keno** [comment]
Well that looks wrong:
```
julia> typeof(Base.unsafe_convert(Ptr{Float64}, Float64[1.0]))
Ptr{T}
```

**Comment by Keno** [comment]
Found the issue. I've pushed a fixed and cherry-picked these commits. Random number generation works now for me. Thanks @SimonDanisch

**Pull request closed without merging**
