### PR TITLE
go gentle into that good night, full

### LINKED ISSUE #229: Use a name other than `full` for returning original array from a factorization
ref discussion in JuliaLang/julia#12137. Calling this operation `full` and returning anything other than a dense array from `full` is fishy to me. I think it's different enough to warrant a separate name, though I'm not sure what that name should be. Maybe this is an uncommon enough operation that we just force the user to know what type it came from and use `convert`. Or we come up with something new, `ifactorize` maybe? Suggestions welcome.

### LINKED ISSUE #12153: Use a name other than `full` for returning original array from a factorization
ref discussion in #12137. Calling this operation `full` and returning anything other than a dense array from `full` is fishy to me. I think it's different enough to warrant a separate name, though I'm not sure what that name should be. Maybe this is an uncommon enough operation that we just force the user to know what type it came from and use `convert`. Or we come up with something new, `ifactorize` maybe? Suggestions welcome.

### PR DESCRIPTION
**Pull request by Sacha0**
Dylan Thomas would much admire how you have raged, raged against the dying of the light, `full`. But even he would insist that close of day has come. So go gentle into that good night, `full`. And when you do, please take JuliaLang/LinearAlgebra.jl#229, JuliaLang/LinearAlgebra.jl#231, and JuliaLang/julia#18850 with you.

(... in case that reference is too obscure, this pull request finally deprecates `full`, and closes JuliaLang/LinearAlgebra.jl#229, JuliaLang/LinearAlgebra.jl#231, and JuliaLang/julia#18850. Best!)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
That's one hell of a deprecation.

**Comment by Sacha0** [comment]
Updated with PR# in NEWS.md. Absent objections or requests for time, I plan to merge this deprecation in the next day or two. Best!

**Review by fredrikekre — APPROVED** [review]

**Comment by andreasnoack** [comment]
It looks like there is still an `import full` in `linalg.jl` which needs to go. No idea why AppVeyor times out.

**Comment by Sacha0** [comment]
> It looks like there is still an import full in linalg.jl which needs to go.

https://www.youtube.com/watch?v=Tim5nU3DwIE

**Comment by Sacha0** [comment]
Thanks all! :)

**Pull request merged**
