### PR TITLE
Avoid `reshape` inside `kron`

### PR DESCRIPTION
**Pull request by mcabbott**
This replaces `reshape` with `ReshapedArray` in the definition of `kron`. They should never escape. The reason to do so is to save a few allocations:
```julia
julia> @btime kron(x,x)  setup=(x=randn(3));
  65.136 ns (7 allocations: 400 bytes)  # before
  22.275 ns (1 allocation: 128 bytes)   # after

julia> @btime kron(x,x)  setup=(x=randn(100));
  1.196 μs (8 allocations: 78.44 KiB)
  1.167 μs (2 allocations: 78.17 KiB)

julia> @btime kron(x,y)  setup=(x=randn(3); y=randn(4,5));
  62.840 ns (3 allocations: 640 bytes)
  48.371 ns (1 allocation: 544 bytes)
```

### CODE REVIEW

**Comment by andreasnoack** [comment]
Might be useful to explain why there is a difference in allocations here.

**Comment by mcabbott** [comment]
Indeed, the allocation is from `reshape(::Array, ...)`, issue https://github.com/JuliaLang/julia/issues/36313 . It's O(1) so only matters for small arrays.

**Comment by dkarrasch** [comment]
This seems to improve performance in the small cases, to not hurt in the large and to be safe. Any objections against merging?

**Comment by mcabbott** [comment]
One concern is breaking something for weird array types. If they overload `reshape` then perhaps the ReshapedArray in `kron!` is inferior. The `c = Vector{...}` in `kron` is I suppose no worse than the existing `R = Matrix{...` for matrices.

**Comment by dkarrasch** [comment]
Honestly, I think the `kron!` for vectors should just be spelled out, and with `eachindex` this can be made to work without one-based indexing. Similarly, the matrix-`kron!` can drop the one-based-indexing requirement by switching to `axes`. Then it only remains to decide about the mixed cases. Moreover, I think the usage of `@inbounds` to turn off size-checking is not quite in line with how it's supposed to be used. May I mess around with your PR?

**Comment by mcabbott** [comment]
Yes for sure, feel free to edit. 

I agree that writing a separate loop for vectors would probably be a nicer end result than this. And that it would not be very hard to make it use `axes` at least for the input --- I presume the output would remain `OneTo(n*m)`?

I have no serious need for this, it was just something someone complained about and I thought perhaps could be fixed easily.

**Comment by dkarrasch** [comment]
I went the route to spell out the few cases explicitly. This is exhaustive, so no more is needed. The original benchmark now reads on my machine as

```julia
julia> using LinearAlgebra, BenchmarkTools

julia> @btime kron(x,x)  setup=(x=randn(3));
  125.787 ns (7 allocations: 400 bytes) # 20 days old master
  47.219 ns (1 allocation: 128 bytes)

julia> @btime kron(x,x)  setup=(x=randn(100));
  5.047 μs (8 allocations: 78.44 KiB)
  4.800 μs (2 allocations: 78.17 KiB)
julia> @btime kron(x,y)  setup=(x=randn(3); y=randn(4,5));
  139.422 ns (3 allocations: 640 bytes)
  120.805 ns (1 allocation: 544 bytes)
```

**Pull request merged**
