### PR TITLE
WIP: Backports release 1.4.2

### LINKED ISSUE #35134: regression printing unusual Exprs inside nested quote
Reported on slack. Caused by part of #32423; we will probably have to revert that bit.

```
julia> ex = Expr(:quote, Expr(:quote, Expr(:foo)))
:(:(:($(Expr(:foo)))))

julia> eval(Meta.parse(repr(ex))) == ex
false
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #35080 - Fix MacOS Notarization
- [x] #35378 - precompile: avoid a potential crash when adding methods
- [x] #35363 - add null check for module-default-defs
- [x] #35545 - implement LibuvStream interface for BufferStream
- [x] #35579 - Add a fast path for returning "" from repeat(str, 0)
- [x] #35555 - exclude types with free variables from `type_morespecific`
- [x] #35590 - fix buggy rand(RandomDevice(), Bool)
- [x] #35695 - Fix dropped bytes when bulk reading from uv streams with oversized bufs
- [x] #35728 - Fix and test PCRE error message getter.
- [x] #35758 - Have matrix square root account for Rii=Rjj=0 to prevent NaN values
- [x] #35479 - fix #35134, regression in printing nested quote Exprs
- [x] Bump Pkg version

Need manual backport:
- [ ] #34935 - [WIP] Bump SuiteSparse to 5.4.0+6

Non-merged PRs with backport label:
- [ ] #35232 - LibGit2: add resolve_url to RemoteCallbacksStruct for LibGit2 0.99.0

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs =":release-1.4")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/35825#issuecomment-626384037) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d0480bf874494d3bb152c505f44e1559adaa2cdc/58353fd_vs_ef4fe83/report.md). cc @ararslan

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35825#issuecomment-627136114) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/7e409e655efd24ff34f2173309a7b2ccc1855531/pkgeval/by_hash/c0b1a0c_vs_ef4fe83/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ARCHModels", "Autologistic", "BlobTracking", "BoltzmannMachines", "BufferedStreams", "DiffEqBayes", "DiskDataProviders", "Graph500", "KrylovKit", "MriResearchTools", "NeuralArithmetic", "TensorNetworkAD"], vs = ":release-1.4")`

**Comment by maleadt** [comment]
Doing some PkgEval development, sorry for the noise.

@nanosoldier `runtests(["ARCHModels", "Autologistic", "BlobTracking", "BoltzmannMachines", "BufferedStreams", "DiffEqBayes", "DiskDataProviders", "Graph500", "KrylovKit", "MriResearchTools", "NeuralArithmetic", "TensorNetworkAD"], vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35825#issuecomment-628038206) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/9d5cd7167b4326f1cf330d2068f358f8f33aef20/pkgeval/by_hash/c0b1a0c_vs_ef4fe83/report.md). cc @maleadt

**Pull request merged**
