### PR TITLE
Do not show the type of intrisics when it's `Any`

### LINKED ISSUE #13568: code_warntype shows ANY for expressions involving UInt32
I'm noticing various surprising `ANY` annotations for some code involving `UInt32` calculations. For example, `@code_warntype typemax(UInt32(3))` produces:
```
Variables:
  x::UInt32

Body:
  begin  # float.jl, line 382:
      return (Base.box)(UInt32,(Base.checked_trunc_uint)(UInt32,4294967295)::ANY)::UInt32
  end::UInt32
```

### PR DESCRIPTION
**Pull request by yuyichao**
This basically disables the printing of `::Any` for intrinsics. AFAIK, an intrinsic will be infered to `Any` only when it is expected to be boxed right after that. This also fix the suppression of type printing for `box`.

Before
code_warntype before

After
code_warntype after

Closes https://github.com/JuliaLang/julia/issues/13568

### CODE REVIEW

**Comment by timholy** [comment]
Nice!

**Comment by hayd** [comment]
Would be good to have a test for this.

**Comment by yuyichao** [comment]
..... I was going to add the test - - ...

**Comment by KristofferC** [comment]
Could this be backported?

**Comment by tkelman** [comment]
it's on the list. will put 0.4.1 together once 0.3.12 is all done.

**Pull request merged**
