### PR TITLE
Fix inference with const opaque closure

### LINKED ISSUE #40409: Illegal instruction interpolating an opaque closure into at-btime
I searched around and didn't see a prior issue for this. Interpolating an `@opaque` closure into a `@btime` body causes an illegal instruction error in the runtime.

MWE:
```julia
julia> using Base.Experimental: @opaque

julia> f = let x = 1
           @opaque () -> x += 1
       end
()::Any->◌

julia> @btime f()
  2.621 μs (25 allocations: 1.78 KiB)
500504

julia> @btime $f()
Unreachable reached at 0x7f7014038099

signal (4): Illegal instruction
in expression starting at REPL[4]:1
##sample#287 at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:377
#_run#6 at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:405
_run##kw at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:399
unknown function (ip: 0x7f70140383fb)
jl_apply at /home/mason/build/julia-dev/src/julia.h:1764 [inlined]
jl_f__call_latest at /home/mason/build/julia-dev/src/builtins.c:751
#invokelatest#2 at ./essentials.jl:723 [inlined]
invokelatest##kw at ./essentials.jl:719 [inlined]
#run_result#37 at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:32 [inlined]
run_result##kw at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:32 [inlined]
#run#40 at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:94
run##kw at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:94 [inlined]
run##kw at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:94 [inlined]
#warmup#45 at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:141 [inlined]
warmup at /home/mason/.julia/packages/BenchmarkTools/eCEpo/src/execution.jl:141
jl_apply at /home/mason/build/julia-dev/src/julia.h:1764 [inlined]
do_call at /home/mason/build/julia-dev/src/interpreter.c:117
eval_value at /home/mason/build/julia-dev/src/interpreter.c:206
eval_stmt_value at /home/mason/build/julia-dev/src/interpreter.c:157 [inlined]
eval_body at /home/mason/build/julia-dev/src/interpreter.c:575
jl_interpret_toplevel_thunk at /home/mason/build/julia-dev/src/interpreter.c:718
jl_toplevel_eval_flex at /home/mason/build/julia-dev/src/toplevel.c:884
jl_toplevel_eval_flex at /home/mason/build/julia-dev/src/toplevel.c:829
jl_toplevel_eval_flex at /home/mason/build/julia-dev/src/toplevel.c:829
jl_toplevel_eval_in at /home/mason/build/julia-dev/src/toplevel.c:936
eval at ./boot.jl:369 [inlined]
eval_user_input at /home/mason/build/julia-dev/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:139
repl_backend_loop at /home/mason/build/julia-dev/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:200
start_repl_backend at /home/mason/build/julia-dev/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:185
#run_repl#43 at /home/mason/build/julia-dev/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:318
run_repl at /home/mason/build/julia-dev/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:305
#893 at ./client.jl:394
jfptr_YY.893_37823 at /home/mason/build/julia-dev/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/mason/build/julia-dev/src/julia.h:1764 [inlined]
jl_f__call_latest at /home/mason/build/julia-dev/src/builtins.c:751
#invokelatest#2 at ./essentials.jl:721 [inlined]
invokelatest at ./essentials.jl:719 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:495
jfptr__start_42888 at /home/mason/build/julia-dev/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/mason/build/julia-dev/src/julia.h:1764 [inlined]
true_main at /home/mason/build/julia-dev/src/jlapi.c:560
repl_entrypoint at /home/mason/build/julia-dev/src/jlapi.c:702
main at /home/mason/build/julia-dev/cli/loader_exe.c:51
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at ./julia (unknown line)
Allocations: 18661064 (Pool: 18659844; Big: 1220); GC: 15
Illegal instruction (core dumped)
```
Here's my version info:
```julia
julia> versioninfo()
Julia Version 1.7.0-DEV.888
Commit b5391980f0* (2021-04-08 21:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 6
```

I'll also not that this occurs for me if I create `f` as a `const` as well.

### PR DESCRIPTION
**Pull request by tkf**
Currently, using constant opaque closure (e.g., a global const or `@benchmark` #40409) introduces an illegal instruction error. MWE:

```julia
const oc = Base.Experimental.@opaque () -> 0
f() = oc()
f()
```

This is because of the incorrect inference:

```julia
julia> @code_typed optimize=false f()
CodeInfo(
1 ─     Main.oc()::Union{}
└──     Core.Const(:(return %1))::Union{}
) => Union{}
```

This seems to be simply due to a missing `widenconst` in inference.

fix #40409

### CODE REVIEW

**Comment by vtjnash** [comment]
If this fixes it, it seems like there is also a deeper underlying bug too that must be fixed also.

**Review by aviatesk — APPROVED** [review]
LGTM, since this pass is supposed to handle a case when only the data type of an opaque closure is known, and we should use `widenconst` when working on `Type` objects.

**Comment by tkf** [comment]
Do you mean we need to fix something between the inference and codegen? But it looks like a correct codegen to me given the inference `Main.oc()::Union{}`? In Julia 1.7, I get

```
julia> @code_llvm f()
;  @ REPL[2]:1 within `f`
; Function Attrs: noreturn
define nonnull {}* @julia_f_184() #0 {
top:
  %0 = call nonnull {}* @jl_apply_generic({}* inttoptr (i64 140356399876112 to {}*), {}** null, i32 0)
  call void @llvm.trap()
  unreachable
}
```

**Comment by tkf** [comment]
Do we need other actions before merging this? Or should we close this PR and wait for a real fix?

**Comment by vtjnash** [comment]
Yes, `Main.oc()::Union{}` is wrong from inference

**Comment by vtjnash** [comment]
It is supposed to be handled by the check on line 1378, for example, but it isn't reaching there apparently.

**Comment by tkf** [comment]
But we don't hit it since `singleton_type(ft) === oc !== nothing`, right? `oc` is not a singleton in the sense of `issingletontype`. But from the definition of `singleton_type`, it seems intentional that it behaves this way (unwraps `Const`)

https://github.com/JuliaLang/julia/blob/011fda9c7892e1bf34f22f0974aaa74fb6bcbc2a/base/compiler/utilities.jl#L266-L275

(TBH, `singleton_type` is a confusing name for me maybe because I'm not familiar with the inference code. It sounds like `known_value` or `const_value` seems to reflect what it returns. It also seems to be tricky to use for cases where you could have `Cons(nothing)`.)

**Review by vtjnash — COMMENTED** [review]
actual correctness requires both patches

**Comment by DilumAluthge** [comment]
@tkf Can you rebase this on the latest master? That should fix the Downloads test failures.

**Comment by DilumAluthge** [comment]
I am eventually going to implement a new Buildkite command that will automatically rerun the entire Buildkite job with the updated merge commit. Once I've done that, you won't need to rebase; you'll be able to run this new command. But it'll be a while before that is ready.

**Comment by tkf** [comment]
I'm pretty sure this PR will be squash-merged. So it doesn't have to be rebased, I suppose? It's good to leave edit and CI history in the PR, which will be hard to reconstruct with rebase.

**Comment by KristofferC** [comment]
Needs a manual backport.

**Comment by aviatesk** [comment]
done backport

**Pull request merged**
