### PR TITLE
avoid kind type dispatch bugs in tuple_type_head and tuple_type_tail

### PR DESCRIPTION
**Pull request by jrevels**
This is a much more narrowly-scoped alternative to some of the tuple code changes that were originally in #27736 (i.e. https://github.com/JuliaLang/julia/commit/c16a1096a0f97a0538fa54a4f0885b27af1ae6e8).

It would still be nice eventually to figure out alternative implementations for https://github.com/JuliaLang/julia/commit/c16a1096a0f97a0538fa54a4f0885b27af1ae6e8, since switching to `fieldtype` is more sound in general (see discussion from #27736). However, for now, this much more palatable change works around the problems that are blocking Cassette.

Unfortunately, I don't have a non-Cassette test case for these bugs yet; they're pretty hard to work out MWEs for.

### CODE REVIEW

**Comment by jrevels** [comment]
will merge tomorrow if there are no objections

**Comment by jrevels** [comment]
(let's make sure nanosoldier doesn't object) 

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by martinholters** [comment]
I didn't follow along what issues this is solving, but ... can't they be tested for?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27776#issuecomment-400111137) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6714712a68b0f53eaf22ada0ebb117af75b1e4cf/394bc4a_vs_c446444/report.md). cc @ararslan

**Comment by jrevels** [comment]
> I didn't follow along what issues this is solving, but ... can't they be tested for?

Definitely, it'd be great to have a non-Cassette MWE here, I just haven't figured one out yet. From the OP:

> Unfortunately, I don't have a non-Cassette test case for these bugs yet; they're pretty hard to work out MWEs for.

If you're curious, here's a Cassette-based one I posted: https://github.com/JuliaLang/julia/pull/27736#discussion_r197831222

Looks like Nanosoldier doesn't like the new implementations...maybe adding a `@_pure_meta` to `tuple_type_head` will fix it? Let's see...

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27776#issuecomment-400397569) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e68e5539ae1e64a5073ae9bf135149b3f3ab97d2/e9a5fbb_vs_feb9260/report.md). cc @ararslan

**Comment by jrevels** [comment]
Cool, the `@_pure_meta` seemed to do the trick.

**Pull request merged**
