### PR TITLE
support missing in radians-degrees conversions

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Review by KristofferC — CHANGES_REQUESTED** [review]
https://github.com/JuliaLang/julia/pull/35066 probably needs to be discussed first

**Comment by aplavin** [comment]
Ok, I just thought this is an accidental omission, i.e. someone just forgot to add these functions to the list. For now the choice of which math functions propagate missing and which don't seems arbitrary for me.

**Comment by KristofferC** [comment]
> For now the choice of which math functions propagate missing and which don't seems arbitrary for me.

Indeed, that is the crux of it.

**Comment by JeffBezanson** [comment]
A possible solution here is just to remove the type restriction from
```
rad2deg(z::Number) = (z/pi)*180
deg2rad(z::Number) = (z*pi)/180
```

**Pull request closed without merging**
