### PR TITLE
fix part of #21016, specificity of `BottomType`

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Hmm, there may be more to this. I noticed

```
julia> Core.BottomType <: Type{T} where T<:Real
false
```

which seems wrong.

**Comment by martinholters** [comment]
At least it is somewhat consistent:
```julia
julia> typeof(Real) <: Type{T} where T<:Real
false

julia> typeof(Int) <: Type{T} where T<:Real
false

julia> typeof(Union{}) <: Type{T} where T<:Real
false
```
Here, the first two are `DataType` of course, while the last one is `Core.BottomType`, but it would be mildly surprising if only the last one gave true here, wouldn't it? (Arguably, one might expect all of them to return true, which indeed they do if the `<:Real` restriction is removed from the RHS, but for that to work, `typeof` would need to return the respective `Type{...}` instead of  `DataType` or `Core.BottomType`.)

**Comment by vtjnash** [comment]
`Type{Bottom} <: Core.BottomType <: Type` seems consistent to me.

**Comment by JeffBezanson** [comment]
`DataType` is a really big set of types. Lots of types are DataTypes, so DataType is not a subset of something like `Type{T} where T<:Real`. However `BottomType` is a set of one type --- `Bottom` --- and `Bottom` is a subtype of `Real`, so `BottomType` is a subset of the set of types <: Real.

**Comment by JeffBezanson** [comment]
#21015 again.

**Comment by JeffBezanson** [comment]
By a slightly circuitous route this got me working on the serializer, and I ended up fixing another mostly-unrelated bug here.

**Pull request merged**
