### PR TITLE
Grouped docstrings for FFTW in an if USE_GPL_LIBS block

### PR DESCRIPTION
**Pull request by nkottary**
Docstrings in helpdb.jl for functions defined in base/fft/ are grouped in an if USE_GPL_LIBS block.
Related to Pull request #13117 and issue #13060.

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Docstrings in `if` blocks, and other non-toplevel blocks, don't get automatically wrapped in ``@doc`` so you'll need add `@doc ... ->` syntax to each one for the docsystem to find them. (We need to add mention of this to the manual.)

Perhaps these docs could be moved out of ``helpdb.jl`` and to their respective definitions in `FFTW` instead? That should avoid needing to use `@doc` directly.

**Comment by tkelman** [comment]
do the `plan_*fft` docstrings need to be moved?

**Comment by nkottary** [comment]
Yes they would need to be moved to base/dft.jl. But the above changes are what is required to prevent build `make USE_GPL_LIBS=1` from breaking.

**Comment by nkottary** [comment]
I mean `make USE_GPL_LIBS=0`

**Comment by ViralBShah** [comment]
Yes, we need to move the `plan_*fft` docstrings too out of helpdb.jl

**Comment by JeffBezanson** [comment]
Bump. Looks ready to merge?

**Comment by tkelman** [comment]
some unrelated changes snuck in here

**Comment by JeffBezanson** [comment]
Possibly due to a merge conflict?

**Comment by tkelman** [comment]
merge instead of rebase, more likely

**Comment by tkelman** [comment]
I'll assume the intent is for this to only contain
f21e2490584da11eb104402ec95fb601fbd5110d
897c6e9f18a4c4fbd4cba46e6c985f7c7380a823
0479ea0767c127a9ebe696217f9a89724c8d5004

**Comment by nkottary** [comment]
Yes.

**Comment by ViralBShah** [comment]
Perhaps close this one and create a new clean PR?

**Comment by tkelman** [comment]
I'm just going to cherry-pick those 3 commits and push them to master.

**Comment by tkelman** [comment]
backported in #13182

**Pull request closed without merging**
