### PR TITLE
Test dimensional reduce with non-bitstype

### LINKED ISSUE #26709: reducedim allocates array of incorrect eltype
To compute the `eltype` of the array storing the result, `reducedim` does
https://github.com/JuliaLang/julia/blob/bce5bbef9ba4b0a30a857d9032c00b1375de73ff/base/reducedim.jl#L119
I don't understand the reasoning behind the condition `typeof(z) == typeof(x) && !isbits(T)`. Why not just do `Tr = typeof(z)` ?

Here is a MWE:
```julia
struct Variable
    name::Symbol
end
struct AffExpr
    vars::Vector{Variable}
end
Base.zero(::Union{Variable, Type{Variable}, AffExpr}) = AffExpr(Variable[])
Base.:+(v::Variable, w::Variable) = AffExpr([v, w])
Base.:+(aff::AffExpr, v::Variable) = AffExpr([aff.vars; v])
Base.:+(aff1::AffExpr, aff2::AffExpr) = AffExpr([aff1.vars; aff2.vars])
```
The reduction fails because `Tr` is `Variable` instead of `AffExpr`. `typeof(z)` and `typeof(x)` are `AffExpr` and `isbits(Variable)` is `false`.
```julia
julia> sum([Variable(:x), Variable(:y)], 1)
ERROR: MethodError: Cannot `convert` an object of type AffExpr to an object of type Variable
This may have arisen from a call to the constructor Variable(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] fill!(::Array{Variable,1}, ::AffExpr) at ./multidimensional.jl:841
 [2] reducedim_initarray(::Array{Variable,1}, ::Int64, ::AffExpr, ::Type{Variable}) at ./reducedim.jl:73
 [3] _reducedim_init(::Base.#identity, ::Base.#+, ::Base.#zero, ::Base.#sum, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:102
 [4] reducedim_init(::Function, ::Base.#+, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:87
 [5] mapreducedim(::Function, ::Function, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:242
 [6] sum(::Array{Variable,1}, ::Int64) at ./reducedim.jl:585
 [7] macro expansion at ./REPL.jl:97 [inlined]
 [8] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

### PR DESCRIPTION
**Pull request by non-Jedi**
Fixes #26709 (see discussion on reasoning in issue)

### CODE REVIEW

**Comment by nalimilan** [comment]
Bump. I was going to make the same PR. @JeffBezanson Any objections?

Though I'm not sure the test needs to be so complex. A much shorter reproducer is:
```julia
julia> mapreduce(cos, +, Union{Int,Missing}[1], dims=1)
ERROR: InexactError: Int64(Int64, 0.5403023058681398)
```

**Comment by JeffBezanson** [comment]
> maybe as a temporary fix we could do typeof(z) <: T ? T : typeof(z)? That's really what matters here.

That does sound a bit better to me --- using `T` can't possibly work unless `z isa T`.

**Comment by nalimilan** [comment]
I've implemented that in the first commit of https://github.com/JuliaLang/julia/pull/28027.

**Comment by JeffBezanson** [comment]
Fixed by #28089, but would be good to add the test case from here.

**Comment by non-Jedi** [comment]
Force-pushed this to a commit with just the test-case if there's still interest in including it.

**Pull request merged**
