### PR TITLE
Refactor LibGit2 credential_loop tests

### PR DESCRIPTION
**Pull request by omus**
- Modified `credential_loop` to return a `LibGit2.GitError`.
- Modified `challenge_prompt` to take a an `Expr` instead of a `String`.

### CODE REVIEW

**Comment by omus** [comment]
Related to work on #20725

**Comment by omus** [comment]
I forgot to update some of the code that was commented out.

**Review by kshyatt — APPROVED** [review]
LGTM but someone else should probably take a look too!

**Comment by omus** [comment]
Would be good to get another pair of eyes on this. Potentially I'll merge this tomorrow.

**Pull request merged**
