### PR TITLE
fix more of the #18017 regression

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a better fix that should take care of the remaining regressions.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Comment by vtjnash** [comment]
lgtm

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/18126#issuecomment-240854613): `RemoteException(2,CapturedException(ErrorException("type NanosoldierError is immutable"),Any[( in report at BenchmarkJob.jl:405,1),( in run at BenchmarkJob.jl:233,1),( in #503 at multi.jl:1410,1),( in run_work_thunk at multi.jl:996,1),( in macro expansion at multi.jl:1410 [inlined],1),( in #502 at event.jl:46,1)]))`
cc @jrevels

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/18126#issuecomment-240894910): `RemoteException(3,CapturedException(ErrorException("type NanosoldierError is immutable"),Any[( in report at BenchmarkJob.jl:405,1),( in run at BenchmarkJob.jl:233,1),( in #503 at multi.jl:1410,1),( in run_work_thunk at multi.jl:996,1),( in macro expansion at multi.jl:1410 [inlined],1),( in #502 at event.jl:46,1)]))`
cc @jrevels

**Comment by KristofferC** [comment]
https://github.com/JuliaCI/BaseBenchmarkReports/blob/73b77790dbeafd8a7db4e3806cc48874c2f7e51b/260852e_vs_b80dad4/report.md

Make seemed to fail.

**Comment by tkelman** [comment]
```
configure: WARNING: libpsl was not found
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssh2 -lmbedtls -lmbedx509 -lmbedcrypto -lz 
```

Does nanosoldier do each build from a totally clean state, or does it reuse the artifacts of one when it builds the other?

**Comment by jrevels** [comment]
Builds from a clean state. The relevant function is [here](https://github.com/JuliaCI/Nanosoldier.jl/blob/master/src/build.jl#L22).

**Comment by tkelman** [comment]
So did https://github.com/JuliaLang/julia/pull/18103 break a clean build from master then?

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/18126#issuecomment-241143289): `RemoteException(3,CapturedException(ErrorException("type NanosoldierError is immutable"),Any[( in report at BenchmarkJob.jl:405,1),( in run at BenchmarkJob.jl:233,1),( in #503 at multi.jl:1410,1),( in run_work_thunk at multi.jl:996,1),( in macro expansion at multi.jl:1410 [inlined],1),( in #502 at event.jl:46,1)]))`
cc @jrevels

**Comment by tkelman** [comment]
Make is failing, and will until (at least part of) https://github.com/JuliaLang/julia/pull/18153 is merged.

Is this ready to merge or do you want to be absolutely sure it doesn't cause regressions beforehand?

**Comment by JeffBezanson** [comment]
I did want to run the benchmarks to confirm the fix, but this should be fine to merge.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Comment by tkelman** [comment]
daily build is working, but comment triggers aren't?
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Pull request merged**
