### PR TITLE
small optimization to subtyping

### PR DESCRIPTION
**Pull request by JeffBezanson**
Zero and copy only the used portion of the union state buffer. Also cut down some integer sizes.

For me this shaves about 0.2 seconds off `using Plots` and the TTFP.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by oscardssmith** [comment]
What effect does reducing the size of stack from 100 to 80 have?

**Comment by JeffBezanson** [comment]
It saves some stack space, which seems to help performance a hair. Might as well try to use as little space as we can get away with.

**Comment by JeffBezanson** [comment]
Modified to use even less stack space.

**Comment by vtjnash** [comment]
Win32 is still failing CI in subtyping: https://build.julialang.org/#/builders/9/builds/2179

**Pull request merged**
