### PR TITLE
Bump Pkg3

### PR DESCRIPTION
**Pull request by KristofferC**
- Build packages added from git repos (https://github.com/JuliaLang/Pkg3.jl/issues/239)
- Use dependencies from Project files when developed (https://github.com/JuliaLang/Pkg3.jl/issues/244)
- Hopefully get better error in cases of https://github.com/JuliaLang/Pkg3.jl/issues/228, from PR https://github.com/JuliaLang/Pkg3.jl/pull/242
- No longer overwrite custom REPL settings: https://github.com/JuliaLang/Pkg3.jl/pull/243
- Fix upgrading when a package with a project is developed https://github.com/JuliaLang/Pkg3.jl/issues/238

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Windows failures are both timeouts. Not sure what's up with the macOS failure. Seems unrelated but I haven't seen it before so it's hard to tell. It happened too early on to be affected by Pkg3 code.

**Comment by KristofferC** [comment]
Seems like everything in the last 6-7 hours failed with that on macOS.

**Comment by StefanKarpinski** [comment]
That file is supposed to exist at `deps/scratch/SuiteSparse-4.4.5/CHOLMOD/Include/cholmod.h`. If it doesn't then either that isn't getting put in the right place or the directory isn't being added to the header path of the compiler anymore. We checksum SuiteSparse-4.4.5, which hasn't changed since October. The most recent change to makefiles in `deps` was https://github.com/JuliaLang/julia/pull/26698 which does mess with a lot of LLVM flags. @vchuravy, is there any change that change might have messed up SuiteSparse compilation like this?

**Comment by StefanKarpinski** [comment]
This seems to be a problem with @staticfloat's Homebrew tap.

Good log:
```
sh$ ack 'Tapping staticfloat/julia' log_good.txt -C
==> Summary
🍺  /usr/local/Cellar/ccache/3.4.2: 57 files, 246.9KB
==> Tapping staticfloat/julia
Cloning into '/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia'...
Warning: Calling 'depends_on :fortran' is deprecated!
--
==> Summary
🍺  /usr/local/Cellar/suite-sparse-julia/4.4.6_3: 94 files, 3.3MB
==> Tapping staticfloat/juliadeps
git clone https://github.com/staticfloat/homebrew-juliadeps /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-juliadeps --depth=1
Cloning into '/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-juliadeps'...
```
Bad log:
```
sh$ ack 'Tapping staticfloat/julia' log_bad.txt -C
==> Summary
🍺  /usr/local/Cellar/ccache/3.4.2: 57 files, 246.9KB
==> Tapping staticfloat/julia
Cloning into '/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia'...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb
--
To install one of them, run (for example):
  brew install caskroom/cask/julia
==> Tapping staticfloat/juliadeps
git clone https://github.com/staticfloat/homebrew-juliadeps /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-juliadeps --depth=1
Cloning into '/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-juliadeps'...
```
The following formulas are all failing now:
```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/julia.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm37-julia.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm39-julia.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/openblas-julia.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/staticfloat/homebrew-juliadeps/imagemagick@6.rb
```

**Comment by StefanKarpinski** [comment]
In any case, clearly unrelated to this PR, so I'm going to merge.

**Pull request merged**
