### PR TITLE
rm ubuntu nightly ppa as not actively maintained

### PR DESCRIPTION
**Pull request by xgdgsc**
rm ubuntu nightly ppa as not actively maintained.

### CODE REVIEW

**Comment by yuyichao** [comment]
..... I thought we've removed all traces of it a long time ago.....................
Anyway, LGTM unless @staticfloat proves otherwise ;-p

**Comment by fredrikekre** [comment]
To be fair this is under the headline:

> The following distributions include julia, but the versions may be out of date due to rapid development:

So... Whats the status of the other ones?

**Comment by yuyichao** [comment]
> So... Whats the status of the other ones?

The PPA does seem to be the one that recieves the most complains. Not sure if it's just because there are a lot of ubuntu users...

Not entirely the same issue but you do make me realized that the arch version should link to x86_64 instead....

**Comment by tkelman** [comment]
The Debian and Ubuntu packages are *more* outdated than the PPA.

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
Turns out a lot of these are pretty outdated. For example, MacPorts is on 0.4.6, which isn't even the most recent release in the 0.4 series, and the Homebrew tap explicitly declares itself to be unmaintained.

**Comment by fredrikekre** [comment]
Can we just remove these then? It should be enough to recommend binaries in the README.

**Comment by PallHaraldsson** [comment]
The nightly link had at least some (outdated) 0.6.0. Do we really want to keep the link just above "nightly"that only links to unmaintained 0.4.x, e.g. in:

https://packages.ubuntu.com/xenial/julia

I suggest rather the opposite, and say something like "PPAs are outdated (use Julia's download page or), but here are recent 'nightlies' and PPAs may or may not get updated".

**Comment by staticfloat** [comment]
The PPA nightlies aren't working, and haven't worked for quite a while.  I don't have time to debug them, but if someone wants to email me and propose ways forward to getting that to work, I'm more than happy to shepherd them through the build process.

**Comment by ararslan** [comment]
I think we should just remove the references to the various system package managers and say something along the lines of:
```markdown
# Binary Installation

<existing text, minus the list of distros>

**Note**: While some system package managers have Julia installers available,
these are not maintained nor endorsed by the Julia project. They may be outdated
and/or unmaintained. We recommend you use the official Julia binaries instead.
```

**Comment by ViralBShah** [comment]
@ararslan Let's do what you suggested.

**Comment by ararslan** [comment]
Okay, sounds good. @xgdgsc, would you be willing to make that change in this PR?

**Review by ararslan — APPROVED** [review]
Thanks!

**Comment by fredrikekre** [comment]
We should probably remove the corresponding section on https://julialang.org/downloads/platform.html as well? (Section from `Linux Distribution-Specific Packages` and below)?

**Pull request merged**
