### PR TITLE
Move docstrings from helpdb/Base.jl inline

### PR DESCRIPTION
**Pull request by xorJane**
Yay hackathon <3

Thanks in advance for reviewing!

### CODE REVIEW

**Comment by KristofferC** [comment]
I wonder if some of these docstrings occur before enough of the documentation system itself has been loaded (which would explain the CI problems).

**Comment by fredrikekre** [comment]
> I wonder if some of these docstrings occur before enough of the documentation system itself has been loaded (which would explain the CI problems).

Yes, I don't think we can have inline docstrings in `boot.jl` for instance, that's why I added the number docstrings in `helpdb/Base.jl` in #22067

**Comment by KristofferC** [comment]
Perhaps we should have a comment on those helpdb docstrings that are difficult to move.

**Comment by fredrikekre** [comment]
Or possibly `helpdb/boot.jl` etc, which would be more contained than having everything in `helpdb/Base.jl`?

**Comment by KristofferC** [comment]
Yes

**Comment by KristofferC** [comment]
So the easiest way forward would be to move some of the stuff (`boot.jl`) back into the helpdb file. You can check that everything works locally by rebuilding Julia.

**Comment by tkelman** [comment]
or `base/docs/basedocs.jl` for things that are tricky due to bootstrap order

**Comment by xorJane** [comment]
Thank you for the feedback! I'm realizing that a PR that touches this many lines of docs is harder to review and more likely to end up with merge conflicts. So, I'm going to break this PR up into a few smaller PR's.

**Comment by JeffBezanson** [comment]
I'll assume this was superseded by the smaller PRs; reopen if not.

**Pull request closed without merging**
