### PR TITLE
deprecate zero-arg Vector constructor

### PR DESCRIPTION
**Pull request by fredrikekre**
Ref #14201, #20330 (specifically https://github.com/JuliaLang/julia/pull/20330#discussion_r98599907) and https://github.com/JuliaLang/julia/issues/20402#issuecomment-313089294

### CODE REVIEW

**Comment by nalimilan** [comment]
I'm not sure I like this idea. Yes, that would be more consistent with `Matrix{T}()` throwing an error, but `Vector{T}()` is quite natural and very common...

**Comment by mauro3** [comment]
I think the most natural for `Vector{T}()` is `T[]`, so making this consistent will at least not impact my code.  In fact, maybe this PR could use the `T[]` form where appropriate?

**Comment by fredrikekre** [comment]
> I'm not sure I like this idea. Yes, that would be more consistent with `Matrix{T}()` throwing an error, but `Vector{T}()` is quite natural and very common...

I like the consistency, but on the other hand, an empty vector is useful which a empty matrix really isn't, so that could warrant special treatment of `Vector()`...

> I think the most natural for `Vector{T}()` is `T[]`, so making this consistent will at least not impact my code. In fact, maybe this PR could use the `T[]` form where appropriate?

I included the `[]` / `T[]` syntax as a suggestion in the deprecation warning, I also think `[]` / `T[]` is nicer than `Vector()` / `Vector{T}()`.

**Comment by rfourquet** [comment]
Another consistency would be broken with this PR when we see `Vector` as the general go-to container (the `list` of python, `std::vector` of C++ etc.), in the same family as other general containers like `Set`, rather than a special case of multi-dim arrays; then it's natural that a call to the type with no argument constructs an empty container. Consider e.g.
```
T = rand(Bool) ? Vector{Int} : Set{Int}
c = T()
```
Similarly, `Vector()` should not be deprecated IMHO, by analogy to `Set()`.

**Comment by fredrikekre** [comment]
This is a bad idea, I kinda like `Vector{T}()` to make a new empty vector, and people seem to agree with me, so I'll close this, and also #21082 and put this issue at a rest.

**Pull request closed without merging**
