### PR TITLE
subtyping: fast path for lhs union and rhs typevar

### LINKED ISSUE #55230: Inference regression in 1.11
We are seeing massive latency increases in `ClimaAtmos.jl` with Julia 1.11, starting from the alphas and continuing in 1.11-rc1 (https://github.com/CliMA/ClimaAtmos.jl/issues/3186).

`ClimaAtmos.jl` does no longer compile in any reasonable time with Julia 1.11-rc1. I identified that the offending function is `get_atmos`, a simple function that returns a keyword-defined type. For the most part, this function simply converts string keywords read from YAML files to types, then, it returns a `AtmosModel` (defined below). 

I used `SnoopCompile` (`master`) to try to get a little more insight. The `get_atmos` function, as it is, takes too long to compile (on Julia 1.10, this is instantaneous), so I had to remove part of it (as mentioned in the referenced issue). Once I do so, I see with `@snoop_inference` that:
```
InferenceTimingNode: 1.171199/288.711156 on Core.Compiler.Timings.ROOT() with 21 direct children
```

Plotting the inference:
image

All the time is spent in `types.jl` line 329. This line simply defines our struct:
```julia
Base.@kwdef struct AtmosModel{
    MC,
    MM,
    PM,
    CM,
    CCDPS,
    F,
    S,
    RM,
    LA,
    EXTFORCING,
    EC,
    AT,
    TM,
    EEM,
    EDM,
    ESMF,
    ESDF,
    ENP,
    EVR,
    TCM,
    NOGW,
    OGW,
    HD,
    VD,
    DM,
    SAM,
    VS,
    RS,
    ST,
    IN,
    SM,
    SA,
    NUM,
}
    model_config::MC = nothing
    moisture_model::MM = nothing
    precip_model::PM = nothing
    cloud_model::CM = nothing
    call_cloud_diagnostics_per_stage::CCDPS = nothing
    forcing_type::F = nothing
    subsidence::S = nothing
    radiation_mode::RM = nothing
    ls_adv::LA = nothing
    external_forcing::EXTFORCING = nothing
    edmf_coriolis::EC = nothing
    advection_test::AT = nothing
    tendency_model::TM = nothing
    edmfx_entr_model::EEM = nothing
    edmfx_detr_model::EDM = nothing
    edmfx_sgs_mass_flux::ESMF = nothing
    edmfx_sgs_diffusive_flux::ESDF = nothing
    edmfx_nh_pressure::ENP = nothing
    edmfx_filter::EVR = nothing
    turbconv_model::TCM = nothing
    non_orographic_gravity_wave::NOGW = nothing
    orographic_gravity_wave::OGW = nothing
    hyperdiff::HD = nothing
    vert_diff::VD = nothing
    diff_mode::DM = nothing
    sgs_adv_mode::SAM = nothing
    viscous_sponge::VS = nothing
    rayleigh_sponge::RS = nothing
    sfc_temperature::ST = nothing
    insolation::IN = nothing
    surface_model::SM = nothing
    surface_albedo::SA = nothing
    numerics::NUM = nothing
end
```

I have not tried without keyword arguments.

I don't think that what we are doing up to this point is particularly complex or unorthodox, and most of the types involved are very simple (mostly singletons and bools, all immutable).

_Originally posted by @Sbozzolo in https://github.com/JuliaLang/julia/issues/55171#issuecomment-2247094348_

### PR DESCRIPTION
**Pull request by vtjnash**
Fixes #55230

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55413#issuecomment-2274864173) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/b01e7a7_vs_c767032/report.md).

**Comment by vtjnash** [comment]
Looking closer into a test failure, I realized this instead needed to be guarded with `jl_has_free_typevars(u)` (to avoid the possibility of a union element becoming degenerate in `simple_join` but not being able to detect that without testing each element separately). The remaining check `e->Runions.depth == 0` is still needed to avoid introducing this failure:
```
Error in testset subtype:
Test Failed at /home/vtjnash/julia/test/subtype.jl:1642
  Expression: U2 == V
   Evaluated: Union{Tuple{LT, R, Int64} where {R<:Tuple{Int64}, LT<:Int64}, Tuple{LT, R, Int64} where {R<:Tuple{Int64}, LT<:R}} == Tuple{Union{Int64, Tuple{Int64}}, Tuple{Int64}, Int64}
```
Which comes from this kind of union-tuple switch:
```
julia> Tuple{Union{Int64, Tuple{Int64}}} <: Union{Tuple{<:Integer}, Tuple{<:Tuple}}
false
```

**Comment by vtjnash** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55413#issuecomment-2276329432) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3c075c9_vs_2193895/report.html) is available.

**Comment by N5N3** [comment]
I haven't verified it locally, but this change seems to break `Tuple{Union{Val{1},Val{2}}} <: Tuple{S} where {T, S<:Val{T}}`?
(`subtype_ccheck` traverses all internal ∀ unions, so we need to ensure there's no free typevars in y's ub.)

**Comment by vtjnash** [comment]
You are correct, that one would be broken by this fast path attempt, so I added that as a test and added your suggested fix. Do you think this is correct now? Or would it still become wrong if something was added to the stenv constraints?

**Review by JeffBezanson — APPROVED** [review]

**Pull request merged**
