### PR TITLE
Remove contrib/build_sysimg.jl

### PR DESCRIPTION
**Pull request by staticfloat**
Users should instead use [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) as it is more fully-featured and better maintained.

### CODE REVIEW

**Comment by ViralBShah** [comment]
A separate topic - we should bring PackageCompiler in here or at least make it part of the default Julia distribution. It could use more CI and testing.

**Comment by StefanKarpinski** [comment]
+1 to PackageCompiler in stdlib.

**Review by andreasnoack — APPROVED** [review]

**Comment by ararslan** [comment]
This seems to have broken `make binary-dist`. See this buildbot build: https://build.julialang.org/#/builders/53/builds/412

**Comment by chriscoey** [comment]
Can we revive a discussion of bringing PackageCompiler functionality to stdlib please? 

What would it take to make such a PR?

**Comment by ViralBShah** [comment]
For a JSOC, we need an identified competent student and money. Do we have someone in mind for this?

**Comment by chriscoey** [comment]
Not on my end. Perhaps there were some capable people whose ideas were turned down for JSOC?

**Pull request merged**
