### PR TITLE
Isolate string interpolation in error paths for sparse matrix construction

### PR DESCRIPTION
**Pull request by timholy**
This provides a better-than-3x speed improvement for `spzeros(5, 5)`:

```julia
julia> @btime spzeros(5, 5);
  341.371 ns (3 allocations: 288 bytes)

julia> Revise.track(SparseArrays)

julia> @btime spzeros(5, 5);
  103.633 ns (3 allocations: 288 bytes)
```

### CODE REVIEW

**Comment by simeonschaub** [comment]
I wonder whether we should have an `@throw` macro that just expanded to `(() -> throw(...))()`, which would make it easier to use this trick in more places.

**Comment by jmert** [comment]
The `@lazy_str` construct from #33711 is also a useful alternative to an `@throw` construct.

**Comment by PallHaraldsson** [comment]
@timholy I like how this is faster, but I would worry about it staying that way, in (current or) future versions, e.g. e.g. `-O3`. I had such a case, and used `@noinline`, but I wish Julia would outline `throw` by default, so we wouldn't have to use tricks all over the place. Here (and I guess with proposed `@throw` trick) a future compiler could decide to inline and negate your optimization?

**Comment by timholy** [comment]
>  a future compiler could decide to inline and negate your optimization?

We have tests for `throw` paths, so hopefully that won't happen.

**Pull request merged**
