### PR TITLE
Add relocatable root compression

### PR DESCRIPTION
**Pull request by timholy**
Currently we can't cache "external" CodeInstances, i.e., those generated
by compiling other modules' methods with externally-defined types.
For example, consider `push!([], MyPkg.MyType())`: Base owns
the method `push!(::Vector{Any}, ::Any)` but doesn't know about `MyType`.

While there are several obstacles to caching exteral CodeInstances,
the primary one is that in compressed IR, method roots are referenced
from a list by index, and the index is defined by order of insertion.
This order might change depending on package-loading sequence or other
history-dependent factors. If the order isn't consistent, our current
serialization techniques would result in corrupted code upon
decompression, and that would generally trigger catastrophic
failure. To avoid this problem, we simply avoid caching such
CodeInstances.

This enables roots to be referenced with respect to a `(key, index)`
pair, where `key` identifies the module and `index` numbers just those
roots with the same `key`. Roots with `key = 0` are considered to be
of unknown origin, and CodeInstances referencing such roots will remain
unserializable unless all such roots were added at the time of system
image creation.  To track this additional data, this adds two fields
to core types:

- to methods, it adds a `nroots_sysimg` field to count the number
  of roots defined at the time of writing the system image
  (such occur first in the list of `roots`)
- to CodeInstances, it adds a flag `relocatability` having value 1
  if every root is "safe," meaning it was either added at sysimg
  creation or is tagged with a non-zero `key`. Even a single
  unsafe root will cause this to have value 0.

This is part 2 of a series that started in #43793. Change in sysimg size is less than half a percent.

### CODE REVIEW

**Comment by timholy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43881#issuecomment-1018543850) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/81d5216_vs_5f79cb3/report.html).

**Comment by timholy** [comment]
@nanosoldier `runtests(["AdvancedHMC", "AtomicGraphNets", "BioServices", "CMAEvolutionStrategy", "CatBoost", "CopEnt", "CropRootBox", "DataFrames", "FieldTracer", "GeoDatasets", "GridapPETSc", "GrowthMaps", "JSOSolvers", "MatrixPencils", "NumericalAlgorithms", "OpenTelemetryProto", "OpticSimVis", "PBWDeformations", "PCloud", "Pfam", "ProximalAlgorithms", "PyRhodium", "QuantumTomography", "STREAMBenchmark", "SimpleHypergraphs", "StaticKernels", "VoronoiGraph", "YAAD"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43881#issuecomment-1019280381) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/81d5216_vs_1db8b8f/report.html).

**Comment by timholy** [comment]
This seems ready. I stripped out the asan work as it was submitted independently in #43885, but there are no other changes.

**Comment by vtjnash** [comment]
I think the main thing we need to do to make this safe is to alter the system to avoid representing external objects directly in the IR, and instead use indirection descriptions (such as GlobalRef). To do that, we need to add a similar representation for a `MethodRef(::Method, ::Int)` that describes the original source of the root, for arbitrary things that the user spliced into the IR when originally defining the method.

**Comment by timholy** [comment]
Do you mean if we want to handle the roots that are currently marked with `key=0` (aka, unknown origin)? Or are you saying that the package level is too coarse-grained for other things you'd like to do?

**Pull request merged**
