### PR TITLE
Fix `bb-install` naming conventions, add hashes

### PR DESCRIPTION
**Pull request by staticfloat**
@vtjnash here are the changes requested in the original `bb-install` PR.

### CODE REVIEW

**Comment by Keno** [comment]
I'm using BB for wasm-compatible LLVM binaries. After the original bb-install PR, it started failing with:
```
/home/keno/julia-wasm2/deps/llvm.mk:523: *** multiple target patterns.  Stop.
```
and even with this, I get:
```
basename: extra operand ‘platform’
Try 'basename --help' for more information.
/home/keno/julia-wasm2/deps/llvm.mk:523: warning: overriding recipe for target '/home/keno/julia-wasm2/usr-staging/LLVM.v6.0.1.tgz'
/home/keno/julia-wasm2/deps/llvm.mk:523: warning: ignoring old recipe for target '/home/keno/julia-wasm2/usr-staging/LLVM.v6.0.1.tgz'
WARNING: sha512 checksum for srccache not found in deps/checksums/, autogenerating...
md5sum: /home/keno/julia-wasm2/deps/srccache/: Is a directory
sha512sum: /home/keno/julia-wasm2/deps/srccache/: Is a directory
sha512sum: /home/keno/julia-wasm2/deps/srccache/: Is a directory
cp: -r not specified; omitting directory '/home/keno/julia-wasm2/deps/srccache/'
/home/keno/julia-wasm2/deps/llvm.mk:523: recipe for target '/home/keno/julia-wasm2/usr-staging/LLVM.v6.0.1.tgz' failed
make[1]: *** [/home/keno/julia-wasm2/usr-staging/LLVM.v6.0.1.tgz] Error 1
Makefile:57: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```
The relevant Make.user entries are:
```
USE_BINARYBUILDER_LLVM=1
BINARYBUILDER_TRIPLET=wasm32-unknown-emscripten
override LLVM_BB_URL_BASE := https://github.com/tshort/LLVMBuilder/releases/download
override LLVM_BB_REL = 0-wasm
```

**Comment by staticfloat** [comment]
@keno the meaning of the flags has changed a bit, try this instead on this branch:

```
$ cat Make.user
USE_BINARYBUILDER_LLVM=1
override LLVM_BB_TRIPLET := wasm32-unknown-emscripten
override LLVM_BB_URL_BASE := https://github.com/tshort/LLVMBuilder/releases/download/v6.0.1-0-wasm
```

**Comment by staticfloat** [comment]
I have added windows versions of OpenBLAS v0.3.3; I had to [dodge a compiler bug](https://github.com/JuliaPackaging/Yggdrasil/commit/2b1576aeb8cdac4e783bd35f58e77fad97c09225) in AVX-512 register placement.  Let's see if Appveyor is happier about that.

**Comment by vchuravy** [comment]
This only adds checksums for darwin, should we have checksums for all/any architecture? Maybe it is better to download a checksum file and use that instead?

**Comment by JeffBezanson** [comment]
Anything blocking merging this to get AV back?

**Comment by staticfloat** [comment]
I'm going to add checksums for all the architectures and then we can merge.

**Comment by staticfloat** [comment]
Alright this is now good to go from my perspective.  As soon as this returns green (the only reason it wouldn't be green is if one of the hashes that I added is wrong) let's merge it.

**Review by vchuravy — APPROVED** [review]

**Comment by staticfloat** [comment]
That's enough green for me (excluding SuiteSparse LU factorization error).  Merging.

**Comment by KristofferC** [comment]
Not sure why this should go into 1.0. Removing for now.

**Pull request merged**
