### PR TITLE
constructors for Matrix and SparseMatrixCSC from UniformScaling

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request provides constructors for `Matrix` and `SparseMatrixCSC` from `UniformScaling`s, for example `Matrix(I, dims)` and `SparseMatrixCSC(I, dims)`. In other words, this pull request explores the intersection of JuliaLang/julia#11557 (particularly https://github.com/JuliaLang/julia/issues/11557#issuecomment-339776065) and JuliaLang/LinearAlgebra.jl#454. So far this approach feels nice, supporting the direction in https://github.com/JuliaLang/julia/issues/11557#issuecomment-339776065. Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
Ref. https://github.com/JuliaLang/julia/issues/23156#issuecomment-340305031, suggesting special-casing `Matrix(I, m, n)`/`sparse(I, m, n)`/`SparseMatrixCSC(I, m, n)` to yield an array with eltype `Float64` rather than `eltype(I)`.

**Comment by andreasnoack** [comment]
As mentioned in #23156, I don't think it is necessary to return `Float64` elements. Using `Int` elements will probably also result in a better promotion in some cases. At least for `Float32` computations.

**Comment by Sacha0** [comment]
Cleaned up the existing commits and added a couple commits providing the convenience forms suggested by `@andreasnoack`'s https://github.com/JuliaLang/julia/issues/23156#issuecomment-340364862 (e.g. `Matrix[{T}](I, n)`, `SparseMatrixCSC[{T}](I, n)`).

This pull request should be in shape. Absent objections or requests for time, I am inclined to move forward with this approach (merge) in the next day or two. Thoughts? Thanks!

**Comment by Sacha0** [comment]
Thanks all!

**Pull request merged**
