### PR TITLE
Fix 32 bit overflows

### PR DESCRIPTION
**Pull request by mschauer**
See #32894

### CODE REVIEW

**Comment by mschauer** [comment]
These overflows mostly made the test problems silently easier/trivial on 32 bit systems as far as I can tell.

**Comment by mschauer** [comment]
It appears to me that the testset `rounding` does not run under 32 bit, at least I looked for it in `tester_linux32`.

**Comment by KristofferC** [comment]
I see

```
      From worker 9:	running testset rounding...
```

in the logs for 32 bit linux.

**Comment by mschauer** [comment]
Ah, true, the website search is broken, thanks for checking.

**Pull request merged**
