### PR TITLE
Preserve structured matrix types more often when broadcasting

### LINKED ISSUE #648: Broadcasted power does not preserve Diagonal and UpperTriangular types
It seems many broadcasted operations preserve LinearAlgebra types. For example,

D = Diagonal(rand(3))
abs.(D)
sqrt.(D)

each return a Diagonal type. However, 

.^(D,2)
D.^2 

return a Matrix type. The behavior is similar for UpperTriangular types. I believe this should be fixed.

### LINKED ISSUE #32759: Broadcasted power does not preserve Diagonal and UpperTriangular types
It seems many broadcasted operations preserve LinearAlgebra types. For example,

D = Diagonal(rand(3))
abs.(D)
sqrt.(D)

each return a Diagonal type. However, 

.^(D,2)
D.^2 

return a Matrix type. The behavior is similar for UpperTriangular types. I believe this should be fixed.

### PR DESCRIPTION
**Pull request by mbauman**
The primary motivation here is exponentiation (fixes JuliaLang/LinearAlgebra.jl#648). Previously `X .^ 2` would return a Matrix but `two=2; X .^ two` would return the same structured matrix type as `X`. This simply teaches LinearAlgebra a little bit more about broadcast so it can safely compute the zero-preservation property of broadcasts involving `Ref`s, which is sufficient to handle the literal pow argument list.

### CODE REVIEW

**Comment by mbauman** [comment]
Let's re-run CI and get this in.

**Comment by mbauman** [comment]
Interesting — the 32 bit failures look related.  I don't see any differences in the printout below, but I think the `â¦` is a mojibake `⋯`.

```
Test Failed at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win32\build\share\julia\stdlib\v1.3\LinearAlgebra\test\structuredbroadcast.jl:37
  Expression: X .^ 2 == X .^ (2,) == fX .^ 2 == X .^ two
   Evaluated: 
    [0.31502726237096007 0.43928288933667414 â¦ 0.0 0.0; 0.41656112475245854 0.009615577025932596 â¦ 0.0 0.0; â¦ ; 0.0 0.0 â¦ 0.037316269381872484 0.2966281365862301; 0.0 0.0 â¦ 0.788465378213704 0.7921566497473703] ==
    [0.31502726237096007 0.43928288933667414 â¦ 0.0 0.0; 0.41656112475245854 0.009615577025932596 â¦ 0.0 0.0; â¦ ; 0.0 0.0 â¦ 0.037316269381872484 0.2966281365862301; 0.0 0.0 â¦ 0.788465378213704 0.7921566497473703] == 
    [0.31502726237096007 0.43928288933667414 â¦ 0.0 0.0; 0.41656112475245854 0.009615577025932596 â¦ 0.0 0.0; â¦ ; 0.0 0.0 â¦ 0.037316269381872484 0.2966281365862301; 0.0 0.0 â¦ 0.788465378213704 0.7921566497473703] == 
    [0.31502726237096007 0.43928288933667414 â¦ 0.0 0.0; 0.41656112475245854 0.009615577025932596 â¦ 0.0 0.0; â¦ ; 0.0 0.0 â¦ 0.037316269381872484 0.2966281365862301; 0.0 0.0 â¦ 0.788465378213704 0.7921566497473703]
```

**Comment by dkarrasch** [comment]
@mbauman Could you rebase this PR? The last CI failures look weird, and partly unrelated. Would be nice to see if those issues have been resolved meanwhile, so we could get this in.

**Comment by mbauman** [comment]
Bah, now it passes tests?  Looks like this is a failure that depends upon the RNG seed — likely due to differences between BLAS' exponentiation.  We're probably within an ULP or two.  I suppose I'll just make those `≈`s.

**Comment by mbauman** [comment]
Wait that makes no sense.  We're not hitting BLAS in any case here.  Not sure where a difference would come in.

**Comment by dkarrasch** [comment]
Could it be that it has to do with small numbers getting squared and getting even smaller? It has to be somehow related to the relative accuracy, I guess. What if you define
```julia
D = Diagonal(rand(N).+1)
```
or
```julia
D = Diagonal(rand(-10:10, N))
```
?

**Comment by mbauman** [comment]
This is fun:

```Julia
julia> two = 2
2

julia> x = 0.9390576568834563
0.9390576568834563

julia> x ^ 2
0.8818292829514472

julia> x ^ two
0.8818292829514471
```

**Comment by dkarrasch** [comment]
Which one corresponds to which? `x^2` is the first, and `x^two` the second? Like literal vs. variable?

**Comment by dkarrasch** [comment]
The failure is in `Distributed`, I'd say we can merge this, right? @mbauman

**Comment by mbauman** [comment]
Since https://github.com/JuliaLang/julia/pull/34863 got in first, I think we should drop its workaround commit from here.

**Comment by dkarrasch** [comment]
Oh yea, you mean the "fine-grained tests" thing?

**Comment by mbauman** [comment]
Sure, that one too.  There had also been another commit that completely avoided looking at numeric equality between `X .^ 2` and `X .^ two`, but now those are the same.

**Pull request merged**
