### PR TITLE
Testsets for test/statistics

### PR DESCRIPTION
**Pull request by kshyatt**
I'm kind of confused by the inference failure...

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by kshyatt** [comment]
@fredrikekre I think there's some inference problem i don't understand here, don't merge this without checking CI logs...

**Comment by fredrikekre** [comment]
Could it be related to #23371?

**Comment by kshyatt** [comment]
Could be! I can see it locally on my mac...

**Comment by fredrikekre** [comment]
Oh nice, no one has been able to reproduce locally before I think. Mind trying to reduce it and post in the issue?

**Comment by kshyatt** [comment]
Will do once I get home!

**Comment by kshyatt** [comment]
This is passing CI and approved.

**Pull request merged**
