### PR TITLE
Fix BoundsError for regex deepcopy

### LINKED ISSUE #31260: Bounds exception when using deepcopy with regex
```
julia> match(deepcopy(r""), "")
ERROR: BoundsError: attempt to access ""
  at index [1829569203750929]
Stacktrace:
 [1] prevind(::String, ::Int64, ::Int64) at ./strings/basic.jl:460
 [2] prevind at ./strings/basic.jl:455 [inlined]
 [3] prevind at ./strings/basic.jl:454 [inlined]
 [4] match(::Regex, ::String, ::Int64, ::UInt32) at ./regex.jl:214
 [5] match at ./regex.jl:207 [inlined]
 [6] match(::Regex, ::String) at ./regex.jl:222
 [7] top-level scope at none:0```
```
As discussed on Slack with @StefanKarpinski and @vtjnash, the right fix is probably to provide an overload of `deepcopy_internal` for `Regex` which makes a copy of the underlying PCRE object, ideally through the PCRE API if such functionality exists.

### PR DESCRIPTION
**Pull request by eulerkochy**
Fixes #31260 , as per https://github.com/JuliaLang/julia/issues/31260#issuecomment-469827890

### CODE REVIEW

**Comment by eulerkochy** [comment]
@StefanKarpinski @JeffBezanson can you look at this PR?

**Comment by StefanKarpinski** [comment]
@JeffBezanson, this is all you. I have no idea if this is kosher or not.

**Comment by eulerkochy** [comment]
Bump

**Comment by StefanKarpinski** [comment]
Triage is cool with this but notes that the regex JIT compile cache isn't threadsafe but that's a problem for another day.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Could you add a test as well? You can test that creating a copy doesn't cause a bounds check error.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by eulerkochy** [comment]
`Bump`

**Comment by StefanKarpinski** [comment]
Thanks for fixing this, @eulerkochy! Nice work.

**Pull request merged**
