### PR TITLE
`@something`: a short-circuiting `something`

### PR DESCRIPTION
**Pull request by omus**
In the AWS.jl package I was noticing a pattern where if an argument was undefined a series of fallbacks would be tried. The code was similar to:

```julia 
if region === nothing
    region === nothing && (region = get(ENV, "AWS_REGION", nothing)
    region === nothing && (region = get_profile_region())
    region === nothing && (region = get_ec2_instance_region())
    region === nothing && (region = DEFAULT_REGION)
end
``` 
Since the code above makes use of `nothing` using the `something` function is a natural fit:

```julia
something(
    region,
    get(ENV, "AWS_REGION", nothing),
    get_profile_region(),
    get_ec2_instance_region(),
    DEFAULT_REGION,
)
```
This is much easier to read but unfortunately evaluates all arguments even if they aren't used. The `@something` macro is equivalent to `something` but skips evaluating all argument after the first non-`nothing` value.

### CODE REVIEW

**Comment by omus** [comment]
I'll add a NEWS entry tomorrow

**Comment by jw3126** [comment]
Nice! Would it make sence to also have `@coalesce`?

**Comment by omus** [comment]
> Nice! Would it make sence to also have `@coalesce`?

That can definitely be added. I just didn't have a use case for it

**Comment by omus** [comment]
- Added NEWS entry
- Added short-circuiting `@coalesce`
- Fixed a minor documentation error which made it appear that `something` and `coalesce` required at least one argument.

**Comment by omus** [comment]
CI failure is from the LibCURL stdlib and is unrelated

**Review by ararslan — APPROVED** [review]

**Comment by ararslan** [comment]
Ah, I forgot to mention that these should have a compat annotation in the docstrings.

**Comment by omus** [comment]
> Ah, I forgot to mention that these should have a compat annotation in the docstrings.

I'll take care of that now

**Pull request merged**
