### PR TITLE
Use syntax-propertize-function on Emacs 24.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes https://github.com/JuliaLang/julia/issues/11591

### CODE REVIEW

**Comment by yuyichao** [comment]
@Wilfred You should probably use the `[av skip]` tag in the commit log or the PR title for julia-mode change.

**Comment by yuyichao** [comment]
I can confirm locally that all 11 tests passes and it fixes #11591 for me.

I don't know about these features enough to review this but since @Wilfred is our emacs expert and it works for me, I'll merge this sometime tomorrow if there's no more comments.

**Comment by yuyichao** [comment]
And @Wilfred. Thanks for fixing this!

**Comment by pao** [comment]
This isn't core; no reason to hold it up. The faster we break @JeffBezanson's emacs setup, the faster we'll know it didn't work right.

**Comment by tkelman** [comment]
> commit log

anywhere in the commit message, first line or later. Putting `[av skip]` in the PR title but not in the commit message doesn't help.

**Pull request merged**
