### PR TITLE
optimizer: organize code and more strongly type `OptimizationState.ir`

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by aviatesk** [comment]
Rebased against the current master. Will merge once I confirm CI get passed, because this PR doesn't change any logic other than code organization.

**Comment by vtjnash** [comment]
FWIW, CI is a bit slow right now, so only 13 of the 20 checks ran (though we are unlikely to see platform differences here)

**Comment by aviatesk** [comment]
Are you okay/comfortable with this change ? I feel I unnecessarily hurried to merged this.

**Comment by vtjnash** [comment]
It sounded fine, so I didn’t look too closely. Possibly somewhat fast, due to the weekend, but not an issue here.

**Pull request merged**
