### PR TITLE
fix testset printing and add test

### PR DESCRIPTION
**Pull request by KristofferC**
It is currently bugged (on 0.5 as well) in that it is not indenting nested testets. I had to put this on top of https://github.com/JuliaLang/julia/pull/20221 to test it (because testsets were not printed at all before that). I just took the old implementation from BaseTestNext where it works as it should.

Now:

```
Test Summary: | Pass  Fail  Total
Foo Tests     |    2     2      4
  Animals     |    1     1      2
    Felines   |    1            1
    Canines   |          1      1
  Arrays      |    1     1      2
```

Previously:

```
Test Summary: | Pass  Fail  Total
  Foo Tests   |    2     2      4
  Animals     |    1     1      2
  Felines     |    1            1
  Canines     |          1      1
  Arrays      |    1     1      2
```

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @kshyatt

**Review by kshyatt — APPROVED** [review]
Nice! LGTM

**Comment by tkelman** [comment]
This is outputting the failure messages even during normal execution, looks a bit alarming.

**Comment by KristofferC** [comment]
Thanks for fixing.

**Pull request merged**
