### PR TITLE
22% faster startup because sysimage is 33% smaller

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by KristofferC** [comment]
There is ongoing work to move out stdlibs from the sysimage, https://github.com/JuliaLang/julia/pull/49130, https://github.com/JuliaLang/julia/pull/49132, https://github.com/JuliaLang/julia/pull/49134, etc. However, this needs to be done one by one and checks against load time and first call latency has to be done. And for some packages like Pkg there needs to be hooks in place to load the package on `]` in the REPL etc. Removing everything in one step is too coarse.

**Comment by PallHaraldsson** [comment]
>this needs to be done one by one and checks against load time and first call latency has to be done. 

First call of what? Most programs do not care about first call latency of anything related to e.g. LibGit2, Tar, Downloads, and well Pkg, the major offender it seems. Do you have an idea of any other big offender to start with excising? Or a likely first call issue? Wouldn't it be offset by the faster startup? Fully? Everything can be precompiled in the stdlibs.

>And for some packages like Pkg there needs to be hooks in place to load the package on ] in the REPL

Are you opposed to this if I make it work? You closed the issue on that, at Pkg, implying you don't want it done. I was looking into what I can excise and still start. I forgot that I disabled the Pkg, I believe everything else still works.

Pkg alone pulls in 17 dependencies of all 27, many of are not needed by general programs (so it's blocking good progress):

Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

**Comment by KristofferC** [comment]
Once Pkg is out, that frees up quite a bit of other stdlibs that can be moved out:

https://github.com/JuliaLang/julia/pull/49428
https://github.com/JuliaLang/julia/pull/49426
https://github.com/JuliaLang/julia/pull/49425

(You can also see from those PRs other things that need updating, like various make files and tests).

**Comment by vchuravy** [comment]
Hitting `]` needs to work and it needs to be reasonably snappy

**Comment by KristofferC** [comment]
> But loading the Pkg code (and more e.g. the deprecated Downloads) is worse for all users, which don't use it, at least for benchmarks.

To be clear, the goal is indeed to move out Pkg from the sysimage. It just requires the proper ground work.

**Pull request closed without merging**
