### PR TITLE
allow invalid UTF-8 string literals, deprecate b"..."

### PR DESCRIPTION
**Pull request by StefanKarpinski**
also print invalid UTF-8 characters correctly

related: #25072

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This is ready to go. After the first commit, `b"..."` is no longer any more expressive than normal string literals, and we can get rid of cases where we have written `String(b"...")` to construct string literals containing invalid UTF-8, since they can now just be written as `"..."` directly. The additional decision is whether to deprecate `b"abc"` as a shorthand for `Vector{UInt8}("abc")` or keep it.

**Comment by quinnj** [comment]
I would vote to keep it; it can be handy sometimes.

**Comment by StefanKarpinski** [comment]
Ok, I can revert the deprecation and just keep the `String(b"...")` => `"..."` changes.

**Comment by StefanKarpinski** [comment]
This is pretty bad though (pointed out by @keno):
```
julia> function f(p)
           v = b"123"
           p && (v[1] = 'x')
           return v
       end
f (generic function with 1 method)

julia> f(false)
3-element Array{UInt8,1}:
 0x31
 0x32
 0x33

julia> f(true)
3-element Array{UInt8,1}:
 0x78
 0x32
 0x33

julia> f(false)
3-element Array{UInt8,1}:
 0x78
 0x32
 0x33
```
We should consider changing this while we're at it.

**Comment by StefanKarpinski** [comment]
Triage resolution: make `b"..."` create a new vector each time instead of the same one every time.

**Pull request merged**
