### PR TITLE
Remove permute!! and invpermute!!

### PR DESCRIPTION
**Pull request by LilithHafner**
I don't think that these algorithms provide an unambiguous performance improvement that justifies their inclusion in base. 

Perhaps a more complex dispatch system that looks at length and eltype might be warranted, but I'm in favor of excision and putting fancy and high-efficiency permutations somewhere like Permutations.jl. Here are some benchmarks that shed light on the consequences of this PR, green is an improvement and red is a regression:

permute
invpermute

Roguhly, I'm benchmarking `[inv]permute!(Vector{NTuple{width, Int}}(undef, length), shuffle!(collect(1:length)))`

<details>
<summary> Benchmark code </summary>

```julia
using Random, Plots
_permute!(a, p::AbstractVector) = copyto!(a, a[p])
_invpermute!(a, p::AbstractVector) = copyto!(a, a[invperm(p)])

function t(::Type{T}, n, fs...) where T
    m = max(1, 10^6 ÷ max(10, n * sizeof(T)))
    A = [Vector{T}(undef, n) for _ in 1:m]
    P = [shuffle!(collect(1:n)) for _ in 1:m]
    [@elapsed(for (a,p) in zip(A,P) 
        f(a,p)
    end) for f in fs]
    [@elapsed(for (a,p) in zip(A,P) 
        f(a,p)
    end) for f in fs]
end

function compute()
    global fs = permute!,_permute!,invpermute!,_invpermute!
    global data = [t(NTuple{x,Int},2^y,fs...) 
        for x in 1:15, y in 1:20]
end
function plot()
    for (i,f) in collect(enumerate(fs))[[1,3]]
        display(heatmap(
            log10.(getindex.(data, i+1) ./ getindex.(data, i)),
            c=cgrad([:black, :green, :white, :red, :black]),
            xlabel="log2(length)", ylabel="width",
            title="log10(_$f / $f)",
            clims=(-2,2)))
    end
end
```

</details>

### CODE REVIEW

**Comment by stevengj** [comment]
Note that in practice, there are several packages using `Base.permute!!`: DataArrays, StructArrays, DataFrames, IndexedTables, PooledArrays, … so this change will be breaking.

**Comment by LilithHafner** [comment]
Good catch, @stevengj.

Going through [all the packages](https://juliahub.com/ui/Search?type=code&q=permute%21%21) that use `Base.permute!!` or `Base.ipermute!!`

**DataArrays** has been deprecated since julia 1.0
**DataFrames** no longer uses `Base..permute!!` in its master branch, it now uses a much faster approach.
**PooledArrays** only uses `Base.permute!!` to define `Base.permute!!` on the `PooledArray` type.

Some packages would need to switch from `Base.permute!!` to `permute!`. All of these packages use `Base.permute!!` instead of `permute!` only for performance reasons but may experience a speedup switching to `permute!` after this PR compared to the current `Base.permute!!`.

**Clustering** would almost certainly see a speedup as the eltype it's permuting is `Int`.
**IndexdTables** could be much (perhaps 2x) faster if it used a similar approach as DataFrames instead of `Base.permute!!`, whether it sees a speedup depends on user eltype size and length.
**Qaintessent** may see a minor regression.

If folks want to go through with this PR, I cane make the necessary PRs to those packages.
**StructArrays** uses `Base.permute!!` on an eltype of references, so I suspect it would also be faster after this PR to simply call `permute!`

**Comment by oscardssmith** [comment]
If these PRs are expected to be performance wins, it sounds like they should be made whether we want this PR or not.

**Comment by oscardssmith** [comment]
In that case, I think the order should be
1. fix performance of `permute!` / `invpermute!`.
2. make PRs to packages.
3. decide whether we want to deprecate `permute!!`

**Comment by LilithHafner** [comment]
[Step 1 is complete.](https://github.com/JuliaLang/julia/pull/44941)

**Comment by LilithHafner** [comment]
Waiting for the release of 1.9 to begin step 2.

**Comment by alyst** [comment]
`[inv]permute!!(v, p)` doesn't allocate the new array, so while the algorithm itself might be slower than `copyto!(v, v[p])`, in certain contexts the GC overhead of `permute!()` may result in lower overall performance.

**Comment by LilithHafner** [comment]
The benchmarks in the OP do not exclude GC overhead.

**Comment by LilithHafner** [comment]
I'm not going to reproduce the above figure with 1000x iterations because that would take to long. Here's a single point from the figure in the OP, benchmarked while reusing both parameters 1000x times. This result is consistent with the figures in the OP.
```julia
julia> x2 = rand(1000); perm = Vector{Int}(undef, 1000); perm2 = Vector{Int}(undef, 1000); @benchmark Base.permute!!($x2, copyto!($perm2, perm)) setup=(rand!($x2); randperm!($perm)) gcsample=false gctrial=false evals=1000 samples=100
BenchmarkTools.Trial: 100 samples with 1000 evaluations.
 Range (min … max):  2.932 μs …   4.214 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.284 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.293 μs ± 215.969 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

       ▃▃ ▃  ▃▁ ▁ ▁▁▁  ▆█▆▆ ▃▆▃▆                               
  ▄▄▄▁▄██▄█▁▄██▁█▁███▇▁████▇████▇▇▁▄▄▄▇▄▁▁▄▄▁▁▁▁▁▁▄▁▄▄▁▁▁▁▇▁▇ ▄
  2.93 μs         Histogram: frequency by time        3.83 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> x2 = rand(1000); perm = Vector{Int}(undef, 1000); perm2 = Vector{Int}(undef, 1000); @benchmark Base.permute!($x2, copyto!($perm2, perm)) setup=(rand!($x2); randperm!($perm)) gcsample=false gctrial=false evals=1000 samples=100
BenchmarkTools.Trial: 100 samples with 1000 evaluations.
 Range (min … max):  1.018 μs … 8.594 μs  ┊ GC (min … max):  0.00% … 79.15%
 Time  (median):     1.323 μs             ┊ GC (median):     0.00%
 Time  (mean ± σ):   1.730 μs ± 1.108 μs  ┊ GC (mean ± σ):  22.74% ± 23.38%

    █                                                        
  ▄▄██▄▃▂▂▃▃▁▁▁▁▁▃▁▄▃▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▁▁▁▁▁▁▂ ▂
  1.02 μs        Histogram: frequency by time       6.83 μs <

 Memory estimate: 7.94 KiB, allocs estimate: 1.
```

**Comment by stevengj** [comment]
Note that these follow-the-cycles algorithms become more of a win when the elements size is large, as in `Base.permutecols!!` where we are permuting the columns of a matrix (used for [sorting eigenvectors](https://github.com/JuliaLang/julia/blob/344f1f5a9cd5a1b55ab6f7a06aafb075cb66bade/stdlib/LinearAlgebra/src/eigen.jl#L135-L136)).

**Comment by LilithHafner** [comment]
Right now pkgeval will be pretty bad, I'm still waiting on https://github.com/JuliaArrays/StructArrays.jl/pull/272, the last major usage of permute!! in the package ecosystem.

**Comment by PallHaraldsson** [comment]
Should at least permute!! and invpermute!! be deprecated in 1.10 already (since it will be LTS likely, I wouldn't want it to promise it always being available)? Is deprecation only for API, not such no-exported "non-API"?

I went looking into users, well StructArrays and it seems to me not so much using Base.permute!! but rather adding to its definition (so I'm not worried about that package per se. It has 75 dependants, and while any one of those could be using it (I didn't check, and I actually doubt they use), could any of the users of those dependants be exposed?

https://github.com/JuliaArrays/StructArrays.jl/blob/e2f0667ecafc8e6d029242289ff68dee1aafa479/src/sort.jl#L3

I'm just thinking can we never drop anything from Base (even if not exported), in practice. Should you change your PR at StructArrays to still add to Base.permute!! definition, but pointing it to `Base.permute!` (not not break that package, or if not does it need a major-version upgrade?)? And actually here too, keep Base.permute!! as a synonym for Base.permute! if I understood things correctly. Then if it were never going away completely then I guess you don't need to deprecate, but still do that, as a hind on it not to be used?

Do permute!! and invpermute!! take up, yes, a tiny bit of space in the sysimage? I really like to make it smaller and things add up... I'm looking into what could be dropped to make it smaller; and it seems like a conflicting goal. Can we have our cake and eat it too somehow, I suppose `@noinline Base.permute!! = Base.permute!` would be one way, though still a non-zero amount of code (in the sysimage). Can we somehow have function definitions that are available but still invisible (not sure if a good idea), i.e. not this:

```
help?> Base.permute!!
  No documentation found.

  Base.permute!! is a Function.

  # 1 method for generic function "permute!!" from Base:
   [1] permute!!(a, p::AbstractVector{<:Integer})
       @ combinatorics.jl:139
```

That's not a very helpful doc, still indicates availability (would you want to censor that?). Does this info come from, the sysimage? I'm curious in general as there or if there were actual docs.

**Comment by LilithHafner** [comment]
We shouldn't backport this to 1.10, but I do think now is a good time to merge this. We never made these public and never promised to keep the,, so postponing deletion does not make them any more supported.

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1676137865) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bf097e2_vs_15b590b/report.html) is available.

**Comment by PallHaraldsson** [comment]
If you want to go ahead with this, then I agree it should be dropped ASAP in 1.11/master, early in 1.11 development, in case we need to revert it later.

>We shouldn't backport this to 1.10

If you drop this in 1.11 I would argue doing it in 1.10 too before its release, in case it will be LTS. It would be easy to add it back in 1.10.1, but if it stays in then it will be a (practically) breaking change to drop in in a 1.10.x, seemingly bad for an LTS.

**Comment by LilithHafner** [comment]
> 888 packages failed tests only on the current version.

😢

**Comment by LilithHafner** [comment]
After Rerunning after https://github.com/JuliaRegistries/General/pull/91067
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1711878520) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bf097e2_vs_15b590b/report.html) is available.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1717713494) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bf097e2_vs_15b590b/report.html) is available.

**Comment by LilithHafner** [comment]
@nanosoldier `runtests(["PooledArrays"], configuration=(registry="LilithHafner/General#permute-testing", ), vs = ":master")`

**Comment by LilithHafner** [comment]
Trying again after fixing a bug in my custom registry setup:
@nanosoldier `@nanosoldier runtests(["PooledArrays"], configuration=(registry="LilithHafner/General#permute-testing", ), vs = ":master")`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1718250408) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bf097e2_vs_8660cdd/report.html) is available.

**Comment by LilithHafner** [comment]
@nanosoldier `runtests(["PooledArrays"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1722564353) has completed - no new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c73c649_vs_28d0e1e/report.html) is available.

**Comment by LilithHafner** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1723442632) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c73c649_vs_28d0e1e/report.html) is available.

**Comment by LilithHafner** [comment]
Failures due to folks using old versions of PooledArrays and StructArrays. I'll try again in a while.

**Pull request closed without merging**
