### PR TITLE
fixed `cumprod` and `cumprod!`

### PR DESCRIPTION
**Pull request by yomichi**
`cumprod` and `cumprod!` return wrong answer for a long array (length >= 128).
A test code and the result are following :

```
julia> xs = fill(0.9, 1000);

julia> Test.@test_approx_eq prod(xs) cumprod(xs)[end]
ERROR: assertion failed: |prod(xs) - (cumprod(xs))[end]| <= 2.117582368135751e-18
  prod(xs) = 1.7478712517226966e-46
  (cumprod(xs))[end] = 1.9068411172040859e-6
  difference = 1.9068411172040859e-6 > 2.117582368135751e-18
 in error at error.jl:20
 in test_approx_eq at test.jl:137
 in test_approx_eq at test.jl:147
```

`VERSION >= v"0.3.6"` have this bug.

### CODE REVIEW

**Comment by jiahao** [comment]
Wow, that's a pretty silly mistake. Thanks for catching that.

**Comment by ScottPJones** [comment]
I hate to ask... where did the names for these functions come from?  Matlab?  They *really* could use a name change...

**Comment by tkelman** [comment]
@yomichi ouch, thanks for finding and fixing this. #9650 was missing tests of cumprod, apparently.

@ScottPJones Yes these names come from Matlab. If you have better suggestions for name or API, please file a new issue.

**Comment by KristofferC** [comment]
@ScottPJones `cumprod` is used in Matlab, Numpy, R, Scilab, panda etc.

I am not sure how asking "where did these name come from" in an issue not related to naming, without even putting in the effort of suggesting a better name is such a good idea. 

Better to make a PR with your suggested changes and the discussion can go there.

**Comment by ScottPJones** [comment]
@tkelman, my surprise has nothing to do about the issues I've raised recently about naming (although that's why I suspected it was from Matlab), but rather to do with my own dirty mind! ;-)  (You seriously haven't had to deal with a bunch of Belgian developers, joking about all the things I'm doing at night with "Julia").
@KristofferC My comment wasn't so much a criticism of the function, just surprise that nobody had decided to name them something that sounds less.... XXX

**Comment by tkelman** [comment]
Let's keep the issue tracker PG. It's short for cumulative.

**Comment by ScottPJones** [comment]
@tkelman I understood that it was short for cumulative - and I wasn't trying to make things not "PG"... I was simply surprised that the name hadn't caused any comment previously... I've run into issues where even a name that sounds totally fine in one language is bad in another... that's much harder to watch out for... for example, take the word for "year" in Portuguese, it sounds really bad in Spanish.

**Comment by KristofferC** [comment]
No offense, but it feels like every issue I read now has a @ScottPJones life story in it.

I think sometimes it is important to evaluate what noise/signal ratio you produce.

**Comment by tkelman** [comment]
backported in 127c4b9d2abc1806bf47a41b14be83fcba7b6d66

**Pull request merged**
