### PR TITLE
This PR is to test nanosoldier running sorting benchmarks

### PR DESCRIPTION
**Pull request by LilithHafner**

### CODE REVIEW

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47795#issuecomment-1336328387) failed.

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("linalg")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47795#issuecomment-1336359448) has completed - successfully executed benchmarks. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8bbf44e/report.md).

**Comment by LilithHafner** [comment]
I can't reproduce this locally

```julia
(jl_18BzHl) pkg> add https://github.com/JuliaCI/BaseBenchmarks.jl
     Cloning git-repo `https://github.com/JuliaCI/BaseBenchmarks.jl`
 [...]
  11 dependencies successfully precompiled in 28 seconds

julia> using BaseBenchmarks

julia> BaseBenchmarks.load!("sort");

julia> run(BaseBenchmarks.SUITE)
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "sort" => 4-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "insertionsort" => 32-element BenchmarkTools.BenchmarkGroup:
                  tags: []
                  ("sort! forwards", "ones") => Trial(146.740 μs)
                  ("sortperm reverse", "ascending") => Trial(1.222 s)
                  ("sort forwards", "random") => Trial(1.046 s)
                  ("sortperm! forwards", "ascending") => Trial(103.755 μs)
                  ("sort forwards", "descending") => Trial(848.311 ms)
                  ("sort! forwards", "random") => Trial(1.092 s)
                  ("sortperm forwards", "random") => Trial(4.208 s)
                  ("sortperm forwards", "ascending") => Trial(142.864 μs)
                  ("sort reverse", "descending") => Trial(76.990 μs)
                  ("sort! reverse", "descending") => Trial(53.025 μs)
                  ⋮
```

**Comment by DilumAluthge** [comment]
Is it just `sort` that Nanosoldier is having trouble with?

**Comment by DilumAluthge** [comment]
@nanosoldier `runbenchmarks("sort")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47795#issuecomment-1336711093) failed.

**Comment by DilumAluthge** [comment]
@nanosoldier runbenchmarks(ALL)

**Comment by maleadt** [comment]
Yes, see https://github.com/JuliaLang/julia/pull/47788#issuecomment-1336313518

**Comment by DilumAluthge** [comment]
@nanosoldier `runbenchmarks(ALL)`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47795#issuecomment-1337096240) failed.

**Comment by LilithHafner** [comment]
@nanosoldier runbenchmarks("sort")

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47795#issuecomment-1348872321) has completed - successfully executed benchmarks. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/bb65aca/report.md).

**Pull request closed without merging**
