### PR TITLE
Avoid a branch in `getindex(::ASCIIString,::Int)`

### LINKED ISSUE #11768: `next` not inlined for ASCIIStrings
I've realized while working on https://github.com/JuliaLang/julia/pull/11708 that `next(::ASCIIString, ::Int)` was never inlined on 0.4 master, while `nextind` is. This means that using the most obvious construct `[c for c in s]` is slower than manually iterating over the string and indexing it. That's unexpected to me since the definition is very simple:
```julia
next(s::DirectIndexString, i::Int) = (s[i],i+1)
```

Below is a simple test case:
```julia
# Most obvious comprehension (not inlined)
function f(s)
    [c for c in s]
end

# Iteration protocol, manually written (still not inlined)
function g(s::ASCIIString)
    out = Vector{Char}(length(s))
    i = 1
    state = start(s)
    while !done(s, state)
        out[i], state = next(s, state)
        i += 1
    end
    out
end

# Using nextind(), inlined
function h(s::ASCIIString)
    out = Vector{Char}(length(s))
    i = 1
    state = 1
    while state <= length(s)
        out[i] = s[state]
        state = nextind(s, state)
    end
    out
end

s = "jkm sqdkqmsj j k fsdfsd sdjkfls jkljmj"
f(s); g(s); h(s);
@time for i in 1:1000000 f(s) end
@time for i in 1:1000000 g(s) end
@time for i in 1:1000000 h(s) end
```

And the timings:
```
julia> @time for i in 1:1000000 f(s) end

 303.891 milliseconds (1000 k allocations: 214 MB, 9.93% gc time)

julia> @time for i in 1:1000000 g(s) end
 297.436 milliseconds (1000 k allocations: 214 MB, 9.24% gc time)

julia> @time for i in 1:1000000 h(s) end
 234.801 milliseconds (1000 k allocations: 214 MB, 11.36% gc time)
```

(But even without timings you can see that no inlining happens in the two first functions.)

### PR DESCRIPTION
**Pull request by carnaval**
Should fix #11768.

### CODE REVIEW

**Comment by nalimilan** [comment]
Interesting! So LLVM considers that the branch is costly enough that it's not worth inlining this function?

**Comment by yuyichao** [comment]
@nalimilan I think it's probably julia level inlining (i.e. typeinf)?

**Comment by carnaval** [comment]
Yes we don't use llvm inlining actually (cf Keno)

**Comment by nalimilan** [comment]
OK, thanks. Looks like the inlining heuristics could be made more inclined towards inlining.

**Comment by carnaval** [comment]
Our inlining heuristic is a bit of a mess IMO, but it's hard to balance because if you inline too much compilation can become very slow (and code can also become slower). We should still have Jameson have a look at this one maybe there is a good fix.

**Comment by nalimilan** [comment]
Yes, I can imagine it's very hard to find the best behaviour...

**Pull request merged**
