### PR TITLE
Improve prepare_release.sh

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ararslan** [comment]
Can you elaborate on what in particular this improves upon?

**Comment by albap** [comment]
I used a ( subshell ) to avoid having to cd back.
https://github.com/koalaman/shellcheck/wiki/SC2103

I also quoted variables to prevent globbing and word splitting.
https://github.com/koalaman/shellcheck/wiki/SC2086
https://github.com/koalaman/shellcheck/wiki/SC2046

Is this a must?
Probably not.
But it's good for future-proof and to keep on the safe side.
I don't think there's anything negative to this.

**Comment by tkelman** [comment]
it makes the script harder to read, and nearly all of these will never have spaces in the values

**Comment by albap** [comment]
Yeah, I think you're right. It makes harder to read. The benefits aren't too good to outweigh that. 
Sorry, closing.

**Pull request closed without merging**
