### PR TITLE
enable inline allocation of structs with pointers

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-566697053):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(`git push`, ProcessExited(128)) [128]

```
Unfortunately, the logs could not be uploaded.
cc @maleadt

**Comment by maleadt** [comment]
Ah, forgot to add Nanosoldier as a repository collaborator after switching to his account... I pushed the report manually: https://github.com/maleadt/BasePkgEvalReports/blob/master/pkgeval-86ae65b_vs_630a551/report.md

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-567616466) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/f51be6e297b3b70bb41fc9223338cabe5b12edaa/pkgeval-54133f9_vs_0edadf1/report.md). cc @maleadt

**Comment by vtjnash** [comment]
Working through this list, will update as I learn more:

- YAJL: invalid code, filed https://github.com/christopher-dG/YAJL.jl/issues/3
- Tulip: OrderedDict (OrderedCollections) is using the old `jl_arrayunset`, and I implemented it wrong (new code should usually use `Base._unsetindex!` now for better performance.


TODO:
AIBECS v0.4.1 (a segmentation fault happened) vs. AIBECS v0.4.1 (successful)
AmplNLReader v0.6.0 (there were unidentified errors) vs. AmplNLReader v0.6.0 (successful)
BSON v0.2.4 (a segmentation fault happened) vs. BSON v0.2.4 (successful)
BSONMmap v0.2.1 (there were unidentified errors) vs. BSONMmap v0.2.1 (successful)
BSONqs v0.6.2 (a segmentation fault happened) vs. BSONqs v0.6.2 (successful)
Bridge v0.10.0 (package has test failures) vs. Bridge v0.10.0 (successful)
FastIOBuffers v0.3.1 (package has test failures) vs. FastIOBuffers v0.3.1 (successful)
HTTP v0.8.8 (test duration exceeded the time limit) vs. HTTP v0.8.8 (successful)
KissMCMC v0.2.0 (package has test failures) vs. KissMCMC v0.2.0 (successful)
LazyArrays v0.14.10 (package has test failures) vs. LazyArrays v0.14.10 (successful)
LightQuery v0.5.0 (test duration exceeded the time limit) vs. LightQuery v0.5.0 (successful)
MambaModels v1.0.0 (a segmentation fault happened) vs. MambaModels v1.0.0 (successful)
Nabla v0.12.1 (package has test failures) vs. Nabla v0.12.1 (successful)
PushVectors v0.2.0 (package has test failures) vs. PushVectors v0.2.0 (successful)
SMM v1.4.0 (package has test failures) vs. SMM v1.4.0 (successful)
SecretSanta v0.1.0 (a segmentation fault happened) vs. SecretSanta v0.1.0 (successful)
SpatialJackknife v1.0.1 (package has test failures) vs. SpatialJackknife v1.0.1 (successful)
TravelingSalesmanExact v0.3.2 (there were unidentified errors) vs. TravelingSalesmanExact v0.3.2 (successful)

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-568549730) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/ebe3aa7fcfd6777eeb33724fbd589e3e4f414b19/pkgeval-23159b0_vs_1c89535/report.md). cc @maleadt

**Comment by vtjnash** [comment]
Unfortunately that didn't include #34186 or #34176, so it's not especially useful. AIBECS is still probably worth looking into, but fails when I try to run it locally. RoME and OhMyREPL might be interesting (appear to have hit a deadlock inside Pkg).

**Comment by KristofferC** [comment]
> OhMyREPL might be interesting (appear to have hit a deadlock inside Pkg).

I've seen it deadlock sometimes in PkgEval. My guess is that it is this test that hangs: https://github.com/KristofferC/OhMyREPL.jl/blob/70927549f78591e9b572714b5ed5b8e3a25f795a/test/flicker.jl#L5-L19. It is most likely unrelated to this PR though.

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-600762091) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/523e4ee504b0379db11374c6facef32b68974464/pkgeval/by_hash/b9de078_vs_7f28d91/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Found the issue in EfficientGlobalOptimization. NLopt has an array of immutable structs of two pointers each (`Callback_Data`). It passes those objects to C for use as callback closure pointers, but they no longer have persistent addresses. That will need to be fixed by making the structs mutable.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-609993115) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/8db31309c045e14ea6fe755ea647598f382ff56c/60db763_vs_755f479/report.md). cc @ararslan

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-610477494) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/95a1e8640aae49abd4751d1a0546760049653b53/pkgeval/by_hash/3ec2fab_vs_16652a6/report.md). cc @maleadt

**Comment by vtjnash** [comment]
Yikes, that report is real unhealthy due to https://github.com/JuliaLang/julia/issues/35393

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-611298570) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/63b3d4ab2856f999875e985f419ced7685536bad/pkgeval/by_hash/198567a_vs_70d7e1e/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AMRVW", "Bridge", "BufferedStreams", "DiskDataProviders", "EfficientGlobalOptimization", "FastIOBuffers", "LazyArrays", "LoopThrottle", "Nabla", "RigidBodyDynamics", "Rocket", "SMM", "StaticPolynomials", "TensorNetworkAD", "YAAD", "YAJL"], vs = ":master")`

**Comment by maleadt** [comment]
NLOpt 0.5.2 was me hacking PkgEval's registry to include Jeff's fix; I'm going to undo that now since it holds the daily evaluations back (so it might fail again, but the fix has shown to be working).

**Comment by JeffBezanson** [comment]
Some investigations:

YAJL - needs the same kind of fix as NLopt; will make a PR
SMM - failure looks plausible but I couldn't reproduce it locally

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-611685884) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/2b2a9ec3b5090f74eae199a556343c071ecf92f5/pkgeval/by_hash/198567a_vs_8a5b323/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34126#issuecomment-616177450) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2522ed4ee6fa1852b8a0748c3049b6d94df041b1/61ae558_vs_dd738f9/report.md). cc @ararslan

**Comment by vtjnash** [comment]
That's looking super. Only one I wondered about (if it's real) was:
```
["string", "repeat", "repeat char 2"] | 1.74 (5%) ❌ | 1.00 (1%)
```

**Comment by JeffBezanson** [comment]
It looks like `repeat char 2` is a really fast benchmark (~160ns). I don't see any difference locally.

**Comment by quinnj** [comment]
Exciting!!

**Comment by oschulz** [comment]
From what I understand, this would close #14955, @JeffBezanson ? If so, I'd update the docs of [UnsafeArrays](https://github.com/JuliaArrays/UnsafeArrays.jl), which I guess would then be largely obsolete when using Julia v1.5. This is exciting!

**Comment by JeffBezanson** [comment]
Yes. Would be interesting to see how performance now compares with a non-trivial use of UnsafeArrays.

**Comment by oschulz** [comment]
@JeffBezanson , it's not a very involved benchmark, but looks like the result is dramatic, in a very positive way: JuliaArrays/UnsafeArrays.jl#8

**Pull request merged**
