### PR TITLE
Fix sign() for ranges in 0.4, add tests

### PR DESCRIPTION
**Pull request by nalimilan**
Fixes https://github.com/JuliaLang/julia/issues/16067.

The second commit also applies to master, I'll commit it directly once this is merged.

### CODE REVIEW

**Comment by tkelman** [comment]
Also test the other methods this changes: `-, ~, conj`

**Comment by nalimilan** [comment]
Right. I've added tests for those (except `-` for ranges, which was already covered).

**Comment by timholy** [comment]
Trying to save some CI time I attempted to cancel my build and ended up canceling this one instead. Sorry. (Though it looks like appveyor failed, so perhaps travis could be aborted?)

**Comment by nalimilan** [comment]
I thought it failed with a weird error instead. Anyway, not a big deal.

**Comment by timholy** [comment]
Yeah, I saw that now on one of mine. Seems to be some kind of PCRE problem in 32-bit.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/16188

**Comment by tkelman** [comment]
This just needed the fix backported for release-0.4. Other cases may have needed rebases to pull in the fix from master. I think that issue is solved now.

@nalimilan do please forward-port the tests

**Pull request merged**
