### PR TITLE
[release-0.4, RFC] backports for 0.4.2

### PR DESCRIPTION
**Pull request by tkelman**
cc @viralbshah ~~still working on this, putting up my progress so far~~ more or less ready I think, running PkgEval now

### CODE REVIEW

**Comment by nalimilan** [comment]
After merging, and when you'll be ready to release 0.4.2, could you leave me some time to build RPM packages from the branch to check everything is OK?

**Comment by tkelman** [comment]
Glad you're paying attention. Also cc @petercolberg who's maintaining the debian package now.

The point of doing these in a branch and opening a PR is giving people some time to review my backports and test things (including myself running PackageEvaluator), do you need to wait for me to merge it to do that?

**Comment by bicycle1885** [comment]
@tkelman Could you include [this patch](https://github.com/JuliaLang/julia/commit/18706cbda833576a9b08426d393b2ccd042aedeb) in this release? I'd like to write code that depends on this fix.

**Comment by tkelman** [comment]
I haven't pushed the backport of that yet but it's on my list, I'm about to. If you depend on backported changes in any publicly registered packages then please be strict about marking `julia 0.4.2` in your `REQUIRE` file (unless your package still manages to support 0.3 and you're dealing with an 0.4-only regression).

**Comment by tkelman** [comment]
Hm, OOM killer on Travis. It's looking very very likely that #13491 was responsible for that. I can backport our RSS measurement/restarting bandaid for Travis, but should carefully compare perf here or I may have to take #13491 out of this again.

**Comment by tkelman** [comment]
Looks like there's a roughly 10% regression here relative to 0.4.1 on `rand_mat_stat` and `micro.mem`. This is on top of the 15% regression in `rand_mat_stat` (and about 7% in `micro.mem`) from 0.4.0 to 0.4.1, ref https://github.com/JuliaLang/julia/pull/13834#issuecomment-153717323

**Comment by bicycle1885** [comment]
@tkelman Thank you! That will be used in my application script, not in packages.

**Comment by tkelman** [comment]
Pre-release binaries are available for testing at:
https://s3.amazonaws.com/julianightlies/bin/linux/x64/0.4/julia-0.4.2-456f38d433-linux64.tar.gz
https://s3.amazonaws.com/julianightlies/bin/linux/x86/0.4/julia-0.4.2-456f38d433-linux32.tar.gz
https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.4/julia-0.4.2-456f38d433-win64.exe
https://s3.amazonaws.com/julianightlies/bin/winnt/x86/0.4/julia-0.4.2-456f38d433-win32.exe
https://s3.amazonaws.com/julianightlies/bin/osx/x64/0.4/julia-0.4.2-456f38d433-osx.dmg (still building, not ready yet)

These links are temporary and won't work forever.

**Comment by ViralBShah** [comment]
@one-more-minute Can we test the pre-release binaries for Juno?

**Comment by tkelman** [comment]
PackageEvaluator results - 9 packages fail tests at 456f38d but succeed at 0.4.1 (and one, LibCURL.jl, has a long-standing intermittent failure making it look the other way around): https://gist.github.com/a0e1e9fe76b99d1112ee

- Benchmark.jl (intermittent and deprecated I think)
- CompilerTools.jl and ParallelAccelerator.jl (cc @ehsantn @DrTodd13 @ninegua @lkuper etc)
- Coverage.jl (cc @IainNZ)
- GeoStats.jl (cc @juliohm, looks like a tolerance might be too tight)
- NullableArrays.jl (cc @davidagold, I suspect this one is due to @timholy's #13803)
- SALSA.jl (cc @jumutc)
- StackTraces.jl (cc @spurll)
- Taro.jl (cc @aviks)

The PackageEvaluator JSON logs are attached to the gist, but I could use some help pinpointing what on this branch is responsible for the failures.

**Comment by IainNZ** [comment]
@tkelman the error in Coverage is due to a change in the parser - the code does mention https://github.com/JuliaLang/julia/issues/9663 although that doesn't seem to be related to the backports

**Comment by juliohm** [comment]
Thank you @tkelman, I increased the tolerance. Let me know if it doesn't solve the issue.

**Comment by tkelman** [comment]
@IainNZ I wouldn't be surprised if the first few commits here
make a difference w.r.t. https://github.com/JuliaLang/julia/pull/10479

**Comment by jumutc** [comment]
Thank you @tkelman, I had plans to fix everything related to **nightly** builds. I will proceed with changes ASAP!

**Comment by nalimilan** [comment]
> Glad you're paying attention. Also cc @petercolberg who's maintaining the debian package now.
> 
> The point of doing these in a branch and opening a PR is giving people some time to review my backports and test things (including myself running PackageEvaluator), do you need to wait for me to merge it to do that?

@tkelman It's just that I used to wait for the PR to be merged to `release-*` before building the packages, as my script was set up to do that. If I were you I wouldn't be afraid of merging things into release-0.4 that sometimes need to be reverted: better leave commits sit in a public branch that some people may want to test for as long as possible. But do as you prefer, I've updated my script to build any PRs, and this one builds fine.

**Comment by iamed2** [comment]
StackTraces also does some stuff with innards so it may also need to distinguish between 0.4.1 and 0.4.2.

**Comment by spurll** [comment]
Looks like my test cases for StackTraces were a little too strict in their inlining expectations. Tests should pass now.

**Comment by DrTodd13** [comment]
The CompilerTools and ParallelAccelerator issues have been fixed. 

Thanks for the report. 

Todd 

----- Original Message -----

**Comment by tkelman** [comment]
Thanks @DrTodd13, do tag new versions soon if you can, so the PackageEvaluator results won't show a regression and users who upgrade right away to 0.4.2 can still use ParallelAccelerator.

**Comment by tkelman** [comment]
Given the breakage in NullableArrays and SALSA, and possibly other non-public or already-failing or under-tested code I'm going to revert the backport of #13803 for now. Sorry Tim.

**Comment by ViralBShah** [comment]
@one-more-minute I verified that Juno works with the test 0.4 build you provided me.

**Comment by davidagold** [comment]
@tkelman Thank you for the notice. I'll try to take a look at the issue this weekend and see if I can make a fix.

**Comment by tkelman** [comment]
For now I'm not going to backport the relevant commit, if it broke 2 registered previously-passing packages then it likely would also break some non public user code. That code (and NullableArrays) is also now broken on 0.5-dev, but that's the right place for breaking changes to go.

**Comment by JeffBezanson** [comment]
If this includes a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9, it also needs to include 2155f60821be758e1d020bcb2329e6dca2925776. The commit gives slightly better info on inlined functions at the expense of making many things worse (#13725).

**Comment by tkelman** [comment]
So, should it?

CompilerTools.jl needs a tag. GeoStats.jl and StackTraces.jl have already been fixed. NullableArrays.jl and SALSA.jl (and ParallelAccelerator.jl) are passing again with #13803 reverted. Benchmark.jl and Taro.jl have intermittent testing issues. That leaves just Coverage.jl. I'll see whether https://github.com/JuliaLang/julia/commit/2155f60821be758e1d020bcb2329e6dca2925776 makes any difference?

Iain, any estimate on how hard and how long it'll be to fix?

**Comment by JeffBezanson** [comment]
I'm inclined to be very conservative with backports, and I'd exclude both commits.

**Comment by tkelman** [comment]
Reverting 488fb5a5978589fec4e703203d333f27b859a4aa presumably means b8a6d771042add982a6a8739994c6f7dba2f4461 and 617db6b7625acebb22361c63ab1d898fa3f1e1bc should also be reverted? And re-fix the doctests again.

**Comment by JeffBezanson** [comment]
Yes, but https://github.com/JuliaLang/julia/commit/b8a6d771042add982a6a8739994c6f7dba2f4461 is a different issue and should be safe. However it can be excluded if we want to simply minimize the number of backports.

**Comment by tkelman** [comment]
I was just assuming they should go together if they were related enough to originally come from the same PR. I also don't know which of these backports is responsible for breaking Coverage.jl but if I'm going to be reverting some of them then I'd like to fix it.

**Comment by timholy** [comment]
> Given the breakage in NullableArrays and SALSA, and possibly other non-public or already-failing or under-tested code I'm going to revert the backport of #13803 for now. Sorry Tim.

Sorry I didn't notice this earlier. But I'm fine with being cautious about this---breakage is no fun.

If I get time I'll try to see why NullableArrays broke.

**Comment by davidagold** [comment]
NullableArrays broke because of [this](https://github.com/JuliaLang/julia/pull/13803/files#diff-3377d917b3abf3efb064b20a9067a794R975). The argument signature of the internal `gen_broadcast_function` in the NullableArrays `broadcast` interface was [declared too restrictively](https://github.com/JuliaStats/NullableArrays.jl/blob/33e97108cd253d5e8e376265a58e92f2e6b93981/src/broadcast.jl#L45). Removing the `::Function` annotation from `f` fixes the problem. I can push an immediate fix to this later today. Hopefully in the near future I'll get some time to see what else has gotten out of sync between `NullableArray` interfaces and respective Base interfaces.

NullableArrays also has an unrelated failure on the latest master, but that one is due to dropping of singleton dimensions. Since the defined behavior of range indexing into a multi-dimensional array has changed, the test is outdated.

**Comment by tkelman** [comment]
@amitmurthy any idea what caused the following on linux 32 bit travis?
```
ERROR: LoadError: test error in expression: fill(id_other,num_small_requests) == [remotecall_fetch(id_other,myid) for i = 1:num_small_requests]
UndefRefError: access to undefined reference
 in ht_keyindex2 at dict.jl:602
 in setindex! at dict.jl:643
 in lookup_ref at multi.jl:519
 in remotecall_fetch at multi.jl:726
 in remotecall_fetch at multi.jl:734
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
 in ht_keyindex2 at dict.jl:602
 in setindex! at dict.jl:643
 in lookup_ref at multi.jl:519
 in remotecall_fetch at multi.jl:726
 in remotecall_fetch at multi.jl:734
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /tmp/julia/share/julia/test/parallel_exec.jl, in expression starting on line 287
```

**Comment by tkelman** [comment]
Aside from that Travis error this is looking pretty good on PackageEvaluator in the latest run, these are all intermittent problems that I don't think are related to Base
```
--- 0.4.1.summary       2015-12-03 19:50:44.521061356 -0500
+++ 9f8ec24adb.summary  2015-12-03 19:50:59.632767618 -0500
@@ -31,3 +31,3 @@
 BDF.json "tests_pass"
-Benchmark.json "tests_pass"
+Benchmark.json "tests_fail"
 BenchmarkLite.json "no_tests"
@@ -227,2 +227,3 @@
 GeoInterface.json "tests_pass"
+GeoIP.json "tests_fail"
 GeoJSON.json "tests_pass"
@@ -490,3 +491,3 @@
 NLreg.json "tests_fail"
-NLsolve.json "tests_fail"
+NLsolve.json "tests_pass"
 NMEA.json "tests_pass"
@@ -510,3 +511,3 @@
 OnlineMoments.json "tests_pass"
-OnlineStats.json "tests_pass"
+OnlineStats.json "tests_fail"
 OpenCL.json "not_possible"
```
(GeoIP didn't output a json file in the 0.4.1 job for some reason?)

**Comment by amitmurthy** [comment]
That error is being thrown while inserting a new key-value pair into a Dict. Does not seem to be anything to do with the parallel stuff. Can we try without the last commit?

**Comment by tkelman** [comment]
https://travis-ci.org/JuliaLang/julia/builds/94800834

**Comment by amitmurthy** [comment]
I just restarted the Travis build to see if it shows up again.

**Comment by tkelman** [comment]
Something backported on this branch introduces an intermittent failure, since eccf2316ec689d81b succeeded `make testall` 50 times in a row locally, but 74dcb330dd76ecad44739dac36229616d71ce557 had several failures out of the same number of runs. Needs a bisect and a revert.

**Comment by Keno** [comment]
Which OS?

**Comment by tkelman** [comment]
Linux 64. It's a bit unreliable to bisect since it happens somewhat rarely, but my suspicion is it's most likely https://github.com/JuliaLang/julia/commit/8b3c67bc46a093ba50472ec527a677794a3481d0

**Comment by JeffBezanson** [comment]
Let's also make sure this doesn't exhibit #14245.

**Comment by amitmurthy** [comment]
Is it the same failure every time?

**Comment by tkelman** [comment]
Not sure. These logs are long and slightly out of order because of the redirection to get stdout and stderr to go to the same file: https://gist.github.com/edeec37dc129f2a5c2f2

There are some conversion errors and bounds errors here https://gist.githubusercontent.com/anonymous/edeec37dc129f2a5c2f2/raw/51db4fbb6d7895b723fe5b6994d19539fe8d0f7c/tests-74dcb330dd76ecad44739dac36229616d71ce557.log

and an UndefRefError here https://gist.githubusercontent.com/anonymous/edeec37dc129f2a5c2f2/raw/51db4fbb6d7895b723fe5b6994d19539fe8d0f7c/tests-cbebbb71b58531c6aa00906188363886955acaa0.log

**Comment by amitmurthy** [comment]
https://github.com/JuliaLang/julia/commit/8b3c67bc46a093ba50472ec527a677794a3481d0 is a hygiene fix. We can try reverting that, but the issue actually seems to be a memory corruption.

**Comment by amitmurthy** [comment]
FWIW, ```for i in `seq 1 50`; do ../julia runtests.jl parallel; done``` just went through on a local Linux 64 machine. Since the parallel test spawns out `parallel_exec.jl`, the original `UndefRef` error should have shown up.

Something in the Travis environment is triggering this?

**Comment by tkelman** [comment]
Or possibly something caused by a different earlier test executed on the same worker?

**Comment by amitmurthy** [comment]
That does not hold true for the parallel test. 

https://github.com/JuliaLang/julia/blob/071390affb0000dfdbcf5837a7814dfd2571ecf6/test/parallel.jl#L14-L16

`parallel_exec.jl` is run outside the initial set of julia processes.

**Comment by amitmurthy** [comment]
It took a few hours, but 50 runs of `runtests.jl all` just finished with no errors locally.

```
  | | |_| | | | (_| |  |  Version 0.4.2-pre+117 (2015-12-03 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  tk/backports-0.4.2/74dcb33* (fork: 99 commits, 9 days)
|__/                   |  x86_64-linux-gnu

julia> versioninfo()
Julia Version 0.4.2-pre+117
Commit 74dcb33* (2015-12-03 21:37 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
I think it might be that my openblas patch should be windows only. Needs looking into upstream to see if the next release is going to have this same issue.

**Comment by tkelman** [comment]
though until I backport #13569, travis should be using the ppa for openblas so that doesn't make much sense

**Comment by tkelman** [comment]
If this passes on Travis and AppVeyor, I think it's ready to merge and tag. If it doesn't, please copy and save the Travis logs to a gist before restarting any failed jobs.

**Comment by nalimilan** [comment]
FWIW, the Fedora/RHEL package builds fine with the current version of this PR.

**Pull request merged**
