### PR TITLE
workaround for dict access issue in a finalizer

### PR DESCRIPTION
**Pull request by amitmurthy**
This is a workaround for https://github.com/JuliaLang/julia/issues/14295 and https://github.com/JuliaLang/julia/issues/14445

### CODE REVIEW

**Comment by amitmurthy** [comment]
@yuyichao can you think of a different/better workaround? I'll merge this and https://github.com/JuliaLang/julia/pull/14457 in a day in the absence of any other approaches.

**Comment by yuyichao** [comment]
Can't think of a better workaround without fixing our dict implementation

**Comment by tkelman** [comment]
Can a test case be added that would fail without this change?

**Comment by amitmurthy** [comment]
Something like this
```
julia> @time for n = 1:10^6
          fetch(@spawnat myid() myid())
       end
  8.801960 seconds (50.66 M allocations: 1.747 GB, 16.59% gc time)
```

But it will add to both the memory pressure as well as elapsed time on already stressed CI infra. It is more of a stress test, rather than unit tests that the test suite is comprised of.

**Comment by tkelman** [comment]
Maybe under `JULIA_TESTFULL` then?

**Pull request merged**
