### PR TITLE
use git subtree to graft Pkg3, etc. into stdlib

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This was astonishingly easy to do with `git subtree`. It really might be a great solution for developing stdlib packages outside of the main repo but having the code available without any additional futzing upon checkout of julia. On this branch, you can do `using Pkg3` from the julia prompt and it works:
```jl
julia> using Pkg3
[ Info: Precompiling module Pkg3

pkg> init
[ Info: Initialized environment in /Users/stefan/projects/julia by creating the file Project.toml

pkg> add JSON
[ Info: Resolving package versions
[ Info: Updating "Project.toml"
 [682c06a0] + JSON v0.16.4
[ Info: Updating "Manifest.toml"
 [34da2185] + Compat v0.49.0
 [682c06a0] + JSON v0.16.4
 [4d1e1d77] + Nullables v0.0.3
```
Resulting project and manifest files.

#### Project.toml:
```toml
[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
```

#### Manifest.toml
```toml
[[Compat]]
git-tree-sha1 = "e74e175d5b9c7411f17d7db90ccdfdf492bde9e9"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.49.0"

[[JSON]]
deps = ["Compat", "Nullables"]
git-tree-sha1 = "e4b57d438f523a2ad5f9f3510598f00961d4bc08"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.16.4"

[[Nullables]]
deps = ["Compat"]
git-tree-sha1 = "05176cebbb49ab979006b0bd12008c3f9a54f60c"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "0.0.3"
```

#### Upshot
```jl
julia> using JSON
[ Info: Precompiling module JSON
ERROR: LoadError: LoadError: ArgumentError: Module Unicode not found in current path.
Run `Pkg.add("Unicode")` to install the Unicode package.
```
Ok, so there are some rough edges to smooth out, but this finally basically works.

### CODE REVIEW

**Comment by vchuravy** [comment]
Why do we need `Pkg3/ext`? We should replace those with proper stdlib
modules. Also I still prefer the approach I prototyped in #25714 and don't
quite see the benefit of using `git sub-tree`.

**Comment by StefanKarpinski** [comment]
Yes, the things in Pkg3/ext should become proper stdlib modules, but I wasn't quite ready to add those right now – they are at the moment, implementation details of Pkg3. I'm not 100% sold on git subtree, but so far it's been a pleasure to use. The main advantages seem to be:

1. See history of stdlib packages in the same repo as Base.
2. Develop stdlib packages together with Base, upstream the changes when they're ready.

**Comment by StefanKarpinski** [comment]
Milestoning, not because we have to do it this way but because we have to do _something_ like this.

**Comment by o314** [comment]
Drupal followed a similar way a few month ago

> Subtree splits are now being automated by drupal infrastructure. We have a jenkins job that is polling git.drupal.org/project/drupal.git every minute and runs a script that traverses a git checkout of drupal, looking for composer.json files. If it discovers a composer.json (except in test directories), it will:
>
> - create a subtree split of that directory
> - parse composer.json
> - If it doesnt exist, it will create a new repo at github.com/drupal/{composer-project-name}
> - It pushes the subtree split to github.com/drupal/{composer-project-name}
> - If it doesnt exist, it will create a new entry at packagist.org
> - If the packagist entry does exist, it is instructed to update its entry from github.
>
> So new components or new composer.json parts that we wish to expose outside the drupal ecosystem should automatically appear on packagist.
>
> @ https://www.drupal.org/project/infrastructure/issues/2352091#comment-12056883

The symfony framework (~ new drupal kernel, and more) guys gave a talk about this at drupalcon 2016 : [a monorepo vs manyrepos (slides)](https://speakerdeck.com/fabpot/a-monorepo-vs-manyrepos), [(video)](https://www.youtube.com/watch?v=4w3-f6Xhvu8), and [(code)](https://github.com/splitsh/lite)

**Comment by StefanKarpinski** [comment]
Triage dixit: no Compat in stdlib, so excise that dependency. Pkg3 + SHA in base is fine, but favors @vchuravy's approach to use @vtjnash's "git external" mechanism. The TerminalMenus is a different story since it should be merged into REPL; for that, using subtree to import and do a temporary bridge between internal and external is fine.

**Comment by JeffBezanson** [comment]
In triage several of us prefer @vchuravy 's approach (#25714). I think that will make it clearer that the packages are separate, and owned by different repos. There's something to be said for being able to update Base and stdlibs all at once, but we're already used to having many packages in external repos that might need to be updated in sync with Base.

**Comment by KristofferC** [comment]
That seems very(!!!) unfortunate in my view. Having stuff in the same repo tremendously ease development and coherence. All other stdlibs live in the repo. Why should Pkg3 be the only one getting punished!?

>  I think that will make it clearer that the packages are separate, and owned by different repos.

I am all for getting rid of the Pkg3 repo and just have it here if it would mean not having to do this. Just develop it here then.
 
> but we're already used to having many packages in external repos that might need to be updated in sync with Base.

And this is typically very annoying and time-consuming.

**Comment by KristofferC** [comment]
I didn't manage to get to the triage call in time for this, but if the discussion was only between keeping the Pkg3 repo separate and using `subtree` to sync changes vs using `git-external` then my suggestion here is just to move Pkg3 to a stdlib and delete the old Pkg3 repo. Just like any other stdlib we currently have.

**Comment by JeffBezanson** [comment]
If Compat is out of the picture, then I'm much more ok with using git subtrees. I also wouldn't object to entirely moving the Pkg3 code here.

**Comment by KristofferC** [comment]
Yes, Compat is out of the picture.

Great, I can update this PR now with https://github.com/JuliaLang/julia/pull/25956 and https://github.com/JuliaLang/julia/pull/25953 in the picture.

**Comment by StefanKarpinski** [comment]
I'll close this then since @KristofferC's PRs supersede it.

**Comment by KristofferC** [comment]
I was going to update this one but can make a new one.

**Comment by StefanKarpinski** [comment]
Eh, just make a new one. There's too much junk in here.

**Comment by vtjnash** [comment]
> Why should Pkg3 be the only one getting punished!?

Being frozen in stdlib is a punishment, being free to develop separately should be a _positive_.

> Develop stdlib packages together with Base, upstream the changes when they're ready.

Regardless of where this code lives, I think we should encourage development to happen upstream, with separate release cycles, issue tracker, etc., then just import the stable releases here.

**Pull request closed without merging**
