### PR TITLE
Set VERSION to 1.7.0-DEV, move 1.6 NEWS to HISTORY

### PR DESCRIPTION
**Pull request by KristofferC**
Whenever this is merged, the commit just before it will be the commit the 1.6 release branch is made from.

### CODE REVIEW

**Comment by timholy** [comment]
Has there been a feature-freeze announcement on Discourse? I couldn't find one.

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/1-6-soft-feature-freeze-nov-8th/49379

**Comment by Keno** [comment]
Master is currently broken - we need to hold off.

**Comment by ViralBShah** [comment]
For anyone watching, the breakage was fixed before merging.

**Comment by Keno** [comment]
Well, we reverted the problematic commit, which unblocked master at least ;)

**Pull request merged**
