### PR TITLE
make extension not load twice on workers

### LINKED ISSUE #49437: Julia hanging with extensions + Distributed on latest backports-release-1.9
Sorry if I'm jumping the gun but haven't seen it mentioned and no one on Slack seemed to know about this, but a consequence of https://github.com/JuliaLang/julia/pull/49257 (slated to be included in 1.9.0-rc3) appears to be that Julia hangs when loading extension modules in sessions with multiple processes. I have a tiny MWE repo which reproduces this:

```bash
gh repo clone marius311/julia19_distributed_extension_hang_mwe
cd julia19_distributed_extension_hang_mwe
julia +1.9.0-rc2 mwe.jl # ok
julia +1.9.0-rc1 mwe.jl # hangs
julia +dev mwe.jl # hangs, where dev == after this PR
```

The code is just two dummy modules, one with an extension for the other, and code:
```julia
using Distributed
addprocs(2)
using Foo, Bar
```

Not sure the solution since https://github.com/JuliaLang/julia/pull/49257 *is* important for fixing https://github.com/JuliaLang/julia/issues/49250 (which I had also run into hence why I was running backports-release-1.9 when I noticed this)

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/49437

The issue is the following:

- Distributed wants to load packages on workers when someone loads a package on the master.
- Therefore it inserts a package callback to load the package whenever the master loads a package.
- Upon all the triggers for a package getting loaded on the master, this causes two copies of the extension to try to get loaded:
  - One from the callback (fired from the master)
  - And one due to all the triggers being loaded on the worker.

An alternative to this PR could be to never trigger the extension loading on workers and always let the callback handle it but I don't know how to identify a worker (`myid`) in Base.

### CODE REVIEW

**Comment by KristofferC** [comment]
The alternative would look something like

```diff
 function run_extension_callbacks(pkgid::PkgId)
+    distributed_id = PkgId(UUID((0x8ba89e20_285c_5b6f, 0x9357_94700520ee1b)), "
Distributed")
+    Distributed = get(loaded_modules, distributed_id, nothing)
+    if Distributed !== nothing && isdefined(Distributed, :myid)
+        id = @invokelatest Distributed.myid()
+        # Do not trigger extensions to load on workers, they will be loaded by 
the
+        # callback Distributed inserts
+        id != 1 && return
+    end
```

**Comment by marius311** [comment]
Thanks for this quick fix. The solution in the PR seems right to me because at least based on your description / my basic understanding (ie I havent actually tested), it will handle this correctly:

```julia
using Foo, Distributed
addprocs(2)
using Bar
```

which, based on current rules, should load Foo, Bar, and FooBarExt on master, and only Bar on workers. Conversely, letting master trigger the worker-loads I don't know if it could really handle that easily.

**Review by vtjnash — COMMENTED** [review]
Shouldn't `Base.toplevel_load[]` be false already, since the extension is not the toplevel load?

**Comment by KristofferC** [comment]
> Shouldn't Base.toplevel_load[] be false already, since the extension is not the toplevel load?

I don't know the exact definition of that but  adding

```julia
        @show Base.toplevel_load[]
        @show mod
```

to

https://github.com/JuliaLang/julia/blob/f84fb5b26f87169c00e4bdc3c4db050772974023/stdlib/Distributed/src/Distributed.jl#L74-L85

shows:

```
Base.toplevel_load[] = true
mod = BarFooExt [4863ffa8-0e90-52b0-a292-a281b01911ec]
```

**Comment by KristofferC** [comment]
I think an extension loading like this is arguably a top level load, no? It doesn't get loaded into any other package. The "extension callback" here gets run after we have loaded all the triggers and at that point we are at toplevel again calling `require_prelocked´.

**Comment by KristofferC** [comment]
I'll go with this for now, if someone has a cleaner solution it can always be tweaked.

**Pull request merged**
