### PR TITLE
Rename indmin and indmax to argmin and argmax

### PR DESCRIPTION
**Pull request by nalimilan**
`argmin` and `argmax` match the mathematical names as well as those used by Numpy. On the contrary, there does not appear to be any precedent for `indmin` and `indmax`, and they do not follow any pattern in Julia either.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by kmsquire** [comment]
I proposed this a long time ago (and it was shit down at the time—on a phone, so it’s hard to find the discussion). Very much approve!

**Comment by kmsquire** [comment]
I proposed this a long time ago (and it was shot down at the time—on a phone, so it’s gard to find a link to the discussion). Very much approve!

**Comment by kmsquire** [comment]
(Argh... I need to respond on a real keyboard!)

**Comment by JeffBezanson** [comment]
@StefanKarpinski any opinion? I think we should do this.

**Pull request merged**
