### PR TITLE
RFC: inference: add allocation cache for common Const objects

### PR DESCRIPTION
**Pull request by vtjnash**
performance experiment: Does maintaining an allocation cache of `Const` objects we guess to be very common make inference faster?

### CODE REVIEW

**Comment by JeffBezanson** [comment]
So, does it help? :-)

**Comment by StefanKarpinski** [comment]
Nanosoldier doesn't seem to have been run on this so ???

**Comment by oscardssmith** [comment]
Is there a way we could get `nanosoldier` to report compilation time?

**Comment by vtjnash** [comment]
It seems to reduce memory usage, but not affect performance much

**Pull request closed without merging**
