### PR TITLE
Subtype: some performance tuning.

### LINKED ISSUE #55807: Dispatch performance regression
I think I found a regression with compiling methods with increasing type information (cc @gbaraldi). Here is a reproducer:

```julia
Base.@kwdef struct Nested{A,B}
    num::Int = 1
end
nest_val(na, nb, ::Val{1}) = Nested{na, nb}()
nest_val(na, nb, ::Val{n}) where {n} = nest_val(Nested{na, nb}, Nested{na, nb}, Val(n-1))
nest_val(na, nb, n::Int) = nest_val(na, nb, Val(n))
nest_val(n) = nest_val(1, 1, n)
foo(t::Nested) = 1
for i in 1:4:25
    let i=i
        NV = nest_val(i)
        @time begin
            foo(NV)
        end
    end
end
```

##### Julia 1.8 🚀
```julia
  0.000002 seconds
  0.000057 seconds (355 allocations: 24.688 KiB, 76.66% compilation time)
  0.000055 seconds (355 allocations: 24.688 KiB, 77.15% compilation time)
  0.000060 seconds (355 allocations: 24.688 KiB, 76.81% compilation time)
  0.000061 seconds (355 allocations: 24.688 KiB, 76.18% compilation time)
  0.000121 seconds (355 allocations: 24.688 KiB, 86.99% compilation time)
  0.000063 seconds (355 allocations: 24.688 KiB, 74.36% compilation time)
```

##### Julia 1.9 🐢
```julia
  0.000002 seconds
  0.000087 seconds (323 allocations: 23.266 KiB, 86.27% compilation time)
  0.000102 seconds (323 allocations: 23.266 KiB, 83.09% compilation time)
  0.000180 seconds (323 allocations: 23.266 KiB, 41.63% compilation time)
  0.001830 seconds (323 allocations: 23.266 KiB, 10.49% compilation time)
  0.024255 seconds (323 allocations: 23.266 KiB, 0.37% compilation time)
  0.391652 seconds (323 allocations: 23.266 KiB, 0.02% compilation time)
```

##### Julia 1.10 🐢
```julia
  0.000002 seconds
  0.000106 seconds (312 allocations: 23.031 KiB, 71.90% compilation time)
  0.000112 seconds (312 allocations: 23.031 KiB, 80.39% compilation time)
  0.000233 seconds (312 allocations: 23.031 KiB, 57.58% compilation time)
  0.001319 seconds (312 allocations: 23.031 KiB, 4.36% compilation time)
  0.019645 seconds (313 allocations: 23.125 KiB, 0.24% compilation time)
  0.318507 seconds (312 allocations: 23.031 KiB, 0.03% compilation time)
```

##### Julia 1.11.0-rc3 🐢
```julia
  0.000004 seconds
  0.000043 seconds (105 allocations: 4.828 KiB, 56.51% compilation time)
  0.000043 seconds (105 allocations: 4.828 KiB, 50.47% compilation time)
  0.000125 seconds (105 allocations: 4.828 KiB, 18.22% compilation time)
  0.001327 seconds (105 allocations: 4.828 KiB, 1.66% compilation time)
  0.022224 seconds (106 allocations: 4.922 KiB, 0.12% compilation time)
  0.343260 seconds (105 allocations: 4.828 KiB, 0.01% compilation time)
```

### PR DESCRIPTION
**Pull request by N5N3**
The main motivation of this PR is to fix #55807.
dc689fe8700f70f4a4e2dbaaf270f26b87e79e04 tries to remove the slow `may_contain_union_decision` check by re-organizing the code path. Now the fast path has been removed and most of its optimization has been integrated into the preserved slow path.
Since the slow path stores all inner ∃ decisions on the outer most R stack, there might be overflow risk. aee69a41441b4306ba3ee5e845bc96cb45d9b327 should fix that concern.

The reported MWE now becomes
```julia
  0.000002 seconds
  0.000040 seconds (105 allocations: 4.828 KiB, 52.00% compilation time)
  0.000023 seconds (105 allocations: 4.828 KiB, 49.36% compilation time)
  0.000026 seconds (105 allocations: 4.828 KiB, 50.38% compilation time)
  0.000027 seconds (105 allocations: 4.828 KiB, 54.95% compilation time)
  0.000019 seconds (106 allocations: 4.922 KiB, 49.73% compilation time)
  0.000024 seconds (105 allocations: 4.828 KiB, 52.24% compilation time)
```

Local bench also shows that 72855cd slightly accelerates `OmniPackage.jl`'s loading
```julia
julia> @time using OmniPackage
# v1.11rc4
 20.525278 seconds (25.36 M allocations: 1.606 GiB, 8.48% gc time, 12.89% compilation time: 77% of which was recompilation)
# v1.11rc4+aee69a4+72855cd 
 19.527871 seconds (24.92 M allocations: 1.593 GiB, 8.88% gc time, 15.13% compilation time: 82% of which was recompilation)
```

### CODE REVIEW

**Comment by N5N3** [comment]
@nanosoldier `runtests()`

**Comment by N5N3** [comment]
@nanosoldier `runtests(["LinearRationalExpectations", "EarlyStopping", "QuantumAlgebra", "QuantumPropagators", "Permanents", "FindMinimaxPolynomial", "CTFlows", "OptimalBids", "SliceSampling", "FSimBase", "DiffEqFinancial", "PlantBiophysics", "MLJTestIntegration", "CellularPotts", "CirculatorySystemModels", "IterativeLearningControl"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56007#issuecomment-2395775490) has completed - no new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/dc689fe_vs_0c8c20c/report.html) is available.

**Comment by charleskawczynski** [comment]
Out of curiosity, @N5N3, could you please try out https://github.com/JuliaLang/julia/issues/55952#issue-2559085520, too?

**Comment by KristofferC** [comment]
@charleskawczynski, you can get the built Julia from this PR from buildkite to easily test it yourself, for example:

image

**Comment by N5N3** [comment]
@charleskawczynski I tried it, but the error print is still quite slow.

**Comment by charleskawczynski** [comment]
> @charleskawczynski, you can get the built Julia from this PR from buildkite to easily test it yourself, for example: ...

Ah, cool! I just tried downloading it but I'm getting

Screenshot 2024-10-08 at 11 03 55 AM

when I try to run `julia-dc689fe870/bin/julia`. Am I supposed to run it some other way?

**Review by vtjnash — APPROVED** [review]

**Comment by charleskawczynski** [comment]
If I try to run it from terminal, I get
```
/Users/charliek/Downloads/julia-dc689fe870Build/bin/julia 
dyld[65179]: Library not loaded: @rpath/libjulia.1.12.dylib
  Referenced from: <C0E46333-5FAF-3210-A327-5E41CB0C8AFE> /Users/charliek/Downloads/julia-dc689fe870Build/bin/julia
  Reason: tried: '/Users/charliek/Downloads/julia-dc689fe870Build/lib/libjulia.1.12.dylib' (code signature in <845EDEB7-45DE-332E-B6A8-5C21830FD847> '/Users/charliek/Downloads/julia-dc689fe870Build/lib/libjulia.1.12.0.dylib' not valid for use in process: library load disallowed by system policy), '/Users/charliek/Downloads/julia-dc689fe870Build/lib/libjulia.1.12.dylib' (code signature in <845EDEB7-45DE-332E-B6A8-5C21830FD847> '/Users/charliek/Downloads/julia-dc689fe870Build/lib/libjulia.1.12.0.dylib' not valid for use in process: library load disallowed by system policy), '/usr/local/lib/libjulia.1.12.dylib' (no such file), '/usr/lib/libjulia.1.12.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Pull request merged**
