### PR TITLE
replace push! + sort! with searchsortedfirst + insert! in optimizer

### PR DESCRIPTION
**Pull request by LilithHafner**
Implements the suggestion in a TODO dating back to #34306

This is motivated by my belief that almost all uses of `sort` can be replaced with more performant alternatives.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Review by aviatesk — APPROVED** [review]
Looks good to me. Let's see the compiler performance benchmark.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46512#issuecomment-1229660587) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/80a6aae_vs_5316549/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46512#issuecomment-1230087251) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4e5179e_vs_10961d1/report.md).

**Comment by oscardssmith** [comment]
Wouldn't it be more efficient to do a linear scan from the back that moves items at the same time? It would touch strictly fewer memory addresses (at the cost of more comparisons).

**Comment by LilithHafner** [comment]
Probably. A heap could be even better depending on the read access pattern of the array, but I'll try a linear scan first.

**Comment by LilithHafner** [comment]
Does this code get compiled with the standard optimizing compiler? (e.g. do I need those `@inbounds` annotations and explicit storage of `j` or can the compiler infer them as I think it would normally)

**Comment by LilithHafner** [comment]
@nanosoldier runbenchmarks("inference", vs=":master")

**Comment by oscardssmith** [comment]
Yeah, this does get compiled normally.

**Comment by LilithHafner** [comment]
It turns out that the compiler couldn't infer the `@inbounds` annotations, oh well.

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46512#issuecomment-1230862529) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/94309e6_vs_ccf04c2/report.md).

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks(["inference", "optimization", "sin(42)"], vs=":master")`

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("inference" && "optimization", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46512#issuecomment-1234928048) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/3bdbc9f_vs_31e4e26/report.md).

**Pull request closed without merging**
