### PR TITLE
Help for professional programmers

### PR DESCRIPTION
**Pull request by robbyriverside**
I just started learning Julia a month ago and the getting started documentation is really just an overview of some basic elements.  It needs to answer the question: how do I structure my code for using projects.  The JuliaCon 2016 talk on programmers vs scientists touches on this.  I agree that Julia's tools are extensive.  But the getting started docs needs to offer initial guidance for programmers on how to develop projects right away.   Even just a "here's how I do it" would be extremely helpful.  The reference I gave is almost too short.  But even that is very valuable.

### CODE REVIEW

**Comment by timholy** [comment]
Why is this relevant only for people who receive a paycheck to write code, but not for people who are paid to do something else and happen to write code for free? :smile: 

More specifically, that blog post is great but its main focus is customizing your startup.jl so that you automatically start from a directory-specific Project file. (You could also achieve that by aliasing `julia` to always use `--project=@.`.) That's different from an overview of project management itself, which is covered more directly in https://docs.julialang.org/en/v1/stdlib/Pkg/. I agree that it's relevant to give what is essentially a "shout out" to these issues, but it might be best to say something like

> Julia comes with a sophisticated package manager and the ability to set up project-specific environments; for an introduction to these topics, see https://docs.julialang.org/en/v1/stdlib/Pkg/.

**Comment by robbyriverside** [comment]
The Pkg documentation is fine, if you already know how.  If you’ve already used python anaconda, for example.  

Take the Go documentation for contrast.  The very first thing it tells you is how to organize compile and run your code.

We can drop the word professional, but when a programmer (vs a scientist) organizes code it is intended to be a reusable component, always.
A scientist is just running experiments, seeking an answer.  A programmer wants what they write to be reusable from the start, so everything is a package.
Scripting is simple and if that’s all you care about it works fine.  

As for the blog post, when I started I did not realize that —project argument and activate did the same thing.  It’s not that the docs don’t say that somewhere, but when you are starting out it is not obvious that those two things are related.
When you are starting out, trying to write reusable code, it’s not clear how to do that.  The docs provide a whole bunch of functionality, but after you read it, you ask yourself, "okay, but how do I use this?"

I am simply stating my own frustration with starting to use Julia.  It does mirror the sentiments in the JuliaCon 2016 presentation on programmers vs scientists.  

Finally, I don’t agree that the post is about using startup.jl.  It is about using environments in a practical way.  I could not find any practical advise or approach in the docs.  Especially, getting started.

**Comment by KristofferC** [comment]
> A scientist is just running experiments, seeking an answer.  A programmer wants what they write to be reusable from the start, so everything is a package.
Scripting is simple and if that’s all you care about it works fine.

FWIW, I'm not sure if this is a useful distinction to make. If anything, reproducibility ("reusable from start") is perhaps even more important in science when you try to make an observation about the world and not "just" have a service running.

**Comment by robbyriverside** [comment]
I was trying to spark a debate about what would be better documentation for getting started using packages, environments, and modules to create reusable code (public or private).  Alas, I can tell from your comments, that this approach did not work.  

IMO the Pkg docs are really like a reference.  It assumes you already know what to do with it.  If you come from Python, I'm sure it is easy to figure out.  

But I am coming from Go, where they show you how to create packages from start.  I gather that Ruby also has a specific code organization standard.  I am aware that some users will not care and are fine with just writing scripts that load other scripts and labeling them as scientists did not help.

The blog I referenced seems to get what I am talking about, albeit not really complete.  But I did not find that until weeks into the process of learning Julia and I just think it would have been better to find something like that on the first day.  So I will retract my attempt.

**Comment by fredrikekre** [comment]
This section https://docs.julialang.org/en/v1/manual/workflow-tips/ could be improved to include more such things maybe.

**Comment by timholy** [comment]
How about we leave behind the scientist-vs-professional issue? I don't think it's a useful distinction, but it's also not productive to argue about it. Let's just agree to leave that aspect out of the docs.

There's still the issue of usability to consider. I don't think you're wrong in thinking that there are reasons to mention project management in the "getting started page" (there are many things worth mentioning, and a desire for reasonable brevity will force us to pick and choose, but this topic seems worthy to me). Could our docs use clarification, examples, howtos? Yes!

I'd still say that the issue of modifying your `startup.jl` is too far into the weeds for the "getting started" page. I think we'd be fine if you took the parts that you liked about it and contribute a focused version of it as a PR here.

**Comment by robbyriverside** [comment]
IF anything, Julia is the place where programmers become scientists and the other way around.  So I agree the distinction is of little value.  I’d like to but Differentiable Programmer on my resume! 🙂

The workflow tips may be just the thing, I like the three approaches.  But I would prefer a page for each and perhaps a step by step with some philosophy and full examples.

You also may want to reference workflow tips in the getting started page, for someone like myself who wants to start with that.

**Comment by StefanKarpinski** [comment]
I'll leave this open nannd

**Comment by StefanKarpinski** [comment]
While I don't think this particular change is what we need, it would be great if people (like you) coming at things with a fresh mind could help push the getting started pages where they need to be. That is very much appreciated! If you have any other improvements in mind, please don't hold back from opening issues to discuss.

**Comment by robbyriverside** [comment]
I’m in a startup, so time is precious.  But Julia is my new love, so you never know.

**Pull request closed without merging**
