### PR TITLE
ignore this

### PR DESCRIPTION
**Pull request by vtjnash**
doing an appveyor test on this commit

### CODE REVIEW

**Comment by tkelman** [comment]
another way to do this is add your branch name to the `branches: only:` whitelist btw, don't absolutely have to make a pr

**Comment by yuyichao** [comment]
> another way to do this is add your branch name to the branches: only: whitelist btw, don't absolutely have to make a pr

On master or on the branch?

**Comment by tkelman** [comment]
On the branch, no need to touch master for test runs

**Comment by yuyichao** [comment]
Makes sense. Thanks.

**Pull request closed without merging**
