### PR TITLE
Fix #19129, type inference for Mmap.mmap

### LINKED ISSUE #19129: Return type of Mmap.mmap is not inferred
```julia
julia> Base.return_types(Mmap.mmap, Tuple{IOStream, Type{Vector{Int8}}, Int})
1-element Array{Any,1}:                                                                                                   
 Any
```

### PR DESCRIPTION
**Pull request by simonster**
Unfortunately `mmaplen` and `ptr` still get boxed inside the function due to the finalizer closure (#15276) but at least the return type can now be inferred.

### CODE REVIEW

**Comment by simonster** [comment]
The AppVeyor failure seems to be because `@inferred` leaks its result so it never gets gc'ed, and on Windows that stops us from opening the file. I've wrapped `@inferred` in a let block. Hopefully this fixes things and also doesn't make the tests too much longer to run.

**Comment by simonster** [comment]
AFAICT, the `@inferred` change didn't adversely affect test runtimes and fixed AppVeyor, so as soon as the OS X tests are done and someone gives this a :+1:, it should be good to merge.

**Comment by quinnj** [comment]
Looks good by me.

**Comment by quinnj** [comment]
Though I'm not sure we need to backport this for 0.4 since I don't think it actually solves it there
```julia
julia> @code_warntype ntuple(x->0, Val{10})
Variables:
  f::F
  #s13::Type{Val{10}}

Body:
  begin  # tuple.jl, line 48:
      return (Base.tuple)((f::F)(1)::Any,(f::F)(2)::Any,(f::F)(3)::Any,(f::F)(4)::Any,(f::F)(5)::Any,(f::F)((Base.box)(Int64,(Base.sub_int)(10,4)))::Any,(f::F)((Base.box)(Int64,(Base.sub_int)(10,3)))::Any,(f::F)((Base.box)(Int64,(Base.sub_int)(10,2)))::Any,(f::F)((Base.box)(Int64,(Base.sub_int)(10,1)))::Any,(f::F)(10)::Any)::Tuple{Any,Any,Any,Any,Any,Any,Any,Vararg{Any}}
  end::Tuple{Any,Any,Any,Any,Any,Any,Any,Vararg{Any}}

```

**Comment by simonster** [comment]
In 0.4 the `ntuple` call may need the type annotation `::NTuple{N,Int}`.

**Pull request merged**
