### PR TITLE
[release-0.5] Backport of #21069

### PR DESCRIPTION
**Pull request by martinholters**

### CODE REVIEW

**Comment by tkelman** [comment]
cherry-pick with -x please

**Comment by martinholters** [comment]
Like so?

**Comment by tkelman** [comment]
yep. I'll want to run things through pkgeval before merging them to the release branch.

**Comment by martinholters** [comment]
Sure, no hurries from my side.

**Comment by tkelman** [comment]
noting that this was reverted in #21684 since it may have caused performance regressions, if there will be a 0.5.3 it may be worth testing that again

**Pull request merged**
