### PR TITLE
Move emacs-mode.el to its own repo.

### LINKED ISSUE #15694: move emacs julia-mode into its own repository

### PR DESCRIPTION
**Pull request by yuyichao**
Close #15694

Moved to https://github.com/JuliaLang/julia-emacs with full history.

I add `[ci skip]` since there's nothing to test...

### CODE REVIEW

**Comment by yuyichao** [comment]
The new repo is ready. The only question I can think of right now is that should I move over all the julia-mode issues? There's 13 of them open right now.

**Comment by StefanKarpinski** [comment]
Yes, I think that's a good idea – part of my motivation for this was to move the discussion of emacs-specific issues to a more focused place. I would just open issues with the same subject and link back to the original issue's discussion and maybe include a very brief summary in the issue body.

**Comment by yuyichao** [comment]
OK, I'll do that soon.

**Comment by tkelman** [comment]
Nice work preserving the history across the move. Was that some subtree magic?

**Comment by yuyichao** [comment]
I use filter tree to delete everything else and rebase out the merge commits. Not sure if this is the best way though.

**Comment by StefanKarpinski** [comment]
I think that's the best way to do it. Thanks for that, @yuyichao!

**Pull request merged**
