### PR TITLE
Fix bug in backsolve of sparse hermitian matrices

### PR DESCRIPTION
**Pull request by ranjanan**
~~Will add~~ Added a benchmark to BaseBenchmarks too.

cc: @andreasnoack

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Are there any computational tests that would distinguish the Hermitian branch from LU?

**Comment by andreasnoack** [comment]
> Are there any computational tests that would distinguish the Hermitian branch from LU?

In theory, it might be possible because the LU branch is a bit more numerically stable but I think the benchmark route is more reliable. Let's try to run the sparse benchmarks when https://github.com/JuliaCI/BaseBenchmarks.jl/pull/68 has been merged.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")` since I forget how to ask for just sparse benchmarks

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21165#issuecomment-290491881) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4693aa3e261eca92ad1eeb302cfbf8590eb1ff82/fcd3a2a_vs_2da9afc/report.md). cc @jrevels

**Pull request merged**
