### PR TITLE
Statistics

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by andreasnoack** [comment]
It looks like the doc tests are failing or at least needs to be adjusted a bit.

**Comment by ViralBShah** [comment]
Should we rename the functions to remove the things with `m` suffixes (maybe in a separate PR) and really consider not using up 3 letter names for `std` and `var`?

**Comment by vchuravy** [comment]
No `std` and `var` are fine and this in the Statistics namespace. I am in favour of merging this quickly.

**Review by vchuravy — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Agree, now that this is all in a package in a place where people can still get at it easily, we have the ability to improve and evolve this API outside of Base without everyone being up in arms about it.

**Comment by mbauman** [comment]
What's the plan with regards to `StatsBase`?

**Comment by quinnj** [comment]
We can selectively move stuff from StatsBase.jl to here; it will be a good cleanup/fine-tuning of functionality there anyway.

**Comment by simonbyrne** [comment]
I've rebased.

**Pull request merged**
