### PR TITLE
Deprecate similar(f, …) in favor of just dispatching directly on f(…)

### LINKED ISSUE #26433: Making space for a swankier similar
A major task I'd love to accomplish in 1.x is a redesign of `similar`.  This has been discussed in oh-so-many issues (primarily #18161, but also #25107), and I don't want to rehash those discussions all that much.  The `similar` function currently has lots of methods on it, with three "chains" of fallbacks:

```julia
┌similar(::AbstractArray)
├similar(::AbstractArray, ::Union{Integer,AbstractUnitRange}...)
├similar(::AbstractArray, ::Tuple)
├similar(::AbstractArray, ::Type, ::Union{Integer,AbstractUnitRange}...)
╘similar(::Array, ::Type, ::Tuple) = Array(…)
┌similar(::Type{T}, ::Union{Integer,AbstractUnitRange}...)
╘similar(::Type{T}, ::Tuple) = T(…)
┌similar(f, ::Union{Integer,AbstractUnitRange}...)
╘similar(f, ::Tuple) = f(…)
```

(Where `::Array` is a stand-in for any object that `similar` supports).

I'd like to bifurcate this into a value-domain and a type-domain, wherein the type-domain methods become the canonical endpoints.  In order to make space for that, though, I believe we'll need to deprecate the second two pairs of chains.  Those guys are there to support offset arrays.  I believe `similar(f, …)` can be deprecated in favor of just putting methods on `f`.  `similar(Type{<:Array}, ...)` is messier, though, since it feels wrong to have `Array(undef, 2:3, 2:3)` return something that's not an `Array`.

### PR DESCRIPTION
**Pull request by mbauman**
Fixes #26433.

Previously, OffsetArrays used `similar(dims->zeros(dims), axes)` to add offset support for the base functions that created arrays: `zeros`, `ones`, `trues`, `falses`, and `fill`.  It was a bit of a strange construct — the function specified the "internal" array around which `OffsetArray`s would wrap.  This deprecates that similar method in favor just structuring the method tables of those five functions in a manner that is conducive for overloading with offset axis argument(s).  Paired with https://github.com/JuliaArrays/OffsetArrays.jl/pull/43 to match the changes in test/TestHelpers.jl.

### CODE REVIEW

**Comment by mbauman** [comment]
Just a note that I first attempted to coalesce all these functions around an `AbstractArray{T}(dims_or_axes…)` constructor.  I still think that may be a good idea, but it was turning into a rabbit hole and is a new feature so I decided to punt on it until later.  I left that first commit here that does so — it can be squashed out on merge but I think it's nice to leave here in the GitHub PR as a starting point if we ever decide to implement that feature.

The biggest reason not to couple it with this change was simply that it became quite disruptive — it meant that `fill(true, dims)` returned a `BitArray`.  That led me down quite a rabbit hole trying to figure out how we could come up with a consistent rule for returning arrays or bitarrays… and it's not something that I particularly wanted to tackle so close to a release.

**Comment by mbauman** [comment]
I've added NEWS and deprecations for the newly-tighter ones and zeros methods… but now I'm running into a test failure I don't quite understand:

```julia
f5575() = zeros(Type[Float64][1], 1)
@test Base.return_types(f5575, ())[1] == Vector
```

With these additional deprecations, I'm now getting `Any` from `return_types`.  I'm not entirely sure what that test is meant to be testing… as it appears we again have "too many methods" (#5575)?  It's a little odd, as `(::Type, ::Integer)` is still only selecting one method:

```julia
julia> methods(zeros, Tuple{Type, Int})
# 1 method for generic function "zeros":
[1] zeros(::Type{T}, dims::Union{Integer, AbstractUnitRange}...) where T in Base at array.jl:401
```

So I'm not sure what to do with that...

**Comment by vtjnash** [comment]
The zeros function (currently) recurses aggressively. The test is there to make sure the compile stops trying to follow the possible branches in a reasonable time, without losing accuracy.

**Comment by mbauman** [comment]
Thanks.  So the fact that I broke this test by adding these deprecations is expected?  Should I just copy the previous zeros method tree (without deprecations) onto a new function whose sole purpose is to live in `test`?

**Pull request merged**
