### PR TITLE
clarify Base.isidentifier docs (false for operator symbols)

### LINKED ISSUE #42076: [parsing] is "++" an identifier or not ?
are "++", ".." valid identifiers or not ?

FOR "++"
```julia
using Test

# pass @ v1.6
@test Base.isidentifier("++") == false  # it should not be
@test (++ = 1) == 1                     # but it can be assigned,
@test let ++ = 1 ; 2 * ++ end == 2      # be doubled,
@test let ++ = 1 ; 1 + ++ end == 2      # be incremented at right,

# do not pass @ v1.6
@test let ++ = 1 ; ++ + 1 end == 2      # but not be incremented at left # will syntaxically throws
```

FOR ".."

```julia
@test Base.isidentifier("..") == false  # it should not be
@test (.. = 1) == 1                     # but it can be assigned,
@test let .. = 1 ; 2 * .. end == 2      # be doubled,
@test let .. = 1 ; 1 + .. end == 2      # be incremented at right,


# do not pass @ v1.6
@test let .. = 1 ; .. + 1 end == 2      # but not be incremented at left # will syntaxically throws
```

BTW, "--" seems to throws on assign coherently with

```julia
@test Base.isidentifier("--") == false
```

Edited: add the ".." case

### PR DESCRIPTION
**Pull request by stevengj**
Closes #42076.

### CODE REVIEW

**Comment by mcabbott** [comment]
Maybe this should say "See also `Base.isoperator`"?

**Comment by stevengj** [comment]
Added some "see also" lines.  Note that this is exported by the `Meta` package, so we can refer to that rather than `Base`.

**Comment by o314** [comment]
Thanks,

Considering the boundary and similarity between id and op, I remain a bit puzzled by some changes at https://github.com/JuliaLang/julia/blob/v1.6.2/test/syntax.jl#L1945 introduced by https://github.com/JuliaLang/julia/pull/33158/

```julia
@test Meta.parse("import Base.Foo.:(==).bar") == :(import Base.Foo.==.bar)
```
IMHO operator should be atomical eg. do not be able to handle a getfield request

May also concern https://github.com/JuliaLang/julia/pull/37583 afterwards isoperator may accept more than symbol

**Comment by stevengj** [comment]
Hmm, cross-referencing to `Meta` doesn't work with the docsystem. 😢

**Comment by mcabbott** [comment]
Sorry about the hassle. I'm a bit confused which module this is in. It seems to have a doc entry at https://docs.julialang.org/en/v1/base/base/#Base.isoperator, and:
```
julia> @which Base.isoperator
Base

julia> @which Base.isoperator(:+)
isoperator(s::Union{AbstractString, Symbol}) in Base at show.jl:1358

help?> Base.isoperator
  isoperator(s::Symbol)

  Return true if the symbol can be used as an operator, false otherwise.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> Meta.isoperator(:+), Meta.isoperator(:f)
  (true, false)
```

**Pull request merged**
