### PR TITLE
make `Core.ifelse` just a function that does a ternary

### PR DESCRIPTION
**Pull request by oscardssmith**
LLVM is already allowed to turn `ifelse` into a terinary,  or to tern a terinary into a `cmov` instruction so the only effect of this is to remove a lot of special cases from the compiler. This also lets us constant fold on constant conditions earlier in the compiler which can lead to passing less code through the compiler. For example
 ```
 f(x) = ifelse(false, exp(x), x)
 @code_typed f(1.1)
 # before 
CodeInfo(
1 ─ %1 = invoke Main.exp(x::Float64)::Float64
│   %2 = Core.ifelse(false, %1, x)::Float64
└──      return %2
) => Float6
 # after
CodeInfo(
1 ─     goto #3
2 ─     nothing::Nothing
3 ┄     goto #4
4 ─     return x
) => Float64
```

Note that this was suggested by @vtjnash.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
good riddence

**Comment by gbaraldi** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by brenhinkeller** [comment]
Hmm, so I thought the whole point of `ifelse` was that both sides get evaluated so it doesn't introduce a branch / speculative execution. Is that not true, or is there another way of achieving that goal?

**Comment by brenhinkeller** [comment]
cc @chriselrod

**Comment by oscardssmith** [comment]
This still evaluates both sides since it is a function. The key realization is that LLVM already can choose whether or not `ifelse` has a branch or not, and we have have better analysis at the IR level for `if`/`else`.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51007#issuecomment-1688688557) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/1c1daf1_vs_3c18223/report.md).

**Comment by fingolfin** [comment]
Ah, the sweet feeling when removing an "optimization" to get simpler, shorter *and* faster code. Wonderful 😄

**Comment by oscardssmith** [comment]
yes, but right now, both ifelse and a terinary really on llvm to make the choice

**Comment by chriselrod** [comment]
See here: https://mhdm.dev/posts/sb_lower_bound/
They need to pass `-mllvm -x86-cmov-converter=false`.
I didn't try this in Julia. Maybe we would need the same thing, as it looks like this is blocking llvm from converting cmov into a branch in the x86 backend. 
So I guess my point above isn't relevant to this PR, and only to the vague idea of "it'd be nice if we could get conditionals without bending over backwards".

**Comment by chriselrod** [comment]
> yes, but right now, both ifelse and a terinary really on llvm to make the choice

Yeah, it would be nice if we can control or at least strongly hint what it should do, because it isn't great at picking the right thing, and we can't expect julia users to start their REPLs with flags like that.

**Comment by Keno** [comment]
As I said on slack, I'm inclined to NAK this for the time being until we can properly assess the impact of the CFG growth of this implementations for downstream code that has tens of thousands of `ifelse`'s per function.

**Comment by vchuravy** [comment]
From a GPU perspective we would also need to do some testing to ensure that this gets optimized/lowered correctly.

**Pull request closed without merging**
