### PR TITLE
Replace regex package module checks with actual code checks

### LINKED ISSUE #55792: Multiline comment parsing error on 1.11-rc3
When loaded via `using` from a directory on LOAD_PATH, the following code
works on Julia 1.10.5, but fails on 1.11-rc3 as well on nightly (02549d5c54e):
```julia
#=
Demonstrate a parsing error when 
using multiline comments on Julia 1.11-rc3
^^^^^
   This `using` word makes 1.11-rc3 believe that 
there is a `using` statement before the module
declaration when the code is loaded from a directory
on LOAD_PATH
=#
module UsingError
main()=println("Hi there!")
end
```

This is the error message:

```
julia> using UsingError
[ Info: Precompiling UsingError [top-level]
ERROR: LoadError: Package UsingError [top-level] source file /home/fuhrmann/Wias/work/julia/dev/VoronoiFVM/examples/UsingError.jl has a using/import before a module declaration.
Stacktrace:
[1] check_src_module_wrap(pkg::Base.PkgId, srcpath::String)
@ Base ./loading.jl:2718
[2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
@ Base ./loading.jl:2733
[3] top-level scope
@ stdin:4
in expression starting at stdin:4
ERROR: Failed to precompile UsingError [top-level] to "/home/fuhrmann/.julia/compiled/v1.11/jl_RH516U".
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool; flags::Cmd, cacheflags::Base.CacheFlags, reasons::Dict{…})
@ Base ./loading.jl:3036
[3] (::Base.var"#1080#1081"{Base.PkgId})()
...
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/55792
Replaces https://github.com/JuliaLang/julia/pull/55822
Improves what https://github.com/JuliaLang/julia/pull/51635 was trying to do

```
ERROR: LoadError: `using/import Printf` outside of a Module detected. Importing a package outside of a module is not allowed during package precompilation.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:44
  [2] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2220
  [3] include
    @ ./Base.jl:582 [inlined]
  [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2822
  [5] top-level scope
    @ stdin:5
  [6] eval
    @ ./boot.jl:439 [inlined]
  [7] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:2675
  [8] include_string
    @ ./loading.jl:2685 [inlined]
  [9] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:327
 [10] _start()
    @ Base ./client.jl:558
in expression starting at /var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_zoGR1X/ImportBeforeMod.jl:1
in expression starting at stdin:5
```
cc. @barucden

### CODE REVIEW

**Comment by IanButterworth** [comment]
Perhaps the part of https://github.com/JuliaLang/julia/pull/51635 that this doesn't do is flag when a module is completely missing and the package has no imports.

**Review by JeffBezanson — APPROVED** [review]

**Comment by IanButterworth** [comment]
@JeffBezanson would you mind a second look. I added detecting a missing package module.

**Comment by giordano** [comment]
Should this PR include the tests added to #55822? Unless I'm missing it, I don't see a new test which actually catches the issue described in #55792.

**Comment by IanButterworth** [comment]
We could add that test but this is more correct by design. For a comment to be parsed as julia code and trigger an import would require quite a bigger breakage. 

Though, more tests is better. So I'll add it.

**Pull request merged**
