### PR TITLE
codegen: truncate Float16 vector ops also

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by giordano** [comment]
Is this meant to fix #45881?

**Comment by vchuravy** [comment]
Would be great to have tests in llvmpases for this!

**Comment by giordano** [comment]
Would also be cool to finish #40216 at the same time, otherwise this would turn into one of the worst bug fixes, I quite liked the bug 😂

**Comment by gbaraldi** [comment]
@vtjnash is it possible to make https://github.com/JuliaLang/julia/pull/43327 work without https://reviews.llvm.org/D120585. I think you mentioned it's possible to see the CPU features from inside the pass without a target machine.

**Comment by vtjnash** [comment]
Seems to have run into a rare test issue with #30415 (@ViralBShah)?
```
Error in testset SparseArrays/spqr:
Test Failed at /cache/build/default-amdci4-0/julialang/julia-master/julia-052c652e1c/share/julia/stdlib/v1.9/SparseArrays/test/spqr.jl:134
  Expression: rank(qr(S)) == 5
   Evaluated: 6 == 5
Error in testset SparseArrays/spqr:
Test Failed at /cache/build/default-amdci4-0/julialang/julia-master/julia-052c652e1c/share/julia/stdlib/v1.9/SparseArrays/test/spqr.jl:135
  Expression: rank(S) == 5
   Evaluated: 6 == 5
```

**Comment by ViralBShah** [comment]
I believe there are some fixes coming along on SparseArrays.jl soon.

**Pull request merged**
