### PR TITLE
use isnothing instead of `=== nothing`

### PR DESCRIPTION
**Pull request by mzaffalon**

### CODE REVIEW

**Review by KristofferC — CHANGES_REQUESTED** [review]
This is not a good idea. Using `!==` allows inference to do more checking, see https://docs.julialang.org/en/v1/manual/performance-tips/#Checking-for-equality-with-a-singleton-1.

**Comment by mzaffalon** [comment]
For my understanding: isn't this what [`isnothing(::Nothing) = true
`](https://github.com/JuliaLang/julia/blob/master/base/some.jl#L67) does?

**Comment by KristofferC** [comment]
> For my understanding: isn't this what isnothing(::Nothing) = true does?

No, it needs to be inline `===` (or `!==`).

**Comment by mzaffalon** [comment]
When would one use `isnothing`?

**Comment by KristofferC** [comment]
Can use it in something like `filter(!isnothing, x)`

**Pull request closed without merging**
