### PR TITLE
alloca & callconv fixes

### PR DESCRIPTION
**Pull request by vtjnash**
@Keno and @JeffBezanson for your awareness, see the commit description for all of the things that this modifies

(i couldn't get the Vector case working -- it corrupts the `functional` test if you are interested in trying to find the alignment bug yourself -- so i turned it back off)

### CODE REVIEW

**Comment by Keno** [comment]
This is fantastic. Great work, Jameson!

**Comment by vtjnash** [comment]
the win32 test was broken because llvm33 incorrectly orders a `WIN_ALLOCA` and a libcall (to `floor`) during the machine code instruction selection pass (conversion from IR). i'm just going to just turn off the emission of `_chkstk` on llvm33, since it doesn't work that well there anyways (fixed in llvm 3.6.1).

**Comment by vtjnash** [comment]
CI seems (mostly) happy now, so I'll merge this in the morning. then we can start to check whether it has successfully taken care of all of the invalid stack reads or if any still remain.

**Comment by JeffBezanson** [comment]
Looks like the ccall test failed on 32-bit travis?

**Comment by vtjnash** [comment]
fooey, i think i merged the wrong version of this branch

**Pull request merged**
