### PR TITLE
Minor `AbstractQ` audit

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes part of https://github.com/JuliaGPU/CUDA.jl/issues/1866, resolves https://github.com/JuliaLang/julia/pull/46196#issuecomment-1508630769. I removed some not exported functions that hadn't existed before #46196 anyway and added a few tests.

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks!

**Comment by dkarrasch** [comment]
Have you checked, does this fix the entire GPU package stack? Or will it be easier to merge this as is and then see what happens with nightly?

**Comment by dkarrasch** [comment]
Let's go with this and then fix issues as/if they arise.

**Comment by maleadt** [comment]
Sorry, didn't have time to test this over the weekend.
It fixes the immediate issue, but it looks like https://github.com/JuliaLang/julia/pull/46196 has broken other parts of CUDA.jl. For example, our tests were relying on `collect(::QRCompactWYQ)` to get an Array, but that doesn't seem to work anymore post #46196. I assume that's intended, as `collect` is documented to get an Array from anything iterable?

**Comment by dkarrasch** [comment]
I see. I've "fixed" quite a couple of packages with this usage. If you're fine with the result being a plain `Matrix`, then replace `collect` by `Matrix`, or replace `collect(Q)` by `Q*I` (i.e., the `UniformScaling` `I`). That might be able to return a `CuArray`, if that's what the corresponding `Q * true` does. I hope this is just a test pattern, not a productive code pattern.

I don't think I can develop CUDA.jl locally, so should I just fork the repo, start a PR and test with online CI until it's all green?

**Pull request merged**
