### PR TITLE
Deprecate ntuple(n::Integer, f::Function)

### PR DESCRIPTION
**Pull request by quinnj**
[edited]

### CODE REVIEW

**Comment by ivarne** [comment]
Why [ci skip]? This changes code, and causes lots of deprecation warnings on Travis.

**Comment by quinnj** [comment]
Yeah, sorry, probably not a good case for [ci skip]; I was just trying it out. I'll fix this up.

**Comment by Jutho** [comment]
Note that actually ntuple(n,f) is the form in the manual, not the ntuple(f,n) form. I was very surprised when i discovered the latter is the default one, but never reported it.

**Comment by quinnj** [comment]
Yeah, I was actually looking ot update the docs when I noticed there were
two methods, so I figured I'd make a PR to deprecate the one that had
"TODO: deprecate this?" marked next to it. I'll push an update in a few
minutes.

**Comment by quinnj** [comment]
Interestingly enough, there isn't a single use of `ntuple(f::Function, n::Integer)` in Base. @StefanKarpinski , as you added that method (from git blame), do you have an opinion on keeping one or the other (or both)?

**Comment by simonster** [comment]
`ntuple(f::Function, n::Integer)` seems more Julian; function-valued arguments typically come first so they can be used with `do` block syntax. OTOH, `ntuple(n::Integer, f::Function)` mirrors `NTuple{N,T}`.

Also, while we're revising `ntuple`, I believe that `f::Function` should actually just be `f` to accommodate constructors and arbitrary objects that implement `call`.

**Comment by timholy** [comment]
I agree the `f`-first version seems more julian, but wow was I surprised to see this.

**Comment by quinnj** [comment]
Bump @StefanKarpinski, any thoughts on this?

**Comment by StefanKarpinski** [comment]
I'm ok with the change. I'd be interested to hear what @JeffBezanson thinks.

**Comment by JeffBezanson** [comment]
Yes I'm ok with this. The rest of the needed changes should be done.

**Comment by quinnj** [comment]
closing in favor of #11486

**Comment by timholy** [comment]
Ah, sorry, I had forgotten all about this.

**Comment by quinnj** [comment]
No worries. It had fallen by the way-side and yours has more bells and whistles.

**Pull request closed without merging**
