### PR TITLE
work around a splatting penalty in twiceprecision

### PR DESCRIPTION
**Pull request by KristofferC**
Before:

```
julia> @btime 0:$(286.493442):360
  1.648 μs (8 allocations: 352 bytes)
```

After:

```
julia> @btime 0:$(286.493442):360
  170.405 ns (0 allocations: 0 bytes)
```

Ref https://discourse.julialang.org/t/a-possible-regression-in-0-7/14597

The typed code before this PR looks like

```
julia> f() = Base.steprangelen_hp(Float64, 2.0, 25.0, 5, 10, 2)
f (generic function with 1 method)

julia> @code_typed f()
CodeInfo(
1 1 ─ %1  = (Core._apply)(TwicePrecision{Float64}, 2.0)::TwicePrecision{Float64}                                                                                                                                   │╻     steprangelen_hp
  │   %2  = (Core._apply)(TwicePrecision{Float64}, 25.0)::TwicePrecision{Float64}  
...           
```

so not sure why that is not devirtualized (if this is the correct term here).

### CODE REVIEW

**Comment by mbauman** [comment]
Oh interesting.  We have specials support for splatting tuples, but this is sometimes splatting numbers to just pass one argument, and there we hit the pessimistic case:

```julia
julia> f(x) = println(x...)
f (generic function with 1 method)

julia> @code_typed f(1)
CodeInfo(
1 1 ─ %1 = (Core._apply)(Main.println, x)::Const(nothing, false)           │
  └──      return %1                                                       │
) => Nothing

julia> @code_typed f((1,2))
CodeInfo(
1 1 ─ %1 = (getfield)(x, 1)::Int64                                         │
  │   %2 = (getfield)(x, 2)::Int64                                         │
  │   %3 = invoke Main.println(%1::Int64, %2::Int64)::Const(nothing, false)│
  └──      return %3                                                       │
) => Nothing
```

Maybe add an `@allocated` test?

**Comment by vtjnash** [comment]
> but this is sometimes splatting numbers to just pass one argument

I think Jarrett was working on this some in #28955

**Comment by martinholters** [comment]
Ref. https://github.com/JuliaLang/julia/pull/27434#issuecomment-400335764 re. elision of `_apply` here.

**Review by mbauman — APPROVED** [review]

**Review by Keno — APPROVED** [review]
LGTM, though we should fix the underlying compiler issue also.

**Comment by KristofferC** [comment]
When that happens I'll happily revert :)

**Pull request merged**
