### PR TITLE
Add new GC STATS (max memory used, and max pause time)

### PR DESCRIPTION
**Pull request by chflood**
We want these two statistics for our GC Benchmark suite so we can do meaningful comparisons between GC algorithms.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Comment by vchuravy** [comment]
Should there be a a facility to reset those?

**Comment by oscardssmith** [comment]
probably.

**Comment by chflood** [comment]
ok, I want to add max TTSP too so I will add the reset and the TTSP to a new PR.

**Comment by oscardssmith** [comment]
what's ttsp?

**Comment by chflood** [comment]
Time To SafePoint (sorry for being cryptic)

**Pull request merged**
