### PR TITLE
Revert "Generalize broadcast to handle tuples and scalars"

### PR DESCRIPTION
**Pull request by vtjnash**
Reverts JuliaLang/julia#16986 because it broke the build.

### CODE REVIEW

**Comment by tkelman** [comment]
doesn't https://github.com/JuliaLang/julia/pull/18580 fix this, making reverting unnecessary?

**Comment by vtjnash** [comment]
This should have been done 18 hours ago.

**Comment by tkelman** [comment]
Sure. But it wasn't.

**Comment by martinholters** [comment]
If #18580 passes CI in its current form, I am in favour of merging that one rather than reverting.

**Comment by vtjnash** [comment]
OK, I see that's been updated and lgtm

**Pull request closed without merging**
