### PR TITLE
Update nullable.jl

### PR DESCRIPTION
**Pull request by bryaan**
Simple helper.

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @BryanARivera, welcome to Julia, and thanks for adding this. Could you maybe add a test as well?

**Comment by yuyichao** [comment]
Is this intended to be an unexported and untested new function?

I think we don't usually add functions that are simply the not of another one either.

**Comment by BryanARivera** [comment]
Will add test and export.  Do you think it would be better named `isNotNull` ?

**Comment by tkelman** [comment]
I think it would be better named `! isnull` at the call site

**Comment by StefanKarpinski** [comment]
Agreed. We have the `!` operator so that we don't have to define the negation of every function.

**Comment by BryanARivera** [comment]
I really like simple.  And even so, I think it would be worth the tradeoff of adding the negation fun for three reasons:

1. It reads more naturally.
2. It might just prevent a logic error here and there, 
3. Should speed up comprehension. 

Even though each task above might mostly take a second at worst, man-seconds do add up.

I also don't think `isnotnull` would be better than `exists`.  They are different enough that it's highly unlikely one would glaze over the nuance, as they *might* for a skinny, single exclamation mark, or the slightly better `isnotnull`.

I default to your judgement here Stefan.

**Comment by johnmyleswhite** [comment]
FWIW, I'm not a fan of this. I could see this being called `isempty` if we ever commit to full container semantics for Nullables.

**Comment by StefanKarpinski** [comment]
The name `exists` is also not great – the nullable exists whether it is null or not.

**Pull request closed without merging**
