### PR TITLE
More moving docstrings out of helpdb 

### PR DESCRIPTION
**Pull request by hayd**
This moves some docstrings inline and out of helpdb:
- BLAS
- libc
- libdl
- Profile
- _Most_ of Dates (there's still some docstrings I couldn't find a home for; specifically some converts and some docstrings which are grouped by year but apply to month, day etc.)

~~_Note: ATM This was on top of #14530 in the hope I needn't rebase (but I looks like I'll have to!)_~~ rebased

### CODE REVIEW

**Comment by nalimilan** [comment]
This is simply great!

**Comment by hayd** [comment]
For completeness, I'm seeing the following outcome in `make julia-genstdlib`:

*Note: I guess I shouldn't have moved the mysync docstring to deprecated that seems to have failed, I don't think it's due to the `@inline` macro...?*

```
Collect 1737 Docs

Converting rst files in stdlib/

UndefVarError(:GetLastError)
WARNING: Mod Libc GetLastError
INFO: stdlib/libc.rst: no docs for GetLastError() in Libc
UndefVarError(:FormatMessage)
WARNING: Mod Libc FormatMessage
INFO: stdlib/libc.rst: no docs for FormatMessage(n=GetLastError()) in Libc
ErrorException("Cannot find doc for msync")
WARNING: Mod Libc msync
INFO: stdlib/libc.rst: no docs for msync(ptr, len, [flags]) in Libc

Converting rst files in manual/


Converting rst files in devdocs/

UndefVarError(:build_sysimg)
WARNING: Mod Base build_sysimg
INFO: devdocs/sysimg.rst: no docs for build_sysimg(sysimg_path=default_sysimg_path, cpu_target="native", userimg_path=nothing; force=false) in Base

WARNING: Exported method missing doc for Base.@threadcall

WARNING: Missing 1 exported doc strings
INFO: Missing 105 unexported doc strings
```

**Comment by MichaelHatherly** [comment]
Yeah, those errors have been around for a while now. `GetLastError` and `FormatMessage` are windows-only I think. Might be best to try documenting all objects via `Binding`s rather than the objects themselves. I'll have a go at doing that tomorrow. That might also solve the `build_sysimg` error too, though not 100% sure.

**Comment by hayd** [comment]
@MichaelHatherly any thoughts on the `msync` deprecated placement? Should I put it in libc (even though it's deprecated)?

**Comment by MichaelHatherly** [comment]
> any thoughts on the msync deprecated placement?

Looks like you've got it in a `@unix_only` block, meaning that it's not parsed as `@doc ...` since it's not toplevel. Probably best to put it outside of the block as

```julia
"""
    msync(ptr, len, [flags])

...
"""
msync(ptr, len, flags= ?)
```

**Comment by MichaelHatherly** [comment]
> Should I put it in libc

Since `msync` isn't defined in `Libc` it seems probably best not to put it there.

**Comment by hayd** [comment]
Ah yes! I missed it was in a unix_only block! Now we're all good.

**Comment by hayd** [comment]
@MichaelHatherly I pushed a fix for that too, it was also defined in a system only block.

Now it's just `build_sysimg` and `@threadcall`:
```
Collect 1740 Docs

Converting rst files in stdlib/


Converting rst files in manual/


Converting rst files in devdocs/

UndefVarError(:build_sysimg)
WARNING: Mod Base build_sysimg
INFO: devdocs/sysimg.rst: no docs for build_sysimg(sysimg_path=default_sysimg_path, cpu_target="native", userimg_path=nothing; force=false) in Base

WARNING: Exported method missing doc for Base.@threadcall

WARNING: Missing 1 exported doc strings
INFO: Missing 105 unexported doc strings
```

**Comment by hayd** [comment]
Next up: Base...

**Comment by MichaelHatherly** [comment]
> I pushed a fix for the other Libc warnings, they were also defined in a system only block.

Cool, that works too. Though doing it that way does only document the `Function` rather than particular `Method`s, would be good to support that too. From what I've tried so far storing everything as `Binding`s simplifies things quite a bit so I'll probably still try getting that working.

> Next up: Base...

D:

**Pull request merged**
