### PR TITLE
Deprecate Coff_t and FileOffset

### LINKED ISSUE #14555: remove Coff_t
we should remove `Coff_t` from the base API as it cannot be used correctly. the problem with it is that is is not OS-dependent, but compiler-flag dependent (on glibc) and so any function that tries to use this parameter as an argument (e.g. d000aaef) ends up calling the wrong function (again, possibly just on glibc).

Instead, we should tell people to use Int64 for all file offsets and define c-stubs for resolving any libc lies (e.g. a78e48c0)

### PR DESCRIPTION
**Pull request by yuyichao**
See #14555 for explaination, bottom line is that these could be wrong for libc functions and are unreliable for external libraries.

Also fixes the types in libgit2, which is what the backport pending label is for. (The second commit shouldn't be backported).

The second commit also change the windows `jl_lseek` to use `_lseeki64` since we are using 64bit file offset everywhere now. I found the function on MSDN for VC2003~VS2015 so I hope it's MSVC compatible.... @tkelman 

Close #14555

c.c. @vtjnash

### CODE REVIEW

**Comment by vtjnash** [comment]
lgtm

**Comment by tkelman** [comment]
huh? libgit2 julia wrappers aren't on 0.4

**Comment by yuyichao** [comment]
Oh, I thought we had libgit2 wrappers without integrating into the packaging system. never mind for the backport part then ;-p

**Comment by tkelman** [comment]
> I found the function on MSDN for VC2003~VS2015 so I hope it's MSVC compatible....

Not causing a build failure, so good enough for now. Little incentive at the moment to work much harder supporting it, checking test results etc.

**Comment by PallHaraldsson** [comment]
I see there packages, e.g. PyCall have to remove FileOffset and GZip (actually doesn't have the same trivial code with it's own "typealias ZFileOffset"), for no good reason?

There could be more packages.. and in case say later we have Int128 bit file offsets.. isn't a typealias just a good (cheap, and descriptive, even if always defined as Int64) thing?

I didn't look to closely at Coff_t (that is not te public API, and I care less about), but I saw
size_t: "is a type able to represent the size of any object in bytes" used. Wouldn't that in general be Integer (not Int64)?

**Comment by yuyichao** [comment]
> I see there packages, e.g. PyCall have to remove FileOffset and GZip (actually doesn't have the same trivial code with it's own "typealias ZFileOffset"), for no good reason?

GZip (And Libz) was using it to determine the size of `z_off_t` which has nothing to do with `off_t`.
PyCall use it as the standard type for file offset in julia. The version check is only necessary to support old julia versions.

**Comment by PallHaraldsson** [comment]
>PyCall use it as the standard type for file offset in julia. The version check is only necessary to support old julia versions.

Yes, but only given that FileOffset is deprecated (is it really a good idea? should it be reverted?) and it seems just unnecessary and without that this comment not needed:

https://github.com/yuyichao/PyCall.jl/commit/e35ffc89e81c8243e329478b06b4cc1bc9057ef9

**Comment by vtjnash** [comment]
As mentioned in #14555, the `off_t` type is compiler-flag dependent, so it was confusing and wrong to present this as a OS-dependent value. This would be like presenting the windows TCHAR type as Ctchar -- which would also be nonsensical because tchar is an alias for either `char` or `wchar_t` depending on which function variant is called (A or W), and not dependent on the OS at all.

While a 128-bit files (or more likely a raw disk fd) isn't outside the realm of possibility (> 9 exabytes -- https://en.wikipedia.org/wiki/Exabyte), I don't expect to see them anytime soon enough for it to be worth the current maintenance effort to make Julia code forward-compatible.

@yuyichao that PyCall commit might be overly complicated. i think we can safely assume that FileOffset was also an Int64 for all existing supported versions of julia.

**Comment by yuyichao** [comment]
> I think we can safely assume that FileOffset was also an Int64 for all existing supported versions of julia.

Win32 is the only platform I'm worrying about.

**Pull request merged**
