### PR TITLE
CI: Also try `codespell`

### PR DESCRIPTION
**Pull request by DilumAluthge**
https://github.com/codespell-project/codespell

Targets https://github.com/JuliaLang/julia/pull/51704

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Still some false positives.

**Comment by LilithHafner** [comment]
As a point of comparison, `typos` got [208 legitimate typos ](https://github.com/JuliaLang/julia/pull/51709) and 58 explicit exclusions (23 of which could be remove if https://github.com/crate-ci/typos/issues/852 is implemented)

<details>
<summary>exclusions (typos.toml)</summary>

```toml
default.extend-ignore-identifiers-re = ["^[a-zA-Z][a-zA-Z]?[a-zA-Z]?[a-zA-Z]?$"]

[default.extend-words]
ba = "ba"
egal = "egal"
parm = "parm"
modul = "modul"
nd = "nd"
strat = "strat"
WRONLY = "WRONLY"
thisy = "thisy"
vally = "vally"
Ot = "Ot"
clos = "clos"
applys = "applys"
findn = "findn"
mis = "mis"
seh = "seh"
ue = "ue"
Missings = "Missings"
SOM = "SOM"
sais = "sais"
Merly = "Merly"
Filetimes = "Filetimes"
HSA = "HSA"
Strategems = "Strategems"
anumber = "anumber"
uupper = "uupper"
shttp = "shttp"
ser = "ser"
somes = "somes"
sav = "sav"
egals = "egals"
OLT = "OLT"
eyt = "eyt"
matc = "matc"
nam = "nam"
alls = "alls"
noe = "noe"

# strings in tests directories
fo = "fo"
Uest = "Uest"
Dows = "Dows"
aquire = "aquire"

# typos that are programmatically observable
compileable = "compileable"
overlayed = "overlayed"

[default.extend-identifiers]
mrs_claus = "mrs_claus"
womens = "womens"
breal = "breal"
Breal = "Breal"
Numer = "Numer"
splitted = "splitted"
affinitized = "affinitized"
key_smove = "key_smove"
readed_zero = "readed_zero"
check_inconsistentcy = "check_inconsistentcy"
L_OP_CALLL = "L_OP_CALLL"
OP_CALLL = "OP_CALLL"

# strings in test directories
Facilisi = "Facilisi"
vailable = "vailable"

# typos that are programmatically observable
supress_output = "supress_output"
hashs_seed = "hashs_seed"
```

</details>

**Comment by LilithHafner** [comment]
After applying corrections from `typos`, `codespell` found 12 more typos. I conclude that `codespell` is between 0.057 and 1.057x as sensitive as `typos`. I'm guessing it's a decent bit less sensitive.

I'm not sure how many exclusions are necessary with `codespell` because of https://github.com/codespell-project/codespell/issues/3144.

**Comment by LilithHafner** [comment]
Also, I find `typos` easier to work with and less flakey/buggy.

**Pull request closed without merging**
