### PR TITLE
Delete codesign.sh

### PR DESCRIPTION
**Pull request by staticfloat**
The better, more powerful version of this is now stored in julia-buildkite at https://github.com/JuliaCI/julia-buildkite/blob/main/utilities/macos/codesign.sh

### CODE REVIEW

**Comment by giordano** [comment]
There are some references to this file, for example https://github.com/JuliaLang/julia/blob/2a9f4412a00cbaf366895083f651d5d7906cce1f/Makefile#L442-L445 and https://github.com/JuliaLang/julia/blob/2a9f4412a00cbaf366895083f651d5d7906cce1f/contrib/prepare_release.sh#L59-L63

**Review by DilumAluthge — APPROVED** [review]

**Review by DilumAluthge — DISMISSED** [review]
Actually, don't we need to keep this? So that when someone does `make` on their local machine, we do the ad-hoc signing, and then the user can run the binary on their local machine without having any "unsigned binary" errors?

**Comment by staticfloat** [comment]
`ld` already ad-hoc signs most stuff; I guess we need to double-check that removing this still allows local builds to work.

**Comment by staticfloat** [comment]
LGTM

**Comment by IanButterworth** [comment]
The macos aarch64 tesst runner that's failing seems to have no free memory at the start of the run.

The macos x86 build artifact works for me locally, as does a local `make`.

Seems good?

**Comment by DilumAluthge** [comment]
> I guess we need to double-check that removing this still allows local builds to work.

@staticfloat or @IanButterworth Have you verified this?

**Comment by IanButterworth** [comment]
I mentioned what I tested above. Is there another test to do?

**Comment by DilumAluthge** [comment]
Yeah, as long as a local `make` works correctly on macOS, I think we should be good.

**Pull request merged**
