### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by robbyriverside**
A simple project example that gives beginners a starting point for creating and using their own projects.

### CODE REVIEW

**Comment by bramtayl** [comment]
It's cool that you're trying to make things more beginner friendly. Maybe suggest improvements to or a reorganization of the existing documentation? I'm not sure documentation should exist in a separate repo (and in any case, there's a bunch of typos in getting_started_faq)

**Comment by robbyriverside** [comment]
Well, I am new to Julia and this is strictly volunteer work.  I offer it without license or assumption.  Feel free to incorporate it as you see fit.  It does not need to continue on my repo.  You are welcome to download it and change it.  I was merely suggesting that this kind of approach would have been useful to me when I was starting out.  It provides enough of a boost to get started and learn as you go.

I believe that a similar quick overview of using the basics of Julia would also be helpful.  The documentation is a bit dense for just finding out how to, for example, convert a tuple into an array.  Perhaps an FAQ style document might be useful for language basics.  My time is limited, or I would have done that as well.

All the best and thank you for an amazing language!

Rob Farrow

**Comment by simonbyrne** [comment]
Hi Rob,

Thanks for the write up. [Your guide](https://github.com/robbyriverside/ModulePlay/blob/main/getting_started_faq.md) looks very useful and is well-written, however we tend to avoid linking to tutorials and similar resources directly from the manual itself. We do however have a place for them [on the website](https://julialang.org/learning/tutorials/): you can add it by opening a pull request on this file: https://github.com/JuliaLang/www.julialang.org/blob/master/learning/tutorials.md

If you were interested in contributing it to the manual itself, we could probably find a way to work some of this in. I've long been bothered that the [Getting Started](https://docs.julialang.org/en/v1/manual/getting-started/) page spends so much time talking about command line options, and not  about more useful things. Maybe a sequence of simple guides (REPL basics, projects and packages, modules) would be a good way forward.

**Comment by robbyriverside** [comment]
Thank you, Simon.  That looks like the right place to put this.  

I will take a look at Getting Started and see what I can do.

Rob

**Pull request closed without merging**
