### PR TITLE
Augment sort.jl documentation with doctests

### PR DESCRIPTION
**Pull request by xorJane**
I added some doctests to sort.jl in issorted(), sort!(), sort(), sortrows(), sortcols(), sortperm(), and sortperm!(). Per `make -C doc doctest`, it seems all added tests pass.

Many of the examples are redundant. Just let me know if you'd like more/different examples, less redundancy, etc.!

Thanks a lot!!

ref #18821

### CODE REVIEW

**Comment by mauro3** [comment]
I think they should be more concise: when calling help at the REPL I don't want pages and pages of examples.  For instance there is no advantage to sort vectors with more than three elements.  Also construction of the vector should be done inside the function call.  For example the `issorted` example could be shortened to:
```
```jldoctest
julia> issorted([1,2,3])
true

julia> issorted(-1* [1,2,3])
false
```

**Comment by StefanKarpinski** [comment]
It's much better to have too much documentation than too little, but I do think that some of the extra examples would be better off in the manual, but then again the stdlib reference is generated from the doc strings. Maybe we need some mechanism for basic and extended documentation?

**Comment by xorJane** [comment]
Thank you --- I appreciate the feedback!

I updated my PR to make the examples more concise as @mauro3 suggested, and I added doctests for sortperm() and sortperm!()

For now I left vector construction outside of the function calls to sort!() and sortperm!() to illustrate mutation, but I'm happy to change that too. :)

**Comment by hayd** [comment]
Another thing worth mentioning is that [-1, -2, -3] is "sorted" in the sense that it is reversed, so it may be worth adding **even more** examples:
```
julia> issorted([1, 2, 3])
true

julia> issorted([2, 1, 3])
false

julia> issorted([-1, -2, -3])
false

julia> issorted([-1, -2, -3], rev=true)
true
```

This branch needs a rebase!

**Comment by xorJane** [comment]
Thanks for the bump! Just rebased. It looks like most of the functions for which I originally wrote doctests have since been covered. Now this PR just adds doctests for `sortrows` and `sortcols`, and adds a doctest using the `rev` flag to the docstring for `issorted` as suggested by hayd. Have a great night!

**Review by tkelman — APPROVED** [review]
lgtm, thanks for updating

**Pull request merged**
