### PR TITLE
move TestHelpers.OAs -> Test.OAs

### PR DESCRIPTION
**Pull request by rfourquet**
This is motivated by the fact that I didn't find a way to use the `OAs` module in `Random` tests (in #24874, where I had to duplicate temporarily `OAs`), and that after all this `OAs` module could very well be useful beyond base/stdlib (i.e. in external packages).
I'm not sure why the module name is not `OffsetArrays` - maybe to not be confused with the "real" module which is in a package? (cc @timholy).

### CODE REVIEW

**Comment by KristofferC** [comment]
I don't think this should be in the `Test` module. It is just a utility thing to help test some Base functionality. If people want to test their stuff with OffsetArrays in their packages, they can just use the OffsetArrays package?

**Comment by StefanKarpinski** [comment]
Agree, this seems strange. Keep in mind that `Test` is a formal interface that we support. Having random (forgive the pun) stuff in it just for Base's own testing is not ideal.

**Comment by rfourquet** [comment]
Ok, I agree, and I also remember now that a package can depend on another one only for tests, which makes this dependency optional for using the package (so depending on `OffsetArrays` for testing is not a big deal).

**Comment by rfourquet** [comment]
For reference, another (better) fix at #25582.

**Pull request closed without merging**
