### PR TITLE
Bump openspecfun (on master)

### PR DESCRIPTION
**Pull request by jiahao**
Attempt to improve build for Intel compilers.

Refs: JuliaLang/openspecfun#30 #10181

### CODE REVIEW

**Comment by jiahao** [comment]
Build failure seems unrelated.

**Comment by tkelman** [comment]
seems fairly safe https://github.com/JuliaLang/openspecfun/compare/f3036c094ae56fdf447092a871ea4fe27fdeec16...381db9bc865e51de67be9dcaa1610a6f90029c72

**Comment by jiahao** [comment]
YOLO

**Comment by tkelman** [comment]
Oh yeah, I forgot that openspecfun doesn't build on appveyor, we just use the dll from the nightlies (and we don't have gfortran there). Looks okay on the buildbots though.

**Pull request merged**
