### PR TITLE
inference: fix inference error from constructing invalid `TypeVar`

### LINKED ISSUE #56248: A TypeError crashes Julia
The following code crashes Julia
```julia
using Test
import Pkg
Pkg.add("Manifolds")
using Manifolds



@testset "Julia crash" for M in
    [
        Sphere(2),
    ]
    @test_throws TypeError [] isa Vector{<:Sphere(3)}
end
```

See a discussion in [this issue](https://github.com/JuliaManifolds/Manifolds.jl/issues/758) and a reproduction of the problem in [this repo](https://github.com/olivierverdier/JuliaCrash.jl).

### PR DESCRIPTION
**Pull request by aviatesk**
- fixes JuliaLang/julia#56248

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by nsajko** [comment]
Is this backportable to v1.10, v1.11?

**Comment by oscardssmith** [comment]
looks pretty backportable.

**Comment by topolarity** [comment]
The backport of this broke the tests on 1.10 (`Base.infer_return_type` does not exist on 1.10)

**Comment by nsajko** [comment]
Probably `Core.Compiler.return_type` should be used instead of `Base.infer_return_type`.

**Comment by aviatesk** [comment]
I general we should use `Base.infer_return_type` or `Base.return_types` instead of `Core.Compiler.return_type` for inference quality tests.

**Comment by nsajko** [comment]
> `Base.infer_return_type` does not exist on 1.10

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/56381/commits/bb86259075aa94b2425e769c0b79fe2d63a585e5 I guess (I had already made that change locally and forgotten to push the whole part, I only pushed the `only` part of it).

**Pull request merged**
