### PR TITLE
More helpful error message for empty `cpu_target` in `Base.julia_cmd`

### LINKED ISSUE #52209: Confusing error if `JULIA_CPU_TARGET=""`
This isn't a valid setting, but the error should be more clear (bc this can happen by accident). Currently it gives the error
```
ERROR: Invalid CPU name "-J/Users/eph/.julia/juliaup/julia-1.9.4+0.aarch64.apple.darwin14/lib/julia/sys.dylib"
```
which looks like it is somehow taking the next implicit argument as the target.

Full demo on 1.9.4:
```julia
JULIA_CPU_TARGET="" julia
]               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.4 (2023-11-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> activate --temp
  Activating new project at `/var/folders/gj/l9rbktlj6qndlnz1nk164d280000gn/T/jl_5zBoLF`

(jl_5zBoLF) pkg> add PackageAnalyzer
   Resolving package versions...
   Installed PackageAnalyzer ─ v3.0.1
   Installed JuliaSyntax ───── v0.4.7
    Updating `/private/var/folders/gj/l9rbktlj6qndlnz1nk164d280000gn/T/jl_5zBoLF/Project.toml`
  [e713c705] + PackageAnalyzer v3.0.1
    Updating `/private/var/folders/gj/l9rbktlj6qndlnz1nk164d280000gn/T/jl_5zBoLF/Manifest.toml`
  [1520ce14] + AbstractTrees v0.4.4
  [69666777] + Arrow v2.6.2
  [31f734f8] + ArrowTypes v2.2.2
  [d1d4a3ce] + BitFlags v0.1.8
  [c3b6d118] + BitIntegers v0.3.1
⌅ [fa961155] + CEnum v0.4.2
  [5ba52731] + CodecLz4 v0.4.1
  [944b1d66] + CodecZlib v0.7.3
⌅ [6b39b394] + CodecZstd v0.7.2
  [34da2185] + Compat v4.10.0
  [f0e56b4a] + ConcurrentUtilities v2.3.0
  [187b0558] + ConstructionBase v1.5.4
  [9a962f9c] + DataAPI v1.15.0
  [e2d170a0] + DataValueInterfaces v1.0.0
  [4e289a0a] + EnumX v1.0.4
  [460bff9d] + ExceptionUnwrapping v0.1.9
  [e2ba6199] + ExprTools v0.1.10
  [d7ba0133] + Git v1.3.0
  [bc5e4493] + GitHub v5.9.0
  [cd3eb016] + HTTP v1.10.0
  [842dd82b] + InlineStrings v1.4.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.5.0
  [682c06a0] + JSON v0.21.4
  [0f8b85d8] + JSON3 v1.13.2
  [70703baa] + JuliaSyntax v0.4.7
  [0e77f7df] + LazilyInitializedFields v1.2.2
  [741b9549] + Legolas v0.5.15
  [726dbf0d] + LicenseCheck v0.2.2
  [e6f89c97] + LoggingExtras v1.0.3
  [739be429] + MbedTLS v1.1.8
  [78c3b35d] + Mocking v0.7.7
  [4d8831e6] + OpenSSL v1.4.1
  [bac558e1] + OrderedCollections v1.6.2
  [e713c705] + PackageAnalyzer v3.0.1
  [69de0a69] + Parsers v2.8.0
  [2dfb63ee] + PooledArrays v1.4.3
  [aea7be01] + PrecompileTools v1.2.0
  [21216c6a] + Preferences v1.4.1
  [2792f1a3] + RegistryInstances v0.1.0
  [6c6a2e73] + Scratch v1.2.1
  [91c51154] + SentinelArrays v1.4.1
  [777ac1f9] + SimpleBufferStream v1.1.0
  [2133526b] + SodiumSeal v0.1.1
  [856f2bd8] + StructTypes v1.10.0
  [dc5dba14] + TZJData v1.0.0+2023c
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.11.1
  [f269a46b] + TimeZones v1.13.0
⌅ [3bb67fe8] + TranscodingStreams v0.9.13
  [5c2747f8] + URIs v1.5.1
  [2e619515] + Expat_jll v2.5.0+0
  [f8c6e375] + Git_jll v2.42.0+0
  [94ce4f54] + Libiconv_jll v1.17.0+0
  [5ced341a] + Lz4_jll v1.9.4+0
  [458c3c95] + OpenSSL_jll v3.0.12+0
  [3ac119c9] + Tokei_jll v12.1.200+0
  [3161d3a3] + Zstd_jll v1.5.5+0
  [a9144af2] + libsodium_jll v1.0.20+0
  [4ecb348a] + licensecheck_jll v0.3.101+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.9.2
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.0.5+0
  [deac9b47] + LibCURL_jll v8.4.0+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.2+0
  [14a3606d] + MozillaCACerts_jll v2022.10.11
  [4536629a] + OpenBLAS_jll v0.3.21+4
  [efcefdf7] + PCRE2_jll v10.42.0+0
  [83775a58] + Zlib_jll v1.2.13+0
  [8e850b90] + libblastrampoline_jll v5.8.0+0
  [8e850ede] + nghttp2_jll v1.52.0+1
  [3f19e933] + p7zip_jll v17.4.0+0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✗ LazilyInitializedFields
  ✗ AbstractTrees
  ✗ JuliaSyntax
  ✗ Tokei_jll
  ✗ Expat_jll
  ✗ licensecheck_jll
  ✗ RegistryInstances
  ✗ Git_jll
  ✗ LicenseCheck
  ✗ Git
  ✗ PackageAnalyzer
  0 dependencies successfully precompiled in 1 seconds. 55 already precompiled.
  11 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

(jl_5zBoLF) pkg> precompile
Precompiling project...
  ✗ LazilyInitializedFields
  ✗ AbstractTrees
  ✗ JuliaSyntax
  ✗ Tokei_jll
  ✗ Expat_jll
  ✗ licensecheck_jll
  ✗ RegistryInstances
  ✗ Git_jll
  ✗ LicenseCheck
  ✗ Git
  ✗ PackageAnalyzer
  0 dependencies successfully precompiled in 0 seconds. 55 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

PackageAnalyzer [e713c705-17e4-4cec-abe0-95bf5bf3e10c]

Failed to precompile PackageAnalyzer [e713c705-17e4-4cec-abe0-95bf5bf3e10c] to "/Users/eph/.julia/compiled/v1.9/PackageAnalyzer/jl_YTsf62".
ERROR: Invalid CPU name "-J/Users/eph/.julia/juliaup/julia-1.9.4+0.aarch64.apple.darwin14/lib/julia/sys.dylib"

```

### PR DESCRIPTION
**Pull request by giordano**
Fix #52209.

### CODE REVIEW

**Comment by ericphanson** [comment]
We could also error if the string is empty. In my case that would’ve been preferable, because I was trying to set it but had messed up my docker ENVs and so it got set to the empty string. It would’ve been harder to track down my error if it seemed to work.

**Comment by staticfloat** [comment]
I think we should error on `-C ''`.

**Comment by giordano** [comment]
I mean, that's already the case now and precisely the cause of #52209.

**Comment by ericphanson** [comment]
The problem is the error message is misleading. The error message should be clear and direct: “invalid CPU target: `””`”

**Comment by giordano** [comment]
With latest version:
```
% JULIA_CPU_TARGET='' julia -q
(@v1.11) pkg> activate --temp
  Activating new project at `/var/folders/v2/hmy3kzgj4tb3xsy8qkltxd0r0000gn/T/jl_G2vx2I`

(jl_G2vx2I) pkg> add Example
   Resolving package versions...
    Updating `/private/var/folders/v2/hmy3kzgj4tb3xsy8qkltxd0r0000gn/T/jl_G2vx2I/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `/private/var/folders/v2/hmy3kzgj4tb3xsy8qkltxd0r0000gn/T/jl_G2vx2I/Manifest.toml`
  [7876af07] + Example v0.5.3
Precompiling project...
  ✗ Example
  0 dependencies successfully precompiled in 0 seconds
  1 dependency errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

julia> using Example
Precompiling Example
        Info Given Example was explicitly requested, output will be shown live
ERROR: Invalid target option: empty CPU name
  ✗ Example
  0 dependencies successfully precompiled in 0 seconds

ERROR: The following 1 direct dependency failed to precompile:

Example [7876af07-990d-54b4-ab0e-23690620f79a]

Failed to precompile Example [7876af07-990d-54b4-ab0e-23690620f79a] to "/Users/mose/.julia/compiled/v1.11/Example/jl_pewRlt".
ERROR: Invalid target option: empty CPU nam
Stacktrace:
```
I don't know why in the last line the error message is missing the last character, but I think this is unrelated to this PR.

**Review by staticfloat — APPROVED** [review]

**Pull request merged**
