### PR TITLE
Revert "Revert "fix #12096, disagreement between type cache and isleaftype

### LINKED ISSUE #12096: instance field of egal singleton types may not be egal
Is it valid that there may be type->instance assigned for a type that was excluded from the type cache (and not assigned a uid)? I thought it must be true that a type qualifies as a leaf type iff it is guaranteed to be unique'd.

currently it is possible to define:
```julia
immutable Blah{T} end
a=Blah{Blah{TypeVar(:_,Int,true)}} # some random type (not in type cache)
a.instance # valid
Base.isleaftype(a) # true
```

but the definition of jl_egal says that ta and tb can always be compared by pointer if retrieved by jl_typeof:
```c
 279 int jl_egal(jl_value_t *a, jl_value_t *b)
 280 {
 281     if (a == b)
 282         return 1;
 283     jl_value_t *ta = (jl_value_t*)jl_typeof(a);
 284     if (ta != (jl_value_t*)jl_typeof(b))
 285         return 0;
```
which leads to the potentially faulty conclusion that the instances of egal types aren't necessarily egal:
```julia
julia> a=Blah{Blah{TypeVar(:_,Int,true)}}
Blah{Blah{_<:Int64}}

julia> b=Blah{Blah{TypeVar(:_,Int,true)}}
Blah{Blah{_<:Int64}}
julia> a.instance === b.instance
false

julia> a === b
true
```

### PR DESCRIPTION
**Pull request by vtjnash**
This reverts commit c6e5a5452897cc2e9d22a57c0795a1b5ffe73eb3.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I assume this should be merged? Are we sure this fix is safe now?

**Comment by tkelman** [comment]
Does anyone know why it got reverted in the first place?

**Comment by StefanKarpinski** [comment]
> Does anyone know why it got reverted in the first place?

If only there were a place to record such information. Fortunately, @timholy left us some bread crumbs: https://github.com/JuliaLang/julia/commit/c6e5a5452897cc2e9d22a57c0795a1b5ffe73eb3, https://github.com/JuliaLang/julia/issues/12096.

**Comment by yuyichao** [comment]
I believe those are what the original commit should fix (and unfixed by the revert) and not the reason of the revert.

**Comment by StefanKarpinski** [comment]
Ah, well then I don't have any idea about the revert.

**Comment by vtjnash** [comment]
So what's the call? Do we just revert this then find out what packages are broken?

**Comment by vtjnash** [comment]
If only there was a way we could see if this might break any packages before merging it..

**Comment by tkelman** [comment]
Do you want me to run pkgeval on this branch and compare to master I can do that.

**Comment by tkelman** [comment]
These look unrelated or intermittent: https://gist.github.com/84f7f7cd637550f7c65a85a8b2fef5c1

**Pull request merged**
