### PR TITLE
Allow the the REPL backend to run on the root Task

### PR DESCRIPTION
**Pull request by mkitti**
This change allows the REPL backend to run on the root `Task` rather than running using `@async` on a new `Task` as done in `REPL.start_repl_backend`. When the change is activated by setting the environmental variable `JULIA_ROOT_REPL=1`, the statement `Base.roottask === Base.current_task()` will evaluate to `true` in the REPL.

Use of the environmental variable `JULIA_ROOT_REPL` is mainly meant to permit evaluation and testing in the near term. Movement of the backend REPL loop to `REPL.repl_backend_loop` and the addition of `backend_on_current_task` keyword argument to `REPL.run_repl` also facilitates running the REPL backend on the root Task by an outside package.

JavaCall is a package for interoperability with the Java Virtual Machine that could benefit from a REPL backend running on the root Task. Currently `JULIA_COPY_STACKS=1` is required for JavaCall.jl to function properly on Mac and Linux. On the Windows operating system, `JULIA_COPY_STACKS=1` is not needed for JavaCall and may create more issues. This approach avoids the performance degradation involved in enabling `JULIA_COPY_STACKS=1`. If the REPL backend were run on the root `Task`, then `JULIA_COPY_STACKS=1` would not be required to run JavaCall on the REPL.

The status quo results in a segmentation fault on Linux run trying to run JavaCall:
```julia
$ ./julia --banner=no
julia> versioninfo()
Julia Version 1.5.0-DEV.422
Commit de4f8211b9* (2020-03-08 21:42 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, bdver1)

julia> import Pkg; Pkg.status()
     Status `~/.julia/environments/v1.5/Project.toml`
   494afd89 JavaCall v0.7.3

julia> using JavaCall; JavaCall.init()
┌ Warning: JavaCall needs the environment variable `JULIA_COPY_STACKS` to be `1` or `yes`.
│ Calling the JVM may result in undefined behavior.
└ @ JavaCall ~/.julia/packages/JavaCall/0wJQZ/src/JavaCall.jl:38
Segmentation fault (core dumped)
```

With `JULIA_ROOT_REPL = 1` and the REPL backend running on the root `Task`, a segmentation fault does not occur and JavaCall functions perfectly. `JULIA_COPY_STACKS` does not need to be enabled here for JavaCall to function.
```julia
$ JULIA_ROOT_REPL=1 ./julia --banner=no
julia> versioninfo()
Julia Version 1.5.0-DEV.422
Commit de4f8211b9* (2020-03-08 21:42 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, bdver1)
Environment:
  JULIA_ROOT_REPL = 1

julia> import Pkg; Pkg.status()
     Status `~/.julia/environments/v1.5/Project.toml`
   494afd89 JavaCall v0.7.3

julia> using JavaCall; JavaCall.init()
┌ Warning: JavaCall needs the environment variable `JULIA_COPY_STACKS` to be `1` or `yes`.
│ Calling the JVM may result in undefined behavior.
└ @ JavaCall ~/.julia/packages/JavaCall/0wJQZ/src/JavaCall.jl:38

julia> jlm = @jimport java.lang.Math
JavaObject{Symbol("java.lang.Math")}

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0

julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/4)
0.7071067811865475
```

Further thoughts:
1. Perhaps running the REPL backend on the root `Task` should be the default behavior. I am not aware of a situation that actually requires the backend to run under `@async` on a non-root `Task`
2. This approach may allow Julia to drop the need for `JULIA_COPY_STACKS`, simplifying the code base.
3. Packages like JavaCall could enable functions that need to be executed from the root `Task` to be called on non-root `Tasks` through a similar `Channel` based system. Java is fully capable of asynchronous multithreaded behavior on its own.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I think this should be the default; I'm not sure we need the environment variable at all.

We still need `JULIA_COPY_STACKS`, but we also need a better general solution to this problem. In the meantime, I think this is a good improvement given how simple it is.

**Comment by mkitti** [comment]
Would you like me to revise the PR?

I will:
1. Eliminate the environmental variable
2. Set the keyword argument `backend_on_current_task`  of `run_repl` to default to `true`
3. Revert client.jl to master

**Comment by c42f** [comment]
As mentioned on slack, a nicer API to resolve the java issues would be to have a custom calling convention. Jeff mentioned this here: https://github.com/JuliaLang/julia/issues/31104#issuecomment-484256248

I wonder whether a crude implementation of this could be done right now, taking your general approach of running on the root task, but wrapping a rather different API around it than you have here.

My thought would be to extend the new `@ccall` macro to add a calling convention argument and use this for calling into the JVM inside JavaCall. For example the following ccall 

https://github.com/JuliaInterop/JavaCall.jl/blob/4989b64cb69cbd3e0409ec46a62e6124628cdb8a/src/core.jl#L222

might become

```julia
@ccall callmethod(penv::Ptr{JNIEnv},
                  obj.ptr::Ptr{Nothing},
                  jmethodId::Ptr{Nothing},
                  convertedArgs::Ptr{Nothing})::$x force_main_stack=true
```

The new `force_main_stack=true` attribute (better / more accurate name needed?) would force the call to happen on the main stack (for this, the root task will do, as you have found).

Implementation-wise, changing `@ccall` to emit the right code should be fairly accessible. I feel like the tricky part would be making sure the root task is available for running such code, and managing the communication between the root task and the task which actually wants to do the call.

The benefit of this approach is that it won't break JavaCall when people try to use it from a task which is `@async` or `@spawn`d, rather than directly from the REPL backend task.

(Having said all that, I'm not opposed to merging this change per se. It just would be nice to aim for the more general solution if you have the time to pursue it.)

**Comment by vtjnash** [comment]
If we forced both front and back end to live on different tasks, the ‘force_main_stack’ option implementation becomes relatively simple to implement using existing primitives (using yieldto, with the root task running a simple ccall dispatch worker). Personally, I think this PR is closer to optimal though, until Java fixes their implementation, though I know other developers who reasonably disagree.

**Comment by c42f** [comment]
> using yieldto, with the root task running a simple ccall dispatch worker

Great, I was thinking `yieldto` could come into the story, but not sure of the detail.

> Personally, I think this PR is closer to optimal though, until Java fixes their implementation, though I know other developers who reasonably disagree.

But does the current PR help JavaCall in anything other than trivial code where nobody ever calls `@async` or `@spawn`?

**Comment by mkitti** [comment]
By providing access to the root Task from the standard REPL, packages like JavaCall should be able then engineer solutions like @vtjnash suggested.

As for multithreading and JavaCall, it is best to leave multiprocessing of Java functions to Java.

After this PR is merged, the JavaCall package would have a few engineering options to handle `jcall` under `@async` or `@spawn` from the standard REPL including launching the worker that @vtjnash suggested. To continue the REPL, JavaCall could launch a second REPL backend loop using `@async` to continue handling new commands from the REPL frontend.

To be clear, this PR does nothing specific for JavaCall. It simply makes the REPL commands execute on the root Task by default, which enables further engineering from within the REPL that is currently not possible. The other solutions require setting `JULIA_COPY_STACKS` before starting Julia and the REPL or starting the the REPL in a non-conventional fashion such as in [RootTaskREPL.jl](https://github.com/mkitti/RootTaskREPL.jl). JavaCall is just the motivation.

Additionally, `JULIA_COPY_STACKS` does not work on Windows leading to some confusion [ [1](https://discourse.julialang.org/t/problem-in-running-julia-on-juno/35412/2), [2](https://travis-ci.org/github/mkitti/JavaCall.jl) ].

Even if this only enabled trivial code from the REPL, it is much more user friendly for potential new Julia users who would like to interface with legacy Java code. Seeing warnings or segmentation faults and having to set OS specific environmental variables is less than ideal.

**Review by JeffBezanson — APPROVED** [review]

**Comment by mkitti** [comment]
Should we mention something about this in NEWS?

**Pull request merged**
