### PR TITLE
[release 1.5] more backports for 1.5-rc2

### PR DESCRIPTION
**Pull request by JeffBezanson**
Includes:
#36738
#36727
#36725
#36715
#36657
#36650
#36641
#36610
#36679
#36739
#36757
#36763
#36785
#36781

### CODE REVIEW

**Comment by mbauman** [comment]
The FreeBSD tester looks like [it froze](https://build.julialang.org/#/builders/33/builds/1859). I clicked rebuild.

**Comment by oscardssmith** [comment]
Not sure if this is the right place to ask, but is the goal to have 1.5 out for JuliaCon?

**Comment by StefanKarpinski** [comment]
That would be great, but we're not going to rush or slow down the release based on JuliaCon. The final 1.5 will be released when it's ready — i.e. after a release candidate has been out for a week or so without any release blockers.

**Comment by JeffBezanson** [comment]
This is ready to go.

**Comment by rfourquet** [comment]
Can the following be backported? #36734, #36561, #36560, and maybe the as yet unmerged #36658.

**Comment by JeffBezanson** [comment]
Yes those all look fine. Go ahead and `cherry-pick -x` them onto this branch and push it.

**Comment by JeffBezanson** [comment]
Wow, a lot of files were missing license headers.

**Comment by rfourquet** [comment]
I just pushed #36346 here which is a bug fix, I hope this is ok.

**Pull request merged**
