### PR TITLE
[release-1.0] Set VERSION to 1.0.5

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Review by KristofferC — APPROVED** [review]

**Comment by ararslan** [comment]
Anyone know what's up with the libgit2 failure on macOS? Looks like it thinks it doesn't have ssh support.

**Comment by ararslan** [comment]
@staticfloat ^?

**Comment by staticfloat** [comment]
Nope, no idea.  Has anything changed on this branch?

**Comment by ararslan** [comment]
Hm, I thought we had made changes to the libgit2 version or something but according to https://github.com/JuliaLang/julia/compare/v1.0.4...81c396b the only changes (presumably) wouldn't affect this.

**Comment by ararslan** [comment]
Would someone on a Mac be willing to build this branch and run tests?

**Comment by KristofferC** [comment]
```
➜  julia git:(81c396b544) ✗ make -C test LibGit2                      
    JULIA test/LibGit2
Test        (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
The following 'Resetting the helper list...' warning is expected:
┌ Warning: Resetting the helper list is currently unsupported:
│ ignoring all git credential helpers
└ @ LibGit2 ~/julia/usr/share/julia/stdlib/v1.0/LibGit2/src/gitcredential.jl:234
LibGit2/libgit2  (1) |   142.70 |   1.36 |  1.0 |    1457.54 |   627.83

Test Summary: | Pass  Broken  Total
  Overall     |  682       1    683
    SUCCESS

➜  julia git:(81c396b544) ✗ ./julia -q -e 'using InteractiveUtils; versioninfo()'
Julia Version 1.0.5
Commit 81c396b544* (2019-08-31 18:18 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.2.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by ararslan** [comment]
Excellent, thanks Kristoffer!

**Comment by KristofferC** [comment]
Well, look like the mac build passed now...

**Comment by staticfloat** [comment]
I figured there might be something wrong with the build that got uploaded, so I restarted the `package_macos64` builder, which then retriggered the `tester_macos64` builder.  That's kind of worrying, but I'm glad our test suite caught it.

**Pull request merged**
