### PR TITLE
🤖 [master] Bump the Downloads stdlib from f97c72f to 246504e

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Downloads
URL: https://github.com/JuliaLang/Downloads.jl.git
Stdlib branch: master
Julia branch: master
Old commit: f97c72f
New commit: 246504e
Julia version: 1.11.0-DEV
Downloads version: 1.6.0(It's okay that it doesn't match)
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/Downloads.jl/compare/f97c72fbd726e208a04c53791b35cc34c747569f...246504e420fcdb5d28aad9945957f477a74f9671

```
$ git log --oneline f97c72f..246504e
246504e add a small precompile workload (#226)
3ed0f08 Document how to bypass the 20-second timeout (#222)
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @StefanKarpinski

**Comment by DilumAluthge** [comment]
@StefanKarpinski Any idea why the tests are failing?

```
FAILURE
--
  |  
  | The global RNG seed was 0xd8b03682a6081147698689331d8b70b1.
  |  
  | Error in testset NetworkOptions:
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/julia-1e7e80d143/share/julia/stdlib/v1.11/NetworkOptions/test/runtests.jl:72
  | Expression: ssh_known_hosts_file() == bundled
  | Evaluated: "/private/var/tmp/agent-tempdirs/default-honeycrisp-HL2F7YQ3XH.0/tmp/jl_ORKJOnAJiJ/known_hosts" == "/private/var/tmp/agent-tempdirs/default-honeycrisp-HL2F7YQ3XH.0/tmp/jl_zSOqaz"
  |  
  | Error in testset NetworkOptions:
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-master/julia-1e7e80d143/share/julia/stdlib/v1.11/NetworkOptions/test/runtests.jl:166
  | Expression: ssh_known_hosts_file() == bundled
  | Evaluated: "/private/var/tmp/agent-tempdirs/default-honeycrisp-HL2F7YQ3XH.0/home/.ssh/known_hosts" == "/private/var/tmp/agent-tempdirs/default-honeycrisp-HL2F7YQ3XH.0/tmp/jl_zSOqaz"
  |  
  | ERROR: LoadError: Test run finished with errors
```

**Comment by DilumAluthge** [comment]
@staticfloat Has anything changed on the Mac machines that might explain these test failures?

**Comment by DilumAluthge** [comment]
@staticfloat Could this be some kind of multiprocessing-unsafeness? E.g. maybe the NetworkOptions tests are not safe to run at the same time as other tests, and we need to add NetworkOptions to the "move to node 1" list?

**Comment by staticfloat** [comment]
I'm not aware of anything changing that would cause these failures.

**Comment by staticfloat** [comment]
It looks like Linux is failing as well, so perhaps this is just a bad commit?

**Comment by DilumAluthge** [comment]
Yeah, it's failing on all operating systems.

**Comment by vchuravy** [comment]
https://github.com/JuliaLang/Downloads.jl/pull/226 added a precompilation workload.

In NetworkOptions we have:
https://github.com/JuliaLang/NetworkOptions.jl/blob/976e51a48abb4e09356f1979c3cde8fbc0852e2e/src/ssh_options.jl#L147-L159

```
[46](https://mit-julialab.slack.com/archives/D053XD19UDS/p1694043975620029)
  | | |_| | | | (_| |  |  Version 1.9.1 (2023-06-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using NetworkOptions

julia> NetworkOptions.BUNDLED_KNOWN_HOSTS_FILE
Base.RefValue{String}(#undef)
```

after:

```
 _/ |\__'_|_|_|\__'_|  |  vc/libuv_lock/0761a665ae* (fork: 19 commits, 0 days)
|__/                   |

julia> using NetworkOptions

julia> NetworkOptions.BUNDLED_KNOWN_HOSTS_FILE
Base.RefValue{String}("/tmp/jl_CoSSi4")
```

So the precompilation workload calls `bundled_known_hosts()` which then means we cache the value of the Ref during serialization instead of letting it be undefined.

Diagnosed for #50880 since we will need to bump Pkg for a concurrency bug.

cc: @gbaraldi @KristofferC

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/JuliaLang/julia/pull/51246

**Pull request closed without merging**
