### PR TITLE
use NTuple as the representation of a CartesianIndex

### PR DESCRIPTION
**Pull request by JeffBezanson**
cc @timholy @mbauman @Jutho 
What should I run to make sure there are no performance regressions here?

### CODE REVIEW

**Comment by timholy** [comment]
:+1:. Use the new `perf/array` tests.

**Comment by Jutho** [comment]
+1

**Comment by JeffBezanson** [comment]
Great, ran the tests, examined with DataFrames, looks good.

**Comment by mbauman** [comment]
Awesome.

**Comment by mbauman** [comment]
Bonus :cake: for speeding up scalar SubArray indexing of small arrays by 6-8x.

**Comment by timholy** [comment]
I don't really understand how that's possible, but I'll take it! (An `NTuple` shouldn't be _better_ than a custom immutable.)

Overall I have the sense that the loss of regular perf testing means that we've kind of been bouncing around.

**Comment by IainNZ** [comment]
AFAIK a new machine has been ordered that we should be able to use for performance testing, so I'm hoping we can grind out (or at least identify) perf regressions before 0.4.0

**Comment by ScottPJones** [comment]
When will you get this new machine? (would that also be the machine for running PackageEvaluator?)
I'd be happy to do nightly runs on my MacPro, if that would help, until you get it (it's not in use at night anyway)

**Comment by jakebolewski** [comment]
Realistically I think end of August would be the soonest we can hope for.

**Pull request merged**
