### PR TITLE
Added test for Matrix(F::LU{T,Triadiagonal{T,V}})

### PR DESCRIPTION
**Pull request by ShriprajwalK**
Added test for https://codecov.io/gh/julialang/julia/src/master/stdlib/LinearAlgebra/src/lu.jl#L732

### CODE REVIEW

**Comment by dkarrasch** [comment]
Actually, could you find where the method one line above

https://codecov.io/gh/julialang/julia/src/master/stdlib/LinearAlgebra/src/lu.jl#L731

is tested, and add a single line to test the `Array` conversion? That would be great. Not sure we need six new lines for testing this simple conversion.

**Comment by dkarrasch** [comment]
Sorry, I wasn't being very clear. I meant to suggest to remove your entire new testset and to insert
```julia
@test Array(alu) == fa
```
after line 234 (and maybe also
```julia
@test Array(lud) ≈ d
```
after line 94) instead. That's a minimal change, and should do the job just as well.

**Comment by dkarrasch** [comment]
Ok, Windows failure is weird but common, and the additions are actually not imposing any new/independent tests, they just run by different methods and thereby cover them.

**Comment by ShriprajwalK** [comment]
Every PR recently made has failed for Windows for some reason.
Is there any change I should make for this PR?

**Pull request merged**
