### PR TITLE
Permit the construction of a 1D `StepRangeLen` of `CartesianIndex`es

### PR DESCRIPTION
**Pull request by jishnub**
This PR adds a  `CartesianIndex` constructor with `ndims`-matching `CartesianIndex` argument.

This allows constructing the following range:
```julia
julia> r = StepRangeLen(CartesianIndex(2,3), CartesianIndex(1,1), 10)
CartesianIndex(2, 3):CartesianIndex(1, 1):CartesianIndex(11, 12)

julia> collect(r)
10-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 3)
 CartesianIndex(3, 4)
 CartesianIndex(4, 5)
 CartesianIndex(5, 6)
 CartesianIndex(6, 7)
 CartesianIndex(7, 8)
 CartesianIndex(8, 9)
 CartesianIndex(9, 10)
 CartesianIndex(10, 11)
 CartesianIndex(11, 12)

```

### CODE REVIEW

**Comment by Seelengrab** [comment]
The wider discussion around how `CartesianIndex` is expected to behave in discussions like https://github.com/JuliaLang/julia/issues/43336 is likely related - not quite sure if this PR and the points discussed in that (and other issues linked within) are in conflict or not though.

**Comment by jishnub** [comment]
There is certainly some scope for ambiguity here, as the following will behave differently:
```
julia> range(CartesianIndex(1,1), step=CartesianIndex(1,1), stop=CartesianIndex(2,2))
CartesianIndices((1:1:2, 1:1:2))

julia> range(CartesianIndex(1,1), step=CartesianIndex(1,1), length=2)
CartesianIndex(1, 1):CartesianIndex(1, 1):CartesianIndex(2, 2)
```
However, a 1D range of `CartesianIndex`es is a vital cog in indexing into banded matrices, and the `StepRangeLen` constructor appears to be consistent here. Perhaps we may disallow using `range` in this case until a decision is reached?

**Comment by Seelengrab** [comment]
Yes that's a very good point - we'll likely have to decide one way or another at some point what we want the semantics to be. The core issue is in which direction that length ("hoe many steps to take") should be, i.e. whether a `CartesianIndex` is vector-like or not.

**Comment by jishnub** [comment]
Looking at [the history](https://github.com/JuliaLang/julia/commit/ba0add86fd8cc8bd3ba6fbc98d8b243c4c740b6d) of the colon constructor for `CartesianIndices`, it seems like this was added as a syntactic sugar, and not with properties of `CartesianIndex`es in mind. Given that `CartesianIndex`es obey all the axioms of a vector space, it'll be odd to not allow them to behave like vectors.

It seems like I had attempted a similar change in #41960, where the [decision](https://github.com/JuliaLang/julia/pull/41960#issuecomment-903604226) was the same: that `StepRangeLen` makes sense, but `range` is inconsistent and may be disallowed beyond the current behavior.

**Comment by jishnub** [comment]
I think that since `StepRangeLen <: AbstractRange <: AbstractVector`, the constructor should only return an object of that type (i.e. an `AbstractVector`), and not an n-D `CartesianIndices` hypercube. The ambiguity in the meaning of `range`  will probably persist, which is why it makes sense to disallow the `start-step-length` range method for `CartesianIndex`es.

**Comment by jishnub** [comment]
I've specialized `show` to display the `StepRangeLen` constructor:
```julia
julia> StepRangeLen(CartesianIndex(1, 2), CartesianIndex(3, 4), 2)
StepRangeLen(CartesianIndex(1, 2), CartesianIndex(3, 4), 2)
```

**Comment by jishnub** [comment]
Gentle bump

**Comment by jishnub** [comment]
Gentle bump @JeffBezanson

**Comment by jishnub** [comment]
Gentle bump

**Comment by jishnub** [comment]
Gentle bump

**Comment by jishnub** [comment]
Gentle bump, is there anything that remains to be done here?

**Comment by Seelengrab** [comment]
I think it's good now, I added the `triage` label since I wasn't sure that triage approves too. I'll bring it up next session if I have time to join.

**Comment by LilithHafner** [comment]
Triage already approved this.

**Comment by jishnub** [comment]
Thanks everyone!

**Comment by LilithHafner** [comment]
Thank you for bearing with us.

**Pull request merged**
