### PR TITLE
contrib: updated BBEdit/TextWrangler editor language syntax plist file for Julia 0.4

### PR DESCRIPTION
**Pull request by cormullion**
For ./contrib: updated BBEdit editor language syntax plist file for Julia 0.4.

Replaces #12861, which I screwed up in a significant number of ways...

### CODE REVIEW

**Comment by tkelman** [comment]
Looks pretty good so far, is there a script or did you do this by hand?

`@compat` isn't defined in base, maybe it's common enough that it should be recognized here though?

**Comment by cormullion** [comment]
@tkelman mostly cut and paste and sorted by hand, I seem to remember, after an initial loop through Base. Still, now it's done, it's done. :)

**Comment by tkelman** [comment]
If anyone else wants to review this, it's cleaner locally via
```
git fetch origin +refs/pull/15201/merge:
git show -w 5460f8d36f7efde35e21615e532ed9dd07d70368
```

**Comment by cormullion** [comment]
@tkelman thanks, Tony (or Heimdall, Guardian of AsGit. :))

**Pull request merged**
