### PR TITLE
WIP: Code coverage reports for base

### PR DESCRIPTION
**Pull request by ghost**
A long time ago I noticed [a comment by simonster about code coverage in base](https://github.com/JuliaLang/julia/issues/7095#issuecomment-44986625) and finally took a stab at it.  Little did I know that I ended up with almost exactly [what timholy hacked together several moons ago](https://github.com/JuliaLang/julia/commit/15c9ef3b5a4ddcce91b64d2464b9de9ff9c1d517).

I put the coverage as a separate entry in the build matrix on Travis and explicitly allow for it to fail in order not to slow down the Travis reports.  As a consequence of this we will only run coverage on Linux, but I suspect that this does not matter.

However, there are several issues to consider before merging something like this (thus the WIP).
1. Do we really want Coveralls notifications for all pull requests?
2. Is the current quality of the coverage reports good enough?

For 1., if it is not possible to disable them on the Coveralls dashboard I can tuck the coverage code and Coveralls submission as optional make targets that can be run upon request rather than on Travis.  As for 2., I hope that someone else has more insights into exactly what the current shortcomings of the coverage code is.

Another note on the WIP status, I am yet to fire off the script onto Travis and may push to this branch shortly if I messed something up.

### CODE REVIEW

**Comment by hayd** [comment]
Is this closed by #9493 ?

https://coveralls.io/r/timholy/julia

**Comment by IainNZ** [comment]
Wooah guys:
https://twitter.com/CoverallsApp/status/562351762049208320
https://github.com/lemurheavy/coveralls-public/issues/25#issuecomment-72526134

**Comment by staticfloat** [comment]
:D

**Comment by timholy** [comment]
I do think this is largely done, but I'm sure it could be set up to be a bit more convenient. Currently I have to manually push master to my fork of julia on a daily basis to keep Coveralls in sync with this repo.

However, keep in mind that you basically can't use Travis to generate accurate coverage reports. You hit the 50-minute timeout due to these requirements:
- turn off inlining
- run without the precompiled image file
- run all tests in a single process

So we can't do this as a byproduct of testing PRs, it has to be a separate pass. I think @staticfloat has been taking what I did in `CoverageBase.jl` and setting it up on his buildbots?

**Comment by hayd** [comment]
Having the badge on the README would be nice (I can never get these to work):
 
[Coverage Status](https://coveralls.io/r/timholy/julia)

(but perhaps you want to wait til it's "more respectable" :p)

**Comment by staticfloat** [comment]
I had things working a little while ago, but with the 32-bit failures the
tarballs haven't been getting built.  I'll try to make sure things are
working well by this weekend, as I love having coverage reports for Base!
-E

**Comment by tkelman** [comment]
We have buildbots for this now, closing. We aren't getting coverage reports for PR's since nothing in https://github.com/JuliaLang/julia/pull/8781#issuecomment-72831352 has changed, but given a bit of webhook scripting we could possibly do so on-demand if there ends up being a need for that.

**Comment by kshyatt** [comment]
The last part of https://github.com/JuliaLang/julia/pull/8781#issuecomment-72831352 is about to change once I can test this on linux I swear!!!

**Pull request closed without merging**
