### PR TITLE
Makefile: Use Clang CFLAGS when running `analyzegc`

### PR DESCRIPTION
**Pull request by topolarity**
I believe it's supported to build the analysis plugin with GCC, but the flags we actually run it with need to match Clang.

### CODE REVIEW

**Comment by topolarity** [comment]
Changed direction here.

Instead of removing support for building `analyzegc` with GCC, this updates the Makefile to use the Clang CFLAGS only when running Clang with the GC analyzer plugin.

**Review by staticfloat — APPROVED** [review]
I think I do actually like splitting the CFLAGS by compiler type

**Review by vtjnash — COMMENTED** [review]
SGTM

**Comment by inkydragon** [comment]
CI error seems related
*analyzegc*
```
make: Entering directory '/cache/build/default-amdci5-2/julialang/julia-master/src'
    ANALYZE src/clang-sa-llvm-pass-helpers
In file included from /cache/build/default-amdci5-2/julialang/julia-master/src/llvm-pass-helpers.cpp:8:
/cache/build/default-amdci5-2/julialang/julia-master/src/llvm-version.h:5:10: fatal error: 'platform.h' file not found
#include "platform.h"
         ^~~~~~~~~~~~
1 error generated.
```
https://buildkite.com/julialang/julia-master/builds/24396#01886e4e-9f55-48ef-be00-a2a0cfde28d5/846-982

**Comment by topolarity** [comment]
Should be passing CI now - Would be good to get a re-review from @staticfloat for the new changes

This scheme is not ideal, since by convention we update our JCFLAGs etc. in many places after they are initialized in `Make.inc`, but I think the important flag updates have all been included now.

**Pull request merged**
