### PR TITLE
another improvement to closure analysis precision

### PR DESCRIPTION
**Pull request by JeffBezanson**
This adds support for the case where an assignment dominates all uses, but there are intervening `if` blocks. Also simplifies the implementation a bit.

helps #15276 

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30972#issuecomment-460839104) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4fe03c5050193bbbe0987a3a03aab99062b26e96/6b65da8_vs_f52c911/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
There is a small memory regression in one of the io tests but I believe it is data-dependent. I'm able to get similar fluctuations locally for different random arrays.

**Comment by KristofferC** [comment]
Yes, it is known to fluctuate.

**Comment by JeffBezanson** [comment]
Ugh I found a crazy test case. goto ruins everything!! :stuck_out_tongue:

**Comment by vtjnash** [comment]
disable it if there's a gotolabel? 😜

**Comment by JeffBezanson** [comment]
Yeah, pretty much :)

**Pull request merged**
