### PR TITLE
move `dirname.c` from flisp/ to support/

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a general utility and not specifically part of flisp.

Need to make sure this works on windows and MSVC (to the extent possible).

### CODE REVIEW

**Comment by tkelman** [comment]
I haven't been maintaining the Windows.mk nmake files, I don't think they work. If we switch to cmake we can get rid of them. For now the easiest way to test against msvc is turning appveyor on on your fork and rebasing this branch: https://github.com/tkelman/julia/tree/tk/avmsvc

Note that the msvc llvm binaries are still against llvm 3.3. I don't have msvc on my new system yet, and upstream doesn't believe in including static libraries in their windows binary installer.

**Comment by JeffBezanson** [comment]
Ok, thanks. I will interpret that as "if this passes normal CI we can merge it" :)

**Comment by tkelman** [comment]
No, not quite. "If https://ci.appveyor.com/project/tkelman/julia/build/1.0.737 gets to bootstrap we can merge it." Which it didn't ```No rule to make target `/c/projects/julia/src/support/dirname.c.o', needed by `/c/projects/julia/src/support/libsupport.a'.  Stop.```

**Comment by JeffBezanson** [comment]
Ack, ok, I think I see my mistake there.

**Comment by tkelman** [comment]
Good call, cuz I didn't. If https://ci.appveyor.com/project/tkelman/julia/build/1.0.738 gets to bootstrap, then ok to merge.

**Comment by JeffBezanson** [comment]
AV failure is #14991

**Pull request merged**
