### PR TITLE
codegen: handle dead code with unsafe_store of FCA pointers

### LINKED ISSUE #50125: unsafe pointers with non-isbits may crash
This is dead code (generated by inference), but we should make sure codegen doesn't crash on it. The problem is we are trying to store an FCA, which is not directly quite legal.
```
(gdb) p jl_dump_llvm_value(src.V)
  %value_phi1 = phi { i32, {} addrspace(10)* } 
$10 = void
(gdb) p jl_(src.typ)
OpenTelemetryAPI.SpanStatus
$11 = void
```

https://github.com/oolong-dev/OpenTelemetry.jl/issues/80#issuecomment-1585539829

MWE:

```
julia> struct AA; a::Int; b::Union{Nothing,String}; end
julia> code_llvm((String,)) do x; unsafe_store!(Ptr{AA}(1), AA(0,x)); end
```

### PR DESCRIPTION
**Pull request by vtjnash**
Fix #50125

### CODE REVIEW

**Comment by vchuravy** [comment]
Can you add the tests from https://github.com/JuliaLang/julia/pull/50244

**Comment by NHDaly** [comment]
Cool, glad to see a fix coming up! :) 
Ah, funny timing that you were doing this at the same time as me.

**Comment by NHDaly** [comment]
Can you explain what's wrong with the tests in https://github.com/JuliaLang/julia/pull/50244?

This first one seems legal from what I understand:
```julia
# issue #50243
struct ImmutableNonIsBits
    v::Vector{Int}
end
const ref50243 = Ref(ImmutableNonIsBits([1,2,3]))
load50243() = unsafe_load(Ptr{ImmutableNonIsBits}(pointer_from_objref(ref50243)))
sum50243() = sum(load50243().v)  # (Do something with v to prevent the compiler from eliding)
@test load50243() === ref50243[]
@test sum50243() === 6
@test @allocated(sum50243()) === 0
```
Is this fundamentally different than doing the same trick with an isbits type, like an NTuple?

And i think this second one is possibly more illegal, but i'm not 100% clear why.
```julia
const ref50243 = Ref(ImmutableNonIsBits([1,2,3]))
store50243!(v2) = unsafe_store!(Ptr{ImmutableNonIsBits}(pointer_from_objref(ref50243)), v2)
new50243 = ImmutableNonIsBits([1])
store50243!(new50243)
@test ref50243[] === new50243
@test @allocated(store50243!(ref50243[])) === 0
```
... But neither of them pass on master - what makes you say that?

**Comment by vtjnash** [comment]
The first tests pass on master for me, except for the allocated bytes test which is not semantically guaranteed. The `unsafe_store!` has the wrong memory provenance for that, so it is UB. The first test also might have the wrong memory provenance, but it is only a read, so it is potentially unclear right now if that is legal or not.

**Comment by NHDaly** [comment]
Thanks, makes sense.

> The first tests pass on master for me, except for the allocated bytes test which is not semantically guaranteed.

^ Yeah, this is specifically what I was trying to test. Even though it's not semantically guaranteed, I assume that it's something we want to preserve in _our implementation_ of julia, which is why I thought it might be good to test.

But maybe the goal with the test suite is that it should pass under _any_ implementation of julia that follows the spec? Which does make sense 👍

**Comment by vtjnash** [comment]
It would likely fail currently under the interpreter and/or runtime implementations of this, so it is not an ideal test.

**Comment by NHDaly** [comment]
Thanks all.

----

One more question: should this be backported to 1.9? Since it's a bugfix? (It's _also_ a perf fix for `unsafe_load(::Ptr{<immutable>})`, and I think those aren't usually backported.) But it's also a bug fix for the case that crashes?

**Pull request merged**
