### PR TITLE
make tab width a kwarg instead of a global

### PR DESCRIPTION
**Pull request by tkelman**
ref #11719

### CODE REVIEW

**Comment by tkelman** [comment]
re: https://github.com/JuliaLang/julia/pull/11719#issuecomment-125910403 @ScottPJones 

what's the point in adding global state to `Base`'s namespace just for these two functions, when it's more flexible to just make it an optional part of the API?

**Comment by ScottPJones** [comment]
Because otherwise a user can't adjust it for their own preferences.
(although the standard is tabs stops being every 8 positions, many people set their editors to 4 space tabs).
Adding an argument, that isn't used in the REPL and LineEdit code, won't help with that at all.
This change is a loss of useful functionality, that other users had asked for.

**Comment by tkelman** [comment]
Users had asked for configurable tab widths in REPL bracketed paste? Can you point to that? I also agree with Stefan to a large extent that maybe we should be setting the default to 4, pasting at the Julia REPL should probably default to standard Julia formatting conventions.

**Comment by ScottPJones** [comment]
I'll try to find where it was that people asked for configurable tab widths.
I wouldn't have put it in otherwise, because I believe that *physical* tabs should always be at every 8 positions.

>I also agree with Stefan to a large extent that maybe we should be setting the default to 4, pasting at the Julia REPL should probably default to standard Julia formatting conventions.

Problem with that, is that stops at every 8 spaces *is* part of a number of standards.
Displaying 4 spaces (for the physical tab character) (or whatever the user set) is the shortcut used by editors that didn't take the time to implement smart indentation (bound to the tab *key*), that outputs the right number of tabs and spaces (or just spaces) to indent code correctly (based on the language).

This really is totally orthogonal to the standard Julia formatting conventions, you can always output the correct indentation level for Julia using either all spaces, or a combination of tabs and spaces.

**Comment by tkelman** [comment]
The only functional difference this change makes, and the only case in which it makes a difference whether the API for modifying the default value uses a global or a keyword argument, is for the specific use case of bracketed paste. I'll add a commit that requests an indentation of 4 there. Please limit future discussion here to only that use case - standards, editors, and tab characters are not particularly relevant there.

**Comment by ScottPJones** [comment]
>edit: And customization of this should go through the existing REPL customization mechanisms (which are admittedly a bit clunky right now), not a global integer in Base.

What are those mechanisms?  I agree, if there is another way of the user being able to customize their own setting for the size of a physical tab other than setting a global integer, it would be better.

>standards, editors, and tab characters are not particularly relevant there.
They are relevant to the discussion of changing the default from the standard 8 (see CSS and various ANSI standard languages), to 4.

**Comment by tkelman** [comment]
I had to look this up - ref https://github.com/JuliaLang/julia/blob/9b14a7ca1c8403fe3d72d7c1cb0fb26b32d12342/doc/manual/interacting-with-julia.rst#customizing-keybindings. I'm not positive if keybindings for existing bound sequences (like the bracketed-paste escape code) can be completely overwritten, but it's worth trying.

Copy-pasting the default REPL keybinding code and only changing the tab widths is not the greatest of workarounds, I'll admit that. But it would be good to see whether there's really any demand for customization of tab stops in bracketed paste. It seems like one of the least useful possible features, and worth leaving out to get rid of a global. It wasn't possible before #11719, and it hasn't been a source of complaints.

> changing the default from the standard 8

I'm only changing the default for pasting in the Julia repl. We can do whatever we want there.

**Comment by ScottPJones** [comment]
>Copy-pasting the default REPL keybinding code into your juliarc

What about LineEdit.jl?  I'm not sure where that is called, the code is identical to the code in REPL.jl.

For later, at least for the REPL, could something be added to the REPL state to set the width, nice and easy, instead of changing a key binding to code that then would easily get out of date?

Here is the first comment I found, about somebody wanting the tab width settable: https://github.com/JuliaLang/julia/issues/11659#issuecomment-110886100

@tkelman I'm not at all against removing the global, I just think there needs to be a better way than replicating a bunch of code in juliaarc, before doing so.

**Comment by tkelman** [comment]
This wasn't a feature that existed on master prior to #11719. I merged #11719 because I was tired of arguing with you. I have better things to do than worry about this, I'm sure you do too.

Markdown can use the functions and the keyword arguments, they're not using the REPL/LineEdit keybindings. I don't entirely understand why keybinding code is duplicated in both places there, but this really doesn't seem like it's worth having a global for, or continuing to argue about. Someone else can either merge this or close this if they care one way or another, but I'd rather have no more comments here from either of us.

**Comment by tkelman** [comment]
Scott sent me the following in a personal email.

====

You closed off discussion of #12369, but I’m afraid somebody will merge that, and it is a breaking change for people doing multiline pastes.

```
         @inbounds while out < len
         ch::UInt32 = dat[pos += 1]
         # Handle ASCII characters
             if ch <= 0x7f
```

This messes up the formatting quite a bit.

I thought you were going to leave changing the default form 8 -> 4 for another PR, but this changes it for everybody in a way that is very hard to work around.

I’m sorry that this annoys you, but this *is* something (cut and paste code into the REPL) that I’ve found quite useful, and I would like to see it handled well.
I think other people (like @ johnmyleswhite, since he opened Keno/REPL.jl#35), also find it useful.

====

A global variable is a lousy API. Always has been, always will be. But I really don't care enough to continue dealing with this.

**Comment by ScottPJones** [comment]
I agree a global variable is a lousy API.  Never disagreed.  I also sent you this:
>
I said I agreed that it would be better not to have a global,
there are many other globals of this sort though, like LOAD_PATH, DOCDIR, `_oldstyle_array_vcat_`, transposebaselength, `_default_splice`, bitcache_chunks, base64_pad, b64chars, etc.
I did not know a better way of handling the request for a settable default,
and nobody said there was a problem with having the default value in a global.

**Comment by ScottPJones** [comment]
Since this has been reopened, I will say that I think this is a fine change, except for the lines changed in `REPL.jl` and `LineEdit.jl`, which change the default used for REPL. (another separate PR with a better mechanism of setting the default instead of using a global would also be good, then it wouldn't matter really if the REPL default were changed, if a single simple line say in juliarc.jl could change it back to 8)

**Pull request merged**
