### PR TITLE
[release-0.4] backports for 0.4.7

### PR DESCRIPTION
**Pull request by tkelman**
@nanosoldier `runbenchmarks(ALL, vs = "@2e358ce975029ec97aba5994c17d4a2169c3b085")` vs v0.4.6

will also run pkgeval

(32 bit linux travis hit an intermittent failure due to a fixed-on-0.5 race condition during bootstrap, log backed up to https://gist.github.com/caa5dcd3cfd4af0081c79b6648926e1c and restarted)

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18478) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4a6506687f764ea94d6d7267bd879eb463a497a6/fcfca35_vs_2e358ce/report.md). cc @jrevels

**Comment by ViralBShah** [comment]
I was expecting just a couple of things in 0.4.7, but that is quite a handful of stuff.Nice!

**Comment by tkelman** [comment]
haven't put out an 0.4 release since just before juliacon, been focused on 0.5

**Comment by tkelman** [comment]
Mads and Mamba had a strange error with DualNumbers that may or may not be precompilation-related, NullableArrays had a DomainError that looks like a real issue: https://gist.github.com/f2cf4758c26675669fdeba881d628917

**Comment by vtjnash** [comment]
It's probably because precompile has poor support support right now for dealing with packages that drop a dependency (it starts trying to load the existing module, sees that it depends on a non-existant package, but then doesn't have a good solution for dealing with failure in this case)

**Comment by ViralBShah** [comment]
All these packages are in regular use on JuliaBox, so we do need to keep them all working.

**Comment by nkottary** [comment]
Ok, sure.

**Comment by tkelman** [comment]
Yeah I'd like to avoid repeatable regressions if we can. This issue with DualNumbers (also manifests with FileIO sometimes) has been seen before on PkgEval https://github.com/JuliaCI/PackageEvaluator.jl/issues/138 so a bit hard to tell if it's new here or intermittent. NullableArrays should be tested locally on this branch, and bisected if reproducible. The second to last commit here should have a build up on julianightlies if binaries helps.

**Comment by tkelman** [comment]
The NullableArrays issue looks like it's caused by this line https://github.com/JuliaStats/NullableArrays.jl/blob/v0.0.8/test/operators.jl#L81. For reasons I don't understand at all, https://github.com/JuliaLang/julia/commit/57d08348c5dc3a308abab1cd90c002d3f1c056c7 changed the results of random numbers, and that `v2 = rand(T)` when `T == Int8` hits `-128` on that commit or newer, and `abs(Int8(-128))` overflows to `-128` and hits a DomainError later.

**Comment by tkelman** [comment]
Re-ran pkgeval with basically no changes here. https://gist.github.com/3c01c5766474c9cc21520be63bd8df53

- DynamicDiscreteModels is flaky (ref http://pkg.julialang.org/detail/DynamicDiscreteModels.html), has a tolerance too tight
- Mamba had the same "module DualNumbers not found in current path," someone earlier in the same VM is probably doing something unreliable with hacky optional dependencies that causes this issue, but it passes locally when I run just Mamba by itself
- NullableArrays we worked around in https://github.com/JuliaStats/NullableArrays.jl/issues/146 - I still don't get why https://github.com/JuliaLang/julia/commit/57d08348c5dc3a308abab1cd90c002d3f1c056c7 changed the RNG results despite an `srand`
- ReverseDiffSource is flaky (ref http://pkg.julialang.org/detail/ReverseDiffSource.html), it fails intermittently

**Pull request merged**
