### PR TITLE
Use new caching server protocol

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by tkelman** [comment]
Should we start using this for `jldownload` too instead of manually mirroring various source tarballs?

**Comment by staticfloat** [comment]
That's the idea, but I wanted to take one step at a time.  The caching server should be able to support it now, we'd just need to change a line or two inside of `jldownload`.

**Comment by staticfloat** [comment]
This passed on OSX, so I'm calling it good.

**Comment by tkelman** [comment]
backported in https://github.com/JuliaLang/julia/commit/892fd029b2a75f24b08de98c4e51890def3bfe05

**Pull request merged**
