### PR TITLE
move development related functions to `PkgDev` package

### PR DESCRIPTION
**Pull request by wildart**
Remove development related functionality to a separate package [PkgDev](https://github.com/JuliaLang/PkgDev.jl)

### CODE REVIEW

**Comment by jakebolewski** [comment]
`PkgDev` should probably be put under the JuliaLang organization.

**Comment by jakebolewski** [comment]
@StefanKarpinski I believe you have that power .

**Comment by tkelman** [comment]
Yes, please put the package in place and make sure it's working, tested, registered, etc before removing the code from base.

**Comment by wildart** [comment]
I've transferred package to @StefanKarpinski

**Comment by wildart** [comment]
[PkgDev](https://github.com/JuliaLang/METADATA.jl/pull/3600) is ready.

**Comment by wildart** [comment]
Ready for merging.

**Comment by tkelman** [comment]
No, depends on https://github.com/JuliaLang/METADATA.jl/pull/3682 which depends on https://github.com/JuliaLang/METADATA.jl/pull/3601

**Comment by hayd** [comment]
should these be deprecated in 0.4.1 (?)

**Comment by tkelman** [comment]
No, not unless PkgDev.jl gets written to support the old git module on 0.4.

**Comment by wildart** [comment]
No, `git` will not be supported.

**Comment by tkelman** [comment]
all the docs need to be updated in the rst and moved, pkgdev should host static docs somewhere - rtd or mkdocs

**Pull request merged**
