### PR TITLE
Fix #38256 (lpad/rpad defined in terms of textwidth)

### LINKED ISSUE #38256: Should lpad/rpad be defined in terms of textwidth instead of code units or have the option to do so?
One of the main use cases of `lpad` and `rpad` is, at least for me personally, to align things in the terminal. However, `lpad` and `rpad` are defined (and documented) to work in terms of code units (i.e. they call `length` on the input string) which means that when `length` and `textwidth` disagree, you get unaligned output:

```
julia> s1 = "⟨k|H₁|k̃⟩"
"⟨k|H₁|k̃⟩"
julia> s2 = "⟨k|H₁|k⟩"
"⟨k|H₁|k⟩"
julia> textwidth(s1), textwidth(s2)
(8, 8)
julia> rpad(s1, 12) |> textwidth
11
julia> rpad(s2, 12) |> textwidth
12
```

This can cause bugs like https://github.com/KristofferC/TimerOutputs.jl/issues/94.

Two points of discussions:

- Should the default be changed to use `textwidth` instead of `length`? Perhaps too much of a breaking change.
- Should there be an option to use `textwidth`, e.g. with a kwarg?

### PR DESCRIPTION
**Pull request by mimame**
Fix #38256 (lpad/rpad defined in terms of textwidth)

Julia is awesome and I hope to be useful :blush:

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Great, thanks! This should have a NEWS entry since it could technically change the behavior of some code.

**Comment by JeffBezanson** [comment]
Also the doc string needs to be changed, since it says the function pads in terms of code points.

**Comment by mimame** [comment]
Hi @JeffBezanson, I'm really sorry by the delay and I hope the fix still can be backported to the 1.6 release :disappointed: 
I've updated the doc and added the entry in the NEWS.md file
Don't hesitate to require more changes I promise to pay attention

**Comment by oscardssmith** [comment]
This is definitely too late to backport to 1.6. We're already in RC2. Glad this change is getting made though.

**Comment by StefanKarpinski** [comment]
It would be great to have this finished. It still needs a compat entry explaining that the behavior changed in 1.7 and the NEWS conflict needs to be fixed. Otherwise it looks good to go. Very close!

**Comment by stevengj** [comment]
Added the compat annotation and fixed the merge conflict.

**Review by stevengj — APPROVED** [review]

**Comment by vtjnash** [comment]
something going wrong with this? seeing this fail sometimes on master:
https://build.julialang.org/#builders/1/builds/4447
```
Error in testset Tar:
Error During Test at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.7/Tar/test/runtests.jl:879
  Got exception outside of a @test
  DivideError: integer division error
  Stacktrace:
    [1] div
      @ ./int.jl:278 [inlined]
    [2] divrem
      @ ./div.jl:162 [inlined]
    [3] divrem
      @ ./div.jl:158 [inlined]
    [4] lpad(s::String, n::Int64, p::String)
      @ Base ./strings/util.jl:352
    [5] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.7/Tar/test/runtests.jl:910 [inlined]
    [6] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
    [7] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.7/Tar/test/runtests.jl:881 [inlined]
    [8] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
    [9] top-level scope
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.7/Tar/test/runtests.jl:872
   [10] include
      @ ./Base.jl:417 [inlined]
   [11] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:24 [inlined]
   [12] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
   [13] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:23 [inlined]
   [14] macro expansion
      @ ./timing.jl:368 [inlined]
   [15] runtests(name::String, path::String, isolate::Bool; seed::UInt128)
      @ Main /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:21
   [16] (::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278
   [17] run_work_thunk(thunk::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:63
   [18] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278 [inlined]
   [19] (::Distributed.var"#105#107"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed ./task.jl:411
```

**Comment by giordano** [comment]
This is causing problems also for me in strings sent over MPI, where I do want the `length` size, not the `textwidth` size

**Comment by StefanKarpinski** [comment]
Oh, interesting. That's a very inefficient way to send a string but yes, you would want length there.

**Comment by GordStephen** [comment]
I'm seeing a similar issue where a fixed-length `Vector{Char}` needs to be padded with null bytes. I'll manually pre-`fill` and copy the chars, but a fallback for zero-width padding strings/chars would be nice.

**Pull request merged**
