### PR TITLE
build: cleanup base files inclusion

### LINKED ISSUE #31140: Out of tree builds fails to copy base julia files
Running  the julia  installer after running `make -C outdir binary-dist` from cygwin for a windows build.

`share/julia/base` only includes the files:
image

### PR DESCRIPTION
**Pull request by vtjnash**
Ensures the out-of-tree build has the correct src files installed for the base image, and simplifies some of the `include`s used in Base.

Fixes https://github.com/JuliaLang/julia/issues/31140

### CODE REVIEW

**Comment by vtjnash** [comment]
I will assume people are okay with this, and take review comments afterwards if not

**Comment by Keno** [comment]
I don't really understand what the point of moving the files from `usr/share/julia/base` to `usr/share/julia/src/base` is? That seems like a completely random directory structure.

**Comment by vtjnash** [comment]
It sort of is random, in that the alternate versions I tried seemed to have more problems with make or Revise getting confused. I didn't really want to nest them this way for any design reason.

**Comment by Keno** [comment]
Revise is very confused right now :).

**Comment by timholy** [comment]
Revise is fixable (see https://github.com/timholy/Revise.jl/pull/694), but it would be worth knowing whether this change is going to be reconsidered. I wouldn't choose an unfortunate directory structure in a (failed) attempt to keep Revise happy, I'd rather see this solved as it should be and Revise can adapt accordingly.

**Comment by timholy** [comment]
Quick thoughts from @vtjnash? Should we change this directory organization or should I merge https://github.com/timholy/Revise.jl/pull/694?

**Comment by staticfloat** [comment]
I would very much like to change the directory structure. This change confuses not just Revise but also VSCode, grep, and other tools.

**Comment by pfitzseb** [comment]
The directory *structure* is probably fine, but symlinking `user/share/julia/src/base` to `src/base` makes sense imo.

**Comment by timholy** [comment]
I'll hold off on the Revise change then. I'll also defer to others in implementing the change since everyone involved in this conversation has a better sense for what needs to be done than me. We'll update Revise when it's done. (@pfitzseb feel free to just modify your PR and merge it whenever you wish.)

**Pull request merged**
