### PR TITLE
codegen improvements

### PR DESCRIPTION
**Pull request by vtjnash**
No significant functional changes, just small cleanups

### CODE REVIEW

**Comment by vtjnash** [comment]
Added a pass to optimize this pattern, as it seemed likely to be fast (though probably not especially frequent):
```julia
f(x) = x ? (1, 2, 3) : (1, 2, 3)
```
```llvm
julia> @code_llvm optimize=true f(true)
define void @f_master([3 x i64]* noalias nocapture sret, i8) {
top:
  %2 = and i8 %1, 1
  %3 = icmp eq i8 %2, 0
  %4 = bitcast [3 x i64]* %0 to i8*
  br i1 %3, label %L3, label %L2

L2:                                               ; preds = %top
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 %4, i8* align 16 bitcast ([3 x i64]* @0 to i8*), i64 24, i1 false)
  ret void

L3:                                               ; preds = %top
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 %4, i8* align 16 bitcast ([3 x i64]* @1 to i8*), i64 24, i1 false)
  ret void
}

define void @ f_PR([3 x i64]* noalias nocapture sret, i8) {
top:
  %2 = bitcast [3 x i64]* %0 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 %2, i8* align 16 bitcast ([3 x i64]* @0 to i8*), i64 24, i1 false)
  ret void
}
```

**Comment by maleadt** [comment]
Nice, thanks! For those following along (@vchuravy), we can now return tagged objects (what used to be impossible due to the `jl_value_t`->`jl_value_t.0` rename):

```
julia> f() = Base.llvmcall("ret {} addrspace(10)* undef", Any, Tuple{})
f (generic function with 1 method)

julia> code_llvm(f, Tuple{})

define nonnull {}* @julia_f_1209() {
top:
  ret {}* undef
}
```

This will obviate some uses of `llvmcall(llvm::Function*)`.

Doesn't even require use of LLVM's IRLinker and it's type equivalence machinery to merge these together, although that might still be a useful change that might allow us to get rid of our custom FunctionMover.

**Review by maleadt — APPROVED** [review]
LGTM (Although I can't actually test with a GPU compiler since master is currently unsupported for other reasons)

**Comment by vtjnash** [comment]
Discovered I needed to add "llvm.used" because of that pass for Win64, but otherwise should be good

**Pull request merged**
