### PR TITLE
Minor English fixes + 1 semantic change

### PR DESCRIPTION
**Pull request by mark-summerfield**
Most of the info. seems to refer to Unix-like systems. Surely Windows users ought to be better catered for, esp. regarding paths?

I have no idea what the word 'decimation' means; at least not in this context. (I only know it to mean 'wipe-out' or 'destroy'.)

There's no `open` command on Windows that I know of, so I changed that to `start`.

The info. on JULIA_LLVM_ARGS seems incomplete.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
> There's no `open` command on Windows that I know of, so I changed that to `start`.

I'm sure you're right about that, but as far as I can tell we don't actually use `start` as the default editor on windows, so maybe we should change our implementation as well?

**Comment by vtjnash** [comment]
`start` doesn’t exist on windows either. We intercept calls to “open” and ask the shell (meaning shell32.dll, and completely unrelated to he usual meaning of the word shell) to execute the “open” verb. Calling the batch processor built in function “cmd /c start” gives a similar result. IIRC though, the actual command line application for handling this verb is explorer.exe.

**Comment by mark-summerfield** [comment]
In Windows 7 and 10 if you write "start filename.ext" in a console providing there's an association to a .exe (or .com etc.) for .ext, Windows will run that executable with the filename as its argument.

**Comment by Keno** [comment]
There's two different notions here. The `shell32`, `open` command and the `cmd` `start` command. The former basically corresponds to a double click, while the latter works as documented in the `cmd` docs. They mostly agree, but since we picked the former and intercept it, that part of this change is incorrect. I'll roll the remaining changes with minor tweaks into #34424.

**Pull request closed without merging**
