### PR TITLE
Throw ArgumentError for negative array dimensions and added test

### LINKED ISSUE #32307: Array allocation with negative size should throw a `ArgumentError` not a `ErrorException`
```
julia> try 
       fill('a', -10)
       catch err
       @show typeof(err)
       end

typeof(err) = ErrorException
```

### PR DESCRIPTION
**Pull request by dnabanita7**
Fix #32307

### CODE REVIEW

**Comment by Naba7** [comment]
I don't understand why this buildbot/tester_macos64 is failing ? Please help

**Comment by musm** [comment]
Looks like it just timed out, happens occasionally.

**Comment by Naba7** [comment]
I guess its ready to be merged.

**Comment by Naba7** [comment]
@StefanKarpinski @mbauman Is it good?

**Comment by StefanKarpinski** [comment]
Yes, it's great. Thanks for the contribution and congrats on your first PR!

**Pull request merged**
