### PR TITLE
Bump LLVM to include additional patch.

### PR DESCRIPTION
**Pull request by maleadt**
Specifically, https://github.com/llvm/llvm-project/pull/91334, which LLVM.jl needs to use the internalize pass on NewPM.

### CODE REVIEW

**Comment by giordano** [comment]
I think you need to update the tools like clang and lld?

**Comment by maleadt** [comment]
> I think you need to update the tools like clang and lld?

I didn't rebuild those, only LLVM_full/LLVM_asserts_full and libLLVM_jll. Are you saying we should rebuild those as well? The patch included here does extend the pass pipeline syntax that you can use with `opt` or `clang`, but in practice it won't matter (as it will only be used by LLVM.jl via libLLVM).

**Comment by giordano** [comment]
I believe the standard procedure is to rebuild all llvm-related packages to keep consistent numbers anyway. @gbaraldi @vchuravy can you please clarify the process?

**Comment by gbaraldi** [comment]
We usually rebuild everything yes

**Pull request merged**
