### PR TITLE
sort/sort! for Generators

### PR DESCRIPTION
**Pull request by bramtayl**
A little test: 

```julia
rows = [(number = 2, name = "two"), (number = 1, name = "one")]
@test sort(row.number for row in rows) == [(number = 1, name = "one"), (number = 2, name = "two")]
sort!(row.number for row in rows)
@test  rows == [(number = 1, name = "one"), (number = 2, name = "two")]
```

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This seems like a rather bad idea to me... at least the `sort!` version is.

**Comment by nalimilan** [comment]
Also if we support `sort` on generators, better support it for any iterable (and collect to a `Vector` by default).

**Comment by bramtayl** [comment]
Ok, what about sort(f, v::AbstractArray) instead

**Comment by JeffBezanson** [comment]
That's what the `by` keyword argument to sort is for.

**Comment by bramtayl** [comment]
Doh

**Pull request closed without merging**
