### PR TITLE
Address part of #28866, prevent array operations from dropping 0d containers

### LINKED ISSUE #28866: 0-dimensional array becomes scalar after broadcast
```julia
julia> map(typeof, (zeros(), ones(), fill(3.14)))
(Array{Float64,0}, Array{Float64,0}, Array{Float64,0})

julia> typeof(ones() .* fill(3.14))
Float64

julia> typeof(zeros() + ones())  # in fact not only after broadcast
Float64
```

Is it a bug, or a feature?

### PR DESCRIPTION
**Pull request by mbauman**
This is a simple workaround for the handful of elementwise operations that are defined on arrays _without_ the need for explicit broadcast but use broadcasting (with an extra shape check) in their implementation. These were the only affected cases I could find.

This is restoring the intended behavior, and matches the behavior of Julia pre-0.7.  It is a fairly impactful change, though, so even though I'd call it a bugfix we probably want to be conservative in our backporting.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Seems reasonable. I think whatever you end up deciding here is good, @mbauman.

**Comment by mbauman** [comment]
Failures were real and stemmed from the fact that LinearAlgebra specialized `broadcast` for adjoint/transposed vectors but didn't hook into the broadcast machinery.  I initially tried to start addressing the root cause and move the specializations to the equivalent `copy(::Broadcasted{...})` methods, but that ended up with effective ambiguities between this behavior and SparseArray's PromoteToSparse style.  It'd be good to address this in the future but I wanted to keep this change as minimal as possible.  So see #32289 for that change.

**Comment by StefanKarpinski** [comment]
Look at all those green checks 😁

**Comment by mbauman** [comment]
I say we do this.

**Pull request merged**
