### PR TITLE
fix DEPOT_PATH in cmdlineargs

### PR DESCRIPTION
**Pull request by clouds56**
It would randomly failed if test `loading` and `cmdlineargs` run in the same worker.

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by clouds56** [comment]
Sorry, didn't realize https://github.com/JuliaLang/julia/pull/46602 has been merged, but this still prevent the test case from being affected by randomly introduced `startup.jl`

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
Thanks for making this PR!

I don't think this is necessary after #46602.

**Comment by DilumAluthge** [comment]
> but this still prevent the test case from being affected by randomly introduced `startup.jl`

In `Base.runtests()`, we set a temporary `JULIA_DEPOT_PATH` before we run the tests. So none of the tests should be affected by a `startup.jl` file in the user's depot.

**Comment by DilumAluthge** [comment]
@clouds56 Would you mind making a separate PR with just the fix from line 989 of `test/loading.jl`? Even though it's not strictly necessary, it would be nice to fix that typo.

**Pull request closed without merging**
