### PR TITLE
Fix #8193, take 2.

### LINKED ISSUE #8193: IOBuffer allows seeking to before beginning
This code from iobuffer.jl does not check whether n is non-negative:
```
function seek(io::IOBuffer, n::Integer)
    !io.seekable && (!ismarked(io) || n!=io.mark) && error("seek failed")
    io.ptr = min(n+1, io.size+1)
    return io
end
```
Also -- why is the position given in a zero-based measure?

### PR DESCRIPTION
**Pull request by kmsquire**
Cc: @jakebolewski, @ivarne

### CODE REVIEW

**Comment by kmsquire** [comment]
Finally got back to this.  Fixed, rebased, tests pass locally.

@vtjnash suggested [here](https://github.com/JuliaLang/julia/pull/8229#issuecomment-54592066) that seek to a nonexistent location (negative or past the end of a file) should be an argument error.  

However, if I make that an error, I get an error in REPL.jl [here](https://github.com/JuliaLang/julia/blob/1d4e75283ebcec815ef79efd3fca25360648289c/base/REPL.jl#L780), which suggests that that line is attempting to seek past the end of the buffer.

@mbauman, @Keno, is the calculation in that line correct?

**Comment by kmsquire** [comment]
This fixes an issue, so even though the implementation isn't ideal, I'm going to merge, and open up a new issue for the remaining part.

**Comment by tkelman** [comment]
This has had the backport pending label on it for a very long time, but only recently got merged to master. Can we get a more up-to-date opinion on whether / when this should should still be backported? The pace of changes that apply to release-0.3 has slowed dramatically (a good sign that there's a serious need to finalize decisions on what will go into 0.4 and when we change from 0.4-dev to 0.4-pre).

**Comment by kmsquire** [comment]
Well, it does fix #8193.  It's unlikely anyone has actually hit that bug, but it is incorrect behavior, and it does exist on v0.3.

I would have preferred #8229/#10582, but was never motivated enough to dig into the REPL code blocking that, and never got a response to my queries about that code.

**Comment by stevengj** [comment]
Before this is backported, please look into #10658.

**Comment by stevengj** [comment]
Seems like it should be `n < 0 && return seek(io, seekto-1)`.  But I don't know why `skip` returns an error for skipping backwards on a `!seekable` stream, but not for skipping forwards — it seems oddly inconsistent.  Shouldn't it call `seek` for either sign of `n` or for neither?

**Comment by vtjnash** [comment]
skipping forwards on a non-seekable stream is equivalent to a discarded read, so it is legal

**Comment by stevengj** [comment]
Unfortunately, this bug seems to have propagated elsewhere in Base in the last few days, e.g. f73ee0f5a66355f653396894621bc72beeea1c2a

**Comment by tkelman** [comment]
Given that we're approaching an rc fairly soon for 0.4, I'm removing the backport pending label here and on anything else that has had that label in a "maybe if someone makes a PR to fix the conflicts" state.

**Pull request merged**
