### PR TITLE
Fix MSVC compilation

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
Corrected a typo in the comment, rebased and also fixed the out-of-date comment about codegen steps. Will merge after CI is done again.

**Comment by tkelman** [comment]
It seems to have gotten mad again? Something since 62615c374d348a72f000e956cddb0a7864b2a471, possibly rearranged includes?
```
llvm-gcroot.cpp
c:/projects/julia/src/llvm-gcroot.cpp(221) : error C2039: 'function' : is not a member of 'std'
c:/projects/julia/src/llvm-gcroot.cpp(221) : error C2065: 'function' : undeclared identifier
c:/projects/julia/src/llvm-gcroot.cpp(221) : error C2275: 'hdlr_iter_t' : illegal use of this type as an expression
        c:/projects/julia/src/llvm-gcroot.cpp(216) : see declaration of 'hdlr_iter_t'
c:/projects/julia/src/llvm-gcroot.cpp(221) : error C2065: 'process_handler' : undeclared identifier
c:/projects/julia/src/llvm-gcroot.cpp(260) : error C3861: 'process_handler': identifier not found
c:/projects/julia/src/llvm-gcroot.cpp(303) : error C3861: 'process_handler': identifier not found
make[1]: *** [llvm-gcroot.o] Error 2
```

**Comment by yuyichao** [comment]
Seems that the error is just missing `std::function`. According to [cppreference](http://en.cppreference.com/w/cpp/utility/functional/function) `<functional>` is the only header that needs to be included so I'm not sure how it can stop working.....

**Comment by tkelman** [comment]
Nevermind, my mistake, I thought I was rebasing onto your llvm33 test-fix branch but must've removed a few too many commits or something. False alarm, sorry.

**Pull request merged**
