### PR TITLE
Sparse NEWS.md Update

### PR DESCRIPTION
**Pull request by rayegun**
Not sure how to call out PR numbers now that they're in an external repo?

### CODE REVIEW

**Comment by DilumAluthge** [comment]
> Not sure how to call out PR numbers now that they're in an external repo?

Per https://github.com/JuliaLang/julia/blob/master/HISTORY.md, display them as ORG/REPO.jl#PRNUMBER

**Comment by DilumAluthge** [comment]
You can Control-F https://github.com/JuliaLang/julia/blob/master/HISTORY.md for "JuliaIO/Tar.jl" to find examples.

**Comment by Wimmerer** [comment]
I need to block to be sure this matches some changes just made to the repo

**Comment by KristofferC** [comment]
@Wimmerer, good to go?

**Comment by Wimmerer** [comment]
Now yes

**Pull request merged**
