### PR TITLE
Make Refs fully container-like

### PR DESCRIPTION
**Pull request by mbauman**
Give them iteration and all the associated behaviors surrounding iteration and indexing.

### CODE REVIEW

**Comment by vtjnash** [comment]
I'm a little hesitant to give Ref all of these properties, because I don't know what the unintended side-effects might be for adding these methods to all of the subtypes, such as Ptr, but I suppose the best way to find out is to try it.

**Review by vtjnash — APPROVED** [review]

**Comment by Keno** [comment]
Ptr being a subtype of Ref really does make me uncomfortable about this though. Should iteration on a pointer automatically dereference that ptr? Surely not? Is there anything to be gained with this over just defining this for the subtypes of Ref that need it (`RefValue` in particular and maybe `RefArray`).

**Comment by vtjnash** [comment]
Yes, it's either the ABI for `Ref` or it isn't. There's no "ABI for RefValue" in the language currently, so it would be weird to add this as a special case.

This also doesn't magically cause it to start dereferencing pointers, it just changes which MethodError would get thrown.

**Comment by mbauman** [comment]
So are we game to give this a shot?  The major impetus here is so that user-code can reason about what `broadcast` is gonna do with arbitrary/unknown arguments just by checking its `axes`.

**Comment by andyferris** [comment]
I like the idea here, at least for the managed reference types.

I actually wonder if pointers and refs maybe should support different interfaces... pointers support `unsafe_load` and so-on and refs support `getindex` and so-on. To me, the type tree is there to represent interfaces, yet we have `Ptr <: Ref`.

**Comment by JeffBezanson** [comment]
Needs to be updated for the new iteration protocol.

**Comment by mbauman** [comment]
Bump.  Shall we try this?

**Comment by StefanKarpinski** [comment]
Yes, I think we should.

**Pull request merged**
