### PR TITLE
Update OpenBLAS to v0.3.5

### PR DESCRIPTION
**Pull request by ararslan**
Note that we're currently using v0.3.3 and this PR goes directly to the newest version, v0.3.5. See the release notes for both 0.3.4 and 0.3.5 for a more complete summary of the changes: https://github.com/xianyi/OpenBLAS/releases.

@staticfloat, we'll need some kind of BinaryBuilder magic for this as well, right? How do?

### CODE REVIEW

**Comment by vchuravy** [comment]
I think the right place is https://github.com/JuliaPackaging/Yggdrasil/tree/master/OpenBLAS

**Comment by staticfloat** [comment]
I've started a build of `v0.3.5`; we'll see what's broken this time around.  ;)

**Comment by ViralBShah** [comment]
We should increase the number of MAX THREADS to 40 or perhaps even 64 (on x86-64).

https://github.com/JuliaPackaging/Yggdrasil/blob/2b1576aeb8cdac4e783bd35f58e77fad97c09225/OpenBLAS/build_tarballs.jl#L46

**Comment by vtjnash** [comment]
We set that option low because it seemed to improve performance on small matrices and limits virtual memory usage (iirc, it reserves 256MB * MAX_THREADS). We can reconsider (esp. if OpenBLAS is improved now to initialize this lazily), but that should be a separate PR.

**Comment by ViralBShah** [comment]
Yes, but the flip side now is that people complain they have bigger machines and Julia does not use all the cores.

**Comment by ViralBShah** [comment]
The small matrix performance is driven by the gemm threshold (which is 50, so multi-threading is not used for smaller matrices). The main driver was memory when we did that change in 2013. I say that core counts and memories have grown enough that doubling the max threads now should be ok (ideally only on linux x86-64).

**Comment by ViralBShah** [comment]
From the openblas 0.3.4 release notes:

OpenBLAS will now provide enough buffer space for at least 50 threads by default.

I am sure we override this with our setting.

**Comment by staticfloat** [comment]
BB tarballs are good to go.

@ViralBShah let's open a separate issue, do some performance measurements, then decide the new value to default to.

**Review by staticfloat — APPROVED** [review]

**Comment by ViralBShah** [comment]
Yes, agree that the max threads should not hold up the version update.

**Comment by ararslan** [comment]
Thanks for taking care of the BinaryBuilder stuff, Elliot!

**Comment by ararslan** [comment]
Travis macOS is trying to build GCC from source which filled up the max log length so Travis killed the build.

**Comment by ararslan** [comment]
The macOS failure should be fixed by #30599.

**Comment by andreasnoack** [comment]
There might be some important bug fixes in the latest release https://github.com/JuliaLang/julia/issues/30460#issuecomment-451930128

**Comment by staticfloat** [comment]
Sure, we could revert back to 0.3.3 (0.3.4 won't build on all our platforms) but there are some nice things to have in 0.3.5, lots of bugs fixed, so it's better IMO to disable a few optimized kernels instead.

**Comment by ViralBShah** [comment]
I've been trying to find a reproducible test case for https://github.com/xianyi/OpenBLAS/issues/1955

The openblas failure is strange. On skylake, the tests that fail in `triangular`, if I run them on the command line, they are fine. Perhaps some buffer overruns somewhere in openblas?

**Pull request merged**
