### PR TITLE
RFC: move FastISel <= -O1

### LINKED ISSUE #16375: Integer division by 2 is 6x slower with FastISel
The following code is slightly modified from my answer to http://stackoverflow.com/questions/37193586/bigints-seem-slow-in-julia (a solution for Project Euler problem 78), a memoized calculation of number of partitions of integers.

(I don't guarantee that it is a correct solution but) I do see a **3-fold slowdown** from 0.4.5 to 0.5:

https://gist.github.com/bc07c76f6330799595f6f41fb0380307

0.4.5:    10.695675 seconds (5 allocations: 192 bytes)
0.5.0-dev+4088:    33.703394 seconds (5 allocations: 192 bytes)

### PR DESCRIPTION
**Pull request by vtjnash**
fix #16375, but need to see what effect this would have on travis times

### CODE REVIEW

**Comment by vtjnash** [comment]
I've found the `int.jl` test to be pretty visibly compile-time driven in a short test. The following seem to be pretty representative to me (where the only difference between -O1 and -O2 is FastISel):
```julia
~/julia/test$ ../build-llvm37/usr/bin/julia -O3 runtests.jl int
     * int                   in   4.80 seconds, maxrss  222.41 MB
    SUCCESS
~/julia/test$ ../build-llvm37/usr/bin/julia -O2 runtests.jl int
     * int                   in   4.77 seconds, maxrss  222.25 MB
    SUCCESS
~/julia/test$ ../build-llvm37/usr/bin/julia -O1 runtests.jl int
     * int                   in   4.60 seconds, maxrss  222.99 MB
    SUCCESS
~/julia/test$ ../build-llvm37/usr/bin/julia -O0 runtests.jl int
     * int                   in   3.74 seconds, maxrss  219.98 MB
    SUCCESS


~/julia/test$ ../usr/bin/julia -O3 runtests.jl int
     * int                   in   3.28 seconds, maxrss  208.89 MB
    SUCCESS
~/julia/test$ ../usr/bin/julia -O2 runtests.jl int
     * int                   in   3.13 seconds, maxrss  208.38 MB
    SUCCESS
~/julia/test$ ../usr/bin/julia -O1 runtests.jl int
     * int                   in   3.11 seconds, maxrss  208.75 MB
    SUCCESS
~/julia/test$ ../usr/bin/julia -O0 runtests.jl int
     * int                   in   2.59 seconds, maxrss  206.73 MB
    SUCCESS
```

**Comment by vtjnash** [comment]
AppVeyor restarted, but so far it doesn't look like CI is looking favorable

**Comment by vtjnash** [comment]
restart run of AppVeyor seemed to have better performance, so I've restarted both CI workers again to see if it seems repeatable

**Comment by JeffBezanson** [comment]
LLVM's normal ISel must have lots of assertions --- with assertions enabled the tests are close to 2x slower than before locally. Even without assertions there is a big slowdown on my machine, even though it doesn't seem to affect CI that much.

**Pull request merged**
