### PR TITLE
Backports for 1.10.1

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #51095 
- [x] #52583 
- [x] #52645 
- [x] #52423 
- [x] #52721 
- [x] #52637 
- [x] #52752 
- [x] #52758 
- [x] #51375 
- [x] #52994 
- [x] #53015 
- [x] #53032 
- [x] #52748 
- [x] #52856 
- [x] #52878
- [x] #52754 
- [x] #52228
- [x] #52924
- [x] #52569 
- [x] #52605 
- [x] #52618 
- [x] #52781 
- [x] #53055 
- [x] #53096 
- [x] #53076 
- [x] #52841 
- [x] #52078 
- [x] #53035 
- [x] #53066 
- [x] #52996 
- [x] #53121 

Non-merged PRs with backport label:
- [ ] #52694 
- [ ] #51479

### CODE REVIEW

**Comment by aviatesk** [comment]
Looks like this branch isn't rebased against the latest `release-1.10` branch?

**Comment by KristofferC** [comment]
Thanks, should be fixed.

**Comment by PallHaraldsson** [comment]
Can we backport the public keyword? https://github.com/JuliaLang/JuliaSyntax.jl/pull/320/files And does that simply mean using a later/st JuliaSyntax.jl version? It seem annoying to have to use `@compat`, and would not help adoption of the new keyword:  https://github.com/JuliaLang/Compat.jl/pull/805 I would be ok with supporting it in the same way, as no-op in 1.10.1.

**Comment by PallHaraldsson** [comment]
Also backport #52762 (it fixes a bug, and e.g. better for Apple M1, can be 2.8x faster)?!

**Comment by imciner2** [comment]
> Also maybe backport https://github.com/JuliaLang/julia/pull/52577#top from 7.2.1?

IMO, no, this isn't backportable. The JLL for 7.4.0 was built with a Julia 1.11 compat entry, so the JLL won't install on 1.10 right now.

> I suppose the bar is fixing a bug and the only I see are in v7.2.2:
>
>>    CHOLMOD 4.2.2: minor bug fix to CHOLMOD/Supernodal when determining the # of OpenMP threads to use for assembling values into the last supernode (nthreads). The resulting nthreads is valid, just perhaps not optimal for this last supernode.

We don't build with OpenMP, so I don't see this bugfix as being useful for us.

> And I'm not sure it fixes a bug (that applies), this in 7.4:
>
>>    CHOLMOD 5.1.0: full support for sparse single precision matrices, bug fixes in the GPU Module.

The SparseArrays.jl wrappers (and underlying SuiteSparse solver wrappers) don't support any of the single-precision parts yet.

> but of interest:
>
>>    SuiteSparseLAPACK.cmake: allow the use of BLIS/FLAME for LAPACK

This is a build system change, and the SuiteSparse we use is already built against LBT, so you can try BLIS/FLAME by setting the redirects in LBT appropriately in 7.2.1 that we already ship in 1.10.

**Comment by IanButterworth** [comment]
Notable failures:

REPL
```
  | REPL                                              (6) \|         failed at 2024-01-07T10:51:33.489
  | Test Failed at /cache/build/tester-amdci5-12/julialang/julia-release-1-dot-10/julia-5c0a2a61cb/share/julia/stdlib/v1.10/REPL/test/replcompletions.jl:683
  | Expression: occursin("test(args...)", c[1])
  | Evaluated: occursin("test(args...)", "test11(a::Integer, b, c) @ Main.CompletionFoo /cache/build/tester-amdci5-12/julialang/julia-release-1-dot-10/julia-5c0a2a61cb/share/julia/stdlib/v1.10/REPL/test/replcompletions.jl:102")
  |  
  | Test Failed at /cache/build/tester-amdci5-12/julialang/julia-release-1-dot-10/julia-5c0a2a61cb/share/julia/stdlib/v1.10/REPL/test/replcompletions.jl:684
  | Expression: occursin("test11(a::Integer, b, c)", c[2])
  | Evaluated: occursin("test11(a::Integer, b, c)", "test(args...) @ Main.CompletionFoo /cache/build/tester-amdci5-12/julialang/julia-release-1-dot-10/julia-5c0a2a61cb/share/julia/stdlib/v1.10/REPL/test/replcompletions.jl:72")
```

NetworkOptions
```
  | NetworkOptions                                    (4) \|         failed at 2024-01-16T05:53:45.557
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-5.0/build/default-macmini-x64-5-0/julialang/julia-release-1-dot-10/julia-aaaf5de5e6/share/julia/stdlib/v1.10/NetworkOptions/test/runtests.jl:72
  | Expression: ssh_known_hosts_file() == bundled
  | Evaluated: "/private/var/tmp/agent-tempdirs/default-macmini-x64-5.0/tmp/jl_BoDIFcvqZ4/known_hosts" == "/private/var/tmp/agent-tempdirs/default-macmini-x64-6.0/tmp/jl_19mCzs"
  |  
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-5.0/build/default-macmini-x64-5-0/julialang/julia-release-1-dot-10/julia-aaaf5de5e6/share/julia/stdlib/v1.10/NetworkOptions/test/runtests.jl:166
  | Expression: ssh_known_hosts_file() == bundled
  | Evaluated: "/private/var/tmp/agent-tempdirs/default-macmini-x64-5.0/home/.ssh/known_hosts" == "/private/var/tmp/agent-tempdirs/default-macmini-x64-6.0/tmp/jl_19mCzs"
```

**Comment by imciner2** [comment]
Is the OpenBLAS 0.3.26 backport possible? We have it configured with a Julia compat of 1.11 in the Yggdrasil build recipe, so I don't think the JLL will be compatible with Julia 1.10 unless we do another change in Yggdrasil first. @giordano thoughts on this?

**Comment by giordano** [comment]
Dunno, compatibility can be fixed in the registry, that isn't a big deal, I don't mind but I think in the past other devs weren't excited about backporting upgrades of JLLs, although OpenBLAS is a pretty stable package.

**Comment by KristofferC** [comment]
This looked like a simple patch update to a JLL. Why is there a julia version dependency on it?

**Comment by giordano** [comment]
> This looked like a simple patch update to a JLL.

https://github.com/OpenMathLib/OpenBLAS/compare/v0.3.23...v0.3.26

> Why is there a julia version dependency on it?

Because jlls need to specify julia compat like any other package?  And we usually put as compat the julia version where we expect that build to be used, but the registry can be fixed if necessary, it isn't a problem.

**Comment by KristofferC** [comment]
> And we usually put as compat the julia version where we expect that build to be used,

Naively, it seems better to put it for the lowest julia version where it can be used. Anyway, I'll drop it for now.

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52755#issuecomment-1908374674) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6fdf37e_vs_0ba6ec2/report.html) is available.

**Comment by oscardssmith** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/7202 is merged so we now should be able to update openblas. this is pretty important because it fixes issues on M1 chips and fixes the cutoff point for gemv using multiple threads which previously could case a ~100x regression on chips with many cores.

**Comment by imciner2** [comment]
> https://github.com/JuliaPackaging/Yggdrasil/pull/7202 is merged so we now should be able to update openblas. this is pretty important because it fixes issues on M1 chips and fixes the cutoff point for gemv using multiple threads which previously could case a ~100x regression on chips with many cores.

It is the OpenBLAS@0.3.23+2 package specifically that should be backported directly to this branch (that PR did merge both the 0.3.26 for current master and the update for 0.3.23 for here).

**Comment by jaakkor2** [comment]
This branch does not compile on Cygwin on Windows without https://github.com/JuliaLang/julia/pull/51698

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52755#issuecomment-1927648855) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/0627076_vs_0ba6ec2/report.html) is available.

**Pull request merged**
