### PR TITLE
Update curl to 7.51.0, mpfr to 3.1.5

### PR DESCRIPTION
**Pull request by tkelman**
As mentioned in #19135, and moving the mpfr bit here too since that wasn't causing the libgit2 issue that's holding up that PR. Hopefully this won't cause issues, though I don't think we have tests for Pkg through proxies currently (#17916).

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is there a reason to upgrade curl? Why not leave it as it is unless there is a reason? That way we may not need to worry about proxies and such.

**Comment by aviks** [comment]
There are apparently security fixes for curl.

**Comment by ViralBShah** [comment]
But wouldn't they make those available in a patch release?

**Comment by tkelman** [comment]
No. See the upcoming-release announcement linked from the other PR. Any time there's a CVE we really need to upgrade asap. Some linux distros may backport the patches to try to get stability and fix the security bugs, but then they're building from code that doesn't really match any upstream release.

If we want to claim that we support proxies without it regressing then it needs to be tested on CI.

**Pull request merged**
