### PR TITLE
Make var and std work for Vector{Vector{T}}

### LINKED ISSUE #23884: std() and var() do not work on array of arrays while mean() does
Hello, I wonder why I cannot use `std()` or `var()` on an array of arrays while I can do so for `mean()`.

Consider this simple example:
```julia
julia> x = [[2,4,6],[4,6,8]]
2-element Array{Array{Int64,1},1}:
 [2, 4, 6]
 [4, 6, 8]

julia> mean(x)
3-element Array{Float64,1}:
 3.0
 5.0
 7.0

julia> std(x)
ERROR: MethodError: no method matching zero(::Type{Array{Int64,1}})
Closest candidates are:
  zero(::Type{Base.LibGit2.GitHash}) at libgit2/oid.jl:106
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:82
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:124
  ...
Stacktrace:                                                                                                                                                                                                       
 [1] #var#533(::Bool, ::Void, ::Function, ::Array{Array{Int64,1},1}) at ./statistics.jl:184                                                                                                                       
 [2] (::Base.#kw##var)(::Array{Any,1}, ::Base.#var, ::Array{Array{Int64,1},1}) at ./<missing>:0                                                                                                                   
 [3] std(::Array{Array{Int64,1},1}) at ./statistics.jl:244                                                                                                                                                        
 [4] macro expansion at ./REPL.jl:97 [inlined]                                                                                                                                                                    
 [5] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73   
```
The version information is
```julia
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Pentium(R) CPU  N3530  @ 2.16GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, silvermont)
```
I find it strange that the one function is possible to give the intended outcome while the other end up with an error. Is this the desired behavior? Have I missed something?

I would say that exactly the same interpretation as for the `mean()` function should be used for `std()` and `var()`. I am aware of the possibility of a multidimensional array and direction argument to `std()` but this does not explain why it works out so nicely for `mean()`.

I came across this while using DataFrames with arrays as elements of the DataArray but the problem seams to be much more general.

Maybe there are other ways to do this?

### PR DESCRIPTION
**Pull request by andreasnoack**
by removing Number restriction from some signatures as well as using broadcasting in `std`.

I'd also like to do something similar for `cov` but hit the issue that `broadcast` is not doing the right thing for `Vector{Vector{T}}`. E.g.
```julia
julia> x = [[2,4,6],[4,6,8]];

julia> x .- [1,1,1]
ERROR: DimensionMismatch("arrays could not be broadcast to a common size")
Stacktrace:
 [1] _bcs1 at ./broadcast.jl:69 [inlined]
 [2] _bcs at ./broadcast.jl:63 [inlined]
 [3] broadcast_shape at ./broadcast.jl:57 [inlined]
 [4] broadcast_indices at ./broadcast.jl:49 [inlined]
 [5] broadcast_c at ./broadcast.jl:310 [inlined]
 [6] broadcast(::Function, ::Array{Array{Int64,1},1}, ::Array{Int64,1}) at ./broadcast.jl:434
```
Do we have an issue for that?

Fixes #23884

### CODE REVIEW

**Comment by DNF2** [comment]
Does this not go in the opposite direction to the strategy of not auto-vectorizing functions?

Why not just use: `std.(x)` and `cov.(x)`? It seems odd that `std` should support vectors of vectors, since `v^2` and `sqrt(v)` makes no sense for vectors.

**Comment by andreasnoack** [comment]
> Why not just use: `std.(x)` and `cov.(x)`? 

It is not the same thing.
```julia
julia> x = [[2,4,6],[4,6,8]];

julia> var(x)
3-element Array{Float64,1}:
 2.0
 2.0
 2.0

julia> var.(x)
2-element Array{Float64,1}:
 4.0
 4.0
```
You can compute the variance of a vector. In Julia, we have decided that it is just the diagonal of the covariance matrix. The standard deviation is a bit tricky, though. It could either be the diagonal of the matrix square root of the covariance matrix or the element wise square root of the diagonal of the covariance matrix. This PR uses the latter definition.

**Comment by mschauer** [comment]
@DNF2 The empirical covariance is a function which maps a collection of equal-length vectors to a matrix (this involves the outer product `v*v'`, not on `v^2`). In order to work on arrays it interprets the array as collection of vectors (therefore the `vardim` argument, as there are two possible interpretations of a matrix as vector of vectors). `std.( )` does something entirely different (computing many standard deviations)

**Comment by DNF2** [comment]
Hm. In #23884 I guess I misread the answer to
> What do you expect to get?

probably because the example vectors was so similar. I thought the request was to auto-broadcast.

Thanks for the explanation.

**Comment by mschauer** [comment]
> broadcast is not doing the right thing 

Cases like this could be caught in the signature, right? E.g.
```
julia> Vector{Vector} <: S where {S<:AbstractVector{T}} where {T<:AbstractVector}
true
```
but maybe it is better to fix that at the root.

**Comment by TotalVerb** [comment]
@andreasnoack We do have an issue for it: https://github.com/JuliaLang/julia/issues/18379

**Comment by andyferris** [comment]
I have to admit, I find this a bit surprising. I'm trying to put my finger on it - but I think that it has something to do with the fact the the properties of `Vector`s *as objects* obey certain change-of-basis relationships. The examples above seem to be some kind of automatic element wise thing (no, not `var.(...)` but something else) and is definitely basis dependent. 

If you were to ask me what I thought the "variance" of a set of vectors was, I would answer the covariance or it's determinant or the RMS L2 distance from the mean, not some element wise calculation. The covariance works generically with number as `sum(v*v' for v in vecs)` and last one like `sum(v'*v for v in veces)` (ignoring mean).

**Comment by mschauer** [comment]
Returning the "diagonal of the covariance matrix" is basically component-wise application of the var function. So that is a case of automatic broadcasting which is not easily expressed in dot operations for `Vector{Vector}`s (also not easily expressed in other implicit form, e.g. `var.(collect(zip(vectors...)))` is not so nice)

**Comment by andreasnoack** [comment]
I'd also prefer that covariance matrix but we have kind of already made the decision since
```julia
julia> X = randn(10,2);

julia> var(X, 1)
1×2 Array{Float64,2}:
 0.69424  0.894716
```
whereas
```julia
julia> cov(X, 1)
2×2 Array{Float64,2}:
  0.69424    -0.0762704
 -0.0762704   0.894716
```

**Comment by bramtayl** [comment]
This seems like a job for a zip-like iterator.

**Comment by andreasnoack** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23897#issuecomment-333489989) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/102a65791ff59c68ab1fef982c1c4964511b9f03/71548e8_vs_149f785/report.md). cc @ararslan

**Comment by mbauman** [comment]
I just discovered this — it seems quite strange to me.  How are we defining `var`?  Is it not just `sum(abs2, v - mean(v)) / (length(v) - 1)`?  Why are we defining `abs2(v::Vector) = abs2.(v)`?

**Comment by mbauman** [comment]
Ok, after discussing this more with Andreas, I'm on board with the behaviors here… but we might want to look into updating the docstring… and possibly moving away from broadcasting.  Basically, `cov([[1,2,3],[4,5,6]])` is a well-defined operation based upon multiplication of the transpose — that works just fine for vectors of vectors.  And the variance can be defined as the diagonal of the covariance matrix.

Moreover, this is an operation that is good to support because we implicitly do it with `var(X, 1)` — that's effectively `var([X[:,1],X[:,2],…])`.

[Using broadcasting here](https://github.com/JuliaLang/julia/pull/23897/files#diff-b85f81409a2a21f2174ccb078b0d7030R122) still tastes a little funny to me, because it is effectively imposing `diag(X*X') == abs2.(X)` for all types.  If a collection were to support broadcasting and addition/subtraction (but not multiplication), should we still use this same definition?

**Pull request merged**
