### PR TITLE
Fix getindex inlining for Array{Union{T,Missing}}

### PR DESCRIPTION
**Pull request by nalimilan**
Fixes https://github.com/JuliaLang/julia/issues/27403.

With this PR, a naive sum over non-missing values in a `Vector{Union{Int,Missing}}` is (probably) as fast as it could theoretically be. Masked SIMD instructions are used, which is almost too good to be true.
```julia
function mysum(X)
    s = zero(eltype(X))
    @inbounds @simd for x in X
        if x !== missing
            s += x
        end
    end
    s
end

X1 = rand(Int, 10_000_000);
X2 = Vector{Union{Missing,Int}}(X1);
X3 = ifelse.(rand(length(X2)) .< 0.9, X2, missing);

julia> @btime mysum(X1);
  5.787 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);
  5.726 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  5.844 ms (1 allocation: 16 bytes)
```

I've added a test to check that `getindex` is inlined, but I'm really not sure that's the best way to do it. There are also benchmarks for this in BaseBenchmarks, and I'll add another one (EDIT: see https://github.com/JuliaCI/BaseBenchmarks.jl/pull/207).

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by davidanthoff** [comment]
I get slightly different numbers, in particular the ``X1`` case is faster than the other two (which kind of makes sense?):
````
julia> @btime mysum(X1);
  4.812 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);
  5.757 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  5.753 ms (1 allocation: 16 bytes)
````

**Comment by nalimilan** [comment]
Yes, the particular run I posted was a bit extreme. The one I added to the blog post is more similar to yours. I have no idea why it changed.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27651#issuecomment-398576589) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ca8bf6d3add5508f878f73255d9b142229f944b1/e1cb0d5_vs_b331c70/report.md). cc @ararslan

**Comment by nalimilan** [comment]
Some probably spurious regressions, lots of `Union`-related improvements (about 2×-3×), and some very dramatic speedups. This one is particularly nice:

ID | time ratio | memory ratio
-- | -- | --
["union", "array", "(\"perf_sum\", Int8, true)"] | 0.04 (15%) | 1.00 (1%)

**Pull request merged**
