### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by tkelman** [comment]
needs to be done in helpdb too

**Comment by eschnett** [comment]
@tkelman This typo does not exist in `base/doc/helpdb.jl`.

I see that this branch consists of 7 commits -- this should not be. I used the Github web interface to make this change, and something may have gone wrong. Only the last commit of this branch (13e9720) should be applied.

**Comment by jakebolewski** [comment]
@eschnett unfortunately we lost the ability to update documentation through the online editor with the recent documentation reorg.  See CONTRIBUTING.md for the hoops you now have to go through to do this.

**Comment by yuyichao** [comment]
It appears that this is something missing in the helpdb.jl doc. The (unindented) paragraph should belong to the doc of `eachindex(A...)` but is not included in the helpdb doc...

**Comment by eschnett** [comment]
How can it be missing in one of two places? Do we need to keep two separate places in sync when making changes? I thought one of them was generated automatically. Puzzled.

**Pull request closed without merging**
