### PR TITLE
Fix performance bug for `*` with `AbstractQ`

### LINKED ISSUE #800: Two performance problems with the Q in QR factorizations
```julia
n = 300
B = randn(n, n)
D = Diagonal(ones(n))
F = qr(randn(n, 1))
@time F.Q * B # Works as expected
@time F.Q * D # Slow
@time F.Q * I # Slow
@time F.Q[:, :] # Slow
```
gives
```
  0.000505 seconds (4 allocations: 705.734 KiB)
  0.251926 seconds (270.00 k allocations: 448.380 MiB, 10.12% gc time)
  0.246129 seconds (270.00 k allocations: 448.380 MiB, 7.77% gc time)
  0.239383 seconds (270.01 k allocations: 448.380 MiB, 8.09% gc time)
```

There seems to be two problems
1) Multiplying various matrix types with `QRCompactQ`.
The same issue was reported for multiplication with `UniformScaling` in JuliaLang/LinearAlgebra.jl#758.
I guess the solution is to define the proper methods. Perhaps this would also fix JuliaLang/LinearAlgebra.jl#801.
2) `getindex` for  `QRCompactQ`
This problem could be solved by defining the `getindex` method properly.
A bonus would be that one could use `F.Q[:,:]` to retrieve the full `Q`, rather than the cumbersome `F.Q*Matrix(I,m,m)` as suggested in the docstring. 

For problem 2., the following method seems to work for me, but I guess it needs further consideration and testing.
```julia
function getindex(Q::Union{AbstractQ,Adjoint{<:Any,<:AbstractQ}}, ind1, ind2)
    if ind2 isa Colon
        ind2 = 1:size(Q,2)
    end

    X = zeros(eltype(Q), size(Q,1), length(ind2))
    for (j,i) in enumerate(ind2)
        X[i,j] = 1
    end

    lmul!(Q, X)
    
    if ind2 isa Integer
        return X[ind1, 1]
    else
        return X[ind1, :]
    end
end
```
Perhaps it would also be good to have
```julia
getindex(Q::Union{AbstractQ,Adjoint{<:Any,<:AbstractQ}}, ::Colon, ::Colon) = lmul!(Q, Matrix{eltype(Q)}(I, size(Q)))
```

If the above methods are introduced it seems like the existing method,
```julia
function getindex(Q::AbstractQ, i::Integer, j::Integer)
    x = zeros(eltype(Q), size(Q, 1))
    x[i] = 1
    y = zeros(eltype(Q), size(Q, 2))
    y[j] = 1
    return dot(x, lmul!(Q, y))
end
```
could be removed.

### LINKED ISSUE #38972: Two performance problems with the Q in QR factorizations
```julia
n = 300
B = randn(n, n)
D = Diagonal(ones(n))
F = qr(randn(n, 1))
@time F.Q * B # Works as expected
@time F.Q * D # Slow
@time F.Q * I # Slow
@time F.Q[:, :] # Slow
```
gives
```
  0.000505 seconds (4 allocations: 705.734 KiB)
  0.251926 seconds (270.00 k allocations: 448.380 MiB, 10.12% gc time)
  0.246129 seconds (270.00 k allocations: 448.380 MiB, 7.77% gc time)
  0.239383 seconds (270.01 k allocations: 448.380 MiB, 8.09% gc time)
```

There seems to be two problems
1) Multiplying various matrix types with `QRCompactQ`.
The same issue was reported for multiplication with `UniformScaling` in #37102.
I guess the solution is to define the proper methods. Perhaps this would also fix #38974.
2) `getindex` for  `QRCompactQ`
This problem could be solved by defining the `getindex` method properly.
A bonus would be that one could use `F.Q[:,:]` to retrieve the full `Q`, rather than the cumbersome `F.Q*Matrix(I,m,m)` as suggested in the docstring. 

For problem 2., the following method seems to work for me, but I guess it needs further consideration and testing.
```julia
function getindex(Q::Union{AbstractQ,Adjoint{<:Any,<:AbstractQ}}, ind1, ind2)
    if ind2 isa Colon
        ind2 = 1:size(Q,2)
    end

    X = zeros(eltype(Q), size(Q,1), length(ind2))
    for (j,i) in enumerate(ind2)
        X[i,j] = 1
    end

    lmul!(Q, X)
    
    if ind2 isa Integer
        return X[ind1, 1]
    else
        return X[ind1, :]
    end
end
```
Perhaps it would also be good to have
```julia
getindex(Q::Union{AbstractQ,Adjoint{<:Any,<:AbstractQ}}, ::Colon, ::Colon) = lmul!(Q, Matrix{eltype(Q)}(I, size(Q)))
```

If the above methods are introduced it seems like the existing method,
```julia
function getindex(Q::AbstractQ, i::Integer, j::Integer)
    x = zeros(eltype(Q), size(Q, 1))
    x[i] = 1
    y = zeros(eltype(Q), size(Q, 2))
    y[j] = 1
    return dot(x, lmul!(Q, y))
end
```
could be removed.

### PR DESCRIPTION
**Pull request by dkarrasch**
This fixes a major regression discovered in https://github.com/JuliaLang/LinearAlgebra.jl/issues/800 in multiplication of `Q` times `Diagonal` (and other structurally sparse matrices). The reason was that these "sparse" matrices took precedence, however assuming that the other factor was easily indexable. In older versions, `Q*D = rmul!(copyto!(Matrix{}(undef, size(Q)), Q), D)`, so we sped up `copyto!` for `Q`s. Recently (in the v1.8 cycle) we defined diagonal multiplication by 3-arg `mul!`, thus avoiding the copy. But now multiplication fell back to scalar indexing, in this case to performance hell. So, in this PR we teach Julia that in the case of two special matrices, `Q`should take precedence, and the other factor should by densified, since the result will be dense anyway.

Closes JuliaLang/LinearAlgebra.jl#800.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Performance results following the issue to be closed:

```julia
using LinearAlgebra, BenchmarkTools
n = 300
M = rand(n,n);
dl = ones(n-1);
d = ones(n);
D = Diagonal(d);
Bi = Bidiagonal(d, dl, :L);
Tri = Tridiagonal(dl, d, dl);
Sym = SymTridiagonal(d, dl);
F = qr(ones(n, 1));
A = F.Q';
for A in (F.Q, F.Q'), B in (M, D, Bi, Tri, Sym)
  @btime $B*$A
  @btime $A*$B
end
```
yields
```julia
133.003 μs (3 allocations: 705.67 KiB)
  143.650 μs (3 allocations: 705.67 KiB)
  127.117 μs (3 allocations: 705.67 KiB)
  139.770 μs (3 allocations: 705.67 KiB)
  130.832 μs (3 allocations: 705.67 KiB)
  139.763 μs (3 allocations: 705.67 KiB)
  131.360 μs (3 allocations: 705.67 KiB)
  139.343 μs (3 allocations: 705.67 KiB)
  131.962 μs (3 allocations: 705.67 KiB)
  139.792 μs (3 allocations: 705.67 KiB)
  131.476 μs (3 allocations: 705.67 KiB)
  143.652 μs (3 allocations: 705.67 KiB)
  143.366 μs (3 allocations: 705.67 KiB)
  140.696 μs (3 allocations: 705.67 KiB)
  130.995 μs (3 allocations: 705.67 KiB)
  139.819 μs (3 allocations: 705.67 KiB)
  131.542 μs (3 allocations: 705.67 KiB)
  140.390 μs (3 allocations: 705.67 KiB)
  131.729 μs (3 allocations: 705.67 KiB)
  140.411 μs (3 allocations: 705.67 KiB)
```
including the latest `copyto!` improvements, which avoid reading out the many structural zeros.

**Comment by ararslan** [comment]
CI failures:
- Linux x86: Out of memory, which I think has been common for this builder
- macOS x64: LibGit2 failures related to `master` vs. `main` branch naming
- Windows x86: Something weird with profiling

All unrelated to this PR but I'm always wary of backporting things that fail CI.

**Comment by dkarrasch** [comment]
Thanks for checking. I understand your concern, but the regression that is fixed here is horrible. I don't think we want to release v1.8 with that performance trap.

**Comment by ViralBShah** [comment]
Maybe we can wait for a couple of days for this to get better here to make sure it is good, and then merge, so that it can also be backported?

**Comment by ararslan** [comment]
The macOS failure has been fixed on master, so that at least would likely be fixed here with a rebase.

**Comment by ViralBShah** [comment]
I think this is good to merge - the 32-bit CI seems to be having trouble.

**Comment by odow** [comment]
This broke JuMP's tests because it's not the case that `Diagonal{T,Vector{T}}` can be converted to a `Matrix{T}`.

Here's what used to happen:
```Julia
julia> using JuMP, LinearAlgebra

julia> model = Model();

julia> @variable(model, x[1:2])
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> D = Diagonal(x)
2×2 Diagonal{VariableRef, Vector{VariableRef}}:
 x[1]  ⋅
 ⋅     x[2]

julia> Matrix(D)
2×2 Matrix{AffExpr}:
 x[1]  0
 0     x[2]
```
Note the promotion in element type from `VariableRef` to `AffExpr`. This happens when `zero(T) isa T` is false.

Now we get
image

cc @blegat

**Comment by dkarrasch** [comment]
Thanks for the quick report!!! I'm very sorry about that. I overlooked the special type promotion in `diagm`. I think I have a fix and maybe even a test to guard against this issue.... alright, JuMP tests pass locally with my fix!

**Comment by odow** [comment]
Thanks for the fix!

**Pull request merged**
