### PR TITLE
mention ++, per discussion at #11686

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by tkelman** [comment]
I'd rather not even mention string concatenation here at this point, and just say that packages are free to provide their own implementations for the `++` operator now.

**Comment by StefanKarpinski** [comment]
This is the danger: people are going to start using `++` and then that code is going to break if Base defines a meaning for `++`. That's why there was resistance to adding this note.

**Comment by waldyrious** [comment]
While that's technically true, it can't be denied that the only reason this operator was added was in the sequence of that discussion. Pretending otherwise would be fooling ourselves IMO. In any case, I can't imagine Base implementing anything too different from string concatenation based on this operator (it wouldn't make sense given the history of discussions that led to its inclusion), so any potential breakage would be in implementation details, rather than entirely different functionality.

**Comment by quinnj** [comment]
Yeah, I'm still not feeling the need to document this, I think it may lead to more trouble than it's worth.

**Comment by waldyrious** [comment]
Update, for future reference: @JeffBezanson has removed the bit about string concatenation in 500ecf6.

**Pull request merged**
