### PR TITLE
Simplify Appveyor build script

### PR DESCRIPTION
**Pull request by musm**
`@staticfloat` agreed we should try to simplify the build script to a minimum.

I've tried to remove as many unnecessary steps and tried to simplify things as much as possible.

### CODE REVIEW

**Comment by KristofferC** [comment]
An alternative way of simplifying it is to delete it.

**Comment by ViralBShah** [comment]
Why delete it? Because the new CI instructure is adequate and effort is best spent on improving the new stuff?

**Comment by musm** [comment]
this is ready for review

**Comment by KristofferC** [comment]
> Why delete it? Because the new CI instructure is adequate and effort is best spent on improving the new stuff?

We are already running windows CI on the build bots.

**Comment by musm** [comment]
cc @staticfloat for review

**Review by staticfloat — APPROVED** [review]
Looks reasonable to me, and it's a good sign that it passes on Appveyor!

**Comment by musm** [comment]
thanks for the review. Yes it seems fairly robust on my fork

**Comment by musm** [comment]
someone want to merge 😃

**Pull request merged**
