### PR TITLE
Bump to openlibm v0.5 and openspecfun v0.5

### PR DESCRIPTION
**Pull request by ViralBShah**
Bump openlibm and openspecfun versions. This is primarily to run all the tests in CI, and upstream versions will be tagged if everything passes. This PR will then be updated to then use the released upstream versions.

### CODE REVIEW

**Comment by tkelman** [comment]
openspecfun does not get built from source on windows, so appveyor may be misleading. The final version of this will need to update the `NO_GIT` checksum files as well.

**Comment by ViralBShah** [comment]
What is the NO_GIT checksum and how do I generate it?

**Comment by tkelman** [comment]
The files under `deps/checksums`. Should be something like `make -C deps NO_GIT=1 configure-openlibm configure-openspecfun`, then `git add` the new versions' checksums and `git rm` the old. Best to let CI finish since the checksums may need to change for final anyway.

**Comment by ViralBShah** [comment]
Tests pass for me on mac. Some linalg tests crashed, but that is unrelated to this PR.

**Comment by tkelman** [comment]
So, passed, or crashed? Some details of what you mean by "crashed" would be useful.

**Comment by ViralBShah** [comment]
How do I generate the new checksums?

**Comment by nalimilan** [comment]
I think you should do `make NO_GIT=1 -C deps configure-openlibm configure-openspecfun` (but after changing the tags to v0.5.0 to adapt to the change I just made).

**Comment by nalimilan** [comment]
Oops, I see you did that already. Simply call `sha1sum` on the tarballs?

**Comment by ViralBShah** [comment]
I haven't done anything yet.

**Comment by tkelman** [comment]
closing in favor of #16421

**Pull request closed without merging**
