### PR TITLE
merge unions of vararg tuples

### LINKED ISSUE #54746: suboptimal subtyping: tuple types vs unions of tuple types
```julia-repl
julia> Tuple <: Union{Tuple{},Tuple{Any,Vararg}}
false

julia> Tuple{Any,Vararg} <: Union{Tuple{Any},Tuple{Any,Any,Vararg}}
false

julia> versioninfo()
Julia Version 1.12.0-DEV.692
Commit 77c28ab286f (2024-06-09 07:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-17.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Would it be possible to teach Julia that the unions on the RHSs are equivalent to their LHSs?

### PR DESCRIPTION
**Pull request by simeonschaub**
Normalize unions such as `Union{Tuple{}, Tuple{T}, Tuple{T, T,
Vararg{T}}` to `Tuple{Vararg{T}}`. This should make certain sutyping
queries more precise.

fixes #54746

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by oscardssmith** [comment]
should this get an Inference benchmark run to make sure it doesn't cause any regressions?

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master"`

**Comment by simeonschaub** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55123#issuecomment-2237453016) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0821240_vs_d563231/report.md).

**Pull request merged**
