### PR TITLE
inlining: Use `tmeet` on inserted `PiNode` types for extended lattices

### PR DESCRIPTION
**Pull request by topolarity**
For extended lattice elements, the type of the resulting PiNode can end up imprecise when `tmeet(argextype(argex), mft) ⊑ mft`

That said, it's not entirely clear to me what our `IR_FLAG_REFINED` obligations are in the first place. Are we supposed to mark any statements that are widened past what inference would have seen? If so, it seems like we fall far short of that.

### CODE REVIEW

**Comment by Keno** [comment]
I don't know if this makes sense. The type was not refined in the base lattice. I think the external absint may want to set this itself when doing the lattice extension.

**Comment by topolarity** [comment]
In the case I hit this, we're running with an extended optimizer lattice where the input to the PiNode is already an extended element, so that the new type we insert does not end up being a subtype.

**Review by Keno — APPROVED** [review]

**Review by aviatesk — APPROVED** [review]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/54105#issuecomment-2065739265) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/247addb_vs_7f8635f/report.md).

**Comment by aviatesk** [comment]
The benchmark looks fine.

**Pull request merged**
