### PR TITLE
randperm throws bound error if n equals 0

### PR DESCRIPTION
**Pull request by dovahcrow**

### CODE REVIEW

**Comment by ivarne** [comment]
It still throws for negative `n`

**Comment by ivarne** [comment]
We should also add test cases for this, so that a refactoring doesn't change the edge case results.

**Comment by doomsplayer** [comment]
@ivarne 
n may equals to 0 in some edge cases, for example, when parsing an empty CSV file and randomizing it.
But n can never be negative.
So panicking on negative input may be a good choice.

**Comment by StefanKarpinski** [comment]
Would you mind adding a test for this?

**Pull request merged**
