### PR TITLE
faster indexing for ReinterpretArray for homogeneous struct.

### PR DESCRIPTION
**Pull request by favba**
I've created specific `getindex` and `setindex!` method for reinterpret of arrays to a homogeneous struct (all fields of the struct have the same type as the original array).
I believe that is the most common usage for `reinterpret` and since the reinterpret overhaul it lost some performance.
This PR seems to fix that for those simple - yet widely used - cases.

Before this PR:
```julia

julia> using BenchmarkTools

julia> using StaticArrays

julia> a = rand(16,16);

julia> r = reinterpret(SVector{2,Float64},a);

julia> nr = Array(r);

julia> @benchmark sum($nr)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     95.941 ns (0.00% GC)
  median time:      96.077 ns (0.00% GC)
  mean time:        96.413 ns (0.00% GC)
  maximum time:     437.737 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     950

julia> @benchmark sum($r)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     120.970 ns (0.00% GC)
  median time:      121.436 ns (0.00% GC)
  mean time:        122.972 ns (0.00% GC)
  maximum time:     411.434 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     907

```

After the PR:

```julia
julia> using BenchmarkTools

julia> using StaticArrays

julia> a = rand(16,16);

julia> r = reinterpret(SVector{2,Float64},a);

julia> nr = Array(r);

julia> @benchmark sum($nr)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     96.426 ns (0.00% GC)
  median time:      96.509 ns (0.00% GC)
  mean time:        96.805 ns (0.00% GC)
  maximum time:     181.838 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     949

julia> @benchmark sum($r)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     97.666 ns (0.00% GC)
  median time:      98.251 ns (0.00% GC)
  mean time:        99.009 ns (0.00% GC)
  maximum time:     200.624 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     946
```

It uses a few generated functions. I don't know if that is desirable or not.
I'm also not sure I'm making some improper assumption about the padding of structs or something related to that.

### CODE REVIEW

**Comment by favba** [comment]
Ok, I just found out that relying in calling the constructor will not work as intended if a special constructor is defined:

Before the PR:
```
julia> struct DS{T}
           x::T
           y::T
           DS{T}(x::T,y::T) where {T} = new{T}(x,2*y)
       end

julia> a = Float64[1:10...]
10-element Array{Float64,1}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

julia> reinterpret(DS{Float64},a)
5-element reinterpret(DS{Float64}, ::Array{Float64,1}):
 DS{Float64}(1.0, 2.0)
 DS{Float64}(3.0, 4.0)
 DS{Float64}(5.0, 6.0)
 DS{Float64}(7.0, 8.0)
 DS{Float64}(9.0, 10.0)
```
After the PR:
```
julia> reinterpret(DS{Float64},a)
5-element reinterpret(DS{Float64}, ::Array{Float64,1}):
 DS{Float64}(1.0, 4.0)
 DS{Float64}(3.0, 8.0)
 DS{Float64}(5.0, 12.0)
 DS{Float64}(7.0, 16.0)
 DS{Float64}(9.0, 20.0)
```

Is there a low level function the we can use that would bypass defined constructors to instantiate the struct?
I thought of creating a tuple and `reinterpret` it but it doesn't work: 
```
julia> reinterpret(DS{Float64},(1.,2.))
ERROR: bitcast: target type not a leaf primitive type
Stacktrace:
 [1] reinterpret(::Type{DS{Float64}}, ::Tuple{Float64,Float64}) at ./essentials.jl:381
 [2] top-level scope at none:0
```

**Comment by favba** [comment]
Using `:new` as a the expression head will do the trick 😉

**Comment by favba** [comment]
@Keno, I think I took care of all possible issues that I am aware of for now.
I believe the main questions are:

1) Is there any disadvantages for using all this generated functions?
2) By the way I implement the code, am I making some hidden assumption that might not always be true? (Padding or whatever?)

I believe it is well worth having those specialized code for homogenous structs, as I believe this is a widely used case.

**Comment by Keno** [comment]
Generated functions are always best to be avoided and it would be nice to make the compiler faster, but this looks ok and sane to me in the meanwhile. Ideally also add this as a benchmark to BaseBenchmarks, so we can track it as the compiler gets better and maybe it'll be unnecessary eventually.

**Pull request closed without merging**
