### PR TITLE
Fix libjulia install name and libjulia-internal rpath on OS X

### PR DESCRIPTION
**Pull request by jonathan-conder-sm**
Follow-up to https://github.com/JuliaLang/julia/pull/47053, which explains the rationale

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should we merge this?

**Comment by jonathan-conder-sm** [comment]
That might be a holdover from the 1.6 branch, I can check tomorrow

**Comment by ViralBShah** [comment]
I do see a lot of `DRAWIN_FRAMEWORK` on master - so it didn't happen yet.

**Comment by ViralBShah** [comment]
cc @staticfloat

**Comment by ViralBShah** [comment]
@staticfloat / @giordano Should we merge this?

**Review by andreea199515 — APPROVED** [review]

**Comment by ViralBShah** [comment]
@jonathan-conder-sm Would you be able to resolve the conflict here and we can then get it merged? @staticfloat has already approved the linked PR.

**Comment by jonathan-conder-sm** [comment]
the merge looks fine to me. still has `DARWIN_FRAMEWORK` but looks like master still has it too

**Comment by jonathan-conder-sm** [comment]
actually I'm not sure, looks like RPATH_LIB was removed and this adds it back, unsure if that's the right thing to do or not

**Pull request merged**
