### PR TITLE
Backports for 1.11.1

### LINKED ISSUE #55850: Wrong default REPL prompt when `JULIA_DEPOT_PATH` is a symlink
Found when trying to run tests on master but this happens all the way back to at least 1.5.

Discovered because of new tests.
```
Test Failed at /Users/christian/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/REPL/test/repl.jl:1971
  Expression: prompt == "(@v$(VERSION.major).$(VERSION.minor)) pkg> "
   Evaluated: "(v1.12) pkg> " == "(@v1.12) pkg> "
```

Seems like `projname(project_file::String)` only checks `abspath` instead of `safe_realpath` when comparing `envdir` and `project_file` https://github.com/JuliaLang/julia/blob/fc9f1470458ad6bdeb1f56c1150d651814a0a164/stdlib/REPL/src/Pkg_beforeload.jl#L89-L94

Repl walkthrough of my investigation:
```ChrichriMBP:~$ j +nightly
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1238 (2024-09-23)
 _/ |\__'_|_|_|\__'_|  |  Commit 0fade450a18 (0 days old master)
|__/                   |

julia> withenv("JULIA_DEPOT_PATH" => mktempdir(), "JULIA_LOAD_PATH" => nothing) do
              run(`$(Base.julia_cmd()[1]) --startup-file=no`)
          end
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1238 (2024-09-23)
 _/ |\__'_|_|_|\__'_|  |  Commit 0fade450a18 (0 days old master)
|__/                   |

julia> using REPL; REPL.Pkg_promptf()
[ Info: Precompiling REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] 
"(v1.12) pkg> "

julia> depot = Base.DEPOT_PATH |> first
"/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd"

julia> envdir = joinpath(depot, "environments")
"/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd/environments"

julia> project_file = REPL.find_project_file()
"/private/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd/environments/v1.12/Project.toml"

julia> startswith(abspath(project_file), abspath(envdir)) # Line 91 in Pkg_beforeload.jl
false
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #55945 
- [x] #55932 
- [x] #55968 
- [x] #55977 
- [x] #55982 
- [x] #55743 
- [x] #55851 
- [x] #55992 
- [x] #55589 
- [x] #54009 
- [x] #56019 
- [x] #56023 
- [x] #55569 
- [x] #55824 
- [x] #56041 
- [x] https://github.com/JuliaLang/julia/pull/53469
- [x] #56029 
- [x] https://github.com/JuliaLang/julia/pull/56103
- [x] #55941 

Need manual backport:
- [ ] #55908 

Contains multiple commits, manual intervention needed:
- [ ] #55509 
- [ ] #55877 

Non-merged PRs with backport label:
- [ ] #56069 
- [ ] #55958 
- [ ] #55956 
- [ ] #55910 
- [ ] #55886 
- [ ] #55871 
- [ ] #55870 
- [ ] #55867 
- [ ] #55813 
- [ ] #55802 
- [ ] #55741 
- [ ] #55534 
- [ ] #55499 
- [ ] #55458 
- [ ] #55457 
- [ ] #55220 
- [ ] #55169 
- [ ] #54457 
- [ ] #53957 
- [ ] #51479 
- [ ] #50813 
- [ ] #50157

### CODE REVIEW

**Comment by IanButterworth** [comment]
Sorry, git made it seem like I was deleting a branch on my fork, not here..

**Comment by ViralBShah** [comment]
The release number with the most number of 1s unless we get to 1.11.11.

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56025#issuecomment-2404876987) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/0de7b6c_vs_501a4f2/report.html) is available.

**Comment by ufechner7** [comment]
I don't see https://github.com/JuliaLang/julia/pull/55316 in this list. Can it be added?

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["NNParamsPrinter", "FloatTracker", "Losers", "JuliaInterpreter", "SubSIt", "BlockMatching", "TiledIteration", "HMatrices", "BandedMatrices", "ImplicitPlots", "AccurateArithmetic", "SIMDMathFunctions", "ExtXYZ", "ImageShow", "AMGCLWrap", "Sixel", "YFinance", "ImageInTerminal", "Pyehtim", "ExtendableSparse", "SLEEFMath", "ImageSmooth", "QuantumControl", "MathJaxRenderer", "GIFImages", "OnlinePortfolioAnalytics", "SpectralResampling", "FastDMTransform", "FastHistograms", "MarsagliaDiscreteSamplers", "BoxLeastSquares", "ImageFiltering", "MutualInformationImageRegistration", "TriangularSolve", "VectorizedStatistics", "LabelledArrays", "FinanceCore", "Octavian", "SparseExtra", "GraphDynamics", "MultiCDF", "NLLSsolver", "TropicalGEMM", "RegressionTables", "CategoricalMonteCarlo", "BifrostTools", "StatGeochemBase", "VectorizedReduction", "ObjectPools", "SpheriCart", "Gaius", "SmoQyDEAC", "ImageIO", "LibRaw", "Powerful", "VisualGeometryOptimization", "RandomWalkBVP", "RollingFunctions", "STREAMBenchmark", "FastGeoProjections", "Determinantal", "SpatialAccessTrees", "ImageDistances", "HOODESolver", "ComputerVisionMetrics", "Miter", "JetReconstruction", "QSM", "MicroscopePSFs", "LocalPoly", "ChebParticleMesh", "ModiaResult", "LifeContingencies", "FinEtoolsHeatDiff", "FinEtoolsAcoustics", "SignalAlignment", "ArDCA", "ModiaBase", "RedClust", "Jadex", "AtomsCalculatorsUtilities", "FinEtoolsMultithreading", "EmpiricalPotentials", "FinEtoolsFlexStructures", "ODEInterfaceDiffEq", "FinEtoolsDeforLinear", "LSODA", "PSSFSS", "DiffEqPhysics", "SteadyStateDiffEq", "GLFixedEffectModels", "OrdinaryDiffEqQPRK", "CalciumScoring", "IRKGaussLegendre", "OrdinaryDiffEqFeagin", "OrdinaryDiffEqHighOrderRK", "HclinicBifurcationKit", "OrdinaryDiffEqStabilizedRK", "ShellStructureTopo", "OrdinaryDiffEqLowOrderRK", "Sundials", "ImageQualityIndexes", "OrdinaryDiffEqSSPRK", "OrdinaryDiffEqNordsieck", "OrdinaryDiffEqAdamsBashforthMoulton", "SimSearchManifoldLearning", "SpeedMapping", "OrdinaryDiffEqLinear", "StartUpDG", "AlgebraicMultigrid", "MRISimulation", "AztecDiamonds", "FMIExport", "SignalTablesInterface_PyPlot", "GMT", "ModiaPlot_PyPlot", "EconomicScenarioGenerators", "FMIBuild", "SphericalFunctions", "BoundaryValueProblems", "PolaronMobility", "FMIBase", "OptimizationOptimJL", "Yields", "SurveyDataWeighting", "TruncatedMVN", "ManifoldDiffEq", "MaximumEntropyMomentClosures", "Unfolding", "OrdinaryDiffEqExtrapolation", "DiffEqFinancial", "QuantitativeSusceptibilityMappingTGV", "EvoLinear", "GMMParameterEstimation", "OptimizationSpeedMapping", "ROMEO", "LowLevelParticleFilters", "GlobalSensitivity", "CLEARSWI", "ActuaryUtilities", "OrdinaryDiffEqFIRK", "RealPolyhedralHomotopy", "MriResearchTools", "OrdinaryDiffEqExponentialRK", "FinanceModels", "GeoEnergyIO", "FSimZoo", "Jutul", "DecomposingPolynomialSystems", "Eikonal", "StanModels", "ImageQuilting", "Images", "ColorSchemeTools", "ImageTracking", "ApproxMasterEqs", "DynamicMovementPrimitives", "Attractors", "ImageFeatures", "DIVAnd_HFRadar", "PlantBiophysics", "TrajGWAS", "BattMo", "NBodySimulator", "GeoStatsValidation", "SchwarzChristoffel", "StatisticalRethinking", "OrdinalGWAS", "GameTheory", "AffineMotions", "FourierGPE", "BLASBenchmarksCPU", "DIVAnd", "Globtim", "PeriLab", "StarFormationHistories", "Consensus", "EMpht", "BaseModelica", "FinEtoolsVibInFluids", "SensitivityRankCondition", "ParameterizedFunctions", "SMLMData", "IndependentComponentAnalysis", "GeometryPrimitives", "ONSAS", "SMLMMetrics", "Circuitscape", "ReducedBasis", "CellMLToolkit", "ODEProblemLibrary", "Omniscape", "OptimizationMOI", "AstrodynamicalModels", "ConceptualClimateModels", "ReactionNetworkImporters", "CirculatorySystemModels", "LiquidElectrolytes", "LowRankIntegrators", "PubChem", "GpABC", "ClimateTools", "BatchReactor", "SpiDy", "ChargeTransport", "SMLMFrameConnection", "FrequencySweep", "ClimatePlots", "RealTimeAudioDiffEq", "PlugFlowReactor", "SurfaceCoverage", "SymbolicNumericIntegration", "Petri", "HetaSimulator", "PiecewiseDeterministicMarkovProcesses", "EditorsRepo", "DataDrivenDiffEq", "Tapestree", "TidierPlots", "StirredReactor", "RandomFeatures", "ModiaPlot_CairoMakie", "InternalFluidFlow", "Psychrometrics", "WaveletsExt", "PortfolioAnalytics", "RobustBlindVerification", "FaultTolerantControl", "MultivariateOrthogonalPolynomials", "GeneralizedSasakiNakamura", "GeneticsMakie", "FSimPlots", "MendelImpute", "ControlBarrierFunctions", "MathepiaModels", "HmtArchive", "NVMagnetometer", "MinimallyDisruptiveCurves", "TSML", "HmtGutenberg", "ReactionSensitivity", "QAOA", "Coalescent", "MRINavigator", "BloqadeGates", "OVERT", "Biofilm", "SMLMSim", "MiseEnPage", "NeuroAnalysis", "Pioran", "Chamber", "VlasovMethods", "IonSim", "GIRFReco", "StableSpectralElements"])`

**Pull request merged**
