### PR TITLE
Support building of system image in binary builds

### PR DESCRIPTION
**Pull request by staticfloat**
I'm going to wait for travis to turn green before I merge

### CODE REVIEW

**Comment by tkelman** [comment]
Ouch, @staticfloat, we goofed here. The `julia-debug.exe` segfault on release-0.3 that I mentioned at https://github.com/JuliaLang/julia/issues/10058#issuecomment-74400702 was caused by the changes in the first commit here, 86b109468d58a39a529c30da4dfaae6f9a78a2eb.

We aren't testing julia-debug on AppVeyor to save time, so this went unnoticed for a while. We should really revisit running the tests on the Windows buildbots, where we build a little less frequently and aren't as constrained on time.

**Comment by vtjnash** [comment]
ah yes, there's where someone tried to open sys.dll on julia-debug.exe on windows: https://github.com/JuliaLang/julia/commit/86b109468d58a39a529c30da4dfaae6f9a78a2eb#diff-669d4cc5c9c8f4573c5f8d57f5dcab20R1200

(it's mildly OK on other platforms since libjulia isn't linked to anything else on those platforms, but we should probably be loading it with the platform-specific LOAD_ONLY flags, so it doesn't run code or link itself into anything)

**Comment by tkelman** [comment]
backtrace, if at all useful https://gist.github.com/d1774892dda5962820a2

**Comment by vtjnash** [comment]
this causes libjulia and libjulia-debug to get loaded into the same process. the net effect is that symbol resolution becomes partially ambiguous and the result is a segfault shortly thereafter. the backtrace isn't particularly meaningful, since the fault could happen anywhere, the behavior is simply undefined if multiple libjulia versions get loaded into the same process.

**Comment by staticfloat** [comment]
Ah, whoops.  Yes, this makes a lot of sense.  I'll try to test out a PR today.

**Comment by staticfloat** [comment]
Wait, I'm confused. Why does this cause `libjulia` and `libjulia-debug` to both get loaded?  I'm only loading `sys.dll` here, not `libjulia.dll`.

**Comment by staticfloat** [comment]
At least, those are the ones I'm loading directly.

**Comment by vtjnash** [comment]
julia-debug has already loaded libjulia-debug. `sys.dll` forces `libjulia.dll` to also get loaded in the same process

**Comment by staticfloat** [comment]
I see.  This is because of [this line in `Makefile`](https://github.com/JuliaLang/julia/blob/9ef17207d5f99c7a0019cbbe0e58f77e7c4c1d21/Makefile#L155), where we link against `libjulia` only on Windows.

I can't find any mention of `LOAD_ONLY` flags.  I found a [`RTLD_NOLOAD` flag](http://man7.org/linux/man-pages/man3/dlopen.3.html), but that doesn't seem to do what we'd want it to do.  I noticed that I don't `dlclose()` what I open with `dlopen()` here.  If I did that, do you think it would fix things? 

I'll note here that I don't get a segfault when starting the latest 0.4 `julia-debug.exe` on Win64 right now.  @tkelman is there anything special I need to do in order to make it segfault?  I'm currently building 0.3 right now, we'll see what happens.

**Comment by vtjnash** [comment]
no, that wouldn't help because the damage has already been done. i think tkelman is running the spawn test to trigger this. i don't know exactly what flags should be used, there are a couple that might be correct: https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179%28v=vs.85%29.aspx

**Comment by tkelman** [comment]
@staticfloat on master the segfault happens in the spawn test, #10111. On release-0.3 it happens just from starting julia-debug when sys.dll is present.

**Comment by staticfloat** [comment]
I'm having a hard time triggering this bug, so it's going to be hard for me to come up with a fix and see that it's made a difference.  This is on my win64 buildbot. With a clean build on `0.3-release`:
```
$ ./julia-debug.exe
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6-pre+73 (2015-02-15 00:00 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 50ea614 (1 day old release-0.3)
|__/                   |  x86_64-w64-mingw32

julia> Base.runtests("spawn")
     * spawn
       [stdio passthrough ok]
    SUCCESS

julia>
```

**Comment by tkelman** [comment]
How was that built/installed? If it was doing `make dist` then running the installer, then that deletes `sys.dll`. This is mostly a problem for source builds at this time, but will become important when we want to start distributing `sys.dll`.

**Comment by staticfloat** [comment]
It was running within the source tree of a buildbot.

**Comment by tkelman** [comment]
Was `sys.dll` present? If not, where did it get deleted?

**Comment by staticfloat** [comment]
Yes, it's present.  Here's it running on 0.3.6 on the buildbot:
```
$ ./julia-debug.exe
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> filter( x -> contains(x, "sys."), Sys.dllist())
1-element Array{String,1}:
 "C:\\cygwin\\home\\vagrant\\buildbot\\slave\\package_win8_1-x64\\build\\usr\\lib\\julia\\sys.DLL"

julia> Base.runtests("spawn")
     * spawn
       [stdio passthrough ok]
    SUCCESS
```

**Comment by tkelman** [comment]
I'm confused then. What is the buildbot doing differently than my machine? I forget, what version of windows are the VM's using?

**Comment by staticfloat** [comment]
They're running 8.1
-E

**Comment by tkelman** [comment]
`Base.runtests` never uses debug Julia (maybe it should when run from debug julia). And due to 2670c7710185e8b3f9705125c1c9bd3e891c38f4, on master I currently get a `Julia and the system image were compiled for different architectures` when I try to do `Base.runtests("spawn")` from julia-debug.exe.

**Comment by tkelman** [comment]
Seems to be something different between Windows 7 and 8+. Using a VM of Windows Server 2012 R2 (which should be similar to Windows 8), I can run the spawn test just fine with julia-debug on master. Not sure what's causing the difference.

**Pull request merged**
