### PR TITLE
Set VERSION to 1.0.0

### PR DESCRIPTION
**Pull request by ararslan**
This is a momentous milestone: Once this is merged, Julia will be officially version 1.0. (Obviously this should not be merged until directly before we tag the release.)

Thank you to everyone who's worked on Julia over the years and gotten us this far. It's been a great ride and I can't wait to see where we'll go next.

To be merged first:
- [x] #28517 
- [x] #27674 
- [x] #28522
- [x] #28524 
- [x] #28528

### CODE REVIEW

**Review by fredrikekre — DISMISSED** [review]

**Comment by Keno** [comment]
PkgEval results (as of last night:
- Passing packages with 0.7 --depwarn=error: 161
- Passing packages with 1.0rc1: 158 (165 as of right now)
- Missings.jl has a 1.0 minimum version, so somewhat counterintuitively is passes on 1.0, but fails on 0.7, this causes a number of packages to pass on 1.0, but get skipped on 0.7
- There's about 17 packages that pass on 0.7 and fail on 1.0. These are all due to importing or extending deprecated base methods (which doesn't throw a deprecation warning).

**Review by simonbyrne — APPROVED** [review]
LGTM

**Review by fredrikekre — APPROVED** [review]
:tada:

**Review by HarrisonGrodin — APPROVED** [review]
Lgtm!

**Review by KristofferC — APPROVED** [review]
I'll allow it

**Comment by yurivish** [comment]
🐣

**Review by mbauman — APPROVED** [review]

**Review by Evizero — APPROVED** [review]
lgtm

**Comment by ChrisRackauckas** [comment]
Sure. We can do 2.add(3) so lgtm

**Review by omus — APPROVED** [review]

**Review by andyferris — APPROVED** [review]

**Review by timholy — APPROVED** [review]
Thanks, everyone, for the ride of a lifetime.

**Review by staticfloat — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Review by Keno — APPROVED** [review]

**Review by halleysfifthinc — APPROVED** [review]

**Review by aviks — APPROVED** [review]

**Review by sbromberger — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]
LGTM!

**Review by quinnj — APPROVED** [review]
✔️

**Comment by ysimillides** [comment]
Very excited, much release.

**Review by SaschaMann — APPROVED** [review]

**Review by YingboMa — APPROVED** [review]

**Review by rfourquet — APPROVED** [review]

**Review by kshyatt — APPROVED** [review]

**Comment by ChristianKurz** [comment]
Lgtm

**Review by fredrikekre — APPROVED** [review]

**Review by mbauman — APPROVED** [review]

**Review by bovine3dom — APPROVED** [review]

**Comment by zygmuntszpak** [comment]
Seems legit

**Review by ysimillides — APPROVED** [review]

**Review by arijitkar98 — APPROVED** [review]

**Comment by helgee** [comment]
Do it! Just do it!

**Review by jekbradbury — APPROVED** [review]

**Review by vchuravy — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]

**Comment by kshyatt** [comment]
Please rebase and fix whitespace issues.

**Review by joshday — APPROVED** [review]

**Review by kmsquire — APPROVED** [review]

**Comment by Ellipse0934** [comment]
I dunno how to upvote from the “codehub” app on ios.

**Review by fredrikekre — APPROVED** [review]

**Comment by arsenal9971** [comment]
LGTM!!

**Comment by miguelraz** [comment]
LGTM!

**Comment by rsrock** [comment]
hit it

**Review by mohdibntarek — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]

**Review by vchuravy — APPROVED** [review]
Let's do this!

**Review by eeshan9815 — APPROVED** [review]

**Comment by ellisvalentiner** [comment]
just do it already…

**Comment by Evizero** [comment]
the suspense is killing me

**Comment by Evizero** [comment]
🎉

**Comment by samuelpowell** [comment]
Don’t do it!

**Comment by ararslan** [comment]
Quick let's revert

**Comment by ellisvalentiner** [comment]
what. have. you. done.

**Comment by KristofferC** [comment]
Absolute madman.

**Comment by arsenal9971** [comment]
<3

**Comment by nilshg** [comment]
:100:

**Comment by o314** [comment]
For goodness' sake, there's something amazing happening here and now :sparkles:  :star2: :fireworks:

**Comment by ararslan** [comment]
Meh, nbd.

**Comment by chenxlieee** [comment]
赞

**Comment by ViralBShah** [comment]
The release party was incredibly memorable. Thanks everyone! Linking the video from the event here (release is towards the end).

https://www.youtube.com/watch?v=1jN5wKvN-Uk

**Comment by SalchiPapa** [comment]
:heart:

**Comment by radovankavicky** [comment]
:100: Finally & Congrats!

**Review by radovankavicky — COMMENTED** [review]
Approved. :)

**Comment by codeneomatrix** [comment]
It's amazing congratulations to all

**Pull request merged**
