### PR TITLE
normalize_triplet.py: Properly map libgfortran versions for GCC 10

### LINKED ISSUE #35638: Failed to compile on Fedora 32
Fedora 32 (just upgraded)
Pulled here a few hours ago.
Compile stopped after two errors:
1. julia/contrib/normalize_triplet.py", line 112, in <module>
    libgfortran_version = {
    KeyError: '1'
2. curl: (22) The requested URL returned error: 404 Not Found
    julia/deps/suitesparse.mk:144: 
    julia/deps/srccache/SuiteSparse.v5.4.0-6..tar.gz] Error 22

### PR DESCRIPTION
**Pull request by staticfloat**
Closes https://github.com/JuliaLang/julia/issues/35638

### CODE REVIEW

**Comment by staticfloat** [comment]
@xijiang could I get you to test this, to verify that it fixes https://github.com/JuliaLang/julia/issues/35638?

**Comment by ViralBShah** [comment]
Would be nice to get this in for 1.5.

**Review by vtjnash — APPROVED** [review]

**Comment by xijiang** [comment]
It's working now on my desktop. Many thanks.

**Comment by KristofferC** [comment]
Removing backport since we don't seem to have this list for 1.4.

**Pull request merged**
