### PR TITLE
Add command line option for short banner

### PR DESCRIPTION
**Pull request by LilithHafner**
```
  o  | Version 1.10.0-beta1 (2023-07-25)
 o o | Official https://julialang.org/ release
```
```
  o  | Version 1.11.0-DEV.229 (2023-07-29)
 o o | scoped-export/de8be2b039* (fork: 35 commits, 0 days)
```
(it has color, too)

### CODE REVIEW

**Comment by LilithHafner** [comment]
I've reviewed and approve @c42f's contribution to this PR.

**Review by c42f — APPROVED** [review]
I've looked through all this again including your parts @LilithHafner. I added another two tiny tests to cover the command line argument more thoroughly.

It looks good to me I say we merge it as soon as CI passes.

Personally I'll be turning this on by default for all my Julia aliases :)

**Comment by c42f** [comment]
The windows test failure here looks spurious - something to do with temporary files and the file system.

**Comment by tecosaur** [comment]
@LilithHafner did you by any chance see my efforts to support multiple banner sizes based on the terminal resolution?

**Comment by LilithHafner** [comment]
I did not, would you share a link?

**Comment by tecosaur** [comment]
I had a look when I sent that message, unfortunately it seems like the discussion has disappeared into the slack-hole. That said, I do a brief recap and demo.

I don't think it's very nice how with a narrow or small terminal window, the Julia banner can (a) get ruined by line wrapping, or (b) take up almost all of the window. So, I designed a number of alternative scaling of the Julia banner that are picked between based on `displaysize(io)`.

image

**Comment by LilithHafner** [comment]
I love the rendering of "Julia" in the 8x55 version!

**Comment by tecosaur** [comment]
The 8 or less rows options do assume the Julia mono font, but I like them. I'd be happy to PR these once StyledStrings is in, but I do think we'd then want to switch out `--banner=short` to `--banner=<int>`, say with `0` being the smallest size and going up from there.

**Comment by LilithHafner** [comment]
The deadline to cleanly swap that out (i.e. drop support for `--banner=short`) is 1.11

**Comment by tecosaur** [comment]
Mmm, I'd also like to get StyledStrings in with 1.11 (and Stefan/Kristopher/Jameson seemed to think that reasonable I spoke with them at JuliaCon).

**Comment by LilithHafner** [comment]
For @c42f and others who may want to opt into this by default, here's a little monstrosity to put in startup.jl that does that

```julia
# Use --short banner by default (LINK)
if VERSION >= v"1.11.0-DEV.222" && isinteractive()
    c_options = cglobal(:jl_options, Base.JLOptions)
    opts = unsafe_load(c_options)
    if opts.banner == -1 && isa(stdin, Base.TTY)
        # opts.banner = 2
        fields = fieldnames(Base.JLOptions)
        args = (f == :banner ? 2 : getfield(opts, f) for f in fields)
        new_opts = Base.JLOptions(args...)
        unsafe_store!(c_options, new_opts)
    end
end
```

**Comment by tecosaur** [comment]
That almost makes me wonder if a `JULIA_BANNER` env var may be worth it.

**Comment by LilithHafner** [comment]
That `fieldoffset` method does not exist.
```julia
julia> only(methods(fieldoffset))
fieldoffset(x::DataType, idx::Integer)
     @ Base reflection.jl:917
```

**Comment by vtjnash** [comment]
Ugh, you are right, and it really should exist for this use case. Anyways, here is the verbose version of it then:
```
julia> code_typed() do; fieldoffset(Base.JLOptions, Base.fieldindex(Base.JLOptions, :banner)); end
1-element Vector{Any}:
 CodeInfo(
    @ REPL[7]:1 within `#21`
1 ─     return 0x0000000000000001
) => UInt64
```

**Comment by c42f** [comment]
Oh my. I love that use of `code_typed()` with the lambda :heart_eyes:

**Pull request merged**
