### PR TITLE
Fix find(in(b), a) to return cartesian indices for matrix a

### PR DESCRIPTION
**Pull request by nalimilan**
For consistency with `find(x -> in(b), a)`.
Restrict function signatures for clarity, as a needs to support `keys`/`pairs` and these internal functions are only called on arrays and tuples.

Similar to https://github.com/JuliaLang/julia/pull/30102.

### CODE REVIEW

**Comment by garrison** [comment]
Thanks @nalimilan.  Here is the example from Slack that led to this:
```
julia> findall(in([5, 6]), [5 6; 7 8])
2-element Array{Int64,1}:
 1
 3

julia> findall(!in([5, 6]), [5 6; 7 8])
2-element Array{CartesianIndex{2},1}:
 CartesianIndex(2, 1)
 CartesianIndex(2, 2)

julia> findall(x -> x in [5, 6], [5 6; 7 8])
2-element Array{CartesianIndex{2},1}:
 CartesianIndex(1, 1)
 CartesianIndex(1, 2)
```

**Comment by garrison** [comment]
CC @mbauman 

Also: I agree that this is a minor change, but I do want to note that it is technically breaking AFAICT.

**Comment by StefanKarpinski** [comment]
“Minor change” is a non-scary name for “technically breaking but unlikely to cause anyone real problems, which we will test by running PkgEval before releasing”.

**Review by mbauman — APPROVED** [review]

**Comment by mbauman** [comment]
I just fixed the conflict — let's merge this before the feature freeze for 1.1.

**Pull request merged**
