### PR TITLE
remove some underscores

### PR DESCRIPTION
**Pull request by JeffBezanson**
Part of #20402.

- deprecate `catch_stacktrace`
- rename `method_exists` to `hasmethod`
- rename `object_id` to `objectid`

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Nice, thanks! I especially like `hasmethod`.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by nalimilan** [comment]
+1 in general, but I'm not sure I like `hasmethod`: who's the subject of "has", given that there are multiple types?

**Comment by JeffBezanson** [comment]
The function has the method.

**Comment by vtjnash** [comment]
> The function has the method.

Actually, I agree this is a bit weird. Functions don't have methods. The global MethodTables has methods, with symmetric dispatch across all arguments (including the first argument, which in many cases is a Function).

**Comment by JeffBezanson** [comment]
In generic function systems, functions are traditionally considered sets of methods. True, that's not exactly how it works in julia, but the query `hasmethod(f, types)` is formulated in those terms.

We could also have a 1-argument version, e.g. `hasmethod(Tuple{ftype, argtype})` and I think it might still make sense; you're asking if the system has such a method.

**Pull request merged**
