### PR TITLE
Add getindex(::Pair) + tests for Pairs

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
Uncontroversial? I thought I'd sweeten the deal by adding tests :).

More controversial was the idea to do
```julia
getindex(p::Pair, x::Bool) = ifelse(x,p.first,p.second)
```
which would allow an alternative ternary syntax like
```julia
y = (1=>2)[x in set]
```
but that might be too confusing.....

**Comment by JeffBezanson** [comment]
Yeah I find that pretty obfuscated.

**Comment by quinnj** [comment]
Yeah, I think it was cool realizing we *could* do something like that, but then realizing it's probably not very nice generally.

**Comment by quinnj** [comment]
I'm pretty sure the OSX failure is unrelated (timeout while running some package tests?). These passed for me locally on OSX.

**Comment by quinnj** [comment]
Looks like the appveyor failure is #10045.

**Pull request merged**
