### PR TITLE
Fix UndefVarError due to unintentional signature change

### PR DESCRIPTION
**Pull request by BioTurboNick**
@vtjnash was introduced by #40642

### CODE REVIEW

**Comment by ararslan** [comment]
Is it possible to add a test that would have caught this in the original PR, or is this what caused the (not particularly transparent) `UNHANDLED TASK ERROR: IOError: stream is closed or unusable` errors on Linux and FreeBSD on that PR? It probably shouldn't have been merged with those failures.

**Comment by BioTurboNick** [comment]
I don't know why this would have caused an error specifically on Linux or FreeBSD... But adding a test to make sure this path works seems reasonable.

**Comment by vtjnash** [comment]
The PR likely needed to `wait` for the REPL task to exit, following whatever the other test do

**Comment by BioTurboNick** [comment]
Think I got it. Needed an end of transmission character and then the wait.

**Review by ararslan — APPROVED** [review]

**Pull request merged**
