### PR TITLE
doc: heap snapshot viewing

### PR DESCRIPTION
**Pull request by nsajko**
Say that:
* VS Code may be used for viewing heap snapshots. Important because Chromium currently may *not* be used for this on Julia v1.11 and up: #54414
* Firefox can't be used.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I've personally found https://github.com/RelationalAI/HeapSnapshotUtils.jl to be the most feature-complete, while VSCode's support is still quite buggy. Maybe we can mention this package as well?

**Comment by nsajko** [comment]
@jpsamaroo could you clarify what you mean by "feature-complete", and what is the purpose of HeapSnapshotUtils? Perhaps you meant to point to some other project? I'm confused by the fact that this project, [HeapSnapshotUtils.jl](https://github.com/RelationalAI/HeapSnapshotUtils.jl), doesn't seem to offer visualization of heap snapshots, it just allows to subsample them. Is subsampling more useful than I expect, or is there some other feature, too?

**Comment by jpsamaroo** [comment]
Ahh, sorry, I forgot the README isn't up to date. See https://github.com/RelationalAI/HeapSnapshotUtils.jl/blob/3ee9cf4e8c0c1040f130fbfa1417a13394292aee/src/ui.jl#L331, it provides terminal UI visualization of the GC graph, and allows interactively walking the tree.

**Comment by nsajko** [comment]
I'm grateful for learning about this project, however given that it's not registered, the README is outdated, and there doesn't seem to be any docs either, not even doc strings, IMO it's too early to mention it in the Julia documentation.

**Review by IanButterworth — APPROVED** [review]

**Pull request merged**
