### PR TITLE
add default "auto" as option to --check-bounds

### PR DESCRIPTION
**Pull request by IanButterworth**
It seems to be unusual that neither of the `--check-bounds={yes|no}` options are the default state, so this adds "auto" to make it `--check-bounds={yes|no|auto}`

It would make overruling this arg back to default state possible, for instance in https://github.com/JuliaLang/Pkg.jl/pull/2668 (although that can be fixed in other ways)

### CODE REVIEW

**Comment by IanButterworth** [comment]
Who's a good reviewer for this? @vtjnash perhaps?

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Looks fine to me, but this is not the kind of thing we would usually backport.

**Comment by IanButterworth** [comment]
My rationale for backporting to 1.6 was that this would be helpful for https://github.com/julia-actions/julia-runtest/pull/46
If it's not backported to the LTS, the user would have to guard in CI to not send `--check-bounds=auto` to the LTS, assuming they test on LTS and latest.
And thus couldn't run CI tests with the julia default bounds checking.

I thought the default not being available as an option was more of a bug than a missing feature? That's probably a thin argument though

**Comment by JeffBezanson** [comment]
Yeah, it's a borderline case, and indeed difficult to see this causing any problem. I guess it might be ok to backport, but I would probably not add it to the HISTORY file.

**Comment by IanButterworth** [comment]
Ok. I'll watch out for when it gets backported. I couldn't see a label for "requires manual backport". Perhaps that would help

**Pull request merged**
