### PR TITLE
Added doctests to @printf and @sprintf; added code highlighting

### PR DESCRIPTION
**Pull request by xorJane**
I converted code blocks from PR #18967 to doctests and added some code highlighting per recommendations from @tkelman.

Thank you :)

### CODE REVIEW

**Comment by tkelman** [comment]
hm. would adding `\n` to the end of the format string work?

**Comment by xorJane** [comment]
No, that seemed to mess up the conversion to .rst --- the doctest failed and the formatting of the code block in the .html file was incorrect.

**Comment by tkelman** [comment]
maybe double backslash?

**Comment by xorJane** [comment]
Yeah that seems to work! I'll update accordingly.

**Review by tkelman — APPROVED** [review]

**Comment by tkelman** [comment]
Thanks much!

**Pull request merged**
