### PR TITLE
[minor] removed a confusing semicolon after "end"

### PR DESCRIPTION
**Pull request by sg-s**
removed a confusing semicolon after "end" that did nothing

### CODE REVIEW

**Comment by tomaklutfu** [comment]
I think you need to add the resulting function definition message from Repl too. May be it was there to suppress this message.

**Comment by sg-s** [comment]
This worked in my REPL (no semicolon)

```
function g(x, y)::Int8
       return x*y
       end
g (generic function with 1 method)


```

**Review by aekewu — APPROVED** [review]

**Comment by musm** [comment]
The `;` does something here since its point is to suppress printing the output in the REPL in the doctest. 

Reading the docs surrounding the definition, it is clear that the output of the definition isn't needed for any instructive purpose, thus I would keep it as is.

**Comment by sg-s** [comment]
I see, thanks for that. I'm closing this then

**Comment by tomaklutfu** [comment]
I did not say this does not work. The semicolon has the purpose of suppressing outputs in repl. As you see there is a message in the repl after you make your function definition. This output should be added to doctest too.

**Review by aekewu — COMMENTED** [review]
又

**Pull request closed without merging**
