### PR TITLE
sparse broadcasting with type constructors

### LINKED ISSUE #40901: Broadcasting over sparse matrix generating wrong type
```
julia> VERSION
v"1.7.0-DEV.1108"

julia> rem.(sparse([1 2; 3 4]), 2)
2×2 SparseMatrixCSC{Int64, Int64} with 2 stored entries:
 1  ⋅
 1  ⋅

julia> big.(rem.(sparse([1 2; 3 4]), 2))
2×2 SparseMatrixCSC{BigInt, Int64} with 2 stored entries:
 1  ⋅
 1  ⋅

julia> BigInt.(rem.(sparse([1 2; 3 4]), 2))
2×2 SparseMatrixCSC{Any, Int64} with 2 stored entries:
Error showing value of type SparseMatrixCSC{Any, Int64}:
ERROR: MethodError: no method matching zero(::Type{Any})
Closest candidates are:

...

julia> BigInt.(rem.(sparse([1 2; 3 4]), 2));

julia> typeof(ans)
SparseMatrixCSC{Any, Int64}

julia> BigFloat.(rem.(sparse([1 2; 3 4]), 2));

julia> typeof(ans)
SparseMatrixCSC{Any, Int64}
```

### PR DESCRIPTION
**Pull request by KlausC**
Fixes #40901.

The determination of result element type failed for composed broadcasts involving sparse arrays.
This PR obtains element type in the same way as in the non-sparse array case.

Just by accident, a previously broken test in `SparseArrays/test/higherorderfns.jl` was fixed as well, sharing the same root cause.
That test case was related to issue #30118.

### CODE REVIEW

**Comment by KlausC** [comment]
it's time to push this bugfix a bit.

**Comment by KlausC** [comment]
pump

**Comment by KlausC** [comment]
bump

**Comment by DilumAluthge** [comment]
We have moved the SparseArrays stdlib to an external repository.

Please open this PR against that repository: https://github.com/JuliaLang/SparseArrays.jl

Thank you!

**Pull request closed without merging**
