### PR TITLE
fix #6466, deprecate `write` on non-isbits arrays

### LINKED ISSUE #6466: make `write(io, Any[...])` an error
I noticed this with IOBuffer, but it looks like IOStream, AsyncStream, and File all have the same issue.  In each of their `read!{T,N}(::IO, a::Array{T,N})` methods, they assume that the number of bytes to read is `length(a)*sizeof(T)`.  This is not true for `Char`:

```
julia> buf = IOBuffer("abcdefghijklmnop");

julia> read(buf, Char)
'a'

julia> read(buf, Char, 2) # dispatches to read!(IOBuffer, Array{Char,1})
2-element Array{Char,1}:
 '\U65646362'
 '\U69686766'
```

For IOBuffer, I think the specialization could simply be removed (albeit perhaps at a small performance loss).  The others, however, are trickier — File performance is much more critical and the Async/IOStream ones need to know how many bytes to wait for.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by tkelman** [comment]
How will these change when this is removed? The depwarn and invoke calls replaced by errors?

**Comment by JeffBezanson** [comment]
Yes.

**Comment by vtjnash** [comment]
This feels a bit wrong, since I think in most cases we've found that dispatching on eltype is annoying / throwing unnecessary errors is painful. In particular, we've generally tended towards `f(Any[x, y])` being the same as `f(T[x, y])` for all T, and letting the homogeneity of the elements themselves (or lack thereof) define the behavior. But I realize the current behavior isn't entirely consistent either (sometimes opting for direct `unsafe_write` copies over the more pedantic dispatch loop over all elements), so I'm not strongly opposed either.

**Comment by JeffBezanson** [comment]
Yes, it's slightly unsatisfying. But the concept is that `write` is only valid on objects with a "canonical binary representation", and that the direct argument to `write` (not values inside it) should determine the data format. Otherwise we're stuck with the dispatch loop for all but a fixed set of known types.

Come to think of it the method `write(s::IO, x::Ref{T}) where {T}` also needs this check; currently `write(io, Ref((:a,:b)))` writes garbage.

**Pull request merged**
