### PR TITLE
fix formatting issue in docs

### LINKED ISSUE #36878: incorrect formatting on primitive types section, first warning label
here: https://docs.julialang.org/en/v1/manual/types/#Primitive-Types-1

### PR DESCRIPTION
**Pull request by OkonSamuel**
closes #36878

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Does this fix it? I would think that adding a line here would not help attach the warning to the text.

**Comment by OkonSamuel** [comment]
> Does this fix it? I would think that adding a line here would not help attach the warning to the text.

Yes. It does. I faced something similar when generating https://github.com/cstjean/ScikitLearn.jl/edit/master/docs/src/man/models.md. 
You can also confirm this by comparing https://github.com/JuliaLang/julia/blob/master/doc/src/manual/types.md#primitive-types with https://github.com/OkonSamuel/julia/blob/master/doc/src/manual/types.md#primitive-types.

**Comment by StefanKarpinski** [comment]
@mortenpi, is this a Documenter bug? I'm a bit confused by what the right way to format/fix this is.

**Comment by mortenpi** [comment]
No, it's an indentation problem on the 1.5-branch. It's already fixed on master: https://docs.julialang.org/en/v1.6-dev/manual/types/#Primitive-Types-1

The correct fix would be backport #36254 to 1.5.

For what it's worth, as a style matter, I personally prefer having an empty line between the `!!!` line and the admonition body, so we _could_ merge this, even if it doesn't actually do anything for #36878.

**Pull request closed without merging**
