### PR TITLE
🤖 [master] Bump the SparseArrays stdlib from 2c7f4d6 to b4b0e72

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Stdlib branch: main
Julia branch: master
Old commit: 2c7f4d6
New commit: b4b0e72
Julia version: 1.11.0-DEV
SparseArrays version: 1.10.0 (Does not match)
Bump invoked by: @dkarrasch
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaSparse/SparseArrays.jl/compare/2c7f4d6d839e9a97027454a037bfa004c1eb34b0...b4b0e721ada6e8cf5f6391aff4db307be69b0401

```
$ git log --oneline 2c7f4d6..b4b0e72
b4b0e72 Intermediate test relaxation (#405)
b4d4498 fully qualify promote_eltypeof call (#411)
c93589c Reland new hvcat design (#384, #407)
a9637dd Introduce compat bounds for SuiteSparse (#408)
```

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
Not sure why the mac tests are failing, but they are having some trouble with `vcat`. @vtjnash Can you look into this is if it is related to your PR?

**Comment by vtjnash** [comment]
I don't know why there is a platform difference. I have fixed the erroneous errors in https://github.com/JuliaLang/julia/pull/49322

**Comment by ViralBShah** [comment]
Should #49322 be merged first, then wait for nightlies, and then rerun this one? Alternatively, can they both be merged simultaneously?

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/pull/49322 includes this

**Pull request closed without merging**
