### PR TITLE
Set VERSION to 1.4.2

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/35653 should maybe be included? See https://github.com/JuliaLang/julia/pull/35849 which backports that to release-1.4.

**Comment by KristofferC** [comment]
Thanks missed that. Let's backport that as well indeed.

**Review by ararslan — APPROVED** [review]

**Comment by ararslan** [comment]
Announced a testing period for 1.4.2: https://discourse.julialang.org/t/julia-1-4-2-testing-period/39540?u=ararslan

**Comment by ViralBShah** [comment]
Since this hasn't happened yet, if we still do it, we should try to include https://github.com/JuliaLang/julia/pull/35979

**Comment by ararslan** [comment]
Yeah, I think at this point we could just move forward with releasing 1.4.2 as-is, since there have been no reports from the testing period (as far as I've seen). That change is worthwhile for 1.5, and perhaps 1.4.3, should we do another 1.4 release.

**Pull request merged**
