### PR TITLE
Update noteworthy-differences.md

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
Added notes about the time-to-first-plot problem.

### CODE REVIEW

**Comment by mcabbott** [comment]
I think this might have more chance of being merged if it's a little more subtle. The page is mostly about syntax differences, I'm not sure the very first point should complain so strongly about one particular workflow issue. Perhaps it should be something like this, as the last bullet point:

* While running a script from the command line repeatedly is a common way to use python, like `python3 makeplots.py`, in Julia it is more common to keep a session running. Especially when using large packages such as Plots.jl, which take some seconds to load. Using Revise.jl allows many changes to code to be loaded without restarting the session. Tools such as PackageCompiler.jl, DaemonMode.jl and Pluto.jl offer other approaches.

Alternatively, it's possible that there should be a new Workflow section of the Performance Tips page, where such things could be explained at greater length.

**Comment by tpapp** [comment]
> but Julia's `import mod` or `using mod` is slow

This isn't true in general: it depends on the particular package (`using` a small package with trivial or no dependencies is very fast), the Julia version (cf #33326 and related issues/PRs for work in progress), and of course one's definition of "slow".

Given the recent improvements and the continuing focus on this issue, I don't think it should be addressed in the manual in this form.

Also, I agree with @mcabbott that it would be better to just direct users from other languages to [the workflow tips](https://docs.julialang.org/en/v1.6-dev/manual/workflow-tips/#Revise-based-workflows).

**Comment by Volker-Weissmann** [comment]
> I think this might have more chance of being merged if it's a little more subtle. 

That would be boring :smiley: :wink:

> The page is mostly about syntax differences,

You are right, that page is the wrong place to mention it. So I moved it to another page (see 7b3b090)

**Comment by Volker-Weissmann** [comment]
I won't touch the [workflow-tips](https://docs.julialang.org/en/v1.6-dev/manual/workflow-tips) page, because that page should be written by people who know what they are doing.

**Comment by tpapp** [comment]
> That would be boring smiley wink

I am honestly wondering if you are trolling with this PR, especially after the recent changes. 

If yes, please don't — a lot of people get notifications about this repo. If you don't like Julia, or think that it compares unfavorably to other languages, just don't use it.

**Comment by Volker-Weissmann** [comment]
> 
> I am honestly wondering if you are trolling with this PR, especially after the recent changes.
> 
> If yes, please don't — a lot of people get notifications about this repo. If you don't like Julia, or think that it compares unfavorably to other languages, just don't use it.

Actually, I honestly and sincerely want this PR to be approved.
I will continue to use Julia, at least for some usecases, because I think that Julia is the best language for some usecases.
Everyone needs to know whether a language will fit their usecase BEFORE learning the language. This is why I think that the julia manual should explain which users should use Julia and which users should not use Julia. Choosing a language is a major design decision, and just like with every other design decision there is large value in knowing when to chose witch design.
So, the manual should try to help the reader find out wether Julia fits their needs or not. This should be done honestly and WITHOUT BEING BIASED TOWARDS JULIA. I know that the website of (nearly?) every other language is biased towards their language and I hate it. I hate people that claim that Python is fast and I hate people that claim that C++ is simple, because saying these lies will make people choose the wrong tool for their job.

I'm not saying that Julia is bad. I'm only saying that Julia is not suited for **every** usecase and there are certain things you should now in advance. Julias startup speed makes it unusable for **some** usecases. I know that in many usecases startups of even multiple minutes do not matter, but in other usecases startups 100 ms are too long.

**Comment by timholy** [comment]
I think the first decision is whether we want to have weaknesses on this page. I for one am in favor. But I would edit some of the statements in this PR, should we decide we want to do this.

**Comment by Volker-Weissmann** [comment]
> I think the first decision is whether we want to have weaknesses on this page. I for one am in favor. But I would edit some of the statements in this PR, should we decide we want to do this.

Good. What statement do you want to edit?

**Comment by timholy** [comment]
Several, but let's wait and see whether more people are in favor of adding some of the weaknesses.

**Comment by tpapp** [comment]
@timholy: Can you be more specific about what you consider "weaknesses"? Eg inherent trade-offs in the design (Julia is compiled, which takes time, but then it fast), or long-standing issues that make be fixed some day (eg #15276)?

**Comment by timholy** [comment]
I would focus more on (1) tradeoffs that are mostly inherent to the design choices, and/or (2) reflect longstanding realities even if there might be ways around them. I wouldn't point to specific GitHub issues like #15276, especially as it's really just an annoyance and easily circumventable once you know what to look for.

**Comment by tpapp** [comment]
Do you have any examples of (1) or (2) in mind?

**Comment by timholy** [comment]
Without getting into the word-smithing, I might direct people to JuliaHub to check on package availability and acknowledge the compiler latency. Basically 2/3 of the items in this PR (but rephrased).

**Comment by StefanKarpinski** [comment]
I do think we should list pros and cons of Julia in a straightforward manner and this seems like a reasonable place to do it. I would like to address some of the specific points here:

>  Less mature ecosystem than e.g. Python or C++, because Julia is still a young language (2012).
>  Note that the scientific ecosystem is much greater than the general purpose ecosystem.

When people say that Julia is "less mature" than other languages it's a bit unclear what this is supposed to mean. It's younger? Sure, that's simply a fact. It's therefore less reliable or less well tested? On the contrary, I think that most C++ libraries are poorly tested and poorly documented. Python is a bit better, but the standard for testing in Julia is much, much higher and I feel that the "core package ecosystem" is much more robust and certainly far better tested most other systems you would consider using for numerical computing. For things like writing high performance servers, yes, Julia is less mature, but I don't think that's what you're talking about here. 

> Many Julia packages, have online manuals, but documentation of specific functions is usually only available through the REPL and not available online.

This is not the norm that I have observed. If you have specific examples of packages that do not include an API reference in their documentation, it would be good to file issues with those packages requesting it.

> Note that there exists [a tool](https://juliadocs.github.io/Documenter.jl) that can generate html documentation from the REPL help.

Not sure this belongs here?

> Very slow startup speed when using a lot of large dependencies (known as the "time-to-first-plot problem"). Therefore, it is common workflow to very rarely restart Julia, see [Workflow Tips](@ref man-workflow-tips). Note that you can use the [PackageCompiler.jl](https://julialang.github.io/PackageCompiler.jl/dev) to drastically decrease this time. Also note that there is very active development to decrease this startup time.

"Very slow startup speed" is a bit alarmist, especially on recent Julia versions, but of course the real problem is that this is subjective. It would be better to cite some specific startup time examples with range of times. For example, `@time using Plots` takes 2.6 seconds for me and `@time plot(1:100, cumsum(randn(100)))` takes 2 seconds. I would not personally describe that as "very slow".

**Comment by timholy** [comment]
I agree with all of your points. Still, you didn't address the first-order point: do we want to include weaknesses? If not, then there's no point wordsmithing and we should just close this. If you can imagine a world in which that would be a good thing, then we should attempt to come up with something worthy.

In principle I favor including weaknesses, but I should admit that there's something good about "fitting in with the crowd." If no one else acknowledges their own tradeoffs, then it may send the wrong message if we do. So this is one of those rare cases where I think it will be *better* to come to some decision even before we talk about actual text to display.

**Comment by Volker-Weissmann** [comment]
> I do think we should list pros and cons of Julia in a straightforward manner and this seems like a reasonable place to do it. I would like to address some of the specific points here:

Good
> 
> > Less mature ecosystem than e.g. Python or C++, because Julia is still a young language (2012).
> > Note that the scientific ecosystem is much greater than the general purpose ecosystem.
> 
> When people say that Julia is "less mature" than other languages it's a bit unclear what this is supposed to mean. It's younger? Sure, that's simply a fact. It's therefore less reliable or less well tested? On the contrary, I think that most C++ libraries are poorly tested and poorly documented. Python is a bit better, but the standard for testing in Julia is much, much higher and I feel that the "core package ecosystem" is much more robust and certainly far better tested than most other systems you would consider using for numerical computing. For things like writing high performance servers, yes, Julia is less mature, but I don't think that's what you're talking about here.

"I think that most C++ libraries are poorly tested". Are you serious? The whole world runs on C++. 
I'm mainly talking about General purpose ecosystem, not the scientific ecosystem. 
I'm not saying C++ libraries are better documented, I'm saying there are more and larger C++ libraries. 
C++/Python are two the most popular programming languages, Julia is a niche programming language, that niche being scientific computing. Yes, I know that "scientific computing" is a large niche, but its still a niche.

See for example: https://www.statista.com/statistics/793628/worldwide-developer-survey-most-used-languages/

> 
> > Many Julia packages, have online manuals, but documentation of specific functions is usually only available through the REPL and not available online.

Scrap that part, turns out, I was just too stupid to find the stdlib documentation.
> 
> This is not the norm that I have observed. If you have specific examples of packages that do not include an API reference in their documentation, it would be good to file issues with those packages requesting it.

combinatorics
statprofilerhtml
DifferentialEquations
...

Would it be possible to run Documenter.jl on every package on https://juliapackages.com/p/packagename and host it on https://juliapackages.com/p/packagename ? That would help a lot and this is what Rust does.


> 
> > Note that there exists [a tool](https://juliadocs.github.io/Documenter.jl) that can generate html documentation from the REPL help.

If there is no online manual, you can use that tool to create it. But
> 
> Not sure this belongs here?
> 
> > Very slow startup speed when using a lot of large dependencies (known as the "time-to-first-plot problem"). Therefore, it is common workflow to very rarely restart Julia, see [Workflow Tips](@ref man-workflow-tips). Note that you can use the [PackageCompiler.jl](https://julialang.github.io/PackageCompiler.jl/dev) to drastically decrease this time. Also note that there is very active development to decrease this startup time.
> 
> "Very slow startup speed" is a bit alarmist, especially on recent Julia versions, but of course the real problem is that this phrasing is subjective. It would be better to cite some specific startup time examples with range of times. For example, `@time using Plots` takes 2.6 seconds for me and `@time plot(1:100, cumsum(randn(100)))` takes 2 seconds. I would not personally describe that as "very slow". This could be described objectively as follows:

That's one beafy PC that you have. On my Intel Core i5-4590, I have:
julia> @time using Plots
  9.981201 seconds (17.54 M allocations: 991.089 MiB, 4.20% gc time)

julia> @time plot(1:100, cumsum(randn(100)))
  2.428411 seconds (3.73 M allocations: 192.413 MiB, 1.64% gc time)

> 
> > For large, complex packages with many dependencies, load times can be slow and it can take additional time to execute some functions the first time. For example, it takes 2-4 seconds to load `Plots` (one of the most popular plotting packages) and an additional 1-3 seconds to produce the first plot. After the first plot is produced, producing additional plots will be fast (milliseconds) during the same Julia session. Because of this, many Julia users prefer to keep Julia sessions "alive" for longer periods, only restarting Julia when absolutely necessary. The `Revise` package is particularly useful for this workflow as it allows "hot reloading" code whenever edits are made, which can be even faster and more convenient than running a script repeatedly would be in languages with faster package load times.

That's a good description

**Comment by Volker-Weissmann** [comment]
> @timholy: Can you be more specific about what you consider "weaknesses"? Eg inherent trade-offs in the design (Julia is compiled, which takes time, but then it fast), or long-standing issues that may be fixed some day (eg #15276)?

Inherent trade-offs and issues that will probably not get fixed in the let's say next two years.
If there is an issue that is already fixed on master or will be fixed in a few months it is a detail and not important in considering a language.

**Comment by Volker-Weissmann** [comment]
> In principle I favor including weaknesses, but I should admit that there's something good about "fitting in with the crowd." If no one else acknowledges their own tradeoffs, then it may send the wrong message if we do. 

Doing a bad thing because everyone else does it is not always the best thing.
Trust me, I'm German, we know that.

You could try to open a PR on other languages as well. If you do that, send me a link and I grab my popcorn.

And yes, I know that I'm probably getting banned for the first comment, but that was just too funny to not say it.

**Comment by StefanKarpinski** [comment]
> @timholy: Still, you didn't address the first-order point: do we want to include weaknesses?

> @StefanKarpinski: I do think we should list pros and cons of Julia in a straightforward manner and this seems like a reasonable place to do it.

So yes, I think we should.

> @Volker-Weissmann: "I think that most C++ libraries are poorly tested". Are you serious? The whole world runs on C++.

Deadly. I've used a lot of C and C++ libraries in my life and most of them are only tested by letting people use them and report bugs. That's not what I would consider "well tested". Some C/C++ libraries have great test suites, but it is far from the norm.

> @Volker-Weissmann: Julia is a niche programming language, that niche being scientific computing.

Well, that's like your opinion, man. Julia is a general purpose programming language and always has been. In any case, we don't need to agree on this, but we're not putting in the Julia manual that Julia is less mature than other languages just because it's more recent.

> Anyway, consider e.g. NewvarNode. Using ? NewvarNode, you get

This is a purely internal non-exported type. This is like complaining Python doesn't document the `_PyIO_get_module_state` function.

> combinatorics
> statprofilerhtml
> DifferentialEquations

Please do open issues on these packages about any issues with their documentation. In any case, pretending that this is a norm in the ecosystem and such does not help convince package maintainers to improve things, so we will not be including anything to that effect here.

> Would it be possible to run Documenter.jl on every package on https://juliapackages.com/p/packagename and host it on https://juliapackages.com/p/packagename ? That would help a lot and this is what Rust does.

See JuliaHub: https://juliahub.com/docs/DifferentialEquations/UQdwS/6.15.0/. All registered Julia packages have docs there or, if they have opted out, are linked to from there and can be searched.

> That's one beafy PC that you have.

No, it's a two-year-old MacBook Pro that wasn't even the fastest CPU when I bought it. I am, however, running Julia master, which is already considerably faster than Julia 1.5.

**Comment by Volker-Weissmann** [comment]
> Julia is a general purpose programming language and always has been. 

I'm sorry, but Julia is primarily a scientific computing language. Not saying that this is a bad thing. This here is my proof:



The rest of what you said is good.

**Comment by tpapp** [comment]
> If no one else acknowledges their own tradeoffs, then it may send the wrong message if we do.

Given how long outdated information survives on the internet by people who just keep repeating it without making an effort at understanding, I would assume that most languages don't do this because they don't want to deal with misinformation decades after the original issue is fixed or mitigated. Cf the classic "Lisp is slow".

Regarding the specific points

> direct people to JuliaHub to check on package availability and acknowledge the compiler latency

the [first paragraphs of the manual](https://docs.julialang.org/en/v1/) make it clear that Julia is JIT compiled, which implies that there will be a latency. This is [well known](https://en.wikipedia.org/wiki/Just-in-time_compilation#Startup_delay_and_optimizations) (the page, but not the subsection, is even linked there).

JuliaHub *should* be mentioned as a great resource in the manual though, but I am not sure that we need to suggest that readers check package availability. Generally, I think it is OK to assume that people are reasonably competent, and if package availability is a concern for what they do, they will do their homework.

**Comment by KristofferC** [comment]
This seems very strange to have in the Julia manual to me. I would vote for closing this PR.

**Comment by KristofferC** [comment]
(sorry, fat-fingered the close button).

**Comment by ronisbr** [comment]
IMHO, we should not add this information, at least in the current state, to the manual. For example:

* Less mature ecosystem than e.g. Python or C++, because Julia is still a young language (2012).

It really depends. In terms of ODE solver for control problems I work with, Julia just happens to have the best I have already used, considering both free and paid systems.

**Comment by StefanKarpinski** [comment]
It does seem that this PR is not going to be merged as is. It would be fine to add some pros and cons, including but not limited to the text I wrote about package load times.

**Comment by JeffBezanson** [comment]
I'm not opposed to listing negatives, but the issue is that documentation tends to be viewed as authoritative, e.g. somewhat of a specification. Documentation can also be somewhat aspirational, e.g. describing what *should* work, and ignoring bugs that happen to exist currently (except perhaps in a warning sidebar). There is definitely scope for something like this to be misconstrued as e.g. expressing an intent for julia to only work for scientific computing (whatever that means). Even though the manual now has many authors, it will generally be perceived as coming from the language designers/creators.

I think there is also a bit of a mismatch here in that it's comparing language features to the state of the ecosystem and implementation. I would expect anti-features to include e.g. static typing. Maybe this kind of thing could go under a "Should I use julia?" FAQ entry or something like that.

**Pull request closed without merging**
