### PR TITLE
gc: fix MEMDEBUG build

### PR DESCRIPTION
**Pull request by vtjnash**
Found this commit on my machine. I think it makes sense?

### CODE REVIEW

**Comment by yuyichao** [comment]
whats wrong with the current one?

**Comment by vtjnash** [comment]
I expect `gc_setmark` would crash on the first GC call

**Comment by yuyichao** [comment]
Because of the `jl_assume`? I think it was written this way to have the minimum conditional compilation possible.

**Comment by yuyichao** [comment]
And if it was `jl_assume` the fix should be to just remove `jl_assume`. It seems that the compiler should make that assumption anyway.

**Comment by vtjnash** [comment]
Yeah, that helps the compiler emit better code, but it's not valid here

**Comment by yuyichao** [comment]
I think the assume isn't needed here though if you want it can just be moved into ser_pool_

**Comment by vtjnash** [comment]
It helps skip several branches, and reflects the expectation on the loads on the subsequents statements.

**Comment by yuyichao** [comment]
> It helps skip several branches, and reflects the expectation on the loads on the subsequents statements.

The load is exactly why I said this is not needed. The compiler should be fully aware of that.
And as I said, if explicit documentation of such assumption is needed, it can just move into `gc_setmark_pool_` without having to tripple the number of related `#if(n)def MEMDEBUG`.

**Comment by vtjnash** [comment]
> The compiler should be fully aware of that

Last I checked, that'd be impossible for the compiler to know, but as I said, this was just a commit I found on my machine from awhile ago.

**Comment by yuyichao** [comment]
> Last I checked, that'd be impossible for the compiler to know, but as I said, this was just a commit I found on my machine from awhile ago.

It seems that the compiler does not use this info if the unconditional load is after the check (even if the load happens in both branches).

In any case, as I said, again, I think you can just move the `assume` into `gc_setmark_pool_`. It should do exactly the same thing with a much smaller patch and easier to maintain.

**Pull request merged**
