### PR TITLE
[release-0.5] Backports for 0.5.0-rc4

### PR DESCRIPTION
**Pull request by tkelman**
will probably be the last RC

@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

### CODE REVIEW

**Comment by nalimilan** [comment]
I guess it's too late for https://github.com/JuliaLang/julia/pull/17848?

**Comment by ViralBShah** [comment]
Should be possible, but we should probably run the package evaluator on it.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18276) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/07eb81e9ce2b5724dc5298a35f98091ccce16350/f817842_vs_e6f843b/report.md). cc @jrevels

**Comment by pabloferz** [comment]
Can #18200 and #18198 be considered?

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18276#issuecomment-243237105) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/aa56e75c1816d98b3abcfccb0d0e03402c0ee0a0/a752e1a_vs_e6f843b/report.md). cc @jrevels

**Comment by tkelman** [comment]
The precompilation changes here turned out to be pretty seriously breaking for roughly 46 packages: https://gist.github.com/f9174a738bdf0ba121d6c706a537038f

That's way more regressions than we can add in a release candidate, we'll need to fix these somehow.

**Comment by tkelman** [comment]
Isolated reproduction of a similar-looking failure that you should be able to try:
```
rm -rf ../jlpkgtmp && JULIA_PKGDIR=$PWD/../jlpkgtmp ./julia -e 'versioninfo(); Pkg.init(); Pkg.clone("BinDeps"); Pkg.checkout("BinDeps"); Pkg.add("BiomolecularStructures"); Pkg.free("BinDeps"); Pkg.test("BiomolecularStructures")'
```
output: https://gist.github.com/bdc92b697bf7ca1dadf9c35aea984c8b

**Comment by tkelman** [comment]
with the BinDeps change we're down to 18 new failures: https://gist.github.com/c75d469dcc9b5f7af6ef515113d8b1cd

**Comment by tkelman** [comment]
the latest commits shouldn't make too much difference to perf, but just in case
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

**Comment by ViralBShah** [comment]
#18301 is ready to go in here, and is all strictly conditional on Power. With that, the Power build passes all tests except threading, which seems to be a non-trivial amount of work. Thanks to @staticfloat the buildbots are running on power as well.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18276#issuecomment-243978497) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fdcb88abd876b6eaf157426b32515e8165f24a3b/1e6b3b4_vs_e6f843b/report.md). cc @jrevels

**Comment by ViralBShah** [comment]
I can't reproduce the precompilation failure with `BioMolecularStructures`. I do get a failure but that seems specific to the package:
```
ERROR: LoadError: LoadError: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named Bio.PDB',)
```

**Comment by ViralBShah** [comment]
Also, when I installed `Distances` and `Pkg.test()`ed it, I did not see any failure - even though Distances.jl is listed on the list of 18. 

In `BusinessDays`, the tests go into an infinite loop it seems.

**Comment by ViralBShah** [comment]
Looking at `StatsBase` failure, the error is in StatsBase tests. Thus, I think packages need to be tagged/updated etc., as perhaps things have changed between rc3 and rc4. Based on my small sample, I think this is not a base julia problem - and doesn't seem like precompilation issues.

**Comment by sbromberger** [comment]
I noticed LightGraphs was on the list. What do I need to do to get it ready for 0.5 / this change?

**Comment by ViralBShah** [comment]
@sbromberger I tested LightGraphs on rc4, and all tests pass for me.

**Comment by tkelman** [comment]
It is a precompilation issue, but it's triggered by running a sequence of steps that pkgeval does. Anything that happens on pkgeval could happen elsewhere, so there's a real problem here.

**Comment by ViralBShah** [comment]
I guess what I am saying is that I am unable to reproduce it on those packages I tried. Perhaps there needs to be a more complex set of steps than just wiping .julia. Do you have another case I can reproduce?

**Comment by tkelman** [comment]
Not yet. The above steps with BiomolecularStructures won't show an issue any more since I tagged BinDeps.

**Comment by ufechner7** [comment]
Is it known, why the Travis CI build failed?

**Comment by davidanthoff** [comment]
Is there some way that others can help to get RC4 out? Also, might it make sense to just release RC4 as is, and if more problems show up, just do a RC5?  We've been going with RC3 for two weeks now, and essentially that means that a lot of potential testers are not testing the latest bits.

**Comment by tkelman** [comment]
Help determine what's causing the regressions identified by packageevaluator. I'm not tagging an RC with known regressions, so will revert the precompilation changes if that's the necessary fix.

**Comment by bicycle1885** [comment]
The problem of Cairo.jl seems to have nothing to do with this change. In a clean environment on my OS X of this branch, I saw the same error as https://github.com/JuliaGraphics/Cairo.jl/issues/148. I believe this is a problem of BinDeps.jl. The problem happens on v0.5-RC3, too.

**Comment by bicycle1885** [comment]
I couldn't reproduce the test failure of Complementarity.jl. It seems to be under active development and there are two minor releases after the Package evaluator (https://github.com/chkwon/Complementarity.jl/releases). So, I guess the problem is not in Julia but in the tests of Complementarity.jl.

**Comment by lobingera** [comment]
@bicycle1885 Could you clarify which Cairo failure you see here? If i look into this https://github.com/JuliaLang/julia/pull/18276#issuecomment-243976526 i get the impression that runtest.jl fails with a signal(11) - and not the BinDeps problem you mention. I had some similar failure trying to build some PR for Cairo and indentified this a memory management / GC problem which is mostlikely a cairo internal problem and was hidden by some 'other' gc behaviour.

**Comment by tkelman** [comment]
Am hoping that #18366 will fix the issue. Once that PR has addressed its review I'll backport it in here and run pkgeval again, fingers crossed.

**Comment by tkelman** [comment]
@ufechner7 

> Is it known, why the Travis CI build failed?

I can't recall having seen this error before, but it looks intermittent. Not sure what it is or whether it also would occur on master.

```
	From worker 9:	     * spawn                       [stdio passthrough ok]
	From worker 8:	     * sorting               in  85.87 seconds, maxrss  625.10 MB
	From worker 9:	Test Failed
	From worker 9:	  Expression: desc == "Pipe(open => active, 0 bytes waiting)"
	From worker 9:	   Evaluated: "Pipe(open => active, 9 bytes waiting)" == "Pipe(open => active, 0 bytes waiting)"
```

**Comment by vtjnash** [comment]
looks like there's a race in that test

**Comment by tkelman** [comment]
Yes. If we see it again, should open an issue for it.

My pkgeval run last night froze on several packages doing Pkg.build on Cairo, but it happened for both rc3 and rc4 so it's not a regression, just a nasty bug that needs fixing.

**Comment by tkelman** [comment]
A fair amount going on here, but does look like the precompilation issue is mostly gone - https://gist.github.com/6715eba41378cb57642b79255d86a723

- AmplNLWriter has a bunch of huge C++ test dependencies and most likely ran out of time and got terminated
- `Unexpected HTTP status code: 500` network failures during clone for Anasol, ApproxFun, GeneralizedSampling, GeneticAlgorithms, and OpenGL (Anasol was the only one of these that wasn't already failing on rc3)
- BlsData is flaky and gets a `Request to BLS failed with message 'REQUEST_NOT_PROCESSED'` failure intermittently, not a Julia problem
- Cairo failed with ```Error in `/home/vagrant/julia/bin/julia': double free or corruption (!prev): 0x00000000028464c0 ***\n\nsignal (6): Aborted\nwhile loading /home/vagrant/.julia/v0.5/Cairo/samples/sample_imagepattern.jl, in expression starting on line 29``` which is most likely a problem in the package itself, should be looked at but I don't think it's a Julia regression
- ImageQuilting failed with a real error that I can reproduce outside of pkgeval ```TypeError: Tuple: in non-final parameter, expected Type{T}, got Type{Vararg{ParserCombinator.Transform,N}}\n in _include_from_serialized(::String) at ./loading.jl:150\n in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187\n in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217``` but I think it's the only one
- NEOS is flaky and gets a `LoadError: XML-RPC failed\n in _send(::NEOS.NEOSServer, ::String) at /home/vagrant/.julia/v0.5/NEOS/src/NEOSServer.jl:46` intermittently, not a Julia problem

**Comment by lobingera** [comment]
@tkelman I agree with your decision that the orignal problem is in the memory management of Cairo.jl (and libcairo). My assumption (without any background on details) is, work on GC has corrected something and now a hidden Cairo.jl problem surfaces. I can not currently spend time on debugging this.

**Comment by tkelman** [comment]
@staticfloat took the Linux buildbots down to rebuild gcc for https://github.com/dmlc/MXNet.jl/issues/138. Not the best timing, that should've waited until after this RC. Can't build binaries until they're back up.

**Comment by tkelman** [comment]
buildbots came back and the post-gcc-upgrade binaries look okay (thanks @staticfloat), so rc4 has been tagged and uploaded

**Pull request merged**
