### PR TITLE
Print warnings after system image building

### LINKED ISSUE #20958: Cannot build sys image- Win 64 0.5.1
I am trying to patch an earlier bug I reported on this website (regarding arrays with 6 or more subscripts) in 0.5.1.  However, the instructions for building a system image from the documentation are apparently not working for me.  This is Julia 0.5.1 for Windows 10 - 64 bit that I installed yesterday via the self-installer from the Julia download site.  I issued the commands:
```julia
julia> include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))
```
and
```
julia> build_sysimg(force=true)
```
After many lines flew by on my console window, eventually I received a message stating that the build was successful:
```
C:\Users\vavasis\AppData\Local\Julia-0.5.1\share\julia\base\precompile.jl
INFO: System image successfully built at C:\Users\vavasis\AppData\Local\Julia-0.5.1\bin\..\lib\julia\sys.ji
INFO: Julia will automatically load this system image at next startup
```

However, the old sys.dll was not overwritten as you can see from the date:

```
c:\Users\vavasis\AppData\Local\Julia-0.5.1\lib\julia>dir
 Volume in drive C is Windows8_OS
 Volume Serial Number is 88DB-A798

 Directory of c:\Users\vavasis\AppData\Local\Julia-0.5.1\lib\julia

2017-03-08  11:54 PM    <DIR>          .
2017-03-08  11:54 PM    <DIR>          ..
2017-03-08  11:52 PM         2,116,720 inference.ji
2017-03-08  11:52 PM         7,253,763 inference.o
2017-03-05  10:47 AM        42,798,819 sys-debug.dll
2017-03-05  10:37 AM        41,515,369 sys.dll
2017-03-08  11:54 PM        26,094,220 sys.ji
2017-03-08  11:54 PM        48,834,489 sys.o
               6 File(s)    168,613,380 bytes
               2 Dir(s)  26,042,474,496 bytes free
```

### PR DESCRIPTION
**Pull request by musm**
Print non critical compiler search warnings after system image building, otherwise the error gets lost due to the large number of printed statements

ref  https://github.com/JuliaLang/julia/issues/20958#issuecomment-312733004

close https://github.com/JuliaLang/julia/issues/20958

### CODE REVIEW

**Comment by tkelman** [comment]
multiple warnings can happen, should append instead of overwrite

**Comment by musm** [comment]
> multiple warnings can happen, should append instead of overwrite

By that do you mean to print the warning's twice: once where they show up and then again afterwards?

**Comment by tkelman** [comment]
that may be a good idea, but that wasn't what I meant, no. append to `warn_msg` instead of ignoring any previously set warnings

**Comment by musm** [comment]
Updated PR

**Comment by musm** [comment]
anything else to do here?

**Comment by musm** [comment]
timed out on travis 32

**Pull request merged**
