### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by raminammour**
This took me a while to figure out, and found it in some obscure corner on discourse. It would be good to add it to the docs.

Feel free to change the wording or the example, or correct it for a more "official" way of doing the same.

Cheers

### CODE REVIEW

**Comment by ararslan** [comment]
This looks good to me, thanks for the example! Though I think we've been doing Pkg-related development in a separate repo then merging the changes here, so perhaps this should be opened against that repo instead? I'm not sure though, so I'll ping @KristofferC.

**Comment by KristofferC** [comment]
Yes, we try to keep the development in the Pkg.jl repo. In fact the docs are updated there to be a bit more clear on this point. Perhaps you can look over the new docs and see if there is still a need for clarification?

**Comment by raminammour** [comment]
The issue with the docs is that they don't specify that the right way to add a local (non git dependency is with `dev` and not `add`). Also, issuing an `add` commands returns a not-so-helpful-error:
```
ERROR: GitError(Code:ENOTFOUND, Class:Repository, could not find repository from '/PATH/TO/PACKAGE')
```
This can either be fixed to have `add` work for local packages or documented. I will make a PR in Pkg.jl.

**Comment by KristofferC** [comment]
The current docs contain:


> ##### Adding a local package
>Instead of giving a URL of a git repo to add we could instead have given a local path to a git repo. This works similarly to adding a URL. The local repository will be tracked (at some branch) and updates from that local repo are pulled when packages are updated. Note that changes to files in the local package repository will not immediately be reflected when loading that package. The changes would have to be committed and the packages updated in order to pull in the changes.

and

> If dev is used on a local path, that path to that package is recorded and used when loading that package.

I agree the error message could be improved for `add` on non git repos.

**Pull request closed without merging**
