### PR TITLE
RFC: New manual front end

### PR DESCRIPTION
**Pull request by mortenpi**
Just a preliminary RFC with the new manual front end. Here is the latest demo:

> https://mortenpi.eu/gsoc2019-mockups/bulma/v16/

Other than bumping Documenter (to a branch version currently), it also swaps out the logo for an SVG version (PNG currently). And as the new front end supports a dark theme, we actually need two variants of the logo.

Ref: JuliaDocs/Documenter.jl#1091, JuliaDocs/Documenter.jl#1043

- [x] Compat admonition styling
- [x] Documenter 0.24.0 release
- [x] Update `doc/Manifest.toml` to use a released Documenter version

### CODE REVIEW

**Comment by vchuravy** [comment]
Uh! This looks good. Only comment I had is that versions are rendered without a dot e.g. `v12` instead of `v1.2` in the version selector and the urls (http://mortenpi.eu/gsoc2019-mockups/bulma/v12/manual/mathematical-operations/)

**Comment by bicycle1885** [comment]
Looks really cool! Let me leave a comment. The red code color looks a little bit too vivid to my eyes. How about making it slightly darker?

**Comment by mortenpi** [comment]
@vchuravy The versions there are actually the versions of the front end, and not of Julia.

Played around a bit more with the colors and a few other things -- new version here: https://mortenpi.eu/gsoc2019-mockups/bulma/v13/julia/

**Comment by crstnbr** [comment]
I love it! Looks really fresh. And the ability to fold navigation submenus is very much appreciated! As a side comment, maybe it's just me but I feel the color for inline code (darkish red) and those for the highlight boxes (very vivid blue/yellow etc) clash a tiny bit. Not by much but still noticeable. I don't want to be nitpicky but just wanted to leave it as a comment. Again, awesome work!

**Comment by mbauman** [comment]
This is great!  Just one small (subpixel) nit: this appears to disable subpixel font rendering on (at least) macOS/Chrome.  With my old non-retina screen, it makes things look pretty crummy.  Compare:

Screen Shot 2019-08-13 at 12 36 08 PM



The old is on the left and the new is on the right — note the blue and red shading on the left but not on the right.

**Comment by mortenpi** [comment]
Hmm, it seems to be fine on Ubuntu / Chrome 76?

[subpixel](https://user-images.githubusercontent.com/147757/63132107-183c6180-c014-11e9-9321-2dfa13cb9e5c.png)

Interestingly, unlike in the original manual, Bulma actually sets `-webkit-font-smoothing: antialiased;`, which is what should enable this. Although, there is also `-webkit-font-smoothing: subpixel-antialiased;`?

@mbauman Could you go in with developer tools and try changing `-webkit-font-smoothing` on the `<html>` element, to see what happens if you (1) disable it altogether (equivalent to old style if I am not mistaken), and (2) set it to `-webkit-font-smoothing: subpixel-antialiased`? On my system is does not seem to make any difference though.

**Comment by mbauman** [comment]
That does the trick!  Also removing that property entirely also gets it rendering with subpixel antialiasing.

**Comment by mortenpi** [comment]
Superseded by #33922

**Comment by mortenpi** [comment]
Actually, no. #33922 was missing some updates necessary for the new front end.

**Comment by mortenpi** [comment]
This is good to go now. Latest [demo available here](https://mortenpi.eu/gsoc2019-mockups/bulma/v16/). Also bumps Documenter to 0.24.1 to fix a PDF building bug.

**Pull request merged**
