### PR TITLE
[WIP][DO NOT MERGE] preparation work for llvm 7.0.0

### PR DESCRIPTION
**Pull request by vchuravy**
- filter patch list
- bump magic number

### CODE REVIEW

**Comment by vchuravy** [comment]
Tested with:

```
LLVM_VER = 7.0.0rc1
override LLVM_SRC_URL := http://prereleases.llvm.org/7.0.0/rc1
```

Patches that need update
- [ ] D44650
- [ ] D50010
- [ ] D50167
- [ ] symver-jlprefix

@Keno do you have bandwith to update D50010/D50167? Since that also means that they probably don't apply to master anymore.

**Comment by Keno** [comment]
Yeah, I can take a look at that.

**Comment by vchuravy** [comment]
Yeah that seems pretty accurate. `llvm-6.0-DISABLE_ABI_CHECKS.patch` has fallen through the cracks and I didn't submit it to upstream yet.

#23611 I suspect the larger discussion that Keno wanted to have is how frontends are supposed to handle custom address spaces. One alternative is https://github.com/JuliaLang/julia/issues/22414

**Comment by robsmith11** [comment]
Is there any work remaining for LLVM 7 or should it "just work" if I try building from source with these patches?

**Comment by chriselrod** [comment]
Whether I try `LLVM_VER=7.0.0rc1`, 7.0.0, or 7.0.1, I get:
```
patching file tools/llvm-cfi-verify/CMakeLists.txt
Hunk #1 FAILED at 11.
1 out of 1 hunk FAILED -- saving rejects to file tools/llvm-cfi-verify/CMakeLists.txt.rej
make[1]: *** [/home/chriselrod/Documents/languages/julia-latest/deps/llvm.mk:435: /home/chriselrod/Documents/languages/julia-latest/deps/srccache/llvm-7.0.0rc1/llvm-6.0-D44650.patch-applied] Error 1
make: *** [Makefile:57: julia-deps] Error 2
```
I merged this PR into master, because this PR would give me OpenBLAS build errors.

**Comment by vchuravy** [comment]
I haven't found time to update the two patches that currently don't apply.
So that's why this is DNM.

**Comment by eli-schwartz** [comment]
> Is there any work remaining for LLVM 7 or should it "just work" if I try building from source with these patches?

This PR is not about updating the julia code to compile against llvm 7 -- it is about revendoring the set of custom patches used when building with a vendored llvm.

If you want to compile against llvm 7, you'll need to start with e.g. the last two commits on https://github.com/eli-schwartz/julia/commits/llvm7 and then continue to adapt to other llvm changes, which requires a lot more work than just updating the llvm source tarball.

You can test it by configuring julia to build with an existing system version of llvm and noting the various compiler errors -- I fixed the first two, then gave up when it traveled into C++ template hell.

**Comment by vtjnash** [comment]
replaced by #31849

**Pull request closed without merging**
