### PR TITLE
sroa: Lift restriction that all_same optimization must give SSAValue

### PR DESCRIPTION
**Pull request by Keno**
This restriction has been in there since this code was added in #44557. Unfortunately, I can't tell from the commit history why this restriction was added. It's possible that it was trying to avoid putting things into statement position that were not allowed in the phi block, but we have cleaned that up since (#50308 and related), so let's see if this restriction is still required, since I was seeing some suboptimial optimization results because of this.

### CODE REVIEW

**Comment by Keno** [comment]
@nanosoldier runtests()

**Review by aviatesk — COMMENTED** [review]
The base test suite seems to be successful on this PR.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52338#issuecomment-1830839671) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5179b1c_vs_de525af/report.html) is available.

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["GridapGmsh", "FlexPlan", "PowerModelsWildfire", "SegregatedVMSSolver", "CbaOPF", "Krotov", "TopoPlots", "LIBLINEAR", "Gtk4", "GraphViz", "FileWatching"], vs = ":master")`

**Comment by Keno** [comment]
FWIW, I found the bug that showed up on PkgEval, but it unraveled a whole thread, so standby for that

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52338#issuecomment-1835088692) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/74b8b6a_vs_58c1d51/report.html) is available.

**Comment by Keno** [comment]
Sanity check to make sure I actually fixed the bug:
@nanosoldier `runtests(["PowerAnalytics", "SetProg", "GraphViz", "Gtk4", "REopt", "Biofilm", "NonconvexBayesian", "FourierTools", "SciMLBase", "Tidier", "GridapGmsh", "Scruff", "TSML", "MRISimulation", "PlantRayTracer", "ReliabilityOptimization", "PowerModelsWildfire", "ImageFeatures", "ObservableCortex", "XGPaint", "MCPTrajectoryGameSolver", "AiidaDFTK", "ONSAS", "FileWatching", "GridVisualize", "PowerModelsDistribution", "Polynomials4ML", "FlexPlan", "CbaOPF", "QUnfold", "SensitivityRankCondition", "CombinatorialSpaces", "AlgamesDriving", "QuartetNetworkGoodnessFit", "DynamicMovementPrimitives", "MiseEnPage", "CausalForest", "EditorsRepo"])`
However, I'd like to run a full PkgEval afterwards anyway, because I did some fairly significant code re-arragements, so I want to make sure nothing else broke.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52338#issuecomment-1836986476) has completed - no new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ae2d3cd_vs_58c1d51/report.html) is available.

**Comment by Keno** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52338#issuecomment-1837016600) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ae2d3cd_vs_58c1d51/report.html) is available.

**Comment by Keno** [comment]
@nanosoldier `runtests(["StenoGraphs", "ModiaPlot_WGLMakie", "BSeries", "HmtArchive", "PowerModelsDistribution", "MLJTestIntegration", "CompressiveLearning", "OptimalTransmissionRouting", "TaylorModels", "Pesto", "PowerModelsACDC", "ConstraintTrees", "DiscretePIDs", "Consensus", "EMpht", "FlowAtlas", "Syslogs", "GameTheory", "ReliabilityOptimization", "PALEOmodel", "GeneralizedRouwenhorst", "MiseEnPage", "AiidaDFTK", "Biplots", "HashCode2014", "KelvinletsImage", "ChaosTools", "FractalDimensions", "MRICoilSensitivities", "MRISimulation", "QuantumDynamics", "Oxygen", "PlantMeteo", "GeoParams", "GlobalSensitivity", "LibTrixi", "SMLMMetrics", "FMIImport", "GIFImages", "ReferenceTests", "MixedModels", "Permanents", "Yunir", "MINDFulMakie", "MadNLP", "AutoBZCore"])`

**Pull request merged**
