### PR TITLE
Deprecate Base.Distributed

### PR DESCRIPTION
**Pull request by vchuravy**
@amitmurthy any reason why this was commented out in #24443?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
cc @amitmurthy

**Comment by amitmurthy** [comment]
It caused the AV build to fail - https://github.com/JuliaLang/julia/pull/24443#discussion_r156871233 - as seems to have happened here too.

**Comment by vchuravy** [comment]
Yeah I noticed that, just pushed a fix that passes locally for me. We do
kinda need a Deprecation warning for 0.7 ;)

**Comment by amitmurthy** [comment]
> We do kinda need a Deprecation warning for 0.7 ;)

From a consistency point of view, yes. Practically, no. Because the `Distributed` name was never required to be used as all `Distributed` exports were re-exported once again from `Base`. `Distributed` module was not mentioned in the documentation.

I guess this PR now also closes https://github.com/JuliaLang/julia/issues/25077 ?

**Pull request closed without merging**
