### PR TITLE
Avoid creating a closure for each log message

### LINKED ISSUE #25909: Logging macros generated code quality
I noticed some badly inferred generated code after switching from `info` to `@info`, and wondered whether this is known/expected.

Repro:

```julia
function bar(a)
    @assert a == 0

    x = rand(UInt32)
    if x == 0
        throw(1)
    else
        info("$x")
        # or
        @info "$x"
    end

    return nothing
end

code_warntype(bar, Tuple{Int})
```

With `info`, this generates code with two `Union{}` return paths, and otherwise no badly typed values (ie. nothing red in `code_warntype`).

Using `@info`, there's now a `Core.Box`, an abstract `Base.CoreLogging.AbstractLogger`, and an `Any` from `Base.CoreLogging.shouldlog`. Performance is bad too, increased from ~3ns to ~45ns (tested on latest master).

Part of this issue relies on the exact structure of `bar`, eg. removing the `@assert` removes the box and restores performance, but keeps the `Base.CoreLogging.AbstractLogger`. So there's probably something more subtle going on here.

cc @c42f 

EDIT: changed from `error` to `info`, I was confused about the behavior of `@error`.

### PR DESCRIPTION
**Pull request by c42f**
Closures aren't strictly required for delayed log message creation, so we can remove them to avoid #15276 and reduce the load on the compiler.

This should fix #25909 (CC @maleadt).

[Edit: changed the description for clarity]

### CODE REVIEW

**Comment by maleadt** [comment]
Ah, too bad, delayed message was a valuable feature for me. Maybe a secondary API (`@if_debug`), or keyword option to eg. `@debug`, could offer similar functionality?

**Comment by JeffBezanson** [comment]
Would it make sense to create a closure only if the message requires computation, i.e. isn't a constant string?

**Comment by c42f** [comment]
There's a misunderstanding here (my fault for being unclear): this change doesen't modify the public logging API and message computation is still deferred until `shouldlog(current_logger(), some_static_info)` returns true.

The only thing which changes is an implementation detail:
* Create a message generation closure and pass it to an internal function which later executes it, vs
* Just insert the try/catch inline in the caller, along with the message generation code.

**Comment by c42f** [comment]
CI errors seem unrelated (I restarted the OSX build which had a weird failure in the spawn tests, probably wasn't worth it though).

If there's no objections to the newly cleaned up explanation I'll merge this in the next day or so.

**Pull request merged**
