### PR TITLE
Make `simd_inner_length` generic fallback less specific

### PR DESCRIPTION
**Pull request by chethega**
Changed specifity of `simd_inner_length` and `simd_index` generic fallbacks in order to simplify opt-out for custom iterators that do not support random access. Of course such iterators cannot successfully `simd`, but they can at least work such that the optimistic `@simd` annotation does not cause an error.

Without this patch, this is somewhat inconvenient, since one gets method ambiguities unless one hard-codes the return type of the custom iterator. 

I hope this breaks nothing. 

Before: 
```
julia> r=rand(10).>0.5;
julia> li = Base.LogicalIndex(r);
julia> for i in li
       i
       end
julia> @simd for i in li
       i
       end
ERROR: getindex not defined for Base.LogicalIndex{Int64,BitArray{1}}

julia> begin
       T = typeof(li)
       Base.SimdLoop.simd_index(v::T, j, i) = j
       Base.SimdLoop.simd_inner_length(v::T, j) = 1
       Base.SimdLoop.simd_outer_range(v::T) = v
       end

julia> @simd for i in li
       i
       end
ERROR: MethodError: Base.SimdLoop.simd_inner_length(::Base.LogicalIndex{Int64,BitArray{1}}, ::Int64) is ambiguous. Candidates:
  simd_inner_length(v::Base.LogicalIndex{Int64,BitArray{1}}, j) in Main at REPL[5]:4
  simd_inner_length(r, j::Int64) in Base.SimdLoop at simdloop.jl:47
Possible fix, define
  simd_inner_length(::Base.LogicalIndex{Int64,BitArray{1}}, ::Int64)

julia> begin
       T = typeof(li); RT = Int64
       Base.SimdLoop.simd_index(v::T, j::RT, i) = j
       Base.SimdLoop.simd_inner_length(v::T, j::RT) = 1
       Base.SimdLoop.simd_outer_range(v::T) = v
       end

julia> @simd for i in li
       i
       end
```

After:
```
julia> r=rand(10).>0.5;
julia> li = Base.LogicalIndex(r);
julia> @simd for i in li
       i
       end
ERROR: getindex not defined for Base.LogicalIndex{Int64,BitArray{1}}

julia> begin
       T = typeof(li)
       Base.SimdLoop.simd_index(v::T, j, i) = j
       Base.SimdLoop.simd_inner_length(v::T, j) = 1
       Base.SimdLoop.simd_outer_range(v::T) = v
       end

julia> @simd for i in li
       i
       end
```

As an aside, do we want docs for simd opt-out for custom iterators? Or do these docs exist and I failed at RTFM?

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
Would be great to have a test for this!

**Comment by chethega** [comment]
I think this is done for now, if all tests pass. I would appreciate a backport.

At the next good opportunity for minor changes, I think it would be nice if we could change the default: `AbstractArray`, `Broadcasted`, etc get the current simdloop, default fallback gets the variant introduced here. Realistically, that should not break any code; but it might slow down some `@simd` loops on custom array-like types that are not `<:AbstractArray`, until authors catch up. That would be a separate PR/discussion, though. 

This came up in `LightGraphs.jl`, that optimistically `@simd`-annotates several loops, which speeds up the most important graph implementations, but fails for nonstandard graph implementations. Technically, this is a bug in LightGraphs: Only `@simd` if your interface specified that iterators must support `@simd` or are arraylike. Practically, it is more pragmatic for non-arraylike iterators to opt out of simd, instead of requiring more support for fringe implementations. 

With this patch, this gets less bothersome; if the default were to change, then this would become a complete non-issue, and code like `@simd for x in col` would also work for e.g. dictionaries, despite the invalid `@simd` annotation.

**Comment by vchuravy** [comment]
Hm, I would rather have this be a property derived from the iteration traits. It is unfortunate that users would have to extend an internal/unexported interface.

**Comment by chethega** [comment]
I agree: It would be nice if we had a proper interface / trait, such that people could easily do things like opt out of simd, opt into array-like simd or opt into flattened-vector-of-vector simd. Constructions like `enumerate` inherit their parent's simd-style, abstract array or broadcast have array-style, and iterator constructions like `filter` get opted out. All `Base` iterators (`BitSet`, `Dict`, etc) could become compatible with optimistic `@simd` annotations.

Downside is that this would complicate the simdloop code, and be yet another surprising trait that people need to overload. 

So I am not sure whether a large refactor is worth it: This only really comes up if you need to interface with arguably incorrect upstream code (i.e. upstream code that is very optimistic with sprinkling `@simd` everywhere). If the iterator is not custom, e.g. if I wanted to pass a `BitSet` into upstream code that optimistically uses `@simd` because it implicitly expected a sorted vector of integers; well, piratically extend `Base.simd_inner_length` etc for `BitSet`. This extension is canonical, in the sense that there is only a single extension that is useful; if any other modules engaged in similar piracy, then everything is still fine. And with this PR, the necessary overload is both documented an less prone to causing ambiguity errors.

**Comment by chethega** [comment]
Bump. I think the ci error is unrelated.

**Comment by vchuravy** [comment]
I am fine with reducing the specificity of the methods. I dislike documenting this as a the official way to do this.

**Comment by chethega** [comment]
Sorry for misunderstanding the change request. 

Ok now? If someone runs into the issue of needing to work with optimisitic `@simd`, they are likely to find the source comment and save some time before coming up with the same solution.

**Comment by vchuravy** [comment]
Thanks!

**Pull request merged**
