### PR TITLE
refactor withtag in html markdown

### PR DESCRIPTION
**Pull request by hayd**
some code simplification

cc @one-more-minute

### CODE REVIEW

**Comment by one-more-minute** [comment]
Great stuff, simplifying code is never a bad thing.

The only thing I think would be a nice addition is to define
```julia
tag(args...) = withtag(nothing, args...)
```
and call that instead of `withtag(nothing, ...)`, only for the sake of clarity in that case.

**Comment by hayd** [comment]
Good idea, I didn't like the `withtag(nothing, ...` either :)

**Comment by hayd** [comment]
done!

**Comment by one-more-minute** [comment]
Nice work, thanks. Sorry about the wait.

**Comment by hayd** [comment]
@one-more-minute Hmm there's actually a few other places in Base where this function could be useful (where a writemime for text/html is defined), I wonder if this should go somewhere else or is markdown is included early enough for these to work?

e.g. https://github.com/JuliaLang/julia/blob/2c34c36b17662823a94d90bf392f4778bd3fbd8c/base/methodshow.jl#L106

**Comment by one-more-minute** [comment]
I'm not against moving it if there's a good home for it somewhere else, but I'm not sure where that would be. If you wanted to try writing the methodshow stuff you're welcome to, I think Markdown.jl is probably defined early enough that it's usable from there.

**Pull request merged**
