### PR TITLE
Cleanup lapack.jl

### PR DESCRIPTION
**Pull request by jakebolewski**
- remove error checking macros
- check for error's consistently
- try to adhere to some semblance of standard formatting

### CODE REVIEW

**Comment by kshyatt** [comment]
:100:

**Comment by tkelman** [comment]
You're having too much fun with `gesdd` and `gesvd`. Or maybe not enough.

**Comment by jakebolewski** [comment]
@tkelman any clues as to these `ENOSPC` error's?

**Comment by tkelman** [comment]
docker quotas? ref https://github.com/travis-ci/travis-ci/issues/5241, maybe try a branch build with `group: edge` to see if we pass there? how big are the temp files our tests create?

**Comment by jakebolewski** [comment]
I am going to merge as the appveyor failure is unrelated.

**Comment by KristofferC** [comment]
Nice job.

**Pull request merged**
