### PR TITLE
REPL: hide any prints to stdio during `complete_line`

### LINKED ISSUE #55612: repl completion shows qualification warning inline
```
julia> using Downloads

julia> download(WARNING: both Downloads and Base export "download"; uses of it in module Main must be qualified
```

i.e. typing `download(` will cause the warning to print.

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/55612

### CODE REVIEW

**Comment by Keno** [comment]
I'm ok with it, but it's very much a hack and we should aim to remove it again in the future.

**Comment by IanButterworth** [comment]
@vtjnash is https://github.com/JuliaLang/julia/pull/55958 fixable and backportable? If so this could use `devnull`. If not maybe this should be merged as-is using `Pipe()` as this needs backporting.

**Comment by IanButterworth** [comment]
Bump. https://github.com/JuliaLang/julia/issues/55612 is pretty awkward with tab completion hinting on. It'd be great to get this fixed in 1.11.1

**Comment by IanButterworth** [comment]
@vtjnash @Keno i will merge as is in an hour or so unless I hear otherwise. 

I want to fix this issue for 1.11.1

**Review by vtjnash — COMMENTED** [review]
This introduces a deadlock-prone construct (stdout should typically not be pointed to a Pipe, especially on Windows), and a data-race on changing stdout, both of which are somewhat risky additions :/

**Comment by IanButterworth** [comment]
Thanks for the review. I'll revert. Any ideas on what would be a good fit for fixing #55612?

**Comment by vtjnash** [comment]
Delete it? I am not sure why it exists, since the resulting UndefVarError would have printed a more correct message immediately afterwards, and the printed warning happening first just makes the printing look bad:
```
julia> download
WARNING: both Downloads and Base export "download"; uses of it in module Main must be qualified
ERROR: UndefVarError: `download` not defined in `Main`
Hint: It looks like two or more modules export different bindings with this name, resulting in ambiguity. Try explicitly importing it from a particular module, or qualifying the name with the module it should come from.
Hint: a global variable of this name also exists in Base.
```

**Comment by IanButterworth** [comment]
Ok, yeah, I've done that here https://github.com/JuliaLang/julia/pull/56103

But that hinting isn't quite as good on 1.11 so what do do there still needs figuring out.
```
julia> using Downloads

julia> download
WARNING: both Downloads and Base export "download"; uses of it in module Main must be qualified
ERROR: UndefVarError: `download` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Base.
```

**Comment by IanButterworth** [comment]
I've backported https://github.com/JuliaLang/julia/pull/53469 so https://github.com/JuliaLang/julia/pull/56103 can be backported.

**Pull request merged**
