### PR TITLE
Remove conv2 from base

### PR DESCRIPTION
**Pull request by lbollar**
Referencing [#18384](https://github.com/JuliaLang/julia/issues/18384)

### CODE REVIEW

**Comment by tkelman** [comment]
It should either be deprecated or give a descriptive error about what the replacement is.

**Comment by lbollar** [comment]
In the thread I believe it is an outside package and function imfilter from [here](https://github.com/JuliaImages/ImageFiltering.jl) . Should a depwarn just be used here mentioning this package and function?

Sorry didn't understand deprecation process well before.

**Comment by ararslan** [comment]
You could take a look at how `isprime` et al. have been removed from Base. In that case the error message points directly to the Primes.jl package.

**Comment by lbollar** [comment]
I used depwarn with similar style to isprime and moved function to deprecated.jl. Would it be better to remove it from base and use an error message?

**Comment by ararslan** [comment]
Looks like @JeffBezanson has a more comprehensive plan for these things (see https://github.com/JuliaLang/julia/issues/18384#issuecomment-253263706), so he would probably be the best person to ask here.

**Comment by KristofferC** [comment]
DSP is now removed.

**Pull request closed without merging**
