### PR TITLE
[src] Fix compilation of `crc32.c` on aarch64 with Clang

### LINKED ISSUE #44885: `'++crc' is not a recognized feature for this target (ignoring feature)` when compiling `src/crc32c.c` on the M1
```console
% rm -f crc32c.o; make crc32c.o
    CC src/crc32c.o
'++crc' is not a recognized feature for this target (ignoring feature)
'++crc' is not a recognized feature for this target (ignoring feature)
```
Any idea where the feature `++crc` is coming from?  I suspect it's spelled incorrectly?  The double plus looks suspciously wrong.  I found https://github.com/JuliaLang/julia/blob/559244b383cf1a146f6c8e4ed81b1b746276abe0/src/crc32c.c#L207 but I don't think we go through that code path (putting an `#error` doesn't trigger an error).  We also see this message in CI: https://buildkite.com/julialang/julia-master/builds/10805#8c4ef317-52a8-43b2-a26e-3fca0ee337e3/220-1076

### PR DESCRIPTION
**Pull request by giordano**
Compilation of this file on aarch64 Linux with Clang currently fails with

```console
$ make crc32c.o CC=clang
    CC src/crc32c.o
In file included from /home/mose/repo/julia/src/crc32c.c:45:
In file included from ./julia_internal.h:1021:
In file included from /home/mose/repo/julia/usr/include/libunwind.h:7:
/home/mose/repo/julia/usr/include/libunwind-aarch64.h:60:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wc++-compat]
typedef struct
        ^
/home/mose/repo/julia/usr/include/libunwind-aarch64.h:169:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wc++-compat]
typedef struct unw_tdep_save_loc
        ^
/home/mose/repo/julia/src/crc32c.c:339:22: warning: unused function 'crc32c_dispatch' [-Wunused-function]
static crc32c_func_t crc32c_dispatch(unsigned long hwcap)
                     ^
'++crc' is not a recognized feature for this target (ignoring feature)
'++crc' is not a recognized feature for this target (ignoring feature)
/home/mose/repo/julia/src/crc32c.c:212:9: error: instruction requires: crc
    asm("crc32cx %w0, %w1, %2" : "=r"(res) : "r"(crc), "r"(val));
        ^
<inline asm>:1:2: note: instantiated into assembly here
        crc32cx w0, w0, x1
        ^
/home/mose/repo/julia/src/crc32c.c:218:9: error: instruction requires: crc
    asm("crc32cw %w0, %w1, %w2" : "=r"(res) : "r"(crc), "r"(val));
        ^
<inline asm>:1:2: note: instantiated into assembly here
        crc32cw w0, w0, w1
        ^
/home/mose/repo/julia/src/crc32c.c:224:9: error: instruction requires: crc
    asm("crc32ch %w0, %w1, %w2" : "=r"(res) : "r"(crc), "r"(val));
        ^
<inline asm>:1:2: note: instantiated into assembly here
        crc32ch w0, w0, w1
        ^
/home/mose/repo/julia/src/crc32c.c:230:9: error: instruction requires: crc
    asm("crc32cb %w0, %w1, %w2" : "=r"(res) : "r"(crc), "r"(val));
        ^
<inline asm>:1:2: note: instantiated into assembly here
        crc32cb w0, w0, w1
        ^
3 warnings and 4 errors generated.
make: *** [Makefile:217: crc32c.o] Error 1
```

Compilation on aarch64 macOS with Apple Clang is successful, but there is still
the message about the unrecognized feature:

```console
% rm -f crc32c.o; make crc32c.o
    CC src/crc32c.o
'++crc' is not a recognized feature for this target (ignoring feature)
'++crc' is not a recognized feature for this target (ignoring feature)
```

It appears GCC and Clang disagree on how the target attribute should be
specified: GCC wants `"+crc"`, while Clang wants `"crc"`.  Also Android's zlib
uses `"crc"` only when building with Clang: <https://android.googlesource.com/platform/external/zlib/+/refs/tags/android-platform-12.1.0_r2/crc32_simd.c#187>.

With this change, compilation of Julia on aarch64 Linux with Clang is now
successful.

Fix #44885.

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]
Looks good to me!  Nice work tracking this down!

For further proof that GCC wants `+crc`, just check out [the header file](https://github.com/gcc-mirror/gcc/blob/7b4495d3c4040d8f56c05dd254d76269d4471623/gcc/config/arm/arm_acle.h#L704) mentioned in the comments of the android source file.

**Comment by yuyichao** [comment]
Does this actually work? I thought clang still doesn't support the ifunc attribute. You might need to also condition the ifunc part on gcc as well.

**Comment by giordano** [comment]
> Does this actually work?

What do you mean by "work" here and how do I verify that? I verified at least that compilation of Julia is successful and without messages about unrecognised features on both Linux and macOS when using clang.

> You might need to also condition the ifunc part on gcc as well.

Where exactly?

**Comment by yuyichao** [comment]
I mean whether the crc function actually works as intended.

I forgot that we do have compile time detection for whether the compiler support ifunc so there shouldn't be any need to change the code here. I thought it might be necessary since clang is warning about the dispatch function being unused, which should only happen if it picked the ifunc version. (i.e. both crc32c_dispatch and JL_CRC32C_USE_IFUNC are defined). I guess it's probably just a clang warning bug then.... Which clang version are you using? 13.0.1 seems to support ifunc and also not having the spurious warning.

**Comment by giordano** [comment]
> I mean whether the crc function actually works as intended.

I ran the tests in `test/loading.jl` (the only place in Base I know it uses crc32 functionality) and they are successful.  I also compared the output of `Base._crc32c` on this branch vs master for a few different input types (UInt, IOBuffer, String, SubArray{UInt8}), and they all gave the same answers.  Let me know if you have other ways to make sure crc works as intended.

> I forgot that we do have compile time detection for whether the compiler support ifunc so there shouldn't be any need to change the code here. I thought it might be necessary since clang is warning about the dispatch function being unused, which should only happen if it picked the ifunc version. (i.e. both crc32c_dispatch and JL_CRC32C_USE_IFUNC are defined). I guess it's probably just a clang warning bug then.... Which clang version are you using? 13.0.1 seems to support ifunc and also not having the spurious warning.

On macOS I'm using Apple Clang 13 (which is implicitly required by #44347, but I'm not sure you can get an older version on this architecture), and vanilla Clang 13 on Linux.

**Pull request merged**
