### PR TITLE
[release-0.5] backports for 0.5.1

### PR DESCRIPTION
**Pull request by tkelman**
this is way overdue, ~~and still in progress making my way through the list of pending backports~~

will run pkgeval and nanosoldier here when ready

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@3c9d75391c72d7c32eea75ff187ce77b2d5effc8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20736#issuecomment-283351418) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9acaecf6d27bd45eb4250054b43297920a128fab/b6d6b9e_vs_3c9d753/report.md). cc @jrevels

**Comment by tkelman** [comment]
pkgeval identified some regressions here that I'll have to bisect on (any help would be appreciated): https://gist.github.com/anonymous/4178d02e88176194746115ff641a21b5

**Comment by tkelman** [comment]
@JeffBezanson the backport of #18493 broke ASTInterpreter. If you aren't aware of a fix for that
```
LoadError: local variable T not defined
 in _step_expr(::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:580
 in step_expr at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:666 [inlined]
 in #finish!#81(::Bool, ::Bool, ::Function, ::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:1720
 in finish!(::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:1705
 in _step_expr(::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:625
 in step_expr at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:666 [inlined]
 in #finish!#81(::Bool, ::Bool, ::Function, ::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:1720
 in finish!(::ASTInterpreter.Interpreter) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:1705
 in execute_command(::ASTInterpreter.InterpreterState, ::ASTInterpreter.Interpreter, ::Val{:finish}, ::String) at /home/vagrant/.julia/v0.5/ASTInterpreter/src/ASTInterpreter.jl:1388
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/vagrant/.julia/v0.5/ASTInterpreter/test/stepping.jl, in expression starting on line 37
while loading /home/vagrant/.julia/v0.5/ASTInterpreter/test/runtests.jl, in expression starting on line 6
```
then I'm going to revert f32c0ed6b8c060b4012f8957bc9d52d1761eac4b.

**Comment by tkelman** [comment]
cc @denizyuret I think the failure in Knet.jl (log at https://gist.github.com/8ab4a5e8f0e56370221cbe39924e41fa) is intermittent, I can get it to happen even on 0.5.0 but it requires re-running the tests multiple times to get to happen. So don't think that's a real regression that any of the backports here caused.

**Comment by tkelman** [comment]
The failure in OrdinaryDiffEq is a wrong `if VERSION` in its tests (https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/1f473b4df3f398616735d650a93c51d76b4a4230), meaning it isn't loading a necessary test dependency which causes an `UndefVarError` starting at the very first commit that changed VERSION after the 0.5.0 tag. Also not a regression caused by a backport.

**Comment by tkelman** [comment]
merge commit for PR, currently 0cc7d79: @nanosoldier `runbenchmarks(ALL, vs = "@3c9d75391c72d7c32eea75ff187ce77b2d5effc8")`

I've reverted the conversion change.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20736#issuecomment-284197630) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6a9db6f6c74eb139c100a0306b939cbcb87d8f56/272d9e5_vs_3c9d753/report.md). cc @jrevels

**Comment by tkelman** [comment]
pkgeval results: https://gist.github.com/5b71a57370610d91495f79004f58f354

both failures, InformationMeasures.jl and Tensors.jl, are flaky tolerances.

**Comment by timholy** [comment]
Woot!

**Pull request merged**
