### PR TITLE
[release-0.5] fix type stability of unrelated function after precompile

### PR DESCRIPTION
**Pull request by vtjnash**
(this bug also exists on master, but in a different form so it needs a different fix there)

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
I assume @tkelman will merge this when he wants it (since it is directly targeting the release-0.5 branch)

**Comment by tkelman** [comment]
I'll want to run pkgeval, make sure it doesn't break anything. And figure out what's wrong on osx travis...

**Comment by tkelman** [comment]
I'll run pkgeval in a separate PR and ping you if it turns out this causes any issues.

**Comment by iamed2** [comment]
This broke Atom.jl (and thus Juno):
https://github.com/JuliaLang/julia/issues/19272
http://discuss.junolab.org/t/error-loading-atom-package/1027/2

**Pull request merged**
