### PR TITLE
[doc] Add `@id` for doc title - Part 1

### PR DESCRIPTION
**Pull request by inkydragon**
xref: #23951 

This pr only add internal links.

"Internal links" mean that the `@id` and all `@ref` are in the same md file.
So you can review the changes in each file individually.

----

Useful tools: https://github.dev/inkydragon/julia/tree/doc-title-id
Open and search.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
Just wanted to confirm that this is still an issue though, since #23951 is >4 years old, so I wasn't sure if the translations had addressed this issue in some other way.

**Comment by ViralBShah** [comment]
linux32 got an out of memory error. Should be ok to merge.

**Comment by ViralBShah** [comment]
I did merge #43017 but I didn't see @vtjnash 's comment above. I'll leave this open for someone else to look at and merge or revert the other one if necessary.

**Comment by fredrikekre** [comment]
Can I suggest that you use the same names that Documenter would autogenerate? Otherwise external links will fail after a change like this I believe?

**Comment by vtjnash** [comment]
seems to be having issues:
```
┌ Warning: 'Shared-Arrays' is not unique in src\manual\distributed-computing.md.
└ @ Documenter.CrossReferences C:\buildbot\worker\package_win32\build\doc\deps\packages\Documenter\f5jts\src\CrossReferences.jl:100
┌ Warning: 'Shared-Arrays' is not unique in src\manual\distributed-computing.md.
└ @ Documenter.CrossReferences C:\buildbot\worker\package_win32\build\doc\deps\packages\Documenter\f5jts\src\CrossReferences.jl:100
┌ Warning: 'Glossary' is not unique in src\devdocs\backtraces.md.
└ @ Documenter.CrossReferences C:\buildbot\worker\package_win32\build\doc\deps\packages\Documenter\f5jts\src\CrossReferences.jl:100
```

**Comment by ViralBShah** [comment]
@inkydragon What do we need to do to get this merged (beyond resolving conflicts)?

**Comment by inkydragon** [comment]
@ViralBShah  I took a moment to think back to what this pr was going to do.

Now, my opinion is: close this pr.
Because in order to make sure not to break the existing links.
The `@id` of the new markup should be the same as the one generated by `Documenter.jl`. 
So, there is no need to add a new markup.

**Pull request closed without merging**
