### PR TITLE
Use dmgbuild for building OS X .dmg

### PR DESCRIPTION
**Pull request by simonbyrne**
This should simplify the OS X packaging, and adds a nice background. See discussion in #14470.

cc: @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
test build going at https://build.julialang.org/builders/package_osx10.9-x64/builds/426

**Comment by simonbyrne** [comment]
Seems to work, woohoo!

**Comment by tkelman** [comment]
give it a whirl? https://julianightlies.s3.amazonaws.com/bin/osx/x64/0.5/julia-0.5.0-b83b013ced-osx.dmg

**Comment by simonbyrne** [comment]
I already did! (though it did take me a while to figure out the path: are there links anywhere on build.julialang.org?)

**Comment by ViralBShah** [comment]
I was able to download, drag to desktop, and run a couple of commands.

**Comment by tkelman** [comment]
> are there links anywhere on build.julialang.org?

Not really, but the builds all get uploaded to pretty predictable paths derived from os, arch, Julia version and git sha. I usually check for things on the https://julianightlies.s3.amazonaws.com index (though sometimes that's truncated).

**Comment by tkelman** [comment]
So was the original report of https://github.com/JuliaLang/julia/issues/9010#issue-48833008 doing something strange when loading the file?

And does this change any paths within the dmg or would the existing Travis OSX setup continue to handle it as-is?

**Comment by simonbyrne** [comment]
Re #9010: Yes, they seem to have been loading the dmg in some nonstandard manner. I looked at some other dmg files from open source projects, and few of them used root ownership.

I don't think this should affect travis in any way.

**Comment by tkelman** [comment]
Cool. I'm satisfied enough to try this out then. The file size looks a little larger, is it a different compression level or something?

**Comment by simonbyrne** [comment]
Yeah, it's the compression level. Unfortunately they don't seem to provide an option to change it.

We might be able to do something better here, let me play around with it tomorrow.

**Comment by simonbyrne** [comment]
No luck I'm afraid, though I did open an issue with `dmgbuild`:
https://bitbucket.org/al45tair/dmgbuild/issues/8/zlib-compression-level

Also, while doing this I hit this issue in `platypus` while building the .app
https://github.com/sveinbjornt/Platypus/issues/67
The problem is readily identifiable as the resulting .dmg is only about 400k. The easiest workaround is to stick with v5.0 until it is fixed.

**Comment by tkelman** [comment]
So should we try this then? How/where are we installing platypus, are we in danger of things suddently breaking if an upgrade or reinstall happens?

**Comment by simonbyrne** [comment]
The platypus issue is (or should be) unrelated: we use whatever is installed on the build machine, so as long as no one updates it...

I'm happy with this: the only downside is the 10% increase in file size due to inability to express zlib compression size.

**Comment by ViralBShah** [comment]
I'm ok with binaries that are 10% larger for now.

**Comment by tkelman** [comment]
hopefully the zlib compression level thing will get implemented in dmgbuild some day

> as long as no one updates it

that part doesn't sound very future-proof though...

**Comment by simonbyrne** [comment]
Given that we no longer use python for building the docs, I'm guessing this isn't going to happen unless someone ports dmgbuild to Julia.

**Comment by vtjnash** [comment]
Python is always available on Mac. This would give us a nicer dmg file, right? I think it still just needs someone to push it to completion to merge it

**Pull request closed without merging**
