### PR TITLE
🤖 [master] Bump the ArgTools stdlib from 997089b to 5d56027

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: ArgTools
URL: https://github.com/JuliaIO/ArgTools.jl.git
Stdlib branch: master
Julia branch: master
Old commit: 997089b
New commit: 5d56027
Julia version: 1.12.0-DEV
ArgTools version: 1.1.2(Does not match)
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaIO/ArgTools.jl/compare/997089b9cd56404b40ff766759662e16dc1aab4b...5d560277d6d5417907d56776e5d0d52d88eb8f6e

```
$ git log --oneline 997089b..5d56027
5d56027 build(deps): bump julia-actions/setup-julia from 1 to 2 (#38)
b6189c7 build(deps): bump codecov/codecov-action from 3 to 4 (#37)
```

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by fingolfin** [comment]
There are unmerged PRs in that stdlib's repository, perhaps someone with access rights there could look into merging them?

**Comment by DilumAluthge** [comment]
Let me take a look.

**Comment by DilumAluthge** [comment]
I have reviewed and merged all open PRs on ArgTools.jl.

**Comment by DilumAluthge** [comment]
Closing this PR in favor of https://github.com/JuliaLang/julia/pull/56839

**Pull request closed without merging**
