### PR TITLE
`ismatch(rm)` now takes RegexMatch or Void as args

### PR DESCRIPTION
**Pull request by iagobaapellaniz**
This way one can store the result into a variable before checking the matching. I don't know about any clear example to explain. But I think it is coherent to implement them this way.

### CODE REVIEW

**Comment by nalimilan** [comment]
I think you'll have to be more convincing than that to get support for this change. :-)

**Comment by i-apellaniz** [comment]
```julia
function readContact(io)
    str = readline()
    # match for email
    rm = match(r"^([A-Z0-9\.]*)@([A-Z0-9.-]\.[A-z]{2,})$", str)
    if ismatch(rm)
        return Dict(:user => rm[1], :hosting => rm[2])
    end
    # match for phone
    rm = mathc(r"(\+\d{2,2})(\d{9,12})", str)
    if ismatch(rm)
        return Dict( :countryprefix => rm[1], :phone => rm[2]
    end
end
```
Don't pay too much attention to the regex I included ;-P

**Comment by vtjnash** [comment]
Possibly we should call this just `isnull`? Inference currently can only handle optimizing based on the special functions (`isa`, `===`, `!==`), but that's not a fundamental limitation.

**Comment by i-apellaniz** [comment]
I found a workaround to this. One can use `rm == nothing` to check if there is not a match or `rm != nothing` for matching. 

I'm happy with both cases

**Comment by StefanKarpinski** [comment]
The main advantage of `ismatch(re, str)` is that it knows it doesn't need to allocate a match object. If you're going to allocate a match object, then using `ismatch` is unnecessary since you can just write `m == nothing`.

**Pull request closed without merging**
