### PR TITLE
Deprecate using reserved words as field names

### PR DESCRIPTION
**Pull request by bicycle1885**
This is a part of #26507, and deprecates using keywords as a field name (e.g. `foo.function`).

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by fredrikekre** [comment]
Why can't we allow this? What are we going to do with this syntax instead?

**Comment by JeffBezanson** [comment]
I suppose we could just say that `a.` parses like `a.:`, making all keywords work as properties.

**Comment by JeffBezanson** [comment]
The code for that is just a couple lines above this change, but to spoil the surprise, you call `(parse-atom s #f)` instead of `(parse-atom s)`.

**Review by JeffBezanson — CHANGES_REQUESTED** [review]
I think I now agree with @fredrikekre. If it's possible to parse, there's no real reason to require `.:` instead of `.`

**Comment by bicycle1885** [comment]
The reason is simply because I don't want to see people using reserved words as a field name. It confuses most syntax highlighters and auto-indent tools of editors. If you think it should not be used, why don't you prohibit it at all?

**Comment by JeffBezanson** [comment]
Now that we have `getproperty` I think it makes sense to allow it. It's very difficult to define a type with a reserved word as a field name, but much easier to use one with `getproperty`.

**Comment by bicycle1885** [comment]
That means the start of mess. People can easily (ab)use the feature now.

We can allow this feature after the release of 1.0, but the opposite is breaking.

**Comment by JeffBezanson** [comment]
I understand the possible issues with editor support, but that doesn't seem like a good factor to drive this decision. Is there any other harm this does?

**Comment by JeffBezanson** [comment]
Or maybe the real question is, why is it ok to allow `a.:function` but not `a.function`?

**Comment by bicycle1885** [comment]
Hmm, maybe it complicates static analysis? For example, Tokenize.jl cannot tokenize keyword fields correctly:
```
julia> collect(tokenize("foo.function"))
4-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,3          IDENTIFIER     "foo"
 1,4-1,4          OP             "."
 1,5-1,12         KEYWORD        "function"
 1,13-1,12        ENDMARKER      ""
```

I think `foo.:function` is okay because the keyword is always preceded by a colon, which does not confuse the vim plugin on my editor.

**Comment by bicycle1885** [comment]
Ah, Tokenize.jl does not support this kind of complicated cases at all:
```
julia> collect(tokenize(":if"))
3-element Array{Tokenize.Tokens.Token,1}:
 1,1-1,1          OP             ":"
 1,2-1,3          KEYWORD        "if"
 1,4-1,3          ENDMARKER      ""

```

**Comment by KristofferC** [comment]
Pleaae don't use Tokenize for any argument, it's original purpose was syntax highlighting and any bugs there are just bugs.

**Comment by yurivish** [comment]
Is it the case that parsing `x.` as `x.:` would allow one to say `Base.+` instead of `Base.:+` (but still not `Base.:==`, which needs to be spelled `Base.:(==)`)?

**Comment by bicycle1885** [comment]
Okay, so this is not practically important.

**Comment by KristofferC** [comment]
Just to be clear, I am in favour of this, I just don't wang Tokenize to be an argument for either side :) .

**Comment by JeffBezanson** [comment]
> Is it the case that parsing x. as x.: would allow one to say Base.+ instead of Base.:+

No, because `.+` is an operator itself.

**Comment by JeffBezanson** [comment]
See #26648

**Pull request closed without merging**
