### PR TITLE
RFC: Updated MethodError to show closest candidates, issue #33793

### PR DESCRIPTION
**Pull request by efwright**
Issue #33793 gives an example where closest candidates are not printed after a MethodError. The current MethodError closest candidates implementation only prints candidates that are either single argument, or have at least one argument matching in the function call.

This PR edits the closest candidates printing to first print single argument functions, then functions with a match, followed by anything else. The max closest candidates that will be printed is still 3.

This will fix situations like this:
```
function a(x::Float32, y::Float32)
    return 1
end

a(Float64(0.0), Float64(0.0))
```
so that a(::Float32, ::Float32) will be printed as a closest candidate.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
As @JeffBezanson said, this just needs a simple test added. Should be easy enough to copy an existing one and adjust it to check for this also.

**Comment by Keno** [comment]
Bump on the test request.

**Comment by fingolfin** [comment]
@efwright are you still interested in working on this?

The modified code has been changed quite a bit since then, so besides the requested test, this also needs a rebase / merge with master

**Comment by vtjnash** [comment]
We merged a more comprehensive version of this recently

**Pull request closed without merging**
