### PR TITLE
SuiteSparse files moved

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Those files actually have an MIT header. What's the situation now with GPL? I see "[mix of LGPL2+ and GPL2+", seems still true, and BinaryBuilder doesn't change things.

**Comment by PallHaraldsson** [comment]
Also probably module/file SPQR should be mentioned:

```
if Base.USE_GPL_LIBS
    include("umfpack.jl")
    include("cholmod.jl")
    include("spqr.jl")
end
```

**Comment by ViralBShah** [comment]
We have licensed our driver code as MIT. That's fine.

**Comment by ViralBShah** [comment]
Actually these lines should probably just be deleted. They do not have their own licenses.

**Pull request merged**
