### PR TITLE
Doc author, committer, message

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Review by StefanKarpinski — APPROVED** [review]

**Comment by vtjnash** [comment]
This failed CI. Please check the status before merging.

**Comment by ararslan** [comment]
Yes you're right. Sorry about that.

**Comment by KristofferC** [comment]
If CI never passes, CI always passes.

**Comment by ararslan** [comment]
True. I had assumed the failures were unrelated, since Travis and AppVeyor always fail these days, but I have no excuse for not checking closer. Again, very sorry about that.

**Comment by JeffBezanson** [comment]
Usually you can get at least one platform to pass on AppVeyor.

**Pull request merged**
