### PR TITLE
Extensions: make loading of extensions independent of what packages are in the sysimage

### LINKED ISSUE #52132: Strange "missing from cache"/"does not support precompilation"/... errors
Reproducing in a clean env & depot, latest Julia (1.9.3; *upd* same on 1.9.4 and 1.10):
```julia
pkg> add AccessorsExtra
julia> using AccessorsExtra

┌ LinearAlgebraExt [2e571e4a-e68d-5fe4-9022-ff2e7d6ac6d5]
│  ┌ Warning: Module LinearAlgebraExt with build ID ffffffff-ffff-ffff-0001-6be4cd7b7f3f is missing from the cache.
│  │ This may mean LinearAlgebraExt [2e571e4a-e68d-5fe4-9022-ff2e7d6ac6d5] does not support precompilation but is imported by a module that does.
│  └ @ Base loading.jl:1793
│  ┌ Error: Error during loading of extension LinearAlgebraExt of AccessorsExtra, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
│  │    Declaring __precompile__(false) is not allowed in files that are being precompiled.
│  │    Stacktrace: <...>
└  
┌ TestExt [69cf5fdc-2bf6-5cf1-837e-a22f5027a90f]
│  ┌ Warning: Module TestExt with build ID ffffffff-ffff-ffff-0001-6be4cd7ce9e0 is missing from the cache.
│  │ This may mean TestExt [69cf5fdc-2bf6-5cf1-837e-a22f5027a90f] does not support precompilation but is imported by a module that does.
│  └ @ Base loading.jl:1793
│  ┌ Error: Error during loading of extension TestExt of AccessorsExtra, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
│  │    Declaring __precompile__(false) is not allowed in files that are being precompiled.
│  │    Stacktrace: <...>
└  
[ Info: Precompiling LinearAlgebraExt [2e571e4a-e68d-5fe4-9022-ff2e7d6ac6d5]
┌ Warning: Module LinearAlgebraExt with build ID ffffffff-ffff-ffff-0001-6be52894ee31 is missing from the cache.
│ This may mean LinearAlgebraExt [2e571e4a-e68d-5fe4-9022-ff2e7d6ac6d5] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1793
┌ Error: Error during loading of extension LinearAlgebraExt of AccessorsExtra, use `Base.retry_load_extensions()` to retry.
│   exception =
│    1-element ExceptionStack:
│    Declaring __precompile__(false) is not allowed in files that are being precompiled.
│    Stacktrace: <...>
```
Still, it seems like code from these two extensions is actually loaded and works.
I don't have `__precompile__(false)` anywhere in that package, all modules should support precompilation. What these errors and warnings actually mean, and are they bugs in Julia or in package code?

### PR DESCRIPTION
**Pull request by KristofferC**
When triggers of extension are in the sysimage it is easy to end up with cycles in package loading. Say we have a package A with exts BExt and CExt and say that B and C is in the sysimage.

- Upon loading A, we will immidiately start to precompile BExt (because the trigger B is "loaded" by virtue of being in the sysimage).
- BExt will load A which will cause CExt to start precompiling (again because C is in the sysimage).
- CExt will load A which will now cause BExt to start loading and we get a cycle.

This is fixed in this PR by instead of looking at what modules are loaded, we look at what modules are actually `require`d and only use that to drive the loading of extensions.

Fixes https://github.com/JuliaLang/julia/issues/52132.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52841#issuecomment-1886696193) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/be8fe90_vs_bf13a56/report.html) is available.

**Comment by KristofferC** [comment]
Okay, this PR, as is, is incomplete because it also has to count the dependencies that are loaded. Right now it only considers the package that is explicitly loaded by the user.

**Comment by vtjnash** [comment]
Oh yeah, this is a very good observation. I think a better solution might be a bit different though--we should make sure instead that all of these extensions are included in the original precompile of the package that resolved them all (rather than trying to split them into separate files). The precompile code should already be perfectly happy for them to live inside the `.ji` file of the parent, we just need to teach loading.jl to put them there.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["TranscodingStreams", "EulerAngles", "CodecBase", "GeneralizedSylvesterSolver", "BufferedStreams", "CodecBzip2", "CodecLz4", "CodecZlib", "CodecXz", "CodecZstd", "Sinograms", "Pseudospectra", "ImplicitDifferentiation", "StatsDiscretizations", "StipplePlotly", "MRIOperators", "CategoryData", "GR", "MRISimulation"])`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["TranscodingStreams", "EulerAngles", "CodecBase", "GeneralizedSylvesterSolver", "BufferedStreams", "CodecBzip2", "CodecLz4", "CodecZlib", "CodecXz", "CodecZstd", "Sinograms", "Pseudospectra", "ImplicitDifferentiation", "StatsDiscretizations", "StipplePlotly", "MRIOperators", "CategoryData", "GR", "MRISimulation"])`

**Comment by vtjnash** [comment]
it belongs in `A`, since `B` and `C` are already loaded (in the case where `B` and `C` are already loaded when `A` finishes precompiling)

**Comment by KristofferC** [comment]
And if they aren't and you just load A by itself (and then B and C)?

**Comment by vtjnash** [comment]
Then no change is needed, since there is no circularity problem?

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/52841#issuecomment-1888915228) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
This broke Nanosoldier: It hung during build (PkgEval should use a timeout) at the `generate_precompile.jl` stage:

```
Collecting and executing precompile statements
...
InitError(mod=:Base, error=UndefVarError(var=:required_modules, scope=Base))
ijl_undefined_var_error at /source/src/rtutils.c:152
ijl_get_binding_or_error at /source/src/module.c:464
__init__ at ./Base.jl:630
unknown function (ip: 0x7f6323b56cbf)
_jl_invoke at /source/src/gf.c:2921 [inlined]
ijl_apply_generic at /source/src/gf.c:3098
jl_apply at /source/src/julia.h:2153 [inlined]
jl_module_run_initializer at /source/src/toplevel.c:76
_finish_julia_init at /source/src/init.c:902
julia_init at /source/src/init.c:843
jl_repl_entrypoint at /source/src/jlapi.c:1087
main at /source/cli/loader_exe.c:58
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
```

**Comment by KristofferC** [comment]
Yeah, I was a bit eager to submit that job...

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52841#issuecomment-1888931172) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6be9189_vs_bf13a56/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["CodecZstd", "TranscodingStreams", "CodecBase", "CodecLz4", "CodecBzip2", "CodecZlib", "CodecXz"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52841#issuecomment-1891608578) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/36213eb_vs_bf13a56/report.html) is available.

**Comment by KristofferC** [comment]
I realize now that the failing packages are actually failing due to the bugfix here. They never explicitly load `Random` in their tests but they have an extension that requires both Random and Test to trigger. Their extension used to load due to Random being in the sysimage which isn't enough anymore.

**Comment by vtjnash** [comment]
I don't think this is the right approach, but we should teach it to serialize the whole cycle inside the package A to solve this

**Comment by KristofferC** [comment]
I think this is fine as a small fix aimed to be backported. It isn't more arbitrary than what is already in there. A bigger rewrite can be done by someone inclined and get put into 1.11.

**Pull request merged**
