### PR TITLE
Fix #11673, bad indent after comments ending in =

### LINKED ISSUE #11673: julia-mode: `=` at the end of comment causes increase in indent level...
See screenshot.

minicircuits_2015-4-24

### PR DESCRIPTION
**Pull request by dfannius**

### CODE REVIEW

**Comment by yuyichao** [comment]
LGTM and confirmed it fixes the problem here. Thanks!

I would like to merge this soon unless someone don't like it.

**Comment by pao** [comment]
cc @Wilfred, but I'll go ahead and merge it based on @yuyichao's report.

**Comment by yuyichao** [comment]
@pao You beat me by a few minutes.

**Comment by pao** [comment]
@yuyichao I didn't notice that you'd gotten Collaborator until just now, congrats! You deserve it!

**Comment by Wilfred** [comment]
LGTM, but it would be nice to add this case to the indentation tests.

**Comment by yuyichao** [comment]
@Wilfred Actually I didn't know julia-mode has it's own test...

BTW, I discovered this issue by doing a indent-region on `inference.jl`. You can pretty much see all of the `julia-mode` issues that way.....

**Pull request merged**
