### PR TITLE
Update Mozilla CA certificate store to latest (01-23-2019) for libgit2 SSL.

### PR DESCRIPTION
**Pull request by mikhail-j**
@staticfloat

The [curl project](https://curl.haxx.se/docs/caextract.html) has updated the Mozilla CA certificate store last month (01/23/2019).

This update coincides with CA certificate list changes to [Mozilla NSS 3.41](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.41_release_notes).

7 CA certificates were added:

* Certigna Root CA
* GTS Root R1
* GTS Root R2
* GTS Root R3
* GTS Root R4
* UCA Global G2 Root
* UCA Extended Validation Root

The following CA certificates that were previously trust bit disabled in [Mozilla NSS 3.39](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.39_release_notes) (`cacert-2018-10-17.pem` had them removed #30079) are officially removed in [Mozilla NSS 3.41](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.41_release_notes):

* Certplus Root CA G1
* Certplus Root CA G2
* OpenTrust Root CA G1
* OpenTrust Root CA G2
* OpenTrust Root CA G3

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Thank you for taking care of these updates! Should be backported to 1.0 and 1.1 branches.

**Comment by mikhail-j** [comment]
@StefanKarpinski Glad to be of help.

**Comment by StefanKarpinski** [comment]
@staticfloat: are these safe for backporting? I assume that they should be backported for security.

**Comment by staticfloat** [comment]
Yes, these should be safe for backporting.

**Pull request merged**
