### PR TITLE
SSAIR: improve inlining performance with in-place IR-inflation

### PR DESCRIPTION
**Pull request by aviatesk**
This commit improves the performance of a huge hot-spot within `inflate_ir`
by using the in-place version of it (`inflate_ir!`) and avoiding some
unnecessary allocations.
For `NativeInterpreter`, `CodeInfo`-IR passed to `inflate_ir` can come
from two ways:
1. from global cache: uncompressed from compressed format
2. from local cache: inferred `CodeInfo` as-is managed by `InferenceResult`

And in the case of 1, an uncompressed `CodeInfo` is an newly-allocated
object already and thus we can use the in-place version safely. And it
turns out that this helps us avoid many unnecessary allocations.
The original non-destructive `inflate_ir` remains there for testing or
interactive purpose.

---

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45404) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0709378_vs_9b106ad/report.md).

**Comment by Keno** [comment]
This seems reasonable to me. I usually profile with Cthulhu when I profile inference, which doesn't go through the compression/decompression cycle, so I don't have a good idea of the usual performance impact, but the nanosolider results look favorable, so I'm in favor. My only concern would be ending up with corrupted CodeInfos in some of the generated function cases. I've run into hard to debug bugs of that kind before, but certainly for the compression case, it's a no brainer to do the inflation destructively. Eventually we may want to even skip the decompression step and just inline directly from the compressed representation as we go along, but that's obviously future work.

**Comment by aviatesk** [comment]
> My only concern would be ending up with corrupted CodeInfos in some of the generated function cases.

For the uncompressed case, this PR makes a copy of that `CodeInfo` and so I think it is also safe. Maybe `CodeInstance.inferred` manages `CodeInfo` directly for generated function case? It'd be handled in the same way anyway though.
https://github.com/JuliaLang/julia/blob/f34c57713051f71e6690ad2cfcf6c88d0ac884b8/base/compiler/ssair/inlining.jl#L920

---

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45404#issuecomment-1133548755) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f34c577_vs_9b106ad/report.html).

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["AStarSearch", "ArchGDAL", "AugmentedGPLikelihoods", "AutocorrelationShell", "BigO", "BioStructures", "ClimateModels", "CollectiveSpins", "ConceptnetNumberbatch", "CovarianceMatrices", "CrypticCrosswords", "CryptoGroups", "DarkCurves", "ExactOptimalTransport", "FSimZoo", "Faker", "Ferrite", "GrayCoding", "Individual", "InfrastructureSystems", "Ipaper", "JSONSchema", "Karnak", "MDInclude", "MixedModelsPermutations", "NonconvexIpopt", "OhMyREPL", "PoissonRandom", "PolynomialBases", "PowerSimulations", "QuantumAlgebra", "SimpleGraphs", "SimpleTweaks", "SkipLists", "StringDistances", "Surrogates", "ToeplitzMatrices", "VertexFinder", "VoxelRayTracers", "BasicInterpolators", "BayesianQuadrature", "BitSAD", "BundlerIO", "CiteEXchange", "Evolutionary", "GraphMLDatasets", "JuliaCon", "Probably", "QuantumTomography", "ReadVTK", "Retriever", "SBML", "StochasticDelayDiffEq", "ImageTracking", "Tapestree"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45404#issuecomment-1133767710) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/e32beae_vs_3d6731b/report.html).

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["JSONSchema", "ToeplitzMatrices", "Tapestree"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45404#issuecomment-1134088089) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/0bd5a18_vs_5554676/report.html).

**Comment by aviatesk** [comment]
Just confirmed the JSONSchema test suite runs successfully on my local machine on this branch. Going to merge.

**Pull request merged**
