### PR TITLE
Support isdefined for SimpleVector (fixes #11167)

### LINKED ISSUE #11167: SimpleVector lacks appropriate `isdefined` call
```jl
julia> type MyType{T,N} end

julia> MyType{Int,2}
MyType{Int64,2}

julia> isdefined(MyType.name.cache, 0)
false

julia> isdefined(MyType.name.cache, 1)
true

julia> isdefined(MyType.name.cache, 2)
false

julia> MyType{Float32, 5}
MyType{Float32,5}

julia> isdefined(MyType.name.cache, 2)
false

julia> MyType.name.cache
svec(MyType{Float32,5},MyType{Int64,2},Error showing value of type SimpleVector:
ERROR: UndefRefError: access to undefined reference
 in show_delim_array at show.jl:189
 in show at show.jl:213
 in anonymous at show.jl:1232
 in with_output_limit at ./show.jl:1209
 in showlimited at show.jl:1231
 in writemime at replutil.jl:4
 in display at REPL.jl:113
 in display at REPL.jl:116
 in display at multimedia.jl:151
 in print_response at REPL.jl:133
 in print_response at REPL.jl:120
 in anonymous at REPL.jl:599
 in run_interface at ./LineEdit.jl:1554
 in run_frontend at ./REPL.jl:843
 in run_repl at ./REPL.jl:166
 in _start at ./client.jl:451
```

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, I realized there's a conflict here: for `DataType`s, `isdefined(a, 2)` asks about the 2nd field; for arrays, `isdefined(a, 2)` asks about the 2nd element. There's no conflict between these, because `Array` doesn't have any fields.

However, `SimpleVector` has one field, `length`. So does `isdefined(sv, 1)` ask about the first field or the first element?

**Comment by mbauman** [comment]
Perhaps we should export and document `isassigned` for arrays? Then we could de-tangle the two.

**Comment by JeffBezanson** [comment]
+1
It might also be good to get rid of the `isdefined` case for arrays as part of making them gradually less built-in, but that's lower priority.

**Comment by timholy** [comment]
Argh, git error here.

**Pull request closed without merging**
