### PR TITLE
count(regex, string) computes length(findall(regex, string)) better

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Sometimes you just want to count how many times something occurs. I basically just copied the `findall` method above and counted instead of pushing. It could be refactored to share logic, but that seemed like overkill.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I basically just copied the `findall` method above and counted instead of pushing. It could be refactored to share logic, but that seemed like overkill.

**Comment by StefanKarpinski** [comment]
FreeBSD failure is unrelated.

**Comment by StefanKarpinski** [comment]
Win64 failure also unrelated (frippery.org can't be reached).

**Comment by StefanKarpinski** [comment]
I guess an API concern about this is that `count(p, itr)` counts items in `itr` that match `p` whereas this method counts subsequences of `itr` which match a regex. Does that matter?

**Comment by JeffBezanson** [comment]
Well, we also have methods of `findall` where the first argument is either a Function or a Regex, so that ship has sailed.

**Comment by StefanKarpinski** [comment]
Ok, in that case, there's no real reason not to do this.

**Comment by rfourquet** [comment]
Sorry, didn't have time to review before merge! (On holidays 😎, but will have a look later)

**Comment by tkf** [comment]
> seemed like overkill.

Alas, if Base had transducers...

```julia
using Transducers
using Transducers: @next, complete

matches(t, s, overlap=false) = AdHocFoldable() do rf, acc, _
    i, e = firstindex(s), lastindex(s)
    while true
        r = findnext(t, s, i)
        isnothing(r) && return complete(rf, acc)
        acc = @next(rf, acc, r)
        j = overlap || isempty(r) ? first(r) : last(r)
        j > e && return complete(rf, acc)
        @inbounds i = nextind(s, j)
    end
end

count′(args...) = foldl(right, Count(), matches(args...); init=0)
findall′(args...) = foldl(push!, Map(identity), matches(args...); init=UnitRange{Int}[])
find3(args...) = foldl(push!, Take(3), matches(args...); init=UnitRange{Int}[])
```

(sorry, cannot help it)

**Pull request merged**
