### PR TITLE
Adds optional message to @test

### PR DESCRIPTION
**Pull request by morris25**
Perhaps an optional message in test would be useful for debugging?
FactCheck.jl has it so why not include it with tests?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I think it would be better if we improved test failure reporting to include:

- stack trace with values (should be possible with recent Gallium work)
- source context of the failure

These are both generally useful and would allow comments on the test to serve as messages.

**Comment by IainNZ** [comment]
> stack trace with values

That sounds neat, you mean the values passed into each function in the backtrace?

On this PR: It doesn't add much complexity, so 👍 , although I've never really understood the use for this - I know where the error occurred from the backtrace, and I also have the values if it was a comparison-style test, so what would I put in the message? I was hoping that test set names provided enough instant-context for this too, especially as you can splat the variables that you are testset-looping over into the testset name.

**Comment by StefanKarpinski** [comment]
I don't want to add an optional message argument even if it doesn't add much complexity since if/when we decide we didn't need it after all, we have to start a deprecation cycle.

**Comment by morris25** [comment]
On second thought this is probably not the best idea. I suppose I should just get rid of this.

**Pull request closed without merging**
