### PR TITLE
Add missing datatype_module method for UnionAll types

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
I don't think I've seen this failure before
```julia
	From worker 1:		From worker 1:	Worker 6 failed running test ranges:
Some tests did not pass: 12107327 passed, 1 failed, 0 errored, 327680 broken.ranges: Test Failed
  Expression: cmp_sn2(Tw(xw / yw), astuple(x / y)..., slopbits)
Stacktrace:
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:651
 [2] (::getfield(Main, Symbol("##40#44")))() at /usr/home/julia/worker/11rel-amd64/build/test/runtests.jl:160
 [3] cd(::getfield(Main, Symbol("##40#44")), ::String) at ./file.jl:70
 [4] include_relative(::Module, ::String) at ./loading.jl:464
 [5] include(::Module, ::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:315
 [7] _start() at ./client.jl:383
```
Anybody have any concerns w/ this?

**Comment by StefanKarpinski** [comment]
I'm not sure what problem this is addressing or who should review it.

**Comment by quinnj** [comment]
It's just a missing method for `UnionAll` types, e.g., `datatype_name` works on both `DataType` and `UnionAll`, but `datatype_module` currently only works on `DataType`. Hence the PR.

**Comment by Keno** [comment]
That test failure is https://github.com/JuliaLang/julia/issues/23497 AFAIK. As for the actual change, LGTM.

**Review by Keno — APPROVED** [review]

**Pull request merged**
