### PR TITLE
Support @inbounds in setindex!(::Array, ::AbstractArray, ::AbstractVector}

### PR DESCRIPTION
**Pull request by nalimilan**
Previously this annotation wouldn't have any effect on Array, contrary to
what happens with the general AbstractArray fallback method.
Also always use @inbounds for X[count] since count depends on the length of I,
(which is checked), and mark setindex_shape_check() as a bounds check.

Fixes https://github.com/JuliaLang/julia/issues/20907.

### CODE REVIEW

**Comment by nalimilan** [comment]
Failures are https://github.com/JuliaLang/julia/pull/20906. We should probably run Nanosoldier if it passes the review, though.

**Comment by ararslan** [comment]
I've restarted CI now that #20906 has been merged.

**Comment by blakejohnson** [comment]
LGTM

**Comment by mbauman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by mbauman** [comment]
With regards to using `@boundscheck` blocks for `setindex_shape_check`, I think that's fine.  We could eventually do the same for the general AbstractArray methods.  I didn't worry too much about it since it's typically much cheaper than the real work.

**Review by mbauman — APPROVED** [review]

**Review by Sacha0 — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20910#issuecomment-284533188) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/11051b67f39e23f56746e66c4a3b14bb760b58f1/44e40cd_vs_666eee6/report.md). cc @jrevels

**Comment by blakejohnson** [comment]
That array comprehension slowdown is troubling. Can you reproduce that locally, @nalimilan?

**Comment by KristofferC** [comment]
It is a very noisy benchmark that warns every second time the benchmarks are run which is why I merged anyway. I can double check to make sure.

**Comment by simonster** [comment]
`@_propagate_inbounds_meta` includes `@inline`. I'm not sure it's a good idea to inline a function as big as `setindex!(A::Array, X::AbstractArray, I::AbstractVector{Int})`.

**Comment by blakejohnson** [comment]
Unfortunately, our `@inbounds` mechanism requires inlining in order to have any effect.

**Comment by simonster** [comment]
I am aware. It just seems weird to be inlining a 13 line function to make it possible to elide bounds checks. That can have serious consequences in terms of compilation time even for people not using `@inbounds`.

In this case, maybe we could do something like:

```julia
function setindex!(A::Array, X::AbstractArray, I::AbstractVector{Int})
    @_inline_meta
    @boundscheck return checked_setindex!(A, X, I)
    unchecked_setindex!(A, X, I)
end
```

The method splitting could be done automatically with a macro, although that may not be so easy this early in bootstrap.

**Comment by blakejohnson** [comment]
If we can make that work, I agree that it would be better.

**Comment by nalimilan** [comment]
Makes sense. Though that would be `unsafe_setindex!`.

**Pull request merged**
