### PR TITLE
`Base.runtests`: set a temporary Pkg depot path

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by KristofferC** [comment]
Would be good to say something in the commit message why this is needed now. Something with Buildkite?

**Comment by DilumAluthge** [comment]
Buildbot, actually. This fixes one source of intermittent Buildbot failures.

More context on Slack: https://julialang.slack.com/archives/C01F9PX2UMU/p1632263882053700

> Ahhh, I know why this is happening.  The “fake” JLLs don’t get compiled into the system image, because we don’t want to run their __init__() until they’re imported.
>
> This means that when we try to load the module, we compile, and we save out the .ji file.  And when we’re running Base.runtests() we don’t have a default depot set, I bet.

**Review by vtjnash — APPROVED** [review]
I think we also need to set `JULIA_PROJECT`?

**Review by vtjnash — COMMENTED** [review]
Does buildbot / buildkite use this code? I thought they generally launched the runtests.jl file directly (and avoided the `ncores /= 2`here).

**Comment by DilumAluthge** [comment]
I'm not sure about Buildbot - @staticfloat will know.

Buildkite calls `Base.runtests`. However, we explicitly set the `ncores` keyword argument.

**Comment by staticfloat** [comment]
Yes, buildbot uses `Base.runtests()` as well: https://github.com/JuliaCI/julia-buildbot/blob/63603639f20d848cf2173b47aee31ec8f9a427b2/master/separated_testing.py#L16

**Comment by sostock** [comment]
> > I think we also need to set `JULIA_PROJECT`?
> 
> Hmmm, I don't think we need to. If `JULIA_DEPOT_PATH` is provided, and no project is provided, then Julia should just use the default global project in our temp depot.

Does it? At least for me, this PR breaks the `revise` option of `Base.runtests`:
```julia
julia> Base.runtests("ranges", revise=true)
ERROR: LoadError: ArgumentError: Package Revise not found in current path.
- Run `import Pkg; Pkg.add("Revise")` to install the Revise package.
Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:989
 [2] top-level scope
   @ ~/Development/julia/usr/share/julia/test/runtests.jl:26
in expression starting at /home/sebastian/Development/julia/usr/share/julia/test/runtests.jl:25
```

**Pull request merged**
