### PR TITLE
Export test status to buildkite

### PR DESCRIPTION
**Pull request by vchuravy**
Very rough draft of exporting our test-results to buildkite using https://buildkite.com/docs/test-analytics/importing-json

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@vchuravy To spare you rolling your own JSON writer, I would be quite happy with either of the following:

1. In the https://github.com/JuliaCI/julia-buildkite repository, we vendor a copy of the `JSON3.jl` package, and use that to write JSON files.
2. In the https://github.com/JuliaCI/julia-buildkite repository, we check in a `Manifest.toml` file that has `JSON3.jl` as a dependency, and we instantiate that environment and then use JSON3 to write JSON files.

@staticfloat What do you think?

**Comment by DilumAluthge** [comment]
There's a third option - we already include the [`jq`](https://github.com/stedolan/jq) binary in our Linux rootfs images, and I'm sure we could add it to our Windows and macOS build environments. So you could use `jq` to create your JSON documents and write them to JSON files.

Although I'd probably prefer that we use a Julia package, because that might lower the barrier to entry for other members of the Julia community to contribute to this code (since it will all be written in Julia).

**Comment by staticfloat** [comment]
The JSON writing so far is not onerous; I say we just emit the restricted subset of JSON that we need manually and don't worry about all the complexity of including a full JSON dumper.  This is really cool Valentin!

**Review by DilumAluthge — COMMENTED** [review]
I wonder how much of this code actually needs to live in `JuliaLang/julia`, and how much can live in `JuliaCI/julia-buildkite` instead?

For example, would it be sufficient for this code (the code in `JuliaLang/julia`) to just have it `Serialization.serialize` the `o_ts` to a file?

And then in the next step of the CI workflow, we could `Serialization.deserialize` the `o_ts` back in, and then do all the JSON stuff? And all that code (starting with the deserialize) would live in `JuliaCI/julia-buildkite`?

**Comment by vchuravy** [comment]
The code I actually would want is https://github.com/JuliaTesting/TestReports.jl
I was contemplating writing out to TOML and then converting to JSON afterwards, but the code wasn't that bad.

In the longterm we might in particular import https://github.com/JuliaTesting/TestReports.jl/blob/master/src/testsets.jl into Test.jl so that we can get a better indication of things.

**Comment by vchuravy** [comment]
Replaced by #53145 53145

**Pull request closed without merging**
