### PR TITLE
deprecate syntax `1.+`. fixes #19089

### LINKED ISSUE #19089: syntax confusion: `1.+2`
This sort of confusion keeps cropping up: https://groups.google.com/forum/#!topic/julia-users/aycsd2iAktE. Two possibilities seem possible:
- Eliminate `1.` as a short syntax for `1.0`;
- Allow `1.` but make ambiguous cases like `1.+2` a syntax error.

Related: https://github.com/JuliaLang/julia/issues/18714 – in that it also relates to making potentially ambiguous cases errors.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
lgtm (modulo the parser changes which I did not pore over)! :)

**Comment by Sacha0** [comment]
Might be worth mentioning the need for disambiguation in the documentation somewhere?

**Comment by JeffBezanson** [comment]
Added a bit on this to the manual.

**Review by Sacha0 — APPROVED** [review]
lgtm for the manual addition! :)

**Comment by jebej** [comment]
Was there any argument for why keeping the `1.` syntax is preferable? The only two I see in #19089 was that other languages accept it, and that it would be annoying to have people replace all the dots with `.0`.

I find that putting spaces for operations like division, multiplication and exponentiation to be fairly jarring as it makes their higher precedence less obvious.

**Comment by JeffBezanson** [comment]
I see numeric literal syntax as much more established than dot operator syntax. Even if `1.` were disallowed in julia, it would be easy to read `1.+x` as `(1.)+x` due to the prevalence of `1.` as numeric literal syntax. In any case, deprecating `1.+x` is the safest thing, since that at least allows us to change its meaning in the future.

**Pull request merged**
