### PR TITLE
Fix #36550 with the same solution for Regex

### LINKED ISSUE #36550: SubstitutionString with non-trailing backslashes is displayed incorrectly
```
julia> s"\x"
s"\\x"

julia> s"\\x"
s"\\\\x"

julia> s"\\\x"
s"\\\\\\x"

julia> versioninfo()
Julia Version 1.6.0-DEV.370
Commit dec679e352 (2020-07-05 05:37 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by melonedo**
This is the same solution for Regex (r"...") if the flags are simple.

### CODE REVIEW

**Comment by musm** [comment]
LGTM can you add tests?

**Comment by melonedo** [comment]
> 
> 
> LGTM can you add tests?

I am searching for a place to place them. BTW, this commit certainly breaks doctests of `SubstitutionString`.

**Comment by melonedo** [comment]
Test timeout... Test worker issue?

**Comment by musm** [comment]
Yeah, looks unrelated.

**Review by musm — APPROVED** [review]

**Pull request merged**
