### PR TITLE
SIMD regression tests

### PR DESCRIPTION
**Pull request by damiendr**
Implements the following:
- SIMD loop tests described in issue #13686 
- changes in the test runner to run code generation tests without `--check-bounds=yes`.

### CODE REVIEW

**Comment by simonster** [comment]
One possible problem here is that, if these tests are run on an architecture without SIMD instructions, or where LLVM thinks use of SIMD for some of these cases is possible but not profitable, they will fail. I'm not sure what the right solution is here.

**Comment by KristofferC** [comment]
Can someone remind me what the problem here was?

Basically every time there is a performance regression the generated code explodes in size. Being able to check generated code seems like it could catch many problems at C.I  time instead of "when someone notices it weeks down the road"-time. Issues like: https://github.com/JuliaLang/julia/issues/15274, https://github.com/JuliaLang/julia/issues/16185 should in my view have codegen tests.

**Comment by StefanKarpinski** [comment]
+1 to codegen tests. The simplest thing I can think of is having a test that the number of instructions emitted is less than some fixed threshold. If that fails, then we can investigate and either fix the issue or bump the limit if the generated code is still ok just unexpectedly verbose (e.g. some kind of unrolling).

**Comment by damiendr** [comment]
@KristofferC In that particular case the test was to check for a "vector" keyword in the LLVM IR returned by code_llvm. The problem was that the IR varied depending on the processor type, causing some of the tests to fail on some of the (older) CI machines.
At the time I did not investigate further because it seemed like all SIMD codegen tests would need a whitelist of CPU types and that seemed hard to write and maintain. But for other types of codegen tests it might be possible to find a suitable invariant feature to test for, I suppose!

**Comment by musm** [comment]
According to https://github.com/JuliaLang/julia/issues/13686#issuecomment-310858244 it sounds like the current test suite is sufficient.

**Pull request closed without merging**
