### PR TITLE
Add let blocks to timing macros.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Ref: https://github.com/JuliaLang/julia/pull/11801#issuecomment-114100225

@yuyichao only saw your comment about just removing `local` now, is there a particular advantage doing it that way rather? I'm happy to update this is there is.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I suspect we want the let blocks for this to avoid littering the global namespace with oddly named global variables.

**Comment by yuyichao** [comment]
For `@time a = 1`

**Comment by MichaelHatherly** [comment]
> For ``@time a = 1``

Yeah, I guess that rules out using ``let`` then. Is littering the global namespace by removing the ``local``s something that's actually avoidable then?

**Comment by yuyichao** [comment]
There are tricks to figure out whether you are in the global scope and call `eval` if true but I think it doesn't worth doing for this....

**Comment by JeffBezanson** [comment]
Maybe we should just roll back the error message for `local`. It's totally independent of the rest of that fix.

**Comment by phobon** [comment]
There should also be some tests for these macros added. It's pretty crazy this was able to be broken without getting caught by Travis.

**Comment by JeffBezanson** [comment]
Yes I started adding these locally before I saw this PR:

```
let t = @elapsed 1+1
    @test isa(t, Real) && t >= 0
end

let
    val, t = @timed sin(1)
    @test val == sin(1)
    @test isa(t, Real) && t >= 0
end
```

It's always good to have even trivial tests like these.

**Comment by JeffBezanson** [comment]
Er, of course we also need some that test it at global scope. Part of why this is tricky!

**Comment by MichaelHatherly** [comment]
Thanks for taking the time to discuss this everyone. Much appreciated.

**Pull request closed without merging**
