### PR TITLE
Avoid impossible unionall normalization

### PR DESCRIPTION
**Pull request by martinholters**
Cousin of #41976, fixing the second case of https://github.com/JuliaLang/julia/issues/41908#issuecomment-901837460.

### CODE REVIEW

**Comment by KristofferC** [comment]
bugfix? (and thus should be backported?)

**Comment by martinholters** [comment]
I'd say yes.

**Comment by vtjnash** [comment]
I am not sure it is to be expected that apply type is infailable. There seem like other reasons (earlier) that it could also fail?

**Comment by martinholters** [comment]
True, but that there are types `T` for which `Tuple{T}` fails seems a bit of a gotcha.

**Pull request merged**
