### PR TITLE
fix NullException in procs(::Int)

### LINKED ISSUE #11230: NullException with procs(::Int) when using --machinefile
When starting Julia with `--machinefile` the command `procs` gives `NullException`:
```julia
jaak@node-1-14:~$ julia --machinefile test.machinefile 
...
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4603 (2015-05-02 18:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 803193e* (8 days old master)
|__/                   |  x86_64-linux-gnu

julia> workers()
2-element Array{Int64,1}:
 2
 3

julia> procs(2)
ERROR: NullException()
 in == at nullable.jl:42
 in anonymous at multi.jl:261
 in filter at ./array.jl:1321
 in procs at multi.jl:261

julia> procs(3)
ERROR: NullException()
 in == at nullable.jl:42
 in anonymous at multi.jl:261
 in filter at ./array.jl:1321
 in procs at multi.jl:261

julia> procs(1)
1-element Array{Int64,1}:
 1
```
No problem with general parallel commands:
```julia
julia> fetch(@spawnat 3 sum(rand(10,10)))
46.096993964605204
```
In my setup julia is started on `node1` and the machine file is
```
node1
node2
```
The problem does not happen if julia is started with `julia -p 2`.

### PR DESCRIPTION
**Pull request by amitmurthy**
closes #11230

### CODE REVIEW

**Comment by amitmurthy** [comment]
Failed test is OOM related

**Comment by KristofferC** [comment]
Did you mean to merge?

**Comment by amitmurthy** [comment]
Yes. Why?

**Comment by KristofferC** [comment]
You closed it instead of merging? Or am I being stupid.

**Comment by amitmurthy** [comment]
Thanks. It was just me being stupid. :-)

**Comment by KristofferC** [comment]
:)

**Pull request merged**
