### PR TITLE
inference: normalize lattice naming

### PR DESCRIPTION
**Pull request by aviatesk**
@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47851#issuecomment-1345747201) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/88ed239_vs_b5a6b0f/report.md).

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47851#issuecomment-1345766108) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c03f7f7_vs_b5a6b0f/report.md).

**Pull request merged**
