### PR TITLE
Update BinaryBuilder libuv to 2.0.1+4

### PR DESCRIPTION
**Pull request by ararslan**
The FreeBSD binaries for this build are built with FreeBSD 12 rather than FreeBSD 11, which will work around #34627 now that support for FreeBSD 11 has been officially discontinued. Before closing that issue I'd like to verify whether binaries built for FreeBSD 12 will work on 13 so that I don't have a copy-paste a new issue with 11 and 12 incremented to 12 and 13. 😄

Note that the FreeBSD buildbot won't notice this change since we have it set to build with `USE_BINARYBUILDER_LIBUV=0` specifically to work around #34627. Once this is merged, it would be nice if we could figure out a way to conditionally set that flag.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Sounds good to me. Probably good to have Elliot sign off on this as well before merging.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
> Note that the FreeBSD buildbot won't notice this change since we have it set to build with `USE_BINARYBUILDER_LIBUV=0` specifically to work around #34627. Once this is merged, it would be nice if we could figure out a way to conditionally set that flag.

Not sure how to do this with Buildbot, but when we switch to Buildkite, we can condition the flag based on which branch is being built (master, release-1.6, release-1.7, etc.).

**Comment by ararslan** [comment]
The FreeBSD CI failure is
```
ERROR: The working directory is dirty.
Output of git status:
On branch refs/pull/41900/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	base/Artifacts.toml
	base/load_artifact.jl
```
which I've not observed locally.

**Comment by ararslan** [comment]
Also Julia now builds successfully on FreeBSD 13 without setting `USE_BINARYBUILDER_LIBUV=0`, so I think this PR effectively fixes #34627.

**Comment by ararslan** [comment]
Rebased to see whether that fixes anything, since I can't reproduce.

**Comment by ararslan** [comment]
The buildkite stuff is failing with
```
ERROR: "/cache/julia-buildkite-plugin/depots/53de1ea5-6dd3-4008-b976-161c9f34b0ad/registries/General/J/JLLWrappers/Package.toml": No such file
```

**Comment by ararslan** [comment]
I restarted the FreeBSD buildbots and the build passed successfully. I don't expect the tests to pass at the moment.

**Comment by ararslan** [comment]
Summary of CI failures, all of which appear unrelated to this PR:
- Windows x86 tests: Failure in `spawn`:
   ```
   LoadError: Failed to connect to cache.julialang.org port 443: Timed out while requesting https://cache.julialang.org/https://frippery.org/files/busybox/busybox.exe
   ```
- Windows x64 tests: Failure in `spawn`:
   ```
   LoadError: Failed to connect to cache.julialang.org port 443: Timed out while requesting https://cache.julialang.org/https://frippery.org/files/busybox/busybox.exe
   ```
- Linux x86 tests: Failure in `cmdlineargs`:
   ```
   Error During Test at /buildworker/worker/tester_linux32/build/share/julia/test/cmdlineargs.jl:202
  Test threw exception
  Expression: string(cpu_threads) == read(`$exename --threads auto -e $code`, String) == read(`$exename --threads=auto -e $code`, String) == read(`$exename -tauto -e $code`, String) == read(`$exename -t auto -e $code`, String)
  failed process: Process(`/buildworker/worker/tester_linux32/build/bin/julia -Cnative -J/buildworker/worker/tester_linux32/build/lib/julia/sys.so --depwarn=error --check-bounds=yes -g1 --startup-file=no --startup-file=no --color=no --threads auto -e 'print(Threads.nthreads())'`, ProcessExited(1)) [1]
  ```
- Linux PPC build: OOM while building the sysimage
   ```
   /bin/sh: line 1: 146626 Killed                  JULIA_BINDIR=/buildworker/worker/package_linuxppc64le/build/usr/bin WINEPATH="/buildworker/worker/package_linuxppc64le/build/usr/bin;$WINEPATH" /buildworker/worker/package_linuxppc64le/build/usr/bin/julia -O3 -C "pwr8" --output-o /buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys-o.a.tmp --startup-file=no --warn-overwrite=yes --sysimage /buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys.ji /buildworker/worker/package_linuxppc64le/build/contrib/generate_precompile.jl 1
   make[1]: *** [/buildworker/worker/package_linuxppc64le/build/usr/lib/julia/sys-o.a] Error 1
   make: *** [julia-sysimg-release] Error 2
   ```
- FreeBSD x64 tests:
  - Sockets failure (known, introduced by #40783)
     ```
     Test Failed at /usr/home/julia/buildbot/w2_tester/tester_freebsd64/build/share/julia/stdlib/v1.8/Sockets/test/runtests.jl:524
       Expression: !(isopen(P))
     ```
  - Workers killed by a sneaky segfault (known, under investigation)
     ```
     UNHANDLED TASK ERROR: EOFError: read end of file
     ```
  - Sigterm due to tests hanging (known, under investigation and likely due to the aforementioned segfaults)
     ```
     signal (15): Terminated
     in expression starting at /usr/home/julia/buildbot/w2_tester/tester_freebsd64/build/share/julia/test/runtests.jl:93
     ```

**Pull request merged**
