### PR TITLE
Update packages.rst

### PR DESCRIPTION
**Pull request by oadams**
Included a very brief explanation of how to install packages on machines that are offline.

### CODE REVIEW

**Comment by ViralBShah** [comment]
It is worth mentioning here that this method should be used carefully, and ideally only on the same OS versions. Packages that have binary dependencies may not work when copied to other systems - usually it should just work, but it is likely there will be idiosyncracies.

**Comment by nalimilan** [comment]
Looks like you added trailing whitespaces, which makes Travis complain:
```
$ make check-whitespace || exit 1
doc/manual/packages.rst:132:
Error: trailing whitespace found in source file(s)
```

**Comment by oadams** [comment]
I should mention that this is just intended to be an incomplete stub explanation, as most of it is just copied from what vtjnash told me on IRC.

**Comment by jiahao** [comment]
Committed in 3de1471cd5c9e5452d195e76f2de4b6d556d6553

**Pull request closed without merging**
