### PR TITLE
fix newline parsing in markdown paragraphs

### PR DESCRIPTION
**Pull request by shashi**
@jakebolewski @one-more-minute 

as described in http://spec.commonmark.org/0.21/#hard-line-breaks

### CODE REVIEW

**Comment by one-more-minute** [comment]
Technically we [already have this](https://github.com/JuliaLang/julia/blob/097801bfc8881519ab8ae9d5a29140eef388cd1e/base/markdown/Common/inline.jl#L85-L90) although perhaps it's not working properly. Throwing in a `\n` character isn't really enough, since you need to render line breaks explicitly in some formats – including Markdown and HTML.

**Comment by shashi** [comment]
@one-more-minute yeah, this already exists, that's why I changed the title of the PR. specifically, this fix adds a `'\n'` at the appropriate place in paragraph parsing before it gets passed into `parseinline`. The corresponding `htmlinline`, `rstinline` methods existed for `LineBreak`, but no `terminline` method did.

**Comment by one-more-minute** [comment]
Ah I see, thanks for the explanation.

It's a little unfortunate in that it makes the `paragraph` and `linebreak` parsers inter-dependent – it'd be a shame to break that modularity, but a better design doesn't immediately occur to me. Perhaps preserving all `\n` chars at parse time and throwing them out at render time? Not sure that's any better...

**Comment by jakebolewski** [comment]
Is the goal to be able support multiple Markdown markup variants?  I feel we should just pick one and make that varient work well.

**Comment by hayd** [comment]
I think we're: CommonMark + Github Tables + Latex

**Comment by StefanKarpinski** [comment]
I agree fully with @jakebolewski – we shouldn't be configurable, just good at one thing. But I'm not sure this is at odds with that? @shashi?

**Comment by shashi** [comment]
this PR specifically makes the CommonMark compliance more correct.

**Comment by StefanKarpinski** [comment]
Great. Let's merge it them. Backportable?

**Comment by shashi** [comment]
Sure. yes, I think we should backport.

**Comment by hayd** [comment]
I find http://johnmacfarlane.net/babelmark2/ very useful for checking CommonMark compliance (easier than checking the spec).

See https://github.com/one-more-minute/Markdown.jl/issues/7.

Hmmm, there's a subtle case now that I look at that list http://johnmacfarlane.net/babelmark2/?text=--%0A**%0A__%0A (for some reason newlines should sometimes be kept...) http://spec.commonmark.org/0.21/#example-10

**Comment by tkelman** [comment]
backported in #13159

**Pull request merged**
