### PR TITLE
Evaluate Circle CI (23171 but from a branch in JuliaLang)

### PR DESCRIPTION
**Pull request by tkelman**
See #23171, this is the same thing but I'm trying to get the Circle CI webhook to recognize the PR and build from the JuliaLang account instead of my fork. ~~It might only work if `circle.yml` (or `.circle/config.yml`) is on master?~~  edit: I think something's wrong with PR's from forks? Not sure, contacted circle support to see if I can figure out what's wrong.

### CODE REVIEW

**Comment by ararslan** [comment]
39:11 for the Circle build??? I didn't think that was even possible!

**Comment by ararslan** [comment]
Good to merge once Travis finishes?

**Comment by tkelman** [comment]
Maybe it is working from forks now, #23249 triggered a build. Unless anyone has any comments on the yml contents, this should be good to merge and try out.

**Comment by ararslan** [comment]
Without this configuration merged, the Circle webhook just reports failure since there's nothing telling it what to do. That's pretty annoying. I think we should just merge this then adjust settings as needed. Though as it stands, the YAML contents look good to me.

**Comment by quinnj** [comment]
Yeah, it looked liked it thought it needed to do something for #22441, but didn't know what to do.

**Pull request merged**
