### PR TITLE
Backport #30385 + dependent changes to 1.0.4

### PR DESCRIPTION
**Pull request by jrevels**
Had to do a bit of git sleuthing to find some previous changes that #30385 depended on that hadn't yet been backported.

I'm opening this PR against `backport-1.0.4` instead of committing directly to that branch just to make sure I don't screw anything up 😛

### CODE REVIEW

**Comment by KristofferC** [comment]
This feels a bit of a large change for a patch release and it touches a lot of internals so I marked it for triage to discuss it.

**Comment by StefanKarpinski** [comment]
Agree, this feels pretty large and risky for a patch release.

**Comment by JeffBezanson** [comment]
Also agree. Only critical bug fixes should go in patch releases, not major improvements to type inference. Before anybody asks: no, inferring less accurate types is not a bug :smile:

**Comment by jrevels** [comment]
> Only critical bug fixes should go in patch releases, not major improvements to type inference. Before anybody asks: no, inferring less accurate types is not a bug 😄

Ah, sorry! I thought non-API-changing performance improvements were also fair game for patch releases, so I backported this grab-bag of compiler improvements to solve the tuple perf issues in 1.0.x. It's not really one big change so much as a bunch of related little changes, but I see your point w.r.t. risk.

I'll just close this then since there seems to be consensus.

**Pull request closed without merging**
