### PR TITLE
updated missing doc on macro @~

### PR DESCRIPTION
**Pull request by yebai**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Thanks!

**Comment by Keno** [comment]
Shouldn't this have gone to master first or is it already fixed there?

**Comment by tkelman** [comment]
Please open PR's against master first. And check which branch PR's are opened against before merging them.

**Comment by JeffBezanson** [comment]
Wow, I did not notice that. Sorry everybody.

**Comment by tkelman** [comment]
Easy to miss, and I think if you come from the edit button on the release-0.4 docs RTD does this. At least this was a harmless doc change, and if it hadn't been there would always be the option of reverting if really needed.

**Comment by yebai** [comment]
Thanks guys! I will create a PR for the master branch too.

**Pull request merged**
