### PR TITLE
add failing test for ==(::Rational, ::AbstractFloat)

### PR DESCRIPTION
**Pull request by jkroso**

### CODE REVIEW

**Comment by Keno** [comment]
As you observe, this test fails, because those values are not the same. What was your intent with this pull request?

**Comment by jkroso** [comment]
I thought it was a bug. I should have spent longer in school.

**Comment by jkroso** [comment]
So `3/5` can't be exactly represented in floating point so it should fail. Sorry for the hassle

**Comment by Keno** [comment]
No worries - floating point equality is tricky :).

**Pull request closed without merging**
