### PR TITLE
Replace @assert with throw() in winprompt()

### PR DESCRIPTION
**Pull request by petershintech**
1. The extra argument, stdcall, is a bug. The return value is just a boolean.
2. T conversion can be failed if something wrong happens in the system. So, in this case, need to raise an exception rather than assertion. I think SystemError would be the best choice for this case.

Wondering why the extra argument bug was not caught by tests. If it is missing in tests, can I have your help to add a unit test for winprompt()?

### CODE REVIEW

**Comment by yuyichao** [comment]
https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Calling-Convention-1

**Review by yuyichao — DISMISSED** [review]
stdcall has nothing to do with return type.

**Comment by petershintech** [comment]
Yichao. Thanks for the information. I only checked https://docs.julialang.org/en/v1/base/c/#ccall
It seems the doc string of ccall() needs to be updated. Am I right?

**Comment by JeffBezanson** [comment]
Also, when the function fails it updates the length argument to tell you how much space is needed. So an alternative fix is to handle that case and retry the call with a bigger buffer, after which an assertion would be warranted.

**Comment by petershintech** [comment]
I think retrying the call with a bigger buffer is a good choice to make the code more solid, but if it fails again, we need to raise an exception rather than insert an assertion, because the outcome of the call depends on the response of an external program. If Julia allows @assert to be deactivated in the future, the critical check can be bypassed.

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/pull/38828 addresses resizing the buffer  in case of failure

**Pull request closed without merging**
