### PR TITLE
fix logging macros to use the updated stdlib path

### LINKED ISSUE #45112: incorrect paths in macOS stacktraces with references to standard libraries
I was almost positive that this got fixed but I got this warning. I tried finding the original but can't seem to
```julia

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/sabae/src/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl:661

julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = code
```

on 1.7
```julia 
julia> Pkg.installed();
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/administrator/src/julia/usr/share/julia/stdlib/v1.7/Pkg/src/Pkg.jl:595

julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_NUM_THREADS = 8
```
Neither `/Users/sabae/src/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl` or `/Users/administrator/src/julia/usr/share/julia/stdlib/v1.7/Pkg/src/Pkg.jl` is real. Makes it a little annoying since you can't click to open it in vscode.

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/45112

### CODE REVIEW

**Comment by KristofferC** [comment]
Did not seem to work. After downloading the artifact from buildkite:

```
julia> Pkg.installed()
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /cache/build/default-amdci4-5/julialang/julia-master/usr/share/julia/stdlib/v1.9/Pkg/src/Pkg.jl:676
```

**Comment by KristofferC** [comment]
Works now:

```
julia> Pkg.installed()
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg ~/Downloads/julia-563ddbf31a/share/julia/stdlib/v1.9/Pkg/src/Pkg.jl:676
```

**Review by fredrikekre — APPROVED** [review]

**Comment by fredrikekre** [comment]
You can fake an embedded stdlib file by passing `_file=joinpath(STDLIB_DIR, ...)` perhaps.

**Comment by KristofferC** [comment]
Yeah, with this implementation that should work. I had an earlier whee that wouldn't work but with this it is indeed straight forward.

**Comment by fredrikekre** [comment]
win64 failed with:
```
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\corelogging.jl:125
  Expression: record.file == "/a/file"
   Evaluated: "\\a\\file" == "/a/file"
```

**Comment by KristofferC** [comment]
Yeah, I'll fix it.

**Comment by KristofferC** [comment]
The errors in Buildkite seem to also happen in other PRs.

**Pull request merged**
