### PR TITLE
Slightly less bad error messages for promote_shape

### PR DESCRIPTION
**Pull request by kshyatt**
Having been enraged by these existing cryptic error messages, I tried to give the user a bit more information about what went wrong. Happy to take suggestions on further improvements.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Fixes https://github.com/JuliaLang/julia/issues/33273 ?

**Comment by JeffBezanson** [comment]
:+1: 
Something about `DimensionMismatch("dimensions must match")` certainly smells wrong. How about adding two fields to `DimensionMismatch` for the things that don't match?

**Comment by kshyatt** [comment]
Is that what we want to do? You can have three things which have a dimensionality issue, and this occurs in the LinearAlgebra stdlib. ([Here](https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/triangular.jl#L1465), for example).

**Comment by JeffBezanson** [comment]
I guess it could be a tuple of N things. It can also be optional; we can still allow just passing a string. We do want to move away from interpolating in error messages though, since it is generally hard on the compiler (it makes many functions recursive, via a circuitous route through all of the I/O and printing code), makes it harder to compile things to e.g. GPUs, and it would often be better to separate the information from the presentation.

**Comment by kshyatt** [comment]
Yeah, that sounds reasonable. But IDK if I want to tackle rewriting `DimensionMismatch` entirely in this pr :).

**Comment by kshyatt** [comment]
BSD failure was in LibGit2.

**Comment by kshyatt** [comment]
Got the go-ahead from Jeff to merge this.

**Pull request merged**
