### PR TITLE
Avoid race condition when removing cache file

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
This addresses #14118 .

**Comment by tkelman** [comment]
I think there's technically a chance that `rm` could throw something other than a ENOENT, in which case this would mask #12720. This probably calls for either a fancier catch that checks the exception type, or a `force` keyword argument that ignores nonexistent files.

**Comment by eschnett** [comment]
See #14248.

**Comment by tkelman** [comment]
Great. I don't think I want to backport this version, unless it gets changed to add more of the checking of exceptions that you're putting into the force kwarg.

**Pull request merged**
