### PR TITLE
RFC: clean up timer API

### PR DESCRIPTION
**Pull request by JeffBezanson**
This fixes the following problems:
- start_timer and stop_timer were ugly, and are now removed.
- Timer resources were never fully freed because Timers were never closed, only "stopped". It wasn't clear whether a stopped timer was done for good, or would be restarted.
- We were calling user callbacks directly from libuv callbacks, meaning they could not block.

The new API is
- `Timer(callback, timeout, repeat=0)` creates _and starts_ a timer that calls a callback repeatedly.
- `close(timer)` stops and fully shuts down a timer. If a timer is set not to repeat, it closes itself after firing once.
- `Timer(timeout, repeat=0)` creates a timer that periodically wakes up whoever calls `wait` on it. This is used to implement `sleep` in 1 line.

~~This PR also removes `SingleAsyncWork` because it's not used anywhere and is redundant with `@schedule`.~~

Developed with @vtjnash.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Also of note: if a callback throws an exception, you will get an unexpected task exit message, which kind of makes sense.

**Comment by Keno** [comment]
SingleAsyncWork is used in packages for cross-thread communication.

**Comment by JeffBezanson** [comment]
But it's not exported and `@schedule` would do the same thing.

**Comment by Keno** [comment]
You can't call `@schedule` from a different thread at the moment.

**Comment by JeffBezanson** [comment]
You mean an actual different thread? But it's not safe to call any julia code from another thread...

**Comment by Keno** [comment]
Yes, an actual different thread. The julia code is not safe, but the underlying libuv primitive is, and single AsyncWork is the julia side interface to the listening side. This is used in quite a few packages (ZMQ most notably).

**Comment by vtjnash** [comment]
http://docs.libuv.org/en/latest/async.html

**Comment by JeffBezanson** [comment]
Looking at the ZMQ code, it uses a mix of un-exported Base functions and direct calls to libuv. We need a real API for this.

**Comment by JeffBezanson** [comment]
Also while we're on the subject, it would be nice to eventually replace the current callback mechanism with cfunction. That would eliminate a lot of redundant code.

**Comment by JeffBezanson** [comment]
Interestingly, this change actually makes Timer and SingleAsyncWork even more similar, since now they are both `preserve_handle`'d over their whole lifetimes.

**Comment by JeffBezanson** [comment]
Added back SingleAsyncWork so we can focus on the real point of this PR.

**Comment by vtjnash** [comment]
lgtm

**Comment by Keno** [comment]
LGTM as well.

**Comment by ScottPJones** [comment]
I noticed that the code in `deprecate.jl` doesn't actually make the code work, they just give an error.
These timer functions were used in 9 registered packages (such as `PyCall.jl`), which I thought was heavily used.   Have all of those packages been updated already to use the new Timer API?
(I'm not saying anything against the new API, I also think it is an improvement, I was just concerned about breakage...)

**Comment by JeffBezanson** [comment]
A non-breaking deprecation for this would be pretty awkward. You'd basically need a full copy of the old code. For full compatibility, `Timer` would need to support an extra state where it is restartable.

**Comment by ScottPJones** [comment]
OK, do you know if the 9 registered packages have been updated?  These were the places I found that would break:
```julia
/j/pkg/ImageView/src/navigation.jl:     start_timer(state.timer, dt, dt)
/j/pkg/ImageView/src/navigation.jl:     start_timer(state.timer, dt, dt)
/j/pkg/MessageUtils/src/core.jl:     start_timer(t, timeout, 0.0)
/j/pkg/MessageUtils/src/spaces.jl:     start_timer(t, 15.0, 15.0)
/j/pkg/PyCall/src/gui.jl:     Base.start_timer(timeout,sec,sec)
/j/pkg/PySide/examples/workspace.jl: ## Base.start_timer(timer,int64(200),int64(200))
/j/pkg/RCall/src/eventloop.jl:         Base.start_timer(timeout, 0.05, 0.05)
/j/pkg/React/src/timing.jl:     start_timer(t, delta, delta)
/j/pkg/React/src/timing.jl:             start_timer(timer, delta, 0)
/j/pkg/Reactive/src/timing.jl:     start_timer(t, delta, delta)
/j/pkg/Reactive/src/timing.jl:             start_timer(timer, delta, 0)
/j/pkg/Rif/src/embeddedr.jl:         start_timer(timeout,50e-3,50e-3)
/j/pkg/Tk/src/core.jl: ## Base.start_timer(timer,int64(50),int64(50))
/j/pkg/Tk/src/tkwidget.jl:     Base.start_timer(timeout,0.1,0.01)
```

**Comment by tkelman** [comment]
The fix is being worked on in https://github.com/JuliaLang/Compat.jl/pull/103. Once that's merged and tagged, the packages that used the now-broken versions need to be updated to use Compat's version.

**Comment by ScottPJones** [comment]
OK, but for the moment, PyCall and those others are broken, correct?
It seems like there should be a procedure to avoid breakage like this... like having Compat ready to merge (except for the version number) before the breaking change is merged, and then merge Compat immedately after, once the version number has been set...
This seems exactly like the sort of thing that hit us with `ODBC.jl` and `StrPack.jl`, with the tuple changes.

**Comment by ViralBShah** [comment]
Yes, we should ideally do that to avoid breakage.

**Comment by tknopp** [comment]
@ScottPJones: There is quite some disagreement about this point. In my option it should not be a goal to avoid breakage of packages on julia master. It is a little dangerous if packages immediately follow master because it can introduce bugs in the stable julia ecosystem. We had this issue in the last months with Cairo/Winston/Gtk.

**Comment by ScottPJones** [comment]
@tknopp Why can't the packages themselves have a 0.3.x version and a 0.4.x version?  The packages on the released version would remain stable, and only the ones that are used with master would keep up-to-date with master.

**Comment by tkelman** [comment]
A handful of packages do have separate code or branches for 0.3 vs 0.4. Few people want to go to that maintenance effort though. Compat, when used correctly, allows the same code to work on both 0.3 and 0.4. The primary limiting factor here, as with so many other things, is manpower. With an infinite supply of labor, ideally yes we would identify all package breakages and prepare pull requests to mitigate them ahead of time.

Until that happens, packages should generally be assumed to be broken on latest master, unless verified otherwise with a recent Travis (which only runs when the package changes, not when Julia changes), PkgEvaluator, or local test run. If you want stable use with packages you should use the release branch or pin Julia and packages to a verified working commit.

**Comment by ScottPJones** [comment]
OK, I don't know how to pin Julia and the packages to a stable set... and maybe that is something that could be done automatically...  Have on the website both the "last known good" version of 0.4, and the nightly build...  If the nightly build is stable, and PkgEvaluator gives a thumbs up, then the "last known good" is pointed to that build, otherwise, it isn't changed.

**Comment by tkelman** [comment]
See `Pkg.pin` for packages, and `git checkout sha && make` should do the job for Julia.

Anything "automatic" has to be set up by someone to start with, and what determines "last known good" is going to be different for every use case. It looks like @IainNZ could use some help running PkgEvaluator more often, it's apparently been a week since the last update? http://pkg.julialang.org/pulse.html

**Comment by ScottPJones** [comment]
@tkelman Thanks for the useful information.
Yes, "automatic" needs to be set up, but once done, it hopefully will make everybody's lives a lot easier.
In this case, I had proposed that the criteria of "last known good" is simply no regressions found by the PkgEvaluator.  Do you think that would be workable?

**Comment by IainNZ** [comment]
My opinion is that anyone on 0.4 should have no expectation of anything working on it, I really don't think its something package owners should care about (unless they want to). Its why I don't notify individual packages when things break on 0.4 in general (although I do file issues here if I suspect it was not an intentional break).

@tkelman yeah it kept having issues with packages "freezing" at the end of their tests. When I get a chance I'm going to simplify the whole thing substantially, it currently has lots of hacks for the pre `Pkg.test` days that I don't think are really necessary anymore. I also had to use the machine for something else. I'll try it again tonight.

@ScottPJones I don't really get what you are proposing.

**Comment by tkelman** [comment]
We're also way beyond even remotely related to this issue - we could look into adding a new category on https://github.com/staticfloat/status.julialang.org - right now we have https://status.julialang.org/download/linux-x86_64 for auto-updated latest nightly binary, and https://status.julialang.org/stable/linux-x86_64 for auto-updated latest release binary. And equivalent versioned links (just copies, I think) on S3. I think this is going to have to be "he who wants it needs to do it" work though.

**Comment by ScottPJones** [comment]
@IainNZ I thought the PkgEvaluator would test a package with a particular build, and give a thumbs up or down status when it was done.  If you save the state of which packages worked in the "last known good", and then compare that to the new build, the new build would only be considered "good" if there were no regressions.

**Comment by tkelman** [comment]
You'd pretty much never have "zero regressions" because packages are constantly changing too. You'd need to run PkgEvaluator in a different mode, comparing changing Julia against constant package versions. Or accept any newly introduced failures when a package changed versions since the last run, since automatically determining the difference between a package-introduced failure and a Julia-introduced failure is going to be difficult.

Right now PkgEvaluator checks latest release/master Julia against latest versions of all packages, because that's most useful for the community. The way PkgEvaluator is currently set up using Vagrant it should be not too hard to hack on it and run a custom tailored version of it for your particular purposes.

**Comment by IainNZ** [comment]
Ah I think I get what you are saying now. Yeah, thats not what its doing, its doing the mirror of that. The purpose isn't to check Julia, its to check packages. It was initially created to track regressions against "release" Julia (which was 0.2) as people started to focus more on 0.3. With the advent of Compat.jl and widespread Travis testing its actually not really as valuable as it was for that purpose. Instead its become more of a interesting unexpected-breakage-in-Base detector.

**Comment by ScottPJones** [comment]
Right, because of that, the tool would need to keep track also of which version of each package was tested.  I think it could first try with the latest version of a package, if that is a regression, then try again with the version that passed with the "last known good" version of master (I don't know how difficult it would be to assure that it's dependencies also are picked from the version that succeeded). If *that* fails, it points to master being broken, if it succeeds, it points to the package having broken.

It's not really so much for my own particular purposes, I just think this might be good for the community as a whole, seeing that a lot of time is being spent dealing with breakages (again, not meant as a criticism of anybody, just trying to help out come up with some workable solutions).

**Comment by ScottPJones** [comment]
@IainNZ Does my response to @tkelman just now make sense to you, that this "uber" package evaluator tool could help diagnose both base and package breakage?  Thanks!

**Comment by tkelman** [comment]
There might be enough data stored from past results to make all that happen if someone wants to write the logic around it all. Really this should move to an issue/enhancement discussion at https://github.com/iainnz/PackageEvaluator.jl though.

**Comment by IainNZ** [comment]
I think I'm starting to get it. Doesn't really matter if I get or not though really, I won't be the one making it :+1: Should probably move to another issue at this point though.

**Pull request merged**
