### PR TITLE
Move small arrays to the stack

### PR DESCRIPTION
**Pull request by pchintalapudi**
Stack allocation of small arrays can reduce GC pressure and occasionally expose additional optimization opportunities to LLVM.

### CODE REVIEW

**Comment by pchintalapudi** [comment]
Since my branches are part of a fork, I've created a PR comparing this one and the branch elimination PR immediately before it here: https://github.com/pchintalapudi/julia/pull/5

**Comment by DilumAluthge** [comment]
cc: @chriselrod

**Comment by pchintalapudi** [comment]
Marking as draft because #43487, #43547, #43384, and #43548 are all still under review.

**Comment by chriselrod** [comment]
Looking forward to trying this out!
I wrote a C++ version of [SIMDPolynomials.jl](https://github.com/YingboMa/SIMDPolynomials.jl) that's close to 3x faster, in part because of its ability to automatically stack allocate small arrays (I'm using `llvm::SmallVector`s).
I was curious how much this PR would help, and am looking forward to trying it.
For now, I just tried building the current state of this PR but got an error:
```
Instruction does not dominate all uses!
  %14 = load {} addrspace(10)* addrspace(13)*, {} addrspace(10)* addrspace(13)* addrspace(11)* %13, align 8, !dbg !225348, !tbaa !13683, !nonnull !0
  store atomic {} addrspace(10)* %5, {} addrspace(10)* addrspace(13)* %14 unordered, align 8, !dbg !225348, !tbaa !14013
in function japi1_getindex_27361
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by pchintalapudi** [comment]
I think I've squashed that bug and a few others now, and slightly upgraded the stack allocation process itself. Do you think you could try again now @chriselrod? Just as a note, arrays of references aren't currently being stack allocated because I haven't figured out how to make stack allocation play nicely with the garbage collector yet.

**Comment by chriselrod** [comment]
> I think I've squashed that bug and a few others now, and slightly upgraded the stack allocation process itself. Do you think you could try again now @chriselrod? Just as a note, arrays of references aren't currently being stack allocated because I haven't figured out how to make stack allocation play nicely with the garbage collector yet.

The vectors contain structs wrapping `UInt8`. They're `isbits`.
However, these vectors are held in structs themselves.
There was another issue where IIRC you and others said this may cause issues with the escape analysis?

I see no difference in allocations.

**Comment by Moelf** [comment]
This seems stalled, but it's really cool, can we push this through the goal line?

**Comment by KristofferC** [comment]
This also need some examples / benchmarks to show the effect.

**Pull request closed without merging**
