### PR TITLE
Allow exponentiation of `Diagonal{*Range}`

### LINKED ISSUE #848: Exponentiation of `Diagonal{*Range}` fails
```julia
julia> using LinearAlgebra; D = Diagonal(1:3)
3×3 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

julia> D^2
ERROR: MethodError: no method matching Vector{Int64}(::Diagonal{Int64, UnitRange{Int64}})
Closest candidates are:
  Array{T, N}(::AbstractArray{S, N}) where {T, N, S} at array.jl:540
  Vector{T}() where T at boot.jl:467
  Vector{T}(::Core.Compiler.AbstractRange{T}) where T at range.jl:1042
  ...
Stacktrace:
 [1] convert(#unused#::Type{Vector{Int64}}, a::Diagonal{Int64, UnitRange{Int64}})
   @ Base ./array.jl:532
 [2] Diagonal{Int64, Vector{Int64}}(diag::Diagonal{Int64, UnitRange{Int64}})
   @ LinearAlgebra /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:10
 [3] convert(T::Type{Diagonal{Int64, Vector{Int64}}}, m::Diagonal{Int64, UnitRange{Int64}})
   @ LinearAlgebra /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:53
 [4] to_power_type(x::Diagonal{Int64, UnitRange{Int64}})
   @ Base ./intfuncs.jl:240
 [5] power_by_squaring(x_::Diagonal{Int64, UnitRange{Int64}}, p::Int64)
   @ Base ./intfuncs.jl:255
 [6] ^(A::Diagonal{Int64, UnitRange{Int64}}, p::Int64)
   @ LinearAlgebra /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/dense.jl:447
 [7] macro expansion
   @ ./none:0 [inlined]
 [8] literal_pow(f::typeof(^), x::Diagonal{Int64, UnitRange{Int64}}, #unused#::Val{2})
   @ Base ./none:0
 [9] top-level scope
   @ REPL[41]:1
```
It fails because the `Diagonal{T,V}` constructor is being called with a diagonal matrix as argument (item [2] in the stacktrace above), whereas the constructor [here](https://github.com/JuliaLang/julia/blob/79ee2b40d45cbbae2e5da02227e6a40bfd686198/stdlib/LinearAlgebra/src/diagonal.jl#L8) expects a vector.

_Originally posted by @daanhb in https://github.com/JuliaLang/julia/issues/40831#issuecomment-844872327_

### PR DESCRIPTION
**Pull request by ArunS-tack**
Edited diagonal.jl for direct Exponentiation of Diagonal{*Range}. Fixes JuliaLang/LinearAlgebra.jl#848.

### CODE REVIEW

**Comment by mcabbott** [comment]
Note that this introduces an ambiguity:
```
julia> dd = Diagonal(rand(100));

julia> @btime $dd .^ 3;
  81.263 ns (3 allocations: 912 bytes)

julia> @btime $dd ^ 3;
  84.845 ns (2 allocations: 1.75 KiB)

julia> @eval LinearAlgebra (^)(D::Diagonal, a::Number) = Diagonal(D.diag .^ a)
^ (generic function with 67 methods)

julia> @btime $dd ^ 3;
ERROR: MethodError: ^(::Diagonal{Float64, Vector{Float64}}, ::Int64) is ambiguous. Candidates:
  ^(A::AbstractMatrix, p::Integer) in LinearAlgebra at /Users/me/.julia/dev/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:445
  ^(A::AbstractMatrix{T}, p::Real) where T in LinearAlgebra at /Users/me/.julia/dev/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:488
  ^(D::Diagonal, a::Number) in LinearAlgebra at REPL[3]:1
Possible fix, define
  ^(::Diagonal, ::Integer)
```
If you wanted to define something, perhaps it is `literal_pow` which ought to be forwarded?
```
julia> @eval LinearAlgebra (^)(D::Diagonal, a::Integer) = Diagonal(D.diag .^ a)
^ (generic function with 68 methods)

julia> @btime $dd ^ 3;
  89.945 ns (1 allocation: 896 bytes)

julia> @eval LinearAlgebra Base.literal_pow(::typeof(^), D::Diagonal, valp::Val) = Diagonal(Base.literal_pow.(^, D.diag, valp))

julia> @btime $dd ^ 3;
  37.726 ns (1 allocation: 896 bytes)
```

**Comment by ArunSanganal** [comment]
> Note that this introduces an ambiguity:
> 
> ```
> julia> dd = Diagonal(rand(100));
> 
> julia> @btime $dd .^ 3;
>   81.263 ns (3 allocations: 912 bytes)
> 
> julia> @btime $dd ^ 3;
>   84.845 ns (2 allocations: 1.75 KiB)
> 
> julia> @eval LinearAlgebra (^)(D::Diagonal, a::Number) = Diagonal(D.diag .^ a)
> ^ (generic function with 67 methods)
> 
> julia> @btime $dd ^ 3;
> ERROR: MethodError: ^(::Diagonal{Float64, Vector{Float64}}, ::Int64) is ambiguous. Candidates:
>   ^(A::AbstractMatrix, p::Integer) in LinearAlgebra at /Users/me/.julia/dev/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:445
>   ^(A::AbstractMatrix{T}, p::Real) where T in LinearAlgebra at /Users/me/.julia/dev/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:488
>   ^(D::Diagonal, a::Number) in LinearAlgebra at REPL[3]:1
> Possible fix, define
>   ^(::Diagonal, ::Integer)
> ```
> 
> If you wanted to define something, perhaps it is `literal_pow` which ought to be forwarded?
> 
> ```
> julia> @eval LinearAlgebra (^)(D::Diagonal, a::Integer) = Diagonal(D.diag .^ a)
> ^ (generic function with 68 methods)
> 
> julia> @btime $dd ^ 3;
>   89.945 ns (1 allocation: 896 bytes)
> 
> julia> @eval LinearAlgebra Base.literal_pow(::typeof(^), D::Diagonal, valp::Val) = Diagonal(Base.literal_pow.(^, D.diag, valp))
> 
> julia> @btime $dd ^ 3;
>   37.726 ns (1 allocation: 896 bytes)
> ```

Shouldn't it be vectorized dot operation though since its more obvious? Literal_pow multiplies the vector 3 times but we only need diagonal elements to be cubed.

**Comment by dkarrasch** [comment]
> Literal_pow multiplies the matrix 3 times but we only need diagonal elements to be cubed.

In @mcabbott's suggestion, `literal_pow` was applied in broadcasted form.

**Comment by dkarrasch** [comment]
You could create a new branch on your new fork, and there make the new changes.

**Comment by ArunSanganal** [comment]
It shows the commits I have already made in the other PR. If I make another branch and make a new PR, those commits will get added again in the PR.

**Comment by dkarrasch** [comment]
No worries, I'll take over and prepare a PR based on the comments so far.

**Pull request closed without merging**
