### PR TITLE
deprecate histogram functionality

### PR DESCRIPTION
**Pull request by simonbyrne**
The new `Histogram` type is now in [StatsBase.jl](https://github.com/JuliaStats/StatsBase.jl). This deprecates the histogram functions (`hist`,`hist!`,`histrange`,`midpoints`) from Base. See discussion in #6601.

### CODE REVIEW

**Comment by ViralBShah** [comment]
We should remove this from Base in 0.4 in favour of the functionality in StatsBase.

**Comment by jakebolewski** [comment]
Bump. A couple of the tests rely on `hist` functionality, should they be rewritten?

**Comment by ViralBShah** [comment]
We can comment them out for now, and rewrite them, or move those tests to StatsBase.

**Comment by IainNZ** [comment]
+1 for removing, and also the older comments that it invites confusion (I tried to use it in the count-uniques sense earlier today...). StatsBase is great and very widely used - most users will have it installed anyway.

**Comment by BobPortmann** [comment]
I'm fine with moving histogram functionality to StatsBase, but do have some issues with the implementation in StatsBase.

1. There does not seem to be an function to make a N dimensional histogram from a Array{T,N}. Instead one must input a NTuple{N,AbstractVector}. This seems strange to me, as any time I would want to compute a N-dimentional histogram the data would be in an Array. Also, the edges need to be input as a NTuple{N,AbstractVector} instead of a Array{T,N}, which seems awkward. Maybe I just didn't look in the right place?

2. Why is the function called "fit"? A histogram is computed directly from the input data and the edges. There is no fitting involved. I would much prefer to call the function hist or histogram as is more common and much more discoverable.

**Comment by johnmyleswhite** [comment]
Having a function called `hist` is fine. But a histogram is both a descriptive statistic and an inferential statistic, so it's certainly a type of model that one fits to the data.

**Comment by simonbyrne** [comment]
I've updated the PR.

@BobPortmann Those are good points: would you mind opening an issue on StatsBase?

**Comment by ViralBShah** [comment]
Bump.

**Comment by quinnj** [comment]
This was a 0.4.x milestone PR; still relevant? Should we remove `hist` & friends before 0.5 release?

**Comment by ViralBShah** [comment]
Marking 0.5.0 for the triage team.

**Comment by simonbyrne** [comment]
Closed in favour of #16450

**Pull request closed without merging**
