### PR TITLE
🤖 [master] Bump the Distributed stdlib from 6c7cdb5 to c613685

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Distributed
URL: https://github.com/JuliaLang/Distributed.jl
Stdlib branch: master
Julia branch: master
Old commit: 6c7cdb5
New commit: c613685
Julia version: 1.12.0-DEV
Distributed version: 1.11.0(Does not match)
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/Distributed.jl/compare/6c7cdb5860fa5cb9ca191ce9c52a3d25a9ab3781...c6136853451677f1957bec20ecce13419cde3a12

```
$ git log --oneline 6c7cdb5..c613685
c613685 Merge pull request #116 from JuliaLang/ci-caching
20e2ce7 Use julia-actions/cache in CI
9c5d73a Merge pull request #112 from JuliaLang/dependabot/github_actions/codecov/codecov-action-5
ed12496 Merge pull request #107 from JamesWrigley/remotechannel-empty
010828a Update .github/workflows/ci.yml
11451a8 Bump codecov/codecov-action from 4 to 5
8b5983b Merge branch 'master' into remotechannel-empty
729ba6a Fix docstring of `@everywhere` (#110)
af89e6c Adding better docs to exeflags kwarg (#108)
8537424 Implement Base.isempty(::RemoteChannel)
6a0383b Add a wait(::[Abstract]WorkerPool) (#106)
1cd2677 Bump codecov/codecov-action from 1 to 4 (#96)
cde4078 Bump actions/cache from 1 to 4 (#98)
6c8245a Bump julia-actions/setup-julia from 1 to 2 (#97)
1ffaac8 Bump actions/checkout from 2 to 4 (#99)
8e3f849 Fix RemoteChannel iterator interface (#100)
f4aaf1b Fix markdown errors in README.md (#95)
2017da9 Merge pull request #103 from JuliaLang/sf/sigquit_instead
07389dd Use `SIGQUIT` instead of `SIGTERM`
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @vchuravy

**Comment by vchuravy** [comment]
I haven't reviewed most PRs that got merged, I don't have the bandwidth for Distributed.jl these days.
It looks like @ViralBShah has been looking at these.

**Comment by DilumAluthge** [comment]
Maybe also cc @jpsamaroo

**Comment by ViralBShah** [comment]
Yes @jpsamaroo probably is best. Perhaps @JamesWrigley too. I only was able to look into some housekeeping

**Review by inkydragon — COMMENTED** [review]
If someone wants to review functional changes in depth.
The following is a list of changes that do not include CI maintenance and document formatting changes.

- BUG: fix undefined value error
	Fix RemoteChannel iterator interface [#100](https://github.com/JuliaLang/Distributed.jl/pull/100/files)
- ENH:  Use `SIGQUIT` instead of `SIGTERM` [#103](https://github.com/JuliaLang/Distributed.jl/pull/103/files)
- API: Add a `wait(::[Abstract]WorkerPool)` [#106](https://github.com/JuliaLang/Distributed.jl/pull/106/files)
- API: Implement `Base.isempty(::RemoteChannel)` [#107](https://github.com/JuliaLang/Distributed.jl/pull/107/files)
- DOC: Adding better docs to exeflags kwarg for `addprocs` [#108](https://github.com/JuliaLang/Distributed.jl/pull/108/files)

Other CI maintenance and document formatting changes look good to me.

-----

On a side note, I've found that it helps to quickly review a large number of commits
if we squash the commits by default and add categories to the commit messages.

I'm using scipy style: [Writing the commit message](https://docs.scipy.org/doc/scipy/dev/contributor/development_workflow.html#writing-the-commit-message)

**Review by jpsamaroo — APPROVED** [review]
Should be good to go, I would just keep an eye out to make sure the SIGQUIT changes don't cause any issues with CI cleanup (not that I would expect it to).

**Pull request merged**
