### PR TITLE
Stateful: fix major bug in implementation

### LINKED ISSUE #26339: Suboptimal inference of === with Union{}
An Int, is never `===` to `Union{}`, but inference doesn't seem to be able to figure that out.
Curiously, it does figure it out for most other types:

```
julia> f(T) = T === Union{} ? 1 : ""
f (generic function with 1 method)

julia> @code_typed f(2)
CodeInfo(:(begin
      Core.SSAValue(1) = (T === Union{})::Bool
      unless Core.SSAValue(1) goto 4
      return 1
      4:
      return ""
  end)) => Union{Int64, String}

julia> f(T) = T === Int ? 1 : ""
f (generic function with 1 method)

julia> @code_typed f(2)
CodeInfo(:(begin
      goto 2
      2:
      return ""
  end)) => String
```

### LINKED ISSUE #26417: Inference regression with === nothing
The return type `f(1)` used to be inferred as `Int` on 0.6.2, but on master it's inferred as `Union{Int,Nothing}`. It still works when using `isa Nothing` though.
```julia
f(x) = x === nothing ? nothing : 1
```

### PR DESCRIPTION
**Pull request by vtjnash**
And re-tighten Inference information for Const boolean converted to Conditional

fix #26417
fix #26339

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Was this a behavioral bug or a performance bug?

**Comment by Keno** [comment]
Implementation looks fine to me, but it's a bit odd that the commit message says this fixes a bug in Stateful, when neither of the bugs it fixes uses Stateful.

**Comment by vtjnash** [comment]
Behavioral bug. `Stateful` was depending on Inference failing here in order to not reach its bad code (its tfunc model for `iterate` was wrong).

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27972#issuecomment-403678139) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/95026663dd7b2094600c6cdbff99f357bcdd8f08/4bbe12e_vs_d8f70a5/report.md). cc @ararslan

**Pull request merged**
