### PR TITLE
Add a callback so packages can correct line numbers for "moving code"

### PR DESCRIPTION
**Pull request by timholy**
One of the most longstanding [annoyances with Revise](https://github.com/timholy/Revise.jl/issues/51) is that heavy editing of source files can cause line numbers to become wildly inaccurate. Rather than recompile all the code just to update the line numbers, this PR allows one to register a callback to correct the line numbers before showing the stacktrace to the user. Together with a [heavily-redesigned Revise](https://github.com/timholy/Revise.jl/pull/116), initial local testing suggests this strategy is effective.

While the necessary changes to Revise were extensive, this PR is pretty modest.

### CODE REVIEW

**Comment by timholy** [comment]
Any objections to this?

**Comment by StefanKarpinski** [comment]
Nope. Since it's not an official API, I'm quite happy to have it to help make Revise work better.

**Comment by Liozou** [comment]
This PR completely ruined #28016... The original example given there now yields:

**Comment by Liozou** [comment]
Namely, it would be much easier if `update_stackframes_callback[]` could be called on each stackframe separately and yield another stackframe. The number of repetitions doesn't have to be touched, and it would be more convenient than operating on the entire stacktrace.

**Comment by Liozou** [comment]
I'm also not sure to understand the reason for a `try...catch` block around the call to `invokelatest(update_stackframes_callback[], ...)` since `update_stackframes_callback[]` is rightfully initialized to `identity`. But that's less important.

**Comment by KristofferC** [comment]
Would perhaps have been good with a test in #28016.

**Comment by StefanKarpinski** [comment]
Indeed, this should definitely have a test so that people's changes can't silently mess with it.

**Comment by timholy** [comment]
Oh dear, sorry this messed that up.

The reason for the `try/catch` block is just for safety, in case the user writes a badly-behaved function that sometimes throws an error. (If julia has an error while handling errors, the result is often quite messy.)

I'll review #28453 pronto.

**Pull request merged**
