### PR TITLE
Revert inlined method signature stacktrace lookup code

### PR DESCRIPTION
**Pull request by BioTurboNick**
The fallback code that was written for #41099 is causing unintended issues with some inlined stack frames (one previous #51405, new #52709), since the main piece, linetable storage and lookup, was removed in #50546. Probably better to strip it all back to how it was previously, until it can all be revisited more fully.

Should be backported to 1.10.

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]

**Review by aviatesk — APPROVED** [review]
LGTM. Would it be difficult to add tests?

**Comment by BioTurboNick** [comment]
```
using LinearAlgebra
f(M::AbstractMatrix) = f!(copy(M))
function f!(M::AbstractMatrix)
    m, n = size(M)
    for j in 1:min(n, m)
        for i in max(1, j - 1):m
            g(M)
        end
    end
    M
end
g(::AbstractMatrix) = error()
g(::Matrix) = nothing

f(zeros(5, 5))
f(Diagonal(1:5))
#=
ERROR:
Stacktrace:
 [1] error()
   @ Base .\error.jl:44
 [2] g(::Diagonal{Int64, Vector{Int64}})
   @ Main .\REPL[4]:1
 [3] f!(M::Matrix{Float64}) # <------ wrong type
   @ Main .\REPL[11]:5 [inlined]
 [4] f(M::Diagonal{Int64, UnitRange{Int64}})
   @ Main .\REPL[2]:1
 [5] top-level scope
   @ REPL[13]:1
=#
```

I simplified a triggering condition as much as I could. It seems to actually be a pretty narrow set of conditions. I'll make a test for it shortly.

**Comment by BioTurboNick** [comment]
Trying to see if there's a simpler way to create the effect than this. I notice the function, when it has a problem, has different effects than when it doesn't:

```
Problem: (!c,!e,!n,!t,!s,!m,+i)′
No problem: (+c,+e,!n,+t,+s,+m,+i)
```
If so, I'm wondering if I can force Julia to apply the former to a simpler function... `@assume_effects` doesn't seem to do it.

**Comment by vtjnash** [comment]
This hack should also be fully unnecessary once someone merges https://github.com/JuliaLang/julia/pull/52415 since that preserves the information natively (indeed, I think it already replaces it there with a corrected version)

**Comment by BioTurboNick** [comment]
Oh sweet!

**Comment by BioTurboNick** [comment]
In that case, maybe a test just isn't needed - it's sort of an edge case that only exists as an edge case because of a quirk of this code. It's extremely unlikely to resurface now that the approach I was previously trying to use won't be necessary.

**Comment by aviatesk** [comment]
Ok, then let's move this forward as is.

**Pull request merged**
