### PR TITLE
Update VERSION for 1.3

### PR DESCRIPTION
**Pull request by KristofferC**
To be merged after https://github.com/JuliaLang/julia/pull/33940

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like this is the NEWS commit rather than the VERSION bump?

**Comment by KristofferC** [comment]
wow

**Comment by ararslan** [comment]
Seems to need a rebase on release-1.3, since this is apparently from before 1.3.0-rc5 was released

**Comment by KristofferC** [comment]
wow

that removing a few characters would be so hard

**Review by ararslan — APPROVED** [review]

**Pull request merged**
