### PR TITLE
add regression test for inference failure on 0.5

### LINKED ISSUE #19362: Type inference failure on 0.5
Noticed this when testing the lifting ideas @vtjnash suggested:

```julia
# lifttest.jl
using Compat #0.9.3
abstract MaybeNullable
immutable YesNullable <: MaybeNullable end
immutable NoNullable <: MaybeNullable end
Base.@pure any_nullable(x,y) = 
    ifelse((x<:Nullable) | (y<:Nullable), YesNullable(), NoNullable())

@inline lift(f, x, y) = lift(f, x, y, any_nullable(typeof(x), typeof(y)))
@inline lift(f, x, y, ::NoNullable) = f(x, y)

@inline function lift(f, x1, x2, ::YesNullable)
    if null_safe_op(f, typeof(x1), typeof(x2))
        return @compat Nullable(
            f(x1.value, x2.value), !(isnull(x1) | isnull(x2)))
    else
        U = Core.Inference.return_type(
            f, Tuple{eltype(typeof(x1)), eltype(typeof(x2))})
        if isnull(x1) | isnull(x2)
            return Nullable{U}()
        else
            return Nullable(f(unsafe_get(x1), unsafe_get(x2)))
        end
    end
end
```

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> include("/Users/David/.julia/v0.6/StructuredQueries/lifttest.jl")
lift (generic function with 3 methods)

julia> @code_warntype lift(*, Nullable(1), Nullable(2))
Variables:
  #self#::#lift
  f::Base.#*
  x::Nullable{Int64}
  y::Nullable{Int64}
  U::Any
  #temp#::Nullable{T}

Body:
  begin 
      # meta: location /Users/David/.julia/v0.6/StructuredQueries/lifttest.jl lift 11
      NewvarNode(:(U::Any))
      unless (Main.null_safe_op)(f::Base.#*,Nullable{Int64},Nullable{Int64})::Any goto 7 # line 12:
      #temp#::Nullable{T} = $(Expr(:new, Nullable{Int64}, :((Base.box)(Base.Bool,(Base.not_int)((Base.box)(Base.Bool,(Base.not_int)((Base.box)(Base.Bool,(Base.or_int)((Core.getfield)(x,:isnull)::Bool,(Core.getfield)(y,:isnull)::Bool))))))), :((Base.box)(Int64,(Base.mul_int)((Core.getfield)(x,:value)::Int64,(Core.getfield)(y,:value)::Int64)))))
      goto 18
      7:  # line 15:
      U::Any = $(Expr(:invoke, LambdaInfo for return_type(::Any, ::Any), :((Core.getfield)(Core.Inference,:return_type)::Core.Inference.#return_type), :(f), Tuple{Int64,Int64})) # line 17:
      unless (Base.box)(Base.Bool,(Base.or_int)((Core.getfield)(x::Nullable{Int64},:isnull)::Bool,(Core.getfield)(y::Nullable{Int64},:isnull)::Bool)) goto 15 # line 18:
      #temp#::Nullable{T} = ((Core.apply_type)(Main.Nullable,U::Any)::Type{_<:Nullable})()::Nullable{T}
      goto 18
      15:  # line 20:
      #temp#::Nullable{T} = $(Expr(:new, Nullable{Int64}, false, :((Base.box)(Int64,(Base.mul_int)((Core.getfield)(x,:value)::Int64,(Core.getfield)(y,:value)::Int64)))))
      18: 
      # meta: pop location
      return #temp#::Nullable{T}
  end::Nullable{T}
```

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.1258 (2016-11-16 17:32 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 06a21b0* (1 day old master)
|__/                   |  x86_64-apple-darwin15.6.0

julia> include("/Users/David/.julia/v0.6/StructuredQueries/lifttest.jl")
lift (generic function with 3 methods)

julia> @code_warntype lift(*, Nullable(1), Nullable(2))
Variables:
  #self#::#lift
  f::Base.#*
  x::Nullable{Int64}
  y::Nullable{Int64}
  U::Type{Int64}
  #temp#::Nullable{Int64}

Body:
  begin 
      $(Expr(:inbounds, false))
      # meta: location /Users/David/.julia/v0.6/StructuredQueries/lifttest.jl lift 11
      NewvarNode(:(U::Type{Int64}))
      unless (Main.null_safe_op)(f::Base.#*,Nullable{Int64},Nullable{Int64})::Any goto 8 # line 12:
      #temp#::Nullable{Int64} = $(Expr(:new, Nullable{Int64}, :((Base.box)(Base.Bool,(Base.not_int)((Base.box)(Base.Bool,(Base.or_int)((Base.box)(Base.Bool,(Base.not_int)((Core.getfield)(x,:hasvalue)::Bool)),(Base.box)(Base.Bool,(Base.not_int)((Core.getfield)(y,:hasvalue)::Bool))))))), :((Base.box)(Int64,(Base.mul_int)((Core.getfield)(x,:value)::Int64,(Core.getfield)(y,:value)::Int64)))))
      goto 19
      8:  # line 15:
      U::Type{Int64} = $(QuoteNode(Int64)) # line 17:
      unless (Base.box)(Base.Bool,(Base.or_int)((Base.box)(Base.Bool,(Base.not_int)((Core.getfield)(x::Nullable{Int64},:hasvalue)::Bool)),(Base.box)(Base.Bool,(Base.not_int)((Core.getfield)(y::Nullable{Int64},:hasvalue)::Bool)))) goto 16 # line 18:
      #temp#::Nullable{Int64} = $(Expr(:new, Nullable{Int64}, false))
      goto 19
      16:  # line 20:
      #temp#::Nullable{Int64} = $(Expr(:new, Nullable{Int64}, true, :((Base.box)(Int64,(Base.mul_int)((Core.getfield)(x,:value)::Int64,(Core.getfield)(y,:value)::Int64)))))
      19: 
      # meta: pop location
      $(Expr(:inbounds, :pop))
      return #temp#::Nullable{Int64}
  end::Nullable{Int64}
```

### PR DESCRIPTION
**Pull request by KristofferC**
Closes #19362

### CODE REVIEW

**Comment by KristofferC** [comment]
AppVeyor failed on a pkg test.

**Comment by kshyatt** [comment]
Needs a rebase

**Comment by KristofferC** [comment]
@vtjnash could you look if this test makes sense, it is using `Core.Inference` and `@pure` functions and I don't want to merge something that we don't want to test for. The issue this was taken from is #19362.

**Comment by vtjnash** [comment]
It would be nice to have more of a MRE. IIRC, this example was just showing whether we could infer that a singleton type has once instance. I'm not sure that's worth adding another test for.

**Comment by StefanKarpinski** [comment]
I resolved the conflicts, hopefully correctly.

**Comment by KristofferC** [comment]
Almost :P

```
$ make check-whitespace
test/inference.jl:548:  
Error: trailing whitespace found in source file(s
```

**Comment by StefanKarpinski** [comment]
GitHub's conflict resolve editor is amazingly bad at whitespace.

**Comment by tkelman** [comment]
why the close, shouldn't this be tested?

**Comment by KristofferC** [comment]
Comment for close would be kind when closing someone else's PR.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/19362#issuecomment-304081986 said

> Not a bug, just a suboptimal inference result

but isn't it still worth regression testing the inference result quality?

**Comment by vtjnash** [comment]
yeah, but we already have some unit tests for this item (as mentioned in my comment above)

**Comment by KristofferC** [comment]
Ok i didn't see the comment on the other issue.

**Pull request closed without merging**
