### PR TITLE
Disable globbing for curl download (#23254)

### LINKED ISSUE #23254: download() does not disable globbing for curl (-g)
When using download() with a URL that contains `[ ]` or `{ }`, Julia crashes with

    ERROR: LoadError: failed process: Process(`curl ...

This could be prevented by using the `-g` or `--globoff` switch.
Version info (Arch Linux binary):

    Julia Version 0.6.0
    Commit 903644385b* (2017-06-19 13:05 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
      WORD_SIZE: 64
      BLAS: libblas
      LAPACK: liblapack
      LIBM: libm
      LLVM: libLLVM-4.0.0 (ORCJIT, skylake)

### PR DESCRIPTION
**Pull request by 0x47**
Fixes #23254

### CODE REVIEW

**Review by nalimilan — APPROVED** [review]
Thanks! This indeed looks more correct, safer and consistent with other download methods.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by ararslan** [comment]
Would it be worth adding a test with a URL that would otherwise have failed as in the linked issue?

**Comment by nalimilan** [comment]
That would be cool but I'm not sure how it could work, as the man page for `curl` seems to imply `{}[]` are not valid characters in a URL and should be escaped. Maybe we could test that the download fails when the URL contains these characters in a case where it succeeds without `-g`? Then we will also need a stable URL to test for.

**Comment by StefanKarpinski** [comment]
I thought about that, but let's not bother – making our test suite depend on one more external link is really not worth it. This is a feature of `curl` which is a really stable piece of software, we don't need to do their testing for them.

**Comment by ararslan** [comment]
Good point. Thanks for the contribution, @0x47!

**Pull request merged**
