### PR TITLE
Cleaned up test set PR

### PR DESCRIPTION
**Pull request by kshyatt**
@tkelman what are your thoughts?

### CODE REVIEW

**Comment by tkelman** [comment]
This looks very good. I'm confused exactly what's going on with `test/test.jl` now though (looking at https://github.com/JuliaLang/julia/pull/18738/commits/8982605c1998061a95181b6a52a54110d019dc75?w=1#diff-5222cfa9e61d516842beb8a60f07e58e). Did `@testset` always return the testset object itself, or is that a new behavior? Does it still throw? Do we need to be doing the try-catch in the "accounting" testset? Do the docs for `Base.Test` need updating? If so it can be a separate follow-up, but it would need doing.

**Comment by kshyatt** [comment]
`@testset` always returns itself, and it does still throw if it is the top-level testset (inner ones do not throw so that you can see if a file had multiple failures).

Docs shouldn't need much of an update, I can take a thorough look tomorrow and open a PR for it?

I think `try-catch` should stay for now.

**Comment by tkelman** [comment]
dates/accessors allocates way more here than before merging, wonder why

**Comment by kshyatt** [comment]
@quinnj and @Sacha0, any thoughts?

**Comment by ihnorton** [comment]
@kshyatt was it intentional to remove summary printing? I only see one call to `print_test_results` in `test/runtests.jl`, whereas the summaries used to be printed by `finish`.

Ref this discourse question: https://discourse.julialang.org/t/test-summary-in-julia-0-6/1461

**Comment by KristofferC** [comment]
IIRC the argument was that the testsets printing  was to verbose for use in Base and they therefore got removed. Imo this should instead probably just be explicitly disabled by the Base test runner somehowand the default left like it used to be.

**Comment by Arkoniak** [comment]
Real problem was in this log: https://travis-ci.org/Arkoniak/MXNet.jl/jobs/191010907. Error message is on the row 2726 and "ERROR: LoadError: Some tests did not pass: 347 passed, 0 failed, 3 errored, 0 broken." is almost useless. I do not think, that +20 rows would be too verbose, but they will make search much more easier in cases like this.

**Comment by TotalVerb** [comment]
Unfortunately `Base.Test.print_test_results` is not available on 0.5. If this is the way forward, then it should be added to Compat.

**Comment by StefanKarpinski** [comment]
OMG, thank goodness this finally got merged!

**Comment by tkelman** [comment]
in september...

**Pull request merged**
