### PR TITLE
docs: make mod an operator

### PR DESCRIPTION
**Pull request by Mo-Gul**
(unfortunately I couldn't run `make docs` because I am a Windows child and this command failed ...)

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Thanks for the contribution!

**Comment by nsajko** [comment]
The result has ugly spacing:

screenshot_mod

> (unfortunately I couldn't run `make docs` because I am a Windows child and this command failed ...)

What I usually do is look at the PDF manual generated by the CI after I submit the PR here.

**Comment by Mo-Gul** [comment]
@nsajko thank you very much for the tip. Unfortunately, as can be seen here, this quite late, but of course better than nothing. Of course that was not the intended result. But this seems to be a known problem/limitation of `\mod` in LaTeX (see <https://tex.stackexchange.com/q/137073/95441>).

So a possible solution could be to use `\pmod` instead, i.e. change

```
Find `y` in the range `r` such that ``x ≡ y (\\mod n)``, where `n = length(r)`,
```

to 

```
Find `y` in the range `r` such that ``x ≡ y \\pmod n``, where `n = length(r)`,
```

which might introduce a to big space before the operator. Also it is unknown (to me), if this command does exist in however Documenter.jl transforms this to the HTML output.

Maybe this is the reason why the docstrings for `rem` write something similar as

https://github.com/JuliaLang/julia/blob/fb77d60fb7088a3b8ccac73ea3476b9a8c88d455/base/int.jl#L600

So the safe, non-LaTeX alternative should be

```
Find `y` in the range `r` such that `x` ≡ `y` (mod `n`), where `n = length(r)`,
```

Can someone confirm this? And if yes, shall I push another commit to this PR or create a new one?

(Sorry, I am very new to all this stuff ...)

**Comment by nsajko** [comment]
> shall I push another commit to this PR or create a new one?

This one is merged already, create a new one.

**Pull request merged**
