### PR TITLE
deprecate vectorized ! and ~ in favor of dot syntax

### PR DESCRIPTION
**Pull request by Sacha0**
With benefit of #20249, this pull request deprecates all remaining vectorized `!`  and `~` methods in favor of dot syntax (`.!`, `.~`). (`.~` does not parse as a unary operator; the second commit changes that.) Best!

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I have to say there's something about unary operators that makes me feel like they should be vectorized. Of course, then we don't get loop fusion, but writing `.!v` just looks really odd.

**Comment by ararslan** [comment]
Having a unary operators be exempt from the "no vectorization without dot representation" ideal seems a little iffy. But at the same time, I have to agree that the dots for unary ops look weird wherever you put them, especially before the operator. (`!.v` isn't too terrible IMO.)

Regarding loop fusion, it seems that they could be special-cased to achieve loop fusion, but then that's _two_ special cases for unary ops...

**Comment by Sacha0** [comment]
Rebased and now passing CI.

> writing .!v just looks really odd

> the dots for unary ops look weird [...] especially before the operator

I sympathize, hence #20540 for options next dev cycle. (Will clean that up later.) Best!

**Review by tkelman — APPROVED** [review]
lgtm

**Pull request merged**
