### PR TITLE
Fix behavior of foldr on single-element arrays

### LINKED ISSUE #21493: foldr failing for one element arrays on 0.6
I did not find anything in NEWS.

julia v0.5.1
```julia
julia> foldr(+, [1])
1

julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

```
julia latest master:
```jula
julia> foldr(+, [1])
ERROR: BoundsError: attempt to access 1-element Array{Int64,1} at index [0]
Stacktrace:
 [1] mapfoldr_impl(::Base.#identity, ::Base.#+, ::Int64, ::Array{Int64,1}, ::Int64) at ./reduce.jl:110
 [2] mapfoldr(::Base.#identity, ::Function, ::Array{Int64,1}) at ./reduce.jl:139
 [3] foldr(::Function, ::Array{Int64,1}) at ./reduce.jl:166

julia> versioninfo()
Julia Version 0.6.0-pre.beta.245
Commit d31f196* (2017-04-22 01:52 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #21493

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
lgtm! :)

(Though not for this PR, making `mapfoldr_impl` mirror `mapfoldl_impl` in not assuming indexing from one might be worthwhile.)

**Comment by ararslan** [comment]
Could be as simple as replacing `i == 0` here with `i < first(linearindices(itr))`.

**Comment by Sacha0** [comment]
(Usage in the `else` would also need to change?)

**Comment by ararslan** [comment]
Ah yeah, probably.

As an aside: 64-bit AV failure unrelated

**Comment by Sacha0** [comment]
(Absent objections, requests for time, or someone beating me to it, I plan to merge this tomorrow morning. Best!)

**Pull request merged**
