### PR TITLE
Move number-related files to numbers directory

### PR DESCRIPTION
**Pull request by simonbyrne**
Okay, this is a bit of a bike shed, but the number of files in base means that it is starting to get difficult to navigate. There is perhaps room for discussion as to which files should be moved where, but I figured this seemed like a good start.

I've intentionally left out primes.jl, pending #16481.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Agree with the direction, but I think it would be better to isolate pieces that could actually become separate modules or packages, per the discussion in #16357.

**Comment by StefanKarpinski** [comment]
Doesn't this seem like a good first step in that direction?

**Comment by JeffBezanson** [comment]
I don't really see how, since most of this code will never be removed from Base.

**Comment by simonbyrne** [comment]
So if it's going to remain in Base, doesn't make sense to keep it somewhat organised?

**Comment by JeffBezanson** [comment]
It could, but personally I find lots of directories more annoying, unless they represent really obvious components. Thinking about it as "these files could form a separate package" is likely to be a good test for whether the organization is useful.

Looking at it, I see we have several bits that have both a file and a directory, e.g. both `pkg` and `pkg.jl`, `sparse` and `sparse.jl`. I think `x.jl` should be moved into `x/` in these cases, which will help clean up the base directory a bit.

**Comment by quinnj** [comment]
Yeah, I did the same thing for the `dates/` directory and the `base/Dates.jl` file, the distinction being the `base/Dates.jl` file is what `sysimg.jl` knows about, and includes all the `include("dates/.")` commands. I think it's fine moving it into the `dates/` directory, but I thought of it more as the "Base interface" file or a breadcrumb to where the Dates.jl code is coming from.

**Comment by oscardssmith** [comment]
Possibly a good idea, but if we wanted this, it would be easier to make a new PR from scratch.

**Pull request closed without merging**
