### PR TITLE
Add macro version of dump

### PR DESCRIPTION
**Pull request by omus**
Makes it easier to call `dump` on handcrafted expressions:

```julia
julia> Meta.@dump x.*(y+z)
...

julia> dump(:(x.*(y+z)))
...
```

Note that `Meta.@dump` does not evaluate the given expression:
```julia
julia> Meta.@dump x.*(y+z)
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol .*
    2: Symbol x
    3: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol +
        2: Symbol y
        3: Symbol z
      typ: Any
  typ: Any
```

### CODE REVIEW

**Comment by tshort** [comment]
How about naming that `@dumpex`? If it's `@dump`, I'd expect it to act like `@show` and evaluate the expression first.

**Comment by StefanKarpinski** [comment]
I have wanted a macro that does this on many occasions.

**Comment by StefanKarpinski** [comment]
I can see the reasoning, @tshort, but otherwise why have/use the macro form?

**Comment by yuyichao** [comment]
> why have/use the macro form?

The same reason people use `@show`?

**Comment by tshort** [comment]
I'm thinking that the naming similarity of `dump` / `@dump` and `show` / `@show` might be confusing. If someone has `@show` in their code, they may want to change it to `@dump` to see the structure. 

@yuyichao beat me to it, I see.

**Comment by StefanKarpinski** [comment]
The reason `@show` is a macro is so that it can print `ex = val`. Similarly, there would be a reason for `@dump` to be a macro, which would be so it can dump the expression structure instead of the value. Different reason, different behavior, but there has to be a reason for something to be a macro. In anycase, I don't really feel too strongly about this, but I'm not sure calling it `@dumpex` is really necessary – `dump` is a function that dumps the structure of a value, `@dump` is a macro that dumps the structure of an expression. Seems fine to me.

**Comment by yuyichao** [comment]
`@dump` looks too similar to `@show`, in fact, I was really surprised to see @tshort 's comment and was assuming that the macro shows `ex = $(dump(ex))` instead of what it is doing now.

If `dump` is a function that only works on expressions, it would make some sense to make a macro version that quotes the input. However, it is not and I've personally actually use it more on other values than on expressions. Being a macro is also not really suggesting that it should quote the input. That's not what `@show` does at least.

**Comment by yuyichao** [comment]
In another word, I'd be fine with a `Meta.@show_sexpr` that printes the input as expression rather than value, but not for `dump`.

**Review by ararslan — APPROVED** [review]

**Comment by omus** [comment]
@yuyichao is this the implementation you expected?
```julia
macro dump(ex)
    quote
        print($(sprint(Base.show_unquoted, ex) * " = "))
        print($(sprint(dump, ex)))
        println()
    end
end
```
```julia
julia> @dump2 x.*(y+z)
x .* (y + z) = Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol .*
    2: Symbol x
    3: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol +
        2: Symbol y
        3: Symbol z
      typ: Any
  typ: Any
```

**Comment by yuyichao** [comment]
> is this the implementation you expected?

Yes.

**Comment by omus** [comment]
`@dump` works similarly to `@show` now. I've updated the description with an example.

**Comment by yuyichao** [comment]
Sorry, no that's not what I expect. I expect it to evaluate the expression .

**Comment by yuyichao** [comment]
What I expected was,

```julia
macro dump(ex)
    quote
        print($(sprint(Base.show_unquoted, ex) * " = "))
        dump($(esc(ex)))
        println()
    end
end
```

**Comment by omus** [comment]
Thanks @yuyichao for explaining. I can see the argument for that implementation of the dump macro.

**Comment by omus** [comment]
Since this implementation only dumps expressions I'll rename the macro in this PR to `@dumpexpr`.  The `dumpex` name isn't great as it could be interpreted as "dumpx" in conversation. Additionally naming the macro `dumpx` isn't very clear on what the macro does.

**Comment by yuyichao** [comment]
`@dumpexpr` sounds good to me. `@dumpx` would be again too similar to the deprecated and removed `xdump`......

**Comment by JeffBezanson** [comment]
Isn't this what `Meta.show_sexpr` is for? Or, maybe put it in `Meta`? I hesitate to add Yet Another Export for this.

**Comment by yuyichao** [comment]
`Meta.@dump`? If it's namespaced in `Meta` it'll be perfectly fine for me to call it `@dump`.

**Comment by omus** [comment]
I changed the name back to `@dump` and put it in the `Meta` module. I've added it to the export list to `Meta` so doing `using Base.Meta` will allow you to simply call `@dump` for those who want to have this macro available in `Main`.

**Comment by omus** [comment]
Any other comments here? I'll squash and merge this later today.

**Pull request merged**
