### PR TITLE
Remove non-existent `exclude_tags` kwarg from `triplet` docstring

### LINKED ISSUE #50389: Docstring and function signature of `Base.BinaryPlatforms.triplet` differ
```
Julia Version 1.10.0-DEV.1619
Commit 27e21c8865 (2023-07-01 12:01 UTC)
```

The docstring of `triplet` mentions the kwarg `exclude_tags`, whereas this kwarg does not exist in the actual code.

### PR DESCRIPTION
**Pull request by marcom**
Fixes #50389

### CODE REVIEW

**Comment by marcom** [comment]
Test failures look unrelated to this change.

**Review by brenhinkeller — APPROVED** [review]

**Comment by brenhinkeller** [comment]
Tests look good now

**Comment by LilithHafner** [comment]
@staticfloat, Git blame tells me you added this code, Can you confirm we're not missing something here?

**Comment by staticfloat** [comment]
Confirmed; I think that was missed in a rebase or something.

**Pull request merged**
