### PR TITLE
Dummy PR to do a PkgEval run

### PR DESCRIPTION
**Pull request by KristofferC**
Might as well start with this process now in preparation for 1.6, to see what the state is. Quite a lot has happened since 1.5.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-680878107) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/303a819e120eac6b87b3c74c18c024ae0359e457/pkgeval/by_hash/3573793_vs_c4acbf9/report.md). cc @maleadt

**Comment by KristofferC** [comment]
:sob:

**Comment by KristofferC** [comment]
This is a rough outline of the failures (number to the left is number of packages).

70: still uncategorized
58: `paramter_upper_bounds` removal (mostly seems to be from old Colors versions)
37: Changes to `llvmcall`
35: Various printing changes
32: `IRTools` broken
15: doctest failures (mostly printing changes)
12: Cassette broken
7: bounds error in compiler (https://github.com/JuliaLang/julia/issues/37182)
7: new ambiguities
5: GPU problems
5: New syntax error: https://github.com/JuliaLang/julia/issues/37228
3: People doing "bad stuff"
3: `@inferred` failures
2: `@approx` error
2: `Test.detect_ambiguities`

**Comment by timholy** [comment]
We just tagged a bunch of packages that fixed some printing-test failures on nightly.

**Comment by JeffBezanson** [comment]
Wow, this was amazingly (depressingly?) useful.

**Comment by KristofferC** [comment]
Rebased on master:

@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by maleadt** [comment]
Nanosoldier process died, let's try again:

@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-688282986) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/5401256da7d60e8b1ea5ec7c7a1a3becc543201b/pkgeval/by_hash/d97ccd7_vs_c4acbf9/report.md). cc @maleadt

**Comment by KristofferC** [comment]
Some updates: https://github.com/KristofferC/PkgEvalAnalysis/blob/master/analysis.ipynb


```
 (84, PrintingChange)
 (47, Unknown)
 (39, IRTools)
 (28, LLVMModuleIR)
 (26, TestAmbiguities)
 (17, DocTest)
 (14, GPUErrors)
 (13, Cassette)
 (13, InferenceStackOverFlow)
 (12, BadBoy)
 (9, NewAmbiguity)
 (8, BoundsErrorCompiler)
 (4, NewExceptionType)
 (2, UnexpectedPass)
 (2, DownloadError)
 (2, ApproxError)
 (2, InferredFailure)
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ARCHModels", "ASE", "AbstractGPs", "AbstractMCMC", "AbstractTrees", "AcceleratedArrays", "AccurateArithmetic", "AdversarialPrediction", "Amb", "AnyMOD", "ApproximateComputations", "ArgParse", "Augmentor", "AxisArrays", "AxisIndices", "BSON", "BSONqs", "BandedMatrices", "Baselet", "BayesianLinearRegressors", "BayesianOptimization", "BenchmarkTools", "BetaML", "BilevelJuMP", "BilevelOptimization", "BinningAnalysis", "BioAlignments", "BirkhoffDecomposition", "Blades", "BlockDiagonals", "Bonsai", "BrokenRecord", "Bukdu", "BundleMethod", "CDDLib", "CORBITS", "CQLdriver", "CUDAnative", "Cassette", "CategoricalArrays", "Cbc", "ChainRules", "ChainRulesCore", "ChainRulesTestUtils", "CheckedArithmetic", "ClearStacktrace", "ClimateMARGO", "Clp", "ClusteringGA", "ColorTypes", "Colors", "CombinedParsers", "Compat", "Compose", "ConstrainedDynamicsVis", "ConstraintSolver", "ContinuumArrays", "Contour", "ControlSystems", "Convex", "CorticalSpectralTemporalResponses", "Cthulhu", "CustomUnitRanges", "CutPruners", "DECAES", "DFTK", "DataAPI", "DataEnvelopmentAnalysis", "DataFrames", "DataKnots", "DataStructures", "DataTools", "DataTypesBasic", "DataValues", "DefaultArrays", "DevIL", "Dictionaries", "DiffEqBayes", "DiffEqCallbacks", "DiffEqGPU", "DiffEqJump", "DiffEqOperators", "DiffEqParamEstim", "DiffusionDefinition", "DimensionalData", "Discord", "DiscreteDifferentialGeometry", "DiscreteFunctions", "DiskDataProviders", "DocStringExtensions", "Documenter", "DomainSets", "DualDecomposition", "DualNumbers", "DynamicAxisWarping", "DynamicPPL", "DynamicPolynomials", "DynamicSparseArrays", "EAGO", "ECOS", "EMpht", "ElasticFDA", "ErdosExtras", "ExperimentalDesign", "ExprTools", "Fermi", "FieldMetadata", "FieldProperties", "FillArrays", "FinEtools", "FixedEffectModels", "FixedEffects", "FixedPointNumbers", "Flux", "Flux3D", "ForneyLab", "ForwardDiff", "FourierFlows", "FreeParameters", "Fri", "FunctionWrappers", "FuzzyCompletions", "GCMAES", "GFlops", "GNSSSignals", "GPUArrays", "GPUCompiler", "GalacticOptim", "GasModels", "GasPowerModels", "GenerativeModels", "GeoGreensFunctions", "GeophysicalFlows", "GitHubActions", "GraphicalModelLearning", "Gridap", "GslibIO", "HAML", "HalfIntegerArrays", "HierarchicalTemporalMemory", "HierarchicalUtils", "HomotopyContinuation", "IPMeasures", "IRTools", "IdentityRanges", "ImageInTerminal", "ImageMorphology", "ImagePhaseCongruency", "IncrementalInference", "IndependentComponentAnalysis", "IndexedTables", "InfiniteArrays", "InfiniteLinearAlgebra", "InfiniteOpt", "InfrastructureModels", "InitialValues", "InstantiateFromURL", "InterProcessCommunication", "Interpolations", "IntervalSets", "Intervals", "IonCLI", "Ipopt", "JSON3", "Jaynes", "JuMP", "Judycon", "JuliaGrid", "JuliaInterpreter", "JuliennedArrays", "Juniper", "KVectors", "Kaleido", "KernelAbstractions", "KernelFunctions", "KernelMachines", "LLVM", "LSHFunctions", "LatinSquares", "Lazy", "LazyArrays", "Libtask", "LightGraphsFlows", "LightGraphsMatching", "LightQuery", "Lilith", "LinearMapsAA", "LiveServer", "LogDensityProblems", "LogRoller", "LoopVectorization", "LowLevelParticleFilters", "LoweredCodeUtils", "MCMCChainSummaries", "MCMCChains", "MINLPTests", "MLDataPattern", "MLJBase", "MLJFlux", "MLJLinearModels", "MLJModelInterface", "MLJModels", "MLJScikitLearn", "MLJScikitLearnInterface", "MLLabelUtils", "ManifoldsBase", "MathOptInterface", "MatrixFactorizations", "MatrixProfile", "MaxMinFilters", "Measurements", "Memento", "MeshCatMechanisms", "Metadata", "MicroLogging", "Missings", "Mjolnir", "ModelingToolkit", "MomentOpt", "MonteCarloObservable", "MultiScaleArrays", "MultivariatePolynomials", "Multivectors", "MutableArithmetics", "NLopt", "NaiveGAflux", "NaiveNASflux", "NaiveNASlib", "NamedArrays", "NeuralArithmetic", "NeuroCore", "NicePipes", "OILMMs", "OMEinsum", "OPFSampler", "OffsetArrays", "OpSel", "Optim", "OptimKit", "OptimalTransport", "OrderedCollections", "Oscar", "POMDPModelTools", "PaddedMatrices", "PaddedViews", "ParallelUtilities", "ParameterHandling", "ParameterJuMP", "PassiveTracerFlows", "PencilFFTs", "PhaseSpaceIO", "PhysicsInformedML", "Pickle", "PiecewiseLinearOpt", "Pluto", "PolyChaos", "PolyJuMP", "PolyhedralRelaxations", "Polynomials", "PotentialFlow", "PowerDynamics", "PowerModelsACDC", "PowerModelsDistribution", "PowerModelsSecurityConstrained", "PowerSimulations", "PowerWaterModels", "PrettyPrint", "ProgressBars", "ProxSDP", "ProximalBase", "ProximalOperators", "PushVectors", "QBase", "QHull", "QML", "QuadraticToBinary", "Quadrature", "QuantReg", "Quante", "QuasiArrays", "QuasiNewtonMethods", "RBNF", "RHEOS", "RLEVectors", "RandomBasedArrays", "RayTracer", "ReactionMechanismSimulator", "Reactive", "ReadWriteDlm2", "Rectangle", "RecursiveArrayTools", "RecursiveFactorization", "ReferenceTests", "ReinforcementLearning", "ReinforcementLearningCore", "RestrictedBoltzmannMachines", "ResumableFunctions", "Revise", "Rocket", "Rotations", "SCS", "SDDP", "SDPA", "SIMDPirates", "SLEEFPirates", "Sched", "Scrypt", "Seleroute", "SemialgebraicSets", "SentinelArrays", "SetProg", "SimJulia", "SimpleMock", "SimplePosetAlgorithms", "SingularIntegralEquations", "SkipLists", "SliceMap", "SlidingDistancesBase", "SnakeIterator", "SnoopCompile", "SolidStateDetectors", "SparseDiffTools", "SparseGaussianProcesses", "SparsityDetection", "SpatialJackknife", "SphericalHarmonicArrays", "SphericalHarmonicModes", "StatProfilerHTML", "StaticLint", "StaticNumbers", "StaticRanges", "StochDynamicProgramming", "StochasticPrograms", "StructArrays", "StructJuMP", "Sudoku", "SumOfSquares", "SwapStreams", "SymArrays", "SymbolServer", "SymbolicUtils", "TaylorModels", "TensorCast", "TensorCore", "TerminalLoggers", "ThreadPools", "TimeSeries", "Traceur", "Tracker", "Tracking", "TrajectoryOptimization", "Transformers", "TravelingSalesmanExact", "Tricks", "TropicalYao", "Tulip", "Tullio", "TypedCodeUtils", "UnbalancedOptimalTransport", "Unitful", "UnsteadyFlowSolvers", "VIDA", "VectorizationBase", "VectorizedRNG", "VideoIO", "VoronoiFVM", "WaterModels", "Wilkinson", "XPORTA", "YOLO", "YaoLang", "YaoSym", "Yota", "Zeros", "ZipFile", "ZygoteStructArrays", "sparseQFCA", "vOptGeneric"], vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-690057043) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/8fb0c0d77fc424797415d4a0bfcd86c8d62b4fc5/pkgeval/by_hash/2fb82a3_vs_c4acbf9/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-724543324) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/c3bb6df_vs_788b2c7/report.md). cc @maleadt

**Comment by maleadt** [comment]
This one might be interesting too:

@nanosoldier `runtests(ALL, vs = ":release-1.5", buildflags=["USE_BINARYBUILDER_LLVM=0", "LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by KristofferC** [comment]
CSV + some other packages should be fixed now.

@nanosoldier `runtests(ALL, vs = ":release-1.5", buildflags=["USE_BINARYBUILDER_LLVM=0", "LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-728757861) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/c3bb6df_vs_599ecd8/report.md). cc @maleadt

**Comment by KristofferC** [comment]
Checking if master is in an ok shape to branch.

@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-739911617):
```
NanosoldierError: failed to run tests: Build for julia on x86_64-linux-gnu did not complete successfully

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/60dfeda_vs_599ecd8/report.md)
cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-740507219) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/6bc3e2e_vs_599ecd8/report.md). cc @maleadt

**Comment by maleadt** [comment]
Let's see if some of these segfault are due to a failed assertion:

@nanosoldier `runtests(ALL, vs = ":release-1.5", buildflags=["USE_BINARYBUILDER_LLVM=0", "LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37214#issuecomment-740758200) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/6bc3e2e_vs_599ecd8/report.md). cc @maleadt

**Pull request closed without merging**
