### PR TITLE
Revert "Use libblastrampoline to forward to a user-defined BLAS at runtime"

### PR DESCRIPTION
**Pull request by vtjnash**
Reverts JuliaLang/julia#39455

This seems to have broken one or more packages (as well as missing some checksums?)

### CODE REVIEW

**Comment by DilumAluthge** [comment]
😢 

Hopefully we can re-add the functionality in time for 1.7.

**Review by DilumAluthge — APPROVED** [review]

**Comment by KristofferC** [comment]
What packages? Why are they broken? From what I see, the packages where accessing internals so the package should be fixed.

**Comment by ViralBShah** [comment]
Don't the checksums get auto-computed. It is easier to add the missing checksums than revert this whole PR. It would be good to understand which packages have been affected. @KristofferC helped do a pretty complete audit - but it is possible something has been missed. My understanding is that it is only a handful of packages that are accessing internal APIs and they will be updated in the 1.7 cycle.

**Comment by simeonschaub** [comment]
It looks like the failures were mainly due to NNlib, which ccalls `libblas` directly.

**Comment by ViralBShah** [comment]
We'll get NNLib fixed. You have to get the changes into Julia master early on in a release cycle and then work through the ecosystem. In fact much of Yggdrasil needs to be updated to link against LBT in any case (but obviously most things won't break since they are just directly linking to openblas).

**Comment by ViralBShah** [comment]
I see what happened. After the pkgeval audit, we ended up removing the internal `BLAS.libblas` name and calling it `BLAS.libblastrampoline`.

@staticfloat

**Comment by ViralBShah** [comment]
Fixes coming in https://github.com/JuliaLang/julia/pull/39845

Can always reopen this if necessary.

**Pull request closed without merging**
