### PR TITLE
Fix duplicated ldiv! method in qr.jl

### PR DESCRIPTION
**Pull request by Keno**
Introduced in #38389

### CODE REVIEW

**Comment by dkarrasch** [comment]
Wait, why? One is for `QR`, the other for `QRPivoted`. What am I missing?

**Comment by Keno** [comment]
See the method just above it.

**Comment by dkarrasch** [comment]
🤦 above... below... it all depends. 😂

**Comment by Keno** [comment]
github's diff view can be misleading that way, because the method above is cut off.

**Pull request merged**
