### PR TITLE
Allow specifying skip tests in command line

### PR DESCRIPTION
**Pull request by yuyichao**
Allow using `--skip` option in the command line to skip the tests after it.
e.g. (ok I know this example is stupid..)

``` julia
yuyichao% julia -f test/runtests.jl dict socket parallel --skip parallel dict
     * socket               in   1.91 seconds
    SUCCESS
```

Original post;

Allow using `-` prefix in the command line to skip certain tests.
e.g. (ok I know this example is stupid..)

``` julia
% julia -f test/runtests.jl socket parallel -parallel
     * socket               in   1.75 seconds
    SUCCESS
```

I am aware that `-` is usually not used like this in command line but I think this doesn't matter that much for an (almost) developer only test runner...

### CODE REVIEW

**Comment by tkelman** [comment]
Neat.

**Comment by hayd** [comment]
Is there any reason not to use `!` (or `^`)?

**Comment by yuyichao** [comment]
@hayd I didn't thought about using them but they are specially characters for shell and requires quoting in the command line.

**Comment by pao** [comment]
cf Mozilla's approach to a similar problem (though intended to be used for remote test builds rather than local ones) https://wiki.mozilla.org/Build:TryChooser

**Comment by ScottPJones** [comment]
The problem with `-` is that it makes it look like an option...

**Comment by yuyichao** [comment]
> The problem with - is that it makes it look like an option...

As I said in the original post

> I am aware that - is usually not used like this in command line but I think this doesn't matter that much for an (almost) developer only test runner...

**Comment by jakebolewski** [comment]
@yuyichao why not make it an actual command line option to the runtests.jl script then?  Coming up with your own syntax / convention here is a bit strange.

```julia

julia -f test/runtests all --skip parallel 

```

**Comment by yuyichao** [comment]
> @yuyichao why not make it an actual command line option to the runtests.jl script then? Coming up with your own syntax / convention here is a bit strange.

I just want to keep it simple (lazy..) and I think `runtests` is not sth that important (and we can break at any time).

I guess making everything after `--skip` to be the skipped tests is actually not harder to implement so I can definitely do that. (I just want to avoid having a very long command line if I want to skip some tests)

**Comment by yuyichao** [comment]
Updated.

**Comment by ScottPJones** [comment]
:+1: to having this as `--skip`, would be nice to get this in.

**Pull request merged**
