### PR TITLE
Timer: handle timeout correctly

### PR DESCRIPTION
**Pull request by vtjnash**
I am not sure why we ever used round+1 instead of ceil+1, as this is
strictly more correct.

### CODE REVIEW

**Comment by IanButterworth** [comment]
Could `Timer` support a `reset(::Timer)` method?

That way one could do something like this to avoid time creep

```
Timer(0) do t
    foo()
    Dates.second(Dates.now()) % 5 == 0 && reset(t)
end
```

**Comment by IanButterworth** [comment]
Could `Timer` support a `reset(::Timer)` method?

That way interval creep could be addressed by something like
```
Timer(0; interval = 5) do t
    foo()
    Dates.second(Dates.now()) % 5 != 0 && reset(t)
end
```

**Comment by vtjnash** [comment]
What does reset do?

**Comment by IanButterworth** [comment]
Reset the timing as if the timer had just been recreated.

**Comment by IanButterworth** [comment]
It could error if the timer is closed

**Pull request merged**
