### PR TITLE
Naive fix for pretty-printing of compact broadcast expressions

### LINKED ISSUE #17289: Display of compact broadcast expressions
Ref. #17302, impacts all deprecation warnings in that PR.
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+5164 (2016-07-05 20:52 UTC)
 _/ |\__'_|_|_|\__'_|  |  vectobroad/1476b79* (fork: 3393 commits, 205 days)
|__/                   |  x86_64-apple-darwin15.5.0

julia> show(:(sin.(A)))
:(sin.((A,)))
```

### PR DESCRIPTION
**Pull request by Sacha0**
Fixes #17289. Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
[AV i686 failure](https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4387/job/jr51w1fjet0rqns5#L1684) seems unrelated? ('unhandled task failure' in test/parallel.)

**Comment by vtjnash** [comment]
yes, that's a known issue. This lgtm, just needs someone to resolve the merge conflict.

**Comment by Sacha0** [comment]
> just needs someone to resolve the merge conflict.

Should be resolved. Thanks!

**Comment by Sacha0** [comment]
Thanks for the reviews and merge!

**Pull request merged**
