### PR TITLE
Fix indexing triangular matrices with `undef` elements in the parent

### PR DESCRIPTION
**Pull request by jishnub**
I'm not totally sure about specializing`getindex` for numeric arrays, but this lets us display a triangular matrix where the parent is not initialized.
```julia
julia> M = Matrix{BigFloat}(undef, 4, 4)
4×4 Matrix{BigFloat}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

julia> UpperTriangular(M)
4×4 UpperTriangular{BigFloat, Matrix{BigFloat}}:
 #undef  #undef  #undef  #undef
    ⋅    #undef  #undef  #undef
    ⋅       ⋅    #undef  #undef
    ⋅       ⋅       ⋅    #undef
```

### CODE REVIEW

**Comment by mikmoore** [comment]
See concern at [comment on #52528](https://github.com/JuliaLang/julia/pull/52528#issuecomment-1856808752).

**Comment by jishnub** [comment]
Similar to https://github.com/JuliaLang/julia/pull/52528#issuecomment-1876594022, is it reasonable to add a `haszero` trait, and use to decide if we should return `zero(T)` or `zero(data[i,j])`? The former would only be chosen for concrete number types, which should resolve the issue raised above.

**Comment by jishnub** [comment]
@mikmoore In line with #52528, I think this PR should also be fine?

**Comment by mikmoore** [comment]
> @mikmoore In line with #52528, I think this PR should also be fine?

I think so, yes.

**Pull request merged**
