### PR TITLE
Fix runtests for RemoteException capturing a UndefVarError case.

### LINKED ISSUE #20027: Parallel tests exit with wrong status
Over at least the last few weeks, when tests get run in parallel (as on CI) and there's a failure, the overall execution isn't exiting with a nonzero status like it should be. This has been hiding several issues. For example,
```
~/Julia/julia-0.6$ git checkout -q e9380c00d1d
~/Julia/julia-0.6$ make && for cores in 2 1; do JULIA_CPU_CORES=$cores usr/bin/julia test/runtests.jl abstractarray int; done
Test (Worker)     | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
int (3)           |    4.92  |  0.33  |  6.8 | 56.74      | 213.37
Worker 1 failed running test abstractarray:
UndefVarError: TestMain_abstractarray not defined
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::Type{Module}) at ./serialize.jl:604
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:583
 in deserialize(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:543
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:837
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:903
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:850
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:903
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:850
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize_array(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:720
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:571
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:903
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:850
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:903
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:850
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:903
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:850
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:573
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}, ::Type{Base.ResultMsg}) at ./multi.jl:120
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}) at ./multi.jl:130
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1371
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1328
 in (::Base.##500#501{TCPSocket,TCPSocket,Bool})() at ./event.jl:71
Test Summary: |  Pass  Total
  Overall     | 10017  10017
    SUCCESS
Test (Worker)     | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 2×12 TestMain_abstractarray.T24Linear{Int64,2,(2,12)} at index [Base.LogicalIndex(Bool[true,true,false,false,false,false,false,true,true,true,true,true,false,true,true,false,false,false,true,false,true,true,true,true])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.T24Linear{Int64,2,(2,12)}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.T24Linear{Int64,2,(2,12)}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.T24Linear}, ::Tuple{Int64,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 2×3×4 TestMain_abstractarray.T24Linear{Int64,3,(2,3,4)} at index [Base.LogicalIndex(Bool[false,false,false,false,false,true,true,false,true,true,false,true,false,false,true,true,false,false,false,false,true,true,false,false])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.T24Linear{Int64,3,(2,3,4)}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.T24Linear{Int64,3,(2,3,4)}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.T24Linear}, ::Tuple{Int64,Int64,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 1×2×3×4 TestMain_abstractarray.T24Linear{Int64,4,(1,2,3,4)} at index [Base.LogicalIndex(Bool[true,false,false,true,false,true,false,false,false,true,false,true,false,false,true,true,true,true,true,true,true,false,true,true])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.T24Linear{Int64,4,(1,2,3,4)}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.T24Linear{Int64,4,(1,2,3,4)}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.T24Linear}, ::NTuple{4,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 4×3×2×1 TestMain_abstractarray.T24Linear{Int64,4,(4,3,2,1)} at index [Base.LogicalIndex(Bool[true,false,false,false,true,true,false,false,true,true,false,false,false,true,true,false,false,false,true,true,true,true,true,false])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.T24Linear{Int64,4,(4,3,2,1)}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.T24Linear{Int64,4,(4,3,2,1)}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.T24Linear}, ::NTuple{4,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 2×12 TestMain_abstractarray.TSlow{Int64,2} at index [Base.LogicalIndex(Bool[true,true,false,false,false,false,false,true,false,true,false,false,true,true,false,false,true,false,true,false,true,false,true,false])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.TSlow{Int64,2}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.TSlow{Int64,2}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.TSlow}, ::Tuple{Int64,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 2×3×4 TestMain_abstractarray.TSlow{Int64,3} at index [Base.LogicalIndex(Bool[true,false,true,true,true,false,false,true,true,false,false,false,false,true,false,true,false,true,false,true,true,true,true,true])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.TSlow{Int64,3}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.TSlow{Int64,3}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.TSlow}, ::Tuple{Int64,Int64,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 1×2×3×4 TestMain_abstractarray.TSlow{Int64,4} at index [Base.LogicalIndex(Bool[false,true,false,true,true,true,true,true,true,false,false,true,true,true,false,false,false,true,false,false,true,true,true,true])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.TSlow{Int64,4}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.TSlow{Int64,4}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.TSlow}, ::NTuple{4,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
  BoundsError: attempt to access 4×3×2×1 TestMain_abstractarray.TSlow{Int64,4} at index [Base.LogicalIndex(Bool[false,false,true,false,false,false,false,true,true,true,true,false,true,false,true,true,false,false,false,true,false,false,true,false])]
  Stacktrace:
   [1] throw_boundserror(::TestMain_abstractarray.TSlow{Int64,4}, ::Tuple{Base.LogicalIndex{Int64,BitArray{1}}}) at ./abstractarray.jl:365
   [2] checkbounds at ./abstractarray.jl:322 [inlined]
   [3] macro expansion at ./multidimensional.jl:369 [inlined]
   [4] _getindex at ./multidimensional.jl:366 [inlined]
   [5] getindex(::TestMain_abstractarray.TSlow{Int64,4}, ::BitArray{1}) at ./abstractarray.jl:793
   [6] test_vector_indexing(::Type{TestMain_abstractarray.TSlow}, ::NTuple{4,Int64}, ::Type{TestMain_abstractarray.TestAbstractArray}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:378
   [7] macro expansion; at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:701 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:532
   [10] include(::String) at ./sysimg.jl:14
   [11] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:13 [inlined]
   [12] macro expansion; at ./test.jl:842 [inlined]
   [13] macro expansion; at ./util.jl:288 [inlined]
   [14] macro expansion; at /home/tkelman/Julia/julia-0.6/test/testdefs.jl:0 [inlined]
   [15] anonymous at ./<missing>:?
int (1)           |    2.51  |  0.02  |  0.7 | 50.27      | 321.00
Worker 1 failed running test abstractarray:
Some tests did not pass: 2776 passed, 0 failed, 8 errored, 0 broken.abstractarray: Error During Test
  Test threw an exception of type BoundsError
  Expression: $(Expr(:escape, :(B[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(A[vec(mask)]))) $(Expr(:escape, :(==))) $(Expr(:escape, :(find(mask))))
ERROR: LoadError: MethodError: no method matching size(::TestMain_abstractarray.T24Linear{Int64,2,(2,12)})
The applicable method may be too new: running in world age 20887, while current world is 20976.
Closest candidates are:
  size{T,N,dims}(::TestMain_abstractarray.T24Linear{T,N,dims}) at /home/tkelman/Julia/julia-0.6/test/abstractarray.jl:190 (method too new to be called from this world context.)
  size{T,N}(::AbstractArray{T,N}, !Matched::Any) at abstractarray.jl:22
  size{N}(::Any, !Matched::Integer, !Matched::Integer, !Matched::Integer...) at abstractarray.jl:23
  ...
Stacktrace:
 [1] summary(::TestMain_abstractarray.T24Linear{Int64,2,(2,12)}) at ./show.jl:1533
 [2] showerror(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::BoundsError) at ./replutil.jl:163
 [3] (::Base.##755#756{BoundsError})(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}) at ./replutil.jl:198
 [4] #with_output_color#793(::Bool, ::Function, ::Function, ::Symbol, ::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./util.jl:310
 [5] with_output_color(::Function, ::Symbol, ::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./util.jl:307
 [6] #showerror#754(::Bool, ::Function, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::BoundsError, ::Array{Ptr{Void},1}) at ./replutil.jl:197
 [7] showerror(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::BoundsError, ::Array{Ptr{Void},1}) at ./replutil.jl:196
 [8] #sprint#208(::Void, ::Function, ::Int64, ::Function, ::BoundsError, ::Vararg{Any,N}) at ./strings/io.jl:55
 [9] show(::Base.TTY, ::Base.Test.Error) at ./test.jl:138
 [10] print(::Base.TTY, ::Base.Test.Error) at ./strings/io.jl:18
 [11] record(::Base.Test.DefaultTestSet, ::Base.Test.Error) at ./test.jl:558
 [12] (::##33#41)() at /home/tkelman/Julia/julia-0.6/test/runtests.jl:170
 [13] cd(::##33#41, ::String) at ./file.jl:69
 [14] include_from_node1(::String) at ./loading.jl:532
 [15] include(::String) at ./sysimg.jl:14
 [16] process_options(::Base.JLOptions) at ./client.jl:308
 [17] _start() at ./client.jl:374
while loading /home/tkelman/Julia/julia-0.6/test/runtests.jl, in expression starting on line 38
```

The abstractarray failure here isn't the important part (it was fixed by https://github.com/JuliaLang/julia/pull/20018), this issue is about that fact that tests "passed" with the failure present.

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes #20027

Deserialization errors due to a remote UndefVarError were not being recorded.

### CODE REVIEW

**Comment by tkelman** [comment]
Great, applying this patch on top of e9380c00d1d does fix the worst part of the issue, and parallel tests fail consistently as they would if you run the tests in serial. But the UndefVarError and the deserialization backtrace is useless for identifying what actually caused the failure...

**Comment by tkelman** [comment]
Looks like that's a really old issue actually - if a test throws something like a `BoundsError` that has a custom array type in one of its fields, and that array type isn't defined on node 1, then you get an UndefVarError when node 1 tries to display anything useful about the error. 561db3bfde made the backtrace when that happens much messier, with a few dozen lines in deserialize.

**Comment by amitmurthy** [comment]
> then you get an UndefVarError when node 1 tries to display anything useful about the error

I think this would probably happen at deserialize time on node 1 itself. And it would end up hiding the original error.

**Comment by tkelman** [comment]
Right, I think that's what's been happening here. This patch fixes the incorrect exist status and tests showing green when they shouldn't be, but it doesn't fix the actual test failure error getting hidden by a bunch of confusing deserialization backtraces. Will be hard to debug if intermittent problems do this, but it's also not a recent regression (vs the exit status mistake which was).

**Comment by amitmurthy** [comment]
I think that is a more involved fix. Offhand I have no idea how to tackle it. Should track it in a separate issue.

FWIW:
```
julia> remotecall_fetch(()->eval(quote
         type Foo <: Exception
           x
         end
         throw(Foo(1))
       end), 2)
ERROR: UndefVarError: Foo not defined
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:841
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:909
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:856
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize(::Base.ClusterSerializer{TCPSocket}, ::DataType) at ./serialize.jl:909
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:856
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}, ::Type{Base.ResultMsg}) at ./multi.jl:120
 in deserialize_msg(::Base.ClusterSerializer{TCPSocket}) at ./multi.jl:130
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1371
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:1328
 in (::Base.##505#506{TCPSocket,TCPSocket,Bool})() at ./event.jl:73
Stacktrace:
 [1] #remotecall_fetch#493(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1093
 [2] remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1085
 [3] #remotecall_fetch#496(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./multi.jl:1106
 [4] remotecall_fetch(::Function, ::Int64) at ./multi.jl:1106
```

**Comment by amitmurthy** [comment]
Should probably treat deserialization of `Exception` objects differently. If we get any any errors during deserialization, it should be captured along with the type of the container and rethrown.

**Comment by KristofferC** [comment]
Could you point out where that stacktrace is being printed. It should probably be "updated" to the new version (similar to the last being printed).

**Comment by amitmurthy** [comment]
As a workaround for the testsystem, we can print any exceptions captured in a testset to STDERR on the workers (and not on 1) so that relevant information is not lost.

**Comment by amitmurthy** [comment]
> Could you point out where that stacktrace is being printed. It should probably be "updated" to the new version (similar to the last being printed).

I assume the question was in the context of the example above.

Captured as a RemoteException here - https://github.com/JuliaLang/julia/blob/711941988565debc661d8fd9022bf52689749ced/base/multi.jl#L1388

And thrown here - https://github.com/JuliaLang/julia/blob/711941988565debc661d8fd9022bf52689749ced/base/multi.jl#L1093

Don't quite follow what you mean by "updated to the new version"

**Comment by KristofferC** [comment]
The stacktraces on 0.6 are a bit changed (you can see it in the very end of the code you quoted a few posts up):

```
Stacktrace:
 [1] #remotecall_fetch#493(::Array{Any,1}, ::Function, ::Function, ::Base.Worker) at ./multi.jl:1093
 [2] remotecall_fetch(::Function, ::Base.Worker) at ./multi.jl:1085
...
```

 However, the stacktrace above that one uses the "old" way of printing backtraces:

```
 in deserialize_datatype(::Base.ClusterSerializer{TCPSocket}) at ./serialize.jl:841
 in handle_deserialize(::Base.ClusterSerializer{TCPSocket}, ::Int32) at ./serialize.jl:580
....
```
 so there is apparently something about the new stacktraces that are not properly hooked in for remote exceptions.

**Comment by amitmurthy** [comment]
https://github.com/JuliaLang/julia/blob/711941988565debc661d8fd9022bf52689749ced/base/multi.jl#L1016-L1019

and 

https://github.com/JuliaLang/julia/blob/711941988565debc661d8fd9022bf52689749ced/base/task.jl#L23

**Review by kshyatt — APPROVED** [review]

**Pull request merged**
