### PR TITLE
remove Woodbury special matrix type

### PR DESCRIPTION
**Pull request by jakebolewski**
This is not used anywhere in the `Linalg` module or in `Base` and the number of methods it supports a fairly limited compared to the other special matrix types.  Now would be a good time to extract it out into an external package.  See JuliaLang/LinearAlgebra.jl#33

cc @timholy, @jiahao

### CODE REVIEW

**Comment by timholy** [comment]
Seems reasonable to me.

**Comment by jakebolewski** [comment]
Where would you like it to go?  I can submit a PR.

**Comment by jiahao** [comment]
I think @andreasnoack's `LinearAlgebra.jl` would be a good home for the Woodbury code.

**Comment by ViralBShah** [comment]
+1 I have been wanting to do this for a while.

**Comment by timholy** [comment]
https://github.com/timholy/WoodburyMatrices.jl

**Comment by timholy** [comment]
I can move it to LinearAlgebra.jl if you want. I just wanted to rescue it before it disappeared.

**Comment by jakebolewski** [comment]
With git nothing disappears :-)

**Comment by timholy** [comment]
Yes, but the number of keystrokes increases :-).

**Comment by andreasnoack** [comment]
I'd be happy to host it in `LinearAlgebra.jl`, but my package is not ready for publication yet so in the meantime it is probably good to have in a separate package. Then we can consolidate later.

**Comment by jiahao** [comment]
I'll let @andreasnoack comment first, but the idea for `LinearAlgebra.jl` was to house experimental and more esoteric linear algebra functionality that didn't really belong to `Base`.

**Comment by timholy** [comment]
Just create an issue over at WoodburyMatrices when you want me to do something.

**Pull request merged**
