### PR TITLE
optimizer: inline inlineable `GlobalRef`

### PR DESCRIPTION
**Pull request by aviatesk**
This should let us generate a smaller IR in general, as well as reducing chances that the semi-concrete interpretation causes the precision issue that is caused by the current limitation that a compressed IR can't keep propagate a constant type information in statement position to the
semi-concrete interpretation (xref: #47349).

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47729#issuecomment-1329380620) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ca3e8b6_vs_902e8a7/report.md).

**Comment by fingolfin** [comment]
"can't keep propagate a" ? Grammar/typo?

**Comment by vtjnash** [comment]
Why does it make a smaller IR to inline more bigger things into it?

**Pull request closed without merging**
