### PR TITLE
Fix constructor for RecursiveSpinLock

### PR DESCRIPTION
**Pull request by yuyichao**
Add and clean up tests for locks.

### CODE REVIEW

**Comment by yuyichao** [comment]
@kpamnany

**Comment by yuyichao** [comment]
Also add `jl_cpu_pause` to the wait loop in spin locks.

**Comment by yuyichao** [comment]
And make spinlocks immutable.

**Comment by kpamnany** [comment]
Looks fine to me.

But, now that I think about it, shouldn't a properly recursive spinlock count the number of recursive lock calls and only unlock when the same number of unlock calls have been made?

**Comment by yuyichao** [comment]
I think you are right. That's what we do for the C version. I'll see if I can fix it and add tests....

**Comment by yuyichao** [comment]
Done.

**Comment by kpamnany** [comment]
If the tests are passing, this looks fine.

**Comment by yuyichao** [comment]
Travis Lin32

```
	From worker 2:	  Expression: threaded_add_locked(Threads.RecursiveSpinLock,0,10000) == 10000
	From worker 2:	   Evaluated: 0 == 10000
```

Hmm, this is strange.

**Comment by yuyichao** [comment]
Looks like `atomic_cas!` is not tested and `@threads` silently swallows errors. I suspect it is not correctly implemented/supported on LLVM 3.3 ....

**Comment by yuyichao** [comment]
The return value of `cmpxchg` changes between [LLVM 3.4](http://llvm.org/releases/3.3/docs/LangRef.html#cmpxchg-instruction) and [LLVM 3.5](http://llvm.org/releases/3.5.0/docs/LangRef.html#cmpxchg-instruction). Will try to fix...

**Comment by yuyichao** [comment]
Done... hopefully it's good this time........................................................

**Comment by yuyichao** [comment]
Tests passed locally with LLVM 3.3 and LLVM 3.7.

**Comment by kpamnany** [comment]
Good find on cmpxchg.

I have a solution for ``@threads`` swallowing errors; waiting on https://github.com/JuliaLang/julia/pull/14060 before opening the PR.

**Comment by yuyichao** [comment]
> I have a solution for `@threads` swallowing errors

Cool. I guess that's an independent issue. =)

**Comment by yuyichao** [comment]
@kpamnany Are you going to merge #14060 soon? This PR will conflict with it in the test.

**Comment by kpamnany** [comment]
Jeff just merged it. The test merge should be really easy though.

**Comment by yuyichao** [comment]
Yep. Doing that and testing it locally now.

**Pull request merged**
