### PR TITLE
Test some libgit2 warnings

### PR DESCRIPTION
**Pull request by kshyatt**
Re #21560.

### CODE REVIEW

**Review by tkelman — APPROVED** [review]
yay thank you, that works locally

there are also the `readuntil(IO,AbstractString) will perform poorly` ones but I think @omus added those

**Comment by kshyatt** [comment]
Glad it works, when I get back I can take a look at the readstring ones if
no one else has.

**Review by ararslan — APPROVED** [review]

**Comment by omus** [comment]
> there are also the readuntil(IO,AbstractString) will perform poorly ones but I think @omus added those

Was definitely me. Will eventually be resolved by #20621

**Comment by tkelman** [comment]
Right, but if that's post-0.6 material, will it be possible to do something quick with test_warn so these tests are quieter for the lifetime of the release-0.6 branch?

**Comment by omus** [comment]
The warning is coming from https://github.com/JuliaLang/julia/blob/master/test/TestHelpers.jl#L95. We could either silence the warning by redirecting STDERR at this point or adding a keyword into `readuntil` which stops the warning from being reported. I don't think we can use `@test_warn` as I'm unsure how it would handle multiple warnings from the same function call

**Comment by kshyatt** [comment]
Is the AV failure real? Can we merge?

**Comment by tkelman** [comment]
it's #16555

**Pull request merged**
