### PR TITLE
xref `UnionAll` in the doc string of `where`

### PR DESCRIPTION
**Pull request by nsajko**

### CODE REVIEW

**Comment by nsajko** [comment]
Apart from cross-referencing `UnionAll`, the goal here is to prevent confusion with `Union`, which often happens to newcomers due to the "iterated **union**" phrasing.

**Comment by nsajko** [comment]
ping

**Comment by nsajko** [comment]
bump

**Review by oscardssmith — APPROVED** [review]

**Comment by nsajko** [comment]
merge?

**Pull request merged**
