### PR TITLE
add specific Adjoint{StridedMatrix} * SparseVector method

### LINKED ISSUE #32402: Slow matrix vector product (adjoint dense * SparseCSC)
When multiplying Dense matrices by sparse vectors the speed seems to degrade too much if the dense matrix is an adjoint.

```julia
percent_nonzeros =  0.01
W = rand(15000, 2);
x_sp = sprand(15000, percent_nonzeros);
Wt = copy(W') 

@btime W'*x_sp
  285.560 μs (6 allocations: 304 bytes)

@btime Wt*x_sp
  522.068 ns (1 allocation: 96 bytes)
```

This seems to be related with #32195 but this is not matrix-matrix multiply. This is matrix-vector multiply

### PR DESCRIPTION
**Pull request by dkarrasch**
Closes #32402.

A quick adoption of the existing Transpose method, plus some minor code simplification/consistency.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Test failure on windows is in `download`.

**Comment by ViralBShah** [comment]
Do we have adequate test coverage of these cases?

**Comment by dkarrasch** [comment]
> Do we have adequate test coverage of these cases?

What do you mean? We had tests for denseMat*sparseVec and transposeDenseMat * sparseVec. I added tests to cover `Adjoint`s and added `Complex` eltypes where `Transpose` and `Adjoint` make a difference.

**Comment by ViralBShah** [comment]
Looks good to me.

**Comment by dkarrasch** [comment]
If anything, then I see the "issue" of code duplication. I see that we usually don't make much effort in code reduction in the area of matrix multiplication, because of the risk of method ambiguity. But I guess if code reduction is desired this could be another PR.

Just to give an example, the 3-arg `mul!` simply forwards its arguments to the 5-arg `mul!` by appending `one` and `zero`. Currently, we have 3 individual methods for that, for `StridedMatrix`, `Adjoint` and `Transpose`. Other reductions include the trick we sometimes use in tests, for-loop over `transform in (adjoint, transpose)` and then `@eval` and the function definition etc.

**Comment by ViralBShah** [comment]
I would be happy to do code reduction separately and get performance improvements in for now.

**Pull request merged**
