### PR TITLE
More consistent return value for annotations, take 2

### PR DESCRIPTION
**Pull request by tecosaur**
The PR #53281 was reverted due to issues it caused in CI that could not be quickly spotted. I think I may have identified the cause, and hope to use CI here to see whether this is the case or not.

### CODE REVIEW

**Comment by vtjnash** [comment]
I looked up the error you are getting in the logs, and it turns out to be https://github.com/JuliaLang/julia/issues/53147

```
     Testing Running tests...
julia: /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:2273: jl_root_new_gvars: Assertion `codeinst && (__extension__ ({ __auto_type __atomic_load_ptr = (&codeinst->specsigflags); __typeof__ (*__atomic_load_ptr) __atomic_load_tmp; __atomic_load (__atomic_load_ptr, &__atomic_load_tmp, (memory_order_relaxed)); __atomic_load_tmp; }) & 0b01) && __extension__ ({ __auto_type __atomic_load_ptr = (&codeinst->specptr.fptr); __typeof__ (*__atomic_load_ptr) __atomic_load_tmp; __atomic_load (__atomic_load_ptr, &__atomic_load_tmp, (memory_order_relaxed)); __atomic_load_tmp; })' failed.

[2609] signal 6 (-6): Aborted
in expression starting at /tmp/jl_IF6A9B/packages/Example/aqsx3/test/runtests.jl:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fe54044040e)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
jl_root_new_gvars at /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:2273 [inlined]
jl_restore_system_image_from_stream_ at /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:3494
jl_restore_package_image_from_stream at /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:3632
jl_restore_incremental_from_buf at /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:3687
ijl_restore_package_image_from_file at /cache/build/builder-amdci4-3/julialang/julia-master/src/staticdata.c:3775
_include_from_serialized at ./loading.jl:1128
_include_from_serialized at ./loading.jl:1103 [inlined]
#_require_search_from_serialized#1063 at ./loading.jl:1690
_require_search_from_serialized at ./loading.jl:1645
jfptr__require_search_from_serialized_41098.1 at /cache/build/tester-amdci5-9/julialang/julia-master/julia-f855c1d903/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
_require at ./loading.jl:2118
__require_prelocked at ./loading.jl:1987
jfptr___require_prelocked_64844.1 at /cache/build/tester-amdci5-9/julialang/julia-master/julia-f855c1d903/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
jl_apply at /cache/build/builder-amdci4-3/julialang/julia-master/src/julia.h:2165 [inlined]
jl_f__call_in_world at /cache/build/builder-amdci4-3/julialang/julia-master/src/builtins.c:894
#invoke_in_world#3 at ./essentials.jl:1064 [inlined]
invoke_in_world at ./essentials.jl:1061 [inlined]
_require_prelocked at ./loading.jl:1978
macro expansion at ./loading.jl:1916 [inlined]
macro expansion at ./lock.jl:273 [inlined]
__require at ./loading.jl:1873
jfptr___require_64781.1 at /cache/build/tester-amdci5-9/julialang/julia-master/julia-f855c1d903/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
jl_apply at /cache/build/builder-amdci4-3/julialang/julia-master/src/julia.h:2165 [inlined]
jl_f__call_in_world at /cache/build/builder-amdci4-3/julialang/julia-master/src/builtins.c:894
#invoke_in_world#3 at ./essentials.jl:1064 [inlined]
invoke_in_world at ./essentials.jl:1061 [inlined]
require at ./loading.jl:1866
jfptr_require_64778.1 at /cache/build/tester-amdci5-9/julialang/julia-master/julia-f855c1d903/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
jl_apply at /cache/build/builder-amdci4-3/julialang/julia-master/src/julia.h:2165 [inlined]
call_require at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:486 [inlined]
eval_import_path at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:523
jl_toplevel_eval_flex at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:759
jl_toplevel_eval_flex at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:994
eval at ./boot.jl:428 [inlined]
include_string at ./loading.jl:2260
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
_include at ./loading.jl:2320
include at ./sysimg.jl:38
unknown function (ip: 0x7fe5263ca992)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
jl_apply at /cache/build/builder-amdci4-3/julialang/julia-master/src/julia.h:2165 [inlined]
do_call at /cache/build/builder-amdci4-3/julialang/julia-master/src/interpreter.c:126
eval_value at /cache/build/builder-amdci4-3/julialang/julia-master/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-amdci4-3/julialang/julia-master/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-amdci4-3/julialang/julia-master/src/interpreter.c:657
jl_interpret_toplevel_thunk at /cache/build/builder-amdci4-3/julialang/julia-master/src/interpreter.c:815
jl_toplevel_eval_flex at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:943
jl_toplevel_eval_flex at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-amdci4-3/julialang/julia-master/src/toplevel.c:994
eval at ./boot.jl:428 [inlined]
exec_options at ./client.jl:291
_start at ./client.jl:525
jfptr__start_66507.1 at /cache/build/tester-amdci5-9/julialang/julia-master/julia-f855c1d903/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:2941 [inlined]
ijl_apply_generic at /cache/build/builder-amdci4-3/julialang/julia-master/src/gf.c:3118
jl_apply at /cache/build/builder-amdci4-3/julialang/julia-master/src/julia.h:2165 [inlined]
true_main at /cache/build/builder-amdci4-3/julialang/julia-master/src/jlapi.c:898
jl_repl_entrypoint at /cache/build/builder-amdci4-3/julialang/julia-master/src/jlapi.c:1057
main at /cache/build/builder-amdci4-3/julialang/julia-master/cli/loader_exe.c:58
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 1 (Pool: 1; Big: 0); GC: 0
```

**Comment by tecosaur** [comment]
So I'm guessing we re-visit this once #53147 has been solved?

**Comment by vtjnash** [comment]
This should be merged after #53373

**Comment by tecosaur** [comment]
The failures in CI just seem to be two things with Pkg. I'm not sure if they're unrelated to this or not though?

**Comment by KristofferC** [comment]
>   Package Example errored during testing (received signal: 6)

Seems to be the same as complained about in https://github.com/JuliaLang/julia/pull/53281#issuecomment-1938071915 but not sure how this PR would cause that.

**Pull request merged**
