### PR TITLE
simplify doc/Makefile

### PR DESCRIPTION
**Pull request by fredrikekre**
First commit removes some `doc/Makefile` targets, such that
`make doctest` becomes `make doctest=true` etc. Seems unnecessary to have a target for each option like we do now
Second commit  moves the `deploy` stage back to `after_success` on Travis.
~Third commit enables the doctests on CircleCI 64-bit, seems better to run them on two workers.~

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why does CircleCI show green when we get an error?
```
ERROR: LoadError: ArgumentError: Module Pkg not found in current path.
Run `Pkg.add("Pkg")` to install the Pkg package.
```
Also, why do I get that error? :smile:

**Comment by ararslan** [comment]
Getting this on Circle:
```
/bin/bash: line 12: pushd: project: No such file or directory
total 4
drwxr-xr-x 16 circleci circleci 4096 May 21 16:30 julia-src
make: *** doc: No such file or directory.  Stop.
/bin/bash: line 15: popd: directory stack empty
```

**Comment by ararslan** [comment]
Circle build canceled by Fredrik's request.

**Comment by KristofferC** [comment]
I think this broke the doc deployment? At least looking at https://travis-ci.org/JuliaLang/julia/jobs/392976968 the after_sucess part is not running.

**Pull request merged**
