### PR TITLE
Throw an error if trying to access unassigned data in Base.RefValue

### PR DESCRIPTION
**Pull request by vchuravy**
Right now:

```
b = Base.RefValue{Integer}()
Base.unsafe_convert(Ptr{Integer}, b)
```

Happens to return a null-pointer. This is inconsistent with the case where
`T` is a mutable object where we will throw a `UndefRef` error. 

We have run into this in Enzyme a couple of times and I think the null-pointer there is a
big footgun.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
This should check the value of `p` in the branch that followed `!=C_NULL` (for consistency with other part of the code now, we might want to make that an explicit atomic monotonic-consume-load too)

**Comment by vtjnash** [comment]
Why are you reverting aviatesk's recent PR here?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45829#issuecomment-1167419756) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/897d089_vs_a549929/report.html).

**Comment by vchuravy** [comment]
> Why are you reverting aviatesk's recent PR here?

Huh? Where did you see that?

**Comment by vtjnash** [comment]
Huh, that is odd. It was in the GitHub diff, but now is correct.

**Comment by vtjnash** [comment]
Rebase?

**Pull request merged**
