### PR TITLE
ensure proper handling of sparams for widened compile signatures

### LINKED ISSUE #47476: Regression in computing type parameter(?) on 1.9
Repro:

```julia
using QuantumLattices: FID, Coupling
Coupling(:, FID, :, :, (1, 1))
```

(PkgEval log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6b14101_vs_97ccb97/TightBindingApproximation.primary.log)

On 1.9:

```julia
julia> Coupling(:, FID, :, :, (1, 1))
ERROR: UndefVarError: `N` not defined
Stacktrace:
 [1] Coupling(::Int64, ::Colon, ::Type{FID}, ::Colon, ::Vararg{Union{Colon, Tuple{T, T} where T}})
   @ QuantumLattices.DegreesOfFreedom ~/QuantumLattices.jl/src/DegreesOfFreedom.jl:766
 [2] Coupling(::Colon, ::Type{FID}, ::Colon, ::Vararg{Union{Colon, Tuple{T, T} where T}})
   @ QuantumLattices.DegreesOfFreedom ~/QuantumLattices.jl/src/DegreesOfFreedom.jl:764
 [3] top-level scope
   @ REPL[20]:1
```

With the debugger on 1.9:

```julia
julia> using Debugger

julia> @run Coupling(:, FID, :, :, (1, 1))
∑[Index(:, FID(:, :, 1)) Index(:, FID(:, :, 1))]
```

With `--compile=no` on 1,9:

```julia
julia> Coupling(:, FID, :, :, (1, 1))
# code missing for _string_n(Int64) from _string_n(Integer) : sysimg may not have been built with --compile=all
# code missing for unsafe_convert(Type{Ptr{UInt8}}, Array{UInt8, 1}) from unsafe_convert(Type{Ptr{T}}, Array{T, N} where N) where {T} : sysimg may not have been built with --compile=all
# ∑[code missing for unsafe_convert(Type{Ptr{UInt8}}, String) from unsafe_convert(Type{Ptr{UInt8}}, String) : sysimg may not have been built with --compile=all
Index(:, FID(:, :, 1)) Index(:, FID(:, :, 1))]
```

With 1.8:

```julia
julia> Coupling(:, FID, :, :, (1, 1))
∑[Index(:, FID(:, :, 1)) Index(:, FID(:, :, 1))]
```

Since it "works" in 1.9 both with the debugger and compilation turned off I would guess this is a bug.

### PR DESCRIPTION
**Pull request by vtjnash**
Fix #47476

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runtests()`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47667#issuecomment-1329655676) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/fa52d60_vs_c8ea33d/report.md).

**Comment by vtjnash** [comment]
Interesting that ["misc", "julia", ("macroexpand", "evalpoly")] was slightly hurt and insertionsort sortperm was slightly helped by this. But fortunately no issues seem to have been detected

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47667#issuecomment-1329591566) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/371ab11_vs_7262534/report.html).

**Comment by vtjnash** [comment]
That did surprisingly badly. I will need to dig into those

**Comment by vtjnash** [comment]
Found one of the main causes. Still need to look more into `FastGaussQuadrature` which is failing to precompile with a typeintersect issue:
```
ERROR: LoadError: MethodError: Union{}(::NTuple{20, Float64}) is ambiguous.                                                     
                                                                                                                                
Candidates:                                                                                                                     
  (::Type{FA})(x::Tuple) where FA<:StaticArraysCore.FieldArray                                                                  
    @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/FieldArray.jl:2                                                     
  (::Type{T})(x::Tuple) where T<:Tuple                                                                                          
    @ Base tuple.jl:362                                                                                                         
  (::Type{SA})(x::Tuple) where SA<:Union{StaticArrays.SHermitianCompact, StaticArraysCore.MArray, StaticArraysCore.SArray, StaticArraysCore.SizedArray}
    @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/convert.jl:161                                                      
  Union{}(a...)                                                                                                                                                                                                                                                  
    @ Core boot.jl:263                                                                                                          
  (::Type{T})(itr) where T<:Tuple                                                                                               
    @ Base tuple.jl:367                                                                                                                                                                                                                                          
  (::Type{SA})(x...) where SA<:StaticArraysCore.StaticArray                                                                     
    @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/convert.jl:160                                                      
                                                                
Possible fix, define                                                                                                            
  Union{}(::Tuple)

Stacktrace:
 [1] (StaticArraysCore.SVector{20})(x::NTuple{20, Float64})
   @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/convert.jl:163
 [2] top-level scope
   @ ~/.julia/packages/FastGaussQuadrature/BRLTf/src/constants.jl:1
```
and `Hygienic` which is failing after tests with an LLVM error:
```
julia: /workspace/srcdir/llvm-project/llvm/include/llvm/ExecutionEngine/Orc/SymbolStringPool.h:157: llvm::orc::SymbolStringPool::~SymbolStringPool(): Assertion `Pool.empty() && "Dangling references at pool destruction time"' failed.                         
                                                                                                                                                                                                                                                                 
[1829272] signal (6.-6): Aborted                                                                                                                                                                                                                                 
in expression starting at none:0                                                                                                                                                                                                                                 
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)                                                                                                                                                                                                        
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)                                                                                                                                                                                                          
unknown function (ip: 0x7ff2edd5c728)                                                                                                                                                                                                                            
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)                                                                                                                                                                                                  
_ZNSt19_Sp_counted_deleterIPN4llvm3orc16SymbolStringPoolENSt12__shared_ptrIS2_LN9__gnu_cxx12_Lock_policyE2EE8_DeleterISaIS2_EEES9_LS6_2EE10_M_disposeEv at /data/vtjnash/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)                                     
_ZN4llvm3orc26SelfExecutorProcessControlD0Ev at /data/vtjnash/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)                                                                                                                                                
_ZNKSt14default_deleteIN4llvm3orc16ExecutionSessionEEclEPS2_.isra.664.part.665 at /data/vtjnash/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)                                                                                                              
_ZN4llvm3orc5LLJITD2Ev at /data/vtjnash/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)                                                                                                                                                                      
LLVMOrcDisposeLLJIT at /data/vtjnash/julia/usr/bin/../lib/libLLVM-14jl.so (unknown line)                                                                                                                                                                         
LLVMOrcDisposeLLJIT at /home/vtjnash/.julia/packages/LLVM/WjSQG/lib/13/libLLVM_h.jl:5994 [inlined]                                                                                                                                                               
dispose at /home/vtjnash/.julia/packages/LLVM/WjSQG/src/executionengine/lljit.jl:43 [inlined]                                                                                                                                                                    
dispose at /home/vtjnash/.julia/packages/Enzyme/7ekWs/src/compiler/orcv2.jl:18                                                                                                                                                                                   
#2 at /home/vtjnash/.julia/packages/Enzyme/7ekWs/src/compiler/orcv2.jl:109                                                                                                                                                                                       
unknown function (ip: 0x7ff2b98875df)                                                                                                                                                                                                                            
_jl_invoke at /data/vtjnash/julia/src/gf.c:2627 [inlined]                                                                                                                                                                                                        
ijl_apply_generic at /data/vtjnash/julia/src/gf.c:2828                                                                                                                                                                                                           
_atexit at ./initdefs.jl:383                                                                                                                                                                                                                                     
jfptr__atexit_28468 at /data/vtjnash/julia/usr/lib/julia/sys.so (unknown line)                                                                                                                                                                                   
_jl_invoke at /data/vtjnash/julia/src/gf.c:2627 [inlined]                                                                                                                                                                                                        
ijl_apply_generic at /data/vtjnash/julia/src/gf.c:2828                                                                                                                                                                                                           
jl_apply at /data/vtjnash/julia/src/julia.h:1875 [inlined]                                                                                                                                                                                                       
ijl_atexit_hook at /data/vtjnash/julia/src/init.c:280                                                                                                                                                                                                            
jl_repl_entrypoint at /data/vtjnash/julia/src/jlapi.c:718                                                                                                                                                                                                        
main at /data/vtjnash/julia/cli/loader_exe.c:58                                                                                                                                                                                                                  
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)                                                                                                                                                                                              
_start at /data/vtjnash/julia/usr/bin/julia (unknown line)                                                                                                                                                                                                       
Allocations: 38229437 (Pool: 38200545; Big: 28892); GC: 47                                                                                                                                                                                                       
```

**Pull request merged**
