### PR TITLE
Change the error messages in relpath function.

### PR DESCRIPTION
**Pull request by sudhansubhushanmishra**
This was an attempt to fix issue #47443
I'm just a beginner, so please guide me in the right direction. I thought isempty checked for empty string arguments, and that an unspecified argument would rather cause a compile-time error. Looking forward to feedback

### CODE REVIEW

**Review by sudhansubhushanmishra — COMMENTED** [review]
This was an attempt to fix issue #47443
I'm just a beginner, so please guide me in the right direction. I thought isempty checked for empty string arguments, and that an unspecified argument would rather cause a compile-time error. Looking forward to feedback

**Comment by KristofferC** [comment]
Thanks for the PR. This is indeed an improvment!

**Comment by StefanKarpinski** [comment]
Any reason why there's no CI checks on this PR?

**Comment by giordano** [comment]
There is some problems on GitHub's side with this PR, we can't merge it.

**Comment by the-lazy-learner** [comment]
@giordano Could you please let me know what things need to be fixed?

**Comment by giordano** [comment]
Can you please open a new PR?

**Comment by the-lazy-learner** [comment]
Okay will do in a while

**Pull request merged**
