### PR TITLE
set VERSION to 1.8.0-beta3

### PR DESCRIPTION
**Pull request by KristofferC**
There was some issue with the beta2 tag regarding buildkite so it seems we have to go straight to beta3. Hopefully this will work better on buildkite.

cc @ararslan, @staticfloat, @DilumAluthge

### CODE REVIEW

**Comment by staticfloat** [comment]
Buildkite test failure is fixed by https://github.com/JuliaLang/julia/pull/44280 which needs backporting.  It's a harmless failure in the grand scheme of things, but would be nice to fix.

Note to @ararslan and @DilumAluthge: if we want to publish a beta that isn't passing tests (and therefore does not get uploaded to S3), we can do so by downloading the built artifacts from buildkite.  You go to the `build` step that you're interested in, click "artifacts", download the tarball, then upload to S3.

Screen Shot 2022-03-28 at 9 07 45 AM

This is a pain for non-linux arches though, as we don't get `.dmg`, `.exe`, codesigning, etc....  So it's better if we can get it to pass tests.  :)

**Comment by ararslan** [comment]
> Buildkite test failure is fixed by https://github.com/JuliaLang/julia/pull/44280 which needs backporting.

Backporting in https://github.com/JuliaLang/julia/pull/44779

**Comment by ararslan** [comment]
I've rebased to retrigger CI now that the backport PR was merged.

**Comment by KristofferC** [comment]
```


From worker 6:	┌ Warning: Skipping hostname verification tests. Is `openssl` on the path?
--
  | From worker 6:	│   exception = IOError: could not spawn `openssl version`: no such file or directory (ENOENT)
  | From worker 6:	└ @ Main.Test15Main_LibGit2_libgit2.LibGit2Tests /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/julia-5a42289325/share/julia/stdlib/v1.8/LibGit2/test/libgit2.jl:3104
  | From worker 6:	┌ Warning: Skipping hostname verification tests. Unable to determine a hostname which maps to the loopback address
```

Is this known @staticfloat @DilumAluthge?

**Comment by KristofferC** [comment]
Also something about

```


The futex facility returned an unexpected error code.
--
  |  
  | signal (6): Aborted
  | in expression starting at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/julia-5a42289325/share/julia/stdlib/v1.8/Distributed/test/topology.jl:5
  | Allocations: 103830700 (Pool: 103802582; Big: 28118); GC: 121
  | Distributed                               (1) \|         failed at 2022-03-29T02:11:05.663
  | Error During Test at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/julia-5a42289325/share/julia/test/testdefs.jl:21
  | Got exception outside of a @test
  | LoadError: Distributed test failed, cmd : `/cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/julia-5a42289325/bin/julia -Cnative -J/cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/julia-5a42289325/lib/julia/sys.so -g1 --check-bounds=yes --startup-file=no --depwarn=error /cache/build/default-amdci5-5/julialang/julia-release-1-dot-8/julia-5a42289325/share/julia/stdlib/v1.8/Distributed/test/distributed_exec.jl`
```

**Comment by DilumAluthge** [comment]
I've never seen the `openssl version` failure before.

I also saw the `The futex facility returned an unexpected error code`, but I'm not sure it's about. I've only seen it during the Distributed test suite, so I posted in `#distributed` on Slack.

**Comment by KristofferC** [comment]
Got told the particular builders where the test failures are are not critical so I will merge this.

**Pull request merged**
