### PR TITLE
Check whether ld supports -Bsymbolic-functions flag

### PR DESCRIPTION
**Pull request by tkelman**
cc @grayclhn @waTeim @staticfloat look okay to you guys?

Wasn't so hard after all, but I'd rather not go too far down the road of doing this in gmake for every single flag.

### CODE REVIEW

**Comment by staticfloat** [comment]
Looks good to me, but I guess the true test is to see if it works for @grayclhn.

**Comment by waTeim** [comment]
Tested the command on 6.5 anyhoo,  I won't be near a Linux julia dist Makefile for a while yet to try the makefile directly.

    ld --help | grep -o -e -Bsymbolic-functions
    -Bsymbolic-functions

**Comment by grayclhn** [comment]
It works. And it works when it's cherry-picked onto release-0.3 as well. Thanks!

**Comment by tkelman** [comment]
Sounds good, thanks for testing. Looks okay on Travis, let's put it on master for a little while to see if it somehow causes any other problems. We'll be sure to backport before the next release if nothing comes up.

**Comment by grayclhn** [comment]
sounds great

**Comment by tkelman** [comment]
backported in eaad06c0a55fa0e201b1c23f5bf74000b179fd6a

**Pull request merged**
