### PR TITLE
Minor changes and links

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note also the [Vagrant](http://www.vagrantup.com/downloads) link (in two places) and its link in the script are not working:

zypper addrepo http://download.opensuse.org/repositories/windows:mingw:win$BITS/openSUSE_Leap_42.2/windows:mingw:win$BITS.repo

**Comment by inkydragon** [comment]
+ `http://www.vagrantup.com/downloads` => `https://www.vagrantup.com/downloads.html`
+ did you replace `$bits` to `32`/`64`?
> * After  String interpolation ：
>   `https://download.opensuse.org/repositories/windows:mingw:win$BITS/openSUSE_Leap_42.2/windows:mingw:win$BITS.repo`, it will 301 redrect to https://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/windows:mingw:win64.repo 
> 
>  https://github.com/JuliaLang/julia/pull/30910/files#r257454985 

It seems like you are going to update those doc, and there is a pr #30910 which is going to update code.

**Comment by PallHaraldsson** [comment]
The original commit (and the one I just did now) should be non-controversial; I don't know if it difficult to merge.

@inkydragon "did you replace $bits to 32/64?"

No, nor sure I should have. I only changed docs (not meaning), and docs on code (its comments, but not the "code" itself). I just made one more small change, still github says "added 2 commits on 25 Feb". Not sure why, maybe related to that I found out the file is gone... was moved, and then again (at least the letter time with no changes, didn't locate commit for first move):

https://github.com/JuliaLang/julia/pull/31858/files#diff-6b980be813aa6e70a9ca3344d4771c86

**Comment by Keno** [comment]
This file got moved to `doc/build/windows.md`. I think the change is ok, but I don't care enough about it to try and rebase this myself. I'd take a new PR against the moved document if somebody cares enough.

**Pull request closed without merging**
