### PR TITLE
Update annotated.jl docstrings according to #55741

### PR DESCRIPTION
**Pull request by danielwe**
@tecosaur

### CODE REVIEW

**Comment by LilithHafner** [comment]
Good catch, thanks! Would you also change those `julia-repl` blocks to `jldoctest` so that in the future these types of mistakes will make CI fail?

**Comment by danielwe** [comment]
Done!

**Comment by tecosaur** [comment]
Looks good to me! I do wonder if it would be better to have `using Base.AnnotatedString` as the doctest line, even though it is technically private, just for the sake of not loading a stdlib for a Base doctest.

**Comment by LilithHafner** [comment]
Great! Thanks for the update.

**Pull request merged**
