### PR TITLE
Fix #17462, break/continue in an at-testset for loop

### LINKED ISSUE #17462: break/continue in a @testset for loop is broken
As @tkelman reported here: https://github.com/KristofferC/NearestNeighbors.jl/issues/25 (and kindly bisected to https://github.com/JuliaLang/julia/commit/cd35df536bd) Julia master now does not support `break` or `continue` in a `@testset` for loop

```jl
using Base.Test

@testset for x in [1,2,3]
	if x == 1
		continue
	end
end

ERROR: syntax: break or continue outside loop
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

cc @JeffBezanson since it got bisected to commit that was authored by you

### PR DESCRIPTION
**Pull request by tkelman**
This fixes NearestNeighbors.jl.

### CODE REVIEW

**Comment by tkelman** [comment]
I might not be understanding how testsets are supposed to work, but one strange thing here is that if I put a failing test inside the testset then I get a backtrace but `make test-test` says "SUCCESS". Is that a bug too or intended?

**Comment by kshyatt** [comment]
@tkelman That is a bug that my big ball of testset mud PR fixes

**Comment by tkelman** [comment]
could it be split out so it would be an 0.5 backport candidate?

**Comment by kshyatt** [comment]
It might be kind of hard to `cherry-pick` a specific commit but I can try to make a new PR against `release-0.5`?

**Comment by tkelman** [comment]
if it's a bugfix that's doable independently of the rest of that pr that would be best. though there isn't quite a release-0.5 branch just yet.

**Pull request merged**
