### PR TITLE
use Pkg.precompile during loading via Pkg hook

### LINKED ISSUE #48259: `using` should trigger Pkg's parallel precompilation
I think Base should add a hook so that when Pkg is loaded, `using PkgX` triggers parallel precompilation instead of serial. It's not intuitive for that there's different precompilation modes with hugely different runtimes, and I think it's a common footgun to accidentally use the non-parallel version.

### PR DESCRIPTION
**Pull request by IanButterworth**
Closes https://github.com/JuliaLang/julia/issues/48259

Previously
```
julia> using CSV
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]

julia> 
```

This PR
```
julia> using CSV
Precompiling CSV
  20 dependencies successfully precompiled in 30 seconds. 1 already precompiled.

julia> 
```

Note that errors and warnings will be shown, including warnings about precompilation waiting for tasks to finish etc. so this should be quite safe. But a switch could be added to turn it off.

Requires:
- https://github.com/JuliaLang/Pkg.jl/pull/3433

Also two minor bug fixes:
- https://github.com/JuliaLang/Pkg.jl/pull/3432
- https://github.com/JuliaLang/Pkg.jl/pull/3431

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
We are in the imminent process of removing Pkg, so this seems unwise to merge now

**Comment by vtjnash** [comment]
There was also an issue with Pkg.precompile suppressing warnings and other similar messages, which means this PR would harm usability and development until that fix is merged.

**Comment by ericphanson** [comment]
I believe Ian has already [addressed this in Pkg.jl
](https://github.com/JuliaLang/Pkg.jl/pull/3319)

>Note that errors and warnings will be shown, including warnings about precompilation waiting for tasks to finish etc. so this should be quite safe. But a switch could be added to turn it off.

> We are in the imminent process of removing Pkg, so this seems unwise to merge now

This just adds a hook, so it seems fine? If you load Pkg, it populates the hook, and switches you to parallel precompilation.

**Comment by KristofferC** [comment]
> We are in the imminent process of removing Pkg, so this seems unwise to merge now

We might want to move the parallel precompile code to Base. It doesn't really have anything to do with the package manager itself. You would want parallel precompile without having to load Pkg.

**Comment by IanButterworth** [comment]
Oops. Just closed that

**Comment by vtjnash** [comment]
Gotcha, yeah that makes more sense.

**Comment by IanButterworth** [comment]
Won't be functional until Pkg has been bumped with https://github.com/JuliaLang/Pkg.jl/pull/3433

**Pull request merged**
