### PR TITLE
Add ``Base.`` annotations to ``mapfoldl`` in docs

### PR DESCRIPTION
**Pull request by joehuchette**
Figured this was probably preferable to adding more exports.

### CODE REVIEW

**Comment by tkelman** [comment]
I think cross-references are now annotated with `:func:` ?

**Comment by joehuchette** [comment]
As best I can tell these functions are undocumented, so not sure what I would cross-reference.

**Comment by tkelman** [comment]
lines 429-449?

**Comment by joehuchette** [comment]
...that's embarrassing. Haha. I'll make the change.

**Comment by joehuchette** [comment]
Take 3

**Comment by nolta** [comment]
Needs a squash.

**Comment by joehuchette** [comment]
Squashed

**Comment by tkelman** [comment]
backported in 988f3a287664e97b515c76a1a2c651b0cf13ed14

**Pull request merged**
