### PR TITLE
🤖 Bump the SuiteSparse stdlib from f63732c to 8e83ebc

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SuiteSparse
URL: https://github.com/JuliaSparse/SuiteSparse.jl.git
Branch: master
Old commit: f63732c
New commit: 8e83ebc
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline f63732c..8e83ebc
8e83ebc Add docstrings to local docs, add SuiteSparse citations to docstrings (#64)
f31dc2e Merge pull request #63 from IanButterworth/ib/testset_org_tweak
b33eab5 move threaded testsets to main process
```

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@ViralBShah @KristofferC Any idea how to fix the build failures?

**Comment by ViralBShah** [comment]
cc @Wimmerer

**Comment by Wimmerer** [comment]
I'm not sure what 

```Error: duplicate docs found for 'SuiteSparse.UMFPACK.lu' in `@docs` block in src/stdlib/SuiteSparse.md:23-29```

means. Does that indicate there are multiple doc strings? There shouldn't be, the only two significant ones in UMFPACK are `lu` and `lu!`.

The other one is related to footnotes I added. Let me look at why it's not building correctly.

**Comment by DilumAluthge** [comment]
Yeah I'm not sure what's causing the docs failure. Maybe @fredrikekre can help?

**Comment by DilumAluthge** [comment]
Maybe the docs issue is from duplication between SuiteSparse and SparseArrays? Just brainstorming.

**Comment by Wimmerer** [comment]
Indeed building those docs locally for me works _perfectly_ (except some failing doctests which I've fixed after the transfer to SparseArrays so I'll leave be). I have no erroring footnotes in particular.

That being said, despite building locally I am missing a lot of documentation from https://suitesparse.juliasparse.org/dev/ compared to local.

**Comment by KristofferC** [comment]
> Error: duplicate docs found for 'SuiteSparse.UMFPACK.lu' in `@docs` block in src/stdlib/SuiteSparse.md:23-29

These are defined in SuiteSparse docs: https://github.com/JuliaSparse/SuiteSparse.jl/blob/master/docs/src/index.md and now also in the SparseArrays docs and you cannot have two references to the same documentation in one documentation build. So the SuiteSparse docs have to be updated to not refer to these docs (since the packages are merged, maybe it should just link to the SparseArrays.SuiteSparse docs).

**Comment by ViralBShah** [comment]
Maybe skip this one and bump everything once again with the updated combined package?

**Comment by DilumAluthge** [comment]
> Maybe skip this one and bump everything once again with the updated combined package?

Probably the easiest approach.

**Pull request closed without merging**
