### PR TITLE
update nthreads info in versioninfo

### LINKED ISSUE #52404: Improve information displayed on threads by `versioninfo`
Current 1.10-rc2 shows:

```
C:\>julia -q --threads=auto --startup-file=no -e "using InteractiveUtils; versioninfo()"

Julia Version 1.10.0-rc2
Commit dbb9c46795 (2023-12-03 15:25 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 11 on 8 virtual cores
```

I've learned on Slack that the surprisingly high number of threads is due to additional GC threads and that therefore the CPU isn't actually oversubscribed. 

A related issue is #48580 which complained about `nthreads()` giving unexpected results since the introduction of interactive threads. To my mind ideally `versioninfo()` (and related places/functions which give threads info) should say something like:

```
Threads:
    - Default: 8
    - Interactive: 1
    - GC: 3
Number of virtual cores: 8
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/52404
@nilshg I opted to make it one line as it fits.
```
julia> versioninfo()
Julia Version 1.11.0-DEV.1011
Commit bb7091c6f2* (2023-12-04 14:58 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin23.0.0)
  CPU: 10 × Apple M2 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
Environment:
  JULIA_EDITOR = code
```

### CODE REVIEW

**Comment by nilshg** [comment]
Looks great, thank you!

**Comment by christiangnrd** [comment]
There might be an off-by-one error somewhere. I'm not familiar enough with the internals to be able to tell where but with this pr the total number of threads (8 default + 0 interactive + 4 GC = 12) is one higher than on master (11 on 8 virtual cores).

Or maybe one of the GC threads is shared with the default ones?

If this PR does not get backported to 1.10 and the current versioninfo() is incorrect, let me know and I'll create a separate issue to at least fix it.

**Comment by IanButterworth** [comment]
> Or maybe one of the GC threads is shared with the default ones?

Seems to be the case. The thread that spawns GC is used for GC, so `ngcthreads()` is only >1 if dedicated GC threads are requested
https://github.com/JuliaLang/julia/blob/8440f83a799f9a04691d8f8bbfc4a6a234c98e87/base/threadingconstructs.jl#L145

**Comment by IanButterworth** [comment]
bump @vchuravy (hopefully simple)

**Comment by giordano** [comment]
Can this be backported to 1.10, since that's where the issue was originally reported on in #52404?

**Comment by IanButterworth** [comment]
If this doesn't get specific approval first I'll merge this in a few days assuming https://github.com/JuliaLang/julia/pull/52423#issuecomment-1858355793 is correct.

**Pull request merged**
