### PR TITLE
README: 0.4 is the new 0.3

### PR DESCRIPTION
**Pull request by jiahao**

### CODE REVIEW

**Comment by vtjnash** [comment]
thanks. i forgot my addition of this to the make release-candidate instructions had been languishing in my PR (https://github.com/JuliaLang/julia/blob/jn/makefile_o/Makefile#L145)

**Comment by tkelman** [comment]
There hasn't been a release on 0.4 yet.

**Comment by jiahao** [comment]
Well this is the classic chicken-and-egg situation. If you claim a RC is releaseworthy, then this has to be in the release materials.

**Comment by tkelman** [comment]
This PR is against master, and README.md is not part of the release materials, it doesn't get installed.

**Comment by jiahao** [comment]
> This PR is against master, and README.md is not part of the release materials, it doesn't get installed.

I don't believe this is correct. `README.md` is picked up by the `Makefile` rule `light-source-dist.tmp`, needed by both `light-source-dist` and `full-source-dist`. I don't see where it is filtered out by the list of files generated by `git ls-files`.

**Comment by tkelman** [comment]
It's in the tarball, but only out of laziness in creating them. The README in the tarball is of limited use, and instructions pertaining to git are irrelevant when you're working from a tarball or a distro-packaged binary. README.md's primary purpose is for online use from github, and distros can choose to install it from the tarball manually if they want but `make install` doesn't do so.

**Comment by jiahao** [comment]
So should when should this update be applied? between items 9 and 10 on the `release-candidate` checklist?

**Comment by tkelman** [comment]
In my mind this would be the last commit on the release-0.4 branch before bumping VERSION to 0.4.0 and tagging, then I would push the two commits (plus a third for bumping VERSION to 0.4.1-pre) and the tag, tarball, etc simultaneously. Once the actual stable 0.4.0 release is available, then I'd forward-port this commit to master. But that's just me.

**Pull request merged**
