### PR TITLE
fix some FIXMEs in random, and take 2 to #9174

### PR DESCRIPTION
**Pull request by rfourquet**
In "random/RNGs.jl", some code was `unsafe_wrap`ing a pointer of an `Array`, which was apparently "completely invalid". `reinterpret` could work in some case as replacement, but it's not flexible enough, e.g. the following doesn't work: `reinterpret(UInt128, UInt32[1, 2, 3])`. So we use `Ptr` directly, which is the dSFMT API anyway, with an `UnsafeView<:DenseArray` wrapper which makes the code nicer. So this is a re-implementation of #9174 in disguise, and allows some nice speed-up for `rand!` on small arrays as a result of allocating less (`unsafe_wrap` allocates), for example `a = UInt64[1]; rand!(a)` has a speed-up of 85% on my machine.

### CODE REVIEW

**Comment by rfourquet** [comment]
@nanosoldier `runbenchmarks("random", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24885#issuecomment-348713623) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a9cbef5bdbeb0cd04949d06c1de040f239faae13/4a28387_vs_255b5d5/report.md). cc @ararslan

**Comment by ViralBShah** [comment]
cc @andreasnoack @simonbyrne for review.

**Comment by rfourquet** [comment]
@vtjnash even without reviewing in detail, would you mind skimming over this to check that this change indeed fixes the previously invalid code? Basically the `rand!` "kernel" receives a `Ptr` (wrapped in an `UnsafeView`), and other `rand!(::Array)` methods call to the kernel by sending a pointer the array with a length.

**Comment by rfourquet** [comment]
I would like to merge this today or tomorrow, to make another PR touching this code. I believe this change is correct, and anyway the old one was "invalid" so it's unlikely to get worse.

**Comment by StefanKarpinski** [comment]
Please go for it then, @rfourquet!

**Comment by rfourquet** [comment]
Big thanks for your support Stefan with my PRs !

**Pull request merged**
