### PR TITLE
release-1.8: Backports for 1.8-rc4

### LINKED ISSUE #45825: BitArray "constructor" incorrectly assumes 1-based indexing, leading to nondeterministic incorrect results due to out-of-bounds memory access
For example, in the following code, a `BitArray` that is constructed from an input array of values that are all `false` is found to contain some values that are `true`:

```jl
julia> using OffsetArrays

julia> all_false = falses(-1000:1000);

julia> any(==(true), all_false)
false

julia> all_false_bitarray = BitArray(all_false);

julia> any(==(true), all_false_bitarray)
true
```

This is due to the code [here](https://github.com/JuliaLang/julia/blob/2168230c210d620786311d91528a155582f78bc8/base/bitarray.jl#L510-L514), which applies `@inbounds` to a loop before proceeding to index the user-provided array with indices that start from one.

https://github.com/JuliaLang/julia/blob/2168230c210d620786311d91528a155582f78bc8/base/bitarray.jl#L510-L514

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #46040 
- [x] #45967 
- [x] #45212 
- [x] #46053 
- [x] #46072 
- [x] #45835 
- [x] #46111 
- [x] #45613
- [x] #45993
- [x] #45670
- [x] #45992 
- [x] #44670
- [x] #45613
- [x] #45980 
- [x] #45890 
- [x] #46114 
- [x] #46050 
- [x] #46085 
- [x] #46208 
- [x] #46100 
- [x] #46161 
- [x] #46118 
- [x] #46171 
- [x] #46163 
- [x] #44935 

Need manual backport:
- [ ] #46086 

Contains multiple commits, manual intervention needed:
- [x] #46239 

Non-merged PRs with backport label:
- [ ] #46237 
- [ ] #46183 
- [ ] #46010 
- [ ] #45582 
- [ ] #45578

### CODE REVIEW

**Comment by vchuravy** [comment]
@aviatesk Failure on windows looks relevant:

```
Error in testset math:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\math.jl:1426
  Expression: Core.Compiler.is_foldable(Base.infer_effects(^, (T, Int)))
Error in testset math:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\math.jl:1447
  Expression: Core.Compiler.is_foldable(Base.infer_effects(^, (Float32, Int)))
```

**Comment by aviatesk** [comment]
Thanks, I backported #45299 to fix it. Now I'm a bit worried that the backports ends up being fairly big...

**Comment by IanButterworth** [comment]
Some Pkg backports are pending https://github.com/JuliaLang/Pkg.jl/pull/3114

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1203183767):
```
Base.IOError("unlink(\"/tmp/jl_c8vjoA\"): no such file or directory (ENOENT)", -2)
```
cc @maleadt

**Comment by maleadt** [comment]
I'm actually still doing some work on PkgEval (currently trying-out https://github.com/JuliaCI/PkgEval.jl/pull/108, if that works I think we could significantly reduce the time it takes to run all tests). However, I could as well do those tests on a useful comparison:

@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

It's possible the results might be off though, and I might have to run it again if another bug surfaces.

**Comment by maleadt** [comment]
Fixed another bug, so let's re-start:

@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1204849013) failed. cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1205349344) failed. cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1205453179):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/storage/pkgeval/depot/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/NanosoldierReports"), ProcessExited(128)) [128]

```
Unfortunately, the logs could not be uploaded.
cc @maleadt

**Comment by maleadt** [comment]
Pushed it manually: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4983135_vs_843b322/report.html

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["Balloons", "COPT", "CellListMap", "CitableImage", "CountdownNumbers", "CrystalInfoFramework", "DataDrivenDiffEq", "DiffEqDevTools", "FlameGraphs", "Folds", "GPUCompiler", "GasChromatographySimulator", "InformationGeometry", "MatrixPencils", "NODAL", "Optimization", "OteraEngine", "PDENLPModels", "PoreMatMod", "PowerFlowData", "ProfileView", "ProxSDP", "PsychomotorVigilanceTask", "QuadraticToBinary", "RadiativeTransfer", "RetroCap", "SimpleFWA", "Singular", "StochasticPrograms", "StrBase", "StressTest", "SymbolicUtils", "TensorBoardLogger", "TensorToolbox", "TransitionalMCMC", "UrlDownload", "YAAD", "vSmartMOM"], vs = ":release-1.8"buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["Balloons", "COPT", "CellListMap", "CitableImage", "CountdownNumbers", "CrystalInfoFramework", "DataDrivenDiffEq", "DiffEqDevTools", "FlameGraphs", "Folds", "GPUCompiler", "GasChromatographySimulator", "InformationGeometry", "MatrixPencils", "NODAL", "Optimization", "OteraEngine", "PDENLPModels", "PoreMatMod", "PowerFlowData", "ProfileView", "ProxSDP", "PsychomotorVigilanceTask", "QuadraticToBinary", "RadiativeTransfer", "RetroCap", "SimpleFWA", "Singular", "StochasticPrograms", "StrBase", "StressTest", "SymbolicUtils", "TensorBoardLogger", "TensorToolbox", "TransitionalMCMC", "UrlDownload", "YAAD", "vSmartMOM"], vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1207248491) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/2415a14_vs_843b322/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["COPT", "CountdownNumbers", "FlameGraphs", "Folds", "GPUCompiler", "PowerFlowData", "RetroCap", "StrBase", "StressTest", "SymbolicUtils", "TensorBoardLogger", "vSmartMOM"], vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46075#issuecomment-1207380506) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/2415a14_vs_843b322/report.html).

**Pull request merged**
