### PR TITLE
aotcompile: Merge two continue's into one

### PR DESCRIPTION
**Pull request by zlatanvasovic**
A minor improvement.

### CODE REVIEW

**Comment by KristofferC** [comment]
I personally don't really see this as an improvement. Why do you think this is better?

**Comment by StefanKarpinski** [comment]
Agree, I think the current version is clearer. They're different cases that both happen to continue, but they're logically distinct so might as well leave them separate.

**Comment by zdroid** [comment]
Well as I said, it's a minor improvement. It reduces the code duplication and maybe removes an instruction or two (but more likely it ends up compiling to the same code).

**Comment by KristofferC** [comment]
Again, I think it would still be good to explain why this is an improvement at all. And yes, there is no performance effect of this.

**Comment by Keno** [comment]
Yeah, this is contrary to most style guides which explicitly recommend to reduce the condition depth, unless the conditions are very closely linked.

**Comment by zdroid** [comment]
@Keno I agree with that one, so I'm closing this. Thanks for the remarks.

**Pull request closed without merging**
