### PR TITLE
move Iterators module out of Base

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a bit ugly, since `Iterators` is used and referenced by name very often in Base. We can't have a deprecation for `Base.Iterators` and also continue to use `Base.Iterators` as the name of the module internally, so I (possibly temporarily) renamed `Base.Iterators` to `Base.Iter`. Then I added an `Iterators` stdlib module as usual, which mostly re-exports items from `Base.Iter`. There are also a couple things not used in Base that can be fully moved to the new module.

Maybe the worst part about this is that some iterator types will print as `Base.Iter.X` and some as `Iterators.X`. It would be better if we could move everything to `Iterators`, and somehow arrange for Base to load it very early. Another possibility might be to add a way for the top-level `Iterators` package name to actually be an alias for `Base.Iterators`. I don't think we have a way to do that though.

### CODE REVIEW

**Comment by ararslan** [comment]
Is it actually necessary to move Iterators given that it's used to heavily in Base?

**Comment by JeffBezanson** [comment]
True, "move" is not quite the right term here. The main point is to rename `Base.Iterators` to `Iterators` so it's more like other packages and stdlibs.

**Comment by ararslan** [comment]
Would be possible to make this work instead?
```
julia> Iterators
Base.Iterators

julia> using Iterators
ERROR: ArgumentError: Module Iterators not found in current path.
Run `Pkg.add("Iterators")` to install the Iterators package.
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:868
```
Seems like it would be possible to modify `identify_package` such that exported Base modules can be identified?

**Comment by StefanKarpinski** [comment]
The correct ways to load `Iterators` are `using Base.Iterators` or `using .Iterators` if `Iterators` is bound to the module you want to load from in your current module.

**Comment by ararslan** [comment]
I understand that's currently the correct way. I'm asking if it's possible to allow unqualified loading for modules that are exported from Base.

**Comment by StefanKarpinski** [comment]
I guess, but isn't that equivalent to putting them in the standard library? You just don't want to have a file in that directory with exports?

**Comment by ararslan** [comment]
If Base is using something heavily, it seems suboptimal to hide it inside of a different internal module then make a separate, standalone module to export the things that were already defined in Base. As Jeff noted above, things will print differently, which is confusing. It seems ideal to me to simply be able to load the same module as Base without the huge workaround.

**Comment by JeffBezanson** [comment]
I did consider flattening `Base.Iterators` into `Base` first, but it's not fully possible since `Base.Iterators.filter` and `Base.Iterators.reverse` differ from `Base.filter` and `Base.reverse`.

We could potentially add a feature that allows `stdlib/Iterators/src/Iterators.jl` to say "use Base.Iterators as the module for this package".

**Comment by ararslan** [comment]
> We could potentially add a feature that allows `stdlib/Iterators/src/Iterators.jl` to say "use Base.Iterators as the module for this package".

I'm not sure what you mean. Could you elaborate?

**Comment by JeffBezanson** [comment]
We would have `stdlib/Iterators/src/Iterators.jl` as usual for stdlib packages, but in that file, instead of `module Iterators ... end` would be an incantation that says "use `Base.Iterators` for this". That would allow `using Iterators` to work as normal, and if it resolves to the stdlib package is equivalent to `using Base.Iterators`.

**Comment by StefanKarpinski** [comment]
Can't we just import and reexport all the iterators from `Base.Iterators` in `stdlib/Iterators`? I'm not clear on what feature is needed.

**Comment by JeffBezanson** [comment]
Yes, and that's basically what this PR does. The problems are (1) `Base.Iterators` needs to be renamed to allow deprecation, (2) we end up with two modules instead of one, which works but is sub-optimal for reflection purposes.

**Comment by vtjnash** [comment]
I don't like having code inside `stdlib/` that's actually part of `base/`. It also confuses and messes up the build system to put code in the wrong folder.

If the goal is simply to make `using Iterators` work, would the following suffice:
```diff
diff --git a/base/loading.jl b/base/loading.jl
index 56646cd417..3d477fc035 100644
--- a/base/loading.jl
+++ b/base/loading.jl
@@ -899,6 +899,7 @@ end
 register_root_module(Core)
 register_root_module(Base)
 register_root_module(Main)
+register_root_module(Iterators)
 
 is_root_module(m::Module) = haskey(module_keys, m)
 root_module_key(m::Module) = module_keys[m]
```

**Comment by bramtayl** [comment]
It seems like their should be some official guidance or at least heuristics about deciding what belongs in Base, a Base submodule, a stdlib, or an external package.

**Comment by nalimilan** [comment]
> I don't like having code inside stdlib/ that's actually part of base/. It also confuses and messes up the build system to put code in the wrong folder.

FWIW, that's already the case for Unicode and CRC32c (at least).

**Comment by JeffBezanson** [comment]
> code inside stdlib/ that's actually part of base/

If I understand you, I don't think that's what's going on here --- Base is not including code from `stdlib/`. The code in Base is indeed in `base/`, but some stdlib modules re-export names from there. The same is true of Unicode and CRC32c. Are there examples I'm missing?

**Comment by vtjnash** [comment]
`Base64`, but OK, that's clearer at least. I still don't really like doing that.

For naming, maybe some combinations of "Lazy", "Tools", "Extra", "Iter", "Iterators"?

**Pull request closed without merging**
