### PR TITLE
fix maximum on generic orders

### PR DESCRIPTION
**Pull request by jw3126**
Closes #30436
See #30320

### CODE REVIEW

**Comment by ViralBShah** [comment]
I believe it retains those fixes, but good to see how the performance pans out.

**Comment by jw3126** [comment]
This is still as fast:
```julia
julia> using BenchmarkTools; arr = randn(10^6); @benchmark maximum($arr)
[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     560.122 μs (0.00% GC)
  median time:      587.918 μs (0.00% GC)
  mean time:        593.810 μs (0.00% GC)
  maximum time:     1.197 ms (0.00% GC)
  --------------
  samples:          8328
  evals/sample:     1
```

**Comment by ViralBShah** [comment]
Good to merge?

**Review by mbauman — APPROVED** [review]

**Comment by jw3126** [comment]
I also think so.

**Pull request merged**
