### PR TITLE
Make install cleaning and improvements

### PR DESCRIPTION
**Pull request by nalimilan**
The first commit makes the tree resulting from `make install` cleaner.

The second one is an attempt at fixing https://github.com/JuliaLang/julia/issues/8367, but it currently doesn't work. I'd appreciate some help from the genius who wrote Makefile:27. It should be adapted so that the symlink to `doc/` is no longer created at `$(build_datarootdir)/julia/doc`, but at `$(build_docdir)` -- Make.inc:102 should then also be made consistent with Make.inc:89.

### CODE REVIEW

**Comment by waTeim** [comment]
Hey no problem!  Confirmed functional after merge on OS/X, Linux, Windows.  Now on to #8757; I'll return to that discussion to ask questions.

**Comment by waTeim** [comment]
Hey! wrong thread.

**Comment by tkelman** [comment]
Hm, we never backported this. Should we? Also #8398 would be necessary

cc @juliabackports

**Comment by staticfloat** [comment]
I don't think this is urgent enough to backport; it's mostly stuff to make things more "correct", but doesn't fix any big bugs that I can tell.

**Comment by tkelman** [comment]
No urgency, not really fixing a bug, but does reduce the number of fiddly conflicts if we want to backport #10253. I could probably limit that to just 94334bc0b0b572f186fa43227409fcdfd4a1290f for consistent naming on the buildbots though, and not backport the rest of it.

**Comment by vtjnash** [comment]
i just got bit by this commit on master, since the files never get recopied from examples when they get modified. this either needs to be reverted to a symlink or written with proper makefile dependency update rules.

**Comment by waTeim** [comment]
Oh! is it a possible “julia-config to the rescue” moment?

**Comment by tkelman** [comment]
No, it's a "makefiles should never be written by humans" moment since no one ever seems to be able to write them perfectly.

**Comment by nalimilan** [comment]
Makefiles are also particularly hard to test... As can be seen from the fact that nobody had noticed this bug for months. :-/

Ideally, `$(build_docdir)` should recursively depend on `doc/` (and thus on `examples/`), so that it's copied again on every change. But it doesn't seem easy in make. We could just mark this as a `PHONY` target, but running it on every build would be silly. Any ideas?

**Comment by nalimilan** [comment]
Bump!

**Comment by tkelman** [comment]
would the directory timestamp be a decent proxy?

**Comment by nalimilan** [comment]
Not AFAICT. Switching between two branches which have differences under `doc/` does not update the timestamp. You need to create/delete a file for that (and, I think, only at the toplevel). That's really lousy.

**Comment by nalimilan** [comment]
@staticfloat Do you have any ideas?

**Comment by staticfloat** [comment]
Take a look at [this branch](https://github.com/JuliaLang/julia/tree/sf/examplesfix) and let me know if it fixes it for you.

**Comment by nalimilan** [comment]
@vtjnash I think you're the best person to check whether @staticfloat's fix works.

**Comment by vtjnash** [comment]
Wildcard is preferable to shell find, but you can't use directory timestamps for this, so it wouldn't be entirely reliably. A better option would be to put a dummy file in there and "touch" it at the end of the makefile rule.

**Comment by staticfloat** [comment]
Yes, the nice thing about `$(shell find examples)` is that it recurses.

I'm not sure how the dummy file would work?  We want to re-rerun this command every time a file in `examples` changes, so how would the timestamp of the dummy file get updated when I edit e.g. `examples/clustermanager/0mq/head.jl`?

**Comment by vtjnash** [comment]
Good point about the recursion. The dummy file would be the target, since the timestamp of a folder target is unreliable.

**Comment by staticfloat** [comment]
What I mean is how does the timestamp of the dummy file get updated?  As it stands, because `$(shell find examples)` explicitly lists out all the files contained within `examples/`, we have direct dependency on each file within `examples/` and aren't relying on the directory timestamps at all.  I suppose we could ask `find` to only list files and not include directories, but I'm not sure that would help anything.

**Comment by vtjnash** [comment]
touch $@

**Comment by waTeim** [comment]
Following on, If you wanted to go down the find-touch route, then something like this might work:

    find . -type f -exec touch {} \;

Or some-such.  Sorry I have not been paying attention to this thread as much as I should.

**Comment by staticfloat** [comment]
I don't think we're talking about the same thing; we want to re-run these commands whenever an _external_ program modifies the files; we don't want to change the timestamps from within the Makefile.

**Pull request merged**
