### PR TITLE
 release-1.7: Backports for 1.7-RC1/1.7-beta4

### LINKED ISSUE #40773: Base.summarysize not properly accounting for Vectors containing certain types
Hey all. On Julia 1.5.3:
```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

it seems that `Base.summarysize` doesn't recurse deeply enough for `Vector`s containing `Set`s (as well as for our own user-defined type).

```julia
julia> s = Set(1:100)
Set{Int64} with 100 elements:
  2
  89
  11
  29
  74
  57
  31
  78
  70
  33
  96
  ⋮ 
julia> c = [s]
1-element Array{Set{Int64},1}:
 Set([2, 89, 11, 29, 74, 57, 31, 78, 70, 33  …  19, 51, 22, 6, 24, 73, 53, 23, 27, 56])
julia> Base.summarysize(c)
48
julia> Base.summarysize(s)
4800
```
`Array{Array{Int64}}`, `Array{Dict{Int64,Int64}}`, and a few other permutations seem to work fine.

I dug a little bit and I think this has something to do with it and is preventing the function from accessing the set:
```julia
julia> Base.allocatedinline(Dict{Int,Int})
false

julia> Base.allocatedinline(Vector{Int})
false

julia> Base.allocatedinline(Set{Int})
true
```

which is defined here
https://github.com/JuliaLang/julia/blob/e4f79b7167312dab649218b53b84c0829ea0c103/base/array.jl#L157

### LINKED ISSUE #41157: unhappy codegen handling of invalid tuples
MWE for a codegen bug observed "in the wild"
```
julia> f(a, b) = a[1] = b[1]
f (generic function with 1 method)

julia> @code_llvm optimize=false raw=true f(Tuple{Int}[], Tuple{Union{}}[])
julia: /data/vtjnash/julia/src/intrinsics.cpp:287: llvm::Value* emit_unboxed_coercion(jl_codectx_t&, llvm::Type*, llvm::Value*): Assertion `to->isIntOrPtrTy() || to->isFloatingPointTy()' failed.

signal (6): Aborted
in expression starting at REPL[3]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fc43c965728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
emit_unboxed_coercion at /data/vtjnash/julia/src/intrinsics.cpp:287
emit_unbox at /data/vtjnash/julia/src/intrinsics.cpp:353
typed_store at /data/vtjnash/julia/src/cgutils.cpp:1485
emit_builtin_call at /data/vtjnash/julia/src/codegen.cpp:2984
emit_call at /data/vtjnash/julia/src/codegen.cpp:3692
emit_expr at /data/vtjnash/julia/src/codegen.cpp:4509
emit_ssaval_assign at /data/vtjnash/julia/src/codegen.cpp:4160
emit_stmtpos at /data/vtjnash/julia/src/codegen.cpp:4402 [inlined]
emit_function at /data/vtjnash/julia/src/codegen.cpp:7191
jl_emit_code at /data/vtjnash/julia/src/codegen.cpp:7564
```

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-06/03/SplittablesBase.1.7.0-DEV-9f32653992.log

split from https://github.com/JuliaLang/julia/issues/40065#issuecomment-853895364

(prior to f313b08bc76cd8b9ffd413172674f215ed40dfed, we didn't have an assert here and would just return Undef)

### LINKED ISSUE #41489: 1.7-beta2: type instability for matrix multiplication
Hi, I encountered a type instability in matrix multiplication

```
julia> A=Rational[1 1 1; 2 2 2; 3 3 3]
3×3 Matrix{Rational}:
 1//1  1//1  1//1
 2//1  2//1  2//1
 3//1  3//1  3//1
```

On 1.7-beta2:
```
julia> A*A
3×3 Matrix{Any}:
  6//1   6//1   6//1
 12//1  12//1  12//1
 18//1  18//1  18//1
```

On 1.6.1:
```
julia> A*A
3×3 Matrix{Rational}:
  6//1   6//1   6//1
 12//1  12//1  12//1
 18//1  18//1  18//1
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #41238
- [x] #41375
- [x] #40628
- [x] #40738
- [x] #41298
- [x] #41483
- [x] #41321
- [x] #41493
- [x] #41494
- [x] #41501
- [x] #41495
- [x] #41491
- [x] #41496
- [x] #41197
- [x] #41492
- [x] #41441
- [x] #41507
- [x] #41531
- [x] #41543
- [x] #41544
- [x] #41545
- [x] #41549
- [x] #41559
- [x] #41556
- [x] #41551
- [x] #41530
- [x] #41516
- [x] #41583
- [x] #41571
- [x] #41515
- [x] #41594
- [x] #41563
- [x] #41196
- [x] #41591
- [x] #41201
- [x] #41610
- [x] #41286
- [x] #41596
- [x] #41617
- [x] #41614
- [x] #41622
- [x] #41606
- [x] #41651
- [x] #41653
- [x] #41657
- [x] #41658
- [x] #41646
- [x] #41660
- [x] #41648
- [x] #41645
- [x] #41667
- [x] #41682
- [x] #41541
- [x] #41698
- [x] #41700
- [x] #41706
- [x] #41629
- [x] #41641
- [x] #40382
- [x] #41619
- [x] #41587
- [x] #41676
- [x] #41710
- [x] #41722
- [x] #41752
- [x] #41595
- [x] #41479

Non-merged PRs with backport label:
- [ ] #41733
- [ ] #41711
- [ ] #41707
- [ ] #41695
- [ ] #41687
- [ ] #41659
- [ ] #41650
- [ ] #41602
- [ ] #41452
- [ ] #41447
- [ ] #41325
- [ ] #41269
- [ ] #41228
- [ ] #41091
- [ ] #41041

### CODE REVIEW

**Comment by BioTurboNick** [comment]
So this doesn't get lost: Consider marking #41201 for backport too. It's the last piece of the set of fixes to `hvncat` intended to go together.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.7")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by tkf** [comment]
This error

> `==13373==You are trying to dlopen a /cache/build/amdci5-0/julialang/julia-release-1-dot-7/tmp/test-asan/asan/usr/bin/../lib/libopenblas64_.so shared library with RTLD_DEEPBIND flag which is incompatible with sanitizer runtime (see https://github.com/google/sanitizers/issues/611 for details). If you want to run /cache/build/amdci5-0/julialang/julia-release-1-dot-7/tmp/test-asan/asan/usr/bin/../lib/libopenblas64_.so library under sanitizers please remove RTLD_DEEPBIND from dlopen flags.`
>
> --- https://buildkite.com/julialang/julia-release-1-dot-7/builds/23#ea03010c-a544-4bba-bd0a-c48293797b83/190-1104

indicates that libblastrampoline does not support `LBT_USE_RTLD_DEEPBIND` flag.

Backporting #41530 would require backporting #41522 which updated libblastrampoline.

Given the trouble we are experiencing with ASN on CI #41606, maybe it's better to not backport #41530, to avoid complicating the release process?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-882508322) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8d7a4ae_vs_96386f9/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-882508434) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8d7a4ae_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BetterFileWatching", "CartesianGrids", "CombinedParsers", "Convex1d", "Diagonalizations", "FlashWeave", "GenericSchur", "Jaynes", "JuliaInterpreter", "KLDivergences", "LoggingExtras", "MRIgeneralizedBloch", "MusicManipulations", "Qaintessent", "QuadEig", "ReservoirComputing", "VideoIO"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-883139526) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8d7a4ae_vs_96386f9/report.md).

**Comment by aviatesk** [comment]
@KristofferC can we backport https://github.com/JuliaLang/julia/pull/41633 (it's okay if that's hard)

**Comment by KristofferC** [comment]
I mean, we probably theoretically can but what's the reason? 1.7 is starting to drag out on time and I'd personally feel it makes sense to be quite conservative with backports, especially those that have recently been merged to master. They can always go into 1.7.1 when they have the extra benefit of being tried out on master for some time.

**Comment by StefanKarpinski** [comment]
We should definitely not backport a compiler refactor — that's very much a high risk thing one doesn't backport. Refactor implies: no functional change, including no bugfixes. Is there some reason backporting makes sense?

**Comment by aviatesk** [comment]
My motivation was, since I changed the signature of `Core.Compiler.add_backedge!` in that PR, now I need to keep [this dirty code](https://github.com/aviatesk/JET.jl/blob/8d52f8650aaffaab94a1958188e4fa1bb709a9f3/src/abstractinterpretation.jl#L130-L182) for JET to be compatible between v1.7 and future versions..

But I also understood this is a hasty suggestion and there is a certain risk involved with it, and now I just agree to not backport that PR (those compatibility costs are what I have to pay for at some point as far as I reuse `Core.Compiler` after all). Thanks for your pointers !

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-886539240) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e04e3e1_vs_96386f9/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AdaOPS", "AlphaStableDistributions", "BayesianBlocks", "BlobTracking", "CartesianGrids", "CorrelationFunctions", "Dispatcher", "DistributedJets", "DistributedOperations", "ECharts", "EFTfitter", "EcoSISTEM", "Enigma", "FixedPointNumbers", "GadgetIO", "GenericSchur", "GeometryBasics", "HalfIntegers", "ImageInpainting", "ImageTracking", "Images", "JuliaInterpreter", "LassoPlot", "LowLevelParticleFilters", "MCMCChain", "MatrixEquations", "MixedModelsPermutations", "MusicManipulations", "ParallelKMeans", "Revise", "SPHtoGrid", "Scalpels", "SimpleSDMLayers", "StaticRanges", "StatsPlots", "SymbolicRegression", "TensorBoardLogger", "TightBinding", "Transducers", "TreeParzen", "Unitful", "VideoIO", "Winston", "YAActL"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-887036894) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e04e3e1_vs_96386f9/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AdaOPS", "AlphaStableDistributions", "BayesianBlocks", "BlobTracking", "CartesianGrids", "CorrelationFunctions", "Dispatcher", "DistributedJets", "DistributedOperations", "ECharts", "EFTfitter", "EcoSISTEM", "Enigma", "FixedPointNumbers", "GadgetIO", "GenericSchur", "GeometryBasics", "HalfIntegers", "ImageInpainting", "ImageTracking", "Images", "JuliaInterpreter", "LassoPlot", "LowLevelParticleFilters", "MCMCChain", "MatrixEquations", "MixedModelsPermutations", "MusicManipulations", "ParallelKMeans", "Revise", "SPHtoGrid", "Scalpels", "SimpleSDMLayers", "StaticRanges", "StatsPlots", "SymbolicRegression", "TensorBoardLogger", "TightBinding", "Transducers", "TreeParzen", "Unitful", "VideoIO", "Winston", "YAActL"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41499#issuecomment-890840231) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/f8bae15_vs_96386f9/report.md).

**Comment by tkf** [comment]
@KristofferC @ararslan I just noticed beta4 was not released. I wonder if it is by oversight?

https://github.com/JuliaLang/julia/releases
https://julialang.org/downloads/

**Comment by ararslan** [comment]
We're waiting on being able to code sign Windows binaries again, Elliot is looking into it

**Comment by tkf** [comment]
Ah, I see. Thanks for the clarification.

**Pull request merged**
