### PR TITLE
Consolidate a few LU tests

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by KristofferC** [comment]
This is not an improvement in my opinion.

**Comment by ViralBShah** [comment]
Why not?

**Review by fredrikekre — COMMENTED** [review]
Change looks fine, no opinion about if this is better or worse.

**Comment by KristofferC** [comment]
I posted about it in the other PR doing the same thing but kept it short here to not spread the discussion.

**Comment by KristofferC** [comment]
To give a bit more context to my earlier comment (which in hindsight was a bit "direct") I think that too much DRY in tests can increase coupling and make it harder to get an overview of the state when the test is run. Instead of putting tests in the same loop to make sure they test the same types, in my opinion, having a `TEST_LU_TYPES` that each test loop over independently is preferred.

However, this is just my opinion and I don't feel very strongly about it so I am in no way "blocking" this PR from getting merged.

**Comment by andreasnoack** [comment]
Will merge since it seems like we decided this was the direction we wanted to go in the two similar PRs.

**Pull request merged**
