### PR TITLE
Add NEWS entry for #28156: add `splitpath(p)`

### PR DESCRIPTION
**Pull request by NHDaly**

### CODE REVIEW

**Comment by NHDaly** [comment]
Something like this?

It was a bit confusing cause the NEWS.md file currently still looks like it's for the `1.0.0` launch, not `v1.0.1`. Should I have based it off of a different branch or something? Thanks! :)

**Comment by StefanKarpinski** [comment]
Do we actually have a joinpath method that takes an array?

**Comment by NHDaly** [comment]
Eep! Thanks Stefan, I did that late at night and didn't actually think to check.. -_- thanks. Corrected it to `joinpath(parts...)`, which is the description in its docstring.

I'm still about confused about whether this is the right place to make this change though. Could you comment on that? Thanks!

**Comment by StefanKarpinski** [comment]
It's a bit unclear—we're going to have to figure out what the right headings for release notes are as part of our new release process. This seems fine for now; we can always rearrange later.

**Comment by NHDaly** [comment]
Okay cool, works for me!

In particular, I was confused because reading that file, it seems like it's still referring to the julia v1.0.0 release, even though now I guess master would be v1.0.2? Or v1.1.0 even?

AND that file looks different in both the `v1.0.0` and `v1.0.1` tags than it does at `master`:
https://github.com/JuliaLang/julia/blob/v1.0.0/NEWS.md
https://github.com/JuliaLang/julia/blob/v1.0.1/NEWS.md

So that's why i'm asking. Is the NEWS.md file on `master` supposed to reflect the last major/minor release, such that this PR shouldn't be attempting to merge into master, but rather into some development branch? Thanks, and sorry for the confusion! :)

**Comment by StefanKarpinski** [comment]
Ah yes, this will actually only go out in Julia 1.1 since it's a new feature.

**Comment by Sacha0** [comment]
> Ah yes, this will actually only go out in Julia 1.1 since it's a new feature.

Agreed, looks like the v1.0.0 release notes should move to history, and v1.1.0 release notes should replace them, with this entry under the latter? Best!

**Comment by JeffBezanson** [comment]
#29490

**Comment by NHDaly** [comment]
(Thanks Jeff!)

**Comment by NHDaly** [comment]
Okay, this is rebased.

Merge away! Thanks

**Pull request merged**
