### PR TITLE
RFC: More customizable testset interface (start method added)

### PR DESCRIPTION
**Pull request by robertfeldt**
With a very small change to the AbstractTestSet interface we can allow test sets to control whether they should run the tests in their set multiple times. This allow for random testing, property-based testing (QuickCheck style) and many more types of automated testing.

I also think it makes sense from the viewpoint of elegance; the AbstractTestSet already has a finish method and it seems symmetric it should also have a start method.

I pondered adding additional methods to give more fine-grained control to the test set but ultimately decided against it in order for having a small interface to test sets and changing as little as possible in base/test.jl.

The added tests shows one typical use case, i.e. a custom test set with a fixed number of repetitions. In this specific case a similar effect could be achieved by using an (existing) @testset for loop but the start method is needed for more refined and advanced control, for example by adaptively deciding on the number of repetitions based on coverage, sequential testing for probabilistic properties etc.

If there is interest in making base/test.jl more flexible I would like, in future PR's, to generalize the reporting methods of the current DefaultTestSet so it can more easily be reused by custom test sets defined by the user.

### CODE REVIEW

**Comment by tkelman** [comment]
It's not ideal to use the `start` name for this method, since this isn't an iterator.

**Comment by robertfeldt** [comment]
Thanks, good point. :) Maybe `starttests` or `runtests` is better...

**Comment by robertfeldt** [comment]
Or even `shouldrun`? Naming help needed... ;)

**Comment by robertfeldt** [comment]
`shouldrun` makes some sense if we later add a `skip` option to the DefaultTestSet which user can set to `true` if the testset should be skipped.

**Comment by robertfeldt** [comment]
If one prefers two different methods maybe have one named `setup` which is called right after adding the testset to the stack, and then have `shouldrun`to indicate that it wants to run more (which the framework can choose to ignore, for example if there is a top-level timeout to adhere to).

**Comment by StefanKarpinski** [comment]
Does it make sense to have some kind of test iterator type which test sets implement? Then making these actual iterator methods would make sense.

**Comment by robertfeldt** [comment]
@StefanKarpinski : Hm, longer-term I've been thinking that an iterator over the test results would be useful.

OTOH, I think some custom test set implementation might choose not to save Pass results since there might be *very* many of them (while often only quite few Fail results). For example, in our in-house test data generator package the automated testing is scaled up based on the available test time; it can lead to many, many test passes...

Overall though, to take adaptive and sequential decisions on where to put test effort we need richer "hooks" for custom test sets into the Base.Test architecture. So aside from the method naming issue is there support for the general thinking in this RFC PR? If we can still keep base/test.jl quite simple and straightforward with clean and compact interfaces I'd rather see that than putting things in many different test packages; I think most future Julia testing will use and be inspired/based on Base.Test so it's important what is in there imho. 

We need to find a balance between keeping it simple and light while still providing enough power for extensions. If there is support for this RFC, or at least its general "philosophy", I'd like to then propose and test out a few other changes:

1. Generalise the test report printing code to a TestReporter hierarchy that can be used also by custom test sets
2. A simple TestPredicate type hierarchy which allows more control over when the predicate is evaluated (right away or on testset finish/exit time), on what (accumulated values of an expression from multiple runs of the testset), as well as how failure/error is reported
3. More details about sub-expressions of the failing expression in a test (knowing the value a variable had can be useful in pinpointing the failure; its not always enough to know what the values of the lhs or rhs in the comparison were)

While this may sound like a lot I think it can be done quite simply and compactly with just minor changes to the current code. If we can find a good trade-off between power/customization and simplicity it might be worth it if it helps the community do more powerful testing over time.

**Comment by tkelman** [comment]
That plan sounds reasonable, as long as it can be accomplished as a series of small incremental changes.

**Comment by robertfeldt** [comment]
Thanks Tony. Do you suggest I add commits to this branch so they are considered together or what's the "standard" way?

**Comment by tkelman** [comment]
This branch needs a bit of squashing, but yes let's accomplish the first small piece that you'd like to get merged within this PR.

**Comment by jkroso** [comment]
I'd prefer to just create a standardized place for test results to go. Kind of like STDIO but it may aswell be proper data not text. Then Base.Test wouldn't need to be extensible. Stuff like `RepeatingTestSet` could then be implemented completely independently of Base.Test while still sharing test reporters.

**Comment by robertfeldt** [comment]
Yes, but we need a few hooks into the current code so that we can invoke `RepeatingTestSet` and friends.

**Comment by jkroso** [comment]
I don't see any reason why it needs to be invoked by Base.Test

**Comment by robertfeldt** [comment]
I don't see how it can repeat without something like what I called `start` above (but propose to change to `should_run`). I wouldn't want to have to redefine the `@testset` macro in order to implement `RepeatingTestSet`.

**Comment by jkroso** [comment]
Well loosely speaking with a standard place to put all test results a `RepeatingTestSet` would just dump a bunch of information for the test reporter to look at. It might be implemented something vaguely like this:

```julia
macro repeating_test(iterations, test)
  write(results, SetStart(name))
  for i in i:iterations
    write(results, Result($test))
  end
  write(results, SetEnd(name))
end
```

It might still be worth implementing what you have proposed in this PR but only to reduce code duplication. I think...

**Comment by robertfeldt** [comment]
But we have added the `@testset CustomTestSet testassertionblock` construct to allow custom test sets but the control of invoking the tests (in `testassertionblock`) is kept in the `@testset` macro. I don't see the real value of writing new CustomTestSet's if I also have to rewrite the `@testset` macro in order to invoke the testassertionblock many times. So, to me, it seems we must add some logic so that either `@testset` macro calls out to allow CustomTestSet to invoke the test block or at least give CustomTestSet the power to more precisely control the invocation.

**Comment by robertfeldt** [comment]
One idea would be to reuse the record method also to record/emit TestSet events such as TestSetFinish, TestSetRunStart and TestSetRunEnd. This way we could skip the finish method and just have `record` and `should_run`.

**Comment by robertfeldt** [comment]
Given your concerns @jkroso I've given this some more thought and think that a better way is to supply a block to a run method in the TestSet and then it can choose how many times to run the block etc. This takes away the nruns local counter var which was a bit inelegant.

If we also fold the finish method into instead using record with a new TestingEvent to indicate which event has been triggered the interface to AbstractTestSet can be only `record` and `run`.

**Comment by tkelman** [comment]
`record` and `run` sounds like it could be a promising api

**Comment by jkroso** [comment]
Yea I like it too. Though I don't mind if the `finish` method stays and we add a `test_set_start` method since it's pretty much equivalent to passing distinct event types to `record`

**Comment by robertfeldt** [comment]
Hmm, I thought I got this right but by wrapping the block with tests in a function that is supplied to the `run` method the block will not be evaluated in the `@testset` macro call environment. This would be too big a step to take imho. Any ideas welcome. The problem is showcased below in a simplified form and is that the call to `@t2` doesn't change `a` which might be expected if this was a testset.

````
type Runner; end # Dummy just to have same code structure
run(f::Function, r::Runner) = f()

macro t1(ex)
  quote
      $(esc(ex))
  end
end

macro t2(ex)
  quote
    r = Runner()
    run(r) do
      $(esc(ex))
    end
  end
end

a = 3

@t1 begin
  a += 1
end
@show a

@t2 begin
  a += 1
end
@show a
````

**Comment by robertfeldt** [comment]
I guess we could get around this by having the interface be only `record` (as before) and `run_code(::Type{AbstractTestSet}, tests::Expr)` so that each test set can specify the code to be used when running its `tests`. The `@testset` macro would then splice in this code in between the `push_testset()` and `pop_testset()` calls. It might be a bit messy since it needs to mix compile-time and run-time since it needs access to the actual TestSet type to get its run code but with some debugging it should be doable, I guess.

Not the most elegant but very customizable and I guess people writing their own `CustomTestSet` need to know what they are doing anyway. I would argue for this or to go back to the original `should_run` proposal and only allow the test set to control the number of times its tests are run.

Any thoughts @jkroso or @tkelman ?

**Comment by robertfeldt** [comment]
As pointed out by Cedric on julia-users mailing list maybe we shouldn't even allow test code in `@testset` blocks to have an effect outside of the block?

https://groups.google.com/forum/#!topic/julia-users/jVm1JkPDJK8

**Comment by jkroso** [comment]
I think this scoping problem is a pretty weird part of Julia since this works

```julia
inc = (function a()
  b = 1
  ()->b+=1
end)()
inc() # => 2
```

And you can make you example work using `global`

```julia
@t2 begin
  global a += 1
end
```
So perhaps a solution could be to automatically add `global` to any top level variables that get referenced in `@testset`

**Comment by robertfeldt** [comment]
Hmm, doesn't feel right to start manipulating the test block too much; risk we get into corner cases... What if we just require TestSets that are args to `@testset` macro should be fully qualified? Then we can always eval to get their type and take it from there.

**Comment by jkroso** [comment]
I'm not sure what you mean. Can you give an example of the API when fully qualified.

**Comment by robertfeldt** [comment]
Ok, I mean that if your `CustomTestSet` is defined in a module `MyModule` you would have to write

`@testset Mymodule.CustomTestSet`

or make sure it is imported into main since the code needs to be able to `eval` that first arg to a test set type. So if someone did not, like in this contrived example:

````
module MyModule
type CustomTestSet <: Base.Test.AbstractTestSet
...
end

@testset CustomTestSet "sgdg" begin
...
end
end
````

I would have to throw an error since `eval(:CustomTestSet)` would throw an `UndefVarError` since `eval` always evaluates in Main (and we cannot use `MyModule.eval` since the module is not yet defined). But it seems a small price to pay. I think my main proposal is for the AbstractTestSet API to be:

1. `record` for recording testing results as well as testing events, the testset can decide how to handle them differently based on multi-dispatch
2. `run_code` for creating the code to splice into the code that @testset expands to

and that we keep `finish` around as a default that `record(::AbstractTestSet, ::TestsetEventFinish)` calls for now but that we make it obsolete in order to have a small interface long-term.

**Comment by jkroso** [comment]
But resolving the testset type already works doesn't it? What's changing that is causing that to break?

Also with regards to that `global` hack I think it could be done robustly without a ton of code. Even with tuple destructuring. I'd be happy to give it a go anyway. Or even not supporting global variable mutation would be okay IMO.

**Comment by toivoh** [comment]
But what if the `@testset` macro is not invoked in a global scope? 

Also, macros should pretty much never use `eval`, they should rearrange the code that is passed to them (or they will likely be broken). What is the reason to use `eval` in this macro?

**Comment by robertfeldt** [comment]
Yes @toivoh would be great with your input here. The goal is to give much more control to custom TestSets on how the block of tests is executed. The initial proposal of this PR was:

1. Add one or a few methods to AbstractTestSet that allows custom test sets more control over the execution of the test block. A basic need is to control how many times to run the tests for example for random testing, QuickCheck-style testing etc.

The pro with 1 is that it is easy and that people can just implement the required interface to get more control. Downside is that we have to come up with a rich enough interface to give enough control for what people will want to do. The next approach discuss here has been:

2. Let each CustomTestSet control which expr is spliced in to the expr returned by the `@testset` macro. This allows almost endless customizability (and possibility to mess up) but (at least seems to) require a way to call a method on the type of CustomTestSet, like `run_tests_expr(::Type{MyTestSet}, testblock::Expr)`, in the `@testset` macro in order to get the expr back to splice in.

The pro is that we need not add a lot of methods to the AbstractTestSet interface, it allows a lot of customizability. Downside is that we need to `eval` the name of the test set in order to be able to call `run_tests_expr` which, we have found, leads to problems with the scope etc.

A 3rd possibility I can see is that people must redefine their own `@testset` macro if they have special needs but then I don't see the real value of allowing people to add CustomTestSet's if they can basically only change how things are reported and not how the actual testing should happen.

Would be great with advice on a good design here. I think it will be quite important for the community if people can easily extend Base.Test rather than implement a plethora of different testing tools and packages that can't easily share a similar infrastructure.

**Comment by robertfeldt** [comment]
Maybe generated functions can be used in some way? But I still don't see how we can avoid an eval since if we need to be able to change what the testset macro is expanded to.

**Comment by robertfeldt** [comment]
@jkroso Yes, in current `@testset` macro the resolving works because it happens at runtime so in the scope where `@testset` was called. If we want to go with design (2) in my post above we need the type of the test set at macro compile time rather than runtime. This introduces the scoping problem.

**Comment by robertfeldt** [comment]
A fourth way (or really a modification of (2)) above would be if CustomTestSet can register with the `@testset` macro so basically update a Dict in Base.Test which maps CustomTestSet names to their type. This way the `@testset` macro can call run_tests_expr(::Type{MyCustomTestSet}, ::Expr) method without having to eval the name of the custom testset. Too hackish?

**Comment by toivoh** [comment]
I must admit that I haven't looked into this issue in depth, but here's a few thoughts anyway:
* Macros are for saving typing. The first step of redesigning the `@testset` macro should be to consider what the typed-out version should be.
* If there's some specific testing need that needs to generate different code than `@testset`, I think it should be a different macro. But the infrastructure that `@testset` uses could be made available to make it easy to implement. 
* The scoping of code wrapped in `@testset` should be well defined, and always be the same. If it introduces a scope, then `@testset let` might be preferable to `@testset begin`.
* If choosing the number of times to run a test set is really the only issue, then maybe `@testset` could wrap the code in a `while` loop, and let the test set class supply the condition for when it should terminate. Does that seem like it would provide enough freedom?

**Comment by robertfeldt** [comment]
Thans a lot @toivoh for your input. I will keep this macro design ides/"rules" more clearly in mind in the future. Your final proposal, with a while loop, was exactly my initial proposal for this PR, i.e. a start method called like:

```
nruns = 0
while start(testset, nruns)
# call the test block here
nruns += 1
end
```

We decided in this thread to call it something else than start though. I will change to `should_run` and then hopefully we can get this PR merged. I guess I need to document it somewhere also, not sure where that is done.

**Comment by robertfeldt** [comment]
Ok, I do get the problems in relation to scope on my machine after having updated to latest version of master. Very weird. How can other changes in master branch (base/test.jl ro test/test.jl) have not been changed lead to scope problems with this PR? I don't understand it. Also, wrapping the test block in a while loop should not create a scope problem since the test block is still escaped and inserted right into the expanded expr.

Still, we need to add tests to detect the current scoping of testset blocks, did this in a separate PR:
https://github.com/JuliaLang/julia/pull/15148

**Comment by robertfeldt** [comment]
Ok, given the new tests in https://github.com/JuliaLang/julia/pull/15148 I managed to debug this and the scoping issue only happens if the testset is assigned to a variable:

```
counter = 0
@testset "this is ok" begin
  counter += 1
end
ts = @testset "this is not ok, we get UndefVarError" begin
  counter += 1
end
```

**Comment by robertfeldt** [comment]
I moved the final discussed solution (with tests and doc updates) to the new branch so will close this one now, please refer to:
https://github.com/JuliaLang/julia/pull/15148

**Pull request closed without merging**
