### PR TITLE
Export nonmissingtype

### LINKED ISSUE #30657: Export Base.nonmissingtype
It would be nice to have this name documented and exported. It should be used often in stats packages.

The old way with `Missings.T` is not as descriptive.

### PR DESCRIPTION
**Pull request by juliohm**
Fix #30657

### CODE REVIEW

**Comment by juliohm** [comment]
I don't have time at the moment to work on this. Please feel free to improve the PR.

**Comment by juliohm** [comment]
Can this be merged into Julia 1.2 or Julia 1.3?

**Comment by vtjnash** [comment]
Perhaps should wait for #31602?

**Comment by StefanKarpinski** [comment]
Too late for 1.2, can go into 1.3. As long as #31602 also goes into 1.3, this is fine 👍

**Comment by JeffBezanson** [comment]
From #31602, there is a question on whether this should check to make sure it could do anything; e.g. `nonmissingtype(Any) == Any`, which might violate your assumptions.

Mostly this needs docs though.

**Comment by StefanKarpinski** [comment]
What about calling this `subtract_missing` to match `Base.subtract_singletontype`?

**Comment by JeffBezanson** [comment]
Thank goodness `subtract_singletontype` isn't exported :) That is a pretty rancid name/concept.

**Comment by StefanKarpinski** [comment]
I find `subtractmissing` to be a clearer name for what this does than `nonmissingtype` which seems like it might be an assertion or something? I would have no immediate guess about what a function by that name would do. The name `subtractmissing` at least gives me a hint.

**Comment by juliohm** [comment]
I personally find `subtractmissing` confusing. It may read well for core developers, but end users will ask why "subtraction"? I'd even shorten the name further and write `nonmissing`. The "type" suffix is intuitive from the call? `nonmissing(T)`

**Comment by JeffBezanson** [comment]
Please add docs and news, then triage is ok with the name `nonmissingtype`.

**Comment by juliohm** [comment]
Please feel free to add docs and news to this PR.

**Comment by JeffBezanson** [comment]
Docs added and merged.

**Pull request closed without merging**
