### PR TITLE
Fix plus and minus for LinSpace, and other missing methods

### LINKED ISSUE #12195: BUG: arithmetic with linspace incorrect
Consider:

```
julia> x = linspace(0.01, 0.99, 12)
linspace(0.01,0.99,12)

julia> collect(1 - x)
12-element Array{Float64,1}:
  0.0
 -0.0890909
 -0.178182
 -0.267273
 -0.356364
 -0.445455
 -0.534545
 -0.623636
 -0.712727
 -0.801818
 -0.890909
 -0.98

julia> 1 - collect(x)
12-element Array{Float64,1}:
 0.99
 0.900909
 0.811818
 0.722727
 0.633636
 0.544545
 0.455455
 0.366364
 0.277273
 0.188182
 0.0990909
 0.01
```

### PR DESCRIPTION
**Pull request by yuyichao**
Test coming later.

I make `LinSpace` and `FloatRange` promotes to `LinSpace` since the type of `linspace(...) + FloatRange(...)` is the same with `linspace` (i.e. `Array`) before. @StefanKarpinski does this look ok?

Close #12195

### CODE REVIEW

**Comment by yuyichao** [comment]
This also fixes a small type stability issue https://github.com/JuliaLang/julia/commit/59cdac6e6a7d07d849e37f10ed5deed6029a1479#diff-c5053a63cd3df77d9079e95f29f350adL210. 

Actually should this be called type stability issue? The type of `p` is always known at each point but type inference still insist on using the same local variable for them...

**Comment by yuyichao** [comment]
Test added. AppVeyor 32 is having a strange build problem?

**Comment by JeffBezanson** [comment]
That build failure is exceedingly strange.

**Comment by yuyichao** [comment]
Is that file generated temporarily at some point?

**Comment by yuyichao** [comment]
Restarted the build. Just for the record, the error is [here](https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.6942/job/w79o4e96lhh765n3#L832).

**Pull request merged**
