### PR TITLE
fix #27352, disallow `print`/`string` of `nothing`

### LINKED ISSUE #27352: Interpolation of `nothing` should be an error
Now that we're firming up our notion of what `nothing` and `missing` actually mean, we should probably semantically enforce them a little bit more.  Example:

`Sys.which(cmd)` will return `nothing` if the given `cmd` cannot be found on the `PATH`.  This makes it easy to define a hierarchy of commands: `coalesce(Sys.which("curl"), Sys.which("wget"))`, etc...  However, if the user then interpolates the result into a `Cmd`, it makes sense that we should error out.

[Jeff suggested](https://github.com/JuliaLang/julia/pull/27298#issuecomment-392808638) disallowing all kinds of `print()` or `string()` conversion of `nothing`, leaving only `repr()`.  I tend to agree, despite that this has the potential to be a quite breaking change.

I would also like to suggest that `missing` get a similar treatment, as it is a subtly different but largely identical concept.

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #27352

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
Intended to make this comment visible 2 days ago, but apparently it got stuck in Github's review queue :(

**Comment by iamed2** [comment]
This is a breaking change to the beta; this should at very least be deprecated first. This changes makes every `print` of a `Union{T, Nothing}` possibly invalid. Given that `print` and `show` sometimes have different behaviour (and this behaviour can be introduced by the user for any user-defined type), there are going to be cases in user code where this happens. 

This also contradicts the documented behaviour of `print`:

> Write to io (or to the default output stream STDOUT if io is not given) a canonical (un-decorated) text representation of a value if there is one, otherwise call show.

By that definition, there doesn't seem to be any room for a case where `print` itself would error, it should always call `show` if it doesn't know how to handle something.

**Comment by StefanKarpinski** [comment]
What if the show fallback were to wrap its output in backticks or something to indicate that it was not just a plain string? That would mean that the printing of nothing would be sufficiently weird to avoid any chance of it accidentally being spliced into a command or something in a way that calls a command.

**Comment by JeffBezanson** [comment]
I don't think that helps much, except in that it's much less likely for a filename with backticks to exist. Or we could handle this by only giving an error in backtick interpolation, instead of `print` in general.

**Pull request merged**
