### PR TITLE
Remove Windows Vista from manifest

### PR DESCRIPTION
**Pull request by musm**
partially address https://github.com/JuliaLang/julia/issues/21424

### CODE REVIEW

**Comment by tkelman** [comment]
I don't think this is necessary or solves any actual problems.

**Comment by musm** [comment]
Are we keeping vista support or not? The linked issue suggests to drop all mentions of vista.

**Comment by tkelman** [comment]
Has anyone tested whether or not it currently works? The LLVM release notes don't necessarily tell us whether that matters for what we use.

**Comment by musm** [comment]
> Has anyone tested whether or not it currently works? The LLVM release notes don't necessarily tell us whether that matters for what we use.

yes it does

http://releases.llvm.org/3.8.1/docs/ReleaseNotes.html
"With this release, the minimum Windows version required for running LLVM is Windows 7. Earlier versions, including Windows Vista and XP are no longer supported."

**Comment by tkelman** [comment]
I'm saying the LLVM release notes don't tell us whether or not Julia starts and works, only testing it would answer that.

**Comment by musm** [comment]
I don't have vista machine to test.

**Comment by tkelman** [comment]
Then I don't think we should remove this until it's been tested. If it works, we should leave it. If testing demonstrates that it's broken for other reasons then sure we can delete these two lines, not that there's any advantage to doing so.

**Comment by vtjnash** [comment]
I think we should trust that since LLVM said they were going to drop support in order to use newer APIs, we can safely copy that into our docs. I doubt whether anyone has a copy of Vista anymore to be concerned with.

**Comment by musm** [comment]
> I think we should trust that since LLVM said they were going to drop support in order to use newer APIs, we can safely copy that into our docs. I doubt whether anyone has a copy of Vista anymore to be concerned with.

That was my thinking as well

**Comment by musm** [comment]
Microsoft has also dropped Vista support as of April 11, 2017

**Comment by tkelman** [comment]
That wasn't the case with libgit2 and xp.

**Comment by tkelman** [comment]
Docs are one thing, but intentionally breaking build code isn't necessary.

**Comment by musm** [comment]
Ok well I don't really care tbh, I thought I'd open this to address the linked issue, but apparently it's not an issue

**Comment by musm** [comment]
Can we then close the original issue, so that we don't waste more time on the problem ?

**Pull request closed without merging**
