### PR TITLE
Remove Float promotion and converions of 'Char' type now that Char !<: Integer

### PR DESCRIPTION
**Pull request by jakebolewski**
See #9725.

### CODE REVIEW

**Comment by ivarne** [comment]
Great effort on cleaning debris!

I fully support removing promotion, but I don't see why `convert(Float64,'a')` should fail. If someone wants a Char point as a Float, it seems strange to require `convert(Float64, convert(Int, 'a'))`

**Comment by jakebolewski** [comment]
You almost never want to convert a `Char` to a floating point.  Removing implicit conversions (a source of logic bugs) to support this marginal use case seem like a win.  In 0.4 this would be `Float(Int('C'))` which is not so bad.

**Comment by ivarne** [comment]
Hmm. You're probably right that that conversion is much less common than logic errors this will catch.

**Comment by nalimilan** [comment]
I'm not completely convinced that forbidding conversions that are possible and logically correct is a good thing, even if they are not really useful in practice. The transitivity rule that `(A can be directly converted to B) && (B can be directly converted to C) => (A can be *directly* converted to C)` looks logically hard not to follow. But of course this could easily be re-added later.

I wonder whether this may reflect a deeper issue that allowing conversion from `Char` to `Int` can be a bit dangerous.

**Comment by ivarne** [comment]
We need a way to convert `Char` to `Int`, so the alternative would be a separate function (eg. `char2int`), but that seems a little too pedantic in my opinion.

**Pull request merged**
