### PR TITLE
Fix build failure from `WITH_DTRACE` on Darwin

### PR DESCRIPTION
**Pull request by carlocab**
Building `WITH_DTRACE=1` off of master fails with syntax errors from
`uprobes.d` on macOS. I've added a modified `uprobes.d` that should work
on Darwin and amended `src/Makefile` to use the appropriate one
depending on the platform.

For reference, the error from building without this change is:

    dtrace: failed to compile script /private/tmp/julia/src/uprobes.d: line 5: syntax error near "probe"
    make[1]: *** [uprobes.h.gen] Error 1

I'm not super familiar with Julia's `Makefile`s, so there might be a nicer way to do what I'm trying to do here. Happy to change this where needed.

CC @vchuravy

### CODE REVIEW

**Comment by vchuravy** [comment]
It seems that on Linux, the file for darwin works as well.

` dtrace -G -s src/uprobes-darwin.d -o uprobes.o`

So maybe we can get away with just one file?

**Comment by carlocab** [comment]
I suspected that might be the case, but had no convenient way of testing it. That works for me; will push that change shortly.

**Comment by carlocab** [comment]
Pushed the suggested change.

**Comment by vchuravy** [comment]
Thanks!

**Pull request merged**
