### PR TITLE
use permutation rather than sort for not in place quantile

### PR DESCRIPTION
**Pull request by matthieugomez**

### CODE REVIEW

**Comment by tkelman** [comment]
What's the benefit of this? This is copy-pasting most of the function (with 3-space indent instead of 4) which is a bad sign. `isnan(v[end])` would also need to change if `v` is not sorted.

**Comment by matthieugomez** [comment]
I thought it was faster to create an int vector rather than copying a float vector.

**Comment by tkelman** [comment]
There might be types where that could be the case, BigFloats or user-defined number types. I don't think this needs to be closed, but it could be improved a little.

**Comment by nalimilan** [comment]
You'll probably have to come up with some benchmarks showing the impact of this change with a few different types if you want this kind of change to be accepted.

**Pull request closed without merging**
