### PR TITLE
Propagate more errors in Distributed test

### PR DESCRIPTION
**Pull request by Keno**
Hoping this will make issues like #38712 easier to debug.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Looks like something is seeing a process id of -1?

**Comment by Keno** [comment]
Yes, it's an unsoundness in WeakKeyDict (https://github.com/JuliaLang/julia/issues/38712#issuecomment-739420623). The `@async` was turning the error into a hang.

**Comment by JeffBezanson** [comment]
Ah I see, or a RemoteRef getting finalized too early somehow?

**Comment by Keno** [comment]
No, I've verified that it happens as described in that comment in #38712 (at least in the instance that I was debugging) - WeakKeyDict is performing illegal necromancy.

**Pull request merged**
