### PR TITLE
remove timing stack fields when !ENABLE_TIMINGS

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vtjnash** [comment]
`ENABLE_TIMINGS` is never defined here

**Comment by JeffBezanson** [comment]
Ah, indeed. Any reason not to include options.h in julia.h?

**Comment by vtjnash** [comment]
Just unnecessary, since none of the other options affect the public ABI, we don't ship this file.

**Comment by JeffBezanson** [comment]
I would argue it is necessary, for removing these fields.

**Comment by JeffBezanson** [comment]
This has been unconditionally removed from jl_task_t, so I'm basically happy now.

**Pull request closed without merging**
