### PR TITLE
Make sure the object is still alive during unsafe_load in ccall tests

### LINKED ISSUE #12122: ccall test races with GC
I once saw this in MEMDEBUG mode. It depends on precise timing but it's pretty clear what's going on:

```
     * ccall               exception on 1: ERROR: LoadError: test failed: -4919131752989213765 is 881
 in expression: unsafe_load(ccall_echo_func(IntLike(881),Ptr{IntLike},Ref{IntLike})).x === 881
 in error at ./error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in include at ./boot.jl:254
 in runtests at /home/jeff/src/julia/test/testdefs.jl:197
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1401
while loading /home/jeff/src/julia/test/ccall.jl, in expression starting on line 20
ERROR: LoadError: LoadError: test failed: -4919131752989213765 is 881
 in expression: unsafe_load(ccall_echo_func(IntLike(881),Ptr{IntLike},Ref{IntLike})).x === 881
 in error at ./error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in include at ./boot.jl:254
 in runtests at /home/jeff/src/julia/test/testdefs.jl:197
 in anonymous at multi.jl:629
 in run_work_thunk at multi.jl:590
 in remotecall_fetch at multi.jl:663
 in remotecall_fetch at multi.jl:678
 in anonymous at task.jl:1401
while loading /home/jeff/src/julia/test/ccall.jl, in expression starting on line 20
while loading /home/jeff/src/julia/test/runtests.jl, in expression starting on line 5
```

`-4919131752989213765` is `0xbbbbbbbbbbbbbbbb`, so the `IntLike` value must have been freed before its contents could be loaded.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #12122 . Ref https://github.com/JuliaLang/julia/issues/12122#issuecomment-122063557

### CODE REVIEW

**Comment by carnaval** [comment]
looks good. thanks !

**Comment by yuyichao** [comment]
I found that fixing the ccall test (or the ccall test in general) is a good way to learn all different kinds of obscure use of `ccall`, `Ref`, `Any`, `Ptr{Any}` ......

**Comment by yuyichao** [comment]
This passes the GC stress test with 10x more collections than the one I used before to reliably trigger this issue.

**Comment by yuyichao** [comment]
CI looks good. Merged. Please keep this branch, I use it for gc related debugging in general.

**Comment by carnaval** [comment]
You better pray that Tony the branch slayer read this before going on his usual rampage

**Comment by yuyichao** [comment]
> You better pray that Tony the branch slayer read this before going on his usual rampage

And that was exactly the point of that note ;-P. I keep local copy so it won't be a big issue anyway.

**Comment by vtjnash** [comment]
thanks!

**Comment by tkelman** [comment]
Something is still up in the ccall test on 32 bit, apparently
```
        From worker 3:       * path                 in   2.51 seconds
exception on 3: ERROR: LoadError: test error in expression: b == s1
TypeError: subtype: expected Type{T}, got Any
 in record_var_type at ./inference.jl:1720
 in eval_annotate at ./inference.jl:1741
 in eval_annotate at ./inference.jl:1798 (repeats 2 times)
 in type_annotate at ./inference.jl:1826
 in typeinf_uncached at ./inference.jl:1695
 in typeinf at ./inference.jl:1339
 in typeinf_ext at ./inference.jl:1283
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in anonymous at /home/tkelman/Julia/julia-linux32/test/ccall.jl:189
 in anonymous at no file:139
 in include_string at loading.jl:153
 in include_from_node1 at ./loading.jl:190
 in runtests at /home/tkelman/Julia/julia-linux32/test/testdefs.jl:197
 in anonymous at /home/tkelman/Julia/julia-linux32/test/runtests.jl:14
 in anonymous at multi.jl:822
 in run_work_thunk at multi.jl:584
 in anonymous at task.jl:822
 in record_var_type at ./inference.jl:1720
 in eval_annotate at ./inference.jl:1741
 in eval_annotate at ./inference.jl:1798 (repeats 2 times)
 in type_annotate at ./inference.jl:1826
 in typeinf_uncached at ./inference.jl:1695
 in typeinf at ./inference.jl:1339
 in typeinf_ext at ./inference.jl:1283
 in anonymous at test.jl:90
 in do_test at test.jl:50
 in anonymous at /home/tkelman/Julia/julia-linux32/test/ccall.jl:189
 in anonymous at no file:139
 in include_string at loading.jl:153
 in include_from_node1 at ./loading.jl:190
 in runtests at /home/tkelman/Julia/julia-linux32/test/testdefs.jl:197
 in anonymous at /home/tkelman/Julia/julia-linux32/test/runtests.jl:14
 in anonymous at multi.jl:822
 in run_work_thunk at multi.jl:584
 in anonymous at task.jl:822
while loading /home/tkelman/Julia/julia-linux32/test/ccall.jl, in expression starting on line 135
        From worker 2:       * bitarray             in  73.95 seconds

signal (11): Segmentation fault
unknown function (ip: 0x5565fe53)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556605ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x55661b3b)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x5566184c)
unknown function (ip: 0x55661cc3)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661afb)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661b1b)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661afb)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661b1b)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661afb)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661afb)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x55661b1b)
unknown function (ip: 0x55660d5b)
unknown function (ip: 0x556605ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x55661695)
unknown function (ip: 0x55660bca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x55661695)
unknown function (ip: 0x55660bca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x556606ca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x55661695)
unknown function (ip: 0x55660bca)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x5565fe6e)
unknown function (ip: 0x55661695)
unknown function (ip: 0x55662b15)
jl_gc_collect at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_gc_alloc_1w at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_box_int32 at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_lookup_code_address at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
show_backtrace at replutil.jl:357
show_backtrace at replutil.jl:344
showerror at replutil.jl:85
julia_showerror_21081 at  (unknown line)
jlcall_showerror_21081 at  (unknown line)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
showerror at replutil.jl:83
jlcall___showerror#156___21076 at  (unknown line)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
julia_showerror_21075 at  (unknown line)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_f_kwcall at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
julia_showerror_21074 at  (unknown line)
jlcall_showerror_21074 at  (unknown line)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_f_kwcall at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
showerror at replutil.jl:91
julia_showerror_21068 at  (unknown line)
jlcall_showerror_21068 at  (unknown line)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
anonymous at client.jl:88
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
with_output_color at util.jl:331
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
display_error at client.jl:86
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
_start at ./client.jl:458
unknown function (ip: 0x56d5e856)
jl_trampoline at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/tkelman/Julia/julia-linux32/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x804940a)
unknown function (ip: 0x8048fa8)
__libc_start_main at /lib/i386-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x8048fe5)
Segmentation fault (core dumped)
make[1]: *** [all] Error 139
make: *** [testall] Error 2
```

**Comment by yuyichao** [comment]
That looks like a (or two) different issue. How repeatable is it?

**Comment by tkelman** [comment]
Not very, unfortunately

**Pull request merged**
