### PR TITLE
[release-0.5] Backport #19015

### PR DESCRIPTION
**Pull request by timholy**
This is against `release-0.5`. CC @tkelman, @nalimilan.

### CODE REVIEW

**Comment by tkelman** [comment]
missing the pr reference in the commit message

**Comment by timholy** [comment]
Each references the "parent" commit separately (I used `cherry-pick -x`). Should I have done it differently? How do you recommend fixing?

**Comment by tkelman** [comment]
commit --amend on the last one and add "ref #19015"

**Comment by timholy** [comment]
As a preemptive strike, I just did a grep on my installed packages. It looks like the following call `Base.reduced_dims` and/or `Base.reduced_dims0` directly:
- DataArrays
- Images
- PackageEvaluator
- StatsBase

With this PR, the return type is now an `Indices` tuple rather than a `Dims` tuple, so it's almost certain to cause a breakage.

If that's too much breakage, there's an easy fix: make the internal function `_reduced_dims` (which returns an `Indices` tuple) and then have `reduced_dims` unwrap any `OneTo` tuple as a `Dims` tuple. That *should* (theoretically) make this "invisible." Would you prefer that?

**Comment by timholy** [comment]
Alternatively, we could rename the core function `reduced_indices` on julia-0.6, define a deprecated `reduced_dims` to wrap-and-unwrap `Indices`<--->`Dims`, and then having a version of that change join this one before backporting to 0.5. The advantage of the latter strategy is that there would be some testing of this last piece on 0.6 first.

**Comment by timholy** [comment]
See #19103.

**Comment by timholy** [comment]
OK, commit message edited to link to the original PR, and #19103 added. In theory this should be 100% non-breaking.

**Comment by tkelman** [comment]
Thanks. I'll run pkgeval on a separate PR, hopefully this won't break anything but let's see.

**Comment by timholy** [comment]
Probably want #19196 too.

**Comment by tkelman** [comment]
That only touched deprecated.jl, which this didn't

**Comment by timholy** [comment]
Right, but the same issue might apply. I haven't checked carefully, though. (This had some of the deprecated functions without the deprecations.)

**Pull request merged**
