### PR TITLE
Fix #10865, Windows julia segfaulting without sys.dll

### LINKED ISSUE #10865: Windows nightly 64-bit release exe does not start
The release exe does not start in the latest Win64 nightly (ef062117ba). The -debug version and both 32-bit exes are fine. `--help` does work, but `julia -e "println(\"hello, world\")"` does not.

There are no messages when run in cmd, and nothing obviously wrong in Dependency Walker. I don't have gdb available right now, but in WinDbg I get:

```
...
ModLoad: 000007fe`ff610000 000007fe`ff65d000   C:\Windows\system32\WS2_32.dll
(1613d0.1613a4): Break instruction exception - code 80000003 (first chance)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 
ntdll!CsrSetPriorityClass+0x40:
00000000`77bfcb70 cc              int     3
0:000> g
ModLoad: 000007fe`ff5e0000 000007fe`ff60e000   C:\Windows\system32\IMM32.DLL
ModLoad: 000007fe`ff170000 000007fe`ff279000   C:\Windows\system32\MSCTF.dll
ModLoad: 000007fe`fd000000 000007fe`fd055000   C:\Windows\system32\mswsock.dll
ModLoad: 000007fe`fca30000 000007fe`fca37000   C:\Windows\System32\wshtcpip.dll
ModLoad: 000007fe`fd100000 000007fe`fd107000   C:\Windows\System32\wship6.dll
HEAP[julia.exe]: Invalid address specified to RtlFreeHeap( 0000000000F30000, 00000000001A47B0 )
(1613d0.1613a4): Break instruction exception - code 80000003 (first chance)
ntdll!EtwpCreateEtwThread+0x1721:
00000000`77bff0c1 cc              int     3
0:000> k
Child-SP          RetAddr           Call Site
00000000`00d5f3e8 00000000`77be8331 ntdll!EtwpCreateEtwThread+0x1721
00000000`00d5f3f0 00000000`77c19a39 ntdll!MD5Final+0x6d81
00000000`00d5f430 00000000`77bbdb50 ntdll!LdrGetFileNameFromLoadAsDataTable+0x1949
00000000`00d5f490 00000000`77ba40fd ntdll!RtlIsDosDeviceName_U+0x14130
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\system32\msvcrt.dll - 
00000000`00d5f7d0 000007fe`ffa510c8 ntdll!RtlAllocateHeap+0xd9d
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for D:\Software\Julia-0.4.0-dev-ef062117ba\bin\libjulia.dll - 
00000000`00d5f850 00000000`6bf9adea msvcrt!free+0x1c
00000000`00d5f880 00000000`6bfa47ed libjulia!jl_f_new_expr+0x33a
00000000`00d5fb10 00000000`6bf9dcee libjulia!jl_preload_sysimg_so+0x8d
00000000`00d5fba0 00000000`6bf9ec1d libjulia!jl_get_builtin_hooks+0x5ee
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for julia.exe - 
00000000`00d5fd50 00000000`0040245f libjulia!julia_init+0xd
00000000`00d5fd90 00000000`004013ca julia+0x245f
00000000`00d5fe60 00000000`004014f8 julia+0x13ca
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\system32\kernel32.dll - 
00000000`00d5ff30 00000000`77a459ed julia+0x14f8
00000000`00d5ff60 00000000`77b7c541 kernel32!BaseThreadInitThunk+0xd
00000000`00d5ff90 00000000`00000000 ntdll!RtlUserThreadStart+0x21
0:000> g
HEAP[julia.exe]: Invalid address specified to RtlFreeHeap( 0000000000F30000, 00000000001A4990 )
(1613d0.1613a4): Break instruction exception - code 80000003 (first chance)
ntdll!EtwpCreateEtwThread+0x1721:
00000000`77bff0c1 cc              int     3
0:000> k
Child-SP          RetAddr           Call Site
00000000`00d5f3e8 00000000`77be8331 ntdll!EtwpCreateEtwThread+0x1721
00000000`00d5f3f0 00000000`77c19a39 ntdll!MD5Final+0x6d81
00000000`00d5f430 00000000`77bbdb50 ntdll!LdrGetFileNameFromLoadAsDataTable+0x1949
00000000`00d5f490 00000000`77ba40fd ntdll!RtlIsDosDeviceName_U+0x14130
00000000`00d5f7d0 000007fe`ffa510c8 ntdll!RtlAllocateHeap+0xd9d
00000000`00d5f850 00000000`6bf9adea msvcrt!free+0x1c
00000000`00d5f880 00000000`6bfa47ed libjulia!jl_f_new_expr+0x33a
00000000`00d5fb10 00000000`6bf9dcee libjulia!jl_preload_sysimg_so+0x8d
00000000`00d5fba0 00000000`6bf9ec1d libjulia!jl_get_builtin_hooks+0x5ee
00000000`00d5fd50 00000000`0040245f libjulia!julia_init+0xd
00000000`00d5fd90 00000000`004013ca julia+0x245f
00000000`00d5fe60 00000000`004014f8 julia+0x13ca
00000000`00d5ff30 00000000`77a459ed julia+0x14f8
00000000`00d5ff60 00000000`77b7c541 kernel32!BaseThreadInitThunk+0xd
00000000`00d5ff90 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

(in WinDbg I can continue through these errors and get to the REPL prompt)

Based on seeing `jl_get_builtin_hooks`, I'm mildly suspicious of #10714, but I can't justify the suspicion since we should not be compiling the new readlink function at startup. Given the timing, the tuple overhaul seems more likely, but I did build and run ef062117ba in release mode last night.

### PR DESCRIPTION
**Pull request by tkelman**
also test this on appveyor

@ihnorton @pao etc we should probably test that this still works with bindeps etc

### CODE REVIEW

**Comment by tkelman** [comment]
Would also appreciate an opinion from @vtjnash on this and #10832, should this maybe only ifndef out the `free` lines but leave the setting-to-NULL in place?

**Comment by ihnorton** [comment]
Thanks for debugging this. The issue seems to be that we are using the wrong flavor of `free`... So, rather than ifdef'ing this out entirely, we could probably use `LocalFree` as libuv does.

(it is remarkable to me that node calls `uv_dlopen` and `uv_dlerror` exactly once in the whole runtime codebase. on the other hand, they apparently have no need for anything other than `RTLD_LAZY`)

**Comment by tkelman** [comment]
Cool, `LocalFree` works for me locally, thanks for finding that.

**Comment by vtjnash** [comment]
there's a second issue here, which is that this may not work properly with the msvc build. it is not valid to call `free` (or variants such as `LocalFree`) on a pointer that was created in a different shared library. for example, in this case, you must call `uv_dlclose` on the pointer so that libuv can correctly free any memory that it allocated, and not call `free` (or `LocalFree`) directly.

**Comment by tkelman** [comment]
Do you mean like c2def2cfe707ea574762a1a04cbfafd1f745d560? libuv isn't in a separate shared library in our current setup

**Comment by vtjnash** [comment]
yes, that looks right

**Comment by ihnorton** [comment]
x86_64 travis failure is just github and <DDOS people> doing their tango.

**Pull request merged**
