### PR TITLE
Rename realmin/max -> floatmin/max

### PR DESCRIPTION
**Pull request by Keno**
Similar in spirit to #28301 and also discussed on triage today. The names realmin/realmax, don't make too much sense in our terminology. These function are floating-point property queries, querying in particular the largest/smallest positive normalized floating point value. `posnormfloatmin` isn't a great name however, so simply `floatmin` was suggested. This has the advantage that it's suggestive of the fact that it's a floating point type query, even if it's not quite the minimum floating point value or even the minimum positive floating point value, but that's what docs are for. In any case, they're better than real. We have a good number of subtypes of `Real` for which  these functions make no sense. In libc, these are called `FLT_MIN`/`FLT_MAX` or `DBL_MIN`/`DBL_MAX`.

Note, this PR is against #28301, since it touches some of the same lines and I wanted to keep the diff clean. I expect to merge that PR first and rebase this against master.

### CODE REVIEW

**Comment by oscardssmith** [comment]
why not deprecate to `eps(0.0)`? does that not take into account subnormals or something?

**Comment by ViralBShah** [comment]
```

julia> realmin(Float64)
2.2250738585072014e-308

julia> eps(0.0)
5.0e-324
```

**Comment by ViralBShah** [comment]
Also, not generalizable for the other extreme.

**Comment by Keno** [comment]
We could have a `normeps` or a `nextnormfloat`, in which case these would be `nextnormfloat(0.0)` and `prevfloat(Inf)`, but not sure that's any better.

**Comment by Keno** [comment]
Alright, good to go or are there any alternatives we're considering?

**Review by ararslan — APPROVED** [review]

**Pull request merged**
