### PR TITLE
[release-1.5] Set VERSION to 1.5.4

### PR DESCRIPTION
**Pull request by ararslan**
cc @vchuravy

### CODE REVIEW

**Comment by ararslan** [comment]
The testing period for this release has been [announced on Discourse](https://discourse.julialang.org/t/julia-1-5-4-testing-period/56052?u=ararslan).

**Review by Sacha0 — APPROVED** [review]
Thanks again Alex! :)

**Comment by KristofferC** [comment]
It is usually run on the backport PR.

**Comment by ararslan** [comment]
Haven't seen problems noted from people trying out 1.5.4. Good to go?

**Pull request merged**
