### PR TITLE
refactor post-opt analysis and get rid of closures

### PR DESCRIPTION
**Pull request by aviatesk**
@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/51290) failed.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51290#issuecomment-1717074541) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/86be8ce_vs_141e07e/report.md).

**Comment by aviatesk** [comment]
@Keno, does this seem sane to you? While it may not boost performance itself, it does simplify maintaining our codebase's performance. Previously, we had to be careful with variable naming, e.g. [this variable](https://github.com/JuliaLang/julia/blob/141e07e1db432beb6e84703200ea01af4fb558bc/base/compiler/optimize.jl#L598) should be named `istmt` instead of simpler `stmt` just to avoid unnecessary allocations. This change eliminates such nuances. I agree with the idea of initially developing with closures for flexibility, but I think it's time to transition to a more robust implementation.

**Comment by Keno** [comment]
Sure, this is fine. Manually closure converting does allow us to make sure the captures are exactly what we want.

**Pull request merged**
