### PR TITLE
Avoid infinite method error on bootstrap error

### PR DESCRIPTION
**Pull request by yuyichao**
Also make the control flow in `exec_program` easier to understand.

### CODE REVIEW

**Comment by tkelman** [comment]
is whatever this was fixing also an issue on release-0.5?

**Comment by yuyichao** [comment]
It does. But this is a developer only feature.

**Comment by tkelman** [comment]
or if you do something wrong in userimg, right?

**Comment by yuyichao** [comment]
No

**Comment by tkelman** [comment]
what would cause it then? will wait until 0.5.1

**Comment by yuyichao** [comment]
Raising an uncaught error before it can be shown or essentially anytime when something is broken, which is why I said this is a developer only feature. (In https://github.com/JuliaLang/julia/pull/18444 I think it was when I messed up some parameter packing for vararg functions in type inference).

Might also fix hanging when pressing Ctrl-C too early in sysimg compilation.

**Pull request merged**
