### PR TITLE
Fix #11140 Added `is_valid_utf32`

### LINKED ISSUE #11140: Missing is_valid_utf32 function
Although there are is_valid_ascii, is_valid_utf8, and is_valid_utf16 functions, the corresponding is_valid_utf32 function does not exist.
[I will submit a PR later to fix that]

### PR DESCRIPTION
**Pull request by ScottPJones**
Added a new function, which corresponds to the is_valid_ascii, is_valid_utf8, is_valid_utf16 functions.
Added some simple testing (same as what was done for the other is_valid_\* functions).
[more should be done in the future]

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This cries out for a more generic interface but this works for now and will be easy to deprecate.

**Comment by ScottPJones** [comment]
Maybe something like:  is_valid(type, value)?
is_valid(Char, integer) instead of is_valid_char, is_valid(ASCIIString, Vector{UInt8}), etc.?

**Comment by quinnj** [comment]
`isvalid`

**Comment by ScottPJones** [comment]
Sounds good to me

**Pull request merged**
