### PR TITLE
bump Pkg to fix hash failure in some artifacts

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
No CI?

**Comment by StefanKarpinski** [comment]
Buildbots seem to be down. cc @christopher-dG, @staticfloat

**Comment by christopher-dG** [comment]
Confirmed, build.julialang.org can't be reached. That's Elliot's domain though.

**Comment by AshtonSBradley** [comment]
if it helps, works for me on macos

**Pull request merged**
