### PR TITLE
Convenience Functions for `isweekend` or `isweekday`

### LINKED ISSUE #41058: [PR Proposal] Adding Functionality for `isweekday` or `isweekend` to Dates.
In the `Dates` package, there exist methods for `ismonday`, `istuesday`, etc. May I open a PR to add functionality to `Dates` to check for whether or not a given date falls on a weekday or weekend? There may be some localization differences I could account for (i.e. does a weekday start Sunday or Monday for people) but I thought this might be a reasonable PR to add as this is a functionality I could use.

Thoughts? Thank you!

### PR DESCRIPTION
**Pull request by TheCedarPrince**
Based off of issue #41058 , I created the following PR which adds in two functions to determine whether a day of the week falls on a weekday or weekend. This also contains the four most common locales for when these days occur. 

Closes #41058

### CODE REVIEW

**Comment by stevengj** [comment]
I don't like the idea of introducing a function-specific "locale" definition here… if we don't support "real" [ISO locales](https://en.wikipedia.org/wiki/Locale_(computer_software)) we shouldn't make up our own an an ad-hoc basis for particular functions.

**Comment by TheCedarPrince** [comment]
I think that makes a lot of sense @stevengj - so I can just close this PR. Or do you have any other ideas about how it could be improved?

**Comment by ParadaCarleton** [comment]
> I think that makes a lot of sense @stevengj - so I can just close this PR. Or do you have any other ideas about how it could be improved?
I would just remove locales and have it return the current default behavior, which aligns with what almost all Julia programmers would expect (i.e. weekends are Saturday+Sunday). As long as this is clearly documented, it shouldn't be a big problem.

**Comment by oscardssmith** [comment]
I'm not sure that's a good idea. It would be wrong for (at least) most of the middle east, and probably other places as well. As such, it's probably better to have this in a package somewhere than to have it in Base. Functions in Base are very hard to remove, need to work reliably even in edge cases. As such adding functions that depend on non-universal cultural assumptions is usually a bad idea.

**Comment by TheCedarPrince** [comment]
I agree @oscardssmith - I based this off of research I had done to find the four most common definitions of weekends/weekdays. It is not in full alignment with the [ISO 8601 spec](https://en.wikipedia.org/wiki/ISO_8601) here as the spec does not define what a weekday/weekend actually is. I could see why as the definition of such tends to not only depend on country but also other social factors in those areas making it neigh impossible to ascertain when a weekday/weekend actually is. Therefore, I will close this PR as I agree that although my attempt at being inclusive with respect to the four general locales I defined, it is not enough for Base Julia.

I do have this defined in another package so I will probably just open source that at some point in the future - and the code is linked here always for someone to take it and run with it. :) Thanks all!

**Pull request closed without merging**
