### PR TITLE
release-1.7: set VERSION to 1.7.0

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
Tester linux64 will hang because of a RR issue with 1.7. Look at the result from the buildkite run (one without RR).

**Comment by DilumAluthge** [comment]
Here's the Buildkite run: https://buildkite.com/julialang/julia-release-1-dot-7/builds/180

**Comment by DilumAluthge** [comment]
Based on the Buildkite run linked above, it looks like all of the non-rr linux64 jobs are all passing, so I think CI can be considered

**Comment by vtjnash** [comment]
Is `Pkg.upgrade_manifest` functional on this version? It seems it was broken for RC3 (https://github.com/JuliaLang/Pkg.jl/issues/2867)

**Comment by DilumAluthge** [comment]
> Is `Pkg.upgrade_manifest` functional on this version? It seems it was broken for RC3 ([JuliaLang/Pkg.jl#2867](https://github.com/JuliaLang/Pkg.jl/issues/2867))

From https://github.com/JuliaLang/Pkg.jl/issues/2867#issuecomment-982202409:

> Oh, this seems to be an issue with an old version of Revise, and since I had a stack environment, it wasn't able to update.

**Pull request merged**
