### PR TITLE
RFC: quicksort refactor, addition of selectperm

### PR DESCRIPTION
**Pull request by kmsquire**
This PR picks up where #10800 left off:
1. extracts `select_pivot!` and `partition!` from quicksort
2. reuses these among the different quicksort-like algorithms
3. (from #10800) adds `PartialQuickSort` (originally from @carlobaldassi)
4. (from #10800) adds `selectperm`, `selectperm!`
5. For uniformity, switches `select` (and `select!`) to use `PartialQuickSort`

`PartialQuickSort` here handles both `Int` and  `OrdinalRange` type parameters (which was not part of #10800).  

It could (and probably should) be changed to only handle `OrdinalRange` parameters, which would simplify the code (removing one extra function), at the cost of 1 extra comparison per (recursive) call.

With limited testing, it seems that there are no performance regressions.

Cc: @spencerlyon2, @StefanKarpinski

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Nice.

**Comment by spencerlyon2** [comment]
This looks great. Anything else need to be done?

**Comment by kmsquire** [comment]
The docs for PartialQuickSort need to be updated (it can handle any OrdinalRange).  I would also like to try only having PartialQuickSort take an OrdinalRange,  but I'm not sure I'll get to that today.  It shouldn't change any functionality, but it would simplify the code some.

**Comment by StefanKarpinski** [comment]
That could be done in a follow-on change, right? Seems better to do it separately then.

**Comment by StefanKarpinski** [comment]
:+1: merge at will!

**Comment by kmsquire** [comment]
Thanks!  Updated docs, squashed, and will merge when CI turns green again.

I left @spencerlyon2's original commit in here.  It passed CI previously, so I don't think it should be a problem.

**Comment by spencerlyon2** [comment]
Thanks @kmsquire.

Hopefully it isn't an issue!

**Comment by kmsquire** [comment]
:-)

**Pull request merged**
