### PR TITLE
fix #20220 - repeated deprecation warning

### LINKED ISSUE #20220: Deprecation warning for Array(T) never stop printing
For example: `Pkg.test("SHA")`:

Gif: https://media.giphy.com/media/l3q2uhPC2EsBExBvi/source.gif

### PR DESCRIPTION
**Pull request by JeffBezanson**
1-character bugfix.

### CODE REVIEW

**Comment by tkelman** [comment]
Wow. There's a copy of this for a more specific deprecation at L1064 that probably needs the same change?

**Review by tkelman — APPROVED** [review]
we don't have all that great tests of depwarns, but this should help pkgeval logs be much smaller

**Comment by yuyichao** [comment]
Why was this causing the issue?

**Comment by JeffBezanson** [comment]
depwarn passes `once=(caller != StackTraces.UNKNOWN)` to `warn`, so returning any frame that's `==` to `StackTraces.UNKNOWN` disables warn-once handling.

**Comment by tkelman** [comment]
32 bit appveyor looks like it's timing out, but don't see how that could be caused by this. merging to get this into tonight's pkgeval run

**Comment by tkelman** [comment]
Just leaving a note that this caused the results of some `@test_warn` invocations that Diversity.jl was doing, xref https://github.com/JuliaCI/PackageEvaluator.jl/issues/159

**Pull request merged**
