### PR TITLE
RFC: Add `isa` as an infix operator

### PR DESCRIPTION
**Pull request by ararslan**
This implements @yuyichao's suggestion in #19524 of an infix operator version of `isa`. Thus, with this PR, we have
```julia
julia> 1 isa Integer
true
```

### CODE REVIEW

**Comment by ararslan** [comment]
The macOS failure is unrelated (stalled build).

**Comment by ararslan** [comment]
Any comments? Is this something we want to have?

**Comment by quinnj** [comment]
I'm a fan 👍

**Comment by nalimilan** [comment]
I always fail to remember the order of arguments to `isa`; having it infix would fix that.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
If this gets the @JeffBezanson go-ahead, we should probably change the usages as well.

**Comment by JeffBezanson** [comment]
I won't object --- but it's starting to seem like only a matter of time before we allow infix for any function.

**Review by JeffBezanson — APPROVED** [review]

**Comment by ararslan** [comment]
> it's starting to seem like only a matter of time before we allow infix for any function.

Actually I was initially against this change for exactly that reason. But upon further reflection, this just seems to me like a natural infix operator, like `<:` except for values instead of types.

**Comment by JeffBezanson** [comment]
One observation is that both `in` and `isa` should obviously have comparison precedence, but for arbitrary functions the precedence is less clear.

**Comment by ararslan** [comment]
Would this give you any less pause if there were some kind of symbolic infix operator that lowered to `isa` rather than having `isa` itself be infix?

**Comment by JeffBezanson** [comment]
No, this is fine. I can't think of an operator that would improve on just using `isa`.

**Comment by ararslan** [comment]
Okay, cool. Thanks everyone!

**Comment by ararslan** [comment]
If this is good to merge, does someone want to do the deed?

**Comment by oscardssmith** [comment]
Can we also add isan in case the type starts with a vowel?

**Comment by JeffBezanson** [comment]
No. English is too weird :)

**Comment by tkelman** [comment]
This should go into news since it can change how existing code is parsed

**Comment by ararslan** [comment]
Okay, I can submit a PR with a news item.

**Comment by ranjanan** [comment]
@tkelman are you going to including this in 0.6.0-rc2? It's not included in 0.6.0-rc1

**Comment by tkelman** [comment]
merged in december, what makes you think it isn't in rc1?

**Comment by ranjanan** [comment]
My bad, I was using 0.5 instead. Forget I asked.

**Pull request merged**
