### PR TITLE
move shell_parse into parser (fixes #3150)

### LINKED ISSUE #3150: parse command interpolations at parse time
It would be nice to have a way to "double interpolate" a variable with respects to nested possible interpolation contexts to make it easier to write quoted code blocks that wants to interpolate a variable inside a string. e.g., so the below code echos "hi". Not sure what the best way to go about that is.

``` julia
macro example()
 f="hi"
 quote
  run(`echo $$f`)
 end
end
```

### PR DESCRIPTION
**Pull request by nolta**

### CODE REVIEW

**Comment by eschnett** [comment]
I assume this conflicts with #13195.

**Comment by jakebolewski** [comment]
Seems also to conflict with https://github.com/JuliaLang/julia/issues/12139?

**Comment by vtjnash** [comment]
This seems like it would be breaking, if we decide to proceed with it, so it's v2.0+ only. Should we tag it that way?

**Comment by StefanKarpinski** [comment]
I don't really see much need for nested backticks, tbh.

**Pull request closed without merging**
