### PR TITLE
Revert "don't pass through stderr of processes started by `eachline` …

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/issues/13938

**Comment by StefanKarpinski** [comment]
Feel free to merge as soon as the tests pass.

**Comment by tkelman** [comment]
ahk this makes the test from https://github.com/JuliaLang/julia/commit/9b248b6b24a14b92d6a51fac26683d1a737c8ea8 a little noisy but I think it's better to just handle that one specific invocation locally in that test rather than play hide-the-stderr everywhere.

**Comment by StefanKarpinski** [comment]
Agreed. Error messages aren't much use if you never see them. I generally want to see any error messages produced anywhere in anything I run unless I explicitly silence them.

**Pull request merged**
