### PR TITLE
RFC: Replaced Dict with OrderedDict

### LINKED ISSUE #34265: Deserializing a Dict gives a different order
@bkamins  pointed out on slack:

```
julia> using Serialization;
julia> d = Dict{Symbol, Vector{Int}}(Symbol.('a':'z') .=> Ref([1]));
julia> serialize("test.bin", d);
julia> d2 = deserialize("test.bin");
julia> hcat(collect.(keys.([d, d2]))...)
26×2 Array{Symbol,2}:
 :o  :j
 :b  :x
 :p  :d
 :n  :k
 :j  :g
 :e  :u
 :c  :r
 :h  :a
 :l  :m
 :w  :y
 :x  :i
 :d  :o
 :k  :b
 :s  :p
 :v  :n
 :g  :e
 :u  :c
 :q  :h
 :r  :l
 :z  :w
 :a  :s
 :f  :v
 :m  :z
 :y  :q
 :i  :f
 :t  :t
```

But it doesn't have to be this way.

If we redefine things so it remembers how many slots it should have,
then it comes out the same as it came in.
```

hintsize(dict::AbstractDict) = length(dict)
hintsize(dict::Dict) = length(dict.keys)

function Serialization.deserialize_dict(s::AbstractSerializer, T::Type{<:AbstractDict})
    n = read(s.io, Int32)
    sz = read(s.io, Int32)
    t = T();
    sizehint!(t, sz)
    Serialization.deserialize_cycle(s, t)
    for i = 1:n
        k = deserialize(s)
        v = deserialize(s)
        t[k] = v
    end
    return t
end

function Serialization.serialize_dict_data(s::AbstractSerializer, d::AbstractDict)
    write(s.io, Int32(length(d)))
    write(s.io, Int32(length(d.slots)))
    for (k,v) in d
        serialize(s, k)
        serialize(s, v)
    end
end
```

But this is annoying because it changes the serialization format.
I would rather change `sizehint!(::Dict)` or how we call it.
The problem is that `sizehint!(Dict(), 26)` gives it 32 slots,
but the `d` had 64 slots.

---
In python this was one of thing things that really caught me out.
Because python salts its hashes wiith a random salt selected each time it starts.
But julia doesn't.

### PR DESCRIPTION
**Pull request by PallHaraldsson**
(from OrderedCollections.jl/DataStructures.jl).

Fixes: #34265 See also my argument: https://github.com/JuliaLang/julia/issues/37761#issuecomment-699218475

[My first real PR, or I mean the first where I had to recompile Julia.]

Added also other variants, e.g. OrderedRobinDict, for now disabled.
UDict is the old unordered (or unpredictable order) Dict. It is for now
NOT exported, unclear it should be as there are better replacements
e.g. SwissDict based on Google's Swiss Table.

I would like packageeval run on this.

I know there are no tests (they are in the packages I took the code from). The 2x slowdown isn't real. I.e. starting Julia where I have Revise and OhMyREPL with `@time`

  0.948864 seconds (552.62 k allocations: 34.550 MiB)
  0.856972 seconds (747.65 k allocations: 48.796 MiB, 2.50% gc time)

vs. Commit a0a68a54d6 (14 days old master)

  0.592275 seconds (635.56 k allocations: 40.700 MiB, 1.61% gc time)
  0.686102 seconds (668.09 k allocations: 44.774 MiB, 2.82% gc time)

is because of precompilation issues. Note, however former has fewer allocations, so I'm optimistic about the speed (for those, after fixing packages themselves). I looked into it and at least OhMyREPL needs more statements, independent of this, and with this a bit more.

By adding precompile statements to Revise I got slowdown limited to 10%:

```
$ ./julia --startup-file=no -e "@time using Revise"
  0.796831 seconds (716.50 k allocations: 47.621 MiB, 1.93% gc time)
vs.
  0.721835 seconds (661.93 k allocations: 45.353 MiB, 2.18% gc time)
```

There are tricks possible to make OrderedDict much faster, but not in time for Julia 1.6.0 (faster than Dict is now, for this/these cases). Startup of Julia itself <s>is 174.5 ms</s> vs. 162.2, <s>extra 12 ms or 7%</s> [EDIT: no longer slower in to come PR], likely could be faster than with Dict as it is now. See: https://github.com/JuliaCollections/OrderedCollections.jl/issues/57#issuecomment-700977969

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Note, only real added file is base/ordered_dict.jl and just Dict->UDict renaming in dict.jl, so can ignore the other files. Helpful to merge the other disabled variants(?), and RobinDict, in case people want to experiment with it in base.

**Comment by PallHaraldsson** [comment]
The only CI fail, whitespace (well plus now "makedocs") is I guess:
```
# Types
UDict,
OrderedRobinDict,
RobinDict,
    AbstractChannel,
    AbstractChannel,
```

for me, I wanted it to stand out, as in some sense WIP. Interesting that you can exporst undefined stuff (only UDict of those is really defined).

**Comment by JeffBezanson** [comment]
We are not going to dump a whole slew of new dictionary types into Base. It would help your case if the PR did only as described, and just made Dict ordered, but it's still very uncertain whether we will do this.

**Comment by PallHaraldsson** [comment]
People asked for not just replacing, but also having the old Dict. I guess that's reasonable, and first I replaced types dependent on it e.g. IdDict, but then wasn't sure, so left it in to only replace Dict.

It's very easy to drop the other files, they are even not included (except for old Dict support). I was just working on different implementation of OrderedDict too compare, e.g. OrderedRobinDict, and if anyone would like to compare then I have the files in. We would drop them later, before Julia 1.6 release.

This shouldn't stop packageeval?

**Comment by StefanKarpinski** [comment]
This PR isn't building, let alone passing CI, never mind being able to do a PkgEval run.

**Comment by PallHaraldsson** [comment]
It's:
```
ERROR: LoadError: `makedocs` encountered errors. Terminating build
```
The new Dict works for me, I compiled locally (first commit), with make test, wasn't aware of doc issue, seemingly this:

```
help?> Dict
[..]
  Base.Dict is of type UnionAll.
```
I guess because of my: const Dict = OrderedDict

Is it ok to not export UDict from Base (intentionally excluding users of Julia), does it interfere with using it internally? Maybe that broke something in my subsequent commit?

**Comment by PallHaraldsson** [comment]
Linux CI compete (strange as I see "trigger 0 builds, 1 pending builds").

**Comment by KristofferC** [comment]
> Linux CI compete (strange as I see "trigger 0 builds, 1 pending builds").

The package phase completed but the tests fail, see e.g. https://build.julialang.org/#/builders/34/builds/4250/steps/5/logs/stdio.

**Comment by PallHaraldsson** [comment]
The problem seems to be "unbound type parameters" in Method or ("UndefVarErrors"), I'm just not sure what that means. See details on error below.

`Set`s seem to work however, with Dict and Udict:

```
julia> Base.UDict("A" => 1, "B" => 2)
Base.UDict{String, Int64} with 2 entries:
  "B" => 2
  "A" => 1

julia> Set(ans)
Set{Pair{String, Int64}} with 2 elements:
  "B" => 2
  "A" => 1

vs.

julia> Dict("A" => 1, "B" => 2)
Dict{String, Int64} with 2 entries:
  "A" => 1
  "B" => 2

julia> Set(ans)
Set{Pair{String, Int64}} with 2 elements:
  "A" => 1
  "B" => 2

Error in last test, be e.g. not in similar test higher up:

```
# Test that Core and Base are free of UndefVarErrors
# not using isempty so this prints more information when it fails
@testset "detect_unbound_args in Base and Core" begin
    # TODO: review this list and remove everything between test_broken and test
    let need_to_handle_undef_sparam =
            Set{Method}(detect_unbound_args(Core; recursive=true))
        pop!(need_to_handle_undef_sparam, which(Core.Compiler.eltype, Tuple{Type{Tuple{Any}}}))
        @test_broken need_to_handle_undef_sparam == Set()
        pop!(need_to_handle_undef_sparam, which(Core.Compiler._cat, Tuple{Any, AbstractArray}))
        pop!(need_to_handle_undef_sparam, first(methods(Core.Compiler.same_names)))
        @test need_to_handle_undef_sparam == Set()
    end
    let need_to_handle_undef_sparam =
            Set{Method}(detect_unbound_args(Base; recursive=true))
        pop!(need_to_handle_undef_sparam, which(Base._totuple, (Type{Tuple{Vararg{E}}} where E, Any, Any)))
        pop!(need_to_handle_undef_sparam, which(Base.eltype, Tuple{Type{Tuple{Any}}}))
        pop!(need_to_handle_undef_sparam, first(methods(Base.same_names)))
        @test_broken need_to_handle_undef_sparam == Set()
        pop!(need_to_handle_undef_sparam, which(Base._cat, Tuple{Any, AbstractArray}))
        pop!(need_to_handle_undef_sparam, which(Base.byteenv, (Union{AbstractArray{Pair{T,V}, 1}, Tuple{Vararg{Pair{T,V}}}} where {T<:AbstractString,V},)))
        pop!(need_to_handle_undef_sparam, which(Base.float, Tuple{AbstractArray{Union{Missing, T},N} where {T, N}}))
        pop!(need_to_handle_undef_sparam, which(Base.zero, Tuple{Type{Union{Missing, T}} where T}))
        pop!(need_to_handle_undef_sparam, which(Base.one, Tuple{Type{Union{Missing, T}} where T}))
        pop!(need_to_handle_undef_sparam, which(Base.oneunit, Tuple{Type{Union{Missing, T}} where T}))
        @test need_to_handle_undef_sparam == Set()
    end
end
```

Does it mean I need to export the new type UDict from Base, for Julia itself to work?

**Comment by PallHaraldsson** [comment]
I donðt know about those test if false alarm or code broken, but I now get 157.5 ms startup of Julia (with change not in PR), faster than my best so far on master 162.2 ms. And also faster than with current PR:

```
$ julia --startup-file=no -e "@time using Revise"
  0.734465 seconds (682.46 k allocations: 46.733 MiB, 2.14% gc time)
```

**Comment by PallHaraldsson** [comment]
I could silence the test error by commenting out this one line:

```
# problematic line: OrderedDict(kv::Tuple{Vararg{Pair{K,V}}}) where {K,V}  = OrderedDict{K,V}(kv)

OrderedDict(ps::Pair...)                  = OrderedDict(ps)
```

Is the former redundant with the latter? As of Julia 1.6? It there still time to get this in Julia 1.6?

**Comment by PallHaraldsson** [comment]
The docss test is a false alarm kind of, but the API for OrderedDict isn't the same so I need to look into e.g.:

A.
Error in testset Random:
Error During Test at /usr/home/julia/buildbot/worker-tabularasa/tester_freebsd64/build/share/julia/test/testdefs.jl:22
  Got exception outside of a @test
  LoadError: MethodError: no method matching isslotfilled(::Dict{Int64, Nothing}, ::Int64)
  Closest candidates are:
    isslotfilled(!Matched::Base.UDict, ::Int64) at dict.jl:172

B.
Error During Test at /buildworker/worker/tester_linux64/build/share/julia/test/asyncmap.jl:6
  Test threw exception
  Expression: allunique(asyncmap((x->begin
                sleep(1.0)
                objectid(current_task())
            end), 1:10))
  MethodError: no method matching ht_keyindex2!(::Dict{UInt64, Nothing}, ::UInt64)
  Closest candidates are:
    ht_keyindex2!(!Matched::Base.UDict{K, V}, ::Any) where {K, V} at dict.jl:305
  Stacktrace:
   [1] allunique(C::Vector{UInt64})
     @ Base ./set.jl:0
   [2] top-level scope
     @ /buildworker/worker/tester_linux64/build/share/julia/test/asyncmap.jl:6
   [3] include(mod::Module, _path::String)
     @ Base ./Base.jl:392
   [4] include
     @ /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:13 [inlined]
   [5] macro expansion
     @ /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:25 [inlined]
   [6] macro expansion
     @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1113 [inlined]
   [7] macro expansion
     @ /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:24 [inlined]
   [8] macro expansion
     @ ./timing.jl:310 [inlined]
   [9] top-level scope
     @ /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:22

C.
And fix tests, that assume a order:
Evaluated: "Set([(1.0, 1.0), (2.0, 2.0), (3.0, 3.0)])" == "Set([(3.0, 3.0), (2.0, 2.0), (1.0, 1.0)])"

**Pull request closed without merging**
