### PR TITLE
Remove mention of `reload` from the docs; fix #28572

### LINKED ISSUE #28572: Docs still mention `reload(...)`
The docs (https://docs.julialang.org/en/stable/manual/modules/) still suggest to use `reload`, but this function is no longer defined in Julia 0.7/1.0.

See also https://github.com/JuliaLang/julia/issues/25720.

### PR DESCRIPTION
**Pull request by mkborregaard**
I believe `reload` has been deprecated.

### CODE REVIEW

**Comment by KristofferC** [comment]
Whitespace issue

**Comment by mkborregaard** [comment]
Sorry, fixed.

**Comment by fredrikekre** [comment]
Seems to be on the other 3 lines too.

**Comment by mkborregaard** [comment]
:ahhhhhhh:
right - sorry. Fixed.

**Pull request merged**
