### PR TITLE
Add doc for @raw_str

### PR DESCRIPTION
**Pull request by innerlee**
Docs copied from manual. Locally looks good.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by fredrikekre** [comment]
Typically doc strings are more compact. Perhaps something like
````julia
"""
    @raw_str -> String

Create a raw string without interpolation and unescaping.

# Examples
```jldoctest
julia> raw"\\""
"\\""

julia> raw""\" " ""\"
" \\" "
```
"""
````
would be more typical and unified with how we express other docstrings?

**Comment by innerlee** [comment]
I can change it like that. A small question: should this `The exception is quotation marks that still must be escaped.` be added?

**Comment by fredrikekre** [comment]
Yea that makes sense to keep, since there is also an example of it.

**Review by fredrikekre — APPROVED** [review]

**Comment by innerlee** [comment]
Changed the sentence to "The exception is that quotation marks still must be escaped."

**Comment by innerlee** [comment]
:up: :)

**Review by ararslan — APPROVED** [review]

**Pull request merged**
