### PR TITLE
upgrade OpenBLAS to 0.3.0

### PR DESCRIPTION
**Pull request by vchuravy**
0.3.0 was released just recently and it has some improvement w.r.t to performance on Mac OSX.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Will the ci systems build openblas?

**Comment by ViralBShah** [comment]
Note this also updates to lapack 3.8

**Comment by ViralBShah** [comment]
FreeBSD died on Distributed. Appveyor looks like it might have timed out.

**Comment by ViralBShah** [comment]
Restarted Appveyor build, but not sure if it will help.

**Comment by vchuravy** [comment]
This might also benefit from #27222

**Comment by ViralBShah** [comment]
Should we merge #27222 and rebase this on top of that?

**Comment by tkelman** [comment]
Need to update the checksums.

**Comment by vchuravy** [comment]
All of Travis stalled out. I was thinking that it might have been an issue with their infrastructure, but there is no report.

IIUC AV doesn't build OpenBLAS since it uses the prebuilt binaries. I kicked of some buildbot runs, but that this point our queue is 18h behind.

**Comment by ViralBShah** [comment]
Pushed the checksums.

**Comment by vchuravy** [comment]
5fcc6d3 already had the checksums

**Comment by andreasnoack** [comment]
Would it make sense to start using https://github.com/staticfloat/OpenBLASBuilder/ instead of building these here?

**Comment by ViralBShah** [comment]
@vchuravy I think I had an older branch, which is why I didn't see your checksum commit. Should have pulled.

**Comment by ViralBShah** [comment]
How do we know whether the windows buildbot successfully built openblas 0.3 last night and that is being picked up here? The appveyor build logs seem to not have any indicating information about openblas.

**Comment by vchuravy** [comment]
The buildbot builds haven even started yet, and they won't be used for the nightly.

I would propose waiting for them to go through and then merging this. At least I am not seeing any testfailures that are LinAlg related.

**Review by Sacha0 — APPROVED** [review]
🎉

**Comment by ViralBShah** [comment]
This should fix #16653, #26162 when merged.

**Comment by ViralBShah** [comment]
I am marking as backport for 0.6.3 if @ararslan will allow it, as it will fix outstanding mac performance issues for 0.6 reported in the issues above.

**Comment by ararslan** [comment]
I'd like to freeze the 0.6.3 backports at this point, otherwise it risks continuously amassing new commits while I try to resolve the one remaining issue.

**Comment by ararslan** [comment]
Just because I'm curious: @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/27221#issuecomment-391938697):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9e28a7f50cf6f0e86a524bb06083c7140a9dbc10/e5f9a4c_vs_779cf84/report.md)
cc @ararslan

**Comment by ViralBShah** [comment]
Will nanosoldier build openblas 0.3 on this branch?

**Comment by vchuravy** [comment]
> Will nanosoldier build openblas 0.3 on this branch?
Yes nanosoldier doesn't use any caching besides ccache.

**Comment by ararslan** [comment]
Nanosoldier is broken right now and I haven't yet figured out why.

**Comment by ViralBShah** [comment]
Do we really need this on the 0.7 milestone? We can do this any time, given that it is completely non-breaking.

**Comment by ViralBShah** [comment]
We'll probably have openblas 0.3.1 by the time we release Julia 0.7. I have not yet seen anything major, and this looks like a good openblas release.

**Pull request merged**
