### PR TITLE
Fix build from source on alpine linux

### PR DESCRIPTION
**Pull request by tkelman**
carrying patches from:
- https://github.com/llvm-mirror/llvm/commit/ae8900a8833835309aecb0a3d947c2ae46fd86c3
- https://github.com/llvm-mirror/llvm/commit/32028c8f08ff146b4fbf93108cd519d025b312d3
- https://github.com/xianyi/OpenBLAS/pull/1257

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by quinnj** [comment]
Nice. do you have docker images somewhere based on alpine working?

**Comment by ararslan** [comment]
If there's an appropriate Docker image available we should be able to add Alpine to our CI testing on CircleCI, which would arguably be more valuable than having redundant glibc Linux builds.

**Comment by tkelman** [comment]
Something like https://github.com/tkelman/julia-alpine/blob/master/Dockerfile seems to be working so far. Can collapse that down, do a make install and remove build-only deps once it's done if you want a small image for deployment purposes.

**Comment by ararslan** [comment]
Good to merge?

**Comment by JeffBezanson** [comment]
Cool. Is there a released version of llvm/openblas including these changes, that we're likely to upgrade to?

**Comment by tkelman** [comment]
See the makefile comments - llvm 6.0.0 will include https://github.com/llvm-mirror/llvm/commit/ae8900a8833835309aecb0a3d947c2ae46fd86c3, llvm 5.0.0 should already include https://github.com/llvm-mirror/llvm/commit/32028c8f08ff146b4fbf93108cd519d025b312d3, openblas 0.2.21 was supposed to be a hotfix that already included https://github.com/xianyi/OpenBLAS/pull/1257 (and worth noting that upstream tests against alpine on their dev branch CI now) but ref https://github.com/xianyi/OpenBLAS/issues/1258, xianyi is kinda MIA and no one knows what the exact release plan is there.

I'm also somewhat curious whether this also works on a non-edge release of alpine but haven't tested that yet.

**Comment by ViralBShah** [comment]
Yes the OpenBLAS release schedule is unclear. I believe we need another matvec perf fix that @simonbyrne reported too - but digressing here. Do we need to run Package Evaluator on this, since these are LLVM patches that are late in the release cycle?

**Comment by tkelman** [comment]
The large patch should be an llvm-internal enum renaming rather than externally visible, but maybe clang or llvm.jl are worth testing to be sure this doesn't cause any problems there. It's also entirely possible that I missed something or made a mistake when rebasing those, so might also be good to verify it's not noticeable on nanosoldier if that's working properly right now

**Comment by ararslan** [comment]
cc @maleadt for LLVM.jl

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26358#issuecomment-371651282) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6dfda92d12c296a4b8563825d109016957ae7ae8/f699233_vs_c3ffa99/report.md). cc @ararslan

**Comment by maleadt** [comment]
Works fine with (what's currently covered by) LLVM.jl.

**Comment by ViralBShah** [comment]
Seems like there is quite a bit of regression on some of the tests. Should we wait to see how the llvm 6 stuff pans out and then do what's necessary? I suspect we could do the openblas stuff right away.

**Comment by KristofferC** [comment]
I am quite sure none of those "regressions" are from this PR. They are very spread and most of the groups with regressions also have improvements, just showing that they are noisy.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26358#issuecomment-372062152) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e7186f8a12e6b502d7c8e7a535d5a7b629b5da1d/af02f19_vs_e47ae98/report.md). cc @ararslan

**Comment by ararslan** [comment]
Bump. Anything else needed here?

**Comment by ViralBShah** [comment]
Should we wait to see the situation on llvm 6 before deciding here?

**Comment by tkelman** [comment]
Why? LLVM 6 almost certainly will break more than this would.

**Review by vchuravy — APPROVED** [review]
LGTM

**Comment by KristofferC** [comment]
Rerunning CI because it was 9 days ago.

**Comment by vchuravy** [comment]
Patch: `llvm-D28476-musl-targetlibraryinfo_3.9` breaks compilation with `BUILD_LLVM_CLANG=1`

```
/home/vchuravy/src/julia/deps/srccache/llvm-3.9.1/tools/clang/lib/CodeGen/BackendUtil.cpp:256:14: error: ‘Func’ is not a member of ‘llvm::LibFunc’
     LibFunc::Func F;
              ^~~~
/home/vchuravy/src/julia/deps/srccache/llvm-3.9.1/tools/clang/lib/CodeGen/BackendUtil.cpp:258:38: error: ‘F’ was not declared in this scope
       if (TLII->getLibFunc(FuncName, F))

```

**Pull request merged**
