### PR TITLE
Update microbenchmarks to run on release-0.4

### PR DESCRIPTION
**Pull request by jiahao**
This PR updates the microbenchmarks on the `release-0.4` branch and incorporates the modernized Go benchmarks kindly provided by @btracey in #13133 and #13251.

Current status
- [x] ~~C `mandel` benchmark needs to be fixed because of constant folding at the `-O1` and `-O2` levels~~ (fixed in 46076df) 
- [ ] Needs to be ported back onto master. An additional change must be made because of the new out-of-place build locations of the dependencies

### CODE REVIEW

**Comment by tkelman** [comment]
ok - is this for the new go benchmarks or the old ones?

**Comment by jiahao** [comment]
9a9c723 is for the new go benchmarks. I think it would be easiest to cherry-pick #13133 onto this branch.

**Comment by tkelman** [comment]
agreed

**Comment by jiahao** [comment]
There's a problem with `mandel` on `gcc-4.9.2`. It looks like the compiler is optimizing out the entire computation at `-O1` and `-O2`:

```
ᐅ  grep mandel benchmarks/c1.csv 
c,mandel,0.003920
c,mandel,0.003920
c,mandel,0.003910
c,mandel,0.003910
c,mandel,0.003910
ᐅ  grep mandel benchmarks/c2.csv 
c,mandel,0.000000
c,mandel,0.000000
c,mandel,0.000000
c,mandel,0.000000
c,mandel,0.000000
ᐅ  grep mandel benchmarks/c3.csv 
c,mandel,0.420010
c,mandel,0.419209
c,mandel,0.419610
c,mandel,0.419970
c,mandel,0.419910
```

**Comment by jiahao** [comment]
Thanks to a tip from @vtjnash the `mandel` benchmark seems to be behaving again.

Here are the current benchmark numbers:

<table class="benchmarks">
<colgroup>
<col class="name"></col>
<col class="relative" span="11"></col>
</colgroup>
<thead>
<tr><td></td><th class="system">Fortran</th><th class="system">Julia</th><th class="system">Python</th><th class="system">R</th><th class="system">Matlab</th><th class="system">Octave</th><th class="system">Mathe-matica</th><th class="system">JavaScript</th><th class="system">Go</th><th class="system">LuaJIT</th><th class="system">Java</th></tr>
<tr><td></td><td class="version">gcc </td><td class="version">0.5.0-dev
</td><td class="version">2.7.9
</td><td class="version">3.1.2
</td><td class="version">R2014a
</td><td class="version">3.8.2
</td><td class="version">10.2.0
</td><td class="version">V8 3.28.71.19
</td><td class="version">go1.3.3
</td><td class="version">gsl-shell 2.3.1
</td><td class="version">1.8.0_45
</td></tr>
</thead>
<tbody>
<tr><th>fib</th><td class="data">0.69</td><td class="data">2.10</td><td class="data">78.66</td><td class="data">555.16</td><td class="data">4314.33</td><td class="data">8867.51</td><td class="data">122.01</td><td class="data">3.40</td><td class="data">2.30</td><td class="data">1.97</td><td class="data">2.75</td></tr>
<tr><th>parse_int</th><td class="data">4.50</td><td class="data">1.45</td><td class="data">12.67</td><td class="data">50.34</td><td class="data">1559.48</td><td class="data">9023.60</td><td class="data">15.05</td><td class="data">5.93</td><td class="data">3.26</td><td class="data">5.72</td><td class="data">3.38</td></tr>
<tr><th>quicksort</th><td class="data">1.30</td><td class="data">1.13</td><td class="data">31.46</td><td class="data">239.77</td><td class="data">55.07</td><td class="data">1805.13</td><td class="data">40.85</td><td class="data">2.69</td><td class="data">1.03</td><td class="data">2.60</td><td class="data">2.58</td></tr>
<tr><th>mandel</th><td class="data">0.91</td><td class="data">0.87</td><td class="data">14.40</td><td class="data">56.08</td><td class="data">63.13</td><td class="data">474.33</td><td class="data">5.51</td><td class="data">0.74</td><td class="data">1.22</td><td class="data">0.74</td><td class="data">1.50</td></tr>
<tr><th>pi_sum</th><td class="data">1.00</td><td class="data">1.00</td><td class="data">14.25</td><td class="data">15.03</td><td class="data">1.28</td><td class="data">282.63</td><td class="data">1.69</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td></tr>
<tr><th>rand_mat_stat</th><td class="data">1.31</td><td class="data">1.75</td><td class="data">16.82</td><td class="data">17.02</td><td class="data">10.30</td><td class="data">36.84</td><td class="data">5.60</td><td class="data">2.30</td><td class="data">3.12</td><td class="data">3.35</td><td class="data">3.94</td></tr>
<tr><th>rand_mat_mul</th><td class="data">3.42</td><td class="data">1.04</td><td class="data">1.13</td><td class="data">6.48</td><td class="data">1.12</td><td class="data">1.13</td><td class="data">1.16</td><td class="data">15.11</td><td class="data">1.76</td><td class="data">1.10</td><td class="data">2.36</td></tr>
</tbody>
</table>

**Comment by mauro3** [comment]
Matlab 2015b is supposed to have a new JIT (that came up on the mailing list), maybe include that?

**Comment by jiahao** [comment]
I'll update my site license and find out for the actual numbers to be posted to the website.

**Comment by jiahao** [comment]
Here are updated benchmarks for Matlab R2015b and Octave 4.0.0.

Matlab's new JIT significantly improves the performance of its benchmarks, in many cases by over an order of magnitude from R2014a. In contrast, Octave seems exhibit somewhat of a slowdown from 3.8.2.

<table class="benchmarks">
<colgroup>
<col class="name"></col>
<col class="relative" span="11"></col>
</colgroup>
<thead>
<tr><td></td><th class="system">Fortran</th><th class="system">Julia</th><th class="system">Python</th><th class="system">R</th><th class="system">Matlab</th><th class="system">Octave</th><th class="system">Mathe-matica</th><th class="system">JavaScript</th><th class="system">Go</th><th class="system">LuaJIT</th><th class="system">Java</th></tr>
<tr><td></td><td class="version">gcc 4.9.2
</td><td class="version">0.4.0-rc2
</td><td class="version">2.7.9
</td><td class="version">3.1.2
</td><td class="version">R2015b
</td><td class="version">4.0.0
</td><td class="version">10.2.0
</td><td class="version">V8 3.28.71.19
</td><td class="version">go1.3.3
</td><td class="version">gsl-shell 2.3.1
</td><td class="version">1.8.0_45
</td></tr>
</thead>
<tbody>
<tr><th>fib</th><td class="data">0.68</td><td class="data">2.08</td><td class="data">78.10</td><td class="data">534.18</td><td class="data">28.13</td><td class="data">9911.04</td><td class="data">122.91</td><td class="data">3.38</td><td class="data">2.29</td><td class="data">1.96</td><td class="data">2.72</td></tr>
<tr><th>parse_int</th><td class="data">4.50</td><td class="data">1.45</td><td class="data">12.77</td><td class="data">50.36</td><td class="data">811.96</td><td class="data">10175.76</td><td class="data">15.22</td><td class="data">5.91</td><td class="data">3.30</td><td class="data">5.72</td><td class="data">3.38</td></tr>
<tr><th>quicksort</th><td class="data">1.30</td><td class="data">1.13</td><td class="data">31.70</td><td class="data">233.57</td><td class="data">4.88</td><td class="data">2097.64</td><td class="data">41.61</td><td class="data">2.66</td><td class="data">1.04</td><td class="data">1.99</td><td class="data">2.58</td></tr>
<tr><th>mandel</th><td class="data">0.91</td><td class="data">0.87</td><td class="data">14.46</td><td class="data">53.54</td><td class="data">8.37</td><td class="data">533.09</td><td class="data">5.51</td><td class="data">0.73</td><td class="data">1.22</td><td class="data">0.74</td><td class="data">1.49</td></tr>
<tr><th>pi_sum</th><td class="data">1.00</td><td class="data">1.00</td><td class="data">14.17</td><td class="data">13.61</td><td class="data">1.00</td><td class="data">349.35</td><td class="data">1.68</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td></tr>
<tr><th>rand_mat_stat</th><td class="data">1.32</td><td class="data">1.62</td><td class="data">16.80</td><td class="data">17.95</td><td class="data">14.66</td><td class="data">31.82</td><td class="data">5.66</td><td class="data">2.30</td><td class="data">3.11</td><td class="data">3.28</td><td class="data">3.89</td></tr>
<tr><th>rand_mat_mul</th><td class="data">3.36</td><td class="data">1.02</td><td class="data">1.12</td><td class="data">6.38</td><td class="data">1.11</td><td class="data">1.39</td><td class="data">1.13</td><td class="data">16.71</td><td class="data">1.71</td><td class="data">1.09</td><td class="data">2.34</td></tr>
</tbody>
</table>

**Comment by jiahao** [comment]
One last update:

- gcc 4.9.2 ⟶ 5.1.1
- go 1.3.3 ⟶ 1.5
- R 3.1.2 ⟶ 3.2.2

<table class="benchmarks">
<colgroup>
<col class="name"></col>
<col class="relative" span="11"></col>
</colgroup>
<thead>
<tr><td></td><th class="system">Fortran</th><th class="system">Julia</th><th class="system">Python</th><th class="system">R</th><th class="system">Matlab</th><th class="system">Octave</th><th class="system">Mathe-matica</th><th class="system">JavaScript</th><th class="system">Go</th><th class="system">LuaJIT</th><th class="system">Java</th></tr>
<tr><td></td><td class="version">gcc 5.1.1
</td><td class="version">0.4.0-rc2
</td><td class="version">2.7.9
</td><td class="version">3.2.2
</td><td class="version">R2015b
</td><td class="version">4.0.0
</td><td class="version">10.2.0
</td><td class="version">V8 3.28.71.19
</td><td class="version">go1.5
</td><td class="version">gsl-shell 2.3.1
</td><td class="version">1.8.0_45
</td></tr>
</thead>
<tbody>
<tr><th>fib</th><td class="data">0.70</td><td class="data">2.08</td><td class="data">78.45</td><td class="data">514.35</td><td class="data">27.40</td><td class="data">9700.62</td><td class="data">117.32</td><td class="data">3.35</td><td class="data">1.85</td><td class="data">1.95</td><td class="data">2.72</td></tr>
<tr><th>parse_int</th><td class="data">5.08</td><td class="data">1.45</td><td class="data">12.61</td><td class="data">41.05</td><td class="data">793.97</td><td class="data">10033.52</td><td class="data">14.83</td><td class="data">6.02</td><td class="data">2.79</td><td class="data">5.61</td><td class="data">3.35</td></tr>
<tr><th>quicksort</th><td class="data">1.30</td><td class="data">1.13</td><td class="data">31.46</td><td class="data">258.21</td><td class="data">4.98</td><td class="data">2106.40</td><td class="data">40.33</td><td class="data">2.68</td><td class="data">1.05</td><td class="data">1.99</td><td class="data">2.37</td></tr>
<tr><th>mandel</th><td class="data">0.81</td><td class="data">0.79</td><td class="data">12.98</td><td class="data">53.11</td><td class="data">7.51</td><td class="data">486.61</td><td class="data">4.97</td><td class="data">0.66</td><td class="data">1.10</td><td class="data">0.67</td><td class="data">1.36</td></tr>
<tr><th>pi_sum</th><td class="data">1.00</td><td class="data">1.00</td><td class="data">14.24</td><td class="data">9.54</td><td class="data">1.00</td><td class="data">343.69</td><td class="data">1.68</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td></tr>
<tr><th>rand_mat_stat</th><td class="data">1.45</td><td class="data">1.61</td><td class="data">16.53</td><td class="data">14.49</td><td class="data">14.63</td><td class="data">31.68</td><td class="data">5.54</td><td class="data">2.30</td><td class="data">2.98</td><td class="data">3.28</td><td class="data">3.91</td></tr>
<tr><th>rand_mat_mul</th><td class="data">3.49</td><td class="data">1.01</td><td class="data">1.12</td><td class="data">1.56</td><td class="data">1.11</td><td class="data">1.12</td><td class="data">1.13</td><td class="data">15.01</td><td class="data">1.40</td><td class="data">1.10</td><td class="data">2.34</td></tr>
</tbody>
</table>

**Comment by dpsanders** [comment]
@oheim proposed some new benchmarks for Octave in https://github.com/JuliaLang/julia/issues/13042

**Comment by jiahao** [comment]
Yes, but that issue has not been resolved. See that issue for the timing difference between those benchmarks.

**Comment by ScottPJones** [comment]
It might be nice to highlight the fastest time in each row.
Does this now have the current released versions of each platform (except for Python)?
(Python really should have both 2.7.10 & 3.5.0)

**Comment by jiahao** [comment]
I've installed Anaconda Python 2.7.10 and 3.4.3 and timed the benchmarks on both. It's interesting that Python 3 is significantly faster on almost all of them. The question is whether it's desirable to report both in the main benchmarks.

cc: @StefanKarpinski 

<table class="benchmarks">
<colgroup>
<col class="name"></col>
<col class="relative" span="12"></col>
</colgroup>
<thead>
<tr><td></td><th class="system">Fortran</th><th class="system">Julia</th><th class="system">Python</th><th class="system">Python</th><th class="system">R</th><th class="system">Matlab</th><th class="system">Octave</th><th class="system">Mathe-matica</th><th class="system">JavaScript</th><th class="system">Go</th><th class="system">LuaJIT</th><th class="system">Java</th></tr>
<tr><td></td><td class="version">gcc 4.9.2
</td><td class="version">0.4.0-rc2
</td><td class="version">2.7.10
</td><td class="version">3.4.3
</td><td class="version">3.2.2
</td><td class="version">R2015b
</td><td class="version">4.0.0
</td><td class="version">10.2.0
</td><td class="version">V8 3.28.71.19
</td><td class="version">go1.5
</td><td class="version">gsl-shell 2.3.1
</td><td class="version">1.8.0_45
</td></tr>
</thead>
<tbody>
<tr><th>fib</th><td class="data">0.69</td><td class="data">2.09</td><td class="data">97.58</td><td class="data">77.84</td><td class="data">517.99</td><td class="data">27.02</td><td class="data">9744.10</td><td class="data">118.08</td><td class="data">3.38</td><td class="data">1.86</td><td class="data">1.98</td><td class="data">2.74</td></tr>
<tr><th>parse_int</th><td class="data">4.50</td><td class="data">1.45</td><td class="data">20.91</td><td class="data">16.62</td><td class="data">45.71</td><td class="data">800.16</td><td class="data">10253.76</td><td class="data">14.75</td><td class="data">6.02</td><td class="data">2.77</td><td class="data">5.48</td><td class="data">3.37</td></tr>
<tr><th>quicksort</th><td class="data">1.30</td><td class="data">1.13</td><td class="data">46.66</td><td class="data">32.55</td><td class="data">262.35</td><td class="data">4.96</td><td class="data">2119.84</td><td class="data">40.77</td><td class="data">2.67</td><td class="data">1.05</td><td class="data">2.61</td><td class="data">2.60</td></tr>
<tr><th>mandel</th><td class="data">0.91</td><td class="data">0.87</td><td class="data">20.54</td><td class="data">16.81</td><td class="data">61.18</td><td class="data">8.26</td><td class="data">542.91</td><td class="data">5.49</td><td class="data">0.73</td><td class="data">1.22</td><td class="data">0.73</td><td class="data">1.50</td></tr>
<tr><th>pi_sum</th><td class="data">1.00</td><td class="data">1.00</td><td class="data">20.91</td><td class="data">21.74</td><td class="data">9.54</td><td class="data">1.00</td><td class="data">344.40</td><td class="data">1.68</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.00</td></tr>
<tr><th>rand_mat_stat</th><td class="data">1.32</td><td class="data">1.61</td><td class="data">21.15</td><td class="data">17.76</td><td class="data">14.51</td><td class="data">14.55</td><td class="data">32.27</td><td class="data">5.57</td><td class="data">2.31</td><td class="data">2.98</td><td class="data">3.26</td><td class="data">3.92</td></tr>
<tr><th>rand_mat_mul</th><td class="data">3.35</td><td class="data">1.00</td><td class="data">1.13</td><td class="data">1.13</td><td class="data">1.56</td><td class="data">1.12</td><td class="data">1.12</td><td class="data">1.13</td><td class="data">15.09</td><td class="data">1.41</td><td class="data">1.10</td><td class="data">2.35</td></tr>
</tbody>
</table>

**Comment by vtjnash** [comment]
my vote is just to go with the faster python3 numbers

**Comment by ScottPJones** [comment]
Since probably over 50% of Python users are still stuck on 2.x, I still would show both - it's almost like two different languages.

**Comment by btracey** [comment]
My colleague @kortschak updated the perf.go file to use the Go testing harness (while keeping the output the same). This significantly reduces the noise in the benchmarks. He also found some remaining inconsistencies between the Go algorithm and the intended Julia algorithm. Which branch should I propose the changes to? The numbers here suggest that my previous PR is being used, but my actual PR says it was closed without being accepted.

Thanks

**Comment by tkelman** [comment]
At the moment you can propose changes to `cjh/mubench-fix`

**Comment by btracey** [comment]
Thanks. Done.

**Comment by ScottPJones** [comment]
If having different versions of Python on the main page is too much, what about just putting Python 3.5 (3.4.3 is no longer the current release version), and having more complete numbers available as a csv file, with 2.7.10, maybe also have numbers for Julia 3.11(? whatever latest is), which would help encourage people to upgrade (as soon as 0.4.0 is really released).

**Comment by jiahao** [comment]
@btracey I cherry-picked the commits from your previous PR here and it will go into the release branch (and master later) after this branch is merged in. sorry if it's unclear.

@ScottPJones Anaconda's distribution has yet to catch up and it's not worth my time to upgrade manually.

**Comment by btracey** [comment]
@jiahao , an updated PR is https://github.com/JuliaLang/julia/pull/13251

**Comment by StefanKarpinski** [comment]
I would just report the best Python times in the main page. When we originally wrote these, Python 3 was slower than Python 2 and I think you still couldn't use NumPy with Python 3.

**Comment by jiahao** [comment]
Sounds like switching to Python 3 is the simplest solution.

**Comment by jiahao** [comment]
Ok, I think this covers everything. Thanks to @btracey for catching a logic error in the Go quicksort benchmark.

**Comment by kortschak** [comment]
Please note some changes that should be added to the Go perf code.

https://github.com/JuliaLang/julia/pull/13251#discussion_r40042114
https://github.com/JuliaLang/julia/pull/13251#discussion_r40042221

**Comment by ninjin** [comment]
It would be great if we could have some sort of background colour indicator of relative speed for each benchmark.  Sorry to only bring ideas and no code to back it up with.

**Comment by ScottPJones** [comment]
@ninjin Yes, that would be even better than what I'd suggested
>It might be nice to highlight the fastest time in each row.

**Comment by jiahao** [comment]
Thanks to @btracey and @kortschak's fixes and improvements, the Go microbenchmarks are now significantly faster.

 |   Julia 0.4.0-rc2 | go1.5 (before) | go1.5 (now)
--- | --- | --- | ---
fib      | 2.08 | 2.74 | 1.80
parse_int   | 1.47 | 2.77 | 1.17 
quicksort   | 1.13 | 2.61 | 1.28 
mandel     | 0.87 | 1.50 | 1.22
pi_sum     | 1.00 | 1.00 | 1.00
rand_mat_stat | 1.63 | 3.26 | 2.78 
rand_mat_mul  | 1.02 | 1.10 | 1.19

**Comment by nalimilan** [comment]
So, now starts the race to beat Go at the fib and parse_int benchmarks? ;-)

**Comment by jiahao** [comment]
Merged. PRs for improved reporting welcomed separately.

**Comment by jiahao** [comment]
Ref: f7eeb1a9f33f9d62582a044cd4df7534770c0cea - re-spell location of OpenBLAS in Go blas dependency

**Comment by hayd** [comment]
@jiahao conda should have python 3.5 http://continuum.io/blog/python35

**Pull request merged**
