### PR TITLE
[WIP] Set `CMAKE_AR` and `CMAKE_RANLIB`

### PR DESCRIPTION
**Pull request by staticfloat**
Since we set `CXX` and `CC`, we should probably set `AR` and `RANLIB` for `cmake` dependencies.

This is useful for our armv7l builder, that needs to override `ar` and `ranlib` so that `gcc-ar` and `gcc-ranlib` can be used, which know about things like LTO.

### CODE REVIEW

**Comment by tkelman** [comment]
what's the difference between gcc-ar and binutils ar?

should probably test this via clean from-scratch builds on all the buildbots

**Comment by staticfloat** [comment]
The difference is that `gcc-ar` knows how to load `gcc` plugins to do things like LTO.  Other than the enhancements offered by `gcc` plugins, it should function as a drop-in replacement.  I've tested this branch out on multiple different buildbots, but this is a great excuse to try out something new I've been building.  The buildtest buildbots are setup such that `AR=gcc-ar` will be passed on the ARM buildbot (which is where this is needed) and not on the others, the following test should give us confidence that this simultaneously works when it's needed, and also doesn't do anything to a default build:

@jlbuild !nuke !filter=arm,linux64

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/ce16585d2709ea71b62f9fafc5e4e4056fc71794

I will edit this comment as the build jobs complete.

**Comment by yuyichao** [comment]
> AR=gcc-ar will be passed on the ARM buildbot (which is where this is needed)

I don't think it's needed, ref https://github.com/staticfloat/julia-buildbot/issues/58#issuecomment-257095571

**Comment by staticfloat** [comment]
> I don't think it's needed, ref staticfloat/julia-buildbot#58 (comment)

Confirmed that it is not needed in this case, so that's nice.  I'm building new buildbot images incorporating that change.

I think this PR is still reasonable however, as the `AR` we use for `cmake` dependencies should mirror those used by non-`cmake` dependencies, IMO.

**Comment by yuyichao** [comment]
> should mirror those used by non-cmake dependencies

Sure. Sounds reasonable.

**Pull request merged**
