### PR TITLE
inlining: avoid `Union` computations in the inliner call analysis

### PR DESCRIPTION
**Pull request by aviatesk**
By reusing `MethodMatch.fully_covers` information.
I think this logic would be valid if the analysis accounts for "no method error" (corresponding to the `length(meth) == 0` cases).

### CODE REVIEW

**Comment by vtjnash** [comment]
How does performance compare?

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/44095#issuecomment-1033998071) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/a52d046_vs_dc0aa61/report.md).

**Review by Keno — APPROVED** [review]
Seems fine by me. I did the same for the purity code, which needs to know the same information, so we're already relying on correctness.

**Pull request merged**
