### PR TITLE
turn on linear IR

### PR DESCRIPTION
**Pull request by JeffBezanson**
This should be a fairly agreeable version of #24027. All calls are pulled out of argument position, but are still allowed as any assignment RHS and as arguments to `return`. The Expr `.typ` field is still there. I updated codevalidation.jl with the rules implemented here, and got it passing on everything. I hacked in a solution for `cglobal` by pre-evaluating constant tuples in `jl_resolve_globals`.

This only increases the sysimg by about 15%, and with a few more things like #24109 I think we'll be fine. I think we should merge this soon and work on optimizations later.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/24113):
```
NanosoldierError: failed to run benchmarks against primary commit: stored type BenchmarkTools.ParametersPreV006 does not match currently loaded type
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2da0b45cc0be6486c6f7798073480174486eb1b7/9faa137_vs_0504584/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Nanosoldier won't be functional again until https://github.com/JuliaIO/JLD.jl/issues/196 is fixed.

**Comment by JeffBezanson** [comment]
Ah, `llvmcall` has the same problem as `cglobal`, but more complex. It will probably have to be a macro that expands to a `foreigncall`.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24113#issuecomment-344381739) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a638dabb43c3dbbf39ec9f6f125d13ce82f0de76/d5c56f4_vs_9b1b1bd/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24113#issuecomment-344484955) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4688da05332a7e4599a904e748ff2705f886aed7/24f537f_vs_973e059/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24113#issuecomment-344667023) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3c2c1c76c4831ad93197a0dfac082f32cd775e6e/e38ba88_vs_8c8fb67/report.md). cc @ararslan

**Comment by StefanKarpinski** [comment]
Oy vey. Some of those regressions!

**Comment by quinnj** [comment]
Looks like it's almost entirely `SubArray` benchmarks w/ significant regressions though, so at least it's targeted.

**Comment by JeffBezanson** [comment]
Yep, looks scary but not a huge deal. I've been picking these off one by one.

**Comment by vtjnash** [comment]
How is the performance of this for building the system image and running tests? On my machine, it seems to be about 25% slower at building and generated about 25% large AST data. But also seems to have emitted about 10% more functions (I'm not sure whether that's good or bad).
```
sysimg size breakdown (PR):
     sys data: 52669172
  isbits data: 28600958
      symbols:   260314
    tags list:  2679720
   reloc list: 10264512
    gvar list:    76048
    fptr list:   238240

sysimg size breakdown (master):
     sys data: 52659044
  isbits data: 22744512
      symbols:   266667
    tags list:  2589636
   reloc list:  9858840
    gvar list:    76232
    fptr list:   212744

```

**Comment by JeffBezanson** [comment]
Yes, I see the same numbers. I think we'll be able to simplify some of the optimization passes (probably including merging #23240) and add some more compact encodings of common patterns like ssavalue assignment. There are also lots of sequences like this:

```
        # meta: location subarray.jl reindex 179
        SSAValue(309) = SSAValue(103)
        # meta: pop location
```

that we can peephole optimize away. We'll see how far that gets us.

**Comment by JeffBezanson** [comment]
This now includes #23240, but using front-end linearization instead of its own linearize pass. Seems to help clean up some of the extra allocations in the benchmarks here. Let's see.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24113#issuecomment-345010168) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1833dc7fb72b1fa3119ffbe7d70888db841ad200/a3b9983_vs_7d7a456/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
Ok, it appears that adding some @yuyichao magic has indeed fixed the remaining performance regressions. I worked through a couple more bugs and I think this is working now.

**Comment by StefanKarpinski** [comment]
Everything’s coming up Milhouse!

**Comment by JeffBezanson** [comment]
This recent test is failing on this branch:

```
@test contains(get_llvm_noopt(foo24632, (Bool,), false), "!dereferenceable_or_null")
```

The reason appears to be that the better optimizations here are able to eliminate the `x` variable. This:
```
        x = #temp#@_5
        #= line 319 =#
        unless (x isa Main.Int)::Bool goto 25
```
became this:
```
        SSAValue(2) = #temp#@_5
        #= line 319 =#
        SSAValue(4) = (SSAValue(2) isa Main.Int)::Bool
        unless SSAValue(4) goto 27
```

I'm not sure why `x` gets this annotation but the temp variable it's initialized from doesn't (in the first version of the code).

**Comment by JeffBezanson** [comment]
Ok, I believe I've fixed that, by avoiding replacing `TypedSlot`s. @yuyichao would be good if you can take a look at this.

**Comment by JeffBezanson** [comment]
... In particular, in my latest commit I wasn't fully sure whether to return `true` or `false`.

**Comment by quinnj** [comment]
Looks like this needs a rebase; but the last CI run had quite a bit of green.

**Comment by Sacha0** [comment]
🎉!

**Pull request merged**
