### PR TITLE
document AbstractArray and doctest for Array

### LINKED ISSUE #19211: Meaning of type parameters for `Array`s is not discoverable
As pointed out by @alanedelman:

While typing `AbstractArray` indicates that there are two type parameters,
neither `?AbstractArray` nor `?Array` give information about what those parameters are for.

This also seems to be difficult to discover from http://docs.julialang.org/en/release-0.5/manual/arrays/

### PR DESCRIPTION
**Pull request by fredrikekre**
fix #19211

### CODE REVIEW

**Comment by dpsanders** [comment]
Great, thanks! I would add something like
```
A = Array{Float64}(2, 2);
```
where the `N` is inferred also.

**Comment by KristofferC** [comment]
Improvements can be added to future PRs.

**Comment by tkelman** [comment]
This needs to be added to the stdlib doc index to show up anywhere other than the repl

**Comment by fredrikekre** [comment]
`Array` is in stdlib, didn't find a suitable headline in https://github.com/JuliaLang/julia/blob/master/doc/src/stdlib/arrays.md for `AbstractArray`. Under constructors?

**Comment by tkelman** [comment]
guess so? we could call it "Constructors and Types" maybe?

**Pull request merged**
