### PR TITLE
[libgit2] Fix zlib stream abandonment causing clone error on 32-bit systems

### LINKED ISSUE #39617: win32: clone error on ci
I have seen this error on multiple PRs now (https://build.julialang.org/#/builders/2/builds/624/steps/14/logs/stdio, https://build.julialang.org/#/builders/2/builds/624/steps/14/logs/stdio for example):
```
Building HTML documentation.
/cygdrive/c/buildbot/worker/package_win32/build/usr/bin/julia.exe --startup-file=no --color=yes `cygpath -w /cygdrive/c/buildbot/worker/package_win32/build/doc/make.jl` linkcheck= doctest= buildroot=`cygpath -w /cygdrive/c/buildbot/worker/package_win32/build` texplatform= revise=
  Installing known registries into `C:\buildbot\worker\package_win32\build\doc\deps`
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: LoadError: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:Zlib, error inflating zlib stream)
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Types.jl:68
  [2] clone(io::IOContext{Base.PipeEndpoint}, url::String, source_path::String; header::String, credentials::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.GitTools C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\GitTools.jl:119
  [3] (::Pkg.Registry.var"#28#29"{IOContext{Base.PipeEndpoint}, String, Pkg.Registry.RegistrySpec})(tmp::String)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:164
  [4] mktempdir(fn::Pkg.Registry.var"#28#29"{IOContext{Base.PipeEndpoint}, String, Pkg.Registry.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem .\file.jl:734
  [5] mktempdir
    @ .\file.jl:732 [inlined]
  [6] download_registries(io::IOContext{Base.PipeEndpoint}, regs::Vector{Pkg.Registry.RegistrySpec}, depot::String)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:147
  [7] download_registries
    @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:140 [inlined]
  [8] download_default_registries(io::IOContext{Base.PipeEndpoint}; only_if_empty::Bool)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:112
  [9] download_default_registries(io::IOContext{Base.PipeEndpoint})
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:100
 [10] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1337
 [11] instantiate
    @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1336 [inlined]
 [12] instantiate(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1332
 [13] instantiate()
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1332
 [14] top-level scope
    @ C:\buildbot\worker\package_win32\build\doc\make.jl:8
in expression starting at C:\buildbot\worker\package_win32\build\doc\make.jl:8
caused by: GitError(Code:ERROR, Class:Zlib, error inflating zlib stream)
Stacktrace:
  [1] macro expansion
    @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\LibGit2\src\error.jl:110 [inlined]
  [2] clone(repo_url::SubString{String}, repo_path::String, clone_opts::LibGit2.CloneOptions)
    @ LibGit2 C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\LibGit2\src\repository.jl:459
  [3] clone(repo_url::SubString{String}, repo_path::String; branch::String, isbare::Bool, remote_cb::Ptr{Nothing}, credentials::LibGit2.CachedCredentials, callbacks::Dict{Symbol, Tuple{Ptr{Nothing}, Any}})
    @ LibGit2 C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\LibGit2\src\LibGit2.jl:583
  [4] clone(io::IOContext{Base.PipeEndpoint}, url::String, source_path::String; header::String, credentials::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.GitTools C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\GitTools.jl:109
  [5] (::Pkg.Registry.var"#28#29"{IOContext{Base.PipeEndpoint}, String, Pkg.Registry.RegistrySpec})(tmp::String)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:164
  [6] mktempdir(fn::Pkg.Registry.var"#28#29"{IOContext{Base.PipeEndpoint}, String, Pkg.Registry.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem .\file.jl:734
  [7] mktempdir
    @ .\file.jl:732 [inlined]
  [8] download_registries(io::IOContext{Base.PipeEndpoint}, regs::Vector{Pkg.Registry.RegistrySpec}, depot::String)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:147
  [9] download_registries
    @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:140 [inlined]
 [10] download_default_registries(io::IOContext{Base.PipeEndpoint}; only_if_empty::Bool)
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:112
 [11] download_default_registries(io::IOContext{Base.PipeEndpoint})
    @ Pkg.Registry C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\Registry\Registry.jl:100
 [12] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1337
 [13] instantiate
    @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1336 [inlined]
 [14] instantiate(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1332
 [15] instantiate()
    @ Pkg.API C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.7\Pkg\src\API.jl:1332
 [16] top-level scope
    @ C:\buildbot\worker\package_win32\build\doc\make.jl:8
```

Perhaps just bad network connection https://github.com/JuliaLang/julia/pull/39603#issuecomment-777373696 passed after a restart.

### PR DESCRIPTION
**Pull request by kimikage**
This backports libgit2 patch to fix zlib stream handling. xref: https://github.com/libgit2/libgit2/pull/5740

Fixes #39617

**Edit:** See #39791 for checksum error

### CODE REVIEW

**Comment by kimikage** [comment]
Note that no updates have been made to LibGit2 in Yggdrasil. I don't understand in what order it is better to keep consistency.

**Comment by Keno** [comment]
> I don't understand in what order it is better to keep consistency

Merge the Yggdrasil bump first, then add the patch here and bump the jll version (and checksums) in the same commit.

**Comment by kimikage** [comment]
The checksums for "LibGit2.v1.2.3.aarch64-linux-gnu.tar.gz" by "refresh_checksums.mk" and by manual are different. :confused:

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
I'm not sure there is justification to backport this to 1.6 at this stages. It's not really a bugfix and it has not been extensively tested, so there's always a possibility to expose fun new LLVM behavior. If it proves safe on master, it can go into 1.6.1.

**Comment by Keno** [comment]
(sorry left a comment on the wrong commit)

**Comment by kimikage** [comment]
I'm very sorry, but the checksum for aarch64-apple-darwin was (also) broken. :scream: It seems that an empty file was left behind.
cc: @keno

**Comment by Keno** [comment]
just put up a separate PR for the aarch64-apple-darwin checksum. That's not a supported platform on 1.6, so we don't even really need to backport it.

**Pull request merged**
