### PR TITLE
Add input function

### PR DESCRIPTION
**Pull request by SquidSinker**
I translated over a thousand lines of Python code aimed at beginners into Julia. Almost everything was as easy, if not easier. However, typing the combination of `println` and `readline` gets tiring very quickly. Python has the function `input`, which prints a message and returns an input, and so I thought Julia should have something similar.

Juno/Atom.jl has an input function that takes an input from an Atom dialog box; that might need to import from Base.

I'm not sure how to test `stdin`, would appreciate any pointers.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
For a function this simple, I think most maintainers would argue that you're better off recommending that users put this function into their startup.jl file so that it's always available. Why would they say that instead of just maintaining this very simple function in Julia? Because it doesn't compose well. For example, how do I use `input` with colored/bold/italic text? What if I only want to read a single character while in raw TTY mode? I'm sure any number of other arguments could be made, along with the argument that this function will need to be tested, documented, and maintained as Julia's stable API until at least 2.0.

**Comment by SquidSinker** [comment]
It's true, this is a very simple function, and it's not like this is significant functionality that Julia is lacking but it's something I feel beginners trip over.  I'll say that most people who will appreciate a function like this do not know anything about a `startup.jl` file.  You'll notice that many programming tutorials are full of examples like `input a number for the computer to guess` etc etc. 

It's these little things that make Python so great as a first programming language and is something I felt useful when learning, and teaching, Julia as, and to, absolute beginners.

But I'll understand if people do not want this.

**Comment by vtjnash** [comment]
I'm okay with this, but think the general feel will be that if typing the combination in your scripts is annoying, to just add the definition at the top yourself: `input(x) = (print(x); readline())`

**Comment by StefanKarpinski** [comment]
If all you want is a simple input function in a script, then you can define this in your script. For a proper input function in Julia itself, it should integrate into the REPL infrastructure properly and allow notebook environments to provide hooks for getting input in those environments instead.

**Comment by simeonschaub** [comment]
I also wonder whether `prompt` might be a better name than `input`. `input` seems like a weird name for a function like this, as the function itself isn't inputting anything.

**Comment by StefanKarpinski** [comment]
Agree: `prompt` is a much better name.

**Comment by musm** [comment]
This sounds like it just needs a decision to be made whether it is worth adding or not (and there are conflicting opinions on this), as a result the quickest way to resolve this is to discuss in triage and either accept or reject.

**Comment by StefanKarpinski** [comment]
It's fine to add but it should be called `prompt` and it should hook into the REPL infrastructure.

**Comment by JeffBezanson** [comment]
Yes that would be fine; it can go in REPL and use its nice editing features. Or maybe LineEdit can be factored out of REPL and it can go there?

**Comment by StefanKarpinski** [comment]
Triage thoughts:
- even though learning examples sometimes do this, it's pretty rare to write real programs that work this way
- if someone does want this functionality it's truly trivial to implement: the core is just `readline()`
- a better version would go in the REPL module, not Base, and be called `prompt`

**Comment by AbhiShake1** [comment]
> I translated over a thousand lines of Python code aimed at beginners into Julia. Almost everything was as easy, if not easier. However, typing the combination of `println` and `readline` gets tiring very quickly. Python has the function `input`, which prints a message and returns an input, and so I thought Julia should have something similar.
> 
> Juno/Atom.jl has an input function that takes an input from an Atom dialog box; that might need to import from Base.
> 
> I'm not sure how to test `stdin`, would appreciate any pointers.

I completely agree. If it worked on all platforms, would just be a nice thing to have since julia is so easy to write(not to mention fast due to implementation and caching) and separate println doesnt look that great(even if i wouldnt mind writing it)

**Pull request closed without merging**
