### PR TITLE
issue #27848: backport exp10(Float16) and exp10(Complex32)

### PR DESCRIPTION
**Pull request by johnfgibson**
for issue [#27848](https://github.com/JuliaLang/julia/issues/27848)

### CODE REVIEW

**Comment by ararslan** [comment]
How necessary is this? I'd really like to freeze 0.6.4 backports.

**Comment by ararslan** [comment]
Also typically changes should be backported by cherry-picking actual commits from master.

**Comment by ararslan** [comment]
Come to think of it, this is actually not backport eligible, since it's a feature.

**Comment by johnfgibson** [comment]
This seems like a bug

```
julia> exp10(Float16(1.0))
ERROR: StackOverflowError:
Stacktrace:
 [1] exp10(::Float16) at ./math.jl:295 (repeats 80000 times)

julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc350 (2018-05-28 20:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```
Sorry about the nonconformal back port and lack of test. My git is not the greatest, but I can add tests.

**Comment by ararslan** [comment]
Don't worry about it, I've identified the appropriate commit and will push it to my branch.

**Pull request closed without merging**
