### PR TITLE
Move `SHA` to be an external stdlib

### PR DESCRIPTION
**Pull request by staticfloat**
For the past few years, we have had `SHA` as a vendored copy, however
improvements have been made both to the vendored copy here in base as
well as to the registered copy living within `JuliaCrypto`.  This
eliminates the vendored copy and sets `SHA` up as an external stdlib
just like `Pkg`, `Tar`, and all of their friends, as well as merges the
improvements made to both into the external repository.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Any particular reason for moving the `GIT_URL` and `TAR_URL` variables?

**Comment by DilumAluthge** [comment]
Also, it looks like you need to commit the checksums, specifically `deps/checksums/SHA-7ac490dfa78449ae81354cff9471a317f211a8f6.tar.gz/stdlib/SHA-7ac490dfa78449ae81354cff9471a317f211a8f6/`.

**Comment by staticfloat** [comment]
> Any particular reason for moving the `GIT_URL` and `TAR_URL` variables?

It makes sense to have all the stdlib-specific stuff in their own files.

**Comment by DilumAluthge** [comment]
Makes sense to me.

Can you ping me when you merge this PR? I'll need to update the BumpStdlibs.jl bot to account for the new locations of the `GIT_URL` and `TAR_URL` variables.

**Comment by staticfloat** [comment]
This PR is hung up on #41528, as it breaks CI by triggering a new internal bug.

**Comment by vtjnash** [comment]
The contrib/new-stdlib.sh script probably should also be updated to write these values to the new location

**Comment by DilumAluthge** [comment]
Could we break this PR up into two separate parts? With one part doing only the "make SHA an external stdlib", and a separate PR doing the "new locations of the GIT_URL and TAR_URL variables"?

**Comment by staticfloat** [comment]
Okay, I rebased and dropped the second commit.

**Comment by staticfloat** [comment]
Rebased on latest `master`, let's see if we pass tests on linux32 now.

**Pull request merged**
