### PR TITLE
RFC: deprecate hex2num and num2hex, alternative to #22088

### PR DESCRIPTION
**Pull request by rfourquet**
This is point 2 in https://github.com/JuliaLang/julia/pull/22088#issuecomment-304446262. 

- `num2hex(x)` is deprecated in favor of `bits(x, hex)`, as `bits` is also a function to give the string representation of the bit pattern of a bitstype value.
- `hex2num(str)` is deprecated in favor of `reinterpret(T::Type, str)`: this one may be controversial, as it may also mean reinterpret the bytes in the string as a value of type `T`. For this last operation, this could also be done more explicitly by `reinterpret(T, Vector{UInt8}(str))`.
An alternative to `reinterpret` would be to use `parse` with e.g. a `binary=true` keyword.

This is based off #22039, which was fixing bugs in those functions (this present PR introduces only one new commit).

### CODE REVIEW

**Comment by dpsanders** [comment]
Isn't Hex2num just parse(s, 16)?

**Comment by mbauman** [comment]
Not quite — it's `reinterpret(Float64, parse(UInt64, s, 16))`.

I think a hypothetical `parse(Float64, s, 16)` would interpret a string without decimals like `Float64(parse(Int64, s, 16))`.

**Comment by tkelman** [comment]
IMO reinterpret on a string is not the right function to use for this.

**Comment by rfourquet** [comment]
I'm also not convinced about `reinterpret` on a string, although it depends on the definition we give to `reinterpret`! I feel `parse` is also not the right function. Why not a new `frombits` functions (does the inverse of `bits`) ?

**Comment by fredrikekre** [comment]
Given #22088, is this still relevant?

**Comment by JeffBezanson** [comment]
Let's revive the useful non-num2hex parts of this.

**Comment by ViralBShah** [comment]
Do we still need this one - or can we close?

**Comment by rfourquet** [comment]
As the other straightforward deprecation of `num2hex/hex2num` was chosen, I'm not sure what is the "useful non-num2hex parts of this" Jeff is refering to. I personally still wish the `bitstring(x, hex)` as another spelling of `num2hex`.

**Comment by StefanKarpinski** [comment]
`bitstring(x, 16)` would be a perfectly ok spelling in my view, if you want to make a PR, but I have to say that I'm very strongly in favor of PRs that remove functions since we can always add methods to functions like `bitstring` in the future. What do you think the general rule would be for bases that don't have the property that the base divides the number of bits in `x`? Error? Pad with zeros to the length of the longest possible number of digits? I.e. `length(bitstring(typemax(x), base))`.

**Pull request closed without merging**
