### PR TITLE
RFC: unzip

### PR DESCRIPTION
**Pull request by bramtayl**
Just doc tests to start. I've never contributed such a big chunk of code, so I think I'm gonna need some help here.

### CODE REVIEW

**Comment by bramtayl** [comment]
Looks like I'm running into `UndefVarError(var=Symbol("@boundscheck")))))`. How do I get around that?

**Comment by bramtayl** [comment]
SOS

**Review by inkydragon — COMMENTED** [review]
You may import everything you need by `import .Base xxx`, even `+`.
Note: `+` has already imported.

https://github.com/JuliaLang/julia/blob/3799a7ef31e9542ed562d207390d24dd3e83384f/base/iterators.jl#L15

**Comment by bramtayl** [comment]
I give up. unzip currently lives in [LightQuery.jl](https://github.com/bramtayl/LightQuery.jl) , which is now published.

**Comment by StefanKarpinski** [comment]
Thanks for putting this up here. Please don't delete the branch—someone will pick this up at some point. It's a meaty problem getting a Base-ready version of this done here. Thank you for the prototype!

**Comment by inkydragon** [comment]
here is the code:
- [LightQuery.jl/Unzip.jl at master · bramtayl/LightQuery.jl](https://github.com/bramtayl/LightQuery.jl/blob/master/src/Unzip.jl)


### Some notes:

I tried for hours, build from source. Base on [julia/iterators.jl](https://github.com/JuliaLang/julia/blob/3799a7ef31e9542ed562d207390d24dd3e83384f/base/iterators.jl) (Those code need `_zip_iterator_eltype` & `_zip_iterator_size`, so you should use this version)

If I just `using` and `import` thing everything works well.
```julia
import .Base: push!, sizehint!, similar,
    empty, copyto!, ntuple
using .Base: _collect, @boundscheck, @inbounds, @default_eltype,
    ArgumentError, AbstractArray, foreach, !=, throw, Tuple, typeof, Dims
```
When add [some code](https://github.com/JuliaLang/julia/blob/3799a7ef31e9542ed562d207390d24dd3e83384f/base/iterators.jl#L1098-L1123), build fails with error:

    ....
    BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
    RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
    LoadError(at "compiler/compiler.jl" line 3: LoadError(at "compiler/bootstrap.jl" line 8: UndefVarError(var=:Broadcast)))

    make[1]: *** [/home/woclass/julia-1.0.3/Makefile:188：/home/woclass/julia-1.0.3/julia-win64/usr/lib/julia/corecompiler.ji] Error 1
    make: *** [/home/woclass/julia-1.0.3/Makefile:75：julia-sysimg] Error 2

In fact, it has nothing to do with `compiler/bootstrap.jl`, it's still related to those `unzip` code.

**Comment by bramtayl** [comment]
Updates: 

1) I figured out the variable number of items issue. It has to be handled basically the same way variable eltypes are: inference for zero length, and progressive widening otherwise (using `missing` as a filler).

2) The current version of LightQuery doesn't include `Unzip` anymore, but it does include `make_columns`, which is basically unzip for named tuples.

**Pull request closed without merging**
