### PR TITLE
Document how to make "type fields"

### PR DESCRIPTION
**Pull request by elextr**
See https://groups.google.com/forum/#!msg/julia-users/w45WVfSM3gc/Qaus9p0nHeAJ and #9443

### CODE REVIEW

**Comment by phobon** [comment]
This is not very clear to anyone who didn't read those discussions.

The description should probably be changed from "type fields" because that already refers to plain-old fields in composite types. Something like static fields (c++ish) or type attributes (python-ish) would be better. Also your setter example makes it seem like declaring an extra immutable type is necessary but it isn't. This would work equally well:

```
type MyType
    .
    .
    let a=0
        MyType() = a
        MyType(i) = a = i
    end
end
get_a(::Type{MyType}) = MyType()
set_a(::Type{MyType}, v) = MyType(v)
```

**Comment by elextr** [comment]
On 17 February 2015 at 04:06, Josh Langsfeld <notifications@github.com>
wrote:

> This is not very clear to anyone who didn't read those discussions.
>
> The description should probably be changed from "type fields" because that
> already refers to plain-old fields in composite types. Something like
> static fields (c++ish) or type attributes (python-ish) would be better.
> Also your setter example makes it seem like declaring an extra immutable
> type is necessary but it isn't. This would work equally well:
>
​Yeah, C++ uses the term "static member" and Python "class attribute" but
Julia doesn't (yet) have a term for them.  I was using the term "type
field" since they are effectively fields of the type object, whereas normal
fields are actually fields of the instance​, but Julia does tend to call
normal fields "type fields".  As both a C++ and Python programmer I'd be
happy with either suggestion but neither "static" or "attribute" has any
traction in Julia terminology, maybe "per type fields" "type object fields"
?


> type MyType
>     .
>     .
>     let a=0
>         MyType() = a
>         MyType(i) = a = i
>     end
> end
> get_a(::Type{MyType}) = MyType()
> set_a(::Type{MyType}, v) = MyType(v)
>
> ​That only works for one (whatever its gonna be called) field, you need
the immutable to distinguish the constructors when you have more than one,
​will make two examples to make that clearer.

​BTW does anyone know if its possible to squash commits when editing via
the github online editor, my search didn't find any way?  ​Or should I just
leave that to the committer?

**Comment by phobon** [comment]
> ​That only works for one (whatever its gonna be called) field, you need
> the immutable to distinguish the constructors when you have more than one,
> ​will make two examples to make that clearer.

My only point was that there are multiple ways to do the dispatch, which should be clear in the docs.

I wonder if there is a larger point to be made about constructors here. This all relies on inner constructors not actually creating a new object which appears to be at odds with the proper use of the language given in the rest of the manual. It seems odd that it would only be mentioned briefly in a specific question about emulating a specific feature.

**Comment by JeffBezanson** [comment]
I agree with @phobon; the description can be much simpler and should use a different term.

**Comment by elextr** [comment]
@JeffBezanson why close this?  Do you have a better term? So far nobody has suggested any.  Also I have been waiting to see if any of the changes on 0.4 break it.

**Pull request closed without merging**
