### PR TITLE
fix #50562, regression in `in` of tuple of Symbols

### LINKED ISSUE #50562: Type instability (allocations) regression in Julia v1.10-alpha1
We have some code in Trixi.jl that checks

```julia
if :i_backward in secondary_indices
```

where, `secondary_indices` is a tuple of `Symbol`s, see https://github.com/trixi-framework/Trixi.jl/blob/07981c3e50943a9bdb1a845f918a4e8831714338/src/solvers/dgsem_p4est/dg_2d.jl#L148

We observed a significantly increased amount of allocations when checking CI with Julia v1.10.0-alpha1 in https://github.com/trixi-framework/Trixi.jl/pull/1562. Locally, I checked that the allocations are gone when modifying the code above to

```julia
if any(==(:i_backward), secondary_indices)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #50562

### CODE REVIEW

**Comment by oscardssmith** [comment]
wasn't this intended to only target 1.10 rather than master?

**Comment by JeffBezanson** [comment]
@Keno What would be more convenient?

**Comment by Keno** [comment]
Only 1.10 please

**Comment by KristofferC** [comment]
Changed the branch to merge into to the 1.10 backport branch.

**Pull request merged**
