### PR TITLE
Add docstrings for days of the week

### PR DESCRIPTION
**Pull request by kshyatt**
Following https://github.com/JuliaLang/julia/pull/31218...

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Comment by fredrikekre** [comment]
How about this pattern instead:
````julia
const Monday, ...., = 1, ...
const Mon, ..., = 1, ...

"""
    Monday
    Mon

The first day of the week.

# Examples
```jldoctest
julia> Monday
1
```
"""
Mon, Monday

...
````

**Comment by kshyatt** [comment]
@fredrikekre I tried to match the pattern already in place for the months.

**Comment by fredrikekre** [comment]
> @fredrikekre I tried to match the pattern already in place for the months.

Change that too then :) I just think it is completely unecessary to maintain two different docstrings for aliases to the integers 1-7 (and 1-12 for the months).

**Comment by StefanKarpinski** [comment]
Is it possible to attache a single doc string to the symbols for the days? It would be pretty weird for the Monday doc string to be attached to the number 1.

**Comment by dkarrasch** [comment]
x-ref #31202

**Comment by kshyatt** [comment]
@fredrikekre is this better? I checked and tests passed and docs build (and the docstring lookup works).

**Comment by kshyatt** [comment]
Win32 and Travis errors are unrelated.

**Comment by fredrikekre** [comment]
I still don't think we need separate docstrings for the long and short names, why not just
````
const Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday = 1, 2, 3, 4, 5, 6, 7
const Mon, Tue, Wed, Thu, Fri, Sat, Sun = 1, 2, 3, 4, 5, 6, 7

"""
    Monday
    Mon

The first day of the week.

# Examples
```jldoctest
julia> Monday
1
```
"""
Monday, Mon

"""
    Tuesday
    Tue

The second day of the week.

# Examples
```jldoctest
julia> Tuesday
2
```
"""
Tuesday, Tue

...
````
etc?

**Comment by kshyatt** [comment]
Now even more sm0l

**Comment by kshyatt** [comment]
Anything else we want for this?

**Pull request merged**
