### PR TITLE
Export `strtod_c`/`strtof_c` from src/

### PR DESCRIPTION
**Pull request by quinnj**
Is this all I need to allow these to be ccall-able?
[ci skip]

### CODE REVIEW

**Comment by tkelman** [comment]
on the implementation too. [ci skip] needs to be in the commit message not just the pr description, but we shouldn't use it unless you've tested in all CI configurations and run `make check-whitespace` locally.

**Comment by quinnj** [comment]
> on the implementation too.
Not sure what you meant here. This seems to have passed all tests and I did indeed `make check-whitespace` locally and everything seemed fine. This also seems to solve the `strtod` problem I was seeing on windows (i.e. being able to use this instead of the system `strtod`). Ok to merge?

**Comment by tkelman** [comment]
You only added `DLLEXPORT` in the header. You also need to add it on the function in the `.c` file. Mingw isn't so picky, but having them not match is a compile error with MSVC.

**Comment by quinnj** [comment]
Everything look ok?

**Comment by tkelman** [comment]
Yeah but on second thought anything we export from libjulia should probably be prefixed by `jl_`

**Comment by quinnj** [comment]
I thought about that too, but there were a couple other functions in `support` that weren't so I thought it might be ok. I can do other ones too?

**Comment by tkelman** [comment]
ref #10682 and #11741, I don't think libsupport is honestly going to be used anywhere outside of Julia at this point

**Comment by quinnj** [comment]
So does that mean I should prefix them or not?

**Comment by tkelman** [comment]
IMO yes, at least the newly exported functions. If you want to catch any others while you're at it I think it would be a good cleanup. No one else has had enough of an opinion to say otherwise.

**Comment by quinnj** [comment]
Would this be ok to back port? Pretty please?

**Comment by tkelman** [comment]
only if you promise to be strict about `REQUIRE`ing the first patch release that has it

**Comment by quinnj** [comment]
Yes sir!

**Pull request merged**
