### PR TITLE
Add missing checksums for libgit2 0.28

### PR DESCRIPTION
**Pull request by nalimilan**
Should have been added by https://github.com/JuliaLang/julia/pull/32806.

### CODE REVIEW

**Comment by fredrikekre** [comment]
This is just the checksums for the source tarball, right? Also needs the BB checksums, e.g.
```
deps/checksums/LibGit2.v0.28.2-0.x86_64-linux-gnu.tar.gz/md5
deps/checksums/LibGit2.v0.28.2-0.x86_64-linux-gnu.tar.gz/sha512
```
and similar for the other architectures.

**Comment by nalimilan** [comment]
Ah, OK. Is there an automated way to generate these files?

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/blob/master/contrib/refresh_bb_tarballs.sh

**Comment by ararslan** [comment]
Should also delete the checksums for the version removed in the previous PR

**Comment by nalimilan** [comment]
Of course!

**Pull request merged**
