### PR TITLE
[backports-release-1.11] Make `String(::Memory)` copy

### LINKED ISSUE #54369: `String(v::Memory{UInt8})` doesn't make a copy
The docstring of `String` says:

> To avoid truncation
  of Vector{UInt8} data, use String(copy(v)); for other AbstractVector types,
  String(v) already makes a copy.

Since `Memory` is an `AbstractVector`, `String` should make a copy. However, it doesn't look like this is happening in:

https://github.com/JuliaLang/julia/blob/9d8e0e7016ad64890f81b1fd93c1d46de9588a02/base/strings/string.jl#L67-L71

```julia
julia> v = Memory{UInt8}(undef, 10);

julia> fill!(v, 0x01);

julia> String(v)
"\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01"

julia> v
0-element Memory{UInt8}
```

Maybe the current `String(v::Memory{UInt8})` method could be renamed to something like `take_string!` to make it clear that it can mutate `v`.

### PR DESCRIPTION
**Pull request by nhz2**
Manual backport of #54457 to fix #54369 in 1.11

### CODE REVIEW

**Comment by giordano** [comment]
https://buildkite.com/julialang/julia-release-1-dot-11/builds/325#01931891-b8f7-414d-8bce-0c0908b26d74/875-1652
```
The global RNG seed was 0xc55e57e524be7f332615c29ea9da899b.
Error in testset operators:
Test Failed at /cache/build/tester-amdci5-9/julialang/julia-release-1-dot-11/julia-114953cb48/share/julia/test/operators.jl:158
  Expression: +()
    Expected: MethodError
      Thrown: StackOverflowError
      StackOverflowError:
      Stacktrace:
       [1] +() (repeats 79984 times)
         @ Main.Test32Main_LinearAlgebra_matmul.TestMatmul /cache/build/tester-amdci5-9/julialang/julia-release-1-dot-11/julia-114953cb48/share/julia/stdlib/v1.11/LinearAlgebra/test/matmul.jl:1119
```
I seem to have seen this error before, maybe we need to backport some other patches.  @jishnub perhaps you remember what was it?  I thought it was #56184, which fixed #56136, but that was in a different testset.

**Comment by jishnub** [comment]
This was caused by https://github.com/JuliaLang/julia/pull/56089, and was fixed subsequently by https://github.com/JuliaLang/julia/pull/56184.

**Comment by giordano** [comment]
> and was fixed subsequently by https://github.com/JuliaLang/julia/pull/56184.

But that's changing `stdlib/LinearAlgebra/test/matmul.jl`, the failure is in `test/operators.jl`

**Comment by jishnub** [comment]
IIUC, the failure happens if the `test/operators.jl` is run in the same process after the LinearAlgebra `matmul` tests that introduce the stack-overflowing method. The offending method https://github.com/JuliaLang/julia/blob/2a6ce58958c37b804034272d42eb5c8f93e77cb1/stdlib/LinearAlgebra/test/matmul.jl#L1142 is committing type-piracy by defining `+() = +()`, so this would impact any subsequent invocation of `+()` that is run in the same process. This showed up in the `test/errorshow.jl` failure after the PR was merged, but apparently `test/operators.jl` also checks the same method.

**Comment by giordano** [comment]
I see, tests weren't isolated enough.  I pushed the backport to #56228, this [is failing also there anyway](https://buildkite.com/julialang/julia-release-1-dot-11/builds/324#01931827-d5a2-4f5b-84db-153e8724f139/743-920)

**Comment by KristofferC** [comment]
Feels a bit too intrusive to backport to a patch release, or?

**Comment by nhz2** [comment]
This fixes code like `String(str isa Vector{UInt8} ? copy(str) : str)` in https://github.com/JuliaData/Parsers.jl/pull/193

Since this is how the docs of `String` recommend copying an `AbstractVector{UInt8}` into a `String` there may be other existing packages that are fixed by this. This shouldn't break anything unless someone is using the internal `Base.StringMemory` to create a huge string, and there isn't enough memory left to make a copy.
Using `String` on a vector created with `Base.StringVector(len)` still avoids copying like before, since this only affects `String(::Memory)`.

**Pull request closed without merging**
