### PR TITLE
Explicitly test these constant methods for special functions that cov…

### PR DESCRIPTION
**Pull request by kshyatt**
…erage doesn't pick up

See https://app.codecov.io/gh/JuliaLang/julia/blob/master/base%2Fspecial%2Ftrig.jl for examples

### CODE REVIEW

**Comment by oscardssmith** [comment]
I'm not really sure how much value these tests have. They kind of seem like they will just make it annoying to change the implementation in the future for no real reason.

**Comment by kshyatt** [comment]
It’s mostly for the purposes of making the coverage report less annoying to
me

**Comment by nsajko** [comment]
I don't think this PR will actually help the coverage results. See the linked issue.

**Comment by kshyatt** [comment]
Fair enough. Happy to close this, then. I wonder if we should mark these
functions excluded from coverage and explain why?

**Comment by KristofferC** [comment]
Doing some coverage exclusion or similar seems like a better idea than basically duplicating the definitions of these functions into the test files.

**Pull request closed without merging**
