### PR TITLE
[REPL] Fix #55850 by using `safe_realpath` instead of `abspath` in `projname`

### LINKED ISSUE #55850: Wrong default REPL prompt when `JULIA_DEPOT_PATH` is a symlink
Found when trying to run tests on master but this happens all the way back to at least 1.5.

Discovered because of new tests.
```
Test Failed at /Users/christian/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/REPL/test/repl.jl:1971
  Expression: prompt == "(@v$(VERSION.major).$(VERSION.minor)) pkg> "
   Evaluated: "(v1.12) pkg> " == "(@v1.12) pkg> "
```

Seems like `projname(project_file::String)` only checks `abspath` instead of `safe_realpath` when comparing `envdir` and `project_file` https://github.com/JuliaLang/julia/blob/fc9f1470458ad6bdeb1f56c1150d651814a0a164/stdlib/REPL/src/Pkg_beforeload.jl#L89-L94

Repl walkthrough of my investigation:
```ChrichriMBP:~$ j +nightly
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1238 (2024-09-23)
 _/ |\__'_|_|_|\__'_|  |  Commit 0fade450a18 (0 days old master)
|__/                   |

julia> withenv("JULIA_DEPOT_PATH" => mktempdir(), "JULIA_LOAD_PATH" => nothing) do
              run(`$(Base.julia_cmd()[1]) --startup-file=no`)
          end
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1238 (2024-09-23)
 _/ |\__'_|_|_|\__'_|  |  Commit 0fade450a18 (0 days old master)
|__/                   |

julia> using REPL; REPL.Pkg_promptf()
[ Info: Precompiling REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] 
"(v1.12) pkg> "

julia> depot = Base.DEPOT_PATH |> first
"/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd"

julia> envdir = joinpath(depot, "environments")
"/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd/environments"

julia> project_file = REPL.find_project_file()
"/private/var/folders/4g/lnkpkf3s4rxd_wbl8vwnqs4r0000gn/T/jl_KEaptd/environments/v1.12/Project.toml"

julia> startswith(abspath(project_file), abspath(envdir)) # Line 91 in Pkg_beforeload.jl
false
```

### PR DESCRIPTION
**Pull request by christiangnrd**
Closes #55850.

### CODE REVIEW

**Comment by IanButterworth** [comment]
Pkg will need updating too https://github.com/JuliaLang/Pkg.jl/blob/ef9f76c175872bab6803da4a5fa3fd99bce3d03a/ext/REPLExt/REPLExt.jl#L50

Maybe Pkg should use `REPL.projname` instead. `promptf` is slightly different but `projname` might be a full copy.

**Comment by christiangnrd** [comment]
@IanButterworth You were too quick https://github.com/JuliaLang/Pkg.jl/pull/4025

**Comment by christiangnrd** [comment]
I can definitely update the PR to use REPL.projname that sounds like a good way to reduce code duplication

**Comment by christiangnrd** [comment]
@IanButterworth I don't have permission to request a review but this is ready for review.

**Comment by christiangnrd** [comment]
This should also probably be backported to 1.11 and 1.10. I'll submit a manual backport in Pkg.jl once this is accepted.

**Review by IanButterworth — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
