### PR TITLE
cosmetic fixes for `LinAlg.chksquare`

### LINKED ISSUE #292: export `Base.LinAlg.chksquare`
Rationale: checking that a matrix is square is a pretty common operation. While `chksquare` is a minor utility function, it is well-designed, useful, and allows standard error reporting. Without a common function, libraries end up implementing their own solutions or explicitly spell out something like

``` julia
n, m = size(A)
if n != m
    throw(ArgumentError("matrix is not square"))
```

or one of the countless variations. Standardizing this outside `Base.LinAlg` would be useful.

### LINKED ISSUE #14388: export `Base.LinAlg.chksquare`
Rationale: checking that a matrix is square is a pretty common operation. While `chksquare` is a minor utility function, it is well-designed, useful, and allows standard error reporting. Without a common function, libraries end up implementing their own solutions or explicitly spell out something like
```julia
n, m = size(A)
if n != m
    throw(ArgumentError("matrix is not square"))
```
or one of the countless variations. Standardizing this outside `Base.LinAlg` would be useful.

### PR DESCRIPTION
**Pull request by tpapp**
Closes JuliaLang/LinearAlgebra.jl#292, by
- renaming `chksquare` to `checksquare`
- writing documentation for `checksquare` and putting it in the stdlib docs (without exportingit from `LinAlg`)
- adding some simple tests for `checksquare`

### CODE REVIEW

**Comment by ViralBShah** [comment]
Cc @andreasnoack

**Comment by StefanKarpinski** [comment]
Didn't we want to export it too?

**Comment by tkelman** [comment]
I didn't. This lgtm as is.

**Comment by andreasnoack** [comment]
Yes. I agree.

**Pull request merged**
