### PR TITLE
test parser support for underscore curry

### PR DESCRIPTION
**Pull request by simeonschaub**
This is an initial implementation of the solution proposed in
https://github.com/JuliaLang/julia/pull/24990#issuecomment-439708350.
This is only the parser part to that, so it doesn't currently do
anything useful, but I am mainly putting this up so we can run PkgEval
on it to see how breaking this solution would be.

### CODE REVIEW

**Comment by simeonschaub** [comment]
Looks like Documenter doesn't like this already

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40860#issuecomment-844190718) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/00732ab_vs_fd4ca66/report.md). cc @maleadt

**Comment by simeonschaub** [comment]
> **991 packages failed tests only on the current version.**

GitHub won't even display the file... :cry:

**Comment by simeonschaub** [comment]
It does seem like most failures are coming from transitive dependencies on MacroTools, but this might still be a little bit too breaking. Some initial analysis:
```
 (945, MacroTools)
 (38, MatchImpl)
 (30, Unknown)
 (28, SyntaxError)
 (6, Match)
 (3, MatchCore)
 (3, PrintingChange)
 (1, CBinding)
 (1, NewExceptionType)
 (1, DocTest)
```

**Comment by simeonschaub** [comment]
Marking this for triage to decide whether this is the right approach regarding #24990 vs. only implementing that in lowering and if so, whether this has to be considered a breaking change, meaning it will have to wait for 2.0

**Comment by vtjnash** [comment]
Triage said this doesn't appear to really work. We also discussed that there isn't agreement about what rule to use for https://github.com/JuliaLang/julia/pull/24990

**Pull request closed without merging**
