### PR TITLE
store module bindings now in an array for safe, fast iteration

### PR DESCRIPTION
**Pull request by vtjnash**
Converts module bindings from a completely hidden custom htable_t to a less-hidden simplevector+index_array implementation.

This lets us query and iterate the bindings without needing to hold locks over the queries, making those operations more scalable, and safe to use across safe-points or concurrently. It is similar to how we already deal with specializations and datatype caches already.

Updates the smallintcache to additionally be more thread-safe for users too, with explicit acquire and release operations.

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/48212#issuecomment-1379388788) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f69e39a_vs_79ceb8d/report.html).

**Comment by maleadt** [comment]
> is pkgeval susceptible to false positives?

Not sure what you mean? Packages are, and despite PkgEval retrying failures it happens all the time that bad tests spoil the result. The only known issue with PkgEval is that the compilecache can 'break' when packages fail to build, see e.g. the DevIl issue, but that's rare and will be fixed as soon as we upgrade amdci to a newer version of Ubuntu.

**Comment by gbaraldi** [comment]
I was being dumb and clicked in the wrong place :(. Sorry for the ping, :\

**Pull request merged**
