### PR TITLE
move 0.6 NEWS.md section to HISTORY.md

### PR DESCRIPTION
**Pull request by Sacha0**
The time seems right :).

### CODE REVIEW

**Comment by Sacha0** [comment]
(Seems a few 0.7 changes ended up in the 0.6 section due to 0.6 remaining in NEWS.md till now. Will fix and push.)

**Comment by Sacha0** [comment]
Absent objections, I plan to merge these changes later this afternoon PT or later. Best!

**Review by fredrikekre — APPROVED** [review]
lgtm, perhaps time to remove deprecations too :)

**Comment by Sacha0** [comment]
Thanks @fredrikekre! :)

**Pull request merged**
