### PR TITLE
Add `RawFD` constructors as an alternative to `fd`

### PR DESCRIPTION
**Pull request by LilithHafner**
This provides an alternative to `fd` for getting the raw file descriptor of a File or IOStream. This is important because `fd` returns an `Int` which is a poor choice of return type in the presence of `Base.RawFD`. I copped most of the docstring and implementation from `fd`.

This allows folks to write `RawFD(::File)` instead of `RawFD(fd(::File)::Int)`, and eventually may enable us to deprecate `fd`.

See also: https://github.com/JuliaLang/julia/issues/51710

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Looks sensible to me. Would it make sense to backport this to 1.11 (then the docstring of course needs to be adjusted)

**Comment by LilithHafner** [comment]
`fd` no longer returns `Int` since #55080, making this less necessary, though still possibly a good idea.

**Comment by KristofferC** [comment]
```
error during bootstrap:
LoadError("sysimg.jl", 3, LoadError("Base.jl", 408, LoadError("libc.jl", 38, UndefVarError(:IOStream, Base.Libc))))
ijl_undefined_var_error at /cache/build/tester-amdci4-15/julialang/julia-master/src/rtutils.c:152
jl_eval_globalref at /cache/build/tester-amdci4-15/julialang/julia-master/src/interpreter.c:159 [inlined]
eval_value at /cache/build/tester-amdci4-15/julialang/julia-master/src/interpreter.c:202
eval_stmt_value at /cache/build/tester-amdci4-15/julialang/julia-master/src/interpreter.c:175 [inlined]
```

**Comment by LilithHafner** [comment]
@whomever, feel free to re-open if you want to see this through. I'm going to close because I no longer think it's necessary.

**Pull request closed without merging**
