### PR TITLE
Improve promote_op

### PR DESCRIPTION
**Pull request by p-zubieta**
This is the promised fix for #17794 (at least it works locally for me).

CC @JeffBezanson, @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by pabloferz** [comment]
@tkelman I made a mistake and force-pushed a commit. Can we try again?

**Comment by tkelman** [comment]
Okay, not sure exactly what this'll do. We'll also probably want to compare this against 0.5.0-rc0.

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/17929#issuecomment-238707210): `RemoteException(2,CapturedException(NanosoldierError: error when preparing/pushing to report repo: UndefVarError(:result),Any[( in printreport at BenchmarkJob.jl:481,1),( in open at iostream.jl:113,1),( in report at BenchmarkJob.jl:387,1),( in run at BenchmarkJob.jl:233,1),( in #503 at multi.jl:1410,1),( in run_work_thunk at multi.jl:996,1),( in macro expansion at multi.jl:1410 [inlined],1),( in #502 at event.jl:46,1)]))`
cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17929#issuecomment-238714003) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/dcc8ef262e409243d77898cc4beab522188f3551/fcd8683_vs_d64cfe4/report.md). cc @jrevels

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17929#issuecomment-238741663) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3020e6f86f11d95949fcfd40d117d2547cf00b2d/1040aa0_vs_acfd04c/report.md). cc @jrevels

**Comment by tkelman** [comment]
Okay, so relative to master, much better, relative to release-0.5 where #17389 was reverted there are just a couple of regressions and they're not too huge.

**Comment by pabloferz** [comment]
The remaining regressions seem to come from somewhere else. See https://github.com/JuliaCI/BaseBenchmarkReports/blob/07527ce784fc022b854f37a29230dad4816a6895/daily_2016_8_10/report.md

**Comment by tkelman** [comment]
Jeff, is this okay to merge?

**Comment by JeffBezanson** [comment]
Yes. Thanks @pabloferz .

**Comment by tkelman** [comment]
I'll plan to backport this for RC3, along with reverting dbdaf72b22078aa692875806b5ba20c8e7154e77 and e6f5d89f519f95ce71370bb44f62c387388cda35

**Pull request merged**
