### PR TITLE
Fix show_unquoted for :break and :continue

### LINKED ISSUE #15765: Printing of `Expr(:continue)`
In AWSLambda.jl there is [a macro](https://github.com/samoconnor/AWSLambda.jl/blob/master/src/AWSLambda.jl#L769) that takes a function and generates a string containing the body of the function.

It the function contains a `continue` statement, the function body string ends up containing, e.g.

```julia
        if length(r) == 0
            writecsv(out,[key,"?"])
            $(Expr(:continue))
        end
```
... where just `continue` was expected.

@toivoh: you previously helped out with the `clean_ex` function to remove line numbers. See #15299.
Any ideas on this one?

Another example
```julia
julia> ex = :(if true continue end)
:(if true # none, line 1:
        $(Expr(:continue))
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        $(Expr(:$, :(Expr(:continue))))
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        $(Expr(:$, :(Expr(:$,$(Expr(:quote, :(Expr(:continue))))))))
    end)
```

```julia
julia> ex = :(if true foo end)
:(if true # none, line 1:
        foo
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        foo
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        foo
    end)
```

### PR DESCRIPTION
**Pull request by samoconnor**
Fix #15765

### CODE REVIEW

**Comment by toivoh** [comment]
Thanks for making the PR!

**Comment by yuyichao** [comment]
I believe this leave an extra space at the end. These expressions should probably have their own branch and also handle the zero argument form of the other expressions in the current branch.

And as Tony have indicated, this need test.

**Comment by samoconnor** [comment]
@yuyichao: Thanks for the feedback. I don't think I fully understand the detail of this code. This PR is just a copy/paste of @toivoh' s suggestion. It is probably best for someone who is familiar with this part of the code to just make the change rather than explaining it to me step by step in PR comments.

**Comment by toivoh** [comment]
@yuyichao: Why do you think that `:continue` and `:break` should have their own branch? The place where I suggested to add this was intended as a convenient way to gather a number of expression types that have really simple printing.

**Comment by yuyichao** [comment]
Because:

> I believe this leave an extra space at the end

and

> also handle the zero argument form of the other expressions in the current branch.

I think adding sub branches to conditionally omit the space will be less clear than just use separate branches.

**Pull request closed without merging**
