### PR TITLE
Get rid of --lisp prompt

### PR DESCRIPTION
**Pull request by PallHaraldsson**
It shouldn't be exported (seems not needed, was always undocumented). I'll look into what more can go, but will be a separate PR likely.

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
"usage" found online, are snippets in forks of (outdated, e.g. using wmain in) Julia (unlikely to find many more (valid) examples):
https://cpp.hotexamples.com/examples/-/-/julia_init/cpp-julia_init-function-examples.html

**Comment by adienes** [comment]
why do you want to remove this? it's just a fun easter egg. I don't think anybody is taking this lisp too seriously as a piece of major / stable language functionality

**Comment by fingolfin** [comment]
This leaves `jl_lisp_prompt` itself in, now unused.

But in any case I agree with @adienes

**Comment by PallHaraldsson** [comment]
>why do you want to remove this?

I don't want it as exported API (for e.g. 1.12, not sure if it can disappear in 1.11.x), for people to think may be relied on, existing forever. For the CLI switch --lisp, yes a fun Easter egg, and flisp is going away I suppose at some point, I just don't think needed. Yes, jl_lisp_prompt itself is still in (dead-code eliminated?), could also go. Those that need --lisp can use Julia LTS, for I suppose 3+ years.

I don't think this does make Julia smaller yet, to any really degree, but it's a future plan.

**Comment by giordano** [comment]
> I wanted to test this, see size-change, but this didn't work

Juliaup uses the upload that happens after the tests complete successfully. You broke the tests for all the platforms.

> (usually such works, only for merged PRs?

Of course not, otherwise this wouldn't be much different than using a nightly build.

**Comment by PallHaraldsson** [comment]
@ViralBShah, I understand you closing, given the opposition, but should a lesser form of not just exporting for C API be wanted?

**Comment by Roger-luo** [comment]
What if change --flisp to print something as the future eastern egg so you can get rid of whatever you want while having fun.

**Pull request closed without merging**
