### PR TITLE
Deprecate indexing by Bool values

### PR DESCRIPTION
**Pull request by mbauman**
Note that this does not affect indexing by boolean arrays (logical masks).  Just `A[true]` and `A[false]`; the latter is a BoundsError and the former is almost certainly an error.

~~Also — this adds a warning during bootstrap since I overwrite the desired behavior with a deprecation. It means that simply deleting the deprecated method will do the right thing. Is that an ok tradeoff to make?~~

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Motivation?

**Comment by mbauman** [comment]
We're doing `eltype` chicanery to identify logical arrays.  That should eventually be fixed, too, but for now it makes it more obvious when this happens:

```
julia> (1:3)[[true,true,true]]
3-element Array{Int64,1}:
 1
 2
 3

julia> (1:3)[Any[true,true,true]]
3-element Array{Int64,1}:
 1
 1
 1
```

**Comment by fredrikekre** [comment]
Could add back the tests in a commend and add a note in deprecated.jl to activate them when deprecations are removed. It is likely that the tests won't be added otherwise.

**Comment by JeffBezanson** [comment]
I'd prefer not to have the method overwrite --- can instead put a comment in deprecated.jl saying what to change when the deprecation is removed.

**Comment by mbauman** [comment]
Ok, fixed the overwriting method and restored the tests using comments.  Also added NEWS.

@ararslan care to explain the thumbs down?  This will allow us to work harder at converting `Array{>:Bool}` to logical index in the future without breaking code.

**Comment by ararslan** [comment]
Yep, sorry. Misunderstood initially. 👍

**Review by ararslan — APPROVED** [review]

**Pull request merged**
