### PR TITLE
Type-stabilize eachline

### LINKED ISSUE #20351: inferred type for eachline() is lost in v0.6
```
julia> Base.Test.@inferred eachline(STDIN)
ERROR: return type EachLine does not match inferred return type Any
Stacktrace:
 [1] error(::String) at ./error.jl:21

julia> versioninfo()
Julia Version 0.6.0-dev.2481
Commit 2d86c42* (2017-01-30 22:50 UTC)
```

works fine in v0.5

```
julia> Base.Test.@inferred eachline(STDIN)
EachLine(Base.TTY(open, 0 bytes waiting),Base.#281)

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753* (2016-09-19 18:14 UTC)
```

and then when used in a loop the eltype() is not known either:

```
julia> f() = for k in eachline(STDIN); @show k; end
f (generic function with 2 methods)

julia> @code_warntype f()
Variables:
  #self#::#f
  k::Any
  value::Any
  #temp#::Any

Body:
  begin 
      SSAValue(0) = (Main.eachline)(Main.STDIN)::Any
      #temp#::Any = (Base.start)(SSAValue(0))::Any
      3: 
      unless !((Base.done)(SSAValue(0),#temp#::Any)::Any)::Any goto 26
      SSAValue(1) = (Base.next)(SSAValue(0),#temp#::Any)::Any
      k::Any = (Core.getfield)(SSAValue(1),1)::Any
      #temp#::Any = (Core.getfield)(SSAValue(1),2)::Any # line 1:
      SSAValue(2) = "k = "
      # meta: location show.jl # line 251:
```

### PR DESCRIPTION
**Pull request by p-zubieta**
Fix #20351

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by stevengj** [comment]
Why is the typeassert needed?  Is this an inference bug, or could the `EachLine` constructor be written differently to be type-stable?

**Comment by pabloferz** [comment]
`eachline` is calling invoke right now because of the resent deprecations. And I think inference has problems with `invoke` and methods with keyword arguments. This is a temporal measure (probably I should add a comment).

**Comment by pabloferz** [comment]
@stevengj It seems that the problem is simply with type constructors with keyword arguments

```julia
type Foo
    i::Int
    b::Bool
    Foo(i::Int=1, b::Bool=true) = new(i, b)
end

type Bar
    i::Int
    b::Bool
    Bar(i::Int=1; b::Bool=true) = new(i, b)
end

@code_warntype Foo(1)
# ...
end::Foo

@code_warntype Bar(1)
# ...
end::Any
```

This PRs works around that in case there is no easy/soon-to-be fix.

**Comment by pabloferz** [comment]
Another way to fix this is to change the `EachLine` constructor to use positional arguments, but leaving `eachline` with keyword arguments. That would need to remove the almost just added deprecation for `EachLine(stream, ondone)`.

**Comment by martinholters** [comment]
Well, that the return type of the constructors with keyword arguments cannot be inferred is rather unfortunate (do we an issue for that?), but with that explanation, just type-asserting their usages seems to be a valid work-around.

**Comment by StefanKarpinski** [comment]
We export `EachLine` as a public API. As such, I think that using positional arguments for this sort of thing is really not ideal: it doesn't match `eachline`, which people will expect, and who can remember which of the arguments goes first – `chomp` or the `ondone` callback? Which do we think it's more common to pass? I'd be more ok with unexporting `EachLine` since I'm not entirely sure why we export it in the first place – in that case we can make the API anything we want without worrying about ergonomics.

**Comment by StefanKarpinski** [comment]
Unfortunate as it may be that we can't type infer constructors with keyword arguments at the moment, that will be fixed and those type assertions can be deleted without affecting anyone's code. Committing to a public API based on a temporary performance issue is not a good move.

**Comment by nalimilan** [comment]
`RegexMatchIterator` (returned by `eachmatch`) isn't exported either, so +1 for unexporting `EachLine`. A similar situation happens with `zip` and `Zip`/`Zip2`.

**Comment by StefanKarpinski** [comment]
In any case, let's leave this PR as the simplest fix that addresses the type issue: sticking some type annotations on calls to the `EachLine` constructor.

**Comment by pabloferz** [comment]
I left just the type-assertion work-around, so the changes on the type constructor and unexporting can be done separately.

**Comment by martinholters** [comment]
A bit late now, but I guess we could just have made the constructor an outer constructor, replacing the `new` with a call to the default inner constructor.

**Pull request merged**
