### PR TITLE
Revert manual conversion

### PR DESCRIPTION
**Pull request by MikeInnes**
The last thing I want to do is to anger those who have spent time writing the documentation, and it's clear that these changes have done that, so it seems right to give them the opportunity to undo them.

I can fix things one way or another at this stage (and I certainly don't want to lose anyone's hard work), but if I start from scratch and do everything in one go it may leave things in a less distressing state in the meantime.

### CODE REVIEW

**Comment by jiahao** [comment]
I do appreciate all the work that you and others have put in toward the doc transition. However, I really do wish that more attention was paid to all the formatting and semantic information that was lost or broken in the #11906

**Comment by ViralBShah** [comment]
Thanks Mike for patiently working through this. This is a tough task and yes more attention could be given before merging, but reverting is certainly the right thing to do till all the things are figured out.

**Comment by tkelman** [comment]
Agreed. It's great that the doc string syntax was worked out recently, and the tools are *almost* good enough to make a seamless transition of the doc system, but given the other items on the 0.4 menu I have to say I was really surprised to see so much attention placed here.

**Comment by one-more-minute** [comment]
Ok, I'll go ahead and merge this.

When I have another go at this I'll make sure it's a completely lossless transition so that it's clear no corners are being cut. Some of the patches (Stefan's work on pulling out the help system, at least) should be fairly easy to reuse.

**Pull request merged**
