### PR TITLE
enable unconditional PKG3 precompile

### PR DESCRIPTION
**Pull request by KristofferC**
Reopens https://github.com/JuliaLang/julia/pull/26431.

This needs to happen at some point so let's look at it again.

### CODE REVIEW

**Comment by KristofferC** [comment]
5 greens, wat...

**Comment by KristofferC** [comment]
@staticfloat is it possible to run the buildbots on this commit to try it out?

**Comment by vchuravy** [comment]
Elliot is currently busy with his thesis. I will start a series of builds and let you know what the buildbots think about this.

**Comment by vchuravy** [comment]
Got an OOM on Win32 (https://build.julialang.org/#/builders/44/builds/1268)

**Comment by KristofferC** [comment]
Ok, so the only problem is the Win32 debug build. Seems a lot better than it was a while ago when half of CI crashed.

**Comment by KristofferC** [comment]
Could we just disable it for debug builds?

**Comment by KristofferC** [comment]
Testing on top of https://github.com/JuliaLang/julia/pull/27156.

**Comment by KristofferC** [comment]
Precompile statements should be a bit fewer now, rerunning CI and the buildbots.

**Comment by KristofferC** [comment]
Can't get e.g. Win32 to build, it just errors after building OpenBLAS with:

```
make[1]: Leaving directory '/home/Administrator/buildbot/worker/package_win32/build/deps'
make: *** [Makefile:60: julia-deps] Error 2
program finished with exit code 2
elapsedTime=1937.144804
```

**Comment by KristofferC** [comment]
The situation with Pkg3 without precompile statements are now (perhaps the new optimizer) fairly terrible. Just doing status takes up to 6-7 seconds and adding packages is almost back to Pkg2 coffee break times. I have yet managed to get a buildbot run through because it fails on random stuff that doesn't happen with the buildbots when running from master. So the only way to test this seems to be live. I have reduced the number of precompile statements here significantly going from this makes Pkg3 feel good, to this makes Pkg3 not feel like a slow moving piece of sloth.

**Pull request merged**
