### PR TITLE
Track deletion of merged constants

### PR DESCRIPTION
**Pull request by Keno**
This fixes an intermittent segfault in the Diffractor tests. I tried for a while to come up with a more minimal test case, but failed to do so, because it very closely depends on the order of events, but essentially what happens is that a GlobalVariable gets stored into mergedConstants, but then deleted in jl_merge_module when the opaque closure module is merged into its parent.

### CODE REVIEW

**Comment by Keno** [comment]
Managed to get a testcase after all.

**Review by vtjnash — COMMENTED** [review]
Why is there a jl_merge_module call? I think there is a lot more state sometimes destroyed than just this, so I would just say there should not be a merge-modules call, and fallback to the workqueue as designed.

**Comment by Keno** [comment]
Yeah, the design could probably be improved. I just wanted to fix the segfault for now.

**Comment by Keno** [comment]
Shall we merge this anyway and we can revisit the design in the future? It's be good to fix the immediate segfaults.

**Comment by oscardssmith** [comment]
Does this need to be bumped?

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/pull/50724

**Pull request closed without merging**
