### PR TITLE
[release-0.6] backports for 0.6.0-rc1

### PR DESCRIPTION
**Pull request by tkelman**
will run pkgeval here, make sure we aren't introducing any regressions relative to beta
(5d609ec44c3f3c2a3bc40d47e0979ebbf1ba5d29 is a non-backport commit, for this reason)

### CODE REVIEW

**Comment by tkelman** [comment]
The latest run is still going, but I do have pkgeval results from a couple days ago (before this PR) comparing 0.6.0-pre.beta to 609b3d12c75bdf99d98a29ab3db856a307253e74 that should be mostly representative: https://gist.github.com/anonymous/23d8d8b0cb092cfa251dea47150f4b69

- ApproxFun timed out
- ColorTypes is fixed by https://github.com/JuliaGraphics/ColorTypes.jl/pull/82 which hadn't been tagged yet when that run started
- CxxWrap needs to tag https://github.com/JuliaInterop/CxxWrap.jl/commit/5d74f49508cabdf36723aa2c18e8bd089ee6bf98 cc @barche 
- Feather timed out
- GadflyDiff timed out
- IntervalSets should be fixed by 5d609ec44c3f3c2a3bc40d47e0979ebbf1ba5d29
- JuMP timed out
- SQLite needs to adjust for the serializer change in https://github.com/JuliaLang/julia/pull/21514 cc @quinnj 
- Sugar needs to adjust for the serializer change in https://github.com/JuliaLang/julia/pull/21514 cc @SimonDanisch 
- Uniful has some `@test_broken`s that aren't broken any more cc @ajkeller34

**Comment by barche** [comment]
@tkelman PR for CxxWrap is ready: https://github.com/JuliaLang/METADATA.jl/pull/9146

**Comment by tkelman** [comment]
0.6.0-pre.beta vs 5d609ec: https://gist.github.com/cf010d498a9b12add39e7a736d34b4bf
- BayesianNonparametrics has some flaky numerical issues, doubt it's a Julia regression
- ColorTypes same issues as above
- CxxWrap same issues as above (started before latest tag)
- Feather same timeout
- GadflyDiff same timeout
- Interpolations has some flaky timing tests
- JuliaFEM has multiple megabytes of deprecation warnings and vagrant has some trouble handling its log file (not a recent Julia regression though)
- JuMP same timeout
- KrylovMethods has some flaky numerical issues
- LowRankModels not sure, should probably be looked into
- SQLite same serializer issue
- Sugar same serializer issue
- Unitful same broken-test issue

If anyone wants to help try to reproduce the timeouts or other issues, or resolve the serializer / broken-test packages, would be appreciated. Running one (fingers crossed) last time on the set of binaries currently building at
- https://s3.amazonaws.com/julianightlies/bin/linux/x64/0.6/julia-0.6.0-7e19aa3bad-linux64.tar.gz
- https://s3.amazonaws.com/julianightlies/bin/linux/x86/0.6/julia-0.6.0-7e19aa3bad-linux32.tar.gz
- https://s3.amazonaws.com/julianightlies/bin/linux/ppc64le/0.6/julia-0.6.0-7e19aa3bad-linuxppc64.tar.gz
- https://s3.amazonaws.com/julianightlies/bin/linux/arm/0.6/julia-0.6.0-7e19aa3bad-linuxarm.tar.gz
- https://s3.amazonaws.com/julianightlies/bin/osx/x64/0.6/julia-0.6.0-7e19aa3bad-osx.dmg
- https://s3.amazonaws.com/julianightlies/bin/winnt/x64/0.6/julia-0.6.0-7e19aa3bad-win64.exe
- https://s3.amazonaws.com/julianightlies/bin/winnt/x86/0.6/julia-0.6.0-7e19aa3bad-win32.exe

**Comment by tkelman** [comment]
vs 0.6.0-pre.beta @nanosoldier `runbenchmarks(ALL, vs = "@bd84fa1bad1e08b5c368999aa9b07e4382f54910")`

**Comment by tkelman** [comment]
5e709e46458f8a1cc566d75718b385a63ac9d917 changed Feather.jl from an assertion failure to a freeze, @vtjnash could you look into that?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21694#issuecomment-299337756) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4ac0a6626188e9c8f9dcd21212757312cb4c631a/5a7a596_vs_bd84fa1/report.md). cc @jrevels

**Comment by tkelman** [comment]
nothing new here, 0.6.0-pre.beta vs 7e19aa3bad2b74e0eb7d14ee48f6f9188a4fdbd6: https://gist.github.com/bcf62470ffa192a300edb4d04476db2f

**Pull request merged**
