### PR TITLE
Fix #14216: Add `lt` option to findmin and `gt` option to findmax

### LINKED ISSUE #14216: Comparison operator in findmin() variants
This issue was raised in the mailing list: https://groups.google.com/forum/#!topic/julia-users/iBydnBqQgxg

Although we can define a custom type and specialize the `<` operator for it, sometimes we may be interested in testing different operators on the spot. What are your thoughts on an additional option a la C++?

```julia
findmin(array, lt=<)
```

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
While this works, it wrecks performance. This should be done in a similar fashion to how sorting functions do this. See `base/ordering.jl` and `base/sort.jl` for examples. I also think that both functions should take an `lt` argument for consistency.

**Comment by juliohm** [comment]
Thanks @StefanKarpinski, something on these lines?

```julia
function findmin(a, order::Ordering)
    if isempty(a)
        throw(ArgumentError("collection must be non-empty"))
    end
    s = start(a)
    mi = i = 1
    m, s = next(a, s)
    while !done(a, s)
        ai, s = next(a, s)
        i += 1
        if lt(order, ai, m) || m!=m
            m = ai
            mi = i
        end
    end
    return (m, mi)
end
findmin(a;
    lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward) =
    findmin(a, ord(lt,by,rev,order))
```

How do I use the implementations in `ordering.jl` from `array.jl`? I tried adding `using Base.Order` and `include("ordering.jl")` but neither worked. Some guidance?

**Comment by ViralBShah** [comment]
Why do we have the benchmark label on this one? Does it mean it needs to be benchmarked, or it is part of a benchmark?

**Comment by tkelman** [comment]
The benchmark label was created at the suggestion of @jrevels as a to-do note that something should be added to perf tracking. So where you've been adding it to microbenchmark-related issues has been against the intent that label was created for.

**Comment by StefanKarpinski** [comment]
The problem is with the load order – `array.jl` is loaded in `sysimg.jl` before `ordering.jl` is. Arguably since `findmin` and `findmax` are ordering-related they should go in `sort.jl`. Or maybe we need to try to load `ordering.jl` much earlier...

**Comment by StefanKarpinski** [comment]
Ok, try applying this patch:

```diff
diff --git a/base/sysimg.jl b/base/sysimg.jl
index 6a525d4..fb86371 100644
--- a/base/sysimg.jl
+++ b/base/sysimg.jl
@@ -49,6 +49,10 @@ include("pointer.jl")
 include("refpointer.jl")
 include("functors.jl")

+# ordering things
+include("ordering.jl")
+importall .Order
+
 # array structures
 include("abstractarray.jl")
 include("subarray.jl")
@@ -155,8 +159,6 @@ end
 include("reducedim.jl")  # macros in this file relies on string.jl

 # basic data structures
-include("ordering.jl")
-importall .Order
 include("collections.jl")

 # Combinatorics
```

Unfortunately I can't test right now because I just got my machine repaired and I'm reinstalling basic tools like `gcc`...

**Comment by juliohm** [comment]
Thank you Stefan, I'll check it when I get back to my laptop.

-Júlio

**Comment by StefanKarpinski** [comment]
That change doesn't work but this one does:

```diff
diff --git a/base/sysimg.jl b/base/sysimg.jl
index 655d5e5..5696f40 100644
--- a/base/sysimg.jl
+++ b/base/sysimg.jl
@@ -51,6 +51,8 @@ include("functors.jl")

 # array structures
 include("abstractarray.jl")
+include("ordering.jl")
+importall .Order
 include("subarray.jl")
 include("array.jl")

@@ -155,8 +157,6 @@ end
 include("reducedim.jl")  # macros in this file relies on string.jl

 # basic data structures
-include("ordering.jl")
-importall .Order
 include("collections.jl")

 # Combinatorics
```

**Comment by juliohm** [comment]
Sorry, I don't have the time to work on this pull request, I will close it so that other people can contribute.

**Pull request closed without merging**
