### PR TITLE
REPL: make paste work in search mode

### LINKED ISSUE #29347: REPL: BoundsError in history search
To reproduce:

* `Ctrl-R` to enter reverse mode
* Paste som gibberish
* Press `Ctrl-R` again

```
': verse-i-search)` sdgfdfgdfgfdgfdgfd        ┌ Error: Error in the keymap
│   exception =
│    BoundsError: attempt to access ""
│      at index [0]
│    Stacktrace:
│     [1] prevind(::String, ::Int64, ::Int64) at ./strings/basic.jl:460
│     [2] prevind(::String, ::Int64) at ./strings/basic.jl:455
│     [3] history_search(::REPL.REPLHistoryProvider, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool, ::Bool) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:631
│     [4] history_next_result(::REPL.LineEdit.MIState, ::REPL.LineEdit.SearchState) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:1565
│     [5] (::getfield(REPL.LineEdit, Symbol("##44#75")))(::Any, ::Any, ::Any) at /Users/kristoffer/julia/usr/share/julia/stdlib/v1.1/REPL/src/LineEdit.jl:1777
...
```

The paste is not necessary, you can also type something that doesn't make any result in the reverse search come up and trigger the same behavior. Pasting is easier though.

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by KristofferC** [comment]
Note that the example in #29347 can be reproduced without using paste at all so it is not an only paste issue, or?

**Comment by rfourquet** [comment]
Actually, I couldn't reproduce the issue without using paste at all, so was not sure... (maybe it can depend on the content of the history file?) 
On the other hand, pasting triggers reliably the bug, even if I paste non-gibberish (which matches something in history). If you confirm, I will remove the "fix ..." from the title.

**Comment by KristofferC** [comment]
You need to write something that gives zero results in the reverse search. `Å` did it for me

```
(reverse-i-search)`Å': ┌ Error: Error in the keymap
│   exception =
│    BoundsError: attempt to access ""
│      at index [0]
│    Stacktrace:
```

So, Ctrl-R, Å, Ctrl-R was my input there

**Comment by rfourquet** [comment]
Ok I can reproduce, so there seems to be two bugs here!

**Comment by rfourquet** [comment]
I indentified the problem, I will make a fix for the second bug.

**Comment by rfourquet** [comment]
For reference, the bug was introduced in #25646 which introduced the `keep` keyword to `readuntil`.

**Pull request merged**
