### PR TITLE
add `@locals` macro for obtaining dictionary of local vars and values

### PR DESCRIPTION
**Pull request by JeffBezanson**
implements #29366

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Wouldn't it make more sense for this to return a named tuple?

**Comment by JeffBezanson** [comment]
I see this as just a reflection and debugging kind of thing, so a somewhat loosely-typed dictionary seems appropriate. The order of the variables is also going to be all over the place, so not having a well-defined order is a feature.

**Comment by yuyichao** [comment]
> Could this be useful in code generation as well?

No.

**Comment by dalum** [comment]
I just checked out the branch and it actually does have the effect that I want, so maybe I didn't describe it properly. :smile:

```julia
julia> function f(expr, x, y)
           __locals__ = Base.@locals()
           ex = Expr(:let, Expr(:block), Expr(:block,
               :(__locals__ = $__locals__),
               (:($key = __locals__[$(QuoteNode(key))]) for (key) in keys(__locals__))...,
               expr,
               (:(__locals__[$(QuoteNode(key))] = $key) for (key) in keys(__locals__))...))
           eval(ex)
           return __locals__[:x], __locals__[:y]
       end
f (generic function with 1 method)

julia> expr = :(x += 1; y += 1);

julia> f(expr, 1, 6)
(2, 7)
```
If it was possible to write back to the `@locals` dict to modify the local scope, that would be really cool, though ...

**Comment by StefanKarpinski** [comment]
> If it was possible to write back to the `@locals` dict to modify the local scope

This may sound good but it ruins all ability to optimize anything.

**Pull request merged**
