### PR TITLE
Fix inlining pass corner case on release-0.3

### LINKED ISSUE #9630: Undefined variable in inlining pass under Julia 0.3.4
Not sure if anyone's going to want to debug this, but when running the tests for [the Lasso package I'm working on](https://github.com/simonster/Lasso.jl/tree/5bd8bb5e91b3fb7ef86a4ec3c10c99a499d6a670) on Julia 0.3.4, I get the following error:

```
ERROR: #s3694 not defined
 in inlining_pass at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 4 times)
 in typeinf at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib
 in typeinf_ext at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at /Users/simon/.julia/v0.3/Lasso/test/runtests.jl:22
 in facts at /Users/simon/.julia/v0.3/FactCheck/src/FactCheck.jl:286
 in anonymous at no file:21
 in include at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.4.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/simon/.julia/v0.3/Lasso/test/runtests.jl, in expression starting on line 20
```

The tests stochastically pass on master, with failures due to #9232.

### LINKED ISSUE #9835: Type inference bug on 0.3.5 and release-0.3
Fine on 0.4.
```
type LLA
           lat::Float64
           lon::Float64
           alt::Float64
end

type ENU
           east::Float64
           north::Float64
           up::Float64
end

for pt in [ENU(-1.1, 2.2, -3.3)]
           typ = isa(pt, LLA) ? LLA : ENU
           r = typ(2.2, 3.3, 4.4)
end
```
```
ERROR: typ not defined
 in inlining_pass at ./inference.jl:2628
 in inlining_pass at ./inference.jl:2590
 in inlining_pass at ./inference.jl:2553
 in typeinf at ./inference.jl:1544
 in typeinf_ext at ./inference.jl:1216
```

### PR DESCRIPTION
**Pull request by ihnorton**
This fixes the test cases in #9835 

closes #9630 
closes #9835

### CODE REVIEW

**Comment by simonster** [comment]
Fixes #9630 as well.

**Comment by JeffBezanson** [comment]
Thanks. Do we have a test case added for this?

**Comment by tkelman** [comment]
No need for backport pending label, this PR was against release-0.3. A test would be good though.

**Comment by JeffBezanson** [comment]
Ah, I see, this bug doesn't exist on master. That's good.

**Comment by ihnorton** [comment]
tests added:
1857ad5f6448f195da3f0d4ac971fdf152ab9beb
d900738d9220a2a4b1197d057c351a50794ac338

**Pull request merged**
