### PR TITLE
Try to fix CI

### PR DESCRIPTION
**Pull request by LilithHafner**
- Catch busybox bad gateway error
- Don't use workers on freebsd

### CODE REVIEW

**Comment by DilumAluthge** [comment]
We've migrated Windows to Buildkite, and we'll hopefully migrate FreeBSD to Buildkite soon. So instead of implementing fixes in this repo, I'd recommend implementing them in the https://github.com/JuliaCI/julia-buildkite repo.

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
We've migrated Windows to Buildkite, and we'll hopefully migrate FreeBSD to Buildkite soon. So instead of implementing fixes in this repo, I'd recommend implementing them in the https://github.com/JuliaCI/julia-buildkite repo.

**Comment by DilumAluthge** [comment]
For https://github.com/JuliaLang/julia/pull/47014/commits/d1ab12248596ffedb6ce26345fdaa1d60e755342, I think we should either install Busybox in the Windows VM, or, preferably, we would create new `tester_windows` Docker images (which should be intentionally separate from the existing [`package_windows`](https://github.com/JuliaCI/rootfs-images/tree/main/windows) Docker images) and install Busybox inside the Docker image. Then, we don't actually need to download Busybox during the test suite.

**Comment by DilumAluthge** [comment]
For https://github.com/JuliaLang/julia/pull/47014/commits/18ce7b2e61ecb3623dcecc34899db36a90b4e639, I don't think we should skip that test. I think that segfault represents a real bug that we need to diagnose and solve.

**Comment by DilumAluthge** [comment]
Hmmm, regarding Busybox, I guess installing Busybox in the CI environment doesn't address people running the tests locally.

However, we shouldn't skip the test if cache.julialang.org is down - instead, we should just download directly from the upstream source.

**Comment by DilumAluthge** [comment]
> However, we shouldn't skip the test if cache.julialang.org is down - instead, we should just download directly from the upstream source.

#47015

**Comment by LilithHafner** [comment]
> For [18ce7b2](https://github.com/JuliaLang/julia/commit/18ce7b2e61ecb3623dcecc34899db36a90b4e639), I don't think we should skip that test. I think that segfault represents a real bug that we need to diagnose and solve.

I agree that it is a real bug, but I think that we should track it in the issue tracker (https://github.com/JuliaLang/julia/issues/47016), not as a failing CI test.

**Pull request closed without merging**
