### PR TITLE
RFC: degree trig functions on square matrices

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
We could also make `deg2rad` and `rad2deg` work on any argument that supports multiplication with a scalar.

**Comment by StefanKarpinski** [comment]
That's also a sensible idea. I'm putting this out there as an RFC: it seems to make sense to me that this function is well-defined for square matrices since it can be defined in terms of a Taylor series. If people think that makes sense I'll add tests for this behavior as well.

**Comment by ronisbr** [comment]
Is there any geometrical meaning of computing a sine of a matrix in "degrees"?

**Comment by ronisbr** [comment]
@StefanKarpinski I think I can help here, but I need to understand what is to compute a degree trig function in a matrix. I am not seeing a geometrical meaning. Any idea? Just a scaling in the series expansion?

**Comment by StefanKarpinski** [comment]
Honestly I don’t really know. I would presume the same meaning as the natural versions but with degrees in place or radians.

**Comment by ViralBShah** [comment]
Thoughts on what is next here? Is it still unclear?

**Comment by StefanKarpinski** [comment]
I'm closing this because it's annoying to have this PR hanging around open.

**Pull request closed without merging**
