### PR TITLE
more consistently show lists with spaces

### PR DESCRIPTION
**Pull request by vtjnash**
#yolo

### CODE REVIEW

**Comment by JeffBezanson** [comment]
No strong opinion on this but I notice it still doesn't use spaces in type parameters:

```
julia> typeof(1=>2)
Pair{Int64,Int64}

julia> f{T,N}(x::Array{T,N})=0;

julia> methods(f)
# 1 method for generic function "f":
f{T, N}(x::Array{T,N}) in Main at REPL[10]:1
```

Except of course the method one will have to change anyway.

**Comment by KristofferC** [comment]
RIP doctests

**Comment by KristofferC** [comment]
But seriously, it's pretty much impossible to work with doctests now. That this wasn't taken into considering before merging is a bit disappointing.

**Comment by StefanKarpinski** [comment]
I suspect it didn't occur to @vtjnash that this would trash the doctests. It seems like the way to work with doctests should be to generate the new output so that you can do a `git add -p` and step through them interactively accept/reject changes.

**Comment by Keno** [comment]
Why aren't we running the doctests on CI?

**Comment by ararslan** [comment]
I think it has to do with how Documenter works. IIRC it's only set up to build the docs when merging to master, but I could be wrong on that. cc @MichaelHatherly

**Comment by StefanKarpinski** [comment]
Because @KristofferC, @kshyatt and @fredrikekre have been [busting their butts](https://github.com/JuliaLang/julia/pulls?utf8=%E2%9C%93&q=is%3Apr%20doctest%20) to get the doctests to actually pass! Which this completely screws up. It breaks the doctests again and causes all their PRs to conflict.

**Comment by tkelman** [comment]
We've never had doctests running on CI because they never stayed passing on master long enough for someone to follow that through all the way, but we were getting really close this time. Ref https://github.com/JuliaLang/julia/issues/19528

**Comment by vtjnash** [comment]
So ... I'll make a PR adding a mode to Documenter that can auto-update the doctest output. That seems like a positive outcome? (and the work to get doctests written will be able to keep going?)

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaLang/julia/issues/20274 for the umbrella doctest tracking issue.

**Pull request merged**
