### PR TITLE
Fix hyperlinks

### PR DESCRIPTION
**Pull request by bluesmoon**

### CODE REVIEW

**Comment by simeonschaub** [comment]
You will need to add the links below as well. Because 1.8 has already branched, this also needs a PR against the `backports-release-1.8` branch updating the NEWS.md file.

**Comment by ViralBShah** [comment]
Can it be backported?

**Comment by simeonschaub** [comment]
No, I don't think it can be automatically because it's a different file

**Comment by bluesmoon** [comment]
I've updated the links. Will make a separate PR against the 1.8 branch.

**Comment by bluesmoon** [comment]
Added https://github.com/JuliaLang/julia/pull/44374

**Pull request merged**
