### PR TITLE
Get rid of cmp/isless for AdjTrans

### PR DESCRIPTION
**Pull request by kshyatt**
Without the imports, the tests fail due to method problems

### CODE REVIEW

**Comment by mbauman** [comment]
Oh nice find.

Do we want to just delete these definitions instead?

* They're not exported and have never worked as you'd expect; nobody has complained
* We only define `cmp` and `isless` for 1-dimensional vectors, but row vectors (mostly) behave like 2-dimensional arrays
* We don't define `<` for adjoints and transposes (nor 2-dimensional arrays in general)

**Comment by andyferris** [comment]
Yeah I also think maybe we should limit ourselves to `AbstractArray{<:Any, 1}` for now, which these types are not.

When we have a generic definition for matrices we should revisit.

**Comment by kshyatt** [comment]
OK, the plan is delete these (and the tests too)?

**Comment by mbauman** [comment]
Yes, I think that'd make the most sense.

**Comment by dkarrasch** [comment]
Maybe adjust the title, for later reference?

**Comment by kshyatt** [comment]
Is this good to go?

**Pull request merged**
