### PR TITLE
[release-1.9] Backport #47797 to 1.9 (Parallel LLVM Image Generation)

### PR DESCRIPTION
**Pull request by pchintalapudi**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
It seems like this is a new feature, and thus shouldn't be backported?

**Comment by vchuravy** [comment]
Feature is explicitly about language level/stdlib/Base change. This is an implementation detail. I agree that this is a higher risk change and we might want to wait for it to sit on master for little while longer and only include it in 1.9.1.

I will leave it up to @KristofferC for when to include it.

**Comment by vchuravy** [comment]
@pchintalapudi can you ensure that the backreference to the individual commits are in the commit message? E.g. the result should be `git cherry-pick -x` and then `git rebase -i` and squashing them all into one.

**Comment by vtjnash** [comment]
I don't think we have a reason to backport this.

**Pull request closed without merging**
