### PR TITLE
Add Windows patches for LLVM 3.9

### PR DESCRIPTION
**Pull request by tkelman**
part of https://github.com/JuliaLang/julia/issues/19123

threads patch was rebased on rust's llvm fork
https://github.com/rust-lang/llvm/commit/d1cc48989b13780f21c408fef17dceb104a09c9d

cygwin build patch is from https://github.com/llvm-mirror/llvm/commit/9f7957830512dbcddd9cb5542080eb2d1cdd705b
in cross-compile, a subset of llvm gets built for the native build system

This crashes at the start of bootstrap on both win64:

```
    JULIA usr/lib/julia/inference.ji

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\cygwin64\home\Tony\julia\usr\bin\julia.exe
File: /home/Tony/julia/src/codegen.cpp, Line 1149

Expression: fptr.fptr != NULL
make[1]: *** [Makefile:217: /home/Tony/julia/usr/lib/julia/inference.ji] Error 3
make: *** [Makefile:96: julia-inference] Error 2
```

and win32:

```
    JULIA usr/lib/julia/inference.ji
LLVM ERROR: Program used external function '_memset' which could not be resolved!
make[1]: *** [Makefile:217: /home/Tony/julia32/usr/lib/julia/inference.ji] Error 1
make: *** [Makefile:96: julia-inference] Error 2
```

### CODE REVIEW

**Comment by tkelman** [comment]
@vtjnash I'll need you to check that I rebased 7ee818ce0a12ebd14b6ae219c865dd5dc1fc141f right. We also need to write an LLVM unit test for that so we can get it upstreamed.

**Comment by tkelman** [comment]
Note to self: should look into whether we need https://github.com/cygwinports/llvm/blob/598b7d8c704f2c8e59daddde1900318aef9eed72/0003-Fix-RuntimeDyldCOFFI386-to-handle-relocations-with-a.patch

**Comment by vtjnash** [comment]
We don't need it, as we don't use that code path. Could be interesting to look into though at some point, now that we know that code path might work.

**Comment by vchuravy** [comment]
I tried to look into this:
* Rebased this branch and added patch to copy missing `winpthread-1`
* Building on Windows 10 Cygwin + Mingw64 5.4.0

Debug on Win64
```
    LINK usr/bin/julia-debug.exe
    JULIA usr/lib/julia/inference.ji
LLVM ERROR: Program used external function '__security_check_cookie' which could not be resolved!
make[1]: *** [Makefile:217: /home/valentin-churavy/julia/usr/lib/julia/inference.ji] Error 1
make: *** [Makefile:96: julia-inference] Error 
```
The lowering for that is In lib/Target/X86/X86ISelLowering.cpp around line 1994, which is guarded by a check to `Subtarget.getTargetTriple().isOSMSVCRT()`. Added in D20346. 
We either have to load the MSVC `bufferoverflowu.lib` or change the SubTarget to not be MSVC.

Win64:
```
$ make
    JULIA usr/lib/julia/inference.ji
/bin/sh: line 1:  6560 Segmentation fault      /home/valentin-churavy/julia/usr/bin/julia.exe -C native --output-ji `cygpath -w /home/valentin-churavy/julia/usr/lib/julia/inference.ji` --startup-file=no -g0 -O0 coreimg.jl
make[1]: *** [Makefile:217: /home/valentin-churavy/julia/usr/lib/julia/inference.ji] Error 139
make: *** [Makefile:96: julia-inference] Error 2
```

**Comment by tkelman** [comment]
GCC 5.4 will most likely still miscompile LLVM (even 3.7) on win32. The GCC 4.9 build from cygwin did not need libwinpthread, but it's not currently easy to get. Probably need to use the cygwin time machine to get the past versions.

**Comment by vchuravy** [comment]
Thanks for the hint with cygwin time machine (`2016/09/09-131242` still has 4.9.2)

**Comment by vchuravy** [comment]
Same problem with 4.9.2
```
(gdb) call jl_(meth)
Core.Typeof(#Typeof, #<null>.Any)
(gdb) p meth.fptr
$1 = (jl_fptr_t) 0x0
```

**Comment by vchuravy** [comment]
@tkelman The `llvm-3.9.0_threads` patch seems to be excessively large in comparison to the patch for 3.8.

**Comment by tkelman** [comment]
I took it straight from Rust's fork, didn't think too much about it.

**Comment by vchuravy** [comment]
Restarted appveyor for this. Log is backed up here https://gist.github.com/vchuravy/4b995598e033574c45b7b9f83c4333b1

**Review by vchuravy — APPROVED** [review]
From my perspective this is ready to be merged

**Comment by tkelman** [comment]
I still haven't looked much at the threads patch, but I think the old copy was doing `#if 0` around big chunks of code. Maybe that's not as possible to do cleanly in 3.9 for some reason?

**Comment by vchuravy** [comment]
It seems to remove `lli-child-target`, `llvm-cov`, and `sancov` completely. Maybe these are parts of llvm that rely on the functionality that is disabled? It looks like the patch is turning of `RPCUtils.

**Pull request merged**
