### PR TITLE
fix another incorrect quiescent finalizer detection

### LINKED ISSUE #47185: Segfault during GC marking if jl_adopt_thread is called
I might completely misunderstand how `jl_adopt_thread` should be used, or that it should only be used through `cfunction` or `@ccallable`, but if I initialize Julia and call `jl_adopt_thread from another thread a segfault occurs in line 811 of gc.c:

> tag = jl_atomic_exchange_relaxed((_Atomic(uintptr_t)*)&o->header, tag);

Version info:

```
julia> versioninfo()
Julia Version 1.9.0-DEV.1599
Commit e569459da6 (2022-10-16 11:17 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 1 on 12 virtual cores
```

I compiled  Julia with `make` / `make debug`.

This is my C code:

```C
#include <julia.h>
#include <pthread.h>

JULIA_DEFINE_FAST_TLS

void *thread(void *ptr)
{
    int i = 1000;
    jl_adopt_thread();
    jl_eval_string("println(\"Foreign thread\")");

    while (--i) {
        jl_eval_string("sleep(0.01)");
    }

    return NULL;
}

int main(int argc, char *argv[])
{
    jl_init();

    pthread_t thr;
    pthread_create(&thr, NULL, *thread, NULL);

    jl_eval_string("sleep(1)");
    jl_eval_string("println(\"Collect\")");
    jl_gc_collect(JL_GC_FULL);
    jl_eval_string("println(\"Done\")");

    pthread_join(thr, NULL);

    jl_atexit_hook(0);
    return 0;
}
```

Compiled with: `gcc -o test -fPIC -I$JULIA_DIR/include/julia -L$JULIA_DIR/lib -Wl,-rpath,$JULIA_DIR/lib test.c -ljulia-debug -g`

### PR DESCRIPTION
**Pull request by vtjnash**
Missed in #47214
Fixes https://github.com/JuliaLang/julia/issues/47185
Closes https://github.com/JuliaLang/julia/pull/47177

### CODE REVIEW

**Comment by giordano** [comment]
aarch64 darwin segfaulted during build: https://buildkite.com/julialang/julia-master/builds/17183#0183f2ed-2670-4078-a331-ef2875924055

**Comment by vtjnash** [comment]
That is someone else's fault (does seem to be recent though). e.g. https://buildkite.com/julialang/julia-master/builds/17191#0183f3d6-0a57-471e-a6f7-53674e8708d1

**Comment by vtjnash** [comment]
Seems to be first seen in https://buildkite.com/julialang/julia-master/builds/17186 though, which makes no sense

However, note that worker is also failing at doing a whole lot of other things too, since it is out of disk space and often  aborting other random processes

**Comment by George9000** [comment]
1.9.0 at `ecf9e56037` builds on aarch64-darwin without errors and is successful, both specifically for `gmake test-ccall`, and generally for `gmake testall`  Many thanks, @vtjnash!

<details>
<summary>Build and test summary</summary>

```
julia> versioninfo()
Julia Version 1.9.0-DEV.1623
Commit ecf9e56037 (2022-10-20 19:04 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_DEPOT_PATH = /Volumes/ssd500/juliabuildtemp


----------------

Sysimage built. Summary:
Base ────────  14.566728 seconds 40.5889%
Stdlibs ─────  21.321013 seconds 59.4091%
Total ───────  35.888477 seconds
    JULIA usr/lib/julia/sys-o.a
Generating REPL precompile statements... 40/40
Executing precompile statements... 1828/1871
Precompilation complete. Summary:
Generation ──  53.105973 seconds 76.0573%
Execution ───  16.717651 seconds 23.9427%
Total ───────  69.823624 seconds
Outputting sysimage file...
Output ──────  69.022922 seconds
    LINK usr/lib/julia/sys.dylib
    CC usr/lib/libccalltest.dylib
    CC usr/lib/libllvmcalltest.dylib
    
----------------    

% gmake test-ccall                                                                                                   21:07
Whitespace check found no issues.
    HINT The system image was recently rebuilt. Are you aware of the test-revise-* targets? See CONTRIBUTING.md.
    JULIA test/ccall
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 8
  Sys.total_memory() = 64.000 GiB
  Sys.free_memory() = 32.400 GiB

Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
ccall      (1) |        started at 2022-10-20T21:07:45.324
ccall      (1) |     9.84 |   0.08 |  0.8 |     493.04 |   365.06

Test Summary: |   Pass  Broken   Total   Time
  Overall     | 165130       1  165131  10.5s
    SUCCESS

----------------

% gmake testall
...
Test Summary:                     | Pass  Total  Time
Threads.Conditions must be locked |    5      5  0.0s
Test Summary:       | Pass  Total  Time
IntrusiveLinkedList |   72     72  0.1s
Test Summary:        | Pass  Total  Time
@spawn interpolation |   10     10  0.3s
Test Summary:        | Pass  Total  Time
@async interpolation |    8      8  0.0s
Test Summary:                   | Pass  Total  Time
spawn interpolation: macrocalls |    2      2  1.6s
Test Summary: | Pass  Total  Time
Co-schedule   |    1      1  0.0s
Test Summary:                 | Pass  Total  Time
Threads.foreach(f, ::Channel) |    7      7  1.2s
Test Summary:     | Pass  Total  Time
Task-local random |    4      4  0.1s
Test Summary: | Pass  Total  Time
Racy `@spawn` |    1      1  0.1s
Test Summary:   | Pass  Total  Time
package loading |    1      1  0.2s
Test Summary:                     | Pass  Total  Time
Threads.Conditions must be locked |    5      5  0.0s
Test Summary:       | Pass  Total  Time
IntrusiveLinkedList |   72     72  0.1s
Test Summary:        | Pass  Total  Time
@spawn interpolation |   10     10  0.3s
Test Summary:        | Pass  Total  Time
@async interpolation |    8      8  0.0s
Test Summary:                   | Pass  Total  Time
spawn interpolation: macrocalls |    2      2  1.6s
Test Summary: | Pass  Total  Time
Co-schedule   |    1      1  0.0s
Test Summary:                 | Pass  Total  Time
Threads.foreach(f, ::Channel) |    7      7  1.1s
Test Summary:     | Pass  Total  Time
Task-local random |    4      4  0.0s
Test Summary: | Pass  Total  Time
Racy `@spawn` |    1      1  0.1s
Test Summary:   | Pass  Total  Time
package loading |    1      1  0.1s
Test Summary:                     | Pass  Total  Time
Threads.Conditions must be locked |    5      5  0.0s
Test Summary:       | Pass  Total  Time
IntrusiveLinkedList |   72     72  0.1s
Test Summary:        | Pass  Total  Time
@spawn interpolation |   10     10  0.3s
Test Summary:        | Pass  Total  Time
@async interpolation |    8      8  0.0s
Test Summary:                   | Pass  Total  Time
spawn interpolation: macrocalls |    2      2  1.6s
Test Summary: | Pass  Total  Time
Co-schedule   |    1      1  0.0s
Test Summary:                 | Pass  Total  Time
Threads.foreach(f, ::Channel) |    7      7  1.3s
Test Summary:     | Pass  Total  Time
Task-local random |    4      4  0.0s
Test Summary: | Pass  Total  Time
Racy `@spawn` |    1      1  0.1s
Test Summary:   | Pass  Total  Time
package loading |    1      1  0.1s
Test Summary:                     | Pass  Total  Time
Threads.Conditions must be locked |    5      5  0.0s
Test Summary:       | Pass  Total  Time
IntrusiveLinkedList |   72     72  0.1s
Test Summary:        | Pass  Total  Time
@spawn interpolation |   10     10  0.3s
Test Summary:        | Pass  Total  Time
@async interpolation |    8      8  0.0s
Test Summary:                   | Pass  Total  Time
spawn interpolation: macrocalls |    2      2  1.6s
Test Summary: | Pass  Total  Time
Co-schedule   |    1      1  0.0s
Test Summary:                 | Pass  Total  Time
Threads.foreach(f, ::Channel) |    7      7  1.3s
Test Summary:     | Pass  Total  Time
Task-local random |    4      4  0.0s
Test Summary: | Pass  Total  Time
Racy `@spawn` |    1      1  0.1s
Test Summary:   | Pass  Total  Time
package loading |    1      1  0.1s
threads                                          (1) |    80.97 |   0.01 |  0.0 |      36.45 |   454.77
Distributed                                      (1) |        started at 2022-10-20T21:28:41.865
[ Info: SO_REUSEPORT is unsupported, skipping reuseport tests
      From worker 28:
      From worker 28:	[62934] signal (15): Terminated: 15
      From worker 28:	in expression starting at none:0
      From worker 28:	kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
      From worker 28:	unknown function (ip: 0x0)
      From worker 28:	Allocations: 3246292 (Pool: 3243671; Big: 2621); GC: 5
┌ Warning: rmprocs: process 1 not removed
└ @ Distributed /Volumes/ssd500/julia/usr/share/julia/stdlib/v1.9/Distributed/src/cluster.jl:1049
Distributed                                      (1) |   114.79 |   0.01 |  0.0 |      32.25 |   456.55
stress                                           (1) |        started at 2022-10-20T21:30:36.661
(libuv) kqueue(): Too many open files
stress                                           (1) |     7.05 |   0.01 |  0.1 |      44.55 |   457.41

Test Summary: |     Pass  Broken     Total      Time
  Overall     | 40647823  352702  41000525  16m41.7s
    SUCCESS
```
  
</details>

**Pull request merged**
