### PR TITLE
Added tests for the set operations

### PR DESCRIPTION
**Pull request by gman93**
Added some test cases for the set operations as an initial contributions to get to understand the workflow of the project as mentioned in #9493.

### CODE REVIEW

**Comment by ihnorton** [comment]
@gman93 please see existing tests in collections.jl and move/dedupe these into there.

**Comment by timholy** [comment]
This is really exciting! Thanks for taking the plunge.

But there are some Set tests in `collections.jl`; does this add to them? You could append any new ones to that file.

If there are redundancies here (and it looks like there probably are), it's my fault. In #9493, I only yesterday added the instruction to use `JULIA_CPU_CORES=1` when launching julia for the tests---that turns out to be important, because any process other than the main one does not get run with `code-coverage` turned on (and even if they did, they would tromp on each others' results).

**Comment by gman93** [comment]
Sorry my bad, didn't know that all the test for collections are grouped into a single file. @timholy Thanks for pointing me that Edit I haven't noticed it. In fact I was gonna ask  "why are these tested functions not compailing"  . Also I am excited to contirbute to Julia. Looking forward to add more :)

**Comment by gman93** [comment]
Also This doesn't add to the test, set is already well tested. I will look for different place to start.

**Pull request closed without merging**
