### PR TITLE
Fix USE_GPL_LIBS=1 #13060: Changed Makefile and base/docs/helpdb.jl

### PR DESCRIPTION
**Pull request by nkottary**
Makefile: Add FFTW libs to JL_PRIVATE_LIBS only when USE_GPL_LIBS is 1.
helpdb.jl: Add docstrings for FFTW API only when USE_GPL_LIBS is true.

Build with `make USE_GPL_LIBS=1` passes with these changes.

### CODE REVIEW

**Comment by tkelman** [comment]
#12766 also covered suitesparse and rmath

**Comment by jakebolewski** [comment]
Why not move these to the FFTW module (now that that works)?

**Comment by hayd** [comment]
I think this is now merged via #13117 and #13118 (committed directly to master).

*There's one remaining fft doc in [basedocs](https://github.com/JuliaLang/julia/blob/cd5922102189ffc329765dd60f038bf3109742b3/base/docs/basedocs.jl#L493).*

**Comment by ViralBShah** [comment]
Should we leave this open until the last fft in basedocs is also moved?

Cc: @nkottary

**Pull request closed without merging**
