### PR TITLE
Reorganize filesystem and I/O docs in stdlib

### PR DESCRIPTION
**Pull request by nalimilan**
Here's an attempt at making it easier to find filesystem and I/O related functions. This makes the first page (which appears as "The Standard library") shorter, which is good IMHO as it's really too large ATM. I've harmonized headline levels which were a bit messy. Also, I've regrouped filesystem and network functions which appeared related to me, but were in completely different places.

There's something I don't know how to fix: it's that the first page (file base.rst) appears as "The Standard library", when it should be called "Base functions" or "Essential functions". It's very confusing because you don't understand what's the hierarchical organization of the docs and of the stdlib: are other files parts of the stdlib or not? What should I expect to find in that first page (which is the biggest section)?

### CODE REVIEW

**Comment by ViralBShah** [comment]
I think these changes are by and large good to have. Could you merge this?

**Comment by tkelman** [comment]
This will make future doc updates harder to backport, unless of course we backport the same reorganization to release-0.3. Might be best to manually re-do this change on release-0.3 to avoid putting 0.4-specific functionality or syntax in the 0.3 docs.

**Comment by ViralBShah** [comment]
Even this particular merge is a bit difficult to sort out. I suspect it will be easier to do it manually on both master and 0.3, since there have been some changes on master since this was done, and it is hard to tell what has changed.

**Comment by nalimilan** [comment]
OK, merged a slightly revised version. I'm also pushing the equivalent reorganization re-applied manually to release-0.3. Hope I didn't break anything major...

**Comment by StefanKarpinski** [comment]
Thanks, @nalimilan – this is a very nice change.

**Comment by tkelman** [comment]
Thanks for manually redoing this on release-0.3 @nalimilan. Considering the recent flurry of doc improvements, I think we'll have to go through https://github.com/JuliaLang/julia/commits/master/doc manually and replay as much as applies to release-0.3 by hand.

**Comment by tkelman** [comment]
Looking at this again, I'm not sure combining the section for `sparse` into `arrays` was really necessary.

**Comment by nalimilan** [comment]
@tkelman It makes sense to me, especially as `BitArrays` are also covered in that section. `BitArrays` and sparse matrices could also be moved to a separate "special arrays" section. But I'm fine with any solution.

**Pull request merged**
