### PR TITLE
fix the read and write methods of DevNull

### PR DESCRIPTION
**Pull request by bicycle1885**
This patch fixes the IO-related behaviors of `DevNull`.

In the current revision, `write(DevNull, 0x00)` is not callable:

``` julia
~/v/julia (master|✚1…) $ julia-dev
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+963 (2015-10-25 05:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 5d7c0ad* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

julia> write(DevNull, 0x00)
ERROR: Base.DevNullStream does not support byte I/O
 [inlined code] from error.jl:22
 in write at io.jl:338
```

And `read(DevNull, UInt8)` throws an incorrect exception due to a typo (`EOFErorr`).
So, I fixed these problems and added tests in `test/io.jl`, which is a newly created file for these tests since I couldn't find a suitable place to put them.

### CODE REVIEW

**Comment by tkelman** [comment]
These tests won't actually run unless you add them to the list in `test/choosetests.jl`. Though I suspect there are a few existing test files that would work to add these to.

**Comment by bicycle1885** [comment]
@tkelman Thank you, I've placed tests in test/file.jl. Does this looks good?

**Comment by Keno** [comment]
Actually it seems like writing should return the total number of bytes rather than 0, because the writing does succeed to the abstraction, it just doesn't go anywhere.

**Comment by tkelman** [comment]
And why should this constrain the types of the second arguments to `read` and `write`?

At least the typo fix part of this should be backported. Maybe the rest too?

**Comment by bicycle1885** [comment]
@Keno That sounds reasonable. I'll fix that.

@tkelman This is because there is ambiguity about method types. I see this kind of warnings while precompiling:

```
...
random.jl
printf.jl
meta.jl
Enums.jl
WARNING: New definition
    write(Base.IO, Base.Enums.Enum) at Enums.jl:11
is ambiguous with:
    write(Base.DevNullStream, Any) at process.jl:95.
To fix, define
    write(Base.DevNullStream, Base.Enums.Enum)
before the new definition.
serialize.jl
channels.jl
...
```

And the defined method is not callable:

```
julia> write(DevNull, 0x00)
ERROR: Base.DevNullStream does not support byte I/O
 [inlined code] from error.jl:22
 in write at io.jl:338
```

**Pull request merged**
