### PR TITLE
Documentation - Change complete_me (inner constructor helper function) to complete_me!

### PR DESCRIPTION
**Pull request by moustachio-belvedere**
To be consistent with Julia style guidelines change _complete_me_ to _complete_me!_ as it alters at least one of its mutable arguments.

Although the “!” requirement is arguably less stringent on inner constructor completion functions, as they will never be called directly, only indirectly upon creation of a struct instance, the “!” should still be appended to the function name for code reading clarity.

As discussed here:

https://discourse.julialang.org/t/a-question-of-style-should-inner-constructor-completion-functions-end-with/8948

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by fredrikekre** [comment]
On second thought -- is this actually mutation?

**Comment by moustachio-belvedere** [comment]
On the one hand, it is not traditional mutation as it must also return the struct back rather than just mutate it in place. On the other hand, it does mutate something it is _mutating_ the struct so should be considered a mutating function.

It's my opinion that the "!" appended adds clarity but I'm a fairly inexperienced Julia developer, others might disagree.

**Comment by GregPlowman** [comment]
> On the one hand, it is not traditional mutation as it must also return the struct back rather than just mutate it in place.

Many mutating functions return the mutated object.

> On second thought -- is this actually mutation?

What makes say you that?

Presumably, `complete_me!` would look like a normal external mutating function, and could be called from anywhere, not just from the inner constructor. 

```
mutable struct Lazy
    xx
    Lazy(v) = complete_me!(new(), v)
end

function complete_me!(lazy::Lazy, v)
    lazy.xx = v
    return lazy
end
```
In isolation, the  `complete_me!` seems indistinguishable from any other type of mutating function.

**Comment by ViralBShah** [comment]
I'm closing this since there doesn't seem to be a clear answer on this. Can always reopen if necessary.

**Pull request closed without merging**
