### PR TITLE
Adds description of triple-quoting behavior to manual

### PR DESCRIPTION
**Pull request by ssfrr**

### CODE REVIEW

**Comment by ssfrr** [comment]
whooops, hold on. things look a little fishy with some of the code blocks. fixing...

**Comment by ssfrr** [comment]
OK, added the `::` that I needed to get the code blocks to show up correctly. Squashed the change and it seems good now.

**Comment by mauro3** [comment]
Nice

**Comment by tkelman** [comment]
Travis failure unrelated, #12824

**Comment by tkelman** [comment]
backported in 6662098ced2df0fef02ddc36e469767e2b0114a3

**Pull request merged**
