### PR TITLE
Fix misunwind during Profile test under rr 

### PR DESCRIPTION
**Pull request by Keno**
See the included patch for details. In short, libunwind has a bug that causes Profile test failures. Unfortunately, since I'm not seeing the issue locally, I cannot say whether this actually fixes it, so I added a second commit that just builds libunwind locally on the buildbot and hopefully if we run this a couple of times, we'll find out if it works or not. If it does, we can submit this upstream and spin a Yggdrasil release.

### CODE REVIEW

**Comment by Keno** [comment]
Actually, I was able to reproduce the original problem in a docker container, and this does seem to fix it, so I'll go ahead and go work on the Yggdrasil bump.

**Comment by Keno** [comment]
Updated the patch. Hopefully that should fix the backtrace quality regression of the previous patch while keeping the Profile fix.

**Comment by Keno** [comment]
I'm gonna go with this method of CI'ing doesn't work. Works fine locally with the patch applied as well as with a BB-built version of the binary, but not with the one from the buildbot - I assume the corruption has something to do with it. I'll just bump BB and let's try that.

**Comment by Keno** [comment]
Freebsd issue turned out to be the fallback unwinder (I guess some library on freebsd doesn't have DWARF info), which needs to be updated to this change. Aarch64 issue, I didn't debug, but I'll just drop the non-x86_64 changes here since we don't (currently) run under rr on aarch64.

**Comment by vtjnash** [comment]
This is broken on i686. Looks like the failures appeared on earlier runs of the PR, but, awkwardly, tester_linux32 never ran on the final update, so it has 17 green marks without showing the 1 red.

**Pull request merged**
