### PR TITLE
Backports for Julia 1.10.7

### LINKED ISSUE #45494: Error in SSA conversion (crashes on several Julia versions including 1.9 and master)
The following relatively simple script dumps core on Linux:

```julia
#!/usr/bin/julia

struct Aa
  train!::Function
end

function createa()
  x::Vector{T} where T<:Real = fill(NaN,0)

  train = () -> begin
    a = zeros(1, 100)

    x = ones(size(a,2)-1)
    a * vcat(x, 1)
    return x
  end

  Aa(train)
end

a = createa()
a.train!()
```

Linux: Versions 1.7.2 and 1.7.3 on x86_64 and version 1.7.0 on aarch64 exhibit the problem.

Windows 10: Version 1.6.2 on x86_64 crashes the REPL.

Linux: Version 1.4.2 on x86_64 does not have the problem.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #50832 
- [x] #51782 
- [x] #55720 
- [x] #55773 
- [x] #55886 
- [x] #55867 
- [x] #56148 
- [x] #55870 
- [x] #56252 
- [x] #56264 
- [x] #56276 
- [x] #56254 
- [x] #56280 
- [x] #56304 
- [x] #56306 
- [x] #42080 
- [x] #56441 
- [x] #56511 
- [x] #55052 
- [x] #52694 

Need manual backport:
- [ ] #55405 
- [ ] #55744 
- [ ] #55890 

Contains multiple commits, manual intervention needed:
- [ ] #54009 
- [ ] #54738 
- [ ] #55251 
- [ ] #55306 
- [ ] #55729 
- [ ] #55589 
- [ ] #55877 
- [ ] #56234 
- [x] #56311 
- [ ] #56369 

Non-merged PRs with backport label:
- [ ] #56423 
- [ ] #56411 
- [ ] #55958 
- [ ] #55956 
- [ ] #55910 
- [ ] #55813 
- [ ] #55534 
- [ ] #55499 
- [ ] #55311 
- [ ] #55220 
- [ ] #55169 
- [ ] #51479 
- [ ] #50813 
- [ ] #50157

### CODE REVIEW

**Comment by topolarity** [comment]
As a heads up, I just marked https://github.com/JuliaLang/julia/pull/54009 for backport this morning

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["JuliaInterpreter", "TelegramClient", "HubbardAtoms", "PropertyGraphs", "BM3DDenoise", "AstroRepresentations", "FindMinimaxPolynomial", "LASDatasets", "ObjectPools", "OrdinaryDiffEqRKN", "OrdinaryDiffEqSymplecticRK", "PostNewtonian", "PeriLab", "Yunir", "JumpProblemLibrary", "GalacticPotentials", "OptimizationMOI", "PeriodicMatrices", "QuantumToolbox", "SpiDy"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56381#issuecomment-2450765573) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/396b557_vs_67dffc4/report.html) is available.

**Comment by dkarrasch** [comment]
If it works out well, this should include #56415.

**Comment by KristofferC** [comment]
```

     Testing PropertyGraphs
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1822

Testing failed after 1.92s

ERROR: LoadError: Unsatisfiable requirements detected for package Test [8dfed614]:
 Test [8dfed614] log:
 ├─possible versions are: 1.10.6 or uninstalled
 └─restricted to versions 1.11.0-1 by project [bbe18be1] — no versions left
   └─project [bbe18be1] log:
     ├─possible versions are: 0.0.0 or uninstalled
     └─project [bbe18be1] is fixed to version 0.0.0
```

Not sure where

```
 └─restricted to versions 1.11.0-1 by project [bbe18be1] — no versions left
```

comes from... Where does 1.11 come from?

**Comment by dkarrasch** [comment]
@DilumAluthge Can one use the BumpStdlibs.jl workflow to bump SparseArrays.jl here to the latest commit on the `release-1.10` branch there? I saw one can choose the target branch, but from a quick glance I couldn't see if one can also choose the origin branch.

**Comment by IanButterworth** [comment]
@dkarrasch the origin branch is dictated by the stdlib version entry on the target branch i.e. for this PR branch https://github.com/JuliaLang/julia/blob/e23fb4be2d956fbe10399dbaab35beef1248cda7/stdlib/SparseArrays.version#L1 so you should just be able to invoke BumpStdlibs with `backports-release-1.10` and `SparseArrays`. I'll do that now to illustrate

**Comment by DilumAluthge** [comment]
@dkarrasch @IanButterworth Looks like that task is completed now?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/56381#issuecomment-2452567853 seems like a bugfix so I would say the PkgEval results are fine.

**Pull request merged**
