### PR TITLE
META: CUDA external language implementation

### PR DESCRIPTION
**Pull request by maleadt**
**Summary**: make inference and codegen modular and configurable for packages to reuse, eg., when generating code for a different platform. This way, we avoid bloating the compiler, and make it possible to develop and import new hardware support without requiring modifications to the compiler/base.

Concretely, this PR will track the necessary additions to Julia `master` and host the remaining diff to support the CUDA compiler over at [CUDAnative.jl](https://github.com/JuliaGPU/CUDAnative.jl).
## Inference

We need to influence inference in order to select alternative functions for some stdlib functionality (think `sin`, which now [calls out to libm](https://github.com/JuliaLang/julia/blob/2d24eda52727c6cbccec935d689d84d710366f5a/base/math.jl#L134) but needs to [call another library](https://github.com/JuliaGPU/CUDAnative.jl/blob/d5765e9ee8d3e39c106ae13798c0053d2ff1c054/src/intrinsics.jl#L361)), sometimes even depending on the GPU version.
- [x] Allow modifying the inference-limiting parameters to perform more exhaustive search: #18496
- [ ] Properly handle caching (either uncached, or using multiple method caches)
- [ ] Hooks for eg. overriding method selection: [tb/inference_hooks](https://github.com/JuliaLang/julia/tree/tb/inference_hooks)

## Codegen

Much of this is similar to inference:
- [x] Allow specifying certain parameters, eg. disabling optimization: #19046
- [x] Allow disabling language features: #19046
- [ ] Handle caches: partially implemented in #19046
- [ ] Hooks for changing code emission: [tb/codegen_hooks](https://github.com/JuliaLang/julia/tree/tb/codegen_hooks)

Longer-term:
- [ ] Make codegen sane: pure entry-points, less global state
## Support
- [x] Wrap LLVM C API: [LLVM.jl](https://github.com/maleadt/LLVM.jl)

### CODE REVIEW

**Comment by maleadt** [comment]
Small update: [LLVM.jl](https://github.com/maleadt/LLVM.jl) is now powerful enough to [fully implement the PTX JIT](https://gist.github.com/maleadt/ec07509c880903efce0d2fed6bded416) (which is pretty simple).

**Comment by datnamer** [comment]
Would be cool to keep in mind a Webassembly usecase for this:

https://github.com/WebAssembly/wasm-jit-prototype
https://github.com/WebAssembly/binaryen

**Comment by maleadt** [comment]
Yes, definitely. Implementation wise, we can look at [Rust](https://github.com/rust-lang/rust/pull/36339) for inspiration as they have a functional LLVM-based wasm target nowadays. Do you have any use-cases in mind?

**Comment by datnamer** [comment]
Well my high level usecases include distributing fully client side interactive reports and machine learning mobile apps.

**Comment by maleadt** [comment]
Rebased on top of #18496. I've been working on similar 'codegen params' in the JuliaGPU/julia repo, but that still needs to be fleshed out.

**Comment by maleadt** [comment]
I've removed commits from this PR, making it a tracking issue instead. Code has moved to [tb/cuda](https://github.com/JuliaLang/julia/commits/tb/cuda).

**Comment by maleadt** [comment]
This is outdated.

**Pull request closed without merging**
