### PR TITLE
Use `musttail` only as an optimization in the PLT.

### LINKED ISSUE #17373: poor man PLT breaks arm and power - need the rich man's version
Same as #17312.
Using master branch of julia, after `make cleanall`. My last successful build was at 45400d0.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #17373
Replaces https://github.com/JuliaLang/julia/pull/17378

### CODE REVIEW

**Comment by vtjnash** [comment]
Lgtm

**Comment by StefanKarpinski** [comment]
Love the comments. Nice work!

**Comment by ViralBShah** [comment]
Worth noting that this requires multi-threading to be enabled.

**Comment by yuyichao** [comment]
No it shouldn't. Any failure on power without llvm 3.8.1 is likely because of llvm bug.

**Pull request merged**
