### PR TITLE
avoid calling `uncompressed_ir` when checking `has_fcall`

### PR DESCRIPTION
**Pull request by aviatesk**
We don't need to allocate new `CodeInfo` just to check `has_fcall` since the equivalent information can be encoded in `Method` object.

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48258) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/461e12c_vs_b07484c/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48258#issuecomment-1380942711) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/588baca_vs_b07484c/report.md).

**Comment by Keno** [comment]
Why not use the same strategy as `jl_ir_inlining_cost` and just read the flag out of the compressed CodeInfo?

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Review by Keno — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48258#issuecomment-1381240323) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/d9fbe65_vs_d61cfd2/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48258#issuecomment-1381302909) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/b1acc24_vs_206fd5a/report.md).

**Pull request merged**
