### PR TITLE
repl: beep and ignore unrecognized inputs rather then crashing

### LINKED ISSUE #9696: Shift-enter kills REPL on Linux
With:

```julia
julia> ERROR: Unrecognized input
 in error at error.jl:21
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1556
 in run_interface at ./LineEdit.jl:1529
 in run_frontend at ./REPL.jl:838
 in run_repl at ./REPL.jl:170
 in _start at ./client.jl:438
```

### PR DESCRIPTION
**Pull request by srp**
Fixes #9696

### CODE REVIEW

**Comment by ivarne** [comment]
Pretty useless to `beep` when beep is disabled.

**Comment by ivarne** [comment]
But that seems to be fixed in https://github.com/JuliaLang/julia/pull/9710

**Comment by Keno** [comment]
This isn't the right place to put this, because it's generic code. It should probably go in one of the keymaps instead.

**Comment by JeffBezanson** [comment]
Shouldn't the fallback behavior for unhandled keys apply to all keymaps?

**Comment by Keno** [comment]
This code isn't julia REPL specific. I would rather disallow creating keymaps that don't specify a default.

**Comment by stevengj** [comment]
@Keno, since this is the default that nearly all imaginable keymaps would want for undefined inputs, wouldn't it make more sense to put it here rather than force this code to be repeated in every keymap?  If the keymap really wants to throw an exception, they can always specify a different default, no?

**Comment by srp** [comment]
I didn't understand what @Keno was saying at first, but I've been learning a lot more about keymaps. Now that I have a much better understanding about what's going on, I don't think we should be seeing this failure, I believe there may be a but where the `default` key in the keymap of the highest precedence isn't propagated to the lower precedent keymaps. I arrived at that this morning, but haven't had time to try to prove it and identify the bug.

If that's the case, I'd also agree with @Keno that this check should be replaced with an error at keymap creation time for any keymaps missing defaults.

**Comment by Keno** [comment]
I can take another look at the code. I suspect this place to add the default may be wrong anyway.

**Pull request closed without merging**
