### PR TITLE
[skip ci] Remove mention to Airy functions deprecations in NEWS.md

### PR DESCRIPTION
**Pull request by giordano**
They have been moved to SpecialFunctions.jl package.

### CODE REVIEW

**Comment by tkelman** [comment]
The two notes should probably be combined, since they were both moved and the API changed.

**Comment by giordano** [comment]
Shouldn't the user refer to `SpecialFunctions.jl` documentation?

**Comment by tkelman** [comment]
yes, but both aspects of the breakage and deprecation relative to 0.5 should be mentioned in NEWS here. probably together.

**Comment by giordano** [comment]
Better now?

**Review by tkelman — APPROVED** [review]
lgtm

**Review by Sacha0 — APPROVED** [review]

**Pull request merged**
