### PR TITLE
move Mmap and SharedArrays to stdlib

### PR DESCRIPTION
**Pull request by JeffBezanson**
One or both of these might go on to become an external package, but this at least does part of the work.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Thrilled to see this happening. This experience probably needs to be improved, however :)
```jl
julia> Mmap
WARNING: Base.Mmap is deprecated, run `using Mmap` instead.
  likely near no file:0

julia> using Mmap
WARNING: using Mmap.Mmap in module Main conflicts with an existing identifier.
ERROR: importing Mmap into Main conflicts with an existing identifier
```

**Comment by iblis17** [comment]
BSD CI got error after this PR merged
e.g. https://julia.iblis.cnmc.tw/#/builders/1/builds/2848
```
	From worker 12:	ERROR: LoadError: could not open file /usr/home/julia/worker/11rel-amd64/build/stdlib/SharedArrays/test/../../../../test/testenv.jl
	From worker 12:	Stacktrace:
	From worker 12:	 [1] include at ./boot.jl:285 [inlined]
	From worker 12:	 [2] include_relative(::Module, ::String) at ./loading.jl:526
	From worker 12:	 [3] include(::Module, ::String) at ./sysimg.jl:14
	From worker 12:	 [4] include(::String) at ./sysimg.jl:47
	From worker 12:	 [5] include at ./boot.jl:285 [inlined]
	From worker 12:	 [6] include_relative(::Module, ::String) at ./loading.jl:526
	From worker 12:	 [7] include(::Module, ::String) at ./sysimg.jl:14
	From worker 12:	 [8] process_options(::Base.JLOptions) at ./client.jl:325
	From worker 12:	 [9] _start() at ./client.jl:391
	From worker 12:	in expression starting at /usr/home/julia/worker/11rel-amd64/build/stdlib/SharedArrays/test/runtests.jl:2
llvmcall (8)              |    1.86  |  0.02  |  1.0 | 20.01      | 764.29  
	From worker 12:	============================[ ERROR: SharedArrays ]=============================
	From worker 12:	
llvmcall2 (8)             |    0.03  |  0.00  |  0.0 |  0.30      | 764.31  
	From worker 12:	failed process: Process(`/usr/home/julia/worker/11rel-amd64/build/usr/bin/julia -Cnative -J/usr/home/julia/worker/11rel-amd64/build/usr/lib/julia/sys.so --compile=yes --depwarn=error --code-coverage=none --color=no --compiled-modules=yes --check-bounds=yes --warn-overwrite=yes --startup-file=no /usr/home/julia/worker/11rel-amd64/build/stdlib/SharedArrays/test/runtests.jl`, ProcessExited(1)) [1]
	From worker 12:	
	From worker 12:	================================================================================

**Comment by iblis17** [comment]
🤔  why did it try to load things from `/usr/home/` ?
https://julia.iblis.cnmc.tw/#/builders/1/builds/2848/steps/6/logs/stdio
line 10 shows `HOME = /home/julia`

**Comment by iblis17** [comment]
https://julia.iblis.cnmc.tw/#/builders/1/builds/2843/steps/6/logs/stdio

In this case, home path is correct, but still has trouble with relative path.
I also can reproduce it on my local box with `gmake test-stdlib`

**Comment by iblis17** [comment]
Can reproduce on Linux as well: `make test-stdlib`

**Pull request merged**
