### PR TITLE
Add misc precompiles (for benchmarks)

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Please backport to 1.11

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
This is likely not just useful for benchmarks (here from mandelbrot, I'll look into more if well received). I realize minimizing the sysimage is important, but should be balanced by what is actually likely used for (real-word, and benchmark) code... since not just benchmarking empty startup that important...

```
@time begin # precompile(Tuple{typeof(Base.setindex!), Base.EnvDict, Bool, String})
.. those in here
end
  0.098306 seconds (22.86 k allocations: 1.106 MiB, 99.74% compilation time)
```

I skipped that first one since it showed no crecompilation time on its own, though 3 allocations. Why are some generated by --trace-compile=stderr and still that cheap to make? Should it be included?

**Comment by IanButterworth** [comment]
This PR is lacking a lot of context/motivation.

If these are needed for a benchmark it suggests the benchmark is not set up properly?
Also, adding a workload further down in this file is preferred over hardcoded precompile statements.

**Comment by PallHaraldsson** [comment]
I can look into a workload, just not sure what the minimal one is. How important is it vs precompiles I can easily generate?

>If these are needed for a benchmark it suggests the benchmark is not set up properly?

Why is that? That's how it's done at the Debian Benchmark Game, i.e. it's just a script, not compiled with juliac or similar (PackageCompiler/AOT not wanted there, or a sysimage maybe not either).

**Comment by ViralBShah** [comment]
These things should move into the relevant benchmarks repo. Perhaps the benchmark should even be updated to use `juliac` wherever it makes sense.

**Comment by PallHaraldsson** [comment]
At least some of these are more generaly useful than just for benchmarks like:

precompile(Tuple{typeof(Base.print), Base.IOStream, UInt64})
precompile(Tuple{typeof(Base.println), Base.IOStream, UInt64})

I could trim it somewhat, but yes, eventually juliac could and should be used. I wanted good speed for 1.11.0 and it's broken anyway, startup-speed regression hopefully fixed by 1.11.1 so maybe add something by then?

**Comment by KristofferC** [comment]
I don't think we should put Debian Benchmark game specific precompile signatures here.

**Pull request closed without merging**
