### PR TITLE
Use unique identifier to avoid incorrect ditype reuse

### PR DESCRIPTION
**Pull request by yuyichao**
I don't know when this starts to happen or if this is the right solution but it triggers an LLVM assertion on LLVM svn that seems to be in 3.7 too. Without this LLVM seems to return the same object for types of the same size and name but different fields.

@Keno

### CODE REVIEW

**Comment by yuyichao** [comment]
Should be fixed on llvm 3.7, 3.8 and ready for review now.

I believe this is caused by (or at least related to) https://github.com/llvm-mirror/llvm/commit/de7484036b628b08be6acbfb5feac405d7450300. Without this patch, we are occasionally emitting invalid debug type info on all LLVM versions due to the `DICompositeType` "reuse"/unique. I'm not sure why this only triggers the assertion on LLVM 3.9+ though. I'm still not 100% sure if this is the right approach but I couldn't find a better way.

Also add backport label to make sure LLVM 3.9 is supported.

**Comment by yuyichao** [comment]
Looks like travis didn't even start (not just missing the status). Try again.

**Comment by tkelman** [comment]
How did the assertion trigger? Regular bootstrap?

**Comment by yuyichao** [comment]
Yes.

**Comment by yuyichao** [comment]
And in particular due to one of the recursive type in `Pkg`.

**Comment by Keno** [comment]
LGTM.

**Pull request merged**
