### PR TITLE
Fix show() error while calling UDPSocket() in REPL.

### PR DESCRIPTION
**Pull request by abhijithanilkumar**
Calling UDPSocket() displays this now.

``` julia
julia> UDPSocket()
UDPSocket(init)
```

Fixes [#13711](https://github.com/JuliaLang/julia/issues/13711)

### CODE REVIEW

**Comment by abhijithanilkumar** [comment]
@tkelman  What tests should be implemented here?

**Comment by kshyatt** [comment]
@abhijithanilkumar tests for `show` can be seen [here](https://github.com/JuliaLang/julia/blob/master/test/iobuffer.jl#L195).

**Comment by abhijithanilkumar** [comment]
@kshyatt Is the displayed message fine? Or should it be changed to something else?

**Comment by tkelman** [comment]
This is good, though there's an underlying issue that the show method that was previously being called for the LibuvStream abstract type assumes the presence of a buffer field. That's apparently a bad assumption, question is whether there are counterexamples other than UDPSocket?

**Comment by abhijithanilkumar** [comment]
@tkelman TCPSocket and UDPSocket uses LibuvStream. TCPSocket works fine.

**Comment by kshyatt** [comment]
I think the message is fine. @tkelman I grepped for `<: LibuvStream` and every other subtype has a `buffer` member.

**Comment by tkelman** [comment]
I'm not sure whether that type is meant to be subtyped by packages. If not, maybe the existing show method should be made more specific to only apply to TCPSocket.

**Comment by kshyatt** [comment]
The existing show method also works for `TTY` AFAICT.

**Comment by tkelman** [comment]
Are there other methods on the abstract LibuvStream that make similar type member assumptions? show might not be the only thing broken.

**Comment by rohitvarkey** [comment]
@tkelman @abhijithanilkumar Seems like there are a few methods which are broken due to this assumption. Few examples. (This is on 0.4.1)

```julia
julia> nb_available(s)
ERROR: type UDPSocket has no field buffer
 in nb_available at stream.jl:254

julia> isreadable(s);
ERROR: type UDPSocket has no field buffer
 in isreadable at stream.jl:243

julia> isopen(s);
ERROR: type UDPSocket has no field buffer
 in print at strings/io.jl:8
 in print_to_string at strings/io.jl:36
 in isopen at stream.jl:317
```

**Comment by rohitvarkey** [comment]
I also found a duplicate method for `nb_available`. 
https://github.com/JuliaLang/julia/blob/0ea14f8f433e562a99a3da28487c5b887ea9f4e3/base/stream.jl#L87
https://github.com/JuliaLang/julia/blob/0ea14f8f433e562a99a3da28487c5b887ea9f4e3/base/stream.jl#L253

**Comment by abhijithanilkumar** [comment]
@tkelman What has to be done here?

**Comment by tkelman** [comment]
needs to add tests of this method

**Comment by abhijithanilkumar** [comment]
@tkelman I'm a newbie to Julia. Where should I add the tests? :sweat_smile:  @kshyatt I didn't really understand show tests you posted. I thought I was making a call to an already existing show method. Please correct me if I'm wrong.

**Comment by tkelman** [comment]
`test/socket.jl` would seem like a natural place

**Comment by abhijithanilkumar** [comment]
@tkelman Is this okay?

**Comment by tkelman** [comment]
I think that looks right. `repr` shouldn't result in any stdout output, I think.

**Comment by tkelman** [comment]
Once this is merged we should open a new issue for the other methods that don't work on UDPSocket for the same underlying reason that @rohitvarkey described above.

**Comment by abhijithanilkumar** [comment]
@tkelman So is the work here done? Anything else to be covered?

**Pull request merged**
