### PR TITLE
add paragraph about 5th kind of REPL prompt

### PR DESCRIPTION
**Pull request by StephenVavasis**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]
You can also just press backspace when the input is empty to exit it.

**Comment by musm** [comment]
@StephenVavasis  would you like to rebase to get CI to kickoff again.

**Comment by StefanKarpinski** [comment]
I tried to close this and reopen it again but it seems that I can't since the upstream repo is gone.

**Comment by musm** [comment]
No worries I copied the contents of this PR to  https://github.com/JuliaLang/julia/pull/38842

**Pull request closed without merging**
