### PR TITLE
make @fastmath mirror how lowering applies literal_pow

### LINKED ISSUE #53817: `@fastmath` and `literal_pow` not compatible
While `@fastmath` claims to mimic the compiler:

https://github.com/JuliaLang/julia/blob/91455710f38f226e45591203b0d4cd8e392131fd/base/fastmath.jl#L104-L107

in reality there are some corner cases, where that fails. The condition in the first line seems incorrect. See also #53713.
Examples:

```
julia> @fastmath 2^-2305843009213693953
0.0

julia> 2^-2305843009213693953
ERROR: DomainError with -2305843009213693953:
Cannot raise an integer x to a negative power -2305843009213693953.
```
and

```
julia> foo(a) = a^0x2 
foo (generic function with 1 method)

julia> foofast(a) = @fastmath a^0x2
foofast (generic function with 1 method) 

julia> @code_typed debuginfo=:source foo(2)
CodeInfo(
    @ REPL[58]:1 within `foo`
   ┌ @ intfuncs.jl:349 within `^`
1 ─│ %1 = Base.power_by_squaring::typeof(Base.power_by_squaring)
│  │┌ @ intfuncs.jl:313 within `power_by_squaring`
│  ││ %2 = invoke Base.:(var"#power_by_squaring#522")(Base.:*::typeof(*), %1::typeof(Base.power_by_squaring), a::Int64, 0x02::UInt8)::Int64
└──││      return %2
   └└
) => Int64

julia> @code_typed debuginfo=:source foofast(2)
CodeInfo(
    @ REPL[61]:1 within `foofast`
   ┌ @ fastmath.jl:284 within `pow_fast`
   │┌ @ intfuncs.jl:389 within `literal_pow`
   ││┌ @ intfuncs.jl:349 within `^`
1 ─│││ %1 = Base.power_by_squaring::typeof(Base.power_by_squaring)
│  │││┌ @ intfuncs.jl:313 within `power_by_squaring`
│  ││││ %2 = invoke Base.:(var"#power_by_squaring#522")(Base.:*::typeof(*), %1::typeof(Base.power_by_squaring), a::Int64, 0x02::UInt8)::Int64
└──││││      return %2
   └└└└
) => Int64
```

### PR DESCRIPTION
**Pull request by KlausC**
The expressions `a^x` and `@fastmath a^x` are now producing equivalent results (apart from floating point accuracy) in the case of literal integer `x`.
The logic in the `fastmath` macro, trying to mimic the behaviour of the compiler is fixed.  

Fixes #53817

### CODE REVIEW

**Comment by Seelengrab** [comment]
Per [CONTRIBUTING.md](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#git-recommendations-for-pull-requests), please provide a good description of what the PR does:

> Descriptive commit messages are good.

It's very cumbersome to have to go through three layers of indirection when looking at the history of a file (the change itself, this PR, and finally the issue itself) to figure out what exactly was broken with `@fastmath` in conjunction with `literal_pow`.

**Comment by KlausC** [comment]
> It's very cumbersome to have to go through three layers of indirection

Sorry for the inconvenience - I wanted to avoid repeating the error description for the issue. I added a description of what has been changed.

**Comment by Seelengrab** [comment]
Thank you!

**Comment by oscardssmith** [comment]
LGTM, although it would probably be good to add performance results to the PR, and ideally an example to the base benchmarks so we can see if this regresses.

**Comment by KlausC** [comment]
> add performance results to the PR

No performance changes are expected during runtime, because only the macro logic is changed.

The cases, which behave different do not exhibit changed performance figures. The 4th example in the changed
version now throws DomainError,  like the corresponding non-fastmath version.

For the cases, which now create different runtime code:

NEW: Version 1.12.0-DEV.233 (2024-03-22) krc/fastmath-literalpow/8615c0bdff
```
julia> foop1(a) = @fastmath a ^ 2305843009213693951
foop1 (generic function with 1 method)

julia> foop2(a) = @fastmath a ^ 2305843009213693952
foop2 (generic function with 1 method)

julia> foom2(a) = @fastmath a ^ -2305843009213693952
foom2 (generic function with 1 method)

julia> foom3(a) = @fastmath a ^ -2305843009213693953
foom3 (generic function with 1 method)

julia> a = 2
2

julia> @btime foop1($a)
  113.349 ns (0 allocations: 0 bytes)
0

julia> @btime foop2($a)
  24.203 ns (0 allocations: 0 bytes)
0

julia> @btime foom2($a)
  209.300 ns (0 allocations: 0 bytes)
0.0

julia> @btime foom3($a)
ERROR: DomainError with -2305843009213693953:
```

OLD: Julia Version 1.12.0-DEV.225
```
julia> @btime foop1($a)
  111.230 ns (0 allocations: 0 bytes)
0

julia> @btime foop2($a)
  24.192 ns (0 allocations: 0 bytes)
0

julia> @btime foom2($a)
  209.556 ns (0 allocations: 0 bytes)
0.0

julia> @btime foom3($a)
  209.655 ns (0 allocations: 0 bytes)
0.0
```

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
Looks good to me.

**Comment by mbauman** [comment]
My only hesitation — both here and in https://github.com/JuliaLang/julia/issues/53817 is that this really seems to be a bug in the Julia-flisp interface that doesn't match the expected and documented behaviors.  Ideally we'd fix that interface.  But I don't know how to do that and this is better than nothing.

**Comment by KlausC** [comment]
As soon as the flisp part is fixed, the limits introduced in #53713 and here have to be removed.

**Comment by KlausC** [comment]
This PR is now finished and can be merged if no objections.

**Pull request merged**
