### PR TITLE
interpreter: fix bug with ssair phi-node handling

### PR DESCRIPTION
**Pull request by vtjnash**
same as the bug Keno fixed in https://github.com/JuliaLang/julia/pull/28978/files#diff-6d4d21428a67320600faf5a1a9f3a16a

### CODE REVIEW

**Comment by vtjnash** [comment]
@Keno This is failing the 32-bit build. Can you tell me how to fix that?

**Comment by vtjnash** [comment]
For adding tests, I plan to run the core.jl tests with the interpreter (takes a couple minutes). There's just one test that needs to be fixed.

**Comment by JeffBezanson** [comment]
I would rather have an example of a specific function that fails. If an existing test in core.jl is sufficient that's fine, we should just copy it into a new test that runs it with --compile=min.

**Comment by vtjnash** [comment]
I know the approximate forms of IR that would fail, but I think it's also useful to show that our interpreter is an accurate representation of our compiler.

**Comment by JeffBezanson** [comment]
Yes, I agree it's useful to run some subset of the tests both in the interpreter and compiler, but we also need an example that's known to trigger this problem. Otherwise e.g. moving tests out of core.jl or other test changes could inadvertently stop testing for this.

**Pull request merged**
