### PR TITLE
Add iconv-based string encoding and decoding

### PR DESCRIPTION
**Pull request by nalimilan**
I think this is one of the major missing bits in Julia at the moment compared with competitors. iconv is available in libc in all POSIX.1-2001 compliant platforms and on Windows via Cygwin.

This PR adds:
- `StringEncodingPipe` and `StringDecodingPipe`, two `IO` types that convert between character encodings on the fly
- `encode` and `decode` which convert between strings and byte arrays in a given encoding
- a `readall` convenience method which wraps the stream in a `StringDecodingPipe`

The tests pass, but I think several points needs discussion, including:
- [ ] Bikeshed the names. I took inspiration from the Base64 names, but these names are quite long and not very friendly. `StringEncoder`/`StringDecoder` might be nicer. Besides, I'm not sure what `Pipe` exactly means here, as neither Base64 types nor the present ones are subtypes of `AbstractPipe`.
- [ ] Improve the `ccall` code. I'd like somebody to tell me what's the best way of passing a `Ptr{Array{UInt8}}` as `char**` from Julia. I've tried using `Ref` instead of `pointer`, but that didn't work. It would also be good to avoid calling `pointer` from `read`/`write` to avoid allocating memory. Should I store the pointers as objects fields?
- [ ] Discuss the best way of integrating this more with `open` and `write`, as in e.g. Python. Some variants of `open` can easily be extended with an `encoding` argument, but for the ones with varargs, it's not possible. But using keyword arguments would break type stability. Maybe supporting only the simplest method `open(fname::AbstractString, mode::AbstractString, encoding::ASCIIString)` would be enough.
- [ ] Throw more specific error types. `UnicodeError` cannot be used as it requires a byte offset and a character the code cannot compute (it would need to track the number of times the buffer was filled for the offset, which is kind of a waste). Anyway, this isn't always about Unicode, since two non-Unicode encodings can be chosen too. `StringEncodingError`?
- [ ] `encode` and `decode` can likely be made much more efficient by calling directly the iconv functions instead of creating `StringEncoder`/`StringDecoder` objects. They could also be made more user-friendly by showing the characters instead of their codes on decoding errors. There's also the question of how to make these efficient when you need to call them repeatedly on short strings. I could move the buffers to the `IConv` object, and allow creating one manually, with  `encode` and `decode` methods accepting it instead of an encoding string.

Anyway, please comment!

### CODE REVIEW

**Comment by tkelman** [comment]
Julia is not a Cygwin application. Can't assume posix. This would fit better in a package IMO, where you could get a mingw libiconv via winrpm.

**Comment by nalimilan** [comment]
Ah, too bad. I had thought about a creating a package, but this is such a basic functionality, with so limited requirements that I thought it should be available by default. Similar/competing languages generally provide built-in support (Python, Ruby, R, Swift, MATLAB...). We could include GNU libiconv (which is LGPL) on Windows. Though in line with the idea of shrinking base, this could go to a package which would be included by default.

The test failure on Windows is expected, but that on Mac OS X isn't clear. Looks like I'll have to get access to a Mac.

**Comment by nalimilan** [comment]
Any other opinions about this PR? Of course it would be fine as a package, be it temporary or not. Anyway, I'd be interested in comments about the points I raised above.

**Comment by nalimilan** [comment]
Given the lack of enthusiasm (to say the least :-), I'm withdrawing this PR, at least for now. Instead, I've set up a new package, which now passes relatively complete tests on Linux, Mac and Windows: https://github.com/nalimilan/iconv.jl/

In the meantime, I've discovered that a small library (https://github.com/win-iconv/win-iconv/) allows using the POSIX iconv API on Windows, calling the OS functions under the hood. It works quite well, and it's used for example by GLib, meaning its consistent enough with other implementations. That library lives in a single 2000-lines C file, and it's public domain. So it would be incredibly easy to include this in Julia when we feel the need for it.

**Comment by vtjnash** [comment]
cross-ref https://github.com/JuliaLang/julia/issues/14052, since one of our discussion points was how a StringEncodingPipe should fit into the API

**Comment by nalimilan** [comment]
@vtjnash Agreed. As regards the naming convention, I like `Stream` better than `Pipe`. But for now, in the package, I called them `StringEncoder` and `StringDecoder`.

**Pull request closed without merging**
