### PR TITLE
fix math in condskeel docstring

### PR DESCRIPTION
**Pull request by fredrikekre**
Update this

screen shot 2017-08-02 at 02 51 43

to this

screen shot 2017-08-02 at 02 51 54

### CODE REVIEW

**Review by andreasnoack — APPROVED** [review]
Maybe explain the `\vert`notation now that you are here anyway since I think most people have seen the notation used for the determinant.

**Review by Sacha0 — APPROVED** [review]
:) !

**Comment by fredrikekre** [comment]
Added an explanation of the `\vert` usage @andreasnoack

**Review by Sacha0 — APPROVED** [review]
lgtm for the additions! Thanks @fredrikekre ! :)

**Comment by fredrikekre** [comment]
Pre-#23124 Arnoldi failure.

**Pull request merged**
