### PR TITLE
RFC: Add tests for base/int.jl in new file test/int.jl

### PR DESCRIPTION
**Pull request by dpsanders**
This adds tests for the conversion functionality between different integer types in `base/int.jl`,
in a new file `test/int.jl`.

This is my first PR, so any feedback is appreciated.

### CODE REVIEW

**Comment by ScottPJones** [comment]
Nice, I like that it has the test name the same as the base name (I'm trying to get that to happen for strings, but I've got to convince people to merge my PR).
LGTM :+1:

**Comment by ViralBShah** [comment]
I can't fully understand the Problems at the end. Should they instead be in an issue or something rather than in comments at the end of the test file?

**Comment by tkelman** [comment]
note the 32 bit failures on appveyor and travis

**Comment by dpsanders** [comment]
@ViralBShah Yes sorry, they weren't meant for public consumption. I'll remove them

@tkelman Thanks. Is there a 32-bit machine available for local testing before submitting to Travis?

Another point: How can I test macros?

**Comment by tkelman** [comment]
> Is there a 32-bit machine available for local testing before submitting to Travis?

We can test some things on the buildbots, but I'm not sure whether it would be any faster than Travis in the end. It is possible to build a 32-bit Julia from 64-bit Linux though. Or use a 32 bit VM in Virtualbox.

**Comment by dpsanders** [comment]
There's a strange failure [here](https://travis-ci.org/JuliaLang/julia/jobs/69144000). Could someone restart  this, please?

**Comment by tkelman** [comment]
PSA: before restating Travis builds that have confusing-looking errors, it's best to save the log to a gist. When you restart a build on Travis the old log is no longer accessible.

**Comment by dpsanders** [comment]
These tests test (I believe) all the functionality that can be tested on a 64-bit machine, without touching the `base/int.jl` file (which would be a second step).

The exception is the `big_str` macro, that had to be modified in order to be able to test it with `@test_throws`. Incidentally, `int.jl` does not seem to be the good place for this macro.

**Comment by ScottPJones** [comment]
One thing that now concerns me, is that it looks like the Coveralls % coverage statistics are coming only from running on the 64-bit version, or am I missing something?
Really nice to see all of these tests added!

**Comment by kshyatt** [comment]
Bumping this. We seem to have some merge conflicts - @dpsanders, could you rebase on top of master, and if CI passes, can we merge this?

**Comment by tkelman** [comment]
David mentioned he'd be out of town for a little while with possibly spotty email. I doubt he'd mind if someone were in a hurry and wanted to rebase this for him.

**Comment by dpsanders** [comment]
I should be able to get to this tomorrow at the latest.

**Comment by tkelman** [comment]
Oh, spoke too soon. Sorry!

**Comment by dpsanders** [comment]
I think it's ready to go once it turns green.

**Comment by kshyatt** [comment]
This looks really great! Awesome job, @dpsanders :fireworks:. I hope the testing bug has bitten another person :)

**Comment by dpsanders** [comment]
Thanks! Yes, it was fun, and I learnt a lot!

**Comment by dpsanders** [comment]
Thanks :)

**Comment by vtjnash** [comment]
> The exception is the big_str macro, that had to be modified in order to be able to test it with `@test_throws`. Incidentally, int.jl does not seem to be the good place for this macro.

I'm slightly inclined to revert this at test it via `macroexpand` instead (so the user gets notified of the error sooner). Any particular reason to keep it this way? I'm not strongly against keeping it unchanged either.

**Comment by JeffBezanson** [comment]
I agree. It's not a huge deal, but throwing the error at macroexpand time seems better to me.

**Comment by StefanKarpinski** [comment]
Please don't revert the whole thing, just fix it.

**Pull request merged**
