### PR TITLE
relax repmat signature

### PR DESCRIPTION
**Pull request by CarloLucibello**
ref #20112

### CODE REVIEW

**Comment by andreasnoack** [comment]
It would be less expensive to use this pattern https://github.com/JuliaLang/julia/issues/17372#issuecomment-231952224. Then you would only compile very small methods for each combination of integer input type instead of recompiling the full `repmat` method.

**Comment by CarloLucibello** [comment]
>It would be less expensive to use this pattern #17372 (comment). Then you would only compile very small methods for each combination of integer input type instead of recompiling the full repmat method.

I implemented a slight variation  the comment, in which I splatter the argument, since repmat had two methods (for vector and matrices). Is this ok?

**Comment by andreasnoack** [comment]
LGTM. Needs a rebase.

**Comment by CarloLucibello** [comment]
rebased

**Comment by CarloLucibello** [comment]
merge? @andreasnoack

**Comment by andreasnoack** [comment]
One thing more: the docstring should probably be adjusted to reflect that all integer types can now be used.

**Comment by CarloLucibello** [comment]
ok, thanks. Something like this
```
    repmat(A, m, n=1)

Construct a matrix by repeating the given matrix `m` times in dimension 1 and `n` times in
dimension 2.
```
or like this
```
    repmat(A, m::Integer, n::Integer=1)
...
```
?
The former is clear enough, isn'it?

**Comment by andreasnoack** [comment]
I'd prefer the `Integer` version since it makes it clear that floating point values are not accepted.

**Comment by StefanKarpinski** [comment]
Bump – this seems ready to merge.

**Pull request merged**
