### PR TITLE
WIP Revenge of the precompile statement generator

### PR DESCRIPTION
**Pull request by KristofferC**
(This will be the third time we have made this PR, and we have become exceedingly efficient at it.)

Due to previous embarrassing reverts, this PR will not be merged until it is thoroughly reviewed I have tried this on all build bots and gotten good artifacts that I have tested and made sure they are working well.

The previous attempt at doing this was by spawning a new process where the stdout was redirected to a `Pipe` where the precompilation statements were printed into. In the spawned process a fake REPL was spawned and commands where executed into that which was what produced the precompilation statements.

This had some problems:

* It relied on that stdin of the process producing output being a PTY, otherwise we would have bad coverage of the startup.
* It used a `FakeTerminal` in the spawned process which was bad for coverage. While there was a textual replacement to of `FakeTerminal` to `REPL.Terminals.TTYTerminal` this wasn't 100% perfect.
* Pipes where used for stdin & co in the REPL replayer which was bad for coverage.
* Some output when generating statements was leaked to stdout which was a bit ugly.

The new PR instead creates a PTY and spawns a new julia process with that. REPL commands are written into the TTY and precompile statements are collected. From the spawned process point of view, this should be completely equivalent to being fed commands from a keyboard. This has the following advantages:

* Generating the precompile statements is faster (~ 5 seconds faster than previous PR).
* It requires less code (60 lines shorter than the previous PR) and this also has ~10 lines more of script that the REPL replays.
* The coverage should be completely accurate. For example, running julia with `--trace-compile=yes` and executing `? reinterpret` outputs zero precompilation statement. In the previous version of the PR, this was not true and you could see a tiny delay before the text appeared.
* It doesn't rely on the type of the streams of the process producing output.
* Completely silent.

Short demo: https://asciinema.org/a/Vs8CM20vP7kQVxTNPpOR4kECg

The major obstacle to overcome is how to do this on Windows. I am not sure at all how you would write the equivalent of `open_fake_pty` there.

### CODE REVIEW

**Comment by KristofferC** [comment]
The fact that CI now prints `748 precompile statements generated` (https://travis-ci.org/JuliaLang/julia/jobs/410239444#L1472) means that this method of generating is successful even on CI / build bots. Previously it was in the order of 650 statements due to the bad type of input streams.

**Comment by iblis17** [comment]
Just out of curiosity.
Why does freebsd ci show `759 precompile statements generated`, the number is inconsistent with linux's?

https://freebsdci.julialang.org/#/builders/1/builds/11828/steps/6/logs/stdio

**Comment by Keno** [comment]
To support cygwin an msys pipes, we fake a tty in the child process if the pipe matches a specific name: https://github.com/JuliaLang/julia/blob/master/src/jl_uv.c#L957-L966

You can probably create a pipe with that name to force the child process to use a TTY. @vtjnash may be able to help.

**Comment by JeffBezanson** [comment]
:cry: Noooo not the explicit list again! I guess this is the fastest way to get this merged; it will be better on non-windows and at least as good as before on windows. Then we have more time to develop a better solution on windows (though maybe it's impossible?).

**Comment by Keno** [comment]
> impossible

The solution I suggested above should work. I can take a look once this is merged.

**Comment by KristofferC** [comment]
> Noooo not the explicit list again! I guess this is the fastest way to get this merged; it will be better on non-windows and at least as good as before on windows. Then we have more time to develop a better solution on windows (though maybe it's impossible?).

Indeed, Nooo :)

The reason I put the last commit in is that I have some other obligations for the upcoming ~2weeks (JuliaCon and other things) so even though I would really like to dig down into the Windows issue, I won't be able to do that for some time. So, given those constraints, I put this PR into an as close as mergable state that I could, and then we can discuss whether it is worth merging even with the explicit list left or if we should wait until the Windows situation is fixed. While I really like the REPL experience with this PR I realize it is a bit problematic with the current state since it pessimizes an OS (compared to the others) so directly. 

I built some artifacts with the buildbots:

* https://s3.amazonaws.com/julialangnightlies/pretesting/bin/mac/x64/0.7/julia-d2ebd9399b-mac64.dmg
* https://s3.amazonaws.com/julialangnightlies/pretesting/bin/linux/x64/0.7/julia-d2ebd9399b-linux64.tar.gz

and I have verified that startup and REPL performance is as expected on both of them.

**Comment by KristofferC** [comment]
CircleCI is producing significantly fewer statements:

```
Generating precompile statements... 139 generated in  28.795173 seconds
```

Should look into that.

**Comment by KristofferC** [comment]
I am scared to say yes after two reverts heh. 

It would be nice to have Keno or Jameson briefly look over the pipe/stream stuff to make sure I am not deadlocking with some low probability. I haven't done very much of this before so don't really have the intuition yet.

**Review by Keno — APPROVED** [review]

**Pull request merged**
