### PR TITLE
rm tests of deprecated logging functions

### PR DESCRIPTION
**Pull request by stevengj**
As @StefanKarpinski suggested (https://github.com/JuliaLang/julia/pull/25067#issuecomment-352224057), this PR deletes the tests of the logging functions that were deprecated in #24490.

In fact, these tests had apparently already bitrotted because they aren't exercised by CI (which runs with `--depwarn=error`, I guess), making `make -C tests misc` break if you run it locally.

### CODE REVIEW

**Comment by stevengj** [comment]
MacOS Travis failure `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` seems unrelated.

**Review by c42f — COMMENTED** [review]
This looks fine to me.

I had an alternative for this which I thought addressed your concerns at https://github.com/JuliaLang/julia/commit/5d77d1b8ddd4bbe340e087802bf928ac208e4229#r26334167 a little more thoroughly.

It was coming as part of a larger cleanup of small odds and ends, but here it is #25239

Either way seems reasonable to me, though I think testing deprecations as a matter of course would be good practice.  It should be as simple as moving them to a section in `deprecation_exec.jl` just like we do for `base/deprecated.jl`

**Comment by c42f** [comment]
Hopefully I manage to remove the need for `--depwarn=error` soon so we won't need to run `deprecation_exec.jl` with special flags.

**Comment by c42f** [comment]
Superseded by #25239

**Pull request closed without merging**
