### PR TITLE
Remove 2x2 and 3x3 matrix multiply optimizations.

### PR DESCRIPTION
**Pull request by andreasnoack**
These predates https://github.com/JuliaArrays/StaticArrays.jl, which is the best way to get access to operations optimized for small matrices, the sizes are a bit arbitrary (why not 2x3?)`, they are not that efficient anyway because they are behind quite a few function calls, and they make the matrix multiply code more complicated.

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by nalimilan** [comment]
> they are not that efficient anyway because they are behind quite a few function calls

How large is the performance loss?

**Comment by mcognetta** [comment]
> > they are not that efficient anyway because they are behind quite a few function calls

> How large is the performance loss?

I am also interested in seeing the benchmarks. A few weeks ago I replaced the 2x2 code with the 7 multiplication version from Strassen's algorithm and there was a noticeable slowdown but I bet some further optimizations could be made with specific numerical types (like simd if it isn't being done automatically by the compiler). Anyway, my point is the results were a little unintuitive so I'd like to see what results others get for similar changes.

**Comment by KristofferC** [comment]
```jl
julia> using StaticArrays

julia> using BenchmarkTools

julia> a = rand(SMatrix{3,3});

julia> @btime $a * $a;
  7.000 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)

julia> A = rand(3,3);

julia> @btime $A * $A;
  76.132 ns [100.00% CPU, 0.00% GC] (1 allocation: 160 bytes)

julia> C = similar(A);

julia> @btime A_mul_B!($C, $A, $A);
  40.363 ns [102.50% CPU, 0.00% GC] (0 allocations: 0 bytes)
```

What's the point having these specialized functions if they are 7-10 times slower than static arrays.

**Comment by martinholters** [comment]
Assume the matrix sizes aren't known it advance, then there is the additional dynamic dispatch cost for the StaticArrays version. Don't know how much that eats away...

**Comment by KristofferC** [comment]
I'm having a hard time thinking out a realistic scenario where you are multiplying matrices of varying sizes and still have the performance be limited by 3x3 matrix multiplications.

**Comment by JeffBezanson** [comment]
> Why should we benchmark?

I'm going to pretend I didn't see that.

There always exists some faster way to do anything, but people aren't always aware of it. So I'd also like to see some simple benchmarks.

**Comment by ViralBShah** [comment]
The benchmark to see is what happens to the 2x2 and 3x3 multiplications for regular Base matrices before and after removing the special cased code. Also, it is likely that it makes other cases slightly faster, so good to benchmark, say, 10x10 too.

**Comment by KristofferC** [comment]
> I'm going to pretend I didn't see that.

I should have been more clear that my question was more hypothetical than literal. Of course, it should be benchmarked etc. My point was that the number of people that care about the speed of 3x3 matrix multiplication and at the same time gives up a pretty easy 5-10x speedup is probably quite small.

> There always exists some faster way to do anything, but people aren't always aware of it. So I'd also like to see some simple benchmarks.

The solution there seems to be to try harder to make people aware of it.

Anyway, here is a benchmark (0.6)

```
using StaticArrays
for i in 2:3
    println("-------- size $i x $i ---------")
    A = rand(i,i); B = rand(i,i); C = similar(A);
    a = rand(SMatrix{i,i}); b = rand(SMatrix{i,i})
    println("Static Arrays:")
    @btime $a * $b
    println("Base:")
    @btime A_mul_B!($C, $A, $B)
    println("BLAS:")
    @btime LinAlg.BLAS.gemm!('N', 'N', 1.0, $A, $B, 0.0, $C)
end
```

```
-------- size 2 x 2 ---------
Static Arrays:
  4.000 ns [125.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
Base:
  36.254 ns [102.78% CPU, 0.00% GC] (0 allocations: 0 bytes)
BLAS:
  126.824 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
-------- size 3 x 3 ---------
Static Arrays:
  8.008 ns [112.50% CPU, 0.00% GC] (0 allocations: 0 bytes)
Base:
  41.414 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
BLAS:
  146.635 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
```

**Comment by ViralBShah** [comment]
So, if we remove this, won't the time for these increase 4-fold, unless the argument is that it won't register in any real application? I mean it is a bit ugly and we don't want to add more cases, but why slow things down as they stand?

**Comment by ViralBShah** [comment]
@andreasnoack Does removing this dynamic dispatch check improve performance elsewhere in a visible way? Figure it is easier for you to try it out since you have the before and after.

**Comment by KristofferC** [comment]
> So, if we remove this, won't the time for these increase 4-fold, unless the argument is that it won't register in any real application? I mean it is a bit ugly and we don't want to add more cases, but why slow things down as they stand?

My guess is that the argument is that if you are worried about the speed of 3x3 and 2x2 matrices you would use the method that is 10x faster. The reason for slowing things down is that it reduces code, special cases, and number of methods that need to be compiled. But yes, they will indeed get slower.

Silly example, but you can always play games like:

```
function sortfast!(a)
    if length(a) == 1
        return a
    else
        sort!(a)
    end
end

a = [1]

julia> @btime sortfast!($a)
  6.000 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
1-element Array{Int64,1}:
 1

julia> @btime sort!($a)
  45.547 ns [100.00% CPU, 0.00% GC] (0 allocations: 0 bytes)
1-element Array{Int64,1}:
 1
```

> Does removing this dynamic dispatch check improve performance elsewhere in a visible way? 

This is not a dynamic dispatch though, it is just an `if` statement. It won't be noticeable at all compared to the runtime of a matrix multiplication.

**Comment by andreasnoack** [comment]
It is just so arbitrary to just have special handling of `2x2*2x2` and `3x3*3x3`. What about all the other small matrix combinations? I have no reason to believe that the square case is be more common than e.g. `3x3*3x1` which is not currently covered. Initially, I thought about extending the cases we cover in `LinearAlgebra` (and actually I did write the macro to handle it) but then decided that there are two kinds of people: those who care about small matrix performance and those who don't. As we can see from the benchmarks, those who do care are much better off with `StaticArrays`.

**Comment by andreasnoack** [comment]
> Does removing this dynamic dispatch check improve performance elsewhere in a visible way? Figure it is easier for you to try it out since you have the before and after.

I'm working on another PR right now, but I'll check later. I'd be surprised if it matters anything compared to the BLAS call though.

**Comment by JeffBezanson** [comment]
> if you are worried about the speed of 3x3 and 2x2 matrices you would use the method that is 10x faster

The problem is that this process is far from automatic. First, somebody will notice their code got slower in 0.7/1.0, and they won't know why. Then hopefully they analyze it, and if all goes well they find this thread. Then they have to figure out how to use StaticArrays and rewrite their code to use it. All of that is unnecessary pain.

People don't necessarily classify themselves as caring about small matrix performance or not; they just want everything to be as fast as possible.

**Comment by KristofferC** [comment]
>  Then they have to figure out how to use StaticArrays and rewrite their code to use it.

If their code got slower from this, then their code would now be dramatically faster though? And they would be very happy, I guess.

**Comment by JeffBezanson** [comment]
I just think we can find better ways to spend our time than going through code trying to slow things down.

**Comment by ViralBShah** [comment]
@Keno mentioned yesterday to me. Are these cases consistent with the new transpose and adjoint and all the other stuff? If not, it is best to remove.

**Comment by ViralBShah** [comment]
Ok, so the small transpose case does not even take these code paths.

```
julia> a = rand(2,2);

julia> @which a*a
*(A::AbstractArray{T,2} where T, B::AbstractArray{T,2} where T) in LinearAlgebra at /Users/viral/julia/usr/share/julia/site/v0.7/LinearAlgebra/src/matmul.jl:126

julia> @which a'*a
*(adjA::LinearAlgebra.Adjoint{#s545,#s544} where #s544<:(Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S, Base.ReshapedArray{T,2,A,MI} ... in LinearAlgebra at /Users/viral/julia/usr/share/julia/site/v0.7/LinearAlgebra/src/matmul.jl:226
```

**Comment by KristofferC** [comment]
I think they do:

```
julia> @btime $a * $a;
  58.359 ns (1 allocation: 112 bytes)

julia> @btime $(a') * $a;
  56.590 ns (1 allocation: 112 bytes)
```

They take a slightly different route, but end up in the same place.

**Comment by ViralBShah** [comment]
Those copies could certainly be avoided by hand rolling out the transpose cases. But that would mean going and updating this old code.

**Comment by KristofferC** [comment]
> Those copies could certainly be avoided by hand rolling out the transpose cases. But that would mean going and updating this old code.

The allocation is just to form the return matrix. Could be avoided using in place matrix multiplication:

```
julia> using LinearAlgebra

julia> c = similar(a);

julia> @btime mul!($c, $(a'), $a);
  21.584 ns (0 allocations: 0 bytes)

julia> @btime mul!($c, $a, $a)
  23.052 ns (0 allocations: 0 bytes)
```

**Comment by ViralBShah** [comment]
But the 2x2 and 3x3 codes have explicit copies in them currently, which are visible in the diff. Stuff like:

`A11 = copy(transpose(A[1,1]))`

**Comment by ViralBShah** [comment]
Ok, never mind. That only affects cases where you have non-bitstypes.

**Comment by KristofferC** [comment]
Yes, but copying a number is a no-op. I guess that copy is for cases where you have a matrix of matrices as a block matrix or something.

**Pull request closed without merging**
