### PR TITLE
meet_tvars: return bound tvar if both inputs are bound. Fixes #17648

### LINKED ISSUE #17648: Order of function defintion affects ambiguity detection
The following exhibits an ambiguity:
```jl
immutable MyArray{T,N} <: AbstractArray{T,N}
    data::Array{T,N}
end

Base.convert{T,N}(::Type{Array{T,N}}, A::MyArray{T,N}) = A.data
Base.convert{T<:AbstractFloat,N}(::Type{Array{T,N}}, A::MyArray{T,N}) = A.data
Base.convert{S<:AbstractFloat,N,T<:AbstractFloat}(::Type{Array{S,N}}, A::AbstractArray{T,N}) = copy!(Array{S}(size(A)), A)
Base.convert{S<:AbstractFloat,N,T<:AbstractFloat}(::Type{Array{S,N}}, A::MyArray{T,N}) = copy!(Array{S}(size(A)), A.data)

Base.Test.detect_ambiguities(Base)
```
However, switch the 3rd and 4th and there is no ambiguity.

### PR DESCRIPTION
**Pull request by timholy**
Untested locally, let's see what breaks...

### CODE REVIEW

**Comment by vtjnash** [comment]
It passed, so does that mean it should be merged now?

**Comment by timholy** [comment]
Hmm, this doesn't go deep enough: I still can't turn on precompilation for [ImagesAxes.jl](https://github.com/JuliaImages/ImagesAxes.jl/blob/master/src/ImagesAxes.jl).

**Comment by timholy** [comment]
OK, this version allows me to turn on precompilation for ImagesAxes. It passes tests locally, so assuming CI passes this version can be merged.

**Comment by vtjnash** [comment]
Should we run PkgEval on this before backporting?

**Comment by tkelman** [comment]
Already started what will hopefully become rc4 if it looks good. How critical is this?

**Comment by timholy** [comment]
The only known real-world bug this fixes is not being able to turn on precompilation in ImagesAxes.jl, so I'd rate it as non-critical. If this run works out, I'd recommend going with rc4 and waiting on this one until the next time you're backporting.

If rc4 needs more tweaks, then it would be nice to have.

**Comment by timholy** [comment]
Just thought of one more issue to consider, though: while I think it's unlikely, it's possible that there are packages relying on the current (broken) behavior. (This affects dispatch, so fixing the bug could conceivably change which functions get called.) If that proves to be true, there's always the possibility that fixing the bug in 0.5.1 would be breaking.

As long as you're aware of this risk and willing to accept the fact that we might need to encourage those packages to make fixes, I'd still say to go with rc4 as-is unless it requires additional PkgEval runs anyway.

**Pull request merged**
