### PR TITLE
Remove the FFTW bindings from Base

### LINKED ISSUE #18389: Move FFTW to a package
In response to a question from @jongwook at https://github.com/JuliaLang/julia/issues/17000#issuecomment-245165991 (I'd really like to keep that issue focused specifically on its title, of FFTW threading - if this issue gets resolved before that one does, then we'll move issue #17000 to the package)

> is it related to the GPL of FFTW

Yes. The goal is to have a default Julia distribution that doesn't contain any GPL components (aside from libgit2 and gcc runtimes which have linking exceptions, and possibly a few "mere aggregation" programs that aren't linked into the same address space), as soon as 0.6 if we can come up with a minimally-disruptive way of moving FFTW and SuiteSparse out to packages.

> in favor of other FFT implementation like MKL

Hard to say. I believe MKL has a mostly-FFTW-compatible FFT API, but it's not exactly equivalent so might not be a complete drop-in replacement in all respects. Either we make an FFTW.jl package that is capable of handling either the GPL FFTW library or the MKL version based on user choice (or whether the version of Julia being used is detected to already be using MKL for BLAS), or we separate the bindings for the GPL FFTW and the MKL FFT API into independent packages.

A pure-Julia MIT-licensed FFT was implemented in https://github.com/JuliaLang/julia/pull/6193 but never merged. I personally think that code should have been published as a Julia package from the start, so it could have been used for the past 2 years rather than sitting as a closed PR. I believe @yuyichao occasionally rebases a branch up to recent master but I'm not sure when he last did so.

### PR DESCRIPTION
**Pull request by ararslan**
Ready to merge!

This PR completely removes FFTW from Base. The bindings will instead be available in the [FFTW.jl](https://github.com/JuliaMath/FFTW.jl) package in the JuliaMath organization. ~~I'm still working on the package, but in the meantime I figured I'd put this up here to give folks a preview of what's to come.~~

- [x] DFT framework -> [AbstractFFTs.jl](https://github.com/JuliaMath/AbstractFFTs.jl)
- [x] FFTW bindings -> [FFTW.jl](https://github.com/JuliaMath/FFTW.jl)
- [x] DSP functions -> [DSP.jl](https://github.com/JuliaDSP/DSP.jl)

Fixes #18389

### CODE REVIEW

**Comment by ararslan** [comment]
@jlbuild !nuke
```
Pkg.clone("https://github.com/JuliaMath/FFTW.jl.git")
Pkg.checkout("FFTW", "master")
Pkg.build("FFTW")
Pkg.test("FFTW")
```

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/65bb63fc39e5b34a921864562de6841e2eb3aed1

I will edit this comment as the build jobs complete.

**Comment by ararslan** [comment]
This is getting really close. This PR, AbstractFFTs, and FFTW are ready to go, I just need to finish up the DSP package.

**Comment by ararslan** [comment]
The packages that inherited these functions are ready now, so this is good to go!

**Comment by ararslan** [comment]
Four hours in the CI queue after a rebase, but _now_ it's good to go.

**Comment by StefanKarpinski** [comment]
do it

**Comment by ararslan** [comment]
i did it

**Comment by StefanKarpinski** [comment]
Probably should have tried this before we merged this, but I'm seeing this:

```jl
julia> fft(rand(10))
ERROR: UndefVarError: pkg not defined
Stacktrace:
 [1] #fft#6(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at ./deprecated.jl:1448
 [2] fft(::Array{Float64,1}, ::Vararg{Array{Float64,1},N} where N) at ./deprecated.jl:1448
```

**Comment by JeffBezanson** [comment]
Ah, string interpolation strikes again :trollface:

**Comment by ararslan** [comment]
Ah crap. Will fix.

**Comment by ararslan** [comment]
Fix in #22391

**Comment by martinholters** [comment]
Something is still not quite as it should here (or am I missing something?), but the problem might be with DSP.jl?

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.1776 (2017-09-14 03:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit deceb3be66* (7 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.status("DSP")
 - DSP                           0.3.2

julia> using DSP

julia> xcorr([1, 2], [3, 4])
ERROR: Base.DSP.xcorr has been moved to the package DSP.jl.
Run `Pkg.add("DSP")` to install it, restart Julia,
and then run `using DSP` to load it.
Stacktrace:
 [1] error(::Function, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String) at ./error.jl:44
 [2] #xcorr#6(::Array{Any,1}, ::Function, ::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at ./deprecated.jl:126
 [3] xcorr(::Array{Int64,1}, ::Vararg{Array{Int64,1},N} where N) at ./deprecated.jl:126
```

OTOH:
```
julia> using DSP: xcorr

julia> xcorr([1, 2], [3, 4])
3-element Array{Int64,1}:
  4
 11
  6
```

**Pull request merged**
