### PR TITLE
add a try catch in hascolor so it returns false if tput not present

### PR DESCRIPTION
**Pull request by tkelman**
Avoids a freeze in environments that don't have ncurses installed
(such as the `opensuse:42.1` docker image)

It's used in `hascolor` here: https://github.com/JuliaLang/julia/blob/53ecbaa1392485764fd5fb42900175d29909223d/base/Terminals.jl#L182

### CODE REVIEW

**Comment by tkelman** [comment]
@nalimilan any opinion? I don't know if fedora ever exists without this part of ncurses installed?

**Comment by yuyichao** [comment]
Why is the test frozen? (Instead of failing or treat the tty as not supporting colors)

**Comment by tkelman** [comment]
it's doing readuntil it gets a prompt, but it never does, it gets a fail to spawn tput error when you try to start julia with TERM=dumb. Maybe worth checking if the stream has already received an eof and erroring there with the output from the child process instead of waiting to get a julia prompt

**Comment by tkelman** [comment]
Or I guess hascolor could do a try catch

**Comment by yuyichao** [comment]
> Or I guess hascolor could do a try catch

I think that's good in general. It'll be sad if one can't use julia simply because it cannot decide whether color output should be used.

**Pull request merged**
