### PR TITLE
fix shell mode interpolation while allowing special chars in commands

### LINKED ISSUE #22176: REPL shell mode string interpolation regression
Originally reported on [Discourse](https://discourse.julialang.org/t/repl-shell-mode-string-interpolation-on-0-6-rc2/4028)

On v0.5.1:
```
shell> echo $("hello world")
hello world
```

On v0.6.0-rc2.0:
```
shell> echo $("hello world")
$(hello world)
```

Version info:
```
Julia Version 0.6.0-rc2.0
Commit 68e911be53 (2017-05-18 02:31 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

cc @StefanKarpinski

### PR DESCRIPTION
**Pull request by StefanKarpinski**
fixes #22176, see also #20494 and #20482

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This commit cherry-picks cleanly onto master, so maybe I should have done it there, but I did the work on the 0.6 release branch, so we can do a forward cherry-pick later.

**Comment by StefanKarpinski** [comment]
I have no idea what the Windows failure is – something related to loading libfftw3?

**Comment by yuyichao** [comment]
It downloads the nightly which may not have fftw library anymore? Shouldn't be a problem on master.

**Comment by StefanKarpinski** [comment]
Ah, ok. I guess I'll close this and reopen against master.

**Comment by yuyichao** [comment]
> and reopen against master.

It'll probably show up again on the next backport release but I assume someone else ~~@tkelman~~ will worry about it :trollface:

**Comment by StefanKarpinski** [comment]
Yes, @tkelman knows better than I do how to test for Windows on non-master.

**Comment by tkelman** [comment]
fixed that in my backport branch

**Pull request closed without merging**
