### PR TITLE
Made \brokenbar ¦ and \notslash ⌿ infix. fixes #34651

### LINKED ISSUE #34651: \brokenbar ¦ and \notslash ⌿ should be parsed infix
As the title says, unless there is a compelling reason otherwise it seems that \brokenbar ¦ should be parsed infix, for consistency with all the other bars.

 So should \notslash ⌿, perhaps.

### PR DESCRIPTION
**Pull request by ravibitsgoa**
Fixes #34651

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by ravibitsgoa** [comment]
@JeffBezanson , Can this PR be merged if it is satisfactory?

**Comment by stevengj** [comment]
Needs a NEWS item

**Comment by JeffBezanson** [comment]
Ah, turns out this does not quite work yet, since these characters are in the "So" category. `is_wc_cat_id_start` needs to be modified as well.

**Comment by stevengj** [comment]
So this is technically a breaking change since they are valid parts of identifiers in 1.5:
```jl
julia> x¦ = 3
3

julia> x⌿ = 7
7
```
I doubt that it will break anything in practice, but should we revert the patch and create a new PR with the modifications to `is_wc_cat_id_start` and NEWS and then run pkgeval?

**Comment by JeffBezanson** [comment]
JuliaHub code search doesn't turn up any results, so it's probably ok.

**Pull request merged**
