### PR TITLE
Revise isdisjoint documentation and add doctest

### PR DESCRIPTION
**Pull request by LilithHafner**
Changed mostly to follow patterns in abstractset.jl

There is still an inconsistency between the argument names used in documentation (a, b) and argument names used in code (l, r). This inconsistency is visible to Julia's end users in Juno (and I suspect other IDEs). Should I also fix that by:
1. changing documented argument names to l, r
2. changing code argument names to a, b
3. changing code argument names to a, b only for non-infix functions and/or symmetric functions
I lean toward option 2.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Welcome, thanks for cleaning this up. Yes your option 2 sounds fine.

**Comment by LilithHafner** [comment]
Thanks! I think I've implemented it, but as you can see, am having some trouble.
I tried to follow the directions to squash small commits together and avoid having broken states in the history, but I think I botched it.
I'm also not sure why it fails tests on 32 bit windows. I tried to parse the error log, but couldn't make much sense of it, and I don't have a 32 bit windows machine to debug on.
Any help or advice appreciated.

**Comment by kshyatt** [comment]
Windows test error is an unrelated problem in LibSSH. Is this good to go now?

**Comment by LilithHafner** [comment]
Yes! Aside from windows test, all looks good to me.

**Pull request merged**
