### PR TITLE
Request to Test: detect cause of #16091

### PR DESCRIPTION
**Pull request by amitmurthy**
I would like anyone with access to a Windows system to test `examples` with this branch. Please run `examples` with a few other tests to trigger the parallel path in the test suite.

If not possible, I would like this merged after sometime to help with detecting #16091 .

### CODE REVIEW

**Comment by tkelman** [comment]
something horribly failed with CI here? closing and reopening to get the webhooks to fire

**Comment by tkelman** [comment]
I should note that I don't think I've ever seen the failure locally, only on appveyor.

**Comment by amitmurthy** [comment]
OK. I'll just keep rebuilding on AV and hope to trigger it. Wouldn't be surprised if it is a heisenbug.

**Comment by vtjnash** [comment]
good plan. maybe add the following test also:
```diff
diff --git a/test/examples.jl b/test/examples.jl
index 9c8b4a7..d85dcde 100644
--- a/test/examples.jl
+++ b/test/examples.jl
@@ -49,10 +49,10 @@ myid() == 1 || include(dc_path)
 
 # Run the remote on pid 1, since runtests may terminate workers
 # at any time depending on memory usage
-remotecall_fetch(1, dc_path) do f
+@test remotecall_fetch(1, dc_path) do f
     include(f)
-    nothing
-end
+    return :infungible
+end === :infungible
 dc=RemoteChannel(()->DictChannel(), 1)
 @test typeof(dc) == RemoteChannel{DictChannel}
 
```

my current suspicion is that this block is not being executed (or at least not before the RemoteChannel call)

**Comment by tkelman** [comment]
https://build.julialang.org/builders/nightly_threading-x86/builds/180/steps/make%20testall/logs/stdio
```
	From worker 9:	     * examples             Test Failed
	From worker 9:	  Expression: remotecall_fetch(((f,)->begin 
	From worker 9:	                include(f)
	From worker 9:	                return :infungible
	From worker 9:	            end),1,dc_path) === :infungible
	From worker 9:	   Evaluated: true is infungible
```

**Pull request merged**
