### PR TITLE
Fix warnings about unused static function

### PR DESCRIPTION
**Pull request by fingolfin**
There are a TON of warnings when compiling Julia right now,
get rid of some of them

### CODE REVIEW

**Comment by ViralBShah** [comment]
It would be better to fix the warnings than to silence them - because if silenced, they'll never be seen and fixed.

**Comment by fingolfin** [comment]
Well, one part of this PR fixes the root cause of some warnings. The other fixes warnings about the use of a C feature that is officially not supported in current C++, but in practice GCC and clang support. So unless someone rewrites the code in question (e.g. @keno, who wrote that code in the first place?), I see no alternative to turning off this warning. The warning is of very limited use anyway, as both gcc and clang support the feature and it won't go away, there are so many other things that really limit the current code base to clang and gcc

**Comment by giordano** [comment]
Looks like the warning is emitted only by clang?  With GCC now you get
```
cc1: warning: unrecognized command line option '-Wno-nested-anon-types'
```
which ironically is a _new_ warning.

**Comment by vtjnash** [comment]
The nested-anon-types are also being used to violate TBAA, so we should probably just remove it.

**Comment by fingolfin** [comment]
I've removed the Makefile change and changed the title correspondingly to "Fix warnings about unused static function"

**Pull request merged**
