### PR TITLE
[release-0.5] backport mapreduce fixes

### PR DESCRIPTION
**Pull request by alyst**
Backport #19325 and #21167 to 0.5 branch (I hope it's not too late for #21684):
- fix `mapreduce_impl()` for 1-element ranges
- avoid `@inbounds` propagating into user-specified `f`
- the backport doesn't include the changes of `mapreduce(f, min/max)` behaviour introduced in 0.6

### CODE REVIEW

**Comment by tkelman** [comment]
It's a bit on the late side, yes. Please cherry-pick with `-x -e` to include both commit and PR # cross-references

**Comment by alyst** [comment]
@tkelman Replaced the branch; is it ok like this? I did it with `-x -e`, but then, of course, I still had to resolve the conflicts and remove breaking changes (and correct the commit message)

**Comment by tkelman** [comment]
Thanks, that looks better, yeah. Though one thing that would help is if you could rebase this w.r.t. the 0.5.1 tag, rather than the tip of release-0.5. That way I could change the target of the PR to my tk/backports-0.5.2 branch without it pulling in the extra travis-related commit that's on release-0.5 but isn't in that branch.

**Comment by alyst** [comment]
@tkelman re-cherry-picked :)

**Pull request merged**
