### PR TITLE
Sparse solver reorganization

### PR DESCRIPTION
**Pull request by ViralBShah**
This helps keep all the sparse matrix code separate from other code in Base. It also paves the way for separating the GPL sparse solvers into a separate package.

### CODE REVIEW

**Comment by ViralBShah** [comment]
The eventual goal is to set things up so that new sparse solver packages can just provide a few methods like `lufact()` and `cholfact()`, and that it is easy to switch between solvers, while the generic code remains common and in base.

**Comment by ViralBShah** [comment]
Some related discussion here: https://github.com/JuliaSparse/MUMPSseq.jl/issues/1

**Comment by ViralBShah** [comment]
Given that the sparse solvers are now in Base.Sparse instead of Base.LinAlg, I wonder if this will have a major impact on packages, and what we can do to prevent the churn. The exported interfaces have not changed here.

Cc: @IainNZ @tkelman

**Comment by IainNZ** [comment]
Not sure, but I don't think it'll be too bad - I don't recall seeing code like LingAlg.SparseMatrixCSC, which would be only way it'd cause a problem right? I did some github searching, found e.g. this
https://github.com/ilovealldata/SelectMixedModels/blob/5f0a8a6b5d9272091474591075f9c66978a41436/src/SelectMixedModels.jl

**Comment by ViralBShah** [comment]
Cc: @ilovealldata

**Pull request merged**
