### PR TITLE
implement lowrankupdate for triangular matrices

### PR DESCRIPTION
**Pull request by bicycle1885**
This PR adds new `lowrankupdate` and `lowrankdowndate` methods and their in-place version for triangular matrices. Occasionally symmetric (or Hermitian) positive definite matrices are most naturally represented by their Cholesky factor. So, it would be great if we could directly update or downdate the factor without wrapping it in `Cholesky`. This behaviour is basically the same as [`cholupdate`](https://www.mathworks.com/help/matlab/ref/cholupdate.html) of MATLAB.

### CODE REVIEW

**Comment by bicycle1885** [comment]
Oh, the commit of `lowrankdowndate` has gone somewhere. Give me a moment.

**Comment by andreasnoack** [comment]
I'm not super excited about this one. I don't think it's a good idea to overload the existing function for the triangular matrices since it suggests that you are making a low-rank modification of the triangular matrix.

> So, it would be great if we could directly update or downdate the factor without wrapping it in Cholesky.

Could you elaborate here? It's not clear to me why you don't want to use `Cholesky` here.

**Comment by bicycle1885** [comment]
> it suggests that you are making a low-rank modification of the triangular matrix.

You are right. Perhaps I too much focused on the low-rank update of the Cholesky factor and other low-rank updates were out of scope. In my specific use case, I need to do a bunch of Cholesky downdates for a small matrix for the purpose of Monte-Carlo sampling. Because the matrix is symmetric positive definite, the most natural way to represent it is to use a lower triangular matrix. However, the standard library doesn't that operation so I thought it would be good to have one.

The current workaround is like:
```julia
LL = lowrankdowndate(Cholesky(L, 'L', 0), x).L
# do some operation (e.g. multiplication) using LL
```

But it looked awkward. So, I made this pull request so that we could write it more elegantly:
```julia
LL = lowrankdowndate(L, x)
```

A possibly better compromise is to define constructors for triangular matrices:
```julia
LL = lowrankdowndate(Cholesky(L), x).L
```

What do you think about this?

**Comment by andreasnoack** [comment]
I like that. Having `Cholesky` constructors for `LowerTriangular` and `UpperTriagular` should be unambiguous.

**Comment by bicycle1885** [comment]
Thank you for your comment. I've opened a new pull request at #39352 that supersedes this pull request.

**Pull request closed without merging**
