### PR TITLE
Uint => UInt in random.jl

### PR DESCRIPTION
**Pull request by WestleyArgentum**

### CODE REVIEW

**Comment by jiahao** [comment]
Can has tests? :)

**Comment by tkelman** [comment]
victim of #11200

**Comment by WestleyArgentum** [comment]
I'm sorry, I'm not entirely sure what's wrong... The tests pass locally, and AppVeyor seems to be alright, but Travis is angry. I see plenty of errors in the Travis log, but those all appear in the output of successful Travis builds as well...

**Comment by tkelman** [comment]
I think something's wrong with the dsfmt download. @staticfloat can you check on the cache server to see whether or not it's healthy?

**Comment by staticfloat** [comment]
The original server isn't responding, which causes the ETAG verification to take a really long time.  [I've maxed it out at 1s now](https://github.com/staticfloat/cache.julialang.org/commit/870066254cade0d4a61a18fc9e63bb484d10bdd7), so things seem to be working better.

**Comment by tkelman** [comment]
Awesome, thanks.

**Comment by ivarne** [comment]
The easy way to test for issues like this would be to comment out `include("deprecated.jl")` in [base/sysimg.jl](https://github.com/JuliaLang/julia/blob/6682661e5825a05cf09b403b9b6efca85d1488f1/base/sysimg.jl#L296) before running tests.

**Pull request merged**
