### PR TITLE
Make Distributed.Worker threadsafe [Take 2]

### LINKED ISSUE #73: Concurrency violation on interplay between Distributed and Base.Threads
I’m working on a distributed pipeline algorithm that uses several stages per worker process. IIRC tasks cannot hop between threads once they’ve been scheduled. Since I want my stages to potentially run in parallel, I tried to create non-sticky tasks by chaining each `D.@spawnat` with a `T.@spawn`. However, this setup keeps failing/crashing and I don’t understand why.

I boiled it down to a minimal example:

```julia
using Distributed, Base.Threads

const D = Distributed
const T = Threads

pids = addprocs(10)
wids = repeat(pids, inner=2)

conns = map(RemoteChannel, wids)
fst = first(conns)
lst = RemoteChannel()
push!(conns, lst)

@everywhere begin
    function stillepost(i, prev, next)
        message = take!(prev)
        put!(next, message)
        @info "Player $i done"
    end
end

players = []
for i in 1:length(wids)
    w = wids[i]
    c1 = conns[i]
    c2 = conns[i+1]
    p = D.@spawnat w fetch(T.@spawn stillepost(i, c1, c2))
    push!(players, p)
end

game = @async begin
    m1 = "gibberish"
    put!(fst, m1)
    m2 = take!(lst)
    @info "'$m1' turned into '$m2'; well done!"
end

wait.(players)
wait(game)
```

Player 2 fails with a concurrency violation:

```
julia> include("stillepost.jl")
[ Info: Player 1 done
ERROR: LoadError: On worker 2:
TaskFailedException:
concurrency violation detected
error at ./error.jl:33
concurrency_violation at ./condition.jl:8
assert_havelock at ./condition.jl:25 [inlined]
assert_havelock at ./condition.jl:48 [inlined]
assert_havelock at ./condition.jl:72 [inlined]
wait at ./condition.jl:102
wait_for_conn at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/cluster.jl:193
check_worker_state at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/cluster.jl:168
send_msg_ at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/messages.jl:176
send_msg at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/messages.jl:134 [inlined]
#remotecall_fetch#143 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:389
remotecall_fetch at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:386
#remotecall_fetch#146 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
remotecall_fetch at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
call_on_owner at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:494
put! at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:595 [inlined]
stillepost at /Users/jonas/.../stillepost.jl:18
JuliaLang/julia#3 at ./threadingconstructs.jl:169
wait at ./task.jl:267 [inlined]
```

Am I holding it wrong?

```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PROJECT = @.
```

See also [this post](https://discourse.julialang.org/t/concurrency-violation-on-interplay-between-distributed-and-base-threads/47080) on discourse. foobar_lv2 suggested this might be a bug in Distributed.

### LINKED ISSUE #37706: Concurrency violation on interplay between Distributed and Base.Threads
I’m working on a distributed pipeline algorithm that uses several stages per worker process. IIRC tasks cannot hop between threads once they’ve been scheduled. Since I want my stages to potentially run in parallel, I tried to create non-sticky tasks by chaining each `D.@spawnat` with a `T.@spawn`. However, this setup keeps failing/crashing and I don’t understand why.

I boiled it down to a minimal example:

```julia
using Distributed, Base.Threads

const D = Distributed
const T = Threads

pids = addprocs(10)
wids = repeat(pids, inner=2)

conns = map(RemoteChannel, wids)
fst = first(conns)
lst = RemoteChannel()
push!(conns, lst)

@everywhere begin
    function stillepost(i, prev, next)
        message = take!(prev)
        put!(next, message)
        @info "Player $i done"
    end
end

players = []
for i in 1:length(wids)
    w = wids[i]
    c1 = conns[i]
    c2 = conns[i+1]
    p = D.@spawnat w fetch(T.@spawn stillepost(i, c1, c2))
    push!(players, p)
end

game = @async begin
    m1 = "gibberish"
    put!(fst, m1)
    m2 = take!(lst)
    @info "'$m1' turned into '$m2'; well done!"
end

wait.(players)
wait(game)
```

Player 2 fails with a concurrency violation:

```
julia> include("stillepost.jl")
[ Info: Player 1 done
ERROR: LoadError: On worker 2:
TaskFailedException:
concurrency violation detected
error at ./error.jl:33
concurrency_violation at ./condition.jl:8
assert_havelock at ./condition.jl:25 [inlined]
assert_havelock at ./condition.jl:48 [inlined]
assert_havelock at ./condition.jl:72 [inlined]
wait at ./condition.jl:102
wait_for_conn at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/cluster.jl:193
check_worker_state at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/cluster.jl:168
send_msg_ at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/messages.jl:176
send_msg at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/messages.jl:134 [inlined]
#remotecall_fetch#143 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:389
remotecall_fetch at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:386
#remotecall_fetch#146 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
remotecall_fetch at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
call_on_owner at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:494
put! at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:595 [inlined]
stillepost at /Users/jonas/.../stillepost.jl:18
#3 at ./threadingconstructs.jl:169
wait at ./task.jl:267 [inlined]
```

Am I holding it wrong?

```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PROJECT = @.
```

See also [this post](https://discourse.julialang.org/t/concurrency-violation-on-interplay-between-distributed-and-base-threads/47080) on discourse. foobar_lv2 suggested this might be a bug in Distributed.

### PR DESCRIPTION
**Pull request by vchuravy**
cc: @jonas-schulze  

If my understanding is correct, the issue was that on the slower CI machines the `timedwait` could feasibly timeout and cause the subsequent test to fail. This replaces the `timedwait` with actual waits. 

Should be squashed on merge. 

Fixes JuliaLang/Distributed.jl#73

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
Ah yes, the dreaded `timedwait` function. Yes we should always try to avoid that in preference for more responsible implementations.

**Comment by jonas-schulze** [comment]
The `timedwait` was not the issue; I used it on purpose so that the tests definitely do not get stuck (or: fail before CI times out after 1h or so). If it would have been the issue, the tests would just have failed, but they errored.

I'm on vacation this week and don't have a laptop at hand.

**Comment by vchuravy** [comment]
> If it would have been the issue, the tests would just have failed, but they errored.

I was looking at https://build.julialang.org/#/builders/52/builds/4632/steps/5/logs/stdio

```
      From worker 4:	from thread 1.1 to 2.2: Test Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/Distributed/test/threads.jl:48
      From worker 4:	  Expression: isdone(recv)
      From worker 4:	Stacktrace:
      From worker 4:	 [1] top-level scope
      From worker 4:	   @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/Distributed/test/threads.jl:48
      From worker 4:	 [2] top-level scope
      From worker 4:	   @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1219
      From worker 4:	 [3] top-level scope
      From worker 4:	   @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/Distributed/test/threads.jl:32
      From worker 4:	 [4] top-level scope
      From worker 4:	   @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1219
      From worker 4:	 [5] top-level scope
      From worker 4:	   @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/Distributed/test/threads.jl:31
      From worker 4:	 [6] top-level scope
      From worker 4:	   @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1144
      From worker 4:	 [7] top-level scope
      From worker 4:	   @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/Distributed/test/threads.jl:29
```

Which definitely looks like a time out.

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
Still might be failing? https://build.julialang.org/#/builders/4/builds/5236

**Comment by vchuravy** [comment]
>       From worker 56:	error in running finalizer: ErrorException("concurrency violation detected")

yeah...., much rarer so this might be a case of the actual code change not being sufficient.

**Comment by jonas-schulze** [comment]
Maybe we should replace `any_gc_flag`?

**Comment by vtjnash** [comment]
I don't know if it is much rarer or a different issue, but almost 25% of builds are failing in this test (ie. https://build.julialang.org/#/builders/52/builds/4884)

**Comment by vchuravy** [comment]
```
      From worker 56:	signal (11): Segmentation fault
      From worker 56:	in expression starting at none:0
      From worker 56:	*** Error in `/buildworker/worker/tester_linuxaarch64/build/bin/julia': free(): corrupted unsorted chunks: 0x000000000e0e13f0 ***
      From worker 56:	
      From worker 56:	signal (6): Aborted
      From worker 56:	in expression starting at none:0
      From worker 56:	gsignal at /lib/aarch64-linux-gnu/libc.so.6 (unknown line)
      From worker 56:	abort at /lib/aarch64-linux-gnu/libc.so.6 (unknown line)
      From worker 56:	Allocations: 13059132 (Pool: 13054874; Big: 4258); GC: 15
```

That looks like a peculiar FreeBSD issue.

**Pull request merged**
