### PR TITLE
Check bounds upon construction of SubArrays.

### LINKED ISSUE #9924: Segfault due to `free(): invalid pointer`
Can I say again how much I'm enjoying #8699? For a change, it's hard to see the impact of gc on performance.

Unsurprisingly, in heavy usage I am noticing some segfaults, which I imagine might be related to that PR. (I also wonder if, since gc runs more frequently, it might simply be revealing pre-existing bugs.) There's one I haven't pinned down yet, which seems to be triggered relatively frequently by interacting with windows created by ProfileView.

However, here's one that does seem to be reasonably reproducible. Unfortunately it's after a massive computation involving many thousands of lines of code, and I haven't yet gotten around to reducing the size of the test case. But for what it's worth:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff67babd3 in _int_malloc (av=0x7ffff6af9760 <main_arena>, bytes=1024) at malloc.c:3551
3551    malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff67babd3 in _int_malloc (av=0x7ffff6af9760 <main_arena>, bytes=1024) at malloc.c:3551
#1  0x00007ffff67bd340 in __GI___libc_malloc (bytes=1024) at malloc.c:2891
#2  0x00007ffff778068d in llvm::SmallPtrSetImpl::Grow(unsigned int) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#3  0x00007ffff77807d3 in llvm::SmallPtrSetImpl::insert_imp(void const*) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#4  0x00007ffff70c9909 in llvm::ScheduleDAGSDNodes::BuildSchedUnits() () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#5  0x00007ffff70c9cf1 in llvm::ScheduleDAGSDNodes::BuildSchedGraph(llvm::AliasAnalysis*) ()
   from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#6  0x00007ffff70c248a in (anonymous namespace)::ScheduleDAGRRList::Schedule() () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#7  0x00007ffff706456c in llvm::SelectionDAGISel::CodeGenAndEmitDAG() () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#8  0x00007ffff7066902 in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) ()
   from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#9  0x00007ffff7067a58 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
   from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#10 0x00007ffff7724cff in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#11 0x00007ffff7724dde in llvm::FunctionPassManagerImpl::run(llvm::Function&) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#12 0x00007ffff7724eb4 in llvm::FunctionPassManager::run(llvm::Function&) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#13 0x00007ffff71d0774 in llvm::JIT::jitTheFunction(llvm::Function*, llvm::MutexGuard const&) ()
   from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#14 0x00007ffff71d0d6f in llvm::JIT::runJITOnFunctionUnlocked(llvm::Function*, llvm::MutexGuard const&) ()
   from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#15 0x00007ffff71d0f42 in llvm::JIT::getPointerToFunction(llvm::Function*) () from /home/tim/src/julia/usr/bin/../lib/libjulia-debug.so
#16 0x00007ffff6e0e794 in jl_generate_fptr (f=0x7ffdf534b100) at codegen.cpp:676
#17 0x00007ffff6dfff62 in jl_trampoline_compile_function (f=0x7ffdf534b100, always_infer=0, sig=0x7ffdf3830000) at builtins.c:922
#18 0x00007ffff6e0007b in jl_trampoline (F=0x7ffdf534b100, args=0x7fffffffd7a0, nargs=2) at builtins.c:933
#19 0x00007ffff6df07be in jl_apply (f=0x7ffdf534b100, args=0x7fffffffd7a0, nargs=2) at julia.h:1057
#20 0x00007ffff6df6738 in jl_apply_generic (F=0x7ffdf49b1980, args=0x7fffffffd7a0, nargs=2) at gf.c:1685
#21 0x00007ffff5333a25 in julia__start_64310 () at client.jl:449
#22 0x00007ffff53346a9 in jlcall.start_64310 () from /home/tim/src/julia/usr/lib/julia/sys.so
#23 0x00007ffff6dfc16e in jl_apply (f=0x7ffdf4e83b40, args=0x0, nargs=0) at julia.h:1057
#24 0x00007ffff6e00091 in jl_trampoline (F=0x7ffdf4e83b40, args=0x0, nargs=0) at builtins.c:934
#25 0x00007ffff6df07be in jl_apply (f=0x7ffdf4e83b40, args=0x0, nargs=0) at julia.h:1057
#26 0x00007ffff6df662c in jl_apply_generic (F=0x7ffdf4e83500, args=0x0, nargs=0) at gf.c:1665
---Type <return> to continue, or q <return> to quit---
#27 0x0000000000401448 in jl_apply (f=0x7ffdf4e83500, args=0x0, nargs=0) at ../src/julia.h:1057
#28 0x0000000000402152 in true_main (argc=1, argv=0x7fffffffdce0) at repl.c:338
#29 0x0000000000402318 in main (argc=1, argv=0x7fffffffdce0) at repl.c:389
```
What's interesting is that while this sequence of commands always triggers a bug, the manifestation seems to vary: I got the above when running through gdb, I got `malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.` when running from bash, sometimes the message in the title of the issue, and an occasional pure hang (no segfault, not interruptable by Ctrl-C, etc).

### PR DESCRIPTION
**Pull request by timholy**
Fixes #9924, and see #4044. It seems appropriate to say "hoisted by my own petard," but of course it's not like we used to check and now we don't.

This is not quite as powerful a solution as the one outlined in https://github.com/JuliaLang/julia/issues/4044#issuecomment-72381862, but that can't happen until something like #8227 is merged.

### CODE REVIEW

**Comment by jakebolewski** [comment]
I like the suffix 'unsafe'.

**Comment by timholy** [comment]
Will change, it's more consistent that way.

**Comment by timholy** [comment]
Our OSX tests are starting to get a little close to that 50 minute timeout limit: https://travis-ci.org/JuliaLang/julia/builds/51845135

**Comment by timholy** [comment]
It just takes *sooo* long for the tests to run, I thought it better to save the CPU cycles for other people.

I agree it's a little strange, but I decided it would be OK here. There's no "code," so it can't break anything other than tests themselves (we'll know soon enough if it causes problems for other PRs), and I did try it on my laptop first.

**Comment by tkelman** [comment]
True, CI will run on the merge commit anyway (unless you also go and put in [ci skip] there), so as long as people keep an eye on master it wouldn't cause problems for too long. I think OSX Travis is the slowest in overall runtime, but it also does a few more things than what runs on appveyor (debug build, make install, pkg test, etc). AIUI the OSX Travis VM's run on some relatively old hardware, so it's tough to optimize that much.

**Pull request merged**
