### PR TITLE
RFC: fix #2501

### LINKED ISSUE #2501: Make `helpdb.jl` and docs as part of build
Now that binary builds are a reality, it might be time for us to stop checking in `helpdb.jl` and make Sphinx a build dependency. We could consider making it an option so you could choose not to build the docs (another Make variable?)

This has implications for the work @wlbksy is doing in #2499.

### PR DESCRIPTION
**Pull request by tkelman**
Build helpdb.jl instead of checking it in to repository.

~~In my local builds, there's a kinda funny race condition between the system image getting to `base/help.jl` vs the Sphinx build finishing, they happen at the same time with `-j` > 1. That could be fixed with a few more explicit makefile dependencies, but it's a little faster this way, and `help.jl` is near the end of the sysimg, well after inference which takes a good chunk of time.~~ nevermind, not a race condition, `helpdb.jl` is a dependency of `sys.o`, not `sys0.o`. System image seems to build fine even without `helpdb.jl` present at all?

### CODE REVIEW

**Comment by tkelman** [comment]
I don't know enough about Python `virtualenv`s to figure out what's happening on appveyor https://ci.appveyor.com/project/tkelman/julia/build/1.0.619/job/ypr5i09d4kqvkcs8:
```
New python executable in julia-env\Scripts\python.exe
Installing setuptools, pip...done.
/bin/sh: /c/projects/julia/deps/julia-env/bin/activate: No such file or directory
make[2]: *** [/c/projects/julia/deps/julia-env/bin/sphinx-build] Error 1
```

Any ideas?

**Comment by tkelman** [comment]
Grr, Win32 Python you are awful and I hate you. Evidently `activate` and `sphinx-build.exe` end up in `Scripts` if you're using a Win32 Python, as opposed to a posix Python. Anyone know the canonical way of determining whether or not a given Python is Win32?

**Comment by catawbasam** [comment]
http://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os

looks relevant.

**Comment by tkelman** [comment]
@catawbasam thanks but I think 32 vs 64 bit shouldn't matter much as far as Sphinx is concerned. What I was referring to was whether the python executable is, say Cygwin-style, where conventions like `/bin` vs `/Scripts` match Unix systems, or Win32-style which is different because someone at some point felt `/Scripts` was a more Windows-y name than `/bin`.

**Comment by tkelman** [comment]
Changing to RFC since I got it to work on AppVeyor. Should probably delete `helpdb.jl`, and maybe also `$(build_docdir)`, in one of `make clean` or `make cleanall`. Thoughts?

**Comment by ViralBShah** [comment]
I think `make cleanall` should be the target to delete `$(build_docdir)` in. 

Does building `helpdb.jl` get triggered when any file in `doc/stdlib` it depends on changes? It doesn't seem to be the case right now, but I may be missing something.

**Comment by tkelman** [comment]
> Does building `helpdb.jl` get triggered when any file in `doc/stdlib` it depends on changes?

There is a dependency in `doc/Makefile` on `stdlib/*.rst` for the `helpdb.jl` target, so I would think so.

> It doesn't seem to be the case right now, but I may be missing something.

Did you test this branch out and see it not rebuild when it should've? I admittedly should do more testing on this branch (and it needs a rebase) to get a feel for how well-behaved it is.

**Comment by tkelman** [comment]
rebased and added `@rm -f doc/helpdb.jl $(build_docdir)/helpdb.jl` to `make cleanall`. Let's see what CI thinks about it. I somehow managed to lose the Windows Python `/Scripts` fix in my first rebase, whoops. Dug it up on Travis though.

**Comment by tkelman** [comment]
@jiahao any idea how to fix the unicode table warning? that would get pretty annoying to see in every CI log

**Comment by jiahao** [comment]
The Unicode table simply needs to be rebuilt on master. Done in 27d6c1d

I added a new doc Make target to simplify rebuilding this table (it has to be done every time someone changes latex_symbols.jl). Now you can run `make -C doc unicode`.

**Comment by tkelman** [comment]
closing this since it looks like helpdb.jl will be going away imminently

**Pull request closed without merging**
