### PR TITLE
Update Travis CI build to try building docs

### PR DESCRIPTION
**Pull request by jiahao**
This PR adds automatic doctest builds to Travis. By including the doctests as part of the Travis test suite, the hope is to prevent the documentation examples from becoming so far out of sync with reality as to require serious manual updating, as in #7693.

This is the brute force solution to #7691.

Four documentation tests are included here:
- HTML documentation build test
- PDF documentation build test (which can catch some embedded HTMLisms)
- Doctest build test (runs example blocks and compares them with the embedded output)
- Link test (checks that links are still current)

### CODE REVIEW

**Comment by jiahao** [comment]
I've updated this PR so that only the basic HTML and PDF docbuilds are run. 

I realize that these tests add more time to the Travis build, but it takes only about a minute or two to run and will catch syntax errors in changes to the documentation, which are unfortunately quite frequent since not many people are familiar with the nuances of ReStructuredText.

As for the doctests, I think running them as part of the `release-candidate` target is the best we can hope for at this point without an extensive rewrite of `JuliaDoc`.

cc @tkelman @staticfloat

**Comment by tkelman** [comment]
Related: #9553 #9554 
We shouldn't need to touch apt-get, pip, or brew upgrade gcc here, I think.

**Comment by jiahao** [comment]
I'll remove the gcc line, it must have been left over from the rebase.

The pip lines are necessary to install sphinx and the doc theme correctly.

**Comment by jiahao** [comment]
Oh, I guess the new virtualenv setup means that it's no longer necessary. Let me try that.

**Comment by staticfloat** [comment]
Alternative idea;  We could add an entry to the build environment matrix that is a "no-arch" run, that just builds the docs and not Julia.  It can then run in parallel to the other jobs, and won't run multiple times.

**Comment by tkelman** [comment]
That's exactly the approach I took in #9553, which I am increasingly convinced no one other than me has ever looked at.

**Comment by jiahao** [comment]
Sounds good. I think @tkelman proposed something similar in one of the other issues.

This afternoon I played around with trying to make Travis short-circuit the build if only doc files were changed. (see the cjh/probe-travis branch)

I've figured out what to do as a git pre-push hook [here](https://github.com/jiahao/julia-helper/blob/master/julia/git-hooks/pre-push.sample#L14), but Travis appears to choke on the `;;` in the case statement and I haven't figured out how to fix it. Perhaps you'll have some idea.

**Comment by tkelman** [comment]
I don't know where you're getting the inputs from, but note that `$remote_sha` from Travis is generally not accurate. Travis typically sets it to the sha of a merge commit at time of build queuing, not the actual merge commit that gets fetched.

> Travis appears to choke on the `;;` in the case statement and I haven't figured out how to fix it

If you try to write too much bash in yaml you will only end up tearing your hair out. Write a script under `contrib` or `contrib/ci` and just call it.

**Comment by jiahao** [comment]
The pre-push hook is for my local use; it will have to be adapted to the Travis environment.

>  note that $remote_sha from Travis is generally not accurate

I did notice this and tried to substitute as proxy the nearest branch point. I tried the magic incantation from [this SO thread](http://stackoverflow.com/questions/3161204/find-the-parent-branch-of-a-branch#comment35666518_17843908)

    PARENT_BRANCH=`git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'`

It worked locally in that branches off master gave PARENT_BRANCH=master and similarly for release-0.3, but not on Travis

https://travis-ci.org/JuliaLang/julia/builds/49214143#L136

I think owing to the clone being shallow.

**Comment by tkelman** [comment]
There's also something a little strange about the way remotes work on Travis that can make `version_git.sh` behave oddly.

**Comment by jiahao** [comment]
I'll leave my git experiments here for now. It's time to ford the 3' snow piles in search of suds and vittles.

**Comment by tkelman** [comment]
No longer relevant, we've been building the docs in `make install` for some time.

**Comment by jiahao** [comment]
But not the manual.

**Comment by tkelman** [comment]
Good point, guess we could reopen and/or try again.

**Pull request closed without merging**
