### PR TITLE
🤖 [master] Bump the SparseArrays stdlib from 760989e to c09f0ac

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Stdlib branch: main
Julia branch: master
Old commit: 760989e
New commit: c09f0ac
Julia version: 1.10.0-DEV
SparseArrays version: 1.10.0
Bump invoked by: @ViralBShah
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaSparse/SparseArrays.jl/compare/760989ec650761541deff039efb5b767a051c172...c09f0ac575165ddf4d264c15284d8fc0f8ac54b0

```
$ git log --oneline 760989e..c09f0ac
c09f0ac Handle SuiteSparse >= 7 (#353)
f22cab0 fix doc spelling, grammar for lu (#352)
cb79e06 Clean up temporary fixes (#348)
195c470 Replace AbstractTriangular by UpperOrLowerTriangular (#329)
d938744 Fix "map does not respect sources index type" (#350) (#351)
38604c3 Fix bug where non-order keyword arguments are passed from `sort!` to `searchsortedfirst` (#335)
0d2d30a Keep `Hermitian(::Sparse) \ SparseArray` throwing (#322)
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
From worker 4:	Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/julia-1ea056bc37/share/julia/stdlib/v1.10/LinearAlgebra/test/ambiguous_exec.jl:5
  | From worker 4:	  Expression: isempty(ambig)
  | From worker 4:	   Evaluated: isempty(Tuple{Method, Method}[(*(u::Adjoint{T, <:AbstractVector} where T, Q::LinearAlgebra.AbstractQ) @ LinearAlgebra /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/julia-1ea056bc37/share/julia/stdlib/v1.10/LinearAlgebra/src/abstractq.jl:144, *(A::AbstractMatrix, adjQ::LinearAlgebra.AdjointQ{<:Any, <:SparseArrays.SPQR.QRSparseQ}) @ SparseArrays.SPQR /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/julia-1ea056bc37/share/julia/stdlib/v1.10/SparseArrays/src/solvers/spqr.jl:312)])
  | From worker 4:
  | From worker 4:	ERROR: LoadError: There was an error during testing
  | From worker 4:	in expression starting at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-master/julia-1ea056bc37/share/julia/stdlib/v1.10/LinearAlgebra/test/ambiguous_exec.jl:4
 ```

**Comment by DilumAluthge** [comment]
@ViralBShah @dkarrasch

**Comment by ViralBShah** [comment]
We should probably run linear algebra tests in the SparseArrays repo.

**Comment by DilumAluthge** [comment]
You don't necessarily need to run all of them, just the ambiguity tests and maybe a few other tests.

**Comment by dkarrasch** [comment]
I think this is currently hopeless. The ambiguity test of `SparseArrays` themselves are ineffective, because they only test if a warning is thrown by calling `detect_ambiguities(SparseArrays, ...)`. So, `detect_ambiguities` happily returns ambiguities without throwing a warning, and the test passes. But we can't turn on the test whether the result of ambiguity detection is empty, because it won't be, because there are ambiguities with some methods from the sysimg's `SparseArrays`. Similarly, we can't `detect_ambiguities(LinearAlgebra, ...)` after `using SparseArrays`, because LinearAlgebra will use the `SparseArrays` version from the sysimg, which is proven to be ambiguity-free by PRs like this one. I don't know if using `Aqua.jl` on `SparseArrays` might help?

**Comment by dkarrasch** [comment]
Superseded by #48914. For some reason, older, open bump PRs are not closed automatically, even though I ticked that option.

**Pull request closed without merging**
