### PR TITLE
LinearAlgebra: Add bareiss det for BigInt Matrices(#40128)

### PR DESCRIPTION
**Pull request by Pramodh-G**
@stevengj  Please review.

### CODE REVIEW

**Comment by Pramodh-G** [comment]
Sorry for all the autoformatting, my editor does that by itself. If you want me to revert them, I can do so.
Please suggest ways in which this can be improved

**Comment by Pramodh-G** [comment]
Hi I think there was a change on master that is causing the merge conflicts, could anyone please help me on how to proceed here?
Thanks

**Comment by oscardssmith** [comment]
I think I fixed the merge conflict on this branch. You should `git pull` before committing more code.

**Comment by Pramodh-G** [comment]
yes, I'll be sure to do that from next time. thanks for the help @oscardssmith

**Comment by Pramodh-G** [comment]
Hi, I think the failure of checks has nothing to do with LinearAlgebra Library. Is this good for merging?

**Comment by simeonschaub** [comment]
Could you remove the auto formatting here as well?

**Comment by Pramodh-G** [comment]
Hi, Sorry for the shoddy work, It seems like I messed up my fork of julia, it feels like I have to start afresh. Please feel free to delete this PR, I'll make a new one in no time.

**Comment by oscardssmith** [comment]
No problem. learning to use git is a process. The thing to do next time is `git rebase master` instead of a merge. The difference is that a rebase will lead to only the files you changed being in the PR since it will "rewrite history".  If you wanted, you could revert the change, but if you're new to Git, it's perfectly reasonable to delete and start again. If you want to do so, just close the PR, and open a new one.

**Comment by Pramodh-G** [comment]
@oscardssmith  I already opened a new one, please check it out!

**Pull request closed without merging**
