### PR TITLE
Allow bitarray to handle shifts by a negative value.

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Rebased and fixed conflicts here: https://github.com/JuliaLang/julia/pull/18154

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19760#issuecomment-269676863) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/88d896b0db239199f97014dad2444ed5a1ba6011/6d6ed95_vs_19f81ac/report.md). cc @jrevels

**Comment by tkelman** [comment]
there is the doc issue @rfourquet mentioned, opened as https://github.com/JuliaLang/julia/issues/19767 if you don't want to get it now

**Comment by StefanKarpinski** [comment]
Any clue what the deal with the failed AppVeyor run is? Seems random and unrelated.

**Comment by StefanKarpinski** [comment]
There are a handful of apparent regressions (and one progression), but most of them seem to be unrelated and just noise, with the exception of the nullable arrays regression, which could be real and is fairly significant – 50% slow down.

**Comment by tkelman** [comment]
appveyor failure looks like #16555

**Comment by StefanKarpinski** [comment]
How about I merge this and open a performance issue for the one regression?

**Pull request merged**
