### PR TITLE
avoid file ownership requirement in touch

### PR DESCRIPTION
**Pull request by tanmaykm**
Using `futimes` and passing NULL for the `times` parameter sets the current and access file times, but does not require file ownwership (on unices).

From man page:
> If times is NULL, the access and modification times are set to the current time. The caller must be the owner of the file, have permission to write the file, or be the superuser.

ref: #28815

### CODE REVIEW

**Comment by tanmaykm** [comment]
File tests have passed. CI failure is in `LinearAlgebra/matmul` and seems unrelated.

**Comment by Keno** [comment]
This seems fine, but maybe the proper solution is to fix libuv instead?

**Comment by tanmaykm** [comment]
CI passing now (after a re-run)

**Comment by aviks** [comment]
Can this be merged now?

**Comment by JeffBezanson** [comment]
`futimes` does not seem to accept a pointer as the second argument. Am I missing something?

**Comment by tanmaykm** [comment]
It does... as per [linux](http://man7.org/linux/man-pages/man3/futimes.3.html) and [osx](https://www.unix.com/man-page/osx/2/futimes/) man pages. Doesn't it?

**Comment by JeffBezanson** [comment]
Ah, though the linux man page doesn't mention the `NULL` argument value.

**Comment by tanmaykm** [comment]
It says it behaves similar to `utimes` and `utimes` man page does mention behavior when `NULL` is passed.

**Comment by nalimilan** [comment]
I'd rather apply a temporary patch to our libuv fork than add platform-specific code in Julia.

**Comment by JeffBezanson** [comment]
I agree it's not really a bug in libuv though; it would be adding a new function there. We should probably just merge this.

**Pull request merged**
