### PR TITLE
Add coverage badge to README

### PR DESCRIPTION
**Pull request by kshyatt**
As suggested in #9493.

### CODE REVIEW

**Comment by kshyatt** [comment]
Sorry, I forgot to put [ci skip] on this!

**Comment by IainNZ** [comment]
No problem, I was thinking about the CI too!

**Comment by dhoegh** [comment]
The badge do not lead to the same site as: https://coveralls.io/r/JuliaLang/julia. Which then do show a lower and older coverage number than Julia and @kshyatt work deserves.

**Comment by ViralBShah** [comment]
I verified - the link is not doing the right thing. It takes us to some older commits. How to fix this?

**Comment by kshyatt** [comment]
I did exactly what Coveralls told me to! Grrrrr. I think there's a larger issue where the Repo Stats part of our Coveralls.io page is doing something funky.

**Comment by staticfloat** [comment]
Yes, @kshyatt is right.  It's because the commit information isn't surviving all the way through to Coveralls.  I remember having some serious headaches trying to figure out how to bully Coveralls into accepting my git commit information, looks like it's time to revisit it and figure out what's broken.

The OpenStack cluster at MIT had an emergency poweroff this morning due to coolant systems failing at CSAIL; so I'll take a look at this once the buildbots are back up.

**Comment by tkelman** [comment]
I don't have anything to add to this issue except to wholeheartedly second the sentiment behind

> lower and older coverage number than Julia and @kshyatt work deserves.

**Comment by staticfloat** [comment]
@kshyatt can you give me the exact command sequence you're using to upload to your coveralls stats?

**Comment by tkelman** [comment]
Is it expected that in the "Gather inlined test results" and "Gather non-inlined test results" steps of http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64/builds/544, that all of the `.cov` files are being Skipped?

**Comment by IainNZ** [comment]
Yep, its just because Coverage.jl does a silly thing where it walks through every file in the folder and looks for `file.cov` - so it works for the `.jl` files, but when it hits a `.cov` file it can't find a `.cov.cov` so it says "skipped".

**Comment by kshyatt** [comment]
Just a quick update, thanks to the amazing work of @staticfloat, the coverage badge is now correct!

**Comment by tkelman** [comment]
Nice work. I bet running the pkg test during the coverage run would make the numbers a bit better.

**Comment by staticfloat** [comment]
Yes, I briefly discussed the best way to do that with Tim Holy [here](https://github.com/timholy/CoverageBase.jl/issues/4), I'll write something up and see if we can't get it running tonight.  :D

**Pull request merged**
