### PR TITLE
Quick return for linspace when start == stop. Fixes #20520.

### LINKED ISSUE #20520: linspace construction failures
Specifically [this line](https://github.com/JuliaLang/julia/blob/e849169bcf8ef79bd7c1dbfb6200a5a218496ceb/test/ranges.jl#L350
) fails on 32-bit systems. The failure is an `InexactError` and goes away when linspace construction in that loop is commented out, suggesting that there's some code somewhere that does a `trunc`, `floor` or `ceil` to `Int` with a value that is too large to represent as a 32-bit integer.

### PR DESCRIPTION
**Pull request by timholy**
The old code worked in the case where the inputs are expressible as rationals, but when that fails we were getting an InexactError.

CC @StefanKarpinski.

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by timholy** [comment]
Any complaints if I resove the merge conflict and push again with a `[ci skip]`?

**Comment by StefanKarpinski** [comment]
Oh, I merged for you, sorry. Feel free to skip the CI after resolving the merge. Do run the ranges tests locally though since it's easy to make a silly mistake (syntax, etc.).

**Comment by timholy** [comment]
Looks like it's already well underway, so I'll just let it run. Anyone who notices it finish, go ahead and merge.

**Comment by martinholters** [comment]
Wow, literally just saw the merge button disappear under my mouse...

**Pull request merged**
