### PR TITLE
Document all documentable syntax

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Summarise all legal documentation syntax, what actually gets documented in each case, and suggest the preferred style when there is more than one way to document something.

### CODE REVIEW

**Comment by jakebolewski** [comment]
```julia
"""
some doc
"""
foo(...)
```

```
doc"""
some doc
""""
foo(...)
``` 

do not have the same behavior, is this documented somewhere?

**Comment by MichaelHatherly** [comment]
> do not have the same behavior, is this documented somewhere?

I can't see any difference at the moment:

```
julia> f(x) = x; g(x) = x
g (generic function with 1 method)

julia> """
       some doc
       """
       f(x)
f (generic function with 1 method)

julia> doc"""
       some doc
       """
       g(x)
g (generic function with 1 method)

julia> Main.__META__[f].meta == Main.__META__[g].meta
true

julia> Main.__META__[f].order == Main.__META__[g].order
true

julia> Main.__META__[f].main == Main.__META__[g].main
true
```

They both appear to be behaving the same way and storing equivalent things I think. Have I missed something? They definitely shouldn't have different behaviours.

(I'll update with the ``f(...)`` syntax shortly.)

**Comment by jakebolewski** [comment]
When trying to update the manual last night, in linalg/eigen.jl adding:

```julia
doc"""
    eigvals!(A; permute::Bool=true, scale::Bool=true)

Same as eigvals, but saves space by overwriting the input A (and B), instead of creating a copy.
"""
eigvals!(A; permute::Bool, scale::Bool)
```

correctly updates the manual and is correctly found by genstdlib.jl

```julia
"""
    eigvals!(A; permute::Bool=true, scale::Bool=true)

Same as eigvals, but saves space by overwriting the input A (and B), instead of creating a copy.
"""
eigvals!(A; permute::Bool, scale::Bool)
```

does not

**Comment by prcastro** [comment]
Isn't that a bug, rather than a feature worth documenting?

**Comment by MichaelHatherly** [comment]
> correctly updates the manual and is correctly found by genstdlib.jl ... does not

Fixed in #13019 I hope. ``@doc_str`` adds a ``file`` and ``module`` field to each docstring, but ``Markdown.parse`` does not, which seems to have been the problem.

**Comment by MichaelHatherly** [comment]
> Isn't that a bug

Yes, it's a bug not a feature.

**Comment by jakebolewski** [comment]
This was needed.  Great work @MichaelHatherly

**Comment by MichaelHatherly** [comment]
Thanks.

**Pull request merged**
