### PR TITLE
add logic to prefer loading modules that are already loaded

### PR DESCRIPTION
**Pull request by vtjnash**
Iterate over the list of existing loaded modules for PkgId whenever loading a new module for PkgId, so that we will use that existing build_id content if it otherwise passes the other stale_checks.

### CODE REVIEW

**Comment by vtjnash** [comment]
Tested locally with 
```
JULIA_DEPOT_PATH=testdepot ./julia -e 'using REPL'
```
then
```
JULIA_DEPOT_PATH=testdepot: ./julia -e 'Base.require_stdlib(Base.PkgId(Base.UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb"), "REPL")); using REPL; display(Base.loaded_precompiles)'
```
which shows the result is correct for both `testdepot:` (no loaded duplicates) and `testdepot` (loaded duplicates)

**Comment by Keno** [comment]
> Tested locally with

Add this to the test suite?

**Comment by topolarity** [comment]
I'm not sure we should backport this to 1.11 - feels like a relatively major change to loading to make at this point

**Comment by giordano** [comment]
Looks like this PR [broke the test revise job](https://buildkite.com/julialang/julia-master/builds/40456#0192489f-a6d3-48a5-b6e1-ac17c7dfe464/774-1108) (but it's marked to be allowed to fail)

**Comment by vtjnash** [comment]
I thought this was one of the milestone issues, or at least that is what I thought I was told offline about it

**Comment by topolarity** [comment]
This makes it more rare for `require_stdlib` to trigger the outstanding type-piracy problems we have (https://github.com/JuliaLang/StyledStrings.jl/issues/91) that lead to mis-behavior on 1.11

I don't think it's a milestone issue though because it doesn't actually solve the problem (it just makes it more unlikely)

**Comment by DilumAluthge** [comment]
@vtjnash How difficult will it be to fix the `test-revise` failures? Would it be easier to just revert this PR, and re-land it with a fix?

**Comment by vtjnash** [comment]
It is a Revise bug (unsafe access to private internals). Trying a fix here https://github.com/timholy/Revise.jl/pull/856

**Comment by IanButterworth** [comment]
I think the backport label was removed erroneously here

**Comment by KristofferC** [comment]
This commit is at least on the 1.11 branch now https://github.com/JuliaLang/julia/pull/56228/commits/a25475cb093b3a686905ae7227319332df09b567

**Comment by IanButterworth** [comment]
Thanks. Argh, maybe I'm just not approaching determining this in the right way:
- The todo list entry wasn't completed
- github was hiding the commit on the PR so ctrl-f didn't find it

I should probably just use git.

So that means this didn't fix https://github.com/JuliaLang/julia/issues/56216

**Pull request merged**
