### PR TITLE
Use iteration instead of indexing in `Threads.@threads`

### LINKED ISSUE #40704: firstindex(enumerate(...)) not defined
```
julia> firstindex(enumerate(1:3))
ERROR: MethodError: no method matching firstindex(::Base.Iterators.Enumerate{UnitRange{Int64}})
Closest candidates are:
  firstindex(::Any, ::Any) at abstractarray.jl:366
  firstindex(::Pair) at pair.jl:63
  firstindex(::AbstractChar) at char.jl:195
  ...
```

Shouldn't this be defined? The return of iterate(enumerate...) is a tuple of an index and the value of the original iterable. Shouldn't `firstindex` return the first index in that way?

I came across this because I wanted to parallelize a for loop with threads via
```
julia> for i in enumerate(2:5); @show i; end
i = (1, 2)
i = (2, 3)
i = (3, 4)
i = (4, 5)

julia> Threads.@threads for i in enumerate(2:5); @show i; end
ERROR: TaskFailedException
Stacktrace:
 [1] wait
   @ .\task.jl:317 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads .\threadingconstructs.jl:34
 [3] top-level scope
   @ .\threadingconstructs.jl:93

    nested task error: MethodError: no method matching firstindex(::Base.Iterators.Enumerate{UnitRange{Int64}})
    Closest candidates are:
      firstindex(::Any, ::Any) at abstractarray.jl:366
      firstindex(::Pair) at pair.jl:63
      firstindex(::AbstractChar) at char.jl:195
      ...
    Stacktrace:
     [1] (::var"#14#threadsfor_fun#7"{Base.Iterators.Enumerate{UnitRange{Int64}}})(onethread::Bool)
       @ Main .\threadingconstructs.jl:66
     [2] (::var"#14#threadsfor_fun#7"{Base.Iterators.Enumerate{UnitRange{Int64}}})()   
       @ Main .\threadingconstructs.jl:48

julia> 
``` 

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\gnakerst\AppData\Local\atom\app-1.56.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4
```

### PR DESCRIPTION
**Pull request by sostock**
The code created by `Threads.@threads for x = y; ...; end` currently indexes into `y`. Therefore, it does not work for iterators which do not support indexing. This PR changes that by using `Iterators.drop` and `Iterators.take` to pick the correct chunk of `y` for each thread.

Fixes #40704.

### CODE REVIEW

**Comment by simeonschaub** [comment]
This will iterate through the entire vector O(nthreads) times, which will have a large penalty. If we wanted to support `Threads.@threads` for more iterators, we would want some kind of generic API for splitting collections. There is [SplittablesBase](https://github.com/JuliaFolds/SplittablesBase.jl) which has something like this. Perhaps something like it could be moved into Base, but that would have to be well thought through.
It doesn't make much sense in my mind to try to support any kind of iterator, since this will inherently never work for stateful iterators and be very slow for Iterators where `iterate` is expensive.

**Comment by sostock** [comment]
We could use indexing for `AbstractArray`s and only iterate over the collection as a fallback for other iterators.

**Comment by tkf** [comment]
While I understand the desire to make `@threads` more usable, I strongly suggest avoiding this approach. This `Iterators.drop`-based approach incurs `O(length(input) * nthreads())` overhead which is not negligible for a large class of collections including `Iterators.map`, `Iterators.filter`, strings, hash tables, trees, lists, and so on.

SplittingBase takes a simple approach but it turned out to be very effective. Although I still want to explore better APIs for handling important non-standard cases, I believe something like this combined with loop composition based on higher-order function is a much better approach for providing extensible parallel loop infrastructure.

**Comment by Seelengrab** [comment]
I think a good solution would be to have the `@threads` macro support work stealing or lazy iteration for non-indexables. It does support switching scheduling strategy since 1.5, but only `:static` scheduling is available right now. That would also prevent redundant consumption of the given iterable (which may have side effects anyway).

**Comment by tkf** [comment]
For the class of parallel code that include `for` loops, it's [already possible](https://discourse.julialang.org/t/ann-foldsthreads-jl-a-zoo-of-pluggable-thread-based-data-parallel-execution-mechanisms/54662) to implement even continuation stealing (the "better" strategy of work-stealing) in Julia. It also already supports generic collections that implement SplittablesBase interface.

**Pull request closed without merging**
