### PR TITLE
 Add Julia port of atan2 from Openlibm and add some tests.

### PR DESCRIPTION
**Pull request by pkofod**
Not tested for performance yet.

### CODE REVIEW

**Comment by pkofod** [comment]
Does anyone have an idea what the following test failure is about?
```
    FAILURE
Error in testset statistics:
Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: return type RowVector{Float64,Array{Float64,1}} does not match inferred return type Any
  Stacktrace:
   [1] include_relative(::Module, ::String) at ./loading.jl:464
   [2] eval(::Module, ::Any) at ./boot.jl:291
   [3] checked_add at ./checked.jl:170 [inlined]
   [4] length at ./range.jl:408 [inlined]
   [5] getindex at ./array.jl:770 [inlined]
   [6] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:57
   [7] vect at ./array.jl:96 [inlined]
   [8] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:151
   [9] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:146
   [10] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:148
   [11] choosetests(::Array{String,1}) at /usr/home/julia/worker/11rel-amd64/build/test/choosetests.jl:139
  while loading /usr/home/julia/worker/11rel-amd64/build/test/statistics.jl, in expression starting on line 177
```

**Comment by fredrikekre** [comment]
#23371

**Comment by pkofod** [comment]
Travis has some test failures. They don't look nice, but I doubt they are related.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks("scalar", vs=":master")`

**Comment by ararslan** [comment]
Had to kick the server. @nanosoldier `runbenchmarks("scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23468#issuecomment-333392962) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/48048d0974b63ec47fa0e7ece0d395898df7c8c0/a9966bb_vs_e88b264/report.md). cc @ararslan

**Comment by pkofod** [comment]
Nanosoldier seems to be ok (? @simonbyrne )

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
