### PR TITLE
Force "uUeE" dateformats to return Int64 values

### PR DESCRIPTION
**Pull request by fchorney**
Attempt at addressing #31363

### CODE REVIEW

**Comment by quinnj** [comment]
I think the better fix here would be to change all the `Int` types in `DateLocale` to `Int64`. So `month_value::Dict{String, Int}` would be come `   
 `month_value::Dict{String, Int64}`. I don't think any other code would need to change since the constructors will take care of the promotion.

**Comment by fchorney** [comment]
Fair enough, that seems reasonable

**Comment by StefanKarpinski** [comment]
It's generally a good idea for all these types to have system-independent sizes. Are there any others in the Dates package that are `Int` or `UInt` that aren't tied to memory addresses?

**Comment by fchorney** [comment]
I've taken some time to look at the other values returned by any dateformat parsing, and they all seem to be Int64 after this change. I have not looked deeper into the Dates package passed that yet.

**Comment by StefanKarpinski** [comment]
Excellent. Thank you for taking a look though that!

**Review by StefanKarpinski — APPROVED** [review]

**Pull request merged**
