### PR TITLE
Update julia.appdata.xml to a new AppStream specification.

### LINKED ISSUE #27996: julia.appdata.xml uses an ancient version of the AppStream specification
```
$ appstreamcli validate contrib/julia.appdata.xml 
E - julia.appdata.xml:~:3
    The metainfo file uses an ancient version of the AppStream specification, which 
    can not be validated. Please migrate it to version 0.6 (or higher).

Validation failed: errors: 1
```

The following patch is taken from Debian's package. It makes Debian's package checker happy, but I'm not sure whether it's correct.
```patch
Purpose: lintian error due to ancient version of metadata format
Reference: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
Created-by: Mo Zhou
Last-Update: 2018-07-04
Forwarded: not yet.

diff --git a/contrib/julia.appdata.xml b/contrib/julia.appdata.xml
index 576d883..e88a844 100644
--- a/contrib/julia.appdata.xml
+++ b/contrib/julia.appdata.xml
@@ -1,9 +1,11 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!-- Copyright 2014 Paul Lange <palango@gmx.de> -->
-<application>
- <id type="desktop">julia.desktop</id>
+<component>
+ <id>org.julialang.www</id>
+ <name>Julia</name>
  <metadata_license>CC-BY-SA-3.0</metadata_license>
  <project_license>MIT and LGPL-2.1+ and GPL-2.0+</project_license>
+ <summary>high-performance programming language for technical computing</summary>
  <description>
   <p>
    Julia is a high-level, high-performance dynamic programming language for
@@ -20,9 +22,6 @@
    external packages through Julia’s built-in package manager at a rapid pace.
   </p>
  </description>
- <screenshots>
-  <screenshot type="default">https://julialang.org/images/julia-gnome.png</screenshot>
- </screenshots>
  <url type="homepage">https://julialang.org/</url>
- <updatecontact>julia-dev@googlegroups.com</updatecontact>
-</application>
+ <update_contact>julia-dev@googlegroups.com</update_contact>
+</component>
```

### PR DESCRIPTION
**Pull request by cdluminate**
closes: https://github.com/JuliaLang/julia/issues/27996

### CODE REVIEW

**Comment by ViralBShah** [comment]
cc @nalimilan

**Review by nalimilan — APPROVED** [review]
Thanks! While we're at it, I've added a `<provides/>` tag. The file passes validation tests locally.

EDIT: cancelling CI since it doesn't check that file at all.

**Comment by kshyatt** [comment]
Whoa CI failures. Should we re-run this? Or can it be merged as-is?

**Comment by nalimilan** [comment]
Yes, CI doesn't really check that file anyway. If it's OK to merge PRs at the moment, please do so.

**Pull request merged**
