### PR TITLE
fix `hash(::BigInt)` on 32 bit systems

### LINKED ISSUE #50075: hash(::BigInt) broken in 1.9 on 32-bit systems
```julia
julia> a = 12345678901234
12345678901234

julia> b = big(a)
12345678901234

julia> a == b
true

julia> hash(a) == hash(b)
false

julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 1 on 20 virtual cores
```
Presumably also broken on master.

### PR DESCRIPTION
**Pull request by oscardssmith**
Theoretically fixes https://github.com/JuliaLang/julia/issues/50075 (CI will let us know for sure).

### CODE REVIEW

**Comment by LilithHafner** [comment]
Wow you're fast!

**Comment by oscardssmith** [comment]
you're assuming that the fix is actually correct :) I am mostly just guessing.

**Comment by LilithHafner** [comment]
Hmm, yeah. On 32-bit systems the pointer in a BigInt is a UInt32 pointer, so creating a UInt64 pointer and `unsafe_load`ing from it may be broken when `x.alloc == 1`.

**Comment by oscardssmith** [comment]
Yeah. I don't think this is workable. Let's eval it out then.

**Comment by oscardssmith** [comment]
grr. The collision test fails. Any thoughts?

**Comment by LilithHafner** [comment]
The `(length(types) - 1) ^ 2` upper bound in the collision test is cute, but afaict, the comment explaining why it works is wrong (or maybe its too clever for me cc @vtjnash https://github.com/JuliaLang/julia/pull/38031). My unmerged approach when [adding BigFloat tests](https://github.com/JuliaLang/julia/pull/50067/commits/bee9e21d5181d6475bf6580b3a14c3042f34818b) is to replace it with a hardcoded bound, which is also not good.

The best approach would be to adjust BigInt and BigFloat hashing to reduce collisions, but we shouldn't hold these bugfixes for that.

**Comment by rfourquet** [comment]
Was this broken only since 1.9? Do we know what is broken in the current code for 32 bits systems?

**Comment by LilithHafner** [comment]
The following is merely speculation:

> Was this broken only since 1.9?

Unlikely

> Do we know what is broken in the current code for 32 bits systems?

I believe Int64 gets hashed in one go while BigInt gets hashed one UInt32 chunk at a time, so for numbers in the range `typemax(Int32) < x < typemax(Int64)`, BigInts and Int64s are hashed differently.

**Comment by vtjnash** [comment]
The hash range used to fold back on itself for certain types, so it is not a comment about the required guarantee but simply a statement about why it was not zero anymore and why the resulting collisions are still rare enough (and not e.g. clustered)

**Comment by oscardssmith** [comment]
This has been broken since at least https://github.com/JuliaLang/julia/pull/38031 (it goes further back, but git blame is hard to track then).

**Comment by jmkuhn** [comment]
> This has been broken since at least #38031 (it goes further back, but git blame is hard to track then).

Testing a few old 32 bit arm builds that I have, it worked in v1.4.2 and was broken by v1.5.3.

**Pull request merged**
