### PR TITLE
Fix rem/mod doc

### PR DESCRIPTION
**Pull request by yuyichao**
Unbreak Colors.jl. Not sure if/how to test......

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Thanks so much!

**Comment by tkelman** [comment]
what about this broke Colors.jl? should something be throwing a MethodError that wasn't?

**Comment by ararslan** [comment]
That was my fault. The way I did it in my PR inadvertently added a method that shouldn't have been there.

**Comment by tkelman** [comment]
can we test the "shouldn't have been there" part? what method, and what problems did it cause?

**Comment by ararslan** [comment]
Not sure. @yuyichao noted the failure and the cause, perhaps he knows.

**Comment by tkelman** [comment]
looks like it was causing an ambiguity

**Pull request merged**
