### PR TITLE
Export standard log levels from Logging stdlib.

### PR DESCRIPTION
**Pull request by fredrikekre**
Is there a reason these are not exported?

### CODE REVIEW

**Comment by c42f** [comment]
This was a conscious choice originally because these constants have quite generic names.

At this point I'm kind of neutral on this. I do agree it's kind of annoying to have to use the `Logging` prefix for these and they're certainly part of the public API.

**Comment by fredrikekre** [comment]
@nanosoldier runtests(ALL, vs = ":master")

**Comment by fredrikekre** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40980#issuecomment-851240571) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8b4cdc7_vs_b46df09/report.md). cc @maleadt

**Review by c42f — COMMENTED** [review]
Did pkgeval find any compatibility issues of note?

**Comment by fredrikekre** [comment]
No, so I updated with NEWS and tests.

**Review by c42f — APPROVED** [review]

**Pull request merged**
