### PR TITLE
Replace Val-types by singleton types in `lu` and `qr`

### LINKED ISSUE #476: lu(A, Val{false}) should be lu(A, pivot=false)
I use the unpivoted `lu` function a lot in teaching linear algebra, because its results are more easily compared to hand calculations (where you rarely permute rows), and it is continually annoying to me that you do this by passing `Val{false}` as the second argument — I feel like I'm exposing an ugly internal.   Can't we changed this to a `pivot=false` keyword?

LU factorization is a fairly expensive operation, so I am mystified by why we would care about dispatch performance here.  Surely the cost of a runtime branch is negligible?

cc @andreasnoack

### LINKED ISSUE #24144: lu(A, Val{false}) should be lu(A, pivot=false)
I use the unpivoted `lu` function a lot in teaching linear algebra, because its results are more easily compared to hand calculations (where you rarely permute rows), and it is continually annoying to me that you do this by passing `Val{false}` as the second argument — I feel like I'm exposing an ugly internal.   Can't we changed this to a `pivot=false` keyword?

LU factorization is a fairly expensive operation, so I am mystified by why we would care about dispatch performance here.  Surely the cost of a runtime branch is negligible?

cc @andreasnoack

### PR DESCRIPTION
**Pull request by dkarrasch**
This is a rebase of JuliaLang/julia#25303. The first commit doesn't change the tests functionally and thereby proves that this is non-breaking. Seems like all `@inline`s in the `qr` code are necessary for type stability. If we go for it, we'll need tests for the new argument and a NEWS announcement.

Closes JuliaLang/julia#25303, closes JuliaLang/LinearAlgebra.jl#476.

### CODE REVIEW

**Comment by simeonschaub** [comment]
Instead of forcing more aggressive inlining, it might be better to use just `@aggressive_constprop` instead, so we don't generate excessive code.

**Comment by dkarrasch** [comment]
> Instead of forcing more aggressive inlining, it might be better to use just `@aggressive_constprop` instead, so we don't generate excessive code.

I didn't know about it, I'll try that out.

**Comment by dkarrasch** [comment]
This is ready for a first rough "review". Currently, this is "just" adding new accepted keyword values. Would we actively deprecate the old `Val`-type-based arguments, or let it go and try to remember to deprecated this as we are approaching v2.0? @andreasnoack @ViralBShah @stevengj may have some thoughts here.

**Comment by ViralBShah** [comment]
Maybe we create a label - `2.0-deprecation` so that whenever we get to 2.0, we get all those things out. 

@StefanKarpinski

**Comment by StefanKarpinski** [comment]
Deprecations are already off by default, so we can make something a deprecation already. For things that we want to change before 2.0, that's what the 2.0 milestone is for. I also keep a document with a list of things (linking to issues where appropriate). That's handy because sometimes a change is too small or vague to create an issue for but we still want to remember it.

**Comment by dkarrasch** [comment]
> so we can make something a deprecation already.

I took that as an invitation to add `@deprecate` macros, but I'm getting errors when testing locally:
```julia
Got exception outside of a @test
  `qr(A::AbstractMatrix, ::Val{true}; kwargs...)` is deprecated, use `qr(A, :colnorm; kwargs...)` instead.
```
so I must have misunderstood something. Do I need to update all calls of `lu[!]` and `qr[!]` in the tests? I thought we should keep at least some tests of the current, "expected" behavior.

**Comment by dkarrasch** [comment]
I have now updated the tests and deprecated the `Val`-type-based methods.

**Comment by dkarrasch** [comment]
Tests pass, this is ready for review.

**Comment by dkarrasch** [comment]
Anyone who wants to take a look? Since the old way of calling the decomposition functions continues to work, I guess the main issue to check is whether the NEWS entry is helpful and explicit enough.

**Comment by andreasnoack** [comment]
This is generally a great change that makes it much clearer which pivoting strategy is being used. However, I'm wondering if we should use empty structs instead of symbols here since we already to structs for selecting algorithm in SVD, ref https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/stdlib/LinearAlgebra/src/LinearAlgebra.jl#L163-L165.

**Comment by dkarrasch** [comment]
That sounds like a good idea, since that no longer depends on constant propagation.

**Comment by dkarrasch** [comment]
Perhaps some input/feedback on the naming would be helpful. The `SVD` algorithms are not exported, but I chose to export the new `PivotingStrategy`s.

**Comment by andreasnoack** [comment]
> The SVD algorithms are not exported

It's actually one of the main issues with using structs: it seems excessive to export them when they are only used for dispatch in a few functions but it also feels wrong to qualify them. I think I prefer for exporting though.

I think the names are okay but I generally prefer to write out the words at the cost of some slightly longer names, i.e. something like `ColumnNorm`, `RowMaximum` (should it be `RowMaximizer`?).

**Comment by dkarrasch** [comment]
For the time being, I went with `RowMaximum`, because that's what the strategy is _based on_ (similar to `ColumnNorm`), not referring to _which pivot_ is chosen.

**Comment by dkarrasch** [comment]
Gentle bump.

**Review by andreasnoack — APPROVED** [review]

**Comment by andreasvarga** [comment]
Sorry for interferring in this discussion, but because these changes (especially those in `qr!`) heavily affect my packages [MatrixPencils](https://github.com/andreasvarga/MatrixPencils.jl) and [DescriptorSystems](https://github.com/andreasvarga/DescriptorSystems.jl), I wonder if the recent failures of tests on the nightly version have to do with these changes. And, sorry for my ignorance, are the expected benefits of these changes somewhere discussed more in depth? For example, could I hope for shorter compilation times for the affected functions?

**Comment by dkarrasch** [comment]
This PR only renames `Val{true/false}` to more verbose types, specifically targetted to either `lu` or `qr`, which is the main benefit. The old signatures remain valid, but lead to deprecation warnings, as you can see in your CI runs. The algorithms underneath have not changed at all. From a quick glance, I don't think the failures on nightly are related to this change: the errors occur in "safe distance" to the deprecation warnings, as if the `qr` call worked ok, and the error occurred in a different test later.

**Comment by dlfivefifty** [comment]
What about `cholesky`?

**Comment by dkarrasch** [comment]
I was wondering the same recently after getting lost in the lu/cholesky/qr files when I still saw some `Val`s. How would you name the `PivotingStrategy` here?

**Comment by dlfivefifty** [comment]
It's "complete pivoting"

http://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga31cdc13a7f4ad687f4aefebff870e1cc.html

I believe this is equivalent to `ColumnNorm()` but also (due to symmetry) `RowNorm()`, which is currently not defined.

(I have a need for `RowNorm()` and `ColumnMaximum()` in MatrixFactorizations.jl but can add that there)

**Comment by dlfivefifty** [comment]
Actually It pivots the largest value to the diagonal, so maybe that's `RowMaximum()`?

**Pull request merged**
