### PR TITLE
Update svd.jl

### PR DESCRIPTION
**Pull request by alanedelman**

### CODE REVIEW

**Review by kshyatt — COMMENTED** [review]
Did you run these doctests locally? I'm pretty sure you wanted `A == ...` here...

**Comment by KristofferC** [comment]
I think this works fine? Note that it is `≈` (`isapprox`) and not `=`. However, there should be spaces between the inputs like

```
julia> A = rand(4,3);

julia> U,S,V = svd(A);

julia> A ≈ U*Diagonal(S)*V'
true
```

**Comment by kshyatt** [comment]
The dangers of phone reviewing...

**Comment by simonbyrne** [comment]
Welcome @alanedelman, I see that this is your first pull request to Julia!

Would it be better to combine this example with the one below it?

**Comment by ViralBShah** [comment]
Tests failing with trailing whitespaces.

**Comment by andreasnoack** [comment]
I've fixed the doctests so they are now passing (the failure on Mac is unrelated). @alanedelman I've reorganized the paragraphs in the generalized svd documentation. The docstrings usually starts with a fairly compact description of inputs and outputs and then gives more details in the following. Please take a look.

I've also deleted the examples in the docstrings of the mutating versions and instead made references to the documentation of the non-mutating versions. This should make it easier to maintain the documentation.

**Pull request merged**
