### PR TITLE
more accurate names for identifiers that refer to `Array{Any}`s

### PR DESCRIPTION
**Pull request by JeffBezanson**
These changes were supposed to be part of #16515.

### CODE REVIEW

**Comment by nalimilan** [comment]
Sorry if I missed these when rebasing -- I guess I picked the wrong commit.

Regarding the actual change, shouldn't that function be called `jl_alloc_array_any_1d` for consistency with `jl_alloc_array_1d`?

**Comment by pabloferz** [comment]
Or `jl_alloc_array_1d` could also be changed to `jl_alloc_vec`...

**Comment by JeffBezanson** [comment]
I just went for conciseness here. I think it's clear what the name means.

**Comment by nalimilan** [comment]
Fine with me.

**Pull request merged**
