### PR TITLE
attach finalizer in `mmap` to the correct object

### LINKED ISSUE #54128: segfault when reading from mmap derived from a file that get closed(?)
Vague title because I am not really sure what is going on.

Slightly reduced from https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c356e60_vs_bd47eca/LasIO.primary.log

Pasting the following into the REPL segfaults:

```julia
using LasIO
using Mmap
using Downloads

testfile = Downloads.download("https://github.com/visr/LasIO.jl/raw/d39266994f60213ce373ed7d30b449d5400dc6c5/test/libLAS_1.2.las")

io = open(testfile)
header, pointdata = try
    read(io, UInt32)
    header = read(io, LasHeader)

    n = header.records_count
    pointtype = LasIO.pointformat(header)

    pointsize = Int(header.data_record_length)
    pointbytes = Mmap.mmap(io, Vector{UInt8}, n*pointsize, position(io))
    pointdata = LasIO.PointVector{pointtype}(pointbytes, pointsize)
    header, pointdata
finally
    close(io)
end

pointdata
```

```julia 
[41248] signal 11 (2): Segmentation fault: 11
in expression starting at none:0
unsafe_load at ./pointer.jl:153 [inlined]
unsafe_load at ./pointer.jl:153 [inlined]
peek at ./iobuffer.jl:205 [inlined]
read at ./iobuffer.jl:211 [inlined]
read at ./none:0 [inlined]
getindex at /Users/kristoffercarlsson/PkgEvalAnalysis/dev/LasIO.jl/src/point.jl:37
isassigned at ./multidimensional.jl:1601 [inlined]
isassigned at ./multidimensional.jl:1596
unknown function (ip: 0x11150c153)
alignment at ./arrayshow.jl:68
_print_matrix at ./arrayshow.jl:207
print_matrix at ./arrayshow.jl:171
print_matrix at ./arrayshow.jl:171 [inlined]
print_array at ./arrayshow.jl:358 [inlined]
show at ./arrayshow.jl:399
unknown function (ip: 0x11145c6ab)
```

Note that `pointdata` contains an `IOBuffer` wrapping the input `pointbytes` (https://github.com/visr/LasIO.jl/blob/0a9f58d78c5a68da42b467275cdeca83cc0c7450/src/point.jl#L15-L20)

Things that make it "work":

- adding a `error()` call above the `pointdata` printing
- Calling the `close(io)` outside the `finally`
- Not using `mmap` and instead using `pointbytes = read(io, n*pointsize)`

Any idea @vtjnash?

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/54128

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by KristofferC** [comment]
@vtjnash, this seems to make Mmap tests fail on Windows:

```
Mmap                                             (2) |         failed at 2024-04-23T11:08:39.378
Error During Test at C:\buildkite-agent\builds\win2k22-amdci6-5\julialang\julia-master\julia-39a8092b06\share\julia\test\testdefs.jl:24
  Got exception outside of a @test
  LoadError: SystemError: opening file "C:\\Users\\julia\\AppData\\Local\\Temp\\jl_MNqlAn4hyl": Invalid argument
  Stacktrace:
    [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
      @ Base .\error.jl:185
    [2] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Bool, append::Nothing)
      @ Base .\iostream.jl:298
    [3] open
      @ .\iostream.jl:277 [inlined]
    [4] open(fname::String, mode::String; lock::Bool)
      @ Base .\iostream.jl:361
    [5] open(fname::String, mode::String)
      @ Base .\iostream.jl:360
    [6] open(::Base.var"#470#471"{String, Tuple{}}, ::String, ::Vararg{String}; kwargs::@Kwargs{})
      @ Base .\io.jl:408
    [7] open
      @ .\io.jl:407 [inlined]
    [8] write(::String, ::String)
      @ Base .\io.jl:489
    [9] top-level scope
      @ C:\buildkite-agent\builds\win2k22-amdci6-5\julialang\julia-master\julia-39a8092b06\share\julia\stdlib\v1.12\Mmap\test\runtests.jl:106
   [10] include
```

**Comment by KristofferC** [comment]
@vtjnash, do you have an idea about the Windows CI mmap failures here?

**Comment by vtjnash** [comment]
No idea. Seems to imply it isn't getting finalized (or finalized soon enough for it to be happy) but I didn't look at what that test expects of it to see if it was reasonable looking

**Comment by KristofferC** [comment]
Still seem to error on CI.

**Comment by nhz2** [comment]
Adding a `GC.gc()` on line 105 should fix it.

**Comment by KristofferC** [comment]
That seems to have done it. Thanks for the help @nhz2

**Comment by davidanthoff** [comment]
This broke TextParse.jl (and I believe CSV.jl also). Both used calls to `finalize(array)` to deterministically release the OS resources associated with memory mapped files. Both now have workarounds, but they feel hacky as they are now depending on what is presumably internals (see e.g. https://github.com/JuliaData/CSV.jl/blob/9f95cfbd82fd0096497a26eb57998ec66758bcb6/src/file.jl#L342-L347).

**Pull request merged**
