### PR TITLE
Update for Unicode

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
It's unclear if this is needed, should at least not hurt.

**Comment by PallHaraldsson** [comment]
I get errors from two buildbots (but not the others), completely unrelated to to the one line changed (and file downloaded)...

**Comment by c42f** [comment]
It appears this is used to get the official unicode name for every character which has an existing tab completion in the REPL to make the list here: https://docs.julialang.org/en/v1/manual/unicode-input/

So while this update can't do any harm (I understand the Unicode Consortium doesn't remove characters?), it also won't have much (any?) effect until the unicode completions in the REPL are also updated to the latest list available from https://github.com/iamcal/emoji-data. It appears the `emoji-data` repo is used as an unofficial list of short emoji names for the completion strings.

**Comment by PallHaraldsson** [comment]
>So while this update can't do any harm (I understand the Unicode Consortium doesn't remove characters?)

Right I didn't notice anything deleted, by diffing I see 57 lines "deleted" but really changed (and 2306 added). Example of both:

```
< 20BF;BITCOIN SIGN;Sc;0;ET;;;;;N;;;;;
8241d8137
< 23FF;OBSERVER EYE SYMBOL;So;0;ON;;;;;N;;;;;
9637c9533
< 29A1;SPHERICAL ANGLE OPENING UP;Sm;0;ON;;;;;N;;;;;
---
> 29A1;SPHERICAL ANGLE OPENING UP;Sm;0;ON;;;;;Y;;;;;
```

**Pull request closed without merging**
