### PR TITLE
Speed up BitArray packing

### PR DESCRIPTION
**Pull request by carlobaldassi**
Addresses #13914.

### CODE REVIEW

**Comment by tkelman** [comment]
this is the kind of thing we should try and track perf for, ref https://github.com/JuliaLang/julia/issues/13893

**Comment by carlobaldassi** [comment]
I managed to speed up the whole process of BitArray packing.
Example:

```
a = rand(1:5, 300, 200);

julia> b = 2;

julia> function bcmp(n, a, b)
           for _ = 1:n
               a .!= b
           end
       end;

julia> function cmp(n, a, b)
           for _ = 1:n
               o = Array(Bool, size(a))
               for i in eachindex(a)
                   o[i] = a[i] != b
               end
            end
       end;
```

Timings:
on julia-0.4:

```
julia-0.4> @time bcmp(10_000, a, b)
  2.066846 seconds (41.74 k allocations: 113.155 MB, 0.56% gc time)

julia-0.4> @time cmp(10_000, a, b)
  0.407888 seconds (34.97 k allocations: 573.515 MB, 2.91% gc time)
```

with this PR:

```
julia-0.5> @time bcmp(10_000, a, b)
  0.675820 seconds (341.83 k allocations: 124.603 MB, 1.14% gc time)

julia-0.5> @time cmp(10_000, a, b)
  0.407919 seconds (34.30 k allocations: 573.476 MB, 3.04% gc time)
```

If everything works, and after some grace period, this could also be backported.

> this is the kind of thing we should try and track perf for, ref #13893

Yes, definitely.

**Comment by carlobaldassi** [comment]
Also, a ~2x speedup in `unsafe_setindex!` by avoiding branching.

**Comment by timholy** [comment]
Very impressive!

**Comment by JeffBezanson** [comment]
Nice!

**Pull request merged**
