### PR TITLE
Improve codegen for `Core.throw_methoderror` and `Core.current_scope`

### PR DESCRIPTION
**Pull request by topolarity**
This slightly improves our (LLVM) codegen for `Core.throw_methoderror` and `Core.current_scope`

```julia
julia> foo() = Core.current_scope()
julia> bar() = Core.throw_methoderror(+, nothing)
```

Before:
```llvm
; Function Signature: foo()
define nonnull ptr @julia_foo_2488() #0 {
top:
  %0 = call ptr @jl_get_builtin_fptr(ptr nonnull @"+Core.#current_scope#2491.jit")
  %Builtin_ret = call nonnull ptr %0(ptr nonnull @"jl_global#2492.jit", ptr null, i32 0)
  ret ptr %Builtin_ret
}
; Function Signature: bar()
define void @julia_bar_589() #0 {
top:
  %jlcallframe1 = alloca [2 x ptr], align 8
  %0 = call ptr @jl_get_builtin_fptr(ptr nonnull @"+Core.#throw_methoderror#591.jit")
  %jl_nothing = load ptr, ptr @jl_nothing, align 8
  store ptr @"jl_global#593.jit", ptr %jlcallframe1, align 8
  %1 = getelementptr inbounds ptr, ptr %jlcallframe1, i64 1
  store ptr %jl_nothing, ptr %1, align 8
  %Builtin_ret = call nonnull ptr %0(ptr nonnull @"jl_global#592.jit", ptr nonnull %jlcallframe1, i32 2)
  call void @llvm.trap()
  unreachable
}
```

After:
```llvm
; Function Signature: foo()
define nonnull ptr @julia_foo_713() #0 {
top:
  %thread_ptr = call ptr asm "movq %fs:0, $0", "=r"() #5
  %tls_ppgcstack = getelementptr inbounds i8, ptr %thread_ptr, i64 -8
  %tls_pgcstack = load ptr, ptr %tls_ppgcstack, align 8
  %current_scope = getelementptr inbounds i8, ptr %tls_pgcstack, i64 -72
  %0 = load ptr, ptr %current_scope, align 8
  ret ptr %0
}
; Function Signature: bar()
define void @julia_bar_1581() #0 {
top:
  %jlcallframe1 = alloca [2 x ptr], align 8
  %jl_nothing = load ptr, ptr @jl_nothing, align 8
  store ptr @"jl_global#1583.jit", ptr %jlcallframe1, align 8
  %0 = getelementptr inbounds ptr, ptr %jlcallframe1, i64 1
  store ptr %jl_nothing, ptr %0, align 8
  %jl_f_throw_methoderror_ret = call nonnull ptr @jl_f_throw_methoderror(ptr null, ptr nonnull %jlcallframe1, i32 2)
  call void @llvm.trap()
  unreachable
}
```

### CODE REVIEW

**Comment by topolarity** [comment]
@vtjnash Do you know why we don't just make `builtin_func_map` fully exhaustive (i.e. require all lookups to succeed)?

**Comment by vtjnash** [comment]
We certainly could. Just hasn't been done by anyone yet

**Comment by vtjnash** [comment]
We could also do better to inline that pointer, since we don't need to call `jl_get_builtin_fptr` when we could inline a load from the CodeInstance directly there

**Comment by topolarity** [comment]
Which CodeInstance?

**Comment by vtjnash** [comment]
The one in `jl_f_current_scope`

**Comment by topolarity** [comment]
Ah right - but if we make `builtin_func_map` fully-exhaustive, then we should almost never use jl_get_builtin_fptr at runtime?

**Comment by gbaraldi** [comment]
Current scope should just be codegened to lower to just getting the scope out of the task. The fact it's a builtin is slightly annoying but it's fine. https://github.com/JuliaLang/julia/blob/00739173311983479fee3f5f826e4b763872860a/src/codegen.cpp#L6789-L6793

**Comment by topolarity** [comment]
> Current scope should just be codegened to lower to just getting the scope out of the task

Done 👍

**Review by Keno — APPROVED** [review]

**Pull request merged**
