### PR TITLE
Fix `@threadcall` argument passing.

### LINKED ISSUE #17819: @threadcall fragility
There's multiple issues with `@threadcall` I've spotted while debugging a test.

1) segfaults when printing/... in called cfunction

```julia
foo(a) = (println("$a"); Cint(42))
foo_c = cfunction(foo, Cint, (Cint,))
@show       ccall(foo_c, Cint, (Cint,), 1)
@show @threadcall(foo_c, Cint, (Cint,), 1)
```

Probably by design, but the docs don't mention such a restriction.

2) argument passing botched

```julia
foo(a,b) = (Cint(a+b))
foo_c = cfunction(foo, Cint, (Cint,Cint))
@show       ccall(foo_c, Cint, (Cint,Cint), 1, 2)
@show @threadcall(foo_c, Cint, (Cint,Cint), 1, 2)       # returns 2
```

The reason is a missing `ptr` adjustment when creating the args array in `do_threadcall`:

```julia
# cconvert, root and unsafe_convert arguments
roots = Any[]
args_size = isempty(argtypes) ? 0 : sum(sizeof, argtypes)
args_arr = Array{UInt8}(args_size)
ptr = pointer(args_arr)
for (T, x) in zip(argtypes, argvals)
    y = cconvert(T, x)
    push!(roots, y)
    unsafe_store!(convert(Ptr{T}, ptr), unsafe_convert(T, y))
    ptr += sizeof(T)    # ADDED
end
```

3) example 2 often deadlocks

When debugging 2) by adding some print statements to `do_threadcall`, Julia easily locked up. Not sure whether or not this is expected, but I thought I'd mention it anyway.

```julia
import Base: do_threadcall

import Base: cconvert, unsafe_convert,
             acquire, threadcall_restrictor,
             thread_notifiers, c_notify_fun, release

function do_threadcall(wrapper::Function, rettype::Type, argtypes::Vector, argvals::Vector)
    # generate function pointer
    fun_ptr = cfunction(wrapper, Int, (Ptr{Void}, Ptr{Void}))

    # cconvert, root and unsafe_convert arguments
    roots = Any[]
    args_size = isempty(argtypes) ? 0 : sum(sizeof, argtypes)
    args_arr = Array{UInt8}(args_size)
    ptr = pointer(args_arr)
    for (T, x) in zip(argtypes, argvals)
        y = cconvert(T, x)
        push!(roots, y)
        unsafe_store!(convert(Ptr{T}, ptr), unsafe_convert(T, y))
        ptr += sizeof(T)    # ADDED
    end

    # create return buffer
    ret_arr = Array{UInt8}(sizeof(rettype))

    # wait for a worker thread to be available
    acquire(threadcall_restrictor)
    idx = findfirst(isnull, thread_notifiers)
    thread_notifiers[idx] = Nullable{Condition}(Condition())

    # queue up the work to be done
    println("queue work")
    ccall(:jl_queue_work, Void,
        (Ptr{Void}, Ptr{UInt8}, Ptr{UInt8}, Ptr{Void}, Cint),
        fun_ptr, args_arr, ret_arr, c_notify_fun, idx)

    # wait for a result & return it
    println("wait for it")
    wait(get(thread_notifiers[idx]))
    thread_notifiers[idx] = Nullable{Condition}()
    release(threadcall_restrictor)

    unsafe_load(convert(Ptr{rettype}, pointer(ret_arr)))
end


using Base.Test

foo(a,b) = (Cint(a+b))
foo_c = cfunction(foo, Cint, (Cint,Cint))
@show       ccall(foo_c, Cint, (Cint,Cint), 1, 2)
@show @threadcall(foo_c, Cint, (Cint,Cint), 1, 2)
```

Tested on latest master.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes #17819. Also document not being allowed to call back into Julia.

### CODE REVIEW

**Comment by yuyichao** [comment]
The requirement is basically https://github.com/JuliaLang/julia/issues/17573, do we have that documented already?

**Comment by kshyatt** [comment]
I've restarted the OSX build which seems to have failed for other reasons. If that passes, is this PR good to go?

**Comment by tkelman** [comment]
when you restart a travis build, please back up the log to a gist first. travis overwrites logs when you restart.

**Comment by StefanKarpinski** [comment]
What even is the point of these OS X builds? Can we merge this?

**Comment by StefanKarpinski** [comment]
@yuyichao: even though that's the underlying cause of this restriction, it doesn't hurt to mention in the docstring for `@threadcall` too.

**Comment by kshyatt** [comment]
>when you restart a travis build, please back up the log to a gist first. travis overwrites logs when you restart.

Apologies, will do next time.

**Comment by maleadt** [comment]
Yeah, this should be good to go. I had restarted the OS X bot already (to no avail), but forgot to mention it.

**Comment by yuyichao** [comment]
@StefanKarpinski I'm only asking `do we have that documented already?`

**Comment by tkelman** [comment]
when something persistently fails, look into the reasons next time

**Comment by maleadt** [comment]
I did, and even though I should have spotted the `ccall` failure, the logs always ended in:
```
ErrorException("could not load library "libopenblas"
dlopen(libopenblas.dylib, 1): image not found")
	From worker 8:	     * examples              in  33.75 seconds, maxrss  474.41 MB
The job exceeded the maximum time limit for jobs, and has been terminated.
```
So I assumed the failure to be unrelated (as it often happens)... Will be more careful next time.

**Pull request merged**
