### PR TITLE
Update usage for build_sysimg.jl

### PR DESCRIPTION
**Pull request by iamed2**
Just ended up having to make some 1.0 updates to the code and add a Makefile target so it's present in the documented directory when Julia is built.

### CODE REVIEW

**Comment by iamed2** [comment]
Note: building sysimgs is still broken.

**Comment by ViralBShah** [comment]
I wonder if we can get rid of this file and have all the focus on PackageCompiler.jl. This was a stopgap file until something more serious existed. Or alternately, bring PackageCompiler into this repo and make it first class.

**Comment by iamed2** [comment]
It's not clear to me how to replicate this functionality with PackageCompiler. Maybe `compile_package("blahblahrandom", "userimg.jl")`? 

In any case no one has paid any attention to PackageCompiler either, as it doesn't build on 1.0.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/27629

**Comment by omus** [comment]
`contrib/build_sysimg.jl` was removed in #30225

**Pull request closed without merging**
