### PR TITLE
Mention JULIA_PROJECT env variable

### PR DESCRIPTION
**Pull request by jbrea**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
This looks correct to me, but I think we could automate it by adding a `--project` option to worker processes if `Base.HOME_PROJECT` is non-default.

**Comment by oxinabox** [comment]
Cf https://github.com/JuliaLang/julia/issues/28781

**Comment by ViralBShah** [comment]
I feel like more explanation is perhaps required here, if we want to get this in. Otherwise, we may want to close.

**Comment by vtjnash** [comment]
Yeah, I think we need to solve https://github.com/JuliaLang/julia/issues/28781 first. This won't work on clusters, for example.

**Pull request closed without merging**
