### PR TITLE
Fix #16667 for deepcopy on BigFloat/BigInt causing segfaults

### LINKED ISSUE #16667: deepcopy of BigFloat kills REPL
Both on 0.4 and 0.5:
```
/tmp >> julia5
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4359 (2016-05-27 08:02 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e11ff35* (3 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> y = deepcopy(BigFloat[1, 2])
2-element Array{BigFloat,1}:
/home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/get_str.c:153: MPFR assertion failed: size_s1 >= m

signal (6): Aborted
while loading no file, in expression starting on line 0
unknown function (ip: 0x7fdc3b909294)
unknown function (ip: 0x7fdc3b90a6d9)
mpfr_assert_fail at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/mpfr-gmp.c:305
mpfr_get_str_aux at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/get_str.c:153
mpfr_get_str at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/get_str.c:2518
regular_eg at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/vasprintf.c:1082
partition_number at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/vasprintf.c:1640
mpfr_snprintf at /home/mauro/julia/julialang_upstream/deps/srccache/mpfr-3.1.3/src/printf.c:169
string at ./mpfr.jl:857
show at ./mpfr.jl:868
unknown function (ip: 0x7fda363020a6)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
jl_apply at /home/mauro/julia/julialang_upstream/src/julia.h:1388
#sprint#131 at ./strings/io.jl:36
#sprint#131 at ./strings/io.jl:36
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
jl_apply at /home/mauro/julia/julialang_upstream/src/julia.h:1388
#sprint at ./null:0
alignment at ./show.jl:1157
alignment at ./show.jl:1195
unknown function (ip: 0x7fda368bd64e)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
print_matrix at ./show.jl:1316
print_matrix at ./show.jl:1294
unknown function (ip: 0x7fda368c00b9)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
jl_apply at /home/mauro/julia/julialang_upstream/src/julia.h:1388
showarray at ./show.jl:1501
show at ./replutil.jl:4
unknown function (ip: 0x7fda368d80bd)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
display at ./REPL.jl:114
unknown function (ip: 0x7fda368e05d6)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
display at ./REPL.jl:117
unknown function (ip: 0x7fda368e4176)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
display at ./multimedia.jl:153
unknown function (ip: 0x7fda368e6609)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
print_response at ./REPL.jl:134
unknown function (ip: 0x7fda368e8408)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
print_response at ./REPL.jl:121
unknown function (ip: 0x7fda368ea148)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
#18 at ./REPL.jl:630
unknown function (ip: 0x7fda3690284c)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
run_interface at ./LineEdit.jl:1570
unknown function (ip: 0x7fdc3862caca)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
run_frontend at ./REPL.jl:881
run_repl at ./REPL.jl:166
unknown function (ip: 0x7fdc3daba19d)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
_start at ./client.jl:364
unknown function (ip: 0x7fdc3865b994)
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:88
unknown function (ip: 0x401bf5)
unknown function (ip: 0x40167a)
unknown function (ip: 0x7fdc3b8f6740)
unknown function (ip: 0x4016c8)
Allocations: 2688926 (Pool: 2687706; Big: 1220); GC: 4
zsh: abort (core dumped)  julia5
```

However, below example behaves differently. On 0.5:
```
julia> y = deepcopy(BigFloat[1, 2]);

julia> y[2]
2.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> y[3]
ERROR: BoundsError: attempt to access 2-element Array{BigFloat,1} at index [3]
 in getindex(::Array{BigFloat,1}, ::Int64) at ./array.jl:311
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
on 0.4:
```
julia> y = deepcopy(BigFloat[1, 2]);

julia> y[2]
2.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> y[3]
get_str.c:153: MPFR assertion failed: size_s1 >= m
... (same error as above)
```

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Fix proposed by @ScottPJones.

### CODE REVIEW

**Comment by yuyichao** [comment]
This means that if the old one is finalized the new one is too, which is not what it is supposed to do.

**Comment by StefanKarpinski** [comment]
I'm not advocating for this, just opening it since SPJ can't.

**Comment by yuyichao** [comment]
And just to be clear, I mean calling `finalize` explicitly.

**Comment by JeffBezanson** [comment]
Maybe we should just merge this. Fixing possible memory corruption is always good even if the fix isn't comprehensive.

**Comment by JeffBezanson** [comment]
Bump. Merge?

**Comment by StefanKarpinski** [comment]
@yuyichao: you expressed concerns/objections here; please follow up so we can decide to merge or not.

**Comment by yuyichao** [comment]
I'm fine with merging an incorrect and incomplete workaround of the issue if we just want to get rid of the segfault.

**Comment by StefanKarpinski** [comment]
We always want to get rid of segfaults. Please merge this and open an issue documenting what is wrong with this fix and what needs to be done better – in whatever order you see fit.

**Pull request closed without merging**
