### PR TITLE
fix jl_gc_realloc_string size miscomputation

### LINKED ISSUE #22021: add test for: Problem with `join`
I don't have a MWE, but 

```julia
s=String["\"\"\"\n     non_max_suppression(boxes, scores, max_output_size; iou_threshold=nothing)\n\nGreedily selects a subset of bounding boxes in descending order of score,\n\npruning away boxes that have high intersection-over-union (IOU) overlap\nwith previously selected boxes.  Bounding boxes are supplied as\n[y1, x1, y2, x2], where (y1, x1) and (y2, x2) are the coordinates of any\ndiagonal pair of box corners and the coordinates can be provided as normalized\n(i.e., lying in the interval [0, 1]) or absolute.  Note that this algorithm\nis agnostic to where the origin is in the coordinate system.  Note that this\nalgorithm is invariant to orthogonal transformations and translations\nof the coordinate system; thus translating or reflections of the coordinate\nsystem result in the same boxes being selected by the algorithm.\n\nThe output of this operation is a set of integers indexing into the input\ncollection of bounding boxes representing the selected boxes.  The bounding\nbox coordinates corresponding to the selected indices can then be obtained\nusing the `tf.gather operation`.  For example:\n\n  selected_indices = tf.image.non_max_suppression(\n      boxes, scores, max_output_size, iou_threshold)\n  selected_boxes = tf.gather(boxes, selected_indices)\n\"\"\"", "    tf.@op function non_max_suppression(v13566, v13567, v13568; name=nothing, iou_threshold=nothing) ", "            local desc ", "            tf.with_op_name((()->begin  ", "                        desc = tf.NodeDescription(\"NonMaxSuppression\") ", "                        begin  ", "                            begin  ", "                                v13566 = convert(TensorFlow.Tensor{Float32}, v13566) ", "                                begin  ", "                                end", "                            end", "                            begin  ", "                                v13567 = convert(TensorFlow.Tensor{Float32}, v13567) ", "                                begin  ", "                                end", "                            end", "                            begin  ", "                                v13568 = convert(TensorFlow.Tensor{Int32}, v13568) ", "                                begin  ", "                                end", "                            end", "                        end ", "                        begin  ", "                            begin  ", "                                tf.add_input(desc, v13566)", "                            end", "                            begin  ", "                                tf.add_input(desc, v13567)", "                            end", "                            begin  ", "                                tf.add_input(desc, v13568)", "                            end", "                        end ", "                        begin  ", "                            begin  ", "                                if iou_threshold !== nothing ", "                                    desc[\"iou_threshold\"] = Base.identity(iou_threshold)", "                                end", "                            end", "                        end", "                    end), name, \"NonMaxSuppression\") ", "            tf.Tensor(tf.Operation(desc))", "        end"]

print(join(s, "\n"))
```

outputs a non-deterministic string that has several seemingly random codepoints inserted in it.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #22021

### CODE REVIEW

**Comment by WestleyArgentum** [comment]
+10000 Works locally here!

**Review by yuyichao — APPROVED** [review]
Note that this actually doesn't have any performance advantage, only smaller allocation count since we count realloc differently than free and alloc, even though the latter is actually what's happening....

**Comment by alyst** [comment]
Would be nice to add the test for the bug.

**Comment by tkelman** [comment]
#22196 opened to add a test

**Pull request merged**
