### PR TITLE
Do not use `widen` for 128-bit ints in `MultiplicativeInverses`

### PR DESCRIPTION
**Pull request by sumiya11**
Hello! This PR improves `MultiplicativeInverses` for `Int128` and `UInt128`. PR consists of 3 tiny points:

- Previously, division with multiplicative inverses used `widen`. It widened 128-bit ints to `BigInt`, which hindered performance. The solution in this PR is to replace `widen` with higher half multiplication for `Int128` and `UInt128`.
```julia
# 1.8.2
using BenchmarkTools
a, b = rand(UInt128), rand(UInt128)
d = Base.MultiplicativeInverses.UnsignedMultiplicativeInverse(b)

@btime div($a, $d)
  645.455 ns (12 allocations: 216 bytes)
```

```julia
# this pr
using BenchmarkTools
a, b = rand(UInt128), rand(UInt128)
d = Base.MultiplicativeInverses.UnsignedMultiplicativeInverse(b)

@btime div($a, $d)
  6.800 ns (0 allocations: 0 bytes)
```

- Added tests for `MultiplicativeInverses` for all bit integer types;
- Draw attention to the fact that signed division with `MultiplicativeInverses` does not throw when the result overflows (see tests)

As for the latter, it's alright with me, but I think it would be good to mention this fact somewhere

Also, I've coded the higher half mult. from scratch, so let me know if there were functions for this in Base already 😊

### CODE REVIEW

**Comment by oscardssmith** [comment]
This is a really nice improvement! I think we should consider making `mulhi` an exported function (e.g. I wouldn't mind using it in `Primes.jl`).

**Comment by oscardssmith** [comment]
Also, do you happen to know if there's an efficient way to compute `a*b%n` for `Int128` without widening to `BigInt`?

**Comment by sumiya11** [comment]
> Also, do you happen to know if there's an efficient way to compute a*b%n for Int128 without widening to BigInt?

Nope :(

>  I think we should consider making mulhi an exported function (e.g. I wouldn't mind using it in Primes.jl).

Sounds like a good idea. I would also use it somewhere in fast modular arithmetic

**Comment by sumiya11** [comment]
ping !

**Comment by oscardssmith** [comment]
Needs a rebase but other than that, I think it's ready.

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
I just did the rebase and will merge when tests pass.

**Pull request merged**
