### PR TITLE
move out Profile from the sysimage

### PR DESCRIPTION
**Pull request by KristofferC**
Loads fast anyway (edit: a bit slower when adding the precompile stuff):

```julia
julia> @time using Profile
  0.008181 seconds (13.36 k allocations: 900.847 KiB)
```

### CODE REVIEW

**Comment by KristofferC** [comment]
Why does

https://github.com/JuliaLang/julia/blob/db7971f49912d1abba703345ca6eb43249607f32/contrib/generate_precompile.jl#L240

have to run in the REPL?

**Comment by IanButterworth** [comment]
I guess it doesn't.

**Comment by KristofferC** [comment]
Need to figure out how this will work with the hotkeys for profiling a running application.

**Comment by IanButterworth** [comment]
Ok, I found and pushed an alternative fix which is to move the listener into Base and load Profile there when needed

**Comment by IanButterworth** [comment]
I'm still hitting precompilation 
```
julia> using Profile
[ Info: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]

```

**Comment by KristofferC** [comment]
> I'm still hitting precompilation

It seemed to work for me.

```
julia> ENV["JULIA_DEBUG"] = "loading";

julia> using Profile
┌ Debug: Rejecting cache file /Users/kristoffercarlsson/.julia/compiled/v1.10/Profile/nGhxz_pvFUp.ji for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:2724
┌ Debug: Loading object cache file /Users/kristoffercarlsson/.julia/compiled/v1.10/Profile/nGhxz_ggTXk.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
```

These files were created by the pkgimage builder make step.

**Comment by IanButterworth** [comment]
I didn't cleanall before build. It could be a make issue

**Comment by IanButterworth** [comment]
Wait, but neither of those cache files are in your julia dir, they're in the Depot. Shouldn't they be bundled with Julia?

**Comment by KristofferC** [comment]
I think only when you are making a release they get bundled by setting the depot. But not sure..

**Comment by IanButterworth** [comment]
After a cleanall build
```
julia> using Profile
┌ Debug: Rejecting cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_wG2DL.ji because module Core [top-level] is already loaded and incompatible.
└ @ Base loading.jl:2779
[ Info: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
┌ Debug: Loading object cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_wG2DL.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
```

Also, all of the `stdlib/*.release.image` files are zero bytes. Is that expected?

This is intel MacOS if that's relevant

cc. @vchuravy

**Comment by vchuravy** [comment]
> Also, all of the stdlib/*.release.image files are zero bytes. Is that expected?

These are marker files. It's a make technique when you don't know the output file of a rule. 

I set JULIA_DEPOT_PATH := `$build_prefix/share/julia`. Can you check if it contains the files you expected? That should be the same as `Sys.STDLIB`.

**Comment by IanButterworth** [comment]
Great. That fixed it
```
julia> using Profile
┌ Debug: Rejecting cache file /Users/ian/Documents/GitHub/julia/usr/share/julia/compiled/v1.10/Profile/nGhxz_rikHs.ji for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:2724
┌ Debug: Loading object cache file /Users/ian/Documents/GitHub/julia/usr/share/julia/compiled/v1.10/Profile/nGhxz_KZhni.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
```

Very minor but perhaps the `check_bounds = 0` image should be built last so it has the latest mtime and is tried first?

**Comment by IanButterworth** [comment]
Something's not quite right, perhaps with the make setup?

After the last commit and a `make cleanall` then `make` I get

```
julia> using Profile
┌ Debug: Rejecting cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_wG2DL.ji because module Core [top-level] is already loaded and incompatible.
└ @ Base loading.jl:2779
[ Info: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
┌ Debug: Loading object cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_wG2DL.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
```

So it's not even trying  to find cachefiles in `/Users/ian/Documents/GitHub/julia/usr/share/julia/compiled`

**Comment by vchuravy** [comment]
That seems right? We start at the lowest depot and then go up from there? What happens if you remove `compiled/Profile`?

**Comment by IanButterworth** [comment]
Oh.. so if it finds something it can't use in a depots, it doesn't search in deeper depots?

**Comment by IanButterworth** [comment]
That didn't work
```
julia> using Profile
[ Info: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
┌ Debug: Loading object cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_wG2DL.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010

julia> Base.DEPOT_PATH
3-element Vector{String}:
 "/Users/ian/.julia"
 "/Users/ian/Documents/GitHub/julia/usr/local/share/julia"
 "/Users/ian/Documents/GitHub/julia/usr/share/julia"
```

**Comment by IanButterworth** [comment]
Fixing that missing comma didn't fix it
```
% make cleanall
...
% make -j6
...
Outputting sysimage file...
Output ──────  60.238698 seconds
    LINK usr/lib/julia/sys.dylib
    JULIA stdlib/SparseArrays.release.image
    JULIA stdlib/DelimitedFiles.release.image
    JULIA stdlib/DelimitedFiles.release.image
    JULIA stdlib/SparseArrays.release.image

% ls /Users/ian/Documents/GitHub/julia/usr/share/julia/compiled/v1.10
DelimitedFiles	SparseArrays
```

**Comment by vchuravy** [comment]
Looking at the artifiact from one of the build jobs:

image

**Review by IanButterworth — APPROVED** [review]

**Comment by IanButterworth** [comment]
Works well for me now. The ctrl-t profile prints quickly

**Comment by vchuravy** [comment]
Good to go? Or should I move out the Bugfixes into a separate PR?

**Comment by KristofferC** [comment]
> Or should I move out the Bugfixes into a separate PR?

Either that or at least fixup the commits a bit maybe?

**Comment by IanButterworth** [comment]
I reran the MacOS jobs and they failed again. I thought it might look like the spawned processes were each trying to precompile? Or is that an existing issue?

**Comment by IanButterworth** [comment]
Any idea what's going on here on MacOS @vchuravy ? I can't reproduce via `Base.runtests("threads")` locally.

During https://github.com/IanButterworth/julia/blob/f65df74f4d53ccba7db271e36d8b472ed81c0a13/test/threads.jl#L280
```
  | ┌ Debug: Rejecting cache file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_1C6hv.ji for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] since the flags are mismatched
  | │   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
  | │   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
  | └ @ Base loading.jl:2724
  | ┌ Debug: Skipping mtime check for file /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Profile.jl used by /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_Ntg4d.ji, since it is a stdlib
  | └ @ Base loading.jl:2829
  | ┌ Debug: Skipping mtime check for file /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Allocs.jl used by /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_Ntg4d.ji, since it is a stdlib
  | └ @ Base loading.jl:2829
  | ┌ Debug: Skipping mtime check for file /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/precompile.jl used by /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_Ntg4d.ji, since it is a stdlib
  | └ @ Base loading.jl:2829
  | ┌ Debug: Rejecting cache file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_Ntg4d.ji because /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_Ntg4d.dylib has an invalid checksum
  | └ @ Base loading.jl:2856
  | ┌ Debug: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
  | └ @ Base loading.jl:2173
  | ERROR: LoadError: IOError: mkdir("/Users/julia/.julia/compiled/v1.10/Profile"; mode=0o777): operation not permitted (EPERM)
```

**Comment by KristofferC** [comment]
A difference  s locally running the tests is that on CI the julia executable that runs the tests are downloaded from the builder which is on a different machine. So what happens if you also download that artifact from. Buildkite and run the tests from there?

**Comment by IanButterworth** [comment]
Ok yeah that reproduces `has an invalid checksum`, although it ultimately succeeds. 
Perhaps the test bots don't have write access to the usual depot location? but that seems weird..

```
┌ Debug: Rejecting cache file /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_pQJuF.ji for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:2724
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Profile.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Allocs.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/precompile.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Rejecting cache file /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji because /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.dylib has an invalid checksum
└ @ Base loading.jl:2856
┌ Debug: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:2173
┌ Debug: Loading object cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_lj9PN.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
```

**Comment by KristofferC** [comment]
I think that has been the case for quite a while. So what's included in that checksum that is not valid anymore? Absolute paths?

**Comment by IanButterworth** [comment]
Isn't the checksum just a file checksum, and I don't believe cache files can change without being recreated? So could this be a tar compress/extract issue?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/blob/ceafd6cad9a66e290aece75a62ba7733e03ba58d/base/loading.jl#L2855-L2858

https://github.com/JuliaLang/julia/blob/ceafd6cad9a66e290aece75a62ba7733e03ba58d/base/loading.jl#L2315-L2321

Yes, it indeed just seems like a (crc) checksum.

**Comment by KristofferC** [comment]
What does

```julia
julia> io = open("share/julia/compiled/v1.10/Profile/nGhxz_VorsS.ji");

julia> Base.isvalid_pkgimage_crc(io, "share/julia/compiled/v1.10/Profile/nGhxz_VorsS.so")
true
```

say when downloading the mac artifact?

**Comment by IanButterworth** [comment]
@KristofferC 
```
julia> io = open("share/julia/compiled/v1.10/Profile/nGhxz_pQJuF.ji");

julia> Base.isvalid_pkgimage_crc(io, "share/julia/compiled/v1.10/Profile/nGhxz_pQJuF.dylib")
false
```

**Comment by IanButterworth** [comment]
The files don't appear to be modified locally. This is after a fresh extract just now. mtimes are yesterday, so the tar appears to be maintaining mtime.

```
ian@IanMBP julia-f65df74f4d % ls -lT share/julia/compiled/v1.10/Profile                           
total 14776
-rwxr-xr-x@ 1 ian  staff  3728224 Mar 29 10:22:10 2023 nGhxz_pQJuF.dylib
drwxr-xr-x@ 3 ian  staff       96 Mar 29 10:22:06 2023 nGhxz_pQJuF.dylib.dSYM
-rw-r--r--@ 1 ian  staff    58898 Mar 29 10:22:06 2023 nGhxz_pQJuF.ji
-rwxr-xr-x@ 1 ian  staff  3708096 Mar 29 10:22:10 2023 nGhxz_x4TlO.dylib
drwxr-xr-x@ 3 ian  staff       96 Mar 29 10:22:06 2023 nGhxz_x4TlO.dylib.dSYM
-rw-r--r--@ 1 ian  staff    58898 Mar 29 10:22:06 2023 nGhxz_x4TlO.ji
ian@IanMBP julia-f65df74f4d % JULIA_DEBUG=loading ./bin/julia --startup-file=no -e "using Profile"
┌ Debug: Rejecting cache file /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_pQJuF.ji for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:2724
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Profile.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/Allocs.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Skipping mtime check for file /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/usr/share/julia/stdlib/v1.10/Profile/src/precompile.jl used by /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji, since it is a stdlib
└ @ Base loading.jl:2829
┌ Debug: Rejecting cache file /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.ji because /Users/ian/Downloads/julia-f65df74f4d/share/julia/compiled/v1.10/Profile/nGhxz_x4TlO.dylib has an invalid checksum
└ @ Base loading.jl:2856
┌ Debug: Precompiling Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:2173
┌ Debug: Loading object cache file /Users/ian/.julia/compiled/v1.10/Profile/nGhxz_lj9PN.dylib for Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79]
└ @ Base loading.jl:1010
ian@IanMBP julia-f65df74f4d % ls -lT share/julia/compiled/v1.10/Profile                           
total 14776
-rwxr-xr-x@ 1 ian  staff  3728224 Mar 29 10:22:10 2023 nGhxz_pQJuF.dylib
drwxr-xr-x@ 3 ian  staff       96 Mar 29 10:22:06 2023 nGhxz_pQJuF.dylib.dSYM
-rw-r--r--@ 1 ian  staff    58898 Mar 29 10:22:06 2023 nGhxz_pQJuF.ji
-rwxr-xr-x@ 1 ian  staff  3708096 Mar 29 10:22:10 2023 nGhxz_x4TlO.dylib
drwxr-xr-x@ 3 ian  staff       96 Mar 29 10:22:06 2023 nGhxz_x4TlO.dylib.dSYM
-rw-r--r--@ 1 ian  staff    58898 Mar 29 10:22:06 2023 nGhxz_x4TlO.ji
```

**Comment by gbaraldi** [comment]
Maybe the .dSYM creation does something here?

**Comment by IanButterworth** [comment]
Btw, the same checksum failure also happens for the other non-sysimage stdlibs like SparseArrays and they end up being re-precompiled

**Comment by IanButterworth** [comment]
Ok, so as expected ignoring the checksum failure for pkgimage stdlibs on macos works, so the files are good, just changed somehow.

How can we debug this further?

**Comment by staticfloat** [comment]
> @staticfloat is it known that codesigning modifies dylibs?

Yes, that's the whole point of codesigning; to modify the dylibs by adding a cryptographic signature to them.  I thought the `.dylib` files would have a hash of the `.ji` files, not the other way around.  Aren't the `.dylib` files created after the `.ji` files?

**Comment by vchuravy** [comment]
The `ji` contains very little information that the dylibs are dependent on, but we use the `ji` for quick rejection of cachefiles so we want to be able to detect corruption before we go to load the dylib  (which we often can't unload)

**Comment by IanButterworth** [comment]
> Yes, that's the whole point of codesigning

I had thought codesigning saved its information elsewhere

**Comment by staticfloat** [comment]
I see.  Then yes, we need a convenient way to update the checksums inside of the `.ji` files.

**Comment by IanButterworth** [comment]
Now that https://github.com/JuliaLang/julia/pull/48545 is merged, this should _just work_.

Codesigning will still happen for .dmg distribution but that happens after tests and will be handled here https://github.com/JuliaCI/julia-buildkite/pull/292

**Comment by IanButterworth** [comment]
> Now that https://github.com/JuliaLang/julia/pull/48545 is merged, this should just work.

That was wrong, it needed https://github.com/JuliaCI/julia-buildkite/pull/292 which is now merged, so I updated here

**Review by IanButterworth — APPROVED** [review]
Should be good to go now

**Review by staticfloat — APPROVED** [review]

**Pull request merged**
