### PR TITLE
Use official LLVM 3.7.1 sources

### PR DESCRIPTION
**Pull request by tkelman**
And remove 3.5.x and 3.6.x checksums, I don't think we're encouraging anyone to use those versions.

I compared the tarballs Keno made vs these with `diff -r`, the only differences were in autogenerated svn info comments, empty files, and some generated test content (maybe not cleaned properly from a past build).

### CODE REVIEW

**Comment by eschnett** [comment]
`Make.ppc` wants to use LLVM 3.6.0.

There are also patches for older LLVM versions; shouldn't they be removed as well?

**Comment by tkelman** [comment]
The patches still fix bugs so I think it might be worth leaving those in for a little longer, at least until 3.7 has been working solidly on master for some time. Good call on powerpc, forgot about that. @vtjnash have you tested powerpc with 3.7?

**Comment by eschnett** [comment]
If you still want to support building the older versions, then why remove the checksums? Either an LLVM version is supported or not; partially removing support seems a strange thing to do.

**Comment by tkelman** [comment]
Just cleaning up files that only serve for download verification purposes. We've been partially supporting various LLVM versions for years.

**Comment by tkelman** [comment]
The only people who should have any need to build against llvm 3.5 or 3.6 are doing so from distributions where they won't be downloading or building llvm through our build system. So removing the old patches probably makes more sense since the test failures would be pretty obvious.

**Comment by Keno** [comment]
I would leave the patches in for now. People might want to build julia with older version of LLVM, e.g. to run their experimental pass written against a specific version of LLVM. I don't think having the patches here does any harm until we do remove any left over support in the code. I'm fine with removing the checksums though.

**Comment by vtjnash** [comment]
lgtm

**Comment by tkelman** [comment]
Oops. I think both those 3.6.0 patches were included in 3.6.1.

**Comment by Keno** [comment]
Ok, in that case I don't mind.

**Comment by ViralBShah** [comment]
We should probably move Make.powerpc into Make.inc or into contrib.

**Pull request merged**
