### PR TITLE
fix #29269, type intersection bug in union parameters with typevars

### LINKED ISSUE #25752: type intersection bug in `Ref{Union{Int,T}} where T`
Difficult to tell if this is a duplicate of some existing subtyping issue, but it's important:

```
julia> typeintersect(Base.RefValue, Ref{Union{Int,T}} where T)
Union{}
```

The answer should be (ideally) `RefValue{Union{Int,T}} where T`.

### LINKED ISSUE #29269: Crash on overloading map on parametric struct with two Unions
The following crashes in 0.7 and 1.0. I cannot reproduce this without parametric types or without at least two Unions in the struct.

```julia
struct Test{T}
    A::Array{Union{Missing, T},1}
    x::Union{Nothing, Int}
end

Base.map(f, t::Test) = Test(map(f, t.A), 1)

t = Test([missing, 1], 1)

Test(map(x->x, t.A), 1)  # works
map(x->x, t)  # crash
```

Versioninfo:
```julia
versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

The crash message:
```julia
Unreachable reached at 0x11ad423a4

signal (4): Illegal instruction: 4
in expression starting at /Users/epta/.julia/v0.7/GeoRaster/crash.jl:12
map at /Users/epta/.julia/v0.7/GeoRaster/crash.jl:7
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x11492a85f)
unknown function (ip: 0x6)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
_start at ./client.jl:432
true_main at /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 581374 (Pool: 581270; Big: 104); GC: 0
[1]    18287 illegal hardware instruction  /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia crash.jl
```

Code_typed:
```julia
print(@code_typed map(x->x, t))
CodeInfo(
7 1 ─ %1 = (Base.getfield)(t, :A)::Array{Union{Missing, Int64},1}
  │   %2 = %new(Generator{Array{Union{Missing, Int64},1},##5#6}, ##5#6(), %1)::Generator{Array{Union{Missing, Int64},1},##5#6}
  │   %3 = invoke Base._collect(%1::Array{Union{Missing, Int64},1}, %2::Base.Generator{Array{Union{Missing, Int64},1},getfield(Main, Symbol("##5#6"))}, $(QuoteNode(Base.EltypeUnknown()))::Base.EltypeUnknown, $(QuoteNode(Base.HasShape{1}()))::Base.HasShape{1})::Array
  │        (Main.Test)(%3, 1)::Union{}
  │        $(Expr(:unreachable))::Union{}
  └──      $(Expr(:unreachable))::Union{}
) => Union{}%
```

### LINKED ISSUE #29430: Illegal instruction when calling DataFrames function
When running the following code using the `nl/grouping2` branch of `DataFrames` (commit 256bd1d), Julia 0.7, 1.0 and master crashes with "Illegal instruction".

```julia
using Pkg
Pkg.add("DataFrames#nl/grouping2")
using DataFrames
df = DataFrame(Key1 = CategoricalArray(["A", "A", "B", "B"]),
               Key2 = CategoricalArray(["A", "B", "A", "B"]),
               Value = 1:4)
combine(d -> DataFrame(x=d[1, :Key2]), groupby(df, :Key1))

Unreachable reached at 0x7f4bc01192fd

signal (4): Illegal instruction
in expression starting at no file:0
append_rows! at /home/milan/.julia/dev/DataFrames/src/groupeddataframe/grouping.jl:357
_combine! at /home/milan/.julia/dev/DataFrames/src/groupeddataframe/grouping.jl:373
unknown function (ip: 0x7f4bc0118c75)
jl_fptr_trampoline at /home/milan/Dev/julia/src/gf.c:1843
jl_apply_generic at /home/milan/Dev/julia/src/gf.c:2198
_combine at /home/milan/.julia/dev/DataFrames/src/groupeddataframe/grouping.jl:261
jl_fptr_trampoline at /home/milan/Dev/julia/src/gf.c:1843
jl_apply_generic at /home/milan/Dev/julia/src/gf.c:2198
combine at /home/milan/.julia/dev/DataFrames/src/groupeddataframe/grouping.jl:238
jl_fptr_trampoline at /home/milan/Dev/julia/src/gf.c:1843
jl_apply_generic at /home/milan/Dev/julia/src/gf.c:2198
do_call at /home/milan/Dev/julia/src/interpreter.c:324
eval_value at /home/milan/Dev/julia/src/interpreter.c:430
eval_stmt_value at /home/milan/Dev/julia/src/interpreter.c:363 [inlined]
eval_body at /home/milan/Dev/julia/src/interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/milan/Dev/julia/src/interpreter.c:808
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f4ba66bce1f)
unknown function (ip: 0x7)
jl_interpret_toplevel_thunk at /home/milan/Dev/julia/src/interpreter.c:817
jl_toplevel_eval_flex at /home/milan/Dev/julia/src/toplevel.c:818
jl_toplevel_eval_in at /home/milan/Dev/julia/src/builtins.c:622
eval at ./boot.jl:319
jl_apply_generic at /home/milan/Dev/julia/src/gf.c:2198
eval_user_input at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /home/milan/Dev/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:259
jl_apply_generic at /home/milan/Dev/julia/src/gf.c:2198
jl_apply at /home/milan/Dev/julia/src/julia.h:1559 [inlined]
start_task at /home/milan/Dev/julia/src/task.c:271
unknown function (ip: 0xffffffffffffffff)
Allocations: 39452559 (Pool: 39445133; Big: 7426); GC: 85
Illegal instruction (core dumped)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #25752, fixes #29269, fixes #29430

This fixes some more cases where type intersection incorrectly returned `Union{}` (which is unsound and causes crashes). Unfortunately, more non-empty intersections means more ambiguities. This mostly affects definitions with types like `Type{Union{Missing, T}} ... where T`, common of course in missing-data-related code. This requires #29405 (commit included), and also more disambiguating definitions.

The timing of this and #29380 was unintentionally good, so we can try these on master from the beginning of the 1.0.2 and/or 1.1 cycle. Since this fixes a crash it's a candidate for 1.0.2, but a PkgEval run is certainly warranted. If packages hit the same cases Base did, this will have to wait for 1.x.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
This will now also require #29419.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29406#issuecomment-426784969) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/7518a7529e3ac774da89192cfe1c91bf2f37518a/de73bff_vs_ea16391/report.md). cc @ararslan

**Comment by nalimilan** [comment]
@JeffBezanson Do you think this is ready to merge? There are lots of apparent regressions but it's hard for me to tell which ones could be real.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by JeffBezanson** [comment]
I think this is ready to merge but a PkgEval run would be good. It's hard to know how many packages will hit the same kinds of ambiguities Base and stdlib did.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29406#issuecomment-428167704) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fc8f30fa8413a1a8afeb7bf85e680ddd7219c450/caefb9b_vs_38612e0/report.md). cc @ararslan

**Comment by nalimilan** [comment]
Bump.

**Comment by JeffBezanson** [comment]
Bump for PkgEval.

**Comment by ararslan** [comment]
I think right now @Keno and I are the only ones who know how to do a run of NewPkgEval on demand. Unfortunately it requires a fair bit of setup since we don't have the infrastructure in place to just "click go" as it were, and I haven't had time recently to devote to doing on-demand runs nor to improving the infrastructure. Maybe Keno can take care of this in the shorter term, but I won't be able to get to it for a while yet.

**Comment by KristofferC** [comment]
Also fixes the following crash

```
@inline function partition_missing!(v::Vector{Union{T,Missing}}) where {T}
    i, j = 1, length(v)
    @inbounds while true
        while i < j && v[i] !== missing; i += 1; end
        while i < j && v[j] === missing; j -= 1; end
        i >= j && break
        v[i], v[j] = v[j], v[i]
        i += 1; j -= 1;
    end
    @inbounds return v[i] === missing ? i - 1 : i
end

function my_sort!(v::Vector{Union{T,Missing}}) where {T}
    m = partition_missing!(v)
    w = unsafe_wrap(Array, Ptr{T}(pointer(v)), m)
    @time sort!(w)
    v
end

using Random

function bench(T::Type = Int, n = 1_000_000)
    y = rand(T, n)
    vec = ifelse.(y .< 0.9, y, missing)
    z = copy(vec)
    bench_new = @time my_sort!(z)
end
```

**Comment by Keno** [comment]
Is this still waiting for PkgEval?

**Comment by nalimilan** [comment]
Yes, but I think we should merge this, PkgEval is only needed for backporting (since we need to fix this bug anyway, even if it breaks a few packages).

**Comment by JeffBezanson** [comment]
Ok, this can be merged now if we're willing to defer deciding whether to backport it.

**Comment by nalimilan** [comment]
I've rebased. Merge?

**Comment by nalimilan** [comment]
I'll merge this tomorrow if nobody objects. I really don't want it to miss 1.1.

**Pull request merged**
