### PR TITLE
Backports for 1.11.0-beta2

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #53665 <!-- use afoldl instead of tail recursion for tuples -->
- [x] #53976 <!-- LinearAlgebra: LazyString in interpolated error messages -->
- [x] #54005 <!-- make `view(::Memory, ::Colon)` produce a Vector -->
- [x] #54010 <!-- Overload `Base.literal_pow` for `AbstractQ` -->
- [x] #54069 <!-- Allow PrecompileTools to see MI's inferred by foreign abstract interpreters -->
- [x] #53750 <!-- inference correctness: fields and globals can revert to undef -->
- [x] #53984 <!-- Profile: fix heap snapshot is valid char check -->
- [x] #54102 <!-- Explicitly compute stride in unaliascopy for SubArray -->
- [x] #54070 <!-- Fix integer overflow in `skip(s::IOBuffer, typemax(Int64))` -->
- [x] #54013 <!-- Support case-changes to Annotated{String,Char}s -->
- [x] #53941 <!-- Fix writing of AnnotatedChars to AnnotatedIOBuffer -->
- [x] #54137 <!-- Fix typo in docs for `partialsortperm` -->
- [x] #54129 <!-- use correct size when creating output data from an IOBuffer -->
- [x] #54153 <!-- Fixup IdSet docstring -->
- [x] #54143 <!-- Fix `make install` from tarballs -->
- [x] #54151 <!-- LinearAlgebra: Correct zero element in `_generic_matvecmul!` for block adj/trans -->
- [x] #54213 <!-- Add `public` statement to `Base.GC` -->
- [x] #54222 <!-- Utilize correct tbaa when emitting stores of unions. -->
- [x] #54233 <!-- set MAX_OS_WRITE on unix -->
- [x] #54255 <!-- fix `_checked_mul_dims` in the presence of 0s and overflow. -->
- [x] #54259 <!-- Fix typo in `readuntil` -->
- [x] #54251 <!-- fix typo in gc_mark_memory8 when chunking a large array -->
- [x] #54276 <!-- Fix solve for complex `Hermitian`  with non-vanishing imaginary part on diagonal -->
- [x] #54248 <!-- ensure package callbacks are invoked when no valid precompile file exists for an "auto loaded" stdlib -->
- [x] #54308 <!-- Implement eval-able AnnotatedString 2-arg show -->
- [x] #54302 <!-- Specialised substring equality for annotated strs -->
- [x] #54243 <!-- prevent `package_callbacks` to run multiple time for a single package -->
- [x] #54350 <!-- add a precompile signature to Artifacts code that is used by JLLs -->
- [x] #54331 <!-- correctly track freed bytes in jl_genericmemory_to_string -->
- [x] #53509 <!-- revert moving "creating packages" from Pkg.jl -->
- [x] #54335 <!-- When accessing the data pointer for an array, first decay it to a Derived Pointer -->
- [x] #54239 <!-- Make sure `fieldcount` constant-folds for `Tuple{...}` -->
- [x] #54288
- [x] #54067
- [x] #53715 <!-- Add read/write specialisation for IOContext{AnnIO} -->
- [x] #54289 <!-- Rework annotation ordering/optimisations -->
- [x] #53815 <!-- create phantom task for GC threads -->
- [x] #54130 <!-- inference: handle `LimitedAccuracy` in `handle_global_assignment!` -->
- [x] #54428 <!-- Move ConsoleLogging.jl into Base -->
- [x] #54332 <!-- Revert "add unsetindex support to more copyto methods (#51760)" -->
- [x] #53826 <!-- Make all command-line options documented in all related files -->
- [x] #54465 <!-- typeintersect: conservative typevar subtitution during `finish_unionall` -->
- [x] #54514 <!-- typeintersect: followup cleanup for the nothrow path of type instantiation -->
- [x] #54499 <!-- make `@doc x` work without REPL loaded -->
- [x] #54210 <!-- attach finalizer in `mmap` to the correct object -->
- [x] #54359 <!-- Pkg REPL: cache `pkg_mode` lookup -->

Non-merged PRs with backport label:
- [ ] #54471 <!-- Actually setup jit targets when compiling packageimages instead of targeting only one -->
- [ ] #54457 <!-- Make `String(::Memory)` copy -->
- [ ] #54323 <!-- inference: fix too conservative effects for recursive cycles -->
- [ ] #54322 <!-- effects: add new `@consistent_overlay` macro -->
- [ ] #54191 <!-- make `AbstractPipe` public -->
- [ ] #53957 <!-- tweak how filtering is done for what packages should be precompiled -->
- [ ] #53882 <!-- Warn about cycles in extension precompilation -->
- [ ] #53707 <!-- Make ScopedValue public -->
- [ ] #53452 <!-- RFC: allow Tuple{Union{}}, returning Union{} -->
- [ ] #53402 <!-- Add `jl_getaffinity` and `jl_setaffinity` -->
- [ ] #53286 <!-- Raise an error when using `include_dependency` with non-existent file or directory -->
- [ ] #52694 <!-- Reinstate similar for AbstractQ for backward compatibility -->
- [ ] #51479 <!-- prevent code loading from lookin in the versioned environment when building Julia -->

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(vs =":release-1.10")`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54112#issuecomment-2060751087) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bdc7fb7_vs_bd47eca/report.html) is available.

**Comment by PallHaraldsson** [comment]
@tecosaur, I'm confused annotate! is new, but public, not exported so why:

Failed to precompile InMemoryDatasets [5c01b14b-ab03-46ff-b164-14c663efdd9f] to "/home/pkgeval/.julia/compiled/v1.11/InMemoryDatasets/jl_TqjVub".
ERROR: LoadError: UndefVarError: `annotate!` not defined in `InMemoryDatasets`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in Base.

I'm concerned how many packages are failing, and why, e.g. QML, because of CxxWrap seemingly. It's bad the CxxWrap gets broken repeatedly by Julia. I'm not exactly sure why (each time), I just understand it happens... And we now have a brand-new competitor to it, not sure if it's immune to such.

**Comment by tecosaur** [comment]
@PallHaraldsson I don't see what

> ERROR: LoadError: UndefVarError: annotate! not defined in InMemoryDatasets

has to do with `Base.annotate!`

**Comment by KristofferC** [comment]
Regarding `annotate!` in InMemoryDataSets.jl, probably fixed in https://github.com/sl-solution/InMemoryDatasets.jl/pull/117/. Not sure what that code is really doing though. 

@PallHaraldsson, please try to keep on topic for this PR, if you want to discuss stability of the C-API, this is not the place.

**Comment by tecosaur** [comment]
Three new backport-labelled PRs from me:
- #54308
- #54289
- #54302

**Comment by KristofferC** [comment]
@tecosaur, can you push your commits you want backported to here. I get merge conflicts for some and it is easier if you just do it.

**Comment by tecosaur** [comment]
> @tecosaur, can you push your commits you want backported to here. I get merge conflicts for some and it is easier if you just do it.

@KristofferC sure, I presume you're just referring to #54289 ?

**Comment by KristofferC** [comment]
I think it was https://github.com/JuliaLang/julia/pull/53715 as well

**Comment by tecosaur** [comment]
Cool, I've just cherry-picked them locally. FWIW I didn't run into any merge conflicts.

<details>
<summary>
Magit log
</summary>

```shell
  0 git … reset --hard upstream/backports-release-1.11 --
HEAD is now at bc9c928846 LinearAlgebra: Type-stability in broadcasting numbers over Bidiagonal (#54067)

  0 git … cherry-pick --mainline\=1 --ff fe554b791a
Auto-merging base/strings/annotated.jl
Auto-merging test/strings/annotated.jl
[backports-release-1.11 05e685ee8a] Rework annotation ordering/optimisations (#54289)
 Author: Timothy <git@tecosaur.net>
 Date: Tue Apr 30 23:14:48 2024 +0800
 7 files changed, 122 insertions(+), 83 deletions(-)
 create mode 100644 deps/checksums/StyledStrings-ac472083359dde956aed8c61d43b8158ac84d9ce.tar.gz/md5
 create mode 100644 deps/checksums/StyledStrings-ac472083359dde956aed8c61d43b8158ac84d9ce.tar.gz/sha512
 delete mode 100644 deps/checksums/StyledStrings-bfdb4c3f73a93a956ad48b0f06f89eb1cd40ff6b.tar.gz/md5
 delete mode 100644 deps/checksums/StyledStrings-bfdb4c3f73a93a956ad48b0f06f89eb1cd40ff6b.tar.gz/sha512

  0 git … cherry-pick --ff 5dcd509b66
[backports-release-1.11 6609f7d69e] Add specialised AnnotatedString pipe read/writes (#53715)
 Author: Timothy <git@tecosaur.net>
 Date: Thu May 2 17:39:37 2024 +0800
 2 files changed, 25 insertions(+)
```
</details>

**Comment by tecosaur** [comment]
If the markdown PR finally gets merged and there are any complications (or you'd just rather not deal with it), let me know and I'll happily repeat this.

**Comment by fingolfin** [comment]
It would be great to also get #53815 into 1.11.0-beta2. It requires (IMHO straightforward) manual resolution of the merge (identical to what is needed for the 1.10 branch) but it is easy enough, I can provide a PR if needed.

**Comment by JamesWrigley** [comment]
If it's merged in time, could https://github.com/JuliaLang/julia/pull/54571 be backported too? It's pretty important for developing Distributed on 1.11.

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54112#issuecomment-2133139577) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/af49d9f_vs_08e1fc0/report.html) is available.

**Pull request merged**
