### PR TITLE
fix incorrect displaysize when running some tests (fix #23071)

### LINKED ISSUE #23071: Printing of ranges: number of omitted elements
Since some time (say recent master) I get a test error because locally the number of print elements in a range differs. This could also be a fault of my configuration if this is locally configurable, but I do not see how and perhaps the test should not fail regardless.

```
Error in testset ranges:
Test Failed
  Expression: replstrmime(LinSpace{Float64}(0, 100, 10000)) == "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,…,99.95,99.96,99.97,99.98,99.99,100.0"
   Evaluated: "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,0.050005,0.060006,0.070007,0.080008,0.090009,…,99.86,99.87,99.88,99.89,99.9,99.91,99.92,99.93,99.94,99.95,99.96,99.97,99.98,99.99,100.0" == "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,…,99.95,99.96,99.97,99.98,99.99,100.0"
ERROR: LoadError: Test run finished with errors
```

```
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu) [PRETTY_NAME="Debian GNU/Linux 8 (jessie)]
  CPU: Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by rfourquet** [comment]
I'm not certain whether `displaysize()`, which returns `(24, 80)` if the dimensions are not found in `ENV`, is better than hardcoding `(24, 80)` in those tests...

**Comment by mschauer** [comment]
I suppose hard-coding would be best because the results are compared to the output on a machine with ``(24, 80)``.

**Comment by rfourquet** [comment]
Yes you are right, updated.

**Review by mschauer — APPROVED** [review]
That does it.

**Pull request merged**
