### PR TITLE
Derive T_size from DataLayout

### PR DESCRIPTION
**Pull request by pchintalapudi**

### CODE REVIEW

**Comment by KristofferC** [comment]
Would be nice with some context. Does this fix some issue, why is it better etc?

**Comment by pchintalapudi** [comment]
This PR just eliminates the obvious assumptions about host pointer size/alignment in codegen, since those are available from the data layout. It's necessary for codegen on not 32/64 bit architectures, and if in the future cross compilation is supported.

**Comment by gbaraldi** [comment]
And making JuliaFunction a template makes it a bit cleaner?

**Comment by pchintalapudi** [comment]
Yeah, otherwise there's a lot of JuliaFunctions with lambdas/function pointers that need to be rewritten to accept a target triple and T_size.

**Review by vchuravy — APPROVED** [review]
Looks good from my side.

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
