### PR TITLE
handle unicode space characters in `parse` for `Bool`

### PR DESCRIPTION
**Pull request by JeffBezanson**
Discovered this while investigating #21180.

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Would it make sense to make this change more broadly for other integer types and test it?

**Comment by JeffBezanson** [comment]
AFAICT the other parsing functions already handle this, since they only use `next` to move through the string.

**Comment by getzdan** [comment]
Hmm.. was preparing a PR to address this bug too. Guess things move quickly.
I suspect this commit, does not fix the problem, as the exception is caused by the initial `isspace(sbuff[endpos])`, as `endpos` does not point to a `isvalid` index (regarding the other issue of `readcsv`, there was another bug there).

**Comment by getzdan** [comment]
And I see this was addressed too in `datafmt.jl`, but there is still one unrelated bug there...

**Pull request merged**
