### PR TITLE
make broadcasting into getproperty extensible

### LINKED ISSUE #36741: Allow x.y .= z not to use getproperty(x, y)
When you write:
```
x[idx] .= z
```
it is processed as:
```
Base.materialize!(Base.dotview(x, idx), Base.broadcasted(Base.identity, z))
```
which allows packages to give a special meaning to`Base.dotview(x, idx)`, which is important if they want to define types that are broadcasting aware (as it allows to specialize the behavior of `dotview`).

On the other hand:
```
x.field .= z
```
is processed as:
```
Base.materialize!(Base.getproperty(x, :field), Base.broadcasted(Base.identity, z))
```
which does not allow to introduce a special broadcasting behavior in this case, as we call just `getproperty` (this is as if we called `getindex` instead of `dotview` in the first example).

The solution would be to use some intermediate function (name is tentative) with a defualt definition:
```
maybegetproperty(x, y) = getproperty(x, y)
```
that could get a special implementation in packages if needed.

---

A concrete use case is in DataFrames.jl, which allows:

```
df[:, :newcol] .= 1
```
to add a new column to the `df` `DataFrame`, while:
```
df.newcol .= 1
```
errors if `:newcol` does not exist in `df`.

---

@tkf you had a more more general idea what could be done here. Can you please comment on this?

### PR DESCRIPTION
**Pull request by simeonschaub**
Don't know if `dotgetproperty` is a good name for this, since as discussed in #36741, the way this works is a bit different from `dotview`. Right now, `dotproperty` returns a function which is used instead of `getproperty`, but not sure if that is a bit strange and we should just make it behave like `dotview` instead.

fixes #36741

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I'm inclined to have it do the operation (i.e. `dotgetproperty(x,y) = getproperty(x,y)`) instead of returning a function, if at all possible. It just seems easier to understand.

**Comment by simeonschaub** [comment]
Yes, that's probably less awkward.

**Comment by simeonschaub** [comment]
@JeffBezanson Is this good to go?

**Review by JeffBezanson — APPROVED** [review]

**Comment by bkamins** [comment]
Would it be possible to have it in 1.6 (or in general in new target Julia LTS release). It would be great for DataFrames.jl users to be able to assume this functionality is always available (otherwise I would need to write in the documentation that some basic functionality like `df.a .= 1` is available only in Julia 1.7 and upwards which is OK, but might be confusing for the users).

**Comment by KristofferC** [comment]
Feature freeze was a long time ago, so don't think any new features can go into 1.6.

**Pull request merged**
