### PR TITLE
Skip using nonexistent homedir() in repl tests

### PR DESCRIPTION
**Pull request by petercolberg**
The home directory might not exist, e.g., in a Debian sbuild chroot.

_This is part of an effort to upstream all patches in the Debian julia package._

### CODE REVIEW

**Comment by tkelman** [comment]
maybe give a warning if it doesn't exist that the corresponding tests aren't being run?

**Comment by petercolberg** [comment]
The tests now print a warning when the home directory is missing.

**Comment by Keno** [comment]
You could temporarily set `HOME` to a different directory to test functionality that defaults to homedir.

**Comment by petercolberg** [comment]
To not see the forest for the trees.

**Pull request closed without merging**
