### PR TITLE
when widening tuple types in tmerge, only widen the complex parts

### LINKED ISSUE #49249: parse_json regression in String allocations
[This commit](https://github.com/JuliaLang/julia/commit/56950e270863c0225b860e313451f70defa82c6d) (https://github.com/JuliaLang/julia/pull/48996) caused a regression in parse_json. Maybe related to https://github.com/JuliaLang/julia/issues/49241? @oscardssmith

### PR DESCRIPTION
**Pull request by oscardssmith**
This is the part of https://github.com/JuliaLang/julia/pull/50927 required to fix https://github.com/JuliaLang/julia/issues/49249. Specifically, before this change `tmerge(Tuple{Any, Int}, Nothing)` would be `Union{Nothing, Tuple{Any, Int}}` but `tmerge(Tuple{BIG_UNION, Int}, Nothing)` would be `Union{Nothing, Tuple{Any, Any}}`. This feels bad intuitively because giving the compiler more type information led it to forget type information that it already knew about, and is especially damaging because it led to unnecessary type instability when iterating tuples with complex element types (because the iterator state should be inferrable as an `Int` even if you have no idea what the tuple type is).

This is tagged for backport to 1.10 since it is a relatively unobtrusive change and it fixes the string regression in a more proper way.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Review by JeffBezanson — APPROVED** [review]

**Comment by oscardssmith** [comment]
Unsurprisingly, getting this exactly right is fairly fiddly. That said, this version now passes the inference tests locally at least. If this passes CI, it definitely needs a runtests (and possibly a pkgeval) to make sure it doesn't cause major regressions. That said, from my initial testing, this seems promising.

**Comment by oscardssmith** [comment]
@nanosoldier `runbenchmarks()`

**Comment by oscardssmith** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50929#issuecomment-1679994623) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/5fa25de_vs_883c19b/report.md).

**Comment by oscardssmith** [comment]
yeah. I think this is actually ready to merge.

**Pull request merged**
