### PR TITLE
Remove ARPACK and derived functions from julia repo

### PR DESCRIPTION
**Pull request by andreasnoack**
Instead, it will become a proper package, see https://github.com/JuliaLinearAlgebra/Arpack.jl, and will use binaries from https://github.com/JuliaLinearAlgebra/ArpackBuilder. This will simplify the build process of Julia a little bit.

When moving the ARPACK related functions from base to stdlib, we decided to name the package `IterativeEigensolver` to avoid using the name of the underlying library. Hence, it might seem to contradict that decision that the name of the new package is `Arpack`. However, the idea is to create a `SparseLinearAlgebra` umbrella package that would be the right entry point for most users. The `Arpack` function would mainly be a repo for hosting the actual wrapper functions.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Also, we have not actually used the name `IterativeEigenSolvers` in any released version of Julia. So, there isn't much code out there depending on it.

**Comment by staticfloat** [comment]
Great work guys.  This has been a long time coming.  Shoutout to @andreasnoack, @ViralBShah and @ararslan for chipping away at bits and pieces of this over the years.  I am looking forward to a fortran-free Julia one of these days.

**Comment by ararslan** [comment]
Bravo! 👏 Thanks so much for taking this on, Andreas.

**Comment by ararslan** [comment]
Looks like you'll need
```diff
--- a/test/precompile.jl
+++ b/test/precompile.jl
@@ -224,7 +224,7 @@ try
                      Base.PkgId(m) => Base.module_build_id(m)
                  end for s in
                 [:Base64, :CRC32c, :Dates, :DelimitedFiles, :Distributed, :FileWatching, :Markdown,
-                 :Future, :IterativeEigensolvers, :Libdl, :LinearAlgebra, :Logging, :Mmap, :Printf,
+                 :Future, :Libdl, :LinearAlgebra, :Logging, :Mmap, :Printf,
                  :Profile, :Random, :Serialization, :SharedArrays, :SparseArrays, :SuiteSparse, :Test,
                  :Unicode, :REPL, :InteractiveUtils, :OldPkg, :Pkg, :LibGit2, :SHA, :UUIDs, :Sockets]))
         @test discard_module.(deps) == deps1
```

**Comment by andreasnoack** [comment]
It looks like the tests are currently failings because Documenter depends on Compat and Compat depends on `IterativeEigensolvers`. I've opened https://github.com/JuliaLang/Compat.jl/pull/578 to resolve this.

**Comment by KristofferC** [comment]
You can just add that branch of Compat to the `docs` project if you want to test the doc building right away.

**Comment by andreasnoack** [comment]
> You can just add that branch of Compat to the docs project if you want to test the doc building right away.

Fancy new package manager. I've tried that so let's see how it goes.

**Comment by ararslan** [comment]
The macOS failure is #26725 and the Circle build looks like it got OOM killed.

**Comment by ViralBShah** [comment]
Seems good to merge.

**Review by ararslan — APPROVED** [review]

**Comment by KristofferC** [comment]
The Compat PR should likely be merged and a new version tagged first. Otherwise there will be no Compat compatible with the latest build.

**Pull request merged**
