### PR TITLE
LDLT: Restrict several methods to SymTridiagonal

### PR DESCRIPTION
**Pull request by barucden**
Related issue: JuliaLang/LinearAlgebra.jl#997

cc @dkarrasch

### CODE REVIEW

**Comment by dkarrasch** [comment]
To play it safe, let's run pkgeval, even though these methods can hardly work for anything else but a wrapped `SymTridiagonal`.

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/49344#issuecomment-1507245222) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3249cf7_vs_f2cbca6/report.html).

**Comment by dkarrasch** [comment]
Seems like most packages actually finished successfully, a few seem to have a segfault, all of which looks unrelated, but let's be sure.

@nanosoldier `runtests(["PyBullet", "SeisProcessing", "Retriever", "Aqua", "Extremes", "GeometricIntegrators", "GraphQLClient", "Anatta", "BioMart", "LovaszTheta", "Estapir", "IntervalOptimisation", "IMFData", "RheaReactions", "Infernal", "OpenQuantumBase", "SpinDoctor", "ProbNumDiffEq", "Relief"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/49344#issuecomment-1508630646) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3249cf7_vs_f2cbca6/report.html).

**Comment by dkarrasch** [comment]
Thanks @barucden!

**Comment by barucden** [comment]
Thank you

**Pull request merged**
