### PR TITLE
added example of array type conversion

### PR DESCRIPTION
**Pull request by mzaffalon**
... because it seems to bite less experienced users like myself.
(Stolen from Terry Seaward's email, https://groups.google.com/d/msg/julia-users/wzaJw_FfNlA/qcuZ4FggEL4J)

### CODE REVIEW

**Comment by martinholters** [comment]
One could also consider
```Julia
julia> a=[1 2 3; 4 5 6]
2×3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> convert(Array{Float64}, a)
2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0
```
as it actually converts the elements. Just an idea, not sure this is indeed better.

**Comment by KristofferC** [comment]
I would say showing an actual conversion taking place is useful.

**Comment by mzaffalon** [comment]
@martinholters your example is better, OK with me to change.

**Comment by kshyatt** [comment]
@mzaffalon is this your first Julia PR? Welcome to Julia, if so! (Or a much-belated hello otherwise.)

Thanks for adding docs. Do you need help making the update to the PR?

**Comment by mzaffalon** [comment]
@kshyatt something like this?

If not, then I would need help with rebasing, but I guess the 8 hour time zone difference won't help...

**Comment by martinholters** [comment]
You could have squashed the two commits, but we can do so upon merge, too, so no worries.

**Comment by mzaffalon** [comment]
I thought I did squash it.

**Comment by mzaffalon** [comment]
@martinholters sorry to bother when 0.5 is about to be released: is there something I should do with this PR? Can it be merged?

**Pull request merged**
