### PR TITLE
Fix performance regression of #19325

### PR DESCRIPTION
**Pull request by alyst**
An attempt to fix `mapreduce()` performance regression introduced by #19325 by bringing back handling of small (<16) arrays by `_mapreduce()`, so that the expensive compilation of `mapreduce_impl()` is not triggered.

In comparison to the pre#19325 version, `@inbounds` is not propagated into user-specified `f`.

### CODE REVIEW

**Comment by KristofferC** [comment]
Compilation time? AFAIU, nanosoldier usese minimum time for comparisons. Have you benchmarked the actual functions (using BenchmarkTools) that regressed before and after this commit and seen that this commit fixes it?

**Comment by alyst** [comment]
@KristofferC Not yet. What command should I run?

**Comment by KristofferC** [comment]
The Base benchmarks that Nanosoldier run are in https://github.com/JuliaCI/BaseBenchmarks.jl.
You can see from the nanosoldier report what functions had regressions.

Then you use https://github.com/JuliaCI/BenchmarkTools.jl to benchmark the functions with regressions and see if the commit here improved the benchmarks.

**Comment by alyst** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@333ff80e852aa20e9568e47d395ded82ad73f8d0")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@333ff80e852aa20e9568e47d395ded82ad73f8d0")`

**Comment by alyst** [comment]
I'm puzzled. The regressed "arrays"/"reduction" tests 1000-element arrays, so they always trigger the sequential branch of `mapreduce_impl()` (as `pairwise_blocksize(f, op)==1024` for these operations).
However, on my machine I do see that this PR significantly improves the results, although it doesn't touch the "kernel" evaluation code:
```
julia> leaves(improvements(judge(minimum(results_fixed), minimum(results))))
12-element Array{Any,1}:
 (Any[("maxabs", "Float64")], TrialJudgement(-1.65% => invariant))    
 (Any[("sumabs", "Float64")], TrialJudgement(-69.89% => improvement)) 
 (Any[("sumabs", "Int64")], TrialJudgement(-60.60% => improvement))   
 (Any[("sumabs2", "Float64")], TrialJudgement(-62.81% => improvement))
 (Any[("sumabs2", "Int64")], TrialJudgement(-46.47% => improvement))  
 (Any[("sum", "Int64")], TrialJudgement(-79.55% => improvement))      
 (Any[("mean", "Int64")], TrialJudgement(-80.36% => improvement))     
 (Any[("mean", "Float64")], TrialJudgement(-70.46% => improvement))   
 (Any[("var", "Float64")], TrialJudgement(-64.42% => improvement))    
 (Any[("var", "Int64")], TrialJudgement(-49.15% => improvement))      
 (Any[("sum", "Float64")], TrialJudgement(-70.42% => improvement))    
 (Any[("maxabs", "Int64")], TrialJudgement(-2.97% => invariant)) 
```

**Comment by alyst** [comment]
I did a quick profiling of master and this PR. One noticeable difference is that invocation of `mapreduce_impl()` from `_mapreduce()` (line 280 here) doesn't create any overhead in this PR, whereas in the master it's 2x the time spent in `mapreduce_impl()`.
I don't see the differences in `@code_warntype` for the invocation code that would explain the performance loss:

Master
```
@code_warntype Base._mapreduce(abs, +, IndexStyle([1.0,2.0,3.0,4.0]), [1.0, 2.0, 3.0, 4.0])
Variables:
  #self#::Base.#_mapreduce
  f::Base.#abs
  op::Base.#+
  #unused#::IndexLinear
  A::Array{Float64,1}
  inds::Base.OneTo{Int64}

Body:
  begin 
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl linearindices 92
      # meta: location abstractarray.jl indices1 64
      # meta: location abstractarray.jl indices 57
      SSAValue(2) = (Base.arraysize)(A::Array{Float64,1}, 1)::Int64
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      SSAValue(3) = (Base.select_value)((Base.slt_int)(SSAValue(2), 0)::Bool, 0, SSAValue(2))::Int64 # line 263:
      unless (Base.slt_int)(0, SSAValue(3))::Bool goto 14
      return $(Expr(:invoke, MethodInstance for mapreduce_impl(::Base.#abs, ::Base.#+, ::Array{Float64,1}, ::Int64, ::Int64, ::Int64), :(Base.mapreduce_impl), :(f), :(op), :(A), 1, SSAValue(3), 1024))
      14: 
      return (Base.abs_float)((Base.sitofp)(Float64, 0)::Float64)::Float64
  end::Float64
```

PR
```
@code_warntype Base._mapreduce(abs, +, IndexStyle([1.0,2.0,3.0,4.0]), [1.0, 2.0, 3.0, 4.0])
Variables:
  #self#::Base.#_mapreduce
  f::Base.#abs
  op::Base.#+
  #unused#::IndexLinear
  A::Array{Float64,1}
  Ai::Float64
  inds::Base.OneTo{Int64}
  n::Int64
  a1::Float64
  a2::Float64
  i::Int64
  s::Float64

Body:
  begin 
      NewvarNode(:(a1::Float64))
      NewvarNode(:(a2::Float64))
      NewvarNode(:(i::Int64))
      NewvarNode(:(s::Float64))
      $(Expr(:inbounds, false))
      # meta: location abstractarray.jl linearindices 92
      # meta: location abstractarray.jl indices1 64
      # meta: location abstractarray.jl indices 57
      SSAValue(6) = (Base.arraysize)(A::Array{Float64,1}, 1)::Int64
      # meta: pop location
      # meta: pop location
      # meta: pop location
      $(Expr(:inbounds, :pop))
      inds::Base.OneTo{Int64} = $(Expr(:new, Base.OneTo{Int64}, :((Base.select_value)((Base.slt_int)(SSAValue(6), 0)::Bool, 0, SSAValue(6))::Int64))) # line 263:
      n::Int64 = (Core.getfield)(inds::Base.OneTo{Int64}, :stop)::Int64 # line 264:
      unless (n::Int64 === 0)::Bool goto 21 # line 265:
      return (Base.abs_float)((Base.sitofp)(Float64, 0)::Float64)::Float64
      21:  # line 266:
      unless (n::Int64 === 1)::Bool goto 34 # line 267:
      $(Expr(:inbounds, true))
      # meta: location range.jl getindex 470
      27: 
      28: 
      # meta: pop location
      a1::Float64 = (Base.arrayref)(A::Array{Float64,1}, 1)::Float64
      $(Expr(:inbounds, :pop)) # line 268:
      return (Base.abs_float)(a1::Float64)::Float64
      34:  # line 269:
      unless (Base.slt_int)(n::Int64, 16)::Bool goto 74 # line 270:
      $(Expr(:inbounds, true))
      # meta: location range.jl getindex 470
      40: 
      41: 
      # meta: pop location
      i::Int64 = 1
      $(Expr(:inbounds, :pop)) # line 271:
      $(Expr(:inbounds, true))
      a1::Float64 = (Base.arrayref)(A::Array{Float64,1}, i::Int64)::Float64
      $(Expr(:inbounds, :pop)) # line 272:
      $(Expr(:inbounds, true))
      SSAValue(1) = (Base.add_int)(i::Int64, 1)::Int64
      i::Int64 = SSAValue(1)
      a2::Float64 = (Base.arrayref)(A::Array{Float64,1}, SSAValue(1))::Float64
      $(Expr(:inbounds, :pop)) # line 273:
      s::Float64 = (Base.add_float)((Base.abs_float)(a1::Float64)::Float64, (Base.abs_float)(a2::Float64)::Float64)::Float64 # line 274:
      NewvarNode(:(Ai::Float64))
      59: 
      unless (Base.slt_int)(i::Int64, (Core.getfield)(inds::Base.OneTo{Int64}, :stop)::Int64)::Bool goto 71 # line 275:
      $(Expr(:inbounds, true))
      SSAValue(3) = (Base.add_int)(i::Int64, 1)::Int64
      i::Int64 = SSAValue(3)
      Ai::Float64 = (Base.arrayref)(A::Array{Float64,1}, SSAValue(3))::Float64
      $(Expr(:inbounds, :pop)) # line 276:
      s::Float64 = (Base.add_float)(s::Float64, (Base.abs_float)(Ai::Float64)::Float64)::Float64
      69: 
      goto 59
      71:  # line 278:
      return s::Float64
      74:  # line 280:
      return $(Expr(:invoke, MethodInstance for mapreduce_impl(::Base.#abs, ::Base.#+, ::Array{Float64,1}, ::Int64, ::Int64, ::Int64), :(Base.mapreduce_impl), :(f), :(op), :(A), 1, :((Core.getfield)(inds, :stop)::Int64), 1024))
  end::Float64
```

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21167#issuecomment-289307652) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ed4034c34746e6380565f8af6decb2580ae69b1e/6ae223e_vs_333ff80/report.md). cc @jrevels

**Comment by alyst** [comment]
Most of the regressions have gone, the regressed "sumelt_boundscheck" and "sum_reduce" do not use `mapreduce()`.

Any ideas why the performance is so different?

**Comment by alyst** [comment]
@tkelman Do you think this was the real fix, not just a workaround for some underlying problem?

**Comment by tkelman** [comment]
Dunno! Might be worth investigating in more detail.

**Comment by tkelman** [comment]
Interestingly something broke in CategoricalArrays due to #19325, though this did fix it. https://github.com/JuliaCI/pkg.julialang.org/blob/gh-pages/logs/CategoricalArrays_0.6.log

**Pull request merged**
