### PR TITLE
Extend `strides` for `ReshapedArray` with strided parent.

### LINKED ISSUE #916: axpy! error:parent must be contiguous
After a routine update of [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl), the nightly run fails with strange errors see [here](https://github.com/andreasvarga/MatrixEquations.jl/runs/5445731334?check_suite_focus=true), while the tests on Julia 1.6 and 1.7 run error free.  All errors contain

`ArgumentError: Parent must be contiguous.`

occured in 

```
[5] axpy!(alpha::Float64, x::SubArray{Float64, 1, Matrix{Float64}, Tuple{UnitRange{Int64}, Int64}, true}, y::SubArray{Float64, 1, Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}, Tuple{UnitRange{Int64}}, false})
      @ LinearAlgebra.BLAS /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/LinearAlgebra/src/blas.jl:496

```

### LINKED ISSUE #44497: axpy! error:parent must be contiguous
After a routine update of [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl), the nightly run fails with strange errors see [here](https://github.com/andreasvarga/MatrixEquations.jl/runs/5445731334?check_suite_focus=true), while the tests on Julia 1.6 and 1.7 run error free.  All errors contain

`ArgumentError: Parent must be contiguous.`

occured in 

```
[5] axpy!(alpha::Float64, x::SubArray{Float64, 1, Matrix{Float64}, Tuple{UnitRange{Int64}, Int64}, true}, y::SubArray{Float64, 1, Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}, Tuple{UnitRange{Int64}}, false})
      @ LinearAlgebra.BLAS /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.9/LinearAlgebra/src/blas.jl:496

```

### PR DESCRIPTION
**Pull request by N5N3**
https://github.com/JuliaLang/julia/pull/44027 defined `strides(::ReshapedArray)` for dense/stridedvector parents, where the dense check failed to cover inputs with size-1 dimension.

With this PR, `strides` is extended to all `ReshapedArray` whose parent has `strides` defined.
And the memory layout check for vector inputs before BLAS call is fixed by code reuse.

Close JuliaLang/LinearAlgebra.jl#916.

### CODE REVIEW

**Comment by vtjnash** [comment]
This was an oversight (regression) in #44027, right, following the discussion after that PR was merged? That commit appears to be in v1.8.0 also, so this may need backporting

**Comment by jishnub** [comment]
Is this PR ready to be merged? Or is there something holding it back?

**Comment by N5N3** [comment]
It's waiting for review. @timholy would you mind taking a quick look at it?

**Comment by N5N3** [comment]
It's waiting for review. @timholy would you mind taking a quick look at it?

**Review by timholy — APPROVED** [review]
Sorry for the delay, I wasn't paying attention to Julia development for a couple of months due to other duties. This looks great, many thanks @N5N3!

**Comment by timholy** [comment]
Let's run tests again since it's been a while.

**Comment by N5N3** [comment]
Never mind @timholy. CI looks busy st present, maybe we need to rerun the test when it's free.

**Comment by timholy** [comment]
I haven't been following CI lately, are these failures OK? If so would someone please merge?

**Pull request merged**
