### PR TITLE
fix regression in select_intrinsic code emitted from a constant

### PR DESCRIPTION
**Pull request by vtjnash**
constant values to select were being emitted as an opaque load of a boxed value, preventing llvm from constant-folding with them downstream.

### CODE REVIEW

**Comment by tkelman** [comment]
any way to test this?

**Comment by vtjnash** [comment]
nothing particularly obvious to me. it wasn't previously wrong, just suboptimal for this particular example.

**Comment by tkelman** [comment]
Are the small examples from the end of #15323 better than nothing as tests for this?

**Comment by ArchRobison** [comment]
The commit looks right to me, and is easier to understand than what it replaces.

**Pull request merged**
