### PR TITLE
add Compiler diagram

### PR DESCRIPTION
**Pull request by sjkelly**
This is inspired by the diagram presented by Lionel Zoubritzky
in his 2018 JuliaCon talk.
This gives a visual overview of what is happening in the compiler.

### CODE REVIEW

**Comment by sjkelly** [comment]
I've cleaned up the design up a bit for symmetry and legibility. Feedback is appreciated.

**Comment by Seelengrab** [comment]
The green on orange text is a bit hard to make out, and the "Specialize" from "Method Dispatch" to "IR" could do with a different layout/position - it looks a bit odd that it's the only text crossing a colored box boundary.

**Comment by sjkelly** [comment]
Thanks for the great feedback @Seelengrab! I tweaked the colors and alignment a bit. I agree yellows are tough on the eyes!

**Review by vtjnash — APPROVED** [review]

**Comment by Seelengrab** [comment]
Thank you! Yeah, that's easier to follow.

**Comment by cormullion** [comment]
the black lines might struggle for visibility on a dark background (eg dark mode)...

**Review by JeffBezanson — APPROVED** [review]

**Comment by inkydragon** [comment]
> Note that CI seems to fail here.

LaTeX does not have good support for SVG.
So there is an error when compiling PDFs.

- https://tex.stackexchange.com/questions/2099/how-to-include-svg-diagrams-in-latex

A temporary solution is to keep both SVG and PNG formatted images, and to refer to the PNG images in the md document.

This is an upstream issue that requires Documenter.jl to improve the SVG support of the LaTeX backend.

**Comment by ViralBShah** [comment]
Simplest to just check in a png as well

**Comment by sjkelly** [comment]
I've opted to commit both the PNG and SVG. It was done in Google Draw, so there is unfortunately no other lossless format we can use for posterity.

**Comment by fredrikekre** [comment]
There is also https://github.com/JuliaDocs/DocumenterMermaid.jl for things like this now, but will probably also fail in PDF output.

**Pull request merged**
