### PR TITLE
allow Array{T,N}() for arbitrary N

### LINKED ISSUE #14201: Array{Int,3}() should create an empty 3d array
`Array{Int,1}()` and `Array{Int,2}()` create empty 1d- and 2d-arrays, respectively. This could also be implemented for all higher dimensions.

### PR DESCRIPTION
**Pull request by KristofferC**
Closes #14201

### CODE REVIEW

**Comment by stevengj** [comment]
This syntax seems a bit weird to me.

**Comment by KristofferC** [comment]
What syntax? `Array{T,  N}() `?

**Comment by martinholters** [comment]
I'd favor deprecating the `N==1` and `N==2` cases, but if we're going with this, I think we can safely remove those from boot.jl, no?

**Comment by KristofferC** [comment]
Unless they are used there? I was also worried if the splatting carried some performance problems but could just check the generated code. I don't think this should be deprecated, it is a convenient way to put a place holder object in a type that you will swap out later.

**Comment by martinholters** [comment]
> Unless they are used there?

I think base only uses this for `N==1` and only in files included after array.jl, so things should be good.

> it is a convenient way to put a place holder object in a type that you will swap out later.

I guess you only need it if `N` is largish or unknown at code-writing-time, so that spelling out the `0`s is impractical/impossible. Is that common? Should we consider different syntax, e.g. `empty(Array{T,N})`?

**Comment by KristofferC** [comment]
Removed the boot.jl definitions.

**Comment by stevengj** [comment]
I would rather deprecate the `N=1` and `N=2` cases; I didn't even realize we had those.

**Comment by mbauman** [comment]
See https://github.com/JuliaLang/julia/pull/11154 for a bit of history.  I think that `Vector()` and `Vector{Int}()` are somewhat common first attempts at constructing a vector for new users… but at the same time, learning those signatures generalizes poorly.  See the comment within that thread about `Array{Any}()`'s surprising behavior within that context and the immediate desire for `Vector(1,2,3) => Any[1,2,3]`.

I'm rather ambivalent here, but I agree it should be all or none.  It'd be interesting to see how common `Vector{T}()` is across registered packages.

**Comment by KristofferC** [comment]
Rekt by #20330

**Comment by StefanKarpinski** [comment]
Sorry, man!

**Comment by KristofferC** [comment]
I just wanted to close #14201 (which I just did) so end result is the same

**Pull request closed without merging**
