### PR TITLE
static macro: support unrolling a static for loop

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Just a thing I thought would be handy today for unrolling a static for loop at parse time.

### CODE REVIEW

**Comment by KristofferC** [comment]
Is this different from e.g. https://docs.julialang.org/en/v1/devdocs/cartesian/#Anonymous-function-expressions-as-macro-arguments?

**Comment by mikmoore** [comment]
It looks like this unrolls a `for` into a sequence of `let` blocks. This will result in errors (if lucky) or incorrect behavior (if unlucky) when utilized with `break`/`continue` statements. It seems that the macro should either handle these (they could be replaced with `@goto`, I think) or error (until a full solution is implemented) if the provided expression contains them.

For example
```julia
julia> for i in 1:2
	@static for j in 1:3
		x = 10i+j
		println(x)
		iseven(x) && break
	end
	#= result of @macroexpand
	begin
		let j = 1
			x = 10i + j
			println(x)
			iseven(x) && break
		end
		let j = 2
			x = 10i + j
			println(x)
			iseven(x) && break
		end
		let j = 3
			x = 10i + j
			println(x)
			iseven(x) && break
		end
	end
	=#
end
11
12
# did not write 21, 22 
```

**Comment by StefanKarpinski** [comment]
> @KristofferC: Is this different from e.g. https://docs.julialang.org/en/v1/devdocs/cartesian/#Anonymous-function-expressions-as-macro-arguments?

`@nloops` is, as I understand it, for emitting `n` nested for loops with dynamic numbers of iterations, whereas this is for statically unrolling a single for loop where the RHS iterator is evaluated statically like the condition in `@static if`. My motivating use case was wanting to unroll a small fixed number of loop bodies to avoid confusing the compiler with type instabilities. I'm not sure if `@nloops` can emulate this, but I don't think it can.

> @mikmoore: This will result in errors (if lucky) or incorrect behavior (if unlucky) when utilized with `break`/`continue` statements. It seems that the macro should either handle these (they could be replaced with `@goto`, I think) or error (until a full solution is implemented) if the provided expression contains them.

Yes, that's a good point. I'm not sure about adding those features; I think they can be implemented either using flag variables or labels and gotos. But would be complex to implement and kind of goes against the ethos of this as a simple feature to statically unroll a fixed number of loop iterations. Initially I would lean towards disallowing. This already errors, although the error message isn't super clear:
```jl
julia> @static for i = 1:3
           println(i)
           break
       end
ERROR: syntax: break or continue outside loop
```
I'm not entirely sure it's worth the additional complexity to try to catch this error and translate it; might be sufficient to document that this macro unrolls to let blocks and if you try to use `break` or `continue` this is the error you will see.

**Comment by StefanKarpinski** [comment]
> The point of my example was that this _does not_ error when nested inside a loop construct that supports `break`/`continue` -- instead it just applies the control statement to the outer loop. In that context, this macro can silently change the meaning of code.

Ah, I see now. Yes, that's not ok. We'd need to either error or handle it correctly.

> I'd be content if it scanned the loop expression and threw an error if one of these statements occurs anywhere.

This is a little tricky to do fully correctly since you can have a normal loop inside of the static loop body and that should be allowed. Might be sufficient to stop a recursive when encountering a loop inside.

> If I interpret the previous poster correctly, they were comparing this to `@nexprs` rather than `@nloops`.

Right, I misread the link as `@nloops`; indeed it does seem like `@nexprs` can do this. Maybe we don't need this feature then.

**Comment by KristofferC** [comment]
> Now that I realize that @nexprs can already do this, I'm a less inclined...

Let's pull the plug on it then. Seems like probably a bit too big of an overlap of functionality to warrant this.

**Pull request closed without merging**
