### PR TITLE
special-case UnitRange and OneTo range comparisons

### PR DESCRIPTION
**Pull request by stevengj**
Just a slight performance optimization for range comparisons, since these could be relatively important in critical indexing code.

### CODE REVIEW

**Comment by stevengj** [comment]
Whoops, I added the test but not the optimizations.  One sec.

**Comment by timholy** [comment]
Thanks!

**Comment by tkelman** [comment]
shouldn't this have gone through nanosoldier to verify that it made a difference?

**Comment by timholy** [comment]
Hmm, you're right:
```jl
julia> using Base.OneTo

julia> neweq(r::OneTo, s::OneTo) = last(r) == last(s)
neweq (generic function with 1 method)

julia> r = OneTo(5)
Base.OneTo(5)

julia> s = OneTo(6)
Base.OneTo(6)

julia> @which ==(r,s)
==(r::OrdinalRange, s::OrdinalRange) at range.jl:597

julia> @code_llvm ==(r,s)

define i8 @"jlsys_==_61863"(%OneTo*, %OneTo*) #0 {
top:
  %2 = getelementptr inbounds %OneTo, %OneTo* %0, i64 0, i32 0
  %3 = getelementptr inbounds %OneTo, %OneTo* %1, i64 0, i32 0
  %4 = load i64, i64* %2, align 8
  %5 = load i64, i64* %3, align 8
  %6 = icmp eq i64 %4, %5
  %7 = zext i1 %6 to i8
  ret i8 %7
}

julia> @code_llvm neweq(r,s)

define i8 @julia_neweq_70624(%OneTo*, %OneTo*) #0 {
top:
  %2 = getelementptr inbounds %OneTo, %OneTo* %0, i64 0, i32 0
  %3 = getelementptr inbounds %OneTo, %OneTo* %1, i64 0, i32 0
  %4 = load i64, i64* %2, align 8
  %5 = load i64, i64* %3, align 8
  %6 = icmp eq i64 %4, %5
  %7 = zext i1 %6 to i8
  ret i8 %7
}
```
@stevengj, did you have the impression this mattered?

**Comment by stevengj** [comment]
Hmm, I got confused by the LLVM output for `f(n,m) = Base.OneTo(n) == Base.OneTo(m)` and I thought it was doing three comparisons.  You're right, it looks like LLVM optimizes out the constant comparisons.

I think we can go ahead and revert this PR, but it might be good to keep the additional tests.

**Pull request merged**
