### PR TITLE
[RFC/WIP] Specify alignment of primitve types

### PR DESCRIPTION
**Pull request by vchuravy**
This is my first time feeling my way around the parser code so any pointer would be welcomed. The goal is to allow users to specify alignments for bitstypes. My particular use-case comes after talking to @simonbyrne about `Float128` support. I separated out the ABI changes for `Float128` which will be part of a later PR.

I would want to make the alignment an optional value since their should be only a limited number of use-cases, any pointer how do to that in lisp?

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Cool. This looks basically right, it's just a matter of deciding exactly what syntax we want. For example we might want

```
primitive type Float128 <: AbstractFloat 128
    alignment=16
end
```

to leave more room for other features in the future.

**Comment by vchuravy** [comment]
That sounds like an excellent idea. Any pointers how to do so without duplicating most of `struct-def-expr-` in `julia-synatx.scm`?

**Comment by vtjnash** [comment]
also fixes #20415

**Comment by vchuravy** [comment]
Very stale.

**Comment by simonbyrne** [comment]
I would still love a real Float128 (and perhaps Float80) one day...

**Pull request closed without merging**
