### PR TITLE
Added canonicalize for Periods

### PR DESCRIPTION
**Pull request by cfitz25**
When i was using canonicalize i had crashes sometimes when doing Period addition as sometimes a Period would be returned instead of a CompoundPeriod, this is a fix for that

### CODE REVIEW

**Comment by stevengj** [comment]
Could use a test…

**Comment by cfitz25** [comment]
Oops, sorry ill go create one now, thanks for the heads up

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
Maybe a NEWS item as well since this is a new method?

**Comment by cfitz25** [comment]
Sorry i am new here, how would i make a NEWS item?

**Comment by stevengj** [comment]
edit NEWS.md

**Pull request merged**
