### PR TITLE
Backports for 1.10.3

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #50759 
- [x] #51830 
- [x] #53273 
- [x] #53499 
- [x] #53424 
- [x] #53596 
- [x] #53516 
- [x] #53643 
- [x] #53655 
- [x] #53391 
- [x] #53809 
- [x] #53961 

Need manual backport:
- [ ] #52505 
- [ ] #53373 

Contains multiple commits, manual intervention needed:
- [x] #52913 
- [ ] #53218 
- [x] #53553 
- [ ] #53833 
- [ ] #53984  (should be done with #53833)

Non-merged PRs with backport label:
- [ ] #54010 
- [ ] #53882 
- [ ] #53597 
- [ ] #53452 
- [ ] #52694 
- [ ] #51479

### CODE REVIEW

**Comment by IanButterworth** [comment]
It'd be great to get 1.10.3 out (with the [threading gc segfault fix](https://github.com/JuliaLang/julia/commit/d3c8eb9dc960ce0e46231ec5bfc7ba8fcf687f46) that's on this branch)

**Comment by IanButterworth** [comment]
[feceefe](https://github.com/JuliaLang/julia/pull/53714/commits/feceefe1417304feb55b35201dc70cfdb7a3a628) appears to have introduced a LinearAlgebra failure https://buildkite.com/julialang/julia-release-1-dot-10/builds/245#018ecd32-81ec-4189-99ed-8fcbb37d3b6c/634-688 which seems odd

**Comment by IanButterworth** [comment]
I confirmed locally that this error was introduced by [`feceefe` (#53714)](https://github.com/JuliaLang/julia/pull/53714/commits/feceefe1417304feb55b35201dc70cfdb7a3a628)
```
tr: Test Failed at /Users/ian/Documents/GitHub/alts/julia/stdlib/LinearAlgebra/test/symmetric.jl:224
  Expression: tr(aherm) == tr(Hermitian(aherm))
   Evaluated: 2.6298493464368606 + 0.0im == 2.62984934643686
```

which is weird for just a change switching to lazy strings?
```diff
diff --git a/stdlib/LinearAlgebra/src/LinearAlgebra.jl b/stdlib/LinearAlgebra/src/LinearAlgebra.jl
index 494572b1e8dd8..7b3ff8f0db53d 100644
--- a/stdlib/LinearAlgebra/src/LinearAlgebra.jl
+++ b/stdlib/LinearAlgebra/src/LinearAlgebra.jl
@@ -238,14 +238,14 @@ julia> LinearAlgebra.checksquare(A, B)
 """
 function checksquare(A)
     m,n = size(A)
-    m == n || throw(DimensionMismatch("matrix is not square: dimensions are $(size(A))"))
+    m == n || throw(DimensionMismatch(lazy"matrix is not square: dimensions are $(size(A))"))
     m
 end
 
 function checksquare(A...)
     sizes = Int[]
     for a in A
-        size(a,1)==size(a,2) || throw(DimensionMismatch("matrix is not square: dimensions are $(size(a))"))
+        size(a,1)==size(a,2) || throw(DimensionMismatch(lazy"matrix is not square: dimensions are $(size(a))"))
         push!(sizes, size(a,1))
     end
     return sizes
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests(vs=":release-1.10")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.10")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/53714#issuecomment-2055740746) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/7305b58_vs_bd47eca/report.md).

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53714#issuecomment-2055739526) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b05a4f2_vs_bd47eca/report.html) is available.

**Comment by KristofferC** [comment]
Seeing some weird stuff in the PkgEval logs for a few packages:

```
lld: error: relocation R_X86_64_64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_t4SQ3q(text#0.o)
>>> referenced by libLLVM.jl:232 (/home/pkgeval/.julia/packages/LLVM/bzSzE/lib/15/libLLVM.jl:232)
>>>               text#0.o:(julia___init___1081) in archive /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_t4SQ3q

lld: error: relocation R_X86_64_64 cannot be used against local symbol; recompile with -fPIC
>>> defined in /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_t4SQ3q(text#0.o)
>>> referenced by libLLVM.jl:580 (/home/pkgeval/.julia/packages/LLVM/bzSzE/lib/15/libLLVM.jl:580)
>>>               text#0.o:(julia___init___1081) in archive /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_t4SQ3q
ERROR: LoadError: failed process: Process(setenv(`/opt/julia/libexec/julia/lld -flavor gnu '' -shared -o /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_xJbDgp --whole-archive /home/pkgeval/.julia/compiled/v1.10/LLVM/jl_t4SQ3q --no-whole-archive -L/opt/julia/lib/julia -L/opt/julia/lib -ljulia -ljulia-internal`,["PYTHON=", "LANG=C.UTF-8", "PATH=/opt/julia/libexec/julia:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin", "R_HOME=*", "JULIA_CPU_THREADS=1", "JULIA_NUM_PRECOMPILE_TASKS=1", "DISPLAY=:1", "JULIA_LOAD_PATH=/tmp/jl_SW24ut/Project.toml", "PKGEVAL=true", "OPENBLAS_NUM_THREADS=1", "LD_LIBRARY_PATH=/opt/julia/lib/julia:/opt/julia/lib", "HOME=/home/pkgeval", "CI=true", "JULIA_PKG_PRECOMPILE_AUTO=0", "JULIA_PKGEVAL=true", "OPENBLAS_MAIN_FREE=1", "JULIA_DEPOT_PATH=/home/pkgeval/.julia:/usr/local/share/julia:", "JULIA_NUM_THREADS=1"]), ProcessExited(1)) [1]
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["JuliaInterpreter", "ParallelStencil", "ImplicitGlobalGrid", "BenchmarkProfiles", "Permanents", "ComradeBase", "StaticTools", "ObjectPools", "StructuralIdentifiability", "Mango", "StaticCompiler", "QuantumTomography", "NeuralAttentionlib", "PlutoStaticHTML", "DiscreteChoiceModels", "RAPIDS", "CounterfactualExplanations"], vs = ":release-1.10")`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53714#issuecomment-2058591672) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5cf5146_vs_bd47eca/report.html) is available.

**Comment by IanButterworth** [comment]
Are there things remaining for this?

**Pull request merged**
