### PR TITLE
Update manual for dynamic docstrings

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by tkelman** [comment]
should also mention what `sig` is for

**Comment by malmaud** [comment]
I'm actually unclear myself on why you would use it in this context

**Comment by tkelman** [comment]
@stevengj / @MichaelHatherly? ref https://github.com/JuliaLang/julia/pull/20142#discussion_r97683848

**Comment by MichaelHatherly** [comment]
Passing `sig` *should* allow for returning different docs for `?x(1)` and `?x(1.0)`, currently it seems there's a bug in `?` mode preventing that from working though.

Probably not hugely important to have for PyCall for example, but I figured it would be best to make "dynamic" docs behave as closely to "normal" ones as possible.

**Comment by malmaud** [comment]
Ya, that's what I thought initially and then got confused when `?x(1)` didn't work. The manual probably shouldn't mention the sig stuff while it isn't actually working.

**Comment by kshyatt** [comment]
AV failure is in `pkg`, unrelated. Going to press the pretty button since this is Approved.

**Comment by tkelman** [comment]
> currently it seems there's a bug in `?` mode preventing that from working though.

That needs an issue

**Pull request merged**
