### PR TITLE
Add lu decomposition of *diagonal matrices

### LINKED ISSUE #281: Upcoming `lu` issue on nightly
On current master, there is a finer distinction in `copy_oftype`-like constructors, which will likely make this package fail on nightly, see

https://github.com/JuliaLang/julia/pull/40831#issuecomment-864385804

This affects your own `lu` implementation, which uses `copy_oftype(A, S)`, which used to call `convert(AbstractArray{S}(A))`, but now relies on 2-arg `similar`. So there are two options to fix this:

1. Write a 2-arg `similar` function for matrices with eltype `Taylor1`, then `copy_oftype` will start using this starting from Julia v1.8 "silently".
2. Replace `copy_oftype(A, S)` in `lu` by a direct call to `convert(AbstractArray{S}, A)`, which is handled internally in your package.

If needed, I'd be willing to help, probably just like @daanhb.

### LINKED ISSUE #375: lufact fails for Diagonal, Bidiagonal, and SymTridiagonal
`lufact` fails for `Diagonal`, `Bidiagonal`, and `SymTridiagonal` matrices. (I realize the former two are in factored form and LDLt is a better choice for `SymTridiagonal`.) Contrast with `qrfact`, which succeeds for all such types. (The difference seems to be that [`qrfact` calls `similar` to construct necessary fully mutable containers](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/qr.jl#L176), whereas [`lufact` merely copies the input matrix](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/lu.jl#L81). The fix may be as simple as replacing the `copy` with `similar` and an appropriate type computation.) Ref. JuliaLang/LinearAlgebra.jl#136. Best!

``` julia
julia> VERSION
v"0.6.0-dev.979"

julia> lufact(Diagonal(ones(4)))
ERROR: MethodError: no method matching lufact!(::Diagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Diagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(Bidiagonal(fill(2, 4), ones(3), true))
ERROR: MethodError: no method matching lufact!(::Bidiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Bidiagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(SymTridiagonal(fill(2, 4), ones(3)))
ERROR: MethodError: no method matching lufact!(::SymTridiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::SymTridiagonal{Float64}) at ./linalg/lu.jl:81
```

### LINKED ISSUE #18970: lufact fails for Diagonal, Bidiagonal, and SymTridiagonal
`lufact` fails for `Diagonal`, `Bidiagonal`, and `SymTridiagonal` matrices. (I realize the former two are in factored form and LDLt is a better choice for `SymTridiagonal`.) Contrast with `qrfact`, which succeeds for all such types. (The difference seems to be that [`qrfact` calls `similar` to construct necessary fully mutable containers](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/qr.jl#L176), whereas [`lufact` merely copies the input matrix](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/lu.jl#L81). The fix may be as simple as replacing the `copy` with `similar` and an appropriate type computation.) Ref. #8001. Best!

``` julia
julia> VERSION
v"0.6.0-dev.979"

julia> lufact(Diagonal(ones(4)))
ERROR: MethodError: no method matching lufact!(::Diagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Diagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(Bidiagonal(fill(2, 4), ones(3), true))
ERROR: MethodError: no method matching lufact!(::Bidiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::Bidiagonal{Float64}) at ./linalg/lu.jl:81

julia> lufact(SymTridiagonal(fill(2, 4), ones(3)))
ERROR: MethodError: no method matching lufact!(::SymTridiagonal{Float64}, ::Type{Val{true}})
Closest candidates are:
  lufact!{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:16
  lufact!(::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:31
  lufact!{T}(::Tridiagonal{T}, ::Union{Type{Val{false}},Type{Val{true}}}) at linalg/lu.jl:261
 in lufact(::SymTridiagonal{Float64}) at ./linalg/lu.jl:81
```

### PR DESCRIPTION
**Pull request by dkarrasch**
This adds `lu[!]` methods for all `*diagonal` types. As a follow-up to JuliaLang/julia#40831, which made `lu` work on AbstractMatrix, this reduces the computational load for the structured cases.

Closes JuliaLang/LinearAlgebra.jl#375. Closes https://github.com/JuliaDiff/TaylorSeries.jl/issues/281

### CODE REVIEW

**Comment by dkarrasch** [comment]
This also adds `rdiv!` for `Bidiagonal` matrices and removes the `lu(::StridedMatrix,...)` method added in #40831.

**Comment by dkarrasch** [comment]
@nanosoldier `runtests("TaylorSeries", vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41288#issuecomment-864560826):
```
NanosoldierError: failed to run tests: MethodError: no method matching read_pkgs(::String)
Closest candidates are:
  read_pkgs() at /storage/pkgeval/depot/packages/PkgEval/59AzU/src/registry.jl:39
  read_pkgs(!Matched::Vector{String}; registry) at /storage/pkgeval/depot/packages/PkgEval/59AzU/src/registry.jl:39
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e6a9151_vs_153f908/report.md)
cc @maleadt

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["TaylorSeries"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41288#issuecomment-864565384) has completed - no new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e6a9151_vs_153f908/report.md). cc @maleadt

**Comment by dkarrasch** [comment]
@andreasnoack Would you be able to take a quick look?

While working on this and the other "clean-up" PRs, I was wondering why we have lazy adjoints or transposes of the `*diagonal` at all. The minute you want to multiply or solve, you materialize the adjoint silently via `copy`. This concerns only non-`Number` eltypes. At some point, we must have decided that transposes of `Diagonal`s are never lazy, but the other `*diagonal` types are also only 2-3 times the memory of `Diagonal`, so it can hardly be a memory consumption argument.

**Comment by dkarrasch** [comment]
Gentle bump.

**Comment by andreasnoack** [comment]
I've some pending review comments, but first I'd like to ask if these are really useful in the first place? When you call `lu` you do so because you expect that your matrix doesn't have any structure. To me, `lu` for structured matrices seems like an unlikely usecase for optimize for. Am I missing something?

> I was wondering why we have lazy adjoints or transposes of the *diagonal at all.

I'm pretty sure that this has been discussed at least once but, unfortunately, I don't remember the details. I'd guess that it's to allow for future optimizations that weren't implemented initially because of lack of time.

**Comment by dkarrasch** [comment]
> Am I missing something?

No, you don't. I'm well aware that these by themselves are not very useful. It was two things that triggered this PR: first, the old open issue mentioned in the OP, and second, the `copy_*` PR which made `lu` work on `AbstractMatrix`es (by creating a dense copy) where `lu` used to fail with a method error before.

**Comment by andreasnoack** [comment]
Do you think it is worth the extra lines of code that are required to support optimized versions?

**Comment by dkarrasch** [comment]
Perhaps not. I'm fine with closing it, except we should remove the `StridedMatrix` `lu` method which caused trouble with `TaylorSeries.jl` because it took over precedence, perhaps together with other small changes in the sequel to #40831 and your review there.

**Pull request closed without merging**
