### PR TITLE
fix `exp` in `--math-mode=fast`

### LINKED ISSUE #41592: exp() accuracy is severly affected when using --fast-mode=fast
As discussed on the forum, the accuracy of exp() suffers when using fast-math because llvm optimizes away a numerical trick that is used for rounding:
https://discourse.julialang.org/t/whats-going-on-with-exp-and-math-mode-fast/64619/21

While some inaccuracy is expected when using fast-math, it seems like this specific situation could be improved by instructing llvm to not optimize away the numerical rounding trick.

There's probably a better way to do this, but I was able to get exp() working with fast-math by replacing the subtraction:
```N_float -=  MAGIC_ROUND_CONST(T)```
with
```N_float = forcesub(N_float, MAGIC_ROUND_CONST(T))```
where
```
function forcesub(a,b)
    Base.llvmcall("%3 = fsub double %0, %1\n ret double %3", Float64, Tuple{Float64,Float64}, a, b)
end
```

Before (with --math-mode=fast):
```
julia> exp(1.0)
2.7158546124258023

julia> exp(1e-3)
1.0
```
After (with --math-mode=fast):
```
julia> exp(1.0)
2.718281828459045

julia> exp(1e-3)
1.0010005001667084

### PR DESCRIPTION
**Pull request by oscardssmith**
don't rely on `muladd` fusing. Performance impact is minimal (max 1 cycle regression)

Closes #41592

### CODE REVIEW

**Comment by oscardssmith** [comment]
Merging soon if there are no objections.

**Comment by DilumAluthge** [comment]
Would be good to get a review?

**Comment by oscardssmith** [comment]
probably

**Comment by Keno** [comment]
I don't think we really should be designing for `--math-mode=fast`. That flag is just broken.

**Comment by oscardssmith** [comment]
This is actually fixing a broader issue that I had incorrectly assumed `muladd` would fold to `fma` here, and when it doesn't, it produces broken results. Since there is a 0 cost work around (or very close, within noise), this is still worth it.

**Comment by vtjnash** [comment]
It appears to still fail tests on all platforms, so there is some work left

When you say "assumed to be fma" do you mean we should have actually called the `fma` function here? Or just that the performance advantage of `fma` is tiny, but the loss of performance and accuracy (if it doesn't fold to fma) is undesirable?

**Comment by oscardssmith** [comment]
so I was using an `fma` with a subtraction to round, but I can also just round instead. The failing test appears to be `NaN` which was working implicitly before, but failing now.

**Comment by kimikage** [comment]
To be clear, this problem is not directly caused by `fma`. This is an optimization problem.

**Comment by KristofferC** [comment]
What about

https://github.com/JuliaLang/julia/blob/2893de764f86e3990e74a3cefdd46e13eb93a676/base/special/exp.jl#L404-L406

**Comment by oscardssmith** [comment]
I just realized that the problem here wasn't muladd not folding, but  fastmath making an assumption that `x+a-a=x`. Given that, this can just be closed as math mode fast being broken.

**Pull request closed without merging**
