### PR TITLE
Allow setindex! in zero part of Triangular matrices...

### PR DESCRIPTION
**Pull request by mbauman**
as long as the value is zero. The error message is similar to that of setindex for Diagonal matrices.  And similarly for setting the diagonal of UnitTriangular types to one.

Prompted by [this SO question](http://stackoverflow.com/a/33027927/176071).  We may want to also think about what a similar triangular matrix is… but that's a bigger question.

### CODE REVIEW

**Comment by mbauman** [comment]
This should be safe to backport.

**Comment by tkelman** [comment]
Only if all libraries that rely on this behavior explicitly mark their dependency on the first release version of Julia that has this change backported.

**Comment by mbauman** [comment]
Hunh?  Yes, this changes the tested interface (error types change, an error becomes a no-op in some situations), but I really would not consider it to be breaking.

**Comment by tkelman** [comment]
No, but it could be considered a new feature. User code that formerly errored would now work - so if a package starts relying on the new behavior, it needs to very clearly specify its dependence on the first version of Julia where it started working, otherwise the package would suddenly break upon upgrade for any users who stay on 0.4.0.

**Comment by mbauman** [comment]
Gotcha.  I was thinking of this more as a bug fix than a feature, but I can see your point.  Your call.

**Comment by tkelman** [comment]
This is a little of both. I guess the point is more general - even for obvious bug fixes, relying on fixes in backport releases should come with stricter dependency versioning discipline in packages to avoid causing issues for users. At least we now support testing against specific versions in Travis, so packages can test specifically against 0.4.0 (potentially in addition to 0.4-latest) now that it's out.

**Pull request merged**
