### PR TITLE
codegen optimizations for unions

### PR DESCRIPTION
**Pull request by vtjnash**
This seems to generate code that llvm is better at optimizing. Will definitely need to check nanosoldier though to see if this seems to trigger any regressions elsewhere.

### CODE REVIEW

**Comment by Keno** [comment]
Instcombine is quite expensive. Can you get away with instsimplify for your purpose?

**Comment by vtjnash** [comment]
Ah, I was assuming it was cheap since we call it very often. I don't actually need it.

**Comment by ararslan** [comment]
Looks like this broke the `cfunction` round-trip test on x86-64

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21279#issuecomment-291768370) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/99f008ea6a83a8145e37b112955dee91a5d97f87/f73beb6_vs_a5b993c/report.md). cc @jrevels

**Comment by martinholters** [comment]
Are the `"simd"` regressions real? I don't remember those as particularly noisy.

**Comment by ararslan** [comment]
We can always run again to see if the results are the same.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
They seem to be "quasi-real", but the reason is hilarious. With the extra passes, LLVM is able to notice that the loop is computing the number `0` and can elid all of the SIMD computational work and replace it with a simple `memset`. So we end up profiling the quality of the system memset function 😆

**Comment by ararslan** [comment]
That is pretty amusing. Why would that cause a regression though? The system's `memset` could actually be slower than the full SIMD computations?

**Comment by vtjnash** [comment]
> The system's memset could actually be slower than the full SIMD computations?

Yes. It is entirely reliant on the glibc version supporting the max vector width for the machine. The bottleneck is waiting for memory, making the SIMD calculations essentially "free".

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21279#issuecomment-291922501) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a088641336796883a11887823d0edbcc20c45b71/f73beb6_vs_a5b993c/report.md). cc @jrevels

**Pull request merged**
