### PR TITLE
Replace a :: with .. doctest:: in the types.rst

### PR DESCRIPTION
**Pull request by zhmz90**

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but could you squash the two commits into one?

**Comment by tkelman** [comment]
And remove the trailing whitespace. Generally you'll be better off if you manage updating your fork and creating new branches from either a local clone, or using the auto-branch feature of editing the file inline on github, rather than making pull requests on your fork (https://github.com/zhmz90/julia/pull/1) to update your copy of master.

**Comment by zhmz90** [comment]
Thanks, @tkelman .
And I start a new  pull request just with one commit.

**Comment by milktrader** [comment]
you can use `make check-whitespace` at the root of the Julia directory and it will tell you where your trailing whitespaces are (it passes silently).

**Comment by zhmz90** [comment]
Thank you, @milktrader . This feature is really useful!

**Pull request closed without merging**
