### PR TITLE
Remove flakey sorting test

### LINKED ISSUE #52591: Broken `partialsort` test unexpectedly passed in CI job
This is probably a random number issue, as the broken test passes if all the array elements are chosen to be identical. In https://buildkite.com/julialang/julia-master/builds/31349#018c859d-6e20-43d7-bf95-804b688d1ac5,
```julia
The global RNG seed was 0x6822a35e4a9f43d3b58013ecc6981379.
Error in testset sorting:
Error During Test at C:\buildkite-agent\builds\win2k22-amdci6-4\julialang\julia-master\julia-f7de26d7ee\share\julia\test\sorting.jl:725
 Unexpected Pass
 Expression: partialsort(1:n, 172, lt = ((i, j)->begin
                    #= C:\buildkite-agent\builds\win2k22-amdci6-4\julialang\julia-master\julia-f7de26d7ee\share\julia\test\sorting.jl:725 =#
                    v[i] <= v[j]
                end)) == perm[172]
 Got correct result, please change to @test if no longer broken.
ERROR: LoadError: Test run finished with errors
in expression starting at C:\buildkite-agent\builds\win2k22-amdci6-4\julialang\julia-master\julia-f7de26d7ee\share\julia\test\runtests.jl:97
[...]
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 1.11.0-DEV.1130
Commit f7de26d7ee (2023-12-20 05:04 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: 8 × AMD EPYC Processor (with IBPB)
  WORD_SIZE: 32
  LLVM: libLLVM-15.0.7 (ORCJIT, znver1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_BINARYDIST_FILENAME =
  JULIA_CMD_FOR_TESTS = julia-f7de26d7ee/bin/julia.exe .buildkite/utilities/timeout.jl julia-f7de26d7ee/bin/julia.exe
  JULIA_CPU_TARGET = pentium4
  JULIA_CPU_THREADS = 8
  JULIA_IMAGE_THREADS = 8
  JULIA_INSTALL_DIR = julia-f7de26d7ee
  JULIA_NUM_THREADS = 1
  JULIA_SHELL = C:/Program Files/Git/usr/bin/bash
  JULIA_TEST_IS_BASE_CI = true
  JULIA_TEST_MAXRSS_MB = 1536
  JULIA_TEST_VERBOSE_LOGS_DIR = C:\Users\julia\AppData\Local\Temp\jl_a8jqbI
  JULIA_VERSION = 1.11.0-DEV
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] runtests(tests::String; ncores::Int32, exit_on_error::Bool, revise::Bool, seed::Nothing)
   @ Base .\util.jl:704
 [3] top-level scope
   @ none:1
```
The test is at https://github.com/JuliaLang/julia/blob/d53fc50c24f5758bd0056f5e3fdf8655da63b9bc/test/sorting.jl#L706-L725

### PR DESCRIPTION
**Pull request by LilithHafner**
Fixes https://github.com/JuliaLang/julia/issues/52591

The other one is vastly less likely to pass by chance (on the order of 1/5 vs (1/5)^100) so I left it for now.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Instead of removing the test, could we just set the RNG seed right before we run the test?

**Comment by LilithHafner** [comment]
That's an option, but now there's a 4.7% chance of a false positive any time we change RNGs. IDK if we want that.

**Comment by MasonProtter** [comment]
Why are we testing for behaviour we explicitly don't support? These tests are a large burden on the whole CI infrastructure, is there any benefit at all to keeping them?

**Comment by LilithHafner** [comment]
> Why are we testing for behaviour we explicitly don't support

To catch bugs like https://github.com/JuliaLang/julia/pull/52494

> and only stochastically holds?

We shouldn't. This PR originally proposed to comment out the test that fails 4% of the time, but leave the test that fails less than one in 100_000 times (that's how much I was able to verify empirically, I expect it fails much less often than that). I think it's okay to test `rand(Int) != 0`.

I've reverted the PR to the original proposal and, at @DilumAluthge's suggestion, also fixed the RNG seed.

**Comment by MasonProtter** [comment]
@LilithHafner These tests are still causing problems for CI all over. E.g. https://github.com/JuliaLang/julia/pull/49546 has been updated multiple times since this PR merged and still fails it's tests because of the test
```
 Expression: partialsort(x, i, lt = (<=)) == (sort(x))[i]
   Evaluated: [1, 1, 1, 1, 1] == [2, 2, 2, 2, 2]
```
in `test/sorting.jl:1066`.

**Comment by KristofferC** [comment]
Let's just remove these imo. The argument is that if these tests start to pass then it is possible that something like https://github.com/JuliaLang/julia/pull/52494 happened and would be detected which is a quite roundabout way of thinking about tests. What will actually happen is someone will just be happy that they are now able to change `@test_broken` to `@test` and go ahead and do that.

**Comment by LilithHafner** [comment]
The test @MasonProtter noticed failing is actually a test, not a test_broken. It's a bad test because it's failing flakily rather than consistently, so it should be removed. However, I am concerned it reflects a correctness bug in a new partialsort algorithm and will investigate when I get the chance.

Sorry about the CI troubles.

**Comment by LilithHafner** [comment]
I'm going it be AFK for a bit, feel free to merge #52643 if you approve the removal.

**Pull request merged**
