### PR TITLE
Comment out DebugObjectManagerPlugin

### LINKED ISSUE #51794: ASAN builds spam "duplicate section" errors
When running an ASAN build, the output is spammed with the following error:

```
JIT session error: Duplicate section
```

The source: https://github.com/llvm/llvm-project/blob/8dfdcc7b7bf66834a761bd8de445840ef68e4d1a/llvm/lib/ExecutionEngine/Orc/DebugObjectManagerPlugin.cpp#L366-L376

I'm not familiar with the JIT, but having a look at the debugger, the duplicate section is `.group`, and indeed `createELFGroupSection` is called twice from https://github.com/llvm/llvm-project/blob/8dfdcc7b7bf66834a761bd8de445840ef68e4d1a/llvm/lib/MC/ELFObjectWriter.cpp#L1095-L1096, once for the `asan.module_ctor` symbol, and once for `asan.module_dtor`. Does this ring a bell, @lhames?

This didn't happen on 1.9, and I bisected it to #47037 (cc @pchintalapudi)

### PR DESCRIPTION
**Pull request by Keno**
Prem said this might fix #51794.

### CODE REVIEW

**Comment by vchuravy** [comment]
Can we do so only when on ASAN?

**Comment by Keno** [comment]
Do we know that this is ASAN specific? I think JITLINK is just not enabled currently on ELF unless we're using the sanitizers.

**Comment by gbaraldi** [comment]
It's enabled on aarch64 linux

**Comment by vchuravy** [comment]
The message is ASAN specific and harmless.

The goal is to get JITLink fully functional on all platforms and this plugin is needed for the GDB support. So commenting that out breaks more than it fixes.

**Pull request merged**
