### PR TITLE
Unrevert 46845 (Add `jl_print_task_backtraces()`)

### LINKED ISSUE #46177: Ability to print stacktraces of all tasks, including unscheduled ones
Detecting deadlocks is currently a bit difficult because if the tasks involved are unscheduled, we have no way of printing their backtraces.

Feature request: ability to print backtraces of all tasks, including all currently unscheduled tasks.

For us, deadlocks are not just priority inversions on locks, they can be byzantine scenarios involving many tasks, semaphores, channels, mutexes, conditions, futures, etc.

CC @NHDaly

### PR DESCRIPTION
**Pull request by kpamnany**
Intended for use from `gdb` to find deadlocks: iterates through `jl_all_tls_states` and through all `live_tasks` in `ptls->heap`, printing backtraces.

Closes #46177.

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by kpamnany** [comment]
The `julia-master` failure seems unrelated (possibly transient?) and `analyzegc` seems to have passed? Is there a way to check the day/time that this [`analyzegc` ran](https://buildkite.com/julialang/julia-master/builds/17663#01842e87-2d6e-49bb-a856-ba841f82c256)?

Cc: @Keno and @vtjnash

**Comment by giordano** [comment]
> Is there a way to check the day/time that this analyzegc ran?

You can click on "show timestamps", if that's what you're asking

**Comment by kpamnany** [comment]
> You can click on "show timestamps", if that's what you're asking

Ah. Thanks!

So it did run and it seems to have passed. 😕

**Comment by giordano** [comment]
> So it did run and it seems to have passed. :confused:

Does the confusion come from the fact
[`1f6ba00` (#47402)](https://github.com/JuliaLang/julia/pull/47402/commits/1f6ba00f96ef3eb4c84c6caee829bfd5a9ece98c) is the same commit as in #46845?  If so, that's not particularly surprising: CI in buildkite runs on the tip of the branch you want to merge, not on the merge commit generated by GitHub, and also in #46845 analyzegc was passing, so this CI run just replicated the successful run in #46845.

I'm going to merge `master` onto your branch.

**Comment by giordano** [comment]
It's failing now: https://buildkite.com/julialang/julia-master/builds/17686#01843307-64c9-4650-a112-a63e347b5894 :slightly_smiling_face:

**Comment by kpamnany** [comment]
Thanks @giordano! Turns out that `jl_n_threads` had turned into an atomically accessed variable. The pushed fix is hopefully going to solve this...

**Comment by vtjnash** [comment]
That looks right to me

**Pull request merged**
