### PR TITLE
Update dates.md

### PR DESCRIPTION
**Pull request by stephancb**
The claim that Julia Base DateTime implements UT (meant is UT1) time would require that the user converts ubiquitous UTC time stamps to UT1 and back, when accuracy requirements are about 1 s or higher. For most users this would be challenging to understand and perform correctly. Moreover, Julia itself gets system time, which is UTC (or UTC plus a timezone offset) with the `now()` function and constructs a DateTime without conversion to UT1, and so does not fulfill the claim. I think, that the claim should be retracted, see also the discussion at https://discourse.julialang.org/t/higher-resolution-datetime-timestamp/3069/35. I have suggested corresponding updates to dates.md

### CODE REVIEW

**Comment by fredrikekre** [comment]
Resolved conflicts, and requested review from (hopefully) relevant reviewers :)

**Review by quinnj — CHANGES_REQUESTED** [review]
I personally don't think the change is helpful here. Copy/pasting a few paragraphs from wikipedia about generic "time definitions" just feels like complicating the documentation without actually saying anything useful about the Julia `DateTime` type.

The documentation as-is is brief and tries to be upfront for developers coming from other languages or who may not have a great understanding of UT/UTC/TAI differences.

**Comment by fredrikekre** [comment]
Is that explanation to your satisfaction @stephancb ? If so, perhaps this can be closed instead.

**Comment by stephancb** [comment]
Thanks for considering, and I understand that a description of the differences between 
UTC, TAI, and UT is perhaps not necessary. On the other hand, it is the present 
documentation (at https://docs.julialang.org/en/stable/manual/dates/), 
where the rarely used and not needed UT/UT1 is (incorrectly) described, and this 
triggered my PR.

The manual should simply refer to UTC only.

One could then mention that the Julia Date/Time constructors don't 
accept ISO 8601 strings in leap seconds (like "2016-12-31T23.59.60"),
and that for the time metric all days have 86400 seconds.

To add some more detail, one could mention that leap second time stamps 
are also never produced by the OS (POSIX or Windows) via the now() 
function, and therefore the approach of rejecting/ignoring leap seconds 
is acceptable and harmless.

Please let me know, if you want me to draft an alternative PR.

**Comment by ViralBShah** [comment]
Closing this since its quite old. Reopen if still relevant, perhaps as a new PR.

**Pull request closed without merging**
