### PR TITLE
More robust fenv_constants

### PR DESCRIPTION
**Pull request by yuyichao**
The constant is platform dependent and the macro definition may not expand to the value itself.

By moving these from the `Makefile`/`perl` script to C, it is much more robust to detect if these are defined and is also slightly easier to define the fallback values for each platforms.

Fixes https://github.com/JuliaLang/julia/issues/10127

### CODE REVIEW

**Comment by yuyichao** [comment]
(The `arm` label is because the fallback value defined in the perl script is x86 specific so it causes the rounding tests to fail on arm when the fallback is used).

**Comment by yuyichao** [comment]
Tentatively mark as backport

**Comment by yuyichao** [comment]
With this PR and https://github.com/JuliaLang/julia/pull/19378, all tests (other than the skipped profile test) passed on the buildbot https://buildtest.e.ip.saba.us/#/builders/66/builds/10 🎉

**Comment by vtjnash** [comment]
Since these are hardware constants, would it be simpler to just enumerate them in Julia rather than doing this dance with the preprocessor?

**Comment by yuyichao** [comment]
I'd still like to query it from the libc if available. I can move the fallback to julia though.

**Comment by yuyichao** [comment]
I decided to remove the fallback entirely. According to cppreference, all of these constants are required by c99 and c++11 which is the minimum requirement for this file. The perl fallback was added original in https://github.com/JuliaLang/julia/commit/773b60e442472828c76c33209c3e7b0581588a44 with the [comment](https://github.com/JuliaLang/julia/pull/3149#issuecomment-23416447)

> I think we could check whether the preprocessor output parsed correctly, and if not, use the default x86/x64 values. I only found this issue on Ubuntu 12.04 (I didn't test it on other versions, I haven't got any other Ubuntu VMs handy), but not on Debian testing or on Arch Linux, so it might not be that big of an issue.

So I'm going to assume that the original issue is exactly the same as the issue we hit on master on arm buildbot (due to old glibc version that (legally) uses the `#define FE_* FE_*` pattern) which is what this PR solves properly.

**Comment by yuyichao** [comment]
AFAICT the osx failure was a [network issue](https://gist.github.com/yuyichao/4e09cfea78faf381937b04121dd34f39). Restarted.

**Comment by tkelman** [comment]
let me check whether this version works on msvc before merging

**Comment by tkelman** [comment]
strange, seems to freeze during bootstrap at number.jl? https://ci.appveyor.com/project/tkelman/julia/build/1.0.966 not sure what would cause that

**Comment by yuyichao** [comment]
`number.jl`? And it doesn't happen without this commit?

I'll expect any possible platform dependent failure to be in C not julia though so that's indeed very strange.

**Comment by tkelman** [comment]
Or maybe the file after that, I'm not sure how file name printing during bootstrap is ordered w.r.t. errors, start of processing a file or end of it. I was comparing this commit backported to release-0.5, since master has some other MSVC issues that I'm looking into.

Compare the above build 966 to https://ci.appveyor.com/project/tkelman/julia/build/1.0.965 which gets through bootstrap and stops at ccalltest, as expected. That was at the parent commit of https://github.com/tkelman/julia/commit/7356cc7b0de80e88b3f069c44a506760ee2494b9, which is just the following commits on top of release-0.5 https://github.com/JuliaLang/julia/compare/release-0.5...9c115465abad1383f57cf8b44a581d3a693f57e0 (misc build hacks that shouldn't be upstreamed)

**Comment by yuyichao** [comment]
I fixed a wrong include order (`#include <cfenv>` should not be in `extern "C"`) although I don't understand how it can cause a runtime error rather than a compile time one... maybe try again?

It doesn't really make sense if this causes error in bootstrap before including `rounding.jl`. A few things that I would try to debug this if this happens again

1. Putting sth like a `jl_safe_printf("in jl_get_fenv_consts\n");` in the C function to see if it is actually executed
2. Print the global values in `rounding.jl` to see if they are the same.
3. Include only the `include` change in `jlapi.c` to check if that causes any issues. (This should be the only change that could in theory make a difference before including `rounding.jl` if there's a compiler bug)

**Comment by tkelman** [comment]
https://ci.appveyor.com/project/tkelman/julia/build/1.0.982 didn't get to the prints
making just the include changes worked okay though https://ci.appveyor.com/project/tkelman/julia/build/1.0.983

Any other ideas?

**Comment by yuyichao** [comment]
Should be fixed (worked around). The issue seems to be that the MSVC build is somehow now happy about the use of `Cint` here. It might have got stuck in some loop/recursion when trying to report the actual error.

The error actually happen in `rounding.jl` but the printing of filename does not appear to be flushed correctly so the output stops at `bool.jl`. See my test commit(s) on my test branch to fix the https://github.com/yuyichao/julia/commit/b87c5ccaa8be05740ca6947e49164e7baa22677c to make sure the filename is printed before the file is included on windows (not a proper fix...).

**Comment by yuyichao** [comment]
AppVeyor failure was git network issue, restarted.

I think the MSVC issue was actually due to the difference between master and 0.5 (iirc `Cint` was moved to much earlier in bootstrap recently). The stuck was likely due to the lack of https://github.com/JuliaLang/julia/pull/18438/commits/320b86de0fdebaa01c83ac8dd300ab77e1bc3a27. With the commit cherry-picked on the MSVC branch it correctly reports the `Cint`missing error instead of causing infinite recursion/stackoverflow/whatever when an error occurs.

**Comment by yuyichao** [comment]
I revert back to the `Cint` version and removed the incorrect comment about MSVC build. I created a 0.5 backport version at https://github.com/JuliaLang/julia/tree/yyc/arm/fenv-0.5 which uses `Int32` instead.

**Pull request merged**
