### PR TITLE
Added a silent mode for download() function. E.g. `download("http://g…

### PR DESCRIPTION
**Pull request by ewiger**
…oogle.com", silent=true)` will make not output to STDERR or STDOUT.

Added a test into `test/file.jl`

### CODE REVIEW

**Comment by tkelman** [comment]
You can always redirect those streams to suppress them. Ref https://github.com/JuliaLang/BinDeps.jl/issues/135

**Comment by ewiger** [comment]
@tkelman can you please give an example of such a call?

**Comment by ewiger** [comment]
Oh.. you mean literally the implementation of **download_cmd** in BinDeps?

**Comment by tkelman** [comment]
Sorry, the reference was to a past discussion on improvements to this function. `redirect_stdout` and `redirect_stderr` should be able to do this, there are a few examples of this in the tests but I don't have one right in front of me at the moment.

**Comment by ewiger** [comment]
Maybe you mean something like

```
using BinDeps

cmd = BinDeps.download_cmd("http://google.com", tempname())
run(pipe(cmd, stdout=DevNull, stderr=DevNull))
```

?

**Comment by tkelman** [comment]
I'm not sure there was much of a conclusion to https://github.com/JuliaLang/BinDeps.jl/issues/135 yet, other than we should consolidate and improve whatever downloading functionality can be reasonably done well within base. We haven't had people volunteer to work on this area yet as I guess it hasn't been much of a priority, but contributions welcome. We might want to do some design discussion first though, adding flags piecemeal is probably not the ideal way forward.

**Comment by ewiger** [comment]
Ok, I used BinDeps for now. But I will think of a better design in Base.download, maybe by creating a type and some symbols for all the options.

**Comment by tkelman** [comment]
Should we close this for now then? Also note that next time it's best to create a separate branch for pull requests rather than submitting them from your fork's master branch, otherwise you end up with a lot of messy merge commits cluttering up the history.

**Pull request closed without merging**
