### PR TITLE
Add note about (un)shift to (push/pop)first docs

### PR DESCRIPTION
**Pull request by tckmn**
This would be helpful for new users when searching for these functions via e.g. apropos().

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
Yes, that's a good improvement. Thanks!

**Comment by crstnbr** [comment]
Why would one choose `unshift` as the name for a function that adds an element to the beginning of a collection? Seems super weird to me... Our `pushfirst!`/`popfirst!` names are so much better!

On a more general note, since when do we add such references to other programming languages naming conventions in docstrings? Isn't that what the "Noteworthy differences ..." section in the docs is for?

**Comment by ararslan** [comment]
> Isn't that what the "Noteworthy differences ..." section in the docs is for?

I generally assumed that that was for structural/design differences between languages rather than naming/API.

**Comment by StefanKarpinski** [comment]
That is why we didn't keep those names. Nevertheless that is what these are called in many other languages.

**Pull request merged**
