### PR TITLE
Feature to stop accepting new tasks on existing threads

### PR DESCRIPTION
**Pull request by janrous-rai**
This feature allows operators to stop scheduling of new tasks on specific threads which will make those threads high priority and only handle either explicitly scheduled tasks or tasks that are already running on those high priority threads.

This feature can be used to guarantee responsiveness on certain critical low-latency tasks by isolating them from the bulk of the julia workload that will run on other threads. We have observed that this eliminates most of the scheduling issues and slowdowns due to tasks occupying threads for excessive amounts of time (this is particularly problematic with sticky tasks in 1.6 where single long-running task that gets scheduled on the same thread as critical periodic task can cause major delays).

That said, low-latency is still subject to occasional hiccup as a result of stop-the-world behaviors that happen during garbage collection and compilation.

### CODE REVIEW

**Comment by vtjnash** [comment]
Why the close?

**Comment by KristofferC** [comment]
This was against the `backports-release-1.6` branch which was merged and auto-deleted causing this PR to automatically close.

**Comment by vtjnash** [comment]
Ah, it needs to be re-created against master then, since it cannot be reopened.

**Comment by tkf** [comment]
I just created a dummy `backports-release-1.6`, reopened this PR, changed the PR base, and then removed `backports-release-1.6`.

**Comment by NHDaly** [comment]
Thanks for managing that, @tkf!

**Comment by tkf** [comment]
(I just realized that my hack made it impossible to review the patch. The diff is easy to see at https://github.com/JuliaLang/julia/compare/1b93d53fc4bb59350ada898038ed4de2994cce33..e5cce258ea722884cb14d018213cef60da48b79c)

> some ideological design disagreements

This is a pretty good way to summarize my complaints :)

But, from the practical point of view, I think this PR might be better than #42302 as it's very (and surprisingly) minimal. Maybe that's why Jameson liked the approach.

> an API that would allow us to spawn a task in a dedicated thread that will only exist while the task is running and will be shut down when the task completes. This way we could spin off lightweight threads running critical work and ensure that they won't be blocked by bulk workloads

Booting up Julia's runtime environment (ptls) for a thread does not seem like a "lightweight" thing to do (at least intuitively). I'm also not entirely sure if it's easy to tear it down in the middle of the process lifetime. I think it would be "easier" to reuse the thread pool as I just sketched in #43649.

> I'm not sure whether the assumption that all transitive tasks need to stay on the dedicated thread. Our critical tasks are generally pretty simple and they don't do much concurrency so we are probably assuming that this is best-effort and that if something calls `@spawn`, the low latency is no longer guaranteed.

It's easy to set up a `Channel{Task}` where a consumer in a non-dedicated worker thread schedules the tasks on the non-dedicated worker threads. On the other hand, if we want to receive results from the non-dedicated threads and then do the work based on the result as soon as possible, we'd need to spawn a "waiter" task on the dedicated thread. I prefer this approach also because it let us stick with the structured concurrency paradigm.

To put it in another way, I think we better stick with the "black box rule" (i.e., it's an implementation detail if a function spawns tasks or not) to ensure composability, even with the tasks on dedicated worker threads. If every function call is a potential cause of priority inversion, I think it'd be very hard to use library functions.

**Comment by vtjnash** [comment]
This still needs to be rebased against master, and the flag moved into ptls

**Comment by vtjnash** [comment]
Threadpools is a slight generalization of this idea (allowing multiple threads to be prevented from examining the queue), but I think this is still something we can do in the meantime, and likely will be able to continue to support long-term. Other than finishing some nits, I think we can merge (and backport)

**Comment by tkf** [comment]
> Threadpools is a slight generalization of this idea (allowing multiple threads to be prevented from examining the queue), but I think this is still something we can do in the meantime, and likely will be able to continue to support long-term.

Hmm... Isn't #42302 close to ready? (I should probably look at the implementation a bit more, though.) I think expanding API surface of the scheduler makes it hard to extend and enable a more flexible approach like #44064. If we are planning to merge #42302, I think it's better to only add #42302 and not in combination with this PR. Or, can we at least put it in Experimental, so that it can be eventually removed once #42302 is in?

**Pull request closed without merging**
