### PR TITLE
Better candidate methods list for constructors

### PR DESCRIPTION
**Pull request by simonster**
This is an attempt to improve the MethodError from #9970. #10129 improved the message so that it doesn't show methods that obviously don't apply, but we still didn't show the method that @timholy wanted to call:

``` julia
julia> ArrayContainer(zeros(3,3), (:,:))
ERROR: MethodError: `convert` has no method matching convert(::Type{ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}}, :
:Array{Float64,2}, ::(Colon,Colon))
This may have arisen from a call to the constructor ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(...), since type co
nstructors fall back to convert methods in julia v0.4.
Closest candidates are:
  convert{T}(::Type{T}, ::T)

 in call at base.jl:36
```

I've changed the code so that, when it encounters a MethodError for `convert`, it shows matching methods for `call` as well, as I proposed in https://github.com/JuliaLang/julia/issues/9970#issuecomment-72529695. This is necessary to show matching constructors because `call` falls back to `convert` and so we never get a method error for `call` itself. It also makes some sense even if the user called `convert` explicitly; if there's a `call` method with a matching signature then there's a good chance that's what the user meant. For @timholy's case, this gives the candidates:

``` julia
julia> ArrayContainer(zeros(3,3), (:,:))
ERROR: MethodError: `convert` has no method matching convert(::Type{ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}}, ::Array{Float64,2}, ::(Colon,Colon))
This may have arisen from a call to the constructor ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(::Array{T,N}, ::I<:(Union(Int64,UnitRange{Int64})...,))
  convert{T}(::Type{T}, ::T)
 in call at base.jl:36
```

One issue is that inner constructors for parametrized types are not readily distinguishable from outer constructors. An example:

``` julia
julia> ArrayContainer{Float64,2,(Int,)}(1, 2, 3)
ERROR: MethodError: `convert` has no method matching convert(::Type{ArrayContainer{Float64,2,(Int64,)}}, ::Int64, ::Int64, ::Int64)
This may have arisen from a call to the constructor ArrayContainer{Float64,2,(Int64,)}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(::Any, ::Any)
  convert{T}(::Type{T}, ::T)
 in call at base.jl:36
```

It's not clear from the output that that's an inner constructor and not an outer one. But this seems to be a more general problem that also applies when printing a MethodTable:

``` julia
julia> methods(ArrayContainer)
2-element Array{Any,1}:
 call{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(::Type{ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}},data::Array{T,N},indexes::I<:(Union(Int64,UnitRange{Int64})...,))
 call{T}(::Type{T},args...) at base.jl:36

julia> methods(ArrayContainer{Float64,2,(Int,)})
2-element Array{Any,1}:
 call{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}(::Type{ArrayContainer{T,N,I<:(Union(Int64,UnitRange{Int64})...,)}},data,indexes)
 call{T}(::Type{T},args...) at base.jl:36 
```

How should we be distinguishing these?

### CODE REVIEW

**Comment by simonster** [comment]
Bump. Any objections to merging this? I just ran into a case where this would have helped today.

**Comment by StefanKarpinski** [comment]
Seems reasonable to me.

**Comment by dhoegh** [comment]
Seems like a good addition and  test is passing so I have no objections.

**Comment by jhasse** [comment]
Same goes for me :)

**Pull request merged**
