### PR TITLE
doc: remove changing "Stacktrace" in errors by [...]

### PR DESCRIPTION
**Pull request by rfourquet**
Cf. https://juliadocs.github.io/Documenter.jl/latest/man/doctests/.

### CODE REVIEW

**Comment by fredrikekre** [comment]
xref comments in #20202 when I tried to sneak this in :stuck_out_tongue:

**Comment by tkelman** [comment]
-1, I think showing some of the stacktrace is useful to show where the error and corresponding code happens.

If the concern is just avoiding having to update line numbers, would be better to adjust Documenter to add a permissive mode that ignores line number differences on master.

**Comment by KristofferC** [comment]
+1 It is a lot of extra noise when reading the docs. Anyone who is interested in the stack trace can run the code in the repl.

**Comment by tkelman** [comment]
not easily, if you're reading the documentation from somewhere that doesn't have julia installed, or mobile.

**Comment by KristofferC** [comment]
Yeah, those are the cases where this is likely more annoying than helpful since it is a real pain to navigate through the stacktrace on such a device.

**Comment by tkelman** [comment]
it looks fine to me, scrolling works normally, it's useful information to show and doesn't take a whole lot of space if you're selective about showing only the top few most relevant frames. also makes the output more representative of what you'd get from actually running the code - in a perfect world our docs would be live runnable snippets.

screenshot_2017-05-26-07-35-12

**Comment by KristofferC** [comment]
I meant to go through the source code for where the stacktrace points to.

>  it's useful information to show 

image

**Comment by rfourquet** [comment]
@fredrikekre oups sorry, I didn't even had the idea about searching for this topic as I thought it would be uncontroversial (in particular as it is suggested in Documenter). 
I don't have a strong opinion myself, but would be on the side to remove it, maybe while keeping the line containing "Stackstrace:" before the "[...]" to make explicit what output is suppressed. Why not keeping one place or two in the manual with the full stacktrace, as an exemple, but I would believe that otherwise the information is not used by people while reading the manual. 
Anyway, whatever decision is taken, it's probably worth it to document it once it's taken, so I will update this PR then, hoping some more people will give their opinion.

**Comment by tkelman** [comment]
Many of these have always been shown for as long as there have been doctests here, #4897

> the information is not used by people while reading the manual.

It's used in the same way as the output from example code is used, an illustrative part of what the code will do when run.

**Comment by KristofferC** [comment]
I think we should do this. In e.g. https://docs.python.org/2/library/doctest.html#what-about-exceptions they say:

> Best practice is to omit the traceback stack, unless it adds significant documentation value to the example. So the last example is probably better as:

So we can keep it when there is a point to it. But having it by default is just noise.

**Comment by rfourquet** [comment]
I will rebase this if a decision is made.

**Comment by KristofferC** [comment]
I was almost done with a rebased (actually done from scratch) version so I pushed it. I also added one commit with you as author for the description. https://github.com/JuliaLang/julia/pull/23988

**Pull request closed without merging**
