### PR TITLE
Change simd loop lowering

### LINKED ISSUE #29716: Simd loops emulates for loop scoping incorrectly
```jl
let j = 0; k = 0
   @simd for j = 1:5 end
   for k = 1:5 end
   @show j
   @show k
end
```

Results in 

```jl
j = 5
k = 0
```

### PR DESCRIPTION
**Pull request by KristofferC**
An experiment based on the benchmark in https://github.com/JuliaLang/julia/issues/25964.

Benchmark

```jl
regular = complex.(randn(1000000), randn(1000000));

function f_nosimd(x, a)
    s = zero(eltype(x))
    for i in 1:length(x)
        @inbounds s += x[i] * a
    end
    s
end


function f(x, a)
    s = zero(eltype(x))
    @simd for i in 1:length(x)
        @inbounds s += x[i] * a
    end
    s
end

using BenchmarkTools
```

```jl
julia> @btime f_nosimd($regular, 0.5+0.5im)
  1.191 ms (0 allocations: 0 bytes)
```

Before:

```jl
julia> @btime f($regular, 0.5+0.5im)
  1.194 ms (0 allocations: 0 bytes)
```

After:

```jl
julia> @btime f($regular, 0.5+0.5im)
  918.342 μs (0 allocations: 0 bytes)
```

This is a bit scary though:

https://github.com/JuliaLang/julia/blob/5f2759d85eeeb9c68e35e5e84b10715a49f4449d/src/llvm-simdloop.cpp#L38-L40

cc @vchuravy 

Fixes #29716

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
Interestingly the LLVM LangRef states that loop metadata goes on the `br` https://llvm.org/docs/LangRef.html#llvm-loop, we should figure out what LLVM prefers these days since that part of the code hasn't changed since Arch implemented it 5years ago.
Keno probably has a better feel for waht we should be doing here codegen wise.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29717#issuecomment-431111205) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/733a2385922434e5ac0fd9b047d6370cf7af6ceb/54f65a1_vs_5f2759d/report.md). cc @ararslan

**Comment by KristofferC** [comment]
That was much less exciting than I expected it to be...

**Comment by StefanKarpinski** [comment]
Yeah, that's kind of a wash. Hard to say if it was beneficial or detrimental overall.

**Comment by Keno** [comment]
FWIW, this change seems fine to me. I have general misgivings about the semantics of `@simd`, but that's neither here nor there. The `annotateSimdLoop` isn't actually used anymore in favor of the IR marker I introduced in #26985, so there should be nothing to worry about.

**Review by Keno — APPROVED** [review]

**Comment by KristofferC** [comment]
Ive seen some performance regression trying this out so doesnt seem like a good idea.

**Pull request closed without merging**
