### PR TITLE
Make ScopedValues public

### PR DESCRIPTION
**Pull request by LilithHafner**
See also, some alternatives: #54556, #53707

### CODE REVIEW

**Comment by arhik** [comment]
we will need to include :ScopedValues here after :PipeEndpoint
https://github.com/JuliaLang/julia/blob/2a5d553eb3698b7edc1be7addd55c1fd8d1be82f/test/misc.jl#L1527

**Comment by LilithHafner** [comment]
@vchuravy, would you be willing to write a very brief docstring for the module?

**Comment by vchuravy** [comment]
I currently do not have the bandwidth.

**Comment by LilithHafner** [comment]
We can add a docstring later.

**Pull request merged**
