### PR TITLE
Improve Pkg.resolve accuracy

### PR DESCRIPTION
**Pull request by carlobaldassi**
Reset the messages after each decimation. This helps avoiding some of the problems that were reported lately, in particular those at: https://discourse.julialang.org/t/differentialequations-pkg-wont-be-added

The idea is that resetting the messages makes the solver more accurate because it greatly mitigates the confounding effect of loops in the graph, since 1) the decimated variables are effectively like "cavities" in the graph, i.e. they break loops, and 2) the messages reset clears up all the spurious correlations.

In principle there may be a slight performance tradeoff, in practice it seems to me that it is basically as fast as before, and seems to solve all the problems that were reported.

The principle is sound, but thorough testing by somebody else is of course strongly encouraged.

### CODE REVIEW

**Comment by tkelman** [comment]
Cool, glad there was a thread to pull on with this. Can the problematic requirements graphs be distilled in some way into a test case? Does the resolver lend itself to being unit-tested like that without needing full integration of the rest of Pkg?

**Comment by ChrisRackauckas** [comment]
Could this geta v0.6 milestone? It seems that the resolver issues have become more widespread

Maybe https://github.com/JuliaLang/julia/issues/21430 is also fixed by this?

**Comment by carlobaldassi** [comment]
> Can the problematic requirements graphs be distilled in some way into a test case? Does the resolver lend itself to being unit-tested like that without needing full integration of the rest of Pkg?

See the latest commit, that's the best I could do.

**Comment by timholy** [comment]
Thanks a million, @carlobaldassi.

To what extent is this backportable to 0.5?

**Comment by carlobaldassi** [comment]
> To what extent is this backportable to 0.5?

There should zero problems with that.

**Comment by tkelman** [comment]
it may depend on https://github.com/JuliaLang/julia/pull/20598? will have to check

**Comment by carlobaldassi** [comment]
> it may depend on #20598?

They should be orthogonal.

**Comment by carlobaldassi** [comment]
> They should be orthogonal.

Well, except that I'm not sure if the new tests would pass without #20598.

**Pull request merged**
