### PR TITLE
Backport more GMP patches to fix FreeBSD compilation

### PR DESCRIPTION
**Pull request by staticfloat**
@ararslan Let's see if these extra backports fix FreeBSD CI.

### CODE REVIEW

**Comment by ararslan** [comment]
```
gmake[1]: *** [/usr/home/julia/buildbot/worker/package_freebsd64/build/deps/gmp.mk:34: scratch/gmp-6.1.2/build-configured] Error 1
```
:(

**Comment by staticfloat** [comment]
I finally figured out what is causing the problems on the FreeBSD buildbot; it's us setting `MALLOC_CONF=junk:true` in the environment; this causes the `clang` code for a `configure` test in `gmp-6.1.2` to reliably segfault.  @iblis17 I believe you were the one that set that flag initially; do you have any input here as to what we might be able to do?  To repro, just run the following in your `gmp-6.1.2` checkout:

```
export MALLOC_CONF=junk:true
./configure
```

**Comment by iblis17** [comment]
well, I always set it to false
https://github.com/JuliaLang/julia/blob/release-1.1/.freebsdci.sh#L28

**Comment by iblis17** [comment]
But I'm not sure why the .freebsdci.sh is gone and not used by CI.

**Comment by iblis17** [comment]
If you have any compilation issues on FreeBSD.
Feel free to ping me.

**Comment by staticfloat** [comment]
> But I'm not sure why the .freebsdci.sh is gone and not used by CI.

Back when we switched to the unified CI infrastructure, we stopped using separated build scripts and now just use [the `julia-buildbot/package.py` script](https://github.com/JuliaCI/julia-buildbot/blob/master/master/package.py); that way we have only one set of build steps across all platforms and architectures.

> well, I always set it to false

Oh.  Well then.  [I'll just fix that](https://github.com/JuliaCI/julia-buildbot/commit/e370897c3adcb19d6473e9832250a5acbe68d526).

> I still do not understand why it's failing here and not on master though.

I figured it out.  It's because we use BB on `master`.  Doh!

**Comment by iblis17** [comment]
> Oh. Well then. I'll just fix that.

:+1:

**Comment by iblis17** [comment]
Actually, I think the GMP developers abused the usage of `malloc`: 
  the standard does not promise to provide zero-out memory from malloc.
 
`MALLOC_CONF=junk:true` is quite helpful to discover that kind of issues.

**Comment by staticfloat** [comment]
> MALLOC_CONF=junk:true is quite helpful to discover that kind of issues.

Agreed; but I don't really want to have to fix every package's issues just to get backports working.  :P  If you like, you can open an issue on the gmp tracker and I will add a "me too!" to it.

**Comment by iblis17** [comment]
IIRC, FreeBSD ports developer already sent a patch to GMP upstream, but it haven been accepted yet.

**Comment by iblis17** [comment]
https://gmplib.org/list-archives/gmp-bugs/2018-February/004331.html

**Pull request closed without merging**
