### PR TITLE
RFC: Low-level API for `schedule` and `wait`

### PR DESCRIPTION
**Pull request by tkf**
Can we expose the use case of `schedule(task)` with `wait()` for running `task`s, if the caller of `schedule(task)` _knows that the `task` is "calling" `wait`_? I explained the API as a newly added manual section with an example ([rendered markdown here](https://github.com/tkf/julia/blob/doc-schedule/doc/src/base/parallel.md#low-level-synchronization-using-schedule-and-waitid-low-level-schedule-wait). This would be a very useful low-level API for building synchronization interfaces.

<strike>The challenge here is how to handle the case where the `task` is about to call `wait` but the context switch is not completed. IIUC, the API proposed here is not valid anymore in 1.8-DEV since the task migration improvement. That is to say, another worker thread may try to execute the task before `wait` is started. But I think there are a few ways to implement this API (see below) and I don't think there are large unavoidable performance impact for code not using it.</strike> (Edit: I think it's actually already supported https://github.com/JuliaLang/julia/pull/41270#issuecomment-965780335)

Can we add this API? <strike>If so, what's the preferred way to implement it?

### Possible implementation strategies

(1) Make public API `schedule(task)` insert runnable task to the sticky queue if it has non-zero `tid` (while switching the internal use of `schedule(task)` to directly calling `enq_work` which works as-is). This seems like the simplest solution.

(2) Introduce a new (say) `rerun` task state and let `schedule` try CASing `._state` from `runnable` to `rerun` first. It is checked during the context switch and then the task would be re-enqueued (or restarted) appropriately

(3) Similarly, introduce `running` task state and let `enq_work` use the sticky queue if it's `running`. (`schedule(task)` proposed in this PR does not "miss" `runnable`-to-`running` transition since the pre-condition for this API is that the `task` enters into the location in which the caller ensures the next context switch is the known `wait` call).
</strike>

### CODE REVIEW

**Comment by vtjnash** [comment]
Can you talk more about the motivating use case for this? Currently this is enforced by the Task scheduler implementation that represents each Task as an intrusive linked-list, so the Task can only exist in one place.

In particular, I don't see the motivation for your statement "Can we expose the use case of schedule(task) with wait() for running tasks, if the caller of schedule(task) knows that the task is "calling" wait?" as this seems to be a description of an existing `Condition` object, as has always existed and already been the primary API for interacting with the scheduler.

**Comment by tkf** [comment]
I needed similar patterns for implementing [Barriers.jl](https://github.com/tkf/Barriers.jl) and [ThreadedScans.jl](https://github.com/JuliaFolds/ThreadedScans.jl). For example, ThreadedScans.jl uses Hillis and Steele communication patterns

[](https://en.wikipedia.org/wiki/Prefix_sum#/media/File:Prefix_sum_16.svg)

where the small and large yellow circles can be semantically interpreted as `put!` and `take!` of a single-element `Channel` (aka promise). However, since there is always only one "communication peer" (denoted by non-vertical lines), we can use a lighter-weight mechanism than `Channel` (or `Condition`). For example, in a limited case like this, it does not even have to acquire a lock if the value is already there.

This kind of "peer-to-peer" communication pattern is abundant in high-performance parallel and concurrent programming. As you know, this is because the emphasis is on reducing the contention. I think the pattern I discussed in the manual can be used as a building block for translating atomic flag in spin-based algorithmic definitions to a usable form in a cooperative task system that Julia implements. I think it lets people experiment and implement interesting algorithms such as NUMA-aware hierarchical lock and nonblocking dual data structure without heavily modifying the task scheduler itself.

> a description of an existing `Condition` object, as has always existed and already been the primary API for interacting with the scheduler

Yes, this is semantically similar to a limited version of `Condition`. But the point is that this API lets you _avoid_ interacting with the scheduler (via `Condition`) _when checking if you **need** to interact with the scheduler_, in a nonblocking manner.

**Comment by tkf** [comment]
> the API proposed here is not valid anymore in 1.8-DEV since the task migration improvement

After writing the PR, I realized that the API proposed here is already correctly implemented due to

https://github.com/JuliaLang/julia/blob/d89addd21b97865eb5445f0051e5946d13842c68/src/partr.c#L191-L194

which is presumably required for supporting condition variable anyway.

So, I don't think any action is needed other than deciding if we want to support this.

**Comment by vtjnash** [comment]
I am not sure this doc addition is simple and clear enough for a future user to be benefited from it

**Comment by tkf** [comment]
I'm all for clarifying the documentation. But I guess the problem is that I've thought about this too much and I'm rather blind to what is unclear.

Would a more "practical" example help? I think I can turn this into a single-reader promise (or even to a generic promise; but that'd require introducing concurrent bag/queue/stack).

Or maybe adding sequence and state transition diagrams?

**Comment by tkf** [comment]
From chatting this with Jameson today: This is rather too low-level as a section in the manual. devdocs is probably a more appropriate place.

**Comment by tkf** [comment]
I moved it to the reference section.

(It's not in devdocs since there's no appropriate section in the devdocs. Besides, I don't think devdocs is an ideal place for documenting public API contracts.)

**Review by vtjnash — APPROVED** [review]
okay, sounds good

Also, perhaps adding a few code comments would help guide the reader?

**Comment by tkf** [comment]
@JeffBezanson Do you want to review this PR?

@vtjnash Do you prefer waiting for @JeffBezanson to check this?

**Comment by vtjnash** [comment]
It seems ready to go

**Comment by tkf** [comment]
Thanks!

**Comment by N5N3** [comment]
The following warning appeared on win64 during building after this PR:
```julia
┌ Warning: invalid local link: unresolved path in base\parallel.md
│   link.text =
│    1-element Vector{Any}:
│     "the API reference"
│   link.url = "@id low-level-schedule-wait"
└ @ Documenter.Writers.HTMLWriter C:\Users\MYJ\Documents\GitHub\julia\doc\deps\packages\Documenter\qdbx6\src\Writers\HTML
Writer.jl:2074
```

**Pull request merged**
