### PR TITLE
Revert "make internal calls to `require` use a fixed world"

### LINKED ISSUE #28042: World age issue when precompiling and redirecting the logger stream
See https://github.com/JuliaLang/IJulia.jl/issues/677. `IJulia` sets the global logger with its own stream which causes the following during precompilation of a package:
```
MethodError: no method matching pipe_writer(::IJulia.IJuliaStdio{Base.PipeEndpoint})
The applicable method may be too new: running in world age 27495, while current world is 27509.
Closest candidates are:
  pipe_writer(::IJulia.IJuliaStdio) at /home/fredrik/.julia/dev/IJulia/src/stdio.jl:15 (method too new to be called from this world context.)
  pipe_writer(!Matched::Base.ProcessChain) at process.jl:344
  pipe_writer(!Matched::Base.Process) at process.jl:332
```

Here is another repro from @pfitzseb:
```
julia> using Logging
       struct MyLogger <: AbstractLogger end
       Logging.shouldlog(::MyLogger, level, _module, group, id) = false
       Logging.min_enabled_level(::MyLogger) = Logging.BelowMinLevel

shell> rm -rf /home/fredrik/.julia/compiled/v0.7/BenchmarkTools/

julia> with_logger(MyLogger()) do
           @eval using BenchmarkTools
       end
ERROR: MethodError: no method matching shouldlog(::MyLogger, ::LogLevel, ::Module, ::Symbol, ::Symbol)
The applicable method may be too new: running in world age 27495, while current world is 27499.
Closest candidates are:
  shouldlog(::MyLogger, ::Any, ::Any, ::Any, ::Any) at REPL[0]:3 (method too new to be called from this world context.)
  shouldlog(::NullLogger, ::Any...) at logging.jl:83
  shouldlog(::SimpleLogger, ::Any, ::Any, ::Any, ::Any) at logging.jl:507
  ...
Stacktrace:
 [1] macro expansion at ./logging.jl:306 [inlined]
 [2] compilecache(::Base.PkgId) at ./loading.jl:1169
 [3] _require(::Base.PkgId) at ./loading.jl:942
 [4] require(::Base.PkgId) at ./loading.jl:838
 [5] require(::Module, ::Symbol) at ./loading.jl:833
 [6] eval at ./boot.jl:319 [inlined]
 [7] (::getfield(Main, Symbol("##3#4")))() at ./REPL[2]:2
 [8] with_logstate(::getfield(Main, Symbol("##3#4")), ::Base.CoreLogging.LogState) at ./logging.jl:385
 [9] with_logger(::Function, ::MyLogger) at ./logging.jl:481
 [10] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by pfitzseb**
This reverts commit 027e3444943d1442f3f9c39da2757f2c6f568a2c.

Fixes #28042.

### CODE REVIEW

**Comment by KristofferC** [comment]
One of the ideas was that only the precompile processes have this active. What would be the best way to do that? Add a ccallable function that activates this and put that into the script that is executed when the precompilation process run.

**Comment by vtjnash** [comment]
You can trigger it based on the `jl_generating_output`

**Comment by JeffBezanson** [comment]
I'll just remind everyone that this is not a trivial performance issue --- without it, precompiling CSV literally took 5 minutes, and now takes 50 seconds.

**Comment by Keno** [comment]
> I'll just remind everyone that this is not a trivial performance issue --- without it, precompiling CSV literally took 5 minutes, and now takes 50 seconds.

+1. I don't think this is acceptable without addressing this, just to print a couple of log messages.

**Comment by fredrikekre** [comment]
> just to print a couple of log messages.

It's not just that the message is not printed. The problem is that `using Package` errors in IJulia and Juno.

**Comment by ufechner7** [comment]
I think reverting is not an option, because it would make Julia unusable for me and other people. So we must find a different way to fix the problems with IJulia and Juno.

**Pull request closed without merging**
