### PR TITLE
Replace the first lady of DPRK with two famous actresses

### PR DESCRIPTION
**Pull request by petershintech**
The test data is listing names of famous actors and actresses of each countries. However, LEE Sol-Hee is the first lay of DPRK so it would be better to replace her with famous actresses in DPRK. Here I chose two actresses who are being highly respected in DPRK.

### CODE REVIEW

**Comment by wookay** [comment]
You seem to be confused with https://en.wikipedia.org/wiki/Ri_Sol-ju
and 이설희(李雪姬) is one of the famous actress in DPRK.

**Comment by petershintech** [comment]
Yes. I am confused. Here I am submitting an amend to keep 이설희 and drop 김선영. If you don't mind, I like to add 홍영희 because she was one of the most famous actresses in DPRK.

**Comment by KristofferC** [comment]
This data is taken from an external resource. It is just meant as a way of testing a library. I think we can leave this list alone.

**Comment by petershintech** [comment]
No problem with dropping this push request. Hopefully, somebody in North Korea will review the list in the near future :-)

**Pull request closed without merging**
