### PR TITLE
add --precompiled option to control whether precompiled code is used

### PR DESCRIPTION
**Pull request by JeffBezanson**
Ideally, we would do some extra work on windows here to pass `LOAD_LIBRARY_AS_DATAFILE` to LoadLibraryEx.

### CODE REVIEW

**Comment by ScottPJones** [comment]
Will this affect all precompiled code, including code in `inference*.dylib`?  That will help getting better coverage information, if so.
:+1: :100: for this!

**Comment by JeffBezanson** [comment]
This just tells us not to actually use any precompiled code loaded from shared libraries, whichever they are.

**Comment by ScottPJones** [comment]
Great!

**Comment by tkelman** [comment]
A thought - should we ship sys.dll on windows but change the default value of this flag for now, instead of messing with `--output-ji`? I'll have to test that and see if it gives decent backtraces.

**Comment by JeffBezanson** [comment]
Yes, that sounds simpler to me.

**Comment by tkelman** [comment]
if it works, we could manually force `--precompiled=true` for the cmdlineargs test so it runs faster and may work around #11818

**Comment by JeffBezanson** [comment]
That would be ideal.

**Comment by JeffBezanson** [comment]
I propose merging this now so people can try out the option, and separately change the windows build and defaults.

**Comment by ScottPJones** [comment]
Please merge this!

**Comment by tkelman** [comment]
Jeff, should I commit/PR
```patch
diff --git a/Make.inc b/Make.inc
index b03571b..9d53de9 100644
--- a/Make.inc
+++ b/Make.inc
@@ -384,12 +384,7 @@ endif


 # if not absolute, then relative to the directory of the julia executable
-# on windows, use .ji by default
-ifeq ($(OS),WINNT)
-JCPPFLAGS += "-DJL_SYSTEM_IMAGE_PATH=\"$(build_private_libdir_rel)/sys.ji\""
-else
 JCPPFLAGS += "-DJL_SYSTEM_IMAGE_PATH=\"$(build_private_libdir_rel)/sys.$(SHLIB_EXT)\""
-endif

 # On Windows, we want shared library files to end up in $(build_bindir), instead of $(build_libdir)
 ifeq ($(OS),WINNT)
diff --git a/Makefile b/Makefile
index 81c8857..5f404c2 100644
--- a/Makefile
+++ b/Makefile
@@ -182,11 +182,6 @@ $(build_private_libdir)/inference.o: $(build_private_libdir)/inference0.$(SHLIB_
        $(call spawn,$(JULIA_EXECUTABLE)) -C $(JULIA_CPU_TARGET) --output-o $(call cygpath_w,$(build_private_libdir)/inference.o) -f \
                -J $(call cygpath_w,$(build_private_libdir)/inference0.$(SHLIB_EXT)) coreimg.jl)

-# on windows, also generate a .ji file so we can delete the .dll
-ifeq ($(OS),WINNT)
-JULIA_SYSIMG_BUILD_FLAGS += --output-ji $(call cygpath_w,$(build_private_libdir)/sys.ji)
-endif
-
 COMMA:=,
 $(build_private_libdir)/sys.o: VERSION $(BASE_SRCS) $(build_docdir)/helpdb.jl $(build_private_libdir)/inference.$(SHLIB_EXT)
        @$(call PRINT_JULIA, cd base && \
@@ -363,16 +358,10 @@ else ifeq ($(OS), Linux)
 endif

        # Overwrite JL_SYSTEM_IMAGE_PATH in julia library
-ifeq ($(OS),WINNT)
-       for julia in $(DESTDIR)$(private_libdir)/libjulia*.$(SHLIB_EXT) ; do \
-               $(call spawn,$(build_bindir)/stringreplace $$(strings -t x - $$julia | grep "sys.ji$$" | awk '{print $$1;}' ) "$(private_libdir_rel)/sys.ji" 256 $(call cygpath_w,$$julia)); \
-       done
-else
        for julia in $(DESTDIR)$(private_libdir)/libjulia*.$(SHLIB_EXT) ; do \
                $(call spawn,$(build_bindir)/stringreplace $$(strings -t x - $$julia | grep "sys.$(SHLIB_EXT)$$" | awk '{print $$1;}' ) "$(private_libdir_rel)/sys.$(SHLIB_EXT)" 256 $(call cygpath_w,$$julia)); \
        done
 endif
-endif

        mkdir -p $(DESTDIR)$(sysconfdir)
        cp -R $(build_sysconfdir)/julia $(DESTDIR)$(sysconfdir)/
@@ -417,9 +406,6 @@ ifeq ($(JULIA_CPU_TARGET), native)
 endif

 ifeq ($(OS), WINNT)
-       # If we are running on windows, also delete sys.dll until we switch to llvm3.5+
-       -rm -f $(DESTDIR)$(private_libdir)/sys.$(SHLIB_EXT)
-
        [ ! -d dist-extras ] || ( cd dist-extras && \
                cp 7z.exe 7z.dll libexpat-1.dll zlib1.dll libgfortran-3.dll libquadmath-0.dll libstdc++-6.dll libgcc_s_s*-1.dll libssp-0.dll $(bindir) && \
            mkdir $(DESTDIR)$(prefix)/Git && \
diff --git a/src/init.c b/src/init.c
index 0bc1151..02ccfd9 100644
--- a/src/init.c
+++ b/src/init.c
@@ -111,7 +111,12 @@ jl_options_t jl_options = { 0,    // quiet
                             JL_OPTIONS_FAST_MATH_DEFAULT,
                             0,    // worker
                             JL_OPTIONS_HANDLE_SIGNALS_ON,
+#ifdef _OS_WINDOWS_
+// TODO remove this when using LLVM 3.5+
+                            JL_OPTIONS_USE_PRECOMPILED_NO,
+#else
                             JL_OPTIONS_USE_PRECOMPILED_YES,
+#endif
                             NULL, // bindto
                             NULL, // outputbc
                             NULL, // outputo
```
?

This looks like it gets the right backtrace behavior.

**Comment by JeffBezanson** [comment]
LGTM!

**Comment by tkelman** [comment]
Also the name might need to be bikeshedded a little, and at least a bare-bones test for this and other recently added compiler flags should be added to the cmdlineargs test.

**Comment by JeffBezanson** [comment]
True enough.

**Comment by tkelman** [comment]
And whoops, that broke `julia-debug.exe` with a `System image file "D:\cygwin64\home\Tony\julia\usr\lib\julia\sys.dll" not found`. Either we bring the `output-ji` flags back for debug, or link a separate `sys-debug.dll`. Since we can't have undefined references on Windows, and don't want both release and debug versions of libjulia loaded into the same process.

**Comment by JeffBezanson** [comment]
Would passing `LOAD_LIBRARY_AS_DATAFILE` fix that? We should really do that anyway.

**Comment by tkelman** [comment]
I don't know.

**Comment by tkelman** [comment]
@JeffBezanson can you propose a patch? Would be good to get `julia-debug.exe` working again.

**Comment by tkelman** [comment]
If I'm reading this right, it looks like even latest libuv upstream doesn't allow for flags in the `uv_dlopen` API? https://github.com/libuv/libuv/blob/44485ce682e4111fdd5d538ee20ed294563a3df9/src/win/dl.c#L28

Do we need to copy over that code to soup-up `jl_uv_dlopen` then?

**Comment by JeffBezanson** [comment]
Ok I have tried to implement this idea in #12147.

**Pull request merged**
