### PR TITLE
Fix broken show method for Base.LogicalIndex

### LINKED ISSUE #34364: broken show method for Base.LogicalIndex
As reported in https://github.com/JuliaLang/IJulia.jl/issues/892,
```jl
julia> Base.LogicalIndex([true])
1-element Base.LogicalIndex{Int64,Array{Bool,1}}:
Error showing value of type Base.LogicalIndex{Int64,Array{Bool,1}}:
ERROR: getindex not defined for Base.LogicalIndex{Int64,Array{Bool,1}}
```
stemming from an error in the `text/plain` method for `show`:
```jl
julia> show(stdout, Base.LogicalIndex([true]))
Base.LogicalIndex(Bool[1])
julia> show(stdout, "text/plain", Base.LogicalIndex([true]))
1-element Base.LogicalIndex{Int64,Array{Bool,1}}:
ERROR: getindex not defined for Base.LogicalIndex{Int64,Array{Bool,1}}
Stacktrace:
 [1] error(::String, ::Type) at ./error.jl:42
 [2] error_if_canonical_getindex(::IndexCartesian, ::Base.LogicalIndex{Int64,Array{Bool,1}}, ::Int64) at ./abstractarray.jl:991
 [3] _getindex at ./abstractarray.jl:980 [inlined]
 [4] getindex at ./abstractarray.jl:981 [inlined]
 [5] isassigned(::Base.LogicalIndex{Int64,Array{Bool,1}}, ::Int64, ::Int64) at ./abstractarray.jl:405
 [6] alignment(::IOContext{Base.TTY}, ::Base.LogicalIndex{Int64,Array{Bool,1}}, ::UnitRange{Int64}, ::UnitRange{Int64}, ::Int64, ::Int64, ::Int64) at ./arrayshow.jl:67
 [7] print_matrix(::IOContext{Base.TTY}, ::Base.LogicalIndex{Int64,Array{Bool,1}}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at ./arrayshow.jl:186
 [8] print_matrix at ./arrayshow.jl:159 [inlined]
 [9] print_array at ./arrayshow.jl:308 [inlined]
 [10] show(::Base.TTY, ::MIME{Symbol("text/plain")}, ::Base.LogicalIndex{Int64,Array{Bool,1}}) at ./arrayshow.jl:345
 [11] show(::Base.TTY, ::String, ::Base.LogicalIndex{Int64,Array{Bool,1}}) at ./multimedia.jl:109
 [12] top-level scope at REPL[7]:1
```

### PR DESCRIPTION
**Pull request by karan0299**
Fixes #34364 
`julia> show(stdout, "text/plain", Base.LogicalIndex([true]))` now shows the following output
` 1-element Base.LogicalIndex{Int64,Array{Bool,1}}:
 1`
Output is similar to that of collect method on LogicalIndex as suggested by @stevengj
In my opinion this is the appropriate change required.
Defined `print_array(io,X::LogicalIndex) = print_array(io,collect(X))`

### CODE REVIEW

**Comment by stevengj** [comment]
Should we change the 2-arg show as well?

**Comment by karan0299** [comment]
I think we should change show function with 2 args to maintain the consistency with the 3 args show method.
In my opinion output of show function with similar args i.e.
`julia> show(stdout,Base.LogicalIndex([true,false,true]))` should be displayed as 
`[1,3]`
What is your opinion @stevengj ?

**Comment by karan0299** [comment]
I have updated the 2 args show method as well in last commit.

**Comment by stevengj** [comment]
As discussed in #34364, it seems like we may not want `LogicalIndex` to be a subtype of `AbstractArray` at all, in which case this implementation will have to change slightly.

**Comment by karan0299** [comment]
@stevengj as explained by Matt Bauman why he considers it to be a subtype of Abstract array, is this fix fine?

**Review by stevengj — APPROVED** [review]

**Comment by mbauman** [comment]
Failures are unrelated (a timeout and a distributed test failure).

**Pull request merged**
