### PR TITLE
Fix coverage for the first statement in the function

### LINKED ISSUE #17442: 0.5 code-coverage regression
`--code-coverage` appears to be skipping the first line of methods. For example with the following package:

```julia
module TestPackage

function test()
    a = 1
    b = 2
    a + b
end

end
```

and `test/runtests.jl` containing:

```julia
using TestPackage
using Base.Test

TestPackage.test()
```

On `0.5` we have

```
$ julia-0.5 --code-coverage=user test/runtests.jl
$ cat src/TestPackage.jl.11032.cov 
        - module TestPackage
        - 
        - function test()
        -     a = 1
        2     b = 2
        2     a + b
        - end
        - 
        - end
        - 
```

while on `0.4`

```
$ julia-0.4 --code-coverage=user test/runtests.jl
$ cat src/TestPackage.jl.9700.cov 
        - module TestPackage
        - 
        - function test()
        1     a = 1
        1     b = 2
        1     a + b
        - end
        - 
        - end
        - 
```

`--inline=no` doesn't change the result.

This is on `0.5.0-dev+5448` 54a6490 and `0.4.7-pre+3` eb322c0.

### PR DESCRIPTION
**Pull request by yuyichao**
Fixes #17442 

Not sure how to add tests but at least this fixes the coverage [on my package](https://codecov.io/github/yuyichao/LibALPM.jl/commits).

### CODE REVIEW

**Comment by tkelman** [comment]
why did bd06d27c001cd1c0a9d118c3614c74d33b406cb6 make this necessary? should see if Coverage.jl's tests might start passing again on this branch

**Comment by yuyichao** [comment]
> remove location/pure/inline meta early, in the front end
> (the first line node isn't needed, since this info is in the Method object)

**Comment by yuyichao** [comment]
From the commit message

**Comment by MichaelHatherly** [comment]
Thanks.

**Comment by vtjnash** [comment]
Looks like this has fixed coveralls for master (https://coveralls.io/builds/7058631). Thanks :)

**Pull request merged**
