### PR TITLE
accelerate openblas startup for many-core machines

### PR DESCRIPTION
**Pull request by vtjnash**
Address #4993 and possibly #2852 and #3536
This only works against the static compile branch, because we need to run this code before the codegen loads openblas.

### CODE REVIEW

**Comment by buczek** [comment]
To my experiments, this doesn't work at all (at least for version 0.6.0). It can't work, because assignment to `ENV` doesn't change the environment of the running process.

<pre>
buczek@nomatophobie:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-unknown-linux-gnu

julia> ENV["OPENBLAS_NUM_THREADS"]
"8"

julia> ccall((:openblas_get_num_threads64_, Base.libblas_name), Cint, ())
16

julia> pid=getpid()
19422

julia> run(`cat /proc/$pid/environ`)
XDG_SESSION_ID=2257TERM=xtermSHELL=/bin/bashTMPDIR=/scratch/localSSH_CLIENT=141.14.31.7 38676 22SSH_TTY=/dev/pts/3USER=buczekMAIL=/var/mail/buczekPATH=/home/buczek/android-sdks/platform-tools:/home/buczek/bin:/bin:/usr/bin:/sbin:/root/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/package/bin:/usr/local/binPWD=/home/buczekLANG=CPS1=\u@\h:\w\$ SHLVL=1HOME=/home/buczekXDG_CACHE_HOME=/scratch/local/buczek/.cacheLOGNAME=buczekPRINTER=chipprinterXDG_DATA_DIRS=/usr/local/share/:/usr/share/:/usr/local/packageLC_CTYPE=en_US.UTF-8SSH_CONNECTION=141.14.31.7 38676 141.14.31.93 22XDG_RUNTIME_DIR=/run/user/buczekDISPLAY=localhost:23.0_=/usr/bin/julia
julia> 
</pre>

**Comment by ViralBShah** [comment]
I believe you have to set the variable before starting julia. OpenBLAS reads it only during its initialization, IIRC.

**Comment by buczek** [comment]
That's right and another reason, why this commit which attempts to set the environment-variable from within julia, wouldn't be working. Even if the environment would be changed, it would be to late to change the initialization. One of the comments above suggest, that OpenBLAS is not yet loaded and initialized when this code is executed (`base/client.jl` in this pull request, nowadays migrated into `base/initdefs.jl` on master), but I think that is wrong. Anyway, if `ENV["OPENBLAS_NUM_THREADS"] = 8` doesn't change the environment of the executing process, it doesn't matter, if this would be in time or not.

We changed that to 
```
    if !("OPENBLAS_NUM_THREADS" in keys(ENV)) && !("OMP_NUM_THREADS" in keys(ENV))
        Base.LinAlg.BLAS.set_num_threads(1)
    end
```
and have another local patch, which allows us to specify NUM_THREADS for OpenBLAS compilation (which becomes the maximum) at julia compile time. In the julia distribution its hard-coded to 8 or 16 depending on the architecture ( `deps/blas.mk` ). So we start with 1 and users can increase via environment `OPENBLAS_NUM_THREADS` or `Base.LinAlg.BLAS.set_num_threads()`.

**Comment by yuyichao** [comment]
> if ENV["OPENBLAS_NUM_THREADS"] = 8 doesn't change the environment of the executing process

Unclear why you say that.

**Comment by buczek** [comment]
I'm sorry, I was wrong. Assignment to ENV does indeed call `setenv()`   and `/proc/$pid/environ` can't be expected to reflect these changes. 

Still, the julia init code `ENV["OPENBLAS_NUM_THREADS"] = 8` doesn't reduce the number of threads, so I guess it is just called to late and OpenBLAS is already initialized.
<pre>
buczek@taphophobie:/dev/shm/julia (master)$ ./julia -q
julia> ccall((:openblas_get_num_threads64_, Base.libblas_name), Cint, ())
16

julia> 
buczek@taphophobie:/dev/shm/julia (master)$ OPENBLAS_NUM_THREADS=5 ./julia -q
julia> ccall((:openblas_get_num_threads64_, Base.libblas_name), Cint, ())
5

julia> 
</pre>

**Comment by buczek** [comment]
Yes, the assignment is to late (in 0.6.0) :
<pre>
buczek@taphophobie:/dev/shm/julia (master)$ gdb ./julia
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./julia...done.
(gdb) break main
Breakpoint 1 at 0x4015a0: file /dev/shm/julia/ui/repl.c, line 171.
(gdb) run
Starting program: /dev/shm/julia/julia 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".

Breakpoint 1, main (argc=1, argv=0x7fffffffeb08) at /dev/shm/julia/ui/repl.c:171
171        {
(gdb) break setenv
Breakpoint 2 at 0x7ffff6d2c930: file setenv.c, line 253.
(gdb) break openblas_read_env
Function "openblas_read_env" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 3 (openblas_read_env) pending.
(gdb) c
Continuing.
[New Thread 0x7ffff3c7b700 (LWP 19294)]

Breakpoint 3, 0x00007fffe6212050 in openblas_read_env () from /dev/shm/julia/usr/bin/../lib/libopenblas64_.so
(gdb) where
#0  0x00007fffe6212050 in openblas_read_env () from /dev/shm/julia/usr/bin/../lib/libopenblas64_.so
#1  0x00007fffe5ff704a in gotoblas_init () from /dev/shm/julia/usr/bin/../lib/libopenblas64_.so
#2  0x00007ffff7de915a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffeb08, env=env@entry=0x7fffffffeb18) at dl-init.c:72
#3  0x00007ffff7de926b in call_init (env=0x7fffffffeb18, argv=0x7fffffffeb08, argc=1, l=<optimized out>) at dl-init.c:30
#4  _dl_init (main_map=main_map@entry=0x7ba450, argc=1, argv=0x7fffffffeb08, env=0x7fffffffeb18) at dl-init.c:120
#5  0x00007ffff7ded740 in dl_open_worker (a=a@entry=0x7fffffffde20) at dl-open.c:564
#6  0x00007ffff6e15821 in __GI__dl_catch_error (objname=0x7fffffffde10, errstring=0x7fffffffde18, mallocedp=0x7fffffffde0f, operate=0x7ffff7ded360 <dl_open_worker>, args=0x7fffffffde20) at dl-error-skeleton.c:198
#7  0x00007ffff7deced7 in _dl_open (file=0x7fffffffe140 "libopenblas64_.so", mode=-2147483639, caller_dlopen=0x7ffff77137f9 <jl_load_dynamic_library_+729>, nsid=-2, argc=1, argv=<optimized out>, env=0x7fffffffeb18)
    at dl-open.c:649
#8  0x00007ffff74bbf76 in dlopen_doit (a=a@entry=0x7fffffffe030) at dlopen.c:66
#9  0x00007ffff6e15821 in __GI__dl_catch_error (objname=0x6286e0, errstring=0x6286e8, mallocedp=0x6286d8, operate=0x7ffff74bbf20 <dlopen_doit>, args=0x7fffffffe030) at dl-error-skeleton.c:198
#10 0x00007ffff74bc579 in _dlerror_run (operate=operate@entry=0x7ffff74bbf20 <dlopen_doit>, args=args@entry=0x7fffffffe030) at dlerror.c:163
#11 0x00007ffff74bc001 in __dlopen (file=file@entry=0x7fffffffe140 "libopenblas64_.so", mode=mode@entry=9) at dlopen.c:87
#12 0x00007ffff771351c in jl_dlopen (filename=filename@entry=0x7fffffffe140 "libopenblas64_.so", flags=flags@entry=68) at /dev/shm/julia/src/dlload.c:88
#13 0x00007ffff77137f9 in jl_load_dynamic_library_ (modname=<optimized out>, flags=<optimized out>, throw_err=0) at /dev/shm/julia/src/dlload.c:189
#14 0x00007fffee754690 in julia_dlopen_e_22619 () at libdl.jl:110
#15 0x00007fffee754871 in julia_vendor_22618 () at linalg/blas.jl:66
#16 0x00007fffee78e9e3 in julia_check_23551 () at linalg/blas.jl:116
#17 0x00007fffee78efbc in julia___init___23550 () at linalg/linalg.jl:284
#18 0x00007fffee78f021 in jlcall___init___23549 () from /dev/shm/julia/usr/lib/julia/sys.so
#19 0x00007ffff76fd2b7 in jl_call_fptr_internal (fptr=<synthetic pointer>, fptr=<synthetic pointer>, nargs=1, args=0x7fffffffe728, meth=<optimized out>) at /dev/shm/julia/src/julia_internal.h:369
#20 jl_call_method_internal (nargs=1, args=0x7fffffffe728, meth=<optimized out>) at /dev/shm/julia/src/julia_internal.h:388
#21 jl_apply_generic (args=args@entry=0x7fffffffe728, nargs=nargs@entry=1) at /dev/shm/julia/src/gf.c:1928
#22 0x00007ffff772e415 in jl_apply (nargs=1, args=0x7fffffffe728) at /dev/shm/julia/src/julia.h:1450
#23 jl_module_run_initializer (m=0x7fffeed637b0 <jl_system_image_data+655536>) at /dev/shm/julia/src/toplevel.c:87
#24 0x00007ffff771613f in _julia_init (rel=<optimized out>) at /dev/shm/julia/src/init.c:733
#25 0x00007ffff771676d in julia_init__threading (rel=<optimized out>) at /dev/shm/julia/src/task.c:297
#26 0x0000000000401637 in main (argc=0, argv=0x7fffffffeb10) at /dev/shm/julia/ui/repl.c:245
(gdb)  c
Continuing.
[New Thread 0x7fffe5988700 (LWP 19364)]
[New Thread 0x7fffe5187700 (LWP 19365)]
[New Thread 0x7fffe0986700 (LWP 19366)]
[New Thread 0x7fffde185700 (LWP 19367)]
[New Thread 0x7fffdd984700 (LWP 19368)]
[New Thread 0x7fffd9183700 (LWP 19369)]
[New Thread 0x7fffd6982700 (LWP 19370)]
[New Thread 0x7fffd6181700 (LWP 19371)]
[New Thread 0x7fffd3980700 (LWP 19372)]
[New Thread 0x7fffd117f700 (LWP 19373)]
[New Thread 0x7fffcc97e700 (LWP 19374)]
[New Thread 0x7fffcc17d700 (LWP 19375)]
[New Thread 0x7fffc997c700 (LWP 19376)]
[New Thread 0x7fffc517b700 (LWP 19377)]
[New Thread 0x7fffc297a700 (LWP 19378)]

Breakpoint 2, __setenv (name=0x7fffef327518 <jl_system_image_data+6700568> "SSL_CERT_FILE", value=0x7fffe9d70398 "/dev/shm/julia/usr/share/julia/cert.pem", replace=1) at setenv.c:253
253        setenv.c: No such file or directory.
(gdb) c
Continuing.

Breakpoint 2, __setenv (name=0x7fffef327538 <jl_system_image_data+6700600> "SSL_CERT_DIR", value=0x7fffe9c983d8 "Cstring(0x", '0' <repeats 16 times>, ")", replace=1) at setenv.c:253
253        in setenv.c
(gdb) c
Continuing.

Breakpoint 2, __setenv (name=0x7fffef3b8888 <jl_system_image_data+7295368> "OPENBLAS_MAIN_FREE", value=0x7fffef3b8868 <jl_system_image_data+7295336> "1", replace=1) at setenv.c:253
253        in setenv.c
(gdb) #0  __setenv (name=0x7fffef3b8888 <jl_system_image_data+7295368> "OPENBLAS_MAIN_FREE", value=0x7fffef3b8868 <jl_system_image_data+7295336> "1", replace=1) at setenv.c:253
#1  0x00007fffee78e78e in julia__setenv_23594 () at env.jl:49
#2  0x00007fffee7966f0 in julia_early_init_23879 () at initdefs.jl:63
#3  0x00007fffee798fef in julia___init___23713 () at sysimg.jl:432
#4  0x00007fffee7990df in jlcall___init___23712 () from /dev/shm/julia/usr/lib/julia/sys.so
#5  0x00007ffff76fd2b7 in jl_call_fptr_internal (fptr=<synthetic pointer>, fptr=<synthetic pointer>, nargs=1, args=0x7fffffffe728, meth=<optimized out>) at /dev/shm/julia/src/julia_internal.h:369
#6  jl_call_method_internal (nargs=1, args=0x7fffffffe728, meth=<optimized out>) at /dev/shm/julia/src/julia_internal.h:388
#7  jl_apply_generic (args=args@entry=0x7fffffffe728, nargs=nargs@entry=1) at /dev/shm/julia/src/gf.c:1928
#8  0x00007ffff772e415 in jl_apply (nargs=1, args=0x7fffffffe728) at /dev/shm/julia/src/julia.h:1450
#9  jl_module_run_initializer (m=0x7fffeecc6170 <jl_system_image_data+10864>) at /dev/shm/julia/src/toplevel.c:87
#10 0x00007ffff771613f in _julia_init (rel=<optimized out>) at /dev/shm/julia/src/init.c:733
#11 0x00007ffff771676d in julia_init__threading (rel=<optimized out>) at /dev/shm/julia/src/task.c:297
#12 0x0000000000401637 in main (argc=0, argv=0x7fffffffeb10) at /dev/shm/julia/ui/repl.c:245
(gdb) 
</pre>

**Pull request closed without merging**
