### PR TITLE
corrected a typo

### PR DESCRIPTION
**Pull request by Sisyphuss**

### CODE REVIEW

**Comment by Keno** [comment]
I believe `contiguous` as used here is actually correct.

**Comment by IainNZ** [comment]
Thanks for the PR @Sisyphuss , but this is [a correct usage of the word](http://en.wikipedia.org/wiki/Contiguity#Computer_science)

**Comment by IainNZ** [comment]
Ah double post!

**Comment by Sisyphuss** [comment]
Ah, thanks @IainNZ . And sorry for my poor English.

**Pull request closed without merging**
