### PR TITLE
Issue https://github.com/JuliaLang/julia/issues/6264 related fixes

### PR DESCRIPTION
**Pull request by jumutc**
I have implemented feature request of https://github.com/JuliaLang/julia/issues/6264

Now we are able to create heterogeneous clusters where some nodes might not be visible to each other and one should initiate an SSH tunnel between them.

One additional bud is fixed which is related to https://github.com/JuliaLang/julia/issues/6256:
1. Execution of `addporcs(n)` fails when some nodes where already added via SSH tunnel.

### CODE REVIEW

**Comment by yjk21** [comment]
Hello,
this feature is quite useful for my infrastructure.
Is there a way for me to include this into a generic binary release? 
I tried to replace the file base/multi.jl with the one from the commit, but it does not seem to work.
Now I cloned the julia source and replaced it there, but its still not done building (also there was a warning on the repository page, that things outside of a official release may be unstable).
Thanks a lot.

**Comment by jumutc** [comment]
I have seen some code improvements in ```multi.jl``` but the feature has to be reimplemented in the latest version of ```julia```. I'm still quite sure that it would be useful when there is a heterogeneous environment in place.

**Comment by yjk21** [comment]
Hi, 
I have found the topology parameter in addprocs() to be useful.
The master_slave topology works in this case, since I have only a simple use case.
I still have some minor glitches that I cannot explain right now, so I'll keep an eye on this.
Unfortunately, I don't think I can be of much assistance, since I am just beginning to understand the language. At least I can offer to test it in my network.

**Comment by amitmurthy** [comment]
Additional security related features in the SSHManager are best done in an external ClusterManager and added to ClusterManagers.jl

**Pull request closed without merging**
