### PR TITLE
add configurable flisp profiling / timing code

### PR DESCRIPTION
**Pull request by vtjnash**
@JeffBezanson thoughts on whether / how we should put this in core?

### CODE REVIEW

**Comment by vtjnash** [comment]
bump

**Comment by vtjnash** [comment]
for example, here's a sample usage for evaluating lowering timings:
```julia
begin
           ccall(:fl_profile, Void, (Cstring,), "julia-expand")
           ccall(:fl_profile, Void, (Cstring,), "julia-expand-macros")
           ccall(:fl_profile, Void, (Cstring,), "julia-expand0")
           ccall(:fl_profile, Void, (Cstring,), "julia-expand1")
           ccall(:fl_profile, Void, (Cstring,), "resolve-scopes")
           ccall(:fl_profile, Void, (Cstring,), "analyze-variables!")
           ccall(:fl_profile, Void, (Cstring,), "closure-convert")
           ccall(:fl_profile, Void, (Cstring,), "linearize")
           ccall(:fl_profile, Void, (Cstring,), "renumber-slots-and-labels")
           ccall(:fl_profile, Void, (Cstring,), "lift-toplevel")
           ccall(:fl_profile, Void, (Cstring,), "map-cl-convert")
           ccall(:fl_profile, Void, (Cstring,), "cl-convert")
           ccall(:fl_profile, Void, (Cstring,), "expr-find-all")
           ccall(:fl_profile, Void, (Cstring,), "lambda-optimize-vars!")
end
ccall(:fl_show_profile, Void, ())
ccall(:fl_clear_profile, Void, ())
```

**Comment by StefanKarpinski** [comment]
Might want to restart the OS X tests?

**Comment by vtjnash** [comment]
would need to rebase to pick up the new .travis file

**Pull request merged**
