### PR TITLE
🤖 [backports-release-1.10] Bump the SHA stdlib from 2d1f84e to 4eee84f

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SHA
URL: https://github.com/JuliaCrypto/SHA.jl.git
Stdlib branch: master
Julia branch: backports-release-1.10
Old commit: 2d1f84e
New commit: 4eee84f
Julia version: 1.10.2
SHA version: 0.7.0(Does not match)
Bump invoked by: @IanButterworth
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaCrypto/SHA.jl/compare/2d1f84e6f8417a1a368de48318640d948b023e7a...4eee84f434590ffa21b551576abc1a6b4d224fc4

```
$ git log --oneline 2d1f84e..4eee84f
4eee84f Bump codecov/codecov-action from 3 to 4 (#104)
15f7dbc Bump codecov/codecov-action from 1 to 3 (#102)
860e6b9 Bump actions/checkout from 2 to 4 (#103)
8e5f0ea Add dependabot to auto update github actions (#100)
4ab324c Merge pull request #98 from fork4jl/sha512-t
a658829 SHA-512: add ref to NIST standard
11a4c73 Apply suggestions from code review
969f867 Merge pull request #97 from fingolfin/mh/Vector
b1401fb SHA-512: add NIST test
4d7091b SHA-512: add to docs
09fef9a SHA-512: test SHA-512/224, SHA-512/256
7201b74 SHA-512: impl SHA-512/224, SHA-512/256
4ab85ad Array -> Vector
8ef91b6 fixed bug in padding for shake, addes testcases for full code coverage (#95)
88e1c83 Remove non-existent property (#75)
068f85d shake128,shake256: fixed typo in export declarations (#93)
176baaa SHA3 xof shake128 and shake256  (#92)
e1af7dd Hardcode doc edit backlink
aaf2df6 [test] fix typo
0f70e8b [test] test `AbstractString` input
335322a [test] test branch in `digest!`
5992826 [test] Testing branch within the `HMAC_CTX` constructor
5e3a676 Protect against re-using digested context
```

### CODE REVIEW

**Comment by IanButterworth** [comment]
@inkydragon we should set up a `release-1.10` branch on SHA. Should the base of that branch be the tip of master, or where this was before 2d1f84e6f8417a1a368de48318640d948b023e7a

**Comment by inkydragon** [comment]
@IanButterworth 
I've set up a new branch `julia-1.10` based on master: https://github.com/JuliaCrypto/SHA.jl/tree/julia-1.10
There is some ambiguity in the branch name `release-1.10`, which implies that this is version 1.10 of SHA.jl, so perhaps it would be better to just call it `julia-1.10`.

----

The new branch is created to pin the version of SHA.jl used by julia 1.10, do I get it correctly?

Next step, considering #54016, would it be a better option to release a new version.

**Comment by IanButterworth** [comment]
Maybe it should be `release-0.7` if that's the version SHA is on. 

It is a bit confusing, but I think the stdlib having branches that match its own versioning makes more sense?

Also if the tip of master is what 1.10.3 should be on because no minor change has been made to SHA, then it's also reasonable to leave it as master and branch if/when it's needed because a new feature is added etc.

**Comment by inkydragon** [comment]
The main branch of SHA.jl does contain some new features, exports some new functions, and should probably be [released as v0.8](https://github.com/JuliaCrypto/SHA.jl/issues/106).

The latest version of the corresponding v0.7 should be [`e1af7dd`](https://github.com/JuliaCrypto/SHA.jl/commit/e1af7dd0863dee14a83550faf4b6e08971993ce8).
However, the CI seems to be having some problems at the moment...

<details>
<summary>CI error msg</summary>

https://github.com/JuliaCrypto/SHA.jl/actions/runs/8656096300/job/23736084703
```
ERROR: LoadError: ArgumentError: Package Logging does not have StyledStrings in its dependencies:
- Note that the following manifests in the load path were resolved with a different
  julia version, which may be the cause of the error:
    /home/runner/work/SHA.jl/SHA.jl/Manifest.toml (vnothing)
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Logging checked out for development and have
  added StyledStrings as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Logging
Stacktrace:
```

</details>

I've created `release-0.7` based on `e1af7dd`: https://github.com/JuliaCrypto/SHA.jl/tree/release-0.7

**Comment by IanButterworth** [comment]
Great. I've updated the branch and commit on https://github.com/JuliaLang/julia/pull/53714

**Pull request closed without merging**
