### PR TITLE
Remove warning for non occurring static parameter in method definition

### PR DESCRIPTION
**Pull request by KristofferC**
These type of exceptions doesn't seem to be catchable with the standard `@test_throws` framework so I just checked the exit status.

### CODE REVIEW

**Comment by yuyichao** [comment]
Didn't we decided to make it not warn at def time?

**Comment by KristofferC** [comment]
I dunno, but I would argue that is a bad decision. Ayway, some discussion at https://github.com/JuliaLang/julia/issues/17319.

**Comment by yuyichao** [comment]
In fact, it was already merged https://github.com/JuliaLang/julia/pull/23117. (I got confused by this PR....).

It seems that the warning should just be removed.

**Comment by KristofferC** [comment]
Aha, ok. Just like this then?

**Comment by KristofferC** [comment]
Hmm, the whole loop can be removed I guess?

**Review by yuyichao — APPROVED** [review]
I think we can remove this warning since it should't cause any crash or confusing behavior anymore. I don't feel too strongly about it if someone really want to keep it though....

**Comment by vtjnash** [comment]
What's the motivation here? I understand that we current don't warn for functions like:
```julia
f() = (local x; 2)
```
which declares a variable `x`, but never assigns it. But seems generally useful anyways?

**Comment by yuyichao** [comment]
A default on warning for something that's not clearly wrong is really annoy.
If it's going to cause crash or is always wrong, a warning or error is fine (and an error is better since both needs to be fixed and an error is more clear and easier to fine).
Otherwise, there should be no warning or errors.
Since we are moving towards allowing this it seems that removing this warning is appropriate.

**Comment by JeffBezanson** [comment]
I think the two reasons for this warning were (1) the method being un-callable was a gotcha, which has been fixed, and (2) you might write `Complex{Float64}(x) = ...` thinking it defined a constructor for `Complex{Float64}` when it actually introduced an unused static parameter. That syntax is deprecated. So I agree there don't seem to be good reasons left for this warning.

**Pull request merged**
