### PR TITLE
added 7 dimensional cross product

### PR DESCRIPTION
**Pull request by adamnemecek**
It's a nice to have.

### CODE REVIEW

**Comment by adamnemecek** [comment]
What should be my next steps?

**Comment by ararslan** [comment]
I would:
* Add tests to ensure correctness. You can use the existing tests for 3-vectors as a guideline.
* Amend the docstring for `cross` to mention that it can handle vectors with 7 values.
* Add a compatibility note in the docstring mentioning that 7-vectors require Julia 1.3. (Check out other docstrings with `!!!compat` in them as a guide.)
* Add an entry in the LinearAlgebra section of NEWS.md mentioning this change.

Also: Welcome, and thanks for the contribution!

**Comment by stevengj** [comment]
This is neat, but would anyone use this in practice?  I hesitate to merge code unless there is a realistic application in mind.

**Comment by adamnemecek** [comment]
@ararslan I'll add the things in a couple of days.

@stevengj Cross product is defined only in 3 and 7 dimensions. I know it's weird. 
https://en.wikipedia.org/wiki/Seven-dimensional_cross_product

**Comment by ViralBShah** [comment]
I wonder if this is better to put into a package. (I wonder which one).

**Comment by stevengj** [comment]
@adamnemecek, I know that.  But just because it *can* be defined in 7 dimensions doesn't automatically mean that we should include the code — it depends on whether it is *useful*.

The 3-dimensional cross-product is useful because we live in 3 dimensions and so lots of people do computations with this product in practice.   On the other hand, any code that wants to handle 7 dimensions probably is either

1. using octonions, in which case they should just use an octonion type from https://github.com/JuliaGeometry/Quaternions.jl

2. needs to handle any number of dimensions, in which case they shouldn't use cross products at all and must frame their algorithms in terms of bivectors or similar.

**Comment by adamnemecek** [comment]
@ViralBShah I thought about that but there's no way to overload a function based on array size. 

@stevengj You are correct, I'd like to use it for implementation of octonions. However I need a custom octonion implementation for one reason or another. I still feel like it makes sense to add 7 dim cross product, just for the sake of completeness.

**Comment by thofma** [comment]
Since it is not unique, why choose this one?

**Comment by adamnemecek** [comment]
What not unique.

**Comment by thofma** [comment]
There is not "the" seven dimensional cross product.

**Comment by StefanKarpinski** [comment]
https://en.wikipedia.org/wiki/Seven-dimensional_cross_product:

> while the three-dimensional cross product is unique up to a sign, there are many seven-dimensional cross products

**Comment by adamnemecek** [comment]
OK if someone needs a different one they can deal with that. This one is more commonly used than the others.

**Comment by StefanKarpinski** [comment]
Do you have a reference for that?

**Comment by adamnemecek** [comment]
Is it going to change things If I provide a different one?

**Comment by StefanKarpinski** [comment]
It might. If there's one unique preferred cross product in seven dimensions, then that's a decent argument for "well, we might as well have it compute that". For three dimensions, there are two cross products that differ only by sign, and one of those is the standard by convention. I know squat about seven dimensional cross products, but from reading that wikipedia page, the non-uniqueness makes me very reluctant to bake an arbitrary choice in that may or may not be standard. If you can make a convincing case that it is actually standard, that's much more compelling.

**Comment by adamnemecek** [comment]
The implementation I went with is the one from wiki. I can take the one from the julia implementation of octonions. I think it makes sense to pick one and be consistent.

**Comment by thofma** [comment]
The wikipedia page gives at least two different definitions.

**Comment by adamnemecek** [comment]
Do you like any of the other ones better?

**Comment by thofma** [comment]
In any case the docstring needs to explain clearly which cross product is given. I don't know what the most compact form would be. Multiplication table?

**Comment by adamnemecek** [comment]
OK, I'll add a docstring if I know this will get merged once it's polished.

**Comment by StefanKarpinski** [comment]
> I think it makes sense to pick one and be consistent.

I'm afraid that's not how it works in the core language. We are not trying to be difficult or argumentative here—by accepting an API in the language, we are committing to it essentially forever. You may well forget about this PR or that you ever worked with seven dimensional cross products in a few years, but I'll be here answering questions about why we chose to implement this particular cross product for decades to come. Before more work is put into this, it should be determined whether there is one standard cross product that it makes sense to bake into the language forever. If not, then this definition belongs in a package which has much more leeway to be opinionated since people can choose which packages they use.

**Comment by adamnemecek** [comment]
Imma close it.

**Comment by stevengj** [comment]
> However I need a custom octonion implementation for one reason or another

If there is something wrong with the type in Quaternions.jl please file an issue there or make a PR.

**Comment by adamnemecek** [comment]
Nothing is wrong with it, I'm trying to implement some clifford algebras and I'd like to able to declare say dual sedenions by composing already existing types.

**Comment by ViralBShah** [comment]
Thank you for the PR. I definitely learnt something new here!

**Pull request closed without merging**
