### PR TITLE
Revert "RFC: prettier IR-show for line number and inlining information"

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Reverts JuliaLang/julia#28390

### CODE REVIEW

**Comment by vtjnash** [comment]
Why?

**Comment by mbauman** [comment]
In #28390 in response to your merge:

> I extremely much prefer the old printing. Please bring that back with an option or something. I can't use this at all.

> Yeah, I'm sorry, but this printing just looks messy. It's great if I care about the line information, but near useless if I want to actually look at the code:

> Just merging this despite all the objections…

I agree. I loved the previous `@code_typed` output.  I had _already_ found the line info comments in LLVM IR and native ASM to be far too verbose to be helpful… and we've talked about it on Slack.  Do you really find the pushback here surprising?

**Comment by StefanKarpinski** [comment]
Because you merged it without getting consensus or addressing the many objections to the change. That's not acceptable and immediate reversion is the appropriate response.

**Comment by KristofferC** [comment]
There seem to be two main purposes to use these macros. One is where you want to get an overview of what the code actually end up doing. And another when you want to pinpoint exactly where in the source code a specific instruction came from. I typically use it for the first purpose where these verbose line annotations is mostly noise. So some option flag to toggle between these two modes might be suitable.

And as a reference, when looking at code_warntype, I typically paste it into an editor and use some regex filtering to remove all line annotations.

**Comment by jrevels** [comment]
I can understand why others feel it's too verbose by default, but I find the verbose pretty-printing really useful for my purposes (which are probably similar to Jameson's). 

Is it possible that instead of reverting this entirely, we can hide the additional verbosity behind a flag or something? It makes debugging things via looking at the IR way easier IMO.

**Comment by KristofferC** [comment]
That is the wrong order. The correct order is to revert this and then the author makes a new PR that adds that verbosity option.

**Comment by vtjnash** [comment]
The verbosity option is already present (`Base.IRShow.lineinfo_disabled`), it just needs a name. There's actually several configuration options that got added here, so that people could experiment further—I just opted not to expose any of them initially (they're listed as hard-coded constants right now in the source code, until we got a feel for which would be most useful).

**Comment by vtjnash** [comment]
> All the code introspection tools need to be switched back to reasonably concise, readable output by default

OK, so what you're saying is that we should go back to the v0.6 level of information in printing?

**Pull request merged**
