### PR TITLE
Update Windows icon and NSIS banner

### PR DESCRIPTION
**Pull request by musm**
part of https://github.com/JuliaLang/julia/pull/32038

It looks like the old icon had a smaller size, updating it now looks much better.

### CODE REVIEW

**Comment by musm** [comment]
I'm not sure why but the  julia exe files are still using the  old  icons even after updating them. It might have something to the with the being embedded in  7zS.sfx ?  the julia.rc file specifies the icon as `julia.ico` which is the same folder as the `julia.rc` file so I don't know why it is not picking it up.

**Comment by StefanKarpinski** [comment]
Thanks for polishing this!

**Comment by musm** [comment]
Fixed up the actual 7z stage of the  installer icon, it needed manual modification using resource hacker.

@vtjnash  do you by any chance know why the actual `julia.exe` is not picking up the `julia.ico` changes? My understanding was that `julia.rc` is involved.  https://github.com/JuliaLang/julia/blob/master/contrib/windows/julia.rc#L34

**Comment by musm** [comment]
So what I think was happening was that the resource file defined the same number for VERSIONINFO  and  ICON 
https://github.com/JuliaLang/julia/blob/1d4b25e803cbb8fa674bbcd84845f7fc416a820e/contrib/windows/julia.rc#L3 https://github.com/JuliaLang/julia/blob/1d4b25e803cbb8fa674bbcd84845f7fc416a820e/contrib/windows/julia.rc#L34

changing the resource number for ICON to 101 (the number is arbitrary and doesn't matter unless it is referenced), seems to fix the clash and now builds properly update the icons to the new ones.

I'm not sure if it was some strange luck that the current version works. It could be related to the sizes of the  master ico  and the updated ico (which have defined more sizes in them)


Compare the new one to the old one in the figure below
image

**Comment by vtjnash** [comment]
I assume it's just because you modified the file so it rebuilt. There's no conflict, so it'll just pick up the lowest number in each group (1, 24, and 101; or it could have been 1, 1, and 1)

**Comment by musm** [comment]
I don't think so? I deleted my icon cache and I made sure to `distclean` and built from scratch, but it still persisted, before renumbering.

**Comment by musm** [comment]
Seems like you were right.... It's pretty annoying to mess around with icons since things don't always refresh properly...

**Comment by musm** [comment]
I fixed up a very subtle scaling issue  (@cormullion the julia-dots.svg isn't perfectly square and there is some space even around the widest dots, I trimmed that space and made it a perfect square, which fixed the scaling in the creation of the ico files)

**Comment by musm** [comment]
FYI this is good to go on my end

**Comment by musm** [comment]
merge?

**Comment by KristofferC** [comment]
Is the `Title` change and the `ShowUninstDetails` change part of the icon change?

**Comment by ViralBShah** [comment]
I believe they are part of the NSIS banner change which we discussed elsewhere. Let's go ahead with this.

**Comment by musm** [comment]
Yeah it's not entirely related to the branding update. The showuninst improves consistency with the installer and the name change actually has no impact due to the 7zSFX module used is outdated, but I changed it anyways if it gets updated.

**Pull request merged**
