### PR TITLE
Breaking change, but minor(?) for countlines()

### PR DESCRIPTION
**Pull request by PallHaraldsson**
I'm not sure this is the right place to put this. Didn't notice a section on breaking changes. Linked issue, has different title, but its second commit is on this, to docs. Should you not link issues, not that directly? I didn't find another correct issue number. Countlines has parameters, e.g. for the new, for empty lines. Should all (or any) be listed?

### CODE REVIEW

**Comment by pao** [comment]
...continuing from the other issue, as you may have figured out: putting `[ci skip]` in the issue title is ineffective. :D

**Comment by lostanlen** [comment]
Why should you put commas before and after the words "non-empty lines" ?

**Comment by PallHaraldsson** [comment]
The commas may be overkill or just plain wrong here..

Is this correct: "now also counts non-empty lines, by default"?

with one comma looked wrong to me but maybe isn't.. Similarly, I would say "By default, countlines() counts non-empty-lines".

English (and my native language) use fewer commas than previously (was taught, when I was young..), but I think you are still allowed to use more, just a preference.

If you want "now also counts non-empty lines by default", I think I can change the commit that way.

I' a little confused by:

ARCH="x86_64"

in the Travis CI build fail.

**Comment by KristofferC** [comment]
The Travis CI failure is due to running out of memory and it has nothing to do with your change.

I am also not a native speaker but for me it sounds best with no commas.

**Comment by PallHaraldsson** [comment]
Thanks, I see this was added, but to be useful to people should it be added to v0.4.0-rc2? I think (as with similar situations), stuff only committed to master will not show up in 0.4.0* end the eventual released 0.4.0(?).

**Comment by tkelman** [comment]
it was backported here ddee1038e3c3c2ff6dee4fcf1e45fe29ee7fcbc6 and will be in rc3

**Pull request closed without merging**
