### PR TITLE
Make `@deprecate_binding` work with `--depwarn` cmdline flags

### PR DESCRIPTION
**Pull request by jakebolewski**
Adds tests for `--depwarn` and `@deprecate_binding`. 

cc @tkelman

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Nice, thanks.

**Comment by tkelman** [comment]
awesome. note to self to also backport 184c56b1eb8bf1d6a062a5dba49a278ad10a5ecc with this

**Comment by jakebolewski** [comment]
Does Appveyor just time out after 40 minutes?

**Comment by tkelman** [comment]
redirection hang, maybe same as #12519

**Comment by tkelman** [comment]
Since we should try to get this backported for RC3, unless someone has a great idea for how to fix the redirection bug on Windows I propose making the tests unix-only for now with a FIXME comment.

**Comment by tkelman** [comment]
Ping. This is needed for RC3. Do you have time to implement my suggestion, or need someone else to do it?

**Comment by jakebolewski** [comment]
done

**Comment by tkelman** [comment]
You didn't add a FIXME comment, which is an important thing to put in for hacks like these otherwise we'll never remember why things are running conditionally - I had done ae5452a509908a1886de50864580a8d36738a337 but your version at least runs some of the tests.

**Comment by jakebolewski** [comment]
go ahead

**Comment by KristofferC** [comment]
Will this also make deprecation's only print once for each deprecation like for functions? Right now, it feels that whatever command I run from an external package i get 10 pages of deprecation warnings.

**Comment by JeffBezanson** [comment]
Bump. Ready to merge?

**Pull request merged**
