### PR TITLE
[RFC] Add argmin and argmax over given dimensions

### PR DESCRIPTION
**Pull request by ghost**
This is a common operation for batched Machine Learning operations, it also brings us on par with NumPy and friends when it comes to their `argmin` and `argmax`.

Bonus commit: A tiny typo in a comment.

### CODE REVIEW

**Comment by ninjin** [comment]
Travis i686 failure appears unrelated.

**Comment by ninjin** [comment]
Rebased and resolved merge conflicts.

**Review by mbauman — APPROVED** [review]
Looks good and seems worthwhile.  We can always add the optimization to avoid allocating the values array later.

**Comment by ViralBShah** [comment]
I'm killing the CI until we can get the alpha tagged.

**Comment by ninjin** [comment]
Got it, rebased to kick the CI into gear now that the alpha is tagged.

**Comment by ninjin** [comment]
AppVeyor timed out due to maximum build time, all other CI was fine.

**Pull request merged**
