### PR TITLE
fix #10950 (UnitRange(1//2,3) bug)

### LINKED ISSUE #10950: UnitRange{Rational} misbehaves
```julia
julia> rg = 1//2:3
1//2:3//1

julia> length(rg)
ERROR: InexactError()
 in call at base.jl:38
 in length at range.jl:191

julia> for x in rg println(x) end
1//2
3//2
5//2
7//2
9//2
11//2
... (does not end)
```

I guess this should work if we adjust the endpoint on construction?

### PR DESCRIPTION
**Pull request by nolta**

### CODE REVIEW

**Comment by simonster** [comment]
lgtm

**Comment by tkelman** [comment]
Hm, the `UnitRange` constructor has changed a few times since release-0.3. #10950 exists there too, but I'm not sure whether 275564e661fa8d483b2da7d9b502b4c6ae8c2b8a and fb342cb52390170942bb471a62121e90337b41ce are safe to backport. Thoughts? @JeffBezanson if you've got a minute, those were both by you.

**Comment by tkelman** [comment]
Bump. Would like to tag 0.3.9 within a few days, this is the only thing on my list that might be ready for backporting before then.

**Comment by JeffBezanson** [comment]
Yes those both look safe to backport.

**Comment by tkelman** [comment]
Yikes, maybe not...
```
string.jl
error during bootstrap: LoadError(at "sysimg.jl" line 81: LoadError(at "string.jl" line 1676: ErrorException("box: argument is of incorrect size")))
```

**Pull request merged**
