### PR TITLE
new LLVM optimization pass list

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a rough cut of some possible changes to our pass list, that should run a bit faster and possibly even produce better code. There is some inline commentary that will be removed, and just reflects some notes from a discussion with an LLVM developer. Several variations are possible, but I'm curious to try some benchmarks first. This does make the build a bit faster, and reduces time-to-first-plot by about 4-5%.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34940) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/8f4e4d5f08b0e9ded4d130596875d100286fc46b/0ea914c_vs_966a9b9/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
So some of the regressions were caused by moving IndVarSimplify and removing the second LoopDeletion. I put those back. I'll also try replacing the internal InstCombines with InstSimplify, which is much faster. Passing `false` to InstCombine to disable "expensive" combines does not provide any real speedup.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by JeffBezanson** [comment]
With this pass list time-to-first-plot is ~8% faster instead of ~4% (due to using InstSimplify).

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34940#issuecomment-593148832) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b921461974f03fcd42967f13fbb599bba26c8bd1/4456a0d_vs_c2ce8f6/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
Ok, one of those InstCombines was important for vectorizing loops over Union arrays. Let's put that back and try again.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34940#issuecomment-593564685) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/152a422ed878a2313d3b88d3e2d1bd4c36ee85b1/d9f893e_vs_5b241c2/report.md). cc @ararslan

**Comment by JeffBezanson** [comment]
That's starting to look pretty good. We may have a solid candidate here.

**Comment by JeffBezanson** [comment]
Ok, @Keno @vtjnash and I went over this and we think it's ready to go.

**Pull request merged**
