### PR TITLE
make explicit that xvf is flag on tar

### PR DESCRIPTION
**Pull request by LOAS2**
Same as https://github.com/JuliaLang/julia/pull/18426 but for the remaining ones.

### CODE REVIEW

**Comment by staticfloat** [comment]
I just tested `tar zxv` on CentOS 5, OSX 10.10, Ubuntu 14.04, and my OpenWRT router.  I think we're good for this change.

**Review by staticfloat — APPROVED** [review]

**Comment by tkelman** [comment]
sorry for the slightly OT question, but does suckless tar have its own bzip2 implementation for `-j` ?

**Comment by LOAS2** [comment]
The manpage -

```
TAR(1)                      General Commands Manual                     TAR(1)

NAME
     tar – create, list or extract a tape archive

SYNOPSIS
     tar [-C dir] [-J | -Z | -a | -j | -z] -x [-m | -t] [-f file] [file ...]
     tar [-C dir] [-J | -Z | -a | -j | -z] [-h] -c path ... [-f file]

DESCRIPTION
     tar is the standard file archiver.

OPTIONS
     -c path ...
             Create archive from path.

     -C dir  Change directory to dir before beginning.

     -f file
             Set file as input | output archive instead of stdin | stdout. If
             '-', stdin | stdout is used.

     -m      Do not preserve modification time.

     -t      List all files in the archive.

     -x      Extract archive.

     -h      Always dereference symbolic links while recursively traversing
             directories.

     -J | -Z | -a | -j | -z
             Use xz | compress | lzma | bzip2 | gzip compression or
             decompression. These utilities must be installed separately.
             Using these flags is discouraged in favour of the flexibility and
             clarity of pipes:

                   $ bzip2 -cd archive.tar.bz2 | tar -x
                   $ gzip -cd archive.tar.gz | tar -x

                   $ tar -c file ... | bzip2 > archive.tar.bz2
                   $ tar -c file ... | gzip2 > archive.tar.gz

SEE ALSO
     ar(1), bzip2(1), gzip(1)

STANDARDS
     The tar utility is compliant with the UStar (Uniform Standard Tape
     ARchive) format defined in the IEEE Std 1003.1-1988 (“POSIX.1”)
     specification.

sbase                             2015-10-08                             sbase
```

**Comment by LOAS2** [comment]
It looks that suckless doesn't have its own compression algorithms yet.
They want to have their own versions, simpler and that sucks less.
You find this information in the thread http://lists.suckless.org/dev/1409/23635.html on their mailing list, read the replies too.
For now they also recommend some compression algorithms (third-party) http://suckless.org/rocks
It's my hope this answers your question. Can I ask why you made it :) ? Interested in suckless?

**Comment by tkelman** [comment]
Yes, I think sbase is really neat. It's like an MIT licensed version of busybox but with a simpler build system than toybox. I've even built it for cygwin before and tested that it works for what we currently use busybox-w32 for in our tests. At some point we'll probably start shipping cygwin1.dll, sbase, and mintty in the windows binaries of julia, now that cygwin1.dll is LGPL.

**Pull request merged**
