### PR TITLE
[stdlib/jll] Automatic include of all `*.version` makefile

### PR DESCRIPTION
**Pull request by inkydragon**
> we don't have to update manually here (`all_jlls.version`) in the future
>
> _Originally posted by `@ViralBShah` in https://github.com/JuliaLang/julia/pull/45720#discussion_r901151732_

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano Do you recollect why utf8proc, libwhich and patchelf don't have JLLs? I see some Yggdrasil PRs for utf8proc recently, but perhaps the other two have issues with cross-compilation?

**Comment by giordano** [comment]
I don't think any of those are runtime dependencies of Julia

**Comment by giordano** [comment]
BTW, we do have [`Patchelf_jll.jl`](https://github.com/JuliaBinaryWrappers/Patchelf_jll.jl), but not libwhich (probably because no one needed it badly enough).  I though the question was why we don't have these as JLL stdlibs bundled in Julia, to which the answer is what I wrote above.

**Comment by ViralBShah** [comment]
Would downloading these from Yggdrasil just makes all the dependency management process uniform, even if only compile time?

**Pull request merged**
