### PR TITLE
parse `let` the same as `for`. part of #21774

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by ararslan** [comment]
Purely out of curiosity, could you provide an example of a situation in which this is breaking?

**Comment by JeffBezanson** [comment]
Only breaking for macros.

**Comment by vtjnash** [comment]
Looks like the deprecation still needs to be implemented? But otherwise, I have no objections.

**Comment by JeffBezanson** [comment]
Unfortunately I'm not sure it's possible to distinguish the two forms in all cases. Some cases can be reliably deprecated though.

**Pull request merged**
