### PR TITLE
fix keyword example to be runable in x86 also

### PR DESCRIPTION
**Pull request by DrKrar**
replace `Int64` by the Architecture independent `Int`

### CODE REVIEW

**Comment by Keno** [comment]
`Int64` does exist on 32bit architectures as well.

**Comment by DrKrar** [comment]
> Int64 does exist on 32bit architectures as well.

the problem here not that we can't define an `Int64`  on 32bit architectures. the problem is that by default literal like 1 will be treated as  `Int32` . this will yield an error.

**Comment by StefanKarpinski** [comment]
@keno, the point is that this example will not be callable on 32-bit architectures. If we change the example to use `Int32` and try it on a 64-bit system, the problem becomes evident:

```jl
julia> f(; x::Int32=1) = x
f (generic function with 1 method)

julia> f()
ERROR: MethodError: no method matching #f#1(::Int64, ::#f)
Closest candidates are:
  #f#1(::Int32, ::Any) at REPL[7]:1
Stacktrace:
 [1] f() at ./REPL[7]:1

julia> f(x=1)
ERROR: TypeError: #f: in typeassert, expected Int32, got Int64
Stacktrace:
 [1] (::#kw##f)(::Array{Any,1}, ::#f) at ./<missing>:0
```

**Comment by DrKrar** [comment]
@StefanKarpinski you get the point.
the literal inferred type is  architecture dependent so should be the type assertion or it will not  wok on every word length.

**Comment by Keno** [comment]
Right, sorry, I forgot about the default.

**Pull request merged**
