### PR TITLE
simplify generated code for `@kwdef`

### PR DESCRIPTION
**Pull request by oscardssmith**
this makes the generated code a lot simpler. No major performance difference.

### CODE REVIEW

**Comment by simeonschaub** [comment]
What is the actual goal here? If anything, this seems to slightly complicate the current code

**Comment by sjkelly** [comment]
Would be good to show the before and after `@code_typed` because that is the real simplification here. Also I thought we had a marginal inference time improvement as well?

**Comment by oscardssmith** [comment]
For the following code
```
@kwdef struct x
     var1::Union{Int, Float64} = 1
     var2::Union{Int, Float64} = 1
     var3::Union{Int, Float64} = 1
     var4::Union{Int, Float64} = 1
     var5::Union{Int, Float64} = 1
     var6::Union{Int, Float64} = 1
     var7::Union{Int, Float64} = 1
     var8::Union{Int, Float64} = 1
     var9::Union{Int, Float64} = 1
     var10::Union{Int, Float64} = 1
     var11::Union{Int, Float64} = 1
     var12::Union{Int, Float64} = 1
     var13::Union{Int, Float64} = 1
     var14::Union{Int, Float64} = 1
     var15::Union{Int, Float64} = 1
     var16::Union{Int, Float64} = 1
     var17::Union{Int, Float64} = 1
     var18::Union{Int, Float64} = 1
     var19::Union{Int, Float64} = 1
     var20::Union{Int, Float64} = 1
     var21::Union{Int, Float64} = 1
     var22::Union{Int, Float64} = 1
     var23::Union{Int, Float64} = 1
     var24::Union{Int, Float64} = 1
     var25::Union{Int, Float64} = 1
     var26::Union{Int, Float64} = 1
     var27::Union{Int, Float64} = 1
     var28::Union{Int, Float64} = 1
     var29::Union{Int, Float64} = 1
     var30::Union{Int, Float64} = 1
     var31::Union{Int, Float64} = 1
     var32::Union{Int, Float64} = 1
     var33::Union{Int, Float64} = 1
     var34::Union{Int, Float64} = 1
     var35::Union{Int, Float64} = 1
     var36::Union{Int, Float64} = 1
     var37::Union{Int, Float64} = 1
     var38::Union{Int, Float64} = 1
     var39::Union{Int, Float64} = 1
     var40::Union{Int, Float64} = 1
     var41::Union{Int, Float64} = 1
     var42::Union{Int, Float64} = 1
     var43::Union{Int, Float64} = 1
     var44::Union{Int, Float64} = 1
     var45::Union{Int, Float64} = 1
     var46::Union{Int, Float64} = 1
     var47::Union{Int, Float64} = 1
     var48::Union{Int, Float64} = 1
     var49::Union{Int, Float64} = 1
     var50::Union{Int, Float64} = 1
end
@code_typed x(var10=3)
```
master gives,
```
CodeInfo(
1 ───        goto #3 if not false
2 ───        nothing::Nothing
3 ┄── %3   = π (1, Int64)
└────        goto #5 if not false
4 ───        nothing::Nothing
5 ┄── %6   = π (1, Int64)
└────        goto #7 if not false
6 ───        nothing::Nothing
7 ┄── %9   = π (1, Int64)
└────        goto #9 if not false
8 ───        nothing::Nothing
9 ┄── %12  = π (1, Int64)
└────        goto #11 if not false
10 ──        nothing::Nothing
11 ┄─ %15  = π (1, Int64)
└────        goto #13 if not false
12 ──        nothing::Nothing
13 ┄─ %18  = π (1, Int64)
└────        goto #15 if not false
14 ──        nothing::Nothing
15 ┄─ %21  = π (1, Int64)
└────        goto #17 if not false
16 ──        nothing::Nothing
17 ┄─ %24  = π (1, Int64)
└────        goto #19 if not false
18 ──        nothing::Nothing
19 ┄─ %27  = π (1, Int64)
│     %28  = Base.getfield(@_2, :var10)::Int64
└────        goto #21 if not false
20 ──        nothing::Nothing
21 ┄─ %31  = π (1, Int64)
└────        goto #23 if not false
22 ──        nothing::Nothing
23 ┄─ %34  = π (1, Int64)
└────        goto #25 if not false
24 ──        nothing::Nothing
25 ┄─ %37  = π (1, Int64)
└────        goto #27 if not false
26 ──        nothing::Nothing
27 ┄─ %40  = π (1, Int64)
└────        goto #29 if not false
28 ──        nothing::Nothing
29 ┄─ %43  = π (1, Int64)
└────        goto #31 if not false
30 ──        nothing::Nothing
31 ┄─ %46  = π (1, Int64)
└────        goto #33 if not false
32 ──        nothing::Nothing
33 ┄─ %49  = π (1, Int64)
└────        goto #35 if not false
34 ──        nothing::Nothing
35 ┄─ %52  = π (1, Int64)
└────        goto #37 if not false
36 ──        nothing::Nothing
37 ┄─ %55  = π (1, Int64)
└────        goto #39 if not false
38 ──        nothing::Nothing
39 ┄─ %58  = π (1, Int64)
└────        goto #41 if not false
40 ──        nothing::Nothing
41 ┄─ %61  = π (1, Int64)
└────        goto #43 if not false
42 ──        nothing::Nothing
43 ┄─ %64  = π (1, Int64)
└────        goto #45 if not false
44 ──        nothing::Nothing
45 ┄─ %67  = π (1, Int64)
└────        goto #47 if not false
46 ──        nothing::Nothing
47 ┄─ %70  = π (1, Int64)
└────        goto #49 if not false
48 ──        nothing::Nothing
49 ┄─ %73  = π (1, Int64)
└────        goto #51 if not false
50 ──        nothing::Nothing
51 ┄─ %76  = π (1, Int64)
└────        goto #53 if not false
52 ──        nothing::Nothing
53 ┄─ %79  = π (1, Int64)
└────        goto #55 if not false
54 ──        nothing::Nothing
55 ┄─ %82  = π (1, Int64)
└────        goto #57 if not false
56 ──        nothing::Nothing
57 ┄─ %85  = π (1, Int64)
└────        goto #59 if not false
58 ──        nothing::Nothing
59 ┄─ %88  = π (1, Int64)
└────        goto #61 if not false
60 ──        nothing::Nothing
61 ┄─ %91  = π (1, Int64)
└────        goto #63 if not false
62 ──        nothing::Nothing
63 ┄─ %94  = π (1, Int64)
└────        goto #65 if not false
64 ──        nothing::Nothing
65 ┄─ %97  = π (1, Int64)
└────        goto #67 if not false
66 ──        nothing::Nothing
67 ┄─ %100 = π (1, Int64)
└────        goto #69 if not false
68 ──        nothing::Nothing
69 ┄─ %103 = π (1, Int64)
└────        goto #71 if not false
70 ──        nothing::Nothing
71 ┄─ %106 = π (1, Int64)
└────        goto #73 if not false
72 ──        nothing::Nothing
73 ┄─ %109 = π (1, Int64)
└────        goto #75 if not false
74 ──        nothing::Nothing
75 ┄─ %112 = π (1, Int64)
└────        goto #77 if not false
76 ──        nothing::Nothing
77 ┄─ %115 = π (1, Int64)
└────        goto #79 if not false
78 ──        nothing::Nothing
79 ┄─ %118 = π (1, Int64)
└────        goto #81 if not false
80 ──        nothing::Nothing
81 ┄─ %121 = π (1, Int64)
└────        goto #83 if not false
82 ──        nothing::Nothing
83 ┄─ %124 = π (1, Int64)
└────        goto #85 if not false
84 ──        nothing::Nothing
85 ┄─ %127 = π (1, Int64)
└────        goto #87 if not false
86 ──        nothing::Nothing
87 ┄─ %130 = π (1, Int64)
└────        goto #89 if not false
88 ──        nothing::Nothing
89 ┄─ %133 = π (1, Int64)
└────        goto #91 if not false
90 ──        nothing::Nothing
91 ┄─ %136 = π (1, Int64)
└────        goto #93 if not false
92 ──        nothing::Nothing
93 ┄─ %139 = π (1, Int64)
└────        goto #95 if not false
94 ──        nothing::Nothing
95 ┄─ %142 = π (1, Int64)
└────        goto #97 if not false
96 ──        nothing::Nothing
97 ┄─ %145 = π (1, Int64)
└────        goto #99 if not false
98 ──        nothing::Nothing
99 ┄─ %148 = π (1, Int64)
│     %149 = Base.sle_int(1, 1)::Bool
└────        goto #101 if not %149
100 ─ %151 = Base.sle_int(1, 0)::Bool
└────        goto #102
101 ─        nothing::Nothing
102 ┄ %154 = φ (#100 => %151, #101 => false)::Bool
└────        goto #104 if not %154
103 ─        invoke Base.getindex(()::Tuple, 1::Int64)::Union{}
└────        unreachable
104 ─        Base.nothing::Nothing
└────        goto #105
105 ─        goto #106
106 ─        goto #107
107 ─        goto #108
108 ─        nothing::Nothing
│     %164 = %new(Main.x2, %3, %6, %9, %12, %15, %18, %21, %24, %27, %28, %31, %34, %37, %40, %43, %46, %49, %52, %55, %58, %61, %64, %67, %70, %73, %76, %79, %82, %85, %88, %91, %94, %97, %100, %103, %106, %109, %112, %115, %118, %121, %124, %127, %130, %133, %136, %139, %142, %145, %148)::x
└────        return %164
) => x2
```
but the PR gives
```
CodeInfo(
1 ─ %1 = Base.getfield(@_2, :var12)::Int64
│   %2 = %new(Main.x, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  %1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, )::x
└──      return %2
) => x
```

**Comment by JeffBezanson** [comment]
I think this will no longer error if unsupported keywords are passed? Also, if this is a good idea, then we can change all keyword argument methods to use `get` instead of `if` statements in julia-syntax.scm.

**Comment by JeffBezanson** [comment]
Oh wait won't this also evaluate all the default expressions unconditionally? We don't want to do that.

**Comment by JeffBezanson** [comment]
Or maybe even better, if the default expr is a literal, use `ifelse` and `isdefined` instead of a branch or `get` or `haskey` to avoid inferring those methods.

**Comment by JeffBezanson** [comment]
OK I think #44333 has everything we can reasonably do here.

**Pull request closed without merging**
