### PR TITLE
Add 👍 and 👎 for constructing ranges

### PR DESCRIPTION
**Pull request by ararslan**
When people don't code quote their ranges, markdown will render a specified step size as :+1: or :-1:. It does what you want, so why not make it syntax? This PR adds :+1: for a range with positive unit step size and :-1: for a range with negative unit step size.

### CODE REVIEW

**Comment by matbesancon** [comment]
I love it, finally a syntax proposal that will help beginners

**Review by mkitti — APPROVED** [review]
This will make Julia easier to use for emoji oriented users, opening Julia to a new generation.

**Comment by Wikunia** [comment]
Why not add 📈 and 📉 for randomly increasing and decreasing ranges?

**Comment by StefanKarpinski** [comment]
Even though this is a joke (I think I can give that away now that it's April 2nd), I can't see much actual harm in doing it. You can still use 👍 and 👎 as identifiers if you want to, they just _also_ parse as infix operators like the word `in`. It also doesn't prevent them from being used in longer identifiers, just as `in` being an infix operator doesn't prevent `sin` or `int` from being identifiers. So: cute easter egg? Plus kind of a fun range syntax?

**Comment by simeonschaub** [comment]
Would be slightly breaking for identifiers containing :+1:, but looks like we're fine on that front: https://juliahub.com/ui/RepoSearch?q=%F0%9F%91%8D&r=true

**Comment by StefanKarpinski** [comment]
> Would be slightly breaking for identifiers containing 👍

Why? I haven't looked it this PR currently breaks that but it's perfectly possible to allow 👍 in identifiers but make 👍 by itself an infix operator. (This is why I used `in` as my point of comparison.)

**Comment by simeonschaub** [comment]
We don't require whitespace around operators, so `a👍b` is currently a valid identifier, while it would parse as `👍(a, b)` with this PR.

**Comment by ararslan** [comment]
I should note that space _is_ required around :+1: and :-1: with this PR, since otherwise `1👍2` parses as `1 * 👍2`.

> We don't require whitespace around operators

Not entirely true: `1in2` also parses as `1 * in2`.

**Comment by simeonschaub** [comment]
Ah, sorry, I didn't read the PR closely enough then

**Comment by JeffBezanson** [comment]
Closing as "surprisingly plausible, but still a bit ... much".

**Pull request closed without merging**
