### PR TITLE
add small clarification to noinline macro

### LINKED ISSUE #19418: @noinline ignored
It looks like Julia 0.6 ignores `@noinline` in the following snippet:

```julia
@noinline bar() = 1
function foo()
    bar()
end
@code_typed(foo())
```

Julia Version 0.5.0-dev+2349
Commit cf93d6f* (2016-01-29 02:19 UTC):
```
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[]], :(begin  # In[1], line 3:
        return (Main.bar)()::Int64
    end::Int64))))
```

Julia Version 0.6.0-dev.1297
Commit 416f5f2* (2016-11-23 13:12 UTC):
```
CodeInfo(:(begin 
        return $(QuoteNode(1))
    end))=>Int64
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/19418

### CODE REVIEW

**Comment by rfourquet** [comment]
The doc change is nice, but it seems you commited "base/precompile.jl" not on purpose?

**Comment by KristofferC** [comment]
Oops!

**Comment by rfourquet** [comment]
> Fixed.

Not yet!

**Comment by KristofferC** [comment]
wat

**Review by rfourquet — APPROVED** [review]

**Pull request merged**
