### PR TITLE
fix #21382, specificity problem with `DataType`

### LINKED ISSUE #21382: Specificity problem with recursive methods involving supertype +  DataType
This worked on earlier versions of 0.6 but doesn't now. (EDIT: maybe it never worked, it's possible this impression could have been confounded by the precompilation issue detected below.) If you change `eltype` to `foo` in the code below, then everything works as expected, leading me to suspect that it's a method-ordering bug.

```julia
julia> abstract type Colorant{T,N} end

julia> abstract type Color{T,N} <: Colorant{T,N} end

julia> Base.eltype{T}(::Type{Colorant{T}}) = T

julia> Base.eltype{T,N}(::Type{Colorant{T,N}}) = T

julia> Base.eltype{C<:Colorant}(::Type{C}) = eltype(supertype(C))

julia> eltype(Color{Float32})
Any

julia> @which eltype(Color{Float32})
eltype(::Type{C}) where C<:Colorant in Main at REPL[5]:1

julia> supertype(Color{Float32})
Colorant{Float32,N} where N

julia> eltype(Colorant{Float32})
Any

julia> @which eltype(Colorant{Float32})
eltype(::Type{C}) where C<:Colorant in Main at REPL[5]:1
```

If you omit the method that invokes `supertype`, then `eltype(Colorant{Float32})` works fine (but of course `eltype(Color{Float32})` doesn't).

Origin of a test failure in https://github.com/JuliaGraphics/ColorTypes.jl/pull/81. EDIT: Well, not really, see the next comment...

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by timholy** [comment]
Should I file a separate issue about the precompilation part, or should that also be taken care of by this? (I can test myself, if you haven't yet.)

**Comment by JeffBezanson** [comment]
I didn't look at the precompilation part; could you test it?

**Comment by JeffBezanson** [comment]
Potentially interesting stack trace in jl_uv on travis OS X: https://travis-ci.org/JuliaLang/julia/jobs/222404207

**Comment by timholy** [comment]
Seems to work in all circumstances (doesn't matter whether precompiled or not). Thanks!

I don't have any useful insights about the segfault. If nothing else it might be worth running a few more times to see if it seems to be dependent on this PR.

**Pull request merged**
