### PR TITLE
inference: make `limit::Int` as a caching key of `CachedMethodTable`

### LINKED ISSUE #46722: Broadcasting picks wrong method in 1.8.1
See https://github.com/PainterQubits/Unitful.jl/issues/557:
```julia
julia> using Unitful;

julia> [1.0u"m", 2.0u"m"] .+ 3.0u"m"
2-element Vector{Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}:
 4.0 m
 5.0 m

julia> Any[1.0u"m", 2.0u"m"] .+ 3.0u"m"
ERROR: + not defined for Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}
[...]
```

* `[1.0u"m", 2.0u"m"] .+ 3.0u"m"` uses
  `+(x::AbstractQuantity{S,D,U}, y::AbstractQuantity{T,D,U}) where {S,T,D,U}` in Unitful at src/quantities.jl:125
* `Any[1.0u"m", 2.0u"m"] .+ 3.0u"m"` uses
  `+(x::T, y::T) where T<:Number` in Base at promotion.jl:463` and therefore errors.

It worked on 1.8.0 and is broken on 1.8.1 and master. For the regression from 1.8.0 to 1.8.1, bisect blames 5d03fcd948ad862458f2b7b09cc97ad66c08ac1f, which is the backport of #46535.

### PR DESCRIPTION
**Pull request by aviatesk**
Sometimes `Core.Compiler.findall(::Type, ::CachedMethodTable; limit::Int)` is called with different `limit` setting (in particularity `return_type_tfunc` calls it with `limit=-1`). The query should return different results given different `limit` settings, so its cache should also have different keys per different `limit` settings.

fix #46722

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46799#issuecomment-1249404004) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ffac3da_vs_03ed550/report.md).

**Review by vtjnash — APPROVED** [review]

**Comment by giordano** [comment]
Isn't there any test that could be added?

**Comment by aviatesk** [comment]
https://github.com/JuliaLang/julia/pull/46818

**Pull request merged**
