### PR TITLE
fix / restore verifyModule functionality

### PR DESCRIPTION
**Pull request by vtjnash**
@Keno

### CODE REVIEW

**Comment by Keno** [comment]
For ORC, there is a verifier pass in the pass manager, so it probably isn't needed there.

**Comment by vtjnash** [comment]
is it running? the module fails verification due to these incorrect intrinsic method definitions, but orcjit hasn't been complaining

also, the verifyModule call at jl_dump_shadow at cgutils.cpp:644 seems to be very unexpectedly slow for me (on llvm-3.7.0, it's been running for a least ten minutes). perhaps we just run that for the debug build? or perhaps something is wrong with my build -- i haven't used this llvm version much recently to know what to expect.

**Comment by Keno** [comment]
You need to be careful not to run the verifier before all module references have been fixed up. The verifier should not take that long.

**Comment by vtjnash** [comment]
hm, ok -- that makes sense then. I originally found this because I was running the verifier before each time `FPM->run()` is run. the function was invalid then, and hadn't been added to the OrcJIT yet (because of being in `imaging_mode`).

(apparently the verifier was taking a long long time because I introduced a verifier error here:
```Referencing function in another module!   call void @llvm.dbg.value(metadata i1 false, i64 0, metadata !17241, metadata !17242), !dbg !17239```. I guess this confused the shadow_module copier.)

**Comment by vtjnash** [comment]
ok. i've changed this to not call `FPM->run` until after verifyModule has been called and can succeed

**Comment by Keno** [comment]
So you're proposing not running any optimizations on the code we jit during imaging?

**Comment by vtjnash** [comment]
no, i'm proposing that we will run the optimizations pass twice (rather than running it on invalid functions in and attempt to merge them). there's a pretty good chance we will want these to be different in the future anyways (much cheaper for JIT / much more expensive for the code that will be saved)

**Comment by vtjnash** [comment]
although now that you mention it, maybe that might actually be a good idea -- would need to benchmark that first to see what affect it would have on codegen speed / memory usage

**Pull request merged**
