### PR TITLE
fix turn back on latex output for markdown

### PR DESCRIPTION
**Pull request by hayd**
fixes https://github.com/one-more-minute/Markdown.jl/issues/15

Reworks latex.jl to be more like html.jl and updates for newer Markdown types; uses a latex method rather than writemime (writemime is defined only for the MD type).

cc @one-more-minute @MichaelHatherly

### CODE REVIEW

**Comment by one-more-minute** [comment]
This looks good, thanks. It looks like an unrelated change (from the ordered lists pr) has snuck in, though, which is stopping me from merging – can you rebase against master?

I think the build failure is unrelated, should go away once you've rebased.

**Comment by hayd** [comment]
rebased, I also have another commit I had not pushed about latex escaping. Will push and can delete if you dislike it.

**Comment by MichaelHatherly** [comment]
Sorry for taking a while to notice this. Thanks for doing this @hayd! I noticed there's no rendering for tables (have I just missed it?) for latex or html. Would be great to have at some point, though not that urgently needed (for myself).

**Comment by hayd** [comment]
@MichaelHatherly It's all in https://github.com/JuliaLang/julia/blob/master/base/markdown/GitHub/table.jl, I added it for latex with the old syntax - I should update.

**Comment by MichaelHatherly** [comment]
Thanks for the link @hayd. I was looking in the render directory instead.

**Comment by hayd** [comment]
@MichaelHatherly np, they were originally spread about there in my first implementation for tables. The idea was to not get those too crowded with non-default types. It's pretty nice IMO... I guess an alternative/refactor would be to put each md type in it's own file!

**Comment by hayd** [comment]
Pushed a fix for that. I've tested locally for GH table, but I will add a test onto another PR (I have another biggish one coming together for some common-mark fixes, so don't want to modify the test file too much in this one), thanks!

**Comment by hayd** [comment]
@one-more-minute bump! (The travis osx timeout is nothing to do with me!)

**Comment by one-more-minute** [comment]
Nice, thanks!

**Pull request merged**
