### PR TITLE
ASAN fixes.

### LINKED ISSUE #47698: ASAN: debug build fails
Trying to make a debug build of Julia under ASAN I'm running into:

```
ERROR: Unable to load dependent library libjulia-internal-debug.so.1
Message: libjulia-internal-debug.so.1: undefined symbol: __libc_siglongjmp
```

Use of this symbol was introduced by @keno in https://github.com/JuliaLang/julia/pull/46336, and is intended to bypass the ASAN hook and directly call siglongjmp from glibc. I'm not sure why it isn't working; @vtjnash commented that this symbol has been named like that for 25 years. Disabling the redefinition and just using `siglongjmp` works around the compilation error.

`objdump` output:
```
objdump -t libjulia-internal-debug.so.1 | grep siglong
0000000000000000       F *UND*  0000000000000000              siglongjmp@GLIBC_2.2.5
0000000000000000         *UND*  0000000000000000              __libc_siglongjmp
```

### PR DESCRIPTION
**Pull request by maleadt**
Taking @topolarity's fixes from https://github.com/JuliaLang/julia/issues/50170. Resolves https://github.com/JuliaLang/julia/issues/47698

For the `sigsetjmp` bypass; looks like glibc removed the `__libc_siglongjmp` symbol in glibc 2.34, so I guess that's the cutoff:

```
❯ objdump --disassemble --show-all-symbols 2.33/lib/x86_64-linux-gnu/libc.so.6 | grep siglongjmp
000000000003c510 <__libc_siglongjmp@@GLIBC_PRIVATE>:
000000000003c510 <siglongjmp@@GLIBC_2.2.5>:
   3c528:	75 14                	jne    3c53e <__libc_siglongjmp@@GLIBC_PRIVATE+0x2e>
   3c54f:	eb d9                	jmp    3c52a <__libc_siglongjmp@@GLIBC_PRIVATE+0x1a>

❯ objdump --disassemble --show-all-symbols 2.34/lib/x86_64-linux-gnu/libc.so.6 | grep siglongjmp
000000000003d820 <siglongjmp@@GLIBC_2.2.5>:
```

@Keno What kind of code required bypassing the ASAN siglongjmp interceptor? Stuff seems to work fine without it.

### CODE REVIEW

**Comment by Keno** [comment]
What does `make testall` look like with this branch for you? If you're not getting any false positives around the task stuff then there is probably no issue.

**Comment by maleadt** [comment]
Hard to tell. `make testall` fails in so many ways (fails to connect to worker, and running tests in isolation shows failures all over the place), and I have to build to compare against. Maybe CI should upload the ASAN binaries it generates?

**Comment by Keno** [comment]
IIRC, I had `make testall` passing under asan after #46336, so if it looks bad, that's probably a regression (though not particularly surprising).

**Comment by vtjnash** [comment]
@keno seemed like the main problem with that approach is that the stack will almost always be entirely unpoisoned, IIUC, which should miss issues not cause them. But I suppose it also would only unpoison the main stack, which might confuse it when running on alternate stacks. But anyways, I have now implemented the strategy used by dlopen for this, which seems to be working locally for me. I didn't run all of the tests, but the ones I ran (such as channels) were generally seeming to be working.

**Review by Keno — APPROVED** [review]

**Comment by giordano** [comment]
ASAN is failing, timing out after two hours more specifically: https://buildkite.com/julialang/julia-master/builds/30174#018bd9c4-922a-4e1d-9321-1290ad23019f/705-1659

**Comment by vtjnash** [comment]
@giordano this is not expected to change the time taken by the test or to fix that incorrect timeout threshold set in the buildkite CI configuration

**Pull request merged**
