### PR TITLE
Use the POSIX timers API rather than itimer on FreeBSD

### LINKED ISSUE #48714: Profile test fails on FreeBSD after 46571
Noticed while getting FreeBSD CI set up on buildkite. On current master (12d329b6e3, v1.10.0-DEV.635) with FreeBSD 12.2, one of the Profile test sets fails:
```
$ ./julia -e 'Base.runtests("Profile"; ncores=6)'
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 6
  Sys.total_memory() = 23.959 GiB
  Sys.free_memory() = 16.695 GiB

Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
Profile    (1) |        started at 2023-02-17T20:24:21.565
KILLING BY PROFILE TEST WATCHDOG

Profile    (1) |         failed at 2023-02-17T20:27:43.969
Test Failed at /usr/home/julia/julia/usr/share/julia/stdlib/v1.10/Profile/test/runtests.jl:230
  Expression: occursin("Overhead _", s)
   Evaluated: occursin("Overhead _", "\n\n======================================================================================\nInformation request received. A stacktrace will print followed by a 1.0 second profil
e\n======================================================================================\n\nsignal (29): Information request\n__sys_write at /lib/libc.so.7 (unknown line)\n_pthread_suspend_all_np at /lib/libthr.so.
3 (unknown line)\nuv__writev at /workspace/srcdir/libuv/src/unix/stream.c:697\nuv__try_write at /workspace/srcdir/libuv/src/unix/stream.c:856\nuv__write at /workspace/srcdir/libuv/src/unix/stream.c:898\nuv_write2 at
 /workspace/srcdir/libuv/src/unix/stream.c:1447\nuv_write at /workspace/srcdir/libuv/src/unix/stream.c:1472\njl_uv_write at /usr/home/julia/julia/src/jl_uv.c:544\nuv_write_async at ./stream.jl:1080\nuv_write at ./st
ream.jl:1037\nunsafe_write at ./stream.jl:1120\nwrite at ./strings/io.jl:248 [inlined]\nprint at ./strings/io.jl:250\nunknown function (ip: 0x8182c4056)\n_jl_invoke at /usr/home/julia/julia/src/gf.c:2691\nijl_apply_
generic at /usr/home/julia/julia/src/gf.c:2873\njl_apply at /usr/home/julia/julia/src/./julia.h:1875\ndo_call at /usr/home/julia/julia/src/interpreter.c:125\neval_value at /usr/home/julia/julia/src/interpreter.c:222
\neval_stmt_value at /usr/home/julia/julia/src/interpreter.c:173\neval_body at /usr/home/julia/julia/src/interpreter.c:602\njl_interpret_toplevel_thunk at /usr/home/julia/julia/src/interpreter.c:758\njl_toplevel_eva
l_flex at /usr/home/julia/julia/src/toplevel.c:910\njl_toplevel_eval_flex at /usr/home/julia/julia/src/toplevel.c:853\nijl_toplevel_eval at /usr/home/julia/julia/src/toplevel.c:919\nijl_toplevel_eval_in at /usr/home
/julia/julia/src/toplevel.c:969\neval at ./boot.jl:370 [inlined]\nexec_options at ./client.jl:280\n_start at ./client.jl:541\njfptr__start_56127 at /usr/home/julia/julia/usr/lib/julia/sys-debug.so (unknown line)\n_j
l_invoke at /usr/home/julia/julia/src/gf.c:2672\nijl_apply_generic at /usr/home/julia/julia/src/gf.c:2873\njl_apply at /usr/home/julia/julia/src/./julia.h:1875\ntrue_main at /usr/home/julia/julia/src/jlapi.c:573\njl
_repl_entrypoint at /usr/home/julia/julia/src/jlapi.c:717\njl_load_repl at /usr/home/julia/julia/cli/loader_lib.c:543\nmain at /usr/home/julia/julia/usr/bin/julia-debug (unknown line)\n_start at /usr/home/julia/juli
a/usr/bin/julia-debug (unknown line)\nunknown function (ip: 0x80022dfff)\nunknown function (ip: 0x0)\n\n[85977] signal (15): Terminated\nin expression starting at none:3\n\n==========================================
====================\nProfile collected. A report will print at the next yield point\n==============================================================\n\n_kevent at /lib/libc.so.7 (unknown line)\n_pthread_suspend_all_
np at /lib/libthr.so.3 (unknown line)\nuv__io_poll at /workspace/srcdir/libuv/src/unix/kqueue.c:199\nuv_run at /workspace/srcdir/libuv/src/unix/core.c:400\nijl_task_get_next at /usr/home/julia/julia/src/partr.c:411\
npoptask at ./task.jl:963\nwait at ./task.jl:972\n#wait#623 at ./condition.jl:130\nwait at ./condition.jl:125 [inlined]\nwait_readnb at ./stream.jl:416\neof at ./stream.jl:106\njfptr_eof_31258 at /usr/home/julia/jul
ia/usr/lib/julia/sys-debug.so (unknown line)\n_jl_invoke at /usr/home/julia/julia/src/gf.c:2672\nijl_apply_generic at /usr/home/julia/julia/src/gf.c:2873\njl_apply at /usr/home/julia/julia/src/./julia.h:1875\ndo_cal
l at /usr/home/julia/julia/src/interpreter.c:125\neval_value at /usr/home/julia/julia/src/interpreter.c:222\neval_stmt_value at /usr/home/julia/julia/src/interpreter.c:173\neval_body at /usr/home/julia/julia/src/int
erpreter.c:602\njl_interpret_toplevel_thunk at /usr/home/julia/julia/src/interpreter.c:758\njl_toplevel_eval_flex at /usr/home/julia/julia/src/toplevel.c:910\njl_toplevel_eval_flex at /usr/home/julia/julia/src/tople
vel.c:853\nijl_toplevel_eval at /usr/home/julia/julia/src/toplevel.c:919\nijl_toplevel_eval_in at /usr/home/julia/julia/src/toplevel.c:969\neval at ./boot.jl:370 [inlined]\nexec_options at ./client.jl:280\n_start at
 ./client.jl:541\njfptr__start_56127 at /usr/home/julia/julia/usr/lib/julia/sys-debug.so (unknown line)\n_jl_invoke at /usr/home/julia/julia/src/gf.c:2672\nijl_apply_generic at /usr/home/julia/julia/src/gf.c:2873\nj
l_apply at /usr/home/julia/julia/src/./julia.h:1875\ntrue_main at /usr/home/julia/julia/src/jlapi.c:573\njl_repl_entrypoint at /usr/home/julia/julia/src/jlapi.c:717\njl_load_repl at /usr/home/julia/julia/cli/loader_
lib.c:543\nmain at /usr/home/julia/julia/usr/bin/julia-debug (unknown line)\n_start at /usr/home/julia/julia/usr/bin/julia-debug (unknown line)\nunknown function (ip: 0x80022dfff)\nunknown function (ip: 0x0)\nAlloca
tions: 3029 (Pool: 3018; Big: 11); GC: 0\n")
Test Failed at /usr/home/julia/julia/usr/share/julia/stdlib/v1.10/Profile/test/runtests.jl:228
  Expression: process_running(p)
Test Failed at /usr/home/julia/julia/usr/share/julia/stdlib/v1.10/Profile/test/runtests.jl:230
  Expression: occursin("Overhead _", s)
   Evaluated: occursin("Overhead _", "")


Test Summary: | Pass  Fail  Total     Time
  Overall     |  113     3    116  3m25.1s
    Profile   |  113     3    116  3m23.5s
    FAILURE
```
I bisected the failure to #46571, and it happens to be the test set that's modified in that PR that's failing.

### PR DESCRIPTION
**Pull request by ararslan**
POSIX.1-2008 marks `getitimer`/`setitimer` obsolete in favor of `timer_gettime`/`timer_settime`. Additionally, POSIX.1-2017 marks `SIGPROF` obsolete. Thus we can make simply have FreeBSD use the same signals code paths as Linux, which already uses the timer API and uses `SIGUSR1` rather than `SIGPROF`. The code conditional on the `HAVE_ITIMER` flag, as well as the flag itself, have been removed since they're no longer used.

Inexplicably fixes #48714 for me.

### CODE REVIEW

**Comment by ararslan** [comment]
Weird, I did not get this locally:
```
cmdlineargs                                      (4) |         failed at 2023-03-21T02:00:25.487
Error During Test at /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-1/julialang/julia-master/julia-044401cfcd/share/julia/test/cmdlineargs.jl:303
  Test threw exception
  Expression: string(cpu_threads) == read(`$exename --threads auto -e $code`, String) == read(`$exename --threads=auto -e $code`, String) == read(`$exename -tauto -e $code`, String) == read(`$exename -t auto -e $code`, String)
  failed process: Process(`/usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-1/julialang/julia-master/julia-044401cfcd/bin/julia -Cnative -J/usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-1/julialang/julia-master/julia-044401cfcd/lib/julia/sys.so --depwarn=error --check-bounds=yes -g1 --startup-file=no --startup-file=no --color=no -t auto -e 'print(Threads.threadpoolsize())'`, ProcessSignaled(6)) [0]
   
  Stacktrace:
   [1] pipeline_error
     @ ./process.jl:565 [inlined]
   [2] read(cmd::Cmd)
     @ Base ./process.jl:449
   [3] read(cmd::Cmd, #unused#::Type{String})
     @ Base ./process.jl:458
   [4] macro expansion
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-1/julialang/julia-master/julia-044401cfcd/share/julia/stdlib/v1.10/Test/src/Test.jl:478 [inlined]
   [5] top-level scope
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-1/julialang/julia-master/julia-044401cfcd/share/julia/test/cmdlineargs.jl:303
```

**Comment by giordano** [comment]
We've seen that error on other platforms as well. CC @gbaraldi

**Comment by gbaraldi** [comment]
Yeah, we usually get a segfault here when it errors, but it seems we got a sigabrt.

**Review by vtjnash — APPROVED** [review]
Do you want to use SIGPROF still, via setting:
```
    sigprof.sigev_signo = SIGPROF;
```

**Comment by ararslan** [comment]
The `cmdlineargs` test failure didn't occur on the run triggered by the merge so I guess it's sporadic here as well

**Comment by giordano** [comment]
I opened an issue about the `cmdlineargs` test failure: #49154

**Pull request merged**
