### PR TITLE
Add Levi-Civita and Parity of a permutation to Base (Fix #8534 and #10172)

### LINKED ISSUE #8534: Parity for permutations?
It would be good to have a way to obtain the parity of a permutation, i.e. whether an odd or an even number of pair permutations is necessary to arrive at a given permutation.

### PR DESCRIPTION
**Pull request by p-zubieta**
It has been suggested that it would be good to have a way of calculating the Levi-Civita symbol and parity of a permutation. This commit implements both.

### CODE REVIEW

**Comment by blakejohnson** [comment]
I would prefer not to export two new names. Why not just check for `lenght(p) == 3` in the general version and call the fast path?

**Comment by pabloferz** [comment]
You're right Blake. What do you think is best: just to remove `levicivita3` or also `_levicivita3`?

**Comment by pabloferz** [comment]
Ok. I removed the `levicivita3` functions so now all the work is done by the general version `levicivita`.

**Comment by blakejohnson** [comment]
Yes, that looks pretty good to me. Looks like you are failing the tests because of trailing whitespace.

**Comment by pabloferz** [comment]
I fixed that, but the AppVeyor fail is unrelated.

**Comment by blakejohnson** [comment]
Maybe the only thing left is to bike shed the name. I may have a slight preference for `signature`. Could we get some other opinions? Ping @jiahao and @StefanKarpinski.

**Comment by pabloferz** [comment]
I wouldn't have a problem changing the name to `signature` as long as there are no objections on calling it that.

**Comment by tkelman** [comment]
`signature` doesn't seem like an obvious unambiguous name to me at all, fwiw

**Comment by StefanKarpinski** [comment]
Yeah, I kind of feel the same way. There's a lot of other things that could be called `signature` – in method signatures and cryptographic signatures to name just two off the top of my head. Somehow calling it `sig` seems better to me.

**Comment by pabloferz** [comment]
You're right. `sig` sounds better, maybe `sgn` can also work.

**Comment by jiahao** [comment]
I don't see how "sig" is somehow more obvious than "signature".

The other extant names for this quantity are "sign (of a permutation)" and "parity (of a permutation)". This PR currently uses `parity`.

Also, this PR defines `parity` for an arbitrary `AbstractVector`. Perhaps it would make more sense to define it for `Base.Permutations` instead.

**Comment by StefanKarpinski** [comment]
It's not more obvious – it's less obvious, which makes it more ok to take as a name for a fairly specific thing.

**Comment by StefanKarpinski** [comment]
I think `parity` is a fine name, btw. Is there an issue with using that?

**Comment by jiahao** [comment]
I think `parity` is the least overloaded choice of the 3.

**Comment by StefanKarpinski** [comment]
Hmm. It would be nice if we could define it in a generalizable way:

http://en.wikipedia.org/wiki/Parity_(mathematics)

**Comment by blakejohnson** [comment]
I don't think parity and signature are equivalent. Usually `sgn(s) =
-1^parity(s)`. Additionally parity should be undefined when `isperm(s) =
false`, but `sgn(s) = 0`.

**Comment by jiahao** [comment]
Crumbs, you're right.

**Comment by pabloferz** [comment]
This PR does both, defines sgn (`levicivita(p)`) and `parity(p)` using the sgn.

Also, I believe it's useful to have `parity` for an `AbstractVector` in case someone wants the parity of for example `ranperm(1:100)`.

The nice thing about `parity` is that you can write `iseven(parity(p))`

**Comment by pabloferz** [comment]
The only inconvenience I see is that `levicivita` might not be a good name (and that's what Blake was proposing to change).

**Comment by tkelman** [comment]
`levicevita` has the rare advantage of a pretty unambiguous meaning. I'll vote for the names as they are now.

**Comment by StefanKarpinski** [comment]
Ok, let's go with this. If we figure out a way to fold `levicivita` into a more general function nicely, we can always just do that and add a deprecation.

**Comment by pabloferz** [comment]
Another option would be to change the current `sign{T<:Real}(a::AbstractArray{T})` to `signs{T<:Real}(a::AbstractArray{T})` and rename `levicivita` to `sign`, but that might be confusing and would need a deprecation message.

**Comment by blakejohnson** [comment]
@pabloferz would you mind squashing the commits, and then adding documentation for `parity` and `levicivita`? At that point I think this will be ready to merge.

**Comment by blakejohnson** [comment]
Bump. @pabloferz can you please squash the commits?

**Comment by pabloferz** [comment]
Done.

**Comment by blakejohnson** [comment]
Thank you, @pabloferz.

**Comment by tkelman** [comment]
Still needs to be documented, right?

**Comment by blakejohnson** [comment]
Yes, needs docs and NEWS.

**Pull request merged**
