### PR TITLE
Bump openspecfun (release-0.3)

### PR DESCRIPTION
**Pull request by jiahao**
Locally icc 14.0.1/linux64 builds and tests pass except for logdet in linalg4 and mod2pi.

Replaces #10199

Ref #10188 JuliaLang/openspecfun#28 JuliaLang/openspecfun#30

### CODE REVIEW

**Comment by jiahao** [comment]
I'll let the backporters decide when to merge this.

**Comment by tkelman** [comment]
This helps release-0.3 pass the math test with Intel compilers but doesn't fix any other issues, right? I think I'd be okay with merging this pre-0.3.6 since the changes (https://github.com/JuliaLang/openspecfun/compare/f3036c094ae56fdf447092a871ea4fe27fdeec16...381db9bc865e51de67be9dcaa1610a6f90029c72) are fairly minor and have been on master for a few days without appearing to cause any trouble.

**Comment by jiahao** [comment]
Essentially yes. The commit history shows some Solaris fixes also.

**Comment by staticfloat** [comment]
I'm pulling the trigger.

**Pull request merged**
