### PR TITLE
don't mutate lhs while destructuring

### LINKED ISSUE #40574: Evaluation order when using mutating operations with destructuring assignment
```julia
julia> x = [1,2]
2-element Vector{Int64}:
 1
 2

julia> x[2],x[1] = x
2-element Vector{Int64}:
 1
 1
```
This is caused by mutating the iterator as it is being iterated: i.e. it is being lowered to
```julia
julia> x = [1,2]
2-element Vector{Int64}:
 1
 2

julia> x[2], state = iterate(x)
(1, 2)

julia> x[1], state = iterate(x, state)
(1, 3)

julia> x
2-element Vector{Int64}:
 1
 1
```

From @simeonschaub on Slack:
> For a non-trivial lhs, we should probably always assign the rhs to temporary variables first and only then call setindex! etc.

cc: @JeffBezanson @vtjnash

### PR DESCRIPTION
**Pull request by simeonschaub**
@jeffbezanson was a bit sceptical about this in #40574, but I think this
is worth doing since it seems strictly more useful than the current
behavior and we already go out of our way in cases like `x, y = y, x` to
only assign to the lhs after the rhs has been evaluated, so I think
handling `x[2], x[1] = x` in a similar way would only be consisten. As a
general rule that assignment will always happen after destructuring does
not seem much less obvious than the current behavior to me. This might
technically be slightly breaking, but I would be surprised if people
relied on the current behavior here. Nevertheless, it would probably
good to run PkgEval if we decide to go with this change.

closes #40574

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Triage thinks this is the right thing to do.

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40737#issuecomment-834259272) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/bcccabf_vs_fbe28e4/report.md). cc @maleadt

**Comment by simeonschaub** [comment]
@nanosoldier `runtests(["AbstractMCMC", "Circuitscape", "DiffEqUncertainty", "EliminateGraphs", "Expect", "ExtensibleUnions", "Graph500", "KrigingEstimators", "Manifolds", "MixedModelsExtras", "MixedModelsSim", "NumericalAlgorithms", "PLCTag", "ProgressMeterLogging", "Reactive", "SpatialJackknife"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40737#issuecomment-834604780) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/5bd1968_vs_6726ae8/report.md). cc @maleadt

**Comment by StefanKarpinski** [comment]
This does seem strictly better. I'm pretty sure we can wave any breakage under the rug of undefined behavior.

**Pull request merged**
