### PR TITLE
Set VERSION to 0.7.0-beta2

### PR DESCRIPTION
**Pull request by ararslan**
This will be the second beta release for 0.7.

To merge first:
- [x] #27998
- [x] #28009
- [x] #28002
- [x] #28010
- [x] #28066
- [x] #28082
- [x] #28091

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Note, please wait until https://github.com/JuliaLang/Pkg.jl/pull/471 and any other Pkg changes that @KristofferC deems important enough are downstreamed into julia#master.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/27998 contains https://github.com/JuliaLang/Pkg.jl/pull/471 so after that is merged, should be good to go here.

**Comment by KristofferC** [comment]
Would be good to get some docs in about the new code loading but I don't think it should hold up the beta release since so many fixes have gone in and getting this out is important for people updating packages..

**Comment by ararslan** [comment]
#28009 also needs to be merged before this.

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/julia/pull/28002 is needed as well

**Comment by ararslan** [comment]
I've started a checklist in the top post, feel free to add and check off as appropriate.

**Comment by StefanKarpinski** [comment]
Agree, docs can and will be written after the second beta.

**Comment by ararslan** [comment]
All prerequisite PRs have been merged so this should be good to go. @vtjnash has requested we make this a release candidate rather than another beta.

**Comment by StefanKarpinski** [comment]
Request noted. Unless this is really plausibly an actual release, we're not calling it a release candidate.

**Comment by ararslan** [comment]
Alright, good to merge then?

**Comment by ararslan** [comment]
image

**Comment by StefanKarpinski** [comment]
Let's wait on this guy: https://github.com/JuliaLang/julia/pull/28066.

**Comment by ararslan** [comment]
Added to checklist

**Comment by ararslan** [comment]
Last item checked off. Anything else?

**Comment by ararslan** [comment]
Maybe we want to wait on #28082? @KristofferC

**Comment by KristofferC** [comment]
Should be good to go but it seems AV failed to download julia?

**Comment by StefanKarpinski** [comment]
This would be nice but not necessary: https://github.com/JuliaLang/julia/pull/28091.

**Comment by ararslan** [comment]
Everything is checked off. _Now_ can we do this? :smile:

**Comment by StefanKarpinski** [comment]
Yeah, I think we're good to go now.

**Comment by ararslan** [comment]
3 2 1 go

**Pull request merged**
