### PR TITLE
[deps/stdlib] put all version info in `Versions.make`

### PR DESCRIPTION
**Pull request by inkydragon**
> I agree that there doesn't need to be both `Versions.make` and `libname.version`.  We could combine the two (probably by just putting everything into `Versions.make`).
> 
> _Originally posted by `@staticfloat` in https://github.com/JuliaLang/julia/issues/40430#issuecomment-904186068_

ref: #40430

- [x] rm all `*.version` files, and put all version info in `Versions.make`
- [x] fix 2 version mismatch: `libblastrampoline` and `OpenBLAS`
- [x] add a comment for `LibSSH2`, why `LIBSSH2_VER !== LIBSSH2_BRANCH`

----

Maybe we can backport this pr to other versions.

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
For stdlib, we actually want to keep each of the external stdlibs in their own file. See for example https://github.com/JuliaLang/julia/pull/41370#issuecomment-869856645. So this PR undoes the work we did in https://github.com/JuliaLang/julia/pull/42474.

https://github.com/JuliaLang/julia/issues/40430 was about deps, not stdlib. Can you remove the external stdlib changes from this PR?

**Comment by inkydragon** [comment]
> Can you remove the external stdlib changes from this PR?

There is one small problem. Because the installation of stdlib calls the function `stdlib-external`, which in turn calls `git-external`. So we can't just have stdlib use a separate `.version` file.

Perhaps we could reuse the deprecated arguments of the `git-external` function, and add a new argument  `use_all_in_one_version_file` so that we can distinguish between `deps` and `stdlib`.

**Comment by vtjnash** [comment]
We don't want to do this for deps either, since it means we can't determine as accurately when they need to be updated, and it increases the chances that backporting something ends up in a merge conflict. But we could probably move the BB versions into the `.version` files, to keep all of the ways of specifying it in one place.

**Comment by inkydragon** [comment]
replace by: #45720

**Pull request closed without merging**
