### PR TITLE
[release-0.5] Backport #19022

### PR DESCRIPTION
**Pull request by staticfloat**
This backports some fixes for ARMv7 support.  It makes it easier for Julia to autodetect the proper version, and fixes the binaries so that they can run on ARM processors that don't have NEON support.  If I download the [beta 0.5.2 binary (6accda38c4)](https://s3.amazonaws.com/julianightlies/bin/linux/arm/0.5/julia-0.5.2-6accda38c4-linuxarm.tar.gz) from [this thread](https://github.com/JuliaLang/julia/pull/21684#issuecomment-299331305) and try to run it on a scaleway server with no NEON support, it `SIGILL`'s.  With this change, we can compile with `JULIA_CPU_TYPE=generic` (which is what the buildbots are doing anyway) and it works okay.

### CODE REVIEW

**Comment by tkelman** [comment]
last time around this caused build issues which is why I was leaving this alone on release-0.5

**Comment by tkelman** [comment]
please cherry-pick with `-x -e` and add cross references to the PR to the commit message. would also be slightly cleaner if this branch were rebased against the 0.5.1 tag instead of the tip of release-0.5

**Comment by staticfloat** [comment]
> last time around this caused build issues which is why I was leaving this alone on release-0.5

I'm not sure exactly what build issues you're referring to, but I think it's worth the effort so that we can support non-NEON ARM architectures.

**Comment by tkelman** [comment]
still missing a reference to the pr # in the commit messages

**Comment by staticfloat** [comment]
Sorry, missed that.  Done.

**Comment by tkelman** [comment]
those commit shas also don't make much sense, those aren't linking to the commit that's on master

**Comment by staticfloat** [comment]
Rarely have I been so confused by a git mess.  One more try.

**Comment by staticfloat** [comment]
Closing this as 0.6.0 is out now.

**Pull request closed without merging**
