### PR TITLE
fix #14825

### LINKED ISSUE #14825: Circular parametric types
In continuation from https://groups.google.com/forum/#!topic/julia-users/bYPdJSUq_9g

I am trying to define two parametric types with circular dependency as follows (julia version 0.4.2):

```julia
abstract abstest

type t1{A <: abstest, B} 
  x::A 
  y::B
end

type t2{C, B} <: abstest 
  x::C 
  y::t1{t2{C, B}, B}
end
```
Unfortunately it doesn't work:
```
ERROR: TypeError: t1: in A, expected A<:abstest, got Type{t2{C,B}}
```
Apparently he is complaining about the definition of field `y` in the definition of type `t2`. But `t2{C, B}` is a subtype of abstest, so `{t2{C, B}, B}` should be valid parameters for type `t1`. Probably I am missing something here.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Backportable?

**Comment by yuyichao** [comment]
Would also be nice to have a more descriptive commit message.

**Comment by JeffBezanson** [comment]
Yes should be backportable, but the reference to `jl_builtin_type` will need to be removed.

**Comment by tkelman** [comment]
Just drop the `|| super == (jl_value_t*)jl_builtin_type` at the end of the condition?

**Comment by JeffBezanson** [comment]
@tkelman Yes.

**Comment by tkelman** [comment]
also needed https://github.com/JuliaLang/julia/commit/fd33166c827df738ad6d6aa22762b5505de42d17

**Pull request merged**
