### PR TITLE
Move back isascii() from Unicode to Base

### LINKED ISSUE #25075: isascii was left behind in the Unicode move
On 0.6:
```
julia> isascii
isascii (generic function with 2 methods)
```
On 0.7.0-DEV.2949:
```
julia> isascii
ERROR: UndefVarError: isascii not defined

julia> Base.isascii
ERROR: UndefVarError: isascii not defined

julia> Unicode.isascii
ERROR: UndefVarError: isascii not defined

julia> Base.Unicode.isascii
isascii (generic function with 2 methods)
```
Seems like it should be defined in the Unicode stdlib package and have a deprecation message.

### PR DESCRIPTION
**Pull request by nalimilan**
This function is not really Unicode-related and its definition does not depend on the Unicode standard version. This fixes a bug introduced when moving `isascii` to `Base.Unicode` (https://github.com/JuliaLang/julia/pull/25021), as it was not exported from `Unicode` stdlib module as it should have been.

Fixes #25075.

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Comment by quinnj** [comment]
Looks like there's already a conflict though

**Comment by ararslan** [comment]
Will `isascii` still be defined in `Base.Unicode`? If not, I need to make another PR to URIParser...

**Comment by nalimilan** [comment]
I don't think so. Why define a function in two places?

**Comment by ararslan** [comment]
¯\\\_(ツ)\_/¯

**Pull request merged**
