### PR TITLE
fix #15590

### LINKED ISSUE #15590: Deprecation warning uses illegal syntax
I get this warning (not the white space between the brackets):
```Julia
[1] [2]

WARNING: deprecated syntax "(vect 1) [".
Use "(vect 1)[" instead.
```
The expression `(vect 1)` is not legal in Julia; it looks like Lisp. The message should probably read `"[1]["` instead.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@vtjnash This is only used when printing syntax deprecation warnings. Do we have any tests for those?

**Comment by ranjanan** [comment]
@JeffBezanson @vtjnash This kind of syntax now throws an error
```
julia> [1] [2]
ERROR: syntax: space before "[" not allowed in "[1] ["
```
Is this PR meant to have changed the text in the warning or actually throw an error?

**Comment by tkelman** [comment]
At the time of this PR it was a warning, a few months later it was made an error. If there are now tests for the printing of the syntax error, then we can remove the needs-tests label.

**Comment by ranjanan** [comment]
Alright, will send a PR with tests to check for the error.

**Comment by tkelman** [comment]
Check `test/parse.jl` for what's there already, might already be covered.

**Comment by ranjanan** [comment]
I cannot find a test for this there, so I'll write one up.

**Pull request merged**
