### PR TITLE
Fix compilation on AArch64

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
Will merge tomorrow since this shouldn't introduce any regression on any platforms that currently compiles and this passes compilation locally.

**Comment by tkelman** [comment]
lgtm, assuming that `// instructions are always 4 bytes` also holds for aarch64? is it just pointers that are 64 bit on that arch?

**Comment by yuyichao** [comment]
> assuming that `// instructions are always 4 bytes` also holds for aarch64? is it just pointers that are 64 bit on that arch?

Yes. (I also checked the disassemble to make sure). Note that the 4 bytes instructions length is not enough to hold a pointer immediate on 32bit either.

**Comment by ViralBShah** [comment]
Would this fix the recent regression for arm as well?

**Comment by yuyichao** [comment]
I assume you mean https://github.com/JuliaLang/julia/issues/14466 ?

I doubt that.

**Comment by ViralBShah** [comment]
Yes - I did check, and it is still broken.

**Pull request merged**
