### PR TITLE
Upgrade and use NSIS for compression instead of extra 7z stage

### LINKED ISSUE #30475: Source code for julia/contrib/windows/7zS.sfx missing
I'm afraid there isn't source code for `7zS.sfx` in julia's source tarball. Missing source code violates Debian's free software guideline, and we (Debian) will remove `7zS.sfx` from the source tarball being distributed by Debian itself[1].

Is source code for `7zS.sfx` available?

Sorry if I opened a stupid issue, but I'm really not familiar with any windows-related file.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916957

### LINKED ISSUE #31875: Remove the extra 7zip compression and just use nsis directly for compression
Upgrading to the latest nsis installer and setting the compression to lzma in the config for the nsis installer I am able to produce a windows installer that is the same size as that achieved by the additional compression step through the post-processing 7z stage in the makefile. 

In other words the stages for https://github.com/JuliaLang/julia/blob/master/Makefile#L467 are not needed.

What this means is that decompression occurs during the installation time.

Should I make a PR for this change?

### PR DESCRIPTION
**Pull request by musm**
For a reference see the original issue https://github.com/JuliaLang/julia/issues/31875

Fix https://github.com/JuliaLang/julia/issues/31875
This also fixes https://github.com/JuliaLang/julia/issues/30475

### CODE REVIEW

**Comment by ViralBShah** [comment]
Does this mean we can completely remove the dependency on 7z?

**Comment by musm** [comment]
I don't think so. Julia ships with 7z but I'm not exactly sure what it's used for.

**Comment by musm** [comment]
I searched the repo and indeed 7z isn't used by any  julia source files either in base or stdlib. We can work that in another PR since that is an unrelated change.

**Comment by staticfloat** [comment]
> Does this mean we can completely remove the dependency on 7z?

No; we use `7z` to extract `.tar.gz` files on Windows.  We use it in things like `BinaryProvider` (and, soon, `Pkg`)

**Comment by staticfloat** [comment]
Does this affect compression factor at all?

**Comment by musm** [comment]
> Does this affect compression factor at all?

No, the binaries are almost  the same size (I can't remember the size difference anymore)

**Comment by staticfloat** [comment]
Is there any discernable difference between the installation experience?  E.g. for people who do headless installs, are they going to need to change the flags they use to do a headless install?  If so, we may need to note that in `NEWS.md`.

**Comment by musm** [comment]
The only differences is that it's a smoother installation experience from user perspective. Instead of an extraction pop up and then installation, the two are merged into the nsis installer.

> E.g. for people who do headless installs, are they going to need to change the flags they use to do a headless install?

No change required. With the 7z  stage it merged the extraction details into the binary. 



The reason I delved into this was I got super annoyed at how chocolatey kept popping up the Julia extraction stage of the installer **even though the silent flag of the nsis installer was used**. The reason for this is that the 7z configuration is unaffected by the silent flag.

**Comment by musm** [comment]
BTW I plan to also update and make the installer look more modern in another PR.

**Comment by musm** [comment]
size difference: 
This pr: 58929 KB  
master: 52669 KB  

I can increase the dictionary size if this difference is too big @staticfloat ?

**Comment by musm** [comment]
size difference reduced to less than 2MB

**Review by staticfloat — APPROVED** [review]
LGTM

**Comment by StefanKarpinski** [comment]
I restarted the Linux 64 Travis build because it wasn't 100% clear to me that it was unrelated. Also unclear to me if @staticfloat's "LGTM" was about the code, the test failures or both.

**Comment by musm** [comment]
Squashed the commits and cleaned things up. @staticfloat  want to take another look before merge?
I've tested this out several times and things are working nicely. Binaries have a comparable size (within 2 MB) and build times are a bit faster for `binary-dist`.

**Comment by musm** [comment]
Awesome thanks so much, I'm glad to have this improvement.

**Comment by staticfloat** [comment]
@musm I'm having trouble with win32 installers now, and I think it might be related to this.  Previously, I've been using the following command to silently extract the Julia installer's files into the current directory for CI:

```
./julia*.exe /S /D=$(cygpath -w $(pwd))
```

But when I run that on a win32 build now, it doesn't put anything in the current directory.  Could this be related to these changes?  For reference, you can see this behavior in [this file](https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x86/1.3/julia-325297f2c1-win32.exe).

**Comment by musm** [comment]
Unlikely, but I'll take a look Sunday at the earliest. Is that exe from this branch, since we reverted these changes anyways?

**Comment by staticfloat** [comment]
Ah, you're right, I forgot that we reverted this.  Hmmm, I wonder what could have changed then... Furthermore, it looks like it's only happening on win32, not on win64, which I think rules these changes out.

**Pull request merged**
