### PR TITLE
[release-1.3] Set VERSION to 1.3.1

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by KristofferC** [comment]
Let's wait with a repo tag until we have gotten some testing on discourse.

**Comment by ararslan** [comment]
Testing period announced on Discourse: https://discourse.julialang.org/t/julia-1-3-1-testing-period/32492?u=ararslan

**Review by fredrikekre — APPROVED** [review]

**Comment by maleadt** [comment]
Maybe we should mention some binaries there?
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.3/julia-90620af6b9-linux64.tar.gz
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x86/1.3/julia-90620af6b9-linux32.tar.gz
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x64/1.3/julia-90620af6b9-win64.exe
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x86/1.3/julia-90620af6b9-win32.exe
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/mac/x64/1.3/julia-90620af6b9-mac64.dmg
- https://s3.amazonaws.com/julialangnightlies/assert_pretesting/freebsd/x64/1.3/julia-90620af6b9-freebsd64.tar.gz

I could only find assert_pretesting builds on s3 though, nothing in the assert_bin or bin folders (cc @staticfloat).

**Comment by staticfloat** [comment]
We only promote things on `master`, we don't do anything with release branches.  So yes, you have to grab them from the pretesting buckets.

**Comment by maleadt** [comment]
> We only promote things on `master`, we don't do anything with release branches. So yes, you have to grab them from the pretesting buckets.

The `pretesting` bucket doesn't contain them either though.

**Comment by staticfloat** [comment]
Ah, indeed.  It appears that we only bother to build nonassert builds for `master`.  I'm not certain the extra CI strain is worth it; if we want a nonassert version of this, just go to [build.julialang.org](https://build.julialang.org) and login with GitHub in the top right, then go to [the `package_all` builder](https://build.julialang.org/#/builders/147), click `package_all` in the top right, paste in the gitsha you want to build and keep `Build with Assertions` unchecked.  It's easy enough that I think it's fine to just have people generate the nonassert binaries when they really need them.

**Comment by maleadt** [comment]
OK, thanks for those instructions. Here are regular binaries for this branch:
- https://s3.amazonaws.com/julialangnightlies/pretesting/linux/x64/1.3/julia-ee4a096f62-linux64.tar.gz
- https://s3.amazonaws.com/julialangnightlies/pretesting/linux/x86/1.3/julia-ee4a096f62-linux32.tar.gz
- https://s3.amazonaws.com/julialangnightlies/pretesting/winnt/x64/1.3/julia-ee4a096f62-win64.exe
- https://s3.amazonaws.com/julialangnightlies/pretesting/winnt/x86/1.3/julia-ee4a096f62-win32.exe
- https://s3.amazonaws.com/julialangnightlies/pretesting/mac/x64/1.3/julia-ee4a096f62-mac64.dmg
- https://s3.amazonaws.com/julialangnightlies/pretesting/freebsd/x64/1.3/julia-ee4a096f62-freebsd64.tar.gz

Just to make sure:
```
$ wget -q https://s3.amazonaws.com/julialangnightlies/pretesting/linux/x64/1.3/julia-ee4a096f62-linux64.tar.gz                                                                                                               
$ tar -xf julia-ee4a096f62-linux64.tar.gz                                                                                                                                                                                    
$ ./julia-ee4a096f62/bin/julia                                                                                                                                                                                               
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-19)
 _/ |\__'_|_|_|\__'_|  |  master/ee4a096f62 (fork: 117 commits, 124 days)
|__/ 
```

**Pull request merged**
