### PR TITLE
fix mapreduce on matrices with extra trailing elements in rowval/nzval

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://github.com/JuliaLang/julia/issues/26534

### CODE REVIEW

**Review by andreasnoack — COMMENTED** [review]
LGTM except that a swp file has sneaked into the commit.

I'm wondering if it would make sense to just change `getnzval` to return what you `nzvalview` does. The view might cause some overhead in some situations though.

**Comment by KristofferC** [comment]
`getnzval` is used in a single place in the whole code and that is in `bwdTriSolve!`...

**Comment by andreasnoack** [comment]
At least the author left a comment that explains why these function can be useful. By using these, I think many of the sparse functions can be written such that they also work for views of contiguous columns. However, there is still much work to do.

**Comment by KristofferC** [comment]
Is this good to go @andreasnoack?

**Comment by andreasnoack** [comment]
I'm still wondering if the functions could be merged but they are internal so the cleanup can happen whenever.

**Pull request merged**
