### PR TITLE
CI (buildkite): ensure passing --output-sync when passing -j

### PR DESCRIPTION
**Pull request by vtjnash**
To be at feature-parity with old buildbots (assuming the buildkite workers aren't ancient dinosaurs like some of the buildbots).

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Could you explain what this does?

**Comment by DilumAluthge** [comment]
> (assuming the buildkite workers aren't ancient dinosaurs like some of the buildbots)

Just FYI, right now we are only running Buildkite agents on the newer AMDCI machines, but eventually, as we transition everything from Buildbot to Buildkite, we may end up running some Buildkite agents on some of the older machines as well.

**Comment by staticfloat** [comment]
Yes, our grand plan is to not have ancient tool versions anymore, just ancient glibc versions.

**Review by staticfloat — APPROVED** [review]

**Comment by DilumAluthge** [comment]
We need to update the coverage pipeline signature before merging this PR.

**Comment by vtjnash** [comment]
Looks like a I missed the ASAN builder, but I don't see where it called make -j

Separately, the linux32 trampolines seem to have an error in them (according to the linker) @staticfloat

**Pull request merged**
