### PR TITLE
WIP: Attach docstrings inside begin blocks

### PR DESCRIPTION
**Pull request by bramtayl**
Using Keno's one line patch from #15684

### CODE REVIEW

**Comment by bramtayl** [comment]
It seems like the section in "doc/src/manual/documentation.md" starting with "Documentation written in non-toplevel blocks" would need to be updated. I don't know scheme (gasp), so I'm not actually sure how things will change?

**Comment by bramtayl** [comment]
Am I reading the tests right, in that there was only one error in iterators,

```julia
@test eltype(collect(enumerate(Iterators.Filter(x -> x>0, randn(10))))) == Tuple{Int, Float64}
```

Not sure what this has to do with docstrings???

**Comment by bramtayl** [comment]
So I spent a ton of time trying to build julia from source to test out the new features, only now to discover I've built a version that doesn't include said features. Anyway, I've updated the manual based on how I think things will work (i.e. inline docstrings behaving the same way as `@doc`) but someone should probably check first.

**Comment by bramtayl** [comment]
Will this be good to go after a rebase?

**Comment by StefanKarpinski** [comment]
@MichaelHatherly, if this looks good to you, imo, we should go ahead with it.

**Review by MichaelHatherly — APPROVED** [review]
Looks fine to me, though I'm not all that familiar with the parser. If there's any uses of `@doc` in blocks that can now be avoided then it would be good to change those now as well.

(I'm currently travelling over the next few months so responses will likely not be as prompt as usual, though I'll try to work through the notification backlog at least weekly whenever possible.)

**Comment by bramtayl** [comment]
I'm getting confused about what I'm supposed to do next

**Comment by tkelman** [comment]
appveyor is still confused so should probably be rebased again

**Comment by musm** [comment]
does this also work for `let` blocks? i.e.
```julia
let 
global foo

"""
hi
"""
foo(x) = x
end
```

**Comment by bramtayl** [comment]
Yes, from my understanding, any place where could could use this syntax will be in a begin block (or global) in the AST, meaning that docstrings could be attached anywhere.

**Comment by bramtayl** [comment]
Mac failure seems unrelated

**Comment by bramtayl** [comment]
First successful base PR! I'd like to thank the academy and...
Karen's pet snake...
intimidating real life responsibilities....
and last but not least, burritos.

**Comment by musm** [comment]
@bramtayl  any ideas on why this isn't working for `let` blocks?

**Comment by bramtayl** [comment]
No idea sorry. The original patch to the parser was written by Keno and I don't know lisp

**Comment by bramtayl** [comment]
However it does mention in the docs that this is supposed to work with let blocks, which is I guess incorrect. The test I added was only for a begin block; it's possible this has regressed?

**Comment by bramtayl** [comment]
Seems to work in 0.6 for me.

**Comment by musm** [comment]
Try 
```julia
julia> let
       global foo

       """
       hi
       """
       foo(x) = x
       end
```

and then 
```
help?>foo
```
which does not work on 0.6 and master

**Comment by bramtayl** [comment]
Oh yeah sorry definitely doesn't work

**Pull request merged**
