### PR TITLE
fix typo in #31263

### PR DESCRIPTION
**Pull request by dkarrasch**

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by kshyatt** [comment]
Really sorry about this one 😓

**Comment by dkarrasch** [comment]
No worries, @kshyatt. Your documentation enthusiasm is inspiring, I started working on other docstrings to also have "own" contributions, not only fixing others. ;-)

**Comment by kshyatt** [comment]
One of us! One of us!

**Comment by dkarrasch** [comment]
> One of us! One of us!

Here it is: #31274. Find the typo! 😛

**Pull request merged**
