### PR TITLE
optimizer: Julia-level escape analysis (rebase)

### PR DESCRIPTION
**Pull request by ianatol**
This commit ports [EscapeAnalysis.jl](https://github.com/aviatesk/EscapeAnalysis.jl) into Julia base.
You can find the documentation of this escape analysis at [this GitHub page](https://aviatesk.github.io/EscapeAnalysis.jl/dev/)[^1].

[^1]: The same documentation will be included into Julia's developer
      documentation by this commit.

This escape analysis will hopefully be an enabling technology for various
memory-related optimizations at Julia's high level compilation pipeline.
Possible target optimization includes alias aware SROA (#43888),
array SROA (#43909), `mutating_arrayfreeze` optimization (#42465),
stack allocation of mutables, finalizer elision and so on[^2].

[^2]: It would be also interesting if LLVM-level optimizations can consume
      IPO information derived by this escape analysis to broaden
      optimization possibilities.

The primary motivation for porting EA in this PR is to check its impact
on latency as well as to get feedbacks from a broader range of developers.
The plan is that we first introduce EA in this commit, and then merge the
depending PRs built on top of this commit like #43888, #43909 and #42465

This commit simply defines and runs EA inside Julia base compiler and
enables the existing test suite with it. In this commit, we just run EA
before inlining to generate IPO cache. The depending PRs, EA will be
invoked again after inlining to be used for various local optimizations.

### CODE REVIEW

**Comment by ianatol** [comment]
Just rebases #43800 with the changes from #44008

**Comment by ianatol** [comment]
Might as well start nanosoldier here too, I guess:

@nanosoldier `runtests(ALL, vs = ":master")`
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by ianatol** [comment]
Superseded by https://github.com/JuliaLang/julia/commit/bad5206049a28c9d71a2ce08d77873c7c7a820d8

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/44195#issuecomment-1040977131) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/316516c_vs_983598a/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44195#issuecomment-1040977131) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/93f0003_vs_983598a/report.html).

**Pull request closed without merging**
