### PR TITLE
effects: support callsite `@assume_effects` annotation

### PR DESCRIPTION
**Pull request by aviatesk**
`@assume_effects` on method definitions is very useful, but at some times, its application can be too broad on generic signatures. We've addressed this by defining methods specialized for particular types and applying `@assume_effects` to them. However, this method has downsides, such as being restricted to pre-set types or increasing nearly identical method definitions.

To remedy this, this commit introduces a support for callsite `@assume_effects` annotation, enabling finer control over its application. Now the annotations for `@ccall` are just specific instances of callsite `@assume_effects` annotation, so it might be a good idea to replace `@ccall` annotations with callsite `@assume_effects` annotations.

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/52400) failed.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/52400#issuecomment-1841994537) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/5ecb807_vs_2949dd5/report.md).

**Review by vtjnash — APPROVED** [review]
RSLGTM

**Pull request merged**
