### PR TITLE
Fixed Build Warning

### PR DESCRIPTION
**Pull request by 0xAlexS**
I get the following warning when building Julia:

```
    CC src/codegen.o
In file included from /home/alexs/git/julia/src/codegen.cpp:57:
/home/alexs/git/julia/usr/include/llvm/ADT/Statistic.h:38: warning: "LLVM_ENABLE_STATS" redefined
   38 | #define LLVM_ENABLE_STATS 1
      | 

In file included from /home/alexs/git/julia/src/codegen.cpp:3:
/home/alexs/git/julia/src/llvm-version.h:24: note: this is the location of the previous definition
   24 | #define LLVM_ENABLE_STATS 0
      | 
```

To fix the issue, I removed the definition in the llvm-version.h header file. I tested the new build by doing a "make clean" and a "make" to be sure that the build is successful without the definition that I removed in the source code.

### CODE REVIEW

**Comment by vtjnash** [comment]
Huh, this appears to be an ancient bug in the cmake build of LLVM. In particular, `cmake` might add NDEBUG to the compiler flags, but llvm-config doesn't correctly reflect if that flag is getting set, resulting in incorrect compiler flags being used here. In particular, if 
```
`./usr/tools/llvm-config --build-mode` == Release and `./usr/tools/llvm-config --assertion-mode` == OFF
```
Then we need to add `-DNDEBUG` to the cppflags computed to match how cmake computes them.

**Comment by ViralBShah** [comment]
Is this still required? I don't recollect seeing these warnings recently.

**Comment by vtjnash** [comment]
Only present with non-default build options

**Comment by vtjnash** [comment]
We should fix in LLVM perhaps though

**Pull request closed without merging**
