### PR TITLE
Add LIBEXECDIR relative folder constant

### PR DESCRIPTION
**Pull request by musm**
cc @staticfloat  is this how we want the API ? 

Base.LIBEXECDIR return `..\\libexecdir` and users will need to do
```julia
exe7z = joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.exe")
```

This mirrors how some of the other constants are computed.

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by musm** [comment]
I'll also add a basic 7z check test if  I receive further approval on this.

**Comment by rapus95** [comment]
Why not assign an absolute path (like Sys.BINDIR * "../libexecdir") as it is done for Sys.STDLIB? Even though there might be other cases, I think it will be more useful since there is no situation I can think of where one wants the relative path. In other words, if you already propose usage like `joinpath(Sys.BINDIR, Base.LIBEXECDIR, "7z.exe")` then why not directly combine both?

On the other hand, after reading into the new Artifacts-system I became uncertain whether making this a public API is wanted as it is could end in file/version conflicts in that dictionary if not properly managed. What do you think about it?

**Comment by staticfloat** [comment]
The reason why they're not absolute values is because we want Julia itself to be relocatable; if you compile Julia in one location, then move the executable (like when you download it off of the internet) that absolute path is no longer valid.

We actually do [a surprising amount of work](https://github.com/JuliaLang/julia/search?q=julia_bindir&unscoped_q=julia_bindir) in the C runtime to special-case `Sys.BINDIR` such that you can write Julia code that has `Sys.BINDIR` baked into it and still have it work properly after things have been moved around.  We don't want to duplicate that work for a bunch of other constants, so it's easier to have everything else be defined in relation to `Sys.BINDIR`.

We could, of course, export something like `Sys.LIBEXECDIR()` which does the `joinpath()` for you, but that would be a function rather than a `String`, and we'd then change the rest of the similar APIs as well.

**Comment by rapus95** [comment]
> The reason why they're not absolute values is because we want Julia itself to be relocatable; if you compile Julia in one location, then move the executable (like when you download it off of the internet) that absolute path is no longer valid.

That's the exact reason, why I suggested:
> Why not assign an absolute path (like `Sys.BINDIR * "../libexecdir"` ...

I really meant to assign that line into Sys.LIBEXECDIR (Though I guess the first run inlines that, thus inlining and resolving as constant would need to be delayed, or is that the actual problem?). Then it is built relative from bindir but always usable as an absolute path. Best from both worlds in my opinion.

> We could, of course, export something like `Sys.LIBEXECDIR()` which does the `joinpath()` for you, but that would be a function rather than a `String`, and we'd then change the rest of the similar APIs as well.

Is there any way to somehow fill a variable on every new run? (Preventing @pure inlining and constant propagation?) That'd be the way how to fill such a variable. Somewhat like a static const in Java which would be filled upon loading of the class.
If that all doesn't work, then how about providing some function like Sys.dir(:LIBEXECDIR), Sys.dir(:BINDIR) etc or maybe even macros for them? In my opinion the fact that BINDIR gets special casing should be entirely hidden thus making the public api to access the LIBEXECDIR in the same way as the BINDIR would be important for universality. (just my 2 cents)

What do you think about my Artifacts uncertainty?

**Comment by KristofferC** [comment]
FWIW

```
julia> Base.INCLUDEDIR
"../include"

julia> Base.LIBDIR
"../lib"
```

are already relative so might make sense to keep things consistent.

**Comment by rapus95** [comment]
> FWIW
> 
> ```
> julia> Base.INCLUDEDIR
> "../include"
> 
> julia> Base.LIBDIR
> "../lib"
> ```
> 
> are already relative so might make sense to keep things consistent.

So the consistency between BINDIR and the relative ones come from the different module location I guess. whatever DIR is found in Base is to be assumed relative. For Sys it is assumed to be absolute?

**Comment by musm** [comment]
OK test failures are unrelated (  LoadError: LoadError: "hard kill repl test"
) . This is ready on my end.

**Comment by musm** [comment]
It is certainly possible to add a  runtime global const  that gives you `Sys.LIBEXEC`

**Comment by musm** [comment]
However after discussion, adding a runtime global const that gives the absolute path isn't the best course to take. There are plans to replace the whole 7z machinery et. al with  equivalents in pure Julia , which will avoid their need completely. As that is the case @staticfloat and I agree that this is a good solution until then, since we should opt for consistency.

**Comment by musm** [comment]
Should we merge this and add it to 1.3

Yeah I was initially very pro LIBEXECDIR but given the larger plans it's a bit annoying to introduce it then potentially remove it in a future release. However, I suppose it's not so bad since it's guaranteed to only hold 7z  and  the name of the folder  is a variable so it can change (even if an exotic configuration) and thus it's safer to introduce it for robustness.

**Comment by rapus95** [comment]
> Should we merge this and add it to 1.3
> 
> Yeah I was initially very pro LIBEXECDIR but given the larger plans it's a bit annoying to introduce it then potentially remove it in a future release. However, I suppose it's not so bad since it's guaranteed to only hold 7z and the name of the folder is a variable so it can change (even if an exotic configuration) and thus it's safer to introduce it for robustness.

How about labeling it as 1.4 only in the docs and adding a description/link to the upcoming system?

**Comment by musm** [comment]
This is more relevant to address in 1.3, since the libexec changes happened  in this release.

**Comment by rapus95** [comment]
Ah, well, of course my question should be rephrased: How about specifying 
that the constant will be available only until version 1.x where it will be 
replaced with a new, better system?

Am 12. November 2019 16:42:31 schrieb "Mustafa M." <notifications@github.com>:

**Comment by nalimilan** [comment]
I don't think we need to remove this in a future release. We also provide `LIBDIR`, which isn't going to be removed, and the cost of an additional variable is quite low.

**Review by staticfloat — APPROVED** [review]

**Comment by musm** [comment]
@staticfloat if you approve can you merge this or are you waiting on someone else to also review? 

> I don't think we need to remove this in a future release. We also provide `LIBDIR`, which isn't going to be removed, and the cost of an additional variable is quite low.

Sure, but at the same time I think it will be empty on windows after removing 7z since it's the only exe that lives in the folder on Windows. (Not arguing against, just thought I should mention this)

**Comment by staticfloat** [comment]
`LIBEXECDIR` being empty is fine; there's no reason to drop it; it's a standard filesystem path.

**Comment by rapus95** [comment]
Those are where my question was pointing to, whether the usage by packages 
will soon be discouraged in favour of the new artifacts system?

Am 12. November 2019 18:28:34 schrieb Milan Bouchet-Valat 
<notifications@github.com>:

**Comment by nalimilan** [comment]
@KristofferC Do you think this can be backported to 1.3? Since the 7z change has been introduced in that release, it would be cool to provide the solution to access it too.

**Comment by KristofferC** [comment]
@staticfloat, please squash PRs like this.

**Comment by KristofferC** [comment]
It's on the backport branch npw.

**Comment by musm** [comment]
Thanks @KristofferC !

**Comment by musm** [comment]
BTW since this and the other constants defined in the same file are private, this doesn't need a news item right?   (In all the other constants are undocumented)

**Pull request merged**
