### PR TITLE
Decouple setjmp and longjmp assembly from openlibm headers

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by nalimilan** [comment]
+1 for no longer hardcoding paths int the openlibm tree.

**Comment by ViralBShah** [comment]
:+1:

**Comment by tkelman** [comment]
I think I'll need to copy over the license header, annoyingly.

**Comment by vtjnash** [comment]
lgtm.

i'm not a lawyer, but this doesn't particularly seem like a derived work to me; I think you could take full ownership of these files, rather than copying the license from openlibm.

**Comment by tkelman** [comment]
ianal either which is why I'd rather be on the safe side, this definitely required referencing that file and ensuring the content matched.

**Comment by vtjnash** [comment]
i was also the original contributor of the relevant code that you would have referenced (https://github.com/JuliaLang/openlibm/commit/3c8738e6422bcd38320b2eb69fdbde0422fd6372).

**Comment by tkelman** [comment]
Ah, good to know. The non-Windows lines come from https://github.com/JuliaLang/openlibm/commit/f0862df1db8b67be5dbab1bcfd11015a181df4f8, but also aren't strictly speaking necessary for the current uses of these files.

**Comment by tkelman** [comment]
So, merge as is, or remove non-Windows pieces along with the license headers?

**Comment by tkelman** [comment]
If no comments otherwise I'll merge as-is in a day or two.

**Comment by vtjnash** [comment]
i was hoping someone else would evaluate the license as well. i don't think anything in that file can really be claimed as copyrightable, but it would be good to get a second opinion too

**Comment by tkelman** [comment]
@JeffBezanson is our usual closest-thing-to-almost-a-lawyer...

**Comment by ViralBShah** [comment]
Also worthy seeing what @andygreenwell has to say.

**Comment by tkelman** [comment]
Bump again. I'm not opposed to taking out the non-Windows pieces here so there's no license ambiguity, but it will make it more annoying to put back together if we migrate these over to openlibm in the future for MSVC compatibility there.

**Pull request merged**
