### PR TITLE
Use a codeunit type-assert that is easier for inference to elide

### PR DESCRIPTION
**Pull request by timholy**
Circumvents #37135

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by omus** [comment]
I was working on a performance improvement for `==(::AbstractString, ::AbstractString)` but I discovered this PR addresses the performance issue I was noticing (mostly allocations):

Before this PR (6aee988223):

```julia
julia> str = "A" ^ 1000;

julia> @btime invoke(==, Tuple{AbstractString, AbstractString}, $"ABC", $"ABC")
  4.357 ns (0 allocations: 0 bytes)
true

julia> @btime $(SubString("ABC")) == $"ABCD"
  29.574 ns (2 allocations: 64 bytes)
false

julia> @btime $(SubString("ABC")) == $"ABC"
  32.492 ns (2 allocations: 64 bytes)
true

julia> @btime $(SubString("ABC")) == $"DEF"
  31.985 ns (2 allocations: 64 bytes)
false

julia> @btime $(SubString(str)) == $str
  65.086 ns (2 allocations: 64 bytes)
true
```

With this PR (dbf5e005d9):

```julia
julia> str = "A" ^ 1000;

julia> @btime invoke(==, Tuple{AbstractString, AbstractString}, $"ABC", $"ABC")
  3.907 ns (0 allocations: 0 bytes)
true

julia> @btime $(SubString("ABC")) == $"ABCD"
  0.033 ns (0 allocations: 0 bytes)
false

julia> @btime $(SubString("ABC")) == $"ABC"
  4.003 ns (0 allocations: 0 bytes)
true

julia> @btime $(SubString("ABC")) == $"DEF"
  3.282 ns (0 allocations: 0 bytes)
false

julia> @btime $(SubString(str)) == $str
  38.978 ns (0 allocations: 0 bytes)
true
```

I'll be adding some benchmarks for this.

**Comment by KristofferC** [comment]
Is this v1.5? Because AFAIU this just fixed an earlier regression on nightly. But good to have benchmarks anyway.

**Comment by omus** [comment]
I noticed similar slow performance on Julia 1.3.1, 1.4.2, and 1.5.1. All of these versions were substantially worse with the final test:
```julia
julia> @btime $(SubString(str)) == $str
  4.043 μs (2 allocations: 112 bytes)
true
```

**Comment by KristofferC** [comment]
Seems more likely that the improvement here was because of https://github.com/JuliaLang/julia/pull/35973

**Comment by omus** [comment]
You are correct that https://github.com/JuliaLang/julia/pull/35973 is the main driver behind the performance improvement. I'll update my benchmarks to reflect this.

**Comment by omus** [comment]
I've also opened https://github.com/JuliaLang/julia/pull/37467 which improves performance of the fallback `==(::AbstractString, ::AbstractString)` call.

**Pull request merged**
