### PR TITLE
Make Regex a scalar in broadcasting

### PR DESCRIPTION
**Pull request by fredrikekre**
https://github.com/JuliaLang/julia/pull/29913/files?w=1 for the real diff.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Diff best seen ignoring whitespace; related: don't squash since there's a testset-introducing commit.

**Review by mbauman — APPROVED** [review]

**Comment by mbauman** [comment]
Ref https://github.com/JuliaLang/julia/issues/29250 (would close it if it weren't already closed).

**Comment by fredrikekre** [comment]
Had to move the definition from `regex.jl` to `broadcast.jl` for bootstrapping reasons.

**Comment by mbauman** [comment]
@KristofferC https://github.com/JuliaLang/julia/pull/29913/files#diff-8312ad0561ef661716b48d09478362f3R17

**Comment by KristofferC** [comment]
Missed that, sorry.

**Pull request merged**
