### PR TITLE
release-1.9: set VERSION to 1.9.0-alpha1

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Can you hold off on merging this until we have created the Buildkite pipeline for 1.9?

(CI won't run on the `release-1.9` branch until that pipeline is created.)

I'll create the pipeline later today (unless Elliot beats me to it).

**Comment by DilumAluthge** [comment]
I'm in the process of finishing the setup of the pipeline. I'll post an update here when it's done.

**Comment by DilumAluthge** [comment]
The `release-1.9` Buildkite pipeline is now available here: https://buildkite.com/julialang/julia-release-1-dot-9

The instructions for creating a new `release-1.N` Buildkite pipeline will be added to the devdocs here: https://github.com/JuliaCI/julia-buildkite/pull/248

**Review by ararslan — APPROVED** [review]
😎

**Review by DilumAluthge — APPROVED** [review]
Looks like CI is working correctly.

**Pull request merged**
