### PR TITLE
Handle setfield! in alloc_elim_pass

### PR DESCRIPTION
**Pull request by carnaval**
Probably does not come up very often but was added to allow for generic code with mutable accumulators such as

``` julia
mut_zero(::Type{BigFloat}) = zero(BigFloat)
function mut_add!(x::BigFloat, y::BigFloat)
    ccall((:mpfr_add,:libmpfr), Int32, (Ptr{BigFloat}, Ptr{BigFloat}, Ptr{BigFloat}, Int32), &x, &x, &y, Base.MPFR.ROUNDING_MODE[end])
end

mut_zero(::Type{Float64}) = Ref(0.0)
mut_add!(x,y) = x[] += y
Base.convert(::Type{Float64}, r::Ref{Float64}) = r[]
```

then write

``` julia
function sum{T}(vs::Vector{T})
    acc = mut_zero(T)
    for v in vs
        mut_add!(acc,v)
    end
    convert(T, acc)
end
```

and get efficient scalar code in the Float64 case

@andreasnoack

### CODE REVIEW

**Comment by yuyichao** [comment]
:+1: I didn't do this last time because I worry being more aggressive here might make the codegen bug worse.

**Comment by JeffBezanson** [comment]
Cool!

While you're at it, it would be good to see if alloc_elim_pass can be sped up at all, since I've seen some profiles that indicate a fair amount of time is spent there.

I would also like to see comments illustrating the transformation done, i.e. showing example IR fragments and what they get converted to.

**Comment by carnaval** [comment]
> While you're at it, it would be good to see if alloc_elim_pass can be sped up at all, since I've seen some profiles that indicate a fair amount of time is spent there.

do you have an example benchmark where this is particularly evident that I can use as a basis ?

> I would also like to see comments illustrating the transformation done, i.e. showing example IR fragments and what they get converted to.

can do

**Comment by JeffBezanson** [comment]
It was one that @andreasnoack ran into:

```
a = rand(5,5);
LinAlg.generic_matmatmul!(a, 'N', 'N', a, a);
```

I don't think this pass is more than half the time, but I was hoping there might be low-hanging fruit there. In particular a lot of time is spent in `occurs_outside_getfield`.

**Comment by timholy** [comment]
With apologies for hijacking this for unrelated purposes, see https://github.com/JuliaLang/julia/issues/16128#issuecomment-226594988

@nanosoldier `runbenchmarks(ALL, vs=":release-0.4")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16969#issuecomment-226595602) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/66908d6349ded33ea16c61431f9cf7710e5ec402/cab5fa2_vs_d398d4e/report.md). cc @jrevels

**Comment by vtjnash** [comment]
This looks pretty cool. The benchmarks are all over the place though: some got faster, some slower.

**Comment by jrevels** [comment]
> The benchmarks are all over the place though: some got faster, some slower.

Note that Tim ran the benchmarks here against the `release-0.4` branch, not `master` (I think at the time he didn't know that benchmarks could be run from commits, so he hijacked this PR to do a comparison).

**Comment by andreasnoack** [comment]
@nanosoldier runbenchmarks(ALL, vs=":master")

**Comment by yuyichao** [comment]
Quote?

**Comment by jrevels** [comment]
Nanosoldier doesn't accept jobs via comment edits (assuming that's what happened here). It used to, but I considered that a bug and fixed it (since it easily allowed jobs to accidentally get re-triggered, or triggered on comment deletion).

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by andreasnoack** [comment]
Thanks and I can see that the soldier actually changes color so I should have noticed.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16969#issuecomment-233209601) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2432c36d008722f869797d51d26c529ffb8b8a05/01fcea6_vs_39b9d7d/report.md). cc @jrevels

**Comment by andreasnoack** [comment]
@carnaval Do you have an idea why this would slow down `setindex!`? See https://github.com/JuliaCI/BaseBenchmarkReports/blob/2432c36d008722f869797d51d26c529ffb8b8a05/01fcea6_vs_39b9d7d/report.md

**Comment by Keno** [comment]
We have this now

**Pull request closed without merging**
