### PR TITLE
Corrected precedence ordering (2)

### PR DESCRIPTION
**Pull request by hiAndrewQuinn**
`Base.operator_precedence` lists `>> << >>>` as having a lower precedence than `//` and `*`, but a `dump` of a few expressions reveals this to be a bug in `operator_precedence`. It in fact has higher precedence.

See [this error in the Julia documentation](https://github.com/JuliaLang/julia/pull/32944) for more.

(I had [another PR](https://github.com/JuliaLang/julia/pull/32962) but it failed code tests due to trailing whitespace. Oops!)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Thanks for the fix! I added some tests to make sure that `Base.operator_precedence` reports the correct precedence and—what do you know—I found another case that's reported incorrectly.

**Comment by 8ERdv1dXa7v8** [comment]
I probably shouldn't be surprised the cofounder of the language writes in it so expressively. Dang. I think you just taught me how to do basic unit testing in Julia with that single example.

**Comment by StefanKarpinski** [comment]
Ah crap, the doctest failure is real. Will fix.

**Comment by StefanKarpinski** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/32965.

**Comment by c42f** [comment]
@AndrewQuinn2020 thanks! Just a note on github usage: rather than opening multiple pull requests, it's best to push additional changes to your branch and they will show up on the original pull request. This keeps the discussion coherent.

It's also generally a good idea to make your pull request based off a branch in your clone of the julia repo (rather than your master branch `AndrewQuinn2020:master`). This way the github pull requests don't get mixed up if you make more than one pull request at once.

**Pull request merged**
