### PR TITLE
Bump `Pkg` version to include fix to git tree hash calculation

### PR DESCRIPTION
**Pull request by staticfloat**
This fixes some recently-reported issues with restrictive `umask`'s and
the `Pkg.Artifacts` git tree hash calculation.

X-ref: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/527

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
This fix alone would be a candidate for a very quick 1.3.1 release since the umask artifact issue is rather bad.

**Comment by giordano** [comment]
Does this include improvement of loading time of jll packages? Also that would be good to have in 1.3.1

**Comment by staticfloat** [comment]
> This fix alone would be a candidate for a very quick 1.3.1 release since the umask artifact issue is rather bad.

Note that this is to update `master`; to update `release-1.3` we should use a separate PR that bases itself off of @fredrikekre's very helpful [1.3 backports branch](https://github.com/JuliaLang/Pkg.jl/pull/1480).

> Does this include improvement of loading time of jll packages? Also that would be good to have in 1.3.1

Yes, both this PR and Fredrik's 1.3 backporting branch contain the speedups.

**Comment by KristofferC** [comment]
For precompilation time of jll packages we also need to use some of the artifact functionality in the precompile script.

**Comment by KristofferC** [comment]
Should include https://github.com/JuliaLang/Pkg.jl/pull/1517 here as well, since right now, master is pretty broken for packages overall.

**Comment by staticfloat** [comment]
> For precompilation time of jll packages we also need to use some of the artifact functionality in the precompile script.

We could do something like download a JLL package into the Julia source directory (before the build) and install the artifacts somewhere, then `using` it within the precompile script to precompile the loading code (but not the downloading code).  Is that what you have in mind?

**Comment by KristofferC** [comment]
> We could do something like download a JLL package into the Julia source directory (before the build) and install the artifacts somewhere, then using it within the precompile script to precompile the loading code (but not the downloading code). Is that what you have in mind?

Yeah, just bundle something with Pkg that allows us to use the `artifact` macro in the precompile script.

**Comment by staticfloat** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/1521

**Pull request merged**
