### PR TITLE
fix #15597

### LINKED ISSUE #15597: `ERROR: syntax: malformed expression` in parsing `0x`
Hi, 

Not sure this can be considered as a bug or what, feel free to close it. Here is a demo:

```julia
julia> x = 32
32
julia> 2x
64
julia> 1x
32
julia> 0x
ERROR: syntax: malformed expression
julia> typeof(0x00)
UInt8
```

I understand why the syntax error is given, but I feel one should be able to write `0x` to mean `0*x` as easily as with other numbers.

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vtjnash** [comment]
lgtm

**Comment by JeffBezanson** [comment]
On 64-bit AV:

```
	From worker 14:	     * threads              Test Failed
	From worker 14:	  Expression: delay2 > 0.05
	From worker 14:	   Evaluated: 0.0492253 > 0.05
```

Looks like an intermittent, time-sensitive thing.

**Comment by tkelman** [comment]
added by e85cc680b7ed7e46a6ba39ae1170f7296b21790f - didn't we learn our lesson about time-dependent tests?

**Comment by nalimilan** [comment]
@vtjnash Could you disable that test?

**Pull request merged**
