### PR TITLE
Upgrade libgit2 and curl

### PR DESCRIPTION
**Pull request by tkelman**
These include security fixes so we should probably upgrade these, despite the feature freeze and lack of testing so far. Hopefully these shouldn't be noticeable changes from the Julia side.

### CODE REVIEW

**Comment by tkelman** [comment]
I ran these through all the buildbots and everything seemed okay, so will merge tomorrow if no one objects.

**Review by simonbyrne — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Hard to imagine what the objection would be...

**Review by ararslan — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
If you ran PkgEval on this and there weren't any problems, there's only one way we're going to find out if it's an issue – merge it and see.

**Comment by tkelman** [comment]
buildbots, not pkgeval

**Comment by StefanKarpinski** [comment]
Yeah, I edited my comment.

**Pull request merged**
