### PR TITLE
Run doc/genstdlib.jl after bootstrap, take 2

### PR DESCRIPTION
**Pull request by tkelman**
this time with a JULIA_ENABLE_DOCBUILD flag to allow disabling this step on the buildbots
where #11727 causes trouble on windows

ref #13069

### CODE REVIEW

**Comment by tkelman** [comment]
Codegen assertion failure is a real issue, can reproduce locally.

**Comment by tkelman** [comment]
Restarted the merge ci builds, codegen issue is fixed on master.

**Comment by tkelman** [comment]
This should be mergable if we want to try this. Now has an escape hatch we can make the buildbots use.

**Comment by jakebolewski** [comment]
Bump, I think we should try this.

**Comment by ScottPJones** [comment]
I am now seeing `modified: doc/stdlib/base.rst` when I run `git status`, apparently because of this.
If that is now generated, shouldn't it be added to the `.gitignore` file? Or is something else going wrong?

**Comment by tkelman** [comment]
Depends on the diff. It's only partially autogenerated so should not be in gitignore.

**Comment by ScottPJones** [comment]
OK - it's painful then that it keeps coming up as modified when I build from source, even without any doc changes.

**Comment by MichaelHatherly** [comment]
Please post a gist of the diff @ScottPJones.

**Comment by ScottPJones** [comment]
Doesn't even need a gist - it's just:
```
--- a/doc/stdlib/base.rst
+++ b/doc/stdlib/base.rst
@@ -1384,3 +1384,4 @@ Internals
    .. Docstring generated from Julia source
 
    Compile the given function ``f`` for the argument tuple (of types) ``args``\ , but do not execute it.
```

**Comment by JeffBezanson** [comment]
I see the same thing.

**Pull request merged**
