### PR TITLE
Make inbounds macros expression-like

### PR DESCRIPTION
**Pull request by StefanKarpinski**
In which I steal @mbauman's PR: https://github.com/JuliaLang/julia/pull/15558. Sorry Matt, your branch was not setup to allow me to force push it, so I just made my own to get this rebased.

### CODE REVIEW

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-350891807) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a63b00a26a400549c72a07a2eb1a3b678fa896db/cac9714_vs_66b2090/report.md). cc @ararslan

**Comment by StefanKarpinski** [comment]
Circle CI is a timeout so it seems unrelated. Any care to interpret whether the slow downs are real or not here?

**Review by andyferris — APPROVED** [review]

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-351663564):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4db6fd1258643ba4959c2edb083891d76f943938/f458885_vs_d192302/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Things moving to stdlib broke Nanosoldier, I'm working on fixing it now

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
I got a 400 from Nanosoldier so I restarted the server. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-352084321):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/34e112bdf73d0571166cd08e7f4037de2f4c026c/1092fcc_vs_7cfcca2/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Sorry, one more change is needed, working on that now.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-352211897):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e4b729dacdf903715f4d50d46379d8ddf9cd2dfe/22e7665_vs_fbbdaeb/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Okay, I think I know what happened. Should be fixed now... I hope. Sorry for guinea pigging you, Stefan. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-352216137):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/93e172e08deafe4fbaff5dd527c6a4fdeb3118f8/cd814fd_vs_e89a2b8/report.md)
cc @ararslan

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
Had to restart the server. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/25033#issuecomment-352601866) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ac09a86d2eac1629dafd90d6ac779248048ef31d/2293d23_vs_07740b6/report.md). cc @ararslan

**Comment by vchuravy** [comment]
LGTM.

**Comment by ararslan** [comment]
So much has changed in the 7 days since this was opened that we should rerun CI before merging just in case.

**Comment by StefanKarpinski** [comment]
Oh wow, legitimately no performance regressions. Nice.

**Comment by ararslan** [comment]
Plus both Circle failures are unrelated, so I'd say this is good to go!

**Pull request merged**
