### PR TITLE
Fix borked mmap deprecations

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
The OSX failure looks unrelated (further up in the build process); can anyone confirm before I merge this?

**Comment by tkelman** [comment]
was a timeout, I restarted the PR build

**Comment by IainNZ** [comment]
Seems to have happened again?

**Comment by tkelman** [comment]
did someone else restart the pr build a second time? i didn't restart the push build, that one was a strange clang internal error? https://gist.github.com/tkelman/b5ef2226c575c2613933

**Comment by quinnj** [comment]
Yeah, the push build has the weird OSX clang error. We're good to merge, right?

**Comment by tkelman** [comment]
lgtm

**Pull request merged**
