### PR TITLE
small change in rational constructor

### PR DESCRIPTION
**Pull request by Jutho**
This small change is required for a custom type of mine that represents integers as their prime factorization. In this format, `*`, `lcd` and `gcd` are easy, and so is `divgcd`. However, general `div` is not necessarily easy.

This PR also fixes consistency. On master `divgcd` is used in the various `//` methods, but not in the actual `Rational` constructor itself.

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
Seems reasonable enough to me. Anyone have any objections to this change? I guess my one concern is checking the sign of the denominator. But I suppose if one uses a type where sign doesn't make sense, it can always just return 1.

**Comment by tkelman** [comment]
should probably @nanosoldier `runbenchmarks(ALL, vs=":master")` just in case, though not sure how thoroughly rationals are covered

**Comment by Jutho** [comment]
Thanks for the review. The `sign` part was something I added in the second commit, since my `PrimeFactorization` type does not even support comparing two arbitrary numbers easily (i.e. without converting to another format). However, getting the `sign` is easy I could certainly just write a method for `<` that deals with the comparison to zero. There are probably other cases where `sign` doesn't make sense, so I could undo this second commit.

**Comment by StefanKarpinski** [comment]
If `den < 0` works then `sign(den)` probably should as well, so this seems fine. Perhaps the `divgcd` function should include the normalization so that the first value is always positive when that makes sense? That way each type can define this in a way that works for it.

**Comment by Jutho** [comment]
`divgcd` does not seem to be used in base outside of rational.jl, so I can change that if you like (though that behaviour is not explicitly implied by the name of the function).

I am fine with any suggestion that gives me a handle on modifying the construction of `Rational{MyType}`. Since `Rational{T}` uses an inner constructor, it did not seem possible to modify its behaviour for my particular `T=MyType` other than creating this PR.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23174#issuecomment-321038694) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b361a4dea2b41b906771ecf3338fcaeb617667a7/4f51228_vs_edbcb91/report.md). cc @ararslan

**Comment by Jutho** [comment]
Those benchmark results seem unbelievable; is everything running correctly? If so, than I will have to check what is going on, but most of these regressions seem completely independent of `Rational` at first sight.

**Comment by fredrikekre** [comment]
Likely some noise? Let's rerun
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23174#issuecomment-321100765) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/beac093dc70626ada57a84fcfb43fdf855f5035b/ba69e50_vs_676faec/report.md). cc @ararslan

**Comment by Jutho** [comment]
All regressions from latest benchmark seem to fall just outside of the tolerance window, so I guess it is still noise?

@StefanKarpinski , would you like me to change `divgcd` as you proposed, or are you fine with the current implementation?

**Comment by StefanKarpinski** [comment]
I'm cool with your current PR. If it comes up in the future, we can always introduce a new factorization point for this and I think `divgcd`'s current behavior is what it should do.

**Comment by Jutho** [comment]
Ok great. And you agree with my assessment that the benchmark regressions are noise? Is CI always so unreliable these days? Any other requests/requirements before this can be merged?

PS: This is what motivated this PR -> https://github.com/Jutho/WignerSymbols.jl

**Comment by StefanKarpinski** [comment]
Regressions are probably noise.

> Is CI always so unreliable these days?

Yes. @travis-ci has been oversubscribing their machines for months now and it has made their service (which we pay for) completely useless since it never actually passes. We have raised the issue with them multiple times and so far they have not managed to do anything helpful. @AppVeyor  is not usually too bad – they should consider offering Linux and/or Mac CI to take advantage of the situation and get some new customers. We would happily jump ship from Travis at this point, and we are, in fact actively investigating switching to @CircleCI, which seems to have much better performance (https://github.com/JuliaLang/julia/pull/23188).

**Comment by fredrikekre** [comment]
Lets rerun CI, but should be good to go?

**Comment by Jutho** [comment]
Thanks

**Pull request merged**
