### PR TITLE
release-1.7: set VERSION to 1.7.0-rc1

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
Should probably fix https://github.com/JuliaLang/julia/issues/42150 first.

**Comment by PallHaraldsson** [comment]
It seems #42201 isn't in (its issue on 1.7 milestone) release-1.7 branch, and should, even though you force-pushed.

**Comment by KristofferC** [comment]
I didn't really understand that.

**Comment by aviatesk** [comment]
@KristofferC how should we backport https://github.com/JuliaLang/julia/pull/42125 into `release-1.7` ?

**Comment by KristofferC** [comment]
To me that looks like a feature and is pretty late for the feature freeze. Am I wrong in that?

**Comment by aviatesk** [comment]
Yes, it certainly adds new features (enable constant-prop' to be disabled). But the reason why we want to backport it is that it generalizes and renames  `@aggressive_constprop`, which was introduced in v1.7, and we don't want to release `@aggressive_constprop` into the wild.

/cc @timholy

**Comment by KristofferC** [comment]
`@aggressive_constprop` already looks used in the wild and it is internal anyway. And it doesn't seem hard to silently deprecate `@aggresive_constprop`into `@constprop :aggressive`?

**Comment by timholy** [comment]
I can easily make PRs against the 6 known packages that use `@aggressive_constprop`, but I'm fine either way. There's already `Compat.@constprop` which implements the new interface on Julias that have `@aggressive_constprop`.

**Pull request merged**
