### PR TITLE
Fix conversion of Float16 and BigFloat to Bool

### PR DESCRIPTION
**Pull request by tkelman**
ref https://github.com/JuliaLang/julia/pull/12378/files#r35858805

ignore what was formerly here, these are all needed to resolve ambiguity warnings

### CODE REVIEW

**Comment by tkelman** [comment]
Oh wow that `# to resolve ambiguity` comment dates back over 3 years - 031e51437855d2bec310470ce0017d599d6926da

Probably not the case any more.

**Comment by hayd** [comment]
Why define this at all?

**Comment by tkelman** [comment]
There are ambiguities since Bool is a subtype of Integer. My first try at this took out these lines since both Float16 and BigFloat are subtypes of Real, but there are warnings during bootstrap.

**Comment by kshyatt** [comment]
Nice. I'll update my PR once this gets merged.

**Comment by hayd** [comment]
(Oops, sorry, I meant why not define this as Inexact for every float? But I see this is the definition used for Ints and Floats, makes sense to be consistent!)

**Pull request merged**
