### PR TITLE
Fix PkgId repr

### LINKED ISSUE #52793: repr of a PkgId isn't usable
```
julia> repr(Base.PkgId(Base.UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb"), "REPL"))
"REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb]"
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #52793 

```
% ./julia  --startup-file=no -E 'repr(Base.PkgId(Base.UUID("295af30f-e4ad-537b-8983-00126c2a3abe"), "Revise"))'
"Base.PkgId(UUID(\"295af30f-e4ad-537b-8983-00126c2a3abe\"), \"Revise\")"
```
```
julia> Base.PkgId(Base.UUID("295af30f-e4ad-537b-8983-00126c2a3abe"), "Revise")
Revise [295af30f-e4ad-537b-8983-00126c2a3abe]
```

Although `UUID` should be `Base.UUID` otherwise this is only usable in Base.

Also interpolation seems to be using the wrong show method?

```
julia> pkgid = Base.PkgId(Base.UUID("295af30f-e4ad-537b-8983-00126c2a3abe"), "Revise")
Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> "$pkgid"
"Base.PkgId(UUID(\"295af30f-e4ad-537b-8983-00126c2a3abe\"), \"Revise\")"
```

### CODE REVIEW

**Comment by stevengj** [comment]
In Julia 1.10, interpolation is calling the expected `show` method:
```jl
julia> pkgid = Base.PkgId(Base.UUID("295af30f-e4ad-537b-8983-00126c2a3abe"), "Revise")
Revise [295af30f-e4ad-537b-8983-00126c2a3abe]

julia> "$pkgid"
"Revise [295af30f-e4ad-537b-8983-00126c2a3abe]"
```

**Comment by IanButterworth** [comment]
Indeed. This PR breaks that. I'm not sure how to achieve both a usable repr and the nice interpolation version

**Comment by stevengj** [comment]
The missing qualification of `Base.UUID` is apparently due to the [UUID show method](https://github.com/JuliaLang/julia/blob/b4d857be0c05ce6c7840694d1a0241e67ff9732f/base/uuid.jl#L104):
```jl
julia> Base.UUID("295af30f-e4ad-537b-8983-00126c2a3abe")
UUID("295af30f-e4ad-537b-8983-00126c2a3abe")
```
which should probably be defined as:
```jl
show(io::IO, u::UUID) = print(io, UUID, "(\"", u, "\")")
```
so that it uses the `show` machinery for the type name.

**Comment by stevengj** [comment]
> I'm not sure how to achieve both a usable repr and the nice interpolation version

Interpolation calls `print`, which by default calls the 2-argument `show`.  What do you want the interpolation to look like?

**Comment by IanButterworth** [comment]
What I think would make sense and be helpful would be 
```
julia> "$pkgid did something"
"Revise [295af30f-e4ad-537b-8983-00126c2a3abe] did something"

julia> "$(repr(pkgid))"
"Base.PkgId(UUID(\"295af30f-e4ad-537b-8983-00126c2a3abe\"), \"Revise\")"

julia> repr(pkgid))
"Base.PkgId(UUID(\"295af30f-e4ad-537b-8983-00126c2a3abe\"), \"Revise\")"
```

**Comment by stevengj** [comment]
That's not the way string interpolation works with any other type of object AFAIK…

**Comment by inkydragon** [comment]
Only ":windows: build i686-w64-mingw32" failed in 4s.
So, LGTM?

**Comment by vtjnash** [comment]
I was just reading through the loading.jl file in detail, and it seems like this failed to update most of the places that I think would be expected, such as `$modkey` or `$req_key` or `isprecompiled`. Do we fix those or revert this for v1.11, or is that intended?

**Comment by KristofferC** [comment]
Just fix them up I guess. This is still an improvement to make the `show` method follow the documentation of `show` and `repr` as in https://github.com/JuliaLang/julia/issues/52793#issuecomment-1881090319.

**Pull request merged**
