### PR TITLE
Revert broadening of arithmetic `Any` methods (revert #44564 and #45320)

### LINKED ISSUE #45463: revert broadening of arithmetic Any methods
PR https://github.com/JuliaLang/julia/pull/45320 removed a couple of ~ancient~ recent and dicey overly generic methods for arithmetic operators: `+(x) = x` and `*(x) = x`. But it left equally generic fallbacks like `-(x) = Int8(-1)*x` and `-(x, y) = x + (-y)`. I would argue that these should also require subtyping `Number` to opt into them. This is potentially a breaking change, but it seems weird to expect these things to work if your type isn't a number (and most other numbery things don't work). I would argue that the policy should be: if you don't subtype `Number` then you don't get any arithmetic fallbacks, you only get fallbacks that truly make sense for all objects.

Btw, several times people have insisted on specification of what the "interface for `Number`" is. There is no interface for `Number`, it is not an interface—there are no requirements that must be satisfied by a `Number`. What `Number` is, is a way to opt into a bunch of generic behaviors like these.

### PR DESCRIPTION
**Pull request by DilumAluthge**
See #45463 for context.

---

Reverts #44564 (reverts cf1f717700ada2784575c969d7114b3416e4f138)
Reverts #45320 (reverts 990b1f3b1a254963bd71ceada44a560161225afb)
Fixes #45463

### CODE REVIEW

**Comment by daanhb** [comment]
I had a failing test in one of my packages and narrowed it down to a change in left division after #44564:
```julia
julia> a = BigFloat(1)
1.0

julia> 3 \ a
0.333333333333333314829616256247390992939472198486328125
```
There is loss of accuracy because left division started doing `inv(3) * a`. This might happen in more packages with high precision calculations.

**Comment by dkarrasch** [comment]
Ok, then it's clear that this here needs to be merged. I resolve the merge conflict and merge after tests pass, unless someone beats me to it.

One conclusion from this whole tour then is that we should be clearer in the docstrings for left-division about what the actual fallback is. The `x \ y = inv(x) * y` idea was taken from the docstring, which otherwise does not state that for custom types, you need to have right-division and `adjoint` (or `conj` for `Number`-subtypes) defined.

**Review by dkarrasch — APPROVED** [review]

**Comment by daanhb** [comment]
To be fair, I should be careful anyway about assuming that `3 \ a` will give the right answer without converting 3 to the type of `a` in my case. I just wanted to point out that, as things stand, the change breaks some packages. I'll be changing my offending code regardless of the outcome here.

(In general, division might be safer than computing an inverse, but I did not think this through.)

**Comment by DilumAluthge** [comment]
The `Test i686-linux-gnu` failures are https://github.com/JuliaLang/julia/issues/46159

**Pull request merged**
