### PR TITLE
Fix out of tree builds failing to copy base files

### LINKED ISSUE #31140: Out of tree builds fails to copy base julia files
Running  the julia  installer after running `make -C outdir binary-dist` from cygwin for a windows build.

`share/julia/base` only includes the files:
image

### PR DESCRIPTION
**Pull request by musm**
Close https://github.com/JuliaLang/julia/issues/31140

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Review by vtjnash — DISMISSED** [review]
Actually, I'm not sure. I think this just switches which files we are missing? Since we need to eventaully merge the contents of `$(JULIAHOME)/base` and `$(BUILDROOT)/base` (e.g. just "base", since BUILDROOT is `$(pwd)`), perhaps there needs to be an explicit copy during install?

**Comment by musm** [comment]
That seems like an unrelated issue that should be fixed separately from this PR. 

I think I understand what you are getting at. In the `$BUILDROOT/base`  folder we have the output  of the  build/makefile  process, but then they just get copied to  $(build_datarootdir)/julia .    

I'm not sure if that logic makes sense or needs to be tweaked but that should be a separate issue PR in my opinion. It would be good to have this fix for the core issue and then address the problem you mentioned separately.

**Comment by musm** [comment]
In summary:
`base/makefile` builds to `$BUILDROOT/base` which at some point gets copied to   `$build_datarootdir/julia/base`
we symlink directory  `$JULIAHOME/base`  to   `$build_datarootdir/julia/base`

`$BUILDROOT/base`  only holds the contents of `base/makefile`

**Comment by vtjnash** [comment]
Right, so another approach might be to separate out the generated artifacts (outputs) from the source code (inputs) to make it less complicated to have both. The other concern with this change is that the source folder right now might contain (autogenerated) files that are unrelated to the OOT build.

One final option would be to replace this with `cp -r`, so that the source archive is more independent of changes to the input folder.

**Comment by musm** [comment]
Ok I'm getting confused with the terminology you are using:  source archive and  input  folder  (which folders exactly do you mean?)

**Your proposal 1:**

> Right, so another approach might be to separate out the generated artifacts (outputs) from the source code (inputs) to make it less complicated to have both.

The generated artifacts (i.e. the output of  base/Makefile build to `$BUILDROOT/base` . At this point this is independent of the source code  (i.e. `$JULIAHOME/base` ).   

What exactly are you proposing with this option? 


**Your proposal 1:**

> One final option would be to replace this with cp -r, so that the source archive is more independent of changes to the input folder. 

I'm not sure if this is a great option.  If you then want to modify base files, i.e. through Revise, then the changes would have to be made in `$build_datarootdir/julia/base`  to be picked up by julia.exe, which would be annoying since then you would have copy the changes back to `$JULIAHOME`

**Comment by musm** [comment]
In any case, I don't think this PR fixes all the issues....

**Comment by musm** [comment]
Should I close this?

**Comment by musm** [comment]
Stle: this is ok, but there is probably a better solution, so closing.

**Pull request closed without merging**
