### PR TITLE
Benchmark new optimizer

### PR DESCRIPTION
**Pull request by Keno**
Opening this PR to have nanosoldier run over the new optimizer

TODO:

Top priority:
 - [x] track inbounds/boundscheck elision through slot2ssa [#26849]
 - [x] splitting union callsites during inlining [#26900]
 - [x] fix stmt_effect_free aggressiveness (typically, broken due to a failure to check for the possibility of control flow divergence – aka the error case) [#26948]
 - [ ] interpreter testing (esp. PhiC nodes)

Other fixes:
 - [ ] remove PiNode from GlobalRef (e.g. `function sizeof_typeref(); g = Core.sizeof; return g; end`)
 - [ ] remove usages of IdDict where Array or BitSet could be used instead
 - [ ] fix compiler performance issues resulting from use of `isa Union{...}` pattern (or eliminate uses) – this is used quite heavily in the new passes, and so contributes quite visibly to performance in profile runs
 - [x] ensure function signatures are marked (ensures stable performance)
 - [x] fix compiler/validation.jl test [#26951]
 - [x] fix crash during precompile test [#26901]
 - [x] fix validation errors during Pkg/resolve tests [#26918]
 - [x] fix crash in cmdlineargs test [#26945]
 - [x] fix incorrect phi node lifting for nested try/catch blocks during read tests [#26943]
 - [x] fix LLVM IR verifier failure [#26958]
 - [ ] fix scope of try/catch blocks during ssa construction
 - [ ] make type inference work on new style IR
 - [x] pass compiler tests for `_apply` elision (#26821)
 - [x] ensure getfield-elimination / alloc-elimination still throws fieldtype errors, not-concrete-datatype , and undef-ref errors, as appropriate (#26948)

### CODE REVIEW

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by Keno** [comment]
When looking at the performance results it's important to note that bounds check elision is currently disabled. That's not too hard, so we should fix that and re-run. Looks like a good franction of these could be explained by that.

**Review by vtjnash — CHANGES_REQUESTED** [review]
not for merging

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-383181912):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/dcdc24014bd4770563f30b74a383b4021a6df5be/294ebac_vs_8f46450/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Weird, I don't see what the issue was; the logs appear to be incomplete.

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by Keno** [comment]
Nanosoldier seems to be sleeping on the job here. Let's try this again. @ararslan could you look into this if it doesn't work:

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by quinnj** [comment]
If one wanted to give the new optimizer a spin, is building this branch enough?

**Comment by Keno** [comment]
Yes, the only difference on this branch is toggling the flag though. All the code is already on master.

**Comment by ararslan** [comment]
Restarted the server. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-386064305) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f0c86f4e5764f54b95660baf77b8e74e2aeb5c75/c592024_vs_76f7d0b/report.md). cc @ararslan

**Comment by Keno** [comment]
Rebased to include #26969 while that is pending

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-386404418) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f3a14bd01501f7b10cb09bfd9bad984bebf075cc/6a6cd09_vs_b9f412b/report.md). cc @ararslan

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

This PR now has everything except the main change in #26969, since @vtjnash doesn't like that one. Let's see where we're at.

**Comment by Keno** [comment]
A bunch of regressions are back from the original report due to not including #26969. Let's re-benchmark with #27068, otherwise we may want to consider merging that one anyway.

**Comment by Keno** [comment]
Ok, I looked into it. The performance regressions due to not including #26969 are because we're lacking pi nodes in the union split branches now. I can reduce #26969 to just pinode insertion. @vtjnash would that be acceptable?

**Comment by Keno** [comment]
This is now master + #27068. Rerunning nanosoldier:

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-388521865) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2d239d8304c5df9a7236b7e9d6912eccb6a514f1/6088ba4_vs_ff99c03/report.md). cc @ararslan

**Comment by vtjnash** [comment]
Performance looks fixed. Do we know what causes the extra allocations on a couple?

**Comment by Keno** [comment]
I looked into the extra allocations and it looks like what happens is that the inlining heuristics push a function over the inlining threshold causing an allocation of the argument (where before it was inlined and getfield elim would eliminate the allocation). Nothing to be done here for now, I don't think.

**Comment by Keno** [comment]
Now that the new optimizer is on its way to being enabled, let's start benchmarking the iteration protocol change on top of it:

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-388588744) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/342ec41795d1071afdc2fbf5bbd941b9ccec8658/1aa6be4_vs_2a21849/report.md). cc @ararslan

**Comment by Keno** [comment]
Well, that is moderately disappointing. Looks like the getfield elim pass is powerful enough to capture the loop pattern at the moment. #26778 would do it, but I think I can simply adjust the lowering to produce a pattern that the less fancy getfield elim pass can handle.

**Comment by Keno** [comment]
This branch now has a rebased version of #26778 with the new iteration protocol. I need to clean things up and PR them separately, but should be good enough for a nanosoldier run.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by Keno** [comment]
I should point out that I didn't yet port mutable struct elision to the new SROA pass, so the thing to look for in those benchmark results is the things that did badly the last time around (e.g. `perf_countnothing`).

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-389024778) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/147b96f9221816e9317421f196ee678a266f60e4/1112d25_vs_fcaa379/report.md). cc @ararslan

**Comment by Keno** [comment]
Hmm, I must have messed something up here. Those regressions are not there locally. Let me take a look.

**Comment by Keno** [comment]
Looks like because of the merge conflicts nanosoldier just dropped the last couple commits from this branch. Let me rebase and try again.

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-389193101) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2142b072ad9dddd9105b7e2f36add0ff9eaeb82e/ac89aeb_vs_1b92f51/report.md). cc @ararslan

**Comment by Keno** [comment]
Ok, that's fairly encouraging. I see three remaining classes of regressions
- `cat` - Will need to look at what's going on here
- `parse(Int, x::String)` - same
- calling `start`/`next`/`done` explicitly - Now trigger deprecation warning, so that's expected. Should be switched to iterate once we merge `kf/iterate`.

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26795#issuecomment-389362695) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/16d3934784857f1eeb8e0883511e14d7efc9b255/c16cd54_vs_11c803c/report.md). cc @ararslan

**Comment by KristofferC** [comment]
So do we know the reason for the rest of the regressions? Will fixing it be a case of wack a mole adding more optimization passes etc or is there a known failure case that fixing would fix everything?

**Comment by mbauman** [comment]
The 200-600x regressions look to be hitting deprecations (explicitly calling start/next/done). I'd say just a couple of big guys left: 5x on `reduce((x,y) -> x + 2y, 0, rand(10^3))`, 5-10x to parse dates, 10x on raytracing and 50x on `pop!(::Set)`.

**Comment by Keno** [comment]
Yes, what @mbauman, the real regressions are those three plus a couple 2x in the array code. I haven't look at them in detail, but I suspect the Date parsing regression is a missing type assertion somewhere. For the array code, there's a pattern where we know two iterators are of the same length which used to be done by skipping the `done` call and using `@inbounds next` to skip the extra branch (which by itself isn't expensive, but messes with the vectorizer). That obviously doesn't work anymore, but I plan to add an `@unsafe_assume` macro, to express those invariants (the two iterators being the same length) directly to LLVM.

**Pull request closed without merging**
