### PR TITLE
make it easier to mark a new module as top

### PR DESCRIPTION
**Pull request by vtjnash**
It's a bit hard to explain exactly what this does, but see the demonstration in the added tests for how this affects the `string` function.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Some cases that currently have `top` nodes probably shouldn't; for example `a[i]` lowers to just `getindex` but `[a,b]` lowers to `(top vect)` and string interpolation lowers to `(top string)`. I think anything that's just alternate syntax for a function call should *not* use `top`. That will handle many cases where one might use this feature.

**Comment by yuyichao** [comment]
What's the advantage of allowing the syntax sugger to be overwritten by a local symbol? Is there a example where this behavior is useful?

I feel like this is probably the most useful for advanced user who will most likely find an alternative way to do it (macro, just call the function directly, etc). OTOH, it'll cause surprise for new users, e.g. defining a local variable `string` and string interpolation suddently breaks.

**Comment by JeffBezanson** [comment]
@vtjnash Suggested using `outer` for these, so that they can only be overridden by globals, and not local variables. That might be the right thing to do.

**Comment by yuyichao** [comment]
`outter` can be confusing too. It can be quite surprising if a package defined a `getindex` method that works when pasting into the REPL and when used by other code in the package but suddently doesn't work anymore when it's used by another package.....

**Comment by JeffBezanson** [comment]
The idea has to be that `a[i]` is widely known as just a rewrite of `getindex(a, i)`. Then it isn't confusing.

**Comment by vtjnash** [comment]
Thinking through this some more over the weekend, I think we should do both. Indeed, starting this PR has already had the intended effect of getting eyes on how much we are (over) using `Expr(:top)`. I think having this list maintained by Base in this way, will serve as a useful way of documenting (to reflection, for example) of what lowering may decide to do. The next logical step then will be to eliminate as much of this list as possible.

**Comment by vtjnash** [comment]
> It can be quite surprising if a package defined a getindex method that works when pasting into the REPL...

Interesting choice of example, since that's actually the only known case (along with `setindex!`) where the lowering of the special syntax will already use the local symbol instead of the top module.

**Comment by JeffBezanson** [comment]
I think it's very important to distinguish between names that correspond directly to syntax (e.g. `string`), and functions that are just incidentally used by lowering. Overriding `string` and `getindex` is fine, but if you use `@topmodule` and then define, say, `>>`, keyword arguments will mysteriously stop working. I don't think we should have a feature that does that. So I think the only thing we should do here is remove `top` nodes for functions in the former "safe" category and document the names very well.

**Comment by yuyichao** [comment]
I agree that the second kind should not happen but I don't see why the first kind should happen. Is there any concrete example of the clear advantage to allow the name to be overwritten?

Put it in another way, these syntaxes are very similar to macros (both are special syntax) and the only difference between the two kind is how complex the transformation is / how long the lowered form is. Allowing name overwrite is basically a non-hygiene macro. I don't see why the macro hygiene should depend on what it expands to / how complex is the expansion.

**Comment by vtjnash** [comment]
> I don't think we should have a feature that does that

We already have the feature. And it is quite important for the implementation of Core.Inference that it works this way (precisely to let you define alternative lowering for keyword args and spatting). The question posed by this PR is only whether it would be useful to have executable documentation in Base of the existing feature (where it can be kept in sync with changes to the lowering code), or whether to maintain it as an independent package.

Documenting this feature (this PR) is independent of whether we also choose to use it substantially less (next planned PR).

**Comment by JeffBezanson** [comment]
> We already have the feature.

I'm really just talking about exposing `jl_set_istopmod` --- we have not previously documented it or encouraged people to call it. Yes, you can also break lowering by overwriting a method of `+` etc., but at least that requires specifically importing the operator (which reminds me, I think we should get rid of `Base.Operators`). Here, if you use `@topmodule` intending to redefine `string` and `vcat` syntax, lowering will also pick up all other functions in your module with matching names.

I will also second @yuyichao 's request for use cases.

**Pull request closed without merging**
