### PR TITLE
Add missing parameter to initialization of LibGit2.RebaseOptions

### PR DESCRIPTION
**Pull request by kmsquire**
Ref #16366.  Not sure if this is the complete fix, but it's needed either way.

Introduced in 0c869e9.  Cc: @nalimilan, @timholy

### CODE REVIEW

**Comment by tkelman** [comment]
Don't merge this kind of thing without adding a test.

**Comment by tkelman** [comment]
This may also be worth adding a keyword for if we're ever going to use it.

**Comment by kmsquire** [comment]
Generally, I agree with needing a test, and won't merge without more discussion in the future.

In this case, though, what would you recommend?  The problem only exists In very recent versions of libgit2, it causes a problem during package updating when there's a local change to the repository, and it was a very obvious missing parameter.

**Comment by tkelman** [comment]
The pkg and libgit2 tests both have quite a few examples of populating local mock repositories and making various changes to them to test the code paths. I believe the recent versions of libgit2 are what is being built and tested on travis, it's only distribution packages that may still use the old version code paths (and would be harder to test)

**Comment by kmsquire** [comment]
Fair enough, I'll take a look.

**Pull request merged**
