### PR TITLE
[release-1.6] Set VERSION to 1.6.4

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
🎉

**Review by KristofferC — APPROVED** [review]

**Comment by ararslan** [comment]
FreeBSD builder "failure" (build status is red but this check doesn't prevent the builder from building and passing along to the tester, which succeeded):
```
ERROR: The working directory is dirty.
Output of git status:
On branch refs/pull/43133/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	deps/checksums/libuv-fb3e3364c33ae48c827f6b103e05c3f0e78b79a9.tar.gz/
nothing added to commit but untracked files present (use "git add" to track)
```
I think this is because we're still setting `USE_BINARYBUILDER_LIBUV=0` on buildbot to work around an issue that's since been fixed and backported (https://github.com/JuliaLang/julia/pull/41900). However, the checksum there that's causing the issue appears to be for a different version of libuv than the one in use. Does anyone know what might be going on there? Perhaps @staticfloat and/or @DilumAluthge?

(Also @DilumAluthge, I think we can remove the `USE_BINARYBUILDER_LIBUV=0` setting on buildbot now.)

**Comment by DilumAluthge** [comment]
> However, the checksum there that's causing the issue appears to be for a different version of libuv than the one in use.

The checksums should be fixed by  #43139

**Comment by DilumAluthge** [comment]
> (Also @DilumAluthge, I think we can remove the `USE_BINARYBUILDER_LIBUV=0` setting on buildbot now.)

I agree that it's almost certainly safe to do so, but just to be extra cautious, maybe we can wait until the 1.7.0 release process has finished before we make that change? Just to avoid breaking the Buildbots in the middle of the release process.

**Comment by DilumAluthge** [comment]
> > (Also @DilumAluthge, I think we can remove the `USE_BINARYBUILDER_LIBUV=0` setting on buildbot now.)
> 
> I agree that it's almost certainly safe to do so, but just to be extra cautious, maybe we can wait until the 1.7.0 release process has finished before we make that change? Just to avoid breaking the Buildbots in the middle of the release process.

https://github.com/JuliaCI/julia-buildbot/pull/255

**Comment by Sacha0** [comment]
🎉 Thanks for all of your efforts folks!

**Pull request merged**
