### PR TITLE
Bump to openblas 0.3.1

### PR DESCRIPTION
**Pull request by ViralBShah**
Maybe will have smaller binaries, faster build time, and faster initilization:

https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.1

### CODE REVIEW

**Comment by ViralBShah** [comment]
Maybe will have smaller binaries, faster build time, and faster initilization:

https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.1

**Comment by ViralBShah** [comment]
@KristofferC Any idea what might cause this:

```
Some tests did not pass: 2 passed, 0 failed, 1 errored, 0 broken.OldPkg/pkg: Error During Test at /tmp/julia/share/julia/test/testdefs.jl:19
  Got exception LoadError("/tmp/julia/share/julia/stdlib/v0.7/OldPkg/test/pkg.jl", 56, KeyError("Unicode")) outside of a @test
  LoadError: KeyError: key "Unicode" not found
  Stacktrace:
   [1] getindex at ./dict.jl:487 [inlined]
   [2] prune_versions(::Dict{String,OldPkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,OldPkg.Types.Available}}, ::Dict{AbstractString,OldPkg.Types.ResolveBacktraceItem}) at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v0.7/OldPkg/src/query.jl:421
```

**Comment by ViralBShah** [comment]
Seems like rebasing on master and re-running things made that go away.

**Comment by KristofferC** [comment]
Likely that someone put a non existing package (Unicode) in their REQUIRE file and merged to Metadata.

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/15437

**Comment by iblis17** [comment]
FreeBSD CI got error after this PR merged into master.
- Master branch: https://freebsdci.julialang.org/#/builders/1/builds/10874
- https://freebsdci.julialang.org/#/builders/1/builds/10881
- https://freebsdci.julialang.org/#/builders/1/builds/10876

**Comment by ViralBShah** [comment]
Hmm. The CI passed on this when I merged it. Which makes me believe it is not related.

**Comment by ViralBShah** [comment]
@KristofferC Is it possible to avoid tests here failing when METADATA has trouble? You have mentioned this in the past too (and I keep forgetting the reason).

**Comment by KristofferC** [comment]
Hm, test here seems to fail in the `ccall` tests?

For METADATA, it should be enough to not allow failures on nightly on METADATA to catch this before they get merged.

**Comment by ViralBShah** [comment]
This PR should not have anything to do with `ccall`.

**Comment by KristofferC** [comment]
Im just reading from the logs Iblis posted.

```
Error in testset ccall:
Error During Test at /home/julia/ci/worker/11rel-amd64/build/test/testdefs.jl:19
  Got exception LoadError("/home/julia/ci/worker/11rel-amd64/build/test/ccall.jl", 994, ErrorException("failed process: Process(`/home/julia/ci/worker/11rel-amd64/build/usr/bin/julia -Cnative -J/home/julia/ci/worker/11rel-amd64/build/usr/lib/julia/sys.so --compile=yes --depwarn=error --startup-file=no -e 'A = Ref{Cint}(42); finalizer(cglobal((:c_exit_finalizer, \"libccalltest\"), Cvoid), A)'`, ProcessSignaled(6)) [0]")) outside of a @test
  LoadError: failed process: Process(`/home/julia/ci/worker/11rel-amd64/build/usr/bin/julia -Cnative -J/home/julia/ci/worker/11rel-amd64/build/usr/lib/julia/sys.so --compile=yes --depwarn=error --startup-file=no -e 'A = Ref{Cint}(42); finalizer(cglobal((:c_exit_finalizer, "libccalltest"), Cvoid), A)'`, ProcessSignaled(6)) [0]
  Stacktrace:
```

**Comment by ViralBShah** [comment]
Yes, I see that too - but not sure if this PR is the issue.

**Comment by iblis17** [comment]
well, I guess the error happened randomly.
Some of the following builds passed.
e.g. https://freebsdci.julialang.org/#/builders/1/builds/10885

**Pull request merged**
