### PR TITLE
threads: move safepoint into loop

### LINKED ISSUE #41407: Julia can hang when using threading, on 1.7 beta2 and 1.8
A.

```
$ time ~/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000 > /dev/null

real	0m3,032s
user	0m8,379s
sys	0m0,883s

then immediately after:

$ time sh -c ~/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000 > /dev/null

^C
^C
^C
Terminated

real	4m25,588s
user	0m0,004s
sys	0m0,000s
```

Note, CTRL-C didn't work to kill, I had to use the kill command (did in another terminal tab). I previously ran into hangs with hyperfine, which I do not believe implicated, it does the latter, but wqith it I could kill with CTRL-C, meaning hyperfine got killed but julia was still running in the background.

I would mark this as a regression. I've done plenty of benchmarking before, often with hyperfine for 1.6, or time (or just `@btime`), and this never happened with hyperfine. I'm however new to using only "sh -c" (which is implied by hyperfine). See at https://github.com/JuliaLang/julia/issues/39598#issuecomment-870655221

This affect 1.7.0-beta2 too (tested later):

```
$ time sh -c ~/julia-1.7-DEV-da96fef327/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000 > /dev/null
Terminated

real	1m31,985s
user	0m0,001s
sys	0m0,003s

and strangely doing "nothing":

Note, I believe I pressed ENTER despite of ERROR on the same line. At least it was quick:

$ ~/julia-1.7-DEV-da96fef327/bin/juliaERROR: TaskFailedException
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:705
  [2] wait
    @ ./task.jl:764 [inlined]
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base ./condition.jl:113
  [4] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:389
  [5] take!
    @ ./channels.jl:383 [inlined]
  [6] repl_backend_loop(backend::REPL.REPLBackend)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:195
  [7] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:185
  [8] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:317
  [9] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:305
 [10] (::Base.var"#914#916"{Bool, Bool, Bool})(REPL::Module)
    @ Base ./client.jl:394
 [11] #invokelatest#2
    @ ./essentials.jl:721 [inlined]
 [12] invokelatest
    @ ./essentials.jl:719 [inlined]
 [13] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:379
 [14] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:309
 [15] _start()
    @ Base ./client.jl:492

    nested task error: IOError: stream is closed or unusable
    Stacktrace:
     [1] check_open(x::Base.TTY)
       @ Base ./stream.jl:386
     [2] raw!(t::REPL.Terminals.TTYTerminal, raw::Bool)
       @ REPL.Terminals /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/Terminals.jl:138
     [3] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
       @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2602
     [4] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
       @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2481
     [5] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
       @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1126
     [6] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
       @ REPL ./task.jl:406
    
    caused by: IOError: read: i/o error (EIO)
    Stacktrace:
     [1] wait_readnb(x::Base.TTY, nb::Int64)
       @ Base ./stream.jl:408
     [2] eof(s::Base.TTY)
       @ Base ./stream.jl:106
     [3] eof(io::REPL.Terminals.TTYTerminal)
       @ Base ./io.jl:416
     [4] match_input(k::Dict{Char, V} where V, s::Union{Nothing, REPL.LineEdit.MIState}, term::Union{REPL.Terminals.AbstractTerminal, IOBuffer}, cs::Vector{Char}, keymap::Dict{Char, V} where V) (repeats 4 times)
       @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:1475
     [5] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
       @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2571
     [6] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
       @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2481
     [7] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
       @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1126
     [8] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()

then nothing for a while until I pressed ENTER (again?!) and got:

   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-DEV.714 (2021-03-16)
 _/ |\__'_|_|_|\__'_|  |  Commit da96fef327 (105 days old master)

```

This is getting strange, running that julia version straight after no problem. It's either only random and/or my machine getting strange. Any idea what could cause it? Everything else seems to work fine. I do not recall if I was using that exact git commit of 1.7 before. 

I was probably using all my three 1.7 downloads frequently before, not sure which most, and running all of them once went ok now:

```
$ ~/julia-1.7-
julia-1.7-a7848a28e5/     julia-1.7-DEV-da96fef327/ julia-1.7-DEV-f2ea26d1a1/ 
```

B.
Since I got "ERROR: TaskFailedException" on the same line, it it plausible it was from previous invocation, i.e. when running with sh? If not then not even sh needs be implicated. I guess that's the mostly likely reason, since I tried later to run that 1.7 version 20 times in a row without any problems.

### PR DESCRIPTION
**Pull request by vtjnash**
@PallHaraldsson, can you see if this fixes #41407 for you? The stacktrace it printed on interrupt suggests this was the problem.

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by PallHaraldsson** [comment]
@vtjnash I can check when this is merged/there's a (nightly) binary. It should be merged (first), right, since Jeff approved?

**Comment by vtjnash** [comment]
Yes, note that you can download a binary from any CI run, master or PR. The download URL will be in the first steps of the testing bots.

**Comment by PallHaraldsson** [comment]
You mean at:
https://build.julialang.org/#/builders/69/builds/777

under "Build steps" tab somewhere? I'm not seeing it, should it be were "uploading 0 files (skipped)" is?

**Comment by PallHaraldsson** [comment]
A.
I can't debug your "move safepoint into loop" code. I just note it's strictly not in the loop while just ahead and I see the "goto retry;" so in some loop.

I don't know enough about this, to see if this small change or other is responsible for the slowdown. If that's the price to pay to get rid of a hang, then I guess better until an even better solution.

B.
I really would like to replicate the hangs I got very repeatedly before, and am frustrated that I can't. There was some hanging julia process with 400% CPU load I killed, and it didn't help. I'm not sure, should the hang be more or less likely with more, or less load? Could this bug have been in Julia for a long time, and e.g. still be there in 1.6? Just the likelihood of triggering it differs?

**Comment by PallHaraldsson** [comment]
>The stacktrace it printed on interrupt suggests this was the problem.

Can that only happen on I/O? I confirmed the hang with no I/O, narrowed down to only "wait" being the problem.

**Comment by PallHaraldsson** [comment]
@vchuravy this may be a fix for #41407 that you closed.

And I actually replicated the hang just now with old commit, also located it here (i.e. first commit there):

```
$ ps -ef |grep julia
pharald+  8402 18133  0 jún29 pts/11  00:00:00 sh -c ~/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000 > /dev/null
pharald+  8403  8402 14 jún29 pts/11  03:45:50 /home/pharaldsson_sym/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000
pharald+  8682 18133  0 jún29 pts/11  00:00:00 sh -c ~/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000 > /dev/null
pharald+  8683  8682 13 jún29 pts/11  03:36:01 /home/pharaldsson_sym/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -t4 -O2 fasta.jl 25000000
pharald+ 22881 18133  0 jún29 pts/11  00:00:00 sh -c ~/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -p2 -O2 bt.jl 21
```

The last line also must be a hang from yesterday, with -p2 rather than -t4 and other program. It's also slowed down:

```
$ hyperfine '~/julia-1.8-DEV-a9412439c3/bin/julia --startup-file=no -p2 -O2 bt.jl 21'
Benchmark #1: ~/julia-1.8-DEV-a9412439c3/bin/julia --startup-file=no -p2 -O2 bt.jl 21
  Time (mean ± σ):     25.268 s ±  1.619 s    [User: 47.272 s, System: 2.329 s]
  Range (min … max):   23.995 s … 29.276 s    10 runs
 
(base) pharaldsson_sym@SYMLINUX011:~/discretionary_dash$ hyperfine '/home/pharaldsson_sym/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -p2 -O2 bt.jl 21'
Benchmark #1: /home/pharaldsson_sym/julia-1.8-DEV-7553ca13cc/bin/julia --startup-file=no -p2 -O2 bt.jl 21
 ⠹ Current estimate: 19.710 s     ███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ETA 00:02:58
^C
```

**Pull request merged**
