### PR TITLE
use LLVM checked intrinsics instead of custom checked code

### PR DESCRIPTION
**Pull request by simonbyrne**
Unfortunately the generated code is still not that nice, e.g. the function

``` julia
function zadd(x,y)
    z = Base.safe_add(x,y)
    isnull(z) ? zero(x) : get(z)
end
```

gives the following assembly:

```
julia> @code_native zadd(1,2)
    .section    __TEXT,__text,regular,pure_instructions
    pushq   %rbp
    movq    %rsp, %rbp
    addq    %rsi, %rdi
    seto    %al
    testb   $1, %al
    jne L19
    movq    %rdi, %rax
    popq    %rbp
    retq
L19:
    xorl    %eax, %eax
    popq    %rbp
    retq
    nopw    (%rax,%rax)
```

Now I'm not really that familiar with assembly, but wouldn't a `jo` instruction would be more appropriate?

As a net result, there doesn't seem to be much change in `safe_add`, but `safe_mul` is about 10 times faster.

### CODE REVIEW

**Comment by eschnett** [comment]
The really interesting question is whether LLVM is able to combine two related overflow checks, eliminating one of them.

I think this is still the way to go forward. With a "missed optimization" report for LLVM, it'll improve in the future. At the same time, the Julia code is simplified.

**Comment by simonbyrne** [comment]
I can't seem to get this to work in Base, though it works fine in a package. Any ideas?

**Comment by eschnett** [comment]
Base is loaded in a particular order. You might be loading it too early, before e.g. string processing is working. Try putting the code into a new file, and load it at the end of `sysimg.jl`.

Of course this won't work if other code in Base requires it earlier.

**Comment by simonbyrne** [comment]
that makes sense, thanks.

**Comment by simonbyrne** [comment]
closed in favour of #17152

**Pull request closed without merging**
