### PR TITLE
Use all normal prereqs in ui/Makefile

### LINKED ISSUE #31876: Icons and exe information are lost on windows installer
For some reason, from a fresh clean build of julia the installers no longer include `.ico` and no  information about the julia binary is attached to the exe.

### PR DESCRIPTION
**Pull request by slarew**
Fixes #31876.

### CODE REVIEW

**Comment by slarew** [comment]
I do not know for sure if this fix works.  I made it based on the [GNU Make manual](https://www.gnu.org/software/make/manual/make.html#Automatic-Variables)

> $^ ... This list does not contain any of the order-only prerequisites; for those see the ‘$|’ variable, below.

**Comment by vtjnash** [comment]
lgtm

**Comment by musm** [comment]
works, thanks

**Comment by vtjnash** [comment]
Included in #31919

**Pull request closed without merging**
