### PR TITLE
release-1.6: Set VERSION to 1.6.7

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@staticfloat Can you turn the necessary buildbots on?

**Comment by DilumAluthge** [comment]
(@KristofferC We haven't yet gotten Buildkite running on 1.6.)

**Comment by KristofferC** [comment]
I know I have to run the mac buildbot manually. But the linux buildbots have to be turned on explicitly as well?

**Comment by KristofferC** [comment]
Nothing has changed here since https://github.com/JuliaLang/julia/pull/45319 which was ok so I will just merge this.

**Pull request merged**
