### PR TITLE
release-1.8: set VERSION to 1.8.3

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
We probably want to first merge https://github.com/JuliaLang/julia/pull/47495, and then rebase this PR.

**Review by ararslan — APPROVED** [review]
🆒

**Comment by DilumAluthge** [comment]
@KristofferC @ararslan You can ignore the pending (yellow) `buildbot/tester_freebsd64` commit status here. We have turned off the `tester_freebsd64` Buildbot. (The `package_freebsd64` Buildbot is still online.) The `buildbot/tester_freebsd64` commit status will no longer show up once we have merged https://github.com/JuliaLang/julia/pull/47562.

**Review by DilumAluthge — APPROVED** [review]
From the CI perspective, LGTM.

**Comment by EwoutH** [comment]
Thanks for this release! How long does it normally take for binaries to be available on https://julialang.org/downloads/ ?

**Comment by KristofferC** [comment]
Up to a few days

**Pull request merged**
