### PR TITLE
Set VERSION to 1.1.0-DEV

### PR DESCRIPTION
**Pull request by ararslan**
This sets master to the development version of 1.1.0, now that `release-1.0` has been branched.

### CODE REVIEW

**Comment by ararslan** [comment]
Can someone fix Example so that the Pkg tests work again? @KristofferC?

**Comment by StefanKarpinski** [comment]
Woah... it's so weird to have a post-1.0 version number.

**Comment by ViralBShah** [comment]
Do we need a release-1.0 branch?

**Comment by KristofferC** [comment]
Registry should be fixed

**Comment by ararslan** [comment]
@ViralBShah We already have it. 🙂

**Comment by simonbyrne** [comment]
I think a good plan is:

1. We're going to keep master as 1.1, at least for the next month or so
   - this means no breaking changes should be merged
   - we need to tag any bugfixes with "backport pending 1.0"
2. We need to develop a process to automate backporting
   - Something like [bors](https://github.com/graydon/bors)?
3. Once we have this working we can switch master to 2.0
   - backport any non-breaking features

**Review by staticfloat — APPROVED** [review]

**Review by simonbyrne — APPROVED** [review]

**Comment by ararslan** [comment]
There's been a lot of discussion offline and the consensus is for the first item on Simon's list above, so I'll merge this. Thanks everyone! We will now be in The Future.

**Pull request merged**
