### PR TITLE
Rebase of #28526 on master: Sparse cholesky solve with sparse RHS

### PR DESCRIPTION
**Pull request by ViralBShah**
Rebase #28526 on top of master.  

cc @pochoi

### CODE REVIEW

**Review by dkarrasch — COMMENTED** [review]
LGTM, though I should add that I'm not familiar with the specific `spsolve` calls. Shall we have another non-trivial test with a small, densely populated sparse SPD matrix, and compare against the classic dense solution?

**Comment by ViralBShah** [comment]
I think we should not need more tests because this only handles the case of the sparse rhs by making it dense and thus reducing the missing case to an existing case.

**Comment by ViralBShah** [comment]
CI failures are unrelated. Merging.

**Comment by pochoi** [comment]
Thank you so much!

**Pull request merged**
