### PR TITLE
FAQ: Is Julia named after someone or something?

### PR DESCRIPTION
**Pull request by stevengj**
Seems to be another FAQ:

* https://discourse.julialang.org/t/why-is-the-name-of-the-language-julia/4382
* https://stackoverflow.com/questions/29290780/what-does-the-name-of-julia-the-programming-language-refer-to
* #5499
* http://www.infoworld.com/d/application-development/new-julia-language-seeks-be-the-c-scientists-190818?page=0,1
* https://www.quora.com/Why-is-Julia-named-Julia

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
❤️ 😂

**Review by miguelraz — COMMENTED** [review]
This is correct but unhelpful for newcomers. Adding 1 or 2 sentences on how they (Jeff?) Just thought it was a nice name for a language could reduce people's confusion about it, and lead to less spam.

**Comment by KristofferC** [comment]
I think this is perfect.

**Review by fredrikekre — APPROVED** [review]

**Comment by cdsousa** [comment]
Looks like an answer Yichao Yu would give. :smile:

**Pull request merged**
