### PR TITLE
Added utility functions expmin and expmax

### PR DESCRIPTION
**Pull request by willow-ahrens**
Julia needs a way to find the minimum and maximum exponents of normalized floating point numbers.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Is the idea that these should be equivalent to `exponent(realmin(T))` and `exponent(realmax(T))`? I'm not really sure we need functions for these, but I could be convinced.

If we do this, I would prefer to change the name. Perhaps `exponentmin`/`exponentmax` would be better, as they relate to the `exponent` function, not `exp`.

Also, the help text for `BigFloat`s is redundant, as it would be covered by the `AbstractFloat`.

**Comment by peterahrens** [comment]
I guess I wasn't clever enough to figure out that I should just do `exponent(realmin(T)).` I suppose that we don't really need these functions in that case. I was just looking for an equivalent function to the constants defined in the typical float.h file in C.

**Comment by simonbyrne** [comment]
> I was just looking for an equivalent function to the constants defined in the typical float.h file in C.

That's a reasonable argument. I'll wait to see what others think.

**Comment by StefanKarpinski** [comment]
Writing `exponent(real{min,max}(T))` seems quite reasonable to me. Especially since the compiler should be smart enough to figure out that this is constant and compute it at compile time. If it isn't then it probably should be.

**Comment by peterahrens** [comment]
sounds good. I'll stick to the existing functions.

**Pull request closed without merging**
