### PR TITLE
added prototype for evalcheck

### PR DESCRIPTION
**Pull request by chakravala**
As discussed on discourse [here](https://discourse.julialang.org/t/parsed-anonymous-functions-type-inference-and-base-invokelatest/6518/10), it may be beneficial to add a function to Julia's base that checks for dangerous system calls when using `eval`.

This pull request offers a prototype for such an idea.

```Julia
"""
    evalcheck(e)

Recursively checks `Expr` objects for dangerous calls
"""
function evalcheck(e)
    if typeof(e) == Expr
        if e.head == :call && e.args[1] == :run
            error("Invalid `eval` with system call")
        elseif condition
            # check for other invalid calls
        else
            for i ∈ 1:length(e.args)
                evalcheck(e.args[i])
            end
        end
    end
    return e
end
```
Then if you want to use `eval` but want to check that the supplied expression does not do anything unexpected you can do
```Julia
julia> "y = run(`hey`)" |> parse |> evalcheck |> eval
ERROR: Invalid `eval` with system call
...
```
Is this something worth adding to base? If there are other types of calls you want to error out on, those only need to be added to the conditional in `evalcheck`.

This is the first time I'm contributing to base, and this is just a concept idea at the moment. So please let me know how this idea can be improved upon and what you think of it.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why should you not be allowed to call `run` from `eval`?

**Comment by yuyichao** [comment]
There's nothing intrinsically wrong with these few functions names. If you have specific requirement for what the expression you want to evaluate must be, you should have your own version and possibly in a shared package.

**Comment by chakravala** [comment]
@fredrikekre it doesn't stop you from using `eval`, it only gives you the option to check for undesired commands that might unintentially affect your operating system before running `eval`.

**Comment by StefanKarpinski** [comment]
Having such a function in the standard library suggests that it would actually work and be safe, which could not be farther from the truth. This kind of check cannot, _in principle_, protect you from anything but the most superficial attempts to run dangerous code.

**Comment by chakravala** [comment]
Yes, that's true. I suppose what it could do is prevent you from making a stupid mistake, but it wouldn't necessarily prevent a malicious code from executing.

**Pull request closed without merging**
