### PR TITLE
Include @​propagate_inbounds docstring in documentation

### PR DESCRIPTION
**Pull request by tkf**
Just an addition of one line.

### CODE REVIEW

**Comment by fredrikekre** [comment]
AFAICT we don't usually include unexported things in the manual.

**Comment by tkf** [comment]
`@pure` is mentioned but included in the documentation: https://docs.julialang.org/en/v1.2-dev/base/base/#Base.@pure.  Other examples: `require`, `summarysize`

Even if it is not exported, I suppose `@​propagate_inbounds` is considered a public API, right?  It is impossible (extremely tedious) to write a proper bound checking without it.  If it is considered public, I suggest to include in the documentation as otherwise there is no way ATM to mark something is a public API.

> include it in the devdocs for boundschecking instead?

It's already mentioned in devdocs: https://docs.julialang.org/en/v1.2-dev/devdocs/boundscheck/#Propagating-inbounds-1

But I think it's better to have it in the manual to make it easier to be discovered.

**Comment by fredrikekre** [comment]
> Even if it is not exported, I suppose `@​propagate_inbounds` is considered a public API, right?

Not sure, wouldn't it have been exported in that case?

> It's already mentioned in devdocs: https://docs.julialang.org/en/v1.2-dev/devdocs/boundscheck/#Propagating-inbounds-1

Yea, but I was suggesting adding the docstring to that page instead. At least make it a reference.

**Comment by tkf** [comment]
> wouldn't it have been exported in that case?

I already mentioned the counter examples (`@pure`, `require` and `summarysize`).  I think more important examples are `IteratorSize` and `IteratorEltype`.  They are not exported but their docstring are included in the manual https://docs.julialang.org/en/v1.2-dev/base/collections/#Base.IteratorSize and also this blog post https://julialang.org/blog/2018/07/iterators-in-julia-0.7 mentioned them.  I would be very surprised if `IteratorSize` and `IteratorEltype` are considered non-public.

**Comment by fredrikekre** [comment]
Ok, but
> At least make it a reference.

**Comment by tkf** [comment]
I added the link.

**Comment by mbauman** [comment]
Yeah, I say it's worth documenting this even if we don't export it.

Heck, I'd even be okay exporting it, but it is a bit of an expert feature.

**Comment by Keno** [comment]
Triage: Fine change, but no backport.

**Comment by mbauman** [comment]
Especially since we already reference this in other documentation!

**Pull request merged**
