### PR TITLE
fix seqfault in cgutils for ccall with UA

### PR DESCRIPTION
**Pull request by vchuravy**
Encountered while trying to do some shenanigans with VecElement.

x-ref: https://github.com/JuliaLang/julia/commit/6dc5f50d22e1fc1e7a5e4d5e2c885d7ad5d9697c#commitcomment-20908405

### CODE REVIEW

**Review by vtjnash — CHANGES_REQUESTED** [review]
wrong change <20 character limit>

**Comment by vchuravy** [comment]
@vtjnash I will leave this up to you then ;)

**Comment by vtjnash** [comment]
er, I just meant that the review was at the x-ref link above: https://github.com/JuliaLang/julia/commit/6dc5f50d22e1fc1e7a5e4d5e2c885d7ad5d9697c#commitcomment-20914896

**Comment by vchuravy** [comment]
If I find time today I will see if I can find a testcase and then implement
your suggestion.

**Pull request closed without merging**
