### PR TITLE
Upgrade to LLVM 3.7.1 and switch over CI

### LINKED ISSUE #9336: activate LLVM37
this is an umbrella issue for tracking known issues with switching to LLVM35 as default. please edit this post or add a comment below. close when someone edits `deps/Versions.make` to ~~`3.6.0`~~ `3.7.0`

current known issues:
 - [ ] requires editing deps/Versions.make - #14623
 - [x] #7910 ([upstream patch](http://reviews.llvm.org/D6961) committed to 3.7 -- only an issue on Mac)
 - [ ] figure out performance regression (perhaps only run passes once ~~(requires writing a `TargetMachine` wrapper and overloading `addPassesToEmitMC`)~~ (requires changes to LLVM to expose passes))
 - [x] requires leaving behind LLVM33
 - [x] would eliminate content from the "fixed in LLVM 3.5" issue label
 - [x] #8137
 - [x] #8999
 - [x] #9280
 - [x] #9339 ~~(LLVM36-only issue)~~
 - [x] #9967 (fixed in LLVM36)
 - [x] #10377
 - [x] #10394
 - [x] #11085 linalg/arnoldi test on win64
 - [x] #11083
 - [x] ~~#10806~~ (afaict, this is a non-fatal issue in valgrind. jwn)
 - [x] #11003 
 - [x] ~~#13106~~ (this issue is a non-fatal performance regression. jwn)
 - [x] re-disable FPO

related:
- [x] #7779 coverage flags are broken with LLVM 3.5 on master 

@Keno

### LINKED ISSUE #11083: Win32 std::bad_alloc during make testall1
ref https://github.com/JuliaLang/julia/issues/10394#issue-59712802

When run one at a time via something like `include("test/choosetests.jl"); testlist, net_on = choosetests(); for i in testlist; try Base.runtests(i, 1); catch; end; end`, all tests pass in this configuration at b8aa30d. However running standard `make testall1` results in (also note the really awful performance)

```
    JULIA test/all
     * linalg1              in 114.59 seconds
     * linalg2              in  95.28 seconds
     * linalg3              in  40.11 seconds
     * linalg4              in  14.75 seconds
     * linalg/lapack        in   6.95 seconds
     * linalg/triangular    in 1028.06 seconds
     * linalg/tridiag       in  31.62 seconds
     * linalg/bidiag        in  49.95 seconds
     * linalg/diagonal      in  36.07 seconds
     * linalg/pinv          in  29.31 seconds
     * linalg/givens        in  18.50 seconds
     * linalg/cholesky      in  78.32 seconds
     * linalg/lu            in  51.09 seconds
     * linalg/symmetric     in  52.06 seconds
     * linalg/arnoldi       in  78.38 seconds
     * core                 in 283.12 seconds
     * keywordargs          in  36.12 seconds
     * numbers              in 1103.33 seconds
     * strings              in 471.06 seconds
     * dates                in 1203.63 seconds
     * dict                 in 176.02 seconds
     * hashing
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 3
Makefile:492: recipe for target 'testall1' failed
make: *** [testall1] Error 2
```

If I do `make test` with 3 simultaneous workers, I get the same exception at a different place.

```
    JULIA test/all
        From worker 4:       * linalg3              in  77.08 seconds
        From worker 4:       * linalg4              in  18.90 seconds
        From worker 4:       * linalg/lapack        in  12.60 seconds
        From worker 3:       * linalg2              in 150.06 seconds
        From worker 3:       * linalg/tridiag       in  18.33 seconds
        From worker 2:       * linalg1              in 205.75 seconds
        From worker 3:       * linalg/bidiag        in  56.38 seconds
        From worker 2:       * linalg/diagonal      in  34.59 seconds
        From worker 3:       * linalg/pinv          in  33.00 seconds
        From worker 2:       * linalg/givens        in  17.79 seconds
        From worker 2:       * linalg/lu            in  46.05 seconds
        From worker 2:       * linalg/symmetric     in  34.39 seconds
        From worker 3:       * linalg/cholesky      in 123.67 seconds
        From worker 2:       * linalg/arnoldi       in  62.23 seconds
        From worker 2:       * keywordargs          in  22.07 seconds
        From worker 3:       * core                 in 179.23 seconds
        From worker 3:       * strings              in 314.78 seconds
        From worker 2:       * numbers              in 766.31 seconds
        From worker 2:       * dict                 in 130.68 seconds
        From worker 4:       * linalg/triangular    in 1496.39 seconds
        From worker 4:       * remote               in   4.32 seconds
        From worker 2:       * hashing              in 312.99 seconds
        From worker 4:       * iobuffer             in  28.52 seconds
        From worker 2:       * staged               in  21.23 seconds
        From worker 2:       * tuple                in  39.91 seconds
        From worker 3:       * dates                in 904.55 seconds
        From worker 3:       * reduce               in 111.45 seconds
        From worker 3:       * reducedim            in 251.95 seconds
        From worker 4:       * arrayops             in 714.60 seconds
        From worker 4:       * intfuncs             in  56.20 seconds
        From worker 4:       * simdloop             in  48.57 seconds
        From worker 3:       * random               in 377.39 seconds
        From worker 4:       * blas                 in  93.34 seconds
        From worker 3:       * sparse               in 769.23 seconds
        From worker 3:       * copy                 in  41.79 seconds

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
        From worker 3:       * math                Worker 3 terminated.
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
 in yieldto at .\task.jl:19
 in wait at <invalid> (repeats 2 times)
 in wait_full at <invalid>
 in remotecall_fetch at .\multi.jl:670
 in remotecall_fetch at .\multi.jl:675
 in anonymous at .\task.jl:1390
        From worker 4:       * bitarray             in 822.41 seconds
        From worker 2:       * subarray             in 2596.30 seconds
ERROR: LoadError: ProcessExitedException()
 in yieldto at .\task.jl:19
 in wait at <invalid> (repeats 2 times)
 in wait_full at <invalid>
 in remotecall_fetch at .\multi.jl:670
 in remotecall_fetch at .\multi.jl:675
 in anonymous at .\task.jl:1390
while loading D:\cygwin64\home\Tony\julia32\test\runtests.jl, in expression starting on line 3

WARNING: Forcibly interrupting busy workers
Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:485: recipe for target 'test' failed
make: *** [test] Error 2
```

### PR DESCRIPTION
**Pull request by tkelman**
Thanks to @Keno for doing most of the preparation work, and @staticfloat for handling mac packaging. ~~There's one ugly git line in the `.travis.yml` that can go away once https://github.com/staticfloat/homebrew-julia/commit/9642485ab2a86176808ff9b19ebcf1ed7803b151 and https://github.com/staticfloat/homebrew-julia/commit/e6b8d2d324f5c53d45926d03f26490f44ffcd133 are merged into master of homebrew-julia.~~ gone

This probably calls for a PkgEval run before merging. Closes #9336.

Fixes: (not yet) ~~#10595~~, #12671, #10444, #9222, #9085, #4905, #4418, #3596, #10301, #11037,  #11083
^^ these should all be checked manually, and add tests before closing wherever possible

todo:
- [x] fix #11083, rebuild windows llvm binaries to include fix
- [x] USE_ORCJIT on osx travis (needs https://github.com/staticfloat/homebrew-julia/pull/199 to be merged, then restart osx travis jobs)
- [x] run PkgEval

### CODE REVIEW

**Comment by tkelman** [comment]
Both win32 and win64 are failing on appveyor with `LLVM ERROR: Unable to allocate section memory!`, so #11083 is indeed still open and a blocker here.

**Comment by staticfloat** [comment]
Now merged into `homebrew-julia`'s `master` branch.

**Comment by IainNZ** [comment]
Wow, huge!

How carefully have the perf implications been looked into for this? I recall a lot of work on bringing codegen times down to a relatively small regression, but how about the generated code on nontrivial code?

**Comment by ViralBShah** [comment]
The plan is to get this in for now, and then tackle the rest going forward on master as undoubtedly we will find more issues.

**Comment by ViralBShah** [comment]
Perhaps this is also where the benchmarking infrastructure will come in handy.

**Comment by jrevels** [comment]
No time like the present?

`runbenchmarks(ALL, vs = "JuliaLang/julia:master")`

The CI tracker currently only has a subset of the array benchmarks in Base, so some manual perf testing would also be helpful.

**Comment by KristofferC** [comment]
FWIW I see the same performance in my packages and some of them ([NearestNeighbors.jl](https://github.com/KristofferC/NearestNeighbors.jl)) have previously been quite good at detecting performance regressions, at least in the array code. Just one sample, but hey.

**Comment by tkelman** [comment]
@staticfloat we're going to need a newer gtar on the linux buildbots, apparently they don't understand `.xz` https://build.julialang.org/builders/package_tarball64/builds/24/steps/make%20binary-dist/logs/stdio

**Comment by jrevels** [comment]
https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/54afb4e/54afb4e_vs_16301d2.md

Looks like some of the raw time regressions could be attributable to GC, but some might go away if johnmyleswhite/Benchmarks.jl#40 was in play. `eig(rand(4, 4))` seems to be the only benchmark that demonstrates memory allocation regressions.

**Comment by Keno** [comment]
Ok, fine, I'll write us a better memory manager.

**Comment by Keno** [comment]
Also, do people know what other JITs do to avoid RWX pages? I looked at v8 and openjdk, but both seems to have RWX pages.

**Comment by ihnorton** [comment]
LuaJIT does RW first and then switches to RX.
https://github.com/LuaJIT/LuaJIT/blob/2e85af8836931f10aaaaae8c10f9b394219187a5/src/lj_mcode.c#L169-L203

(related: http://lists.llvm.org/pipermail/llvm-dev/2012-July/051843.html)

**Comment by Keno** [comment]
Right, that's what LLVM 3.7 does too, but we run into some fragmentation problems which artificially bloats our memory usage.

**Comment by Keno** [comment]
What we could do is go RW->RX and put it pack into RW when we want to append. There is a problem with multi-threaded code, but I'm sure we could solve that just by holding the thread until we're done writing to the page. I'm not sure that's significantly better than just having a RWX page though. An attacker just have to time the writing to the page correctly. Also, I'm not necessarily arguing  that it should be our job to protect against this, just exploring if there's a reasonable default.

**Comment by yuyichao** [comment]
> There is a problem with multi-threaded code, but I'm sure we could solve that just by holding the thread until we're done writing to the page.

We already relies on segfault for multithreading GC, we could easily add the logic for catching not executable fault as long as LLVM (or codegen) is able to tell whether an address is being written to by LLVM.

> An attacker just have to time the writing to the page correctly.

I always thought the whole point is to make the attack window smaller? The attacker can always write to the same page when we are doing codegen, unless there's some verification pass after we set the page to not-writable, in which case we can also do that when we set the page back.

**Comment by tkelman** [comment]
dunno. I should remember https://github.com/JuliaLang/julia/pull/14430#issuecomment-168413414 and add in `-DUSE_ORCJIT` somewhere for osx travis since we know the homebrew bottle is patched

**Comment by Keno** [comment]
@yuyichao That was my thought as well (i.e. holding the thread on an NX fault). The fact that the attack window is already there is a fair point. The only thing that is worse here is that a potential attacker might more easily be able to determine the allocation address. In any case, I think I actually found a bug in my patch which caused us to waste some memory. Let's see if just fixing that is sufficient. We should still think about a better memory allocator in the future though.

**Comment by Keno** [comment]
We could checksum the portion of the page that already exists and crash if it was modified.

**Comment by yuyichao** [comment]
If detecting the address is an issue, we can hide that by making two maps of the physical pages that we might still emit code into and never set the RX one back. Not sure if this is possible to do on windows or if it is supported by the llvm api though.

**Comment by Keno** [comment]
Also, my patch does indeed seem to fix the windows issue. Nice! Will commit upstream and add it to the patch set.

**Comment by Keno** [comment]
> If detecting the address is an issue, we can hide that by making two maps of the physical pages that we might still emit code into and never set the RX one back. Not sure if this is possible to do on windows or if it is supported by the llvm api though.

Yeah, Windows allows it. LLVM's memory APIs may not currently support it, but that's what a custom memory manager is for.

**Comment by yuyichao** [comment]
> We could checksum the portion of the page that already exists and crash if it was modified.

A very minor issue is what if the attacher can modify the checksum on the stack.... probably not important compare to the one it solve.....

**Comment by tkelman** [comment]
Is the bug Windows only or will it also be worth rebuilding a new revision of the homebrew bottle with the modified patch?

**Comment by Keno** [comment]
This bug is windows-only, but there was also a MachO patch that was forgotten (but that one is only a problem in LLVM_ASSERTIONS mode which the bottles may not be in?)

**Comment by tkelman** [comment]
not sure whether bottles have assertions on, but I think that would be good to do on CI?

**Comment by Keno** [comment]
Yeah, probably.

**Comment by Keno** [comment]
If the attacker can write the stack you have generally lost because they can overwrite the return address.

**Comment by Keno** [comment]
Patch committed upstream as https://github.com/llvm-mirror/llvm/commit/1f644cd56aa74ab04b02d7415e940a7be9e6f39e.

**Comment by ihnorton** [comment]
> there was also a MachO patch that was forgotten

@tkelman: https://github.com/JuliaLang/julia/issues/14585#issuecomment-169712071

> If the attacker can write the stack you have generally lost because they can overwrite the return address.

Right now can't anybody just `ccall(:mprotect, ...` themselves?

(also, can we please, please add the [llvm-shlib patch](https://github.com/ihnorton/llvm/commit/a94a96cbd20b672ed319506a7a01724de5e5a02d) to our patchset so we can support `USE_LLVM_SHLIB` on Windows?)

**Comment by Keno** [comment]
Ok, I'll prepare a second patchset with:
- ARM bugfix
- MachO patch
- New Windows Patch
- LLVM SHLIB patch

**Comment by tkelman** [comment]
@Keno I also had an upstream fix for sone nuisance `_MSC_VER` warnings that we may as well throw in

**Comment by Keno** [comment]
@tkelman Sure, point me to the commit sha please?

**Comment by Keno** [comment]
> Right now can't anybody just ccall(:mprotect, ... themselves?

Yes. We aren't protecting against somebody who can call `eval`. The concern is more, what if somebody uses julia as a webserver, and somehow manages to let an attacker overwrite memory (e.g. they used `@inbounds` on the buffer, but didn't do range checking properly). There need to be many layers of defenses, and it's useful to pick more secure defaults if possible.

**Comment by tkelman** [comment]
d14598 on phabricator, trying to find gitsha

**Comment by Keno** [comment]
It's SVN r253614. Should be easy to find.

**Comment by Keno** [comment]
Even easier than I thought ;):
```
$ git svn find-rev r253614
ab9499328c0131c75131825c527557c4b1c922cb
```

**Comment by IainNZ** [comment]
Well, here is my benchmark FWIW

Code: https://gist.github.com/IainNZ/3fb295d26f48857e0aac
(its a JuMP model for an optimal control problem. Need JuMP.jl and Ipopt.jl)

Performance numbers:

```
JuMP 0.11
  Julia 0.4.1
    5.173100 seconds (8.65 M allocations: 387.304 MB, 1.78% gc time)
    1.112170 seconds (2.30 M allocations: 103.153 MB, 3.06% gc time)
    1.112430 seconds (2.30 M allocations: 103.343 MB, 2.77% gc time)
  Julia 0.5-dev+2072 (17287f0)
    5.294610 seconds (8.65 M allocations: 387.346 MB, 1.70% gc time)
    1.164331 seconds (2.30 M allocations: 103.153 MB, 3.15% gc time)
    1.104843 seconds (2.30 M allocations: 103.343 MB, 2.81% gc time)
  Julia 0.5-llvm37 branch
    7.562005 seconds (8.92 M allocations: 398.443 MB, 1.37% gc time)
    1.468272 seconds (2.30 M allocations: 104.098 MB, 2.71% gc time)
    1.561090 seconds (2.30 M allocations: 103.989 MB, 6.74% gc time)
```

**Comment by Keno** [comment]
Does the code still do some amount of compilation in the second two runs or is that actually degraded runtime performance of the generated code?

**Comment by Keno** [comment]
Can we collect all these benchmarks? It would be amazing to have them all available when I do LLVM performance work do get some numbers (cc @jrevels).

**Comment by KristofferC** [comment]
We could have a repo similar to `BaseBenchmarks.jl` but instead users can contribute their benchmarks for their packages? Although, maybe it will be a lot of maintenance to keep the benchmarks in sync with the packages and packages getting abandoned etc.

`BaseBenchmarks.jl` will then be more micro benchmarks while the one in the new repo will test larger pieces of code.

**Comment by Keno** [comment]
I think I would rather see packages add a benchmarks/ directory and have the benchmark infrastructure be able to pull those all in.

**Comment by KristofferC** [comment]
Yeah, depends on how much control you want over the benchmarks. If we go that route it feels that it should be included in Base somehow á la `Pkg.benchmark()`.

**Comment by Keno** [comment]
Second round of patches added as bcfc9673357df5d4dbeef84bc51099ff743e3757. @tkelman, @staticfloat, can you take it from here?

**Comment by jrevels** [comment]
> Can we collect all these benchmarks?

I'll add the benchmark tag to this thread to remind myself to sweep through here later to see if any benchmarks crop up that can be added to BaseBenchmarks.jl. 

On the other benchmark-related points, I've responded [here](https://github.com/JuliaLang/julia/issues/13893#issuecomment-170387156).

**Comment by simonster** [comment]
Here's a [blog post](http://jandemooij.nl/blog/2015/12/29/wx-jit-code-enabled-in-firefox/) on W^X in Firefox, which evidently just landed. It seems like they rejected the two mapping approach for security reasons, but they have more reason to be worried about security than we do at this point.

**Comment by yuyichao** [comment]
IIUC, the temporary RX->RW window (also the initial codegen window) is only an issue for multi-threading. I'm wondering if that's an issue for firefox. I think two map should be the same with flipping the page to RW for this attach window as long as the second map is `mprotect` to `PROT_NONE` outside codegen. The advantage of the two map approach then is that we don't need to handle NX segfault or pulse threads.

**Comment by tkelman** [comment]
Could yoy guys discuss memory protection in a separate issue? Kind of distracting how many conversations are now happening in this PR.

**Comment by Keno** [comment]
Yes, we should. Will open a new issue.

**Comment by staticfloat** [comment]
@tkelman I have built and installed a newer version of `tar` that is also symlinked to `gtar`.  Let's see if it works.

**Comment by Keno** [comment]
Is this latest AppVeyor run with the new patch?

**Comment by tkelman** [comment]
Yes, the r02 binaries include the second patch set.

**Comment by Keno** [comment]
I don't understand the AppVeyor failure then.

**Comment by Keno** [comment]
I cannot reproduce the failure locally with the patch applied. The memory usage doesn't even get near the 4GB mark. Something must have gone wrong.

**Comment by tkelman** [comment]
I can, with `make testall1`. Any specific debugging that I could help with? Note that my win32 `Make.user` contains (cygwin-cross build):
```
XC_HOST = i686-w64-mingw32
override LLVM_ASSERTIONS = 1
override MARCH = pentium4
override JULIA_CPU_TARGET = pentium4
```
The last 2 are for consistency with how the buildbots build lowest-common-denominator portable binaries. For good measure I just ran `make cleanall && make -C deps distclean-llvm && make -j8 testall1` and it happened again at c427db7b7.

**Comment by Keno** [comment]
At which point does it fail. Can you open resource manager and see if Commit Size grows significantly larger than the working set. Just to be sure is c427db7 rebased on master such that it includes the patch set?

**Comment by tkelman** [comment]
> At which point does it fail?

during subarray

> Can you open resource manager and see if Commit Size grows significantly larger than the working set

Commit is 2-3x larger than working set just going on linalg/triangular. Will post a screenshot if I can catch it in subarray before the failure.

> Just to be sure is c427db7 rebased on master such that it includes the patch set?

Yes, see: [c427db7b~6](https://github.com/JuliaLang/julia/commit/c427db7b7ad1fac3bfd205adf3afaa266b693092~6)

**Comment by Keno** [comment]
> Commit is 2-3x larger than working set just going on linalg/triangular. Will post a screenshot if I can catch it in subarray before the failure.

Ok, that's the symptom of the bug I'm fixing, so something is going wrong here. With the patch applied, commit is ~200MB larger than WS at all times.

**Comment by Keno** [comment]
Can you look in the source tree and make sure the patch is getting applied properly. In particular the line that's deleted in the new patch should be gone.

**Comment by tkelman** [comment]
Ah, the `RODataMem.FreeMem.clear()` line was not deleted correctly. Something is up with patch application in cygwin-cross apparently? Will take a closer look.

**Comment by tkelman** [comment]
Figured it out. It's a race condition between the two patches with parallel make, since they touch the same files.

**Comment by Keno** [comment]
What's the status here? Looks like the OS X build failed? Is there a problem with the homebrew bottles?

**Comment by tkelman** [comment]
It's timing out. Still too slow.

**Comment by Keno** [comment]
I'm not sure why OS X would take any longer than windows. Are we sure the ORCJIT definition is working properly?

**Comment by Keno** [comment]
The subarray test is taking almost twice as long as it does on linux.

**Comment by tkelman** [comment]
> Are we sure the ORCJIT definition is working properly?

Maybe not. What's the best way to check?

#14656 might help here?

**Comment by Keno** [comment]
Probably `nm libjulia.dylib | grep JuliaOJIT`.

**Comment by tkelman** [comment]
https://travis-ci.org/JuliaLang/julia/builds/101974382, go nuts on the `llvm37-travistest` branch if you have any other ideas

**Comment by staticfloat** [comment]
Could it be due to LLVM assertions being enabled on OSX?

**Comment by Keno** [comment]
Yes, though 2x julia execution time overhead is surprising even for that.

**Comment by Keno** [comment]
Also are they enabled, did you rebuild the bottles with those enabled?

**Comment by tkelman** [comment]
We looked into what LLVM's `./configure --help` says is the default for assertions and left it that way, apparently it's enabled.

**Comment by Keno** [comment]
I think assertions are only enabled by default in debug builds.

**Comment by tkelman** [comment]
The flags we apply in `deps/Makefile` are a little different than what would get used in a straight `./configure` as in homebrew

**Comment by Keno** [comment]
Hmm, ok. Worth trying without assertions perhaps.

**Comment by tkelman** [comment]
The mac builders are going to be a little busy for the next hour or two working on 0.4.3, but depending which OS X version the Travis VM's are running we might get away with only rebuilding one or two of the bottles.

A rather annoying fact is that the Travis OS X workers are using Xeon X5570 which is apparently a 2009-era processor.

**Comment by tkelman** [comment]
We'll see whether this makes a difference but apparently I was overwriting the default `-pipe -fPIC -fno-rtti` contents of `JCXXFLAGS`. If there's a better way to append `-DUSE_ORCJIT` in a way that codegen will see it let me know.

**Comment by yuyichao** [comment]
Can we add sth like

```
#ifndef USE_ORCJIT
#  define USE_ORCJIT
#endif
```

to `llvm-config.h` in our patched version of LLVM 3.7.* ?

**Comment by tkelman** [comment]
D'oh, I should have saved the logs to measure more carefully how much difference disabling exceptions made. I think it wasn't much. Jeff's compiler change was noticeable but not quite enough.

So. Disable osx travis? Split it up into multiple jobs for different groups of tests? Tweak codegen or patch llvm some more?

I'll also run pkgeval on linux.

**Comment by Keno** [comment]
All of the above, but once pkgeval is through, we should disable and merge immediately. Then we can worry about getting performance better and/or working around the problem.

**Comment by vtjnash** [comment]
from the latest x86-64 linux travis builds, it looks like CPU or IO bound tests are only slightly slower (~10%-ish), but that compile-bound tests are up to ~15x slower (what is that `int` test doing?!). the average travis slowdown seems to be about 60% for total compile & test timing?

**Comment by tkelman** [comment]
Nightlies built off this branch break because they're missing libedit.so.0. Does LLVM build its own copy of that? We need some makefile modifications to deal with that.

**Comment by tkelman** [comment]
@Keno would it hurt anything if we unconditionally configured llvm with `--disable-libedit` and/or `--disable-terminfo` ? Is there anything you badly need for Cxx or Gallium that wouldn't be possible with those disabled?

**Comment by tkelman** [comment]
PkgEval results: https://gist.github.com/227c163de0dab721bf72

Quite a bit more breakage than I'd expect for a change that should in theory not be visible to user code.

**Comment by IainNZ** [comment]
I'm seeing segfaults in many at `jl_recache_types`

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/pull/14301#issuecomment-171055039 ?

**Comment by tkelman** [comment]
Yeah, cherry-picking fe8967009b144e32ba179167fcaa2616bfd74819 (and resolving the small conflict there) seems to at least fix DataFrames locally on this branch. That should probably be split out and applied to master on its own now so we can rebase both of these.

**Comment by tkelman** [comment]
Fewer failures this time around, but still more than you might hope: https://gist.github.com/cf1da5230c275eedaa67

**Comment by tkelman** [comment]
MbedTLS and dependents look like they were broken by #14667, so these aren't all regressions relative to latest master. The nightly binary is old because the centos and osx buildbots have been constantly failing for 2 weeks.

There are some strange-looking bounds errors and segfaults in here that may be legit regressions though.

**Comment by tkelman** [comment]
Enough other things have changed on master in the last few weeks that it's probably best to just merge this and work on fixing things, bringing back osx testing, etc as we go.

**Comment by Keno** [comment]
+1 Let's get this merged and address failures as they come in

**Comment by JeffBezanson** [comment]
:fireworks: Congrats, big milestone here!

**Comment by JeffBezanson** [comment]
Am I reading correctly that this makes total travis CI time 2 hours longer? And to think I was holding off on merging jb/functions since it makes CI time 20 minutes longer...

**Comment by Keno** [comment]
No, something is going wrong with Travis.

**Comment by JeffBezanson** [comment]
Ok, I suspected it must be something like that. A single AV build is ~20 minutes longer; is that expected?

**Comment by Keno** [comment]
Looks like it's recompiling OpenBLAS for some reason. @tkelman take a look? 20 minutes is possible though moderately more than expected.

**Comment by tkelman** [comment]
It's how the docker caching works on travis now. We aren't using the ppa any more, we do a source build from scratch but cache the built deps. It only takes so long after clearing out the cache. When the cache is populated it's about half an hour.

AppVeyor is slower as a real perf regression. OSX was so much slower it timed out constantly and we had to turn it off for the time being.

**Comment by vtjnash** [comment]
@JeffBezanson yes, i noted that prior to merging. total CI build time regression appeared to be about 2x

**Comment by vtjnash** [comment]
@Keno can you look into the `int.jl` test? it seems to be showing a 15x increase in runtime on CI runs

**Comment by Keno** [comment]
Will take a look.

**Comment by jiahao** [comment]
:tada:

**Comment by blakejohnson** [comment]
>There are some strange-looking bounds errors and segfaults in here that may be legit regressions though. (or more likely due to #14474)

@tkelman if you find particular examples where you suspect, #14474, please let me know.

**Comment by tkelman** [comment]
If you could take a look at Brim, Gadfly, Mamba, OpenStreetMap, and/or Winston that'd be awesome. They're all hitting BoundsErrors.

JuMP, NamedTuples, and Persist are failing for reasons that don't make sense to me yet, but they don't look BoundsError related.

**Comment by blakejohnson** [comment]
So, trying `Pkg.test("Gadfly")`, the first error I encounter is a BoundsError in Showoff.jl of the flavor:
```julia
a, b, c, d = (1,2,3)
```
and caused by 53ecbaa1392485764fd5fb42900175d29909223d changing the number of arguments returned by `Base.grisu` from 4 to 3. If I fix that, then all Gadfly tests pass. This is probably something to add to Compat.jl

@dcjones

**Comment by tkelman** [comment]
Ah good call, sorry about the false alarm. Does anyone else have commit access to Showoff.jl? If not we may need to redirect metadata to use a mirror/fork for a while if it becomes urgent.

**Comment by blakejohnson** [comment]
Ah, I guess I am on 0201437, which doesn't include this PR. But, at that point `Brim` also passes all tests. I would say, generally, that if you see a BoundsError, it is actually quite unlikely to be #14474. The more likely signature would be a segfault, because we elided a bounds check that we shouldn't have.

**Comment by blakejohnson** [comment]
There is definitely something pretty weird going on with Brim related to bounds checks. The test which fails is:
```julia
using Brim
A = [1 0; 0 1]
M = partition_lp(A)
```
When launched from a julia session with `--check-bounds=yes` it gives a bizarre BoundsError:
```
ERROR: BoundsError: attempt to access 4x4 Array{Int64,2}:
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  1
  at index [3,1]
```
Without that command line option it works with a deprecation warning.

**Comment by nalimilan** [comment]
FWIW, I've just switched the Copr RPM nightlies to LLVM 3.7.1, and all the tests pass. The build is only slightly slower than before (~26 minutes vs. 18 minutes in the best cases). This should increase the testing of this code since there are about 500 downloads each week.

**Pull request merged**
