### PR TITLE
Add an option to build without libuv

### PR DESCRIPTION
**Pull request by Keno**
There is increasing interest in running Julia in environments where
libuv is not available (JSVM, baremetal library OSes, etc). This adds
a make file option to disable building libuv entirely and fixes up
the bootstrap process to go through despite libuv not being available.
There is of course a question of whether instead of this it makes sense
to just port libuv to those platforms, but I suspect the answer is no,
because the most core part of libuv (async sockets, the event loop,
spawning processes), must either have a completely different implementation
or is unavailable entirely. Particularly for JSVM it is also unlikely
that libuv upstream is particularly interested, because JavaScript already
runs natively in JSVM. One slightly weird part is that these platforms
do generally implement POSIX where possible, so in a number of instances,
I had to replace the libuv calls (which wrap POSIX calls on non-Windows
platforms) by the corresponding POSIX calls.

Long term I see a few options:
 - Expand libuv support for these new platforms
 - Seperate libuv into two libraries, one for async IO, process spawning, event
   loop etc, and one for the POSIX-compat layer on Windows.
 - Use POSIX calls everywhere on platforms that support it and use libuv
   for windows support where necessary (since windows does also implement
   POSIX for some things).

However, until then, this build flag is useful as a basis for rebuilding
these abstraction on top of the JSVM APIs and for simplifying boostrap
on other platforms. However, I don't envision this to be a supported or
tested configuration on platforms where libuv is otherwise available.

### CODE REVIEW

**Comment by vtjnash** [comment]
I’m against adding an unsupported configuration and a bunch of disabled code. I think we should expand libuv (for something like jsvm, it might be a separate shim library) to provide our OS-abstraction layer everywhere (option 1), rather than randomly splitting things up.

**Comment by Keno** [comment]
Yes, I'd of course also prefer to have as few conditionals as possible, they are super ugly after all. However, we won't get around a few of them at least. Things like TCP, UDP, Process Spawning, Threading and the event loop are just not available in these platform and we do need some reflection of that fact at the julia level.

**Comment by Keno** [comment]
For example, I think if we (on master),

- Take the change splitting cmd.jl out of process.jl; and
- Move the stat functions to jl_uv.c

that'd already go a long way to making this patch set easier to maintain.

**Comment by vtjnash** [comment]
> Yes, I'd of course also prefer to have as few conditionals as possible, they are super ugly after all. 
> which particular parts of this you don't like

I don't mind the changes that affect the build scripts, although I think some are redundant with USE_SYSTEM_LIBUV and the many others can be replaced with a new stub library "libuv-jsvm" (e.g. the jl_antiuv.c started here, but as a separate library that's API-compatible with libuv).

> However, we won't get around a few of them at least. Things like TCP, UDP, Process Spawning, Threading and the event loop are just not available in these platform and we do need some reflection of that fact at the julia level.

libuv already supports platforms without these things (limited network stack, no process spawning), although perhaps not very well maintained, since it's rare (and just returns ENOTSUP errors). JSVM has [sockets](https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/enet/unix.c) (WebSockets with emscripten wrapper helper?) and an event loop (of sorts—it's just libuv with a thin js wrapper, haha. Although control is inverted, so that'll be mildly annoying.). I would prefer to have libuv ported to run on itself (aka webasm) than to maintain a duplicate of it here.

**Comment by Keno** [comment]
> JSVM has [sockets](https://github.com/kripken/emscripten/blob/5187ea263120ff57424a184c1bc73259e24dc9a9/tests/enet/unix.c) (WebSockets with emscripten wrapper helper?).

Sure, but the right way to expose that to julia should the through the WebSockets.jl interface rather than the uv interface. I just don't think libuv provides anything of value on this platform (or on other embedded platforms for that matter). However, I also think that's a discussion for another day. For now I'd like to find a way to keep the base maintenance burden as low as possible for wasm support until we get more experience with what things should look like on that platform.

**Comment by vtjnash** [comment]
> I just don't think libuv provides anything of value on this platform (or on other embedded platforms for that matter)

The anticodegen file is an antipattern—it exists because our codegen doesn't provide those services (yet). The libuv project provides 2 services to us: an OS-abstraction API, and a backend implementation of the same (plus tests of the same). While the backend doesn't provide value, the API still does, since it lets us drop in a replacement project customized to suit the needs of a particular backend (such as jsvm) without throwing conditionals throughout the codebase.

> keep the base maintenance burden as low as possible

Right, that's why we split things out into separate projects, rather than intermixing them. If we didn't have libuv already, antilibuv would be a reasonable step towards building such a library. But since we already have that API defined, it would be a step backwards from that existing separation.

> but the right way to expose that to julia should the through the WebSockets.jl interface rather than the uv interface

I agree it's the right way to use it from a julia application designed to run only on top of jsvm. But IMO, that seems to be more a fundamentally (intentional) deficiency in jsvm than a feature. Ideally (from a use-ability perspective), it would run portable application just like any other platform (of course, it's instead intentionally limited for security reasons, so the point is perhaps moot). Thus, I think ideally it would be able to do both (a "native" WebSockets.jl for performance and a posix sockets wrapper for convenience / compatibility)

**Comment by StefanKarpinski** [comment]
> Sure, but the right way to expose that to julia should the through the WebSockets.jl interface rather than the uv interface.

I can see why that makes sense when it's an option but it would be super valuable to emulate UNIX sockets APIs over WebSockets so that you can run as many unmodified Julia programs as possible.

>  I would prefer to have libuv ported to run on itself (aka webasm) than to maintain a duplicate of it here.

So I also find myself leaning this way—the end goal should be to have most Julia programs "just work" in the wasm environment. Porting libuv to wasm seems to accomplish that.

**Comment by Keno** [comment]
> I can see why that makes sense when it's an option but it would be super valuable to emulate UNIX sockets APIs over WebSockets so that you can run as many unmodified Julia programs as possible.

I don't really think it makes much sense to have a `TCPSocket` type that's really a WebSocket under the hood and can't talk to a TCP server. Websockets and TCP are not interoperable. I do think it might make sense to have the `connect` and `listen` APIs return websockets clients and server rather than TCP clients and servers, but that's sort of separate from trying to implement a `uv_tcp_t` that's really a web socket.

**Comment by StefanKarpinski** [comment]
We may need to separate `Sockets` out more in that case and make them a more optional part of Julia. I'm not sure how practical that would be, but it would be good to be able to say that any package or application that doesn't use `Sockets` can run under wasm in the browser.

**Comment by Keno** [comment]
> but it would be good to be able to say that any package or application that doesn't use `Sockets` can run under wasm in the browser.

Well, we're more limited than that at the moment. E.g. I don't think we can do tasks yet, though the wasm people are working on that. It'll be a bit of a long road before everything just works. Most numerical things should be ok though.

**Comment by vchuravy** [comment]
>  E.g. I don't think we can do tasks yet,
I think Go is supporting goroutines in wasm and rust has some progress as well.

https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html

**Comment by Keno** [comment]
Yes, ironically wasm may support multithreading before co-routines, but that's all still experimental and being specified.

**Comment by Keno** [comment]
Looking into this some more, it looks like Go just doesn't use the webassembly stack and instead spills everything into its own explicitly managed linear stack. That's a possibility I suppose, but I don't know if LLVM can emit that for us.

**Comment by vtjnash** [comment]
Very stale

**Pull request closed without merging**
