### PR TITLE
Optimizing some structured matrix multiply methods

### LINKED ISSUE #525: dense*tridiag yields sparse rather than dense
```julia
julia> rand(2, 2)*Tridiagonal([1,],[2,2],[1,])
2×2 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
  [1, 1]  =  0.848589
  [2, 1]  =  0.364125
  [1, 2]  =  1.23836
  [2, 2]  =  0.419272
```
Results from hitting an `*(::AbstractMatrix, ::AbstractMatrix)` fallback. Best!

### LINKED ISSUE #741: Dense * Tridiagonal = Sparse?
```julia
julia> using LinearAlgebra

julia> N = 8
8

julia> Mx = Tridiagonal([1.0 for i in 1:N-1],[-2.0 for i in 1:N],[1.0 for i in 1:N-1])
8×8 Tridiagonal{Float64,Array{Float64,1}}:
 -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅
  1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅     ⋅
   ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅     ⋅
   ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅     ⋅
   ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅     ⋅
   ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0    ⋅
   ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0   1.0
   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    1.0  -2.0

julia> A = rand(N,N)
8×8 Array{Float64,2}:
 0.52234   0.075572   0.492018  0.534107  …  0.11925    0.933859   0.927217
 0.554405  0.674733   0.322482  0.895656     0.025754   0.842152   0.810342
 0.116686  0.603084   0.130214  0.475674     0.0697535  0.97639    0.713087
 0.717719  0.211584   0.568428  0.294381     0.643912   0.270161   0.337518
 0.251835  0.569177   0.554402  0.577696     0.535705   0.854619   0.145042
 0.267439  0.0778166  0.480589  0.133326  …  0.365856   0.543645   0.157496
 0.366063  0.68394    0.365163  0.443594     0.75635    0.0335027  0.0916263
 0.423794  0.728052   0.885349  0.717036     0.24141    0.017163   0.651004

julia> AMx = A*Mx
8×8 SparseArrays.SparseMatrixCSC{Float64,Int64} with 64 stored entries:
  [1, 1]  =  -0.969108
  [2, 1]  =  -0.434078
  [3, 1]  =  0.369713
  [4, 1]  =  -1.22385
  [5, 1]  =  0.0655065
  [6, 1]  =  -0.457062
  [7, 1]  =  -0.0481849
  [8, 1]  =  -0.119537
  [1, 2]  =  0.863215
  [2, 2]  =  -0.472578
  ⋮
  [7, 7]  =  0.780971
  [8, 7]  =  0.858088
  [1, 8]  =  -0.920576
  [2, 8]  =  -0.778531
  [3, 8]  =  -0.449783
  [4, 8]  =  -0.404876
  [5, 8]  =  0.564534
  [6, 8]  =  0.228652
  [7, 8]  =  -0.14975
  [8, 8]  =  -1.28485
```

This seems to be a trap that will give you dense matrices in SparseMatrixCSC form. In general, Dense * Tridiagonal will be as dense as it started, so I'm not sure this was a conscious decision.

```julia
julia> @which A*Mx
*(A::AbstractArray{T,2} where T, B::AbstractArray{T,2} where T) in LinearAlgebra at C:\Users\accou\AppData\Local\Programs\Julia\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\matmul.jl:152
```

This was on v1.4, so I'm not sure if it's on master.

### PR DESCRIPTION
**Pull request by mcognetta**
This PR addresses JuliaLang/julia#28345 and JuliaLang/LinearAlgebra.jl#525 as well as some missed optimizations from JuliaLang/julia#28883.

A summary of the changes:

- Dense times Structured matrices output dense matrices (not `SparseMatrixCSC`)
- `Bidiagonal`x`Tridiagonal`, `SymTridiagonal`x`SymTridiagonal`, and others output `SparseMatrixCSC` (not Dense). These changes were mentioned in JuliaLang/julia#28883, but apparently I missed them in that PR.
- `Bidiagonal`x`Bidiagonal` outputs `Tridiagonal` or `SparseMatrixCSC` depending on if `A.uplo == B.uplo`. Before it output `SparseMatrixCSC` or Dense.

(EDIT: Closes JuliaLang/LinearAlgebra.jl#741, closes JuliaLang/LinearAlgebra.jl#525.)

Below are some benchmarks as well as the input/output types:

-------------------------------------------------------------------------

Before:

| A              | B              | A*B             | Time             |
|----------------|----------------|-----------------|------------------|
| Array          | Diagonal       | Array           | 0.029855 seconds |
| Array          | Bidiagonal     | SparseMatrixCSC | 2.767608 seconds |
| Array          | Tridiagonal    | SparseMatrixCSC | 2.813555 seconds |
| Array          | SymTridiagonal | SparseMatrixCSC | 2.826780 seconds |
| Diagonal       | Array          | Array           | 0.030034 seconds |
| Diagonal       | Diagonal       | Diagonal        | 0.000007 seconds |
| Diagonal       | Bidiagonal     | SparseMatrixCSC | 0.053484 seconds |
| Diagonal       | Tridiagonal    | SparseMatrixCSC | 0.060171 seconds |
| Diagonal       | SymTridiagonal | SparseMatrixCSC | 0.059392 seconds |
| Bidiagonal     | Array          | Array           | 0.013068 seconds |
| Bidiagonal     | Diagonal       | SparseMatrixCSC | 0.052733 seconds |
| Bidiagonal     | Bidiagonal     | Array           | 0.344665 seconds |
| Bidiagonal     | Tridiagonal    | Array           | 0.345147 seconds |
| Bidiagonal     | SymTridiagonal | Array           | 0.344073 seconds |
| Tridiagonal    | Array          | Array           | 0.014226 seconds |
| Tridiagonal    | Diagonal       | SparseMatrixCSC | 0.057033 seconds |
| Tridiagonal    | Bidiagonal     | Array           | 0.346379 seconds |
| Tridiagonal    | Tridiagonal    | Array           | 0.345191 seconds |
| Tridiagonal    | SymTridiagonal | Array           | 0.347181 seconds |
| SymTridiagonal | Array          | Array           | 0.011845 seconds |
| SymTridiagonal | Diagonal       | SparseMatrixCSC | 0.057408 seconds |
| SymTridiagonal | Bidiagonal     | Array           | 0.349033 seconds |
| SymTridiagonal | Tridiagonal    | Array           | 0.347890 seconds |
| SymTridiagonal | SymTridiagonal | Array           | 0.348104 seconds |

```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

----------------------------------------------------------------

This PR:

| A              | B              | A*B             | Time             |
|----------------|----------------|-----------------|------------------|
| Array          | Diagonal       | Array           | 0.013508 seconds |
| Array          | Bidiagonal     | Array           | 0.024095 seconds |
| Array          | Tridiagonal    | Array           | 0.007269 seconds |
| Array          | SymTridiagonal | Array           | 0.024687 seconds |
| Diagonal       | Array          | Array           | 0.011103 seconds |
| Diagonal       | Diagonal       | Diagonal        | 0.000009 seconds |
| Diagonal       | Bidiagonal     | Bidiagonal      | 0.000103 seconds |
| Diagonal       | Tridiagonal    | Tridiagonal     | 0.000106 seconds |
| Diagonal       | SymTridiagonal | Tridiagonal     | 0.000108 seconds |
| Bidiagonal     | Array          | Array           | 0.013104 seconds |
| Bidiagonal     | Diagonal       | Bidiagonal      | 0.000111 seconds |
| Bidiagonal     | Bidiagonal     | SparseMatrixCSC | 0.002295 seconds |
| Bidiagonal     | Tridiagonal    | SparseMatrixCSC | 0.002942 seconds |
| Bidiagonal     | SymTridiagonal | SparseMatrixCSC | 0.003073 seconds |
| Tridiagonal    | Array          | Array           | 0.022158 seconds |
| Tridiagonal    | Diagonal       | Tridiagonal     | 0.000108 seconds |
| Tridiagonal    | Bidiagonal     | SparseMatrixCSC | 0.002936 seconds |
| Tridiagonal    | Tridiagonal    | SparseMatrixCSC | 0.003766 seconds |
| Tridiagonal    | SymTridiagonal | SparseMatrixCSC | 0.003762 seconds |
| SymTridiagonal | Array          | Array           | 0.011779 seconds |
| SymTridiagonal | Diagonal       | Tridiagonal     | 0.000117 seconds |
| SymTridiagonal | Bidiagonal     | SparseMatrixCSC | 0.003116 seconds |
| SymTridiagonal | Tridiagonal    | SparseMatrixCSC | 0.003845 seconds |
| SymTridiagonal | SymTridiagonal | SparseMatrixCSC | 0.003791 seconds |

### CODE REVIEW

**Comment by mcognetta** [comment]
attn: @ViralBShah This is the new version of #28345.

**Comment by StefanKarpinski** [comment]
Let's get this thing merged this time!

**Comment by mcognetta** [comment]
I resolved the ambiguities by restricting the left side to be `::Array`. I don't think this is a particularly good solution (since there could be other subtypes of `AbstractMatrix` that need consideration), but the alternative involved untangling a ton of ambiguous matrix multiply definitions. Suggestions/comments are appreciated.

**Comment by andreasnoack** [comment]
> I resolved the ambiguities by restricting the left side to be `::Matrix`

Did you try with `StridedMatrix`?

**Comment by mcognetta** [comment]
@andreasnoack Yes, that seems more appropriate. Thanks.

**Review by andreasnoack — APPROVED** [review]

**Comment by mcognetta** [comment]
Fixed merge conflicts.

**Comment by andreasnoack** [comment]
Looks like something broke

**Comment by mcognetta** [comment]
Seems like I accidentally deleted the relevant code. Should be fixed now.

**Comment by andreasnoack** [comment]
Thanks. One concern here is that `BidiagonalxTridiagonal` returning a sparse matrix implies a dependency of `LinearAlgebra` on `SparseArrays`. We already have a few of these so maybe we just want to accept it but we have been thinking about making the sparse stdlibs more stand-alone and pluggable in which case it would be unfortunate to add another such dependency. An alternative could be to add an informative error message for `BidiagonalxTridiagonal` asking the user to convert to sparse matrices before multiplying. I doubt that this will be a common operation so I'd expect few users to hit it.

**Comment by mcognetta** [comment]
@andreasnoack Yes, I have noticed this is several places with structured matrices. Would you be ok with a warning instead of an error (`Bidiag` times `Tridag` runs before this patch, having it error would be breaking)?

**Comment by andreasnoack** [comment]
I.e. dense output with a warning?

**Comment by mcognetta** [comment]
I had thought Sparse output with a warning (which I guess is still breaking, but better than interrupting execution).

**Comment by andreasnoack** [comment]
The problem is that sparse output with a warning would introduce the dependency. We'd need to make a general decision if we can allow LinearAlgebra to depend on SparseArrays

**Comment by mcognetta** [comment]
I had it backwards, I thought LinearAlgebra already had a dependency on SparseArrays, but it is the other way around. In this case, is it best to throw an error and move the method definition to SparseArrays?

**Comment by andreasnoack** [comment]
I guess we could also continue to return a dense array?

**Comment by dkarrasch** [comment]
I kind of agree that, if the result type is none of `LinearAlgebra`'s, the result should be dense. So if someone wants to invoke the sparse machinery, then (s)he would need to make at least one of the factors sparse. I remember I optimized the sparse constructors for structured matrices over at #32492, so hopefully that shouldn't be a computational bottleneck.

But, I need to admit that I'm confused. In a fresh Julia session:
```julia
using LinearAlgebra
B = Bidiagonal(rand(4), rand(3), 'U')
@which similar(B, Float64, (3,3))
```
returns
```julia
similar(B::Bidiagonal, ::Type{T}, dims::Union{Tuple{Int64}, Tuple{Int64,Int64}}) where T in SparseArrays at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/SparseArrays/src/SparseArrays.jl:50
```
I couldn't find where we import this `similar` method from `SparseArrays` in `LinearAlgebra`. Shouldn't it throw a `MethodError`? I was digging a bit, but couldn't find any explicit reference to `sparse` or `Sparse` in `LinearAlgebra`, so I assume the only dependency is via these `similar` methods, right? Also, in the `Project.toml` of `LinearAlgebra`, `SparseArrays` occurs only in the extras and for testing.

**Comment by ranocha** [comment]
Is there any update on this? Or could I help in moving this PR forward?

**Comment by mcognetta** [comment]
Yeah this sort of stalled. Happy to keep working on it, perhaps with @ranocha if there is interest.

**Comment by dkarrasch** [comment]
`BiTriSym * BiTriSym` is currently governed by https://github.com/JuliaLang/julia/blob/ab04170ece55886d624c9836140693be2426cfa9/stdlib/SparseArrays/src/SparseArrays.jl#L58-L61

I don't understand how this is "known" to Julia without declaring `using SparseArrays`. Anyway, this PR here doesn't change the sparse return type, it only removes the case of different (in the sense of uplo) bidiagonal matrices from that list and makes it return a tridiagonal. So, we could (i) go with it, but remove the tests for `SparseMatrix` return types, or (ii) remove that special casing, and only go with the `*(::StridedMatrix, ::BiTriSym)` part. Personally, I think adding the bidiag-bidiag special case is much less important than disentangling the stdlibs,so I'd favor option (ii).

**Comment by KristofferC** [comment]
> I don't understand how this is "known" to Julia without declaring using SparseArrays. 

Type piracy in combination with that SparseArrays exist in the sysimage.

**Comment by mcognetta** [comment]
Seems all of these optimizations have been added in other PRs so I will close this one.

**Pull request closed without merging**
