### PR TITLE
RFC: Distribute an OS X Installer

### PR DESCRIPTION
**Pull request by slarew**
I wrote some scripts that properly codesign and package up a Julia distribution into an installer for OS X.

I propose either distributing both the OS X app _and_ an OS X installer, or entirely move to only distributing an OS X installer.

Motivation: I personally prefer installing Julia directly into `/usr/local`.  If you already have Git and use other command line tools regularly, having Julia in `/usr/local` just feels right.  When Julia is inside an app bundle, the julia binary is not in the `PATH`, requiring extra knowledge and steps from the user who does not want to double click the app.  Furthermore, the Julia app is merely a wrapper (launches Terminal.app and runs the embedded julia binary) and not a typical OS X application or even IDE.  Using the OS X installer avoids the hassle of manually unpacking an archive and moving it into place.  Moreover, the installer has both a UI and command line interface for regular and power users alike.

I think there are some benefits to the Julia app that is currently distributed for OS X:
1. Easy "drag-n-drop" install.
2. Easy uninstall (just delete app or move app to trash).
3. Easy to run (double click the app).
4. Included Git (for those without it).
5. Simultaneous availability of multiple versions of Julia.

The first three points are arguably user friendly for novices.  To compare the installer approach to the benefits of the app:
1. The installer is nearly as easy to use for installation as drag-n-drop.  However, it currently requires admin privileges.
2. The installer adds an uninstall script under `sbin/` (but user must be told it exists).
3. Once installed, the user must know how to launch a shell and type `julia` (automated by the double click app approach).  An optional wrapper "Julia app" could be added to the installer that mimics the current Julia app.
4. Git could be added to the installer as an optional (opt-in or -out) component.
5. Supporting simultaneous install and switching between versions could be supported, but would require more thought for a good design.

I think distributing an app inside a DMG has some initial advantages for regular/novice users, but the burden is diminished or reversed for those who are comfortable working with a shell.

If you want to test the installer that is built by this script, you can find a copy at [my personal site](https://www.slarew.net/julia-os-x-installer/).

I believe the requirement of admin privileges could be removed.  I created an installer package that was able to target directories in the user's home folder without admin privileges. However, the installer would fail (with a cryptic error message) if the user said to target his or her home folder but did not manually change the install location to be within the home folder.  I suspect this could be fixed if some javascript was added to the installer package with the correct logic.

Original pr #15746

### CODE REVIEW

**Comment by vtjnash** [comment]
i believe it would be more correct to install to `/opt/julia-v0.X` and install a symlink into `/usr/local/bin/julia`. however, i'm not a huge fan of hiding gunzip behind a huge installer package. it's what we do on windows to give it a "native" feel, but i find it a huge pita. i would rather provide some convenient way to suggest the user calls from their REPL:
```
run(`sudo ln -s $JULIA_HOME/julia /usr/local/bin/julia`)
```

**Comment by slarew** [comment]
@vtjnash Are you suggesting `/opt/julia-vX.Y` as a means of supporting multiple simultaneous installs of julia?  The idea being to simply change where the symlink `/usr/local/bin/julia` points to?  That is one (reasonable) approach.

Also, you're correct that the installer package hides a gzip'd archive of the distribution inside a bunch of support packaging.  The support packaging is what provides the information (e.g. readme, license, graphics, min os version, etc.) to OS X Installer.  The main benefit in my estimation is that the installer package can be run as a GUI installer natively on OS X.  Moreover, since the installer package is nearly entirely composed of the gzip'd binary distribution file, it's essentially equivalent to providing the user with a standard tar.gz archive.

If you require the user to be able to symlink julia into `/usr/local`, this amounts to the same level of burden as running `installer -pkg julia-X.Y.Z.pkg -target /opt/julia-vX.Y && ln -s /opt/julia-vX.Y/bin/julia /usr/local/bin/julia`.

In fact, I think creating a symlink could be done automatically (opt-out behavior) by the OS X Installer.  This might be accomplished with a javascript embedded in the installer package.

**Comment by vtjnash** [comment]
> The main benefit in my estimation is that the installer package can be run as a GUI installer natively on OS X. Moreover, since the installer package is nearly entirely composed of the gzip'd binary distribution file, it's essentially equivalent to providing the user with a standard tar.gz archive.

How is something that is "essentially equivalent" but with the advantage of being more complex and much slower an improvement? Distribution of software via a `.dmg` is the standard installation mechanism for Apple users.

**Comment by StefanKarpinski** [comment]
I think we should stick with `.dmg` for OS X installation. I guess we could also provide a tarball like the Linux one, but I don't think that should be the standard installation mechanism.

**Comment by slarew** [comment]
In the pr, I tried to outline a comparison of the dmg+app approach to an os x installer.  The way I see it, the OS X installer is user friendly because it provides the opportunity to show the user a readme, license, (optionally) change the install target.  Moreover, if the user is comfortable with the command line, the installer package can be installed *quickly* with one command to the standard unix location.  Thus, the installer balances the needs of regular users and power users.

As for DMG as the standard *distribution* method for OS X, I agree that a majority of OS X apps that I download are distributed in DMG files.  However, the DMG is not an installation method in and of itself.  It still requires the user to know to move the app bundle to (usually) the Applications folder.  The DMG is often made more user friendly by adding a background image with text telling the user to drag the app bundle to the Applications folder.  Nevertheless, downloading a DMG and drag-n-drop installing is very common and thus the de facto distribution and installation method.

In my opinion, the problem with distributing Julia in an app bundle wrapped inside a DMG is that the Julia app is not a typical OS X app.  It does not have its own Cocoa gui (e.g. an IDE for julia). The app bundle simply launches Terminal and execs julia.  Such a wrapper app could easily be distributed and installed by default by an OS X installer without awkwardly hiding the jullia binary inside the app bundle.

**Comment by staticfloat** [comment]
@slarew I agree with many of your points, however I see the `.app` distribution serving a different purpose than command-line usage.  For users that want to habitually use Julia from `/usr/local`, it's quite likely they have either MacPorts ([MacPorts portfile](https://trac.macports.org/browser/trunk/dports/lang/julia/Portfile)) or Homebrew ([Homebrew tap](https://github.com/staticfloat/homebrew-julia)) installed.

Rather than install to `/usr/local`, which is managed by Homebrew, and hence will raise warnings in Homebrew if non-`brew`-managed software puts itself in there, we could install to `/opt` as suggested by @vtjnash, but I guess the question I ask is "What use case is this solving that's not already solved by the Homebrew and MacPorts installers"?

**Comment by johnmyleswhite** [comment]
As a counterpoint to that, I'm a command-line user who would like to do exactly what @slarew is proposing and I've always been really surprised we didn't install things into `/usr/local`. I intentionally don't use MacPorts or Homebrew, so there's no conflicts for me.

**Comment by slarew** [comment]
The Homebrew FAQ indicates that it should be safe to install to `/usr/local` without interference. Although I suspect there could be issues nevertheless.  At that point we're running into all the problems that lead to the /opt/xxx types of folders or Homebrew type linking solutions.

I'll reiterate that in the PR I propose distributing *both* an installer and app as one option.

**Comment by ihnorton** [comment]
@slarew: regardless of the outcome of this discussion, I just want to say: thank you for working on this! This is an excellent (first?) PR.

**Comment by tkelman** [comment]
I'm not opposed to doing both, but that could get a bit confusing in terms of differentiating the two and accurately informing users which one they should be using.

**Comment by slarew** [comment]
Any thoughts on this PR for 0.5?

**Comment by tkelman** [comment]
Too late for 0.5 I'd say, seems to me there's still unaddressed feedback above. We can consider it during 0.6-dev, and address the concerns and determine if our buildbot infrastructure can produce these as an alternative.

**Comment by simonbyrne** [comment]
Technically, we should probably distribute Julia as an OS X Framework:
https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Frameworks.html#//apple_ref/doc/uid/10000183i
which is how most other languages are packaged (R, Python, Ruby, etc).

This might require rearranging some file locations, and we might need to figure out where packages and whatnot should go.

**Comment by slarew** [comment]
@simonbyrne  I've already started a branch to do just that.  See my work at https://github.com/slarew/julia/commits/sgl/darwinframework

**Comment by slarew** [comment]
I've also done some work to make Julia work in the macOS App Sandbox, but that is very much a WIP.  I pushed some changes to https://github.com/slarew/julia/tree/sgl/sandboxjulia for those interested.  I think I have more in my local branch that aren't on Github yet.

**Comment by simonbyrne** [comment]
Ah that would be great. 

As someone who seems to understand the OS X packaging process, would you mind looking over #18522?

**Comment by ViralBShah** [comment]
The framework build is the right direction to move in.

**Pull request closed without merging**
