### PR TITLE
Fix #10970. Allow LU factorizing non-square sparse matrices.

### LINKED ISSUE #10970: lufact should not require a square matrix
Here's the error code 

function lufact{Tv<:UMFVTypes,Ti<:UMFITypes}(S::SparseMatrixCSC{Tv,Ti})
    S.m == S.n || error("argument matrix must be square")

lu factorization of rectangular matrices is useful as a preconditioner for the normal 
equation A'Ax = A'b (used for example by Wilkinson and Duff and Bjorck ) 

The option of using rectangular matrices is available in UMFPACK C code 
and in the matlab and octave wrappers on it.

### PR DESCRIPTION
**Pull request by andreasnoack**
E.g.

``` julia
julia> full(lufact(sprandn(5,3,0.5))[:L])
5x3 Array{Float64,2}:
  1.0        0.0        0.0      
  0.0        1.0        0.0      
  0.0        0.56509    1.0      
 -0.300521  -0.673485  -0.0597699
  0.0        0.0        0.0
```

### CODE REVIEW

**Comment by tkelman** [comment]
Cool, +1

cc @gwhowell

**Comment by gwhowell** [comment]
Looks good,
Thanks,
Gary

**Comment by ViralBShah** [comment]
Is it realistic to backport this?

**Comment by andreasnoack** [comment]
Yes. I could cherry-pick it cleanly, so I think we should just do it by the end of the week.

**Comment by tkelman** [comment]
The tests have been moved around to different files, but otherwise the change looks pretty small - depends whether the umfpack code looks the same on release-0.3.

**Comment by andreasnoack** [comment]
@tkelman I've already tried `git cherry-pick` and there weren't any conflicts.

**Comment by tkelman** [comment]
Sounds good, just make sure the added tests get run under release-0.3's file organization.

At this point I wouldn't be opposed to saying all backports to release-0.3 from now on should go through pr's against release-0.3, but I might be the only one who thinks that.

**Comment by tkelman** [comment]
Wasn't sure if you were going to do the backport, so I did in a6efa596360cda90f1fb4336bfaa328c26d9efea.

`git cherry-pick` is smarter than I thought it was, it seems to have figured out that the tests have moved around to different files.

**Comment by tkelman** [comment]
@gwhowell just your luck that we should also have 0.3.8 out momentarily, binaries are building now

**Comment by gwhowell** [comment]
Hi,
I
 was able to recompile 0.3.7 with the lufact  nonsquare changes.  It's
probably working (returns results, have not yet checked the results).

If I make progress with the column pivoting, I'll let you know.

Another operator I'm interested in is condest.  matlab and octave seem to
use the same
algorithm for that (actually estimates the L1 condition number, uses work
of
Higham and Hager).  When I get more time I can submit that as a ticket (and
perhaps
give you some code that seems to work).  I use condest at runtime to decide
what preconditioners to use.

So thanks,
Gary Howell

**Comment by tkelman** [comment]
@gwhowell ref https://github.com/JuliaLang/julia/issues/6485

**Pull request merged**
