### PR TITLE
Revert "Remove repackaging SuiteSparse script. It is no longer needed."

### LINKED ISSUE #26499: umfpack library issue on mac os travis
E.g. https://travis-ci.org/JuliaLang/julia/jobs/354433461

### PR DESCRIPTION
**Pull request by ararslan**
This reverts commit 1b099846879a02cd4c9884f33f690e6813f1415f. This script is used by Travis, which is causing https://github.com/JuliaLang/julia/issues/26499. Fixes #26499.

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
We should turn on protected branches.

**Comment by ararslan** [comment]
The master branch is already protected. It only prevents force pushing to master, but people can still push to master without `--force`.

**Comment by ararslan** [comment]
I didn't think that setting existed, otherwise we probably would have already enabled it. If it does though then :100: for enabling it.

**Comment by vchuravy** [comment]
The closest option is called

> Require pull request reviews before merging
When enabled, all commits must be made to a non-protected branch and submitted via a pull request with the required number of approving reviews and no changes requested before it can be merged into master.

**Comment by ararslan** [comment]
The Windows failures are timeouts. The macOS failure is that LibGit2 failed to resolve github.com which is weird, so I restarted it.

**Comment by ararslan** [comment]
The Mac build will take a while; looks like it's recompiling SuiteSparse from source.

**Comment by ararslan** [comment]
Okay, the Mac build timed out at 3 hours. @staticfloat, do you know what to do in this situation, where we need to recompile a binary dependency but trying to do it hits the job time limit?

**Comment by KristofferC** [comment]
Requiring a pr is a good idea but not if it forces a review approved.

**Comment by bramtayl** [comment]
Maybe add some comments about why this is needed so it doesn't get deleted again?

**Comment by nalimilan** [comment]
Also the mention of the script in README could have to be reintroduced: https://github.com/JuliaLang/julia/pull/26432#discussion_r175147398

**Comment by ViralBShah** [comment]
We still don't want people to use this script in their own builds or depend upon it. It should not be mentioned in the Readme. The purpose should remain only for Mac Travis builds.

**Comment by vchuravy** [comment]
The Mac OS build bot timed out because it failed to download GCC

```
==> Installing staticfloat/julia/julia dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-7.3.0_1.el_capitan.bottle.tar.gz
/usr/bin/curl --show-error --user-agent Homebrew/1.5.10 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 --fail --silent --location --remote-time --continue-at - --output /Users/travis/Library/Caches/Homebrew/gcc-7.3.0_1.el_capitan.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/gcc-7.3.0_1.el_capitan.bottle.tar.gz
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "gcc"
Download failed: https://homebrew.bintray.com/bottles/gcc-7.3.0_1.el_capitan.bottle.tar.gz
```

I just kicked it off again hoping that it is a network fluke.

**Pull request merged**
