### PR TITLE
Backports 1.5.1

### LINKED ISSUE #36869: julia crashes during method disptch
recently julia dispatch used a less specific method rather than the expected more specific method. While playing around i discovered that following code crashes julia.

```julia
julia> using SentinelArrays
b 
julia> b =SentinelArray([1,2,3,4])
4-element SentinelArray{Int64,1,Int64,Missing,Array{Int64,1}}:
 1
 2
 3
 4

julia> f(::Type{T}, y, x::AbstractVector{T}) where T = (T, y)
f (generic function with 1 method)

julia> function g(x, y)
       if x == Int64
        z = true
       else
        z= false
        end
        return f(x, z, y)
        end
g (generic function with 1 method)

julia> f(Union{Missing, Int64}, true, b)
(Union{Missing, Int64}, true)

julia> Union{Missing, Int64} == Int64
false

julia> f(Union{Missing, Int64}, true, b)
(Union{Missing, Int64}, true)

julia> f(Union{Missing, Int64}, false, b)
(Union{Missing, Int64}, false)

julia> g(Union{Missing, Int64}, b)
Unreachable reached at 0x7ff87d4a2085signal (4): Illegal instruction
in expression starting at REPL[9]:1
g at ./REPL[4]:7
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2159 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:369
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:458
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:409 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:817
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:911
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:819
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:769
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:848
eval at ./boot.jl:331
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:358
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:687
unknown function (ip: (nil))
Allocations: 30348217 (Pool: 30340443; Big: 7774); GC: 28
Illegal instruction (core dumped)
```

is this behavior expected??
```julia
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
```

### LINKED ISSUE #36955: LLVM Crash in SelectionDAG
Over in https://github.com/PumasAI/PumasTutorials.jl/pull/56, @chriselrod reports an LLVM crash in SelectionDAG with the following backtrace:

```
julia> pop = read_nca(data, llq=0concu, timeu=timeu, concu=concu, amtu=amtu)

signal (11): Segmentation fault
in expression starting at REPL[128]:1
isVectorTy at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/IR/Type.h:229 [inlined]
isExtendedVector at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/ValueTypes.cpp:59
isVector at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:151 [inlined]
getScalarType at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:260
getScalarSizeInBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:298 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/TargetLowering.cpp:1569
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/TargetLowering.cpp:863
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1225 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:300 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:293
visitOR at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:5891
combine at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1801
Run at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1625 [inlined]
Combine at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:20876
CodeGenAndEmitDAG at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:817
SelectAllBasicBlocks at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1588
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #36254 - docs: Fix indentation on !!! warn section
- [x] #36734 - fix stackoverflow in circshift!(x, y, (1.0,))
- [x] #36835 - Update Mozilla CA certificate store to latest (07-22-2020) for libgit2 SSL.
- [x] #36416 - Make compilecache atomic
- [x] #36638 - Pass force=true option to rename in case of loading failure in compilecache
- [x] #36502 - Update X86 feature and CPU detection
- [x] #36819  - Fix compact float printing when output contains exactly 6 digits
- [x] #36485 -  Update ARM feature and CPU detection (supersedes #36464) 
- [x] #36831 - A few processor detection/features tweaks
- [x] #36850 - Fix allunique(::StepRangeLen)
- [x] #36858 - test: fix textual output for precompile
- [x] #36914 - REPL: fix confusion between function name and local variable
- [x] #36956 - Fix #36955
- [x] #36776 - update MPFR to v4.1.0
- [x] #36705 - Strip non-integral address space from datalayout after GC lowering 
- [x] #36959 - Fix replace(::String, count=1) with empty pattern (issue #36953)
- [x] #36996 - fix #36869, incorrect intersection with `Union` in supertype
- [x] #36859 - Better deployment of rc docs 
- [x] #36975 - Improve inferrability of generic matrix-vector multiplication
- [x] #36983 - Include new Documenter footer: "Powered by Documenter.jl and the Julia Programming Language" 
- [x] #36697  - build: make libunwind linked dynamically 
- [x] #37069 - Add `get-task-allow` entitlement to allow debuggers to attach to codesigned Julia
- [x] #37105 - workaround for #35800, inference issue in `mapreduce` 
- [x] - Update Pkg

Non-merged PRs with backport label:
- [ ] #36821 - Fix function call to rec_backtrace_ctx when using USE_SYSTEM_LIBUNWIND=1

### CODE REVIEW

**Comment by quinnj** [comment]
Can we add #36819 as a backport?

**Comment by KristofferC** [comment]
Sure, done.

**Comment by ianshmean** [comment]
Backport for the arm cpu feature detection would be good too https://github.com/JuliaLang/julia/pull/36485

**Comment by musm** [comment]
Are PRs like https://github.com/JuliaLang/julia/pull/36756 eligible for backporting?

**Comment by KristofferC** [comment]
Upgrading libuv seems a bit too big for a patch release, in my opinion.

**Comment by jmkuhn** [comment]
Could you add #36705 to enable building on ARMv7l?

**Comment by non-Jedi** [comment]
Not sure exactly what the backport policy is but #36697 would be helpful to fix #36943.

**Comment by ianshmean** [comment]
Probably a good idea to backport the documentation footer for SEO/tiobe etc. #36983

**Comment by JeffBezanson** [comment]
Looks like we cannot use e438d0e9874b154d64da8f6523e1a57b2f44f5f9, since it calls `parseatom` that doesn't exist in 1.5.

**Comment by KristofferC** [comment]
> Looks like we cannot use e438d0e, since it calls parseatom that doesn't exist in 1.5.


image

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/36899#issuecomment-674821277) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b467de5ea773217b359dfe7ec2357802a7fce96c/0d71d8c_vs_f0b8c76/report.md). cc @ararslan

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/36899#issuecomment-674821347) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/5206e8006b84e70e4e9e0bf474e5a6b44366b24f/pkgeval/by_hash/317b2cf_vs_f0b8c76/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ARCHModels", "Autologistic", "BitFloats", "Dagger", "DataDrivenDiffEq", "IncrementalInference", "KissMCMC", "LiveServer", "NeuralArithmetic", "SparseGaussianProcesses", "XPORTA"], vs = ":release-1.5")`

**Comment by KristofferC** [comment]
Dropping https://github.com/JuliaLang/julia/pull/36856 since it changes exception types.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/36899#issuecomment-675265785) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/943384554f9d9b8edc48f4ca1a6563fdb27f9cde/pkgeval/by_hash/317b2cf_vs_f0b8c76/report.md). cc @maleadt

**Comment by KristofferC** [comment]
Should be good to go now.

**Pull request merged**
