### PR TITLE
Prevent pool allocations under MEMDEBUG

### PR DESCRIPTION
**Pull request by maleadt**
More work on getting the build through ASAN (which enables MEMDEBUG).

### CODE REVIEW

**Comment by yuyichao** [comment]
These shouldnt be necessary

**Comment by maleadt** [comment]
An ASAN build fails without these, as `gc_setmark_pool` call `find_region` before calling `gc_setmark_pool_` (which indeed already checks for `MEMDEBUG`).

**Comment by yuyichao** [comment]
I'd like to have as few ifdefs as possible in the gc. The preferred way would be to remove the assertion in find region (and possible the maybe argument) and let the user (e.g. after the ifdefs in gc setmark pool) assertion the pool is not null

**Comment by maleadt** [comment]
OK sure, will update in a bit.

**Comment by maleadt** [comment]
Updated. In addition, could we use ASAN runtime functions (`__asan_poison_memory_region`, `__asan_unpoison_memory_region`) to be able to run without MEMDEBUG?

**Comment by yuyichao** [comment]
LGTM. (Never used ASAN so not sure about using ASAN runtime functions)

**Comment by carnaval** [comment]
Yep. You could poison cells during sweep (sweep_page) and unpoison them during alloc (__pool_alloc).

**Pull request merged**
