### PR TITLE
Handle non-const function in `return_types` special case

### LINKED ISSUE #19641: Core.Inference.return_type and closures
In [this discourse thread](https://discourse.julialang.org/t/towards-broadcast-over-combinations-of-sparse-matrices-and-scalars/910), `@yuyichao` (thanks!) indicated that extending `Core.Inference.return_types` to handle closures should be possible. IIUC, doing so would enable simplification and improvement of the `broadcast` promotion mechanism. Ref. #19421 and #19633. Best!

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #19641

### CODE REVIEW

**Comment by yuyichao** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19667#issuecomment-268431914) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/61008b04f43822deec137b427f014ca2c88d74c6/10910a5_vs_a041e6e/report.md). cc @jrevels

**Comment by Sacha0** [comment]
I could not reproduce any of the possible regressions locally. Best!

**Comment by Sacha0** [comment]
Confirming the test case in https://github.com/JuliaLang/julia/pull/19633#issuecomment-268158362 succeeds on this branch:
```julia
julia> baz() = (a = 1; Base._return_type((x, y) -> x + y + a, Base.Broadcast.typestuple(eye(4), eye(4))))
baz (generic function with 1 method)

julia> baz()
Float64

julia> @code_warntype baz()
Variables:
  #self#::#baz
  a::Int64
  #3::##3#4{Int64}

Body:
  begin
      a::Int64 = 1
      SSAValue(0) = Base._return_type
      #3::##3#4{Int64} = $(Expr(:new, ##3#4{Int64}, :(a)))
      SSAValue(1) = #3::##3#4{Int64}
      $(Expr(:invoke, MethodInstance for eye(::Type{T}, ::Int64, ::Int64), :(Base.eye), :(Base.Float64), 4, 4))
      $(Expr(:invoke, MethodInstance for eye(::Type{T}, ::Int64, ::Int64), :(Base.eye), :(Base.Float64), 4, 4))
      SSAValue(2) = $(QuoteNode(Tuple{Float64,Float64}))
      return $(QuoteNode(Float64))
  end::Type{Float64}
```
Best!

**Comment by musm** [comment]
ldexp, frexp, exponent, and significand are notoriously noisy. The functions are evaluated on scalars and take a few ns to finish.  BenchmarkTools locally has ns resolution on my local pc, but perhaps not on the benchmarking server

**Comment by jrevels** [comment]
> BenchmarkTools locally has ns resolution on my local pc, but perhaps not on the benchmarking server

The latest BenchmarkTools tag has picosecond resolution (it will pretty print in fractions of nanoseconds), but I still need to update Nanosoldier with that capability.

**Comment by Sacha0** [comment]
Confirming that the test cases I've written against the code mentioned in [the related discourse thread](https://discourse.julialang.org/t/towards-broadcast-over-combinations-of-sparse-matrices-and-scalars/910) succeed on this branch. Best!

**Comment by andyferris** [comment]
Is this backportable?

(@tkelman are there any backports planned for v0.5? we still haven't seen v0.5.1, but then again I haven't seen a lot of bugs either)

**Comment by yuyichao** [comment]
Rebased. AppVeyor failure is the intermittent libgit2 network issue..... @JeffBezanson @vtjnash

**Comment by yuyichao** [comment]
Ping @JeffBezanson @vtjnash

**Review by vtjnash — APPROVED** [review]

**Review by JeffBezanson — APPROVED** [review]

**Pull request merged**
