### PR TITLE
Fix #30006, getindex accessing fields that might not exist

### LINKED ISSUE #30006: sparse matrix with non-Int64 index type slice assignment failure
```
julia> using SparseArrays

julia> a=SparseMatrixCSC{Float64, Int32}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int32} with 0 stored entries

julia> a[:,1]=[1,2,3]
ERROR: type Slice has no field stop
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] getindex at ./range.jl:610 [inlined]
 [3] setindex!(::SparseMatrixCSC{Float64,Int32}, ::Array{Int64,1}, ::Colon, ::Int64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/sparsematrix.jl:2656
 [4] top-level scope at none:0
```

The same code with Int64 in place of Int32 succeeds
```

julia> a=SparseMatrixCSC{Float64, Int64}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int64} with 0 stored entries

julia> a[:,1]=[1,2,3]
3-element Array{Int64,1}:
 1
 2
 3
```

### PR DESCRIPTION
**Pull request by raghav9-97**
Fixes #30006

### CODE REVIEW

**Comment by raghav9-97** [comment]
I don't think this build fail is because of my code.

**Comment by ViralBShah** [comment]
Yes, failure is not relevant. Should be good to merge with some tests.

**Comment by ViralBShah** [comment]
This should serve as a test from #30006:

```
@test Base.Slice(Base.OneTo(3))[Int32(1)] == Int32(1)
```

**Comment by JeffBezanson** [comment]
This could also use a better commit message, e.g. `fix #30006, range getindex accessing fields that might not exist`.

**Comment by raghav9-97** [comment]
I have added required tests, please review this PR.

**Comment by ViralBShah** [comment]
This looks good. Can be merged once CI is complete. Whoever merges it can improve the commit message.

**Comment by raghav9-97** [comment]
Does this message looks good enough?

**Comment by ViralBShah** [comment]
The comment was about the message in the commit itself (which you have to fix with `git rebase -i`). But like I said, don't worry about it, since I can fix while squash merging.

**Comment by raghav9-97** [comment]
Ok, I misunderstood the comment, Thanks for helping out @ViralBShah

**Comment by raghav9-97** [comment]
Is this PR now ready to be merged?

**Comment by ViralBShah** [comment]
@raghav9-97 Thanks for the PR. It seems you are relatively new to Julia (at least as a committer). So welcome!

**Comment by raghav9-97** [comment]
@ViralBShah Thanks for helping me out and guiding me throughout the process.

**Comment by KristofferC** [comment]
Already backported to 1.1.

**Comment by KristofferC** [comment]
Should have been squashed.

**Pull request merged**
