### PR TITLE
added parts to the builtins

### PR DESCRIPTION
**Pull request by generationzcode**
For issue number  #33666 . I'm a beginner at contributing to julia. But I guess I'm working on my first task...

### CODE REVIEW

**Comment by mbauman** [comment]
Hi @generationXcode, welcome!  This isn't going to do the trick here.  What we need are the addition of documentation blocks to `base/docs/basedocs.jl` like what I did here: 

https://github.com/JuliaLang/julia/pull/33344/files#diff-27a0578f1e9003d41562a9648191ce26

For example, one such addition could be something like:

```
"""
    @

A description of what an @ symbol does goes here — ideally with examples of how to use it.
"""
kw"@"
```

**Comment by generationXcode** [comment]
@mbauman - So I had to add docstrings to the program? ohhhhh.Ok thanks! do I have to make another pull request or are you doing it?

**Comment by mbauman** [comment]
Yes, that's exactly right.  A good starting point for the descriptions can be found here: https://github.com/JuliaLang/julia/blob/master/doc/src/base/punctuation.md

Go for it!

**Comment by fredrikekre** [comment]
> do I have to make another pull request

Easiest is if you just update this one!

**Comment by generationXcode** [comment]
done!

**Comment by ViralBShah** [comment]
@generationzcode Can you rebase this?

**Comment by mbauman** [comment]
I'm afraid a rebase isn't quite enough — we need this to be restructured into separate docstrings for each point like I suggested in https://github.com/JuliaLang/julia/pull/33733#issuecomment-548816435.

**Comment by ViralBShah** [comment]
Thanks. Closing this one then.

**Pull request closed without merging**
