### PR TITLE
deprecate dict comprehension syntax. fixes #16510

### LINKED ISSUE #16510: Deprecate dict comprehension construction in favor for Generator
As the new Generator syntax matches nicely with the construction of dictionaries. I propose using generators instead of using the comprehensions syntax to construct dictionaries as the generator syntax is closer to the syntax for manually initialization of the dictionaries. This should be deprecated:
```
julia> [i=>i*2 for i=1:2]
Dict{Int64,Int64} with 2 entries:
  2 => 4
  1 => 2
``` 
In favor for:
```
julia> Dict(i=>i*2 for i=1:2)
Dict{Int64,Int64} with 2 entries:
  2 => 4
  1 => 2
```
The deprecation will match the deprecation in:
```
julia> [1=>2, 2=>4]

WARNING: deprecated syntax "[a=>b, ...]" at REPL[53]:1.
Use "Dict(a=>b, ...)" instead.
Dict{Int64,Int64} with 2 entries:
  2 => 4
  1 => 2
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by tkelman** [comment]
There are several uses of this remaining that didn't trigger deprecation warnings but should have:
https://gist.github.com/93bc9000984ee4b603f3839c3ace0e50

Also devdocs/ast.rst needs an update (and sphinx is complaining that it's currently malformed)

**Comment by JeffBezanson** [comment]
That must be due to #10727, which I don't really agree with.

**Comment by tkelman** [comment]
Yeah, ref https://github.com/JuliaLang/julia/pull/10728#issuecomment-89679378, and it would be more useful if the various command-line flags were available as scoped in-language API's.

**Comment by tkelman** [comment]
Or people who want to build deprecated syntax into userimg could manually add the flag themselves, it seems like just honoring the command line flag would be enough there.

**Comment by JeffBezanson** [comment]
Yes I think we should revert that change. Never getting warnings for Base because somebody once found them annoying is the wrong tradeoff.

**Comment by StefanKarpinski** [comment]
I think the only reason I haven't been bitten by this is that I usually make changes first, make sure that nothing breaks and only *then* add deprecations. Of course, that's gotten me in trouble too.

**Comment by quinnj** [comment]
Is there compat support for this yet? I guess this will need an entry in the `@compat` macro to change the lowering?

**Pull request merged**
