### PR TITLE
Add complete documentation for `Base.countlines()`

### LINKED ISSUE #48494: Incomplete method documentation of Base.countlines()
[`Base.countlines()`](https://github.com/JuliaLang/julia/blob/e48a0c99bef949a84979c05dc33fd5578f684c1d/base/io.jl#L1336) can be called with an IO stream or a file name string. However, the [documentation](https://docs.julialang.org/en/v1/base/io-network/#Base.countlines) only talks about the former, potentially obscuring a very helpful feature.

As with [`Base.readlines()`](https://docs.julialang.org/en/v1/base/io-network/#Base.readlines) and similar functions, all methods of `countlines()` should be listed in the documentation.

### PR DESCRIPTION
**Pull request by vmpyr**
Fixes: #48494

I think this makes sense. It is also in line with the documentation for `Base.readlines()` and similar functions. Please let me know of possible improvements.

### CODE REVIEW

**Comment by barucden** [comment]
I am wondering whether the examples with the `eol` argument are that instructive. What if we used a space instead of `.` to indicate the effect more clearly?
```julia
julia> io = IOBuffer("JuliaLang is a GitHub organization.");

julia> countlines(io, eol = ' ')
5
```
(and similarly for your newly added example)

What do you think?

**Comment by vmpyr** [comment]
This is a good suggestion. However, I think it would be nice to better explain its usage in the description above the examples, since it would then explain both the filename's as well as the IOBuffer's usage.

> What if we used a space instead of `.` to indicate the `eol`'s effect more clearly?

We can still definitely do this btw.

**Review by x0samnan — APPROVED** [review]

**Comment by vmpyr** [comment]
Can this be merged now or are there things to change

**Comment by StefanKarpinski** [comment]
I think that since the file name and the example content both include a single `.` it's potentially confusing. Might be better to use a character that only occurs in the file text.

**Review by x0samnan — APPROVED** [review]

**Pull request merged**
