### PR TITLE
Track "permanently defined" status for bindings

### PR DESCRIPTION
**Pull request by topolarity**
This change regains some inference power that we lost with https://github.com/JuliaLang/julia/pull/53750.

It adds an `isdefined` bit to all bindings to track whether they were defined when their module was open - if so, we can be sure that they will be defined forever.

This does not implement support for the atomic global ops, since those are far less common - this is a "best effort" bit, so it's only an inference/optimization impact if we fail to set it (in any case, no worse than the status quo today)

### CODE REVIEW

**Comment by Keno** [comment]
Needs tests, but also will stop working after #54654.

**Comment by topolarity** [comment]
> also will stop working after https://github.com/JuliaLang/julia/pull/54654.

Only the `nothrow` piece right? The static `isdefined` checks will still work?

**Review by vtjnash — COMMENTED** [review]
It is not really acceptable to add cost to every global assignment call. We could put this into the staticdata serializer itself, but I think it remains to be shown that the loss of the `isdefined`/`UndefRefError` optimizations actually matters.

**Comment by vtjnash** [comment]
No longer relevant, due to https://github.com/JuliaLang/julia/pull/54654 which may allow all bindings to be redefined and none to be permanent anymore

**Pull request closed without merging**
