### PR TITLE
RFC: Add vararg comparison functions

### PR DESCRIPTION
**Pull request by iamed2**
~I couldn't get docstrings working so I'll wait to see if this might be accepted and then ask for help on that.~

This allows calls like:
```julia
all(map(==, parallel_arrays...))
```

Currently short-circuits and has no special optimized versions for small or large argument lengths.

### CODE REVIEW

**Comment by tkelman** [comment]
wouldn't a fold be better than splatting?

**Comment by iamed2** [comment]
Do you mean a loop? AFAIK there's no generic reduction operator that would work.

**Comment by tkelman** [comment]
wouldn't foldl do this?

**Comment by iamed2** [comment]
@tkelman What would you use for `op`?

What we want is `3 == 3 == 3` (which is true) but `foldl` would do `(3 == 3) == 3` which is false (`(true) == 3`)

**Comment by iamed2** [comment]
I believe Travis failures are unrelated and possibly transient.

**Comment by iamed2** [comment]
Bump?

**Comment by stevengj** [comment]
I'd prefer to see a looping version, since it seems to be 100x faster than splatting:
```jl
julia> fsplat(x, y) = x < y
fsplat (generic function with 1 method)

julia> fsplat(a, b, c, args...) = a < b && fsplat(b, c, args...)
fsplat (generic function with 2 methods)

julia> @btime fsplat(1,2,3,4,5,6);
  1.138 μs (6 allocations: 176 bytes)

julia> function floop(a, b, args...)
           v = a < b
           if v && length(args) > 0
               b < args[1] || return false
               @inbounds for i = 1:length(args)-1
                   args[i] < args[i+1] || return false
               end
           end
           return v
       end
floop (generic function with 1 method)

julia> @btime floop(1,2,3,4,5,6);
  12.134 ns (0 allocations: 0 bytes
```

**Comment by yuyichao** [comment]
Loop could be problematic if not all arguments have the same type.

**Comment by stevengj** [comment]
Okay, a generated function then 😝

**Comment by iamed2** [comment]
Bug in the pushed code: signature needs to be (a, b, c, args...) to avoid defining comparison methods for types which don't have them already.

**Pull request closed without merging**
