### PR TITLE
Printing of BigFloats (fixes #11276)

### LINKED ISSUE #11276: Printing of BigFloat's and Complex{BigFloat}'s
Currently the printing of `Complex{BigFloat}`'s is like this
```julia
julia> big(1.) + 2im
1e+00 with 256 bits of precision + 2e+00 with 256 bits of precisionim
```
which is bad.

I have some proposals to improve this.

(1) Make `Complex{BigFloat}` print like
```julia
julia> big(1.) + 2im
1e+00 with 256 bits of precision + 2e+00im with 256 bits of precision
```
(2) Make `BigFloat`'s print the precision info inside parenthesis as
```julia
julia> big(1.)
1e+00 (with 256 bits of precision)
```

and then display `Complex{BigFloat}` as one of the following

(a)
```julia
julia> big(1.) + 2im
1e+00 (with 256 bits of precision) + 2e+00 (with 256 bits of precision) * im
```
(b)
```julia
julia> big(1.) + 2im
1e+00 (with 256 bits of precision) + 2e+00im (with 256 bits of precision)
```

Personally, I find better options (2) and (b). If there is an agreement I can submit a PR based on that decision

### PR DESCRIPTION
**Pull request by p-zubieta**
Removes the precision info when printing a `BigFloat`, this leads to cleaner printed `Complex{BigFloat}`s. So before we had

``` julia
julia> big"1.2" + big"2.1" * im
1.200000000000000000000000000000000000000000000000000000000000000000000000000007e+00 with 256 bits of precision + 2.099999999999999999999999999999999999999999999999999999999999999999999999999986e+00 with 256 bits of precisionim
```

while after this change it would be

``` julia
julia> big"1.2" + big"2.1" * im
1.200000000000000000000000000000000000000000000000000000000000000000000000000007e+00 + 2.099999999999999999999999999999999999999999999999999999999999999999999999999986e+00im
```

This also removes one extra allocation that was present when returning the `bytestring`.

Fixes #11276

### CODE REVIEW

**Comment by pabloferz** [comment]
I forgot to mention that this prints at least 78 decimal places or enough digits so that it can be read back exactly.

**Comment by dpsanders** [comment]
Perhaps the default should be to print fewer digits (and avoid the `e+00` if possible), and `showall` can be used to print back enough digits for it to be read exactly. However, in this case the number of digits should depend on the precision, and not be fixed to work only for the default precision.

Do you know what MPFR returns here? Does it automatically give enough digits to be read back exactly?

**Comment by dpsanders** [comment]
There is an `mpfr_get_str` function that apparently does this:
http://www.mpfr.org/mpfr-current/mpfr.html#Conversion-Functions

**Comment by pabloferz** [comment]
The formatted output function from MPFR (the ones in the code among others) give you the number of digits depending on the format template specified (similar to C's `printf`, except the MPFR formats are an extension of the C ones). In the code there is a "%.Re" for example that does that but it returns the output in scientific notation. I used that notation because it was the one being used already. I wouldn't have problem changing it, as long as there is enough consensus.

**Comment by pabloferz** [comment]
On the issue of the `e+00`, I haven't found a solution using MPFR, the only thing I have thought to avoid it is to check whether the the BigFloat is between 1 and 10 and limit the output in that case so the `e+00`does not get returned.

**Comment by pabloferz** [comment]
Ping @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Seems reasonable. Thanks for the change.

**Comment by pabloferz** [comment]
You're welcome!

**Pull request merged**
