### PR TITLE
Better indexing for coupled iteration of array with AbstractArray{Bool}

### PR DESCRIPTION
**Pull request by p-zubieta**
This should help with some of the problems with `add1` and `add1_logical` in #16128 until something like #15356 gets sorted out.

CC @timholy @JeffBezanson

### CODE REVIEW

**Comment by timholy** [comment]
This addresses my concerns voiced in https://github.com/JuliaLang/julia/issues/16128#issuecomment-225179379, so :+1: We should wait for the tests to run, but I'm in favor of merging this if it fixes the performance. Nice work, @pabloferz!

**Comment by pabloferz** [comment]
Turns out that the first thing I tried helps, but is not enough. So, I wrote specialized versions that help even more. I understand this is not ideal (and I can remove the specialized versions) but wanted to let you now anyway.

**Comment by nalimilan** [comment]
(FWIW, it would have been nice to use a more detailed commit message, instead of keeping the explanations on GitHub.)

**Comment by pabloferz** [comment]
@nalimilan Sorry. I'll keep this in mind.

Tests passes, but now I am a bit hesitant. Should I only propose the first commit and see if using -O3 takes care of the rest? Or the latest changes are OK?

**Comment by timholy** [comment]
Seems fine to me. Let's check the performance: @nanosoldier `runbenchmarks("array", vs=":master")`

**Comment by tkelman** [comment]
Yeah the code near-duplication is a bit unfortunate, but hopefully we can improve the compiler for the general case and make it unnecessary again at some point in the future.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16865#issuecomment-225262192) has completed, but something went wrong when trying to upload the result data. cc @jrevels

**Comment by jrevels** [comment]
Hmm. I think @nanosoldier ran into a bug trying to get the permalink to the report, but all the data did in fact upload correctly. Permalink to the report is [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/cb755d5250cfa065b51bbe721151bf877779735c/f1e4b30_vs_bbf0030/report.md).

**Comment by timholy** [comment]
Looks like I ran the wrong ones. @nanosoldier `runbenchmarks("problem", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16865#issuecomment-225304673) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a981e6927e7aea46198b621757c70b871f2000fe/8829433_vs_466da65/report.md). cc @jrevels

**Comment by pabloferz** [comment]
The tests are <a href="https://github.com/JuliaLang/julia/blob/6b5a05eb1a029aef93f77b60bb1d745c7d6e1d8d/test/perf/kernel/indexing.jl">here</a> but I don't see anything like it over BaseBenchmarks.jl

**Comment by timholy** [comment]
Arg, yes, I found some of those `perf/kernel` tests and didn't look for the rest.

Let's just merge. Thanks for this!

**Comment by pabloferz** [comment]
No problem!

**Pull request merged**
