### PR TITLE
`release-1.10`: set `VERSION` to `1.10.0-alpha1`

### PR DESCRIPTION
**Pull request by DilumAluthge**
Replaces #50394 
Closes #50394

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Okay, that worked. I guess Buildkite doesn't want to run on #50394 because #50394 was created before the [`julia-release-1.10` pipeline](https://buildkite.com/julialang/julia-release-1-dot-10) was created.

**Comment by Seelengrab** [comment]
Just so you're aware, there's some discussion in https://github.com/JuliaLang/julia/pull/49805 about a potential issue with a previous PR feature-wise.

**Comment by DilumAluthge** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.9", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by DilumAluthge** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.9")`

**Comment by KristofferC** [comment]
This is just an alpha so it basically provides no guarantees.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50420#issuecomment-1621654162) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/2d2021d_vs_e4ee485/report.md).

**Comment by KristofferC** [comment]
Dilum Aluthge, what was the reason for rerunning nanosoldier? It's already running on the previous PR.

**Comment by DilumAluthge** [comment]
Ah, I just assumed that when the old PR was closed, it would auto-cancel the Nanosoldier job. (Similar to how when you delete a branch, Buildkite auto-cancels the CI run on that branch.)

**Pull request merged**
