### PR TITLE
deprecate Array(shape...)-like constructors to Array(uninitialized, shape...)

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request deprecates uninitialized-`Array` constructors of the form `Array[{T,N}](shape...)` in favor of `Array[{T,N}](uninitialized, shape...)` equivalents. For background, please see #24595. Best!

(This pull request should not pass CI till the remaining `Array(shape...)` call replacement pull requests merge, hence the WIP.)

### CODE REVIEW

**Comment by fredrikekre** [comment]
```
error during bootstrap:
LoadError(at "coreimg.jl" line 3: LoadError(at "bitarray.jl" line 1053: MethodError(f=typeof(Core.Inference.convert)(), args=(Array{UInt64, 1}, 0), world=0x00000000000008fa)))
rec_backtrace at /home/travis/build/JuliaLang/julia/src/stackwalk.c:94
record_backtrace at /home/travis/build/JuliaLang/julia/src/task.c:246
jl_throw at /home/travis/build/JuliaLang/julia/src/task.c:577
jl_method_error_bare at /home/travis/build/JuliaLang/julia/src/gf.c:1507
jl_method_error at /home/travis/build/JuliaLang/julia/src/gf.c:1525
jl_lookup_generic_ at /home/travis/build/JuliaLang/julia/src/gf.c:1987 [inlined]
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:2007
```

**Comment by Sacha0** [comment]
Comprehension lowering required updating, and a `similar(arraytype, shape...)` method as well. Those  updates fix bootstrap locally. What say you now, CI?

**Comment by Sacha0** [comment]
Thoughts on the `similar(funcortype, inds...) = funcortype(inds...)` -> `... = funcortype(uninitialized, inds...)` change, @timholy? Thanks!

**Comment by Sacha0** [comment]
Caught another necessary lowering change, fixed a few additional `Array(shape...)`-like calls that slipped by previously, switched to a more conservative `similar(typeorfunc, shape)` change, and polished the deprecations a bit. What say you now, CI?

Pending CI this pull request should now be in shape. (Though merging #24785 will introduce a minor conflict here.) So absent objections or requests for time, I plan to merge these changes tomorrow. Best!

**Comment by Sacha0** [comment]
Thanks all! :)

**Pull request merged**
