### PR TITLE
Internalize LLVM C API extensions from LLVM.jl

### PR DESCRIPTION
**Pull request by maleadt**
After having let users struggle with source builds of Julia in order to run LLVM.jl -> CUDAnative.jl -> CuArrays.jl, I think the easiest short-term solution is to internalize the LLVM C API extensions and build them together with Julia (these were hard to build because of a missing `llvm-config`, C++ ABI compatibility issues, etc). Because even with BinDeps2, it doesn't seem like building against the Julia build tree is going to be easy to support, and it also doesn't fix the problem for people who run `make install` (`llvm-config` isn't installed) or use an external package manager.

Putting these API extensions in the Julia repo restricts our ability to iterate freely on LLVM.jl, but I guess that's the price to pay. Besides, the set of extensions has been relatively stable, and future extensions might be considered backportable in order to get them out there more quickly.

Most of these extensions should find their way upstream at some point, but I haven't got the time|motivation for that (esp. with us sticking to 3.9 which would then require additional patches to be backported etc).
Rust has a similar set of extensions: https://github.com/rust-lang/rust/tree/master/src/rustllvm

Ref https://github.com/maleadt/LLVM.jl/pull/68

TODO:
- [x] format the code
- [x] make sure it builds with other supported LLVM versions: tested with 3.9, 4.0, 5.0

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
As long as we don't consider this API stable (it shouldn't be), then this can certainly go into 1.0 and be iterated upon in minor releases (1.1, 1.2, etc.).

**Comment by Keno** [comment]
I'm ok with this. I do think we should find a BinDeps2-based solution for LLVM.jl and Cxx that doesn't require this, but there's no harm in including these.

**Comment by maleadt** [comment]
I'll be happy to move back to a BinDeps2-based solution once that's possible, although it's not clear to me how that'll deal with all possible build scenarios (notably, `make install` on custom trees, distro-packages). This solution at-least covers all those cases, as long as LLVM is build as a shared library.

I'll have another pass over it, document the API as unstable, and squash&merge this later today.

**Comment by vchuravy** [comment]
Should we backport this to 0.6.2? cc: @araslan

**Comment by maleadt** [comment]
Is there a 0.6.2 planned?

**Comment by vchuravy** [comment]
Yes. Alex has been hard at work.

**Comment by maleadt** [comment]
Of course, I'm confused and was thinking about the _next_ point release.
About 0.6.2, I didn't add it to the backports because it is a new feature and not a fix, albeit a very isolated one which shouldn't impact any user code except for LLVM.jl. I'll leave the decision to @ararslan.

**Comment by ararslan** [comment]
It's too late to get it into 0.6.2 and we're close enough to feature freeze for 0.7 that I'm not sure it will even be worth doing a 0.6.3. Even if we do though, per our usual backport policy as I understand it, this can't be backported since it's technically a feature, however isolated, and not a fix.

**Comment by vchuravy** [comment]
Fair enough.

**Pull request merged**
