### PR TITLE
[release-0.6] fix #22164 and #22002, method sorting problems

### LINKED ISSUE #22164: ForwardDiff asserts while precompiling
```
julia> using ForwardDiff

julia-debug: /home/keno/julia/src/gf.c:1122: check_ambiguous_visitor: Assertion `!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)' failed.

signal (6): Aborted
while loading /home/keno/.julia/v0.7/ForwardDiff/src/dual.jl, in expression starting on line 195
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fbe6dc73bb6)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
check_ambiguous_visitor at /home/keno/julia/src/gf.c:1122
jl_typemap_intersection_node_visitor at /home/keno/julia/src/typemap.c:488
jl_typemap_intersection_visitor at /home/keno/julia/src/typemap.c:545
jl_typemap_intersection_visitor at /home/keno/julia/src/typemap.c:536
check_ambiguous_matches at /home/keno/julia/src/gf.c:1209
jl_method_table_insert at /home/keno/julia/src/gf.c:1395
jl_method_def at /home/keno/julia/src/method.c:737
eval at /home/keno/julia/src/interpreter.c:303
eval_body at /home/keno/julia/src/interpreter.c:608
jl_interpret_toplevel_thunk at /home/keno/julia/src/interpreter.c:692
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:590
jl_parse_eval_all at /home/keno/julia/src/ast.c:907
jl_load at /home/keno/julia/src/toplevel.c:614
jl_load_ at /home/keno/julia/src/toplevel.c:621
include_from_node1 at ./loading.jl:551
unknown function (ip: 0x7fbe34c7069d)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
include at ./sysimg.jl:14
unknown function (ip: 0x7fbe67acda99)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
do_call at /home/keno/julia/src/interpreter.c:75
eval at /home/keno/julia/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/keno/julia/src/interpreter.c:34
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:575
jl_eval_module_expr at /home/keno/julia/src/toplevel.c:203
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:478
jl_parse_eval_all at /home/keno/julia/src/ast.c:907
jl_load at /home/keno/julia/src/toplevel.c:614
jl_load_ at /home/keno/julia/src/toplevel.c:621
include_from_node1 at ./loading.jl:551
unknown function (ip: 0x7fbe67d287e9)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
include at ./sysimg.jl:14
unknown function (ip: 0x7fbe67acda99)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
do_call at /home/keno/julia/src/interpreter.c:75
eval at /home/keno/julia/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/keno/julia/src/interpreter.c:34
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:575
jl_toplevel_eval at /home/keno/julia/src/toplevel.c:598
jl_toplevel_eval_in at /home/keno/julia/src/builtins.c:496
anonymous at ./<missing>:2
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_toplevel_eval_flex at /home/keno/julia/src/toplevel.c:587
jl_toplevel_eval at /home/keno/julia/src/toplevel.c:598
jl_toplevel_eval_in at /home/keno/julia/src/builtins.c:496
eval at ./boot.jl:236
unknown function (ip: 0x7fbe67cbec2d)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
process_options at ./client.jl:288
_start at ./client.jl:373
unknown function (ip: 0x7fbe67d3bd31)
jl_call_fptr_internal at /home/keno/julia/src/julia_internal.h:353
jl_call_method_internal at /home/keno/julia/src/julia_internal.h:372
jl_apply_generic at /home/keno/julia/src/gf.c:1923
jl_apply at /home/keno/julia/ui/../src/julia.h:1424
true_main at /home/keno/julia/ui/repl.c:127
main at /home/keno/julia/ui/repl.c:264
```
Happens at with ForwardDiff `0.4.2` as well as with `0.5.0`.
```
(rr) p jl_(sig)
Tuple{typeof(Base.convert), Type{ForwardDiff.Dual{N, T} where T<:Real where N}, ForwardDiff.Dual{N, T} where T<:Real where N}
$1 = void
(rr) p jl_(type)
Tuple{typeof(Base.convert), Type{D}, D} where D<:(ForwardDiff.Dual{N, T} where T<:Real where N)
$2 = void
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a minimal version of #22162 that fixes these two bugs, which seem fairly important. Hence I've opened this against release-0.6.

### CODE REVIEW

**Comment by tkelman** [comment]
changed the base branch to https://github.com/JuliaLang/julia/pull/22199 so I don't have to rebase that

**Comment by tkelman** [comment]
if this is an exact cherry pick of https://github.com/JuliaLang/julia/pull/22162/commits/8b83fa7716dba95628ee0592b5a29c1b98992205 and partial backport of #22162, would be good to cross reference that fact in the commit message

**Comment by JeffBezanson** [comment]
It's not a cherry pick, but I guess it qualifies as a partial backport.

**Comment by tkelman** [comment]
patch looks the same to me, other than the tests going in a different file?

**Pull request merged**
