### PR TITLE
benchmark something

### PR DESCRIPTION
**Pull request by KristofferC**
just because I am curious

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

### CODE REVIEW

**Comment by vchuravy** [comment]
BTW you don't need to open a PR to trigger nanosoldier, you can do it from the comments to a commit.
That way you don't trigger CI a swell.

**Comment by KristofferC** [comment]
Didn't know I could comment on commits on non PR branches. I'll do that in the future.

**Comment by JeffBezanson** [comment]
Even more interestingly, this seems to cause test failures.

**Comment by KristofferC** [comment]
Wohoo, didn't waste CI after all.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27054) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c3717cff740c6aebc2b61ed46c740edd72aeaee8/f1f87e9_vs_b81b118/report.md). cc @ararslan

**Pull request closed without merging**
