### PR TITLE
Add docs about the Dates.DateFormat type for more efficient Date/DateTime parsing.

### PR DESCRIPTION
**Pull request by quinnj**
[ci skip]

### CODE REVIEW

**Comment by quinnj** [comment]
Ah, so how does [ci skip] work on subsequent commits? Do I need to include it in each commit?

**Comment by tkelman** [comment]
You need to include it in the commit message of the last commit you push. If you push one commit at a time, then yes it'll need to be in each one. Or you can rebase locally and force push, then you could remove it from the messages of the earlier commits and only have it in the last one. But I don't think anyone cares enough to go to that much trouble.

Though now that we have some whitespace checks running on Travis, it might be better to just do `[av skip]` for doc stuff, so Travis will check it but it won't make the AppVeyor queue any longer.

**Comment by quinnj** [comment]
Thanks @tkelman. I was a little out of touch when a lot of the CI dev went on, so it's helpful to get back up to speed on how that works. Thanks for all the work on AppVeyor, among other things.

**Comment by ivarne** [comment]
How big are these `Dates.DateFormat` objects. Does it make sense to cache the last (few?) objects used so that parsing is just a (few?) simple string comparisons in the common case of repeated usage of the same format?

Python does this for regex.

**Comment by nalimilan** [comment]
Or maybe use a non-standard string literal for this, so that in a loop the same object is used without the user doing anything special: `[Date(d, df"y-m-d") for d in dates]`.

**Comment by quinnj** [comment]
These are great ideas. I'm actually unfamiliar with teh internals of how the `r""` regex string literal does it's magic. Would we need a global cache for `DateFormat` objects?

**Comment by nalimilan** [comment]
They are relatively well documented in the manual. Actually that's just a special syntax for a macro call: http://docs.julialang.org/en/latest/manual/metaprogramming/#non-standard-abstractstring-literals

This solution would replace a global cache if you can do most of the work at compile time, which I guess is the case.

**Comment by quinnj** [comment]
Sorry, I'm familiar with string literal macros, I'm just unfamiliar with how the performance gain works. I.e. turning this
```julia
Date("2015-01-01", df"yyyy-mm-dd")
```
into this
```julia
Date("2015-01-01", DateFormat("yyyy-mm-dd") )
```
Particularly, if someone were to be calling the first form within a loop, how does the macro create the DateFormat object only once? it seems like you'd have to use a global cache of some sort.

**Comment by StefanKarpinski** [comment]
The macro expansion of `df"yyyy-mm-dd"` into a `DateFormat` object happens at compile time, so when the code is parsed, not when it runs. The AST ends up with a DateFormat object in it.

**Comment by ivarne** [comment]
The string macro thing is just pretty syntax for giving a string to a macro. `df"yyyy-mm-dd"` is parsed as `@df_str("yyyy-mm-dd")`, so the macro can do anything normal macros can do.

```julia
macro df_str(format)
     return DateFormat(format)
end
 # or
macro df_str(format)
     return :(DateFormat($format))
end
```
Both gives the same answer,  but the first one is more efficient when used in a loop, as the object gets stored in the AST, instead of being recomputed at every iteration.

**Pull request merged**
