### PR TITLE
Add ability to add output prefixes to the REPL output and use that to implement an IPython mode

### LINKED ISSUE #46310: Would like numbered REPL prompts
Sometimes it would be convenient if the REPL prompts (`julia>`) were numbered, starting from 1 when the session begins.

For example, when I receive a large output in the Julia REPL, I might need to scroll back to find the previous prompt. Numbered prompts would help here.

### PR DESCRIPTION
**Pull request by KristofferC**
With

```jl
atreplinit() do repl
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.ipython_mode(repl)
end
```

in the startup.jl file:

image

Only the first commit is needed for a package to implement the IPython mode (except prompt pasting which will not work from a package and currently requires a source change in REPL to modify the searched prefix).

Fixes https://github.com/JuliaLang/julia/issues/46310.

cc @eschnett

### CODE REVIEW

**Comment by KristofferC** [comment]
Seems pretty harmless and fun so I'll merge.

**Comment by hyrodium** [comment]
Is it correct to call this feature "ipython"? I'm understanding the origin of the format like `In[1]` and `Out[1]` is Mathematica.

* The first version of ipython was released in 2001 (https://en.wikipedia.org/wiki/IPython).
* [The `Out` function in Mathematica](https://reference.wolfram.com/language/ref/Out.html) was introduced in 1998.

**Comment by singularitti** [comment]
Sorry, I put the following lines in my `startup.jl` but I do not see `Out[1]` was highlighted:

```julia
using REPL
atreplinit() do repl
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.ipython_mode!(repl)
end
```

image

Am I using it wrongly?

**Comment by svretina** [comment]
since the name changed, if anyone comes looking how to enable the numbered promt in startup, here is the snippet with the updated name:
```
atreplinit() do repl
    try
        @eval using REPL
    catch e
        @warn "error while imporing REPL" e
    end
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.numbered_prompt!(repl)
end
```

**Pull request merged**
