### PR TITLE
Include Base.Filesystem.contractuser in documentation.

### PR DESCRIPTION
**Pull request by EQt**

### CODE REVIEW

**Comment by fredrikekre** [comment]
This function is not exported.

**Comment by EQt** [comment]
True. Nevertheless it is a useful function and can be accessed as `Base.Filesystem.contractuser`. So I think it should be included in the documentation of the module. This way it can be searched, also via Google.

If this function is part of the html documentation, one could link from `expanduser` to `contractuser` and vice versa.

**Comment by EQt** [comment]
Please let me know if documenting `contractuser` does not make sense. Then I can withdraw this pull request.

**Comment by fredrikekre** [comment]
Sorry for being unclear. For Julia base the public API is usually considered to be what is i) exported and ii) documented. This function is currently not exported, so thats why I don't think it should be included in the documentation, it is only meant for internal use. Of course, if it is useful we can consider exporting it if people find it useful.

**Comment by EQt** [comment]
If I understand it correctly, `contractuser` has not been changed since July 2018. It has got unit tests. So it could be considered "stable" in my opinion.

The main use is to shorten file names in the stacktrace and `ConsoleLogger` on Unix. 

I would like it to be at least part of the `Filesystem` documentation, at least.

**Comment by KristofferC** [comment]
Not sure why this got closed, I was trying to add a commit that also exported `contractuser`.

**Pull request closed without merging**
