### PR TITLE
Change default output of `[@]code_native` to intel syntax

### PR DESCRIPTION
**Pull request by Seelengrab**
Tests ran through on my local machine, here's to hoping that this isn't too controversial :eyes: My personal reasoning for preferring intel syntax is that it's much, MUCH easier to read when it comes to offsets in hot loops (where it's most useful to look at the assembly), as well as being more consistent with our usual `var = val` syntax.

If this turns out to be too controversial, I hope to pivot this to SOMETHING that makes this more easily configurable than a per-use flag, which seems to be the worst of all worlds (if you don't always want the default, that is).

### CODE REVIEW

**Comment by quinnj** [comment]
It'd be nice to maybe show a side by side of old vs. new via screenshots? Or code blocks?

**Comment by Seelengrab** [comment]
Well, the differences are numerous, but I don't know of a list comparing each explicitly :sweat_smile: Here's an example of a small inner loop that I think is easier to read:
image

On the left is the existing AT&T syntax, on the right is the (also existing, but not default) intel syntax. While AT&T e.g. has `src + src => target`, intel does `target <= src + src`. Where AT&T has `-192(%rsi,%rdi,8)` for describing an address, intel has `zmmword ptr [rsi + 8*rdi - 192]` for describing an address. They both show & do exactly the same thing, I just think the latter is much, MUCH more readable for judging the base to calculate off of, the stride, as well as the ultimate offset.

Similarly, looking up an instruction is, to me at least, simpler with intel syntax, because it purely has the instruction in the name, instead of adding the size of the argument to the instruction itself. `mov`/`add`/`cmp` works the same, no matter if it's a word, doubleword, quadword or what have you.

**Comment by Seelengrab** [comment]
Not sure why CI doesn't even build, seems unrelated?

**Comment by StefanKarpinski** [comment]
I'm good with this, but I would also love a way to default debuginfo to `:none`.

**Comment by vtjnash** [comment]
The inlining depth corresponds exactly to the indentation depth (aside from old versions of llvm where it seemed to sometimes randomly shuffled the order when generating dwarf–but I have not seen that in several years)

**Comment by Seelengrab** [comment]
With the changed default, it looks like this:

image

I wonder if it would be useful to distinguish that first part in `code_llvm` about thread synchronization with its own little comment marker. If the `fence syncscope` there is always the last one to print of that particular section, placing a comment after it should be doable.

**Comment by giordano** [comment]
Based on a comment on Slack I thought that #47393 would get rid of the safepoint in the output of `code_llvm`/`code_native`, but that doesn't seem to be the case.  That adds quite a lot of noise, especially in short functions.

**Comment by Seelengrab** [comment]
Well last I heard was that it was always emitted, but removed later on by the optimizer anyway due to the loads being dead. Would be useful to not have it generated in the first place if it's not required (mainly thinking of trouble I had with the IR and arduino..), but not a problem per se.

**Comment by gbaraldi** [comment]
I will say, I like having the debug_info in the function, it does help guide the eye for larger functions.

**Comment by vchuravy** [comment]
> Well last I heard was that it was always emitted, but removed later on by the optimizer anyway due to the loads being dead. Would be useful to not have it generated in the first place if it's not required (mainly thinking of trouble I had with the IR and arduino..), but not a problem per se.

You are thinking of the GC stack frame. There is a codegen option for the safepoint emission, but be default the prologue of every function will have it.

**Comment by Seelengrab** [comment]
Well, just yesterday I ran into an issue where printing with debuginfo filled my terminalbuffer completely, due to heavy inlining and compression of 5-10 function calls into a single instruction (which could have been worse, granted). So for heavily unrolled functions it's sometimes even more of a hindrance :/ Changing that to only print some layers (without re-parsing the whole output) seems tricky, since there's 2-3 codepaths we could end up in, some of which just defer to whatever output LLVM produces.

**Comment by vchuravy** [comment]
I think we are digressing from the PR. I am in favor of changing to Intel syntax, readability of it is much improved, the only downside is that a lot of other tools (GDB comes to mind) default to ATT. 

Having something like #41295 would make these discussions easier since there are reasonable arguments on both sides and it is indeed a personal preference.

**Comment by Seelengrab** [comment]
I don't mind removing the `debuginfo` default again if it gets the PR merged :shrug: Happy to take it to triage too, if necessary.

**Comment by StefanKarpinski** [comment]
Yes, please change the default to `debuginfo=:none`!

**Comment by giordano** [comment]
If that's more controversial maybe it can done in a separate PR?

**Comment by StefanKarpinski** [comment]
(Just do it)

**Comment by Seelengrab** [comment]
Ok, so since `debuginfo` is a lot more controversial, I'll remove it from this PR again, just so this doesn't die the slow death of abandoned PRs :) I still hope we can get the preferences toml thing at some point, since it would make PRs like this pretty much moot.

**Comment by Seelengrab** [comment]
This PR is pretty much done from my POV, so should be mergeable.

**Pull request merged**
