### PR TITLE
Update command line options

### PR DESCRIPTION
**Pull request by gitboy16**
Hi,
Sorry @oscardssmith , I think I might have closed the previous pull request by mistake.
I wanted to rebase the PR.
Original PR  #53759.
I have made the changes to align command line option and description.
Thank you

### CODE REVIEW

**Comment by oscardssmith** [comment]
for future reference, you can always just reopen a PR if you close it. That said, this lgtm.

**Comment by gitboy16** [comment]
Ok thank you. I'll try to familiarize myself with github.
I am not able to choose a reviewer or add a label for this PR.
Is it normal?

Also I was wondering, if someone would be able to look at my other PR which aims at fixing C compiler warnings on Windows?
Not sure what the process to get a review on a PR is?
Thank you.

**Comment by gitboy16** [comment]
Bump
Please let me know if anything else is needed.
I think it is a straightforward PR or am I missing something?
Thank you

**Comment by gitboy16** [comment]
Thank you @oscardssmith

**Comment by oscardssmith** [comment]
no problem. Thanks for the contribution!

**Pull request merged**
