### PR TITLE
Added documentation for the Markdown Macro

### PR DESCRIPTION
**Pull request by mokshablr**
Added documentation for the `md_str()` macro which is used by `md""`.
Mentioned in #51168.

### CODE REVIEW

**Comment by mokshablr** [comment]
I would love to help fixing the failed tests with some help. I'm still very new to contributing to projects so I don't quite understand why these tests are failing.

**Comment by mitiemann** [comment]
> I would love to help fixing the failed tests with some help. I'm still very new to contributing to projects so I don't quite understand why these tests are failing.

The build system fails as some formatting tests are not passing. I'm guessing there are some undesired blank lines? What output does `make check-whitespace` generate?

However, is there a particular reason why you've wanted to create your own PR instead of contributing to #52606 ?

**Comment by mokshablr** [comment]
> The build system fails as some formatting tests are not passing. I'm guessing there are some undesired blank lines? What output does `make check-whitespace` generate?

```
Whitespace check found 1 issues:
stdlib/Markdown/docs/src/index.md:409 -- no trailing newline
make: *** [check-whitespace] Error 1
 ```
> However, is there a particular reason why you've wanted to create your own PR instead of contributing to #52606 ?

When I started working on this issue there was no PR relating to this. Looks like it was made a few minutes before I made mine.

**Comment by mitiemann** [comment]
> ```
> Whitespace check found 1 issues:
> stdlib/Markdown/docs/src/index.md:409 -- no trailing newline
> make: *** [check-whitespace] Error 1
>  ```

This means that you need to add one newline at the end of the file.

> > However, is there a particular reason why you've wanted to create your own PR instead of contributing to #52606 ?
> 
> When I started working on this issue there was no PR relating to this. Looks like it was made a few minutes before I made mine.
> 

Funny coincidence :-) So, which of the two PRs should we complete? I'd personally would like to keep the added docstring for the macro in the source file, but I don't have strong opinions how the `docs/index.md` should look like.

**Comment by mokshablr** [comment]
> This means that you need to add one newline at the end of the file.
I removed the newline since I had got this error when it existed. Not quite sure what it expects from me.
```
Whitespace check found 1 issues:
stdlib/Markdown/docs/src/index.md:410 -- trailing blank lines
make: *** [check-whitespace] Error 1
```

> Funny coincidence :-) So, which of the two PRs should we complete? I'd personally would like to keep the added docstring for the macro in the source file, but I don't have strong opinions how the `docs/index.md` should look like.

We could have 2 seperate PRs maybe? Yours for the docstring and mine for the docs/index.md? Again, not sure if this is how it works here since I'm new to contributing.

**Comment by mitiemann** [comment]
It seems  you've gone from "no newline at end of file" to "too many newlines at end of file". The enforced style is "the last line with content should have another newline character, but then, there should be no more empty lines". Hope this helps.

As for the communal aspect: this is also my very first contribution to Julia, so I'm also unaware of these guidelines. I guess we'll just have to wait what the moderators say. However, if you want to, I could give you write access to my fork (or vice versa) and we could converge in one PR. Maybe that would make it easier for the mods as well?

**Pull request merged**
