### PR TITLE
Added test for position

### PR DESCRIPTION
**Pull request by ShriprajwalK**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Congrats on your first PR!

**Comment by logankilpatrick** [comment]
Since you made the changes on the same branch of your fork, this PR also includes the changes you suggested in #34736

**Comment by ShriprajwalK** [comment]
Thanks! 
Should I make another commit with the code for #34746 and the others removed?

**Comment by logankilpatrick** [comment]
I would add a commit here that removes the tests you already added in the other PR. So this PR should just be for the position tests.

**Comment by ShriprajwalK** [comment]
Is it alright now?

**Pull request merged**
