### PR TITLE
gf: accelerate adding backedges back to old performance

### PR DESCRIPTION
**Pull request by vtjnash**
Since it does not compute and branch on typeof, in my measurements, this implementation is about 10x faster!

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by timholy** [comment]
Did this regress in #46010? If so, maybe I should think about adding a benchmark. It doesn't seem easy, though, because it's not a step that's easy to isolate.

**Comment by vtjnash** [comment]
As you can see in the report, it actually had significantly regressed a benchmark (many_local_vars, née quadratic), but we hadn't done anything about it yet https://github.com/JuliaLang/julia/commit/dd375e199b6f17d5a14bbf1339d8a74cf5a3bb62#commitcomment-83236324

**Comment by timholy** [comment]
Ah, that does ring a bell. Thanks for explaining, and especially for fixing it!

**Comment by aviatesk** [comment]
Nice improvements! Do you think it would be worthwhile to try implementing a similar optimization at the Julia level? Specifically, the inlining code often adds duplicated backedges, but we could use IdSet there to prevent the duplication.

**Pull request merged**
