### PR TITLE
bump SuiteSparse.jl version

### PR DESCRIPTION
**Pull request by KristofferC**
This includes the recent work by @Gnimuc (https://github.com/JuliaLang/SuiteSparse.jl/pull/2, https://github.com/JuliaLang/SuiteSparse.jl/pull/3). Since this stdlib has heavy couplings to e.g. SparseArrays it is possible some more things have to be fixed here before this can be merged.

### CODE REVIEW

**Comment by KristofferC** [comment]
Win64 build error tracked at https://github.com/JuliaLang/SuiteSparse.jl/issues/6.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40844#issuecomment-842942864) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/0883b82_vs_b054be5/report.md). cc @maleadt

**Comment by KristofferC** [comment]
Hm,

```
      From worker 6:	julia: /buildworker/worker/package_linux64/build/src/gf.c:578: jl_compilation_sig: Assertion `jl_is_tuple_type(tt)' failed.
      From worker 6:	
      From worker 6:	signal (6): Aborted
      From worker 6:	in expression starting at /buildworker/worker/tester_linux64/build/share/julia/test/ambiguous.jl:155
      From worker 6:	unknown function (ip: 0x70000002)
      From worker 6:	unknown function (ip: 0x7fb231c5550b)
      From worker 6:	traced_raw_syscall at /workspace/srcdir/rr/src/preload/syscallbuf.c:278
      From worker 6:	sys_fcntl at /workspace/srcdir/rr/src/preload/syscallbuf.c:1508 [inlined]
      From worker 6:	syscall_hook_internal at /workspace/srcdir/rr/src/preload/syscallbuf.c:3234 [inlined]
      From worker 6:	syscall_hook at /workspace/srcdir/rr/src/preload/syscallbuf.c:3394
      From worker 6:	unknown function (ip: 0x7fb231c5055f)
      From worker 6:	unknown function (ip: 0x7fb231c505be)
      From worker 6:	unknown function (ip: 0x7fb231c505da)
      From worker 6:	gsignal at /lib64/libc.so.6 (unknown line)
      From worker 6:	abort at /lib64/libc.so.6 (unknown line)
      From worker 6:	__assert_fail_base at /lib64/libc.so.6 (unknown line)
      From worker 6:	__assert_fail at /lib64/libc.so.6 (unknown line)
      From worker 6:	jl_compilation_sig at /buildworker/worker/package_linux64/build/src/gf.c:578
      From worker 6:	jl_compilation_sig at /buildworker/worker/package_linux64/build/src/gf.c:1119 [inlined]
      From worker 6:	cache_method at /buildworker/worker/package_linux64/build/src/gf.c:1025
      From worker 6:	ml_matches at /buildworker/worker/package_linux64/build/src/gf.c:3125
      From worker 6:	jl_matching_methods at /buildworker/worker/package_linux64/build/src/gf.c:1891
      From worker 6:	_methods_by_ftype at ./reflection.jl:901 [inlined]
      From worker 6:	examine at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1597
      From worker 6:	#detect_ambiguities#45 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1629
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1760 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:707
      From worker 6:	detect_ambiguities##kw at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1584
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1760 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:707
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1760 [inlined]
      From worker 6:	do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
      From worker 6:	eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
      From worker 6:	eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
      From worker 6:	eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:575
      From worker 6:	eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:503
      From worker 6:	eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:503
      From worker 6:	eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:503
      From worker 6:	jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:718
      From worker 6:	jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:884
      From worker 6:	jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:829
      From worker 6:	jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:936
      From worker 6:	eval at ./boot.jl:369 [inlined]
      From worker 6:	include_string at ./loading.jl:1097
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	_include at ./loading.jl:1154
      From worker 6:	include at ./Base.jl:389 [inlined]
      From worker 6:	macro expansion at /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:24 [inlined]
      From worker 6:	macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1269 [inlined]
      From worker 6:	macro expansion at /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:23 [inlined]
      From worker 6:	macro expansion at ./timing.jl:368 [inlined]
      From worker 6:	#runtests#1 at /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:21
      From worker 6:	runtests##kw at /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:6 [inlined]
      From worker 6:	runtests##kw at /buildworker/worker/tester_linux64/build/share/julia/test/testdefs.jl:6
      From worker 6:	unknown function (ip: 0x7fb20a82e19c)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1760 [inlined]
      From worker 6:	do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:707
      From worker 6:	#106 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278
      From worker 6:	run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:63
      From worker 6:	macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:278 [inlined]
      From worker 6:	#105 at ./task.jl:411
      From worker 6:	unknown function (ip: 0x7fb20a823d4f)
      From worker 6:	_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2224 [inlined]
      From worker 6:	jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
      From worker 6:	jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1760 [inlined]
      From worker 6:	start_task at /buildworker/worker/package_linux64/build/src/task.c:833
      From worker 6:	Allocations: 628053481 (Pool: 627724870; Big: 328611); GC: 657
```

and

```
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/precompile.jl:303
  Expression: Dict(modules) == merge(Dict((let m = Base.PkgId(s)
                m => Base.module_build_id(Base.root_module(m))
            end for s = ["Base", "Core", "Main", string(Foo2_module), string(FooBase_module)])), Dict((let m = Base.root_module(Base, s)
                Base.PkgId(m) => Base.module_build_id(m)
            end for s = [:ArgTools, :Artifacts, :Base64, :CRC32c, :Dates, :DelimitedFiles, :Distributed, :Downloads, :FileWatching, :Future, :InteractiveUtils, :LazyArtifacts, :LibCURL, :LibCURL_jll, :LibGit2, :Libdl, :LinearAlgebra, :Logging, :Markdown, :Mmap, :MozillaCACerts_jll, :NetworkOptions, :Pkg, :Printf, :Profile, :p7zip_jll, :REPL, :Random, :SHA, :Serialization, :SharedArrays, :Sockets, :SparseArrays, :Statistics, :SuiteSparse, :TOML, :Tar, :Test, :UUIDs, :Unicode, :nghttp2_jll])))
   Evaluated: Dict{Base.PkgId, UInt64}(Dates [ade2ca70-3891-5945-98fb-dc099432e06a] => 0x00406771290f5902, ArgTools [0dad84c5-d112-42e6-8d28-ef12dabb789f] => 0x0040676d448d732d, CRC32c [8bf52ea8-c179-5cab-976a-9e18b702a9bc] => 0x0040676daa804320, LinearAlgebra [37e2e46d-f89d-539d-b4ee-838fcccc9c8e] => 0x0040676e0ad8d6bc, SparseArrays [2f01184e-e22b-5df5-ae63-d93ebab69eaf] => 0x00406772ac37f4ce, libblastrampoline_jll [8e850b90-86db-534c-a0d3-1478176c7d93] => 0x00406774f35210c9, TOML [fa267f1f-6049-4f14-aa54-33bafae1ed76] => 0x004067756a538ceb, LibCURL [b27032c2-a3e7-50c8-80cd-2d36dbcbfd21] => 0x0040677585912981, Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] => 0x0040676da161fc1c, Serialization [9e88b42a-f829-5b0c-bbe9-9e923198166b] => 0x0040676dd45e07a7���) == Dict{Base.PkgId, UInt64}(LibCURL [b27032c2-a3e7-50c8-80cd-2d36dbcbfd21] => 0x0040677585912981, SparseArrays [2f01184e-e22b-5df5-ae63-d93ebab69eaf] => 0x00406772ac37f4ce, TOML [fa267f1f-6049-4f14-aa54-33bafae1ed76] => 0x004067756a538ceb, Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] => 0x0040676da161fc1c, Serialization [9e88b42a-f829-5b0c-bbe9-9e923198166b] => 0x0040676dd45e07a7, UUIDs [cf7118a7-6976-5b1a-9a39-7adc72f591a4] => 0x004067738f20ea8b, Future [9fa8497b-333b-5362-9e8d-4d0656e87820] => 0x00406771f9ee6032, FooBase4b3a94a1a081a8cb [top-level] => 0x00d00eedd311b921, Main [top-level] => 0x0040674b39020926, REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] => 0x00406773937b2e5b���)

```

**Comment by vtjnash** [comment]
That is changing a lot of files https://github.com/JuliaLang/SuiteSparse.jl/compare/9cfdbbd33d2d52b83b2459f670162244cc95460c...79db23e6c2a499059ea12122f329b60d7b0ac429 so there might be a bug in there?

The latter error probably means something got loaded which was not supposed to be (probably a JLL compatibility module).

**Comment by ViralBShah** [comment]
We may need @gnimuc to help track these down.

**Comment by KristofferC** [comment]
The internal assertion when running the method ambiguity test seems like it is a Base issue?

**Comment by Gnimuc** [comment]
How to debug this locally? By editing those hashes and doing a source build of Julia?

**Comment by Gnimuc** [comment]
I get this warning when building Julia with this branch:
```
➜  julia git:(kc/bump_suitesparse) make -j4              
/Users/gnimuc/Codes/julia-master/julia/contrib/install.sh 755 /Users/gnimuc/Codes/julia-master/julia/contrib/julia-config.jl /Users/gnimuc/Codes/julia-master/julia/usr/share/julia/
Creating usr/etc/julia/startup.jl
Copying in usr/share/man/man1/julia.1
    LINK usr/lib/libjulia.1.7.dylib
WARNING: using mismatched version for SuiteSparse.v5.8.1+2.x86_64-apple-darwin bb-uninstaller:
  want SuiteSparse-79db23e6c2a499059ea12122f329b60d7b0ac429 symlink-uninstaller /Users/gnimuc/Codes/julia-master/julia/usr/share/julia/stdlib/v1.7
  To resolve this warning, you could try either of the following suggestions: 
  1. Run the following command: make -C deps uninstall
  2. Remove the following directory: /Users/gnimuc/Codes/julia-master/julia/usr
```

**Comment by Gnimuc** [comment]
Oh, never mind. It's https://github.com/JuliaLang/julia/issues/40854.

**Comment by KristofferC** [comment]
For the second error, I don't think https://github.com/JuliaLang/SuiteSparse.jl/blob/79db23e6c2a499059ea12122f329b60d7b0ac429/src/LibSuiteSparse.jl#L3 should be in there. Right now, the stdlibs don't actually use their jlls.

**Comment by Gnimuc** [comment]
I don't understand. I just copied what LibCURL.jl did [here](https://github.com/JuliaWeb/LibCURL.jl/blob/master/src/LibCURL.jl#L4) when creating the `LibSuiteSparse` module.

**Comment by Gnimuc** [comment]
Any references/docs on how to develop/create a stdlib package?

**Comment by KristofferC** [comment]
I see, and `LibCURL_jll` was added here https://github.com/JuliaLang/julia/blob/bb5b98e72a151c41471d8cc14cacb495d647fb7f/test/precompile.jl#L315. So I guess in theory we could add `SuiteSparse_jll` to that list as well (with the side effect that it would now be in the sysimage).

The jll situation with stdlibs is quite confusing right now and I don't know what is right and wrong. Maybe @StefanKarpinski  or @staticfloat knows what one is supposed to do.

**Comment by staticfloat** [comment]
For now, I move that we continue to write stdlibs in the form where we write ccalls as `ccall((:funcname, "libfoo.so"), ...)`, which will implicitly load `libfoo.so` if it's not already loaded.  As long as the library belongs to a JLL that drops its libraries into Julia's libdir, that will continue to work, and will have no startup impact.  We need to get a few more pieces into Base Julia (And some JLL changes) to be able to `using SuiteSparse_jll` and have it not impact load time at all.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by KristofferC** [comment]
Looks good now, can be merged after the benchmarks.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40844#issuecomment-847848965) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/1702fa5_vs_8bc9e78/report.md). cc @christopher-dG

**Pull request merged**
