### PR TITLE
more compact lowering of return type decls on short functions

### PR DESCRIPTION
**Pull request by JeffBezanson**
This fixes the large SIMD regressions in #17600, which were due to a failure to inline `afoldl`.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("simd", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17613#issuecomment-235018513) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b051971f2f41290b04eaa974c3dc5f971fca7e43/fb0c436_vs_c6fab9d/report.md). cc @jrevels

**Comment by JeffBezanson** [comment]
Now we're failing to infer certain Float16 functions again. So far I can't make any sense of it.

**Comment by JeffBezanson** [comment]
Ok, Float16 issues should be fixed now.

**Comment by tkelman** [comment]
Funny enough this broke the tests for ResultTypes.jl, cc @iamed2 

```
INFO: Testing ResultTypes
Test Summary: | Pass  Total
  Result      |    8      8
Test Summary: | Pass  Total
  ErrorResult |   10     10
Test Summary: | Pass  Total
  Convert     |    8      8
Return: Test Failed
  Expression: isa(x,Result{Int,DivideError})
 in record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:428
 in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:281
 in macro expansion; at /home/vagrant/.julia/v0.5/ResultTypes/test/runtests.jl:89 [inlined]
 in macro expansion; at ./test.jl:672 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
Return: Error During Test
  Test threw an exception of type MethodError
  Expression: unwrap(x) === 1
  MethodError: no method matching unwrap(::Int64)
  Closest candidates are:
    unwrap{T,E}(!Matched::ResultTypes.Result{T,E}) at /home/vagrant/.julia/v0.5/ResultTypes/src/ResultTypes.jl:26
   in macro expansion; at /home/vagrant/.julia/v0.5/ResultTypes/test/runtests.jl:90 [inlined]
   in macro expansion; at ./test.jl:672 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:426
   in process_options(::Base.JLOptions) at ./client.jl:262
   in _start() at ./client.jl:318
Return: Test Failed
  Expression: isa(y,Result{Int,DivideError})
 in record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:428
 in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:281
 in macro expansion; at /home/vagrant/.julia/v0.5/ResultTypes/test/runtests.jl:93 [inlined]
 in macro expansion; at ./test.jl:672 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
Return: Error During Test
  Test threw an exception of type MethodError
  Expression: unwrap_error(y) == DivideError()
  MethodError: no method matching unwrap_error(::DivideError)
  Closest candidates are:
    unwrap_error{T,E}(!Matched::ResultTypes.Result{T,E}) at /home/vagrant/.julia/v0.5/ResultTypes/src/ResultTypes.jl:36
   in macro expansion; at /home/vagrant/.julia/v0.5/ResultTypes/test/runtests.jl:94 [inlined]
   in macro expansion; at ./test.jl:672 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:426
   in process_options(::Base.JLOptions) at ./client.jl:262
   in _start() at ./client.jl:318
Test Summary: | Fail  Error  Total
  Return      |    2      2      4
ERROR: LoadError: Some tests did not pass: 0 passed, 2 failed, 2 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:495
 in macro expansion; at ./test.jl:679 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/vagrant/.julia/v0.5/ResultTypes/test/runtests.jl, in expression starting on line 78
```

**Comment by iamed2** [comment]
Looks like `convert` is not being called on the return values for [this function](https://github.com/iamed2/ResultTypes.jl/blob/master/test/runtests.jl#L80).

**Comment by JeffBezanson** [comment]
Fix on the way.

**Pull request merged**
