### PR TITLE
Deprecate conj(::Any), add real(::Missing) and imag(::Missing)

### PR DESCRIPTION
**Pull request by dlfivefifty**
This resolves issue #26248

### CODE REVIEW

**Review by Sacha0 — COMMENTED** [review]
Thanks @dlfivefifty! :) Out of curiosity, why the associated `real` and `imag` changes? Also, perhaps a brief news entry is in order?

**Review by andreasnoack — APPROVED** [review]

**Comment by dlfivefifty** [comment]
I noticed that `real(::Missing)` and `imag(::Missing)` weren't implemented (threw an error) and so I added them.

Unless they were left off intentionally.

**Review by nalimilan — APPROVED** [review]
Thanks! Could you make the same changes in Missings.jl for 0.6 compatibility?

**Comment by quinnj** [comment]
@dlfivefifty, any interest in just adding https://github.com/JuliaLang/julia/pull/25502#issuecomment-369769135 into this PR? These changes are so small...

**Comment by dlfivefifty** [comment]
> any interest in just adding #25502 (comment)

Isn't that PR fine as is?

**Comment by fredrikekre** [comment]
At this rate of adding special `missing` methods I feel like we should instead have something like `(::Function)(::Missing) = missing` instead of go digging for methods that dont have their `missing` method defined.

**Comment by nalimilan** [comment]
> At this rate of adding special missing methods I feel like we should instead have something like (::Function)(::Missing) = missing instead of go digging for methods that dont have their missing method defined.

That's been evoked at least since `Nullable` was introduced. Indeed that would make a lot of sense for one-argument methods, but then it's more difficult when there are several arguments as we have no way currently to express "at least one argument is `missing`". We would also need a special mechanism to prevent ambiguities from arising everywhere. In theory this could be introduced in 1.x without breaking code, at least if methods with arguments marked as `::Any` take precedence over the `missing` fallback.

There's also the objection that `missing` generally only makes sense where a scalar would be passed. It's probably better to have `det(missing)` or `permutedims(missing)` throw an error than return `missing` (though in practice you'll likely get an error soon enough anyway).

**Comment by dlfivefifty** [comment]
I think a less dangerous approach would be to keep an official list of "math" functions a la `Calculus.symbolic_derivatives_1arg` that can be looped over.

**Comment by JeffBezanson** [comment]
I'll remind everybody here of the terms of the `missing` deal: I was assured that those who wanted `missing` would content themselves with a fixed set of commonly-used functions (as in e.g. C#), and use some kind of manual lifting for everything else.

**Pull request merged**
