### PR TITLE
make Cstring and Cwstring subtypes of Ref

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
cc @vtjnash, @yuyichao

**Comment by stevengj** [comment]
What does this accomplish?

**Comment by StefanKarpinski** [comment]
Was suggested by @vtjnash to fix an issue I was having that it turns out it doesn't fix. It might still be the right thing to do.

**Comment by stevengj** [comment]
It just seems odd.  if `x::Ref`, I would expect `x[]` to refer to the "value" being referenced, but that doesn't work for `Cstring` (and it's not clear what the `x[]` method would do in that case).  Also, I would expect a `Ref` to be mutable, i.e. `x[] = value` to work, and again it's not clear to me what this would mean for `Cstring`.

**Pull request closed without merging**
