### PR TITLE
add LLVM patch D65174 to fix a compiler performance regression

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vchuravy** [comment]
After the BB bump I can do the backport to 1.4

**Comment by vchuravy** [comment]
Did you test that the patch for LLVM8 applies cleanly? I was applying in https://github.com/JuliaPackaging/Yggdrasil/pull/658 and it seems to fail.

**Comment by JeffBezanson** [comment]
I don't believe any released version of julia uses LLVM 8, so I'd be fine just not supporting the patch there.

**Comment by KristofferC** [comment]
1.4 uses LLVM 8 right?

**Comment by vchuravy** [comment]
This should be good to go, and I will handle the backport to 1.4

**Comment by JeffBezanson** [comment]
Oops, of course, for some reason I thought 1.4 was also LLVM 9. @vchuravy did you manage to port the patch to LLVM 8 or should I do it?

**Comment by vchuravy** [comment]
> Oops, of course, for some reason I thought 1.4 was also LLVM 9. @vchuravy did you manage to port the patch to LLVM 8 or should I do it?

I was planning to do it over the weekend since there is a second patch as well. Dealing with LLVM is a good cure of insomnia.

**Comment by KristofferC** [comment]
Backporting tracked in https://github.com/JuliaLang/julia/pull/35300

**Pull request merged**
