### PR TITLE
wip: pass around `CallInfo` object to the inlining algorithm

### PR DESCRIPTION
**Pull request by aviatesk**
So that `inlining_policy` can see user-`CallInfo` object. It allows us to implement a customized inlining heuristics by just seeing a callsite information, without requiring the inlining cost of cached code to be tweaked.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46963#issuecomment-1261676720) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ef193e8_vs_75e96c5/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46963#issuecomment-1261874742) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c64ec60_vs_9118373/report.md).

**Comment by vtjnash** [comment]
This seems quite expensive for inference (perhaps because `@nospecialize(info::CallInfo)` is rather bad for performance until CallInfo is concrete). Can we make CallInfo a concrete object here so that we don't pay that dispatch cost?

**Comment by aviatesk** [comment]
> This seems quite expensive for inference (perhaps because `@nospecialize(info::CallInfo)` is rather bad for performance until CallInfo is concrete). Can we make CallInfo a concrete object here so that we don't pay that dispatch cost?

Yeah, that sounds to be a way to optimize this PR. I will give a try to the idea on #46965.

**Comment by aviatesk** [comment]
> > This seems quite expensive for inference (perhaps because `@nospecialize(info::CallInfo)` is rather bad for performance until CallInfo is concrete). Can we make CallInfo a concrete object here so that we don't pay that dispatch cost?
> 
> Yeah, that sounds to be a way to optimize this PR. I will give a try to the idea on #46965.

Hmm, but on a second thought, the `CallInfo` subtypes are fairly diverse and have very different structures, making it hard to unify them into a single struct.

**Comment by JeffBezanson** [comment]
Do we really need this much flexibility to customize inlining, or would it be sufficient just to customize cost computation?

**Comment by aviatesk** [comment]
> Do we really need this much flexibility to customize inlining, or would it be sufficient just to customize cost computation?

I think sometimes we need a logic to tweak inlineability based on caller's context rather than computed inline costs, and in order to propagate the information of caller's context we need this sort of infrastructure for user `CallInfo` object.

I crafted this test set for explaining what we are trying to achieve here https://github.com/JuliaLang/julia/pull/46965/commits/f0b5872e39f967230bfd1df3e2be6e9490462c4b.

---

I also submitted a more optimized version of this PR at #46965 -- the regression there seems minor and I'd like to focus on completing it.

**Pull request closed without merging**
