### PR TITLE
Added tests for Iterators for a few edge cases.

### PR DESCRIPTION
**Pull request by ravibitsgoa**
Improves test coverage for Iterators.
Covers a few edge cases.

### CODE REVIEW

**Comment by ravibitsgoa** [comment]
Hi everyone,
Can someone please review this PR?

**Comment by ViralBShah** [comment]
Can you rebase to master?

@kshyatt Should we merge this?

**Comment by rfourquet** [comment]
There seems to have been a problem with git rebase/merge, as this now shows 611 files changed and 311 commits in this PR :)

**Comment by ViralBShah** [comment]
I guess best to close.

**Pull request closed without merging**
