### PR TITLE
Docs: Reference functions instead of methods

### PR DESCRIPTION
**Pull request by BioTurboNick**
By referencing methods sometimes and not just functions, there was some duplication and confusion. For instance, we had `get(::Any, ::Any, ::Any)` method and also a `get` function, the latter of which duplicated the documentation for the former.

~~Is there an unseen benefit to referencing just the function at times?~~ EDIT: Documenter errors if there are exact duplicates, and sometimes it makes sense to split the functions by section.

~~If this PR is acceptable, I can go through the other pages to do the same.~~

### CODE REVIEW

**Review by fredrikekre — CHANGES_REQUESTED** [review]
They are here for a reason; there are other places where methods of these functions are included. See CI failures.

**Comment by BioTurboNick** [comment]
I think I made the only necessary change.

**Comment by ViralBShah** [comment]
@fredrikekre Is this ok to merge?

**Comment by BioTurboNick** [comment]
I narrowed the scope to just change it for `get` and `get!`, since there might be good reasons for the others.

**Pull request merged**
