### PR TITLE
🤖 Bump the SparseArrays stdlib from aa51c9b to 96820d3

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Branch: main
Old commit: aa51c9b
New commit: 96820d3
Bump invoked by: @stevengj
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline aa51c9b..96820d3
96820d3 remove invalid test for failing sprand(BigFloat) (#85)
97189f3 Add borders when showing sparse matrices with Braille (#79)
a5e9ac4 Change type signature of _checkbuffers and _goodbuffers (#77)
119cd63 Fix syntax in basetests.jl (#80)
```

### CODE REVIEW

**Comment by stevengj** [comment]
(Needed for #44714.)

**Comment by stevengj** [comment]
CI failure (timed out "generating REPL precompile statements") seems unrelated?  (It had already finished precompiling SparseArrays.)

**Comment by stevengj** [comment]
Not sure why `buildbot/tester_linux32` has been *"Pending"* for a day now?

**Comment by DilumAluthge** [comment]
> Not sure why `buildbot/tester_linux32` has been _"Pending"_ for a day now?

There's a two-day backlog: https://build.julialang.org/#/builders/17

cc: @staticfloat

**Pull request merged**
