### PR TITLE
Backports for 1.0.3

### LINKED ISSUE #29713: Bug in out of place ldiv!
The out-of-place version of `ldiv!(Y, A, B)` incorrectly overwrite `B` when `A` is a factorization of a non square matrix. 

```julia
using LinearAlgebra
A = [ -3.0  -6.0; 0.0 1.0; 1.0   2.0]
B = [0.0 1.0; 1.0   2.0; 2.0   3.0]
Bc = copy(B)
Y = Array{Float64}(undef, 3,3)
ldiv!(Y, qr(A), B)
Bc == B #false
```
The problem is in https://github.com/JuliaLang/julia/blob/367aab3dc15a5543bd14c73d1e38a3ce7e310f05/stdlib/LinearAlgebra/src/factorization.jl#L103 where `ldiv!(Y, A, B)` reduces to a call to `ldiv!(A,B)` which overwrites B.

### LINKED ISSUE #29955: Unreachable reached - Linux and Windows - Julia v1.0.1 and 0.7.0
Hi,

The following code seems to break multiple versions of Julia. I tried it on Linux and Windows, v0.7.0 and v1.0.1. It worked fine in Julia v0.6.4.

```julia
run(`git clone https://github.com/mohamed82008/TopOpt.jl TopOpt`)
cd(()->run(`git checkout segfault`), "TopOpt")
using Pkg
Pkg.activate("./TopOpt")
Pkg.instantiate()

include("TopOpt/test/segfault.jl")
```

Here is the Linux `versioninfo()`:
```julia
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

Good luck!

### LINKED ISSUE #29989: mkpath should always return the path
If a path doesn't exist, `mkpath` returns it:
```jl
julia> @show mkpath("frizz")
mkpath("frizz") = "frizz"
"frizz"
```
However, if the path already exists, it doesn't:
```jl
julia> @show mkpath("frizz")
mkpath("frizz") = nothing
```

### LINKED ISSUE #29995: broken text/latex output for markdown horizontal rule
`Markdown.MD` objects claim to support text/latex output, but there is a `MethodError` for `HorizontalRule` elements (from JuliaLang/IJulia.jl#776):
```jl
julia> using Markdown

julia> m = Markdown.parse("---")
  ────────────────────────────────────────────────────────────────────────────

julia> showable("text/latex", m)
true

julia> show(stdout, "text/latex", m)
ERROR: MethodError: no method matching latex(::Base.TTY, ::Markdown.HorizontalRule)
Closest candidates are:
  latex(::IO, ::Markdown.Table) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/GitHub/table.jl:154
  latex(::IO, ::Markdown.LaTeX) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/IPython/IPython.jl:28
  latex(::IO, ::Markdown.MD) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:19
  ...
Stacktrace:
 [1] latex(::Base.TTY, ::Array{Any,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:23
 [2] latex at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:19 [inlined]
 [3] show(::Base.TTY, ::MIME{Symbol("text/latex")}, ::Markdown.MD) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Markdown/src/render/latex.jl:172
 [4] show(::Base.TTY, ::String, ::Markdown.MD) at ./multimedia.jl:79
 [5] top-level scope at none:0
```

### LINKED ISSUE #30030: `ERROR: syntax: invalid named tuple element` misleading message
The following code produces the following syntax error.
```
julia> d = 4
4

julia> (
           a=2,
           b=3,
           c = (d=d)
           )
ERROR: syntax: invalid named tuple element "2"
```

The fix is to add a trailing `,` (comma) to the named tuple of one element, which is not quite what the error message says.

```
julia> (
           a=2,
           b=3,
           c = (d=d,)
           )
(a = 2, b = 3, c = (d = 4,))

```

```julia
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

(I ran into this when porting code away from using `NamedTuples.jl`on juia v0.6)

### LINKED ISSUE #30048: syntax: bad ssavalue / `GC.@preserve` interaction
Julia fails at parsing the following seemingly-legal function definition:
```jl
function handle_repos_add!(ctx::Context, pkgs::AbstractVector{PackageSpec};
                           upgrade_or_add::Bool=true, credentials=nothing)
    # Always update the registry when adding
    UPDATED_REGISTRY_THIS_SESSION[] || update_registries(ctx)
    creds = credentials !== nothing ? credentials : LibGit2.CachedCredentials()
    try
        env = ctx.env
        new_uuids = UUID[]
        for pkg in pkgs
            pkg.repo == nothing && continue
            pkg.special_action = PKGSPEC_REPO_ADDED
            isempty(pkg.repo.url) && set_repo_for_pkg!(env, pkg)
            clones_dir = joinpath(depots1(), "clones")
            mkpath(clones_dir)
            repo_path = joinpath(clones_dir, string(hash(pkg.repo.url)))
            repo = nothing
            do_nothing_more = false
            project_path = nothing
            folder_already_downloaded = false
            try
                repo = if ispath(repo_path)
                    LibGit2.GitRepo(repo_path)
                else
                    GitTools.clone(pkg.repo.url, repo_path, isbare=true, credentials=creds)
                end
                info = manifest_info(env, pkg.uuid)
                pinned = (info != nothing && get(info, "pinned", false))
                upgrading = upgrade_or_add && !pinned
                if upgrading
                    GitTools.fetch(repo; refspecs=refspecs, credentials=creds)
                    rev = pkg.repo.rev
                    # see if we can get rev as a branch
                    if isempty(rev)
                        if LibGit2.isattached(repo)
                            rev = LibGit2.branch(repo)
                        else
                            rev = string(LibGit2.GitHash(LibGit2.head(repo)))
                        end
                    end
                else
                    # Not upgrading so the rev should be the current git-tree-sha
                    rev = info["git-tree-sha1"]
                    pkg.version = VersionNumber(info["version"])
                end

                gitobject, isbranch = get_object_branch(repo, rev, creds)
                # If the user gave a shortened commit SHA, might as well update it to the full one
                try
                    if upgrading
                        pkg.repo.rev = isbranch ? rev : string(LibGit2.GitHash(gitobject))
                    end
                    LibGit2.with(LibGit2.peel(LibGit2.GitTree, gitobject)) do git_tree
                        @assert git_tree isa LibGit2.GitTree
                        pkg.repo.git_tree_sha1 = SHA1(string(LibGit2.GitHash(git_tree)))
                            version_path = nothing
                            folder_already_downloaded = false
                        if has_uuid(pkg) && has_name(pkg)
                            version_path = Pkg.Operations.find_installed(pkg.name, pkg.uuid, pkg.repo.git_tree_sha1)
                            isdir(version_path) && (folder_already_downloaded = true)
                            info = manifest_info(env, pkg.uuid)
                            if info != nothing && get(info, "git-tree-sha1", "") == string(pkg.repo.git_tree_sha1) && folder_already_downloaded
                                # Same tree sha and this version already downloaded, nothing left to do
                                do_nothing_more = true
                            end
                        end
                        if folder_already_downloaded
                            project_path = version_path
                        else
                            project_path = mktempdir()
                            GC.@preserve project_path begin
                                opts = LibGit2.CheckoutOptions(
                                    checkout_strategy = LibGit2.Consts.CHECKOUT_FORCE,
                                    target_directory = Base.unsafe_convert(Cstring, project_path),
                                )
                                LibGit2.checkout_tree(repo, git_tree, options=opts)
                            end
                        end
                    end
                finally
                    close(gitobject)
                end
            finally
                repo isa LibGit2.GitRepo && close(repo)
            end
            do_nothing_more && continue
            parse_package!(ctx, pkg, project_path)
            if !folder_already_downloaded
                version_path = Pkg.Operations.find_installed(pkg.name, pkg.uuid, pkg.repo.git_tree_sha1)
                mkpath(version_path)
                mv(project_path, version_path; force=true)
                push!(new_uuids, pkg.uuid)
            end
            Base.rm(project_path; force = true, recursive = true)
            @assert has_uuid(pkg)
        end
        return new_uuids
    finally
        creds !== credentials && Base.shred!(creds)
    end
end
```
with this error message:
```
ERROR: syntax: ssavalue with no def
```
There is no error without the `GC.@preserve` block.

Found at https://github.com/JuliaLang/Pkg.jl/pull/902.

### LINKED ISSUE #30122: Unreachable reached
I hit "Unreachable reached" error with Julia 1.0.2 on Archlinux, then I tried backports-1.0.3 branch, assuming that #29986 will fix the problem, but it's still there.
Unfortunately, I don't have a small reproducible test case: it happens when I try to run the `]test BlackBoxOptim` using [pareto_rtree](https://github.com/alyst/BlackBoxOptim.jl/tree/pareto_rtree) branch, which requires [SpatialIndexing](https://github.com/alyst/SpatialIndexing.jl) master (not yet in Julia registry).

Here's the log:
```
              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3-pre.29 (2018-11-19)
 _/ |\__'_|_|_|\__'_|  |  makepkg/33a5d6a2d9* (fork: 316 commits, 105 days)
|__/                   |

julia> versioninfo()
Julia Version 1.0.3-pre.29
Commit 33a5d6a2d9* (2018-11-19 15:19 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

(v1.0) pkg> test BlackBoxOptim
   Testing BlackBoxOptim
 Resolving package versions...
    Status `/tmp/tmpZWmfd8/Manifest.toml`
....

[ Info: subtract!(): region=BlackBoxOptim.DominanceCone{Int64,2,true}((22, 11))
[ Info: subtract!(): region=BlackBoxOptim.DominanceCone{Int64,2,true}((32, 11))
[ Info: _subtract!(): lev=0 i=0 len=1
[ Info: _subtract!(): delete subtree lev=0 i=0 len=1
[ Info: delete_subtree(): lev=0
[ Info: _delete_subtree(): empty children (1 objs) of node lev=0 parent=false
[ Info: _delete_subtree(): done node lev=0 parent=false
[ Info: _subtract!(): delete subtree done lev=0 i=0 len=0, returning 1
Unreachable reached at 0x7f8e4dabf335

signal (4): Illegal instruction
in expression starting at /home/ge68wan/.julia/dev/BlackBoxOptim/test/test_epsbox_archive.jl:1
subtract! at /home/ge68wan/.julia/dev/SpatialIndexing/src/rtree/delete.jl:65
add_candidate! at /home/ge68wan/.julia/dev/BlackBoxOptim/src/archives/epsbox_archive.jl:235
add_candidate! at /home/ge68wan/.julia/dev/BlackBoxOptim/src/archives/epsbox_archive.jl:262 [inlined]
add_candidate! at /home/ge68wan/.julia/dev/BlackBoxOptim/src/archives/epsbox_archive.jl:262
unknown function (ip: 0x7f8e4dad9d35)
jl_fptr_trampoline at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/bin/../lib/libjulia.so.1 (unknown line)
macro expansion at /home/ge68wan/.julia/dev/BlackBoxOptim/test/test_epsbox_archive.jl:50 [inlined]
macro expansion at /home/ge68wan/aur/julia-git/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
macro expansion at /home/ge68wan/.julia/dev/BlackBoxOptim/test/test_epsbox_archive.jl:32 [inlined]
macro expansion at /home/ge68wan/aur/julia-git/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
top-level scope at /home/ge68wan/.julia/dev/BlackBoxOptim/test/test_epsbox_archive.jl:4
jl_fptr_trampoline at /usr/bin/../lib/libjulia.so.1 (unknown line)
....
```

Here's the [code in question](https://github.com/alyst/SpatialIndexing.jl/blob/master/src/rtree/delete.jl):
```julia
function subtract!(tree::RTree{T,N}, reg::Region{T,N}) where {T,N}
    @info "subtract!(): region=$(reg)"
    isempty(tree) && return tree

    tmpdetached = Vector{nodetype(tree)}()
    status = _subtract!(tree.root, 0, reg, tree, tmpdetached)
    @info "_subtract!(root) done"
    @show status
    @show typeof(tmpdetached) length(tmpdetached)
    @info "subtract!(): status=$(status) tmpdetached=$(length(tmpdetached))"
    if status == 1 # tree changed, but not removed
        _condense!(tree.root, tree, tmpdetached) # try to condense the root
    elseif status == 2 # whole tree removed
        @assert isempty(tree)
        @assert isempty(tmpdetached)
    end
    _reinsert!(tree, tmpdetached)
    return tree
end

function _subtract!(node::Node, node_ix::Int, reg::Region, tree::RTree,
                    tmpdetached::AbstractVector{<:Node})
    nodembr = mbr(node)
    @info "_subtract!(): lev=$(level(node)) i=$node_ix len=$(length(node))"
    # FIXME juxtaposition() method that combines in() and intersects()?
    if in(nodembr, reg)
        @info "_subtract!(): delete subtree lev=$(level(node)) i=$node_ix len=$(length(node))"
        delete_subtree!(tree, node)
        @info "_subtract!(): delete subtree done lev=$(level(node)) i=$node_ix len=$(length(node)), returning 1"
        return 2 # node removed
    elseif intersects(nodembr, reg)
        mbr_dirty = false
        i = 1
        while i <= length(node)
            #@debug "1: lev=$(level(node)) i=$i len=$(length(node))"
            child = node[i]
            oldmbr = mbr(child)
            if node isa Branch
                child_res = _subtract!(child, i, reg, tree, tmpdetached)
            else
                @assert node isa Leaf
                if in(oldmbr, reg)
                    @info "_subtract!(): detach elem lev=$(level(node)) i=$i len=$(length(node))"
                    _detach!(node, i, tree, updatembr = false) # don't update MBR, we do it later
                    tree.nelems -= 1
                    tree.nelem_deletions += 1
                    child_res = 2
                    # FIXME intersect is not considered (would be important if elem mbr is not a point), should be handled by `filter`
                else
                    child_res = 0
                end
            end
            if !mbr_dirty && (child_res != 0) && tree.tight_mbrs
                mbr_dirty = touches(nodembr, oldmbr)
            end
            if child_res != 2 # don't increment if i-th node removed
                i += 1
            end
        end
        if hasparent(node) && length(node) < floor(Int, tree.reinsert_factor * capacity(node, tree))
            _detach!(parent(node), node_ix, tree)
            tree.nnodes_perlevel[level(node)+1] -= 1
            push!(tmpdetached, node)
            return 2 # node removed
        elseif mbr_dirty
            syncmbr!(node)
            return 1 # mbr changed
        else
            return 0 # no mbr change
        end
    else
        return 0 # no change
    end
end
```

It looks like the error happens immediately before/after `_subtract!()` returns to `subtract!()`.

I think it's related to the concrete types of the `RTree` and `Node`, because this code runs fine in `SpatialIndexing` tests (`nodetype(tree) = SpatialIndexing.Node{Float64,3,SpatialElem{Float64,3,Int64,String}}`), but fails when (`nodetype(tree) = SpatialIndexing.Node{Int64,2,BlackBoxOptim.FrontierIndividual{BlackBoxOptim.IndexedTupleFitness{2,Float64}}}`).
Since it looks like it's type-related, I thought that it might be similar to #30067.

### LINKED ISSUE #30234: REPL: cannot assign variables whose names match a name exported from Base after any tab autocompletion
If you press tab twice to autocomplete a name, the variable `names` is no longer assignable in global scope. 

In a new REPL session:

```
julia> f<tab><tab>
factorial   fieldoffset  finalizer    findnext     flipsign     for
false       fieldtype    finally      findprev     float        foreach
falses      filemode     findall      first        floatmax     frexp
fd          filesize     findfirst    firstindex   floatmin     fullname
fdio        fill         findlast     fld          floor        function
fetch       fill!        findmax      fld1         flush        functionloc
fieldcount  filter       findmax!     fldmod       fma
fieldname   filter!      findmin      fldmod1      foldl
fieldnames  finalize     findmin!     flip         foldr
julia> names = 10
ERROR: cannot assign variable Base.names from module Main
Stacktrace:
 [1] top-level scope at none:0

julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = subl
```

I saw a few related issues (e.g. https://github.com/JuliaLang/julia/issues/23677) but am not sure if they describe the same issue. If they do, feel free to close.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] JuliaLang/julia#29296 - stdlib/SparseArrays: add rmul! and lmul! of sparse matrix with Diagonal
- [x] JuliaLang/julia#29865 - Avoid slow fallback Matrix constructor when converting Q from QR,
- [x] JuliaLang/julia#29899 - Fix minor typo in print_range docs
- [x] JuliaLang/julia#29892 - avoid expensive runtime div in parse for common bases
- [x] JuliaLang/julia#29715 - Fix JuliaLang/LinearAlgebra.jl#577 (ldiv! overwrites arguments)
- [x] JuliaLang/julia#29910 - Update old reference to Base.REPL
- [x] JuliaLang/julia#29902 - Make median! type stable for small float types
- [x] JuliaLang/julia#29925 - Avoid reading inactive rowvals when computing the rank of a QRSparse
- [x] JuliaLang/julia#29738 - Prepend a version number too in source tarballs
- [x] JuliaLang/julia#29948 - Add missing devdoc pages to make.jl
- [x] JuliaLang/julia#29933 - Add missing backslashes in LaTeX syntax in the document of binomial function
- [x] JuliaLang/julia#29803 - Use SYSTEMROOT env variable for powershell detection
- [x] JuliaLang/julia#29961 - Add backticks around som JL_* words in the manual
- [x] JuliaLang/julia#29898 - deploy docs to JuliaLang/docs.julialang.org
- [x] JuliaLang/julia#29990 - mkpath should always return the path (fix JuliaLang/julia#29989)
- [x] JuliaLang/julia#29994 - file creation tests: check path existence before & after
- [x] JuliaLang/julia#29888 - Faster findall for bitarrays
- [x] JuliaLang/julia#30012 - Use at-DIR instead of Sys.BINDIR to find UnicodeData.txt in doc build.
- [x] JuliaLang/julia#30000 - Include stdlib tarballs in light-source-dist.
- [x] JuliaLang/julia#30029 - Move Markdown docs to the Markdown stdlib
- [x] JuliaLang/julia#30015 - Added note to highlight that some variables can't be set in `startup.jl`
- [x] JuliaLang/julia#29986 - fix JuliaLang/julia#29955, intersection bugs involving triangular constraints
- [x] JuliaLang/julia#30033 - Work around a llvm-config bug by creating a versioned symlink to libLLVM
- [x] JuliaLang/julia#30036 - Make generated code for rational constructor and gcd slightly smaller
- [x] JuliaLang/julia#30011 - Fix backtrace line numbers following macros
- [x] JuliaLang/julia#30051 - fix JuliaLang/julia#30048, lowering gc_preserve of closure variables
- [x] JuliaLang/julia#29921 - Update the Regex section of strings.md.
- [x] JuliaLang/julia#29167 - Update arrays.md for element-wise assignment
- [x] JuliaLang/julia#29700 - Fix RoundNearestTiesAway
- [x] JuliaLang/julia#30045 - fix JuliaLang/julia#30030, assignment expr as named tuple element value
- [x] JuliaLang/julia#30074 - Make `broadcast_axes` inferrable even if axes are of different types
- [x] JuliaLang/julia#29976 - Clarify the role of pivoting in QR factorization
- [x] JuliaLang/julia#30106 - Update typo in julia-syntax.scm
- [x] JuliaLang/julia#30111 - Install `ccache` on OSX Travis
- [x] JuliaLang/julia#30085 - Put boxed arguments in llvmcall into the correct addrspace
- [x] JuliaLang/julia#30112 - Fix deadlock caused by REPL blinking
- [x] JuliaLang/julia#30130 - varinfo() has been moved to `InteractiveUtils`
- [x] JuliaLang/julia#30146 - Fix indexing with Union{} array
- [x] JuliaLang/julia#30075 - stdlib-git: improve integration with git-external
- [x] JuliaLang/julia#30147 - document tab completion for dictionary keys
- [x] JuliaLang/julia#30128 - [AllocOpt] Track deleted instructions
- [x] JuliaLang/julia#30195 - Fix issue with Git Credential Manager for Windows
- [x] JuliaLang/julia#30049 - Two documentation updates
- [x] JuliaLang/julia#30209 - fix typo in `clipboard.jl`
- [x] JuliaLang/julia#29158 - Initializer the union selector of undefined upsilon nodes
- [x] JuliaLang/julia#30224 - Remove incorrect return in load_path_expand
- [x] JuliaLang/julia#30231 - Update libosxunwind to v0.0.5
- [x] JuliaLang/julia#30237 - doc: fix typo for named regex capture group
- [x] JuliaLang/julia#30221 - speed up (de)serialization of Base bits types in abstract containers
- [x] JuliaLang/julia#30261 - fix formatting in bullets for simdloop
- [x] JuliaLang/julia#30254 - fix JuliaLang/julia#30234, don't resolve bindings when tab-completing `using`
- [x] JuliaLang/julia#30265 - fix JuliaLang/julia#30122, bad type intersection involving NTuple and Vararg
- [x] JuliaLang/julia#30113 - avoid jl_arrayunset in dicts with bitstypes; add some more @inbounds
- [x] JuliaLang/julia#30016 - fix JuliaLang/julia#29995: latex printing of Markdown.HorizontalRule
- [x] JuliaLang/julia#30289 - Create new sparse matrix for R factor in sparse least square solve
- [x] JuliaLang/julia#29962 - `isdeprecated` should not resolve binding

Need manual backport:
- [ ] JuliaLang/julia#30242 - Add C-linkage to gc extensions for correct compiling in C++
- [ ] JuliaLang/julia#30251 - codegen,coverage: handle inlining info

Contains multiple commits, manual intervention needed:
- [ ] JuliaLang/julia#29721 - fixes for the runtime (interpreted intrinsics)
- [ ] JuliaLang/julia#30120 - Fix method ambiguities in SparseArrays

Non-merged PRs with backport label:
- [ ] JuliaLang/julia#30163 - [SparseArrays] Respect order of mul in (l)mul!(::Diagonal,::Sparse)

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.0")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30010#issuecomment-445292804) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e050ae9db753801041092ad45e3cb819ba457cf7/13ee84e_vs_a390279/report.md). cc @ararslan

**Comment by KristofferC** [comment]
PkgEval came back clean 🎉 

Just want to double check that the

```
["linalg", "arithmetic", "(\"sqrt\", \"UnitUpperTriangular\", 1024)"]
```

regression is noise:

@nanosoldier `runbenchmarks("linalg", vs = ":release-1.0")

If things are ok we should merge this and announce a testing period of a few days.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("linalg", vs = ":release-1.0")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30010#issuecomment-446461079) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a8aed636dc279acc884cda6c3d4208a6a82d3ce5/be79880_vs_a390279/report.md). cc @ararslan

**Review by fredrikekre — APPROVED** [review]

**Pull request merged**
