### PR TITLE
`first!`

### PR DESCRIPTION
**Pull request by palday**
This adds mutating `first!` and `last!` methods to match `first` and `last` and somewhat in the vein of `get!` or clobbering variants of `pushfirst!` and `push!`.

### CODE REVIEW

**Comment by ararslan** [comment]
...This is the first PR on April 1st (UTC) and it introduces a function called `first!`

image

**Comment by oscardssmith** [comment]
What's the value proposition here compared to `A[begin]=x`, `A[end]=x`?

**Comment by palday** [comment]
The same as the use of `first(v)` compared to `v[begin]`. 

It also makes some types of chaining easier:

```julia
julia> x = [1, 2]
2-element Vector{Int64}:
 1
 2

julia> y = first!(x,3) * 3
9
```

vs.

```julia
julia> x = [1, 2]
2-element Vector{Int64}:
 1
 2

julia> y = (x[begin] = 3) * 3
9
```

**Comment by StefanKarpinski** [comment]
IMO the second version is clearer.

**Comment by palday** [comment]
Since there seems to be a tiny bit of confusion (@nickrobinson251 @oscardssmith)...

This was meant to be half in jest (note the branch name and the title I gave the PR as well as the timing of opening it, as pointed out by @ararslan), but there are actually a few use cases for the type of functionality I proposed, i.e. something like a clobbering `push!` and `pushfirst!`. Note also that I was being a bit snarky about "what's the use of [non modifying] `first` and `last`?", but also quite serious: there are times I prefer `first(v)` or `v[begin]` for stylistic reasons, but having a `first` function is very convenient for higher order functions or broadcasting. Likewise for `first!` and `last!`.

Given @StefanKarpinski's feedback, I suspect the way to implement things would be to change my proposal to `setfirst!` and `setlast!` and implement his proposed variants as `first!` and `last!`. I do actually have a few things where I use the first or last element of a collection to do a computation and then immediately overwrite it with something else; in that case returning the old value while overwriting would actually allow condensing the relevant code. Whether or not it's good for readability is a different question...

**Pull request closed without merging**
