### PR TITLE
Ensure to call jl_islayout_inline() even in the case @assert is deactivated

### PR DESCRIPTION
**Pull request by petershintech**

### CODE REVIEW

**Comment by yuyichao** [comment]
Why?

**Comment by ararslan** [comment]
Thanks for the contribution @petershintech! It would be good to know what the justification for the change is. Could you provide some more information?

**Comment by jlapeyre** [comment]
See this thread: https://discourse.julialang.org/t/no-problem-with-more-than-500-assert-statements-in-v1-0-3/19255

I don't think this PR offers an advantage at the moment. But, if there is a mechanism to turn off assertions in the future, then the code will fail without this PR.

**Comment by KristofferC** [comment]
This is the docs for `@assert`:

>   │ Warning
  │
  │  An assert might be disabled at various optimization levels. Assert should therefore only be used as a
  │  debugging tool and not used for authentication verification (e.g., verifying passwords), nor should
  │  side effects needed for the function to work correctly be used inside of asserts.

So this LGTM.

**Comment by petershintech** [comment]
Yes. The problem is, this code depends on the side effect of the @assert statement to return a correct result.

**Pull request merged**
