### PR TITLE
support for Unicode 12.1.0

### PR DESCRIPTION
**Pull request by stevengj**
Via utf8proc 2.4.

This adds exactly one character: U+32FF SQUARE ERA NAME [REIWA](https://en.wikipedia.org/wiki/Reiwa).

### CODE REVIEW

**Comment by stevengj** [comment]
Travis OSX failure is unrelated `failed running test FileWatching`.

**Comment by stevengj** [comment]
I'll merge in a day or so if there are no objections.

**Comment by PallHaraldsson** [comment]
Should we backport this to Julia 1.1.1 (too late?)? As a possible PR stunt to get the Japanese [emperor] exited for Julia?

**Comment by StefanKarpinski** [comment]
No, this is a feature.

**Comment by PallHaraldsson** [comment]
Ok, understand for 1.1.1. But not to late for 1.2 as its not released and this a trivial change.

**Comment by StefanKarpinski** [comment]
Every change has risk. What's the upside? One extra character? It's up to @KristofferC.

**Comment by KristofferC** [comment]
I think `SQUARE ERA NAME REIWA.` has gotten too much work dedicated to it already ;)

**Comment by antimon2** [comment]
I sent [PR](https://github.com/JuliaStrings/utf8proc/pull/156) to `utf8proc` to make Julia support 'U+32FF'.
But I don't need the new character so far as my Julia programming, I'm only interested in technical feature.
I don't need that feature in the next release of Julia immediately. If necessary, I use development build of Julia at my own risk.

**Pull request merged**
