### PR TITLE
dlopen: eliminate internal soname mapping

### LINKED ISSUE #13719: Intermittent segfault in libdl test on linux64 buildbots
See recent failures at http://buildbot.e.ip.saba.us:8010/builders/build_ubuntu12.04-x64?numbuilds=250 and http://buildbot.e.ip.saba.us:8010/builders/build_centos7.1-x64?numbuilds=250

```
    From worker 3:       * enums                 in   1.33 seconds, maxrss 1165.46 MB
    From worker 2:       * misc                  in  24.35 seconds, maxrss 1406.89 MB
    From worker 2:       * i18n                  in   0.03 seconds, maxrss 1406.89 MB
    From worker 2:       * workspace             in   0.35 seconds, maxrss 1406.89 MB

signal (11): Segmentation fault
_IO_feof at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x7f8cf8b107dd)
anonymous at essentials.jl:116
cd at file.jl:22
jl_apply_generic at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f8cf8b0d7a3)
unknown function (ip: 0x7f8cf8b0cbe1)
unknown function (ip: 0x7f8cf8b0e038)
unknown function (ip: 0x7f8cf8b0e1ee)
unknown function (ip: 0x7f8cf8b219df)
unknown function (ip: 0x7f8cf8b222a9)
jl_load_file_string at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
include_string at essentials.jl:116
jl_apply_generic at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
include_from_node1 at ./loading.jl:387
jl_apply_generic at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
runtests at util.jl:179
jlcall_runtests_22758 at  (unknown line)
jl_apply_generic at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
anonymous at /home/centos/buildbot/slave/build_centos7_1-x64/build/test/runtests.jl:36
jl_f_apply at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
anonymous at multi.jl:898
run_work_thunk at multi.jl:651
jlcall_run_work_thunk_22669 at  (unknown line)
jl_apply_generic at /home/centos/buildbot/slave/build_centos7_1-x64/build/usr/bin/../lib/libjulia.so (unknown line)
anonymous at multi.jl:898
unknown function (ip: 0x7f8cf8b13dc8)
unknown function (ip: (nil))
    From worker 2:       * libdl                Worker 2 terminated.
ERROR (unhandled task failure): EOFError: read end of file
    From worker 4:       * int                   in   1.33 seconds, maxrss  156.14 MB
    From worker 4:       * intset                in   0.75 seconds, maxrss  156.14 MB
    From worker 4:       * floatfuncs            in   1.66 seconds, maxrss  156.14 MB
    From worker 3:       * cmdlineargs           in  28.07 seconds, maxrss 1175.49 MB
    From worker 3:       * fft                   in  24.96 seconds, maxrss 1226.80 MB
    From worker 4:       * parallel             
    From worker 4:   in  35.81 seconds, maxrss  156.14 MB
    From worker 3:       * dsp                   in  15.16 seconds, maxrss 1229.05 MB
    From worker 4:       * examples              in  22.73 seconds, maxrss  191.95 MB
Exception running test libdl :
ProcessExitedException()
ERROR: LoadError: Some tests exited with errors.
 [inlined code] from error.jl:21
 in anonymous at /home/centos/buildbot/slave/build_centos7_1-x64/build/test/runtests.jl:64
 in cd at file.jl:22
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:384
 [inlined code] from ./operators.jl:313
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading /home/centos/buildbot/slave/build_centos7_1-x64/build/test/runtests.jl, in expression starting on line 13
```

### PR DESCRIPTION
**Pull request by vtjnash**
This should now be handled by external packages (e.g. https://github.com/JuliaLang/BinDeps.jl/pull/277), where we can handle errors appropriately and cache the results to ensure they are observable and constant.

fix #13719

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you'll need
```diff
diff --git a/test/libdl.jl b/test/libdl.jl
index ffeeed83f4..c189616013 100644
--- a/test/libdl.jl
+++ b/test/libdl.jl
@@ -183,8 +183,4 @@ let dl = C_NULL
     end
 end

-if Sys.KERNEL in (:Linux, :FreeBSD)
-    ccall(:jl_read_sonames, Void, ())
-end
-
 end
```

**Comment by vtjnash** [comment]
Oops, I had that, then pushed the wrong commit.

**Comment by ararslan** [comment]
Is it possible to deprecate this rather than a hard break?

**Comment by tkelman** [comment]
and will this break benchmarking or do things that haven't been widely tested need to be released?
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by tkelman** [comment]
Will this result in visible changes to the way the Julia `Libdl.dlopen` handles sonames?

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/22828#issuecomment-315602367):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/8e9d34c6c3659b94bf19a9864c76f31a31bcf1ef/523f654_vs_3ff6eac/report.md)
cc @ararslan

**Comment by vtjnash** [comment]
> Is it possible to deprecate this rather than a hard break?

Everything is possible, but I changed BinDeps to stop using this code a few weeks ago, so there wouldn't seem to be any consumer of this code even if I did the work to add a deprecation. I just realized it still needed a release tag however (https://github.com/JuliaLang/BinDeps.jl/compare/264e086062f3c39adba7997f187bd54bc0e6b218...e2553e57468d5692f7e13f45ddc888670bcbbfda)

> Will this result in visible changes to the way the Julia `Libdl.dlopen`

Yes, but since the ecosystem uses BinDeps, this code path wasn't really being used and didn't have any tests.

**Comment by tkelman** [comment]
There are quite a few raw uses of dlopen without going through BinDeps. The BinDeps version of the code is also largely untested.

**Comment by tkelman** [comment]
and what about ccall without an soname? that's harder to search for, but BinDeps usage is not universal

**Comment by vtjnash** [comment]
> and what about ccall without an soname

then you'll now either need to install the correct (usually `-dev`) package, compile the library yourself (not recommended), or use a distro that doesn't have this issue (e.g. not debian/ubuntu-like, afaik)

**Comment by yuyichao** [comment]
FWIW, there are many base libraries that do not set the correct soname.
Only developer oriented distros installs the unversioned libraries by default, it includes everything other than Arch, LFS and maybe gentoo.

**Review by tkelman — CHANGES_REQUESTED** [review]
don't think we should delete this functionality from ccall and dlopen, it's useful outside of bindeps.

**Comment by vtjnash** [comment]
Just to clarify the purpose of this PR. The functionality in here that I'm deleting is poorly tested, fails occasionally and unpredictably (we silently hide this during CI runs, which ends up working OK, since we don't actually use or test for it), and in general this is just a bad (unreliable) way of managing dependencies. The code I added to BinDeps solves all of those issues. If you want to keep this code, you should add tests for it. But, I'm getting rid of it.

**Comment by tkelman** [comment]
Adding code to BinDeps doesn't fix usage of this via direct ccall or dlopen of a library name without an soname. That doesn't go through BinDeps and would be broken by this.

**Comment by ararslan** [comment]
Is there any estimate of how often this is used in packages and/or "in the wild"?

**Comment by vtjnash** [comment]
This will fix #6742, once the build system changes for this PR are also integrated

**Comment by vtjnash** [comment]
@tkelman Our build system is fixed now not to want this hack (as demonstrated by our working macOS Travis build, which used to use a different, CI-specific hack), so I'd like to merge this now to finish removing it from Linux in favor of predictable builds.

**Comment by tkelman** [comment]
"usage of this via direct ccall or dlopen of a library name without an soname" is still a valuable feature that this would be deleting without any replacement

**Comment by StefanKarpinski** [comment]
Can you elaborate? Valuable for what? Why do we need that?

**Comment by tkelman** [comment]
Being able to use ccall or dlopen on a library without having to include the full numbered soname

**Comment by nalimilan** [comment]
OTOH libraries are supposed to break API when they change SONAME, so why would you load a library without specifying its SONAME?

**Comment by tkelman** [comment]
The same reason you might want to link to them without having to specify the soname, especially if you don't know or care what it is. Or write code that works across a range of old and new linux distros in a single line instead of needing to have an soname lookup table and search in user code. Having the julia loader do that resolution for you, even if there are supposedly some bugs with it (of which an example failure case hasn't been provided despite being requested over in the bindeps pr), is more convenient than needing to know the soname or install a -dev package (which non-admin users often won't be able to do without having to rebuild many things from source) to dynamically load and call functions in a library on linux.

**Comment by tkelman** [comment]
Hardly any downstream projects ever write down specific sonames of their dependencies that they require. The naming conventions are often platform-specific, and "supports all versions" is at least a decent default to work for if you don't have any other information.

**Comment by ihnorton** [comment]
> In general I think it's good practice to push people into thinking about what versions they support

I'm a little unclear on what problem this point of view really solves. Absent some tooling to do it automatically (which I don't think we have), 99% of package developers are never going to actually audit their `ccall`s. They are just going to pick whatever version they see first that seems to work, and IIUC they'll still only get errors at runtime if they got it wrong. So forcing people to pick an SONAME seems to add an extra layer of ceremony for uncertain benefit.

That said, if the code removed here is wrong and the code in BinDeps does the correct thing, why don't we move it to stdlib?

**Comment by vtjnash** [comment]
> even if there are supposedly some bugs with it (of which an example failure case hasn't been provided despite being requested over in the bindeps pr)

It looks like this issue was originally reported by tkelman back in https://github.com/JuliaLang/julia/issues/13719#issuecomment-161865318, apparently he was only seeing it locally and on buildbots that we no longer have.

**Comment by vtjnash** [comment]
> why don't we move it to stdlib as the convenience

I don't think we want to move BinDeps into stdlib

**Comment by ihnorton** [comment]
I meant the lookup function, of course... Seems like a fairly useful, system-level functionality.

**Comment by vtjnash** [comment]
As I said, I would prefer not to move BinDeps into Base, but the proper way to handle this is a bit coupled to how you intend to get and manage the system package (this code path isn't active otherwise), so I'm not sure it makes sense to separate from there. We perhaps should move this into `Libdl.find_library`, but I'm not totally convinced we should keep that function around either (I assume BinDeps2 will be better at handling this and replace it entirely).

So, I plan to merge this soon, unless there's any new review comments.

To answer @ihnorton's questions:

> Absent some tooling to do it automatically (which I don't think we have)

That's actually what the code in BinDeps does (if you don't have the `-dev` package installed, but that's an entirely separate issue). That's actually been true for a long time, we just didn't use to have error handling implemented (because it used to call this code, and this code just silently hides the errors that we used to see periodically on CI as existing in this code).

> And IIUC they'll still only get errors at runtime if they got it wrong.

That's what this PR removes. BinDeps already disabled this codepath, such that once you have the package working, changes to the system (`apt upgrade` or whatever) won't break or corrupt your Julia packages that configured themselves to use the old version.

**Comment by ihnorton** [comment]
I certainly don't want to hold up this PR, because it seems I'm being unclear... But just to reiterate: what I'm asking is whether, in addition to this PR, we can take the code to do `ldconfig` lookup, which was added to BinDeps in: https://github.com/JuliaLang/BinDeps.jl/pull/277

... and put it in `Base.Libdl` or stdlib instead.

Because I think such a function mapping `libname` -> `libname.so.867.5309` is useful outside of BinDeps and could/should be provided once, by core Julia, rather than having multiple reimplementations (not everyone uses, or will want to use, BinDeps). Much like Julia provides various other platform abstractions for relatively low-level functionality.

**Comment by tkelman** [comment]
My objection to this remains - if `ccall` and `dlopen` no longer work without dev packages installed or manually listing the soname, this is a regression in usability of C FFI. Wherever that lookup code exists, moving it out of the path that `ccall` and `dlopen` leverage automatically seems to be removing a convenient and valuable feature without a very strong justification for why it shouldn't be used by default. A past implementation having some rare, difficult-to-reproduce bugs in corner cases doesn't mean the functionality should be deleted entirely.

**Comment by vtjnash** [comment]
> A past implementation having some rare, difficult-to-reproduce bugs in corner cases doesn't mean the functionality should be deleted entirely.

The past implementation used to fail pretty often on CI, so rather than fix it at the time (which was deferred until this PR, while waiting for the other pieces to come into place), I fixed our tests to silently ignore the failures and pass anyways. Please stop insisting that this feature works when we have never had any tests for it (and can't write any, because we know they would often fail in CI). The failure was neither rare nor difficult-to-reproduce (just run the test suite on a system with < 8GB RAM)

> in addition to this PR

Sure, I would not oppose someone who wanted to move that code from BinDeps into Base in a later PR. I think it would be better to do that in the context of solving a specific problem though, rather than as a hypothetical in this PR.

**Comment by tkelman** [comment]
The feature does work, at least enough of the time for a few packages to rely on it. For example LightXML.jl, which has never used BinDeps to define its ccalls. Aside from unrelated deprecations, that package functions on master and does not work on this branch because of the feature that's being removed by this PR. I doubt it's the only example of a ccall or dlopen without an soname.

**Comment by vtjnash** [comment]
Of course, it'll never fail in package tests / unit tests, this code (by it's very design) would only frequently fail during integration tests or after processing data. For example, if you first did some calculation that uses a fair amount of memory, it would usually crash when you tried to next load an XML file.

**Comment by tkelman** [comment]
Don't think that's been reported as such. But the point still stands - the code not having tests and being unreliable in some situations is unfortunate, but not a very good reason to completely remove the existing feature from ccall and dlopen. If the newer code is better and has tests, then should replace the functionality with the new version, not make ccall and dlopen less capable.

**Comment by vtjnash** [comment]
> If the newer code is better and has tests, then should replace the functionality with the new version, not make ccall and dlopen less capable.

Yes. Part one of that statement is already done (The better version is implemented in https://github.com/JuliaLang/BinDeps.jl/pull/277 and tested by existing tests, as can additionally be verified visually by checking the verbose log and confirming that it found the library through searching ldconfig, not the filesystem). Part 2 then is to replace the functionality – delete the broken code – which is this PR.

Long ago, I had worked on some designs for extending `DL_LIBRARY_PATH` to supplant this code with more flexibility in Base. But then `BinDeps.jl` was created, and it solved this problem with more flexibility, reliability, and extensibility.

So now all that remains, is to get rid of this broken legacy stuff and encourage people to use the new fangled mechanism (aka BinDeps) which has now existed for 5ish years.

**Comment by tkelman** [comment]
To be clear, by "the functionality," I mean ccall and dlopen working without needing an soname. It's rather user unfriendly to force going through a BinDeps lookup for `ccall((..., "libxml2"), ...)` to work. You aren't replacing that functionality within ccall/dlopen, you're deleting it and suggesting users should have to do additional external work instead of ccall/dlopen doing it for them. That's what makes this an undesirable regression.

**Comment by vtjnash** [comment]
> That's what makes this an undesirable

I disagree. I used to have a design (I think in a Google doc somewhere, it's that old) that improved and tested this functionality within Base. But with the majority of packages using BinDeps, it was deemed actively counter-productive to split the design doc into including support for both a recommended practice ("just configure BinDeps") and bad practice ("just let ccall do magic").

> The feature does work, at least enough of the time for a few packages to rely on it. For example LightXML.jl

> [it] just works

Except that's not how it's done in LightXML.jl, since that doesn't even work there. There's a a partial reimplementation of BinDeps for Windows. But it's also entirely missing support for bare Posix (largely understandable, since it's a pre-requisit of many programs, so installations of Linux almost always have some version of libxml2.so installed. But it's not required by, for example, the `ubuntu-minimal` package. While converting to use BinDeps would have solved that.).

So yes, I could implement some nonsense like this in `ccall`, but since – as it turned out years ago – nobody should be using it, that's pretty pointless now.

**Comment by tkelman** [comment]
Assuming some version of the library is already installed, but not having to care about the soname, is how a lot of people and tutorials begin using ccall interactively, and it contributes quite a bit to the ease of use. If every ccall tutorial has to start with a BinDeps lookup and a platform/distro-dependent aside about sonames, you've exhausted the attention span of a lot of people who just want to call code from a C library and have Julia do the hard parts.

**Comment by tkelman** [comment]
CodecZlib (and I believe all of its predecessor gzip wrapper packages) also work this way and have not needed to go through BinDeps on master or prior releases but would need to do so here. Being able to avoid BinDeps once in a while is seen as desirable to most people, not a bug or misfeature.

**Comment by vtjnash** [comment]
`CodecZlib` hardcodes the SONAME-mangled name on PE-COFF/Windows, what's odd about simply adding one more case to that code to also cover ELF-based systems? Most of the time, you should probably just be installing the `-dev` package at the start of the tutorial.

**Comment by tkelman** [comment]
Installing the -dev package introduces an "ask your sysadmin or compile it from source yourself" problem we didn't have before, at least for libraries where the non-dev version is generally present.

I think it's user hostile to remove a feature from ccall that people have been using to simplify their code and force them to do additional work that Julia has been doing for them. It's more complicated than "one more case" for any library that has multiple soname versions in common usage.

**Comment by ihnorton** [comment]
x-ref https://github.com/JuliaLang/julia/issues/949

**Comment by vtjnash** [comment]
Yes, we were exploring multiple solutions at that time. Eventually the ecosystem consolidated around using BinDeps and this vestigial code was left behind.

**Comment by tkelman** [comment]
It's hardly vestigial when it's used and useful in all the above ccall-without-BinDeps situations, all of which would be made noticeably less convenient by removing this capability.

**Comment by vtjnash** [comment]
> It's hardly vestigial when it's used and useful in all the above ccall-without-BinDeps situations, all of which would be made noticeably less convenient by removing this capability.

You're about 4 years too late to stop BinDeps from becoming the de facto implementation of correct ccall usage. Sorry, but if you wanted this design, you would have needed to push for it back then. But since all of the examples you gave are of broken packages, it's pretty obvious why we eventually adopted BinDeps (despite its quirks) and stopped pursuing this more complicated design.

**Comment by ararslan** [comment]
To me this is mostly orthogonal to BinDeps. `ccall` has other uses, and I agree with Tony that this makes interactive and exploratory use of `ccall` far less pleasant, which is quite unfortunate given how cool a feature `ccall` is in Julia.

**Comment by tkelman** [comment]
They aren't broken packages, currently. They would be broken by this PR's removal of the feature they rely on.

**Comment by StefanKarpinski** [comment]
While I'm  sympathetic to wanting to delete code, I don't understand why it's urgent to remove this code. What harm is it doing? Does deleting it enable anything we can't otherwise do?

**Comment by vtjnash** [comment]
It needs to be merge in advance of feature freeze so we don’t get stuck with it (code that we can’t test or fix) for 1.0.

**Comment by tkelman** [comment]
"can't fix" is an awfully strong statement. Couldn't the better implementation replace this one without changing the way ccall works in some 1.x release, and no one would notice?

**Comment by vtjnash** [comment]
Seeing no alternatives posed, or tests implemented, and having given fair warning, and wanting to finally close a fairly old bug report, I've merged this. Sometimes deleting half broken functionality is the only way to motivate improvement. Sometimes it'll just turn out that that code wasn't that necessary or useful, or that having simple, reliable models mattered more anyways.

**Comment by ararslan** [comment]
As far as I can tell no one in this thread was supportive of this change, and Stefan's question of "what harm is it doing" was not actually addressed.

**Comment by tkelman** [comment]
Deleting a used, and useful, feature is not an improvement. It's just vindictive. You've given zero evidence that keeping the feature and improving it later hurts anything. Deleting the feature now serves no purpose.

**Comment by JeffBezanson** [comment]
Wouldn't it fix the out-of-memory problem if we called `jl_read_sonames` at or near process start rather than on demand?

**Comment by vtjnash** [comment]
There’s a lot of ways to change this feature - we just don’t need this complexity here as we already have several alternatives (BinDeps, symlinks, and computed sonames) that are much more widely used and enjoy cross-platform applicability.

**Comment by tkelman** [comment]
It's less than 150 lines of code, hardly the most complex feature. Multiple packages have been making good use of it and are now broken on master for no reason, with no deprecation. The bug that this closed hasn't been reported reliably or recently. Symlinks or computed sonames add unnecessary complexity downstream across every package that would prefer to not worry about linux-specific library versioning details.

Making a breaking change by removing a feature generally calls for a mention in news, and a stronger justification than one person not liking it.

**Comment by brenhinkeller** [comment]
This is terrible! I'm probably going to sound unreasonably irritated, but this is something like the tenth case I've found in the switch to 1.0 where my code has been broken because someone decided to remove imperfect-but-workable functionality for no reason other than ideological purity. Congratulations, @vtjnash, now all your tests pass but you've broken actual users code and wasted my time.

Can't agree strongly enough with @tkelman "Deleting a used, and useful, feature is not an improvement. It's just vindictive."

**Pull request merged**
