### PR TITLE
duplicate invoke expr during call method splitting

### PR DESCRIPTION
**Pull request by vtjnash**
With the new gc-rooting pass, this should generate better code over the copying of just the method instance.

### CODE REVIEW

**Comment by quinnj** [comment]
Will this help the inlining issue I reported in #22097?

**Comment by vtjnash** [comment]
This does the transform mentioned at https://github.com/JuliaLang/julia/issues/22097#issuecomment-305012702 so it no longer needs to be done manually.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22481#issuecomment-310731715) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/88f4bb96be0affea11a7fc7673e9a0128f81d734/bdd5477_vs_5176ded/report.md). cc @jrevels

**Comment by vtjnash** [comment]
forget to update the inliner heuristics for the new code structure. lets try that again: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22481#issuecomment-310864487) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e7a918a93ce904d04e61f2ed0ea4c68290a17d03/3829ef2_vs_b12bac5/report.md). cc @jrevels

**Comment by vtjnash** [comment]
Alright, the performance changes here are now unhelpfully coupled due to its affect on inlining. But I don't see anything that seems broken.

**Comment by tkelman** [comment]
what does "unhelpfully coupled" mean?

**Comment by KristofferC** [comment]
That performance changes are because of the different inlining heuristics and not what the PR is actually fixing?

**Comment by tkelman** [comment]
How about adding a test for the fix then?

**Comment by timholy** [comment]
The `linalg/givens` failure was one I hit in #22210 and is the issue addressed by #22516; I'm surprised the last commit doesn't fix it, but rebasing on #22516 might be an easy fix.

**Comment by timholy** [comment]
Oh, and the regressions in the `"issorted"` benchmarks are presumably fixed (twice :smile:) in #22210; I don't see anything here performance-wise that you need to worry about. Nice improvements here!

**Comment by vtjnash** [comment]
> what does "unhelpfully coupled" mean?

Almost all of the difference are attributable to getting the inlining decision wrong (#22210), but neither the old nor the new is consistently better. But some of the differences (at least one improvement – raytrace) are real.

> How about adding a test for the fix then?

The PR doesn't fix anything. It's just a more concise and readable way to implement this, and moves us closer to a very-linear-ir (so that flipping that switch will have a smaller impact).

**Comment by vtjnash** [comment]
Removed the inlining changes, so hopefully this PR will not be unhelpfully coupled anymore: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22481#issuecomment-311159872) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f3bef8a4f4fdd7b2d085320ee7e7f3c59a07bd86/c019c6d_vs_2796b40/report.md). cc @jrevels

**Comment by vtjnash** [comment]
Looks excellent. Will merge tomorrow if there's no comments.

**Comment by tkelman** [comment]
many of the nullable operations got considerably slower, is this inhibiting simd?

**Comment by vtjnash** [comment]
Those functions don't run this codepath, and are generating the same IR when I examined them locally. Not sure why they are showing up noisy here.

**Comment by martinholters** [comment]
They're not the usual suspects for being (that) noisy, so @nanosoldier `runbenchmarks(ALL, vs = ":master")` again.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22481#issuecomment-311572195) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/af79fdbd5f86f67cc7b2db47a3b3302457120ed8/047a67b_vs_f4501ff/report.md). cc @jrevels

**Comment by tkelman** [comment]
Good enough for me, sqrtm is a frequently noisy one

**Comment by Keno** [comment]
The nullable operations had gotten faster on master.

**Comment by tkelman** [comment]
nanosoldier should be building the merge commit though so that shouldn't make a difference

**Pull request merged**
