### PR TITLE
Allow `Time`s to be rounded to `Period`s

### LINKED ISSUE #43284: Cannot round Time to Period
The documentation for `round` says

>   `round(dt::TimeType, p::Period, [r::RoundingMode]) -> TimeType`
> 
>  Return the `Date` or `DateTime` nearest to `dt` at resolution `p`. [...] For convenience, `p` may be a type instead of a value: `round(dt, Dates.Hour)` is a shortcut for `round(dt, Dates.Hour(1))`.

However it seems `Time` values (which are `TimeType`) cannot be rounded to `Period` values:

```julia
julia> round(Time(now()), Second)
ERROR: MethodError: no method matching floor(::Time, ::Second)
Closest candidates are:
  floor(::Union{Day, Week, TimePeriod}, ::T) where T<:Union{Day, Week, TimePeriod} at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:110
  floor(::Union{Day, Week, TimePeriod, TimeType}, ::Type{P}) where P<:Period at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:285
  floor(::DateTime, ::TimePeriod) at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:81
  ...
Stacktrace:
 [1] floorceil(dt::Time, p::Second)
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:196
 [2] round(dt::Time, p::Second, r::RoundingMode{:NearestTiesUp})
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:235
 [3] round(x::Time, ::Type{Second}, r::RoundingMode{:NearestTiesUp}) (repeats 2 times)
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:291
 [4] top-level scope
   @ REPL[4]:1
```

This seems related to https://github.com/JuliaLang/julia/issues/37738 but it's not clear to me what that issue is about.

### PR DESCRIPTION
**Pull request by TheLostLambda**
Finally closes #43284

This is my first contribution to Julia, so let me know if I've messed anything up!

### CODE REVIEW

**Comment by TheLostLambda** [comment]
Test failures appear unrelated to my change and seem to be either random failures or failures on the current `master`?

I'll update my branch just in case that helps!

**Review by omus — APPROVED** [review]
The tests for `Dates/rounding` are passing and the failure is unrelated

**Comment by IanButterworth** [comment]
Is this a bugfix or new feature? i.e. either needs News or backport

**Comment by TheLostLambda** [comment]
I don't know 100% either, though I'd lean towards feature? Since it's added some new methods and enabled new rounding of types?

Open to people disagreeing though! Since it seemed like a missing bit of functionality and could reasonably be thought of as a bug.

Where would I write something for NEWS?

**Comment by IanButterworth** [comment]
I'll mark it for triage to decide whether it's a bugfix or feature

**Comment by omus** [comment]
It was functionality which should have been added when `Time` was introduced but I would call this a feature and not a bugfix.

**Comment by DilumAluthge** [comment]
@IanButterworth Does this still need discussing in a triage call? If so, I'll open a new issue. I think people usually filter just for open issues when they are filtering for the triage label.

**Comment by oscardssmith** [comment]
Triage says this is a feature and needs news (and no backport).

**Comment by LilithHafner** [comment]
The most important place to document when this was introduced is in the doc-string of the method this PR added, as a compat annotation.

**Pull request merged**
