### PR TITLE
🤖 Bump the Statistics stdlib from 4b3ef9a to 54f9b0d

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Statistics
Branch: master
Old commit: 4b3ef9a
New commit: 54f9b0d
Bump invoked by: @DilumAluthge

```
$ git log --oneline 4b3ef9a..54f9b0d
54f9b0d CI: Standardize the workflow for testing and changing the UUID (#78)
ba24318 Fix detection of NaN in median() (#73)
55d93f7 Fix NaN and missing detection in quantile() (#72)
fadeeee fix handling of Missing in cor (#74)
862798b Fix CI badge
27a63ae change real to float in cor of a single collection (#61)
7b56a27 In var, don't compute the mean if provided (#68)
ba90d86 Fix CI (#64)
698530b Add GitHub action for CI (#62)
05f09fe Delete .travis.yml
7a0c0d1 Clarify "IID" (#58)
```

### CODE REVIEW

**Review by bkamins — APPROVED** [review]
I think it is OK to make this bump. We have still open https://github.com/JuliaLang/Statistics.jl/pull/70 in a related area to the changes this bump would introduce but it is independent.

However, my question is what is the release policy of Statistics.jl (and in consequence synchronization policy with Julia Base) as I am not aware of standards we use here?

**Comment by DilumAluthge** [comment]
As I understand it, there is no separate release cycle for the `Statistics` stdlib. That is, it is fixed to the Julia release cycle.

@andreasnoack @nalimilan Does that sound correct?

**Comment by DilumAluthge** [comment]
See also this comment by @StefanKarpinski regarding the release cycle of external stdlibs: https://github.com/JuliaLang/BumpStdlibs.jl/issues/31#issuecomment-747477515:
> My workflow has generally been to bump stdlibs to Julia master first and only after they've proven to be unproblematic there for a while, tag a release of the stdlib.

**Comment by DilumAluthge** [comment]
@nalimilan Can you take a look at this PR and make sure that the bump is okay?

We can always revert this PR if need be.

**Pull request merged**
