### PR TITLE
Bump tolerance a bit in stressful test of eigs on matrix with many repeated eigenvalues.

### PR DESCRIPTION
**Pull request by andreasnoack**
Should make #23068 unnecessary

### CODE REVIEW

**Comment by tkelman** [comment]
Why did adding other tests earlier in the file change this? Is there some global state in arpack that we aren't resetting properly?

**Comment by mschauer** [comment]
The starting vector insight ARPACK is randomly sampled which introduces some call order dependence.

**Comment by andreasnoack** [comment]
As @mschauer said. It suggests that we might want to provide the random starting vector such that the result of `eigs` would always be deterministic conditionally on `srand`.

**Comment by tkelman** [comment]
aren't we providing a default though? https://github.com/JuliaLang/julia/blob/2b983d41f064c39c0b73f6c7695cc13e0de45c03/base/linalg/arnoldi.jl#L171

**Comment by mschauer** [comment]
Thats a vector of length zero which gets replaced by an empty vector in https://github.com/JuliaLang/julia/blob/a6f1e96feae1e37365543b9f5de378d79a24ddd2/base/linalg/arpack.jl#L23 and filled in ARPACK because info is set to 1.

**Comment by tkelman** [comment]
Ah right thanks. We should probably take control over that random filling so the Julia RNG is responsible for it (separately, this PR as a band-aid is fine for now)?

**Comment by andreasnoack** [comment]
Should also cross reference https://github.com/JuliaLang/julia/issues/4246 which is the same issue caused by accidentally using a too small tolerance.

I think I kind of understand what is going on here but it is puzzling that we only see the issue when using OpenBLAS with the Sandybridge kernels. I tried a lot of repetitions on the same machine with the OpenBLAS Nehalem kernels and with MKL and neither of them gave a single error. However, it seems that the error can be provoked on any system by lowering the tolerance. The good part is that people rarely needs to compute the eigenvalues of the identity matrix in real world problems 😛

**Pull request merged**
