### PR TITLE
Revert "Revert "Merge pull request #15860 from JuliaLang/kf/tracing""

### PR DESCRIPTION
**Pull request by Keno**
This was silently reverted by #15779.

### CODE REVIEW

**Comment by vtjnash** [comment]
i'm concerned about the usage of this now that i can see https://github.com/Keno/Gallium.jl/commit/a14a67b8ba2440b1d30e78fc819080c7e59f452e. the one thing you must not do with the returned lambda object is look at its llvm object (there are a few code paths where that can assert). so i don't see how it can be safely used for debugging.

also you need to update jltypes.c now

also, 810e53ff5020ab3bcd455dfd0b3e560145889396 was unrelated, but I'm not sure it's a good idea to assume without testing that `jl_tparam0` in `jl_get_llvmf` is a datatype.

**Comment by Keno** [comment]
> i'm concerned about the usage of this now that i can see Keno/Gallium.jl@a14a67b. the one thing you must not do with the returned lambda object is look at its llvm object (there are a few code paths where that can assert). so i don't see how it can be safely used for debugging.

Return lambda object where?

> also you need to update jltypes.c now

in what way?

> also, 810e53f was unrelated, but I'm not sure it's a good idea to assume without testing that jl_tparam0 in jl_get_llvmf is a datatype.

Adding an assert to this extent seems reasonable.

**Comment by vtjnash** [comment]
from cache_method / `jl_linfo_tracer`

> in what way?

there's an extra field in jl_method_t, it needs to be added to the description of the type

**Comment by Keno** [comment]
Which code path is it that would assert. Would it be reasonable to add an extra tracing flag to the lambda info that gets triggered when that lambda info gets compiled? That flags could be set from `jl_linfo_tracer`, and only set the breakpoint after the thing is actually compiled?

I'm not sure I want this flag to be accessible from julia.

**Comment by vtjnash** [comment]
you can give it a name of `""` to make it harder to access

that's sounds like a possibility. we might be able to attach `NotifyObjectEmitted` to Julia? that's a tricky time too though, since calling `jl_get_llvmf` in there will hit llvm assertions (recursive compilation and double-finalizing the RTDyld)

codegen may decide to assert if inference hasn't decided to finish yet (for example, if `cache_method` is called from within inference), or if the function is being compiled recursively and forms part of a cycle (because it would force resolution of the function before the rest of the cycle was ready)

**Comment by Keno** [comment]
We could record all traced linfos in `NotifyObjectEmitted` and delay calling the callback until we're out of the JIT again, no?

**Comment by vtjnash** [comment]
that sounds plausible. i don't know off-hand how many entry points we have into the JIT, but I don't believe it could be that many (c-function, c-alias, and fptr?)

**Comment by Keno** [comment]
Don't they all go through `getAddressForFunction`?

**Pull request merged**
