### PR TITLE
Upgrades 7z version on Windows to v16.04

### PR DESCRIPTION
**Pull request by bmharsha**
This code change makes sure 7z v16.04 (Instead of v9.20) is embedded within Windows Julia binary. v16.04 is the latest stable version of 7z at the moment.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Some antivirus scanners have complained about an old version that is not supported - hence the need to update.

**Review by ararslan — APPROVED** [review]
LGTM and AppVeyor seems to agree

**Comment by ihnorton** [comment]
I thought that signing solved this long ago, once the signing cert got enough reputation? (note though, IIRC, the whole package needs to be signed -- not just the inner installer)

Good to update anyway, of course.

**Comment by tkelman** [comment]
I wouldn't backport this unless nightly binaries built with it have been *very* thoroughly tested against all packages that make use of 7zip on windows. WinRPM and a few others had been picky and wouldn't work correctly with recent 7zip versions last I tested.

**Comment by ararslan** [comment]
Thanks for the heads up. I've reverted the commit on my backports branch.

**Pull request merged**
