### PR TITLE
Use a nonstandard name to record the artifacts our fake JLLs came from

### PR DESCRIPTION
**Pull request by staticfloat**
This avoids `Pkg` from finding the `Artifacts.toml` for these stdlibs
(which already have their binaries bundled with Julia, so no need to
download the actual artifacts) while still allowing other tools (such as
BinaryBuilder) to find the binaries in a structured manner.

Fixes https://github.com/JuliaLang/julia/pull/38070#issuecomment-714634284

### CODE REVIEW

**Comment by yuyichao** [comment]
It's unclear to me what these files are supposed to do. Any use of these are automatically wrong since these are not necessarily where the binaires come from.

**Comment by staticfloat** [comment]
> Any use of these are automatically wrong since these are not necessarily where the binaires come from.

The use of these is for things like BinaryBuilder and PackageCompiler, which needs to find e.g. the (exact) version of `libmbedtls` that shipped (or was supposed to ship, barring unusual configurations such as `USE_SYSTEM_X=1` or `USE_BINARYBUILDER_X=0`) with that version of Julia.  If the user has overridden their mbedtls version then the tools that use these files won't work, that is true, but it doesn't really make sense to try to get BinaryBuilder to use system or custom-compiled stdlib binaries anyway, so I don't think it should matter at all.

**Comment by yuyichao** [comment]
> but it doesn't really make sense to try to get BinaryBuilder to use system or custom-compiled stdlib binaries anyway, so I don't think it should matter at all.

The binary itself is available and it's path is exported from the corresponding JLL package. There should not be a need to have a independent entry for that.
I also don't see why you are saying compiling custom sysimg doesnt matter for non official binary.

Note that this is about the file included in the distributed result. Having a file like this to store information (which already exist elsewhere) is fine, but it must not be relied on at runtime. In another word, if this is just a file that other tools that is only supposed to work for the official binary, like the binary builder but not including custom sysimg, it's fine to include a file like this in the repo. However, this file must not be installed since any use of that file in the installed version is wrong.

**Comment by staticfloat** [comment]
> The binary itself is available and it's path is exported from the corresponding JLL package

That's insufficient; we need the full artifact.  Header files, static libraries, etc...

> I also don't see why you are saying compiling custom sysimg doesnt matter for non official binary.

I did not say that.

> However, this file must not be installed since any use of that file in the installed version is wrong.

When you say "this file" do you mean the `StdlibArtifacts.toml` file, or do you mean the artifacts within the TOML? The `StdlibArtifacts.toml` file itself must be installed so that tools like BB can find the artifacts that Julia build was built from.  The reason I've renamed the `Artifacts.toml` files here to `StdlibArtifacts.toml` is precisely to avoid confusing `Pkg` and getting the artifacts themselves downloaded during normal `Pkg` operations.

**Comment by yuyichao** [comment]
> That's insufficient; we need the full artifact. Header files, static libraries, etc...

Then those should just be packaged as well, just like how headers and julia source code for julia itself is, either is needed during normal usage.

> I did not say that.

IIUC that's what PackageCompiler does.

> When you say "this file" do you mean the StdlibArtifacts.toml file, or do you mean the artifacts within the TOML? The StdlibArtifacts.toml file itself must be installed so that tools like BB can find the artifacts that Julia build was built from. The reason I've renamed the Artifacts.toml files here to StdlibArtifacts.toml is precisely to avoid confusing Pkg and getting the artifacts themselves downloaded during normal Pkg operations.

I mean the toml file. What I mean is that no code that runs a julia binary should access this file. BinaryBuilder can rely on this file just fine but anything else that doesn't download the julia itself must not. If the binary is downloaded from a known source, then that source can also provide a link that include this information, which could also simply be the source.

**Comment by staticfloat** [comment]
> Then those should just be packaged as well, just like how headers and julia source code for julia itself is, either is needed during normal usage.

We don't want them bundled together with Julia's source code.  Having links to them in a machine-readable format for tools that need these dependencies is the best solution.

> What I mean is that no code that runs a julia binary should access this file. BinaryBuilder can rely on this file just fine but anything else that doesn't download the julia itself must not.

I don't understand your objections here; BinaryBuilder is code that runs a Julia binary?  Why are you worried about these files being used?

**Comment by yuyichao** [comment]
> We don't want them bundled together with Julia's source code

I'm not sure what you are talking about.
1. I'm talking about the binary distribution
2. AFAICT this file will be bundled together with the julia source code (git and tarball) simply from the fact that it's in this repo.

> I don't understand your objections here; BinaryBuilder is code that runs a Julia binary? Why are you worried about these files being used?

If some code controls where it gets julia from, it's perfectly fine to read it, and since it knows where it gets its julia from, it can also download another file including links to all the other files it needs to download so the TOML file does not need to be included in the binary distribution itself.
If some code doesn't control where it gets its julia from, such code must never read this file so the TOML file should not be included in the binary distribution to avoid error.

**Comment by staticfloat** [comment]
I think what you're saying is that if you don't know where your copy of Julia came from, a tool that wants to read this file (such as BinaryBuilder) may download a version of a dependency that doesn't actually match what Julia is using, e.g. it may look at the `StdlibArtifacts.toml` file for `LibCURL_jll` and expect that if it downloaded that tarball it would match what Julia right now is using.

You're right.

On the other hand, the whole JLL ecosystem kind of relies on the presupposition that you're not painting too far outside of the lines of the official Julia distribution anyway; if you build Julia with an incompatible version of, say, libcurl, the binaries built by BinaryBuilder won't work with it anyway.  If you build Julia with a version of libcurl that is slightly modified but is still ABI-compatible with the official Julia version, then compiling something against the distributions pointed to by these Artifacts.toml files will work just fine to link at runtime against the custom libraries.  So in the end, I contend it doesn't matter; this doesn't break any configurations that weren't already broken, and it greatly increases the convenience of building things that are compatible with the official builds, which in my estimation is >99% of all Julia installs worldwide.

**Comment by yuyichao** [comment]
> On the other hand, the whole JLL ecosystem kind of relies on the presupposition that you're not painting too far outside of the lines of the official Julia distribution anyway

Yes, which is why I specifically said it's perfectly fine for BinaryBuilder to read this TOML file.
It just shouldn't be in the binary distribution, which is not limited to what binary builder build.

> this doesn't break any configurations that weren't already broken

No, but it encourages more things to be broken.

**Comment by staticfloat** [comment]
> No, but it encourages more things to be broken.

I disagree.  This improves the workflow for by far the most common configuration of Julia, and if this doesn't actually break other usecases (even the rare ones like `USE_SYSTEM_X=1`) then I see no reason not to merge this.

**Comment by yuyichao** [comment]
> this doesn't break any configurations that weren't already broken

And case in point, it was already broken since it was read by Pkg. Changing the name of course makes Pkg skips it but this encourages other packages to read this new file causing the same breakage.

**Comment by yuyichao** [comment]
> This improves the workflow for by far the most common configuration of Julia

And I'm saying that this is the worst way to make that improvement.

**Comment by yuyichao** [comment]
And the simplist way to make this work is by not installing this file and simply access this file from the source tarball. The better way to do this is to record the path of the dev files (header/static libraries etc) at build time and store it in a different file. If these files are not included in the binary distribution since it is known to be downloadable from somewhere else later, that info can also be recorded there.

**Comment by staticfloat** [comment]
> And the simplist way to make this work is by not installing this file and simply access this file from the source tarball.

For the vast majority of users, if they simply `using BinaryBuilder` and then try to build something, they should not have to specify where their Julia build came from.  BB-sourced binaries are the standard for ABI compatibility across the Julia ecosystem, and while I think it is good for us to keep compatibility with as wide a range of platforms and configurations as possible, making things more and more convenient for the primary users is a good thing, and should not be hindered by the fringe configurations, especially since very few users of BinaryBuilder that are using a custom build of Julia would actually want to use their custom versions of things; more likely they'd want the standard versions because they would want their built binaries to be actually usable by others.

**Comment by yuyichao** [comment]
> making things more and more convenient for the primary users is a good thing, and should not be hindered by the fringe configurations

No this is not a valid argument. By this argument, most users are using julia on x86 so the support for all other architectures can be dropped. Also, most user are using this is only because there are constent breakage to all other configurations and the only way to keep those breakage minimum is not to encourage such breakage.

> they should not have to specify where their Julia build came from

And BB can be taught to download the source necessary, or as I said, go with the less lazy approach and encode all the needed info instead of hardcoding a single configuration.

Also the question about PackageCompiler remains unanswered.

**Comment by staticfloat** [comment]
> Also the question about PackageCompiler remains unanswered.

Hmmm, now that I think about it, PackageCompiler is probably unaffected because the binaries are within the Julia distribution's `lib` folder already, so the artifacts should be unused (for now, not in v1.7 though).  I take back what I said about PackageCompiler in this case.

> No this is not a valid argument. By this argument, most users are using julia on x86 so the support for all other architectures can be dropped. Also, most user are using this is only because there are constent breakage to all other configurations and the only way to keep those breakage minimum is not to encourage such breakage.

I didn't say that, and you know that's not my stance as my work to bring all platforms to feature parity with things like the `libjulialoader` PR can attest.  The importance of `USE_SYSTEM_X=1` and (for instance) `ppc64le` linux are two very different things.  And most critically: This PR does not degrade any configurations!  It in fact only fixes them.

**Comment by yuyichao** [comment]
> and you know that's not my stance as my work to bring all platforms to feature parity with things like the libjulialoader PR can attest

Well, I don't doubt that this is your intention but what I don't think that's whats actually happening. These changes are all towards isolating the whole julia ecosystems so that only configurations that you would like to support are supported, increasingly forcing all other users to give up on previously working setup. It of course bring "feature parity" to platforms you care about but at the same time they just break what you decide is something you don't want to worry about. What you are supporting is by no mean "all platforms".

> The importance of USE_SYSTEM_X=1 and (for instance) ppc64le linux are two very different things

And I don't really see the importance of system library being different from ppc64, at least not in the way you believe. As a concrete example, I don't use ppc64 but I do use julia and many other programs and libraries on my computer. Yet the official julia bundles libraries that are incompatible with the system one, making it impossible to load julia from those programs (A non-LLVM example of that is libgit2). For people that actually want to integrate julia with anything, the compatibility outside what BB builds is important. You can say that few people are doing that, and that's because it's intentially broken. The approach of including all binaries used is only possible if you literally build every single libraries and programs on the system, some of which cannot be decided by the user, for example when it's necessary to interact with shared system resources. I have personally deal with many other cases where the binary distributer simply didn't care about what my community needs (mostly input methods related) and it's almost impossible to fix. Fortunately those has mostly been closed source software so I could avoid most of the time. Julia is actually the first open source project that I had to deal with this.

> This PR does not degrade any configurations! It in fact only fixes them.

And I never said this breaks anything. What I said is that this encourage other people to break it. Most other incompatibilities between the libraries shipped/compiled for julia is also not caused by changes to how julia is compiled/load library but is strongly affected by inventing new says to add libraries and encourage people to use these that are incompatible with system ones. For example, adding a BinDeps replacement does not break any packages since it's a strict addition. However, as people starts to use the new method it does start to break people that were using system libraries from BinDeps. This is exactly the same. Of course the addition of yet unused file doesn't break anything, but people starting to make change to existing code will cause breakage and those breakage should be blaimed on changes here rather than the people following the recommendation.

**Comment by StefanKarpinski** [comment]
Instead of copy-pasta-ing the entire artifacts file here, could we instead identify the real package that the stdlib stub is a dummy for and teach the relevant BB tooling to look at that? We already have the version number in the project file; if that's not enough, we could put a tree hash and/or a URL.

**Comment by staticfloat** [comment]
> Instead of copy-pasta-ing the entire artifacts file here, could we instead identify the real package that the stdlib stub is a dummy for and teach the relevant BB tooling to look at that? We already have the version number in the project file; if that's not enough, we could put a tree hash and/or a URL.

I'd prefer to record the actual artifact treehashes here, but I agree that copy-pasta makes this error-prone, so instead I suggest we can automatically download the appropriate `Artifacts.toml` (and still save it as `StdlibArtifacts.toml`) at `make` time.  That's done in this PR here: https://github.com/JuliaLang/julia/pull/38347/files#diff-fec02f2f9c3bc0d818319ad7343f04ba15eef7f64e99aeb5e7892fe2fbfa2606R25-R35

I'll close this PR as the fix is included in that PR.

> These changes are all towards isolating the whole julia ecosystems so that only configurations that you would like to support are supported, increasingly forcing all other users to give up on previously working setup.

While I do know that some setups have been broken by the move toward JLLs, the amount of positive feedback received outweighs the negative by orders of magnitude.  I understand that you don't like the JLL philosophy because it makes it harder to integrate things into the system, but while you may be able to get your system to work well, the vast majority of users are unable to, and building an ecosystem that is more isolated from the system by default has been a big win for the ecosystem as a whole.

That being said, we're still interested in providing fallbacks and escape hatches for users that want to not use JLLs and instead use custom-compiled versions of things.  The Julia HPC calls (Usually happen once per month, we have a good chunk of the Julia binary builder community involved, along with some Spack developers) have recently been very focused on how to do things like convince JLLs to load binaries generated by Spack.  I think you would be very interested in some of these discussions.  If you'd like to join, just let me know.  The current momentum is to allow configuration of JLLs through `Preferences` to not use the default artifact, but allow passing explicit paths (or just SONAMEs) to `dlopen()` instead.

**Comment by yuyichao** [comment]
> the amount of positive feedback received outweighs the negative by orders of magnitude.
> and building an ecosystem that is more isolated from the system by default has been a big win for the ecosystem as a whole.

As I said, you do not get much feedback because you've selected out only users that doesn't care. People that are affected are simply being driven away and the report are regarded as issues in their setup instead of having the underlying issue fixed. This only works for people whose interest are mainly on julia and of course for them you'll only get positive feedback. However, this decision to simply walk away from the problem instead of facing it is extremely short-sighted. The simplest way to show this is that there is no way for two ecosystems like this to co-exist.

> I do know that some setups have been broken

And so you should also note that this will encourage people to break things, which is something you refuse to acknowledge above.

> while you may be able to get your system to work well, the vast majority of users are unable to,

Getting a software to work well with the system isn't the job of users, it's the job of the developer. Also, out of LLVM, there basically isn't anything that needs to be done to get julia to work with system libraries and LLVM itself has it's own unique solution so it's not really a problem either. I can speak from my own experience that the only issue that exists when building with system libraries is from people making changes (like this one) that actively breaks the setup, and not from any incompatibility of the library itself. And just to be clear, as I mentioned from different angles many times above, providing a default way to download things from your own build server (effectively creating your own distro) is fine and the assumptions about library versions can be made on when dealing with such a service. It does mean that loading official julia or julia pro binay in many local programs causes them to crash but that's not something I care too much about. What I am against instead are the changes that actively making what you thought was hard to do even harder because you didn't care enough about them and there isn't a entity that to voice related concern after you've driven them away.

**Pull request closed without merging**
