### PR TITLE
Backports for julia 1.8.0-beta2

### LINKED ISSUE #43411: Wrapping NamedTuple in struct is no longer bitstype in 1.7
cf brief discussion on [discourse](https://discourse.julialang.org/t/struct-wrapping-namedtuple-is-not-isbits-depending-on-how-it-is-defined/72965/9) 

This bug(?) occurs on 1.7 but not on 1.6: 

```Julia
struct Wrapper{SYMS, TT}
   x::NamedTuple{SYMS, TT}
end
randnt() = Wrapper((a = randn(), b = rand(), c = rand(1:5), d = randn(SVector{3, Float64})))
X = randnt()
@allocated randnt()  # 64
isbits(X)   # false
isbits(X.x)   # true 
```

But if the wrapper is defined differently then the `isbits == true` is recovered:
```Julia
struct Wrapper1{NT} 
   x::NT
end
randnt1() = Wrapper1((a = randn(), b = rand(), c = rand(1:5), d = randn(SVector{3, Float64})))
X1 = randnt1()
@allocated randnt1() # 0 
isbits(X1) # true
isbits(X1.x) # true
```
Because of this, it is easy enough to produce a work-around, but it feels like that shouldn't be necessary and the behaviour described above should not occur?

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```
(built from source)

### LINKED ISSUE #44328: OpaqueClosure precompilation test generates warnings in debug builds
In a debug build, `make debug test-precompile` generates the following warnings:
```
WARNING: Encountered invalid lowered code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
WARNING: Encountered invalid inferred code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
WARNING: Encountered invalid optimized code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
WARNING: Encountered invalid lowered code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
WARNING: Encountered invalid inferred code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
WARNING: Encountered invalid optimized code for method Tuple: Core.Compiler.InvalidCodeError(kind="method signature does not match number of method arguments", meta=(false, 1, 2))
```
This comes from https://github.com/JuliaLang/julia/blob/df81bf9a96c59f257a01307cd0ecf05035d8301f/test/precompile.jl#L1222
in the test harness that uses `@opaque`.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #44258 
- [x] #44275 
- [x] #44274 
- [x] #44313 
- [x] #43990 
- [x] #44321 
- [x] #44311 
- [x] #44305 
- [x] #44223 
- [x] #44262 
- [x] #44335 
- [x] #44345 
- [x] #44359 
- [x] #44420 
- [x] #44419 
- [x] #44168 
- [x] #44319 
- [x] #44416 
- [x] #44446 
- [x] #44453 
- [x] #44444 
- [x] #44479 
- [x] #44456 
- [x] #44516 
- [x] #44476 
- [x] #44464 
- [x] #44487 
- [x] #44524 
- [x] #44528 
- [x] #44555 
- [x] #44404 
- [x] #44529 
- [x] #44240
- [x] #44389
- [x] #44448
- [x] #44511 
- [x] #44608 
- [x] #44609 
- [x] #44561 
- [x] #44515 
- [ ] #44617

Contains multiple commits, manual intervention needed:
- [ ] #44360 

Non-merged PRs with backport label:
- [ ] #44554 
- [ ] #44507 
- [ ] #44412 
- [ ] #44232 
- [ ] #44197 <!-- add entry point to construct an OpaqueClosure from pre-optimized IRCode

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, that `tester_macos64` failure is concerning since it happened in `test/precompile.jl`. Might be #44328? The crash happened in the very next `@testset`.

**Comment by timholy** [comment]
@simeonschaub [clarifies](https://github.com/JuliaLang/julia/pull/44335#issuecomment-1050938225) that the warnings aren't serious, so that's unlikely to be the cause. 

Looking at the log, it might have failed in precompile simply due to a timeout. That's consistent with #44338, which will be fixed by #44345.

**Comment by timholy** [comment]
You'll definitely want #44345

**Comment by KristofferC** [comment]
Added

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AbstractDifferentiation", "AbstractTrees", "AdaStress", "AdventOfCode", "AnyMOD", "ApproxFun", "ApproxFunFourier", "ApproxFunOrthogonalPolynomials", "ApproxFunSingularities", "ArrayLayouts", "AssociativeArrays", "AtomicGraphNets", "AxisKeys", "AxisSets", "AxisTables", "BEASTXMLConstructor", "BIDSTools", "BPFnative", "BSON", "BlockArrays", "Bonsai", "CBinding", "CGAL", "CUDAKernels", "Caching", "Cassette", "Causal", "ChainRulesCore", "ChainRulesOverloadGeneration", "Checkpointing", "ClassicalOrthogonalPolynomials", "ClimaCore", "ClimaCorePlots", "ClimaCoreVTK", "ClimatePlots", "ClimateTools", "Cloudy", "CodeInfoTools", "CombinedParsers", "CompactBases", "CompilerPluginTools", "ConditionalDists", "Conductor", "ConjugatePriors", "ControlSystems", "CxxWrap", "DSP", "DailyTreasuryYieldCurve", "Dash", "DataFrames", "DataKnots", "DataStructures", "DeIdentification", "DeepDiffs", "DiffEqCallbacks", "DiffEqParamEstim", "DiscreteEvents", "Dispatcher", "DynamicBoundsBase", "DynamicPPL", "DynamicalBilliards", "EconJobMarket", "Enzyme", "EquationsOfStateOfSolids", "EquivalentCircuits", "ExSup", "FMIFlux", "FastJet", "FastTransforms", "FeatureEng", "FeatureSelectors", "FillArrays", "FinEtoolsVoxelMesher", "FinRua", "FindClosest", "FlightMechanics", "FlxQTL", "FormattedTables", "GPUCompiler", "GalacticOptim", "GarishPrint", "GeneralizedSVD", "GenericSchur", "GeoEfficiency", "GeoStatsDevTools", "GoogleCodeSearch", "GroebnerBasis", "HalfIntegers", "HarmonicOrthogonalPolynomials", "HierarchicalUtils", "HomotopyContinuation", "Hypatia", "IBMQClient", "ITensorGaussianMPS", "ITensorUnicodePlots", "ITensorVisualizationBase", "ImageCore", "ImageQuilting", "ImageSegmentation", "ImplicitArrays", "InfiniteArrays", "InverseLaplace", "JET", "JSONPointer", "JuliennedArrays", "Juniper", "KernelAbstractions", "KernelGradients", "LCIO", "LMDB", "LRSLib", "LazyArrays", "LazySets", "LegibleLambdas", "LinearMaps", "LiterateOrg", "LiterateTest", "LocalRegistry", "LogParser", "LogRoller", "LoweredCodeUtils", "Luxor", "MEstimation", "MIRT", "MIRTjim", "MPSToolkit", "Mamba", "MambaModels", "MappedArrays", "MarketCycles", "Memento", "MeshCore", "MetaArrays", "Metatheory", "MinimallyDisruptiveCurves", "MultinomialRegression", "MultipleTesting", "MultivariateOrthogonalPolynomials", "NMRTools", "NeuralArithmetic", "NicePipes", "NotebookToLaTeX", "OpenEphysLoader", "OrbitalTrajectories", "OscillatoryIntegrals", "PLCTag", "POMDPPolicies", "PProf", "PSIS", "PackageAnalyzer", "ParallelUtilities", "Parallelism", "Pathfinder", "PerfChecker", "PkgDeps", "Plots", "Poltergeist", "Polyhedra", "PowerGraphics", "PredictMDExtra", "ProfileSVG", "QML", "QXTns", "QXTools", "QuantizedArrays", "QuantumESPRESSOCommands", "QuantumOptics", "QuasiArrays", "Qwind", "ROCKernels", "RSCG", "RangeHelpers", "RedefStructs", "RiemannHilbert", "RobotDescriptions", "RobotOSData", "Runner", "SIAN", "SIMD", "SOM", "SemiclassicalOrthogonalPolynomials", "SemiseparableMatrices", "Signals", "SimplePadics", "SingularIntegralEquations", "SlackThreads", "SnoopCompile", "SocialSolver", "SolverTraces", "Soss", "SparseTimeSeries", "SpatialBoundaries", "SpatialJackknife", "SpecialFunctions", "StableDQMC", "StackOverflow", "StarAlgebras", "StatProfilerHTML", "StaticTrafficAssignment", "StochasticDiffEq", "StrBase", "StrRegex", "StructuralIdentifiability", "StructuredArrays", "TORA", "TaylorModels", "TensorKitManifolds", "TheFix", "ThresholdStability", "TimeSeries", "TimeZones", "Tracker", "TraitSimulation", "TurbulenceConvection", "Wikidata", "WriteVTK", "YaoQX", "ZfpCompression", "Zomato"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44324#issuecomment-1058937187) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/fb69baf_vs_40279f9/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AbstractDifferentiation", "AbstractTrees", "AdaStress", "AdventOfCode", "AnyMOD", "ApproxFun", "ApproxFunFourier", "ApproxFunOrthogonalPolynomials", "ApproxFunSingularities", "ArrayLayouts", "AssociativeArrays", "AtomicGraphNets", "AxisKeys", "AxisSets", "AxisTables", "BEASTXMLConstructor", "BIDSTools", "BPFnative", "BSON", "BlockArrays", "Bonsai", "CBinding", "CGAL", "CUDAKernels", "Caching", "Cassette", "Causal", "ChainRulesCore", "ChainRulesOverloadGeneration", "Checkpointing", "ClassicalOrthogonalPolynomials", "ClimaCore", "ClimaCorePlots", "ClimaCoreVTK", "ClimatePlots", "ClimateTools", "Cloudy", "CombinedParsers", "CompactBases", "CompilerPluginTools", "ConditionalDists", "Conductor", "ConjugatePriors", "CxxWrap", "DailyTreasuryYieldCurve", "Dash", "DataFrames", "DataKnots", "DataStructures", "DeIdentification", "DeepDiffs", "DiffEqCallbacks", "DiffEqParamEstim", "DiscreteEvents", "Dispatcher", "DynamicBoundsBase", "DynamicPPL", "DynamicalBilliards", "EconJobMarket", "Enzyme", "EquationsOfStateOfSolids", "EquivalentCircuits", "ExSup", "FMIFlux", "FastJet", "FastTransforms", "FeatureEng", "FeatureSelectors", "FillArrays", "FinEtoolsVoxelMesher", "FinRua", "FindClosest", "FlightMechanics", "FlxQTL", "FormattedTables", "GPUCompiler", "GarishPrint", "GeneralizedSVD", "GenericSchur", "GeoEfficiency", "GeoStatsDevTools", "GoogleCodeSearch", "GroebnerBasis", "HarmonicOrthogonalPolynomials", "HierarchicalUtils", "HomotopyContinuation", "Hypatia", "IBMQClient", "ImageCore", "ImageQuilting", "ImageSegmentation", "ImplicitArrays", "InfiniteArrays", "InverseLaplace", "JET", "JSONPointer", "JuliennedArrays", "KernelGradients", "LCIO", "LMDB", "LRSLib", "LazyArrays", "LegibleLambdas", "LinearMaps", "LiterateOrg", "LiterateTest", "LogParser", "LogRoller", "LoweredCodeUtils", "Luxor", "MEstimation", "MIRT", "MIRTjim", "Mamba", "MambaModels", "MappedArrays", "MarketCycles", "Memento", "MeshCore", "MetaArrays", "Metatheory", "MinimallyDisruptiveCurves", "MultinomialRegression", "MultipleTesting", "MultivariateOrthogonalPolynomials", "NMRTools", "NeuralArithmetic", "NicePipes", "NotebookToLaTeX", "OpenEphysLoader", "OrbitalTrajectories", "OscillatoryIntegrals", "PLCTag", "POMDPPolicies", "PProf", "PSIS", "PackageAnalyzer", "ParallelUtilities", "Parallelism", "Pathfinder", "PerfChecker", "PkgDeps", "Plots", "Poltergeist", "Polyhedra", "PowerGraphics", "PredictMDExtra", "ProfileSVG", "QML", "QuantizedArrays", "QuantumESPRESSOCommands", "QuantumOptics", "QuasiArrays", "Qwind", "ROCKernels", "RSCG", "RangeHelpers", "RedefStructs", "RiemannHilbert", "RobotDescriptions", "RobotOSData", "Runner", "SIAN", "SIMD", "SOM", "SemiclassicalOrthogonalPolynomials", "SemiseparableMatrices", "Signals", "SimplePadics", "SingularIntegralEquations", "SlackThreads", "SnoopCompile", "SocialSolver", "SolverTraces", "Soss", "SparseTimeSeries", "SpatialBoundaries", "SpecialFunctions", "StableDQMC", "StackOverflow", "StarAlgebras", "StatProfilerHTML", "StaticTrafficAssignment", "StochasticDiffEq", "StrRegex", "StructuralIdentifiability", "StructuredArrays", "TORA", "TaylorModels", "TensorKitManifolds", "TheFix", "TimeSeries", "Tracker", "TraitSimulation", "TurbulenceConvection", "Wikidata", "ZfpCompression", "Zomato"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44324#issuecomment-1065238790) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/abf0a9a_vs_8611a64/report.html).

**Comment by KristofferC** [comment]
CI is not great here (which is the same as master) but all these commits have already had a full CI run on them and the failures here are known and it is "just" a beta that we really need to get out so I will merge this nonetheless.

**Pull request merged**
