### PR TITLE
Fix #20409: rank for sparse matrices.

### LINKED ISSUE #20409: rank for sparse matrices
```julia
mat = sparse([1 0 0; 0 1 0; 0 0 1])
rank(mat)
```

throws an error:

> ERROR: MethodError: no method matching svdvals!(::SparseMatrixCSC{Float64,Int64})

Can we have `rank` for sparse matrices?

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Review by andreasnoack — APPROVED** [review]

**Comment by fredrikekre** [comment]
Just want to note that this is type-piracy by `SuiteSparse`, and might make it more difficult to decouple `SuiteSparse`, `SparseArrays` them in the future.

**Comment by andreasnoack** [comment]
We should flesh out the possible dependency graphs between `SparseArrays`, `SuiteSparse`, and the (currently non-existing) `SparseLinearAlgebra` packages and discuss benefits and complications.

While it's true that this PR might add to the confusion, I suspect it won't add much work to the eventual decoupling process. A solution could also be to just define this method in the current `linearalgebra.jl` in `SparseArrays` and make it call `qr` anyway. It will then just fail if no sparse `QR` is available.

**Comment by ViralBShah** [comment]
The question around separating SparseArrays and SuiteSparse is whether Dense will also roughly split the same functionality into separate packages. Otherwise, we will end up with a real patchwork of what sparse capability lives where and will be different than dense.

**Comment by ViralBShah** [comment]
Is this ok to backport, at least to 1.1?

**Pull request merged**
