### PR TITLE
Add Filesystem Docs

### PR DESCRIPTION
**Pull request by Akshat-mehrotra**

### CODE REVIEW

**Comment by Keno** [comment]
The examples here are all windows specific, we should have examples for Unix operating systems also. @mortenpi @fredrikekre do we have OS specific examples for doc examples/doctests? In addition there's a bunch of uses of `julia-repl`, with non-REPL examples.

**Comment by Akshat-mehrotra** [comment]
Made it non-windows specific and replaced `julia-repl` with `jldoctest`.

**Comment by logankilpatrick** [comment]
Nice work @Akshat-mehrotra

**Comment by mortenpi** [comment]
> The examples here are all windows specific, we should have examples for Unix operating systems also. @mortenpi @fredrikekre do we have OS specific examples for doc examples/doctests?

Just for the record, at the moment we don't have that. But we could add an argument to `jldoctest` for that if we need this feature.

**Comment by ViralBShah** [comment]
A lot of this documentation is now available. We could possibly use some of the examples and  jldoctest sections in here, but best to start a new PR.

**Pull request closed without merging**
