### PR TITLE
interpret Expr(:isdefined, ::QuoteNode) correctly

### PR DESCRIPTION
**Pull request by simeonschaub**
discovered in https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/477

### CODE REVIEW

**Comment by vtjnash** [comment]
This sounds like someone generated corrupt IR, which is not permitted. Using lowering from an AST should prevent this from reaching the backend, and any compiler passes in Core.Compiler are written to avoid generating it later.

Can you add a test to julia/base/compiler/validation.jl instead to reject this?

**Comment by simeonschaub** [comment]
Would it be problematic to consider this valid? Many Cassette style code transformations use `Meta.partially_inline!` to replace slots or static parameters with QuoteNodes, the specific example here was Zygote: https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/476.

**Comment by vtjnash** [comment]
Hm, perhaps we should eliminate that code, but in the meantime, it should be taught how to correctly inline a `:isdefined` node

**Comment by JeffBezanson** [comment]
Right; inlining into `isdefined` is not valid since `isdefined` is not referentially transparent --- it operates on a variable, not its value, so you can't replace the variable with its value.

**Pull request closed without merging**
