### PR TITLE
Add patch for 31156

### LINKED ISSUE #31156: LLVM ERROR: Broken function found, compilation aborted! when precompiling Base.permutedims
I get `LLVM ERROR: Broken function found, compilation aborted!` when including `Base.precompile(Tuple{typeof(Base.permutedims), Array{Bool, 3}, Array{Int64, 1}})` for system image compilation.  I can reproduce this in Julia 1.0 to 1.2.

First I created `compile.bash`:

```bash
#!/bin/bash

code_print_image_file="print(unsafe_string(Base.JLOptions().image_file))"

JULIA="${JULIA:-julia}"
IMAGE="$("$JULIA" -e "$code_print_image_file")"

OUTPUT_O=sys.a

set -ex

${JULIA} --output-o="$OUTPUT_O" \
    -g1 --startup-file=no --code-coverage=none \
    --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes \
    --startup-file=no --warn-overwrite=no --compile=yes --depwarn=yes \
    --cpu-target=native --track-allocation=none --sysimage-native-code=yes \
    --sysimage="$IMAGE" \
    --compiled-modules=yes --optimize=2 \
    ./precompile_wrapper.jl
```

and `./precompile_wrapper.jl`:

```julia
atexit_hook_copy = copy(Base.atexit_hooks) # make backup
# clean state so that any package we use can carelessly call atexit
empty!(Base.atexit_hooks)
Base.__init__()
Sys.__init__() #fix https://github.com/JuliaLang/julia/issues/30479
using REPL
Base.REPL_MODULE_REF[] = REPL

Base.precompile(Tuple{typeof(Base.permutedims), Array{Bool, 3}, Array{Int64, 1}})

Base._atexit() # run all exit hooks we registered during precompile
empty!(Base.atexit_hooks) # don't serialize the exit hooks we run + added
# atexit_hook_copy should be empty, but who knows what base will do in the future
append!(Base.atexit_hooks, atexit_hook_copy)
```

Then run:

```console
$ julia --version
julia version 1.1.0

$ ./compile.bash
+ julia --output-o=sys.a -g1 --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --startup-file=no --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes --sysimage=/home/takafumi/opt/julia/julia-1.1.0/lib/julia/sys.so --compiled-modules=yes --optimize=2 ./precompile_wrapper.jl
ptrtoint not supported for non-integral pointers
inttoptr not supported for non-integral pointers
LLVM ERROR: Broken function found, compilation aborted!

$ julia-1.0 --version
julia version 1.0.3

$ JULIA=julia-1.0 ./compile.bash
+ julia-1.0 --output-o=sys.a -g1 --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --startup-file=no --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes --sysimage=/home/takafumi/opt/julia/julia-1.0.3/lib/julia/sys.so --compiled-modules=yes --optimize=2 ./precompile_wrapper.jl
ptrtoint not supported for non-integral pointers
inttoptr not supported for non-integral pointers
LLVM ERROR: Broken function found, compilation aborted!

$ ~/repos/watch/julia/usr/bin/julia -E VERSION
v"1.2.0-DEV.339"

$ JULIA=~/repos/watch/julia/usr/bin/julia ./compile.bash
+ /home/takafumi/repos/watch/julia/usr/bin/julia --output-o=sys.a -g1 --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --startup-file=no --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes --sysimage=/home/takafumi/repos/watch/julia/usr/lib/julia/sys.so --compiled-modules=yes --optimize=2 ./precompile_wrapper.jl
ptrtoint not supported for non-integral pointers
inttoptr not supported for non-integral pointers
LLVM ERROR: Broken function found, compilation aborted!
```

(`precompile_wrapper.jl` is taken from `run_julia_code.jl` generated by PackageCompiler.jl)

### PR DESCRIPTION
**Pull request by Keno**
This imports the patch I put up in https://reviews.llvm.org/D75072
and should fix #31156. We should probably hold off on merging this
for a few days while upstream review is ongoing. In the meantime,
this branch should be convenient to try. Make sure to remember to build
LLVM from source, not BB.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ianshmean Can you try this out and let us know if it fixes the bug for you?

**Comment by ianshmean** [comment]
Already getting started 👍🏻
Thanks @Keno !

**Comment by ianshmean** [comment]
Indeed, this fixes https://github.com/JuliaLang/julia/issues/31156
See https://github.com/JuliaLang/julia/issues/31156#issuecomment-590925156 for test setup

I also just successfully compiled a sysimage with PackageCompiler that was previously failing for this reason 👍🏻❤️

**Comment by JeffBezanson** [comment]
Ready to merge?

**Comment by Keno** [comment]
I haven't gotten any feedback upstream, but I do think this patch is ok to do. It's about as minimal as I could make it.

**Comment by Keno** [comment]
Actually, we should probably add this patch to BB first and add the bump here, so we test this patch on CI.

**Comment by vchuravy** [comment]
Replaced by #35076

**Pull request closed without merging**
