### PR TITLE
Don't access parent of triangular matrix in powm

### PR DESCRIPTION
**Pull request by jishnub**
Since the values stored in the parent corresponding to the structural zeros of a tridiagonal matrix aren't well-defined, using it in `ldiv!` is a footgun that may lead to heisenbugs (one seen in https://buildkite.com/julialang/julia-master/builds/31285#018c7cc7-6c77-41ac-a01b-1c7d14cb1b15). This PR changes it to using the tridiagonal matrix directly in `ldiv!`, which should lead to predictable results, and be bug-free. The failing tests for #52571 pass locally with this change.

### CODE REVIEW

**Comment by dkarrasch** [comment]
I'm not familiar with this part of the code. Why is this method restricted to `BlasFloat` to begin with, but not to `StridedMatrix`? Can we relax the restriction? Is there a way to test the difference? And finally, should this be backported to v1.10?

**Comment by jishnub** [comment]
I've relaxed the `eltype`, which now makes exponentiation work with a `BigFloat` upper-triangular matrix (used to fail earlier as the `eltype` was too narrow).

**Comment by jishnub** [comment]
Why are the tests not running, btw? I see two successful checks (typos and labels), but no actual testsets

**Review by dkarrasch — APPROVED** [review]
LGTM

**Pull request merged**
