### PR TITLE
notepad++_solarized

### PR DESCRIPTION
**Pull request by cameyo42**
http://julia-programming-language.2336112.n4.nabble.com/Julia-and-notepad-tp21094.html

### CODE REVIEW

**Comment by tkelman** [comment]
Are the changes to the `.ahk` file the same as in #11585?

**Comment by cameyo42** [comment]
@tkelman
Yes. Excuse me. It's my first post on github.

**Comment by pao** [comment]
It'll still merge on top--do we have a policy on requiring a rebase here, @tkelman? Since this is in /contrib and unlikely to matter for a bisection I'm inclined not to worry about it, but I also like sparkly, clean histories, so I'm inclined to also worry about it. :D

**Comment by tkelman** [comment]
@pao why not cherry-pick fe0495229be71064183a8501a6504db489c6230b and push that to master, since the other commit should have been the same as what you just merged in the other PR.

@cameyo42 thanks for these improvements. Next time you submit a PR, it's a good idea to make a separate branch on your fork, instead of opening pull requests from master.

**Comment by pao** [comment]
> why not cherry-pick fe04952 and push that to master

That sounds suspiciously like effort (and I can't easily do it from my current location, where I have no local clone.) But I can do that if it's not taken care of in the next 6-7 hours.

**Pull request closed without merging**
