### PR TITLE
update precompile.jl

### LINKED ISSUE #21196: update precompile.jl
This file should be updated to reflect changes to Base over the 0.6 cycle, and will help repl startup time and package load times.

See e.g. https://github.com/JuliaLang/julia/pull/20793#issuecomment-289732784

This can now be done by defining `TRACE_COMPILE` in options.h.

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #21196.

With this, the sysimg goes from 43MB to 38MB, DataFrames precompile time goes from 47 sec to 37 sec, and the sysimg build gets faster --- despite the list of precompiles being significantly longer. Maybe there was something strange in the old precompile.jl?

### CODE REVIEW

**Comment by vtjnash** [comment]
Seems like this drops a lot of the custom calls at the bottom, or were those part of the "do various things"?

**Comment by JeffBezanson** [comment]
The custom calls are not maintainable. I tried to do things related to their comments however (repl help, completion, addprocs).

**Comment by StefanKarpinski** [comment]
Could this precompile generation functionality be exposed for packages to use as well? Presumably that might help a bit with post-precompile load times.

**Comment by JeffBezanson** [comment]
Yes, we could make it an environment variable or command-line option.

**Pull request merged**
