### PR TITLE
docstrings for dllist, dlpath (#32501)

### PR DESCRIPTION
**Pull request by chrisvwx**

### CODE REVIEW

**Comment by kshyatt** [comment]
Can we please get a review on this?

**Comment by StefanKarpinski** [comment]
If it's wrong, someone can complain and fix it. Better to have something :)

**Comment by christianpeel** [comment]
Thanks!

**Comment by StefanKarpinski** [comment]
No, thank you for writing the docs! Sorry it took so long to merge.

**Pull request merged**
