### PR TITLE
🤖 [master] Bump the StyledStrings stdlib from e0ca0f8 to 9c015e2

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: StyledStrings
URL: https://github.com/JuliaLang/StyledStrings.jl.git
Stdlib branch: main
Julia branch: master
Old commit: e0ca0f8
New commit: 9c015e2
Julia version: 1.12.0-DEV
StyledStrings version: 1.11.0(Does not match)
Bump invoked by: @tecosaur
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/StyledStrings.jl/compare/e0ca0f85412ea5cafabfeaaec4d62ca26c3959d2...9c015e2ced03cc9d8d882278d3af0c20cfbaf062

```
$ git log --oneline e0ca0f8..9c015e2
9c015e2 Docs: create an examples page
a9772d4 Markup annot keys cannot contain null character
243d959 Allow interpolation of underline properties
fd2adcc Docs: tweak face description for clarity
4b06b79 Docs: clarify that AbstractString is wrapped
7f07b1b Docs: second paragraph reads better as not a note
a3d15cb Docs: forgot to mention font attribute
9c10614 Show colour and styling in docs
59fd944 Add docs previews to PR CI
9709612 Mark styled and withfaces functions as public API
a4c7678 Make withfaces behave more consistently
50d4198 Add speculative consideration of future face keys
04b5031 Add fuzzing to the tests set
7dc3c26 Allow color strings as in Face constructor
c419317 Don't annotate interpolated empty strings
dfef96d Adjust prioritisation of composed styling in parse
9a23e9e Test the display of parsing errors
1d7f42a Test parsing of each and every inline face attr
84ba211 No need to escape a string when parsing
e3c0453 Add missing is-macro check to face value interp
db006ed Mistyped font attribute as "face" in the parser
230fa8e Test errors emitted with various malformed stystrs
31f4c1d Overly aggressive color names check in styled strs
bec9216 Expand on faces tests
093385e Improve showing of RGB SimpleColors without MIME
d60d545 Test the show methods of SimpleColor and Face
cb05225 Test the AnnotatedIOBuffer printstyled method
c36911c Test the (legacy) loading of colors from envvars
14b4c6e Reduce test code verbosity by importing more names
3db948f Add a battery of HTML encoding tests
316bdd5 Remove extranious spaces from HTML underline style
62a7d25 Adjust named HTML colours to be not-garish
81e031e Add a battery of ANSI encoding tests
a14c3b1 Check the Smulx termcap instead of Su
b9d4aea Use the redmean colour distance in 8-bit approx
f9976ad More careful comma handling with inline face specs
24e10e4 Accept a style symbol as the sole underline value
2ba234a Use the hardcoded bold ANSI code
ab4f681 Refactro termcolor8bit to be less magic
a8b8aaf Fix off-by-one errors in termcolor8bit
21e127a Introduce fuzzer for styled markup
a3b40b7 Mention the loading of faces.toml in the docs
16c0e4f Fix functional parsing of inline face weight
7da631f Consolidate use of "ws" and "whitespace" in EBNF
b76c1ce Introduce ismacro convenience func to parser
b1cb60c Fix handling of space around inline face attrs
e22d058 Clarification in styled markup grammar docs
701d29f Introduce isnextchar convenience func to parser
6efb352 Fix edge-case parsing of empty face construct
10f6839 Implement new functional styled markup interpreter
e2d2d5f Refactor stylemacro into a submodule
11c5bd9 Introduce specialised write for AnnotatedIOBuffer
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
For bumping stdlibs to backports, what I'd recommend is telling BumpStdlibs to directly target the backports branch. So, you would run the BumpStdlibs bot again, and in the field for target branch, put `backports-release-1.11`.

**Comment by DilumAluthge** [comment]
Once that PR's been opened, we can remove the backport label from this PR.

**Comment by tecosaur** [comment]
Ah yep, might as well merge this PR to master too, but I'll open a 1.11 backports PR as you suggest :+1:.

**Comment by DilumAluthge** [comment]
The test failures look related to the contents of this PR:

```
Error in testset StyledStrings:
Error During Test at /cache/build/tester-amdci5-12/julialang/julia-master/julia-f4ef8a2f36/share/julia/test/testdefs.jl:24
  Got exception outside of a @test
  LoadError: UndefVarError: `@check` not defined in `Main.Test16Main_StyledStrings`
```

**Comment by DilumAluthge** [comment]
> I'll open a 1.11 backports PR

For reference, here is the 1.11 backport PR: https://github.com/JuliaLang/julia/pull/53923

**Comment by tecosaur** [comment]
> The test failures look related to the contents of this PR:

Ah, I attempted to copy Tar.jl's "extra CI tests when not being built as part of Julia itself" logic, but seems like it's not quite right if that's what's come up.

For reference, the copied test/logic is:

```julia
const NON_STDLIB_TESTS = Main == @__MODULE__
```

and this is what's in StyledStirngs's test suite:

```julia

if NON_STDLIB_TESTS
    function maybefuzz()
        isstyled(s) = StyledStrings.styled(s) isa Base.AnnotatedString
        max_examples = if hasparserdiverged()
            ifelse(IS_CI, 5_000, 10_000)
        else
            1_000
        end
        @testset "Fuzz ($max_examples)" begin
            @check max_examples = max_examples isstyled(Fuzzer.content)
        end
    end
else
    maybefuzz() = nothing
end
```

**Comment by tecosaur** [comment]
Ah, I think the problem is the `@check` macro (trying to be) expanded before the `if` branches.

**Comment by tecosaur** [comment]
Let's see if I've managed to fix this with the tweaked approach...

If #53942 looks fine, I'll open a new backport bump PR.

**Pull request closed without merging**
