### PR TITLE
add _IO_stdin_used to julia.expmap

### LINKED ISSUE #10982: Invalid free() on exit (32-bit build under valgrind)
It seems that julia attempts to call `free(0xffffffff)` on exit when built for 32 bits:

    $ valgrind --smc-check=all-non-file ./julia -e ""
    ==25616== Memcheck, a memory error detector
    ==25616== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
    ==25616== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
    ==25616== Command: ./julia -e 
    ==25616== 
    ==25616== Invalid free() / delete / delete[] / realloc()
    ==25616==    at 0x402A3A8: free (vg_replace_malloc.c:473)
    ==25616==    by 0x52ADBF4: __libc_freeres (in /lib/i386-linux-gnu/i686/cmov/libc-2.19.so)
    ==25616==    by 0x4023536: _vgnU_freeres (vg_preloaded.c:63)
    ==25616==    by 0x521CA5D: _Exit (_exit.S:29)
    ==25616==  Address 0xffffffff is not stack'd, malloc'd or (recently) free'd
    ==25616== 
    ==25616== 
    ==25616== HEAP SUMMARY:
    ==25616==     in use at exit: 42,884,254 bytes in 346,643 blocks
    ==25616==   total heap usage: 428,248 allocs, 81,606 frees, 58,625,310 bytes allocated
    ==25616== 
    ==25616== LEAK SUMMARY:
    ==25616==    definitely lost: 872 bytes in 4 blocks
    ==25616==    indirectly lost: 2,048 bytes in 1 blocks
    ==25616==      possibly lost: 293,182 bytes in 8,349 blocks
    ==25616==    still reachable: 42,588,152 bytes in 338,289 blocks
    ==25616==         suppressed: 0 bytes in 0 blocks
    ==25616== Rerun with --leak-check=full to see details of leaked memory
    ==25616== 
    ==25616== For counts of detected and suppressed errors, rerun with: -v
    ==25616== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

`Make.user` is as follows:

    CFLAGS = -DMEMDEBUG
    ARCH = i686

In fact, I can reproduce this both with and without `MEMDEBUG`.  I am running Debian jessie (64 bits).

### PR DESCRIPTION
**Pull request by tkelman**
fixes #10982 
cc @garrison

### CODE REVIEW

**Comment by garrison** [comment]
LGTM!

I wish I had more *understanding* of why this is necessary, but that is another matter.  In particular, I'm wondering if it's typical/expected to use a "version script" with a binary (i.e. `julia`), or whether they are really only meant to be used with libraries (e.g. `libjulia`).  In other words, are there any other symbols we really ought to be exporting?  The difference between using `julia.expmap` on `julia` itself and not using it (but still using it for `libjulia`) is fairly minimal:

    64   0: 0804cbd0     0 NOTYPE  GLOBAL DEFAULT  24 _edata
    66   0: 0804c9c0     0 NOTYPE  GLOBAL DEFAULT  24 __data_start
    67   0: 0804cbe4     0 NOTYPE  GLOBAL DEFAULT  25 _end
    68   0: 08049870  2637 FUNC    GLOBAL DEFAULT  13 parse_opts
    69   1: 0804c9c0     0 NOTYPE  WEAK   DEFAULT  24 data_start
    70   1: 0804a384     4 OBJECT  GLOBAL DEFAULT  15 _IO_stdin_used
    71   1: 0804a380     4 OBJECT  GLOBAL DEFAULT  15 _fp_hw
    72   1: 08049100   134 FUNC    GLOBAL DEFAULT  13 main
    73   1: 08049186     0 FUNC    GLOBAL DEFAULT  13 _start
    74   1: 08048e18     0 FUNC    GLOBAL DEFAULT  11 _init
    75   1: 0804cbd0     0 NOTYPE  GLOBAL DEFAULT  25 __bss_start
    76   1: 0804a2f0    97 FUNC    GLOBAL DEFAULT  13 __libc_csu_init
    77   2: 0804a364     0 FUNC    GLOBAL DEFAULT  14 _fini
    78   2: 0804a360     2 FUNC    GLOBAL DEFAULT  13 __libc_csu_fini

So an alternative patch would be to use `julia.expmap` on `libjulia` but *not* `julia`.  It's unclear to me which approach is more solid.

**Comment by garrison** [comment]
cc @Keno

**Comment by tkelman** [comment]
Yeah, I don't know either, but I figured it was worth sending through the CI at least.

**Comment by Keno** [comment]
From what I understand, one part of glibc uses the presence of this symbol to decide which version another part of it is and executes code conditional based one that. The version script hides the symbol and the version mismatch causes bad code to run. I think it would be fine to only use `julia.exmap` for libjulia and not for the executable.

**Comment by tkelman** [comment]
[The link command for the julia executable](https://github.com/JuliaLang/julia/blob/d777bccb870bf71355ac37299cb2d6bf31d51899/ui/Makefile#L71) is
`@$(call PRINT_LINK, $(CXXLD) $(CXXFLAGS) $(CXXLDFLAGS) $(LINK_FLAGS) $(SHIPFLAGS) $^ -o $@ -L$(build_private_libdir) -L$(build_libdir) -L$(build_shlibdir) -ljulia $(JLDFLAGS) $(CXXLDFLAGS))`

So we'd have to fiddle with some of these flag variables to split them out and differentiate between libjulia and the executable. Let's just merge this since it's easier, and see if it hurts anything.

**Pull request merged**
