### PR TITLE
🤖 Bump the Downloads stdlib from c91876a to f856630

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Downloads
URL: [https://github.com/JuliaLang/Downloads.jl](https://github.com/JuliaLang/Downloads.jl)
Branch: master
Old commit: c91876a
New commit: f856630
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline c91876a..f856630
f856630 Merge pull request #157 from JuliaLang/revert-156-revert-151-sk/no-libuv-sushi
43a3484 add missing locks during Timer callbacks
69acc13 Revert "Revert "stop using raw libuv API" (#156)"
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I am seeing some method errors and some unhandled task errors?

**Comment by DilumAluthge** [comment]
cc: @StefanKarpinski

**Comment by DilumAluthge** [comment]
Also cc @vtjnash

**Comment by DilumAluthge** [comment]
Oh, I forgot to mention. For Buildkite, these Downloads failures happened while running under rr, so we have rr traces.

You can download the rr trace directly from the Buildkite page. If you have trouble getting the rr trace, just let me know.

**Comment by StefanKarpinski** [comment]
The method errors are because Jameson's batch uses the `Timer` callback API wrong, so I've fixed those. I don't know about the unhandled task errors, which look like something with `FDWatcher`, but I figure it might have to do with the `Timer` usage being wrong, so lets see.

**Comment by DilumAluthge** [comment]
Just FYI, when you run the BumpStdlibs bot, it will automatically close old/outdated PRs, so you don't need to close them manually.

**Comment by vtjnash** [comment]
This sounds like a more serious error, since EBADF means the program has failed to close the uv_poll_t and is at risk of severe crashes.
```
      From worker 6:	UNHANDLED TASK ERROR: IOError: FDWatcher: bad file descriptor (EBADF)
      From worker 6:	Stacktrace:
      From worker 6:	 [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
      From worker 6:	   @ Base ./task.jl:777
      From worker 6:	 [2] wait()
      From worker 6:	   @ Base ./task.jl:837
      From worker 6:	 [3] wait(c::Base.GenericCondition{Base.Threads.SpinLock})
      From worker 6:	   @ Base ./condition.jl:124
      From worker 6:	 [4] wait(fdw::FileWatching._FDWatcher; readable::Bool, writable::Bool)
      From worker 6:	   @ FileWatching /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.8/FileWatching/src/FileWatching.jl:533
      From worker 6:	 [5] wait
      From worker 6:	   @ /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.8/FileWatching/src/FileWatching.jl:504 [inlined]
      From worker 6:	 [6] macro expansion
      From worker 6:	   @ /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:154 [inlined]
      From worker 6:	 [7] (::Downloads.Curl.var"#42#48"{Int32, FileWatching.FDWatcher, Downloads.Curl.Multi})()
      From worker 6:	   @ Downloads.Curl ./task.jl:423
```

**Pull request closed without merging**
