### PR TITLE
Set VERSION to 0.7.0-rc2

### PR DESCRIPTION
**Pull request by ararslan**
Master is still 0.7 since #28378 hasn't been merged yet, so this PR is against master.

To be merged first:

- [x] #28391: Iteration protocol deprecation fix
- [x] #28402: `__precompile__(false)` fix
- [x] #28387: Fix deprecated REPL reference in docs
- [x] #28389: Bitshift precedence deprecation fix
- [x] #28371: Auto-generate `precompile` statements
- [x] #26813: Use `require` properly in Distributed
- [x] #28403: LLVM patch

Please add and check off as you see fit.

### CODE REVIEW

**Comment by timholy** [comment]
Do we also need the fix for #28388?

**Comment by JeffBezanson** [comment]
We need everything with the "backport pending 0.7" label. Of course since there's no 0.7.1 that label is more or less equivalent to the 0.7 milestone.

**Comment by ararslan** [comment]
Are we going to do #28395?

**Comment by StefanKarpinski** [comment]
It would be fine. I worry about a late upgrade of OpenBLAS but it seems to fix issues mainly.

**Comment by ararslan** [comment]
That was my thinking as well. I'll let someone else determine whether we should go ahead with it. :grin:

**Review by Keno — APPROVED** [review]

**Pull request merged**
