### PR TITLE
Some fixes for Ranges without length

### PR DESCRIPTION
**Pull request by mschauer**
Fix UnitRange with StepRange comparison (and make it faster). Reverse range without using `length`.
Make `intersect(StepRange, UnitRange)` and `intersect(StepRange, StepRange)` uses `empty(s)` instead of `length(s)==0`. And some tests.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Looks pretty reasonable to me – thanks for adding tests! cc: @JeffBezanson

**Comment by mschauer** [comment]
I will still add a fix for
```
julia> 10 in -9223372036854775790:100:9223372036854775710
true

julia> 110 in -9223372036854775790:100:9223372036854775710
false
```

**Comment by mschauer** [comment]
> I will still add a fix for...

I am done so far. AppVeyor seem to hang.

**Comment by tkelman** [comment]
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.2327/job/ib3cqv48p4mwauw0 didn't hang, it just ran out of time because the tests were running much slower than usual - #10094

I'll restart it, since I think the issue is intermittent (and not windows-specific afaict).

**Comment by tkelman** [comment]
Oh, but https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.2331/job/xy247fyhpn7r26kk did hang. Different timeout failure modes on different commits here.

**Pull request merged**
