### PR TITLE
Rename files to corresponding modulename

### LINKED ISSUE #11302: File name conventions for modules in Base?
It seems like we have a number of different conventions for naming files that contain modules in Base. As far as single-file modules go, Enums, LineEdit, REPL, and REPLCompletions are in files that begin with a capital letter first, but all the other modules are in files that begin with lowercase letters. We're also not totally consistent about how we organize multiple file modules. In most cases, the module itself is in the base directory and the supporting files are in separate directories, but this is not true of the Markdown module. And while I could imagine an argument for distinguishing modules whose exported bindings are exported from Base and modules whose exported bindings are not, I don't think that can explain the current inconsistency.

This may be a pedantic request, but I think we should settle on a single convention and stick with it. While I think basically any rule is better than no rule, my first thought is that all modules should be named with capital letters first and multiple file modules should live in the same directory as their supporting files. I'm happy to do the work here if we can decide what we want.

### PR DESCRIPTION
**Pull request by fredrikekre**
Fix #11302 

Renames files in `/base/` to its corresponding module name as suggested in the issue.

Only diff from the general pattern is now `/base/sparse/SparseArrays.jl`, should it be `/base/sparsearrays/SparseArrays.jl`?

If its desired, multi-file modules can be gathered in a folder like some modules, like `Markdown`, already do. That is also mentioned in the issue, all though not yet included in this PR. Thanks!

### CODE REVIEW

**Comment by vtjnash** [comment]
This is likely going to cause massive headaches for devs on
case-insensitive systems. I'm not saying we shouldn't do it, just that we
should probably be careful not to reuse the same case-insensitive names
anytime in the near future.

**Comment by tkelman** [comment]
a way of avoiding that issue (at the moment) would be structuring each module within a subfolder of base

**Comment by fredrikekre** [comment]
All modules, or just multi-file modules as discussed in the issue?

**Comment by fredrikekre** [comment]
Obsolete with stdlibs.

**Pull request closed without merging**
