### PR TITLE
Fix for log colorization test due to merge overlap with #25289

### PR DESCRIPTION
**Pull request by c42f**
Emergency fix for CI due to merge overlap (CI race condition!) between #25370 and #25289

CC @KristofferC

### CODE REVIEW

**Comment by KristofferC** [comment]
Lgtm, let's merge quickly when this passes.

**Comment by nalimilan** [comment]
CircleCI failures look unrelated (timeout).

**Comment by andreasnoack** [comment]
```
Connection timed out after 15930 milliseconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0curl: (28) Connection timed out after 15000 milliseconds
/home/circleci/project/deps/pcre.mk:8: recipe for target '/home/circleci/project/deps/srccache/pcre2-10.30.tar.bz2' failed
make[1]: *** [/home/circleci/project/deps/srccache/pcre2-10.30.tar.bz2] Error 28
Makefile:83: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
Exited with code 2
```

**Comment by c42f** [comment]
FWIW, the full test suite passes locally.  Ah, and I see FreeBSD has completed successfully.

By the way I think we could fix the above category of CI timeout pretty simply by caching tarballs of the thirdparty deps in an S3 bucket (bonus points for putting the bucket it in the same region as the CI system).  I did this for a previous build system and it worked really nicely.

**Comment by StefanKarpinski** [comment]
AppVeyor 32-bit failure is a timeout; Circle CI failures seem to be some kind of build problem.

**Pull request merged**
