### PR TITLE
Set VERSION to 1.2.0-DEV

### PR DESCRIPTION
**Pull request by ararslan**
Since we've branched for 1.1. (This should have been the first thing merged after branching but ¯\\\_(ツ)\_/¯)

### CODE REVIEW

**Comment by ararslan** [comment]
Ah, good ol' Pkg test failures due to version compatibility bounds.

**Comment by StefanKarpinski** [comment]
Sure, but I'm not sure we need a dummy commit anymore, tbh. Let's see how it goes.

**Comment by fredrikekre** [comment]
Yes, packages are not installable on Julia 1.2 since they are all capped on Julia 1.1

**Comment by ararslan** [comment]
See https://github.com/JuliaLang/Pkg.jl/pull/962

**Comment by ararslan** [comment]
```
Error During Test at /tmp/julia/share/julia/stdlib/v1.2/Pkg/test/registry.jl:262
  Got exception outside of a @test
  Unsatisfiable requirements detected for package Example [7876af07]:
   Example [7876af07] log:
   ├─possible versions are: 0.5.0 or uninstalled
   ├─restricted to versions * by an explicit requirement, leaving only versions 0.5.0
   └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by JeffBezanson** [comment]
How about also moving 1.1 news to history at the same time?

**Comment by ararslan** [comment]
> How about also moving 1.1 news to history at the same time?

Doable, just have to figure out what was merged since branching that won't be backported to 1.1, since those items are applicable to 1.2.

**Comment by ararslan** [comment]
Fredrik has suggested that we hold off on that for a bit, since it will make backporting changes to `release-1.1` annoying. That seems reasonable to me.

**Comment by ararslan** [comment]
Kristoffer agrees. The Swedes have spoken, let's wait until 1.1 is released.

**Pull request merged**
