### PR TITLE
Fix many GC related bugs

### PR DESCRIPTION
**Pull request by yuyichao**
- Make `jl_linenode_line` non-allocating
- Fix missing GC root when calling `jl_fieldref` and `jl_get_nth_field`
  that can possibly allocate
- Add missing write barrier when using heap allocated array as stack buffer
- Remove allocations from `jl_static_show_x`
- Fix missing and extra `JL_GC_POP`
- Fix misplaced `JL_GC_PUSH*`

@carnaval 

@vtjnash, @stevengj Could you please have a look at the changes in [ccall.cpp](https://github.com/JuliaLang/julia/commit/3f35ccef2352744f307c2abcaf018c18bf43d795#diff-be60d844ffde1319a02946d17c472e46L886) and [dump.c](https://github.com/JuliaLang/julia/commit/3f35ccef2352744f307c2abcaf018c18bf43d795#diff-669d4cc5c9c8f4573c5f8d57f5dcab20R1030) I discovered these by accident. I think this should be the right fix but are these code path so cold (and combined with the gc stack pointer reset on exception) that they never causes a real issue?

### CODE REVIEW

**Comment by yuyichao** [comment]
Most of these are in 0.4 as well. (A few are possibly even in 0.3 if we ever want a new 0.3 release). The patch may not apply cleanly so I'll cherry pick this on release-0.4 after this is merged to master...

**Comment by tkelman** [comment]
Please don't cherry pick directly to the release branch, open a pr. Nothing else is going into 0.4.0 without being run through pkgeval first

**Comment by yuyichao** [comment]
> Please don't cherry pick directly to the release branch, open a pr. Nothing else is going into 0.4.0 without being run through pkgeval first

Yes, that's what I meant.

**Comment by yuyichao** [comment]
Travis failures are https://github.com/JuliaLang/julia/pull/13322

**Comment by yuyichao** [comment]
OK. I've now removed all (AFAIK) GC allocations in `jl_static_show`. This is useful when debugging memory related issues since the GC may be corrupted or may introduce unwanted side effects (e.g. change the address between different runs).

@carnaval You should be able to safely use `jl_` even when the heap is totally corrupted now.

**Comment by pao** [comment]
cf, mentioned by @yuyichao as possible fix for "Double free or corruption" with NLOpt: https://groups.google.com/forum/#!topic/julia-users/FV9AmKsZNuk

**Comment by carnaval** [comment]
seems ok to me. thanks!

**Comment by yuyichao** [comment]
CI all pass after the OSX backtrace test is fixed. I've also verified that running the NLopt test with GC at every single allocation and GC scrub do not segfault anymore (took ~5-10h to run). I'll merge this tomorrow unless someone tell me not to.

@tkelman The cherry picked commits are at the [yyc/gc/getfield-0.4 branch](https://github.com/JuliaLang/julia/tree/yyc/gc/getfield-0.4). Since most of these are only needed for debugging (all `jl_static_show` changes) or in very special cases (files longer than 511 lines and GC triggers exactly at the right time...) and given no one has noticed these for months on the master, I think you can take your time running the PkgEval and not including this in rc3. I can open a PR if it is easier for you.

**Comment by tkelman** [comment]
thanks for resolving the conflict. unless another conflict arises that i need help resolving, they're good where they are and I'll bring them into a branch (rebased to post-rc3) when i'm ready to test them

**Comment by vtjnash** [comment]
these changes look good to me.

another unrelated gc bug i noticed recently is that `ctx->gc.argDepth` is not being saved/restored in emit_llvm. @Keno, this means that if Cxx.jl is using an expression of the form `jlcall(llvmcall(jl_value_t), arg2)`, the boxed arguments to the llvmcall may end up inserted into the args list for the outer jlcall

**Pull request merged**
