### PR TITLE
RFC: Deprecate `and`, `or`, and `not` as identifier names

### PR DESCRIPTION
**Pull request by martinholters**
Please leave the discussion of `and`/`or`/`not` versus `&&`/`||`/`!` to #5238. The aim of this PR is to allow that decision to be taken after 1.0, not to push it in one way or the other.

### CODE REVIEW

**Comment by bramtayl** [comment]
It seems like we'd want to reserve a set of aliases both for `&`/`|` and for `&&`/`||`. My personal favorite is `and`/`or` and `andthen`/`orelse` but not really bothered as long as words are involved.

**Comment by StefanKarpinski** [comment]
That's a complete non-sequitur. We're not going to start spelling out all non-alphabetic operators. This reserves the obvious names for the only two control flow operators we have plus `not`.

**Comment by quinnj** [comment]
Does `not` need to be included here? I can't you just do `const not = !`?

**Comment by StefanKarpinski** [comment]
It's included because it's used in `Python` in addition to `and` and `or` and `x not in y` is a potentially better syntax for `!(x in y)`; while `x !in y` would also be possible, it's not quite so legible. We may decide we don't want to do this and re-allow `and`, `or` and `not` but in the meantime, this gives us the option to follow languages that use these names as operators. Having two of three available to use seems like it's not worth doing, and it's not as if `not` is a super popular identifier name – all of these would be a confusing identifier names, in fact.

**Comment by martinholters** [comment]
Added the link to the NEWS entry. @ararslan were you missing anything more when you added the "needs news" tag?

Regarding the test, I  followed the approach of
https://github.com/JuliaLang/julia/blob/beb752629afe18539845826b61ac8b3859cba1d8/test/arrayops.jl#L313-L325.

I hope that is ok, given how little precedent we have for testing deprecations.

**Comment by JeffBezanson** [comment]
I don't think we're going to change this syntax, so this is not necessary.

**Comment by martinholters** [comment]
> I don't think we're going to change this syntax

Feel free to remove the triage label and close this. But if you do, please also (re-)close #5238 along with a definite comment.

**Comment by martinholters** [comment]
@ararslan I take the removal of the triage label as saying "we have reached a decision". That's fine with me. (I personally don't care much about the syntax.) But _please_ do comment on #5238, saying "XXX discussed this and decided to keep `&&` and `||`" for whatever XXX it is here. (Did you discuss this on a triage call?) Then close #5238 and hope this ends the discussion.

**Comment by StefanKarpinski** [comment]
This was not discussed since the triage label was imo prematurely removed. Jeff saying this isn't going to happen isn't the same as discussing and coming to a decision. I'm still supportive of reserving this syntax, fwiw.

**Comment by JeffBezanson** [comment]
I think it's silly to steal identifier names; we might as well let people use them.

**Comment by ararslan** [comment]
Triage said we aren't going to do this; we'll allow them as identifiers.

**Comment by martinholters** [comment]
Thanks for discussion it!

**Pull request closed without merging**
