### PR TITLE
deprecate `&`, `|`, and `xor` for 1 or >2 arguments

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by iblis17** [comment]
hmm, endless error message in freebsd ci (https://julia.iblis.cnmc.tw/#/builders/1/builds/570) ?
It has run for 3 hours .... I'm going to cancel this build.

**Comment by JeffBezanson** [comment]
Ah, there are still some uses of multi-arg `xor`. Since that now uses prefix call syntax, it doesn't seem so bad to allow it. So then maybe we should just not do this change?

**Comment by simonbyrne** [comment]
Why do we want to get rid of these?

**Comment by JeffBezanson** [comment]
Because I like deleting stuff :) But yeah, might be pointless.

**Comment by simonbyrne** [comment]
I was going to say it would conflict with #7368, but I didn't realise that had been closed.

**Pull request closed without merging**
