### PR TITLE
WIP: Implement simple tilde expansion and globbing

### PR DESCRIPTION
**Pull request by timholy**
This at least partially implements #1136. This does not support `~someotheruser` notation.

Once I learned more about how backticks worked, it was so dirt-simple that I'm suspicious this is overlooking something big. @StefanKarpinski in particular please review.

I'd really like to get this merged for 0.2. Globbing would be even nicer. Is shell-parse the right place to put that? It seems quite a bit more complicated.

### CODE REVIEW

**Comment by blakejohnson** [comment]
Is this closed because Tim indicated that continuing it was not in his wheelhouse?

**Comment by StefanKarpinski** [comment]
So there are two pieces: user expansion and globbing. @vtjnash has implemented POSIX globbing in [Glob.jl](https://github.com/vtjnash/Glob.jl). A good approach to handling globbing would be to move the code from Glob.jl into Base and hook it up to backtick parsing. User expansion is a little harder. We need to use the correct APIs on each system for mapping user names to home directories – I'm not even sure that those APIs are. Maybe looking at an MIT or BSD-license shell implementation would be a good start.

**Comment by quinnj** [comment]
Or python's `os.expanduser` function.

On Tue, Mar 24, 2015 at 10:39 AM, Stefan Karpinski <notifications@github.com

**Comment by timholy** [comment]
@blakejohnson, if it were an issue, then it should stay open until the issue was addressed. But this was a pull request---one that is probably not a good starting point for implementation---so I agree with @Keno's having closed it.

**Comment by Sean1708** [comment]
@StefanKarpinski I made some changes to the Unix implementation of `expanduser` in #8668 though there were some (non-fatal) issues with the linux build. I'm not sure how much it'll help but it might make a good starting point.

**Pull request closed without merging**
