### PR TITLE
Bump Pkg

### PR DESCRIPTION
**Pull request by KristofferC**
* Fix a bug where `dev` would not pull the latest git revision.
* Improve error message when `dev`eloping packages, thanks @innerlee 
* Add `setprotocol!` to Pkg3.
* Only update the registry on first add, instead of every add.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Btw, you can reuse branch names once a previous PR with the same branch name has been merged.

**Comment by KristofferC** [comment]
So this breaks the OldPkg tests... Interesting.

**Comment by KristofferC** [comment]
Seems like the same OldPkg error in https://github.com/JuliaLang/julia/pull/27927#issuecomment-402429157

**Comment by KristofferC** [comment]
But this PR seems to make that problem much worse...

**Comment by KristofferC** [comment]
I guess what is happening is that `using Example` picks up an Example from a project file (which has a UUID) but the `OldPkg` checks for an Example with no UUID to write the imported package has been updated warning. So something from Pkg (an Example installation) is left such that OldPkg picks it up.

**Comment by KristofferC** [comment]
@iblis17 I think I corrupted the Freebsd build bot state by modifying the `~/.julia/v0.7/environment` files because my tests were not isolated properly...

**Comment by iblis17** [comment]
@KristofferC So can I remove that file safely?

```diff
diff --git a/.freebsdci.sh b/.freebsdci.sh
index d55ca329e4..b4a93876be 100755
--- a/.freebsdci.sh
+++ b/.freebsdci.sh
@@ -22,6 +22,7 @@ build-state(){

 cleanup(){
     git clean -fdx
+    rm -rv $HOME/.julia
 }

 compile(){
```

**Comment by KristofferC** [comment]
Yes, should be fine.

**Comment by iblis17** [comment]
I cannot find the file `~/.julia/v0.7/environment`, but a dir `~/.julia/environments`.
Anyway... I removed `~/.julia` at both of my workers.

**Comment by KristofferC** [comment]
CI failures are failure in download (FreeBSD + AV) and FileWatching on one Travis worker.

**Comment by vtjnash** [comment]
This appears to be responsible for causing frequent AV test failures. Please fix ASAP, since I'm not exactly sure how to do the usual revert with this workflow.
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.28580/job/9ngkjahgltj7vcaj
```
┌ Error: mktempdir cleanup
2907│   exception =
2908│    unlink: resource busy or locked (EBUSY)
2909│    Stacktrace:
2910│     [1] uv_error at .\libuv.jl:80 [inlined]
2911│     [2] unlink(::String) at .\file.jl:715
2912│     [3] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:253
2913│     [4] #rm at .\none:0 [inlined]
2914│     [5] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:263
2915│     [6] #rm at .\none:0 [inlined]
2916│     [7] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:263
2917│     [8] #rm at .\none:0 [inlined]
2918│     [9] mktempdir(::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##51#57")), ::String) at .\file.jl:573
2919│     [10] mktempdir at .\file.jl:567 [inlined]
2920│     [11] #50 at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\pkg.jl:349 [inlined]
2921│     [12] cd(::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##50#56")), ::String) at .\file.jl:85
2922│     [13] macro expansion at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\pkg.jl:1090 [inlined]
2923│     [14] (::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##49#54")))(::String) at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\pkg.jl:336
2924│     [15] #2 at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\utils.jl:22 [inlined]
2925│     [16] mktempdir(::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##2#4")){String,getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##49#54"))}, ::String) at .\file.jl:569
2926│     [17] mktempdir at .\file.jl:567 [inlined]
2927│     [18] #1 at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\utils.jl:19 [inlined]
2928│     [19] mktempdir(::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##1#3")){getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##49#54"))}, ::String) at .\file.jl:569
2929│     [20] mktempdir at .\file.jl:567 [inlined]
2930│     [21] temp_pkg_dir(::getfield(Main.Test18Main_Pkg_pkg.OperationsTest, Symbol("##49#54"))) at C:\projects\julia\julia-96df724aa6\share\julia\stdlib\v0.7\Pkg\test\utils.jl:18
2931│     [22] top-level scope at none:0
2932│     [23] include at .\boot.jl:317 [inlined]
2933│     [24] include_relative(::Module, ::String) at .\loading.jl:1034
2934│     [25] include at .\sysimg.jl:29 [inlined]
2935│     [26] include(::String) at C:\projects\julia\julia-96df724aa6\share\julia\test\testdefs.jl:13
2936│     [27] macro expansion at C:\projects\julia\julia-96df724aa6\share\julia\test\testdefs.jl:292 [inlined]
2937│     [28] macro expansion at C:\projects\julia\usr\share\julia\stdlib\v0.7\Test\src\Test.jl:1080 [inlined]
2938│     [29] macro expansion at C:\projects\julia\julia-96df724aa6\share\julia\test\testdefs.jl:21 [inlined]
2939│     [30] macro expansion at .\util.jl:289 [inlined]
2940│     [31] top-level scope at C:\projects\julia\julia-96df724aa6\share\julia\test\testdefs.jl:19 [inlined]
2941│     [32] top-level scope at .\<missing>:0
2942│     [33] eval at .\boot.jl:319 [inlined]
2943│     [34] #runtests#3(::UInt128, ::Function, ::String, ::String, ::Bool) at C:\projects\julia\julia-96df724aa6\share\julia\test\testdefs.jl:25
2944│     [35] #runtests at .\none:0 [inlined] (repeats 2 times)
2945│     [36] (::getfield(Distributed, Symbol("##112#114")){Distributed.CallMsg{:call_fetch}})() at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\process_messages.jl:269
2946│     [37] run_work_thunk(::getfield(Distributed, Symbol("##112#114")){Distributed.CallMsg{:call_fetch}}, ::Bool) at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\process_messages.jl:56
2947│     [38] macro expansion at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\process_messages.jl:270 [inlined]
2948│     [39] (::getfield(Distributed, Symbol("##111#113")){Distributed.CallMsg{:call_fetch},Distributed.MsgHeader,Sockets.TCPSocket})() at .\task.jl:257
2949└ @ Base.Filesystem file.jl:575
```

**Comment by KristofferC** [comment]
That would be good to fix but is not as test failure (as in that it doesn't fail the build).

**Comment by KristofferC** [comment]
The reason I didn't see this before merging is that you, in the recent PR called "minor test improvements" changed it from erroring to just logging https://github.com/JuliaLang/julia/pull/27508/commits/67c690f667bb62b52431e9af1240bcc1a20494c2.

**Comment by vtjnash** [comment]
Right - it’s confusing that `finally` prints the wrong stacktrace and error sometimes, so I probably shouldn’t have copied that above since it’s misleading. This actually did cause a test failure (which later led to the above warning).

**Comment by KristofferC** [comment]
Can you then link to the actual test failure so I know what needs to be fixed.

**Pull request merged**
