### PR TITLE
Tag v0.6.1

### PR DESCRIPTION
**Pull request by ararslan**
It's taggin' time.

[bsd skip]

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by mauro3** [comment]
Just wondering, what is holding this up?

**Comment by fredrikekre** [comment]
Presumably #24265

**Comment by ararslan** [comment]
Yep, exactly.

**Comment by ararslan** [comment]
Okay, this is good to go now.

**Review by fredrikekre — APPROVED** [review]

**Comment by tkelman** [comment]
Coverage.jl still fails tests on the release branch, something about your processing of pkgeval results is missing that

**Comment by ararslan** [comment]
Yes it's still failing, and PkgEval caught it. I'm going to add logic to that package to adjust on 0.6.1 in addition to 0.7.0.

**Comment by ararslan** [comment]
Coverage fix merged and I got the go-ahead from @ViralBShah to merge this, so here we go, folks!

**Pull request merged**
