### PR TITLE
RFC: Add ⊇, ⊉, ⊋ analogous to ⊆, ⊈, ⊊. (#21461)

### PR DESCRIPTION
**Pull request by SaschaMann**
Issue #21461.

This adds definitions for `⊇, ⊉, ⊋` based on `⊆, ⊈, ⊊`.

### CODE REVIEW

**Comment by tkelman** [comment]
:+1:

Looks like the existing docstring for `issubset` is still in `base/docs/helpdb/Base.jl`, and it isn't explaining the distinction between the unicode aliases all that well.

**Comment by SaschaMann** [comment]
I can add an explanation/examples for the unicode aliases to the docs.

One question about it, though. Why are there two different entries for `issubset` in the docs? What's the difference between them? https://github.com/JuliaLang/julia/blob/master/base/docs/helpdb/Base.jl#L2083-L2099

The second one shows up under "Set-Like Collections", the first under "Iterable collections" in the generated docs. From my understanding the unicode aliases (except for ⊇) are explicitely defined for just `::Set` parameters, though. Is that a mistake?

**Review by StefanKarpinski — APPROVED** [review]

**Comment by tkelman** [comment]
Good question. We could try hunting down via blame where the two docstrings originally came from, see if that helps find out why they're separate.

**Review by ararslan — APPROVED** [review]
Nice work here!

**Review by Sacha0 — APPROVED** [review]

**Comment by tkelman** [comment]
For now we can just add the aliases below the ascii names in the existing docstrings, but a cleanup as followup to consolidate (and move from helpdb to inline) would be good.

**Comment by tkelman** [comment]
still need adding to the docstrings

**Comment by StefanKarpinski** [comment]
go for it

**Comment by tkelman** [comment]
Adding the exports here broke packages that were using private versions of these operators. Given this was 2 months post feature-freeze, I'm inclined to revert this on release-0.6.

**Comment by JeffBezanson** [comment]
Which packages? I'd also like to know exactly how that happened, since we dropped the default `importall Base.Operators`. Which brings up the fact that these operators were not added to the Operators module, and probably should be. (Except we probably also want to eliminate the Operators module.)

**Comment by tkelman** [comment]
IntervalSets now gets a "both IntervalSets and Base export "⊇"; uses of it in module Main must be qualified" error because it had been exporting its local version.

**Comment by martinholters** [comment]
Would there be a benefit to only referring the export, given that we probably do want this post 0.6?

**Comment by JeffBezanson** [comment]
Yes, if we only remove the exports then packages will have the option of extending the Base operator, which will be more future-proof.

**Pull request merged**
