### PR TITLE
mpfr.jl: don't add extra zero when pretty-printing BigFloats

### PR DESCRIPTION
**Pull request by waldyrious**
Tweak `_prettify_bigfloat()` in `mpfr.jl` to not add a trailing zero to the representation of a `BigFloat`.

Addresses a question by @jishnub from [this Discourse thread](https://discourse.julialang.org/t/why-is-big-0-5-printed-as-0-50/59395).

Before:

```julia
julia> big(0.5)
0.50
```

After:

```julia
julia> big(0.5)
0.5
```

### CODE REVIEW

**Comment by waldyrious** [comment]
For reference, this sort of follows-up #29211, which changed the output of `big"0.5"` from

    5.0e-1

to the current

    0.50

I believe this is a progression in the same spirit, but pinging @rfourquet just to be safe.

**Comment by JeffBezanson** [comment]
Thanks, LGTM. Could you add a test?

**Review by rfourquet — APPROVED** [review]
LGTM, thanks!

**Comment by waldyrious** [comment]
Where should I put the test? Perhaps [here](https://github.com/JuliaLang/julia/blob/c4fc095fffaa5c5a3c4375dca2e93b580a7cb1e3/test/mpfr.jl#L671), like this?

```diff
 @testset "string representation" begin
     str = "1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012"
     setprecision(406) do
         @test string(nextfloat(BigFloat(1))) == str
     end
     setprecision(21) do
         @test string(parse(BigFloat, "0.1")) == "0.10000002"
+        @test string(parse(BigFloat, "0.5")) == "0.5"
         @test string(parse(BigFloat, "-9.9")) == "-9.9000015"
     end
     setprecision(40) do
         @test string(parse(BigFloat, "0.1")) == "0.10000000000002"
+        @test string(parse(BigFloat, "0.5")) == "0.5"
         @test string(parse(BigFloat, "-9.9")) == "-9.8999999999942"
     end
     setprecision(123) do
         @test string(parse(BigFloat, "0.1")) == "0.0999999999999999999999999999999999999953"
+        @test string(parse(BigFloat, "0.5")) == "0.5"
         @test string(parse(BigFloat, "-9.9")) == "-9.8999999999999999999999999999999999997"
     end
 end
```

Or perhaps [here](https://github.com/JuliaLang/julia/blob/c4fc095fffaa5c5a3c4375dca2e93b580a7cb1e3/test/mpfr.jl#L985) would be more appropriate?

```diff
    for to_string in [string,
                      x->sprint(show, x),
                      x->sprint(show, x, context=:compact => true)]
        @test to_string(big"0.0") == "0.0"
        @test to_string(big"-0.0") == "-0.0"
+       @test to_string(big"0.5") == "0.5"
+       @test to_string(big"-0.5") == "-0.5"
        @test to_string(big"1.0") == "1.0"
        @test to_string(big"-1.0") == "-1.0"

    end
```

Or something else? Please let me know.

**Comment by musm** [comment]
> Where should I put the test? Perhaps [here](https://github.com/JuliaLang/julia/blob/c4fc095fffaa5c5a3c4375dca2e93b580a7cb1e3/test/mpfr.jl#L671), like this?
> 
> ```diff
>  @testset "string representation" begin
>      str = "1.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012"
>      setprecision(406) do
>          @test string(nextfloat(BigFloat(1))) == str
>      end
>      setprecision(21) do
>          @test string(parse(BigFloat, "0.1")) == "0.10000002"
> +        @test string(parse(BigFloat, "0.5")) == "0.5"
>          @test string(parse(BigFloat, "-9.9")) == "-9.9000015"
>      end
>      setprecision(40) do
>          @test string(parse(BigFloat, "0.1")) == "0.10000000000002"
> +        @test string(parse(BigFloat, "0.5")) == "0.5"
>          @test string(parse(BigFloat, "-9.9")) == "-9.8999999999942"
>      end
>      setprecision(123) do
>          @test string(parse(BigFloat, "0.1")) == "0.0999999999999999999999999999999999999953"
> +        @test string(parse(BigFloat, "0.5")) == "0.5"
>          @test string(parse(BigFloat, "-9.9")) == "-9.8999999999999999999999999999999999997"
>      end
>  end
> ```
> 
> Or perhaps [here](https://github.com/JuliaLang/julia/blob/c4fc095fffaa5c5a3c4375dca2e93b580a7cb1e3/test/mpfr.jl#L985) would be more appropriate?
> 
> ```diff
>     for to_string in [string,
>                       x->sprint(show, x),
>                       x->sprint(show, x, context=:compact => true)]
>         @test to_string(big"0.0") == "0.0"
>         @test to_string(big"-0.0") == "-0.0"
> +       @test to_string(big"0.5") == "0.5"
> +       @test to_string(big"-0.5") == "-0.5"
>         @test to_string(big"1.0") == "1.0"
>         @test to_string(big"-1.0") == "-1.0"
> 
>     end
> ```
> 
> Or something else? Please let me know.

Yes, that looks reasonable to me.

**Comment by waldyrious** [comment]
Ok, I've amended the previous commit to add a test, and while I was at it, added a new commit with a few minor cleanup changes to `test/mpfr.jl` — hope that's OK!

**Review by rfourquet — APPROVED** [review]

**Comment by musm** [comment]
> edit: Looks like I slightly misunderstood your comment, @musm — did you mean to approve the first diff, the second, or both?

Ah yea, I didn't quote the right one. What you have updated is exactly what I meant to agree to 👍

**Comment by musm** [comment]
are test failures a known fluke https://build.julialang.org/#/builders/83/builds/2920/steps/5/logs/stdio ?

**Pull request merged**
