### PR TITLE
Fix #11092

### LINKED ISSUE #11092: reflection test failure when run with include_from_node1
When I run
`julia --code-coverage=all`
```
import(CoverageBase)
using Base.Test
CoverageBase.runtests(CoverageBase.testnames())
```
specifically **with** inlining, the tests immediately fail with:
```
reflection
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
ERROR: LoadError: test failed: ("/Users/kshyatt/Projects/julia/test/reflection.jl" == "reflection.jl")
 in expression: (functionloc(foo7648,(Any,)))[1] == "reflection.jl"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in anonymous at /Users/kshyatt/.julia/v0.4/CoverageBase/src/CoverageBase.jl:38
 in cd at file.jl:20
 in runtests at /Users/kshyatt/.julia/v0.4/CoverageBase/src/CoverageBase.jl:35
while loading /Users/kshyatt/Projects/julia/test/reflection.jl, in expression starting on line 150
```
which does not occur when I run the tests starting Julia with `--inline-no`.

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

**Comment by simonster** [comment]
But apparently this doesn't work, because `@__FILE__` is not defined properly when the tests are run in parallel... :frowning:

**Comment by tkelman** [comment]
> `@__FILE__` is not defined properly when the tests are run in parallel...

Really? Bugs upon bugs today.

**Comment by simonster** [comment]
I think the `@__FILE__` issue also results from the `Core.include` hack, because `@__FILE__` uses `Base.source_path`, which is only going to work when the file was loaded through `include_from_node1`. I made it work by passing `joinpath(dirname(@__FILE__), "reflection.jl")` through `abspath`, which doesn't hurt anything if it is already an absolute path and fixes it if it's not.

I still think it would be better to make `include_from_node1` do a local include if the worker is on the same system as node 1 so that we can get rid of the `Core.include` hack without slowing the tests down, but at least this fix works from both the REPL and the harness.

**Comment by kshyatt** [comment]
I guess it's a good thing I got a bee in my bonnet about tests today

**Comment by tkelman** [comment]
Yep. I had noticed the amount of red at http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64 for a while but wasn't too motivated to dig into it. Thanks for poking it, work towards making it green again.

This change LGTM if CI is green. cc @mauro3 who wrote the test in question.

**Comment by StefanKarpinski** [comment]
@kshyatt – it's the best bee! 🐝

**Comment by tkelman** [comment]
32 bit failure on travis is almost definitely unrelated, there's still some memory corruption somewhere (#11003?)

**Comment by mauro3** [comment]
LGTM and sorry for introducing a bad test.

**Pull request merged**
