### PR TITLE
src/task.c: Use `b` instead of `br` instruction on armv7l

### PR DESCRIPTION
**Pull request by staticfloat**
Fixes https://github.com/JuliaLang/julia/issues/29710

### CODE REVIEW

**Comment by yuyichao** [comment]
Did you check this works? I think `b` can only work with label.

**Comment by staticfloat** [comment]
I am compiling it on a raspberry pi right now, but it is indeed quite slow.  I will update this once it is built.

**Comment by yuyichao** [comment]
And what I wrote before and what I mentioned in the comments was `b start_task`.

**Comment by staticfloat** [comment]
I thought we were passing in the location to branch to via `%1`?  Or are you saying to use `b start_task %1;`?

**Comment by staticfloat** [comment]
Okay, I see what you're saying now.  I feel like Jameson intended for us to have the flexibility of passing in arbitrary function addresses though, so I will revert to using `bx` instead of `b`.

**Comment by yuyichao** [comment]
The question I asked in the issue was exactly about this. What was the point of being flexible here? Is there plan to make it not a constant? (If so, that should be commented since the current version is pretty confusing.....)

**Comment by staticfloat** [comment]
@vtjnash Do we actually need the arbitrary function pointer?  If not, is there a performance improvement to using `b` instead of `bx`?

**Comment by yuyichao** [comment]
The code will be shorter and there will be one fewer relocation. It's not a particularly important performance improvement to have but it's confusing only because the more optimized form is actually very simple...

**Comment by vtjnash** [comment]
it just keeps the code-paths more common

**Comment by yuyichao** [comment]
But direct jump to label is available on all platforms?

**Comment by staticfloat** [comment]
With these changes, the code at least compiles and makes it partway through the test suite on an RPi 3B+.

**Comment by staticfloat** [comment]
Okay the confirmed test error that I'm hitting is the following:

```
vecelement: Error During Test at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/vecelement.jl:71
  Test threw exception
  Expression: a[2] == Gr(1.0, Bunch((VecElement(2.0), VecElement(3.0))), 4.0)
  StackOverflowError:
  Stacktrace:
   [1] Main.Test40Main_vecelement.Bunch(::Tuple{VecElement{Float64},VecElement{Float64}}) at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/vecelement.jl:35
   [2] top-level scope at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/vecelement.jl:71
   [3] include at ./boot.jl:317 [inlined]
   [4] include_relative(::Module, ::String) at ./loading.jl:1038
   [5] include at ./sysimg.jl:29 [inlined]
   [6] include(::String) at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/testdefs.jl:13
   [7] top-level scope at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/testdefs.jl:22
   [8] top-level scope at /home/pi/tmp/julia-build/julia-sf/fixarm/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [9] top-level scope at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/testdefs.jl:21
   [10] top-level scope at util.jl:289
   [11] top-level scope at /home/pi/local/dist/julia-sf/fixarm/share/julia/test/testdefs.jl:19
```

This seems unrelated to the changes on this branch though, so I think we are ready to merge these fixes.

**Comment by ararslan** [comment]
Now that we've branched for 1.1, I assume this should be backported to 1.1?

**Comment by ararslan** [comment]
Is 1.0 affected by this? I thought the commit that broke ARM support wasn't backported.

**Comment by staticfloat** [comment]
oh you are so right

**Comment by ararslan** [comment]
What else needs to happen before this can be merged and backported to 1.1?

**Comment by staticfloat** [comment]
I think this can be merged; I got my Firefly board this morning, so I've been working towards getting true Armv7l buildbots working again, but I think any further changes should be done on different PRs.

**Pull request merged**
