### PR TITLE
Deprecate (un)escape_string to Unicode.(un)escape

### PR DESCRIPTION
**Pull request by ararslan**
This PR deprecates `escape_string` and `unescape_string` to `Unicode.escape` and `Unicode.unescape`, respectively. Further, `escape_string` and `unescape_string` are kind of odd functions in that they'll either return a string or print to a stream depending on the presence of an `IO` argument, so this PR also deprecates the `IO` methods to use `print`. That way `Unicode.escape` and `Unicode.unescape` always return strings.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
-1. I don't really see these as Unicode functions. The `io` argument also allows them to print more efficiently, without creating an intermediate copy.

**Comment by ararslan** [comment]
Do we have any other function that behaves that way?

**Comment by StefanKarpinski** [comment]
I also don't see what this function has to do with Unicode. If we had a `Strings` modules, this would be a thing I could see calling as `Strings.escape` and `Strings.unescape`.

**Comment by ararslan** [comment]
Yeah it isn't really Unicode-specific, I mostly put it in the Unicode module since it's the closest thing we have to a stdlib package we have for "extra" string utilities.

**Pull request closed without merging**
