### PR TITLE
use Ref in getipaddr and improve type stability

### PR DESCRIPTION
**Pull request by stevengj**
Just a slight improvement I noticed when I was doing something else.

### CODE REVIEW

**Comment by stevengj** [comment]
AppVeyor failure seems to be #16555.

**Comment by stevengj** [comment]
Merging, since this seems uncontroversial.

**Comment by tkelman** [comment]
what about this improves type stability?

**Comment by yuyichao** [comment]
Not reassigning a variable to a different type. This is the known limitation of type inference/codegen that generates inefficient code for type unstable variable even though each use of the variable have a leaftype.

**Comment by stevengj** [comment]
Yeah, unfortunately it's a quite common pattern to do
```
function foo(x)
   x = canonicalize(x)
   ...
end
```
so that `x` changes type.

**Pull request merged**
