### PR TITLE
[WIP] improved dense-sparse and sparse-dense matrix multiplication kernels

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request provides improved dense-sparse matrix multiplication kernels. ~Equivalent kernels for sparse-dense matrix multiplication to follow.~ (Edit: Equivalent kernels for sparse-dense matrix multiplication have landed.) Further optimization of the trickier cases in this pull request (see comments) also to follow.

Performance in a machine learning application from @pevnak motivated this pull request (see slack/#linalg). Specifically, IIRC TensorFlow outperforms Flux on master on his problem, whereas with these kernels (and the ~~forthcoming~~ sparse-dense equivalents) the tables turn.

Comprehensive benchmarks ~~forthcoming~~ (via BaseBenchmarks PR https://github.com/JuliaCI/BaseBenchmarks.jl/pull/128).

Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
Equivalent kernels for sparse-dense matrix multiplication are now live in the second commit. I have a third commit that consolidates the dense-sparse and sparse-dense methods, but would like to run nanosoldier before and after pushing that commit to check that the consolidation does not impact performance.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/24045#issuecomment-335352210):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e605ea522f5a72ec65fe634196cffd11617913db/76f2b33_vs_8ea00cc/report.md)
cc @ararslan

**Comment by Sacha0** [comment]
From nanosoldier's logs,
```julia
ERROR: LoadError: MethodError: no method matching h5d_write(::Int32, ::Int32, ::Base.ReinterpretArray{UInt8,1,HDF5.HDF5ReferenceObj,Array{HDF5.HDF5ReferenceObj,1}})
Closest candidates are:
  h5d_write(::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any) at /home/nanosoldier/.julia/v0.7/HDF5/src/HDF5.jl:2053
  h5d_write(::Int32, ::Int32, !Matched::String) at /home/nanosoldier/.julia/v0.7/HDF5/src/HDF5.jl:1922
  h5d_write(::Int32, ::Int32, !Matched::Array{S<:String,N} where N) where S<:String at /home/nanosoldier/.julia/v0.7/HDF5/src/HDF5.jl:1929
  ...
Stacktrace:
 [1] writearray(::HDF5.HDF5Dataset, ::Int32, ::Base.ReinterpretArray{UInt8,1,HDF5.HDF5ReferenceObj,Array{HDF5.HDF5ReferenceObj,1}}) at /home/nanosoldier/.julia/v0.7/HDF5/src/HDF5.jl:1807
 [2] #_write#17(::Array{Any,1}, ::Function, ::JLD.JldFile, ::String, ::Array{Any,1}, ::JLD.JldWriteSession) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:574
 [3] _write(::JLD.JldFile, ::String, ::Array{Any,1}, ::JLD.JldWriteSession) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:559
 [4] #write#14(::Array{Any,1}, ::Function, ::JLD.JldFile, ::String, ::Any, ::JLD.JldWriteSession) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:512
 [5] #jldopen#9(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:178
 [6] (::getfield(JLD, Symbol("#kw##jldopen")))(::Array{Any,1}, ::typeof(JLD.jldopen), ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./<missing>:0
 [7] #jldopen#10(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:231
 [8] (::getfield(JLD, Symbol("#kw##jldopen")))(::Array{Any,1}, ::typeof(JLD.jldopen), ::String, ::String) at ./<missing>:0
 [9] #jldopen#11(::Array{Any,1}, ::Function, ::getfield(JLD, Symbol("##34#35")){String,Dict{String,String},Tuple{String,BenchmarkTools.BenchmarkGroup}}, ::String, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:241
 [10] (::getfield(JLD, Symbol("#kw##jldopen")))(::Array{Any,1}, ::typeof(JLD.jldopen), ::Function, ::String, ::String) at ./<missing>:0
 [11] #save#33(::Bool, ::Bool, ::Function, ::FileIO.File{FileIO.DataFormat{:JLD}}, ::String, ::Any, ::Any, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:1220
 [12] save(::FileIO.File{FileIO.DataFormat{:JLD}}, ::String, ::Dict{String,String}, ::String, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/JLD/src/JLD.jl:1217
 [13] #save#14(::Array{Any,1}, ::Function, ::String, ::String, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/FileIO/src/loadsave.jl:61
 [14] save(::String, ::String, ::Dict{String,String}, ::String, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/FileIO/src/loadsave.jl:61
 [15] save(::String, ::String, ::Vararg{Any,N} where N) at /home/nanosoldier/.julia/v0.7/BenchmarkTools/src/serialization.jl:36
 [16] include_relative(::Module, ::String) at ./loading.jl:533
 [17] include(::Module, ::String) at ./sysimg.jl:14
 [18] process_options(::Base.JLOptions) at ./client.jl:325
 [19] _start() at ./client.jl:391
in expression starting at /home/nanosoldier/workdir/tmpra50k1/benchscript.jl:28
```
which looks like https://github.com/JuliaLang/julia/pull/23750#issuecomment-335071634 ?

**Comment by ararslan** [comment]
Yep, that's a JLD issue that just got fixed. Let's try this again.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24045#issuecomment-335636416) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/093148a405bfbc384f52a6a70b3078629f4c7433/3744665_vs_8afbe45/report.md). cc @ararslan

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks("sparse" && "matmul", vs=":master")`

**Comment by Sacha0** [comment]
Nanosoldier reported meaningful regressions only in the kernel for `A(t|c)_mul_B[!]([dense,] sparse, dense)`. Local testing indicated that an added `@simd` annotation, replacement of a `z += x*y` with a `z = muladd(x, y, z)`, and the type assertion in `CjAjB::eltype(C) = zero(eltype(C))` each negatively impacted performance, so I've removed each. If these changes fix the `A(t|c)_mul_B[!]([dense,] sparse, dense)` regressions per nanosoldier, I plan to merge this pull request and defer consolidation and additional improvements to later pull requests. Best!

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/24045#issuecomment-336530999):
```
NanosoldierError: failed to run benchmarks against primary commit: stored type BenchmarkTools.ParametersPreV006 does not match currently loaded type
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/bc7e64ccf70d3020721bc99464920146baf4c8a0/5d2fb8a_vs_cbeab1a/report.md)
cc @ararslan

**Comment by andreasnoack** [comment]
Fixes #22615

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("sparse" && "matmul", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/24045#issuecomment-342771928) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6e2417b96f2110aff12f405a447dae6b370de70b/5447339_vs_9528562/report.md). cc @ararslan

**Comment by ararslan** [comment]
The sparse matmul benchmarks have been pretty noisy on master, so it's kind of hard to determine how much is related and how much is noise.

**Comment by ViralBShah** [comment]
Should we try to bring back these improvements.

**Comment by Sacha0** [comment]
I'd love to. Regrettably I won't have time to see this through for the foreseeable future. Best!

**Comment by KristofferC** [comment]
Is there anything "big" that is left to do here @Sacha0? Getting these in would be very nice so if it is just a manner of rebasing, checking Nanosoldier and doing some small performance tweaks, I could look at it.

**Comment by Sacha0** [comment]
> Is there anything "big" that is left to do here @Sacha0? Getting these in would be very nice so if it is just a manner of rebasing (A_mul_B! -> mul! etc), checking Nanosoldier and doing some small performance tweaks, I could look at it.

[Insert hazy memory disclaimer here.] Much thanks for looking into resuscitating this pull request! :) Rebasing through the lazy adjoint/transpose change and associated cleanup should make this mergeworthy again. Of course there remains potential downstream work, but none of it pressing. (If this pull request nonetheless remains open then, I hope to polish it off after submitting my dissertation and figuring out immediate next steps.) Best!

**Comment by jebej** [comment]
It would be amazing to have this land :)

**Comment by crstnbr** [comment]
This would fix https://discourse.julialang.org/t/asymmetric-speed-of-in-place-sparse-dense-matrix-product/10256/4.

**Comment by mschauer** [comment]
Currently, `B*A`, `A*B` and `B'*A` create dense matrices and perform reasonably, while not perfectly.
Here `A` is full and `B` is sparse.

`A*B'` freezes for some time while it creates a full sparse matrix, which is likely unwanted. I just note that this PR would fix this too (I think this problem is less subtile than others performance issues mentioned.)

**Comment by ViralBShah** [comment]
@Sacha0 Would it be possible for you to revive this PR?

**Comment by Sacha0** [comment]
> @Sacha0 Would it be possible for you to revive this PR?

[That's the hope! :)](
https://github.com/JuliaLang/julia/issues/29956#issuecomment-441389372)

**Comment by ViralBShah** [comment]
Thank you. :-)

**Comment by vtjnash** [comment]
IIUC, this was revived in https://github.com/JuliaLang/julia/pull/38876, but we might still need the tests from here, as it seems like that was merged without tests? @Sacha0, @dkarrasch, or @ViralBShah would you be able confirm and close or update this, as appropriate?

**Comment by dkarrasch** [comment]
We are covering all but one cases according to https://codecov.io/gh/JuliaLang/julia/src/master/stdlib/SparseArrays/src/linalg.jl. I'll add one as soon as I get to it. Other than that, this could be closed. The remaining aspect of this one was to (silently) materialize certain adjoints/transposes, but in #40089 I found this can be sometimes advantageous and sometimes not, so it doesn't look like a good general solution and materializing should be left to the user.

**Pull request closed without merging**
