### PR TITLE
Allow kwarg in function composition 

### LINKED ISSUE #38351: Allow `∘` usage with kwargs
Would allowing `∘` to compose functions with keyword arguments be a possible update?

E.g. update the current definition of

```julia
∘(f, g) = (x...)->f(g(x...))
```

To 

```
∘(f, g) = (x...; kw...)->f(g(x...; kw...))
```

Stackoverflow question where @bkamins suggested the above solution: https://stackoverflow.com/questions/64740010/how-to-alias-composite-function-with-keyword-arguments

If people are open to this, it seems to have a low surface area in the code (at first glance) and thus PR I could work on.

### PR DESCRIPTION
**Pull request by alecloudenback**
closes #38351

This pull request would allow kwargs in functions that are composed with `∘` (a `ComposedFunction`). This is my first commit to Julia base.

The compat note in the docstring assumes that this change would make it into 1.7.

Needs:
 - [x] test case
 - [x] docstring update

### CODE REVIEW

**Review by jw3126 — APPROVED** [review]
Looks good!

**Comment by jw3126** [comment]
Bump! Can this be merged?

**Comment by jw3126** [comment]
bump

**Comment by JeffBezanson** [comment]
Thanks! Congrats on your first julia base PR.

**Comment by alecloudenback** [comment]
Is this worth including in NEWS.md?

**Pull request merged**
