### PR TITLE
[deps] Update PCRE2 URL

### LINKED ISSUE #43878: pcre2 download server is permanently offline
> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on [GitHub](https://github.com/PhilipHazel/pcre2/releases) instead.

Causing builds to now fail.

From http://pcre.org

### PR DESCRIPTION
**Pull request by giordano**
Similar to https://github.com/JuliaPackaging/Yggdrasil/pull/4293.  The old
release tarballs are gone, so we have to use GitHub-generated snapshots and also
to run `./autogen.sh` before `./configure`.

Should fix #43878 but I didn't test it locally, I mainly followed the changes I had to in Yggdrasil as well.

### CODE REVIEW

**Comment by vchuravy** [comment]
Do we not need to update the checksums?

**Comment by giordano** [comment]
Likely, the tarballs changed. Where are the checksums?

**Comment by vchuravy** [comment]
https://github.com/JuliaLang/julia/blob/master/deps/checksums/pcre

`make -f contrib/update_checksums.mk pcre`

**Review by vchuravy — APPROVED** [review]

**Comment by vtjnash** [comment]
Autogen requires programs that we avoid having in our dependency list.

**Comment by DilumAluthge** [comment]
Is there a place we can get tarballs that don't require us to run `autogen`? I agree with Jameson that it would be optimal if we didn't need to add any new build dependencies.

**Comment by DilumAluthge** [comment]
Alternatively, we could download the tarballs, run autogen, tar up the results, and host the resultant tarballs ourselves. Then users don't need autogen.

**Comment by giordano** [comment]
Valentin had already asked in spack the PCRE2 dev to reupload the release tarballs somewhere. We're waiting for a reply

**Comment by giordano** [comment]
The original tarball for 10.36 is now available on GitHub (same checksums): https://github.com/PhilipHazel/pcre2/releases/tag/pcre2-10.36.  I updated this PR to just change the URL

**Review by DilumAluthge — APPROVED** [review]

**Pull request merged**
