### PR TITLE
[release-0.4] WIP: backports for 0.4.4

### PR DESCRIPTION
**Pull request by tkelman**
If you'd like to nominate anything that doesn't already have the label go ahead and leave a comment here - especially doc-only or test-only changes are usually fair game.

TODO's:
- [x] https://github.com/JuliaLang/julia/pull/12429 plus fixes to satisfy sphinx
- [ ] https://github.com/JuliaLang/julia/pull/14659 borderline, behavior change
- [ ] https://github.com/JuliaLang/julia/pull/14625 also a bit of a behavior change
- [ ] https://github.com/JuliaLang/julia/pull/14194 needs to be done carefully to work on old llvm / pre-codegen-rewrite
- [x] https://github.com/JuliaLang/julia/pull/15285 need to test whether this works properly with winrpm on release-0.4 (edit: it didn't, see 36089d7713a4f21988369f7e0b22da46f74d403d for temporary workaround)
- [ ] https://github.com/JuliaLang/julia/pull/14902 need help with resolving conflicts
- [x] https://github.com/JuliaLang/julia/issues/13818 and https://github.com/JuliaLang/julia/issues/13851, possibly could be fixed by backporting the non-breaking part of #13491 but needs to be done carefully
- [x] pkgeval

### CODE REVIEW

**Comment by nalimilan** [comment]
RPM builds went fine, so +1

**Comment by musmo** [comment]
can include #15407

**Comment by toivoh** [comment]
#15309? I saw you added the back port pending label to it.

**Comment by tkelman** [comment]
@toivoh I guess I can put that in, it'll require re-running PkgEval. My previous run at 1d274002e59962a62d9132f6da22b77dafe3da23 is showing regressions in DictFiles, ExperimentalAnalysis, and FunctionalData, so will need some more tweaking and a re-run of PkgEval.

I bisected the FunctionalData failure to 132cb20935, @yuychao can you take a look?

**Comment by tkelman** [comment]
DictFiles failure starts happening at the same commit. ExperimentalAnalysis was a PyCall segfault that I'm having trouble reproducing.

**Comment by yuyichao** [comment]
The issue with `FunctionalData` is that the local function `pass` is now refering to a global function `vect` that specialized on (and therefore has a reference to) a type (`_somedummytype`) that is not defined on the worker process. I'm not really familiar with the serialization of functions/types (and when is `@everywhere` necessary) to tell what's the right fix....

Given this commit is causing too much trouble and is fixing unlikely segfault for a unsupported usage (#265) I think we can leave this out for backporting.....

**Comment by toivoh** [comment]
@tkelman: Yeah, or if it's too much trouble then you can just wait with it.

**Comment by tkelman** [comment]
A handful of failures here that all seem intermittent, I can't reproduce any of them locally. https://gist.github.com/0c394be0a2f0b4e0d736

I'll merge and tag this soon, assuming my incoming trivial doc fix passes.

**Pull request merged**
