### PR TITLE
Add <(::Tuple, ::Tuple) implementing three-valued logic

### PR DESCRIPTION
**Pull request by nalimilan**
For consistency with `==`, as `<` was the only remaining exception.
`isless` still returns a `Bool`, treating missing as greater than any other value.

I should have fixed that at the same time as https://github.com/JuliaLang/julia/pull/24963.

### CODE REVIEW

**Comment by andyferris** [comment]
Do we have a lexical ordering comparitor for iterables collections?

**Comment by nalimilan** [comment]
We have `lexcmp` and `lexless` (which do not implement 3VL, like `isless`).

**Comment by nalimilan** [comment]
@StefanKarpinski OK for this one too? Should be the last of the 3VL series.

**Comment by StefanKarpinski** [comment]
Yes, that's good to go. I'm still planning on deprecating `lexless` as described in https://github.com/JuliaLang/julia/issues/5290.

**Comment by andyferris** [comment]
OK, so out of curiosity: the plan is to support lexical ordering for `<` and `isless` for tuples only? Or for basically any iterable?

**Comment by StefanKarpinski** [comment]
I was not going to do any iterable, but any abstract array seems reasonable.

**Comment by andyferris** [comment]
> any abstract array seems reasonable.

I wonder if `NamedTuple`s and `AbstractDict`s that share an iteration order might also make sense?

**Pull request merged**
