### PR TITLE
trace-compile: color recompilation yellow

### PR DESCRIPTION
**Pull request by IanButterworth**
Marks recompilation of a method that produced a `precompile` statement as yellow, or if color isn't supported adds a trailing comment `# recompilation`.

The coloring matches the `@time_imports` coloring. i.e. an excerpt of
```
% ./julia --start=no --trace-compile=stderr --trace-compile-timing -e "using InteractiveUtils; @time @time_imports using Plots"
```
Screenshot 2024-09-13 at 5 04 24 PM

Some more examples

Screenshot 2024-09-12 at 7 06 25 PM

## Todo
- [x] Disable if stderr doesn't support color (done if `--color=no`)

### CODE REVIEW

**Comment by giordano** [comment]
> Disable if stderr doesn't support color

Should it add another comment to indicate recompilation, to retain the information also when colour isn't available (and clear the meaning of the colour, which at the moment isn't)?

**Comment by IanButterworth** [comment]
I think docs and color is enough. I'd personally prefer to not risk causing more lines to wrap as it's quite confusing when they do. For no color yeah, I've added a trailing comment.

**Comment by tecosaur** [comment]
I'd quite like to be able to pipe trace-compile output to a file and look at it for recompiled statements, how about adding a sigil like `*` to the timing record? E.g.

```julia
#=    1.4 ms =# precompile(...)
#= * 33.7 ms =# precompile(...)
```

**Comment by IanButterworth** [comment]
I'll add the trailing comment to the file output too.

**Comment by IanButterworth** [comment]
I propose going ahead with this. One example of it being useful https://github.com/JuliaLang/julia/pull/55782

**Pull request merged**
