### PR TITLE
🤖 [master] Bump the StyledStrings stdlib from d7496d2 to f6035eb

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: StyledStrings
URL: https://github.com/JuliaLang/StyledStrings.jl.git
Stdlib branch: main
Julia branch: master
Old commit: d7496d2
New commit: f6035eb
Julia version: 1.12.0-DEV
StyledStrings version: 1.11.0(Does not match)
Bump invoked by: @LilithHafner
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/StyledStrings.jl/compare/d7496d24d3f05536bce6a7eb4cd8ca05a75c02aa...f6035eb97b516862b16e36cab2ecc6ea8adc3d7c

```
$ git log --oneline d7496d2..f6035eb
f6035eb Replace accidental Int64s with Ints
4fcd8bb Use const fields in parser State instead of refs
35a3cdf Load user-customisations lazily
9802b6c Load ScopedValues symbols from their source
9b9cf71 Use branches when choosing how to merge face attrs
eada2dc Avoid needlessly creating a new Face in get calls
c647af9 Avoid boxing mergedface by making it toplevel
a117008 Avoid creating strings for ansi_4bit_color_code
6863348 Improve type inference of face merging
f588218 Quick fix for 4d04102adf0d (Optimised SimpleColor)
4d04102 Optimise creation of a SimpleColor from a UInt32
6d3f44d Actually overload Base's escape_string
58507e5 Fully qualify method overloads, avoid importing
fc686f3 Explicitly test eachregion
c417262 Refactor eachregion to be O(n log n) not O(n^2)
f7af623 Use concrete refs in macro parser state struct
41b2446 Check for underline term capability flag
987f776 Treat printing as more than a nothing-return write
43fb018 Add types to some comprehensions
d3aa7e1 Improve inference with a function over a closure
6901610 Mention the importance of semantic names in docs
0be209b Better hint at the package capabilities in readme
37b9e4b Load no faces.toml when the DEPOT_PATH is empty
```

### CODE REVIEW

**Comment by LilithHafner** [comment]
#55452 depends on `9802b6c Load ScopedValues symbols from their source`; it might be easiest to simply backport this PR

**Comment by LilithHafner** [comment]
@tecosaur, is this bump appropriate for backporting?

**Comment by tecosaur** [comment]
I think so, actually we'll probably want to backport another version once the public-ness of the API is transferred over from `Base` to `StyledStrings`.

**Comment by LilithHafner** [comment]
Lovely!

**Pull request merged**
