### PR TITLE
add missing extern sig_stack_size to julia_internal.h

### LINKED ISSUE #14138: Build error on building julia with USE_INTEL_JITEVENTS = 1
```
$ make
    CC src/threading.o
/home/kristoffer/juliaintel/src/threading.c(544): error: identifier "sig_stack_size" is undefined
              sig_stack_size = 1<<16;
              ^

compilation aborted for /home/kristoffer/juliaintel/src/threading.c (code 2)
make[1]: *** [threading.o] Error 2
make: *** [julia-src-release] Error 2
```

CC @ArchRobison

### PR DESCRIPTION
**Pull request by KristofferC**
As recommended by @yuyichao in #14138

fixes #14138

### CODE REVIEW

**Comment by yuyichao** [comment]
This looks wrong, you are adding it to a place that is not enabled on x86 or x64. I would also prefer to put these in a header file like `julia_internal.h`.

**Comment by KristofferC** [comment]
I know nada C++ so figured there would be something wrong. Just made the PR to get the ball rolling :P

Better now?

**Comment by yuyichao** [comment]
You also need to put it inside `#ifdef JL_USE_INTEL_JITEVENTS` like in `signals-unix.c`

**Comment by yuyichao** [comment]
LGTM

**Comment by KristofferC** [comment]
Thanks for the assistance.

**Pull request merged**
