### PR TITLE
Upgrade OpenBLAS to v0.3.17

### PR DESCRIPTION
**Pull request by ararslan**
This allows us to drop several patches.

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41973#issuecomment-904064590):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.
cc @christopher-dG

**Comment by ararslan** [comment]
Classic

**Review by maleadt — APPROVED** [review]

**Comment by ararslan** [comment]
Worth getting Nanosoldier figured out for this?

**Comment by vtjnash** [comment]
Seems like you managed to find an adversarial input for `xz`. Usually the 1GB input data compresses into 20-30 MB, but this time it took 103 MB.
```
      From worker 2:    [master 42bf2650c4d] upload report for BenchmarkJob JuliaLang/julia@8e85649 vs. JuliaLang/julia@0974dfa
      From worker 2:     10 files changed, 35784 insertions(+)
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/data.tar.xz
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/0974dfa1bd2779cdd07283359236c5aa4b8536da_against.err
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/0974dfa1bd2779cdd07283359236c5aa4b8536da_against.out
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/0974dfa1bd2779cdd07283359236c5aa4b8536da_build.err
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/0974dfa1bd2779cdd07283359236c5aa4b8536da_build.out
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/8e8564937be7078b5e4fe61b3c6dafb1928353fc_build.err
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/8e8564937be7078b5e4fe61b3c6dafb1928353fc_build.out
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/8e8564937be7078b5e4fe61b3c6dafb1928353fc_primary.err
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/logs/8e8564937be7078b5e4fe61b3c6dafb1928353fc_primary.out
      From worker 2:     create mode 100644 benchmark/by_hash/8e85649_vs_0974dfa/report.md
      From worker 2:    From https://github.com/JuliaCI/NanosoldierReports
      From worker 2:       00d2e8aa5ad..077225d2c96  master     -> origin/master
      From worker 2:    Merge made by the 'recursive' strategy.
      From worker 2:     pkgeval/by_hash/0a1bf84_vs_292f1a9/data.tar.xz | Bin 0 -> 27012 bytes
      From worker 2:     pkgeval/by_hash/0a1bf84_vs_292f1a9/report.md   |  87 +++++++++++++++++++++++++
      From worker 2:     2 files changed, 87 insertions(+)
      From worker 2:     create mode 100644 pkgeval/by_hash/0a1bf84_vs_292f1a9/data.tar.xz
      From worker 2:     create mode 100644 pkgeval/by_hash/0a1bf84_vs_292f1a9/report.md
      From worker 2:    remote: error: Trace: 940c273325305c7c9d7d7d9b9394d083723ae6b4c4accf5055fa5a0c75ab4e2e        
      From worker 2:    remote: error: See http://git.io/iEPt8g for more information.        
      From worker 2:    remote: error: File benchmark/by_hash/8e85649_vs_0974dfa/data.tar.xz is 103.07 MB; this exceeds GitHub's file size limit of 100.00 MB        
      From worker 2:    remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
      From worker 2:    To https://github.com/JuliaCI/NanosoldierReports.git
      From worker 2:     ! [remote rejected]         master -> master (pre-receive hook declined)
```
I uploaded the report manually for you (after deleting the data file):

https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8e85649_vs_0974dfa/report.md

**Comment by ararslan** [comment]
Great, thanks so much, Jameson! The results look like noise to me, so I think we're good.

**Pull request merged**
