### PR TITLE
Show broadcasting with Date constructor

### PR DESCRIPTION
**Pull request by rikhuijzer**
Months ago, I have looked very long for how to parse a bunch of strings to dates and couldn't figure it out. It turned out to be very easy with broadcasting and dateformat.

Here, I propose to change a fairly arbitrary example to an example using broadcasting on the Date constructor. This still demonstrates that the Date constructor performs good, but now with a more sensible use-case.

### CODE REVIEW

**Comment by bicycle1885** [comment]
I don't think this is a very good example. The description above the example code says:

> You can also use the `dateformat""` string macro. This macro creates the `DateFormat` object once when the macro is expanded and uses the same `DateFormat` object even if a code snippet is run multiple times.

So, this example should showcase a typical use of the `dateformat""` macro that will be expanded once and repeatedly used in a tight loop or something, which will result in performance improvement in common cases. On the other hand, the proposed example will have the same performance regardless of whether you use `dateformat""` macro or not, because the datetime format object will be created only once before the function call.

**Comment by rikhuijzer** [comment]
Okay, I've moved it a bit up.

**Review by bicycle1885 — APPROVED** [review]
LGTM :+1:

**Comment by rikhuijzer** [comment]
@KristofferC, could you close or merge this? The list of open PRs is already long enough. Thanks

**Review by quinnj — APPROVED** [review]

**Pull request merged**
