### PR TITLE
Use -ffc2 when compiling Fortran libraries with gfortran and MKL

### LINKED ISSUE #359: Compiles with MKL on OS X, but 'make testall' fails calling mkl_blas_zdotc and elsewhere
I am using OS X and followed the MKL installation instructions for the 0.5 release (Version 0.5.0-rc1+1 (2016-08-05 15:23 UTC), Commit acfd04c (5 days old release-0.5)). The build completed (output attached), but several tests failed (also attached). I also tried this with the 0.4.6 release, and I get the same mkl_blas_zdotc error in the arnoldi code.

My bash profile contains:

```
source /opt/intel/mkl/bin/mklvars.sh intel64 ilp64
MKLPATH=/opt/intel/mkl
```

My Maker.user file is:

```
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 0
USE_INTEL_JITEVENTS ?= 0
USEICC = 0
USEIFC = 0
```

My environment variables are:

```
echo $MKLROOT
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl
echo $DYLD_LIBRARY_PATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/tbb/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib
echo $LIBRARY_PATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/tbb/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib
echo $NLSPATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib/locale/%l_%t/%N
echo $MANPATH
nothing...
echo $CPATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/include
```

[MakeTestallOutput.txt](https://github.com/JuliaLang/julia/files/411856/MakeTestallOutput.txt)

### LINKED ISSUE #17946: Compiles with MKL on OS X, but 'make testall' fails calling mkl_blas_zdotc and elsewhere
I am using OS X and followed the MKL installation instructions for the 0.5 release (Version 0.5.0-rc1+1 (2016-08-05 15:23 UTC), Commit acfd04c (5 days old release-0.5)). The build completed (output attached), but several tests failed (also attached). I also tried this with the 0.4.6 release, and I get the same mkl_blas_zdotc error in the arnoldi code.

My bash profile contains:

```
source /opt/intel/mkl/bin/mklvars.sh intel64 ilp64
MKLPATH=/opt/intel/mkl
```

My Maker.user file is:

```
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 0
USE_INTEL_JITEVENTS ?= 0
USEICC = 0
USEIFC = 0
```

My environment variables are:

```
echo $MKLROOT
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl
echo $DYLD_LIBRARY_PATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/tbb/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib
echo $LIBRARY_PATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/tbb/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/compiler/lib:/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib
echo $NLSPATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/lib/locale/%l_%t/%N
echo $MANPATH
nothing...
echo $CPATH
/opt/intel//compilers_and_libraries_2016.3.170/mac/mkl/include
```

[MakeTestallOutput.txt](https://github.com/JuliaLang/julia/files/411856/MakeTestallOutput.txt)

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes JuliaLang/LinearAlgebra.jl#359

### CODE REVIEW

**Comment by tkelman** [comment]
Should test whether this is necessary or harmful on windows before merging.

**Comment by andreasnoack** [comment]
@tkelman This has been tested on Windows as part of the JuliaPro tests.

@ararslan Why did you remove the backport labels?

**Comment by StefanKarpinski** [comment]
> Why did you remove the backport labels?

There are not going to be anymore 0.5 releases and most likely no more 0.6 releases either.

**Comment by andreasnoack** [comment]
> There are not going to be anymore 0.5 releases and most likely no more 0.6 releases either.

Fine but why not keep them in case we change our mind. If that happens then finding these PRs again might be quite some work and it doesn't save us anything now.

**Comment by StefanKarpinski** [comment]
Sure. Makes sense in case we do ever release those (although the chances of a new 0.5 release are essentially zero).

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
