### PR TITLE
Add doc for `open(::Cmd)` to section on I/O and Networking

### LINKED ISSUE #14286: open(`cmd`) not on stdlib documentation [v0.4]
It is mentioned in http://docs.julialang.org/en/release-0.4/manual/running-external-programs/ that one can `open` a command. However, such use is not documented in the stdlib section on I/O and networking at http://docs.julialang.org/en/release-0.4/stdlib/io-network/#Base.open.

### PR DESCRIPTION
**Pull request by mbaz**
Fixes #14286.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but it looks like you forgot to remove the definitions from the other file.

**Comment by mbaz** [comment]
My mistake -- I did copy and paste instead of cut and paste. Will edit PR and resubmit.

**Comment by mbaz** [comment]
I removed the text from Essentials -- please review.

**Comment by nalimilan** [comment]
Thanks, looks good to me.

**Pull request merged**
