### PR TITLE
Implement vararg methods for mapreduce similar to map, fixes #27704.

### LINKED ISSUE #27704: `mapreduce` with multiple input containers
It occurs to me that it would be great if operations like `mapreduce(f, op, a, b)` actually worked where `a` and `b` are two containers of the same length, like it does for `map`.

For me, there are two issues here. 

 * There is no varargs form for `mapreduce` that applies `zip` to the inputs and the appropriate form.
 * Perhaps this is just my taste, but I honestly find the placement of the optional `v0` term is a little annoying in `mapreduce(f, op, v0, a)`. If it is optional, maybe it should be an optional argument or a keyword argument. And it can't be an optional (positional) argument when the last term is a varargs list of the input containers.

My suggestion would be a signature something like `mapreduce(f, op, a...; v0 = nothing)` (we might need something other than `nothing`, since it seems to mean something these days). Moving `v0` would be necessary to have the `v0`-less `mapreduce` algorithm with two or more input containers (since it can't magically infer whether the 3rd argument is meant to be `v0` or a container to reduce over).

xref: https://github.com/JuliaLang/julia/pull/27677#issuecomment-398710388 cc: @StefanKarpinski

### PR DESCRIPTION
**Pull request by fredrikekre**
This is not really an optimal implementation, but I wanted to try to get the functionality in for 1.2. Should be fine to make improvements later.

### CODE REVIEW

**Comment by tkf** [comment]
I think this can be optimized by lowering to `Broadcasted`-based `mapreduce` in #31020 in the future. That is to say, `mapreduce(f, op, x, y, z)` can call whatever `mapreduce(identity, op, Broadcast.instantiate(Broadcast.broadcasted(f, x, y, z))))` would call internally.

**Comment by fredrikekre** [comment]
bump

**Comment by StefanKarpinski** [comment]
@mbauman: do you think you could review so that this can make it into 1.2?

**Comment by mbauman** [comment]
LGTM! Thanks @fredrikekre.

**Pull request merged**
