### PR TITLE
merge Union and UnionType; allow writing union types with `Union{ }`

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like the right way to go and shouldn't break anything in packages due to the fallback definition, but it's freezing while building inference on Win64 which I can reproduce locally. Ideas?

**Comment by tkelman** [comment]
Very much worth noting: the freeze does not occur with LLVM 3.6.0.

**Comment by JeffBezanson** [comment]
Looks like there was a segfault due to not being able to find `append_any` in the `Inference` module from `jl_f_apply` during the first bootstrap stage.

**Comment by tkelman** [comment]
`repr(Nullable())` test needs to be updated

**Comment by JeffBezanson** [comment]
Yep, working on it.

**Pull request merged**
