### PR TITLE
Do not download tarballs when unpacked sources are present

### PR DESCRIPTION
**Pull request by nalimilan**
The tarballs are not needed if the sources are there, it can allow
saving some space, and that's the standard way of building RPM packages.

That behavior confused me as I used to unpack Rmath-julia*.tar.gz into `deps/` (and it broke the RPM nightlies). But I'm not sure this is the best way of fixing this. Suggestions welcome.

### CODE REVIEW

**Comment by nalimilan** [comment]
AppVeyor failure on 32-bit looks unrelated

**Comment by vtjnash** [comment]
combining rules like this seems likely to coarsen make's ability to handle dependency resolution. is there a particular reason that the RPM packages can't start with the tar.gz file instead of the unpacked folder?

you could instead setup your build machine to just `touch` dummy tar.gz files, although I'm not quite sure how that would work either

**Comment by nalimilan** [comment]
Maybe I haven't implemented the right way, but the goal here was on the contrary to avoid requiring the tarballs when the sources are already there -- thus handling dependencies better, not worse. Tarballs are not classic targets since you don't modify them: they are versioned, so they only change by replacing the target with another one.

I can certainly work around this when building the RPM, but I figured it could be more generally useful.

**Comment by vtjnash** [comment]
I was initially hesitant mostly because I had just made exactly the opposite change in cfd4aee for other parts of the build system.

however, those are good points. i actually now think this is almost good to merge. the only trouble is that this will definitely break the fftw rules, although the rest should be fine. with this formulation, both fftw-single and fftw-double are going to try to download the fftw source, unaware of the other process, and potentially conflicting.

we could make the tar.gz files into `|` targets, which would be the same as saying they are versioned and don't need to cause a rebuild if newer. that would make it easier for you to simply `touch` source files in their place.

although, one more complication in the whole thing is that a few sources get patches applied when they are unpacked. that has always been a rather brittle process (and could be improved by having a patch also create a dummy file indicating whether it has been applied). however, currently, implying that sources could be extracted manually may miss that step.

**Comment by nalimilan** [comment]
> I was initially hesitant mostly because I had just made exactly the opposite change in cfd4aee for other parts of the build system.

Yeah, it's paradoxical, but I think these are actually two very different situations.

> however, those are good points. i actually now think this is almost good to merge. the only trouble is that this will definitely break the fftw rules, although the rest should be fine. with this formulation, both fftw-single and fftw-double are going to try to download the fftw source, unaware of the other process, and potentially conflicting.

Indeed, though that would only be a problem if one target triggered a download before the other is over; else nothing would happen. We could write `fftw-$(FFTW_VER)-double/configure: | fftw-$(FFTW_VER)-single/configure`, so that the targets are not run at the same time, right?

> we could make the tar.gz files into | targets, which would be the same as saying they are versioned and don't need to cause a rebuild if newer. that would make it easier for you to simply touch source files in their place.

Yeah, but that would still mean you need to create a dummy `.tar.gz` to prevent it from being downloaded. I don't see that as a real improvement.

> although, one more complication in the whole thing is that a few sources get patches applied when they are unpacked. that has always been a rather brittle process (and could be improved by having a patch also create a dummy file indicating whether it has been applied). however, currently, implying that sources could be extracted manually may miss that step.

Yes, but nothing changes in that regard. The idea is just to allow people to remove all the tarballs after the first build, or to extract tarballs manually beforehand *when they know what they are doing*, in particular for packaging. Nothing more.

**Comment by vtjnash** [comment]
> Yeah, it's paradoxical, but I think these are actually two very different situations.

it's not really that different. the concern only applies to the fftw rules, but in that case it is exactly the same

> Indeed, though that would only be a problem if one target triggered a download before the other is over; 

yes, but saying the failure only happens when it fails is a bit tautological. however, i assign a relatively high probability to this scenario, since you only need to start the download while the other is being downloaded, verified, or unzipped to cause a failure (e.g. there's a relatively large time window).

> Yes, but nothing changes in that regard. The idea is just to allow people to remove all the tarballs after the first build, or to extract tarballs manually beforehand when they know what they are doing, in particular for packaging. Nothing more.

i don't see any benefit from that. each llvm Release build folder on my harddrive is 400MB (of which there are 3) and each Debug build folder is 4 GB (of which there are 2). by contrast, all of the sources files here appear to total about 60 MB. I know that i'm unusual in that I strongly don't care about hard drive space and prefer not to waste time trying to optimize exactly which files are no longer needed.

we would likely realize much bigger space saving by finishing the implementation of out-of-tree builds, so that my builds could share these source files, rather than deleting them

**Comment by nalimilan** [comment]
OK, forget it. If I'm the only one interested in this, I can easily work around in when building RPMs. Anyway the goal is to get rid of bundled dependencies in distro packages, and we're not too far.

**Pull request closed without merging**
