### PR TITLE
WIP: Eliminate backtrace display when testing __precompile__()

### PR DESCRIPTION
**Pull request by ScottPJones**
This just cleans up the output of unit test in compile.jl.

### CODE REVIEW

**Comment by tkelman** [comment]
Yes, would like to clean this up, thanks. Though would be good to actually check and verify the error message in the caught exception, and maybe some of the redirected output.

**Comment by ScottPJones** [comment]
Yes, better to verify at least some of the output (with the backtrace it will be very platform specific, too much for exact matching, I guess)
Could you merge and we can make it even better later, or do you want to wait for some checking of output?

**Comment by tkelman** [comment]
Something about the redirection appears to have failed and timed out on appveyor.

**Comment by ScottPJones** [comment]
@tkelman I think this may be showing some problem with `Base.compilecache`, possibly with exception handling.  Do you see any reason that the try/catch code in this case should not work as expected?
cc: @JeffBezanson

**Comment by tkelman** [comment]
Looks like a bug somewhere, but I have no idea what's wrong here.

**Comment by tkelman** [comment]
closing in favor of https://github.com/JuliaLang/julia/pull/14117

**Pull request closed without merging**
