### PR TITLE
types as C-structs [rebased]

### PR DESCRIPTION
**Pull request by Keno**
@JeffBezanson and I are in the process of looking at and hopefully merging #2818. This rebases that PR (with some unrelated changes already cherry-picked to master) hopefully to be merged soon.

### CODE REVIEW

**Comment by kmsquire** [comment]
Does this deserve a NEWS entry?

**Comment by kmsquire** [comment]
Also need to remove the reference to #2818 from the "Calling C and Fortran" docs.

**Comment by tkelman** [comment]
This utterly broke the windows build. Can we please let CI do its job?

**Comment by StefanKarpinski** [comment]
True – there's not much point in paying AppVeyor for CI as a service if we're going to ignore it.

**Comment by tkelman** [comment]
@vtjnash or @keno, how do we deal with this
```
$ usr/bin/julia-debug
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3939 (2015-03-20 12:38 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit b43f0b0* (0 days old master)
|__/                   |  x86_64-w64-mingw32


Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0xe08aab -- jl_setjmp at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_setjmp at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
julia_init at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_f_yieldto at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
wait at task.jl:305
stream_wait at stream.jl:271
uv_write at stream.jl:751
buffer_or_write at stream.jl:764
write at stream.jl:826
print at string.jl:68
jlcall_print_664 at  (unknown line)
jl_operator_precedence at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_trampoline at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_init_types at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_apply_generic at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
banner at version.jl:232
_start at client.jl:415
jlcall__start_589 at  (unknown line)
jl_operator_precedence at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_trampoline at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_init_types at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
jl_apply_generic at D:\cygwin64\home\Tony\julia\usr\bin\libjulia-debug.dll (unknown line)
unknown function (ip: 4199740)
unknown function (ip: 4203441)
unknown function (ip: 4204232)
unknown function (ip: 4199370)
unknown function (ip: 4199672)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)

Tony@TK-samsung ~/julia
$ gdb usr/bin/julia-debug
GNU gdb (GDB) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-cygwin".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from usr/bin/julia-debug...done.
(gdb) r
Starting program: /home/Tony/julia/usr/bin/julia-debug
[New Thread 9584.0x1e30]
[New Thread 9584.0x11bc]
[New Thread 9584.0x3180]
[New Thread 9584.0x5d34]
[New Thread 9584.0x47d4]
[New Thread 9584.0x2440]
[New Thread 9584.0x4c28]
[New Thread 9584.0x4444]
[New Thread 9584.0x56d4]
[New Thread 9584.0x5b84]
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3939 (2015-03-20 12:38 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit b43f0b0* (0 days old master)
|__/                   |  x86_64-w64-mingw32

[New Thread 9584.0x2b34]

Program received signal SIGSEGV, Segmentation fault.
jl_setjmp () at _setjmp.win64.S:23
23          movaps XMMWORD PTR [rcx+96],xmm6
(gdb) bt
#0  jl_setjmp () at _setjmp.win64.S:23
#1  0x0000000000dc6ce0 in ctx_switch (t=0x8170f0c8, where=0x8170f118) at task.c:296
#2  0x0000000000dc6ebb in switchto (t=0x8170f0c8) at task.c:371
#3  0x0000000000dc7dd4 in jl_f_yieldto (F=0x80020728, args=0xd5ece0, nargs=2) at task.c:887
#4  0x0000000010aa799e in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by vtjnash** [comment]
Ah, I was considering fixing that, but couldn't come up with a test case originally.

On my phone now, but if someone wants to take a shot at this -- every pool we allocate in the gc should be shifted by (sizeof(jl_typetag_t)%16 bytes) before slicing it up

**Comment by tkelman** [comment]
AppVeyor's also idle right now so if someone can translate that into a patch it shouldn't take long to check.

**Comment by JeffBezanson** [comment]
@StefanKarpinski is it possible to change some permissions to let more people cancel appveyor builds? I don't think I can.

**Comment by tkelman** [comment]
@JeffBezanson you have to log out then log back in as StefanKarpinski. Everyone with commit access should be allowed to do that.

**Comment by tkelman** [comment]
It's a really odd UI (cc @FeodorFitsner this should probably be made simpler / more obvious) - you log in with your own Github credentials, but then you should see a screen that looks like this:
image
You have to select the StefanKarpinski entry there to be able to cancel / restart Julia builds.

**Comment by Keno** [comment]
I don't have that option, I presume because my GitHub account was relinked and AppVeyor got confused.

**Comment by FeodorFitsner** [comment]
Sure, this will be changed though it's non-trivial change (API is affected) that requires careful planning. Perhaps, will be a good chance to re-write UI on Angular 2.0 and TypeScript :)

**Comment by tkelman** [comment]
So, aside from the MinGW failure which I was hoping someone could translate from Jameson English into commit-worthy code (I can't...), there's also this: https://msdn.microsoft.com/en-us/library/0scy7z2d.aspx

**Comment by vtjnash** [comment]
> there's also this: https://msdn.microsoft.com/en-us/library/0scy7z2d.aspx

i assume you mean that issue comes up when you try to do a msvc compile? you could probably just make this macro define empty: https://github.com/JuliaLang/julia/blob/0d8cec3d29ae8e4d687ee8f1da7de86232694472/src/julia.h#L60

it seems that may be a C99 feature

**Comment by tkelman** [comment]
Will try that. Thanks for fixing the alignment issue.

**Comment by tkelman** [comment]
That helps a bit. How about this line https://github.com/JuliaLang/julia/blob/master/src/julia.h#L86 giving https://msdn.microsoft.com/en-us/library/81zca88z.aspx ?

I've also been trying with the VS 2015 rc's that are available on AppVeyor, and it doesn't help fix these.

**Comment by tkelman** [comment]
I don't think the size-zero array is a C99 thing, it looks from https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html like it's a GNU extension and the MSVC error is strictly speaking true according to the C standard.

Someone should check whether ICC allows this construct.

**Comment by nalimilan** [comment]
If the intent is to have a variable-length array, then you should be able to replace `value[0]` with `value[]`, right? That's how it's done here:
https://github.com/JuliaLang/julia/blob/e1f0310d1ac9547fced1394419622801b483d415/src/gc.c#L49

**Comment by tkelman** [comment]
No, that doesn't work https://ci.appveyor.com/project/tkelman/julia/build/1.0.644

The other struct types with C99 flexible array members aren't causing problems because there don't appear to be any arrays of them anywhere. `value` is an array of `jl_value_t`, which violates "A structure containing a flexible array member, or a union containing such a structure (possibly recursively), may not be a member of a structure or an element of an array." - since `jl_value_t` itself has a flexible array member in it for `fieldptr`.

**Comment by nalimilan** [comment]
Ah, got it, that's the recursive nature of these that's the problem.

**Pull request merged**
