### PR TITLE
Update libunwind to 1.3.1

### PR DESCRIPTION
**Pull request by ararslan**
This allows us to drop all of our patches except for one: the one that prefers extbl-based unwinding on ARM. It appears that patch will need to be redone atop current libunwind. @yuyichao, would you be able to help out with that, since you authored the original patch?

### CODE REVIEW

**Comment by ararslan** [comment]
Elliot also mentioned that it would be good to know whether the patch is still necessary at all. Perhaps DWARF-based unwinding, which is the default for ARM in libunwind, is sufficient now.

**Comment by staticfloat** [comment]
@yuyichao do you think that the old libunwind patch is still necessary?

**Comment by yuyichao** [comment]
https://github.com/archlinuxcn/repo/tree/c97e87749097cdf7938e8f7f3dbcfa82f69c5e6c/archlinuxcn/libunwind-git

AFAIK nothing has changed about dwarf on arm. It's not what the platform use so there's just no reason to use it.

**Comment by ararslan** [comment]
Perfect, thanks. I've updated the patch file with the contents of the Arch patch, modified to apply to libunwind 1.3.1. I've added Yichao as a co-author for the commit since the patch was his work.

**Review by yuyichao — APPROVED** [review]

**Pull request merged**
