### PR TITLE
🤖 Bump the Downloads stdlib from c91876a to 4250b35

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Downloads
URL: `https://github.com/JuliaLang/Downloads.jl.git`
Branch: master
Old commit: c91876a
New commit: 4250b35
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline c91876a..4250b35
4250b35 Check for timer isopen correctly (#162)
7f91b8a Workaround for missing isopen check in FDWatcher (#161)
62b497e fix Timer usage (#158)
f856630 Merge pull request #157 from JuliaLang/revert-156-revert-151-sk/no-libuv-sushi
43a3484 add missing locks during Timer callbacks
69acc13 Revert "Revert "stop using raw libuv API" (#156)"
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
If possible, it would be nice to hold off on merging this until https://github.com/JuliaLang/julia/pull/42885 is merged.

**Comment by StefanKarpinski** [comment]
Well, I guess the good news is that the CI failures don't appear to be related to Downloads? Can hold off for whatever or re-bump afterwards. Whatever's convenient.

**Comment by DilumAluthge** [comment]
I merged https://github.com/JuliaLang/julia/pull/42885 and triggered a new bump. Now the Pkg test suite is going to run on this bump PR, so we can see whether or not it breaks the Pkg tests.

**Comment by StefanKarpinski** [comment]
FreeBSD failure is some LBT issue. Presumably unrelated.

**Comment by DilumAluthge** [comment]
Yeah, I think the `tester_freebsd64` failure is unrelated. I'll open an issue.

It looks like the Pkg test suite passed (on Buildkite), which is good news.

If all CI jobs (other than `tester_freebsd64`) pass, I think that this is good to merge.

**Comment by DilumAluthge** [comment]
> Yeah, I think the `tester_freebsd64` failure is unrelated. I'll open an issue.

https://github.com/JuliaLang/julia/issues/42944

**Comment by DilumAluthge** [comment]
The `tester_win64` failures are not due to this PR. See https://github.com/JuliaLang/julia/pull/42950

**Comment by StefanKarpinski** [comment]
Fingers crossed that this one sticks and we finally have a threadsafe Downloads.

**Pull request merged**
