### PR TITLE
Correct @fastmath cis

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Seems like a straightforward bugfix. cc @stevengj, @jiahao

**Comment by stevengj** [comment]
LGTM.

**Comment by stevengj** [comment]
It might be nice to have a `Complex(a::Complex, b::Complex)` constructor that computes `a+b*im` in order to enable writing this sort of generic code in the future.

**Comment by eschnett** [comment]
The code that was removed was not only broken (because of the missing constructor), it was also inefficient. The new code should be roughly twice as fast. In this case, not having such a constructor found a bug. I assume that the broken `cis` implementation was copy-pasted from the version that accepts real arguments.

I don't think `Complex(a::Complex, b::Complex)` would be used often.

**Pull request merged**
