### PR TITLE
remove false statement about convert on types

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://discourse.julialang.org/t/convert-vs-constructors/4159/

### CODE REVIEW

**Comment by nalimilan** [comment]
Rather than removing this paragraph, shouldn't it be restricted to one-argument constructors? Given the confusion this generates, the fallback should really be described in detail (so that it doesn't need to be repeated on Discourse).

**Comment by stevengj** [comment]
The fallback, and the circumstances where you would define `convert` rather than a constructor, definitely needs to be defined.

**Comment by helgee** [comment]
Related: #15120

**Comment by JeffBezanson** [comment]
This is handled by #23273

**Pull request closed without merging**
