### PR TITLE
LAPACK: validate input parameters to throw informative errors

### PR DESCRIPTION
**Pull request by jishnub**
This PR validates the input parameters to the Julia LAPACK wrappers, so that the error messages are more informative.
On nightly
```julia
julia> using LinearAlgebra

julia> LAPACK.geev!('X', 'X', rand(2,2))
 ** On entry to DGEEV  parameter number  1 had an illegal value
ERROR: ArgumentError: invalid argument #1 to LAPACK call
```
This PR
```julia
julia> using LinearAlgebra

julia> LAPACK.geev!('X', 'X', rand(2,2))
ERROR: ArgumentError: argument #1: jobvl must be one of ('N', 'V'), but 'X' was passed
```

Secondly, moved certain allocations (e.g. in `geevx`) below the validation checks, so that these only happen for valid parameter values.

Thirdly, added `require_one_based_indexing` checks to functions where these were missing.

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]
Looking great!

**Comment by jebej** [comment]
Some a these functions do a lot of checks, could there be a performance impact on fast calls?

**Comment by oscardssmith** [comment]
IMO this is a bad idea. We don't want to encourage people to use the LAPACK interfaces directly because the character interface is bad, and the function names are bad. Adding extra checks for using a low level library directly that should instead be called via wrappers that ensure correct construction is IMO not the right way to go here.

**Comment by ViralBShah** [comment]
@oscardssmith I don't agree. These are not exported interfaces. So we are under no obligation. But people do use these, and they should work nicely. If someone writes a new Julian LAPACK interface at some point, we can point people there.

**Comment by ViralBShah** [comment]
> There are some O(N^2) infinite/NaN checks that may be relegated to post-call error reporting. I suspect this will help with performance. I am planning a separate PR for better post-call error messages. The checks in this PR are O(1), so they shouldn't impact performance.

I was going to mention that we could do a lot better on post-call error messages. Looking forward!

**Pull request merged**
