### PR TITLE
🤖 Bump the Pkg stdlib to 51595f95

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
This pull request bumps Pkg to `51595f95`, which is currently the latest commit on the `release-1.6` branch.

```
$ git log --pretty=oneline --abbrev=commit 87d336454a7ad960cf42bbb782d4c38dcd1e1124^..51595f958ddd326643a8b1b8902a3c47964d8cb4
51595f958ddd326643a8b1b8902a3c47964d8cb4 Don't do autoprecomp after Pkg.dev [fixed] (#2235) (#2257)
67fc36789b9dbcfdfc51d7bcfbec8d7859426114 Merge pull request #2255 from JuliaLang/backports-release-1.6
94ebf9db816bf291793a2b517d3f31c7724c17c4 check for fancy print availability in Platformengines (#2256)
a734e1d17ad5f2200d343cb03884675213247487 update github action files to be against release-1.6
83cbe5fc73fddd8134fa8d42b699249dc3383701 Work around precompiling packages with no `version` entry (#2251)
c97afbdcb29ffa1b8fac5f5485c157d8ea0cf2e7 PlatformEngines: fix last case of passing header as string (#2250)
1cb7baf3446cf6b72793202f4ea38dc951959677 Use repo_source when cloning. (#2249)
bbd5a7fb26cd6237f1d2a9e058ba5f74e6854753 CI: Re-enable testing on Pkg server (#2243)
176cf562a2ebdaa46c64d71517ec33c9da37708e Remove bad Artifacts test (#2242)
08934a47058bb808135be21599a8402c6a17e87f Codecov: use the official Codecov GitHub Action (#2229)
94627d66c175ddb81e34c7160fdd156f66da5827 AppVeyor: temporarily disable submitting to Codecov (#2227)
64d7a90ea559b6125df11b56422946e1da96dc28 GitHub actions (#2224)
27cb0ebf26bc47e2a952363b74bba16945538b0f Allow `7z` selection to pick something up off of the PATH (#2210)
87d336454a7ad960cf42bbb782d4c38dcd1e1124 Merge pull request #2189 from JuliaLang/kc/backports
c616bccdba2d7da16d2fe3edadca9ce74f3b5d02 clean up progress bars usage (#2190)
928c57b59b6b64e7083e8781a2ec3b037c1b92f0 remove duplicated tests and move registry into place instead of copying (#2186)
0f05d39a539fe82c703361ea29efb61fdb6acce1 Windows: prefer git cloning registries (close #2014) (#2175)
1c3df0726034064b274f80cc462ab18ef45dd6cf Auto-precompilation: Remove tip, add env var note to pkg repl help (#2172)
```

### CODE REVIEW

**Comment by staticfloat** [comment]
@DilumAluthge since I just merged https://github.com/JuliaLang/julia/pull/38655 will your bot notice and close this automatically, or will we need to close this ourselves?

**Comment by DilumAluthge** [comment]
Right now we'll need to manually close.

Also, if you want to make the new bump PR now, just go to https://juliapackaging.github.io/BumpStdlibs.jl/dev/usage/ and follow the instructions.

**Comment by staticfloat** [comment]
Cool, thanks!  I love that it's that easy.

**Comment by KristofferC** [comment]
Can this be disabled for Pkg for now since we don't want to update to the master of it until we have branched?

**Comment by staticfloat** [comment]
It looks to me like it’s pulling from release-1.6

**Comment by DilumAluthge** [comment]
> Can this be disabled for Pkg for now since we don't want to update to the master of it until we have branched?

It uses whatever is specified for `PKG_BRANCH`. Since right now we have `PKG_BRANCH = PKG_BRANCH = release-1.6`, it only updates to the latest commit on the `release-1.6` branch in the Pkg.jl repository.

**Comment by DilumAluthge** [comment]
> It looks to me like it’s pulling from release-1.6

Yeah for each stdlib, it looks in `STDLIBNAME.version`, and looks at the line that says `STDLIBNAME_BRANCH`, and it pulls from that branch.

**Comment by DilumAluthge** [comment]
> @DilumAluthge since I just merged #38655 will your bot notice and close this automatically, or will we need to close this ourselves?

BTW, BumpStdlibs.jl now has the "close old PRs" functionality available. You can toggle it on or off by setting the "close old pull requests" input to `true` or `false` respectively.

**Pull request closed without merging**
