### PR TITLE
Improved DimensionMismatch error messages for range

### PR DESCRIPTION
**Pull request by kshyatt**
Incremental improvements before we fix this error type entirely

### CODE REVIEW

**Comment by kshyatt** [comment]
The whitespace thing is in `Logging` docs, unrelated to me.

**Review by c42f — APPROVED** [review]
Looks good to me.

**Comment by c42f** [comment]
win32 CI error looks to be a spurious timeout

**Comment by maleadt** [comment]
FWIW, these kind of changes tend to break GPU compatibility, but I guess that shouldn't hold it back and we should look at a proper fix (e.g. automatic outlining of `throw` and its arguments).

**Comment by kshyatt** [comment]
OK, I'm going to merge then.

**Pull request merged**
