### PR TITLE
for PkgEval only: error when an implicit local at the toplevel shadows a global

### PR DESCRIPTION
**Pull request by JeffBezanson**
@nanosoldier `runtests(ALL, vs = ":master")`

### CODE REVIEW

**Comment by maleadt** [comment]
Huh, this did actually not register with the NewPkg Nanosoldier, but the logs have scrolled past so I can't diagnose why. Let's just try again:

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34410#issuecomment-575480366) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/6043300b564e06d915b404f398badb9a465cfa8c/pkgeval/by_hash/490f831_vs_ce211b9/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
So, this affects 150 packages. Not surprising, but it is a bit striking that all cases except 1 are in test files. In practice, this is nearly a test-suite-specific issue.

The one other case appears to be a genuine bug:
https://github.com/JuliaRobotics/Caesar.jl/blob/4a79ee9933a778bffbfa1c0834b9f17a6a1cbc13/src/zmq/services/plotting.jl#L6
That certainly helps convince me that this warning is valuable. Maybe there should be a command line option for it, disabled by default for Pkg.test?

**Comment by StefanKarpinski** [comment]
So 150 packages fail from this if I'm reading the results right. From spot inspection, the failures are almost all in test quite code—normal code doesn't seem to do this. It's also mostly from cases where one test file defines a top-level global and another test file uses the same name for a local. In a sense, this data strongly vindicates the scope change in 1.0 since all of these cases would have been accidental bugs in 0.6. And if the evaluation order of the test files was non-deterministic as it is in Base's test suite, then the bug would have been non-deterministic as well since whether the intended assignment would be local or not would depend on file evaluation order. What a nightmare!

The vast majority of these situations seem like they would be avoided if `@testset` introduce a non-soft scope. There are a few ways to accomplish this:

1. the macro could lower to defining a function and then calling it
2. the macro could lower to a let block and we could make let blocks hard scopes like functions
3. there's already a try-catch block in there, if that was a hard scope it would be fixed
4. some other explicit way of introducing a hard scope without a function body.

Not sure what the best approach would be, but that's my analysis.

**Comment by StefanKarpinski** [comment]
It would also be significantly mitigated by evaluating test files in individual modules. My first cut at a preferred course of action is:

1. Make `let` introduce a hard scope. I.e. on this branch, don't warn inside a let block; on the other brach, let would behave like a function body and introduce a hard scope.

2. Change `@testset` to wrap its contents in a `let` block, thereby introducing a hard scope and allowing locals inside test sets to define locals that shadow globals.

3. Introduce a `test_include` function (exported from `Test`) that includes a test file but wraps it in an anonymous module first (we may already have a function to do this, I don't recall).

4. Encourage people to use `test_include` in their test suites rather than `include`.

**Comment by JeffBezanson** [comment]
> It would also be significantly mitigated by evaluating test files in individual modules.

I've definitely seen many cases where the issue existed within a single file.

**Comment by StefanKarpinski** [comment]
Of course, I'm just proposing that as a way to reduce the issue.

**Pull request closed without merging**
