### PR TITLE
speedup @everywhere

### PR DESCRIPTION
**Pull request by amitmurthy**
Current implementation executes two calls - a `remotecall` for expression execution and a `remotecall_fetch` to wait for execution completion on each worker. Now there is a single call of `remotecall_fetch`.

@andreasnoack , ~~the linear slowdown in the first `@everywhere 1+1` was because all code paths related to `remotecall_fetch` was being compiled for the first time and it was being executed serially.~~
Actually `remotecall_fetch` was being called as part of the `addprocs`. The extra time may just have been due to the serial execution of `remotecall_fetch` against all workers.

cc @JeffBezanson

### CODE REVIEW

**Comment by andreasnoack** [comment]
Great. I can confirm that this is much faster. On the Slurm managed cluster I now get

nworkers | second
--- | ---
 4 | 0.630646
8 |  0.309988
16 | 0.31393 
32 | 0.325648
64 | 0.334107
128 | 0.374203
256 | 0.38756 
512 | 0.443842
1024 | :bomb:

but the last row could easily be Slurm related and would have to be investigated further.

**Comment by ViralBShah** [comment]
:+

**Comment by ViralBShah** [comment]
cc @alanedelman

**Comment by tkelman** [comment]
backported in 426c5bee5a9cb431ae2ea7aac94fe280eb0f6ab8

**Pull request merged**
