### PR TITLE
[doc] Add example for NaN comparision

### PR DESCRIPTION
**Pull request by krishna-vasudev**
added example code for inequality of NaN.

### CODE REVIEW

**Review by fredrikekre — CHANGES_REQUESTED** [review]
This is not a good place for this, could add it to the block ~10 lines below perhaps or to the `NaN` docstring.

**Comment by krishna-vasudev** [comment]
> This is not a good place for this, could add it to the block ~10 lines below perhaps or to the `NaN` docstring.

I will make those changes,but i didn't get where to make these changes.Can you please guide me?

**Comment by mcabbott** [comment]
For the docstring, xref #38606 , where https://github.com/JuliaLang/julia/pull/38606/commits/ae2468b7c9596231cd590552fcd0f476752034c4 adds comparison examples.

**Comment by ViralBShah** [comment]
@krishna-vasudev If you can incorporate the change requested, we can get it merged.

**Comment by krishna-vasudev** [comment]
> @krishna-vasudev If you can incorporate the change requested, we can get it merged.

@ViralBShah ,i have added it to the block below. But  still confused how to add it to docstrings.

**Pull request merged**
