### PR TITLE
Workaround incorrect Uint deprecation message

### PR DESCRIPTION
**Pull request by c42f**
The Uint deprecation warning suggested a system dependent type (UInt64 or UInt32) rather than UInt, due to this being a type alias.  Hardcode a warning message for this rather common type, pending a more powerful deprecation warning system.

See #13221.  I hope this is what Jeff had in mind as a quick patch for 0.4... it's pretty disgusting :-)

Fixes https://github.com/JuliaLang/julia/issues/13221

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Yes, exactly the kind of disgustingness I had in mind :)

**Comment by ivarne** [comment]
A searchable keyword and a mention in a comment [here](https://github.com/JuliaLang/julia/blob/a7d0830bca1af8c0810ac72515acdee8ff4bd2c4/base/deprecated.jl#L169) to ~~ensure~~ *improve the chances for* the removal of this hack when the deprecation is removed, would be great.

**Comment by c42f** [comment]
Sure I can add an extra note if you like, but I figured that any real solution to this problem would involve touching `jl_binding_deprecation_warning` in any case.

**Comment by c42f** [comment]
@ivarne - reminder added for the case that the Uint deprecation goes away before the deprecation system itself gets another look.

**Pull request merged**
