### PR TITLE
Specialize findmax/findmin on SparseVector

### LINKED ISSUE #42823: Missing optimization for findmax/findmin on SparseVector
```julia
using SparseArrays

a = spzeros(2^32)
a[rand(UInt16,6)] = rand(6)

# this variant is very slow, on bigger Arrays error
@time (m,i)=findmax(a)

# this variant is quick, also on bigger Arrays
#   todo correct result if only negative values in a
@time begin
    (m1,tmp) = findmax(findnz(a)[2])
    i1 = findnz(a)[1][tmp]        
end
@show m i m1 i1

versioninfo()
```
# Output:
 21.400888 seconds (9 allocations: 224 bytes)
  0.000028 seconds (14 allocations: 784 bytes)
m = 0.8275944812507452
i = 51128
m1 = 0.8275944812507452
i1 = 51128
51128

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

### PR DESCRIPTION
**Pull request by dkarrasch**
Closes #42823. The example given there is computed in 18ns on my computer.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Any more suggestions? Is this good to go?

**Comment by barucden** [comment]
Imho, function composition is clearer than macros but that might be just a matter of taste.

**Review by oscardssmith — APPROVED** [review]

**Comment by fredrikekre** [comment]
First time I have seen all green in a year...

**Comment by dkarrasch** [comment]
> First time I have seen all green in a year...

Must be my karma... or my special coding skills.

**Pull request merged**
