### PR TITLE
[SparseArrays] Respect order of mul in (l)mul!(::Diagonal,::Sparse)

### LINKED ISSUE #589: mul! of sparse and diagonal for non-commutative eltypes?
Here (and in the corresponding `rmul!`/`lmul!`)

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1165-L1192

we assume that multiplication of the eltypes of `D` and `A` is commutative, whereas we do care about the order of multiplication here:

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1194-L1218

I don't have a use/test case for matrix multiplication with non-commutative eltypes, so somebody should tell if there is an issue here (with an easy fix). @Jutho ?

### LINKED ISSUE #30161: mul! of sparse and diagonal for non-commutative eltypes?
Here (and in the corresponding `rmul!`/`lmul!`)

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1165-L1192

we assume that multiplication of the eltypes of `D` and `A` is commutative, whereas we do care about the order of multiplication here:

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1194-L1218

I don't have a use/test case for matrix multiplication with non-commutative eltypes, so somebody should tell if there is an issue here (with an easy fix). @Jutho ?

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes JuliaLang/LinearAlgebra.jl#589 .

### CODE REVIEW

**Comment by dkarrasch** [comment]
Ok, cool, I have tests which pass (and wouldn't pass on master for exactly the commutativity issue). It looks like this:
```
for n in (1, 10)
    v = Quaternion.(rand(n), rand(n), rand(n), rand(n))
    D = Diagonal(v)
    Avals = Quaternion.(rand(2n), rand(2n), rand(2n), rand(2n))
    A = sparse(rand(1:n, 2n), rand(1:n, 2n), Avals, n, n)
    Am = convert(Matrix, A) # test versus dense matrix to make sure different code paths are taken
    @test A * D ≈ Am * D
    @test D * A ≈ D * Am
    @test rmul!(copy(A), D) ≈ Am * D
    @test lmul!(D, copy(A)) ≈ D * Am
end
```
Comments are welcome. To get this running, I needed to define
```
Base.zero(::Type{Quaternion{T}}) where T = Quaternion{T}(zero(T), zero(T), zero(T), zero(T))

(+)(ql::Quaternion, qr::Quaternion) =
 Quaternion(ql.s + qr.s, ql.v1 + qr.v1, ql.v2 + qr.v2, ql.v3 + qr.v3)
```
in addition to what is defined in @andreasnoack 's snippet above. I didn't understand the "move the code" comment above. Should I just add the definitions where the others are and the tests somewhere in the usual test section? Would the tests know about `Quaternion`s?

**Comment by KristofferC** [comment]
To move the code you can copy paste the existing Quaternion definition into `test/testhelpers/Quaternions.jl`. Then you can include that file where it is used in the LinearAlgebra test and also include that file for your sparse multiplication test. You can look at how the other test helpers (like Furlong) is used.

**Review by andreasnoack — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]

**Comment by fredrikekre** [comment]
Could be good to squash this into two commits: one with the move of Quaternion and one with the bugfix, but does not matter much.

**Comment by dkarrasch** [comment]
Yes, I'll see if I can find a git expert to help me with that.

On a different note: this PR affects #29296, which is labelled as "backport pending 1.0".

**Comment by andreasnoack** [comment]
> On a different note: this PR affects #29296, which is labelled as "backport pending 1.0".

I think it should be safe to mark this PR for backport as well.

**Comment by dkarrasch** [comment]
That was the adventure of my life, but I managed to clean up my commit mess (with the help of my colleague... well, he dictated, I was typing). Result: two beautiful, nicely sorted commits. 🎉

**Comment by chriscoey** [comment]
can this be merged?

**Comment by ViralBShah** [comment]
I believe so - but I am wondering if we need to wait for the 1.1 release process.

**Comment by dkarrasch** [comment]
> can this be merged?

Yes. I wasn't sure if I needed to give another "I'm done" signal, since I felt that was obvious and didn't want to put pressure on anyone.

**Comment by KristofferC** [comment]
Can change behavior so should not be backported

**Pull request merged**
