### PR TITLE
add ability to print message while reading

### PR DESCRIPTION
**Pull request by AbhiShake1**
readLine(msg="example")
readLines(msg="example")

### CODE REVIEW

**Comment by simeonschaub** [comment]
Ref https://github.com/JuliaLang/julia/pull/38164#issuecomment-720578220

**Comment by AbhiShake1** [comment]
> Ref [#38164 (comment)](https://github.com/JuliaLang/julia/pull/38164#issuecomment-720578220). I am not sure whether this is really worth complicating `readline` for if you can just add a `println` yourself.

I am fine with writing println("msg"); readline() but readline(msg="msg") would make it alot cleaner and we could use readline() like we traditionally do. If it doesnt make anything slower, it would make readability better in my opinion

**Comment by Keno** [comment]
You're probably looking for `Base.prompt`.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/41384

**Pull request closed without merging**
