### PR TITLE
fix handling of inferred static parameter values with free variables

### PR DESCRIPTION
**Pull request by JeffBezanson**
seems to be needed after #23643

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
But does this mean the subtyping (intersection) env is returning wrong information?

**Comment by JeffBezanson** [comment]
Basically the environment contains `Vector{_}` (`_` is a free variable), instead of `T <: (Vector{_} where _)`. So it's not completely wrong, and it seems unnecessary to require the intersection code to do this transformation.

**Comment by vtjnash** [comment]
So you're saying intersection may get this, but subtyping will never get this wrong at runtime?

**Comment by JeffBezanson** [comment]
This can happen any time we can't determine the exact value of a static parameter, for example

```
(Tuple{Type{Vector{S}}, Int} where S)  <:  Tuple{Type{T}, Any} where T<:Array
```

is true, so subtype and intersection are both correct, but the value we determine for `T` is `Vector{S}` with free `S`.

**Review by vtjnash — DISMISSED** [review]
Needs to be handled by subtyping

**Comment by JeffBezanson** [comment]
Actually we lose a bit of precision that way. Previously, for a static parameter value of `Vector{_}` we'd infer `Type{Vector{_}} where _`. With this extra transformation we get `Type{T} where T<:(Vector{_} where _)`, which is a larger type. We might have to pick our poison here --- either get less precision or use `has_free_typevars` in more places.

**Comment by vtjnash** [comment]
Seems like a good improvement then. It sounds like the old logic could have incorrectly inferred that the runtime value was definitely not `Vector`?

**Comment by JeffBezanson** [comment]
I'm not sure if there is such a case. In a case like `Tuple{Type{Vector{S}}, Int} where S`, the first argument actually never will be `Vector`. Maybe there is an example the other way as well though.

**Comment by JeffBezanson** [comment]
Ok, I have the conservative version here. If there are no inference regressions in the tests then hopefully it's good enough.

**Pull request merged**
