### PR TITLE
Make `cholesky` handle AbstractMatrix

### LINKED ISSUE #906: Cholesky fails for `Hermitian{.., Diagonal}`
There appears to be some missing method that handles Hermitian/Symmetric wrappers around special matrices. 
```julia
julia> cholesky((1.0I(3)))
Cholesky{Float64, Diagonal{Float64, Vector{Float64}}}
U factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> cholesky(Hermitian(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Hermitian{Float64, Diagonal{Float64, Vector{Float64}}})

julia> cholesky(Symmetric(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Symmetric{Float64, Diagonal{Float64, Vector{Float64}}})
```
I assume the pattern `cholesky(Hermitian(Σ))`, i.e., automatically wrapping symmetric matrices in a `Hermitian` wrapper is quite common, so it would be great if it worked for all `AbstractMatrix`.

Tested on Julia v1.7.1

### LINKED ISSUE #44053: Cholesky fails for `Hermitian{.., Diagonal}`
There appears to be some missing method that handles Hermitian/Symmetric wrappers around special matrices. 
```julia
julia> cholesky((1.0I(3)))
Cholesky{Float64, Diagonal{Float64, Vector{Float64}}}
U factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> cholesky(Hermitian(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Hermitian{Float64, Diagonal{Float64, Vector{Float64}}})

julia> cholesky(Symmetric(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Symmetric{Float64, Diagonal{Float64, Vector{Float64}}})
```
I assume the pattern `cholesky(Hermitian(Σ))`, i.e., automatically wrapping symmetric matrices in a `Hermitian` wrapper is quite common, so it would be great if it worked for all `AbstractMatrix`.

Tested on Julia v1.7.1

### PR DESCRIPTION
**Pull request by dkarrasch**
Closes JuliaLang/LinearAlgebra.jl#906. Closes JuliaLang/julia#40690.

### CODE REVIEW

**Comment by dkarrasch** [comment]
I only now realize that this is somewhat duplicate to #40690, though it includes some special handling for some special matrices, and (currently) doesn't relax the stridedness assumption on inplace `cholesky!`.

@dlfivefifty Do you have an example for a non-strided matrix that should cooperate with `cholesky!`? I could include it here if you don't mind.

**Comment by dlfivefifty** [comment]
Banded matrices

**Comment by dkarrasch** [comment]
Do we have some minimal testhelper thing for that, do you know?

**Comment by dkarrasch** [comment]
I'm not sure we have an easy way to test this, but I checked that `cholesky!` works on a BandedMatrix, so that extension should be fine.

**Pull request merged**
