### PR TITLE
Handle compressed AST in jl_local_in_linfo

### PR DESCRIPTION
**Pull request by yuyichao**
This somehow shows up in threading build when `jl_static_eval` is called from `jl_get_unspecialized`.

@vtjnash who had some comment about compressing and uncompressiong ast, to check if this is the right solution. =)

### CODE REVIEW

**Comment by carnaval** [comment]
I think this will be made unnecessary by jb/linear3 since the variable info is not part of the compressed code anymore

**Comment by JeffBezanson** [comment]
That's right; on that branch this function doesn't exist any more.

**Comment by yuyichao** [comment]
So is https://github.com/JuliaLang/julia/pull/15609 going to be ready soon? I'd like to make sure the threading build bot can pass since there's very frequent breakage on the threading build recently...

**Comment by yuyichao** [comment]
> [Ok, let's merge jb/linear3 today.](https://github.com/JuliaLang/julia/pull/14949#issuecomment-203047809)

Sounds good.

**Pull request closed without merging**
