### PR TITLE
Update noteworthy differences from R due to R update

### PR DESCRIPTION
**Pull request by wdearden**
* As of R 3.5.0, ranges in R no longer have a high memory overhead due to ALTREP (see https://svn.r-project.org/R/branches/ALTREP/ALTREP.html#sample_implementations and http://blog.revolutionanalytics.com/2018/04/r-350.html). Since it is still important to note the syntax difference and nothing changed with R's syntax, I propose only removing the mention of high memory overhead.

* Correct `isna` to `is.na`.

### CODE REVIEW

**Comment by wdearden** [comment]
Deleting because I forgot to run `make docs`.

**Comment by nalimilan** [comment]
And? You don't need to run `make docs`.

**Comment by wdearden** [comment]
Ah thanks. I see that now.

**Comment by StefanKarpinski** [comment]
Is ALTREP used by default in standard R now?

**Comment by nalimilan** [comment]
It's too bad R managed to do that by default before Julia 1.0 is ready. ;-)

Though Julia ranges seem to remain more powerful since you can easily implement efficient methods for them using multiple dispatch.

**Review by nalimilan — APPROVED** [review]

**Comment by wdearden** [comment]
Absolutely. `sum(1:1e06)` takes about 200 ns in Julia and 300 ns in R 3.5.0 so there's not much of a performance difference. In R 3.4.3 it took about 8 milliseconds and scales a little above linear.

More importantly, with my minimal knowledge of Julia I can use github search to find the source code here: https://github.com/JuliaLang/julia/blob/6a0ac1b43a2331951f5bb3891fd5c320ce2557d8/base/range.jl#L820

With strong knowledge of R, I still need help. Typing `pryr::show_c_source(.Primitive("sum"))` helps me write the correct search term in a github mirror of R source code. This leads me here https://github.com/wch/r-source/blob/2172f62cb860de36a24248c61012d42c07bdd3ee/src/main/summary.c#L564, which leads me here https://github.com/wch/r-source/blob/90347217a25ba1ac16cee363ac38d1c42750bc11/src/main/altrep.c#L461, which leads me here https://github.com/wch/r-source/blob/90347217a25ba1ac16cee363ac38d1c42750bc11/src/main/altrep.c#L185 and at this point I'm lost.

**Comment by ViralBShah** [comment]
Should we get this merged? Would be nice to update if it should - otherwise we should close it.

**Comment by nalimilan** [comment]
I've rebased. Only one of the changes still applies, the other one has been fixed since then.

**Review by nalimilan — APPROVED** [review]

**Pull request merged**
