### PR TITLE
RFC: catch writes to protected memory in mmapped arrays (fix #3434)

### PR DESCRIPTION
**Pull request by timholy**
Starting from the example in #6703,

```
julia> s = open("/tmp/a.bin", "r")
IOStream(<file /tmp/a.bin>)

julia> m = mmap_array(Float64, (10,1), s)
10x1 Array{Float64,2}:
 0.751866
 0.832087
 0.239773
 0.120287
 0.867469
 0.957427
 0.941344
 0.642588
 0.56932 
 0.464532

julia> m[3] = 2.0
ERROR: MemoryError()
 in setindex! at array.jl:305

julia> m = 5
5

julia> gc()

```

If desired I'd be happy to change the error message to something more descriptive (e.g., `"Memory-access error. Did you try to set the value of a read-only mmapped array?"`). I seem to remember some discussion about problems that can arise from more verbose error messages, which is why I started with something minimal.

Summary of design: store begin/end pointers of blocks of memory that are write-protected; if you get a SIGSEGV, check the address to see if it falls within one of these protected pages. If it doesn't, use the default SIGSEGV handling.

I can't test this on Windows or OSX (and IIUC the AppVeyor testing is still not finished?), but there's relatively little of this that's OS-specific.

### CODE REVIEW

**Comment by quinnj** [comment]
Hmmm......why can't I see any commits/changes with this merge? Even after restoring the branch?

**Comment by quinnj** [comment]
NM, found it

**Comment by tkelman** [comment]
Github (and/or Jacob) did something funky here. d4f8c310bde96877f7e62f3d2152a454fda89c71 does not look like the right commit, can someone find the right commit for this?

**Comment by yuyichao** [comment]
@tkelman caa4bfa ? https://github.com/JuliaLang/julia/pull/6877#issuecomment-44220735 ?

**Comment by yuyichao** [comment]
Or 3b36d857eb2848d8480b82e0f00df7965de233f1

**Comment by tkelman** [comment]
Ah thanks, yes, `git log --grep=3434` helps, that first one was reverted in 87c3e38b3314, then in July it was committed again but without the test.

**Pull request merged**
