### PR TITLE
Backports for 1.6-RC2

### LINKED ISSUE #38491: abspath bug for relative directories
A bit of an edge case, but noticed this when looking at https://github.com/JuliaLang/julia/issues/23646 

Assume the current directory is `C:\Users\Mus\x`
```
julia> abspath("C:x")
"C:\\Users\\Mus\\x"  # correct


julia> abspath("X:x")
"X:x"  # should be "X:\x"
```

### LINKED ISSUE #39521: Varargs-related subtype abort
```
Tuple{Type{Base.PermutedDimsArrays.PermutedDimsArray{Float32, 3, _A, _B, Array{Float32, 3}}} where _B where _A, DataType, DataType} <: Tuple{Vararg{V, N}} where V where N

julia: /home/tim/Julia/src/julia/src/subtype.c:1887: jl_subtype_env: Assertion `obvious_subtype == 3 || obvious_subtype == subtype || jl_has_free_typevars(x) || jl_has_free_typevars(y)' failed.

signal (6): Aborted
in expression starting at none:1
jl_subtype_env at /home/tim/Julia/src/julia/src/subtype.c:1887
jl_f_issubtype at /home/tim/Julia/src/julia/src/builtins.c:444
```

Reproduces on `release-1.6` branch ~~(e.g., https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.6/julia-8ceeb68753-linux64.tar.gz) but not on master (e.g., https://s3.amazonaws.com/julialangnightlies/pretesting/linux/x64/1.7/julia-20224a6686-linux64.tar.gz). Are we missing a backport? cc @KristofferC; I'll see about bisecting this~~, and also on `master`.

### LINKED ISSUE #39600: Dotted comparison chains don't fuse with surrounding dotted calls
I'd expect the following to create just one fused loop, but it creates two (two `materialize`s):

```julia-repl
julia> Meta.@lower (!).(1 .< A .< 2)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(<, 1, A)
│   %2 = Base.broadcasted(<, A, 2)
│   %3 = Base.broadcasted(&, %1, %2)
│   %4 = Base.materialize(%3)
│   %5 = Base.broadcasted(!, %4)
│   %6 = Base.materialize(%5)
└──      return %6
))))
```

It should look like:

```julia-repl
julia> Meta.@lower  (!).((1 .< A) .& (A .< 2))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.broadcasted(<, 1, A)
│   %2 = Base.broadcasted(<, A, 2)
│   %3 = Base.broadcasted(&, %1, %2)
│   %4 = Base.broadcasted(!, %3)
│   %5 = Base.materialize(%4)
└──      return %5
))))
```

### LINKED ISSUE #39698: `ERROR: TypeVar in Vararg length must have bounds Union{} and Any` in `Test.detect_ambiguities(ArrayInterface)`
E.g.:
```julia
julia> using ArrayInterface, Test

julia> Test.detect_ambiguities(ArrayInterface)
ERROR: TypeVar in Vararg length must have bounds Union{} and Any
Stacktrace:
 [1] _methods_by_ftype
   @ ./reflection.jl:884 [inlined]
 [2] (::Test.var"#examine#37"{Bool, Bool, Vector{Module}, Test.var"#sortdefs#36", Set{Tuple{Method, Method}}})(mt::Core.MethodTable)
   @ Test ~/Documents/languages/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1481
 [3] detect_ambiguities(mods::Module; recursive::Bool, ambiguous_bottom::Bool)
   @ Test ~/Documents/languages/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1506
 [4] detect_ambiguities(mods::Module)
   @ Test ~/Documents/languages/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1468
 [5] top-level scope
   @ REPL[4]:1

julia> Test.detect_ambiguities(ArrayInterface, ambiguous_bottom=true)
ERROR: TypeVar in Vararg length must have bounds Union{} and Any
Stacktrace:
 [1] _methods_by_ftype
   @ ./reflection.jl:884 [inlined]
 [2] (::Test.var"#examine#37"{Bool, Bool, Vector{Module}, Test.var"#sortdefs#36", Set{Tuple{Method, Method}}})(mt::Core.MethodTable)
   @ Test ~/Documents/languages/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1481
 [3] detect_ambiguities(mods::Module; recursive::Bool, ambiguous_bottom::Bool)
   @ Test ~/Documents/languages/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1506
 [4] top-level scope
   @ REPL[10]:1
```

### LINKED ISSUE #39789: New downloading issues in 1.6-rc1
Multiple users are reporting issues downloading registries with the new Downloads.jl curl approach, for example:

```
(DosingApp) pkg> up
    Updating registry at `~/.julia/registries/General`
^C┌ Error: curl_multi_remove_handle: 1================>   ]  92.3 %
└ @ Downloads.Curl ~/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
```

This is well-tracked upstream at ~~JuliaLang/Downloads.jl#95 and~~ JuliaLang/Downloads.jl#99, but I'm submitting this here to suggest it be a 1.6-blocker.

### LINKED ISSUE #39804: Segfault in Catlab tests on v1.6.0-rc1 but pass on 1.7.0-DEV.599
When testing 1.6.0-rc1 with the Catlab library, we get a segfault in one test case and an undefined reference error in another (see https://github.com/AlgebraicJulia/Catlab.jl/issues/385). Both tests pass on Julia Version 1.7.0-DEV.599 (2021-02-23)

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #38997 - fixed a bug in the build system
- [x] #39525 - fix #39521, obvious_subtype issue with `Type{}` and diagonal
- [x] #39115 - remove Core._apply Builtin
- [x] #39142 - fix some compiler warnings
- [x] #39227 - Fix a compiler warning
- [x] #39525 - fix #39521, obvious_subtype issue with `Type{}` and diagonal
- [x] #39539 - Add missing imports to SuiteSparse tests
- [x] #39543 - [cli/trampolines] Clean up definitions, fix win32 exporting issue
- [x] #39560 - Improve first/last docstrings
- [x] #39557 - use sparse multiplication for sparse arrays time BitMatrix and BitVector and wrappers
- [x] #39567 - [build] Fix out-of-tree `stringreplace` invocations
- [x] #39522 - Do not print delimiters twice in show(::OffsetMatrix) for matrices with certain shifted axes
- [x] #39553 - Fix misunwind during Profile test under rr
- [x] #39491 - [file] Fix relative symlinks to directories on Windows
- [x] #39570 - fix bug in `let` when a global var is both shadowed and used in an RHS
- [x] #39572 - [loading] Search in Sys.STDLIB if name/uuid is known.
- [x] #39591 - [p7zip_jll] Set `LIBPATH` and `LIBPATH_list` at init-time
- [x] #39610 - special/exp.jl: fix broken jldoctest block
- [x] #39615 - Update Downloads.jl
- [x] #39604 - expand use of egal for testing type equality
- [x] #39602 - fix #39600: broadcast fusion broken for comparison
- [x] #39621 - Lock cfunction trampoline cache and freelist accesses.
- [x] #39667 - Use lower limit on number of threads in cmdlineargs test
- [x] #39671 - Add several compat notes for Julia 1.6
- [x] #39623 - avoid excessive renaming in subtype of intersection result
- [x] #39608 - Fix for infinite loop when passing 0d array to setindex of n-dim arrays
- [x] #39712 - Add Half precision ppc patch and codesign LLVM binaries
- [x] #39668 - UnitRange{Int} -> unitrange
- [x] #39726 - avoid corrupting String on conversion of StringVector to String
- [x] #39737 - Fix typo in BitVector constructor
- [x] #39689 - Protect handle_message from Integer subtype invalidation
- [x] #39745 - codegen: define return_roots in normalized form
- [x] #39747 - codegen: guard phi node loads of invalid inputs
- [x] #39636 - Change Windows CRT func to be considered as libjulia func
- [x] #39744 - fix type uniquing (caching) in incremental deserializer
- [x] #39728 - ensure to show the whole type, even if the proper subset matched an alias
- [x] #39772 - [libgit2] Fix zlib stream abandonment causing clone error on 32-bit systems
- [x] #39809 - make copy correctly handle 0-dimensional SubArray
- [x] #39778 - jl_egal_types: don't reject equivalence just for gensyms
- [x] #39790 - LinearAlgebra._generic_matmul! : Avoid division by zero for tile_size.
- [x] #39833 - Update Downloads.jl to fix download hanging, fixes #39789.
- [x] #39821 - fix #39804, ABI handling of structs with String references
- [x] #39854 - cmdlineargs test: on 32-bit systems, impose a constant upper limit on the number of threads
- [x] #39839 - [BugReporting] pass `ARGS` through properly

Non-merged PRs with backport label:
- [x] #39875 - fix #39698 by disabling the unnecessary Vararg var bounds error
- [ ] #39801 - llvm-alloc-opt: handle dead code better
- [ ] #39785 - Backport #39784 to 1.6
- [ ] #39544 - fix definition of open I/O to Process
- [ ] #39540 - fix internal IR corruption from use of a global
- [ ] #39378 - Restore StackOverflow error message for repeated frames
- [ ] #38981 - Fix #38491: fix an abspath() edge case on Windows
- [ ] #38405 - Make Distributed.jl `Worker` struct thread-safe.

### CODE REVIEW

**Comment by KristofferC** [comment]
Weird error on freebsd and aarch64:

```
est Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/test/precompile.jl:303
  Expression: Dict(modules) == merge(Dict((let m = Base.PkgId(s)
                m => Base.module_build_id(Base.root_module(m))
            end for s = ["Base", "Core", "Main", string(Foo2_module), string(FooBase_module)])), Dict((let m = Base.root_module(Base, s)
                Base.PkgId(m) => Base.module_build_id(m)
            end for s = [:ArgTools, :Artifacts, :Base64, :CRC32c, :Dates, :DelimitedFiles, :Distributed, :Downloads, :FileWatching, :Future, :InteractiveUtils, :LazyArtifacts, :LibCURL, :LibCURL_jll, :LibGit2, :Libdl, :LinearAlgebra, :Logging, :Markdown, :Mmap, :MozillaCACerts_jll, :NetworkOptions, :Pkg, :Printf, :Profile, :REPL, :Random, :SHA, :Serialization, :SharedArrays, :Sockets, :SparseArrays, :Statistics, :SuiteSparse, :TOML, :Tar, :Test, :UUIDs, :Unicode, :nghttp2_jll])))
   Evaluated: Dict{Base.PkgId, UInt64}(SparseArrays [2f01184e-e22b-5df5-ae63-d93ebab69eaf] => 0x0019aa864dc5cd0d, Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] => 0x0019aa8130b4e63e, Random [9a3f8284-a2c9-5f02-9a11-845980a1fd5c] => 0x0019aa848e2207b5, Libdl [8f399da3-3557-5675-b5ff-fb832c97cbdb] => 0x0019aa814155aed6, SuiteSparse [4607b0f0-06f3-5cda-b6b1-a6196a1729e9] => 0x0019aa890aa92039, FileWatching [7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee] => 0x0019aa813be86bc5, LibCURL_jll [deac9b47-8bc7-5906-a0fe-35ac56dc84c0] => 0x0019aa8955d7588d, REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] => 0x0019aa8748038dfb, Future [9fa8497b-333b-5362-9e8d-4d0656e87820] => 0x0019aa85a8a759d6, Markdown [d6f4376e-aef5-505a-96c1-9c027394607a] => 0x0019aa842235211c���) == Dict{Base.PkgId, UInt64}(Random [9a3f8284-a2c9-5f02-9a11-845980a1fd5c] => 0x0019aa848e2207b5, Libdl [8f399da3-3557-5675-b5ff-fb832c97cbdb] => 0x0019aa814155aed6, SuiteSparse [4607b0f0-06f3-5cda-b6b1-a6196a1729e9] => 0x0019aa890aa92039, LibCURL_jll [deac9b47-8bc7-5906-a0fe-35ac56dc84c0] => 0x0019aa8955d7588d, REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] => 0x0019aa8748038dfb, Distributed [8ba89e20-285c-5b6f-9357-94700520ee1b] => 0x0019aa856c765753, LibGit2 [76f85450-5226-5b5a-8eaa-529ad045b433] => 0x0019aa85dbb3a6a8, DelimitedFiles [8bb1440f-4735-579b-a4ab-409b98df4dab] => 0x0019aa818c1e722d, Test [8dfed614-e22c-5e08-85e1-65c5234f0b40] => 0x0019aa8947716f74, SHA [ea8e919c-243c-51af-8825-aaa63cd721ce] => 0x0019aa814e2b1652���)
ERROR: LoadError: Test run finished with errors
```

**Comment by fredrikekre** [comment]
That error happens on https://github.com/JuliaLang/julia/pull/39616 too

**Comment by fredrikekre** [comment]
> Weird error on freebsd and aarch64:

Fixed by https://github.com/JuliaLang/julia/pull/39616/commits/352345c89871f91bee0f859fab7e6e97eebebd6d

**Comment by fingolfin** [comment]
Could #39227 also be backported? It's just a C compiler warning, but I think there is some value in trying to be warning free.

**Comment by tknopp** [comment]
Xref https://github.com/JuliaGraphics/Gtk.jl/issues/562  since Gtk.jl does not pass tests on Julia 1.6.

**Comment by sostock** [comment]
Could #39671 be backported?

**Comment by KristofferC** [comment]
> Xref JuliaGraphics/Gtk.jl#562 since Gtk.jl does not pass tests on Julia 1.6.

Need something to show that this is an issue with Julia and not the package. A bisection would be a good way to progress on that.

**Comment by tknopp** [comment]
> Need something to show that this is an issue with Julia and not the package. A bisection would be a good way to progress on that.

yes that would be helpful. My ping was not intended to say "there is a problem in Julia, fix that" but more giving you an extra data point of what issues are right now on Julia 1.6 in the package landscape.

I will not find time to track this down in the near future. If Jameson (the original author of the code in question) finds time this would be of course cool. He is also the one who can judge best if the issue is in Julia or if the issue is some assumptions that the package made, which are simply not valid anymore (but were never intended to be valid).

**Comment by IanButterworth** [comment]
Just to make sure its caught. Deploy on Base docs has been silently failing since ~Feb 4th. Base docs haven't been updated since then, from what I can tell.
Here's an example from the latest commit https://build.julialang.org/#/builders/34/builds/844/steps/5/logs/stdio

I mentioned it in https://github.com/JuliaLang/julia/pull/39663, but that would just make the error throw. It's not an actual fix

@mortenpi / @fredrikekre should a specific issue be created, or is a fix PR inbound?

1.6-rc2 release blocker? 
It should obviously block the actual 1.6 release

**Comment by mortenpi** [comment]
It looks to be a configuration issue on the buildbots. It doesn't actually have to be a release blocker -- we should be able to re-trigger the docs build for the tag once the configuration is sorted. Or we can even just push the 1.6.0 docs by hand.

**Comment by kimikage** [comment]
Could #39636 also be backported? It's a performance improvement and not a release blocker, though.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39614#issuecomment-783145976) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/df057a1_vs_a58bdd9/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39614#issuecomment-783146083) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/df057a1_vs_ebcc603/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "Alpine", "ArrayInterface", "AtlasRobot", "BundleMethod", "ControlSystemIdentification", "DataDrivenDiffEq", "DiffEqCallbacks", "DiffEqJump", "EliminateGraphs", "ExponentialAction", "FilesystemDatastructures", "GalacticOptim", "Gen", "GenParticleFilters", "Grassmann", "HybridArrays", "Jaynes", "KernelFunctions", "Kinetic", "KissMCMC", "KitML", "Leibniz", "LoopThrottle", "MechanismGeometries", "MeshCatMechanisms", "ModelingToolkit", "ParticleScattering", "PastaQ", "PointPatterns", "QML", "Quadrature", "RandomizedProgressiveHedging", "RigidBodyDynamics", "Ripserer", "SimplePosetAlgorithms", "Solaris", "SpatialJackknife", "ThreadedSparseArrays", "ValkyrieRobot", "VertexSafeGraphs"], vs = ":release-1.6")`

**Comment by giordano** [comment]
> Need something to show that this is an issue with Julia and not the package. A bisection would be a good way to progress on that.

#39811 bisected to #38180, which is in the `release-1.6` branch

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/39614#issuecomment-788701911) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/a25fa4e_vs_071ee97/report.md). cc @christopher-dG

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "Alpine", "ArrayInterface", "AtlasRobot", "BundleMethod", "ControlSystemIdentification", "DataDrivenDiffEq", "DiffEqCallbacks", "DiffEqJump", "EliminateGraphs", "ExponentialAction", "FilesystemDatastructures", "GalacticOptim", "Gen", "GenParticleFilters", "Grassmann", "HybridArrays", "Jaynes", "KernelFunctions", "Kinetic", "KissMCMC", "KitML", "Leibniz", "LoopThrottle", "MechanismGeometries", "MeshCatMechanisms", "ModelingToolkit", "ParticleScattering", "PastaQ", "PointPatterns", "QML", "Quadrature", "RandomizedProgressiveHedging", "RigidBodyDynamics", "Ripserer", "SimplePosetAlgorithms", "Solaris", "SpatialJackknife", "ThreadedSparseArrays", "ValkyrieRobot", "VertexSafeGraphs"], vs = ":release-1.6")`

**Comment by KristofferC** [comment]
The various memory regressions for the Dict benchmarks are due to changes in the RNG. In 1.5, an integer < 256 was generated for these and these are special because they come pre-boxed in Julia and don't need an allocation. In 1.6, the integer is instead > 256 and thus an allocation is needed.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39614#issuecomment-792564622) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/d06bab0_vs_a58bdd9/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "Alpine", "ArrayInterface", "AtlasRobot", "BundleMethod", "ControlSystemIdentification", "DataDrivenDiffEq", "DiffEqCallbacks", "DiffEqJump", "EliminateGraphs", "ExponentialAction", "FilesystemDatastructures", "GalacticOptim", "Gen", "GenParticleFilters", "Grassmann", "HybridArrays", "Jaynes", "KernelFunctions", "Kinetic", "KissMCMC", "KitML", "Leibniz", "LoopThrottle", "MechanismGeometries", "MeshCatMechanisms", "ModelingToolkit", "ParticleScattering", "PastaQ", "PointPatterns", "QML", "Quadrature", "RandomizedProgressiveHedging", "RigidBodyDynamics", "Ripserer", "SimplePosetAlgorithms", "Solaris", "SpatialJackknife", "ThreadedSparseArrays", "ValkyrieRobot", "VertexSafeGraphs"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39614#issuecomment-793477700) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/1e20630_vs_a58bdd9/report.md). cc @maleadt

**Pull request merged**
