### PR TITLE
 release-1.7: Backports for 1.7-RC1

### LINKED ISSUE #41546: Concurrency violation during package loading
IIUC RelationaAI wanted to parallelize their testsuite. (cc: @Sacha0), and while we were looking into making Distributed.jl work with Julia processes that are launched with multi-threading enabled he saw
a failure such like:

```
ERROR: On worker 4:
LoadError: ConcurrencyViolationError("lock must be held")
Stacktrace:
  [1] concurrency_violation
    @ ./condition.jl:8
  [2] assert_havelock
    @ ./condition.jl:25 [inlined]
  [3] assert_havelock
    @ ./condition.jl:48 [inlined]
  [4] assert_havelock
    @ ./condition.jl:72 [inlined]
  [5] notify
    @ ./condition.jl:132
  [6] #notify#548
    @ ./condition.jl:130 [inlined]
  [7] _require
    @ ./loading.jl:1159
  [8] require
    @ ./loading.jl:1013
  [9] require
    @ ./loading.jl:997
 [10] top-level scope
    @ /build/source/usr/share/julia/stdlib/v1.7/Distributed/src/macros.jl:200
 [11] include
    @ ./client.jl:451
 [12] top-level scope
    @ none:1
 [13] eval
    @ ./boot.jl:373
 [14] #115
    @ /build/source/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:274
 [15] run_work_thunk
    @ /build/source/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:63
 [16] run_work_thunk
    @ /build/source/usr/share/julia/stdlib/v1.7/Distributed/src/process_messages.jl:72
 [17] #108
    @ ./threadingconstructs.jl:178
in expression starting at /tmp/nix-build-delve-build.drv-0/delve-source/test-
```

I wrote a small reproducer independent of Distributed.jl (the barrier nonsense just increases the likely hood of the failure.)

```
const ch = Channel{Bool}(Threads.nthreads())
const barrier = Base.Event()

@sync begin
    for _ in 2:Threads.nthreads()
        Threads.@spawn begin
            @eval begin
                put!(ch, true)
                wait(barrier)
                using LLVM
                @info "LLVM loaded" Threads.threadid()
            end
        end
    end

    for _ in 2:Threads.nthreads()
        take!(ch)
    end
    notify(barrier)
end
```

```
➜  rm ~/.julia/compiled/v1.6/LLVM/*
➜  test julia -t auto test.jl
Threads.threadid() = 3
Threads.threadid() = 2
Threads.threadid() = 4
┌ Info: LLVM loaded
└   Threads.threadid() = 3
ERROR: LoadError: TaskFailedException

    nested task error: concurrency violation detected
    Stacktrace:
      [1] error(s::String)
        @ Base ./error.jl:33
      [2] concurrency_violation()
        @ Base ./condition.jl:8
      [3] assert_havelock
        @ ./condition.jl:25 [inlined]
      [4] assert_havelock
        @ ./condition.jl:48 [inlined]
      [5] assert_havelock
        @ ./condition.jl:72 [inlined]
      [6] wait(c::Condition)
        @ Base ./condition.jl:102
      [7] _require(pkg::Base.PkgId)
        @ Base ./loading.jl:978
      [8] require(uuidkey::Base.PkgId)
        @ Base ./loading.jl:914
      [9] require(into::Module, mod::Symbol)
        @ Base ./loading.jl:901
     [10] top-level scope
        @ ~/src/snippets/test/test.jl:13
     [11] eval
        @ ./boot.jl:360 [inlined]
     [12] macro expansion
        @ ~/src/snippets/test/test.jl:8 [inlined]
     [13] (::var"#1#2")()
        @ Main ./threadingconstructs.jl:169

...and 1 more exception.

Stacktrace:
 [1] sync_end(c::Channel{Any})
   @ Base ./task.jl:369
 [2] top-level scope
   @ task.jl:388
in expression starting at /home/vchuravy/src/snippets/test/test.jl:5
```

I sometimes (after making sure that LLVM.jl is precompiled) also get:

```
➜  test julia -t auto test.jl

signal (6): Aborted
in expression starting at /home/vchuravy/src/snippets/test/test.jl:5
gsignal at /usr/bin/../lib/libc.so.6 (unknown line)
abort at /usr/bin/../lib/libc.so.6 (unknown line)
jl_recache_other_ at /buildworker/worker/package_linux64/build/src/dump.c:2458 [inlined]
jl_recache_other at /buildworker/worker/package_linux64/build/src/dump.c:2472 [inlined]
_jl_restore_incremental at /buildworker/worker/package_linux64/build/src/dump.c:2553
jl_restore_incremental at /buildworker/worker/package_linux64/build/src/dump.c:2605

signal (11): Segmentation fault
in expression starting at /home/vchuravy/src/snippets/test/test.jl:5
jl_recache_types at /buildworker/worker/package_linux64/build/src/dump.c:2346 [inlined]
_jl_restore_incremental at /buildworker/worker/package_linux64/build/src/dump.c:2550
jl_restore_incremental at /buildworker/worker/package_linux64/build/src/dump.c:2605
_include_from_serialized at ./loading.jl:658
_include_from_serialized at ./loading.jl:658
_require_search_from_serialized at ./loading.jl:760
_require_search_from_serialized at ./loading.jl:760
_require at ./loading.jl:998
_tryrequire_from_serialized at ./loading.jl:689
require at ./loading.jl:914
_require_search_from_serialized at ./loading.jl:749
require at ./loading.jl:901
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
call_require at /buildworker/worker/package_linux64/build/src/toplevel.c:421 [inlined]
eval_import_path at /buildworker/worker/package_linux64/build/src/toplevel.c:458
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:684
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:529
_require at ./loading.jl:998
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
macro expansion at /home/vchuravy/src/snippets/test/test.jl:8 [inlined]
#1 at ./threadingconstructs.jl:169
unknown function (ip: 0x7f4fa9f763fc)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:839
unknown function (ip: (nil))
Allocations: 2650 (Pool: 2639; Big: 11); GC: 0
```

### LINKED ISSUE #41630: `begin` indexing vs. `replace_ref_begin_end!`
I thought `Base.replace_ref_begin_end!` is used to implement `begin` indexing, but appearently they are inconsistent?

Reading the source of it, I stumbled upon [this line](https://github.com/JuliaLang/julia/blob/9044222bfcee604610d75db25d8d1c07e51cf7f0/base/views.jl#L45) in views.jl:

```julia
exj, used = replace_ref_begin_end_!(ex.args[j], (:($firstindex($S)),:($lastindex($S,$n))))
```

Shouldn't that be `$firstindex($S, $n)`?  I tried producing a failing example using OffsetArrays, but that only showed some sort of discrepancy, which I can't explain:

```julia
julia> a
2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10:
 1  2
 3  4

julia> a[end, begin]
3

julia> Meta.@lower a[end, begin]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.lastindex(a, 1)
│   %2 = Base.axes(a, 2)
│   %3 = Base.first(%2)
│   %4 = Base.getindex(a, %1, %3)
└──      return %4
))))

julia> Base.replace_ref_begin_end!(:(a[end, begin]))
:(a[(lastindex)(a, 1), (firstindex)(a)])

julia> a[(lastindex)(a, 1), (firstindex)(a)]
ERROR: BoundsError: attempt to access 2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10 at index [-9, 1]
Stacktrace:
 [1] throw_boundserror(::OffsetArray{Int64,2,Array{Int64,2}}, ::Tuple{Int64,Int64}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] getindex(::OffsetArray{Int64,2,Array{Int64,2}}, ::Int64, ::Int64) at /home/philipp/.julia/packages/OffsetArrays/Osysv/src/OffsetArrays.jl:407
 [4] top-level scope at REPL[22]:1
```

### LINKED ISSUE #41908: julia type inference crashes (typeerror)
my tests started crashing with the stacktrace:

```
Internal error: encountered unexpected error in runtime:
TypeError(func=:AbstractTensorMap, context="S", expected=S<:(TensorKit.ElementarySpace{𝕜} where 𝕜), got=TensorKit.HomSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}, TensorKit.ProductSpace{TensorKit.GradedSpace{Main.PlanarTrivial, Tuple{Int64}}, 0}})
jl_type_error_rt at /home/maarten/julia/src/rtutils.c:119
check_datatype_parameters at /home/maarten/julia/src/jltypes.c:1229
inst_datatype_inner at /home/maarten/julia/src/jltypes.c:1392
...
```

happens at least on julia 1.6.2, and also on master.

I wasn't able to really reduce it down very far, as it's a reasonably large codebase. To run it, you need my fork of TensorKit.jl, and the planocalypse branch of MPSKit.jl . I will try to reduce it down further, but so far I didn't have much luck.

```
using TensorKit,MPSKit;

#define some new sectortype - with the property that braiding is forbidden
struct PlanarTrivial <: TensorKit.Sector end
struct 𝔹 end
Base.:^(::Type{𝔹}, d::Int) = GradedSpace(PlanarTrivial()=>d);

Base.one(::Type{PlanarTrivial})  = PlanarTrivial();
Base.conj(c::PlanarTrivial) = PlanarTrivial();
TensorKit.:⊗(c1::PlanarTrivial, c2::PlanarTrivial) = (PlanarTrivial(),)

Base.IteratorSize(::Type{TensorKit.SectorValues{PlanarTrivial}}) = TensorKit.HasLength()
Base.length(::TensorKit.SectorValues{PlanarTrivial}) = 1
Base.iterate(::TensorKit.SectorValues{PlanarTrivial}, i = 0) = i==0 ? (PlanarTrivial(),1) : nothing;
Base.getindex(::TensorKit.SectorValues{PlanarTrivial}, i::Int) = i == 1 ? PlanarTrivial() : ArgumentError("lol");
TensorKit.findindex(::TensorKit.SectorValues{PlanarTrivial}, c::PlanarTrivial)  = 1
Base.isless(::PlanarTrivial, ::PlanarTrivial) = false;
TensorKit.BraidingStyle(::Type{PlanarTrivial}) = TensorKit.NoBraiding();
TensorKit.FusionStyle(::Type{PlanarTrivial}) = TensorKit.UniqueFusion();
TensorKit.Fsymbol(args::Vararg{PlanarTrivial,6}) = 1
TensorKit.Nsymbol(args::Vararg{PlanarTrivial,3}) = 1


# use mpskit
alg = GradientGrassmann(verbosity=0,maxiter=1);
mpo = InfiniteMPO([TensorMap(rand,ComplexF64,𝔹^2*𝔹^2,𝔹^2*𝔹^2)]);
state = InfiniteMPS([𝔹^2],[𝔹^10]);
(state,envs) = leading_boundary(state,mpo,alg);

```

### LINKED ISSUE #41975: SSA conversion drops bool typecheck for noop if
Actual:
```
julia> f() = (if nothing; end; unsafe_load(Ptr{Int}(0)))
f (generic function with 1 method)

julia> f()
Unreachable reached at 0x7fb33bb50090

signal (4): Illegal instruction
in expression starting at REPL[13]:1
unsafe_load at ./pointer.jl:105 [inlined]
unsafe_load at ./pointer.jl:105 [inlined]
```

Expected:
```
ERROR: TypeError: non-boolean (Nothing) used in boolean context
Stacktrace:
 [1] f()
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[2]:1
```

### LINKED ISSUE #42090: inference: need to invalidate stale `Conditional` wrapped in `PartialStruct`
MRE:
```julia
# should invalidate old constraint wrapped in PartialStruct when the subject of condition has changed
let M = Module()
    @eval M begin
        struct BePartialStruct
            val::Int
            cond
        end
    end

    rt = @eval M begin
        Base.return_types((Union{Nothing,Int},)) do a
            cond = a === nothing
            obj = $(Expr(:new, M.BePartialStruct, 42, :cond))
            r1 = getfield(obj, :cond) ? 0 : a # r1::Int
            a = $(gensym(:anyvar))::Any
            r2 = getfield(obj, :cond) ? a : nothing # r2::Any, not r2::Const(nothing)
            return r1, r2 # ::Tuple{Int,Any}
        end |> only
    end
    @test rt == Tuple{Int,Any}
end
```

I encountered `Conditional` wrapped in `PartialStruct` when the `Conditional` is captured in a closure.

Solutions:
- (dirty, but more accurate) we can add another special case as like `LimitedAccuracy`: https://github.com/JuliaLang/julia/blob/3aada5982c368f075dd0014dd9bdd5b8d2947b51/base/compiler/typelattice.jl#L366
- (simple, but less accurate) disallow `PartialStruct` to wrap `Conditional`

Which one do we want ?

### PR DESCRIPTION
**Pull request by KristofferC**
- [x] #41650 <!-- Printf %g/%G  format fix for Inf/NaN -->
- [x] #41796 <!-- CI (Buildkite): on the `platform_linux` jobs, after building Julia, make sure that the working directory is clean -->
- [x] #41812 <!-- CI: Disable Codecov commit statuses -->
- [x] #41811 <!-- CI (Buildbot): As soon as a PR is created or updated, create pending (yellow) commit statuses for all Buildbot jobs -->
- [x] #41814 <!-- CI (Buildbot): for the "Create Pending Statuses" GitHub Actions workflow, use the `pull_request_target` event instead of the `pull_request` event -->
- [x] #41815 <!-- CI (Buildbot): Fix a bug in the "Create Pending Statuses" GitHub Actions workflow -->
- [x] #41817 <!-- CI (Buildbot): a simpler way of getting the SHA for the "Statuses" action -->
- [x] #41822 <!-- CI (Buildbot, GHA): in the "Statuses" workflow, we only need to create pending (yellow) statuses for the `tester_` jobs -->
- [x] #41824 <!-- CI (Buildbot, GHA): in the "Statuses" workflow, remove the `macosaarch64` and `musl64` statuses -->
- [x] #41831 <!-- CI (Buildbot, GHA): in the "Statuses" workflow, remove the `tester_linuxppc64le` status -->
- [x] #41832 <!-- CI (Buildbot, GHA): In the "Statuses" workflow, remove the `tester_linuxarmv7l` status -->
- [x] #41825 <!-- CI (Buildbot, GHA): add a note about token permissions -->
- [x] #41842 <!-- Include an additional patch for OpenBLAS. -->
- [x] #41828 <!-- [IRShow] expose index information to postprinter -->
- [x] #41851 <!-- CI (Buildbot, GHA): Simplify the `permissions` key in the workflow file for the "Statuses" workflow -->
- [x] #41849 <!-- win: fix lock function call for backtrace collection -->
- [x] #41659 <!-- atomics: switch to using Pair for return pairs -->
- [x] #41835 <!-- Revert "Add vim bindings to TerminalMenus (#37940)" -->
- [x] #41695 <!-- Fix firstindex in replace_ref_begin_end (fixes #41630) -->
- [x] #41864 <!-- CI (Buildkite): `llvmpasses`: use the latest rootfs image -->
- [x] #41887 <!-- REPL: Don't look for missing packages in code that isn't going to be run -->
- [x] #41873 <!-- docs: add v1.7 compat for @atomic... + fix links -->
- [x] #41898 <!-- ensure that the non-REPL precompile code actually get precompiled -->
- [x] #41877 <!-- Fix ~370 invalidations from Expr(:ncat, ...) pretty-printing -->
- [x] #41878 <!-- Fix ~50 invalidations stemming from `modules_to_be_loaded` -->
- [x] #41672 <!-- small optimization to subtyping -->
- [x] #41956 <!-- README: add a link to the `base-buildkite-docs` repository -->
- [x] #41930 <!-- Derive better name for methods with external method tables. -->
- [x] #41929 <!-- Signatures: restrict color to backtrace printing -->
- [x] #41935 <!-- types: fix cache computation -->
- [x] #41919 <!-- Fix collect on stateful generator -->
- [x] #41867 <!-- fix a case where Vararg.T might be accessed when undefined -->
- [x] #41976 <!-- fix #41908, inference error in subst_trivial_bounds -->
- [x] #41733 <!-- Make `jl_cumulative_compile_time_ns` global (and reentrant). -->
- [x] #42010 <!-- Fix #41975 - Dropped typecheck in GotoIfNot -->
- [x] #42009 <!-- fix ptrhash_remove -->
- [x] #41827 <!-- Parameter attributes on Cfunction closures sticks -->
- [x] #41859 <!-- atomics: optimize modify operation (partially) -->
- [x] #41795 <!-- simplify and improve type intersection algorithm a bit -->
- [x] #42034 <!-- inference: add missing `LimitedAccuracy` handlings -->
- [x] #42024 <!-- improve atomic docs -->
- [x] #42035 <!-- fix missing layout allocation -->
- [x] #41839 <!-- Fix a precision issue in `abstract_iteration` -->
- [x] #42069 <!-- Fix grammar in deprecation warning -->
- [x] #42003 <!-- Avoid impossible unionall normalization -->
- [x] #42059 <!-- [AllocOpt] fix iterator invalidation -->
- [x] #42062 <!-- GMP: fix warning in init -->
- [x] #42058 <!-- avoid loading duplicate libraries -->
- [x] #42017 <!-- atomics: optimize atomic modify operations (mostly)  -->
- [x] #42091 <!-- inference: fix #42090, make sure not to wrap `Conditional` in `PartialStruct` -->
- [x] #42081 <!-- inference: propagate variable changes to all exception frames -->
- [x] #42061 <!-- InteractiveUtils: recursive correctly in varinfo, et al. -->
- [x] #42134 <!-- Missing package Install prompt: return unique modules in search -->
- [x] #42118 <!-- Fix the `cmdlineargs` tests on Buildkite -->
- [x] #41633 <!-- compiler: general refactor -->
- [x] #41697 <!-- more type-stable type-inference -->
- [x] #42112 <!-- inference: bail from const-prop if const-prop fails -->

Non-merged PRs with backport label:
- [ ] #42140 <!-- (#42139) Fixes _is_mailto in resolution of autolink in Markdown module -->
- [ ] #42138 <!-- CI (Buildkite): Allow any user with triage or commit permissions to retry all failed Buildkite jobs -->
- [ ] #42125 <!-- Allow constant-propagation to be disabled -->
- [ ] #42119 <!-- eagerly do boundscheck when indexing into CartesianIndices -->
- [ ] #41707 <!-- CI (Buildkite): Add `package_linux` and `tester_linux` for more Linux architectures -->
- [ ] #41602 <!-- fix #41546, make `using` thread-safe -->

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41781#issuecomment-907406874) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4cddbea_vs_d0c90f3/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "BayesianOptimization", "BilevelJuMP", "CartesianGrids", "DiffEqOperators", "FastMarching", "KernelFunctions", "MusicManipulations", "NumericalAlgorithms", "PLCTag", "PowerGraphics", "Publish", "SphericalHarmonicExpansions", "StaticKernels", "Symbolics", "Transparency", "VisualRegressionTests"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41781#issuecomment-907589222) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4cddbea_vs_d0c90f3/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41781#issuecomment-915105170):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.
cc @christopher-dG

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/5c9ebcd_vs_9e99af6/report.md

(Q: did you mean to compare to master?)

**Comment by KristofferC** [comment]
No.. Fail :(

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41781#issuecomment-915466514):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.
cc @christopher-dG

**Comment by vtjnash** [comment]
I've uploaded without the data files: https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0c1a860_vs_11e64d1/report.md

But note also the very large number of errors reported in the "primary" log files: https://raw.githubusercontent.com/JuliaCI/NanosoldierReports/master/benchmark/by_hash/0c1a860_vs_11e64d1/logs/0c1a860ce5fb2f440bfd23be5a98343c28d39aef_primary.err

due to c2c5a83ee1e0941740ce90181337acaaa59acbc0 being backported incorrectly or without 795935fd3a2d97b2f948cfb82a18da48743b622d (#41697)

**Comment by KristofferC** [comment]
Scary that all the tests passed...

**Comment by KristofferC** [comment]
Let's try with non-broken inference then. Third time's the charm?

@nanosoldier `runbenchmarks(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41781#issuecomment-916016950):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.
cc @christopher-dG

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/7b26fa7_vs_11e64d1/report.md

**Comment by timholy** [comment]
Awesome! What are your thoughts on the likelihood of getting #42125 in? In a sense maybe it doesn't matter since it's not a supported name, but it's not crazy to think that a renaming post-rc1 is also a bit weird.

**Comment by DilumAluthge** [comment]
Are those names part of the public API/do those names appear in the documentation? If not, it wouldn't be breaking to change the names in 1.8, right?

**Comment by timholy** [comment]
Not part of the public API, so we can break them without consequence.

**Pull request merged**
