### PR TITLE
deprecate readcsv in favor of readdlm

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request deprecates `readcsv(io[, T::Type]; opts...)` in favor of `readdlm(io, ','[, T]; opts...)`, addressing part of #23414. Best!

### CODE REVIEW

**Comment by dpsanders** [comment]
Isn't readcsv a more obvious name than readdlm?

**Comment by JeffBezanson** [comment]
That's the problem. You shouldn't use this function, because a far better implementation exists in a package.

**Comment by dpsanders** [comment]
I meant that the name readdlm is hard to discover and hard to remember.

**Comment by StefanKarpinski** [comment]
> I meant that the name readdlm is hard to discover and hard to remember.

True. I'm all for deleting `readdlm` as well.

**Comment by ViralBShah** [comment]
So, just to load some simple files in Base, one has to go mucking with packages? I don't understand this obsession with deleting everything.

**Comment by Sacha0** [comment]
Thanks all! :)

**Pull request merged**
