### PR TITLE
Enable new optimizer by default

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by vtjnash** [comment]
Can we run binary builder on this PR (helps with doing PkgEval)

**Comment by ararslan** [comment]
Getting this on Circle:
```
error during bootstrap:
LoadError(at "compiler/compiler.jl" line 3: LoadError(at "compiler/bootstrap.jl" line 8: MethodError(f=Array{Tuple{Int64, Int64}, 1}, args=(Array{Tuple{Int32, Int32}, (1,)}[(4, 17)],), world=0x00000fa3)))
rec_backtrace at /home/circleci/project/src/stackwalk.c:94
record_backtrace at /home/circleci/project/src/task.c:246
jl_throw at /home/circleci/project/src/task.c:577
jl_method_error_bare at /home/circleci/project/src/gf.c:1601
jl_method_error at /home/circleci/project/src/gf.c:1619
jl_lookup_generic_ at /home/circleci/project/src/gf.c:2110 [inlined]
jl_apply_generic at /home/circleci/project/src/gf.c:2130
unknown function (ip: 0xf0d136ef)
jl_fptr_sparam at /home/circleci/project/src/gf.c:1831
jl_fptr_trampoline at /home/circleci/project/src/gf.c:1816
jl_apply_generic at /home/circleci/project/src/gf.c:2133
unknown function (ip: 0xf0516cf6)
```
Once this branch builds and passes and all that, we can just trigger a buildbot build using the branch SHA, then running PackageEvaluator using the resulting binary is quite straightforward. (Essentially the same as is outlined in DISTRIBUTING.md.)

**Comment by Keno** [comment]
Yeah, I saw, looks like we need to `Int64`->`Int` somewhere.

**Comment by martinholters** [comment]
How is the compile time using the new vs. the old optimizer, e.g. building the sysimg?

**Comment by Keno** [comment]
Worse, but we intend to address that in the 1.0 time frame.

**Comment by JeffBezanson** [comment]
How much worse?

**Comment by Keno** [comment]
About 40% regression on pure sysimg build time (stdlib is essentially unchanged) it seems. That includes the time it takes to compile the optimizer itwelf. A bit less when disabling the IR verifier which we should do. Don't think that's entirely due to compile time regression testing though. We may have to take a look at the inlining thresholds post new optimizer, since the IR looks quite a bit different now. On the other hand, last I checked it was about on par if we also merge kf/iterate (makes the old optimizer quite a bit slower, essentially no effect on the new one).

**Comment by mbauman** [comment]
🎉

**Comment by iblis17** [comment]
Got error on master branch build, after this PR merged.
https://freebsdci.julialang.org/#/builders/1/builds/9415

**Comment by iblis17** [comment]
seems it's FreeBSD only issue.

**Comment by ararslan** [comment]
Reported in #27109

**Pull request merged**
