### PR TITLE
Include "module" in ctags

### PR DESCRIPTION
**Pull request by mauro3**
This also adds the module-names to the TAGS file.

### CODE REVIEW

**Comment by ararslan** [comment]
Seems like the ctags stuff should live outside of Base.

**Comment by mauro3** [comment]
JuliaEditorSupport/Julia-ctags ?

**Comment by StefanKarpinski** [comment]
I don't think this needs triage. This should be moved out but `contrib` is not a public part of Julia's API – anything in there can be changed, moved or deleted at any time.

**Comment by oxinabox** [comment]
I suggest it should be added to the actual upstream CTags repo.
(is that https://github.com/universal-ctags/ctags ?)

And then linked in  https://github.com/JuliaEditorSupport/3rd-Party-Highlighters

**Comment by ViralBShah** [comment]
@mauro3 Can you help with moving the ctags out of contrib and into a new repo for now, and potentially upstream (although that may be more effort but ultimately better)

**Comment by mauro3** [comment]
Can do.  Probably best to do a PR with  https://github.com/universal-ctags/ctags as suggested by @oxinabox, but after feature freeze; just in case Jeff has another crazy idea (#19157).

**Comment by ViralBShah** [comment]
How about we move this file to a repo in `JuliaEditorSupport` for now?

**Comment by ViralBShah** [comment]
https://github.com/JuliaEditorSupport/julia-ctags

Invited you @mauro3. Would you mind moving the file over? I am closing this one.

**Pull request closed without merging**
