### PR TITLE
explain method signatures for `Any` arguments

### PR DESCRIPTION
**Pull request by heliosdrm**
Context: https://discourse.julialang.org/t/function-type-signature/43101/17?u=heliosdrm

### CODE REVIEW

**Comment by tpapp** [comment]
Yes, a sentence mentioning this, maybe with an example, would be useful. Perhaps right at the beginning of the *Methods* chapter, before the example with constraints in the method signature.

**Comment by JeffBezanson** [comment]
This failed doctests.

**Comment by StefanKarpinski** [comment]
Ooops.

**Comment by heliosdrm** [comment]
So, should I wait until https://github.com/JuliaDocs/Documenter.jl/pull/1369 is solved, and the redo this PR? Or do you have another suggestion to work around it? Thanks.

**Pull request merged**
