### PR TITLE
Fix #13175, segfault with 👻 fields

### LINKED ISSUE #13175: Codegen segfault when comparing immutable with 👻 field
This is the minimal reproducer for JuliaLang/JLD.jl#22 and simonster/JLD2.jl#3:

```julia
julia> immutable EmptyImmutable end

julia> immutable EmptyIIOtherField
           x::EmptyImmutable
           y::Float64
       end

julia> EmptyIIOtherField(EmptyImmutable(), 1.0) == EmptyIIOtherField(EmptyImmutable(), 1.0)

signal (11): Segmentation fault: 11
_ZNK4llvm5Value10getValueIDEv at /usr/local/julia/usr/include/llvm/IR/Value.h:231
_ZL17emit_bits_compareRK10jl_cgval_tS1_P12jl_codectx_t at /usr/local/julia/src/codegen.cpp:2050
_ZL10emit_errorRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEP12jl_codectx_t at /usr/local/julia/src/./cgutils.cpp:892
_ZL9emit_callPP11_jl_value_tmP12jl_codectx_tS0_ at /usr/local/julia/src/codegen.cpp:2808
_ZL13emit_functionP17_jl_lambda_info_t at /usr/local/julia/src/codegen.cpp:4911
_Z19jl_eh_restore_stateP13_jl_handler_t at /usr/local/julia/src/./julia.h:1359
jl_compile at /usr/local/julia/src/codegen.cpp:940
jl_trampoline_compile_function at /usr/local/julia/src/builtins.c:1015
jl_apply at /usr/local/julia/src/./julia.h:1274
jl_apply at /usr/local/julia/src/gf.c:1691
jl_apply at /usr/local/julia/src/interpreter.c:55
eval at /usr/local/julia/src/interpreter.c:213
jl_toplevel_eval_flex at /usr/local/julia/src/toplevel.c:527
jl_toplevel_eval_in at /usr/local/julia/src/builtins.c:569
eval_user_input at REPL.jl:62
jlcall_eval_user_input_21750 at  (unknown line)
anonymous at REPL.jl:92
jl_apply at /usr/local/julia/src/task.c:241
fish: Job 1, 'julia' terminated by signal SIGSEGV (Address boundary error)
```

Only broken on master (not release-0.4). cc @vtjnash

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

**Comment by ivarne** [comment]
The test should be on release-0.4 even though it isn't broken there, right?

**Comment by tkelman** [comment]
backported just the test in #13182

**Comment by ivarne** [comment]
@tkelman Thanks for your heroic efforts maintaining `release-0.4`, keeping it in sync with master (and even running package evaluator to prevent easily avoidable breakage). I really miss the 0.3 days when my Mac was alive and I had a build environment to backport changes.

**Comment by StefanKarpinski** [comment]
Yes, thank you, @tkelman, for all the backporting work!

**Pull request merged**
