### PR TITLE
 release-1.7: set VERSION to 1.7.1

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runtests("shootout", vs="#v1.7.0")`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("shootout", vs="#v1.7.0")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997567092):
```
CompositeException(Any[TaskFailedException(Task (failed) @0x00007fff608a7c70)])
```

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997566317):
```
NanosoldierError: failed to run tests: MethodError: no method matching read_pkgs(::String)
Closest candidates are:
  read_pkgs() at /storage/pkgeval/depot/packages/PkgEval/a8wK1/src/registry.jl:39
  read_pkgs(!Matched::Vector{String}; registry) at /storage/pkgeval/depot/packages/PkgEval/a8wK1/src/registry.jl:39
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/b36816a_vs_3bf9d17/report.md)
cc @maleadt

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("shootout", vs="#v1.7.0")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997574164):
```
CompositeException(Any[TaskFailedException(Task (failed) @0x00007fff91d0c940)])
```

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("shootout", vs="#v1.7.0")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997576975) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/bae2d8d_vs_3bf9d17/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("ALL", vs="#v1.7.0")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs="#v1.7.0")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997772637) has completed, but no benchmarks were actually executed. Perhaps your tag predicate contains misspelled tags? cc @

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43480#issuecomment-997773009):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/bae2d8d_vs_3bf9d17/report.md

**Pull request merged**
