### PR TITLE
Add `compiler` as a test group

### PR DESCRIPTION
**Pull request by Keno**
For what the inference test used to be.

### CODE REVIEW

**Review by jrevels — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
There is already a `compile` test target so this naming seem potentially confusing.

**Comment by jrevels** [comment]
> There is already a compile test target so this naming seem potentially confusing.

Could change to `basecompiler` (i.e. "the part of the compiler that lives in Base"), which is what I've been using whenever it could be ambiguous

**Comment by StefanKarpinski** [comment]
We could add the `compile` tests to the `compiler` test suite.

**Comment by JeffBezanson** [comment]
The compile.jl test could be renamed precompile.jl, since that's mostly what it's about.

**Review by vtjnash — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
How about renaming `test/compile` to `test/precompile` at the same time?

**Pull request merged**
