### PR TITLE
Test suite: after running a test set, throw an error if `Base.DEPOT_PATH`, `Base.LOAD_PATH`, or `ENV` have been modified and not restored to their original values

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by gbaraldi** [comment]
LGTM, whitespace check aside.

**Comment by KristofferC** [comment]
Hm, why though? This feels kind of arbitrary. What about the eg the ENV or other global state.

**Comment by DilumAluthge** [comment]
There is currently a known non-deterministic test failure in the `cmdlineargs` test set that is caused by other test sets that modify `Base.DEPOT_PATH` and do not properly restore the original value. If the `cmdlineargs` test set happens to run on the same worker process that previously ran one of those test sets, then the failure will occur.

So this PR only deals with the depot path and load path because those are the ones relevant to this specific `cmdlineargs` test failure. But I have no objection to also checking `ENV` or other pieces of global state.

An alternative would be to always kill the worker process after each test set, so each test set gets a brand new worker process.

**Comment by DilumAluthge** [comment]
I've added `ENV` to the list of global things that we check. If there are other global states that we should check, we can add those also.

**Comment by DilumAluthge** [comment]
Pkg fix is in https://github.com/JuliaLang/Pkg.jl/pull/3191 via https://github.com/JuliaLang/julia/pull/46615.

**Comment by DilumAluthge** [comment]
Depot path fixes for `loading` and `precompile` are in https://github.com/JuliaLang/julia/pull/46616.

**Comment by DilumAluthge** [comment]
The `ENV` fixes for `corelogging`, `env`, and `REPL` are in .

**Comment by DilumAluthge** [comment]
The `ENV` fix for `Pkg` is in https://github.com/JuliaLang/Pkg.jl/pull/3192 via [TODO bump PR]?

**Comment by gbaraldi** [comment]
I think leaving the ENV checks there is fine and hopefully this stops naught tests again. LGTM

**Pull request merged**
