### PR TITLE
[release-1.4] Set VERSION to 1.4.0-rc1

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Review by KristofferC — APPROVED** [review]

**Comment by rfourquet** [comment]
#32414 is on the 1.4 milestone, is it planned to be fixed after RC1 ?

**Comment by KristofferC** [comment]
Maybe? I don't understand why it is on the milestone though.

**Comment by rfourquet** [comment]
> I don't understand why it is on the milestone though.

Probably because it was identified as the cause of the failure of BitIntegers (#34288) (I already fixed the other problem with this package on 1.4 related to `signed`, mentioned there: https://github.com/JuliaLang/julia/pull/34238#issuecomment-571297077)

**Comment by KristofferC** [comment]
Previously, it just gave garbage though, right? We just added the assert to catch it in assert builds.

**Comment by rfourquet** [comment]
> Previously, it just gave garbage though, right?

After investigation, you seem to be right: I was testing `@test f(x) == y`, `f(x)` was actually not equal to `y` but the `==` was still returning `true`, now it segfaults because of the assertion. I guess this still should not segfault though.

**Review by KristofferC — CHANGES_REQUESTED** [review]
Let's get https://github.com/JuliaLang/julia/pull/34461 in as well

**Comment by KristofferC** [comment]
> I guess this still should not segfault though.

Ideally, all bugs should be fixed but this is at least an improvement over status quo?

**Review by KristofferC — APPROVED** [review]
Should be good to go now

**Comment by ararslan** [comment]
CI seems not particularly happy

**Comment by KristofferC** [comment]
All green now.

**Pull request merged**
