### PR TITLE
RFC: Update Windows build toolchain and instructions

### PR DESCRIPTION
**Pull request by tkelman**
This uses the opensuse toolchain, to maximize compatibility with WinRPM packages. Ref previous related issues and discussion in #10490 #11285 and #11682.

I haven't gotten this toolchain to fully work in Cygwin yet, since it's a native windows compiler executable and not cygwin-hosted so it doesn't understand Cygwin paths, symlinks, etc. If we're lucky, a future cygwin mingw-w64 package update might restore ABI compatibility with opensuse. We'll need to figure out something to do about the buildbots, which are currently cygwin-based. Maybe we could transition or augment them with MSYS2 and/or opensuse cross-compile.

I'd greatly appreciate people testing this, especially from a clean environment (pristine VM or fresh separate install of msys2, no pre-existing junk on the path, etc) to verify that it works as I'm describing for other people too.

I'll be adding another commit shortly that replaces the cross-compiling section of README.windows.md with a much simpler set of Docker+opensuse instructions.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
```
C:\Users\Sim\AppData\Local\Julia-0.4.0-dev\share\julia\test>julia runtests.jl all
        From worker 5:       * linalg4              in  25.04 seconds
        From worker 5:       * linalg/lapack        in  27.55 seconds
        From worker 4:       * linalg3              in  61.16 seconds
        From worker 4:       * linalg/tridiag       in  15.53 seconds
        From worker 3:       * linalg2              in  85.88 seconds
        From worker 4:       * linalg/bidiag        in  31.97 seconds
        From worker 3:       * linalg/diagonal      in  28.99 seconds
        From worker 3:       * linalg/givens        in   6.65 seconds
        From worker 4:       * linalg/pinv          in  19.93 seconds
        From worker 3:       * linalg/cholesky      in  71.02 seconds
        From worker 4:       * linalg/lu            in  63.75 seconds
        From worker 2:       * linalg1              in 196.67 seconds
        From worker 3:       * linalg/symmetric     in  15.71 seconds
        From worker 3:       * keywordargs          in   5.23 seconds
        From worker 4:       * linalg/arnoldi       in  41.61 seconds
        From worker 2:       * core                 in  50.73 seconds
        From worker 4:       * strings              in  55.59 seconds
        From worker 5:       * linalg/triangular    in 258.09 seconds
        From worker 5:       * hashing              in  26.62 seconds
        From worker 4:       * dict                 in  46.82 seconds
        From worker 5:       * remote               in   1.18 seconds
        From worker 5:       * staged               in   1.84 seconds
        From worker 4:       * iobuffer             in   2.78 seconds
        From worker 4:       * tuple                in   3.64 seconds
        From worker 3:       * numbers              in 146.67 seconds
        From worker 2:       * dates                in 116.27 seconds
        From worker 3:       * reduce               in   5.85 seconds
        From worker 3:       * random               in  18.99 seconds
        From worker 3:       * intfuncs             in   1.02 seconds
        From worker 3:       * simdloop             in   1.99 seconds
        From worker 2:       * reducedim            in  26.97 seconds
        From worker 3:       * blas                 in   3.54 seconds
        From worker 5:       * arrayops             in  56.97 seconds
        From worker 5:       * copy                 in   2.88 seconds
        From worker 5:       * math                 in  17.49 seconds
        From worker 5:       * fastmath             in   5.61 seconds
        From worker 5:       * functional           in   1.94 seconds
        From worker 5:       * operators            in   0.30 seconds
        From worker 5:       * path                 in   3.43 seconds
        From worker 5:       * ccall                in   2.58 seconds
        From worker 5:       * unicode              in   6.33 seconds
        From worker 5:       * bigint               in   4.17 seconds
        From worker 2:       * sparse               in  94.62 seconds
        From worker 5:       * sorting              in  43.66 seconds
        From worker 5:       * spawn                      [stdio passthrough ok]
bash.exe: warning: could not find /tmp, please create!
bash.exe: warning: could not find /tmp, please create!
bash.exe: warning: could not find /tmp, please create!
        From worker 3:       * bitarray             in  98.11 seconds
        From worker 3:       * backtrace            in   0.34 seconds
        From worker 3:       * priorityqueue        in   1.76 seconds
        From worker 2:       * statistics           in  19.28 seconds
        From worker 5:   in  20.08 seconds
        From worker 2:       * version              in   3.13 seconds
        From worker 2:       * pollfd               in   0.01 seconds
        From worker 3:       * file                 in  14.11 seconds
        From worker 2:       * mpfr                 in   8.55 seconds
        From worker 5:       * resolve              in  12.60 seconds
        From worker 2:       * complex              in   5.57 seconds
        From worker 2:       * floatapprox          in   0.51 seconds
        From worker 5:       * socket               in   4.32 seconds
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
        From worker 3:       * broadcast            in  17.50 seconds
        From worker 5:       * reflection           in   2.84 seconds
        From worker 3:       * regex                in   1.36 seconds
        From worker 5:       * float16              in   2.06 seconds
        From worker 5:       * sysinfo              in   1.91 seconds
        From worker 3:       * combinatorics        in   4.24 seconds
        From worker 5:       * rounding             in   1.76 seconds
        From worker 5:       * mod2pi               in   0.35 seconds
        From worker 5:       * euler                in   2.36 seconds
        From worker 5:       * show                 in   5.52 seconds
        From worker 5:       * lineedit             in   6.77 seconds
        From worker 2:       * readdlm              in  27.25 seconds
        From worker 5:       * replcompletions      in   5.80 seconds
        From worker 5:       * replutil             in   2.65 seconds
        From worker 5:       * sets                 in   4.58 seconds
        From worker 5:       * test                 in   0.57 seconds
        From worker 5:       * goto                 in   0.12 seconds
        From worker 5:       * llvmcall             in   0.11 seconds
        From worker 2:       * repl                 in  18.06 seconds
        From worker 5:       * grisu                in   9.49 seconds
        From worker 5:       * meta                 in   0.54 seconds
        From worker 2:       * nullable             in   4.12 seconds
        From worker 2:       * libgit2              in   0.04 seconds
        From worker 2:       * docs                 in   1.35 seconds
        From worker 5:       * profile              in   5.22 seconds
        From worker 5:       * base64               in   0.63 seconds
        From worker 5:       * parser               in   0.96 seconds
        From worker 2:       * markdown             in   6.42 seconds
        From worker 2:       * functors             in   0.96 seconds
        From worker 2:       * char                 in   1.07 seconds
        From worker 5:       * serialize            in   4.83 seconds
        From worker 3:       * ranges               in  58.09 seconds
        From worker 5:       * enums                in  10.08 seconds
        From worker 5:       * i18n                 in   0.05 seconds
        From worker 5:       * fft                  in   6.50 seconds
        From worker 5:       * dsp                  in   6.72 seconds
        From worker 4:       * subarray             in 269.65 seconds
        From worker 2:       * misc                 in  38.30 seconds
        From worker 5:       * examples             in  46.20 seconds
        From worker 4:       * parallel             in  62.76 seconds
        From worker 3:       * cmdlineargs          in 289.72 seconds
    SUCCESS
```

```Julia
Julia Version 0.4.0-dev+5368
Commit d8e5d6f (2015-06-14 02:22 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Thanks,
Simon

**Comment by tkelman** [comment]
Thanks! That was MSYS2, using the script and instructions here? That commit looks like master, rather than this branch.

Looks like cross-compiling won't actually work under docker, will try with vagrant instead today.

**Comment by SimonDanisch** [comment]
Oh I think I haven't fully understood your intentions. This was the binary from juliang.org!

**Comment by tkelman** [comment]
At least that confirms https://github.com/JuliaLang/julia/issues/11682#issuecomment-111752155 that the nightlies are working. I moved the comment into a gist to save space.

This PR is about updating the recommended toolchain and build instructions.

**Comment by Mike43110** [comment]
`pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime`

This line should replace point number 2. I just reinstalled msys2 and opening `msys2_shell.bat` just opens the msys shell on the latest version. After the above lines run the system files are then updated and then it must be restarted.

**Comment by tkelman** [comment]
Should that replace `ii` or `iii` ? Is `pacman-key --init` still needed?

**Comment by Mike43110** [comment]
That'll teach me to read the raws and not the formatted version!
`iii` should be replaced. `pacman -Syu` fails otherwise.
I just checked and the system update works without it. `-Syu` seems to work as well. I am not sure what that does (other than init pacman-key).

**Comment by Mike43110** [comment]
I just ran the `get_toolchain.sh` and got 2 404s. It did say that it was successful however.

I will retry it and build it tomorrow, can't stay up and resume the failed downloads unfortunately.

**Comment by tkelman** [comment]
The downloads fall back to a mirror so the 404's are probably not fatal, if the fallback fails then the script should terminate with an error. How do the updated msys2 setup steps look? I'll probably try in a clean VM just to make sure it works okay, so far I've been running the cross-compiles.

**Comment by Mike43110** [comment]
They look fine now. I can't see anything wrong with a quick read-through.

**Comment by tkelman** [comment]
Pretty sure this works now, let me know if any feedback, will merge soon if I don't get any.

We also need to fix the toolchain on release-0.3 before we tag 0.3.10.

**Comment by tkelman** [comment]
Err, I thought this was working. Now msys2 Python (which I was hoping would make the installation simpler) is interacting badly with virtualenv https://github.com/pypa/virtualenv/issues/650 - could have sworn I built the docs successfully at least once.

**Comment by ihnorton** [comment]
>  If we're lucky, a future cygwin mingw-w64 package update might restore ABI compatibility with opensuse.

Is the issue that opensuse did a major version bump of libstdc++?

**Comment by tkelman** [comment]
Not even! They did that a month or two ago and it didn't cause that many problems. A couple weeks ago they fixed a typo in a gcc configure flag and that apparently caused ABI breakage. https://build.opensuse.org/package/rdiff/windows:mingw:win64/mingw64-gcc?linkrev=base&rev=73

Oh, the neverending "joys" of C++.

**Comment by ihnorton** [comment]
I see, thanks. Fun times: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=16612

Linking (your) relevant cygwin mailing list post for future reference: http://comments.gmane.org/gmane.os.cygwin/153535

**Comment by tkelman** [comment]
Also ref https://github.com/staticfloat/julia-buildbot/issues/20#issuecomment-112668808 where we're figuring out what to do about the buildbots.

**Comment by ScottPJones** [comment]
>Oh, the neverending "joys" of C++
Hehe... precisely why I'm working so hard to make sure I can use julia for my consulting job... Hell would be going to C++ full time!

**Comment by Keno** [comment]
C++ standard library ABIs are absolutely horrible. I just lost a week of my life to the fact that std::shared_ptr ABIs differ depending on whether the compiler thinks it has certain atomics, causing subtly memory corruption if not GRRRR.

**Comment by tkelman** [comment]
Last call for comments, I'll merge if no one has any.

**Comment by SimonDanisch** [comment]
Seems to build fine on my windows machine + cygwin!

**Comment by tkelman** [comment]
I know cygwin works, what's more in need of testing here is the opensuse toolchain + msys2. Cygwin-built Julia won't work with WinRPM packages at the moment. This unfortunately keeps changing.

**Comment by SimonDanisch** [comment]
Is the behaviour that it hangs at "INFO: Extracting packageX" ?

**Comment by tkelman** [comment]
The behavior would more likely be something like `Provider PackageManager failed to satisfy dependency libzmq` because it fails to dlopen the zmq library built against a different libstdc++ ABI.

**Comment by SimonDanisch** [comment]
... Is the WinRPM problem supposed to also happen with the prebuild binaries from julialang? 
Because the hanging actually happens with these binaries (on both my windows desktops).
Now I additionally tested the freshly build tk/winbuild branch:
```Julia
using WinRPM
WinRPM.install("gcc")
..
..
..
INFO: Extracting: runtime
#nothing happens anymore
```
This goes for all tested versions, which were something between 5-day old master and 0-day old master (juliang binary) and this branch here.

**Comment by tkelman** [comment]
Yes the nightly binaries are built from cygwin so are also broken with WinRPM packages right now.

Just checking, you did the usual `make win-extras` steps from this branch?

**Comment by SimonDanisch** [comment]
yes! also make binary-dist, installed it and copied `lib/julia`

**Comment by tkelman** [comment]
And by freshly built you mean from cygwin? I don't know what's wrong with the extraction.

I hope an msys2+opensuse toolchain build would run more smoothly, I'll try to test that along with WinRPM on my own machine.

**Comment by SimonDanisch** [comment]
Yes, that's what I meant.
Also, I think that Julia hangs while starting sometimes...Not sure if this is still related in any way, though.

**Comment by tkelman** [comment]
The freeze is #9242 #7942 and probably unrelated.

**Comment by tkelman** [comment]
Sorry to @SimonDanisch that what I was wanting help with testing here was unclear. I just did some tests using an MSYS2 + opensuse toolchain build with WinRPM packages and things worked more or less the way I expected them to, so I'll merge this.

**Comment by tkelman** [comment]
backport moved to #11793

**Pull request merged**
