### PR TITLE
RFC: Split multi.jl into multiple files. Wrap parallel into its own module.

### PR DESCRIPTION
**Pull request by amitmurthy**
A first step in refactoring and making multi.jl more modular with cleaner separation of functionality. This PR splits multi.jl into smaller files and moves all multiprocessing code into a new module `Base.Parallel`

### CODE REVIEW

**Comment by amitmurthy** [comment]
Any thoughts on this? Any reasons to *NOT* have a `Parallel` submodule.

**Comment by vchuravy** [comment]
:+1: from me.

**Comment by amitmurthy** [comment]
Will merge this tomorrow.

**Comment by ViralBShah** [comment]
Now that you ask could be to have a separate module for RPC / distributed computing that can be used to build any arbitrary distributed computing system and put user-facing parallel computing models in a parallel module.

**Comment by amitmurthy** [comment]
@ViralBShah , I agree with you on differentiating between a higher level API (for users) and a lower level RPC API (for library writers).  However, at this time I want to merge this as is and take some more time to debate the correct way of modularization Parallel and the interfaces between each of them.

Broadly, functionally I can think of

- ClusterManagement - partially modularized via ClusterManagers.jl . Needs a rework to handle elastic computation scenarios better.
- Serialization, Transport, Topology - Option to plugin other serialization schemes? Other IO infrastructure, routing via intermediate nodes, etc.
- Communication primitives - point-to-point remote calls (existing), collective MPI style communication (not yet defined)
- User facing API - pmap, distributed arrays, etc

> Not relevant here, but do we need to put Channels in their own module too?

IMO, Channels and all task related code should be grouped together under module `Tasks`

**Comment by vtjnash** [comment]
> Any reasons to NOT have a Parallel submodule

In order to make this a toplevel module? 😛 

But seriously, would it be difficult to make this a toplevel module? I think `using Parallel` would be nicer than `using Base.Parallel`, and would better align with making this a stdlib module.

**Comment by vchuravy** [comment]
@vtjnash That is the long term-goal, but should we start moving bits and pieces out before we have the infrastructure for `stdlib`?

**Comment by vtjnash** [comment]
We should be able to make them toplevel modules without yet changing anything about the `stdlib` infrastructures. I expect this may be one of the harder ones to detangle, however. The PR here will be a useful start to that process.

**Comment by amitmurthy** [comment]
As a first step, I'll just rebase and merge as is. Will take a shot at making it a top-level module in a different PR. 

The main issues in distentangling that I see are:
- current behavior of `using` that loads on all workers. https://github.com/JuliaLang/julia/pull/19073 may remove the need for this.
- loading from node 1
- workers preloading the Parallel module when they come up

**Comment by amitmurthy** [comment]
I am going to rework this again in a few days to make it mergeable. Would like to get it in in the 0.6 timeframe. No user facing functionality change. Just code reorg.

**Comment by tkelman** [comment]
still planning on doing this?

**Comment by amitmurthy** [comment]
Yes. I am waiting for other PRs to get in / not get in before redoing this PR.

**Comment by StefanKarpinski** [comment]
You may want to refresh this change so it can be merged since it's not externally visible and then rebase the parallel for change on top of this.

**Comment by StefanKarpinski** [comment]
Not externally visible – can be done whenever.

**Comment by amitmurthy** [comment]
Closing in favor of #20428

As mentioned there, we should get this in soon. Will help in backporting bugfixes onto 0.6.

**Pull request closed without merging**
