### PR TITLE
[SuiteSparse_jll] Update to v7.0.1

### PR DESCRIPTION
**Pull request by fxcoudert**
This will not work currently, as it requires merging of https://github.com/JuliaPackaging/Yggdrasil/pull/6296 first
This is currently progressing through a full build from source on my machine

### CODE REVIEW

**Comment by ViralBShah** [comment]
SparseArrays.jl needs updates to use the new SuiteSparse as discussed in https://github.com/JuliaSparse/SparseArrays.jl/issues/332. We shouldn't update before that is done, and we bump SparseArrays.jl here.

**Comment by fxcoudert** [comment]
@ViralBShah fix proposed at https://github.com/JuliaSparse/SparseArrays.jl/pull/353

**Comment by ViralBShah** [comment]
I've triggered the [sparsearrays bump](https://github.com/JuliaLang/BumpStdlibs.jl/actions/runs/4318367248/jobs/7536569022). Once that is in, we can upgrade the other pieces here.

**Comment by fxcoudert** [comment]
Indeed, will rebase after https://github.com/JuliaLang/julia/pull/48876 is merged

**Comment by ViralBShah** [comment]
The SparseArrays bump PR is https://github.com/JuliaLang/julia/pull/48876

**Comment by fxcoudert** [comment]
Now waiting on https://github.com/JuliaLang/julia/pull/48914

**Comment by fxcoudert** [comment]
```
┌ Warning: CHOLMOD version incompatibility
  | │
  | │ Julia was compiled with CHOLMOD version 3.0.14. It is
  | │ currently linked with version 4.0.3.
  | │ This might cause Julia to terminate when working with
  | │ sparse matrix factorizations, e.g. solving systems of
  | │ equations with \.
  | │
  | │ It is recommended that you use Julia with the same major
  | │ version of CHOLMOD as the one used during the build, or
  | │ download the generic binaries from www.julialang.org,
  | │ which ship with the correct versions of all dependencies.
  | └ @ SparseArrays.CHOLMOD /cache/build/default-amdci5-7/julialang/juliamaster/usr/share/julia/stdlib/v1.10/SparseArrays/src/solvers/cholmod.jl:199
```

I have a hard time understanding where that `3.0.14` version comes from.

```
ERROR: could not load library "libspqr"
  | │    libspqr_cuda.so.3: cannot open shared object file: No such file or directory
```

😢

**Comment by fxcoudert** [comment]
Re. the CHOLMOD version warning. I welcome guidance here, because I really don't understand the update and testing process. I've opened an issue at https://github.com/JuliaSparse/SparseArrays.jl/issues/359 because it appears it should be fixed there. But it's like I'm missing something, because a dependency update needs:

1. an update on Yggdrasil (and publishing of the builds)
2. an update on generated sources in SparseArrays.jl (built against what? unclear to me)
3. an update of the SparseArrays.jl in julia
4. an update of the julia source build

and steps 2 and 3 need to be possibly done multiple times because when SparseArrays.jl is updated, it doesn't fully test julia, so it needs to be iterated until new problems are discovered.

**Comment by Wimmerer** [comment]
Regarding unconditional loading of the CUDA SPQR this is somewhat annoying. It means we'll have to rename the actual CUDA binaries...

**Comment by ViralBShah** [comment]
It is coming from: https://github.com/JuliaSparse/SparseArrays.jl/blob/4aab8df5d3f0f19f16de52e92023c2971e60f9f9/src/solvers/cholmod.jl#L183

I suspect we probably need to just merge this PR. @staticfloat?

**Comment by ViralBShah** [comment]
It's picking up `3.0.14` from `julia/stdlib/v1.10/SparseArrays/src/solvers/lib`

**Comment by fxcoudert** [comment]
> I believe to run the wrapper script, one has to run it as part of the PR that also bumps SuiteSparse in Julia

I have no idea how to do that.

**Comment by fxcoudert** [comment]
> I need to look into why this didn't get detected in SparseArrays.jl tests to begin with.

What version(s) of SparseSuite is SparseArrays.jl tested against? If it is tied to that in julia, then that would be why, I suppose.

**Comment by ViralBShah** [comment]
Ok, so here's what is happening:

1. The version of SuiteSparse.jl is decided in Julia master - the files that are updated in this PR. 
2. When we update SparseArrays.jl, it uses the nightly build of Julia master in the CI.
3. But when we update julia master here, it has the old version of SparseArrays.jl

The two need to be tested together, which I'll try to do locally, and then push things. These are remnants of our recent efforts to remove SparseArrays from stdlib, and decouple SparseArrays.jl and SuiteSparse.jl (which didn't fully go through successfully).

**Comment by ViralBShah** [comment]
It looks like the SuiteSparse_jll does not have the header files.

**Comment by ViralBShah** [comment]
Carried forward in #48977

**Pull request closed without merging**
