### PR TITLE
add condition to use emulated fma

### PR DESCRIPTION
**Pull request by oscardssmith**
Testing has revealed that some old windows machines without fma were using broken emulated versions for Float32. This adds a test.

### CODE REVIEW

**Comment by oscardssmith** [comment]
This is kind of a regression from https://github.com/JuliaLang/julia/pull/42783 but only in the sense that we added a test that correctly found out that old machines were already doing the wrong thing.

**Comment by ViralBShah** [comment]
The old machine case we found here was a win64 ivybridge which does not have hardware fma.

**Comment by oscardssmith** [comment]
@JeffBezanson can we please get fma multiversioning so I don't have to figure out why this doesn't work?

**Comment by ViralBShah** [comment]
The CI machines are AMD Epycs. Might that be a different case?

**Comment by oscardssmith** [comment]
If they are Epyc, than they have FMA which would imply that my emulated version is wrong which doesn't make any sense, because then the failures should happen on other platforms.

**Comment by ViralBShah** [comment]
And the tests are passing on epyc with Linux and win32. Is something off with llvm on win64?

**Comment by oscardssmith** [comment]
It really shouldn't be able to do anything for LLVM to mess up. It should just be using the processor instruction...

**Comment by ViralBShah** [comment]
Isn't it possible that if this is running in some kind of a VM, that the VM is not exhibiting a slightly different target processor? I mean we've seen these issues when running in VMs before. Perhaps @staticfloat may know more.

**Comment by oscardssmith** [comment]
Closing as this test can't do anything until we have fma multiversioning.

**Pull request closed without merging**
