### PR TITLE
Enable inference on throw blocks

### PR DESCRIPTION
**Pull request by oscardssmith**
This removes the disabling of inference on error paths. This will need careful evaluation (probably a nanosoldier and package eval)

### CODE REVIEW

**Comment by KristofferC** [comment]
I feel like this is lacking some context. Clearly, the current choice was put there for some reason (reason given in PR that introduced it https://github.com/JuliaLang/julia/pull/35982). So what has changed? What is the argument for spending inference time on code that will throw?

Also, I don't think this change any benchmarks or package tests, it would just infer more than it currently does.

**Comment by aviatesk** [comment]
What's the motivation? This feature is added and enabled intentionally since we figured out this is good for latency.

We should check impacts on latency carefully.

**Comment by oscardssmith** [comment]
@KristofferC a lot of the motivation for this PR is that in between then and now we added the effect system and inferring tighter effects can help latency a bunch since it allows us to run constant folding more often.

**Comment by KristofferC** [comment]
Did you check a TTFP or something?

**Comment by Keno** [comment]
The core issue here is that unoptimizing error paths interacts badly with effects inference, which can cause more latency problems than it solves. We should re-evaluate the trade-off.

**Comment by Keno** [comment]
Just saw another case where this issue is seriously pessimizing effects. Can we do the benchmarking and see where we're at?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47595#issuecomment-1487363879) has completed - successfully executed benchmarks. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/98e7095/report.md).

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by oscardssmith** [comment]
why is `vs=":master"` necessary?

**Comment by KristofferC** [comment]
Otherwise it doesn't run a comparison. It just gives you absolute values.

**Comment by staticfloat** [comment]
I think we should get some larger benchmarks that include some runtime performance as well.  Let's get the compile-time benchmarks of large packages such as `Plots` and `OmniPackage` on this branch.

Let's also get some runtime benchmarks from nanosoldier on the `broadcast` and `random` suites, since we're spending so much time on those inference paths, let's see if we're getting any better runtime for our trouble.

**Comment by Keno** [comment]
We should consider trying a version of it that only deoptimizes the throw blocks if and only if the effects already make it constprop ineligibile, but we should also evaluate the original motivating benchmarks from when this change was introduced. Inference mcirobenchmark time is sort of the wrong benchmark here, because we do expect it to do more work ahead of time, just potentially armotizing it later with better constprop.

**Comment by aviatesk** [comment]
Replaced by #49235.

**Pull request closed without merging**
