### PR TITLE
fix build with JULIA_ENABLE_THREADING==0

### PR DESCRIPTION
**Pull request by JeffBezanson**
#32168 ported to 1.2.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Also needs #32210

**Comment by KristofferC** [comment]
`jl_set_task_tid` doesn't exist on 1.2 I think so how should https://github.com/JuliaLang/julia/pull/32210 be backported?

**Comment by KristofferC** [comment]
This commit is now on https://github.com/JuliaLang/julia/pull/32270.

**Comment by JeffBezanson** [comment]
`sticky == false` doesn't need to be supported on 1.2, so we can probably leave out #32210.

**Pull request closed without merging**
