### PR TITLE
[release 0.4] cache compile dep tracking

### PR DESCRIPTION
**Pull request by vtjnash**
backport #18150

### CODE REVIEW

**Comment by tkelman** [comment]
please use `cherry-pick -x -e` and add the reference to the PR number to the commit messages so everything is cross-referenced.

**Comment by ViralBShah** [comment]
Bump. Can we get this merged?

**Comment by tkelman** [comment]
If @vtjnash doesn't do so, then I'll redo this with cross-references if needed when preparing 0.4.7.

**Comment by ViralBShah** [comment]
It would be nice to get this on the release-0.4 branch soon, so that we can get a nightly and test whether that would fix the issue we have been seeing on juliabox.

Cc @nkottary

**Comment by ViralBShah** [comment]
Classes are starting soon, and we'd like to address this asap before lots of people get onto juliabox.

**Comment by tkelman** [comment]
We only build nightlies from master. I can trigger a custom build from this branch for testing purposes, but it doesn't happen automatically.

**Comment by ViralBShah** [comment]
Good to know, and certainly valuable in this case. Can you trigger a build for this branch? That would help us test, while the PR gets ready for eventual merging and release.

**Comment by tkelman** [comment]
https://build.julialang.org/builders/package_tarball64/builds/812

**Comment by vtjnash** [comment]
travis failure was a build Makefile race condition, unrelated to the PR. @tkelman I assume you'll merge this when you want it for the next nightly / release-0.4 build

**Comment by ViralBShah** [comment]
This seemed to be more stable on juliabox than the current release. @nkottary Can you chime in?

**Comment by nkottary** [comment]
Yes, this build does not emit the precompilation warnings and errors that we were seeing in the release on JuliaBox.

**Comment by tkelman** [comment]
I haven't run pkgeval here yet, but I suspect this will have the same issues we're seeing on release-0.5.

**Comment by ViralBShah** [comment]
This only has part of the PR that is on 0.5. Hence, there is some chance it doesn't have the same issues. Good to know though.

**Pull request merged**
