### PR TITLE
Update dSFMT to 2.2.3

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by ViralBShah** [comment]
The reason I didn't do this earlier because none of the things in the changelog seem relevant - unless you need the visual C++ 2012 fix.

**Comment by tkelman** [comment]
I am hitting a dsfmt-related problem during bootstrap with msvc (ref https://github.com/JuliaLang/julia/pull/10609#issuecomment-85314433) so may need to switch to building it with msvc instead of using the mingw binary from the nightlies. Not positive exactly what's wrong.

The diff does look quite minor, apart from the altivec changes. Not sure about those.

**Comment by ViralBShah** [comment]
Can you just check that the random streams are the same? Just to make sure. Otherwise, we should go ahead with this.

**Comment by tkelman** [comment]
Does `test/random.jl` not verify that? I agree that it would be good to double-check the standard rng test sets on this but have no idea how to run those.

**Comment by ViralBShah** [comment]
I'm just checking `srand(0); rand()` being the same on this branch and on master. Should be, but just being paranoid.

**Comment by ViralBShah** [comment]
Just verified. All good.

**Pull request merged**
