### PR TITLE
add generic fallback for haskey

### PR DESCRIPTION
**Pull request by simeonschaub**
I know this was discussed a while ago, but there was never a PR. I think this is reasonable enough to add.

### CODE REVIEW

**Comment by bkamins** [comment]
As usual such change turns out to break DataFrames.jl tests which assumed this method is not defined 😄. I will fix it in the package.

**Comment by bkamins** [comment]
For a reference - we defined `in` using `haskey`. Not sure if such things also happen in other packages.

**Comment by bkamins** [comment]
Also is this indented:
```
julia> haskey((1,2,3), 1)
true

julia> haskey((1,2,3), 1.0)
true

julia> haskey((a=1,b=2,c=3), 1)
true

julia> haskey((a=1,b=2,c=3), 1.0)
false
```
?

**Comment by nalimilan** [comment]
Is this change really a good idea? What's the rationale? I'm afraid it's going to create some confusion as @bkamins shows.

**Comment by bkamins** [comment]
> when some types

I agree, however, my concern was that these "some types" are fundamental types that are most commonly used in practice.

The alternative would be to make sure that we define proper `haskey` methods for all types defined in Julia Base and make sure they work consistently.

**Comment by aplavin** [comment]
In addition to @bkamins examples, is this also expected?
```
julia> haskey([1, 2, 3], CartesianIndex(2))
false

julia> [1, 2, 3][CartesianIndex(2)]
2
```

**Pull request merged**
