### PR TITLE
don't drop profile / coverage information for statements

### LINKED ISSUE #21541: line number wrong in function after inliner runs
The inliner appears to be mistakenly destroying line number information. For example, in the following snippet, the "#line 607" should say "#line 84" (as it said before inlining):
```julia
julia> @code_typed Base.enq_work(current_task())
CodeInfo(:(begin 
        SSAValue(0) = ((Core.getfield)(t, :state)::Symbol === :runnable)::Bool
        unless SSAValue(0) goto 4
        goto 6
        4: 
        (Base.throw)($(Expr(:new, :(Core.ErrorException), "schedule: Task not runnable")))::Union{}
        6:  # line 83:
        SSAValue(3) = (Core.typeassert)(Base.uv_eventloop, Ptr{Void})::Ptr{Void}
        $(Expr(:foreigncall, :(:uv_stop), Void, svec(Ptr{Void}), SSAValue(3), 0))
        $(Expr(:inbounds, false))
        # meta: location array.jl push! 606
        SSAValue(4) = (Base.bitcast)(UInt64, (Base.check_top_bit)(1)::Int64)
        $(Expr(:foreigncall, :(:jl_array_grow_end), Void, svec(Any, UInt64), :(Base.Workqueue), 0, SSAValue(4), 0)) # line 607:
        # meta: location abstractarray.jl endof 127
        # meta: location abstractarray.jl linearindices 92
        # meta: location abstractarray.jl indices1 64
        # meta: location abstractarray.jl indices 57
        SSAValue(7) = (Base.arraysize)(Base.Workqueue, 1)::Int64
        # meta: pop location
        # meta: pop location
        # meta: pop location
        # meta: pop location
        (Base.arrayset)(Base.Workqueue, t, (Base.select_value)((Base.slt_int)(SSAValue(7), 0)::Bool, 0, SSAValue(7))::Int64)::Array{Task,1}
        # meta: pop location
        $(Expr(:inbounds, :pop)) # line 85:
        SSAValue(2) = :queued
        (Core.setfield!)(t, :state, SSAValue(2))::Symbol # line 86:
        return t
    end))=>Task
```

this is causing us to miss some line coverage: https://coveralls.io/jobs/25117894/source_files/949498628#L84

### PR DESCRIPTION
**Pull request by vtjnash**
fix #21541

### CODE REVIEW

**Comment by yuyichao** [comment]
I believe the correct change is

```diff
diff --git a/base/inference.jl b/base/inference.jl
index cb6275e0ea..a944621d21 100644
--- a/base/inference.jl
+++ b/base/inference.jl
@@ -5075,6 +5075,7 @@ function meta_elim_pass!(code::Array{Any,1}, propagate_inbounds::Bool, do_covera
                 code[push_loc] = nothing
                 code[i] = nothing
             else
+                prev_dbg_stack[end] = 0
                 push_loc_pos_stack[end] = 0
             end
         else
```

which should allow this information to propagate up incrementally. In general, any clearing of `push_loc_pos_stack[end]` should also clear `prev_dbg_stack[end]`, which is what's missing here.

I still don't really see how this affect coverage though. This should only cause a less accurage call stack line number with coverage off but makes no difference with coverage on.

**Comment by yuyichao** [comment]
And the typed AST with this change

```julia
CodeInfo(:(begin
        SSAValue(0) = ((Core.getfield)(t, :state)::Symbol === :runnable)::Bool
        unless SSAValue(0) goto 4
        goto 6
        4:
        (Base.throw)($(Expr(:new, :(Core.ErrorException), "schedule: Task not runnable")))::Union{}
        6:  # line 83:
        SSAValue(3) = (Core.typeassert)(Base.uv_eventloop, Ptr{Void})::Ptr{Void}
        $(Expr(:foreigncall, :(:uv_stop), Void, svec(Ptr{Void}), SSAValue(3), 0)) # line 84:
        $(Expr(:inbounds, false))
        # meta: location array.jl push! 606
        SSAValue(4) = (Base.bitcast)(UInt64, (Base.check_top_bit)(1)::Int64)
        $(Expr(:foreigncall, :(:jl_array_grow_end), Void, svec(Any, UInt64), :(Base.Workqueue), 0, SSAValue(4), 0)) # line 607:
        # meta: location abstractarray.jl endof 127
        # meta: location abstractarray.jl linearindices 92
        # meta: location abstractarray.jl indices1 64
        # meta: location abstractarray.jl indices 57
        SSAValue(7) = (Base.arraysize)(Base.Workqueue, 1)::Int64
        # meta: pop location
        # meta: pop location
        # meta: pop location
        # meta: pop location
        (Base.arrayset)(Base.Workqueue, t, (Base.select_value)((Base.slt_int)(SSAValue(7), 0)::Bool, 0, SSAValue(7))::Int64)::Array{Task,1}
        # meta: pop location
        $(Expr(:inbounds, :pop)) # line 85:
        SSAValue(2) = :queued
        (Core.setfield!)(t, :state, SSAValue(2))::Symbol # line 86:
        return t
    end))=>Task
```

**Comment by vtjnash** [comment]
> I still don't really see how this affect coverage though. This should only cause a less accurage call stack line number with coverage off but makes no difference with coverage on.

That took me a long time too: We don't drop all of the cached code before running coverage (or rebuild a sysimg with coverage enabled), so for functions that got optimized in the sysimg, this information could get lost.

**Comment by yuyichao** [comment]
> so for functions that got optimized in the sysimg, this information could get lost.

That will cause much more lost of information. Are we not running it with `--precompile=no`?

**Review by yuyichao — APPROVED** [review]

**Comment by yuyichao** [comment]
Just to check if the inlining heuristic (and possibly other things) are still insensitive to extra metadata nodes as they should, given that my previous PR fixing these once caused the largest performance regression I've ever seen....

@nanosoldier `runbenchmarks("serialization", vs = ":master")`

**Comment by yuyichao** [comment]
Oh, I guess `precompile=no` is still using the `sys.ji`?

**Comment by JeffBezanson** [comment]
Any effect on sysimg size?

**Comment by vtjnash** [comment]
@JeffBezanson From travis logs, looks like the size is not impacted. @yuyichao yeah, we would also have to go through and drop all of those caches.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21552#issuecomment-297173075) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9f2207b2cedf5415549d853b752caae90a75629a/2a8335d_vs_91625e0/report.md). cc @jrevels

**Comment by JeffBezanson** [comment]
Wait, I'm going to guess you didn't mean to run just the serialization benchmarks.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by yuyichao** [comment]
Ah, right. I guess you can guess what's the first search result from a `mentions:nanosoldier`.....

**Comment by tkelman** [comment]
Should have a test for the issue being fixed.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21552#issuecomment-297184042) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/76565ba0952549f4ae91d9b1fc3d700007dd1113/b220dc9_vs_c181805/report.md). cc @jrevels

**Comment by Sacha0** [comment]
To check the potential array benchmark regressions:
@nanosoldier `runbenchmarks("array", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21552#issuecomment-297214084) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f91cb7535de1d831ee0fe62d5aa343fd3c2bb1a3/112941b_vs_98414b9/report.md). cc @jrevels

**Comment by vtjnash** [comment]
I've improved the existing test to be stricter

**Pull request merged**
