### PR TITLE
change array realloc alignment to 16 bytes?

### PR DESCRIPTION
**Pull request by chethega**
Inline allocated arrays are only16 byte aligned. This means that we can de-facto only guarantee 16 byte alignment. Hence, there is no need for stronger alignment guarantees on realloc.

We call the system realloc when we don't need stronger alignment than supplied by the libc. This is good: In practice, only large arrays are system-allocated (instead of pool-allocated), and these get `mmap`ed and subsequently `mremap`ed (or whatever the analogue syscall the system allocator uses on whatever target kernel). This gives O(1) array growth and shrink operations. 

That should in theory be a speedup on apple and P64. 

Glibc malloc always returns 16-byte aligned pointers. Using this fact, we should be able to get the fast behavior on glibc/linux as well.

There are various alternatives to the way I wrote this here. Ultimately, I fear that we will need a small jungle of `#ifdef` that peeks into the internals of the most popular systems (glibc+linux, windows, macos, bsd). A more complicated alternative would be to bypass the system allocator and talk to the kernel directly, in the special case that we know how to do this. 

Needs: 
1. clarification whether we are happy with only 16 byte alignment
2. Check again in glibc for behavior on 32 bit x86, 32 bit arm, 64 bit arm, and add cross-refs for that.
3. Some better "portable C" person to tell me whether the feature check is correct
4. Someone knowledgeable about the build scripts to make this really work
5. Explore alternative: Optimistically try to realloc and see whether alignment happens to fit.

In theory I am for option 5 in favor of this one (seems more robust). Still, this is an option, especially since there is precedent of the `#if defined(__apple__)` special case, so I'll just put this preliminary PR up as a place for discussion.

Thanks for your comments on slack @NHDaly, @vtjnash 

Cross-ref: [28588](https://github.com/JuliaLang/julia/issues/28588#issuecomment-492699026)

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I also like option (5); once sizes get big enough it should be almost certain to work.

It seems what we need here is to fix the alignment of inline-allocated arrays. Clearly we need 64-byte alignment or we wouldn't have gone to all this trouble, so rolling everything back to 16 doesn't seem viable.

**Comment by vtjnash** [comment]
c.f. wip fix https://github.com/JuliaLang/julia/pull/21959

**Comment by yuyichao** [comment]
> once sizes get big enough it should be almost certain to work.

That is not the case on linux last time I checked. In fact, it is guaranteed to not work for large enough size since glibc seems to be only aligning the header to 16bytes.

**Comment by NHDaly** [comment]
I've opened https://github.com/JuliaLang/julia/pull/32320 to implement option 5 above. So far, on my mac, the results look good. Realloc is able to happily grow my arrays in-place in most of my small silly tests.

Of course, in a real project who knows -- and if it's reallocating with bad alignment, we may end up doing _more_ work overall, not less. So let's keep an eye on it, run some benchmarks, etc. But so far, this seems promising. :)

**Pull request closed without merging**
