### PR TITLE
change libLLVM suffix to match build-configuration

### PR DESCRIPTION
**Pull request by nalimilan**
Backport of 5e0cab69966eb989f380492dda7590bca3a3ba8d.

Fixes https://github.com/JuliaLang/julia/issues/34264.

### CODE REVIEW

**Comment by vchuravy** [comment]
This was due to a misconfiguration between Yggdrasil and base Julia. So we need to release a new LLVM v8 BB. This patch is fine if you just want to carry it locally until I get to that.

**Comment by nalimilan** [comment]
So you mean it's not needed at all in release-1.4?

**Comment by vchuravy** [comment]
> So you mean it's not needed at all in release-1.4?

It is needed in 1.4, but it needs a new release for BB which I am working on at https://github.com/JuliaLang/julia/pull/35300

**Comment by vchuravy** [comment]
Part of  #35313

**Pull request closed without merging**
