### PR TITLE
Move benchmarks out of the repository

### PR DESCRIPTION
**Pull request by ararslan**
These now live in:

* [JuliaArchive/Benchmarks](https://github.com/JuliaArchive/Benchmarks): Julia-specific benchmarks. Most of these are in BaseBenchmarks.jl, which should be updated instead of this. This was formerly the test/perf directory with the micro subdirectory removed.

* [JuliaLang/Microbenchmarks](https://github.com/JuliaLang/Microbenchmarks): Benchmark comparisons across languages. This was formerly the test/perf/micro directory. These can be updated as needed, adding new languages or what have you.

### CODE REVIEW

**Comment by ararslan** [comment]
32-bit Windows failure is a timeout.

**Review by staticfloat — APPROVED** [review]
Looks good to me!

**Comment by PallHaraldsson** [comment]
FYI: https://github.com/JuliaLang/staging.julialang.org/issues/1

I'm not sure if "staging" rep was the correct place, at least now you know here.

**Comment by ararslan** [comment]
https://github.com/JuliaLang/julialang.github.com/pull/757

**Pull request merged**
