### PR TITLE
Use powershell for download function for Windows

### LINKED ISSUE #19526: download function not working on Windows
Hi. I installed julia-0.5 on Windows Server 2008 R2 SP1 via the installer. Once that was finished, I added `WinRPM` and fixed it by removing the malformed URLs from its _deps/build.jl_. Then I installed `curl` via `WinRPM` and added the `WinRPM` directory to Julia's path via _.juliarc.jl_ in my home directory. When I open up Julia and enter the shell, `curl` executes, but when I try to use the `download` function, I get the following error:

```
ERROR: automatic download failed (error: 2148270088): https://cdn.plot.ly/plotly
-latest.min.js
 in download(::String, ::String) at .\interactiveutil.jl:505
 in download(::String) at .\interactiveutil.jl:534
```

Here's my `versioninfo`:
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2687W 0 @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

Edit: I should add that I created a firewall exception for julia, so I don't think that the system firewall is the issue.

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #19526.

### CODE REVIEW

**Comment by oxinabox** [comment]
It it worth this having a fallback to `urlmon` (or even to `ie.exe`) for purposes of making it work on Windows Vista and earlier?

**Comment by JeffBezanson** [comment]
My understanding is that we only support windows 7+.

**Comment by pkofod** [comment]
> My understanding is that we only support windows 7+.

relevant part of windows readme:

https://github.com/JuliaLang/julia/blob/9cdd88789604096999d4b2c1935d18aee4ade895/README.windows.md#binary-distribution

**Comment by JeffBezanson** [comment]
I'll just merge this and we'll see how it goes.

**Comment by davidanthoff** [comment]
I think one potential problem with this might be corporate machines that have powershell disabled via group policy... I also think that Windows Nano Server doesn't ship with Powershell by default. Not sure there are enough users in any of these categories to matter, but this will probably not work everywhere.

**Comment by ihnorton** [comment]
> I think one potential problem with this might be corporate machines that have powershell disabled via group policy

https://stackoverflow.com/questions/49061971/is-it-possible-to-stop-julia-from-using-powershell-on-windows-7

**Comment by phlavenk** [comment]
I'm very positive to have only one download function in base and use it everywhere - but I'd also like a optional hook-in mechanism such that the user might customize it for some corner cases - on clusters, in corporate environment, etc... The custom routine might ask e.g. a linux machine by ssh to download it for you to a shared storage and than copy it from that place to the destination place.

**Comment by nalimilan** [comment]
Julia provides this hook-in mechanism by default: just replace `Base.download`, and all code will use your custom version.

**Pull request merged**
