### PR TITLE
Prefer the parent module when serializing functions (fixes #13452)

### LINKED ISSUE #13452: serialization of Functions chooses the wrong module for scoping
I've got a situation where I have a "base" module (here called `Shell`) that defines a general API, and several "specialized" versions (here called `Instance1` and `Instance2`) which specialize the API for types defined in their respective modules. It seems that functions defined in `Shell` get serialized by scoping with respect to `Instance1` rather than `Shell`. This interacts quite badly with #3674, in which different workers added at different times may not have access to the same modules---in my situation, all processes know about `Shell` but some workers know about `Instance1` while other workers know about `Instance2`.

Demo:
```jl
julia> module Shell

       export foo

       foo(args) = error("Instances must implement foo")

       end
Shell

julia> using Shell

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> serialize(io, foo)

julia> takebuf_string(io)
"\x13\x02#\x02\x05Shell/\x02\x03foo"

julia> module Instance1

       using Shell
       import Shell: foo

       foo(x::Int) = "This is an Int"

       end
Instance1

julia> using Instance1

julia> serialize(io, foo)

julia> takebuf_string(io)
"\x13\x02#\x02\tInstance1/\x02\x03foo"

julia> module Instance2

       using Shell
       import Shell: foo

       foo(x::Float64) = "This is a Float64"

       end
Instance2

julia> using Instance2

julia> serialize(io, foo)

julia> takebuf_string(io)
"\x13\x02#\x02\tInstance1/\x02\x03foo"

julia> serialize(io, Shell.foo)

julia> takebuf_string(io)
"\x13\x02#\x02\tInstance1/\x02\x03foo"
```

Here's [why this happens](https://github.com/JuliaLang/julia/blob/716af6f4d1ddb3864f3efad82452921a186c2dcd/base/serialize.jl#L285) and what we might do about it:
```jl
julia> foo.env.defs.func.code.module
Instance1

julia> for m in methods(foo)
           @show m.func.code.module
       end
m.func.code.module = Instance1
m.func.code.module = Instance2
m.func.code.module = Shell

```
But I'm uncertain how one decides to choose `Shell` among these options; is there some place we can look to decide that `Instance1` and `Instance2` both require `Shell`?

### PR DESCRIPTION
**Pull request by timholy**
I've verified that this works on `0.4.0-rc4`, so @JuliaBackports.

### CODE REVIEW

**Comment by tkelman** [comment]
where does this rank in criticality? must do for final, or could wait for next point release?

**Comment by timholy** [comment]
I'm fine if we wait for point release---people like me can fix locally, there hasn't been a barnstorming of complaints about this, and I'm as excited as anyone to get 0.4 out.

FYI, those lines were last touched in 74b0488adb040388b63c4cb5c210fb1c10abd781 and 015401dad2b3c05c0b0850747f3301b07026cdf8. CC @JeffBezanson.

**Comment by timholy** [comment]
If I wanted to get this into the `release-0.4` queue, what's the proper procedure? Submit a cherry-pick PR against `release-0.4`, or are you staging these on some other branch?

**Comment by tkelman** [comment]
The label is the right procedure. I haven't started staging things for 0.4.1 yet, I consider #13550 release blocking. I will do a staging branch where I run PkgEval on code changes before merging them to release-0.4.

**Comment by timholy** [comment]
Your care in managing these releases is greatly appreciated.

**Comment by tkelman** [comment]
It's been working out pretty well so far 😀

Though I'm a little ashamed I let #13550 slip through without noticing beforehand, but the download numbers for 32 bit linux are the lowest of any of the platforms we regularly build binaries for so at least it isn't hitting too many users.

**Comment by timholy** [comment]
> It's been working out pretty well so far 😀

I'd rate that as an understatement; perhaps it's just that the most vocal people were already running 0.4, but the relative lack of "this broke my code!" reports is quite amazing.

**Pull request merged**
