### PR TITLE
Allow juxtaposition of macro and array literal. fixes #23519

### LINKED ISSUE #23519: Add "Non-Standard Array Literals" by allowing juxtaposition of macro and array
*TLDR*: Please, allow parsing `@foo[1, 2, 3]` as a shortcut for `@foo([1, 2, 3])`.

Too many times, when using StaticArrays, I write stuff like
```julia
@SArray[1 2; 3 4] * v
```
which fails with `ERROR: syntax: invalid macro use "@((typed_vcat SArray (row 1 2) (row 3 4)))"`
I then add a space between `@SArray` and `[1 2; 3 4]` which also fails since the macro tries to consume the whole `[1 2; 3 4] * v` expression.
The right way to do it
```julia
@SArray([1 2; 3 4]) * v
```

It would be nice to be able to this without the parentheses...
Yes, I know, it's not that cumbersome to type two extra characters... but on the other hand, this syntax is available and making it work will hopefully not introduce many accidental bugs.

This could be seen as a kind of "**Non-Standard Array Literals**".
(related: https://github.com/JuliaLang/julia/issues/8934, https://github.com/JuliaLang/julia/issues/7128, https://github.com/JuliaLang/julia/issues/6960, https://github.com/JuliaLang/julia/pull/8892, https://github.com/JuliaLang/julia/issues/7128)

(Had I the knowledge of Julia parser I would open a PR instead of an issue, but I'm a null at scheme.)

### PR DESCRIPTION
**Pull request by cdsousa**
This is an attempt to implement what I have suggested in #23519:
interpret `@foo[1, 2, 3]` as `@foo([1, 2, 3])`.

I have almost (now) zero knowledge of scheme, so pardon me if the implementation is too wrong.
It seems to work ok in many situations, ~~but it doesn't have any test yet~~.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Implementation looks fine to me.

**Comment by ararslan** [comment]
What you've noted in the docs, that `@m[x] * v` is not the same as `@m [x] * v` implies to me that this will introduce another subtle "gotcha" for macro invocations. The fact that omitting a space changes the meaning in a subtle way is concerning. Is it really so onerous to use `@m([x])`?

**Comment by KristofferC** [comment]
Does anyone write `@m[x] * v`?

**Comment by cdsousa** [comment]
Yes, unfortunately, it adds yet another gotcha, along with `@m(1,2)` vs. `@m (1,2)`, but it is somehow of the same type and thus hopefully easier to remember...

From my experience, my brain defaults to already interpret `@m[x] * v` as applying only to `[x]` although it has never been the case. That was the reason which triggers me to open the issue in the first place.

This desire for a lightweight syntax for "non-standard array literals" comes mainly from static arrays, where, possibly unlike to other custom arrays, it is very common to need small literal arrays with constructors as performant as possible. Indeed StaticArrays is all about the performance of small matrices where stuff like construction, indexing, etc. (and their optimization/inlining) tends to be as much important as matrix algebra and iteration. Also, array literals (excluding concatenations and comprehension) are used almost always for small matrices!

Many discussions have been taken about a more lightweight syntax for custom array literals (notice that array elements don't have to be literal numbers). I referred some in #23519, and another important one happens https://github.com/JuliaArrays/StaticArrays.jl/issues/24 .

The syntax change I'm proposing is a very low-hanging fruit for "something reasonabe".
Having it will readily allow StaticArrays users to simply prefix arrays/vectors/matrices literals with `@SArray` (or something like `@SA`) and instantly get small static arrays with types and sizes resolved at compile time solely from the literal. 
Maybe, StaticArrays developers, @andyferris, @SimonDanisch, and others (I merely a user), can also have something to say here.

**Comment by cdsousa** [comment]
Rebased.

**Comment by cdsousa** [comment]
Some people have shown dislike and some people have shown sympathy for this change, both here and in the issue (#23519). How usually are these cases resolved? I think that it is better to either merge or reject the PR, right?

**Comment by andyferris** [comment]
It can sometimes be a slow process, @cdsousa.

If you want resolution, I'll add some labels which means it will be picked up by what's being called the "triage" process.

**Comment by martinholters** [comment]
@ararslan The fact that 

> `@m[x] * v` is not the same as `@m [x] * v`

doesn't seem worse than the fact that  `@m([x]) * v` is not the same as `@m ([x]) * v` to me.

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Needs news, then I will merge this.

**Pull request merged**
