### PR TITLE
performance fix: String join

### PR DESCRIPTION
**Pull request by vtjnash**
The code generated here for Stateful is (necessarily) quite slow (and expensive to compile)
and not really even any shorter or simpler to write. For reference, the expected performance report on @nanosoldier `runbenchmarks("string", vs = ":master")` is 20-40% (and afaict, is also going to be slightly faster than v0.6, but possibly below the noise threshold for reporting it):

```
julia> x = ("a", 2); @btime sprint(join, $x, "")
  1.301 μs (15 allocations: 560 bytes)
"a2"

julia> x = ("a", 2); @btime sprint(join2, $x, "")
  484.754 ns (8 allocations: 336 bytes)
"a2"

julia> x = ("a", "2"); @btime sprint(join, $x, "")
  1.396 μs (13 allocations: 464 bytes)
"a2"

julia> x = ("a", "2"); @btime sprint(join2, $x, "")
  364.522 ns (6 allocations: 240 bytes)
"a2"
```

### CODE REVIEW

**Comment by vtjnash** [comment]
> is 20-40% 

Actually, I'm not certain what that benchmark contains. If `x::Vector{String}`, then the improvement is only expected to be 75% (below reporting threshold of 60%). While if it's `x::Vector{Any}`, the improvement is expected to be 15%! (all relative to master, vs. 0.6 all of these seem pretty consistent to be about 75%, but that might be unrelated measurement error since there's so many other changes).

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27974) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6210049591eccd7ddf909e7dc5d73a6667a90625/e788ee0_vs_a60119b/report.md). cc @ararslan

**Comment by vtjnash** [comment]
@nanosoldier runbenchmarks("problem", vs = ":master")

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("problem", vs = ":master"),`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("problem", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27974#issuecomment-403191497) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f864bf224fc7105dd025ca8e582ae6cf3b0fdca3/825cb51_vs_6014e7d/report.md). cc @ararslan

**Pull request merged**
