### PR TITLE
Fix wrong use of `isdefined` #21492

### PR DESCRIPTION
**Pull request by vchuravy**
This is the immediate fix from #21537.

### CODE REVIEW

**Comment by tkelman** [comment]
any quick and/or simple within-base way of testing this

**Comment by vchuravy** [comment]
I have been thinking about it, but nothing that is simple and wouldn't poison the test worker.

**Comment by amitmurthy** [comment]
You can have a test that runs outside of the main workers set. See how boundscheck_exec.jl and distributed_exec.jl are run.

**Comment by vchuravy** [comment]
thanks that pointed me into the right direction.

**Comment by fredrikekre** [comment]
(this fixes the problems I had in https://github.com/JuliaLang/julia/pull/21492#issuecomment-296676743, thanks!)

**Comment by vchuravy** [comment]
@tkelman Is the test sufficient? My only worry is that it will stop testing what it needs to test if `Base.Iterators` changes.

**Comment by tkelman** [comment]
better than no test!

(should be 4 space indent though)

**Comment by vchuravy** [comment]
Done :) one might think that by now I just would have fixed my editor.

**Comment by vchuravy** [comment]
@vtjnash Good to merge?

**Comment by tkelman** [comment]
Is the `WARNING: replacing module Test6c92f26` expected here? If so, should it use `@test_warn` to suppress and check for that?

**Comment by vchuravy** [comment]
The warning is expected, but I don't know how to suppress it, since it is
coming from a different process.

**Comment by tkelman** [comment]
set its stdout and/or stderr?

**Pull request merged**
