### PR TITLE
Convert filterArgs.sh to POSIX shell

### PR DESCRIPTION
**Pull request by mirabilos**
requested by qlal1 in the #!/bin/mksh channel on Freenode IRC

### CODE REVIEW

**Comment by tkelman** [comment]
wow, you folks are fast

**Comment by albap** [comment]
What's this "AppVeyor build failed"? Should we worry about it or can the patch me merged?

**Comment by tkelman** [comment]
#16555 - not related. This script only gets called by `contrib/repackage_system_suitesparse4.make` which isn't relevant on Windows anyway.

**Comment by albap** [comment]
Nice, awaiting the merge.

**Comment by albap** [comment]
In the meantime, I proposed a POSIX-compliant implementation of relative_path.sh here https://github.com/JuliaLang/julia/pull/16838

I'm not sure if you're okay with StackOverflow (CC-BY-SA) code being added.
Or that it's even going to work, I'm waiting for the Travis CI results.

As a last resort, we can convince @mirabilos to have a look at this little challenge ;)
absolute_path -> relative_path

**Comment by tkelman** [comment]
Thanks for the contribution!

**Pull request merged**
