### PR TITLE
Reorganize spones to match other sparse functions, add spfill, spfillnz

### LINKED ISSUE #22381: spones documentation is incorrect
The documentation for the spones function describes the Matlab behavior for this function, which replaces each non-zero entry by a value of 1.0. However, the implementation appears to use julia's notion of "stored entries" instead. 

~~~~
julia> versioninfo()
Julia Version 0.6.0-rc3.0
Commit ad290e9 (2017-06-07 11:53 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

help?> spones
search: spones unsafe_pointer_to_objref

  spones(S)

  Create a sparse array with the same structure as that of S, but with every nonzero element having the value 1.0.

  julia> A = sparse([1,2,3,4],[2,4,3,1],[5.,4.,3.,2.])
  4×4 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
    [4, 1]  =  2.0
    [1, 2]  =  5.0
    [3, 3]  =  3.0
    [2, 4]  =  4.0
  
  julia> spones(A)
  4×4 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
    [4, 1]  =  1.0
    [1, 2]  =  1.0
    [3, 3]  =  1.0
    [2, 4]  =  1.0

  Note the difference from speye.

julia> A = sparse([1,2],[1,2],[true,false])
2×2 SparseMatrixCSC{Bool,Int64} with 2 stored entries:
  [1, 1]  =  true
  [2, 2]  =  false

julia> B = spones(A)
2×2 SparseMatrixCSC{Bool,Int64} with 2 stored entries:
  [1, 1]  =  true
  [2, 2]  =  true

julia> A = sparse([1,2],[1,2],[1.0,0.0])
2×2 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  0.0

julia> C = spones(A)
2×2 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  1.0
~~~~

Expected behavior given the documentation

~~~~
julia> B = spones(A)
2×2 SparseMatrixCSC{Float64,Int64} with 1 stored entries:
  [1, 1]  =  1.0

julia> C = spones(A)
2×2 SparseMatrixCSC{Float64,Int64} with 1 stored entries:
  [1, 1]  =  1.0
~~~~

So note that there are two issues with the current documentation. First, the value is one(T) not 1.0. Second, the operation proceeds over the stored entries, not the non-zero stored entries.

Ideal handling.

* Change the operation of `spones` to do the same thing as Matlab's function. In which case, this would operate according to the documentation. (That is, it would satisfy the relationship `countnz(spones(A)) == countnz(A)`)
* Introduce a new function for the current behavior. `spsones` ? 

Minimal handling.

* Adjust the documentation for the current function. Would suggest including an example describing the difference from Matlab's behavior (as above). 

I don't like the minimal handling because the semantics of Matlab's `spones` and Julia's `spones` are radically different in unexpected and bug-inducing fashions because I have no idea which Julia operations introduce new structural non-zeros. (Let's just say I spent a while working with the wrong distribution of random matrices.)

### PR DESCRIPTION
**Pull request by dgleich**
Fixes #22381

The `spones` function is inconsistently named with the rest of the sparse
functions.

`zeros -> spzeros`
`eye -> speye`
`diagm -> spdiagm`
`rand -> sprand`

`ones` -> ????

Instead, the `spones` function replaced all the structural entries with ones. This, I suppose, was done to mirror the matlab function `spones` 

This pull request has two main changes:

1. changes `spones` to the equivalent of `sparse(ones(...)))`
2. introduces `spfill` and `spfillnz` to replace the previous functionality

The new `spfill` function fills the structural entries of a matrix with a given value. The `spfill!` function fills this in-place. Also,  the `spfill` function can change the value type of the matrix itself.

The new `spfillnz` function operates the fill only over the non-zero values, which are determined by testing `abs(A[i,j]) > tol`, for a user-specified  value `tol` that defaults to 0. There is also an in-place version  `spfillnz!`.

### CODE REVIEW

**Comment by bramtayl** [comment]
spones looks to me like a misspelling of spoons. Seems possible to handle sp* this with dispatch? Passing SparseArray as the first argument?

**Comment by tkelman** [comment]
We have `fillslots!` though I don't think it's exported. What your version of `spones` does isn't super useful, and it would need to go through a deprecation. Sending the array type (instead of the element type) as the first argument to ones etc would be more general.

**Comment by fredrikekre** [comment]
I agree with `@tkelman` that the new `spones` is not very useful, and kinda defeats the purpose of using sparse arrays in the first place. It is also just as easy using `sparse(ones(...))` for this, presumably rare, use case.

**Comment by Sacha0** [comment]
Closely related discussion: #17670. Best!

**Comment by martinholters** [comment]
I don't think the `spones` functionality proposed here is useful. OTOH, `spfill[!]` and `spfillnz[!]` may both make sense in different contexts. However, they don't have to be limited to `SparseMatrixCSC`/`SparseVector` - think e.g. `Diagonal` and friends. In fact, `spfillnz[!]` could be useful for any `AbstractArray`. So I guess we should rethink those names. How about `fillnz[!]` instead of `spfillnz[!]`? Not sure what to do about `spfill[!]` - stay with `fillslots!`?

But yes, once this is settled, let's deprecate `spones` in favor of whatever we decide as the new name.

**Comment by dgleich** [comment]
**Summary.**

I'll submit a revision of this with spones removed, fillnz[!] working for
Arrays, SpecialMatrices, and SparseMatrices, and 
countnz revised to have a tolerance. The current spfill! will become
fillslots! for the same types. See also the discussion below about
"nonzeros" in terms of sparse matrices. 

**Notes.**

There are a few things mixed in here.

Re: spones vs. sparse(ones)...

I understand the high-level objection to having spones allocate an 
array of all ones for the matrix case; and agree that it's unlikely.
There are a number of scenarios where spones comes in handy for the
sparsevector. (e.g. I expect `y = A*ones` to be sparse.) For instance

    n = 100; A = sprand(n,n,0.5/n); y = A*sparse(ones(n)); z = A*y

Just food for thought. The argument is then, if it's there for sparsevector,
why not sparsematrix too :) ?. It's easy enough to put back the code
if anyone agrees with this line or argument -- but it sounds like there
isn't much support. 

Re: spfillnz[!]

I agree that a better strategy would be to implement

fillnz[!] for

Array, SparseMatrixCSC, SparseVector, SpecialArrays (linalg/bidiag.jl).
Two questions: 
* Are there others where this makes sense?
* Is everyone happy with the nz tolerance? If so, the countnz function
should also probably be extended to this case too? 

Re: fillslots! vs. fill

It looks like there is a long debate on this already. I don't like the
idea of these functions in general as it surfaces what should be a irrelevant
implementation detail. The only thing I'll
say is that "sel" -- stored entry location might be another thing to 
consider for the name. e.g `fillsels!` at least points out that you
might want to understand what a "sel" is before using it. This is reasonably
consistent with the sparse matrix terminology used in the documentation. 

Re: nonzeros for sparse matrices aren't

One final issue is that all of the terminology on the SparseMatrixCSC
side is in terms of nonzeros.

    nonzeros(A), A.nzval, nnz(A), nzrange(A,i), ...
    
which is problematic as these are not "non-zeros". They may be zero!
"sels" or "slots" give another possible interface here. 

    nsels(A) nslots(A) 
    
But that seems like another issue. (Is there already a discussion of this?)

**Comment by StefanKarpinski** [comment]
The entire `sp*` family of functions is a bit suspect in that it is a parallel universe of functions which line up with other functions differing only by a mechanical name transformation. It would be beneficial to consider how to express this sort of thing more generically.

**Comment by dgleich** [comment]
Still working on some of those changes mentioned above due to time restrictions based on travel. 

Regarding the parallel universe of "sp*" functions. There are a number of structural matrix types that are somewhat similar to "sp*" -- 

~~~
SparseMatrixCSC
SparseVector
Bidiagonal
Diagonal
Tridiagonal
SymTridiagonal
AbstractTriangular
Banded (BandedMatrices.jl) 
~~~

In theory, all of the functions
~~~
ones
zeros
diagm
eye
rand[n]
~~~
would apply to any of these types (there are some slight differences in rand[n] for SparseMatrix types)

e.g you can see the functions in BandedMatrices.jl

~~~
  bzeros(m,n,l,u)    # creates a banded matrix of zeros, with l sub-diagonals and u super-diagonals
  brand(m,n,l,u)     # creates a random banded matrix, with l sub-diagonals and u super-diagonals
  bones(m,n,l,u)     # creates a banded matrix of ones, with l sub-diagonals and u super-diagonals
  beye(n,l,u)        # creates a banded  n x n identity matrix, with l sub-diagonals and u super-diagonals
~~~

I suspect one of the issues with having a generic interface is that each type has slightly different parameters that determine some of the structural properties. 

Since it seems these types are all Matrices (except for SparseVector), it might make sense to write a function that would unify some of these 
~~~
spzeros(5,6) 
could be 
matrix(SparseMatrixCSC, 0.0) 
~~~

**Comment by StefanKarpinski** [comment]
> each type has slightly different parameters that determine some of the structural properties.

One of the common patterns for dealing with this is capturing these parameters in its own type and then having a standard argument there such a generic parameter object gets passed. Not sure how that pans out here, but it's an approach.

**Comment by ViralBShah** [comment]
As I mentioned elsewhere, I think we should find a way to do away with the `sp` prefixes. The obvious suggestion is to have the usual constructors take a type argument.

**Comment by ViralBShah** [comment]
I think we won't be able to do anything here for now - until we start versioning stdlib or get into 2.0.

**Pull request closed without merging**
