### PR TITLE
add git url printing to methodshow

### LINKED ISSUE #44151: add `Base.url(::Method)` result to `show(io, ::Method)`
I'd like to know if people support this.

now:
```julia
julia> @which sum(1:3)
sum(r::AbstractRange{<:Real}) in Base at range.jl:1312
```

proposed:
```julia
julia> @which sum(1:3)
# https://github.com/JuliaLang/julia/tree/bf534986350a991e4a1b29126de0342ffd76205e/base/range.jl#L1312
sum(r::AbstractRange{<:Real}) in Base at range.jl:1312
```
many terminals have the ability to "open URL in browser". Besides, assuming you're sharing the result to other people, it's nice to have a perm github url than trying to go to the file and look around the line number.

### PR DESCRIPTION
**Pull request by Moelf**
closes https://github.com/JuliaLang/julia/issues/44151

```julia
julia> @which sum(1:3)
# https://github.com/JuliaLang/julia/tree/5e7b6dd090791ca545897d9625a82cae34c116b1/base/range.jl#L1387
sum(r::AbstractRange{<:Real}) in Base at range.jl:1387

julia> @which typeof(3)
typeof(...) in Core
```

### CODE REVIEW

**Comment by Moelf** [comment]
closes https://github.com/JuliaLang/julia/issues/44151

**Comment by fredrikekre** [comment]
This is of pretty limited use since it will only work for methods in Base. Currently the URL is wrong for stdlib code, and for methods in packages it just repeasts the file location twice.

**Comment by Moelf** [comment]
Do we want scrap it then? I thought it works with general registry package too

**Comment by Moelf** [comment]
https://github.com/adrhill/BrowserMacros.jl

**Pull request closed without merging**
