### PR TITLE
Revert "Bump dependencies to fix ppc64le page size issues"

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Reverts JuliaLang/julia#34082. Since it seems to be causing download hash failures.

### CODE REVIEW

**Comment by giordano** [comment]
I think reverting only the change to `SUITESPARSE_BB_URL_BASE` in [`deps/suitesparse.mk`](https://github.com/JuliaLang/julia/commit/cfb6e79146c963286115cb76781aaa525f7c99fc#diff-a631d2e400d40fcebd84976af4c2ff91) might be sufficient.  I was also almost about to delete the tag referenced by that change, as it's wrong.

**Comment by giordano** [comment]
Ok, I think something went very wrong with the registration of a new tag in SparseSuite.

**Comment by StefanKarpinski** [comment]
I'd rather revert this whole thing and get back to working CI; someone can unrevert it along with the rest of the fix once it's ready. In the meantime, this is causing all CI runs to fail.

**Comment by giordano** [comment]
> I'd rather revert this whole thing and get back to working CI

Yes, that's probably safer now.

**Comment by vchuravy** [comment]
Reverted it for now, good way of finding a race condition in the system...

**Pull request merged**
