### PR TITLE
[RFC] Add Input function.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Continues #9851

### CODE REVIEW

**Comment by tkelman** [comment]
Why 2 n's on the `inn` keyword argument?

**Comment by ivarne** [comment]
Probably because he copied my suggestion in the previous issue. It's definitely wrong so it has to be fixed.

This also needs a rebase (squash),  because we don't want  to have too many commits with broken tests in the history.  (`git bisect` is much harder to use when tests fail).

More importantly we need some comments on the utility if this new function, whether it belongs in Base, and if the implementation is correct.

**Comment by Ismael-VC** [comment]
@ivarne & @tkelman I actually thought `inn` was to avoid using `in`, I'll fix that and learn how to rebase it. I'm studying Python's [`raw_input`][1] source code, and they seem to check for a lot of stuff, but I don't know if this is relevant, since I'm already using high level Julia functions.

[1]: https://github.com/python/cpython/blob/2.7/Python/bltinmodule.c#L2020

**Comment by ivarne** [comment]
That might be a good reason, but I think `in` should work, and if it causes parsing issues I we should use `io_in` and `io_out` (or something similar) instead. `inn` was because I'm Norwegian and we write "inn" so I did not catch my typo.

**Comment by Ismael-VC** [comment]
@ivarne like that? I fixed the typo misunderstanding and then I did:

```zsh
git reset --soft HEAD~10 && git commit && git push --mirror
```

**Comment by StefanKarpinski** [comment]
> `inn` was because I'm Norwegian and we write "inn" so I did not catch my typo.

Oh, you crazy Norwegians! Reminds me, it's been *way* too long since I've celebrated syttende mai :-)

**Comment by ivarne** [comment]
@Ismael-VC looks good.

@StefanKarpinski You're most welcome, if you want to do that again. It's every year at May 17.

**Comment by StefanKarpinski** [comment]
Is that what that means?

**Comment by ivarne** [comment]
Yes, just as "fourth of July" is more than just a date in the US.

**Comment by Ismael-VC** [comment]
This is similar to what Matlab does except that it's the other way around:

```julia
function input(prompt::AbstractString = ""; evaluate::Bool = false,
               io_in::IO = STDIN, io_out::IO = STDOUT)
    print(io_out, prompt)
    _input = chomp(readline(io_in))
    if evaluate
        return eval(parse(_input))
    else
        return _input
    end
end
```

* `input(prompt)` is equivalent to Matlab's `input(prompt, "s")` which returns a string literal.
* `input(prompt, evaluate = true)` es equivalent to Matlab's `input(prompt)` which evaluates input.

```julia
julia> input("Test: ")
Test: x = 3 + 3
"x = 3 + 3"

julia> x
ERROR: UndefVarError: x not defined

julia> input("Test: ", evaluate = true)
Test: x = 3 + 3
6

julia> x
6
```

**Comment by ivarne** [comment]
I don't think it is worth complicating the interface for `input` to write 15 characters (`, evaluate=true`) instead of 13 characters (`eval(parse(...))`). We would also need an additional parameter to be able to supply a module scope for eval, and there might also be security considerations when using `eval` that a developer should be aware of (that I think is better communicated by calling the `eval` function directly).

**Comment by Ismael-VC** [comment]
@ivarne I know about the security considerations of evaluating unsanitized input and I also think using explicitly `eval(parse(...))` is better (even more since Julia only evaluates at the global scope and Python can do it in any namespace), I'm just considering all the options (since there are many) so others can give me feedback about it, this is how `input` is done in this languages:

* [Python3][1], [PEP 3111][6]
*  [R][2]
* [Matlab][3]
* [Octave][4]
* [Mathematica][5]

Basically this avoids redundancy when prompting users for input:

```julia
x = prompt('Input something: ')
```

Rather than this pattern:

```julia
print('Enter something')
x = chomp(readline())
```

Which becomes cumbersome and error prone if you need to ask for lots of inputs.

[1]: https://docs.python.org/3.4/library/functions.html#input
[2]: http://www.rexamples.com/4/Reading%20user%20input
[3]: http://www.mathworks.com/help/matlab/ref/input.html
[4]: https://www.gnu.org/software/octave/doc/interpreter/Terminal-Input.html
[5]: http://reference.wolfram.com/language/ref/Input.html
[6]: https://www.python.org/dev/peps/pep-3111/

**Comment by Ismael-VC** [comment]
I just rebased the pull request.

**Comment by StefanKarpinski** [comment]
It's a much bigger bit of work, but I think this should automatically hook into the REPL machinery when it's available and only fall back on reading directly from STDIN when that's not available. Actually, is REPL and smart Terminal support ever not available these days?

**Comment by Ismael-VC** [comment]
@StefanKarpinski could you please elaborate a little bit about what would have to be done?

 I'll dig into the REPL source code and see if I can understand it. I don't get why it has to be hooked to the REPL, doesn't it use `STDOUT` & `STIDIN`?

Do you mean that at the REPL it should use the REPL mechanism and when run from a file it should fall back to `STDIN`?

**Comment by StefanKarpinski** [comment]
Oh man, if I knew what all had to be done, I probably would have done it already. Basically, use the stuff that's in REPL.jl and Terminal.jl to prompt for input with line editing support. Not very helpful, I'm afraid :-\

**Comment by Ismael-VC** [comment]
> Basically, use the stuff that's in REPL.jl and Terminal.jl to prompt for input with line editing support.

Believe me that's better than nothing. Thanks!

**Comment by ivarne** [comment]
So the main point is that backspace should work in the input field (and a minor point is all the other shortcuts to skip words and so on should work too).

**Comment by ivarne** [comment]
Another thing that would be great for a `input` function to support is iJulia (and possible other GUIs).

But the real question now, is whether this is a good start for the `input` function we want in Julia, and if the API is right and gives proper opportunity for anyone to add functionality without breaking current code.

**Pull request closed without merging**
