### PR TITLE
Max the cutoff for splat penalty much higher

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
One proposal for https://github.com/JuliaLang/julia/issues/22370. I took @vtjnash 's changes, put a nice simple number on them, and also upped the splatting length. Not entirely sure how to argue specifics here.

### CODE REVIEW

**Comment by andyferris** [comment]
Very cool.

**Comment by andyferris** [comment]
OSX build timed out...

**Comment by musm** [comment]
Run nanosoldier here?

**Comment by andyferris** [comment]
Let's see if I can do this...

@nanosoldier `runbenchmarks(ALL, vs = "master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22545#issuecomment-318912784) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/358a42a897875b653f3b37923629d7e431be941c/905ba1d_vs_1ce3c8e/report.md). cc @ararslan

**Comment by Jutho** [comment]
Is this still on the table for julia 1.0. Maybe it's worth trying to more gradually increase each of the three parameters individually in order to investigate their effect on the benchmarks?

**Comment by vtjnash** [comment]
doesn't apply anymore (these constants are gone)

**Pull request closed without merging**
