### PR TITLE
Remove sign checks in VersionNumber constructor

### PR DESCRIPTION
**Pull request by musm**
ref https://github.com/JuliaLang/julia/pull/23048#discussion_r130524083

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I kind of left those in there on purpose so that if you change `VInt` to a signed type the code is still correct. Of course, we're probably not going to do that, so I guess this is ok.

**Comment by musm** [comment]
Maybe then I should remove the `const VInt = UInt32` so that it is not a problem if someone changes it?

**Comment by StefanKarpinski** [comment]
Eh, no, I guess we can just merge this PR. It might be good to have the sign checks on this method instead:

https://github.com/musm/julia/blob/397099994b68a5831a6d2444fe055d102133157a/base/version.jl#L32-L37

Although I suppose the `InexactError` is probably good enough.

**Comment by StefanKarpinski** [comment]
Did you not want to do this anymore?

**Comment by musm** [comment]
Yeah, if someone really wants to make this change feel free.

**Pull request closed without merging**
