### PR TITLE
Add coverage in more places for unicode/*.jl

### PR DESCRIPTION
**Pull request by ScottPJones**
Added test for uncovered line in utf32.jl
Changed Uint to UInt in types.jl
Removed a duplicate convert method in utf16.jl
Add test to cover converting a long utf8 sequence in utf8.jl
Changed a method in checkstring.jl for better coverage
Added more tests for checkstring.jl, test accept_long_char option

### CODE REVIEW

**Comment by ScottPJones** [comment]
Tests have passed, could I beg you to merge my coverage improvements @kshyatt?

**Comment by KristofferC** [comment]
This is not important at all but just a thought. Maybe it is best to avoid commit messages like "Test for *last uncovered line* in utf32.jl" and "Add tests for *complete coverage* of checkstring," because it could be argued that these type of messages are talking about things which are "out of scope" for what the PR actually does.

For example, if someone merged some new functions into these files before this is merged then the commit messages would suddenly be false.

**Comment by ScottPJones** [comment]
Reasonable point, I'll take that into account next PR.

**Comment by ScottPJones** [comment]
(or if somebody does change any of these, I'll rebase with a reword)

**Pull request merged**
