### PR TITLE
remove length from Stateful

### LINKED ISSUE #47790: Reported length of zip of stateful iterators wrong
A common idiom in the Python world to partition an iterator into chunks of length N is to turn it into a stateful iterator, then zip it with itself N times.

However, such a Zip iterator in Julia falsely report to have the same length as the original iterator.

Perhaps the takeaway is that stateful iterators cannot be HasLength or HasShape, as it's unknowable if another reference to the iterator iterates it.

### PR DESCRIPTION
**Pull request by vtjnash**
Stateful iterators do not have a consistent notion of length, as it is continuously changing as elements are removed. As the main purpose of Stateful is to take elements from multiple places, any notion of HaveShape is invalid for those cases, and thus not useful in general.

Fix #47790
~Blocked on #51869~

### CODE REVIEW

**Comment by jakobnissen** [comment]
This will not be backported to 1.10, it's too late for that kind of changes.
This is a breaking change, but the only alternative I can see is incorrect behaviour, and while breaking changes are very bad, silently getting incorrect answers is worse.

I can't help but feel that the fix here is a bandaid over a larger problem, namely that Julia does not have any functionality to distinguish mutable from immutable iterators, and as a result of that, consistently conflate them even in Base. However, this is a rather fundamental problem, and as such, is unlikely to be fixed. So solutions like the ones here may be the best approach.

**Comment by KristofferC** [comment]
@PallHaraldsson You keep commenting in various PRs (that have semi-breaking or invasive changes) about backporting them to 1.10 and every time it has to be pointed out that 1.10 is not in that stage. At this point, I would maybe stop worrying so much about 1.10 and just assume that the backports will be handled in an ok way.

**Comment by PallHaraldsson** [comment]
Should we at least add a "breaking" label? I think we should take breaking changes seriously, why I bring this up more than 1.10.

**Comment by oscardssmith** [comment]
triage says this is a (slightly breaking) bugfix.

**Comment by oscardssmith** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/51747#issuecomment-1781823816) failed. Consult the server logs for more details (cc @maleadt).

**Comment by tecosaur** [comment]
Mea culpa, thanks for the PR to fix my usage of this Jameson.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("strings" || "string", vs=":master")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/51747#issuecomment-1788970774) failed.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("strings" || "string", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51747#issuecomment-1915954138) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/118de7f_vs_fbd14a2/report.md).

**Comment by rafaqz** [comment]
Turns out this is kinda breaking

**Comment by jakobnissen** [comment]
That's right. However, status quo (before this PR) have wrong answers in several cases. I would argue that breaking code is better than having it silently be wrong.
Ideally, the correctness bugs would be fixed, but it's proven to be difficult to do.

**Comment by rafaqz** [comment]
The problem is where `Stateful` was used internally im controlled conditions.

In DiskArrays.jl we will have to make our own identical `DiskArrays.Stateful` with `length` defined.

**Comment by vtjnash** [comment]
Yeah, I can see that use, but it is only fine because you are relying on it being a monotonic counter to see if the iterator has advanced, and not actually using it as a `length`. It seems like that code might be more correct with a call to `peek()` there instead, as a drop in replacement? (or perhaps needs all of `s.nextvalstate`)
https://github.com/meggart/DiskArrays.jl/blob/9fc52e23a1f3e46267f9377d45dbd832e8c83750/src/iterator.jl#L45-L52

**Comment by vtjnash** [comment]
All cases so far of `length` in action have been to test if the `length` is zero, which is better written as `isempty` anyways (since `length` may be expensive or incorrect to compute). I have made PRs to fix the ones that I know about.

**Pull request merged**
