### PR TITLE
Remove openblas set_num_threads in julia __init__

### PR DESCRIPTION
**Pull request by ViralBShah**
We used to set the number of threads to a conservative number, since openblas thread detection used to be less reliable than it is today. Hopefully this leads to better out of the box performance, since it is quite common for people to have more than 8 cores!

cc @chriselrod @staticfloat

### CODE REVIEW

**Comment by ViralBShah** [comment]
This needs to be followed up with increasing of the max num threads as discussed in this PR, so that users can start getting good linear algebra performance out of the box. 

https://github.com/JuliaPackaging/Yggdrasil/pull/3667

**Comment by ViralBShah** [comment]
Getting 2x `peakflops()` already with just this PR.

**Review by staticfloat — APPROVED** [review]

**Review by chriselrod — APPROVED** [review]

**Comment by DilumAluthge** [comment]
The Buildkite `tester_linux64_st` job ("st" = "single-threaded") keeps failing, even when I retry it.

Are the failures related to the contents of this PR?

**Comment by JeffBezanson** [comment]
:+1: Do we want to do anything if the number of threads is specified, e.g. `-t 4`, or just leave openblas separate from our thread selection?

**Comment by oscardssmith** [comment]
I think we should leave it separate unless and until we can integrate OpenBlas threads with Julia threads.

**Comment by ViralBShah** [comment]
What's the issue with the single thread failure?

**Comment by DilumAluthge** [comment]
I don't know, but I've retried it three times now, and it fails every time.

The same job (`tester_linux64_st`) is passing on master, so I think the failures might be due to this PR.

**Comment by DilumAluthge** [comment]
It looks like the failure is happening in the Distributed test set. @vchuravy could you take a look?

**Comment by DilumAluthge** [comment]
```


Distributed                         (1) \|        started at 2021-10-01T16:22:31.825
--
  | Test Failed at /cache/build/amdci7-3/julialang/julia-master/julia-710a3ca24d/share/julia/stdlib/v1.8/Distributed/test/distributed_exec.jl:1034
  | Expression: master_blas_thread_count <= 8
  | Evaluated: 32 <= 8
  | ERROR: LoadError: There was an error during testing
  | in expression starting at /cache/build/amdci7-3/julialang/julia-master/julia-710a3ca24d/share/julia/stdlib/v1.8/Distributed/test/distributed_exec.jl:1068
  | Distributed                         (1) \|         failed at 2021-10-01T16:23:27.146


```

**Comment by vchuravy** [comment]
Yeah @ViralBShah that test in Distributed.jl needs to be adjusted.

**Comment by DilumAluthge** [comment]
What would be the most correct way to fix the test?

**Comment by ViralBShah** [comment]
Note impact on startup times discussed in https://github.com/JuliaPackaging/Yggdrasil/pull/3667#issuecomment-932620369

This will remove the cap of 8 threads, and thus add something like 50ms more when using 32 threads (if the hardware does have that many cores).

**Comment by DilumAluthge** [comment]
For Buildkite CI, we probably still want to limit the OpenBLAS thread count to avoid each Buildkite job from starting e.g. 64 OpenBLAS threads.

https://github.com/JuliaLang/julia/pull/42470

**Comment by KristofferC** [comment]
Personally, I think adding a 25% increased startup time for everyone with high core system is a bit much. It feels more reasonable to opt into that if you know you think yiu are going to use it. A lot of work has gone in to push that startup time down.

**Comment by ViralBShah** [comment]
There is no way people know that our openblas can't use all your cores by default, and  I did not even know that we set this to 8 (even though I knew that we build openblas for 32 cores). 

If I care about 50ms faster startup on a high core system, I can read the docs and improve my startup time. 

I am also wondering if this cost of thread initialization can be moved to the first time you do `using LinearAlgebra`, especially since we have some more control through LBT.

**Comment by ViralBShah** [comment]
I should also point out that this 50ms startup time is not purely a startup time hit. It includes doing `using LinearAlgebra`, querying and showing the number of threads.

If I do a pure startup time test, there is no perceptible difference. I get 0.16s with 8 threads and 0.17s with 32 threads on a fairly old machine.

**Comment by vchuravy** [comment]
I don't think this should necessarily be backported to 1.6. Changing the default behaviour like that seems okay for a minor release, but not in a patch release.

**Comment by KristofferC** [comment]
I don't think it should go in 1.7 either. At least not in 1.7. 0. The impact on loading times is unclear and since this has not been tested on master at all it introduces some uncertainty and we don't want that for a heavily delayed release.

**Pull request merged**
