### PR TITLE
LibGit2 miscellaneous fixes to credential callback

### PR DESCRIPTION
**Pull request by omus**
Part of #20725.

- Removes unnecessary `nothing` checks against `String`s. 
- Corrects a type instability with the `err` variable. 
- ~~Uses `@static` to avoid runtime calls to `is_windows`~~

### CODE REVIEW

**Comment by tkelman** [comment]
where's the type instability here?

is doing `is_windows` at runtime really making a material difference?

**Comment by omus** [comment]
Type instability was that `err = 0` is an `Int64` and later it is set to a `Int32` (Cint) by `authenticate_ssh`. Also note that `err == 0 && return Cint(0)` at the end of `authenticate_ssh` makes that function return either `false` or `Cint(0)`

**Comment by omus** [comment]
> is doing is_windows at runtime really making a material difference?

Probably not, I didn't do performance tests between the two. Is there an issue with adding in the `@static` macro?

**Comment by tkelman** [comment]
same as other kinds of conditional compilation, you could have invalid code in the inactive branch and possibly not notice until you send things through appveyor

**Comment by omus** [comment]
I didn't consider that. Since we always test with appveyor though the invalid code will eventually get caught. I personally would still leave in the `@static` macro. I'd be okay with dropping that commit if that is your preference.

**Review by ararslan — APPROVED** [review]

**Comment by tkelman** [comment]
appveyor doesn't help people testing locally, I'd rather use `@static` as sparingly as possible, only where absolutely necessary for performance or failure to build without it

**Comment by yuyichao** [comment]
What's the kind of error you want to catch by removing `@static`?

**Comment by ararslan** [comment]
I understand your point and agree in principle, @tkelman, but it seems pretty harmless in this case. (At least it seems that way to me.) I have no strong feelings either way I suppose, but the rest of this PR looks good to me.

**Comment by tkelman** [comment]
Deprecations, as one example
```
julia> @static if false
           ASCIIString("foo")
       end

julia> if false
           ASCIIString("foo")
       end
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near no file:0
```

Unless you're actually looking at the appveyor log every time, that stuff can slip through until someone who actually builds on windows (usually me) notices and fixes it. If `@static` isn't necessary, I'd rather have that failing your local builds first (if it's running in `--depwarn=error` anyway), even on other operating systems before you submit a PR and waste a bunch of CI time.

**Comment by omus** [comment]
I've reverted the `@static` change.

**Pull request merged**
