### PR TITLE
Benchmark 0.5 vs 0.6 [do not merge]

### PR DESCRIPTION
**Pull request by KristofferC**
#20947 got auto closed for some reason... Oh well.

Benchmarks again now when the inlining improvements were merged.:

@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20993) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/00b218e7e83032ed21a7cf3f494a1c56fc1c1847/4ac416d_vs_6445c82/report.md). cc @jrevels

**Comment by KristofferC** [comment]
Not bad.

Summary of stuff that got slower:

### Arrays:

* `["array","index",("sumcolon","1.0:1.0:100000.0")]`
* `["array","index",("sumeach_view","BitArray{2}")]`
* `["array","index",("sumlinear_view","BitArray{2}")]`
* `["array","index",("sumrange","1.0:1.0:100000.0")]`
* Some of the concatenations.

### ~~Date accessors in general~~

~~For example: `["dates","accessor","millisecond"]`~~

Fixed by https://github.com/JuliaLang/julia/pull/20853?

### Eig and Schuf Factorizations

For example: `["linalg","factorization",("eig","Matrix",256)]`

### `div` with BigNumbers

For example: `["scalar","arithmetic",("div","BigFloat","Complex{Float32}")]`

Maybe some new promotion paths that leads to multiple allocations of big numbers?

Yes, changed from:

```
/(a::Real, z::Complex) = a*inv(z)
```

to
```
/{R<:Real,S<:Complex}(a::R, z::S) = (T = promote_type(R,S); a*inv(T(z)))
```

### Parallell remotecall

For example `["parallel","remotecall",("identity",2)]`

### Sorting in general

For example `["sort","insertionsort",("sort forwards","ascending")]`

I think this happened when we upgraded LLVM

### Sparse indexing

For example `["sparse","index",("spmat","col","array",10)]`

### Other

* `["problem","laplacian","laplace_sparse_matvec"]`
* `["misc","bitshift",("UInt32","UInt32")]`
* `["shootout","revcomp"]`

**Comment by tkelman** [comment]
> `["scalar","arithmetic",("div","BigFloat","Complex{Float32}")]`

that should be pretty easy to fix by adding a few specialized methods that avoid creating the intermediate BigFloats that the new promotion path introduced

**Comment by tkelman** [comment]
cc @rfourquet if you're working on BigInt / BigFloat performance tweaks

**Comment by pabloferz** [comment]
With all the recent changes to codegen and bugfixes for the type system would it be worth to rebase this and rerun the benchmarks?

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-292319220):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d8f8f672b02a15d6b59ba68b113cd94707816079/b9adeec_vs_6445c82/report.md)
cc @jrevels

**Comment by KristofferC** [comment]
Looks like the benchmarks I added are to blame:

```
ERROR: LoadError: LoadError: UndefVarError: IndexStyle not defined
```

 https://github.com/JuliaCI/BaseBenchmarks.jl/blob/master/src/tuple/TupleBenchmarks.jl#L62

Anyone know what the problem is?

**Comment by timholy** [comment]
Is it using an old version of `Compat`? It needs at least `v0.19`.

**Comment by KristofferC** [comment]
Perhaps, the required one is too low at least. I made a PR to bump it.

**Comment by jrevels** [comment]
Now that Compat is updated on Nanosoldier:

@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-292549510) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c6cdfca76fdf338878c80adad21bad385f270bf4/e7132b7_vs_6445c82/report.md). cc @jrevels

**Comment by jebej** [comment]
Factorization regressions are still there :(

**Comment by jrevels** [comment]
Let's see if benchmarks vs. v0.4.7 work now (I did a `Pkg.update()` on Nanosoldier's v0.4 installation): 

@nanosoldier `runbenchmarks(ALL, vs = "@ae26b25d43317d7dd3ca05f60b70677aab9c0e08")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-294009183) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c95f3559e3e240a271c31e79239d832e75afadb2/5e1cd27_vs_ae26b25/report.md). cc @jrevels

**Comment by KristofferC** [comment]
How should this be continued? Should I open a new PR against some `release-0.6` branch or just keep benchmarking against master?

**Comment by tkelman** [comment]
at the moment the latest wip state is at tk/backports-0.6.0-rc1

**Comment by KristofferC** [comment]
ah, I can change the branch to merge into from an existing PR. Cool

**Comment by KristofferC** [comment]
tk/backports-0.6.0-rc1 vs 0.4:

@nanosoldier `runbenchmarks(ALL, vs = "@ae26b25d43317d7dd3ca05f60b70677aab9c0e08")`

**Comment by KristofferC** [comment]
tk/backports-0.6.0-rc1 vs 0.5.1:

@nanosoldier runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")

**Comment by KristofferC** [comment]
tk/backports-0.6.0-rc1 vs 0.5.1:

@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-299417648):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`make -j3`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/320fbfed060a9bcf0bb047856878537912da2834/4674210_vs_ae26b25/report.md)
cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-299418008) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a07ba09403b32d4571ffa29a8735948716b0c99f/4674210_vs_6445c82/report.md). cc @jrevels

**Comment by oscardssmith** [comment]
This looks really good overall. Does anyone know what caused the regression in div for complex bigfloats?

**Comment by KristofferC** [comment]
Yes, read the first post.

**Comment by KristofferC** [comment]
rc2 vs 0.5.2:

@nanosoldier runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")

**Comment by KristofferC** [comment]
rc2 vs 0.5.2:

@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20993#issuecomment-301342616) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d23b8d75c63370252f87784a2b413c123d02f6dd/85eab98_vs_6445c82/report.md). cc @jrevels

**Comment by tkelman** [comment]
dates constructors, uint bitshift, and some of the simd regressions might be worth looking at to see if they're fixable

I looked a bit at complex div but couldn't find a way of preserving the more accurate result with fewer allocations. I think it would require writing some careful in-place code, which would be really messy without the module reorganization @rfourquet did recently (which for now is 0.7-only)

**Comment by jebej** [comment]
Should the benchmarks be run for the upcoming rc3 as well?

**Comment by KristofferC** [comment]
They are run for regressions against the last risk but she how useful it is to benchmark here. Could probably close it.

**Pull request closed without merging**
