### PR TITLE
update `jltapir-pr` to the latest master

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Something has gone wrong here?

**Comment by DilumAluthge** [comment]
If the goal is to update a certain feature branch to be up-to-date with master, I think it would make more sense to rebase that feature branch and force-push.

**Comment by aviatesk** [comment]
Rebasing can make collaboration hard.

**Comment by aviatesk** [comment]
Hmmm... Somehow all related commits are appearing here... I'm really not sure why this weirdness happened, but let me just close this.

**Comment by tkf** [comment]
Thanks! I tried to extract out the changes in this PR in the last three commits. Let me know if I missed other changes.

**Review by tkf — COMMENTED** [review]
Thanks! I tried to extract out the changes in this PR in the last three commits. Let me know if I missed other changes.

**Pull request merged**
