### PR TITLE
Julia now multi-threaded by default i.e. -t auto,1

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Completes #50636

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Does FreeBSD for sure allow -t auto, or just not in this case, that I could fix:

┌ Warning: Running this file with multiple Julia threads may lead to a build error
│   Threads.maxthreadid() = 2
└ @ Main.anonymous /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-1/julialang/julia-master/contrib/generate_precompile.jl:7

**Comment by KristofferC** [comment]
This should be draft so it isn't accidentally merged.

**Comment by PallHaraldsson** [comment]
E.g. at  4160:

```
[12097] signal (11.1): Segmentation fault
in expression starting at none:0
_ZN12_GLOBAL__N_116GetCFGOnlyPasses13passEnumerateEPKN4llvm8PassInfoE at /cache/build/default-amdci5-5/julialang/julia-master/usr/bin/../lib/libLLVM-15jl.so (unknown line)
Allocations: 2906 (Pool: 2896; Big: 10); GC: 0
Segmentation fault
make[1]: *** [pkgimage.mk:130: stdlib/LazyArtifacts.release.image] Error 139
make[1]: Leaving directory '/cache/build/default-amdci5-5/julialang/julia-master'
make[1]: *** Waiting for unfinished jobs....
make[1]: Entering directory '/cache/build/default-amdci5-5/julialang/julia-master'
 /cache/build/default-amdci5-5/julialang/julia-master/usr/bin/julia --startup-file=no -e 'Base.compilecache(Base.identify_package("GMP_jll"))'
```

This could seemingly be fixed by (well a workaround) by (and I'll look into that, would I expect many more similar issues that will not have such a simple fix?):

julia -t 1 --startup-file=no -e 'Base.compilecache(Base.identify_package("GMP_jll"))'

For some reason it doesn't always segfault e.g. for the line higher up:

/cache/build/default-amdci5-5/julialang/julia-master/usr/bin/julia --startup-file=no -e 'Base.compilecache(Base.identify_package("libLLVM_jll"))'

**Comment by carstenbauer** [comment]
> if CI passes this doesn't need to be a draft, and can at least be merged on master.

A side comment: You propose a pretty influential change. Making a PR for it and expecting it/pushing for it to be merged to master within less than 3 days isn't helpful and unrealistic. Also, it suggests - at least to me - that you haven't thought this through properly. For example, neither here nor in https://github.com/JuliaLang/julia/issues/50636 do you really address the question what we should do about BLAS threads when increasing the `-t` default. It might be fine to keep the current default for the number of BLAS threads (I think so) but it isn't obvious at all because calling BLAS functions from multiple Julia threads would then give bad performance (which is why we currently recommend `OPENBLAS_NUM_THREADS=1` when using `-t >1`).

**Comment by gbaraldi** [comment]
Adding workarounds to the issues isn't the way forward, instead finding ways to at least consistently reproduce them, and then with debugging trying to make whatever thread unsafe operation we are doing thread safe.

**Pull request closed without merging**
