### PR TITLE
WIP: Move some documentation to sparse files

### PR DESCRIPTION
**Pull request by KristofferC**
So this is my mini attempt of moving some of the documentation from helpdb.jl to source files. I started small with a few methods in `sparsematrix.jl`. The reason for starting small is that I don't know if I do it right or if this is desired at this point.

Questions:
- The fact that nothing changed in the .rst files from my changes means I did it right?
- Why was unrelated changes updated in the manual when I ran `genstdlib.jl`. Is it because people have added things to `helpdb.jl` without rerunning the manual builder?

@one-more-minute @MichaelHatherly

### CODE REVIEW

**Comment by yuyichao** [comment]
I'm not sure if we want to mess with the doc more before 0.4 is released. Definitely not before https://github.com/JuliaLang/julia/pull/12835 is merged

**Comment by KristofferC** [comment]
Yeah, I realize that. Would be good to get answers to the questions nonetheless. I could easily redo this after #12835 is merged.

**Comment by MichaelHatherly** [comment]
> The fact that nothing changed in the .rst files from my changes means I did it right?

Yes, I believe so.

> Why was unrelated changes updated in the manual when I ran ``genstdlib.jl``. Is it because people have added things to ``helpdb.jl`` without rerunning the manual builder?

Could ``genstdlib.jl`` be run automatically at the very end of ``make`` to avoid this from happening with future doc-related PRs?

**Comment by jakebolewski** [comment]
I think it would be safe to do this now.

**Comment by ViralBShah** [comment]
@KristofferC Could you rebase this? Nice to get it in and perhaps even backport.

**Comment by KristofferC** [comment]
I redid it from scartch in #13236 because I didn't want to deal with merge conflicts.

**Pull request closed without merging**
