### PR TITLE
export println_with_color

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/10327

### CODE REVIEW

**Comment by tkelman** [comment]
quoting jeff

> Generally underscores are unsatisfying. print_color should ideally be separated into two concepts: print and color

would be better to deprecate print_with_color and have a composable api for color output

to export this it would have to go in the stdlib doc index and be tested.

**Comment by KristofferC** [comment]
> would be better to deprecate print_with_color and have a composable api for color output

Sure but that is a whole other project. Considering we have `print`, `println`, `print_with_color` it makes sense to have `println_with_color`. If someone later revamps the color printing, then that will of course change. Agree?

**Comment by KristofferC** [comment]
Otherwise, please close this and #10327.

**Comment by KristofferC** [comment]
Regarding a revamped color printing design, https://github.com/KristofferC/Crayons.jl would be my suggestion but it feels that with the push to move things out of base, it might be better to stay as a package.

**Pull request closed without merging**
