### PR TITLE
Fix #10124 by adding check for undefined behaviour

### LINKED ISSUE #10124: numbers test failure on ARM
On x86:
````
julia> typemax(UInt64) != 2.0 ^ 64
true
````

On ARM:
````
julia> typemax(UInt64) != 2.0 ^ 64
false
````

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #10124, also adds explanation of logic. Checked on ARM machine.

cc: @eschnett, @nkottary, @ViralBShah

### CODE REVIEW

**Comment by ViralBShah** [comment]
Looks like this is failing the whitespace test.

**Comment by simonbyrne** [comment]
Updated. Is there an easy way to add the whitespace check as a pre-commit hook?

**Comment by simonbyrne** [comment]
Ah, figured it out:
```
cp .git/hooks/pre-commit.sample .git/hooks/pre-commit
```

**Comment by vtjnash** [comment]
is this overly conservative?

> +# - typemax(Ti) can't be exactly represented by Tf:

for example, `typemax(Int32)` can be exactly represented in Float64

**Comment by simonbyrne** [comment]
Yes, these methods would not be valid in that case (note that `Int32` vs `Float64` are defined elsewhere).

The extra condition that I've added `(fy != $(Tf(typemax(Ti))))` assumes that `Tf(typemax(Ti)))` involves some sort of rounding (either to `2^n` or `+Inf`).

**Comment by yuyichao** [comment]
Hmmm, I suspect this PR has turned a similar test failure on AArch64 into an abort. Not exactly sure what happens yet trying to get a backtrace.

**Comment by yuyichao** [comment]
Actually the failing test passes and it is probably something else going wrong.

**Pull request merged**
