### PR TITLE
update libwhich to latest commit (from 2022/10)

### PR DESCRIPTION
**Pull request by semarie**
it supports more platforms.

it is part of on-going work to port julia to OpenBSD.

### CODE REVIEW

**Comment by vtjnash** [comment]
I think you also need to first update Yggdrasil to build the latest commit also

**Comment by imciner2** [comment]
I don't think libwhich is in Yggdrasil.

**Comment by ViralBShah** [comment]
Should we add it to Yggdrasil?

**Comment by imciner2** [comment]
I think it is a build-time only dep, right? If so, I don't really see a need to put it into Ygg.

**Review by fingolfin — APPROVED** [review]
This moves libwhich from a commit made in November 2017 to the most recent (from October 2022), including fixes for OpenBSD and musl (?), so it seems indeed long overdue to do this. Hopefully won't cause regressions, but if the tests pass, should be merged.

However the mingw32 test is failing. I hope it's a fluke but it should be restarted to verify.

**Pull request merged**
