### PR TITLE
🤖 [master] Bump the SparseArrays stdlib from 99c99b4 to 54f4b39

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Stdlib branch: main
Julia branch: master
Old commit: 99c99b4
New commit: 54f4b39
Julia version: 1.11.0-DEV
SparseArrays version: 1.11.0
Bump invoked by: @ViralBShah
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaSparse/SparseArrays.jl/compare/99c99b4521eb19a7973643d1aa4d7b1e4d50a6db...54f4b39d1cd34a908ff4fdfcd052a38fe23f6555

```
$ git log --oneline 99c99b4..54f4b39
54f4b39 Fix docs conflict when building as part of full Julia docs (#430)
a64ef4f Cleanup reloaded (#426)
4e2d1e4 Respect `IOContext` while displaying a `SparseMatrixCSC` (#423)
3d1eda9 Test suite: activate a temp project if we need to install Aqua.jl during the test suite (#425)
18b7fce Merge pull request #422 from JuliaSparse/jn/cat
e2c78b8 test: restore ambiguous test
68afc6e fix inference of SparseVector cat
c402d09 cat: ensure vararg is more inferrable
2c4f870 Fix some broken links (#421)
36a5308 bump version (#418)
```

### CODE REVIEW

**Comment by jishnub** [comment]
Would it be possible to backport this (or certain SparseArrays commits featured in this) to v1.10? This bump appears to fix the regression observed in https://github.com/JuliaLang/julia/issues/50854. I've not narrowed it down yet.

**Comment by DilumAluthge** [comment]
We won't backport this BumpStdlibs PR. Instead, the backports will be done in the SparseArrays.jl repo to the `release-1.10` branch there, and then when BumpStdlibs is triggered, it'll be to target the `release-1.10` branch in this repo to update to the latest commit on the `release-1.10` branch in the SparseArrays.jl repo.

Essentially the same process that we use in Pkg.jl.

**Comment by jishnub** [comment]
There doesn't seem to be a `release-1.10` branch in `SparseArrays.jl` yet. I'm unsure which commit this should be created from, is it from the commit before https://github.com/JuliaSparse/SparseArrays.jl/commit/36a53083043e397d98e41e94324b5656d1384600, given that this bumped the Julia compat?

**Comment by DilumAluthge** [comment]
cc: @Wimmerer who I think will be doing the backports for SparseArrays for the 1.10 release process.

**Pull request merged**
