### PR TITLE
Make RowVector obey AbstractMatrix indexing interface

### LINKED ISSUE #466: Diagonal(RowVector) segfaults
Found by @alanedelman,

```julia
julia> Diagonal(randn(4)')
[1]    47132 segmentation fault  julia-dev
```

### LINKED ISSUE #23649: Diagonal(RowVector) segfaults
Found by @alanedelman,

```julia
julia> Diagonal(randn(4)')
[1]    47132 segmentation fault  julia-dev
```

### PR DESCRIPTION
**Pull request by andyferris**
Fixes JuliaLang/LinearAlgebra.jl#466

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Love the code reduction and simplification! ❤️

**Review by andreasnoack — APPROVED** [review]

**Comment by ararslan** [comment]
`git bisect` says that backporting this broke the ImageFiltering tests. See https://gist.github.com/ararslan/ae2efe715bbc9357ea0a3f501d30b2b0#file-pkgeval_imagefiltering_test-log. Looks like it's hitting a `getindex` method here.

**Comment by andyferris** [comment]
@ararslan not too surprising something was affected by this...

**Comment by ararslan** [comment]
Is there a way to fix the `Diagonal` segfault in a non-breaking way in 0.6? Otherwise I think I have to just remove this commit from my backports branch.

**Pull request merged**
