### PR TITLE
lock: optimize re-entrant performance

### PR DESCRIPTION
**Pull request by vtjnash**
```
julia> r = ReentrantLock(); lock(r); unlock(r);
julia> f(r) = @time for i = 1:10^7; lock(r); unlock(r); end;

before:
julia> f(r)
  0.271201 seconds
julia> lock(r); f(r); unlock(r)
  0.274864 seconds

after:
julia> f(r)
  0.280015 seconds
julia> lock(r); f(r); unlock(r)
  0.149524 seconds
```

This also may need #24431 to show better improvement. Both are also being harmed by incorrect PhiC node placement (will open an issue about this).

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by yuyichao** [comment]
I think this is currently undefined behavior.

**Comment by vtjnash** [comment]
What part?

**Comment by yuyichao** [comment]
The part that's accessing shared field without lock. The read (and the corresponding store) of the `locked_by` field must be atomic (relaxed order).

**Comment by vtjnash** [comment]
`unlock` usually should contain the memory barrier to make that unnecessary

**Comment by yuyichao** [comment]
No the barrier always works in pairs. The unlock can have all the barrier you can possibly implement and it won't make the unprotected access in lock any safer.

**Comment by vtjnash** [comment]
> The read (and the corresponding store) of the locked_by field must be atomic (relaxed order).

Now implemented in #36507

**Pull request merged**
