### PR TITLE
fix parse(ComplexF64, "inf")

### PR DESCRIPTION
**Pull request by stevengj**
I noticed that the parsing code in #24713 was getting confused by the `i` in `"inf"` when parsing a purely real infinity.  This PR fixes that and adds some more tests for floating-point values.

Probably could be backported?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I've added backport labels and triage to discuss but maybe the latter is unnecessary since this seems like a straightforward bugfix so long as it applies.

**Comment by JeffBezanson** [comment]
Seems to have relevant failures on windows.

**Comment by mbauman** [comment]
Test failures from the windows buildbots look highly relevant.  For example:

```
Error During Test at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\parse.jl:299
  Test threw exception
  Expression: n === parse(ComplexF64, s)
  ArgumentError: cannot parse " nan" as Float64
```

**Comment by stevengj** [comment]
@mbauman, is that a Windows bug?  On my Mac I get:
```jl
julia> parse(Float64, " nan")
NaN
```
We should definitely be consistent across platforms here, and in general `parse(Float64, string)` ignores leading whitespace so it should do the same thing for `nan` and `inf`.

**Comment by mbauman** [comment]
I'm just copy-pasting the error message from the buildbots.  I don't know anything more.

**Comment by GregPlowman** [comment]
On Windows 10 with Julia 1.1.0 I get this:
```
Julia-1.1.0> parse(Float64, "nan")
NaN

Julia-1.1.0> parse(Float64, "nan ")
NaN

Julia-1.1.0> parse(Float64, " nan")
ERROR: ArgumentError: cannot parse " nan" as Float64
Stacktrace:
 [1] _parse_failure(::Type, ::String, ::Int64, ::Int64) at .\parse.jl:370 (repeats 2 times)
 [2] #tryparse_internal#349 at .\parse.jl:366 [inlined]
 [3] tryparse_internal at .\parse.jl:364 [inlined]
 [4] #parse#350 at .\parse.jl:376 [inlined]
 [5] parse(::Type{Float64}, ::String) at .\parse.jl:376
 [6] top-level scope at none:0
```

**Comment by stevengj** [comment]
Sounds like a bug in on `jl_strtod_c` in [`strtod.c`](https://github.com/JuliaLang/julia/blob/master/src/support/strtod.c), which is called on Windows because it doesn't have `strtod_l` (though it does have [`_strtod_l`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l)… not sure why we don't call that?).

**Comment by stevengj** [comment]
added a bugfix

**Comment by stevengj** [comment]
AppVeyor is now passing.  Travis Linux x86 failures (in zillions of tests) look unrelated.  win32 buildbot timeout looks unrelated.

Note that this PR does *not* need to be squashed — it's two commits that fix two bugs.

**Pull request merged**
