### PR TITLE
Unexport with, at_with, and ScopedValue from Base

### LINKED ISSUE #52535: Consider renaming `@with` for ScopedValues
PR #50958 introduces the `@with` macro along with dynamic scoping generally. 

DataFramesMeta.jl, the data analysis package I maintain, currently exports our own `@with` and will have to re-name the macro before the Julia's v1.11 release. 

`@with` is a very valuable name. It's short and clear. Considering this, having it's use-case for `ScopedValue`s only seems unnecessarily niche to me. 

Would it be possible to re-name the `with` and `@with` to something that doesn't use such a short name? 

I'm not opposed to Julia Base taking over `with` and `@with` in the abstract. But this seems like such a unique use-case that the costs don't outweigh the benefits.

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #52535

### CODE REVIEW

**Comment by vchuravy** [comment]
Depends on https://github.com/JuliaLang/julia/pull/53012

**Comment by vchuravy** [comment]
Likely, but I haven't had time to dig into the test failure.

**Comment by pdeffebach** [comment]
Thanks all! I really appreciate it!

**Comment by MilesCranmer** [comment]
This change is breaking some of my internal CI I just started testing the new alpha on.

To help me understand, why was this added to Julia 1.x? I thought the rule was that any exported symbol would be part of the stable API and guaranteed backwards compatibility.

This is what the [Julia blog](https://julialang.org/blog/2019/08/release-process/#minor_releases) states:

> [Minor releases](https://julialang.org/blog/2019/08/release-process/#minor_releases)
> Minor releases increment the middle digit of Julia's version number, e.g. going from 1.2.3 to 1.3.0.
> 
> Minor releases may include bug fixes, new features and "minor changes"—which is the term we're using for technically breaking changes that are sufficiently unlikely to break anyone's code and which, in fact, do not break things in the package ecosystem as determined by running PkgEval to verify that there isn't any breakage.
> 
> Minor releases are also where significant refactorings of internals go, since we should only be refactoring to the extent that is necessary for fixing bugs in patch releases. This means that if you're relying on some internal Julia stuff that's not public, your code might break in a minor release. This is allowed according to SemVer since the change isn't to a public API—so technically it can break at any time; but we will avoid this in patch releases, so minor releases will be where you have to watch out if you rely on internals somehow.
> 
> Minor releases are branched every four months, which means that there are three minor releases per year. The rate is controlled by doing timed features freezes for minor releases: every four months, we announce on discourse that the current development version is about to feature freeze (with about two weeks notice); then on the freeze date, we branch a release-1.3 branch for the minor release and after that no more feature development is allowed on that branch, from which the release will be tagged. More on that process below.

`@with` is not "internal" since it is exported on 1.10. So why not make a Julia 2.x instead so I can do get alerted I need to update my compatibility? Why change the meaning of a minor release for the convenience of a downstream package? You can always do a 2.x like PyTorch and not have it change much at all, just do a few breaking changes. But why put breaking changes in 1.x?

It's not so much the specific symbol here as I can fix it; it's more the precedent this sets. Do I need to assume minor releases are now major releases?

**Comment by MilesCranmer** [comment]
Why was this done in 1.11? It seems to violate SemVer, no? This is ultimately a breaking change to the public API. For the convenience of a third party package seems like a weak reason for such a change. I guess the assumption here was that `@with` was not used a lot in publicly available packages?

**Pull request merged**
