### PR TITLE
[release-0.4] backport ARM ABI

### PR DESCRIPTION
**Pull request by tkelman**
Backporting #14194 again, but this time in a way that should build correctly on release-0.4.

### CODE REVIEW

**Comment by tkelman** [comment]
A colleague hit a segfault where the root cause was calling `float("0")`. ccall ABI fixes it.

`runbenchmarks("all", vs = "JuliaLang/julia:v0.4.3")`

**Comment by jrevels** [comment]
The format allowed for `vs` is `"user/repo:branch"` or `"user/repo@sha"`. It'd be nice if it accepted tags, though... 

Also, I think you were looking for the keyword `ALL`, which is a placeholder that matches all benchmarks:

`runbenchmarks(ALL, vs = "JuliaLang/julia@a2f713dea5ac6320d8dcf2835ac4a37ea751af05")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/15638#issuecomment-201991807) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/080edb9e08e6855732b73b15a0783bc28b8345cb/01a0654/01a0654_vs_a2f713d.md). cc @jrevels

**Comment by tkelman** [comment]
are those regressions serious enough to worry about? what's the best way to replicate locally? this makes the arm build work much much better on release-0.4

**Comment by jrevels** [comment]
The timing regressions are all from benchmarks that have proven very noisy in the past. The ~83x allocation count regression on the in-place insertion sort benchmark is weird, though, and worth checking out. I could tell you how to do it using BaseBenchmarks.jl, but those instructions will be obsolete soon, so it'll probably be easier just to check it manually:

```julia
list = rand(MersenneTwister(1), 50000)
@time sort!(list, alg = InsertionSort)
```

I'm currently building this branch locally to see if I can reproduce the regression using the newer benchmark tools, I'll report back if I find anything relevant.

**Pull request merged**
