### PR TITLE
🤖 Bump the Pkg stdlib from ad3d6396 to 1a47f445

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Pkg
Branch: master
Old commit: ad3d6396
New commit: 1a47f445
Bump invoked by: @IanButterworth

```
$ git log --oneline ad3d6396..1a47f445
1a47f445 make registry dir if missing (#2546)
b35c6731 Fix module reference typo in #2307 (#2547)
```

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by IanButterworth** [comment]
My bad. https://github.com/JuliaLang/julia/pull/40684 had a bug that's now covered by Pkg tests as of this update

**Comment by IanButterworth** [comment]
Why has this started happening in this PR? That version of SuiteSparse was released 17 days ago

```
ERROR: The working directory is dirty.
Output of git status:
On branch refs/pull/40687/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	deps/checksums/SuiteSparse.v5.8.1+2.x86_64-linux-gnu.tar.gz/
```

**Comment by DilumAluthge** [comment]
> Why has this started happening in this PR? That version of SuiteSparse was released 17 days ago
> 
> ```
> ERROR: The working directory is dirty.
> Output of git status:
> On branch refs/pull/40687/merge
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	deps/checksums/SuiteSparse.v5.8.1+2.x86_64-linux-gnu.tar.gz/
> ```

It just started happening now because we just merged https://github.com/JuliaCI/julia-buildbot/pull/203 an hour ago.

cc: @staticfloat @vtjnash @vchuravy

**Comment by DilumAluthge** [comment]
Also cc: @omus @ViralBShah

**Comment by IanButterworth** [comment]
I see.. unlucky timing (was hoping this would be a quick PR)
I'll PR the missing checksums

**Comment by ViralBShah** [comment]
Not sure how that checksum was missed. I had run the script that auto-generates them all just recently.

**Pull request merged**
