### PR TITLE
More consistent return value for annotations

### PR DESCRIPTION
**Pull request by tecosaur**
This is a generally nice simplification, that tweaks the `annotations` API.

It also requires the adjustment in
https://github.com/JuliaLang/StyledStrings.jl/pull/38 to be made, hence the
bump.

### CODE REVIEW

**Comment by tecosaur** [comment]
Changes included in the StyledStrings bump:

```
e0ca0f8 * Adjust to changed annotations function return form
7ce4e69 * More consistent legacy color conversion
26b5d2f * Fix invalid non-empty state assumptions in macro
0625bce * More predictible parsing with escape_raw_string
57619c2 * New faces for stacktrace printing in Base
0af21d0 * printstyled specialisation for AnnotatedIOBuffer
```

**Comment by vtjnash** [comment]
Just FYI, I lost your good commit message here because github now automatically replaces them with the text in the PR title. If you want to ensure that content is preserved, I recommend including it in the Github PR text.

**Comment by tecosaur** [comment]
I don't think so, and it's hard for me to see how this commit would affect anything with `@inbounds` (since this changes the form of the list returned, not the length of it).

**Comment by tecosaur** [comment]
I have just noticed that the implementation of `annotations(s::SubString{<:AnnotatedString})` will return invalid ranges, not sure if that could have something to do with it.

**Comment by vtjnash** [comment]
Are there any `@inbounds` statements that could be deleted? I see some here, and it makes me suspicious that they shouldn't be present in this code almost anywhere as it is not vectorizable code.

**Comment by tecosaur** [comment]
Aha! I think I might have found it, with the `SubString` returning invalid ranges, I've since found some code that may assume that substring ranges are valid: https://github.com/JuliaLang/StyledStrings.jl/blob/e0ca0f85412ea5cafabfeaaec4d62ca26c3959d2/src/regioniterator.jl#L13

I'm not sure how to test this theory though...

**Comment by vtjnash** [comment]
If you push a new PR, the net tests will pass/fail based on whether that fixes it. If necessarily, you might just delete the `@inbounds` there to see if it errors, if you aren't sure about the fix for it yet.

**Comment by tecosaur** [comment]
#53333 now exists (hey, that's a surprisingly memorable PR number), which should let us confirm (or disprove) my suspicion :crossed_fingers:

**Pull request merged**
