### PR TITLE
release-1.6: fix a regression in Pkg before 1.6.3 is released

### PR DESCRIPTION
**Pull request by KristofferC**
Adds https://github.com/JuliaLang/Pkg.jl/pull/2730 to Pkg which is a revert of a commit that had some issues.

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
Terrific, thanks Kristoffer! :)

**Comment by Sacha0** [comment]
Looking at the tester_linux64 log I found this:
```
channels                           (4) |         failed at 2021-09-16T22:14:30.676
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:297
  Expression: ���(duration, 1, atol = 0.4)
   Evaluated: 1.899859072 ��� 1 (atol=0.4)
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:429
  Expression: tc[] == 2
   Evaluated: 1 == 2
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:431
  Expression: tc[] == 2
   Evaluated: 1 == 2
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:438
  Expression: tc[] == 2
   Evaluated: 1 == 2
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:439
  Expression: tc[] == 2
   Evaluated: 1 == 2
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:441
  Expression: tc[] == 3
   Evaluated: 2 == 3
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/test/channels.jl:443
  Expression: tc[] == 3
   Evaluated: 2 == 3
```
which appears unrelated but is worrisome. Is that failure mode known?

Later the job timed out, not sure why.

Restarting as neither of those failure modes appear related to this diff :).

**Comment by DilumAluthge** [comment]
The `buildbot/tester_macos64` job did not run, for some reason.

**Comment by DilumAluthge** [comment]
Nor did the `buildbot/package_macos64` job.

**Comment by Sacha0** [comment]
Closing/opening this pull request doesn't seem to be doing the trick with regard to buildbot/tester_macos64 and  buildbot/package_macos64. Is there some other way we can nudge those? :)

**Comment by DilumAluthge** [comment]
For those following along in this thread, we are working on fixing the macOS Buildbots. Join the `#infrastructure` channel on Slack for more details.

**Comment by DilumAluthge** [comment]
Okay, the macOS packager has passed. Let's make sure the macOS tester passes.

**Comment by Sacha0** [comment]
The buildbot/package_linuxppc64le failures appear unrelated:
```
 ==> ./julia launch speedtest
make: time: Command not found
make: *** [build-stats] Error 127
program finished with exit code 2
elapsedTime=2.389282
```
and
```
  Installing known registries into `/buildworker/worker/package_linuxppc64le/build/doc/deps`
ERROR: LoadError: expected package `Parsers [69de0a69]` to be registered
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
 [2] check_registered(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
   @ Pkg.Operations /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1157
 [3] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1372
 [4] instantiate
   @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
 [5] #instantiate#252
   @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [6] instantiate()
   @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [7] top-level scope
   @ /buildworker/worker/package_linuxppc64le/build/doc/make.jl:8
in expression starting at /buildworker/worker/package_linuxppc64le/build/doc/make.jl:8
caused by: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/cc9d45ece542806aa9bc5da7c2bca2f15849a763
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
  [2] (::Pkg.Types.var"#82#85"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec})(tmp::String)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1035
  [3] mktempdir(fn::Pkg.Types.var"#82#85"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:729
  [4] mktempdir (repeats 2 times)
    @ ./file.jl:727 [inlined]
  [5] clone_or_cp_registries(ctx::Pkg.Types.Context, regs::Vector{Pkg.Types.RegistrySpec}, depot::String)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1027
  [6] clone_or_cp_registries
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1020 [inlined]
  [7] clone_default_registries(ctx::Pkg.Types.Context; only_if_empty::Bool)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:920
  [8] clone_default_registries
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:908 [inlined]
  [9] find_registered!(ctx::Pkg.Types.Context, names::Vector{String}, uuids::Vector{Base.UUID})
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1291
 [10] find_registered!
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1252 [inlined]
 [11] check_registered(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1154
 [12] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1366
 [13] instantiate
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
 [14] #instantiate#252
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [15] instantiate()
    @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [16] top-level scope
    @ /buildworker/worker/package_linuxppc64le/build/doc/make.jl:8
caused by: HTTP/2 502 while requesting https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/cc9d45ece542806aa9bc5da7c2bca2f15849a763
Stacktrace:
  [1] (::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Pkg.PlatformEngines.var"#14#16", Bool, Nothing, String})(output::IOStream)
    @ Downloads /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:233
  [2] open(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Pkg.PlatformEngines.var"#14#16", Bool, Nothing, String}, args::String; kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:write,), Tuple{Bool}}})
    @ Base ./io.jl:330
  [3] arg_write(f::Function, arg::String)
    @ ArgTools /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:86
  [4] #download#2
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:221 [inlined]
  [5] download(url::String, dest::String; verbose::Bool, headers::Vector{Pair{String, String}}, auth_header::Nothing, io::IOContext{Base.PipeEndpoint})
    @ Pkg.PlatformEngines /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/PlatformEngines.jl:270
  [6] download_verify(url::String, hash::Nothing, dest::String; verbose::Bool, force::Bool, quiet_download::Bool)
    @ Pkg.PlatformEngines /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/PlatformEngines.jl:333
  [7] download_verify_unpack(url::String, hash::Nothing, dest::String; tarball_path::Nothing, ignore_existence::Bool, force::Bool, verbose::Bool, quiet_download::Bool, io::IOContext{Base.PipeEndpoint})
    @ Pkg.PlatformEngines /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/PlatformEngines.jl:488
  [8] (::Pkg.Types.var"#82#85"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec})(tmp::String)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1033
  [9] mktempdir(fn::Pkg.Types.var"#82#85"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:729
 [10] mktempdir (repeats 2 times)
    @ ./file.jl:727 [inlined]
 [11] clone_or_cp_registries(ctx::Pkg.Types.Context, regs::Vector{Pkg.Types.RegistrySpec}, depot::String)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1027
 [12] clone_or_cp_registries
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1020 [inlined]
 [13] clone_default_registries(ctx::Pkg.Types.Context; only_if_empty::Bool)
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:920
 [14] clone_default_registries
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:908 [inlined]
 [15] find_registered!(ctx::Pkg.Types.Context, names::Vector{String}, uuids::Vector{Base.UUID})
    @ Pkg.Types /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1291
 [16] find_registered!
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1252 [inlined]
 [17] check_registered(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1154
 [18] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1366
 [19] instantiate
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
 [20] #instantiate#252
    @ /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [21] instantiate()
    @ Pkg.API /buildworker/worker/package_linuxppc64le/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [22] top-level scope
    @ /buildworker/worker/package_linuxppc64le/build/doc/make.jl:8
make[3]: *** [html] Error 1
make[3]: Leaving directory `/buildworker/worker/package_linuxppc64le/build/doc'
make[2]: *** [docs] Error 2
make[2]: Leaving directory `/buildworker/worker/package_linuxppc64le/build'
make[1]: *** [/buildworker/worker/package_linuxppc64le/build/doc/_build/html/en/index.html] Error 2
make[1]: Leaving directory `/buildworker/worker/package_linuxppc64le/build'
make: *** [binary-dist] Error 2
program finished with exit code 2
elapsedTime=12.548407
```

**Pull request merged**
