### PR TITLE
Ensure Bool to Integer conversions always return 0 or 1

### LINKED ISSUE #20065: Random behavior when converting uninitialized Array{Bool} entries
This issue has been reported against DataArrays (https://github.com/JuliaStats/DataArrays.jl/issues/233). A short reproducer without using any package can be found [in this gist](https://gist.github.com/nalimilan/30d87f1e810afce76660e79ab5dc22f7): running the last line multiple times gives different results for several entries which should be defined.

Basically, it appears that ~~leaving some entries in a `BitArray` undefined~~ iterating over a `BitArray` can lead to an unexpected behaviour when using the `BitArray` entries in a condition to decide whether to initialize another array's entries or not.  Initializing the array fixes the randomness, as does changing the `na::BitArray{N}` field to an `Array{Bool,N}`.

This happens on both 0.5 and master, but not on 0.4.7.

Cc: @carlobaldassi

### PR DESCRIPTION
**Pull request by mbauman**
Fix #20065. Supersedes #22293.

### CODE REVIEW

**Comment by tkelman** [comment]
I'm not sure if this is running correctly right now but @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/22332#issuecomment-307703260):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/bd84593803ed9cc5cbaffe45b44e4f95421eefd6/f161fbc_vs_85ef52c/report.md)
cc @jrevels

**Comment by nalimilan** [comment]
Thanks, I can confirm this fixes https://github.com/JuliaStats/DataArrays.jl/issues/233.

**Comment by musm** [comment]
maybe try nanosoldier again?

**Comment by martinholters** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22332#issuecomment-308942968) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d415187a18cbf0703216ab55ba376af0cb1ec456/fa6236a_vs_00b9ea2/report.md). cc @jrevels

**Comment by tkelman** [comment]
@yuyichao @JeffBezanson can we merge this? Backport for 0.6.0 (if it doesn't break anything) or 0.6.1?

**Pull request merged**
