### PR TITLE
Add checking offset axis before for reshaping (#33614)

### LINKED ISSUE #33614: [SEGFAULT] Checking offset axis before for reshaping
In https://github.com/JuliaLang/julia/blob/606420a308d951ab810a05f6f6c50a1b805f2b47/base/reshapedarray.jl#L173-L177 it should be checked whether the requested array has offset axes.
Otherwise we can get segfaults. See #33603 

In the 1D->1D case (`AbstractVector`) there already is such a check:
https://github.com/JuliaLang/julia/blob/606420a308d951ab810a05f6f6c50a1b805f2b47/base/reshapedarray.jl#L165-L171

Sure, in that given Issue #33603 there might also be an error in OffsetArrays.jl but segfaulting should be prevented here aswell as ultimately ReshapedArray didn't check the indices.

MWE:
```julia
using OffsetArrays
reshape(OffsetArray(-1:0, -1:0), :,1) #shows [1,2] (because invalid indexing into UnitRange cannot segfault)
reshape(OffsetArray(-1:0, -1:0), 2,1) #works though
```
If using an Array instead of a UnitRange, one can get segfaults.

### PR DESCRIPTION
**Pull request by ghost**
fix #33614

### CODE REVIEW

**Comment by dkarrasch** [comment]
Seems like this is the wrong approach to fixing #33614. There are tons of tests that do reshaping of OffsetArrays, and which pass, i.e., meet the expectation. So reshaping does not require the array to be one-based.

**Comment by mikan2087** [comment]
@dkarrasch Thank you for review of my code. I fixed this issue by adding lines in OffsetArrays.jl(JuliaArrays/OffsetArrays.jl#84).

**Comment by timholy** [comment]
Superseded by #33890.

**Comment by rapus95** [comment]
@dkarrasch @timholy Am I on the wrong train, when think that both changes should be done? the onebased check to prevent offset types from segfaulting and the OffsetArrays patch to "reallow" using the given offset implementation. That way, if some new type doesn't implement reshaping it wont segfault.
Best would probably be if it was marked with @checkbounds,thus it will be a noop if we are sure to have correct indexing. 
And regarding the argument "but many tests do reshape offset arrays", for me that'd be an explicit reason why I would want to prevent segfaulting...

**Comment by dkarrasch** [comment]
@rapus95 But how do you reshape offset arrays if you disallow non-one-based indexing in reshape?

**Comment by rapus95** [comment]
@dkarrasch a) by reshaping the parent array (as most offset arrays are backed by a "normal" array) b) if you really know what you're doing, then you can still provide a specialized version. But the code in base cannot handle offset axes as we were able to see by the segfault.

**Comment by timholy** [comment]
The fix in #33890 does allow reshaping for arbitrary axes: the segfault happens because you access invalid memory, and #33890 fixes the address lookup. The advantage of fixing it there is that you don't even require a specific type like `OffsetArray`.

**Comment by rapus95** [comment]
so I guess reshaping sort of encourages multilayer wrapping now (since there is no need to get back to a somewhat basic array)? But oth I favour higher composability and generalisation anyway. Thus, it is the right direction I guess :D

**Comment by timholy** [comment]
Right, it needs to do the right thing in all cases. You can do something "better" in some cases, but that's the job of packages. And, of course, to "save" Julia from a segfault in older versions that won't have #33890 (which reminded me to add at least one "backport" label, so thanks for persisting).

**Pull request closed without merging**
