### PR TITLE
`InteractiveUtils.versioninfo()`: when `verbose=true`, print environment variables that might affect the `NetworkOptions` stdlib; also, try to redact some (but not all) sensitive environment variables

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by vtjnash** [comment]
BugReporting already contains a full copy of all of these secrets

**Comment by DilumAluthge** [comment]
One of the motivations for this PR is to help people diagnose errors that they encounter when they try to download and install packages. Putting this functionality into an external package kind of defeats the purpose, right?

**Comment by DilumAluthge** [comment]
Bump @StefanKarpinski

**Comment by vtjnash** [comment]
@StefanKarpinski Is this a good list of variables, or is there a better way to print the full set of NetworkOptions information?

**Comment by DilumAluthge** [comment]
@vtjnash Based on your idea [here](https://github.com/JuliaLang/julia/pull/43834#issuecomment-1034211488), perhaps this would go better in a `NetworkOptions.__diagnostics__()` function?

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/JuliaLang/NetworkOptions.jl/pull/21

**Pull request closed without merging**
