### PR TITLE
Update combinatorics.jl

### PR DESCRIPTION
**Pull request by sbromberger**
Fixes issue 2 described in #9943 for most (if not all) reasonable cases.

### CODE REVIEW

**Comment by ivarne** [comment]
We also have `Base.checked_mul`, which seem somewhat more elegant.

**Comment by sbromberger** [comment]
Yes, absolutely. I didn't know it existed!

**Comment by jiahao** [comment]
lgtm, please squash

**Comment by sbromberger** [comment]
I don't know whether I can squash this - I edited via github.

**Comment by garborg** [comment]
@sbromberger It looks like it's living in the 'patch-1' branch of sbromberger/julia.

**Comment by sbromberger** [comment]
It is but that only exists in github.com since I'm away from my primary machine for the next week. If the squash is necessary I'll do it when I can clone the repo to a machine  where I can issue a rebase. 

Unless there's a way to do it within GitHub.com...

**Comment by jiahao** [comment]
I can go ahead and clean it up.

**Comment by jiahao** [comment]
Committed as 624e466526320b1267074ba3cd8031f78623736f

**Pull request closed without merging**
