### PR TITLE
clean up argument processing order

### PR DESCRIPTION
**Pull request by JeffBezanson**
- load juliarc very early, before start_worker or starting processes
- load juliarc in only one place
- handle -L after starting workers, like the help says
- shorten some of the code

see #10692

### CODE REVIEW

**Comment by jakebolewski** [comment]
@tkelman do you know why this causes the Windows tests to consistently fail? I have a follow up quick fix that addresses #10226.

**Comment by tkelman** [comment]
Yeah, programs that the spawn tests are calling live in Git/bin which gets added to the path by juliarc https://github.com/JuliaLang/julia/blob/master/contrib/windows/juliarc.jl so evidently that isn't happening early enough or at all here?

**Comment by JeffBezanson** [comment]
Ah, maybe I want

```
startup               = (opts.startupfile != 2)
```

instead?

**Comment by mbauman** [comment]
Loading .juliarc.jl this early means that we can no longer make modifications to the REPL.  I simply had `using TerminalExtensions` in my juliarc, but I'm pretty sure this will also affect folks who were changing their keymaps or things like that.

**Comment by KristofferC** [comment]
FWIW modifications can still be done with `atreplinit` but directly changing fields in the repl does not work (because it doesn't exist yet).

**Pull request merged**
