### PR TITLE
Generic fallback for logdet

### PR DESCRIPTION
**Pull request by mschauer**
This was suggested by @tkelman https://github.com/mschauer/Bridge.jl/commit/9a9410ec9a1e51647af4de892bb8f364d8b96876#commitcomment-22846497 .

### CODE REVIEW

**Comment by tkelman** [comment]
maybe just for `::Number` to be consistent with `det`? `logabsdet` might also be useful in some generic-code cases

**Comment by mschauer** [comment]
Hm.

Contra: if ``det`` is defined, ``logdet`` should be defined as well; if ``det`` is not defined, ``logdet`` fails with a (helpful) error that ``det`` is just not defined.

Contra: the presence of ``logdet`` somehow indicates, that it is "better" than just log(det(x))

**Comment by bramtayl** [comment]
Is it possible to make a det method that specializes on log generators? Then you could get rid of logdet altogether

**Review by andreasnoack — APPROVED** [review]
I think this is fine to have for `Any` since it should always be correct and failing will happen as expected via `det` and `log`.

**Comment by mschauer** [comment]
I think this is fine now.

**Comment by tkelman** [comment]
should probably do logabsdet as well

**Pull request merged**
