### PR TITLE
Move testenv specific consts and addprocs to a separate file.

### PR DESCRIPTION
**Pull request by amitmurthy**
https://github.com/JuliaLang/julia/pull/21652 broke code coverage.

~~This PR addresses https://github.com/JuliaLang/julia/pull/21652#issuecomment-299216890 by isolating test env constants and addprocs into a new module `JuliaTestEnv`.~~ 

Changed to https://github.com/JuliaLang/julia/pull/21713#issuecomment-299653874

### CODE REVIEW

**Comment by yuyichao** [comment]
Shouldn't 
```patch
diff --git a/test/testdefs.jl b/test/testdefs.jl
index 7450c4bcaf..79c0f7edca 100644
--- a/test/testdefs.jl
+++ b/test/testdefs.jl
@@ -30,7 +30,11 @@ function runtests(name, isolate=true)
             # code it in the test
             mod_name = Symbol("Test", rand(1:100), "Main_", replace(name, '/', '_'))
             m = @eval(Main, module $mod_name end)
-            eval(m, :(import Main: test_exename, test_exeflags, addprocs_with_testenv))
+            @eval m begin
+                const test_exename = $test_exename
+                const test_exeflags = $test_exeflags
+                const addprocs_with_testenv = $addprocs_with_testenv
+            end
         else
             m = Main
         end
```
Be enough?

**Comment by yuyichao** [comment]
Also it broke non-isolating test runs so it should be

```
diff --git a/test/testdefs.jl b/test/testdefs.jl
index 7450c4bcaf..b2f264d4ad 100644
--- a/test/testdefs.jl
+++ b/test/testdefs.jl
@@ -30,11 +30,15 @@ function runtests(name, isolate=true)
             # code it in the test
             mod_name = Symbol("Test", rand(1:100), "Main_", replace(name, '/', '_'))
             m = @eval(Main, module $mod_name end)
-            eval(m, :(import Main: test_exename, test_exeflags, addprocs_with_testenv))
         else
             m = Main
         end
-        @eval(m, using Base.Test)
+        @eval m begin
+            using Base.Test
+            const test_exename = $test_exename
+            const test_exeflags = $test_exeflags
+            const addprocs_with_testenv = $addprocs_with_testenv
+        end
         ex = quote
             @timed @testset $"$name" begin
                 include($"$name.jl")
```

**Comment by amitmurthy** [comment]
@yuyichao that should work too. Isolating it is a separate module allows us to cleanly add a) new test environment specific stuff later and b) `JuliaTestEnv.addprocs` is nicer than `addprocs_with_testenv`.

Would prefer to have `JuliaTestEnv` unless there are specific concerns with it.

**Comment by yuyichao** [comment]
Mostly because this is a much larger change then just setting a few variables correctly.

This also doesn't make it easier to add new variables later, especially since this cannot replace the few other variables that are currently set in the test files (`cur_mod` etc) since they are test dependent and makes running individual test files even harder (now you have to create the module).

FWIW, I was trying very hard to not require more than `using Base.Test` before running https://github.com/JuliaLang/julia/pull/21652 is the first PR that break this. It's going to be much more annoy when reducing a test case from now on............................

**Comment by amitmurthy** [comment]
How about we move the definitions to a new file `testenv.jl` and have only `runtests.jl`, `distributed.jl` and `distributed_exec.jl` include it?  These are the only files calling addprocs. topology.jl call addprocs too but it is itself an include in `distributed_exec.jl`.

**Comment by yuyichao** [comment]
That'll be much better.

**Comment by amitmurthy** [comment]
Done.

**Review by yuyichao — APPROVED** [review]
Now `testenv.jl` is indeed a good place for some of the other variables to live. Maybe even merge with `TestHelpers.jl`. I'll probably submit a clean up PR to do some of these after this is merged.

**Pull request merged**
