### PR TITLE
bump Pkg (release-1.6) & Downloads (v1.1.0)

### PR DESCRIPTION
**Pull request by StefanKarpinski**
cc @KristofferC: this bumps Pkg to the head of the release-1.6 branch. @staticfloat: any idea why the Downloads hashes would not be regenerated when I make? Very strange.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Ok, for some reason this is not regenerating deps hashes for Downloads. I have no idea why.

**Comment by DilumAluthge** [comment]
> Ok, for some reason this is not regenerating deps hashes for Downloads. I have no idea why.

In my experience, I always have to generate the hashes locally. E.g. delete the old hashes, update the sha, and then run `make clean; make` locally to generate the hashes.

**Comment by KristofferC** [comment]
>  any idea why the Downloads hashes would not be regenerated when I make? Very strange.

I remember something like that happening. Then I did something and it went away. Probably the most unhelpful thing I've written, but that's what I remember...

**Comment by StefanKarpinski** [comment]
@DilumAluthge: that is what I did. I even did `git clean -xdf -- deps` to make sure that I forced make to download everything. @KristofferC: not that unhelpful since it's making me feel less nuts.

**Comment by StefanKarpinski** [comment]
@staticfloat: looks like our CI setup does not like PUT/POST requests. Works fine when testing elsewhere. Anything we can do about that?

**Comment by StefanKarpinski** [comment]
But apparently only a problem on 32-bit systems 🤔. Maybe that does suggest a 32-bit Downloads bug...

**Comment by staticfloat** [comment]
If you're on a Linux system such as an arctic, you can build a 32-bit build by setting `MARCH=i686` and adapting the autodetected BB triplet.  Figure out the old triplet via `make print-BB_TRIPLET_LIBGFORTRAN_CXXABI`, then change `x86_64-` to `i686-`.  So for instance on my machine, I can build from a clean slate via `make -j$(nproc) ARCH=i686 BB_TRIPLET_LIBGFORTRAN_CXXABI=i686-linux-gnu-libgfortran5-cxx11`.  That's probably the easiest way to figure out what's going on.

**Comment by staticfloat** [comment]
I'm not sure what the hash issues are; if you need to bump again and the hashes aren't here, I'll take a look.

**Comment by StefanKarpinski** [comment]
I have succeeded at making this fail elsewhere on 32-bit, so this is a legit Downloads bug:

https://travis-ci.com/github/JuliaLang/Downloads.jl/jobs/420040949

**Comment by StefanKarpinski** [comment]
There was a legitimate bug with PUT/POST requests on 32-bit platforms, fixed by https://github.com/JuliaLang/Downloads.jl/pull/57.

**Comment by StefanKarpinski** [comment]
Only failures are on flaky platforms that always time out and/or fail.

**Pull request merged**
