### PR TITLE
Removed confusing array of types in readcsv help

### PR DESCRIPTION
**Pull request by mbeltagy**

### CODE REVIEW

**Comment by tkelman** [comment]
this isn't an array, it's actually trying to say that the type input is optional (another reason why I think we should just use Julia syntax for that optional argument convention in docstrings)

**Comment by ViralBShah** [comment]
Cc @tanmaykm

**Comment by mbeltagy** [comment]
I believe we need better standards for documenting optional arguments.  In the manual I sometimes see it as 
```
foo(arg [,optional_arg])
```
So maybe we need to have that for all optional arguments in the docs, instead of the often ambiguous
```
foo(arg, [optional_arg])
```

**Comment by tanmaykm** [comment]
I think we can merge this.
And also open an issue to have a uniform standard for documenting optional arguments.

**Comment by tkelman** [comment]
it would need a genstdlib run. and it's probably covered by #18041, but worth checking

**Comment by mbeltagy** [comment]
I checked  #18041 and found that the [optional_arg] style was used. This is often at odds with the manual. So I created #18318.

**Comment by kshyatt** [comment]
@mbeltagy in that PR I was just trying to get as much stuff out of HelpDB as possible, not really overhaul all those docs (although some of that ended up happening). I agree that the square brackets aren't great. Have you run `genstdlib`? Is this good to go?

**Comment by mbeltagy** [comment]
@kshyatt I ran `genstdlib`. It is good to go.  
I could start an effort to remove square brackets from the docs, if you think it is worth while. I get a feeling that the community has not been happy with them for some time. (c.f. #4902)

**Comment by tkelman** [comment]
A correct run of `genstdlib` needs to happen after bootstrapping and should change the rst docs. You'd need to commit and push that change.

**Pull request merged**
