### PR TITLE
mul!, rmul! and lmul! methods for UniformScaling

### PR DESCRIPTION
**Pull request by dmbates**
As per https://discourse.julialang.org/t/in-place-multiplication-methods-for-uniformscaling-type/15837

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Thank you, Doug! Tests exercising this would be good as well.

**Comment by dmbates** [comment]
Why did I know that was coming? :smile:

**Comment by chriscoey** [comment]
🎉 I needed this one hour ago. Thanks!

**Comment by StefanKarpinski** [comment]
I know, it's a drag... we actually require tests these days.

**Comment by dmbates** [comment]
@StefanKarpinski I wasn't complaining.  I appreciate the fact that unit tests are part of the DNA of the Julia language.  Right after I clicked on the pull request button I though "Ah, I should add tests.".  Will do.

**Comment by dmbates** [comment]
I added tests.  Because these methods just call the corresponding method for `Number`, the tests are rather perfunctory - mostly to catch if I have made a spelling mistake.  Let me know if you want me to go full @kshyatt on it instead.

**Review by Sacha0 — APPROVED** [review]
Looks great! Thanks @dmbates! :)

**Pull request merged**
