### PR TITLE
Multiset Combinations, Multiset Permutations, K-Permutations and Combinations with Replacement.

### PR DESCRIPTION
**Pull request by randy3k**
Hi developers,

Four different arrangements are added:
1. Multiset Combinations
2. Combinations with Replacement.
3. Multiset Permutations
4. K-Permutations

Not sure if they should be placed in a separate package or should be merged to julia base. But I would love to put them in julia base.

I am not good at naming functions, please suggest better names for them if you have any ideas. It may also make sense to introduce abstract types `AbstractCombinations` and `AbstractPermutations` or even a super type `AbstractArrangement`.

Demo:

``` julia
julia> import Base: multiset_combinations, with_replacement_combinations, multiset_permutations

julia> collect(multiset_combinations("aabc", 2))
4-element Array{Array{Char,1},1}:
 ['a','a']
 ['a','b']
 ['a','c']
 ['b','c']

julia> collect(with_replacement_combinations("abc", 2))
6-element Array{Array{Char,1},1}:
 ['a','a']
 ['a','b']
 ['a','c']
 ['b','b']
 ['b','c']
 ['c','c']

julia> collect(multiset_permutations("aabc", 2))
7-element Array{Array{Char,1},1}:
 ['a','a']
 ['a','b']
 ['a','c']
 ['b','a']
 ['b','c']
 ['c','a']
 ['c','b']

julia> collect(permutations("abc", 2))
6-element Array{Array{Char,1},1}:
 ['a','b']
 ['a','c']
 ['b','a']
 ['b','c']
 ['c','a']
 ['c','b']
```

Details:

There are three new types: `MultiSetCombinations`, `WithReplacementCombinations`, `MultiSetPermutations`. For k-permutations, one more field is added to the `Permutations` type to store the value of k.

There are also two functions `nextpermutation` and  `nextpermutation0`. `nextpermutation0` is the actually not new, it is the original permutation algorithm used. The other function `nextpermutation` does permutations with multiset and k-permutations. I have tested the different permutation functions on n-permutations and there are not much differences.

``` julia
julia> @time collect(permutations("abcdefgh"));
   7.135 milliseconds (121 k allocations: 10395 KB)

julia> @time collect(multiset_permutations("abcdefgh", 8));
   7.675 milliseconds (121 k allocations: 10405 KB)
```

### CODE REVIEW

**Comment by tkelman** [comment]
I'd prefer putting this in DataStructures.jl or similar, if it isn't fundamental enough for other base code to depend on it.

**Comment by kmsquire** [comment]
How about submitting it to https://github.com/jiahao/Combinatorics.jl?

Cc: @jiahao

**Comment by randy3k** [comment]
It seems Combinatorics.jl is a good host. But I still think that the somehow the julia base should also support k-permutations given that there is k-combinations.

**Comment by jiahao** [comment]
These functions make more sense in a Combinatorics package. The trend has been to remove nonessential functions from Base.

**Comment by tkelman** [comment]
Does any other base code depend on the k-combinations features that are there now? If not we can think about (carefully) migrating that out of base eventually.

**Comment by randy3k** [comment]
I will submit a PR to Combinatorics.jl on multiset Combinations/permutations and combinations with replacement. But not sure what to do with k-permutations. Should go here or Combinatorics.jl?

**Comment by JeffBezanson** [comment]
Very nice, thanks! I do think this should go in Combinatorics.jl, and we should also move `combinations` and other similar Base functions into there.

**Comment by StefanKarpinski** [comment]
Agreed.

**Comment by randy3k** [comment]
Finally, I have the motivation to submit my commits to [Combinatorics](https://github.com/JuliaLang/Combinatorics.jl/pull/7). It should be closed now.

**Pull request closed without merging**
