### PR TITLE
[NewOptimizer] Get rid of use of broadcasting in compiler

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by mbauman** [comment]
Sorry I stole away your ability to do this!  We could probably re-instate these `setindex!(::Array, ::AbstractRange,  ::AbstractRange)` methods to be defined earlier in bootstrap if you want to be able to use this idiom here — it's not really broadcasting just `base/multidimensional.jl`.

**Comment by Keno** [comment]
I don't really care at the moment, just want to get the compiler un-broken.

**Comment by Keno** [comment]
Actually, yeah, let's define this earlier, there's a bunch of things that are also broken as a result of this, e.g. `vcat(::Vector{Int}, ::Vector{Int})`. Would you mind submitting a PR?

**Comment by mbauman** [comment]
#26968

**Pull request closed without merging**
