### PR TITLE
always obey inline declarations if the calling signature is concrete

### PR DESCRIPTION
**Pull request by JeffBezanson**
This implements the suggestion in
https://github.com/JuliaLang/julia/pull/27857#issuecomment-421109530

Will hopefully help e.g. https://github.com/JuliaArrays/StaticArrays.jl/pull/494

### CODE REVIEW

**Comment by KristofferC** [comment]
It indeed fixes https://github.com/JuliaArrays/StaticArrays.jl/pull/494. Awesome!

**Review by Keno — APPROVED** [review]

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29258#issuecomment-422849889) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9ba3f9ebb16edc4335f5fec7cc26bcd5fdf3088b/d10df6c_vs_d28a7d5/report.md). cc @ararslan

**Comment by andyferris** [comment]
Nice!

**Comment by oscardssmith** [comment]
Are the many regressions places to remove inlines or just noise?

**Pull request merged**
