### PR TITLE
Deprecate no-op transpose fallback instead of error'ing

### PR DESCRIPTION
**Pull request by Sacha0**
Ref. JuliaLang/LinearAlgebra.jl#257 and JuliaLang/julia#17075. cc @tkelman @andreasnoack. Thanks!

### CODE REVIEW

**Comment by andreasnoack** [comment]
Should probably also add a NEWS.md entry.

**Comment by Sacha0** [comment]
> Should probably also add a NEWS.md entry.

NEWS.md entry added. Thoughts? Thanks!

**Comment by tkelman** [comment]
> Thoughts?

I think you rock. Should have realized it was such a simple change.

**Comment by Sacha0** [comment]
> I think you rock. 

Why thank you sir! :blush: Not really though: I should have thought to deprecate the method rather than have it throw an error the first time around. Would have saved your and others' time and energy.

Whitespace issue fixed. Thanks again!

**Comment by tkelman** [comment]
Not sure what the Travis assertion failure is about, but most likely unrelated
```
julia: /home/travis/build/JuliaLang/julia/src/typemap.c:862: jl_typemap_level_assoc_exact: Assertion `(((jl_value_t*)(((jl_taggedvalue_t*)((char*)(ty) - sizeof(jl_taggedvalue_t)))->header & ~(uintptr_t)15))==(jl_value_t*)(jl_datatype_type))' failed.
```

**Comment by Sacha0** [comment]
Thanks!

**Comment by StefanKarpinski** [comment]
Uh, this maybe should have waited a bit longer...

**Comment by StefanKarpinski** [comment]
Ah, sorry, I thought this was removing the fallback.

**Comment by tkelman** [comment]
which part?

**Pull request merged**
