### PR TITLE
Add clamp!(array, lo, hi)

### PR DESCRIPTION
**Pull request by alyst**
Vectorized in-place `clamp!()`

### CODE REVIEW

**Comment by alyst** [comment]
Does the addition of `clamp!()` make sense or there are some concerns?

**Comment by pao** [comment]
I think the question would be the perennial vectorization question--is this better expressed as `map!(x->clamp(x,lo,hi), arr)`?

**Comment by timholy** [comment]
It's not quite the same question, because we already have `clamp(::AbstractArray, lo, hi)`. I will merge in 24 hours if (1) I remember (feel free to bump again) and (2) no one complains in the meantime about another exported name.

**Comment by pao** [comment]
Wait, does that mean `clamp` is array-only then? That seems odd (though I agree that it may be the most common use case.)

**Comment by alyst** [comment]
No, there is scalar `clamp()` as well.
IMHO `map!()` or for-loop should be the recommended approach an arbitrary transformation. But `clamp()` (as well as `min()` and `max()`) is frequently used to ensure that values are in the valid range, so it's worth to make an exception for this sort of "almost identity" transform.

**Comment by tkelman** [comment]
The tests are nice, though exports should probably be documented. Little silly since this is only 3 lines of code, but this probably falls under the category of functions that Jeff will gleefully deprecate once map is fast.

**Comment by StefanKarpinski** [comment]
I'm generally loathe to add exports, but this is a very handy in-place function. Tempted to merge.

**Comment by timholy** [comment]
I think it's consistent with some of our other choices like `maximum!`

**Comment by timholy** [comment]
Thanks, @alyst!

**Comment by timholy** [comment]
(Keep in mind it might go away again once `map!(x->clamp(x, a, b), A)` becomes fast.)

**Comment by alyst** [comment]
@timholy Thanks for merging!

**Comment by tkelman** [comment]
And it should be documented somewhere.

**Pull request merged**
