### PR TITLE
micro: improve bench, fix cgo build and isolate

### PR DESCRIPTION
**Pull request by kortschak**
- Use .so instead of .a,
- Use local GOPATH to prevent contaminating client GOPATH,
- Use strconv.FormatUint instead of fmt.Sprintf,
- Make noise for bench errors.

@jiahao

### CODE REVIEW

**Comment by jiahao** [comment]
:+1:

**Comment by jiahao** [comment]
I just tried this again on a clean copy of `release-0.4` and cannot get the shared library version to link correctly. There are numerous undefined reference errors of the form

```
/tmp/go-build807365913/github.com/gonum/blas/cgo/_obj/blas.cgo2.o: In function `_cgo_5665df3ba697_Cfunc_cblas_zscal':
gopath/src/github.com/gonum/blas/cgo/blas.go:2605: undefined reference to `cblas_zscal'
```

Also it turns out that `make clean` is leaving git objects in `./gopath/.git`, so I will have to modify the makefile rule to delete the entire `./gopath` directory instead of `./gopath/*`.

**Comment by jiahao** [comment]
Can you elaborate on what errors you are seeing with the statically linked version? When I tested again on a clean repo I couldn't get the build to work on the test machine with the dynamically linked version, but the statically linked form works fine.

**Comment by tkelman** [comment]
might be the fact that we rename symbols in openblas

**Comment by kortschak** [comment]
No, it was f7eeb1a9f33f9d62582a044cd4df7534770c0cea. This breaks the build since it is pointing to the wrong level of the tree.

The error I get when using the .a is a segfault, but I can replicate the error in https://github.com/JuliaLang/julia/pull/13262#issuecomment-142429900 by making the change in the ref above.

Reproduced interactively here:
```
~/Development/julia/test/perf/micro [fix-go-perf*]$ CGO_LDFLAGS="/home/daniel/Development/julia/deps/openblas/libopenblas.a -lm" go get github.com/gonum/blas/cgo
~/Development/julia/test/perf/micro [fix-go-perf*]$ go get github.com/gonum/matrix/mat64
~/Development/julia/test/perf/micro [fix-go-perf*]$ go get github.com/gonum/stat
~/Development/julia/test/perf/micro [fix-go-perf*]$ go run perf.go 
go,fib,0.07413145225
go,parse_int,0.1875474161
go,mandel,0.34414741960000006
go,quicksort,0.5584646626666667
go,pi_sum,39.6906305
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x9ae532]

runtime stack:
runtime.throw(0x1c8ef40, 0x2a)
	/home/daniel/Development/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/home/daniel/Development/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 37 [syscall, locked to thread]:
runtime.cgocall(0x4789f0, 0xc820047428, 0x0)
	/home/daniel/Development/go/src/runtime/cgocall.go:120 +0x11b fp=0xc8200473d8 sp=0xc8200473a8
github.com/gonum/blas/cgo._Cfunc_cblas_dgemm(0x7000000065, 0x140000006f, 0x500000014, 0x3ff0000000000000, 0xc820078000, 0x14, 0xc820078000, 0x14, 0x0, 0xc8204a2000, ...)
	github.com/gonum/blas/cgo/_obj/_cgo_gotypes.go:809 +0x35 fp=0xc820047428 sp=0xc8200473d8
github.com/gonum/blas/cgo.Implementation.Dgemm(0x70, 0x6f, 0x14, 0x14, 0x5, 0x3ff0000000000000, 0xc820078000, 0x64, 0x64, 0x14, ...)
	/home/daniel/Development/julia/test/perf/micro/gopath/src/github.com/gonum/blas/cgo/blas.go:2877 +0x397 fp=0xc820047498 sp=0xc820047428
github.com/gonum/blas/cgo.(*Implementation).Dgemm(0x20140c8, 0x70, 0x6f, 0x14, 0x14, 0x5, 0x3ff0000000000000, 0xc820078000, 0x64, 0x64, ...)
	<autogenerated>:119 +0x1a6 fp=0xc820047538 sp=0xc820047498
github.com/gonum/blas/blas64.Gemm(0x70, 0x6f, 0x3ff0000000000000, 0x5, 0x14, 0x14, 0xc820078000, 0x64, 0x64, 0x5, ...)
	/home/daniel/Development/julia/test/perf/micro/gopath/src/github.com/gonum/blas/blas64/blas64.go:364 +0x140 fp=0xc8200475e0 sp=0xc820047538
github.com/gonum/matrix/mat64.(*Dense).Mul(0xc820014840, 0x7f8294410140, 0xc82000a090, 0x7f82944100b8, 0xc820014340)
	/home/daniel/Development/julia/test/perf/micro/gopath/src/github.com/gonum/matrix/mat64/dense_arithmetic.go:365 +0x4d7 fp=0xc820047d50 sp=0xc8200475e0
main.randmatstat(0x3e8, 0xc806bd8474, 0x1feb120)
	/home/daniel/Development/julia/test/perf/micro/perf.go:120 +0xbcc fp=0xc820047ef8 sp=0xc820047d50
main.glob.func6(0xc820092100)
	/home/daniel/Development/julia/test/perf/micro/perf.go:295 +0x3d fp=0xc820047f30 sp=0xc820047ef8
testing.(*B).runN(0xc820092100, 0x1)
	/home/daniel/Development/go/src/testing/benchmark.go:124 +0x9a fp=0xc820047f50 sp=0xc820047f30
testing.(*B).launch(0xc820092100)
	/home/daniel/Development/go/src/testing/benchmark.go:199 +0x63 fp=0xc820047fa8 sp=0xc820047f50
runtime.goexit()
	/home/daniel/Development/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820047fb0 sp=0xc820047fa8
created by testing.(*B).run
	/home/daniel/Development/go/src/testing/benchmark.go:179 +0x54

goroutine 1 [chan receive]:
testing.(*B).run(0xc820092100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/Development/go/src/testing/benchmark.go:180 +0x7b
testing.Benchmark(0x1ca7470, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/Development/go/src/testing/benchmark.go:465 +0xc7
main.runBenchmarkFor(0x1ca7470, 0x6, 0x0, 0x0)
	/home/daniel/Development/julia/test/perf/micro/perf.go:218 +0x47
main.main()
	/home/daniel/Development/julia/test/perf/micro/perf.go:209 +0xda

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/daniel/Development/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
```

**Comment by kortschak** [comment]
>Also it turns out that make clean is leaving git objects in ./gopath/.git, so I will have to modify the makefile rule to delete the entire ./gopath directory instead of ./gopath/*.

It's entirely unclear to me how this is happening. go get will cause git to checkout `github.com/gonum/...` paths each with a .git at their root. There should be no .git in gopath.

**Comment by jiahao** [comment]
Huh. There is no `libopenblas.so` in `$(JULIAHOME)/deps` so I'm not sure why passing that to `-L` would have worked. But I did try with f7eeb1a reverted and it worked. I'll put in a fix.

Regarding the error you get when linking statically, is this a Mac OS X machine you see the error on? One thing we do that is a little unusual is we compile OpenBLAS with the 64-bit integer interface by default. Could that be an issue for the go compiler?  (I'm not sure why this would only be a problem when linking statically...)

> go get will cause git to checkout github.com/gonum/... paths each with a .git at their root. There should be no .git in gopath.

I observe this behavior in `bash`. In `zsh` it appears that somehow expanding the `gopath/*` glob misses some of the `gopath/src/*/.git` targets for some reason (not `gopath/.git` as I said earlier). Not sure why. Anyway since `./gopath` is only created for the purpose of running the test I think it makes sense to wipe the entire thing on a `make clean` anyway.

**Comment by kortschak** [comment]
>Huh. There is no libopenblas.so in $(JULIAHOME)/deps so I'm not sure why passing that to -L would have worked. But I did try with f7eeb1a reverted and it worked. I'll put in a fix.

I think I have an explanation for this. And it's not a happy one. I am guessing you have a libopenblas.so somewhere in a standard location as well. This is being linked since there is (as you correctly say) no libopenblas.so in .../julia/deps. I have confirmed this here by nuking my system-wide openblas install.

It seems that since I'm the only one that is having troubles with the static linking, you should go with that. When I have several hours to spare (I kid), I will compile julia on the more recent install and confirm it works.

>is this a Mac OS X machine you see the error on?

No, this is an ubuntu box, though old (12.04). I spent some time on another more recent install this morning, but I only have so much time, and compiling julia from scratch is just too slow.

>Anyway since ./gopath is only created for the purpose of running the test I think it makes sense to wipe the entire thing on a make clean anyway.

No worries, so long as you create it before trying the Go package build steps. (also using bash).

**Comment by tkelman** [comment]
We have binaries with a compiled openblas included in them: https://s3.amazonaws.com/julialang/bin/linux/x64/0.4/julia-0.4.0-rc2-linux-x86_64.tar.gz

**Comment by kortschak** [comment]
OK, cool. I have a look later. Thanks.

**Comment by kortschak** [comment]
Just had a look at that tarball and it doesn't have the deps needed to test this problem - there is no libopenblas.a. If there were a way to just build the OpenBLAS dep, that would be fine (preferably only building for the local arch - when I tried this morning it seemed to want to build for everything ever constructed and then didn't leave an artifact for me).

**Comment by tkelman** [comment]
Ah sorry we only ship shared libraries in our tarballs.

`make -C deps install-openblas OPENBLAS_TARGET=...`

**Comment by kortschak** [comment]
Confirm on trusty with 4.8.4, still segfaults with the static linking. The invocation above still takes ~30minutes and seems to build against all targets. I give up.

**Comment by tkelman** [comment]
I originally had a typo but the edited version is supposed to work. Will look into it.

Can gonum use an ILP64 blas?

**Comment by btracey** [comment]
I don't know much about ILP. Does it have a C interface? We use the C interface because Go is row major. If so, then we should be able to use it. We have used ATLAS, MKL, OpenBLAS, and Accelerate at various times. We have an extensive BLAS testing suite, and It's worth checking that the alternate installations behave correctly. We've found a bunch of bugs in BLAS and LAPACK. I'd imagine matrix multiplication is fine, and that's all that's needed for this benchmark, but it's worth verifying.

**Comment by tkelman** [comment]
by ILP64 I mean 64 bit integer size convention, I think corresponding to the INTERFACE variable when you build openblas

**Comment by btracey** [comment]
Ah. Sorry, when I tried searching all that came up were MKL pages and I assumed the "I" was Intel.

In theory we could use it, but our wrapper casts to int. https://github.com/gonum/blas/blob/master/cgo/blas.go#L2877

**Comment by jiahao** [comment]
I suspect now a 64 bit BLAS interface issue. Julia also segfaults doing linear algebra when there is a integer size mismatch.

**Pull request merged**
