### PR TITLE
release-1.7: Backports for 1.7.0/1.7.0-rc4

### LINKED ISSUE #43008: 1.7.0-rc2: StackOverflowError with complex-valued matrix exp
On macos, using version `1.7.0-rc2`, julia just shows `StackOverflowError` with no other info when taking the matrix exp with a ~ 300x300 complex-valued matrix. Minimum example:

```
using LinearAlgebra

n = 300
m = rand(ComplexF64, n, n);
mex = exp(m);
```

Alro ran with `--startup-file=no` to make sure it's not some clash with other packages.

Screen Shot 2021-11-08 at 5 52 35 PM

my `versioninfo()`:

```
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_MATHLINK = /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework
  JULIA_MATHKERNEL = /Applications/Mathematica.app/Contents/MacOS/MathKernel
```

Same code runs fine with `Version 1.6.3 (2021-09-23)`.

Hardware: Macbook pro (intel) with 16 GB ram, activity monitor shows low memory usage. 

In addition, the same code sometimes gives `ERROR: LoadError: ReadOnlyMemoryError()`, not sure how to reproduce that one...

Thanks!

### LINKED ISSUE #43199: Some links to source in the stdlib documentation broken
E.g.: this leads to 404 error:

- got to https://docs.julialang.org/en/v1/stdlib/Statistics/
- mouse over bottom right of the box Statistics.std
- click 'Source'

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #42334 
- [x] #43042 
- [x] #43029 
- [x] #43005 
- [x] #42978 
- [x] #43093 
- [x] #43096 
- [x] #42481 
- [x] #43100 
- [x] #42585 
- [x] #43120 
- [x] #43090 
- [x] #43168 
- [x] #43225 
- [x] #43092 
- [x] #43188 
- [x] #43219 
- [x] #43226
- [x] #42725 
- [x] #43163 
- [x] #41206

<details>
<summary>Backported CI PRs:</summary>

- [x] #43003 
- [x] #43073 
</details>

Need manual backport:

Non-merged PRs with backport label:
- [ ] #43047 
- [ ] #42736 
- [ ] #42715 
- [ ] #42339 
- [ ] #42311 
- [ ] #42239 <!-- [Distributed] Make worker state variable threadsafe -

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.7")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.7")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/43084#issuecomment-979768627):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/109d724_vs_3348de4/report.md

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43084#issuecomment-979768516) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8906af3_vs_3348de4/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BytePairEncoding", "CategoricalDistributions", "CombinatorialSpaces", "DataDeps", "ElasticArrays", "ExtendableGrids", "Fread", "Glimmer", "GridapPardiso", "ImageInTerminal", "KeplerTools", "LazyBandedMatrices", "MLJParticleSwarmOptimization", "MemPool", "MeshPorter", "Minio", "OMEinsum", "OdsIO", "ParquetFiles", "Photometry", "Publish", "Reactive", "RemoteFiles", "SOM", "SimpleBufferStream", "StaticKernels", "TreeViewWidget", "VoronoiDelaunay"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43084#issuecomment-980334637) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/727feea_vs_3348de4/report.md).

**Pull request merged**
