### PR TITLE
Update libosxunwind to v0.0.4

### LINKED ISSUE #29912: Cannot build Julia with clang from XCode 10
Issue: https://github.com/JuliaLang/libosxunwind/issues/11
Attempt at a fix: https://github.com/JuliaLang/libosxunwind/pull/12

Would it be possible to build libosxunwind using BinaryBuilder instead? Then I can avoid going through the `libosxunwind` repo which appears to be abandoned.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #29912.

### CODE REVIEW

**Comment by ararslan** [comment]
It sure would be nice to have working macOS CI for this.

**Comment by iamed2** [comment]
Is there an open issue for the macOS CI or is this a new problem?

**Comment by ararslan** [comment]
It's relatively new, not introduced here, but I don't think there's an open issue for it. Not sure what the issue actually is. Looking at the raw Travis log, the build and all tests actually completed successfully.

**Comment by ararslan** [comment]
Looks like macOS CI is working again, and tests here are passing on it.

**Comment by StefanKarpinski** [comment]
Cool, any reason not to merge?

**Comment by ararslan** [comment]
Not as far as I'm concerned, just figured having another set of eyes on it before we bump a dependency version would be worthwhile. The changes in this most recent tag of libosxunwind are incredibly minimal though.

**Comment by StefanKarpinski** [comment]
This is causing build problems on macOS, specifically:
```
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command
      line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
src/libuwind.cxx:28:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
1 warning and 1 error generated.
make[2]: *** [src/libuwind.cxx.o] Error 1
make[1]: *** [scratch/libosxunwind-0.0.4/build-compiled] Error 2
make: *** [julia-deps] Error 2
```

**Comment by staticfloat** [comment]
What version of MacOS and what version of Xcode do you have installed?

**Comment by StefanKarpinski** [comment]
10.14.1 and I have updated all the things.

**Comment by staticfloat** [comment]
PR to fix this in libosxunwind is here: https://github.com/JuliaLang/libosxunwind/pull/14

**Comment by wsshin** [comment]
I ran into this problem while building Julia 0.7 on a new Mac as @staticfloat pointed out.  Couldn't figure out how to solve it (because I had no problem building 0.7 on my previous Mac).  After reading this thread I tried building master and it succeeded.

Is it possible to backport this fix to 0.7?  I still prefer using 0.7 to get deprecation warnings.

**Comment by ViralBShah** [comment]
As of now, there are no new 0.7 releases planed.

**Comment by ararslan** [comment]
You should be able to use the official 0.7 binaries for Mac available at https://julialang.org/downloads.

**Pull request merged**
