### PR TITLE
Backports for Julia 1.5-RC1 (or beta2)

### LINKED ISSUE #36031: Printf bug for BigInt
The following fails on master, as well as 1.4:
```
julia> using Printf

julia> @printf "%.5e" big(10)
ERROR: MethodError: no method matching decode_dec(::BigInt)
Closest candidates are:
  decode_dec(::BigInt, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:932
  decode_dec(::Integer, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:892
  decode_dec(::Real, ::Any) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:855
  ...
Stacktrace:
 [1] ini_dec(::BigInt, ::Int64, ::Array{UInt8,1}) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:1062
 [2] ini_dec(::Base.TTY, ::BigInt, ::Int64, ::String, ::Int64, ::Int64, ::Char, ::Array{UInt8,1}) at /home/simeon/Documents/Julia/julia/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:845
 [3] top-level scope at REPL[6]:1
```
It seems like `decode_dec(::BigInt)` calls a method that does not exist.

### LINKED ISSUE #36104: Referring to `Foo.F` inside struct `F` defined in module `Foo` now errors with UndefVar error
```jl
module Foo
    struct F
        v::Foo.F
    end
end
```

Works in 1.4, errors in 1.5 with

```
ERROR: UndefVarError: F not defined
```

From PkgEval on 1.5 (https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/logs/Persa/1.5.0-DEV-f11a73bd9c.log).

### LINKED ISSUE #36108: Printing of multiplication and vs. UInt16 etc.
This is a bit odd:
```julia
julia> :(2 * a)
:(2a)

julia> 2a
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope at REPL[6]:1

julia> :(0x0 * a)
:(0x00a)

julia> 0x00a == 10
true
```
From here: https://discourse.julialang.org/t/not-clear-what-0-01f0x-is-in-the-flux-docs/40553/4

### LINKED ISSUE #36116: diff on some ranges now error
```jl
julia> diff(0:2)
ERROR: ArgumentError: step cannot be zero
Stacktrace:
 [1] steprange_last(::Int64, ::Int64, ::Int64) at ./range.jl:215
 [2] StepRange at ./range.jl:205 [inlined]
 [3] _rangestyle at ./range.jl:118 [inlined]
 [4] _range at ./range.jl:116 [inlined]
 [5] #range#43 at ./range.jl:91 [inlined]
 [6] -(::UnitRange{Int64}, ::UnitRange{Int64}) at ./range.jl:1044
 [7] broadcasted at ./broadcast.jl:1081 [inlined]
 [8] broadcasted at ./broadcast.jl:1263 [inlined]
 [9] diff(::UnitRange{Int64}; dims::Int64) at ./multidimensional.jl:849
 [10] diff(::UnitRange{Int64}) at ./multidimensional.jl:809
 [11] top-level scope at REPL[3]:1

julia> diff(collect(0:2))
2-element Array{Int64,1}:
 1
 1
```

In 1.4, both of these gave a consistent answer.

From PkgEval for 1.5 (https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/logs/ContinuumArrays/1.5.0-DEV-f11a73bd9c.log).

### LINKED ISSUE #36272: Error with optional argument in anonymous function defined in macro
In Julia 1.5.0 beta 1, the following fails:
```julia
macro m()
    :((a, b=1) -> a*b)
end
@m()(1)
```
with
```
ERROR: UndefVarError: b not defined
Stacktrace:
 [1] (::var"#1#2")(::Int64, ::Int64) at ./REPL[1]:3 (repeats 2 times)
 [2] top-level scope at REPL[1]:3
```

The reason I want to do this is here: https://github.com/JuliaPOMDP/POMDPs.jl/blob/609fe87094d4b1b01993deb0514565450266547f/src/generative.jl#L189. A workaround is to name the function.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #35232 - LibGit2: add resolve_url to RemoteCallbacksStruct for LibGit2 0.99.0
- [x] #36033 - fix #36031: Printf bug for BigInt
- [x] #36061 - Update armv7l `-d16` -> `+d32` feature change for LLVM 9+
- [x] #36070 - rename pop!(vector, idx, [default]) to popat!
- [x] #36046 - Fix a bug with break/continue/return in at-testset begin end
- [x] #36076 - clarify `show` doc strings
- [x] #36096 - Revert "Use norm instead of abs in generic lu factorization (#34575)"
- [x] #36117 - fix #36116, diff(::AbstractRange) returns an Array
- [x] #36122 - fix #36108, printing invalid numeric juxtapositions
- [x] #36126 - Fix mkpath error handling
- [x] #36121 - fix #36104, assign global name during type definitions
- [x] #36113 - Fix zero(::Type{TwicePrecision}) for dimensionful quantities
- [x] #36074 - Fix equality for one-element ranges
- [x] #36143 - fix ImmutableDict(pairs...) constructor
- [x] #36115 - inference: ignore badly behaving generated functions
- [x] #36059 - Rename AddrSpacePtr
- [x] #36152 - Mark Tuples with Bottom among their parameters as cacheable
- [x] #36187 - Allow non-Function callables to be used in count(f, itr)
- [x] #36273 - fix #36272: Error with optional argument in anonymous function defined in macro 
- [x] #35281 - Fix Broadcasting of Bidiagonal
- [x] #36279 - Promote on Rational binary operations
- [x] #36305 - Remove `init` from `count!` docstring
- [x] #36231 - deleteat! : check bounds for the first passed index
- [x] #36336 - Switch `httpbin` tests over to JuliaLang-hosted `httpbin` mock server
- [x] #35976 - more precise inference of `splatnew`

Non-merged PRs with backport label:
- [ ] #35929 - Remove unnecessary restriction to `StridedVecOrMat`

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AMRVW", "AdvancedHMC", "ArchGDAL", "ArrayLayouts", "AugmentedGaussianProcesses", "AutoPreallocation", "AxisIndices", "BangBang", "BlockArrays", "BloomFilters", "Bridge", "CBindingGen", "CUDAatomics", "CancerSeqSim", "ChainRulesCore", "Chemfiles", "ClinicalTrialUtilities", "ColorVectorSpace", "CompScienceMeshes", "ContinuumArrays", "CoverageCore", "CoverageTools", "CurveProximityQueries", "DRIPs", "DataAssim", "DataFlow", "DimensionalData", "DirectGaussianSimulation", "DistributedArrays", "Diversity", "Documenter", "EfficientGlobalOptimization", "ExprRules", "ExtensibleUnions", "FEMBase", "FEMBasis", "FIGlet", "FastIOBuffers", "FillArrays", "FunctionalCollections", "FunctionalTables", "GeometryTypes", "Gtk", "GtkReactive", "GtkUtilities", "HomotopyContinuation", "ImageInpainting", "ImageView", "Immerse", "InfiniteArrays", "InspectDR", "IntervalArithmetic", "JLD2", "JSONSchema", "JuliaVariables", "KrigingModel", "LazyStack", "Lerche", "LibGEOS", "LinearMapsAA", "LocalRegistry", "MCHammer", "MIToS", "MLStyle", "Manifolds", "Maxvol", "MbedTLS", "Miletus", "MultiplesOfPi", "NTFk", "Nabla", "NarrativeTest", "NiLangCore", "OceanGrids", "OpenEphysLoader", "OptionalArgChecks", "PassiveTracerFlows", "Persa", "PlotUtils", "Plots", "Polymake", "PowerDynSolve", "ProfileView", "QuantumOpticsBase", "QuartetNetworkGoodnessFit", "QuasiArrays", "RecursiveArrayTools", "RevealedPreferences", "RigidBodyDynamics", "RoMEPlotting", "SimpleGF2", "StaticArrays", "StaticNumbers", "StratiGraphics", "StructuralInheritance", "TaylorIntegration", "TensorKitManifolds", "ThreePhasePowerModels", "TikzQTrees", "Turf", "TuringModels", "TwoFAST", "VarStructs", "VerTeX", "Winston", "Wrangling", "XLSXasJSON"], vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/36098#issuecomment-636759047) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/855707f48423877451c573e3e23d7be2d85be12b/pkgeval/by_hash/53f0393_vs_b5f13c3/report.md). cc @maleadt

**Comment by rfourquet** [comment]
@KristofferC I pushed a commit to update the NEWS entry for `popat!` to this branch. I hope this is OK, otherwise please tell me where I should have pushed it.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AMRVW", "AdvancedHMC", "ArchGDAL", "ArrayLayouts", "AugmentedGaussianProcesses", "AutoPreallocation", "AxisIndices", "BlockArrays", "BloomFilters", "Bridge", "CBindingGen", "CUDAatomics", "CancerSeqSim", "ChainRulesCore", "Chemfiles", "ClinicalTrialUtilities", "ColorVectorSpace", "CompScienceMeshes", "ContinuumArrays", "CoverageCore", "CoverageTools", "CurveProximityQueries", "DataAssim", "DataFlow", "DimensionalData", "DirectGaussianSimulation", "DistributedArrays", "Diversity", "Documenter", "EfficientGlobalOptimization", "ExprRules", "ExtensibleUnions", "FEMBase", "FEMBasis", "FIGlet", "FastIOBuffers", "FillArrays", "FunctionalCollections", "FunctionalTables", "GeometryTypes", "Gtk", "GtkReactive", "GtkUtilities", "HomotopyContinuation", "ImageInpainting", "ImageView", "Immerse", "InspectDR", "IntervalArithmetic", "JLD2", "JSONSchema", "JuliaVariables", "KrigingModel", "LazyStack", "LinearMapsAA", "LocalRegistry", "MCHammer", "MIToS", "MLStyle", "Manifolds", "Maxvol", "MbedTLS", "Miletus", "MultiplesOfPi", "NTFk", "Nabla", "NiLangCore", "OceanGrids", "OpenEphysLoader", "OptionalArgChecks", "PassiveTracerFlows", "Persa", "PlotUtils", "Plots", "Polymake", "PowerDynSolve", "ProfileView", "QuantumOpticsBase", "QuartetNetworkGoodnessFit", "QuasiArrays", "RecursiveArrayTools", "RevealedPreferences", "RigidBodyDynamics", "RoMEPlotting", "SimpleGF2", "StaticArrays", "StaticNumbers", "StratiGraphics", "StructuralInheritance", "TaylorIntegration", "TensorKitManifolds", "ThreePhasePowerModels", "TikzQTrees", "Turf", "TuringModels", "TwoFAST", "VarStructs", "VerTeX", "Winston", "XLSXasJSON"], vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/36098#issuecomment-639291621) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/680e2355355927aeac1c26154cc0aca38b5c13e6/pkgeval/by_hash/bf34e0a_vs_b5f13c3/report.md). cc @maleadt

**Pull request merged**
