### PR TITLE
release-1.7: Backports for 1.7.1

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #43196 
- [x] #43251 
- [x] #43264 
- [x] #42339 
- [x] #43306 
- [x] #43298 
- [x] #43359 
- [x] #43381 
- [x] #43361 

Need manual backport:
- [ ] #43276 

Non-merged PRs with backport label:
- [ ] #43347 
- [ ] #42736 
- [ ] #42715 
- [ ] #42311 
- [ ] #42239 <!-- [Distributed] Make worker state variable threadsafe -

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43297#issuecomment-990238800) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a1dd801_vs_d73f2a7/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43297#issuecomment-990722522) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a1dd801_vs_3bf9d17/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BioServices", "BrokenRecord", "COBREXA", "Dance", "DistributedArrays", "DistributedData", "FaultDetectionTools", "GaussBP", "GigaSOM", "GraphBasedSystems", "LoopThrottle", "MATDaemon", "MCPhyloTree", "MPIClusterManagers", "Merly", "PProf", "ParallelOperations", "Pathfinder", "PhysicalTrees", "ProgressiveHedging", "QuantumPropagators", "ReverseDiff", "RuntimeGeneratedFunctions", "SetIntersectionProjection", "SpectralDistances", "StaticKernels", "TexasHoldem", "Theta"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43297#issuecomment-991261253) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/a1dd801_vs_3bf9d17/report.md).

**Comment by KristofferC** [comment]
Let's try again with #42339 dropped

@nanosoldier `runtests(["BioServices", "BrokenRecord", "COBREXA", "Dance", "DistributedArrays", "DistributedData", "FaultDetectionTools", "GaussBP", "GigaSOM", "GraphBasedSystems", "LoopThrottle", "MATDaemon", "MCPhyloTree", "MPIClusterManagers", "Merly", "PProf", "ParallelOperations", "Pathfinder", "PhysicalTrees", "ProgressiveHedging", "QuantumPropagators", "ReverseDiff", "RuntimeGeneratedFunctions", "SetIntersectionProjection", "SpectralDistances", "StaticKernels", "TexasHoldem", "Theta"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43297#issuecomment-991503937) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/0a921be_vs_3bf9d17/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BioServices", "BrokenRecord", "COBREXA", "Dance", "DistributedArrays", "DistributedData", "FaultDetectionTools", "GaussBP", "GigaSOM", "GraphBasedSystems", "LoopThrottle", "MATDaemon", "MCPhyloTree", "MPIClusterManagers", "Merly", "PProf", "ParallelOperations", "Pathfinder", "PhysicalTrees", "ProgressiveHedging", "QuantumPropagators", "ReverseDiff", "RuntimeGeneratedFunctions", "SetIntersectionProjection", "SpectralDistances", "StaticKernels", "TexasHoldem", "Theta"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/43297#issuecomment-991759981) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/7599df4_vs_3bf9d17/report.md).

**Pull request merged**
