### PR TITLE
When accessing the data pointer for an array, first decay it to a Derived Pointer

### LINKED ISSUE #54266: segfault in `jl_datatype_layout` while constructing `Memory`
Reproducer, for both v1.11.0-beta1 and nightly:

```julia
module FixedSizeArrays

struct Internal end

struct FixedSizeArray{T,N} <: DenseArray{T,N}
    mem::Memory{T}
    size::NTuple{N,Int}
    function FixedSizeArray{T,N}(::Internal, mem::Memory{T}, size::NTuple{N,Int}) where {T,N}
        new{T,N}(mem, size)
    end
end

function FixedSizeArray{T,N}(::UndefInitializer, size::NTuple{N,Int}) where {T,N}
    FixedSizeArray{T,N}(Internal(), Memory{T}(undef, checked_dims(size)), size)
end
function FixedSizeArray{T,N}(::UndefInitializer, size::Vararg{Int,N}) where {T,N}
    FixedSizeArray{T,N}(undef, size)
end
function FixedSizeArray{T}(::UndefInitializer, size::Vararg{Int,N}) where {T,N}
    FixedSizeArray{T,N}(undef, size)
end
function FixedSizeArray{T}(::UndefInitializer, size::NTuple{N,Int}) where {T,N}
    FixedSizeArray{T,N}(undef, size)
end

Base.IndexStyle(::Type{<:FixedSizeArray}) = IndexLinear()
Base.getindex(A::FixedSizeArray, i::Int) = A.mem[i]
Base.setindex!(A::FixedSizeArray, v, i::Int) = A.mem[i] = v

Base.size(a::FixedSizeArray) = getfield(a, :size)

function Base.similar(::FixedSizeArray, ::Type{S}, size::NTuple{N,Int}) where {S,N}
    FixedSizeArray{S,N}(undef, size...)
end

# safe product of a tuple of integers, for calculating dimensions size

checked_dims_impl(a::Int, ::Tuple{}, have_overflow::Bool) = (a, have_overflow)
function checked_dims_impl(a::Int, t::Tuple{Int,Vararg{Int,N}}, have_overflow::Bool) where {N}
    b = first(t)
    (m, o) = Base.Checked.mul_with_overflow(a, b)
    r = Base.tail(t)::NTuple{N,Int}
    checked_dims_impl(m, r, have_overflow | o)::Tuple{Int,Bool}
end

checked_dims(::Tuple{}) = 1
function checked_dims(t::Tuple{Int,Vararg{Int,N}}) where {N}
    any_is_zero     = any(iszero,                 t)::Bool
    any_is_negative = any((x -> x < false),       t)::Bool
    any_is_typemax  = any((x -> x == typemax(x)), t)::Bool
    a = first(t)
    r = Base.tail(t)::NTuple{N,Int}
    (product, have_overflow) = checked_dims_impl(a, r, false)::Tuple{Int,Bool}
    if any_is_negative
        throw(ArgumentError("array dimension size can't be negative"))
    end
    if any_is_typemax
        throw(ArgumentError("array dimension size can't be the maximum representable value"))
    end
    if have_overflow & !any_is_zero
        throw(ArgumentError("array dimensions too great, can't represent length"))
    end
    product
end

# broadcasting

function Base.BroadcastStyle(::Type{<:FixedSizeArray})
    Broadcast.ArrayStyle{FixedSizeArray}()
end

function Base.similar(
    bc::Broadcast.Broadcasted{Broadcast.ArrayStyle{FixedSizeArray}},
    ::Type{E},
) where {E}
    similar(FixedSizeArray{E}, axes(bc))
end

# helper functions

parent_type(::Type{<:FixedSizeArray{T}}) where {T} = Memory{T}

memory_of(m::Memory) = m
memory_of(f::FixedSizeArray) = f.mem

first_linear_index(a) = first(eachindex(IndexLinear(), a))

axes_are_one_based(axes) = all(isone ∘ first, axes)

# converting constructors for copying other array types

function FixedSizeArray{T,N}(src::AbstractArray{S,N}) where {T,N,S}
    axs = axes(src)
    if !axes_are_one_based(axs)
        throw(DimensionMismatch("source array has a non-one-based indexing axis"))
    end
    # Can't use `Base.size` because, according to it's doc string, it's not
    # available for all `AbstractArray` types.
    size = map(length, axs)
    dst = FixedSizeArray{T,N}(undef, size)
    copyto!(dst, src)::FixedSizeArray{T,N}
end

FixedSizeArray{T}(a::AbstractArray{<:Any,N})   where {T,N} = FixedSizeArray{T,N}(a)
FixedSizeArray{<:Any,N}(a::AbstractArray{T,N}) where {T,N} = FixedSizeArray{T,N}(a)
FixedSizeArray(a::AbstractArray{T,N})          where {T,N} = FixedSizeArray{T,N}(a)

# conversion

Base.convert(::Type{T}, a::T) where {T<:FixedSizeArray} = a
Base.convert(::Type{T}, a::AbstractArray) where {T<:FixedSizeArray} = T(a)::T

end # module FixedSizeArrays


# creates nested vectors
rand_nested_vec(::Tuple{}) = rand()
function rand_nested_vec(size::Tuple{Vararg{Int}})
  [rand_nested_vec(Base.tail(size)) for _ ∈ Base.OneTo(first(size))]::Vector
end

# converts nested vectors to other `AbstractArray` types
recursive_array_convert(::Type{T}) where {T} = a -> recursive_array_convert(T, a)
recursive_array_convert(::Type, a) = a
function recursive_array_convert(::Type{T}, a::AbstractArray) where {T}
  t = map(recursive_array_convert(T), a)
  T(t)::T
end

f(a) = map(+, a, a)

data = recursive_array_convert(FixedSizeArrays.FixedSizeArray, rand_nested_vec((100, 10, 100)));

iter_cnt = 1000  # when lowered to, e.g., 30, the bug doesn't reproduce each time

for _ ∈ 1:iter_cnt
  f(data)
end
```

Backtrace with `-g2 --check-bounds=yes`:

```
julia> for _ ∈ 1:iter_cnt
         f(data)
       end

[150999] signal 11 (1): Segmentation fault
in expression starting at REPL[11]:1
jl_datatype_layout at /cache/build/builder-amdci5-3/julialang/julia-master/src/julia.h:1366 [inlined]
gc_mark_outrefs at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:2791 [inlined]
gc_mark_loop_serial_ at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:2963
gc_mark_loop_serial at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:2986
gc_mark_loop at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:3163 [inlined]
_jl_gc_collect at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:3552
ijl_gc_collect at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:3931
maybe_collect at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:922 [inlined]
jl_gc_pool_alloc_inner at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:1319
jl_gc_pool_alloc_noinline at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:1386 [inlined]
jl_gc_alloc_ at /cache/build/builder-amdci5-3/julialang/julia-master/src/julia_internal.h:506 [inlined]
jl_gc_alloc at /cache/build/builder-amdci5-3/julialang/julia-master/src/gc.c:3984
_new_genericmemory_ at /cache/build/builder-amdci5-3/julialang/julia-master/src/genericmemory.c:56 [inlined]
jl_alloc_genericmemory at /cache/build/builder-amdci5-3/julialang/julia-master/src/genericmemory.c:99
GenericMemory at ./boot.jl:529 [inlined]
FixedSizeArray at ./REPL[1]:19 [inlined]
FixedSizeArray at ./REPL[1]:28 [inlined]
similar at ./abstractarray.jl:868 [inlined]
similar at ./abstractarray.jl:867 [inlined]
similar at ./REPL[1]:81 [inlined]
copy at ./broadcast.jl:897 [inlined]
materialize at ./broadcast.jl:872 [inlined]
broadcast_preserving_zero_d at ./broadcast.jl:861 [inlined]
+ at ./arraymath.jl:8
_broadcast_getindex_evalf at ./broadcast.jl:678 [inlined]
_broadcast_getindex at ./broadcast.jl:651 [inlined]
getindex at ./broadcast.jl:610 [inlined]
macro expansion at ./broadcast.jl:973 [inlined]
macro expansion at ./simdloop.jl:77 [inlined]
copyto! at ./broadcast.jl:972 [inlined]
copyto! at ./broadcast.jl:925 [inlined]
copy at ./broadcast.jl:897 [inlined]
materialize at ./broadcast.jl:872 [inlined]
broadcast_preserving_zero_d at ./broadcast.jl:861 [inlined]
+ at ./arraymath.jl:8
#4 at ./generator.jl:37 [inlined]
iterate at ./generator.jl:48 [inlined]
collect_to! at ./array.jl:834 [inlined]
collect_to_with_first! at ./array.jl:812 [inlined]
collect at ./array.jl:786
map at ./abstractarray.jl:3547 [inlined]
f at ./REPL[7]:1
unknown function (ip: 0x700b7160e3a2)
top-level scope at ./REPL[11]:2
jl_toplevel_eval_flex at /cache/build/builder-amdci5-3/julialang/julia-master/src/toplevel.c:944
__repl_entry_eval_expanded_with_loc at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:220
toplevel_eval_with_hooks at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:227
toplevel_eval_with_hooks at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:231
toplevel_eval_with_hooks at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:224 [inlined]
eval_user_input at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:249
repl_backend_loop at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:358
#start_repl_backend#59 at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:343
start_repl_backend at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:340
#run_repl#72 at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:499
run_repl at /home/nsajko/tmp/jl/jl/julia-aeac289163/share/julia/stdlib/v1.12/REPL/src/REPL.jl:485
jfptr_run_repl_12511 at /home/nsajko/.julia/compiled/v1.12/REPL/u0gqU_ZNQMV.so (unknown line)
#1161 at ./client.jl:448
jfptr_YY.1161_17027 at /home/nsajko/.julia/compiled/v1.12/REPL/u0gqU_ZNQMV.so (unknown line)
jl_apply at /cache/build/builder-amdci5-3/julialang/julia-master/src/julia.h:2188 [inlined]
jl_f__call_latest at /cache/build/builder-amdci5-3/julialang/julia-master/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:1032 [inlined]
invokelatest at ./essentials.jl:1029 [inlined]
run_main_repl at ./client.jl:432
repl_main at ./client.jl:569 [inlined]
_start at ./client.jl:543
jfptr__start_69977.1 at /home/nsajko/tmp/jl/jl/julia-aeac289163/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-amdci5-3/julialang/julia-master/src/julia.h:2188 [inlined]
true_main at /cache/build/builder-amdci5-3/julialang/julia-master/src/jlapi.c:900
jl_repl_entrypoint at /cache/build/builder-amdci5-3/julialang/julia-master/src/jlapi.c:1059
main at /cache/build/builder-amdci5-3/julialang/julia-master/cli/loader_exe.c:58
unknown function (ip: 0x700b73043ccf)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 2017840 (Pool: 2017705; Big: 135); GC: 3
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Fixes https://github.com/JuliaLang/julia/issues/54266, I've not yet minimized something to put into a test but in any case we can add the large test since it executes quite quickly. 

This also enables IR verification with `Strong=true` when building with assertions, this would've caught this bug much earlier.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by Keno** [comment]
A pointer GEP in addrspace 10 is basically never legal (because each object is a separate allocation and there's only one addrspace 10 pointer that's valid in that allocation). Can we add this to the verifier? Then adding a test for this will also become easy.

**Comment by Keno** [comment]
Actually, we already have it https://github.com/JuliaLang/julia/blob/f712512a1159771d9a61e1a768e1a8b297a493c8/src/llvm-gc-invariant-verifier.cpp#L139:

```
    /* We're actually ok with GEPs here, as long as they don't feed into any
       uses. Upstream is currently still debating whether CAST(GEP) == GEP(CAST).
       In the frontend, we always perform CAST(GEP), so while we can enforce
       this invariant when we run directly after the frontend (Strong == 1),
       the optimizer will introduce the other form. Thus, we need to allow it
       while upstream hasn't decided whether the optimizer is allowed to
       introduce these.
       */
    if (Strong) {
        Check(AS != AddressSpace::Tracked,
             "GC tracked values may not appear in GEP expressions."
             " You may have to decay the value first", &GEP);
    }
```
But clearly it's not triggering in this example, so we may need to enhance it.

**Comment by gbaraldi** [comment]
@Keno the issue is that the check is behind the `Strong` flag, you have a comment there as to why we may disable this, do you know if we can just remove that check?

**Comment by Keno** [comment]
As the comment indicates, the `Strong` version of this should run on the IR that we output from the frontend, which is supposed to catch this issue.

**Comment by Keno** [comment]
I don't believe LLVM has decided the pointercast vs gep issue.

**Comment by gbaraldi** [comment]
So we should run the verifier twice then? Once before optimization and once after with Strong off?

**Comment by Keno** [comment]
Yes, that's how it's designed (in debug mode only of course). It's possible we lost one of the passes.

**Comment by gbaraldi** [comment]
I'm tempted to move this check to run when assertions are on instead of just debug. Debug is not part of CI nor PkgEval and that pass isn't particularly expensive, it should be O(N) with a small constant

**Comment by Keno** [comment]
That's fine.

**Pull request merged**
