### PR TITLE
Add `\approxeq` (`≊`) as an alias to `isapprox` as well

### PR DESCRIPTION
**Pull request by staticfloat**
It seems to me that this would be another reasonable shortcut

### CODE REVIEW

**Comment by yuyichao** [comment]
Why do we need two aliases for it?

**Comment by staticfloat** [comment]
Because some people write `\appox` and others write `\approxeq`.  Considering the semantics behind the symbols, this seems reasonable to me.

**Comment by yuyichao** [comment]
> others write `\approxeq`

You mean on paper? That seems like a pretty weak reason. I don't think we should add all these as alias though since it'll be confusing for the reader. We can certainly have ascii and unicode operator aliases for functions since operators give the function special syntax and unicode usually makes it shorter. However, having both `≈` and `≊` seems to me like adding `const isapproxeq = isapprox` and I think we should just pick one standard operator and stick to it for both the function name and unicode or operator.

Also, FWIW, `≒` seems to be a more direct synonym according to https://en.wiktionary.org/wiki/%E2%89%88 .

Also need export, doc, etc.

Also ref https://github.com/JuliaLang/julia/issues/5903. I think we can do that for ones with identical looking (which is IIRC defined in unicode in some way?) but adding other aliases seems like a pretty deep rabit hole.

**Comment by yuyichao** [comment]
> I think we can do that for ones with identical looking (which is IIRC defined in unicode in some way?) but adding other aliases seems like a pretty deep rabit hole.

Or put in another way, if we have some clear rule what should be added, we can add all of them.

**Comment by StefanKarpinski** [comment]
Yeah, I'm :-1: on this too – I've considered using `≊` for other relations and it seems inconsiderate to take yet another name for the same operation in Base.

**Pull request closed without merging**
