### PR TITLE
Remove outdated restriction on Type{} calls in abstract interpretation

### PR DESCRIPTION
**Pull request by Keno**
`@vtjnash` said in #35845 that he didn't know what this code was for
and didn't think it was necessary. Since he's the one that added it
and the comment says it's about backedges, I'm inclined to believe
him :). In any case, removing it passes base tests, so let's try it.

### CODE REVIEW

**Comment by Keno** [comment]
I also pushed the other change here (using `jl_method_table_for`), since it's in the same place and I'd like to PkgEval them together. If one of them turns out problematic, we can split the PR again.

**Comment by Keno** [comment]
@nanosoldier `runtests(ALL, vs = "master")`

**Comment by Keno** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Review by JeffBezanson — APPROVED** [review]

**Comment by Keno** [comment]
Looks like PkgEval is having some issues. I'll give it until tomorrow morning to get back. Otherwise, I'll just merge and we can see if anything breaks during the regular PkgEval runs.

**Pull request merged**
