### PR TITLE
RFC: Bump libgit2 to 0.22

### PR DESCRIPTION
**Pull request by tkelman**
cc @jakebolewski

They move pretty quickly, this isn't a security update like the last one (not that we're actually using libgit2 yet...), but should we try to keep up with their latest branch in terms of the API's we target?

### CODE REVIEW

**Comment by staticfloat** [comment]
I think updates that remove patches kept locally are always a plus.  As long as they don't introduce regressions, of course, but in this case, we don't have all _that_ much to test it with, right?

**Comment by tkelman** [comment]
> updates that remove patches kept locally are always a plus

And Makefile complication in MSYS, since they fixed https://github.com/libgit2/libgit2/issues/2526 (thanks for that @ethomson!)

> we don't have all that much to test it with, right?

Not yet. Except for this bit:

```patch
-    if v.major == LIBGIT2_VER.major && v.minor == LIBGIT2_VER.minor
+    if v.major == LIBGIT2_VER.major && v.minor >= LIBGIT2_VER.minor
```

**Comment by jakebolewski** [comment]
Thanks, I've been trying to follow the development branch.  They broke a whole bunch of API's again.

**Comment by jakebolewski** [comment]
@staticfloat, @tkelman do you have a 32 bit Windows VM with a source build of Julia I can use?

**Comment by nalimilan** [comment]
IIUC this raised the requirement to libgit2 0.22, right? But apparently, 0.21 is also supported, since this PR does not contain any change. Could we allow anything >= 0.21, for distributions where only that version would be available?

**Comment by staticfloat** [comment]
@jakebolewski I'll email you the details.

**Comment by tkelman** [comment]
> Could we allow anything >= 0.21, for distributions where only that version would be available?

That depends on how flexible we can manage to be in terms of which API's the bindings use.

**Comment by tkelman** [comment]
> do you have a 32 bit Windows VM with a source build of Julia I can use

32 bit Julia works just fine in 64 bit Windows. What's the issue?

**Comment by nalimilan** [comment]
> That depends on how flexible we can manage to be in terms of which API's the bindings use.

@tkelman If a future Julia version relies on an API that is not present in 0.21, I'm absolutely fine with requiring 0.22. I was just wondering why we would require 0.22 if (as appears to be the case) 0.21 would also work ATM.

**Comment by quinnj** [comment]
I'm just updating my windows build and running into the error below, I tried nuking all libgit2 files in `deps`, but am still seeing it. Am I missing any other required makes for the upgrade?
```julia
C:/Users/karbarcca/julia/deps/libgit2-0.22.0/src/openssl_stream.c: In function 'openssl_certificate':
C:/Users/karbarcca/julia/deps/libgit2-0.22.0/src/openssl_stream.c:276:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  *out = (git_cert *)&st->cert_info;
  ^
CMakeFiles/git2.dir/build.make:1483: recipe for target 'CMakeFiles/git2.dir/src/openssl_stream.c.obj' failed
make[5]: *** [CMakeFiles/git2.dir/src/openssl_stream.c.obj] Error 1
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/git2.dir/all' failed
make[4]: *** [CMakeFiles/git2.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make[3]: *** [all] Error 2
Makefile:1795: recipe for target 'libgit2-0.22.0/build/libgit2.dll' failed
make[2]: *** [libgit2-0.22.0/build/libgit2.dll] Error 2
Makefile:110: recipe for target 'julia-release' failed
make[1]: *** [julia-release] Error 2
Makefile:50: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by nalimilan** [comment]
Looks like `-Werror` is striking. Maybe that flag is passed when it shouldn't (it's usually considered a mistake on tarballs since you never know what warnings an arbitrary compiler version is going to raise).

**Comment by tkelman** [comment]
Is that the only message, sure there isn't something higher up? It says `warning:` ... could turn verbose output on to see whether it's actually sending `-Werror`.

**Comment by tkelman** [comment]
I was able to do `make -C deps install-libgit2` in a clean clone in MSYS2. I get some unused parameter warnings from `deps/libgit2-0.22.0/src/openssl_stream.c:369`, but nothing fatal. I think the difference is my machine was unable to find OpenSSL. Do you have openssl on your path somewhere? What does the cmake output say?

**Comment by quinnj** [comment]
I'm away from my box until tonight, but I'll try the suggestion and report some more later. Thanks for helping @tkelman

**Comment by tkelman** [comment]
0.22.1 has also been released already, so maybe worth trying that to see if it fixes the problem

**Comment by tkelman** [comment]
@quinnj okay turns out this is an upstream bug with building libgit2, even latest 0.22.1 release, when openssl is found. It might be MinGW-only, but I'm not sure whether an MSVC build of openssl is possible.

Here's the full log, there are lots of errors more severe than that type-punned dereference warning: https://build.opensuse.org/build/home:kelman:branches:windows:mingw:win64/openSUSE_Factory/x86_64/mingw64-libgit2/_log

**Comment by tkelman** [comment]
Reported upstream at https://github.com/libgit2/libgit2/issues/2850

**Pull request merged**
