### PR TITLE
Backporting the libblas and vendor() improvements to 1.8

### PR DESCRIPTION
**Pull request by ViralBShah**
This PR includes #44360, #44379, and #42957 all of which are required together. The crash reported in https://github.com/JuliaLang/julia/pull/44379#issuecomment-1058928522 is fixed as a result.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Some of the 0-stride tests are failing - no exception is being thrown. Maybe something changed in openblas 0.3.20. I'll look into it a bit more and should be easy to fix.

**Comment by ViralBShah** [comment]
I think we need #42957 to fix the test failures with 0 strides.

**Comment by ViralBShah** [comment]
win32 test failure seems unrelated.

**Comment by KristofferC** [comment]
Why is this so important to get into 1.8 (and why is it on the milestone). And https://github.com/JuliaLang/julia/pull/42957 looks like a feature.

**Comment by ViralBShah** [comment]
This has been a lot of hassle for 1.8. Let's not bother about getting this to 1.8. We'll just focus on 1.9. There are some annoyances where 1.8 will unconditionally (and incorrectly when MKL is loaded) claim that `Base.libblas_name` and `vendor` is openblas - but that was also the case in 1.7.

Best to focus on 1.9 to get it fixed ecosystem-wide.

**Pull request closed without merging**
