### PR TITLE
add a few doctests and updates to networking and streams

### PR DESCRIPTION
**Pull request by KristofferC**
I didnt manage to add so many doctests here because it contained stuff like reading from STDIN. I just ran most locally and updated what I found.

### CODE REVIEW

**Comment by KristofferC** [comment]
I guess some more stuff here could be doctests if we would actually create the files that are being read from. Not sure where they should be created and how cleanup is best handled. Maybe they could just be checked into the doc tree?

**Comment by tkelman** [comment]
which files are you referring to?

**Comment by KristofferC** [comment]
The one that is being read by `readlines` in the manual for example.

**Comment by tkelman** [comment]
Ah, okay. We could create it in the doctest, and show best practices with a do block to avoid leaking handles even (as long as that's described somewhere prior or nearby)

**Comment by kshyatt** [comment]
For the STDIN/OUT stuff, can we show making our own `IOStream` and putting in/taking from it?

**Comment by KristofferC** [comment]
Perhaps but maybe that would make the section more advanced / less interactive?

**Comment by kshyatt** [comment]
I think if we explain it well it would really enhance that part of the manual. I confess this stuff is still pretty opaque to me and it would be nice to have a thorough explanation/example.

**Review by kshyatt — APPROVED** [review]
My desire for big improvements to this section doesn't have much to do with this PR. Looks good as is.

**Comment by KristofferC** [comment]
Opened issue #20325 to track improvementss to docs for this part of the manual.

**Pull request merged**
