### PR TITLE
add favicon to doc directory

### PR DESCRIPTION
**Pull request by morrme**
Closes: #21723

### CODE REVIEW

**Comment by tkelman** [comment]
how does this make its way into the gh-pages built docs?

**Comment by morrme** [comment]
@tkelman I initially put it on that branch but was told to move it because of the way the build works. 🤷‍♀️

**Comment by tkelman** [comment]
I don't think that person was correct. I suspect #21821 is more likely to work than this one would be.

**Comment by morrme** [comment]
@tkelman I really thought so as well but I had to go with what the julia team wanted.

**Comment by tkelman** [comment]
huh? the comment in #21723 that said not to do this on gh-pages was from someone who has never contributed to julia before

**Comment by morrme** [comment]
ah! I was not aware of that @tkelman  .... there were no objections/counterpoints at the time (yours was the first) . I am new to this project so I am not well versed on who is who. Should I reopen the other PR so that it can be open for discussion ?

**Comment by tkelman** [comment]
Let's reopen that one, merge it, then see if the favicon starts working. If not we can think about it again, but from what I know about how the content of docs gets deployed to the gh-pages branch, I don't think there's any code there that would copy the favicon for us automatically. We don't use jekyll for the gh-pages documentation branch on this repo.

**Pull request closed without merging**
