### PR TITLE
Revert "Store `UnicodeData.txt` within `$(SRCCACHE)`"

### PR DESCRIPTION
**Pull request by vtjnash**
Reverts JuliaLang/julia#31476 (while we fix it)

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
Whoops, you're right.

**Comment by staticfloat** [comment]
The reason I didn't notice this (and the buildbots didn't care) is because all my systems always override `SRCCACHE` from the global level.

**Comment by vtjnash** [comment]
We can probably still do this, we should just have `deps` do the download and put the file somewhere predictable for us.

**Comment by staticfloat** [comment]
I have a second PR up (that I requested your review on) that just initializes `SRCCACHE` in the same way that `deps/Makefile` does.

**Pull request merged**
