### PR TITLE
WIP: put a bow on package precompilation and merge it

### PR DESCRIPTION
**Pull request by timholy**
NOTE: this is a PR against jn/static_compile_4, not master. CC @vtjnash.

@vtjnash has done (quite some time ago) basically all the work needed for package precompilation; to merge it, we just need to wrap up a few loose ends and put a bow on it. This is my attempt to make some progress on that goal. This WIP adds a mechanism to keep track of the files associated with a package and perform an `mtime` check to see if the precompiled version needs to be updated if files have been edited.

However, I can't test this contribution because #8745 is broken in ways I don't fully understand. I am also well aware that this ignores the multiprocess case, I was just going to try to get the single process case working first.

Also note this adds `mkdir("/tmp/a/b/c", recursive=true)` and changes the location of the `libs` directory.

### CODE REVIEW

**Comment by rened** [comment]
@timholy I believe `mkpath` already does what `mkdir(..., recursive=true)` does?

**Comment by timholy** [comment]
Indeed it does. Thanks! I'll refactor when the other points are addressable.

**Comment by vtjnash** [comment]
i think this needs to be more deeply integrated with the C code, including the code that handles `Core.include` and the code that handle serialization/deserialization (verification) of a module. it's too late if jl_restore_new_module has completed to return false from that method.

it perhaps also needs a user-accessible hook, so the user can specify `@cacheable depends_on some_file`.

the split by version looks good.

i'll rebase my PR when I get a chance, although it probably won't be for another week. it's hard to know whether some deep assumption got broken, or something highly trivial (the inference change also involved some small changes to the dump.c code, including what should be a very minor performance improvement for this usage).

**Comment by timholy** [comment]
Thanks for the feedback, @vtjnash. It all sounds like good advice.

It will be easier to test this when #8745 is working again, so I may focus my efforts elsewhere until you get a chance to look at that.

**Comment by ufechner7** [comment]
Why was this issue closed?

**Comment by vtjnash** [comment]
i believe it was covered by https://github.com/JuliaLang/julia/pull/12117

**Comment by ufechner7** [comment]
In that case #11536 should be updated, because it references this issue as unresolved.

**Comment by vtjnash** [comment]
fixed

**Pull request closed without merging**
