### PR TITLE
at-kwdef support for parametric types and subtypes

### LINKED ISSUE #29307: `@kwdef` fails on structs with supertypes
This is best explained with an example:
```julia
julia> abstract type Super end

julia> Base.@kwdef struct S <: Super; v; end
ERROR: syntax: invalid function name "S <: Super"

julia> @macroexpand Base.@kwdef struct S <: Super; v; end
quote
    #= util.jl:660 =#
    begin
        $(Expr(:meta, :doc))
        struct S1 <: Super
            #= none:1 =#
            v
        end
    end
    (S1 <: Super)(; v) = (S1 <: Super)(v)
end
```

`@kwdef` is blindly taking the first argument of the struct Expr and using as the function name. But the first argument includes the supertype when it is present. This means the function name includes the supertype annotation which is invalid.

I think the fix for this is simple and safe: Check for the case where the struct "name" is not a Symbol and further deconstruct it to get the real struct name. Patch below.

```diff
From 22f0ccfe0e97ad157aca6a917ccc2c299a1329c8 Mon Sep 17 00:00:00 2001
From: Arthur Peters <amp@singingwizard.org>
Date: Fri, 21 Sep 2018 12:32:24 -0500
Subject: [PATCH] Fix invalid code generation in @kwdef when struct has
 supertype.

---
 base/util.jl | 7 ++++++-
 1 file changed, 6 insertions(+), 1 deletion(-)

diff --git a/base/util.jl b/base/util.jl
index 80c7907..d27dc03 100644
--- a/base/util.jl
+++ b/base/util.jl
@@ -652,7 +652,12 @@ Stacktrace:
 """
 macro kwdef(expr)
     expr = macroexpand(__module__, expr) # to expand @static
-    T = expr.args[2]
+    if expr.args[2] isa Symbol
+        T = expr.args[2]
+    else
+        @assert expr.args[2].head == :<:
+        T = expr.args[2].args[1]
+    end
     params_ex = Expr(:parameters)
     call_ex = Expr(:call, T)
     _kwdef!(expr.args[3], params_ex, call_ex)
-- 
2.17.1
```

(I explicitly release my copy rights, if any, to this patch, putting my contribution to this patch in the public domain.)

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #29307.

### CODE REVIEW

**Comment by simonbyrne** [comment]
I have no idea what is happening, but I get this locally:
```
Generating precompile statements...┌ Error: Failed to precompile precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Type{Vararg{Any, N} where N}})
└ @ Main.anonymous /Users/simon/src/julia/contrib/generate_precompile.jl:169
ERROR: LoadError: LoadError: TypeError: in Type, in parameter, expected Type, got Type{Vararg{Any,N} where N}
```
any ideas?

**Comment by KristofferC** [comment]
Seems like another manifestation of https://github.com/JuliaLang/julia/issues/28808.

**Comment by simonbyrne** [comment]
Thanks for the fix and the examples. I'm not sure what you mean by "feature completeness", but if it exists, it might as well be correct.

**Comment by mauro3** [comment]
Sorry,  with "feature complete" I meant what the equivalent macro `@with_kw` in Parameters.jl supports.  Looks like I can drop that part of Parameters.jl, thanks!

How about adding to the docs something like: "If inner constructors are defined, then `@kwdef` assumes that one is the positional constructor of all fields."

**Comment by simonbyrne** [comment]
Makes sense: what else is missing compared with `@with_kw`?

How about:

> Inner constructors can still be defined, but should accept arguments in the same form as the default inner constructor (i.e. one positional argument per field) in order to function correctly with the keyword outer constructor.

**Comment by mauro3** [comment]
Three bits which are "missing" are:
- allow `@assert`s in the type body which then get included in the positional inner constructor.
- different `show` method. 
- automatic documentation of the type-fields with their defaults

I don't think the first two are suitable for Base.  The third would be nice though, but maybe for another PR.

> Inner constructors can still be defined, but *one needs* accept arguments in the same form as the default inner constructor (i.e. one positional argument per field) in order to function correctly with the keyword outer constructor.

**Comment by mauro3** [comment]
Wait, there is another useful one:
```
i1 =  SomeType(a=77, b=0,...)
i2 = SomeType(i1, b=9) # takes all of i1's values except the ones defined with the kw
```
x-ref: https://github.com/JuliaLang/julia/issues/5333

**Comment by simonbyrne** [comment]
I can see that last one would be useful, but there is the question of what to do if the struct takes a single field. e.g.
```
struct SomeType
   a
end
```
then what should
```
SomeType(SomeType(a=1))
```
give?

**Comment by simonbyrne** [comment]
How would you construct the nested type?

**Comment by simonbyrne** [comment]
It's a pity we can't overload splatting, then we could use the syntax
```
SomeType(SomeType(a=1)...; a=2)
```
At the moment that would require writing an iterator over the object.

**Comment by mauro3** [comment]
> How would you construct the nested type?

I see the problem.  But you already figured out the solution:

> It's a pity we can't overload splatting

but you should probably implement that in a separate PR. ;-)

No, more seriously, probably leave that feature for now.  Alternatively, just forget about the nested type in the one-field case.

**Comment by simonbyrne** [comment]
Okay, I think this is ready to merge.

**Comment by mauro3** [comment]
LGTM except the doc-string update:

Inner constructors can still be defined, but one needs to accept arguments in the same form as the default inner constructor (i.e. one positional argument per field) in order to function correctly with the keyword outer constructor.

**Comment by simonbyrne** [comment]
Done.

**Comment by simonbyrne** [comment]
Yes, though it shouldn't be breaking, so we could backport if you wanted it?

**Comment by StefanKarpinski** [comment]
Features don't go in point releases.

**Comment by simonbyrne** [comment]
I would argue this is a bugfix rather than a feature. (from https://discourse.julialang.org/t/kwdef-not-working-for-parametric-struct/25286/4)

**Comment by fredrikekre** [comment]
It's not even exported.

**Pull request merged**
