### PR TITLE
Fixed parenthesis error

### PR DESCRIPTION
**Pull request by marsue**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Since both of these evaluate to the same (correct) value, it's unclear to me that this was an error:

```jl
julia> -(3/4*im)
-0.0 - 0.75im

julia> -(3/4)*im
-0.0 - 0.75im
```

**Comment by yuyichao** [comment]
Isn't there some extra/missing minus signs going on here?

**Comment by yuyichao** [comment]
NVM, it is correct.

**Comment by marsue** [comment]
I didn't notice the precence of the *-operator, because the text is about the literal coefficient and the division.
Sorry my fault.

**Comment by marsue** [comment]
Leave the *-operator out would make the example more clear to me:
3/4im == 3/(4im) == -(3/4)im
But -(3/4)im evaluates to negative zero in the real part, whereas the other expressions have a positive zero…

**Comment by marsue** [comment]
I updated the patch.
Since the following equation is better, since it the focus is on the literal coefficient and the division operator and the priority of the multiplication is removed.
```jl
3/4im == 3/(4im) == -(3/4)im
```
I had read the previous equation (in a mathematical sense) as 3/4im == -(3/4im) which seemed to be an error to me.

**Comment by jiahao** [comment]
> But -(3/4)im evaluates to negative zero in the real part, whereas the other expressions have a positive zero…

#10000

At this point this PR is just a cosmetic change which I don't think conveys significant value. However, some additional wording about paying attention to the parentheses in the expression would make a useful contribution.

**Comment by StefanKarpinski** [comment]
It seems a bit clearer, let's just merge it.

**Comment by tkelman** [comment]
Note that this was against the release branch. It's generally preferable to open PR's against master first.

**Pull request merged**
