### PR TITLE
`Base.setindex` return type inference quick fix

### PR DESCRIPTION
**Pull request by nsajko**
Xref #54462

### CODE REVIEW

**Comment by kimikage** [comment]
In the first place, is it appropriate to use `ntuple` for code which do not return `NTuple`?
It is misleading, even if intentional.

**Comment by kimikage** [comment]
E.g.:
```julia
import Base: setindex

function setindex(x::Tuple, v, i::Integer)
    @boundscheck 1 <= i <= length(x) || throw(BoundsError(x, i))
    @inline
    _setindex_tuple(x, v, i)
end

function _setindex_tuple(x::NTuple{N, T}, v::T, i::Integer) where {N, T}
    @inline
    return ntuple(j -> ifelse(j == i, v, x[j]), Val{N}())
end

function _setindex_tuple(x::Tuple, v, i::Integer)
    @inline
    return Tuple(ifelse(j == i, v, xj) for (j, xj) in enumerate(x))
end
```

**Comment by kimikage** [comment]
E.g.
```julia
import Base: setindex

function setindex(x::Tuple, v, i::Integer)
    @boundscheck 1 <= i <= length(x) || throw(BoundsError(x, i))
    @inline
    _setindex_tuple(x, v, i)::Tuple
end

function _setindex_tuple(x::NTuple{N, T}, v::T, i::Integer) where {N, T}
    @inline
    return ntuple(j -> ifelse(j == i, v, x[j]), Val{N}())
end

function _setindex_tuple(x::Tuple, v, i::Integer)
    @inline
    return ((ifelse(j == i, v, xj) for (j, xj) in enumerate(x))...,)::Tuple
end
```

**Comment by nsajko** [comment]
I've got a better fix locally, a recursive implementation of `_setindex`, not based on `ntuple`. It's got way better inference.

**Pull request closed without merging**
