### PR TITLE
[backports-release-1.11] fix pkgdir during inits on 1.11

### PR DESCRIPTION
**Pull request by IanButterworth**
Proposed fix for https://github.com/JuliaLang/julia/issues/56077 on 1.11

```
julia> using MWE
[ Info: Precompiling MWE [f3b207a7-3b3b-4b3b-8b3b-3b3b3b3b3b3b] (cache misses: include_dependency fsize change (1))
MWE
/Users/ian/Documents/GitHub/mwe
```

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
I believe you cannot move this here because we rely on the require lock remaining held during this function for safety

**Review by vtjnash — COMMENTED** [review]
Oh, I see, this is actually moving it later? I guess that seems okay

**Comment by KristofferC** [comment]
Can someone explain why you want to call this in init?

**Comment by IanButterworth** [comment]
I don't have a defense. If you want to look into the issue in the ecosystem https://github.com/JuliaIO/JLD2.jl/issues/610

But I don't think we should be fixing this by changing user code. It works on 1.10 and master

**Comment by IanButterworth** [comment]
@vtjnash this appears to now avoid a deadlock that tests expected
```
precompile (1) |         failed at 2024-11-13T14:47:42.184
Test Failed at /var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_INOnAw/Baz26028.jl:3
  Expression: #= /var/folders/1z/jf841bdj73bdj3vk7kc7f_3w0000gn/T/jl_INOnAw/Baz26028.jl:4 =# @eval import Foo26028.Bar26028.x
    Expected: ConcurrencyViolationError("deadlock detected in loading Foo26028 -> Foo26028")
  No exception thrown
```
Related issues
https://github.com/JuliaLang/julia/issues/26028
https://github.com/JuliaLang/julia/pull/28416

I think that's a good thing?

**Comment by vtjnash** [comment]
That means you've introduced a new data race. Although I don't see precisely why, I think it is because of the expected failures without the fixes for it from https://github.com/JuliaLang/julia/pull/56329

**Comment by IanButterworth** [comment]
I can't figure out why either.

> I think it is because of the expected failures without the fixes for it from https://github.com/JuliaLang/julia/pull/56329

I don't follow this, sorry.

**Comment by IanButterworth** [comment]
So we mark the test as broken on 1.11 ?

**Comment by IanButterworth** [comment]
@vtjnash I've done that, but this does need approval.

**Comment by IanButterworth** [comment]
Potentially related https://discourse.julialang.org/t/concurrencyviolationerror-when-loading-packages-via-requires-jl-in-julia-1-11/122685

**Pull request closed without merging**
