### PR TITLE
load Pkg when hitting Pkg repl history

### PR DESCRIPTION
**Pull request by IanButterworth**
Previously, since Pkg was moved out of the sysimage, Pkg entries in history would be skipped until Pkg was loaded.

### CODE REVIEW

**Comment by KristofferC** [comment]
I've been somewhat annoyed about this too but:

- It feels a bit "heavy-handed" to load all of Pkg when scrolling through history.
- It doesn't help with reverse search.

So maybe this is a good idea but it is perhaps worth pondering over it for a while if something else could be done.

**Comment by IanButterworth** [comment]
What about this one @KristofferC @Keno 

Maybe we just load like this in 1.11 to avoid regression and then try to make a lighter weight history that doesn't load Pkg or something?

**Comment by JeffBezanson** [comment]
Idea from @vtjnash: make all history entries always visible, but if one is from a mode that's not available use a fallback prompt mode where the text is grayed out and gives a "Pkg not loaded" error if you try to run it. Maybe also make the prompt text un-editable.

**Comment by IanButterworth** [comment]
We could pair that with the same dummy pkg prompt from https://github.com/JuliaLang/julia/pull/54594

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/julia/pull/54674 now allows scrolling through the dummy Pkg prompt if Pkg isn't loaded, then loads Pkg and executes on return.

**Pull request closed without merging**
