### PR TITLE
[Zlib_jll] Update to v1.2.12+3

### PR DESCRIPTION
**Pull request by giordano**
Follow up to https://github.com/JuliaPackaging/Yggdrasil/pull/4692.

Note: this is the first build of the real upstream version 1.2.12 which was
released a few days ago.

Usual memo to self:

* update the version number in `stdlib/Zlib_jll/Project.toml`
* update the version number in `deps/zlib.version`
* refresh checksums with `make -f contrib/refresh_checksums.mk -j zlib`

CC: @eschnett

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by eschnett** [comment]
This is a security update for zlib. It would make sense to backport these changes.

**Comment by giordano** [comment]
I believe @KristofferC has a script which does that automatically

**Comment by nsslh** [comment]
Please add the security label.

**Comment by fxcoudert** [comment]
@giordano quick question: why is `ZLIB_VER` in `deps/Versions.make` still `1.2.11`? Is that a mistake that should be updated, or should that line be removed entirely? I do not understand the difference between `deps/Versions.make` and `deps/zlib.version`?

**Comment by giordano** [comment]
That's a good question to which I don't have a definitive answer.  `deps/zlib.mk` fetches the source with the function `git-external`: https://github.com/JuliaLang/julia/blob/dea980590f41bab820be4c42b42f29639ac8a56c/deps/zlib.mk#L5 which reads `deps/zlib.version` and uses the variables defined there: https://github.com/JuliaLang/julia/blob/dea980590f41bab820be4c42b42f29639ac8a56c/deps/tools/git-external.mk#L24-L26  So I _think_ that the version number in  `deps/Versions.make` is not really used, but judging by the comments at the top of the file the variable still needs to be defined?

**Pull request merged**
