### PR TITLE
More efficient permutedims

### PR DESCRIPTION
**Pull request by Jutho**
Dear Julia developers,

this is a first suggestion for a performance improvement for permutedims! by using a cache-friendly blocking strategy. The improvement can be large (up to a factor of 5 or more) for big arrays (100 x 100 x 100 x 100 or 10 x 10 x 10 x 10 x 10 x 10 x 10 x 10) and permutations that mix strongly, such as the complete reversing of dimensions (`p=N:-1:1`), although there might be a penalty for small arrays because of the dynamic computation of a blocking strategy. This could matter in loops where small arrays are permuted many times. I will try to post some timing results later today.

### CODE REVIEW

**Comment by quinnj** [comment]
Going through old PRs here......is this something that is still relevant for Base? Seems like a lot of new machinery has gone into Arrays/iteration, but I also wonder if this is a better candidate for the [Combinatorics.jl](https://github.com/JuliaLang/Combinatorics.jl) package?

**Comment by ViralBShah** [comment]
This one certainly belongs to Base.

**Comment by Jutho** [comment]
But this particular PR can certainly be closed as it is completely outdated and will need to be redone ( (this was before `@generated` functions.  `permutedims` has already evolved since this PR was created, though as far as I know it is still not yet cache efficient / oblivious.

**Comment by timholy** [comment]
The generic algorithm (meaning, the one that doesn't assume linear indexing & strides) is somewhat [cache-efficient](https://github.com/JuliaLang/julia/blob/bf7310259d232ee2002abdbeb7f08de5b70d6d8c/base/permuteddimsarray.jl#L68-L94), but without a doubt more could be done to tune its performance. Once I beat the alternative of copying the input array, I just quit there (bad me).

**Comment by stevengj** [comment]
@timholy, I'm a little confused by that code.  Where is the permutation in `P[I1, i, I2, j, I3] = src[I1, i, I2, j, I3]`?  All the arguments seem to be in the same order on the lhs and rhs.

**Comment by timholy** [comment]
So glad you noticed how sneaky it is. The magic is in the definition of `setindex!`. The implementation is:
- allocate the output array `dest`
- wrap `dest` in a `PermutedDimsArray` "view," called `P`. `P` has the same size as the original matrix you want to permute.
- copy the data to `P`. From the perspective of `dest`, `setindex!` takes care of rearranging the indexes to enact the permutation. (There's also a `getindex`, naturally, which does the same index-swapping upon access.) 
- discard the wrapper and return `dest`

So it's the implementation of `copy!` that does all the work---you basically get two methods for the price of one, meaning you can concentrate your efforts at improving performance.

Plus, julia now supports arrays with arbitrary storage order (in less than 100 lines of code). This simply turned out to be the most modular way to implement `permutedims` in a way that avoids linear indexing (which is horrible for many array types). But obviously this can go way, way beyond that. I'm not sure how well these views will work for general use, hence this infrastructure is deliberately buried (not exported, not even visible in Base) until there's evidence that it's safe to use more broadly. It definitely would be good for adventurous souls to kick the tires and see what's missing.

**Comment by stevengj** [comment]
@timholy, because of that rearrangement of indices, it is not as cache-efficient as it could be.  The problem is that at least one of the arrays (either the source or the destination) will be reading/writing data non-consecutively in memory, which hurts cache-line utilization.

However, for power-of-two sizes (which are the worst case for cache-line conflicts), `permutedims(A, (2,1))` on Julia 0.4 seems 2-3 times worse than `copy(A)`, which is actually surprisingly good.  Maybe cache associativity has gotten a lot larger since the last time I looked at this sort of thing?

**Comment by timholy** [comment]
That's the reason for splitting out the loops over `src`'s first dimension and `dest`'s first dimension (the `i` and `j` loops) separately. It does the copy in 8x8 blocks (a number I chose arbitrarily).

**Comment by timholy** [comment]
Oh shoot, I was going by a mix of memory and the code, but just glanced again and I see I've been a little bit confusing. To clarify, `_permutedims!` is just a specialized implementation of `copy!`, for those cases where the arrays don't share an extended first dimension in common. When both arrays share the same first dimension(s), and those dimensions correspond to quite a few elements (perhaps I should set the threshold bigger than 1 :smile:), then there's really no harm in using plain-old `copy!`.

**Pull request closed without merging**
