### PR TITLE
reduce allocation in a few linalg functions while removing full calls

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request reduces allocation in a few linalg functions by replacing (allocating) `full` calls with (non-allocating) alternatives. Serves as another small step towards deprecation of `full`. Ref. JuliaLang/LinearAlgebra.jl#229, JuliaLang/LinearAlgebra.jl#231, JuliaLang/julia#18850, and linked threads. Best!

### CODE REVIEW

**Comment by andreasnoack** [comment]
What about having a generic function for this operation?

**Comment by Sacha0** [comment]
> What about having a generic function for this operation?

As in the present `full!`? I thought of extending `full!` from the triangular types to `Symmetric`/`Hermitian` and deploying it here, but hesitated for a few reasons:

Foremost I wanted to ponder `full!`'s semantics (to make certain I was not replacing one poorly defined operation with another). But `full!`'s semantics seem well defined: Make the parent match the child's contents and return the parent.

Next I was curious how frequently `full!` sees use, and whether in those cases some better approach exists. (My experience in eliminating `full` has been that usually a better approach exists, as e.g. in  this pull request.) Outside the potential uses in this pull request, `full!` has only three uses (exclusively in two-argument `A_mul_B[c]!` methods), and one of those uses is redundant. But in those cases `full!`'s semantics do seem right, and as this pull request demonstrates `full!`'s semantics are useful beyond the existing uses.

So given the above I favor your proposition, i.e. I lean towards extending `full!` to `Symmetric`/`Hermitian` and deploying it here. But simultaneously I would rename `full!` to reflect its semantics. Some ideas: `fillparent!`, `fixparent!`, `matchparent!`, `conformparent!`, `completeparent!`.

In any case playing with `full!` seemed like something for a followup pull request, so I left off.

Thoughts? Thanks! :)

**Comment by Sacha0** [comment]
Rebased and extended to the `full` calls introduced in #23679. Assuming CI signs off and absent objections or requests for time, I plan to merge these changes this evening or tomorrow morning and carry through the plan outlined in https://github.com/JuliaLang/julia/pull/24137#issuecomment-336656037 in a followup pull request. Best!

**Comment by fredrikekre** [comment]
```
linalg/dense: Test Failed
  Expression: all((z->begin
            -π < imag(z) < π && real(z) > 0 || (0 <= imag(z) < π && abs(real(z)) < abstol || abs(imag(z) - π) < abstol && real(z) >= 0)
        end), (eigfact(acosh(A)))[:values])
```

**Comment by Sacha0** [comment]
(The CI failure should be fixed. Thanks `@fredrikekre`! :) )

**Comment by Sacha0** [comment]
Thanks all!

**Pull request merged**
