### PR TITLE
Change srand default seed to 0 from nothing in testdefs

### PR DESCRIPTION
**Pull request by kshyatt**
This [seems to be killing coverage](https://buildog.julialang.org/#/builders/16/builds/10/steps/8/logs/stdio), because `srand(nothing)` doesn't work anymore. `0` is the default `MersenneTwister` seed, I think? Should we be using `make_seed()` instead?

### CODE REVIEW

**Comment by andreasnoack** [comment]
> because srand(nothing) doesn't work anymore

I don't think it ever has so something else must be going on here and is probably worth figuring out before changing this.

**Comment by rfourquet** [comment]
Indeed `srand(nothing)` never worked (only `srand(::MersenneTwister, ::Void)` was added recently as an implementation detail). Also, `0` is not anymore a default seed, actually there is no default seed. Not providing a seed amounts to seeding randomly; when specifying a `MersenneTwister` RNG `r`, this is equivalent to passing `nothing` as the seed (i.e. `srand(r, nothing)` is equivalent to `srand(r)`). So we could add `srand(::Void) = srand()`, but I'm not conviced this is the solution here. In the keyword arg `seed=nothing`, `nothing` represents a default which is not used, i.e. the function API requires to pass a `seed`, but the keyword syntax requires a default. So a solution could be to add a test: `seed == nothing && throw(...)` (but I don't know if this works for test coverage?), or maybe `seed != nothing && srand($seed)` in the `quote` block.

**Comment by kshyatt** [comment]
What about making the kwarg `seed=make_seed()`?

**Comment by rfourquet** [comment]
In the end it doesn't matter too much I guess, as in practice we call this function with the `seed` set (at least this is the intention); hence it may be better to throw if no seed is passed, to enforce this requirement: is this compatible with coverage testing? But I don't see `make_seed()` really preferable to `0`, unless a new use of this `runtests` function shows it can be useful to have a default random seed (but this `seed` argument was precisely introduced to have reproducible tests).

**Comment by kshyatt** [comment]
A lot of the individual test files (especially in `linalg` and `sparse`) set `srand` themselves anyway. I think `0` is fine, and probably better than `make_seed` - forcing people to pick a seed every time seems kind of harsh to me...

**Comment by kshyatt** [comment]
So, @rfourquet, would you be ok with merging this as-is? Or should we change something?

**Comment by rfourquet** [comment]
> forcing people to pick a seed every time seems kind of harsh to me...

I don't understand this bit: we are talking of an internal function which is called twice, in "test/runtests.jl", so besides this I don't see who we are forcing to pick a seed, am I missing something? So as I said my prefered solution is to throw if no seed is provided, can you update your PR to that? this can be amended later if a need arises where we want to allow not specifying the seed. Setting an actual default value makes little sense for me as it is only used with a speicified value, except that test coverage insists to call this function without a `seed`. Again, I may totally miss something, and I know nothing about the test coverage infrastructure.

**Comment by kshyatt** [comment]
I took the suggestion of `$seed != nothing && srand($seed)`, so that things will silently do the right thing. Do we want to issue a warning in this case, or is this acceptable as-is?

**Comment by rfourquet** [comment]
Ok so I investigated a bit more and found that indeed `runtests` is called in "CoverageBase.jl", which does something very different from what I imagined. Then indeed I find it unnecessary to force this caller to specify a seed, and it seems to me the most conservative solution, and with least surprise, is to do nothing when no seed is provided. Thanks @kshyatt !

**Review by rfourquet — APPROVED** [review]

**Comment by kshyatt** [comment]
https://codecov.io/gh/JuliaLang/julia/tree/master/base COVERAGE IS BACK, BABY! Thanks again @rfourquet <3<3<3

**Pull request merged**
