### PR TITLE
Simplify takebuf() API

### PR DESCRIPTION
**Pull request by nalimilan**
This implements one of the Stringapalooza tasks scheduled for 0.6 (https://github.com/JuliaLang/julia/issues/16107 and https://github.com/JuliaLang/julia/pull/16058#discussion_r61229502): `takebuf_array` is now simply `takebuf`, and `takebuf_string(b)` is now `String(takebuf(b))`.

Points to discuss:
- I've removed the `jl_takebuf_string` C function, which was used for `IOStream` method and performed the conversion from array to string in C. I don't think it should be a performance issue, but could someone confirm that?
- I've kept the name `takebuf`, but maybe another one is appropriate now? Could it be a method of a more generic function like `collect` or `Array`?
- There's already a `String(b::AbstractIOBuffer)` method with a similar behavior, but it only works on seekable streams. One difference is that it doesn't call `unmark`, maybe there are others. Probably doesn't affect this PR, but I thought I would mention it.

Fixes https://github.com/JuliaLang/julia/issues/8575.

### CODE REVIEW

**Comment by vtjnash** [comment]
`takebuffer`? or `buffer!`?

**Comment by dhoegh** [comment]
What about `take!`? It does not seem in conflict with the current uses. The help list:
```
help?> take!
search: take! take takebuf_array takebuf_string StackOverflowError istaskdone stacktrace StackTraces

  take!(c::Channel)

  Removes and returns a value from a Channel. Blocks till data is available.

  take!(rr::RemoteChannel, args...)

  Fetch value(s) from a remote channel, removing the value(s) in the processs.
```

**Comment by ararslan** [comment]
I like the idea of overloading `take!` for this purpose but IIRC that function was recently moved to a new `Base.Iterators` module, so you'd have to call it like `Iterators.take!`. I suppose it doesn't really matter, but to me the name `Iterators` seems a little odd in the context of working with buffers.

**Comment by nalimilan** [comment]
`take!` sounds nice, but as @vtjnash told me today I/O functions don't end with a `!` in general even when they mutate the input stream. So it would have to be `take`, which has a very different meaning.

@vtjnash Why do you suggest `buffer!` with an ending `!`?

**Comment by dpsanders** [comment]
Can't it just be string(buf) where buf::IOBuffer?

**Comment by yuyichao** [comment]
> `string(buf)`

No, `string` is roughly how you show the object.

**Comment by dpsanders** [comment]
There is repr for that.

**Comment by yuyichao** [comment]
No that's yet another more verbose representation of the object. http://docs.julialang.org/en/release-0.5/stdlib/strings/?highlight=repr

**Comment by nalimilan** [comment]
It could be `String(b)`, but as I said it already exists and has a slightly different behavior. I think the rationale it that a constructor doesn't look like it should mutate the input argument (by calling `unmark!`).

I've just re-discovered that there was an issue for this naming debate, but not with many proposals: https://github.com/JuliaLang/julia/issues/8575.

**Comment by dhoegh** [comment]
@ararslan as far as I can see only `take` and not `take!` is deprecated in https://github.com/JuliaLang/julia/pull/18839/files#diff-7904f4ddd9158030529e0ed5ee8707eeR1031.

**Comment by ararslan** [comment]
@dhoegh Oh you're right—I mistakenly thought `take!` was the mutating form of `Iterators.take`, but that seems to not be the case. In that case, +1 to `take!`.

**Comment by stevengj** [comment]
+1 for `take!`.  This isn't an I/O function in the same sense as `read` or `write`, so I think `!` seems appropriate.

**Comment by nalimilan** [comment]
So is the general preference for `take!`?

Something that escapes me is why the docs say "Obtain the contents of an IOBuffer as an array, *without copying*". Looking at the code, it seems to me that a copy is always made, even when it could be avoided by reusing the `data` field. I would be more inclined to use `take!` if that field was indeed reused.

**Comment by vtjnash** [comment]
If it is seekable, writable, and backed by an Array{UInt8}, then it is no-copy. I agree that the seekable condition seems somewhat extraneous.

**Comment by nalimilan** [comment]
Thanks, I hadn't noticed that the newly allocated array was of length 0 in the best case.

I've updated the PR to use `take!`. I've also renamed `jl_takebuf_array` and `ios_takebuf` to `jl_take_buffer` and `ios_take_buffer`, which seems more consistent.

**Comment by nalimilan** [comment]
Should we merge now?

**Comment by nalimilan** [comment]
I'll merge tomorrow barring further suggestions or objections.

**Comment by nalimilan** [comment]
Phew! It was hard to get into a mergeable state, `deprecated.jl` is such a busy place these days...

**Comment by s2maki** [comment]
This deprecation warning is sometimes wrong (and results in an error in those cases).  When `takebuf_string(v)` is passed a UInt8 vector, it reports that `String(take!(v))` is the replacement, but `take!(v)` doesn't accept a UInt8 vector.  It should just be `String(v)` in that case.

**Comment by nalimilan** [comment]
At least the `Vector{UInt8}` method (if it ever existed) wasn't removed in this PR.

**Pull request merged**
