### PR TITLE
turn codegen into a C++ class

### PR DESCRIPTION
**Pull request by vtjnash**
this lets us stop passing around `ctx`, while not making any functional changes (yet)

### CODE REVIEW

**Comment by maleadt** [comment]
Are you working towards being able to instantiate multiple codegen instances? Thinking in terms of multiple back-ends here, it would be nice if the frontend's linfos wouldn't be coupled to codegen (funcobj, specfuncobj) and jit (fptr). Or how would you envision generating IR for a different back-end, where we don't want use/pollute the already compiled llvmfs/fptrs?

**Comment by vtjnash** [comment]
That wasn't the direct goal, but yes that's effectively where this is trying to go. Some of the current motivating thoughts include:
 - experimenting with multiple threads / multiple contexts
 - removing globalUnique (and funcobj / specfunobj) and make codegen more pure (enabling more generic caching of precompiled code)
 - removing recursion into julia code (e.g. fixing ccall)

but I'm also just interested in seeing where you and others take this

**Comment by StefanKarpinski** [comment]
Woah, man. You're turning this C in C++'s clothing into actual C++.

**Comment by StefanKarpinski** [comment]
Can you leave a comment when you close a PR like this?

**Comment by vtjnash** [comment]
I guess it seemed to have gotten stale and wasn't likely to make much headway towards getting merged.

**Comment by StefanKarpinski** [comment]
Is there a reason not to do this?

**Comment by tkelman** [comment]
I was told by Yichao that this is likely to be the fix for the current reason master doesn't compile with MSVC:
```
codegen.cpp
c:/projects/julia/src/codegen.cpp(550) : error C2905: '<unnamed-tag>::is_inbounds' : an in-class initializer is not allowed for a member of an anonymous union in non-class scope
```

**Comment by vtjnash** [comment]
We can also just delete that initializer, since we now zero-initialize the struct everywhere we use it.

**Pull request closed without merging**
