### PR TITLE
SubArray: avoid invalid elimination of singleton indices

### LINKED ISSUE #53209: view fails when new axis is prepended and last axis is selected
Hello,

In 1.10.0 view fails when:
1) new axis is prepended with [CartesianIndex()]
2) the last axis is chosen at some value

```
julia> A = rand(2,3)
2×3 Matrix{Float64}:
 0.562201  0.212601  0.193508
 0.408022  0.978427  0.823557

julia> A[[CartesianIndex()], :, 1]
1×2 Matrix{Float64}:
 0.562201  0.408022

julia> view(A, [CartesianIndex()], :, 1)
ERROR: ArgumentError: number of indices (1) must match the parent dimensionality (2)
Stacktrace:
 [1] check_parent_index_match(parent::Matrix{Float64}, #unused#::Tuple{Bool})
   @ Base .\subarray.jl:43
 [2] check_parent_index_match(parent::Matrix{Float64}, indices::Tuple{Vector{CartesianIndex{0}}, Base.Slice{Base.OneTo{Int64}}})
   @ Base .\subarray.jl:41
 [3] SubArray
   @ .\subarray.jl:21 [inlined]
 [4] SubArray
   @ .\subarray.jl:32 [inlined]
 [5] SubArray
   @ .\subarray.jl:28 [inlined]
 [6] unsafe_view
   @ .\subarray.jl:219 [inlined]
 [7] view(::Matrix{Float64}, ::Vector{CartesianIndex{0}}, ::Function, ::Int64)
   @ Base .\subarray.jl:180
 [8] top-level scope
   @ REPL[11]:1
```

This shouldn't happen according to the second block of example.

Analysis of code brought the following lines: https://github.com/JuliaLang/julia/blob/94fd312df03d5075796fbd2e8b47288a84a1c6de/base/subarray.jl#L207-L210 

As we see, the condition holds because the length of J is 3 and `ndims(A)` is 2 and the last index is integer. Therefore `view` proceeds to the line 209.

However, because of `[CartesianIndex()]`, the array really needs to be reshaped.

When I explicitly type line 211, it works as expected:
```
julia> A = rand(2,3)
2×3 Matrix{Float64}:
 0.784263  0.958573   0.869377
 0.619148  0.0324357  0.966875

julia> J = map(i->Base.unalias(A,i), to_indices(A, ([CartesianIndex()], :, 1)))
([CartesianIndex()], Base.Slice(Base.OneTo(2)), 1)

julia> Base.unsafe_view(Base._maybe_reshape_parent(A, Base.index_ndims(J...)), J...)
1×2 view(::Matrix{Float64}, [CartesianIndex()], :, 1) with eltype Float64:
 0.784263  0.619148
```

With best regards, Vadim Zborovskii

### PR DESCRIPTION
**Pull request by N5N3**
close #53209

### CODE REVIEW

**Comment by vadim-z** [comment]
What if the last index is not singleton but, for example, 3? I fear it would be incorrectly removed from the list J'.

**Comment by N5N3** [comment]
That would be took care by bounds checking.
https://github.com/JuliaLang/julia/blob/d453af81c8c70f06b2c8b70cef566ffdc5705958/base/abstractarray.jl#L725
Thus the trailing indices will only contain `1`.
They could be replaced with someting like `fill(CartesianIndex(), index_shape(trailing_indices...))` if `length(index_shape(trailing_indices...)) > 0`
But at present we don't have lazy `fill` in `Base`.

**Comment by vadim-z** [comment]
Sorry, but because of CartesianIndex() bound checking will pass, and this is correct behavior.

Example:

```
julia> A = rand(2,3)
2×3 Matrix{Float64}:
 0.0221974  0.820445  0.861314
 0.555607   0.457571  0.875773

julia> A[[CartesianIndex()], :, 3]
1×2 Matrix{Float64}:
 0.861314  0.875773

julia> J = map(i->Base.unalias(A,i), to_indices(A, ([CartesianIndex()], :, 3)))
([CartesianIndex()], Base.Slice(Base.OneTo(2)), 3)

julia> @boundscheck checkbounds(A, J...)

julia>
```

If some extra axes are added, the trailing indices are not really "trailing", as they refer to real dimensions of a parent array.

**Comment by N5N3** [comment]
Yes, but `CartesianIndex()` also consumes no parent's dimension.
Thus `rm_singleton_indices` won't eliminate `3` from `J = ([CartesianIndex()], :, 3))`
I guess the added test
```julia
@test A[CartesianIndices(()), :, 1] == @inferred(view(A, CartesianIndices(()), :, 1))
```
is enough?

**Comment by vadim-z** [comment]
Yes, you are right.

> Yes, but `CartesianIndex()` also consumes no parent's dimension.

I've missed the point.

**Pull request merged**
