### PR TITLE
avoid nested SubString construction

### PR DESCRIPTION
**Pull request by bkamins**
Currently:
```
x = "123"
y = SubString(x, 1, 2)
z1 = SubString(y, 1, 1)
z2 = SubString{typeof(y)}(y, 1, 1)
```
yields:
```
julia> typeof(z1)
SubString{String}

julia> typeof(z2)
SubString{SubString{String}}
```
This PR is intends to make this consistent and `z1` and `z2` should be `SubString{String}` avoiding unnecessary nesting of `SubString`.

### CODE REVIEW

**Comment by nalimilan** [comment]
Can you add a test?

**Review by nalimilan — APPROVED** [review]

**Comment by nalimilan** [comment]
I always find it weird for a `X{T}` constructor not to return a `X{T}` object, but that's clearly one of the cases where the requested `T` does not make any sense.

**Comment by JeffBezanson** [comment]
I'm not convinced this is really needed --- if a `SubString{SubString{...}}` is requested explicitly, we might as well allow it. It can be ok for `T(x)` not to return an instance of `T`, but that should only be done if truly, truly necessary.

**Comment by bkamins** [comment]
This was a side observation when I worked on `SubString` serialization PR that was just merged (as nesting of `SubString` generated problems). Given the accepted implementation there this PR it is not *truly, truly necessary*.

So it is OK for me that this PR is rejected and closed.

**Comment by bkamins** [comment]
I am closing this PR following @JeffBezanson comment (I am not sure what is the policy in Julialang regarding who is allowed to close a PR - but I assume that it is OK if I close it).

**Pull request closed without merging**
