### PR TITLE
Don't hard-code `#include` paths

### PR DESCRIPTION
**Pull request by eschnett**
Otherwise I can't compile on OS X with LLVM 3.5.1.

### CODE REVIEW

**Comment by Keno** [comment]
I didn't think the header was public in LLVM 3.5. Can you confirm that this compiles on 3.5.0?

**Comment by tkelman** [comment]
Yeah, I complained about this one when it was added in https://github.com/JuliaLang/julia/commit/3e23dfdb975d652651acf5628410aa3db90cf191

If it works in 3.5.1 but not 3.5.0, I think just not supporting 3.5.0 on OSX is preferable to adding patch-level `ifdef`ery.

**Comment by eschnett** [comment]
I don't know whether it works with LLVM 3.5.0. However, since I specify `USE_SYSTEM_LLVM=1`, this would be broken for me anyway -- any direct pointer to `../deps/llvm*` would not work.

**Comment by eschnett** [comment]
My suggested patch doesn't work. The `MCJIT.h` file that the patch uses is very different from the original one. It seems one cannot use an installed LLVM 3.5 with Julia since the MCJIT interface is not exposed.

**Pull request closed without merging**
