### PR TITLE
add load=false option to atmacroexpand1

### PR DESCRIPTION
**Pull request by bramtayl**
This is a useful for testing whether macros parsed correctly. Ref https://github.com/JuliaLang/julia/pull/34854#discussion_r383507425

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This would be one of the only things in the `Test` module that doesn't start with `test_` ...

**Comment by StefanKarpinski** [comment]
It's also a bit weird that it has such a generic name when it is very specific: it parses a single macro call expression. Would be good to see some places in the test suite where this would clean up the code.

**Comment by fredrikekre** [comment]
Could maybe just be a `raise=false` argument to `@macroexpand`? (Similar to `Meta.parse` etc.)

**Comment by bramtayl** [comment]
> Could maybe just be a raise=false argument to @macroexpand? (Similar to Meta.parse etc.)

Ooh I like that better. I'll give that a shot.

**Comment by bramtayl** [comment]
On further reflection, maybe `@macroexpand` throwing a load error is a bug? Compare:

```
macro test(x)
    x == "bad" && error("bad")
    :good
end
# same result
(@test "bad")
(@macroexpand @test "bad")
# different result
@test "hello world"
@macroexpand @test "hello world"
```

**Comment by bramtayl** [comment]
The docs for LoadError say

An error occurred while includeing, requireing, or using a file. The error specifics should be available in the .error field.

Which all sound like eval to me, and `@macroexpand` doesn't eval...

**Comment by bramtayl** [comment]
Hmm seems LoadErrors are intended based on #24825, so I've used @frederickekre s suggestion and added an option to `@macroexpand1`

**Comment by bramtayl** [comment]
I don't know why the arch failed to build and I'm torn between opening a new issue, retriggering CI, and crying.

**Comment by bramtayl** [comment]
Replaced by #34895

**Pull request closed without merging**
