### PR TITLE
[release-0.3] backports for 0.3.12

### PR DESCRIPTION
**Pull request by tkelman**
Been a while since 0.3.11, we had a bunch of 0.4.0 release candidates to worry about. Since there are a few commits already on release-0.3 that haven't been released, and a few more tagged for "backport pending 0.3," figured we should probably do one last tag. I'll build test binaries from this branch and run PkgEval to compare with 0.3.11, make sure there are no regressions at least in automatically tested code. If anyone identifies any regression between 0.3.x and 0.3.12 at any point in the future we can put out an 0.3.13 to fix it if we need to.

Please do check my backporting work. The only PR with the "backport pending 0.3" label that isn't yet included here is #12645, cc @timholy and see my recent comment there. I did just remove that label from #12934 and #12607 due to cherry-picking conflicts, but could be convinced otherwise if someone feels strongly.

### CODE REVIEW

**Comment by tkelman** [comment]
Oh, I need to set the git config in .travis.yml. Will fix that tomorrow.

**Comment by tkelman** [comment]
@IainNZ any idea why PackageEvaluator refuses to finish a complete run here? 6+ times now on multiple machines. Partway through, packages start giving 0-size _add.log files and not outputting json files. This is extremely frustrating.

**Comment by IainNZ** [comment]
I've never experienced that before... obviously, works well on 0.3.11

**Comment by tkelman** [comment]
No, it doesn't, not on any of the machines I've been trying to run it on. One of the VM's I'm testing on for this comparison is 0.3.11.

**Comment by IainNZ** [comment]
Hah, well, thats weird. The "obviously" was because its been working for me on my machine, Miles machine, and now nanosoldier for a while now. Are you running in split AL/MZ config?

**Comment by tkelman** [comment]
Yes, though I also tried the "all" version and hit the same issue.

**Comment by tkelman** [comment]
I did eventually get an entire run to go through, but it took way more attempts than I would have liked - https://gist.github.com/anonymous/d101e776fad97f46e1ab

The only newly failing package was RouletteWheels.jl (cc @jbn), not sure what's causing that. Oddly on 0.3.11, Dates froze, HTTPClient had an `ERROR: test failed: r.http_code == 200` (flaky connection on nanosoldier maybe?) and OnlineStats had an `ERROR: ArgumentError("Cauchy: the condition σ > zero(σ) is not satisfied.")` but I suspect those are probably intermittent, rather than any of the changes here making them pass.

**Comment by IainNZ** [comment]
Dates has intermittently frozen for all of 0.3, and I've seen that for httpclient plenty too. Online stats problem sounds familiar

**Comment by tkelman** [comment]
Note for future reference that without https://github.com/JuliaLang/julia/pull/7906, release-0.3 cannot be built on win32 using `MARCH=pentium4`, so the buildbot configuration needs to be temporarily adjusted to make things work. @staticfloat the binaries of 0.3.12 are ready in julianightlies, can you check `Base.runtests()` on mac?

**Comment by staticfloat** [comment]
`Base.runtests()` passes with no errors on mac.

**Comment by tkelman** [comment]
Great, thanks. Do you have a set of scripts you've been using for moving binaries from julianightlies to julialang? I imagine it needs to update the -latest files, create checksums and do the gpg signing, and make sure it sets the permissions to readable. Anything else? The gpg key is yours so I guess only you can do that one, but for the rest could you email me anything where it would help if I did it? Along with s3 credentials which I somehow don't have yet.

**Comment by staticfloat** [comment]
No, I've just been doing it manually, using Cyberduck.  I'm a little paranoid about automating stuff in the julialang bucket.  We'll get you the access.

**Pull request merged**
