### PR TITLE
Enable stride/strides to work on a ReinterpretArray with complex Strided parents.

### PR DESCRIPTION
**Pull request by BioTurboNick**
As described in issue #37405, a complex nested array type like reinterpret(view(reinterpret(view(A)) is not defined as a `StridedArray`. I tried implementing a type-based solution but it caused things to break and made the type signatures very long.

So instead I just implemented `stride`/`strides` methods that check if the parent is a `StridedArray`, erroring otherwise.

### CODE REVIEW

**Comment by BioTurboNick** [comment]
Why are the 32-bit tests failing? Int16 and Int32 should behave the same regardless of architecture, right?

**Comment by simeonschaub** [comment]
Int literals are `Int32`s on 32 bit platforms, so `1:20` is actually a `UnitRange{Int32}` there.

**Comment by BioTurboNick** [comment]
Is the analyzegc failure related to this PR?

**Comment by timholy** [comment]
The analyzegc test looks mostly at Julia's C code, so it shouldn't be related.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
