### PR TITLE
move SparseArrays to the external repo https://github.com/JuliaLang/SparseArrays.jl

### PR DESCRIPTION
**Pull request by KristofferC**
Right now it uses the last commit in https://github.com/JuliaLang/SparseArrays.jl/pull/7. That should be merged and the SHA updated when it is.

There are some tests that loads SparseArrays:

- `Random/test/runtests.jl`
- `abstractarray.jl`
- `ambiguous.jl`
- `arrayops.jl`
- `core.jl`
- `hashing.jl`
- `show.jl`

These tests should migrate to the SparseArray repo, but that can be done after this PR is done.

@dkarrasch, @ViralBShah, I think we should try not to merge anything to SparseArrays in the Julia repo until this PR is merged.

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]
I'm not an expert in the package management, but tests pass, so this LGTM. Do we need this PR bot which files a checksum-update PR every time we merge a PR to `SparseArrays.jl`?

**Comment by KristofferC** [comment]
Merged https://github.com/JuliaLang/SparseArrays.jl/pull/7 and updated the SHA here. Will merge once CI passes and start transitioning sparse issues to the separate repo.

**Comment by ViralBShah** [comment]
Do we want a NEWS entry?

**Review by ViralBShah — APPROVED** [review]

**Comment by KristofferC** [comment]
Sounds like a good idea, I'll add one.

**Comment by staticfloat** [comment]
Wish I could give this PR a posthumous approval!

**Comment by DilumAluthge** [comment]
> Do we need this PR bot which files a checksum-update PR every time we merge a PR to `SparseArrays.jl`?

Are you referring to https://github.com/JuliaLang/BumpStdlibs.jl?

BumpStdlibs.jl won't bump the checksums every time you merge a PR to `SparseArrays.jl`? Instead, when you want to trigger a bump manually, just follow the instructions in the BumpStdlibs README.

**Pull request merged**
