### PR TITLE
reverse traversal of row entries if step(I) < 0

### PR DESCRIPTION
**Pull request by nassarhuda**
Details about the bug can be found in #21986 
This should fix it.

### CODE REVIEW

**Comment by ararslan** [comment]
Hi @nassarhuda, welcome! This is a very nice first contribution. It would be great if you could add some tests though to ensure that the behavior doesn't end up showing up again in the future.

**Review by timholy — COMMENTED** [review]
LGTM. Just needs a test and it can go in.

**Comment by KristofferC** [comment]
Messed something up while adding a test to this branch. Gimme a sec...

**Comment by KristofferC** [comment]
New PR at https://github.com/JuliaLang/julia/pull/22544. Tried to update this but didnt have access to OPs branch anymore.

**Pull request closed without merging**
