### PR TITLE
Add a warning that HTML should not be used #38909

### LINKED ISSUE #38909: Add a warning that HTML should not be used
Reference: https://github.com/JuliaLang/julia/pull/38892#issuecomment-746607119

We accidentally exported `HTML` and we should warn users to avoid them.

### PR DESCRIPTION
**Pull request by josemanuel22**
Add a warning that HTML should not be used #38909
Fixes #38909

### CODE REVIEW

**Comment by mortenpi** [comment]
Thanks @josemanuel22! This conveys the message, but I reckon stylistically it would be better to avoid all caps, have full sentences and [format it as a `warning` admonition](https://docs.julialang.org/en/v1/stdlib/Markdown/#Admonitions) instead. Currently it won't look very pretty.

Perhaps a phrasing like

> These names are currently exported to maintain backwards-compatibility, but are considered to be deprecated and should not be used. They will be removed in Julia 2.0.

would be better?

**Comment by simeonschaub** [comment]
I thought #38909 was about not exporting `HTML` and `Text` anymore, not deleting them outright. It just seems a bit odd to me to warn about a change here that may perhaps happen in 2.0, since 2.0 is still a long way off and there will likely be many more impactful changes, so I don't really see the point of a warning like this.

**Comment by josemanuel22** [comment]
> Thanks @josemanuel22! This conveys the message, but I reckon stylistically it would be better to avoid all caps, have full sentences and [format it as a `warning` admonition](https://docs.julialang.org/en/v1/stdlib/Markdown/#Admonitions) instead. Currently it won't look very pretty.
> 
> Perhaps a phrasing like
> 
> > These names are currently exported to maintain backwards-compatibility, but are considered to be deprecated and should not be used. They will be removed in Julia 2.0.
> 
> would be better?

It is much better! Thanks for the info!

**Comment by mortenpi** [comment]
> It just seems a bit odd to me to warn about a change here that may perhaps happen in 2.0, since 2.0 is still a long way off and there will likely be many more impactful changes, so I don't really see the point of a warning like this.

I think you might be right in that it doesn't make sense to document what will or won't happen in 2.0 like this (especially since we could theoretically change our minds). Perhaps just drop the "They will be removed in Julia 2.0" part then?

I do think we want a warning though, in order to steer users away from using these.

**Comment by musm** [comment]
> I thought #38909 was about not exporting HTML and Text anymore, not deleting them outright. It just seems a bit odd to me to warn about a change here that may perhaps happen in 2.0, since 2.0 is still a long way off and there will likely be many more impactful changes, so I don't really see the point of a warning like this.

We definitely want to get rid of them, just how to address the deprecation strategy is the main issue. I don't think there has a been discussion on this or how to go about it more generally for 2.0 yet. It might be an appropriate time to think about it soon, however, now that 1.6 is on the loom.

**Review by fredrikekre — APPROVED** [review]

**Pull request merged**
