### PR TITLE
Printf %g/%G  format fix for Inf/NaN

### LINKED ISSUE #41631: @printf crashes with g/G format and non-finite numbers
@printf("%G", NaN)
ERROR: BoundsError: attempt to access 337-element Vector{UInt8} at index [0]
Stacktrace:
 [1] getindex
   @ .\array.jl:801 [inlined]
 [2] fmt
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Printf\src\Printf.jl:428 [inlined]
 [3] format
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Printf\src\Printf.jl:720 [inlined]
 [4] format(io::Base.TTY, f::Printf.Format{Base.CodeUnits{UInt8, String}, Tuple{Printf.Spec{Val{'G'}}}}, args::Float64)
   @ Printf C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Printf\src\Printf.jl:803
 [5] top-level scope
   @ REPL[4]:1

It works as expected with f and e formats . This is with v1.6.2

### PR DESCRIPTION
**Pull request by Seelengrab**
Fixes #41631

### CODE REVIEW

**Comment by Seelengrab** [comment]
> mkdir -p 
> mkdir: missing operand
> Try 'mkdir --help' for more information.
> make[1]: *** [/buildworker/worker/package_linuxppc64le/build/usr/manifest/csl] Error 123

Uuhh.. Not `Printf` related?

**Comment by KristofferC** [comment]
> Not Printf related?

No :)

**Comment by Seelengrab** [comment]
I'll get the champagne then, a build failure that's not caused by me missing something 😂

**Comment by Seelengrab** [comment]
Seems like Distributed tests deadlocked on Freebsd.

**Review by quinnj — APPROVED** [review]
Thanks!

**Comment by KristofferC** [comment]
Please squash PRs like this :)

**Comment by quinnj** [comment]
Oof, sorry. I still think we shouldn't allow merge commits and just do rebase or squash.

**Comment by StefanKarpinski** [comment]
Merge commits are appropriate sometimes. Core devs often make PRs that are a series of logically separate, staged commits, in which case a merge commit is the right thing to do. A rebase would be ok in those cases but the GitHub UI for rebase-merge sucks and makes it impossible to trace each commit back to the PR that it came from, so that's not ideal.

**Pull request merged**
