### PR TITLE
Update SuiteSparse to 4.4.2

### PR DESCRIPTION
**Pull request by ViralBShah**
Fixes a known bug in earlier releases.
#9720

### CODE REVIEW

**Comment by tkelman** [comment]
should delete old and add new checksums

**Comment by ViralBShah** [comment]
I thought I was forgetting something.

**Comment by staticfloat** [comment]
I actually haven't updated the debs or bottles for Suitesparse in a long time.  I'll add this to my TODO, now that I've finished updating the whole Gtk+3 tree for Tobias.  :P

**Comment by tkelman** [comment]
I think this should be safe.

**Comment by staticfloat** [comment]
I've discovered that `repackage_system_suitesparse4.make` is broken and has been broken for some time, so I will fix that.   I also mirrored this tarball to the cloudfront mirror.

**Comment by staticfloat** [comment]
Small note: SuiteSparse 4.4.3 is now the default on Travis and Ubuntu.

**Comment by ViralBShah** [comment]
@andreasnoack Are we waiting for 4.4.4 shortly?

**Pull request merged**
