### PR TITLE
use sparse multiplication for sparse arrays time BitMatrix and BitVector and wrappers

### LINKED ISSUE #39474: SparseMatrixCSC times BitVector falls back to dense multiplication
I apologize if this is already known (couldn't find it) but on 1.6

```julia
using SparseArrays, BenchmarkTools
N=10000
x=rand(Bool, N) .!= 0
M=sprand(N,N,10/N)
@btime $M*$x
@btime $M*Vector($x)
```

gives

```
  1.365 s (2 allocations: 78.20 KiB)
  296.739 μs (3 allocations: 88.14 KiB)
```

Maybe it may be sensible to use the second version by default? (or of course, better an ad-hoc implementation)

### PR DESCRIPTION
**Pull request by abraunst**
My attempt to fix #39474
Not really sure about the types renaming, can be rolled back or changed of course.

### CODE REVIEW

**Comment by abraunst** [comment]
I can add some tests if this is deemed the way forward.

**Comment by ViralBShah** [comment]
@dkarrasch Can you also take a look?

**Comment by ViralBShah** [comment]
Let's add the tests. I'm not sure - but is nanosoldier functional at the moment?

**Comment by abraunst** [comment]
> Let's add the tests. I'm not sure - but is nanosoldier functional at the moment?

About the tests... how can we target the fact that the multiplication is the sparse one? 
Or maybe we just need benchmarking?

**Comment by dkarrasch** [comment]
> About the tests... how can we target the fact that the multiplication is the sparse one?

I think you can do something like
```
m = @which mul!(C, A, B, true, false)
@test m.module == SparseArrays
```

> Or maybe we just need benchmarking?

It would be interesting to see whether we have tests that cover the BitVector case. But to make sure we don't regress from where we currently are, let's run Nanosoldier.

@nanosoldier `runbenchmarks("sparse", vs=":master")`

**Comment by abraunst** [comment]
> @nanosoldier `runbenchmarks("sparse", vs=":master")`

nanosoldier seems MIA :(

**Comment by dkarrasch** [comment]
Sometimes it's actually running but fails to leave a footprint. Unfortunately, I don't know where to look for whether it's running. I'll wait two or three hours and then try again.

**Review by dkarrasch — APPROVED** [review]
LGTM. I think this is carefully written to include "`BitVecOrMat`", but otherwise not change current behavior. I'd not expect to learn much from a Nanosoldiers run.

**Comment by ViralBShah** [comment]
That's what I thought as well - I think it should be good to merge.

I think nanosoldier is out of commission (and physical access to MIT is needed to fix it - which is not likely to be approved anytime soon).

**Comment by ViralBShah** [comment]
@dkarrasch Please merge if good.

**Pull request merged**
