### PR TITLE
allow pwd take paths as argument

### PR DESCRIPTION
**Pull request by Roger-luo**
just find this seems quite convenient when accessing subdir of current working directory (similar to the `pkgdir` interface)

### CODE REVIEW

**Comment by kshyatt** [comment]
Any interest in getting this out the door, or should I close it?

**Comment by Roger-luo** [comment]
> Any interest in getting this out the door, or should I close it?

right I forgot about this PR. let me try to fix the tests now

**Comment by fredrikekre** [comment]
Isnt't this just `abspath(paths...)`?

**Comment by Roger-luo** [comment]
actually you are right🥲

**Pull request closed without merging**
