### PR TITLE
Update Julia logos, removing rings, round 2

### PR DESCRIPTION
**Pull request by cormullion**
(Round 2, Round 1 is [here](https://github.com/JuliaLang/www.julialang.org/pull/372))

The Julia logo is gradually evolving, becoming simpler, clearer, and stronger. (The only change is that the two-color rings have become single-color.) 

oldlogo-newlogo-800
 
(See also https://github.com/JuliaCon/www.juliacon.org/issues/185). This PR updates some of the older PNGs and SVGs in this repo that used the old two-color rings to use single colors and a more consistent use of transparency.

### CODE REVIEW

**Comment by fredrikekre** [comment]
RIP stickers.

**Comment by cormullion** [comment]
@fredrikekre The vintage "I used Julia before it was cool" stickers? 😂

**Comment by musm** [comment]
Is this now the official logo? There are still a couple of places that need an update.

**Comment by musm** [comment]
@cormullion  do you have an svg of just the three dots ?

**Comment by cormullion** [comment]
@musm well there's certainly a few more to do, but I thought I'd better start somewhere. 😂  You can find much source material [here](https://github.com/JuliaGraphics/julia-logo-graphics).

**Comment by musm** [comment]
Thanks !!

**Comment by musm** [comment]
@cormullion  https://github.com/JuliaLang/julia/pull/32054 updates some of the windows icons and images

**Comment by cormullion** [comment]
@musm Great, I was puzzled about doing the .ico file... Cheers!

**Comment by musm** [comment]
THe BMP files are a pain too...

**Pull request merged**
