### PR TITLE
fix the bug in PR #21620 correctly

### LINKED ISSUE #22256: Sporadic segfaults in v0.6.0-rc2 using ODBC package
I experience sporadic segfaults when using the ODBC.jl package, but only when I use julia v0.6.0-rc2 (not v0.5.2 or v0.6.0-rc1). At first I thought this was a problem with the ODBC package, but given the functions in the coredump (which seem to be related to memory allocation?) and the fact that I only experience the segfaults when using v0.6.0-rc2, I think this may be a julia bug and not a ODBC bug.

I don't know how to make a 'minimal example' of this bug, since it necessarily involves interacting with a database. However, the following causes a segfault about 80% of the time in julia v0.6.0-rc2:

```julia
julia> versioninfo()
Julia Version 0.6.0-rc2.0
Commit 68e911be53* (2017-05-18 02:31 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

julia> using ODBC; db = ODBC.DSN("PostgreSQL")
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/galen/.julia/v0.6/NullableArrays/src/operators.jl:128.
ODBC.DSN(PostgreSQL)

julia> ODBC.query(db, "SELECT 1;")

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
julia_type_to_llvm at /home/galen/julia-0.6.0-rc2/src/cgutils.cpp:382
typed_store at /home/galen/julia-0.6.0-rc2/src/cgutils.cpp:1221
emit_setfield at /home/galen/julia-0.6.0-rc2/src/cgutils.cpp:2249
emit_builtin_call at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:3073
emit_call at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:3441
emit_expr at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:4139
emit_stmtpos at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:4058 [inlined]
emit_function at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:6242
jl_compile_linfo at /home/galen/julia-0.6.0-rc2/src/codegen.cpp:1256
jl_compile_for_dispatch at /home/galen/julia-0.6.0-rc2/src/gf.c:1672
jl_compile_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:305 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:352 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
stream! at /home/galen/.julia/v0.6/DataStreams/src/DataStreams.jl:239
unknown function (ip: 0x7fbcc1756e6a)
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
#stream!#5 at /home/galen/.julia/v0.6/DataStreams/src/DataStreams.jl:151
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
jl_apply at /home/galen/julia-0.6.0-rc2/src/julia.h:1422 [inlined]
jl_invoke at /home/galen/julia-0.6.0-rc2/src/gf.c:51
#query#14 at /home/galen/.julia/v0.6/ODBC/src/Source.jl:352 [inlined]
query at /home/galen/.julia/v0.6/ODBC/src/Source.jl:352
query at /home/galen/.julia/v0.6/ODBC/src/Source.jl:346
unknown function (ip: 0x7fbcc17337a6)
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
do_call at /home/galen/julia-0.6.0-rc2/src/interpreter.c:75
eval at /home/galen/julia-0.6.0-rc2/src/interpreter.c:242
jl_interpret_toplevel_expr at /home/galen/julia-0.6.0-rc2/src/interpreter.c:34
jl_toplevel_eval_flex at /home/galen/julia-0.6.0-rc2/src/toplevel.c:575
jl_toplevel_eval_in at /home/galen/julia-0.6.0-rc2/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7fbcdd8bfd4f)
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
eval_user_input at ./REPL.jl:66
unknown function (ip: 0x7fbcdd93b28f)
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
macro expansion at ./REPL.jl:97 [inlined]
#1 at ./event.jl:73
unknown function (ip: 0x7fbcc171636f)
jl_call_fptr_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:337 [inlined]
jl_call_method_internal at /home/galen/julia-0.6.0-rc2/src/julia_internal.h:356 [inlined]
jl_apply_generic at /home/galen/julia-0.6.0-rc2/src/gf.c:1930
jl_apply at /home/galen/julia-0.6.0-rc2/src/julia.h:1422 [inlined]
start_task at /home/galen/julia-0.6.0-rc2/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 6448532 (Pool: 6446872; Big: 1660); GC: 7
[1]    25988 segmentation fault (core dumped)  julia0.6
```

Here is a [coredump.txt](https://github.com/JuliaLang/julia/files/1056325/coredump.txt) produced by a different instance of the same bug.

### PR DESCRIPTION
**Pull request by vtjnash**
fix #22256

### CODE REVIEW

**Comment by tkelman** [comment]
would be good if the commit message briefly described what either the bug or the fix was

**Review by JeffBezanson — APPROVED** [review]

**Comment by galenlynch** [comment]
Looks like this may still have some issues: See this comment in [Feather.jl #46](https://github.com/JuliaStats/Feather.jl/issues/46#issuecomment-307258280)

**Comment by vtjnash** [comment]
@tkelman could you please suggest a new commit message rather than just asking for rework. In general, I strongly agree that commit messages should be more descriptive of the bug than an issue number. In this case, I just didn't have much more to say.

**Comment by tkelman** [comment]
What was the bug? Uninitialized memory of some kind, going by the reduction of #22256? I didn't author the diff here, I don't know enough about what was wrong or what these lines of code are supposed to be doing vs what they were doing to come up with a summary for you - I trust you're capable of doing so if you try to.

**Comment by JeffBezanson** [comment]
Something like "fix bug in `setfield!` codegen with abstract type"?

**Comment by vtjnash** [comment]
The bug is that PR https://github.com/JuliaLang/julia/pull/21620 would have caused Julia to crash if it had included a test. Somewhat surprising how little this code path gets used!

**Pull request merged**
