### PR TITLE
Test PR; please ignore

### PR DESCRIPTION
**Pull request by mbauman**
I haven't had success in getting AppVeyor to run on branches in my own fork (or in manually whitelisting branches to run here).  This is just a quick test to see if Win32 passes with a combination of two patches.

### CODE REVIEW

**Comment by tkelman** [comment]
> or in manually whitelisting branches to run here

What have you tried?

**Comment by mbauman** [comment]
On AppVeyor, in settings, adding this branch name to the whitelist and pushing again.  It's possible that `/` or `+` is interpreted as a non-literal, given that they do have some sort of `/regex/` syntax enabled for those fields.

**Comment by tkelman** [comment]
Ah. I think appveyor only pays attention to some of the gui settings if you don't specify them in appveyor.yml. Most likely you need to actually modify the yml file to add a test branch to the whitelist - https://github.com/JuliaLang/julia/blob/d586d8d31b807c3050d759b196bb00ab47839d0e/appveyor.yml#L11-L14

**Comment by mbauman** [comment]
Ah, that makes sense. Thanks.  Really, I should finally get around to compiling on my win32 box, especially if I'm going to need to fiddle with a workaround.  Sorry for the noise, all.

**Comment by mbauman** [comment]
Test success.

**Comment by tkelman** [comment]
I took the liberty of rebasing this to just include the `inline_worthy` change, mostly because this PR's title makes me really want to merge it.

**Comment by yuyichao** [comment]
> mostly because this PR's title makes me really want to merge it.

Noted. In case I really want a PR to be merged =).

**Comment by mbauman** [comment]
You're terrible. :)

I hate to steal the punchline from your joke, but I'd rather give credit where credit is due.  Committed as 56342be.

**Pull request closed without merging**
