### PR TITLE
inlining: pack return value of `ir_prepare_inlining!` into a struct

### PR DESCRIPTION
**Pull request by aviatesk**
To make the implementation a bit simpler.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50593#issuecomment-1641443324) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/67eff4a_vs_c5e4621/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50593#issuecomment-1641493642) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c64a896_vs_c5e4621/report.md).

**Pull request merged**
