### PR TITLE
small perf enhancement for deserialize of Arrays

### PR DESCRIPTION
**Pull request by vtjnash**
`Array(Type, dims)` is very hard (expensive) to dispatch, so this makes the constructor call a leaftype first to make it cheaper

### CODE REVIEW

**Comment by tkelman** [comment]
do we have any deserialization benchmarks? @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by ViralBShah** [comment]
Cc @kpamnany @jeff-reiger Perhaps we can adapt the use case from Celeste.jl as a standalone deserialize benchmark. Would really help catch future regressions.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18583#issuecomment-248379389) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/907e743762ba4ad3315afb079a51a41737582185/d029bb9_vs_9f50a2c/report.md). cc @jrevels

**Comment by vtjnash** [comment]
It looks like the parallel::remotecall perf test may lightly involve this

**Comment by stevengj** [comment]
See #18633 for a small benchmark.

**Comment by shashi** [comment]
@tkelman this is candidate for #20736 ?

**Comment by shashi** [comment]
@tkelman made that easy for you: https://github.com/JuliaLang/julia/pull/20825

**Pull request merged**
