### PR TITLE
Fix #17680 (sparse general concatenation) and #17686 (concatenation of heterogeneous Matrix-Vector combinations)

### LINKED ISSUE #17680: general concatenation (`cat`) of sparse arrays yields dense
```julia
julia> cat((1,2), spdiagm(1:4), spdiagm(1:4))
8×8 Array{Int64,2}:
 1  0  0  0  0  0  0  0
 0  2  0  0  0  0  0  0
 0  0  3  0  0  0  0  0
 0  0  0  4  0  0  0  0
 0  0  0  0  1  0  0  0
 0  0  0  0  0  2  0  0
 0  0  0  0  0  0  3  0
 0  0  0  0  0  0  0  4
```
Cross reference #15172 and #16722. Best!

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request's first commit makes general concatenations (`cat`) of combinations of sparse matrices with sparse matrices or dense matrices/vectors yield sparse arrays, addressing #17680.

The second commit makes `hvcat`s of heterogeneous combinations of dense matrices and vectors yield dense arrays, addressing #17686. The third commit removes seemingly redundant dense array concatenation methods and cleans up the corresponding code.

Given the performance sensitivity of these concatenation methods, would one of the powers that be ask Nanosoldier to perf test this? Thanks and best!

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Would be good to also reference the numbers of the fixed issues in the commit messages.

**Comment by Sacha0** [comment]
> Would be good to also reference the numbers of the fixed issues in the commit messages.

Added. Thanks!

**Comment by tkelman** [comment]
any difference between this and jeff's version at https://github.com/JuliaLang/julia/commit/28ec527384e4ec6b95a35f6b613fd01bd5723648?

**Comment by tkelman** [comment]
it's running the nightly build right now, but hopefully only that @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17690#issuecomment-236095014) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f25ce43dde70fb3b2835b85dfc50e707ca1e78f8/3f773da_vs_d528b63/report.md). cc @jrevels

**Comment by martinholters** [comment]
Performance delta looks like measurement noise.

**Comment by Sacha0** [comment]
Thanks for the reviews and merge!

**Pull request merged**
