### PR TITLE
increase default sleep time

### PR DESCRIPTION
**Pull request by oscardssmith**
the current number is way too low (and when combined with our current behavior of waking up all the threads might even be leading threads to fall asleep before the rest of the threads wake up).

on master, (40 threads) I'm seeing  `@btime Threads.@spawn nothing` be roughly `300μ` while with this patch I'm seeing `16 μs`

### CODE REVIEW

**Comment by KristofferC** [comment]
Based on what? I guess there is some benchmark or something that shows this is better?

**Comment by kpamnany** [comment]
I cannot find the sleep threshold used by Java. @chflood any idea? Cilk has workers sleep after a certain number of steal failures so it isn't time-based. We should probably go this way too, eventually.

We want threads to sleep when there's no work in order to stop burning power, and also to not unnecessarily interfere with other running threads in an oversubscribed system. So there's no clear definition of _better_ here. This threshold was originally 1 second.

Threads going to sleep too quickly is bad because they then have to be woken up, and that does seem to be happening per Oscar -- 16us seems too short a threshold to me.

**Comment by JeffBezanson** [comment]
Spinning longer here lets us pick up new work sooner, but at the cost of delaying checking for I/O. Running the event loop on a dedicated thread should eventually fix that.

**Comment by kpamnany** [comment]
> Spinning longer here lets us pick up new work sooner, but at the cost of delaying checking for I/O. Running the event loop on a dedicated thread should eventually fix that.

I don't understand this? If `sleep_threshold` is larger, [this check](https://github.com/JuliaLang/julia/blob/master/src/partr.c#L304) will return 0 for longer but that just calls `jl_process_events()` [here](https://github.com/JuliaLang/julia/blob/master/src/partr.c#L412), so why is I/O checking delayed?

**Comment by vtjnash** [comment]
oh, that seems pretty good then already, at the cost of possibly doing a lot more syscalls (doing them more frequently than we should, since we could have simply blocked into this syscall instead)

**Comment by kpamnany** [comment]
True. Doesn't affect anything though, except burning a bit more power.

Merge this?

**Comment by kpamnany** [comment]
Bump.

**Comment by oscardssmith** [comment]
do we want to merge this? @JeffBezanson @vtjnash

**Pull request merged**
