### PR TITLE
Distributed test suite: if `Threads.nthreads() > 1`, skip certain tests

### PR DESCRIPTION
**Pull request by DilumAluthge**
1. If `Threads.nthreads() == 1`, then we will run all tests.
2. If `Threads.nthreads() > 1`:
    - If `ENV["JULIA_TEST_INCLUDE_THREAD_UNSAFE"] == "true"`, then we will run all tests.
    - Else, we will skip a few tests that are known to non-deterministically fail when there are multiple threads.

### CODE REVIEW

**Review by tkf — COMMENTED** [review]
Yes, I think it's nice to mark thread-incompatible tests like this.

**Review by vchuravy — APPROVED** [review]

**Review by tkf — APPROVED** [review]
LGTM!

**Comment by KristofferC** [comment]
If Distributed needs to be tested both threaded and unthreaded it should just do so, like:

https://github.com/JuliaLang/julia/blob/d39b2c0d147d4fdf09b66f63c23027ed9f10a7d1/test/threads.jl#L5-L11

It should not be an external "setting" so that to fully test Julia, one needs to run the full test suite multiple times with the different settings.

**Comment by DilumAluthge** [comment]
This is incorrect. The entire Julia test suite needs to be run both singlethreaded and multithreaded. There are bugs that only show up in one case versus the other.

Just off the top of my head, there was a test for one of the invalid sysimage code paths that passed when singlethreaded but failed when multithreaded. More specifically, we were testing that a segfault would not be signaled when testing a certain code path. However, when we ran the tests with multiple threads enabled, the test segfaulted. This indicated that there was a bug in this particular code path.

That test was not part of the Distributed test suite.

**Comment by DilumAluthge** [comment]
> when 99%+ of the tests execute exactly the same no matter that setting.

This is just not true. There are all kinds of subtle bugs in Julia that are absent when threading is disabled and are present when threading is enabled. The only way to test for these bugs is to run the test suite both with and without threading.

As I said on Slack, in order to conserve CI resources, we only do this on linux64. On linux64, we run the test suite both with and without threading. On all other platforms, we only run the test suite once.

**Pull request merged**
