### PR TITLE
Aways make a copy of the finalizer list to run before running finalizers

### PR DESCRIPTION
**Pull request by yuyichao**
This is trying to reduce the pain of synchronizing GC and finalizers run in threading. In particular, moving the finalizer run out of the critical region locked by `finalizers` lock in `jl_finalize` mean that we can now safely add a GC transition before acquiring the lock and `jl_gc_collect` can also acquire the lock without possible dead lock. (We currently don't need to hold the lock in `jl_gc_collect` since we don't allow unmanaged code to run during a GC yet.)

Another possible solution is to check `jl_in_gc` in `jl_finalize` and don't do anything if we are in a collection or in another finalizer. My current conclusion is that doing a copy and allow calling `finalize` is a saner schematic and is actually simpler to implement with threading.

Tests coming soon.

@vtjnash @carnaval

### CODE REVIEW

**Comment by yuyichao** [comment]
Test added. Note that the test failure on current master should be repeatable but not too robust. It could easily be made pass if we change the order we run the finalizers. Nonetheless, the test should always pass after this PR.

**Comment by yuyichao** [comment]
Any comments?

**Comment by tkelman** [comment]
use a better variable name than `tmp`?

**Comment by yuyichao** [comment]
Err, `tmp_list`, `local_list`, `local_copy`?

**Comment by tkelman** [comment]
`copied_list` ? or any of yours, all ae better than `tmp`

**Comment by yuyichao** [comment]
Done. `copied_list` it is.

**Comment by yuyichao** [comment]
Apparently our CI's don't like the new variable name ;-p

AppVeyor Win64 is the known hang after the `example` test. The Travis-PR OSX failure is very similar to one of the crash in https://github.com/JuliaLang/julia/pull/14024#issuecomment-161052494.

Force pushed to restart the CI.

**Comment by yuyichao** [comment]
I'll merge this weekend if no one objects.

**Comment by vtjnash** [comment]
sgtm

**Pull request merged**
