### PR TITLE
`@nospecialize` for `identity`

### PR DESCRIPTION
**Pull request by Tokazama**

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
We generally don't need to add `@nospecialize` annotation if a generic function only contains a single method (and `identity` will rarely be extended), but approved nevertheless as it doesn't hurt anything anyway.

**Comment by Tokazama** [comment]
I know there's a point where specialization doesn't occur, but I figure that we _never_ wanted it to specialize and that even this was more than we wanted:

```julia
julia> using MethodAnalysis

julia> using StaticArrays

julia> length(methodinstances(identity))
18

julia> identity(SVector(1, 2, 3));

julia> length(methodinstances(identity))
19

julia> foo(x) = identity(x)
foo (generic function with 1 method)

julia> foo(SVector(1, 2, 3, 4));

julia> length(methodinstances(identity))
20

```

**Comment by aviatesk** [comment]
Please note that `@nospecialize` influences dispatch only, does not intervene into inference in anyway. See https://github.com/JuliaLang/julia/pull/41931 for more explanation.

**Comment by Tokazama** [comment]
The goal here was just to avoid codegen. I'm assuming that if this made it so we couldn't even infer what type `identity` returned that it would be a bad idea.

**Comment by aviatesk** [comment]
"codegen" would be avoided even as is assuming the method body of `identity` is inlined always.

**Comment by aviatesk** [comment]
It's simply that that information was used for Julia-level inference but it doesn't necessarily imply whole codegen process.

**Comment by Tokazama** [comment]
Gotcha. Thanks for the clarification.

**Pull request merged**
