### PR TITLE
[release-0.5] backports for 0.5.0 rc2

### PR DESCRIPTION
**Pull request by tkelman**
A few things aren't here yet. The curl build still needs a bit more work on master and might have to wait until rc3, and the SSH tests are disabled here with a commit that we'll hopefully be able to revert at some point, since they're causing issues on the buildbots.

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0030eec2f332f353e6890ca289ac2aca55532dde")`

(vs 0.5.0-rc0)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17960#issuecomment-239087372) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/5a510a2e7c6bfd6973d60924970723bdcd67ed50/92c85fd_vs_0030eec/report.md). cc @jrevels

**Comment by tkelman** [comment]
PkgEval comparison (vs rc0) finished: https://gist.github.com/c5e9489fdacaeed4a31abfe69ebbbe1b

This is a few more failures than I would like to see (9, though 8 packages went from failing to passing???), would be good to get a few more eyes looking through the failure logs.

**Comment by KristofferC** [comment]
For `BlockArrays` it is because a typo: https://github.com/JuliaLang/julia/blob/ad15fc942661dee16cbd9a16851e0b7bee1dbd48/base/special/trig.jl#L324

**Comment by swt30** [comment]
Similar thing for `ForwardDiff` I think
```
ERROR: LoadError: LoadError: UndefVarError: atahn not defined
in macro expansion; at /home/vagrant/.julia/v0.5/ForwardDiff/test/DualTest.jl:388 [inlined]
```

**Comment by tkelman** [comment]
BiomolecularStructures and NullableArrays pass for me locally, so those may have been flukes. That leaves
CovarianceMatrices (cc @gragusa) and MixedModels (cc @dmbates) that look like real failures we don't know the cause of, worth bisecting.

**Comment by tkelman** [comment]
@andreasnoack CovarianceMatrices was broken by the backport of #17909, can you take a look?

**Comment by andreasnoack** [comment]
Sure. I'll do that.

**Comment by tkelman** [comment]
MixedModels bisected to the same commit.

**Comment by andreasnoack** [comment]
@tkelman Thanks for catching this before it got backported. [This check](https://github.com/JuliaLang/julia/blob/master/base/linalg/cholesky.jl#L184) is comparing a `Char` and a `Symbol` so it ends up exactly the opposite of what it should be. The tests actually captured this but unfortunately I convinced myself that the tests were wrong. https://github.com/JuliaLang/julia/pull/17985 reverts the old commit and adds a new commit without the bug.

**Pull request merged**
