### PR TITLE
typemap: fix bug with handling of Tuple{}

### PR DESCRIPTION
**Pull request by vtjnash**
introduced by e0aee185e60d8afbb53d93404ddede203d1ddfaf

### CODE REVIEW

**Comment by Keno** [comment]
Add a test?

**Comment by JeffBezanson** [comment]
I see; 793481037a30fb02b09efdad447fa1d13e11390c introduced the first use of `Tuple{}` as a typemap key.

**Comment by JeffBezanson** [comment]
Test case from #26607 should be added.

**Comment by ararslan** [comment]
Why was this merged without a test?

**Pull request merged**
