### PR TITLE
Added condition for checking negative indices in array

### LINKED ISSUE #32307: Array allocation with negative size should throw a `ArgumentError` not a `ErrorException`
```
julia> try 
       fill('a', -10)
       catch err
       @show typeof(err)
       end

typeof(err) = ErrorException
```

### PR DESCRIPTION
**Pull request by dnabanita7**
Fixes #32307
changed in abstractarray.jl

### CODE REVIEW

**Comment by tomaklutfu** [comment]
`i` is defined only in the function body but the logic is in the outside. At the same time, this method already correctly defined 3 lines above. Besides, correct error checking should be in `fill` as pointed out in that issue.

**Comment by KristofferC** [comment]
As a tip, it is generally a good idea to try the change locally first. Also, adding a test is also important (to the point of being a requirement before things gets merged).

**Comment by mbauman** [comment]
Welcome and thanks for trying to fix this bug!  What we want to do here is change an `error("invalid Array dimensions")` to `throw(ArgumentError("invalid Array dimensions"))`.  To do that, we need to find where that error got thrown.  And for that, you can just follow the stacktrace from the original issue:

```julia
julia> fill('a', -10)
ERROR: invalid Array dimensions
Stacktrace:
 [1] Array at ./boot.jl:404 [inlined]
 [2] Array at ./boot.jl:413 [inlined]
 [3] fill at ./array.jl:395 [inlined]
 [4] fill(::Char, ::Int64) at ./array.jl:393
 [5] top-level scope at REPL[1]:1
```

Unfortunately, following [`boot.jl:404`](https://github.com/JuliaLang/julia/blob/86bf1b240950acb47eedfab13fa8609c71e21af6/base/boot.jl#L404) takes us to one of the few places where the language is implemented in C (and not Julia).  So where you'll need to go to fix this change is going to be somewhere in [`array.c`](https://github.com/JuliaLang/julia/blob/86bf1b240950acb47eedfab13fa8609c71e21af6/src/array.c).  Searching that file for `invalid Array dimensions` points to three places where a `jl_error(...)` call needs to be replaced with a `jl_exceptionf(jl_argumenterror_type, ...)`.  That's the ticket to resolving this issue.

**Comment by Naba7** [comment]
Thanks a lot @mbauman Can you please tell how can I know from the error trace that it is from array.c not from array.jl. Because I have been searching in array.jl and abstractarray.jl but no success.

**Comment by mbauman** [comment]
The stacktrace shows that the method that threw the error is:

https://github.com/JuliaLang/julia/blob/86bf1b240950acb47eedfab13fa8609c71e21af6/base/boot.jl#L404-L405

That `ccall` means it's making a C call into Julia's C implementation — and I know that the relevant C definitions are in `src/array.c`.  You can also just search for the error string itself:

```
$ ack "invalid Array dimensions"
src/array.c
67:            jl_error("invalid Array dimensions");
255:                jl_error("invalid Array dimensions");
359:            jl_error("invalid Array dimensions");
...
```

**Comment by Naba7** [comment]
Thanks I figured it out and am making changes.

**Pull request closed without merging**
