### PR TITLE
jl_profile_atomic lock around jl_spawn to prevent macos profiling deadlock

### LINKED ISSUE #43578: Profile: `@profile` hanging on MacOS 12
On master and 1.6.4, on MacOS (other platforms not tested yet)

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.1183 (2021-12-28)
 _/ |\__'_|_|_|\__'_|  |  Commit 693b4471fa (0 days old master)
|__/                   |

julia> versioninfo()
Julia Version 1.8.0-DEV.1183
Commit 693b4471fa (2021-12-28 10:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6

(jl_ePM8ng) pkg> add FFMPEG
...
Precompiling project...
  44 dependencies successfully precompiled in 10 seconds. 3 already precompiled.

julia> using Profile

julia> @profile using FFMPEG
# hangs with no CPU usage
```

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #43578

Thanks to @dnadlinger and @staticfloat for the pointers on this.

```
julia> using Profile

julia> @profile while true
              run(`pwd`)
              end
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
# runs continuously, and signal handling still works, unlike on master
```

### CODE REVIEW

**Comment by IanButterworth** [comment]
Maybe this is doing something bad.. I just tried `ProfileView` with this PR and the Gtk window just shows black, which doesn't happen on master

**Comment by IanButterworth** [comment]
The last commit doesn't fix the Gtk issue, but it seems like a better approach

**Comment by giordano** [comment]
I presume the gtk issue isn't https://github.com/JuliaGraphics/Gtk.jl/issues/590?

**Comment by IanButterworth** [comment]
Yeah! That fixes ProfileView. Thanks.

Unfortunately more testing of this PR has shown it's interfering with execution time substantially
```
julia> t = Timer(10)

julia> @profile while isopen(t)
       run(`pwd`)
       sleep(0.1)
       end
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia

julia>
```

So `run` only gets to acquire the profiling lock 3 times in 10 seconds

**Comment by IanButterworth** [comment]
Switching the lock nesting fixes that ^

**Comment by vtjnash** [comment]
superseded by #43701

**Pull request closed without merging**
