### PR TITLE
fix inference of `split_rest`

### LINKED ISSUE #47326: Type instability in front slurping of tuples.
There's an unfortunate asymmetry when slurping tuples in 1.9.0-DEV.1651, e50b32f278

MWE:

```
function fun1(args...)                                                        
    head..., tail = args                                                      
    head                                                                      
end                                                                           
                                                                              
function fun2(args...)                                                        
    head, tail... = args                                                      
    tail                                                                      
end

@code_warntype fun1(1,2,3)
@code_warntype fun2(1,2,3)
```
`fun1(1,2,3)` says `Body::Tuple{Vararg{Int64}}`, whereas `fun2(1,2,3)` says `Body::Tuple{Int64, Int64}`.

### PR DESCRIPTION
**Pull request by simeonschaub**
fixes #47326

### CODE REVIEW

**Comment by jakobnissen** [comment]
Just to copy a comment over from the other PR: I wonder if this aggressive constprop might be better to have directly in the lowering, if possible, such that it applies to all cases of `Base.split_rest` created using slurping. I don't know if it's feasible to do at the callsite though.

**Review by aviatesk — APPROVED** [review]
Good catch!

**Comment by aviatesk** [comment]
> Just to copy a comment over from the other PR: I wonder if this aggressive constprop might be better to have directly in the lowering, if possible, such that it applies to all cases of `Base.split_rest` created using slurping. I don't know if it's feasible to do at the callsite though.

We really can't generally transform `Base.split_rest` into code with some fixed length, as Julia's lowering pass doesn't known type information of object being slurped.

**Comment by aviatesk** [comment]
> would it be possible to somehow say "constprop the `split_rest` call, regardless of the type of `args`"

So you basically want to annotate `@constprop :aggressive fun1` automatically since it contains slurping, or force const-prop' for `Base.split_rest` calls whenever they appear? The second option might be reasonable, but we will need to implement callsite `@constprop` annotation support first.

**Comment by jakobnissen** [comment]
I had the latter in mind, but don't know if it's technically feasible.

**Pull request merged**
