### PR TITLE
replace Array{...}(shape...)-like calls in base/[e-k]*

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request replaces `Array{...}(shape...)`-like calls in base/[e-k]*.jl. Ref. #24595. Best!

### CODE REVIEW

**Comment by fredrikekre** [comment]
Something is up here too, but this information is not very useful, same on all workers 
```
89.381032 *** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[2]: *** [/home/travis/build/JuliaLang/julia/usr/lib/julia/sys.o] Error 1
89.381268 make[2]: Leaving directory `/home/travis/build/JuliaLang/julia'
make[1]: *** [julia-sysimg-release] Error 2
89.381555 make[1]: Leaving directory `/home/travis/build/JuliaLang/julia'
make: *** [/home/travis/build/JuliaLang/julia/doc/_build/html/en/index.html] Error 2
```

**Comment by Sacha0** [comment]
Should be fixed. Thanks! :)

**Comment by Sacha0** [comment]
Absent objections or requests for time, I plan to merge these changes this evening PT or later. Best!

**Review by fredrikekre — APPROVED** [review]

**Comment by Sacha0** [comment]
Thanks `@fredrikekre`! :)

**Pull request merged**
