### PR TITLE
Make Slot a Union type

### LINKED ISSUE #27202: Make Core.Slot a Union type instead of a generic abstract type
For the moment, Core.Slot is defined in src/jltypes.c with 
```
jl_abstractslot_type = jl_new_abstracttype((jl_value_t*)jl_symbol("Slot"), core, jl_any_type,
                                               jl_emptysvec);
```

This type is only ever used in the compiler as a supertype of SlotNumber and TypedSlot, and widely so in queries of the form `isa(x, Slot)`. Since I don't believe it is supposed to be extended with any other subtype, I think it should be defined as `Union{SlotNumber, TypedSlot}` instead of its current definition. 
The main interest of this is that it would allow the compiler to union-split after all the queries `isa(x, Slot)`, which is impossible in the current setting.

As a sidenote, maybe its definition should also be added to the commented part of base/boot.jl, as well as that of SlotNumber and TypedSlot.

### PR DESCRIPTION
**Pull request by Liozou**
Closes #27202 

I'm not familiar with these files, so it would be good if someone checked I haven't broken anything by moving Slot from the C builtins to boot.jl

### CODE REVIEW

**Comment by vtjnash** [comment]
Nice work! I haven't reviewed in much detail, but I'm amazed how small this is. Very recently though, `TypedSlot` became unused (outside of a brief appearance in the IR between inlining and optimization in Core.Compiler). We can still merge this, but if you're able to completely remove all references to it outside of `base/compiler/optimize.jl` and `base/compiler/ssair/slot2ssa.jl`, that would be even more epic! :)

**Comment by Liozou** [comment]
On master `TypedSlot` seems to be still used in boot.jl and compiler/utilities.jl so I'm afraid to break everything if I replace `Slot` by `SlotNumber` almost everywhere... Is this removal of `TypedSlot` on a specific branch?

**Comment by vtjnash** [comment]
It's essentially executable documentation at
https://github.com/JuliaLang/julia/blob/db158b85b7b0c9bcdf8d6c80379ab0e091cbbafa/base/boot.jl#L443

 The work hasn't yet been done to detangle and remove the references to TypedSlot (it's only just recently become feasible).

**Comment by Liozou** [comment]
OK, in that case I'm going to have a look at what can be trimmed

**Comment by Liozou** [comment]
I made a scan of all the uses of `Slot` in the code and, apart from `optimize.jl`, it also mainly appears in `typelattice.jl` and `abstractinterpretation.jl`. I suppose you would like to replace it with `SlotNumber` as much as possible there, but I have no idea whether that would be correct in these cases since I don't know this part of the compiler at all.
As for `TypedSlot` itself, I remarked that it was used to define `slot_id` twice: once in `utilities.jl` and the other in `ssair/slot2ssa.jl`. Should one of the two be removed?

**Comment by vtjnash** [comment]
It's referenced (but will never actually appear) in abstractinterpretation.jl. It might appear in the typelattice, but you can define TypedSlot in that code (in Core.Compiler, and not a subtype of Slot) and handle it in the few cases where it is observed to appear.

**Comment by Liozou** [comment]
`TypedSlot` never explicitly appears in `abstractinterpretation.jl`, only `Slot` does and I don't know whether it can or cannot contain a `TypedSlot` value. This is kind of my issue whenever `Slot` is used: I never know whether it is safe to replace it by `SlotNumber` or not.

**Comment by aviatesk** [comment]
Will be replaced by #48693.

**Pull request closed without merging**
