### PR TITLE
[release-0.5] final backports for 0.5.0

### LINKED ISSUE #17418: Checklist of steps towards 0.5 release [candidates]
[minor edits / cross referencing welcome here, but copy-paste your changes before submitting in case of multiple people trying to simultaneously make edits and be careful not to overwrite changes made by others - for additions, or deletions?, leave comments below and we'll discuss before adding to the master list]

Timeline for things that need to happen in a specific order:
- [x] finish the remaining breaking/feature items on the 0.5.0 milestone
  1. SSH support in Pkg: https://github.com/JuliaLang/julia/issues/16041, PR at https://github.com/JuliaLang/julia/pull/17391 - assignees = Art, Keno, and myself
  2. safe non-traditional array indexing: https://github.com/JuliaLang/julia/issues/16973, (possibly stale?) PR at https://github.com/JuliaLang/julia/pull/17228 - assignees = Tim, Jeff, core team for feedback
- [x] announce feature freeze by changing `VERSION` from `0.5.0-dev` to `0.5.0-pre` #17503
  - master becomes (temporarily) locked for anything other than bugfixes (preferably release-critical ones, anything not absolutely critical can potentially wait until backporting for 0.5.1), doc fixes or test additions
- [x] create `release-0.5` branch, change master `VERSION` from `0.5.0-pre` to `0.6.0-dev` to reopen master for breaking changes
  - this could happen immediately after the feature freeze step, but unless progress towards breaking 0.6 changes is inconveniently blocked here we might want to wait a short time
- [x] at this point commits should not be made directly to the `release-0.5` branch without prior discussion, the branch will operate in release mode:
  1. bugfixes should be made as usual via PR's to master first, wherever applicable there
  2. if you think something is a backport candidate, ask about it with a comment, we will have some discussion and decide yes or no on backporting during the RC process
  3. a contributor will mark the issue/PR with the `backport pending 0.5` label, or ping the `@juliabackports` user in a comment (which sends a message to https://groups.google.com/forum/#!forum/julia-backports which we will monitor) if there's a needed commit to master without an associated issue/PR number (we should almost always avoid doing that)
  4. backporting changes should be done as follows:
    - `git checkout release-0.5`
    - `git pull`
    - `git checkout -b $USER/backport-foo`
    - `git cherry-pick -x -e SHA`
    - Edit the commit message to add "ref #..." so the cross-reference link shows up to the associated issue/PR.
    - Open a pull request targeted against the `release-0.5` branch (there's a github dropdown menu on the open PR page) so CI runs. Please add `[release-0.5]` to the title of the PR so it's more obvious that the PR is against the release branch and not master.
    - If we have a lot of these, I will handle the backporting myself with a series of rollup pull requests to lessen the CI load.
- [x] when the last RC1-critical cleanup items (see below) are finished, we tag v0.5.0-rc1, build binaries, and announce to the mailing lists
  - automatic windows code signing is not working right now on the buildbots, so this will have to be done manually on a windows machine by someone who has access to the certificates - probably me
 -  any users and package authors who've been waiting to test their code and update their packages for 0.5 should do so
  - the most recent RC will be available under Travis `language: julia` as a `julia: 0.5` option and AppVeyor with an `0.5-latest` url, but `release` will not change until 0.5.0 final is tagged
- [x] repeat the last few steps in the process, targeting 1 RC per week, until we're satisfied with being ready to tag v0.5.0 final.
  - I'll probably handle most of the backports at this stage, and run PackageEvaluator on the proposed changes to make sure we don't introduce regressions between successive RC's
- [ ] tag v0.5.0 final, celebrate, :fireworks: :beers: etc, get 0.6 going and [onwards towards 1.0, world domination](https://www.youtube.com/watch?v=5gXMpbY1kJY)
  - bugfix backport 0.5.x releases will happen at a target of one per month, as we've been doing
  - change `VERSION` on `release-0.5` branch to `0.5.1-pre`

Things that can happen at any time but need to be done (help welcome!) before RC1:
- [x] remaining NEWS and doc additions for Stringapalooza, threads, IOContext https://github.com/JuliaLang/julia/issues/16763 and all other breaking changes, deprecations, and major feature additions and performance changes that users should know about (e.g. startup time on Windows, LLVM version, debugger availability, iterator traits #15977, #17439, etc)
- [x] deprecations still not in NEWS like #16603 and many others (done in #17779)
- [x] make sure CI, buildbots, and tests in both source builds and binary installs are all happy with the final set of changes (linux binaries need https://github.com/JuliaLang/julia/issues/17602#issuecomment-237190583 fixed prior to 0.5.0 final to get rid of a warning when libgfortran is not installed system-wide)
- [x] make sure `make release-candidate` passes and checklist will all work, and keep it that way (doctests etc)
- [x] fix final important straggler bugs, e.g. Pkg.checkout issues, deciding what to do about ARM/Power breakage (maybe use a different LLVM version but only on those architectures, if that's the best fix)

Things that can start now but will go on between RC1 and v0.5.0 final:
- [ ] fixing broken packages! see http://pkg.julialang.org/pulse.html, there's a lot of work to do to bring the ecosystem to a state where it works as well on 0.5 as it does on 0.4 right now
- [x] identifying and fixing any release-blocking bugs that we don't know about yet and/or can't fix before we decide to tag RC1
- [x] review parts of the documentation that aren't tested by doctests and make sure they're up to date (moved from rc1 to ongoing)
- [x] review issues and PR's (both open and closed) marked with needs-docs and needs-tests and rectify any we can (moved from rc1 to ongoing)

The later pieces of this have been my policy for release management ever since the 0.3.x backports and 0.4 RC's, which has been working pretty well from my impression. Feedback on this is welcome, and I'll be turning these items into a formal written release/backporting policy document going forward.

### PR DESCRIPTION
**Pull request by tkelman**
closes #17418 

will run pkgeval, and 
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

### CODE REVIEW

**Comment by musm** [comment]
I would add https://github.com/JuliaLang/julia/pull/18368 
Since the docs are wrong

**Comment by MichaelHatherly** [comment]
https://github.com/JuliaLang/julia/pull/18229 should be fine to backport as well &mdash; if it's not too late?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18546) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4b6a59a0360289d214825975110a52b1fed21709/8d77fb1_vs_9c76c3e/report.md). cc @jrevels

**Comment by tkelman** [comment]
binaries for testing
https://julianightlies.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-b9ec73c89f-linux64.tar.gz
https://julianightlies.s3.amazonaws.com/bin/linux/x86/0.5/julia-0.5.0-b9ec73c89f-linux32.tar.gz
https://julianightlies.s3.amazonaws.com/bin/linux/ppc64le/0.5/julia-0.5.0-b9ec73c89f-linuxppc64.tar.gz
https://julianightlies.s3.amazonaws.com/bin/linux/arm/0.5/julia-0.5.0-b9ec73c89f-linuxarm.tar.gz
https://julianightlies.s3.amazonaws.com/bin/osx/x64/0.5/julia-0.5.0-b9ec73c89f-osx.dmg
https://julianightlies.s3.amazonaws.com/bin/winnt/x64/0.5/julia-0.5.0-b9ec73c89f-win64.exe
https://julianightlies.s3.amazonaws.com/bin/winnt/x86/0.5/julia-0.5.0-b9ec73c89f-win32.exe

ARM and Windows ones are still building but should be up before too long.

**Comment by tkelman** [comment]
Failures were in Cairo, Mamba, and Gadfly. Cairo we've seen before, might be fixed in that package but need a tag I think? Mamba and Gadfly should be fixed by #18452 which I'll probably merge into this branch but does need a test.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

**Comment by tkelman** [comment]
@jrevels recent nanosoldier webhooks aren't going through, "We had a problem connecting to the server. The most common problem with these types of errors is a misconfigured SSL certificate. Try verifying your certificate chain."

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.5")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18546#issuecomment-247843854) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/13ed4cbbc2eb62a3c78a9d7b4ce53431bffca130/4a6e3b7_vs_9c76c3e/report.md). cc @jrevels

**Comment by tkelman** [comment]
https://gist.github.com/525cd694db739bc38a7b17761fbaa2d8

- same Cairo segfault we've seen before, I started this run before making the tag with the fix
- GeoIP didn't finish running properly in the 0.5.0-rc4 baseline run for some reason, but that package is problematic anyway http://pkg.julialang.org/detail/GeoIP.html
- NullableArrays looks like the same issue we were seeing in https://github.com/JuliaLang/julia/pull/18478#issuecomment-247788353 and https://github.com/JuliaStats/NullableArrays.jl/issues/146, probably worked around by the latest tag

Given @timholy's comment at https://github.com/JuliaLang/julia/pull/18401#issuecomment-247754494, I think I'm going to revert https://github.com/JuliaLang/julia/pull/18546/commits/15096f04a6d521c76a535ee642a745b40f5085de (cc @mbauman) and rerun pkgeval one hopefully-last time for good measure.

**Comment by timholy** [comment]
Re #18401: out of curiosity, did you get any failures because of it? It is a tough call: on one hand it might conflict with a "better" way to solve the problem for 0.6, on the other hand it fixes a regression from 0.4. I tend to be conservative by not adding behavioral changes at the last minute, but I recognize this is a difficult decision.

**Comment by tkelman** [comment]
From that most recent pkgeval run, it neither caused not solved any new failures afaict. However note that PyPlot is broken right now so any regressions in packages using it might have been missed.

**Comment by tkelman** [comment]
I'm about to merge and tag this. https://gist.github.com/636a2c609ac0ce380053f0973eb47746
Speak up soon if you think something's missing or I should reconsider any of what's here.

**Comment by ViralBShah** [comment]
Is #17602 release blocking, or should it be tagged 0.5.x?

**Pull request merged**
