### PR TITLE
Rename super() to supertype()

### LINKED ISSUE #14337: Rename super() to supertype()
There's currently a naming inconsistency between `subtypes()` and `super()`. How about renaming the latter to `supertype()`. That would make it more explicit and easier to find.

### PR DESCRIPTION
**Pull request by nalimilan**
This name is more explicit and consistent with subtypes().
Also rename promote_to_super() for consistency, but without
deprecation as it isn't exported.

Fixes #14337.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I'm in favor of this rename, but I suspect we should wait until after potential shakeup due to adding protocols and/or traits.

**Comment by nalimilan** [comment]
Why not, but this doesn't strike me as really affecting the same code, nor requiring the same kind of change.

**Comment by StefanKarpinski** [comment]
Eh, that's fair. I guess I'm just wondering somewhere if the whole notion of `super` won't go away. But maybe we should just do this anyway. It's a much better name.

**Comment by nalimilan** [comment]
I'm fine with waiting for a bit until we know whether abstract types might go away completely.

**Comment by jakebolewski** [comment]
They are not anytime soon.

**Comment by JeffreySarnoff** [comment]
supertype is an easy preference 

*and super(x) should be reflexively assignable*

**Comment by mason-bially** [comment]
Also, I think based on my understanding of the proposals, although I might be wrong, but supertype would still be a helpful utility function regardless of the changes.

**Comment by JeffBezanson** [comment]
+1
Sorry this took long enough that it needs a rebase. But, let's rebase and merge it.

**Comment by nalimilan** [comment]
No problem. I've rebased it and will merge when the tests pass.

**Comment by tkelman** [comment]
please don't restart failed travis jobs without making a note and saving the log.

**Comment by nalimilan** [comment]
Sorry, I always forget that Travis doesn't keep the log available.

**Pull request merged**
