### PR TITLE
New doc syntax

### PR DESCRIPTION
**Pull request by MikeInnes**
I'm sure this implementation is far from acceptable (aesthetically and as far as the tests are concerned) but hopefully the core idea is sound. I've used the new syntax for the `include` doc string for illustration, and as you can easily verify from `Base.DocBootstrap.docs` the plain docstrings we already have are successfully stored, even before the doc system itself is in place (although we don't process these just yet).

(@Keno @ViralBShah apologies that this is four hours late)

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Cool! Just giving this a try now. Some results:

At the REPL triplequoted strings work fine for methods:

```
julia> """f"""
       f() = ()
f (generic function with 1 method)

julia> Main.META
ObjectIdDict with 2 entries:
  #= circular reference =# => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["Documen…
  f                        => Base.Docs.FuncDoc([f() at none:2],Dict{Method,Any}(f() at…
```

Single quotes don't yet, they probably should:

```
julia> "g"
       g() = ()
ERROR: unsupported or misplaced expression single_quoted_string
```

I've not had any luck getting a source file documented yet. [This gist](https://gist.github.com/MichaelHatherly/fe80e8daa2086cb568f1) contains some test cases that should probably be supported. Where should the docs end up? ``Base.DocBootstrap.docs`` only has some stored from ``Base.Markdown`` and ``Base``, ``Testcases.META`` is undefined. Perhaps I'm just missing something quite basic?

**Comment by MichaelHatherly** [comment]
Switching all the docstrings in the gist to ``@doc`` syntax shows up a few problems we have currently:

The syntax

```jl
@doc """F""" ->
function F end
```

gives a ``type Symbol has no field args`` error, presumably because that syntax is quite new.

Bitstype

```jl
@doc """B""" ->
bitstype 8 B
```

is being stored as ``nothing`` in ``Testcases.META``.

The inner constructor

```jl
    @doc """C_1""" ->
    C(x) = new()
```

produces

```
MethodError: `doc!` has no method matching doc!(::Type{Testcases.C}, ::Method, ::Base.Markdown.MD, ::Expr)
```

I can open separate issues for each of these, but perhaps it's best to just put the fixes in here and now?

**Comment by prcastro** [comment]
:+1: thanks for doing this

**Comment by one-more-minute** [comment]
Yeah so the doc macro is a little out of date for some of the newer 0.4 features, I think there are separate issues open for that.

I think the module thing isn't working because technically you're no longer at the top level inside a module. So I just need to patch the part that parses modules too.

**Comment by ScottPJones** [comment]
:+1: :party:

**Comment by ViralBShah** [comment]
:+1:

**Pull request merged**
