### PR TITLE
RFC: Add a guideline to avoid `Julia` in package names

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by IainNZ** [comment]
Woops, forgot av skip. Cancelled Travis.

**Comment by johnmyleswhite** [comment]
+1

**Comment by nalimilan** [comment]
+1

Though I would also stress that the convention of the `.jl` suffix makes adding `Julia` in the name redundant.

**Comment by IainNZ** [comment]
I see what you mean @nalimilan, but I'll just add this for to keep it simple - could reword it later to fit that in somewhere.

**Pull request merged**
