### PR TITLE
updated improvements to accuracy/performance for float^integer

### PR DESCRIPTION
**Pull request by stevengj**
Updated version of #24500 to allow 1ulp variations in tests.

### CODE REVIEW

**Comment by musm** [comment]
Does this patch loosen accuracy to within 1 ulp instead of 0.5 ulp for literal powers?

**Comment by StefanKarpinski** [comment]
It's closer than what we have now but we're also not doing very well currently. However, on my system this PR is still within 0.5 ulps:
```jl
julia> function powerr(z::T, x, y) where T
           Z = big(x)^y
           T(abs(Z - z)/eps(T(Z)))
       end
powerr (generic function with 1 method)

julia> powerr(0.7130409001548401^-2, 0.7130409001548401, -2)
0.174427353514541

julia> powerr(0.09496527f0^-2, 0.09496527f0, -2)
0.3787126f0

julia> powerr(0.20675883960662367^-100, 0.20675883960662367, -100)
0.3435074562833216

julia> powerr(0.6123676f0^-100, 0.6123676f0, -100)
0.4938203f0

julia> powerr(0.004155780785470562^-1, 0.004155780785470562, -1)
0.434970050207055
```
My analysis is that the computation of `x^y` can have up to 0.5 ulp error and the literals for the "correct" answer can also have up to 0.5 ulp of rounding error, so yes, this allows up to 1 ulp error from the closest rounded value in the correct type, but that's not the same as 1 ulp of actual error. Perhaps it would be better to test for error from the true value as a BigFloat?

**Comment by stevengj** [comment]
@StefanKarpinski, updated to test against the exactly rounded value from bigfloat.

**Comment by StefanKarpinski** [comment]
I checked beforehand and all the values were already the exactly rounded values. I think the errors I'm seeing above imply that if we get adjacent float values on other systems they are more than 0.5 ulps away from the true answer. But I'm ok with that: we just have to claim that these functions are within 1 ulp rather than within 0.5 ulp (although it seems to be 0.5 ulp on x86).

**Review by StefanKarpinski — APPROVED** [review]

**Comment by simonbyrne** [comment]
It's hard to provide guarantees here, since in the general case we're at the mercy of the system libm (since LLVM uses that instead of openlibm).

**Comment by stevengj** [comment]
Ah…  grrr, the test passes on my machine.   Not sure what tests to use here, especially if we can't compare to openlibm.

Maybe just check that the result is the same for float^integer and float^float?

**Comment by StefanKarpinski** [comment]
> Maybe just check that the result is the same for float^integer and float^float?

That seems fine since it effectively tests *this* feature; correctness of float^float is another matter.

**Comment by stevengj** [comment]
The error on Travis i686 (missing exception for `zero(String)`) seems unrelated.

**Comment by stevengj** [comment]
Should be good to merge again?

**Pull request merged**
