### PR TITLE
Always use summary for BoundsError, even with non-AbstractArrays

### PR DESCRIPTION
**Pull request by iamed2**
Previously, BoundsError used `show` when the container wasn't an AbstractArray. That could print a lot of stuff, and customizing it required changing the behaviour of `show`. Now it always uses `summary`, so users can define their own `summary` to customize the display here. 

Also `summary` of a tuple now displays the whole tuple instead of its type. That's usually shorter than printing the type, and it keeps the existing behaviour for BoundsError.

### CODE REVIEW

**Comment by mbauman** [comment]
Oh, I see — this is for the printing of the "parent" object (and not the indices).  Yes, this seems reasonable.  Because I had to look: the default implementation of `summary` is simply printing the type.

**Comment by iamed2** [comment]
I don't know why Travis mac is failing now but I don't think I did it

**Comment by fredrikekre** [comment]
This broke a bunch of doctests, for example it changed
```
julia> "α"[0]
ERROR: BoundsError: attempt to access "α"
  at index [0]
```
to
```
julia> "α"[0]
ERROR: BoundsError: attempt to access String
  at index [0]
```
which IMO is much worse.

**Comment by iamed2** [comment]
Doctests need to be added as a CI step. Is there an issue/PR for that?

**Comment by JeffBezanson** [comment]
They're already run in CI, but haven't been causing builds to fail due to a bug in documenter (it just needs to be upgraded).

**Pull request merged**
