### PR TITLE
Remove outdated `LibGit2.get_creds!` methods

### PR DESCRIPTION
**Pull request by omus**
Part of #20725.

Did a cleanup pass after #23189. 

- Moved the `AbstractCredentials` closer to the other credentials. Previously this code needed to be defined before a `RemoteCallbacks` constructor that no longer exists.
- ~Deprecated~ Remove some `get_creds!` methods which are no longer required since the introduction of the `CredentialPayload`.

### CODE REVIEW

**Comment by omus** [comment]
I'm not sure what the protocol is when we're removing a method with no replacement. I'm assuming it should still go through a deprecation cycle.

**Comment by Keno** [comment]
If it wasn't exported, it doesn't need a deprecation cycle.

**Comment by omus** [comment]
Unfortunately most things in the LibGit2 module aren't exported so it can be difficult to know what is being used externally. I'm pretty sure these methods should be used externally so I'll remove the "base/deprecated.jl" changes.

**Comment by omus** [comment]
Removed the deprecations.

**Comment by tkelman** [comment]
What's the "too many prompts" error on circle about?

Agreed that if things are externally used then it's nice as a courtesy to deprecate instead of hard break, when possible. If not externally used then it's not too important.

**Comment by omus** [comment]
> What's the "too many prompts" error on circle about?

That is coming from the [`challenge_prompt`](https://github.com/JuliaLang/julia/blob/master/test/TestHelpers.jl#L107) and typically only appears during a test failure. It is possible however that this is a false positive as the way we detect "too many prompts" by using a timeout of 10 seconds.

Is there a reason there isn't a full traceback on Circle CI?

**Comment by omus** [comment]
I've triggered a rebuild to see if it reoccurs. The failing Circle CI log can be seen [here](https://circleci.com/gh/JuliaLang/julia/235).

**Comment by tkelman** [comment]
dunno, would we get a better backtrace on that kind of failure on travis? it might be something strange with piping or where stderr goes, or it may relate to #18647?

**Comment by omus** [comment]
On Travis CI I typically see full stack traces for those kind of exceptions. I'm not going to worry too much about it as it's only occurred once.

Any other comments?

**Comment by omus** [comment]
Removed one more unused method. I also changed the first commit message as it referred to deprecating a method instead of removing it.

**Pull request merged**
