### PR TITLE
improve performance for reverse(::String)

### PR DESCRIPTION
**Pull request by KristofferC**
```jl
julia> using Random

julia> s = String([rand(Char) for i in 1:200]) * randstring(200);

# Before
julia> @btime reverse($s)
  15.229 μs (4 allocations: 1.13 KiB)

# After
julia> @btime reverse($s)
  2.277 μs (1 allocation: 1008 bytes)
```

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
LGTM. I wonder if it would be more efficient to iterate forwards and fill the new string from the back.

**Comment by KristofferC** [comment]
Nice idea, I'll try it.

**Comment by KristofferC** [comment]
Indeed!

```jl
function reverse2(s::Union{String,SubString{String}})::String
    out = Base._string_n(sizeof(s))
    offs = sizeof(s) + 1
    for c in s
        offs -= Base.ncodeunits(c)
        Base.__unsafe_string!(out, c, offs)
    end
    return out
end
```

```jl
julia> s = String([rand(Char) for i in 1:200]) * randstring(200);

julia> reverse2(s) == reverse(s)
true

julia> @btime reverse($s)
  15.229 μs (4 allocations: 1.13 KiB)

julia> @btime reverse2($s)
  2.277 μs (1 allocation: 1008 bytes)
```

**Comment by KristofferC** [comment]
Pushed update and updated OP with new results.

**Pull request merged**
