### PR TITLE
rename `colon` to `:`, make other syntax call Base functions

### LINKED ISSUE #25947: scope of identifier names in lowered syntax forms
Is this behavior intended?

```
julia> f(c) = 1:5 ;

julia> f(0)
1:5

julia> g(colon) = 1:5 ;

julia> g(0)
ERROR: MethodError: objects of type Int64 are not callable
Stacktrace:
 [1] g(::Int64) at ./REPL[3]:1
 [2] top-level scope
```

If so, is it documented anywhere what variable/function names could change behavior, or could the names used by changed to be more "internal-looking" (e.g. `__colon__` instead)?

I can see how the behavior is a potentially useful feature:
```
julia> function f()
           colon = function (args...) ; println("args: ", join([args...], ' ')) ; Base.colon(args...) ; end
           1:5
       end
f (generic function with 1 method)

julia> f()
args: 1 5
1:5
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #25947.

I can't see much reason to have `:` call `colon`, so this changes it to be like other operators and parse as a call to `:`.

The next commit changes the lowering of syntax that corresponds to function names to be "hygienic", i.e. always call Base. A long time ago I thought it might be a feature that `a[i]` could call a local function called `getindex`, but (1) that's probably not a good idea, and (2) we're not consistent about this, and most forms already called Base functions. This makes it totally consistent (unless I missed one).

The first commit is just a simple lowering bugfix.

### CODE REVIEW

**Comment by yuyichao** [comment]
Finally....

**Comment by StefanKarpinski** [comment]
I'm all for this change. It would be nice to have a mechanism for overriding non-obvious lowering names. The current names are `hcat`, `vcat`, `hvcat`, `adjoint`, `getindex`, `setindex!`, `getproperty` and `setproperty!`. One thought I had was to have some special name like `__operators__` which is set by default to a module with these names bound. But why not just allow overriding them individually then? Another thought I had was to lower calls to them to `__vcat__`, etc. but have exported aliases from `__vcat__` to `Base.vcat` and so on. That way you can extend `vcat` by its normal name or replace it with a different function (in local or global module scope) by doing `const __vcat__ = myvcat`.

**Comment by JeffBezanson** [comment]
There are more: `broadcast[!]`, `dotview`, `typed_hcat`, `typed_vcat`, `typed_hvcat`, `vect`, `string`, `getfield`, `setfield!`. Then generator expressions are kind of a borderline case, calling `Generator`, `product`, `Filter`, `Flatten`, and `collect`. Then there are a couple other cases: `literal_pow`, the iteration protocol functions, and `lastindex` for `end`. So there's a question of where to draw the line.

The double underscore idea is not bad. We already do that for `@.`, which parses to `@__dot__`.

**Comment by JeffBezanson** [comment]
I should know better than to put 3 unrelated commits in the same PR. Will split these out.

**Comment by mbauman** [comment]
Split into #26073, #26074 and #26380.

**Pull request closed without merging**
