### PR TITLE
call `static_eval` less during codegen

### PR DESCRIPTION
**Pull request by JeffBezanson**
I noticed these while looking at #21369. Is this change valid? I don't see why we would need to try `static_eval` on every call.

### CODE REVIEW

**Comment by vtjnash** [comment]
We should definitely work on removing the remaining usages. Inference should be able to handle all of the optimizations and the semantics shouldn't depend on this function. That said, I think llvmcall and some of the ccall arguments may be leaning on this for evaluating calls to tuple?

**Comment by JeffBezanson** [comment]
I don't see how `ccall` is using this --- it seems to call `static_eval` for itself.

**Comment by vtjnash** [comment]
It has to assume that some earlier pass (such as very-linear-mode) didn't pull its arguments out into SSA position.

**Comment by JeffBezanson** [comment]
That should be easy to ensure via how we lower the `foreigncall` form. Trying to `static_eval` every single call expression doesn't seem like the right way to handle that.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21436#issuecomment-295036559) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/47f668dcb10777f64f52d1bcf511b052af1f13b0/2b7a0b3_vs_085876e/report.md). cc @jrevels

**Review by vtjnash — APPROVED** [review]

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21436#issuecomment-312471394) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f7a10bcf924091601e1f01a8bb269d86824356d2/d92301b_vs_db5ddfa/report.md). cc @jrevels

**Pull request merged**
