### PR TITLE
add reverse(::NamedTuple)

### PR DESCRIPTION
**Pull request by aplavin**
Following recent discussion on slack.
For some reason, my previous PR with the same content was closed without any comment: https://github.com/JuliaLang/julia/pull/45410.

### CODE REVIEW

**Comment by aplavin** [comment]
Test failures seem totally unrelated

**Comment by bramtayl** [comment]
Is this type stable?

**Comment by aplavin** [comment]
@bramtayl, sure:
```julia
julia> nt = (a=1, b=:c)
(a = 1, b = :c)

julia> @code_warntype reverse(nt)
MethodInstance for reverse(::NamedTuple{(:a, :b), Tuple{Int64, Symbol}})
  from reverse(nt::NamedTuple) in Main at REPL[1]:1
Arguments
  #self#::Core.Const(reverse)
  nt::NamedTuple{(:a, :b), Tuple{Int64, Symbol}}
Body::NamedTuple{(:b, :a), Tuple{Symbol, Int64}}
1 ─ %1 = Main.keys(nt)::Core.Const((:a, :b))
│   %2 = Main.reverse(%1)::Core.Const((:b, :a))
│   %3 = Core.apply_type(Main.NamedTuple, %2)::Core.Const(NamedTuple{(:b, :a)})
│   %4 = Main.values(nt)::Tuple{Int64, Symbol}
│   %5 = Main.reverse(%4)::Tuple{Symbol, Int64}
│   %6 = (%3)(%5)::NamedTuple{(:b, :a), Tuple{Symbol, Int64}}
└──      return %6

julia> @btime reverse($nt)
  2.754 ns (0 allocations: 0 bytes)
(b = :c, a = 1)
```

**Comment by N5N3** [comment]
Sorry for the late response. Thanks again for the PR!

**Pull request merged**
