### PR TITLE
WIP: Building a smaller system image.

### PR DESCRIPTION
**Pull request by ViralBShah**
This is a first cut towards building a smaller system image. For now, this is just an experimental branch, but I am hoping we can eventually take this in the direction where we have a smaller Base, and move other code outside of Base, and perhaps some even into packages.

As of now, this is mainly for porting and experimenting.

### CODE REVIEW

**Comment by ScottPJones** [comment]
Instead of commenting things out, could this be done by checking a constant flag, so that this could actually be merged in? (Like thread support)
I did just that when I first got involved with Julia (i called it JuliaLite) and it seemed to work well.

**Comment by ScottPJones** [comment]
Also, could you write what your philosophy for what you think should stay, and what should go? 
I noticed BigInt, BigFloat, Linalg, and math stuff, out.
However, you also removed package support, so is it still able to load from packages with import or using? 

Finally, I wasn't not meaning to criticize here, I think your doing this is absolutely fantastic, I love it, I just want everything handled so it can be merged ASAP!

**Comment by ViralBShah** [comment]
At the moment I just want to experiment with this - as I said, and maybe make things more modular so that they can be swapped in and out, and get a feel for things. I am also trying to see what the most minimal Julia could potentially look like. Later on, I'll be able to form my own view on what this ought to look like.

I hope this work can eventually evolve towards #5155. Roughly, I am thinking that Base could be minimal, and all the math libraries, while bundled in the distribution for now, not part of sys.so. More and more people are playing with Julia on increasingly smaller devices, and this will help port to many other systems.

**Comment by ScottPJones** [comment]
Still, would it be possible to have it controlled by conditionals instead of commenting out, and actually merge it in (like threads), turned off, to make it (much) easier for others of us (who are *very* interested in seeing this succeed) to play with?  We could then also help you make sure that all the tests that need the missing parts are also correctly disabled, so that it would pass the CI tests. (The more hands helping you, the faster it will go)

**Comment by mason-bially** [comment]
:+1:

I agree with @ScottPJones I would love to help build a branch like this if it was setup like threading and using conditionals.

Personally I think BigInt's at least are a key feature. And if the package library is changed to be more extensible (ala python's `importlib`) it should probably stay as a default namespace, but it's great someone is working on this!

**Comment by ScottPJones** [comment]
Something *like* `BigInt`s, yes, but I think I'd rather see `BigInt`s replaced with a pure Julia implementation, and actually mostly get rid of `BigFloat` (I think a pure Julia implementation of Unums,
both binary and decimal, would really be great for Julia). Just sayin' 😃

**Comment by eschnett** [comment]
When modifying the Base library, it's difficult to understand which parts are required in what order during bootstrap. Haver a really tiny, barely usable core, and loading the remaining parts of Base as separate modules/packages/whatnot with clearly defined dependencies would simplify things a lot. I'm not thinking about a usable Julia here, I'm thinking of the minimum necessary that could still work in a self-contained manner. Julia will always need arbitrary-size integers, but this "basic Base" would not.

**Comment by ScottPJones** [comment]
Yes, I also don't think the `Unum`, or `BigInt` or `BigFloat` should be in Base, but, as in one of my PRs, just the abstract types and base types, with all the rest in modules/packages/whatever.

**Comment by tkelman** [comment]
We already have a tiny core, see coreimg.jl. But better layering and modularity on top of that would be good. Splitting sys.so into multiple modules would be a good start.

**Comment by tknopp** [comment]
The key thing is to first have a concept how a default package could look like (i.e. how is the build process?) Then, first create the default package then remove from base.

Regarding default packages I think they could be just like regular packages but when julia is build, there should be a time where the default packages are pulled. Ideally there is a config file that can be easily changed.

**Comment by ScottPJones** [comment]
>We already have a tiny core, see coreimg.jl

@tkelman There's no documentation in coreimg.jl, about how it would be used, etc., and also I wasn't able to find any in the Julia documentation or on GitHub issues either. Could you point to some explanation of what `coreimg.jl` was intended for, how to use it, etc.?

**Pull request closed without merging**
