### PR TITLE
Backports for 1.8-rc2/1.8.0

### LINKED ISSUE #45657: Julia v1.8.0-rc1: support for znver3 (even though underlying LLVM13 supports is) is missing
This is with the official https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.0-rc1-linux-x86_64.tar.gz
```
$ /opt/julia/bin/julia --cpu-target znver2 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> exit()
$ /opt/julia/bin/julia --cpu-target native
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> exit()
$ /opt/julia/bin/julia --cpu-target znver3 
ERROR: Your CPU does not support the CX16 instruction, which is required by this version of Julia!  This is often due to running inside of a virtualized environment.  Please read https://docs.julialang.org/en/v1/devdocs/sysimg/ for more.
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 5950X 16-Core Processor
    CPU family:          25
    Model:               33
    Thread(s) per core:  2
    Core(s) per socket:  16
    Socket(s):           1
    Stepping:            0
    Frequency boost:     disabled
    CPU(s) scaling MHz:  67%
    CPU max MHz:         6017.8462
    CPU min MHz:         2200.0000
    BogoMIPS:            8050.09
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse
                         3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_p
                         state ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbn
                         oinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   512 KiB (16 instances)
  L1i:                   512 KiB (16 instances)
  L2:                    8 MiB (16 instances)
  L3:                    64 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-31
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

### LINKED ISSUE #45703: Testing Diagonalization asserts on 1.8 in subtyping
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8b2e406_vs_742b9ab/Diagonalizations.primary.log

```
(jl_2ZlRez) pkg> test Diagonalizations
....

signal (6): Aborted
in expression starting at /home/kc/.julia/packages/Diagonalizations/VKvpN/test/runtests.jl:93
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fdc5af2171a)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
ijl_subtype_env at /home/kc/julia1.8/src/subtype.c:1878
subtype_tuple_tail at /home/kc/julia1.8/src/subtype.c:1076 [inlined]
subtype_tuple at /home/kc/julia1.8/src/subtype.c:1158 [inlined]
subtype at /home/kc/julia1.8/src/subtype.c:1298
exists_subtype at /home/kc/julia1.8/src/subtype.c:1394
forall_exists_subtype at /home/kc/julia1.8/src/subtype.c:1422
ijl_types_equal at /home/kc/julia1.8/src/subtype.c:1969
jl_specializations_get_linfo_ at /home/kc/julia1.8/src/gf.c:129
#specialize_method#255 at ./compiler/utilities.jl:204
specialize_method at ./compiler/utilities.jl:190 [inlined]
typeinf_edge at ./compiler/typeinfer.jl:823
abstract_call_method at ./compiler/abstractinterpretation.jl:643
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:154
abstract_call_known at ./compiler/abstractinterpretation.jl:1674
...
```

Also happens for PosDefManifoldML.jl

### LINKED ISSUE #45825: BitArray "constructor" incorrectly assumes 1-based indexing, leading to nondeterministic incorrect results due to out-of-bounds memory access
For example, in the following code, a `BitArray` that is constructed from an input array of values that are all `false` is found to contain some values that are `true`:

```jl
julia> using OffsetArrays

julia> all_false = falses(-1000:1000);

julia> any(==(true), all_false)
false

julia> all_false_bitarray = BitArray(all_false);

julia> any(==(true), all_false_bitarray)
true
```

This is due to the code [here](https://github.com/JuliaLang/julia/blob/2168230c210d620786311d91528a155582f78bc8/base/bitarray.jl#L510-L514), which applies `@inbounds` to a loop before proceeding to index the user-provided array with indices that start from one.

https://github.com/JuliaLang/julia/blob/2168230c210d620786311d91528a155582f78bc8/base/bitarray.jl#L510-L514

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #45348 
- [x] #45409 
- [x] #45443 
- [x] #45478 
- [x] #44318 
- [x] #45380 
- [x] #45504 
- [x] #45383 
- [x] #45548 
- [x] #45547 
- [x] #45615 
- [x] #45625 
- [x] #45675 
- [x] #44390
- [x] #45663 
- [x] #45737 
- [x] #45750 
- [x] #45746 
- [x] #45710 
- [x] #45727 
- [x] #45771 
- [x] #45120 
- [x] #45861 

Contains multiple commits, manual intervention needed:
- [ ] #45437 
- [ ] #45765 
- [ ] #45871 

Non-merged PRs with backport label:
- [ ] #45899 
- [ ] #45896 
- [ ] #45835 
- [ ] #45649 
- [ ] #45605 
- [ ] #45582 
- [ ] #45578 
- [ ] #45212 
- [ ] #45001 
- [ ] #44507

### CODE REVIEW

**Comment by ufechner7** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2990 should be included. This fixes a very annoying bug which is still present in 1.8.0-rc1

**Comment by KristofferC** [comment]
Yep, thanjs for the pointer.

**Comment by KristofferC** [comment]
Eh, that commit is already included from what I can see. So could you elaborate a bit on what the issue is?

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1149826085):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1149825979) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/087ba27_vs_6368fdc/report.html).

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/01d6fae_vs_6368fdc/report.md

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "AutomotiveVisualization", "Bonsai", "ConScape", "ControlSystemIdentification", "DASKR", "GeoArrays", "HighDimPDE", "InvertibleNetworks", "MKL", "OteraEngine", "OutlierDetectionData", "PNGFiles", "ParameterEstimateScatterPlots", "Reactive", "SeisNoise", "ShipMMG"], vs = ":release-1.8")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1153586178) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3a2eb39_vs_6368fdc/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.7", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1156051923) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8b2e406_vs_742b9ab/report.html).

**Comment by KristofferC** [comment]
Bleh, I should have checked PkgEval with assertions much earlier.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1163637350) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/e8418f8_vs_6368fdc/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "ApproxFunOrthogonalPolynomials", "AugmentedGaussianProcesses", "BifurcationInference", "Cambrian", "EclipsingBinaryStars", "ElasticArrays", "EnsembleKalmanProcesses", "FHIRClient", "FieldTracer", "GibbsSeaWater", "GitCommand", "Hashpipe", "HorseML", "InferOpt", "InformationGeometry", "MCPhyloTree", "MIToS", "MPSKit", "MemPool", "MultivariatePolynomials", "NNlib", "NavAbilitySDK", "NormalSplines", "PhaseSpaceTools", "PotentialFlow", "ProgressiveHedging", "Quiqbox", "RetroCap", "SpinDoctor", "SummationByPartsOperators"], vs = ":release-1.8")`

**Comment by KristofferC** [comment]
Should have been run with assertions:

@nanosoldier `runtests(["AlphaStableDistributions", "ApproxFunOrthogonalPolynomials", "AugmentedGaussianProcesses", "BifurcationInference", "Cambrian", "EclipsingBinaryStars", "ElasticArrays", "EnsembleKalmanProcesses", "FHIRClient", "FieldTracer", "GibbsSeaWater", "GitCommand", "Hashpipe", "HorseML", "InferOpt", "InformationGeometry", "MCPhyloTree", "MIToS", "MPSKit", "MemPool", "MultivariatePolynomials", "NNlib", "NavAbilitySDK", "NormalSplines", "PhaseSpaceTools", "PotentialFlow", "ProgressiveHedging", "Quiqbox", "RetroCap", "SpinDoctor", "SummationByPartsOperators"], vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1173610995) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/a87550d_vs_6368fdc/report.html).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45491#issuecomment-1173612792) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/a87550d_vs_6368fdc/report.html).

**Pull request merged**
