### PR TITLE
Disable BB `GMP` and `MPFR`, to fix performance regressions

### PR DESCRIPTION
**Pull request by staticfloat**
Let's see if this compiles everywhere (fingers crossed for FreeBSD) and gives us the bigfloat performance back.

### CODE REVIEW

**Comment by fredrikekre** [comment]
@nanosoldier `runbenchmarks("linalg", vs=":master")`

**Comment by nanosoldier** [comment]
RIP me.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks("linalg", vs=":master")`

**Comment by nanosoldier** [comment]
Long live Nanosoldier!

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32102#issuecomment-494476989) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ffb1919b82c6067ee1b96f4609deb3ec3f8a0f6a/d360782_vs_b21d39d/report.md). cc @ararslan

**Comment by KristofferC** [comment]
Why are you guys just testing LinAlg?

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
Also we are not using BB for the release builds are we?

**Comment by KristofferC** [comment]
I dunno, but it is important that what ends up in the binary is built the same way that what we test performance on.

**Comment by staticfloat** [comment]
> Also we are not using BB for the release builds are we?

We are using BB for the official releases.  No reason not to, as far as we can tell.

**Comment by staticfloat** [comment]
IMO we should rework nanosoldier to use the binaries built by the buildbots.

**Comment by ararslan** [comment]
> Why are you guys just testing LinAlg?

Hah yeah, I did it because it's what Fredrik did and I'm a :sheep:. He apparently noticed that linalg wasn't the best choice given the edit.

**Comment by ararslan** [comment]
I _think_ the only dependency that Nanosoldier doesn't use BB for is LLVM.

**Comment by fredrikekre** [comment]
Well, I copied you: https://github.com/JuliaLang/julia/pull/32097#issuecomment-494182435 :)

**Comment by ararslan** [comment]
We're all :sheep:
Untitled

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32102#issuecomment-494519807) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b640dc46a84233a495612786118637c9b0510b26/d360782_vs_b21d39d/report.md). cc @ararslan

**Comment by ararslan** [comment]
The relevant stuff looks good.

**Comment by KristofferC** [comment]
The memory regressions are weird... But they should not be related.

**Comment by KristofferC** [comment]
So should we just merge this into 1.3 + master as well since it seems like it is here to stay for a while?

**Comment by StefanKarpinski** [comment]
Unless we can fix the issue somehow. @staticfloat, any thoughts?

**Comment by ViralBShah** [comment]
How about we mark it for triage? So that if we hit a couple of RCs and not resolved, we can at least merge.

**Comment by KristofferC** [comment]
I put https://github.com/JuliaLang/julia/issues/31759 on the milestone at least.

**Pull request merged**
