### PR TITLE
inline mod1

### PR DESCRIPTION
**Pull request by KristofferC**
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21409) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c587a11bb419d28af272c48708f7d0075cfd5c22/c3c6fae_vs_8934aab/report.md). cc @jrevels

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21409#issuecomment-294429166) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c1bb502a2cbcbc0e11097ccb6a9292b25dbab014/6aa3895_vs_934e0e3/report.md). cc @jrevels

**Comment by KristofferC** [comment]
Seems ok.

**Review by ararslan — APPROVED** [review]

**Pull request merged**
