### PR TITLE
Merge strwidth and charwidth to textwidth

### LINKED ISSUE #20816: Merge `charwidth` and `strwidth`?
Since these functions are very similar, I wonder if it is worth merging them into a single function, maybe `textwidth`.

Alternatively, perhaps `strwidth(_)` can be spelt `sum(charwidth, _)`.

### PR DESCRIPTION
**Pull request by TotalVerb**
Closes #20816.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Review by JeffBezanson — APPROVED** [review]

**Comment by TotalVerb** [comment]
Fixed a (seemingly untested?) mistake with the rewrite of `strwidth` into a `sum` instead of an explicit loop. This should be squashed when merging.

**Comment by ararslan** [comment]
The CI failures are doc stuff; I think you'll have to remove the doc references to `charwidth` and `strwidth` and add `textwidth`.

**Review by stevengj — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Needs a rebase.

**Comment by TotalVerb** [comment]
Sorry for the delay here, the documentation build failures were confusing me. I'll check Documenter out and see what's up.

**Review by ararslan — APPROVED** [review]

**Pull request merged**
