### PR TITLE
Clarification on try/catch/finally blocks and a few more examples

### PR DESCRIPTION
**Pull request by harikb**
I have a few edits for the try/catch/finally blocks. Related discussion on this topic in julia-users mailing is here https://groups.google.com/d/msg/julia-users/Kqn6gNIwD5o/g9xiMmOKAoIJ

I understand this is a fairly extensive edit than what is discussed in the thread, but I think it clarifies a lot of things. If you want me to remove any edits, please let me know and I will undo them and resubmit.

All examples are quoted from real julia session. I have done "make html" and verified it appears ok. However, I have not been successful running doctest in general (even before this change) because of the issue mentioned in this post https://groups.google.com/d/msg/julia-users/n0OjsGJpMRc/XOdv7Uqtu9oJ

### CODE REVIEW

**Comment by harikb** [comment]
Thanks, I didn't know what. That said, although I removed that phrase from the original example, the return value of nothing is documented below (in a separate section on return values, after the finally is explained, with many examples). I have tried to use ``nothing`` (in quotes), but let me see if I can word it better.  I removed it from original example to clearly state that "return value of nothing" is caused by the empty block and not something special about that terse syntax. Unless it is something special about catch clause. I know nothing about Julia internals, buy my explanation based on reading rest of the manual sounded intuitive to me.

julia> nothing == try end
true

julia> nothing == begin end
true

I will resubmit tomorrow.

Thanks for your time

**Comment by harikb** [comment]
elextr, I am still purplexed by this comment
> note the value nothing can be tested so you can tell if the block exited by exception rather than returning its last expression

julia> nothing == try println("hello") end
hello
true

If developers start using return of ``nothing`` to detect having got an exception, that is bad as well. In the above example, there is perfectly valid non-erroring block and it returns ``nothing``  (because println returns ``nothing``)

IMHO, we should be simply saying 'it returns the last expression executed' (just like any other block) - that is how I have worded it.

**Comment by elextr** [comment]
Of course if the normal return from the block is also `nothing` then you can't tell if there was an exception, but then you probably don't use the value of the try block if its normal value is `nothing`.

If there is an exception the value of the try block is `nothing` and that must be documented correctly, saying that the value is the last expression is wrong if there is an exception.

You are not meant to use the `nothing` to detect exceptions to do something with them, thats what `catch` is for.

But if you are ignoring exceptions and the normal value of the try block is something else and *you use that value* then you probably need to check, because further computations using that value may barf with `nothing`.  It would be nice to mention this.

**Comment by tkelman** [comment]
@harikb sorry we seem to have lost track of this. It looks like your commit 1526a54e05b6f343e04a435b0497a06f9b8f3c0c still applies and would be a useful doc addition?

**Comment by harikb** [comment]
thanks. I closed only because I thought I couldn't state my point with elextr. I didn't know Julia enough to continue to make the case, so I left it.

**Comment by elextr** [comment]
@harikb I'm not sure what is still open, you have documented the fact that the `try` code `end` construct returns `nothing` on an exception.  That was all I was after.

**Comment by vtjnash** [comment]
Since this PR, we renamed the file (from rst to md format). Is it something we should revive?

**Pull request closed without merging**
