### PR TITLE
Docs: cross-reference `username` and `homedir`

### PR DESCRIPTION
**Pull request by barucden**
To improve discoverability (mainly) of `username`.

[skip ci]

### CODE REVIEW

**Comment by barucden** [comment]
Bump. The test fails are not related as far as I can tell.

**Comment by barucden** [comment]
Bump

**Comment by barucden** [comment]
The PR adds only two "see also" references. Can we decide its fate?

**Review by StefanKarpinski — APPROVED** [review]

**Comment by barucden** [comment]
Thank you

**Pull request merged**
