### PR TITLE
Deprecate prime number functions (`isprime`, `primes`, `primesmask`, `factor`)

### PR DESCRIPTION
**Pull request by simonbyrne**
See #16357.

Current functionality has been moved to https://github.com/JuliaMath/Primes.jl

### CODE REVIEW

**Comment by tkelman** [comment]
Cool. This should wait until Primes.jl is registered before merging.

**Comment by tkelman** [comment]
Remaining mentions:
```
contrib/BBEditTextWrangler-julia.plist:645:            <string>isprime</string>
doc/manual/arrays.rst:322:    julia> x[map(isprime, x)]
doc/stdlib/numbers.rst:458:.. function:: isprime(x::Integer) -> Bool
doc/stdlib/numbers.rst:466:       julia> isprime(3)
doc/stdlib/numbers.rst:469:.. function:: isprime(x::BigInt, [reps = 25]) -> Bool
doc/stdlib/numbers.rst:477:       julia> isprime(big(3))
contrib/BBEditTextWrangler-julia.plist:861:            <string>primes</string>
contrib/BBEditTextWrangler-julia.plist:862:            <string>primesmask</string>
doc/stdlib/numbers.rst:480:.. function:: primes([lo,] hi)
doc/stdlib/numbers.rst:486:.. function:: primesmask([lo,] hi)
doc/stdlib/numbers.rst:490:   Returns a prime sieve, as a ``BitArray``\ , of the positive integers (from ``lo``\ , if specified) up to ``hi``\ . Useful when working with either primes or composite numbers.
contrib/BBEditTextWrangler-julia.plist:435:            <string>factor</string>
doc/stdlib/math.rst:1362:.. function:: factor(n) -> Dict
doc/stdlib/math.rst:1366:   Compute the prime factorization of an integer ``n``\ . Returns
 a dictionary. The keys of the dictionary correspond to the factors, and hence are of the same type as ``n``\ . The value associated with each key indicates the number of times the factor appears in the factorization.
doc/stdlib/math.rst:1370:       julia> factor(100) # == 2*2*5*5
```

**Comment by simonbyrne** [comment]
The question is how best to handle deprecations of functions: should we do the same thing as #13897, where we throw an error (instead of `depwarn`)?

**Comment by tkelman** [comment]
I actually liked the way you had it where the old functions were just moved to being included from deprecated.jl. No errors that way, just warnings.

**Comment by simonbyrne** [comment]
Yeah, I wasn't sure what was the best way, which is why I kept it as a separate commit. We should figure out a consistent way to do this, especially as we're going to move more stuff out of Base.

The trouble is figuring out a way so that doing the correct thing, e.g. something like `using Primes; isprime(7)`, doesn't throw a warning or error for deprecation, duplicate export or method overwriting.

**Comment by tkelman** [comment]
So which (if any?) of these commits is able to do that?

**Comment by simonbyrne** [comment]
Once we merge this, my plan is to add something like the following to Primes.jl:
```
if VERSION >= v"0.6-"
    export isprime, primes, primesmask, factor
elseif VERSION >= v"0.5-dev+XXXX"
    import Base: isprime, primes, primesmask, factor
end
```
Then `using Primes` shouldn't cause a problem on any version (after 0.4).

**Comment by tkelman** [comment]
using `isdefined` would probably be more accurate in capturing exactly when the deprecations get removed.

**Comment by simonbyrne** [comment]
Okay, so we could use:
```julia
if VERSION >= v"0.5-dev+XXXX"
    if isdefined(Base,:isprime)
        import Base: isprime, primes, primesmask, factor
    else
        export isprime, primes, primesmask, factor
    end
end
```

Either way, we still need the commit no for this change.

**Comment by tkelman** [comment]
Yep. So if we prefer the error-causing version, merge this as is?

**Comment by simonbyrne** [comment]
Yes, I think it should be good to go.

**Pull request merged**
