### PR TITLE
Add JITLink ELF debugger support

### PR DESCRIPTION
**Pull request by pchintalapudi**
GDBJITDebugInfoRegistrationPlugin only supports MachO debugger support; EPCDebugObjectRegistrar is used for ELF debugger support.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
SGTM. But I don't know anything about this

**Comment by dnadlinger** [comment]
Apolgoies, won't have any bandwidth for this for a few days (and haven't looked at EPCDebugObjectRegistrar yet).

**Comment by dnadlinger** [comment]
Just saw that this is still sitting unmerged – I'm not sure I have much useful to add. 

I might have enabled DebugObjectManagerPlugin only when targeting ELF and 
GDBJITDebugInfoRegistrationPlugin only when targeting MachO to avoid the performance overhead, but I suppose the cost should be very small.

I'm also not sure whether there is any advantage to synthesising the `JITDylib` entries only for `Create` to the immediately look them up; or rather, the AllocAction – I think `llvm_orc_registerJITLoaderGDBWrapper` is only used by the `EPCDebugObjectRegistrar`.

**Review by vchuravy — APPROVED** [review]

**Comment by gbaraldi** [comment]
Does this turn off the ability to do JIT debugging on macho? (I'm not sure this ever worked but in a more theoritical sense)

**Comment by pchintalapudi** [comment]
> I'm also not sure whether there is any advantage to synthesising the JITDylib entries only for Create to the immediately look them up; or rather, the AllocAction – I think llvm_orc_registerJITLoaderGDBWrapper is only used by the EPCDebugObjectRegistrar.

There isn't any immediate benefit, but I figure the cost is pretty low to route it through Create, and maybe in the future upstream LLVM will do something fancy in Create that can't be applied to a new call (e.g. give back the correct plugin).

> Does this turn off the ability to do JIT debugging on macho? (I'm not sure this ever worked but in a more theoritical sense)

No, we still add the MachO plugin when we're emitting to MachO format.

**Pull request merged**
