### PR TITLE
Backports for 1.1.0

### LINKED ISSUE #30006: sparse matrix with non-Int64 index type slice assignment failure
```
julia> using SparseArrays

julia> a=SparseMatrixCSC{Float64, Int32}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int32} with 0 stored entries

julia> a[:,1]=[1,2,3]
ERROR: type Slice has no field stop
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] getindex at ./range.jl:610 [inlined]
 [3] setindex!(::SparseMatrixCSC{Float64,Int32}, ::Array{Int64,1}, ::Colon, ::Int64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/sparsematrix.jl:2656
 [4] top-level scope at none:0
```

The same code with Int64 in place of Int32 succeeds
```

julia> a=SparseMatrixCSC{Float64, Int64}(spzeros(3,3))
3×3 SparseMatrixCSC{Float64,Int64} with 0 stored entries

julia> a[:,1]=[1,2,3]
3-element Array{Int64,1}:
 1
 2
 3
```

### LINKED ISSUE #30124: Scalar multiplying static vector in CUDAnative kernel makes unsupported call to Julia runtime in Julia master but not 1.0.2
The following code works on Julia 1.0.2 and fails in Julia Commit 8a4f20b887 (2018-11-19 01:50 UTC). The issue first started at https://github.com/JuliaGPU/CUDAnative.jl/issues/291, and @maleadt found the causing commit to be https://github.com/JuliaLang/julia/commit/9e98386bea64c24d51c1d44a5bfc2f66f4e7563a. If you replace the multiplication line by the next commented one, it works fine.

```julia
using CUDAnative, CuArrays, StaticArrays

Ks = [SMatrix{1, 1, Float64}(rand(1,1))] |> CuArrays.CuArray
fs = [SVector{1, Float64}(rand(1))] |> CuArrays.CuArray

function kernel(fs::AbstractVector{TV}, Ks) where {N, T, TV<:SVector{N,T}}
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    m = 2.0
    if i == 1
	    fs[i] = m * (Ks[i] * fs[i])
	    #fs[i] = SVector{1,T}((m,)) .* (Ks[i] * fs[i])
    end
    return
end

@cuda blocks=1 threads=1 kernel(fs,  Ks)

#=
ERROR: InvalidIRError: compiling kernel(CuDeviceArray{SArray{Tuple{3},Float64,1,3},1,CUDAnative.AS.Global}, CuDeviceArray{SArray{Tuple{3,3},Float64,2,9},1,CUDAnative.AS.Global}) resulted in invalid LLVM IR
Reason: unsupported call to the Julia runtime (call to jl_invoke)
Stacktrace:
 [1] Type at broadcast.jl:141
 [2] result_style at broadcast.jl:397
 [3] combine_styles at broadcast.jl:390
 [4] broadcasted at broadcast.jl:1162
 [5] broadcast at broadcast.jl:702
 [6] * at /home/mohd/.julia/packages/StaticArrays/WmJnA/src/linalg.jl:25
 [7] kernel at REPL[18]:5
Stacktrace:
 [1] check_ir(::CUDAnative.CompilerContext, ::LLVM.Module) at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/compiler/validation.jl:123
 [2] #compile#80(::Bool, ::Function, ::CUDAnative.CompilerContext) at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/compiler/driver.jl:74
 [3] compile at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/compiler/driver.jl:49 [inlined]
 [4] #compile#79(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::CUDAdrv.CuDevice, ::Any, ::Any) at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/compiler/driver.jl:28
 [5] compile at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/compiler/driver.jl:16 [inlined]
 [6] macro expansion at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/execution.jl:255 [inlined]
 [7] #cufunction#91(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(cufunction), ::typeof(kernel), ::Type{Tuple{CuDeviceArray{SArray{Tuple{3},Float64,1,3},1,CUDAnative.AS.Global},CuDeviceArray{SArray{Tuple{3,3},Float64,2,9},1,CUDAnative.AS.Global}}}) at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/execution.jl:230
 [8] cufunction(::Function, ::Type) at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/execution.jl:230
 [9] top-level scope at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/execution.jl:198
 [10] top-level scope at gcutils.jl:87
 [11] top-level scope at /home/mohd/.julia/packages/CUDAnative/5H3Dk/src/execution.jl:195
=#
```

My `versioninfo()` is:
```julia
Julia Version 1.1.0-DEV.681
Commit 8a4f20b887 (2018-11-19 01:50 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
``` 

Good luck!

### LINKED ISSUE #30303: Unescaped $ when using `show` on `Symbol`
The output here is trying to display the Julia code for creating the Symbol below but it fails to show that `$` is escaped:
```julia
julia> Symbol("USD\$")
Symbol("USD$")

julia> Symbol("USD$")
ERROR: syntax: invalid interpolation syntax: "$""
```

### LINKED ISSUE #30335: "Slicing" due to type unstable parametric type construction
I'm seeing something that reminds me a little bit about type slicing in C++; I'm trying to generate term symbols (https://en.wikipedia.org/wiki/Term_symbol) from their string representation. I have this type
```julia
struct Term{I<:Integer,R<:Rational{I},LT<:Union{I,R}}
    L::LT
    S::R
    parity::I
end
```
The creation of a `Term` from a string is accomplished with (input error checks removed)
```julia
spectroscopic="spdfghiklmnoqrtuv"

function term_string(s::AbstractString)
    m = match(r"([0-9]+)([A-Z]|\[[0-9/]+\])([oe ]{0,1})", s)
    L = lowercase(m[2])
    L = if L[1] == '['
        L = strip(L, ['[',']'])
        if occursin("/", L)
            Ls = split(L, "/")
            Rational(parse(Int, Ls[1]),parse(Int, Ls[2]))
        else
            parse(Int, L)
        end
    else
        findfirst(L, spectroscopic)[1]-1
    end
    S = (parse(Int, m[1]) - 1)//2
    Term(L, S, m[3] == "o" ? -1 : 1)
end
```
Input `1S` should yield `Term.L=0`, `1[5]` => `Term.L=5`, `1[3/2]` => `Term.L=3//2` (rational). The last one however, results in
```julia
Term{Int64,Rational{Int64},Int64}
  L: Int64 3
  S: Rational{Int64}
    num: Int64 2
    den: Int64 0
  parity: Int64 1
```
where it can be seen that the type of `L` was not correctly inferred, and `3//2` was split such that the numerator ended up in `L` and the denominator in `S.num`, etc.

This works as it should on Julia v1.0.2, but not on nightly 1bd316b972. I can make it work on nightly by either

- declaring `const spectroscopic="spdfghiklmnoqrtuv"` (which is the sane thing to do anyway), or
- replacing the last line in `term_string` with `Term{Int,Rational{Int},typeof(L)}(L, S, m[3] == "o" ? -1 : 1)`

I tried to bisect using the following scripts:
```bash
#!/bin/bash
make || make clean && make || make clean && exit 125 # If build fails, we cannot test it
./julia term-test.jl || exit 1
```
`term-test.jl`:
```julia
using Test

struct Term{I<:Integer,R<:Rational{I},LT<:Union{I,R}}
    L::LT
    S::R
    parity::I
end

spectroscopic = "spdfghiklmnoqrtuv"

function term_string(s::AbstractString)
    m = match(r"([0-9]+)([A-Z]|\[[0-9/]+\])([oe ]{0,1})", s)
    println(m)
    L = lowercase(m[2])
    L = if L[1] == '['
        L = strip(L, ['[',']'])
        if occursin("/", L)
            Ls = split(L, "/")
            Rational(parse(Int, Ls[1]),parse(Int, Ls[2]))
        else
            parse(Int, L)
        end
    else
        findfirst(L, spectroscopic)[1]-1
    end
    S = (parse(Int, m[1]) - 1)//2
    Term(L, S, m[3] == "o" ? -1 : 1)
end

@test term_string("1S") == Term(0, 0//1, 1)
@test term_string("1[5]") == Term(5, 0//1, 1)
@test term_string("1[3/2]") == Term(3//2, 0//1, 1)
```
but I end up with the unsatisfactory result
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1bd316b972cb4ef83b9b8e79f435cc4d59029a93
bd21aa75eb4c0e56ef870f6bffea3281c724cbb1
We cannot bisect more!
bisect run cannot continue any more
```

### LINKED ISSUE #30346: Unreachable reached
I hit a bug very similar to #30122. Unfortunately I was not able to reduce this to a self-contained example. This is on the release-1.1 branch.
```
              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.839 (2018-12-07)
 _/ |\__'_|_|_|\__'_|  |  Commit b55b85cd99 (3 days old master)
|__/                   |

julia> versioninfo()
Julia Version 1.1.0-DEV.839
Commit b55b85cd99 (2018-12-07 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.0.0)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

julia> using DynamicPolynomials
[ Info: Precompiling DynamicPolynomials [7c1d4256-1411-5781-91ec-d7bc3513ac07]

julia> @polyvar x[1:2]
Unreachable reached at 0x12a28a3ca

signal (4): Illegal instruction: 4
in expression starting at no file:0
setindex! at ./array.jl:764
collect_to_with_first! at ./array.jl:626
collect at ./array.jl:608
map at ./abstractarray.jl:2044 [inlined]
polyarrayvar at /Users/sascha/.julia/packages/DynamicPolynomials/3rBvr/src/var.jl:6
unknown function (ip: 0x12a28a37d)
jl_fptr_trampoline at /Users/sascha/coding/julia/src/gf.c:1854
do_call at /Users/sascha/coding/julia/src/interpreter.c:323
eval_stmt_value at /Users/sascha/coding/julia/src/interpreter.c:362 [inlined]
eval_body at /Users/sascha/coding/julia/src/interpreter.c:759
jl_interpret_toplevel_thunk_callback at /Users/sascha/coding/julia/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x117da000f)
unknown function (ip: 0x1)
jl_interpret_toplevel_thunk at /Users/sascha/coding/julia/src/interpreter.c:894
jl_toplevel_eval_flex at /Users/sascha/coding/julia/src/toplevel.c:764
jl_toplevel_eval at /Users/sascha/coding/julia/src/toplevel.c:773 [inlined]
jl_toplevel_eval_in at /Users/sascha/coding/julia/src/toplevel.c:793
eval at ./boot.jl:328
eval_user_input at /Users/sascha/coding/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /Users/sascha/coding/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply at /Users/sascha/coding/julia/src/./julia.h:1571 [inlined]
start_task at /Users/sascha/coding/julia/src/task.c:572
Allocations: 12189244 (Pool: 12186847; Big: 2397); GC: 26
Illegal instruction: 4
```

### LINKED ISSUE #30394: Incorrectly Inferred Return type
From [Discourse](https://discourse.julialang.org/t/incorrectly-inferred-return-type/18668)

Example code:

```
abstract type AbstractFoo end

mutable struct FooBase <: AbstractFoo
  a::Int
  # no foo_inner: terminates any recursion
end


mutable struct Foo1 <: AbstractFoo
  foo_inner::FooBase

  function Foo1()
    return new(FooBase(1))
  end
end

mutable struct Foo2 <: AbstractFoo
  foo_inner::Foo1

  function Foo2()
    return new(Foo1())
  end
end


mutable struct Foo3 <: AbstractFoo
  foo_inner::Foo2

  function Foo3()
    return new(Foo2())
  end
end


mutable struct Foo4 <: AbstractFoo
  foo_inner::Foo3

  function Foo4()
    return new(Foo3())
  end
end



# T1 <: T2 implies T1 == T2 as long as all T1 and T2 are concrete
function getInnerFoo(foo::T1, ::Type{T2}) where {T2 <: AbstractFoo, T1 <: T2}
  return foo
end

function getInnerFoo(foo::T1, ::Type{T2}) where {T1 <: AbstractFoo, T2 <: AbstractFoo}
  return getInnerFoo(foo.foo_inner, T2)
end

obj = Foo4()

obj2 = getInnerFoo(obj, Foo2)
println("typeof(obj2) = ", typeof(obj2))
@code_warntype getInnerFoo(obj, Foo2)
```

On Julia 0.6.2, the output is:

```
typeof(obj2) = Foo2
Variables:
  #self# <optimized out>
  foo::Foo4
  #unused# <optimized out>

Body:
  begin 
      return foo::Foo4
  end::Foo4
Variables:
  #self# <optimized out>
  foo::Foo4
  #unused# <optimized out>

Body:
  begin 
      return (Main.getInnerFoo)((Core.getfield)(foo::Foo4, :foo_inner)::Foo3, $(Expr(:static_parameter, 2)))::Foo3
  end::Foo3
```

The `typeof` line shows `obj2` is of type `Foo2`, but `code_warntype` infers it to be `Foo3`.  Similar result on Julia 1.0.1.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #30297 - Some more compat annotations
- [x] #30304 - fix #30303, escaping $ when showing Symbols
- [x] #30059 - Fix Makefile not removing  debug julia lib on windows
- [x] #30311 - Add LinearAlgebra as test dependency to Distributed.
- [x] #30253 - src/task.c: Use `b` instead of `br` instruction on armv7l
- [x] #30286 - Make `unique(f, itr)` and `unique!(f, itr)` faster
- [x] #30316 - Unexport catch_stack
- [x] #30324 - Use `JL_AArch64_crc` instead of `HWCAP_CRC32`
- [x] #30302 - NEWS edits for 1.1
- [x] #30156 - `@inbounds` annotations for filter
- [x] #30340 - Expand and fix documentation of BitArray
- [x] #30228 - oneunit of sparse matrix should return sparse matrix
- [x] #30342 - Upgrade Pkg to version 1.1.
- [x] #30108 - adding == for structured matrices (split off of #29724)
- [x] #30339 - Documenter updates for future pdf deployment
- [x] #29998 - Adding rtol and atol for pinv and nullspace
- [x] #30194 - use non Pkg for workflow tips
- [x] #30315 - fix bug with max_values in union!
- [x] #30331 - Force specialization on the type argument of `_similar_for`
- [x] #30351 - Allow dotted binary tilde
- [x] #30361 - Add compat annotation for NaN handling in (l|r)mul!
- [x] #30347 - added doc for AbstractChannel
- [x] #30057 - Update references to Base.SparseArrays
- [x] #30350 - codegen: disable Bool optimization for maybe-undef fields
- [x] #30360 - fix #30346, specificity issue with DynamicPolynomials
- [x] #30330 - Copying editing in "Environment variables" docs
- [x] #29916 - Add Float16 comparisons
- [x] #30373 - improve printf performance by passing digit buffer around
- [x] #30353 - fix #30335, regression in intersection of unions of typevars
- [x] #30378 - Upgrade to Pkg 1.1.1.
- [x] #30376 - Fix reinterpret for 0-dimensional arrays
- [x] #30369 - stacktrace: prevent OOB-error in sysimage lookup
- [x] #30405 - Fix #30006, getindex accessing fields that might not exist
- [x] #30396 - fix #30394, an unsoundness in ml_matches
- [x] #30266 - Try implementing N-dimensional indexing for fast linear SubArrays
- [x] #29946 - loading: work on simplifications (and some corrections) of docs
- [x] #30420 - fix #30124, broadcast regression due to removed pure annotation
- [x] #30385 - attempt to refine return type when it could be improved via PartialTuple
- [x] #30384 - make `ndigits` more generic
- [x] #30449 - Add link to the pdf version of the documentation to the html pages
- [x] #30319 - generalize sparse matrix slicing to integer types
- [x] #30439 - Fix mention of Base.worker_timeout() in manual
- [x] #30459 - Only use llvm-config for library selection with USE_SYSTEM_LLVM
- [x] #30519 - Add Dates as a test dependency to SparseArrays.
- [x] #30521 - Bump Pkg to 1.1.2.

Non-merged PRs with backport label:
- [ ] #30483 - make inference of `_apply` match the implementation more closely
- [ ] #30458 - gf: fix jl_isa_compileable_sig again
- [ ] #30431 - Build: fix output directory when specified with O=
- [ ] #30403 - Include @​propagate_inbounds docstring in documentation
- [ ] #30398 - Fix enumerate documentation
- [ ] #30367 - move generate_precompile to Base so that it is bundled in downloads
- [ ] #30357 - workaround for F_DUPFD_CLOEXEC on Linux kernel <2.6.24 before it existed

### CODE REVIEW

**Comment by andyferris** [comment]
FYI: #30286 has merged.

**Comment by JeffBezanson** [comment]
#30302 and #30316 are also merged.

**Comment by andyferris** [comment]
#30156

**Comment by KristofferC** [comment]
Thanks but there is no need to comment here for every merged PR that has a backport label. :)

**Pull request merged**
