### PR TITLE
Updates to TM bundle.

### PR DESCRIPTION
**Pull request by chrisvoncsefalvay**
Big New Year's Eve update to the enclosed textmate bundle that seems to have gotten little love lately ;(
- Snippets:
  - Docstring
  - Documented function
  - elseif
  - error
  - finally
  - for/in
  - function
  - if
  - if/else
  - macro
  - println
  - Ternary operator
  - throw
  - try/catch
  - type declaration
  - while
- Highlighting
  - Syntax highlighting for base functions and base types. Yes, the lot. Might be missing a few, so let me know if I have failed to spot something.

### CODE REVIEW

**Comment by tkelman** [comment]
That's really strange, https://github.com/nanoant/Julia.tmbundle/commits/master matches https://github.com/JuliaLang/julia/commits/master/contrib/Julia.tmbundle before April. I guess the guy who forked it is a Textmate contributor, but I can't find any sign of him raising an issue or commenting anywhere about wanting to maintain the official bundle in a separate repo? It's MIT licensed so we could just cherry-pick the improvements... might want to raise an issue there asking whether it can refer to contrib here, or if it should be hosted at JuliaLang if the bundle needs to be a top-level repo.

**Comment by ihnorton** [comment]
Was discussed on list: https://groups.google.com/d/msg/julia-dev/FpLtt6GV_hI/ayoyGmA0MMIJ)

**Comment by tkelman** [comment]
Oh there you go, nevermind then he did contact us. Maybe ask if moving the repo to JuliaLang (giving commit access to anyone who has contributed there since April) would be possible? Would probably be higher visibility for future contributions like this PR.

**Comment by jiahao** [comment]
cc @nanoant

**Comment by nanoant** [comment]
Honestly I would prefer `Julia.tmbundle` stay in separate repo. I expressed my reasoning behind that on the list. Keeping `Julia.tmbundle` inside Julia main source is just PITA to maintain and sync since you need to pull ALL the Julia source.

So again I humbly please @StefanKarpinski to move `Julia.tmbundle` to separate repo, preferably make it submodule of main Julia repo. Then we can sync, pull & push merge requests across TM, Sumblime forks boundaries.

**Comment by tkelman** [comment]
> preferably make it submodule of main Julia repo

-1. Submodules are a pain. Editor support probably doesn't need to be kept here, other than for synchronizing changes in language keywords. May be best to keep separate branches for different Julia versions of editor support files.

However if we want things to be visible, official, and easy for contributors to find, use, and submit modifications to, it would probably be better to have the repo as part of the organization. Can easily grant commit access to it for anyone who has contributed at its current location.

**Comment by nanoant** [comment]
@tkelman Okay, it doesn't need to be submodule then, but it should be separate repo.

So once we all agree on that I can handle making it in sync with TextMate.

**Comment by jiahao** [comment]
I do think that since we have someone willing to update the TextMate bundle that making it a separate repo makes a lot of sense. After all we already have julia-vim as a separate repo.

**Comment by nanoant** [comment]
If you give me the access to the new repo I can handle rewriting all new commits from `Julia.tmbundle` from Julia's and my repo http://github.com/nanoant/Julia.tmbundle into this new one. WDYT?

**Comment by nanoant** [comment]
Or better, why not just move my repo to Julia organization!?

**Comment by jiahao** [comment]
moving your repo to JuliaLang would be preferred I think. I don't have the admin rights to do so though.

**Comment by tkelman** [comment]
Bump @StefanKarpinski or @ViralBShah would have to do that I think.

**Comment by nanoant** [comment]
Bump @StefanKarpinski or @ViralBShah once again.

**Comment by Keno** [comment]
@tkelman You have Admin rights as well, I believe. However, we'd still have to create a new team for the new repository to give @nanoant access. I'll bug @JeffBezanson about this when I see him tomorrow.

**Comment by tkelman** [comment]
I can fiddle with the webhooks, but I can't adjust users or teams.

**Comment by JeffBezanson** [comment]
@nanoant I added a team for this. You should be able to move the repo now.

**Comment by nanoant** [comment]
@JeffBezanson Done! Now TM bundle is available at https://github.com/JuliaLang/Julia.tmbundle I will now try to merge and review all changes from other repos and julia project itself.

**Comment by nanoant** [comment]
@JeffBezanson Okay there seems to be no extra changes in `/contrib/Julia.tmbundle` since I made `Julia.tmbundle` separate repo. So I think it is now safe to kill `/contrib/Julia.tmbundle` and point to the https://github.com/JuliaLang/Julia.tmbundle in the README.md, also maybe adding note that TextMate 2 supports Julia out of the box.

**Comment by Keno** [comment]
Great! I will close this issue as resolved then.

**Comment by nanoant** [comment]
@chrisvoncsefalvay I have committed 1st change partially (snippets only) to JuliaLang/Julia.tmbundle@35b4b0f07d5f042aae2ce60b42b7f4893da27a25

But I have not committed 2nd change, as it reverts some grammar modifications introduced in first one. I don't really understand purpose of these modifications. Please open some more pull requests to [JuliaLang/Julia.tmbundle](/JuliaLang/Julia.tmbundle).

**Comment by mbauman** [comment]
Hooray a real home!  Thanks everyone. :+1:

**Comment by tkelman** [comment]
Sweet. We should probably delete the files from `contrib` at some point.

**Comment by ivarne** [comment]
@tkelman Is there any reason to wait?

**Comment by tkelman** [comment]
nope #10580

**Pull request closed without merging**
