### PR TITLE
Print a hint if the user types `exit` in the REPL (implemented by customizing `Base.show` for `typeof(exit)`)

### PR DESCRIPTION
**Pull request by DilumAluthge**
This implements the suggestion from triage in https://github.com/JuliaLang/julia/pull/42011#issuecomment-961323748 and https://github.com/JuliaLang/julia/pull/42011#issuecomment-961729741.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @mkitti

**Review by vtjnash — APPROVED** [review]
Seems okay, but feels a little odd that `display` will have this text in all cases, not just the REPL. I think this might be better:
```diff
diff --git a/stdlib/REPL/src/REPL.jl b/stdlib/REPL/src/REPL.jl
index 3308760046..cb7163aeab 100644
--- a/stdlib/REPL/src/REPL.jl
+++ b/stdlib/REPL/src/REPL.jl
@@ -301,6 +301,9 @@ function print_response(errio::IO, response, show_value::Bool, have_color::Bool,
                         println(errio, "Error showing value of type ", typeof(val), ":")
                         rethrow()
                     end
+                    if response === exit
+                        println("Hint: To exit Julia, use Ctrl-D or type exit() and press enter.")
+                    end
                 end
             end
             break
```

**Comment by mkitti** [comment]
To review, we've explored a few ways of doing this, and come full circle:
1. https://github.com/JuliaLang/julia/pull/21362
Similar to this PR
2. https://github.com/JuliaLang/julia/pull/38307
Modified `display(d::REPLDisplay, mime::MIME"text/plain", x)`
3. https://github.com/JuliaLang/julia/pull/38522
Added a `print_exit_help` method called after `print_response`
4. https://github.com/JuliaLang/julia/pull/42011
Used an AST transform in the REPL

```
julia> function Base.show(io::IO, m::MIME"text/plain", fn::typeof(exit))
           TT = Tuple{IO, MIME"text/plain", Function}
           invoke(show, TT, io, m, fn)
           println(io)
           print(io, "Hint: To exit Julia, use Ctrl-D or type exit() and press enter.")
           return nothing
       end

julia> exit
exit (generic function with 2 methods)
Hint: To exit Julia, use Ctrl-D or type exit() and press enter.

julia> (exit, exit)
(exit, exit)

julia> [exit]
1-element Vector{typeof(exit)}:
 exit

julia> ans[1]
exit (generic function with 2 methods)
Hint: To exit Julia, use Ctrl-D or type exit() and press enter.
```

**Comment by mkitti** [comment]
Would making it conditional on `Base.isinteractive()` help?

**Comment by mkitti** [comment]
Thinking of the bigger picture here, why doesn't the REPL have it's own MIME type? `text/vnd.juliarepl` perhaps. The fallback would be to text/plain.

**Comment by JeffBezanson** [comment]
Same thing I posted in *2017* btw.

**Comment by vtjnash** [comment]
So https://github.com/JuliaLang/julia/pull/42011?

**Comment by JeffBezanson** [comment]
That's not ideal either; a string operation like how we handle `;` seems like the best way. But I don't think this is necessary at all.

**Comment by mkitti** [comment]
> That's not ideal either; a string operation like how we handle `;` seems like the best way. But I don't think this is necessary at all.

https://github.com/JuliaLang/julia/pull/38522/files

**Comment by JeffBezanson** [comment]
While we're at it, we can fix `quit` too, which does weird things:
```
julia> f() = quit
f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: quit not defined
suggestion: To exit Julia, use Ctrl-D, or type exit() and press enter.
```

**Comment by mkitti** [comment]
@DilumAluthge , Jeff, leading triage, says to go back to https://github.com/JuliaLang/julia/pull/38522 , with the binding resolved enhancement he suggested.

**Comment by JeffBezanson** [comment]
Same thing for `help`.

**Pull request closed without merging**
