### PR TITLE
add graphemes(s) function to iterate over string graphemes

### PR DESCRIPTION
**Pull request by stevengj**
utf8proc/libmojibake includes a feature to break a string up into [graphemes (as defined by UAX#29)](http://www.unicode.org/reports/tr29/).   This PR exports a new function `graphemes(s::AbstractString)` to expose this functionality as an iterator over substrings of `s`.

e.g. `collect(graphemes("b̀lahβlahb̂láh"))` yields `SubString{UTF8String}["b̀","l","a","h","β","l","a","h","b̂","l","á","h"]`.   Note that these are strings, not characters, because graphemes may consist of multiple codepoints (e.g. `"b̀"` is `"\u0062\u0300"` in any normalization).

(This may be useful e.g. in the REPL if we want the arrow keys etcetera to work with graphemes as recommended by UAX#29.)

cc: @jiahao, @Keno

### CODE REVIEW

**Comment by matthieugomez** [comment]
I'm using `graphemes` today. Why does `next` return  `s[i:j]` rather than `SubString(s, i, j)`?

**Comment by stevengj** [comment]
@matthieugomez, I don't understand your question.   `graphemes` iterates over substrings, e.g. `collect(graphemes("Hello, 世界 noe\u0308l et noël"))` returns an `Array{SubString{UTF8String},1}`.

**Comment by matthieugomez** [comment]
I'm on my phone but first(graphemes("hello")) is ASCIIString not a Substring

**Comment by nalimilan** [comment]
Good catch! See https://github.com/JuliaLang/julia/pull/13903.

**Comment by stevengj** [comment]
Oh, right; I think I thought that `s[i:j]` returned a substring at the time.

**Comment by matthieugomez** [comment]
Yes so the enumerations generates strings. These strings are converted into
substrings when calling collect (due to your eltype definition). But they
are just substrings of themselves. It seems like the way to fix this is to
replace s[i:j] by SubString(s, i, j) in next

**Comment by matthieugomez** [comment]
Thanks. I have another question. With your type definition, some functions defined for AbstractStrings could directly work on GraphemeIterator, like chr2ind, nextind etc. but currently one needs to redefine all of them. Could GraphemeIterator be an AbstractString? If not could there be a common parent of ABstractStrings and Grapheme iterator?

**Comment by nalimilan** [comment]
@matthieugomez GraphemeIterator sounds very different from an `AbstractString`. It's more like a collection of strings, actually. What would `chr2ind` or `nextind` do on a `GraphemeIterator`?

**Comment by matthieugomez** [comment]
@nalimilan Sorry i was not clear

AbstractStrings and `GraphemeIterator` are both iterators on characters. In a `GraphemeIterator` the type of a character is a `SubString` rather than a `Char`, but both correspond to our notion of character. 

Another reason is that they have the same implementation. AbstractStrings and `GraphemeIterator` are both implemented as indexable array where only some index that are valid. For these structures, functions such as `chr2ind` and `nextind` make sense : they allow to map elements to their starting index in the array. Both iterators use the starting index as the iterator state.  For this reason, `chr2ind` and `nextind` already work on `GraphemeIterator` — yet they're only defined on `AbstractString`.

My user case is the following. I'm currently writing a package computing various [string distances](https://github.com/matthieugomez/StringDistances.jl). Most of these distances work by comparing characters.I've written a package with the idea that a character = a Char. But the functions should also allow to compare strings with the idea that a character = a grapheme. Looking at my code, I just need to sign all methods with a `Union{AbstractString, Grapheme}`,  define `SubString(x::GraphemeIterator,...) = SubString(x.s,...)`, and extend `chr2ind` and `nextind` to work on Graphemes (by copying the code used to define these functions on `AbstractStrings`. It seems like there should be some kind of inheritance.

**Comment by nalimilan** [comment]
I think it would be more logical to consider iterating over characters and iterating over graphemes as two different ways of going over a string. You could define a `CharacterIterator` similar to `GraphemeIterator`, and use one or the other, or let the user pass one of these two types as an argument. Note that currently, `GraphemeIterator` isn't indexable: would you pass it a byte index or an index expressed in number of graphemes?

(Actually, one could even advocate that iterating over a string shouldn't be possible: you would be required to do `for c in characters(s)` or `for c in graphemes(s)`, so that you make an explicit choice.)

**Comment by matthieugomez** [comment]
If I only needed to use  `for` loop, wrapping a string in two different enumerators types would be enough. 
But I need more than the iterator interface: I also need functions such as `nextind`, `chr2ind` (which differs between chars vs graphemes although they're implemented similarly once we have the functions `start`, `next`, `done`), or `endof` (which should return the same value for both).

To answer your question, I would pass the index as a byte index, similarly to Unicode. The only difference between a graphemes or a Unicode should be that the individual element is a Substring instead of a Char, and that more indexes are invalid.

**Comment by matthieugomez** [comment]
To sum up, my point is that having the function `nextind` and `chr2ind` defined on `GraphemeIterator` would allow me to write a more generic code (for instance check the definiation of a QgramIterator [here](https://github.com/matthieugomez/StringDistances.jl/blob/master/src/distances/qgram.jl). These functions are restricted to an `AbstractString` signature for now, but they would directly work on GraphemeIterators, due to the way `start`, `next` are implemented in this pull request. So it seems like there's some duplication going on.

**Comment by matthieugomez** [comment]
I'm trying to follow @nalimilian idea by defining two different iterating wrappers for AbstractString. But it's hard to rewrite stuff like `split`, `join`, etc so that the iteration property of the string is conserved after passing the function. There must be a better solution.

**Comment by nalimilan** [comment]
@matthieugomez What do you mean exactly? Are you trying to allow calling `split` on these iterators?

**Comment by matthieugomez** [comment]
Yes. One reason your solution does not work for me it that it's very inelegant to define string distances that don't accept strings. This means someone the code is harder to read, and one cannot just copy past the code and use it in its library. Another reason is that I still need to `Substring` or `split` these iterators (ie apply a function on the wrapped string and then wrap the output so that the iterator property of the original string is conserved). So with enough methods the iterator starts to look like a string. But since it is not an abstractString, I keep having to redefine new methods.

**Comment by nalimilan** [comment]
I think you misunderstood my suggestion. My proposal was to always work with the standard string, and apply operations (`split`...) to it, but to also carry an iterator type that you call on that string when you need to iterate over its characters or its graphemes. But I'm not in position to evaluate whether this suits your needs.

**Pull request merged**
