### PR TITLE
teach compiler that `getindex` on SimpleVector is effect-free when Const

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is for @Keno .

### CODE REVIEW

**Comment by Keno** [comment]
thank you! :)

**Comment by tkelman** [comment]
can whatever behavior this changes be tested?

**Comment by Keno** [comment]
@JeffBezanson Can you check that https://github.com/JuliaLang/julia/commit/97c7496d908ef665b3fe1e363a78c6b2261e9481 is a correct backport of this? If so, this appears to break Optim precompilation. @andreasnoack has details

**Comment by andreasnoack** [comment]
I got this one with this commit
```julia
julia> using Optim
INFO: Precompiling module Optim.
ERROR: LoadError: LoadError: `float` not defined on abstractly-typed arrays; please convert to a more specific type
Stacktrace:
 [1] float(::Array{Int64,1}) at ./float.jl:844
 [2] include_from_node1(::String) at ./loading.jl:539
 [3] include(::String) at ./sysimg.jl:14
 [4] include_from_node1(::String) at ./loading.jl:539
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /global/cscratch1/sd/noack/.julia_cori/v0.6/Optim/src/problems/unconstrained.jl, in expression starting on line 193
while loading /global/cscratch1/sd/noack/.julia_cori/v0.6/Optim/src/Optim.jl, in expression starting on line 108
ERROR: Failed to precompile Optim to /global/cscratch1/sd/noack/.julia_cori/lib/v0.6/bfebfbff7ffefbff/Optim.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:673
 [2] require(::Symbol) at ./loading.jl:460
```
and it disappeared when I reverted it.

**Comment by JeffBezanson** [comment]
Wow, that is really strange. @Keno how do I get the version of llvm needed to build that branch?

**Comment by Keno** [comment]
There's github.com/Keno/llvm kf/celeste4, but you'll need https://github.com/JuliaLang/julia/pull/21366

**Comment by JeffBezanson** [comment]
In the mean time, what's `@code_typed float([1:250;])`?

**Pull request closed without merging**
