### PR TITLE
Clarify stdlib package for identity matrix

### PR DESCRIPTION
**Pull request by Yijia-Chen**
When I tried to create an identity matrix, I had an issue where `I` is not defined, and I could not figure out why. Clarifying that you need `LinearAlgebra` is probably helpful for people who don't realize they need the stdlib package.

### CODE REVIEW

**Comment by stevengj** [comment]
`I isa AbstractArray` is `false`, so the section on multi-dimensional arrays is the wrong place for this.  It's really a linear-algebra-specific object.

**Comment by andreasnoack** [comment]
> It's really a linear-algebra-specific object

That is true but many people would probably be looking for `eye` in this section so having a short cross reference to `I` would be helpful.

**Comment by stevengj** [comment]
Okay, but it seems like it would make more sense to put this directly in the table entry for `Matrix{T}(I, m, n)`.    That is, instead of `m-by-n identity matrix`, it would say `m-by-n identity matrix; requires using LinearAlgebra for I`

**Comment by ViralBShah** [comment]
Is there an easy way for me to rebase a PR that is on a fork onto master?

**Comment by stevengj** [comment]
I rebased it, Viral.   (Procedure: `git fetch` the branch, then rebase, then `git push`.)

**Comment by ViralBShah** [comment]
> I rebased it, Viral. (Procedure: `git fetch` the branch, then rebase, then `git push`.)

Thanks. I was following the command line instructions that github provides here, and they seemed to complicated.

**Pull request merged**
