### PR TITLE
Bump `Pkg` version to be `Artifact`-aware

### LINKED ISSUE #32913: Update Pkg to include Artifacts
We want to tag a new version of Pkg with https://github.com/JuliaLang/Pkg.jl/pull/1277 and merge it into Julia master before branching for 1.3.

### PR DESCRIPTION
**Pull request by staticfloat**
This introduces the new `Pkg.Artifacts` subsystem into the standard library.

Closes #32913

### CODE REVIEW

**Comment by ararslan** [comment]
Why did we get an Azure Pipelines status from this? o_O

**Comment by staticfloat** [comment]
Somebody has been playing around with Github Actions I think

**Comment by staticfloat** [comment]
@mortenpi What is the right way to do `using Pkg.Artifacts` in front of all of the doctests in `Pkg`?

**Comment by mortenpi** [comment]
> @mortenpi What is the right way to do `using Pkg.Artifacts` in front of all of the doctests in `Pkg`?

Adding

```julia
DocMeta.setdocmeta!(Pkg, :DocTestSetup, :(using Pkg, Pkg.Artifacts), recursive=true, warn=false)
```

after https://github.com/JuliaLang/julia/blob/4c4751d03b9446ccbe017b2a2a254a73be59fd55/doc/make.jl#L148-L156 should work I think?

**Comment by mortenpi** [comment]
I think you also need this:

```julia
DocMeta.setdocmeta!(Pkg.BinaryPlatforms, :DocTestSetup, :(using Pkg, Pkg.BinaryPlatforms), recursive=true, warn=false)
```

Should be fine if you get `using BinaryPlatforms` just for the doctests in `Pkg.BinaryPlatforms`?

**Comment by staticfloat** [comment]
I think Morten and I have fixed all the doctest problems (needed to adjust a few of the docstrings in the Pkg repo itself as well).  If this goes reasonably green (I've been seeing windows buildbot problems recently for some reason) let's call it good and merge.

**Comment by KristofferC** [comment]
It would be good to see a green CI for Pkg for the commit we put into master. So far a bunch of things got pushed to Pkg directly to master / without running CI.

**Comment by KristofferC** [comment]
Let's bump the commit here to whatever https://github.com/JuliaLang/Pkg.jl/pull/1298 ends up getting merged into and then merge here.

**Comment by KristofferC** [comment]
Failed on win64 with


```
tar (child): C\:\\cygwin\\tmp\\jl_42ED.tmpLjzxso.tar.gz: Cannot open: Input/output error
tar (child): Error is not recoverable: exiting now
gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tar (child): C\:\\cygwin\\tmp\\jl_CFE3.tmpOBycTO.tar.gz: Cannot open: Input/output error
tar (child): Error is not recoverable: exiting now
gzip: stdin: unexpected end of file
tar (child): C\:\\cygwin\\tmp\\jl_82BA.tmpbGoEgF.tar.gz: Cannot open: Input/output error
tar (child): Error is not recoverable: exiting now
gzip: stdin: unexpected end of file
tar (child): C\:\\cygwin\\tmp\\jl_7ED2.tmpWvMuMV.tar.gz: Cannot open: Input/output error
tar (child): Error is not recoverable: exiting now
gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tartar (child): :Child returned status  2
C\:\\cygwin\\tmp\\jl_C529.tmpZgJFyd.tar.gz: Cannot tar: Error is not recoverable: exiting now
open: Input/output error
tar (child): Error is not recoverable: exiting now
gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

I restarted it.

**Comment by KristofferC** [comment]
Still happens. It seems to be when the manifest for our documentation is instantiated?

**Comment by staticfloat** [comment]
Okay, I have completed my initial investigation.  Here's what's going on:

Although we download `7z` during `make win-extras`, we do not put it onto the PATH. This is fine on most systems, but on cygwin-based windows systems (like our buildbots) Pkg instantiation fails when it tries to extract tarballs because all of the `tar` and `7z` executables on the PATH are from cygwin and therefore are expecting unixy paths, not the windows paths that Julia passes them.

This should not be fatal; we should gracefully fail and fall back to `libgit2` cloning, which is what happens on `master`, but something breaks horribly within Julia, consistently:

```
Error: Exception while generating log record in module Pkg.Operations at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Operations.jl:487
   exception =
    ReadOnlyMemoryError()
    Stacktrace:
     [1] poptaskref(::Base.InvasiveLinkedListSynchronized{Task}) at .\task.jl:651
     [2] wait() at .\task.jl:658
     [3] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at .\stream.jl:933
     [4] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at .\stream.jl:1002
     [5] macro expansion at .\io.jl:593 [inlined]
     [6] write(::Base.PipeEndpoint, ::Array{UInt8,1}) at .\io.jl:616
     [7] #handle_message#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Base.CoreLogging.handle_message), ::Logging.ConsoleLogger, ::Base.CoreLogging.LogLevel, ::String, ::Module, ::String, ::Symbol, ::String, ::Int64) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Logging\src\ConsoleLogger.jl:161
     [8] handle_message at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Logging\src\ConsoleLogger.jl:100 [inlined]
     [9] macro expansion at .\logging.jl:320 [inlined]
     [10] install_archive(::Array{String,1}, ::Base.SHA1, ::String) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Operations.jl:487
     [11] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Operations.jl:618 [inlined]
     [12] (::getfield(Pkg.Operations, Symbol("##76#79")){Bool,Pkg.Types.Context,Dict{Base.UUID,Array{String,1}},Channel{Any},Channel{Any}})() at .\task.jl:333
@ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Pkg\src\Operations.jl:487
```

**Comment by staticfloat** [comment]
I think we need to figure out why we're segfaulting within `poptaskref()`, but in the immediate-term, we can work around this by manipulating the environment to have a working `7z` on the path.  I will do that, and re-run the tests, and hopefully merge this immediately afterward.

**Comment by staticfloat** [comment]
My temporary workaround worked (although not in quite the way I intended; I pushed a new fix for it, but regardless it passed on win64, and once the win32 buildbots get around to it, we should be good to merge).

**Review by ararslan — APPROVED** [review]

**Pull request merged**
