### PR TITLE
Upgrade to OpenBLAS 0.3.13

### LINKED ISSUE #39201: OpenBLAS 0.3.10 fails to compile from source with Xcode 12
When compiling the OpenBLAS dependency from source I see errors like:
```
lapacke_cggsvp_work.c:52:9: error: implicit declaration of function 'cggsvp_' is invalid in C9
```
The issue seems to be that OpenBLAS 0.3.10 doesn't support xcode 12/clang 12 (https://github.com/xianyi/OpenBLAS/issues/2870). That issue was resolved with OpenBLAS [0.3.11](https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.11) but that particular release mentions it contains defects and shouldn't be used in production environments so we could use 0.3.12 or 0.3.13 instead.

I encountered this issue when compiling Julia on macOS Big Sur without BB on an M1 Mac using Rosetta 2. I've also confirmed that this issue occurs on Intel macs as well.
```sh
make USE_BINARYBUILDER=0 OPENBLAS_USE_THREAD=0 OPENBLAS_TARGET_ARCH=GENERIC OPENBLAS_DYNAMIC_ARCH=0 OPENBLAS_NO_AVX=1 -C deps compile-openblas
```

### PR DESCRIPTION
**Pull request by omus**
Fixes https://github.com/JuliaLang/julia/issues/39201. Requires https://github.com/JuliaPackaging/Yggdrasil/pull/2385. 

~~Possibly this PR also should include the `neoverse-generic-kernels.patch` used with the BinaryBuilder version.~~ (the additional patches are for GCC and don't apply here)

### CODE REVIEW

**Comment by omus** [comment]
I'll mention that the patches here and in the BB version have minor differences but should be functionally identical

**Comment by dkarrasch** [comment]
Should close #36976 and #38865.

**Comment by omus** [comment]
I've successfully ran the Julia test suite locally with OpenBLAS 0.3.13 using dependencies built from source. I just need to get the BinaryBuilder version working.

**Comment by omus** [comment]
Testers seem to have this error (I just spot checked a couple):
```
precompile                         (1) |        started at 2021-01-21T15:46:04.840
julia: /workspace/srcdir/llvm-project/llvm/lib/IR/Value.cpp:460: void llvm::Value::doRAUW(llvm::Value*, llvm::Value::ReplaceMetadataUses): Assertion `New->getType() == getType() && "replaceAllUses of value with new value of different type!"' failed.
signal (6): Aborted
in expression starting at /buildworker/worker/tester_linux64/build/share/julia/test/precompile.jl:850
```

**Comment by omus** [comment]
I had some strange building issues locally that have since disappeared. I'll try a CI re-run as I'm unable to reproduce locally

**Comment by pablosanjose** [comment]
There is a fix to a [LAPACK-netlib bug](https://github.com/Reference-LAPACK/lapack/issues/475) for OpenBLAS [here](https://github.com/xianyi/OpenBLAS/pull/3091). Is there any chance it could be included here as a patch? Or do we need OpenBLAS 0.3.14 to be released?

**Comment by omus** [comment]
> There is a fix to a [LAPACK-netlib bug](https://github.com/Reference-LAPACK/lapack/issues/475) for OpenBLAS [here](https://github.com/xianyi/OpenBLAS/pull/3091). Is there any chance it could be included here as a patch? Or do we need to wait for OpenBLAS 0.3.14 to be released?

It's fine to include the patch here.

**Comment by omus** [comment]
CI error seems to be the same as: https://github.com/JuliaLang/julia/issues/27055

**Comment by pablosanjose** [comment]
> It's fine to include the patch here.

Should I do a PR onto this PR? The patch is quite simple, just [this](https://gist.github.com/pablosanjose/3b673d14865ac7c7bdef194feca1c966)

**Comment by omus** [comment]
Just providing the patch is good enough. I can incorporate the patch here but I may start with it disabled until I sort out the CI issue.

**Comment by pablosanjose** [comment]
Many thanks! The issue addressed by the patch is making my life complicated, given that it produces convergence errors that are difficult to predict and are platform-dependent. I really appreciate this!

**Comment by omus** [comment]
Disabling the test that seems to cause the failure on CI just to see if that's the only issue

**Comment by omus** [comment]
> The patch is quite simple, just [this](https://gist.github.com/pablosanjose/3b673d14865ac7c7bdef194feca1c966)

The patch you provided appears to be corrupt. I've regenerated the [patch](https://gist.github.com/omus/c25ec6e3f871a062799a4275b40bb448). If you could make sure it still is correct that would be great

**Comment by pablosanjose** [comment]
Uh, sorry, I actually tried to adapt the full patch at https://github.com/Reference-LAPACK/lapack/pull/477 into an OpenBLAS patch (the relevant files are identical), but I guess that's not how this is done (I've never done it before). Unfortunately, the OpenBLAS PR https://github.com/xianyi/OpenBLAS/pull/3091 you took the patch from was merged before the full fix was made upstream in https://github.com/Reference-LAPACK/lapack/pull/477, so that patch you posted is actually incomplete... Is there a way to adapt  https://github.com/Reference-LAPACK/lapack/pull/477 into an OpenBLAS patch?

**Comment by pablosanjose** [comment]
Forget all I said above. Your patch is correct, it includes all the important commits. Thanks.

**Comment by pablosanjose** [comment]
My confusion above was due to the fact that the original fix in https://github.com/Reference-LAPACK/lapack/pull/477 has been ported to OpenBLAS in two parts, https://github.com/xianyi/OpenBLAS/pull/3087 and https://github.com/xianyi/OpenBLAS/pull/3091. When you corrected my corrupted patch I believe you made a patch with only the latter PR, but not the former. I'm pretty sure they are both necessary. The question is how to do a single patch that applies two PRs. I'm afraid I don't know how to do that, but perhaps you do?

**Comment by pablosanjose** [comment]
Is it clear what is the cause of the CI failure here? 

[The macos failure (`[1] pipeline_error
    @ ./process.jl:525 [inlined]`) reminds me of [this issue](https://github.com/JuliaLinearAlgebra/MKL.jl/issues/60) , if that's any help]

**Comment by omus** [comment]
Patch should now include xianyi/OpenBLAS#3087 and xianyi/OpenBLAS#3091.

**Comment by omus** [comment]
After applying the revised patch and rebasing I am unable to reproduce the doctest failure or the issue with opaque closures locally.

**Comment by omus** [comment]
Looks like the opaque closure failures were fixed somewhere else. I've managed to reproduce the docstrings failures in a Linux environment but oddly they don't fail on macOS with or without adjusting the docstrings.

**Comment by omus** [comment]
I've updated the doctests to pass on Linux. With these changes however the doctests no longer locally pass on macOS for me. I'm looking into why this is happening but I wanted to see if the CI passes. If the CI tests all pass we may want to run doctests for each platform.

**Comment by staticfloat** [comment]
looks like there might be a legitimate macos issue?

**Comment by omus** [comment]
> looks like there might be a legitimate macos issue?

Does look legitimate:
```
Error in testset LinearAlgebra/eigen:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.7/LinearAlgebra/test/eigen.jl:87
  Expression: f.values ≈ eigvals(a1_nsg, a2_nsg)
   Evaluated: ComplexF64[-2.2091829272839187 + 0.0im, -0.1929516548950063 - 0.5797178835402432im, -0.1929516548950063 + 0.5797178835402432im, 1.840108365237263 + 0.0im, 13.613564441762232 + 0.0im] ≈ ComplexF64[-2.2091829272839187 + 0.0im, -0.19295165489500624 + 0.5797178835402432im, -0.1929516548950062 - 0.5797178835402432im, 1.840108365237263 + 0.0im, 13.613564441762232 + 0.0im]
Error in testset LinearAlgebra/eigen:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/stdlib/v1.7/LinearAlgebra/test/eigen.jl:87
  Expression: f.values ≈ eigvals(a1_nsg, a2_nsg)
   Evaluated: ComplexF64[-2.2091829272839187 + 0.0im, -0.1929516548950063 - 0.5797178835402432im, -0.1929516548950063 + 0.5797178835402432im, 1.840108365237263 + 0.0im, 13.613564441762232 + 0.0im] ≈ ComplexF64[-2.2091829272839187 + 0.0im, -0.19295165489500624 + 0.5797178835402432im, -0.1929516548950062 - 0.5797178835402432im, 1.840108365237263 + 0.0im, 13.613564441762232 + 0.0im]
```

**Comment by chriselrod** [comment]
Flipped signs on the 2nd and 3rd imaginary numbers. I wonder how that happened.

**Comment by pablosanjose** [comment]
I'd say this sorting failure is not a real issue. The problem is that eigenvalues are sorted by `(real(λ), imag(λ))`. So if there is a degeneracy in `real(λ)` (as it happens here) the final order of the corresponding eigenvalues is unpredictable, and depends on rounding errors in `real(λ)`.

**Comment by ViralBShah** [comment]
Yes, this is not a real issue, but it will break the tests. Should we just mark this test as `@test_skip` for now so we can get all greens and merge?

**Comment by staticfloat** [comment]
If Pablo can show how to do `sortby` with the generalized `eigvals()` function, I think we should be able to fix the test rather easily.

**Comment by ViralBShah** [comment]
> If Pablo can show how to do `sortby` with the generalized `eigvals()` function, I think we should be able to fix the test rather easily.

That's not hard - but for things where the rounding errors can change the order, the order may change again in the future. But for now we can do a `sortby`. @pablosanjose It would be great if you can offer what order to use (since you have looked at the problem), or even better a PR.

**Comment by ViralBShah** [comment]
Unfortunately, the test doesn't fail on my mac.

**Comment by pablosanjose** [comment]
It appears tests now pass in #39767. I used `sortby = x -> real(x) + imag(x)` with the rationale that the failure was due to unpredictable sorting of exactly conjugate eigenvalue pairs `a ± i b` (that however satisfy no particular relation between `a` and `b`). These arise for real non-symmetric random matrices. I didn't modify the ordering in the other cases.

**Comment by pablosanjose** [comment]
When we upgrade to OpenBLAS 0.3.14 (due, in principle, in a week or so, according to [this](https://github.com/xianyi/OpenBLAS/milestone/33)), the exshift patch will not be needed anymore (as it has been merged to OpenBLAS master). It's great to have it in Julia in the meantime, as it fixes a very ugly bug in `eigen!(A,B)`, but we must remember to remove it in the next OpenBLAS upgrade.

**Comment by ViralBShah** [comment]
Assuming all tests pass, is this PR good to merge?

**Comment by omus** [comment]
Probably should have removed the WIP from the commit message. What's our feeling on changing it?

**Comment by ViralBShah** [comment]
I was mostly looking at the diff and not the commit message. I'm not sure if things can be(?) changed on master - but there are a few other wip commit messages in the log. I'll leave it to the git specialists to decide.

I am removing the WIP from the PR title though.

**Comment by KristofferC** [comment]
Based on https://github.com/JuliaLang/julia/issues/40279 I will take off the backport label here. It can be put back until it is resolved.

**Comment by ViralBShah** [comment]
Fixed through new binaries in https://github.com/JuliaPackaging/Yggdrasil/pull/2769.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/40361

**Comment by ViralBShah** [comment]
Wow I can't imagine what is causing that.

**Comment by KristofferC** [comment]
Me neither, it was discussed a bit in the #binarybuilder channel in Slack but nothing concrete came out of it.

**Comment by omus** [comment]
#40361 has been addressed (details: https://github.com/JuliaLang/julia/issues/40361#issuecomment-815286928). Should the backport label be added again?

**Comment by ViralBShah** [comment]
Given that 1.7 is going to not be too far away (timed releases going forward), and we've found various openblas related issues, it might be best not to backport.

**Comment by vchuravy** [comment]
We should backport the fix to the LTS https://github.com/JuliaLang/julia/issues/40492#issuecomment-1011481698

**Pull request merged**
