### PR TITLE
Backports for Julia 1.8.4

### LINKED ISSUE #43921: Product iterator is not zipped properly
When zipping with a product iterator with no arguments (which produces only one output, the empty tuple), it seems the check for zip completion does not handle this case:
```
julia> for (z,) in zip(Iterators.product())
       @show z
       end
z = ()
ERROR: ArgumentError: tuple must be non-empty
Stacktrace:
 [1] first(#unused#::Tuple{})
   @ Base ./tuple.jl:140
 [2] _pisdone
   @ ./iterators.jl:1005 [inlined]
 [3] isdone
   @ ./iterators.jl:1012 [inlined]
 [4] _zip_isdone(is::Tuple{Base.Iterators.ProductIterator{Tuple{}}}, ss::Tuple{Tuple{Bool}})
   @ Base.Iterators ./iterators.jl:379
 [5] _zip_iterate_all
   @ ./iterators.jl:348 [inlined]
 [6] iterate
   @ ./iterators.jl:341 [inlined]
 [7] top-level scope
   @ ./REPL[79]:2
```

`versioninfo()` output:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = vim
```
EDIT: `zip([()])` works fine though:
```
julia> for (z,) in zip([()])
       @show z
       end
z = ()

julia> 
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #44827 
- [x] #45893 
- [x] #47229 
- [x] #43947 
- [x] #47433 
- [x] #47460 
- [x] #47482 
- [x] #46976 
- [x] #46844 
- [x] #47499 
- [x] #47580 
- [x] #47586 
- [x] #47668 
- [x] #47637 
- [x] #47665 
- [x] #47739 
- [x] #47719 
- [x] #47783 
- [x] #47803 
- [x] #47741 
- [x] #47859 

Need manual backport:
- [ ] #47865 

Contains multiple commits, manual intervention needed:
- [ ] #46819 
- [ ] #45582 

Non-merged PRs with backport label:
- [ ] #47636 
- [ ] #46801

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I'd like to get https://github.com/JuliaCI/julia-buildkite/pull/259 merged before this PR is merged. This will allow Buildkite to upload `.zip` files for Windows for 1.8.4.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(; vs=":release-1.8")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.8")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47488#issuecomment-1350679678) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/280047e_vs_0434deb/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47488#issuecomment-1351319473) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/992d4ca_vs_0434deb/report.html).

**Comment by KristofferC** [comment]
The PkgEval failures are due to https://github.com/QuantumBFS/LuxurySparse.jl/pull/72.

**Pull request merged**
