### PR TITLE
Fix bad Blob ctor in libgit2 tests

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Thanks!

**Comment by KristofferC** [comment]
Please merge as soon CI finish

**Review by Sacha0 — APPROVED** [review]

**Comment by Sacha0** [comment]
Travis macOS failure (known?) unrelated?
```julia
Error in testset spawn:
Error During Test
  Test threw an exception of type InterruptException
  Expression: success(pipeline(@cmd("sh -c \"for i in 1 2 3 4 5 6 7 8 9 10; do echo \\\$i; sleep 0.1; done\""), (prefixer("X", 0.3) & prefixer("Y", 0.3)) & prefixer("Z", 0.3), prefixer("A", 0.2) & prefixer("B", 0.2)))
```

**Comment by ararslan** [comment]
I think it's unrelated because I _think_ I've seen it before, I just have no idea what the cause is

**Comment by Sacha0** [comment]
Thanks `@kshyatt`!

**Pull request merged**
