### PR TITLE
Misc doc fixes

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Fixes for several small bugs and inconsistencies.

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Good to merge?

**Comment by StefanKarpinski** [comment]
Looks good to me. @MikeInnes, would you mind reviewing?

**Comment by MikeInnes** [comment]
Yup, looks like a great set of patches to me!

**Comment by MichaelHatherly** [comment]
Thanks.

**Pull request merged**
