### PR TITLE
Revert "Revert "Bump Pkg to 1.4-DEV. (#33364)" (#33410)"

### PR DESCRIPTION
**Pull request by fredrikekre**
This reverts commit 0b55ce12bf882d7db1e8eb68c91cb03f7e135c33.

### CODE REVIEW

**Comment by KristofferC** [comment]
Try if BaseBenchmarks now works with this

@nanosoldier `runbenchmarks("linalg", vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/33434#issuecomment-537059788):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`/home/nanosoldier/workdir/tmpZP9pld/julia -e 'VERSION >= v"0.7.0-DEV.3656" && using Pkg; Pkg.update()'`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ab546fa1c775cde142d870cbac290896815e1f33/c96212e_vs_4fa6a62/report.md)
cc @ararslan

**Comment by KristofferC** [comment]
@ararslan, could you check the logs and see what is going on?

**Comment by ararslan** [comment]
Looks like one of the nodes didn't have an updated BaseBenchmarks. Not sure how/why that happened, but I updated it manually.

@nanosoldier `runbenchmarks("linalg", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/33434#issuecomment-537131315) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a95f813e8375709f0503ac59d90870c6f06caf7f/40d2417_vs_06d6b8e/report.md). cc @ararslan

**Review by KristofferC — APPROVED** [review]

**Pull request merged**
