### PR TITLE
WIP: Run travis tests under rr

### PR DESCRIPTION
**Pull request by garrison**
This is an experiment to see how feasible it is to run tests under [`rr`](http://rr-project.org/), inspired by [discussion here](https://github.com/JuliaLang/julia/pull/10738#issuecomment-95374001).

### CODE REVIEW

**Comment by vtjnash** [comment]
that's pretty cool to see as an experiment. any idea how we would go about saving off the results to somewhere we could play with it?

**Comment by garrison** [comment]
@tkelman suggested sending the dump to gist.  Since some of the files are binary that may not be the *best* option, but in any case it should be possible to put everything in a tarball and then HTTP POST it somewhere to save it (which, come to think of it, is somewhat similar to how we get coverage results).

**Comment by vtjnash** [comment]
since you need the whole `make install` directory, i think the HTTP POST will be the way to go. I'm just not sure of the best way to do that. Is is possible to run a post-fail hook? Is it possible to dump this (from within travis) on some file-hosting like google drive or dropbox and delete the files on a frequent basis?

**Comment by tkelman** [comment]
Hrm, judging by https://github.com/mozilla/rr/issues/1433 this might not work under Travis. We could try it on our buildbots (and just use our S3 space), I think they're running KVM on OpenStack? I think @staticfloat is the only person with ssh access to those machines, would be good to check if they can provide the perf counters that rr needs.

**Comment by garrison** [comment]
Ah yes, that issue was [discussed previously here](https://github.com/JuliaLang/julia/issues/10021#issuecomment-73349341).

**Comment by tkelman** [comment]
Hm, kernel too old on non-docker workers apparently? The Travis docker workers use 3.13.0-29-generic according to https://travis-ci.org/amitmurthy/LibExpat.jl/jobs/59514940, but that's going to take some serious dependency wrangling, and it could easily complain about the performance counters after that.

**Comment by timholy** [comment]
Even though there are obviously some challenges to getting this working, I'm going to :100: this general idea---if successful, it could be transformative. Keep up the awesome work, @garrison!

**Comment by carnaval** [comment]
Oh! Wishes come true overnight here. If this succeeds I expect to see the number of CI failures to go down drastically, reproducing being the hardest part of the work most of the time. Glad to see you working on this @garrison :-)

**Comment by garrison** [comment]
I got travis using the docker image now (though I disabled the julia build), and indeed `rr` complains about the lack of perf counters there.

**Comment by tkelman** [comment]
Bummer. We should still try on the buildbots. Ping @staticfloat can you try building rr there if you get a chance, see if it works?

**Comment by hayd** [comment]
It may be worth posting an issue on https://github.com/travis-ci/travis-ci.

*I searched for "rr" and the only issue is about "RR (Double Ruby)".*

**Comment by staticfloat** [comment]
just wanted to ACK here and let you guys know I'll try this this weekend.

**Comment by staticfloat** [comment]
I looked through this really quick, and before trying to install `rr` or anything, took a look at the [performance counters offered on one of my buildbots](https://gist.github.com/ad064cd6ae653f2afba7) as mentioned by the [rr issue](https://github.com/mozilla/rr/issues/1433) linked above.  Can someone who knows better than I tell if those results from `sudo perf list` are a good sign?  To me it doesn't look good.

For reference, here's the [output from an actual bare metal machine](https://gist.github.com/e4f1044c7adede489ef6).

**Comment by pao** [comment]
The [rr wiki](https://github.com/mozilla/rr/wiki/Building-And-Installing) mentions "If rr isn't working at all, run `dmesg|grep PMU`." How is the buildbot setup? There are instructions for enabling PMUs for certain virtualization environments listed on the linked wiki page.

**Comment by staticfloat** [comment]
Buildbots are running on MIT's openstack cloud, which are all KVM-virtualized machines.  I'm not sure what kind of hardware they run on top of, but this doesn't look super hopeful:
```
$ sudo dmesg | grep PMU
[    0.024000] Performance Events: unsupported p6 CPU model 44 no PMU driver, software events only.
```

I don't have access to the virtualization configuration of course, but I'll email the MIT TIG guys and see what they have to say about it.

**Comment by pao** [comment]
Yeah, that looks like a no-go as is. Googling for "kvm pmu" brings me [here](http://www.linux-kvm.org/page/Guest_PMU), which claims both "out of tree patches" and "implemented and works", so hard to be sure...

**Comment by garrison** [comment]
I have a DigitalOcean droplet and it seems to support perf counters (at least the output of `dmesg` is promising).

    $ dmesg | grep PMU
    [    0.024001] Performance Events: generic architected perfmon, Intel PMU driver.

If we could demonstrate that this indeed works, might it be worth setting up buildbots there?

**Comment by staticfloat** [comment]
That is promising.  What is the output of `sudo perf list`?

**Comment by garrison** [comment]
The output is fairly long (what, in particular, should I be looking for?).  But it may not matter what it says.  The *good* news is that I just compiled `rr` on a DigitialOcean droplet in the SFO data center, and I just successfully ran `rr record /bin/ls`.

**Comment by pao** [comment]
> what, in particular, should I be looking for?

That first stanza that says "Hardware Event" in the rightmost column. If those exist (it's not documented exactly which ones you need, but I think they kind of come as a set on the right processors) then you're good to go.

Cool that it's working, though.

**Comment by garrison** [comment]
Alright, I just managed to (purposely) segfault Julia on my DigitalOcean droplet and replay it under `gdb` using `rr`.  So I think we have a winner here.

**Comment by tkelman** [comment]
Nice. So should we try to hook up a DigitalOcean droplet to buildbot? Or just add a dedicated webhook for it?

**Comment by pao** [comment]
If it's a no-go from the MIT cloud team, that seems reasonable. You'd want to hook it to a successful build (with the possibility of failing tests) that the machine could download and install, then rerun tests, yes?

To ensure we get the exact same libraries, too, should we install the generic Linux tarball? Do we produce that every build?

**Comment by ihnorton** [comment]
Has anyone compared the test time-to-completion under rr vs. without? I know it is supposed to be only a few percent overhead, but it would be good to know exactly what the cost is. We already have issues with test duration.

Also, see rocallahan's [comment](https://github.com/JuliaLang/julia/issues/10021#issuecomment-96875785).

**Comment by tkelman** [comment]
> Do we produce that every build?

Almost. See http://buildbot.e.ip.saba.us:8010/builders/ - if all the `build_*` jobs complete successfully and pass tests, then a binary gets made by the `package_*` jobs.

**Comment by staticfloat** [comment]
Yep, ironically, we only build a binary when all the tests pass on all the
platforms.

**Comment by garrison** [comment]
Per @ihnorton's comment and others, it seems that we really want `rr` running on separate infrastructure from our main tests.  The purpose of existing tests is to tell us whether a commit passes all tests.  Since `rr` runs on a single core, doing this for all tests will influence the results and lead to us missing race conditions.

The purpose of the `rr` workers, on the other hand, is to have a good log of test failures (and not necessarily be the thing that tells us definitively whether a build is good or bad).  For this reason the behavior of the `rr` build bots should probably be slightly different too. If the `rr` builder is ahead -- i.e. it has built and run the latest commit on master and on each branch until there was success or failure -- we could even have it repeatedly run the test suite on the latest `master` build until it finds a failure or something else is committed, in the hopes of catching an intermittent bug.

**Comment by staticfloat** [comment]
Well, I'd be happy to help set this up, (I haven't heard back from the MIT guys yet) but unfortunately the piece of the puzzle I can't speak to is money.  How much would it cost to run a droplet such as you've built, continuously?

**Comment by pao** [comment]
> Yep, ironically, we only build a binary when all the tests pass on all the platforms.

To be fair, for public builds that's a perfectly reasonable approach.

**Comment by garrison** [comment]
Depends on how much RAM.  A single core with 512MB RAM is $5/month.  I used a 2-core, 2GB Droplet to test, and the cost of it is $20/month.

Another option--if we don't want to run on a dedicated machine--would be to make it easier for people to run the test suite locally under `rr` (perhaps even repeatedly), and be able to share the results with others (the latter part is key).  Since we're all running on different Linux distributions, sharing a build (as currently done) is unlikely to be useful.  But one thing we could do is to set up a system to build julia locally using [nix](http://nixos.org/nix/), and then run the `rr` tests locally on that.  Since `nix` works on all Linux distributions, it would then mean that two people using the same architecture could ushare and use the same build of julia, even if they are not using  the same Linux distribution.  Hence, an `rr record` and `rr replay` that allow any one of us to share a crash with others, and long as it occurs in this environment.

**Comment by pao** [comment]
@garrison The generic tarballs include all dependencies, and we already produce them (modulo the conversation above, but that seems easily changed). Does nix add anything else to that? If not, it's just creating more work and more friction to actually performing a replay.

**Comment by staticfloat** [comment]
If possible, I think it would simplify things significantly to use the
generic linux binaries as much as possible.  Even though nix works on huge
number of linux distributions, compiler differences and system library
differences and such can cause the binaries built by nix on two platforms
to be different.  Using the same .tar.gz file from our binaries stash
should, however, work out just fine.  (In theory)
-E

**Comment by pao** [comment]
(ping-pong with @staticfloat) And if we're worried about differences in i.e., glibc, we can work from a common base container.

**Comment by garrison** [comment]
I hadn't considered the generic linux binaries.  I suppose that is the better option indeed.

**Comment by staticfloat** [comment]
@pao I don't think we even need to worry about `glibc`, since the whole reason we build the linux binaries on an archaic version of CentOS is to force it to link against an ancient `glibc`, so it only uses the lowest common denominator functions.

**Comment by staticfloat** [comment]
This does indeed sound pretty useful, @garrison.  How do you currently run the Julia tests against `rr`?

**Comment by pao** [comment]
I don't know enough about `rr`'s internals is all--if it's symbol-level stability, yep, agreed that shouldn't be an issue.

**Comment by garrison** [comment]
If we run `rr record` using one version of glibc and `rr replay` using another, what happens?  My assumption is that it would not work, but I am not sure.  Assuming it wouldn't work, I guess my point was that if we wanted to run *locally* instead of on a dedicated machine (or even if we want to take a build from the `rr` runner and debug it on a local machine), it would be necessary to have the exact same distribution running, with glibc version/build and all.  Using nix is the only way I know of to provide a way of doing this across distributions, as far as I know.

**Comment by staticfloat** [comment]
I'm pretty darn certain `nix` doesn't rebuild `glibc`; If we require that level of certainty, then we will need a virtual machine/docker container that enforces a very strict host OS version.  But I very much doubt it will require such shenanigans.  I propose we put it to the test!  If you can give me the instructions for running the Julia test suite inside `rr`, I'll record a trace on a reasonably new Ubuntu 14.04 machine on an Intel processor, and we can see what other machines we can `replay` it on.

**Comment by pao** [comment]
I'm game. I have a 12.04 machine I can test on.

**Comment by garrison** [comment]
Nix indeed builds its own glibc.  But another option (less complex than nix) would be to statically link glibc in the builds we use for `rr` (is this possible?).

**Comment by staticfloat** [comment]
> Nix indeed builds its own glibc.

Well then, color me shocked and enlightened.  :)

**Comment by garrison** [comment]
To test `rr` I wouldn't even try running the whole test suite -- just a trivial julia program.  (I know that the `spawn` tests currently fail under `rr`, perhaps others too.)  The `rr` wiki has instructions for building (you'll need the latest version, `3.1.0`, for julia to work).  Then, do something like `~/rr/obj/bin/rr record ./julia -e "Libc.free(Ptr{Void}(1))"` to purposely create a segfault.

**Comment by garrison** [comment]
Following [discussion elsewhere](https://github.com/JuliaLang/julia/issues/10021#issuecomment-97248380), it seems unlikely that `rr` will allow us to share traces from machine to machine anytime soon, even if `glibc` versions match.

**Comment by carnaval** [comment]
I think it's fine. Just being able to have easy ssh access to the box would go a long way. If it's on a VPS we could even snapshot the VM with the recording and replay it locally right ? (not that it changes much)

I'm looking forward to this.

**Comment by garrison** [comment]
Let me summarize my current thinking, based on the discussion above.

At the moment it is possible for anybody running Linux to run the julia test suite under `rr`.  This involves disabling the `spawn` tests (there is a failure involving `SIGPIPE`) and the `profile` tests (as `rr` does not support the `timer_create`, `timer_settime`, and `timer_delete` syscalls, at least not yet).  Perhaps we could make running the test suite in this way easier by documenting which tests to disable, or figuring out how to make all the tests work.  (Is there a way, from C, to detect whether the code is running under `rr`?  If so, we could just disable certain tests, just as we do when running under valgrind.)

Encouraging people to run tests under `rr` locally has some distinct advantages.  It does not require any additional infrastructure beyond what we have now.  Also, the range of systems tested will be much more diverse than a single buildbot could ever offer (that is, individual users will have a wider array of hardware and Linux distributions than we would set up).  The downside is that (since `rr` traces are not yet portable) the person finding a bug is then responsible for debugging it with `gdb`, whether or not they are the person most familiar with the code that crashed.

And so another option is to somehow set up a build bot in the cloud, which runs `rr record` until a crash occurs.  Then, we could either allow (some subset of) people to login to the host to debug it, or we could find a way for people to download the image of the virtual machine and debug it locally under virtualization.  I'm unsure which way would make more sense.

As mentioned, running `rr` on a cloud machine has the drawback that we'd be testing a smaller set of build configurations than if everybody were to run `rr` individually.  The obvious benefit, though, is that it would give more people access to the replay when a failure does occur.  Are there any other benefits that I have not considered? And overall would this be worth the effort of setting up and maintaining a host?  (In particular, is having a buildbot running `julia` under `rr` going to lead to bugs being found and fixed far sooner than they would be otherwise?)  That's what I'm trying to figure out.

**Comment by tkelman** [comment]
> Is there a way, from C, to detect whether the code is running under `rr`? 

Good question, worth asking the rr devs about.

> or we could find a way for people to download the image of the virtual machine and debug it locally under virtualization. I'm unsure which way would make more sense.

Shouldn't using a docker container work for this? I think docker would be easier for this purpose than nix.

**Comment by garrison** [comment]
> Shouldn't using a docker container work for this? I think docker would be easier for this purpose than nix.

I think nix is out of the running, as it doesn't solve all the problems that need to be solved for trace portability.  Based on a look at the `rr` [trace portability notes](https://github.com/mozilla/rr/wiki/Trace-Portability), I don't think a lightweight container (as offered by Docker) would solve the problems either.

**Comment by ihnorton** [comment]
Just as a follow-up on the overhead question... unscientifically, my conclusion is "much more than 2x", at least for codegen. I've just run bootstrap under `rr` and it is over 10x slower, and still not finished. Maybe LLVM? Maybe the fact that in type inference the stack rolls 300+ deep? ... We do have some codegen-intensive test suites (linalg...) so do keep an eye on this before burning a bunch of CPU credits somewhere.

**Comment by garrison** [comment]
When I ran the testsuite under rr, it seemed to take about 10% longer in walltime for me.  (The exception was the parallel tests, which took probably 4 times longer.)

**Comment by garrison** [comment]
@ihnorton can disable the `spawn` and `profile` tests and see what the difference is on the testsuite?  (I also set `n=1` in `julia/test/runtests.jl` to run on a single worker.)  It would be interesting to know if the slowdown you're experiencing is indeed an issue specific to codegen.

**Comment by tkelman** [comment]
different relative behavior with different versions of llvm maybe?

**Comment by ihnorton** [comment]
@tkelman this is on LLVM3.6, but so is my baseline.
@garrison ok, cool, 10% is reasonable. Makes sense that it would be much lower overhead when using an optimized version of type inference vs. when trying to actually compile inference itself. I'm mostly just sad that `rr` won't make my bootstrap-debugging life any better. Carry on!

**Comment by garrison** [comment]
Since having `rr` work on Travis is hopeless, I'm going to close this in favor of #11150 (which I believe is the main actionable thing to come out of this discussion).

**Comment by staticfloat** [comment]
I'll post this in #11150 presently, but to update everyone who was watching this thread, the MIT cloud guys are making sure setting the proper KVM options for this doesn't break anything, and if it turns out okay, then they're going to set it up early next week.  I can't guarantee it will work, but I think we've got a good shot at it working.

**Comment by garrison** [comment]
Awesome!

**Comment by rocallahan** [comment]
> I've just run bootstrap under rr and it is over 10x slower

Please file an rr issue on this with steps to reproduce! It's very likely we can fix it in rr, or possibly suggest fixes to your code that will fix it.

**Pull request closed without merging**
