### PR TITLE
move `Libdl` to stdlib

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Capitalizations of this has always bothered me. This might be a good moment to adjust it... maybe `Base/Libdl` => `stdlib/LibDL`?

**Comment by JeffBezanson** [comment]
Tough call; on the one hand `LibDL` is a bit nicer (though a bit harder to type), but `Libdl` is closer to the actual name of the library. It also looks a bit odd for a name to be 3/5 uppercase.

**Comment by StefanKarpinski** [comment]
Your call, just thought I'd mention it while you were renaming. I slightly prefer `LibDL`.

**Comment by thofma** [comment]
Was this intentionally without NEWS entry and deprecation warning? Tested a package on 0.7 and was greeted by `ERROR: UndefVarError: Libdl not defined`.

**Pull request merged**
