### PR TITLE
Generalized CartesianRange

### PR DESCRIPTION
**Pull request by Jutho**
This PR provides a different implementation of CartesianRange which is more general in that it also allows `StepRange`s. I have been conservative in restricting everything to subtypes of `OrdinalRange{Int,Int}`, though most of the implementation is completely general up to one or two lines. I think a completely general implementation is possible, though for this it would be helpful if `next` is split into `nextval` and `nextstate` as was suggested in a different context some time ago.

I have not been able to detect a noticeable slowdown using some quick tests with BenchmarkTools. If there is one, it cannot be more than a few percent. I would of course like some thoughts and comments, e.g. from @timholy .

### CODE REVIEW

**Comment by tkelman** [comment]
should the new capabilities this allows be tested?

**Comment by Jutho** [comment]
Sure, I should have added WIP to the title. Tests are on the todo list.

**Comment by timholy** [comment]
I'm in favor. I've thought about this multiple times in the past, though at the moment I can't remember a concrete example of what I wanted this for.

I've also looked over the implementation; I didn't notice any issues, so once there are tests and nanosoldier gives its blessing, I'd say this is good to go.

**Comment by JeffBezanson** [comment]
At this point this is very similar to a product iterator. Is there some way to combine them or share implementations?

**Comment by Jutho** [comment]
Yes I have actually been making the exercise to build a type stable product iterator in complete generality. See here:
https://gist.github.com/Jutho/4dfecd7d39b1379950cc8d28a153ba20

Two issues:
1) This is more natural using an iteration protocol with `nextval` and `nextstate` separated. I now define `nextval` and `nextstate` myself and hope that the compiler will optimize this for simple enough iterators (e.g. ranges).

2) I don't know how to recursively (i.e. lisp style) build a `Type{T1,T2,...}` object in a type stable way. Hence I just determine `eltype` of the iterator from evaluating `typeof` on the first value. I looked at `Base.tuple_type_cons` but it doesn't seem to be properly inferred (yet?).

**Comment by Jutho** [comment]
Also, this general implementation has probably a small performance hit over `CartesianRange`. I should benchmark some more but have been doing other stuff in the mean time. I should have some time later this week.

**Comment by Jutho** [comment]
Ah, I just noticed there actually is a product iterator in Base already

**Comment by Jutho** [comment]
... and about as fast as
`@benchmark collect($(CartesianRange(CartesianIndex(10,10,10,10,10))))`

I cleaned up the gist some more.

**Comment by Jutho** [comment]
Ok, I now also understand why I did not find `product` in the first place. I did look for `Base.Iterators` but also did not find that. I was apparently not working on master but rather on some `julia v0.5.?` version where `product` itself is not exported but `Base.Iterators` does not exist. Anyway, I will close this PR and, after some more benchmarking, maybe prepare a different PR to replace `Base.Iterators.product` with my implementation if that sounds ok to @JeffBezanson .

And then maybe even `CartesianRange` (just the default without the `StepRange` generalization) can be written in terms of that?

**Pull request closed without merging**
