### PR TITLE
more atomic dep install

### PR DESCRIPTION
**Pull request by vtjnash**
this should help when switching between versions not to get a partial install. this happens to me a lot when trying to jump between LLVM versions, for example.

### CODE REVIEW

**Comment by vtjnash** [comment]
merged in 8fc5b4e605a843eaa702b4c1cba74f5cb6fded22

**Comment by tkelman** [comment]
This is a lot of extra copying for a problem that you seem to have hit more often than anyone else. I never have issues with this, but I also make a point to `make cleanall` between switching versions of anything. This makes compilation in the regular case noticeably slower, especially on Windows.

**Comment by vtjnash** [comment]
it's not really that large:
```
du -sh usr-staging/
169M	usr-staging/
```

given the speed of hard drives with reasonably modern hardware, i would expect this to complete within ~5 seconds:
```
~/Documents/no-backup/julia$ time cp -a usr-staging/ usr-staging2
real	0m11.571s
user	0m0.050s
sys	0m0.786s
~/Documents/no-backup/julia$ time cp -a usr-staging/ usr-staging3
real	0m5.315s
user	0m0.046s
sys	0m0.633s
~/Documents/no-backup/julia$ time cp -a usr-staging/ usr-staging4
real	0m4.290s
user	0m0.042s
sys	0m0.583s
```

i've noticed that windows has a lot of trouble with `rm -rf` however. that operation completes in < 1 second on linux/osx for this folder, but perhaps may be taking quite a bit longer on windows?

for me, this is the difference between needing to call `rm -rf usr` before changing a dependency version (of llvm, mostly), and having the build system just get it correct for me.

and most of that is llvm anyways, so you should only end up paying this cost when installing llvm, which is already slow anyways.

fwiw too, this may open up the possibility of some additional build features in the future, like using the `usr-staging` folder as a location-agnostic cache for some dependencies, instead of compiling them on each new machine

**Comment by tkelman** [comment]
the `rm -rf` is not that long for me, but the `cp -a` takes over 40 seconds here

**Comment by vtjnash** [comment]
is xcopy (or windows explorer) any faster?

**Comment by tkelman** [comment]
Yes, `xcopy /E /Q /I usr-staging usr-staging3` takes only 2.5 seconds. It however skips `llvm-ranlib.exe` and a bunch of pcre `man3` files which are cygwin symlinks.

**Comment by vtjnash** [comment]
alright, let's just switch to that then, conditional on BUILD_OS=WINNT

why do we have cygwin symlinks showing up? that seems like a separate, additional issue.

**Comment by tkelman** [comment]
bug in pcre and/or llvm's autotools, possibly.

**Comment by vtjnash** [comment]
oh well, lets go with it anyways since it's a lot faster and those files aren't needed for anything. can you make the commit?

**Comment by tkelman** [comment]
For cygwin cross-compile, BUILD_OS is not WINNT (and probably shouldn't be, given the number of msys assumptions sprinkled around the makefiles for that case).

**Comment by tkelman** [comment]
Wanted to double-check here before pushing straight to master, shouldn't `make distcleanall` delete `$(build_staging)` here https://github.com/JuliaLang/julia/blob/d107cd9eab23c9162ac86d022408732911ea1b78/Makefile#L496?

**Comment by vtjnash** [comment]
yes

**Pull request closed without merging**
