### PR TITLE
make core `eltype` definitions operate on types

### PR DESCRIPTION
**Pull request by JeffBezanson**
This way, when the type entirely determines `eltype`, a single definition is enough to make `eltype` work for both types and values. We were not consistent about this before; some types supported it and others didn't.

### CODE REVIEW

**Comment by vtjnash** [comment]
+1

when is this getting merged?

**Comment by JeffBezanson** [comment]
So I accidentally broke something here, but in a useful way. Apparently we had:

```
julia> collect(combinations("abc",2))
3-element Array{ASCIIString,1}:
 "ab"
 "ac"
 "bc"
```

Does anybody else find that a bit too clever? I'm fine with always returning a vector for each combination, or in the future a Combination type.

**Comment by kmsquire** [comment]
Unless there are objections, I'm going to

1. add this to `Compat.jl`
2. update `Iterators.jl` to use the same logic

**Comment by kmsquire** [comment]
https://github.com/JuliaLang/Compat.jl/pull/43
https://github.com/JuliaLang/Iterators.jl/pull/38

**Pull request merged**
