### PR TITLE
Fix overflow for hypot in Float16

### LINKED ISSUE #38311: `hypot` for Float16 regressed
I changed the commit as suggested in PR https://github.com/JuliaLang/julia/pull/38272, however some issue arised during running tests with make command:

```
ach@ach-Vostro-7580:~/development/julia/packages/julia$ make test-math
    JULIA test/math
Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
math       (1) |        started at 2020-11-05T01:59:33.535
math       (1) |         failed at 2020-11-05T02:00:11.506
Test Failed at /home/ach/development/julia/packages/julia/test/math.jl:1173
  Expression: #= /home/ach/development/julia/packages/julia/test/math.jl:1173 =# @inferred(hypot(x, complex(x / 4))) ≈ x * sqrt(17 / BigFloat(16))
   Evaluated: Inf16 ≈ 33759.98886255740458193770390071574268190526725735920411685601169650148618781252
```

the issue is with Float16, when I remove Float16 from the tested types, all tests pass.

When I do the same in REPL, everything goes as it should:

```
julia> using Test

julia> x = floatmax(Float16)/2
Float16(3.275e4)

julia> @test (@inferred hypot(x, complex(x/4))) ≈ x * sqrt(17/BigFloat(16))
Test Passed
```

Interestingly, the test in line below passes even with Float16:

```
@test (@inferred hypot(x, complex(x/4), x/4)) ≈ x * sqrt(9/BigFloat(8))
```

all test pass.

It seems that there is something wrong with make command.

## Version Info

```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = pkg.juliahub.com
  JULIA_DEPOT_PATH = /home/ach/.julia:/opt/JuliaPro-1.5.2-1/Julia/local/share/julia:/opt/JuliaPro-1.5.2-1/Julia/share/julia
  JULIA_LOAD_PATH = @:@v#.#:@stdlib
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #38311, includes tests from #38272.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by KristofferC** [comment]
Bump, here's another one from PkgEval:

```jl
julia> hypot(Float16(0.004406) - Float16(0.01092)im)
NaN16
```

**Comment by JeffBezanson** [comment]
Bump. Looks like this has some test failures?

**Comment by JeffBezanson** [comment]
Bump.

**Comment by stevengj** [comment]
Wouldn't we be better off doing the `Float16 calculations as:
```jl
_hypot(x::Float16, y::Float16) = Float16(_hypot(Float32(x), Float32(y)))
_hypot(x::ComplexF16, y::ComplexF16) = ComplexF16(_hypot(ComplexF32(x), ComplexF32(y)))
```

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
