### PR TITLE
Split base/string.jl into logical pieces, and split test/strings.jl, test/unicode.jl to match new organization

### PR DESCRIPTION
**Pull request by ScottPJones**
The first commit splits up string.jl into more logical, manageable pieces.
The second commit splits up test/strings.jl into files that match the files in base by name.
The third commit splits up test/unicode.jl into files that match the files in base by name.
The fourth commit puts the base string code into subsdirectories, strings and utf.

Finally, in another PR, I'll be able to add extra tests to get strings to hopefully 100% coverage.

### CODE REVIEW

**Comment by quinnj** [comment]
-1, this seems like overkill. It would be much better to create a `Strings` module with a single `strings.jl` file in the `/base` directory and a `strings` folder that includes more like 3-5 files of stuff broken out.

**Comment by ScottPJones** [comment]
The things I split out are pretty much totally unrelated - a lot don't really even seem to belong under a "Strings" module, and other splitting out is in preparation to boot them out of Base entirely and into packages.

**Comment by nalimilan** [comment]
I agree that you went too far here. For example, `stringchop.jl`,  `stringcmp.jl` and `base/stringstrip.jl` don't deserve being separated. I think you should aim at files with about 500 lines, not 50!

But +1 to the idea of splitting a little bit more than currently, and moving everything to a subdirectory.

**Comment by ScottPJones** [comment]
Hmm, I guess I still disagree, it's not about how many lines of code some set of functions has, but rather, do they really fit together logically.
I could move the ones that are implement using different logical pieces of strings into a subdirectory, but not all that was in `string.jl` even belonged there.

**Comment by tkelman** [comment]
Dozens of 50-line files are just a pain. Let's not go there.

**Comment by StefanKarpinski** [comment]
OTOH, Matlab has one file per function – optimal logical separation.

**Comment by ScottPJones** [comment]
I didn't create a `Strings` module yet, because this PR has any real "substantive" changes, it is totally splitting up the files and then renaming them (the only code changes are in `sysimg.jl` and `choosetests.jl`.
One reason that I tried to split things up on a logical basis, no matter the resulting size, rather than just trying to carve it into some arbitrary "reasonable" size, is that it makes life a lot easier over time.
Files that are stable may not get changed again in years, and that it much likelier to happen if you don't have one mongo "strings" file, or even smaller ones with unrelated parts (this is much like the issues of preventing cache-line ping-ponging).  I don't know how many times over the last two months I've had to rebase and manually merge stuff, because something unrelated to what I was working on changed one or more of base/string.jl, test/strings.jl, and test/unicode.jl.
This also helps in tracking down bugs, because the backtrace saying line xx in `strings/RepStrings.jl` is a lot more informative than line xxxx in `string.jl` or `strings.jl`, and sometimes the line number isn't even good, because of macros being used.

**Comment by quinnj** [comment]
Scott, we've had 3-4 collaborators say they're decidedly against this with several tips on what *may* be more acceptable (I'm still not convinced this is really worth the effort...).

**Comment by ScottPJones** [comment]
@quinnj I don't think it's a very good thing to just shut down somebody else's PR while they are actively working on it.  That's incredibly annoying - and I haven't even had a chance to defend why I believe this is a much better organization.  Saying something is "overkill" or "just a pain", without anything to back up *why*, is not really a technical argument.  Also, it was *my* effort, here til 5am last night, not yours.

**Pull request closed without merging**
