### PR TITLE
WIP: truly sparse broadcast when not zero preserving

### PR DESCRIPTION
**Pull request by mfalt**
This PR presents one possible solution to having truly sparse results when doing non-zero-preserving broadcast on sparse matrices, see https://github.com/JuliaLang/julia/issues/21515#issuecomment-298713344.
Instead of returning a full sparse `C` on `C = sprand(n,n,0.0)./sprand(n,1-p)`, `C` is now `p%` full.
This greatly improves performance on further usage of `C`, reduces the memory allocated on call and usually seems to improve computation time for most calls.

This solution avoids a separate implementation of  `_broadcast_notzeropres!(f::Tf, fillvalue, C::SparseVecOrMat, A::SparseVecOrMat, B::`<b>`Dense`</b>`)` which would otherwise be needed in my opinion, since "Sparse ./ Dense" is currently handled by "Sparse ./ Sparse" which is horrible for cases like `C = sprand(n,n,p)./rand(n)`.

I only implemented it for the case  `numrows(A) == numrows(B) == numrows(C)` since there are several questions to be considered:
1. Is this the right approach?
2. Is it better to fill the expanded vector with `fillvalue` immediately (as is done in this PR), or should it only be filled with `fillvalue` on `nskip!=0`, i.e. when a set of `0/0` operations are skipped?
3. The code is now quite similar to `_broadcast_zeropres!`, should they be merged, and can it be done without significant performance loss? 
4. What is the right approach to expanding the storage? This implementation expands it by roughly a factor 2 each time, is this a good trade-off between number of allocations and excessive memory usage?

### CODE REVIEW

**Comment by kshyatt** [comment]
Welcome to Julia, @mfalt! It looks like some of the `sparse` tests are failing - are you able to reproduce that locally?

**Comment by mfalt** [comment]
Well,  yes, it's quite a significant redesign and I only rewrote one out of three cases in the function, so there's no expectation of passing the tests for the other cases. I just wanted to illustrate my idea, and start a discussion before I spend too many hours rewriting and benchmarking everything, which is why I added the WIP tag.

**Comment by Sacha0** [comment]
Thanks for having a look at this @mfalt! I should think the design tradeoffs through more before commenting. Could you describe your use case? Best!

**Comment by mfalt** [comment]
@Sacha0, sure, do you mean the use case where this was a problem or on which I'm testing the code?
The problem arose when I was computing a factorization, which should be used for repeated projection onto a linear space. Something like
```julia
""" Store QR factorization for projection onto Ax=b """
function MyType(A::SparseMatrixCSC, b::AbstractVector)
    normrows = vec(1.0./sqrt.(sum(abs2.(A), 2))) #Norm or rows
    A = A./normrows  #Normalize
    b = b./normrows
    F = qrfact(A')  #Sparse factorization
    MyType(A,b,F)
end
```
which ends up storing and factorizing a sparse matrix with no structural zeros since `A./normrows` is calling sparse `_broadcast_notzeropres!`.  This example was relatively easy to fix by doing
```julia
normrowsinv = 1./normrows
A = A.*normrowsinv
```
but I think this is a fundamental flaw that we should consider fixing.
I have been testing the code in the PR on examples like
```julia
A = sprandn(n,10000,p1)
b = sprandn(n,p2)
C = A./b
D = C*2 + C
```
for different values on `n`, `p1` and `p2`. The performance gain is significant when most elements are not results of `0/0` and `A` is sparse, i.e. when `p2>>0, p1<<1`. Did this answer your question?

**Comment by mfalt** [comment]
Do we have any more thoughts regarding this? I think the a solution is really needed, but I'm not sure if I'm able to judge if this is the right approach.

**Comment by StefanKarpinski** [comment]
bump: @tkelman, @Sacha0

**Comment by Sacha0** [comment]
Apologies for the slow response here @mfalt! I will eke out time to think this through and respond at least over JuliaCon. Best!

**Comment by Sacha0** [comment]
Stream-of-consciousness thoughts :).

Two cases exist: Either all operands are sparse, or some operands are dense. These cases have competing demands: When all operands are sparse, the result should be (practically speaking) full. When some operands are dense, the result may be sparse.

The existing methods are optimized for the all-operands-sparse case (originally the only case designed-for). These methods' memory consumption may be suboptimal in the some-operands dense case. Conversely, methods optimal for the some-operands-dense case will perform suboptimally in the all-operands-sparse case.

In favor of the existing design, all-operands-sparse is in some sense the expected case. Additionally, the existing methods' result indicates that one is generally operating over all (i.e. `O(prod(size(result)))` rather than `O(numstored(operands))`) entries. This behavior has some virtue. For example, said behavior provides a nice hint that `broadcast` is a suboptimal means to achieve the row and/or column scaling operations you mention above. (Though where the dense operands have expanded singleton dimensions as in scaling ops, we sometimes are / can be a bit clever to avoid an asymptotic hit.)

In favor of changing the design, `broadcast`ing a not-zero-preserving operation over all-sparse operands is already a performance catastrophe. And trading some performance in that case may facilitate avoiding spurious OOM killers in some legitimate some-operands-dense use cases. In the preceding some-operands-dense cases, downstream operations will perform much better as well.

The tradeoffs have me leaning towards changing the design, weighting avoiding an OOM over a constant factor performance hit in an already catastrophic case.

Thoughts @tkelman @KristofferC @stevengj @nalimilan ? Best! :)

**Comment by mfalt** [comment]
> The tradeoffs have me leaning towards changing the design, weighting avoiding an OOM over a constant factor performance hit in an already catastrophic case.

I think this is a good point. There are several heuristics that can be taken to achieve this.
1. One extreme is to only pre-allocate enough space for the minimum number of nnz i.e. something like `max(nnz(A),nnz(B))`, (ignoring the dimensions of broadcast here). This assumes that there won't be any non-zero-perserving operations, and allocates space when needed.
2. Probabilistic approach: Allocating extra space according to the expected number of non-zero assuming uncorrelated zero locations. Using some simple code, not taking into account edge-cases:
```julia
elementsA, elementsB, elementsC = prod(size(A)), prod(size(B)), prod(size(C))
probnzA, probnzB = (elementsA-nnz(A))/elementsA, (elementsB-nnz(B))/elementsB
probzerozero = (1-probnzA)*(1-probnzB) #Probablility that an element is f(0,0)
nnzguess = max(nnz(A),nnz(B)) + ceil(Int, probzerozero*elementsC)
expandstorage!(C, min(nnzguess, elementsC))
```
This would allocate nothing extra when one of the inputs are dense and allocate a dense result if both matrices are empty.

3. I'm sure there are other reasonable assumptions, any ideas?

**Comment by DilumAluthge** [comment]
We have moved the SparseArrays stdlib to an external repository.

Please open this PR against that repository: https://github.com/JuliaLang/SparseArrays.jl

Thank you!

**Pull request closed without merging**
