### PR TITLE
Adds AbstractRNG to various methods which utilise rand.

### LINKED ISSUE #10345: overloads for combinatorics.jl methods that accept rng's as parameters
It would be cool if we had some overloads for functions in combinatorics.jl (like randperm and shuffle) that accept an rng as an argument.

Using the global rng works fine 99% of the time, but that 1%!  Gah!

Here's a contrived example:

`# seed the global rng`
`srand(42)`

` # do something random a non-deterministic number of times` 
`for line in lines_in_a_file shuffle(collect(1:10)) end`

`# later, do a shuffle on something unrelated`
`shuffle(collect(1:10))`

Global seeding is great, but if you invoke rand() a non-deterministic number of times... well the global rng is a non-deterministic state there on out, so you can't really get deterministic behaviour out of it  unless you reinitialize it like so: `srand(42)`.

I guess that's fine, but doesn't that approach break down when you get into distributed computation?

Anywho, I'm trying to make a case for always including overloads that accept an rng, in any method, not sure how successful the point is coming across.

I'm happy to pick it up as an issue unless someone else would rather give it a shot.

### PR DESCRIPTION
**Pull request by simonbyrne**
Partially fixes #10345. Also utilise `randexp` in `randsubseq` instead of taking log of `rand`. I had to move some methods around so that `AbstractRNG` would be defined when they were parsed.

Remaining methods which call `rand` without an `AbstractRNG` argument are 
- ~~`sprand`: this is a bit complicated, as it accepts an optional functional argument for generating the values.~~ now done.
- `SharedArray` and `DArray` methods: I don't understand these well enough to know how they interact with the RNG
- `mktempdir` in file.jl (windows only).
- ~~`peakflops` in linalg/generic.jl~~

### CODE REVIEW

**Comment by ivarne** [comment]
DArray seems to be moving (https://github.com/JuliaLang/julia/pull/10334), so a PR to fix the RNG for them should probably go to https://github.com/JuliaParallel/DistributedArrays.jl

`mktempdir` does uses OS functionality on Unix, so I think relying on the global RNG is fine.

CC: @rfourquet

**Comment by simonbyrne** [comment]
Yeah, I don't think we need to worry about `mktempdir` or `peakflops`.

**Comment by simonbyrne** [comment]
Okay, I've added some tests, and updated `sprand`.

**Comment by ViralBShah** [comment]
I am ok with this. SharedArray will probably go into a package later on, once we have multi-threading.

**Pull request merged**
