### PR TITLE
Remove bit-rotted plife example from release-0.3

### PR DESCRIPTION
**Pull request by IainNZ**
Seems to require an external package

Cross-ref: http://stackoverflow.com/questions/31198482/how-to-run-plife-jl-in-julia-examples

### CODE REVIEW

**Comment by tkelman** [comment]
Which PR/commit took this out of master?

**Comment by ivarne** [comment]
Seems like it also depends on DArray, which has been removed in my https://github.com/JuliaLang/julia/commit/b84b0e274ae3d6011c048b1ad8d16eeec9fc6769.

git blame is useless to find when something was deleted, but luckily the history on test/examples.jl was short.

**Comment by IainNZ** [comment]
Yeah it was DArray removal.

**Comment by amitmurthy** [comment]
But since DArray continues to exist on 0.3, plife should have continued to work with 0.3. Shouldn't we have fixed the example instead of removing it?

**Comment by IainNZ** [comment]
It seems to depend on an external package that no longer exists in that form, I suspect a long-dead version of Tk.jl. So, it shouldn't have been there in the first place. Feel free to submit another PR replacing it in the release-0.3 branch with a working one, but I think it'd be better to port it to DistributedArrays.jl (which it was not initially).

**Comment by amitmurthy** [comment]
Ah! OK. Didn't realize it also depended on Tk.

**Pull request merged**
