### PR TITLE
𝟎-𝟗 and 𝟘-𝟡 Identifiers 

### PR DESCRIPTION
**Pull request by ajozefiak**
Implementation of issue #26808

### CODE REVIEW

**Review by StefanKarpinski — COMMENTED** [review]
Shouldn't this allow all bold and double struck digits, not just 0s and 1s?

**Comment by StefanKarpinski** [comment]
In fact, looking at [this page](http://shapecatcher.com/unicode/block/Mathematical_Alphanumeric_Symbols.html), maybe all of [U+1d7ce](http://shapecatcher.com/unicode/info/120782) through [U+1D7FF](http://shapecatcher.com/unicode/info/120831). It seems like the same reasoning applies to all of these if it applies to any of them. Although maybe not the sans-serif and monospace digits since those are pretty likely to just look like normal digits in many places, as opposed to the bold and double struck ones, which are a common typographical convention.

**Comment by Keno** [comment]
The consistent thing to do would be to allow all of ND expect ASCII 0-9

**Comment by StefanKarpinski** [comment]
Consistent, sure, but we might want to normalize some of them first.

**Comment by Keno** [comment]
Sure, but that's a) an orthogonal concern and b), breaking since we already allow these in identifiers (just not in leading position).

**Comment by JeffBezanson** [comment]
I vote for adding U+1d7ce through U+1d7e1

**Comment by Keno** [comment]
Works for me. We can always add more of Nd later if we want.

**Review by Keno — APPROVED** [review]

**Comment by JeffBezanson** [comment]
A NEWS entry would be good.

**Pull request merged**
