### PR TITLE
Added value of sinc and cosc at Infinities.

### PR DESCRIPTION
**Pull request by pjgaudre**
Defined the value of the sinc and cosc functions for their limiting values at plus or minus infinities.

### CODE REVIEW

**Comment by jiahao** [comment]
Thanks for your contribution.

`isinf(x)` is a more efficient test for infinity and it would be better to use that here.

**Comment by nalimilan** [comment]
Maybe use `isinf(x)` rather than `abs(x)==Inf`?

Other than that, I can't comment on the opportunity of this change.

**Comment by nalimilan** [comment]
Rhah, too late! :-)

**Comment by mschauer** [comment]
The limit holds only for ``<:Real``, not for ``<:Numbers``, right?

**Comment by pjgaudre** [comment]
Of course! isinf would be better and yes, mschauer, these limits only hold for real numbers.

**Comment by mschauer** [comment]
Now definitions are recursive... this would need tests, see https://github.com/JuliaLang/julia/blob/master/test/math.jl .

**Comment by simonbyrne** [comment]
I think the simplest forms would be:
```julia
sinc(x::Number) = x==0 ? one(x)  : isinf(x) ? zero(x) : oftype(x,sinpi(x)/(pi*x))
cosc(x::Number) = x==0 || isinf(x) ? zero(x) : oftype(x,(cospi(x)-sinpi(x)/(pi*x))/x)
```

**Comment by KristofferC** [comment]
Would `ifelse` be worth it to potentially avoid a branch?

**Comment by simonbyrne** [comment]
I don't think it's worth worrying about: `sin` is a function call, so it's not readily vectorizable in any case (at least at the moment).

**Comment by MikaelSlevinsky** [comment]
@simonbyrne, except that those definitions only hold for `x::Real`. I think the `x::Complex` limit depends on the direction in the complex plane. Do these work?
```julia
sinc(x::Real) = x==0 ? one(x) : isinf(x) ? zero(x) : sinpi(x)/(pi*x)
cosc(x::Real) = x==0 || isinf(x) ? zero(x) : (cospi(x)-sinpi(x)/(pi*x))/x
sinc(x::Complex) = x==0 ? one(x) : isinf(x) ? (imag(x) == 0 ? zero(x) : oftype(x,Inf)*complex(1,sign(real(x))*sign(imag(x)))) : sinpi(x)/(pi*x)
cosc(x::Complex) = x==0 || isinf(x) ? (imag(x) == 0 ? zero(x) : oftype(x,Inf)*complex(sign(real(x)),-sign(imag(x)))) : (cospi(x)-sinpi(x)/(pi*x))/x
```

**Comment by pjgaudre** [comment]
For the complex case, there are many cases to consider depending on the value of both the real part and imaginary part. To the best of my knowledge, I think this covers all scenarios for the sinc function.

```julia
function sinc(x::Complex)
  if x == 0
    return one(x)
  elseif isinf(real(x))
    if isfinite(imag(x))
      return zero(x)
    else
      return oftype(x,NaN)*complex(1,1)
    end
  elseif isinf(imag(x))
    if isinteger(real(x))
      return complex(Inf*sign(cospi(real(x))),0)
    elseif isinteger(2*real(x))
      return complex(0,-Inf*sign(sinpi(real(x))))
    else
      return oftype(x,Inf)*complex(sign(cospi(real(x))),-sign(sinpi(real(x))))
    end
  else
    return sinpi(x)/(pi*x)
  end
end

```

**Comment by simonbyrne** [comment]
Ah good point, I wasn't thinking about `Complex`, but I don't think `NaN` is the correct answer: some of those limits are well-defined. If we're going to fix it, we should also fix the cases where it returns incorrect `NaN`s for finite values as well (e.g. `sinc(0.0 +250.0*im)`).

However this is probably a bit of work: it will require a bit of complex analysis to figure out what those limits should be (unless you can find a good reference), and fix some of the other incorrect functions (e.g. `sinpi(1+300*im)`, as well as adding tests and docs.

Why don't we limit this pull request to the `Real` case for now (and combine #14855 into this as well)? If you're up for it, you can put the `Complex` case into a separate pull request: feel free to ping me if you have any questions.

**Comment by mschauer** [comment]
> Why don't we limit this pull request to the Real case for now 
I also think that this would be a good idea.

**Comment by MikaelSlevinsky** [comment]
Sounds good to me. @pjgaudre, do you agree? Does it make sense to include the tests of #14855 in one PR?

**Comment by simonbyrne** [comment]
Yes, definitely combine #14855 into this.

**Comment by pjgaudre** [comment]
Sure, I agree. We can certainly limit this pull request to the Real case. That said, I think @MikaelSlevinsky 's definition is good. We can definitely include the tests of #14855. I didn't know how to add them to this pull request so I made a separate one by mistake. Thanks for the help guys!

**Comment by pjgaudre** [comment]
Sorry for the lack of experience. This is my first time making a pull request to the Julia community. In the future, would I simply include the tests in the file as part of my commit?

**Comment by nalimilan** [comment]
> Sorry for the lack of experience. This is my first time making a pull request to the Julia community. In the future, would I simply include the tests in the file as part of my commit?

Yes, that sounds natural.

**Comment by pjgaudre** [comment]
@nalimilan Sounds good! Thanks!

**Comment by tkelman** [comment]
not in the same file in base/ though, the tests should still be under test/

**Comment by nalimilan** [comment]
Ugh, looks like I misunderstood your question. I thought "commit" that was the key word, not "file".

**Comment by simonbyrne** [comment]
@pjgaudre Tests should go in `test/math.jl`. Once you're done with that, could you squash your commits? If you've not done it before, see [here](http://docs.julialang.org/en/release-0.4/manual/packages/#squashing-and-rebasing) for some instructions (feel free to ask if you get stuck).

**Comment by simonbyrne** [comment]
Thanks for doing all that.

**Comment by mschauer** [comment]
Nice.

**Pull request merged**
