### PR TITLE
Fix LAPACK test: don't call `sygvd!` on `undef`ed matrix

### LINKED ISSUE #964: LinearAlgebra/lapack error on CI in sygvd
```
LinearAlgebra/lapack                             (2) |         failed at 2022-10-28T14:23:53.339
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-aee41e1c57/share/julia/stdlib/v1.9/LinearAlgebra/test/lapack.jl:30
  Expression: LAPACK.sygvd!(1, 'V', 'U', copy(Asym), Matrix{elty}(undef, 6, 6))
    Expected: DimensionMismatch
      Thrown: ArgumentError
LinearAlgebra/svd                                (3) |    26.26 |   1.40 |  5.3 |    3490.46 |  1671.30
```
https://buildkite.com/julialang/julia-master/builds/17588#01841fc9-4176-4a2c-875f-a3fba6343de2

### LINKED ISSUE #47376: LinearAlgebra/lapack error on CI in sygvd
```
LinearAlgebra/lapack                             (2) |         failed at 2022-10-28T14:23:53.339
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-aee41e1c57/share/julia/stdlib/v1.9/LinearAlgebra/test/lapack.jl:30
  Expression: LAPACK.sygvd!(1, 'V', 'U', copy(Asym), Matrix{elty}(undef, 6, 6))
    Expected: DimensionMismatch
      Thrown: ArgumentError
LinearAlgebra/svd                                (3) |    26.26 |   1.40 |  5.3 |    3490.46 |  1671.30
```
https://buildkite.com/julialang/julia-master/builds/17588#01841fc9-4176-4a2c-875f-a3fba6343de2

### PR DESCRIPTION
**Pull request by dkarrasch**
Fixes JuliaLang/LinearAlgebra.jl#964.

### CODE REVIEW

**Comment by dkarrasch** [comment]
Is this also a test issue on v1.6? Should we backport this to v1.6 and v1.8?

**Review by vtjnash — APPROVED** [review]

**Comment by KristofferC** [comment]
Might as well

**Comment by Keno** [comment]
The same pattern is used in a bunch of other places in this file also.

**Comment by N5N3** [comment]
The error should come from #47074, which adds NaN check before the dimension check.
So this should be a fresh (and limited) CI regression. Perhaps there's no need for 1.6 backpork.

**Pull request merged**
