### PR TITLE
Backport LLVM patches to fix X86 partial register stall

### LINKED ISSUE #19976: LLVM generates bad code on newer architercures
Didn't find an issue for this. Cross-reference: https://github.com/JuliaLang/julia/pull/19259#issuecomment-270640272

I believe some of the performance "noisy" regressions seen lately are caused by this.

On my machine (Haswell) the [pisum()](https://github.com/JuliaLang/julia/blob/30bf89f3d8e564b588b8e48993e92a551b384f2c/test/perf/micro/perf.jl#L84) benchmark on master gives

```julia
julia> @benchmark pisum()
BenchmarkTools.Trial: 
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     33.362 ms (0.00% GC)
  median time:      33.445 ms (0.00% GC)
  mean time:        33.532 ms (0.00% GC)
  maximum time:     34.761 ms (0.00% GC)
  --------------
  samples:          150
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

while on 0.5 I get

```julia
julia> @benchmark pisum()
BenchmarkTools.Trial: 
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     7.548 ms (0.00% GC)
  median time:      7.571 ms (0.00% GC)
  mean time:        7.611 ms (0.00% GC)
  maximum time:     8.404 ms (0.00% GC)
  --------------
  samples:          657
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

Even when both show practically the same LLVM code.

cc @yuyichao

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #19976 

This improves the performance of `pisum` on one of my machine by ~5.5x and the assembly looks better.

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

@mbauman @KristofferC you probably have better idea about the original/other case this comes up.

### CODE REVIEW

**Comment by Keno** [comment]
Out of curiosity, which of these commits is the actual fix for our issue?

**Comment by yuyichao** [comment]
The fourth patch is the one that nominally fixes it. I included the fifth one because it claims to have fixed a bug in the fourth one. With only this two commit the LLVM tests fails and the failure looks like real codegen regressions so I included a few more that touches the same tests and the LLVM tests are now passing. I'm not entirely sure which ones fixes the "regression" caused by the fix but from the commit message I suspect it's the third one.

**Comment by yuyichao** [comment]
Counted by the order they are cherry picked (see the `[PATCH */5] in the commit message`) Apparently I got the order wrong in `llvm.mk` but there doesn't seem to be too many conflicts.....

So the one that should be fixing this issue is `[PATCH 4/5] Avoid false dependencies of undef machine operands` (also the biggest one though a big part of it is tests...). The fix for it is `[PATCH 5/5] Fixing bug committed in rev. 278321`. The one that I think fixes the regression is `[PATCH 3/5] ExecutionDepsFix - Fix bug in clearance calculation`

**Review by Keno — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9699e886812eddf5dd33d7a7b6cd0b55249dc3dd/b55af93_vs_974e2ff/report.md). cc @jrevels

**Comment by yuyichao** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

Just to check which ones are noise....

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-272607296) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e51ca23323a0608bd20979f4bb1fd60428009ae3/3f25916_vs_71b207a/report.md). cc @jrevels

**Comment by tkelman** [comment]
looks like `["array","growth",("append!",2048)]` was noise, the rest were not

**Comment by Keno** [comment]
I've looked into the regression and the problem is that LLVM fails to take into account the clearance from an incoming backedge when choosing which register to use. Should be fixable, I'll try for a patch.

**Comment by Keno** [comment]
Upstream patch is here: https://reviews.llvm.org/D28759

Will push an update to this PR that adds the upstream patch, so we can re-run nanosoldier.

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-272778157) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/bd6162bdc4b949c3dc876340c2251446c862371b/3c9e6f7_vs_281e2be/report.md). cc @jrevels

**Comment by Keno** [comment]
Looks like I did indeed fix the super bad regressions we saw. There's still `comprehension_iteration` left which I should probably look at. Also, there's some new ones which may or may not be real.
Let's run again to see: @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-272910755) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/0c97f0620409323ebba3e2126d1a7ba9bb5f3272/3c9e6f7_vs_281e2be/report.md). cc @jrevels

**Comment by Keno** [comment]
Ok, I'm gonna go with the comprehension one is the only remaining regression. Looking into it.

**Comment by tkelman** [comment]
`["scalar","arithmetic",("div","Complex{Float32}","Complex{Float32}")]` also looks real and a bit larger?

**Comment by Keno** [comment]
Ah, yes. In any case, the cause seems to be what @yuyichao mentioned to me. Namely, that calls to non-inlined functions don't reset clearance information.

**Comment by Keno** [comment]
https://reviews.llvm.org/D28786 same procedure yesterday.

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-272988275) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b5b349f59689c2aac4e38250d28129e6bb818c38/237cb20_vs_a1f232e/report.md). cc @jrevels

**Comment by vchuravy** [comment]
Travis fails on 32bit:
```
julia: /home/travis/build/JuliaLang/julia/deps/srccache/llvm-3.9.1/include/llvm/CodeGen/MachineOperand.h:268: unsigned int llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
```

**Comment by Keno** [comment]
I was unable to reproduce this locally, but I had an off by one in the patch, which could have easily caused that. Fixed.

**Comment by Keno** [comment]
Also, I think the last nanosoldier run picked up some improvements on master, so @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by Keno** [comment]
In any case, `div` still seems to be broken, so let me take a look at that.

**Comment by KristofferC** [comment]
How did sparse transpose and co get 100x faster.. ?

**Comment by Keno** [comment]
I think it's the other way around :(. This branch was older than master, so sparse transpose is slower on master.

**Comment by mbauman** [comment]
Nanosoldier reports comparing these two commits:

* JuliaLang/julia@237cb207cefaa050c9ca94a0f1f4ef8a32a788f6: this PR @ d006cc4 merged into a1f232e
* JuliaLang/julia@a1f232e77411fcb18e314be1f6f1caa281499f3b: the same master from the merge above

We'll see what this next run brings, but I think it's comparing the right things.

**Comment by Keno** [comment]
This PR shouldn't affect memory allocation though, so something was very wonky.

**Comment by KristofferC** [comment]
The pi sum benchmark showed same improvement as before.

**Comment by Keno** [comment]
Yes, my suspicion was that nanosoldier tested this branch (with outdated master commits) against a more up to date master, which would give the union of {improvements from this branch, reverse of changes on master}. We'll see what the new nanosoldier run has to say.

**Comment by tkelman** [comment]
nanosoldier should be testing against the merge commit

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-273253161) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/0d39a0ae9ef33c9e7faa320a84f8ae391d852a78/9f80457_vs_fab13f2/report.md). cc @jrevels

**Comment by tkelman** [comment]
So everything but complex div, that's pretty good. The assertion failure on travis looks related though?
```
llvm/CodeGen/MachineOperand.h:268: unsigned int llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
```

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-273654606):
```
NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`make`, ProcessExited(2)) [2]")
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9f514c2426067fc363692f93d8893718bf89877f/f5f036c_vs_0dfdc2c/report.md)
cc @jrevels

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-273657993) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/dba3f83951314aeb44844d0e27c4a78c8b74c5f0/a4c4cc1_vs_0dfdc2c/report.md). cc @jrevels

**Comment by vchuravy** [comment]
Nanosoldier seems very happy with this :tada:. LGTM if travis is green

**Comment by martinholters** [comment]
The travis failure looks unrelated. Any ideas what that might be?

**Comment by tkelman** [comment]
it's the mac spawn test issue that https://github.com/JuliaLang/julia/pull/20073 is attempting to fix. these patches should be updated to match whatever gets committed upstream once it goes through review there, but lgtm for now

**Comment by Keno** [comment]
Let's wait a few days while upstream review is ongoing. The problem with replacing these patches later is that they won't apply cleanly to people who've had this version applied. Also, FYI, the second commit has been split up into 
https://reviews.llvm.org/D28915.

**Comment by tkelman** [comment]
Any news upstream on these?

**Comment by Keno** [comment]
No, but it's only been one business day since I posted that, and some of these folks might not work weekend ;).

**Comment by yuyichao** [comment]
Any news a week later now?

**Comment by Keno** [comment]
Yes, for some reason I'm not getting email notifications on these anymore though.

**Comment by tkelman** [comment]
I had the same happen on phabricator, seems flaky

**Comment by Keno** [comment]
1/3 is now nominally upstream. We'll see if it survives the buildbot onslaught.

**Comment by KristofferC** [comment]
Bump, any news?

**Comment by tkelman** [comment]
@Keno what is the status on these?

**Comment by Keno** [comment]
Making its way through review upstream.

**Comment by tkelman** [comment]
Can we rebase this to reflect latest state and get that in before alpha, then add additional incremental patches on top of that as the upstream review continues?

**Comment by tkelman** [comment]
getting the latest state of this in would help make the benchmark resilts much more predictable and useful

**Comment by tkelman** [comment]
@Keno can we please just merge the current state of this patch set now?

**Comment by Keno** [comment]
The latest state of this patch is still very much in flux. We can however, rebase this PR as is and merge it.

**Comment by tkelman** [comment]
one of them was upstreamed, wasn't it? what's closer to what will eventually be upstream, what's in this PR now or the current state of the upstream reviews?

**Comment by StefanKarpinski** [comment]
OS X failure: https://gist.github.com/StefanKarpinski/1663878980f211580b7fb83b93d2e911

**Comment by tkelman** [comment]
been a while since this last ran @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20025#issuecomment-281599300) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ca7142170612358d1c1afea07fcf488a373a975e/6a6ba8a_vs_61a291b/report.md). cc @jrevels

**Comment by StefanKarpinski** [comment]
Dang, that's a lot of performance improvements. Hard to believe LLVM let something this big regress. Oh wait, no it isn't.

**Comment by KristofferC** [comment]
We got the best LLVM hackers don't we?

**Pull request merged**
