### PR TITLE
serialization: fix relocatability bug

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by vtjnash** [comment]
Seems like this is not quite sufficient, since if an external client (e.g GPUCompiler) captures a reference to an CodeInstance, we may segfault later, since only those Method's that are present in new_ext_cis get serialized correctly (for other CI, the relocatability bit is computed wrong during serialization). I am not certain if we need to attempt to make that legal or recompute the bit.

**Comment by maleadt** [comment]
I'm not really familiar with the serializer, so I don't think I'm the best person to review, unless there's a specific GPUCompiler issue you're referring to?

**Comment by vchuravy** [comment]
This is part of the reason why we needed an integrated cache. I can locally backport and validate it against GPUCompiler.

I would like to see some extended tests, maybe added to the external owner precompilation tests.

**Comment by vtjnash** [comment]
I mostly just wanted to tag you so that you are aware of it. It is not strictly required that the caches be integrated for this particular bug, it is just caring about the extending-external list contents right now, and whether the roots are getting saved for it.

**Comment by KristofferC** [comment]
Needs a manual backport.

**Pull request merged**
