### PR TITLE
[deps/libssh2]: fix import library name

### PR DESCRIPTION
**Pull request by inkydragon**
xref issue: https://github.com/JuliaLang/julia/issues/45645#issuecomment-1153214379
import lib should be named `libssh2.dll.a` instead of `liblibssh2.dll.a`.

### CODE REVIEW

**Comment by inkydragon** [comment]
https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases
The static library in releasse also has this problem: 

- [LibSSH2.v1.10.2.x86_64-w64-mingw32.tar.gz](https://github.com/JuliaBinaryWrappers/LibSSH2_jll.jl/releases/download/LibSSH2-v1.10.2%2B0/LibSSH2.v1.10.2.x86_64-w64-mingw32.tar.gz)
```
$ tar -tvf LibSSH2.v1.10.2.x86_64-w64-mingw32.tar.gz
drwxr-xr-x 0/0               0 1970-01-01 08:00 bin
-rwxr-xr-x 0/0          416261 1970-01-01 08:00 bin/libssh2.dll
drwxr-xr-x 0/0               0 1970-01-01 08:00 lib
-rw-r--r-- 0/0          161378 1970-01-01 08:00 lib/liblibssh2.dll.a
```

**Comment by giordano** [comment]
>  static lib should be named libssh2.dll.a instead of liblibssh2.dll.a.

That's ***not*** a static library, but an [import library](https://en.wikipedia.org/w/index.php?title=Library_(computing)&oldid=1091643091#Microsoft_Windows_2).

**Comment by staticfloat** [comment]
Looks good to me!  Do we need to do this in Yggdrasil as well?

**Review by staticfloat — APPROVED** [review]

**Comment by inkydragon** [comment]
> Do we need to do this in Yggdrasil as well?

I think it's good to apply this patch to Yggdrasil.

To avoid breaking libraries that already depend on the name `liblibssh2.dll.a`, perhaps we could also add a hard link (`liblibssh2.dll.a` -> `libssh2.dll.a`)

**Comment by ViralBShah** [comment]
Merge?

**Pull request merged**
