### PR TITLE
distinguish "inlineable" from "declared as inline"

### PR DESCRIPTION
**Pull request by aviatesk**
This commit addresses the current asymmetry in handling `@inline/@noinline` declarations by storing the information in `src::CodeInfo`. `src` now has the `inlining` field that indicates the inlining declaration as follows:

- `src.inlining == 0`: no declaration
- `src.inlining == 1`: declared as `@inline`
- `src.inlining == 2`: declared as `@noinline`

This change is a preparation for an upcoming refactor that will allow for judging inlineability at callsites of `is_inlineable`, while leaving the `inline_cost` function to simply compute the inlining cost without judging inlineability.

Replaces #41922.

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48250) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4125c3a_vs_e40d813/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48250#issuecomment-1380404472) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4125c3a_vs_e40d813/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48250#issuecomment-1380919741) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/b38f071_vs_b07484c/report.md).

**Pull request merged**
