### PR TITLE
rename test/bigint.jl to test/gmp.jl

### PR DESCRIPTION
**Pull request by rfourquet**
For consistency with base/gmp.jl and test/mpfr.jl.

See https://github.com/JuliaLang/julia/pull/29144#issuecomment-420667995.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Need to update `bigint` to `gmp` here: https://github.com/JuliaLang/julia/blob/829a4a665a749efd109ac5dd857b979ec7dd944d/test/choosetests.jl#L43

**Comment by rfourquet** [comment]
Ah yeah thanks, I just realised too!

**Comment by StefanKarpinski** [comment]
I wonder if we shouldn't change in the other direction—use `bigint` and `bigfloat` in base and test.

**Comment by rfourquet** [comment]
> I wonder if we shouldn't change in the other direction—use bigint and bigfloat in base and test.

This makes a lot of sense to me. On the other hand, it's somewhat practical to have the filenames reflect the name of the contained modules.

**Comment by StefanKarpinski** [comment]
> On the other hand, it's somewhat practical to have the filenames reflect the name of the contained modules.

We could change the names of those modules too. If breaking code that reaches into them is a concern, we could just do `const GMP = BigInts` right after the module is defined.

**Comment by JeffBezanson** [comment]
I think we should merge this. If somebody wants to do the renaming the other way (gmp -> bigint) they can, but in the meantime the filenames will be more consistent.

**Comment by rfourquet** [comment]
I realize this was a bit silly of me to add the triage label, I will just merge when CI is green as Jeff suggested.

**Pull request merged**
