### PR TITLE
Fix build_sysimg OSX

### PR DESCRIPTION
**Pull request by dhoegh**
This fix `build_sysimg` on OSX, the solution was proposed in https://groups.google.com/forum/#!topic/julia-users/loQs86WPtVQ. The issue has also been discussed in https://github.com/dhoegh/BuildExecutable.jl/issues/1#issuecomment-148502698. I have confirmed this fixes the issue on Travis OSX but I have not tested i locally as I do not own a Mac.

I have also change the `require` responsible for #14007 to `using`

### CODE REVIEW

**Comment by staticfloat** [comment]
@vtjnash you originally removed these two lines on OSX in https://github.com/JuliaLang/julia/commit/d45e430ceb79562bcd2b7e50566ee2910e257488#diff-aad9ab47160c145b4b5171d33b3064da, can you make sure this change isn't accidentally doing something wrong?

**Comment by vtjnash** [comment]
yes, i removed those intentionally. the linking should be correct now and not require this flag

**Comment by dhoegh** [comment]
When this is not applied Travis fails building sysimg like this: https://travis-ci.org/dhoegh/BuildExecutable.jl/jobs/85558875

**Comment by dhoegh** [comment]
@vtjnash I have created a new branch at: https://github.com/dhoegh/BuildExecutable.jl/pull/3, that displays that OSX fails in linking the sysimg during execution of `build_sysimg.jl`. When the two flags are given it succeeds, see https://github.com/dhoegh/BuildExecutable.jl/pull/2. So somehow the linking is not correct, do you have a better alternative for fixing this issue?

**Comment by vtjnash** [comment]
It looks like it is missing openlibm and the compiler-specific libraries in the linker list. We should probably be calling the compiler (`cc`) instead of `ld`.

**Comment by dhoegh** [comment]
I have tried to use `cc` in https://github.com/dhoegh/BuildExecutable.jl/pull/2 by reverting the changes made here on changing `ld` to `cc`. Now it fails like this: https://travis-ci.org/dhoegh/BuildExecutable.jl/jobs/91867020

**Comment by tkelman** [comment]
`-dylib` should probably be changed to `-shared` when invoking the compiler instead of the linker

**Comment by vtjnash** [comment]
Yes, the flags for darwin should probably be the same as the flags for linux

**Comment by eschnett** [comment]
On OS X, I think you need to use `-dynamiclib` to create a shared library.

**Comment by dhoegh** [comment]
Thank you guys for the help. That fixed the problem in https://github.com/dhoegh/BuildExecutable.jl/pull/2, I will update this PR to reflect the changes we discussed above.

**Comment by dhoegh** [comment]
I have updated the PR and I have checked it works in https://github.com/dhoegh/BuildExecutable.jl/pull/2.

**Comment by tkelman** [comment]
It's not really `find_system_linker` any more, but whatever. Seems good enough to merge as far as I'm concerned. Is the same fix needed on release-0.4?

**Comment by dhoegh** [comment]
>It's not really find_system_linker any more, but whatever. Seems good enough to merge as far as I'm concerned. Is the same fix needed on release-0.4?

I have changed it to `find_system_compiler` and updated the warnings/comments to use compiler. This is also needed on 0.4 to build sysimg on OSX, so a backport would be good.

**Comment by tkelman** [comment]
I think there are some distros that have a `gcc` but not a `cc` alias, but let's see how widely this works.

**Pull request merged**
