### PR TITLE
Use fewer threads on the ccall test on 32bit

### PR DESCRIPTION
**Pull request by gbaraldi**
I'm confused about why we allocate so many stacks here, I was under the impression that the libuv threadpool was 4 threads, but apparently we try and allocate about 1000 stacks here.

This is to make the test a bit more reliable while the whole threadcall thing isn't fixed.

### CODE REVIEW

**Comment by gbaraldi** [comment]
@vtjnash can we merge this so 32 bit doesn't fail so often?

**Comment by vtjnash** [comment]
This does not actually do anything, especially not what the title claims

**Comment by vtjnash** [comment]
The libuv threadpool should be only about 4 threads

**Comment by vtjnash** [comment]
You can see this by counting the number generated after running the test:
```
julia> Threads.maxthreadid()
5
```

**Comment by gbaraldi** [comment]
So this is what puzzled me. It does make a difference, if you add a print statement in the code that allocates stacks this allocates a lot fewer ones. And we don't seem to reuse them.

**Pull request closed without merging**
