### PR TITLE
remove `scalarmin`, `scalarmax`, and corresponding deprecations

### PR DESCRIPTION
**Pull request by JeffBezanson**
One of the more tangled deprecations we need to extricate ourselves from.

@KlausC does this look right? I wasn't quite sure what to do with the separate `reducedim_init` definitions for `max` and `scalarmax`.

### CODE REVIEW

**Review by KlausC — COMMENTED** [review]
The code changes consequently replace `scalarmin/max` by `min/max`. As far as I can see, that has been implemented correctly in this PR. I will add a comment to this PR, to explain, why I am not happy with that.

**Comment by KlausC** [comment]
The original surpose of `scalarmin/max` was to prevent comparisons of `AbstractArray` with  `AbstractArray` or other types in the context of reducing maximum and minimum. There was an `"ArgumentError: ordering is not well-defined for arrays"` if you tried that.
IMO that was acceptable and true.

Now if `a isa AbstractArray`and `b isa AbstractArray`, `a` and `b` are comparable by the definition of functions `cmp` (`abstractarrays.jl:1559`) and `isless`.
This relationship is not a total ordering in a mathematical sense, for example `cmp([1,2], [1 2]) == 0`, but not `[1,2] == [1 2]`. That is in contrast to the clear statement about the meaning of `isless` in the doco:

> isless(x, y)
  Test whether x is less than y, according to a canonical total order. Values that are normally
  unordered, such as NaN, are ordered in an arbitrary but consistent fashion. This is the default
  comparison used by sort. Non-numeric types with a canonical total order should implement this
  function. Numeric types only need to implement it if they have special values such as NaN.

Probably I was missing the discussion about introducing `cmp` and `isless` for arrays and I can get a hint to that?
At least comparison between array and other types is not possible now. It leads to an `MethodError: no method matching isless`.

**Comment by JeffBezanson** [comment]
Good point; I think `isless` should either (1) only be defined for vectors, or (2) somehow take the shape into account.

**Comment by KlausC** [comment]
I started this discourse: [meaning of isless ...](https://discourse.julialang.org/t/meaning-of-isless-cmp-isequal-total-order-partial-order-unordered/8176) about the subject.

**Pull request merged**
