### PR TITLE
`fixup-libgfortran.sh`: Use `patchelf` instead of parsing `ldd` output

### PR DESCRIPTION
**Pull request by staticfloat**
This should be less brittle, and even better, work on `musl`

Also ask `$FC` where `libgfortran` lives if we have no dirname

Ask `libgfortran` where to get its libraries, don't rely on recursive dep printing

### CODE REVIEW

**Comment by staticfloat** [comment]
@rana @shabmk As the two users in https://github.com/JuliaCI/julia-buildbot/issues/102 that have expressed interest in musl CI/CD, do builds of this branch locally pass tests for you?  I'm thinking there might be something wrong with our BinaryBuilder libgit2 binaries, seeing as those tests seem to fail immediately with I/O errors.

**Comment by ararslan** [comment]
>  I'm thinking there might be something wrong with our BinaryBuilder libgit2 binaries, seeing as those tests seem to fail immediately with I/O errors.

I don't think our libgit2 has ever worked for musl. See also #28805.

**Comment by rana** [comment]
Moved on without `musl`. Not enough support. Use case was for slim containers. Just using localhost for now. Would be interested in slim container deployment but i don't think there is enough demand for it. Even if it passed CI i would be concerned to deploy with it because of the support tier level.

**Comment by ararslan** [comment]
> do builds of this branch locally pass tests for you?

I tested in a Docker container (Alpine 3.9) and I encountered a total of 9 failures (all from the file testset) and 10 errors (2 in Sockets due to running in Docker). I did get that same I/O error from libgit2 but oddly enough I did not hit #28805.

**Comment by ecsx1** [comment]
This issue was brought to my attention. I compiled this branch on my musl-native system. The I ran the tests.
```
Test Summary:                       |     Pass  Error  Broken     Total
  Overall                           | 38205789      6  327751  38533546
    compiler/inline                 |       26              1        27
    compiler/validation             |       26                       26
    compiler/contextual             |        6                        6
    compiler/irpasses               |       15                       15
    compiler/ssair                  |       23                       23
    compiler/codegen                |      110                      110
    strings/search                  |      580                      580
    unicode/utf8                    |       19                       19
    strings/io                      |    12751                    12751
    worlds                          |       65                       65
    strings/types                   |  2302691                  2302691
    strings/util                    |      453                      453
    keywordargs                     |      138                      138
    char                            |     1528                     1528
    strings/basic                   |    87313                    87313
    intrinsics                      |       47                       47
    triplequote                     |       28                       28
    subtype                         |   337574              8    337582
    compiler/inference              |      711              1       712
    iobuffer                        |      200                      200
    hashing                         |    18762                    18762
    staged                          |       61                       61
    tuple                           |      503                      503
    dict                            |   144351                   144351
    reduce                          |     8490                     8490
    core                            |  8444959              1   8444960
    intfuncs                        |     4434                     4434
    ambiguous                       |       81              2        83
    simdloop                        |      249                      249
    offsetarray                     |      377                      377
    vecelement                      |      533                      533
    reducedim                       |      690                      690
    copy                            |      522                      522
    rational                        |    97541                    97541
    numbers                         |  1578276                  1578276
    fastmath                        |      937                      937
    functional                      |       95                       95
    path                            |      355             12       367
    operators                       |    12930                    12930
    parse                           |    16591                    16591
    abstractarray                   |     2790                     2790
    math                            |  1519660                  1519660
    loading                         |   153678                   153678
    iterators                       |    10036                    10036
    backtrace                       |       35              1        36
    gmp                             |     2177                     2177
    exceptions                      |       60                       60
    spawn                           |      175              4       179
    version                         |     2448                     2448
    file                            |     1025                     1025
    namedtuple                      |      177              1       178
    read                            |     3089                     3089
    arrayops                        |     1865              2      1867
    floatapprox                     |       49                       49
    mpfr                            |      944                      944
    ccall                           |     5297                     5297
    regex                           |       91                       91
    combinatorics                   |       98                       98
    sysinfo                         |        2                        2
    env                             |       59                       59
    reflection                      |      405                      405
    float16                         |      130                      130
    mod2pi                          |       80                       80
    euler                           |       12                       12
    sorting                         |     4957                     4957
    client                          |        3                        3
    rounding                        |   112720                   112720
    complex                         |     8392              2      8394
    goto                            |       19                       19
    llvmcall                        |       16                       16
    llvmcall2                       |        6                        6
    ryu                             |    31206                    31206
    errorshow                       |      189                      189
    some                            |       64                       64
    meta                            |       55                       55
    stacktraces                     |       48                       48
    docs                            |      213                      213
    enums                           |       90                       90
    sets                            |     3336              1      3337
    misc                            |  1280961                  1280961
    int                             |   524596                   524596
    interpreter                     |        3                        3
    subarray                        |      281                      281
    show                            |     1363                     1363
    bitset                          |      192                      192
    error                           |       31                       31
    checked                         |     1219                     1219
    osutils                         |       42                       42
    cartesian                       |       21                       21
    ranges                          | 12108447         327689  12436136
    iostream                        |       32                       32
    specificity                     |      175                      175
    boundscheck                     |                          No tests
    secretbuffer                    |       17                       17
    floatfuncs                      |      134                      134
    syntax                          |      669              3       672
    logging                         |      212                      212
    asyncmap                        |      292                      292
    channels                        |      211                      211
    broadcast                       |      438                      438
    atexit                          |       40                       40
    reinterpretarray                |      130                      130
    missing                         |      466              1       467
    Pkg/resolve                     |      182                      182
    bitarray                        |   912726                   912726
    cmdlineargs                     |      224                      224
    LinearAlgebra/qr                |     3746                     3746
    SparseArrays/higherorderfns     |     7096              1      7097
    LinearAlgebra/schur             |      390                      390
    LinearAlgebra/eigen             |      410                      410
    LinearAlgebra/bunchkaufman      |     5285                     5285
    LinearAlgebra/dense             |     7870                     7870
    LinearAlgebra/lapack            |      800                      800
    LinearAlgebra/special           |     2863                     2863
    LinearAlgebra/svd               |      501                      501
    SparseArrays/sparsevector       |    10284                    10284
    LinearAlgebra/tridiag           |     1288                     1288
    LinearAlgebra/matmul            |      968                      968
    SparseArrays/sparse             |     3274                     3274
    LinearAlgebra/cholesky          |     2371                     2371
    LinearAlgebra/symmetric         |     2510                     2510
    LinearAlgebra/generic           |      500                      500
    LinearAlgebra/uniformscaling    |      410                      410
    LinearAlgebra/lu                |     1240                     1240
    LinearAlgebra/blas              |      628                      628
    LinearAlgebra/adjtrans          |      290                      290
    LinearAlgebra/givens            |     1840                     1840
    LinearAlgebra/bidiag            |     3185                     3185
    LinearAlgebra/lq                |     1489                     1489
    LinearAlgebra/pinv              |      288                      288
    LinearAlgebra/hessenberg        |      357                      357
    Dates/query                     |      988                      988
    Dates/adjusters                 |     3147                     3147
    Dates/accessors                 |  7723858                  7723858
    Dates/rounding                  |      296                      296
    Dates/types                     |      213                      213
    Dates/periods                   |      687                      687
    Dates/ranges                    |   349123                   349123
    Dates/conversions               |      160                      160
    Base64                          |     2016                     2016
    CRC32c                          |      664                      664
    Dates/arithmetic                |      325                      325
    LinearAlgebra/structuredbroadcast |      564                      564
    LinearAlgebra/diagonal          |     2429                     2429
    Future                          |                          No tests
    Dates/io                        |      324                      324
    Libdl                           |       64              1        65
    DelimitedFiles                  |       83                       83
    Logging                         |       39                       39
    Markdown                        |      236                      236
    InteractiveUtils                |      110                      110
    Mmap                            |      137                      137
    FileWatching                    |      506                      506
    Printf                          |      743                      743
    Profile                         |       20                       20
    LibGit2/libgit2                 |      645      6       1       652
    Serialization                   |      112                      112
    Sockets                         |      167                      167
    REPL                            |     1028              5      1033
    Random                          |   203134                   203134
    UUIDs                           |       22                       22
    Unicode                         |      752                      752
    Statistics                      |      636                      636
    Test                            |      319             14       333
    LinearAlgebra/triangular        |    33684                    33684
    SHA                             |        1                        1
    SuiteSparse                     |      790                      790
    Distributed                     |                          No tests
    LinearAlgebra/addmul            |     3402                     3402
    precompile                      |      102                      102
    SharedArrays                    |      114                      114
    threads                         |    40306                    40306
    stress                          |      119                      119
    FAILURE
```

**Comment by ecsx1** [comment]
Full long in case it helps
http://sprunge.us/kO4V09

**Comment by maleadt** [comment]
Is it possible this broke something on Aarch64? After rebasing https://github.com/JuliaLang/julia/pull/34326 on master (which includes this PR), [testing](https://build.julialang.org/#/builders/28/builds/7102) failed:

```
WARNING: Error during initialization of module LinearAlgebra:
ErrorException("could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory")
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
WARNING: Error during initialization of module LinearAlgebra:
ErrorException("could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory")
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
WARNING: Error during initialization of module LinearAlgebraWARNING: Error during initialization of module LinearAlgebraWARNING: Error during initialization of module LinearAlgebra:
:
ErrorException(ErrorException(""could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directorycould not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory""))
:
ErrorException("could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory")
WARNING: Error during initialization of module LinearAlgebraWARNING: Error during initialization of module LinearAlgebraWARNING: Error during initialization of module LinearAlgebra:
:
ErrorException(ErrorException(""could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directorycould not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory""))
:
ErrorException("could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory")
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Error: Error during initialization of module CHOLMOD
���   exception =
���    could not load library "libcholmod"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
���     [2] dlopen at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
���     [3] __init__() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
��� @ SuiteSparse.CHOLMOD /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:177
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
��� Warning: a hook from a library to disable threading failed:
���   exception =
���    could not load library "libopenblas"
���    libgfortran.so.4: cannot open shared object file: No such file or directory
���    Stacktrace:
���     [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
���     [2] (::LinearAlgebra.var"#199#200")() at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/LinearAlgebra.jl:448
���     [3] disable_library_threading() at ./initdefs.jl:343
���     [4] handle_msg(::Distributed.JoinPGRPMsg, ::Distributed.MsgHeader, ::Sockets.TCPSocket, ::Sockets.TCPSocket, ::VersionNumber) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:343
���     [5] message_handler_loop(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:173
���     [6] process_tcp_streams(::Sockets.TCPSocket, ::Sockets.TCPSocket, ::Bool) at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:142
���     [7] (::Distributed.var"#97#98"{Sockets.TCPSocket,Sockets.TCPSocket,Bool})() at ./task.jl:358
��� @ Base initdefs.jl:345
ERROR: LoadError: could not load library "libopenblas"
libgfortran.so.4: cannot open shared object file: No such file or directory
Stacktrace:
 [1] set_num_threads at /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/blas.jl:115 [inlined]
 [2] (::var"#44#53")() at /buildworker/worker/tester_linuxaarch64/build/share/julia/test/runtests.jl:72
 [3] cd(::var"#44#53", ::String) at ./file.jl:104
 [4] top-level scope at /buildworker/worker/tester_linuxaarch64/build/share/julia/test/runtests.jl:67
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
in expression starting at /buildworker/worker/tester_linuxaarch64/build/share/julia/test/runtests.jl:67
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 1.5.0-DEV.55
Commit 4f84e226a4 (2020-01-13 09:23 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, thunderxt88)
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] runtests(::Array{String,1}; ncores::Int64, exit_on_error::Bool, seed::Nothing) at ./util.jl:842
 [3] top-level scope at none:3
caused by [exception 1]
failed process: Process(setenv(`/buildworker/worker/tester_linuxaarch64/build/bin/julia -Cnative -J/buildworker/worker/tester_linuxaarch64/build/lib/julia/sys.so -g1 /buildworker/worker/tester_linuxaarch64/build/bin/../share/julia/test/runtests.jl ambiguous compiler/inference compiler/validation compiler/ssair compiler/irpasses compiler/codegen compiler/inline compiler/contextual subarray strings/basic strings/search strings/util strings/io strings/types unicode/utf8 core worlds keywordargs numbers subtype char triplequote intrinsics dict hashing iobuffer staged offsetarray arrayops tuple reduce reducedim abstractarray intfuncs simdloop vecelement rational bitarray copy math fastmath functional iterators operators path ccall parse loading gmp sorting spawn backtrace exceptions file read version namedtuple mpfr broadcast complex floatapprox reflection regex float16 combinatorics sysinfo env rounding ranges mod2pi euler show client errorshow sets goto llvmcall llvmcall2 ryu some meta stacktraces docs misc threads stress enums cmdlineargs int interpreter checked bitset floatfuncs precompile boundscheck error cartesian osutils channels iostream secretbuffer specificity reinterpretarray syntax logging missing asyncmap atexit SparseArrays/higherorderfns SparseArrays/sparse SparseArrays/sparsevector Pkg/resolve LinearAlgebra/triangular LinearAlgebra/qr LinearAlgebra/dense LinearAlgebra/matmul LinearAlgebra/schur LinearAlgebra/special LinearAlgebra/eigen LinearAlgebra/bunchkaufman LinearAlgebra/svd LinearAlgebra/lapack LinearAlgebra/tridiag LinearAlgebra/bidiag LinearAlgebra/diagonal LinearAlgebra/cholesky LinearAlgebra/lu LinearAlgebra/symmetric LinearAlgebra/generic LinearAlgebra/uniformscaling LinearAlgebra/lq LinearAlgebra/hessenberg LinearAlgebra/blas LinearAlgebra/adjtrans LinearAlgebra/pinv LinearAlgebra/givens LinearAlgebra/structuredbroadcast LinearAlgebra/addmul LibGit2/libgit2 Dates/accessors Dates/adjusters Dates/query Dates/periods Dates/ranges Dates/rounding Dates/types Dates/io Dates/arithmetic Dates/conversions Base64 CRC32c DelimitedFiles Distributed FileWatching Future InteractiveUtils Libdl Logging Markdown Mmap Printf Profile REPL Random SHA Serialization SharedArrays Sockets Statistics SuiteSparse Test UUIDs Unicode LibGit2/online download`,["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PWD=/buildworker/worker/tester_linuxaarch64/build", "OPENBLAS_NUM_THREADS=8", "SHLVL=1", "JULIA_CPU_THREADS=6", "OLDPWD=/buildworker", "_=/buildworker/start_worker.sh", "TERM=screen", "HOME=/home/buildworker", "OPENBLAS_MAIN_FREE=1", "HOSTNAME=e5d496518d5b"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] runtests(::Array{String,1}; ncores::Int64, exit_on_error::Bool, seed::Nothing) at ./util.jl:836
 [5] top-level scope at none:3
```

**Pull request merged**
