### PR TITLE
Fix negation for an immutable unit triangular

### PR DESCRIPTION
**Pull request by jishnub**
Fixes
```julia
julia> using FillArrays, LinearAlgebra

julia> U = UnitUpperTriangular(Fill(2,4,4))
4×4 UnitUpperTriangular{Int64, Fill{Int64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}}:
 1  2  2  2
 ⋅  1  2  2
 ⋅  ⋅  1  2
 ⋅  ⋅  ⋅  1

julia> -U
ERROR: ArgumentError: Cannot setindex! to -1 for an AbstractFill with value -2.
Stacktrace:
 [1] setindex!
   @ ~/.julia/packages/FillArrays/oXkMk/src/FillArrays.jl:52 [inlined]
 [2] -(A::UnitUpperTriangular{Int64, Fill{Int64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}})
   @ LinearAlgebra ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/LinearAlgebra/src/triangular.jl:442
 [3] top-level scope
   @ REPL[33]:1
```
After this,
```julia
julia> -U
4×4 UpperTriangular{Int64, Matrix{Int64}}:
 -1  -2  -2  -2
  ⋅  -1  -2  -2
  ⋅   ⋅  -1  -2
  ⋅   ⋅   ⋅  -1
```

### CODE REVIEW

**Comment by mikmoore** [comment]
Wait is this fixed? Your "after" no longer throws an error but each `2` was "negated" to `-4`?

**Comment by jishnub** [comment]
Oops, that was a copying error, thanks for spotting! Updated now.

**Comment by dkarrasch** [comment]
Wouldn't you want to catch that at the `FillArrays.jl` level? Like `-(A::FillArray) = FillArray(-A.val, size(A))` or something?

**Comment by jishnub** [comment]
Perhaps I'm not understanding your suggestion, but this is for the `UnitLowerTriangular`/`UnitUpperrTriangular` case, where the diagonal must be set to `-1` independent of the values in the parent matrix. This requires the new parent to be mutable.

**Comment by dkarrasch** [comment]
Ah, I missed that detail.

**Review by dkarrasch — APPROVED** [review]

**Pull request merged**
