### PR TITLE
Delete absolute paths in gdb bootstrap debugging

### PR DESCRIPTION
**Pull request by timholy**
Ref. https://github.com/JuliaLang/julia/commit/c991a239548f708fe71991929bdcf79e3bf90c29#commitcomment-10963835. CC @ihnorton. (Correct?)

### CODE REVIEW

**Comment by timholy** [comment]
Forgot the `[ci skip]`, so I canceled them manually.

**Comment by tkelman** [comment]
You probably still want the relative path to julia, otherwise you'll just be picking up whatever happens to be on your path (if anything) instead of the build from within the source clone you're working in?

**Comment by timholy** [comment]
@tkelman, good point.

**Comment by tkelman** [comment]
though the `.../usr/bin/julia-debug` looks like a typo, 3 leading dots instead of 2?

**Pull request closed without merging**
