### PR TITLE
@cfunction: swap argument names for at, rt

### PR DESCRIPTION
**Pull request by pemryan**
swap at (types of arguments) and rt (return value type).

### CODE REVIEW

**Comment by vchuravy** [comment]
Why? I am afraid we can't make this change because it changes an exported API.

**Comment by fredrikekre** [comment]
> Why? I am afraid we can't make this change because it changes an exported API.

This is just changing the argument names.

**Comment by ararslan** [comment]
Yeah as it stands the argument names are backwards from how the macro is documented.

**Comment by vchuravy** [comment]
Nevermind me then

**Comment by swissr** [comment]
Very confusing atm when looking at this method.

**Pull request merged**
