### PR TITLE
Fix compilation on LLVM 4.0

### PR DESCRIPTION
**Pull request by yuyichao**
Ref https://github.com/llvm-mirror/llvm/commit/a5479197371e169bc676e0e570f2a994329f8773

There's still an assertion we are hitting.

### CODE REVIEW

**Comment by yuyichao** [comment]
AFAICT the assertion is caused by https://github.com/llvm-mirror/llvm/commit/b73e1558ac8255d5df48d6d200ac6a5a20c968fd

**Comment by yuyichao** [comment]
TBAA assertion should also be fixed. Compilation passes locally on linux x64, LLVM 3.3/3.7/3.9/SVN.

This might be something the LLVM autoupgrade should be able to handle?

**Comment by seokj567** [comment]
Compilation passes on my mac (Darwin Kernel Version 16.1.0 xnu-3789.21.3~60/RELEASE_X86_64 x86_64) with Xcode's clang (Apple LLVM version 8.0.0 (clang-800.0.42.1)), LLVM master branch.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19380#issuecomment-262354284) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/cbaeffae6754b011f982744416791c5c1342a8e5/5fa875e_vs_2a4b68a/report.md). cc @jrevels

**Comment by MatthiasJReisinger** [comment]
@yuyichao I had a [local fix](https://github.com/MatthiasJReisinger/julia/commit/0368f40824a60c020fd3b36440ad342d0e70c16d) that uses the auto-upgrade functionality based on [this hint](https://groups.google.com/d/msg/llvm-dev/0fmKPg10wS8/Ov0-pt2NCwAJ) at the llvm dev mailing list, because I could not find reliable documentation on the new tbaa api and did not want to destroy anything. maybe this is something you can use here.

**Comment by yuyichao** [comment]
As I mentioned on [discourse](https://discourse.julialang.org/t/llvm-upstream-dropped-scalar-tbaa-tags-support/503/4?u=yuyichao), I don't think that's the right way to do it.

1. I don't see why we shouldn't create the right TBAA node directly.
2. The change is very different from the change mentioned on llvm-dev. In particular, by calling the upgrade function on the creator and not all the uses, the parent node becomes the struct type node and not the scalar node, which is what the asm parser does and also what this PR (copied from clang) does.

    This also means that the root node should not be "upgraded". It's also where the complexity of the change here comes from. It's trivial to do the equivalent of `UpgradeTBAANode` without calling it but it's none trivial to get the correct DAG since that requires returning two values, one for use in `setMetadata` and one for use as parent node.

**Pull request merged**
