### PR TITLE
allow 24:00 DateTime

### LINKED ISSUE #28203: DateTime hour=24
Hi, I'm using julia to read data files with hourly observations. These also include data at midnight, recorded as 24:00 rather than 00:00. This gives an error upon reading, for example:

DateTime("2018-01-01 24:00","yyyy-mm-dd HH:MM")
ERROR: ArgumentError: Hour: 24 out of range (0:23)

It might be good to make an exception for 24:00, changing to 00:00 the next day, but I'm not sure how/where to change this. (I have little experience with julia so far). Thanks for advice!

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #28203.

### CODE REVIEW

**Comment by quinnj** [comment]
The original discourse thread mentioned something about how, for example, `2018-01-01 24:00:00` would actually refer to `2018-01-02 00:00:00`; should that be the case here? i.e. do `day + 1` if the hour is 24?

**Comment by stevengj** [comment]
That’s what it does. See the tests.

**Comment by Liozou** [comment]
CI is unhappy because of https://github.com/JuliaLang/julia/blob/ce9bc6c08d6be9df76e9242d44837fa2e3460550/stdlib/Dates/test/types.jl#L157 and https://github.com/JuliaLang/julia/blob/ce9bc6c08d6be9df76e9242d44837fa2e3460550/stdlib/Dates/test/io.jl#L34

**Comment by stevengj** [comment]
@Liozou, fixed.

**Pull request merged**
