### PR TITLE
remove unused `roottask` constant

### PR DESCRIPTION
**Pull request by JeffBezanson**
This doesn't seem to be used anywhere and must be quite obsolete.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Removing an unused variable breaks everything. Classic :joy: 

It looks like the system image writer is depending on there being a reference to this; will fix it.

**Comment by vtjnash** [comment]
LOL, this would have made #31948 easier. I was wondering where that reference was popping up from. You could now just drop all references to `root_task` inside that file (unless you want to continue supporting packages creating references to it). I suppose you have to add a test now too to make sure it keeps working, since it's no longer implicitly tested by the sysimg build?

**Comment by mkitti** [comment]
In JavaCall.jl, we use the `roottask` constant to detect if the code is running on the root task. Is there a better way?

https://github.com/JuliaInterop/JavaCall.jl/blob/81029b7220803d743bf966a059f8981973cfad3c/src/jvm.jl#L230

**Comment by StefanKarpinski** [comment]
@vtjnash: is there an answer to @mkitti's question?

**Comment by mkitti** [comment]
As long as we are not removing `Base.roottask`, we should be able to get by at the moment.

I suggested in https://github.com/JuliaLang/julia/pull/35726 that the API should be a method, `Base.root_task()` that parallels `Base.current_task()`, which would allow some flexibility in the future. We could change the underlying implementation of the method if needed. An alternative is to implement `Base.isroottask( task = Base.current_task() )`.

There's some concern that the concept of a root `Task` is an implementation detail that should not be relied upon. However, with the current implementation there is a practical need to identify the root `Task` for interoperability with other software such as the Java Virtual Machine. This also arose in https://github.com/JuliaLang/julia/pull/36064. Should the concept of a root `Task` become obsolete, one could just make `Base.root_task()` an alias for `Base.current_task()` or have `Base.isroottask() = true`.

**Comment by Keno** [comment]
I just ran into this also. Having this magic object that needs special magic in the serializer is very unfortunate. We should get rid of it if we can.

**Comment by mkitti** [comment]
> I just ran into this also. Having this magic object that needs special magic in the serializer is very unfortunate. We should get rid of it if we can.

We just need a way to detect if the current task is the root task to prevent JavaCall.jl from crashing Julia.

The following would be sufficient if `jl_get_root_task` always existed.
```julia
function is_root_task(task = current_task())
    task == ccall(:jl_get_root_task, Ref{Task}, ())
end
```

That depends on `jl_get_root_task` always existing:
https://github.com/JuliaLang/julia/blob/107901d09a847eb43c0cde923861b01f969b428d/src/task.c#L753-L757
`jl_get_root_task` is currently only defined if `JL_HAVE_ASYNCIFY`.

**Pull request closed without merging**
