### PR TITLE
Correct documentation on how a for loop it translated.

### PR DESCRIPTION
**Pull request by ndinsmore**
Corrects the documentation to reflect how a for loop is translated

### CODE REVIEW

**Comment by ndinsmore** [comment]
As this is just a doc change is there a way to kill all the builds?

**Comment by JeffBezanson** [comment]
I don't think this is an improvement. The purpose of this is to show how `iterate` works, which the original shows more clearly.

**Comment by Keno** [comment]
Agreed, this is an introductory part of the docs and while users can be expected to be familiar with destructuring syntax, we should not expect them to know what `Core.getfield` does.

**Comment by ndinsmore** [comment]
I can agree with that on from the point of view of explaining `iterate`.   
That said so there be a section of the documentation that goes into a bit more detail on loops and `iterate`.  I know there is the flow control section, but that doesn't seem like the place for a more in-depth description.

**Comment by Keno** [comment]
The devdocs would be the right place for that. It might make sense to have a devdocs session documenting the exact lowering for various syntax forms.

**Comment by mbauman** [comment]
We could say "is effectively translated to" instead of "is translated to" in the section immediately above this code.

**Comment by JeffBezanson** [comment]
Yes, devdocs seems like the right place, but I don't think it's realistic to document the *exact* lowering of everything; that would be almost as long as the implementation itself. Rather I think we can document various aspects of lowering, like what each pass does and what its few intermediate forms mean.

**Comment by JeffBezanson** [comment]
Also it's worth pointing out that the lowering of something can't be accurately represented as julia surface syntax, since lowering has forms that don't have surface syntax. E.g. in this case we use a form called `_do_while` that has no syntax, and there are many other examples like ssavalues etc.

**Comment by ndinsmore** [comment]
I would think that there are only a few forms that a loop based around `iterate` can reasonably take and still be performant... currently.

Would it be worthwhile to mention those in the devdocs and maybe the performance section?

**Pull request closed without merging**
