### PR TITLE
RFC: rename `trace` to `tr`

### PR DESCRIPTION
**Pull request by JeffBezanson**
In math this is always written as `tr(A)`, and `trace` could potentially mean other things.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I have never seen it written as `tr` in math. It is a pretty standard name, and I have always seen it as `trace`. More so, I don't think we should be taking up 2 letter names like this.

**Comment by JeffBezanson** [comment]
See https://en.wikipedia.org/wiki/Trace_(linear_algebra). `tr` for days.

**Comment by mbauman** [comment]
It also helps that this is now behind a `using LinearAlgebra` in order to bring it into your namespace.  I think it's totally ok for `LinearAlgebra` to export a two-letter function like this.  Base would be a much tougher sell, I agree.

**Comment by ViralBShah** [comment]
I still feel that being in Stdlib is special. And something like LinearAlgebra will be widely used.

**Comment by innerlee** [comment]
I support `tr`. The math books (maybe old books) I used use `tr`. Until recently, I noticed that engineering books like the verbose `trace`. It is understandable because the target audience is different.

**Comment by GlenHertz** [comment]
Functions should have long verbose names so users variables can have short names. Otherwise people will write ` t = tr(a)` and it will not be obvious what it does. If people want they can ` tr = trace` themselves.

**Review by fredrikekre — APPROVED** [review]

**Comment by strickek** [comment]
SciPy and Matlab also use "trace". And it is short, so why change it?

**Comment by antoine-levitt** [comment]
There are already two letter names (qr, lu) and abbreviations (det, inv). tr for trace is very standard (I haven't ever seen trace written down in full)

**Comment by haampie** [comment]
Wolfram Language also uses`Tr`

**Comment by KristofferC** [comment]
Googling on images for `trace matrix math` and counting I got 18 `tr` and 4 `trace`.

**Comment by vtjnash** [comment]
`tr` seems a bit less common, so it's harder for someone to google than `trace`, but it does seem to go right along with the glorious tradition of using truncated names (I'm looking at you "sine"): `cos`, `atan`, `exp`, `det`, `log`, `log1p`, `sqrt`, `pow`, `mul`, `hypot`, etc.

**Comment by ajkeller34** [comment]
In physics, I rarely if ever see `trace` written out in full; almost always I see `tr`. The context makes it clear though. If `tr` lived in Base I'd be against this change, but if it lived in LinearAlgebra I think it'd be fine.

**Comment by Keno** [comment]
No love for https://en.wikipedia.org/wiki/Tr_(Unix)?

**Comment by StefanKarpinski** [comment]
I've only ever seen the mathematical trace operator written in equations as `tr(A)`. In prose it's referred to as "the trace" but as an operator this is called `tr` so I'm in favor of changing it.

**Comment by GlenHertz** [comment]
I can foresee tr being in an html package (table row), tr is also a common Unix command, Total Return in finances, etc. Someone doing financial stuff may want to generate html reports and use linear algebra. If Julia is general purpose then to gain the full benefits of multi-dispatch shouldn't function names be long enough so people can combine packages and still be able to write generic code? Maybe this is better now but in the past it was problematic. Please consider other factors than popularity and people what don't have word auto-complete in there text editor.

**Comment by DNF2** [comment]
I agree with @GlenHertz here (except I don't like verbosity in general). It is nice to write
```
tr = trace(A)
```
While `tr` is common in mathematics, where the context is always totally obvious, `trace` is common in programming languages.

It's even monosyllabic.

**Review by fredrikekre — APPROVED** [review]

**Comment by antoine-levitt** [comment]
> It is nice to write
tr = trace(A)

It's the same argument for det & co. I usually write `detA = det(A)`.

> I think in this case trace is perfectly clear and not without precedent. What else could trace(::AbstractMatrix) mean?

In Julia there is at least https://github.com/MikeInnes/Traceur.jl (although in macro form). Trace in non-numerical programming languages usually means to examine the execution of a command, e.g. strace, dtrace, python's trace, etc.

**Comment by andyferris** [comment]
Personally I find `trace` more readable - I like to consider that people (eg at work) who aren’t mathematicians will read my code and have enough breadcrumbs to figure out what it means. `tr` wouldn’t Google well (though there is the docsting, I guess).

**Comment by JeffBezanson** [comment]
I think readability by non-mathematicians is not a real requirement --- `tr` is the standard notation, like `sin`, `cos`, and `det`.

**Comment by StefanKarpinski** [comment]
This seems to me to be *exactly* the same situation as the determinant which is _always_, _always_, _always_ written as `det(A)` in math textbooks; similarly `tr(A)` is _always_ how the trace of `A` is written.

**Comment by StefanKarpinski** [comment]
Evidence: just look through this google image search (courtesy of @mbauman):

https://www.google.com/search?tbm=isch&q=linear%20algebra%20trace&tbs=imgo:1

**Review by fredrikekre — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
This one's for @fredrikekre!

**Comment by JeffBezanson** [comment]
Ok, looks like the "aye"s have it.

**Pull request merged**
