### PR TITLE
Set VERSION to 0.7.0-rc1

### PR DESCRIPTION
**Pull request by ararslan**
The following need to be merged first:

- [x] #26991
- [x] #27944
- [x] #28287
- [x] #28296
- [x] #28302
- [x] #28304
- [x] #28309
- [x] #28314
- [x] #28332
- [x] #28334
- [x] #28362
- [x] #28365
- [x] #28374

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
must be lowercase

**Comment by tknopp** [comment]
What about #13099 ? It solves a real issue, which is a pain to work around in Gtk.jl. Also it seems that PR ist all set.

**Comment by JeffBezanson** [comment]
Yes, we could perhaps merge that now, but I would consider it non-breaking so it's not urgent to get it into any particular version.

**Comment by tknopp** [comment]
But it fixes a bug that persists since 3 years and leads to segfaults: https://github.com/JuliaGraphics/Gtk.jl/issues/161.  So its not like a feature request but a request to solve a bug which makes GUI programming with Gtk much harder than it is for other languages. I have code where the `sigatom` workaround cited in https://github.com/JuliaGraphics/Gtk.jl/issues/161 does not work and in turn cannot proceed.

**Comment by JeffBezanson** [comment]
If everybody is allowed to block the release on a bug of their choosing, there will never be a release. I do want to merge #13099 though. Hopefully we'll be able to merge it by 1.0.x.

**Comment by ararslan** [comment]
Looks like @rfourquet added #27944, which isn't on the milestone nor marked for triage. Yay or nay?

**Comment by rfourquet** [comment]
> Looks like @rfourquet added #27944, which isn't on the milestone nor marked for triage. Yea or nay?

Yes, with a question mark because it was rejected in triage but now Jeff re-opened it. It's a conservative Yea for me, but definitely not crucial (but should be decided before rc1 I think).

**Comment by JeffBezanson** [comment]
#27944 deletes functions that were only added in 0.7, so it's low risk and the concern is avoiding adding an API that we might not want to commit to.

#13099 is non-breaking but involves a complete redesign of the task code, so is quite risky. It seems to work well as far as any of us know, but we all know how that goes.

**Comment by ararslan** [comment]
#28310?

**Comment by maleadt** [comment]
I'd like to add https://github.com/JuliaLang/julia/pull/28291, which is a pretty small bugfix that makes it possible to `@profile` CUDAnative code. Review & approved, CI is green, so good to go but nonetheless putting it here for consideration.

**Comment by ararslan** [comment]
Somehow that checklist seems to keep getting longer... 😉

**Comment by StefanKarpinski** [comment]
It just got shorter—we're not doing #28193.

**Review by Keno — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]

**Comment by ararslan** [comment]
HERE. WE. GO.

**Pull request merged**
