### PR TITLE
Work around Clang 3.9 not being able to compile OpenBLAS.

### LINKED ISSUE #18619: Julia does not build with clang 3.9
Attempting to build Julia with clang 3.9 leads to a syntax error while building OpenBLAS. The problem is analyzed [here](https://github.com/xianyi/OpenBLAS/issues/942), but without solution or work-around. Julia should either disallow this compiler, or patch OpenBLAS to avoid this problem.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes #18619

### CODE REVIEW

**Comment by tkelman** [comment]
won't this be unnecessary as soon as there's an openblas release that includes 3705f5675ae45f3cc662927db1955701cf73d95b ?
did the fix for the clang bug make it into 3.9.1?

**Comment by maleadt** [comment]
This is using 3.9.1, so apparently not. And I haven't tested the OpenBLAS fix (I presume it would work), but that won't be part of 0.6, will it? And that would mean 0.6 is not testable using ASAN (because one typically builds a fully-compatible LLVM toolchain using the Julia Makefiles, currently ending up with a broken Clang 3.9.1, using which it is impossible to subsequently compile Julia).

I'd prefer to have this workaround part of 0.6, and remove it as soon as OpenBLAS is fixed and the dep is upgraded.

**Comment by tkelman** [comment]
or if the problem is with a self built clang, then we can carry the patch to clang that fixed the issue. let's not add in poorly tested non default compiler flags that change build products in the default configuration (did you test this in a clean build on mac?) to fix bugs that only hit exotic build configurations, **and** have multiple better fixes available.

**Comment by maleadt** [comment]
... so far for getting the ASAN build-bot working again ...

So you'd rather carry a hacky patch to openblas, or backport an unreleased patch to Clang, rather than selectively (only openblas, only clang) enable a compiler option? I wouldn't call either of those alternatives 'better' in any way. `-no-integrated-as` has been documented in the LLVM and Clang release notes as early as 3.5, and was the default assembler before that. And while I did encounter this mainly when building using a bootstrapped ASAN toolchain, it also prevents me from building on Arch which ships Clang 3.9.1. Not really 'exotic', I'd say.

Oh well, revert as you please. This isn't worth my time anyway.

**Comment by tkelman** [comment]
We don't recommend building Julia with clang on Linux, it's certainly not default. It is default on mac though, and unless you've shown this flag has no noticeable impact there, either an openblas patch or a clang patch to fix the specific problem rather than changing the way all assembly in openblas is getting compiled would be preferable.

**Comment by tkelman** [comment]
what makes you call the openblas patch hacky? it's just changing the format of assembly comments.

**Comment by tkelman** [comment]
and yes, this does break the mac build https://build.julialang.org/builders/build_osx10.9-x64/builds/2775/steps/shell_1/logs/stdio

**Pull request merged**
