### PR TITLE
update utf8proc, replace wcwidth

### PR DESCRIPTION
**Pull request by stevengj**
This updates utf8proc to version 1.2 (#10654) and replaces calls to the often-outdated `wcwidth` with `utf8proc_charwidth` (#3721 and #6939).

(It seemed simpler to leave it as a submodule and just rename it from libmojibake back to utf8proc.)

Note that `USE_SYSTEM_UTF8PROC=1` will no longer work unless the system has utf8proc 1.2 or later (cc @nalimilan).

The patch also uses the new function `utf8proc_category` to get the category code rather than looking inside the `utf8proc_property_t` struct (which assumed that the category is the first 16-bit field).

### CODE REVIEW

**Comment by tkelman** [comment]
For AppVeyor, will need to do `s/mojibake/utf8proc/g` in `contrib/windows/msys_build.sh`

**Comment by stevengj** [comment]
Thanks @tkelman, just pushed a fixed commit.

**Comment by tkelman** [comment]
Looks like `wcwidth` is also used in flisp. And the undefined symbols issue with `__imp` is probably related to the conflicting definitions of `DLLEXPORT`. Maybe `#undef DLLEXPORT` after including `dtypes.h` but before including `uft8proc.h`.

**Comment by stevengj** [comment]
I don't really understand why the Makefile for flisp used the `-DUTF8PROC_EXPORT` flag; shouldn't this only be used when compiling utf8proc (so that it adds the `dllexport` decorator)?   Is it because we're going to link utf8proc and flisp into the same library in the end?    In that case, I guess we now need `-DUTF8PROC_EXPORT` when compiling libsupport (since that now calls `utf8proc_charwidth`).

**Comment by tkelman** [comment]
We only build the static library of utf8proc, but we link that static library into the shared libjulia. We want the shared libjulia to export these utf8proc symbols. At least I'm pretty sure that's how it works. MSVC is pickier than MinGW in these matters, but I can worry about that later.

**Comment by nalimilan** [comment]
Why don't we link dynamically to utf8proc?

**Comment by stevengj** [comment]
@nalimilan, because it is a dependency of libjulia, not just of Base, utf8proc has to be included in libjulia itself (to avoid inter-library dependencies, which are problematic in general and especially problematic on Windows).

**Comment by tkelman** [comment]
Libjulia already has dll dependencies, namely libgcc and libstdc++. It's really not so bad on Windows, you just can't have undefined references and the dependencies have to be specified at link time. And the dll dependencies need to be available either in the same folder as the binary or on the path somewhere (I prefer the former).

**Comment by nalimilan** [comment]
OK, you know what you're doing. :-)

**Comment by stevengj** [comment]
(Yes, but this means that on Windows it's quite hard to `dlopen` a library with dependencies on another library ... the contortions that numpy goes through to be openable dynamically and yet still callable from other Python modules that are loaded dynamically are quite atrocious.)

**Comment by tkelman** [comment]
We dlopen (via ccall in JuliaOpt packages) the entire COIN-OR stack which is a big complicated interdependent set of shared libraries just fine. It occasionally requires some patching to make sure the dependencies are linked properly at build time, but that's not so bad. I have no idea what numpy is doing wrong there, but it's not so hard to do right. Numpy is just such a rat's nest that no one wants to touch it (I apparently managed to talk Travis Oliphant out of wanting to interview me for that job by being too honest about how uninteresting it would be to work on fixing Python's Windows problems...).

**Comment by stevengj** [comment]
Arg, now appveyor is succeeding, but one of the Travis jobs timed out; possibly unrelated?

**Comment by tkelman** [comment]
Yeah, was on osx so most likely. There have been some efforts to optimize the tests a little recently, but apparently didn't get all the way to reliably finishing in time.

**Comment by stevengj** [comment]
Argh, one of the appveyor builds is failing now, too.  All I did was push a NEWS update; another timeout?

**Comment by tkelman** [comment]
> another timeout?

Yeah, froze at linalg1 only on 64 bit, that's been a long-standing intermittent mystery.

**Comment by stevengj** [comment]
So, is this mergeable?

**Comment by tkelman** [comment]
I think so, may as well.

**Pull request merged**
