### PR TITLE
Extend definition of StridedReshapedArray

### LINKED ISSUE #22411: Dispatch problems when reshaping a SubArray
The following performance issue is present on master (as well as v0.6.0-rc3 and v0.5.2):

```
using BenchmarkTools
f1(A, B) = A*B
f2(A, B) = reshape(view(A, :, :), size(A))*B

N = 100
A = rand(N, N) 
B = rand(N, N)
@btime f1($A, $B)
@btime f2($A, $B)
```

gives

```
73.563 μs (2 allocations: 78.20 KiB)
1.510 ms (10 allocations: 78.61 KiB)
```

This occurs because a `ReshapedArray{T,N,P<:SubArray,MI}` is currently not considered a `StridedArray`:
```
julia> typeof(reshape(view(A, :, :), size(A))) <: StridedArray
false
```
so generic matrix multiplication is called instead of BLAS.

Extending the definition of `Base.StridedReshapedArray` from                     
```
StridedReshapedArray{T,N,A<:DenseArray} = ReshapedArray{T,N,A}
```
to
```
StridedReshapedArray{T,N,A<:Union{DenseArray,SubArray}} = ReshapedArray{T,N,A}
```
appears to fix this (I can create a pull request if that seems reasonable to the experts, I'm not sure if that new definition could have some unintended consequences).

For posterity:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.635
Commit e2ef50f7c8 (2017-06-17 21:49 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
Environment:
  JULIAPATH = /Users/mfishman/workdir/julia
```

### PR DESCRIPTION
**Pull request by mtfishman**
Fixes #22411

### CODE REVIEW

**Review by timholy — APPROVED** [review]

**Comment by tkelman** [comment]
Add a test for something that this fixes?

**Comment by ararslan** [comment]
Not sure how one could test this, since it's just making sure that certain array types go through a different path in dispatch that improves performance, right?

**Comment by mtfishman** [comment]
A test could be something like:
```
A = rand(5, 5)
@test typeof(reshape(view(A, :, :), size(A))) <: StridedArray
```

**Comment by ararslan** [comment]
Okay great, if you'd be willing to add that as a test, that'd be awesome. In the meantime, the current test failures here are unrelated.

As an aside, rather than `typeof(x) <: T`, you can do `x isa T` (or `isa(x, T)` if you prefer).

**Comment by mtfishman** [comment]
Also this should be backported to 0.5 and 0.6.

**Comment by StefanKarpinski** [comment]
Definitely squash when merging.

**Pull request merged**
