### PR TITLE
Make `LinearAlgebra.haszero` public

### PR DESCRIPTION
**Pull request by jishnub**
The trait `haszero` is used to check if a type `T` has a unique zero defined using `zero(T)`. This lets us dispatch to optimized paths without losing generality. This PR makes the function public so that this may be extended by packages (such as `StaticArrays`).

### CODE REVIEW

**Comment by nsajko** [comment]
Presumably the doc string should be included into:

https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/docs/src/index.md

**Comment by jishnub** [comment]
I'm unsure where it features according to the current structure. We may think of adding a section in the future to include such auxiliary functions.

**Comment by fredrikekre** [comment]
This doesn't feel like a LinearAlgebra function so perhaps it should be in Base instead?

**Comment by jishnub** [comment]
It could be. Currently, the main application is for structured matrices, but I imagine something like this might be useful in general.

**Pull request merged**
