### PR TITLE
Re-enable running tests with multiple processes on Win64

### PR DESCRIPTION
**Pull request by yuyichao**
Since #7942 should be fixed now.

Somehow I'm getting errors from LLVM headers that seems totally unrelated. The build also takes much longer to download at the beginning.

@tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
Not sure what's wrong yet, but it appears to be related to how we have the compiler download cached on appveyor - you're supposed to get a `Restoring "x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z"...OK` right at the beginning so we can avoid downloading from slow unreliable sourceforge on every build, but the cache might be branch-by-branch or something strange like that?

**Comment by yuyichao** [comment]
> but the cache might be branch-by-branch or something strange like that?

That's also my guess and the only possible explaination I have at this point is that the cache is hashed by the environment setup...

**Comment by yuyichao** [comment]
@tkelman FWIW, I see the following error on all master builds and not on any PR's. Is this expected / related?

On 32bit

```
Updating build cache
Cache entry not found: C:\projects\julia\x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z
Cache entry not found: C:\projects\julia\llvm-3.3-x86_64-w64-mingw32-juliadeps.7z
```

On 64bit

```
Updating build cache
Cache entry not found: C:\projects\julia\i686-4.9.2-release-win32-sjlj-rt_v4-rev3.7z
Cache entry not found: C:\projects\julia\llvm-3.3-i686-w64-mingw32-juliadeps.7z
```

**Comment by tkelman** [comment]
That's expected, it just means it doesn't have the opposite bitness downloaded files - so far it hasn't been an issue?

**Comment by yuyichao** [comment]
> so we can avoid downloading from slow unreliable sourceforge on every build

Do we not have any more reliable download sources? (after github removes the download page)

**Comment by tkelman** [comment]
I just moved a bunch of things to bintray. And we have our caching server which goes to s3. I can copy the relevant downloads over to bintray and adjust the url's, if you don't mind me pushing to this branch?

**Comment by yuyichao** [comment]
> if you don't mind me pushing to this branch?

Go ahead! That's the point of using a branch here. =)

**Comment by yuyichao** [comment]
The download address change doesn't seem to help =(.

**Comment by tkelman** [comment]
cache of llvm might be stale for this branch https://github.com/JuliaLang/julia/commit/5db431161796c9479098abcf31195307efcba1cd

**Comment by tkelman** [comment]
Not sure whether that'll fix it, but apologies in retrospect for not versioning these binary filenames when I had to rebuild them for ABI changes.

**Comment by yuyichao** [comment]
> Not sure whether that'll fix it, but apologies in retrospect for not versioning these binary filenames when I had to rebuild them for ABI changes.

No need to apologize since you are the only one who will deal with these. ;-p

**Comment by yuyichao** [comment]
Yay, the compilation passes!

**Comment by tkelman** [comment]
Yeah, was just a stale cache for whatever reason - had you used this branch name before maybe? So switching from sourceforge to bintray wasn't strictly necessary, but the downloads should be faster and more reliable now.

**Comment by yuyichao** [comment]
> had you used this branch name before maybe?

I think it's not because of the branch name since it appears on three of my branches `yyc/appveyor-test`, `yyc/appveyor-freeze` and this one `yyc/windows-test` two of which are new (this one and `yyc/appveyor-freeze`) and one has worked before on very recent master `yyc/appveyor-test` and `yyc/appveyor-freeze`.

Other new branches/PR's also don't have issue using the cache and this issue only appears for whatever commits not having the cpu cores setting, which is why I think it is indexed by the environment settings.

**Comment by tkelman** [comment]
Ah, the most recent time we ran appveyor without `JULIA_CPU_CORES: 1` was probably with a previous version of the llvm binaries that had a different ABI. So deleting `JULIA_CPU_CORES: 1` went back to that stale cached copy of the binaries. I guess that makes sense.

**Comment by yuyichao** [comment]
Yeah, that makes perfect sense than (I was actually wondering why it has something in the cache if it was a new setting and had never finished the build to get a change to update the cache yet....)

I vote for either add checksum or version the filename then....

**Comment by tkelman** [comment]
> add checksum

We can totally do that. We have the technology.

**Comment by yuyichao** [comment]
Hmmm, did I miss sth or is the cache not updated somehow?

https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.7095/job/74o9m5aew7cml52m#L32

**Comment by tkelman** [comment]
I think the cache only gets updated for branch builds, not pr builds. I could be wrong there.

**Comment by yuyichao** [comment]
Makes sense then. I guess this is also why I don't see the cache update error for other PR builds.

So this actually tests that my non-locally-tested code works for both cases? LOL. Should be good to merge then after AppVeyor passes (or if you want to wait for Travis strugling with OSX.....).

**Comment by yuyichao** [comment]
I'm excited now to see if we are free of the AppVeyor hang in the next few days...

**Pull request merged**
