### PR TITLE
WIP/RFH: Make dims a keyword argument to reducing functions

### LINKED ISSUE #25501: Make region a keyword argument for dimension reducing methods
If possible, I think we should make the `region` argument in the dimension reduction methods of `any` and `all` a keyword argument. `map` has an incredibly handy method for multiple iterators, e.g. `map(<, a, b)`. Currently `any(<, a, b)` will use the method `any(f, itr, region)`, but it would be great to be able to reclaim `any(<, a, b)` to do what it looks like it should do. That would require making `region` a keyword argument in 0.7 with a deprecation, and introducing the new method in 1.0.

The downside to this is that we have to come up with a default value for `region` in order to use it as a keyword argument, and when `region` isn't specified then we want it to dispatch to the simpler, short-circuiting method not based on `mapreducedim`.

~~A similar argument could be made for other functions with `mapreducedim`-based methods, such as `sum(f, A, region)`, but I mostly care about `any`/`all` for now.~~ We're doin' 'em all.

### PR DESCRIPTION
**Pull request by ararslan**
_Heavily_ WIP. If you're reading this, you can pretty much ignore this for now.

Still to do:

- [ ] Fix the code
- [ ] Fix the docs
- [ ] Fix the tests
- [ ] Fix inference in global scope
- [ ] Get the other reducers, e.g. `cum(sum|prod)`, `var`, `std`, etc.

Fixes #25501.

### CODE REVIEW

**Comment by ararslan** [comment]
Inference issue, as requested by @JeffBezanson 
```
Error During Test at /home/alex/Projects/julia/test/statistics.jl:198
  Got an exception of type ErrorException outside of a @test
  return type Float64 does not match inferred return type Any
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] macro expansion at /home/alex/Projects/julia/test/statistics.jl:227 [inlined]
   [3] macro expansion at /home/alex/Projects/julia/usr/share/julia/site/v0.7/Test/src/Test.jl:1008 [inlined]
   [4] top-level scope at /home/alex/Projects/julia/test/statistics.jl:199
```

**Comment by JeffBezanson** [comment]
`cumsum` and `cumprod` only accept a single dimension --- should the argument be called `dim` in that case?

**Comment by JeffBezanson** [comment]
Or I guess it could still be called `dims` since we might extend it to multiple dimensions at some point?

**Comment by ararslan** [comment]
The inconsistency with `sum` and `prod` would be kind of weird, in my opinion, especially since you can also pass single dimensions to `sum` and `prod`. I'd call it `dims` across the board, even if it's technically improper English for single dimensions.

**Comment by mbauman** [comment]
Consistency is required for an implementation of `squeeze(f, A, dims=…)` — https://github.com/JuliaLang/julia/pull/23500.

**Pull request closed without merging**
