### PR TITLE
Fix broken links to Pkg.jl documentation

### LINKED ISSUE #53348: Dead link in documentation
On https://docs.julialang.org/en/v1/stdlib/Test/

the link to https://pkgdocs.julialang.org/dev/creating-packages/#Adding-tests-to-the-package does not work. The link has the text "adding tests to your Julia Package"

### PR DESCRIPTION
**Pull request by burtonjosh**
Some dead links in the documentation for v1.10, this points to the most up to date version of the `Pkg.jl` docs

Fixes #53348 

Hopefully I'm requesting to merge to the correct branch, please let me know if I need to change anything!

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can you make this PR to master instead of release-1.10? We'll then mark it for backporting to pull it into 1.10, 1.11, etc. It may be simplest to open a new PR.

**Comment by burtonjosh** [comment]
sure no problem! The issue I ran into was that the same links in master are not broken, since they were updated in this PR #52384 , so I don't know exactly how to change anything in `master` so that `release-1.10` would get updated? Sorry for the confusion.

**Comment by ViralBShah** [comment]
Hmm. @KristofferC Can we merge this PR directly into release-1.10?

**Comment by giordano** [comment]
I think `release-1.10` is the wrong branch, should have targeted the backport branch, and if this PR is just copying another PR then the other PR should be labelled as backport, which also retains authorship.

**Comment by burtonjosh** [comment]
It's not quite a copy of #52384, since in #52102 the page [5. Creating Packages](https://pkgdocs.julialang.org/v1/creating-packages/#Adding-tests-to-the-package) from the `Pkg.jl` documentation has been copied into the official Julia documentation as a tutorial: https://docs.julialang.org/en/v1.11-dev/tutorials/creating-packages/#adding-tests-to-packages . This means the internal referencing with `@ref` can't be used in 1.10, which is why I've had to just update the link directly.

> should have targeted the backport branch

I looked for this but couldn't find anything relevant, is there a specific branch you're referring to?

**Comment by giordano** [comment]
> I looked for this but couldn't find anything relevant, is there a specific branch you're referring to?

[`backport-1.1.0`](https://github.com/JuliaLang/julia/tree/backport-1.1.0)

**Comment by ViralBShah** [comment]
@giordano Did you mean backport-1.10, because your link is to backport-1.1.0 (which is really old).

**Comment by carstenbauer** [comment]
I would assume he meant https://github.com/JuliaLang/julia/tree/backports-release-1.10

**Comment by lgoettgens** [comment]
This PR now somehow seems to contain way too many commits. The only "real" changes are in [`5b38940` (#53374)](https://github.com/JuliaLang/julia/pull/53374/commits/5b38940b985b6aba8a7b2209d3ceb9618d62e68d), the rest seems to be from the https://github.com/JuliaLang/julia/tree/backports-release-1.10 branch.
@KristofferC is this fine to merge like this into the backports branch? If not, @burtonjosh would need to rebase it onto the newest https://github.com/JuliaLang/julia/tree/backports-release-1.10 to get rid of the redundant commits.

**Comment by lgoettgens** [comment]
This shouldn't have been closed. Can someone reopen it again?

**Pull request closed without merging**
