### PR TITLE
Enable FPO again on non-windows

### PR DESCRIPTION
**Pull request by yuyichao**
This was enabled when we were porting to 3.7 for better unwinding.
The unwinding should have been improved (thanks to registering JIT functions to libunwind
and a new libunwind version) on non-windows a lot that we don't need this anymore.

The performance impact of this is likely small but it makes `code_native` for simple functions
quite a bit simpler and has the biggest yet effect on the code size in system image (-4%).

This is the motivation for https://github.com/JuliaLang/julia/pull/24340 ...

### CODE REVIEW

**Comment by oscardssmith** [comment]
What is FPO?

**Comment by yuyichao** [comment]
Frame pointer omission https://github.com/JuliaLang/julia/pull/24341/files#diff-6d4d21428a67320600faf5a1a9f3a16aR4154

**Comment by ararslan** [comment]
The failure on FreeBSD looks related.

**Comment by yuyichao** [comment]
The linux 32bit failure is fixed with the libunwind patch. Anyone interested can try if it works with libunwind master on freebsd but in the mean time this is disabled for windows and freebsd.

**Comment by ararslan** [comment]
It appears to work on FreeBSD with libunwind master. Can we bump the version of libunwind we're using?

**Comment by yuyichao** [comment]
All the patches I've submitted are merged so there are only 1 or 2 patches we need that's not submitted yet and the release the includes the current master would be worth switching to. The currently existing 1.2.x releases are not very different from what we have right now.

**Pull request merged**
