### PR TITLE
make macros generic functions

### LINKED ISSUE #9627: Default values for macros
The following syntax doesn't work for macros (but does for functions):

```jl
julia> macro foo(a, b::Bool=true)
          a, b
       end
ERROR: syntax: "(kw (:: b Bool) #t)" is not a valid function argument name

julia> function foo(a, b::Bool=true)  #works for functions
          a, b
       end
foo (generic function with 2 methods)

julia> foo(1)
(1,true)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Here's another tidbit from jb/functions that's easy to apply to master.

fixes #9627, #8846, and #8701, and might help #3377

### CODE REVIEW

**Comment by quinnj** [comment]
Seems like a first-class kind of solution :sunglasses:

**Comment by StefanKarpinski** [comment]
Love it. Since all the tests pass, should we merge this?

**Comment by mlubin** [comment]
Nice!

**Comment by tkelman** [comment]
If it fixes that many issues, could use a few more test cases couldn't it?

**Comment by mbauman** [comment]
Probably could use a NEWS entry, too.  This is nifty:

```jl
julia> macro foo(x::Int)
           :($x + 1)
       end
@foo (macro with 2 methods)

julia> macro foo(x::Symbol)
         @show x
       end
@foo (macro with 2 methods)

julia> @foo 1
2

julia> @foo show
x = :show
show (generic function with 122 methods)
```

**Comment by timholy** [comment]
Pretty awe-inspiring that this comes with a net reduction of 13 lines of code, and a net churn < 100 lines.

**Comment by tkelman** [comment]
Merging this appears to have introduced a failure on 32 bit appveyor: https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.12336/job/smqeb0ravuyaroa3

**Comment by yuyichao** [comment]
Hmm, I've seen this failure appears on https://github.com/JuliaLang/julia/pull/14541 lin32 for some time and haven't been able to figure out why. I suspect it's related to the IOContext/ImmutableDict and very likely also related to the UndefRefError in dict test and a similar one I've just reproduced repeatedly on ARM.

**Comment by Ismael-VC** [comment]
I understand that this would replace generic functions, am I right?

On generic functions:
> These have the capability to generate specialized code depending on the types of their arguments with more flexibility and/or less code than what can be achieved with multiple dispatch.

**Comment by JeffBezanson** [comment]
No, after this macros are basically the same as they always were. But the implementation is changed so that a bit more flexibility exists, e.g. having separate definitions for cases with different numbers of arguments.

**Comment by iamed2** [comment]
@JeffBezanson but @mbauman's example would suggest that they are not the same as they always were? In that you can now have different implementations for different input types.

**Comment by JeffBezanson** [comment]
Yes, but for the types of the expression objects, not the types of run time values. So the types are almost always just `Expr`.

**Comment by iamed2** [comment]
Ah, understood. Thanks.

**Comment by Ismael-VC** [comment]
> Yes, but for the types of the expression objects, not the types of run time values. So the types are almost always just Expr.

Oh! that makes a lot of sense now, thank you very much!

**Comment by MichaelHatherly** [comment]
Super cool! Unless I've missed something we can't extend a macro without first explicitly importing it, ie.

```julia
module A

macro m(x::Int)
    "an integer"
end

end

# I'd expect this to work as it does for methods
macro A.m(x::Expr)
    "an expression"
end

# but it throws a
#
# ERROR: syntax: invalid macro definition
#  in eval at ./boot.jl:265

# this does work as expected though
import .A: @m
macro m(x::Expr)
    "an expression"
end
```
```
julia> @m 1
"an integer"

julia> @m 1 + 2
"an expression"
```

Would it be too greedy to ask for `macro A.m` syntax as well? :)

**Pull request merged**
