### PR TITLE
wrap tests in anonymous function

### PR DESCRIPTION
**Pull request by KristofferC**
https://github.com/JuliaLang/julia/commit/e9a5117550538537b091b55ae31c23a4c275fe54?w=1 for easier review.

Implements my idea in https://github.com/JuliaLang/julia/issues/18077#issuecomment-251939999 with the code from @maleadt https://github.com/JuliaLang/julia/issues/18077#issuecomment-255215304.

I am not seeing as large improvements as he did in the comment above but at least some:

```jl
# Before:
Test: | Total time (s): | GC time (s): | Percent in gc: | Allocated (MB): | RSS (MB):
math |   27.09         |    0.77      |    2.83        | 1652.87         |  346.46  

# After:
Test: | Total time (s): | GC time (s): | Percent in gc: | Allocated (MB): | RSS (MB):
math |   24.11         |    0.77      |    3.18        | 1631.75         |  329.98  
```

On one of my own packages:
```jl
# Before
100.127960 seconds (139.10 M allocations: 3.634 GB, 1.18% gc time)

# After
 95.142206 seconds (138.52 M allocations: 3.622 GB, 1.17% gc time)
```

Would be interesting to see what Travis says.

### CODE REVIEW

**Comment by yuyichao** [comment]
This changes the test behavior by a lot.

**Comment by KristofferC** [comment]
OK. This was mostly a test to see what would happen.

**Comment by KristofferC** [comment]
For fun I plotted the time for all the test files that passed vs one that recently passed on travis:

**Comment by KristofferC** [comment]
For fun I plotted the time for this PR for each test that passed vs one of a recently passed PR:

y-label is time for recent PR divided by time for current PR (<1 is faster)

image

**Pull request closed without merging**
