### PR TITLE
Test: add durations to testset reports

### LINKED ISSUE #37571: Add timings to verbose test reports
Should #33755 (or an alternative solution to #27088) be merged, it would be nice to also report the results of `@time` on each test set, e.g.

```
Test Summary: | Pass  Total  Duration
Parent        |    9      9  0.301395 seconds (8 allocations: 7.630 MiB)
  Child 1     |    3      3  0.001525 seconds (7 allocations: 336 bytes)
    Child 1.1 |    1      1  ...
    Child 1.2 |    1      1
    Child 1.3 |    1      1
  Child 2     |    3      3
  Child 3     |    3      3
    Child 3.1 |    1      1
    Child 3.2 |    1      1
    Child 3.3 |    1      1
```

Adding `@time` to each test set is quite a common pattern:

* https://juliahub.com/ui/RepoSearch?q=%40time%20%40testset&w=true
* https://github.com/search?l=&p=2&q=%22%5C%40time+%5C%40testset%22+extension%3Ajl&ref=advsearch&type=Code

### PR DESCRIPTION
**Pull request by IanButterworth**
Closes #37571

Adds durations to the testset reports. Can be disabled with `showtiming = false`
```
julia> @testset "FooBar" begin
           @testset "Foo" begin
               sleep(0.1)
               @test true
           end
           @testset "Bar" begin
               sleep(1)
               @test false
           end
           @testset "Baz" begin
               sleep(4)
               @test error()
           end
       end
...
```
Screen Shot 2021-11-28 at 10 31 20 PM

### CODE REVIEW

**Comment by fredrikekre** [comment]
Why not make it default? Who will complain about timings being shown?

**Comment by jonas-schulze** [comment]
Closes #37571

**Comment by thofma** [comment]
Something somewhere needs some tweaking:
```julia
Test Summary:                   | Pass  Total        Duration
GAPGroups_interface_conformance |   67     67  2.73076966e7 m
```
I am sure I did not wait that long.

P.S.: I guess there is no chance that we could get the information on compilation time, right?

**Comment by IanButterworth** [comment]
> Why not make it default? Who will complain about timings being shown?

Updated!

> Something somewhere needs some tweaking:

I think I found and fixed the bug

**Comment by IanButterworth** [comment]
One minor formatting issue is when there are no tests

Currently:
Screen Shot 2021-12-02 at 11 41 45 PM

Could be fixed by changing to "None" given it's shorter than "Total", and fixing the padding
Screen Shot 2021-12-02 at 11 41 35 PM

**Comment by IanButterworth** [comment]
I pushed that change, but happy to drop it if it's too disruptive

**Comment by thchr** [comment]
Very bikeshed'y comment: but could the table header be 'Time' rather than 'Duration'? I often use Julia in vertical split-screen mode with an editor; even now, the corresponding limited REPL width often leads to garbled testset printing - reducing the width of the new timing-column would at least help reduce the impact of this a bit.

Relatedly, if the table header is changed to 'Time' the kwarg could be `showtime` instead of `showtiming`?

**Comment by IanButterworth** [comment]
@thchr I think that's reasonable. "Duration" was longer than all the other titles, so it did look a bit unbalanced too.

Screen Shot 2021-12-03 at 5 20 02 PM

I didn't rename `showtiming` as `@showtime` is now a macro in base, and I think `showtiming` is ok? `timing` as a concept is closer to what it does. `time` is more of an instant in time?
These are minor thoughts though.


Is it acceptable to place the units right beside the number? It looks a bit tidier

Screen Shot 2021-12-03 at 5 24 04 PM

**Comment by thchr** [comment]
Cool!

> I didn't rename `showtiming` as `@showtime` is now a macro in base, and I think `showtiming` is ok? `timing` as a concept is closer to what it does. `time` is more of an instant in time?

Makes sense.

**Comment by IanButterworth** [comment]
I went with no space
 
image

**Pull request merged**
