### PR TITLE
lowering: copy expand-if optimization to expand-while

### LINKED ISSUE #42190: inference: type constraints from multi `while` conditions don't propagate to the `while` body
MRE:
```julia
julia> function foo(r::Union{Nothing,Int}, n::Int)
           while r !== nothing && r < n
               return r # `r::Int`
           end
           return n
       end
foo (generic function with 1 method)

julia> code_typed(foo, (Union{Nothing,Int},Int); optimize=false)
1-element Vector{Any}:
 CodeInfo(
1 ─ %1 = (r !== Main.nothing)::Bool
└──      goto #3 if not %1
2 ─      (@_4 = r::Int64 < n)::Bool
└──      goto #4
3 ─      (@_4 = false)::Core.Const(false)
4 ┄      goto #7 if not @_4
5 ─      return r
6 ─      Core.Const(:(goto %1))::Union{}
7 ┄      return n
) => Union{Nothing, Int64}
```

This happens because inference merges both "then" condition (`r::Int`) and "else" condition (`r::Const(nothing)`) at `4 ┄      goto #7 if not @_4`.

Maybe we can change lowering so that "then" and "else" don't use the same goto checkpoint ?

### PR DESCRIPTION
**Pull request by vtjnash**
Ref #42189
Fixes #42190

copied from expand-if, and moved a couple things, so I might have missed something, but this seemed simple and seemed to work on the test

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
This produces solid lowered code as far as I tried, but I still would like to ask Jeff to review the implementation of scheme code.

**Comment by simeonschaub** [comment]
I think we should move the common parts out into their own functions, so we don't have so much unnecessary duplication here. If you think that's easier, I can also just push to your branch.

**Comment by vtjnash** [comment]
Sure, if you'd like to improve this more, feel free to push here.

**Comment by simeonschaub** [comment]
Ah, wait, forgot to refactor the second part as well ^^

**Pull request merged**
