### PR TITLE
Bump FFTW version (Julia 0.6.x)

### LINKED ISSUE #27306: Test failures and errors on 0.6.x-builds with recent Arch Linux
I just built v0.6.3 in a freshly cloned Julia-repo (no user settings, on Arch Linux) and get test failures & erros.  It seems like they are all related to FFTW not working:
```
~/julia/julia-0.6((HEAD detached at v0.6.3))  >> make test-fft                                                                                                           
    JULIA test/fft                                                                                                                                                       
Test (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)                                                                                                         
fft: Test Failed                                                                                                                                                         
  Expression: norm(ifft(fft(a)) - a) < 1.0e-8                                                                                                                            
   Evaluated: 1.6196790957087954 < 1.0e-8                                                                                                                                
Stacktrace:                                                                                                                                                              
 [1] include_from_node1(::String) at ./loading.jl:576                                                                                                                    
.... many many more failures

Test Summary: | Pass  Fail  Error  Total                                  
  Overall     | 1661   281      1   1943                                                                                                                                
    fft       | 1661   281      1   1943                                                                                                                                
    FAILURE                                                                                                                                                             
...
```
this test also throws the following errror:
```
Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: linearity error 0.12247896 in FFTW forward plan for 40-element array of Complex{Float32}                                                                   
  (dft-thr-ct-dit-x2/5
    (dftw-direct-5/16 "t3fv_5_avx")
    (dftw-direct-5/16 "t3fv_5_avx")
    (dft-thr-vrank>=1-x2/1
      (dft-direct-8-x3 "n1fv_8_sse2")
      (dft-direct-8-x2 "n1fv_8_sse2")))
  Stacktrace:
   [1] fft_test(::Base.DFT.FFTW.cFFTWPlan{Complex{Float32},-1,false,1}, ::Int64, ::Float64) at /home/mauro/julia/julia-0.6/test/fft.jl:265                              
   [2] fft_test(::Base.DFT.FFTW.cFFTWPlan{Complex{Float32},-1,false,1}) at /home/mauro/julia/julia-0.6/test/fft.jl:254                                                  
   [3] macro expansion at /home/mauro/julia/julia-0.6/test/fft.jl:288 [inlined]
   [4] anonymous at ./<missing>:?
   [5] include_from_node1(::String) at ./loading.jl:576
   [6] include(::String) at ./sysimg.jl:14
   [7] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:18 [inlined]
   [8] macro expansion at ./test.jl:860 [inlined]
   [9] macro expansion at ./util.jl:378 [inlined]
   [10] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:17 [inlined]                                                                                    
   [11] anonymous at ./<missing>:?
   [12] eval(::Module, ::Any) at ./boot.jl:235
   [13] runtests(::String, ::Bool) at /home/mauro/julia/julia-0.6/test/testdefs.jl:21                                                                                   
   [14] (::Base.Distributed.##135#136{#runtests,Tuple{String},Array{Any,1}})() at ./distributed/remotecall.jl:319                                                       
   [15] run_work_thunk(::Base.Distributed.##135#136{#runtests,Tuple{String},Array{Any,1}}, ::Bool) at ./distributed/process_messages.jl:56                              
   [16] #remotecall_fetch#140(::Array{Any,1}, ::Function, ::Function, ::Base.Distributed.LocalProcess, ::String, ::Vararg{String,N} where N) at ./distributed/remotecall.jl:344
   [17] remotecall_fetch(::Function, ::Base.Distributed.LocalProcess, ::String, ::Vararg{String,N} where N) at ./distributed/remotecall.jl:344                          
   [18] #remotecall_fetch#144(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N} where N) at ./distributed/remotecall.jl:372                 
   [19] remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N} where N) at ./distributed/remotecall.jl:372                                                     
   [20] macro expansion at /home/mauro/julia/julia-0.6/test/runtests.jl:57 [inlined]                                                                                    
   [21] (::##44#50)() at ./task.jl:335
  while loading /home/mauro/julia/julia-0.6/test/fft.jl, in expression starting on line 285                                                                             
ERROR: LoadError: Test run finished with errors
while loading /home/mauro/julia/julia-0.6/test/runtests.jl, in expression starting on line 29                                                                           
make[1]: *** [Makefile:18: fft] Error 1
make: *** [Makefile:573: test-fft] Error 2
```


```
~/julia/julia-0.6((HEAD detached at v0.6.3))  >> make test-dsp                                                                                                          
    JULIA test/dsp                                                                                                                                                                                                                                                                                                         
Test (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)                                                                                                        
dsp: Test Failed                                                                                                                                                        
  Expression: conv(complex.(a, ones(4)), complex(b)) ≈ complex.([1.0, 4.0, 8.0, 10.0, 7.0, 6.0], [1.0, 3.0, 6.0, 6.0, 5.0, 3.0])                                        
   Evaluated: Complex{Float64}[1.0+6.0im, 0.0+5.0im, 4.44089e-16+3.0im, 6.0+0.0im, 7.0+4.44089e-16im, 10.0+1.0im] ≈ Complex{Float64}[1.0+1.0im, 4.0+3.0im, 8.0+6.0im, 10.0+6.0im, 7.0+5.0im, 6.0+3.0im]                                                                                                                                          
Stacktrace:                                                                                                                                                             
 [1] include_from_node1(::String) at ./loading.jl:576                                                                                                                   
 [2] include(::String) at ./sysimg.jl:14                                                                                                                                
 [3] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:18 [inlined]                                                                                       
 [4] macro expansion at ./test.jl:860 [inlined]                                                                                                                         
 [5] macro expansion at ./util.jl:378 [inlined]                                                                                                                         
 [6] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:17 [inlined]
 [7] anonymous at ./<missing>:?                                                                                                                                         
Worker 1 failed running test dsp:                                                                                                                                       
Some tests did not pass: 364 passed, 1 failed, 0 errored, 0 broken.dsp: Test Failed                                                                                     
  Expression: conv(complex.(a, ones(4)), complex(b)) ≈ complex.([1.0, 4.0, 8.0, 10.0, 7.0, 6.0], [1.0, 3.0, 6.0, 6.0, 5.0, 3.0])                                        
   Evaluated: Complex{Float64}[1.0+6.0im, 0.0+5.0im, 4.44089e-16+3.0im, 6.0+0.0im, 7.0+4.44089e-16im, 10.0+1.0im] ≈ Complex{Float64}[1.0+1.0im, 4.0+3.0im, 8.0+6.0im, 10.0+6.0im, 7.0+5.0im, 6.0+3.0im]                                                                                                                                          
Stacktrace:                                                                                                                                                             
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:568                                                                                              
 [2] (::##40#46)() at /home/mauro/julia/julia-0.6/test/runtests.jl:160                                                                                                  
 [3] cd(::##40#46, ::String) at ./file.jl:70                                                                                                                            
 [4] include_from_node1(::String) at ./loading.jl:576                                                                                                                   
 [5] include(::String) at ./sysimg.jl:14                                                                                                                                
 [6] process_options(::Base.JLOptions) at ./client.jl:305                                                                                                               
 [7] _start() at ./client.jl:371                                                                                                                                        
                                                                                                                                                                        
Test Summary: | Pass  Fail  Total                                                                                                                                       
  Overall     |  364     1    365                                                                                                                                       
    dsp       |  364     1    365                                                                                                                                       
    FAILURE                                                                                                                                                             
Error in testset dsp:                                                                                                                                                   
Test Failed
  Expression: conv(complex.(a, ones(4)), complex(b)) ≈ complex.([1.0, 4.0, 8.0, 10.0, 7.0, 6.0], [1.0, 3.0, 6.0, 6.0, 5.0, 3.0])                                        
   Evaluated: Complex{Float64}[1.0+6.0im, 0.0+5.0im, 4.44089e-16+3.0im, 6.0+0.0im, 7.0+4.44089e-16im, 10.0+1.0im] ≈ Complex{Float64}[1.0+1.0im, 4.0+3.0im, 8.0+6.0im, 10.0+6.0im, 7.0+5.0im, 6.0+3.0im]                                                                                                                                          
ERROR: LoadError: Test run finished with errors                                                                                                                         
while loading /home/mauro/julia/julia-0.6/test/runtests.jl, in expression starting on line 29
make[1]: *** [Makefile:18: dsp] Error 1                                                                                                                                 
make: *** [Makefile:573: test-dsp] Error 2       
```
and
```
              JULIA test/offsetarray                                                                                                                                              
Test (Worker)   | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)                                                                                                      
                                                                                                                                           
offsetarray: Test Failed                                                                                                                   
  Expression: ifft(fft(thisa)) ≈ circcopy!(a1, thisa)                                                                                      
   Evaluated: Complex{Float64}[0.0+0.0im, 8.88178e-17+0.0im, -4.44089e-17+0.0im, -4.44089e-17+0.0im, 1.0+0.0im] ≈ [0.0, 1.0, 0.0, 0.0, 0.0]
Stacktrace:                                                                                                                                
 [1] macro expansion at /home/mauro/julia/julia-0.6/test/offsetarray.jl:426 [inlined]                                                      
 [2] anonymous at ./<missing>:?                                                                                                            
 [3] include_from_node1(::String) at ./loading.jl:576                                                                                      
 [4] include(::String) at ./sysimg.jl:14                                                                                                   
 [5] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:18 [inlined]                                                          
 [6] macro expansion at ./test.jl:860 [inlined]                                                                                            
 [7] macro expansion at ./util.jl:378 [inlined]
 [8] macro expansion at /home/mauro/julia/julia-0.6/test/testdefs.jl:17 [inlined]
 [9] anonymous at ./<missing>:?
offsetarray: Test Failed
              JULIA test/offsetarray             
... many more                                                                                                                                 
```  

CC: @ararslan

### PR DESCRIPTION
**Pull request by mauro3**
This fixes an issue with gcc 8.x compatibility on Julia 0.6.x
http://www.fftw.org/release-notes.html

Fixes #27306

Is `release-0.6` the correct branch to make this PR against?

### CODE REVIEW

**Comment by ViralBShah** [comment]
That is the right branch. We may not make a new release, but it will help folks building from source.

**Comment by ViralBShah** [comment]
Shouldn't we just do FFTWBuilder now?

**Comment by fredrikekre** [comment]
So this branch takes less than an hour to run on Travis, master branch is more than double that. What happened?

**Comment by ViralBShah** [comment]
Master now has Pkg3 precompile, OldPkg tests and new Pkg tests, the compiler has slowed down, etc.

**Pull request merged**
