### PR TITLE
Use 4 space indent in Markdown

### LINKED ISSUE #9849: markdown code does not adhere to the conventions of base julia
When playing around with our new documentation system, the markdown code is formatted very differently from the rest of base (2 character tabs).

cc @one-more-minute

### PR DESCRIPTION
**Pull request by hayd**
fixes #9849

cc @one-more-minute @jakebolewski

### CODE REVIEW

**Comment by ivarne** [comment]
I love
```
git fetch https://github.com/hayd/julia.git markdown_indent
git show --ignore-space-change  e23a1921041482f8348b94b7acf827b61518a90f
```
That saved me an hour reviewing a change like this properly (so that I wouldn)

**Comment by hayd** [comment]
@ivarne Github tricks: https://github.com/JuliaLang/julia/pull/9852/files?w=1 :)

Thanks!

**Comment by ivarne** [comment]
Nice!

(would've be nice to post that trick before this got merged)

Thanks!

**Comment by hayd** [comment]
@ivarne sorry, I had forgotten about it 'til you said!

**Comment by tkelman** [comment]
@hayd that is an awesome trick - here's another great example of its usefulness: https://github.com/JuliaLang/julia/commit/d952f5fa27a22c2fb01f0d8c7085dfeaa656c085?w=1

**Pull request merged**
