### PR TITLE
fix the optimizer's use of cached varargs type info for _apply unrolling

### PR DESCRIPTION
**Pull request by jrevels**

### CODE REVIEW

**Comment by jrevels** [comment]
Note that this closes #25492.

**Comment by jrevels** [comment]
Test failures are unrelated. The CircleCI ones are kinda hilarious. 

The single Travis failure was just to GitHub not being reachable for some reason.

The CircleCI tests ran after #28091 was merged, which seems to be what caused the failures there - looks like the `JULIA_CPU_CORES` deprecation message is getting printed while executing certain commands whose raw output is being tested against, and the tests don't account for the `JULIA_CPU_CORES` deprecation. cc @StefanKarpinski  

I'll wait until this evening to merge to give more time for folks to review if they'd like to.

**Comment by StefanKarpinski** [comment]
Where is the use of `JULIA_CPU_CORES` coming from?

**Comment by StefanKarpinski** [comment]
Oh, I see, CircleCI does this broken thing where it uses the configuration from the branch to test the result of merging the branch with master. So the configuration is wrong and sets `JULIA_CPU_CORES` instead of 
`JULIA_CPU_THREADS`. So a rebase on master should pass.

**Comment by StefanKarpinski** [comment]
FreeBSD failure is the new OffsetArray issue which is unrelated. There's a conflict though, so you may as well rebase again after that gets fixed.

**Comment by jrevels** [comment]
Rebased again, hopefully this'll be the one!

**Pull request merged**
