### PR TITLE
Very much WIP: put Pkg3 in stdlib

### PR DESCRIPTION
**Pull request by KristofferC**
This is quite still a lot of WIP but I wanted to put this up since I am going on vacation next week.

For now, the usefulness of this branch is probably limited to that people can build the branch locally and get a feel for Pkg3.

There are still stuff that needs to be merged in the Pkg3 repo and this needs to be rebased on current master. There are also some design decisions left to be made.

 One things I want to know here is that it is extremely important to get the precompilation stuff right for Pkg3. It is very slow without precompilation directives, but with proper ones (that I hope I have here) it is pretty snappy.

### CODE REVIEW

**Comment by vchuravy** [comment]
I would propose that we either do this via a git-submodule or download Pkg3 during the Julia build, instead of including all the source files (without history) in the main repository. 
We need a path forward for stdlib packages that live outside of the JuliaLang repository anyway.

**Comment by KristofferC** [comment]
I will add the history. There was just a lack of time which is why this PR is not very nice. I put it up anyway since perhaps someone want to play with it. I don't think submodules are a good way forward. Especially not for Pkg that needs significant hooks into Base. From what I have read, a lot of people regret using submodules.

**Comment by StefanKarpinski** [comment]
Git submodules solve zero problems in my experience and create many of them.

**Comment by vchuravy** [comment]
As an alternative to submodules or source code import I propose something along the line of https://github.com/JuliaLang/julia/tree/vc/pkg3

**Pull request closed without merging**
