### PR TITLE
Point to ModernJuliaWorkflows in "getting started"

### PR DESCRIPTION
**Pull request by gdalle**
Add link to https://modernjuliaworkflows.github.io/

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by ViralBShah** [comment]
Good to merge. Should this live in the JuliaLang org?

**Comment by gdalle** [comment]
> Good to merge. Should this live in the JuliaLang org?

I think it would be a good idea for maintenance, but it would make the URLs a bit longer (unless we change the name of the website). Such a proposal also revives the question of whether MoJuWo should be part of the official docs / website.
 @adrhill and @jacobusmmsmit what do you think?

**Comment by ViralBShah** [comment]
My view is that once we link it prominently - it becomes an official Julia resource - and thus good to have in the usual places. Over time, one can even imagine that this just becomes part of the manual and offical docs.

**Comment by adrhill** [comment]
I would love for MoJuWo to become an official resource. Merging this into the manual would take a bit of effort and rewriting at this point, since we make use of a bunch of Franklin/Xranklin features. 

> Should this live in the JuliaLang org?

This sounds like a great compromise.

> it would make the URLs a bit longer (unless we change the name of the blog)

Maybe JuliaHub has some funds for a custom domain like modernjuliaworkflows.org? 😅

**Comment by jacobusmmsmit** [comment]
Ultimately, I believe that it makes sense to keep the resource active separately to the manual and docs, even if the information is incorporated. One of the main reasons we wrote the articles was to have a concise collection of useful tools that didn't feel like a great undertaking to read or find what you wanted, which is how the docs can feel for newcomers.

**Comment by KristofferC** [comment]
I agree that it is good to have this separate where it can be updated independently of Julia version etc. I don't think it has to be moved anywhere, at least not in any hurry.

**Comment by ViralBShah** [comment]
I'm buying the domain and pointing it to github pages. If you share your namecheap login with me, I'll add you as an admin to the domain.

**Comment by adrhill** [comment]
I made a new namecheap account, my username is the same as here.

**Comment by gdalle** [comment]
@ViralBShah actually would you mind sharing the namecheap account with me too? Same handle as on GitHub, `gdalle`

**Pull request merged**
