### PR TITLE
Move out SparseArrays and SuiteSparse from the sysimage

### PR DESCRIPTION
**Pull request by KristofferC**
cc @ViralBShah 

```jl
julia> @time using SparseArrays
  1.821477 seconds (2.71 M allocations: 300.647 MiB, 0.32% compilation time)

julia> @time using SuiteSparse
  0.242231 seconds (228.92 k allocations: 18.472 MiB, 40.21% compilation time)

julia> @time using Statistics
  0.002257 seconds (4.08 k allocations: 428.594 KiB)
```

### CODE REVIEW

**Comment by ViralBShah** [comment]
Those times look quite ok. And probably can receive a bit of love once we move out of sysimage. Does it improve Julia startup time slightly?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44247#issuecomment-1045325049) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/9b86d4d_vs_f5d9b86/report.html).

**Comment by fredrikekre** [comment]
A common failure mode seems to be `MethodError` for missing factorizations on `SparseMatrixCSC`.

**Comment by KristofferC** [comment]
Ugh, this further shows that SparseArrays and SuiteSparse should not have been separated into different packages. SuiteSparse does type piracy between `\` and `SparseArrayCSC`.

**Comment by ViralBShah** [comment]
The reason we split them was so that they could be moved out one at a time - and possibly across releases. I am ok with folding back SuiteSparse.jl into SparseArrays.jl, now that they are all out into separate repos, and would be happier if we can move them out of stdlibs altogether.

**Comment by ViralBShah** [comment]
Can we do this early in the 1.9 release?

**Comment by DilumAluthge** [comment]
The earlier we move it out, the longer we have to test it in the wild before the 1.9 release.

I also think we need to advertise this change broadly across multiple fora, including (but not limited to) Discourse, Slack, and Zulip. And again, the sooner we make the announcement, the more time people have to fix their code.

**Comment by KristofferC** [comment]
Well, the fact that SuiteSparse does type piracy makes moving them out hard. I guess we could start with Statistics.

**Comment by ViralBShah** [comment]
Why is the type piracy a problem? Can't we just merge suitesparse into the sparsearrays package if that is a concern?

**Comment by ViralBShah** [comment]
If making SparseArrays depend on SuiteSparse solves it, that would be the preferred solution. @KristofferC I'm always not sure about these stdlib things - is this something you can do?

**Comment by Wimmerer** [comment]
What remains to be done here?

**Comment by ViralBShah** [comment]
What we need to do is to ensure that SuiteSparse.jl is always installed when SparseArrays.jl is and ensure that https://github.com/JuliaLang/julia/pull/44247 passes.

**Comment by ViralBShah** [comment]
@KristofferC Is the simplest solution here to make SparseArrays.jl depend upon SuiteSparse.jl - to ensure that both are always installed together?

**Comment by ViralBShah** [comment]
For Statistics, we do want to get it out of the system image and off in to its own package, but it will be odd for `mean` and `std` not in base. So perhaps there's some refactoring to be done there. Maybe we should separate out the PR for Statistics?

**Comment by brenhinkeller** [comment]
> For Statistics, we do want to get it out of the system image and off in to its own package, but it will be odd for `mean` and `std` not in base.

Well actually, while I'm not sure I really like the trend of moving everything out of base and stdlibs all the time, this actually might be a silver lining. 

My main "elegance" gripe re the last time things got spun out (1.0) was that the statistics functionality kinda got fractured, with some things in Statistics and some things in StatsBase. 

So if the overall trend is going to continue (and we can't put StatsBase back into Statistics) then maybe the better option actually is to rip off the bandaid, move everything out *including* `mean` and `std` out, spin off Statistics as a separate package and then re-merge that with StatsBase

**Comment by ViralBShah** [comment]
The last time we tried to move `mean` and `std` out of base, the crowd came at us with pitchforks. I would not want to face that crowd again! Can't we just have mean and std for basic arrays in base with all the fancy versions in Statistics? If we are moving them out of base, it would be worth taking a pulse on discourse.

**Comment by nalimilan** [comment]
Having the basic version in Base and weighted versions in Statistics would certainly be possible (currently they are split between Statistics and StatsBase). It would be a bit more tricky if we want to use a keyword argument (though possible using dispatch under the hood). But I would have hoped this change would be the occasion simplifying the organization of stats functions.

Also `std` is implemented by calling `var`, so if we put the former in Base we should probably also move the latter.

Anyway yes, asking for feedback on Discourse is a good idea.

**Comment by brenhinkeller** [comment]
I think I was part of that crowd last time 😆. And TBH I *still* don't think I really understand *why* there's such a push to pull things out of base anyways. But if it's going to happen anyways, I think there's something to be said for doing it in a way that maximizes the number of things that'll be in one place and minimizes the number of `using`s one has to do to get a nice interactive environment for statistics.

**Comment by brenhinkeller** [comment]
Splitting `mean` between a no-frills version in Base and a full-featured version in neo-Statistics could work, but I actually worry that'll cause confusion.

As a selfreport, it took me I think two years to realize that `using Random` could ""change the behavior"" of `Base.rand`. I mean, it's totally unsurprising that this is possible when you're thinking with your multiple dispatch hat, but that's not where most people are probably starting
```
julia> @benchmark rand()
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  4.372 ns … 38.532 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.397 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.796 ns ±  1.099 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █  ▂      ▂▁  ▄▂      ▂▄              ▄                 ▃▃ ▁
  █▃▁█▇▁▆█▃▁██▃▁██▃▁▁▁▁▃██▄▃▁▁▁▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▃▁▁▁▁▃▁██ █
  4.37 ns      Histogram: log(frequency) by time     6.52 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> using Random

julia> rng = MersenneTwister()
MersenneTwister(0x2d04c78cb5f2efddf4a13ff05d5a45dd)

julia> @benchmark rand($rng)
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  3.037 ns … 23.432 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.347 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.376 ns ±  1.144 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

      ▃  ▃█
  ▂▁▂▇█▂▅██▃▇▂▂▂▁▁▁▁▁▂▁▁▂▁▁▂▂▁▁▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂ ▂
  3.04 ns        Histogram: frequency by time        13.1 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

**Comment by nalimilan** [comment]
Regarding statistics, the main goal is to get rid of the divide between Statistics and StatsBase. Note that if some functions are "promoted" to Base you won't need to call `using` to use them. In the scheme I mentioned, `using Statistics` wouldn't change the behavior of `mean(x)`, it would just allow doing `mean(x, weights(w))` or maybe `mean(x, weights=w)`. But I agree that having methods defined in different places is messier in terms of documentation and development.

**Comment by ViralBShah** [comment]
Might be a good idea to make this PR just about SparseArrays and SuiteSparse, and discuss Statistics in https://github.com/JuliaLang/julia/pull/45594.

**Comment by Wimmerer** [comment]
I can post my version, that excused both iirc, but I can limit it to just sparse stuff.

**Comment by ViralBShah** [comment]
Sure why don't you post that and we'll close this one.

**Comment by ViralBShah** [comment]
Updated this PR to be just about moving SparseArrays and SuiteSparse out of the system image since Statistics has already been moved out.

**Comment by ViralBShah** [comment]
@Wimmerer Any idea why this is not passing tests on Windows in SuiteSparse? Perhaps we need to bump SparseArrays and SuiteSparse both to the latest versions?

**Comment by Wimmerer** [comment]
This is building Julia with this PR? I'll try on my Windows machine

**Comment by Wimmerer** [comment]
This looks a lot like: https://github.com/JuliaSparse/SuiteSparse.jl/issues/43

**Comment by Wimmerer** [comment]
Is `tmp = Vector{Ptr{Cvoid}}(undef, 1)` appreciably different from `tmp = Ref{Ptr{Cvoid}}(Ptr{Cvoid}())`? The type signature of the ccall is `Numeric::Ptr{Ptr{Cvoid}}`.

**Comment by ViralBShah** [comment]
Maybe a question to ask on slack. It ought not to be, but what is the outcome on some small standalone tests?

**Comment by Wimmerer** [comment]
I can't reproduce this bug locally yet, I think it's a reappearance of that CI-only bug from before. 

I'll experiment with just that function call.

**Comment by ViralBShah** [comment]
The last time around, I had carefully checked all the Int definitions and they seemed fine.

**Comment by ViralBShah** [comment]
Also bumping SparseArrays and SuiteSparse so that we get the latest versions in. PRs incoming.

**Comment by ViralBShah** [comment]
It seems that on Win64, the failing test is calling `umfpack_di_numeric` (line 453 in the [log file](https://build.julialang.org/#/builders/63/builds/6099/steps/5/logs/stdio)), but the sparse array should have Int64 indices and should instead be calling `umfpack_dl_numeric`.

**Comment by ViralBShah** [comment]
Continuing discussion in https://github.com/JuliaSparse/SuiteSparse.jl/issues/43

**Comment by ViralBShah** [comment]
The SparseArrays and SuiteSparse bumps are in (SS is now incorporated in SA and is an empty package).

**Comment by Wimmerer** [comment]
Are these failures related to us? That error message doesn't seem related to me.

**Comment by ViralBShah** [comment]
Don't seem related, but what is the actual error? I'm missing it - I thought it is getting stuck in the building system image phase and timing out on 32-bit win and linux.

**Comment by Wimmerer** [comment]
Well I can't actually tell either, the linux32 one was failing a minute ago I thought (that seemed like a codegen error or something). For win32 I don't actually see any errors other than `exit code 1`.

**Comment by ViralBShah** [comment]
I restarted the linux32 buildbot.

**Comment by ViralBShah** [comment]
At line 1232 in https://build.julialang.org/#/builders/29/builds/7561/steps/7/logs/stdio:

```
Generating REPL precompile statements... 37/40
Generating REPL precompile statements... 38/40
Generating REPL precompile statements... 39/40
Generating REPL precompile statements... 40/40
command interrupted, attempting to kill
Executing precompile statements... 1/1952
Executing precompile statements... 2/1952
Executing precompile statements... 3/1952
Executing precompile statements... 4/1952
Executing precompile statements... 5/1952
Executing precompile statements... 6/1952
```

**Comment by Wimmerer** [comment]
I see a timeout this time. Will splitting the tests into individual files help with that? Or was that just for memory purposes. It's failing on win64 this time rather than win32 like last time...

**Comment by ViralBShah** [comment]
Rerunning the win64 tester.

**Comment by ViralBShah** [comment]
Let's see how this goes.

**Comment by KristofferC** [comment]
Would maybe have been good to run PkgEval again.

**Comment by PallHaraldsson** [comment]
Since SuiteSparse (which is GPL) is moved out, it means the sysimage is now non-GPL, i.e. MIT only? And "Julia"? It's still a stdlib I believe, for now, and I'm not sure it changes the question if Julia should now be classified as non-GPL. I believe the plan it it will not even be stdlib, like DelimitedFiles isn't by now.

This is a reminder to updated GPL status, if I'm actually right, and not too soon, if it was forgotten.

**Comment by nalimilan** [comment]
AFAICT SuiteSparse was the only GPL library we link to  (see julia.spdx.json), though gmp and mpfr are still LGPL, so the compiled Julia will be LGPL once we move SuiteSparse out of the stdlib.

**Comment by johnnychen94** [comment]
It looks like moving out SparseArrays from sysimage significantly increases the package loading time because many small root dependencies use `Statistics` and `SparseArrays` with the assumption that they are loaded very fast.

| package | v1.8.0-rc1 | v1.9-dev.843 |
| ------- | ------- | ----- |
| FixedPointNumbers | 0.05s | 1.68s |
| ArrayInterface | 0.04s | 1.67s |
| Distances | 0.008s | 1.65s |
| ImageCore | 0.9s | 2.9s |

I kindly request some efforts into https://github.com/JuliaLang/Pkg.jl/issues/1285 so that people don't need to break packages into smaller pieces (say, `ArrayInterfaceCoreSparseArrays`) or use Requires.

**Comment by Wimmerer** [comment]
That is a gigantic slowdown... I had planned to work on conditional deps /glue deps at some point but became sidetracked.

After the 11th I can work towards that again, but that's likely too major a change at this stage of 1.9s lifecycle.

**Comment by ViralBShah** [comment]
Maybe precompile statements for these packages once they become regular packages will greatly help?

**Comment by KristofferC** [comment]
This is loading time so that won't help.

**Pull request merged**
