### PR TITLE
remove 0.5 syntax deprecation warnings

### PR DESCRIPTION
**Pull request by JeffBezanson**
This handles front-end-related syntax deprecations. A helpful "TODO" reminds us that we now have the option of parsing `=>` as a call (like other normal operators) instead of as its own expression head. I could go either way; it's nicer but could break some macros.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
+1 to parsing it as a normal call. Fewer special cases will make future macro writers happier.

**Comment by JeffBezanson** [comment]
Commit added for that.

**Comment by JeffBezanson** [comment]
@vtjnash What do you want tests for --- parsing of `=>`, or something else as well?

**Comment by JeffBezanson** [comment]
Note from triage: tests needed for the new (corrected) meaning of previously-deprecated `::` syntax.

**Comment by vtjnash** [comment]
mostly just testing for the meaning of type declarations

**Pull request merged**
