### PR TITLE
Add `--trace-compile=` flag to `--help-hidden` output.

### PR DESCRIPTION
**Pull request by NHDaly**
The `--trace-compile=stderr` flag was very helpful for us to understand what's going on in our system! :)

This PR just adds the flag to the list of flags in `julia --help-hidden`.

### CODE REVIEW

**Comment by NHDaly** [comment]
Was this not documented on purpose, because it's not a stable API or something? If so we could maybe just mark it EXPERIMENTAL or something?

**Comment by KristofferC** [comment]
Seems good to me to have this documented.

**Comment by KristofferC** [comment]
However, I think the docs is slightly wrong. The argument is a file name with only  `stderr` being special cased to print to `stderr` (unless it has been changed since the original implementation).

**Comment by JeffBezanson** [comment]
Right, we have been very conservative about what we document. Once this goes in the help, we can't change it :|

**Comment by maleadt** [comment]
Maybe this would be a better fit for `--help-hidden`, seeing how not many users would ever want to use this flag? Other options there seem like they might change too.

**Comment by NHDaly** [comment]
Thanks for the advice @maleadt. Sorry it took me so long to respond to it! I've moved the help string to `--help-hidden`, rebased, and repushed. PTAL! :)
Thanks!

**Pull request merged**
