### PR TITLE
LibGit2: improve error when CA root cert can't be set

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This addresses improving the error message in https://github.com/JuliaLang/julia/issues/38691.

This also fixes an insecure behavior: even if `set_ssl_cert_locations` failed, `REFCOUNT` was still incremented, so subsequent calls to `ensure_initialized` didn't call `initialize` and so there is never a successful call to `set_ssl_cert_locations`. Without this libgit2 defaults to not verifying host identities, which is insecure. To prevent this, this patch locks on `ensure_initialized` and decrements `REFCOUNT` if initialize throws an error, ensuring that `initialize` succeeds at least once, including the call to `set_ssl_cert_locations`.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Working on adding some tests to this since doesn't seem to break anything.

**Comment by StefanKarpinski** [comment]
Apparently LibGt2 does not error as expected with a bad (empty or non-existent) CA root certificates path on Linux AArch64. @Keno, are you the person to talk to about getting access to such a machine for debugging?

**Comment by Keno** [comment]
I can get you access to the buildbot, but that sounds like an issue with the docker container that actually runs the test, with is the domain of the great and powerful wizard @staticfloat .

**Comment by StefanKarpinski** [comment]
This seems to work just fine when I'm actually logged into the aarch64 buildbot, so I don't get the failure.

**Comment by StefanKarpinski** [comment]
My working theory here is that some tests that use LibGit2 happened to get run in the same process before the LibGit2 tests, which would cause the library to already be initialized and therefore would cause the tests that expect initialization failure to fail to fail, as seen here. This wouldn't be specific to aarch64, which is supported by aarch64 tests passing when restarted, but means that I need to isolate these tests in a separate process.

**Comment by StefanKarpinski** [comment]
How is CI still running on this? Six hours and counting...

**Comment by Keno** [comment]
Linux32 has a long backlog

**Pull request merged**
