### PR TITLE
Backports 1.6-rc1

### LINKED ISSUE #38491: abspath bug for relative directories
A bit of an edge case, but noticed this when looking at https://github.com/JuliaLang/julia/issues/23646 

Assume the current directory is `C:\Users\Mus\x`
```
julia> abspath("C:x")
"C:\\Users\\Mus\\x"  # correct


julia> abspath("X:x")
"X:x"  # should be "X:\x"
```

### LINKED ISSUE #39218: inlining bug with concrete Union constraints
```julia
julia> struct A end

julia> struct B end

julia> const AB = Union{A, B}
AB (alias for Union{A, B})

julia> f(::T, ::T) where {T<:AB} = false
f (generic function with 1 method)

julia> g(a, b) = (@nospecialize; if a isa AB && b isa AB; f(a, b); end;)
g (generic function with 1 method)

julia> g(A(), A())
false

julia> g(A(), B())
ERROR: fatal error in type inference (type bound)
Stacktrace:
 [1] g(a::Any, b::Any)
   @ Main ./REPL[15]:1
 [2] top-level scope
   @ REPL[17]:1

julia> versioninfo()
Julia Version 1.7.0-DEV.184
Commit 8e0183f2b6 (2020-12-28 17:36 UTC)
```

### LINKED ISSUE #39259: Can't shadow ARGS in Main
Works in Julia < 1.5 but fails after:
```bash
$ julia14 -e 'ARGS=1'

$ julia15 -e 'ARGS=1'
ERROR: cannot assign a value to variable Base.ARGS from module Main

$ julia16 -e 'ARGS=1'
ERROR: cannot assign a value to variable Base.ARGS from module Main

$ julia-master -e 'ARGS=1'
ERROR: cannot assign a value to variable Base.ARGS from module Main
```

Similar to https://github.com/JuliaLang/julia/issues/34924 but that only happened with `const`.

### LINKED ISSUE #39379: zero-argument getindex method in Base incorrectly assumes 1-based indexing
It seems that the bounds check used in `Base` for zero-dimensional indexing hardcodes a comparison to `1`, assuming one-based indexing.

This means that an array with nonstandard axes can successfully pass the bounds check and then access out-of-bounds memory when indexing. I encountered this in an [issue](https://github.com/JuliaArrays/OffsetArrays.jl/issues/194) on OffsetArrays and @jishnub tracked it down to this line in `Base`:

https://github.com/JuliaLang/julia/blob/69d24532980bda6db510b6d4b71f66e7ffff2e81/base/abstractarray.jl#L642

### LINKED ISSUE #39405: Renamed submodules does not play well with precompilation
This package code:
```julia
module ForgetImports

    import Pkg.PlatformEngines as pe
    import Pkg as p

    function test()
        println("Pkg = ", p)
    end

    function test2()
        println("PlatformEngines = ", pe)
    end

end # module
```
results in the following error if the module is precompiled
```
$ julia -q
julia> using ForgetImports

julia> ForgetImports.test()
Pkg = Pkg

julia> ForgetImports.test2()
ERROR: UndefVarError: pe not defined
Stacktrace:
 [1] test2()
   @ ForgetImports /tmp/tmp.wXr6KYv8f2/ForgetImports/src/ForgetImports.jl:11
 [2] top-level scope
   @ REPL[3]:1
```

Works fine without precompilation:
```
$ julia --compiled-modules=no -q                           
julia> using ForgetImports

julia> ForgetImports.test()
Pkg = Pkg

julia> ForgetImports.test2()
PlatformEngines = Pkg.PlatformEngines
```
(Tentatively putting on 1.6 milestone since the rename feature is new for 1.6).

### LINKED ISSUE #39426: Regression for `@which 1..2`
The `..` function is defined, for example, in `IntervalArithmetic.jl`. On 1.5 this works:
```jl
julia> using IntervalArithmetic

julia> @which 1..2
..(a::T, b::S) where {T, S} in IntervalArithmetic at /Users/dpsanders/Dropbox/packages/IntervalArithmetic/src/intervals/intervals.jl:145
```
whereas on 1.6 it errors:
```jl
julia> using IntervalArithmetic

julia> @which 1..2
ERROR: dot expressions are not lowered to a single function call, so @which cannot analyze them. You may want to use Meta.@lower to identify which function call to target.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ REPL[2]:1
```

### PR DESCRIPTION
**Pull request by KristofferC**
- [x] #38830 - fix erroneous code path within `show_sym`
- [x] #38938 - Fix symbol trampolines for OSX and export `jl_n_threads`
- [x] #39101 - Fixes so that test suite can run in more tightly sandboxed environment
- [x] #39149 - fix count(::BitArray; dims)
- [x] #39140 - gf: avoid adding cache entries wider than the original method
- [x] #39155 - Fix `p7zip_jll` environment setup
- [x] #38876 - [WIP] Speed up dense-sparse matmul
- [x] #39215 - fix return type for `jl_uncompress_argnames`
- [x] #39210 - [Artifacts]: Support `using Pkg.Artifacts` with LazyArtifacts
- [x] #39251 - Fix binaryplatforms `union` invalidation
- [x] #39246 - staticdata: fix unreferenced data assertion
- [x] #39236 - codegen: mostly fix uses of undefined PhiNodes
- [x] #39262 - fix #39259, leave `Main.ARGS` unresolved on startup
- [x] #39152 - Fix macos codesign workflow
- [x] #39274 - Use arch-independent magic number as start seed for Preferences hash
- [x] #39265 - aotcompile: avoid cache lookup when disallowed
- [x] #39252 - Prevent TOML invalidation by pirates of `T[elements...]`
- [x] #39237 - fix #39218, bug in subtyping fast path for tuples with repeated elements
- [x] #39153 - improve performance of disabling finalizers in locks
- [x] #39319 - Rebase: Performance regression of scalar randn() between Julia 1.4 and 1.5 
- [x] #39292 - Force-specialize on `T` in `cat_similar`
- [x] #39153 - improve performance of disabling finalizers in locks
- [x] #39294 - Improve inferability of shape::Dims for cat
- [x] #39316 - Preserve input type for unaliascopy(::ReinterpretArray)
- [x] #39321 - make `extrema` with dims inferrable
- [x] #39315 - Only create legal int types during alloc opt
- [x] #39336 - fix failing `enable_finalizers` test
- [x] #39131 - MbedTLS source build fixes
- [x] #39333 - Fix performance regression in broadcasting with CartesianIndices
- [x] #39221 - fix some issues with inference Conditionals
- [x] #39247 - Follow up #39221 
- [x] #38820 - inference: stop re-converging worlds after optimization 
- [x] #38871 - rm unnecessary `widenconst_bestguess` call 
- [x] #39116 - Improve inference SCC '[limited]' code computation
- [x] #39275 -  Prepend build_bindir to LLVM_CONFIG_PATH_FIX rather than append 
- [x] #39324 -  LibGit2: patch to pass hostkey & port to host verify callback 
- [x] #39279 - Correct mbedtls-cmake-findpy.patch whitespace.
- [x] #39364 - libgit2: fix for broken SSH host callback
- [x] #39375 - inference: SCC handling missing for return_type_tfunc
- [x] #39343 - gf: invalidate when adding new methods
- [x] #39073 - Add basic docs for (Lazy)Artifacts stdlibs
- [x] #39211 - Add libldl to SuiteSparse libs
- [x] #39212 - Copy libgomp as part of CSL build
- [x] #39366 - bugfixes for showing type aliases
- [x] #39387 - Don't touch gvars when compiling for an external back-end.
- [x] #39398 - [LLVM] Replace patch for half FP on Power8
- [x] #39408 - fix #39405, saving modules with renamed imports
- [x] #39414 - implement with fewer afoldl methods
- [x] #39393 - fix #39379, use first∘LinearIndices instead of 1
- [x] #39445 - 🤖 Bump the Downloads stdlib from 9d841d9 to 4e55241
- [x] #39429 - remove bad method specialization from cache
- [x] #39256 - make compact type alias output more compact

Need manual backport:
- [ ] #39115 - remove Core._apply Builtin
- [ ] #39142 - fix some compiler warnings

Non-merged PRs with backport label:
- [ ] #39446 - fix #39426, at-which not working with `..` function
- [ ] #39390 - Set -fno-gnu-unique for building LLVM
- [ ] #39378 - Restore StackOverflow error message for repeated frames
- [ ] #39185 - Fix broadcast error when eltype is inconsistent with getindex
- [ ] #38981 - Fix #38491: fix an abspath() edge case on Windows
- [ ] #38405 - Make Distributed.jl `Worker` struct thread-safe.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-757132820):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`/home/nanosoldier/workdir/jl_AqTIX5/julia -e 'VERSION >= v"0.7.0-DEV.3656" && using Pkg; Pkg.update()'`, ProcessExited(1)) [1]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/cfbb7dbbcc23e6a4b09f6e08324ed29d693bb588/benchmark/by_hash/73f862b_vs_ebcc603/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-757132799) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/56ff37a_vs_ebcc603/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-764776792):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`/home/nanosoldier/workdir/jl_X97z8U/julia -e 'VERSION >= v"0.7.0-DEV.3656" && using Pkg; Pkg.update()'`, ProcessExited(1)) [1]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/1a73d34864d110d02f3fbc57be2efc3987575809/benchmark/by_hash/85c46c0_vs_ebcc603/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-764766224) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/7d1533d_vs_ebcc603/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-764766518) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/7d1533d_vs_8240225/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "CBindingGen", "Circuitscape", "DiffEqParamEstim", "Documenter", "EliminateGraphs", "FeedbackNets", "FlashWeave", "GtkReactive", "IMFData", "InfiniteLinearAlgebra", "IntegerSequences", "IntervalTrees", "MLJClusteringInterface", "Manifolds", "Matcha", "MixedSubdivisions", "MultivariateBases", "MultivariateMoments", "P4est", "PDMats", "PLCTag", "PolyJuMP", "PolynomialTestSystems", "SemialgebraicSets", "SetProg", "StaticArrays", "StochasticPrograms", "TensorCast"], vs = ":release-1.6")`

**Comment by fingolfin** [comment]
https://github.com/analytech-solutions/CBindingGen.jl fails because it needs to be adapted to LLVM 11.0.1 (see content of https://github.com/analytech-solutions/CBindingGen.jl/tree/master/deps)

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-765237941) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/0d75f03_vs_8240225/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/39160#issuecomment-769634342) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/0e90f6c_vs_8240225/report.md). cc @maleadt

**Comment by krrutkow** [comment]
@fingolfin The incoming CBindingGen v0.4.5 release supports LLVM 11.0.1, so this should resolve the CBindingGen, P4est, and PLCTag package tests.

**Comment by KristofferC** [comment]
I ran the benchmarks locally and didn't see anything completely crazy. There are some things that might be real regressions but with the server situation being what it is I think we have to go on with RC1 and then perhaps we can do a proper check for RC2.

**Pull request merged**
