### PR TITLE
Fix isless(::SHA1, ::SHA1) method

### LINKED ISSUE #29583: lexless removed in master branch but still used in loading.jl
Grepping through the master branch for lexless revealed this:
```
base/loading.jl:99:isless(a::SHA1, b::SHA1) = lexless(a.bytes, b.bytes)
```

Indeed, one can now trigger this error:
```
julia> a = Base.SHA1("0123456789012345678901234567890123456789")
SHA1("0123456789012345678901234567890123456789")

julia> a < a
ERROR: UndefVarError: lexless not defined
Stacktrace:
 [1] isless(::Base.SHA1, ::Base.SHA1) at ./loading.jl:99
 [2] <(::Base.SHA1, ::Base.SHA1) at ./operators.jl:260
 [3] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by fingolfin**
Use isless instead of lexless. Fixes #29583

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by KristofferC** [comment]
Is this used anywhere? Can it be deleted?

**Comment by StefanKarpinski** [comment]
I'm not sure if we currently use it, but if you want to print a sorted list of SHA1 values, it's handy.

**Comment by KristofferC** [comment]
Sure but you can always just `string.(...)` it. It seems non-clear how to define this so letting someone be explicit seems better.

**Comment by StefanKarpinski** [comment]
What order would you possibly want to sort SHA-1 hash values in?

**Comment by KristofferC** [comment]
I don't see any reason to start adding arbitrary methods and tests to internal structs. A vector of `SHA1` is never formed in Base so there is no way you would end up with one.  It is just dead code floating around, should be deleted.

**Comment by staticfloat** [comment]
I agree it's obvious which way hashes should be sorted, but I also agree we should just remove the method.  We can add it back easily enough next time we want to sort hashes, for now it's just wasting space and compilation time.

**Comment by fingolfin** [comment]
Just to clarify, this not adding any methods, just fixing an existing one. As to the test: I merely added the test because where I come from, it's good policy to add tests for all code you add or touch. I don't mind dropping it either, though *shrug*

Also, I use none of this code, so if you rather drop that isless method, that's perfectly fine by me as well :-).

**Comment by StefanKarpinski** [comment]
The SHA1 type is not public, so it doesn't matter whether it has this method or not. It is, however, better to have a correct method than a broken one. Until we refactor this code to use a real SHA1 type, this is an improvement.

**Pull request merged**
