### PR TITLE
Missing complex tests

### PR DESCRIPTION
**Pull request by bramtayl**
Getting into the weeds, so might need another set of eyes.

I think should cover all the uncovered lines in the file but the one in `tan` (phone a friend?)

### CODE REVIEW

**Comment by bramtayl** [comment]
CI failures unrelated?

**Comment by Keno** [comment]
> CI failures unrelated?

yes

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
Actually, I may have been too quick to merge this. The division by complex infinity bit is an open issue (https://github.com/JuliaLang/julia/issues/32992), so somebody (@stevengj?) should confirm whether the signs on these `@test_broken`'s are correct.

**Comment by StefanKarpinski** [comment]
That's why I requested @stevengj's review on this one 😬

**Pull request merged**
