### PR TITLE
Make `LinearAlgebra._zeros` use `similar`

### PR DESCRIPTION
**Pull request by dkarrasch**
Fix https://github.com/JuliaLang/julia/pull/40899#issuecomment-866675285

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! Disregarding the CI failures here, this does make the relevant CUDA.jl code work again.

**Comment by andreasnoack** [comment]
The problem is that `similar(::SparseMatrixCSC)` is a `SparseMatrixCSC`. We need the output of `_zeros` to be a dense array.

**Comment by dkarrasch** [comment]
So we need to specialize `_zeros(::Type{T}, b::AbstractSparseVector, n::Integer)` to give a dense vector, right? I'll add that in `SparseArrays` and see how it goes.

**Comment by andreasnoack** [comment]
The problem is that `_zero` was supposed to be a single simple helper function. With these changes, it almost becomes part of the interface. I'm not sure what the right solution is. This wouldn't be a problem if `similar(::SparseMatrixCSC)` returned a `Matrix`.

**Comment by dkarrasch** [comment]
How did it work earlier? How did we use `similar` yet avoided the `*Diagonal` and sparse issues?

**Comment by andreasnoack** [comment]
> How did it work earlier?

I think that we effectively called `zeros` or `Matrix` for these cases. For some reason it didn't cause issues for CUDA. In my PR, I made all `\` use the same code path so a few extra `\` might now use `zeros`/`Matrix` instead of `similar`. Maybe `Cholsky\...` since @maleadt mentioned `potrs`. Maybe a better solution is to add `\` method to CUDA similar to the one here that initializes the rhs with a `CuArray`. We don't really have the right generic function to initialize the right hand side of a solve. At least that would require changing `similar` for sparse arrays in a way that probably isn't feasible at this stage.

**Comment by maleadt** [comment]
> Maybe `Cholsky\...` since @maleadt mentioned `potrs`.

Yup, that was the one. I'll duplicate a version of `\` for CuArrays in CUDA.jl.

**Comment by dkarrasch** [comment]
So we can close this, right?

**Comment by andreasnoack** [comment]
I'd think so. @maleadt can you please confirm that you were able to work around the issue by adding a method to CUDA.jl?

**Comment by maleadt** [comment]
Sorry for being unclear, yes this can be closed. It would be nice to revisit this at some point though, because code like https://github.com/JuliaGPU/CUDA.jl/blob/8ba1fe4f1c2b94e309eb4c51583783a43e7f297d/src/linalg.jl#L17-L48 is pretty fragile.

**Pull request closed without merging**
