### PR TITLE
Makes Pkg.test throw error when no tests/testsets are found

### PR DESCRIPTION
**Pull request by morris25**
Package testing should probably fail if there are no tests. Any suggestions for alternate approaches would be appreciated.

### CODE REVIEW

**Comment by thofma** [comment]
If there are no tests for the package, then all tests of the package pass. Why should it be an error?

**Comment by morris25** [comment]
If there are no tests for the package, then the tests cannot be said to pass or fail since they do not exist. Shouldn't Pkg.test at least warn that a package is untested?

**Comment by thofma** [comment]
Using the same argument, the call
```
julia> all( x -> x > 0, [])
true
```
should throw an error/warning?

**Comment by morris25** [comment]
I was thinking more along the lines of
```julia
julia> all( x -> x > 0, [missing])
missing
```
but I see your point

**Comment by thofma** [comment]
Now I see your point. I didn't think of three valued logic here.

**Pull request closed without merging**
