### PR TITLE
Test sort_int_range! for reverse sorting of large unsigned types

### LINKED ISSUE #43034: Sorting broken on an edge case
```jl
julia> sort(unsigned.([1,0,1,0,1,1]), rev=true)
6-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000000
 0x0000000000000001
 0x0000000000000000
 0x0000000000000001
 0x0000000000000001
```
see #42718 for why this bug exists

### PR DESCRIPTION
**Pull request by LilithHafner**
Fixes #43034
```julia
v = rand(UInt64(1):UInt64(2), 7)
issorted(sort(v; rev=true); rev=true) # false
```

The bug was in iterating over a reversed unsigned range (which is not possible). It only comes up for 'UInt`, `UInt64` & `UInt128` because the signed `1::Int` promotes to a signed result if the `UInt` is smaller in `1:rangelen`.

This came up in the process of building a comprehensive sorting test suite which may or may not ever end up suitable for merging into SortingAlgorithms or Base. It tests on many input types, which catches things like this, but results in very long compilation times (~30s) and a lot of compiled code (GBs).

### CODE REVIEW

**Comment by vtjnash** [comment]
Sorry that we missed this! Do you think https://github.com/JuliaLang/julia/pull/29842 solves this for you? I think that may be a more complete fix.

**Review by tkf — COMMENTED** [review]
Yes, it'd be nice if we can fix it at the level of `reverse`, as in #29842. But I think the test is a nice addition.

I think it'd be better to do the refactoring `where` -> `counts` in a separate PR. It's hard to explain a big diff (when squashed) like this in a concise commit message and hard to know what has been done when people revisit this in the future.

**Comment by LilithHafner** [comment]
@vtjnash yes, that would fix it. I agree that it would also be a better solution.
@tkf, I'll revert this back to the first commit adding the test and make a separate PR for `where` -> `counts`

**Comment by LilithHafner** [comment]
The rename PR is #43052

**Comment by tkf** [comment]
It looks like @vtjnash already merged this PR into #29842. I put `closes #42718` there so that this PR will be closed once #29842 lands.

**Pull request closed without merging**
