### PR TITLE
RFC: Distribute an OS X Installer

### PR DESCRIPTION
**Pull request by slarew**
I wrote some scripts that properly codesign and package up a Julia distribution into an installer for OS X.

I propose either distributing both the OS X app _and_ an OS X installer, or entirely move to only distributing an OS X installer.

Motivation: I personally prefer installing Julia directly into `/usr/local`.  If you already have Git and use other command line tools regularly, having Julia in `/usr/local` just feels right.  When Julia is inside an app bundle, the julia binary is not in the `PATH`, requiring extra knowledge and steps from the user who does not want to double click the app.  Furthermore, the Julia app is merely a wrapper (launches Terminal.app and runs the embedded julia binary) and not a typical OS X application or even IDE.  Using the OS X installer avoids the hassle of manually unpacking an archive and moving it into place.  Moreover, the installer has both a UI and command line interface for regular and power users alike.

I think there are some benefits to the Julia app that is currently distributed for OS X:
1. Easy "drag-n-drop" install.
2. Easy uninstall (just delete app or move app to trash).
3. Easy to run (double click the app).
4. Included Git (for those without it).
5. Simultaneous availability of multiple versions of Julia.

The first three points are arguably user friendly for novices.  To compare the installer approach to the benefits of the app:
1. The installer is nearly as easy to use for installation as drag-n-drop.  However, it currently requires admin privileges.
2. The installer adds an uninstall script under `sbin/` (but user must be told it exists).
3. Once installed, the user must know how to launch a shell and type `julia` (automated by the double click app approach).  An optional wrapper "Julia app" could be added to the installer that mimics the current Julia app.
4. Git could be added to the installer as an optional (opt-in or -out) component.
5. Supporting simultaneous install and switching between versions could be supported, but would require more thought for a good design.

I think distributing an app inside a DMG has some initial advantages for regular/novice users, but the burden is diminished or reversed for those who are comfortable working with a shell.

If you want to test the installer that is built by this script, you can find a copy at [my personal site](https://www.slarew.net/julia-os-x-installer/).

### CODE REVIEW

**Comment by tkelman** [comment]
Please open this against master first. The requirement of admin rights means I don't think we should switch exclusively to this.

**Comment by slarew** [comment]
@tkelman I will rebase and test against master.

I believe the requirement of admin privileges could be removed.  I created an installer package that was able to target directories in the user's home folder without admin privileges. However, the installer would fail (with a cryptic error message) if the user said to target his or her home folder but did not manually change the install location to be within the home folder.  I suspect this could be fixed if some javascript was added to the installer package with the correct logic.

**Comment by tkelman** [comment]
If that could be done then I think this could be considered for 0.5-dev, but a new installer is a feature and as a matter of policy we don't generally backport features.

> Git could be added to the installer as an optional (opt-in or -out) component.

Command-line git is not necessary at all on 0.5-dev which is now using LibGit2. Thanks to `@kshyatt`s recent work on Homebrew.jl it is now completely unnecessary to include it in the binaries, and I plan on removing it prior to the final release of 0.5.0.

**Comment by IainNZ** [comment]
> When Julia is inside an app bundle, the julia binary is not in the PATH, requiring extra knowledge and steps from the user who does not want to double click the app.

This alone is a great reason, very nice.

**Comment by slarew** [comment]
I could not get master to build on my machine.  Instead I grabbed the latest OS X nightly for 0.5 and archived the embedded julia folder.  The buildinstaller script worked fine against said archive.

@tkelman I respectfully disagree that adding an OS X installer would be a new feature for 0.4.  The language itself sees no new features, just the distribution method.

I'm not as familiar with the GitHub platform. Should I rebase my changes onto master branch, force push my osxinstaller branch? After doing that, do I need to create a new pr?

**Comment by tkelman** [comment]
As the person who builds the releases, yes this is absolutely a feature and would need changes on the build infrastructure and significant testing before we could make a release with it. Github doesn't let you retarget the branch for a PR, so just open a new one.

**Pull request closed without merging**
