### PR TITLE
Bump openlibm/specfun versions to get properly versioned shlibs for them

### PR DESCRIPTION
**Pull request by staticfloat**
Also move openspecfun git branch to `v0.5.1` as `master` is just a branch and is less desirable.

### CODE REVIEW

**Comment by tkelman** [comment]
These tags have out-of-date VERSION and SOMINOR, we should fix those values in Make.inc and re-tag first.

**Comment by staticfloat** [comment]
Done and done.

**Comment by tkelman** [comment]
whoops, something in openspecfun broke on arm? https://build.julialang.org/builders/package_tarballarm/builds/292/steps/make%20binary-dist/logs/stdio

**Comment by yuyichao** [comment]
This seems to be the failure I see without use openlibm

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/openspecfun/pull/39

**Pull request merged**
