### PR TITLE
Add a test to avoid #53054 regressions

### PR DESCRIPTION
**Pull request by pablosanjose**
Tests issue JuliaLang/LinearAlgebra.jl#1051. The same test is included in backport JuliaLang/julia#53074.

### CODE REVIEW

**Comment by KristofferC** [comment]
Should this ideally be a test is openblas?

**Comment by pablosanjose** [comment]
I also thought so initially, but seeing there was just a lone test in there I thought it might be reserved for other things. But yeah, let me move it.

**Comment by pablosanjose** [comment]
So, @giordano argues [here](https://github.com/JuliaLang/julia/pull/53074#discussion_r1468534032) that "I don't think this test should be here, this is meant to test only very basic functionalities of the jll, like opening the library and such. If we ever switch to a different default blas backend, the test would still be useful, it isn't specific to openblas."
After thinking it over, I agree with him. This test may seem a bit trivial on its own, but it is definitely not tied to OpenBLAS, it is a general test of deterministic behavior. So, absent an agreement between you two guys in a different direction, I'll revert the last commit in both PRs

**Comment by giordano** [comment]
@pablosanjose I think the `master` branch in your fork isn't in-sync with `master` of this repository, so the history of [your PRs](https://github.com/JuliaLang/julia/pulls?q=is%3Apr+author%3Apablosanjose+sort%3Aupdated-desc) is a bit messed up and always includes unrelated commit messages.

**Comment by pablosanjose** [comment]
Sorry about that, I'll try to fix it

**Comment by KristofferC** [comment]
> This test may seem a bit trivial on its own, but it is definitely not tied to OpenBLAS, it is a general test of deterministic behavior.

Eh, I mean, it's not like we run every test a million times like this does to test "deterministic behavior". With "should this ideally be a test in openblas" I meant that they shouldn't be in this repo at all but be tested upstream in openblas itself to prevent the regression at the earliest stage possible.

**Comment by pablosanjose** [comment]
Oh, I fully appreciate the point of Kirstoffer. When it doesn't fail, this test takes a full 0.15s on my machine. Maybe it is too excessive? The problem is that a lower number of iterations made it fail too infrequently to be useful. And of course his other argument that this would be more useful upstream is also totally clear. What do you think @giordano?

If you guys agree this is too much overhead for a test that is likely never going to fail again, please do use your authority to revert this PR.

**Pull request merged**
