### PR TITLE
missing julia-repl in destructuring docs

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Review by LilithHafner — APPROVED** [review]
Thanks! This is am improvement and mergible as is. To make it even better, it would be ideal to change this and the block above it to `jldoctest`.

**Review by inkydragon — COMMENTED** [review]
The output also needs to be updated.
	
	```jldoctest
	julia> map(((x, y),) -> x + y, [(1, 2), (3, 4)])
	2-element Vector{Int64}:
	 3
	 7
	```

**Comment by LilithHafner** [comment]
haha, yes. That is why use use jldoctest.

**Comment by LilithHafner** [comment]
Looking at 

> This is am improvement and mergible as is.

I'm going to merge this. Some things to track for future PRs
- Review all instances of `julia-repl` (and perhaps all code blocks) to see if they should be `jldoctest`
- Grep for Array{T, 1} and Array{T, 2}.

**Comment by LilithHafner** [comment]
Thanks for your contribution, @ArnoStrouwen!

**Pull request merged**
