### PR TITLE
Optimize image sizes

### PR DESCRIPTION
**Pull request by pthariensflame**
This was done by [ImgBot](https://imgbot.net/) on my own fork, which I then immediately merged and turned into this manual pull request.
Below is reproduced [ImgBot's own message](https://github.com/pthariensflame/julia/pull/1#issue-373462348) on the content of this PR.

---

> ## Beep boop. Your images are optimized!
> 
> Your image file size has been reduced by **19%** 🎉
> 
> <details>
> <summary>
> Details
> </summary>
> 
> | File | Before | After | Percent reduction |
> |:--|:--|:--|:--|
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/512@2x.png | 93.13kb | 62.33kb | 33.07% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/256@2x.png | 39.53kb | 27.93kb | 29.36% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/512.png | 37.95kb | 27.92kb | 26.42% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/128@2x.png | 16.51kb | 12.56kb | 23.94% |
> | /doc/images/github_metadata_develbranch.png | 64.04kb | 49.36kb | 22.92% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/256.png | 15.88kb | 12.70kb | 20.02% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/128.png | 7.12kb | 5.73kb | 19.56% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/32@2x.png | 3.29kb | 2.68kb | 18.56% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/16@2x.png | 1.43kb | 1.25kb | 13.14% |
> | /doc/images/github_metadata_pullrequest.png | 36.66kb | 31.91kb | 12.94% |
> | /contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/32.png | 1.44kb | 1.26kb | 12.27% |
> | /doc/images/jltypes.svg | 120.36kb | 116.92kb | 2.86% |
> | /doc/src/assets/logo-dark.svg | 6.82kb | 6.69kb | 1.92% |
> | /doc/src/assets/logo.svg | 6.81kb | 6.69kb | 1.84% |
> | /contrib/julia.svg | 3.19kb | 3.18kb | 0.15% |
> | | | | |
> | **Total :** | **454.15kb** | **369.09kb** | **18.73%** |
> </details>
> 
> ---
> 
> [📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by ViralBShah** [comment]
This is a nice little improvement. Does anyone know what the concerns might be if any?

Pinging @cormullion

**Comment by ViralBShah** [comment]
Might be a good idea to run it on the julialang website repo too.

**Comment by cormullion** [comment]
Seems like a good idea - these aren't the masters anyway.

Is this bunch of files used: 
julia/contrib/mac/frameworkapp/JuliaLauncher/Assets.xcassets/AppIcon.appiconset/512.png etc?

If so, they're out of date - showing the older Julia logo style with dark edges...

**Comment by ViralBShah** [comment]
Given that we now have the logos in their own repo, it might be a good idea to just get rid of them from contrib, except for the ones that are needed in the installers.

**Comment by cormullion** [comment]
Anyway that framework stuff was PR #31914 that is still pending/non-merged. I'd suggest leaving them as they are, and re-visiting if the PR is ever merged...

**Comment by pthariensflame** [comment]
I'll fork JuliaLang/www.julialang.org and do the same there.  I'll just wait for the conclusions on the rest of the concerns here before I do anything on this side.  🙂

**Comment by ViralBShah** [comment]
Fewer concerns on the www.julialang.org side. I think we'll just merge there. Here, we'll leave it open just another day or two.

**Comment by mbauman** [comment]
Is this using the default [`LosslessCompress()` option](https://imgbot.net/docs/#compression)?

**Comment by pthariensflame** [comment]
@mbauman It is, yes.

**Comment by pthariensflame** [comment]
@ViralBShah Any news on this?

**Comment by ViralBShah** [comment]
Good to merge.

**Pull request merged**
