### PR TITLE
fix UnitRange's stop field for release-0.3

### LINKED ISSUE #12534: crash on constructing array of Rationals
On Windows7 64 bit, attempt to constructing the array `[1:10//3]` crashes Julia 0.3.11. `[1:10//2]` works fine.

```
C:\Users\michele>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> [1:10//2]
5-element Array{Rational{Int64},1}:
 1//1
 2//1
 3//1
 4//1
 5//1

julia> [1:10//3]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1c5c885b --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
```

### PR DESCRIPTION
**Pull request by mzaffalon**
backport from 0.4.0 of unitrange_last, fixes #12534
added tests

### CODE REVIEW

**Comment by tkelman** [comment]
Cool, thanks for this. @StefanKarpinski could you take a quick look and say off the top of your head whether this might break or change anything that's currently working on 0.3? It looks okay to me but I wouldn't mind a second opinion.

**Comment by nalimilan** [comment]
Thanks for the PR. It would be good to mention in the commit message that this copies code from 0.4, and add "fixes #12692" so that the issue is automatically closed after merging.

**Comment by StefanKarpinski** [comment]
@JeffBezanson, this was your change. Does this seem safe to you?

**Comment by michele-zaffalon** [comment]
It looks like instead it was reported in #10950.

**Comment by tkelman** [comment]
Ah. Well you managed to do it differently than I tried, and according to CI you've avoided the issue I hit.

**Comment by michele-zaffalon** [comment]
This also mean that I `git bisect`ed wrong and you (@tkelman) were right in finding #10452 weird as the responsible.

**Pull request merged**
