### PR TITLE
make worker_from_id always return without blocking

### LINKED ISSUE #11500: RemoteRef finalizer error
When trying to debug the recent CI error on 64bit Linux, I noticed the following gc finalizer error when trying to run the parallel test twice with

```julia
yuyichao% JULIA_CPU_CORES=2 ./julia -f test/runtests.jl parallel parallel
```

I've got a lot of `task switch not allowed in finalizer` error.

The backtrace is (with some `jl_apply_generic` removed)

```
jl_switchto+0xb8
julia_yieldto_20241+0x48
julia_wait_17556+0x258
julia_wait_18672+0x18d
julia_stream_wait_18243+0xc4
julia_sleep_18220+0x1c7
julia_worker_from_id_18210+0x1ae
julia_send_del_client_20325+0xc0
jlcall_send_del_client_20325+0xc
jl_gc_collect+0x36c
```

Haven't dig further but I'm reporting it here now in case it is useful for someone else.

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #11500.

This allows a `Worker` to be allocated as soon as the object is needed, instead of waiting for messages. This makes `worker_from_id` safe to call in a finalizer.

cc @amitmurthy

### CODE REVIEW

**Comment by tkelman** [comment]
That `EOFError` has gotten *really* common lately.

**Comment by JeffBezanson** [comment]
Have we seen this before?

```
	From worker 5:	System max size of single shmem segment(MB) : 43
	From worker 5:	System max size of all shmem segments(MB) : 8192
	From worker 5:	Requested size(MB) : 0
	From worker 5:	Please ensure requested size is within system limits.
	From worker 5:	If not, increase system limits and try again.
```

**Comment by amitmurthy** [comment]
The changes LGTM. The Travis error seems to be unrelated to this change and has been triggered by an unexplained death of worker 3.

**Comment by tkelman** [comment]
> Have we seen this before?

I think so, but starting somewhat recently IIRC.

**Comment by amitmurthy** [comment]
To add, in this particular case the shared memory error printed is a red herring. What happened is

- worker 8 was trying to setup and map a shared memory segment on all workers
- during this process, worker 3 died (for reasons unknown, but probably its state had been corrupted previously)
- worker 8 caught this event and unlinked the shared memory segment as part of a cleanup-on-error
- worker 5 which had received a request from worker 8 to map the segment, could not find it (and hence printed the above statements as part of additional debugging information)

**Pull request merged**
