### PR TITLE
Update ast.md to where syntax

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by ararslan** [comment]
When I was going through the docs I purposefully left this because otherwise the parsed representation shown below it is different.

**Comment by musm** [comment]
want to update the following parsed representation?

**Comment by ararslan** [comment]
I figured it was still instructive as-is, plus `f{T}` is still valid syntax.

**Comment by musm** [comment]
changing to the `where` would still be equally instructive?

**Comment by ararslan** [comment]
Sure, though showing the parsed representation of pretty much anything is also instructive. Should ask @JeffBezanson what he thinks would be best here.

**Comment by musm** [comment]
btw do you know how to get the following parsed form in the text from julia?

**Comment by ararslan** [comment]
There's a magical command line flag that drops you into flisp, which has `julia-parse`:
```
[10:19:04] alex:~ $ julia --lisp
;  _
; |_ _ _ |_ _ |  . _ _
; | (-||||_(_)|__|_)|_)
;-------------------|----------------------------------------------------------

> (julia-parse "function f(x::T; k = 1) where T\n    return x+1\nend")
(function (where (call f (parameters (kw k 1))
		       (:: x T))
		 T)
	  (block (line 2 none) (return (call + x 1))))
```

**Comment by musm** [comment]
@ararslan  thanks, updated the the code in the text with the output from that also removed the `none` part since it's not important (already this was done in one snippet in the docs)

**Comment by musm** [comment]
bump?

**Review by Sacha0 — APPROVED** [review]
lgtm (modulo the `none` removals, which I am not qualified to speak to)!

**Comment by ararslan** [comment]
The `none` removal should be fine since what's been replaced there is the parsed representation as it current is generated, whereas what was there before might be out of date.

**Pull request merged**
