### PR TITLE
REPL tab don't double " (Fix #7318)

### PR DESCRIPTION
**Pull request by lucasb-eyer**
That bug annoyed me a lit. I hope I didn't miss anything, because it was easier than what I expected!

I also removed a chunk of duplicate code on my way.

### CODE REVIEW

**Comment by damiendr** [comment]
This makes the tests fail on my particular OSX install:
```
julia> versioninfo()
Julia Version 0.5.0-dev+1306
Commit aa24ee0* (2015-11-15 23:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
```
    JULIA test/replcompletions
     * replcompletions      Test Failed
  Expression: "tmp/" in c
   Evaluated: "tmp/" in UTF8String["tmp\""]
...
while loading julia-dev/test/replcompletions.jl, in expression starting on line 395
```
```
$ ls /tmp
lrwxr-xr-x@ 1 root    11B May  2  2015 /tmp@ -> private/tmp
$ ls /tmp/
ls: /tmp/: No such file or directory
```

**Comment by damiendr** [comment]
@Keno @lucasb-eyer @vtjnash

**Comment by lucasb-eyer** [comment]
I assumed `/tmp` to be a readable folder for that test - I wouldn't know how to test otherwise. The same assumption is made in a few more tests [a few lines below](https://github.com/JuliaLang/julia/blob/master/test/replcompletions.jl#L413). I'm not sure what's best to do here.

**Comment by damiendr** [comment]
Maybe check `isdir("/tmp/")`? Mind you, it might just be my particular install that had its `/tmp/` deleted at some point.

**Comment by lucasb-eyer** [comment]
Heh you're right. If `isdir("/tmp/")` correctly return `false` on your system, would you mind opening a PR skipping those tests which require `/tmp/`? I believe it's three of them.

**Pull request merged**
