### PR TITLE
RFC: test 32 bit linux on travis

### PR DESCRIPTION
**Pull request by tkelman**
some slightly crazy `apt-get` contortions going on here, not sure whether this'll actually work

bonus: look at that multi-status action. appveyor's completely redundant for this one, but whatever.

### CODE REVIEW

**Comment by vtjnash** [comment]
You might get a better backtrace by stopping in siglongjmp and seeing the program state then, before it got too corrupted

**Comment by tkelman** [comment]
Any advice how to get gdb to stop there? setting a "breakpoint pending on future shared library load" for siglongjmp doesn't result in actually stopping before the segfault.

**Comment by vtjnash** [comment]
this function is in libc, if you get that message, you aren't setting it on the right function. many operating systems prefix the actual function name with one or two `_` characters, so you might try those variants

**Comment by tkelman** [comment]
Right place to look?
```
root@d05c884d6cc0:/tmp/julia/share/julia/test# readelf -a /lib/i386-linux-gnu/libc.so.6 | grep longjmp
   251: 00104a40   109 FUNC    GLOBAL DEFAULT   12 __longjmp_chk@@GLIBC_2.11
   319: 0002dbf0    95 FUNC    WEAK   DEFAULT   12 _longjmp@@GLIBC_2.0
  1031: 0002dbf0    95 FUNC    WEAK   DEFAULT   12 longjmp@@GLIBC_2.0
  1250: 0002dbf0    95 FUNC    WEAK   DEFAULT   12 siglongjmp@@GLIBC_2.0
  1715: 0002dbf0    95 FUNC    GLOBAL DEFAULT   12 __libc_siglongjmp@@GLIBC_PRIVATE
  2212: 0002dbf0    95 FUNC    GLOBAL DEFAULT   12 __libc_longjmp@@GLIBC_PRIVATE
```

Still no luck getting gdb to stop at a breakpoint on any of these though.

**Comment by vtjnash** [comment]
yield call `ctx_switch` directly.  you might have more success with a breakpoint there

**Comment by tkelman** [comment]
If I try to set a breakpoint for `ctx_switch` I get the same "pending on future shared library load" and the result's no different. spawn test starts running, I get the "[stdio passthrough ok]" message, then segfault with essentially the same backtrace as above, no stack when I ask for a backtrace.

**Comment by tkelman** [comment]
Rebased this on a whim, and hot damn this works now. I'll guess #9450 might be responsible for the fix?

Anyway, should we turn this on? Regular coverage of 32 bit Linux vs more builds on Travis?

**Comment by tkelman** [comment]
Unless anyone voices concerns about queue times on Travis I think it's worth covering another architecture here.

**Comment by StefanKarpinski** [comment]
+1. If need be, can we pay for more compute on Travis?

**Comment by tkelman** [comment]
That's a good question. Travis obviously has pro plans for running private repos, but I'm not sure if the hardware they run on is significantly better than the open-source plan.

One thing I had been meaning to look at was the Docker-based infrastructure, they only allow limited use of apt-get though so we'd have to grab our dependency libraries out of the generic Linux nightlies like we do on AppVeyor. And the level of installation of i386 packages I needed here is way beyond what they whitelist. I think our limiting factor has been OSX builds, rather than Linux builds or queue time anyway.

**Comment by andreasnoack** [comment]
:+1: to 32 bit Linux testing.

**Comment by StefanKarpinski** [comment]
I wonder if we can talk to them about paying for more compute instead of privacy.

**Comment by tkelman** [comment]
I should probably respond to an invitation they sent me to access one of their Slack channels and ask about this, we're timing out really often on OSX.

The OSX workers are physically hosted by a Sauce labs data center, and they're on pretty old hardware - Xeon E5620, or E5645, or X5650 according to `versioninfo()` from a few different builds. These are circa-2010 processors, probably hosting multiple VM's simultaneously. There may be some corner where Sauce labs keeps newer more powerful machines that they only let their paying customers use. Maybe also Travis' paying customers? Worth asking.

**Pull request merged**
