### PR TITLE
Add examples of functions that are not thread safe

### PR DESCRIPTION
**Pull request by bkamins**
A proposal following the discussion in #26006.

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
Thanks! Dealing with random numbers and threading probably deserves an entire section touching upon how to get independent number generators and initialising them correctly. Since you did that for https://github.com/bkamins/KissThreading.jl would you mind adding a section about the lessons learned from that?

**Comment by bkamins** [comment]
There are three separate issues here:
1. correct initialization of RNGs with `randjump` (and a discussion about reproducing of computation results) - this is relevant to parallel computing in general not only threading;
2. working around false sharing/NUMA issues that degrade the performance (but do not affect correctness);

Do you think they both have place in the manual? I am OK with adding both but I am not sure what is the intended scope of material in Julia Manual as:
1. For me the first point `randjump` is already documented - the issue is only how to use it correctly in multi-threading/multi-processing context;
2. For the second one - it is a general issue with threading not related to Julia in particular.

So I would like an opinion to include them both, the first one or none (probably including only the second one would not be very helpful).

A related issue is documenting how `@distributed`, `pmap` and `@threads` distribute work among workers which could be probably better described in the manual;

**Comment by vchuravy** [comment]
I personally think it would fine and even beneficial to include both of them, other parts of the manual dive into similar aspects.
I like the manual to be a place where people can learn about issues and how to best address them, especially since we can expect
to have folks that are not aware about `randjump` or the finer points of memory allocation and false sharing in a multi-threaded context.
And by explaining it to them, we prevent the "my code doesn't scale" moment. 

Generally speaking the manual is the place for longer and deeper discussion and the `Base` or `stdlib` docs are better suited for to the point examples.

**Comment by bkamins** [comment]
I have added examples how to solve the problems.

I would leave the false sharing issue from this PR. The memory layout of `MersenneTwister` has changed a bit between 0.6.2 and 0.7 and I do not get consistent results. I have to run more tests. When I am ready I would probably make another PR related to false sharing.

**Review by vchuravy — APPROVED** [review]

**Pull request merged**
