### PR TITLE
Super-tiny doc link update to io-network.rst

### PR DESCRIPTION
**Pull request by ohadle**

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @ohadle, you need to update the doctstring in the source file it originates from in `base/`, otherwise the next time someone runs `make docs`, your change will be overwritten.

**Comment by tkelman** [comment]
We also very strongly prefer that you open pull requests against master first, we will handle backporting to the release branch instead of going straight there.

**Comment by ohadle** [comment]
@kshyatt will do, thanks.
@tkelman np. This was opened while looking up something in the docs, noticing it and clicking "edit on github" to try and sort it out. I don't know if this is feasible, but maybe that button should be removed / changed to avoid non-master PRs in the future.
Come to think of it, I must have been on the "release-0.5" version of the docs to open it against that branch.

**Comment by kshyatt** [comment]
@ohadle If you've got any questions about how to make a doc pr, don't hesitate to ask for help! Remember to run `make docs` before you commit the change, as this will update the `.rst` for you.

**Pull request closed without merging**
