### PR TITLE
Make rowvector tests check for specific exception type

### PR DESCRIPTION
**Pull request by tkelman**
addresses https://github.com/JuliaLang/julia/pull/19670#discussion_r96156813, cc @andyferris

and line wrap

### CODE REVIEW

**Comment by andyferris** [comment]
Thanks Tony. FYI This was already addressed in my follow-up PR #20047 (but I'm happy to rebase on this, especially for the improved formatting)

**Comment by tkelman** [comment]
whoops, didn't notice, did you add that in the most recent rebase or did I completely miss it earlier?

**Comment by andyferris** [comment]
It was last night, so about 18 hours ago, which I think is also the most recent rebase.

**Comment by Sacha0** [comment]
@tkelman, would you like review on this pull request, or do you plan to close it in favor of the similar changes in #20047? Best!

**Comment by andyferris** [comment]
Merging this first would be fine with me. It looks good to me.

(does a +1 on the OP of a simple PR count as LGTM?)

**Comment by tkelman** [comment]
okay, if @andyferris doesn't mind rebasing then may as well merge this one now

**Pull request merged**
