### PR TITLE
[LinearAlgebra] Correct `liblapack`  binding

### PR DESCRIPTION
**Pull request by lkapelevich**
addresses https://github.com/JuliaLang/julia/pull/39845#issuecomment-805828626

### CODE REVIEW

**Comment by fredrikekre** [comment]
`liblapack` was defined in `LinearAlgebra.BLAS` too, so I think that one should be kept.

**Comment by ViralBShah** [comment]
I suppose ideally we should remove the `liblapack` from `LinearAlgebra.BLAS`, but are we retaining it because things might depend on it?

**Comment by fredrikekre** [comment]
Yes, I thought that was the point of https://github.com/JuliaLang/julia/pull/39845.

**Comment by ViralBShah** [comment]
> Yes, I thought that was the point of #39845.

Yes, that is right. I just looked, and we do have `liblapack` currently defined in blas.jl on release-1.6. I am guessing it would be ok to move it to the LAPACK module and most likely will lead to very little breakage. Most packages care about BLAS and overriding it and much less so with LAPACK. 

What do you think about having only libblas in blas.jl, and liblapack in lapack.jl - and then running the pkgeval to see how breaking it is?

**Comment by fredrikekre** [comment]
Sure, but costs nothing to keep them. Doesn't even seem like they had to be renamed in the first place.

**Comment by KristofferC** [comment]
I don't think this is relevant for 1.6?

**Pull request merged**
