### PR TITLE
🤖 Bump the SuiteSparse stdlib from b15c39b to f1cc473

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SuiteSparse
URL: [https://github.com/JuliaLang/SuiteSparse.jl](https://github.com/JuliaLang/SuiteSparse.jl)
Branch: master
Old commit: b15c39b
New commit: f1cc473
Bump invoked by: @ViralBShah
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline b15c39b..f1cc473
f1cc473 Merge pull request #49 from JuliaLang/vs/win64-clong
5c625f5 Fix LONG_MAX to be typemax(Clonglong) for Win64
```

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
Don't merge this yet. Something went wrong when updating the checksums.

**Comment by ViralBShah** [comment]
@DilumAluthge Why is it deleting all the checksums?

**Comment by ViralBShah** [comment]
The other bigger issue is - how do we know if this truly fixes the suitesparse crashes?

**Comment by DilumAluthge** [comment]
@vtjnash @staticfloat What is the correct way to update the checksums here?

For context, here is what the BumpStdlibs.jl bot currently does when the user asks to update the SuiteSparse.jl stdlib:
1. Delete the old checksum files.
2. Run the following command: `make -f contrib/refresh_checksums.mk libsuitesparse`

**Comment by DilumAluthge** [comment]
> The other bigger issue is - how do we know if this truly fixes the suitesparse crashes?

Since it's non-deterministic, and only happens a small percentage of the time.... we don't. Best we can do is merge it (if all CI jobs pass) and wait to see if we stop seeing the segfaults.

**Comment by ViralBShah** [comment]
I believe that is the right way (or at least documented somewhere). If you run the script again, it will get you all the platform binaries and not the source ones. If you run it again, it will get you the source files and not the platforms. I was quite frustrated with the script yesterday, and manually created the checksum file. You can probably see multiple pushes in the openblas bump PR.

**Comment by DilumAluthge** [comment]
> If you run the script again, it will get you all the platform binaries and not the source ones. If you run it again, it will get you the source files and not the platforms.

I've opened an issue: #42727

**Comment by ViralBShah** [comment]
Should this be closed and a new PR created when the issue is fixed?

**Comment by DilumAluthge** [comment]
We can leave it open as a reminder to ourselves, but convert it to a draft so we don't accidentally click the merge button.

**Pull request closed without merging**
