### PR TITLE
[release-0.4, WIP]: backports for 0.4.3

### PR DESCRIPTION
**Pull request by tkelman**
Just starting on the already-labeled pending backports. Will run PkgEval once I finish putting more of them here. If there's anything that doesn't yet have the backport pending label on it that you think would be a good candidate, please point it out with a comment here.

Not yet here, but considering them:
- [ ] #13803 
- [x] #14372
- [x] #14293

### CODE REVIEW

**Comment by tkelman** [comment]
This is more failures than I normally expect during a backport PackageEvaluator run, these each need looking into: https://gist.github.com/625c0de67ede8cb9e21c

- AverageShiftedHistograms
- Cbc
- DictFiles
- EEG
- FixedPointNumbers
- FunctionalData
- Gadfly
- Jags
- JuMPChance
- JuMPeR
- Mamba
- Stan

**Comment by tkelman** [comment]
All fixed locally by reverting #14301, rerunning pkgeval again just to be sure. @yuyichao what's up with that?

**Comment by nalimilan** [comment]
+1 from me, the Fedora/EPEL RPM build fine with this PR.

**Comment by tkelman** [comment]
These are all intermittent https://gist.github.com/2ebb226d3c549dfd8238

Merging, will tag later today.

**Pull request merged**
