### PR TITLE
Update command-line-interface.md

### PR DESCRIPTION
**Pull request by Jay-sanjay**
I have mentioned the missing argument  in Command-line Interface page.

### CODE REVIEW

**Comment by Jay-sanjay** [comment]
Sir I have made the changes please check if it could be merged .

**Comment by prbzrg** [comment]
Closes #50588

**Comment by prbzrg** [comment]
Why didn't this merge?

**Comment by Jay-sanjay** [comment]
@prbzrg  I guess, I closed it by mistake earlier, so can it merged now

**Comment by PallHaraldsson** [comment]
I'm ok with this merged (as is). The MemBalancer is no longer in, that I hoped would make this redundant (maybe later when back in). I read "Forces garbage collection" as doing that ensuring staying within limit, but it only means does the GC, and it might still end up over the limit.

**Comment by prbzrg** [comment]
It's a copy from
https://github.com/JuliaLang/julia/blob/ef3bf66d5e1d60c9b604eb6e01539eb1c3aced90/doc/man/julia.1#L225-L227
so any changes should apply to both.

**Comment by Jay-sanjay** [comment]
bump.

**Comment by fingolfin** [comment]
Duplicate of PR #50480

**Pull request closed without merging**
