### PR TITLE
libuv upgrade to v2-1.39.0

### PR DESCRIPTION
**Pull request by vtjnash**
~~Needs https://github.com/libuv/libuv/issues/2838 still, but I don't have a clean version of that change to apply. @staticfloat can you make a PR to libuv that I can use as the reference patch?~~
```
* 87d3a78a - Remove incorrect constant in chmod (#12) (5 weeks ago) <Elliot Saba>
*   2d109120 - Merge pull request #10 from JuliaLang/sf/inheritance (4 months ago) <Elliot Saba>
|\  
| * 2b839f1c - Alter permissions given in chmod (4 months ago) <Elliot Saba>
|/  
*   183e5558 - Merge pull request #9 from JuliaLang/sf/readonly_chmod (4 months ago) <Elliot Saba>
|\  
| * 3e3e203c - Propagate permissions, and fix readonly permission ordering (4 months ago) <Elliot Saba>
* | b5bf0b87 - Merge pull request #8 from JuliaLang/sf/readonly_chmod (4 months ago) <Elliot Saba>
|\| 
| * 62808ca2 - win,fs: Continue to set `FILE_ATTRIBUTE_READONLY` (4 months ago) <Elliot Saba>
|/  
*   659812b7 - Merge pull request #6 from JuliaLang/sf/win_acl (4 months ago) <Elliot Saba>
|\  
| * 173a9acb - Fix c89 pedantic warnings (4 months ago) <Elliot Saba>
| * 3ce845cd - win,fs: Add more complete `fs__chmod()` implementation (4 months ago) <Elliot Saba>
| * ce539ac6 - win,fs: Upgrade `fs__access()` to respond to `X_OK`. (8 months ago) <Elliot Saba>
```

### CODE REVIEW

**Comment by musm** [comment]
Awesome, thanks for doing this.

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/blob/master/test/file.jl#L544
```
-    for i = 0:8
+    for i = 0:9
         local tmp = joinpath(PATH_PREFIX, "x"^MAX_PATH * "123456789"[1:i])
         @test withenv(var => tmp) do
             tempdir()
         end == (tmp)
     end
-    for i = 9
-        local tmp = joinpath(PATH_PREFIX, "x"^MAX_PATH * "123456789"[1:i])
-        if Sys.iswindows()
-            # libuv bug
-            @test_broken withenv(var => tmp) do
-                tempdir()
-            end == tmp
-        else
-            @test withenv(var => tmp) do
-                tempdir()
-            end == tmp
-        end
-    end
```

**Review by musm — APPROVED** [review]

**Comment by JeffBezanson** [comment]
generate_precompile seems to hang for me after this.

**Comment by staticfloat** [comment]
On which platform?  Can you switch [this debug out](https://github.com/JuliaLang/julia/blob/master/contrib/generate_precompile.jl#L124) to `stdout` and see where it's hanging?

**Comment by JeffBezanson** [comment]
Ah, looks like a segfault during addprocs:
```
julia> addprocs(2)

signal (11): Segmentation fault
in expression starting at REPL[17]:1
macro expansion at ./libuv.jl:38 [inlined]
uv_connectcb at /home/jeff/src/julia/usr/share/julia/stdlib/v1.6/Sockets/src/Sockets.jl:477
unknown function (ip: 0x7f3401817655)
uv__stream_connect at /workspace/srcdir/libuv/src/unix/stream.c:1381
uv__stream_io at /workspace/srcdir/libuv/src/unix/stream.c:1298
uv__io_poll at /workspace/srcdir/libuv/src/unix/linux-core.c:447
uv_run at /workspace/srcdir/libuv/src/unix/core.c:379
jl_process_events at /home/jeff/src/julia/src/jl_uv.c:214
process_events at ./libuv.jl:104 [inlined]
wait at ./task.jl:747 [inlined]
wait at ./condition.jl:106
_trywait at ./asyncevent.jl:111
wait at ./asyncevent.jl:129 [inlined]
sleep at ./asyncevent.jl:214
read_worker_host_port at /home/jeff/src/julia/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl:318
```
The handle data looks corrupt; `data` is `0x56415741e5894855`.
Linux x86_64.

**Pull request merged**
