### PR TITLE
Add option for readdir to prepend the relative or absolute path

### PR DESCRIPTION
**Pull request by tamasgal**
This is a simple implementation of the feature request created by @yakir12 in #29309 after discussing it on https://discourse.julialang.org/t/readdir-return-full-path/15274?u=yakir12

### CODE REVIEW

**Comment by tamasgal** [comment]
Unfortunately I am not able to run the test suite (I get segmentation faults) so there are no unit tests yet until I figure out what's going on.

**Comment by StefanKarpinski** [comment]
I'm not really into this change. The `readdir` function does one very simple thing: it reads the contents of a directory, which is a vector of the names in that directory. Yes, you can do all sorts of complicated stuff with that, but that's up to you.

**Comment by yakir12** [comment]
So you feel that adding that option over-complicates `readdir`?

**Comment by tamasgal** [comment]
Well, I have never used `readdir()` to just retrieve a list of filenames in a given directory. I always use it to directly work with the files (e.g. in mass processing), so I need the full path (relative or absolute, doesn't matter). I think that most of the people who liked that idea do the same.

I know that one can use `Glob`, but that would be an additional dependency.

**Comment by StefanKarpinski** [comment]
> So you feel that adding that option over-complicates readdir?

Yes. Note that the C function [by the same name](https://linux.die.net/man/3/readdir) and the Python [`os.listdir`](https://docs.python.org/3/library/os.html#os.listdir) function have the same behavior.

**Comment by tamasgal** [comment]
OK, let's close this then!

**Comment by StefanKarpinski** [comment]
Something about closing this kept nagging at me—after all, it is often more convenient to get joined paths or absolute paths. One of the things that bothers me about this proposed API is that it's non-orthogonal: if you set `abspath=true` then the `join` option no longer matters. So I've opened https://github.com/JuliaLang/julia/pull/33113 as an alternative that only introduces `join` and doesn't add the `abspath` option. Instead you can get absolute paths by passing an absolute directory name and asking for joined names.

**Comment by yakir12** [comment]
Win win!

**Comment by tamasgal** [comment]
Nice! I like #33113, I am totally fine with the join-functionality only ☺️

**Comment by rfourquet** [comment]
> Something about closing this kept nagging at me

Same for me and I wanted to look closer at this but you reacted faster, nice!

**Pull request closed without merging**
