### PR TITLE
optimizer: skip post-opt IPO analysis when effects are precise already

### PR DESCRIPTION
**Pull request by aviatesk**
Should give us some performance optimization.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51188#issuecomment-1706268469) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/28393ce_vs_fc2f997/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51188#issuecomment-1706942458) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/5673d16_vs_78e0ca3/report.md).

**Comment by vtjnash** [comment]
Did I mess up the merge commit? Why is that not better anymore

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/51188#issuecomment-1707713943) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/7f9897b_vs_14c5f3d/report.md).

**Pull request merged**
