### PR TITLE
Replace inf by Inf in MPFR string output

### PR DESCRIPTION
**Pull request by dpsanders**
Currently (e.g. Julia 0.4):

``` julia
julia> BigFloat(Inf)
inf
```

After this PR:

``` julia
julia> BigFloat(Inf)
BigFloat(Inf, 256)

julia> BigFloat(-Inf)
BigFloat(-Inf, 256)

julia> BigFloat(NaN)
BigFloat(NaN, 256)

```

### CODE REVIEW

**Comment by tkelman** [comment]
I'd rather show this as `BigFloat(Inf)` or similar so at least it's distinguishable from the default Float64 case.

**Comment by dpsanders** [comment]
That's a good idea. 

But doesn't it raise a bigger issue, namely the distinction made, for example in Python, between the "representation" of an object (a version that will recreate a copy of the object when pasted into the REPL) and the pretty-printed version which is a nicer-looking version?

This seems to be related to #7959

**Comment by stevengj** [comment]
When there is a distinction, `writemime(io, ::MIME"text/html", x)` is the pretty-printed version and `show(io, x)` (called by `print` and `repr`) is the repr-like version.

**Comment by tkelman** [comment]
Though even pretty-printing should probably try to avoid easily confusable output if it can.

**Comment by kshyatt** [comment]
Are we going to change the output to contain `BigFloat`, or is this ok as-is?

**Comment by tkelman** [comment]
I'd prefer having some way of distinguishing the output between normal `Float64` `Inf` and `BigFloat(Inf)`

**Comment by StefanKarpinski** [comment]
I'd be on board with printing `big(Inf)`. Of course, you still don't know how many bits.

**Comment by dpsanders** [comment]
With #13155, we could print `BigFloat(Inf, 256)` for a `BigFloat` `Inf` with precision of 256 (binary) digits. It's noisy, but precise.

I would prefer `big(Inf, 256)`, but this syntax was not liked by @stevengj and @simonbyrne (see #13155).

A new option would be to introduce a `bigf` function, which would convert *anything* to a `BigFloat`. [This compares with `big(2)`, which produces a `BigInt`;  `bigf(2)` would rather give `BigFloat(2.0)`. ]

This would then allow expressions like `bigf("3.1", 128)` to mean the equivalent of `big"3.1"`, having set the precision to 128. [Note that there still would be no easy way to express this number, even after #13155, since `BigFloat(3.1, 128)` converts `3.1` to `Float64` before the conversion to `BigFloat` occurs.)

**Comment by stevengj** [comment]
Note that this PR doesn't handle `big(-Inf)`.

**Comment by dpsanders** [comment]
Made a mess. Closing in favor of #19939 .

**Comment by yuyichao** [comment]
Seems that we've just lost the biggest PR ever ;-p

**Comment by dpsanders** [comment]
How to make a big mess with a rebase, without really trying... :/

**Pull request closed without merging**
