### PR TITLE
؜

### PR DESCRIPTION
**Pull request by ghost**
؜

### CODE REVIEW

**Comment by KristofferC** [comment]
Although tempting, maybe we should try for a bit longer.

**Comment by printbf** [comment]
enjoy that suffering man

**Comment by timholy** [comment]
It would be a smaller code base to maintain...

**Comment by rfourquet** [comment]
... and fix the latency problem ...

**Comment by timholy** [comment]
<a href="https://imgflip.com/i/4k9qec"></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Pull request closed without merging**
