### PR TITLE
julia-mode: Add space to prompt regexp

### LINKED ISSUE #14002: julia-mode.el: please fix julia-mode-regexp
Please change `julia-prompt-regexp` to `"julia> "` (note the space at the end).  Otherwise M-p does not work.

### PR DESCRIPTION
**Pull request by justbur**
Fixes #14002

### CODE REVIEW

**Comment by yuyichao** [comment]
LGTM, is there a way to test this other than checking for the content of `julia-prompt-regexp`?

**Comment by justbur** [comment]
I looked into the problem from that bug report a bit and the issue is related to emacs repositioning the cursor to the wrong place. For `M-p` to work the point has to be at the end of the buffer (after the space inserted by the command prompt), but the regexp used was telling comint that there is no space after the prompt. If you move the point one char to the right `M-p` works again because the point is in the right place.

Besides simulating the problem, I don't see an easy way to test this at the moment. We just want the output from the process, which does have the extra space, to be consistent with the regexp.

**Comment by justbur** [comment]
fwiw ess-julia uses this regexp `"^\\w*> "`

**Comment by yuyichao** [comment]
I think julia-mode currently doesn't really support other REPL mode (`help?> `, `shell> `, etc) but using `"^\\w*> "` should be better anyway.

**Comment by justbur** [comment]
ok, let me change it

**Comment by justbur** [comment]
ok, I fixed it. I just amended the commit. Hope that's ok

**Comment by yuyichao** [comment]
> I just amended the commit

Yep, this is the preferred way of updating a pull request.

**Comment by yuyichao** [comment]
Verified locally that this works. If someone can come up with an easy way to test this against the output of the julia REPL we can always add it later =).

**Comment by justbur** [comment]
Sounds good. Thanks

**Pull request merged**
