### PR TITLE
[WIP] Introducing libuv global lock on master

### PR DESCRIPTION
**Pull request by anton-malakhov**
As title
Partially replaces #29606 (removing kp/partr specifics)

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Out of curiosity, why not just continue it there?

**Comment by anton-malakhov** [comment]
I rebased it against master and wanted to keep original branch name for kp/partr-based branch there. GitHub does not allow changing source branch in a PR. If I'd retarget that PR to master 1) I'd loose few partr-specific changes which I can just keep in that branch and 2) it would look like if I want to merge kp/partr :)

**Comment by StefanKarpinski** [comment]
> GitHub does not allow changing source branch in a PR.

It does: click Edit and then choose a different base branch.

**Comment by anton-malakhov** [comment]
I know it allows to change base branch but I said it does not allow changing source branch.

**Comment by StefanKarpinski** [comment]
Closes issue https://github.com/JuliaLang/julia/issues/14494.

**Comment by c42f** [comment]
It looks like @yuyichao already reviewed this (partially? fully?) over at #29606.

Is the plan still to merge this before merging the other more PARTR-specific work? If so, what's holding it up and would it benefit from another review?

**Comment by anton-malakhov** [comment]
He made good point on not using `JL_LOCK_NOGC`. However, it never worked for me the easy way, triggering some bug or a problem during bootstrap. I'll be glad if somebody will take over this patch since my work is no longer connected to supporting development of multi-threading in Julia-lang

**Comment by c42f** [comment]
Ah that's a real shame. I could possibly pick it up. No promises yet though, I'll have to see what's involved.

@vtjnash what's your take on the order this stuff should get merged?

**Comment by StefanKarpinski** [comment]
> @vtjnash what's your take on the order this stuff should get merged?

In a recent compiler call we discussed this and his take was that this is completely independent of the other multithreading work. It can happen before or after—it just affects whether calling I/O from different Julia threads is safe or not, which is an issue now and would still be an issue after the other threading PRs are merged as well.

**Comment by JeffBezanson** [comment]
Rebased as #31437.

**Pull request closed without merging**
