### PR TITLE
add support for inlining :invoke exprs

### PR DESCRIPTION
**Pull request by JeffBezanson**
Currently the inlining pass is in charge of producing `:invoke` exprs, but is expected to run only once and so it can't consume them. In e.g. Diffractor.jl, optimized IR is transformed and then fed back in to optimization passes, so inlining needs to be able to handle these expressions. I should add a test but it's a bit tricky since nothing like this happens in Base yet.

### CODE REVIEW

**Comment by aviatesk** [comment]
> I should add a test but it's a bit tricky since nothing like this happens in Base yet.

I think I can write a test for this.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/46606#issuecomment-1263362391) failed.

**Comment by vtjnash** [comment]
```
      From worker 3:    ERROR: LoadError: unable to find single target method for Tuple{typeof(Core.Compiler.abstract_call_gf_by_type)
, Core.Compiler.NativeInterpreter, Any, Core.Compiler.ArgInfo, Any, Core.Compiler.InferenceState, Int64}                              
      From worker 3:    Stacktrace:                                                                                                   
      From worker 3:      [1] error(s::String)                     
      From worker 3:        @ Base ./error.jl:35                   
      From worker 3:      [2] get_single_method_match(tt::Any, lim::Int64, world::UInt64)                                             
      From worker 3:        @ BaseBenchmarks.InferenceBenchmarks /home/nanosoldier/.julia/dev/BaseBenchmarks/src/inference/InferenceBe
nchmarks.jl:82
      From worker 3:      [3] #inf_gf_by_type!#3                   
      From worker 3:        @ /home/nanosoldier/.julia/dev/BaseBenchmarks/src/inference/InferenceBenchmarks.jl:74 [inlined]
      From worker 3:      [4] inf_call(f::Any, types::Any; interp::BaseBenchmarks.InferenceBenchmarks.InferenceBenchmarker, run_optimi
zer::Bool)
      From worker 3:        @ BaseBenchmarks.InferenceBenchmarks /home/nanosoldier/.julia/dev/BaseBenchmarks/src/inference/InferenceBe
nchmarks.jl:121
      From worker 3:      [5] #abs_call#10                         
      From worker 3:        @ /home/nanosoldier/.julia/dev/BaseBenchmarks/src/inference/InferenceBenchmarks.jl:129 [inlined]
      From worker 3:      [6] abs_call(f::Any, types::Any)                                                                            
      From worker 3:        @ BaseBenchmarks.InferenceBenchmarks /home/nanosoldier/.julia/dev/BaseBenchmarks/src/inference/InferenceBe
```

**Comment by vtjnash** [comment]
Probably broken by https://github.com/JuliaLang/julia/commit/90dbc5daf77f0a3e08b3365fb8d3fd7295c1c027?

**Comment by aviatesk** [comment]
Thanks, should be fixed by https://github.com/JuliaCI/BaseBenchmarks.jl/pull/302.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46606#issuecomment-1264129021) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/559ec7b_vs_02574e3/report.md).

**Comment by aviatesk** [comment]
No regression detected. This seems good to go from my side.

**Pull request merged**
