### PR TITLE
[LLVMLibUnwindJLL] Update llvmlibunwind to 14.0.6

### PR DESCRIPTION
**Pull request by gbaraldi**

### CODE REVIEW

**Comment by giordano** [comment]
You probably have to update the from source build, building standalone llvm unwind won't work

**Comment by gbaraldi** [comment]
Not sure I follow you, the from source build is in unwind.mk. And it gets the LLVMUNWIND_VER variable.

**Comment by giordano** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/pull/6041

**Comment by vtjnash** [comment]
IIUC, you are meaning that the options changed slightly, and the new ones need to be copied over from that PR?

**Comment by gbaraldi** [comment]
The build does work, but I'm not being able to refresh the checksums 🤔

**Comment by fingolfin** [comment]
This PR has conflicts now. OTOH the JLL was updated just for it (already two years ago).

I wonder how much effort should be put into this, for that it'd be good to know the motivation: is the hope that the new version resolves known issues (which?), improves performance (?), or something like that? Or is it just about getting a new version in for its own sake (in the hope of benefiting from all kinds of improvements they have made, and with the hope that no serious regressions result). 

Of course esp. in the latter case one might then also wonder whether to now switch to an even newer version?

**Comment by ViralBShah** [comment]
Close (since we have moved on to much newer LLVMs)?

**Comment by vchuravy** [comment]
>Close (since we have moved on to much newer LLVMs?

Moving to a new version of LLVM doesn't impact libunwind 

```
vchuravy@loki ~/s/julia (master)> cat deps/llvmunwind.version
## jll artifact
LLVMUNWIND_JLL_NAME := LLVMLibUnwind

## source build
LLVMUNWIND_VER := 12.0.1

```

**Comment by IanButterworth** [comment]
Reviving this as a stepping stone to get to newer versions, in the hope that we can fix the detatched samples we're seeing on macOS arm (and linux aarch64).

Screenshot 2024-09-05 at 12 39 54 PM

**Comment by IanButterworth** [comment]
And hoping to fix https://github.com/JuliaLang/julia/issues/53816
```
ld: warning: reexported library with install name '@rpath/libunwind.1.dylib' found at '/Users/ian/Documents/GitHub/julia/usr/lib/libunwind.1.0.dylib' couldn't be matched with any parent library and will be linked directly
```

**Comment by IanButterworth** [comment]
Seems updating the checksums is breaking checksums on other platforms
```
% make -f contrib/refresh_checksums.mk llvmunwind
making /Users/ian/Documents/GitHub/julia/deps/checksums/llvm.*unwind
rm "/Users/ian/Documents/GitHub/julia/deps/checksums"/'llvmunwind'
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=0 FC_VERSION=7.0.0 LLVMUNWIND_BB_TRIPLET= LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=aarch64-apple-darwin LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=aarch64-linux-gnu LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=aarch64-linux-musl LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=armv6l-linux-gnueabihf LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=armv6l-linux-musleabihf LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=armv7l-linux-gnueabihf LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=armv7l-linux-musleabihf LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=i686-linux-gnu LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=i686-linux-musl LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=i686-w64-mingw32 LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=powerpc64le-linux-gnu LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=x86_64-apple-darwin LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=x86_64-linux-gnu LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=x86_64-linux-musl LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=x86_64-unknown-freebsd LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
/Library/Developer/CommandLineTools/usr/bin/make -s -C "/Users/ian/Documents/GitHub/julia/deps" USE_BINARYBUILDER=1  LLVMUNWIND_BB_TRIPLET=x86_64-w64-mingw32 LLVM_ASSERTIONS=0 DEPS_GIT=0 checksum-llvmunwind
cd "/Users/ian/Documents/GitHub/julia/deps/checksums" && mv 'llvm.*unwind' llvmunwind
```

**Comment by IanButterworth** [comment]
Following the checksum instructions in https://github.com/JuliaLang/julia/pull/42643#issue-1026059597 doesn't seem to produce the right checksums... but giving it a go
```
make -f contrib/refresh_checksums.mk unwind
make -f contrib/refresh_checksums.mk llvmunwind
```

**Review by IanButterworth — APPROVED** [review]

**Comment by IanButterworth** [comment]
For me this doesn't solve the detached profiling samples issue nor https://github.com/JuliaLang/julia/issues/53816 but seems like a good step to take for now, pending https://github.com/JuliaPackaging/Yggdrasil/pull/9241

**Pull request merged**
