### PR TITLE
Resolves #14889

### LINKED ISSUE #14889: File and line number reporting in errors and warnings is inconsistent
Most editors can be configured to parse strings like `filename.txt:23` and automatically open the file with the cursor at the correct line. This format is somewhat standard, sometimes including the column number too as in `filename.txt:23:5`. This can be used in conjunction with terminal emulators, allowing ctrl-clicking the `filename:line` to jump to that location in the default editor.

Julia sometimes uses this `filename:line` format for reporting errors, and sometimes not, often in the same output:

```
ERROR: LoadError:
 in error at error.jl:22
 in include at .../julia/0.4.2/lib/julia/sys.dylib
 in include_from_node1 at .../julia/0.4.2/lib/julia/sys.dylib
 in process_options at .../julia/0.4.2/lib/julia/sys.dylib
 in _start at .../julia/0.4.2/lib/julia/sys.dylib
while loading example.jl, in expression starting on line 11
```

which breaks the system described above; line numbers have to be typed manually.

I suggest a change to instead print the final line above as

```
while loading example.jl:11
```

### PR DESCRIPTION
**Pull request by 315234**
Resolves #14889

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks! Looks good to me, but it would be nice to use a more explicit commit message.

**Comment by 315234** [comment]
Sorry, I don't do this very often. Should I edit the description on the pull request or edit the original commit message and create a new request?

**Comment by vchuravy** [comment]
@315234, best thing to do is to change the commit message locally (with rebase) and then update this pull request by force pushing onto it.

I would do that with:
```
git fetch origin
git rebase -i origin/master
# Replace pick with edit
git push -f
```

**Comment by 315234** [comment]
Thanks @vchuravy. I _think_ I managed it...

**Comment by nalimilan** [comment]
Indeed it worked . Note that in general it's better (for you) to work on a separate branch, and keep master clean.

**Comment by KristofferC** [comment]
Rerun CI, is people still of the opinion that this should be merged. I like it.

**Comment by JeffBezanson** [comment]
Yeah, fine with me.

**Comment by iamed2** [comment]
I'm worried that without "while loading" there's not enough to distinguish this from the rest of the stack trace anymore.

**Pull request merged**
