### PR TITLE
Documentation System

### PR DESCRIPTION
**Pull request by MikeInnes**
A metadata system for global objects + pretty markdown parsing and display (see the [readme](https://github.com/one-more-minute/Markdown.jl)). For example:

``` julia
@doc """
... flowing rivers of technical poetry ...
""" ->
function foo() ...
```

Documenting multiple methods of a function will concatenate the doc strings together, in the order the methods were originally defined, and this is overloadable.

By default `@doc` treats unadorned strings as equivalent to `md""` (i.e. markdown syntax) but you can actually put anything before the arrow to associate it with the function.

Docs can be queried with e.g.

``` julia
doc(Docs.doc)
@doc Docs.doc
@doc @doc # For macros
@doc text""
```

(and you can try these out on this branch – the repl help key `?` will work too)

General Todos:
- [ ] Prettier syntax (`"..."` -> `@doc doc"..." ->`)
- [ ] Add `Docs.@init` call to module init code
- [x] REPL `?` integration
- [x] Make sure exports are present and correct
- [ ] Move away from the current help system and deprecate it
- [ ] Fix the segfault when `Text` docs are uncommented (!?)

### CODE REVIEW

**Comment by ViralBShah** [comment]
Pushing forward on completing the transition - it seems that the next step is to transition `help` to the new documentation system.

Does this mean that our standard library documentation should be translated to Markdown first to leverage the new system best? This may not work best with readthedocs - does it have to use rst?

**Comment by one-more-minute** [comment]
I think readthedocs requires RST, yes. That said, we already have our own docs template and website, so I'm not sure readthedocs really buys us that much – @MichaelHatherly has done a lot of work on generating great documentation pages and might be interested in helping us move away from it entirely.

OTOH, it wouldn't be hard to generate RST manual pages from the inline docs using Markdown.jl, so that's another option.

The important thing is to have *some* way to share content between Base docs and the manual – otherwise there'll be a lot of repeated work.

**Comment by MichaelHatherly** [comment]
There's also http://www.mkdocs.org/, which @tshort has been using recently (https://tshort.github.io/Sims.jl/) in conjunction with Docile.

**Comment by ViralBShah** [comment]
I was thinking the same about readthedocs. The manual and Base docs should just be equally accessible, but they don't share much of anything. They can be done in different ways without impacting anything, I feel.

mkdocs looks really cool!

**Comment by tshort** [comment]
Embedded Docile/Base 0.4 docs can be used with Mkdocs and published on either readthedocs or GitHub Pages. It's really easy.

Github Pages works great with Mkdocs. I haven't tried it, but one advantage of readthedocs is it provides online searching.

**Pull request merged**
