### PR TITLE
Clarify how to select items in a terminal MultiSelectMenu

### PR DESCRIPTION
**Pull request by BenPH**
It wasn't obvious to me how to make selections in a MultiSelectMenu. I think this could help.

### CODE REVIEW

**Comment by timholy** [comment]
It definitely helps. Some thoughts:
- Enter is a toggle (you can also deselect an item that you previously selected). I am not sure how to convey this briefly
- grouping Enter with 'a' and 'n' makes sense since they are all about selection
- should we also mention 'q'?

**Comment by fredrikekre** [comment]
Maybe `q=abort` is clearer?

**Comment by BenPH** [comment]
Thanks for the suggestions all. I've made an update.

**Review by fredrikekre — APPROVED** [review]

**Comment by timholy** [comment]
Thanks @BenPH!

**Pull request merged**
