### PR TITLE
allow assigment to Pair (e.g., `k=>v = 1,2`)

### PR DESCRIPTION
**Pull request by nolta**
``` julia
julia> for k=>v in Dict(1=>2,3=>4)
           println("$k $v")
       end
3 4
1 2
```

### CODE REVIEW

**Comment by ivarne** [comment]
Such a niche little change. Too bad we've just marked feature freeze.

Maybe we can we  call this a bug fix?

**Comment by ScottPJones** [comment]
This might not work, depending on if/how @JeffBezanson changes the precedence of `=>`.
It should still work if he adds a new precedence level, with `=>` above assignment operators, but he was leaning towards not wanting a new level.  This is a good example of why a separate level would be useful.

**Comment by JeffBezanson** [comment]
This is breaking, since the syntax `(a=>b) = x` currently adds a method to `=>`. This is how all operators behave, so this would be the one exception. So fairly controversial I think.

**Comment by jakebolewski** [comment]
i don't like this idea.  I think we should err on the side of destructing rules being fairly simple.

**Comment by ScottPJones** [comment]
Also, since
```julia
for (k,v) in Dict(:x => 1, :y => 2) ; println("$k $v") ; end
```
works just fine, what's the benefit?

**Comment by jakebolewski** [comment]
Exactly

**Pull request closed without merging**
