### PR TITLE
[LibCURL_jll] Update to v7.88.1

### PR DESCRIPTION
**Pull request by fxcoudert**
Will need to be updated after https://github.com/JuliaRegistries/General/pull/78555 is merged

### CODE REVIEW

**Comment by fxcoudert** [comment]
I don't understand this error:

```
ERROR: The working directory is dirty.
--
  | Output of git status:
  | HEAD detached at 4d3d993cb21
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  |  
  | deps/checksums/LibCURL-fd8af649b38ae20c3ff7f5dca53753512ca00376.tar.gz/
```

**Comment by DilumAluthge** [comment]
You'll need to refresh the checksums.

Something like this should work:

```
make -f contrib/refresh_checksums.mk curl
```

**Comment by fxcoudert** [comment]
> make -f contrib/refresh_checksums.mk curl

I have done that, it's the second commit. It put things in `deps/checksums/curl` not that other path. I've tried `make -f contrib/refresh_checksums.mk LibCURL` but it's not the right command.

**Comment by DilumAluthge** [comment]
I can never remember the right incantation for refreshing the checksums.

@giordano or @vtjnash will probably know.

**Comment by giordano** [comment]
The changes look good to me at a first glance, they are the same as #45967, no? But I'm on the phone, can't check very carefully

**Comment by fxcoudert** [comment]
I see the issue now: the two lines at the top of the checksum file:

```
LibCURL-fd8af649b38ae20c3ff7f5dca53753512ca00376.tar.gz/md5/f082283e6a35fcba5b63c9a6219d8003
LibCURL-fd8af649b38ae20c3ff7f5dca53753512ca00376.tar.gz/sha512/3bea5fa3fb6d29651daa923ae6bcb8eeb356ab9f2a1f3e005a6b746b617b0cf609aed4cadda4181783959840873c04b18e34e45ab973549169d19775a05ea01e
```

are removed but not replaced. I do not know why, because this is autogenerated by `make -f contrib/refresh_checksums.mk curl`

**Comment by fxcoudert** [comment]
The revision in question comes from:

```
$ cat stdlib/LibCURL.version 
LIBCURL_BRANCH = master
LIBCURL_SHA1 = fd8af649b38ae20c3ff7f5dca53753512ca00376
LIBCURL_GIT_URL := https://github.com/JuliaWeb/LibCURL.jl.git
LIBCURL_TAR_URL = https://api.github.com/repos/JuliaWeb/LibCURL.jl/tarball/$1
```

which is not touched by my patch (and I do not think it should be).

**Comment by giordano** [comment]
Ah, I think those are from the LibCURL stdlib, i.e. a lightweight wrapper around the binary library provided by the jll package. Perhaps we're putting too much stuff into a single file if the checksums can't be updated correctly.

**Comment by fxcoudert** [comment]
History of the previous PR (https://github.com/JuliaLang/julia/pull/45967) showed that you had force-pushed to re-add the two lines. I'm restoring them manually and pushing.

**Comment by fxcoudert** [comment]
```
Downloads                                        (2) \|         failed at 2023-02-26T12:43:29.335
--
  | Test Failed at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/julia-59079520dc/share/julia/stdlib/v1.10/Downloads/test/runtests.jl:230
  | Expression: any(events) do (type, msg)
  | type == "TEXT" && startswith(msg, "Connected to ")
  | end
```

Maybe related, but it only fails on some platforms. No idea why, or what was offending message.

**Comment by giordano** [comment]
The offending message is
```
msg = "Couldn't find host httpbingo.julialang.org in the (nil) file; using defaults\n"
```
I can reproduce the error by running the `Downloads` testsuite with
```
Base.runtests("Downloads")
```
but not with the individual testsuite:
```
julia> using Test, Downloads

julia> const server = "https://httpbingo.julialang.org";

julia> @testset "debug callback" begin
           url = "$server/get"
           events = Pair{String,String}[]
           resp = request(url, debug = (type, msg) -> push!(events, type => msg))
           @test resp isa Response && resp.status == 200
           @test any(events) do (type, msg)
               type == "TEXT" && startswith(msg, "Connected to ")
           end
           @test any(events) do (type, msg)
               type == "HEADER OUT" && contains(msg, r"^HEAD /get HTTP/[\d\.+]+\s$"m)
           end
           @test any(events) do (type, msg)
               type == "HEADER IN" && contains(msg, r"^HTTP/[\d\.]+ 200 OK\s*$")
           end
       end;
Test Summary:  | Pass  Total  Time
debug callback |    4      4  0.6s
```

I wonder if we're having again problems with race conditions.  CC: @StefanKarpinski @vtjnash

**Comment by fxcoudert** [comment]
Unless the connection is explicitly closed in the tests (but I don't see where), then yes _“Connection #0 to host httpbingo.julialang.org left intact”_ is a valid response.

Where should it be fixed? Is it https://github.com/JuliaLang/Downloads.jl/blob/0098e40feb6d4992920ddfbed181150ef412f189/test/runtests.jl#L231 ?

**Comment by giordano** [comment]
Yes, that's the line.

**Comment by fxcoudert** [comment]
Rebasing, should be fixed now that `Downloads.jl` PR in https://github.com/JuliaLang/Downloads.jl/pull/219 was merged.

**Pull request merged**
