### PR TITLE
Update PCRE2 to 10.36

### PR DESCRIPTION
**Pull request by omus**
Patched version of PCRE2 10.36 which should address the PCRE2 crashes on Apple Silicon (https://github.com/JuliaLang/julia/issues/36617).

### CODE REVIEW

**Comment by Keno** [comment]
Needs a BB bump with the patch also.

**Comment by omus** [comment]
> Needs a BB bump with the patch also.

I believe I just need to update the PCRE2_jll project version for this. Let me know if there's anything else I need to do. From looking at other PRs I don't think checksums need to be committed.

**Comment by Keno** [comment]
Checksums definitely need to be updated.

**Comment by omus** [comment]
I can confirm that this fixes the [hanging issue](https://github.com/JuliaLang/julia/issues/36617#issuecomment-762412814) on Apple Silicon when compiling `shell.jl`

**Comment by omus** [comment]
The `tester_linux64` failure looks unrelated:
```julia
Error in testset Profile:
Error During Test at /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Profile/test/runtests.jl:120
  Test threw exception
  Expression: getline(values(fdictc)) == getline(values(fdict0)) + 2
  MethodError: no method matching +(::Nothing, ::Int64)
  Closest candidates are:
    +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:597
    +(!Matched::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
    +(!Matched::Rational, ::Integer) at rational.jl:310
    ...
  Stacktrace:
   [1] macro expansion
     @ /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Profile/test/runtests.jl:120 [inlined]
   [2] macro expansion
     @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1152 [inlined]
   [3] top-level scope
     @ /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.7/Profile/test/runtests.jl:106
```

**Review by Keno — APPROVED** [review]

**Comment by simonbyrne** [comment]
Should be backported to fix #40231.

**Comment by fxcoudert** [comment]
The patches have been merged in PCRE2 10.37 and later, the latest version being 10.40. Updating to that version would allow to drop the patches, and benefit from other fixes that have been introduced. Would a PR to update the version be welcome?

**Comment by fxcoudert** [comment]
@giordano where do I get the changes for `deps/checksums/pcre`?

**Pull request merged**
