### PR TITLE
[WINDOWS][BUILD] Fix for Cygwin using USE_BINARYBUILDER_LIBGIT2=0

### PR DESCRIPTION
**Pull request by stahta01**
Without change "fatal error: libssh2.h: No such file or directory" happens. It also tends to find the wrong libssh2 library as reported in the cmake cache file. 

Tim S.

See also issue  https://github.com/JuliaLang/julia/issues/45645
```
$ gcc --version | grep '(GCC)'
gcc (GCC) 11.3.0

$ x86_64-w64-mingw32-gcc --version | grep '(GCC)'
x86_64-w64-mingw32-gcc (GCC) 11.3.0

$ x86_64-w64-mingw32-g++ --version | grep '(GCC)'
x86_64-w64-mingw32-g++ (GCC) 11.3.0

$ ld --version | grep '(GNU Binutils)'
GNU ld (GNU Binutils) 2.40

$ make --version | grep 'GNU Make'
GNU Make 4.4.0.91

$ uname -srvmo
CYGWIN_NT-10.0-19045 3.4.6-1.x86_64 2023-02-14 13:23 UTC x86_64 Cygwin
```
Build command
```
cd "H:\devel\general_projects\repos\julia-master-cygwin" && \
[[ -d "./usr-staging" ]] && rm -rf "./usr-staging" ; \
[[ -d "./usr" ]] && rm -rf "./usr" ; \
echo 'XC_HOST = x86_64-w64-mingw32'   > Make.user && \
echo 'USE_BINARYBUILDER_LIBGIT2 = 0' >> Make.user && \
make clean VERBOSE=1 && \
make debug VERBOSE=1
```
```
./usr/bin/julia-debug.exe
```
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0-DEV.662 (2023-02-26)
 _/ |\__'_|_|_|\__'_|  |  libgit_find_libssh2_fix/737368e63b* (fork: 1 commits, 0 days)
|__/                   |

```

```
cd "H:\devel\general_projects\repos\julia-master-cygwin/test" && \
  env PATH="../usr/bin:$PATH" \
    ../usr/bin/julia-debug --check-bounds=yes --startup-file=no ./runtests.jl \
      LibGit2 \
      2>&1 | tee ../../julia-cygwin-master-LibGit2-check.log && echo -ne '\007'
```
```
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 4
  Sys.total_memory() = 7.902 GiB
  Sys.free_memory() = 3.234 GiB

Test        (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LibGit2/libgit2  (1) |        started at 2023-02-26T06:48:30.349
LibGit2/libgit2  (1) |    86.86 |   3.01 |  3.5 |     814.26 |   679.14

Test Summary: | Pass  Total     Time
  Overall     |  593    593  1m30.5s
    SUCCESS
```

### CODE REVIEW

**Comment by inkydragon** [comment]
Perhaps this patch is simpler and more consistent:

```patch
diff --git a/deps/libgit2.mk b/deps/libgit2.mk
index 30d94aeca7..3d9e265d37 100644
--- a/deps/libgit2.mk
+++ b/deps/libgit2.mk
@@ -26,6 +26,7 @@ LIBGIT2_OPTS += -G"MSYS Makefiles"
 else
 LIBGIT2_OPTS += -DBUILD_CLAR=OFF -DDLLTOOL=`which $(CROSS_COMPILE)dlltool`
 LIBGIT2_OPTS += -DCMAKE_FIND_ROOT_PATH=/usr/$(XC_HOST) -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
+LIBGIT2_OPTS += -Dssh2_RESOLVED=${bindir}/libssh2.dll
 endif
 endif
```
ref: https://github.com/JuliaPackaging/Yggdrasil/blob/e7e62e4a11f3fa1ef8b8a55fe9518a36631e5da0/L/LibGit2/build_tarballs.jl#L38-L39

**Comment by stahta01** [comment]
> Perhaps this patch is simpler and more consistent:
> 
> ```diff
> diff --git a/deps/libgit2.mk b/deps/libgit2.mk
> index 30d94aeca7..3d9e265d37 100644
> --- a/deps/libgit2.mk
> +++ b/deps/libgit2.mk
> @@ -26,6 +26,7 @@ LIBGIT2_OPTS += -G"MSYS Makefiles"
>  else
>  LIBGIT2_OPTS += -DBUILD_CLAR=OFF -DDLLTOOL=`which $(CROSS_COMPILE)dlltool`
>  LIBGIT2_OPTS += -DCMAKE_FIND_ROOT_PATH=/usr/$(XC_HOST) -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
> +LIBGIT2_OPTS += -Dssh2_RESOLVED=${build_shlibdir}/libssh2.dll
>  endif
>  endif
> ```
> 
> ref: https://github.com/JuliaPackaging/Yggdrasil/blob/e7e62e4a11f3fa1ef8b8a55fe9518a36631e5da0/L/LibGit2/build_tarballs.jl#L38-L39

I think the CMAKE people would be upset with it; because it likely violates their rules.

Tim S.

**Review by inkydragon — APPROVED** [review]
LGTM.

This pathc fix:

> When building `libgit2`, sometimes `libssh2` is not found
> 
> _Originally posted by `@inkydragon` in https://github.com/JuliaLang/julia/issues/45645#issuecomment-1153212764_

**Comment by stahta01** [comment]
> LGTM.
> 
> This pathc fix:
> 
> > When building `libgit2`, sometimes `libssh2` is not found
> > _Originally posted by `@inkydragon` in [#45645 (comment)](https://github.com/JuliaLang/julia/issues/45645#issuecomment-1153212764)_

Correct, it fixes the problem of libgit2 failing to find libssh2; it also prevents the finding of the wrong libssh2 under MSys2 MINGW64 and likely fixes that issues under Cygwin. If MSys2 has an system installation of libssh2 it finds it before the Julia built version.

Tim S.

**Pull request merged**
