### PR TITLE
Codegen updates for llvm 3.7

### PR DESCRIPTION
**Pull request by sjkelly**
Target/TargetLibraryInfo.h was moved to Analysis/ and TargetLibraryInfo renamed to TargetLibraryInfoWrapperPass

See: https://github.com/llvm-mirror/llvm/commit/eeeec3ce0d358ac43148030636ec9d4372953165 and https://github.com/llvm-mirror/llvm/commit/bda134910ab021c647ed05bfba8176cba4696c82

This is my first time touching anything in src/ and related to LLVM, so I have zero confidence this is correct or a correct interpretation of the changes on LLVM svn. However, it builds and passes tests on my Debian box.

### CODE REVIEW

**Comment by tkelman** [comment]
Note that trunk is on 3.7 now: f11d9b193361e73c28aea5acb40962f636843e04

To get 3.6 we need to check out the specific branch for it.

**Comment by Keno** [comment]
Yes, I believe these are actually the first LLVM 3.7 API changes.

**Comment by sjkelly** [comment]
Wow, the branch was today! Okay I will update this PR.

**Comment by sjkelly** [comment]
I see why the if defs worked on 3.7:

```
#if defined(LLVM_VERSION_MAJOR) && LLVM_VERSION_MAJOR == 3 && LLVM_VERSION_MINOR >= 6
#define LLVM36 1
#endif
```

Should these be changed to strict equality?

**Comment by Keno** [comment]
No, because most things for 3.6 are still valid on 3.7 so we define the lower ones as well to avoid having to write
```
#if defined(LLVM33) || defined(LLVM34) || defined(LLVM35) || defined(LLVM36) || defined(LLVM37)
```

**Comment by sjkelly** [comment]
Okay! Squashed and rebased.

**Pull request merged**
