### PR TITLE
CI (Buildkite): on pull request builds, build the merge commit (e.g. `refs/pull/1234/merge`)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @staticfloat 
cc: @giordano

**Comment by DilumAluthge** [comment]
@staticfloat If master advances after the packager starts, the SHA of the merge commit changes. Then when the tester tries to download the artifact, it has a different filename than the file uploaded by the packager.

**Comment by DilumAluthge** [comment]
What we really want is a way to:
1. At the beginning of the build, get the SHA of the merge commit.
2. Use that same SHA for all jobs in the build, regardless of when they start.

**Comment by staticfloat** [comment]
Easiest fix; just use wildcards with `buildkite-agent artifact download`.

**Comment by DilumAluthge** [comment]
> Easiest fix; just use wildcards with `buildkite-agent artifact download`.

Yeah I think this is the easiest solution. I'll also have to use wildcards a few other places, e.g. when I rename `julia-COMMIT-linux64.tar.gz` to `julia-latest-linux64.tar.gz` before uploading it to S3.

**Review by staticfloat — APPROVED** [review]
I vote that we error out if we can't find a merge commit.

**Comment by DilumAluthge** [comment]
I'm closing this PR in favor of using the new plugin: https://github.com/JuliaCI/merge-commit-buildkite-plugin

**Pull request closed without merging**
