### PR TITLE
Distributed: Set number of BLAS threads if LinearAlgebra is loaded, otherwise do nothing

### PR DESCRIPTION
**Pull request by KristofferC**
Breaks a dependency from Distributed -> LinearAlgebra.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Can we use `package_callbacks` to deal with the other load order?

**Comment by andreasnoack** [comment]
> Can we use package_callbacks to deal with the other load order?

I more general solution might be useful here since e.g. FFTW might also want to use this.

**Comment by KristofferC** [comment]
> I more general solution might be useful here since e.g. FFTW might also want to use this.

Could you propose something? A vector in `Base` with callbacks that packages put there to run with `n` threads?

```jl
const thread_callbacks = []
function set_library_threads(n::Int)
    for f in thread_callbacks
        f(n)
    end
end
```

**Comment by KristofferC** [comment]
Why does loading "Distributed" do "magic things" to other libraries (BLAS). Why can't it be "if you do distributed computing, make sure your libraries only use one core" or something.

**Comment by andreasnoack** [comment]
> Why can't it be just a doc thing,

It could and it would indeed simplify things. It's not unreasonable to ask people to actively set the number of threads when using multiple processes. Often you'd probably want a combination of threads and processes anyway. So far we have assumed that people wanted to disable threading when using multiple processes but we could stop assuming that. As you've pointed out, the dependency structure required by the current assumption is also a bit unfortunate.

**Comment by ViralBShah** [comment]
Is there a decision to do something? Or close?

**Comment by vchuravy** [comment]
> So far we have assumed that people wanted to disable threading when using multiple processes but we could stop assuming that.

I for one are in favour of making things simpler and stop having Distributed change the number of threads in the BLAS library. It made sense when we didn't have robust multi-threading support and the expectation was that users would use Distributed to do single machine work. Machines since then have also gained cores even on laptops.

**Comment by vchuravy** [comment]
Got done in #30004

**Pull request closed without merging**
