### PR TITLE
Implement generic pivoted Cholesky

### PR DESCRIPTION
**Pull request by dkarrasch**
This implements a generic version of the Cholesky decomposition with complete pivoting, as described in the paper/LAPACK report by C. Lucas. It's never been easier to write tests for a PR!

### CODE REVIEW

**Comment by dkarrasch** [comment]
If I remove the dispatch to LAPACK and run a 1500x1500 Float64 matrix, then I get a factor of 2 in runtime and a factor of 1 in allocations. Not too bad, I'd say, since this is the unblocked algorithm.

**Comment by dkarrasch** [comment]
One thing to discuss is the fact that the pivoting strategy is actually not `RowMaximum`. From a brief online search, I guess it's more like `DiagonalPivoting`, or `DiagonalMaximum`, or `CompletePivoting`? Should we do something about this? Like, introduce a new pivoting strategy and redirect the "wrong" one to the new?

**Comment by mikmoore** [comment]
Glad to have it!

I believe widening the `RealHermSymComplexHerm` signature (to, e.g., `Union{Symmetric{<:Real}, Hermitian{<:Number}}`) would allow this to function for some other element types (e.g., `Quaternions.jl`) after ensuring operations are ordered properly (to handle non-commutative multiplication).

I worry about casting *too* wide a net with `Number`, but since the factorization requires some applicable concept of positive semidefiniteness to even be sensible, I expect we get away with it in most instances. Someone with a fancier math background could probably say better.

An even further stretch would be a factorization that can function (probably recursively) on `AbstractMatrix{<:AbstractMatrix}`, but that's now well-beyond the scope of this PR.

**Comment by dkarrasch** [comment]
For the time being, I suggest to merge this as is. Besides the non-commutative cases that you mention, I am working on a blocked version of pivoted Cholesky (but can't seem to get it right ATM). But I think that can be done step by step in future work.

**Comment by DilumAluthge** [comment]
@dkarrasch CI is all green here.

**Pull request merged**
