### PR TITLE
return bytes written from write(IO,IO)

### PR DESCRIPTION
**Pull request by jkroso**

### CODE REVIEW

**Comment by tkelman** [comment]
`test/io.jl` won't actually run unless it's added to `test/choosetests.jl`, but for something this short probably better to add it to an existing file.

**Comment by jkroso** [comment]
I tried to find a file to put that test in but it seemed out of place in all of them

**Comment by kshyatt** [comment]
Looking at your test, why can't we put it in `test/iobuffer.jl`? (This may be a very stupid question.)

**Comment by jkroso** [comment]
Well even though for testing purposes I used an IOBuffer its testing code that applies to all types of IO objects.

But anyway I think the file structure of the test directory should match the structure of the base directory. So that it's easy to find the tests for a given bit of code. And its already pretty close to matching up

**Comment by Keno** [comment]
Fixed independently in https://github.com/JuliaLang/julia/pull/25406. Sorry that this was forgotten.

**Pull request closed without merging**
