### PR TITLE
Added note mentioning asynchrous IO

### PR DESCRIPTION
**Pull request by goelakash**
#13450

### CODE REVIEW

**Comment by goelakash** [comment]
please review.

**Comment by tkelman** [comment]
This doesn't belong in the stdlib which is a function listing, it belongs somewhere in a manual section. And please be patient, there's no need to post a reminder note unless it's been a few days without a response.

**Comment by StefanKarpinski** [comment]
This also requires a more thorough explanation that this. The key is that Julia I/O is semantically blocking but non-blocking under the hood so that when multiple tasks are all doing I/O they do so without blocking each other.

**Comment by goelakash** [comment]
Should I close this PR or let it stay open for further discussion about I/O?

**Pull request closed without merging**
