### PR TITLE
run clang analyzer static checks

### PR DESCRIPTION
**Pull request by vtjnash**
also, make it happy, and fix the missing `free` call that it found

### CODE REVIEW

**Comment by DilumAluthge** [comment]
How long does the Clang analyzer take to run? If it doesn't take a very long time, we could add a CI job for it?

**Comment by Keno** [comment]
We have (had?, Not sure where where at) a CI job for it. The gc root checker is clangsa.

**Comment by DilumAluthge** [comment]
Here is what we are currently running:

| CI Job     | Command                                         |
| ---------- | ----------------------------------------------- |
| embedding  | `make -C test/embedding`                        |
| analyzegc  | `make -C test/clangsa`                          |
| analyzegc  | `make -C src analyzegc`                         |
| llvmpasses | `make -j$${JULIA_NUM_CORES} -C test/llvmpasses` |

However, all of these jobs are currently passing on `master` (see e.g. https://buildkite.com/julialang/julia-master/builds/3717).

So do we need another job to catch the failures that we are currently missing?

**Comment by DilumAluthge** [comment]
> So do we need another job to catch the failures that we are currently missing?

By "the failures that we are currently missing", I mean e.g. "the missing free call that it found" that Jameson fixes in this PR.

**Comment by Keno** [comment]
The analyzer option that catches that was just not turned on. Presumably after this PR, it'll start catching this sort of issue.

**Comment by vtjnash** [comment]
Right, analyzegc is the clang static analyzer, and is already running. This removes the flag where we had been telling it to run many fewer tests.

**Pull request merged**
