### PR TITLE
Make the navigation bar numbered

### PR DESCRIPTION
**Pull request by fredrikekre**
This makes it *much* easier to visually parse the menu and makes it much more pleasant to scroll through the manual.

Old docs: https://docs.julialang.org/en/latest/
New docs: https://fredrikekre.github.io/index.html

### CODE REVIEW

**Comment by KristofferC** [comment]
Indeed looks much better. Is there anything to gain by programmatically inserting these numbers by traversing the `PAGES` variable?

**Comment by fredrikekre** [comment]
> Is there anything to gain by programmatically inserting these numbers by traversing the PAGES variable?

Probably, can do something like that if people like this look.

**Comment by haampie** [comment]
Nice!

Imho a number in the breadcrumbs at the top looks a bit odd tho:

schermafbeelding 2018-05-22 om 21 19 42

**Comment by innerlee** [comment]
Layout of the index of chapter 4 looks a little strange (due to indentation of section 4.1)

**Comment by mauro3** [comment]
It does seem a bit strange to make it numbered without actually needing numbers.  Could not another visual cue be used instead?

**Comment by KristofferC** [comment]
> It does seem a bit strange to make it numbered without actually needing numbers

Numbering sections is the norm in any book / paper / manual, no? Some prior art https://doc.rust-lang.org/book/second-edition/

**Comment by mauro3** [comment]
Maybe then number the headings in the text too?

**Comment by ViralBShah** [comment]
This would certainly be very nice to have.

**Comment by ViralBShah** [comment]
Too old to revive? Certainly would still be nice, but may be close for now?

**Comment by fredrikekre** [comment]
Probably needs to be implemented in Documenter instead of this manual approach.

**Pull request closed without merging**
