### PR TITLE
Minor code and style improvements in ui/repl.c

### PR DESCRIPTION
**Pull request by drepper**
- use array variables instead of pointers
- add const where possible
- use enums to assign values for high getopt options insteaf of
  possibly error-prone manual assignment.  Also documents the
  code better

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Thanks!

Welcome to julia; I know I (and probably many of our contributors and users) have benefited from your excellent articles and open source work over the years.

**Comment by Keno** [comment]
Yes, in particular I found http://www.akkadia.org/drepper/tls.pdf very helpful when implementing TLS support for the JIT (still ongoing work).

**Comment by tkelman** [comment]
Whoa, welcome indeed. @eschnett had suggested the same basic `enum` change in his `@fastmath` pull request, but it's now subsumed in a larger reworking of the command-line-flags code in #9482. The `const`s and array change are probably good to do too.

**Comment by timholy** [comment]
Indeed; I'm a fan of "what every programmer should know about memory." Thanks.

**Comment by ViralBShah** [comment]
Likewise. Welcome!

**Comment by drepper** [comment]
I've pushed one more patch, this time a performance optimization.  The somewhat lengthy commit message should explain this.  If these types of patches are not appropriate let me know.

**Comment by tknopp** [comment]
lgtm. Maybe the noinline code could be put into a macro like the one we have for `STATIC_INLINE`? https://github.com/JuliaLang/julia/blob/4e6547225cf14fc06d56cb372363c82ae9df2cf7/src/support/dtypes.h#L124

**Comment by eschnett** [comment]
Could you take the text from the commit message and turn it into a comment near the implementation of `jl_egal`? This way, future readers will be much more likely to find the explanation for the "don't inline this" behaviour.

**Comment by drepper** [comment]
I've added macros NOINLINE and NOINLINE_DECL (the latter being necessary due to the way function declarations are handled in gcc vs msft compilers) and I added the comment.

What I forgot in the previous comments: I saw a speedup of around 4% due to this change.

**Comment by timholy** [comment]
This looks great, many thanks! What were you timing when you saw that 4% speedup?

**Comment by drepper** [comment]
I just ran some of the tests, mostly arrayops.

**Comment by srp** [comment]
Looks like it was arrayops: https://github.com/JuliaLang/julia/commit/89f3b58a597c81860a353f3e43e13a7faf15d1d0

**Pull request merged**
