### PR TITLE
minor change: non-infinite `iterate(zip())`

### PR DESCRIPTION
**Pull request by Moelf**
#43821

### CODE REVIEW

**Comment by Moelf** [comment]
@LilithHafner

**Comment by Moelf** [comment]
```
julia> for x in zip()
           @show x
       end
x = ()
ERROR: MethodError: no method matching length(::Nothing)

Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator})
```

it doesn't work but it should be enough to see if people actually `iterate(zip())`

**Comment by rfourquet** [comment]
Why would `zip()` produce a single element? It doesn't match the current definition of `zip`. If we really want to diverge from the definition, producing zero elements makes more sense to me, although I would still not know how to justify that. In any case, it we introduce a special-case, it should be stated in the docstring.

**Comment by Moelf** [comment]
@rfourquet did you read OP in https://github.com/JuliaLang/julia/issues/43821?

**Comment by rfourquet** [comment]
> did you read OP in https://github.com/JuliaLang/julia/issues/43821?

Yes and I'm not conviced. I think introducing a special case requires more than "seems bad" as a justification. E.g. evidence that the current behavior caused troubles.

**Comment by Moelf** [comment]
that's absurd, when people raise this question the explanation is "this is the behavior just take it or leave it", how can you possibly find "evidence" for something like this?

can you find an example of an "evidence" of this kind? other than people tweeting about it

**Comment by rfourquet** [comment]
Sorry, "evidence" might have not been the correct term, I just meant this: for example has there been complaints from people having had a bug in their code due to the current behavior. Because for now I didn't see any motivation for this change besides "seems bad"; but the status quo makes sense for some other people.

**Comment by Moelf** [comment]
right, one way I can imagine this is:
```julia
itrs = myfunction(...)

for xs in zip(itrs...)
end
```

now your problem hang

**Comment by rfourquet** [comment]
> Now your program hangs.

I can also imagine this example, but maybe hanging might be the best outcome to find out about an underlying bug, e.g. `itrs` was assumed to be non-empty. Without real-life examples, it's hard to say which behavior is the most useful. Is there one real-world example where `zip()` yielding zero elements or one element `()` is useful? I don't have one where yielding infinitely many `()` is useful, but could definitely imagine one, e.g. something along the lines of `zip(zip(itrs...), 1:9)`. So, without a real motivating example, I prefer not introducing special-cases.

**Comment by jariji** [comment]
> I can't see how people can rely on the current infinite loop behavior

Infinite iterators are a useful feature. In a long-running program, they can continue forever, or in a finite program they can be combined with other iterators that halt earlier. For example, this code uses the feature as intended:

```jl
julia> collect(reduce(zip, [1:3, 4:6]; init=zip()))
3-element Vector{Tuple{Tuple{Tuple{}, Int64}, Int64}}:
 (((), 1), 4)
 (((), 2), 5)
 (((), 3), 6)
```

Not only is it practically useful, `zip()` forms a key part of an algebraic abstraction: `zip` is a (nearly) associative binary operator with `zip()` being the empty element -- i.e. like `1` is to `*`, `""` is to `join`, `Inf` is to `min`, `true` is to `&&`, and so on. The stream of empty tuples plays that role of the [initial value](https://juliafolds.github.io/InitialValues.jl/v0.1/) for the `zip` operator. This point is made more clearly by @tkf in https://github.com/JuliaLang/julia/issues/43821#issuecomment-1013816939.

Julia doesn't _need_ to respect any algebraic structure. But doing so is useful and can simplify reasoning in a functional programming style. The downside of course is that it's possible to iterate over an infinite iterator by accident, which can be surprising if you're not expecting it. The same is true for any infinite iterator.

**Comment by Moelf** [comment]
can we get a PkgEval, I hope it fails so I don't have to keep getting convinced why we should be haskell sometimes

**Comment by JeffBezanson** [comment]
We should see what a bunch of other languages do. According to @oscardssmith python gives an empty iterator. I wonder about clojure, rust, scala, ... ?

**Comment by oscardssmith** [comment]
triage wants a list of what everyone else does.

**Comment by Moelf** [comment]
- Python: runs no iteration, this PR's current behavior
- Rust: `std::zip` requires exactly 2 arguments (https://doc.rust-lang.org/std/iter/struct.Zip.html)
- Haskell: requires exactly 2 arguments (https://hoogle.haskell.org/?hoogle=zip)
- Ruby: `zip` is a member function of Array, if `a = []`, `a.zip()` returns `[]`.
- Scala: `zip` needs arguments: https://www.tutorialspoint.com/scala_collections/scala_collections_zip.htm


Languages checked but without official "zip": Clojure, R, Racket, Wolfram, MATLAB

**Comment by jariji** [comment]
In summary:


- infinite iterators can be surprising if you aren't expecting one, possibly leading to an infinite loop
- Python is the only other language with freestanding variadic zip, and it stops immediately
- infinite `zip()` can be useful if you're doing it intentionally: it makes nice algebraic abstraction where `zip(a, zip(b,c))` is congruent to `zip(zip(a,b), c)` modulo nesting.
- changing may break existing code by cutting an iterator off early like `zip(zip(), 1:3)` which seems like a dangerous silent behavior change: the iterator will stop early.

My code from above gives currently

```jl
julia> collect(reduce(zip, [1:3, 4:6]; init=zip()))
3-element Vector{Tuple{Tuple{Tuple{}, Int64}, Int64}}:
 (((), 1), 4)
 (((), 2), 5)
 (((), 3), 6)
```

but gives inconsistent results under the change:

```jl
@eval Base.Iterators begin
       length(::Zip{Tuple{}}) = 0
       iterate(::Zip{Tuple{}}) = nothing
end

julia> collect(reduce(zip, [1:3, 4:6]; init=zip()))
3-element Vector{Tuple{Tuple{Tuple{}, Int64}, Int64}}:
 (((), 0), 0)
 (((), 0), 0)
 (((), 0), 0)

julia> collect(reduce(zip, [1:3, 4:6]; init=zip()))
3-element Vector{Tuple{Tuple{Tuple{}, Int64}, Int64}}:
 (((), 139870574512800), 139867037887216)
 (((), 139870814318624), 139870576431136)
 (((), 139870814285936), 139870814291824)
```

**Comment by LilithHafner** [comment]
This seems like a worthy use of nanosoldier.

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47344#issuecomment-1294392285) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39c790f_vs_42563aa/report.html).

**Comment by LilithHafner** [comment]
@nanosoldier `runtests(["BasisFunctions", "Gen", "Leaflet", "NumericalAlgorithms"], vs = ":master")`

**Comment by simeonschaub** [comment]
Seems like Gen actually relies on this behavior: https://github.com/probcomp/Gen.jl/blob/e1fb6eb95ed9a9586df9663a4dcf96920487dbc8/src/modeling_library/switch/update.jl#L43

**Comment by PallHaraldsson** [comment]
I'm confused, did this fix 8 packages, including e.g. Graph500.jl that's been unchanged for years. I.e. more than the 4 seemingly failing, e.g. Gen.jl, and then what to do if really fixing more? And why are those  being tested again, I don't see any changes on master in the last few hours.

**Comment by Moelf** [comment]
https://github.com/mrtkp9993/NumericalAlgorithms.jl is deprecated

**Comment by Moelf** [comment]
Gen may .... but personally I think base case empty should just be handled, something like:

```julia
isempty(prev_choice_submap_iterator) && return new_choices
```

idk if it actually depend on it.

**Comment by Moelf** [comment]
@PallHaraldsson I think whenever the error is
>No writable path exists to save the data. Make sure there exists as writable path in your DataDeps Load Path.

it's may not be real

**Comment by PallHaraldsson** [comment]
Yes, for Leaflet.jl that is, this is the reason (a false alarm):
```
⌃ [124859b0] DataDeps v0.7.8
[..]
        Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading.
     Testing Running tests...
┌ Error: No writable path exists to save the data. Make sure there exists as writable path in your DataDeps Load Path.
│ See https://www.oxinabox.net/DataDeps.jl/stable/z10-for-end-users/#The-Load-Path-1
```

**Comment by PallHaraldsson** [comment]
Both logs for NumericalAlgorithms are intriguing, and the failing one for this PR has atol inaccuracy.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/47344#issuecomment-1294774489) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/39c790f_vs_42563aa/report.html).

**Comment by Moelf** [comment]
```
update: Error During Test at /home/pkgeval/.julia/packages/Gen/Dne3u/test/modeling_library/switch.jl:63
  Got exception outside of a @test
  BoundsError: attempt to access Base.Iterators.Zip{Tuple{}} at index [1]
```

interesting, so indeed Gen relies on `zip()` at least have two `(), ()`...

**Comment by Moelf** [comment]
I guess we should keep the current zip behavior then

**Comment by LilithHafner** [comment]
> And why are those being tested again

PkgEval runs the test suite of all (or almost all) registered packages. Some of those test suites have non-deterministic failures (e.g. they pass 90% of the time regardless of whether or not zip() has infinite length). This leads to spurious failures and passes not attributable to this PR. Re-running just the few packages that failed only on this branch and not on master is an easy way to differentiate real failures from spurious ones. In this case, Gen.jl was the only one that failed the second time around, so we can strongly suspect that it actually relies on the behavior that is changed here.

@simeonschaub's analysis pointing to the exact line that uses it and @Moelf's citing the bounds error as reason for test failure are the conclusive results, but re-running failed tests lets us narrow down that search.

**Comment by MasonProtter** [comment]
Triage thinks that `zip()` should either be an infinite stream, or it should error. 

The reason that people think it should be infinite is that the length of `stream(args....)` is the minimum of `length.(args)`, and the neutral element of `minimum` is infinity. However, there are good ergonomic reasons to not want that to be an infinite iterator, so it seems better to just make `zip()` an error (start off with a `@depwarn`), and tell people if they want an inifinite stream they should use `Iterators.repeated`.

**Pull request closed without merging**
