### PR TITLE
trim linefeeds before comparing hashes

### LINKED ISSUE #30752: jlchecksum is sensitive to the linefeed used on the system
Trying to build Julia on cygwin I get a problem during checksum verification made by `jlchecksum`:

```
  ERROR: sha512 checksum failure on cacert-2018-12-05.pem, should be:
      1896c83c6bad4f1ab2a5c1fa04f694597e8319e1892eb48c74ce85dad82c924c
      143c1e09b8d86354ba7b1ef001237a52b503c9ebe06eef61dd16c3689a5e9b30

  But `sha512sum /cygdrive/c/Users/Kristoffer/julia/deps/srccache/cacert-2018-12-05.pem | awk '{ print $1; }'` results in:
      1896c83c6bad4f1ab2a5c1fa04f694597e8319e1892eb48c74ce85dad82c924c
      143c1e09b8d86354ba7b1ef001237a52b503c9ebe06eef61dd16c3689a5e9b30
```

These look the same, but dumping them to hex, we can see

```
$ hexdump deps/curr_check
0000000 3831 3639 3863 6333 6236 6461 6634 6131
0000010 3262 3561 3163 6166 3430 3666 3439 3935
0000020 6537 3338 3931 3165 3938 6532 3462 6338
0000030 3437 6563 3538 6164 3864 6332 3239 6334
0000040 3431 6333 6531 3930 3862 3864 3336 3435
0000050 6162 6237 6531 3066 3130 3332 6137 3235
0000060 3562 3330 3963 6265 3065 6536 6665 3136
0000070 6464 3631 3363 3836 6139 6535 6239 3033
0000080 000a
0000081

Kristoffer@DESKTOP-188MN1B ~/julia
$ hexdump deps/true_check
0000000 3831 3639 3863 6333 6236 6461 6634 6131
0000010 3262 3561 3163 6166 3430 3666 3439 3935
0000020 6537 3338 3931 3165 3938 6532 3462 6338
0000030 3437 6563 3538 6164 3864 6332 3239 6334
0000040 3431 6333 6531 3930 3862 3864 3336 3435
0000050 6162 6237 6531 3066 3130 3332 6137 3235
0000060 3562 3330 3963 6265 3065 6536 6665 3136
0000070 6464 3631 3363 3836 6139 6535 6239 3033
0000080 0a0d
0000082
```

Which to me indicates different line endings (`0a0d`). The true checksum is read with `cat` while the computed one is printed with `awk` and it seems these disagree.

### PR DESCRIPTION
**Pull request by KristofferC**
No idea if this is the correct thing to do but it fixes #30752 for me.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I don't think we should do this universally, but maybe just for the pem files in a more targeted way?

**Comment by KristofferC** [comment]
Seems like a better idea, yes.

**Comment by KristofferC** [comment]
This went away after recloning from scratch. Perhaps I had some bad git settings for Windows the first time I cloned.

**Comment by KristofferC** [comment]
It started again heh

```
===============================================================================
  ERROR: sha512 checksum failure on Pkg-4baddc50a0cab908b5184c2a211453b8c9417330.tar.gz, should be:
      e99485e7a702d48a43fb741621fe5e4fc5ab3dc731eb3033fe5c0829ce5b79c8
      9266a6ce064ed30da18fd1f1f7ba3764e33796d8b3b76f8e80971fdcf691f0ab

  But `sha512sum /mnt/c/Users/Kristoffer/julia/stdlib/srccache/Pkg-4baddc50a0cab908b5184c2a211453b8c9417330.tar.gz | awk '{ print $1; }'` results in:
      e99485e7a702d48a43fb741621fe5e4fc5ab3dc731eb3033fe5c0829ce5b79c8
      9266a6ce064ed30da18fd1f1f7ba3764e33796d8b3b76f8e80971fdcf691f0ab
  This can happen due to bad downloads or network proxies, please check your
  network proxy/firewall settings and delete
  /mnt/c/Users/Kristoffer/julia/stdlib/srccache/Pkg-4baddc50a0cab908b5184c2a211453b8c9417330.tar.gz
  to force a redownload when you are ready
===============================================================================
```

**Pull request closed without merging**
