### PR TITLE
GC bug fix for `max_collect_interval` computation

### PR DESCRIPTION
**Pull request by kpamnany**
Currently, `max_collect_interval` is constrained to `totalmem / ncores / 2` for `_P64` which results in a very short collect interval when you're running with a smaller number of threads on a machine with many cores.

Change this to `totalmem / nthreads / 2` which, for two of our tests, resulted in 40% and 60% runtime reduction (!!) as well as
GC time reduction from 46% to 10% and 64% to 11%.

Spotted by @janrous-rai.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Review by Sacha0 — APPROVED** [review]
Thanks Kiran! :)

**Comment by janrous-rai** [comment]
Wait. I think you need to make sure that jl_n_threads is properly
initialized. It's done after GC setup by default.

**Comment by janrous-rai** [comment]
Or at least this was the case in 1.7.1

**Comment by kpamnany** [comment]
> It's done after GC setup by default.

Not sure exactly when it changed, but GC initialization [happens after](https://github.com/JuliaLang/julia/blob/master/src/init.c#L718-L723) threads are initialized.

**Comment by kpamnany** [comment]
The `tester_linux32` error is an `OutOfMemoryError`. Retrying now, but might this be being caused by this PR? @oscardssmith?

**Comment by kpamnany** [comment]
I'll check. Should I open a PR to a particular branch?

**Comment by KristofferC** [comment]
`backports-release-1.8`

**Pull request merged**
