### PR TITLE
Matrix operations involving different element types

### PR DESCRIPTION
**Pull request by davidbp**
Making operations with different element types can impact a lot execution time. It would be nice to have in the documentation an example showing the tradeoffs a user has to decide. I am not sure where.

I am writting this request as a remainder, feel free to change the examples. I think many users (using LinearAlgebra) will face this problem and it would be nice to have a tiny part of the documentation exposing readers with the behaviour of the different approaches.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Awesome, thank you for the nice doc contribution!

**Review by StefanKarpinski — APPROVED** [review]

**Comment by thchr** [comment]
`C = A*B` seems to dispatch to generic matrix-matrix multiplication [`mul!(C::AbstractMatrix, A::AbstractVecOrMat, B::AbstractVecOrMat)`](https://github.com/JuliaLang/julia/blob/a17d9aedb0c2f88b9d8a2658ef3141e8d614b1b9/stdlib/LinearAlgebra/src/matmul.jl#L176) via [(*)(A::AbstractMatrix, B::AbstractMatrix)](https://github.com/JuliaLang/julia/blob/a17d9aedb0c2f88b9d8a2658ef3141e8d614b1b9/stdlib/LinearAlgebra/src/matmul.jl#L141); it's not completely clear to me that one would actually want that to happen, given that the "benefit" is only a factor of 2 in memory. 

The call to the generic multiplication method could be avoided by changing [this line](https://github.com/JuliaLang/julia/blob/a17d9aedb0c2f88b9d8a2658ef3141e8d614b1b9/stdlib/LinearAlgebra/src/matmul.jl#L143) from
```julia
mul!(similar(B, TS, (size(A,1), size(B,2))), A, B)
```
to 
```julia
mul!(similar(B, TS, (size(A,1), size(B,2))), convert(AbstractArray{TS}, A), convert(AbstractArray{TS}, B))
```
This results timings/memory identical to the `*(A, map(Float64, B))` call in this PR.

Is the current design intentional, i.e. is there some reason it is preferable that `*(::Array{Float64}, Array{Float32})` dispatches to the generic method?

**Comment by dkarrasch** [comment]
@thchr I agree. I'm not sure about the generic case, but at least for `BlasFloat`s we should add
```julia
function (*)(A::AbstractMatrix{<:BlasFloat}, B::AbstractMatrix{<:BlasFloat})
    TS = Base.promote_op(LinearAlgebra.matprod, eltype(A), eltype(B))
    mul!(similar(B, TS, (size(A,1), size(B,2))), convert(AbstractArray{TS}, A), convert(AbstractArray{TS}, B))
end
```
because there we know the `convert` is gonna be worth it. The `*`-call is not in-place anyway, so the user is not expecting memory usage optimization, but probably still speed.

**Comment by dkarrasch** [comment]
The issue discussed in the added docstring disappeared after merging #32587. So shall we revive this with one of the matrices having integer components, @davidbp?

**Comment by davidbp** [comment]
Thank you @dkarrasch for making my issue obsolete! 

All the cases will have similar speed now ? (All cases with different float types). If that is the case ... thanks! 

If the same 3 cases exist with matrices of (etype Float)*(eltype Int) then you could change the examples with new timings taking into consideration those cases.

**Comment by oscardssmith** [comment]
One thing we should definitely look into is a better generic_matmul for the common cases of 2 dense arrays. Doing so could be an easy factor of 2 improvement, especially in the mixed type case.

**Comment by vtjnash** [comment]
I believe we have other issues open for implementing and improving common BLAS functions in Julia

**Pull request closed without merging**
