### PR TITLE
Allow Char as a needle for contains functions

### LINKED ISSUE #22418: `contains` does not allow `Char` needle
```help?> contains
  contains(haystack::AbstractString, needle::AbstractString)

  Determine whether the second argument is a substring of the first.

  julia> contains("JuliaLang is pretty cool!", "Julia")
  true
```
Is there any limitation to relaxing the needle and allowing `Char` types in addition to `AbstractString`?

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaLang/julia/issues/22418

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Review by StefanKarpinski — APPROVED** [review]

**Comment by musm** [comment]
Actually it may be better to let
`contains(str::AbstractString, char::Char) = search(c, s) != 0`
as that is faster.

FYI `in(c::Char, s::AbstractString) = (search(s,c)!=0)`
so this amendment would be equivalent to `in`, but it seems an unnecessary restriction to only allow AbstractString needle's  .  (I personally ran into this when I was using `contains`, I wasn't ware that `in`  accepted searching with a `Char`)

**Comment by JeffBezanson** [comment]
It looks to me like `search` and `searchindex` do the same thing in this case, so ideally they should be equally fast. Separate issue, but maybe we can fix that.

**Comment by musm** [comment]
> It looks to me like search and searchindex do the same thing in this case, so ideally they should be equally fast. Separate issue, but maybe we can fix that.

Sounds good. Better to keep the faster implementation here (latest commit), and then do an audit  after fixing the performance  discrepancy between  the two functions `search` and `searchindex`

**Comment by andyferris** [comment]
If `String` is iterable, I would expect to use `in(::Char, ::String)` (...but possibly in addition to `contains` which might be more convenient but as an alias for `in`?).

**Comment by musm** [comment]
I opened PR https://github.com/JuliaLang/julia/pull/22436 to fix the perf issue so that 
`in`
`contains` 
will be equivalent in terms of performance with `Char` needles, so that we can rely on the same implementation for the `contains` function for these two cases.  

> If String is iterable, I would expect to use in(::Char, ::String) (...but possibly in addition to contains which might be more convenient but as an alias for in?).

I was testing other string containment and then tried to pass  a `Char` and it threw an error, I didn't realize `in`  was meant for this case, but nonetheless it seems like an unnecessary restriction on the `contains` function and it's easy enough to support...

This PR should be g2g now

**Pull request merged**
