### PR TITLE
Add a test for #22021, jl_gc_realloc_string issue with join

### LINKED ISSUE #22021: add test for: Problem with `join`
I don't have a MWE, but 

```julia
s=String["\"\"\"\n     non_max_suppression(boxes, scores, max_output_size; iou_threshold=nothing)\n\nGreedily selects a subset of bounding boxes in descending order of score,\n\npruning away boxes that have high intersection-over-union (IOU) overlap\nwith previously selected boxes.  Bounding boxes are supplied as\n[y1, x1, y2, x2], where (y1, x1) and (y2, x2) are the coordinates of any\ndiagonal pair of box corners and the coordinates can be provided as normalized\n(i.e., lying in the interval [0, 1]) or absolute.  Note that this algorithm\nis agnostic to where the origin is in the coordinate system.  Note that this\nalgorithm is invariant to orthogonal transformations and translations\nof the coordinate system; thus translating or reflections of the coordinate\nsystem result in the same boxes being selected by the algorithm.\n\nThe output of this operation is a set of integers indexing into the input\ncollection of bounding boxes representing the selected boxes.  The bounding\nbox coordinates corresponding to the selected indices can then be obtained\nusing the `tf.gather operation`.  For example:\n\n  selected_indices = tf.image.non_max_suppression(\n      boxes, scores, max_output_size, iou_threshold)\n  selected_boxes = tf.gather(boxes, selected_indices)\n\"\"\"", "    tf.@op function non_max_suppression(v13566, v13567, v13568; name=nothing, iou_threshold=nothing) ", "            local desc ", "            tf.with_op_name((()->begin  ", "                        desc = tf.NodeDescription(\"NonMaxSuppression\") ", "                        begin  ", "                            begin  ", "                                v13566 = convert(TensorFlow.Tensor{Float32}, v13566) ", "                                begin  ", "                                end", "                            end", "                            begin  ", "                                v13567 = convert(TensorFlow.Tensor{Float32}, v13567) ", "                                begin  ", "                                end", "                            end", "                            begin  ", "                                v13568 = convert(TensorFlow.Tensor{Int32}, v13568) ", "                                begin  ", "                                end", "                            end", "                        end ", "                        begin  ", "                            begin  ", "                                tf.add_input(desc, v13566)", "                            end", "                            begin  ", "                                tf.add_input(desc, v13567)", "                            end", "                            begin  ", "                                tf.add_input(desc, v13568)", "                            end", "                        end ", "                        begin  ", "                            begin  ", "                                if iou_threshold !== nothing ", "                                    desc[\"iou_threshold\"] = Base.identity(iou_threshold)", "                                end", "                            end", "                        end", "                    end), name, \"NonMaxSuppression\") ", "            tf.Tensor(tf.Operation(desc))", "        end"]

print(join(s, "\n"))
```

outputs a non-deterministic string that has several seemingly random codepoints inserted in it.

### PR DESCRIPTION
**Pull request by tkelman**
could probably reproduce the bug with randomly generated input data, in case anyone thinks copying the docstring in full here is an issue

re-close #22021

### CODE REVIEW

**Comment by vtjnash** [comment]
Would be better to craft something that keeps slowly growing a bunch of really large String Vectors of odd sizes. Right now, this test is strongly dependent on half a dozen heuristics.

**Comment by tkelman** [comment]
It's a lot better than no test at all.

**Comment by vtjnash** [comment]
Not to belabor the point too much, but is a test that won't be certain to (reliably or periodically) catch the error it was written for actually better than acknowledging that the corner case is not well covered.

**Comment by tkelman** [comment]
I have no idea what you're trying to communicate. Some coverage is better than no coverage. Yes this was intermittent, the loop of 10 executions here would result in anywhere from 2 to 7 failures (out of a few dozen repeats of `make test-strings`) when I ran it on current release-0.6, or on master with the patch from #22044 applied in reverse.

You clearly understand what caused the bug better than I do. If you'd like to submit a more targeted test, please do - you really should have done so in the same PR as fixing the bug, but late is better than never. And even if the test case added in the PR "is strongly dependent on half a dozen heuristics," it's covering a few code paths that the existing tests missed, and it doesn't take all that long to run.

**Comment by vtjnash** [comment]
It shouldn't be intermittent. There's a less than 1 in 2^16 chance of the test succeeding by accident (with the now-fixed bug). However, there's also a high chance of some future commit accidentally disabling this test (due to its reliance of many internal heuristics all lining up just right to hit this case)

**Comment by tkelman** [comment]
The behavior here should continue to pass. It won't always cover the exact same code paths that triggered that bug, so it's not the best test for it, but it's not invalid. If you can propose another more specific test, **please do so**. I don't know what is significant about "slowly growing a bunch of really large String Vectors of odd sizes" or whether you're referring to large strings, vectors of many strings, odd-length strings, or odd numbers of strings, so it's really going to be more effective if you can write another test. If you think the issue shouldn't be closed by this test addition I'm fine with that.

**Pull request merged**
