### PR TITLE
simplify the fields of `UnionSplitInfo`

### PR DESCRIPTION
**Pull request by aviatesk**
xref: <https://github.com/JuliaLang/julia/pull/54972#discussion_r1766187771>

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55815) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c8fc7c5_vs_a73ba3b/report.md).

**Review by topolarity — APPROVED** [review]
Thanks! I'm a fan 👍

Might be good to measure the time spent in `jl_method_table_add_backedge` before vs. after

Or maybe add the local back-edge de-duplication to `add_uncovered_edges!` instead

**Comment by aviatesk** [comment]
> Might be good to measure the time spent in `jl_method_table_add_backedge` before vs. after

What's the best way to do this?

> Or maybe add the local back-edge de-duplication to `add_uncovered_edges!` instead

Implemented:)

**Comment by topolarity** [comment]
> > Might be good to measure the time spent in `jl_method_table_add_backedge` before vs. after
> 
> What's the best way to do this?

compiling with `WITH_TIMING_COUNTS = 1` (and potentially adding a subsystem to `JL_TIMING_SUBSYSTEMS` is probably the most convenient way, but now that we're de-duplicating during the add I'm not very concerned

Thanks!

**Pull request merged**
