### PR TITLE
Backports for 1.1.1

### LINKED ISSUE #28647: ?Symbol help message gives info on constructor, not on type
Looking up help on a type should first explain what the type is and does before going into how to call the constructor. This is not the case for Symbol
```
?Symbol
  Symbol(x...) -> Symbol

  Create a Symbol by concatenating the string representations of the arguments
  together.
```

### LINKED ISSUE #29936: Precompilation causes tuple construction error at REPL
Here's the MWE. In package `Foo`:

```julia
module Foo

const global m = Val{nothing}()
const global h = Val{:hey}()

wab = [("a", m),
       ("b", h),]

end
```

At the REPL:

```julia
julia> using Foo; [("Plan", Foo.m), ("Plan", Foo.h),]
ERROR: TypeError: in arrayset, expected Tuple{String,Val}, got Tuple{String,Val{nothing}}
Stacktrace:
 [1] setindex! at ./array.jl:769 [inlined]
 [2] copyto!(::Array{Tuple{String,Val},1}, ::Tuple{Tuple{String,Val{nothing}},Tuple{String,Val{:hey}}}) at ./abstractarray.jl:649
 [3] vect(::Tuple{String,Val{nothing}}, ::Vararg{Any,N} where N) at ./array.jl:151
 [4] top-level scope at none:0
```

On Julia 1.0.1, Linux binary. FWIW, I encountered several segfaults on the way to this MWE.

**edit**: simplified example.

### LINKED ISSUE #30499: disallow `return` outside function?
On v1.0.2 I used a return statement from within a let block that got assigned to a variable.  This didn't work as I expected, but it also didn't cause any errors.  The surprising side effect was that the variable assigned to was never actually created.

```julia
julia> x = let
           # some ugly calc
           42
       end
42

julia> x
42

julia> y = let
           # some ugly calc
           return 42
       end
42

julia> y
ERROR: UndefVarError: y not defined
```

### LINKED ISSUE #30643: In iterators.jl:1092 and 1095 Stateful{T,VS} is reversed to {VS,T}
https://github.com/JuliaLang/julia/blob/34f7a4a50458594e6d72793b4f371227e8e842e3/base/iterators.jl#L1092

e.g. Stateful(cycle(itr)) claims it has length.

### LINKED ISSUE #30679: StackOverflowError when creating RemoteChannels
I have noticed some strange behavior with RemoteChannel in 1.0.3, that did not occur for me in 1.0.2. I think I have identified a MWE. The following works:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 5)
```
However, if I import some module before the struct definition, the following happens:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> using JuMP

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
ERROR: StackOverflowError:
deserialize(::Distributed.ClusterSerializer{Sockets.TCPSocket}, ::Type{RemoteChannel{Channel{A}}}) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:310 (repeats 100 times)
Stacktrace:
 [1] #remotecall_fetch#149(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:379
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:371
 [3] #remotecall_fetch#152(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Int64, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406
 [4] remotecall_fetch at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406 [inlined]
 [5] RemoteChannel(::Function, ::Int64) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:108
 [6] top-level scope at none:0
```
The error repeats consistently after consecutive attempts of `RemoteChannel(()->Channel{A}(1), 2)`, but if I run some code snippet involving the `A` type on the second node I can suddenly create channels again:
```julia
julia> @fetchfrom 2 A()
A()

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 16)
```
The error does not occur after any model import. For example, `MacroTools`, `Statistics` or seemingly any standard library does not lead to this error. Other large modules that I have tried that does lead to the error are `Plots` and `Distributions`. I have not found any common denominator between model imports that cause this error. My version info:
```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### LINKED ISSUE #30792: Keyword arguments parametric types break matching
This works on Julia 1.0.3

```julia
julia> f(a::C) where {R <: Real, C <: Union{R, Complex{R}}} = println(R)
f (generic function with 1 method)

julia> f(Float64(3))
Float64

julia> f(Float32(3)+Float32(2)im)
Float32
```

but the following does not

```julia 
julia> g(a::C; b=R(1)) where {R <: Real, C <: Union{R, Complex{R}}} = println(R)
ERROR: UndefVarError: R not defined
Stacktrace:
 [1] top-level scope at none:0
```

Discussion here: https://discourse.julialang.org/t/type-matching-with-positional-vs-keyword-arguments/19854

### LINKED ISSUE #30911: deepcopy bug in UnionAll types
Possible bug in deepcopy
```JULIA
julia> x = Array{Float32}
Array{Float32,N} where N

julia> x.var == x.body.parameters[2]
true

julia> x.var
N

julia> y = deepcopy(x)
Array{Float32,N} where N

julia> y == Array{Float32}
true

julia> y = deepcopy(Array{Float32,N} where N)
Array{Float32,N} where N

julia> y == Array{Float32} # !!!
false

julia> y.var == y.body.parameters[2]
false

julia> y.var
N

julia> y.body.parameters[2]
N

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

### LINKED ISSUE #31418: backport fix for Const propagation of uninitialized structs to `v1.1`.
Opening an issue about this so we don't forget.

Today we noticed our code incorrectly const-propagating an unitialized tuple on `julia 1.1`, which it wasn't doing on `julia 1.0`.

This is fixed on `master` by the following lines, introduced in https://github.com/JuliaLang/julia/commit/52bafeb981bac548afd2264edb518d8d86944dca:
https://github.com/JuliaLang/julia/blob/f611b46e72c788c016933033dfadee6a9e138d47/base/compiler/abstractinterpretation.jl#L931-L937

We discussed backporting this fix to a patch release for `v1.1`. Does that still seem doable? 😊Would we backport just those lines, or the whole commit https://github.com/JuliaLang/julia/commit/52bafeb981bac548afd2264edb518d8d86944dca?

Thanks! :)

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #30554 - llvm: fix target triple
- [x] #30564 - fix `lambda-optimize-vars!` with complex assignment RHSs
- [x] #30600 - fix typo in string search api docs
- [x] #30644 - fix #30643, correctly propagate iterator traits through Stateful
- [x] #30655 - SHA,tests: cleanup tempdir
- [x] #30697 - some documentation improvements
- [x] #30689 - improve docstring of SparseMatrixCSC
- [x] #30678 - fix typo in devdocs/sysimg.md
- [x] #30717 - Singleton Types H4 -> H3
- [x] #30716 - fix #30499, document behavior of `return` at top level
- [x] #30747 - fix #28647, add doc string for `Symbol`
- [x] #30745 - Add kw_str for =
- [x] #30754 - Handle :error and :invalid expressions gracefully in REPL helpmode
- [x] #30761 - Fix RemoteChannel example in parallel-computing.md
- [x] #30798 - fix #30792, static param constraints between positional and kw args
- [x] #30804 - fix `at-everywhere using` in Distributed stdlib
- [x] #30821 - Fix signature of git_libgit2_opts
- [x] #30736 - Document indexing by different numbers of indices
- [x] #30884 - isapprox() doc mentioned deprecated 'vecnorm'
- [x] #30895 - Fallback for copying views into sparse matrices
- [x] #30930 - fix #30911, bug in `deepcopy` of `UnionAll`
- [x] #30880 - fix #30679, call correct method for `invoke` calls in `jl_invoke` fallback
- [x] #31047 - fix #29936, precompile should not assume UnionAlls have stable addresses
- [x] #31041 - bump MPFR to 4.0.2
- [x] #30398 - Fix enumerate documentation
- [x] #31312 - allow chop to take an empty string
- [x] #30296 - Fix 29545: Implement unaliascopy for ReinterpretArray
- [x] #31258 - fix undef var in conversion in rounding modes in MPFR
- [x] #30569 - Improve REPL completions
- [x] #31642 - Fix show_vector for long offset arrays with :limit=true
- [x] #31187 - Fix `-`, `conj`, and `conj!` for sparse matrices with invalid entries  in `nzval`
- [x] #31615 - fix parse(ComplexF64, "inf")
- [x] #31443 - minor fixes in multiplication with Diagonals
- [x] #31029 - Update Mozilla CA certificate store to latest (01-23-2019) for libgit2 SSL.
- [x] #31405 - inference: fix typeof-tfunc impl
- [x] #31699 - fix #31418, don't Const-prop unitialized structs

Non-merged PRs with backport label:
- [ ] #31464 - Accept both Cvoid and Ptr{Void} return type in ccall(:memcpy)
- [ ] #31064 - Fix accidental recursion in jl_concrete_subtype
- [ ] #30357 - workaround for F_DUPFD_CLOEXEC on Linux kernel <2.6.24 before it existed

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.1")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31039#issuecomment-483233871) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/08701edeb6adbdeb664a81e0ae1779886af1660a/d5583e0_vs_7132c63/report.md). cc @ararslan

**Comment by fredrikekre** [comment]
- Travis: internet connection error during Pkg tests on macOS.
- `package_freebsd64` looks to have the same gmp issue as https://github.com/JuliaLang/julia/pull/30954#issuecomment-483586398
- `package_macos64` and `package_win64` has the following error:
  ```
  /usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: final link failed: File truncated
  collect2: error: ld returned 1 exit status
  ```

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.1")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31039#issuecomment-483598906) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/f9384cd8ea2035b527df43153aafe480e30f71ff/7b873de_vs_7132c63/report.md). cc @ararslan

**Comment by ararslan** [comment]
PkgEval results: https://gist.github.com/ararslan/8ee7060a539badc996e4226ef02757f3. Regressions in CategoricalArrays (looks okay I think) and YaoBlocks.

**Comment by KristofferC** [comment]
YaoBlocks errors on 1.1.0 for me to.

**Comment by rai-nhdaly** [comment]
(Should we add an entry to the summary block at the top of this PR for #31699?)

Something like:
- [x] #31699 - fix #31418, don't Const-prop unitialized structs

**Comment by ararslan** [comment]
PkgEval says we're good except for CategoricalArrays, which we've determined is fine. I think for FreeBSD CI we'll need a GMP patch?

**Comment by ararslan** [comment]
Elliot fixed CI, so we're all good now.

**Pull request merged**
