### PR TITLE
sync Pkg + introduce home project & active project concepts

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by KristofferC** [comment]
Since this removes `@` from the `LOAD_PATH` it will break CI so we should fix that first? Also, do we want to put the `--project` flag into this PR so everything is ready at once?

**Comment by StefanKarpinski** [comment]
Yes and yes.

**Comment by StefanKarpinski** [comment]
Bam, got that test suite passing finally. Now for more features...

**Comment by tpapp** [comment]
`--project` is still not documented in `julia --help` or the manual, should I open an issue?

**Comment by StefanKarpinski** [comment]
No, that's ok, I'll document it soon. I have to write docs for the whole way the load path is determined.

**Pull request merged**
