### PR TITLE
Decide opaque pointer codepaths at runtime instead of compile time

### PR DESCRIPTION
**Pull request by pchintalapudi**
Ref https://github.com/maleadt/LLVM.jl/pull/337

### CODE REVIEW

**Comment by Keno** [comment]
Would it make sense to keep these in for when LLVM removes non-opaque pointer types entirely in a year or so?

**Comment by Keno** [comment]
Meaning change the non-opaque codepath to support either as you did in this PR, but keep the ifdef?

**Comment by pchintalapudi** [comment]
I don't think the ifdefs here are irreplaceable in the future; transitioning later should be relatively straightforward. The bigger concern then is eliminating the calls to emit_bitcast when we're just casting pointer->pointer.

**Comment by Keno** [comment]
ok

**Comment by maleadt** [comment]
LGTM; but segfaults pretty quickly when doing any `Pkg.test` operation. Not sure whether that was the case before.

```
❯ julia +dev --project --eval 'using Pkg; Pkg.test() '
     Testing Example
...
     Testing Example tests passed
```

```
❯ JULIA_LLVM_ARGS="--opaque-pointers" julia +dev --project --eval 'using Pkg; Pkg.test() '
     Testing Example
[191832] signal (11.1): Segmentation fault
in expression starting at none:1
typekeyvalue_hash at /home/tim/Julia/src/julia/src/jltypes.c:1297 [inlined]
lookup_typevalue at /home/tim/Julia/src/julia/src/jltypes.c:757
jl_inst_arg_tuple_type at /home/tim/Julia/src/julia/src/jltypes.c:1757
arg_type_tuple at /home/tim/Julia/src/julia/src/gf.c:2164 [inlined]
jl_lookup_generic_ at /home/tim/Julia/src/julia/src/gf.c:2947 [inlined]
ijl_apply_generic at /home/tim/Julia/src/julia/src/gf.c:2999
destructure at /home/tim/Julia/src/julia/build/dev/usr/share/julia/stdlib/v1.10/Pkg/src/manifest.jl:269
write_manifest at /home/tim/Julia/src/julia/build/dev/usr/share/julia/stdlib/v1.10/Pkg/src/manifest.jl:322
#115 at /home/tim/Julia/src/julia/build/dev/usr/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1772
#mktempdir#24 at ./file.jl:764
unknown function (ip: 0x7f98f690a92d)
```

**Comment by maleadt** [comment]
Oh yeah I guess LLVM 14 doesn't fully support opaque pointers yet.

> LLVM 14: Supports all necessary APIs for migrating to opaque pointers and deprecates/removes incompatible APIs. However, using opaque pointers in the optimization pipeline is not fully supported.

**Pull request merged**
