### PR TITLE
Fix inference for splatting numbers. Fixes #22291

### LINKED ISSUE #22291: Inference failure for splatting numbers
This fails on at least 0.5.2, 0.6.0-rc2, and master: 

```julia
julia> wrap(ind) = (ind...)
wrap (generic function with 1 method)

julia> wrap(1)
(1,)

julia> using Base.Test

julia> @inferred(wrap(1))
ERROR: return type Tuple{Int64} does not match inferred return type Tuple{Vararg{Int64,N} where N}
Stacktrace:
 [1] error(::String) at ./error.jl:21
```

Fix coming momentarily.

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by martinholters** [comment]
It would be oh so nice if we could do constant propagation to the extent that `abstract_iteration` could figure out the constant length here, but until then this is probably OK. Assuming no-ones defines his own `Number` type which has other iteration properties, that is.

**Comment by Keno** [comment]
> Assuming no-ones defines his own Number type which has other iteration properties, that is.

This is the problem though, because this would generate incorrect code in that case. We can't really have inference operate on the "let's hope nobody ever writes code like this" hypothesis.

**Comment by timholy** [comment]
If there's no better way to fix this, to be perfectly honest I could live with `tt0 <: Union{Int, UInt}`.

**Comment by timholy** [comment]
I guess another option would be to redefine number iterators so that the type system encodes the fact that they have length 1:
```julia
start(x::Number) = Val{false}()
next(x::Number, ::Val{false}) = (x, Val{true}())
done{s}(x::Number, ::Val{s}) = s
```

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/issues/18823 will also address / fix this

**Comment by timholy** [comment]
Given that there is a more general fix on the way, how about I add the `tt0 <: Union{Int, UInt}` as a hack for now? With #22210 I need it for indexing. (Changes in inlining ended up changing the inferred result; presumably we don't want that to happen, but that's where we are now.)

**Comment by martinholters** [comment]
Some more possible solutions that come to my mind:
* #7903
* Do this for `tt0 <: Number` and change `jl_f__apply` to effectively not splat `Number`s. But having splatting subtly different from iteration may be a bit too surprising.
* Do this for `tt0 <: Number` provided that the methods that would be called for `start`, `next`, and `done` for `tt0` are the ones that are defined in `Base` for `Number`.

**Comment by JeffBezanson** [comment]
There is some precedent for inference using a `corenumtype` union to restrict optimizations to known types.

**Comment by timholy** [comment]
This passed tests, so barring objections I'll merge soon.

**Pull request closed without merging**
