### PR TITLE
replace Array{...}(shape...)-like calls in base/linalg/[a-k]*

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request replaces `Array{...}(shape...)`-like calls in base/linalg/[a-k]*.jl and base/linalg/lapack.jl. Ref. #24595. Best!

### CODE REVIEW

**Comment by fredrikekre** [comment]
```
Error in testset linalg/schur:
Error During Test at /tmp/julia/share/julia/test/linalg/schur.jl:83
  Got an exception of type UndefVarError outside of a @test
  UndefVarError: unintialized not defined
```

**Comment by Sacha0** [comment]
The test/linalg/schur failure should be fixed. Thanks! :)

**Comment by Sacha0** [comment]
Absent objections or requests for time, I plan to merge these changes this evening PT or later. Best!

**Review by fredrikekre — APPROVED** [review]

**Comment by Sacha0** [comment]
Thanks `@fredrikekre`! :)

**Pull request merged**
