### PR TITLE
Update libgit2 to v0.27.7

### PR DESCRIPTION
**Pull request by ararslan**
Currently we're using v0.27.2. The full commit diff between 0.27.2 and 0.27.7 can be viewed [here](https://github.com/libgit2/libgit2/compare/v0.27.2...v0.27.7). According to the release notes for some of the the interim versions (https://github.com/libgit2/libgit2/releases), we're currently missing out on security and bug fixes.

### CODE REVIEW

**Comment by staticfloat** [comment]
Looks like our patches do not apply cleanly anymore.  😱

**Comment by ararslan** [comment]
Boooooooo. I'll fix them...

**Comment by omus** [comment]
I believe most of the patches shouldn't be needed anymore. I'm rather pumped about this as it'll fix this  problem: https://github.com/JuliaLang/julia/blob/master/stdlib/LibGit2/src/gitcredential.jl#L227

**Comment by ararslan** [comment]
Ah, the patches don't apply anymore because we're using the diff from a PR that touches their `.travis.yml` file, which has since been removed, as they've switched their CI to Azure pipelines.

**Comment by ararslan** [comment]
macOS error: https://travis-ci.org/JuliaLang/julia/jobs/475511047#L642 :thinking:

**Comment by ararslan** [comment]
The 32-bit Windows failure is #29880 and the macOS failure should be fixed by #30599.

**Review by omus — APPROVED** [review]
LGTM. I was hoping we'd be able to drop some patches with this update. Oh well.

**Pull request merged**
