### PR TITLE
Improve consistency of similar methods operating on sparse matrices and flesh them out

### LINKED ISSUE #17456: [bug] in sparse transposition and multiplication whith Diagonal
this is happening on julia master

``` julia
julia> a = sprand(4,4,0.5)
julia> a*a # ok
julia> a*a' # ok
julia> Diagonal(a) * a # ok
julia> Diagonal(a) * a' 
ERROR: ArgumentError: the length of destination argument `X`'s `rowval` array, `length(X.rowval) (= 0)`, must be greater than or equal to source argument `A`'s allocated entry count, `nnz(A) (= 12)`
 in ftranspose!(::SparseMatrixCSC{Float64,Int64}, ::SparseMatrixCSC{Float64,Int64}, ::Function) at ./sparse/sparsematrix.jl:706
 in A_mul_Bc(::Diagonal{Float64}, ::SparseMatrixCSC{Float64,Int64}) at ./linalg/diagonal.jl:176
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

julia> Diagonal([1,1,1,1]) * a' # also not ok
ERROR ...
```

Cheers, 
Carlo

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request's first commit: (1) makes `similar` methods operating on `SparseMatrixCSC`s more consistent both among themselves and with other `similar` methods in Base; and (2) fleshes those methods out. The second commit thoroughly tests those `similar` methods. The first commit fixes JuliaLang/julia#17456, and the second covers (tests) JuliaLang/julia#17456's underlying cause. Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
The [AV i686 failure](https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4370/job/1j3t7h3we05ql3vs) appears unrelated, but the [Travis i686 failure](https://travis-ci.org/JuliaLang/julia/jobs/146176083) appears real. I can't reproduce the latter locally though, and inspecting the test output
```
From worker 4:	     * sparse               Test Failed
From worker 4:	  Expression: sparse(Fs[:L]) ≈ Lfp
From worker 4:	   Evaluated: 
From worker 4:		[1, 1]  =  6.08276
From worker 4:		[2, 1]  =  -7.06916
From worker 4:		[3, 1]  =  1.97279
From worker 4:		[2, 2]  =  6.93015
From worker 4:		[3, 2]  =  -0.296394
From worker 4:		[3, 3]  =  0.142334 isapprox [6.08276 0.0 0.0; -7.06916 6.93015 0.0; 1.97279 -0.296394 0.142334]
```
suggests that the result is correct, but perhaps not within some tolerance? Thanks!

**Comment by Pbellive** [comment]
Hi. I'm wondering if there's still a plan to fix the CI issues with this PR and get it merged? I just ran into https://github.com/JuliaLang/julia/issues/17456 on Julia 0.5.1 (commit a6c55c5*). Also checked that it still exists on master (commit d6088fc*). I feel a bit silly asking about this when I don't know enough to debug why the CI checks are failing but I thought I'd check in to see if it's just been forgotten about. Is it worth merging this work into an up to date version of `Base` and submitting a new PR? If so I could try doing that. Thanks!

**Comment by Sacha0** [comment]
(Leaving a breadcrumb to #22009 and #23905 for changes during resuscitation of this pull request.)

**Comment by Sacha0** [comment]
Rewritten. What say you now, CI?

**Comment by mbauman** [comment]
Possible alternative: have similar return a reshaped sparse vector for cases where N > 2.  This has two advantages:

* Doesn't unexpectedly blow up memory use
* Will get better performance over time as we add optimizations for reshaped sparse arrays.

**Comment by Sacha0** [comment]
@mbauman, did you intend the above comment for #23905? How to handle `Dim{0}` and `Dim{N>2}` are somewhat orthogonal to this pull request, which primarily addresses #17456 and related issues. Best!

**Comment by mbauman** [comment]
I guess, sure, but doesn't this PR also implicitly fix #23905 by removing the definition for `similar(S::SparseMatrixCSC, ::Type{Tv}, d::Dims)`?  I guess it doesn't matter so much where we discuss it; it was just a brainstorm suggestion.  I'd wager folks who use sparse matrices would almost rather an immediate error here rather than blowing up their storage.  But I'm not one of those folks, so it's not a strong suggestion.

**Comment by Sacha0** [comment]
Yes, as a side effect this pull request partially addresses #23906, and the sequel for `SparseVector`s should similarly cover another part as a side effect. But this pull request's primary target is #17456 and related issues, and I would much appreciate keeping this thread tight and decoupled from broader design questions :). (Your suggestion is quite clever by the by!)

**Comment by Sacha0** [comment]
All test failures appear unrelated, except for the CircleCI i686 failure, which is bizarre:
```julia
Some tests did not pass: 1817 passed, 1 failed, 0 errored, 0 broken.sparse/sparse: Test Failed
  Expression: transpose(view(speye(10), 1:5, 1:5)) ≈ eye(5, 5)
   Evaluated: 
  [1, 1]  =  1.0
  [2, 2]  =  1.0
  [3, 3]  =  1.0
  [4, 4]  =  1.0
  [5, 5]  =  1.0 ≈ [1.0 0.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0 0.0; 0.0 0.0 1.0 0.0 0.0; 0.0 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 0.0 1.0]
```
On the one hand, this failure is quite similar to [the failure that blocked this pull request better than a year ago on Travis i686](https://github.com/JuliaLang/julia/pull/17507#issuecomment-234076017): The failure is also on i686, the report suggests that the test should pass, and I cannot reproduce the failure locally. On the other hand, and what makes the failure seem particularly strange, is that Travis i686 now passes. Any insight would be much appreciated!

**Comment by Sacha0** [comment]
(Seems the failure was either unrelated or related but nondeterministic, as CircleCI i686 passed this round.)

**Comment by Sacha0** [comment]
Another form of the same failure appeared this round on Travis x86_64 Linux:
```julia
Error in testset sparse/sparse:
Test Failed
  Expression: f(arr, 1) ≈ f(farr, 1)
   Evaluated: 
  [1, 2]  =  -0.47132
  [1, 3]  =  -0.463003
  [1, 4]  =  0.0
  [1, 5]  =  -0.848927
  [1, 6]  =  -0.509547
  [1, 7]  =  -0.478014 ≈ [0.0 -0.47132 -0.463003 0.0 -0.848927 -0.509547 -0.478014]
```
So this issue is not confined to 32-bit platforms. I will see whether I can reproduce this locally via repeated runs.

**Comment by Sacha0** [comment]
Reduced to an issue with `vecnorm(A::SparseMatrixCSC, ...)`, which should be fixed by #24204. Best!

**Comment by Sacha0** [comment]
Confirming that #24204 seems to fix the stress test I have locally exercising the nondeterministic CI failure. Cycling CI. Best!

**Comment by Sacha0** [comment]
Absent objections or requests for time, I plan to merge these changes this evening (assuming CI clears). Best!

**Comment by Sacha0** [comment]
Thanks all! :)

**Pull request merged**
