### PR TITLE
Better error message for convert(::Type{Union{}}, ::Int)

### LINKED ISSUE #36706: Better error on pushing an element of wrong type onto an array.
When I push an integer onto an array of element type `Nothing`, I get a really weird error which is not helpful at all. Here is the code and the error:

```julia
julia> stack = [nothing]
1-element Array{Nothing,1}:
 nothing

julia> push!(stack, 1)
ERROR: MethodError: convert(::Type{Union{}}, ::Int64) is ambiguous. Candidates:
  convert(::Type{Union{}}, x) in Base at essentials.jl:169
  convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7
  convert(::Type{T}, arg) where T<:VecElement in Base at baseext.jl:8
  convert(::Type{T}, x::Number) where T<:AbstractChar in Base at char.jl:179
Possible fix, define
  convert(::Type{Union{}}, ::Number)
Stacktrace:
 [1] convert(::Type{Nothing}, ::Int64) at ./some.jl:34
 [2] push!(::Array{Nothing,1}, ::Int64) at ./array.jl:912
 [3] top-level scope at REPL[11]:1

julia>
```

### PR DESCRIPTION
**Pull request by ArunS-tack**
Closes #36706.

### CODE REVIEW

**Review by Keno — CHANGES_REQUESTED** [review]
This does not work. Right now you're switching an error throw to a print. Those are not the same thing. In particular, here execution will continue with a `nothing` return value.

**Comment by ArunSanganal** [comment]
I did check it before making this PR though. It shows the error in `show_convert_error` and doesn't actually execute it.

**Comment by ArunSanganal** [comment]
Or do you mean under the hood, it will actually have executed to `Nothing` but visually prints the error?

**Comment by ArunSanganal** [comment]
@Keno can you review the changes again?  I think it `throws` the error now instead of just printing.

**Pull request closed without merging**
