### PR TITLE
Stop building and shipping openspecfun

### LINKED ISSUE #22390: Actually decouple special function (openspecfun) from base
`SpecialFunctions` relies on `openspecfun` from  Base. Like `FFTW` would the next logical step be to have `SpecialFunctions` actually carry out the build process instead of in base

### PR DESCRIPTION
**Pull request by ararslan**
At this point, this should be a non-functional change, since openspecfun isn't being used internally anymore as of #22603. It is technically breaking, however, since any code that was referencing `Base.Math.openspecfun` or explicitly `ccall`ing into openspecfun will be broken.

~I'm marking this as WIP until I have binary downloading/building finished in SpecialFunctions. (It's close.) Once that's done I'll remove the "WIP."~ Ready. 😎 

Fixes #22390.

### CODE REVIEW

**Comment by ararslan** [comment]
@jlbuild !nuke
```
Pkg.clone("https://github.com/JuliaMath/SpecialFunctions.jl.git")
Pkg.checkout("SpecialFunctions", "master")
Pkg.build("SpecialFunctions")
Pkg.test("SpecialFunctions")
```

**Comment by ararslan** [comment]
Okay, I'm not sure whether jlbuild is still up and running, but either way this works on CI using the binaries I built for it as well as locally on a system without binaries, so I guess the jlbuild run should be mostly unnecessary anyway.

So this is good to go!

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/569e757ffe07de73c0e1c99817117b241879abbc

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/569e757ffe07de73c0e1c99817117b241879abbc

I will edit this comment as the build jobs complete.

**Comment by staticfloat** [comment]
Hmmm, so something is borked in `jlbuild`, I'm getting backtraces from `HTTP.jl`:

```
app_1  | ERROR (unhandled task failure): write: broken pipe (EPIPE)
app_1  |  in yieldto(::Task, ::ANY) at ./event.jl:136
app_1  |  in wait() at ./event.jl:169
app_1  |  in stream_wait(::Task) at ./stream.jl:44
app_1  |  in uv_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:820
app_1  |  in unsafe_write(::TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
app_1  |  in write(::TCPSocket, ::Array{UInt8,1}) at ./io.jl:175
app_1  |  in write(::TCPSocket, ::HttpCommon.Response) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:182
app_1  |  in (::HttpServer.#on_message_complete#18{HttpServer.Server,HttpServer.Client{TCPSocket},Bool})(::HttpCommon.Request) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:447
app_1  |  in on_message_complete(::Ptr{HttpParser.Parser}) at /root/.julia/v0.5/HttpServer/src/RequestParser.jl:113
app_1  |  in http_parser_execute(::HttpParser.Parser, ::HttpParser.ParserSettings, ::Array{UInt8,1}) at /root/.julia/v0.5/HttpParser/src/HttpParser.jl:115
app_1  |  in process_client(::HttpServer.Server, ::HttpServer.Client{TCPSocket}, ::Bool) at /root/.julia/v0.5/HttpServer/src/HttpServer.jl:389
app_1  |  in (::HttpServer.##8#10{HttpServer.Server,Bool})() at ./task.jl:360
```

In any case, I'm going to kick the server over and see if that fixes anything.

**Comment by ararslan** [comment]
If you've kicked the server, should I try invoking jlbuild again?

**Comment by staticfloat** [comment]
It looks like there are unrelated testing errors with the buildbots.  :/

**Comment by ViralBShah** [comment]
Unrelated here, but we had at some point discussed translating the openspecfun code to Julia using @nolta 's script. That might be worth visiting once this is split off and stabilized(but obviously some non-trivial work).

**Review by staticfloat — APPROVED** [review]

**Pull request merged**
