### PR TITLE
include the `[]` doc string into the docs

### PR DESCRIPTION
**Pull request by nsajko**

### CODE REVIEW

**Review by nsajko — COMMENTED** [review]
The entry for `[]` renders correctly in the PDF rendition of the manual, and all links lead where they're supposed to. Screenshot:

square_brackets

**Comment by nsajko** [comment]
bump

**Comment by nsajko** [comment]
ping

**Comment by nsajko** [comment]
bump

**Comment by nsajko** [comment]
ping

**Review by lgoettgens — APPROVED** [review]

**Pull request merged**
