### PR TITLE
RFC: Remove deprecated primes and combinatorics functions from Base

### PR DESCRIPTION
**Pull request by ararslan**
These functions were present in 0.4, are deprecated in 0.5 in favor of JuliaMath packages, and—if I understand the deprecation cycle correctly—should now be removed in 0.6. If that's not the case, we can close the PR or let it stagnate until they're ready to be removed.

Having `isdefined(Base, :isprime) == true` (and likewise for other functions) is messing with the documentation for Primes.jl generated by Documenter; it calls them `Base.isprime`, etc. So it would be nice from that perspective if that were now `false`.

### CODE REVIEW

**Comment by ararslan** [comment]
The 32-bit Windows failure is both unrelated and strange.

**Comment by tkelman** [comment]
This is a little earlier than we usually remove deprecations, but I guess if it's causing problems then ok. Won't you need a solution to the Documenter issue with Primes.jl on 0.5?

**Comment by ararslan** [comment]
> This is a little earlier than we usually remove deprecations

Okay, feel free to close or just let the PR stagnate, then when it's ready to be removed I can reopen or rebase as necessary. I'm fine with whatever. 👍 

> Won't you need a solution to the Documenter issue with Primes.jl on 0.5?

Yep. So far my solution is "hope users aren't confused by the docs listing the functions with the `Base` prefix." I'm at a loss for something better.

**Comment by tkelman** [comment]
travis can be finicky about when changes to the yml file take effect, here for the llvm version switch - this passed CI a few months ago, going to just squash merge

**Pull request merged**
