### PR TITLE
remove hpl.jl since it is outdated

### PR DESCRIPTION
**Pull request by zhmz90**
I found some syntax errors exist in this file, tried to run this example and failed due to not really understand what it is doing yet. I also checked the commit log of this file but just to try the new git command I learned. 
It is @tkelman who really found this file is outdated in #16771.  
I didn't find @tkelman make a new PR for this so I make this PR.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@tkelman Can we simply not remove the whole examples directory? Does anything depend on it being there?

**Comment by yuyichao** [comment]
I believe the `examples` test actually run some of the code there.

**Comment by ViralBShah** [comment]
Maybe delete that too - I doubt it is testing much that is not otherwise tested.

**Comment by tkelman** [comment]
I would want to check coverage closely before believing that.

**Comment by amitmurthy** [comment]
I think the examples are actually useful for someone writing their own `ClusterManager`, `RemoteChannel` or custom `Topology`. Some of the manual entries do point to them.

**Comment by zhmz90** [comment]
This PR just only try to remove `examples/hpl.jl` which is outdated. I do believe the examples directory is useful since I prefer to learn from code better than just words. The checks have passed so that it must be no tests which cover `hpl.jl`.

**Comment by tkelman** [comment]
x-ref https://github.com/JuliaLang/julia/issues/7332#issuecomment-46966167

**Pull request merged**
