### PR TITLE
grisu_license_headers [skip ci]

### PR DESCRIPTION
**Pull request by peter1000**
https://github.com/JuliaLang/julia/pull/11078
https://github.com/JuliaLang/julia/pull/11073#issuecomment-98090053

### CODE REVIEW

**Comment by peter1000** [comment]
sorry I messed up the other PR doing something wrong with git.

**Comment by tkelman** [comment]
Sorry I wasn't completely, clear, I meant to still include the BSD license after the header, just with the description before it.

What went wrong specifically? It's a little cleaner to force push into the same PR if you can.

**Comment by tkelman** [comment]
It might've been an annoying bug with github where if you force push to a PR branch while the PR is closed then you can't reopen it, in which case don't close the PR :)

**Comment by peter1000** [comment]
> I meant to still include the BSD license after the header, just with the description before it.

I see

**Comment by peter1000** [comment]
Updated the PR should be fine now

**Comment by tkelman** [comment]
Great, I think we can merge this if no one objects. Sounds like the consensus in #11023 was it's fine to move towards license headers. Everyone prefers short where possible for our own code, but good to make things clear for code like this that is derived from existing libraries.

**Pull request merged**
