### PR TITLE
Changed issym to issymmetric.

### LINKED ISSUE #15182: Matrix API: Why is it issym, but ishermitian ?
Is there any reason for the function name `issym` instead of `issymmetric` when it is not `isher` but `ishermitian`?

### PR DESCRIPTION
**Pull request by pkofod**
Fixes #15182  .

grepping `/julia/` tells me that there is an `issym` variable in some `.c`-files left, but they should obviously not be changed (they are boolean variables asking if a variable is a symbol by the way, so that strengthens the need for being precise). 

There is something I still need to do. `grep -r issym` still tells me (relevant) `issym`'s still live in
`contrib/BBEditTextWrangler-julia.plist`
`base/docs/helpdb/Base.jl`
`doc/stdlib/linalg.rst`

I am unsure how the documentation system works in julia. Should I just change these files as well, or are some things auto-generated, and others are not - or? Thanks.

Edit: Obviously also need to deprecate `issym`, will do in the morning

### CODE REVIEW

**Comment by andreasnoack** [comment]
Regarding the documentation then check out https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation. However, it can be a little confusing so feel free to ask.

**Comment by pkofod** [comment]
Thanks for the pointer. I hope I did it correctly, let's see if it builds on the CI-services.

I also `@deprecated issym issymmetric`.

**Comment by pkofod** [comment]
I had missed an `issym` in `linalg/dense.jl`, but only the linux builds failed on travis, the OSX builts were OK. Is that supposed to be possible? https://travis-ci.org/JuliaLang/julia/builds/111159068

**Comment by tkelman** [comment]
OSX Travis is not currently running all tests to avoid timing out.

This looks good, thanks! I like `git grep` for this kind of renaming check.

**Comment by pkofod** [comment]
Sounds like i could have benefitted from git grep. Cool, will use that next time.

**Comment by pkofod** [comment]
Are there others places to correct the change than the docs and `@deprecate`ing the old name?

**Comment by tkelman** [comment]
Worth adding a note about the renaming to `NEWS.md` perhaps?

**Comment by pkofod** [comment]
I've added a bullet. I chose `favor` in favour of `favour`, but both seem to be used throughout `NEWS.md`.

**Comment by pkofod** [comment]
I force pushed the change, so unfortunately your message is gone, but I've moved it to the correct section.

**Comment by pkofod** [comment]
Sorry, I actually remember having read that you should do that when adding something to `NEWS.md`. Thanks.

**Comment by andreasnoack** [comment]
@pkofod Could you rebase this?

**Comment by pkofod** [comment]
@andreasnoack I will fix it later, but yes.

**Comment by pkofod** [comment]
I hate and love git. Kind of messed the rebase up, but was able to go back, and it should be :+1: now

**Comment by pkofod** [comment]
What on earth did I do to make it build all the dependencies and fail? Did I err, or is it a travis thing?

**Comment by tkelman** [comment]
The Travis caching for dependencies was in a messed-up state, ref #15249, but it's fixed now - restarted.

**Comment by pkofod** [comment]
Thanks!

**Comment by andreasnoack** [comment]
@pkofod Thanks. It would be great if you could also add an entry to `Compat.jl` for `issymmetric`.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Compat.jl/pull/175/files for a similar PR to compat.

**Comment by pkofod** [comment]
Sure, I'll do it later!

**Pull request merged**
