### PR TITLE
add RemoteLogger for distributed logging

### LINKED ISSUE #51: Need better control over worker logging
Currently, even if you define your own `AbstractLogger` and set `Base.global_logger(mylogger)`, worker loggers still prepend `"        From worker X: ` to all logs.

My current work-around is doing
```julia
using Distributed
function Distributed.redirect_worker_output(ident, stream)
           @schedule while !eof(stream)
               println(readline(stream))
           end
       end
using MyPkg
MyPkg.run()
```
So hurray for JuliaLang/julia#265 and all, but we really need better controls here.

### LINKED ISSUE #25929: Need better control over worker logging
Currently, even if you define your own `AbstractLogger` and set `Base.global_logger(mylogger)`, worker loggers still prepend `"        From worker X: ` to all logs.

My current work-around is doing
```julia
using Distributed
function Distributed.redirect_worker_output(ident, stream)
           @schedule while !eof(stream)
               println(readline(stream))
           end
       end
using MyPkg
MyPkg.run()
```
So hurray for #265 and all, but we really need better controls here.

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes JuliaLang/Distributed.jl#51

This is a pretty crude implementation: it simply `remotecall`s the logger on the main process, attaching a keyword `pid` to indicate which process triggered it, but I hope it can serve as a starting point. 

The main downside of this approach is that it doesn't respect changes to the current logger on the main task, e.g.
```julia
with_logger(mylogger) do
   remotecall_wait(() -> @info("msg"), 2)
end
```
will still log to the global logger on the main process, not `mylogger`. This also means I can't test this using `@test_logs`. I don't see an easy way to fix this without something like JuliaLang/julia#35757.

The other open question is when/where should the logger be instantiated?

### CODE REVIEW

**Comment by simonbyrne** [comment]
@c42f any thoughts?

**Comment by simonbyrne** [comment]
okay, added a test

**Comment by ViralBShah** [comment]
cc @tanmaykm

**Comment by simonbyrne** [comment]
bump?

**Comment by vtjnash** [comment]
I didn't review, but now needs to be reopened at https://github.com/JuliaLang/Distributed.jl for https://github.com/JuliaLang/Distributed.jl/issues/52

**Pull request closed without merging**
