### PR TITLE
String(v::SubArray{UInt8,1}) = String(Vector{UInt8}(v))

### PR DESCRIPTION
**Pull request by samoconnor**

### CODE REVIEW

**Comment by ararslan** [comment]
Hey Sam, thanks for the contribution! Could you provide some context for this change? That is, does it address a particular issue, fix a bug, improve performance, or something else? Also if you could add a test that hits this method, that would be awesome.

**Comment by JeffBezanson** [comment]
Maybe we should just expand it to `AbstractArray`?

**Comment by samoconnor** [comment]
Hi @ararslan, I was working on this https://github.com/JuliaWeb/HTTP.jl/pull/135 and found that it was useful to use `SubArray{UInt8}` to avoid copying data when processing HTTP messages. I want the users to be able to do `String(some_data_returned_by_the_http_package)` to get a string containing the message body. Doing `String(collect(some_data))` or `String(Vector{UInt8}(some_data))` is inconvenient.

I think Jeff is right, `String(v::AbstractArray{UInt8,1}) = String(Vector{UInt8}(v))` would be better (maybe any place where that `Foo(Bar{T})` is defined, it makes sense to define `Foo(v::AbstractBar{T}) = Foo(Bar{T}(v)` ?).

I can't think of a useful test case, assuming that `Vector{Uint8}(::AbstractArray{UInt8})` and `String(::Vector{UInt8})` are already validated, the new method should be correct by definition.

**Comment by JeffBezanson** [comment]
This would be more efficient:

```
function String(a::AbstractArray{UInt8})
    v = StringVector(length(a))
    copyto!(v, a)
    String(v)
end
```

**Comment by samoconnor** [comment]
Ok.
`StringVector` is new to me.
Is it best for me to close the PR and let you paste the above function into wherever you think it should go?

**Comment by JeffBezanson** [comment]
Sure, I can do that.

**Pull request closed without merging**
