### PR TITLE
fix for eig(A,B) actually only using B

### PR DESCRIPTION
**Pull request by mweastwood**
Previously:

```
julia> A = rand(10,10)
       A = A+A'
       B = rand(10,10)
       B = B+B'
       D,V = eig(A,B)
       @show norm(A*V - B*V*diagm(D))
       @show norm(B*V - V*diagm(D))
norm(A * V - B * V * diagm(D)) = 79.49952236628998
norm(B * V - V * diagm(D)) = 5.836760153747318e-15
```

After this fix:

```
julia> A = rand(10,10)
       A = A+A'
       B = rand(10,10)
       B = B+B'
       D,V = eig(A,B)
       @show norm(A*V - B*V*diagm(D))
       @show norm(B*V - V*diagm(D))
norm(A * V - B * V * diagm(D)) = 1.316021077434894e-14
norm(B * V - V * diagm(D)) = 5.841782300334198
```

### CODE REVIEW

**Comment by kshyatt** [comment]
Why didn't this get caught by tests? @mweastwood, could you turn your example above into a test so this doesn't happen again?

**Comment by mweastwood** [comment]
The tests only check that the method runs without error. They do not check the output. I'll try and fix that.

**Comment by mweastwood** [comment]
Ok, I've added tests that fail without the first commit.

**Comment by andreasnoack** [comment]
@mweastwood Thanks for fixing my bug.

**Pull request merged**
