### PR TITLE
deprecate bin, oct, dec, hex, and base in favor of `string` and keyword args

### PR DESCRIPTION
**Pull request by JeffBezanson**
Updated version of #25717

### CODE REVIEW

**Comment by Keno** [comment]
Looks like strings/basic is failing.

**Comment by JeffBezanson** [comment]
Now stuck on a mysterious inference failure. Haven't seen this one in a long time:

```
Error During Test at C:\projects\julia\julia-0aa48c105f\share\julia\test\numbers.jl:2870
  Got an exception of type ErrorException outside of a @test
  return type Rational{UInt128} does not match inferred return type Rational{_1} where _1
```

**Comment by StefanKarpinski** [comment]
Bump.

**Comment by JeffBezanson** [comment]
Still no dice on the mystery inference problem.

**Comment by Keno** [comment]
Rebased. I don't see the mystery inference failure locally, so maybe it went away.

**Comment by JeffBezanson** [comment]
Still happening on travis i686 :(

**Comment by martinholters** [comment]
On this branch, built for i686:
```julia
julia> Core.Compiler.return_type(+, Tuple{Rational{UInt128}, Rational{UInt128}})
Rational{_1} where _1

julia> Core.Compiler.return_type(Base.divgcd, Tuple{UInt128, UInt128})
Tuple{Any,Any}

julia> Core.Compiler.return_type(div, Tuple{UInt128, UInt128})
Any

julia> code_warntype(div, Tuple{UInt128,UInt128})
Variables:
  x::UInt128
  y::UInt128

Body:
  begin
      Core.SSAValue(0) = $(Expr(:invoke, MethodInstance for BigInt(::UInt128), :(Base.BigInt), :(x)))::BigInt
      Core.SSAValue(1) = $(Expr(:invoke, MethodInstance for BigInt(::UInt128), :(Base.BigInt), :(y)))::BigInt
      # meta: location gmp.jl div 411
      Core.SSAValue(5) = $(Expr(:invoke, MethodInstance for tdiv_q(::BigInt, ::BigInt), Base.GMP.MPZ.tdiv_q, Core.SSAValue(0), Core.SSAValue(1)))::BigInt
      # meta: pop location
      Core.SSAValue(3) = $(Expr(:invoke, MethodInstance for UInt128(::BigInt), :(Base.UInt128), Core.SSAValue(5)))::UInt128
      return Core.SSAValue(3)
  end::UInt128

julia> Core.Compiler.return_type(div, Tuple{UInt128, UInt128})
UInt128

julia> Core.Compiler.return_type(Base.divgcd, Tuple{UInt128, UInt128})
Tuple{Any,Any}

julia> code_warntype(Base.divgcd, Tuple{UInt128,UInt128})
# ...
  end::Tuple{UInt128,UInt128}

julia> Core.Compiler.return_type(Base.divgcd, Tuple{UInt128, UInt128})
Tuple{Any,Any}
```
WAT?

(My guess for the platform-specificity here  is that `div(::UInt128, ::UInt128)` uses `BigInt` internally on 32bit platforms.)

It looks like this can be worked around by a type assertion (to be pushed momentarily), but it would be nice to figure out what causes this weird behavior.

**Comment by martinholters** [comment]
I can confirm the source of the platform-specificity. With
```diff
--- a/base/int.jl
+++ b/base/int.jl
@@ -645,7 +645,7 @@ widemul(x::Number,y::Bool) = x * y
 
 ## wide multiplication, Int128 multiply and divide ##
 
-if Core.sizeof(Int) == 4
+if true
     function widemul(u::Int64, v::Int64)
         local u0::UInt64, v0::UInt64, w0::UInt64
         local u1::Int64, v1::Int64, w1::UInt64, w2::Int64, t::UInt64
```
the same failures show on 64bit systems (without the type-assertion work-around, of course).

**Pull request merged**
