### PR TITLE
rewrite a few eye calls in test/broadcast.jl

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request rewrites a few `eye` calls in test/broadcast.jl in keeping with the surrounding style. Ref. JuliaLang/LinearAlgebra.jl#454. Best!

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]
I guess it does not really matter, since that is not the point of these tests, but perhaps the `eye(2)` calls should be `[1. 0.; 0. 1.]` to keep the eltype?

**Comment by Sacha0** [comment]
> I guess it does not really matter, since that is not the point of these tests, but perhaps the eye(2) calls should be [1. 0.; 0. 1.] to keep the eltype?

Yes, to precisely preserve the test the literals should be `Float64`. The `Int` literals seem in better keeping with the spirit of the tests though :).

**Comment by fredrikekre** [comment]
> The `Int` literals seem in better keeping with the spirit of the tests though :).

Yes, I agree

**Comment by Sacha0** [comment]
Thanks all! :)

**Pull request merged**
