### PR TITLE
Greatly simplify dlpath() implementation on OSX

### PR DESCRIPTION
**Pull request by staticfloat**
Addresses https://github.com/JuliaLang/julia/pull/11292#issuecomment-102729304

### CODE REVIEW

**Comment by vtjnash** [comment]
Should this also clear the mode flags from the return value before the comparison?

**Comment by staticfloat** [comment]
I was under the impression that the default set of dlopen flags was the baseline, so I wouldn't be screwing anything up if I used them. If not, how would I do what you're suggesting?

**Comment by vtjnash** [comment]
Mask the low bits like it has in the Apple source code, like it had previously:

>-            handle = (void*)((intptr_t)handle | 1); // in order to trigger findExportedSymbol instead of findExportedSymbolInImageOrDependentImages. See `dlsym` implementation at http://opensource.apple.com/source/dyld/dyld-239.3/src/dyldAPIs.cpp)

(Posting from my phone so I can't search for the exact line)

**Comment by staticfloat** [comment]
Ah, I see what you mean.  No, the bitmasking that was going on there is only useful as input to `dlsym()`.  We're not doing that anymore since we're not calling `dlsym()`, and we don't need to worry about it when doing comparisons because all other functions won't be passing back handles with mode flags set.

**Comment by vtjnash** [comment]
The mode flags are set by dlopen And thus may be set on the original pointer.

**Comment by staticfloat** [comment]
Ah, darn, you are correct, `RTLD_FIRST` can muck with things here.  Just for safety, in case there are more flags that they'll add in the future, I'm using the same method to clear the flags as used in `dlsym()`.  Fixed in 3504a6b.

**Comment by vtjnash** [comment]
Thanks! Is it worth posting this back to the SO page where the original code came from?

**Comment by staticfloat** [comment]
http://stackoverflow.com/questions/20481058/find-pathname-from-dlopen-handle-on-osx/30293362#30293362

**Pull request merged**
