### PR TITLE
code loading revamp

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by amitmurthy** [comment]
My understanding is that the current mechanism of code loading from node 1 addresses two important issues:

1. Modules/packages do not have to be installed on each node in a cluster (only Julia image is required). For users *it just works*. `Pkg.add` on the master and code is available on all workers.

2. Precompilation requires locking of the cache file. This is currently achieved by sending all requests to node 1 which internally ensures a safe compilation in the presence of multiple concurrent requests.

We need to just change the behavior of `using` to only load code on the calling process. It should still request code from node 1, with one additional check. For large clusters, say 100 workers and above, all workers loading code loading from node 1 is not very efficient. Therefore, on workers, loading should first check if the requested module is available in the current system image (built via `userimg.jl` and `build_sysimg`) and only if unavailable load from node 1. Folks running on larger clusters will deploy custom images.

**Comment by amitmurthy** [comment]
I had attempted this in https://github.com/JuliaLang/julia/pull/19073. However, my limited understanding of the code loading process is holding up my taking it to completion.

**Comment by StefanKarpinski** [comment]
My plan is to add support for pluggable code discovery and loading so that loading code from other nodes is an opt-in feature. Pkg3-style code loading where what you load is specified in environment files is going to be another way of discovering and loading code. I figured that pulling features like this out was the first step before providing a way to put them back in again.

**Comment by amitmurthy** [comment]
> I figured that pulling features like this out was the first step before providing a way to put them back in again.

1. As long as both are part of same point release, should not be an issue. Otherwise it will be a pretty serious breakage for folks on multiple nodes.

2. On the same node too, issues related to precompilation have to be addressed. Access to the file is currently synchronized since everyone goes through node 1. Synchronization has to be via `flock` or equivalent. Need to also consider `flock` support on network file systems.

**Comment by JeffBezanson** [comment]
We need to lock the package cache anyway, in case multiple independent julia processes are running on the same machine. I would say that's a separate issue from using node 1 for loading.

**Comment by JeffBezanson** [comment]
In my experience, having all nodes load from node 1 is unreliable. If there are slight differences between the nodes things can easily break --- for example packages with binary dependencies installed in different locations. I think the system is much easier to reason about if loading is local by default. People expect to need to provision each node with all needed software.

**Comment by amitmurthy** [comment]
>  I would say that's a separate issue from using node 1 for loading.

Separate issue maybe, but preferably tackled in the same PR - at least a basic version that works reliably with local filesystems. Else we are going to see issues with even local addprocs failing with module precompilation issues.

> I think the system is much easier to reason about if loading is local by default. People expect to need to provision each node with all needed software.

Not disagreeing with what needs to be done. Just that I think it is a bit premature to drop something that works for most common cases without having a good working alternative in place.

**Comment by StefanKarpinski** [comment]
Closed in favor of ongoing work in https://github.com/JuliaLang/julia/pull/19866.

**Pull request closed without merging**
