### PR TITLE
Don't sink ptrtoint/inttoptr sequences into non-noop addrspacecasts.

### PR DESCRIPTION
**Pull request by maleadt**
This miscompilation causes multiple issues with CUDA.jl, e.g., https://github.com/JuliaGPU/CUDA.jl/issues/558

Patch has been submitted upstream: https://reviews.llvm.org/D92210

I'll kick off a manual build with `USE_BINARYBUILDER_LLVM=0`: https://build.julialang.org/#/builders/47/builds/3

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]
Can you open an issue/PR against Yggdrasil?

**Comment by maleadt** [comment]
> Can you open an issue/PR against Yggdrasil?

I will, but wanted to run CI here first. That failed though; looks like our new CI bots can't compile LLVM: macos64 doesn't have cmake, win* fails to compile. cc @christopher-dG, maybe?

**Comment by vchuravy** [comment]
I think @vtjnash noted the other day that one can't cross-compile LLVM from cygwin anymore.

**Comment by maleadt** [comment]
Ah, I see. Well, I'll do the Yggdrasil change then and add the new tarballs here for CI to test that way.

**Comment by vchuravy** [comment]
Don't forget to remove the old checksums and get new ones.

**Comment by maleadt** [comment]
Not used to all that green! linux64 failure is https://github.com/JuliaLang/julia/issues/38631, so this should be good to go.

**Pull request merged**
