### PR TITLE
Backports for 1.11.2

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #55886 
- [x] #55867 
- [x] #56084 
- [x] #56088 
- [x] #54093 
- [x] #56165 
- [x] #56148 
- [x] #56174 
- [x] #56159 
- [x] #56089 
- [x] #56195 
- [x] #56215 
- [x] #56251 
- [x] #56092 
- [x] #55870 
- [x] #56227 
- [x] #55741 
- [x] #56149 
- [x] #56214 
- [x] #54471
- [x] https://github.com/JuliaLang/julia/pull/55622
- [x] https://github.com/JuliaLang/julia/pull/55704
- [x] https://github.com/JuliaLang/julia/pull/55764

Need manual backport:
- [x] #55908 
- [ ] #56097 

Contains multiple commits, manual intervention needed:
- [ ] #55877 

Non-merged PRs with backport label:
- [ ] #56156 
- [ ] #55958 
- [ ] #55956 
- [ ] #55910 
- [ ] #55871 
- [ ] #55813 
- [ ] #55534 
- [ ] #55499 
- [ ] #55458 
- [ ] #55457 
- [ ] #55220 
- [ ] #55169 
- [ ] #54457 
- [ ] #53957 
- [ ] #51479 
- [ ] #50813 
- [ ] #50157

### CODE REVIEW

**Comment by IanButterworth** [comment]
I tried to cherry-pick https://github.com/JuliaLang/julia/pull/56214 here but it's a bit tricky because precompilepkgs has changed a fair bit with the workspaces support. (I did add two minor backports that help reduce the merge conflicts though.) I highlight that as I think it's something we'd want to get in here. cc. @vtjnash

**Comment by KristofferC** [comment]
@IanButterworth, I attempted a cherry-pick as well. It seems to work ok.

**Comment by KristofferC** [comment]
@maleadt, seems like the llvmpasses test fails after backporting https://github.com/JuliaLang/julia/pull/56228/commits/9c94a386914d330f04a602a3aa9adf9ee9512979

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2429609566) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/d601533_vs_8f5b7ca/report.md).

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2429609000) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/df61bb1_vs_8f5b7ca/report.html) is available.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2433060661) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/df61bb1_vs_8f5b7ca/report.html) is available.

**Comment by KristofferC** [comment]
```
julia> using JuliaInterpreter, BracedErrors

julia> bracederror(2.34567e70, 3.46e69) == @interpret bracederror(2.34567e70, 3.46e69)
false
```

Maybe some fast math stuff?

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BracedErrors", "JuliaSyntaxHighlighting", "Cosmology", "NeighbourLists", "QSFit", "SwitchOnSafety", "IncompressibleNavierStokes"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2434730208) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8d07746_vs_8f5b7ca/report.html) is available.

**Comment by PallHaraldsson** [comment]
Add my trivial approved speed-optimization #56308 to this? I.e. those 3 commits, I plan to add investigate and add more that might be non-trivial. This bug-fix #56278 too?

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2451907613) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/bf5675b_vs_8f5b7ca/report.html) is available.

**Comment by KristofferC** [comment]
Okay, let's run another PkgEval and then not merge too much in here so we can fix the possible regressions and get this out.

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2468045236) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/5a280aa_vs_8f5b7ca/report.html) is available.

**Comment by KristofferC** [comment]
I think the latest backport should fix Revise

**Comment by IanButterworth** [comment]
Is https://github.com/JuliaLang/julia/issues/56077 fixed on this with the latest backports?

**Comment by KristofferC** [comment]
Doesn't look like it, the PR that fixes it seems quite big to backport...

**Comment by tecosaur** [comment]
Kristoffer in another PR (but intended for here):

> looks like JuliaSyntaxHighligting needs updating to work with this.

JuliaSyntaxHighligting shouldn't be included as a 1.11 stdlib though? Unless you're talking about the general-released package, which indeed needs me to backport the changes to a new release.

**Comment by KristofferC** [comment]
> Unless you're talking about the general-released package, which indeed needs me to backport the changes to a new release.

Yes.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/56228#issuecomment-2470539714) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/157ab5a_vs_8f5b7ca/report.html) is available.

**Pull request merged**
