### PR TITLE
Set VERSION to 1.0.0-rc1

### PR DESCRIPTION
**Pull request by ararslan**
To be merged first:

- [x] #28488: Deprecations
- [x] #28486: Deprecations and fix `@inferred` macro to handle broadcast syntax.
- [x] #28485: GC lowering
- [x] #28482: Underlines in command printing
- [x] #28480: Remove some linear algebra checks
- [x] #28479: Deprecations
- [x] #28453: Stack traces

As usual, add and subtract as necessary.

### CODE REVIEW

**Comment by tknopp** [comment]
I wonder if 0.7 and 1.0 will be released simultaneously? I thought first 0.7 then 1.0.

**Comment by Keno** [comment]
They'll be released fairly close together, but probably not quite simultaneously.

**Comment by tknopp** [comment]
Is there some documented timeline? (I am trying getting Gtk.jl into shape but this is not very simple...)

**Comment by ViralBShah** [comment]
There isn't a documented timeline. In the ideal world, they would both be tagged simultaneously, but they may be a few days apart at best.

**Comment by ViralBShah** [comment]
This isn't the right place to discuss the policy for the release, which I believe has been adequately communicated. Request discussing on discourse or slack.

**Comment by StefanKarpinski** [comment]
> Also the transition REQUIRE -> Manifest.toml should be done prior to 1.0.

This has never been the plan.

**Comment by tknopp** [comment]
I fully trust you. My concern ist that julia adaptors using 1.0 for the first time need to learn what REQUIRE is.  This was the thing that confused me most about Pkg3. Pkg3 seems very well designed but it also is pretty complex. Having to learn about REQUIRE and Manifest just increases that conplexity.

**Review by Keno — APPROVED** [review]

**Pull request merged**
