### PR TITLE
[release-0.6] set buildopts on 32bit similar to the buildbots

### LINKED ISSUE #24959: Precision-related test failures on i686 Linux, release-0.6
Observed on Travis and seems only to happen on i686.
```
linalg/dense: Test Failed
  Expression: norm(reshape(A, length(A)), p) == vecnorm(A, p)
   Evaluated: 8.422609468915075 == 8.422609468915073
Stacktrace:
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:568
 [2] (::##40#46)() at /tmp/julia/share/julia/test/runtests.jl:160
 [3] cd(::##40#46, ::String) at ./file.jl:70
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
linalg/dense: Test Failed
  Expression: norm(reshape(A, length(A)), p) == vecnorm(A, p)
   Evaluated: 44.706942422184675 == 44.70694242218468
Stacktrace:
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:568
 [2] (::##40#46)() at /tmp/julia/share/julia/test/runtests.jl:160
 [3] cd(::##40#46, ::String) at ./file.jl:70
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
```
(and a lot more)

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #24959

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
Looks like 32-bit Linux on Travis is still hitting the pthread issue when linking curl. Should we push a commit to `disclean-curl` then remove that before merging?

**Comment by ararslan** [comment]
Awesome, clearing out the curl cache got the dense linear algebra tests passing again. Once CI finishes we can remove that commit and merge, then I think that unblocks 0.6.2.

**Comment by ararslan** [comment]
Travis was smarter than I thought it would be. Removing the commit I added to clear the curl cache didn't rerun your previous commit, it just showed the result from the last run on that commit. So I've added a new commit that does the same clearing, and I guess after that we can add another that undoes it and squash them on merge.

**Comment by omus** [comment]
@ararslan pro git tip: `git commit --squash`

**Pull request merged**
