### PR TITLE
Add tests for #12089

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
AppVeyor freezes during bootstrap like many other builds today....

**Comment by tkelman** [comment]
> AppVeyor freezes during bootstrap like many other builds today....

Hey, whoa. That's not expected at all. Freezes during bootstrap are rarely intermittent, they almost always mean the windows build is broken, and whatever commit caused it needs to be scrutinized.

**Comment by yuyichao** [comment]
Yeah, I know it shouldn't be there. This commit does not touch any file outside `test/` so it should not be the cause.

**Comment by tkelman** [comment]
Okay, but the longer we tolerate a broken build on any platform, the more likely it is we introduce additional breakage on top of the initial cause, making it increasingly difficult to fix anything.

**Pull request merged**
