### PR TITLE
patches #13682 to fix memory mapping of large files on Windows

### LINKED ISSUE #13560: Mmap.mmap throws InexactError for filesize > 2Gb on Windows
Following code on Windows 7 64bit, Julia 0.4.0 shows the error:
```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
julia> Mmap.mmap(open(tempname(),"w+"), Vector{UInt8}, 1024*1024*3048,0)
ERROR: InexactError()
 in mmap at mmap.jl:126
```
I think this origins in the usage of a wrong type `Cint` for a `ccall` in mmap.il:126
```
handle = create ? ccall(:CreateFileMappingW, stdcall, Ptr{Void}, (Cptrdiff_t, Ptr{Void}, Cint, Cint, Cint, Cwstring),
						file_desc, C_NULL, readonly ? PAGE_READONLY : PAGE_READWRITE, szfile >> 32, szfile & typemax(UInt32), name) :
				  ccall(:OpenFileMappingW, stdcall, Ptr{Void}, (Cint, Cint, Cwstring),
					readonly ? FILE_MAP_READ : FILE_MAP_WRITE, true, name)
```
Changing param types from `Cint` to `Cuint` (DWORD as specified for calls `CreateFileMappingW` and `OpenFileMappingW` in https://msdn.microsoft.com/en-us/library/windows/desktop/aa366763%28v=vs.85%29.aspx) lets mmap handle files with a size > 2Gb:
```
handle = create ? ccall(:CreateFileMappingW, stdcall, Ptr{Void}, (Cptrdiff_t, Ptr{Void}, Cuint, Cuint, Cuint, Cwstring),
						file_desc, C_NULL, readonly ? PAGE_READONLY : PAGE_READWRITE, szfile >> 32, szfile & typemax(UInt32), name) :
				  ccall(:OpenFileMappingW, stdcall, Ptr{Void}, (Cuint, Cuint, Cwstring),
					readonly ? FILE_MAP_READ : FILE_MAP_WRITE, true, name)
```

Or did I miss something?

### PR DESCRIPTION
**Pull request by Cody-G**
Fixes #13560

### CODE REVIEW

**Comment by quinnj** [comment]
I still don't think this is right; the [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366537(v=vs.85).aspx) say that all the args for `CreateFileMapping` are `DWORD`. Do you know which function/argument is specifically causing problems for you?

**Comment by yuyichao** [comment]
I think the argument **is** still `DWORD` but the convertion to a integer before getting it's higher and lower 32bits is the issue.

**Comment by quinnj** [comment]
Ah.....that makes sense.

**Comment by vtjnash** [comment]
lgtm. we've been reluctant to add tests for this since it requires making a 4GB+ file. but I assume you've at least tested this locally to show that it is giving the right results?

**Comment by Cody-G** [comment]
Yes, I've tested it with large imaging datasets, and it looks good.  If the mapping was incorrect it should have been obvious in the images.

**Comment by tkelman** [comment]
We could try adding an automated outside-of-base regression test for this running in a dedicated repository on appveyor?

**Comment by tkelman** [comment]
Travis failure is a cache corruption, will restart
```
In file included from /usr/include/limits.h:27:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed/limits.h:169,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed/limits.h:34,
                 from /home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src/os-linux.c:26:
/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.
43.236308 libtool: compile:  gcc -march=pentium4 -m32 -DHAVE_CONFIG_H -I. -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src -I../include -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include/tdep-x86 -I. -D_GNU_SOURCE -DNDEBUG -U_FORTIFY_SOURCE -fPIC -fexceptions -Wall -Wsign-compare -MT mi/init.lo -MD -MP -MF mi/.deps/init.Tpo -c /home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src/mi/init.c -o mi/init.o
In file included from /home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src/mi/init.c:26:0:
/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind_i.h:49:75: fatal error: sys/types.h: No such file or directory
compilation terminated.
make[5]: *** [os-linux.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [mi/init.lo] Error 1
43.312240 libtool: compile:  gcc -march=pentium4 -m32 -DHAVE_CONFIG_H -I. -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src -I../include -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include -I/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include/tdep-x86 -I. -D_GNU_SOURCE -DNDEBUG -U_FORTIFY_SOURCE -fPIC -fexceptions -Wall -Wsign-compare -MT mi/flush_cache.lo -MD -MP -MF mi/.deps/flush_cache.Tpo -c /home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src/mi/flush_cache.c -o mi/flush_cache.o
In file included from /home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/src/mi/flush_cache.c:26:0:
/home/travis/build/JuliaLang/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind_i.h:49:75: fatal error: sys/types.h: No such file or directory
compilation terminated.
``

**Pull request merged**
