### PR TITLE
release-1.6: Set VERSION to 1.6.3

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
🎉

**Comment by ararslan** [comment]
Duplicate of https://github.com/JuliaLang/julia/pull/42191 :smile:

**Comment by DilumAluthge** [comment]
Duplicate of #42191

**Comment by KristofferC** [comment]
5o0cjg

**Comment by ararslan** [comment]
image

**Comment by DilumAluthge** [comment]
"I don't like patch releases. They're coarse and rough and irritating and they get everywhere."

**Pull request closed without merging**
