### PR TITLE
complete module names without .jl suffix

### LINKED ISSUE #10891: REPL completion for module names
When looking for a module `A` that has not been loaded before, julia search for file `A.jl`, `A/src/A.jl` and `A.jl/src/A.jl`.

When auto-completing for module names in `using` or `import` for a module name, REPL compete for the module name `A` for the first two cases (correct) but complete for `A.jl` for the last case `A.jl/src/A.jl` (wrong).

It's a little bit annoy when testing packages by setting `JULIA_LOAD_PATH` to the parent directory of the package repos.

### PR DESCRIPTION
**Pull request by yuyichao**
Fixes #10891

### CODE REVIEW

**Comment by yuyichao** [comment]
Also only complete when the `.jl` file exist.

**Comment by yuyichao** [comment]
... No idea why AppVeyor failed in a unrelated test....

**Comment by tkelman** [comment]
@blakejohnson, @dhoegh, etc, could you take a look?

**Comment by dhoegh** [comment]
The change looks good to me.

**Pull request merged**
