### PR TITLE
RFC: remove 1- and n-arg definitions of &, |, $

### PR DESCRIPTION
**Pull request by JeffBezanson**
See #11521. Without #7368, these definitions aren't necessary. Furthermore, I'd like to move away from using varargs for things like this since they can be a performance trap. You don't want to do reductions using `(&)(A...)`.

### CODE REVIEW

**Comment by mbauman** [comment]
I was using n-ary `&` as a shortcut for code generation in the abstract array indexing fallbacks.  It's a simple change, but this should fail tests due to [abstractarray.jl line 460](https://github.com/JuliaLang/julia/blob/master/base/abstractarray.jl#L460) and [552](https://github.com/JuliaLang/julia/blob/fa473e5930c9f59c1122a6fe6a0f4f033a115a9c/base/abstractarray.jl#L552).

**Comment by JeffBezanson** [comment]
Ah, interesting. Well you certainly wouldn't want a tuple allocated there :)

**Comment by JeffBezanson** [comment]
...aaand it looks like tests are passing. I guess this PR is already unintentionally useful.

**Comment by mbauman** [comment]
Yup, I definitely need to add tests. :)

**Comment by JeffBezanson** [comment]
Bump. @StefanKarpinski what do you think?

**Comment by StefanKarpinski** [comment]
I don't really have a terribly strong opinion, so go for it I suppose.

**Comment by JeffBezanson** [comment]
@mbauman do you have a test for this case?

**Comment by mbauman** [comment]
Yup, this should be covered now.

**Comment by JeffBezanson** [comment]
Will re-do against master.

**Pull request closed without merging**
