### PR TITLE
attempt to refine return type when it could be improved via PartialTuple

### LINKED ISSUE #30380: more tuple/apply inference fun
```julia
julia> g(args...) = h(args...)
g (generic function with 1 method)

julia> h(f, args...) = f(args...)
h (generic function with 1 method)

julia> f(T, y) = g(getfield, g(tuple, T, y), 1)
f (generic function with 1 method)

julia> @code_typed f(AbstractFloat, 1)
CodeInfo(
1 ─ %1 = Main.tuple::Const(tuple, false)
│   %2 = (%1)(T, y)::Tuple{DataType,Int64}
│   %3 = Main.getfield::Const(getfield, false)
│   %4 = (%3)(%2, 1)::DataType
└──      return %4
) => DataType

julia> k(T, y) = getfield(tuple(T, y), 1)
k (generic function with 1 method)

julia> @code_typed k(AbstractFloat, 1)
CodeInfo(
1 ─     return AbstractFloat
) => Type{AbstractFloat}

julia> versioninfo()
Julia Version 1.1.0-DEV.843
Commit a0bc8fdb75 (2018-12-08 18:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.5.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

MWE from Cassette; I'd like the output of `f(...)` to be inferred as `Type{AbstractFloat}` (the same as `k(...)`)

### PR DESCRIPTION
**Pull request by jrevels**
thanks to @vtjnash 
fixes #30380

### CODE REVIEW

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30385#issuecomment-447414261) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fbfb914caf6f9b962a37f55fd041d0a7ed12ab9d/9b3f806_vs_c379900/report.md). cc @ararslan

**Comment by jrevels** [comment]
Looks like some decent improvements across the board, a few regressions too. Here are the potential regressions that seem worth looking into:

| ID | time ratio | memory ratio |
|----|------------|--------------|
| `["array", "comprehension", "(\"collect\", \"Array{Float64,1}\")"]` | 1.44 (5%) :x: | 1.00 (1%)  |
| `["broadcast", "mix_scalar_tuple", "(10, \"scal_tup_x3\")"]` | 1.14 (5%) :x: | 1.00 (1%)  |
| `["io", "array_limit", "(\"display\", \"Array{Float64,2}(10000, 10000)\")"]` | 1.07 (5%) :x: | 1.03 (1%) :x: |
| `["sparse", "index", "(\"spmat\", \"row\", \"array\", 1000)"]` | 1.56 (30%) :x: | 1.00 (1%)  |
| `["sparse", "index", "(\"spmat\", \"row\", \"logical\", 1000)"]` | 2.05 (30%) :x: | 1.00 (1%)  |
| `["union", "array", "(\"map\", abs, Float32, true)"]` | 1.24 (5%) :x: | 1.00 (1%)  |
| `["union", "array", "(\"skipmissing\", sum, Union{Missing, Bool}, true)"]` | 1.25 (5%) :x: | 1.00 (1%)  |

I'll do some digging on these tomorrow or so when I get a chance. 

In the meantime would be great to get some review, especially since there are already merge conflicts cropping up. Would like to get this in ASAP pending investigation of the above regressions.

**Review by vtjnash — APPROVED** [review]

**Comment by jrevels** [comment]
Huh, the sparse index benchmarks are pretty noisy on my local machine. I have to kick `samples` up to 600,000 (from the default 10,000) to start to see some convergence in the minimum. At that point, master and this PR seem mostly the same (this PR is actually slightly faster, but I assume that could be noise as well). 

Same for the array comprehension benchmark; it's unfortunately a bit longer running, so I don't have time to get convergence in the minimum, but the medians seemed to converge around the 500 sample mark on my machine, with the result once again pointing to essentially no change with this PR.

We should consider reconfiguring the time/sample budget on Nanosoldier for those benchmarks...

The `["io", "array_limit", "(\"display\", \"Array{Float64,2}(10000, 10000)\")"]` benchmark seems like the only actual regression here, and IMO it's minor compared to the improvements this PR provides. My guess is that it's a result of overspecializing on something dumb, but I'm not sure yet - `@code_typed` is exactly the same between this PR and master a few invocations down the call chain and I haven't gotten all the way to the bottom yet (Cthulhu makes this so much easier). I'll keep poking to see if I can find a `code_typed` difference somewhere that yields anything interesting, but this doesn't seem like a merge blocker.

**Pull request merged**
