### PR TITLE
Don't use floating-point environment methods from openlibm.

### LINKED ISSUE #38427: openlibm fenv changes broke CUDA
On latest nightly as well as master + `USE_BINARYBUILDER_OPENLIBM=false` `DEPS_GIT=openlibm`:

```
Thread 1 "julia-debug" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b855d0 in fesetenv () from /home/tim/Julia/julia/build/release/usr/bin/../lib/libopenlibm.so
(gdb) bt
#0  0x00007ffff7b855d0 in fesetenv () from /home/tim/Julia/julia/build/release/usr/bin/../lib/libopenlibm.so
#1  0x00007fff824578ae in ?? () from /usr/lib/libnvidia-ptxjitcompiler.so.1
#2  0x00007fff8244b8fc in __cuda_CallJitEntryPoint () from /usr/lib/libnvidia-ptxjitcompiler.so.1
#3  0x00007fff9196bc30 in ?? () from /usr/lib/libcuda.so.1
#4  0x00007fff91995e23 in ?? () from /usr/lib/libcuda.so.1
#5  0x00007fff91793fd0 in ?? () from /usr/lib/libcuda.so.1
#6  0x00007fff91731853 in ?? () from /usr/lib/libcuda.so.1
#7  0x00007fff917e992e in cuModuleLoadDataEx () from /usr/lib/libcuda.so.1
```

Reverting https://github.com/JuliaMath/openlibm/pull/213 by using `OPENLIBM_SHA1=878948d3dd6bc940f65582b8cae286a06d89ad81` (and changing `rounding.jl` to look for `fesetround` and `fegetround` in `libjulia` again or bootstrap fails) fixes the issue. Reproduces with CUDA.jl's `examples/vadd.jl` (requiring https://github.com/JuliaGPU/GPUCompiler.jl/pull/69/files for 1.6 compatibility).

Feel free to transfer this issue to https://github.com/JuliaMath/openlibm; I opened it here because it ultimately manifests as CUDA.jl not working on latest nightly.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaLang/julia/issues/38427, see https://github.com/JuliaMath/openlibm/pull/219

### CODE REVIEW

**Comment by maleadt** [comment]
Kicked-off a build with `USE_BINARYBUILDER_OPENLIBM=false DEPS_GIT=openlibm` here: https://build.julialang.org/#/builders/47/builds/1

**Comment by maleadt** [comment]
Fails to build on Windows because we don't seem to have floating-point functions there. Presumable this used to work, https://github.com/JuliaLang/julia/pull/36588/files#diff-b93461e172b1a09513b591004c100b10a2a3fcf407d51fc19e6be1cb73c246d4, because we were linking openlibm before.

@vtjnash You mentioned, https://github.com/JuliaLang/julia/issues/38427#issuecomment-726928437, we should have functions like `fenv` available on Windows, however `ccall(:fegetenv, Cint, (Ptr{Cvoid},), C_NULL)` (and the build here) fails. Do you have any insights?

**Comment by vtjnash** [comment]
It looks like a .a library, so you need to force link it.

**Comment by maleadt** [comment]
I *guess* these functions are only in the ucrt, and not the msvcrt.dll we're using:

```
julia> crt = Libdl.dlopen("msvcrt.dll")
Ptr{Nothing} @0x00007ffbb0920000

julia> Libdl.dlsym(crt, "ferror")
Ptr{Nothing} @0x00007ffbb096cad0

julia> Libdl.dlsym(crt, "fegetenv")
ERROR: could not load symbol "fegetenv":
The specified procedure could not be found.
```

```
julia> crt = Libdl.dlopen("ucrtbase.dll")
Ptr{Nothing} @0x00007ffbaee70000

julia> Libdl.dlsym(crt, "fegetenv")
Ptr{Nothing} @0x00007ffbaee768d0
```

Switching to the ucrt seems quite an large change. Alternatively, we could ship `libmingwex` and use that?

**Comment by maleadt** [comment]
> It looks like a .a library, so you need to force link it.

No, that results in lots of multiple definition errors. Looks like `mingwex` gets automatically linked already, presumably for C99 support when using msvcrt. So I'm trying to get it to export the `fegetround`/`fesetround` defs from that static library, is there a clean way to do that other than introducing a 'fake' use somewhere in julia or libjulia?

Also, any thoughts about this:
```
Tim@DESKTOP-1NUTSID ~/julia
$ nm -g usr/bin/libjulia.dll | grep feget
0000000065471370 T fegetround

Tim@DESKTOP-1NUTSID ~/julia
$ ./julia.bat -q
julia> using Libdl

julia> lib = Libdl.dlopen("usr/bin/libjulia.dll")
Ptr{Nothing} @0x00000000028f0000

julia> Libdl.dlsym(lib, "fegetround")
ERROR: could not load symbol "fegetround":
The specified procedure could not be found.
```

**Comment by vtjnash** [comment]
`--require-defined=fesetround`

Though to re-export it, I think you may need to mark it during the build, as exported symbols have a different name mangling

**Comment by maleadt** [comment]
Thanks, I'll try that. Alternatively, we do an `if Sys.iswindows()` for these calls and have them use openlibm there, but that would require some reordering of the bootstrap includes.

**Comment by maleadt** [comment]
Couldn't get it to work; `nm` and `objdump` were lying to/confusing me as the symbols weren't visible in Dependencies.
Anyway, decided to take the simpler option of introducing `jl_fegetround`/`jl_fesetround`.
Kicked off another build to use openlibm from master here: https://build.julialang.org/#/builders/47/builds/2

**Comment by vtjnash** [comment]
Could also just add another special case to the jitlayers file. I know we already have a few there.

**Comment by maleadt** [comment]
> Could also just add another special case to the jitlayers file.

Ah, yes. This seems like a simpler solution though, and does the job as well.

CI failures unrelated (happen on master too), and the manual build using openlibm#master, https://build.julialang.org/#/buildersj/47/builds/2, successfully builds and tests on all platforms too. Let's generate new binaries now.

**Comment by nico202** [comment]
I'm trying to build julia#110f1256ac with openlibm 0.7.3 and it's failing with 
```julia
LoadError("sysimg.jl", 3, LoadErjuliaor("Base.jl", 269, LoadError("floatfuncs.jl", 345, ErrorException("could not load symbol \"fesetround\":\n/tmp/guix-build-julia-1.5.3-git.drv-0/source/usr/bin/../lib/libopenlibm.so: undefined symbol: fesetround"))))
```
Is this related?
Thanks

**Comment by maleadt** [comment]
Yes, how come you are using openlibm 0.7.3 already? It needs this PR.

@staticfloat Looks like the macos64 build of openlibm didn't go through; did you do so manually for 0.7.1?

**Comment by nico202** [comment]
I'm preparing the next package for guix, just saw the new tagged openlibm release and updated it (we use USE_SYSTEM_OPENLIBM=1).
I'll try with 0.7.2 in the meanwhile, thanks

**Comment by maleadt** [comment]
Should be good to go now.

**Pull request merged**
