### PR TITLE
Add `Libdl.dlext` to documentation

### PR DESCRIPTION
**Pull request by jayschwa**
Prompted by https://groups.google.com/d/topic/julia-dev/Xk3occIColg/discussion

### CODE REVIEW

**Comment by stevengj** [comment]
I think you actually have to add this as a docstring to `libdl.jl` ... the `.rst` file is generated from that (though a `.. data:: dlext` entry in the `.rst` file is required as a placeholder so that the doc-generation system knows where to put the docstring.

**Comment by jayschwa** [comment]
Hmm, okay. I didn't see other strings from this `.rst` file in the corresponding `.jl` file. If true, https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation should probably make mention of it.

**Comment by stevengj** [comment]
Most of the docs are still in `base/docs/helpdb.jl`, but that is slowly changing.  Probably the CONTRIBUTING file needs to be updated on the new doc procedure, which changed very recently.

cc: @one-more-minute

**Comment by jakebolewski** [comment]
@jayschwa see CONTRIBUTING.md for  how to do doc additions now.

**Pull request closed without merging**
