### PR TITLE
Revert "Bump to openblas 0.3.1 (#27889)"

### PR DESCRIPTION
**Pull request by andreasnoack**
OpenBLAS 0.3.1  introduced a quite serious bug that caused https://github.com/JuliaLang/LinearAlgebra.jl/issues/539. I think we should revert for now. We can try upgrading again once 0.3.2 is out.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is it easy to get a test in for this?

**Comment by andreasnoack** [comment]
The test from #27960 works reliably locally but I don't know if it triggers the bug on Travis. It will take some hours to figure out.

**Comment by tkelman** [comment]
This should also have reverted c9e76a9380c5b26f4963039db895df9faa107910. Openblas downloads are not being verified on master.

**Comment by ViralBShah** [comment]
Good catch @tkelman. Pushed.

**Pull request merged**
