### PR TITLE
make explicit that xvf is flag on tar

### PR DESCRIPTION
**Pull request by LOAS2**

### CODE REVIEW

**Comment by ViralBShah** [comment]
I thought tar with hyphens requires individual arguments. What is the best form that works on various Linux, BSD systems and elsewhere?

**Comment by ViralBShah** [comment]
This is how GNU tar's hyphens work
https://www.gnu.org/software/tar/manual/html_section/tar_21.html

And FreeBSD:
https://www.freebsd.org/cgi/man.cgi?query=tar&apropos=0&sektion=1&manpath=OpenBSD+5.0&arch=default&format=html

The form without the hyphen works on very old tar versions too, but I am not sure this is worth bothering with.

**Comment by LOAS2** [comment]
The tar implementation I'm using doesn't accept flags without hyphens.
Now the question is if it's better to use individual arguments or put them together on single hyphen.
I have no opinion on that.

**Comment by StefanKarpinski** [comment]
What `tar` implementation are you using? The GNU and FreeBSD versions both seem to accept flags without hyphens.

**Comment by StefanKarpinski** [comment]
I think you can bundle the flags like this as long as the `f` flag comes last so that its argument (the tar file name) is the next argument.

**Comment by LOAS2** [comment]
So you think the current pull request is fine?
Final decision for julia to use hyphen for flags and keep the `f` as the last flag?
I agree with this.

**Comment by StefanKarpinski** [comment]
I would like two things first:

1. Verification that this works for both GNU `tar` and FreeBSD `tar`;
2. Info about what version of `tar` you're using that the non-hyphen form doesn't work.

**Comment by LOAS2** [comment]
1. How can we do this? Are there people who use GNU tar and people who use FreeBSD tar that can test for us?

2. I'm using the tar from sbase. If you want to look at the source code, you can find it on the site http://git.suckless.org/sbase/tree/tar.c

**Comment by ViralBShah** [comment]
Is it enough to check on linux and os x?

**Comment by tkelman** [comment]
freebsd can differ from osx. also worth checking on a busybox based system.

**Comment by vtjnash** [comment]
from the man page, looks like busybox tar would also prefer to have the `-`

**Pull request merged**
