### PR TITLE
remove DelimitedFiles from being an stdlib

### LINKED ISSUE #44663: Move DelimitedFiles to a separate external package
Can we move DelimitedFiles to an external package and also perhaps remove it from the system image?

Now that we are considering moving sparse out of the system image, I thought I would ask that about DelimitedFiles as well.  https://github.com/JuliaLang/julia/pull/44247#issuecomment-1071226278

Is Dates.jl worth considering moving out? Any others?

### PR DESCRIPTION
**Pull request by KristofferC**
Requires https://github.com/JuliaLang/Pkg.jl/pull/3097 and https://github.com/JuliaRegistries/General/pull/61457

Fixes #44663

### CODE REVIEW

**Comment by ViralBShah** [comment]
@KristofferC I think you mentioned somewhere that there were some issues with Compat. Perhaps good to capture those here.

**Comment by KristofferC** [comment]
Yes,

So as it is right now, there are a bunch of packages that depend on standard libraries. The compatibility requirements for stdlib dependencies are implicit in the julia compatibility. Now, a stdlib gets moved out to become a standard package (let's call this an ex-stdlib). It will be versioned like a normal package and people with put compat on it like a normal package. There are a few questions that arises now:

- When a package cannot be installed because there is a conflict with the compatibility in an ex-stdlib, Pkg will instead pick an old version of the package that has the ex-stdlib dependency but without any compatibility constrained (which exist from the time the ex-stdlib was an stdlib). Installing very old pacakges is unlikely what you want as a user. 
- When a package adds compat to the ex-stdlib what will happen to older Julias where the package is still and stdlib? Will they be able to install the package?
- Is it important what version the ex-stdlib has when it is moved out. Should it start at 1.9 (since Julia is at 1.9).

I think I have to play around with this a bit locally and create "fake packages" that set up these scenarios to conclusively say what is best to do here.

**Comment by carstenbauer** [comment]
If I may ask, what's the reasoning / motivation for dropping DelimitedFiles as a stdlib? I might have missed it but haven't seen a discussion about this anywhere.

**Comment by ViralBShah** [comment]
Not just DelimitedFiles, but also Statistics and the sparse ecosystem. There are PRs open on these and discussions that are distributed in various places. The main argument for me is to allow broader participation in these packages, letting them evolve and move a bit faster (not be tied to Julia release cadence), and in some cases be replaced by better alternatives by being less special. The spun off packages will be 1.x.y version numbers so that there is no breakage. 

Also, with Project and Manifest files, it is fairly easy to pull these in automatically without breaking existing code (which is being tested).

**Comment by brenhinkeller** [comment]
2 is very valid, and 4 would be awesome!

3 is interesting, in that on one hand that's almost certainly true, but on the other hand it can be nice to have Base and Stdlibs as an "api" of sorts that other packages can extend (i.e., you should import and extend `Statistics.mean` for your custom fancy type, don't just roll your own conflicting `mean`) and with more things spun out of stdlibs it'll be less

I still have a knee-jerk reaction ("surely this will end up breaking someone's workflow anyways" "ok, so they'll still get checked in pkgeval, but what if something breaks them anyways, there won't be as much pressure to fix downstream", etc.), but that's probably paranoid. All in all it's probably (?) worth it as long as it really *really* isn't breaking and everyone's `Project.toml`s will get PRd with appropriate compat bounds and such?

**Comment by juliohm** [comment]
> but on the other hand it can be nice to have Base and Stdlibs as an "api" of sorts that other packages can extend (i.e., you should import and extend `Statistics.mean` for your custom fancy type, don't just roll your own conflicting `mean`)

I don't think that these need to live in Base or as stdlib. They are much better suited for a StatsBase.jl or StatsCore.jl or StatsAPI.jl package that is developed freely **by** the statistics community in Julia without language release cycles and related concerns.

**Comment by KristofferC** [comment]
We want to get rid of SuiteSparse test dependency on DelimitedFiles.

Regarding the compat problem, I think things should be ok if we retroactively add compat to an ex-stdlib, duplicating that of the Julia version, and setting the version of the ex-stdlib to that of the Julia version when it moves out. So DelimitedFiles would get version 1.9.0 in this case.

Here is a commit that adds the compat to DelimitedFiles as an example: https://github.com/JuliaRegistries/General/commit/969344d7dac8ff80f0afd0a3e6815ce44651a4dc.

Made with https://github.com/KristofferC/StdlibRegistryCompatUpdater

**Comment by ViralBShah** [comment]
SuiteSparse test dependency on DelimitedFiles is fixed in https://github.com/JuliaLang/julia/pull/45972

**Comment by ViralBShah** [comment]
Wondering if we can get this in before the 1.9 feature freeze.

**Comment by maleadt** [comment]
Working on Nanosoldier/PkgEval improvements to be able to test this:

@nanosoldier `runtests(["AstroLib"], configuration=(registry="kc/consistent_spacing", ), vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45540#issuecomment-1210507073) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/68356a8_vs_4025b99/report.html).

**Comment by maleadt** [comment]
Looks good. One more test:

@nanosoldier `runtests(["AstroLib"], configuration=(registry="kc/consistent_spacing", ), vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45540#issuecomment-1210540170) has completed - no new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/68356a8_vs_4025b99/report.html).

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, configuration=(registry="kc/consistent_spacing", ), vs = ":master")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/45540#issuecomment-1210558923) failed. cc @maleadt

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/45540#issuecomment-1210587377) failed. cc @maleadt

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45540#issuecomment-1210612971) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/68356a8_vs_4025b99/report.html).

**Comment by maleadt** [comment]
No new errors about uninstallable packages, so that looks good?

**Comment by KristofferC** [comment]
Yep!

**Comment by KristofferC** [comment]
I want to run the Pkg tests using the https://github.com/JuliaRegistries/General/pull/66039 branch of the registry. If that passes, I think we are good to go.

**Comment by KristofferC** [comment]
This is done now. There is a BB-specific feature in Pkg however which currently prevents excising any stdlib so I guess this will have to wait for that to be fixed before getting merged.

**Pull request merged**
