### PR TITLE
fix #17662, failure in nullable test due to type cache corruption

### LINKED ISSUE #17662: Intermittent nullable test failure
```
From worker 10:	     * nullable             Test Failed
	From worker 10:	  Expression: isa(convert(Nullable{Number},one(T)),Nullable{Number})
<or sometimes isa(convert(Nullable{Any},one(T)),Nullable{Any})>
<snip>
Exception running test nullable :
On worker 10:
LoadError: There was an error during testing
 in record at ./test.jl:397
 in do_test at ./test.jl:281
 in macro expansion; at /tmp/julia/share/julia/test/nullable.jl:285 [inlined]
 in anonymous at ./<missing>:?
 in include_string at ./loading.jl:380
 in include_from_node1 at ./loading.jl:429
 in macro expansion at ./util.jl:180 [inlined]
 in runtests at /tmp/julia/share/julia/test/testdefs.jl:7
 in #16 at /tmp/julia/share/julia/test/runtests.jl:44
```

e.g. https://travis-ci.org/JuliaLang/julia/jobs/147705996
https://travis-ci.org/JuliaLang/julia/jobs/147770860
https://travis-ci.org/JuliaLang/julia/jobs/147796256
https://travis-ci.org/JuliaLang/julia/jobs/147915601
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4714/job/hd5ctt5loet610ai

Reproducible (eventually, takes maybe a dozen or so times to occur) via
```sh
for i in `seq 40`; do
  JULIA_CPU_CORES=1 ./julia test/runtests.jl read pollfd grisu nullable || break
done
```

cc @yuyichao who I think has caught this in rr

### PR DESCRIPTION
**Pull request by JeffBezanson**
I'm hoping this will fix it, but I haven't been able to reproduce the failure locally. Could somebody who's had more luck with that try this?

### CODE REVIEW

**Comment by yuyichao** [comment]
Given the `object_id` of `Nullable{Array}` is stable now, I think this will fix the issue I saw. However, IIUC, wouldn't it still have issue for types with partially specified parameters?

```jl
julia> object_id(Nullable{Array{Int}})
0x57f39af1180c8040
# <restart session>
julia> object_id(Nullable{Array{Int}})
0x7d0c97f0313ba7e3
```

**Comment by JeffBezanson** [comment]
I believe types like that will not appear in the type cache.

**Comment by yuyichao** [comment]
You are right, it's in the `linearcache`. Actually, why do we resort the `linearcache`? https://github.com/JuliaLang/julia/blob/b7d37c49b49f5af32ab13d6597dd58ed6a6522d6/src/dump.c#L2036

**Comment by JeffBezanson** [comment]
Yes, looks like that should not be necessary.

**Pull request merged**
