### PR TITLE
Don't try `cholesky` for `Hermitian` in `factorize`

### LINKED ISSUE #1076: `factorize(<:AbstractMatrix)` prefers `Cholesky` but `factorize(<:Hermitian)` prefers `BunchKaufman`
Julia v1.10.3

```julia-repl
julia> x = rand(3,3);

julia> factorize(x'*x) |> typeof
Cholesky{Float64, Matrix{Float64}}

julia> factorize(Hermitian(x'*x)) |> typeof
BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
```

The first thing `factorize(x'*x)` does is determine that `x'*x` is structurally hermitian. Once it does, it attempts `cholesky`. If that fails, it calls `factorize(Hermitian(x'*x))`.

But when `factorize(Hermitian(x'*x))` is called (either directly or after determining that `x'*x` is structurally hermitian), `cholesky` is never attempted. Instead, it attempts `Diagonal`, then `bunchkaufman` or `lu` depending on the `eltype`.

This is at odds with `@doc factorize`, which says `cholesky` is favored for positive definite matrices (which are necessarily `ishermitian`, if not `Hermitian`).

Ignoring the documentation discrepancy, it seems that there shouldn't be this distinction. Either `cholesky` should be preferred for all `ishermitian` matrices or we should never try at all. The fact that the `factorize(<:Hermitian)` method does *not* attempt `cholesky` makes me think someone thought about this and preferred "never cholesky".

However, `bunchkaufman` is 1.5-2x slower than `cholesky` (default OpenBLAS, sizes $3 \times 3$ to $500 \times 500$) and appears to even be somewhat slower than `lu` (1.0-1.5x). It seems that `bunchkaufman` is either overrated or has some low-hanging performance improvements available.

`cholesky` has the potential to be faster, but work is wasted if it fails. `lu` is still faster than `bunchkaufman` (but algorithmically this seems backwards, so *could* reverse in the future), but forgets the hermitian structure. I'm not sure what should be preferred, but I think a consistent preference would be better than the current situation. I guess my dream world would have `bunchkaufman` nearly as fast as `cholesky` and we would just use that (since `cholesky` can still fail for many nonsingular matrices).

### LINKED ISSUE #54717: `factorize(<:AbstractMatrix)` prefers `Cholesky` but `factorize(<:Hermitian)` prefers `BunchKaufman`
Julia v1.10.3

```julia-repl
julia> x = rand(3,3);

julia> factorize(x'*x) |> typeof
Cholesky{Float64, Matrix{Float64}}

julia> factorize(Hermitian(x'*x)) |> typeof
BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
```

The first thing `factorize(x'*x)` does is determine that `x'*x` is structurally hermitian. Once it does, it attempts `cholesky`. If that fails, it calls `factorize(Hermitian(x'*x))`.

But when `factorize(Hermitian(x'*x))` is called (either directly or after determining that `x'*x` is structurally hermitian), `cholesky` is never attempted. Instead, it attempts `Diagonal`, then `bunchkaufman` or `lu` depending on the `eltype`.

This is at odds with `@doc factorize`, which says `cholesky` is favored for positive definite matrices (which are necessarily `ishermitian`, if not `Hermitian`).

Ignoring the documentation discrepancy, it seems that there shouldn't be this distinction. Either `cholesky` should be preferred for all `ishermitian` matrices or we should never try at all. The fact that the `factorize(<:Hermitian)` method does *not* attempt `cholesky` makes me think someone thought about this and preferred "never cholesky".

However, `bunchkaufman` is 1.5-2x slower than `cholesky` (default OpenBLAS, sizes $3 \times 3$ to $500 \times 500$) and appears to even be somewhat slower than `lu` (1.0-1.5x). It seems that `bunchkaufman` is either overrated or has some low-hanging performance improvements available.

`cholesky` has the potential to be faster, but work is wasted if it fails. `lu` is still faster than `bunchkaufman` (but algorithmically this seems backwards, so *could* reverse in the future), but forgets the hermitian structure. I'm not sure what should be preferred, but I think a consistent preference would be better than the current situation. I guess my dream world would have `bunchkaufman` nearly as fast as `cholesky` and we would just use that (since `cholesky` can still fail for many nonsingular matrices).

### PR DESCRIPTION
**Pull request by dkarrasch**
Up for debate/pkgeval testing.

Closes JuliaLang/LinearAlgebra.jl#1076.

### CODE REVIEW

**Comment by dkarrasch** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54775#issuecomment-2163505027) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/77a656f_vs_3f8e1bd/report.html) is available.

**Comment by dkarrasch** [comment]
@nanosoldier `runtests(["HTTP", "MCMCDiagnosticTools", "MLJTestIntegration", "Plots", "TMLE", "JointSurvivalModels", "JumpProblemLibrary", "CryoGrid", "SDEProblemLibrary", "PGFPlots", "Catalyst", "HighVoronoi", "Test", "QuantumAnnealingAnalytics", "GasChromatographySystems"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54775#issuecomment-2165004382) has completed - no new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/77a656f_vs_3f8e1bd/report.html) is available.

**Review by fredrikekre — APPROVED** [review]

**Comment by dkarrasch** [comment]
It's interesting that seemingly no package relied on the previous behavior. This seems to reflect the fact that spd matrices don't pop up in a generic context, and when they occur users call `cholesky` directly.

Given the above observation, do we need to announce something here? Or is this an "implementation detail"?

**Comment by dkarrasch** [comment]
Also, I tried hard spotting new typos, and failed, but I also don't understand why the typo check fails. Is it supposed to spit out a concrete typo, or a code line, like in the whitespace check? Not sure who to ping, but I believe @LilithHafner was involved in setting up the typo check.

**Comment by fredrikekre** [comment]
I think in most cases you know you have an SPD matrix and at a minimum do `factorize(Hermitian(A))` if not `cholesky(Hermitian(A))`. I also think the `factorize` function is not that common to use to begin with.

**Pull request merged**
