### PR TITLE
Fallback for copying views into sparse matrices

### PR DESCRIPTION
**Pull request by mkborregaard**
This is a more specialized version of https://github.com/JuliaLang/julia/pull/30889, requested for backporting.

### CODE REVIEW

**Comment by mkborregaard** [comment]
Once again a bit in doubt about where to best put this code.

**Comment by ViralBShah** [comment]
All tests failing seem to suggest something is wrong (I haven't looked inside yet).

**Comment by mkborregaard** [comment]
Yeah, ` UndefVarError(:SparseArray)`. I might have put this the wrong place.

**Comment by mkborregaard** [comment]
I just copied that code from the other PR, sorry - I could replace with
```julia
Base.copy(a::SubArray{<:Any,<:Any,<:Union{SparseVector, SparseMatrixCSC}}) = a.parent[a.indices...]
```
?

**Comment by mbauman** [comment]
Yeah, sorry, I should have made it clear that was psuedocode!  Using a `Union` like that is probably best. As far as where it should go... maybe [here](https://github.com/JuliaLang/julia/blob/c0e9182fa94e2b96106e8e4c14cb36dc9d35cb40/stdlib/SparseArrays/src/sparsevector.jl#L702) would make sense?  It's where we are defining indexing for combinations of sparse vector/matrix, which seems relevant.

**Comment by mkborregaard** [comment]
OK, I've moved it there and replaced `SparseVecOrMat` with the explicit `Union`

**Review by mbauman — APPROVED** [review]

**Comment by mkborregaard** [comment]
Failure on the Travis Mac build looks unrelated/spurious, it's a GitError "can't connnect to github"

**Pull request merged**
