### PR TITLE
Throw OverflowError when the field offset / size overflows.

### PR DESCRIPTION
**Pull request by yuyichao**
Improve #11320.

This doesn't completely fix it but should be the right thing to do anyway.

@ScottPJones

### CODE REVIEW

**Comment by yuyichao** [comment]
Note that the current overflow checking relies on `size_t` never overflow, which is true now since each increment is small enough. We do need special care if we increase the size of the `size` and `offset` field, especially on 32-bit.

**Comment by yuyichao** [comment]
Test done:
```bash
yuyichao% ./julia -f -e 'Enumerate((Int, 1:10000...))'
ERROR: OverflowError()
 in process_options at ./client.jl:288
 in _start at ./client.jl:409
```

**Comment by yuyichao** [comment]
I agree the error message is not very informative but I guess we'd better live with it before error handling/reporting is not a big issue anymore...

**Comment by ScottPJones** [comment]
Thanks, @yuyichao... this would be nasty for a lot of the stuff I'm doing!

**Comment by yuyichao** [comment]
I guess tuple is not meant to be used as a long immutable array. I can see why it is useful though...
Maybe #11242 addresses some of this?

**Comment by timholy** [comment]
#11242 doesn't address this issue.

**Comment by vtjnash** [comment]
lgtm

**Pull request merged**
