### PR TITLE
Fix compilation on linux with system libunwind

### PR DESCRIPTION
**Pull request by yuyichao**
Also remove old libunwind patches and checksums that are not needed anymore.

This still makes it possible to enable our custom memory manager on linux if the distro provides a more recent git snapshot by defining a macro in the libunwind header.

The libunwind tarball is still hosted on my github account. I'm not sure where is a better place to put it. I'll also try to ping upstream and see if there's any plan for a new release.

### CODE REVIEW

**Comment by ViralBShah** [comment]
We can host it on the julialang s3 bucket on AWS in the meanwhile.

**Comment by yuyichao** [comment]
That's probably better than my github repo. Would you mind uploading it (I don't think I can)? I can update this PR once it's up.

**Comment by tkelman** [comment]
If we're going to host our own tarball, could you include this patch for building against musl? https://github.com/tkelman/libunwind/commit/3252a6fb0a0742c1dc9bd98dd6e0d276dd8a9b9a

**Comment by ViralBShah** [comment]
@tkelman Could you set this up? I think you are one of the few who has access and knows what needs to be done. Assuming - you think this is the right thing to do. If we should be doing something else, please suggest.

**Comment by ViralBShah** [comment]
Cc @vtjnash

**Comment by tkelman** [comment]
Which bucket/location would we put this under? @yuyichao was this generated by `make dist` ?

**Comment by yuyichao** [comment]
No, it's just wrapping everything after running autoreconf.

**Comment by tkelman** [comment]
That can leave a bunch of autoreconf temporary clutter that doesn't belong in a source tarball.

**Comment by yuyichao** [comment]
running `autoreconf -fi` didn't generate any file that was not in the tarball last time and there doesn't seem to be any autotool related files in my tarball that was not in the currently released one. There is indeed a `cscope.out` that was accidentally picked up so I could try to remake the tarball.

**Comment by tkelman** [comment]
`autom4te.cache`, `aux`, and `scripts` doesn't belong there either, but it looks like upstream messed that up too...

**Comment by yuyichao** [comment]
> but it looks like upstream messed that up too...

Right, now I made a tarball with `make dist VERSION=1.1-julia` and it doesn't have those files so it seems that upstream made the tarball the same way I did ;-p.

I uploaded the new tarball (also changed to gz compressing) to the same place.

**Comment by yuyichao** [comment]
https://github.com/yuyichao/libunwind/releases/tag/libunwind-1.1-julia

**Comment by yuyichao** [comment]
Merge now in order to fix https://groups.google.com/forum/?fromgroups=#!topic/julia-users/yKdc8Tz757s. We can always move it later.

**Comment by nalimilan** [comment]
I can confirm this fixed the RPM nightlies (using system libunwind).

**Comment by tkelman** [comment]
ref https://github.com/JuliaLang/julia/pull/14965#issuecomment-180974299

**Comment by yuyichao** [comment]
Ahh, sorry I missed the comment, will try to make one.

**Comment by tkelman** [comment]
Up at https://s3.amazonaws.com/julialang/src/libunwind-1.1-julia2.tar.gz

**Comment by ViralBShah** [comment]
If this is going to be our official libunwind, perhaps we should move the repo to JuliaLang too.

**Comment by tkelman** [comment]
Yes, that makes sense.

**Pull request merged**
