### PR TITLE
Minor fix for long form anonymous functions

### PR DESCRIPTION
**Pull request by ghost**
Minor fix for #32557. Return type declarations for the long form anonymous functions now return ERROR.
```
julia> f = function(x)::Int
                  x/2
              end
ERROR: syntax: invalid "::" syntax
Stacktrace:
 [1] top-level scope at REPL[1]:1
```
To support for the return type declarations, we might have to change the definition of "function" in AST.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
To minimize breakage, I think the right thing here might be to give a clear warning like "this use of :: declares the type of the argument, but in the future may change to declare a return type instead".

**Comment by JeffBezanson** [comment]
Triage thinks we should run PkgEval on this and see if anybody is using this syntax before making a decision.

**Comment by JeffBezanson** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/33961#issuecomment-566217472):
```
NanosoldierError: failed to run tests against primary commit: UndefVarError: LibGit2 not defined
```
Logs and partial data can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/2d241357c01f39d69402b5acb7e2b73a62ee2cd0/pkgeval-6970fbd_vs_074974a/report.md)
cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/33961#issuecomment-566234747):
```
ProcessExitedException(2)
```
cc @maleadt

**Comment by maleadt** [comment]
Server crashed.
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/33961#issuecomment-566574468) has completed - possible new issues were detected. A full report can be found [here](https://github.com/maleadt/BasePkgEvalReports/blob/0d430c29f61028a02ce8dfcd5185a68b82c39902/pkgeval-6970fbd_vs_56d75f7/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
Nice! One thing we find out from PkgEval is that the `anon` flag used here (which, note, was not used at all in `parse-def` before) is not entirely accurate. It triggers an error on this case:
```
function (+)(p::CartesianPoint{T}, v::CartesianVector{T})::CartesianPoint{T} where {T <: Real}
```
where this initially looks like it might be an anonymous function since the signature begins with `(`. So this will need a bit more work.

**Comment by rfourquet** [comment]
Is something blocking this PR?

**Comment by JeffBezanson** [comment]
Yes, see my previous comment. This causes errors on previously valid signatures.

**Comment by DilumAluthge** [comment]
It looks like this pull request is no longer mergeable.

If you would still like to make this change, please make a new pull request based on the latest `master` branch of Julia.

**Pull request closed without merging**
