### PR TITLE
RFC: move `=>` to precedence level of `|>`

### PR DESCRIPTION
**Pull request by JeffBezanson**
Before:

```
julia> 1=>2 in Dict()
1=>false
```

after:

```
julia> 1=>2 in Dict()
false
```

My reasoning is that the precedence of `=>` needs to be higher than `in` or `==`, but lower than `+`. It should also be lower than `:`, since you can't make ranges of Pairs. That puts it directly in the precedence level of `|>`, which also makes sense since `|>` and `=>` look vaguely similar.

### CODE REVIEW

**Comment by vtjnash** [comment]
makes sense. while `=>` has an equals sign in it, it isn't actually an assignment.

**Comment by stevengj** [comment]
:+1:

**Comment by stevengj** [comment]
Wouldn't similar arguments apply to `prec-arrow`?

**Comment by JeffBezanson** [comment]
If you think of an arrow as "implies", then it makes sense for it to be lower than `==`.

**Comment by tkelman** [comment]
This breaks some packages' uses of FactCheck, hopefully all fixable with enough parentheses. I strongly encourage anyone who cares about the health of the package ecosystem leading up to 0.4 to install Vagrant and do some local PackageEvaluator runs while Iain's system is out of commission.

**Comment by IainNZ** [comment]
Kind of funny, this is probably the only really breaking change that seems to have happened in the last couple of weeks, just because of the FactCheck thing. Its not too many packages though, and an easy enough thing to fix.

**Comment by rened** [comment]
I have to say I rarely use the `1=>2 in Dict()` idiom, but use the following quite a bit more often:
```jl
Dict(:key => a == 1, :key2 => b == "hi" || b == "hey")
```
The precedence change makes it fail now:
```jl
Dict(:key => a == 1)  
# equals
Dict(=>(:key, a) == 1)  
# equals 
Dict(false)
```
(sidenote, this currently throws a BoundsError, see https://github.com/JuliaLang/julia/issues/12451)

Of course, the following works but I always feel an itch to remove the "unnecessary" parens:
```jl
Dict(:key => (a == 1), :key2 => (b == "hi" || b == "hey"))
```

Personally, I'd prefer to see the behavior reverted to what is was before this commit, as I believe it is more widely used.

**Comment by JeffBezanson** [comment]
I really don't agree. I don't think using the result of a comparison as a
key or value is that important. In most cases comparisons need parens to be
used for their value, e.g. (a==b)+1.

**Comment by stevengj** [comment]
I don't have strong feeling either way, but I can't find any `a => b == c` or similar expressions in the current packages.

**Comment by mdcfrancis** [comment]
This breaks the precedence of the `?` operator as well, it is a common idiom to use a condition when assigning to the RHS of a pair. 

https://github.com/JuliaLang/julia/issues/12948

Notably this is inconsistent with other languages 

    x = { a : true?true:false }
   Object {a: true}

**Comment by nalimilan** [comment]
@mdcfrancis Could you be more specific about "inconsistent with other languages"? Which ones?

**Comment by mdcfrancis** [comment]
@nalimilan - that's a JavaScript snippet.

**Comment by mdcfrancis** [comment]
I don't think I've ever used 

( :a=>1 ) in Dict( :a=>2 )

as I would commonly be checking based on the key and would use haskey. It is rare that I would be checking for value equality as well.

**Comment by ScottPJones** [comment]
I also think this was a step backwards.
`=>` seems like it should be higher than `=`, but lower than `==`, `?:`, etc.

Other languages?  Well, ':' is not an operator in other languages, but the way `=>` is treated now in Julia is inconsistent with probably most languages that have a table/dict/associative array constructor syntax, such as: Lua, Python, JavaScript.

**Comment by ScottPJones** [comment]
I think you really should though, for this, so that assignment of a Pair is handled well, unless you feel that that people really need to use () around the pair.

`a = :b => "string"`
`x = :b => cond ? "foo" : "bar"`

**Comment by JeffBezanson** [comment]
The `=` precedence level binds right to left, so that's parsed as `(a = (:b => "string"))`.

**Comment by ScottPJones** [comment]
Yes, in those examples, it works out fine, but I do think it's better to have it explicitly higher precedence than assignment, as it isn't really an assignment.
Is there a downside to adding a new precedence level?

**Comment by JeffBezanson** [comment]
Well there are already about 16 of them, and it's pretty confusing. Also if it has strictly higher precedence then `a = b => c = d` is `a = (b => c) = d`. That means to define a method of `=>` returning `d`, then the `=>` function is assigned to `a`. That's probably unexpected. However in these cases one is tempted to require parentheses.

**Comment by ScottPJones** [comment]
OK, so you'd just add it to the assignment precedence list in `julia-parser.scm`?  Telling people to use () in general is a good thing also :grinning:  (I've seen too many bugs from developers using multiple languages with different precedence levels - my fix, always use ()!)

**Comment by JeffBezanson** [comment]
For now I'm just going to revert this. I also realized that `=>` should be right-associative since it is "arrowlike", and this change broke that.

**Comment by mdcfrancis** [comment]
Thanks Jeff, much appreciated.

**Comment by StephenVavasis** [comment]
Sorry to reopen this topic, but something seems to be wrong with => precedence in 0.4-rc1 and 0.5.  Observe (from rc1):

julia> d = Dict(1=>2,3=>4)
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 2

julia> 1=>2,3=>4
1=>((2,3)=>4)

The second result is certainly unexpected, especially given the first result

**Comment by JeffBezanson** [comment]
Yeah well, too late now.

**Comment by ScottPJones** [comment]
Is the problem here really the parsing of `a,b` as a tuple, instead of requiring parenthesis, i.e. `(a,b)`?

**Comment by JeffBezanson** [comment]
The precedence of `=>` is fun and games compared to removing `a, b = x` syntax. Major league breakage.

Implication is the lowest precedence logical operator, so the arrows (which are not much used, so not a huge deal so far) should really be moved below `||`. I will definitely do that for 0.5. It would make sense for `=>` to be part of that set, but folks want to use `?` as an argument to `=>`, so it seems the only possibly choice is @ScottPJones ' suggestion of inserting `=>` by itself between assignment and `?`. I believe that would also fix the `1=>2,3=>4` case.

**Comment by tkelman** [comment]
The most noticeable thing the `=>` precedence change broke was FactCheck, which changed to use one of the arrows. Changing the precedence of the arrows would probably necessitate finding yet another operator to use for FactCheck.

**Comment by JeffBezanson** [comment]
Which precedence change broke FactCheck: the original change or the more recent revert of it?

**Comment by tkelman** [comment]
The original one. So it should be safe now to go back on that deprecation where FactCheck went from `=>` to `-->`, but any future changes to whichever operator FactCheck is recommending should be done with some care.

**Comment by JeffBezanson** [comment]
We should be ok; `=>` will not move far from where it is now.

**Pull request merged**
