### PR TITLE
tweak @parallel for a small improvement in performance

### PR DESCRIPTION
**Pull request by amitmurthy**
replaces `@spawn`/ `fetch` with `remotecall_fetch`

### CODE REVIEW

**Comment by amitmurthy** [comment]
Seeking an explanation for something I didn't understand while making this change:

- `make_preduce_body` calls `localize_vars` which returns an `Expr` object
- `preduce` expects a `Function` as the second argument. What is passed is the return value of `make_preduce_body`. How does this work?

**Comment by amitmurthy** [comment]
How do I restart the AppVeyor build? The link points to some other PR.

**Comment by amitmurthy** [comment]
Just did a dummy rebase and force push. Appveyor now points to different PR.  What is the way to fix this?

**Comment by ViralBShah** [comment]
Something seems broken at Appveyor.

**Comment by tkelman** [comment]
https://github.com/appveyor/ci/issues/353 - either continue with new pushes, rebases or otherwise, or an alternative is going into the github settings and re-delivering the webhook. I'll do that and see if it works correctly.

**Pull request merged**
