### PR TITLE
Let `muladd` accept a more restricted set of arrays

### LINKED ISSUE #784: evalpoly with matrix and Uniformscaling errors when number of arguments > 2
On nightly:

```jl
julia> using LinearAlgebra

julia> x = rand(2,2);

julia> @evalpoly(x, 1.0*I);

julia> @evalpoly(x, 1.0*I, 1.0*I);

julia> @evalpoly(x, 1.0*I, 1.0*I, 1.0*I);
ERROR: MethodError: no method matching length(::UniformScaling{Float64})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:54
  length(::Union{Adjoint{T, S}, Transpose{T, S}} where S where T) at /home/kc/juliamaster/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/adjtrans.jl:207
  length(::StepRangeLen) at range.jl:550
  ...
```

Works on 1.5.

From https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c3bb6df_vs_788b2c7/ExponentialUtilities.1.6.0-DEV-a896693d33.log

### LINKED ISSUE #38426: evalpoly with matrix and Uniformscaling errors when number of arguments > 2
On nightly:

```jl
julia> using LinearAlgebra

julia> x = rand(2,2);

julia> @evalpoly(x, 1.0*I);

julia> @evalpoly(x, 1.0*I, 1.0*I);

julia> @evalpoly(x, 1.0*I, 1.0*I, 1.0*I);
ERROR: MethodError: no method matching length(::UniformScaling{Float64})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:54
  length(::Union{Adjoint{T, S}, Transpose{T, S}} where S where T) at /home/kc/juliamaster/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/adjtrans.jl:207
  length(::StepRangeLen) at range.jl:550
  ...
```

Works on 1.5.

From https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c3bb6df_vs_788b2c7/ExponentialUtilities.1.6.0-DEV-a896693d33.log

### PR DESCRIPTION
**Pull request by mcabbott**
This adjusts JuliaLang/julia#37065 to be much more cautious about what arrays it acts on: it calls `mul!` on StridedArrays, treats a few special types like Diagonal, ~~UpperTriangular,~~ and UniformScaling, and sends anything else to `muladd(A,y,z) = A*y  .+ z`. 

However this broadcasting restricts the shape of `z`, mostly such that `A*y .= z` would work. That ensures you should get the same error from the `mul!(::StridedMatrix, ...)` method, as from the fallback broadcasting one. Both allow `z` of lower dimension than the existing `muladd(x,y,z) = x*y+z`. 

But `x*y+z` also allows `z` to have trailing dimensions, as long as they are of size 1. I made the broadcasting method allow these too, which I think should make this non-breaking. (I presume this is rarely used, and thus not worth sending to the fast method.)

Structured matrices such as `UpperTriangular` should all go to `x*y+z`. Some combinations could be made more efficient but it gets complicated. Only the case of 3 diagonals is handled. 

Closes JuliaLang/LinearAlgebra.jl#784.

### CODE REVIEW

**Comment by c42f** [comment]
Great :+1: I presume this will fix https://github.com/JuliaArrays/StaticArrays.jl/issues/849.

**Comment by mcabbott** [comment]
Sorry about that! 

Is it worth optimising the case `muladd(A::Matrix, B::Matrix, z::UniformScaling)`, with ordinary non-S-matrices? With this PR, it goes to `x*y+z`, but could be done more efficiently.

**Comment by c42f** [comment]
> Is it worth optimising the case `muladd(A::Matrix, B::Matrix, z::UniformScaling)`, with ordinary non-S-matrices?

I'm not sure. @mateuszbaran do you have a use case for this?

**Comment by mateuszbaran** [comment]
> > Is it worth optimising the case `muladd(A::Matrix, B::Matrix, z::UniformScaling)`, with ordinary non-S-matrices?
> 
> I'm not sure. @mateuszbaran do you have a use case for this?

I think I've never needed that, it should be fine to have that slower than optimal.

**Comment by mcabbott** [comment]
OK, maybe this is ready to go. I tried to check carefully this time...

**Comment by KristofferC** [comment]
Maybe https://github.com/JuliaLang/julia/issues/38426 could be added as a test.

**Comment by mcabbott** [comment]
I've added the `@evalpoly` example to the tests. Maybe this is ready?

**Comment by c42f** [comment]
Test failures seem unrelated? The linux32 appears to be some weird buildbot failure and the freebsd64 failure happens during the initial build.

**Review by c42f — APPROVED** [review]
Yeah, this looks good to me :+1:

**Comment by timholy** [comment]
Did this slow down the `LinearAlgebra/addmul` tests? Or are they just highly variable? I thought I've seen a recent doubling of their runtime on my own hardware, and these seem to confirm they take a long time (often 2x longer than any other test):

- https://build.julialang.org/#/builders/4/builds/6325
- https://build.julialang.org/#/builders/71/builds/6059/steps/5/logs/stdio

But this one doesn't seem much worse than `bitarray`:

- https://build.julialang.org/#/builders/34/builds/6365/steps/5/logs/stdio

So I am not sure if anything has really changed here.

**Pull request merged**
