### PR TITLE
Restrict vector indexing of views to 1-based ranges

### PR DESCRIPTION
**Pull request by jishnub**
This will be an offset array in general, so we need to restrict the method to 1-based ranges. This restores the behavior on `v"1.10"`.

The method was added in #45371

### CODE REVIEW

**Comment by mbauman** [comment]
Is the real root problem in broadcast?  To be concrete, indexing a `Vector` by an offset array should — and does — fail on both v1.10 and master if there's no offset array package loaded.  This seems sensible:

```
julia> v[Base.IdentityUnitRange(2:3)]
ERROR: MethodError: no method matching similar(::Vector{Int64}, ::Type{Int64}, ::Tuple{Base.IdentityUnitRange{UnitRange{Int64}}})
```

This SubArray method is forwarding a (potentially offset) index to a parent, which _should_ end up in that same situation.  But it's the broadcasted addition with the SubArray's offset that's causing the trouble:

```
julia> 0 .+ Base.IdentityUnitRange(2:3)
2:3

julia> axes(ans)
(Base.OneTo(2),)
```

Surely those axes should similarly be offset, yeah?  In fact, I think this is an overzealous `::Range` optimization that assumes 1-based indices.  If I hide the offset in a `Ref`, this does give me a pessimistic, but correct method error on similar (that would again work with OffsetArrays loaded):

```
julia> Ref(0) .+ Base.IdentityUnitRange(2:3)
ERROR: MethodError: no method matching similar(::Type{Array{Int64}}, ::Tuple{Base.IdentityUnitRange{UnitRange{Int64}}})
```

**Comment by mbauman** [comment]
Yeah, the real bug is that _all these methods_ assume 1-based axes:

https://github.com/JuliaLang/julia/blob/a0989f42b9bd0b46ec675748fca8f567ed4d13cb/base/broadcast.jl#L1100-L1168

**Comment by mbauman** [comment]
But that's a much bigger issue (see #30950 😳) — and the restriction on this particular optimization seems like a good solution for the immediate problem.  This just needs tests here — would be good to have two sets; one in test/offsetarray and one without them.

**Comment by jishnub** [comment]
I had actually added tests without offset arrays that I subsequently removed in https://github.com/JuliaLang/julia/pull/53249/commits/188c7fc0cc0b039baced74c291ed05fee04b29ec. I fear that if the `OffsetArrays` test helper is loaded incidentally before this test is run, the exception won't be thrown anymore (and it may be a bit difficult to diagnose this).

Adding a test to check that an offset array is returned when `OffsetArrays` is loaded sounds good, though.

**Comment by jishnub** [comment]
Should this be merged?

**Pull request merged**
