### PR TITLE
use `OptimizationParams` parameterized by `interp::AbstractInterpreter`

### PR DESCRIPTION
**Pull request by aviatesk**
This should allow constant propagation of `OptimizationParams`.

@nanosoldier `runbenchmarks("inference", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48225) failed.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48225#issuecomment-1378541450) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/10dca7e_vs_8985403/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48225#issuecomment-1458581813) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c03279c_vs_03fdd0f/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48225#issuecomment-1459201095) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/850231b_vs_a2912e2/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48225#issuecomment-1459373396) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/850231b_vs_a2912e2/report.md).

**Pull request merged**
