### PR TITLE
A few missing imports in LinAlg and DataFmt

### PR DESCRIPTION
**Pull request by andreasnoack**
The are also a few missing in `SparseMatrix`, but @mbauman will take care of those.

### CODE REVIEW

**Comment by tkelman** [comment]
why would these not cause test failures?

**Comment by andreasnoack** [comment]
Probably because they don't have tests.

**Comment by tkelman** [comment]
Can we rectify that?

**Comment by andreasnoack** [comment]
I'll take a look. I haven't used `writemime` before, but I have some experience with the linear algebra code.

**Comment by andreasnoack** [comment]
I've added tests that would have caught the missing `import`s.

**Comment by tkelman** [comment]
yay, thanks, +1

**Comment by mbauman** [comment]
Failure was the OOM killer.

For posterity, these missing imports were found by looking for shadowed Base names that aren't a part of the exported interface:

```jl
setdiff(intersect(names(Base.LinAlg, true), names(Base, true)), names(Base.LinAlg))
```

**Pull request merged**
