### PR TITLE
add pop!(::Dict) to return a key=>value pair

### PR DESCRIPTION
**Pull request by rfourquet**
I didn't find a discussion on this method, so I guess it's simply an omission. I propose it because I needed it.

### CODE REVIEW

**Comment by ararslan** [comment]
Since `Dict`s aren't ordered, this can return any pair? Seems kinda weird, IMO, since `pop!` to me typically implies removal from a well-defined position. Out of curiosity, what was your use case for this?

**Comment by iamed2** [comment]
For comparison, Python has `dict.popitem()` and `dict.pop(key[, default])`

**Comment by rfourquet** [comment]
This is no more weird than `pop(::Set)` returning any of its elements - and is what happens with normal iteration, where all the elements are visited in a non-specified order. This is useful for example if I want to iterate over all elements of a `Set`/`Dict` which can be modified, i.e. new elements are added from within the loop (I use the dict as a stack).

**Comment by ararslan** [comment]
Interesting, I didn't realize we supported `pop!(::Set)` either. I guess this is fine then, especially if it has precedent in other languages.

**Review by JeffBezanson — APPROVED** [review]

**Review by StefanKarpinski — APPROVED** [review]
LGTM

**Pull request merged**
