### PR TITLE
Backport: Correct mbedtls-cmake-findpy.patch whitespace.

### PR DESCRIPTION
**Pull request by Sacha0**
Backport of https://github.com/JuliaLang/julia/pull/39279. Best! :)

### CODE REVIEW

**Comment by KristofferC** [comment]
Why is a separate PR needed for this? If the original PR (which is not merged yet) has the label it will get backported. Also, seems this branch has some other commits on it.

**Comment by Sacha0** [comment]
> Why is a separate PR needed for this?

Trying to be kind to your backports branch, in case I make a mistake (e.g. the accidental extra commits) or CI is not happy. What you would you prefer that I do? :)

**Comment by Sacha0** [comment]
Valentin shared a slack thread that describes some of the (new to me) infrastructure and procedures around backports branches (e.g. the existence of https://github.com/KristofferC/Backporter). It would be great to make that infrastructure / those and any other procedures visible for those of us not as steeped in the details of the release processes :).

**Comment by Sacha0** [comment]
I took a stab in https://github.com/JuliaLang/julia/pull/39357 based on the relevant slack thread :).

**Comment by KristofferC** [comment]
>  What you would you prefer that I do? :)

No need to do anything, it'll get backported in time. If it is a complicated PR then I might ask for help in backporting it (then you can either make a PR or push directly to the backport branch).

**Pull request closed without merging**
