### PR TITLE
Rename allunique to anyduplicated

### PR DESCRIPTION
**Pull request by tkelman**
ref #15803 and #15914 - `allunique` seems to me like it implies composition `all(unique(x))` which isn't what this does, the `anyduplicated` name has precedent in R (where it is doing composition, we don't have a `duplicated` function in Julia right now but we conceivably could).

(I don't think this has been on master under its current name for long enough to warrant a deprecation)

### CODE REVIEW

**Comment by okvs** [comment]
I also tried to point out that there is a further issue with #15914:
```julia
>> r = linspace(1.0, nextfloat(1.0), 10)
>> allunique(r)
true
>> allunique(collect(r))
false
```
Is this not a problem?

**Comment by tkelman** [comment]
That might be an issue. Any suggestions for how to fix it? That doesn't really have a bearing on what to name it though.

**Comment by okvs** [comment]
You're right about that last point, but I see you did some code changes too, I thought I might bring it up.

I don't know if this is iron clad, since I haven't thought of many tests, but:
```julia
function hasduplicates_{T<:AbstractFloat}(r::Range{T})
    if step(r) == 0
        return length(r) > 1
    elseif step(r) > 0
        return last(r) < nextfloat(first(r), length(r) - 1)
    else
        return last(r) > nextfloat(first(r), -length(r) + 1)
    end
end
```
I'm not sure what happens when you have weird steps like for 
```julia
>> r = linspace(1,2,0)
linspace(1.0,2.0,0)
>> step(r)
NaN

```
Furthermore, I wonder whether it shouldn't be
`hasduplicates{T}(r::Range{T}) = (step(r) == zero(T)) && (length(r) > 1)`
instead of `length(r) > one(T)` since `length` always return an `Int`, right?

**Comment by okvs** [comment]
Hmm, maybe this should cover it for floats?
```julia
function hasduplicates{T<:AbstractFloat}(r::Range{T})
    length(r) <= 1 && return false
    rstep = step(r)
    r_ = nextfloat(first(r), flipsign(length(r)-1, rstep))
    return flipsign(last(r), rstep) < flipsign(r_, rstep)
end
```

**Comment by okvs** [comment]
Tests should include `linspace`s, and could be something along these lines:
```julia
!hasduplicates(linspace(1.0, nextfloat(1.0), 2))
hasduplicates(linspace(1.0, nextfloat(1.0, 1), 3))
!hasduplicates(linspace(1.0, nextfloat(1.0, -10), 11))
hasduplicates(linspace(1.0, nextfloat(1.0, -10), 12))
!hasduplicates(linspace(1.0, 1.0, 0))
```
The last one has step() = NaN, which might conceivably trip up some implementations.

**Comment by okvs** [comment]
Here's another one that fails with the current code, but works with the one I suggested:
`hasduplicates(range(2.0, eps(1.0), 4))`

**Comment by okvs** [comment]
Hmmm. This one fails, though:
`hasduplicates(range(prevfloat(typemax(Float64)), eps(1.0), 10))`

There are some pretty hairy edge cases with `LinSpace` and `FloatRange`. It might require some deeper digging into their definitions.

**Comment by nalimilan** [comment]
Why not, if that would be a more efficient version of a (possible) any(duplicated(x)).

@okvs I think you should open a separate issue, that's a complex enough problem.

**Comment by okvs** [comment]
It seemed like a pretty easy fix, when the code was being changed anyway. But now it looks like a rabbit hole, I think it even touches on some problems with `linspace` and `range`.

**Comment by ararslan** [comment]
Unless I'm missing something, wouldn't `allunique` be the *opposite* of `anyduplicated`? With this proposal, to determine whether a collection consists entirely of unique elements you need `!anyduplicated`, whereas currently you use `allunique`, so this isn't really a renaming so much as swapping one function for another, right?

**Comment by tkelman** [comment]
Yes this would be flipping the sense in addition to the different name. Sounds like there are 3 against, 2 or maybe 3 for this. I dislike having that "all" in the name, but not enough people spoke up here with a straight +1 or -1 for it to be conclusive one way or the other.

**Pull request closed without merging**
