### PR TITLE
make () optional for no argument functions in REPL

### PR DESCRIPTION
**Pull request by ghost**
Very convenient for functions like `exit`, `clf`, `grid`, `figure`, `tight_layout`, and such. Typing `exit<ENTER>` will end the process, no need for extra `()` at the end. Saves a lot of keystrokes too: `tig <TAB><ENTER>` is now enough to call `tight_layout()`.

### CODE REVIEW

**Comment by yuyichao** [comment]
👎  This is one of the MATLAB feature that I hated the most.

**Comment by gaika** [comment]
Just to clarify, this is only for REPL, the functions still require `()` when used in the code. It is pretty harmless, very little ambiguity.

**Comment by yuyichao** [comment]
> Just to clarify, this is only for REPL, and only when it is standalone symbol. The functions still require `()` when used in the code.

Yes, I know.

> It is pretty harmless, very little ambiguity.

I totally disagree.

> I've been using MATLAB for ages and in Julia kept typing clf into the REPL twice because of the muscle memory :(

And I've had countless number of time trying to check the function itself and accidentally calling it in MATLAB.

As other REPL features, an option that's off by default might be OK.

**Comment by tkelman** [comment]
having things work differently in the repl vs other code is not a good idea. you could define zero arg macros for these in your juliarc if you feel like doing that.

**Pull request closed without merging**
