### PR TITLE
fix #16815, showing an Enum value should use single-line repr of its type

### LINKED ISSUE #16815: Enum showing is lousy
Current master:
```julia
julia> @enum(Color, Red = 0, Green = 1, Blue = 3)

julia> Color
Enum Color:
Red = 0
Green = 1
Blue = 3

julia> Red
Red::Enum Color:
Red = 0
Green = 1
Blue = 3 = 0

julia> Green
Green::Enum Color:
Red = 0
Green = 1
Blue = 3 = 1

julia> Blue
Blue::Enum Color:
Red = 0
Green = 1
Blue = 3 = 3
```
It's confusing because:
* `typeof(Red) == Color`, but we print `Red::Enum`, which is still true, but one level removed from the actual value of `typeof(Red)`
* Printing out the enum instance integer value on the last line is obviously very confusing:

 `Blue = 3 = 0`??
* It feels very cluttered to print the entire set of enum instances with each value; I find myself visually hunting around to figure out what exactly I'm looking at

I'd propose something more like:
```julia
julia> @enum(Color, Red = 0, Green = 1, Blue = 3)

# align the equal signs
julia> Color
Color::Enum:
Red   = 0
Green = 1
Blue  = 3

julia> Red
Red

# alternatively
julia> Red
Red::Color = 0
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by vtjnash** [comment]
I wonder if this hints that multiline shouldn't have been sticky on the IO stream. E.g. that there should be a `show_multiline` function (default is to dispatch to `show`), and otherwise show assumes it should print a single line representation. Are there any examples where having this property silently propagate gives better output?

**Comment by nalimilan** [comment]
Also, isn't there a simpler way of representing the name of a type? Why isn't `repr` or `string` enough?

**Comment by JeffBezanson** [comment]
Yes, I think I could have used `repr` or `string`, but when printing I prefer to use I/O functions directly instead of converting things to strings first and then printing them.

@vtjnash That's a good point; `show` functions almost always want to turn `multiline` off for printing components of an object. But I can't quite stomach adding a function just for this; it seems simpler just to use the mechanism we have.

**Comment by nalimilan** [comment]
Well, the new version is terribly obscure and complex IMHO. I don't think anybody is going to find out that's the preferred way of printing components of an object.

**Comment by JeffBezanson** [comment]
OK, I can imagine handling verbosity via separate functions. Arguably we are already doing that with `print` vs. `show`. Previously `writemime` *in some cases* was used to mean "most verbose, multiline output", but it doesn't make sense to couple that to MIME types. We could add a third basic printing function, but I think a good test is whether we can think of a good name for it. Maybe something like `replshow`?

I don't think it's fair to dismiss the current approach as obscure and complex. Issues on this were open for months or years. Before, we had a completely inscrutable nest of output functions, and it wasn't even possible to control output in a general way. The fact that some cases could be handled with concise code didn't prevent loud and frequent complaints.

**Comment by nalimilan** [comment]
The new system is clearly a big improvement, not doubt about that. I was just speaking about the specific case of representing the name of a type, which is very simple, and for which I think we need a simple solution. `replshow` sounds like it's limited to interactive use, which isn't necessarily the case. Maybe a name similar to `showcompact`, but referring to multiline? Or maybe `showcompact` could also set `:multiline=>false`, since that's the most common need?

**Comment by JeffBezanson** [comment]
Setting multiline to false in `showcompact` sounds like a good idea.

**Comment by nalimilan** [comment]
Found another case of this when printing Nullable, see https://github.com/JuliaLang/julia/pull/16842. I suspect this pattern is quite common when printing custom types.

**Pull request merged**
