### PR TITLE
Revert "Some fixes for summary, show, and map for non-1 indices"

### PR DESCRIPTION
**Pull request by tkelman**
Reverts JuliaLang/julia#17729

e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4947/job/bywb4b7b1vmo5fc4

### CODE REVIEW

**Comment by tkelman** [comment]
Having trouble reproducing the failure locally so maybe it's an intermittent thing.

**Comment by yuyichao** [comment]
Note that the linked failure is on my WIP pr. So it could be caused by that PR.

**Comment by tkelman** [comment]
Yeah I think I didn't call this one right. Once in a while we do see PR's that pass when CI runs on them, but fail after merged into master because of some other change that got merged in the interim, but this probably was not one of those cases.

**Comment by timholy** [comment]
This was a pretty unlikely one to cause trouble---anything that touches `map` is of course a little scary, but really it was all obvious stuff and should be as wholesome as apple pie.

**Pull request closed without merging**
