### PR TITLE
Channel and RemoteChannel

### PR DESCRIPTION
**Pull request by amitmurthy**
Revisiting the idea to have support for "channels" in Base.
- A `Channel` is used for inter-task communication. Implementation is in `task.jl` 
- Channels have a size, i.e., the maximum number of elements that can be `put!` without blocking. Defaults to 1. 
- They also have a type associated with it. Defaults to `Any`.
- Channels would be a much cleaner interface for the recent `ClusterManager` interface change, where multiple tasks work in parallel totally asynchronously, unlike the `produce`/`consume` pattern which works best where both the producer and consumer work in lock-step.
- `put!` blocks when a channel is full.
- `take!` and `wait` block when it is empty.
- `isready` denotes availability of data in the channel
- `RemoteRef` has been renamed to `RemoteChannel`. Like local channels, they too have a size and type associated with it. Defaults to 1 and `Any`. Unlike a `Channel`, a `RemoteChannel` is accessible across processes. 

TODO:
- [x] documentation
- [x] more tests
- [x] Change the backing object of a `RemoteChannel` to use a `Channel`

### CODE REVIEW

**Comment by ViralBShah** [comment]
Isn't this now in a package? Can it be closed?

**Comment by amitmurthy** [comment]
Similar functionality is available in https://github.com/JuliaParallel/MessageUtils.jl

However, I do feel that we should have channel functionality in Base itself. Channels are a very useful feature for inter-task communications where producers / consumers do not have to co-ordinate with each other. 

And it changes RemoteRef from “shared queue of length 1” to "shared queue of an arbitrary length".

I can rework this PR against the current master. One change I would like is to retain the name `RemoteRef` as an alias for `RemoteChannel(1)`, i.e. a RemoteChannel of length one. Too much of user code out there to unnecessarily annoy them.

**Comment by ViralBShah** [comment]
Is this something we should be targeting for 0.4?

**Comment by StefanKarpinski** [comment]
I think this is a good idea, but I worry about how multithreading is going to affect the API. Go has a channel abstraction that is only for talking between threads in the same process. This is similar, but for talking between tasks either on the same process or across processes (potentially across a network). Do we think this model will survive as is once we have threading?

**Comment by amitmurthy** [comment]
Yes. Will update this PR.

**Comment by amitmurthy** [comment]
Actually Channels are optimized for inter-task communication. While RemoteChannel is more like a handle to a Channel on a different process.

In Erlang, every task has its own message queue, and it is trivial to send a message to a remote task's message queue. Architectures that rely on messaging between lots of tasks will have a need for channels. Multi-threading will reduce the need for shared arrays, but for message driven architectures, where users do not want to deal with locking/unlocking shared resources, message queues are a better model.

A contrived example with tasks and threads - but actually quite a common pattern.

- A Julia web app process has, say, 10 database I/O threads, each of which executes blocking SQL calls. The actual request to be executed is read from a common input channel.
- Incoming HTTP requests, say upto a 1000 concurrent requests, all run under a single thread, but in 1000 different tasks.
- When a request needs database I/O, the request, along with a response channel object are wrapped in a message and dumped onto the database channel, after which the task waits on the response channel.
- The database I/O threads simply work off the queue and results are returned as messages into the response channel.

**Comment by amitmurthy** [comment]
Message queue based communication between lots of very lightweight tasks - which are usually waiting for some event to happen - I/O, timer, etc is different from multi-threading for taking advantage of multiple cores.

Tasks blocking on libuv events are OK. We can have thousands of them in the same thread. Multi-threading will be used for either spreading computation across cores or b) as in the database example above, since, AFAIK, the standard model in ODBC is thread blocking calls.

**Comment by amitmurthy** [comment]
Closed in favor of #12042

**Pull request closed without merging**
