### PR TITLE
Tests for bitarray

### PR DESCRIPTION
**Pull request by kshyatt**
cc @carlobaldassi 

A bunch of error throwing methods were not tested. Some methods weren't tested at all.

### CODE REVIEW

**Comment by carlobaldassi** [comment]
Ah great, thanks as usual. There's a conflict but it should be trivial.

**Comment by kshyatt** [comment]
I'll fix the conflict ASAP.

I did this PR while very sleepy and I forgot to mention something - I think I found some bugs and I will open an issue for them.

**Comment by kshyatt** [comment]
abd70e0e6b91f3ab1ab1901e52804ffdbb96b3c6 introduced the conflict and a `depwarn` in the tests. Fixing that too.

**Comment by kshyatt** [comment]
Ok to merge?

**Pull request merged**
