### PR TITLE
[RFC] haskey(d, k1, k2...): check for keys in nested dicts

### PR DESCRIPTION
**Pull request by StefanKarpinski**
I found myself wanting to check for the presence of a sequence of keys in a nested dictionary and this would be quite handy for that.

### CODE REVIEW

**Comment by laborg** [comment]
Users might think that this API checks for multiple keys in the dict at once, so basically what `all(haskey.(dict,[k1,k2,k3]))` would return if broadcasting would be defined. At least I would be a little bit surprised that this recurses into the values.

**Comment by JeffBezanson** [comment]
I think this is fine in itself, but we defined multi-argument `getindex` for Dicts to look up a tuple, which conflicts somewhat. In hindsight I'm not sure that was a good idea; I don't think I've ever used that feature, and nested dicts (json!!) are much more common than tuple-key dicts.

**Comment by fredrikekre** [comment]
> Users might think that this API checks for multiple keys

That's what I thought.

**Comment by oscardssmith** [comment]
It seems like the best solution would be to define a `NestedDict` with a custom `getindex` method.

**Pull request closed without merging**
