### PR TITLE
Bundle libssl and libcrypto on Linux

### PR DESCRIPTION
**Pull request by staticfloat**
This causes `install-libgit2` to copy in the `libssl` and `libcrypto` that it picks up from the system into `$(build_shlibdir)`.  This is important because without it, `libgit2` won't load, as it refuses to link against newer `libssl` implementations.

This isn't a problem on OSX or Windows, because OSX's `libssl` is consistent enough across versions, and Windows doesn't have a native one so we bundle everything anyway.

### CODE REVIEW

**Comment by staticfloat** [comment]
I ran into this while trying to get @timholy's coverage package running using the generic linux Tarballs.  Tim, you can track my progress [here](http://buildbot.e.ip.saba.us:8010/waterfall?category=Coverage).

**Comment by tkelman** [comment]
This scares me a little, in terms of the number of security updates these libraries require on a regular basis. On Windows I think we're actually building with SSH disabled, but I'm not sure what the consequences of that will be in terms of package manager functionality. On WinRPM where openssl is already packaged, it was easier to enable this for libgit2.

**Comment by staticfloat** [comment]
I'm assuming you meant `SSL` instead of `SSH` above.

I don't think these libraries, despite being older, are any more vulnerable.  They were last updated in October 2014, for the latest SSLv3 vulnerability discovered around then.

**Comment by tkelman** [comment]
> I'm assuming you meant `SSL` instead of `SSH` above.

Nope, confusingly enough I meant what I said, not a typo - https://github.com/JuliaLang/julia/blob/8938e3a32c68910ccfa84d5bb5f6c7850920a38a/deps/Makefile#L1773

We also might want to bump to 0.22 while we're at it, which just came out a few days ago and might change some of this situation. @jakebolewski I think I saw you had a branch to update your package to the new version, should we build it yet?

**Comment by staticfloat** [comment]
Any other objections to this?  This is holding up my work on getting coverage done on a per-commit basis (Well, as per-commit as our continuous deployment is).  I've restarted the Linux travis build twice, it appears we have some hidden segfaults on `master` right now.  :/

**Comment by tkelman** [comment]
As long as you make sure the buildbots keep up-to-date on these libs, we may as well try this out, see whether it causes any issues.

**Pull request merged**
