### PR TITLE
R microbenchmark: Use microbenchmark for much higher accuracy in timing

### PR DESCRIPTION
**Pull request by XD-DENG**
The main change is:

``` r
 t = system.time(f(...))["elapsed"]
```

TO

``` r
t <- microbenchmark(f(...), times = 1)$time/1e9
```

in time counting function. _microbenchmark()_ function can achieve accuracy to nanosecond unit. This is also I divide it with 1e9 (1 second = 1 nanosecond \* 1e9)

Additionally, used more R-style assign symbol (i.e. replace " = " with " <- ")

### CODE REVIEW

**Comment by tkelman** [comment]
Any R users have any comments here? @simonbyrne is this reasonable? Looks like @XD-DENG deleted his fork.

**Comment by XD-DENG** [comment]
@tkelman , Hi, thanks for the comments. Yes, I've deleted my fork, but you can find the modification in my pull request at https://github.com/JuliaLang/julia/pull/16068/files , and you can still merge this PR as well, if you find it useful.

Thanks!

**Comment by StefanKarpinski** [comment]
Seems like a sound change to me – using higher accuracy timing makes sense. It would be good to separate out the purely cosmetic change from `=` to `<-` from the substantive timing change.

**Comment by XD-DENG** [comment]
@StefanKarpinski Thanks for your comment Stefan. How about I close this PR & open another one only with the timing benchmarking change?

**Comment by StefanKarpinski** [comment]
That would be great, if you're willing.

**Comment by XD-DENG** [comment]
@StefanKarpinski  @tkelman , As @StefanKarpinski suggested, I opened another PR containing only the benchmarking method change #16180

**Pull request closed without merging**
