### PR TITLE
add docstring for @ at the REPL

### PR DESCRIPTION
**Pull request by jaideep-seth**
This is an attempt for only '@' (One of seven) described [in this issue](https://github.com/JuliaLang/julia/issues/33666).

Reference: #33666

### CODE REVIEW

**Comment by mbauman** [comment]
Welcome @jaideep-seth!  This looks like a good take on tackling part of https://github.com/JuliaLang/julia/issues/33666.  In general, I encourage you to use more descriptive commit messages — which can then auto-populate your pull request with title and description.  Just saying something like: "add docstring for `@` at the REPL" would be great — you can still edit the title and body of this PR, which would be very helpful to others.

**Comment by jaideep-seth** [comment]
Hi @mbauman , i was a Google Summer of Code 2019 student with INCF. Now im eager to mentor Google Code In 2019 tasks (Small tasks like this one). Please help me get this PR merged inorder to make an appealing case to be a mentor.

Thank you so much!

**Comment by jaideep-seth** [comment]
Hey @mbauman i raised an issue ( #33844 ) as the buildbot asked me to in the build log.

Could you please guide me on how i can clear the remaining build tests?
Thank you!

**Comment by ViralBShah** [comment]
Hi @jaideep-seth - the buildbots are not related to your PR. Please improve the commit message and make it descriptive as suggested.

**Pull request merged**
