### PR TITLE
Various line length, indentation and spelling adjustments

### PR DESCRIPTION
**Pull request by tkelman**
There should be no functional changes here, primarily spacing and spelling.

### CODE REVIEW

**Comment by musm** [comment]
The comments in https://github.com/JuliaLang/julia/blob/974725053d18572a2934408e51bb0838ff4f0648/base/linalg/cholesky.jl

also need to be wrapped

**Comment by musm** [comment]
This comment too: https://github.com/JuliaLang/julia/blob/master/base/linalg/triangular.jl#L1318

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/blob/master/base/linalg/generic.jl#L1060

**Comment by musm** [comment]
A lot of these linalg files have ridiculously  long lines, making it hard to read

**Comment by andreasnoack** [comment]
@musm I don't understand why you'd prefer to adjust prose by hand over using soft line wrapping which is the reason why some of the comments and error messages in linalg are long. E.g. adjusting the next nine lines when I edit a single word or having every second line only consist of a single word when I happen to have a narrow window don't seem preferable to me. However, the hard-new-liners are more vocal  than the soft-new-liners so I've come to terms with the defeat. 😄

**Comment by tkelman** [comment]
Github doesn't soft wrap Julia code, comments or otherwise. Neither do all editors. Hence the style guide recommending a maximum line length, that much of linalg is so egregiously ignoring.

**Comment by musm** [comment]
@andreasnoack I usually softwrap prose documents e.g. tex documents.

@tkelman 
https://github.com/musm/julia/blob/98466be678d1b5ad53de3deda8601462e9231f39/base/replutil.jl#L225

**Review by kshyatt — APPROVED** [review]

**Pull request merged**
