### PR TITLE
Put back the old QuickSort and PartialQuickSort algorithms

### LINKED ISSUE #47304: PartialQuickSort needs a compat annotation
Its functionality was expanded in #45222

### LINKED ISSUE #47715: Sort allocate x2 more memory in master
Hi,
It seems the sort function allocates twice more memory in master vs 1.8.3:

```julia
using BenchmarkTools
x = rand(10^8);
@btime sort($x);
```

In 1.8.3 I get 2 allocations 762 MiB vs 6 allocations 1.49GiB in master.
Is that considered a regression and will it be addressed?
I see that the time spent is improving from 10.2s to 6.2s.
Thank you

PS: I am on Windows and have asked the above question on discourse but did not get any feedback.

### LINKED ISSUE #47766: Regression in allocations of `partialsort!`
I found this while starting to fall into the pit of decemberly despair that is advent of code:

1.6.7:

```julia
julia> @benchmark partialsort!(data, 1:3; rev=true) setup=(data=rand(10_000)) evals=1
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):   26.180 μs … 283.649 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     121.591 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   120.735 μs ±  37.872 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                    ▁▃▂▃▅▅▄▆▆▇▆█▇█████▇▅▇▆▇▅▅▂▂▁▁                
  ▁▂▂▃▃▄▄▄▄▆▆▆▇█▇▇███████████████████████████████▇▇▇▆▅▄▄▄▃▂▃▂▂▂ ▆
  26.2 μs          Histogram: frequency by time          210 μs <

 Memory estimate: 80 bytes, allocs estimate: 2.

julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

1.10/recent-ish master:

```julia
julia> @benchmark partialsort!(data, 1:3; rev=true) setup=(data=rand(10_000)) evals=1
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  31.265 μs … 717.012 μs  ┊ GC (min … max): 0.00% … 81.97%
 Time  (median):     48.968 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   53.924 μs ±  35.874 μs  ┊ GC (mean ± σ):  3.42% ±  5.12%

     ▁▄▅▅▇█▆▇▇▅▆▅▅▃▃▃▂                                          
  ▂▄▇█████████████████████▇▇▆▆▅▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▁▂▁▁▁▁▁▁▁▁▁ ▄
  31.3 μs         Histogram: frequency by time          106 μs <

 Memory estimate: 156.34 KiB, allocs estimate: 4.

julia> versioninfo()
Julia Version 1.10.0-DEV.6
Commit 4cf077cd9a (2022-11-14 21:07 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

The speedup in the average case is nice, but can it be achieved without allocating almost twice the memory that already exists? I think this may be due to the work-space work done recently, so may be related to #47715 (cc @LilithHafner). `partialsort!` doesn't take an algorithm keyword, so there's no workaround for now, I don't think.

### PR DESCRIPTION
**Pull request by LilithHafner**
Put back the old QuickSort and PartialQuickSort, and MergeSort algorithms, rename the new PartialQuickSort to QuickerSort, improve the documentation and API for constructing QuickerSort, and test the QuickerSort API.

Most of the additions are copied verbatim from 05cfe245ce27ffa27669a3cac419e4b0991f8cb1, the commit before #45222 which removed the old implementations of QuickSort and PartialQuickSort.

I'm open to bikesheding on the name QuickerSort. Names I already considered:

`StableQuickSort` — this algorithm can be stable, but it takes a bit of extra work (which we currently always perform). In future versions of julia, perhaps `sort` will take a `stable` keyword, and if `stable` is false, then this algorithm need not perform the cheap-but-not-free reversals which stabilize it. I don't like `sort(v, alg=StableQuickSort, stable=false)`.

`OutOfPlaceQuickSort` — this is long and fails to represent the fact that the algorithm it refers to is typically faster than quicksort.

Fixes #47715 
Fixes #47766
Fixes #47304 by reverting the expanded functionality that would need a compat entry (QuickerSort is still technically internal)
Closes #47297 because QuickerSort can use a fresh API with no need to deprecate any PartialQuickSort methods.

### CODE REVIEW

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47788#issuecomment-1336092002) failed.

**Comment by LilithHafner** [comment]
Strange.
@nanosoldier `runbenchmarks(["sort"])`

**Comment by LilithHafner** [comment]
The nanosoldier issue is not blocking.

**Comment by LilithHafner** [comment]
Local perf tests demonstrate that this restores previous allocation levels:
```julia
julia> x = rand(Int, 10000);

julia> @btime sort!(rand!($x));
  233.624 μs (3 allocations: 86.36 KiB)

julia> @btime sort!(rand!($x); alg=QuickSort);
  419.169 μs (0 allocations: 0 bytes)

julia> @btime sort!(rand!($x); alg=PartialQuickSort(1:3));
  7.815 μs (0 allocations: 0 bytes)
```

**Comment by maleadt** [comment]
@vtjnash probably hasn't updated the benchmark bot to the latest Nanosoldier.jl, so it might still require the `:vs` keyword:

@nanosoldier `runbenchmarks("sort", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47788#issuecomment-1336128633) failed.

**Comment by maleadt** [comment]
> [Your job](https://github.com/JuliaLang/julia/pull/47788#issuecomment-1336128633) failed.

@vtjnash will have to look at the server logs for this one.

**Comment by vtjnash** [comment]
I don't understand why it failed to upload the logs for this as it should have
```
      From worker 3:    2022-12-03T05:26:16.573 | starting benchscript.jl (STDOUT/STDERR will be redirected to the result folder)
┌ Info: [Node 3 | 2022-12-03T05:28:00.583]: failed job: BenchmarkJob JuliaLang/julia@cc25f42 vs. JuliaLang/julia@cee0a04
│ On worker 3:                                                                                       
│ failed process: Process(`sudo -n -- /nanosoldier/cset/bin/cset shield -e -- sudo -n -u nanosoldier-worker -- /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_lN3A
c3/benchscript.sh`, ProcessSignaled(11)) [0]                                                                                                                                                              
```
the log content is
```
[761710] signal (11.1): Segmentation fault
in expression starting at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_lN3Ac3/benchscript.jl:18
jl_gc_pool_alloc_inner at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gc.c:1332 [inlined]
jl_gc_pool_alloc_noinline at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gc.c:1385
jl_gc_alloc_ at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/julia_internal.h:460 [inlined]
jl_new_uninitialized_datatype at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/datatype.c:98
inst_datatype_inner at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/jltypes.c:1525
jl_inst_arg_tuple_type at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/jltypes.c:1665
arg_type_tuple at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:1965 [inlined]
jl_lookup_generic_ at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2650 [inlined]
ijl_apply_generic at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2702
getindex at ./range.jl:419
jfptr_getindex_26325 at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/usr/lib/julia/sys.so (unknown line)
_jl_invoke at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2524 [inlined]
ijl_apply_generic at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2706
#_run#48 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:100
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:92
unknown function (ip: 0x7f87d055934d)
_jl_invoke at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2524 [inlined]
ijl_apply_generic at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2706
jl_apply at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/julia.h:1876 [inlined]
jl_f__call_latest at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/builtins.c:778
#invokelatest#2 at ./essentials.jl:818 [inlined]
kwcall at ./essentials.jl:813 [inlined]
#run_result#45 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:34 [inlined]
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:34 [inlined]
#run#49 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:117
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:117 [inlined]
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:117 [inlined]
macro expansion at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:135 [inlined]
macro expansion at ./timing.jl:393 [inlined]
#51 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:134
#_withprogress#47 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:73
unknown function (ip: 0x7f87d0558477)
_jl_invoke at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2524 [inlined]
ijl_apply_generic at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2706
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:63
unknown function (ip: 0x7f87d0555e52)
#run#50 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:125
kwcall at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:125
macro expansion at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:135 [inlined]
macro expansion at ./timing.jl:393 [inlined]
#51 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:134
#_withprogress#47 at /home/nanosoldier-worker/.julia/packages/BenchmarkTools/0owsb/src/execution.jl:73
unknown function (ip: 0x7f87d0558477)
_jl_invoke at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2524 [inlined]
ijl_apply_generic at /home/nanosoldier/.julia/scratchspaces/89f34f1a-2e6b-52eb-a20f-77051b03b735/workdir/jl_yTI0w1/julia/src/gf.c:2706
```

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47788#issuecomment-1356760783) has completed - successfully executed benchmarks. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4a0ac47/report.md).

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47788#issuecomment-1356927748) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/32b8f48_vs_eb57a77/report.md).

**Comment by LilithHafner** [comment]
This restores the previous performance of QuickSort; the fact that it is typically an improvement is disturbing and likely connected to https://github.com/JuliaLang/julia/pull/47383#issuecomment-1349666916

**Pull request merged**
