### PR TITLE
fix #20406, parse infix `~` as a normal operator

### LINKED ISSUE #20406: change parsing of `~` from macro to operator
From https://github.com/JuliaLang/julia/issues/19598:

- [ ] change parsing of `~` in Base from macro to plain infix operator (https://github.com/JuliaLang/julia/pull/20420)
- [x] change the one user of this as a macro – i.e. StatsModels (https://github.com/JuliaStats/StatsModels.jl/pull/9)

- [ ] update DataFrames to depend on the new version of StatsModels (issue/PR link?)

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by stevengj** [comment]
Should this be added to the list of dottable operators?  (Currently, `~` is special-cased in `prec-assignment`.)

**Comment by stevengj** [comment]
Needs listing in NEWS.

**Comment by StefanKarpinski** [comment]
Weirdly small change. I knew this wouldn't be massive, but I didn't realize it would be this small.

**Comment by stevengj** [comment]
You forgot to add it to the dottable-operators list?

**Comment by JeffBezanson** [comment]
I guess we can add it to the dottable operators list, I just don't know what it's for so it's hard to know whether it makes sense.

**Comment by stevengj** [comment]
The general rule in 0.6 is that every operator is dottable, precisely so that the caller can decide whether to broadcast them.

**Comment by StefanKarpinski** [comment]
Sure, why not?

**Pull request merged**
