### PR TITLE
Ensure Distributed workers inherit threads spec properly

### PR DESCRIPTION
**Pull request by kpamnany**
Now that there are threadpools, we cannot simply use `Base.JLOptions().nthreads` to get the threads spec for Distributed workers.

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
We typically don't need the `@static` VERSION checks for stdlibs, right? So we can just use the 1.9 version here instead of keeping the old compat version too?

**Comment by kpamnany** [comment]
Happy to drop it. I followed the pattern I used when fixing this for [Pkg.jl](https://github.com/JuliaLang/Pkg.jl/pull/3467). I don't know if the convention is different?

**Comment by IanButterworth** [comment]
My bad, yeah we don't need the version check. That should be removed from Pkg

**Comment by kpamnany** [comment]
Removed from here.

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
