### PR TITLE
Consolidate cholesky tests a little

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by KristofferC** [comment]
This is not an improvement in my opinion.

**Review by fredrikekre — COMMENTED** [review]
Change looks fine, no opinion about if this is better or worse.

**Comment by ViralBShah** [comment]
#24054 and #24055 seem to be the similar PRs. For the record here the discussion is in #24055.

**Comment by KristofferC** [comment]
To give a bit more context to my earlier comment (which in hindsight was a bit "direct") I think that too much DRY in tests can increase coupling and make it harder to get an overview of the state when the test is run. Instead of putting tests in the same loop to make sure they test the same types, in my opinion, having a `TEST_LU_TYPES` that each test loop over independently is preferred.

However, this is just my opinion and I don't feel very strongly about it so I am in no way "blocking" this PR from getting merged.

**Comment by kshyatt** [comment]
Thanks for clarifying! I didn't think you were "too direct" or
uncomfortably blunt, fwiw. It's good to hear what other people think
without beating around the bush. I don't feel very strongly either. If
someone else wants to "tie break" go ahead, and if the PRs get closed I'll
self soothe by putting testsets in other files :).

**Comment by StefanKarpinski** [comment]
I'm in favor of both PRs because there doesn't tend to be a lot of structure to test files, and tests just end up in some random and arbitrary order, so grouping them together at least by what type-loops they fall under seems like as good a structure as any. I would agree if there was some other logical ordering that this was interfering with, but afaict, there is none.

**Comment by StefanKarpinski** [comment]
Agree with the general sentiment that overDRYing things can be a problem, but I don't see it here.

**Comment by KristofferC** [comment]
AppVeyor and CircleCI is:

```
Worker 5 failed running test sparse/sparse:
Some tests did not pass: 1772 passed, 0 failed, 1 errored, 0 broken.sparse/sparse: Error During Test
  Test threw an exception of type MethodError
  Expression: !(Base.USE_GPL_LIBS) || abs(det(factorize(Symmetric(A)))) ≈ abs(det(factorize(Array(A))))
  MethodError: no method matching logabsdet(::Base.LinAlg.LDLt{Float64,SymTridiagonal{Float64,Array{Float64,1}}})
```

and some libgit2 error. Should be unrelated.

**Comment by Sacha0** [comment]
Much thanks for your continuous efforts to improve the linear algebra and other tests, `@kshyatt`! :)

I lack a strong opinion about the specific changes in this and the associated pull requests. Generally, however, I share `@KristofferC`'s sentiments about the linear algebra tests: The extensive intra-file coupling makes comprehension a challenge. Understanding the state associated with a single test often requires skimming a substantial fraction of the associated file, and frequently also reasoning about distant (and well-separated) nested loops. I would love to see these files evolve away from that degree of coupling :).

**Comment by kshyatt** [comment]
I think part of our problem in these files is the insistence on using one "starter" matrix for all the tests. If we could decouple things into functions it might make things easier, then you'd pass the starter matrix into a function named `test_nonpivoted_lu_solves` or something and that function would have some nice comments explaining what features the input matrix ought to have.

**Comment by ViralBShah** [comment]
Rethinking the linalg tests would certainly be welcome. In the meanwhile I think we should merge these.

**Comment by kshyatt** [comment]
Since @StefanKarpinski and @ViralBShah voted "yes" on these, I will merge them (and the other two similar PRs), and try to clean up the files in general.

**Pull request merged**
