### PR TITLE
Use isbindingresolved when checking imported packages

### LINKED ISSUE #21578: Warning when updating Iterators.jl
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.353 (2017-04-26 22:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 09299516b5* (0 days old master)
|__/                   |  x86_64-apple-darwin15.6.0

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of Compose...
INFO: Updating cache of Iterators...
INFO: Updating cache of StaticArrays...
INFO: Updating cache of Interpolations...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: Upgrading Compose: v0.5.0 => v0.5.1
INFO: Upgrading Interpolations: v0.5.0 => v0.6.0
INFO: Upgrading Iterators: v0.3.0 => v0.3.1
INFO: Upgrading StaticArrays: v0.4.0 => v0.5.0
WARNING: The following packages have been updated but were already imported:
- Iterators
Restart Julia to use the updated versions.
```
So I guess whenever the Iterators.jl package is updated, a warning is issued because the Base Iterators module is available. It would be great if this could not happen.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #21578

Marking as WIP until I can figure out how best to test this. Suggestions welcome.

Edit: Tested. 😎

### CODE REVIEW

**Comment by ararslan** [comment]
If ever I can figure out how to test this, should the change be backported to 0.6?

**Comment by helgee** [comment]
Just for my understanding: What is the rationale for this change? And related, what is wrong with the [original test](https://github.com/JuliaLang/julia/blob/master/test/pkg.jl#L506)?

**Review by vchuravy — APPROVED** [review]
This is a notoriously difficult to test edge case since you need a binding in Base that is latent. The change per se is correct. But I haven't thought up a way of properly testing it besides doing `Pkg.add("Iterators")`....

**Comment by tkelman** [comment]
we can do `Pkg.add("Iterators")` during the pkg test and test for other things, if that's the easiest way

**Comment by ararslan** [comment]
The problem is that just adding Iterators doesn't trigger it—Iterators has to be updated for it to happen.

**Comment by tkelman** [comment]
there is a part of the pkg test that does an update between 2 known points in metadata history, was there an Iterators update between them?

**Comment by ararslan** [comment]
Got it tested! 🎉

**Comment by tkelman** [comment]
and that would fail without the change to base?

**Comment by ararslan** [comment]
Yep, tried it with and without.

**Comment by vtjnash** [comment]
This appears to have broken the coverage buildbot (http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64/builds/357/steps/Run%20inlined%20tests/logs/stdio)

**Pull request merged**
