### PR TITLE
copy effects key to `Base.infer_effects`

### PR DESCRIPTION
**Pull request by MasonProtter**
Copied from the docstring of `Core.Compiler.Effects`, this makes it easier to figure out what the output of `Base.infer_effects` is actually telling you.

### CODE REVIEW

**Review by topolarity — APPROVED** [review]
It's embarrassing to admit how many times I've had to hunt for this

**Comment by giordano** [comment]
I'm not against having this information in this docstring, but I'm worried about the duplication and the possibility of this information to get out-of-sync, at some point someone will miss to update it everywhere, since it's highly non-obvious it's repeated in multiple places.

**Comment by Keno** [comment]
Yeah, let's only have one place in the source code and paste it into the places that need it. I don't know if we have that feature in the Base doc system, but if not I guess we can hack something

**Comment by MasonProtter** [comment]
Okay, I've de-duplicated the information into a global variable and then interpolated it into the two respective docstrings. There's probably a more elegant way to do this but that's what I came up with.

**Review by Keno — APPROVED** [review]

**Pull request merged**
