### PR TITLE
Preserve ScalarEvolution/MemorySSA in JuliaLICM

### PR DESCRIPTION
**Pull request by pchintalapudi**
In LLVM 14 LICM requires MSSA to be present in NewPM, so we must preserve it here. Also, NewPM requires that ScalarEvolution be preserved during all loop passes, so handle that case too.

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]
Looks good to me, but I would appreciate a second set of eyes.

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by pchintalapudi** [comment]
As currently written, we don't preserve the passes with the old pass manager (so as to not add additional analysis requirements), so there shouldn't be any discernible change here.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45497#issuecomment-1140539588) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/6fea555_vs_6f8860c/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45497#issuecomment-1140539562) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/378725c_vs_6f8860c/report.html).

**Review by maleadt — APPROVED** [review]
I'm not really familiar with this code, but superficially LGTM.

**Pull request merged**
