### PR TITLE
Use where syntax in sparsematrix.jl

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by jebej** [comment]
I'm not sure if you where trying to do them all, but there are a couple more.

**Comment by musm** [comment]
Please feel free to open or push to this PR more changes,  I don't think I have time to change them all

**Comment by jebej** [comment]
I'm unfortunately not a git pro, so I'll leave it up to someone else...

**Comment by musm** [comment]
you can always just open a new PR

**Pull request merged**
