### PR TITLE
Move rectuangular full packed matrix support from base to LinearAlgebra.jl

### LINKED ISSUE #208: LAPACK.trttf! and LAPACK.tfttr! do not mutate arguments
AFAICS these two functions copy to freshly allocated storage so the names should not have a trailing !

### LINKED ISSUE #11072: LAPACK.trttf! and LAPACK.tfttr! do not mutate arguments
AFAICS these two functions copy to freshly allocated storage so the names should not have a trailing !

### PR DESCRIPTION
**Pull request by andreasnoack**
The methods have never been exported or maintained so it should be safe to move them out of base. This also fixes JuliaLang/LinearAlgebra.jl#208.

### CODE REVIEW

**Comment by tkelman** [comment]
ref https://github.com/andreasnoack/LinearAlgebra.jl/commit/946cb42b196647ebf67f4aca39ac58f183d1f10a - looks like these weren't tested here. If any registered packages are using these, it would be good to register LinearAlgebra and add this to Compat.

**Comment by kshyatt** [comment]
:+1: This will dramatically improve `linalg/lapack.jl`'s coverage stats and just be better.

**Comment by andreasnoack** [comment]
@tkelman The package will be registered when I've written some documentation and tests. I'd be very surprised if these functions are used in any package so I'll go ahead a merge this.

**Comment by tkelman** [comment]
> I'd be very surprised if these functions are used in any package

A grep can answer that question. @dmbates had asked about them, and it's entirely possible he's not the only person trying to do more exotic operations.

**Comment by kshyatt** [comment]
`lapack.jl` now has 93% test coverage. https://coveralls.io/builds/3047587

**Comment by StefanKarpinski** [comment]
I find the coveralls UI completely confusing. I have basically no idea how to, e.g., find what the percentage coverage for that file is from that link.

**Comment by StefanKarpinski** [comment]
When I did navigate to it (use the search thing), I see 89.02% coverage. Are we looking at the same thing?

**Comment by kshyatt** [comment]
I swear it was 93% a few minutes ago. Oh well. 89% is still really good.

**Comment by StefanKarpinski** [comment]
Yes, it's great. This is really getting there.

**Comment by kshyatt** [comment]
>I find the coveralls UI completely confusing. I have basically no idea how to, e.g., find what the percentage coverage for that file is from that link.

Is my guide at #11885 not clear enough? Could you suggest improvements?

**Comment by StefanKarpinski** [comment]
No, your guide is great. I'm really just venting that their UI is lousy.

**Comment by kshyatt** [comment]
I think it's really cool that I have to click like 10 different things to get the information I want.

**Pull request merged**
