### PR TITLE
Xcode support? 

### PR DESCRIPTION
**Pull request by Jackdopp**
It would be really nice if Xcode support was added in 0.4.x

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I don't know what's going on here.

**Comment by pao** [comment]
@Jackdopp So strange things are going on here, this became a pull request with random stuff in it that obviously isn't ready, so Stefan closed this before any damage could be done.

While editor support (which is what I think you're asking for?) is often worked on by core developers, and some editor support (such as Emacs) is maintained in the main repository, let's start by punting this over to the mailing list https://groups.google.com/forum/#!forum/julia-users and go from there. In either case, this isn't something that's going to be a priority for 0.4, though anyone is welcome to work on it, whether we opt to maintain it in this repository or as a separate one (like our Atom editor support).

I'm assuming this is for the editor because Xcode tools are already required to compile on OS X, according to the README.

**Comment by ivarne** [comment]
Just pinging @amitmurthy in case he didn't realize that this PR exists for his `amitm/libuv_thread_exec` branch.

**Comment by amitmurthy** [comment]
Since we haven't heard back, maybe it is a bot fooling around?

**Comment by johnmyleswhite** [comment]
I would bet it's a bot. This is the only other GitHub activity ever: https://github.com/Jackdopp/NEW-GO-PROGRAMERS

**Pull request closed without merging**
