### PR TITLE
store more unnecessary information in CodeInfo

### LINKED ISSUE #29287: code_warntype output has become unreadable
I just noticed in my class yesterday that `@code_warntype` has become nearly unreadable in 1.0.  Consider the function
```jl
mysum(a) = let s=0; for x in a; s+=x; end; s; end
```
which is type-unstable for summing a floating-point array.  In Julia 0.6, `@code_warntype mysum([1.0])` outputs:
```jl
Variables:
  #self# <optimized out>
  a::Array{Float64,1}
  x::Float64
  #temp#@_4::Int64
  s::Union{Float64, Int64}
  #temp#@_6::Core.MethodInstance
  #temp#@_7::Float64

Body:
  begin 
      s::Union{Float64, Int64} = 0 # line 1:
      #temp#@_4::Int64 = 1
      4: 
      unless (Base.not_int)((#temp#@_4::Int64 === (Base.add_int)((Base.arraylen)(a::Array{Float64,1})::Int64, 1)::Int64)::Bool)::Bool goto 29
      SSAValue(2) = (Base.arrayref)(a::Array{Float64,1}, #temp#@_4::Int64)::Float64
      SSAValue(3) = (Base.add_int)(#temp#@_4::Int64, 1)::Int64
      x::Float64 = SSAValue(2)
      #temp#@_4::Int64 = SSAValue(3) # line 1:
      unless (s::Union{Float64, Int64} isa Int64)::Bool goto 14
      #temp#@_6::Core.MethodInstance = MethodInstance for +(::Int64, ::Float64)
      goto 23
      14: 
      unless (s::Union{Float64, Int64} isa Float64)::Bool goto 18
      #temp#@_6::Core.MethodInstance = MethodInstance for +(::Float64, ::Float64)
      goto 23
      18: 
      goto 20
      20: 
      #temp#@_7::Float64 = (s::Union{Float64, Int64} + x::Float64)::Float64
      goto 25
      23: 
      #temp#@_7::Float64 = $(Expr(:invoke, :(#temp#@_6), :(Main.+), :(s), :(x)))
      25: 
      s::Union{Float64, Int64} = #temp#@_7::Float64
      27: 
      goto 4
      29:  # line 1:
      return s::Union{Float64, Int64}
  end::Union{Float64, Int64}
```
which clearly indicates at the top that the `s` variable is type-unstable.

In contrast, in Julia 1.0 we get:
```jl
Body::Union{Float64, Int64}
1 1 ── %1  = (Base.arraylen)(a)::Int64                  │╻╷╷   iterate
  │    %2  = (Base.sle_int)(0, %1)::Bool                ││╻╷    iterate
  │    %3  = (Base.bitcast)(UInt64, %1)::UInt64         │││╻     <
  │    %4  = (Base.ult_int)(0x0000000000000000, %3)::Bool│││╻     <
  │    %5  = (Base.and_int)(%2, %4)::Bool               ││││╻     &
  └───       goto #3 if not %5                          │││   
  2 ── %7  = (Base.arrayref)(false, a, 1)::Float64      │││╻     getindex
  └───       goto #4                                    │││   
  3 ──       goto #4                                    │││   
  4 ┄─ %10 = φ (#2 => false, #3 => true)::Bool          ││    
  │    %11 = φ (#2 => %7)::Float64                      ││    
  │    %12 = φ (#2 => 2)::Int64                         ││    
  └───       goto #5                                    ││    
  5 ── %14 = (Base.not_int)(%10)::Bool                  │     
  └───       goto #16 if not %14                        │     
  6 ┄─ %16 = φ (#5 => %11, #15 => %46)::Float64         │     
  │    %17 = φ (#5 => %12, #15 => %47)::Int64           │     
  │    %18 = φ (#5 => 0, #15 => %32)::Union{Float64, Int64}   
  │    %19 = (isa)(%18, Float64)::Bool                  │     
  └───       goto #8 if not %19                         │     
  7 ── %21 = π (%18, Float64)                           │     
  │    %22 = (Base.add_float)(%21, %16)::Float64        │╻     +
  └───       goto #11                                   │     
  8 ── %24 = (isa)(%18, Int64)::Bool                    │     
  └───       goto #10 if not %24                        │     
  9 ── %26 = π (%18, Int64)                             │     
  │    %27 = (Base.sitofp)(Float64, %26)::Float64       ││╻╷╷╷  promote
  │    %28 = (Base.add_float)(%27, %16)::Float64        ││╻     +
  └───       goto #11                                   │     
  10 ─       (Core.throw)(ErrorException("fatal error in type inference (type bound)"))
  └───       $(Expr(:unreachable))                      │     
  11 ┄ %32 = φ (#7 => %22, #9 => %28)::Float64          │     
  │    %33 = (Base.bitcast)(UInt64, %17)::UInt64        ││╻     rem
  │    %34 = π (0x0000000000000001, UInt64)             ││╻     -
  │    %35 = (Base.sub_int)(%33, %34)::UInt64           │││╻     -
  │    %36 = (Base.arraylen)(a)::Int64                  ││╻     length
  │    %37 = (Base.sle_int)(0, %36)::Bool               │││╻╷    >=
  │    %38 = (Base.bitcast)(UInt64, %36)::UInt64        ││││╻     reinterpret
  │    %39 = (Base.ult_int)(%35, %38)::Bool             │││╻     <
  │    %40 = (Base.and_int)(%37, %39)::Bool             │││╻     &
  └───       goto #13 if not %40                        ││    
  12 ─ %42 = (Base.arrayref)(false, a, %17)::Float64    ││╻     getindex
  │    %43 = (Base.add_int)(%17, 1)::Int64              ││╻     +
  └───       goto #14                                   ││    
  13 ─       goto #14                                   ││    
  14 ┄ %46 = φ (#12 => %42)::Float64                    │     
  │    %47 = φ (#12 => %43)::Int64                      │     
  │    %48 = φ (#12 => false, #13 => true)::Bool        │     
  │    %49 = (Base.not_int)(%48)::Bool                  │     
  └───       goto #16 if not %49                        │     
  15 ─       goto #6                                    │     
  16 ─ %52 = φ (#14 => %32, #5 => 0)::Union{Float64, Int64}   
  └───       return %52                     
```
in which the type-instability is attached to a temporary variable `φ`.  Basically, the output contains no useful information for a mere mortal programmer except for the first line `Body::Union{Float64, Int64}`, which indicates that there is a type instability but not where it comes from.

### PR DESCRIPTION
**Pull request by vtjnash**
We've previously been pretty careful to only have useful information in CodeInfo. That's probably not really necessary though, since having the ability to expose extra information (slottypes, rettype, parent, min/max world) isn't too harmful, and is occasionally useful. Here we use it to close #29287.

### CODE REVIEW

**Comment by timholy** [comment]
Demo of `@code_warntype` output?

**Comment by vtjnash** [comment]
```
mysum(a) = let s=0; for x in a; s+=x; end; s; end
```
image

**Comment by vtjnash** [comment]
GTG? It's mostly NFC (since these field are essentially being added with an explicit "no warranty" clause)

Though to be clear, this isn't entirely NFC since it is changing the default of `code_warntype` to optimize=false (while adding the ability to change it), as I proposed in #29287. I think it's worthwhile trying this switch as an experiment (since it allows us to print variable names and is a bit closer thus to the original program), but have no strong opinion that it needs to stay that way if that turns out to be worse.

**Comment by JeffBezanson** [comment]
I think that's a reasonable change.

**Pull request merged**
