### PR TITLE
RFC: Rename HISTORY.md to ChangeLog.md

### PR DESCRIPTION
**Pull request by yuyichao**
So that it won't conflict with auto-completion of `HEAD`. We already have another file starting with `C` (`CONTRIBUTE.md`) and neither of the two files are frequently edited.

`ChangeLog` seems to be the common spelling even in projects that use `README` but I'm fine with `CHANGELOG` (or any other spellings) too if anyone feels strongly about it.

[ci skip]

### CODE REVIEW

**Comment by tkelman** [comment]
tab completion is a lousy reason to name files. a changelog in virtually any other project would include changes for the latest version along with older versions, this would just be confusing to have only old stuff in a changelog file. https://github.com/JuliaLang/julia/issues/15241

**Comment by vtjnash** [comment]
You could also just use my strategy of renaming `HEAD` instead to not need tab-completion.
for example: `ln HEAD .git/head`

**Comment by yuyichao** [comment]
> tab completion is a lousy reason to name files.

Sure, but why not if it doesn't cause other trouble either way.

> a changelog in virtually any other project would include changes for the latest version along with older versions, this would just be confusing to have only old stuff in a changelog file

Suggestions welcome, I'm also totally fine to rename `NEWS.md` to something else. Or having `{ChangeLog,NEWS}.md{,.0.4}`

**Comment by yuyichao** [comment]
> You could also just use my strategy of renaming HEAD instead to not need tab-completion.
for example: `ln -s HEAD .git/head`

Other than that neither bash nor zsh completes it, it needs to be done for each work dir and makes it harder to work with other projects.

**Comment by vtjnash** [comment]
I type `head` faster than `H\tab`, but you could also give it a shorter name, like `H` and then `H\tab` will work :P. True that it's one more thing to do after `git clone julia`

**Comment by StefanKarpinski** [comment]
I have to say I don't think this is a good reason to rename this file.

**Comment by JeffBezanson** [comment]
I don't want to rename it either. Strikes me as random churn.

**Pull request closed without merging**
