### PR TITLE
Fix zero elements for block-matrix kron involving Diagonal

### PR DESCRIPTION
**Pull request by jishnub**
Currently, it's assumed that the zero element is identical for the matrix, but this is not necessary if the elements are matrices themselves and have different sizes. This PR ensures that `kron` for a `Diagonal` has the correct zero elements.
Current:
```julia
julia> D = Diagonal(1:2)
2×2 Diagonal{Int64, UnitRange{Int64}}:
 1  ⋅
 ⋅  2

julia> B = reshape([ones(2,2), ones(3,2), ones(2,3), ones(3,3)], 2, 2);

julia> size.(kron(D, B))
4×4 Matrix{Tuple{Int64, Int64}}:
 (2, 2)  (2, 3)  (2, 2)  (2, 2)
 (3, 2)  (3, 3)  (2, 2)  (2, 2)
 (2, 2)  (2, 2)  (2, 2)  (2, 3)
 (2, 2)  (2, 2)  (3, 2)  (3, 3)
``` 
This PR
```julia
julia> size.(kron(D, B))
4×4 Matrix{Tuple{Int64, Int64}}:
 (2, 2)  (2, 3)  (2, 2)  (2, 3)
 (3, 2)  (3, 3)  (3, 2)  (3, 3)
 (2, 2)  (2, 3)  (2, 2)  (2, 3)
 (3, 2)  (3, 3)  (3, 2)  (3, 3)
```
Note the differences e.g. in the `CartesianIndex(4,1)`, `CartesianIndex(3,2)` and `CartesianIndex(3,3)` elements.

### CODE REVIEW

**Comment by jishnub** [comment]
Bump

**Comment by Krastanov** [comment]
FYI, this broke kron products between `LinearAlgebra.I` and certain Hecke/Oscar/Nemo objects.

https://github.com/QuantumSavory/QuantumClifford.jl/pull/393/commits/6412e28c2135e4b10f22c88c4dc22d67d1477dfa

Found by @royess 

On our end, we have merged and released our workaround so we are not affected anymore, but just wanted to flag this as a potential issue for others.

**Comment by jishnub** [comment]
Hi, could you elaborate on what the breakage is due to, or perhaps provide an MWE? It might make sense to revert the backport to v1.11.

**Comment by royess** [comment]
A MWE would be:

```julia
using Hecke
import LinearAlgebra

GA = group_algebra(GF(2), abelian_group(10))
x = gens(GA)[]
A = [x GA(1); x GA(0)]
B = LinearAlgebra.I(10)
@show kron(B, A)
```

In v1.11.0, it works normally. In v1.11.1, it results in a segmentation fault.

**Pull request merged**
