### PR TITLE
Backports for Julia 1.8.3

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #45552 
- [x] #45751 
- [x] #46882 
- [x] #46897 
- [x] #46914 
- [x] #46906 
- [x] #46925 
- [x] #46759 
- [x] #46997 
- [x] #47008 
- [x] #45646 
- [x] #46806 
- [x] #47114 
- [x] #47058 
- [x] #47091 
- [x] #47076 
- [x] #47187 
- [x] #47203 
- [x] #47213 
- [x] #46787 
- [x] #46683 
- [x] #46373 
- [x] #47311 
- [x] #47299 
- [x] #47204 
- [x] #46938 
- [x] #46935 
- [x] #46980 
- [x] #47336 
- [x] #46998 
- [x] #47438

Need manual backport:

Contains multiple commits, manual intervention needed:
- [ ] #46819 
- [ ] #46921 

Non-merged PRs with backport label:
- [ ] #47229 
- [ ] #46844 
- [ ] #46801 
- [ ] #45582 <!-- [CompilerSupportLibraries_jll] Upgrade to libraries from GCC 12

### CODE REVIEW

**Comment by maleadt** [comment]
Added the manual back-port of https://github.com/JuliaLang/julia/pull/46373

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.8")`

**Comment by DilumAluthge** [comment]
The failure in `buildkite/julia-master-scheduled` will be fixed by https://github.com/JuliaLang/julia/pull/47361

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/46984#issuecomment-1294539503) failed.

**Comment by KristofferC** [comment]
@vtjnash , can you upload log?

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46984#issuecomment-1294535882) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/47ef407_vs_97ccb97/report.html).

**Comment by KristofferC** [comment]
Wow...

**Comment by PallHaraldsson** [comment]
I think the test failure for Evolutionary.jl might be real, then a worry. It doesn't find the correct minimum (and uses StableRNG, so seemingly meant to be deterministic). But it uses Threads, and given it's genetic search, so I'm thinking could it fail occationally randomly? I tested locally and no failures, then its master and 4 failures...

**Comment by PallHaraldsson** [comment]
SugarKelp might have a performance regression, taking much longer. Might this be related to it:

```
[ Info: These tests check if the code has been broken but does not thoroughly check if it produces correct results (for now at least). They are also so monalithic you can't actually tell which bit you've broken.
[ Info: At level 1
┌ Warning: The special case of bisection over BigFloat with zero tolerance using `A42` is deprecated. Now bisection is used with non-zero tolerances.
│   caller = p(temp::Float64, irr::Float64, params::NamedTuple{(:A_0, :α, :C_min, :C_struct, :γ, :ϵ, :I_sat, :J_max, :K_A, :K_DW, :K_C, :K_N, :N_min, :N_max, :m_2, :m_1, :μ_max, :N_struct, :P_1, :P_2, :a_1, :a_2, :R_1, :R_2, :T_R1, :T_R2, :T_P1, :T_P2, :T_AP, :T_PL, :T_PH, :T_APH, :T_APL, :T_AR, :U_0p65, :K_X, :R_A, :R_B), Tuple{Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int64, Int64, Int64, Int64, Float64, Int64, Int64, Float64, Float64, Float64, Float64, Int64, Float64, Float64}}) at SugarKelp.jl:132
└ @ SugarKelp ~/.julia/packages/SugarKelp/FymmY/src/SugarKelp.jl:132
┌ Warning: BisectionExact is deprecated; use Bisection
│   caller = #find_zero#27 at bisection.jl:191 [inlined]
└ @ Core ~/.julia/packages/Roots/6PvI4/src/Bracketing/bisection.jl:191
```

**Comment by PallHaraldsson** [comment]
Why "wow"? Because mostly ok, or because "3167 failed", since I now realized that's with or without 1.8.3 PR, so not a worry? Or that is, a worry, just unrelated.

**Comment by KristofferC** [comment]
Wow because so few regressions :)

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8df0552_vs_97ccb97/report.md 👍

**Comment by DilumAluthge** [comment]
A quick note regarding the two pending (yellow) statuses of the form `buildbot/tester_win*`.

Windows has been migrated to Buildkite. To see the results of Windows CI, please click on the "Details" link next to the `buildkite/julia-release-1.8` commit status.

**Comment by PallHaraldsson** [comment]
I noticed in the logs:
```
Downloading Julia 1.6 for arch x86_64
Julia Version 1.6.7
```

Should CI be downloading 1.8.x or 1.9?

**Comment by KristofferC** [comment]
It's just using Julia 1.6 to do some "bootstrapping" to setup the environment for the CI to run. So it doesn't really matter what version that is.

**Comment by KristofferC** [comment]
The error in Evolutionary seems to come down to a change in the order in which things are put into a dictionary and the tests seem to rely on this being constant. Also, the tests for Evolutionary pass on this branch using the master branch of the package. So it doesn't seem anything is broken.

SugarKelp passed locally so probably just some slowness with the PkgEval setup which is expected.

**Comment by KristofferC** [comment]
@DilumAluthge, are the windows tests expected to pass on Buildkite?

**Comment by DilumAluthge** [comment]
If I recall correctly, the failure in LinearAlgebra/special on i686 was a known failure. But apart from that, I would have expected all tests to pass on Windows on Buildkite.

@staticfloat Have we forgotten to backport something?

Worst case we can turn the Windows Buildbots back on temporarily, but it would be ideal if we could use Buildkite.

**Comment by staticfloat** [comment]
@KristofferC I have backported the missing piece for #44444 and merged it in.  I also identified (with Jameson's help) the missing piece in Pkg that is causing the timeout failures on Windows, and I've submitted a [backport for Pkg's `release-1.8` branch](https://github.com/JuliaLang/Pkg.jl/pull/3255).  Once that is merged, we should bump Pkg to include that here, and that will hopefully get us a green flush on Windows.

**Comment by KristofferC** [comment]
Great!
Regarding https://github.com/JuliaLang/julia/pull/46984/commits/cb1e40b695b246359d88c75a683a1180dc9dcced, it looks like it just reverts the partial revert I just did of that PR. Before, it got an EBUSY error cleaning up the file there.

**Comment by quinnj** [comment]
Can we include https://github.com/JuliaLang/julia/pull/47419? I think it should backport pretty easily. (happy to push it here if that doesn't mess up some regular flow)

**Pull request merged**
