### PR TITLE
Add method to allow rationalize to return Rational

### PR DESCRIPTION
**Pull request by jlazar17**
Address issue #43369

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Comment by Moelf** [comment]
https://github.com/JuliaLang/julia/blob/e31aec422689173b1bf650318a2d71a92ebd0813/test/rational.jl#L35

sprinkle one test here maybe, just to get the line covered...

**Comment by mcabbott** [comment]
Should `rationalize(33//100, tol=0.1)` work, and should it return `1//3`?

**Comment by oscardssmith** [comment]
yes, but that can be a followup PR.

**Comment by tantheta01** [comment]
> Should `rationalize(33//100, tol=0.1)` work, and should it return `1//3`?

Can I work on this?

**Comment by ParadaCarleton** [comment]
> > Should `rationalize(33//100, tol=0.1)` work, and should it return `1//3`?
> 
> Can I work on this?

The answer to that question is always yes!

**Comment by tantheta01** [comment]
Should `rationalize(1)` work and should it return `1//1` ?

**Comment by oscardssmith** [comment]
it seems reasonable that `rational(::Int)` would work (and return `x//1`)

**Comment by mcabbott** [comment]
The next question is whether it should agree with `rationalize(1234.0, tol=100) === 1134//1`, and what that is thinking...

**Comment by oscardssmith** [comment]
I think it should. `rationalize` isn't `round`, and for rationals, there isn't ever a reason (that I can think of) to have an approximation worse than `x//1`.

**Comment by Moelf** [comment]
Tolerance is tolerance, if users want to tolerate 100, whatever, anything within 100 fits the bill

**Comment by mcabbott** [comment]
Yes I'm not claiming the existing behaviour is a bug. And while I haven't looked, I can picture how an algorithm intended for `x<1` might pick the lowest legal result for `x>1`.

It just seems worth a little though about whether `x::Int` (or `x::Rational`) ought to give the same result as `float(x)`, among the legal ones.

**Comment by fingolfin** [comment]
Thank your contribution, sorry for letting it sit for so long. In the meantime multiple PRs were opened to address this very same issue, and we ended up merging PR #43427.

**Pull request closed without merging**
