### PR TITLE
Fix generic mul accidental type promotion Int32 -> Int64

### LINKED ISSUE #704: Generic 5 arg mul! promotes Int32 to Int64
```
using LinearAlgebra
julia> mul!(rand(Int32, 4), rand(Int32, 4, 4), rand(Int32, 4), Int32(4), Int32(5))
ERROR: InexactError: trunc(Int32, -138749043280184131)
```

Like Float32 shoudn't use Float64 arithmetic internally, Int32 should just compute in Int64 throughout as well I would assume.

### LINKED ISSUE #35163: Generic 5 arg mul! promotes Int32 to Int64
```
using LinearAlgebra
julia> mul!(rand(Int32, 4), rand(Int32, 4, 4), rand(Int32, 4), Int32(4), Int32(5))
ERROR: InexactError: trunc(Int32, -138749043280184131)
```

Like Float32 shoudn't use Float64 arithmetic internally, Int32 should just compute in Int64 throughout as well I would assume.

### PR DESCRIPTION
**Pull request by haampie**
Fixes JuliaLang/LinearAlgebra.jl#704.

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]
LGTM. Did you check whether there are more unintended `0`s (instead of `zero`s) in similar contexts?

**Comment by haampie** [comment]
matmul.jl is clear of `0` and `1` literals in computations as far as I can see.

**Comment by haampie** [comment]
:confused: the current `generic_mul!` is really broken it seems :(

Type deduction for the output vector is way too generic:

```julia
julia> Real[1 2] * Real[1.5; 2.0]
1-element Array{Any,1}:
 5.5
```
vs
```julia
julia> Real[1 2] .* Real[1.5; 2.0]
2×2 Array{Float64,2}:
 1.5  3.0
 2.0  4.0
```

The test failure is because I'm using `zero(R)` where `R === Any`. But there's 3 other places where this is used at the moment that apparently aren't covered by tests.

**Comment by KristofferC** [comment]
> Not sure what to replace zero(R) with at the moment.

Does `false` work?

**Comment by dkarrasch** [comment]
I'll rerun CI (the only failure seems unrelated) and merge if everything runs smoothly.

**Pull request merged**
