### PR TITLE
Bump dependencies to fix ppc64le page size issues

### PR DESCRIPTION
**Pull request by vchuravy**
Redo of #34082 

The download of SuiteSparse started failing shortly after the original PR was merged (https://github.com/JuliaLang/julia/pull/34082#issuecomment-565837625) and thus was subsequently reverted in #34108. In short Suitesparse is now build through Yggdrasil and tags are only "final" after the corresponding merge of the JLL package into the General registry. I didn't check that the General PR was merged, before finalizing #34082, thus allowing for a subsequent change to SuiteSparse to invalidate the checksums.

### CODE REVIEW

**Comment by ararslan** [comment]
426 files modified in 1 commit. New record?

**Comment by StefanKarpinski** [comment]
I didn't even realize we had that many checksum files. This project is very secure.

**Review by staticfloat — APPROVED** [review]

**Comment by vchuravy** [comment]
This is completely ruining my lines_added vs lines_deleted ratio.

**Comment by KristofferC** [comment]
This PR was `+200 −248` which should be a boost to the ratio, no?

**Pull request merged**
