### PR TITLE
REPL: disable auto-indent when code is likely being pasted (fix #25186)

### LINKED ISSUE #25186: Pasting in multiline code terminal regression
On 0.7 copy pasting the following 
```julia
mutable struct Test
    a
    b
    c::String
end
```

Results in 
image

compare to 0.6
image

This is especially/annoying/noticeable for larger blocks

### PR DESCRIPTION
**Pull request by rfourquet**
On some Windows terminals, pasting is not recognized as such.
This happens also with tmux' builtin paste.
In those cases, auto-indent is better disabled, as we want
to preserve the original indentation of the code being pasted.

This fix is quite a hack, but seems to work: using time(), if
the next character after a newline is being inserted very fast,
assume this was with paste, and cancel the insertion of the
spaces done by auto-indent.

I couldn't insert two characters in a raw within less than
about 0.03 or 0.02 seconds, so the threshold for "very fast"
is set to 0.005, but this is an option which can changed.

### CODE REVIEW

**Comment by KristofferC** [comment]
Clever workaround!

**Comment by rfourquet** [comment]
The travis failure seems unrelated, but circleci "failure" is very interesting: click on "details" and it shows a page indicating success!!

**Comment by rfourquet** [comment]
Bump, can someone experiencing the issue try out this branch? @musm

**Comment by oheil** [comment]
It works for small code snippets but not for large.
see https://discourse.julialang.org/t/repl-copy-paste-and-auto-indent-in-julia-0-7/10230

**Comment by oheil** [comment]
Still no success:
https://discourse.julialang.org/t/repl-copy-paste-and-auto-indent-in-julia-0-7/10230

**Comment by rfourquet** [comment]
Big thanks to @oheil who spent many hours testing this feature (see the linked discourse thread), we now believe that it works reasonably reliably. I plan to merge in a couple of days.

**Comment by oheil** [comment]
More issue:
If real \t are pasted into REPL instead of space indentation. See
https://discourse.julialang.org/t/repl-copy-paste-and-auto-indent-in-julia-0-7/10230

**Comment by oheil** [comment]
Another solution based on yours:
https://discourse.julialang.org/t/repl-copy-paste-and-auto-indent-in-julia-0-7/10230

It prevents auto-indent before it happens.

Next time I would clone projects and do PRs, but today its late and tomorrow I am offline, So it would take until tuesday.

**Comment by oheil** [comment]
Still missed a special case. Solution is coming in. See discussion.

**Comment by oheil** [comment]
@rfourquet , are you considerung my code proposal? Or is something wrong with it? Heard nothing for a while now. Or did I propose it the wrong way? Somehow offending? If this is the case, I didn't meant it.

**Comment by rfourquet** [comment]
@oheil no no, nothing was wrong with how you did things, sorry you could think that. I just got quite sidetracked, and lost track of Julia development. Will try to come back to this soon.

**Comment by oheil** [comment]
There are currently 2 solutions available. This one and another one which builds on top this. I am hesitating to create my own PR because I do not know, why this PR is not accepted. 

If this PR has something which prevents it to be accepted, it should be closed, ideally with a comment on why, and I would open a new PR.

**Comment by KristofferC** [comment]
This works well from my testing, will merge in a couple of days unless someone objects.

**Comment by oheil** [comment]
I would prefer to see my upgrade on @rfourquet solutions is considered, as I think it is more reliable, as autoindent needs to be reversed. autoindent is not applied when not appropriate.
But @rfourquet has currently  not time to look into it.

I don't object to merge this one. Is this the proper way to go: wait until this one is merged, than open a new issue with the issues and propose a new PR at last?

**Comment by KristofferC** [comment]
You can make a new PR that adds commits on top of this one. This one doesn't have to be merged. Right now, this is the PR that exists and it seems to fixes things so merging it seems to be an improvement over the status quo. If there is an even better implementation, having that as a PR would be good because then it is easy to try out. Implementations in discourse are not so easy to try out.

**Comment by oheil** [comment]
Ok, thanks for your encouragement, I will do a PR as soon as possible (view days).

**Comment by oheil** [comment]
A view days have been a few hours
https://github.com/JuliaLang/julia/pull/30755

**Pull request closed without merging**
