### PR TITLE
Optimize tridiagonal matrix solver

### PR DESCRIPTION
**Pull request by maleadt**
Had some code laying around that I needed for verifying a GPU implementation, and it seems to outperform our current generic fallback:

```julia
julia> function benchmark(;N=256, T=Float32)
           t = Tridiagonal(rand(T, N, N))
           rhs = rand(T, N)

           suite = BenchmarkGroup()
           suite["Base"] = @benchmarkable invoke(\, Tuple{AbstractMatrix, AbstractVector}, $t, $rhs)
           suite["new"] = @benchmarkable $t \ $rhs

           warmup(suite)
           results = run(suite)
           judge(median(results["new"]), median(results["Base"]))
       end

julia> benchmark(N=4)
  "Base" => Trial(219.000 ns)
  "new" => Trial(91.000 ns)

  time:   -58.44% => improvement (5.00% tolerance)
  memory: -73.33% => improvement (1.00% tolerance)


julia> benchmark(N=64)
  "Base" => Trial(1.186 μs)
  "new" => Trial(661.000 ns)

  time:   -49.93% => improvement (5.00% tolerance)
  memory: -72.37% => improvement (1.00% tolerance)


julia> benchmark(N=1024)
  "Base" => Trial(18.241 μs)
  "new" => Trial(10.111 μs)

  time:   -47.03% => improvement (5.00% tolerance)
  memory: -71.43% => improvement (1.00% tolerance)
```

I'm not well versed in linalg so probably making some silly mistakes here.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do we have an existing test case that checks this?

**Comment by maleadt** [comment]
Yeah: https://github.com/JuliaLang/julia/blob/24efaa4f38ca50b902b28c2389b14ef197fb9214/stdlib/LinearAlgebra/test/tridiag.jl#L369-L379

**Comment by ViralBShah** [comment]
We can merge after @andreasnoack reviews.

**Comment by ViralBShah** [comment]
Bump @andreasnoack

**Comment by andreasnoack** [comment]
I suspect at least part of the reason for the time difference is the lack of pivoting in the version here. It makes it unstable for some matrices. However, the current implementation without pivoting isn't faster than the one with pivoting. I'll have to take a closer look.
```julia
julia> function benchmark(;N=256, T=Float32)
                  t = Tridiagonal(rand(T, N, N))
                  rhs = rand(T, N)

                  suite = BenchmarkGroup()
                  suite["Base"] = @benchmarkable invoke(\, Tuple{AbstractMatrix, AbstractVector}, $t, $rhs)
                  suite["BaseNoPivot"] = @benchmarkable lu($t, Val(false)) \ $rhs
                  suite["new"] = @benchmarkable $t \ $rhs

                  warmup(suite)
                  results = run(suite)
                  display(judge(median(results["new"]), median(results["Base"])))
                  display(judge(median(results["Base"]), median(results["BaseNoPivot"])))
              end
benchmark (generic function with 1 method)

julia> benchmark(N=64)
(1/3) benchmarking "Base"...
done (took 0.062119647 seconds)
(2/3) benchmarking "new"...
done (took 0.060346363 seconds)
(3/3) benchmarking "BaseNoPivot"...
done (took 0.070538019 seconds)
BenchmarkTools.TrialJudgement:
  time:   -47.63% => improvement (5.00% tolerance)
  memory: -72.37% => improvement (1.00% tolerance)

BenchmarkTools.TrialJudgement:
  time:   -6.24% => improvement (5.00% tolerance)
  memory: +0.00% => invariant (1.00% tolerance)
```

**Comment by ViralBShah** [comment]
@dkarrasch Any thoughts here?

**Review by andreasnoack — COMMENTED** [review]
It would be fine have this implementation available but I don't think it should be the default `\` because it isn't generally stable. Maybe we could call the function `thomas` instead of overloading `\`.

**Pull request closed without merging**
