### PR TITLE
[release-1.0] Set VERSION to 1.0.2

### PR DESCRIPTION
**Pull request by ararslan**
Should be merged after the testing period is over, right before the release.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Merge?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/29952

**Comment by KristofferC** [comment]
Should be good to go now.

**Review by fredrikekre — APPROVED** [review]

**Comment by ararslan** [comment]
Thanks everyone!

**Pull request merged**
