### PR TITLE
Bump Pkg to latest master (8e236a7f993f1e732ffd0ab5c15736b2594e4109)

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request updates Pkg to the latest commit.

@staticfloat Can you check that I did this correctly?

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]

**Comment by KristofferC** [comment]
Jameson wanted a list of commits between the previous Pkg commit and the updated one when we did this. I think git can generate such a list pretty easily.

**Comment by DilumAluthge** [comment]
> Jameson wanted a list of commits between the previous Pkg commit and the updated one when we did this. I think git can generate such a list pretty easily.

The old commit is `0c2dddd40e4d7492d2a7337be54c345011e5f1e1`. The new commit is `8e236a7f993f1e732ffd0ab5c15736b2594e410`. So if you run this command:
```bash
git log --oneline 0c2dddd40e4d7492d2a7337be54c345011e5f1e1^..8e236a7f993f1e732ffd0ab5c15736b2594e4109
```

Then you get this output:
```
8e236a7 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1544 from JuliaLang/sk/telemetry
90b8482 telemetry: factor out telemetry file loading
228fb97 CI telemetry: send indicators for common CI env vars
246dbd0 Pkg protocol: basic anonymous opt-out telemetry
e66a75f Introduce special REPL syntax for shared environments (#1488)
afeb1ee Merge pull request #1538 from JuliaLang/sk/pkg-client-auth
9c357bb Pkg client auth: support connecting to authenticated Pkg servers
6dd7f34 PlatformEngines: revert API part of headers support (broken)
6825b48 Merge pull request #1539 from 00vareladavid/00/fixes
3f1cf40 it is invalid to `add` a package with no commits
0766765 test: default environment should be created when the primary depot does not exist
43f46f8 check no overwrite is occuring when resolving from a project file
37b6853 handle primary depot as relative path
53fdf24 Check for duplicate name/UUID input
8a6387c Remove redundant precompile statement
4d0901e Dont throw error when autocompleting faulty input (#1530)
d69f6d7 Refactor and test `Pkg.test` (#1427)
8ca8b6d PlatformEngines: use `tar -m` to ignore mtimes (#1537)
6797928 Make sure sandbox's temp Project.toml and Manifest.toml files are writable (#1534)
f968cc9 clarify: stacked envs only affect top-level loading (#1529)
0dfef59 PlatformEngines.download: add header support (#1531)
49ab53e Fix tree hashing with nested empty directories (#1522)
0c2dddd fix #1514: install_archive call in backwards_compatible_isolation (#1517)
```

**Comment by DilumAluthge** [comment]
`buildbot/tester_win32` is failing, but that doesn't seem related to this PR. It looks like a tempfile-related failure.

**Comment by fredrikekre** [comment]
That is a known issue so keeps happening. Also, might be better to just restart the individual worker instead of restatring them all (by opening/closing the PR).

**Comment by DilumAluthge** [comment]
> Also, might be better to just restart the individual worker instead of restatring them all (by opening/closing the PR).

I actually tried that first, but I got the following error:
> Cannot rebuild: you need to have role 'JuliaLang'

**Comment by fredrikekre** [comment]
Right, but you can ask someone to do it :)

**Pull request merged**
