### PR TITLE
use default SIGPIPE handler by default, enable backtrace on SIGPIPE for tests

### LINKED ISSUE #9719: Julia print backtrace on SIGPIPE by default
AFAIK most program either ignore `SIGPIPE` or silently quite on it...

```
yuyichao% LANG=C julia -f -e 'sleep(1); println()' | :

signal (13): Broken pipe
write at /usr/bin/../lib/libpthread.so.0 (unknown line)
unknown function (ip: 756400812)
uv_write2 at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_write_copy at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_putc_copy at /usr/bin/../lib/julia/libjulia.so (unknown line)
jl_pututf8_copy at /usr/bin/../lib/julia/libjulia.so (unknown line)
write at ./stream.jl:732
println at ./string.jl:5
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
println at ./string.jl:8
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 756153688)
unknown function (ip: 756151199)
unknown function (ip: 756223645)
unknown function (ip: 756223783)
jl_toplevel_eval_in at /usr/bin/../lib/julia/libjulia.so (unknown line)
process_options at /usr/lib/julia/sys.so (unknown line)
_start at /usr/lib/julia/sys.so (unknown line)
jlcall__start_40944 at /usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 4200293)
unknown function (ip: 4199194)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 4199269)
unknown function (ip: 0)
```

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #9719.

This implement the 1 and 2 [discussed in #9719](https://github.com/JuliaLang/julia/issues/9719#issuecomment-69485778)
1. Use the default handler on SIGPIPE by default
2. Set the backgrace handler in runtest

I haven't checked how does multiprocessing handle child process terminated by signal but the behavior with runtests should be the same with before and it should probably be discussed somewhere else if the handling of child signal really has an issue.

I'm not sure how/whether to handle windows and I'm also not very good at coming up with good function names so suggestions are definitely welcome........

```
yyc2:~/projects/contrib/julia
yuyichao% LANG=C ./julia -f -e 'sleep(1); println()' | :
yyc2:~/projects/contrib/julia
yuyichao% LANG=C ./julia -f -e 'Base.set_sigpipe_act_die(); sleep(1); println()' | :
ERROR: Couldn't set signal handler for 13: Success
 in error at ./error.jl:21
 in set_sigpipe_act_die at ./process.jl:629
 in process_options at ./client.jl:234
 in _start at ./client.jl:396

signal (13): Broken pipe
write at /usr/lib/libpthread.so.0 (unknown line)
uv__write at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:798
uv_write2 at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:1343
uv_write at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:1369
jl_write_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:541
jl_putc_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:595
jl_pututf8_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:613
write at ./stream.jl:732
println at ./string.jl:5
jl_apply_generic at /home/yuyichao/projects/contrib/julia/src/gf.c:1644
_start at ./client.jl:444
jlcall__start_40668 at /home/yuyichao/projects/contrib/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/yuyichao/projects/contrib/julia/src/gf.c:1646
unknown function (ip: 4200066)
unknown function (ip: 4199034)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 4199109)
unknown function (ip: 0)
```

### CODE REVIEW

**Comment by yuyichao** [comment]
= = ......................... I don't know what I was thinking just now............................ amended....
New output ....................

```
yyc2:~/projects/contrib/julia
yuyichao% LANG=C ./julia -f -e 'sleep(1); println()' | :
yyc2:~/projects/contrib/julia
yuyichao% LANG=C ./julia -f -e 'Base.set_sigpipe_act_die(); sleep(1); println()' | :

signal (13): Broken pipe
write at /usr/lib/libpthread.so.0 (unknown line)
uv__write at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:798
uv_write2 at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:1343
uv_write at /home/yuyichao/projects/contrib/julia/deps/libuv/src/unix/stream.c:1369
jl_write_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:541
jl_putc_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:595
jl_pututf8_copy at /home/yuyichao/projects/contrib/julia/src/jl_uv.c:613
write at ./stream.jl:732
println at ./string.jl:5
jl_apply_generic at /home/yuyichao/projects/contrib/julia/src/gf.c:1644
println at ./string.jl:8
jl_apply_generic at /home/yuyichao/projects/contrib/julia/src/gf.c:1644
do_call at /home/yuyichao/projects/contrib/julia/src/interpreter.c:71
eval at /home/yuyichao/projects/contrib/julia/src/interpreter.c:210
jl_toplevel_eval_flex at /home/yuyichao/projects/contrib/julia/src/toplevel.c:516
jl_toplevel_eval_flex at /home/yuyichao/projects/contrib/julia/src/toplevel.c:381
jl_eh_restore_state at /home/yuyichao/projects/contrib/julia/src/julia.h:1181
process_options at ./client.jl:234
_start at ./client.jl:396
jlcall__start_62919 at /home/yuyichao/projects/contrib/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/yuyichao/projects/contrib/julia/src/gf.c:1646
unknown function (ip: 4200066)
unknown function (ip: 4199034)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 4199109)
unknown function (ip: 0)
```

**Comment by yuyichao** [comment]
What is the access violation error in the windows core tests?

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x68cee033 -- jl_init_codegen at C:\projects\julia\usr\bin\libjulia.dll (unknown line)
```

**Comment by vtjnash** [comment]
i think we can just ignore SIGPIPE always. it would be nice to add a test so that we stop breaking this

ref https://github.com/JuliaLang/julia/issues/4219

(fwiw, window's doesn't have a SIGPIPE)

**Comment by yuyichao** [comment]
[Hmmm.](https://github.com/JuliaLang/julia/commit/0195310b3572f78ec02a0f4a75378b3cc6009ff7)

So here is my opinion.

1. It makes some sense to turn on backtrace printing for `SIGPIPE` especially for testing since there's #9501. So it'll be nice to have a function to turn this on.
2. The default behavior should be silently abort for cli apps and ignored for daemon or gui apps. And which way julia choose depending on what kind of usage julia wants to focus on. My personal preference is to silently abort (default behavior on unix AFAIK) by default and optionally provides an function to ignore sigpipe. The reasons are:

    1. Julia doesn't come with a GUI by default
    2. So far most of the julia program I've seen does not have a GUI
    3. For cases where SIGPIPE might causes issue or should be ignored, this is usually handled by sth else already. E.g. the manager process for daemons and long lasting processes, and the toolkit for GUI programs.

My concern about windows is mainly about whether to provide an alternative implementation of `jl_set_signal_act_die` to print backtrace on certain signals and whether to have a dummy `set_sigpipe_act_die` that does nothing...

**Comment by yuyichao** [comment]
And another point is that

**Comment by vtjnash** [comment]
> My concern about windows is mainly about whether to provide an alternative implementation of jl_set_signal_act_die to print backtrace on certain signals and whether to have a dummy set_sigpipe_act_die that does nothing...

windows doesn't have proper signals. its CLI didn't support running multiple programs back back when it was called DOS, so it didn't have pipes and didn't need SIGPIPE

**Comment by yuyichao** [comment]
It does seem to [have signal](https://github.com/JuliaLang/julia/blob/master/src/init.c#L1135)?
And having a dummy implemtation means I don't need `@unix_only` in `runtests`......

**Comment by vtjnash** [comment]
msvc emulates signals in the C library. having `raise` dispatch to the method table defined by `signal` turns out to be very unreliable however (since there end up being a lot of different method tables owned by a lot of different signals methods in a lot of different msvcrt libraries).

i'm not sure whether it's better to define a no-op method or force the consumer to be aware of it

**Comment by yuyichao** [comment]
I C. In which case I would prefer to leave out windows for now. Anyway, adding a dummy implementation is always less painful than removing one (since removing one is potentially breaking...)

So is there any preference on the default behavior on SIGPIPE? Ignoring seems to be the old behavior before the commit I linked. (I still personally prefer `SIG_DFL` but anything that doesn't print out a nasty backtrace when I pipe the output of a julia script to `head` is fine for me......)

**Comment by yuyichao** [comment]
Close since the current behavior is good enough.

**Pull request closed without merging**
