### PR TITLE
Fix v1.0.0 docs

### PR DESCRIPTION
**Pull request by mortenpi**
This PR is against `gh-pages`.

Copies the `latest/` docs based on e7d15d4a013a43442b75ba4e477382804fa4ac49 to `v1.0.0/` and `stable/`. Fixes the "Edit on GitHub" links and maybe other issues that might have arisen due to manually deploying the 1.0.0 docs.

cc @fredrikekre

### CODE REVIEW

**Comment by fredrikekre** [comment]
I think I may already have pushed it?

**Comment by mortenpi** [comment]
Nope :laughing:

**Comment by mortenpi** [comment]
Feel free to push and close this though. Did you also update the `siteinfo.js` files?

**Comment by fredrikekre** [comment]
Okay then, I had to abort thr push when my plane took off so I guess it did not go tgrough.

Yea, I updated them. Will have a look soon.

**Pull request merged**
