### PR TITLE
add tests for closest candidate for type constructors

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://github.com/JuliaLang/julia/pull/16155 cc @tkelman

### CODE REVIEW

**Comment by KristofferC** [comment]
Oh yeah, this test is not correct on 32 bit. Will update. Btw, I'm impressed with the speed that AppVeyor finished.

**Comment by KristofferC** [comment]
One AppVeyor seems to be stuck.

**Comment by tkelman** [comment]
Restarted. Thanks for these!

**Comment by KristofferC** [comment]
All gucci now.

**Pull request merged**
