### PR TITLE
relax sparse multiplication with other arrays from Strided to Abstract

### LINKED ISSUE #28011: performance regression for the product between a sparse matrix and a BitArray.
In Julia 0.7.0-beta.206 I see a performance regression relative to Julia 0.6.3 for a production between a sparse matrix and a BitArray. This regression does not affect arrays created by e.g. `ones(Bool,n)`, just BitArrays. It seems that the sparse matrix is transformed into a full matrix.

```julia
using SparseArrays
using LinearAlgebra
n = 1000
@time sparse(1.0I,n,n) * trues(n);
```
33.780663 seconds (116.22 M allocations: 2.102 GiB, 0.36% gc time)

julia 0.6.3:

```julia
n = 1000
@time sparse(1.0I,n,n) * trues(n)
```
0.000031 seconds (14 allocations: 32.313 KiB)

```
Julia Version 0.7.0-beta.206
Commit b6f9244d6b (2018-07-08 19:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/28011 and it is good to have as relaxed methods as allowed. I don't see any need to enforce stridedness here?

```jl
julia> n = 1000000
1000000

julia> @time sparse(1.0I,n,n) * trues(n);
  0.010378 seconds (17 allocations: 30.638 MiB)
```

The changes here are that all `mul!` methods where put close to each other and (for ambiguity resolution) a `@eval`-loop goes over `AbstractMatrix` and `AbstractVector` and creates both versions of the `mul!` method. This is to avoid ambiguities.

Should probably be tested somehow, is there some other tests that test that we dispatch to the correct method?

### CODE REVIEW

**Comment by andreasnoack** [comment]
I've wondered if we could fix the "upstream" definitions somehow to avoid the need for splitting up the `VecOrMat` union as you do here. Probably to avoid that any of the wide definitions use anything but the union.

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/pull/8726. I'm not sure I agree with myself as of four years ago here. Of course, it should be possible to do a rank one update in a preallocated matrix but we might not need all of these.

> Why should `mul!(::AbstractMatrix, ::AbstractMatrix, ::AbstractVector)` work?

I think this one is okay. In many places, matrices with one column and vectors behave the same and is there a risk of ambiguity about what should happen here?

**Comment by KristofferC** [comment]
Looks like this induced ambiguities anyway.

**Comment by KristofferC** [comment]
>  In many places, matrices with one column and vectors behave the same and is there a risk of ambiguity about what should happen here?

I think

```
julia> using LinearAlgebra

julia> *(rand(1), rand(1))
ERROR: DimensionMismatch("Cannot multiply two vectors")
Stacktrace:
 [1] *(::Array{Float64,1}, ::Array{Float64,1}) at /Users/kristoffer/julia/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/deprecated.jl:566
 [2] top-level scope at none:0

julia> mul!(rand(1), rand(1), rand(1))
1-element Array{Float64,1}:
 0.1511453429318608
```

is weird, yes.

**Comment by KristofferC** [comment]
Also, the original use case in https://github.com/JuliaLang/julia/pull/8726 doesn't apply anymore with lazy adjoints.

**Comment by andreasnoack** [comment]
I was referring to the `mul!(::AbstractMatrix, ::AbstractMatrix, ::AbstractVector)` signature, i.e. where a vector can be stored in preallocated one-column matrix. I don't think `mul!(::AbstractVector, ::AbstractVector, ::AbstractVector)` is a good idea.

**Comment by KristofferC** [comment]
Hm, I don't think I will have time to drain the ambiguity swamp for a while.

**Comment by ViralBShah** [comment]
Should we leave this PR open, and try to revive it now?

**Pull request closed without merging**
