### PR TITLE
Remove remaining trailing whitespace

### PR DESCRIPTION
**Pull request by jakebolewski**
Removes TODOs from #9787.

### CODE REVIEW

**Comment by tkelman** [comment]
I rebased this for you, hope you don't mind.

**Comment by jakebolewski** [comment]
Not at all.  Here is the command I used if you need to do this on the 0.3 branch.

```
find . -type f \(-name “*.inc” -o -name “*.make” -o -name “*.md” -o -name “*.rst” -o -name “*.sh” -o -name "*.yml" -o  -name "*Makefile" \) -exec perl -p -i -e "s/[ \t]*$//g" "{}" \;
```

**Comment by tkelman** [comment]
That is useful, thanks. Haven't done that yet but have been thinking about it to simplify backporting.

**Comment by tkelman** [comment]
Except that doesn't work with GNU find. Care to translate that into something more portable?

**Comment by tkelman** [comment]
Nevermind, on non-OSX it apparently needs a space after the open parenthesis, and non-unicode quotes are probably also a good idea.

**Comment by jakebolewski** [comment]
Weird, seems to be an autocorrect "feature" in Apple's Notes App.

**Comment by tkelman** [comment]
Rebased this again. A few new whitespaces have snuck in. Interestingly the check does not cause Travis to fail immediately, it runs all the tests and forces you to scroll all the way up to the start of the log to figure out why the status was failed. I'm liking the option of doing this in a separate Travis job or on a separate Travis-competitor service (#9553 did the former, and mentions the latter) more and more.

**Comment by ViralBShah** [comment]
I cancelled the appveyor build. Assume that is ok here.

**Comment by tkelman** [comment]
Yeah, if there are better things to run it on sure. It was otherwise idle, and just in case...

**Comment by ViralBShah** [comment]
I wanted my sparse solver stuff to go through...

**Comment by tkelman** [comment]
Sure, looks like it needs some work to deal with the recent Triangular changes.

Looking at this more closely, we could potentially do `make check-whitespace || exit 1` in `.travis.yml` to make it stop early on whitespace problems. That's what the check as written currently does, where it's entirely in bash straight from `.travis.yml` - when it gets moved into a script that gets run by `make`, then the `exit` inside the script just sets the exit code of that line, rather than terminating the Travis job early.

**Comment by jakebolewski** [comment]
Can we move the check to the end of the travis run, or add your suggested fix, and be done?  I don't think we have to be too fancy yet.   I think that the fast fail is nice, but I agree now it penalizes our appveyor ci builds, so putting it at the end makes sense.

**Comment by tkelman** [comment]
Sure. My idea works for fast failure, tested it in a different branch: https://travis-ci.org/JuliaLang/julia/builds/47524519

Just have to pick which we want. If we merge #9809 as well then doing it at the end of the tests makes more sense, since it should happen earlier on people's local machines.

**Comment by jakebolewski** [comment]
@tkelman thanks, I just kept the behavior we currently have.  We can always tweak this latter.

**Pull request merged**
