### PR TITLE
Allow 0-length arrays to be returned from Mmap.mmap. Fixes #10516

### LINKED ISSUE #10516: mmap_array fails for empty file (0-length array)
`mmap_array(Int, (0,), open("foo", "r"))` on an empty file `"foo"` gives:
```
ERROR: SystemError: memory mapping failed: Invalid argument
 in systemerror at /Users/stevenj/Code/julia/usr/lib/julia/sys.dylib
 in mmap at mmap.jl:35
 in mmap_array at mmap.jl:108
 in mmap_array at mmap.jl:4
```
(See also JuliaLang/JSON.jl#98.)

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
Looks like the 32-bit windows failure is unrelated? (64-bit passes).

**Comment by tkelman** [comment]
Have seen this before elsewhere but still worrying:
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!
Program: C:\projects\julia\usr\bin\julia.exe
File: /home/Tony/julia32/deps/llvm-3.3/include/llvm/ADT/SmallVector.h, Line 144
Expression: begin() + idx < end()
	From worker 2:	     * math                 Worker 2 terminated. 
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
```

restarted, let's see if it's repeatable

**Comment by stevengj** [comment]
Tests are green, looks good to merge.  Thanks!

**Comment by quinnj** [comment]
Could this be backported? I guess probably not since it technically changes the API

**Comment by tkelman** [comment]
Do you have an immediate use case or need? It should just be allowing a case that formerly errored so with my usual caveat of you better declare your exact dependency if you come to rely on this working I guess it could be backported, but maybe let it live on master for a little while first to see if there are any unforeseen consequences.

**Comment by quinnj** [comment]
No, I don't actually have a use case; I think it's just the fact that we're so close to 0.4, there's an itch to not miss out on stuff. I say we leave it for now.

**Pull request merged**
