### PR TITLE
🤖 [master] Bump the Pkg stdlib from 992a8c27b to aead92e73

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Pkg
URL: https://github.com/JuliaLang/Pkg.jl.git
Stdlib branch: master
Julia branch: master
Old commit: 992a8c27b
New commit: aead92e73
Julia version: 1.10.0-DEV
Pkg version: 1.10.0
Bump invoked by: @IanButterworth
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/Pkg.jl/compare/992a8c27b967f45f04de07bd84a2763644cb8a33...aead92e73e3414b45d7f4f7adf217b50a151a59d

```
$ git log --oneline 992a8c27b..aead92e73
aead92e73 precompile: improve no match error messaging (#3437)
79f5e3bc2 fix handling of relative paths in `bind_artifact!` (#3435)
```

### CODE REVIEW

**Comment by aviatesk** [comment]
Thx!

**Comment by IanButterworth** [comment]
arg, I just realized this would break precompiling packages from higher environment stacks due to code load precomp now uses `Pkg.precompile` on master
```
(@v1.10) pkg> st
Status `~/.julia/environments/v1.10/Project.toml`
  [336ed68f] CSV v0.10.9
Info Packages marked with ⌃ have new versions available and may be upgradable.

(@v1.10) pkg> activate --temp
  Activating new project at `/var/folders/_6/1yf6sj0950vcg4t91m9ltb5w0000gn/T/jl_suKAP4`

julia> using CSV
ERROR: No direct dependencies found matching ["CSV"]
```

**Comment by Keno** [comment]
I'm seeing that error on master already for some reason.

**Comment by IanButterworth** [comment]
Ah yeah, there's two code paths. Pkg bump with a fix incoming

**Pull request closed without merging**
