### PR TITLE
[WIP] Add input function.

### PR DESCRIPTION
**Pull request by Ismael-VC**
All these languages provide an `input(prompt)` function:
- [Python](https://docs.python.org/3.4/library/functions.html#input)
-  [R](http://www.rexamples.com/4/Reading%20user%20input)
- [Matlab](http://www.mathworks.com/help/matlab/ref/input.html)
- [Octave](https://www.gnu.org/software/octave/doc/interpreter/Terminal-Input.html)
- [Mathematica](http://reference.wolfram.com/language/ref/Input.html)

I've had to define at first such function whenever I needed input, and then import it from a module to avoid redundancy. It would be nice to have something like this around, though I don't know if my implementation would be correct for a general use case.

### CODE REVIEW

**Comment by dhoegh** [comment]
:+1: for the function.

**Comment by Ismael-VC** [comment]
I don't know why this happens:
   
    error during bootstrap: LoadError(at "sysimg.jl" line 117: LoadError(at "stream.jl" line 707: UndefVarError(var=:String))) 

I define it in the REPL and it works, this are my computer specs:
```
Julia Version 0.4.0-dev+2824
Commit 6bc53e6* (2015-01-19 20:14 UTC)
Platform Info:
  System: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Atom(TM) CPU N570   @ 1.66GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Atom)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I'll compile it tonight while I sleep and check it out tomorrow morning.

**Comment by tkelman** [comment]
`String` has been renamed to `AbstractString` for 0.4, and the deprecation is not yet defined at the time your new function is being compiled into the system image.

**Comment by ivarne** [comment]
We also need documentation (and tests) for new functions (and you'd probably want it to be exported).

I'm also not sure on the argument order. How about something like?
```julia
function input(prompt::AbstractString = ""; inn::IO = STDIN, out=STDOUT)
```
Keyword arguments doesn't cause much performance bottleneck with IO functions and I don't think there is any good way to remember which order to give the arguments.

**Comment by Ismael-VC** [comment]
@tkelman  @ivarne I'll get down to it, thanks!

**Comment by Ismael-VC** [comment]
Ops! I didn't mean to close this, I'll aopen a new pull request and reference this one.

**Comment by Keno** [comment]
I believe you can also just force push any new changes to the branch you opened the pull request from and then reopen this one.

**Comment by Ismael-VC** [comment]
@Keno I'm sorry I already opened another pull request, I just saw your comment, still learning git foo here, I'll have to reread the git book. :smile:

**Pull request closed without merging**
