### PR TITLE
[GCLowering] Fix phis of unions

### PR DESCRIPTION
**Pull request by Keno**
This fixes gc lowering for phis of the form:
```
%phi = phi {%jl_value_t addrspace(10)*, i8} [%aunion, %a], [%bunion, %b]
```
This kind of struct (used by the tagged union representation) has special support
in GC lowering. After optimization, these structs often survive quite far as a
struct (i.e. the destructuring of them is often elided). We simply need to extend
this support to the cases that handle phi and select nodes.

Fixes crashes with the new optimizer enabled noted in #26925

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
Thanks Keno! This does indeed fix the issue I noticed.

The only other thing I am seeing on LLVM 6 with the new optimizer enabled is:

```
Test Failed at /scratch/vchuravy/julia/usr/share/julia/stdlib/v0.7/SparseArrays/test/higherorderfns.jl:269
  Expression: #= /scratch/vchuravy/julia/usr/share/julia/stdlib/v0.7/SparseArrays/test/higherorderfns.jl:269 =# @allocated
(broadcast!(f, Q, X, Y, Z)) == 0
   Evaluated: 16 == 0
``` 

which I suppose is meant to be fixed by 26990?

**Comment by Keno** [comment]
No, that's #26981.

**Comment by Keno** [comment]
CI failures look related. Will take a look.

**Comment by vchuravy** [comment]
OSX CI failure seems unrelated:
```
Error in testset FileWatching:
Test Failed at /private/tmp/julia/share/julia/stdlib/v0.7/FileWatching/test/runtests.jl:401
  Expression: pop!(changes) == (F_PATH => FileWatching.FileEvent(FileWatching.UV_RENAME))
   Evaluated: "afile.txt3" => FileWatching.FileEvent(true, false, false) == "afile.txt" => FileWatching.FileEvent(true, false, false)
Error in testset FileWatching:
Test Failed at /private/tmp/julia/share/julia/stdlib/v0.7/FileWatching/test/runtests.jl:405
  Expression: pop!(changes) == (F_PATH * "~" => FileWatching.FileEvent(FileWatching.UV_RENAME))
   Evaluated: "afile.txt2" => FileWatching.FileEvent(true, false, false) == "afile.txt~" => FileWatching.FileEvent(true, false, false)
Error in testset FileWatching:
Test Failed at /private/tmp/julia/share/julia/stdlib/v0.7/FileWatching/test/runtests.jl:417
  Expression: pop!(changes) == ("$(F_PATH)$(i)" => FileWatching.FileEvent(FileWatching.UV_RENAME))
   Evaluated: "afile.txt" => FileWatching.FileEvent(false, true, false) == "afile.txt3" => FileWatching.FileEvent(true, false, false)
Error in testset FileWatching:
Test Failed at /private/tmp/julia/share/julia/stdlib/v0.7/FileWatching/test/runtests.jl:417
  Expression: pop!(changes) == ("$(F_PATH)$(i)" => FileWatching.FileEvent(FileWatching.UV_RENAME))
   Evaluated: "afile.txt" => FileWatching.FileEvent(true, false, false) == "afile.txt2" => FileWatching.FileEvent(true, false, false)
Error in testset FileWatching:
Test Failed at /private/tmp/julia/share/julia/stdlib/v0.7/FileWatching/test/runtests.jl:417
  Expression: pop!(changes) == ("$(F_PATH)$(i)" => FileWatching.FileEvent(FileWatching.UV_RENAME))
   Evaluated: "afile.txt" => FileWatching.FileEvent(true, false, false) == "afile.txt1" => FileWatching.FileEvent(true, false, false)
ERROR: LoadError: Test run finished with errors
in expression starting at /private/tmp/julia/share/julia/test/runtests.jl:59
```

**Pull request merged**
