### PR TITLE
Small cosmetic correction to merged PR #7322

### PR DESCRIPTION
**Pull request by mauro3**
as suggested by @tkelman: https://github.com/JuliaLang/julia/pull/7322#discussion_r28846072

### CODE REVIEW

**Comment by tkelman** [comment]
seems the first couple `if isa(ex0, Expr)` conditions could also be expressed cleaner via dispatch. I can see why they weren't written that way, they used to be inside the implementation of `macro which` but now it's a separate function.

**Comment by mauro3** [comment]
Like this?

**Comment by tkelman** [comment]
I was thinking more like
```
function gen_call_with_extracted_types(fcn, ex0::Expr)
    if any(a->(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args)
        # keyword args not used in dispatch, so just remove them
        args = filter(a->!(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args)
        return Expr(:call, fcn, esc(args[1]),
                    Expr(:call, :typesof, map(esc, args[2:end])...))
    end
    if ex0.head == :call
        return Expr(:call, fcn, esc(ex0.args[1]),
                    Expr(:call, :typesof, map(esc, ex0.args[2:end])...))
    end
    #
end
function gen_call_with_extracted_types(fcn, ex0)
    ex = expand(ex0)
```
then the rest of the existing implementation, but I realized that would be missing a fallback at `#`. I guess your version works better as long as `expand(::Expr)` always returns an `Expr`, or maybe no need to worry about it.

**Comment by mauro3** [comment]
I don't think expand(::Expr) needs to return a Expr as that would still be caught in line 239. The downside of the tweak is that there is code duplication on line 224 & 238.  Let me know what you prefer and I can update and rebase.

**Comment by tkelman** [comment]
I think if `expand(ex0)` were to somehow return an expression from a non-expression `ex0` (this might not be possible, not sure), then your second commit would return the error in that case, which wouldn't error before. I was looking at it too hastily and on second thought the second commit might not really be worth fiddling with.

**Comment by mauro3** [comment]
No worries, reverted to the first commit.

**Pull request merged**
