### PR TITLE
Do not merge: backport-test of range changes

### PR DESCRIPTION
**Pull request by timholy**
#18777 is failing at either build or test time on 32 bit, in ways that do not seem entirely deterministic. There are at least 2 hypotheses:
- the PR is broken
- the PR exposes a bug in the compiler

This is an attempt to distinguish these (since I don't have access to 32-bit, I'm relying on CI). It's not a perfect test, but if it passes when backported to 0.5, that increases the likelihood that it's a compiler bug.

### CODE REVIEW

**Comment by timholy** [comment]
Oh, now that's simply not fair. Why isn't CI running?

**Comment by quinnj** [comment]
I've seen a few blips w/ travis this morning, jobs taking a long time to "register", OSX is particularly slow/backed up again, etc...

**Comment by tkelman** [comment]
There's a `[ci skip]` in the commit message. Though there might be some travis-specific issues where I need to backport some yml and/or test fixes to make it green. Maybe those won't be relevant for what you're trying to find.

**Comment by timholy** [comment]
That was it! Thanks, @tkelman. Came from a big squash of many commits, I didn't think to check for that.

**Comment by timholy** [comment]
This proved to be unexpectedly informative...I a `test/ranges.jl` failure on 32-bit but with a much more helpful backtrace than on master. The problem seems to be in `maxintfloat`, which is defined [here](https://github.com/JuliaLang/julia/blob/7b7b4e1d24aa449bf33af93e684ca8924b66a010/base/floatfuncs.jl#L19-L21) and used in the range tests [here](https://github.com/JuliaLang/julia/blob/7b7b4e1d24aa449bf33af93e684ca8924b66a010/test/ranges.jl#L376). The issue is that the value for `maxintfloat(Float64)` is smaller than `typemax(Int64)` but bigger than `typemax(Int32)`, and in the new range code I represent the `len` of both `StepRangeLen` and `LinSpace` as `Int` rather than `Float64`. It's the conversion of `maxintfloat(Float64)` that is the source of the `InexactError`.

There are many places in julia where we assume that `length(::AbstractVector)` is representable as an `Int`, so I'm inclined to recommend that we change the tests to be `min(maxintfloat(T), typemax(T))`. But I'm happy to listen to alternative suggestions.

**Pull request closed without merging**
