### PR TITLE
add missing imports for iszero to Big numbers

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes performance regression noted in https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/daily_2016_12_21/report.md

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("scalar", vs = ":master")`

**Comment by KristofferC** [comment]
I force pushed over a whitespace error so the Nanosoldier status is not showing up. It should reply when ready though.

**Comment by KristofferC** [comment]
Or maybe not. Let's try again.

@nanosoldier runbenchmarks("scalar", vs = ":master")

**Comment by KristofferC** [comment]
Or maybe not. Let's try again.

@nanosoldier `runbenchmarks("scalar", vs = ":master")`

**Comment by KristofferC** [comment]
Guess nanosoldier is taking a well deserved rest. Anyway, I confirmed locally that this fixes the regression.

**Review by tkelman — APPROVED** [review]

**Comment by jrevels** [comment]
Our favorite network error took out the head node again. Restarted it:

@nanosoldier `runbenchmarks("scalar", vs = ":master")`

**Comment by stevengj** [comment]
LGTM.

**Review by Sacha0 — APPROVED** [review]

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19679#issuecomment-268810641) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/74bafb974e658a927e9fb0fcb37fe3351c598a8f/3682e02_vs_387e964/report.md). cc @jrevels

**Pull request merged**
