### PR TITLE
Generate instead of hard coding factorial tables

### PR DESCRIPTION
**Pull request by TotalVerb**
This should be less prone to bugs.

### CODE REVIEW

**Comment by tkelman** [comment]
> This should be less prone to bugs.

How so?

**Comment by TotalVerb** [comment]
big number constant literals might be incorrect; it takes some work to verify. of course I think the original literals have been verified already, but there isn't any harm in doing this.

**Comment by tkelman** [comment]
what's more likely to sneak through without tests noticing, the literals being wrong (or mis-parsed?) or something screwy happening to the generation code like an accidental overflow due to some other problem?

**Comment by TotalVerb** [comment]
Any test that detects literals being wrong will certainly also detect the generation code being wrong.

**Comment by TotalVerb** [comment]
Also, it is easier for a human to detect an error in the generation code than to detect an error in the literal.

**Comment by tkelman** [comment]
Probably, and it's a bit shorter. We might want to preallocate them to the right size, to avoid a few bytes of overallocation that'll never be needed.

**Comment by GregPlowman** [comment]
Maybe the existing literal tables could be used as part of the tests for the generated values?

**Comment by ViralBShah** [comment]
How about the other way around - Why not leave the literal tables here, and instead have the code verify the tables in the tests? Does this have any noticeable impact on startup time (just asking)?

**Comment by Keno** [comment]
> Does this have any noticeable impact on startup time (just asking)?

This would happen at sysimg time, so any time impact would only be there. This shouldn't take any noticeable amount of time though.

**Comment by TotalVerb** [comment]
I've addressed the comments of @tkelman and @GregPlowman.

**Review by tkelman — APPROVED** [review]

**Pull request merged**
