### PR TITLE
`OneTo` indices in a `view` should have fast linear indexing

### PR DESCRIPTION
**Pull request by Jutho**
I assume this was missed in the addition of the `OneTo` type?

``` julia
B = view(A, indices(A,1), 2:2)
```

is contiguous and should have fast linear indexing. Does this need a test?

cc @timholy

### CODE REVIEW

**Comment by Jutho** [comment]
Clearly I was too optimistic in thinking that I could fix this via the Github web interface without testing it locally. I'll try to correct this when I am at home tonight.

**Comment by mbauman** [comment]
CI is just failing due to #18577.  But more consideration will need to be given to offset arrays.  If you want to do the minimal thing here and not worry about that, use `Union{UnitRange, OneTo}` instead of `AbstractUnitRange` since the latter might not start at one.

**Comment by timholy** [comment]
Good catch.

Interestingly, the example you give, however, can't have fast linear indexing. For example,
```jl
A = rand(3,5)
B = view(A, 1:2, 1:3)
```
clearly can't have fast linear indexing. Now, `view(A, 1:3, 1:3)` is contiguous and therefore could have fast linear indexing, but the type system (which is where we make this decision) doesn't know that. 

However, if all trailing indices are scalars (2 rather than `2:2`), then it's OK for the last "vector" index to be an `AbstractUnitRange`.

**Comment by Jutho** [comment]
Indeed, I was mixing linear indexing with the contiguous storage for BLAS matrix multiplication. But are the changes correct? Everywhere `UnitRange` is acceptable, `OneTo` should also be acceptable?

**Review by timholy — APPROVED** [review]

**Comment by timholy** [comment]
Yes, the code changes are perfect, and helpful indeed. Thanks!

From my perspective this can be merged once CI finishes.

**Comment by tkelman** [comment]
> Does this need a test?

It wouldn't hurt?

**Comment by mbauman** [comment]
This is still worth doing.  I've rebased it and added a test — although note that it doesn't fix the case @Jutho originally reported.  We cannot assume that `A[OneTo(4), 1:2]` is linear as the first dimension might be larger than four elements.  That's precisely why the special `Base.Slice` object exists — it flags the fact that we're spanning the entire dimension.

This means that Jutho's original case still must remain IndexCartesian.  The case that this affects is OneTo indices that _follow_ a complete slice:

    view(A, indices(A,1), 2:2) # still IndexCartesian
    view(A, :, indices(A,2)) # newly IndexLinear

**Comment by Jutho** [comment]
Thanks for that; I had forgotten about it. My initial example was indeed incorrect, as also pointed out by @timholy .

**Pull request merged**
