### PR TITLE
Make sure `:push_loc` meta always has a corresponding `:pop_loc`

### LINKED ISSUE #16578: Call stack is very confused on error
I have lately been getting very confusing call stacks in the error messages that make no sense from how I know my calls are being made.

For example:

```jl
ERROR: BoundsError: attempt to access 28-element Array{Float64,1} at index [[4,6,13,15,22,24,31,33]]
 in throw_boundserror(::Array{Float64,1}, ::Tuple{Array{Int64,1}}) at ./abstractarray.jl:132
 in _internal_checkbounds at ./multidimensional.jl:219 [inlined]
 in checkbounds at ./multidimensional.jl:215 [inlined]
 in _getindex at ./multidimensional.jl:271 [inlined]
 in getindex at ./abstractarray.jl:425 [inlined]
 in zero at /home/kristoffer/.julia/v0.5/ContMechTensors/src/ContMechTensors.jl:72 [inlined]
 in intf(...)  at /home/kristoffer/Dropbox/julia/ViscoCrystalPlast/src/dual/intf_dual.jl:50
 in zero at /home/kristoffer/.julia/v0.5/ContMechTensors/src/ContMechTensors.jl:105 [inlined]
 in assemble!(...)  at /home/kristoffer/Dropbox/julia/ViscoCrystalPlast/src/solve_problem.jl:85
 in solve_problem(..) at /home/kristoffer/Dropbox/julia/ViscoCrystalPlast/src/solve_problem.jl:44
 in startit(::JuAFEM.Dim{3}) at /home/kristoffer/Dropbox/julia/ViscoCrystalPlast/experiments/compute_gradient_energy_dual.jl:64
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

There are many problems with this call stack:

* It suggests that the function `zero` in `ContMechTensors.jl` calls `intf` which is not true. `assemble!` calls `intf` directly.

* It says that the error is at `/intf_dual.jl:50` which runs a command  `fill!(fe_u, zero(Vec{dim, T}))` so the call above at `zero` makes sense, *if that is where the error actually happened, but it isn't*. 

* The error is actually at line `75` where I have `a[ξ⟂_node_dofs]` and `ξ⟂_node_dofs` are the indices which access the array OOB. However, at this line there is no calls to `zero` at all so how did those get into the call stack?

This is from my research code so it is quite messy to get running so I don't have a MWE right now. I could try to check if it was introduced in #16335 if that would help?

### PR DESCRIPTION
**Pull request by yuyichao**
- Preserve meta node and line number info during dead code elimination
- Insert `:push_loc` and `:pop_loc` in pairs during lowering

Fix #16578

### CODE REVIEW

**Comment by yuyichao** [comment]
This adds a `SSAValue` in some cases so

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

Also, why is circleci trying to build on this pr without a config file?

**Comment by tkelman** [comment]
> Also, why is circleci trying to build on this pr without a config file?

Because it's kinda dumb. Ignore it while we try to get #18007 up and running.

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/18180#issuecomment-241436724): `RemoteException(2,CapturedException(NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`make`, ProcessExited(2)) [2]"),Any[( in pipeline_error at process.jl:612,1),( in run at process.jl:588,1),( in build_julia! at build.jl:54,1),( in execute_benchmarks! at BenchmarkJob.jl:251,1),( in run at BenchmarkJob.jl:178,1),( in #503 at multi.jl:1410,1),( in run_work_thunk at multi.jl:996,1),( in macro expansion at multi.jl:1410 [inlined],1),( in #502 at event.jl:46,1)]))`
cc @jrevels

**Comment by tkelman** [comment]
We should probably revert #18164 until we're sure it works from a clean build. I guess a side effect of running nanosoldier more often is that it tests that configuration, and on a fast enough machine that it doesn't take forever to do so.

**Comment by yuyichao** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18180#issuecomment-241613449) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/764fff324041d2c3ffd4a2644fe6a4ae8ecbdf70/fb34fda_vs_3f29b37/report.md). cc @jrevels

**Comment by yuyichao** [comment]
Comment? I can't really reproduce the two regressions in the nanosoldier report so I'm tempting to believe it's just noise.

**Pull request merged**
