### PR TITLE
remove front-end deprecations for 1.0

### PR DESCRIPTION
**Pull request by JeffBezanson**
This takes care of most of them.

One real problem I've found so far is that the pattern
```
for i in itr
    local i
```
is currently used to opt-in to the new scope behavior. However, with the new behavior turned on this gives a `local declared twice` error. We have long given this error in similar cases, e.g. `let i=0; local i; end`. For now I just disabled the error, since it's pretty useless. Declaring a local twice doesn't cause any real problem and is more of a lint thing. But if we want we could be fancier and only give the error when the source code has two declarations, ignoring compiler-inserted declarations.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Not warning for that seems fine to me. As you said, it's more of a linting thing that correctness.

**Comment by JeffBezanson** [comment]
Another issue: after removing `.'`, `x.'y'` parses as `x`, dot operator, character literal `'y'`. Should this be a parse error?

**Comment by StefanKarpinski** [comment]
> Should this be a parse error?

Yes, otherwise that seems like a a pretty bad trap. We could even allow it again in the future.

**Comment by JeffBezanson** [comment]
Now also includes #9343, underscores as dummy variables. That can be moved to separate PR if necessary though.

**Comment by Keno** [comment]
@JeffBezanson master's now 1.0, so this can go in as soon as you're ready and CI is passing.

**Comment by timholy** [comment]
This may be "in the weeds," but if it's not inconvenient, it would be nice if this deprecation-removal is merged before other deprecation-removals. I have a fun developer-oriented package (will be introduced at JuliaCon) that only works reliably if the "local scope" deprecation is removed. Aficionados might want to build at the merge commit so they can make use of the package and still get the benefit of all the other deprecation warnings as they update their code to 0.7/1.0.

But don't sweat over this request.

**Comment by JeffBezanson** [comment]
You got it, Tim :)

**Pull request merged**
