### PR TITLE
Infer a missing method as returning `Union{}`

### PR DESCRIPTION
**Pull request by martinholters**
Ref https://github.com/JuliaLang/julia/issues/20033#issuecomment-282228948 and https://github.com/JuliaLang/julia/commit/0b8f0b7dc406aabdd1de700b716c5fe700fa5cca#commitcomment-21033206.

### CODE REVIEW

**Comment by martinholters** [comment]
Derp. I really should get into the habit of enabling assertions.

**Comment by martinholters** [comment]
Huh, looks like `[Union{}]` triggers the assertion, while `Any[Union{}]` works.

**Comment by martinholters** [comment]
Looks like I found a reason for better inferring `Any` myself: #20869.
In the long run, I still think this PR is the way to go, but we need to fix #20869 first.

**Comment by StefanKarpinski** [comment]
@vtjnash: Jeff wants your opinion on this, but is "generally in favor".

**Comment by vtjnash** [comment]
As the author of this PR noted above, we can't do this until type-intersection is usually correct.

**Comment by martinholters** [comment]
OTOH, as long as type-intersection may give wrongly empty answers, things can easily break anyway; this PR only makes it even a little easier. Consider
```julia
function foo(...)
# ...
end

function bar(...)
    # ...
    foo(...)
end
```
Now if the inferred types for the arguments to `foo` in `bar` and the signature of `foo` have a wrongly empty intersection computed (i.e. the actual argument types determined at runtime match the signature), then on master, things are fine, while with this PR, calling `bar` will likely crash as `foo` unexpectedly returns a result instead of throwing. But now add
```julia
foo(...) = error("arguments must ... whatever")
```
with a signature more general than the first `foo` method to add a more descriptive error message instead of a `MethodError`. Now if only this second method has a non-empty intersection, then master will be equally prone to a crash as this PR.

I guess what I'm trying to say is: We really need to make type-intersection reliable; this PR only increases the pressure to do so.

**Comment by StefanKarpinski** [comment]
In a way, making the process more likely to crash in cases where inference is wrong is helpful for finding cases where it is wrong.

**Comment by martinholters** [comment]
Superseded by #21892.

**Pull request closed without merging**
