### PR TITLE
make Meta-M with a empty prompt return the contextual module to Main

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Review by rfourquet — APPROVED** [review]
LGTM, but the docs should be updated: https://docs.julialang.org/en/v1/stdlib/REPL/#Changing-the-contextual-module-which-is-active-at-the-REPL

**Comment by tecosaur** [comment]
Prompted by this change, I've just had a thought: could `M-m` when in `Main` take you back to the module you just came from?

**Comment by KristofferC** [comment]
Seems reasonable to me at least.

**Comment by tecosaur** [comment]
I've just been finding myself using the handy `<Module> M-m` when I want to try a tweak to something internal to it, `M-m` to go back to `Main` ... and then realising I need to repeat the process again and am typing `<Module> M-m` a whole lot.

Maybe this is just me, but if it isn't I think it could be quite nice to have.

**Comment by IanButterworth** [comment]
@tecosaur that does seem like a good idea. Are you planning to PR it?

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/julia/pull/52670

**Pull request merged**
