### PR TITLE
add functors SubFun, DivFun, and PowFun

### PR DESCRIPTION
**Pull request by lindahua**
Several basic functors (subtraction, division, and power) are currently missing (which should be an oversight). This PR adds them.

These functors will be useful in the Sparse module. Since this is a very quick-fix, I make a quick PR for this, instead of putting these small changes to the SparseVector PR (which might take a relatively long time to get merged).

### CODE REVIEW

**Comment by tkelman** [comment]
needs tests - https://github.com/JuliaLang/julia/blob/a3f06053335aada2c996f1112ede13749de00697/test/functors.jl#L9

**Comment by lindahua** [comment]
tests added

**Comment by simonbyrne** [comment]
One minor point: we really have three division functions: `/`, `\` and `div`. So should `DivFun` really be `RDivFun`?

**Comment by lindahua** [comment]
What about `RDivFun`, `LDivFun` and `IDivFun`? I can update the PR tomorrow if people think this is ok.

**Comment by jakebolewski** [comment]
Those names seem better.

**Comment by lindahua** [comment]
Since this is just a minor change. I will merge this tomorrow, if there's no objection.

**Comment by timholy** [comment]
I'm not sure if these two PRs affect each other in any way, but you might want to note the candidate introduction of `GenericNFunc` in #12292.

I suspect there will be some who would be happy about avoiding `@generated` functions, which this PR does. If we also add `DotAddFun` and friends, we might not even need `GenericNFunc` (at least, for those particular functions).

**Comment by lindahua** [comment]
I think #12292 can be addressed using `Func` (without the need of introducing `GenericNFunc`). What's probably needed over that is some methods that accept input types and yield output type (such methods can be defined on sub-types of `Func`).

**Comment by timholy** [comment]
Yes, if we only want to cover a fixed list of operations, indeed we can just use manually-defined functors rather than going the parametric route.

**Comment by lindahua** [comment]
From the discussion in #12357, it seems less controversial to just merge this and stay with this predefined list of functors. Then, we will wait for #10269 to land.

**Comment by timholy** [comment]
Likewise, I'll wait on #12292 until this merges, and make use of it rather than introducing `GenericNFunc`.

We'll need versions of `.*` as well as `*`---do you want to add them here, or should I add them in #12292?

**Comment by lindahua** [comment]
You may add a functor for `.*` in #12292 if needed.

**Comment by simonbyrne** [comment]
Why not add a parametric `Dot{F}` functor?

**Comment by yuyichao** [comment]
> Why not add a parametric `Dot{F}` functor?

At least my objection for adding something parametric on a symbol defined in `Base` is [that](https://github.com/JuliaLang/julia/issues/12357#issuecomment-125791661),

1. We expect the function type overhaul to solve all these problems so adding these types is more or less a temporary solution.

2. Defining these types are relatively easy to do so the user can define them even if base julia does not provide them

3. Specialize on a symbol in base breaks the namespace. A good API should either be specific (like `AddFun` etc) or truly generic (e.g. it should work for user defined functions). Something in the middle will be really confusing.

**Comment by simonbyrne** [comment]
I didn't mean for it to be symbol based: I meant use existing functors as parameters, eg  `Dot{AddFun}`.  But you're right in that I'm not sure in what it actually buys us.

**Comment by timholy** [comment]
I wonder whether @simonbyrne was asking whether `.*` should correspond to `Dot{MulFun}` rather than `DotMulFun`. See https://github.com/JuliaLang/julia/blob/db8b4eef850e2682b16a5d8ffda2109f79df09bd/base/functors.jl#L43-L98. But I'm not sure it would save much, unless you have a simple generic way of converting `call(::MulFun, x, y) = x * y` into `call(::DotMulFun, x, y) = x .* y`?

**Comment by yuyichao** [comment]
> I meant use existing functors as parameters, eg `Dot{AddFun}`.

This does sound more reasonable.

> But I'm not sure it would save much, unless you have a simple generic way of converting `call(::MulFun, x, y) = x * y` into `call(::DotMulFun, x, y) = x .* y`?

But, yeah, this is why I didn't think this is what you meant...

**Comment by StefanKarpinski** [comment]
Maybe somethign like this:

```jl
call{F<:ScalarFunctor}(Dot{F}, v::Vector, w::Vector) = [F(v[i],w[i]) for i=1:length(v)]
```

but, you know the actual general version (probably using broadcast).

**Pull request merged**
