### PR TITLE
WIP: Backports 1.2.0 rc2

### LINKED ISSUE #28966: `import Distributed; Distributed.@everywhere x = 2` does not work
This works fine:

```julia
using Distributed; @everywhere x = 2
```

but

```julia
import Distributed; Distributed.@everywhere x = 2
# ERROR: LoadError: UndefVarError: @everywhere not defined
```

gives an error.

### LINKED ISSUE #30653: Memory leak with function redefinition
This code takes less than a minute to fill the 64GB of my Linux machine:

```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

julia> for i in 1:100
           @eval function foo()
               [fill(1.0, 2_000_000) for _ in 1:100]
               nothing
           end
           @time @eval foo()
           # GC.gc()   # uncomment this line to fix the issue
       end
```

EDIT: simplified code

### LINKED ISSUE #31903: PCRE initialization error on alpine
I get the following error on alpine:
```
WARNING: Error during initialization of module PCRE:
ErrorException("could not load library "libpcre2-8"
Error loading shared library libpcre2-8.so: No such file or directory")
fatal: error thrown and no exception handler available.
InitError(mod=:Sys, error=ErrorException("could not load library "libpcre2-8"
Error loading shared library libpcre2-8.so: No such file or directory"))
rec_backtrace at /julia-source/src/stackwalk.c:94
jl_throw at /julia-source/src/task.c:210
jl_module_run_initializer at /julia-source/src/toplevel.c:81
_julia_init at /julia-source/src/init.c:854
main at /julia-source/ui/repl.c:211
__libc_start_main at /lib/ld-musl-x86_64.so.1 (unknown line)
```
which happens after packing a tarball with `make binary-dist` and then unpacking. Julia runs perfectly fine in the build directory.

Dockerfile:
```
FROM alpine:3.9.3
RUN apk add --update git make tar gcc python gfortran g++ perl
WORKDIR /julia-source
RUN git clone --progress https://github.com/JuliaLang/julia.git .
RUN echo 'override USE_BINARYBUILDER_UNWIND=0' >> Make.user
RUN make -j4
RUN make release
RUN make binary-dist
RUN mkdir -p /julia && tar -C /julia --strip-components=1 -xzf julia*.tar.gz
CMD ["/julia/bin/julia"]
```

### LINKED ISSUE #32121: Writing a macro generates code utilizing NamedTuple whose value is calculated
I'm writing a macro tha packs it's parameter and @__FILE__ into a NamedTuple and push it into a Vector, like this:

```julia
testvec=Vector{NamedTuple{(:f,:s),Tuple{Int,String}}}()
# push!(testvec,(f=0,s="abc"))
macro testm(a)
    return quote
        b=a+1
        push!(testvec,$(esc(
            (f=b,s=@__FILE__)
        )))
    end
end
@testm 2
```

My think is to try avoiding other ways than esc to prevent `f` and `s` from being renamed, or to make b work in escaped environment. However I tried `$(esc(b))=a+1` and other escape forms, with none of them succeeded.

Any suggestions?

### LINKED ISSUE #32213: 1.2: SparseArrays commits type piracy in override of copy
The following is an instance of type-piracy:

https://github.com/JuliaLang/julia/blob/7b18a3043b1e0ea73e41e43930c9d9b828a3b08b/stdlib/SparseArrays/src/sparseconvert.jl#L80

It was introduced by @KlausC in https://github.com/JuliaLang/julia/commit/7a75d6bc33808ba1f32f50d994f9481f8f7ff19b

### LINKED ISSUE #32325: Defining a struct with an outer constructor in local scope gives bad error
```jl
let
    struct a end
    a(b) = a()
end
```

gives

```
ERROR: syntax: Slot objects should not occur in an AST
```

Reported in https://discourse.julialang.org/t/outer-constructor-in-testset/25318.

### LINKED ISSUE #32386: Illegal instruction on Julia v1.2-rc1 (regression)
On Julia v1.2-rc1 and v1.3.0-DEV.433 (2019-06-20), we get an `Illegal instruction` error with [SolidStateDetectors](https://github.com/JuliaPhysics/SolidStateDetectors.jl):

```
(v1.2) pkg> add TypedTables#master SolidStateDetectors
(v1.2) pkg> test SolidStateDetectors
   Testing SolidStateDetectors
 Resolving package versions...
 [...]
Unreachable reached at 0x7f75351968fa

signal (4): Illegal instruction
in expression starting at [...]/packages/SolidStateDetectors/7T4zz/test/runtests.jl:8
construct_semiconductor at [...]/packages/SolidStateDetectors/7T4zz/src/SolidStateDetector/SolidStateDetector.jl:72
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2197
construct_objects at [...]/packages/SolidStateDetectors/7T4zz/src/SolidStateDetector/SolidStateDetector.jl:86
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2197
[...]
```

Note: Needs TypedTables#master until a new version of TypedTables is released (see FugroRoames/TypedTables.jl#52).

On Julia v1.1.1 all is fine.

Not sure if this is related to #32222 - it also happens with the current nightly though, which has #32222 fixed.

We've (@oschulz, @lmh91, @hervasa2) run into this on Ubuntu 16, Ubuntu 19, CentOS-7 and OS-X, so doesn't seem to be OS-related.

### LINKED ISSUE #32465: Internal error: encountered unexpected error in runtime: TypeError
I have run into an internal error with Julia 1.2.0-rc1. It can be reduced with

```
]dev git@github.com:madsjulia/LinearAdjoints.jl.git
]dev git@github.com:madsjulia/FiniteVolume.jl.git
]test FiniteVolume
```

The first handful of lines of the error message are below. An extended version of this error message seems to be repeated many times during the tests. The tests (which take about a minute on my laptop) run to completion and pass despite the error. The error does not occur with Julia 1.1.1.

```
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type, got=P)
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:219
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:429
jl_type_error_rt at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:118
jl_type_error at /Users/julia/buildbot/worker/package_macos64/build/src/rtutils.c:125
jl_f_issubtype at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:411
⊑ at ./compiler/typelattice.jl:175
tmerge at ./compiler/typelimits.jl:286
getfield_tfunc at ./compiler/tfuncs.jl:763
getfield_tfunc at ./compiler/tfuncs.jl:668
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1606 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:563
builtin_tfunction at ./compiler/tfuncs.jl:1365
builtin_tfunction at ./compiler/tfuncs.jl:1279 [inlined]
abstract_call at ./compiler/abstractinterpretation.jl:632
abstract_call at ./compiler/abstractinterpretation.jl:605
abstract_eval_call at ./compiler/abstractinterpretation.jl:844
abstract_eval at ./compiler/abstractinterpretation.jl:914
typeinf_local at ./compiler/abstractinterpretation.jl:1171
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1227
typeinf at ./compiler/typeinfer.jl:12
typeinf_edge at ./compiler/typeinfer.jl:482
abstract_call_method at ./compiler/abstractinterpretation.jl:376
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:93
abstract_call at ./compiler/abstractinterpretation.jl:815
abstract_call at ./compiler/abstractinterpretation.jl:605
```

### LINKED ISSUE #32499: Change in, presumably, macro expansion in 1.2 vs 1.1
Opening this as a dedicated issue so it is easier to track.

On the 1.2-RC2 branch, StochasticModels errors and can be reprod with:

```jl
using StochasticModels

farmer_model = @stochastic_model begin
           @stage 1 begin
           end
           @stage 2 begin
               @uncertain ξ::YieldScenario = begin end
           end
       end
```
on the 1.2-RC2 branch it erros with 

```jl
ERROR: UndefVarError: YieldScenario not defined
```

while it runs without error on 1.1.

When I run `@macroexpand1` on this I get

```jl
@scenario YieldScenario = begin
        end
StochasticPrograms.StochasticModel(StageParameters(), StageParameters()) do sp
    @stage 1 sp = begin
            end
    @stage 2 sp = @uncertain(ξ::YieldScenario = begin
                    end)
end
```

and this executes correctly. So not sure what is happening. @JeffBezanson, perhaps you could take a look.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #31933 - Unconditionally append lib/julia to rpath, fixes #31903.
- [x] #31946 - Fix for optind in getopt on musl libc.
- [x] #32072 - Two fixes to win32 cross compilation
- [x] #32139 - fix #32121, macro hygiene bug in named tuples
- [x] #32144 - Fully qualify at-everywhere, fixes #28966.
- [x] #32161 - Fix unsigned wrap around in lpad/rpad/string allocation
- [x] #32192 - Bump OpenBLAS BB tarballs to `v0.3.5-2`, to fix FreeBSD
- [x] #32219 - fix LibGit2 test: unknown repo now returns error instead of EAUTH
- [x] #32260 - Remove internal sort from `getipaddrs`
- [x] #32041 - RFC: use `AbstractMatrix` as the eltype of `Symmetric` for array of arrays
- [x] #32255 - readdlm(bytearray) shouldn't modify bytearray
- [x] #32266 - Remove copy(::SubArray) definition from SparseArrays, fixes #32213.
- [x] #32169 - fix build with JULIA_ENABLE_THREADING==0
- [x] #32281 - Bump Pkg to v1.2.0-rc2.
- [x] #31499 - fixes for getindex tab-completion
- [x] #32326 - fix #32325, struct plus outer ctor inside `let`
- [x] #32351 - Fix tryparse for invalid Chars
- [x] #32383 - Add missing test dependency on Random to Statistics
- [x] #32375 -  Fix -Symmetric for Bool or JuMP.VariableRef
- [x] #32356 - codegen,tbaa: fix array isassigned tbaa information
- [x] #32431 - Fix Distributed.head_and_tail
- [x] #32425 - fix #32386, type intersection bug in var bounds
- [x] #32428 - fix #30653, call `malloc_trim` sometimes
- [x] #32412 - Prevent download on windows picking up rogue curl executable
- [x] #32464 - fix the fix for #32121, more named tuple macro hygiene
- [x] #32457 - bug fixed in read_to_buffer 
- [x] #32494 - fix #32465, inference of splatting unionall NamedTuple types
- [x] #32512  - fix #32499, regression in struct expr in assignment rhs #32512

Non-merged PRs with backport label:
- [ ] #32512 - fix #32499, regression in struct expr in assignment rhs
- [ ] #32327 - bug fixes in matrix log
- [ ] #32271 - [Statistics] fix type determination in corm
- [ ] #32145 - fix bug in block renaming for dead code elimination

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.2")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32270#issuecomment-503584229) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9994011a546cd64de2cff55409ab7a7accfa643e/c670f60_vs_3fcb168/report.md). cc @ararslan

**Comment by KristofferC** [comment]
Windows seems to fail with:

```
Error in testset download:
Test Failed at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\download.jl:27
  Expression: m.captures[1] == "https://httpbin.org/get?test='^'"
   Evaluated: "https://httpbin.org/get?test=^" == "https://httpbin.org/get?test='^'"
```

Anyone seen that before?

**Comment by musm** [comment]
Showed up in several failing PRs. There's only two possibilities (1) is that downloads are picking up a rogue `curl` and (2) something is messed up with powershell on the build bots. 

For (1) I opened PR https://github.com/JuliaLang/julia/pull/32412 to test if that's the cause.

**Comment by ararslan** [comment]
PkgEval failures (each link is to the corresponding log):
- [ ] [BSON](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-bson-log)
- [ ] [BedgraphFiles](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-bedgraphfiles-log)
- [ ] [Cassette](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-cassette-log)
- [ ] [Cbc](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-cbc-log)
- [ ] [Cubature](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-cubature-log)
- [ ] [DocumentFunction](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-documentfunction-log)
- [ ] [Documenter](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-documenter-log)
- [ ] [EponymTuples](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-eponymtuples-log)
- [ ] [InfoZIP](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-infozip-log)
- [ ] [Latexify](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-latexify-log)
- [ ] [Libtask](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-libtask-log)
- [ ] [LinearMaps](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-linearmaps-log)
- [ ] [Mixers](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-mixers-log)
- [ ] [Mosek](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-mosek-log)
- [ ] [OSQP](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-osqp-log)
- [ ] [PkgTemplates](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-pkgtemplates-log)
- [ ] [PriorityChannels](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-prioritychannels-log)
- [ ] [ResumableFunctions](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-resumablefunctions-log)
- [ ] [Revise](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-revise-log)
- [ ] [StaticLint](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-staticlint-log)
- [ ] [Statistics](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-statistics-log)
- [ ] [Strided](https://gist.github.com/ararslan/cac4e2bac4cbb4445b4967605ce0f650#file-strided-log)

Looks like a number of these are failures when loading undeclared dependencies.

**Comment by fredrikekre** [comment]
A lot of packages (the ones I marked) are missing (test) dependencies in their `Project.toml` files, and they fail now cause Pkg is fixed. Of course, it might be other failures in those packages that are hidden by the fact that they are not run due to dependency issues.

**Comment by ararslan** [comment]
Statistics will just need #32383 backported. The others will need PRs and new patch releases I guess.

**Comment by KristofferC** [comment]
The EponymTuples seems real and the MWE is

```jl
var_and_value_form(ex::Symbol) = (e = esc(ex); :($(e) = $(e)))

macro eponymtuple(args::Vararg{Symbol})
    forms = map(var_and_value_form, args)
    Expr(:tuple, forms...)
end

@macroexpand @eponymtuple(a, b)
```

which on 1.1 gives

```
:((a = a, b = b))
```

while on 1.2 gives

```
:((a = (a = a), b = (b = b)))
```

Perhaps you can look at this @JeffBezanson

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.2")`

**Comment by JeffBezanson** [comment]
#32464 should fix EponymTuples

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32270#issuecomment-507297333) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ce814e1207091fd052f264ac694e06e7efb84349/bfb9d70_vs_3fcb168/report.md). cc @ararslan

**Comment by ararslan** [comment]
New PkgEval run:

- [ ] [AlgebraicMultigrid](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-algebraicmultigrid-log)
- [ ] [ArnoldiMethod](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-arnoldimethod-log)
- [ ] [BSON](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-bson-log)
- [ ] [BedgraphFiles](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-bedgraphfiles-log)
- [ ] [BitBasis](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-bitbasis-log)
- [ ] [BlackBoxOptim](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-blackboxoptim-log)
- [ ] [Cassette](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-cassette-log)
- [ ] [Cbc](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-cbc-log)
- [ ] [Cubature](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-cubature-log)
- [ ] [Cumulants](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-cumulants-log)
- [ ] [DataFrames](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-dataframes-log)
- [ ] [Discretizers](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-discretizers-log)
- [ ] [DistQuads](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-distquads-log)
- [ ] [DistributedArrays](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-distributedarrays-log)
- [ ] [Documenter](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-documenter-log)
- [ ] [EponymTuples](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-eponymtuples-log)
- [ ] [FeatherLib](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-featherlib-log)
- [ ] [GLMNet](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-glmnet-log)
- [ ] [GeometryTypes](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-geometrytypes-log)
- [ ] [HMMBase](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-hmmbase-log)
- [ ] [HypothesisTests](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-hypothesistests-log)
- [ ] [InfoZIP](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-infozip-log)
- [ ] [InterpolatedRejectionSampling](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-interpolatedrejectionsampling-log)
- [ ] [Jacobi](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-jacobi-log)
- [ ] [Latexify](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-latexify-log)
- [ ] [Libtask](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-libtask-log)
- [ ] [LinearFractional](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-linearfractional-log)
- [ ] [LocalFunctionApproximation](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-localfunctionapproximation-log)
- [ ] [LsqFit](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-lsqfit-log)
- [ ] [MDDatasets](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-mddatasets-log)
- [ ] [MIDI](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-midi-log)
- [ ] [MLDataPattern](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-mldatapattern-log)
- [ ] [MatrixNetworks](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-matrixnetworks-log)
- [ ] [Millboard](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-millboard-log)
- [ ] [Mixers](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-mixers-log)
- [ ] [Mosek](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-mosek-log)
- [ ] [MultivariateMoments](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-multivariatemoments-log)
- [ ] [NLPModelsJuMP](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-nlpmodelsjump-log)
- [ ] [NLopt](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-nlopt-log)
- [ ] [NamedArrays](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-namedarrays-log)
- [ ] [NaturallyUnitful](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-naturallyunitful-log)
- [ ] [Nullables](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-nullables-log)
- [ ] [OSQP](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-osqp-log)
- [ ] [PkgTemplates](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-pkgtemplates-log)
- [ ] [PlanarConvexHulls](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-planarconvexhulls-log)
- [ ] [PriorityChannels](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-prioritychannels-log)
- [ ] [QuantumLattices](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-quantumlattices-log)
- [ ] [ResumableFunctions](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-resumablefunctions-log)
- [ ] [Revise](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-revise-log)
- [ ] [RingBuffers](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-ringbuffers-log)
- [ ] [Rotations](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-rotations-log)
- [ ] [SimpleTraits](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-simpletraits-log)
- [ ] [StaticLint](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-staticlint-log)
- [ ] [SteamTables](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-steamtables-log)
- [ ] [StochasticPrograms](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-stochasticprograms-log)
- [ ] [Strided](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-strided-log)
- [ ] [SymEngine](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-symengine-log)
- [ ] [TimeSeries](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-timeseries-log)
- [ ] [Tracking](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-tracking-log)
- [ ] [UnicodePlots](https://gist.github.com/ararslan/57dcc2aa3a383cc58db163c42dfa2ba6#file-unicodeplots-log)

On this branch, 1336 packages were skipped due to failing dependencies, compared to 1149 packages skipped with 1.1.1.

**Comment by KristofferC** [comment]
Things that needs looking into:

DistributedArrays:

```
test construct Array from (Sub)DArray: Error During Test at /root/.julia/packages/DistributedArrays/h240R/test/darray.jl:216
  Test threw exception
  Expression: vec(S5) == D[1, 1:4]
  StackOverflowError:
  Stacktrace:
   [1] ==(::SubArray{Float64,1,DArray{Float64,2,Array{Float64,2}},Tuple{Int64,UnitRange{Int64}},false}, ::Array{Float64,1}) at /root/.julia/packages/DistributedArrays/h240R/src/darray.jl:430
   [2] ==(::SubArray{Float64,1,DArray{Float64,2,Array{Float64,2}},Tuple{Int64,UnitRange{Int64}},false}, ::Array{Float64,1}) at /root/.julia/packages/DistributedArrays/h240R/src/darray.jl:431 (repeats 65287 times)
   [3] ==(::Array{Float64,1}, ::SubArray{Float64,1,DArray{Float64,2,Array{Float64,2}},Tuple{Int64,UnitRange{Int64}},false}) at /root/.julia/packages/DistributedArrays/h240R/src/darray.jl:436
   [4] eval_test(::Expr, ::Expr, ::LineNumberNode, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:244
   [5] top-level scope at /root/.julia/packages/DistributedArrays/h240R/test/darray.jl:216
   [6] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [7] top-level scope at /root/.julia/packages/DistributedArrays/h240R/test/darray.jl:186
   [8] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [9] top-level scope at /root/.julia/packages/DistributedArrays/h240R/test/darray.jl:183
```

MIDI:

```
  Test threw exception
  Expression: (MIDI.Note(60, 96, 0, 5) + 2).pitch == 62
  MethodError: no method matching +(::Note, ::Int64)
  Closest candidates are:
    +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
    +(!Matched::Complex{Bool}, ::Real) at complex.jl:293
    +(!Matched::Missing, ::Number) at missing.jl:94
    ...
  Stacktrace:
   [1] top-level scope at /root/.julia/packages/MIDI/WTQq4/test/note.jl:3
   [2] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [3] top-level scope at /root/.julia/packages/MIDI/WTQq4/test/note.jl:3
   [4] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [5] top-level scope at /root/.julia/packages/MIDI/WTQq4/test/note.jl:2
```

**Comment by mbauman** [comment]
DistributedArrays just needs a new tag.

**Comment by KristofferC** [comment]
> On this branch, 1336 packages were skipped due to failing dependencies, compared to 1149 packages skipped with 1.1.1.

DataFrames failing is pretty bad. Again, I think we should just test dependencies anyway, even if their parent fail.

**Comment by JeffBezanson** [comment]
MIDI: the `+` method was removed without removing the test; not our fault.

**Comment by c42f** [comment]
I believe the NaturallyUnitful problem is https://github.com/MasonProtter/NaturallyUnitful.jl/issues/5.

**Comment by KristofferC** [comment]
Matrixnetwork passses locally multiple times on this branch.

**Comment by KristofferC** [comment]
StochasticModels error can be reprod with:

```jl
farmer_model = @stochastic_model begin
           @stage 1 begin
           end
           @stage 2 begin
               @uncertain ξ::YieldScenario = begin end
           end
       end
```
on this branch it erros with 

```jl
ERROR: UndefVarError: YieldScenario not defined
```

When I run `@macroexpand1` on this I get

```
    @scenario YieldScenario = begin
            end
    StochasticPrograms.StochasticModel(StageParameters(), StageParameters()) do sp
        @stage 1 sp = begin
                end
        @stage 2 sp = @uncertain(ξ::YieldScenario = begin
                        end)
    end
```

and this executes correctly. So not sure what is happening. @JeffBezanson, perhaps you could take a look.

**Comment by ecsx1** [comment]
Julia 1.2.0 rc1 doesn't build on my system.
But there are 2 simple commits (already merged on master) that make it work.
Any chance to apply those for 1.2.0 rc2? They fix real bugs.

https://github.com/JuliaLang/julia/pull/31933
https://github.com/JuliaLang/julia/pull/31946

**Comment by ararslan** [comment]
Including those commits here seems reasonable to me, so I've added the backport 1.2 label to the PRs. I assume they should be backported to 1.0 as well?

**Comment by ararslan** [comment]
The macOS buildbot seems to be consistently failing, but it works on Travis, so it's probably fine. Similarly, AppVeyor is failing but the Windows buildbots are working. The GC analysis build fails because the infrastructure for that is not present on the `release-1.2` branch, only on master.

**Pull request merged**
