### PR TITLE
docs: fix `Base.include` docstring signature

### PR DESCRIPTION
**Pull request by mroavi**
The `m::Module` argument is not optional.

### CODE REVIEW

**Comment by Tokazama** [comment]
You can specify just the `path` argument without `m`.

**Comment by inkydragon** [comment]
> You can specify just the path argument without m.

Only for `include`, not `Base.include`.

```julia
julia> methods(include)
# 2 methods for generic function "include":
[1] include(mapexpr::Function, fname::AbstractString) in Base.MainInclude at client.jl:448
[2] include(fname::AbstractString) in Base.MainInclude at client.jl:449

julia> methods(Base.include)
# 2 methods for generic function "include":
[1] include(mod::Module, _path::AbstractString) in Base at Base.jl:416
[2] include(mapexpr::Function, mod::Module, _path::AbstractString) in Base at Base.jl:417

julia> versioninfo()
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
```

**Review by inkydragon — APPROVED** [review]
@ViralBShah LGTM.

**Comment by fredrikekre** [comment]
I don't think the intention here is was to document Base.include specifically. The content of the docstring even mentions:

> Every module (except those defined with [`baremodule`](@ref)) has its own definition of `include` omitting the `m` argument, which evaluates the file in that module.

**Comment by ViralBShah** [comment]
Now that I think about it, I don't really understand what that statement means. 

Do we need to revert this? It would be good to update that statement to be a bit clearer.

**Comment by inkydragon** [comment]
- `Base.include` != `include`

*t.jl*
```
export var
var = "exported_var"
```

```jl
julia> module TestInc
       include("V:/t.jl")
       end
Main.TestInc

julia> var
ERROR: UndefVarError: var not defined

julia> TestInc.var
"exported_var"

julia>

julia> module TestInc2
       Base.include("V:/t.jl")
       end
ERROR: MethodError: no method matching include(::String)
Closest candidates are:
  include(::Module, ::AbstractString) at C:\Users\woclass\.julia\juliaup\julia-1.7.3+0~x64\share\julia\base\Base.jl:418
  include(::Function, ::Module, ::AbstractString) at C:\Users\woclass\.julia\juliaup\julia-1.7.3+0~x64\share\julia\base\Base.jl:419
Stacktrace:
 [1] top-level scope
   @ REPL[4]:2
```

> Every module (except those defined
  with baremodule) has its own definition of include omitting the m argument, which evaluates the file in that module.

I guess this sentence refers to the following definitions:

`[2] include(fname::AbstractString) in Base.MainInclude at client.jl:449`

Or there is an implicit function definition.


> It would be good to update that statement to be a bit clearer.

We could add a `(see [include(fname::AbstractString)](@ref))`

**Comment by fredrikekre** [comment]
> Base.include != include

Yes I know, I meant that the intention with the docstring was probably to document include in general.

**Pull request merged**
