### PR TITLE
Add checksums for LibCURL

### PR DESCRIPTION
**Pull request by DilumAluthge**
These checksums were deleted in https://github.com/JuliaLang/julia/pull/38963.

However:
1. When I run `make` locally, these checksums are generated.
2. If you look in the [`deps/checksums/curl`](https://github.com/JuliaLang/julia/blob/master/deps/checksums/curl) file, these checksums are not located there.

### CODE REVIEW

**Comment by KristofferC** [comment]
> When I run make locally, these checksums are generated.

Not for me. Have you cleaned out old deps stuff from your repo?

**Comment by DilumAluthge** [comment]
Yep, I even tried in a brand-new clone and it still generates the checksums.

This is on macOS.

**Comment by DilumAluthge** [comment]
I get this with a brand-new clone on both macOS and Linux.

**Comment by KristofferC** [comment]
Yeah, I managed to get it now as well after a `git clean -fdX`.

Perhaps these two lines should rather be added back: https://github.com/JuliaLang/julia/pull/39625/files#diff-c5e29ac5eae5352c7cd703597b517a569d2a4fee6684dc03f54e891e6883854eL1-L2

**Comment by DilumAluthge** [comment]
> Perhaps these two lines should rather be added back: https://github.com/JuliaLang/julia/pull/39625/files#diff-c5e29ac5eae5352c7cd703597b517a569d2a4fee6684dc03f54e891e6883854eL2
> 
> Or since this is for jll, maybe it is better to have them in a separate file like in this PR (it seems we do for the other stdlibs).

Good question. I don't feel strongly either way. @vtjnash since you did the reorganization of the checksums recently, which one would you prefer?

**Comment by vtjnash** [comment]
Either is fine

**Pull request merged**
