### PR TITLE
Expand ssl certificate file search parameters

### PR DESCRIPTION
**Pull request by staticfloat**
We just need to search for more variations on the same name in some cases.

### CODE REVIEW

**Comment by tkelman** [comment]
I think the approach of overriding the environment variable may have broken shelling out to curl from the binaries... see e.g. http://pkg.julialang.org/logs/Requests_0.6.log

**Comment by staticfloat** [comment]
I've added a slightly more intelligent environment variable overriding here, let's see if it works.

**Comment by davidanthoff** [comment]
This crashes with a new error on WSL (Windows Subsystem for Windows, aka Bash on Ubuntu on Windows):
````
davidanthoff@DANTHOFF-HOME:~/source/julia$ ./julia
fatal: error thrown and no exception handler available.
Base.InitError(mod=:LibGit2, error=Base.MethodError(f=Base.LibGit2.#get(), args=(Base.EnvHash(), "SSL_CERT_DIR", "")))
rec_backtrace at /home/davidanthoff/source/julia/src/stackwalk.c:84
record_backtrace at /home/davidanthoff/source/julia/src/task.c:238
jl_throw at /home/davidanthoff/source/julia/src/task.c:560
jl_method_error_bare at /home/davidanthoff/source/julia/src/gf.c:1098
jl_method_error at /home/davidanthoff/source/julia/src/gf.c:1115
jl_apply_generic at /home/davidanthoff/source/julia/src/gf.c:1852
__init__ at ./libgit2/libgit2.jl:543
unknown function (ip: 0x7fe82054f748)
jl_call_method_internal at /home/davidanthoff/source/julia/src/julia_internal.h:239 [inlined]
jl_apply_generic at /home/davidanthoff/source/julia/src/gf.c:1861
jl_apply at /home/davidanthoff/source/julia/src/julia.h:1378 [inlined]
jl_module_run_initializer at /home/davidanthoff/source/julia/src/toplevel.c:83
_julia_init at /home/davidanthoff/source/julia/src/init.c:702
julia_init at /home/davidanthoff/source/julia/src/task.c:289
main at /home/davidanthoff/source/julia/ui/repl.c:247
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4013cf)
davidanthoff@DANTHOFF-HOME:~/source/julia$
````

**Comment by tkelman** [comment]
that's some iffy name shadowing pun there...

**Comment by tkelman** [comment]
Is `.crt` a different format than `.pem`? On Ubuntu 14.04 and 16.04 I see a `/usr/lib/ssl/certs/ca-certificates.crt` but none of the three options currently checked here.

**Comment by tkelman** [comment]
unanswered question above and we may need to add more of these, but let's see if this helps the nightlies

**Comment by staticfloat** [comment]
Sorry,

`.crt` and `.pem` are generally not different file formats, so we're good on that front.  On my Ubuntu 14.04 machine, I saw a `cert.pem` which was a symlink to the `ca-certificates.crt` file that you describe.  Let's see what machines this breaks on, then we can add more search locations.

**Comment by tkelman** [comment]
Looking at the PkgEval run that's going right now (which does include this commit), this looks like it's still causing problems with shelling out to curl.

**Comment by staticfloat** [comment]
I don't think the DataFrames failures we're seeing is a curl shelling problem, I think it's a LibGit2 problem.  I'm not sure why, but this call is hanging indefinitely:

```
Base.LibGit2.clone("https://github.com/JuliaStats/DataFrames.jl.git", "/tmp/DataFrames_bare_cb", isbare = true, remote_cb = LibGit2.mirror_cb())
```

If we omit the `remote_cb` callback parameter, it works fine, but instrumenting the callback shows that the callback finishes just fine, so it must be some effect that the callback is having further down the line.  @wildart @jakebolewski, do either of you have any ideas why this would be causing problems?

**Comment by tkelman** [comment]
@staticfloat we have https://github.com/JuliaLang/julia/issues/18871 open, so let's move that part there - pardon my initial misdiagnosis, I'll check the logs if there's anything other than that still going on.

**Pull request merged**
