### PR TITLE
DO NOT MERGE: Nanosoldier testing

### PR DESCRIPTION
**Pull request by ararslan**
Hardhats and proper eye protection must be worn in this area at all times.

Nanosoldier is in the process of being fixed and I'm opening this to do some testing without hijacking any more of Matt's PRs.

Whatever you do, **do not** merge this.

[ci skip]

### CODE REVIEW

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-415573342):
```
KeyError(Nanosoldier [80b32da4-50ac-5880-b45e-eff550e7de25])
```
cc @ararslan

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-415588547):
```
KeyError(Nanosoldier [80b32da4-50ac-5880-b45e-eff550e7de25])
```
cc @ararslan

**Comment by ararslan** [comment]
Thanks to Valentin we've determined that a slight modification in setup caused us to hit a bug where packages loaded before `addprocs` aren't reloaded on the remote workers with later `using`s. I've worked around that in the setup, so let's investigate: @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
Aforementioned bug: #28859

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-415609969):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1dd8b106c00ee9327e2da92ffcef01889756a821/8027355_vs_d55b044/report.md)
cc @ararslan

**Comment by ararslan** [comment]
```
fatal: error thrown and no exception handler available.
ErrorException("Task cannot be serialized")
rec_backtrace at /home/nanosoldier/workdir/tmpmiB2ji/src/stackwalk.c:94
record_backtrace at /home/nanosoldier/workdir/tmpmiB2ji/src/task.c:249
jl_throw at /home/nanosoldier/workdir/tmpmiB2ji/src/task.c:580
jl_error at /home/nanosoldier/workdir/tmpmiB2ji/src/rtutils.c:41
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:293
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:285 [inlined]
jl_serialize_module at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:229
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:285
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302
jl_serialize_value_ at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:302 [inlined]
jl_serialize_module at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:229
jl_serialize_module at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:221
jl_save_system_image_to_stream at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:1272
jl_create_system_image at /home/nanosoldier/workdir/tmpmiB2ji/src/staticdata.c:1377
jl_write_compiler_output at /home/nanosoldier/workdir/tmpmiB2ji/src/precompile.c:68
jl_atexit_hook at /home/nanosoldier/workdir/tmpmiB2ji/src/init.c:233
main at /home/nanosoldier/workdir/tmpmiB2ji/ui/repl.c:234
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/nanosoldier/workdir/tmpmiB2ji/usr/bin/julia (unknown line)
make[1]: *** [/home/nanosoldier/workdir/tmpmiB2ji/usr/lib/julia/sys-o.a] Error 1
make: *** [julia-sysimg-release] Error 2
```

**Comment by KristofferC** [comment]
Hmm, try turn off the precompile generator (we should probably have a make flag for that).

Just put `exit(0)` at the top of https://github.com/JuliaLang/julia/blob/master/contrib/generate_precompile.jl.

**Comment by ararslan** [comment]
Looks like the compiler toolchain installed on the Nanosoldier workers is really old, so I've done a round of software updates that hopefully should do good things. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
Sorry just saw your comment, @KristofferC. That will be nontrivial (it will have to be done programmatically in the Nanosoldier code) but doable.

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-415661551):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6a2b0c023872bf40723dee3347b70a197ac4ad60/8027355_vs_d55b044/report.md)
cc @ararslan

**Comment by ararslan** [comment]
So this looks not great:
```
configure: WARNING: Continuing even with errors mentioned immediately above this line.
configure: WARNING: ==========================================================
configure: WARNING: 'gmp.h' and 'libgmp' seem to have different versions or
configure: WARNING: we cannot run a program linked with GMP (if you cannot
configure: WARNING: see the version numbers above). A cause may be different
configure: WARNING: GMP versions with different ABI's or the use of --with-gmp
configure: WARNING: or --with-gmp-include with a system include directory
configure: WARNING: (such as /usr/include or /usr/local/include).
configure: WARNING: However since we can't use 'libtool' inside the configure,
configure: WARNING: we can't be sure. See 'config.log' for details.
configure: WARNING: CC="ccache gcc -m64"
configure: WARNING: CFLAGS="-Wall -Wmissing-prototypes -Wpointer-arith -g -O2"
configure: WARNING: CPPFLAGS=" -I/home/nanosoldier/workdir/tmp3yjPDD/usr/include"
configure: WARNING: LDFLAGS=" -Wl,-rpath,'$$ORIGIN' -Wl,-z,origin -L/home/nanosoldier/workdir/tmp3yjPDD/usr/lib"
configure: WARNING: LIBS="-lgmp "
configure: WARNING: Temporary LD_RUN_PATH was "/home/nanosoldier/workdir/tmp3yjPDD/usr/lib".
configure: WARNING: ==========================================================
```
likely a product of software updates.

The more troubling thing here is the new OpenBLAS build error:
```
/tmp/ccIoTiWO.s: Assembler messages:
/tmp/ccIoTiWO.s:60: Error: operand type mismatch for `vxorps'
make[3]: *** [sdot_k_SKYLAKEX.o] Error 1
make[2]: *** [libs] Error 1
```

**Comment by ararslan** [comment]
@staticfloat said that OpenBLAS build error is caused by using an old version of binutils.

**Comment by ararslan** [comment]
I did a thing, maybe it fixed stuff @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
Kristoffer did some stuff that should make Nanosoldier happy.

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-418966607):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`/home/nanosoldier/workdir/tmpUm6l0O/julia -e '
    if VERSION >= v"0.7.0-beta2.203"
        import BaseBenchmarks
        print(dirname(dirname(pathof(BaseBenchmarks))))
    else
        print(Pkg.dir("BaseBenchmarks"))
    end
'`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/15237797627c0bd87b362df3cd2214ee0f56285e/a430839_vs_4c02077/report.md)
cc @ararslan

**Comment by ararslan** [comment]
More info from the server log:
```
[ Info: [Node 2 | 2018-09-06T01:50:20.371]: updating local BaseBenchmarks repo
      From worker 2:    ERROR: https://github.com/JuliaCI/BaseBenchmarks.jl is not a valid packagename
      From worker 2:    Stacktrace:
      From worker 2:     [1] pkgerror(::String) at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:120
      From worker 2:     [2] check_package_name(::String) at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:22
      From worker 2:     [3] iterate at ./generator.jl:47 [inlined]
      From worker 2:     [4] collect(::Base.Generator{Array{String,1},typeof(Pkg.API.check_package_name)}) at ./array.jl:619
      From worker 2:     [5] #add_or_develop#11(::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:mode,),Tuple{Symbol}}}, ::Function, ::Array{String,1}) at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:28
      From worker 2:     [6] #add_or_develop at ./none:0 [inlined]
      From worker 2:     [7] #add_or_develop#10 at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:27 [inlined]
      From worker 2:     [8] #add_or_develop at ./none:0 [inlined]
      From worker 2:     [9] #add#18 at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:68 [inlined]
      From worker 2:     [10] add(::String) at /home/nanosoldier/workdir/tmpUm6l0O/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:68
      From worker 2:     [11] top-level scope at none:0
      From worker 2:    ERROR: ArgumentError: Package BaseBenchmarks not found in current path:
      From worker 2:    - Run `import Pkg; Pkg.add("BaseBenchmarks")` to install the BaseBenchmarks package.
```

**Comment by ararslan** [comment]
Okay I think I've fixed that now. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-418974966):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`git fetch --all --quiet`, ProcessExited(128)) [128]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c7208d8c942ed5e64945905a6714a5d20024a198/a430839_vs_4c02077/report.md)
cc @ararslan

**Comment by KristofferC** [comment]
Can't see anything from the Nanosoldier's posted logs but it is good that it goes through the compilation stage now at least.

**Comment by ararslan** [comment]
The closest thing I see to an error in the server's log is this:
```
     From worker 2:    fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by KristofferC** [comment]
Ok anything else?

Is it from here https://github.com/JuliaCI/Nanosoldier.jl/blob/26d6fe7ca41b00da65bb64d75b4cb29d2cb614e9/src/build.jl#L37.

Can we enable some more logging output in Nanosoldier perhaps?

**Comment by ararslan** [comment]
> Is it from here

Unclear, unfortunately.

> Can we enable some more logging output in Nanosoldier perhaps?

That would be great. I've done a bit of that recently but not enough. Want to take a look at [the Nanosoldier package](https://github.com/JuliaCI/Nanosoldier.jl) and see if there's anywhere that some more verbose output could be useful?

**Comment by KristofferC** [comment]
I think the problem is that `Pkg.add` does not  clone a git repo but it tries to do git operations on it here:

https://github.com/JuliaCI/Nanosoldier.jl/blob/533ee6c310e7877ad2079259b8c5bcb414ad8b50/src/jobs/BenchmarkJob.jl#L295-L296

**Comment by jekbradbury** [comment]
I've seen that particular Git error (`fatal: Not a git repository (or any of the parent directories): .git`) for a couple different reasons, but the one I could figure out was a submodule path bug that exists in fairly old Git versions?

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419154482):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/7b9058eca48d7c9403829ff38ce091316a3477fd/0f32e6f_vs_e5cc750/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Derp. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by KristofferC** [comment]
I can feel it, this is the one!

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419170189):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/534fff3cdb484cee6ee3df3880a75a0825f00d70/0f32e6f_vs_e5cc750/report.md)
cc @ararslan

**Comment by KristofferC** [comment]
> AssertionError: bytesavailable(master) == 0

From https://github.com/JuliaLang/julia/pull/29024, Argh!

**Comment by KristofferC** [comment]
Just want to see if that is consistent

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419202118):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/676214590ff4833e51175130a984d68762e60113/39a6194_vs_88d536a/report.md)
cc @ararslan

**Comment by KristofferC** [comment]
Seems the build went through now at least so @ararslan perhaps you can check what is failing now?

**Comment by ararslan** [comment]
The server log contains
```
      From worker 3:    ERROR: LoadError: ArgumentError: Package Compat not found in current path:
      From worker 3:    - Run `import Pkg; Pkg.add("Compat")` to install the Compat package.
      From worker 3:
      From worker 3:    Stacktrace:
      From worker 3:     [1] require(::Module, ::Symbol) at ./loading.jl:820
      From worker 3:     [2] include at ./boot.jl:317 [inlined]
      From worker 3:     [3] include_relative(::Module, ::String) at ./loading.jl:1041
      From worker 3:     [4] include(::Module, ::String) at ./sysimg.jl:29
      From worker 3:     [5] exec_options(::Base.JLOptions) at ./client.jl:229
      From worker 3:     [6] _start() at ./client.jl:421
      From worker 3:    in expression starting at /home/nanosoldier/workdir/tmpyd0wMF/benchscript.jl:1
```
So Compat isn't getting installed alongside the other dependencies of BaseBenchmarks, I guess? Would having a project file there help?

**Comment by KristofferC** [comment]
Add a `Pkg.add("Compat")` here perhaps https://github.com/JuliaCI/Nanosoldier.jl/blob/3d893b5820f14147574ae73389a0cf118fb69578/src/jobs/BenchmarkJob.jl#L275?

**Comment by ararslan** [comment]
Sure, that's fine. But why would it complain about Compat and not any other dependencies? Or maybe it would if it survived the Compat error?

**Comment by KristofferC** [comment]
Compat and Benchmarktools are used here https://github.com/JuliaCI/Nanosoldier.jl/blob/3d893b5820f14147574ae73389a0cf118fb69578/src/jobs/BenchmarkJob.jl#L334-L376.

No other packages. So what else is there to complain about?

**Comment by ararslan** [comment]
BenchmarkTools and JSON: https://github.com/JuliaCI/Nanosoldier.jl/blob/3d893b5820f14147574ae73389a0cf118fb69578/src/jobs/BenchmarkJob.jl#L353-L354

**Comment by KristofferC** [comment]
Oh, yeah missed that. Any package we want to use need to be added...

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419228511):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/85926b3609cdca3cd82e2f80522bacf465e8ec64/986e815_vs_bda5dd8/report.md)
cc @ararslan

**Comment by ararslan** [comment]
```
ERROR: LoadError: AssertionError: bytesavailable(master) == 0
Stacktrace:
 [1] (::getfield(Main.anonymous, Symbol("##3#7")){String,Base.GenericIOBuffer{Array{UInt8,1}},RawFD,Base.TTY,String})() at /home/nanosoldier/workdir/tmpPxxYNu/contrib/generate_precompile.jl:115
 [2] withenv(::getfield(Main.anonymous, Symbol("##3#7")){String,Base.GenericIOBuffer{Array{UInt8,1}},RawFD,Base.TTY,String}, ::Pair{String,String}, ::Vararg{Pair{String,B} where B,N} where N) at ./env.jl:148
 [3] (::getfield(Main.anonymous, Symbol("##2#6")){Float64,String})(::String, ::IOStream) at /home/nanosoldier/workdir/tmpPxxYNu/contrib/generate_precompile.jl:87
 [4] mktemp(::getfield(Main.anonymous, Symbol("##2#6")){Float64,String}, ::String) at ./file.jl:555
 [5] mktemp at ./file.jl:553 [inlined]
 [6] generate_precompile_statements() at /home/nanosoldier/workdir/tmpPxxYNu/contrib/generate_precompile.jl:73
 [7] top-level scope at /home/nanosoldier/workdir/tmpPxxYNu/contrib/generate_precompile.jl:178
in expression starting at /home/nanosoldier/workdir/tmpPxxYNu/contrib/generate_precompile.jl:4
```

**Comment by ararslan** [comment]
Might be a race condition, @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419253169):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ca07b49a27b5ec37e47f68a58b9ce563a9f72cb7/986e815_vs_bda5dd8/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Same assertion error

**Comment by KristofferC** [comment]
I removed the assertion

@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419447145):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/52e913469d9f2e02b4bf6637dc6cde048e857d12/dd712f2_vs_5c1d4a3/report.md)
cc @ararslan

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by ararslan** [comment]
I THINK THIS MIGHT BE THE ONE

**Comment by Sacha0** [comment]
> I THINK THIS MIGHT BE THE ONE

optimism

**Comment by ararslan** [comment]
Too accurate

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/28857#issuecomment-419530825) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d77f74e97b9d91d7576cf282899ae4be1c6038bd/90c69ef_vs_cfca833/report.md). cc @ararslan

**Comment by ararslan** [comment]
NANOSOLDIER LIVES

**Pull request closed without merging**
