### PR TITLE
Minor fixes to Random.seed! docstring

### PR DESCRIPTION
**Pull request by andrewjradcliffe**
Truly, very minor indeed. I just happened to notice them when reading this section of the manual, and thought: why not correct them?

### CODE REVIEW

**Comment by andrewjradcliffe** [comment]
Interesting whitespace failure; unrelated to the scope of this PR.

**Comment by johnnychen94** [comment]
Let me see if close and reopen retriggers the PR.

**Comment by ViralBShah** [comment]
Should we make these `jldoctest`?

**Comment by andrewjradcliffe** [comment]
> Should we make these `jldoctest`?

It seems like a good place to perform a simple check of the default PRNG, given that any edits to said PRNG will break the test.

**Pull request merged**
