### PR TITLE
Fix parentheses in two UnicodeError messages

### PR DESCRIPTION
**Pull request by nalimilan**
This partially reverts eb73a22 and fixes another missing
parenthesis.

### CODE REVIEW

**Comment by tkelman** [comment]
actually I'm not so sure. we should be consistent between UTF_ERR_SHORT and UTF_ERR_CONT one way or the other. Is the continuation byte part of the 0x... or an explanation of the invalid unicode?

**Comment by nalimilan** [comment]
Honestly, I think both solutions are OK. `UTF_ERR_CONT` is a bit different since in that case the message refers the the printed byte, while for `UTF_ERR_SHORT` either the first byte of the sequence, or the sequence itself, lacks a continuation byte.

**Comment by tkelman** [comment]
having them inconsistent is annoying. maybe doesn't matter so much but the paren should either be after the `<<2>>` in both cases or at the end in both cases

**Comment by nalimilan** [comment]
OK, so let's keep the current version, and only fix the other missing parenthesis. Here's an updated commit.

**Comment by tkelman** [comment]
I guess this'll be good enough.

**Pull request merged**
