### PR TITLE
macOS: workaround a dyld/libunwind deadlock issue since 12.1

### LINKED ISSUE #43578: Profile: `@profile` hanging on MacOS 12
On master and 1.6.4, on MacOS (other platforms not tested yet)

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.1183 (2021-12-28)
 _/ |\__'_|_|_|\__'_|  |  Commit 693b4471fa (0 days old master)
|__/                   |

julia> versioninfo()
Julia Version 1.8.0-DEV.1183
Commit 693b4471fa (2021-12-28 10:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6

(jl_ePM8ng) pkg> add FFMPEG
...
Precompiling project...
  44 dependencies successfully precompiled in 10 seconds. 3 already precompiled.

julia> using Profile

julia> @profile using FFMPEG
# hangs with no CPU usage
```

### PR DESCRIPTION
**Pull request by vtjnash**
Apple reintroduced the old bug that we previously worked around in
fad04d39d592d8e0fcbfba439e8157f582bbc850 with a similar patch to this.

Fixes #43578

### CODE REVIEW

**Comment by staticfloat** [comment]
Is there a minimal reproducer that I can send to Apple?

**Comment by vtjnash** [comment]
You can potentially just note that the documentation for these functions in libunwind implies it doesn't acquire a lock, and that dyld is now violating that: http://www.nongnu.org/libunwind/man/unw_step(3).html#section_4

**Comment by staticfloat** [comment]
Alright, I opened a feedback with Apple, we'll see if it goes anywhere.

**Comment by IanButterworth** [comment]
I can confirm that the MWE from https://github.com/JuliaLang/julia/issues/43578 is fixed
```
julia> @profile while true
          run(`pwd`)
       end
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
/Users/ian/Documents/GitHub/julia
etc.
```

but stress testing it here made it deadlock with `^C` and `^T` not working
```
% JULIA_DEPOT_PATH=/tmp/5454 ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.1248 (2022-01-07)
 _/ |\__'_|_|_|\__'_|  |  jn/43578/a51e2d83c0 (fork: 1 commits, 0 days)
|__/                   |

julia> using Pkg, Profile

julia> @profile Pkg.add("PNGFiles")
  Installing known registries into `/tmp/5454`
    Updating registry at `/tmp/5454/registries/General.toml`
   Resolving package versions...


```

**Comment by vtjnash** [comment]
> with ^C and ^T not working

Good catch. That is a different (but closely related) bug.

**Comment by IanButterworth** [comment]
Unfortunately something's still deadlocking for me. This is stopped with 0% cpu.

```
julia> @profile Pkg.add("PNGFiles")
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
Precompiling project...
  Progress [===>                                     ]  12/191
  ◑ SentinelArrays
  ✓ Calculus
  ✓ RoundingIntegers
  ◑ StaticArrays
  ✓ AbstractFFTs
  ✓ IndirectArrays
  ✓ ExprTools
  ✓ IteratorInterfaceExtensions
  ✓ TensorCore
  ✓ StatsAPI
  ✓ CEnum
  ◓ FixedPointNumbers
  ◓ FillArrays
  ✓ OpenLibm_jll
  ✓ InverseFunctions
  ◑ WoodburyMatrices
  ✓ CompilerSupportLibraries_jll
  ◐ MacroTools
  ◒ Preferences
  ◒ Parsers
  ◑ Compat
  ◑ Observables
  ◓ Requires
  ◒ DataValueInterfaces
  ◓ RealDot
```

**Comment by IanButterworth** [comment]
I've tried, but I can't get this to deadlock! Thanks @vtjnash !

**Comment by IanButterworth** [comment]
I just hit a similar repeatable deadlock on ubuntu
```
julia> import Pkg

julia> Pkg.update()
    Updating registry at `~/.julia/registries/HolyLabRegistry`
    Updating git-repo `https://github.com/HolyLab/HolyLabRegistry`
    Updating registry at `~/.julia/registries/PrivateRegistry`
    Updating git-repo `git@github.com:PrivateOrg/PrivateRegistry`
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
        Info Some packages have new versions but cannot be upgraded. To see why use `status --outdated`

julia> using Profile

julia> @profile Pkg.update()
    Updating registry at `~/.julia/registries/HolyLabRegistry`
    Updating git-repo `https://github.com/HolyLab/HolyLabRegistry`
    Updating registry at `~/.julia/registries/PrivateRegistry`
    Updating git-repo `git@github.com:PrivateOrg/PrivateRegistry`
    Updating registry at `~/.julia/registries/General.toml`
┌ Error: Some registries failed to update:
│     — /home/ian/.julia/registries/PrivateRegistry — failed to fetch from repo
└ @ Pkg.Registry ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:446
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

Note that `PrivateRegistry` is the only registry added via ssh

I added a debug print to that [error throw](https://github.com/JuliaLang/Pkg.jl/blob/c313966330e161d5fc8218d0144b80884b6d5657/src/Registry/Registry.jl#L417)
```
Error: Pkg.Types.PkgError("failed to fetch from git@github.com:PrivateOrg/PrivateRegistry, 
error: GitError(Code:ERROR, Class:SSH, Failed to retrieve list of SSH authentication 
methods: Error waiting on socket)"
```

**Comment by KristofferC** [comment]
This requires a manual backport against `backports-release-1.6`.

**Pull request merged**
