### PR TITLE
libuv bugfixes

### LINKED ISSUE #16398: Precompiling exits early using `--inline=no -O0`
E.g.:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4118 (2016-05-16 19:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  master/5f22ab8* (fork: 4 commits, 0 days)
|__/                   |  x86_64-apple-darwin15.3.0

julia> using TerminalExtensions; using Gadfly; using Gallium
INFO: Recompiling stale cache file /Users/kfischer/.julia/lib/v0.5/DataStructures.ji for module DataStructures.
Process 17829 exited with status = 1 (0x00000001)
```

### LINKED ISSUE #17802: Assertion failed: (loop->watchers[w->fd] == w)
Related to #7840

Pretty easy to reproduce:

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> @sync for i = 1:1000
         @async readall(`sleep 1`)
       end
Assertion failed: (loop->watchers[w->fd] == w), function uv__io_stop, file src/unix/core.c, line 764.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by vtjnash**
adds the following libuv commmits:
https://github.com/JuliaLang/libuv/commit/44820a549c317539c865d7e8d573605b1fbe2deb
https://github.com/JuliaLang/libuv/commit/708148fccd47b65a835e290342902781bc8d8548
https://github.com/JuliaLang/libuv/commit/28743d6091531340cfe316de2b2d385fe1778ff5

fixes #17802 
fixes #16398

### CODE REVIEW

**Comment by tkelman** [comment]
xref https://github.com/libuv/libuv/issues/973#issuecomment-237811071 opinion from upstream that one of those commits might not be the best fix

**Comment by vtjnash** [comment]
While we may work on the design more in that issue, the commit in question fixes a regression from v0.4 behavior which had been an unintentional result of upgrading to a newer version of libuv.

**Comment by tkelman** [comment]
appveyor is unhappy
```
From worker 11:	     * spawn                       [stdio passthrough ok]
	From worker 11:	Test Failed
	From worker 11:	  Expression: false
	From worker 11:	Error During Test
	From worker 11:	  Test threw an exception of type TypeError
	From worker 11:	  Expression: ex::Base.UVError.code == Base.UV_EMFILE
	From worker 11:	  TypeError: anonymous: in typeassert, expected Base.UVError, got ErrorException
	From worker 11:	   in macro expansion; at C:\projects\julia\test\spawn.jl:409 [inlined]
	From worker 11:	   in anonymous at .\<missing>:?
	From worker 11:	   in include_string(::String, ::String) at .\loading.jl:380
	From worker 11:	   in include_from_node1(::String) at .\loading.jl:429
	From worker 11:	   in macro expansion at .\util.jl:226 [inlined]
	From worker 11:	   in runtests(::String) at C:\projects\julia\test\testdefs.jl:7
	From worker 11:	   in (::Base.Serializer.__deserialized_types__.##16#24)(::String) at C:\projects\julia\test\runtests.jl:44
	From worker 11:	   in (::Base.##585#587{Base.CallMsg{:call_fetch}})() at .\multi.jl:1410
	From worker 11:	   in run_work_thunk(::Base.##585#587{Base.CallMsg{:call_fetch}}, ::Bool) at .\multi.jl:996
	From worker 11:	   in macro expansion at .\multi.jl:1410 [inlined]
	From worker 11:	   in (::Base.##584#586{Base.CallMsg{:call_fetch},Base.MsgHeader,TCPSocket})() at .\event.jl:46
```

**Comment by vtjnash** [comment]
It appears that windows doesn't have a strict resource limit on pipes. it does well up to about 2M handles, at which point julia.exe has consumed all physical RAM and it becomes somewhat unresponsive. so this test just doesn't really apply to windows.

**Comment by tkelman** [comment]
oh right you asked me to test that and I forgot about it

**Pull request merged**
