### PR TITLE
Fix-15074: Added OS info about building from source in README

### PR DESCRIPTION
**Pull request by goelakash**
#15074 It was mentioned that building via `make` is not a universal solution. I have  added a small change to notify user about which OS' this works with. Should I also add a line wrt to Windows as -

"To build on Windows, see instructions on how to compile from source using Visual Studio or install Cygwin"? 
I am not sure whats the correct recommendation, or Julia community's policies about these are.
Please review.

### CODE REVIEW

**Comment by tkelman** [comment]
There's a separate readme with full instructions for building on windows, we have a link to it at https://github.com/JuliaLang/julia#windows but it's a ways down the page. Building with Visual Studio is highly experimental and not something we can officially support right now (see #12056).

**Comment by goelakash** [comment]
How about I add "For details see #link" in there?

**Comment by tkelman** [comment]
Dunno, there are a lot of build dependencies besides just `make`. We could say `See [Platform-Specific Build Notes](#Platform-Specific-Notes) for more details.` or something like that.

**Comment by goelakash** [comment]
I did add that. Seems ok now.

**Comment by tkelman** [comment]
The part you added `To build on Linux, OSX(with **make** utility installed) or other *nix systems,` is a bit overly verbose and strangely formatted. We build on Windows using make as well. I'd say add the short link right after the short sentence the way it was.

**Pull request closed without merging**
