### PR TITLE
ASAN: Minimal system image to reduce CI time.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
cc: @tkf

**Comment by DilumAluthge** [comment]
@maleadt @tkf Is the `asan` failure here related to the PR, or did we just happen to catch a Heisenbug by coincidence?

**Comment by maleadt** [comment]
It's going to perform more compilation at run time, so maybe it's related.
The stack traces aren't symbolized though, we need to set ASAN_SYMBOLIZER_PATH to the llvm-symbolizer binary that's available there.

**Comment by DilumAluthge** [comment]
I have retried the `asan` job. Let's see if we see the same failure the second time.

(The log from the original run will still be available.)

**Comment by maleadt** [comment]
@DilumAluthge ASAN_SYMBOLIZER_PATH is set in the Make.user, but the tests are run directly, https://github.com/JuliaCI/julia-buildkite/blob/f5f7815ced96d39be665af2d8292a500d2eab916/pipelines/main/misc/sanitizers.yml#L24-L34=. Can we change that to a `make test` invocation so that we inherit those flags?

**Comment by DilumAluthge** [comment]
If we just do `make test interpreter intrinsics ...`, I don't think it will use the correct Julia binary to run the tests, will it? We need it to use the `tmp/test-asan/asan/usr/bin/julia-debug` Julia binary.

**Comment by maleadt** [comment]
I guess `make test` should respect `JULIA_BUILD_MODE` then.

**Comment by DilumAluthge** [comment]
Well it's not just the release/debug mode, right? We need `make test` to use a specific Julia binary at a specific path.

**Comment by tkf** [comment]
> If we just do `make test interpreter intrinsics ...`, I don't think it will use the correct Julia binary to run the tests, will it?

I think you can do something like `make -C tmp/test-asan/asan test-interpreter test-intrinsics test-llvmcall ...`? Although maybe multiple `test-*` targets do not parallelize at the Julia level?

**Comment by DilumAluthge** [comment]
Can we edit the direct test invocation so that it picks up the LLVM symbolizer binary that we want?

**Comment by DilumAluthge** [comment]
With e.g. `make test foo bar ...`, we pick up the space-separated list `foo bar` and pass it in to Julia, where the tests then get run in parallel. So no worries there.

**Comment by tkf** [comment]
> With e.g. `make test foo bar ...`, we pick up the space-separated list `foo bar` and pass it in to Julia, where the tests then get run in parallel.

Huh, can `make` do that?! It sounds easier to use `make` then (to configure things only in Make.user). I can create a quick patch.

**Comment by DilumAluthge** [comment]
I might be misremembering. Let me check the syntax.

**Comment by DilumAluthge** [comment]
Ugh I think I was misremembering. Yes, it looks like you're right, we can't use Julia parallelism for this. We'd have to use `make` parallelism, e.g. `make -j4 test-interpreter test-intrinsics test-llvmcall test-llvmcall2 test-precompile test-worlds test-agents`.

**Comment by DilumAluthge** [comment]
It would be nice to have some kind of `make` flag, e.g. `make test TESTS="interpreter intrinsics llvmcall ..."`, and then have `make` pass the list of tests to Julia, and then do the parallelism at the Julia level. But that's beyond the scope of this PR.

**Comment by vtjnash** [comment]
You can access and change the MAKETARGETS list

**Comment by vtjnash** [comment]
You would need dummy rules that depend upon a common target, and the common target to read the list of other targets
https://www.gnu.org/software/make/manual/html_node/Goals.html

**Comment by tkf** [comment]
I just posted probably the easiest patch for this https://github.com/JuliaCI/julia-buildkite/pull/90

**Comment by DilumAluthge** [comment]
`asan` is now passing on this PR, so I will merge it.

On this PR, `asan` took 46 minutes to run, with 30 minutes being spent in `Build julia-debug with ASAN` and 14 minutes being spent in `Run tests`.

For comparison, on a recent run on master, `asan` took 63 minutes to run, with 58 minutes being spent in `Build julia-debug with ASAN` and 3 minutes being spent in `Run tests`.

So this PR is definitely an improvement to the total run time.

**Pull request merged**
