### PR TITLE
Do not shrink `Dict`/`Set` in `merge!`/`union!`

### PR DESCRIPTION
**Pull request by petvana**
PR provides an alternative approach to #51607 by introducing `shrink = true` argument.

@oscardssmith Feel free to close this PR if you don't like it.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
I think this is probably a better approach than mine.

**Comment by KristofferC** [comment]
I think this should start off as an internal thing (`_sizehint!`) to fix the original issue and there could then be a separate discussion about adding the new argument to the public function etc.

**Comment by oscardssmith** [comment]
since there isn't a real rush (this is just a relatively minor performance improvement), I'm tagging triage to discuss whether this is an interface we want.

**Comment by KristofferC** [comment]
The whole point of splitting it up is to avoid bundling pure performance fixes with discussion of API.

**Comment by petvana** [comment]
As discussed, I've split the PR to contain only performance improvements in the first step.

**Comment by LilithHafner** [comment]
Feel free to tag the proposed API change with triage; this PR in its current state is not a good fit for triage.

**Pull request merged**
