### PR TITLE
Backports for julia-1.6.3

### LINKED ISSUE #39705: LoadError: syntax: malformed expression
Running on latest nightly, I get this cryptic error:
```julia
ERROR: LoadError: syntax: malformed expression
Stacktrace:
  [1] top-level scope
    @ ~/debug-julia/he-gst.jl:13
  [2] EnergyExpressions.NBodyMatrixElement(bcs::EnergyExpressions.BitConfigurations{EnergyExpressions.Orbitals{SpinOrbital{Orbital{Int64}, Tuple{Int64, HalfIntegers.Half{Int64}}}, SparseArrays.SparseMatrixCSC{EnergyExpressions.NBodyTerm, Int64}, BitMatrix, BitVector}}, op::EnergyExpressions.FieldFreeOneBodyHamiltonian, i::Int64, j::Int64)
    @ EnergyExpressions ~/.julia/dev/EnergyExpressions/src/bit_configurations.jl:423
  [3] EnergyExpressions.NBodyMatrixElement(bcs::EnergyExpressions.BitConfigurations{EnergyExpressions.Orbitals{SpinOrbital{Orbital{Int64}, Tuple{Int64, HalfIntegers.Half{Int64}}}, SparseArrays.SparseMatrixCSC{EnergyExpressions.NBodyTerm, Int64}, BitMatrix, BitVector}}, op::EnergyExpressions.LinearCombinationOperator, i::Int64, j::Int64)
    @ EnergyExpressions ~/.julia/dev/EnergyExpressions/src/bit_configurations.jl:431
  [4] (Matrix{T} where T)(bcs::EnergyExpressions.BitConfigurations{EnergyExpressions.Orbitals{SpinOrbital{Orbital{Int64}, Tuple{Int64, HalfIntegers.Half{Int64}}}, SparseArrays.SparseMatrixCSC{EnergyExpressions.NBodyTerm, Int64}, BitMatrix, BitVector}}, rows::UnitRange{Int64}, op::EnergyExpressions.LinearCombinationOperator, cols::UnitRange{Int64}; verbosity::Int64)
    @ EnergyExpressions ~/.julia/dev/EnergyExpressions/src/bit_configurations.jl:453
```

Project attached, which should reproduce the problem: [malformed-syntax.zip](https://github.com/JuliaLang/julia/files/5996700/malformed-syntax.zip)

This appeared a few days ago, e.g. I see the error on
```
Julia Version 1.7.0-DEV.560
Commit dff13e157d* (2021-02-17 07:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```
but not on
```julia
julia> versioninfo()
Julia Version 1.7.0-DEV.499
Commit 21557721f2* (2021-02-09 08:54 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)

julia> include("he-gst.jl")
Fock operator with
- quantum system: Atom{Float64}(R=Staggered finite differences basis {Float64} on 0.0..10.049999999999999 with 100 points spaced by ρ = 0.1; Z = 2 [helium]; 2 e⁻ ⇒ Q = 0) with 1 SpinConfiguration{SpinOrbital{Orbital{Int64}, Tuple{Int64, HalfIntegers.Half{Int64}}}}: 1s₀α 1s₀β
- SCF equations:
  - Hartree–Fock equation: E|1s₀α⟩ = OrbitalEquation(1s₀α):
 + 1ĥ₀|1s₀α⟩ + 1r⁻¹×Y⁰(1s₀β,1s₀β)|1s₀α⟩

⟨1s₀α| 𝓗 |1s₀α⟩ = -0.7500579719133716 Ha = -20.409827473734754 eV

  - Hartree–Fock equation: E|1s₀β⟩ = OrbitalEquation(1s₀β):
 + 1ĥ₀|1s₀β⟩ + 1r⁻¹×Y⁰(1s₀α,1s₀α)|1s₀β⟩

⟨1s₀β| 𝓗 |1s₀β⟩ = -0.7500579719133716 Ha = -20.409827473734754 eV
```

### LINKED ISSUE #40855: Undefined behaviour in struct with only union fields
Code:
```
@enum Fruit Apple
struct A
    a::Union{Nothing, Bool}
    b::Union{Nothing, Bool}
    c::Union{Nothing, Bool}
    d::Union{Nothing, Fruit}
    e::Union{Nothing, Int}
end

function g()
   x = A(true, true, true, Apple, 1)
   println(x)
end
g()
```
Output:
```
<unknown>:0: error: invalid number of bytes
<unknown>:0: error: invalid number of bytes
<unknown>:0: error: invalid number of bytes
<unknown>:0: error: invalid number of bytes
<unknown>:0: error: invalid number of bytes
A(true, true, true, nothing, nothing)
```

The above code works as expected with Julia 1.5.2 however with Julia 1.6.0 or 1.6.1 I get either the output above or, less frequently, the Julia session hangs or crashes. Can reproduce on both Ubuntu 20.04 and Windows 10.

### LINKED ISSUE #40964: `Vararg` argument as optional argument gives error when there is a keyword argument.
MWE:
```
julia> foo(a, b::Array{Int, 1}...=[0,0];c="") = @show b
foo (generic function with 3 methods)

julia> goo(a,b::Array{Array{Int, 1}, 1}) = begin
       c = "c"
       foo(a, b...;c)
       end
goo (generic function with 3 methods)

julia> goo(1, [[1,2,3]])
ERROR: TypeError: in typeassert, expected Vector{Int64}, got a value of type Tuple{Vector{Int64}}

julia> foo2(a, b::Array{Int, 1}...;c="") = @show b
foo2 (generic function with 1 method)

julia> goo2(a,b::Array{Array{Int, 1}, 1}) = begin
       c = "c"
       foo2(a, b...;c)
       end
goo2 (generic function with 1 method)

julia> goo2(1, [[1,2,3]])
b = ([1, 2, 3],)
([1, 2, 3],)

julia> foo3(a, b::Array{Int, 1}...=[0,0]) = @show b
foo3 (generic function with 2 methods)

julia> goo3(a,b::Array{Array{Int, 1}, 1}) = foo3(a, b...)
goo3 (generic function with 1 method)

julia> goo3(1, [[1,2,3]])
b = ([1, 2, 3],)
([1, 2, 3],)
```

System info:
```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client)
Environment:
  JULIA_NUM_THREADS = 6
```

Based on the differences among `foo`, `foo2`, and `foo3`, I suspect it might have something to do with the keyword argument syntax but I’m not sure.

I don’t know if this is technically a bug since I haven’t seen the usage of Vararg arguments as optional arguments on the official documentation (I might have missed it so feel free to point out); on the other hand since it’s not forbidden and yet we have this kind of errors. Initial Discourse link is [here](https://discourse.julialang.org/t/vararg-argument-as-optional-argument-gives-error-when-there-is-a-keyword-argument/61812).

### LINKED ISSUE #41566: _simplify_include_frames throws bounds error
Original issue: https://github.com/JuliaLang/PackageCompiler.jl/issues/517

When using a sysimage, `_simplify_include_frames` throws a bounds error at line 804 because `i` is 0. 

https://github.com/JuliaLang/julia/blob/d7329038feb207997b9a6d969c5c8f11d37680d5/base/errorshow.jl#L804

The immediate fix is to move the decrement to the top of the loop and start at `i = length(trace) + 1`. I can make a pull request for this.

This still gives really verbose stack traces when using a sysimage. I'd like to take a shot at improving that as well, but perhaps this should be done in a separate issue/pull request since it might require further discussion.

Thanks to @KristofferC for identifying the problem.

### LINKED ISSUE #41630: `begin` indexing vs. `replace_ref_begin_end!`
I thought `Base.replace_ref_begin_end!` is used to implement `begin` indexing, but appearently they are inconsistent?

Reading the source of it, I stumbled upon [this line](https://github.com/JuliaLang/julia/blob/9044222bfcee604610d75db25d8d1c07e51cf7f0/base/views.jl#L45) in views.jl:

```julia
exj, used = replace_ref_begin_end_!(ex.args[j], (:($firstindex($S)),:($lastindex($S,$n))))
```

Shouldn't that be `$firstindex($S, $n)`?  I tried producing a failing example using OffsetArrays, but that only showed some sort of discrepancy, which I can't explain:

```julia
julia> a
2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10:
 1  2
 3  4

julia> a[end, begin]
3

julia> Meta.@lower a[end, begin]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.lastindex(a, 1)
│   %2 = Base.axes(a, 2)
│   %3 = Base.first(%2)
│   %4 = Base.getindex(a, %1, %3)
└──      return %4
))))

julia> Base.replace_ref_begin_end!(:(a[end, begin]))
:(a[(lastindex)(a, 1), (firstindex)(a)])

julia> a[(lastindex)(a, 1), (firstindex)(a)]
ERROR: BoundsError: attempt to access 2×2 OffsetArray(::Array{Int64,2}, -10:-9, 9:10) with eltype Int64 with indices -10:-9×9:10 at index [-9, 1]
Stacktrace:
 [1] throw_boundserror(::OffsetArray{Int64,2,Array{Int64,2}}, ::Tuple{Int64,Int64}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] getindex(::OffsetArray{Int64,2,Array{Int64,2}}, ::Int64, ::Int64) at /home/philipp/.julia/packages/OffsetArrays/Osysv/src/OffsetArrays.jl:407
 [4] top-level scope at REPL[22]:1
```

### LINKED ISSUE #41656: Cannot define `isempty` in Main
I found a confusing behavior when I tried to define a function named `isempty` in the `Main` module:
```
julia> isempty(x) = true
ERROR: error in method definition: function Base.isempty must be explicitly imported to be extended
Stacktrace:
 [1] top-level scope
   @ none:0
 [2] top-level scope
   @ REPL[1]:1
```

### LINKED ISSUE #41975: SSA conversion drops bool typecheck for noop if
Actual:
```
julia> f() = (if nothing; end; unsafe_load(Ptr{Int}(0)))
f (generic function with 1 method)

julia> f()
Unreachable reached at 0x7fb33bb50090

signal (4): Illegal instruction
in expression starting at REPL[13]:1
unsafe_load at ./pointer.jl:105 [inlined]
unsafe_load at ./pointer.jl:105 [inlined]
```

Expected:
```
ERROR: TypeError: non-boolean (Nothing) used in boolean context
Stacktrace:
 [1] f()
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[2]:1
```

### LINKED ISSUE #42090: inference: need to invalidate stale `Conditional` wrapped in `PartialStruct`
MRE:
```julia
# should invalidate old constraint wrapped in PartialStruct when the subject of condition has changed
let M = Module()
    @eval M begin
        struct BePartialStruct
            val::Int
            cond
        end
    end

    rt = @eval M begin
        Base.return_types((Union{Nothing,Int},)) do a
            cond = a === nothing
            obj = $(Expr(:new, M.BePartialStruct, 42, :cond))
            r1 = getfield(obj, :cond) ? 0 : a # r1::Int
            a = $(gensym(:anyvar))::Any
            r2 = getfield(obj, :cond) ? a : nothing # r2::Any, not r2::Const(nothing)
            return r1, r2 # ::Tuple{Int,Any}
        end |> only
    end
    @test rt == Tuple{Int,Any}
end
```

I encountered `Conditional` wrapped in `PartialStruct` when the `Conditional` is captured in a closure.

Solutions:
- (dirty, but more accurate) we can add another special case as like `LimitedAccuracy`: https://github.com/JuliaLang/julia/blob/3aada5982c368f075dd0014dd9bdd5b8d2947b51/base/compiler/typelattice.jl#L366
- (simple, but less accurate) disallow `PartialStruct` to wrap `Conditional`

Which one do we want ?

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #38783 - Set the `@JuliaLang/github-actions` team as the code owners for GitHub Actions workflow files
- [x] #39618 - improve constraint propagation with multiple ||
- [x] #39709 - fix #39705: lowering of Expr(:||)
- [x] #40925 - Set up a few code owners
- [x] #40929 - Pare down the CODEOWNERS [skip ci] [ci skip]
- [x] #41238 - Transition the `coverage-linux64` pipeline to Buildkite
- [x] #41292 - [CompilerSupportLibraries_jll] Update to v0.5.0
- [x] #41375 - Code coverage: fix the code coverage pipeline
- [x] #41321 - Add embedding and whitespace jobs to buildkite
- [x] #41493 - Comment out signed pipeline test
- [x] #41494 - Streamline buildkite configuration a bit
- [x] #41441 - add a GC safepoint in Task.wait
- [x] #41507 - CI (code coverage): run some tests in serial
- [x] #41543 - CI (Buildkite): use a consistent naming scheme for labels, keys, and commit statuses
- [x] #41544 - CI: Add more Debian packages to the `llvm-passes` rootfs image
- [x] #41549 - CI (Buildkite): rootfs_images: allow user to override the default value of `tag_name`
- [x] #41559 - Fix `get-task-allow` entitlement
- [x] #41556 - add a test for #41096
- [x] #41551 - add default "auto" as option to --check-bounds
- [x] #41530 - CI: add the sanitizers pipelines (e.g. ASAN) to Buildkite
- [x] #41571 - CI (rootfs_utils): Require that the user explicitly specify the `tag_name`
- [x] #41594 - REPL doc lookup assumed ASCII for the given string
- [x] #41591 - CI (rootfs images): when uploading a tarball, don't allow it to override an existing tarball (unless the user provides the `--force-overwrite` command-line flag)
- [x] #41610 - CI (rootfs images): fix a bug in the `upload_rootfs_image` function
- [x] #41286 - Move compile timing to inside `@time`'s main timing block. Fixes >100% compilation time reports
- [x] #41596 - Do not error when showing invalid enums (#40042)
- [x] #41614 - make precompile files writable
- [x] #41622 - while loop -> for loop in _simplify_include_frames (fixes #41566)
- [x] #41606 - CI (Buildkite): move the `sanitizers` builders (e.g. `asan`) to the experimental pipeline
- [x] #41646 - fix memory corruption in `deleteat!`
- [x] #41648 - CI: delete the `.buildkite/rootfs_images` directory
- [x] #41645 - [build] Automatically set `USE_BINARYBUILDER_CSL=0` when local CSL is new
- [x] #41682 - Update the `file.jl` tests to allow for both `EPERM` and `EINVAL` in the non-root CHOWN tests
- [x] #41541 - CI (Buildkite): Add the `package_linux64` and `doctest` builders
- [x] #41698 - CI (Buildkite): Update all rootfs images to version v3.1, add some documentation, and reorganize/rename/move a bunch of configuration files
- [x] #41700 - CI (Buildkite): include the short commit hash in the artifact filename
- [x] #41706 - CI (Buildkite): for the signed pipeline test, use `signature_file` instead of `signature`
- [x] #41752 - guard isempty (close #41656)
- [x] #41650 - Printf %g/%G  format fix for Inf/NaN
- [x] #41796 - CI (Buildkite): on the `platform_linux` jobs, after building Julia, make sure that the working directory is clean
- [x] #41812 - CI: Disable Codecov commit statuses
- [x] #41811 - CI (Buildbot): As soon as a PR is created or updated, create pending (yellow) commit statuses for all Buildbot jobs
- [x] #41814 - CI (Buildbot): for the "Create Pending Statuses" GitHub Actions workflow, use the `pull_request_target` event instead of the `pull_request` event
- [x] #41815 - CI (Buildbot): Fix a bug in the "Create Pending Statuses" GitHub Actions workflow
- [x] #41817 - CI (Buildbot): a simpler way of getting the SHA for the "Statuses" action
- [x] #41822 - CI (Buildbot, GHA): in the "Statuses" workflow, we only need to create pending (yellow) statuses for the `tester_` jobs
- [x] #41824 - CI (Buildbot, GHA): in the "Statuses" workflow, remove the `macosaarch64` and `musl64` statuses
- [x] #41831 - CI (Buildbot, GHA): in the "Statuses" workflow, remove the `tester_linuxppc64le` status
- [x] #41832 - CI (Buildbot, GHA): In the "Statuses" workflow, remove the `tester_linuxarmv7l` status
- [x] #41825 - CI (Buildbot, GHA): add a note about token permissions
- [x] #41851 - CI (Buildbot, GHA): Simplify the `permissions` key in the workflow file for the "Statuses" workflow
- [x] #41849 - win: fix lock function call for backtrace collection
- [x] #41695 - Fix firstindex in replace_ref_begin_end (fixes #41630)
- [x] #41864 - CI (Buildkite): `llvmpasses`: use the latest rootfs image
- [x] #41898 - ensure that the non-REPL precompile code actually get precompiled
- [x] #41956 - README: add a link to the `base-buildkite-docs` repository
- [x] #41919 - Fix collect on stateful generator
- [x] #42010 - Fix #41975 - Dropped typecheck in GotoIfNot
- [x] #41827 - Parameter attributes on Cfunction closures sticks
- [x] #41839 - Fix a precision issue in `abstract_iteration`
- [x] #42059 - [AllocOpt] fix iterator invalidation
- [x] #42062 - GMP: fix warning in init
- [x] #41510 - Fix `sum()` and `prod()` for tuples
- [x] #42061 - InteractiveUtils: recursive correctly in varinfo, et al.
- [x] #42009 - fix ptrhash_remove
- [x] #42003 - Avoid impossible unionall normalization
- [x] #41095 - Refactor LICENSE.md to make it scanner friendly
- [x] #42058 - avoid loading duplicate libraries
- [x] #42081 - inference: propagate variable changes to all exception frames
- [x] #42091 - inference: fix #42090, make sure not to wrap `Conditional` in `PartialStruct`

Non-merged PRs with backport label:
- [ ] #41707 - CI (Buildkite): Add `package_linux` and `tester_linux` for more Linux architectures
- [ ] #41228 - fix some issues with equality of factorizations
- [ ] #41041 - fix command literals with trailing backslashes
- [ ] #40820 - Fix log message id from at-deprecate to be a Symbol.
- [ ] #40038 - Allow the conversion of AbstractUnitRanges to OrdinalRanges

### CODE REVIEW

**Comment by simeonschaub** [comment]
If we are backporting #39618, we will also have to backport #39709, since it fixes a bug introduced in that PR.

**Comment by KristofferC** [comment]
Thanks, I backported https://github.com/JuliaLang/julia/pull/39618 because it was tangled up with https://github.com/JuliaLang/julia/pull/39980 which fixed a bug (https://github.com/JuliaLang/julia/issues/41096).

**Comment by vchuravy** [comment]
cc: @tkf @staticfloat @DilumAluthge the Asan toolchain seems to be broken here, can someone take a look?

**Comment by KristofferC** [comment]
@vchuravy, https://github.com/JuliaLang/julia/pull/41606 I guess.

**Comment by vchuravy** [comment]
> @vchuravy, #41606 I guess.

Feels more like something is wrong with the setup script since it is complaining that it can't find a certain version of libLLVM.

**Comment by tkf** [comment]
#41530 requires libblastrampoline but 1.6 doesn't have it. So, I guess it's actually not appropriate for backport? Not sure if it's related to the error per se, though.

**Comment by DilumAluthge** [comment]
I would just go ahead and backport all of the CI PRs. They tend to build on one another.

One of the things that PR https://github.com/JuliaLang/julia/pull/41606 (which is labeled for backport) does is that it only runs `asan` on `master`. So if you backport https://github.com/JuliaLang/julia/pull/41606 to this branch, `asan` will no longer be run on `release-1.6`.

**Comment by DilumAluthge** [comment]
Alternatively, if you don't backport https://github.com/JuliaLang/julia/pull/41530 to 1.6, that's also completely fine. There's no problem if the Buildkite configuration files on `release-1.6` differ from those on `master`, since one of the benefits of Buildkite is that we can maintain independent pipelines for `master`, `release-1.6`, `release-1.7`, etc.

So either way is fine (backport https://github.com/JuliaLang/julia/pull/41530 or don't backport https://github.com/JuliaLang/julia/pull/41530).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-886567250) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/0fb9425_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AKNS", "BayesianLinearRegressors", "BetterFileWatching", "BioStructures", "BoltzmannMachines", "Brillouin", "BytePairEncoding", "CalibrationErrorsDistributions", "ChaosTools", "ComplexMixtures", "CountTimeSeries", "DeepForest", "DiffEqParamEstim", "DistanceTransforms", "ElectricFields", "Enzyme", "FilesystemDatastructures", "FuzzyCompletions", "Glowe", "HePPCAT", "ITensors", "ImGuiOpenGLBackend", "IntervalRootFinding", "JET", "Khepri", "KissMCMC", "LowLevelParticleFilters", "ManifoldsBase", "MatrixProfile", "NumericalAlgorithms", "PrincipalMomentAnalysisApp", "PushVectors", "RateLimiter", "ReferenceTests", "ReverseDiff", "SatelliteDynamics", "SpatialJackknife", "StanOptimize", "StochasticDelayDiffEq", "SuiteSparseMatrixCollection", "Symbolics", "Tectonic", "ZigZagBoomerang"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-887247901) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/7ecd8dd_vs_7c45ff0/report.md).

**Comment by vtjnash** [comment]
#41774 just needs to be cherry-picked here, since it is already the backport commit

**Comment by KristofferC** [comment]
@DilumAluthge any idea why the CI commits fail to backport? Are we missing a label on something that then causes merge conflicts?

**Comment by DilumAluthge** [comment]
> Are we missing a label on something that then causes merge conflicts?

That seems like the most likely culprit.

**Comment by DilumAluthge** [comment]
Hmmm, actually....

Are you using a GitHub personal access token to do these pushes?

**Comment by DilumAluthge** [comment]
If so, can you check what permissions that token has?

**Comment by DilumAluthge** [comment]
> > Are we missing a label on something that then causes merge conflicts?
> 
> That seems like the most likely culprit.

Okay, I think I found the missing PRs - they were the PRs that modified the `CODEOWNERS` file. I've added the backport label to all of those PRs.

**Comment by KristofferC** [comment]
Great, that made the bunch of them go through.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-907610439):
```
NanosoldierError: failed to run tests: TypeError: non-boolean (Nothing) used in boolean context
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/390450d_vs_7c45ff0/report.md)
cc @maleadt

**Comment by maleadt** [comment]
That looks like an issue with some BinaryBuilder dependency; I've filed https://github.com/JuliaPackaging/OutputCollectors.jl/issues/1. To work around this, I'm launching PkgEval's `julia` with `--color=no`, can look into a better fix later.

@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-907611746) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/390450d_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "AlphaZero", "BLASBenchmarksCPU", "BioStructures", "BlobTracking", "CodeTransformation", "DIVAnd", "DecisionTree", "FaultDetectionTools", "FlashWeave", "FuzzyCompletions", "GeometricProblems", "Graph500", "JET", "KernelDensityEstimatePlotting", "MPIMeasurements", "Plots", "QuadEig", "RateLimiter", "Reactive", "RoMEPlotting", "SimpleSDMLayers", "SnowyOwl", "SphericalFourierBesselDecompositions", "Stuffing", "VCFTools"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-907668952) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/390450d_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
@nanosoldier runtests(ALL, vs=":release-1.6")

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-912647227) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/2389ed1_vs_7c45ff0/report.md).

**Comment by DilumAluthge** [comment]
@staticfloat Any idea what's causing the Buildkite failure here?

**Comment by DilumAluthge** [comment]
I've identified and fixed the issue. Buildkite should be working again now.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "ApproxFunBase", "BLASBenchmarksCPU", "BitInformation", "CodeTransformation", "ConstraintModels", "CopEnt", "Earth2014", "ElasticArrays", "EliminateGraphs", "JET", "RateLimiter", "SIMD", "StochasticRounding", "StrideArraysCore", "VideoIO", "ZigZagBoomerang"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-913001961) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/4651333_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
SIMD is just a consequence of https://github.com/JuliaLang/julia/pull/41510 and the SIMD tests should be fixed.

ApproxFunBase should be looked at.

StochasticRounding  passes locally

StrideArraysCore should be looked at.

VideoIO `@test_broken` -> working.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AlphaStableDistributions", "ApproxFunBase", "BLASBenchmarksCPU", "BitInformation", "CodeTransformation", "ConstraintModels", "CopEnt", "Earth2014", "ElasticArrays", "EliminateGraphs", "JET", "RateLimiter", "SIMD", "StochasticRounding", "StrideArraysCore", "VideoIO", "ZigZagBoomerang"], vs = ":release-1.6")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-913628735) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/19e66b3_vs_7c45ff0/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.6")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/41554#issuecomment-913957054):
```
NanosoldierError: error when preparing/pushing to report repo: failed process: Process(setenv(`git push`; dir="/run/media/system/data/nanosoldier/workdir/NanosoldierReports"), ProcessExited(1)) [1]

```
Unfortunately, the logs could not be uploaded.
cc @christopher-dG

**Comment by vtjnash** [comment]
From worker 2:    remote: error: See http://git.io/iEPt8g for more information.        
      From worker 2:    remote: error: File benchmark/by_hash/cd5b8fb_vs_7c45ff0/data.tar.xz is 107.50 MB; this exceeds GitHub's file size limit of 100.00 MB        
      From worker 2:    remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
      From worker 2:    To https://github.com/JuliaCI/NanosoldierReports.git
      From worker 2:     ! [remote rejected]         master -> master (pre-receive hook declined)

I've uploaded the report manually (without the data file) to
https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/cd5b8fb_vs_7c45ff0/report.md

**Pull request merged**
