### PR TITLE
respecialize normalized vararg type parameters as part of precise_container_type

### LINKED ISSUE #22875: Splatting causes normalization of `Type{T}` to `DataType`
For example:

```julia
julia> @inline g(args...) = one(args...)
g (generic function with 1 method)

julia> f(args...) = g(args...)
f (generic function with 1 method)

julia> @code_warntype f(Int)
Variables:
  #self#::#f
  args::Tuple{DataType}

Body:
  begin
      return (Main.one)((Core.getfield)(args::Tuple{DataType}, 1)::DataType)::Any
  end::Any
```

This makes it really hard to create argument-passing methods that can handle arbitrary inputs performantly (pretty fundamental need for the tracer I'm building). My current workaround involves wrapping/unwrapping types via the following struct:

```julia
struct BoxedType{T} end

@inline BoxedType(x) = x
@inline BoxedType(::Type{T}) where {T} = BoxedType{T}()

@inline unbox(x) = x
@inline unbox(::BoxedType{T}) where {T} = T
```

Besides being a pain to work with, this technique isn't even technically correct. IIUC from discussions with Jameson, this workaround cannot guarantee that `unbox(BoxedType{T}()) === T` since subtype constraints can be reordered as part of the `unbox` call.

### PR DESCRIPTION
**Pull request by jrevels**
Fix #22875:

```julia
julia> @inline g(args...) = one(args...)
g (generic function with 1 method)

julia> f(args...) = g(args...)
f (generic function with 1 method)

# this previously inferred as Any
julia> @code_warntype f(Int)
Variables:
  #self#::#f
  args::Any

Body:
  begin
      return 1
  end::Int64

# this was also previously inferred as Any
julia> @code_warntype Base.promote_type(Int, Float64, Int, Int, Int, Int)
Variables:
  #self#::Base.#promote_type
  T::Any
  S::Any
  U::Any
  V::Any

Body:
  begin
      return Float64
  end::Type{Float64}
```

This still needs tests, which I'll get to tomorrow (or after dinner, if I'm feeling plucky).

Many thanks to @vtjnash for once again guiding me through the dark waters of inference.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Review by JeffBezanson — APPROVED** [review]

**Comment by jrevels** [comment]
Travis failure unrelated?

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22877#issuecomment-316841867) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e3838b0f3e51f954caa44c1b2cfd6240a536fe9e/2d15c28_vs_cdaa5a7/report.md). cc @ararslan

**Comment by jrevels** [comment]
Can't reproduce the regressions locally. I can reproduce the `perf_local_array` speedups, though. It seems that before this PR, that benchmark was hitting #22875 via the calls to `samerand(T, n)`, causing downstream variables to be inferred as `Any`. With this fix, the function can be fully inferred.

**Pull request merged**
