### PR TITLE
Port v1.1 NEWS changes to HISTORY

### PR DESCRIPTION
**Pull request by blegat**
Mirrors the change of https://github.com/JuliaLang/julia/pull/30562 in `NEWS.md` of release-1.1 branch to `HISTORY.md` of master branch.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Thanks! In fact, maybe we should combine this with #30559. The news item from #30453 also needs to be copied to HISTORY on master. The following change is also missing on master:
```diff
-  * Added keyword arguments `rtol`, `atol` to `rank` ([#29926]).
+  * Added keyword arguments `rtol`, `atol` to `pinv`, `nullspace` and `rank` ([#29998], [#29926]).
```

**Comment by Keno** [comment]
This has a broken markdown footnote. In general, we should work out a process for changes that happen to NEWS.md after the merge.

**Comment by StefanKarpinski** [comment]
Might be good to do some kind of directory of small news snippets with files named by PR numbers and then have a script to generate the NEWS file from that. Would address the conflict issue as well.

**Comment by Keno** [comment]
My suggestion would be to add some commit message convention, e.g.:

````
Add awesome language feature

This adds my awesome language feature. It's so awesome, it deserves to be mentioned in NEWS

```news
# Language changes

* I've added a really awesome feature.
```

````

Then, on the release branch, we scrape the commit log and generate NEWS.md from scratch, allow people to manually make any edits while the release stabilizes and once the release closes, prepend the NEWS.md from the commit branch to HISTORY.md. In particular, master would never have a NEWS.md branch.

**Comment by KristofferC** [comment]
Doesn't sem useful anymore.

**Pull request closed without merging**
