### PR TITLE
Fix #11268

### LINKED ISSUE #11268: test failed: Base.samefile(Libdl.dlpath(dlls[1]),dlls[1])
```julia
[workerm@evo git_julia_new]$ export JULIA_CPU_CORES=2
[workerm@evo git_julia_new]$ make testall
cp /0_JULIA_COMPILED_0/git_julia_new/usr/lib/julia/sys.ji local.ji && /0_JULIA_COMPILED_0/git_julia_new/usr/bin/julia -J local.ji -e 'true' && rm local.ji
    JULIA test/all
	From worker 3:	     * linalg2              in  44.13 seconds
	From worker 3:	     * linalg3              in  13.87 seconds
	From worker 3:	     * linalg4              in   5.30 seconds
	From worker 3:	     * linalg/lapack        in   1.93 seconds
	From worker 2:	     * linalg1              in  86.11 seconds
	From worker 2:	     * linalg/tridiag       in   5.65 seconds
	From worker 2:	     * linalg/bidiag        in   8.87 seconds
	From worker 2:	     * linalg/diagonal      in   7.55 seconds
	From worker 2:	     * linalg/pinv          in   7.22 seconds
	From worker 2:	     * linalg/givens        in   2.19 seconds
	From worker 2:	     * linalg/cholesky      in   9.23 seconds
	From worker 2:	     * linalg/lu            in  13.63 seconds
	From worker 2:	     * linalg/symmetric     in   6.39 seconds
	From worker 3:	     * linalg/triangular    in 101.71 seconds
	From worker 2:	     * linalg/arnoldi       in  21.16 seconds
	From worker 2:	     * keywordargs          in   2.43 seconds
	From worker 3:	     * core                 in  26.04 seconds
	From worker 3:	     * strings              in  31.62 seconds
	From worker 2:	     * numbers              in  66.90 seconds
	From worker 2:	     * dict                 in  12.57 seconds
	From worker 2:	     * hashing              in   5.86 seconds
	From worker 2:	     * remote               in   0.42 seconds
	From worker 2:	     * iobuffer             in   1.01 seconds
	From worker 2:	     * staged               in   0.65 seconds
	From worker 3:	     * dates                in  54.44 seconds
	From worker 3:	     * tuple                in   1.00 seconds
	From worker 2:	     * arrayops             in  33.67 seconds
	From worker 2:	     * reduce               in   4.77 seconds
	From worker 2:	     * reducedim            in  17.46 seconds
	From worker 2:	     * random               in  13.28 seconds
	From worker 2:	     * intfuncs             in   0.87 seconds
	From worker 2:	     * simdloop             in   1.21 seconds
	From worker 2:	     * blas                 in   1.57 seconds
	From worker 2:	     * sparse               in  66.79 seconds
	From worker 3:	     * subarray             in 165.63 seconds
	From worker 3:	     * copy                 in   2.12 seconds
	From worker 3:	     * math                 in  12.49 seconds
	From worker 2:	     * bitarray             in  64.55 seconds
	From worker 2:	     * functional           in   1.37 seconds
	From worker 2:	     * operators            in   0.20 seconds
	From worker 3:	     * fastmath             in   3.96 seconds
	From worker 2:	     * path                 in   1.03 seconds
	From worker 3:	     * ccall                in   2.29 seconds
	From worker 2:	     * unicode              in   4.13 seconds
	From worker 3:	     * bigint               in   3.51 seconds
	From worker 3:	     * statistics           in  12.40 seconds
	From worker 3:	     * spawn                      [stdio passthrough ok]
	From worker 3:	 in   8.00 seconds
exception on 3: ERROR: LoadError: test failed: Base.samefile(Libdl.dlpath(dlls[1]),dlls[1])
 in expression: Base.samefile(Libdl.dlpath(dlls[1]),dlls[1])
 in error at error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in include at ./boot.jl:252
 in runtests at /0_JULIA_COMPILED_0/git_julia_new/test/testdefs.jl:79
 in anonymous at multi.jl:838
 in run_work_thunk at multi.jl:589
 in anonymous at task.jl:838
while loading /0_JULIA_COMPILED_0/git_julia_new/test/backtrace.jl, in expression starting on line 22
	From worker 2:	     * sorting              in  32.81 seconds
ERROR: LoadError: LoadError: test failed: Base.samefile(Libdl.dlpath(dlls[1]),dlls[1])
 in expression: Base.samefile(Libdl.dlpath(dlls[1]),dlls[1])
 in anonymous at task.jl:1394
while loading /0_JULIA_COMPILED_0/git_julia_new/test/backtrace.jl, in expression starting on line 22
while loading /0_JULIA_COMPILED_0/git_julia_new/test/runtests.jl, in expression starting on line 5

	From worker 3:	     * backtrace           Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:477: recipe for target 'testall' failed
make: *** [testall] Error 2
[workerm@evo git_julia_new]$ 
```

Arch Linux:

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+4829
Commit 9a47c3b (2015-05-14 14:22 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> 

```

### PR DESCRIPTION
**Pull request by garrison**
Here's my attempt at fixing #11268.

### CODE REVIEW

**Comment by tkelman** [comment]
LGTM, assuming green CI

Paging @ViralBShah or @StefanKarpinski, can we get @garrison commit access? It's overdue.

**Comment by ViralBShah** [comment]
Will do later today unless someone beats me to it.

**Comment by andreasnoack** [comment]
I think this one is causing
```jl
Andreass-MacBook-Pro:julia-dev andreasnoack$ make test-backtrace
    JULIA test/backtrace
     * backtrace           exception on 1: ERROR: LoadError: test failed: Base.samefile(Libdl.dlpath(dl),dl)
 in expression: Base.samefile(Libdl.dlpath(dl),dl)
 in error at error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in anonymous at no file:24
 in include at ./boot.jl:252
 in runtests at /Users/andreasnoack/julia-dev/test/testdefs.jl:197
 in anonymous at multi.jl:628
 in run_work_thunk at multi.jl:589
 in remotecall_fetch at multi.jl:662
 in remotecall_fetch at multi.jl:677
 in anonymous at task.jl:1392
while loading /Users/andreasnoack/julia-dev/test/backtrace.jl, in expression starting on line 21
ERROR: LoadError: LoadError: test failed: Base.samefile(Libdl.dlpath(dl),dl)
 in expression: Base.samefile(Libdl.dlpath(dl),dl)
 in error at error.jl:21
 in default_handler at test.jl:29
 in do_test at test.jl:52
 in anonymous at no file:24
 in include at ./boot.jl:252
 in runtests at /Users/andreasnoack/julia-dev/test/testdefs.jl:197
 in anonymous at multi.jl:628
 in run_work_thunk at multi.jl:589
 in remotecall_fetch at multi.jl:662
 in remotecall_fetch at multi.jl:677
 in anonymous at task.jl:1392
while loading /Users/andreasnoack/julia-dev/test/backtrace.jl, in expression starting on line 21
while loading /Users/andreasnoack/julia-dev/test/runtests.jl, in expression starting on line 5
```
on my
```jl
julia> versioninfo()
Julia Version 0.4.0-dev+4866
Commit 8f7531b* (2015-05-16 13:01 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by garrison** [comment]
The tests are more rigorous than before, as now all elements are checked (not just the first and last).  What is the filename that is failing?

**Comment by andreasnoack** [comment]
```jl
Andreass-MacBook-Pro:julia-dev andreasnoack$ make test-backtrace
    JULIA test/backtrace
     * backtrace           
Libdl.dlpath(dl) = "/Users/andreasnoack/julia-dev/usr/lib/libjulia.dylib"
dl = "/Users/andreasnoack/julia-dev/usr/lib/libjulia.dylib"
Libdl.dlpath(dl) = "/usr/lib/system/libunwind.dylib"
dl = "/usr/lib/libSystem.B.dylib"
```

**Comment by garrison** [comment]
CC @vtjnash, who added the original check in 6f63659.

**Comment by garrison** [comment]
I have no understanding of why `Libdl.dlpath("/usr/lib/libSystem.B.dylib")` would return `"/usr/lib/system/libunwind.dylib"`.

**Comment by vtjnash** [comment]
@staticfloat looks like you wrote this code originally in d14356eb. any idea why it gets confused by libSystem.B.dylib?

**Comment by staticfloat** [comment]
Yeah, that's because I was doing something way over-complicated which had an assumption broken as soon as two dynamic libraries had the same symbol exported; in this case, `libSystem.B.dylib`'s first symbol had the same name as `libunwind.dylib`'s.  I'm honestly astounded it worked for this long.  I think I've found a much simpler way of divining the absolute path; [PR here](https://github.com/JuliaLang/julia/pull/11307).

**Comment by ViralBShah** [comment]
@garrison Sent you an invite for commit access to JuliaLang repos.

**Comment by ScottPJones** [comment]
OT: @viralbshah How long to I have to be contributing before I can have one of the golden keys to the kingdom, like @garrison? :grinning:

**Comment by garrison** [comment]
Thanks!

**Comment by ihnorton** [comment]
@ScottPJones: I don't think anyone has found it necessary (or prudent) to explicitly ask for commit access in the past.

**Comment by ScottPJones** [comment]
@ihnorton - being rather serious today?
Did I ask for commit access?  No. (You did notice the smiley, right?)
I was just curious about how long it generally was before people were given that sort of access,
as I have noticed that a number of people (at least those that I've been interacting with), are marked as either "Owner" or "Collaborator".
At some point, I do think I'd be a good resource for reviewing other people's Unicode/string related code, but I still have a lot to learn about the guts of Julia first.

**Comment by tkelman** [comment]
Usually at least a few months, and maybe 50-ish commits, from what I've seen. Sometimes less (e.g. working on a big project where it would be useful to have a collaborative branch in this repo), sometimes more.

**Comment by ScottPJones** [comment]
@tkelman Thanks for the very informative response!  I know I've still got a lot to learn (and I'm very appreciative of everybody who's put up with me and given me great advice, on Git, GitHub, Julia, etc.).
I'm bouncing around number 50 on the list of contributors to the core (out of 363), and my goal is to breach into the exalted ranks of the top 25 by the end of the year :grinning: [that is, if I can convince people to merge any more of my changes!]

**Pull request merged**
