### PR TITLE
Remove SuiteSparse_wrapper and winclang patch

### LINKED ISSUE #764: upstream SuiteSparse winclang patch
https://github.com/JuliaLang/julia/blob/master/deps/patches/SuiteSparse-winclang.patch

Should be upstreamed here: https://github.com/DrTimothyAldenDavis/SuiteSparse

### PR DESCRIPTION
**Pull request by ViralBShah**
Thanks to SuiteSparse.jl now in its own repo, we have been able to rapidly move and get rid of a bunch of old stuff.

Fix https://github.com/JuliaLang/SuiteSparse.jl/issues/11
Fix https://github.com/JuliaLang/LinearAlgebra.jl/issues/764

This is all possible thanks to @Gnimuc!

### CODE REVIEW

**Comment by ViralBShah** [comment]
We'll adopt this change starting with SuiteSparse 5.10.1. This PR will be updated to use the newer version once we merge it in Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/3099

**Comment by ViralBShah** [comment]
@Gnimuc When we want to use a newer version of SuiteSparse, do we need to make any changes to SuiteSparse.jl's auto-generated wrappers. IIRC, we do check for version numbers in the code - so that may be necessary.

There really should be no changes between 5.8.1 and 5.10.1, but it gives us a clean new version to adopt in Julia 1.7, where we can stop shipping the wrappers.

**Comment by Gnimuc** [comment]
If the new version of `SuiteSparse_jll` doesn't have new C macro definitions that Clang.jl cannot currently handle, then we're good. Even if that happens, we can simply add them to [this list](https://github.com/JuliaLang/SuiteSparse.jl/blob/ec4b40ad9c0490ebf0969a41d4f880620db3f6f9/gen/generator.toml#L9). We should re-run the generator script whenever the version of `SuiteSparse_jll` is bumped.

**Comment by ViralBShah** [comment]
I am just in the process of bumping it all, and just merged 5.10.1 into Yggdrasil. This way we can keep making new releases if we run into issues, without disrupting older Julia releases (1.6 and earlier).

**Pull request merged**
