### PR TITLE
Add qrfact(SparseMatrixCSC) by wrapping SPQR.

### PR DESCRIPTION
**Pull request by andreasnoack**
Also make `\(SparseMatrixCSC)` work for least squares problems.

### CODE REVIEW

**Comment by jiahao** [comment]
:clap:

**Comment by andreasnoack** [comment]
Now including the new files and with the typos corrected.

**Comment by ViralBShah** [comment]
This also needs a mention in NEWS.

**Comment by andreasnoack** [comment]
The test error is not related to this pr so I'll merge. The error is because a test matrix sometimes doesn't have zero pivots even though it has most of the time. We might want to adjust the test a bit if it shows up more often.

**Comment by tkelman** [comment]
Can we use a known constant test matrix that causes that condition? CI failures should be taken seriously and if they have known, straightforward solutions we should fix them.

**Comment by andreasnoack** [comment]
Yes, we can construct a matrix that fails deterministically instead, so that is the way to avoid this problem.

**Comment by andreasnoack** [comment]
With https://github.com/JuliaLang/julia/commit/ab72de8ba9665ae9e768826b6c3edd9be7cb3118 we shouldn't see the random test failures from `cholmod.jl` anymore.

**Pull request merged**
