### PR TITLE
RFC: add a few GC roots to ast.c

### PR DESCRIPTION
**Pull request by timholy**
This is me playing around with the callgraph stuff I mentioned in #10248. Here I'm testing my understanding and asking for review; I'm going to take the liberty of assigning @JeffBezanson since this gets into interactions with flisp, and no one understands the flisp code like Jeff. 

If my understanding is clear, the ~~first~~ second commit seems pretty straightforwardly necessary. The ~~second~~ first I understand less well, and I suspect there's a good chance that either it's unnecessary or, worse, a half-measure that needs much more serious surgery. To me `scm_to_julia_` looks problematic: after [`iscons(e)`](https://github.com/JuliaLang/julia/blob/235576d7410808095c56d1686413f9f3be881de6/src/ast.c#L280) there seems to be a heap of unsafe code, which is why I suspect that `scm_to_julia` simply [disables gc](https://github.com/JuliaLang/julia/blob/235576d7410808095c56d1686413f9f3be881de6/src/ast.c#L195-L197). The problem is, this isn't the only route into the function: it's also called by [`full_list`](https://github.com/JuliaLang/julia/blob/235576d7410808095c56d1686413f9f3be881de6/src/ast.c#L172), which does not take similar precautions. I don't know what `car_(e)` does---maybe it guarantees that `iscons(e)` will be false?---but I thought I'd better raise the concern for someone with suitable expertise to address.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I'm pretty sure the only way into those functions is through `scm_to_julia`, which disables gc.

**Comment by JeffBezanson** [comment]
`jl_lam_args` doesn't allocate, so I don't think the other commit is necessary either.

**Comment by timholy** [comment]
Argh, I didn't think to check who could call `full_list`, so you're absolutely right about the one.

Just to double-check on the other, to me it looks like `jl_uncompress_ast` can allocate, and `jl_arrayref` can end up calling `jl_gc_collect` prior to any protection of its argument.

**Comment by JeffBezanson** [comment]
Ah, you're right about `jl_arrayref`. But I think that can be changed to a `jl_cellref`, which doesn't allocate.

**Comment by timholy** [comment]
OK, how about I'll let you decide what to do and close this. I guess 1/2 isn't bad for a start.

**Comment by ViralBShah** [comment]
Should we open an issue for the changes discussed here?

**Comment by JeffBezanson** [comment]
There aren't any changes needed.

**Comment by timholy** [comment]
I thought we needed to switch to `jl_cellref`? As it is we have a missing GC root, which seems like nothing to sneeze at given how much instability we're seeing on Travis, AppVeyor, and user reports of segfaults/hangs.

But I'll submit that change as another PR, after going through a few more files.

**Comment by JeffBezanson** [comment]
jl_arrayref allocates in general, but not when given a pointer array, which is what we have here.

**Comment by StefanKarpinski** [comment]
Perhaps some comments explaining the reasoning behind why no roots are needed?

**Comment by timholy** [comment]
Ah, thanks for explaining.

**Pull request closed without merging**
