### PR TITLE
move Sockets out of Base

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Nice!

**Comment by vtjnash** [comment]
Agreed, nice! I suppose you're really trying to make sure I don't upgrade libuv though (#25062)... :(

**Comment by JeffBezanson** [comment]
No, we can still do that. Either of these PRs shouldn't be too hard t rebase around the other.

**Comment by JeffBezanson** [comment]
Hrm, one wrinkle here is that we allow a TCPSocket as a standard I/O stream, which makes Base depend on it. Do we need that feature?

**Comment by JeffBezanson** [comment]
Ok, I'll just keep that for now, with the usual `Ref{Module}` hack, and we can decide what to do with it separately.

**Comment by JeffBezanson** [comment]
Interesting --- on CircleCI only, the `listenany` test is not able to find a port, but I haven't figured out what about these changes might cause that.

**Comment by JeffBezanson** [comment]
Problem solved; `--skip socket` needed to change to `--skip Sockets` in the circleci config.

**Comment by fredrikekre** [comment]
```
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
 !! No doc found for reference '[`TCPSocket`](@ref)'. [src/base/io-network.md]
```

I think this is the same issue as https://github.com/JuliaLang/julia/pull/25706#issuecomment-360169734

**Comment by ararslan** [comment]
Was `bind` intentionally omitted from deprecation here?

**Comment by JeffBezanson** [comment]
`Base.bind` has a meaning for Channels.

**Comment by ararslan** [comment]
Ah, okay. Thanks for clarifying.

**Pull request merged**
