### PR TITLE
Add LQ decomposition for SparseArrays.

### PR DESCRIPTION
**Pull request by SomTambe**
What does this PR do?
- [x] Add LQ decomposition feature for SparseArrays.
- [ ]  Tests are added.

For more details, refer to issue #39632 .

### CODE REVIEW

**Comment by SomTambe** [comment]
If someone could help me with where I can add the tests, it would be great. 
I just can't seem to find where are the QR decomposition tests too.

**Comment by sostock** [comment]
I think it’s unfortunate that the `lq` function returns a QR factorization in this case. This should at least be documented.

Maybe it would be better to just throw an `ArgumentError` that recommends the user to call `qr(SparseMatrixCSC(A'))` on their own? We could also add a custom `qr(::adjoint(::SparseMatrixCSC))` method so that the user can simply call `qr(A')` and still get the sparse QR factorization instead of the dense one.

**Comment by SomTambe** [comment]
@sostock hmm, what you say makes sense to me. Although LQ is actually only the QR decomposition of `transpose(A)`, it should return LQ only. Let me have a look to make something better.

**Comment by SomTambe** [comment]
@sostock I think it would be better that we document that the LQ of a `SparseArray` returns the QR factorization. I am saying so since I am using the SuiteSparse wrapper of `LinearAlgebra.qr(::SparseMatrixCSC)` which is more efficient in the case of SparseArray operations.

Also, let me see what we can do about adding a method `qr(::adjoint(::SparseMatrixCSC))`. It would make the code more readable.

But do think over what I have said about the SuiteSparse wrapper I am using for QR decomposition.

**Comment by dkarrasch** [comment]
Can't you do something along the lines
```julia
function lq(A::SparseMatrixCSC)
    F = qr(A')
    return LQ(F.R', F.Q')
end
```
?

**Comment by SomTambe** [comment]
> EDIT: Hm, it's more complicated than that. `qr` for a sparse matrix returns a different type than `qr` for a dense matrix. Since there is no "`SuiteSparse.SPLQ.LQSparse`" and also no `adjoint(::SuiteSparse.SPQR.QRSparse)`, it's not going to work via double-adjoint.

@dkarrasch Exactly. I think retaining the most efficient method should be done, which is using `SuiteSparse.SPQR.QRSparse`. Apart from that, I think adding a method `qr(::adjoint(::SparseMatrixCSC))` is more desirable.

**Comment by dkarrasch** [comment]
To me, it doesn't feel right to have an `lq` function that returns a `QR` object. As long as we don't have full/some support for LQ of sparse matrices, I think we should support `qr(::AdjOrTrans)` and `::Adjoint{<:Any,<:QR}` better: `*div!` and `mul!` and all that. I believe we have open issues for that, actually. Then users will (a) know there is something missing in our ecosystem, but (b) can choose deliberately to use `qr(A')'`.

**Comment by SomTambe** [comment]
@dkarrasch I have done what was needed. Kindly let me know if anything needs to be changed.

**Comment by dkarrasch** [comment]
Ok, that was the easy part. 😜 The more difficult part, which would be very much appreciated (see #38293, #35421), is to

* allow taking the adjoint of `qr(A::SparseMatrixCSC)`. Currently, we have
  ```julia
  julia> qr(sprand(10, 20, 0.2))'
  ERROR: MethodError: no method matching adjoint(::SuiteSparse.SPQR.QRSparse{Float64, Int64})
  ```
  This could be `adjoint(A::SuiteSparse.SPQR.QRSparse) = Adjoint(A)`.
* add solvers `ldiv!(::Adjoint{<:Any, SuiteSparse.SPQR.QRSparse}, ::AbstractVecOrMat)` and `rdiv!`.

**Comment by sostock** [comment]
>     * allow taking the adjoint of `qr(A::SparseMatrixCSC)`

This is also not supported for dense QR factorizations. Should it work for all of them?

**Comment by dkarrasch** [comment]
> This is also not supported for dense QR factorizations. Should it work for all of them?

Ideally yes, of course.

**Comment by SomTambe** [comment]
@dkarrasch Cool, let me have a look!

**Comment by SomTambe** [comment]
@dkarrasch Could you explain a bit what you mean by the adjoint of a QR decomposition? 
There exists an array `Q` and 'R', so how would I define an adjoint for the decomposition as a whole?

**Comment by dkarrasch** [comment]
If you have `adjF = Adjoint(qr(A))`, then you can define `F = parent(adjF)`, which is going to be the `qr(A)`, and then you can access the usual `QR*` fields via `F.Q` etc. So, you want to use the information contained in the QR of `A`. For instance, you can imagine that `A' = (Q*R)' = R'Q'` (up to potential pivots) and use that to solve `A'\b`.

**Comment by SomTambe** [comment]
> * add solvers `ldiv!(::Adjoint{<:Any, SuiteSparse.SPQR.QRSparse}, ::AbstractVecOrMat)` and `rdiv!`.

I couldn't find any solvers for `lmul!` and `rmul!` too.
```julia
julia> qr(randn(4,4))*randn(4,1)
ERROR: MethodError: no method matching *(::LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}, ::Array{Float64,2})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  *(::Adjoint{var"#s828",var"#s827"} where var"#s827"<:SparseArrays.AbstractSparseMatrixCSC where var"#s828", ::Union{StridedArray{T, 2}, Adjoint{var"#s828",var"#s827"} where var"#s827"<:Union{StridedArray{T, 2}, LowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s828", LowerTriangular{T,S} where S<:AbstractArray{T,2}, Transpose{var"#s826",var"#s825"} where var"#s825"<:Union{StridedArray{T, 2}, LowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s826", UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where T) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:75
  *(::Transpose{var"#s828",var"#s827"} where var"#s827"<:SparseArrays.AbstractSparseMatrixCSC where var"#s828", ::Union{StridedArray{T, 2}, Adjoint{var"#s828",var"#s827"} where var"#s827"<:Union{StridedArray{T, 2}, LowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s828", LowerTriangular{T,S} where S<:AbstractArray{T,2}, Transpose{var"#s826",var"#s825"} where var"#s825"<:Union{StridedArray{T, 2}, LowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s826", UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, UpperTriangular{T,S} where S<:AbstractArray{T,2}} where T) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:101
  ...
Stacktrace:
 [1] top-level scope at REPL[7]:1
```
We need to add them too right? @dkarrasch

**Comment by dkarrasch** [comment]
Sorry for my late response.

> We need to add them too right?

Ideally yes. It shouldn't be too hard once you figure out where the permutations go.

**Comment by ViralBShah** [comment]
This will now need to go to the new SuiteSparse.jl repo.

**Pull request closed without merging**
