### PR TITLE
Silence an unused variable warning from Clang

### PR DESCRIPTION
**Pull request by ararslan**
Part of my never-ending quest to silence Clang warnings emitted when building Julia.

### CODE REVIEW

**Comment by yuyichao** [comment]
All macros should start with `JL_`. `_` prefix is actually reserved names.

I think we are just using `(void)` directly. It's a pretty standard C trick and is actually shorter to type than `JL_UNUSED()`.....

**Comment by ararslan** [comment]
Okay, so rather than introducing a macro for this, I should change `_UNUSED(truncret)` to `(void)truncret`?

**Comment by yuyichao** [comment]
Yes, I think that's good enough. C macros are mainly useful when there's compiler dependent definitions or if the definition is actually complicated. unused is neither. It also conflicts with a potential useful macro that uses the `unused` attribute to mark unused functions so I was especially avoiding introducing it as a void cast.

**Comment by ararslan** [comment]
Okay, I'll make that change. Thanks!

**Review by yuyichao — APPROVED** [review]

**Pull request merged**
