### PR TITLE
Remove julia 0.3 deprecations

### PR DESCRIPTION
**Pull request by Keno**
Seems like the time is about right, plus Gadfly is broken right now because of the `Stat` deprecation, so if we're gonna remove the deprecations anyway, might as well do it now.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
+1

**Comment by JeffBezanson** [comment]
Should we also flip the switch to get the new behavior of `[a, b]`?

**Comment by StefanKarpinski** [comment]
Don't we need to go through a deprecation cycle for that? I.e. wait until 0.5-dev.

**Comment by JeffBezanson** [comment]
The main problem with that is the rather severe overhead of this code:
https://github.com/JuliaLang/julia/blob/0c56dd2fd1aaa226d7b37f8be86f3f9941effe5d/base/abstractarray.jl#L33

Making arrays from mixed types with `[ ]` is currently about 4x slower than in 0.3 (e.g. #4467).

**Comment by kmsquire** [comment]
That would be good motivation to make the 0.5 development cycle really short. ;-)

**Comment by Keno** [comment]
I think the `[a, b]` switch needs to stay for 0.4 unfortunately. In any case, it should not be part of this commit, so I'll go ahead and merge.

**Comment by tkelman** [comment]
Looks like there weren't too many of these, but I think the right time to do this would have been coordinated with transitioning from 0.4-dev to 0.4-pre, and we still have several breaking changes open so I don't think we're ready for that quite yet.

**Comment by IainNZ** [comment]
This was fairly breaking, it turns out, although it might just be in a couple of base packages. Mostly `Range1`.

**Comment by Keno** [comment]
A lot of packages have been updated but not tagged yet.

**Comment by tkelman** [comment]
Do we have a doctest to make sure we remove the docs of deprecated functions? Either before or after we remove the last method definitions...

**Pull request merged**
