### PR TITLE
backport #42125: Allow constant-propagation to be disabled

### PR DESCRIPTION
**Pull request by simeonschaub**
This needed to be backported manually.

### CODE REVIEW

**Comment by KristofferC** [comment]
This feels a lot like a feature? Why shouldn't it adhere to the feature freeze like the other features?

**Comment by simeonschaub** [comment]
I thought that was the conclusion in #42188, but reading it again, I might have misunderstood. It does still have the backport label at least. I definitely share the concern, so this may not be a good idea at this point. @timholy @aviatesk Was that the conclusion, or do you still think that PR should be backported?

**Comment by Keno** [comment]
We don't have to backport the feature, but I'd support backporting the new macro name, because a bunch of packages have already updated to the breakage on master and would need to be un-updated.

**Comment by simeonschaub** [comment]
I think it may just break Diffractor, for the other packages I made it dependent on `isdefined(Base, Symbol("@constprop"))`, which would just mean that 1.7 is slower than master.

**Comment by KristofferC** [comment]
> because a bunch of packages have already updated to the breakage on master and would need to be un-updated.

I think they can just load `Compat`.

**Comment by Keno** [comment]
Ok. We can fix Diffractor, but it does seem odd to release something with a name that's already been removed on master. I don't feel strongly though. Up to @KristofferC I say, but @simeonschaub maybe you could put up a version that just uses the new macro name, but only supports the aggressive option for 1.7? Should be a two line change.

**Comment by simeonschaub** [comment]
So basically the thing that's currently defined in Compat?

**Comment by KristofferC** [comment]
Aren't there packages that use the old name?

**Comment by timholy** [comment]
Not anymore, they've all been updated to the new name or commented out. Last vestige I think is https://github.com/mcabbott/TransmuteDims.jl/issues/33, and I didn't check when it was commented out.

**Comment by timholy** [comment]
Not anymore, they've all been updated to the new name or commented out. Last vestige I think is https://github.com/mcabbott/TransmuteDims.jl/issues/33, and I didn't check when it was commented out.

**Pull request closed without merging**
