### PR TITLE
WIP / RFC: Restore soname mapping

### LINKED ISSUE #26557: `Libdl.dlopen` doesn't find shared libraries anymore
`Libdl.dlopen` doesn't seem to be able to find shared libraries the way it did on 0.6.x

**On Julia 0.6.x**
```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> lib = Libdl.dlopen("libz")
Ptr{Void} @0x00007f47adcb91a0
```

**On Julia 0.7.x-DEV**
```julia
julia> versioninfo()
Julia Version 0.7.0-DEV.4631
Commit 9a55c8fbc* (2018-03-19 03:59 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:

julia> using Libdl

julia> lib = Libdl.dlopen("libz")
ERROR: could not load library "libz"
libz.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String) at /builddir/build/BUILD/julia/build/usr/share/julia/site/v0.7/Libdl/src/Libdl.jl:99
 [2] top-level scope
 [3] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:117 [inlined]
 [4] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./event.jl:92

julia> lib = Libdl.dlopen("libz.so")
ERROR: could not load library "libz.so"
libz.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String) at /builddir/build/BUILD/julia/build/usr/share/julia/site/v0.7/Libdl/src/Libdl.jl:99
 [2] top-level scope
 [3] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/site/v0.7/REPL/src/REPL.jl:117 [inlined]
 [4] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./event.jl:92

julia> lib = Libdl.dlopen("libz.so.1")
Ptr{Nothing} @0x00007f139153b520
```
As you can see, it works once I specify the exact name of the shared library, but not before then.

**Other Details**
- Operating system: Linux (Fedora 27)

### PR DESCRIPTION
**Pull request by nsmith5**
Fixes #26557.

We need a consensus on whether this functionality should be restored or deprecated. I believe restoring is a better option and this pull request partially revert #22828 to that effect.

### CODE REVIEW

**Review by vtjnash — CHANGES_REQUESTED** [review]
Doesn't fix #26557 unless it adds tests (we've historically not had them because they frequently failed) and docs.

**Comment by nsmith5** [comment]
Agreed, do you have some examples of incorrect behaviour you've seen? In my mind the tests should check that dlopen / ccall have the same affect as the combined behaviour of the linker and loader in C, but any other thoughts you have on behaviour would be appreciated.

**Comment by nsmith5** [comment]
It might be nice if the soname mapping could happen in Julia in Libdl instead of in the C++ source. Easier to test / read / contribute to that way.

**Comment by nsmith5** [comment]
Relevant: [Loading GNU ld scripts with dlopen](https://stackoverflow.com/questions/34879686/loading-gnu-ld-script-with-dlopen).

**Comment by ararslan** [comment]
Toy implementation of .so name mapping, translated from the C++ code here: https://github.com/ararslan/SONames.jl

**Comment by vtjnash** [comment]
FWIW, there's a non-toy copy of the same in BinDeps.jl. It's certainly been proposed before that we could have that live in stdlib instead.

**Comment by nsmith5** [comment]
Also relevant: [python ctypes find_library](https://github.com/python/cpython/blob/c0919c27c6442aa147ae559a936b1b8deb4ee783/Lib/ctypes/util.py#L93)

**Comment by brenhinkeller** [comment]
The fact that every single example of ccall over at https://docs.julialang.org/en/v1.0/manual/calling-c-and-fortran-code/ relies on this soname mapping (and is currently broken because of #22828) should be all anyone needs to know.

**Comment by Keno** [comment]
We've moved towards being more explicit about paths in our binary infrastructure and the documentation was updated, so I believe this is outdated now.

**Comment by brenhinkeller** [comment]
So for reference, when this was first proposed, super simple things like `ccall((:clock, "libc"), Int32, ())` were briefly broken unless you specified _which_ libc you wanted. That was fixed pretty quickly, but I guess in some other way than by restoring internal soname mapping?

**Comment by Keno** [comment]
That still doesn't work on systems where the global libc is a linker script that gets remapped with ld.so shenanigans, but the examples were fixed to refer to the global symbol instead.

**Pull request closed without merging**
