### PR TITLE
Specialize axes for structured matrices

### PR DESCRIPTION
**Pull request by jishnub**
On master
```julia
julia> S = SMatrix{4,4}(1:16);

julia> A = StructArray{Complex{Int}}((S,S));

julia> axes(Symmetric(A))
(Base.OneTo(4), Base.OneTo(4))
```
The static axes are lost. After this,
```julia
julia> axes(Symmetric(A))
(SOneTo(4), SOneTo(4))
```
Similarly, I've added methods for other structured matrix types. These help with other cases like infinite arrays.

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
LGTM.

**Comment by stevengj** [comment]
CI failures seem unrelated; maybe try clicking the "updated branch" button to sync with latest `master`?

**Comment by jishnub** [comment]
Test failure in `gc` looks unrelated, so perhaps this should be good to go?

**Comment by jishnub** [comment]
Gentle bump

**Pull request merged**
