### PR TITLE
Depwarn caller fix

### PR DESCRIPTION
**Pull request by c42f**
This fixes the core problem of #25130, namely that on occasion - and especially at top level scope - the internal dispatch or interpreter machinery was being blamed as the caller of a deprecated function.

Along the way I also noticed what was arguably a bug in `global_logger(logger)`, so that's also fixed to more usefully return the old logger rather than the replacement.

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

**Comment by c42f** [comment]
CI failure seems unrelated... if potentially serious

```
      From worker 8:	julia: /home/circleci/project/deps/srccache/llvm-3.9.1/lib/MC/MCContext.cpp:118: llvm::MCSymbol* llvm::MCContext::getOrCreateSymbol(const llvm::Twine&): Assertion `!NameRef.empty() && "Normal symbols cannot be unnamed!"' failed.
      From worker 8:	
      From worker 8:	signal (6): Aborted
```

**Comment by StefanKarpinski** [comment]
cc @vtjnash ^

**Comment by c42f** [comment]
Can this be merged? It's a small bugfix, CI has passed, and I want to build some other things on top of it.

**Comment by StefanKarpinski** [comment]
Should I squash or not?

**Comment by c42f** [comment]
I think not, the two commits here represent distinct changes.

**Pull request merged**
