### PR TITLE
Added degree trig functions on square matrices

### LINKED ISSUE #651: implement degree trig functions on square matrices
See this closed PR: https://github.com/JuliaLang/julia/pull/27254.

### LINKED ISSUE #32876: implement degree trig functions on square matrices
See this closed PR: https://github.com/JuliaLang/julia/pull/27254.

### PR DESCRIPTION
**Pull request by pmk21**
Fixes JuliaLang/LinearAlgebra.jl#651.
I have added trig functions which are compatible with square matrices.
Please advice on any further changes to be made to docs, tests etc.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This just duplicates my PR that was not merged and has been closed.

**Comment by ViralBShah** [comment]
@StefanKarpinski Do you have a link to your PR?

**Comment by pmk21** [comment]
I have generalized the `deg2rad` and `rad2deg` functions to act on matrices as well as arrays. I am quite unsure of the tests to be added and the required docs to be changed. 
@StefanKarpinski Could you please provide some hint?

**Comment by simonbyrne** [comment]
Do you actually have a use case for this? Part of the reason I'm opposed is that it doesn't actually help with the problem that `sind` fixes (e.g. `sind(180) == 0`).

**Comment by laborg** [comment]
This has been stale for 4 years and implemented in https://github.com/JuliaLang/julia/pull/39758

**Pull request closed without merging**
