### PR TITLE
[release-0.5] backport #18583

### PR DESCRIPTION
**Pull request by shashi**
Hope I'm doing this right.

### CODE REVIEW

**Comment by tkelman** [comment]
add a cross reference to the original PR in the commit message

**Comment by jlbuild** [comment]
I'm sorry, I couldn't parse out any valid commands from your comment.
Please see my [README](https://github.com/jlbuild/jlbuild.jl) for instructions on how to use me.

**Comment by tkelman** [comment]
that's odd. @staticfloat I'm shutting that off for now.

**Comment by shashi** [comment]
Done.

**Comment by staticfloat** [comment]
Hah. Looks like I've got some fine tuning to do. :)

**Pull request merged**
