### PR TITLE
Add `OpenBLAS v0.3.5` patch for AVX512 `SGEMM` selection

### LINKED ISSUE #30696: Undefined reference to `sgemm_kernel_direct` during OpenBLAS build
When using ccache, OpenBLAS build regularly fails with:
```
../libopenblas64_p-r0.3.5.a(cblas_sgemm.o): In function `cblas_sgemm':
gemm.c:(.text+0x582): undefined reference to `sgemm_kernel_direct_performant'
gemm.c:(.text+0x5d6): undefined reference to `sgemm_kernel_direct'
```
Most likely explanation is a race condition inside the OpenBLAS build system.

### PR DESCRIPTION
**Pull request by staticfloat**
Fixes https://github.com/JuliaLang/julia/issues/30696

### CODE REVIEW

**Comment by staticfloat** [comment]
Closing, as 0.3.7 is released now, which contains this patch.  We'll just upgrade to 0.3.7 eventually.

**Comment by chriscoey** [comment]
@staticfloat Is there any reason to delay a 0.3.7 upgrade? Would be nice to have that now.

**Comment by staticfloat** [comment]
Don't worry, I'm on it. :)

While it's not top priority, it should happen in the next couple of days.  [The binaries are actually already built](https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/tag/OpenBLAS-v0.3.7%2B0), but there are a few other things I need to upgrade in the Makefile buildsystem, and we need to rebuild ARPACK, Suite Sparse, etc...

**Comment by chriscoey** [comment]
Thank you, looking forward to OpenBLAS 0.3.7

**Pull request closed without merging**
