### PR TITLE
Backports for 1.10.6

### LINKED ISSUE #45494: Error in SSA conversion (crashes on several Julia versions including 1.9 and master)
The following relatively simple script dumps core on Linux:

```julia
#!/usr/bin/julia

struct Aa
  train!::Function
end

function createa()
  x::Vector{T} where T<:Real = fill(NaN,0)

  train = () -> begin
    a = zeros(1, 100)

    x = ones(size(a,2)-1)
    a * vcat(x, 1)
    return x
  end

  Aa(train)
end

a = createa()
a.train!()
```

Linux: Versions 1.7.2 and 1.7.3 on x86_64 and version 1.7.0 on aarch64 exhibit the problem.

Windows 10: Version 1.6.2 on x86_64 crashes the REPL.

Linux: Version 1.4.2 on x86_64 does not have the problem.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #51755 <!-- ASAN fixes. -->
- [x] #55329 <!-- mapreduce: don't inbounds unknown functions -->
- [x] #55365 <!-- ml-matches: ensure all methods are included -->
- [x] #55483 <!-- fix hierarchy level of "API reference" in `Dates` documentation -->
- [x] #55268 <!-- simplify complex atanh and remove singularity perturbation -->
- [x] #55504 <!-- Update symmetric docstring to reflect the type of uplo -->
- [x] #55524 <!-- Set `.jl` sources as read-only during installation -->
- [x] #41244 <!-- Fix shell `cd` error when working dir has been deleted -->
- [x] #55829 <!-- [Dates] Make test more robust against non-UTC timezones -->
- [x] #55641 <!-- fall back to slower stat filesize if optimized filesize fails -->
- [x] #55849 <!-- Mmap: fix grow! for non file IOs -->
- [x] #55945 <!-- Fix logic in `?` docstring example -->
- [x] #55743 <!-- doc: heap snapshot viewing -->
- [x] #56023 <!-- Sockets: Warn when local network access not granted. -->
- [x] #54276 <!-- Fix solve for complex `Hermitian`  with non-vanishing imaginary part on diagonal -->
- [x] #54669 <!-- Improve error message in inplace transpose -->
- [x] #55295 <!-- LAPACK: Aggressive constprop to concretely infer syev!/syevd! -->
- [x] #55303 <!-- avoid overflowing show for OffsetArrays around typemax -->
- [x] #55342 <!-- Ensure bidiagonal setindex! does not read indices in error message -->
- [x] #55507 <!-- Fix fast getptls ccall lowering. -->
- [x] #55522 <!-- Fix tr for Symmetric/Hermitian block matrices -->
- [x] #55854 <!-- 🤖 [master] Bump the Downloads stdlib from 1061ecc to 89d3c7d -->
- [x] #55863 <!-- Update TaskLocalRNG docstring according to #49110 -->
- [x] #55567 <!-- Initialize threadpools correctly during sysimg build -->
- [x] #55506 <!-- Fix indexing in _mapreducedim for OffsetArrays -->
- [x] #54737 <!-- LazyString in interpolated error messages involving types -->

Need manual backport:
- [ ] #55299 <!-- typeintersect: fix bounds merging during inner `intersect_all`. -->
- [ ] #55405 <!-- handle unbound vars in NTuple fields -->
- [ ] #55744 <!-- fix #45494, error in ssa conversion with complex type decl -->
- [ ] #55773 <!-- Add compat entry for `Base.donotdelete` -->
- [ ] #55890 <!-- Profile: fix order of fields in heapsnapshot & improve formatting -->

Contains multiple commits, manual intervention needed:
- [ ] #52854 <!-- Change to streaming out the heap snapshot data -->
- [ ] #53833 <!-- Profile: make heap snapshots viewable in vscode viewer -->
- [ ] #54303 <!-- LinearAlgebra: improve type-inference in Symmetric/Hermitian matmul -->
- [ ] #52694 <!-- Reinstate similar for AbstractQ for backward compatibility -->
- [ ] #54738 <!-- serialization: fix relocatability bug -->
- [ ] #55052 <!-- Fix `(l/r)mul!` with `Diagonal`/`Bidiagonal` -->
- [ ] #55180 <!-- compress jit debuginfo for easy memory savings -->
- [ ] #55251 <!-- Restrict binary ops for Diagonal and Symmetric to Number eltypes -->
- [ ] #55306 <!-- AllocOpt: Fix stack lowering where alloca continas boxed and unboxed data -->
- [ ] #55509 <!-- Fix cong implementation to be properly random and not just cycling. -->
- [ ] #55720 <!-- Fix `pkgdir` for extensions -->
- [ ] #55729 <!-- Avoid confounding compilation side effects of `@time_imports` -->
- [ ] #55589 <!-- prevent loading other extensions when precompiling an extension -->
- [ ] #55877 <!-- fix FileWatching designs and add workaround for a stat bug on Apple -->

Non-merged PRs with backport label:
- [ ] #55959 <!-- REPL: hide any prints to stdio during `complete_line` -->
- [ ] #55958 <!-- also redirect JL_STDERR etc. when redirecting to devnull -->
- [ ] #55956 <!-- Make threadcall gc safe -->
- [ ] #55941 <!-- Fix zero elements for block-matrix kron involving Diagonal -->
- [ ] #55910 <!-- Prevent extensions from blocking parallel pre-compilation -->
- [ ] #55886 <!-- irrationals: restrict assume effects annotations to known types -->
- [ ] #55870 <!-- fix infinite recursion in `promote_type` for `Irrational` -->
- [ ] #55867 <!-- update `hash` doc string: `widen` not required any more -->
- [ ] #55813 <!-- Check for conflicting `@ccallable` name before JIT registration -->
- [ ] #55802 <!-- Remove llvm-muladd pass and move it's functionality to to llvm-simdloop -->
- [ ] #55534 <!-- Set stdlib sources as read-only during installation -->
- [ ] #55499 <!-- propagate the terminal's `displaysize` to the `IOContext` used by the REPL -->
- [ ] #55311 <!-- docs: Add headers for easier Core, Base and stdlib reference -->
- [ ] #55220 <!-- `isfile_casesensitive` fixes on Windows -->
- [ ] #55169 <!-- `propertynames` for SVD respects private argument -->
- [ ] #51479 <!-- prevent code loading from lookin in the versioned environment when building Julia -->
- [ ] #50813 <!-- More doctests for Sockets and capitalization fix -->
- [ ] #50157 <!-- improve docs for `@inbounds` and `Base.@propagate_inbounds` -->

### CODE REVIEW

**Comment by giordano** [comment]
The [test](https://github.com/JuliaLang/julia/pull/55365/files#diff-90c3a7a047872b9929e6577e16ad589a77552d0de0400c98cf303b6b7204e683R7568) modified by the backport of #55365 is [failing on this branch](https://buildkite.com/julialang/julia-release-1-dot-10/builds/372#01922968-3f94-4e74-a6e3-db5f00c21838/849-1633):
```
Error in testset core:
Test Failed at /cache/build/tester-amdci5-15/julialang/julia-release-1-dot-10/julia-f21154fd2e/share/julia/test/core.jl:7545
  Expression: length(methods(foo31696)) == 2
   Evaluated: 1 == 2
```

**Comment by IanButterworth** [comment]
Pkg backports which should fix CI incoming https://github.com/JuliaLang/Pkg.jl/pull/4036

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55746#issuecomment-2417098901) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3ba6c16_vs_6f3fdf7/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["JuliaInterpreter", "KissMCMC", "ParallelStencil", "BenchmarkProfiles", "SmoQyHankelCorrCleaner", "Boscia", "ReducedComplexityModeling", "GMT", "FSimBase", "RealTimeAudioDiffEq", "SurfaceReactions", "JointSurvivalModels", "ControlBarrierFunctions", "GeophysicalModelGenerator", "ReactionSensitivity", "HarmonicBalance"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55746#issuecomment-2422190416) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/25ee4ea_vs_6f3fdf7/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(vs = ":release-1.10")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.10")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55746#issuecomment-2427580732) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/2b240ac_vs_6f3fdf7/report.md).

**Pull request merged**
