### PR TITLE
replace BitArray(shape...) constructors/calls with BitArray(uninitialized, shape...)

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request deprecates uninitialized-`BitArray` constructors of the form `BitArray[{N}](shape...)` in favor of `BitArray[{N}](uninitialized, shape...)` equivalents. For background, please see #24595. Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
Rebased and added the `similar(funcortype, inds...) = funcortype(inds...)` -> `... = funcortype(uninitialized, inds...)` fix from https://github.com/JuliaLang/julia/pull/24781#issuecomment-347038828, which hopefully will take care of most of the depwarns. Best!

**Comment by Sacha0** [comment]
Rebased again, changed to more conservative `similar(funcortype, shape)` changes, and fixed all test failures locally. What say you now, CI?

If CI approves and absent objections or requests for time, I plan to merge these changes this evening PT or later. Best!

**Comment by fredrikekre** [comment]
I think this broke some constructors, noticed in https://github.com/JuliaArrays/OffsetArrays.jl/pull/34

v0.6:
```julia
julia> BitArray(1:2)
2-element BitArray{1}:
 true
 true
```

master:
```julia
julia> BitArray(uninitialized, 1:2)
ERROR: MethodError: no method matching BitArray(::Uninitialized, ::UnitRange{Int64})
Closest candidates are:
  BitArray(::Uninitialized, ::Integer...) at bitarray.jl:57
  BitArray(::Uninitialized, ::Tuple{Vararg{Int64,N}}) where N at bitarray.jl:59
  BitArray(::Any) at bitarray.jl:556
```

**Comment by Sacha0** [comment]
Yes, OffsetArrays will require definitions like [those added to `test/TestHelpers.jl`](https://github.com/JuliaLang/julia/blob/039611acf935ecba0f90400c012e0a6400dd80a6/test/TestHelpers.jl#L184) for the `OffsetArray` implementation in `Base` :). Best!

**Pull request merged**
