### PR TITLE
re-enable the bell ("beep")

### PR DESCRIPTION
**Pull request by srp**
Feedback is important. When I hit `tab` I shouldn't be stuck wondering
if the system isn't responding, or if there are just no completions.

I also agree with those that hate the audio bell but what to do with
'\a' is a terminal setting, and most terminals can be configured to
give a visual bell (a brief flash), or disable completely. So this is
not something that each shell/program needs to also have configuration
for.

How to configure the bell for assorted terminals:

  OSX: http://superuser.com/questions/163994/how-can-i-get-the-mac-terminal-to-not-beep
  Gnome Terminal: Edit -> Profile Preferences -> Terminal Bell
  KDE Konsole: Settings -> Configure Notifications
  XTerm: add the following to .Xdefaults/.Xresources: xterm_visualBell:true
  URxvt: add the following to .Xdefaults/.Xresources: URxvt_visualBell:true
  XWindows: disable across all programs by runnings: xset b off

---
This change is [Reviewable](https://reviewable.io/reviews/julialang/julia/9710)

### CODE REVIEW

**Comment by tkelman** [comment]
-1, would much rather it be off by default

**Comment by vtjnash** [comment]
i think it's appropriate to respect the terminal defaults. +1 to re-enabling this.

but -1 to adding an environment variable

(full disclosure: i disable beep in my terminals, so this is a non-functional change for me)

**Comment by nalimilan** [comment]
+1 too. I don't think the programs should decide whether to beep or not, better leave it up to the terminal. I also don't think an environment variable is needed here.

**Comment by simonster** [comment]
I would prefer that we provide some kind of visual feedback when there are no completions that's not a beep. I think most users find the beep intrusive, and especially for new users who don't know which commands exist and which don't, the beeping frenzy could get annoying fast. We could have a `--beep=no` command line option that we use for the OS X and Windows launcher, or try to disable the beep in the terminal profiles on those platforms, but I think nearly everyone would be happier with a visual indicator. Maybe we can just print "no completions found" in gray at the end of line if it fits, and then clear it on next keystroke?

**Comment by mschauer** [comment]
+1 for the visual feedback. The bell is useful for programs that need to get the attention while out of focus, but julia tab completion always happens in focus.
So there are good reasons to leave the bell activated and still prefer julia to make a visual feedback.

**Comment by brk00** [comment]
+1 for the visual feedback

**Comment by mbauman** [comment]
You know, most terminals have that setting?  This seems like something that we leave up to the terminal.  And perhaps ship with a better terminal if the builtin terminal on a system is bad.

Terminal.app:
screen shot 2015-01-15 at 8 12 42 pm


iTerm2:
screen shot 2015-01-15 at 8 13 18 pm

**Comment by tkelman** [comment]
Disabling the terminal beep in the Windows console requires admin access, afaict. It's easier in mintty, but we're not bundling that yet.

**Comment by mbauman** [comment]
We now have visual feedback!  I'm closing this since we now have #23201.

beep3

**Pull request closed without merging**
