### PR TITLE
Add setindex! for Diagonal

### LINKED ISSUE #168: Addition is broken for UniformScaling with AbstractMatrix types that don't define setindex!
`UniformScaling` assumes it can mutate a copy of the `AbstractMatrix` argument type [see here](https://github.com/JuliaLang/julia/blob/1eb52e89780a1784473c56543aac3ba5f8eacecf/base/linalg/uniformscaling.jl#L35-37) with `setindex!`.

Ex:

``` julia
julia> d = Diagonal(rand(5,5))
5x5 Base.LinAlg.Diagonal{Float64}:
 0.885176  0.0       0.0       0.0       0.0
 0.0       0.553487  0.0       0.0       0.0
 0.0       0.0       0.371698  0.0       0.0
 0.0       0.0       0.0       0.106945  0.0
 0.0       0.0       0.0       0.0       0.150074

julia> d + I
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37

julia> I + d
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37
 in + at linalg/uniformscaling.jl:28
```

### LINKED ISSUE #10004: Addition is broken for UniformScaling with AbstractMatrix types that don't define setindex!
`UniformScaling` assumes it can mutate a copy of the `AbstractMatrix` argument type [see here](https://github.com/JuliaLang/julia/blob/1eb52e89780a1784473c56543aac3ba5f8eacecf/base/linalg/uniformscaling.jl#L35-37) with `setindex!`.

Ex:
```julia
julia> d = Diagonal(rand(5,5))
5x5 Base.LinAlg.Diagonal{Float64}:
 0.885176  0.0       0.0       0.0       0.0
 0.0       0.553487  0.0       0.0       0.0
 0.0       0.0       0.371698  0.0       0.0
 0.0       0.0       0.0       0.106945  0.0
 0.0       0.0       0.0       0.0       0.150074

julia> d + I
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37

julia> I + d
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37
 in + at linalg/uniformscaling.jl:28
```

### PR DESCRIPTION
**Pull request by mbauman**
Fixes JuliaLang/LinearAlgebra.jl#168.

### CODE REVIEW

**Comment by ViralBShah** [comment]
This seems simple enough to merge right away.

**Comment by tkelman** [comment]
I agree.

**Comment by mbauman** [comment]
Thanks guys. I'm still a little gunshy about pushing straight to master. I wish there was a less noisy way to run a branch through CI before merging for stuff that doesn't really need review.

**Comment by tkelman** [comment]
AppVeyor uses a branch whitelist at the moment, you can temporarily add a branch name to the
```
branches:
  only:
```
list if you're worried about something and want to test it but not with a PR. Short-lived non-controversial PR's aren't the end of the world though.

**Pull request merged**
