### PR TITLE
manual/packages: make instructions more generic

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by bramtayl** [comment]
Not a big deal, but John Doe is a (typically) male anglophone name. In the interest of making Julia a smidge more welcoming, it might be nice to use Someone instead?

**Comment by kshyatt** [comment]
I like @bramtayl's idea but I'd split it up into "Some One" for Firstname Lastname.

**Comment by waldyrious** [comment]
Well, the document *is* written in English, and there is infrastructure set up to translate it into other languages. I'd imagine other languages would replace this name by [their equivalents](https://en.wikipedia.org/wiki/List_of_placeholder_names_by_language).

**Comment by waldyrious** [comment]
@kshyatt, @bramtayl any thoughts regarding my comment above?

**Comment by waldyrious** [comment]
Pinging @kshyatt, @bramtayl. I've fixed the merge conflict due to other PRs being merged in the meantime.

**Comment by aviks** [comment]
Well, even in English, I would hope we could be a little wider in our language. `Some One` seems like a good option.

**Comment by waldyrious** [comment]
Ok, I'll change.

**Comment by waldyrious** [comment]
Pinging @aviks, @bramtayl, @kshyatt -- please let me know if there's anything else to be changed here.

**Pull request merged**
