### PR TITLE
Fix missing gc root in jl_cglobal

### PR DESCRIPTION
**Pull request by Keno**
Static analysis complains that the jl_fieldref could allocate,
which then gets passed to jl_bitcast unrooted. I believe it's
right about that.

While we're here, also fix what I believe is a typo (`ty` vs `v`).

### CODE REVIEW

**Review by yuyichao — APPROVED** [review]
Seems that this would only fail in the error case.

**Comment by Keno** [comment]
Which error case are you referring to?

**Comment by Keno** [comment]
Hm, but doesn't the problematic case there explicitly allow it to be a pointer?

**Comment by vtjnash** [comment]
Yes, it looks like the order of checks here is wrong. Its not supposed to accept a 1-tuple of a pointer

**Comment by Keno** [comment]
Ok, we can switch around the conditional and use the non-allocating fieldref version then.

**Pull request merged**
