### PR TITLE
Initialize gvars with their pointer values in create_native

### PR DESCRIPTION
**Pull request by pchintalapudi**
GPUCompiler won't have access to the runtime pointers for global variables emitted from `jl_create_native`, so we need to provide them here.

### CODE REVIEW

**Comment by vtjnash** [comment]
I thought we had exported an accessor to get the mapping from index to global back, which avoids the need to embed runtime state like this. But the PR looks good to merge anyways if it is fixing issues for now.

**Comment by pchintalapudi** [comment]
Given that we have external consumers of `jl_create_native` modules, I think it's better to have the module be as complete and runnable as possible, without needing a side table to finish it off.

**Comment by vchuravy** [comment]
> I thought we had exported an accessor to get the mapping from index to global back

I don't think that is exported.

**Comment by vtjnash** [comment]
Oh, really? How do you manage to do anything without the expected struct accessors for the state: https://github.com/JuliaLang/julia/blob/2d24155119e2157ac0581a054a40b48a3d1e9a2b/src/aotcompile.cpp#L86-L116

**Comment by vchuravy** [comment]
We only use `jl_get_function_id`.

Can we use `arraylist_t` from Julia?

**Pull request merged**
