### PR TITLE
fix slurping into function definition

### PR DESCRIPTION
**Pull request by simeonschaub**
Discovered while working on #40737. Currently, this throws an
unintuitive error:
```julia
julia> a, f()... = 1, 2, 3
ERROR: syntax: ssavalue with no def
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

Might as well fix this properly - Why not allow function definitions to
slurp a little from time to time? ;)

### CODE REVIEW

**Comment by simeonschaub** [comment]
Not claiming it's necessarily all that useful, but I think this is pretty cool at least:
```julia
julia> x = [1, 2, 3];

julia> _, f()... = x;

julia> f()
2-element Vector{Int64}:
 2
 3

julia> x[3] = 4;

julia> f()
2-element Vector{Int64}:
 2
 4
```

**Comment by simeonschaub** [comment]
Bump.

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
Seems unhappy with some merge conflict?

**Comment by simeonschaub** [comment]
Might be related to #40737, will look into it.

**Comment by simeonschaub** [comment]
Yes, the example linked above now doesn't close over `x` anymore, but instead the call to `Base.rest` now happens outside of `f`'s body. I think with #40737 merged, this is actually the behavior we want.

**Pull request merged**
