### PR TITLE
Check undefined fields in `⊑`

### LINKED ISSUE #31164: Internal error when constructing a Measurement type
MWE:

```julia
julia> using Measurements

julia> 1 ± 1
Internal error: encountered unexpected error in runtime:
UndefRefError()
rec_backtrace at /home/ggnore/julia/src/stackwalk.c:94
jl_throw at /home/ggnore/julia/src/task.c:217
jl_f_getfield at /home/ggnore/julia/src/builtins.c:672
⊑ at ./compiler/typelattice.jl:151
⊑ at ./compiler/typelattice.jl:135
tmerge at ./compiler/typelimits.jl:283
typeinf_local at ./compiler/abstractinterpretation.jl:1110
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1215
typeinf at ./compiler/typeinfer.jl:12
typeinf_edge at ./compiler/typeinfer.jl:503
abstract_call_method at ./compiler/abstractinterpretation.jl:363
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:92
abstract_call at ./compiler/abstractinterpretation.jl:802
jfptr_abstract_call_570 at /home/ggnore/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/ggnore/julia/src/gf.c:2250
abstract_apply at ./compiler/abstractinterpretation.jl:545
abstract_call at ./compiler/abstractinterpretation.jl:593
abstract_call at ./compiler/abstractinterpretation.jl:592
abstract_eval_call at ./compiler/abstractinterpretation.jl:831
abstract_eval at ./compiler/abstractinterpretation.jl:901
typeinf_local at ./compiler/abstractinterpretation.jl:1159
typeinf_nocycle at ./compiler/abstractinterpretation.jl:1215
typeinf at ./compiler/typeinfer.jl:12
typeinf_ext at ./compiler/typeinfer.jl:586
typeinf_ext at ./compiler/typeinfer.jl:623
jfptr_typeinf_ext_1 at /home/ggnore/julia/usr/lib/julia/sys.so (unknown line)
jl_apply_generic at /home/ggnore/julia/src/gf.c:2250
jl_apply at /home/ggnore/julia/src/julia.h:1594 [inlined]
jl_type_infer at /home/ggnore/julia/src/gf.c:254
jl_compile_method_internal at /home/ggnore/julia/src/gf.c:1850
jl_fptr_trampoline at /home/ggnore/julia/src/gf.c:1894
jl_apply_generic at /home/ggnore/julia/src/gf.c:2250
do_call at /home/ggnore/julia/src/interpreter.c:323
eval_value at /home/ggnore/julia/src/interpreter.c:411
eval_stmt_value at /home/ggnore/julia/src/interpreter.c:362 [inlined]
eval_body at /home/ggnore/julia/src/interpreter.c:758
jl_interpret_toplevel_thunk_callback at /home/ggnore/julia/src/interpreter.c:884
Interpreter frame (ip: 0)
Core.CodeInfo(code=Array{Any, (2,)}[
  Expr(:call, :±, 1, 1),
  Expr(:return, SSAValue(1))], codelocs=Array{Int32, (2,)}[1, 1], ssavaluetypes=2, ssaflags=Array{UInt8, (0,)}[], method_for_inference_limit_heuristics=nothing, linetable=Array{Any, (1,)}[Core.LineInfoNode(method=Symbol("top-level scope"), file=Symbol("REPL[1]"), line=1, inlined_at=0)], slotnames=Array{Any, (0,)}[], slotflags=Array{UInt8, (0,)}[], slottypes=nothing, rettype=Any, parent=nothing, min_world=0, max_world=0, inferred=false, inlineable=false, propagate_inbounds=false, pure=false)jl_interpret_toplevel_thunk at /home/ggnore/julia/src/interpreter.c:893
jl_toplevel_eval_flex at /home/ggnore/julia/src/toplevel.c:797
jl_toplevel_eval_flex at /home/ggnore/julia/src/toplevel.c:746
jl_toplevel_eval_in at /home/ggnore/julia/src/toplevel.c:826
eval at ./boot.jl:327
jl_apply_generic at /home/ggnore/julia/src/gf.c:2250
eval_user_input at /home/ggnore/julia/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
macro expansion at /home/ggnore/julia/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:261
jl_apply_generic at /home/ggnore/julia/src/gf.c:2250
jl_apply at /home/ggnore/julia/src/julia.h:1594 [inlined]
start_task at /home/ggnore/julia/src/task.c:572
unknown function (ip: 0xffffffffffffffff)
1.0 ± 1.0

julia> versioninfo()
Julia Version 1.2.0-DEV.368
Commit 873c52b763 (2019-02-23 20:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG3_PRECOMPILE = 1
```

### PR DESCRIPTION
**Pull request by YingboMa**
Fixes #31164

### CODE REVIEW

**Comment by YingboMa** [comment]
```julia
julia> using Measurements

julia> @code_typed 1 ± 1
CodeInfo(
1 ─ %1 = Base.sitofp(Float64, val)::Float64
│   %2 = Base.sitofp(Float64, err)::Float64
│   %3 = invoke Measurements.measurement(%1::Float64, %2::Float64)::Measurement{Float64}
└──      return %3
) => Measurement{Float64}

julia> 1 ± 1
1.0 ± 1.0
```

**Comment by vchuravy** [comment]
Test?

**Comment by YingboMa** [comment]
I am not sure how to make a minimal working example of the error.

**Comment by Keno** [comment]
MWE:
```
julia> struct NoInit
           a::Int
           b::Any
           NoInit(a::Int) = new(a)
           NoInit(a::Int, b) = new(a, b)
       end

julia> @eval function foo(b, x)
           if b
              a = NoInit(1, x)
           else
              a = $(NoInit(1))
           end
           return a
       end
foo (generic function with 1 method)

julia> code_typed(foo, Tuple{Bool, Int}; optimize=false)
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] ⊑(::Any, ::Any) at ./compiler/typelattice.jl:151
 [2] issubstate at ./compiler/typelattice.jl:213 [inlined]
 [3] schanged at ./compiler/typelattice.jl:225 [inlined]
 [4] stupdate!(::Array{Any,1}, ::Core.Compiler.StateUpdate) at ./compiler/typelattice.jl:277
 [5] typeinf_local(::Core.Compiler.InferenceState) at ./compiler/abstractinterpretation.jl:1188
 [6] typeinf_nocycle(::Core.Compiler.InferenceState) at ./compiler/abstractinterpretation.jl:1215
 [7] typeinf(::Core.Compiler.InferenceState) at ./compiler/typeinfer.jl:12
 [8] typeinf_code(::Method, ::Any, ::Core.SimpleVector, ::Bool, ::Core.Compiler.Params) at ./compiler/typeinfer.jl:528
 [9] #code_typed#20(::Bool, ::Symbol, ::UInt64, ::Core.Compiler.Params, ::typeof(code_typed), ::Any, ::Any) at ./reflection.jl:1049
 [10] (::getfield(Base, Symbol("#kw##code_typed")))(::NamedTuple{(:optimize,),Tuple{Bool}}, ::typeof(code_typed), ::Function, ::Type) at ./none:0
 [11] top-level scope at REPL[3]:1
```

We don't usually construct `Const` from `:new` with incomplete arguments, which is why this one is a bit rare to hit, but you can force it manually by splicing such an object into the AST as a constant.

**Review by Keno — APPROVED** [review]

**Pull request merged**
