### PR TITLE
typeintersect: fix potential free `TypeVar` caused by chained inner var.

### PR DESCRIPTION
**Pull request by N5N3**
Noticed when working on 02f27c24929ab2561bcb21d3f58c1d313ae5d6e8. The substitution and re-sorting of inner vars are incomplete on master. This commit re-organized the code by:
1. Flatten the inner vars into a reversed list and handling them just like vars in norm bindings.
2. Then perform a global re-sorting on all vars.
3. After that, the inner vars get frozen and dependent bounds are refreshed.

### CODE REVIEW

**Comment by N5N3** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53675#issuecomment-1986831224) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d47c237_vs_bb35dc9/report.html) is available.

**Comment by N5N3** [comment]
@nanosoldier `runtests(["LaurentPolynomials", "PuiseuxPolynomials", "CycPols", "GenericDecMats", "SphericalFunctions", "DispersiveShallowWater", "DiffEqFinancial", "NBodySimulator", "PredefinedDynamicalSystems", "ChaosTools", "HetaSimulator", "PETLION", "NeuronBuilder", "SurfaceReactions", "AstrodynamicalModels", "SMLMFrameConnection", "QuantumCliffordPlots", "AvailablePotentialEnergyFramework"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53675#issuecomment-1987179424) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d47c237_vs_bb35dc9/report.html) is available.

**Review by vtjnash — APPROVED** [review]
SGTM. I didn't follow all of the code rearrangements, but the concept sounds good and it passes tests

**Comment by KristofferC** [comment]
Note, I backported this to 1.11 as well since without it there were some merge conflicts.

**Pull request merged**
