### PR TITLE
add subtypes() for UnionAll

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tkelman** [comment]
could you add a test?

**Comment by JeffBezanson** [comment]
What is `subtypes` for? Do we really need it?

**Comment by gaika** [comment]
Sorry, it doesn't work at all :(

**Comment by mauro3** [comment]
@JeffBezanson: `subtypes(AbstractArray)` seems like a useful query to me.  Or is there now another preferred way to do this?

**Comment by iamed2** [comment]
@JeffBezanson: I use `subtypes` to explore the type tree interactively.

**Comment by tbreloff** [comment]
@JeffBezanson I use `subtypes` to be able to plot type hierarchies: https://github.com/JuliaPlots/PlotRecipes.jl#julia-type-trees

**Pull request closed without merging**
