### PR TITLE
More LU tests and move stuff out of inner loops

### PR DESCRIPTION
**Pull request by kshyatt**
We don't need to run some of these tests for `eltyb`. Also added tests for converting the numerical type of the LU factorization.

### CODE REVIEW

**Comment by kshyatt** [comment]
review pls <3

**Comment by fredrikekre** [comment]
I think it would be nice not to split up the `Tridiagonal LU` testsets, perhaps factor it out and put in its own `eltype` loop?

**Comment by andreasnoack** [comment]
@rfourquet How is it possible that a test in a `guardsrand` block can fail when it is not changed?

**Comment by rfourquet** [comment]
> How is it possible that a test in a guardsrand block can fail when it is not changed?

It shouldn't so I will investigate, will try to find time by tomorrow.

**Comment by KristofferC** [comment]
Just move it out into its completely own for loop? :trollface:

**Comment by rfourquet** [comment]
@andreasnoack So the failing test is apparently because `normestinv` is probabilistic (and hence can sometimes produce different outputs for a given input) and was not included in the `guardsrand` block (fix at #24326).

**Comment by andreasnoack** [comment]
Good news. Thanks for tracking this down.

**Comment by kshyatt** [comment]
What do we want to do with this? Did the `normestinv` thing get fixed?

**Comment by andreasnoack** [comment]
It should be fixed. I've restarted the tests.

**Pull request merged**
