### PR TITLE
Check for Vararg{T,N} in typemap: sig_match_by_type_simple

### LINKED ISSUE #16623: Bug with Vararg{T,N}
**Doctest in [Parametrically-constrained Varargs methods](http://docs.julialang.org/en/latest/manual/methods/#parametrically-constrained-varargs-methods)  fails:**

My latest Julia `repl` displays:
```
julia> bar(a,b,x::Vararg{Any,2}) = (a,b,x)
bar (generic function with 1 method)

julia> bar(1,2,3)
(1,2,(3,))

julia> bar(1,2,3,4)
(1,2,(3,4))

julia> bar(1,2,3,4,5)
(1,2,(3,4,5))
```
while the expected result is:
```
julia> bar(a,b,x::Vararg{Any,2}) = (a,b,x)

julia> bar(1,2,3)
ERROR: MethodError: `bar` has no matching method bar(::Int, ::Int, ::Int)

julia> bar(1,2,3,4)
(1,2,(3,4))

julia> bar(1,2,3,4,5)
ERROR: MethodError: `bar` has no method matching bar(::Int, ::Int, ::Int, ::Int, ::Int)
```

**Another doctest in [Generator Expressions](http://docs.julialang.org/en/latest/manual/arrays/#generator-expressions) fails too.**
```
julia> map(tuple, (1/(i+j) for i=1:2, j=1:2), [1:4;])
ERROR: DimensionMismatch("dimensions must match")
 in promote_shape(::Tuple{Int64,Int64}, ::Tuple{Int64}) at ./operators.jl:304
 in _similar_for at ./array.jl:210 [inlined]
 in _collect(::UnitRange{Int64}, ::Base.Generator{Base.Zip2{Base.Generator{Base.IteratorND{Base.Prod2{UnitRange{Int64},UnitRange{Int64}},2},##1#2},Array{Int64,1}},Base.##1#2{Core.#tuple}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:252
 in map(::Function, ::Base.Generator{Base.IteratorND{Base.Prod2{UnitRange{Int64},UnitRange{Int64}},2},##1#2}, ::Array{Int64,1}) at ./abstractarray.jl:1146
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
while the expected is:
```
julia> map(tuple, (1/(i+j) for i=1:2, j=1:2), [1:4;])
4-element Array{Any,1}:
(0.5,1)
(0.333333,2)
(0.333333,3)
(0.25,4)
```

**Doc in [Method Ambiguities](http://docs.julialang.org/en/latest/manual/methods/#method-ambiguities) maybe need to be revised:**
```
julia> g(x::Float64, y) = 2x + y;

julia> g(x, y::Float64) = x + 2y;

julia> g(2.0, 3)
7.0

julia> g(2, 3.0)
8.0

julia> g(2.0, 3.0)
ERROR: MethodError: g(::Float64, ::Float64) is ambiguous. Candidates:
  svec(Tuple{#g,Float64,Float64},svec(),g(x, y::Float64) at REPL[10]:1)
  svec(Tuple{#g,Float64,Float64},svec(),g(x::Float64, y) at REPL[9]:1)
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
while the expected is:
```
julia> g(x::Float64, y) = 2x + y;

julia> g(x, y::Float64) = x + 2y;
WARNING: New definition
    g(Any, Float64) at none:1
is ambiguous with:
    g(Float64, Any) at none:1.
To fix, define
    g(Float64, Float64)
before the new definition.

julia> g(2.0, 3)
7.0

julia> g(2, 3.0)
8.0

julia> g(2.0, 3.0)
7.0
```

My Julia version is:
```
julia> versioninfo()
Julia Version 0.5.0-dev+4370
Commit 758aebc* (2016-05-27 21:34 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

### PR DESCRIPTION
**Pull request by timholy**
Fixes #16623

### CODE REVIEW

**Comment by timholy** [comment]
I would classify this as a "narrow" fix, but it works in the cases I tested. @vtjnash, since you know typemap.c well, it might make some sense to see if you can think of cases that this simple fix wouldn't catch.

**Comment by vtjnash** [comment]
also likely need the same fix @ https://github.com/JuliaLang/julia/pull/16627/files#diff-213db5d6a6c93b12384ade73dbb25e1aR155, although I don't know of any case where that can be triggered (currently). Might also want to check that very long argument list method matches ending in a limited vararg don't get incorrectly truncated as they get inserted into the cache to look like an unlimited vararg.

**Comment by timholy** [comment]
Did you mean to link somewhere else? That link is for the diff in this PR.

**Comment by vtjnash** [comment]
oh, i forgot that github won't let me link to a line number for a PR. the corrected link to sig_match_simple is https://github.com/JuliaLang/julia/blob/fab4a624b2f67b4f3e5a366743e956852775eeda/src/typemap.c#L155

**Pull request merged**
