### PR TITLE
release-1.10: set VERSION to 1.10.0-alpha1

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by IanButterworth** [comment]
Pkg needs backports and a bump before this

**Comment by KristofferC** [comment]
Might as well run this:

@nanosoldier `runtests(ALL, vs = ":release-1.9", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.9")`

**Comment by DilumAluthge** [comment]
I have created the new `julia-release-1.10` Buildkite pipeline: https://buildkite.com/julialang/julia-release-1-dot-10

**Comment by DilumAluthge** [comment]
I'm not sure why Buildkite isn't running on this PR. Let me try making a new PR.

**Comment by DilumAluthge** [comment]
I'm going to close this in favor of #50420.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50394#issuecomment-1621410506) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/d44cbb2_vs_e4ee485/report.md).

**Comment by KristofferC** [comment]
`["problem", "spellcheck", "spellcheck"]	4.24 (5%) ❌	3.20 (1%) ❌`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/50394#issuecomment-1621409417) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c9a32f4_vs_e4ee485/report.html).

**Pull request closed without merging**
