### PR TITLE
[Codegen] Skip wb emission when they are no children objects

### PR DESCRIPTION
**Pull request by vchuravy**
Originally found by @pchintalapudi

### CODE REVIEW

**Review by Keno — APPROVED** [review]

**Comment by vtjnash** [comment]
Wow, that seemed to cause a surprising amount of CI chaos

**Comment by vtjnash** [comment]
Bisected this to https://reviews.llvm.org/D106613

**Comment by vchuravy** [comment]
Adding this to the milestone so that we pick up https://reviews.llvm.org/D106613 at least, even if we don't backport this commit.

**Comment by JeffBezanson** [comment]
The LLVM patch is probably not release-blocking, since AFAICT we don't actually hit the bug in 1.7. Once it's settled will be good to backport though.

**Comment by vtjnash** [comment]
FWIW, it seems like we are potentially waiting for the next LLVM version, which disables the offending logic (via a better cost model), since I don't know how to fix it.

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/41439#issuecomment-939301106) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/24dd547_vs_a0504ab/report.md).

**Pull request merged**
