### PR TITLE
validate ccall nargs

### LINKED ISSUE #22334: ccall lowering incorrect for syntax errors
I am compiling a simple script into a .o file. This is my hello.jl

````
module mystuff

using Distributions
f() = rand(Normal())

Base.@ccallable Void function julia_main()
   println("hello, world")
   @show f()
end

end

using mystuff
mystuff.julia_main()
````

I am invoking the compiler as follows:
````
/Users/viral/julia/usr/bin/julia -Cnative -J/Users/viral/julia/usr/lib/julia/sys.dylib --compile=yes --depwarn=yes -J/Users/viral/julia/usr/lib/julia/sys.dylib --compile=all --startup-file=no --output-o hello.o hello.jl
````

And get this error:

````
hello, world
f() = 0.6791074260357777
found 35144 uncompiled methods for compile-all
fatal: error thrown and no exception handler available.
TypeError(func=:ccall, context="", expected=Expr, got=SlotNumber(id=7))
rec_backtrace at /Users/viral/julia/src/stackwalk.c:86
record_backtrace at /Users/viral/julia/src/task.c:245 [inlined]
jl_throw at /Users/viral/julia/src/task.c:564
jl_type_error_rt at /Users/viral/julia/src/rtutils.c:118
jl_type_error at /Users/viral/julia/src/rtutils.c:124
emit_ccall at /Users/viral/julia/src/./ccall.cpp:1508
emit_function at /Users/viral/julia/src/codegen.cpp:6177
jl_compile_linfo at /Users/viral/julia/src/codegen.cpp:1255
_compile_all_deq at /Users/viral/julia/src/precompile.c:264 [inlined]
jl_compile_all_defs at /Users/viral/julia/src/precompile.c:309 [inlined]
jl_precompile at /Users/viral/julia/src/precompile.c:352
jl_write_compiler_output at /Users/viral/julia/src/precompile.c:31
jl_atexit_hook at /Users/viral/julia/src/init.c:238
main at /Users/viral/julia/usr/bin/julia (unknown line)
````
I see this on master as well as release-0.6.

### PR DESCRIPTION
**Pull request by vtjnash**
Changes the deprecation warning ("ccall: wrong number of arguments to C function" that was added in v0.6, since making this an error immediately broke too many packages) into a syntax error, rather than emitting malformed syntax.

closes #22334

### CODE REVIEW

**Comment by ViralBShah** [comment]
Hopefully can be backported too.

**Comment by vtjnash** [comment]
This requires removing a deprecation to implement (although if necessary, we could make the deprecation more accurate, there's a small number of cases – like the one in Rmath – that it couldn't currently detect).

**Comment by thofma** [comment]
Will this close https://github.com/JuliaLang/julia/issues/20129?

**Comment by nalimilan** [comment]
That's too late to make it an error in 0.6 IMHO, the RCs shouldn't introduce breaking changes. Same for 0.6.1, which is supposed to fix bugs without introducing any new failures.

**Pull request merged**
