### PR TITLE
simplify mapreduce_impl

### LINKED ISSUE #16185: performance regression in sum(a)
It seems like `sum` has gotten a lot slower.  Back when I first implemented pairwise summation in #4039, it was essentially as fast (within a few %) as naive summation.   In #5205, @lindahua unrolled the loop to make it significantly faster than a naive summation loop.  Now, it seems to be significantly *slower* than naive code:
```jl
function mysum(a)
    s = a[1]
    for i = 2:length(a)
        @inbounds s += a[i]
    end
    return s
end

a = rand(10^7);
@elapsed(sum(a)) / @elapsed(mysum(a))
```
gives a ratio of about 1.6 on my machine with the latest Julia 0.5, whereas the ratio is 0.8 with Julia 0.4.

### PR DESCRIPTION
**Pull request by vtjnash**
this is largely now possible since Functors are not needed for performance
fixes #16185

### CODE REVIEW

**Comment by KristofferC** [comment]
I don't think we should close #16185 until the reduced example I posted there is fixed. Alternatively a new issue could be made for that example.

**Comment by JeffBezanson** [comment]
The reduced example in that issue might not get fixed. The extra code allows dynamic dispatch to a version of `g` specialized for `f`. The method in the example is probably not performance-critical, since all it does is call another function. This is part of the cost of faster higher-order functions.

**Comment by StefanKarpinski** [comment]
From triage call:

- addresses the performance issue in #16185 
- by changing the association order of mapreduce
- does not address the dynamic dispatch slowdown that causes #16185

**Comment by StefanKarpinski** [comment]
TODO: there should be a note in NEWS about the changed reduction order.

**Comment by JeffBezanson** [comment]
We should definitely keep both pairwise summation and the 0.4 level of performance. If necessary we should manually specialize `sum`, or use a `reduce_impl` that has the mapping function removed.

**Comment by tkelman** [comment]
Apparently DataArrays was using `sum_pairwise_blocksize`

**Comment by vtjnash** [comment]
it can define `sum_pairwise_blocksize(T) = pairwise_blocksize(T, +)` for compatibility

**Comment by nalimilan** [comment]
That's what I did in https://github.com/JuliaStats/DataArrays.jl/pull/192. If that was the only use of it outside of Base, I guess that's OK.

**Comment by tkelman** [comment]
NullableArrays was also using it.

**Pull request merged**
