### PR TITLE
Rename cryptic make variable from `,` to `COMMA`

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by staticfloat** [comment]
Dare I ask why we have a variable set to comma in the first place?

**Comment by IainNZ** [comment]
I don't pretend understand the make system, but I must say that it amazes me firstly that `,` is a valid variable name, and secondly that its value was set to `,` and its used once, and its inside a string.

**Comment by staticfloat** [comment]
Asking the senpai: https://github.com/JuliaLang/julia/commit/8e9e68c21d8d8d2aae24b0d8eb7ed31984445ce7

**Comment by jiahao** [comment]
commachameleon_fullpic_artwork

[ref](http://www.snorgtees.com/comma-chameleon)

**Comment by staticfloat** [comment]
Since Jameson notes that there's an actual syntactic reason for this, I vote we just remove the comma.  It's not worth having to go through this discussion again in six months when we've all forgotten why this is here.

**Comment by eschnett** [comment]
It's customary to have make variables called `COMMA` or `EMPTY` or `SPACE` that expand to the respective entity.

Also, if there's a comment in the makefile then there's no confusion. For my purposes, using a non-unusual variable name is good enough. Others may prefer a comment. We could just copy-and-paste the explanation from github into the makefile.

**Comment by ivarne** [comment]
I'd vote for including a comment in the makefile. `$(,)` is a cool variable name, but it seems more distracting than useful.

**Pull request merged**
