### PR TITLE
Valgrind documentation/testsuite improvements

### PR DESCRIPTION
**Pull request by garrison**
This pull request (meant to supersede #10015) greatly improves the documentation for running `julia` under `valgrind`, and also disables a few tests that will fail for obvious reasons under `valgrind`.

### CODE REVIEW

**Comment by garrison** [comment]
I just disabled another `spawn.jl` test that was failing under Valgrind.  I am considering just disabling them all under Valgrind.

**Comment by garrison** [comment]
At least one `examples.jl` test fails under Valgrind too, still (probably due to calling a subprocess that's also running under valgrind).  I believe all other tests pass, but I am waiting to see.

**Comment by garrison** [comment]
OK yes, it looks like `examples.jl` is the only test file that fails under Valgrind still (at least for me).  I'm not sure how best to fix this yet.  I'd be fine with this pull request being merged now, or we can wait until this is fixed (though I may not have time to work on it in the next few days).

**Comment by amitmurthy** [comment]
What is the error?

**Comment by garrison** [comment]
exception on 1: ERROR: LoadError: UnixDomainCM failed test, cmd : `/home/garrison/julia/usr/bin/julia-debug /home/garrison/julia/usr/bin/../share/doc/julia/examples/clustermanager/simple/test_simple.jl`
     in error at error.jl:19
     in runtests at /home/garrison/julia/test/testdefs.jl:78
     in anonymous at multi.jl:656
     in run_work_thunk at multi.jl:617
     in remotecall_fetch at multi.jl:690
     in remotecall_fetch at multi.jl:705
     in anonymous at task.jl:1406
    while loading examples.jl, in expression starting on line 45

**Comment by garrison** [comment]
Like some of the `spawn` tests I disabled, `examples.jl` works under Nulgrind (i.e. `valgrind --tool=none`) but fails under Valgrind with the error above.

**Comment by amitmurthy** [comment]
Yeah, the UnixDomainCM example test does launch a new julia session - maybe the underlying issue is the same as the spawn tests. 

Does `/home/garrison/julia/usr/bin/../share/doc/julia/examples/clustermanager/simple/test_simple.jl`` exist on your system? 

https://github.com/JuliaLang/julia/blob/master/Makefile#L40 copies the required files for the test to work.

**Comment by garrison** [comment]
> Does 
> |/home/garrison/julia/usr/bin/../share/doc/julia/examples/clustermanager/simple/test_simple.jl|` 
> exist on your system?
Yes, it does.

**Comment by garrison** [comment]
I disabled (when running under valgrind) the one remaining `examples.jl` test that was failing, though I do not quite understand why it fails.  (The other consistently failing tests, aside from the rounding tests, are ones that expect specific output from STDERR but instead get a valgrind banner, so that may be the issue here as well.)

I still occasionally get failure of some other test when I run the full suite under valgrind.  The most recent one to fail was:

    exception on 5: ERROR: LoadError: LoadError: test failed: cholfact((A1 + A1') - I) did not throw Base.LinAlg.PosDefException
     in expression: cholfact((A1 + A1') - I)
     in error at error.jl:19
     in default_handler at test.jl:27
     in do_test_throws at test.jl:72
     in anonymous at no file:338
     in include_string at loading.jl:97
     in include_from_node1 at ./loading.jl:131
     in runtests at /home/garrison/julia/test/testdefs.jl:78
     in anonymous at multi.jl:866
     in run_work_thunk at multi.jl:617
     in anonymous at task.jl:866
    while loading /home/garrison/julia/test/sparsedir/cholmod.jl, in expression starting on line 291
    while loading sparse.jl, in expression starting on line 3

but I've only seen this failure once, and it was while running the full suite.  Since it's intermittent, perhaps fixing the existing claimed memory errors in the tests (#10217 in particular) will fix this.

I did just manage to get the full test suite to pass using the current state of this pull request, which has only a few tests disabled under valgrind.

**Comment by garrison** [comment]
OK, I rebased everything due to a conflict on `master`.

**Comment by timholy** [comment]
This looks really great to me. @tkelman, if the AppVeyor failure is unrelated, shall we merge?

**Comment by tkelman** [comment]
yep

**Pull request merged**
