### PR TITLE
Add tests for #10742 on triangular matrice

### PR DESCRIPTION
**Pull request by garrison**
Adding tests for the fix in 2a814112.  Some related tests were already included in bdbd6ca.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks

**Comment by tkelman** [comment]
I don't think a commit that adds tests is a very appropriate choice for `[av skip]`.

**Comment by garrison** [comment]
I was trying to balance the long av queue against a commit that added just two lines and has nothing platform-specific.  I'll keep your comment in mind next time though and leave out the `[av skip]`.

**Comment by tkelman** [comment]
I think the queue would've been fine at the time you submitted this, though it is really long right now because Jeff went on a merging spree today.

Anything that calls into a linear algebra library can have surprising platform dependencies come up in unexpected places, so better to err on the safe side in my mind.

**Pull request merged**
