### PR TITLE
another soft scope PkgEval run

### PR DESCRIPTION
**Pull request by JeffBezanson**
This time excluding `let` (and testsets).

@nanosoldier `runtests(ALL, vs = ":master")`

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by KristofferC** [comment]
Maybe it doesn't like it when the comment is in the body of the first post?

**Comment by DilumAluthge** [comment]
> Maybe it doesn't like it when the comment is in the body of the first post?

From the point-of-view of the GitHub API, the first post (a.k.a. the body of the pull request) does not count as a comment. So if you use the GitHub API to retrieve all of the comments in a PR, the first post will not be included in the list, as you can see in this example.
```julia
julia> import GitHub

julia> repo = GitHub.repo("JuliaLang/julia")

julia> pr = GitHub.pull_request(repo, 34469)

julia> comments, pagedata = GitHub.comments(repo, pr)

julia> length(comments)
2

julia> comments[1]
GitHub.Comment (all fields are Union{Nothing, T}):
  body: "@nanosoldier `runtests(ALL, vs = \":master\")`"
  id: 576904486
  created_at: 2020-01-21T22:02:23
  updated_at: 2020-01-21T22:02:23
  url: HTTP.URI("https://api.github.com/repos/JuliaLang/julia/issues/comments/576904486")
  html_url: HTTP.URI("https://github.com/JuliaLang/julia/pull/34469#issuecomment-576904486")
  issue_url: HTTP.URI("https://api.github.com/repos/JuliaLang/julia/issues/34469")
  user: Owner("KristofferC")

julia> comments[2]
GitHub.Comment (all fields are Union{Nothing, T}):
  body: "Maybe it doesn't like it when the comment is in the body of the first post?"
  id: 576904649
  created_at: 2020-01-21T22:02:43
  updated_at: 2020-01-21T22:02:43
  url: HTTP.URI("https://api.github.com/repos/JuliaLang/julia/issues/comments/576904649")
  html_url: HTTP.URI("https://github.com/JuliaLang/julia/pull/34469#issuecomment-576904649")
  issue_url: HTTP.URI("https://api.github.com/repos/JuliaLang/julia/issues/34469")
  user: Owner("KristofferC")
```

Furthermore, if you have registered a GitHub app to receive webhook events, here is what will happen:
- When the original pull request was created by Jeff, GitHub sent the [`PullRequestEvent`](https://developer.github.com/v3/activity/events/types/#pullrequestevent) webhook. The contents of this web hook included the body of the pull request, a.k.a. the first post.
- When Kristoffer posted a comment with the Nanosoldier command, GitHub sent the [`IssueCommentEvent`](https://developer.github.com/v3/activity/events/types/#issuecommentevent) webhook. The contents of this web hook included the body of the comment, i.e. the Nanosoldier command text.

So if Nanosoldier is expecting to receive its commands in `PullRequestEvent` webhooks, then it won't notice when the command is present in the first post of a pull request, as that is sent in a different type of webhook.

Anyway, this is all off-topic, so it should probably be moved to a thread in the Nanosoldier repository.

**Comment by DilumAluthge** [comment]
If you wanted to use the GitHub API to get the content of the first post of a pull request, you could do so like this:
```julia
julia> import GitHub

julia> repo = GitHub.repo("JuliaLang/julia")

julia> pr = GitHub.pull_request(repo, 34469)

julia> pr.body
"This time excluding `let` (and testsets).\r\n\r\n@nanosoldier `runtests(ALL, vs = \":master\")`"
```

And if you wanted to get it through a webhook event, you would need to tell GitHub to send you  [`PullRequestEvent`](https://developer.github.com/v3/activity/events/types/#pullrequestevent) webhooks.

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34469#issuecomment-576904486) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/533c0ea3be572c0905e0b2072a3f2aaa7d7d7676/pkgeval/by_hash/ce85ee9_vs_c9940ed/report.md). cc @maleadt

**Comment by JeffBezanson** [comment]
OK, now affects 69 packages. Much better than 150 anyway.

**Comment by StefanKarpinski** [comment]
This uncovered a situation that the current PR doesn't quite handle right:
```jl
julia> include_string(Main, """
       x = 1
       @testset begin
           x = "hi"
       end
       x
       """)
Test Summary: |
test set      | No tests
1

julia> include_string(Main, """
       x = 1
       @testset for i = 1:1
           x = "hi"
       end
       x
       """)
┌ Warning: Assignment to `x` in top-level block is ambiguous because an outer global binding by the same name already exists. Use `global x` to assign to the outer global `x` variable or use `local x` to force a new local by the same name.
└ @ string:3
Test Summary: |
i = 1         | No tests
1
```
The for loop version of `@testset` also needs to insert a let block. Will push a fix to jb/softscope.

**Pull request closed without merging**
