### PR TITLE
Support multidim booleans in checkbounds_indices

### LINKED ISSUE #38192: Failure in mixed indexing with multidimensional logicals
Inspired by https://stackoverflow.com/questions/64549136/i-want-to-do-logical-masking-on-an-image-in-julia

```julia
julia> img = cat([1 2; 3 4], [1 5; 6 7]; dims=3)
2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  2
 3  4

[:, :, 2] =
 1  5
 6  7

julia> mask = img[:,:,1] .== img[:,:,2]
2×2 BitMatrix:
 1  0
 0  0

julia> img[mask,2] .= 0
ERROR: BoundsError: attempt to access 2×2×2 Array{Int64, 3} at index [Bool[1 0; 0 0], 2]
Stacktrace:
 [1] throw_boundserror(A::Array{Int64, 3}, I::Tuple{Base.LogicalIndex{CartesianIndex{2}, BitMatrix}, Int64})
   @ Base ./abstractarray.jl:601
 [2] checkbounds
   @ ./abstractarray.jl:566 [inlined]
 [3] view
   @ ./subarray.jl:158 [inlined]
 [4] maybeview
   @ ./views.jl:133 [inlined]
 [5] dotview(::Array{Int64, 3}, ::BitMatrix, ::Int64)
   @ Base.Broadcast ./broadcast.jl:1160
 [6] top-level scope
   @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by timholy**
Fixes #38192

### CODE REVIEW

**Comment by mbauman** [comment]
Hunh, this actually works?  I guess I need to dig a bit deeper here, but I shamefully have long had a pirating set of methods that did this (back in Julia 0.6 days, I think) that I never pushed:

```
@eval Base begin
    # Add support for partial logical indexing
    @inline checkindex(::Type{Bool}, inds::Tuple, I::LogicalIndex) = inds == indices(I.mask)
    @inline checkbounds_indices{N}(::Type{Bool},IA::Tuple{},I::Tuple{LogicalIndex{Int,<:AbstractArray{Bool,N}}}) =
        checkindex(Bool, IA, I[1])
    @inline checkbounds_indices{N}(::Type{Bool},IA::Tuple{Any},I::Tuple{LogicalIndex{Int,<:AbstractArray{Bool,N}}}) =
        checkindex(Bool, IA[1], I[1])
    @inline function checkbounds_indices{N}(::Type{Bool}, IA::Tuple, I::Tuple{LogicalIndex{Int,<:AbstractArray{Bool,N}}})
        IA1, IArest = IteratorsMD.split(IA, Val{N})
        checkindex(Bool, IA1, I[1])
    end
end
```

I'll need to look a bit closer at the differences here.

**Comment by timholy** [comment]
Any more thoughts? If you're concerned it's a bit dangerous for 1.6, we can wait for 1.7.

**Comment by mbauman** [comment]
Ah, I see, you're just transiently wrapping the logical array in a `LogicalIndex` — which is an `AbstractArray{<:CartesianIndex}`, which has support for this operation.  It then gets wrapped in a `LogicalIndex` again later down the road.

The one slight implementation detail is that `LogicalIndex` computes its `sum` on construction, so this won't be quite as efficient as one would hope unless there are some serious compiler CSE heroics.

**Review by mbauman — APPROVED** [review]

**Comment by timholy** [comment]
I think we can leave the efficiency issues for a separate day.

**Comment by bkamins** [comment]
@timholy - how does this PR affect this behavior (on Julia 1.7) and what changes to the documentation you think should be made to take into account changes from this PR? 

Below I give an example of behavior I do not understand:

I have a question is this behavior intended:
```
julia> X = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> sel = [[true, false];;]
2×1 Matrix{Bool}:
 1
 0

julia> X[sel, :]
1×1 Matrix{Int64}:
 1
```

Looking at the source code of `getindex` I know why technically it works, my question is why it is allowed especially that the behavior is not following the https://docs.julialang.org/en/v1/manual/arrays/#Logical-indexing contract as:
```
julia> X[sel]
ERROR: BoundsError: attempt to access 2×2 Matrix{Int64} at index [2×1 Matrix{Bool}]

julia> X[[CartesianIndex(1,1)]]
1-element Vector{Int64}:
 1
```
although the manual says it should be equivalent as it states:
> Similarly, indexing by a N-dimensional boolean array is effectively the same as indexing by the vector of CartesianIndex{N}s where its values are true.

On the other hand if we stick to the next sentence in the manual:
> A logical index must be a vector of the same length as the dimension it indexes into, or it must be the only index provided and match the size and dimensionality of the array it indexes into.

`X[sel, :]` should error.

**Pull request merged**
