### PR TITLE
doc: unique and Set uses both hash and isequal

### PR DESCRIPTION
**Pull request by johnnychen94**
`unique` internally uses `push!(seen::Set, y)`, which uses  `hash` alongside with `isequal`.

```julia
# https://github.com/JuliaLang/julia/blob/98e60ffb11ee431e462b092b48a31a1204bd263d/base/set.jl#L137-L144
function unique(itr)
    ...
        out = Vector{T}()
        seen = Set{T}()
        for x in itr
            if !in(x, seen)
                push!(seen, x) # Set
                push!(out, x)
            end
        end
    ...
end

# https://github.com/JuliaLang/julia/blob/98e60ffb11ee431e462b092b48a31a1204bd263d/base/set.jl#L67
push!(s::Set, x) = (s.dict[x] = nothing; s)

# https://github.com/JuliaLang/julia/blob/98e60ffb11ee431e462b092b48a31a1204bd263d/base/dict.jl#L496-L499
function getindex(h::Dict{K,V}, key) where V where K
    index = ht_keyindex(h, key)
    @inbounds return (index < 0) ? throw(KeyError(key)) : h.vals[index]::V
end

# https://github.com/JuliaLang/julia/blob/98e60ffb11ee431e462b092b48a31a1204bd263d/base/dict.jl#L169
hashindex(key, sz) = (((hash(key)::UInt % Int) & (sz-1)) + 1)::Int
```

### CODE REVIEW

**Comment by simeonschaub** [comment]
The use of `hash` vs `isequal` should only be an implementation detail. Users are responsible for always ensuring the two are consistent, so I think this change gives the wrong impression about the relationship between the two.

**Comment by johnnychen94** [comment]
> Users are responsible for always ensuring the two are consistent, so I think this change gives the wrong impression about the contract here.

I do find the contract from `isequal` docstring:

> `isequal` is the comparison function used by hash tables (`Dict`). `isequal(x,y)` must imply that `hash(x) == hash(y)`.

Should I close this? I find the examples more illustrative to understand the meaning behind the contract. Maybe we should extend the `isequal` docstring instead?

**Comment by simeonschaub** [comment]
Yes, I think we could probably use more documentation for this, but I find it a bit confusing that you don't really talk about `isequal`, only `==`.

Primarily I'm not sure this is really the right place for this, since a lot of other functions like `union` or `setdiff` make exactly the same assumptions. This is not something users of `unique` should need to care about, instead someone defining a type needs to make sure to abide to the proper contract, not only for `unique` to behave correctly, but also any one of a plethora of functions,

**Comment by johnnychen94** [comment]
Okay, I'll close this one. Will open a new one for `isequal` when I find some time.

**Pull request closed without merging**
