### PR TITLE
Fix #9947

### LINKED ISSUE #9947: compiler bug: "cannot convert type" error on first function call, result on second
While debugging #9936, I came up with the following minimal code example that exhibits some strange behavior:

```julia
julia> function badfn()
           if 1 == 0
               1
           else
               min(uint128(2),1)
           end
       end
badfn (generic function with 1 method)

julia> badfn()
ERROR: error compiling badfn: cannot convert type to a julia type

julia> badfn()
0x00000000000000000000000000000001

julia> @code_llvm badfn()
ERROR: error compiling badfn: cannot convert type to a julia type
 in code_llvm at reflection.jl:158
 in code_llvm at reflection.jl:159

julia> versioninfo()
Julia Version 0.4.0-dev+2945
Commit a503afb* (2015-01-27 19:55 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

This happens on *both* v0.3 and v0.4.

### PR DESCRIPTION
**Pull request by kmsquire**

### CODE REVIEW

**Comment by kmsquire** [comment]
Ref: https://github.com/JuliaLang/julia/issues/9947#issuecomment-71968132

**Comment by kmsquire** [comment]
@juliabackports

**Comment by tkelman** [comment]
If I attempt to backport this to release-0.3, I do still get
```
exception on 2: ERROR: test error during f9947() == Uint128(1)
type cannot be constructed
 in f9947 at core.jl:1900
```

**Comment by tkelman** [comment]
Sorry, I think it's just the call constructor syntax for `Uint(2)` that I have to tweak

**Comment by tkelman** [comment]
that worked, backported in 6186035bcd007127e24e94adaab2d13412acdd09 (please double-check that it's testing the right behavior)

**Pull request merged**
