### PR TITLE
Make issparse handle nested wrappers

### PR DESCRIPTION
**Pull request by oxinabox**
Follow up to: https://github.com/JuliaLang/julia/pull/34266

Handles all the existing cases, plus:
 - arbitary nesting of wrappers
 - `SubArrays`
 - `Diagonal`

It all constant folds out:
```
julia> z = adjoint(transpose((1 + im) .*sprandn(5,5, 0.5)));

julia> @code_llvm issparse(z)

;  @ REPL[18]:2 within `issparse'
define i8 @julia_issparse_17287(%jl_value_t addrspace(10)* nonnull align 8 dereferenceable(8)) {
top:
;  @ REPL[18]:4 within `issparse'
  ret i8 1
}

julia> q = adjoint(transpose((1 + im) .*randn(5,5)));

julia> @code_llvm issparse(q)

;  @ REPL[18]:2 within `issparse'
define i8 @julia_issparse_17303(%jl_value_t addrspace(10)* nonnull align 8 dereferenceable(8)) {
top:
;  @ REPL[18]:4 within `issparse'
  ret i8 0
}
```

### CODE REVIEW

**Comment by fredrikekre** [comment]
Perhaps OT, but can we just delete `issparse` instead? It does not seem very useful, what do you do with it? Outside of tests it is only used in three places: https://github.com/JuliaLang/julia/blob/3608c84e6093594fe86923339fc315231492484c/stdlib/SparseArrays/src/sparsevector.jl#L1040 https://github.com/JuliaLang/julia/blob/3608c84e6093594fe86923339fc315231492484c/stdlib/SparseArrays/src/sparsevector.jl#L1045 and https://github.com/JuliaLang/julia/blob/3608c84e6093594fe86923339fc315231492484c/stdlib/SparseArrays/src/sparsevector.jl#L1049

(See also https://github.com/JuliaLang/julia/issues/24645)

**Comment by oxinabox** [comment]
I agree with the sentiment.
a trait without a set of rules about what it promises is not good for much.

But since it is a breaking change, we can't delete it.

So we might as well make it work well.

That may or may not include making it work for these cases.

Perhaps before doing this we should decide what it means.

It probably should mean something about the cost of various operations.

**Comment by oxinabox** [comment]
This errors because:
 -  `Diagonal(rand(4,4))` works fine and just cuts out the diagonal, ignoring nondiagonal elements.
 - `Diagonal(LowerTriangular(rand(4,4)))` errors because the matrix has zeros on the non-diagonal

Which seems really silly and inconsistent to me.

**Comment by ViralBShah** [comment]
I thought we can't delete APIs that are in 1.0.

**Comment by oxinabox** [comment]
Closing in favour of https://github.com/JuliaLang/julia/pull/37644
Since that one doesn't need to be rebased.

**Comment by oxinabox** [comment]
Revisiting this. Since I apparently decided to open a second PR having forgotten i made this one.
#37644 

> What does it mean to be issparse?
> I haven't seen a defination of an interface that must be furfilled.
> 
> Possibly all people want this for is to know if they have some algorthm that really won't run great on a sparse array, then they could issue a warning or run collect to make it dense.

**Comment by dkarrasch** [comment]
The tests pass locally for me, so this should be good to go after a rebase.

**Comment by oxinabox** [comment]
Done

**Pull request merged**
