### PR TITLE
Prevent circular precompile of Pkg

### PR DESCRIPTION
**Pull request by IanButterworth**
Alternative to #51675

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
It is also a serious bug if this gets loaded during any precompilation, not just for Pkg, as we will be unable to load the file afterwards and the compilation pipeline will crash

**Review by vtjnash — COMMENTED** [review]
(That was supposed to be a general comment, not approval)

**Comment by vtjnash** [comment]
Looking closer, no, because it incorrectly passes a parameter to that call

**Review by vtjnash — CHANGES_REQUESTED** [review]
This code is still wrong for any package which Pkg depends upon, since this code adds an edge from all packages to Pkg

**Comment by KristofferC** [comment]
Is that an issue if this is only run in a non precompiling process whereby Pkg is only loaded into Main?

**Comment by vtjnash** [comment]
Where and how a package is loading has no relevance whatsoever to edges. All that matters is the existence of calls to `require`, as that is what an edge literally means to the graph.

**Comment by KristofferC** [comment]
So we could start a new process where Pkg is first loaded, and after that is done, the `Pkg.precompile` call is made? That would avoid the `require` call at the same time as some other package is loaded.

**Comment by vtjnash** [comment]
The proper sequence would be to load Pkg first, before doing any other `require` work, but that is just absurd. This just cannot depend on Pkg, as that introduces many circularity, and thus reliability, problems.

**Pull request closed without merging**
