### PR TITLE
inference: improve edges

### PR DESCRIPTION
**Pull request by vtjnash**
previously bestguess might be Conditional, which was very bad
also, I think there was a missing call to `update_valid_age!` in some cases?

### CODE REVIEW

**Comment by martinholters** [comment]
Any way this could be tested?

**Comment by ararslan** [comment]
This doesn't seem to backport very cleanly to release-0.6. Would you be willing to make a PR for this change against release-0.6?

**Comment by JeffBezanson** [comment]
My impression is only the couple small items mentioned in the OP are eligible for backporting:

> previously bestguess might be Conditional, which was very bad
> also, I think there was a missing call to update_valid_age! in some cases?

**Comment by StefanKarpinski** [comment]
@vtjnash, can you please prepare a PR of the parts of this that are actually backportable?

**Pull request merged**
