### PR TITLE
Update libgit2 to 1.2.0 and remove excess patches

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
Update libgit2 to latest release

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks! AFAIK you'll also have to update the checksums at deps/checksums/libgit2 by running `make -f contrib/refresh_checksums.mk libgit2`. https://github.com/JuliaLang/julia/pull/42209 will have to be merged at the same time as this PR.

It would also be good to update https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibGit2/build_tarballs.jl (it claims version 1.2.3 but that's different from the upstream version).

**Comment by jeremiahpslewis** [comment]
@nalimilan Thoughts about why the new LibGit2 (from source) version isn't used?

**Comment by nalimilan** [comment]
Maybe you should try updating Yggdrasil first?

**Comment by jeremiahpslewis** [comment]
@nalimilan Hmm..now I’m confused…Yggdrasil has the latest version already…(though I just opened a PR to remove an unnecessary patch)

**Comment by nalimilan** [comment]
Actually it uses commit https://github.com/libgit2/libgit2/commit/7f4fa178629d559c037a1f72f79f79af9c1ef8ce, which is 1.1.0. As I said, don't trust the version number!

**Comment by jeremiahpslewis** [comment]
@nalimilan Ok, now I get what you meant. My PR here should do the trick: https://github.com/JuliaPackaging/Yggdrasil/pull/3649

**Comment by vtjnash** [comment]
Now at v1.3 already

**Pull request closed without merging**
