### PR TITLE
Backports for 1.10.0-rc2

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #51213 
- [x] #51520 
- [x] #51598 
- [x] #51757 
- [x] #51781 
- [x] #51848 
- [x] #51847 
- [x] #50824 
- [x] #51885 
- [x] #50207 
- [x] #51967 
- [x] #51980 
- [x] #51995 
- [x] #52098 
- [x] #52136 
- [x] #52140 
- [x] #52009 
- [x] #52192 
- [x] #52206 
- [x] #52027 
- [x] #52217 
- [x] #51371 
- [x] #52214 
- [x] #51895 
- [x] #51596 
- [x] #51834 
- [x] #52010 
- [x] #51430 
- [x] #51471 
- [x] #52194 
- [x] #51035 
- [x] #52030 
- [x] #52189 
- [x] #52228 

Need manual backport:
- [x] #52182 

Contains multiple commits, manual intervention needed:
- [ ] #51092 

Non-merged PRs with backport label:
- [ ] #52196 
- [ ] #52170 
- [ ] #51479

### CODE REVIEW

**Comment by ViralBShah** [comment]
We need #51725 here (just the SuiteSparse_jll bump part)

**Comment by KristofferC** [comment]
> We need https://github.com/JuliaLang/julia/pull/51725 here (Basically everything in that PR except for the SparseArrays version bump)

I think this was already done for rc1?

https://github.com/JuliaLang/julia/commit/5ded9ab8a078e22dd6b95076d2b89182bd621ea5

Anyway, it would be better for the SparseArrays.jl maintainers to push updates to that package to this branch because it has gotten a bit confusing to me what should be included and not etc.

**Comment by ViralBShah** [comment]
@dkarrasch Would it be possible for you to pull in SparseArrays? My understanding is that we should be pulling in whatever is the top of the 1.10 release branch on SparseArrays.jl.

**Comment by KristofferC** [comment]
> My understanding is that we should be pulling in whatever is the top of the 1.10 release branch on SparseArrays.jl.

Yes, that was done in https://github.com/JuliaLang/julia/commit/5ded9ab8a078e22dd6b95076d2b89182bd621ea5. I updated it now to include https://github.com/JuliaSparse/SparseArrays.jl/pull/477

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52045#issuecomment-1828347551) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/46617e5_vs_0ba6ec2/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["OneRule", "Onda", "MultivariateOrthogonalPolynomials", "ITensorVisualizationBase", "LocalSearchSolvers", "NetcdfIO", "ScientificTypes", "SolverBenchmark", "AbnormalReturns", "SMLMMetrics", "Trading", "AntennaPattern", "SimpleBio", "QUnfold", "MosimoBase", "MatrixImpute", "RobustModels", "QuartetNetworkGoodnessFit", "SchwarzChristoffel", "CategoricalDistributions", "GMT", "PQBaseCamp", "FlexiJoins", "Agents", "Express", "LIBSVM", "LinearRegressionKit", "SoilHydraulics", "SingularIntegrals", "Constraints", "SemiclassicalOrthogonalPolynomials", "Feather", "FrankWolfe", "Normalization", "AoGExtensions", "GeoStatsBase", "HybridArrays", "ONSAS", "MLJTestIntegration", "OrdinalMultinomialModels", "DIVAnd", "MLJ", "TSML", "Equate", "GeoArtifacts", "FreqTables", "Wordlegames", "PoreMatMod", "SoleLogics", "SimpleSDMDatasets", "MembraneEOS", "Attractors", "PauliPopRec", "SeasonalTrendLoess", "Compat", "GroupedTemporalTerms", "VegaLite", "ModiaResult", "Pandas", "JDF", "JuliaBUGS", "DiscretePIDs", "CmdStan", "MIPVerify", "Bio3DView", "GeoDataFrames", "EHTUVData", "Geotherm", "GenerativeTopographicMapping", "Unfolding", "Consensus", "SemanticSpaces", "SaguaroTrader", "SensitivityRankCondition", "ARDESPOT", "BioMart", "TextAnalysis", "ForecastData", "GlobalSensitivity", "GEMPIC", "NASAPrecipitation", "NISTStatisticalReferenceData", "JET", "StoppingInterface", "MicroCanonicalHMC", "CBLS", "Santiago", "BHAtp", "GeoStatsModels", "PiecewiseOrthogonalPolynomials", "HMMER", "SaguaroTraderResults", "Extremes", "FlexiMaps", "TreeParzen", "PortfolioAnalytics", "MultiwayNumberPartitioning", "QuandlAccess", "PubChemCrawler", "TexTables", "OSMToolset", "PointCloudRasterizers", "MonolithicFEMVLFS", "StatisticalMeasures", "DiffEqFinancial", "Petri", "OptimizationOptimJL"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/52045#issuecomment-1829625331) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/46617e5_vs_0ba6ec2/report.html) is available.

**Pull request merged**
