### PR TITLE
fix #16089

### LINKED ISSUE #16089: typeof_tfunc wrong for Tuples
```julia
julia> f(args...) = typeof(args)
f (generic function with 1 method)

julia> f(UInt8) # correct
Tuple{DataType}

julia> @code_typed f(UInt8) # wrong
1-element Array{Any,1}:
 LambdaInfo for f
:(begin  # REPL[1], line 1:
        return Tuple{Type{UInt8}}
    end::Type{Tuple{Type{UInt8}}})

julia> g() = f(UInt8)
julia> g() # wrong
Tuple{Type{UInt8}}
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
Forming the type of a vararg tuple needed to call `tuple_tfunc`.

### CODE REVIEW

**Comment by vtjnash** [comment]
apparently something was depending on this information:
```
Exception running test linalg/qr : 
On worker 3:
LoadError: return type Base.LinAlg.QRCompactWY{Float32,Array{Float32,2}} does not match inferred return type Union{Base.LinAlg.QRCompactWY{Float32,Array{Float32,2}},Base.LinAlg.QRPivoted{Float32,Array{Float32,2}}} 
```

**Comment by JeffBezanson** [comment]
Ah, this is from all the `Type{Val{T}}`. Fortunately the use of it with varargs doesn't seem to be necessary.

@andreasnoack I feel like this was discussed, but how about constants like `Pivot`, `NoPivot`, `Upper`, `Lower` etc. that are of different types? Seems like a nicer API than passing `Val{false}`, and you wouldn't need to write `Type{ }` everywhere in the signatures either.

**Comment by tkelman** [comment]
little messy to have to export types that only get used as flags

**Comment by JeffBezanson** [comment]
And `Val{false}` isn't messy?

**Comment by tkelman** [comment]
it is, but at least it doesn't occupy namespace

**Comment by kmsquire** [comment]
We could move to a convention of all CAPS for constants... still in the namespace, but less likely to cause conflicts.

**Comment by vtjnash** [comment]
this PR only fixes one of the code paths that exercises the bug. here's another that doesn't appear to be fixed by this PR:
```julia
julia> f() = (typeof(x::Tuple{Type{Int}, Int}))
f (generic function with 1 method)

julia> @code_typed f()
1-element Array{Any,1}:
 LambdaInfo for f
:(begin  # REPL[3], line 1:
        return Tuple{Type{Int64},Int64}
    end::Type{Tuple{Type{Int64},Int64}})

julia> x = (Int, 1)
(Int64,1)

julia> f()
Tuple{Type{Int64},Int64}
```

(oops, this actually shows two bugs since it's also lost the UndefVar test)

**Comment by yuyichao** [comment]
> it's also lost the UndefVar test

And the [type assersion](https://github.com/JuliaLang/julia/issues/9765)

**Comment by JeffBezanson** [comment]
I think the issue there is just removing the variable. If it did the load, there would be either an undef var error or a type assert error, so it would be fine.

**Comment by StefanKarpinski** [comment]
Failure is OS X timeout. Pls merge asap.

**Comment by andreasnoack** [comment]
The main reason we ended up with using `Val` was exactly what @tkelman mentioned: to avoid all the exports. `Pivot`/`NoPivot` was actaully used the original type stable versions of the linalg functions, but it was changed to `Val` to reduce the exports.

I agree that `Val{}` is not a good solution and we don't use `Val{:U}`/`Val{:L}` anymore in LinAlg so it's only necessary to consider pivoting. We could either have a `Pivot` constant but alternatively we could try to reduce the number of types and see if it's possible to collapse `QRPivoted` into `QR` and `CholeskyPivoted` into `Cholesky`. I think it might be doable.

**Comment by StefanKarpinski** [comment]
🎉

**Pull request merged**
