### PR TITLE
Add a `@ref` to the Main docstring

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by fredrikekre** [comment]
If you want to `@ref` `varinfo` you have to (i) document `varinfo` and (ii) include it somewhere in the manual.

**Comment by ViralBShah** [comment]
Rebase to master?

**Comment by Keno** [comment]
Broke the build. Reverting.

**Comment by fredrikekre** [comment]
> Broke the build

Yea, hence https://github.com/JuliaLang/julia/pull/33357#issuecomment-535000180

**Comment by ViralBShah** [comment]
I misunderstood that comment. Didn't quite understand what include it somewhere in the manual meant.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/27014#issuecomment-622566847

**Pull request merged**
