### PR TITLE
Backports release 1.11

### LINKED ISSUE #55389: Regression in inferred return type for `join` on simple iterator.
```julia-repl
julia> itr = ("foo" for _ in 1:100)
Base.Generator{UnitRange{Int64}, var"#1#2"}(var"#1#2"(), 1:100)

julia> @code_warntype join(itr)
MethodInstance for join(::Base.Generator{UnitRange{Int64}, var"#1#2"})
  from join(iterator) @ Base strings/io.jl:374
Arguments
  #self#::Core.Const(join)
  iterator::Base.Generator{UnitRange{Int64}, var"#1#2"}
Body::Union{Base.AnnotatedString{String}, String}
```

This used to infer to `String`.

Ref https://github.com/JuliaLang/julia/pull/54919.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #54962 <!-- Add timing to precompile trace compile -->
- [x] #55180 <!-- compress jit debuginfo for easy memory savings -->
- [x] #54919 <!-- Fix annotated join with non-concrete eltype iters -->
- [x] #55013 <!-- [docs] change docstring to match code -->
- [x] #55017 <!-- TOML: Make `Dates` a type parameter -->
- [x] #54033 <!-- Fix a bug in `stack`'s DimensionMismatch error message -->
- [x] #55242 <!-- fix at-main docstring to not code quote a compat box -->
- [x] #55261 <!-- Make `jl_*affinity` tests more portable -->
- [x] #54736 <!-- specificity: ensure fast-path in `sub/eq_msp` handle missing `UnionAll` wrapper correctly. -->
- [x] #55299 <!-- typeintersect: fix bounds merging during inner `intersect_all`. -->
- [x] #55302 <!-- Add `lbt_forwarded_funcs()` to debug LBT forwarding issues -->
- [x] #55148 <!-- Random: Mark unexported public symbols as public -->
- [x] #55303 <!-- avoid overflowing show for OffsetArrays around typemax -->
- [x] #55317 <!-- Restrict argument to `isleapyear(::Integer)` -->
- [x] #55327 <!-- Profile: Fix stdlib paths -->
- [x] #55330 <!-- [libblastrampoline] Bump to v5.11.0 -->
- [x] #55310 <!-- Preserve structure in scaling triangular matrices by NaN -->
- [x] #55329 <!-- mapreduce: don't inbounds unknown functions -->
- [x] #55356 <!-- Profile: close files when assembling heap snapshot -->
- [x] #55371 <!-- Fix tr for block SymTridiagonal -->
- [x] #55307 <!-- Make REPL.TerminalMenus public -->
- [x] #55362 <!-- inference: fix missing LimitedAccuracy markers -->
- [x] #55306 <!-- AllocOpt: Fix stack lowering where alloca continas boxed and unboxed data -->
- [x] #55395 <!-- fix #55389: type-unstable `join` -->
- [x] #55226 <!-- re-add `unsafe_convert` for Reinterpret and Reshaped array -->
- [x] #55405 <!-- handle unbound vars in NTuple fields -->
- [x] #55365 <!-- ml-matches: ensure all methods are included -->
- [x] #55428 <!-- codegen: move undef freeze before promotion point -->
- [x] #55419 <!-- `stale_cachefile`: handle if the expected cache file is missing -->
- [x] #55470 <!-- Add push! implementation for AbstractArray depending only on resize! -->
- [x] #55483 <!-- fix hierarchy level of "API reference" in `Dates` documentation -->
- [x] #55268 <!-- simplify complex atanh and remove singularity perturbation -->
- [x] #55441 <!-- fix Event to use normal Condition variable -->
- [x] #55413 <!-- subtyping: fast path for lhs union and rhs typevar -->
- [x] #55492 <!-- build: add missing dependencies for expmap -->
- [x] #55507 <!-- Fix fast getptls ccall lowering. -->
- [x] #55424 <!-- add missing clamp function for IOBuffer -->
- [x] #55504 <!-- Update symmetric docstring to reflect the type of uplo -->
- [x] #55107 <!-- Make the memory GEP an inbounds GEP since the bounds check has happened somewhere else -->
- [x] #55411 <!-- Vendor the terminfo database for use with base/terminfo.jl -->
- [x] #55452 <!-- Do not load `ScopedValues` with `using` -->
- [x] #55407 <!-- Remove deprecated non string API for LLVM pass pipeline and parse all options -->
- [x] #55461 <!-- 🤖 [master] Bump the StyledStrings stdlib from d7496d2 to f6035eb -->
- [x] #55433 <!-- Backport https://github.com/JuliaLang/julia/pull/55407 to 1.11 -->
- [x] #55225 <!-- [1.11 backport] trace-compile: don't generate `precompile` statements for OpaqueClosure methods (#55072) -->
- [x] #55212 <!-- Make `Base.depwarn()` public -->
- [x] #552
- [x] #55052 <!-- Fix `(l/r)mul!` with `Diagonal`/`Bidiagonal` -->
- [x] #55251 <!-- Restrict binary ops for Diagonal and Symmetric to Number eltypes -->95 <!-- LAPACK: Aggressive constprop to concretely infer syev!/syevd! -->
- [x] #55522 <!-- Fix tr for Symmetric/Hermitian block matrices -->

Need manual backport:
- [x] #55342 <!-- Ensure bidiagonal setindex! does not read indices in error message -->

Contains multiple commits, manual intervention needed:

- [ ] #55336 <!-- codegen: take gc roots (and alloca alignment) more seriously -->


Non-merged PRs with backport label:
- [ ] #55506 <!-- Fix indexing in _mapreducedim for OffsetArrays -->
- [ ] #55500 <!-- make jl_thread_suspend_and_get_state safe -->
- [ ] #55499 <!-- propagate the terminal's `displaysize` to the `IOContext` used by the REPL -->
- [ ] #55458 <!-- Allow for generically extracting unannotated string -->
- [ ] #55457 <!-- Make AnnotateChar equality consider annotations -->
- [ ] #55453 <!-- Privatise the annotations API, for StyledStrings -->
- [ ] #55443 <!-- Add test for upper/lower/titlecase and fix call -->
- [ ] #55355 <!-- relocation: account for trailing path separator in depot paths -->
- [ ] #55220 <!-- `isfile_casesensitive` fixes on Windows -->
- [ ] #55169 <!-- `propertynames` for SVD respects private argument -->
- [ ] #54457 <!-- Make `String(::Memory)` copy -->
- [ ] #53957 <!-- tweak how filtering is done for what packages should be precompiled -->
- [ ] #51479 <!-- prevent code loading from lookin in the versioned environment when building Julia -->
- [ ] #50813 <!-- More doctests for Sockets and capitalization fix -->
- [ ] #50157 <!-- improve docs for `@inbounds` and `Base.@propagate_inbounds` -->
- [ ] #41244 <!-- Fix shell `cd` error when working dir has been deleted -->

### CODE REVIEW

**Comment by giordano** [comment]
I pushed a commit to add a NEWS entry about #45641 (ref: https://github.com/JuliaLang/julia/pull/54107#issuecomment-2252826710), basically a backport of #55282.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55344#issuecomment-2298407201) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8467772_vs_34c3a63/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ZippedArrays", "CassetteOverlay", "PolyLog", "UnixTimes", "Suppressor", "TZJData", "DateFormats", "Overseer", "Loess", "Mocking", "JuliaInterpreter", "Memento", "DispatchDoctor", "FactorLoadingMatrices", "Dubins", "MixedStructTypes", "AbstractFFTs", "ArraysOfArrays", "ExponentialAction", "DataFlowTasks", "LogDensityProblemsAD", "FlexiMaps", "JSON3", "LogExpFunctions", "LinearMaps", "NPFinancial", "CatmullRom", "ParameterHandling", "AffineArithmetic", "LIBSVM", "SatelliteDynamics", "ChainRulesTestUtils", "Polynomials", "Roots", "SpecialFunctions", "FastChebInterp", "XsdToStruct", "TypeClasses", "ImageShow", "Term", "BasicBSpline", "StatsFuns", "DataSkimmer", "JpegTurbo", "TimeSeriesEcon", "UTCDateTimes", "Quaternionic", "TimeZones", "TimesDates", "TidierDates", "DataGraphs", "DiffImageRotation", "SpectralEnvelope", "BatchedTransformations", "LaxZonedDateTimes", "HigherOrderKernels", "Hankel", "CloudEvents", "EinExprs", "Neurthino", "EnergyExpressions", "LoggingFacilities", "FeatureTransforms", "Norg", "TimeStruct", "SPDX", "RadonKA", "ForwardDiffPullbacks", "DiffPointRasterisation", "GraphViz", "TotalVariation", "ElementarySymmetricFunctions", "PkgToSoftwareBOM", "OkFiles", "MeasureBase", "DataToolkitCommon", "ChunkedCSV", "CodingTheory", "OpenAPI", "GitForge", "MatterMost", "TestTools", "OpenPolicyAgent", "SunCalc", "AnovaGLM", "ChemicalIdentifiers", "MixedModelsDatasets", "Timestream", "RangeTrees", "AWSInfinidash", "TransformSpecifications", "LabelledArrays", "Azure", "CoDa", "FHIRClient", "Bigsimr", "SmallDatasetMaker", "PetroleumModels", "OMOPCDMCohortCreator", "StateSpaceEcon", "OndaEDFSchemas", "ReverseMcCormick", "RegressionTables", "Plasmo", "AlignedSpans", "BivariateCopulas", "ClimateModels", "JDF", "SQLCompose", "TimeDag", "Bootstrap", "RecoverPose", "RDatasets", "TypeDBClient", "AbstractLogic", "TexTables", "RateTables", "VLBILikelihoods", "FredData", "BestModelSubset", "XPORTA", "PWF", "ParetoSmooth", "ScikitLearn", "DistributionMeasures", "CoinbasePro", "CompositionalNetworks", "Powersense", "Trading", "EnergyModelsCO2", "EnergyModelsRenewableProducers", "EnergyModelsGeography", "SQLREPL", "Effects", "MLUtils", "OPFSampler", "OndaEDF", "NURBS", "Transits", "LocalSearchSolvers", "CryptoMarketData", "Ripserer", "KiteUtils", "StateSpaceModels", "GraphSignals", "WinchModels", "KitePodModels", "DTables", "NetDecOPF", "DecisionMakingPolicies", "BayesSizeAndShape", "BadukGoWeiqiTools", "HDMjl", "Gadfly", "FeatureSelectors", "AtmosphericModels", "WhittleLikelihoodInference", "GLFixedEffectModels", "ImageQualityIndexes", "RDataGet", "MITgcm", "TensorTrains", "OPFLearn", "TidierDB", "POMDPSolve", "SignalingDimension", "GenieAuthorisation", "InvariantPointAttention", "PlutoStaticHTML", "JumpProcesses", "TimeZoneFinder", "OrdinalMultinomialModels", "TaijaBase", "MixedModelsSim", "MixedModelsExtras", "LiftAndLearn", "MixedModelsPermutations", "AnovaMixedModels", "OperatorFlux", "MixedModels", "ITensorMPS", "QuasiCopula", "NextGP", "WaveOpticsPropagation", "ReachabilityAnalysis", "MetidaBioeq", "EverySingleStreet", "TidierFiles", "FluxTraining", "HydroPowerSimulations", "Images", "Consensus", "BloqadeDormandPrince", "GCIdentifier", "Knockoffs", "MarginalLogDensities", "MimiRFFSPs", "ArgoData", "UnfoldSim", "Plots", "AutocorrelationShell", "KiteModels", "Simpsons", "EntropyHub", "BloqadeWaveforms", "PhyNEST", "TrillionDollarWords", "SimpleCrop", "ClimateTools", "LeafGasExchange", "Garlic", "BloqadeKrylov", "ClimatePlots", "EqualitySampler", "Lighthouse", "IonSim", "SwissVAMyKnife", "GasChromatographySimulator", "GeometricIntegrators", "RetentionParameterEstimator", "QuantumAnnealingAnalytics"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/55344#issuecomment-2301459510) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/13d440d_vs_34c3a63/report.html) is available.

**Comment by KristofferC** [comment]
gnome-shell-screenshot-7y9y6y

:tada:

**Pull request merged**
