### PR TITLE
Add checksums for `OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz`

### LINKED ISSUE #38523: Checksums for `OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz`?
Should we add the checksums for `deps/checksums/OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz` to source control?

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #38523

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@maleadt These same checksums currently exists at `deps/checksums/OpenLibm.v0.7.3-0.x86_64-apple-darwin.tar.gz/`.

However, when I run `make` on my machine, these checksums instead get downloaded to `deps/checksums/OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz/`.

**Comment by maleadt** [comment]
Ah yes, sorry. I had to rename the artifact because the one generated by Yggdrasil didn't have the version tag, but I apparently forgot to do the same for the checksums.

**Comment by DilumAluthge** [comment]
So which one should be checked in to source control?
- `OpenLibm.v0.7.3-0.x86_64-apple-darwin.tar.gz`
- `OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz`

**Comment by maleadt** [comment]
> `OpenLibm.v0.7.3-0.x86_64-apple-darwin14.tar.gz`

That's the tarball being used. The same thing may be happening for `freebsd`/`freebsd11`, which @staticfloat recently renamed the asset for too?

**Comment by DilumAluthge** [comment]
I'm now seeing the same issue for OpenBLAS. In source control we have:
```
deps/checksums/OpenBLAS.v0.3.10-3.x86_64-apple-darwin-libgfortran3.tar.gz/
```

But when I `make` locally, I have:
```
deps/checksums/OpenBLAS.v0.3.10-3.x86_64-apple-darwin14-libgfortran5.tar.gz/
```

**Pull request merged**
