### PR TITLE
Improve linear indexing performance for FastSubArrays

### PR DESCRIPTION
**Pull request by jishnub**
This PR forwards `AbstractUnitRange` indices for `FastSubArrays` to the parent, making use of the fact that the parent might have efficient vector indexing methods defined.

Some benchmarks:
<details>
  <summary>getindex benchmarking script</summary>

```julia
function getindexbench()
	a1 = rand(1000);
	b1 = @view a1[:]; # FastContiguousSubArray
	c1 = @view a1[eachindex(a1)]; # FastContiguousSubArray

	@info "views of a 1D array"
	@info "getindex with AbstractUnitRange"
	ax1 = eachindex(a1);
	@btime $a1[$ax1];
	@btime $b1[$ax1];
	@btime $c1[$ax1];

	@info "getindex with Colon"
	@btime $a1[:];
	@btime $b1[:];
	@btime $c1[:];

	a2 = rand(1000, 1000);
	b2 = @view a2[:, :]; # FastContiguousSubArray
	c2 = @view a2[eachindex(a2)]; # FastContiguousSubArray

	@info "views of a 2D array"
	@info "getindex with AbstractUnitRange"
	ax2 = eachindex(a2);
	@btime $a2[$ax2];
	@btime $b2[$ax2];
	@btime $c2[$ax2];

	@info "getindex with Colon"
	@btime $a2[:];
	@btime $b2[:];
	@btime $c2[:];

	return nothing
end
```

</details>

on master
```julia
julia> getindexbench()
[ Info: views of a 1D array
[ Info: getindex with AbstractUnitRange
  660.168 ns (1 allocation: 7.94 KiB)
  1.067 μs (1 allocation: 7.94 KiB)
  1.087 μs (1 allocation: 7.94 KiB)
[ Info: getindex with Colon
  660.567 ns (1 allocation: 7.94 KiB)
  1.353 μs (1 allocation: 7.94 KiB)
  1.083 μs (1 allocation: 7.94 KiB)
[ Info: views of a 2D array
[ Info: getindex with AbstractUnitRange
  476.558 μs (2 allocations: 7.63 MiB)
  1.171 ms (2 allocations: 7.63 MiB)
  1.134 ms (2 allocations: 7.63 MiB)
[ Info: getindex with Colon
  478.056 μs (2 allocations: 7.63 MiB)
  1.117 ms (2 allocations: 7.63 MiB)
  1.117 ms (2 allocations: 7.63 MiB)
```

this PR:
```julia
julia> getindexbench()
[ Info: views of a 1D array
[ Info: getindex with AbstractUnitRange
  679.193 ns (1 allocation: 7.94 KiB)
  695.424 ns (1 allocation: 7.94 KiB)
  691.766 ns (1 allocation: 7.94 KiB)
[ Info: getindex with Colon
  694.644 ns (1 allocation: 7.94 KiB)
  670.639 ns (1 allocation: 7.94 KiB)
  672.520 ns (1 allocation: 7.94 KiB)
[ Info: views of a 2D array
[ Info: getindex with AbstractUnitRange
  497.375 μs (2 allocations: 7.63 MiB)
  499.683 μs (2 allocations: 7.63 MiB)
  501.109 μs (2 allocations: 7.63 MiB)
[ Info: getindex with Colon
  500.335 μs (2 allocations: 7.63 MiB)
  500.966 μs (2 allocations: 7.63 MiB)
  504.430 μs (2 allocations: 7.63 MiB)
```

<details>
  <summary>setindex! benchmarking script</summary>

```julia
function setindexbench()
	a1 = rand(1000);
	a12 = copy(a1);
	b1 = @view a1[:]; # FastContiguousSubArray
	c1 = @view a1[eachindex(a1)]; # FastContiguousSubArray
	d1 = @view a1[begin:1:end]; # FastSubArray

	@info "views of a 1D array"
	@info "setindex with AbstractUnitRange"
	ax1 = eachindex(a1);
	@btime $a1[$ax1] = $a12;
	@btime $b1[$ax1] = $a12;
	@btime $c1[$ax1] = $a12;
	@btime $d1[$ax1] = $a12;

	@info "setindex with Colon"
	@btime $a1[:] = $a12;
	@btime $b1[:] = $a12;
	@btime $c1[:] = $a12;
	@btime $d1[:] = $a12;

	a2 = rand(1000, 1000);
	a22 = copy(a2);
	a2v = vec(a22);
	b2 = @view a2[:, :]; # FastContiguousSubArray
	c2 = @view a2[eachindex(a2)]; # FastContiguousSubArray
	d2 = @view a2[begin:1:end]; # 1D FastSubArray

	@info "views of a 2D array"
	@info "setindex with AbstractUnitRange"
	ax2 = eachindex(a2);
	@btime $a2[$ax2] = $a2v;
	@btime $b2[$ax2] = $a2v;
	@btime $c2[$ax2] = $a2v;
	@btime $d2[$ax2] = $a2v;

	@info "setindex with Colon"
	@btime $a2[:] = $a2v;
	@btime $b2[:] = $a2v;
	@btime $c2[:] = $a2v;
	@btime $d2[:] = $a2v;

	return nothing
end
```
</details>

master
```julia
julia> setindexbench()
[ Info: views of a 1D array
[ Info: setindex with AbstractUnitRange
  67.272 ns (0 allocations: 0 bytes)
  3.367 μs (0 allocations: 0 bytes)
  3.368 μs (0 allocations: 0 bytes)
  3.136 μs (0 allocations: 0 bytes)
[ Info: setindex with Colon
  63.101 ns (0 allocations: 0 bytes)
  1.277 μs (0 allocations: 0 bytes)
  3.368 μs (0 allocations: 0 bytes)
  3.130 μs (0 allocations: 0 bytes)
[ Info: views of a 2D array
[ Info: setindex with AbstractUnitRange
  502.179 μs (0 allocations: 0 bytes)
  3.401 ms (0 allocations: 0 bytes)
  1.403 ms (0 allocations: 0 bytes)
  3.064 ms (0 allocations: 0 bytes)
[ Info: setindex with Colon
  515.148 μs (0 allocations: 0 bytes)
  3.396 ms (0 allocations: 0 bytes)
  3.395 ms (0 allocations: 0 bytes)
  1.292 ms (0 allocations: 0 bytes)
```

this PR:
```julia
julia> setindexbench()
[ Info: views of a 1D array
[ Info: setindex with AbstractUnitRange
  75.606 ns (0 allocations: 0 bytes)
  77.707 ns (0 allocations: 0 bytes)
  81.870 ns (0 allocations: 0 bytes)
  451.902 ns (0 allocations: 0 bytes)
[ Info: setindex with Colon
  74.344 ns (0 allocations: 0 bytes)
  80.618 ns (0 allocations: 0 bytes)
  81.760 ns (0 allocations: 0 bytes)
  481.208 ns (0 allocations: 0 bytes)
[ Info: views of a 2D array
[ Info: setindex with AbstractUnitRange
  502.375 μs (0 allocations: 0 bytes)
  487.665 μs (0 allocations: 0 bytes)
  488.242 μs (0 allocations: 0 bytes)
  960.377 μs (0 allocations: 0 bytes)
[ Info: setindex with Colon
  486.549 μs (0 allocations: 0 bytes)
  489.817 μs (0 allocations: 0 bytes)
  489.038 μs (0 allocations: 0 bytes)
  953.120 μs (0 allocations: 0 bytes)
```

### CODE REVIEW

**Comment by jishnub** [comment]
There are a lot of lines changes in https://github.com/JuliaLang/julia/pull/45371/commits/4232be008751de9808593599aeb2e48b39cb102f, but that's mainly to get the `OffsetArrays` test helper in sync with the repo.

**Comment by johnnychen94** [comment]
> There are a lot of lines changes in https://github.com/JuliaLang/julia/commit/4232be008751de9808593599aeb2e48b39cb102f, but that's mainly to get the OffsetArrays test helper in sync with the repo.

I guess it's better to open a separate PR for this and merge it quickly (since it's only a test dependency). I left the version note here so we need to update it as well https://github.com/JuliaLang/julia/blob/8230203c8cf187ed15d0963314502f2f604d17a3/test/testhelpers/OffsetArrays.jl#L8

**Comment by jishnub** [comment]
Sounds good, I'll roll this back and add the `OffsetArray`s tests as a separate PR.

**Comment by N5N3** [comment]
I'm suppressing that LLVM fails to vectorlize the copy part of genetic `getindex`/`setindex!` even for 1d case.
Maybe we can optimize them if `getindex`'s `dest` (or `setindex!`'s `src`) has linear index.

**Comment by ViralBShah** [comment]
Seems nice to get in.

**Pull request merged**
