### PR TITLE
add NEWS.md entry for midpoints deprecation

### PR DESCRIPTION
**Pull request by Sacha0**
Ref. #21475. Best!

### CODE REVIEW

**Comment by giordano** [comment]
Am I missing something or there is no `midpoint` function in StatBase?  I can see only a `midpoints` exported but defined nowhere.

**Comment by Sacha0** [comment]
> Am I missing something or there is no midpoint function in StatBase? I can see only a midpoints exported but defined nowhere.

Good catch! `midpoint` is a typo. Touchup inbound. Much thanks @giordano! :)

**Comment by Sacha0** [comment]
(#22008)

**Comment by giordano** [comment]
You welcome!  But still, `midpoints` was removed from StatsBase with https://github.com/JuliaStats/StatsBase.jl/pull/144  So I don't think it's useful to refer to a non existing function.

**Comment by Sacha0** [comment]
Good point! I checked only that `StatsBase.midpoints` exists, not for deprecation. Writing out the comprehensions suggested in the deprecations (in both `Base` and `StatsBase`) in NEWS.md seems a bit overlong. What would you suggest instead? Thanks again! :)

**Comment by Sacha0** [comment]
Or perhaps `midpoints` should be un-deprecated in `StatsBase`, the argument for `midpoints`'s deprecation from `StatsBase` seemingly being `midpoints`'s inclusion in `Base`? Thoughts @ararslan @andreasnoack ?

**Comment by ararslan** [comment]
The `midpoints` deprecation suggestion is complex enough that it seems like it would be nice to have a function that does it for you. I agree that it would be good to un-deprecate it in StatsBase.

**Comment by giordano** [comment]
Probably https://github.com/JuliaStats/StatsBase.jl/pull/144 can be simply reverted, also `histrange` is no more in Julia's Base.

**Pull request merged**
