### PR TITLE
move a variable declaration into a for loop

### PR DESCRIPTION
**Pull request by bicycle1885**
Just a stylistic improvement.

### CODE REVIEW

**Comment by ivarne** [comment]
I think this style is still required by some old compillers that is still in use. (It was MS Visual Studio that still required this old coding style a few years ago to my big frustration)

**Comment by bicycle1885** [comment]
But this style is already used in the sqme file. I thought Julia does not support such old compilers.

**Comment by ivarne** [comment]
Seems like I was wrong. All `for` statements in `module.c` (exept this one) declare the loop variable in the loop header. LGTM

**Comment by bicycle1885** [comment]
> All for statements in module.c (exept this one) declare the loop variable in the loop header.

Yes, that's my point.

**Comment by tkelman** [comment]
This is a C99-ism that may not have been supported by MSVC prior to roughly 2013 or 2015, unless you compile C code under C++ mode (which is what we've been doing for building with MSVC).

**Comment by bicycle1885** [comment]
So, we can't step forward to C99 and need to step back to C89?

**Comment by tkelman** [comment]
It's fine, it's used elsewhere and MSVC support is borderline anyway.

**Comment by yuyichao** [comment]
> we can't step forward to C99

We already require c11 features.

**Comment by Keno** [comment]
I think this change is fine, esp since we use this pattern elsewhere in the code, but I also don't care enough to go and rebase it myself, since it's currently conflicted. If somebody feels strongly, we can take a separate PR (or rebase this and we can reopen).

**Pull request closed without merging**
