### PR TITLE
Docs: `julia_cmd`: Document use of `julia_cmd()[1]`

### LINKED ISSUE #48393: Make julia_exename public API?
[`Base.julia_cmd`](https://github.com/JuliaLang/julia/blob/b8adb2ede505e2d9eb2cfcd03caa64da643c9f22/base/util.jl#L155) is public API, but [`Base.julia_exename`](https://github.com/JuliaLang/julia/blob/b8adb2ede505e2d9eb2cfcd03caa64da643c9f22/base/util.jl#L237-L243) is not (it has no docstring). 

Many packages already use `julia_exename`: https://juliahub.com/ui/Search?q=julia_exename&type=code

`julia_exename` is also used in the documentation of `julia_cmd`:

```
help?> Base.julia_cmd
  Base.julia_cmd(juliapath=joinpath(Sys.BINDIR, julia_exename()); cpu_target)

  Return a julia command similar to the one of the running process. Propagates
  any of the --cpu-target, --sysimage, ...
```

### PR DESCRIPTION
**Pull request by fonsp**
Resolve https://github.com/JuliaLang/julia/issues/48393

I don't want to take up too much time for this issue, so feel free to close/edit without comment. I'm already happy to have found the solution ☺️

### CODE REVIEW

**Review by giordano — APPROVED** [review]
Looks good to me, but I'd like someone else to confirm it's ok to set this in stone.

**Comment by IanButterworth** [comment]
Seems a shame to do all the work to construct the args then throw them away. 
What about add a `julia_cmd(args=false)`?

**Comment by IanButterworth** [comment]
Or just
```julia
"""
    Base.julia_exepath()

Returns the path to the julia executable of the running process.
"""
julia_exepath() = joinpath(Sys.BINDIR, julia_exename())

...
function julia_cmd(julia=julia_exepath(); cpu_target::Union{Nothing,String} = nothing)
```

Happy to PR it if people approve

**Comment by fonsp** [comment]
@IanButterworth I don't think this will be used in performance-critical code, right?

The advantage of documenting `julia_cmd()[1]` is that it also works on past Julia versions :)

**Comment by IanButterworth** [comment]
That could be in the compat note
```julia
"""
    Base.julia_exepath()

Returns the path to the julia executable of the running process.

!!! compat julia 1.10
    This was added in Julia 1.10. In prior versions use `julia_cmd()[1]`
    
"""
julia_exepath() = joinpath(Sys.BINDIR, julia_exename())

...
function julia_cmd(julia=julia_exepath(); cpu_target::Union{Nothing,String} = nothing)
```

**Comment by IanButterworth** [comment]
We can also just merge this as is and that can be a follow-on

**Comment by fonsp** [comment]
All sounds good to me! :)

**Pull request merged**
