### PR TITLE
Replace `&hArr;` by `&harr;` in documentation

### PR DESCRIPTION
**Pull request by fingolfin**
There is no HTML entity `&hArr;` and accordingly all the usual browsers (Chrome, Firefox, Safari) don't render it.

My guess is that there is confusion because GitHub supports `&hArr;` and shows it as &hArr; (and `&harr;` as &harr;).

But here is for example what Firefox shows:
Screen Shot 2023-11-08 at 14 02 01

This patch could be backported to 1.9 and 1.10.

### CODE REVIEW

**Comment by fingolfin** [comment]
Any particular reason this isn't merged? (And backported)?

**Comment by DilumAluthge** [comment]
Hmmm. I just looked at the PDF docs for the Buildkite build of this PR, and it's still not rendering correctly. See page 505 (which is actually page 520 of the PDF).

To get the PDF, go to the [Buildkite build](https://buildkite.com/julialang/julia-master/builds/31918) for this PR, and then go to the [pdf_docs_build](https://buildkite.com/julialang/julia-master/builds/31918#018cdf71-e835-4da1-845c-97da72e71bdf) job, and then click on the "Artifacts" tab, and then click on the `TheJuliaLanguage.pdf` artifact.

Maybe this is a bug in Documenter.jl?

**Comment by DilumAluthge** [comment]
Hmmm. Even with this PR, it still looks broken.

Here are the commands that I ran:
```bash
git clone https://github.com/JuliaLang/julia.git
cd julia
git fetch origin 1588e3c965932281346b9fdbc411fa7e816729a7
git checkout 1588e3c965932281346b9fdbc411fa7e816729a7
make
make binary-dist
ls ./doc/_build/html/en/manual/noteworthy-differences.html

# Open the file in my default web browser:
open ./doc/_build/html/en/manual/noteworthy-differences.html
```

And here is a screenshot of the `noteworthy-differences.html` file when I opened it in Firefox on my machine:

screenshot

**Comment by DilumAluthge** [comment]
@mortenpi Is this a Documenter bug?

**Comment by fingolfin** [comment]
It is indeed wrong on https://docs.julialang.org/en/v1.11-dev/manual/noteworthy-differences/#Julia-and-harr;-C/C:-Namespaces

Which is weird - I thought I had actually built the docs and verified it worked? Alas I mad no record here, so now I am uncertain... of course if I dif then it was before Documenter 1.0 was released. When I am back at a computer I'll try this on the 1.9 / 1.10 release branches...

**Comment by fingolfin** [comment]
Huh, this is so weird: I just noticed that both `&harr;` but also `&hArr;` are rendered right *in the search panel*, specifically I see this (tested in Safari and Firefox on macOS):

with the 1.10 docs:
Screen Shot 2024-01-25 at 19 53 24

And with the v1.11-dev manual
Screen Shot 2024-01-25 at 19 53 47

What happens in both cases is that the ampersand is escaped, i.e. `&hArr;` is turned into `&amp;hArr;`.

So it seems my "fix" here was wrong, so sorry :-/. The real issue is escaping of HTML entities in Documenter -- and that even differs by context / where it is done, it seems, given that they are rendered fine in the search results... I just tried `pandoc` and `commonmarker` and a few other tools, they all handle HTML entities in Markdown just fine.

**Comment by mortenpi** [comment]
The `Markdown` parser doesn't support HTML entities though. So in my mind, the Documenter bug here is that _sometimes_ it doesn't escape the `&` when printing out the HTML.

As for fixing this -- I think just using the Unicode character should be enough.

**Comment by fingolfin** [comment]
@mortenpi thanks for the explanation.

I made PR #53066 as a follow up to resolve this.

**Comment by fingolfin** [comment]
If this PR here is backported then the follow-up should of course also be.

**Pull request merged**
