### PR TITLE
Add `BlasReal` qualifier to `svdfact!` for `Bidiagonal`.

### PR DESCRIPTION
**Pull request by simonbyrne**
Also removes unnecessary function definition (can be handled by generic methods).

### CODE REVIEW

**Comment by simonbyrne** [comment]
cc @andreasnoack

**Comment by andreasnoack** [comment]
LGTM

**Comment by tkelman** [comment]
What was the failure case?

**Comment by simonbyrne** [comment]
> What was the failure case?

I'm in the process of implementing a generic SVD, and I can't do this case without completely overriding it.

**Comment by simonbyrne** [comment]
Can anyone tell me what's going on with travis here? I've tried restarting it, but that hasn't helped.

**Comment by tkelman** [comment]
Travis deletes logs when you restart a build, so please copy a backup of the log to a gist before restarting any failures. It looks like the deps cache was corrupt for this branch.

**Comment by simonbyrne** [comment]
Ah, thanks. How can I clear the cache?

**Comment by tkelman** [comment]
Under Travis settings, caches, see if there's an entry for this branch or pr. I think I may have already done so.

**Pull request merged**
