### PR TITLE
Adds License headers #11023

### PR DESCRIPTION
**Pull request by peter1000**
Add script in contrib/add_license_to_files.jl

### CODE REVIEW

**Comment by simonster** [comment]
I think the link should be to http://julialang.org/license (`http` not `https`). While HTTPS is great, apparently there's no way to get GitHub Pages to use an appropriate SSL certificate for a custom domain (https://github.com/JuliaLang/julialang.github.com/issues/198), and sending people to a scary warning page seems bad.

**Comment by peter1000** [comment]
@simonster Thanks I changed the PR

**Comment by tkelman** [comment]
Nice work. The exceptions list is a little longer than I thought it would be, I'll go through it and double-check.
```
    # files to check - already copyright
    "../base/special/trig.jl",
    "../base/emoji_symbols.jl",
    "../base/grisu/LICENSE",
    "../base/linalg/givens.jl",
    "../base/latex_symbols.jl",
    "../base/sparse/csparse.jl",
    "../contrib/julia.lang",
    "../contrib/windows/julia.rc",
    "../contrib/mac/app/script",
    "../contrib/julia.appdata.xml",
    "../src/flisp/compiler.lsp",
    "../src/flisp/dirname.c",
    "../src/disasm.cpp",
    "../src/abi_win64.cpp",
    "../src/abi_x86_64.cpp",
    "../src/abi_x86.cpp",
    "../src/abi_win32.cpp",
    "../src/support/MurmurHash3.h",
    "../src/support/_longjmp.win32.S",
    "../src/support/MurmurHash3.c",
    "../src/support/ENTRY.amd64.h",
    "../src/support/strtod.c",
    "../src/support/_setjmp.win32.S",
    "../src/support/ENTRY.i387.h",
    "../src/support/END.h",
    "../src/support/asprintf.c",
    "../src/abi_llvm.cpp",
   "../test/perf/kernel/imdb-1.tsv",
   "../base/base64.jl",
   "../contrib/julia.lang",
   "../contrib/windows/julia.rc",
   "../contrib/julia-mode.el",
   "../contrib/mac/app/script",
   "../contrib/julia.appdata.xml",
  "../src/flisp/system.lsp",
   "../src/flisp/dirname.c",
   "../src/flisp/flisp.c",
   "../src/disasm.cpp",
   "../src/abi_win64.cpp",
   "../src/abi_x86_64.cpp",
   "../src/abi_x86.cpp",
   "../src/abi_win32.cpp",
   "../src/ccall.cpp",
   "../src/abi_llvm.cpp",
```

**Comment by tkelman** [comment]
I think with Grisu we should probably take the Google license from `base/grisu/LICENSE` and add it to each of the jl files in `base/grisu`, since those were ported by @quinnj based heavily on the original C++ code.

I think it would be good to rearrange the Grisu license as one commit, add the script as a second commit, then add the changes from running the script as a third, so we can split up the automated parts from the manual content.

**Comment by tkelman** [comment]
* `../base/special/trig.jl` only the `kernel_*` functions are under the Sun license, the rest of the file should be MIT - I'd say have the license header, but say "license is MIT: ..., except for kernel_* functions (see below)"
* `../base/emoji_symbols.jl` has a symbol for copyright in it, but should probably have the standard header - it is derived from a data file that is in another MIT-licensed repository, I don't know whether that is worth mentioning in the header
* `../base/latex_symbols.jl` has a symbol for copyright in it, but should probably have the standard header - again, not sure whether the licenses of the W3C and `unicode-math-table.tex` data files it's derived from matter here
* `../src/flisp/compiler.lsp` has one short define at the end that just says "Copyright (C) Marc Feeley 2006. All Rights Reserved." But if you check the linked SRFI page, it's a pretty standard MIT license. If the copied piece is considered a "substantial portion" then I think flisp is currently in violation of that license, but could be fixed pretty easily. And now that I think about it, flisp's license headers should be pointing to flisp's BSD-3 license, not Julia's MIT license. And I think you need a different comment character for scheme code.
* `../test/perf/kernel/imdb-1.tsv` happens to contain the word "license" in a movie title. The data itself appears to come from Udacity but I have no idea what license it's under.
* some of the entries in the list are duplicated, probably doesn't matter much

**Comment by pao** [comment]
(IANAL) The Unicode tables are probably safe to consider as a collection of facts and not subject to US copyrights. However, it would be good to link to the source data files as a matter of documentation if we don't already do so.

We read the `.tsv` file as data so we probably shouldn't modify it. Probably would be smart to check we didn't touch any of the input data files in `/perf` in this patch (I'm not sure if there are others).

**Comment by peter1000** [comment]
@pao we just changed files with extentions

".jl", ".sh", ".h",".c", ".cpp"

**Comment by pao** [comment]
:+1:

**Comment by peter1000** [comment]
https://github.com/JuliaLang/julia/pull/11073#issuecomment-98099389

For this commit only file extension with: ".jl", ".sh", ".h",".c", ".cpp"

if someone wants to do others they can use later the added script to change whatever they want.

**Comment by tkelman** [comment]
Cool. So I'll say remove the latex_symbols and emoji_symbols from the list of exceptions, add the grisu .jl files to the list instead of the to-be-deleted `base/grisu/LICENSE` (taking into account #11078), then the only other file that's being modified here that should need manual handling is `base/special/trig.jl`.

**Comment by peter1000** [comment]
Yes something like that and the and skipping for now thw "../src/flisp" folder as they need a other header you said. This can than be done in an extra PR

**Comment by peter1000** [comment]
**../base/base64.jl** Could probably also get an standard header  and leave the other part as it is.
# Based on code by Stefan Karpinski from https://github.com/hackerschool/WebSockets.jl (distributed under the same MIT license as Julia)

**Comment by tkelman** [comment]
Yeah I agree with that.

**Comment by peter1000** [comment]
Wonder if not the whole src/support folder should be excluded also there a number of copyrights

**Comment by tkelman** [comment]
Much of that folder appears to have originally been collected together here https://github.com/JeffBezanson/libsupport but there isn't a single unifying license on that. So aside from `src/support/utf8.c` which says it's in the public domain, I'm not sure whether any additional exceptions are needed.

**Comment by peter1000** [comment]
e.g. src/support/END.h and others: 

grep -nHIirF -- copyr (in directory: /home/workerm/0__DATA__0/0__Git__REPOSITORIES__0/julia/src/support)
./MurmurHash3.h:3:// domain. The author hereby disclaims copyright to this source code.
./_longjmp.win32.S:4: * Copyright (c) 1990 The Regents of the University of California.
./_longjmp.win32.S:13: * 1. Redistributions of source code must retain the above copyright
./_longjmp.win32.S:15: * 2. Redistributions in binary form must reproduce the above copyright
./MurmurHash3.c:3:// domain. The author hereby disclaims copyright to this source code.
./ENTRY.amd64.h:2: * Copyright (c) 1990 The Regents of the University of California.
./ENTRY.amd64.h:11: * 1. Redistributions of source code must retain the above copyright
./ENTRY.amd64.h:13: * 2. Redistributions in binary form must reproduce the above copyright
./strtod.c:49:// Copyright © 2001-2014 Python Software Foundation; All Rights Reserved
./_setjmp.win32.S:4: * Copyright (c) 1990 The Regents of the University of California.
./_setjmp.win32.S:13: * 1. Redistributions of source code must retain the above copyright
./_setjmp.win32.S:15: * 2. Redistributions in binary form must reproduce the above copyright
./ENTRY.i387.h:2: * Copyright (c) 1990 The Regents of the University of California.
./ENTRY.i387.h:11: * 1. Redistributions of source code must retain the above copyright
./ENTRY.i387.h:13: * 2. Redistributions in binary form must reproduce the above copyright
./END.h:2: * Copyright (c) 1990 The Regents of the University of California.
./END.h:11: * 1. Redistributions of source code must retain the above copyright
./END.h:13: * 2. Redistributions in binary form must reproduce the above copyright
./asprintf.c:2: * Copyright (c) 2004 Darren Tucker.
./asprintf.c:5: * Copyright (c) 1997 Todd C. Miller <Todd.Miller AT courtesan.com>
./asprintf.c:9: * copyright notice and this permission notice appear in all copies.
Search completed with 21 matches.

**Comment by tkelman** [comment]
Right, those are already on your exception list. arraylist.c, bitvector.c, hashing.c, etc are not, so I think applying the Julia license header to them might still be the right thing to do. Might want Jeff to chime in though.

**Comment by peter1000** [comment]
Updated PR

**Pull request merged**
