### PR TITLE
Update newpm pass pipeline

### PR DESCRIPTION
**Pull request by pchintalapudi**
LLVM has added many passes since last we went through our pass pipeline. This adds some of those to our pipelines, though we may want to investigate compile time impact and perhaps ifdef-ing some of the more debugging-friendly ones (ForceFunctionAttrs comes to mind).

### CODE REVIEW

**Comment by gbaraldi** [comment]
Do we want to look into the way LLVM/clang does its loop pass orderings? Specifically the unroll/jam stuff?

**Comment by pchintalapudi** [comment]
Unroll/jam is kept behind an option in clang, so I'm tempted to not include it for now. I've added a new loop unroll pass after vectorization already though.

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/49747#issuecomment-1544159946) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/e0bbaef_vs_6618d44/report.md).

**Comment by pchintalapudi** [comment]
Top 10 regressions:

| Name | Amount |
| --- | --- |
| `["simd", ("Cartesian", "axpy!", "Int32", 3, 32)]` | 1.62 (20%) |
| `["simd", ("CartesianPartition", "conditional_loop!", "Int64", 2, 32)]` | 1.62 (20%) |
| `["collection", "optimizations", ("Vector", "concrete", "Nothing")]` | 1.55 (25%) |
| `["simd", ("Cartesian", "axpy!", "Float32", 3, 32)]` | 1.55 (20%) |
| `["misc", "allocation elision view", "conditional"]` | 1.53 (5%) |
| `["misc", "allocation elision view", "no conditional"]` | 1.53 (5%) |
| `["simd", ("CartesianPartition", "conditional_loop!", "Int32", 2, 64)]` | 1.44 (20%) |
| `["simd", ("CartesianPartition", "inner", "Float64", 2, 63)]` | 1.37 (20%) |
| `["simd", ("CartesianPartition", "conditional_loop!", "Int32", 2, 32)]` | 1.36 (20%) |
| `["simd", ("CartesianPartition", "conditional_loop!", "Int32", 3, 32)]` | 1.33 (20%) |

Top 10 improvements

| Name | Amount |
| --- | --- |
| `["linalg", "arithmetic", ("3-arg mul!", 2)]` | 0.47 (45%) |
| `["sparse", "matmul", ("At_mul_B", "dense 500x5, sparse 500x500 -> dense 5x500")]` | 0.58 (30%) |
| `["sparse", "matmul", ("At_mul_B", "dense 50x5, sparse 50x500 -> dense 5x500")]` | 0.59 (30%) |
| `["union", "array", ("perf_sum", "ComplexF64", 1)]` | 0.59 (5%) |
| `["union", "array", ("perf_sum2", "ComplexF64", 1)]` | 0.59 (5%) |
| `["union", "array", ("skipmissing", "sum", "Union{Missing, ComplexF64}", 1)]` | 0.59 (5%) |
| `["sparse", "matmul", ("At_mul_B", "dense 5x5, sparse 5x500 -> dense 5x500")]` | 0.6 (30%) |
| `["sparse", "matmul", ("At_mul_B", "dense 50x50, sparse 50x50 -> dense 50x50")]` | 0.62 (30%) |
| `["simd", ("Linear", "two_reductions_aliased", "Int32", 4096)]` | 0.64 (20%) |
| `["sparse", "matmul", ("At_mul_B", "dense 500x5, sparse 500x50 -> dense 5x50")]` | 0.64 (30%) |

Overall looks like it doesn't affect benchmarks too much

**Review by vchuravy — APPROVED** [review]

**Comment by pchintalapudi** [comment]
I intend to merge this once the builds/tests come back clean.

**Pull request merged**
