### PR TITLE
Update control-flow.rst

### PR DESCRIPTION
**Pull request by aytekinar**
a minor typo fixed

### CODE REVIEW

**Comment by tkelman** [comment]
Can you fix `x is less than than y` a few lines lower to be consistent with this change?

**Comment by aytekinar** [comment]
Sorry, I noticed it later on while going thru the documentation. Now a consistent change is waiting for your confirmation.

**Comment by tkelman** [comment]
It's better if you modify the same branch to add additional commits, rather than opening separate redundant PR's for the same change.

I actually meant in the example output.

**Comment by aytekinar** [comment]
Done...

**Comment by tkelman** [comment]
Thanks, I applied this plus the extra fix I was referring to in 62a113abeb442d7f019d8a9e14d42c0d771d53f2.

**Pull request closed without merging**
