### PR TITLE
Upgrade PCRE to 10.23, FFTW to 3.3.6

### PR DESCRIPTION
**Pull request by tkelman**
I don't think this is critical, just an upstream bugfix release.

### CODE REVIEW

**Comment by tkelman** [comment]
may as well put the latest fftw in here too

**Comment by tkelman** [comment]
pcre 10.23 has a build issue on windows, so nevermind on this for now

https://build.julialang.org/builders/package_win6.2-x64/builds/1382/steps/make/logs/stdio
should be reported and fixed upstream at some point, not important enough to worry about right now

**Comment by tkelman** [comment]
Buildbots are happy with this, pcre bug patched and reported upstream.

**Comment by tkelman** [comment]
Any opinions on when to merge this? Not critical, but shouldn't be user visible either. If any problems we can of course revert, if they get identified soon enough.

**Comment by StefanKarpinski** [comment]
The sooner the better?

**Comment by tkelman** [comment]
Now I'm trying to remember if there was a reason I used FFTW 3.3.6-pl1 instead of 3.3.6-pl2. Maybe I was worried about https://github.com/FFTW/fftw3/commit/fa9f00b3831177f0a9582092f21efb14e3d4601f. Can't remember if I tried testing that version.

**Pull request merged**
