### PR TITLE
Fix a bug in the `Base.CoreLogging.env_override_minlevel` function

### LINKED ISSUE #34484: JULIA_DEBUG=logging doesn't work
The example in https://github.com/JuliaLang/julia/blob/c819cde083a8161aebd7bec626527dbec47fed44/stdlib/Logging/docs/src/index.md#environment-variables doesn't work (using `JULIA_DEBUG=all` does work).

It would be good to document what values are valid, and also add it to https://github.com/JuliaLang/julia/blob/master/doc/src/manual/environment-variables.md

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #34484

### CODE REVIEW

**Comment by tkf** [comment]
I think it's clear that `_group` expects a symbol

https://github.com/JuliaLang/julia/blob/07a16d695feeba66db2a44c640675e7974ae870b/base/logging.jl#L163-L164

Perhaps fix the macro instead?

https://github.com/JuliaLang/julia/blob/07a16d695feeba66db2a44c640675e7974ae870b/base/logging.jl#L294-L297

**Comment by DilumAluthge** [comment]
Unfortunately I do not know how to fix the macro :(

Want to take a stab at it?

**Comment by bramtayl** [comment]
```
QuoteNode(splitext(basename(file))[1])
```

This line looks suspect: I'm pretty sure it should be

```
QuoteNode(Symbol(splitext(basename(file))[1]))
```

**Comment by bramtayl** [comment]
Might be nice to have a function

```
default_group(file) = Symbol(splitext(basename(file))[1])
```
because that code appears twice

**Comment by c42f** [comment]
Yes it looks like @bramtayl is correct: this is quite an old bug (see b0075cb). The correct fix would indeed be to use `QuoteNode(Symbol(splitext(...)))` so that it's interpolated into the AST as a symbol literal rather than a string and undo the other changes.

(Side note: Interestingly, this brings into question how many people are really using this default value for something important, and suggests we might be able to change it in the future without too much disruption (cf. discussion at https://github.com/JuliaLang/julia/issues/33418#issuecomment-545405073).)

**Comment by tkf** [comment]
I opened #34509

**Comment by DilumAluthge** [comment]
Closing in favor of #34509 :)

**Pull request closed without merging**
