### PR TITLE
disallow juxtaposition with literals ending in `.`

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is likely the less-breaking part of #15731.

### CODE REVIEW

**Comment by vtjnash** [comment]
@Keno how will the affect JuliaParser?

**Comment by Keno** [comment]
We'll have to make the corresponding change there.

**Comment by PallHaraldsson** [comment]
I was going to fix this, but can't tell why the link is missing in NEWS.. No big deal, but since the syntax seems identical, I'm puzzled..

**Comment by tkelman** [comment]
Someone will have to run the news-update script in contrib to add the actual link at the bottom of the file, I think.

**Comment by JeffBezanson** [comment]
I've just been assuming we'll run news-update before release --- trying to avoid merge conflicts at the end of the file.

**Comment by tkelman** [comment]
Yes that one is more reliably automatic and not a big deal to run long after the fact, as opposed to genstdlib which is better to run simultaneously.

**Comment by stevengj** [comment]
I grepped for things that this would break in Julia packages, and all I found was `1.im` and `0.im` in QuantumOptics.jl (cc @bastikr).  I probably missed some, but it doesn't seem like this will break a lot of code.

**Pull request merged**
