### PR TITLE
bump Pkg to latest set of 1.6 backports

### LINKED ISSUE #38654: Pkg.test is broken for stdlibs not in sysimage since 1.3
https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2020-12/01/report.md

Just taking one of them:

```
     Testing Running tests...
ERROR: LoadError: ArgumentError: Package MbedTLS_jll [c8ffd9c3-330d-5841-b78e-0817d7145fa1] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:985
 [2] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:909
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:896
 [4] include
   @ ./Base.jl:386 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1208
 [6] top-level scope
   @ none:1
 [7] eval
   @ ./boot.jl:360 [inlined]
 [8] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [9] top-level scope
   @ none:1
in expression starting at /home/pkgeval/.julia/packages/MbedTLS/4YY6E/src/MbedTLS.jl:1
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/38654

### CODE REVIEW

**Comment by KristofferC** [comment]
Trying a few of the packages that started failing.

@nanosoldier `runtests(["AutoGrad", "MbedTLS", "NBodySimulator"], vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/38678#issuecomment-738022394):
```
NanosoldierError: failed to run tests: Build for julia on x86_64-linux-gnu did not complete successfully

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/ed75b75_vs_96a45ae/report.md)
cc @maleadt

**Comment by KristofferC** [comment]
I don't understand exactly how, but I guess

```
Error in testset Tar:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.6\Tar\test\runtests.jl:85
  Expression: Tar.tree_hash(tar, skip_empty = true) == hash
   Evaluated: "76b0aa58fdf559bada99754472f09838909ec4e7" == "b64eef11d100f2ccf9435f78be5459bbaabcabe6"
Error in testset Tar:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.6\Tar\test\runtests.jl:85
  Expression: Tar.tree_hash(tar, skip_empty = true) == hash
   Evaluated: "76b0aa58fdf559bada99754472f09838909ec4e7" == "b64eef11d100f2ccf9435f78be5459bbaabcabe6"
...
```

on Windows is related to https://github.com/JuliaLang/Pkg.jl/pull/2253? 

cc @StefanKarpinski, @staticfloat

**Comment by maleadt** [comment]
PkgEval doesn't work on Julia master right now: https://github.com/JuliaLang/julia/issues/38680

**Comment by StefanKarpinski** [comment]
I don't entirely understand what's happening there: @staticfloat, you changed the behavior of `GitTools.tree_hash`, right? It should be more correct now. This looks like that fix introduced a discrepancy with `Tar.tree_hash` that wasn't there previously.

**Comment by KristofferC** [comment]
That's my understanding as well.

**Comment by staticfloat** [comment]
I'm trying to reproduce this, but so far haven't been able to.

**Comment by staticfloat** [comment]
I figured it out; Stefan is going to fix `Tar` to fix that.

**Pull request merged**
