### PR TITLE
travis test compile all mode

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by tkelman** [comment]
This is quite a bit slower on the osx build where you turned it on. I'd rather work towards bringin back full test coverage there.

**Comment by vtjnash** [comment]
agreed, but in the meantime, this gives extra test coverage without needing to add another worker. it may also be possible to turn on full coverage on this branch, after a bit of additional work to identify the remaining hotspots.

**Comment by tkelman** [comment]
we could add additional linux workers via non travis CI services

**Comment by tkelman** [comment]
Again, I don't think osx travis is the right place to be experimenting with non default compile modes. We can add additional linux workers using additional, non-travis CI services.

**Pull request merged**
