### PR TITLE
Fix some documentation and deprecation issues

### PR DESCRIPTION
**Pull request by tkelman**
ref #16561 

the dict comprehension is still mentioned in the table at https://github.com/tkelman/julia/blob/d538f2920a5a9b7e0e70280a419e2f5e8fb9772a/doc/devdocs/ast.rst#bracketed-forms, I'm not sure what to replace it with

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Those table entries can just be removed (whether before or after the deprecation is removed, I don't know). They won't occur in ASTs any more.

**Comment by tkelman** [comment]
I think it's probably best to remove documentation at the same time as deprecating something, otherwise it'll sit there for who knows how long. Removing deprecations is usually a deletion of a big chunk of code, and it's too easy to skip the part about searching carefully through any remaining mentions of what you're deleting.

**Comment by tkelman** [comment]
Review appreciated, will merge later if no objections.

**Comment by JeffBezanson** [comment]
:+1: Very nice.

**Comment by tkelman** [comment]
Our various deprecation sprees may have a few conflicts. And https://github.com/tkelman/julia/blob/60c269d9e38f0416635cef8d7e543dcc54bd98b4/base/deprecated.jl#L504-L509 will give a warning (`@deprecate` wasn't quite capable of handling the new form as I think you saw before), but I think the solution there will be to just delete the 0.4 deprecations. We're not quite in 0.5-pre feature freeze yet but we're getting really close, It's been 6+ months with all of the old deprecations giving warnings.

**Comment by JeffBezanson** [comment]
Yeah, that's fine.

**Pull request merged**
