### PR TITLE
Fixed incorrect comparison in Pkg.Read.installed_version

### LINKED ISSUE #13375: Local Pkg version tags should be reported for Pkg.installed()
```julia
julia> Pkg.generate("FooBarBaz", "MIT")
INFO: Initializing FooBarBaz repo: /Users/jacobbolewski/.julia/v0.5/FooBarBaz
INFO: Origin: https://github.com/jakebolewski/FooBarBaz.jl.git
INFO: Generating LICENSE.md
INFO: Generating README.md
INFO: Generating src/FooBarBaz.jl
INFO: Generating test/runtests.jl
INFO: Generating REQUIRE
INFO: Generating .travis.yml
INFO: Generating appveyor.yml
INFO: Generating .gitignore
INFO: Committing FooBarBaz generated files

julia> Pkg.tag("FooBarBaz")
INFO: Tagging FooBarBaz v0.0.1

julia> Pkg.installed("FooBarBaz")
v"0.0.0-"
```

should report the latest tag `v0.0.1`, not `v0.0.0-`

### PR DESCRIPTION
**Pull request by wildart**
Fixed incorrect comparison in `Pkg.Read.installed_version` which affected #13375 and [StatsBase #39](https://github.com/JuliaStats/StatsBase.jl/pull/139)

### CODE REVIEW

**Comment by jakebolewski** [comment]
Cool, lgtm.  Needs a test.

**Comment by stevengj** [comment]
As a general suggestion, please use a more descriptive commit message than `fix #xxxx` — describe roughly what the commit does without forcing the reader to chase down a link on github.

e.g. `report local tags for Pkg.installed (fixes #13375)`

**Comment by simonster** [comment]
@stevengj You may already know this, but if you mouse over issue links on GitHub it gives you the issue title. Doesn't help if you're looking at the git log or an RSS feed though, so still better to be more descriptive.

**Comment by stevengj** [comment]
@simonster, it also doesn't help if you are browsing the list of pull requests.

**Comment by ScottPJones** [comment]
@simonster Also doesn't work on the phone, even if you are using something like the CodeHub app

**Comment by tkelman** [comment]
(still needs a test)

**Comment by tkelman** [comment]
still needs a test

**Pull request merged**
