### PR TITLE
rename MemoryError -> OutOfMemoryError

### PR DESCRIPTION
**Pull request by rened**
While it is clear to the core devs what a `MemoryError` is and this might feel like bike-sheddding, I believe that this will considerably improve the clarity of the error message for beginners.

This can turn the user experience of _"I get these random internal memory errors. Julia is so not stable yet."_ into _"I see, not enough memory. Will try with less data then."_

Had to invest a couple of hours myself, trying to debug these elusive `MemoryError`s which only occured on specific machines, while the root cause was so simple and my own fault.

### CODE REVIEW

**Comment by timholy** [comment]
:+1:

**Comment by aviks** [comment]
+1

**Comment by StefanKarpinski** [comment]
To be conservative, there should probably be an alias for the old name in `base/deprecated.jl`.

**Comment by rened** [comment]
Good point, added `MemoryError` to `deprecated.jl`

**Comment by rened** [comment]
The OSX build on travis had a timeout. Is there a better way to trigger a pull request rebuild than by pushing a dummy commit like I just did?

**Comment by nalimilan** [comment]
I'm able to restart the build from the Travis webpage, but maybe you need rights to do that. If not, then you can always force-push the same commit, only updating the date: `git commit --amend --date=now && git push rened +memoryerror`. The commit you added fails the tests because of whitespaces...

**Comment by nalimilan** [comment]
Oh, and you can remove that commit using `git rebase -i HEAD~2`, and then again a force-push.

**Comment by rened** [comment]
thanks for the hint!

**Comment by IainNZ** [comment]
+1 to this

**Comment by StefanKarpinski** [comment]
Seems reasonable to me. @JeffBezanson, any opinion on the name change?

**Comment by JeffBezanson** [comment]
Fine by me.

**Pull request merged**
