### PR TITLE
Bump Documenter to 0.27.0

### PR DESCRIPTION
**Pull request by mortenpi**
This will now add the old version warnings (thanks to @pfitzseb). So it should also be backported to 1.6 and 1.7 -- otherwise we would end up with versions that don't show the warning again.

I also ran `Pkg.upgrade_manifest()` on this (in the second commit). I am not quite sure what implications this might have for backports. Does 1.6 support the new format? If not, it might be necessary to just backport 81700ab.

cc @fredrikekre

### CODE REVIEW

**Comment by fredrikekre** [comment]
```
julia> using Random

julia> function f()
           Random.seed!(1)
           tsk = @async 1+1
           r = rand()
           fetch(tsk)
           return r
       end;

julia> function g()
           Random.seed!(1)
           r = rand()
           return r
       end;

julia> f()
0.32988171772455244

julia> g()
0.12187431157074147
```

**Comment by fredrikekre** [comment]
Is that behavior intended @JeffBezanson @rfourquet ?

**Comment by rfourquet** [comment]
Yes AFAIU this is intended. Each new spawned task contains a task-local RNG, which is seeded by the task-local RNG of the parent task by calling `rand` on it, so spawning a task mutates the state of the current-task-local RNG.

**Comment by rfourquet** [comment]
I didn't look at the problem of this issue, but in the example above, it's simple enough to work-around:
```julia
julia> function f()
           Random.seed!(1)
           oldrng = copy(Random.default_rng())
           tsk = @async 1+1
           copy!(Random.default_rng(), oldrng)
           r = rand()
           fetch(tsk)
           return r
       end;

julia> f()
0.12187431157074147
```
(ok, I'm not sure if this is 100% reliable, it would be if we are sure that the new task is created before the call to `copy!`.)

**Comment by fredrikekre** [comment]
That is certainly surprising.

> simple enough to work-around

Okay, but in this case it feels like an implementation detail leak out, e.g. in
```julia
using SomePackage: func

function f()
    Random.seed!(1)
    func()
    rand()
end
```
whether `func()` is implemented using tasks or not shouldn't be visible from the outside. (This is similar to what happened here: IOCapture which is a dependency of Documenter now internally spawns a task).

**Comment by rfourquet** [comment]
> it feels like an implementation detail leak out

Yeah, I guess it's the price to pay for "reproducible (schedule-independent) execution of parallel simulation code by default" (NEWS.md).
I don't know if the issue here was anticipated/discussed.

But the same issue arises when the number of times `rand()` is called in your `func` function changes, which can also be considered an implementation detail (e.g. in `Primes.factor`).

**Comment by KristofferC** [comment]
So the question is if the workaround should be done (which would bring back the original doctest output) or if this should just be merged.

**Comment by fredrikekre** [comment]
Yes pretty sure that has to be implemented. Will be a PITA if code in REPL doesn't work the same in Documenter.

**Comment by fredrikekre** [comment]
> I'm not sure if this is 100% reliable, it would be if we are sure that the new task is created before the call to copy!

That should always be the case since (I hope!) the seed for the new task is set on task creation and not when the task start.

**Comment by KristofferC** [comment]
Updated to new IOCapture that should have fixed the RNG thingy

**Review by fredrikekre — APPROVED** [review]

**Pull request merged**
