### PR TITLE
revert fma tests on windows

### PR DESCRIPTION
**Pull request by oscardssmith**
since https://github.com/JuliaLang/julia/pull/42942 somehow didn't fix it, this is the temporary sledgehammer that will get tests passing while I figure out how windows is managing to fail here.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@DilumAluthge Any idea why linux64 failed here? I can't tell from the logs.

**Comment by DilumAluthge** [comment]
Hmmm. I'm not sure. But if you look at master (https://github.com/JuliaLang/julia/commit/4c6696ed4a07417774d90952a2cb3f9631379405), the linux64 tests are passing on master.

**Comment by ViralBShah** [comment]
@oscardssmith Do you know if win64 + openlibm does pass these new tests? I don't think we ever tried.

**Comment by oscardssmith** [comment]
Not 100% sure. They should, since the openlibm implementation is pretty solid. That said, I've been unable to reproduce the failure on the windows hardware I have access to, so I'm very unsure what the problem could be.

**Pull request merged**
