### PR TITLE
Fix computation of range length in certain cases (fix #20373)

### LINKED ISSUE #20373: float ranges: if `a+n*s == b`, `length(a:s:b)` should be `n+1`
See http://stackoverflow.com/questions/41985718/why-the-values-are-not-correctly-iterated-using-range-arrays/41986875#41986875.

Example:

```jl
julia> a, s, b = 3*0.05, 0.05, 4*0.05
(0.15000000000000002,0.05,0.2)

julia> a + 1*s == b
true

julia> length(a:s:b)
1
```

Rational lifting doesn't address this case since `0.15000000000000002 != 3/20 == 0.15`.

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by tkelman** [comment]
why the skipped tests?

**Comment by StefanKarpinski** [comment]
Ok, there's a real 32-bit failure here on Linux & Windows. The stack traces seems to be junk, but the error is an InexactError, which may be from the `floor(Int, ...)` call. That was simply moved to a later point, so maybe it's something else, but this also adds tests that weren't being run before.

**Comment by StefanKarpinski** [comment]
32-bit failure is in the linspace constructor for random ranges, cc: @timholy. I'm just going to skip those tests in this PR since I haven't touched linspace at all, but I'm leaving a FIXME note and we should open a corresponding issue to fix this issue since the tests I added reveal a failure case.

**Comment by StefanKarpinski** [comment]
This PR should be squashed when merged to avoid a broken 32-bit commit in history.

**Comment by StefanKarpinski** [comment]
AppVeyor failure is unrelated, occurring after normal tests have passed (the ColorTypes thing).

**Comment by timholy** [comment]
Sorry, I didn't follow this in real time. What was the `linspace` error? The links here to the test aren't revealing.

**Comment by timholy** [comment]
Boy do we need #20005. It's one of those things that takes one person much more time than they get back, but collectively...

**Comment by StefanKarpinski** [comment]
I opened an issue here: https://github.com/JuliaLang/julia/issues/20520. The backtraces are mostly unhelpful – they simply indicate some unknown `InexactError` that occurs in that block of tests. More informative is that fact that the failure goes away when I don't call `linspace`. Unfortunately, that's all I've got.

**Pull request merged**
