### PR TITLE
🤖 Bump the Downloads stdlib from a55825b to c445f45

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Downloads
URL: https://github.com/JuliaLang/Downloads.jl.git
Branch: master
Old commit: a55825b
New commit: c445f45
Bump invoked by: @StefanKarpinski
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline a55825b..c445f45
c445f45 Merge pull request #170 from JuliaLang/tan/chunkedtransfer
4e0408a tests: use debug option to test for non/chunked uploads
911368d end-to-end tests for #167
55a0c39 add support for setting a debug callback
5bd0826 rename: singularize add_{upload,seek}_callback
ab628ab should also look into headers for input_size (#167)
```

### CODE REVIEW

**Comment by ericphanson** [comment]
Can this be backported to v1.7.2? would be really nice to get the threading fixes

**Comment by vchuravy** [comment]
@StefanKarpinski I am assuming okay to backport?

**Comment by DilumAluthge** [comment]
In general, we don't backporting these bump PRs. Instead, you need to make a backport branch on the Downloads.jl repo, backport the desired PRs there, and then make a PR to the release-1.7 branch here.

**Comment by DilumAluthge** [comment]
@StefanKarpinski If you can post the full instructions for how to do the backporting in Downloads.jl, then maybe @ericphanson can execute the steps?

**Comment by ericphanson** [comment]
hm, I see. So Downloads v1.5 is associated to Julia v1.7, and Downloads v1.6 is associated to Julia v1.8? So I guess my question then is why bugfixes were given a minor release instead of a patch release (i.e. I'd rather they were in Downloads v1.5 😈).

**Comment by DilumAluthge** [comment]
> why bugfixes were given a minor release

That seems like a mistake.

But we can remedy that by backporting the relevant bug fixes to a Downloads 1.5.x release.

**Comment by DilumAluthge** [comment]
@ericphanson Want to make the backports PR? I believe you'd target this branch: https://github.com/JuliaLang/Downloads.jl/tree/release-1.5

**Comment by DilumAluthge** [comment]
> > why bugfixes were given a minor release
> 
> ~That seems like a mistake.~

Actually, I don't think it was a mistake. Like Julia, in Downloads.jl, PRs are always made against matter, and then backported as necessary.

**Comment by ericphanson** [comment]
> Actually, I don't think it was a mistake. Like Julia, in Downloads.jl, PRs are always made against matter, and then backported as necessary.

I just mean, this commit could've bumped the version to 1.5.2: https://github.com/JuliaLang/Downloads.jl/commit/43899e71eed709866f96dd624f1c369a1c8e26a3 -- no backports needed. Though I definitely might've missed something.

**Comment by DilumAluthge** [comment]
I think the idea is that we want to always enforce the rule that we have different minor versions of Downloads.jl for different minor versions of Julia.

**Comment by ericphanson** [comment]
Ok, I'll go ahead and make the backports if a Downloads.jl maintainer can confirm they would be accepted.

**Comment by DilumAluthge** [comment]
If @StefanKarpinski can confirm that he's fine with the backports, I can do the logistical steps of merging your PR and registering a new release.

**Pull request merged**
