### PR TITLE
Add function to get libjulia path at runtime

### PR DESCRIPTION
**Pull request by tknopp**
This adds a function "jl_get_libjulia_path" that gives the path of the libjulia library at runtime.

I would propose that this path should be the first location where the sys.ji (or sys.so in the future) is searched (in jl_init and repl.c). Once the static compilation branch is merged I can make a PR for changes in jl_init and repl.c

In this PR only the addition of the function is included.

### CODE REVIEW

**Comment by stevengj** [comment]
@JeffBezanson's comment in #7801 seems relevant here.  If Julia can tell you the path you need, why not just fix it so that `jl_init` finds the correct image file using this path?

**Comment by vtjnash** [comment]
This is about finding libjulia, not sys.ji

**Comment by stevengj** [comment]
Yes, but the whole point of this patch, as I understand it, is to use the libjulia path to find sys.jl and other files.  i.e. it is not the libjulia path itself that is desired or useful.   If the goal is to set `JULIA_HOME` correctly or to locate `sys.jl` correctly, then we should do that directly.

**Comment by tknopp** [comment]
both is true. This is only about libjulia and was meant as a utility function with the motivation to fix jl_init. And #9691 shows that this is still not fixed. If Steven has a better fix this is great. IMHO jl_init should not have an argument.

**Comment by stevengj** [comment]
@tknopp, I'm not saying that we shouldn't use the libjulia location to fix `jl_init`.  I'm saying that if we want to fix `jl_init`, we should fix `jl_init`.   We can still use this code internally, but I don't see why we should export it if there is no need for it outside of `jl_init`.

**Comment by tknopp** [comment]
Yes this function does not have to be exported. The `jl_init` fix can be made on top of this PR though.

**Comment by ihnorton** [comment]
Closing as fixed by https://github.com/JuliaLang/julia/pull/21299 (`jl_init` can now find libjulia automatically). Please comment or re-open if further discussion needed.

**Pull request closed without merging**
