### PR TITLE
🤖 [master] Bump the Pkg stdlib from 8f772ffa7 to 299b77093

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Pkg
URL: https://github.com/JuliaLang/Pkg.jl.git
Stdlib branch: master
Julia branch: master
Old commit: 8f772ffa7
New commit: 299b77093
Julia version: 1.12.0-DEV
Pkg version: 1.12.0
Bump invoked by: @KristofferC
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/Pkg.jl/compare/8f772ffa72d86c81f03cddce2e779d6b330414e3...299b770939158ee148d53862e2845c11bd1f71da

```
$ git log --oneline 8f772ffa7..299b77093
299b77093 guard against isdir EACESS in completions (#3877)
b9c39a7be Merge pull request #3883 from JuliaLang/kc/resolve_tree_hash
8ab562f72 instantiate the test environment if it is in the current workspace when testing
1d961c1c9 get the correct manifest file for a workspace
e468facb5 allow `resolve` to download packages that have been deleted from disk but has a manifest entry
20ceec9b8 do not precompile full env on `using` callback from REPL (#3876)
195e17e3f Replace UnstableIO with IOContext{IO} (#3735)
00aa38cb3 add missing `**5.**` (#3870)
ac5672dad Revert "Move "Creating Packages" to Julia docs" (#3818)
```

### CODE REVIEW

**Comment by tecosaur** [comment]
I do wonder if I could be a bit greedy and hope that https://github.com/JuliaLang/Pkg.jl/pull/3884 might be merged soon and included in the Pkg bump? After being in limbo the Markdown PR feels tantalisingly within reach, so apologies if I'm badgering a bit.

**Comment by tecosaur** [comment]
Alternatively, I'd be happy to include a Pkg bump in the Markdown PR, I'm just not sure what would be preferred.

**Comment by tecosaur** [comment]
Thanks Kristoffer :heart:

_p.s. should this PR be closed now?_

**Comment by IanButterworth** [comment]
Superseded by https://github.com/JuliaLang/julia/pull/54316

**Pull request closed without merging**
