### PR TITLE
REPL: add an Option type to handle REPL options

### PR DESCRIPTION
**Pull request by rfourquet**
It was previously not practical to disable the "align" feature 
of backspace (#22939): overwriting the '\b' binding with:
`'\b' => (s,o...) -> Base.LineEdit.edit_backspace(s, false)`
worked to a certain extent, but for example it was disabling
the feature that '\b' must get you out of shell/help mode.

A new experimental Option type is introduced here, which is
meant to conveniently allow users to pass options controlling
the REPL behavior. For example:
```
atreplinit() do repl
    repl.options = Base.REPL.Options(backspace_align = false)
end
```

Also the `Options` alternative is offered to setup the `extra_repl_keymap` (and `hascolor`), instead of using the less direct `setup_interface` (but no more complicated though). Eventually, probably only one way should be supported. We could even have the following simplified API for simple but common needs: 
```
atreplinit(backspace_align=true, extra_keymap=Dict(...))
```
I didn't document this yet, until this is approved or becomes less experimental.

cc. @vtjnash who had asked me how to disable `backspace_align`.

### CODE REVIEW

**Comment by vtjnash** [comment]
Thanks for tackling this! As an alternative to `Options`, I think it may be appropriate to use simply a `Dict`?

**Comment by rfourquet** [comment]
> As an alternative to Options, I think it may be appropriate to use simply a Dict?

It may work, but a dedicated type is convenient to encode the defaults, and for data validation (check that an option passed by the user really exists, and make it easier that some options are made compatible, e.g. `backspace_align` and `backspace_adjust` here (admitedly non-essential!)). But for the user-facing API a `Dict` could be nicer indeed than to touch the `Option` type (or a function with keywords like the like example in the OP)

**Comment by rfourquet** [comment]
I will merge for now. The exact API doesn't have to be set in stone, but it responds to a need, and I would like be able to include more configuration options in follow-up PRs.

**Comment by vtjnash** [comment]
Thanks!

**Comment by maleadt** [comment]
Just FYI, I've added REPL start-up plotting at http://users.elis.ugent.be/~tbesard/julia/repl.html and it looks like this PR has regressed REPL start-up user time with ~20%.

**Comment by rfourquet** [comment]
> it looks like this PR has regressed REPL start-up user time with ~20%.

I've really no idea why this would be so... what command can I run to benchmark the REPL start-up time? When I run `$ time ./julia --startup-file=no  -i -e 'exit()'`, I can't observe this 20% increase.

**Comment by maleadt** [comment]
I use this horrible script: https://gist.github.com/maleadt/901833b0317570230e88a5868963fa05

**Comment by KristofferC** [comment]
Maybe the `precompile.jl` file need to be updated?

**Comment by rfourquet** [comment]
Ok thanks to both of you, I will investigate when I can (on travel now).

**Pull request merged**
