### PR TITLE
assume `getfield` is non-volatile if inferred to be constant

### PR DESCRIPTION
**Pull request by JeffBezanson**
Hopefully fixes regression caused by #18017.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier runbenchmarks(ALL, vs="@b80dad40ab36bcd7e11859d36b51c6afcf008148")

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@b80dad4")`

**Comment by vtjnash** [comment]
lgtm. could we test with something like checking if the following folds down to jlapi 2?

```
type A; x::Void; end
f(a::A) = a.x
```

why did this cause such performance issues?

**Comment by JeffBezanson** [comment]
I believe the big regression was due to the getfield calls in `Core.Inference.return_type` not being removed, in turn causing `promote_op` not to be constant-folded.

**Comment by JeffBezanson** [comment]
32-bit AV timeout?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18058#issuecomment-240183009) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/962a07c7bdbb854f05e9ee454e4e0d05a3fe5d35/a73f598_vs_b80dad4/report.md). cc @jrevels

**Comment by vtjnash** [comment]
looks like it fixed most of them, but all the `sumelt` are still regressed

**Comment by JeffBezanson** [comment]
It's possible that's a different issue. In my bisect I only looked at `nbody_vec` since it was the worst regression by a large margin.

**Pull request merged**
