### PR TITLE
Improve error message for character literal

### LINKED ISSUE #29982: ERROR: syntax: Invalid character literal is ambiguous
I've been using Julia for a month now and switch between many languages. Two of the other langauges i use quite a bit are SQL and python, languages that support single-quote strings. Obviously i know strings are defined using `"` double-quotes in Julia, but sometimes I slip up and define a string using `'` rather than `"`. It would be nice in these situations to return a slightly more useful error than the current one.

```julia
'this is intended to be string' #< throws ERROR: syntax: Invalid character literal
```

**improvement**
```julia
'this is intended to be string' # ERROR: syntax: char length greater than 1 (or something)
```

### PR DESCRIPTION
**Pull request by 0x005c**
Modified the error message emitted when character literal have 2 or more characters.
fixes #29982

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This is good but `''` would also report "character literal contains multiple characters" which isn't accurate. So to fix this, check for zero characters and report "invalid empty character literal" separately. You'll also want to write tests to make sure you're doing this correctly. I.e. that `''` throws the "empty literal" error while `'abc'` throws the "multiple characters" error.

**Comment by 0x005c** [comment]
@StefanKarpinski Thank you.
I fixed it, and added tests. Could you please check my changes?

**Review by StefanKarpinski — APPROVED** [review]
LGTM but @JeffBezanson should take a look.

**Comment by StefanKarpinski** [comment]
Nice work! Thanks for the improvement.

**Pull request merged**
