### PR TITLE
Test: compute at-inferred within a non-top-level context

### PR DESCRIPTION
**Pull request by mbauman**
The `@inferred` macro, when presented with a kwargs call, previously would ask return types about the function directly. This is an accurate representation of how the call behaves at top/global scope, but typically we are much more interested in the behavior of the function when called from another function with well-typed arguments. Within this context, the compiler can use inlining and other optimizations that allow some keyword functions to recover type-stability. This is becoming a common idiom within base.

This patch changes the behavior of `@inferred` to test the behavior of the `f(args..., kwargs...)` expression as though it were placed directly as written within an anonymous function.  Required for #25831.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I imagine this will cause problems with global variables. For instance if `a` is global, `@inferred(f(a))` works fine since it basically does `code_typed(f, (typeof(a),))`, but inside `()->f(a)` the `a` is `Any`.

I think it would be better to do this transformation by hand just for the tests that need it. That will also avoid generating lots of extra functions.

**Comment by mbauman** [comment]
> I imagine this will cause problems with global variables

Indeed it does — I called that a feature and even wrote a test for it.  My thought was to test it as though the exact expression were written in a function.  You're right, though, that this is different from how the non-kwargs case works.  What if I were to have it construct the anonymous function with all the arguments transformed as positional args and splice them in appropriately?

I would like to allow `@inferred` to do something like this — and more broadly, all the `@code_*` introspection macros.  I know I've been caught off guard more than once by seeing gc frames in `@code_llvm` that get optimized away once inlined into another function.

**Comment by ararslan** [comment]
For `@test` we have a tolerance keyword argument to the macro. What about having something like `@inferred(ex, scope=:global)` and `@inferred(ex, scope=:function)` with the former being the default? We could then opt into this kind of testing using `@inferred f(x) scope=:function`. Just an idea, anyway.

**Comment by JeffBezanson** [comment]
I think what's actually happening here is `gen_call_with_extracted_types` removes keyword arguments and replaces them with `Any`:

```
        if any(a->(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args)
            # remove keyword args, but call the kwfunc
            args = filter(a->!(Meta.isexpr(a, :kw) || Meta.isexpr(a, :parameters)), ex0.args)
            return quote
                local arg1 = $(esc(args[1]))
                $(fcn)(Core.kwfunc(arg1),
                       Tuple{Any, Core.Typeof(arg1),
                             $(typesof)($(map(esc, args[2:end])...)).parameters...})
            end
```

**Comment by JeffBezanson** [comment]
I'll come up with a replacement for this.

**Pull request closed without merging**
