### PR TITLE
Update LLVM to 14.0.6+0

### PR DESCRIPTION
**Pull request by vchuravy**
Additionally add patches for PPC backend

### CODE REVIEW

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46842#issuecomment-1252505398) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4f547f8_vs_276af84/report.md).

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master",  configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"]))`

**Comment by maleadt** [comment]
`configuration` needs to be a tuple.

@nanosoldier `runtests(ALL, vs = "@892f76e09c06e41bb80eeb47d28a9750826b6e40", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by maleadt** [comment]
Actually, let's run this on the merged commit.

**Comment by maleadt** [comment]
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/70fa9b1_vs_892f76e/report.html

couple of aborts there look related? ignore the read-only fs errors, going through some PkgEval changes and didn't expect so many packages to write crap into their own package folder.

**Pull request merged**
