### PR TITLE
Make Broadcasted iterable and more indexable

### PR DESCRIPTION
**Pull request by mbauman**
Defines iteration and some related traits as well as a few functions to make indexing a bit friendlier.

### CODE REVIEW

**Comment by mbauman** [comment]
Any comments here?  I feel like this should be largely unobjectionable, but I do want to point to my comment here https://github.com/JuliaLang/julia/issues/19198#issuecomment-387123756: defining iteration pretty much locks us into the status quo on the evaluation strategy.

Travis 32bit failure was a bunch of `ProcessExitedException()`s — maybe OOMs?  Appveyor looks like timeouts.

**Comment by andyferris** [comment]
FWIW I agree more-or-less completely with https://github.com/JuliaLang/julia/issues/19198#issuecomment-387123756, especially

> While it feels like we should be able to refactor Broadcasted to work purely based upon iteration alone (and not indexing), I think it'd be really hard and possibly impossible for some combinations of iterable arguments. Doing so performantly is even worse.

**Comment by StefanKarpinski** [comment]
I think the breakdown of `map` is for iterable things and `broadcast` is for indexable things furthers that position as well, so 👍. Another potential use for this is lazy construction of a broadcasted object which you could then do random access indexing into if you don't actually want to materialize the entire broadcasted array, which seems like it could be very handy sometimes, as well as intuitive. That seems at odds with an iteration-based conception of broadcasted objects.

**Comment by mbauman** [comment]
Great. Let's re-run CI now that I think things are back in working order.

**Comment by mbauman** [comment]
Travis Mac failed with a `GitError(Code:ERROR, Class:Net, curl error: Could not resolve host: github.com`.

**Pull request merged**
