### PR TITLE
Show Numbers compactly when typeinfo is a Union with Nothing or Missing

### LINKED ISSUE #26847: Redundant type information printed for arrays with Union eltype
The new `typeinfo` `IOContext` property (https://github.com/JuliaLang/julia/pull/24651/) has no effect for arrays with `Union` element types, since we require the type of elements to be exactly equal to the element type of the array. This is particular annoying for `Union{T,Missing}` arrays, for example with CategoricalArrays. A simple reproducer with only Base types is:
```julia
# OK
julia> [Some(1), Some(2)]
2-element Array{Some{Int64},1}:
 1
 2

# Too verbose
julia> [Some(1), missing]
2-element Array{Union{Missing, Some{Int64}},1}:
 Some(1)
 missing
```

The problem may be more complex to fix than it seems, given that in some cases of `Union` element types, type information for each element may still be needed to unambiguously identify each entry. For example, here the `f0` suffix adds information:
```julia
julia> Union{Float32,Float64}[1.0f0, 1.0]
2-element Array{Union{Float32, Float64},1}:
 1.0f0
 1.0  

```

By the way, the following behavior is probably a bug:
```julia
julia> Union{BigFloat,Float64}[big(1.0), 1.0]
2-element Array{Union{Float64, BigFloat},1}:
 1.0
 1.0
```

So the simplest approach would be to add a special-case for `Missing` and `Nothing`, or maybe for singleton types in general (assuming they will generally not have the same representation as another type).

Cc: @rfourquet

### LINKED ISSUE #39590: Inconsistent printing of booleans with and without missings
Applicable in versions of Julia:
1.5.3, 1.6.0-rc1

```julia
julia> rand([true,missing], 2, 2)
2×2 Array{Union{Missing, Bool},2}:
 true         missing
     missing  missing

julia> rand([true, false], 2, 2)
2×2 Array{Bool,2}:
 0  0
 0  1
```

when missing values are present, booleans are printed in a different way than without missing values, it should be consistent, either true/false or 0/1 all the times.

This was created based on the discussion in https://julialang.slack.com/archives/C67910KEH/p1612874306319500

### PR DESCRIPTION
**Pull request by LilithHafner**
Before:
```julia
julia> show(Union{Missing, Float32}[missing, 1.0])
Union{Missing, Float32}[missing, 1.0f0]
```
After:
```julia
julia> show(Union{Missing, Float32}[missing, 1.0])
Union{Missing, Float32}[missing, 1.0]
```

This is `repr`able because of

https://github.com/JuliaLang/julia/blob/a23b29cb1a6013277e381092147fc527a44d924a/base/missing.jl#L70

Fixes #39590
Fixes #26847

This cannot be extended to arbitrary types because sometimes that method is overwritten (e.g. `convert(Union{Nothing, Some{Int}}, 5)` fails)

### CODE REVIEW

**Comment by LilithHafner** [comment]
The function added here should be used in #45396 as well, creating a weak semantic merge conflict.

**Comment by StefanKarpinski** [comment]
This feels a little ad hoc and messy. How about checking if the type info intersected with `Number` is the type of the value? That would handle a union with anything that isn't a number.

**Comment by LilithHafner** [comment]
Clever!

**Review by simeonschaub — DISMISSED** [review]
This doesn't seem correct since only unions with `Nothing` or `Missing` have the necessary `convert` methods defined, so something like this will error:

```julia
julia> Union{String,Bool}[1]
ERROR: MethodError: Cannot `convert` an object of type 
  Int64 to an object of type 
  Union{Bool, String}
Closest candidates are:
  convert(::Type{T}, ::T) where T at Base.jl:61
Stacktrace:
 [1] setindex!(A::Vector{Union{Bool, String}}, x::Int64, i1::Int64)
   @ Base ./array.jl:966
 [2] getindex(#unused#::Type{Union{Bool, String}}, vals::Int64)
   @ Base ./array.jl:407
 [3] top-level scope
   @ REPL[5]:1
```

This check probably needs to be something like `typesubtract(get(io, :typeinfo, Any), Union{Nothing,Missing}) === Bool` instead

**Comment by vtjnash** [comment]
That function was deprecated a long time ago, but `Base._promote_typesubtract` will do what you are looking for, or `nonmissingtype(nonnothingtype(T))` (those are exported)

**Comment by StefanKarpinski** [comment]
Seems like for my proposal `typeintersect` will work:
```jl
julia> Base.typeintersect(Union{String,Bool}, Number)
Bool

julia> Base.typeintersect(Union{Int,Nothing,Missing}, Number)
Int64
```

**Comment by LilithHafner** [comment]
IIUC, @StefanKarpinski want `Union{String, Bool}[true]` to show as `Union{String, Bool}[1]` because it is clear to a human that that 1 represents true and @simeonschaub want to show it as `Union{String, Bool}[true]` because `Union{String, Bool}[1]` errors when evaluated.

Alternatively, we could try to define 
```julia
convert(::Type{Union{T1, NonNumber}}, x::Number) where T1 <: Number = convert(T1, x)
```
but this seems broken, fragile, and icky.



The implementation using `nonmissingtype` and `nonnothingtype` is [6ff4fc8](https://github.com/JuliaLang/julia/pull/48822/commits/6ff4fc88fdd43b6e88ce422be9a804420c5fe1cd), if we choose to revert the change @StefanKarpinski asked for.

**Comment by LilithHafner** [comment]
My new response to @StefanKarpinski's comment

> This feels a little ad hoc and messy. How about checking if the type info intersected with Number is the type of the value? That would handle a union with anything that isn't a number.

is, we should special case `missing` and `nothing` in `show` because we special case them in `convert`. Arbitrary unions with with non-`Number` types can't be printed without typeinfo because the conversion may not be defined, as @simeonschaub pointed out.

**Comment by LilithHafner** [comment]
Bump, I think that I have addressed all the comments.

**Comment by LilithHafner** [comment]
Bump

**Comment by LilithHafner** [comment]
@simeonschaub, I believe I have made your requested changes, can you confirm?

**Comment by LilithHafner** [comment]
Tagging triage to get a decision on this. Do we want this abbreviation?

**Comment by LilithHafner** [comment]
Triage says merge without the wider version and then reconsider wider version later if wanted

**Pull request merged**
