### PR TITLE
lattice: Don't forget to pass down lattice in Conditional tmerge

### PR DESCRIPTION
**Pull request by Keno**
Also add some extra cases that before were taken care of by the tmerge_fast_path at the entry to the tmerge code. I briefly considered splitting an extra slow path function to avoid the one `===` in the ConstsLattice, but in the non-equality case that check should be quite fast, so it didn't seem worth it.

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47992#issuecomment-1364637062) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c2731aa_vs_ea13810/report.md).

**Comment by Keno** [comment]
Added an appropriate fast path, which should hopefully fix the perf regression:

@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47992#issuecomment-1364656304) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8d03996_vs_21529a9/report.md).

**Pull request merged**
