### PR TITLE
introduce customizable build scripts for FreeBSD CI

### PR DESCRIPTION
**Pull request by iblislin**
See also:
  - https://github.com/JuliaLang/julia/pull/25705#issuecomment-360701168
  - https://github.com/JuliaLang/julia/pull/25705#issuecomment-360961827

---

cc @KristofferC

### CODE REVIEW

**Comment by ararslan** [comment]
This is pretty cool. I don't know that having it as separate files is ideal though.

I wonder whether it would be possible to format it as a YAML file, consistent with the other CI systems. (Not that YAML is an ideal format by any stretch of the imagination, but for some reason CI systems love it...)

**Comment by iblis17** [comment]
The motivation of separating scripts is that Buildbot can provide serval stage in a build report, thus it improves the readability and eases to search.
As you can see, i.e. https://freebsdci.julialang.org/#/builders/1/builds/7001, there are 8 stages at the moment.

About the YAML, Builbot doesn't have any support by default, maybe it need some hacking.

**Comment by iblis17** [comment]
I can merge them into single file, just make it versatile.

**Comment by iblis17** [comment]
merged via #25705

**Pull request closed without merging**
