### PR TITLE
Use yellow for unions with missing or nothing

### PR DESCRIPTION
**Pull request by KristofferC**
Since we are starting to use some "type instabilities" in Base and popular packages, it is a bit harsh to warn about these using bright red colors. Therefore, instead, use a milder yellow for Unions with `missing` or `nothing` since these unions are often intentional.

~~Also, remove highlighting of `Union{}` since these are not a problem.~~

Example screenshot:

screen shot 2018-01-16 at 12 13 50

### CODE REVIEW

**Comment by yuyichao** [comment]
> Also, remove highlighting of `Union{}` since these are not a problem.

Not true. https://github.com/JuliaLang/julia/issues/13295

**Comment by KristofferC** [comment]
Alright, I'll take that out then, even though I personally has always just been bothered by it (and people ask a bunch about it).

**Comment by yuyichao** [comment]
As I said in that thread, you are welcome to document that `Union{}` means the code is raising an error, which can have big (and fairly fundamental performance impact btw). Highlighting it the same as other (real) `Union` should also be fine.

**Comment by nalimilan** [comment]
Makes a lot of sense. Though maybe all `Union`s of concrete types should be in yellow? They are supposed to be handled relatively efficiently by the compiler, contrary to `::Any` or `::Real`. Then the user can evaluate whether that's intended or not.

**Comment by KristofferC** [comment]
> They are supposed to be handled relatively efficiently by the compiler, contrary to ::Any or ::Real. 

True, but I would say it is perhaps more likely a mistake when you return something like `Tuple{Float64, Int}`. I think it is fine to special case nothing and missing.

**Pull request merged**
