### PR TITLE
Fix #10780

### LINKED ISSUE #10780: Build OpenBLAS with MAX_STACK_ALLOC=2048
Building OpenBLAS with MAX_STACK_ALLOC=2048 seems necessary to get proper multi-threading performance from gemv() and ger() functions.  See https://github.com/xianyi/OpenBLAS/issues/532

Options I see:
a) Negotiate with OpenBLAS project to default to MAX_STACK_ALLOC=2048 if MAX_STACK_ALLOC is unspecified in the make options.
b) Update the Julia build environment to include MAX_STACK_ALLOC=2048 for OpenBLAS.

### PR DESCRIPTION
**Pull request by ViralBShah**
Set `MAX_STACK_ALLOC=2048` on the openblas build.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@tkelman @staticfloat How do we update OpenBLAS binaries for this? Do they get rebuilt every night? Should we just wait for a new release?

**Comment by staticfloat** [comment]
@ViralBShah Ping me or @tkelman when this gets merged, and we can run a job on the buildbots that will force OpenBLAS to be rebuilt the next time a build goes through.

**Comment by tkelman** [comment]
I think we'd have to run the "clean openblas" job first, right?

**Comment by staticfloat** [comment]
We would run the "clean arpack, openblas, suite-sparse, openlibm and
openspecfun" builder, after this has been merged.  There isn't a really
great way to run that job just before merging this right now, so I would
settle for merging this, running the job, and then either waiting for
another commit to come through, or force-rebuilding this commit.

**Comment by tkelman** [comment]
Would want to make sure it doesn't cause any problems on any platforms, but the lazy way of doing that is merging (what's with the CI failures here though, how could this cause problems on CI where we aren't even building openblas from source?), but being prepared to revert if it causes any trouble.

**Comment by tkelman** [comment]
There has also been an upstream 0.2.14 that we might want to bump to? Again subject to some testing.

**Comment by ViralBShah** [comment]
Let's move to that on master right away. If all goes well with that and this PR, we can even backport.

**Comment by ViralBShah** [comment]
0.2.14 is a dependency for this patch. I just merged @tkelman 's PR. I will merge this next once I run the tests with 0.2.14.

**Comment by ViralBShah** [comment]
https://github.com/xianyi/OpenBLAS/releases

**Comment by ViralBShah** [comment]
Do not merge, until openblas 0.2.15 is released.

**Comment by hiccup7** [comment]
As I mentioned in #10780, my understanding is that `MAX_STACK_ALLOC=2048` is considered a requirement for OpenBLAS 0.2.14 and unnecessary for OpenBLAS 0.2.15.  Merging #10783 would fix some bugs on the Julia master branch and pave the way to resolving the OpenBLAS develop branch bugs.

**Comment by tkelman** [comment]
As I understand it, the only dll of openblas that you've tested with that had MAX_STACK_ALLOC=2048 would be the test that was using the openblas develop branch where that option is enabled by default. What measurements are you using to conclude that us setting MAX_STACK_ALLOC=2048 is a good idea?

**Comment by tkelman** [comment]
Based on #10780 I believe we should hold off on this.

**Pull request closed without merging**
