### PR TITLE
Allow inlining of constant return value of `isdefined`

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Is there a reference for the motivation for this?

**Comment by yuyichao** [comment]
Make full use of the information since we've already computed it?

**Comment by tkelman** [comment]
might it be visible in benchmarks?

**Comment by yuyichao** [comment]
Very unlikely since I don't think it's used....

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
