### PR TITLE
Clarify error messages for `convert` (fixes #13033)

### LINKED ISSUE #13033: ERROR: `convert` has no method matching convert(::Type{VarNode}, ::Type{VarNode})
I got this error
ERROR: `convert` has no method matching convert(::Type{VarNode}, ::Type{VarNode})

When I tried to assign a variable of type VarNode to the type VarNode itself. 
e.g.
some_var::VarNode
some_var = VarNode
of course I meant to assign some_var to an initialized instance of VarNode
(VarNode is just some complex type I wrote myself).  Obviously the problem is I tried to assign a variable to a type, but the error you get is not informative at all.

### PR DESCRIPTION
**Pull request by timholy**
Old behavior:

``` jl
julia> convert(5, Int)
ERROR: MethodError: `convert` has no method matching convert(::Int64, ::Type{Int64})

julia> convert(Int, Int)
ERROR: MethodError: `convert` has no method matching convert(::Type{Int64}, ::Type{Int64})
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Int64}, ::Int8)
  convert(::Type{Int64}, ::UInt8)
  ...
```

(as reported in #13033).

New behavior:

``` jl
julia> convert(5, Int)
ERROR: MethodError: First argument to `convert` must be a Type, got 5
 in eval at ./boot.jl:264

julia> Int(Int)
ERROR: MethodError: Cannot `convert` an object of type Type{Int64} to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Int64}, ::Int8)
  convert(::Type{Int64}, ::UInt8)
  ...
 in call at essentials.jl:58
 in eval at ./boot.jl:264
```

### CODE REVIEW

**Comment by timholy** [comment]
CC @outlace, @kshyatt

**Comment by kshyatt** [comment]
I think this is way more informative. LGTM.

**Comment by kshyatt** [comment]
My one concern with this is that people might be confused, because:

```julia
julia> complex(Float64)
Complex{Float64}

julia> Complex(Float64)
ERROR: MethodError: `convert` has no method matching convert(::Type{Complex{T<:Real}}, ::Type{Float64})
This may have arisen from a call to the constructor Complex{T<:Real}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{Complex{T<:Real}}, ::Complex{T<:Real})
  convert(::Type{Complex{T<:Real}}, ::Real)
  ...
 in call at essentials.jl:58
 in eval at ./boot.jl:263
```

**Comment by outlace** [comment]
Yes, definitely better than old behavior.

**Comment by ssfrr** [comment]
I definitely think this is an improvement.

**Pull request merged**
