### PR TITLE
Support building LLVM from the monorepo

### PR DESCRIPTION
**Pull request by vchuravy**
Since LLVM is now using a monorepo hosted by Github,
our build-configuration should take that into account.

### CODE REVIEW

**Comment by staticfloat** [comment]
I'm so glad this change has been going through on LLVM's side.  It makes grepping for obscure LLVM error messages so much easier.

**Review by vtjnash — APPROVED** [review]
I'll just trust you this works

**Comment by vchuravy** [comment]
> I'll just trust you this works

It works for building clang, there are a couple more esoteric options that I need to fix.

**Comment by vchuravy** [comment]
Okay I think this is now ready it should also support `BUILD_CUSTOM_LIBCXX`

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
