### PR TITLE
Remove erroneous SparseVector early exit

### LINKED ISSUE #14046: zero sparse vector error
Hi,

I am getting this error with Julia Version 0.5.0-dev+1158

v = sparsevec(zeros(10))
v + v

LoadError: MethodError: `convert` has no method matching convert(::Type{SparseVector{Tv,Ti<:Integer}}, ::Type{Float64}, ::Int64)
This may have arisen from a call to the constructor SparseVector{Tv,Ti<:Integer}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{Tv,Ti}(::Type{SparseVector{Tv,Ti<:Integer}}, !Matched::SparseMatrixCSC{Tv,Ti})
  convert{Tv}(::Type{SparseVector{Tv,Ti<:Integer}}, !Matched::AbstractArray{Tv,1})
  ...
while loading In[133], in expression starting on line 2

 in _binarymap at sparse/sparsevector.jl:815
 in + at sparse/sparsevector.jl:1051
 [inlined code] from essentials.jl:114

There is no error in Julia 0.4.0

Thanks, Gus

### PR DESCRIPTION
**Pull request by mbauman**
There is an optimization available here, but this isn't quite it. Fix #14046.

### CODE REVIEW

**Comment by tkelman** [comment]
LGTM. What's the test failure in the SparseVectors.jl version of this?

**Comment by mbauman** [comment]
SparseVectors.jl is only failing on 0.5; we should probably disable 0.5 support there since it's not needed.

**Comment by tkelman** [comment]
Ah cool, makes sense. On a small screen so didn't check the run too closely. Since we don't have version-dependent REQUIRE (only require SparseVectors to be installed if the package is being used on 0.4) for consumer packages of SparseVectors we may want to leave it as is for a while.

**Comment by mbauman** [comment]
Makes sense, thanks!

**Pull request merged**
