### PR TITLE
@inbounds a few tuple loops

### PR DESCRIPTION
**Pull request by KristofferC**
Should be safe unless I miss something obvious.

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]
Download failure on AV

**Comment by yuyichao** [comment]
This is wrong for the same reason https://github.com/JuliaLang/julia/pull/21402 is.

**Comment by KristofferC** [comment]
```diff
diff --git a/base/tuple.jl b/base/tuple.jl
index 3b0bda4ce2..41b79d2207 100644
--- a/base/tuple.jl
+++ b/base/tuple.jl
@@ -257,8 +257,9 @@ function isequal(t1::Tuple, t2::Tuple)
     if length(t1) != length(t2)
         return false
     end
-    @inbounds for i = 1:length(t1)
-        if !isequal(t1[i], t2[i])
+    for i = 1:length(t1)
+        @inbounds a, b = t1[i], t2[i]
+        if !isequal(a, b)
             return false
         end
     end
@@ -269,8 +270,9 @@ function ==(t1::Tuple, t2::Tuple)
     if length(t1) != length(t2)
         return false
     end
-    @inbounds for i = 1:length(t1)
-        if !(t1[i] == t2[i])
+    for i = 1:length(t1)
+        @inbounds a, b = t1[i], t2[i]
+        if !(a == b)
             return false
         end
     end
@@ -285,8 +287,8 @@ hash(x::Tuple, h::UInt)          = hash(x[1], hash(x[2], hash(tail(tail(x)), h))
 
 function isless(t1::Tuple, t2::Tuple)
     n1, n2 = length(t1), length(t2)
-    @inbounds for i = 1:min(n1, n2)
-        a, b = t1[i], t2[i]
+    for i = 1:min(n1, n2)
+        @inbounds a, b = t1[i], t2[i]
         if !isequal(a, b)
             return isless(a, b)
         end
```

?

**Comment by yuyichao** [comment]
That's better but AFAICT the `@inbounds` is also useless since LLVM can do that just fine.

**Comment by StefanKarpinski** [comment]
On the one hand, let's be a a bit patient and give PRs like this a little more time between being put up and merging. On the other hand, I would greatly appreciate a more detailed explanation of why this is wrong, @yuyichao. The type here is `Tuple` which is a builtin with known good behavior, there's no user callback, and the indices are clearly in bounds – so what is wrong about this?

**Comment by KristofferC** [comment]
My apologies for merging early, it seemed like a trivial thing and it had two approvals from experienced Julia programmers. Will be more patient in the future.

**Comment by yuyichao** [comment]
That's the whole point of linking to the other PR. Please read my comment there https://github.com/JuliaLang/julia/pull/21402#pullrequestreview-70896035

**Comment by KristofferC** [comment]
Maybe you can spell it out clearly for a dummy like me :). Why isn't the "propagate inbounds only one level"-protection sufficient here?

**Comment by yuyichao** [comment]
Because it is not even a protection and it propagate one level too much. You wanted to apply it on the tuple getindex, which is basically the only case LLVM can do it automatically anway, but you apply that on function with unknown input types in the loop (`isequal`, `isless`, `==`).

**Comment by StefanKarpinski** [comment]
I read the linked comment and explained in my comment why yours does not seem to apply here. If we have created a bounds check elimination mechanism that is so hard and subtle to use correctly that no one can use it without running past you for approval first, then we have a much more serious problem than this particular PR being incorrect or not, because this mechanism is exported and is something that we expect people to use safely.

In this particular case, your claim that this usage is unsafe completely violates my understanding of how the `@inbounds` mechanism is supposed to work. My understanding is that it eliminates bounds checks only in indexing calls that are lexically in the current scope. To propagate bounds checking being on or off into a called function whose implementation is in another lexical scope, one must use use `@propagate_inbounds`. In this specific case, we know that the indexing expressions `t1[i]` and `t2[i]` are safe, so we can put `@inbounds` on them. The `@inbounds` should not affect calls to other functions like `isequal`, etc. since those are not indexing expressions and the `@inbounds` annotation does not propagate into their implementation without the `@propagate_inbounds` annotation. If there is something wrong with my analysis, I would like to have it explained clearly here, without reference to some other thread. Which part of my assumptions or analysis is not correct?

**Comment by yuyichao** [comment]
> My understanding is that it eliminates bounds checks only in indexing calls that are lexically in the current scope

Nop this is wrong. It applies to all functions and that's expected since there are many functions that has similar semantics, i.e. `isassigned`. There are also many other user defined functions that has boundscheck that can be eliminated and it doesn't make any sense to have a white list for this.

In fact, you can see this clearly in the documentation of `@boundscheck`.

> If we have created a bounds check elimination mechanism that is so hard and subtle to use correctly that no one can use it without running it past you for approval first, then we have a much more serious problem 

There are two problems

1. `@inbounds` doesn't return a value, otherwise, it's completely safe and recommanded to do `@inbounds(t1[i])` instead.

    There's PR that fix this.

2. Iteration doesn't do this automatically.

    That's what the discussion following the linked PR is all about.

**Comment by KristofferC** [comment]
Could you give an example, something like

```
julia> struct S end

julia> isequal(s1::S, s2::S) = [][1] < 2
isequal (generic function with 1 method)

julia> function isless1(t1::Tuple, t2::Tuple)
           n1, n2 = length(t1), length(t2)
           @inbounds for i = 1:min(n1, n2)
               a, b = t1[i], t2[i]
               if !isequal(a, b)
                   return isless(a, b)
               end
           end
           return n1 < n2
       end
isless1 (generic function with 1 method)

julia> isless1((S(),), (S(),))
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
Stacktrace:
 [1] getindex(::Array{Any,1}, ::Int64) at ./array.jl:758
 [2] isequal(::S, ::S) at ./REPL[3]:1
 [3] isless1(::Tuple{S}, ::Tuple{S}) at ./REPL[4]:5
```

does ok.

**Comment by yuyichao** [comment]
And of course these examples are stupid but it makes perfect sense for a user defined type to have explicit bounds check in any functions. (`Base.@propagate_inbounds` makes less sense on a random function but that's not necessarily alwayse the case either)

**Comment by StefanKarpinski** [comment]
The fact that `@inbounds` applies to all function calls is very dangerous and has not be advertised sufficiently. This makes https://github.com/JuliaLang/julia/pull/15558 extremely urgent, rather than "nice to have" and the general advice when using `@inbounds` must be to only be apply it precisely to calls where it is needed, rather than the blanket usage that we currently tend to have and recommend to people precisely because we cannot write `@inbounds t[i]`.

**Comment by yuyichao** [comment]
That general advice applies only to generic code that calls user defined function and has the same contract as base that invalid input shouldn't crash. Those code usually shouldn't really use `@inbounds` to begin with...

For a lot of the other performance sensitive user/package code, putting inbounds on a body of code is not an issue at all.

**Comment by StefanKarpinski** [comment]
Yes, and for a lot of other code it's a potential segfault waiting to happen. And the problem is that it's not easy to explain to people which case they're in (this PR being a case in point). So the only safe general advice we can give is to only apply `@inbound` to precisely those expressions where they actually need to eliminate bounds checking.

**Comment by mbauman** [comment]
I'm still confused here.  Isn't this only unsafe if a library writer erroneously tags something as `Base.@propagate_inbounds`?  Isn't that the bug?

We have _always_ given library writers enough rope to allow the standard library to shoot themselves in the foot.  I'm not sure how this is different.

**Comment by StefanKarpinski** [comment]
Suppose that `isequal(::UserType, ::UserType)` or `==(::UserType, ::UserType)` have `@boundscheck` in them – I'm not sure why they would, but they certainly could. And suppose these implementations are small enough to get inlined into this code. Then this code, which calls those functions inside of an `@inbounds` annotation, will eliminate that bounds checking code, even though this code has no good reason to think that the bounds check is unnecessary – as it only intended to eliminate the bounds checks on the `t1[i]` and `t2[i]` indexing expressions.

**Comment by mbauman** [comment]
Yes, exactly.  I'd similarly argue that the existence of that `@boundscheck` block is the bug.

Like it or not, this whole scheme is driven by convention, and we're implicitly expecting everyone to follow the convention. I suppose we've never clearly defined the boundaries, though.  For example, we've found it useful to extend `@inbounds` to functions like `view` — that's a fairly clear use-case.  Should we also add `@inbounds` support to `first`?

In any case, I think the warning on `@boundscheck` describes the issue well (although it should probably be a bit more OffsetArray friendly):

> | **Warning**
> |
> |  The `@boundscheck` annotation allows you, as a library writer, to opt-in to
> |  allowing _other code_ to remove your bounds checks with `@inbounds`. As noted
> |  there, the caller must verify—using information they can access—that their
> |  accesses are valid before using `@inbounds`. For indexing into your
> |  `AbstractArray` subclasses, for example, this involves checking the indices
> |  against its `size`. Therefore, `@boundscheck` annotations should only be added
> |  to a `getindex` or `setindex!` implementation after you are certain its behavior
> |  is correct.

**Comment by StefanKarpinski** [comment]
Is the convention that people only use `@boundscheck` inside of indexing operations? If that's what we're relying on for correctness, then why not just make that the only kind of operation that it applies to. In other words, instead of having a convention that people can easily fail to follow, why not bake the correct behavior into the `@inbounds` macro?

**Comment by yuyichao** [comment]
> I'd similarly argue that the existence of that @boundscheck block is the bug.

I disagree. `@boundscheck` is to mark, well bounds check, and since I believe any code can have bounds check, it's perfectly fine to put them on the bounds checking code in any functions.

> Like it or not, this whole scheme is driven by convention, and we're implicitly expecting everyone to follow the convention. I suppose we've never clearly defined the boundaries, though. For example, we've found it useful to extend @inbounds to functions like view — that's a fairly clear use-case. Should we also add `@inbounds` support to first?

That's an orthornal issue or at least a higher level one. At the lowest level, the relation between `@inbounds` and `@boundscheck` is that the user of `@inbounds` has to be sure that the `@boundscheck` will not fail. On top of this, we can/do have higher level conventions. For example, if you are doing an `a[i]`, I think it will/can be perfectly fine to add `@inbounds` on it if the caller performs the bounds check first with, e.g. `boundscheck`. I'm not sure if we have a convention like that but we can and if we do that'll be a perfectly valid thing to do in base. Similarly, we can have such an convention for `first`, `isassign` etc, if we want to (i.e. by specifying what should boundscheck do in those functions).

However, such convention does not exist for arbitrary functions and unless a canonical way to perform the boundscheck for a function is provided, one has to assume that it is not safe to apply `@inbounds` on it. Since the only thing these functions (ones in this PR) know is that the tuple access is inbounds, it cannot assume that the `isless`, etc. function calls doesn't have bounds check in them. Just as a made up example that's more realistic, you can have a type that's only make sense to compare when they are of the same size. That's basically a bounds check and you may want to avoid checking it everytime so it makes sense to use `@inbounds` and `@boundscheck` in the code that you've checked the bound/can assume so already. However, it'll be wrong if the code from other places without your own `@inbounds` that removes the `@boundscheck`. In that sense, I think the thing that can be valid is to make these tuple functions propagate the inbounds context they are in to the callback. That changes the convention of `@propagate_inbounds` so I would not want to do that without in depth discussion but it is much more valid than having these base function making these assumptions automatically.

**Comment by mbauman** [comment]
> such convention does not exist for arbitrary functions … one has to assume that it is not safe to apply @inbounds on it

Here I agree.

> it cannot assume that the `isless`, etc. function calls doesn't have bounds check in them

Here I strongly disagree.  This is the whole point of generic functions; `isless` has a very well-defined meaning that we expect folks to follow.  I don't see how this is different from stating that "a custom type might define ``isless(::Evil, ::Evil) = run(`rm -rf /`)`` so `isless(::Tuple, ::Tuple)` is unsafe".

IMO, this all comes down to this: _what functions are users required to vet before they add `@inbounds`, and how are they supposed to know what they are_?

**Comment by yuyichao** [comment]
> I don't see how this is different from stating that "a custom type might define isless(::Evil, ::Evil) = run(`rm -rf /`) so isless(::Tuple, ::Tuple) is unsafe".

Doing it is perfectly safe or expected if that's what the type implement. OTOH, you are right that Base is definately not allowed to call random user defined functions that's not specified in the contract of the function if that's how you define "unsafe". Even if the implementation is more innocent, it's still completely invalid for base to do so for many other reasons. There are obviously a lot to be improved on the document here (i.e. define a interface and define what generic function each base function will call)

The issue here is completely different though. What you are saying is that no functions other than a few functions in base or appears in the document/tests/example sections are allowed to perform bounds check. I don't think tha makes sense. The contract of `isless` that it's expected to compare it's argument. There's no where that says that the function cannot do bounds check and though it shouldn't be common it's perfectly valid to do. Whether the bounds check exist, as far as the spec of `isless` goes and as far as Base code or fully generic code is concerned, is just an implementation detail. Code that's written specifically for this type, OTOH, can rely on it without any problem.

**Comment by mbauman** [comment]
> What you are saying is that no functions other than a few functions in base or appears in the document/tests/example sections are allowed to perform bounds check.

No, my position is not nearly that well-defined. My position is a more abstract end-goal: _it must be relatively easy for users to know if it's safe to `@inbounds` something_.  My position is that Kristoffer, Sacha, and Fredrik's instinct in approving/merging this PR should be correct, and we should define these operations in a way that makes it so.  I'm not entirely certain what that solution should be, but I want to make sure it's feasible for users to actually use `@inbounds`.

For a user to add `@inbounds`, they need to ensure that all functions called within that block satisfy their pre-requisites.  But which functions are those and what are those prerequisites?  And how does someone figure that out?  That is absolutely the question here, isn't it?

So that's why I'm talking about functions like `view`, `first`, and `isless`.  It's clear to me that `view` should obey the same semantics as `getindex`, just as it should be clear that the same notion of checking bounds of indices really doesn't make sense `isless`.  The meaning of `isless` is absolutely *not* an implementation detail, and that meaning has absolutely nothing to do with indices or array accesses as far as the caller is concerned.  Going back to your previous post, I strongly disagree that:

> it's perfectly fine to put [`@boundscheck`] on the bounds checking code in any functions.

Adding `@boundscheck` blocks is _absolutely_ dangerous… I'd say it's more dangerous than `@inbounds` for this very reason.  It's effectively blindly signing a contract that any caller will satisfy your preconditions for you. The only way for `@boundscheck` to be even marginally useful is if you can communicate that precondition to your caller.  It is absolutely *not* an implementation detail.

And that's why `first(x)` is an interesting test case. It doesn't take any indices as arguments, and as such I'd say it's on the edge of what a user might naively expect they need to vet.  Even better: it doesn't even require indexing and its prerequisite would be more general than `checkbounds(x, 1)`; it's just `!isempty(x)`.

I'm just exploring the boundaries of my own intuition here in search of a solution.  I'd like to be able to support the kinds of arbitrary functions folks are defining (a quick search reveals things like `BlockArrays.getblock` and `SIMD.vload`) while making it more obvious which base functions should be safe to extend with `@boundscheck`ed implementations.

**Comment by yuyichao** [comment]
> My position is that Kristoffer, Sacha, and Fredrik's instinct in approving/merging this PR should be correct, and we should define these operations in a way that makes it so.

They are all fine for package, user code and I would do that all the timeq. It's only because base has a higher standard that those instincts are wrong. I don't think this was even part of the consideration anyway since the lower standard in packages and user code is what causes these instincts.

That's why the `@inbounds` return value and iteration check are the correct solution for base to adopt. Whether they are urgent depends on how much of these annotation do we want to add to Base. Packages won't be affect by as much.

> But which functions are those and what are those prerequisites? And how does someone figure that out? That is absolutely the question here, isn't it?

Only functions/methods that has well defined bounds check convention, which we can define, or ones that they defined on their own. In general, as for basically all other cases, you figure that out by reading the doc and assume you need to do the safe default when it's not.

> The meaning of isless is absolutely not an implementation detail, and that meaning has absolutely nothing to do with indices or array accesses as far as the caller is concerned.

And the fact that the meaning has nothing to do with array access means that the caller is in no position to mess with it. It can absolutely do so in the function. I don't think we can say for sure that comparison has abosolute no overlap with any element access/bounds check for all possible types. And I don't think we can say for sure about it for any functions except maybe some function like `this_function_cannot_do_boundscheck`.

> I'd say it's more dangerous than `@inbounds` for this very reason.

So you are saying that since we want to add `@inbounds` in base at the wrong point we should make it useless for people that want to use it to elide bounds check in their own function/methods? The whole point of having `@inbounds` instead of `unsafe_getindex` is that we don't need to have that white list and it can work as a generic mechanism for all function and methods as long as the caller know what the callee is expecting. Changing this makes having the current boundscheck mechanism useless (strictly worse) compare to syntax rewrite.

> It's effectively blindly signing a contract that any caller will satisfy your preconditions for you. 

It's by all mean not blind since `@inbounds` is not something you do/get blindly. You are basically suggesting that putting in `@inbounds` at random point should be valid since no functions that someone else wrote should actually care other than `getindex` etc. That's again just saying that the solution you want is basically a white list and we should just do that if it's really the goal and that'll remove the awkward dependency on inlining without losing anything. That said, I still don't think that's the right goal though.

> while making it more obvious which base functions should be safe to extend with `@boundscheck`ed implementations.

I don't think we should have that list for the above reason.

**Comment by mbauman** [comment]
I don't think our positions are all that different.  I say that defining `@boundscheck` within an `isless` implementation is wrong, you say that calling `@inbounds isless(x,y)` is wrong.  Thank you for saying:

> It's only because base has a higher standard that those instincts are wrong.

because that's the crux of this disagreement.  If this is true, you should propose an addendum to the style guide or contributing.md stating that `@inbounds` scopes should be limited to precisely the operation(s) where you expect them to occur.  It's certainly not the prevailing style of base.  Heck, even lines like:

```
@inbounds X.colptr[A.rowval[k] + 1] += 1
```

would be incorrect by this definition because `SparseMatrixCSC` supports a custom integer index type that could do something whacky on addition.  It'd have to be written (assuming we can hammer out the performance issues in my inbounds PR):

```
idx = @inbounds(A.rowval[k]) + 1
val = @inbounds(X.colptr[idx]) + 1
@inbounds X.colptr[idx] = val
```

This just seems overly pedantic and legalistic.  It's crazy to trust that this custom integer type defined addition correctly, but not that it didn't use `@boundscheck` to do something idiotic in the process.

I still hold that the onus is on the library developer: s/he must ensure there's a clear contract for the given function before adding `@boundscheck` or `Base.propagate_inbounds`.  There are many fewer library authors than there are users.

Base Julia trusts library authors.  A lot.  Often in return we get performance or extensible capabilities.  In this case, we get readability and maintainability.  And we set the standard for packages and user code.

**Comment by yuyichao** [comment]
> would be incorrect by this definition because SparseMatrixCSC supports a custom integer index type that could do something whacky on addition. It'd have to be written (assuming we can hammer out the performance issues in my inbounds PR):

You can also put that as a constraint for any type you can use with SparseMatrixCSC as an index type. The major difference here is that people will use many more types with tuples than a indexing type (and I do think a julia BigInt implementation can potentially benefit from `@boundscheck` in some functions, though I'm not 100% sure and maybe not `+`) so it's an option for the index type but not for generic algorithms on containers that can hold any types.

It'll also be nice if we can have a better syntax for inbounds `setindex!`. so that sth like `@inbounds(A[i]) += .....` could work.

> I still hold that the onus is on the library developer: s/he must ensure there's a clear contract for the given function before adding `@boundscheck` or `Base.@propagate_inbounds`

That contract can be library and therefore method dependent which is why you can't rely on that if you are writing generic code. This way end user can use `@inbounds` and `@boundscheck` in their own methods whichever way they want and the only hard part is on full generic code. Doing it otherwise will make it much harder for non-generic or partially generic code (which I'm using here to refer to code that is only expected to work for types that satisfy some conditions that are not necessarily true in general) to use bounds check ellision.

**Comment by StefanKarpinski** [comment]
Custom methods are only one way that something that might do a bounds check can get introduced. Consider an implementation of a somewhat specialized map2 function:
```jl
function map2(f::Function, a::Vector, b::Vector)
    n = min(length(a), length(b))
    c = Vector{Any}(n)
    @inbounds for i = 1:n
        c[i] = f(a[i], b[i])
    end
    return c
end
```
Looks safe, right? But what if we call it this way:
```jl
julia> map2(getindex, [[1,2,3],[4,5],[6]], [3,2,1])
3-element Array{Any,1}:
 3
 5
 6
```
Now the above definition is wrong and dangerous because we accidentally applied `@inbounds` to the function argument `f`:
```jl
julia> map2(getindex, [[1,2,3],[4,5],[6]], [3,2,10])
3-element Array{Any,1}:
          3
          5
 4366402032
```
Oops. Custom method definitions of known functions are not very different from this and IMO equally dangerous. The only really safe guidance we can give is "only apply `@inbounds` to indexing calls that you actually know are safe" – which requires #15558 to be practical.

**Comment by mbauman** [comment]
I absolutely agree in that case.  Saying that we should re-write things like:

```
987:    @inbounds for j in 1:p, i in 1:p
988-        out[i,j] -= x̄ᵀ[i] * x̄ᵀ[j]' * n
989-    end
```

because we don't trust `*` and `transpose` is crazy making.  In this case, we're trusting `isequal`, `!`, `==` and `isless`.

**Comment by yuyichao** [comment]
That more of a problem to get better tool/macros to apply `@inbounds` only on the right part, not for putting arbitrary restrictions on user defined methods.

**Comment by StefanKarpinski** [comment]
Yes, where "right part" seems to most likely be "just indexing expressions" which is what I thought this already did.

**Comment by yuyichao** [comment]
Or in another word, even though I still think we should keep the inbounds mechanism so that it can work on any functions and be allowed to use in any user defined functions and methods it'll also be useful to have some helper macros that only apply that on `setindex!` (and maybe `getindex` just for consistency).

This won't be a extensible set and is just for writing generic code more conviniently since we basically only need this for things that has syntax suger that doesn't support `@inbounds` (i.e. `setindex!`).

**Comment by yuyichao** [comment]
And since I think this is only useful for writing full generic code (with a high standard) it's fine to keep the current meaning of `@inbounds` and add a limited version with a different name. I'm also kind of ok with the other way around though as long as both are available.

**Comment by StefanKarpinski** [comment]
My proposal: `@inbounds` on a block only applies to `getindex` and `setindex` calls (and maybe something with views); `@inbounds` on a call expression applies to the outermost call only.

**Comment by nalimilan** [comment]
If `for x in X` automatically skipped bounds checks (https://github.com/JuliaLang/julia/pull/15291), we wouldn't be tempted to put `@inbounds` around blocks. That would make it less problematic for `@inbounds` to have an effect on any function.

> My proposal: @inbounds on a block only applies to getindex and setindex! calls (and maybe something with views); @inbounds on a call expression applies to the outermost call only.

This sounds quite arbitrary and potentially confusing IMHO. People are likely to use `nextind`, `next`, `done`, etc. in loops, and they will expect `@inbounds` to have an effect on them.

A rule that would sound OK to me is that functions should only use `@boundscheck` for code which tests that an index argument *passed by the caller* is correct -- as the name of the macro indicates. That's the only way to ensure that the caller knows the assumptions s/he makes when adding `@inbounds`. So `isless` and `first` should *not* be allowed to use `@boundscheck` because it's not clear what assumption they make. In order to be able to write generic code, `@boundscheck` cannot have an arbitrary meaning: it must always mean the same thing for all types for a given generic function. People can always develop more macros, or add arguments to their functions, if they want to elide other correctness checks than bounds checks per se.

**Comment by yuyichao** [comment]
> as the name of the macro indicates.

There's nowhere in the name of the macro that says anything is passed by the caller. You can simply have something like a `RefArray` that holds both the array and the indices in the same object and there's no way the caller can possibly know.

**Comment by yuyichao** [comment]
I do kind of agree that the change of behavior depending on if you apply it on a block is a little arbitrary so while I see how it is probably what people want most of the time, I still slightly prefer having two versions of the macro instead of trying to guess what the caller wants...

**Comment by mbauman** [comment]
For reference, packages have defined `@boundscheck` blocks or use `@propagate_inbounds` on the following functions:

* `Base.getindex`, `Base.setindex!`, `Base.view`
* `BandedMatrices.symbanded_A_mul_B!` — elides a size check
* `BasisMatrices.funeval` — elides a size check
* `BlockArrays.getblock`, `BlockArrays.setblock!`, `BlockArrays.blocksize` — indexing-like
* `DataFrames.hash_colel` — indexing-like
* DataStructures: Circular Deque `front`, `back`, `Base.push!`, `Base.unshift!` — like `first`
* DataValueArrays: `Base.isnull(x, ::Int...)` `Base.values(x, ::Int...)` — indexing-like
* Dolo: `evaluate` — indexing-like
* `JPLEphemeris.reinterpret_getindex` — indexing-like
* `LibHealpix.lm2index` — sub2ind like?
* `ProximalBase.cdprox!` — complicated indexing-like?
* QuantEcon: calls on interpretation functions (indexing-like)
* RigidBodyDynamics: lots of internal functions with custom pre-conditions
* RRRMC/src/ArraySets: `Base.next`
* `SIMD.vload` — indexing-like
* TypeSortedCollections: `Base.map!`, `Base.foreach` — size check & indices check
* `StaticArrays.insert`, `StaticArrays.deleteat`, `setindex` — indexing-like
* StaticArrays: `Base.convert(::Type{SA}, a::AbstractArray)` — eep. size-check.
* `Tensors.tovoight!`, `Tensors.tomandel!`, etc. — indexing-like

The vast majority are indexing-like, that is, they take a collection and indices.  Some are surprising to me.  But I think I'd expect the indexing-like ones to be dangerous within `@inbounds`.

**Pull request merged**
