### PR TITLE
Addrequire

### PR DESCRIPTION
**Pull request by qyra**
Addition of a function addrequire(filename) to the Pkg module.

Loads a REQUIRE file, adds a requirement entry for each package to `Pkg.dir("REQUIRE")` and calls `Pkg.resolve()`. This uses the same low level package management functions used in normal julia modules to parse the REQUIRE so it respects version information and macros to specify operating systems.

Currently this function does not compare the julia version in the REPL to the julia version requested in the REQUIRE, it will just attempt to install correct versions of all listed packages in the current julia library folder - I could add this if it is a useful feature to have.

### CODE REVIEW

**Comment by tkelman** [comment]
Hm, what's the use case vs concatenating to `Pkg.dir("REQUIRE")` directly?

**Comment by vtjnash** [comment]
this seems to me like the sort of functionality appropriate for https://github.com/JuliaLang/PkgDev.jl

is it feasible to do so now / what would be required in Base.Pkg to make that reasonable?

**Comment by wildart** [comment]
@akrasian Why do you need to add packages to `Pkg.dir("REQUIRE")`? What is the reason for converting dependencies of the package into explicitly installed packages?

**Comment by akrasian** [comment]
PkgDev doesn't seem like it would be the most logical place for functionality like this - It's mostly designed to make writing small scripts which install their own dependencies for distribution faster, while everything in PkgDev at the moment is for publishing new modules for others to use.

Appending to Pkg.dir("REQUIRE") and calling resolve works - but then you have to perform additional checks at runtime. For example Pkg.dir("REQUIRE") might not exist yet, or the repos might be out of date. And just appending to the global require then calling resolve has some of the same issues - It depends on Add to do things like check if a package is actually defined and will just throw a keyerror otherwise, which isn't terribly user friendly. Also prints a status message if there is nothing to do.

The other option if you want to have more robust error checking is to just create a julia script which checks if each package is installed or not, then calls Pkg.add() on missing libraries, and include that script. But being able to use the same format to describe the dependencies of a script or a module is still the easiest overall.

**Comment by wildart** [comment]
It looks that you can extend `Pkg.add` to accept multiple package names for installation, rather than copying content into `Pkg.dir("REQUIRE")`(which is what `Pkg.add` actually does).

**Comment by tkelman** [comment]
multi-package `Pkg.add` would be very useful. maybe with an optional array of version numbers too.

**Pull request closed without merging**
