### PR TITLE
[release-0.6] inference edges

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by ararslan** [comment]
The Travis failures on Linux are almost certainly unrelated but are rather concerning nonetheless.

**Comment by vtjnash** [comment]
hm, yeah. It's been awhile since we've seen this 32-bit OOM

**Comment by ararslan** [comment]
Bump. I'd like to get this into 0.6.2.

**Comment by ararslan** [comment]
I've included these commits in #24519, so I'll go ahead and close this. Thanks Jameson!

**Pull request closed without merging**
