### PR TITLE
Fix #11127 Hermitian matrix multiplication

### LINKED ISSUE #11127: Hermitian matrix multiplication relies on BLAS function that isn't wrapped
In `base/linalg/symmetric.jl`, to multiply a general matrix by a Hermitian one, we can use:
`A_mul_B!{T<:BlasComplex,S<:AbstractMatrix}(y::StridedMatrix{T}, A::Hermitian{T,S}, x::StridedMatrix{T}) = BLAS.hemm!(A.uplo, one(T), A.data, B, zero(T), C)`

Cool! But in `blas.jl`, there's no wrapper for `hemm!` or `hemm`. Also, this **takes** `x` and `y` as args, yet **passes** `B` and `C` which AFAICT don't exist.

Here is a demonstration:
```julia
julia> A = randn(3,3)
3x3 Array{Float64,2}:
 0.37118   -0.115637  -0.2626
 1.44327   -0.3389    -1.36312
 0.402348   0.465449  -0.281456

julia> B = randn(3,3)
3x3 Array{Float64,2}:
  0.63778   -0.577948   0.365766
  1.185      0.115811   1.06565
 -0.446381  -0.329414  -0.504115

julia> C = complex(A,B)
3x3 Array{Complex{Float64},2}:
  0.37118+0.63778im   -0.115637-0.577948im    -0.2626+0.365766im
  1.44327+1.185im       -0.3389+0.115811im   -1.36312+1.06565im
 0.402348-0.446381im   0.465449-0.329414im  -0.281456-0.504115im

julia> C = C + C'
3x3 Array{Complex{Float64},2}:
  0.74236+0.0im         1.32763-1.76295im   0.139748+0.812146im
  1.32763+1.76295im   -0.677799+0.0im      -0.897673+1.39507im
 0.139748-0.812146im  -0.897673-1.39507im  -0.562913+0.0im

julia> C = Hermitian(C)
3x3 Base.LinAlg.Hermitian{Complex{Float64},Array{Complex{Float64},2}}:
  0.74236-0.0im         1.32763-1.76295im   0.139748+0.812146im
  1.32763+1.76295im   -0.677799-0.0im      -0.897673+1.39507im
 0.139748-0.812146im  -0.897673-1.39507im  -0.562913-0.0im

julia> D = complex(A,B)
3x3 Array{Complex{Float64},2}:
  0.37118+0.63778im   -0.115637-0.577948im    -0.2626+0.365766im
  1.44327+1.185im       -0.3389+0.115811im   -1.36312+1.06565im
 0.402348-0.446381im   0.465449-0.329414im  -0.281456-0.504115im

julia> C*D
ERROR: UndefVarError: hemm! not defined
 in * at linalg/matmul.jl:121
```

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by tkelman** [comment]
Nice. The question was raised in https://github.com/JuliaLang/julia/issues/10059 of whether or not we should define methods for `he**` functions that fall back to the real lapack routines for real input types.

**Comment by kshyatt** [comment]
Whitespace strikes again! I'm on a "roll" today.

**Comment by ihnorton** [comment]
@kshyatt there is a 'make check-whitespace' target to run the same test
locally.

**Comment by andreasnoack** [comment]
@kshyatt Great. Thanks for doing this.

As mentioned in #10059, I think we should use the `Ax_mul_Bx!` family for generic programming. If we add too many features to the BLAS wrappers, we might have to document them instead of just relying on the BLAS documentation.

**Comment by kshyatt** [comment]
@ihnorton yeah, I found out right *after* I submitted the PR. Very embarrassing!

@andreasnoack should I keep my right-sided multiplication in for now, and refrain from adding any more, or would you prefer it be removed?

**Comment by andreasnoack** [comment]
Please keep them in. They are needed.

**Comment by kshyatt** [comment]
Since I added tests in this PR and in my other one in `test/linalg/symmetric.jl` I think that's where the conflict is. Should I replay this on top of the other set of tests and fix it all up?

**Comment by tkelman** [comment]
Yeah, rebasing would be great.

**Comment by kshyatt** [comment]
Ok, rebased and tests pass. Yay!

**Comment by andreasnoack** [comment]
Thanks. Your work is highly appreciated.

**Pull request merged**
