### PR TITLE
Restore llvmcall functionality for Cxx

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by vtjnash** [comment]
i deleted this for a reason. (also `jl_merge_module` can already do this LTO)

**Comment by Keno** [comment]
Well, I restored it for a reason, namely it doesn't work. You're welcome to provide an alternative implementation.

**Comment by Keno** [comment]
More to the point, we can't destroy the Cxx shadow module completely, so jl_merge_module may not be applicable?

**Comment by tkelman** [comment]
Can this be tested in base please?

**Comment by vtjnash** [comment]
codegen must be non-destructive (it must be pure since there is no guarantees on how many times it may be called). whereas the JIT is expected to take ownership of a module and destroy it (to avoid leaking memory for Module*).

**Pull request merged**
