### PR TITLE
Added test for dumptype with a Concrete and Abstract type.

### PR DESCRIPTION
**Pull request by kczimm**
Add a test for InteractiveUtils dumptype function.

### CODE REVIEW

**Comment by Keno** [comment]
This test is failing on CI on master.

**Comment by JeffBezanson** [comment]
What is this function supposed to do? If it's supposed to find all subtypes of a type, it doesn't work. But I'm not sure since I've never used this function once.

**Comment by kczimm** [comment]
Sorry, I am feeling bad for this PR. I was looking to start contributing so I wrote a test to increase coverage but maybe the function I tried to cover is no longer needed or desired?

**Comment by JeffBezanson** [comment]
Don't worry, it's not really your fault. This was a rare kind of conflict that our CI setup can't catch since two distant pieces of code interacted (they each passed separately, but not when merged together).

The function isn't exported or documented though, so maybe we should remove it.

**Pull request merged**
