### PR TITLE
reduce the number of precompile statements

### PR DESCRIPTION
**Pull request by KristofferC**
The 32 bit build bots are crashing due to running out of memory when generating the sysimg, see:

https://build.julialang.org/#/builders/44/builds/815, https://build.julialang.org/#/builders/47/builds/807.

So for now, it seems to make sense to reduce the precompile script quite severely (basically just starting the REPL and entering 1+1).
A short-term solution to get the builds back up (and make Julia very much less pleasant to use). We really need to deal with the memory usage for this specific step or stop building on 32 bit all together...

cc @vtjnash @JeffBezanson

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Great. Have we confirmed whether this actually fixes the 32-bit buildbots?

**Comment by staticfloat** [comment]
I just force-triggered a build of this gitsha on the linux32 buildbot: https://build.julialang.org/#/builders/47/builds/809

**Comment by staticfloat** [comment]
Looks like it is, in fact working for the linux32 buildbot.  Hooray!  I've started it on the [win32](https://build.julialang.org/#/builders/44/builds/817) buildbot as well, just to make sure, and the [ubunt32](https://build.julialang.org/#/builders/68/builds/815) buildbot just to make doubly sure.

**Comment by staticfloat** [comment]
Hmmm, strange, `make release` -> `make debug` -> `make testall` caused the sysimg to be built three times.  We may have a makefile bug somewhere, but I don't think it's related to this PR.

**Comment by vtjnash** [comment]
This will hopefully be superseded by #26196

**Comment by KristofferC** [comment]
#26196 also makes build bots work and.

**Pull request closed without merging**
