### PR TITLE
Revert "faster maximum, minimum (#28849)"

### PR DESCRIPTION
**Pull request by ViralBShah**
Reverts JuliaLang/julia#30320

### CODE REVIEW

**Comment by jw3126** [comment]
I have a fix for #30320. What should I do with it? Open a new PR? Against master?

**Comment by ararslan** [comment]
Yes

**Comment by ViralBShah** [comment]
#30441 should fix the issue, in which case this bugfix PR does not need to be merged.

**Comment by ararslan** [comment]
This may still be worthwhile if the proposed fix in #30441 does not improve performance over master prior to #30320.

**Comment by ViralBShah** [comment]
I believe it retains those fixes, but good to see how the performance pans out.

**Pull request closed without merging**
