### PR TITLE
Redesign of triangular matrix types

### LINKED ISSUE #152: type stability of backslash
Note that `_var8` is `Array{Any,1}` and the backslash method as a whole has inferred return type `Any`:

``` jl
julia> (@code_typed rand(3,3)\rand(3))[1].args[2][2]
19-element Array{Any,1}:
 Any[:A,Array{Float64,2},0]
 Any[:B,Array{Float64,1},0]
 Any[symbol("#s1986"),(Int64,Int64),18]
 Any[symbol("#s1984"),(Int64,Int64),18]
 Any[:m,Int64,18]
 Any[symbol("#s1983"),(Int64,Int64),18]
 Any[:n,Int64,18]
 Any[symbol("#s1985"),Int64,2]
 Any[:_var1,Array{Float64,1},18]
 Any[:_var0,Int64,18]
 Any[:_var4,Int64,18]
 Any[:_var5,Array{Float64,2},18]
 Any[:_var8,Array{Any,1},18]
 Any[:_var2,Int64,18]
 Any[:_var3,Int64,18]
 Any[:_var6,Int64,18]
 Any[:_var7,Int64,18]
 Any[:_var9,Int64,18]
 Any[:_var10,Int64,18]

julia> (@code_typed rand(3,3)\rand(3))[1].args[3]
:(begin  # linalg/dense.jl, line 409:
        _var2 = (top(arraysize))(A::Array{Float64,2},1)::Int64
        _var3 = (top(arraysize))(A::Array{Float64,2},2)::Int64
        #s1985 = 1
        _var6 = _var2::Int64
        _var7 = (top(box))(Int64,(top(add_int))(1,1))::Int64
        m = _var6::Int64
        #s1985 = _var7::Int64
        _var9 = _var3::Int64
        _var10 = (top(box))(Int64,(top(add_int))(2,1))::Int64
        n = _var9::Int64
        #s1985 = _var10::Int64 # line 410:
        unless m::Int64 === n::Int64::Bool goto 3 # line 411:
        unless istril(A::Array{Float64,2})::Bool goto 1 # line 412:
        unless istriu(A::Array{Float64,2})::Bool goto 0
        _var1 = getindex(A::Array{Float64,2},diagind((top(arraysize))(A::Array{Float64,2},1)::Int64,(top(arraysize))(A::Array{Float64,2},2)::Int64,0)::StepRange{Int64,Int64})::Array{Float64,1}
        return $(Expr(:new, Diagonal{Float64}, :(_var1::Array{Float64,1})))::Diagonal{Float64} \ B::Array{Float64,1}::Array{Float64,1}
        0:
        chksquare(A::Array{Float64,2})::Int64
        return ((top(apply_type))(Triangular,Float64,typeof(A::Array{Float64,2})::Type{Array{Float64,2}},:L,false)::Type{_<:Triangular{Float64,Array{Float64,2},UpLo,IsUnit}})(A::Array{Float64,2})::Triangular{T,S<:AbstractArray{T,2},UpLo,IsUnit} \ B::Array{Float64,1}
        1:  # line 414:
        unless istriu(A::Array{Float64,2})::Bool goto 2
        chksquare(A::Array{Float64,2})::Int64
        return ((top(apply_type))(Triangular,Float64,typeof(A::Array{Float64,2})::Type{Array{Float64,2}},:U,false)::Type{_<:Triangular{Float64,Array{Float64,2},UpLo,IsUnit}})(A::Array{Float64,2})::Triangular{T,S<:AbstractArray{T,2},UpLo,IsUnit} \ B::Array{Float64,1}
        2:  # line 415:
        _var8 = (top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1))::Type{Array{Any,1}},$(Expr(:call1, :(top(tuple)), :Any, :Int))::(Type{Any},Type{Int64}),Array{Any,1},0,2,0)::Array{Any,1}
        _var4 = (top(arraysize))(A::Array{Float64,2},1)::Int64
        _var0 = (top(arraysize))(A::Array{Float64,2},2)::Int64
        _var5 = (top(ccall))(:jl_alloc_array_2d,$(Expr(:call1, :(top(apply_type)), :Array, Float64, 2))::Type{Array{Float64,2}},$(Expr(:call1, :(top(tuple)), :Any, :Int, :Int))::(Type{Any},Type{Int64},Type{Int64}),Array{Float64,2},0,_var4::Int64,0,_var0::Int64,0)::Array{Float64,2}
        return (top(kwcall))(call,1,:pivot,true,lufact!,_var8::Array{Any,1},copy!(_var5::Array{Float64,2},1,A::Array{Float64,2},1,(top(arraylen))(A::Array{Float64,2})::Int64)::Array{Float64,2})::LU{Float64,Array{Float64,2}} \ B::Array{Float64,1}::Array{Float64,1}
        3:  # line 417:
        return (top(kwcall))(call,1,:pivot,Float64 <: BlasFloat::Bool,qrfact,(top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1))::Type{Array{Any,1}},$(Expr(:call1, :(top(tuple)), :Any, :Int))::(Type{Any},Type{Int64}),Array{Any,1},0,2,0)::Array{Any,1},A::Array{Float64,2})::Union(QRPivoted{Float64},QRCompactWY{Float64}) \ B::Array{Float64,1}
    end)
```

### LINKED ISSUE #9191: type stability of backslash
Note that `_var8` is `Array{Any,1}` and the backslash method as a whole has inferred return type `Any`:

```jl
julia> (@code_typed rand(3,3)\rand(3))[1].args[2][2]
19-element Array{Any,1}:
 Any[:A,Array{Float64,2},0]
 Any[:B,Array{Float64,1},0]
 Any[symbol("#s1986"),(Int64,Int64),18]
 Any[symbol("#s1984"),(Int64,Int64),18]
 Any[:m,Int64,18]
 Any[symbol("#s1983"),(Int64,Int64),18]
 Any[:n,Int64,18]
 Any[symbol("#s1985"),Int64,2]
 Any[:_var1,Array{Float64,1},18]
 Any[:_var0,Int64,18]
 Any[:_var4,Int64,18]
 Any[:_var5,Array{Float64,2},18]
 Any[:_var8,Array{Any,1},18]
 Any[:_var2,Int64,18]
 Any[:_var3,Int64,18]
 Any[:_var6,Int64,18]
 Any[:_var7,Int64,18]
 Any[:_var9,Int64,18]
 Any[:_var10,Int64,18]

julia> (@code_typed rand(3,3)\rand(3))[1].args[3]
:(begin  # linalg/dense.jl, line 409:
        _var2 = (top(arraysize))(A::Array{Float64,2},1)::Int64
        _var3 = (top(arraysize))(A::Array{Float64,2},2)::Int64
        #s1985 = 1
        _var6 = _var2::Int64
        _var7 = (top(box))(Int64,(top(add_int))(1,1))::Int64
        m = _var6::Int64
        #s1985 = _var7::Int64
        _var9 = _var3::Int64
        _var10 = (top(box))(Int64,(top(add_int))(2,1))::Int64
        n = _var9::Int64
        #s1985 = _var10::Int64 # line 410:
        unless m::Int64 === n::Int64::Bool goto 3 # line 411:
        unless istril(A::Array{Float64,2})::Bool goto 1 # line 412:
        unless istriu(A::Array{Float64,2})::Bool goto 0
        _var1 = getindex(A::Array{Float64,2},diagind((top(arraysize))(A::Array{Float64,2},1)::Int64,(top(arraysize))(A::Array{Float64,2},2)::Int64,0)::StepRange{Int64,Int64})::Array{Float64,1}
        return $(Expr(:new, Diagonal{Float64}, :(_var1::Array{Float64,1})))::Diagonal{Float64} \ B::Array{Float64,1}::Array{Float64,1}
        0:
        chksquare(A::Array{Float64,2})::Int64
        return ((top(apply_type))(Triangular,Float64,typeof(A::Array{Float64,2})::Type{Array{Float64,2}},:L,false)::Type{_<:Triangular{Float64,Array{Float64,2},UpLo,IsUnit}})(A::Array{Float64,2})::Triangular{T,S<:AbstractArray{T,2},UpLo,IsUnit} \ B::Array{Float64,1}
        1:  # line 414:
        unless istriu(A::Array{Float64,2})::Bool goto 2
        chksquare(A::Array{Float64,2})::Int64
        return ((top(apply_type))(Triangular,Float64,typeof(A::Array{Float64,2})::Type{Array{Float64,2}},:U,false)::Type{_<:Triangular{Float64,Array{Float64,2},UpLo,IsUnit}})(A::Array{Float64,2})::Triangular{T,S<:AbstractArray{T,2},UpLo,IsUnit} \ B::Array{Float64,1}
        2:  # line 415:
        _var8 = (top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1))::Type{Array{Any,1}},$(Expr(:call1, :(top(tuple)), :Any, :Int))::(Type{Any},Type{Int64}),Array{Any,1},0,2,0)::Array{Any,1}
        _var4 = (top(arraysize))(A::Array{Float64,2},1)::Int64
        _var0 = (top(arraysize))(A::Array{Float64,2},2)::Int64
        _var5 = (top(ccall))(:jl_alloc_array_2d,$(Expr(:call1, :(top(apply_type)), :Array, Float64, 2))::Type{Array{Float64,2}},$(Expr(:call1, :(top(tuple)), :Any, :Int, :Int))::(Type{Any},Type{Int64},Type{Int64}),Array{Float64,2},0,_var4::Int64,0,_var0::Int64,0)::Array{Float64,2}
        return (top(kwcall))(call,1,:pivot,true,lufact!,_var8::Array{Any,1},copy!(_var5::Array{Float64,2},1,A::Array{Float64,2},1,(top(arraylen))(A::Array{Float64,2})::Int64)::Array{Float64,2})::LU{Float64,Array{Float64,2}} \ B::Array{Float64,1}::Array{Float64,1}
        3:  # line 417:
        return (top(kwcall))(call,1,:pivot,Float64 <: BlasFloat::Bool,qrfact,(top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1))::Type{Array{Any,1}},$(Expr(:call1, :(top(tuple)), :Any, :Int))::(Type{Any},Type{Int64}),Array{Any,1},0,2,0)::Array{Any,1},A::Array{Float64,2})::Union(QRPivoted{Float64},QRCompactWY{Float64}) \ B::Array{Float64,1}
    end)
```

### PR DESCRIPTION
**Pull request by andreasnoack**
Instead of using parameters to specify if a triangular matrix is upper, lower and/or has unit diagonal I have decided to write out the four possibilities as types as suggested some time ago by @StefanKarpinski. The four types are `UpperTriangular`, `LowerTriangular`, `UpperTriangularUnit`, `LowerTriangularUnit`, and right now I have only exported the first two as the last two are probably less used.

The main reason for this change is that the use of parameters makes it cumbersome to work with the types in a way the compiler understands because the type parameters aren't types (`:L`, `:U`, `true`, `false`). The new `Val` type would solve this, but I think it is ugly to write `Triangular(A, Val{:L})` compared to simply `LowerTriangular` and as we don't plan to extend the value beyond `:L`, `:U`, `true` and `false`, the type parameters give us nothing.

The problems with writing the old `Triangular` types in a way the compiler understands caused `\` to have inferred return type `Any` for the performance critical case where both left and right hand side has the same `BlasFloat` elements as reported in JuliaLang/LinearAlgebra.jl#152. This PR fixes JuliaLang/LinearAlgebra.jl#152 and supersedes JuliaLang/julia#9196.

cc: @jiahao

### CODE REVIEW

**Comment by tkelman** [comment]
I think I'd prefer `UnitTriangular` over `TriangularUnit`

**Comment by andreasnoack** [comment]
Yes. That is probably better.

**Comment by ViralBShah** [comment]
That does sound better.

**Comment by jiahao** [comment]
This will break a lot of packages.

Would be very helpful to create an entry in `Compat.jl` for backward compatibility.

**Comment by IainNZ** [comment]
Here are the ones that PackageEval found:
https://github.com/davidavdav/GaussianMixtures.jl/issues/6
https://github.com/JuliaStats/MultivariateStats.jl/issues/8
https://github.com/Rpedigree/Pedigrees.jl/issues/1
https://github.com/brian-j-smith/Mamba.jl/issues/22

**Comment by jiahao** [comment]
Formatting error in doc change fixed in e98b817

**Comment by davidavdav** [comment]
Yep---I'd be all for support in Compat.jl for backward compatibility.

**Comment by davidavdav** [comment]
@andreasnoack Would it make sense to export AbstractTriangular, this would make compatibility somewhat easier?  I think I can resolve the references to Triangular in NamedArrays by replacing them by AbstractTriangular. 

Now I have my own `compat.jl`
```julia
if VERSION < v"0.4.0-dev"
    typealias AbstractTriangular Triangular
else
    import Base.LinAlg.AbstractTriangular
end
```

**Pull request merged**
