### PR TITLE
add test for #14398

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by timholy** [comment]
@KristofferC, just wanted to say a big :heart: for all the work you've done testing & closing issues!

**Comment by tkelman** [comment]
should describe what the issue was about in a few more words in the commit message, it won't be obvious when looking through the git log what #14398 was

**Comment by KristofferC** [comment]
commit messaged updated

**Comment by KristofferC** [comment]
Failure is

```
Assertion failed: (jl_typeis(t,jl_simplevector_type)), function jl_svecref, file ./julia.h, line 679.
signal (6): Abort trap: 6
while loading /private/tmp/julia/share/julia/test/fft.jl, in expression starting on line 55
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 22472174 (Pool: 22371721; Big: 100453); GC: 49
Worker 9 terminated.
```

**Pull request merged**
