### PR TITLE
fix REPL completions not always being unique

### LINKED ISSUE #28692: REPL:duplicates in tab completion
```
julia> using Li<tab>
LibGit2       Libc           Libdl          LinearAlgebra  LinearAlgebra  LinearAlgebra
```

### PR DESCRIPTION
**Pull request by KristofferC**
Bug introduced in https://github.com/JuliaLang/julia/pull/26930 since completion types with the same text but different type no longer are filtered out by the `unique!` in `completions`.

I don't think the filtering should take place in `LineEdit` since other consumers (with a more rich display system than the REPL) might want to show duplicates with different types.

Gotta think of a test...

Fixes #28692 

cc @jamii

### CODE REVIEW

**Comment by jamii** [comment]
Ooops.

Seems reasonable.

**Comment by stevengj** [comment]
Does this mean that `IJulia` also has to call `unique!` since it's not happening in REPLCompletions?

**Comment by KristofferC** [comment]
Yes, if IJulia only deals with the textual representation of the completion, then that seems desirable.

**Comment by kalmarek** [comment]
The added test fails, since `test_complete` calls `completions` (which may be non-unique), but not `complete_line`:

```julia
Worker 1 failed running test REPL:
Some tests did not pass: 984 passed, 1 failed, 0 errored, 5 broken.REPL: Test Failed at /usr/share/julia/stdlib/v1.0/REPL/test/replcompletions.jl:109
  Expression: count(isequal("REPL"), c) == 1
   Evaluated: 2 == 1
Stacktrace:
 [1] record(::Test.DefaultTestSet, ::Test.Fail) at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:745
 [2] (::getfield(Main, Symbol("##42#48")))() at /usr/share/julia/test/runtests.jl:237
 [3] cd(::getfield(Main, Symbol("##42#48")), ::String) at ./file.jl:96
 [4] top-level scope at none:0

Test Summary: | Pass  Fail  Broken  Total
  Overall     |  984     1       5    990
    REPL      |  984     1       5    990
    FAILURE

The global RNG seed was 0x632e1e2db9377e27341b33d4eaeea6df.

Error in testset REPL:
Test Failed at /usr/share/julia/stdlib/v1.0/REPL/test/replcompletions.jl:109
  Expression: count(isequal("REPL"), c) == 1
   Evaluated: 2 == 1
ERROR: LoadError: Test run finished with errors
in expression starting at /usr/share/julia/test/runtests.jl:61
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2
```

**Pull request merged**
