### PR TITLE
Handle IntrinsicInst uses in allocation optimization pass

### PR DESCRIPTION
**Pull request by yuyichao**
This is needed on LLVM 5.0.

### CODE REVIEW

**Review by Keno — APPROVED** [review]

**Comment by maleadt** [comment]
This breaks my (possibly invalid) use of `pointer_from_objref`: https://github.com/JuliaGPU/CUDAdrv.jl/blob/fc18bbad0c2286cbd42b2bc8b101663b18df38c5/src/execution.jl#L81-L85

MWE:

```julia
function foo(obj)
    ptr = Base.pointer_from_objref(obj)
    println("Located at: ", ptr)
    println("Which contains: ", Base.unsafe_pointer_to_objref(ptr))

end

const obj = Ptr{Void}(1)
println("Original object: ", obj)
foo(obj)
```

Before this PR:
```
Original object: Ptr{Void} @0x0000000000000001
Located at: Ptr{Void} @0x00007fab0326a770
Which contains: Ptr{Void} @0x0000000000000001
```

But now segfaults on the `unsafe_pointer_to_objref`.
Still works interpreted, so I assume this is not intended.

**Comment by yuyichao** [comment]
This is intended. Calling `pointer_from_objref` on a `isbits` object has always been invalid.

**Comment by maleadt** [comment]
Okay, I think I can have a correct solution using `Ref` boxes. But as I need to pass an array of pointers, I'm doing `unsafe_convert(Ptr{Void}, ref)` which the GC can't track, so I assume I need the new `@gc_preserve` for that. But your pass can't handle that intrinsic, it trips up on:
```  %300 = call token (...) @llvm.julia.gc_preserve_begin(%jl_value_t addrspace(10)* %258, %jl_value_t addrspace(10)* %267, %jl_value_t addrspace(10)* %276), !dbg !162```
at
https://github.com/JuliaLang/julia/blob/809b79e76df3f87ba1383be85f9bd269a4df039c/src/llvm-alloc-opt.cpp#L452

**Comment by yuyichao** [comment]
> it trips up on:
`%300 = call token (...) @llvm.julia.gc_preserve_begin(%jl_value_t addrspace(10)* %258, %jl_value_t addrspace(10)* %267, %jl_value_t addrspace(10)* %276), !dbg !162`

..... OK, this is because Keno is lying to me ;-p..... Will fix later....

**Comment by vtjnash** [comment]
http://llvm.org/doxygen/Function_8h_source.html#l00178 😛

**Pull request merged**
