### PR TITLE
document indexed_iterate and fix destructuring / unpacking interface

### PR DESCRIPTION
**Pull request by chethega**
From a recent discussion on slack:

Sometimes people want iteration and destructuring (like `a, b = rhs` / tuple unpacking) to do different things. One of the simplest example are types that should not be iterable, but still want to support some very convenient unpacking syntax.

It is apparently not very widely known that this is possible since 0.7 by overloading `Base.indexed_iterate`. It is even less widely known that this is a questionable idea, because `indexed_iterate` is not documented / exported and can change/break at any time.

We could simply document the current `indexed_iterate`, as done by this PR.

That would make this feature better known, and retroactively bless all uses of this (currently) internal API. It can be a new feature that is already backported :)

On the flip side, we would lock in the current lowering of destructuring / unpacking / `indexed_iterate` until 2.0 (locking this in is half the point of this PR).

A simple example is:
```
struct PartionedList{T}
  x::Vector{T}
  y::Vector{T}
end

function Base.indexed_iterate(p::PartionedList, i, s = nothing)
  if i == 1
    return (p.x, nothing)
  elseif i == 2
    return (p.y, nothing)
  else
    throw(ArgumentError("PartionedList permits to destructure only up to two variables"))
  end
end
```
with use like 
```
julia> pl = PartionedList([1,2], [3])
PartionedList{Int64}([1, 2], [3])

julia> a, b = pl; a, b
([1, 2], [3])

julia> (pl...,)
ERROR: MethodError: no method matching iterate(::PartionedList{Int64})
```

### CODE REVIEW

**Comment by JeffBezanson** [comment]
No, this is not a public function and is considered an implementation detail. Overloading it is not supported, and this lowering can change. Instead, we can discuss a redesign where destructuring is handled by a new appropriately designed function that falls back to `iterate`.

**Comment by Keno** [comment]
`indexed_iterate` is an implementation detail. At no point should it's behavior be defined do anything but what `iterate` would return. Why not just:
```
function Base.iterate(p::PartionedList, i=1)
  if i == 1
    return (p.x, i+1)
  elseif i == 2
    return (p.y, i+1)
  else
    throw(ArgumentError("PartionedList permits to destructure only up to two variables"))
  end
end
```
?

**Comment by chethega** [comment]
>Why not just ...
The example on slack wanted iteration of `PartionedList` to behave like `flatten(pl.x, pl.y)`.

In the LightGraphs use (linked above), we have an `AbstractEdge` and wanted a very simple interface (implementors can do whatever they want, except overloading `indexed_iterate` in an incompatible way; and they need to implement the current interface of defining `src` and `dst` functions for their edges).

In most of my uses, I simply don't have a sensible notion of iteration, but find unpacking / destructuring syntax very convenient.

>No, this is not a public function and is considered an implementation detail.
>`indexed_iterate` is an implementation detail. At no point should it's behavior be defined do anything but what iterate would return.

That is currently true. This PR is intended to change this fact, and commit us to keeping the `indexed_iterate` lowering.

I find the current (internal / unsupported / unintended) destructuring / unpacking API perfectly acceptable. It is not a thing of beauty, because we need to carry the vestigal `state` parameter in order to permit the generic fallback to `iterate`. But I don't see a direct way around this uglyness. 

If I were to brainstorm about an entirely new API for destructuring, then the name could be more descriptive (e.g. `destructure`), and we could also pass the total number of requested destructuring. E.g. `a,b,c = rhs` could become something like
```
xs = destructure(rhs, 1, 3)
a = getfield(xs, 1)
xs = destructure(rhs, 2, 3, getfield(xs, 2))
b = getfield(xs, 1)
xs = destructure(rhs, 3, 3, getfield(xs, 2))
c = getfield(xs, 1)
```
This would permit even more flexibility: `a,b,c = rhs` and `a,b = rhs` could mean entirely different things that have nothing to do with iteration, but we would get a nice fallback. The destructuring parameters (second and third parameters in the above example) are always source-code literals (post lowering).

However, it is very alluring to have a new feature without any code, just by blessing a current implementation detail. That is more than just backwards compatible, it is retroactive backporting of the feature.

**Comment by JeffBezanson** [comment]
> That is currently true. This PR is intended to change this fact, and commit us to keeping the `indexed_iterate` lowering.

I understand that, and that's what I'm saying "no" to.

The line in your documentation saying "note that splatting doesn't use the destructuring interface" is especially interesting. (And I commend that you paid attention to that in your description!) Currently, we don't have any such inconsistency --- all of these use the iteration protocol. This is the kind of thing that would have to be discussed in a design review.

It would be great if a feature could be added just by updating documentation, but I think that's too much to hope for in this case. At the very least, the function would need to be exported and probably renamed.

> If I were to brainstorm about an entirely new API for destructuring

That's what I think we should do :)

**Comment by chethega** [comment]
Ok, let's think about the desired interface. 

I see three related things: Iteration, unpacking (`a,b=rhs`) and splatting (`f(args...)`)/`VarArg`. As a minor maybe fourth thing, function definitions `f(a, (b,c))= 0`. 

Currently, these things are considered the same in documentation and observable behavior, and we want to permit splitting of the semantics.

I see three relevant groups of interest: Users (who just want to use a package / use `a, b = rhs`). Package authors, who define the types and extend `Base.iterate` / `Base.indexed_iterate` in order to serve the users. Finally internals: We can only offer things that the runtime / compiler can support well. Obviously users and package authors (using the above definition) will often be the same individual working on the same codebase, with conflicting interests between ease-of-use and ease-of-definition for their own types.

Then, there is the issue of compatibility. This absolutely demands that unpacking and splatting both fall back to `iterate` in the 1.* timeframe. Custom unpacking / `indexed_iterate` is officially unsupported, but possible since 0.7. It would be a nice bonus if we could minimize breakage of code that illegally uses the current implementation details. First priority should be to not break semantics at points-of-use, i.e. maintain compatibility for users (e.g.: splatting uses `iterate`, not `indexed_iterate`; implicit destructuring `f(a, (b,c)) = ...` uses `indexed_iterate` and not splatting / iterate / vararg). Distant second bonus would be to not break point-of-definition, i.e. maintain compatibility for package authors. An entirely different issue is what to do at 2.0.

Scope: I have no insight on splatting, destructuring in function definition, nor on interests of the runtime/compiler. Please comment with your views.

Let's discuss the user viewpoint on unpacking. 

The `a,b,c = rhs` syntax is extremely succinct. It relieves the user from the need to remember names of getter functions (like `a = src(rhs); b= dst(rhs); c = weight(rhs);`) or even fieldnames / propertynames, like `a = rhs.src; b=rhs.dst; c=rhs.weight;` (which is potentially worse in terms of genericity). Further, it nicely mirrors positional constructors (`rhs = some_typ(a,b,c)`). The latter is extremely useful when reading code: Often, positional constructors and unpacking / field access appear close to each other in code. If both happen to share unpacking and positional constructor ordering, then it often helps the reader to infer both at a glance; e.g. if `src_, dst_, weight_ = some_instance` and `other = some_typ(a,b,c)` are close in code, it permits to guess that `a` is a source, `b` is a destination and `c` is a weight.

Note that this has nothing at all to do with iteration, except that it happens to coincide for tuples, named tuples and pairs. If unpacking is used in this way, then it can very well decouple from iteration: Example could be a custom array that also carries metadata, where iteration needs to iterate over elements and unpacking wants to split metadata from payload (the actual data array).

This use of unpacking could maybe profit from a further split in semantics: `a,b,_ = rhs` and `a,b = rhs` could give entirely different results for `a` and `b`. This mirrors constructors, where `some_typ(a, b)` and `some_typ(a, b, c)` dispatch to different methods. It is good style to have similar orderings, types and semantics for two-argument constructor and three-argument constructor, but this is sometimes impossible. If unpacking is used as a "reverse constructor", then it would be nice to permit radically different semantics of both. In other words, it would be cool if we could let `Base.indexed_iterate` know how many elements we try to unpack. Post lowering, these are all source-code literals, so const-prop should do the job and we should not need to involve dispatch / lifting to type domain (as far as I understand, this was the original point of implementing and lowering to  `Base.indexed_iterate`). 

Let's next discuss the package author viewpoint on unpacking. The interface that a package author needs to implement in order to permit users to use nice unpacking syntax is defined by lowering choices and vice versa. Currently, authors need to write something like
```
function Base.indexed_iterate(rhs::MyType, i::Int, state=nothing)
if i == 1 
  return (rhs.some_field, nothing)
elseif i == 2
#...
end
end
```
In order to maximize convenience, it would be nicer to have
```
#get field number i in unpacking-order
function Base.unpack(rhs::MyType, i::Int)
if i == 1 
  return rhs.some_field
elseif i == 2
#...
end
end
```
If we want to permit the increased flexibility of having `a,b = rhs` and `a,b,c = rhs` mean radically different things, then we could have something like
```
#get field number i/n in unpacking-order
function Base.unpack(rhs::MyType, i::Int, n::Int)
if i == 1 && n == 2
  return rhs.some_field
elseif i == 2 && n==2
#...
end
end
```
Regardless of whether we want to pass `n`, there are two issues with dropping `state`: First, it is unclear how to fall back on `iterate`, and this fallback is absolutely necessary for compatibility reasons. Second, suppose that the object `rhs` actually represents a lazy computation. That is, we defer some computation until it is unpacked. In that case, we need to stash the result somewhere between subsequent `unpack` calls, and `state` would be the perfect place for this.

If we decide against passing `n` and for keeping some `state`, then the current lowering looks close to optimal (ok, `Base.unpack_iterate` would be a nicer name). If we decide for passing `n` and for keeping some `state`, then I could imagine something like
```
function Base.unpack_iterate(rhs::MyType, i::Int, n::Int, state=nothing)
if i == 1 && n == 2
  return (rhs.some_field, nothing)
elseif i == 2 && (n == 2 || n == 3)
#...
end
end
```
Some renaming could be advisable in order to cause compile-time errors in all code that currently extends `Base.indexed_iterate`, instead of causing possibly subtle silent runtime corruptions (a real deprecation is maybe unneeded, because extending `Base.indexed_iterate` was never officially supported anyways).

For 2.0, we could consider removing the fallback of unpacking to `iterate`.

Other thoughts?

**Comment by chethega** [comment]
Bump. Any more opinions on how tuple-like destructuring should work?

**Comment by chethega** [comment]
Further example: https://github.com/JuliaDiffEq/LabelledArrays.jl 
```
julia> z = @LArray [1.,2.,3.] (a = 1:2, b = 2:3)
3-element LArray{Float64,1,Array{Float64,1},(a = 1:2, b = 2:3)}:
 1.0
 2.0
 3.0
julia> z.a
2-element view(::Array{Float64,1}, 1:2) with eltype Float64:
 1.0
 2.0
julia> a,b=z; a,b
(1.0, 2.0)
```
It would certainly be nice syntax to have `a,b = z` as shorthand for `a, b = z.a, z.b`. We cannot use `iterate` for this: `[x for x in z]` must behave like the array.

**Comment by vtjnash** [comment]
We currently don't consider this an interface.

**Pull request closed without merging**
