### PR TITLE
add bannar "?<str>" info

### LINKED ISSUE #37523: startup message could mention apropos or `?"..."` for text search
Recent discussions on Discourse suggest that not all users know about `apropos` (or equivalently, using `?"..."` for text search). The startup message currently mentions

```
Type "?" for help, "]?" for Pkg help.
```

I suggest that text search is added to this, but I am still looking for a compact way of phrasing it.

### PR DESCRIPTION
**Pull request by Moelf**
fix #37523

### CODE REVIEW

**Comment by ptoche** [comment]
Was there a problem with this suggestion? Seems like a good idea. I have used Julia for a while and didn't know this super convenient feature. I'm trying to advertise it here:

https://stackoverflow.com/questions/67527985/julias-equivalent-to-rs-double-question-mark-help-search/

**Comment by Moelf** [comment]
can we merge this maybe?

**Comment by Moelf** [comment]
gentel bump

**Comment by Moelf** [comment]
building is failing for some reason after re-base, it looks fine locally (without rebasing).

**Comment by Moelf** [comment]
>?"text", it's usually too much.

that's not how you use it, you usually use it when `?> blah` returns an empty result, 
```
help?> julian
search: julia Julia

Couldn't find julian
Perhaps you meant julia, Julia, join, union or Main
  No documentation found.

  Binding julian does not exist.

help?> "julian"
Dates.julian2datetime
Dates.datetime2julian
```

**Comment by mcabbott** [comment]
> you usually use it when ?> blah returns a completely empty result

OK, good. Perhaps this empty result would be a great place to mention this way of searching deeper, then?

**Comment by Moelf** [comment]
maybe. But when the user knows they are not searching a function name, they may just pull up browser directly. I mean to the 0-th order we don't even need `help>?` -- why not just open docs for Julia/package in the browser.

**Comment by mcabbott** [comment]
Sure. I mean the URL is the first thing provided, so searching the web is certainly one strategy.

What I'm dubious about is that trying to present 5 strategies on startup is going to improve the chance of finding one, compared to presenting 3 as it does now. 

But suggesting other paths when people are on a nearby path and it leads to a dead end, that might sometimes work. "Instructions at the point of need", as they say.

**Pull request closed without merging**
