### PR TITLE
Fix typo in docstring for significand

### PR DESCRIPTION
**Pull request by saurvs**

### CODE REVIEW

**Comment by tkelman** [comment]
Note the `Docstring generated from Julia source`. This needs to be fixed at the docstring source or it will be overwritten.

**Comment by saurvs** [comment]
@tkelman I hope this is the right file?

**Comment by tkelman** [comment]
it should be changed both places

**Comment by saurvs** [comment]
@tkelman done

**Comment by tkelman** [comment]
Thanks!

**Pull request merged**
