### PR TITLE
Fix `revise` option of `Base.runtests`

### PR DESCRIPTION
**Pull request by sostock**
https://github.com/JuliaLang/julia/pull/42358 broke the `revise=true` option of `Base.runtests`, since it replaces the depot path list by a temporary directory, so there is no depot from which `Revise` can be installed:
```
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.0
  [33e6dc65] MKL v0.4.2
  [295af30f] Revise v3.1.20

julia> Base.runtests("ranges", revise=true)
ERROR: LoadError: ArgumentError: Package Revise not found in current path.
- Run `import Pkg; Pkg.add("Revise")` to install the Revise package.
```
This PR instead prepends the temporary directory to the `DEPOT_PATH` list.

I’m not sure how to add tests for this.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
> Alternatively, we could do this:
> 
> 1. `revise=false`: empty out all existing depot path entries, and only use our temp depot.
> 2. `revise=true`: prepend our temp depot to the list of depot paths.

I think this is probably the easiest approach. Then we don't have to deal with installing Revise into our temp depot.

**Review by DilumAluthge — APPROVED** [review]

**Comment by vtjnash** [comment]
bump?

**Comment by DilumAluthge** [comment]
The plan is to implement Elliot's idea in https://github.com/JuliaLang/julia/pull/42681#issuecomment-946145259. I won't have time to do it myself. @sostock Do you want to take it on?

**Comment by sostock** [comment]
Right now I don’t have time (I would need to figure out how scratchspaces work). Maybe in a couple of weeks.

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
https://github.com/JuliaLang/julia/pull/42681#issuecomment-946145259

**Pull request closed without merging**
