### PR TITLE
remove lowercase conversions

### LINKED ISSUE #1470: int, Int, and box
I.e. write `Int(1.5)` instead of `int(1.5)`. See this thread for discussion:

https://groups.google.com/d/topic/julia-dev/gy1HlWWcxBA/discussion

### PR DESCRIPTION
**Pull request by JeffBezanson**
Fixes #1470 and #6211.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
What I discovered doing this:

- The vast majority of cases were simple conversions, `T(x)` or `convert(T,x)`
- The lowercase functions had a crazy variety of behaviors (converting, truncating, rounding, parsing, mapping over arrays). Glad to be rid of that.
- The one somewhat-useful operation that we lose is converting reals or complexes to a different precision component-wise, which `float32(z)` used to do. Is there another appropriate name for this?

**Comment by JeffBezanson** [comment]
@tkelman How do we rebuild pcre_h.jl on windows?

**Comment by tkelman** [comment]
> converting reals or complexes to a different precision component-wise, which `float32(z)` used to do

I guess `(isreal(z)?Float32:Complex64)(z)` isn't quite concise enough?

> How do we rebuild pcre_h.jl on windows?

On appveyor we grab `pcre_h.jl` out of the nightly binary, so any time you change it things will break temporarily. There's no `pcre-config` or `pcre.h` in the binaries so it's messy to regenerate. You should be able to add a `sed -i 's/int32/Int32/g' base/pcre_h.jl` roundabout line 95 of `contrib/windows/msys_build.sh`

**Comment by goretkin** [comment]
It might not be concise, but perhaps more importantly, it won't work for new number types (https://github.com/JuliaLang/julia/issues/1470#issuecomment-70293315)

**Comment by JeffBezanson** [comment]
Looks like everything is passing. I'll merge this very soon.

**Comment by quinnj** [comment]
Huzzah!

**Comment by johnmyleswhite** [comment]
:tada:

**Comment by nalimilan** [comment]
Great!

> The one somewhat-useful operation that we lose is converting reals or complexes to a different precision component-wise, which float32(z) used to do. Is there another appropriate name for this?

"components" are called "parts" when considering complex numbers, so what about something like `float_parts`, `parts2float`...? Or have a more general function like `convertparts(T, x)`?

**Comment by Mike43110** [comment]
I would have thought `change_precision(T, x)` would be appropriate?

**Comment by stevengj** [comment]
How about `round(Float32, x::Complex)`?

**Comment by JeffBezanson** [comment]
`round` is a pretty good idea. I like that so far.

**Comment by nalimilan** [comment]
Good idea.

**Comment by JeffBezanson** [comment]
I guess the problem with `round` is that it's defined to yield an integer value. Converting Float64 to Float32 is also a rounding operation though, so it's not so far off.

**Comment by StefanKarpinski** [comment]
Can't `signed(n)` and `unsigned(n)` be replaced with `convert(Signed,n)` and `convert(Unsigned,n)`?

**Comment by JeffBezanson** [comment]
The barrier to that is that there are many uses that depend on them being un-checked. I guess we could use `% Unsigned` for that.

**Comment by jiahao** [comment]
> I guess the problem with round is that it's defined to yield an integer value. 

There's also this syntax:

```
julia> round(59.43984892, 4)
59.4398
```

**Comment by JeffBezanson** [comment]
I don't think it's a good idea to give very different values for `round(T,x)` for different types T.

**Comment by StefanKarpinski** [comment]
> I guess we could use `n % Unsigned` for that.

That's a little weird, but maybe ok :-|

**Comment by quinnj** [comment]
Gotta love the number of deprecation warnings you see after this got merged!

**Pull request merged**
