### PR TITLE
Add `@logwith logger level msg ...` and friends

### PR DESCRIPTION
**Pull request by janEbert**
Add the `@logwith` macro. Comparison with `with_logger`:
```julia
with_logger(logger) do
    @info "My message" x = 0
end
@logwith logger Logging.Info "My message" x = 0
```
Also add the corresponding `@debugwith`, `@infowith`, `@warnwith` and `@errorwith` to omit the `LogLevel`.

Things I would change but do not know how to:
   - Documentation references with `@ref` did not work so they are not used (probably due to the usage of `@eval @doc`).
   - Trying to use the `@logwith` macro to generate the code for `@infowith` and so on resulted in scope errors (tested with `@sprintf` calls in `test/Logging.jl`).

This is the code I tried to re-use the @logwith macro:
```julia
macro infowith(logger, exs...) :(@logwith($(esc(logger)), Logging.Info, $(exs...))) end
```
Mapping `esc` to `exs` prior to interpolation splatting did not help as then regular values were being escaped.

### CODE REVIEW

**Comment by c42f** [comment]
Thanks, I do think we could have something like this. To avoid exporting a lot of new names from `Base`, my thought was to add another special keyword to enhance the macros we already have:

```julia
@info "Message" _logger=lg ...
@logmsg level "Message" _logger=lg ...
```

This would work analogously to the existing keywords `_group`, `_id` etc.

My motivation is that this allows the logger type to be inferred during type inference and `shouldlog` to be inlined which will greatly increase efficiency in certain cases. For example:

```julia
function tight_loop(N, logger)
    for i=1:N
        @debug "Something" _logger=logger
    end
end

tight_loop(N, current_logger())
```

Perhaps you could describe your own use case for this feature? I agree that a construct like
```julia
with_logger(logger) do
    @info "My message" x = 0
end
```
is ugly syntax but the whole idea of making the logger dynamically scoped is that most code should not be dealing with the logger itself. This is a departure from many other logging frameworks so I'd like to understand any use cases where it falls down.

**Comment by janEbert** [comment]
I love the special keyword idea as well, especially if adding more exports should be avoided. I do like that the current version is a little quicker to write, though. :)

> My motivation is that this allows the logger type to be inferred during type inference and shouldlog to be inlined which will greatly increase efficiency in certain cases. For example:

More efficiency always sounds great as well! Why is type inference not possible in the current version?

My use case is using different loggers for different events. I am training a deep neural network and want to use a [TensorBoardLogger](https://github.com/PhilipVinc/TensorBoardLogger.jl) to monitor training statistics. Other informational messages are written to a log file and printed to the terminal by the global logger, so in total I am using 3 loggers in one loop. If hope this is not just sloppy architecture on my side... :)

**Comment by c42f** [comment]
> My use case is using different loggers for different events. I am training a deep neural network and want to use a [TensorBoardLogger](https://github.com/PhilipVinc/TensorBoardLogger.jl) to monitor training statistics. Other informational messages are written to a log file and printed to the terminal by the global logger, so in total I am using 3 loggers in one loop. If hope this is not just sloppy architecture on my side... :)

Ah, very interesting — thanks for explaining. To be honest this is not how I think people "should" be using the system because it makes the decision about log record dispatch in the source code where the log events are created. This means you can't change the event dispatch by just swapping in a different logger, but you've got to edit the source code instead. It also means you have to pass your three logging contexts along with all your function calls which is probably annoying ;-)

As a more flexible and convenient alternative I'd suggest you tag the log records and install a logger backend which knows how to pick the three categories up and dispatch them to the right location.  One way to do this would be with the `_group` keyword which is set to the base name of the file by default, but can be modified:

```julia
@info data _group=:tensor
```

Then you install a logger which takes the `group` positional argument in `handle_message` and puts it into one of the three log sinks (console, file or tensorboard).

You might even find that you can already pattern match the records based on the existing metadata (module, group, id, file, type of the message, custom keywords, etc)

**Comment by c42f** [comment]
Another way of stating the above: the key idea here is to separate log event *content/structure* from *presentation/dispatch*. Content is generated with the frontend macros and presentation is the job of the logger backends. The source code which uses `@info` needs to supply enough structure for the backends to match, but other than that it shouldn't be involved in presentation.

**Comment by janEbert** [comment]
Hey, sorry for only getting back to you now. I'm very thankful for your suggestion and advice!
You were talking about something like [LoggingExtras](https://github.com/oxinabox/LoggingExtras.jl), yes? I suppose that extra dependency would fit very well into the project, given the current – as you said, annoying in the long run – passing of loggers.

Cheers! Should I close this then?

**Comment by c42f** [comment]
Hi Jan. I do think we shouldn't merge this in its current form because having these methods will encourage people to log information in a less composable way and I think the logging frontend already supports what you're trying to do in principle (as described above: you *tag* your log records with enough information to distinguish them in the backend).

The stdlib Logging backends are less flexible than desired but LoggingExtras is forging the way ahead here: I encourage you to play with it and report back! Even if it's as simple as "it worked for me, and here's the code", that can be valuable feedback. If you find that it *doesn't* work for you, knowing about what you were trying to do and the reasons the system didn't work is great too. For the frontend macros, I feel we should be pretty conservative when adding API surface area there: in contrast to the pluggable logging backends they will break a lot of things if we change behavior.

So for now I'll close this. But regardless of that I greatly appreciate the effort that went into it and your description of your use case; thanks for joining in the discussion! If you do want to improve logging in general, I suggest that the best place to innovate and submit PRs is in the logging backend packages which are available in the ecosystem: LoggingExtras / ProgressLogging / MicroLogging / etc. I'm sure will eventually get around to a big design iteration for stdlib Logging, taking in the best ideas from the ecosystem.

**Comment by janEbert** [comment]
Hey Chris, that was a really sweet closing message. :)
I understand that giving people the option to write bad code is definitely not the right way to go about new functionality.
I do think the docs should be improved in regards to external libraries as I imagine logging to both a file and `stdout` is a use case for a lot of people (I actually realized later that this exact thing is already mentioned in the TensorBoardLogger readme; whoops).

I'll definitely share the new code snippets here, or if you wish on another – perhaps more appropriate – channel. Thank you so much for taking your time reviewing and helping me write better code!

**Comment by c42f** [comment]
Well shucks :-)

The Logging docs are definitely a problem. A simple way to improve that situation would be to add a tutorial, and point to the external libraries which implement more logging backends.

Snippets are great; either that, or some links to your actual code if it's open. Feel free to post snippets here for now if you like; I think that's better than fracturing the conversation even more.

What's most interesting to me is how you're using the existing logging backends to route messages; whether that feels natural, and any workarounds or surprises you have had in the process.

**Pull request closed without merging**
