### PR TITLE
Add `filter(f, itr) = collect(Iterators.filter(f, itr))`

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #37146

### CODE REVIEW

**Comment by bramtayl** [comment]
Unrelated but maybe we could change the map method to

`map(f, iters...) = collect(Iterators.map(f, iters...))`

Another thing worth thinking about eventually is whether we need auto-collecting versions of iterators in the first place?

**Comment by mcabbott** [comment]
Aren't those identical?
```
julia> Iterators.map(sqrt, 1:10) === Base.Generator(sqrt, 1:10)
true
```

**Comment by bramtayl** [comment]
Yes, but I think `Iterators.map` is intended to be a public and overloadable interface, whereas `Base.Generator` is an internal, I think.

**Comment by mcabbott** [comment]
Bump? 

cc. @JeffBezanson since he said :+1: earlier...

**Comment by mcabbott** [comment]
October bump?

**Comment by Gyoshi** [comment]
`map` has been explicitly deprecated for Sets and Dicts (#26980):
```julia
map(f, ::AbstractDict) = error("map is not defined on dictionaries")
map(f, ::AbstractSet) = error("map is not defined on sets")
```
Maybe this should also hold for `filter`?

**Comment by JeffBezanson** [comment]
No; `map` and `filter` are different in important ways. `map` changes values, so it's less clear what it should do for structures that impose invariants on the values they hold (e.g. that they are unique). `filter` just removes some elements.

I'm not sure we should add this. I think the fallback `map` definition is kind of a misfeature. We shouldn't encourage collecting all elements into an array until it's really needed. Anyway there's no conclusion from triage posted here, so let's wait for that.

**Comment by JeffBezanson** [comment]
Nobody on triage this week seems to feel strongly positive about this.

**Pull request closed without merging**
