### PR TITLE
Clarify the description of a variable scope.

### PR DESCRIPTION
**Pull request by JonyEpsilon**
This is an ultra-nitpick, but the existing description is circular.
"Visible" in the context of the existing sentence really means, "in scope",
so the description doesn't really explain it if you don't already know
what it means. Change it to something more precise.

### CODE REVIEW

**Comment by JonyEpsilon** [comment]
This is like an exceptional level of nitpicking, but I do think the change improves the docs :-)

**Comment by Seelengrab** [comment]
What's the addition github marks around "scoping"?

**Comment by JonyEpsilon** [comment]
I think that's just indicating that "scoping" has moved to the next line (to keep the line length in check).

**Comment by Seelengrab** [comment]
Ah, I see - I thought there was maybe a new linebreak inserted by your editor, that's why I asked.

There are some other uses of `visibile` in the section about `Local Scope`, should they be clarified as well? (though there's an explanation what is meant by "visible" next to them).

**Comment by StefanKarpinski** [comment]
Doesn't accessible have the same issue as visible?

**Comment by StefanKarpinski** [comment]
My issue with "accessible" is that there are ways to access global variables and even local variables in closures other than as variables. But perhaps this is ok. Unfortunately, we can't really spell out exactly that we mean here without this turning into a massive dissertation on what scope is and how it works in general, as opposed to a reference on the details of how the standard programming language concept of lexical scope works in Julia.

**Comment by JonyEpsilon** [comment]
Yeah, agree that there's always going to be some level of didactic licence in how things are described.

My gut feeling is that "visible" is a bit jargon-y, just because its lay meaning is further from the true situation than something like "accessible" or "usable".

Definitely a matter of opinion, though, and am happy to defer to yours on this.

**Comment by brett-mahar** [comment]
Both the plain-english and the technical term can be combined into one sentence:

The *scope* of a variable is the region of code within which a variable is accessible ("visible").

**Pull request merged**
