### PR TITLE
fix repl completions on unions and Any

### LINKED ISSUE #23284: autocomplete: "type does not have a definite number of fields"
```julia
julia> code_typed(test)[1].<TAB>
```

->

```
ERROR (in the keymap): type does not have a definite number of fields
Stacktrace:
 [1] fieldcount at ./reflection.jl:457 [inlined]
 [2] fieldnames(::DataType) at ./reflection.jl:143
 [3] complete_symbol(::String, ::Base.REPLCompletions.##17#21) at ./repl/REPLCompletions.jl:74
 [4] completions(::String, ::Int64) at ./repl/REPLCompletions.jl:563
 [5] complete_line(::Base.REPL.REPLCompletionProvider, ::Base.LineEdit.PromptState) at ./repl/REPL.jl:290
 [6] complete_line(::Base.LineEdit.PromptState, ::Int64) at ./repl/LineEdit.jl:144
 [7] complete_line(::Base.LineEdit.MIState) at ./repl/LineEdit.jl:142
 [8] edit_tab(::Base.LineEdit.MIState, ::Bool, ::Bool) at ./repl/LineEdit.jl:1386
 [9] (::Base.LineEdit.##91#121)(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL, ::Vararg{Any,N} where N) at ./repl/LineEdit.jl:1412
 [10] (::Base.LineEdit.##13#14{Base.LineEdit.##91#121,String})(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL) at ./repl/LineEdit.jl:777
 [11] prompt!(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface, ::Base.LineEdit.MIState) at ./repl/LineEdit.jl:1681
 [12] run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./repl/LineEdit.jl:1641
 [13] run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./repl/REPL.jl:961
 [14] run_repl(::Base.REPL.LineEditREPL, ::Base.##533#534) at ./repl/REPL.jl:182
 [15] _start() at ./client.jl:425
```

### PR DESCRIPTION
**Pull request by KristofferC**
Fix #23284

### CODE REVIEW

**Comment by KristofferC** [comment]
The circleci test failure is weird:

```
Error in testset statistics:
Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: return type RowVector{Float64,Array{Float64,1}} does not match inferred return type Any
  Stacktrace:
   [1] abstract_call(::Any, ::Tuple{}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2285
   [2] finddoc(::Base.Docs.##9#11{String,Bool}, ::Expr) at ./docs/Docs.jl:632
  while loading /tmp/julia/share/julia/test/statistics.jl, in expression starting on line 177
ERROR: LoadError: Test run finished with errors
while loading /tmp/julia/share/julia/test/runtests.jl, in expression starting on line 29
```

Dont think it is related to this PR?

**Comment by fredrikekre** [comment]
Same error in #23341

**Comment by KristofferC** [comment]
Anyone feel like looking over this?

**Comment by StefanKarpinski** [comment]
What does it need? Does it pass tests at this point or no?

**Comment by KristofferC** [comment]
It needs review.

**Comment by StefanKarpinski** [comment]
It looks reasonable to me, but I don't really understand what it's doing, so if it fixes the problem, passes tests and doesn't seem to break things, then we can just merge it. Otherwise, you'll need to propose someone who understands this code to review it.

**Comment by rfourquet** [comment]
A bit late, but LGTM, thanks!

**Pull request merged**
