### PR TITLE
Use mbedtls instead of openssl in libgit2 on Linux

### LINKED ISSUE #10763: Possible licensing issue with openssl?
Inspired by https://github.com/JuliaWeb/Roadmap/issues/5#issuecomment-84493845, I wanted to check here. Since Julia uses libgit2, which is in turn built using OpenSSL, are we OK with using OpenSSL derivatives elsewhere within Julia or are there licensing issues with the dual-licensed OpenSSL stuff?

If there _are_ licensing issues associated with the use of OpenSSL in Julia, does Julia's reliance on libgit2 (and libgit2's reliance on OpenSSL) pose any problem?

(Bottom line: I'd love to be able to use OpenSSL within Julia without having to worry about license restrictions / violations. IANAL. Please tell me how to do this.)

### LINKED ISSUE #17471: Julia TLS stream implementation for LibGit2
In order to avoid OpenSSL dependency (https://github.com/JuliaLang/julia/issues/10763) in `libgit2`, custom TLS stream framework should be utilized to construct streams with different TLS library.

Required:
- [x] Native TLS stream implementation based on MbedTLS.jl: https://github.com/wildart/MbedTLSStream.jl
- [ ] remove OpenSSL dependency while building `libgit2` for Linux
 - `-DUSE_OPENSSL=OFF`
 - Enable https transport for custom TLS streams in `libgit2`, see https://github.com/libgit2/libgit2/pull/3850 
- [ ] Initialization of custom TLS stream in `LibGit2` module
- [ ] MbedTLS.jl should use on `libmbed*` from julia build, see https://github.com/JuliaWeb/MbedTLS.jl/issues/54
- [ ] Proxy support

Refs: https://github.com/JuliaLang/julia/pull/17246, https://github.com/JuliaWeb/MbedTLS.jl

### PR DESCRIPTION
**Pull request by tkelman**
This carries the patch from https://github.com/libgit2/libgit2/pull/3462 in order to fix #10763, and close #17471. It seems libgit2 maintainers are reluctant to merge this patch upstream, but maybe we can change their mind eventually. This is a much more maintainable approach than re-implementing a pure Julia TLS stack which is what #17471 was suggesting, and no one is actively working on right now.

Would only be backported to release-0.5 after being tested on master for some time. It fixes an as-yet-unreported issue with our generic Linux binaries where our bundled copy of libgit2 links against libgssapi_krb5.so.2 and a bunch of other things that we don't ship. We've just been getting lucky that most Linux systems happen to have those same libraries installed already. The issue is reproducible if you try to download and run the generic Linux binaries in an Ubuntu docker container that has installed wget and nothing else beyond the base image. Dropping our use of openssl from the build system should fix that, and it's an improvement in several other ways. Since the buildbots run on a very old CentOS, their copy of openssl is old and heavily patched.

Assigning @Keno for review.

### CODE REVIEW

**Comment by tkelman** [comment]
There is an alternate way to fix the linking-to-things-we-don't-ship issue by calling `patchelf --remove-needed` on those binaries (and verify that it doesn't break https support), but this wound up easier to do.

**Comment by kshyatt** [comment]
Is this good to go?

**Review by Keno — COMMENTED** [review]
Fine with me. I'll work on getting the upstream review continued.

**Review by Keno — APPROVED** [review]

**Comment by tkelman** [comment]
Thanks Keno. We're already carrying the libssh2 patch that was stalled, this libgit2 patch is now reopened upstream as https://github.com/libgit2/libgit2/pull/3935.

**Comment by Keno** [comment]
Right, too many things at once ;).

**Comment by tkelman** [comment]
probably won't backport this until 0.5.2 or later, but should be done along with https://github.com/JuliaLang/julia/pull/18936 if that turns out to solve the remaining issues

**Pull request merged**
