### PR TITLE
combinatorics coverage

### PR DESCRIPTION
**Pull request by Ismael-VC**
:feelsgood: I just screwed it up again, when trying to squash accidentaly merged something else, continues #11778 I didn't know how to fix it so I did the PR again, sorry for the inconveniences.

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Why does this [lines][1] are not exercised even when this [tests][2] are defined and CI is run on both 32 and 64 bits architectures?

[1]: https://coveralls.io/builds/2863074/source?filename=base%2Fcombinatorics.jl#L40
[2]: https://github.com/JuliaLang/julia/blob/master/test/combinatorics.jl#L87-90

**Comment by tkelman** [comment]
The numbers that go to coveralls don't come from the same CI that tests PR's, they come from a separate 64 bit Ubuntu buildbot.

**Comment by Ismael-VC** [comment]
All right then. Travis tests are passing, only AV is left. I'll keep looking for chances to make more tests.

**Comment by Ismael-VC** [comment]
@tkelman couldn't we add something like [this][1] to the `.travis.yml`, `script` and `after_success` options, so we can have 32 bit coverage also?

[1]: https://github.com/Ismael-VC/HydrocarbonNets.jl/blob/master/.travis.yml#L22-26

**Comment by Ismael-VC** [comment]
Is there any documentation on how this build bots work?

**Comment by tkelman** [comment]
See the first post at #9493. The buildbot configuration lives at https://github.com/staticfloat/julia-buildbot and you can see the setup at http://buildbot.e.ip.saba.us:8010/builders. For measuring base coverage numbers, you have to do some custom configuration, run without inlining, and other modifications that are probably too slow to run on every travis build.

**Comment by Ismael-VC** [comment]
Thank you very much for all your help!

**Comment by tkelman** [comment]
No problem, test additions are great and always welcome. Thanks!

**Pull request merged**
