### PR TITLE
Fix line numbers in doctests

### PR DESCRIPTION
**Pull request by tkelman**
and run contrib/add_license_to_files.jl

keeping `make release-candidate` passing

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
👍

**Review by Sacha0 — APPROVED** [review]

**Comment by tkelman** [comment]
Sorry to append-after-review on you guys, added in what should be a no-functional-change style thing (not skipped).

**Review by Sacha0 — APPROVED** [review]
lgtm for the additional commit! :)

**Review by ararslan — APPROVED** [review]
Still 👍

**Pull request merged**
