### PR TITLE
Even more math tests, and a missing besselhx export

### PR DESCRIPTION
**Pull request by kshyatt**
`besselhx` wasn't exported from `Base.Math`. I've fixed that and added some more tests for it and a few other Bessel functions. I also fixed some bad `symmetric.jl` tests I wrote and added the last two missing tests for `UniformScaling`.

### CODE REVIEW

**Comment by pao** [comment]
cf #8536 and https://github.com/nolta/SpecialFunctions.jl

**Comment by kshyatt** [comment]
@pao Has a decision on that issue been reached? If the plan is to strip the special functions pretty soon I'd be happy to remove that commit from this PR.

**Comment by tkelman** [comment]
Probably not prior to 0.4 unless someone feels motivated enough to go and do it. This is just one thing among many that can be moved out to a package (and here also translated from Fortran to pure-Julia code) as part of #5155.

**Comment by pao** [comment]
I mention it more so there's a breadcrumb if that gets picked back up. A more salient reminder that it will need a resync.

**Comment by kshyatt** [comment]
Ah, ok, thanks :). This look ok to folks?

**Pull request merged**
