### PR TITLE
Bump Pkg3

### PR DESCRIPTION
**Pull request by KristofferC**
* Add credential handling to Pkg3's git functionality (thanks to @omus).
* Add a progress-bar for cloning repos, thanks @omus for the groundwork that made this feature possible (https://github.com/JuliaLang/julia/pull/26437):

apr-04-2018 15-08-29

* Show in the Pkg3 prompt the name of the current project (also shown in gif above). Some users have been a bit confused about what their current project is, this should make that more explicit.

### CODE REVIEW

**Comment by iblis17** [comment]
I saw it on recent master build. It only happened on one of worker. I'm going to detach it and check.

**Comment by iblis17** [comment]
@ararslan found a way to reproduce
```shell
$ touch /tmp/test.magic
$ gmake -C test REPL
```

That test case is somewhat ... fragile.
Will sent a PR later.

**Comment by StefanKarpinski** [comment]
@iblis17: is the test case relevant to this PR or can I go ahead and merge this?

**Comment by StefanKarpinski** [comment]
Also, @KristofferC, is this good to go from your perspective?

**Comment by KristofferC** [comment]
Looks like there are some `cfunction` deprecations so hold off with merging a bit.

**Comment by iblis17** [comment]
> Is the test case relevant to this PR or can I go ahead and merge this?

That test case is irrelevant, but no idea why only BSD CI failed.

**Pull request merged**
