### PR TITLE
minor tweak: OSX --> OS X

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should have probably had a [ci skip]

**Comment by waldyrious** [comment]
Sorry about that :/ I suppose changing the title now doesn't do any good, does it?

**Comment by tkelman** [comment]
no, it would have to be in the commit message. or someone can manually go in and cancel. at least the backlog isn't as bad today as it was earlier this week.

**Comment by tkelman** [comment]
Oh, this was on release-0.4. Please open future PR's against master first.

**Comment by waldyrious** [comment]
huh, that's really strange. I normally just navigate to the document and edit, assuming master is the default branch. I don't know what happened this time, sorry about that. I'll be more attentive next time.

**Pull request merged**
