### PR TITLE
Testsets for numbers

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by kshyatt** [comment]
I think I managed to screw something up in this 3000+ line file...

**Comment by fredrikekre** [comment]
Looks correct to me. The failure is weird though:
```
Test Failed
 Expression: fld(0.3, 0.01) == 29.0
  Evaluated: 30.0 == 29.0
```

**Comment by fredrikekre** [comment]
Reduced to the following:
```julia
@testset begin
    @test fld(0.3,0.01) == 29.0
    @test div(0.3,0.01) == 29.0
end
```
The above two tests fail while inside a `@testset`:
```julia
julia> @testset begin
           @test fld(0.3,0.01) == 29.0
           @test div(0.3,0.01) == 29.0
       end
test set: Test Failed
  Expression: fld(0.3, 0.01) == 29.0
   Evaluated: 30.0 == 29.0
Stacktrace:
 [1] macro expansion at ./REPL[2]:2 [inlined]
 [2] macro expansion at ./test.jl:942 [inlined]
 [3] anonymous at ./<missing>:?
test set: Test Failed
  Expression: div(0.3, 0.01) == 29.0
   Evaluated: 30.0 == 29.0
Stacktrace:
 [1] macro expansion at ./REPL[2]:3 [inlined]
 [2] macro expansion at ./test.jl:942 [inlined]
 [3] anonymous at ./<missing>:?
Test Summary: | Fail  Total
test set      |    2      2
ERROR: Some tests did not pass: 0 passed, 2 failed, 0 errored, 0 broken.
```

Without the testset they pass just fine:
```julia
julia> @test fld(0.3,0.01) == 29.
Test Passed

julia> @test div(0.3,0.01) == 29.0
Test Passed
```

**Comment by kshyatt** [comment]
lol wut

**Review by fredrikekre — APPROVED** [review]

**Comment by fredrikekre** [comment]
Fun fact: Adding the testsets in this file increased runtime with 14%, from 70 to 80 seconds.

**Comment by fredrikekre** [comment]
#23796 × 2 and also an (unrelated?) failure in ranges on circle CI i686:
```
    FAILURE
Error in testset ranges:
Test Failed
  Expression: cmp_sn2(Tw(xw / yw), astuple(x / y)..., slopbits)

ERROR: LoadError: Test run finished with errors
in expression starting at /tmp/julia/share/julia/test/runtests.jl:29
```
What's up with that?

**Comment by fredrikekre** [comment]
Circle CI does not restart when closing/opening PRs? Relevant tests passed anyway.

**Pull request merged**
