### PR TITLE
`hvncat`: Ensure output ndims are >= the ndims of input arrays

### PR DESCRIPTION
**Pull request by BioTurboNick**
Breaking down #41143 into smaller pieces.

This PR ensures the output ndims are at least as large as the ndims of the input arrays.

The max `nd` calculation caused allocations to blow up when I had it in the same method as the remaining code. Removing it to a separate method fixed that.

### CODE REVIEW

**Comment by BioTurboNick** [comment]
This PR should probably have the 1.7 backport label too? @KristofferC @simeonschaub @JeffBezanson

**Comment by vtjnash** [comment]
needs rebase now

**Review by simeonschaub — APPROVED** [review]
LGTM. Sorry for the delay!

**Comment by BioTurboNick** [comment]
No worries, the delay was necessary to make sure it would merge correctly

**Pull request merged**
