### PR TITLE
bump utf8proc to v1.3

### PR DESCRIPTION
**Pull request by stevengj**
This gives us support for Unicode 8.

(Compared to Julia 0.3, this means we are jumping 3 Unicode versions.)

### CODE REVIEW

**Comment by stevengj** [comment]
If there are no objections, I'll go ahead and merge this later today or tomorrow.

cc: @nalimilan, @jiahao

**Comment by nalimilan** [comment]
Yes, that's fine with me.

**Comment by jiahao** [comment]
Should be fine.

**Comment by tkelman** [comment]
This is missing checksums for `NO_GIT` builds, I'll add them

**Comment by stevengj** [comment]
Where do those go?

**Comment by tkelman** [comment]
`deps/checksums` - they're autogenerated if you do `make NO_GIT=1 -C deps get-utf8proc`, anyone else who builds with `NO_GIT` (including travis) will get a warning if the checksum files aren't committed, though that warning's pretty easy to miss

**Pull request merged**
