### PR TITLE
deprecate `broadcast_function` and `broadcast!_function`

### LINKED ISSUE #16601: do we need `broadcast_function`?
I came across this looking for exports to remove. It just does `(As...) -> broadcast(f, As...)`, so I'm not sure we need an exported function for this. Is this widely used?

### PR DESCRIPTION
**Pull request by JeffBezanson**
closes #16601

### CODE REVIEW

**Comment by tkelman** [comment]
Do you use ack or something configured in a way that skips contrib?

**Comment by JeffBezanson** [comment]
Yes. Also I don't think it makes sense for an editor mode to contain a list of Base exports. Can we remove them so we don't have to keep "maintaining" the list? Only this one editor mode has the list, none of the others do AFAIK. I don't think there is a good reason to color those functions differently. They also seem to be classified as "keywords" along with actual keywords like for, while, etc. so I would say the file is just wrong.

**Comment by StefanKarpinski** [comment]
I agree with getting rid of the export lists in various editor modes – functions are just functions. For what it's worth, a good way to search for a pattern in the whole project is

```sh
git ls-files [<dirs>...] | xargs ack <pattern>
```

**Comment by tkelman** [comment]
@cormullion seems to be the main author (and presumably, user?) of that file, so ask him? I would of course prefer if these things were all completely autogenerated, and hosted in external repos (JuliaEditorSupport org?). The other editor support files that are still in contrib have lists of some types and functions, but not all exports like that one.

**Comment by JeffBezanson** [comment]
The fact that Base functions are in the same category as `if`, `while` etc. in that file definitely seems like a bug to me.

**Comment by cormullion** [comment]
I confess and hang my head in a modest amount of shame: I did stick everything into that BBEdit plist file... More recently I've been using Vim and Atom, and I wasn't intending to keep updating the BBEdit plist file for every future release or writing a script to generate one either. I'd support you removing it now, and if anyone wants to hack on a copy they can shout on the discussion forums...

**Comment by tkelman** [comment]
Thanks for responding. Will give people a bit of time to speak up at https://groups.google.com/forum/?nomobile=true#!topic/julia-users/sQ5Atvjicxw, we'll either delete it or move it to its own repo.

**Pull request merged**
