### PR TITLE
Use CPPFLAGS and CXXFLAGS when calling CXXLD

### LINKED ISSUE #10212: CXXFLAGS not used in src/ and ui/
I noticed that `CXXFLAGS` has no effect when building C++ files under `src/` and `ui/` (at least). For example in the following log, the Fedora standard `CXXFLAGS` that are set when calling `make` are not used at all for the last calls to `g++` that fail (at the bottom of the file):

https://gist.github.com/nalimilan/4cf029bcfec741015019

(Noticed when trying to add `std=c++11` for https://github.com/JuliaLang/julia/issues/10201)

### PR DESCRIPTION
**Pull request by nalimilan**
Closes #10212.

### CODE REVIEW

**Comment by Keno** [comment]
I'm not sure about this. `CPPFLAGS` is for the preprocessor which shouldn't not be used during linking. Also, I seem to remember that there was some reason you did not want to in general include `CXXFLAGS` in `CXXLDFLAGS`, but I do not remember what it was, so I guess I'm not objecting to having that (and if I run into a case where this is a problem, I'll adjust and write appropriate comments).

**Comment by nalimilan** [comment]
@Keno I have no idea, but I think we should use `CXXFLAGS` so that when building distribution packages, the compilation flags chosen by the distribution are always followed. I added `CPPFLAGS` after @stevengj's comment: https://github.com/JuliaLang/julia/issues/10212#issuecomment-75101323

**Comment by stevengj** [comment]
@nalimilan, I take it back, the automake scripts do not include `CPPFLAGS` either; @Keno is right in that there is not much point in that.  automake uses (omitting automake/libtools-specific stuff) `$(CCLD) $(CFLAGS) $(LDFLAGS) -o $@`

**Comment by nalimilan** [comment]
OK, makes sense. I've updated the PR.

**Pull request merged**
