### PR TITLE
Remove method that produces error for prod(AbstractArray{Bool}). 

### LINKED ISSUE #14657: det(reshape([true],1,1)) ==> ERROR: use all() instead of prod()
```julia
# and also for other boolean matrices
julia> det(reshape([true,false,false,true],2,2))
ERROR: use all() instead of prod() for boolean arrays
 in det at linalg/generic.jl:512
```

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #14657

### CODE REVIEW

**Comment by tkelman** [comment]
could use a more direct test of this signature, particularly its return type

**Comment by andreasnoack** [comment]
Do you mean something like `prod([true,true,true])===true`?

**Comment by tkelman** [comment]
right. the bitunpack test would work if you check the return type.

I think this is borderline for backporting, it would be really easy to write code that doesn't work on early 0.4.x versions with this change.

**Comment by andreasnoack** [comment]
I've put the modified test back
>  it would be really easy to write code that doesn't work on early 0.4.x versions with this change.

Isn't that true for most bug fixes? Feel free to do what you think is best.

**Comment by tkelman** [comment]
Yes, but what I want to avoid is having `Pkg.update()` break users' code. So package authors need to be very careful with REQUIRE any time they add code that would fail on existing 0.4.x releases. Ideally packages would test against earlier point releases in addition to the latest. Upgrading julia between point releases is intended to be non breaking and easy to do, but might not always be under the user's control.

**Pull request merged**
