### PR TITLE
WIP: LibGit2 support for Git credential helpers

### PR DESCRIPTION
**Pull request by omus**
Refactored the LibGit2 credential callback to add support for [Git credential helpers](https://git-scm.com/docs/gitcredentials). Since the credential callback code was mostly untested I also wrote tests for this code and fixed several issues that were discovered by the new tests. Changes include:

- Support LibGit2 configuration iterators
- Use LibGit2 callback payload to keep track of state
- Add Git credential helper support to HTTPS authentication
- Avoid sending invalid credentials multiple times to remote servers
- Support use of EOF character (`^D`) to abort credential prompt
- Limit amount of re-prompts
- Revise when cached credentials are accepted or rejected
- Testing framework which automates credential prompt responses and does not require external servers 

Additional work to do:

- [x] ~~Make tests compatible with Windows~~ Disable tests for Windows
- [ ] Disable git credential helper tests on systems where command-line `git` isn't installed
- [ ] Add more tests for credential approval/rejection
- [ ] Add more git credential tests
- [ ] Document credential prompt abort using `^D`

### CODE REVIEW

**Comment by ararslan** [comment]
Is this actually release blocking for 0.6? If not, 1.0 might be the more appropriate milestone. (cc @tkelman)

**Comment by omus** [comment]
I can see the argument for not having this be blocking for 0.6. However, this work does include numerous fixes and tests I would like to see included in a 0.6 release.

Additionally, I require the git credential helper feature for running a GitLab CI with support private package dependencies.

**Comment by tkelman** [comment]
If the git credential helper relies on command-line git, then I don't think it should live in base. Can you separate the fixes, tests, and features here? This is a pretty big PR to be opening as we're basically one build-fix away from feature freeze.

**Comment by omus** [comment]
I broke up the PR into smaller commits. Unfortunately GitHub isn't showing the commits in the right order. Here's a listing in the correct order:

1. [Improve scp-like syntax parsing (1f3b39b)](https://github.com/JuliaLang/julia/pull/20725/commits/1f3b39b0d6994c7feba6c9131f4e7376e16fcd1e) (bugfix)
2. [Refactored LibGit2 credential callback (6ea2a68)](https://github.com/JuliaLang/julia/pull/20725/commits/6ea2a681ec2e55d84d9e4e72c958f14cced3bbbc) (bugfix)
3. [Limit amount of re-prompts (73dc088)](https://github.com/JuliaLang/julia/pull/20725/commits/73dc088483066ba761a3864d8499dbbe79d5d86b) (feature)
4. [Use of EOF character (`^D`) to abort cred prompt (c661d60)](https://github.com/JuliaLang/julia/pull/20725/commits/c661d60e0aff060202f1c4b52fc332cec077d7ce) (feature)
5. [Add LibGit2 support for config iterator (a462aeb)](https://github.com/JuliaLang/julia/pull/20725/commits/a462aeb8dfe7a1bf7c25fe58c77f957ef55003c1) (git credential helper)
6. [Add GitConfig into RemotePayload (4ac043d)](https://github.com/JuliaLang/julia/pull/20725/commits/4ac043d3eb00cf08e3b2d09e515d54a73574ab38) (git credential helper)
7. [Add framework for Git credential helper support (409bb3b)](https://github.com/JuliaLang/julia/pull/20725/commits/409bb3bd00b55a356bddfd782c88dec2897e34de) (git credential helper)
8. [Add Git credential helper support for HTTPS (b0bf68d)](https://github.com/JuliaLang/julia/pull/20725/commits/b0bf68d8322d990125e1e56e3fb5a155e5ba64e2) (git credential helper)

**Comment by omus** [comment]
I'll be breaking this PR up into multiple PRs to make things faster and easier to review.

**Comment by omus** [comment]
Removing 0.6.0 milestone as this is no longer critical. Details in #20769

**Comment by omus** [comment]
With the merger of #23824 this PR can now be retired.

**Pull request closed without merging**
