### PR TITLE
make skipping stdlib tests work

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/26692

Development rates can go back to their normal levels.

### CODE REVIEW

**Comment by mbauman** [comment]
Nice. Does this also mean we can `--skip LinearAlgebra/triangular`?

**Comment by KristofferC** [comment]
You can now :)

**Comment by KristofferC** [comment]
Have we seen

```
Error in testset ambiguous:
Test Failed at C:\projects\julia\julia-6f3ea55604\share\julia\test\ambiguous.jl:153
  Expression: detect_ambiguities(Core, Base; imported=true, recursive=true, ambiguous_bottom=false) == []
   Evaluated: Tuple{Method,Method}[((::Type{Main.TestHelpers.Furlong})(x::T) where T<:Number in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:13, (::Type{T})(x::Main.TestHelpers.Furlong) where T<:Number in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:14), ((::Type{Main.TestHelpers.Furlong{p,T}})(v::Number) where {p, T} in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:10, (::Type{T})(x::Main.TestHelpers.Furlong) where T<:Number in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:14), ((::Type{T})(x::Main.TestHelpers.Furlong) where T<:Number in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:14, (::Type{Main.TestHelpers.Furlong{p,T} where T<:Number})(v::Number) where p in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:15), (//(x::Main.TestHelpers.Furlong{p,T} where T<:Number, y::S) where {p, S<:Number} in Main.TestHelpers at C:\projects\julia\julia-6f3ea55604\bin\..\share\julia\test\dimensionful.jl:67, //(x::Number, y::Complex) in Base at rational.jl:57)] == Any[]
ERROR: LoadError: Test run finished with errors
in expression starting at C:\projects\julia\julia-6f3ea55604\share\julia\test\runtests.jl:59
```

before (AV)?

**Comment by JeffBezanson** [comment]
I would tweak the PR to continue to put the ambiguity tests first.

**Comment by KristofferC** [comment]
Ok, now LinearAlgebra went crazy...

```
Worker 9 failed running test LinearAlgebra/dense:
Some tests did not pass: 6977 passed, 0 failed, 132 errored, 2 broken.LinearAlgebra/dense: Error During Test at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/LinearAlgebra/test/dense.jl:25
  Test threw exception ErrorException("1")
  Expression: ≈(cond(a, 1), 483.7320054554436, atol=0.01)
  1
  Stacktrace:
   [1] Type at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/test/errorshow.jl:325 [inlined]
   [2] eval_test(::Expr, ::Expr, ::LineNumberNode) at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/Test/src/Test.jl:254
   [3] macro expansion at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/LinearAlgebra/test/dense.jl:25 [inlined]
   [4] macro expansion at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/Test/src/Test.jl:1095 [inlined]
   [5] macro expansion at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/LinearAlgebra/test/dense.jl:22 [inlined]
   [6] macro expansion at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/Test/src/Test.jl:1022 [inlined]
   [7] top-level scope at /usr/home/julia/julia-fbsd-buildbot/worker/11rel-amd64/build/usr/share/julia/site/v0.7/LinearAlgebra/test/dense.jl:21
```

```
Test threw exception ErrorException("1")
```

what does that even mean?

**Comment by KristofferC** [comment]
@vtjnash, how should we update the

```
Base.Symbol() = throw(ErrorException("1")) 
```

test? Just put some other struct that errors on creation?

**Comment by KristofferC** [comment]
Ok, I updated `Symbol` -> `String`. This still feels a bit "iffy" but shouldn't be worse than before.

**Comment by vtjnash** [comment]
Empty symbol should be `Symbol("")`. Anyways, LGTM. The errorshow logic is demonstrating that it doesn't break on builtin objects with special representations.

**Comment by KristofferC** [comment]
Well, `Symbol()` works and gives the same as `Symbol("")` so, in that case, we should deprecate `Symbol()`.

**Pull request merged**
