### PR TITLE
Remove `DArray`'s from Base

### LINKED ISSUE #10333: Move DArrays from Base
We need a ton of functionality to be developed on DArrays, and perhaps even experimentation with layouts and such. I feel it is best to move the DArray functionality out of Base into the JuliaParallel organization (https://github.com/JuliaParallel) and develop it there.

### PR DESCRIPTION
**Pull request by jakebolewski**
It has been suggested that `DArray`'s should be developed as an external package under the [JuliaParalllel](https://github.com/JuliaParallel) organization. (See https://github.com/JuliaParallel/DistributedArrays.jl)

Closes #10333.

cc @ViralBShah

### CODE REVIEW

**Comment by ivarne** [comment]
Great!

If we do more of this, we'll have less discussion about backporting fixes/improvements to libraries that doesn't really need to follow the slow release schedule of Base.

**Comment by tkelman** [comment]
Please don't make packages 0.4-only when they consist of removed functionality from base. Make them importable on both 0.3 and 0.4, but for 0.3 they should be a stub that just re-exports base functionality.

**Comment by samtkaplan** [comment]
In the Julia documentation, the section on parallel computing references the Julia documentation on distributed arrays. In particular, the sentence:

"Fortunately, distributed arrays can be used to get around this limitation, as we will see in the next section."

will need to be replaced by something like

"Fortunately, distributed arrays can be used to get around this limitation (see the DistributedArrays.jl package)."

I didn't see this change in the commits for this pull request.  Apologies if I missed it.  Here's a screen-grab from the docs:
image

**Comment by ViralBShah** [comment]
Looks good.

**Comment by tkelman** [comment]
What's with the rush here? The package is not yet fully functional or tested, would have been considerably less disruptive to provide a usable (on both 0.3 and 0.4) replacement before merging this.

**Comment by timholy** [comment]
I can't comment about the DArray removal, but I'd characterize the Base.Graphics removal as mildly painful; even after several weeks we're still encountering issues here and there. Just a +1 for making sure these removals are done very carefully.

**Pull request merged**
