### PR TITLE
Revert "Fix #38256 (lpad/rpad defined in terms of textwidth)"

### LINKED ISSUE #38256: Should lpad/rpad be defined in terms of textwidth instead of code units or have the option to do so?
One of the main use cases of `lpad` and `rpad` is, at least for me personally, to align things in the terminal. However, `lpad` and `rpad` are defined (and documented) to work in terms of code units (i.e. they call `length` on the input string) which means that when `length` and `textwidth` disagree, you get unaligned output:

```
julia> s1 = "⟨k|H₁|k̃⟩"
"⟨k|H₁|k̃⟩"
julia> s2 = "⟨k|H₁|k⟩"
"⟨k|H₁|k⟩"
julia> textwidth(s1), textwidth(s2)
(8, 8)
julia> rpad(s1, 12) |> textwidth
11
julia> rpad(s2, 12) |> textwidth
12
```

This can cause bugs like https://github.com/KristofferC/TimerOutputs.jl/issues/94.

Two points of discussions:

- Should the default be changed to use `textwidth` instead of `length`? Perhaps too much of a breaking change.
- Should there be an option to use `textwidth`, e.g. with a kwarg?

### PR DESCRIPTION
**Pull request by DilumAluthge**
Reverts JuliaLang/julia#39044

Let's see if CI passes on this PR.

### CODE REVIEW

**Comment by stevengj** [comment]
I thought #39044 was passing when it was merged?

**Comment by KristofferC** [comment]
There is a big CI queue and the status checks don't show up until CI has started. So it is easy to merge things before CI has even started running on some platforms.

**Comment by DilumAluthge** [comment]
Once we have moved everything to Buildkite, this will be less of an issue. Buildkite creates a pending (yellow) status as soon as a PR is created/updated, and it stays yellow until all checks have completed.

**Comment by DilumAluthge** [comment]
Also, this might have been a "semantic conflict", maybe?

That is, maybe the breakage only happens with the combination of both https://github.com/JuliaLang/julia/pull/39044 and a Tar version bump (e.g. https://github.com/JuliaLang/julia/pull/41093)?

**Comment by stevengj** [comment]
Yes, it looks like it was broken by https://github.com/JuliaIO/Tar.jl/commit/cbcb00b7b33c87792ab35b8325d14ee635d26581

I have an alternative fix #41133 that should hopefully fix that and similar breakage.

**Comment by DilumAluthge** [comment]
Nice! Yeah I'd rather we merge https://github.com/JuliaLang/julia/pull/41133 than this PR.

**Pull request closed without merging**
