### PR TITLE
extend sparse map[!]/broadcast[!] to structured matrices

### PR DESCRIPTION
**Pull request by Sacha0**
(Requires #19724, to which the first four commits belong.) This pull request extends sparse `broadcast[!]` to structured matrices by promoting structured matrices to sparse where appropriate. (For better future performance, handling structured matrices directly in the underlying sparse `broadcast[!]` routines might be possible.) Best!

### CODE REVIEW

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by tkelman** [comment]
tests should probably verify the output type? pretty small amount of additional code, that's encouraging.

**Comment by Sacha0** [comment]
> tests should probably verify the output type?

Good call. Output type checks added to the `broadcast` tests. Thanks!

**Comment by Sacha0** [comment]
On that note, in the sparse `broadcast[!]` tests I intended full equality to check both numerical and structural equality, but I now see that [sparse full equality only ascertains numerical equality](https://github.com/JuliaLang/julia/blob/e55cdeae485097f59344338f8ff01d4f5b4b1f19/base/sparse/sparsematrix.jl#L1417). Have we a stronger sparse equality that checks both numerical and structural equality? If not, perhaps we should add one, at least for testing these routines? Thanks!

**Comment by tkelman** [comment]
don't think we have one, but it would make sense to check for testing

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19926#issuecomment-271123194) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/94ea4ceed3e2ce2fdb30bb11bfa72f2677e97d32/f57c8a3_vs_e55cdea/report.md). cc @jrevels

**Comment by Sacha0** [comment]
Added a commit extending sparse `map[!]` to structured matrices as well. Best!

**Comment by Sacha0** [comment]
Rebased out the commits from #19724. Absent objections, requests for time, or someone else merging this PR prior, I plan to merge on Wednesday morning PST. Best!

**Comment by Sacha0** [comment]
With the additional commit:

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19926#issuecomment-271387555) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/391780bf5dc66b5d5310c69fa3ef8c21933558ed/cb8874c_vs_13da0b9/report.md). cc @jrevels

**Comment by Sacha0** [comment]
Fixed rebase conflict resolution mistakes. Not certain whether those mistakes could have caused the strange nanosoldier results. (The benchmarks that regressed / improved cover unrelated functionality.) Will rerun nanosoldier if / when Travis and AppVeyor approve. Best!

**Comment by Sacha0** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19926#issuecomment-271497981) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/aabef39ac0b7df6f0ed673750e87f1fa23484989/74becf0_vs_6b1b4f6/report.md). cc @jrevels

**Pull request merged**
