### PR TITLE
Improve `jl_print_task_backtraces()`

### PR DESCRIPTION
**Pull request by kpamnany**
We use `jl_rec_backtrace()` which tries to set the task's tid to the current thread before gathering the backtrace. This will fail for tasks that are sticky to another thread as their tid is never reset. However, for `jl_print_task_backtraces()`, we aren't concerned about thread safety since we assume that all threads are stopped so we add a flag to `jl_rec_backtrace()` to ignore the task's tid.

With this, `jl_print_task_backtraces()` should now only miss tasks that are currently executing on threads other than the calling thread.

### CODE REVIEW

**Comment by vtjnash** [comment]
> However, for jl_print_task_backtraces(), we aren't concerned about thread safety since we assume that all threads are stopped

Why? They are almost never stopped when this code is running. Particularly in GDB, we should assume all threads are running, since that is the default.

**Comment by vtjnash** [comment]
With `set scheduler-locking on` this code might deadlock and cause gdb to fail, though you can potentially notice in advance that one of the threads is currently holding one of the required locks and decide not to call the function

**Comment by kpamnany** [comment]
> With `set scheduler-locking on` this code might deadlock and cause gdb to fail, though you can potentially notice in advance that one of the threads is currently holding one of the required locks and decide not to call the function

Which required locks? I see `jl_in_stackwalk`; any others?

We use this `jl_print_task_backtraces()` call when our server process freezes and we're about to kill it. The idea is to try to spot any deadlocks that might have caused that freeze. If some task stacks are missing (as they are), then that makes this capability not very useful.

Completely open to any suggestions for improvement.

> Also, if you can't acquire the tid lock here, that means the contents of memory on that thread is in an inconsistent state, and attempts to unwind it from here may go badly.

The tid lock (assuming you're talking about [this line](https://github.com/JuliaLang/julia/pull/50968/files#diff-f6974e2c87fefab68f1d0b54ba7ca47f601c086ba0d1ccf3f1aaa9177b2f2fe4R872)) cannot be acquired for sticky tasks running on other threads because their tids are never unset. That's the point of this patch.

**Comment by NHDaly** [comment]
The other major alternative to this PR, I think, would be to **preempt** all the other threads, exactly like the profiler does.

Then, once they're all paused, we should be free to safely walk the stacks of all Tasks, right?

-----------

But i think Kiran's question still stands: what locks would this stackwalking code be grabbing? Why should we need to preempt the threads inside julia's runtime if we have already paused them from GDB?

If there's any locks that this code is grabbing, can we use the new, _unsafe_ `ignore_tid` flag to _also ignore those locks_ and just not lock at all?

**Comment by kpamnany** [comment]
We discussed this some more -- this capability has already been very useful for us so we'd really like to improve it.

How would you want to implement this capability @vtjnash, such that no tasks are missed?

**Comment by kpamnany** [comment]
Superseded by https://github.com/JuliaLang/julia/pull/51430. Thanks @vtjnash!

**Pull request closed without merging**
