### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by MichaelHatherly**
- Signature changes in `stdlib/arrays.md` for changes to docstring signatures made in https://github.com/JuliaLang/julia/pull/19635;
- switch around `Pkg.resolve` and `Pkg.update` to hopefully solve an error encountered by @kshyatt;
- try to always build docs using `strict = true` to change doc errors/warnings prior to merging PRs.

### CODE REVIEW

**Review by tkelman — APPROVED** [review]
when we get doctests running regularly we can have those run in permissive mode except for releases, right?

**Comment by MichaelHatherly** [comment]
> when we get doctests running regularly we can have those run in permissive mode except for releases, right?

I'm going to try see if I can get doctests running on each build in this PR. That should stop things like backtrace line numbers becoming stale. There's a 265-related fix in Documenter that I need to tag first though that's blocking running `doctest` at the moment.

**Comment by tkelman** [comment]
I think line numbers will get annoying to keep changing on master, we can ignore those until release branches. Maybe we should take "running doctests on CI" one step at a time to see how it works day to day?

**Comment by MichaelHatherly** [comment]
Ok, small steps are fine too. I'll just push the doc version bump and a couple of doctest fixes here, but leave turning on doctests for another time.

**Pull request merged**
