### PR TITLE
Allow showing of StepRangLen{T} with generic T

### PR DESCRIPTION
**Pull request by SamuelBadr**
For types that don't support `==` with `Int64` (but do support `iszero`), printing `StepRangLen`s currently fails.

### CODE REVIEW

**Comment by jishnub** [comment]
Could you add a test?

**Comment by oscardssmith** [comment]
why does this have a backport label?

**Comment by jishnub** [comment]
It's a bugfix, so doesn't a backport seem reasonable?

**Comment by oscardssmith** [comment]
did this work in 1.8 and break later? otherwise imo it's a feature

**Pull request merged**
