### PR TITLE
RFC: deprecate degree-based trig functions

### PR DESCRIPTION
**Pull request by JeffBezanson**
I think these are kind of silly; does anybody use them for any real purpose?

These could potentially be moved to a package, or replaced in the future e.g. by methods of the normal trig functions on a `Degree` unit type.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Anything important and frequent enough to justify inclusion in Base :)

**Comment by yuyichao** [comment]
> really that bad though?

Yes. As I said, even though I can't qualify the importance, the main reason for me to use it is convinience and by that I mean convinience over `sin(x / 180 * pi)`. In another word, `sin(deg2rad(x))` is even worse than nothing at all since it's actually longer excluding the whitespace.

**Comment by dpsanders** [comment]
Although I am not a particular fan of the degree functions, they actually use extended precision, and so (?) are more ~precise~accurate:

```
julia> sind(180)
0.0

julia> sin(pi)
1.2246467991473532e-16
```
It does seem like they could certainly be moved to a package, though.

**Comment by ViralBShah** [comment]
While I always thought people work in radians, it seems a bit strange to not use our own dispatch for trig functions. While I am not a fan of `rad2deg`, I wouldn't mind an `Angle` type to dispatch on, where all the right stuff can be done with precision etc.

**Comment by ajkeller34** [comment]
Just for the record, there already are angle types to dispatch on if you use Unitful. Unitful calls `sind(30)` when you do `sin(30º)`, for example. Happy to tweak that to accommodate changes in Base though.

**Comment by KristofferC** [comment]
I have used these many times, sometimes  degrees are more natural. I think the convenience of having these outweigh the extra code.

**Comment by ggggggggg** [comment]
I almost always used the degree versions because I'm usually using them for quick calculations/estimates and I think in degrees, so i know the numbers I'm interested in in degrees.

**Comment by ViralBShah** [comment]
I think we should do `sin(30º)`. That is better on all counts.

**Comment by JeffBezanson** [comment]
Yes, I really like the idea of moving this to Unitful. The biggest problem is the inverse functions, where you want the output in degrees but the input is unitless.

**Comment by giordano** [comment]
> I think we should do `sin(30º)`. That is better on all counts.

Perhaps `sin(30°)`?

**Comment by giordano** [comment]
> The biggest problem is the inverse functions, where you want the output in degrees but the input is unitless.

```julia
asin(Degree, 0.5)
```
?

**Comment by yuyichao** [comment]
`sin(30°)` isn't bad but `asin(Degree, 0.5)` is the same length as `asin(0.5)/pi*180`.

**Comment by giordano** [comment]
> `sin(30°)` isn't bad but `asin(Degree, 0.5)` is the same length as `asin(0.5)/pi*180`.

I'm not in favor of the removing the degree-based functions, just like you :slightly_smiling_face:

However, I do believe that `asin(Degree, 0.5)` is better than `asin(0.5)/pi*180`, at least you don't have to remember if it's `*pi/180` or `*180/pi`, someone may can even get confused and multiply by `*pi/180` the argument of `asin`.  Of course, `asind(0.5)` is even simpler and shorter.

**Comment by ViralBShah** [comment]
Why not just `Deg(asin(0.5))` for `asind`? We have been removing the `s` suffixes for sparse matrix operations as well.

**Comment by yuyichao** [comment]
Sure, you can always try to encode more into types at the cost of convenience. I don't think this is comparable to sparse matrix operations since 1) sparse matrix is clearly a type 2) none of those functions are just for convinience. I'll also add that forcing a unit on a fundamentally unitless quantity and making it harder to do otherwise valid arithmetics on it is a minus for anyone that actually use these functions, especially for the inverse ones.

And still, what's the point of removing these? The original reasons given

> I think these are kind of silly; does anybody use them for any real purpose?

seems to be clearly invalid now. They aren't silly since the degree unit is not and they are being used for real purpose. As much as I like to move stuff out of base, I do like these functions to stay with the rad and pi versions.

**Comment by ajkeller34** [comment]
> Yes, I really like the idea of moving this to Unitful. The biggest problem is the inverse functions, where you want the output in degrees but the input is unitless.

In Unitful, conversions between degrees and unitless numbers assume the unitless number is in radians. If the unitless number is used in intermediate calculations there shouldn't be any errors. If you want degrees as a final result, you have to explicitly convert to degrees, which isn't so bad: `asin(0.5)|>°` or `°(asin(0.5))` if you've imported the degree symbol (unit objects do unit conversion when called). I think this is basically what Viral proposes just now.

That being said, while Unitful adds a degree of sophistication... is it such a big deal to keep these in Base? For feature discovery, `sind` is nice for the casual user. Also, `sin(30°)` looks short but you need to type \degree so it's more typing than `sind(30)`, if that's your primary concern. So while it may not be a totally consistent position I also prefer to keep these in Base.

**Comment by simonbyrne** [comment]
I wouldn't be opposed to a more descriptive name (say `sindeg`/`cosdeg`), but I guess `sind`/`cosd` has precedence from Matlab/Octave and some Fortran code (though they aren't in the Fortran standard).

**Comment by Keno** [comment]
What about `sin°` with aliases to `sindeg`, `cosdeg`, etc?

**Comment by StefanKarpinski** [comment]
I actually rather like @keno's suggestion. It's a bit cute but `sin°(180)` reads nicely and is equivalent to `sin(180°)` in  Unitful, which is nice as well. When I see `sind` I fairly regularly forget what it does and think it's like `sinf` in libm so the name `sindeg` would be an improvement since it's more obvious.

**Comment by JeffBezanson** [comment]
Sometimes I think `tand` has something to do with `rand`, or I think "t and what?" :)

**Comment by StefanKarpinski** [comment]
`tand` sounds like a brand of fake tanner.

**Comment by ajkeller34** [comment]
bill_gates_tandy2000

**Comment by simonbyrne** [comment]
> When I see `sind` I fairly regularly forget what it does and think it's like `sinf` in libm

Probably not helped by also having `sinc` and `sinh` as well.

**Comment by Sacha0** [comment]
👍 for `sindeg` and friends. `sin°(180)` looks a bit too much like composition or a product on this end. Best!

**Comment by StefanKarpinski** [comment]
> `sin°(180)` looks a bit too much like composition or a product on this end.

It kind of is both...

**Comment by JeffBezanson** [comment]
`(sin∘°)(x)` :joy:

**Comment by Keno** [comment]
I'll somewhat reluctantly admit that I originally thought `°` was always a postfix unary operator (even on identifiers), for which I wanted to define `°(f::Function) = x->f(x°)`, but it is valid as part of an identifier (and I think we should keep it that way).

**Comment by strickek** [comment]
Every better pocket calculator provide degree-based trig functions. So I think that Julia with the claim as an language for numerical computing should support this functions in Base.

**Comment by phlavenk** [comment]
I'd never use sind but instead always write `sin(30°)` after  `using Unitful, Unitful.°`. 

It's a missed opportunity not to rely more on the unitful values in Julia - one does not have to think of whether the variable is in degrees or in rad and what sin/sind/sin_grad needs to be called, it just always calculates the correct answer (without a speed penalty).

I'd really like to see Unitful being part of the stdlib and used much more through the codebase of other packages. It might not be in base, but all "generic-looking" algorithms and routines should test some unitful arguments in their unit tests. 

The only thing that I'd like to happen is a better support in the base infrastructure -- to simplify type definitions in e.g. tracebacks and logs, where using an unitful variable means one gets very long hard-to-read type definitions.

**Comment by JeffBezanson** [comment]
This doesn't seem to be too popular so I'll close it for now.

**Pull request closed without merging**
