### PR TITLE
Add docstring to `ConcurrencyViolationError`

### PR DESCRIPTION
**Pull request by Seelengrab**
This should cover the current usecases of this error.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
Should we add this to the docs/src files also?

**Comment by Seelengrab** [comment]
What is recorded in that file?

**Comment by vtjnash** [comment]
The source for the https://docs.julialang.org/en/v1/ pages

**Comment by Seelengrab** [comment]
I think it'd be good to have a dedicated "You're doing something weird with concurrency; if you see this error you most likely have a bug in your code" error, so yeah, having that listed there sounds good. I'll add it.

**Comment by gbaraldi** [comment]
Multithreading maybe?

**Comment by Seelengrab** [comment]
Alright, I've added a short blurb to the section on data races, which seemed like the most appropriate place `ConcurrencyViolationError` should be mentioned.

**Comment by Seelengrab** [comment]
Failures are due to not having a canonical place for the docstring-`@ref` of `ConcurrencyViolationError`. Do we have a place for multithreading docstrings to be shown that I can add this too?

**Comment by vtjnash** [comment]
Those seem to be split between docs/src/base/multi-threading.md and docs/src/base/parallel.md, with probably a preference towards the former for this, though either seems acceptable.

**Comment by Seelengrab** [comment]
Ok, I've added it to `parallel.md`, since the error is not exclusive to multithreading but for concurrency in general. Let's see if CI likes it now.

**Comment by Seelengrab** [comment]
Failures seem unrelated, so should be good to merge if the addition to the docs is ok.

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by Seelengrab** [comment]
Like I said in May, if the failure is unrelated (and it seems like it is), yes.

**Pull request merged**
