### PR TITLE
release-1.8: Backports for 1.8-rc3

### LINKED ISSUE #45979: [1.8.0-rc2][macOS] could not load library "@rpath/libcurl.4.dylib" error
Since ~3 days ago, `1.8.0-rc2` and the latest nightlies from `release-1.8` are erroring on the GHA macOS runner. I'm not sure if this is caused by an issue with the runner or an issue with Julia.

It was still working as of 6368fdc6565 aka `1.8.0-rc1`. 381eac37ca2d58a396e17f8355ee756af1bad10f is the first commit that I know to have this issue but the tests only run every 24h, so this isn't necessarily the commit that introduced it.

Possibly related: #45933, #45967

---

Full error

```
julia --compile=min -O0 -e using InteractiveUtils; versioninfo()
[...]
fatal: error thrown and no exception handler available.
InitError(mod=:LibCURL_jll, error=ErrorException("could not load library "@rpath/libcurl.4.dylib"
dlopen(@rpath/libcurl.4.dylib, 1): Library not loaded: @rpath/libnghttp2.14.dylib
  Referenced from: /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libcurl.4.dylib
  Reason: Incompatible library version: libcurl.4.dylib requires version 36.0.0 or later, but libnghttp2.14.dylib provides version 35.0.0"))
ijl_errorf at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_load_dynamic_library at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
#dlopen#3 at ./libdl.jl:117
dlopen at ./libdl.jl:116 [inlined]
dlopen at ./libdl.jl:116 [inlined]
__init__ at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-6.0/build/default-macmini-x64-6-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/LibCURL_jll/src/LibCURL_jll.jl:30
jfptr___init___70049.clone_1 at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_module_run_initializer at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
_finish_julia_init at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
julia_init at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_repl_entrypoint at /Users/runner/hostedtoolcache/julia/1.8-nightly/x64/lib/julia/libjulia-internal.1.8.dylib (unknown line)
Error: The process 'julia' failed with exit code 1
```

Environment info:

```
Operating System
  macOS
  11.6.6
  20G624
Virtual Environment
  Environment: macos-11
  Version: 20220627.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220627.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220627.1
```

Some failing builds:
- `release-1.8`: https://github.com/julia-actions/setup-julia/actions/workflows/example-builds-nightly.yml
- `1.8.0-rc2`: https://github.com/julia-actions/setup-julia/runs/7266108728?check_suite_focus=true

### PR DESCRIPTION
**Pull request by KristofferC**
(cherry picked from commit 69f10f8e649e725203d5202792dac9e3a3f1de3f)

fixes https://github.com/JuliaLang/julia/issues/45979

### CODE REVIEW

**Comment by KristofferC** [comment]
I seem to consistently be getting

```
Error During Test at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/julia-5c5d54aa3b/share/julia/stdlib/v1.8/Downloads/test/runtests.jl:453
  Got exception outside of a @test
  HTTP/2 200 (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds) while requesting https://httpbingo.org/drip
  Stacktrace:
    [1] (::Downloads.var"#9#18"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Main.Test12Main_Downloads.var"#28#54"{Vector{Any}}, Bool, Nothing, Bool, String, Bool, Bool})(easy::Downloads.Curl.Easy)
      @ Downloads /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/julia-5c5d54aa3b/share/julia/stdlib/v1.8/Downloads/src/Downloads.jl:387
    [2] with_handle(f::Downloads.var"#9#18"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Main.Test12Main_Downloads.var"#28#54"{Vector{Any}}, Bool, Nothing, Bool, String, Bool, Bool}, handle::Downloads.Curl.Easy)
      @ Downloads.Curl /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/julia-5c5d54aa3b/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:88
    [3] #8
      @ /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/julia-5c5d54aa3b/share/julia/stdlib/v1.8/Downloads/src/Downloads.jl:328 [inlined]
...
```

in the Downloads test with this :/

**Comment by giordano** [comment]
But #45408 has been merged 2 months ago on master, it doesn't seem to have been particularly problematic since then.

**Comment by KristofferC** [comment]
Well, I see this on both the linux runners that run the Downloads.jl tests and even after a restart. But maybe that endpoint is just down and it is not related to this.

**Comment by giordano** [comment]
Tests for [i686-linux-gnu](https://buildkite.com/julialang/julia-master/builds/13697#0181e8b1-67c8-4ff1-8911-a7e915d29092) and [win64](https://build.julialang.org/#/builders/63/builds/6687/steps/5/logs/stdio) are currently failing with the same errors also for #45823, which is totally unrelated.

**Comment by DilumAluthge** [comment]
Closing and reopening doesn't retrigger Buildkite. I contacted support, and they told me that's the intended behavior.

To retry a failing Buildkite job, you'll need to go to the Buildkite page and click the retry button for the desired jobs.

**Comment by KristofferC** [comment]
Ouch hah! I tried login and it just tells me I am not in the correct github group, or something like that.

**Comment by giordano** [comment]
> they told me that's the intended behavior.

:neutr

**Comment by DilumAluthge** [comment]
I'm going to reach out to Buildkite support again to see if they'll reconsider adding the "rebuild when a PR is closed and reopened" feature.

**Comment by giordano** [comment]
I mean, this is related to the fact they don't build on the merge commit but the tip of the branch. Closing and reopening a PR never changes the tip, you have to actually change that somehow (amend, rebase, whatever)

**Pull request merged**
