### PR TITLE
maybe fix julia-debug on windows

### PR DESCRIPTION
**Pull request by JeffBezanson**
... by loading sys.dll but ignoring the code in it. cc @tkelman 

I haven't tried this yet on windows.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Hrm. dlsym doesn't seem to work on libraries loaded with this flag. Oh well.

**Comment by tkelman** [comment]
are you and @vtjnash duplicating effort here? ref #12145 which looks like a different approach to the same problem

**Comment by vtjnash** [comment]
yes. also ref #12151

**Comment by JeffBezanson** [comment]
Yes we tried multiple approaches.

**Comment by vtjnash** [comment]
...and we're going with #12151.

**Pull request closed without merging**
