### PR TITLE
Convert Ac_ldiv_B etc. docs to Markdown

### PR DESCRIPTION
**Pull request by dpsanders**
Convert the docs for the functions `Ac_ldiv_B` etc. to Markdown, eliminating the use of `:sup:` in `helpdb.jl`. #13047 

This also homogenizes the signatures used in the docs for this set of functions.

Note that documentation for `A_ldiv_B!` is missing. I would add it, if I knew what this function does... (I guess it's `A := A / B` ?

### CODE REVIEW

**Comment by dpsanders** [comment]
Docs also missing for `A_mul_Bc!` etc.

**Comment by yuyichao** [comment]
The rendered html doesn't look too bad but this breaks `make -C doc latexpdf` again.

**Comment by jakebolewski** [comment]
Is this because of the unicode superscripts?

**Comment by dpsanders** [comment]
Ouch. What can I do about that?

**Comment by yuyichao** [comment]
@jakebolewski Yes

@dpsanders Not sure. I think there's a commit/PR that fixes latexpdf recently but I'm having a hard time finding it.

**Comment by yuyichao** [comment]
Find it 8dfdeaf70ad99c34d8c23c8f17ae6d697926eb48

Do something like that then?

**Comment by dpsanders** [comment]
Thanks @yuyichao -- now done. It's not exactly pretty in the PDF, but it's functional...  (An alternative would be to use latex, $...$, instead of `...`,  in the docstrings, but that seems to be out of style.)

**Comment by yuyichao** [comment]
I was actually going to suggest using math mode instead of code quote since these are more mathematically expressions rather than julia code.

**Comment by jakebolewski** [comment]
It looks ok.  If we transition to Markdown there is a good chance we will lose the fancy latex -> pdf output Sphinx offers anyway.

**Comment by dpsanders** [comment]
I was just about to put up the version with inline Latex. Shall I make a new PR?

**Comment by dpsanders** [comment]
(It does look better!)

**Comment by jakebolewski** [comment]
sure

**Comment by tkelman** [comment]
backported in #13107

**Pull request merged**
