### PR TITLE
Reduce context scope

### PR DESCRIPTION
**Pull request by pchintalapudi**

### CODE REVIEW

**Comment by vtjnash** [comment]
This somehow broke the threadcall macro?
```
      From worker 5:	signal (11): Segmentation fault
      From worker 5:	in expression starting at /buildworker/worker/tester_linux32/build/share/julia/test/ccall.jl:1083
      From worker 5:	unsafe_store! at ./pointer.jl:125 [inlined]
      From worker 5:	unsafe_store! at ./pointer.jl:125 [inlined]
      From worker 5:	top-level scope at /buildworker/worker/tester_linux32/build/share/julia/test/ccall.jl:1086
      From worker 5:	_jl_invoke at /buildworker/worker/package_linux32/build/src/gf.c:2383 [inlined]
      From worker 5:	ijl_invoke at /buildworker/worker/package_linux32/build/src/gf.c:2390
```

**Comment by pchintalapudi** [comment]
Are we sure this isn't just another OOM error? The immediately preceding lines are a ccall to jl_malloc, and if overcommit is turned on the pointer might only segfault upon the store rather than being null immediately.

**Comment by vtjnash** [comment]
The allocation is slightly too small to be likely to trigger OOM, even when allocated on the wrong thread. Though true it could just be null like this
```
julia> unsafe_store!(Ptr{Int}(0), 1)
signal (11): Segmentation fault
in expression starting at REPL[3]:1
unsafe_store! at ./pointer.jl:125
```

**Comment by pchintalapudi** [comment]
I'm just more suspicious of the tester because win32 and linux64 show no signs of any errors remotely related to ccall, and linux32 hasn't run on master for at least the last 35 commits (probably more beyond the first page). If we could persuade another run of linux32 to happen that would be nice, if only to see if it's deterministic.

**Comment by DilumAluthge** [comment]
> linux32 hasn't run on master for at least the last 35 commits (probably more beyond the first page)

Linux32 is being run in Buildkite under the name i686-linux-gnu.

**Comment by pchintalapudi** [comment]
@vtjnash does this look good to merge?

**Pull request merged**
