### PR TITLE
inline copyto! for SubArrays

### PR DESCRIPTION
**Pull request by KristofferC**
Motivated by the following benchmark

```jl
using BenchmarkTools
a = rand(3,3); b = rand(2,2);
f1(a,b) = (a[1:2, 2:3] .= b; nothing)
f2(a,b) = copyto!(a, CartesianIndices((1:2, 2:3)), b, CartesianIndices((1:2, 1:2)))
```

Before

```jl
julia> @btime f1($a,$b)
  28.141 ns (1 allocation: 64 bytes)

julia> @btime f2($a,$b)
  20.994 ns (0 allocations: 0 bytes)
```

After

```jl
julia> @btime f1($a,$b)
  20.387 ns (0 allocations: 0 bytes)

julia> @btime f2($a,$b)
  20.995 ns (0 allocations: 0 bytes)
```

Call-site inlining would probably be a better solution to this specific problem though.

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

cc @mbauman since Im pretty sure you thought about this before at some point

Edit: The removal of the allocation requires https://github.com/JuliaLang/julia/pull/29867/files.

### CODE REVIEW

**Review by vtjnash — CHANGES_REQUESTED** [review]
I think this is a bad idea to abuse the compiler for the sake of 2x2 array peformance.

**Comment by KristofferC** [comment]
Could you give an alternative solution or is the compiler not powerful enough to handle this use-case yet?

**Comment by mbauman** [comment]
> Im pretty sure you thought about this before at some point

Yes, I have. In general, I think of functions with for-loops as being too big to inline, but the allocation of subarrays here is particularly annoying.  Want #14955.

Could a middle-ground here be a hack of a duplicate method that inlines just for SubArrays?

**Comment by KristofferC** [comment]
> Could a middle-ground here be a hack of a duplicate method that inlines just for SubArrays?

I thought about that to. I'll try it out.

**Comment by KristofferC** [comment]
How about:

```jl
@inline _copyto!(a, b) = copyto_body
copyto(A::AbstractArray, B::AbstractArray) = _copyto!(A, B)
@inline copyto!(A::SubArray, B::AbstractArray) = _copyto!(A, B)
@inline copyto!(A::AbstractArray, B::SubArray,) = _copyto!(A, B)
```

?

**Comment by mbauman** [comment]
Yeah, that seems reasonable, but of course you'll also need the `(::SubArray, ::SubArray)` case for disambiguation. In general I do try to avoid defining public functions with overrides along those lines (e.g., `(::T, ::T)` + `(::T, ::S)` + `(::S, ::T)` + `(::S, ::S)` where `S <: T`) for exactly that reason.

> In general, I think of functions with for-loops as being too big to inline, but the allocation of subarrays here is particularly annoying. Want #14955.

While I say that, I also think of dot-broadcasting in terms of writing the equivalent for-loop directly in place.  Another longer-term solution here could be call-site inlining, so that broadcasting could explicitly tell `copyto!` to inline into its body without affecting other callers.  Do we not have an issue for that?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29868) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/a8c147a22811fad3688f6c375c059e0e27f961bd/890c808_vs_eabc5de/report.md). cc @ararslan

**Comment by timholy** [comment]
I'm less excited about this, simply because I am pretty sure we can solve this via the compiler. The inliner assigns a cost of 203 to this function (threshold for inlining is 100), but 140 of it is due to these 7 statements:
```julia
 :($(Expr(:invoke, MethodInstance for throw_boundserror(::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}), :(Base.throw_boundserror), :(_2), :(%6))))                                                    
 :($(Expr(:invoke, MethodInstance for mightalias(::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}, ::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}), :(Base.mightalias), :(_2), :(_3))))
 :($(Expr(:foreigncall, :(:jl_alloc_array_2d), Array{Float64,2}, svec(Any, Int64, Int64), :(:ccall), 3, Array{Float64,2}, :(%48), :(%50), :(%50), :(%48))))                                                                                                                                                          
 :($(Expr(:invoke, MethodInstance for copyto!(::Array{Float64,2}, ::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}), :(Base.copyto!), :(%51), :(_3))))                                                                                                 
 :($(Expr(:invoke, MethodInstance for throw_boundserror(::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}, ::Tuple{Int64}), :(Base.throw_boundserror), :(%72), :(%97))))                                                                                
 :($(Expr(:invoke, MethodInstance for throw_boundserror(::SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},true}, ::Tuple{Int64}), :(Base.throw_boundserror), :(_2), :(%124))))                                                                                
 :((Base.arrayset)(false, %145, %121, %147))                                      
```
3 of these would go away with #29798. 1 (`Base.arrayset`) is special-cased by `codegen.cpp` and should not be penalized. That leaves 3 due to aliasing. (I almost wonder if we need a `@wontalias`, but that's a separate discussion.) We could presumably reduce that to 1 by putting a `@noinline` in front of `unalias`. At that point, boom, this function inlines automatically for these inputs.

**Comment by KristofferC** [comment]
Cool, would be good to know how to do this magic (ref https://github.com/JuliaLang/julia/issues/29171) :)

**Comment by KristofferC** [comment]
Even though test fails here and people are not too happy with the implementation I'm running the benchmarks again because the combination of this PR and #29867 is what really allows eliding view allocation in some cases.

So:

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by KristofferC** [comment]
No allocations on master

**Pull request closed without merging**
