### PR TITLE
Throw an error when `call` is not a generic function

### LINKED ISSUE #12612: Segfault in baremodule from trying to call an external type
This is an error in any case (ideally a `call` MethodError, I guess), but it probably shouldn't be a segfault:

```jl
julia> type Foo; end
       baremodule A
         import Main: Foo
         f() = Foo()
       end
       A.f()
ERROR: TypeError: builtin_tfunction: in typeassert, expected Function, got Type{Foo}
 in builtin_tfunction at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in abstract_call at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in abstract_eval_call at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in abstract_eval at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in typeinf_uncached at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in typeinf at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib
 in typeinf_ext at /Users/mbauman/Applications/julia-0.4/lib/julia/sys-debug.dylib

julia> baremodule B
         f() = Main.Foo()
       end
       B.f()

signal (11): Segmentation fault: 11
mtcache_hash_lookup at /Users/mbauman/Code/julia-0.4/src/gf.c:153
jl_method_table_assoc_exact at /Users/mbauman/Code/julia-0.4/src/gf.c:249
jl_apply_generic at /Users/mbauman/Code/julia-0.4/src/gf.c:1629
f at none:2
jlcall_f_21113 at  (unknown line)
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
jl_trampoline at /Users/mbauman/Code/julia-0.4/src/builtins.c:996
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
jl_apply_generic at /Users/mbauman/Code/julia-0.4/src/gf.c:1674
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
do_call at /Users/mbauman/Code/julia-0.4/src/interpreter.c:65
eval at /Users/mbauman/Code/julia-0.4/src/interpreter.c:213
jl_interpret_toplevel_expr at /Users/mbauman/Code/julia-0.4/src/interpreter.c:27
jl_toplevel_eval_flex at /Users/mbauman/Code/julia-0.4/src/toplevel.c:525
jl_toplevel_eval_flex at /Users/mbauman/Code/julia-0.4/src/toplevel.c:473
jl_toplevel_eval at /Users/mbauman/Code/julia-0.4/src/toplevel.c:548
jl_toplevel_eval_in at /Users/mbauman/Code/julia-0.4/src/builtins.c:567
jl_f_top_eval at /Users/mbauman/Code/julia-0.4/src/builtins.c:598
eval_user_input at REPL.jl:63
jlcall_eval_user_input_21080 at  (unknown line)
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
jl_apply_generic at /Users/mbauman/Code/julia-0.4/src/gf.c:1650
anonymous at task.jl:92
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
jl_trampoline at /Users/mbauman/Code/julia-0.4/src/builtins.c:996
jl_apply at /Users/mbauman/Code/julia-0.4/src/./julia.h:1264
start_task at /Users/mbauman/Code/julia-0.4/src/task.c:230
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by yuyichao**
The error message is mirroring the one a few lines above for the definitely not function case.

Fix #12612

@mbauman

### CODE REVIEW

**Comment by yuyichao** [comment]
@vtjnash especially for checking how much conflict this will have with the codegen rewrite.

**Comment by vtjnash** [comment]
it'll be annoying, although not a huge number of lines to fix. my bigger concern would be just that the previous version of this was correct as-is and should have worked. However it looks like jl_bottom_func may be declared incorrectly:
```
jl_bottom_func = jl_new_closure(jl_f_no_function, (jl_value_t*)jl_emptysvec, NULL);
```

by parallel to the other primitives and `add_builtin_func`, it looks like that second argument should have been something like `jl_symbol("no_function")`

**Comment by yuyichao** [comment]
I think `svec()` should be correct?

```julia
julia> (()->()).env
svec()
```

**Comment by yuyichao** [comment]
Also I don't see why the original code would work before without checking for `jl_bottom_func`. `jl_apply_generic` expect a generic function and `jl_bottom_func` is clearly not in any case.

**Comment by vtjnash** [comment]
> Also I don't see why the original code would work before without checking for jl_bottom_func. jl_apply_generic expect a generic function and jl_bottom_func is clearly not in any case.

hm, good point. although `call` isn't necessarily either a gf or bottom, it could also be another random lambda or builtin function, for example. perhaps `jl_apply_generic` should handle those cases more gracefully, or it should emit here an assert that call is a gf.

**Comment by yuyichao** [comment]
> although call isn't necessarily either a gf or bottom

Agree. I'm actually adding the assertion along with the test and the fix in inference right now. I think I'll replace the check in codegen with `jl_is_gf` as well. I don't think we need to support the case where `call` is a non generic function anyway....

**Comment by yuyichao** [comment]
Done.

**Comment by yuyichao** [comment]
FWIW, `jl_apply_generic` seems to be the only case we call `jl_gf_mtable` without a branch or assertion on `jl_is_gf`.

**Comment by yuyichao** [comment]
Or should we just add `jl_is_gf` check to `jl_module_call_func`?

The `just_emit_error` above doesn't handle general random function case either so in order to be consistent we should either always require `call` to be a generic function or fix this assumption everywhere.

We don't really assume call is a generic function in many places but I also don't find it necessary to support non-generic function either.

**Comment by yuyichao** [comment]
I went ahead and restrict the return value of `jl_module_call_func` to be either a generic function or `jl_bottom_func`. I left the check/assert as `jl_is_gf` since I don't think they are very performance critical anyway...

**Comment by yuyichao** [comment]
Any more comments? Should we try to support non gf as call?

**Comment by yuyichao** [comment]
Rebased. If the CI passes and no one has any objection, I'll merge this later today or tomorrow.

**Comment by vtjnash** [comment]
thanks

**Pull request merged**
