### PR TITLE
Handle generic numbers in generic pivoted cholesky correctly

### PR DESCRIPTION
**Pull request by dkarrasch**

### CODE REVIEW

**Comment by dkarrasch** [comment]
This is working correctly now also in the generic complex case, which was not handled correctly before. Local tests indicate that the unpivoted algorithm and the pivoted algorithm (but only in the lowertriangular version) also work for Quaternions. It remains to fix the uppertriangular version of the pivoted algorithm in view of order of multiplication.

**Comment by oscardssmith** [comment]
Do the `@simd` removals not affect performance?

**Comment by dkarrasch** [comment]
I hadn't removed any such annotations, but now I have added them in the new code. Now, both Cholesky decompositions will work for any `Number` eltype.

**Comment by oscardssmith** [comment]
you seem to have messed up your merge.

**Comment by dkarrasch** [comment]
Yes, something went horribly wrong. Now it should be fixed.

**Comment by DilumAluthge** [comment]
@dkarrasch CI is all green now.

**Pull request merged**
