### PR TITLE
upgrade LLVM to 10

### PR DESCRIPTION
**Pull request by vchuravy**
and so it goes, on and on and on. We might either do it now and iron out the kinks
during 1.5 or do it very early in 1.6.

- [x] #37159
- [x] #37153 
- [x] https://github.com/JuliaPackaging/Yggdrasil/pull/1301

### CODE REVIEW

**Comment by vchuravy** [comment]
This might be the first upgrade where Windows passes at the first attempt...

@keno can I bother you with updating the GCAnalyzer?

**Comment by ianshmean** [comment]
What’s the current thinking on when this might merge? 

Just wondering, regarding llvm support for new arm cpus related to #36485, a few of which were added in 10.

I guess it’d need performance benchmarking given the feared 10% that hit rust https://nikic.github.io/2020/05/10/Make-LLVM-fast-again.html

**Comment by vchuravy** [comment]
My current thinking is to wait of 10.0.1 or 11, but yes additional performance benchmarking of the compile time would be good.

**Comment by vchuravy** [comment]
Also #35460 needs to be fixed first. @ianshmean if you want to try your hand at writing an LLVM patch ;)

**Comment by ianshmean** [comment]
I'm happy to take a look in some of my _fun time_. Can't promise much though..

@vchuravy would you mind rebasing this?

**Comment by yuyichao** [comment]
.... How many relocator does LLVM have = = .......

**Comment by vchuravy** [comment]
> .... How many relocator does LLVM have = = .......

https://xkcd.com/927/

**Comment by yuyichao** [comment]
Well, I assume they are not "competing".....

Just that I felt like I've fixed a more complex aarch64 relocatioin before, and it's definitely not either `R_AARCH64_ABS32` or `R_AARCH64_ABS64`.

Is there an LLVM IR that triggers this? That'll make testing significantly easier.

**Comment by yuyichao** [comment]
Is there a patch for this already? I finally have a (actually 2) working aarch64 systems again so if no one is working on it I can.

**Comment by vchuravy** [comment]
No patch that I am aware off.

**Comment by chriselrod** [comment]
Would LLVM 11 be an option for Julia 1.6? RC-2 is out now, with 11-final planned for August 26th.
If so, it'd be worth benchmarking as well. There's been a lot of recent work on improving LLVM's speed, mainly for Rust's sake:
https://nikic.github.io/2020/05/10/Make-LLVM-fast-again.html
https://blog.mozilla.org/nnethercote/2020/08/05/how-to-speed-up-the-rust-compiler-some-more-in-2020/
Would be interesting to benchmark and see if it helps us, too.

I believe LLVM 11 also includes this: https://reviews.llvm.org/D75016
I'd like to at least have that patch in Julia 1.6. I'll look into how to apply it if we won't ship with Julia LLVM 11 (i.e., looking at Valentin's and Yuyichao's PRs to see how it's done).
That patch should allow LoopVectorization to stop using `asm call` for `vfmadd231p(d/s)`, and just use `@llvm.fmuladd` instead.

BTW, not particularly relevant to this issue, but the AVX-512 down-clocking problem has been almost complete solved as of Ice Lake: https://travisdowns.github.io/blog/2020/08/19/icl-avx512-freq.html

Instructions: scalar/light128 bit - heavy 256 bit - heavy 512 bit
My cascadelake 1 core: 4.6 - 4.3 - 4.1
My cascadelake all-core: 4.6 - 4.3 - 4.1
Ice Lake i5-1035G4 1 core: 3.7 - 3.7 - 3.6
Ice Lake i5-1035G4 4 core: 3.3 - 3.3 - 3.3
There are some other problems where LLVM generates bad AVX-512 code where 256 bit vectors would be faster than 512 bit, even at the same clock speed.

I haven't found out how to use `JULIA_LLVM_ARGS` to actually change the preferred vector width, so I can't run benchmarks without also using different LLVM versions. LLVM's args are different from Clang's (where it would be `-mprefer-default-vector-width=$BITS`).

**Comment by yuyichao** [comment]
I assume you mean `-mprefer-vector-width=`.

It's not an LLVM command line option but a (global and per-function) target property. Add `prefer-256-bit` to the cpu specification should work, i.e. `julia -C "native,prefer-256-bit"`.

**Comment by chriselrod** [comment]
Yes, perfect, thanks!

**Comment by ianshmean** [comment]
@chriselrod I was thinking the same. Getting to LLVM 11 in 1.6 seems like a good idea on the face of it. 10 does seem to be the ugly duckling and the work on speed since does seem positive, but probably still a good idea to work through 10 to get to 11?

There's also some newer arm chip support in LLVM 11 such as nvidia Carmel that would be nice to get into the next LTS.

**Comment by chriselrod** [comment]
> 10 does seem to be the ugly duckling 

It may be the ugly duckling, but I did notice some improvements in several LoopVectorization examples, where integer/indexing code was handled better by LLVM 10 than by LLVM <=9. So there're some definite improvements (that probably apply to other examples as well?).

A simple example of where 256-bit performs much better than 512-bit:
```julia
julia> function trmv!(y, A, x)
           fill!(y, 0)
           @inbounds for n ∈ axes(A,2)
               @simd for m ∈ 1:n
                   y[m] += A[m,n] * x[n]
               end
           end
       end
trmv! (generic function with 1 method)

julia> M = 64; C = rand(M, M); x = rand(M); y = similar(x);

julia> @benchmark trmv!($y, $C, $x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     825.942 ns (0.00% GC)
  median time:      830.907 ns (0.00% GC)
  mean time:        838.359 ns (0.00% GC)
  maximum time:     1.315 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     86
```
Versus starting with `-C "native,prefer-256-bit"`:
```julia
julia> function trmv!(y, A, x)
           fill!(y, 0)
           @inbounds for n ∈ axes(A,2)
               @simd for m ∈ 1:n
                   y[m] += A[m,n] * x[n]
               end
           end
       end
trmv! (generic function with 1 method)

julia> M = 64; C = rand(M, M); x = rand(M); y = similar(x);

julia> @benchmark trmv!($y, $C, $x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     508.031 ns (0.00% GC)
  median time:      509.016 ns (0.00% GC)
  mean time:        509.541 ns (0.00% GC)
  maximum time:     668.363 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     193
```

**Comment by vchuravy** [comment]
Note that this is LLVM 10.0.1 so lots of fixes might already been backported. Going to LLVM 11 is feasible, but higher risk and might involve more work from our side to side out regressions. 

If you really want to see LLVM 11 for 1.6 I would appreciate help with that. Getting an WIP on Yggdrasil for rc2 would be the first step, as well as looking at the patch list. Currently I do these upgrades when I am plagued by insomnia.

**Comment by chriselrod** [comment]
I've read a lot of LLVM IR, but that's very different from being familiar with LLVM itself.

What's the procedure for these upgrades, how I would I start? Which patch list? Julia's list of LLVM patches, to see which are no longer needed in LLVM 11?

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = "master")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/35318#issuecomment-697324886) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/0668c39121b8a24309c9c24e7059e4b5b6892aa6/2bc0d8b_vs_274b973/report.md). cc @ararslan

**Comment by vchuravy** [comment]
`["array", "index", "(\"sumeach\",  \"SubArray{Int32, 2, BaseBenchmarks.ArrayBenchmarks.ArrayLS{Int32, 2},  Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}},  false}\")"]` | 15.31 (50%) | 1.00 (1%)
-- | -- | --

Definitely worth looking into

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35318#issuecomment-697325231) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/c17d6c4f08e30538e4d23e3ffa94c22da51abfc7/pkgeval/by_hash/9adcdd4_vs_274b973/report.md). cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(["CartesianGeneticProgramming", "Contour", "DecFP", "Gridap", "IncompleteLU", "Infinity", "IntervalTrees", "MusicManipulations", "NormalSplines"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35318#issuecomment-698485230) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/3f7217cd256c08c2f821e4fc61c3f7dd8cd3aeab/pkgeval/by_hash/9adcdd4_vs_b1e1bb3/report.md). cc @maleadt

**Pull request merged**
