### PR TITLE
Two small tests for enums

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by kshyatt** [comment]
Looks like the CI fails are unrelated?

**Comment by StefanKarpinski** [comment]
@nalimilan: was this by any chance the thing you accidentally broke for a while yesterday?

**Comment by nalimilan** [comment]
Yes, that's it. Let's just re-run CI?

**Comment by StefanKarpinski** [comment]
Since it passed on some of the systems and seems very unlikely to be broken in a platform specific way, I'm just going to merge.

**Pull request merged**
