### PR TITLE
[win] Backport win MSYS2 build pr

### PR DESCRIPTION
**Pull request by inkydragon**
fix build error: "ERROR: Too few special library names specified, check LOADER_BUILD_DEP_LIBS and friends!"
- #46140
- #46803
- #46867

### CODE REVIEW

**Comment by inkydragon** [comment]
Now, Windows build works well, but there is something wrong with `SparseArrays`.

**Comment by DilumAluthge** [comment]
@staticfloat Can you review this?

**Review by staticfloat — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@staticfloat Is this good to merge? I'm seeing failures in LinearAlgebra/special on 32-bit platforms, but I'm not sure if that's an existing problem.

**Comment by staticfloat** [comment]
I believe those are not related to this PR

**Pull request merged**
