### PR TITLE
allow packages to hook into code loading

### PR DESCRIPTION
**Pull request by KristofferC**
This is so e.g. Pkg3 can install packages on demand:

mar-15-2018 12-38-10

### CODE REVIEW

**Comment by fredrikekre** [comment]
Notes from Pkg triage:

> Prompting for package additionTop-level X:
> - happens when doing import X at top-level if X is not in load path
> - “Add package X?”
> - add X
> - resolve (implicit)Dev’d non-top-level package:
> - happens when Y does import X without Y in its deps
> - “Add package X to project Y?”
> - activate Y
> - add X
> - deactivate
> - resolve (edited) 
> both cases need to have a package called X
> if there’s two packages called X they both need to ask which one you want

**Comment by DilumAluthge** [comment]
This is only for the REPL, right? Presumably, if you are running a script, then `using Foo` should still throw an error if the package `Foo` is not found.

**Comment by Keno** [comment]
I think a better implementation of this would be to throw a special error type that the REPL intercepts. That way the REPL (and any other frontend offering code evaluation) can be in charge of presenting the UI without needing to inject callbacks in the core loading code.

**Comment by ianshmean** [comment]
I've given @keno's suggestion a go over here https://github.com/JuliaLang/julia/pull/39026

**Comment by oxinabox** [comment]
Can this now be closed?

**Pull request closed without merging**
