### PR TITLE
README: start adding Buildkite status badges

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Should these move somewhere else? Is the status of e.g. analyzegc really the first things people need to see? It is now even before the description of what Julia is...

**Comment by DilumAluthge** [comment]
> Should these move somewhere else? Is the status of e.g. analyzegc really the first things people need to see? It is now even before the description of what Julia is...

Yeah I agree. Options include:
1. Bottom of the README file.
2. A different markdown file altogether.

Any thoughts?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/41374

**Comment by KristofferC** [comment]
I don't think details like "analyzegc" and "llvmpasses" need to be in the README at all

**Pull request merged**
