### PR TITLE
Fix hashing for large arrays

### PR DESCRIPTION
**Pull request by oscardssmith**
caused by https://github.com/JuliaLang/julia/pull/39966#pullrequestreview-614659942

### CODE REVIEW

**Comment by simeonschaub** [comment]
Could we have a test that covers this case as well?

**Comment by oscardssmith** [comment]
Good point. Added.

**Review by simeonschaub — APPROVED** [review]

**Comment by mbauman** [comment]
Oh dang, this means that what I said [here](https://github.com/JuliaLang/julia/pull/39966#discussion_r590571580) was wrong:

> We already hash the axes, and the access pattern will be constant for a given shape.

**Not true:**

https://github.com/JuliaLang/julia/blob/5515893eac29f9964a84d07ffde4ed9f88aac368/base/abstractarray.jl#L2463-L2465

**Comment by mbauman** [comment]
So, doubly embarrassing.  We should add back in the key hashing.

**Comment by oscardssmith** [comment]
Am I correct in assuming that the purpose of those 2 lines is to make sure we hit nonzeros for `Sparse` arrays?

**Comment by mbauman** [comment]
Yes, that's exactly it.

**Review by mbauman — APPROVED** [review]

**Pull request merged**
