### PR TITLE
Add hasfield to check for field existence

### PR DESCRIPTION
**Pull request by iamed2**
I wanted this in another package but I figure it's general and useful enough for Base.

### CODE REVIEW

**Review by ararslan — DISMISSED** [review]

**Comment by iamed2** [comment]
The doctest is not enough? `fieldindex` itself only has doctests.

**Comment by ararslan** [comment]
No, doctests are nice to have but pretty much everything should have a unit test. Weird that `fieldindex` doesn't have tests.

**Comment by JeffBezanson** [comment]
`fieldindex` probably didn't have tests since it's not exported.

I think this is fine for now. For future reference, I notice that both this and some existing functions like fieldoffset and fieldname should be expanded to handle more types using the technique that `fieldcount` uses.

**Comment by ararslan** [comment]
Could you add an entry for this in NEWS.md as well?

**Review by ararslan — APPROVED** [review]

**Pull request closed without merging**
