### PR TITLE
Update from NSIS to Inno Setup installer

### PR DESCRIPTION
**Pull request by musm**
While working on trying to remove the extra 7z stage we do on the NSIS installer, I realized this was not  ideal since NSIS only implements lzma and not more recent compression methods from 7z. 

Instead, I opted to transition to Inno setup, it's actually far easier to use and more robust and modern than NSIS.  This also compress the files with lzma2 

refixes https://github.com/JuliaLang/julia/issues/30475

### CODE REVIEW

**Comment by musm** [comment]
Installer experience (very similar to the current experience)
t2

**Comment by musm** [comment]
(note to self update BMP's )

**Comment by musm** [comment]
This is ready on my end

**Comment by staticfloat** [comment]
This looks really good to me, @musm.  Thanks for the solid effort here, and especially for the "installation experience" GIF.  Just to be doubly sure that CI and whatnot works well on this branch, I'm going to merge your CI PR, wait for this to make its way through CI, then download and install on a windows machine to ensure that everything is as beautiful as it looks.

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
Works flawlessly.  Merging.

**Comment by staticfloat** [comment]
Actually, one more thing; let's add a `NEWS.md` entry about this to tell users that CLI extraction should use the new slash flags, to avoid frustration.  :)

We also may have to update Appveyor.jl and Travis.

**Comment by musm** [comment]
Done

My my own reference: The following can be used on the svg from julia-branding to generate the `bmp` files used in the installer. 
```
> magick convert banner.svg -transparent white -background white -flatten -resize 164x -gravity center -extent 164x314 -density 1000 julia-banner.bmp
```

**Comment by staticfloat** [comment]
Good work @musm!

**Comment by musm** [comment]
great thanks for the merge. Yep I'm glad for the simplicity of the new builder.

**Comment by musm** [comment]
Great thanks for the merge. I'm glad of the resulting simplicity of the new builder.

**Comment by fredrikekre** [comment]
> We also may have to update Appveyor.jl and Travis.

Looks like this is the case. At least AV is broken now.

**Comment by musm** [comment]
https://github.com/JuliaCI/Appveyor.jl/pull/19

**Comment by musm** [comment]
Appveyor is fixed.

Could someone with more experience in Travis implement the fix there? 
Something like https://github.com/musm/travis-build/pull/1 is needed

**Pull request merged**
