### PR TITLE
oneunit of unitfull matrix should return a unitfull matrix

### PR DESCRIPTION
**Pull request by KlausC**
Applying `oneunit` to an matrix of unitfull element type should return a matrix of same type.
```
julia> using Dates
julia> oneunit([Second(0) Second(0); Second(0) Second(1)] )
2×2 Array{Second,2}:
 1 second   0 seconds
 0 seconds  1 second 
```
but we have currently:
```
julia> oneunit([Second(0) Second(0); Second(0) Second(1)] )
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Second
Closest candidates are:
  convert(::Type{Second}, ::Minute) at /home/julia/julia/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:407
  convert(::Type{Second}, ::Hour) at /home/julia/julia/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:407
  convert(::Type{Second}, ::Day) at /home/julia/julia/usr/share/julia/stdlib/v1.1/Dates/src/periods.jl:407
  ...
Stacktrace:
 [1] setindex! at ./array.jl:779 [inlined]
 [2] _one(::Second, ::Array{Second,2}) at ./array.jl:487
 [3] oneunit(::Array{Second,2}) at ./array.jl:493
 [4] top-level scope at none:0
```

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
Looks like a bug, thanks!

By the way, why does this file still have a docstring for ones? Wasn’t that deprecated?

**Comment by StefanKarpinski** [comment]
> By the way, why does this file still have a docstring for ones? Wasn’t that deprecated?

I thought so too, but apparently it's still there and exported, along with `zeros`:
```jl
julia> ones
ones (generic function with 6 methods)

help?> ones
search: ones leading_ones trailing_ones countlines count_ones to_indices RoundNearest

  ones([T=Float64,] dims...)

  Create an Array, with element type T, of all ones with size specified by dims. See
  also: fill, zeros.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> ones(1,2)
  1×2 Array{Float64,2}:
   1.0  1.0

  julia> ones(ComplexF64, 2, 3)
  2×3 Array{Complex{Float64},2}:
   1.0+0.0im  1.0+0.0im  1.0+0.0im
   1.0+0.0im  1.0+0.0im  1.0+0.0im

julia> zeros
zeros (generic function with 6 methods)

help?> zeros
search: zeros count_zeros set_zero_subnormals get_zero_subnormals leading_zeros

  zeros([T=Float64,] dims...)

  Create an Array, with element type T, of all zeros with size specified by dims. See
  also fill, ones.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> zeros(1)
  1-element Array{Float64,1}:
   0.0

  julia> zeros(Int8, 2, 3)
  2×3 Array{Int8,2}:
   0  0  0
   0  0  0
```
@Sacha0, didn't you delete these?

**Comment by fredrikekre** [comment]
We tried: #25507

**Comment by StefanKarpinski** [comment]
Oh wow, I totally misremembered that as actually happening. I guess it was the removal of all the uses that I remembered. Eh, I'm fairly ok with still having `ones` and `zeros`.

**Comment by Sacha0** [comment]
> `@Sacha0`, didn't you delete these?

`@fredrikekre` made a valiant attempt, but alas... :)

> We tried: #25507

❤️

**Pull request merged**
