### PR TITLE
backport of fast Pkg.publish

### PR DESCRIPTION
**Pull request by carlobaldassi**
This is a PR against the release-0.3 branch, to backport the changes which sped up `Pkg.publish`, i.e. #10323, #10396 and #10417.

It's a fairly large and not quite trivial batch of changes, but the sluggishness of the publishing process on 0.3 is such that this speed up may well be considered a bug fix. Also, it's been on 0.4 without problems for a while now.

Everything seems to work as it should on my machine (about 4s to check the whole metadata...), so unless there are CI surprises or objections I'll merge this in a while.

### CODE REVIEW

**Comment by carlobaldassi** [comment]
I don't understand the Travis error on Mac. It complains about a missing `/usr/local/lib/gcc/4.9/libgfortran.3.dylib for architecture x86_64`. I restarted the job and got the same result. Anyone knows what this is about?

**Comment by tkelman** [comment]
It looks like it failed on something related to suitesparse. I'm going to say homebrew fluke, I restarted it and looks okay now?

**Comment by carlobaldassi** [comment]
Ah I see, thanks.

**Comment by simonbyrne** [comment]
+1!

**Comment by tkelman** [comment]
Just making sure, this included all followup related commits, right?

**Comment by carlobaldassi** [comment]
I'm not sure what you're referring to. It included everything in the 3 PRs mentioned at the beginning. Is there more?

**Comment by tkelman** [comment]
I'm asking since you worked on them and would hopefully remember, were there any followups on master aside from those 3 PR's?

**Comment by carlobaldassi** [comment]
No, everything I did was there.

**Comment by ncnc** [comment]
#11137 is an unrelated Pkg speedup that might be worth backporting as well.

**Pull request merged**
