### PR TITLE
llvm api update for r240826

### PR DESCRIPTION
**Pull request by ihnorton**
https://github.com/llvm-mirror/llvm/commit/237b76d7404db808720d6fd27fa4b85474eebedc

### CODE REVIEW

**Comment by Keno** [comment]
This is on LLVM 3.8.

**Comment by ihnorton** [comment]
? https://github.com/llvm-mirror/llvm/blob/release_37/include/llvm/IR/Module.h

**Comment by ihnorton** [comment]
or, rather, https://github.com/llvm-mirror/llvm/blob/release_37/include/llvm/IR/Module.h#L256-L257

**Comment by ihnorton** [comment]
I linked to the wrong revision in the commit message here. Should be this instead: https://github.com/llvm-mirror/llvm/commit/c94da20917cb4dfa750903b366c920210c5265ee#diff-98ff4600e54bcf7a716dfa47cfc336d4R372

**Comment by ihnorton** [comment]
@Keno ok to commit or did I misunderstand something?

**Comment by tkelman** [comment]
We should pay attention to when they branch for llvm 3.8, should be relatively soon

**Comment by tkelman** [comment]
Oh, they already did last week - http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-July/088034.html

So we need an LLVM38 define for the next breaking changes on trunk, and specifically checkout release_37 for testing the 3.7 rc's.

**Pull request merged**
