### PR TITLE
Faster println()

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Would be nice to backport to 1.11.2 since common enough.

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Before and after seems to have strangly large code with calls.

```
@noinline println() = println(stdout)
```

seems to have no effect.

**Comment by PallHaraldsson** [comment]
Also:
```
println(xs...) = print(stdout, xs..., "\n")  # 3 fewer allocations
```

Timing is better or same, but misleading? Those allocations would cost in the end with many in a loop?

```
julia> @time println("P")
P
  0.000057 seconds (2 allocations: 32 bytes)


julia> @time println("P")
P
  0.000058 seconds (5 allocations: 80 bytes)
```

**Comment by PallHaraldsson** [comment]
This scales badly (independently of my code):
```
@code_native println("Palli ", "Palli ", "Palli ", "Palli ", "Palli ", "Palli ", "Palli ", "Palli ")
```

vs. already bad:

```
@code_native println("Palli ")
```

**Review by vtjnash — APPROVED** [review]
I would have though “ made more sense for both methods though

**Comment by PallHaraldsson** [comment]
julia> @code_native println("Palli", "X", "Y")
	.text
	.file	"println"
	.globl	japi1_println_7124              # -- Begin function japi1_println_7124
	.p2align	4, 0x90
	.type	japi1_println_7124,@function
japi1_println_7124:                     # @japi1_println_7124
; Function Signature: println(String, String, String)
; ┌ @ REPL[83]:1 within `println`
# %bb.0:                                # %top
	push	rbp
	mov	rbp, rsp
	push	rbx
	sub	rsp, 72
	vxorps	xmm0, xmm0, xmm0
	vmovaps	xmmword ptr [rbp - 32], xmm0
	mov	qword ptr [rbp - 16], 0
	mov	qword ptr [rbp - 40], rsi
	#APP
	mov	rax, qword ptr fs:[0]
	#NO_APP
	mov	rbx, qword ptr [rax - 8]
	mov	qword ptr [rbp - 32], 4
	mov	rax, qword ptr [rbx]
	mov	qword ptr [rbp - 24], rax
	lea	rax, [rbp - 32]
	mov	qword ptr [rbx], rax
	movabs	rax, offset ".L*Main.Base.stdout#7125.jit"
	mov	rax, qword ptr [rax]
	test	rax, rax
	je	.LBB0_2
# %bb.1:                                # %ok
	mov	rcx, qword ptr [rsi + 16]
	vmovups	xmm0, xmmword ptr [rsi]
	mov	qword ptr [rbp - 80], rax
	vmovups	xmmword ptr [rbp - 72], xmm0
	mov	qword ptr [rbp - 16], rax
	mov	qword ptr [rbp - 56], rcx
	movabs	rax, offset ".Ljl_global#7130.jit"
	mov	qword ptr [rbp - 48], rax
	movabs	rdi, offset ".Ljl_global#7129.jit"
	movabs	rax, offset ijl_apply_generic
	lea	rsi, [rbp - 80]
	mov	edx, 5
	call	rax
	movabs	rax, offset jl_nothing
	mov	rax, qword ptr [rax]
	mov	rcx, qword ptr [rbp - 24]
	mov	qword ptr [rbx], rcx
	add	rsp, 72
	pop	rbx
	pop	rbp
	ret
.LBB0_2:                                # %err
	movabs	rdi, offset ".Ljl_sym#stdout#7126.jit"
	movabs	rsi, offset ".Ljl_global#7127.jit"
	movabs	rax, offset ijl_undefined_var_error
	call	rax


Despite now fewer allocations:

```
julia> @time println("Hello world")
  0.000057 seconds (2 allocations: 32 bytes)


This still even faster (assuming accurate timing, web browser open), despite more allocations:
julia> using Printf

julia> @time @printf "Hello world\n"
Hello world
  0.000049 seconds (4 allocations: 112 bytes)

julia> @time (@printf "Hello world"; @printf "\n")
Hello world
  0.000055 seconds (8 allocations: 216 bytes)
```

**Comment by PallHaraldsson** [comment]
I can live with this going in as is, but a question about you, @KristofferC dropping this comment:
# These forms do not require a stack, unlike splatting:
..
println(x1, x2) = print(stdout, x1, x2, "\n")

It does use registers, not stack allocate, BUT though does NOT on nightly. Strange why the optimization doesn't work there...

The two argument (and splatting) might need its own precompiled, could be added here for 1.11.2, or in separate commit.

I'm not too worried about three forms of println and print each bloating the sysimage, but could drop that one for println. It does avoid the stack, but then likely on the call to print, no longer, but that part isn't inlined.


The CI is failing for unrelated reasons (I assume all of the CI failures):
```
numbers                                          (4) |        started at 2024-10-24T14:41:12.473
      From worker 4:	LLVM ERROR: Do not know how to promote this operator's result!
      From worker 4:
      From worker 4:	[276] signal 6 (-6): Aborted
      From worker 4:	in expression starting at /cache/build/default-power9bot3-0/julialang/julia-master/julia-9810001467/share/julia/test/numbers.jl:2093
      From worker 4:	gsignal at /lib/powerpc64le-linux-gnu/libc.so.6 (unknown line)
```

**Comment by KristofferC** [comment]
> It does use registers, not stack allocate, BUT though does NOT on nightly. Strange why the optimization doesn't work there...

Talking about stack and registers is too low level of a comment to add at this place.

**Comment by PallHaraldsson** [comment]
@KristofferC I see 1.11.1 has a regression, conditional jump I mentioned above:
je	.LBB0_2

The regression is in with or without this merged. I'm actually confused what's it about, and may not have time to look into. A conditional taken branch is also likely not too bad.

Also I think I do not actually avoid stack allocation as I thought. I think I misread code_native, and this no issue on nightly, i.e. not better in 1.11.

I may look into it, maybe I only avoided stack-allocation, at some point, not sure what I did then differently. It's not that costly anyway so maybe I do not worry. But then just take it out, to also avoid adding more precompile for the one-and two-form?

**Pull request merged**
