### PR TITLE
add some commas (scope section in manual)

### PR DESCRIPTION
**Pull request by tpapp**
Trivial style fixes: added commas.

### CODE REVIEW

**Comment by tkelman** [comment]
there are a lot of unrelated commits in here

**Comment by tpapp** [comment]
Sorry, still learning (fighting) git. Will redo the PR.

**Comment by tkelman** [comment]
best to force push over the existing branch to keep it within the same PR

**Comment by yuyichao** [comment]
For this case, squash on merge can probably work.

**Pull request closed without merging**
