### PR TITLE
bump Pkg version

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
Don't really understand the `analyzegc` test error. Looks like some corrupt registry?

```
ERROR: "/cache/julia-buildkite-plugin/depots/53de1ea5-6dd3-4008-b976-161c9f34b0ad/registries/General/J/JLLWrappers/Package.toml": No such file
```

**Comment by DilumAluthge** [comment]
@staticfloat Looks like a cache corruption?

**Comment by DilumAluthge** [comment]
On a separate note, it would be nice to have a `git log` of the commits between the old Pkg commit and the new Pkg commit.

**Comment by giordano** [comment]
https://github.com/JuliaLang/Pkg.jl/compare/5434d05fba65f4ad735a85644af3c9fa16a1d75c..6351948ae8c7a796fab819e6178d1b5c3c6c1083

**Comment by DilumAluthge** [comment]
I was thinking something more concise that would be included in the PR description itself.

See e.g. the output from `git log --oneline` included in the description of this PR: https://github.com/JuliaLang/julia/pull/41673#issue-950132942

**Comment by DilumAluthge** [comment]
@KristofferC Can you rebase this on the latest master? That will fix the Buildkite failures.

Alternatively, we can merge https://github.com/JuliaLang/julia/pull/41979 instead.

**Pull request closed without merging**
