### PR TITLE
Fix calls to `realpath` for shared network drives

### PR DESCRIPTION
**Pull request by corakingdon**
see https://github.com/JuliaLang/julia/issues/33956 for discussion

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
Looks good to me. Let us know when you've tested with the CI-built binary.

**Comment by fredrikekre** [comment]
Answering https://github.com/JuliaLang/julia/issues/33956#issuecomment-567095365 here:

> Thanks @fredrikekre! where on the PR can I find the option to download?

https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x64/1.4/julia-fe14bfcf42-win64.exe

**Comment by ckingdon95** [comment]
Thank you! for future reference though, where did that link come from?

**Comment by KristofferC** [comment]
Click Details on the `buildbot/tester_win64` (https://build.julialang.org/#/builders/32/builds/6845)

Then look at

> download_url | `"https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x64/1.4/julia-fe14bfcf42-win64.exe"`

**Comment by ckingdon95** [comment]
@StefanKarpinski in combination with the changes made to Pkg, this seems to work fully on my network drive! I'm wondering though if this is a strange work around, and if it would be better to change the `realpath` definition instead, since it's a julia function? thoughts?https://github.com/JuliaLang/julia/blob/8707744ae5f778c005d6c29342fe01cb654527af/base/path.jl#L409-L434

**Comment by StefanKarpinski** [comment]
It's true that the `realpath` function is kind of problematic, but it's a very low level function and I don't think we want our `realpath` to deviate too much from the system one, which has this behavior. Honestly, in this case we maybe shouldn't be calling `realpath` at all. In any case, improving/changing `realpath` is a much bigger discussion and since this fixes your issue, let's go with it. We can merge the two fixes independently and then once they're both included in master, the issue will be fixed. Another question is whether these are backportable fixes or not. I guess I don't really see why not, but it would be good to get some other opinions on backporting.

**Comment by StefanKarpinski** [comment]
I've approved but, @ckingdon95, I need you to make this no longer a draft before I can merge.

**Comment by StefanKarpinski** [comment]
I've opened https://github.com/JuliaLang/julia/issues/34135 to discuss improving `realpath` or offering a better replacement for it.

**Pull request merged**
