### PR TITLE
New methods findprev and findlast

### PR DESCRIPTION
**Pull request by tomasaschan**
While working on something else, I found I wanted a `findlast` method in analogy with `findfirst`.
Since `findfirst` is implemented in terms of `findnext`, I implemented `findlast` with the same
relation to a new `findprev`.

While working, I also noticed there were no tests for `findnext`, so I added a few.

### CODE REVIEW

**Comment by tlycken** [comment]
Bump. Is there any interest in this? Would it be worth my time to rebase it onto current master, so it merges cleanly?

**Comment by tkelman** [comment]
Seems generally useful, not that much added code, has tests and docs, so IMO yes? I'm not sure where the conflicts are going to be though, what has changed in the vicinity of these additions.

**Comment by tlycken** [comment]
My guess is that someone has added unrelated code in the same space that I have, so that the merge is a relatively simple "keep everything". I haven't looked at it in detail, though.

**Comment by kmsquire** [comment]
I think this is useful and fills out functionality, so I'm for it.

**Comment by tlycken** [comment]
Turns out the only merge conflict was in the docs, where someone had changed something on the row *after* what I was adding, and git apparently couldn't tell that it wasn't really a conflict. Should be fixed and mergeable now, anyway.

**Comment by tlycken** [comment]
Since my rebase, #9428 was merged with a big re-organization of stdlib docs. I've rebased to fit this into the new structure, hopefully without errors...

**Comment by StefanKarpinski** [comment]
+1 – let's merge this as soon as the builds turn green.

**Comment by tlycken** [comment]
@StefanKarpinski I would be *very* surprised if this turned anything but green. This will be, at least, the fourth time te CI systems have checked this PR without me changing basically any code in it, and it only adds new code and (tests for itself), so there's almost zero chance these changes could break anything else. The only thing that can actually go wrong is if something else merged into master in the last six hours broke `findnext`, since that is code that existed before but didn't have tests before. This might very well be one of the PR's that's been CI-tested the most times with no changes in between :P

(But if it does turn red, the joke will be on me, surely...)

**Comment by tkelman** [comment]
Technically these rebases are the first time this PR's ever been run on appveyor, and while it doesn't look like there's anything platform-specific here, stranger things have happened. Unfortunately the queue is extremely long right now. I can test this locally if someone's feeling impatient.

**Comment by tkelman** [comment]
Oh, looks like it was green here https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.1061 but there was one more rebase after that. If the most recent rebase was just moving docs around then I think we're fine.

**Comment by tlycken** [comment]
@tkelman All rebases since September have been conflict-free except in docs.

**Comment by tkelman** [comment]
sounds good to me

**Pull request merged**
