### PR TITLE
Better help answers for strange inputs

### PR DESCRIPTION
**Pull request by mbauman**
Before:

```julia
help?> ``
ERROR: LoadError: Invalid @var syntax `Core.@cmd`.

help?> {a
ERROR: LoadError: Invalid @var syntax `incomplete: premature end of input`.

help?> 123456789012345678901234567890
ERROR: LoadError: Invalid @var syntax `Core.@int128_str`.
```

After:

```julia
help?> ``
  @cmd str
  ...

help?> {a
  No documentation found.

help?> 123456789012345678901234567890
  @int128_str str
  ...
```

### CODE REVIEW

**Comment by mbauman** [comment]
Hm, did my commit message break CI? (in addition to pinging/subscribing Vimal and Chris — so sorry guys!  Oh how I wish Github would fix this.)

**Comment by JeffBezanson** [comment]
> ```julia
> 
> help?> 123456789012345678901234567890
>   @int128_str str
> ```

This is a big improvement but it would be nice if this could somehow behave like other numbers instead of exposing the parser implementation detail of the int128_str macro.

**Comment by mbauman** [comment]
I don't have a good enough grasp on the help REPL mode to know how (or if it's possible) to distinguish between asking for `help?> @int128_str "123456789012345678901234567890"` vs. `help?> 123456789012345678901234567890`.  I'd call this a solid 2x incremental improvement in reducing the number of internal macros getting displayed, plus a bonus removal of an ugly error message and stack trace. :)

**Comment by JeffBezanson** [comment]
True enough!

**Pull request merged**
