### PR TITLE
Speed up map on tuples. Fixes #15695

### LINKED ISSUE #15695: map on tuples is prohibitively slow
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3333 (2016-03-30 03:42 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4a13500* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> t = ntuple(x->x,1000);

julia> @time map(-, t)
488.491589 seconds (4.79 M allocations: 227.712 MB, 0.01% gc time)

julia> @time map(-, t)
  0.065904 seconds (620.06 k allocations: 26.750 MB, 6.09% gc time)
```

Two alternative implementations (for tuples with > 3 elements) would be:

```julia
julia> function map1(f, t::Tuple)
           ([f(x) for x in t]...)
       end
map1 (generic function with 1 method)

julia> @time map1(-, t);
  0.028094 seconds (9.86 k allocations: 449.154 KB)

julia> @time map1(-, t);
  0.000096 seconds (498 allocations: 39.500 KB)

# this one is by @SimonDanisch
@generated function map2(f, x::Tuple)
              len = length(x.parameters)
              expr = [:(f(x[$i])) for i=1:len]
              :(tuple($(expr...)))
       end

julia> @time map2(-, t);
 10.158751 seconds (233.77 k allocations: 10.337 MB)

julia> @time map2(-, t);
  0.000030 seconds (6 allocations: 8.047 KB)
```

### PR DESCRIPTION
**Pull request by shashi**

### CODE REVIEW

**Comment by timholy** [comment]
While it will be nice for big tuples, this seems likely to hammer performance on small tuples.

**Comment by shashi** [comment]
It would probably be good to figure out approximately what "small" is and then write generated functions (or just `@eval` in a for loop) up to that number. Then use this method for all other cases. From my experiments performance takes a hit after some 8 elements. I'm also fine with holding up on this PR till there is a better consolidated clever implementation that Jeff mentioned in #15695

**Comment by KristofferC** [comment]
I get the following run times comparing the "Vector version" vs the fully unrolled version up to N = 100:

figure_2

The compilation time looks like this:

figure_1

Pretty interesting that the `@generated` compilation time is lower than the vector one for < 25 elements.

**Comment by JeffBezanson** [comment]
Nice data!

We also need to worry about the ability to infer the result type. We'll need some kind of cutoff, perhaps like this one: https://github.com/JuliaLang/julia/blob/7b51368d95fa682052af0329cb2b03ca1409fbc7/base/operators.jl#L85

**Pull request closed without merging**
