### PR TITLE
use explorer rather than cmd start in Windows edit command

### PR DESCRIPTION
**Pull request by stevengj**
As discussed in #20364

### CODE REVIEW

**Comment by tkelman** [comment]
It looks like setting `JULIA_EDITOR` to `start` was something the old batch files used to do, so not something we need to worry about any more.

**Comment by stevengj** [comment]
Can we get rid of the `start` check on MacOS too?

**Comment by stevengj** [comment]
Good to merge?

**Review by vtjnash — APPROVED** [review]

**Comment by tkelman** [comment]
did anyone test this locally?

**Comment by stevengj** [comment]
Is there a way to download the AppVeyor build?  I can run on Windows, but I can't build Julia on Windows.

**Comment by tkelman** [comment]
appveyor doesn't upload artifacts. you can try running the same script that appveyor does. or if this were a branvh in JuliaLang we could trigger the buildbot on it

**Comment by tkelman** [comment]
since this only touches julia code, build_sysimg should be enough. even eval into base should work in the post-265 world, though might want to add some debugging prints while testing to be sure the new version is what's used

**Comment by stevengj** [comment]
Can I move the branch to JuliaLang without opening a new PR?

**Comment by tkelman** [comment]
sure, doesn't need to have an open pr, just a sha that can be fetched from the JuliaLang repo

**Comment by vtjnash** [comment]
I tested that using `explorer` will indeed launch programs as desired. Although it also always exits with an error code (1), so ymmv. (also, unlike all of the other options, it may execute the item instead of edit it)

**Comment by stevengj** [comment]
@vtjnash, would you prefer the `ShellExecute` method (#20478) instead, then?  It provides more informative error output, and distinguishes between opening and executing the file.

**Comment by stevengj** [comment]
Closing in favor of #20571, then.

**Pull request closed without merging**
