### PR TITLE
preserve `do` syntax in AST

### PR DESCRIPTION
**Pull request by JeffBezanson**
part of #21774

### CODE REVIEW

**Comment by ararslan** [comment]
Can you remind me on why triage was in favor of preserving `do`? Thinking about it now, this seems like an annoying thing to have to remember to special-case when writing a macro that handles anonymous functions like this.

**Comment by JeffBezanson** [comment]
I'm not 100% convinced myself, but I can think of some reasons:

- This allows better pretty-printing of expressions.
- Converting `do` to its lowered form re-orders expressions, which is a bit unintuitive.
- Keno felt that the `do` form might be useful for macro DSLs to intercept.

**Comment by MikeInnes** [comment]
> the `do` form might be useful for macro DSLs to intercept.

Yes, this is generally a good reason to preserve this kind of information. If you don't care it might be an extra concern (though not if you're just walking over all lambdas).

The extra work for `do` blocks pales in comparison with things like function definitions, which we don't normalise at all. So we need a more general solution there anyway, probably involving exposing some lowering tools in Base.Meta.

**Comment by JeffBezanson** [comment]
1.0 decision needed.

**Comment by MikeInnes** [comment]
So right now I'm generating expressions that look like this:

```julia
map(((quetzal,)->(Dagger.Thunk)(begin
    (penguin,)->begin  
            bear = (Array{Any,1})(quetzal)
            for jellyfish = quetzal
                bear[jellyfish] = penguin[jellyfish] + 1
            end
            bear
        end
end, chslice(cat, domain(cat, 1)))), domprod(domain(cat, 1)))
```

With this change the code would output like this:

```julia
map(domprod(domain(cat, 1))) do quetzal
    (Dagger.Thunk)(chslice(cat, domain(cat, 1)))) do penguin 
        bear = (Array{Any,1})(quetzal)
        for jellyfish = quetzal
            bear[jellyfish] = penguin[jellyfish] + 1
        end
        bear
    end
end
```

Which is a significant readability improvement.

**Comment by StefanKarpinski** [comment]
We don't really need this change to get that, we just need some decent heuristics on when to use `do` syntax printing a function call. Just off the top of my head: the function is the first argument and the body of the function definition is multiline.

**Comment by StefanKarpinski** [comment]
Triage is ambivalent about this. @JeffBezanson, it's your call. Do what your heart tells you.

**Comment by StefanKarpinski** [comment]
Triage: let's do it. Merge as soon as CI passes.

**Pull request merged**
