### PR TITLE
[release-0.5] revert #17389 for 0.5.0-rc1

### PR DESCRIPTION
**Pull request by tkelman**
caused a big performance regression, should have ran nanosoldier before merging

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":v0.5.0-rc0")`

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "0030eec2f332f353e6890ca289ac2aca55532dde")`

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0030eec2f332f353e6890ca289ac2aca55532dde")`

**Comment by pabloferz** [comment]
I think I found a solution for the rest of the problems, but this is a good idea anyway.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/17804#issuecomment-237457204) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4be01cdbc9f5ee2b705309454db3358ba396946d/0e239af_vs_0030eec/report.md). cc @jrevels

**Comment by tkelman** [comment]
So since rc0, `["tuple","index",("sumelt","NTuple",30,Float64)]` got almost 2x worse, a bunch of others got maybe 2x better, and a handful got 15-20% worse.

**Comment by KristofferC** [comment]
The native code for `sumelt` with tuple is identical in rc0 and master.

**Pull request merged**
