### PR TITLE
Add `Artifacts.toml` files for our fake JLL packages

### PR DESCRIPTION
**Pull request by staticfloat**
These don't do anyhting except play nicely with other tools that expect
to find `Artifacts.toml` files within JLL package directories, like BB.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This seems to break Pkg CI on AppVeyor: https://ci.appveyor.com/project/JuliaLang/pkg-jl/builds/35900697. It keeps failing with complaints about not being able to install artifacts for LibCURL_jll or MozillaCACerts_jll.

**Comment by fredrikekre** [comment]
I was just about to make a PR to delete those files because they are not used by the packages, and cause artifacts downloads for e.g. `pkg> add Downloads` for no reason. This should not fail as in Stefans comment in any case, but there is no reason to even try to download these at all.

**Comment by KristofferC** [comment]
> These don't do anyhting except play nicely with other tools that expect to find Artifacts.toml files within JLL package directories, like BB.

As Fredrik says, they do in fact do something, they cause Pkg to try download those artifacts when the stdlib is added.

**Comment by StefanKarpinski** [comment]
Would marking all the artifacts as lazy help? The future plan, I believe, is to actually provide these as artifacts, which would prevent Pkg from downloading them, but we haven't merged the change for that yet.

**Comment by KristofferC** [comment]
Yes, that would make them not be downloaded. They were added because other parts of the infrastructure expects them but maybe they are fine with them being lazy.

**Comment by staticfloat** [comment]
I think just naming the file to something else is a fine solution; BB (and other tools) can be taught to look in another filename I think.

**Comment by StefanKarpinski** [comment]
That seems drastic for what seems like a temporary problem, no? Won't this issue go away once we're using actual JLLs for Julia's own dependencies? At that point the JLLs will already be installed (in the read-only system depot), so this wouldn't be a problem anymore.

**Comment by staticfloat** [comment]
Yes; but that's not going to happen until v1.7.

**Comment by StefanKarpinski** [comment]
Ah, ok. I forgot about that and thought it was still happening in 1.6.

**Pull request merged**
