### PR TITLE
move generate_precompile to Base so that it is bundled in downloads

### PR DESCRIPTION
**Pull request by KristofferC**
If one wants to rebuild the sysimg it is useful to have access to this script since it is what makes starting Julia, the REPL and Pkg fast. Not sure if this is the best way to make it bundle with the download.

cc @andreasnoack

### CODE REVIEW

**Comment by ararslan** [comment]
Should this be backported to 1.0 as well?

**Comment by andreasnoack** [comment]
I believe this is still needed for my use case in MKL.jl.

**Comment by phlavenk** [comment]
> Jameson says this is not needed and that one can add things incrementally to the existing sysimg.
> 
> > That’s the very slow way to regenerate it though. The fast way to the same result is just to rerun the optimizer:
> > `julia --output-o x-o.a -J lib/sys.so -O3 -g1 -e "nothing" -C nativ`

Is this incremental build of sysimg used already by PackageCompiler? I had the impression that REPL responsiveness slowed down after I added Makie into the sysimg and blamed the missing REPL precompile. But I didn't spend time by proper benchmarking (I've decided to wait for Makie 1.0 and just reverted the old sysimg).

**Comment by JeffBezanson** [comment]
If we change this, it should be changed in the packaging script instead of moving it to `base` (it's not part of Base).

**Comment by vtjnash** [comment]
PR seems old

**Pull request closed without merging**
