### PR TITLE
Effects for symbol comparisons

### LINKED ISSUE #47424: Inferred effects when comparing symbols
I discovered that comparison operations on symbols (with the exception of `==`) end up removing all inferred effects. I narrowed the problem down to `ccall(:strcmp, Int32, (Cstring, Cstring), x, y)` found [here](https://github.com/JuliaLang/julia/blob/abf2afbcc4f6689809363410aa11bddcfabed540/base/strings/basic.jl#L348). I'm assuming this is because it is converted to a `String` but would it be appropriate to specify any effects since it's an interned string?

### PR DESCRIPTION
**Pull request by Tokazama**
Fixes #47424

### CODE REVIEW

**Review by aviatesk — COMMENTED** [review]
Is the implicit `unsafe_convert(::Type{Cstring},::Symbol)::Cstring` also total? I think so, since it's just lowered to `jl_symbol_name`, but I would like to double check.

**Comment by Tokazama** [comment]
`Base.infer_effects(Base.unsafe_convert, (Type{Cstring},Symbol))` isn't total but I checked all the other components.

**Comment by aviatesk** [comment]
Yes, `Base.infer_effects` (or rather, Julia compiler's effect analysis system) doesn't recognize most of `foreigncall`s so `unsafe_convert(::Type{Cstring},::Symbol)::Cstring` would be not be `:total` unless we mark it explicitly. My concern is if it is not really `:total`, then it would be problematic if we mark `cmp(::Symbol, ::Symbol)` as `:total`. In other word, I would like to check that the implementation of `jl_symbol_name` is total or not.

**Comment by Tokazama** [comment]
The method converting `Symbol` to a `String` is apparently total, which I think ends up calling `jl_symbol_name` to get a pointer ([here](https://github.com/JuliaLang/julia/blob/1715110da6a9f7a1f1774281e5bbb8d953c3ba60/base/strings/string.jl#L98
)), but if one decides to ignore anything marked "unsafe" you can still do some wonky stuff

```julia

julia> s = :foo;

julia> ptr = Base.unsafe_convert(Ptr{UInt8}, s);

julia> unsafe_store!(ptr, unsafe_load(ptr) - one(UInt8));

julia> s
:eoo
```

I'm not sure if that's the sort of thing you had in mind for checking that.

**Comment by Keno** [comment]
> In other word, I would like to check that the implementation of `jl_symbol_name` is total or not.

It is not, because I don't believe the address of the string is stable across sysimg reloads.

**Comment by Keno** [comment]
> It is not, because I don't believe the address of the string is stable across sysimg reloads.

In particular, that means it is not `:consistent`, but the overall comparison function is consistent and it's fine to annotate it as such. Perhaps we may want to do something more fine-grained in the future, but I think this should be fine. @aviatesk do you have any concerns to the contrary?

**Comment by aviatesk** [comment]
> In particular, that means it is not `:consistent`, but the overall comparison function is consistent and it's fine to annotate it as such. Perhaps we may want to do something more fine-grained in the future, but I think this should be fine. @aviatesk do you have any concerns to the contrary?

I understand. I think we may want to annotate `unsafe_convert(::Type{Cstring},::Symbol)` as `@assume_effects :total !consistent` (and ideally change the annotation on `cmp(::Symbol, ::Symbol` to `@ccall`-annotation on `strcmp`, but it might be difficult as `@ccall` isn't available in strings/basic.jl).

**Review by aviatesk — APPROVED** [review]

**Pull request merged**
