### PR TITLE
add support for async backtraces of Tasks on any thread

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by oscardssmith** [comment]
what's the difference between an `arraylist_t` and a Julia `Vector` (which we can also use from the C side?

**Comment by vtjnash** [comment]
An `arraylist_t` is not a safepoint, and as such, cannot hold GC references and cannot be reclaimed by the GC. In most cases, `Vector{Int}` is the preferable thing to use, if the GC is available and initialized on that thread.

**Comment by kpamnany** [comment]
The previous implementation of this capability was insufficiently safe and segfaults on occasion, so this is actually a bugfix. Can we backport it to 1.10 @vtjnash and @KristofferC?

**Comment by kpamnany** [comment]
If so, https://github.com/JuliaLang/julia/pull/51471 should be backported also.

**Pull request merged**
