### PR TITLE
Make `norm` handle `missing`s

### PR DESCRIPTION
**Pull request by dkarrasch**
X-ref  #40769.

### CODE REVIEW

**Comment by ViralBShah** [comment]
This would be nice to update and get merged.

**Comment by dkarrasch** [comment]
Is this less controversial (than `dot`) because it doesn't add methods?

**Comment by dkarrasch** [comment]
@KristofferC What do you think?

**Comment by KristofferC** [comment]
Sorry, I don't think `missing` belongs in the LinearAlgebra module at all :). But that's just my view.

**Comment by ViralBShah** [comment]
If we don't deal with `missing` in basic linear algebra, then we just need to replicate all that machinery on the stats side. I agree with @dkarrasch 's assessment here.

**Comment by KristofferC** [comment]
> If we don't deal with missing in basic linear algebra, then we just need to replicate all that machinery on the stats side.

Not really, you just need to explicitly handle it at the call site (which you have to do in most cases anyway).

 If what you want is a function that always returns missing from missing input then let's just add that one function and be done with it (`liftmissing`). The belief that you can just add these one by one to finally get something consistent is an illusion. Almost any algorithm can be decomposed into "basic math" operations where missing is allegedly supposed to propagate. So you would need to add this special case for virtually every method based on this argument.

**Pull request merged**
