### PR TITLE
correct shape for vec*mat error #14679

### PR DESCRIPTION
**Pull request by fwang88**
If the first dimension of a matrix is not 1, we should throw a dimension mismatch message for vec*mat.

### CODE REVIEW

**Comment by andreasnoack** [comment]
The present definition will already give the error you ask for. It will just be thrown from the matmat method instead.
```jl
julia> randn(2)*randn(2,2)
ERROR: DimensionMismatch("A has dimensions (2,1) but B has dimensions (2,2)")
 in gemm_wrapper! at linalg/matmul.jl:312
 in * at linalg/matmul.jl:89
```

**Comment by fwang88** [comment]
This is from issue #14679. In your example, the dimension of A should be (2,), not (2,1).

**Comment by fwang88** [comment]
I added a test example. Since I'm quite new to all these, I'll appreciate a lot if any comments are provided.

**Comment by tkelman** [comment]
LGTM. Separate issue, but I wonder if using "A" and "B" in these error messages is maybe not the clearest...

**Comment by fwang88** [comment]
@tkelman Yes, I agree with you. But it seems the error message of any mismatched matrix multiplication uses "A" and "B", as used in function [gemm_wrapper!](https://github.com/JuliaLang/julia/blob/master/base/linalg/matmul.jl)

**Comment by tkelman** [comment]
Yeah, it should be consistent here for now, but there's an opportunity to make both clearer in the future. Thanks for the contribution!

**Comment by oscardssmith** [comment]
Fixed on current versions

**Pull request closed without merging**
