### PR TITLE
More fair equivalent for pisum() function in R

### PR DESCRIPTION
**Pull request by kenahoo**
The `pisum` function in the Julia benchmarks uses a vectorized squaring & reciprocal operation on its indices, so it seems fair that R should also.  It's also shorter and more idiomatic of what a typical R programmer would do.

### CODE REVIEW

**Comment by kenahoo** [comment]
I accidentally introduced a whitespace error on the last line when I was using GitHub's web-based editor.  Obviously that shouldn't be included, want me to rebase/squash/something this to fix it?

**Comment by JeffBezanson** [comment]
> The pisum function in the Julia benchmarks uses a vectorized squaring & reciprocal operation on its indices

No it doesn't.

**Comment by yuyichao** [comment]
OTOH, `pisumvec` does, and does so in both.

**Comment by yuyichao** [comment]
And it seems that the `pisumvec` one (not used) should remove the `[]` around `1:10000` in the julia version.

**Comment by kenahoo** [comment]
Oops, sorry, since `pisumvec` isn't shown in the table on http://julialang.org/ , I didn't notice that it existed and I confused one for the other.

It looks like the difference between `pisumvec` in the two languages is that in R it constructs a 500-element vector and then throws away all but the first element, whereas in Julia it only saves the current element, and eventually returns it.  Probably a minor difference.

Sorry for the noise!

**Pull request closed without merging**
