### PR TITLE
Increase range of trunc/floor/ceil/round for BigFloat

### LINKED ISSUE #21914: truncating BigFloat results in InexactError at limits
```julia
julia> typemax(Int128)
170141183460469231731687303715884105727

julia> x = nextfloat(BigFloat(typemax(Int128)))
1.701411834604692317316873037158841057270000000000000000000000000000000000000015e+38

julia> trunc(Int128, x)
ERROR: InexactError()
 in trunc(::Type{Int128}, ::BigFloat) at ./mpfr.jl:133

julia> convert(Int128, trunc(BigInt, x))
170141183460469231731687303715884105727
```

### PR DESCRIPTION
**Pull request by omus**
Fixes #21914

### CODE REVIEW

**Comment by omus** [comment]
Would be nice to backport to 0.5

**Comment by omus** [comment]
Any comments? Ideas on how to get fix the limits on rounding is welcome.

**Comment by omus** [comment]
Figured out how to correctly set the range limit for RoundNearest and friends.

**Comment by simonbyrne** [comment]
My main objection is that this code requires allocating additional `BigFloat` objects. It would be good to get some benchmarks.

**Comment by omus** [comment]
> My main objection is that this code requires allocating additional BigFloat objects. It would be good to get some benchmarks.

I was under the false impression that comparing a `BigFloat` to another `Integer` type required promotion to a `BigFloat`. I should be able most of the new `BigFloat` allocations except for the `RoundingMode{:Nearest}` function.

**Comment by omus** [comment]
Replaced by: https://github.com/JuliaLang/julia/pull/33681

**Pull request closed without merging**
