### PR TITLE
Check stride on preallocated output for matmul (fixes #15286)

### LINKED ISSUE #15286: BLAS.gemm! with SubArray
BLAS.gemm! result values can be stored in subarray, but their indices seem to be wrong.
```julia
julia> A = rand(3, 3)
3x3 Array{Float64,2}:
 0.391348  0.99617   0.127584
 0.761283  0.364923  0.796806
 0.534478  0.201001  0.114469

julia> B = rand(3, 3)
3x3 Array{Float64,2}:
 0.471382   0.0389864  0.10348
 0.376755   0.52683    0.102277
 0.0756814  0.51072    0.119012

julia> C = zeros(6, 6)
6x6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

julia> sC = sub(C, 1:2:6, 1:2:6)
3x3 SubArray{Float64,2,Array{Float64,2},Tuple{StepRange{Int64,Int64},StepRange{Int64,Int64}},1}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> BLAS.gemm!('N', 'N', 1.0, A, B, 0.0 ,sC)
3x3 SubArray{Float64,2,Array{Float64,2},Tuple{StepRange{Int64,Int64},StepRange{Int64,Int64}},1}:
 0.569442  0.605229  0.157565
 0.336335  0.185192  0.0894885
 0.0       0.0       0.0

julia> C
6x6 Array{Float64,2}:
 0.569442  0.0  0.605229  0.0  0.157565   0.0
 0.556645  0.0  0.628877  0.0  0.21093    0.0
 0.336335  0.0  0.185192  0.0  0.0894885  0.0
 0.0       0.0  0.0       0.0  0.0        0.0
 0.0       0.0  0.0       0.0  0.0        0.0
 0.0       0.0  0.0       0.0  0.0        0.0

```

my `versioninfo()`

```
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY HASWELL)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by timholy**
CC @andreasnoack, @machiningcentre

### CODE REVIEW

**Comment by timholy** [comment]
Easy-click link: #15286.

**Comment by tkelman** [comment]
LGTM. Andreas?

(aside: BLIS https://github.com/flame/blis would allow arbitrary strides here)

**Comment by andreasnoack** [comment]
@tkelman We allow arbitrary strides so I'm wondering how much speedup BLIS can get on matrices with special strides.

**Comment by tkelman** [comment]
Yeah, it depends on how well optimized the non unit stride case is in BLIS relative to the julia generic gemm. Probably not commonly benchmarked but worth trying.

**Comment by timholy** [comment]
When strides get so big that there's only 1 element per cache line, I suspect the best performance might be achieved by copying (which essentially compacts the data).

**Comment by tkelman** [comment]
I believe BLIS does copy for the non unit stride case in order to still use optimized simd operations, but only one panel at a time rather than the entire array. Should reread their papers and code though. On typical dgemm their haswell kernels are quite competitive with openblas and mkl.

**Comment by timholy** [comment]
Interesting. I'd be surprised if we couldn't someday match them in pure julia with `@threads` and vectorization, but we aren't there yet.

**Comment by tkelman** [comment]
Yeah, the basic code generation patterns they do would all translate naturally into Julia style code generation (nicer, actually, since they're leaning heavily on the c preprocessor), and we could use their kernels as inline llvm or asm. Some day.

**Pull request merged**
