### PR TITLE
bump utf8proc to 2.1.1

### PR DESCRIPTION
**Pull request by stevengj**
This contains a bug fix for a serious normalization error (JuliaLang/utf8proc#128), so I would recommend backporting to all releases that we still support which use utf8proc 2.0 or later.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks for pinging me. I've updated utf8proc to 2.1.1 in all supported Fedora releases.

BTW, the Fedora tools spotted ABI changes since 2.1.0. Are these expected? https://taskotron.fedoraproject.org/artifacts/all/2bad844c-4a2c-11e8-b912-525400fc9f92/tests.yml/utf8proc-2.1.1-1.fc27.log

**Comment by KristofferC** [comment]
Can we test the correct behavior in julia itself?

**Comment by ginggs** [comment]
@stevengj thanks for the ping, also.  Any plans to switch to Unicode 10?

**Comment by stevengj** [comment]
@nalimilan, there haven't been any header-file changes except for JuliaLang/utf8proc#94 and JuliaLang/utf8proc#131, neither of which should have changed the ABI, so I'm a bit confused.

**Comment by stevengj** [comment]
@nalimilan, ah, that is due to JuliaLang/utf8proc#100.  That PR removed a couple of unintentional exports.  Strictly speaking, this changes the ABI, but only if people were somehow directly using these internal, undocumented variables.

**Comment by nalimilan** [comment]
OK. Could have been better to wait for a major release, as technically this could break existing programs, but in practice hopefully it should be fine.

**Comment by tkelman** [comment]
checksum files need to be updated for NO_GIT builds

**Comment by stevengj** [comment]
Updated the checksums.

**Comment by stevengj** [comment]
CI failures seem unrelated.  OSX failure is ``` failed process: Process(`curl ... ``` while Windows is giving `Error in testset download` and FreeBSD is `Warning: TerminalMenus: Unable to enter raw mode: ArgumentError("stream is closed or unusable")`.

Okay to merge?

**Comment by ararslan** [comment]
I think the download tests are due to a network failure on httpbin. Quoting Valentin in a different PR of his:

> CI is red because apparently httpbin.org got hit by a network fluke and that caused one test to fail across Circle, Travis, and Appveyor.

When in doubt you can restart CI.

**Comment by stevengj** [comment]
I restarted the OSX travis; I don't think I have permissions to restart the AppVeyor build?

**Comment by ararslan** [comment]
AppVeyor's permissions are a mess. I've restarted it for you.

**Comment by ararslan** [comment]
Both the 32- and 64-bit Windows builds timed out, and the FreeBSD build froze (cc @iblis17).

**Pull request merged**
