### PR TITLE
a more earnest attempt at renaming Void

### LINKED ISSUE #25082: rename Void => Nothing with alias Cvoid = Nothing
This was discussed previously a few times. The `Void` name only really makes sense in the context of interop with C, for which the name `Cvoid` is better. We have a pretty well-established convention that `name` is an element of type `Name` so `nothing :: Void` is a bit of a surprising gotcha. Way back when, this type was called `Nothing` but it was deemed that we had too many kinds of nothingness, but we're really jumped the shark on that at this point.

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Closes #25082.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
This is going to be massively conflict-prone, so I've separated it into the manual change to base/boot.jl which is fairly finicky and the automatic part that changes all the things.

**Comment by StefanKarpinski** [comment]
Ok, the real deal this time. Can be easily rebased since the large rename step is scripted.

**Comment by Sacha0** [comment]
(Would you like a manual review here, or are you confident in your transformations? :))

**Comment by StefanKarpinski** [comment]
I'm pretty sure this is correct, we just need to make a decision.

**Comment by JeffBezanson** [comment]
What I recall from when we had `Nothing` was that people would mistakenly use it instead of `nothing` fairly often. The similarity to python's `None` might contribute to this. Python also uses `NoneType` as the type of `None`, which helps avoid this confusion.

**Comment by StefanKarpinski** [comment]
If we have any other name ideas, it's pretty easy to change this since it's automated now. I still don't understand why `nothing :: Nothing` is uniquely problematic when we use that convention all the time. We're doing `missing :: Missing` now, for example, so this is fairly well established. Perhaps it's because back then using `Nothing` instead of `nothing` often ended up working since they're both singletons and we were never using the value for anything except it's special printing in the REPL. Now we are – and passing `Nothing` where `nothing` is expected will fail, so I suspect that issue is probably already resolved. Calling the type of `None` something long like `NoneType` in Python is a bit more palatable since you don't use types much. We have to write `Nothing` pretty often.

**Comment by JeffBezanson** [comment]
There are very few cases where a value and its type have the same name except for case. There are several pairs, like `filter` and `Filter`, or `adjoint` and `Adjoint`, where the two names have a different relationship, typically a function and the type of value it returns.

**Comment by StefanKarpinski** [comment]
There's an awful lot of support for this rename on the original issue – and a bit of dissent, but it's unusually lopsided. Perhaps people who voted up or down over there can chime in here?

**Comment by helgee** [comment]
I concur with all arguments made in favor of the rename in the original issue and I want to add that `Void` is a very jargony term in my opinion. It is an uncommon word and many non-native speakers will encounter it the first time in the context of programming.

Calling it `Nothing` probably saves them a trip to the dictionary if they are learning programming with Julia and thus lowers the barrier of entry.

**Comment by nalimilan** [comment]
I think `Nothing` particularly improves clarity in docstrings where `::Union{T, Void}` parameters and return values don't currently evoke the object `nothing` at all. The consistency with `Missing` is also really appealing.

**Comment by rfourquet** [comment]
I like terseness, so it's hard for me to support officially this rename, considering this evolution in length:
+ `Nullable{Int}`
+ `Union{Int,Void}`
+ `Union{Int,Nothing}`

But if I'm honest, I must admit to secretely hope `Nothing` will win, because it just feels right. `Void` by conflating two notions, is inconsistent in naming with both `nothing` and C's `void`. `Nothing` plus the `Cvoid` alias seems the least surprising on both fronts. And maybe we will have something like a `Maybe{Int} = Union{Int,Nothing}` type anyway for terseness :)

**Comment by JeffBezanson** [comment]
Ok, I'm not really set against this. The arguments for it are pretty reasonable.

We should certainly have a shorter way to write `Union{T,Nothing}`.

**Comment by StefanKarpinski** [comment]
Ready to go when CI passes.

**Comment by StefanKarpinski** [comment]
MacOS timeout; everything else has passed (again).

**Comment by ararslan** [comment]
> Perhaps people who voted up or down over there can chime in here?

For whatever it's worth, I was one of the few dissenters, and I admit that `Cvoid` in `ccall` seems pretty nice. I actually dislike the trend of a singleton value `thing` having type `Thing` (and I rather like the name `Void`), which is mostly why I didn't like the proposal, but if we have a shorter way to write `Union{T, Nothing}` then that solves a significant portion of that concern for me.

**Comment by Sacha0** [comment]
> Perhaps people who voted up or down over there can chime in here?

Crossposting the relevant bit I posted in support:

>The relationship between nothing and Void confused me when I came to Julia, and these changes completely eliminate that source of confusion. Additionally, I find the Ptr{Void} -> Ptr{Cvoid} changes beautifully clarifying as well. ❤️!

**Comment by quinnj** [comment]
I'd be in favor of making `T?` desugar to `Union{T, Nothing}`. I've come to think that this definition will be more used/common than a previously suggested idea of having it desugar to `Union{T, Missing}`. Not something we need to rush into though; we still need some time for all the `Union` improvements to ripple through the ecosystem.

**Comment by StefanKarpinski** [comment]
Let's see where there's more pain. Feel pain, apply syntax?

**Comment by vchuravy** [comment]
FemtoCleaner is going to have it's work cut out for it :P

**Comment by StefanKarpinski** [comment]
Eh, this is a dead easy one to automate (as proved by the PR itself).

**Comment by ararslan** [comment]
It's also now available in Compat.

**Pull request merged**
