### PR TITLE
turn on deprecation warnings for `type` and `immutable`

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by tkelman** [comment]
should probably backport the doc and test bits of this, obviously not the deprecation itself though

**Comment by JeffBezanson** [comment]
Commit split for that purpose.

**Comment by tkelman** [comment]
there was one more under examples that I fixed for you, squashed into the first commit

(backport pending only for that commit)

**Comment by KristofferC** [comment]
FWIW I updated https://gist.github.com/KristofferC/24c269727d914ffb88bfc21624dad891.

Run `update_folder!(folder::String)` to see what files that would be edited and then `update_folder!(folder, false)` to actually do the replacements. I did 
 https://github.com/KristofferC/NearestNeighbors.jl/pull/46 and https://github.com/KristofferC/Crayons.jl/pull/10 with the script.

**Comment by ararslan** [comment]
I probably would have waited until there's a 0.6 release so that packages can soundly require 0.6 without having to worry about 0.6-, which can include 0.6-dev pre-`struct`. ¯\\\_(ツ)\_/¯

**Pull request merged**
