### PR TITLE
Docs: Julia showing where it shouldn't

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by KristofferC** [comment]
What's wrong with the existing formulation?

**Comment by PallHaraldsson** [comment]
It's in the title, julia is showing. I think, it has to do with the indenting, it should function as some markup rule but it doesn't.

**Comment by KristofferC** [comment]
This is how it looks for me. Am I missing something obvious? 

IMG_20200906_234856

**Comment by remi-garcia** [comment]
It is not when you go in the docs but on the file on GitHub: [https://github.com/JuliaLang/julia/blob/master/doc/src/manual/modules.md](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/modules.md)
Screenshot from 2020-09-07 15-36-14

**Comment by remi-garcia** [comment]
Well, in the docs I simply don't have the "!!!note":
Screenshot from 2020-09-07 15-40-04

**Comment by fredrikekre** [comment]
GitHub just doesn't understand `!!!` admonitions.

> Well, in the docs I simply don't have the "!!!note":

https://docs.julialang.org/en/v1.6-dev/manual/modules/#Standard-modules

**Comment by KristofferC** [comment]
> Well, in the docs I simply don't have the "!!!note":

Are you looking at the latest development version of the docs?

**Comment by remi-garcia** [comment]
> > Well, in the docs I simply don't have the "!!!note":
> 
> Are you looking at the latest development version of the docs?

Sorry, I wasn't

**Comment by remi-garcia** [comment]
> GitHub just doesn't understand `!!!` admonitions.
> 
> > Well, in the docs I simply don't have the "!!!note":
> 
> https://docs.julialang.org/en/v1.6-dev/manual/modules/#Standard-modules

I know, sorry if I was misleading you. What @PallHaraldsson said was about the "julia using Test".

**Comment by KristofferC** [comment]
Well, it seems to look fine.

**Comment by remi-garcia** [comment]
It is on the docs but not on the GitHub site ([here](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/modules.md)), which is probably less important.

**Comment by KristofferC** [comment]
Yes, the docs are not written for the github renderer.

**Pull request closed without merging**
