### PR TITLE
proper diagonal in copytri! (fix #30055)

### LINKED ISSUE #30055: copy(UpperTriangular(A)') != UpperTriangular(A)'
Version 1.1.0-DEV.666 (2018-11-16)
Commit 25d0dfc398* (0 days old master)

As the title states: the copy is not equal to the source. The diagonal of the matrix in not copied correctly (`adjoint` missing).

The same behavior is found in Version 1.0.1 (2018-09-29) and probably in earlier versions.
```
julia> A = sparse([1+im 2+im 3+im; 4+im 5+im 6+im; 7+im 9+im 0])
3×3 SparseMatrixCSC{Complex{Int64},Int64} with 8 stored entries:
  [1, 1]  =  1+1im
  [2, 1]  =  4+1im
  [3, 1]  =  7+1im
  [1, 2]  =  2+1im
  [2, 2]  =  5+1im
  [3, 2]  =  9+1im
  [1, 3]  =  3+1im
  [2, 3]  =  6+1im

julia> Matrix(A)
3×3 Array{Complex{Int64},2}:
 1+1im  2+1im  3+1im
 4+1im  5+1im  6+1im
 7+1im  9+1im  0+0im

julia> UpperTriangular(A)'
3×3 Adjoint{Complex{Int64},UpperTriangular{Complex{Int64},SparseMatrixCSC{Complex{Int64},Int64}}}:
 1-1im  0+0im  0+0im
 2-1im  5-1im  0+0im
 3-1im  6-1im  0+0im

julia> copy(UpperTriangular(A)')
3×3 LowerTriangular{Complex{Int64},SparseMatrixCSC{Complex{Int64},Int64}}:
 1+1im    ⋅      ⋅  
 2-1im  5+1im    ⋅  
 3-1im  6-1im  0+0im
```

### PR DESCRIPTION
**Pull request by KlausC**
fix of https://github.com/JuliaLang/LinearAlgebra.jl/issues/586

### CODE REVIEW

**Comment by KlausC** [comment]
It's 4 weeks now and doesn't get better by waiting.... :-)

**Comment by StefanKarpinski** [comment]
bump: @andreasnoack & @KristofferC

**Review by andreasnoack — COMMENTED** [review]
I don't think `copytri!` is the right place to fix this. That function is correct as it is. It just leaves the diagonal which I think is fine. Instead, I'd modify https://github.com/JuliaLang/julia/blob/dffe119421157e4d55caf78801bb15b45b020e5d/stdlib/LinearAlgebra/src/triangular.jl#L349-L356 to also take care of the diagonal. Notice that also the `transpose` case is wrong for matrix elements.

**Comment by andreasnoack** [comment]
Alternatively, you could add an argument to `copytri!` to include the diagonal in the existing loop. That might actually be cleaner and it would automatically fix the `transpose` case as well.

**Comment by KlausC** [comment]
> Alternatively, you could add an argument to `copytri!` to include the diagonal in the existing loop. That might actually be cleaner and it would automatically fix the `transpose` case as well.

Done.
A variant of copytri! has now `Val`arguments to avoid runtime checks on the different arguments.
Also a test case for `transpose` was added.

**Comment by andreasnoack** [comment]
> A variant of `copytri!` has now Valarguments to avoid runtime checks on the different arguments.

This should no longer be necessary with constant propagation. Might need to be forcibly inlined, though.

**Comment by KlausC** [comment]
> This should no longer be necessary with constant propagation. Might need to be forcibly inlined, though.

In `v1.0.3` the output of `@code_warntype` is approximately twice of the current. `uplo` is typically a variable, not a constant, when calling `copytri!`.

**Comment by andreasnoack** [comment]
> In v1.0.3 the output of `@code_warntype` is approximately twice of the current.

It can be a bit tricky to get correct output from constant propagation with `@code_warntype`. How did you invoke it? You should try wrapping the call in a function with constant arguments to `copytri!`.

> `uplo` is typically a variable, not a constant, when calling `copytri!`.

The two other are and `uplo` is the outer branch so I don't think that one is critical.

**Comment by KlausC** [comment]
> You should try wrapping the call in a function with constant arguments to copytri!

I did `@code_warntype LinearAlgebra.copytri!(B, 'U', false)`. That showed the code with runtume checks for everything.

Now I tried
```
julia> foo(B) = LinearAlgebra.copytri!(B, 'U', false)
foo (generic function with 1 method)

@code_warntype foo(B)
Body::Array{Int64,2}
1 1 ─ %1 = LinearAlgebra.copytri!::Core.Compiler.Const(LinearAlgebra.copytri!, false)         │
  │   %2 = invoke %1(_2::Array{Int64,2}, 'U'::Char, false::Bool)::Array{Int64,2}              │
  └──      return %2 
```
That does not show and code from inside `copytri!`, because it is not inlined.

**Comment by andreasnoack** [comment]
Just tried it out locally and the propagation works fine if you just add `@inline`.

**Comment by KlausC** [comment]
Ok. I have now
`@inline copytri!(...., uplo::AbstractCharacter, conjugate::Boolean=false, diag::Boolean=false)`

**Review by andreasnoack — APPROVED** [review]

**Comment by andreasnoack** [comment]
Great. Thanks for fixing this. We can merge once tests pass.

**Comment by KlausC** [comment]
broken windows test run seems unrelated. All LinearAlgebra tests passed. maybe time-out afterwards.

**Comment by KlausC** [comment]
thanks for the review.

**Pull request merged**
