### PR TITLE
renamed (r/a)tol to (rel/abs)tol

### LINKED ISSUE #346: Consistent name for absolute and relative tolerance
In Base there are two conventions for specifying the tolerance parameters:

`quadgk` and use `stebz!` use `abstol`/`reltol` convention

whereas `isapprox` uses `atol`/`rtol`

In JuliaLang projects like `ODE.jl` the `abstol`/`reltol` is followed
whereas `IterativeSolvers.jl`, `Roots.jl` uses the `atol`/`rtol` convention

This is such a common set of parameter names for adaptive/iterative/approximate numerical methods it would be really nice to have a consistent convention put forward by the Julia community to follow. As this will be breaking it would be nice, at a minimum, in the style guide so future projects can aim for consistency.

### LINKED ISSUE #17322: Consistent name for absolute and relative tolerance
In Base there are two conventions for specifying the tolerance parameters:

`quadgk` and use `stebz!` use `abstol`/`reltol` convention

whereas `isapprox` uses `atol`/`rtol`

In JuliaLang projects like `ODE.jl` the `abstol`/`reltol` is followed
whereas `IterativeSolvers.jl`, `Roots.jl` uses the `atol`/`rtol` convention

This is such a common set of parameter names for adaptive/iterative/approximate numerical methods it would be really nice to have a consistent convention put forward by the Julia community to follow. As this will be breaking it would be nice, at a minimum, in the style guide so future projects can aim for consistency.

### PR DESCRIPTION
**Pull request by ArunS-tack**
Initial attempt to close JuliaLang/LinearAlgebra.jl#346.

### CODE REVIEW

**Comment by ArunSanganal** [comment]
should the name be changed in test files as well?

**Comment by stevengj** [comment]
This is a breaking change, so it cannot be merged in Julia 1.x.

It would be better for other packages to follow Base's lead and use `rtol`/`atol` here.

**Comment by stevengj** [comment]
Alternatively, we could support both names in `isapprox`, which is a bit ugly but would not be breaking.  I'd rather just leave it as-is, however.

**Comment by ArunSanganal** [comment]
It's not really breaking, the tests have probably failed because of deprecation message. I have allowed both `a/r tol` and `abs/rel tol` to be used but with a deprecation message.

**Comment by ArunSanganal** [comment]
So, finally what's to be done here?

**Comment by yuyichao** [comment]
At least I think you are missing quite a few aliases so this as it is now is still breaking.

Also, you seems to be doing a straight search and replace and some of the doc string changes doesn’t make sense.

**Comment by ArunSanganal** [comment]
Yes, I didn't attempt to change all of them, or infact most of them as I wanted to get a review first.

**Comment by ArunSanganal** [comment]
>  some of the doc string changes doesn’t make sense.

Which ones?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/41387/files#diff-d7994789f13ec8a5b9800e2d684f99075c83ec7374542832b04ea45c33f80cb0R984

**Comment by vtjnash** [comment]
I agree with stevengj that it is just not worth the deprecation churn at this point. Sorry!

**Pull request closed without merging**
