### PR TITLE
codegen cleanup attempt: use memcpy for field loads and stores

### PR DESCRIPTION
**Pull request by vtjnash**
Previously, we always used LoadInst and StoreInst to deal with fields (except where we could keep them as a GEP), even if that meant we were dealing with FCA (which we would immediately spill back onto the stack). This uses a direct stack copy instead for all supported cases (FCA without tracked pointers).

### CODE REVIEW

**Comment by vtjnash** [comment]
for an example of why LLVM seems to prefer this pattern:
```llvm
julia> @code_llvm debuginfo=:none f(Ref((1,2,3)))
define void @julia_f_1328([3 x i64]* noalias nocapture sret([3 x i64]) %0, {}* nonnull align 8 dereferenceable(24) %1) #0 {
top:
  %2 = bitcast {}* %1 to [3 x i64]*
  %3 = bitcast {}* %1 to <2 x i64>*
  %4 = load <2 x i64>, <2 x i64>* %3, align 8
  %.elt5 = getelementptr inbounds [3 x i64], [3 x i64]* %2, i64 0, i64 2
  %.unpack6 = load i64, i64* %.elt5, align 8
  %5 = bitcast [3 x i64]* %0 to <2 x i64>*
  store <2 x i64> %4, <2 x i64>* %5, align 8
  %.sroa.3.0..sroa_idx2 = getelementptr inbounds [3 x i64], [3 x i64]* %0, i64 0, i64 2
  store i64 %.unpack6, i64* %.sroa.3.0..sroa_idx2, align 8
  ret void
}
julia> @code_native debuginfo=:none dump_module=false f(Ref(Maybe(1,true)))
        .text
        movq    %rdi, %rax
        movb    8(%rsi), %cl
        movq    (%rsi), %rdx
        movq    %rdx, (%rdi)
        movb    %cl, 8(%rdi)
        retq
```
after
```llvm
julia> @code_llvm debuginfo=:none f(Ref((1,2,3)))
define void @julia_f_292([3 x i64]* noalias nocapture sret([3 x i64]) %0, {}* nonnull align 8 dereferenceable(24) %1) #0 {
top:
  %2 = bitcast {}* %1 to i8*
  %3 = bitcast [3 x i64]* %0 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* noundef nonnull align 8 dereferenceable(24) %3, i8* noundef align 1 dereferenceable(24) %2, i64 24, i1 false)
  ret void
}
julia> @code_native debuginfo=:none dump_module=false f(Ref(Maybe(1,true)))
        .text
        movq    %rdi, %rax
        vmovups (%rsi), %xmm0
        vmovups %xmm0, (%rdi)
        retq
        nopl    (%rax)
```

**Comment by chriselrod** [comment]
For fun...
PR:
```julia
julia> @time using LoopVectorization
  2.202143 seconds (5.51 M allocations: 361.684 MiB, 2.53% gc time, 27.68% compilation time: 70% of which was recompilation)

julia> using StaticArrays

julia> M=K=N=15; A = @SMatrix(rand(M,K)); B = @SMatrix(rand(K,N));

julia> @inline function AmulB(A::SMatrix{M,K,T}, B::SMatrix{K,N,S}) where {M,K,N,S,T}
         SMatrix(AmulB!(MMatrix{M,N,promote_type(T,S)}(undef), A, B))
       end
AmulB (generic function with 1 method)

julia> @inline function AmulB!(C, A, B)
         @inbounds for i ∈ eachindex(C); C[i] = zero(eltype(C)); end
         @inbounds for n ∈ axes(C,2), k ∈ axes(B,1), m ∈ axes(C,1)
           @fastmath C[m,n] += A[m,k] * B[k,n]
         end
         return C
       end
AmulB! (generic function with 1 method)

julia> @inline function AmulB_turbo!(C, A, B)
         @inbounds for i ∈ eachindex(C); C[i] = zero(eltype(C)); end
         @turbo for n ∈ axes(C,2), k ∈ axes(B,1), m ∈ axes(C,1)
           C[m,n] += A[m,k] * B[k,n]
         end
         return C
       end
AmulB_turbo! (generic function with 1 method)

julia> @inline function AmulB_turbo(A::SMatrix{M,K,T}, B::SMatrix{K,N,S}) where {M,K,N,S,T}
         SMatrix(AmulB_turbo!(MMatrix{M,N,promote_type(T,S)}(undef), A, B))
       end
AmulB_turbo (generic function with 1 method)

julia> @benchmark AmulB($(Ref(A))[], $(Ref(B))[])
BenchmarkTools.Trial: 10000 samples with 175 evaluations.
 Range (min … max):  611.766 ns … 844.194 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     613.109 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   614.314 ns ±   5.370 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▂▄▆███▆▄▁                                   ▁▂▃▃▃▂▂▁▁        ▂
  ▆█████████▇▅▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▅▇█████████████████ █
  612 ns        Histogram: log(frequency) by time        626 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark AmulB_turbo($(Ref(A))[], $(Ref(B))[])
BenchmarkTools.Trial: 10000 samples with 784 evaluations.
 Range (min … max):  161.139 ns … 217.055 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     162.301 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   162.417 ns ±   1.396 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

     ▂   ██   ▅    █ ▅▁
  ▄▂▁█▂▄▃██▄▂▅█▄▄▂▃█▄██▂▇▂▆▆▅▂▃▁▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▂▃▂▂▂ ▃
  161 ns           Histogram: frequency by time          165 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
Julia 1.7:
```julia
julia> @benchmark AmulB($(Ref(A))[], $(Ref(B))[])
BenchmarkTools.Trial: 10000 samples with 139 evaluations.
 Range (min … max):  711.374 ns … 971.324 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     712.719 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   714.072 ns ±   5.164 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▃▆███▇▅▂                                    ▁▁▂▃▃▃▂▁         ▂
  ▇████████▆▃▁▁▁▁▁▃▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▇▇███████████▇█▇▆▇ █
  711 ns        Histogram: log(frequency) by time        729 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark AmulB_turbo($(Ref(A))[], $(Ref(B))[])
BenchmarkTools.Trial: 10000 samples with 478 evaluations.
 Range (min … max):  222.623 ns … 327.312 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     223.525 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   224.257 ns ±   2.185 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

       █▇▂▄
  ▂▂▃▄▇████▇▃▄▅▆▃▃▃▃▃▃▃▃▄▄▄▆▇▅▂▂▁▁▁▂▁▂▂▂▂▂▂▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  223 ns           Histogram: frequency by time          229 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
Code size is of course much smaller on this PR.
There are memcopies that should be elided by the compiler, but they're fully unrolled on Julia 1.7, while on master they're calls to `memset` and `memcpy`, which apparently runs a lot faster while also yielding smaller code.

Oddly, these timings are not reproducible under LinuxPerf.
Running 20_000_000 in a `foreach` loop, and `@turbo` version takes an average of 130/135 ns on PR/Julia 1.7, while the `@inbounds @fastmath` version takes 725/565 ns, i.e. is faster on 1.7 than on the PR, the opposite of what is reported by `@benchmark`.

The `@turbo` version executes about 225 more instructions/call on this PR, of which about 30 are branches, but gets better instructions per clock. The `memset` and `memcpy` are presumably scalar loops at this size.

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45606#issuecomment-1151493475) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/93541e5_vs_bd26069/report.md).

**Comment by vtjnash** [comment]
This likely should not have been squashed, since it will cause problems for anyone who needs to bisect or backport this

**Pull request merged**
