### PR TITLE
Filter out not available packages

### LINKED ISSUE #12680: Pkg.available lists un-installable packages
On current master:
```jl
julia> "Bebop" in Pkg.available()
true

julia> Pkg.add("Bebop")
ERROR: ErrorException("Bebop can't be installed because it has no versions that support 0.4.0-dev+6807 of julia. You may need to update METADATA by running `Pkg.update()`")
```

"Bebop" only runs on 0.2 and 0.3: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/Bebop/versions/0.0.1/requires

(Similary, "AxisAlgorithms" is in Pkg.available() on 0.3, but requires 0.4-. But probably a backport is overkill here.)

### PR DESCRIPTION
**Pull request by wildart**
This PR fixes #12680 by filtering out not available packages.

### CODE REVIEW

**Comment by tkelman** [comment]
How hard would it be to add a test for this in `test/pkg.jl` ?

**Comment by wildart** [comment]
I guess we need mini METADATA for testing purposes.

**Comment by kshyatt** [comment]
>I guess we need mini METADATA for testing purposes.

I told @StefanKarpinski I would try to do this but I might not get around to it for a while, if someone wants to take up the mantle.

**Comment by wildart** [comment]
@kshyatt It is definitely required. Current `Pkg` test coverage quite insufficient, partly because we test against one package in production METADATA. We could create a separate branch for testing purposes and fill it with various test caes, no need for a complete repository.

**Comment by kshyatt** [comment]
@wildart I gave this a try in https://github.com/JuliaLang/julia/pull/12710 - do you have thoughts on that?

**Comment by wildart** [comment]
Well, I meant separate brunch not a current temporary cloned snapshot. More in #12710 thread.

**Pull request merged**
