### PR TITLE
small change to type intersection that fixes #20344

### LINKED ISSUE #20344: StackOverflow in type inference
This is a pretty nifty one that @andreasnoack ran into. Probably related to #20103, but doesn't seem exactly the same.

To reproduce, checkout https://github.com/JuliaStats/Distributions.jl/commit/3e8d9f946b44a99a182ad176c5c365f43f1f83bd and https://github.com/JuliaDiff/ForwardDiff.jl/commit/791cd934166d6dd03705a79d2f346802268636ba (at the time of writing, these are both the head of the master branches of these packages).

Then, run the following: 

```julia
julia> using Distributions

julia> using ForwardDiff

julia> tmp1 = vcat([1,1], 1, 1)
WARNING: An error occurred during inference. Type inference is now partially disabled.
StackOverflowError()
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
intersect_ufirst at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1032 [inlined]
intersect_var at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1100
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
intersect_ufirst at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1032 [inlined]
intersect_var at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1100
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
⋮ # stacktace repeats for a while until it bubbles back up out of the recursion
4-element Array{Int64,1}:
 1
 1
 1
 1
```

The best part is that this bug can be circumvented by commenting out `Base.zero` and `Base.one` definitions on lines 132 and 135 [here](https://github.com/JuliaDiff/ForwardDiff.jl/blob/791cd934166d6dd03705a79d2f346802268636ba/src/dual.jl#L132).

versioninfo: 

```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2478
Commit dbf41c0 (2017-01-30 18:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
I'm not sure how comprehensive this is but it fixes the example reported in #20344.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Great. I just tried this and it fixes the failures in StaticArrays and Distributions.

**Comment by tkelman** [comment]
does it fix @nanosoldier `runbenchmarks(ALL, vs = ":master")` ?

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20448#issuecomment-277432282):
```
NanosoldierError: failed to run benchmarks against primary commit: ErrorException("failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]")
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3608457863a592f364f8b691f50135a9c04ecee7/11a3a72_vs_e480969/report.md)
cc @jrevels

**Comment by andreasnoack** [comment]
It appears that the removal of the deprecations has broken Nanosoldier and Requests

https://github.com/JuliaCI/Nanosoldier.jl/pull/27
https://github.com/JuliaWeb/Requests.jl/pull/147

**Comment by nalimilan** [comment]
Also fixes the `StackOverflow` error when loading CategoricalArrays.

**Comment by mlubin** [comment]
Also fixes the crash in JuMP

**Pull request merged**
