### PR TITLE
acquire the codegen lock as a more frequent lock

### PR DESCRIPTION
**Pull request by vtjnash**
the codegen lock is being overused here, but otherwise,
it is deadlock-prone, since the code design here is too arbitrarily
recursive to ensure these are being acquired in the right order

### CODE REVIEW

**Comment by tkelman** [comment]
is there a reliable (or even intermittent) test we could add that formerly deadlocked?

**Comment by yuyichao** [comment]
https://github.com/yuyichao/explore/blob/9b8895c588d11d29731520eb8bf47ddbff35d2ab/julia/gc_thread/gc-thread.jl

**Comment by tkelman** [comment]
Can we put that, or something derived from it, here so it runs regularly and we notice if a deadlock starts happening again?

**Comment by tkelman** [comment]
no backport to 0.5 needed, this was merged before we branched

**Pull request merged**
