### PR TITLE
a couple more backports of changes in #17057 that don't require new worlds

### PR DESCRIPTION
**Pull request by vtjnash**
trying to cut down on the diff a bit & bugfixes on the wrong branch

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18811#issuecomment-251942616) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/5f700e4be87feae1a30f3aadd4db045e8f8bebe7/e47e295_vs_121cae3/report.md). cc @jrevels

**Comment by vtjnash** [comment]
I assume those benchmarks are just noisy? I don't see it locally. Travis OSX just ran out of time, so good to merge?

**Comment by andreasnoack** [comment]
Tried the Laplacian benchmark locally on this branch and I didn't see the regression either.

**Pull request merged**
