### PR TITLE
Fix bug and add tests for Bidiagonal

### PR DESCRIPTION
**Pull request by kshyatt**
this `x` variable was undefined. Also added some tests.

### CODE REVIEW

**Review by andreasnoack — APPROVED** [review]

**Review by dkarrasch — APPROVED** [review]

**Comment by KristofferC** [comment]
Backport?

**Comment by kshyatt** [comment]
If you like, I don't see a reason not to but I'm not current with the release schedule

**Comment by KristofferC** [comment]
Sorry, what I mean was, is it also applicable to earlier releases or is it something new. If it is applicable, it should ideally be backported since it is a bugfix.

**Comment by dkarrasch** [comment]
No need to backport. The bug was introduced in #41297 by me.

**Pull request merged**
