### PR TITLE
Update and extend the documentation of expm, logm and sqrtm

### PR DESCRIPTION
**Pull request by mfasi**
Documentation update originally in #12408, moved here after #11943 was merged.

### CODE REVIEW

**Comment by tkelman** [comment]
I think docstrings actually need to change in helpdb.jl now, not in the rst. But please stand by for an announcement on that.

**Comment by mfasi** [comment]
@tkelman OK, thank you. No problem, I just wanted to avoid having documentation and consistency together, as the latter seems to need some more work. Now that I can keep them separate I'm happy.

**Comment by tkelman** [comment]
The docs for `expm` now live here - https://github.com/JuliaLang/julia/blob/7023fc3ea7d35afafe24d6b0ad40b280e37d369f/base/docs/helpdb.jl#L10748-L10755

`sqrtm` and `logm` should live somewhere else in the file, but I believe it should be safe right now to move the docstrings to the location of those functions' source. You can run `./julia doc/genstdlib.jl` to see what the generated rst docs should look like.

**Comment by mfasi** [comment]
@tkelman Maybe something's not working properly yet. By running `./julia doc/genstdlib.jl` I get something like

```
INFO: no docs for Base.ndims
INFO: no docs for Base.size
INFO: no docs for Base.iseltype
INFO: no docs for Base.length
INFO: no docs for Base.eachindex
INFO: no docs for Base.Base.linearindexing
INFO: no docs for Base.countnz
INFO: no docs for Base.conj!
INFO: no docs for Base.stride
INFO: no docs for Base.strides
INFO: no docs for Base.ind2sub
...
```
and the .rst files are not changed.

**Comment by tkelman** [comment]
I think those warnings are normal, but the rst files should be changing. Not sure what's up there.

**Comment by mfasi** [comment]
@tkelman I figured out what I did wrong: each time you change something in `base/docs/helpdb.jl`, you have to recompile julia before running `./julia doc/genstdlib.jl`. Anyway, the generated documentation looks fine, feel free to merge this PR.

**Comment by ViralBShah** [comment]
I think this deserves a mention in NEWS.

**Pull request merged**
