### PR TITLE
add `@_propagate_inbounds_meta` to `Array` indexing methods so `@inbounds` isn't placebo

### PR DESCRIPTION
**Pull request by oscardssmith**
Found by @chriselrod. Tagging jameson for review since I have a sneaking suspicion he might have intentionally not added them.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
What are you propagating / what is it propagating too?

**Comment by chriselrod** [comment]
On Julia 1.11-beta1, `@inbounds` does not remove bounds checks when indexing `Array`s.

**Comment by chriselrod** [comment]
> But that is already called with inbounds, so why do you need to specify it twice?

Are you referring to a specific change in this PR?

```julia
julia> function mydot_inbounds2(x,y)
           acc = zero(eltype(x))
           @inbounds for i = eachindex(x,y)
                @inbounds acc += x[i,1]*y[i]
           end
           acc
       end
mydot_inbounds2 (generic function with 1 method)

julia> @code_typed mydot_inbounds2(Float64[],Float64[])
```
is a reproducer showing 3 boundschecks in the loop.

**Comment by oscardssmith** [comment]
For a simpler example,
```
julia> f(v) = @inbounds v[1]
f (generic function with 1 method)

julia> @code_typed f([1,2,3])
CodeInfo(
1 ─ %1  = $(Expr(:boundscheck, false))::Bool
└──       goto #5 if not %1
2 ─ %3  = Base.sub_int(1, 1)::Int64
│   %4  = Base.bitcast(Base.UInt, %3)::UInt64
│   %5  = Base.getfield(v, :size)::Tuple{Int64}
│   %6  = $(Expr(:boundscheck, true))::Bool
│   %7  = Base.getfield(%5, 1, %6)::Int64
│   %8  = Base.bitcast(Base.UInt, %7)::UInt64
│   %9  = Base.ult_int(%4, %8)::Bool
└──       goto #4 if not %9
3 ─       goto #5
4 ─ %12 = Core.tuple(1)::Tuple{Int64}
│         invoke Base.throw_boundserror(v::Vector{Int64}, %12::Tuple{Int64})::Union{}
└──       unreachable
5 ┄ %15 = Base.getfield(v, :ref)::MemoryRef{Int64}
│   %16 = Base.memoryref(%15, 1, false)::MemoryRef{Int64}
│   %17 = Base.memoryrefget(%16, :not_atomic, false)::Int64
└──       goto #6
6 ─       return %17
) => Int64
```

**Comment by vtjnash** [comment]
There is no bounds checking in that code

**Comment by oscardssmith** [comment]
Isn't
```
│   %9  = Base.ult_int(%4, %8)::Bool
└──       goto #4 if not %9
```
a bounds-check?

**Comment by jakobnissen** [comment]
I don't see boundschecks in any of the two examples on Julia 1.11-beta1. Yes, the typed code contains a boundscheck, but it's inside a branch statically known to be false:
```julia
julia> f(v) = @inbounds v[1];

julia> @code_typed f([1,2,3])
CodeInfo(
1 ─ %1  = $(Expr(:boundscheck, false))::Bool
└──       goto #5 if not %1       <---- this goto skips all the bounds checking code
```
And `@code_native` verifies no bounds checking happens. Same in @chriselrod's example which even vectorizes nicely when `@inbounds @simd` is used.

**Comment by chriselrod** [comment]
The code does NOT vectorize for me:
```julia
julia> function mydot_inbounds2(x,y)
           acc = zero(eltype(x))
           @inbounds for i = eachindex(x)
                @inbounds acc += x[i,1]*y[i]
           end
           acc
       end
mydot_inbounds2 (generic function with 1 method)

julia> @code_native debuginfo=:none syntax=:intel mydot_inbounds2(Float64[],Float64[])
```
```asm
julia> @code_native syntax=:intel debuginfo=:none mydot_inbounds2(Float64[], Float64[])
	.text
	.file	"mydot_inbounds2"
	.globl	julia_mydot_inbounds2_6261      # -- Begin function julia_mydot_inbounds2_6261
	.p2align	4, 0x90
	.type	julia_mydot_inbounds2_6261,@function
julia_mydot_inbounds2_6261:             # @julia_mydot_inbounds2_6261
; Function Signature: mydot_inbounds2(Array{Float64, 1}, Array{Float64, 1})
# %bb.0:                                # %top
	#DEBUG_VALUE: mydot_inbounds2:x <- [DW_OP_deref] $rdi
	#DEBUG_VALUE: mydot_inbounds2:y <- [DW_OP_deref] $rsi
	#DEBUG_VALUE: mydot_inbounds2:y <- [DW_OP_deref] 0
	#DEBUG_VALUE: mydot_inbounds2:x <- [DW_OP_deref] 0
	push	rbp
	mov	rbp, rsp
	mov	r8, qword ptr [rdi + 16]
	test	r8, r8
	jle	.LBB0_1
# %bb.2:                                # %L13.preheader
	mov	rcx, qword ptr [rdi]
	mov	rdx, qword ptr [rsi]
	mov	eax, r8d
	and	eax, 7
	cmp	r8, 8
	jae	.LBB0_4
# %bb.3:
	vxorpd	xmm0, xmm0, xmm0
	mov	esi, 1
	test	rax, rax
	jne	.LBB0_8
	jmp	.LBB0_10
.LBB0_1:
	vxorps	xmm0, xmm0, xmm0
	pop	rbp
	ret
.LBB0_4:                                # %L13.preheader.new
	and	r8, -8
	vxorpd	xmm0, xmm0, xmm0
	xor	esi, esi
	.p2align	4, 0x90
.LBB0_5:                                # %L13
                                        # =>This Inner Loop Header: Depth=1
	vmovsd	xmm1, qword ptr [rcx + 8*rsi]   # xmm1 = mem[0],zero
	vmovsd	xmm2, qword ptr [rcx + 8*rsi + 8] # xmm2 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi]
	vaddsd	xmm0, xmm0, xmm1
	vmulsd	xmm1, xmm2, qword ptr [rdx + 8*rsi + 8]
	vaddsd	xmm0, xmm0, xmm1
	vmovsd	xmm1, qword ptr [rcx + 8*rsi + 16] # xmm1 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi + 16]
	vmovsd	xmm2, qword ptr [rcx + 8*rsi + 24] # xmm2 = mem[0],zero
	vmulsd	xmm2, xmm2, qword ptr [rdx + 8*rsi + 24]
	vaddsd	xmm0, xmm0, xmm1
	vaddsd	xmm0, xmm0, xmm2
	vmovsd	xmm1, qword ptr [rcx + 8*rsi + 32] # xmm1 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi + 32]
	vaddsd	xmm0, xmm0, xmm1
	vmovsd	xmm1, qword ptr [rcx + 8*rsi + 40] # xmm1 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi + 40]
	vaddsd	xmm0, xmm0, xmm1
	vmovsd	xmm1, qword ptr [rcx + 8*rsi + 48] # xmm1 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi + 48]
	vmovsd	xmm2, qword ptr [rcx + 8*rsi + 56] # xmm2 = mem[0],zero
	vaddsd	xmm0, xmm0, xmm1
	vmulsd	xmm1, xmm2, qword ptr [rdx + 8*rsi + 56]
	vaddsd	xmm0, xmm0, xmm1
	add	rsi, 8
	cmp	r8, rsi
	jne	.LBB0_5
# %bb.6:                                # %L89.loopexit.unr-lcssa.loopexit
	inc	rsi
	test	rax, rax
	je	.LBB0_10
.LBB0_8:                                # %L13.epil.preheader
	lea	rdx, [rdx + 8*rsi]
	add	rdx, -8
	lea	rcx, [rcx + 8*rsi]
	add	rcx, -8
	xor	esi, esi
	.p2align	4, 0x90
.LBB0_9:                                # %L13.epil
                                        # =>This Inner Loop Header: Depth=1
	vmovsd	xmm1, qword ptr [rcx + 8*rsi]   # xmm1 = mem[0],zero
	vmulsd	xmm1, xmm1, qword ptr [rdx + 8*rsi]
	vaddsd	xmm0, xmm0, xmm1
	inc	rsi
	cmp	rax, rsi
	jne	.LBB0_9
.LBB0_10:                               # %L89
	pop	rbp
	ret
.Lfunc_end0:
	.size	julia_mydot_inbounds2_6261, .Lfunc_end0-julia_mydot_inbounds2_6261
                                        # -- End function
	.type	".L+Core.Float64#6263",@object  # @"+Core.Float64#6263"
	.section	.rodata,"a",@progbits
	.p2align	3, 0x0
".L+Core.Float64#6263":
	.quad	".L+Core.Float64#6263.jit"
	.size	".L+Core.Float64#6263", 8

.set ".L+Core.Float64#6263.jit", 140537863512432
	.size	".L+Core.Float64#6263.jit", 8
	.section	".note.GNU-stack","",@progbits
```
This is heavily unrolled, but totally scalar.

The boundschecks did disappear, however. Note that this isn't the same example as above: I wanted to (a) get rid of the `eachindex` error path, and (b) make sure that LLVM can't prove that `y[i]` does not throw.

**Comment by oscardssmith** [comment]
Closing this because it doesn't fix the issue, but there still is the issue that the boundscheck is staying around a lot longer (all the way through the Julia IR, and into LLVM IR until LLVM optimizes it out).

**Pull request closed without merging**
