### PR TITLE
Add checksums for LLVM 3.6.1

### PR DESCRIPTION
**Pull request by garrison**

### CODE REVIEW

**Comment by tkelman** [comment]
Should we get rid of the unused 3.5.x and 3.6.0 checksums? Also maybe bump the arm settings for good measure? Good news is it looks like both the patches we're carrying locally got backported properly to 3.6.0, though I don't think any of the other blocker issues are fixed between 3.6.1 vs 3.6.0.

**Comment by garrison** [comment]
If people should really only be using either 3.3 or 3.6.1, then those things make sense.  If 3.5.1 is also in the running, it may make sense to keep the checksums for it and also to add checksums for `cfe-3.5.1.src.tar.xz` and `compiler-rt-3.5.1.src.tar.xz`.  I cannot test ARM or PowerPC myself, but could always bump the versions under the assumption that they work.

**Comment by tkelman** [comment]
cfe and compiler-rt are completely optional, only a subset of people who are building julia will be downloading those at all

**Comment by garrison** [comment]
Sure, I added them simply because they are in the repository for llvm 3.3.

**Comment by garrison** [comment]
I think it makes sense to keep the 3.6.0 patches in the repository though -- somebody may still wish to compare behavior under 3.6.0 and 3.6.1 if they are tracking down a bug.

**Comment by tkelman** [comment]
Yeah it does make sense to keep the llvm 3.6.0 patches around locally for a little while longer, maybe until 3.7.0 is out and we try to start using that. I'm not sure what value there is in having checksums in the repo here for rarely-used versions or optional components of dependencies though.

**Comment by garrison** [comment]
I think it makes sense to have checksums of optional components -- a compromised/corrupted version of any of them is just as bad as a corrupt tarball in a core component for the people using the optional components.  I'd be fine with leaving out checksums for rarely-used versions though.

**Pull request merged**
