### PR TITLE
Revert "[LibGit2_jll] Update to v1.5.0"

### PR DESCRIPTION
**Pull request by DilumAluthge**
Reverts JuliaLang/julia#47382

This broke the once-daily scheduled "from source" CI job.

### CODE REVIEW

**Review by giordano — COMMENTED** [review]
I mentioned already in Slack that
```
make -C deps -j5 install-libgit2 USE_BINARYBUILDER_LIBGIT2=0 USE_BINARYBUILDER_LIBSSH2=0 USE_BINARYBUILDER_MBEDTLS=0 USE_CCACHE=1 VERBOSE=1
```
works locally for me in a fresh clone, so it isn't easy to tell what's wrong here.  Also, in Yggdrasil we didn't have to change the build script, only the patches (which were correctly updated in #47382): https://github.com/JuliaPackaging/Yggdrasil/compare/74712fc07e17bfd5f1dc7342bc8654f522fcb5e4...4993f24d91484fb3a6c689d0872789511164c1ce so I'm more and more confused about the failing build.

We can revert this, but without digging much further I don't have an explanation for the failure.  But we should also go back to v1.5.0 since it contains security fixes.

**Comment by DilumAluthge** [comment]
That same command fails in Buildkite. Example log: https://buildkite.com/julialang/julia-buildkite-scheduled/builds/348#01842f67-5fa9-4929-a627-fed585b7e2bf

So presumably there's something wrong with our build environment in Buildkite?

**Comment by DilumAluthge** [comment]
> But we should also go back to v1.5.0 since it contains security fixes.

Hmmm. If we need the security fixes, it might not be worth reverting, especially since this is just the from-source build. It might be better to just mark the from-source build as "allow fail".

**Comment by Keno** [comment]
It might work locally if you happen to have a local copy of mbedtls globally installed.

**Comment by giordano** [comment]
> I guess maybe the include path for mbedtls is missing?

Yes but I couldn't tell the difference with the output in the successful run.

**Comment by giordano** [comment]
> Yes but I couldn't tell the difference with the output in the successful run.

I couldn't because the CLI component (yes, libgit2 [has a CLI](https://github.com/libgit2/libgit2/tree/a3841af5eecc6301e87f8302c7fdce6555e39247/src/cli) now) was introduced in v1.5.0, and that's what is broken.  Fix in #47422 (simply don't build it, we don't need it anyway)

**Pull request closed without merging**
