### PR TITLE
linearize much of codegen

### PR DESCRIPTION
**Pull request by vtjnash**
We've long since stopped needing access to `expr_type` or having different sorts of `emit_expr` calls depending on the context. Now codegen can just emit arguments in order, ensuring that we never forget to emit side-effects or get ordering wrong.

In effect, this is also just demonstrating that the very-linear-IR mode switch won't have an effect on these functions, since we're avoiding using the structure of the AST to inform codegen decisions.

### CODE REVIEW

**Review by yuyichao — APPROVED** [review]

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by JeffBezanson** [comment]
Very nice. So nice to see codegen shrink for once :)

**Comment by vtjnash** [comment]
Yep, thanks. I've been promising for a long, long time that the codegen changes would eventually start to show code size/complexity reduction benefits. This is finally realizing some of it.

**Comment by yuyichao** [comment]
Rebased on top of https://github.com/JuliaLang/julia/pull/22734 at https://github.com/JuliaLang/julia/tree/yyc/jn/cg-linearize

**Comment by vtjnash** [comment]
Can you just push that to this branch? Nanosoldier shouldn't get impacted by having this branch changed while it's running.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22818#issuecomment-315557727) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/741f5a468367e2f7f8757f71ddaec462ee0435c9/cbfd30a_vs_2096248/report.md). cc @ararslan

**Comment by vtjnash** [comment]
OK to merge?

**Pull request merged**
