### PR TITLE
[doc] Add `HISTORY.md` to doc

### PR DESCRIPTION
**Pull request by inkydragon**
PDF looks good.
image

But the TOC of the HTML doc looks a bit strange:
image

### CODE REVIEW

**Comment by ViralBShah** [comment]
Yes, the heading levels in the NEWS and HISTORY always feel like they are one level higher than they need to be.

**Comment by inkydragon** [comment]
image

| Web page Box color | normal doc markdown            | PDF     | History.md             |
|--------------------|--------------------------------|---------|------------------------|
| red                | one dir                        | Part    | -                      |
| green              | one md file & Main Title (`#`) | Chapter | Main Title (`=====`)   |
| blue               | one section in md (`##`)       | Section | Secondary title (`-----`) |

Note: "normal doc" use [ATX heading](https://spec.commonmark.org/0.30/#atx-heading); and `History.md` use [setext heading](https://spec.commonmark.org/0.30/#setext-heading)

History.md
image

The main problem is that `History.md` contains too many Main Title. 
Normally, one `md` file can have only one Main Title.
A simpler way to do this is to split them into separate files by version.

But I prefer to downgrade the headers in `History.md` in order: `====` => `##`, `----` => `###`
so that although it seems to show only the Secondary title, but the `History.md` is still a whole document, so it is easy to search.


So let's discuss what to do with `History.md` and whether it is necessary to merge `NEWS.md` into it.

**Comment by ViralBShah** [comment]
The reason it has multiple main headers is that when we start a new release, we take NEWS.md and just paste it on top of HISTORY.md. Maybe we should have a script to do that, which does the necessary conversions.

**Comment by ViralBShah** [comment]
Yeah, I am no longer sure I want the full HISTORY. Perhaps just having a link in our NEWS to the full HISTORY would suffice - which would then also get included in this doc.

**Pull request closed without merging**
