### PR TITLE
Make QuickerSort efficient for non-homogonous eltype

### PR DESCRIPTION
**Pull request by LilithHafner**
Set `v[j] = pivot` in `partition!` rather than returning pivot to caller to make `partition!` type stable for non-concrete eltype

This is intended to address the regression in master vs 1.8 revealed by nanosoldier

["union", "array", ("sort", "Union{Nothing, Bool}", 0)] | 1.37 (5%) ❌ | 3.01 (1%) ❌
-- | -- | --

[[link to motivating benchmark results](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4d258ca_vs_61c0b41/report.md)]

### CODE REVIEW

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort", vs=":master")`
@nanosoldier `runbenchmarks("sort", vs=":release-1.8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47973#issuecomment-1363464467) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/571de2e_vs_ebeda7a/report.md).

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort", vs=":release-1.8")`

**Comment by LilithHafner** [comment]
Much better, though still not perfect

["union", "array", ("sort", "Union{Nothing, Bool}", 0)] | 1.00 (5%) | 1.33 (1%) ❌
-- | -- | --

With this and #47966 I believe all the BaseBenchmark regressions in runtime will be gone, though regressions in allocations will remain & some will not correspond to compensating improvements in runtime. Further, using https://github.com/JuliaCI/BaseBenchmarks.jl/pull/305 will also likely still show real regressions. I'll keep looking for regressions once this and #47966 merge.

I'll post here when I get the benchmark results from running https://github.com/JuliaCI/BaseBenchmarks.jl/pull/305 locally across this PR.

**Comment by LilithHafner** [comment]
Local tests reveal no regressions & memory improvements for "mixed eltype with by order"

**Comment by LilithHafner** [comment]
Bump

**Comment by LilithHafner** [comment]
This is orthogonal to #47966 so I'm not concerned about semantic merge conflicts

**Comment by LilithHafner** [comment]
Running nanosoldier here to search for possible remaining regressions to fix before we release 1.9

@nanosoldier `runbenchmarks("sort" vs=":release-1.8")`

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort", vs=":release-1.8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47973#issuecomment-1367419131) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/701206f_vs_00177eb/report.md).

**Comment by StefanKarpinski** [comment]
Is QuickerSort what you ended up calling your stable quicksort algorithm?

**Comment by LilithHafner** [comment]
Yes ([reasoning](https://github.com/JuliaLang/julia/pull/47788#issue-1473794118)); it is probably not too late to rename it if you have a better idea. ([nobody seems to be using it by name](https://juliahub.com/ui/Search?q=QuickerSort&type=code))

**Comment by StefanKarpinski** [comment]
I think calling it `StableQuickSort` would be a slightly less loaded choice, but I see you address that there. If I'm understanding the reasoning, it's that your modified quicksort is stable in its current form but could be modified to be still out of place but unstable and would do less work in that form, so there's a potential for a faster unstable variation of it, which would make the name "StableQuickSort" confusing. Is that correct?

**Comment by LilithHafner** [comment]
Precisely.

**Comment by StefanKarpinski** [comment]
I still think `StableQuickSort` would be ok since the most common version would be stable (you can almost always make something unstable somehow). Or maybe `QuickBufferSort`? But `QuickerSort` is ok too I guess.

**Comment by LilithHafner** [comment]
I prefer `QuickBufferSort` over `StableQuickSort`. I don't feel strongly either way between `QuickBufferSort` (proposed) and `QuickerSort` (current). If you or others feel strongly enough to rename it, I'd be happy to make a PR. It should be technically trivial.

**Pull request merged**
