### PR TITLE
Restoring get_num_threads function of BLAS

### PR DESCRIPTION
**Pull request by ryonghyun**
BLAS.get_num_threads function have been deleted by this commit https://github.com/JuliaLang/julia/commit/1da2c9bfe6f911c39f203bc1d5b7486a2420fdd8.

But, I can not find why, I think, I and other people also need this function by #15008.
And It already implemented by @tkelman before.

### CODE REVIEW

**Comment by martinholters** [comment]
Note this: https://github.com/JuliaLang/julia/blob/e05a921c45d613bea78f1564e8fae6ea619cca53/test/distributed_exec.jl#L1172-L1191

**Comment by tkelman** [comment]
IIRC the issue with this in openblas is that it returns the build time hard coded max number of threads, which is much less useful or expected than the run time dynamic number of threads setting.

**Comment by usefulhyun** [comment]
@tkelman , because in some case it returns the hard coded max number of threads, it have been deleted, is this right? Can I know anther option to replace this function?

**Comment by tkelman** [comment]
It would probably be more useful to look at the same environment variables that blas implmentations do

**Comment by antoine-levitt** [comment]
> @tkelman IIRC the issue with this in openblas is that it returns the build time hard coded max number of threads, which is much less useful or expected than the run time dynamic number of threads setting.

Has this not been fixed by https://github.com/xianyi/OpenBLAS/pull/762? At least here (0.6 and 0.7, linux openblas) it seems to work as expected. This PR should be re-opened as it seems like a useful functionality to have (if only for symmetry wrt set_num_threads)

**Comment by Jutho** [comment]
I am also in favour of reopening this. I think the MKL call needs to be
`mkl_get_max_threads` instead of `MKL_Get_Max_Num_Threads`.

One important use case I see, as multithreading in Julia is now more easy to use with `@spawn`, is that a package developer writes some code that implements an algorithm that uses multithreading at a higher level, and want to use single threaded matrix multiplication in the specific block of code ran on the different threads. So (s)he could do `BLAS.set_num_threads(1)` before the block of his own multithreaded code starts, but to restore `BLAS.set_num_threads(originalvalue)`, (s)he needs to be able to find out what the `originalvalue` of number of BLAS threads is.

**Pull request closed without merging**
