### PR TITLE
Add parallel marking to GC

### PR DESCRIPTION
**Pull request by jpsamaroo**
This is a first pass at multithreading parts of GC marking. The intended approach is simple: Store a "recruitment location" (function address) into a global, and have non-leader threads (those not running `_jl_gc_collect` directly) check for this global to be set to non-`NULL`. Threads that encounter a valid recruitment location will set their GC state to the new `JL_GC_STATE_PARALLEL` (name subject to change), and will call into the recruitment location. The only available recruitment function, `gc_mark_loop_recruited`, will put the thread to work in `gc_mark_loop`, assuming that the GC leader thread setup some work for this thread to do.

I'm posting this PR early because I need some help figuring out what I'm doing wrong. So far, the recruitment mechanism seems to work well, but I haven't figured out what things I need to setup for each thread before letting them enter the mark loop.

I've also got some code commented out, which would (presumably, if it worked) allow threads to steal work from each other. That's probably not required for this PR, but I started on it in case it might be useful.

N.B. I am bad at atomics, thread safety, and GC semantics, so please point out what terrible things I have done here!

@vchuravy @vtjnash

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@yuyichao what's the logic behind the check https://github.com/JuliaLang/julia/blob/5118a1babf9d2963f31e98e427cc99a969d5ca46/src/gc.c#L2706-L2707? I'm hitting this a lot, and I'm not sure I understand the reason why it can fail.

**Comment by yuyichao** [comment]
It just means that you are reading garbage somehow.

**Comment by ViralBShah** [comment]
Ok to close this?

**Comment by jpsamaroo** [comment]
@ViralBShah we have someone actively working on getting this PR up to date, who may end up pushing to this PR or another one (in which case we'll supersede this). I'd like to keep this open until that happens, just so people have something to watch for progress updates.

**Pull request closed without merging**
