### PR TITLE
Revert "add stream shutdown and support half-duplex operation"

### PR DESCRIPTION
**Pull request by DilumAluthge**
Reverts JuliaLang/julia#40783

This broke the tests on FreeBSD 12.

### CODE REVIEW

**Comment by ararslan** [comment]
This fixed the Sockets failure but unfortunately it didn't fix this one:
```
UNHANDLED TASK ERROR: EOFError: read end of file
Stacktrace:
 [1] (::Base.var"#wait_locked#651")(s::TCPSocket, buf::IOBuffer, nb::Int64)
   @ Base ./stream.jl:892
 [2] unsafe_read(s::TCPSocket, p::Ptr{UInt8}, nb::UInt64)
   @ Base ./stream.jl:900
 [3] unsafe_read
   @ ./io.jl:724 [inlined]
 [4] unsafe_read(s::TCPSocket, p::Base.RefValue{NTuple{4, Int64}}, n::Int64)
   @ Base ./io.jl:723
 [5] read!
   @ ./io.jl:725 [inlined]
 [6] deserialize_hdr_raw
   @ /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/messages.jl:160 [inlined]
 [7] message_handler_loop(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:165
 [8] process_tcp_streams(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:126
 [9] (::Distributed.var"#99#100"{TCPSocket, TCPSocket, Bool})()
   @ Distributed ./task.jl:411
```

**Comment by DilumAluthge** [comment]
> This fixed the Sockets failure but unfortunately it didn't fix this one:
> 
> ```
> UNHANDLED TASK ERROR: EOFError: read end of file
> Stacktrace:
>  [1] (::Base.var"#wait_locked#651")(s::TCPSocket, buf::IOBuffer, nb::Int64)
>    @ Base ./stream.jl:892
>  [2] unsafe_read(s::TCPSocket, p::Ptr{UInt8}, nb::UInt64)
>    @ Base ./stream.jl:900
>  [3] unsafe_read
>    @ ./io.jl:724 [inlined]
>  [4] unsafe_read(s::TCPSocket, p::Base.RefValue{NTuple{4, Int64}}, n::Int64)
>    @ Base ./io.jl:723
>  [5] read!
>    @ ./io.jl:725 [inlined]
>  [6] deserialize_hdr_raw
>    @ /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/messages.jl:160 [inlined]
>  [7] message_handler_loop(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
>    @ Distributed /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:165
>  [8] process_tcp_streams(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
>    @ Distributed /usr/home/julia/buildbot/w1_builder/package_freebsd64/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:126
>  [9] (::Distributed.var"#99#100"{TCPSocket, TCPSocket, Bool})()
>    @ Distributed ./task.jl:411
> ```

This is the segfault we've been seeing on FreeBSD 12. I have core dumps. If we build Julia with debug symbols, I can use the core dump to get the backtrace.

**Comment by ararslan** [comment]
Can you remind me how it was you determined that the cause was a segfault? It doesn't show any signs of a segfault in the buildbot log, but I seem to recall you seeing in a system log or something along those lines.

**Comment by DilumAluthge** [comment]
> Can you remind me how it was you determined that the cause was a segfault? It doesn't show any signs of a segfault in the buildbot log, but I seem to recall you seeing in a system log or something along those lines.

Yeah, I went to `/var/log/messages`, where I saw the following:
```
Aug  9 03:56:47 freebsdbot5 kernel: pid 87120 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 11:06:37 freebsdbot5 kernel: pid 10266 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 15:25:44 freebsdbot5 kernel: pid 97369 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 15:30:52 freebsdbot5 kernel: pid 20184 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 15:33:48 freebsdbot5 kernel: pid 97371 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 15:36:08 freebsdbot5 kernel: pid 97370 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 17:51:15 freebsdbot5 kernel: pid 77445 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 18:00:23 freebsdbot5 kernel: pid 78125 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 18:05:19 freebsdbot5 kernel: pid 77448 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 18:09:43 freebsdbot5 kernel: pid 77449 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 19:17:20 freebsdbot5 kernel: pid 77444 (julia), jid 0, uid 1001: exited on signal 6 (core dumped)
Aug  9 19:34:39 freebsdbot5 kernel: pid 31205 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 19:40:47 freebsdbot5 kernel: pid 31870 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 19:50:52 freebsdbot5 kernel: pid 31199 (julia), jid 0, uid 1001: exited on signal 6 (core dumped)
Aug  9 19:54:18 freebsdbot5 kernel: pid 32484 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 20:01:32 freebsdbot5 kernel: pid 32480 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 20:07:43 freebsdbot5 kernel: pid 33145 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
Aug  9 20:39:24 freebsdbot5 kernel: pid 54057 (julia), jid 0, uid 1001: exited on signal 11 (core dumped)
```

**Comment by DilumAluthge** [comment]
Huh. I didn't notice the signal 6. I thought they were all signal 11.

**Comment by vtjnash** [comment]
IIRC, someone said on Slack the failure is a bug in the FreeBSD libunwind library, not this PR?

**Comment by DilumAluthge** [comment]
If I understand correctly, those are two separate issues. The discussion on Slack was about the segfaults during the FreeBSD tests.

But separately from the segfaults, there are test failures in the Sockets tests on FreeBSD that are caused by this PR.

@ararslan Is that correct?

**Comment by ararslan** [comment]
As far as I know, that is correct. In the Sockets tests, the pipe is not being closed when the tests are expecting it to, so `!isopen(P)` is `false`. The segfaults, which show up as that unhandled task error, seem to be due to some issues with DWARF emission and unwinding and are unrelated to this PR.

An alternative to reverting this is to do something like
```diff
diff --git a/stdlib/Sockets/test/runtests.jl b/stdlib/Sockets/test/runtests.jl
index 328ea929f4..0186677726 100644
--- a/stdlib/Sockets/test/runtests.jl
+++ b/stdlib/Sockets/test/runtests.jl
@@ -521,7 +521,12 @@ end
     @test readuntil(P, 'w') == "llo"
     Sys.iswindows() && wait(t)
     @test eof(P)
-    @test !isopen(P) # eof test should have closed this by now
+    # FIXME: eof test should have closed this by now, but it seems not to on FreeBSD
+    if Sys.isfreebsd()
+        @test_broken !isopen(P)
+    else
+        @test !isopen(P)
+    end
     close(P) # should be a no-op, just make sure
     @test !isopen(P)
     @test eof(P)
```
and open an issue for tracking that. I've not yet looked into it, as I've prioritized investigating the segfaults.

**Comment by vtjnash** [comment]
that seems okay too

**Comment by DilumAluthge** [comment]
Between the revert (this PR) and a `@test_broken`, which do you prefer. Either sounds fine to me.

**Comment by DilumAluthge** [comment]
Closing in favor of #41983

**Pull request closed without merging**
