### PR TITLE
Solve the ismutable confusion once and for all

### PR DESCRIPTION
**Pull request by udohjeremiah**
This section on the doc is titled as: [Frequently Asked Questions](https://docs.julialang.org/en/v1/manual/faq/#Frequently-Asked-Questions).

I do not know **"how many times"** the community judges as a valid count for a question to be put in this section, but from the English word "frequently", I feel it is "more than time". Not less than two times in a month, you see someone from [Discourse](http://discourse.julialang.org) confused on why `ismutable` returns `true` for objects they cannot mutate technically and also the docs gives the assurance these objects are immutable; yet they're surprised to see `ismutable` returning `true` when these objects are passed to the function.

As an example, the doc says:
As in Java, strings are immutable: the value of an `AbstractString` object cannot be changed. To construct a different string value, you construct a new string from parts of other strings. Ref: https://docs.julialang.org/en/v1/manual/strings/#man-strings

Of a truth it cannot be changed, so technically we're still on point:
```julia
julia> str = "string"
"string"

julia> str[1] = "S"
ERROR: MethodError: no method matching setindex!(::String, ::String, ::Int64)
```

But then, here comes the "glorified" question: WHY SHOULD `ismutable` then return `true`:
```julia
julia> ismutable(str)
true
```

I am not linking any question or issue regarding this, since I won't be able to link enough, as there are plenty of them available and anyone honest enough with a google search will start seeing what I'm saying. For those closer to the Julia GitHub page, you've seen how many PRs get closed on this, discourse questions not given concrete answers, open PR regarding this that are "stalled". My pain is: **is this too big to explain or solve, so we understand?**. I'm asking this to people closer to the compiler, since we've figured out now that it's a compiler issue (in some way).

So I've opened a PR for it (since surprisingly despite the recommendations on this, no one has done so). People with enough info on this and the compiler, should please drop their suggestions on the PR so we understand **"WHY"** and at least be able to explain it to students when we're asked, instead of standing dumb not knowing what to say. THANK YOU!!!

### CODE REVIEW

**Comment by KristofferC** [comment]
I think a small note in the `ismutable` docstring should be enough. Something like:

```
    !!! note
    For technical reasons, `ismutable` returns `true` for values of certain special types  (for example `String` and `Symbol`) even though they cannot be mutated.
```

**Comment by udohjeremiah** [comment]
Honestly, it is not enough. At least, when you're teaching Julia to smart kids, you don't want to say "for technical reasons". What is "so technical" that cannot be explained to at least make it understandable to some degree? If anything, IMHO, a thorough FAQ should be written on it (regardless of having `ismutable` with the changes you presented).

**Comment by KristofferC** [comment]
This is a side note to a reflection function that is virtually never used in typical code. Having this in the FAQ is grossly excessive.

**Comment by Keno** [comment]
This is probably too pendantic, but you **can** mutate all of those `ismutable` objects. They have identity and memory. You're just not allowed to. That might sound silly, but it is the actual distinction. Now that we have `const` fields, you can construct similar objects yourself:
```
julia> mutable struct foo
       const x
       foo() = new(1)
       end

julia> foo().x = 2
ERROR: setfield!: const field .x of type foo cannot be changed
Stacktrace:
 [1] setproperty!(x::foo, f::Symbol, v::Int64)
   @ Base ./Base.jl:38
 [2] top-level scope
   @ REPL[2]:1

julia> ismutable(foo())
true
```
Anyway, I agree with @KristofferC, this is not FAQ worthy.

**Comment by udohjeremiah** [comment]
This is the same reaction users get over and over again each time the **"`ismutable` question"** is thrown. Nobody likes to talk about it, as if its some proprietary details. I just can't see a concise reason, why this is hidden or refused to be explained in any meaningful that at least appeals to programmers.

Yeah you just said **"It's not worthy of a FAQ"**, but it still doesn't answer the question asked: "WHY?" The answer doesn't need to be "pedantic" as you claim, but at the highest level you possibly can explain it, tell us "WHY?"

**Comment by Keno** [comment]
> I just can't see a concise reason, why this is hidden or refused to be explained in any meaningful that at least appeals to programmers.

I explained it above. It's a mutable object that has memory and identity whose content you happen to not be allowed to mutate, like the `foo` example, I gave.

**Comment by udohjeremiah** [comment]
FAQ are "frequently asked questions" and this question in particular has been frequently asked (since it's confusing), so why  shouldn't it be there?

**Comment by Keno** [comment]
A question being frequently asked does not necessarily mean in needs to go in the FAQ. It often means that some other piece of documentation is missing or misleading. In this case, an appropriate note in `ismutable` seems appropriate as @KristofferC suggested to clarify that in answers whether it's a mutable object, but not necessarily whether it has any mutable content. I think the example I gave above, plus the empty mutable plus the builtin ones are all illustrative examples.

**Comment by brenhinkeller** [comment]
`ismutable` is true because a string is, _technically_ mutable. 
```
julia> str = "string"
"string"

julia> ismutable(str)
true

julia> Base.unsafe_store!(pointer(str), UInt8('S'))
Ptr{UInt8} @0x000000010b0af4b0

julia> str
"String"
```
It's just against the rules to actually do this (i.e., you physically _can_, but doing so may break things, and so you just should never do it -- and the more straightforward ways of trying to do it will intentionally error).

**Comment by vtjnash** [comment]
`unsafe_store!` does not make something mutable, as a technicality or otherwise, any more than random memory corruption makes pure computation technically unpredictable

**Comment by mgkurtz** [comment]
I just stumbled upon this issue and philosophized a bit about it. Perhaps I can give some outside view on this debate.

About how it technically happens, that `String`s present themselves as mutable: the penultimate 1 argument to [`jl_new_datatype`](https://github.com/JuliaLang/julia/blob/113efb6e0aa27879cb423ab323c0159911e4c5e7/src/datatype.c#L660)) defines `String` to be mutable in [jltypes.c](https://github.com/JuliaLang/julia/blob/113efb6e0aa27879cb423ab323c0159911e4c5e7/src/jltypes.c#L2221). I found this by grepping the src folder of the git repository for `\bString\b` and looking at the handful of results. So feel free to tell your smart kids, how they can do the same 😄 Btw. grepping after `struct String` in the base folder yields a comment in [boot.jl](https://github.com/JuliaLang/julia/blob/113efb6e0aa27879cb423ab323c0159911e4c5e7/base/boot.jl#L67) telling us roughly the same.

About the question why the documentation of `String`s and `Symbol`s counterfactually claim, they are immutable: Because conceptually they are. Likely a (link to a) clarifying (foot)note would be honest there. @udohjeremiah, I guess, you are also happy about an answer to your question, if that answer is given at any other appropriate place in the documentation? Then, perhaps in the [mutable composite types](https://docs.julialang.org/en/v1/manual/types/#Mutable-Composite-Types) section, we may elaborate a bit:

> Even if a `mutable struct` `M` contains no field at all or only `const` fields, it still accounts as a mutable struct and `M() !== M()`. Whereas for an immutable `struct` `S` without fields `S() === S()`.
>
> !!! note
> As C does not know the concept of mutability, some types built in C neither really behave like mutable nor like immutable Julia types. Especially `String` adheres to the first essential property of immutability and like for immutable types `"" === ""`. But `String` does not adhere to the second essential property of immutability, the compiler can distinguish equal strings and like for mutable types we can get a `pointer_to_objref` from a string. So from a user point of view `String` appears immutable but from a technical point of view it appears mutable. The reflection method [`ismutable`](https://docs.julialang.org/en/v1/base/base/#Base.ismutable) takes the latter point of view.

Perhaps alternatively, the note could go to the description of `String` or into the [DevDocs](https://docs.julialang.org/en/v1/devdocs/types/) instead. Whereever we put such a note we can happily scatter some hyperlinks to it. The mutable composite types section could use a reference to `ismutable` anyway.

I hope this helps in reuniting the opposing opinions here 😀

**Comment by mgkurtz** [comment]
Thank you @udohjeremiah for backing my suggestion 😄 I will just mention @Keno and @KristofferC here, so they can also tell us their opinion. As far, as I understood @Keno’s

> A question being frequently asked […] often means that some […] piece of documentation is missing or misleading.

they should be happy to fix the partially misleading

> As in Java, strings are immutable

from the [String manual section](https://docs.julialang.org/en/v1/manual/strings/#man-strings). Perhaps with my suggestion, perhaps with another one.

**Pull request closed without merging**
