### PR TITLE
Remove unused function "imagePath"

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by ViralBShah** [comment]
I would leave it in there, in case we need it later on. Ok to merge if @vtjnash doesn't mind removing it.

**Comment by vtjnash** [comment]
Seems like a useful utility function, but I actually can't think of any use for it. So it's probably sensible just to remove it.

**Comment by StefanKarpinski** [comment]
We don't as a general policy accumulate internal junk that we don't use. That's what git history is for.

**Comment by lucatrv** [comment]
If you agree with this PR please go ahead and merge it before #24427 to retain the history of this change

**Pull request merged**
