### PR TITLE
speed up common cases of type application. helps #22593

### PR DESCRIPTION
**Pull request by JeffBezanson**
This skips the intermediate type applications (substituting one parameter at a time) when applying the "wrapper" for a datatype, which has a simple known structure. This cuts the time and allocations roughly in half for the `deserialize` example in #22593.

### CODE REVIEW

**Comment by ararslan** [comment]
Dunno if Nanosoldier will notice, but @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by jrevels** [comment]
Server was just kicked:
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22635#issuecomment-312358576) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e58210c89e994cf7ffe45839b95c14b8667b9c92/fe71996_vs_c509321/report.md). cc @jrevels

**Comment by JeffBezanson** [comment]
Lookin good.

**Pull request merged**
