### PR TITLE
DOC: missing ncv optional argument in eigs

### PR DESCRIPTION
**Pull request by mzaffalon**

### CODE REVIEW

**Comment by mzaffalon** [comment]
I am still confused about by the difference between Julia's eig and eigs.

I read that it is a fundamental limitation of the Implicitly Arnoldi Restarted Method that the number of eigenvalues that can be computed by ARPACK's `aupd` is at most one less than the matrix dimension if the matrix is symmetric and two if the matrix is not.

I would like to add this to the documentation and possibly a link to the documentation. What do you think?

**Comment by jiahao** [comment]
eig is a wrapper around LAPACK's default eigensolver. eigs is a wrapper around ARPACK and can be used on sparse matrices (hence "eig sparse" or eigs). ARPACK also supports functions for implicit matrix-vector products but I don't know if we actually support that feature through eigs.

Yes, more clarification about what ARPACK (and therefore eigs) can or cannot do is welcome

**Comment by StefanKarpinski** [comment]
I've never been a fan of this distinction. Talk about letting the implementation details show.

**Comment by mzaffalon** [comment]
What would you suggest? Have a single eigenvalue solver for dense and sparse? There is also an `svd` and an `svds`.

**Comment by jiahao** [comment]
I don't understand your question. There are two different sets of functions that do two different things because the underlying algorithms are different. Why should they be conflated?

**Comment by jiahao** [comment]
If you'll let me braindump, I assume you mean that there is an API issue here which is similar to sorting. There are many different algorithms for sorting. Most users don't care; they just want an answer. But sometimes users do care but how do you tell `sort` to do mergesort, or quicksort, or quicksort until the problem is less than 17 elements large then do insertion sort? The [`SortingAlgorithms.jl`](https://github.com/JuliaLang/SortingAlgorithms.jl) package has some spelling that uses dispatch to specify the algorithms. I've tried (and have yet to succeed) to do something similar in `IterativeSolvers.jl`. Part of the problem is that there are quite a few more parameters to wrap for these numerical algorithms whereas most of the sorting algorithms take 0 or 1 parameter.

**Comment by StefanKarpinski** [comment]
That's pretty it – I feel like the function should have a way of choosing algorithms rather than having two different functions with slightly different spellings and slightly different behavior that use different algorithms. But I understand that this is a tradition inherited from Matlab.

**Comment by tkelman** [comment]
It's not just a different algorithm, it's also a different quantity of returned information. We could improve the API certainly but not sure if it's sensible to consolidate all the way.

**Comment by StefanKarpinski** [comment]
Sure, that's why I'm describing this as vague API dissatisfaction and not as "this API will not stand, man".

**Comment by tkelman** [comment]
backported in #13182 - though someone who knows how genstdlib.jl should check whether this is working correctly

**Pull request merged**
