### PR TITLE
Make ASAN build not be debug, following clangs recommendation

### PR DESCRIPTION
**Pull request by gbaraldi**
Following LLVMs/Googles recommendation, ASAN should be run with optimization otherwise performance is awful (which it is for us). The asan build is currently by far the longest and it's just a build. I would like for us to one day run ASAN and TSAN tests and maybe even MSAN, but ASAN is the cheapest and less hassly to do it, because it has false negatives instead of false positives like the other sanitizers.

TODO: Make the setting respect if the user asked for a debug build or not.

### CODE REVIEW

**Comment by gbaraldi** [comment]
This needs https://github.com/JuliaCI/julia-buildkite/pull/349 to actually have effect

**Review by Keno — APPROVED** [review]

**Comment by gbaraldi** [comment]
So bootstrapping with O1 is quite a bit faster 🤔

**Comment by giordano** [comment]
But building the pkgimages of the stdlibs is still quite slow, no?

**Comment by giordano** [comment]
Can this this merged since it does sensibly improve ASAN build time, and further improvement can be done in follow up PR?

**Comment by giordano** [comment]
@gbaraldi any objection to backporting this PR to v1.11?

**Comment by KristofferC** [comment]
I backported it because asan fails all the time on 1.11. Maybe this will help.

**Pull request merged**
