### PR TITLE
oneunit of sparse matrix should return sparse matrix

### PR DESCRIPTION
**Pull request by KlausC**
currently we have:
```
julia> oneunit(sparse([1 1 ; 2 2]))
2×2 Array{Int64,2}:
 1  0
 0  1
julia> one(sparse([1 1 ; 2 2]))
2×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  1
  [2, 2]  =  1
```
where it should be. I think the behavour of `one` is as it should be, while `oneunit` is inconsistent. 
```
julia> oneunit(sparse([1 2; 3 4]))
2×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  1
  [2, 2]  =  1

julia> one(sparse([1 2; 3 4]))
2×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  1
  [2, 2]  =  1
```

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Bumping for review. LGTM.

**Review by andreasnoack — APPROVED** [review]

**Comment by ararslan** [comment]
This has already been backported to 1.1.0 and cannot be backported to 1.0 as a minor change.

**Comment by ViralBShah** [comment]
May I request not labelling this as a `minor change` and allowing it backported to 1.0? My only reason is that we are backporting a number of other sparse PRs that are small changes, but together greatly improve the overall quality of the sparse libraries.

There is no urgency, but it would be nice to get it into the 1.0.x at some point.

**Comment by KristofferC** [comment]
We should backport bugfixes, doc improvements and performance improvements to patch releases. Since we are aiming to do 4 month releases it is not too bad if a small change like this goes into the next minor release imo.

**Comment by ViralBShah** [comment]
I guess that is ok. So folks who want LTS (the 1.0 branch) will not get these fixes and have to wait for the next LTS.

**Comment by KristofferC** [comment]
> So folks who want LTS (the 1.0 branch) will not get this and have to wait for the next LTS.

Yes, but the reason you are on an LTS is likely because you don't want these type of changes until you decide to upgrade to a new minor version.

**Pull request merged**
