### PR TITLE
Move unlink function export to the file where function is defined

### PR DESCRIPTION
**Pull request by musm**
To be consistent with all the other exports and function in `file.jl` 

also does anyone know why some of the exports are not actually available in the repl without qualification, i.e. `Base.Filesystem.unlink, Base.Filesystem.cptree, Base.Filesystem.sendfile`

### CODE REVIEW

**Comment by vtjnash** [comment]
(there is no implicit call to `using Base.Filesystem`)

**Comment by musm** [comment]
bump?

**Comment by StefanKarpinski** [comment]
@vtjnash: I don't really understand your comment. Can you elaborate?

**Comment by vtjnash** [comment]
I was answering the second question. This lgtm.

**Pull request merged**
