### PR TITLE
[WIP] Return basic statistics to Base

### LINKED ISSUE #27374: Return basic statistical functionality to Base
It seems incredibly unfortunate to me, and indeed almost actively user-hostile, to remove basic functionality such as `std` from Base. @sbromberger summarized it well in Slack: "if the function is generally understood by a layperson, it should not be removed." You don't have to be a statistics expert to understand what a standard deviation is. The collection of basic statistics functionality in Base in previous versions of Julia was fairly lean and I think struck the perfect balance of "here are the basics, now load a package if you want to get more advanced." Indeed, in the `release-0.6` branch, `base/statistics.jl` is a couple hundred lines of code, including whitespace and extensive documentation. Who was it hurting to have in Base?

### PR DESCRIPTION
**Pull request by ararslan**
This reverts "move cor, cov, std, stdm, var, varm and linreg to StatsBase (#27152)," commit 746d08fdfe65888ca8a30e8cfa3ef2b439251d22. Fixes JuliaLang/julia#27374.

### CODE REVIEW

**Comment by KristofferC** [comment]
Stuff like `linreg` should not be in Base.

**Comment by ararslan** [comment]
Yeah I'm fine with removing `linreg`, but definitely not with removing the rest of the stuff.

**Comment by StefanKarpinski** [comment]
`cor`, `cov`, `stdm`, `var`, `varm` don't belong in Base either. Literally the only one of those functions that is truly objectionable to move out of Base is `std` and honestly, that's a very unfortunately short name and separating `std` from `stdm` seems pretty weird. So we could keep `std` and `stdm` in Base... but really? Why don't we have mean absolute deviation functions in Base or any other dispersion statistics?

**Comment by sbromberger** [comment]
@StefanKarpinski 
> Why don't we have mean absolute deviation functions in Base or any other dispersion statistics?

Because these are generally unuseful to laypeople. Standard deviation, on the other hand, is common enough to be considered "general purpose".

@KristofferC 
> Stuff like `linreg` should not be in Base.

OK, I might agree with you in this particular case, but what are the criteria that we (as a project) have set for what gets put in Base, what gets moved to Stdlib, and what is the responsibility of a third-party package? It seems arbitrary to me that `std` is now third-party while `mean` and `median` are in Base. Was there any reasoning that led to this decision, or was it just an unfortunate result of a drive towards slimming Base?

**Comment by Nosferican** [comment]
I would favor having `statistics.jl` moved to StatsBase, but moving half of it and keeping half in Base seems very arbitrary.

**Comment by ViralBShah** [comment]
I tend to agree with @StefanKarpinski here that retaining `std` makes sense - and it meets @sbromberger's definition of common usage. 

I don't understand though for necessarily including something in `stdlib`. Realistically speaking, to do things, you do need dozens of packages anyways. We are already working on moving SuiteSparse and ARPACK and related capabilities out of stdlib. The more of this stuff is in packages, the easier it is for maintainers to evolve those capabilities. If anything, I think having stats capabilities spread in three places - `Base`, `stdlib/Statistics`, and `StatsBase` could end up being frustrating.

I think having common things in Base (that everyone would want, and I do think `std` falls in that category) and everything in `StatsBase` is the right thing.

**Comment by sbromberger** [comment]
> to do things, you do need dozens of packages anyways. 

This is not my experience at all, and it makes me sad that it seems to be an accepted way of using Julia. Again, I am vehemently opposed to the “npm-ification” of Julia. Perhaps I’m an outlier, or maybe I’m reading too much into this statement, but I have a fundamental aversion to it.

**Comment by juliohm** [comment]
We could start with some simple rules of thumb like "Base" packages can't have dependencies in their REQUIRE file. This is the current list of dependencies in `StatsBase.jl`:

```
julia 0.6
DataStructures 0.5.0
SortingAlgorithms
Compat 0.61.0
Missings
```

As package developers, we have little control of dependency growth unless we establish some conventions like the above. I propose to call a package "Base" if it only depends on `Compat.jl` and maybe other packages like `Missings.jl` (which BTW I think should be part of Julia Base as a too basic type, but that is another issue). Everything else is not considered "Base" and I would be skeptical to add it as a dependency in my projects.

**Comment by dpsanders** [comment]
I have no idea what `stdm` or `varm` are, which seems like a good reason not to have them in Base.
Or should they actually be methods of `std` and `var`?

**Comment by nalimilan** [comment]
> As package developers, we have little control of dependency growth unless we establish some conventions like the above. I propose to call a package "Base" if it only depends on Compat.jl and maybe other packages like Missings.jl (which BTW I think should be part of Julia Base as a too basic type, but that is another issue). Everything else is not considered "Base" and I would be skeptical to add it as a dependency in my projects.

Missings.jl is just a Compat-like package for 0.6 and not needed on 0.7. DataStructures is only used in one place and that dependency could probably go away. Finally, I think SortingAlgorithms is worth adding to the stdlib.

Overall StatsBase isn't that big and it's pure-Julia. See https://github.com/JuliaLang/julia/pull/27152#issuecomment-390687566 for a list of features it includes. I'm not opposed to having `std` in Base since that's a pretty basic function, but for all slightly more advanced functions I don't think it's a problem to depend on StatsBase (whether it lives in the stdlib or not).

**Comment by JeffBezanson** [comment]
If you want objective criteria for what should be in Base, the closest I can come is "as little as possible". It should contain only functions it would be hard to imagine writing any julia code without. Anything else is just arguing about what is "commonly used" enough. It's fine if people want to have those debates; just be aware that's what you're signing up for.

**Comment by oscardssmith** [comment]
I think a lot of the contention here is coming from the fact that `statsbase` isn't in stlib. While I agree with @JeffBezanson that Base should contain as little as possible, I think that one of the things `python` shows us is that the standard libraries should be the home to as much as possible as long as it is useful, robust, and reasonably performant.

**Comment by Nosferican** [comment]
From a developer perspective, I favor moving away from `stdlib` to just packages (easier to maintain, easier for CI, etc.). From a user perspective, I also prefer to have them as packages since it makes explicit my environment and for anything beyond trivial stuff, it would be installed and loaded as dependency when using end user targeted packages.

**Comment by ViralBShah** [comment]
@sbromberger I think calling this npm-ification of Julia is a bit unfair. Julia packages tend to include larger chunks of functionality. On the  dozens of packages, I find myself at least wanting `Plots` and `Gadfly` on any machine I am running Julia on, and you are quickly into quite a few packages. I don't think my experience is uncommon.

@dpsanders I was wondering what `stdm` was too and had to look it up, and then remembered it. Handling them as methods of `std` seems reasonable to me, but the stats folks may want to chime in.

Whether something is in `stdlib` or a package is not the same discussion as `What should ship in the default download of Julia`, even though today the two are connected. Perhaps this is a conversation for JuliaCon, and we might want to have a BOF session on this topic.

**Comment by sbromberger** [comment]
So, since this discussion came out of a gripe I made in slack, perhaps I can help refocus the discussion. Right now, the following seems to have occurred, resulting in an undesirable situation (at least from my perspective) - perhaps I've misunderstood part of it.

1) a "common" function (`std`) was moved from Base to a third-party package, StatsBase, sometime between 0.6.2 and 0.7.
2) the plan is to move StatsBase to the stdlib sometime soon, but until then,
3) anyone who wants to use `std` in their library now must incur the cost of another third-party dependency in `REQUIRE`, and
4) must then change (with a retag) the code to drop that dependency once StatsBase is in stdlib, because
5) there is apparently a desire to avoid moving things from Base to stdlib directly at this time.

It's the combination of 3 - 5 that is causing me grief. We've spent a TON of time and effort trying to reduce the number of dependencies that LightGraphs and the LG ecosystem has. This was originally "reduce the number of packages that get installed by `Pkg.add("LightGraphs")` on a clean system", which was originally 44, but got down to 7 or 8 after a month or so of work. 

The move of functions from Base to stdlib makes this a bit more complex, since we now can't use "number of import/using statements" as a metric, but rather, "number of packages in REQUIRE, plus their dependents", since the move to stdlib *increases* the former but doesn't really represent new dependencies.

So what we've done is reimagined our "ecosystem fragility" as a function of "what are we depending on that's not core Julia?" This is important to us (me) because I am seeing a trend over the past 3 years of abandoned / unmaintained packages, and we've been bitten by this directly. In some cases it's just because the package is mature and there's not much left to do; in others, the maintainer has moved on to other things. But it is a higher risk that a third-party package will stagnate than a stdlib package will, so our preference is for the latter over the former given that we've got to change our thinking about Base.

Thus, we're now faced with a decision:

1) incur the cost (both in terms of development [admittedly small], complexity and fragility) of including a third-party package in order to use a function that used to be in Base, and then incur the cost of moving it back to stdlib at some point in the (hopefully near) future;

2) rewrite `std` and incorporate it in LightGraphs (we've done that for some other things where the dependency cost was too high to justify a REQUIRES just to get a single function); or

3) rewrite our code to eliminate `std` altogether. This is actually what we've wound up doing over the past couple of days, so we don't have to make a suboptimal decision.

So, from our perspective, the initial problem has been resolved by doing something else entirely; but the issue still remains that in the future our strong preference is to prefer Base / stdlib over third party wherever possible. Our [developer guidelines](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/CONTRIBUTING.md) (fourth bullet) need to be updated but the essence still holds, as in order to keep LightGraphs as a "core" library for graph analysis, we need to make sure it's not difficult for end users to use, but just as importantly, for developers to incorporate, adapt, and extend.

Julia Core team, please keep this in mind as you make further decisions about what lives in Base, what lives in stdlib, and what gets moved out to third-party.

**Comment by chethega** [comment]
From a user perspective, my test for Base exports would be: Am I supposed to read the manual for this function before starting to code julia? If not, then it wants to be in a separate namespace.

But I agree that juliaLang should be responsible for maintaining/curating basic necessities like standard deviation; that is, NPM left-pad is a catastrophe to learn from, and a fracturing of dependencies is the worst thing that could happen. But if there is a large majority of users that can get away without knowing of a function's existence, then it only pollutes their namespace and disorganizes the manual.

I would be entirely happy if these things moved to a submodule, like `Base.Order`.

**Comment by ViralBShah** [comment]
I think everyone agrees that `std` will go back to `Base`, as a common function like `mean`. Does that not resolve the immediate issue?

Apart from that, yes, I do acknowledge the larger philosophy of burden on package writers, but perhaps we can focus the conversation here on what is best to solve the current issue - being the specific functions in this PR. 

I really also don't like how folks are bringing up NPM here - as I think it does a disservice to other open source developers (after all it is very easy to sit in ones armchair and criticize things), and it tends to over-simplify the issues we are trying to sort out.

**Comment by sbromberger** [comment]
> I think everyone agrees that std will go back to Base, as a common function like mean. Does that not resolve the immediate issue?

The immediate issue from LightGraphs' perspective has already been solved; that is, even if you choose to do nothing, we have worked around the change.

> I really also don't like how folks are bringing up NPM here - as I think it does a disservice to other open source developers (after all it is very easy to sit in ones armchair and criticize things), and it tends to over-simplify the issues we are trying to sort out

I think this criticism is unfair. NPM is a classic case of a new approach to dependency management that has seen some very strong drawbacks in implementation (left-pad being one of them; reliance on a central repository being another; fragmentation of that repository being a third). There are lots of advantages to an NPM-like system *for Node developers*, but I don't think it carries to Julia developers. This is not a criticism of NPM without context, which is what I gather you mean by "armchair criticism"; it is a plea to the Julia team not to create a repository structure that has all the well-known shortcomings of NPM without some significant offsetting benefits. I'm happy to discuss elsewhere if it's a distraction to the current issue.

**Comment by JeffBezanson** [comment]
I believe with Pkg3 stdlib packages do need to be listed in Project.toml, so your steps 3-5 of first adding and then removing a dependency should not occur.

**Comment by ViralBShah** [comment]
How about we keep `std` in `StatsBase` for a while for now and see how it feels? We can certainly move it to `Base` before 0.7 if that is what we want, but perhaps develop a feel for it in the meanwhile.

**Comment by sbromberger** [comment]
> How about we keep `std` in StatsBase for a while for now and see how it feels? 

Because it's inconsistent with `mean` and `median`, which are in Base. I'd favor moving them into a stdlib package, but moving `std` into a 3rd party package seems like a really bad idea.

**Comment by ViralBShah** [comment]
I was personally on the fence about moving `std` out. Let's wait a little bit to gather other feedback here and then modify this PR accordingly. I would be ok for all three (mean, median, std) to be in Base or Stdlib (but together), since they are quite basic and almost everyone knows them.

**Comment by sbromberger** [comment]
>  I would be ok for all three (mean, median, std) to be in Base or Stdlib (but together), since they are quite basic and almost everyone knows them.

I was under the impression that it was impossible at this point to move things from Base to Stdlib directly without going through a third-party package. Is this wrong?

**Comment by ViralBShah** [comment]
We moved a ton of stuff from Base to Stdlib. I don't think we need to go through third party packages.

**Comment by juliohm** [comment]
On one hand, I think having all these in `StatsBase.jl` makes sense if the package adopts the "Base" convention above, and if we are selling Julia as a general-purpose programming language. On the other hand, it feels like we are hurting the "scientific computing" experience of the language by forcing users to load very basic operations like `mean` and `std`. I am undecided myself. My programmer side likes modularity and minimal packages. My scientific side is annoyed of loading packages to have access to `mean`, `std`. Is there a compromise in between? Any technology that would solve this infinite back and forth?

**Comment by yurivish** [comment]
Perhaps a tool for generating new packages that has templates for e.g. a statistics-based project or package?

**Comment by andreasnoack** [comment]
I think it is worth noting that 442 packages already depend on `StatsBase` so I'd be surprised if any installation that isn't just for testing wouldn't already have `StatsBase` installed. So it is really a light dependency to add to your package. In the `LightGraphs` case, even if people are running it on systems where `StatsBase` isn't already installed (which I doubt), the net increase in code installed from adding `StatsBase` as a dependency is pretty small since `LightGraphs` already depends on `DataStructures` which is the only big `StatsBase` dependency.

> I have no idea what `stdm` or `varm` are, which seems like a good reason not to have them in Base.

They are optimized versions of `std` and `var` when the mean is already known. Now that we have fast keyword arguments, they should probably become methods of `std` and `var`.

**Comment by JeffBezanson** [comment]
For interactive use, you can put `using StatsBase` in your juliarc.

**Comment by martinholters** [comment]
It's noteworthy what a difference it makes whether something is shipped with Julia as part of stdlib or is part of an external package. There is something to be learned here when thinking about moving stdlib packages to external repositories. I don't think it's the need to `pkg> add StatsBase` as such that's stirring people up. My guess is that it's primarily adding another dependency that's the problem here. Because for every dependency, you have to worry. Will it be maintained in the future? Will it be ported to future Julia versions? If it ships with Julia, it just feels safer to use it. And if you like to follow Julia development and use its master version, it is also reassuring to know stdlib is tested as part of the Julia testsuite, so any breaking changes will be dealt with there immediately.

I'm not sure what that means exactly for the future of stdlib packages and their externalization, but we should remember this incident when making decisions there. Note that I'm not at all against moving stdlib packages to external repositories to allow develop at a faster pace than Base. But I do think there has to remain a tighter coupling than just a list of endorsed standard packages.

**Comment by ViralBShah** [comment]
A lot of worry does stem from the fact whether Base and stdlib in fact receive more eyeballs and hence more support. I think while that was true in the first few years of Julia, I think many of these ecosystems have robust development and support, and having a monolithic repo is in fact slowing things down, and we are bursting at the seams (note the CI issues specifically).

Specifically, `StatsBase` has worked out extremely well, even though when we did it, I had the same concerns. In terms of support for future Julia versions and such, I think having a robust release process that is co-ordinated and well communicated would serve us better.

**Comment by catawbasam** [comment]
https://github.com/JuliaLang/julia/issues/27421
would not have happened if StatsBase was in stdlib.  Correct?

**Comment by KristofferC** [comment]
That's an implementation detail of the package manager to help with transition packages so not sure what relevance it has.

**Comment by sbromberger** [comment]
> I think it is worth noting that 442 packages already depend on StatsBase so I'd be surprised if any installation that isn't just for testing wouldn't already have StatsBase installed.

This is a specious argument that I've seen repeated for `Compat`, `Plots`, and others. Just because a package is popular doesn't mean that there's no cost in relying on it in your library. We made the explicit decision to minimize our dependency footprint precisely because we didn't want to perpetuate the trend of massive third-party package installation just to get simple things (like graphs).

Taken to its extreme, the philosophy of "don't worry; the package is popular enough that it's probably on the system already" will ensure the installation of some large set of "must-have" third-party code, which will lead to entrenched bloat throughout the ecosystem.

In any case: I'd be fine with a move to stdlib, but forcing the use of a third-party library for something as common as standard deviation still seems silly. (Again, this particular issue is moot since we eliminated the need for `std` in the LightGraphs code, but this is part of a larger issue that I think needs to be addressed.)

**Comment by Nosferican** [comment]
I don't think there is much difference between a "third-party" and a "stdlib". For most purposes the cost is in loading the code, not in having a copy of it. Having the code in a `stdlib` is basically the same as if it were a third-party (one needs to load the `stdlib` one wants to use).

**Comment by catawbasam** [comment]
In Python-world, modules in the standard library can be less risky in that packages outside the standard library are more prone to incorporate additional third-party packages.  That occasionally causes trouble even to well-maintained packages.

**Comment by sbromberger** [comment]
> I don't think there is much difference between a "third-party" and a "stdlib".

There can a huge difference between third-party and stdlib. Standard library code is distributed with the default installation; it is guaranteed to be maintained by a core team, and changes are less frequent and pretty much guaranteed to follow the organization's change policy (this is a good thing when you're using the functions in a library!).

Take a look at ParserCombinator.jl for a good example (this one's still causing us some problems).

**Comment by Nosferican** [comment]
For a very long time there was a lot of stigma for "third-party" packages and `stdlib` were the "blessed" ones. Historically in Julia, many `stdlib` packages were part of Base and others were third-party packages. In practice, many ecosystems are maintained by Julia core developers. The whole issue of what is "blessed" can be resolved with simply having a "stdlib" registry, a tag or asking the community. In security sensitive settings, one only install vetted packages, being a `stdlib` is just *one of multiple ways* to assess that status (e.g., Tidyverse packages are well-established in the R community and are not `stdlib` or related to R core team or RStudio). Actually, the `Pkg` `stdlib` for 0.7/1.0 is designed to provide various solutions to the problem of curated packages making the `stdlib` "blessed" status something more of a vestigial feature.

**Comment by sbromberger** [comment]
> In security sensitive settings, one only install vetted packages, being a stdlib is just one of multiple ways to assess that status

This may be true in some environments, but not in all. That is, being in stdlib and having the imprimatur of Julia Computing is different than being a package (no matter how widely used) from some other unvetted source.

**Comment by sbromberger** [comment]
> The only safeguard against a security risk in a stdlib is that the reviewers and merge must be approved by a member of the the JuliaLanguage organization with writing access. 

With respect, this statement is simply incorrect.

**Comment by catawbasam** [comment]
As you say --  `A lot of the "blessed" status is driven by perception than actual security considerations (which in itself is a security risk).`  I wholeheartedly agree.   Nonetheless, if stdlib dependencies are restricted to base and stdlib, but curated 3rd party packages are not, that is a real difference even when the maintainers are the same.  

Curated registries like Julia Computing are a partial solution, and should cover most cases as the ecosystem stabilizes.  In the short term, however, many 3rd party developers will need to frequently update from source repos, so curated registries will be of limited use.

**Comment by JeffBezanson** [comment]
I don't think we should flip-flop on this.

**Comment by StefanKarpinski** [comment]
The way forward, if someone wants these functions to ship with Julia again is to create a `stdlib/Statistics` package that includes them and other things from `StatsBase`.

**Comment by Nosferican** [comment]
Probably a good idea to move `base/statistics.jl` to `stdlib/Statistics` unless code in Base actually uses `mean` or `quantile`.

**Comment by ViralBShah** [comment]
I would prefer `quantile` go to `StatsBase` too. I don't think we should have `stdlib/statistics`. All the common things that everyone wants should stay in Base, and the rest in StatsBase, where the JuliaStats community can manage it in one place as a whole.

Note, that it is possible that not all of stdlib ships as is in the future (but of course it will in 1.0).

**Comment by lstagner** [comment]
I honestly don't care about the rest of the functions I just want `std` in base. It's a really common function and I don't look forward to explaining to everyone that in order to use `std` you need to have `using StatsBase`. Can we please just have `std`? 🙏

**Comment by ViralBShah** [comment]
I would be onboard with `std`. My personal list is `mean` and `std` in Base, and everything else `StatsBase`.

**Comment by juliohm** [comment]
I would like to clarify (as a user and follower of the developments) that the initial goal of being a language for scientific computing has changed along the way. Nowadays, it is incorrect to give Julia this label.

We can either accept the new wave of generality and leave all the statistical functions outside of Base for consistency, or regain the title and export a set of names that anyone doing scientific work would expect to have coming from numpy, octave, matlab, etc.

If all these statistical functions are collected coherently in a package `Statistics.jl`, it shouldn't be a big problem for users to type this single line before they start their work. The issue is more about dependency increase for package developers, which will have a harder time with keeping their packages small, and with portability.

**Comment by StefanKarpinski** [comment]
@juliohm, you are not the arbiter of what does or does not make something a scientific computing language and that kind of rhetoric does not help make your point.

**Comment by juliohm** [comment]
Sorry for the noise, I am just sharing my feelings about these changes. Won't do it again.

**Comment by KristofferC** [comment]
`mean` + `std` in Base seems reasonable.

**Comment by Nosferican** [comment]
I discussed the thread with a co-worker and here is a summary of some points from the conversation:
- Julia language as a scientific/computing language/ecosystem might benefit from having both `StatsBase` and a tabular data representation (e.g., `DataFrames`) as standard libraries (e.g., JuliaComputing)
- From a security perspective, if Julia is being used in industry and whatnot, having those capabilities shipped with the language might be lot better from a security/permission standpoint (maybe this will be addressed with `Pkg` curated registries).
- I believe the "best" decision should be informed by these peripheral concerns (will StatsBase morph to a `stdlib/Statistics`, will curated registries solve the security/permission issues for packages not shipped with the language (e.g., preferred versions rather than vanilla like Microsoft R Open to R or conda Python distribution)?
- My personal preference is to keep the code topic organized rather than split them by how layman these might be.

**Comment by JeffBezanson** [comment]
> coming from numpy

...where you have to type `import numpy` to do anything like this.

As long as we're going to have mean, median, and quantile in Base, I won't fight including `std` as well. But I just don't get why being in Base is such a big deal. If your requirements disallow using packages, for whatever reason, it seems to me `std` is the least of your problems.

**Comment by StefanKarpinski** [comment]
Moving `std` back to Base seems reasonable. Can we lose `stdm` then and replace it with a keyword arg to `std` supplying a known mean value? Separating `std` from `stdm` seems weird but `stdm` does not seem like it belongs as its own name in Base.

**Comment by StefanKarpinski** [comment]
@juliohm:

> Sorry for the noise, I am just sharing my feelings about these changes. Won't do it again.

Your input and opinion are welcomed. If you have a solid argument for or against something, please make it. Please do not make technical choices that you disagree with into ["historical disasters"](https://github.com/JuliaLang/julia/issues/25565#issuecomment-389574146) or epic existential threats to the language (because it is no longer a true scientific language). That kind of rhetoric actively hinders having a reasonable, civilized debate about what clearly is a subject where different people, many of whom have been actively involved in scientific computing for a long time, can have divergent opinions. By painting the situation in terms of the people who want Julia to be a scientific language (those who agree with you), versus those who don't (those who disagree), you are implicitly saying that all of the people who disagree with you are not real computational scientists and don't care about scientific computing. In the inner products thread there were many posts where you similarly stated or implied that anyone who disagreed with you was either not a real mathematician or didn't care about correctness (amusingly enough when arguing with Steven Johnson). That's simply not a good stance to approach a debate from. Assume that we are all reasonable people who want Julia to be the best language for scientific computing that it can be (and great for other things too), and that if you make a good case for why your way is better, we will listen to it.

**Comment by juliohm** [comment]
Thank you for the wise words @StefanKarpinski , I will try to organize my thoughts better in the future. Sometimes, however, I feel that there is reluctance from core devs to think neutrally about new ideas proposed by users and package developers. I am not the first to complain about this as you know, and there are many cases online of users blogging about these problems, which are real. That thread with inner products is a good example where a very decent idea was almost killed from the beginning without clear justification, and I would argue that it unrolled in that long discussion just because of the feedback and comments that I got with no scientific basis, and just personal taste. It felt to me like the the idea was being evaluated with a mindset like "He is not from the pack, why do we have to listen to him?" By all means, we are all here with a shared goal to have a good language, and to design it to the best extent possible. More impartial evaluation of new issues contributed by external users would make things a lot better.

**Comment by Nosferican** [comment]
My grain of salt in the above is that usually the misunderstanding are from a lack of sufficient nuance. It is not the first (nor will it be the last) time that someone has turned a decision point into a dooming the language scenario or a core developer has shut it down without sufficient nuance as to why the language / framing is disruptive and counterproductive (which can seem unjust / harsh and shut down a potential contributor). However, in most cases the nuance has taken place afterwards (such as in this case) and clarifies the matter improving the community environment. That is something inherent in the system as human beings and hopefully it continuous to improve. Sometimes, I will have issues closed before having time to address follow ups that lead to actual issues addressed, but I totally get why some responses might be a bit rushed (e.g., closing this PR/issue for instance when the discussion has evolve in spite of being closed) due to the need to move through issues as developers.

**Comment by JeffBezanson** [comment]
I can't help but notice some irony here: some people object to adding a dependency on StatsBase, but their solution to that is to force every julia program to depend on some statistics functions via Base.

**Comment by ViralBShah** [comment]
The reason this PR is closed is because the discussion for moving everything back from StatsBase is not open. The only thing we are considering is `std`. Perhaps enough has been discussed... We need a PR.

**Comment by Nosferican** [comment]
Final vote from my part is that `mean` and `std` should be in the same location. I believe it would be best for `quantile`, `median`, `var`, `skewness`, `kurtosis`, etc. to be in the same location wherever these end up (Base, `stdlib`, a Julia ecosystem).

**Comment by StefanKarpinski** [comment]
I think @Nosferican's split is a good one. The only thing we need to get there is to merge `stdm` into `std` and move it back into Base. Everything else can stay in `StatsBase`.

**Comment by ViralBShah** [comment]
Yes, I'd be up with having the `stdm` functionality folded into `std`, perhaps with a keyword argument, but not having it as a separate function in Base.

**Comment by ararslan** [comment]
Kind of weird that `std` and `var` would be separated, IMO, but otherwise that seems like a logical split.

**Comment by ViralBShah** [comment]
We still have `median` and `quantile` in Base. If people want `std` and `var` together, which is also reasonable, then perhaps they all need to go to `StatsBase`.

**Comment by StefanKarpinski** [comment]
Part of the problem is that `std` and `var` are very short names to be claimed in Base. The names `median` and `quantile` couldn't really mean anything else, so it's far less problematic.

**Comment by nalimilan** [comment]
Implementation-wise, it would be silly to have `std` in Base but not `var` given that the former needs the latter. But I agree `median` and `quantile` would better live in StatsBase.

**Comment by ararslan** [comment]
`std` -> `stddev`, `var` -> `variance`? ¯\\\_(ツ)\_/¯

**Comment by Jutho** [comment]
As somebody who almost never uses statistics (and had to check only to find out that `StatsBase` was installed as a dependency), I would hope that `std(dev)` remains easily available for quick exploration. My main problem with `StatsBase`, crazy as it may seem, is a dislike for abbreviated names for packages. I don't mind `using LinearAlgebra` and `using Statistics`. But `using StatsBase` looks awfully unintuitive and is harder to type then `using Statistics` because of the capital `B` following the letter `s`, which makes my left hand hurt.

**Comment by gabrielgellner** [comment]
I don't personally love the move to `stddev` and `variance`, as it feels like it breaks a naming convention (from numpy / matlab, without going to another one like R's sd / var, or Mathematica's name it in full) to add a new arbitrary one. But a larger question: would this mean we would in the future have both spellings of the name, depending on what packages are loaded, or that this would be the new names (in Base I guess...) for these in Julia?

Finally as to the points made about lean vs fat standard libraries is the point made about copying functions into a package to avoid a dependency something that happens in these more modular environments (i.e. npm etc) more often? That seems so scary to me from a reuse perspective, and code idiom perspective. Seems like some tough trade-offs between given the language a built in feel with enough verbs from the standard library that it has some reach to basic packages, versus having too fat of a base distribution which might hamper some domain applications (that require small install footprints). Also having all the documentation distributed across packages is a real pain point as it makes everything feel less integrated.

**Comment by StefanKarpinski** [comment]
There’s a choice here:
1. Use the very short, overly generic names they want—three letter, highly overloaded terms like `var` and `std‘—and have those names in a stats-specific namespace.
2. Have these functions in Base with longer, more descriptive, less overloaded names like `variance` and `stddev`.

Refusing to do either and insisting that the only acceptable solution is having super short names _and_ having them in Base strikes me frankly as pretty unreasonable, yet that is the position that seems to be taken by many in this discussion.

**Comment by Nosferican** [comment]
I prefer one.

**Comment by JeffBezanson** [comment]
That in large part comes from `exp`, `sin`, etc. being traditional in many languages, much more so than `std` and `var`. `sin` and `cos` are found even in really minimal environments like micropython and small scheme systems.

I also think the namespace issue is not the main issue. Being in Base does *not* prevent other packages or code from using those names for something else, though it's often discussed as if that were the case. On the other side, keeping the functions in Base but renaming them would not fix anything as far as I'm concerned. What matters more to me is where the code is located, for purposes of developing and versioning it, and for purposes of removing it as a dependency for people who might want to build minimal executables at some point in the future.

**Comment by gabrielgellner** [comment]
I agree that std and var is less common (likely just because it is not in math.h :) ), but I think the naming issues are the same,  and std / sd and var, but when they exist in a base language they are almost always one of these versions (though I do see that python has added the variance, stddev version to their standard library ... which is ugly given the numpy names ... but so it goes). Mostly this was in response the @StefanKarpinski  point about the two choices which focused on the namespacing, variable name length trade-off.

For the code location I do think it has a end user impact as well though which is likely why this always brings up so much discussion when any new piece is removed from base. The rise in `using` statements in my own code does change the feel of the language, and downloads the knowledge of what are the basic building blocks of the language onto the end user which can feel bad. I feel this ship has sailed in Julia, but the distributed standard library does make Julia feel less integrated, even if that is only from a new or less savy users perspective.

**Comment by lstagner** [comment]
I'd rather have longer names for `std` and `var` than to not have them in base at all.

**Pull request closed without merging**
