### PR TITLE
Add octal prefix (0o) to filemode in StatStruct

### PR DESCRIPTION
**Pull request by simonbyrne**
Makes it clear it is in octal

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by simonbyrne** [comment]
What sort of test do you have in mind?

**Comment by StefanKarpinski** [comment]
You could create a StatStruct object and ensure that it prints they way you'd expect?

**Comment by ararslan** [comment]
Maybe something like `@test startswith(sprint(show, <some StatStruct>), "StatStruct(mode=0o")`

**Comment by simonbyrne** [comment]
To be honest, I don't really see the point of adding a test for this. I guess to me it's unclear what hypothetical possible regressions we need tests to catch.

> You could create a StatStruct object and ensure that it prints they way you'd expect?

I don't understand what most of the fields are. Also most of them aren't printed.

> Maybe something like `@test startswith(sprint(show, <some StatStruct>), "StatStruct(mode=0o")`

Again, what would this catch?

**Comment by ararslan** [comment]
Yeah, fair points. I guess this would only be useful to ensure that the change actually happened, but it's probably not really necessary with something this simple and obvious.

**Review by ararslan — APPROVED** [review]

**Comment by simonbyrne** [comment]
I added a test to check it parses correctly, not sure what else I could do.

**Comment by ararslan** [comment]
It looks good. Thanks 🙂

**Pull request merged**
