### PR TITLE
Fix wine bootstrap

### LINKED ISSUE #39124: Fix Windows cross-compilation from Unix
There are several issues that cause the build to fail. 

https://github.com/JuliaLang/julia/pull/39022 fixes a bug in the makefile and allows it to run (but this fix fails on Cygwin! so we can't use it)
```
$ make -j8
chmod a+x /home/mus/julia/julia.bat
0031:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0033:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0037:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0035:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0031:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0031:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0037:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0037:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0033:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0033:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0035:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0035:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0041:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0047:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0043:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0041:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0041:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0045:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0043:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0043:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0047:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0047:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0045:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0045:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
004f:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0051:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0051:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
004f:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0051:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
004f:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
0053:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0053:err:module:import_dll Library LLVM.dll (which is needed by L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe") not found
0053:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\mus\\julia\\usr\\tools\\llvm-config.exe" failed, status c0000135
    FLISP src/julia_flisp.boot
002e:err:module:__wine_process_init failed to load L"Z:\\home\\mus\\julia\\src\\flisp\\flisp", error c000012f
make[1]: *** [Makefile:222: julia_flisp.boot] Error 47
make: *** [Makefile:43: julia_flisp.boot.inc.phony] Error 2
```

### PR DESCRIPTION
**Pull request by Keno**
Fixes #39124
Closes #39022

### CODE REVIEW

**Comment by vtjnash** [comment]
heh, I just had worked on this recently in https://github.com/JuliaLang/julia/pull/38994/commits/483379f50934161b1348a75d712d48cf4192bd27. Looks like I'm missing a few of your changes and you're missing a few of mine

**Comment by Keno** [comment]
wanna just squash your changes into this branch?

**Comment by giordano** [comment]
Does this mean we could fully build julia (including precompilation) with BinaryBuilder?  I tried to run Julia in Wine some weeks ago, the REPL looked kind of broken, but running it non-interactively worked fine at least for simple tasks (I did some matrix multiplications)

**Comment by ViralBShah** [comment]
I thought julia in BB needs full cross-compilation capabilities in the Julia compiler, which we do not have.

**Comment by giordano** [comment]
We can already build the `julia` executable, but we can't generate the sysimage.  If we can do that with Wine, I think that's all we need, and using Wine is one of the long-term objectives of BinaryBuilder (https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/10)

**Comment by musm** [comment]
It's been a while since I tried to cross-compile. The build process goes through fine, but I'm getting
```
Test  ─────────────  0.258845 seconds
LibCURL  ──────────  0.405084 seconds
Downloads  ────────  0.420572 seconds
Pkg  ──────────────  4.357362 seconds
LazyArtifacts  ────  0.017907 seconds
Stdlibs total  ──── 30.544908 seconds
Sysimage built. Summary:
Total ───────  54.886725 seconds
Base: ───────  24.339616 seconds 44.3452%
Stdlibs: ────  30.544908 seconds 55.6508%
    JULIA usr/lib/julia/sys-o.a
Generating REPL precompile statements... 30/30
Executing precompile statements... 1363/1396
Precompilation complete. Summary:
Total ─────── 112.483401 seconds
Generation ──  82.938948 seconds 73.7344%
Execution ───  29.544453 seconds 26.2656%
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow The explorer process failed to start.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
```
Following the instructions at https://github.com/JuliaLang/julia/blob/master/doc/build/windows.md#cross-compiling-from-unix 
I might have missed some critical package/step?

**Comment by musm** [comment]
My bad, I had a configuration/env. variable set in my bashrc file that interacted badly with wine, that lead to the printing of messages like:
```
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
```

In any case removing that, I have some warnings during the compilation process (posted below). 

The main issue I'm experiencing is that the compilation process seems to hang during  the precompilation statement generation step (it seems to hand and never complete).
```
Precompilation complete. Summary:
Total ─────── 121.307485 seconds
Generation ──  88.658005 seconds 73.0854%
Execution ───  32.649480 seconds 26.9146%
**stuck**
```




```julia
$ make -j16
    CC cli/loader_exe.o
    CC cli/loader_lib.o
    CC cli/loader_trampolines.o
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/file_constants.jl
    LINK usr/bin/libjulia.dll
    PERL base/uv_constants.jl
    PERL base/features_h.jl
    PERL base/features_h.jl
    PERL base/features_h.jl
    PERL base/build_h.jl.phony
    ANALYZE usr/bin/libjulia.dll
    LINK usr/bin/julia.exe
    PERL base/version_git.jl.phony
    CC usr/bin/libllvmcalltest.dll
    CC usr/bin/libccalltest.dll
    FLISP src/julia_flisp.boot
chmod a+x /home/mus/julia/julia.bat
    FLISP src/julia_flisp.boot.inc
    CC src/jloptions.o
    CC src/runtime_ccall.o
    CC src/rtutils.o
    CC src/codegen.o
    CC src/llvm-ptls.o
    CC src/jltypes.o
    CC src/gf.o
    CC src/typemap.o
    CC src/smallintset.o
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/interpreter.o
    CC src/symbol.o
    CC src/dlload.o
In file included from /home/mus/julia/src/codegen.cpp:57:
/home/mus/julia/usr/include/llvm/ADT/Statistic.h:38: warning: "LLVM_ENABLE_STATS" redefined
   38 | #define LLVM_ENABLE_STATS 1
      |
In file included from /home/mus/julia/src/codegen.cpp:3:
/home/mus/julia/src/llvm-version.h:24: note: this is the location of the previous definition
   24 | #define LLVM_ENABLE_STATS 0
      |
    CC src/init.o
    CC src/sys.o
    CC src/task.o
    CC src/array.o
    CC src/dump.o
    CC src/staticdata.o
    CC src/toplevel.o
    CC src/jl_uv.o
/home/mus/julia/src/sys.c: In function ‘jl_dllist’:
/home/mus/julia/src/sys.c:609:14: warning: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  609 |         free(path);
      |              ^~~~
In file included from /home/mus/julia/src/sys.c:8:
/usr/share/mingw-w64/include/stdlib.h:530:27: note: expected ‘void *’ but argument is of type ‘const char *’
  530 |   void __cdecl free(void *_Memory);
      |                     ~~~~~~^~~~~~~
    CC src/datatype.o
    CC src/simplevector.o
    CC src/runtime_intrinsics.o
    CC src/precompile.o
    CC src/threading.o
    CC src/partr.o
    CC src/stackwalk.o
    CC src/gc.o
    CC src/gc-debug.o
    CC src/gc-pages.o
    CC src/gc-stacks.o
    CC src/method.o
    CC src/jlapi.o
    CC src/signal-handling.o
    CC src/safepoint.o
    CC src/timing.o
    CC src/subtype.o
    CC src/crc32c.o
    CC src/APInt-C.o
    CC src/processor.o
/home/mus/julia/src/jlapi.c: In function ‘repl_entrypoint’:
/home/mus/julia/src/jlapi.c:692:9: warning: implicit declaration of function ‘execv’ [-Wimplicit-function-declaration]
  692 |         execv("/proc/self/exe", orig_argv);
      |         ^~~~~
    CC src/ircode.o
    CC src/opaque_closure.o
    CC src/jitlayers.o
    CC src/aotcompile.o
    CC src/debuginfo.o
    CC src/disasm.o
    CC src/llvm-simdloop.o
    CC src/llvm-muladd.o
    CC src/llvm-final-gc-lowering.o
    CC src/llvm-pass-helpers.o
    CC src/llvm-late-gc-lowering.o
    CC src/llvm-lower-handlers.o
    CC src/llvm-gc-invariant-verifier.o
    CC src/llvm-propagate-addrspaces.o
    CC src/llvm-multiversioning.o
    CC src/llvm-alloc-opt.o
    CC src/cgmemmgr.o
    CC src/llvm-api.o
    CC src/llvm-remove-addrspaces.o
    CC src/llvm-remove-ni.o
/home/mus/julia/src/jitlayers.cpp: In function ‘jl_value_t* (* _jl_compile_codeinst(jl_code_instance_t*, jl_code_info_t*, size_t))(jl_value_t*, jl_value_t**, uint32_t, _jl_code_instance_t*)’:
/home/mus/julia/src/jitlayers.cpp:220:45: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  220 |             jl_printf(dump_compiles_stream, "%" PRIu64 "\t\"", end_time - start_time);
      |                                             ^~~~~~~~~~~~~~~~~
/home/mus/julia/src/jitlayers.cpp:220:45: warning: too many arguments for format [-Wformat-extra-args]
/home/mus/julia/src/jitlayers.cpp: In member function ‘virtual CompilerResultT JuliaOJIT::CompilerT::operator()(llvm::Module&)’:
/home/mus/julia/src/jitlayers.cpp:580:69: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘long long int’ [-Wformat=]
  580 |             jl_printf(dump_llvm_opt_stream, "        basicblocks: %lu\n", countBasicBlocks(F));
      |                                                                   ~~^     ~~~~~~~~~~~~~~~~~~~
      |                                                                     |                     |
      |                                                                     long unsigned int     long long int
      |                                                                   %I64u
/home/mus/julia/src/jitlayers.cpp:635:41: warning: unknown conversion type character ‘l’ in format [-Wformat=]
  635 |         jl_printf(dump_llvm_opt_stream, "  time_ns: %" PRIu64 "\n", end_time - start_time);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mus/julia/src/jitlayers.cpp:635:41: warning: too many arguments for format [-Wformat-extra-args]
/home/mus/julia/src/jitlayers.cpp:646:69: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘long long int’ [-Wformat=]
  646 |             jl_printf(dump_llvm_opt_stream, "        basicblocks: %lu\n", countBasicBlocks(F));
      |                                                                   ~~^     ~~~~~~~~~~~~~~~~~~~
      |                                                                     |                     |
      |                                                                     long unsigned int     long long int
      |                                                                   %I64u
    CC src/llvm-julia-licm.o
    CC src/llvm-demote-float16.o
    LINK usr/bin/libjulia-internal.dll
    JULIA usr/lib/julia/corecompiler.ji
    JULIA usr/lib/julia/sys.ji
```

**Comment by Keno** [comment]
> **Update**, after an awfully long time, it managed to finish the precompilation process. However, running the executable leads to following errors:

You can set the WINEPATH to the bin directory and it'll find it, but I thought the new stdlib jll work took care of this. @staticfloat ?

**Comment by vtjnash** [comment]
My guess is this is something wrong with wine, since the same build works fine without the PATH modifications on Windows

**Comment by musm** [comment]
I agree with this patch (many, many thanks for the effort!), although I think we should keep the original issue open since cross-compilation is still not 100% functioning.

**Pull request merged**
