### PR TITLE
Bump to CSL to 1.0.3 and link it msvcr120.a to the package images

### PR DESCRIPTION
**Pull request by gbaraldi**
This is so that we can remove the openlibm dependency from base julia

### CODE REVIEW

**Comment by vchuravy** [comment]
As far as I understand it one shouldn't link against a specific version of msvcr. Please check the clang wrapper script for windows-gnu. IIRC there msvcr is not linked, and we only link msvcrt.

**Comment by gbaraldi** [comment]
The issue is that the msvcrt we link to doesn't have some functions, in fact linking to the system msvcrt is not supported at all by microsoft. I believe the "correct" way of doing this is to add one of those .exes that download a specific mscvrt.dll.

**Comment by vchuravy** [comment]
Yeah no, that seems strictly worse than continuing to ship openlibm.

**Comment by gbaraldi** [comment]
Yeah, I guess ucrt is the only way of doing this in a non awful way.

**Pull request closed without merging**
