### PR TITLE
simplify and speed up front end

### PR DESCRIPTION
**Pull request by JeffBezanson**
This removes 3 passes and 300 LOC from lowering. It's significantly cleaner, and I see about a 10% speedup on `using Gadfly` with --compilecache=no.

### CODE REVIEW

**Comment by vtjnash** [comment]
since this code is fresh in your mind right now, can we get some real comments in there? I would gladly see +300 lines if that meant I could actually review what these changes do to the code.

**Comment by JeffBezanson** [comment]
Ok, I will add comments.

Among other things, the 6 passes are now clearly marked with `;; pass #` comments, and all the code in a section is used only by that pass. So it should be much easier to read than before.

**Comment by JeffreySarnoff** [comment]
wow .. good plan that, Jeff

**Comment by timholy** [comment]
:cake: Really nice!

**Comment by stevengj** [comment]
This PR seems likely to have caused #15072.

**Pull request merged**
