### PR TITLE
WIP: `readlink` function

### PR DESCRIPTION
**Pull request by ghost**
Necessary for #10506 and simply wraps libuv.  This is my first time working against libuv and working with `ccall`, any feedback is very much appreciated.  Also, should we export `readlink`?  For now I only exported it from `Base.FS`.

### CODE REVIEW

**Comment by ninjin** [comment]
Failing due to white space errors in a commit with [ci skip].  Preparing a separate PR to fix this.

**Comment by ninjin** [comment]
CI run now pending on #10572.

**Comment by tkelman** [comment]
I restarted the travis build for you. Though I think it might be better to add a wrapper function in C in `jl_uv.c`, so the Julia-side `ccall` version is simpler. That's the approach I took in #7590 for example.

**Comment by tkelman** [comment]
And as far as exporting goes, considering the number of other filesystem-related functions we currently export, I think exporting `readlink` would be good for now. Un-exporting portions of `FS` might be good to do eventually, but probably best to do a bunch of them at the same time, and export this for now.

**Comment by Keno** [comment]
Either this or a separate wrapper in `jl_uv.c` is fine to me (a separate wrapper is probably slightly better since you can put the fs struct on the stack, but you're doing a system call anyway, so it doesn't matter much). Also needs docs though.

**Comment by ninjin** [comment]
Should this be closed in favour of #10714.  I am now back from a conference and would be fine with finishing this, but it seems that there are two independent efforts at this point.

**Comment by tkelman** [comment]
Sure, though your input there would of course be welcome. It might be useful to keep your all-Julia-side implementation of `readlink` around for reference, since I'm not sure exactly how much of the function we will actually want to do in C vs Julia for the final version.

**Pull request closed without merging**
