### PR TITLE
Improve robustness in Dates/conversions test

### LINKED ISSUE #48272: Dates/conversions test bug
```
Dates/conversions                                (5) |         failed at 2023-01-11T13:59:58.377
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-1.0/build/default-macmini-x64-1-0/julialang/julia-master/julia-6034d94057/share/julia/stdlib/v1.10/Dates/test/conversions.jl:63
  Expression: abs(Dates.now() - now(Dates.UTC)) < Dates.Second(1)
   Evaluated: Dates.Millisecond(1001) < Dates.Second(1)
```

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/48223#issuecomment-1381934255_

### PR DESCRIPTION
**Pull request by Keno**
In [1], this test was observed to fail, with a 1 second pause between the two Dates.now calls. In general, particularly on high-load CI systems, we cannot make assumptions that calls will complete within any particular amount of time. Instead, we should be asserting properties that should be universally true. This test wants to assert that Dates.now() and Dates.now(UTC) give the same answer if the TZ environment variable is set appropriately, but of course we can't guarantee that these calls run at the same time. Rather than setting an arbitrary limit of 1 second, just run `Dates.now` again. Our semantics guarantee ordering of these calls (in the absence of leap days/seconds at least), so the test is more robust.

[1] https://buildkite.com/julialang/julia-master/builds/22064#0186ff11-f07e-4ba4-9b54-21bdf738d35e

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
Fixes https://github.com/JuliaLang/julia/issues/48272

**Comment by Keno** [comment]
Welp, the test failed on CI.

**Comment by Keno** [comment]
Ah, the issue is that `now()` truncates, while `now(UTC)` rounds. I'm thinking truncation is the correct behavior for these functions, so I'll add an appropriate commit.

**Comment by Keno** [comment]
Actually, scratch that, they're both using the same precision, so the rounding and truncation shouldn't make a difference.

**Comment by Keno** [comment]
Alright, added a commit to truncate `now(UTC)` rather than rounding and deleted the comment I made where I was temporarily confused.

**Pull request merged**
