### PR TITLE
updates documentation for `Test.finish`

### PR DESCRIPTION
**Pull request by ssfrr**
remind custom testset implementers to add themselves to their parent's results when they `finish`

Making sure that custom testsets add themselves to their parent is required so we can wrap the tests in a higher-level testset, as [TestReports.jl](https://github.com/oxinabox/TestReports.jl) does.

@oxinabox @c42f

### CODE REVIEW

**Comment by oxinabox** [comment]
Hmmmm

If it is required, then maybe it should move out of the `finish` function entirely, and into the code that calls `finish`.
If it is not required then it is not required.

As so this should say:

```
Custom `AbstractTestSet` subtypes normally should call `record` on their parent (if there
 as one) to add themselves to the tree of test results.
This allows ...
This might be implemented...
```

**Comment by c42f** [comment]
That's a pretty good point @oxinabox, it seems like a cleaner way forward to always record a test set with its parent inside `testset_beginend()`. Although quite tricky to deprecate the current way, as people would generally be extending `record` rather than just calling it.  I suppose a binding deprecation would work, but then we'd need to dream up a new name other than `record`.

To me it seems odd that the child test set should get to control whether it's added to the tree.

**Comment by oxinabox** [comment]
We could just do a documented breaking change and fix the very small number of packages that actually extend AbstractTestSet.

**Comment by ssfrr** [comment]
I agree that it would be better to just make it happen in the code that calls `finish` rather than having boilerplate that folks extending `finish` need to add. I don't have time to put together a PR in the next couple days, but maybe in the next week. This change wouldn't actually break my `ExtendedTestSet` because my `finish` just calls the `finish` on the wrapped testset, so it'll keep whatever the `DefaultTestSet` does.

It's up to the powers-that-be whether this kind of change could make it into 0.7 or if it's too late. I doubt there are many other custom `AbstractTestSet` subtypes that would break if they got added to their parent automatically on `finish`, but I don't have a super strong intuition on it.

@kshyatt would that break any of your Base testing stuff?

**Comment by ViralBShah** [comment]
Is this something we still need in the docs? If not, would be nice to close.

**Comment by oxinabox** [comment]
I don't know if this is still how `AbstractTestset`s work.
If it is then it should be merged.

**Comment by vtjnash** [comment]
Yes, note that this PR should replace the previous sentence "One common use for this...", as it is stating the same thing, only clearer. Could you rebase and merge?

**Pull request merged**
