### PR TITLE
Use externally hosted DelimitedFiles and move it out of the sysimage

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
Is it meaningful to run `pkgeval` here?

**Comment by KristofferC** [comment]
> Is it meaningful to run pkgeval here?

Somewhat since it moves out DelimitedFiles from the sysimage which could, in theory, have some adverse effects.

@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/45121#issuecomment-1114567322) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/2f68920_vs_ef1c9ce/report.html).

**Comment by ViralBShah** [comment]
I thought a lot more packages would be affected. Unless I am reading something incorrectly, It seems like this is good to merge.

**Comment by ViralBShah** [comment]
Should DelimitedFiles.jl be registered in General before or after this merge?

cc @giordano

**Comment by giordano** [comment]
I presume it should, yes

**Comment by ViralBShah** [comment]
Looks like we should go ahead with this.

**Comment by KristofferC** [comment]
Should be good to go now I think

**Comment by ViralBShah** [comment]
I say we hit merge!

**Comment by ViralBShah** [comment]
DelimitedFiles is not yet moved out of stdlibs. It is just not in the system image. There are other issues to work through (https://github.com/JuliaLang/julia/pull/45540#issuecomment-1147320471) before it can truly move out, and at that point we should remove the docs.

**Pull request merged**
