### PR TITLE
🤖 Bump the Pkg stdlib from fff928aa to 32880c47

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: Pkg
URL: https://github.com/JuliaLang/Pkg.jl.git
Branch: master
Old commit: fff928aa
New commit: 32880c47
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

```
$ git log --oneline fff928aa..32880c47
32880c47 Set `__precompile__(false)` in the `ArtifactOverrideLoading` test package (#2921)
e54b3dee Remove duplicate resolve in `pkg> compat` (#2923)
d39a5ad2 CI: Fix git and 7zip not using default io (#2919)
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
After this bump, the Pkg tests should not produce any output unless a test fails. So the build logs (on Base Julia CI, and also when a user runs `make testall` locally) should be much cleaner.

**Comment by DilumAluthge** [comment]
@staticfloat The tsan and analyzegc failures look like download issues? I reran them but they still failed.

**Comment by DilumAluthge** [comment]
Of course it doesn't actually print the URLs that it was trying to download 😭

**Comment by staticfloat** [comment]
Looks like `Clang-v13.0.0+3` [doesn't exist](https://github.com/JuliaBinaryWrappers/Clang_jll.jl/releases/)

**Comment by staticfloat** [comment]
This is being fixed by this build as it wends its way through the ecosystem: https://github.com/JuliaPackaging/Yggdrasil/pull/4198

**Comment by staticfloat** [comment]
> Of course it doesn't actually print the URLs that it was trying to download 😭

For the record, it prints the URL its trying to download here: https://buildkite.com/julialang/julia-master/builds/7277#7f4caaaa-9d0b-4558-91c4-b8a276f4fcdb/161-178

**Comment by staticfloat** [comment]
Alright, they're passing now. :)

**Pull request merged**
