### PR TITLE
Correction of a typo in file disasm.cpp.

### PR DESCRIPTION
**Pull request by thiagopeixoto**
It should be stream (instead of streamer).

### CODE REVIEW

**Comment by tkelman** [comment]
Looks like this was in a llvm 3.3 block, so if it broke that's a sign of missing test coverage.

**Comment by yuyichao** [comment]
I think it's because this is not compiled on x86

**Comment by tkelman** [comment]
The second one should be? `#elif defined(_CPU_X86_) || defined(_CPU_X86_64_)` ?

**Comment by yuyichao** [comment]
The second one is after the `#else` at `https://github.com/JuliaLang/julia/pull/14311/files#diff-5060fdfc5cb40a40ce5729ca8c4e4cf2L594`.

Do we support non ppc, non arm, non x86(or x64) architectures?.....

**Comment by thiagopeixoto** [comment]
@yuyichao True. I was compiling on ppc64.

**Pull request merged**
