### PR TITLE
bump the Tar stdlib from 5606269 to 5914ef9

### PR DESCRIPTION
**Pull request by ranocha**
I updated the Tar.jl stdlib. There have been some invalidation fixes recently, so I would like to get this backported to Julia 1.8.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
For external stdlibs (i.e. stdlibs that live in external repos), the backport process is a little bit different. We don't apply the backport label to the bump PR in this repo. Instead, the external stdlib needs to go through its own backports process. The full details are here: https://github.com/JuliaSparse/SparseArrays.jl/issues/249

**Comment by ranocha** [comment]
Okay, thanks for the info. I didn't know that. Do you have the rights to create these branches there? I don't, so I can't help with that.
Note that we currently just use the `master` of Tar.jl in Julia. This PR bumps the version to the latest version on `master`.

**Comment by DilumAluthge** [comment]
According to https://github.com/JuliaLang/julia/blob/release-1.8/stdlib/Tar.version, the `release-1.8` branch of the `JuliaLang/julia` repo is currently using the `0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595` commit of the `JuliaIO/Tar.jl` repo:

https://github.com/JuliaLang/julia/blob/afb6c60d69a38e8a2442a0c7e87c47b8880ad294/stdlib/Tar.version#L1-L4

In the `JuliaIO/Tar.jl` repo, at the `0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595` commit, the `Project.toml` file has the version number `1.10.0`:

https://github.com/JuliaIO/Tar.jl/blob/0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595/Project.toml#L1-L4

Therefore, I have created the [`release-1.10`](https://github.com/JuliaIO/Tar.jl/tree/release-1.10) branch in the `JuliaIO/Tar.jl` repo, where the branch points to the `0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595` commit. To do this, I ran the following steps:

```
cd $(mktemp -d)
git clone git@github.com:JuliaIO/Tar.jl.git
cd Tar.jl
git branch release-1.10 0f8a73d5cd4b0c8f1f3c36799c96e9515e9dc595
git push origin release-1.10
cd ..
rm -rf Tar.jl
```

Now, you should be able to make a backports PR in the `JuliaIO/Tar.jl` repo where the target branch of the PR is the `release-1.10` branch in that repo.

**Comment by DilumAluthge** [comment]
> Note that we currently just use the `master` of Tar.jl in Julia.

Ah, good catch. I've made a PR to fix that: https://github.com/JuliaLang/julia/pull/46733

**Comment by ranocha** [comment]
@DilumAluthge I made a PR to Tar.jl following your instructions. How shall we proceed with this PR?

**Pull request merged**
