### PR TITLE
InteractiveUtils: add `@trace_compile` and `@trace_dispatch`

### PR DESCRIPTION
**Pull request by IanButterworth**
Sometimes you just want to see what's compiling in a live session rather than restart into a dedicated session with trace-compile on.

```
julia> @trace_compile rand(2,2) * rand(2,2)
#=   39.1 ms =# precompile(Tuple{typeof(Base.rand), Int64, Int64})
#=  102.0 ms =# precompile(Tuple{typeof(Base.:(*)), Array{Float64, 2}, Array{Float64, 2}})
2×2 Matrix{Float64}:
 0.421704  0.864841
 0.211262  0.444366

```

Another benefit is being able to use it in conjunction with `@time` and `@time_imports`
```
 @time @time_imports @trace_compile using Foo
```

I think it also makes sense to add `@trace_dispatch` after https://github.com/JuliaLang/julia/pull/55848 is merged.

### CODE REVIEW

**Comment by IanButterworth** [comment]
@kpamnany FYI I've added `@trace_dispatch`

**Comment by NHDaly** [comment]
Very cool, Ian! 🎉 
Would it make sense to be able to return them into _data_, rather than just logging them? It seems like a logical extension of this. Or is this starting to encroach too much on what `@snoopi` is for? At that point should you just use SnoopCompile.jl?

**Comment by IanButterworth** [comment]
Yeah I think that's `@snoopi`'s job.

**Comment by mchitre** [comment]
This is neat. But I couldn't get it to work on `1.12.0-beta1`. What I am doing wrong?
```
~> julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-beta1 (2025-04-02)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org release
|__/                   |

julia> @trace_compile rand(2,2) * rand(2,2)
2×2 Matrix{Float64}:
 0.609135  0.38003
 0.348457  0.147205
```

**Comment by IanButterworth** [comment]
Seems like that's just precompiled into the sysimage now. We should update the example with something more robust.
```
julia> @trace_compile rand(2,2) * rand(2,2)
2×2 Matrix{Float64}:
 0.63066   0.478856
 0.868522  0.570842

julia> @trace_compile peakflops()
#=    1.8 ms =# precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:eltype, :ntrials, :parallel), Tuple{DataType, Int64, Bool}}, typeof(LinearAlgebra.peakflops), Int64})
#=    6.1 ms =# precompile(Tuple{typeof(Base.ones), Type{Float64}, Int64, Int64})
#=    4.3 ms =# precompile(Tuple{typeof(Base.:(*)), Array{Float64, 2}, Array{Float64, 2}})
2.8982161668827673e11
```

**Comment by IanButterworth** [comment]
Ah, actually it's the same issue `@time` has. We need `@eval`
```
julia> @trace_compile @eval rand(2,2) * rand(2,2)
#=   14.7 ms =# precompile(Tuple{Core.GeneratedFunctionStub, UInt64, Method, Any, Vararg{Any}}) # recompile
#=   37.9 ms =# precompile(Tuple{typeof(Base.rand), Int64, Int64})
#=    3.0 ms =# precompile(Tuple{typeof(Base.:(*)), Array{Float64, 2}, Array{Float64, 2}})
2×2 Matrix{Float64}:
 0.315353  0.341938
 0.383044  0.949558
```

**Comment by mchitre** [comment]
Fair enough. I can get `peakflops()` to trace:
```julia
julia> @trace_compile peakflops()
#=    1.6 ms =# precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:eltype, :ntrials, :parallel), Tuple{DataType, Int64, Bool}}, typeof(LinearAlgebra.peakflops), Int64})
#=    6.9 ms =# precompile(Tuple{typeof(Base.ones), Type{Float64}, Int64, Int64})
#=    4.1 ms =# precompile(Tuple{typeof(Base.:(*)), Array{Float64, 2}, Array{Float64, 2}})
#=    3.2 ms =# precompile(Tuple{typeof(Base.getindex), Array{Float64, 2}, Int64, Int64})
4.189704786348609e11
```
but why not this then?
```julia
julia> f(x) = 2x
f (generic function with 1 method)

julia> g(x) = f(x) + f(x+1)
g (generic function with 1 method)

julia> @trace_compile g(7)
30
```

**Comment by mchitre** [comment]
Indeed...
```julia
julia> @trace_compile @eval g(7)
#=    1.5 ms =# precompile(Tuple{typeof(Main.g), Int64})
30
```

Thanks!

**Pull request merged**
