### PR TITLE
Remove outdated README.arm.md

### PR DESCRIPTION
**Pull request by ViralBShah**
The ARM build is now just part of the regular build process and not much in the way of special stuff is required. 

[ci skip]

### CODE REVIEW

**Comment by simonbyrne** [comment]
The raspberry pi specific information is still useful.

**Comment by simonbyrne** [comment]
Actually, we could move the raspi specific stuff to https://github.com/JuliaBerry/juliaberry.github.io

**Comment by simonbyrne** [comment]
The raspberry pi specific stuff is now here: https://juliaberry.github.io/compile.html

Some of the more generic stuff (required instruction sets, manually setting `MARCH`) might be useful to have in the general README.

**Comment by ViralBShah** [comment]
There's a bunch of other ARM architectures in there as well. Leaving this as is for now as it can serve a good starting point for people looking to make Julia on ARM better.

**Pull request closed without merging**
