### PR TITLE
Added tests for +,- for UniformScaling matrices

### PR DESCRIPTION
**Pull request by suraj-shivu**
This is for the functions with UniformScaling Type as their first operand

### CODE REVIEW

**Review by dkarrasch — CHANGES_REQUESTED** [review]
I think we should avoid the code duplication. If I'm not mistaken, we can achieve the same code coverage by adding a line after line 154 with `A` and `B` interchanged. Moreover, I assume that the `*` in line 145 is a typo, according to the testset header. So, either we replace it by `-`, or we add `-` there, which I'd advocate for. Then we could remove the entire new testset.

**Comment by suraj-shivu** [comment]
I think the * isn't a typo and the - there would cause step size 0 errors as written in the to-do, when i tried the suggested edits. So I added a couple of selection statements to go about this.

**Comment by dkarrasch** [comment]
Ok, then I suggest not to touch the `A in mats, B in mats` part, because the purpose of the PR is to cover `UniformScaling` methods. Like have the old outer `for op in (+,*)` loop for the `(mats, mats)` case, and then a new `for op in (+,-)` loop for the `A in mats, B in uniformscalingmats` case.

**Review by dkarrasch — APPROVED** [review]
Very clean, very nice.

**Pull request merged**
