### PR TITLE
LinearAlgebra remove unused export

### PR DESCRIPTION
**Pull request by KristofferC**
Maybe we should CI that nothing exports undefined symbols?

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Review by andreasnoack — APPROVED** [review]

**Comment by Jutho** [comment]
Is it actually useful to export all these factorization types. I don't think they are often constructed explicitly/directly in user code?  I sometimes have a name clash while scripting, because I have a variable that is called QR (which has nothing to do with _the_ QR).

**Comment by fredrikekre** [comment]
> Is it useful that all these types are exported?

Which ones are not useful?

> More generally, should the export ...

Yea, I think it is ok for `LinearAlgebra` to export more stuff than what was reexported from Base, since it is required to `using LinearAlgebra` to make them visible in your module.

**Comment by Jutho** [comment]
> Which ones are not useful?

My apologies if I was not clear; I meant the factorization types, i.e.
```julia
    Factorization,
    BunchKaufman,
    Cholesky,
    CholeskyPivoted,
    Eigen,
    GeneralizedEigen,
    GeneralizedSVD,
    GeneralizedSchur,
    Hessenberg,
    LU,
    LDLt,
    QR,
    QRPivoted,
    LQ,
    Schur,
    SVD,
```
I don't think these are ever directly called or constructed, but only arise as output of the corresponding lowercase functions. This is different from e.g. `Symmetric` or `UppperTriangular` which are directly called for construction, and should indeed definitely be exported.

**Comment by andreasnoack** [comment]
I think it would be fine not to export the factorization types. As you point out, normal users should never need to use them explicitly.

**Pull request merged**
