### PR TITLE
Add test for #11497

### PR DESCRIPTION
**Pull request by yuyichao**
@JeffBezanson This is the test only part of #11495 plus additional tests for #11497.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Perhaps it would make sense to change parse so that when the input is multiple whole expressions it returns a quoted block of those expressions. Eg:

```jl
julia> parse("""
       1 + 2
       println("Hello")
       """)
quote  # none, line 2:
    1 + 2 # line 3:
    println("Hello")
end
```

Currently this throws an error: `ParseError("extra token after end of expression")`.

**Comment by StefanKarpinski** [comment]
@JeffBezanson, @jakebolewski?

**Comment by yuyichao** [comment]
@StefanKarpinski Yeah. I was asking about that in https://github.com/JuliaLang/julia/pull/11495#issuecomment-107930455 . I didn't get a reply so I'm keeping the current behavior for now.

**Comment by JeffBezanson** [comment]
I don't know; it seems a bit magical to me, given that there isn't any block syntax in the input.

**Comment by yuyichao** [comment]
@JeffBezanson
What about keeping `parse` as is and add another function that returns an (`Any`) array of parse results?

**Comment by hayd** [comment]
A hack to get the `parseall` behavior described above with correct line numbers.
```
parseall(s::AbstractString) = eval(parse("""quote $s end"""))
```
Is there an open issue for this ?

**Pull request merged**
