### PR TITLE
[release-0.6] backports for 0.6.0-rc2

### PR DESCRIPTION
**Pull request by tkelman**
- [x] pkgeval
- [x] @nanosoldier `runbenchmarks(ALL, vs = "@6bdb3950bdf64152")` vs 0.6.0-rc1

### CODE REVIEW

**Comment by tkelman** [comment]
oh and let's try @jlbuild !Nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```

**Comment by tkelman** [comment]
are the flags case sensitive or does it just not work any time I try it?
@jlbuild !nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/22aec09c796f35e982400c9a79000d70a7562e79

I will edit this comment as the build jobs complete.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21878) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3bfd94b57987fbbfaea93ac0e3d8ac32901f5ca5/e30ab0e_vs_6bdb395/report.md). cc @jrevels

**Comment by alyst** [comment]
Also 2b4bb1ad966f1a7b72a5a439c31453e325d968a1?

**Comment by tkelman** [comment]
thanks for the reminder, overlooked that one. the case that now errors there would just hang on rc1 or earlier, right?

**Comment by alyst** [comment]
@tkelman exactly, but it should be safe to cherry-pick this commit into 0.5 as well

**Comment by tkelman** [comment]
perf looked fine but may as well run again @nanosoldier `runbenchmarks(ALL, vs = "@6bdb3950bdf64152")` vs 0.6.0-rc1

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21878#issuecomment-301462346) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/71501b254e0e7f509161d7ac778f330d38f3d7f2/477b6d4_vs_6bdb395/report.md). cc @jrevels

**Comment by GregPlowman** [comment]
I guess it's too late for rc2, but would it be possible for PR #21695 to be included before 0.6 final?
And also included in 0.5.3?

**Comment by tkelman** [comment]
d818788 was in pretty good shape on pkgeval https://gist.github.com/df43d5af59dd34a3520e59a57c7ff3d0 with one spurious new failure in LPVSpectral, and Feather is segfaulting on this branch as opposed to freezing on rc1 (it was working up until April 6th though (https://github.com/JuliaCI/pkg.julialang.org/blob/88a41b735886f267c8e71ad63be5b3e7eba38449/logs/Feather_0.6.log)

But I think there have been enough new bugfixes on master that it'd be better to get them in here and re-run pkgeval again.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@6bdb3950bdf64152")` vs 0.6.0-rc1

**Comment by tkelman** [comment]
@jlbuild !nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/be004c1bfebb585932c78c8922b06bde049fb2cb

I will edit this comment as the build jobs complete.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21878#issuecomment-302010108) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/324c7225bd2c7635490d10abf8417f382bed0447/e375d87_vs_6bdb395/report.md). cc @jrevels

**Comment by tkelman** [comment]
ouch, what happened to date parsing?

**Comment by tkelman** [comment]
hm. flaky false alarm then? @nanosoldier `runbenchmarks(ALL, vs = "@6bdb3950bdf64152")` vs 0.6.0-rc1

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21878#issuecomment-302171541) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/cb89ecfbf61a2834487ff8af22fa720ea6ee1eb7/e375d87_vs_6bdb395/report.md). cc @jrevels

**Comment by tkelman** [comment]
https://gist.github.com/4804ae73c6d5cec89d78890617c558dc same Feather issue (https://github.com/JuliaLang/julia/issues/21920) and MatrixNetworks had a tolerance too tight

merging and tagging this as rc2

**Comment by tkelman** [comment]
@staticfloat @yuyichao can you check on and reconnect the old arm buildbot? the new buildbots aren't quite ready to be making releases off of just yet

**Pull request merged**
