### PR TITLE
Apple silicon has 128 byte alignment so fix our defines to match

### PR DESCRIPTION
**Pull request by gbaraldi**
https://github.com/JuliaLang/julia/blob/8a69745bdcb06409ab7e4fc84718f34d7d54a7f9/base/lock.jl#L33-L50 this probably also needs a fix, and maybe other places as well

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
Should we also review the uses of `malloc_cache_align`? This particular field seems to be intended to be the largest sized value that can be loaded in a single instruction, or at least whatever alignment is most optimal for that (in bytes)?

**Comment by gbaraldi** [comment]
I guess we should review these things overall. I'm not sure if it has anything to do with specific instructions because both 64 byte alignment and loads are way to large to matter to instructions and seem to do with caches.

**Comment by gbaraldi** [comment]
I think the goal with `malloc_cache_align` is to make sure that different mallocs don't end up in the same cache line, so the large alignment asked here makes some sense.

**Review by d-netto — APPROVED** [review]
Will probably be useful for https://github.com/JuliaLang/julia/pull/52994.

Can we prioritize merging it and backporting it to 1.10?

Thanks.

**Comment by d-netto** [comment]
Some versions of PPC apparently also have a cache line size of 128 bytes: https://reviews.llvm.org/D33656.

I don't know what's the status of supporting PPC, but it might be a good idea to adjust it as well.

**Comment by vchuravy** [comment]
We only support PPC8+ so yeah wes should adjust for that as well l.

**Pull request merged**
