### PR TITLE
Deprecate Euler number e in favor of ℯ (U+212F)

### PR DESCRIPTION
**Pull request by nalimilan**
This reduces confusion with variables called e, and ℯ is
the Unicode character for "natural exponent". It also
makes this constant more similar to others, which have
both a "special letter" and longer ASCII form.

Cf. #10607

Reference : http://en.wikipedia.org/wiki/Numerals_in_Unicode#Characters_for_mathematical_constants

(Shortest branch name ever!)

### CODE REVIEW

**Comment by kmsquire** [comment]
Would be nice if, e.g., `\e<tab>` completed to `ℯ`

**Comment by nalimilan** [comment]
Yeah, but I'm not sure how to do that.

**Comment by nalimilan** [comment]
With this commit, it looks like the deprecation warning is printed every time, not only on the first call. What am I doing wrong?

**Comment by jverzani** [comment]
As someone who has been teaching students to use Julia as a first language, I hope this doesn't go through. It is a much greater hurdle for a beginner to either define `e=exp(1)` or learn to type `\e<tab>` than for an experienced user to reckon with the difference between `Main.e` and `Base.e`, should they wish to redefine `e`.

**Comment by Keno** [comment]
There's still `eu`. Would that work?

**Comment by joa-quim** [comment]
Me too, please don't do this. I don't even know how to write the manuscript 'e'. Honestly I've seen about the Unicode variables but for me they are a 'nice curious thing' that I never really cared about and should never made mandatory in any case.

**Comment by tkelman** [comment]
`e` as a `MathConst` is kind of a party trick that I personally rarely need. I don't see why it needs to claim single-character name space - every time I use Mathematica, I'm always annoyed I can't name a variable `N`. I'd even prefer being explicit with `MathConst{:e}()` for this.

**Comment by kmsquire** [comment]
There's nothing preventing anyone from using `e` as a variable:

```julia
julia> e = 12345
12345

julia> e^2
152399025

julia> eu^2
7.38905609893065
```

Of course, if you try to use it both as `e` and a variable, you get a nice little warning:

```julia
julia> e
e = 2.7182818284590...

julia> e = pi
Warning: imported binding for e overwritten in module Main
π = 3.1415926535897...

julia> e
π = 3.1415926535897...
```

**Comment by tkelman** [comment]
Out of packages I have installed, LibExpat, Dates, ImmutableArrays, Graphs, StatsBase, DataArrays, WinRPM prior to https://github.com/JuliaLang/WinRPM.jl/commit/41c65323c1a4494f9035ec63162338846291d899, GZip, BloomFilters, Tk, HDF5, BinDeps, DataFrames, an old version of FactCheck, Distributions, Winston, IJulia, Gadfly, and Debug all use `catch e` somewhere. I forget the exact details, but the fact that some of the functions in WinRPM were being called inside a BinDeps macro meant some funny things happened with scope and/or error handling, and the value of `e` in the catch block wound up as the MathConst instead of the caught exception.

**Comment by johnmyleswhite** [comment]
Perhaps there be a MathConsts module that isn't imported by default, but can easily switched on? I see the appeal of having instant access to `e` and `pi`, but am increasingly onboard with trying to shrink the number of names claimed by Base.

**Comment by hayd** [comment]
> Would be nice if, e.g., `\e<tab>` completed to ℯ

Kind of off topic, but it would be great if there was  a way to force tab complete to show all possible completions (starting with e), e.g. `\e<shift+tab>`. It's frustrating when you know how a unicode starts... and you tab expecting to see options only to have a shorter char competed.

**Comment by kmsquire** [comment]
@hayd, in the console REPL, at least, you can hit `<tab>` twice, and that list will appear.  Not sure about other interfaces, though.

**Comment by hayd** [comment]
@kmsquire I don't think that's the case if it's already a complete unicode name. Silly example (I can't recall the more annoying case I was dealing with recently, where this occured much earlier), I'm trying to tab complete to equivDD, but 

```
julia> \equ         # This at least shows the options
\equalleftarrow \equalparallel   \equiv           \equivDD
julia> \equi<TAB>   # becomes (without showing options, suppose I start here)
julia> \equiv<TAB>  # becomes
julia> ≡            # I wanted \equivDD :(
```
Or, more annoyingly, I know it starts with c...
```
julia> \c<TAB>   # no options
julia> ̧
```

**Comment by JeffBezanson** [comment]
@tkelman that kind of sounds like a bug, either in the macro expander or one of the macros themselves. Saying that a certain piece of code --- even Base --- should avoid a certain variable name should not be necessary for sane scoping.

`e` has never gotten in my way, but there are still some things to be said for not exporting a 1-letter variable.

**Comment by ViralBShah** [comment]
I would be OK with MathConsts not being imported by default. Also OK with eu as the name.

**Comment by nalimilan** [comment]
Updated with the `\e[tab]` replacement rule. IMHO that's as a good compromise, very similar to what we have for `pi` and all other constants, which don't have the privilege a single ASCII letter symbol just for them. My take is that somebody who used `e` for an exception in a scope where the variable is not defined (e.g. after copy/paste) will be more more confused by seeing an error message about `2.71...` than users of the constant will be be typing `eu` or `\e[tab]`.

I've been able to fix the problem of repeated deprecation warnings for most cases, except when calling `Float64` (and other constructors) from inside a function. It works fine from the REPL, though. I'm defining both `call` and `convert`, but no luck. Any ideas?

**Comment by mschauer** [comment]
Are there actually sources for the wiki claim that "U+212F ℯ script small e" is somehow related to "natural exponent"? This would contradict ISO 80000-2.

**Comment by nalimilan** [comment]
@mschauer Any copy of the Unicode standard will do, e.g. http://unicode.org/charts///PDF/Unicode-4.1/U41-2100.pdf It's true that ISO 80000-2 uses `e`, but well, it also says that the imaginary unit should be written `i`. No idea how Unicode decided to recommend `ℯ`.

**Comment by simonbyrne** [comment]
+1: e is one of the less useful constants for numerical software, since its main use is `e^x == exp(x)`.

I would also be in favour of ⅈ (u+2148) for `im`.

**Comment by mschauer** [comment]
@nalimilan Ok, not our problem ;-)

**Comment by simonbyrne** [comment]
This will also help with things like:
```
julia> 2e
5.43656365691809

julia> 2e-1
0.2
```

**Comment by StefanKarpinski** [comment]
Not really – that still means the same thing, regardless of whether `e` is defined or not.

**Comment by simonbyrne** [comment]
Yes, but now at least one will throw an error (unless the user defines `e` of course).

**Comment by nalimilan** [comment]
`2e-1` is indeed a striking example...

**Comment by StefanKarpinski** [comment]
That's an argument against numeric literal juxtaposition, not using the name `e`.

**Comment by JeffBezanson** [comment]
I think I agree with @jverzani here; not enough benefit to be worth the shakeup. Adding an alias ℯ seems ok though.

**Comment by nalimilan** [comment]
@StefanKarpinski That would be an argument in favor of preventing any variable called `e`. ;-)
(At least, not in favor of shipping by default such an object.)

**Comment by nalimilan** [comment]
@JeffBezanson I'm not sure adding an alias has much value: one of the points was to avoid `e` being implicitly used when you thought a local variable would be called that way. Adding another constant does not improve this -- almost the contrary.

**Comment by tkelman** [comment]
> that kind of sounds like a bug, either in the macro expander or one of the macros themselves

Entirely possible. It might be some hygiene thing that's way above my pay grade to fix. Either way, I think variable names that shadow default exports from Base should be considered a bad practice and linted against (maybe they are already? I should check Lint.jl), which is an argument for both having fewer default exports from Base, and being more careful what you name everything in user code.

**Comment by stevengj** [comment]
I don't think that variable names shadowing Base should be Lint warnings.   Base is just too huge (and continually growing) to avoid collisions from time to time, nor is this a big problem.   I also agree that removing `e` is not worth the shakeup.   (And Julia has had a consistent policy of not *requiring* Unicode to access anything in Base; Unicode identifiers are only aliases.)

Adding an alias would have the benefit that you could use `e` as a local variable while still accessing `ℯ`, though frankly I would be wary of writing such code—seems too confusing and font-dependent to be worth the trouble.

**Comment by tkelman** [comment]
> nor is this a big problem

From years of this being a problem in Matlab code, it is a problem. Julia has better scoping than Matlab, but that only makes issues less likely, not impossible. If you shadow a name from base in your local code, then any following code that executes at the same scope may have an entirely different meaning than what it was written for.

**Comment by JeffBezanson** [comment]
> any following code that executes at the same scope may have an entirely different meaning

How exactly would this happen? It seems to me this would only happen for code un-hygienically pasted somewhere, which isn't going to work anyway.

**Comment by tkelman** [comment]
> un-hygienically pasted somewhere

`include` ?

**Comment by JeffBezanson** [comment]
Yes, that's an example. The only way to fix issues around that is to remove `include`, as some have loudly requested. Guessing which names are likely to collide is not a solution. Plus, collisions caused by `include` have little to do with `Base` exports. You'll have a problem composing two files with `include` that want to use `e` differently regardless of what `Base` exports.

**Comment by tkelman** [comment]
Exports from `Base` are actually used by code with an expectation of already having a specific meaning, other arbitrary names aren't. This may be an emerging anti-pattern, but for lack of a better established practice, most packages tend to be composed of multiple files `include`d into a single module. If someone makes a pull request to change something in the first of those files that happens to use, say, `indmax` as a result of a some local computation, it can break code in later files in a way that using other names that don't have default assigned meanings to them generally won't.

**Comment by JeffBezanson** [comment]
That isn't true --- using `indmax` as a local variable won't break anything. As a global variable it could, but that's entirely an issue with `include` and global variables. I think it's silly to try to fix `include` just by editing the list of Base exports.

**Comment by tkelman** [comment]
This maybe isn't worth un-exporting `e` over, but I still think using a `Base` export as a (global, or module-global) variable name should be avoided and linted against.

**Comment by Keno** [comment]
I think the unicode issue here is a side track. There already is the ASCII `eu` identifier. I think having a two character constant instead of a one character one is totally worth it. I use one-character variable names all the time, e.g. `for e in events` .

**Comment by kmsquire** [comment]
Just curious, does anyone have an example where they've actually run into
this issue--specifically where they attempted to use "e" as both a local
variable and as the mathematical constant within the same scope?

**Comment by simonbyrne** [comment]
> Just curious, does anyone have an example where they've actually run into
this issue--specifically where they attempted to use "e" as both a local
variable and as the mathematical constant within the same scope?

I would be curious to know if anyone has ever actually used the `e` mathematical constant?

**Comment by StefanKarpinski** [comment]
I feel like this used to not be true:

```jl
julia> exp(1) == Float64(e)
true

julia> exp(big(1)) == BigFloat(e)
true
```

Given that it is now true, it may be reasonable to just ditch the constant altogether, unless there are cases where people really like to use it. One nice thing is that for a matrix `M` the expression `e^M` does `expm(M)` while `e.^M` does `exp(M)`. IMO, that's a lot clearer than explaining the difference between those two functions.

**Comment by toivoh** [comment]
Should we make `e^x` the idiomatic way to evaluate `exp(x)` as well? I've never thought about that possibility before, but maybe the fact that it requires the magical mathconst for e makes it a bit too opaque to see that you are not calling `pow`.

**Comment by StefanKarpinski** [comment]
Yeah, that's the down side. I'm not convinced that it's necessarily a good idea. It reads nicely and is clear to me, but I already know what's going on.

**Comment by mlubin** [comment]
> Should we make e^x the idiomatic way to evaluate exp(x) as well?

Please don't, it means we'll have to add a special case for the expression parsing in JuMP.

**Comment by jiahao** [comment]
Both `e^x` and `exp(x)` show up very often in the mathematical literature. Removing `exp(x)` would confuse a great many users.

In practice you don't save much in terms of clarity when exponentiating a long expression, since you'd have `e^(very long expression)` vs `exp(very long expression)`. Consider that people routinely write expressions [like these](http://en.wikipedia.org/wiki/Functional_integration#Examples) or [pdf, p5](http://hitoshi.berkeley.edu/221a/pathintegral.pdf).

**Comment by JeffBezanson** [comment]
As everybody probably knows, I'd rather have `exp(M)` compute the matrix exponential than have expm and the vectorized :shudder: version.

**Comment by simonbyrne** [comment]
> As everybody probably knows, I'd rather have exp(M) compute the matrix exponential than have expm and the vectorized :shudder: version.

Obligatory reference to #5840.

**Comment by sbromberger** [comment]
FWIW, I'm in favor of being consistent here. If `e` is "ok", then it seems to me that denying the use of gamma (per https://github.com/JuliaLang/julia/pull/10607) because "people use it for local variables" is inconsistent. I would counterargue that `e` is more commonly used as a local variable than `ζ`.

Again, it's possible to work around whatever decisions are made here, but absent a policy that one can reference when deciding whether or not a specific single-character variable makes sense or not, it's confusing as heck.

It's also entirely possible that I'm missing the point.

**Comment by JeffBezanson** [comment]
I think what's happening here is that we don't want to add any more 1-letter exported names, but it's not worth breaking things to remove the few we have.

**Comment by Keno** [comment]
Do we know how many people are actually using `e` in their code to mean Euler's constant. I suspect it's not that many.

**Comment by JeffBezanson** [comment]
There is also a question of how strongly associated the letter is. Walk into any technical department and say "e", and it can mean only one thing. Most single letters have marginal meanings by comparison, I think even the `φ` and `γ` that we already have in Base.

**Comment by sbromberger** [comment]
> There is also a question of how strongly associated the letter is. Walk into any technical department and say "e", and it can mean only one thing. Most single letters have marginal meanings by comparison, I think even the φ and γ that we already have in Base.

OK, but then what about ζ? Heck, even the function declared in Base is named "zeta". My original proposal was to give it the corresponding unicode Greek letter.

**Comment by JeffBezanson** [comment]
I'd say `ζ` is really not as universal as `e`. There is also `Γ` to consider for `gamma`.

I'm not sure why we have `φ` and `γ`. We were probably just having fun with unicode and MathConst. Surely those are used even more rarely than `e`.

**Comment by Keno** [comment]
As a quick datapoint from my entirely unscientific survey of all the packages I have installed, there were about 120 uses (multiple uses in the same function/file not counted) of e as local variables, 7 global redefinitions of `e` in a module to be something else, 5 constructs of the form `e = exp(...)` and 3 actual uses of `e` as Euler's constant. As such I would argue that looking at a random piece of code you can not conclude that `e` is Euler's constant. Using `eu` or even the unicode name would make that abundently clear. Further, if I remember the number of times I've accidentally written:
```
try
foo()
catch
println(log,"An error occurred: ", e)
end
```
Only to get in my log file "An error occurred: 2.7182818284590...", being confused for a moment and then realizing what happened, I just don't think reserving the one character name is worth it. In the `try/catch` example above, Lint.jl would probably have flagged (or could have) the undefined use of `e` if it weren't defined in Base.

**Comment by nalimilan** [comment]
@Keno Thanks for actually doing that survey!

**Comment by JeffBezanson** [comment]
Yes, that is interesting. I think this is more a command line thing than a package thing. Most real code will not use `e` anyway, but `exp`. If we get rid of it, we might as well remove φ and γ. That would leave `I` and `π` as the only 1-letter Base exports.

**Comment by tkelman** [comment]
I like the suggestion above of putting these in a `MathConsts` module. Or maybe there's a slightly nicer module name than that.

**Comment by sbromberger** [comment]
Without wanting to bikeshed the name, +1 to the `MathConsts` module idea.

**Comment by mlubin** [comment]
FWIW, I most commonly use ``e`` to refer to an edge in a graph. I never use it as ``exp``.

**Comment by nalimilan** [comment]
Since it doesn't seem this is going to be merged, could somebody knowledgeable review the docs I wrote in https://github.com/JuliaLang/julia/commit/beea5bc83014f38bf6eae7a9571e5c19e92a7633 and confirm they are good to merge separately?

**Comment by tkelman** [comment]
I haven't messed with `@deprecate` too much, but that looks okay to me

**Comment by Keno** [comment]
I still feel strongly that this should be merged. We should think of this is deprecating e in favor of `eu` (while adding a nice unicode alias like we have to the others).

**Comment by nalimilan** [comment]
@tkelman Thanks, pushed as https://github.com/JuliaLang/julia/commit/bfd93352818f19a72da6baae45e43b5e822d34f4

I'm all for reviving the discussion on the PR itself, though. :-)

**Comment by fredrikekre** [comment]
superseeded by #23427

**Comment by nalimilan** [comment]
The posthumous victory of an old and forgotten PR!

**Pull request closed without merging**
