### PR TITLE
relax assertion involving pg->nold to reflect that it may be a bit in…

### LINKED ISSUE #50419: gc_sweep_page assertion triggering in tests
```
gc                                                (1) |        started at 2023-07-03T19:18:26.371 on pid 398
julia: /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:1380: gc_sweep_page: Assertion `!prev_sweep_full || pg->prev_nold >= pg->nold' failed.
[7136] signal (6.-6): Aborted
in expression starting at /cache/build/default-amdci4-4/julialang/julia-master/julia-889c2e3d81/share/julia/test/gc/binarytree.jl:54
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fe2d50c640e)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
gc_sweep_page at /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:1380 [inlined]
gc_sweep_pool_page at /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:1476 [inlined]
gc_sweep_pool at /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:1563
_jl_gc_collect at /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:3260
ijl_gc_collect at /cache/build/default-amdci4-3/julialang/julia-master/src/gc.c:3435
gc at ./gcutils.jl:129 [inlined]
gc at ./gcutils.jl:129
```
https://buildkite.com/julialang/julia-master/builds/25532#01891c91-c02f-4181-b22c-5962d72d1499
@d-netto

### PR DESCRIPTION
**Pull request by d-netto**
…accurate with parallel marking

Should fix https://github.com/JuliaLang/julia/issues/50419.

### CODE REVIEW

**Comment by gbaraldi** [comment]
If we're fine with losing a bit of precision due to data races we can probably relax the atomic [here](https://github.com/JuliaLang/julia/blob/ce7e277bcf78ba4d7a2c4baaf0320f6c5e2ba9e7/src/gc.c#L857) to separate loads and stores.

**Comment by gbaraldi** [comment]
What I'm saying is that we can still use that information to skip a sweep even when multithreaded, so the mark_threads == 0 should only potentially guard the assertion.

**Comment by d-netto** [comment]
I believe this could lead us to incorrectly skip the page. 

As an example, we may have a case where the racy increment cause nold to be exactly prev_nold, while a non-racy update would lead nold to be less than prev_nold, thus causing us to take an incorrect sweeping decision.

**Comment by gbaraldi** [comment]
Fair enough, LGTM

**Review by gbaraldi — APPROVED** [review]

**Comment by vtjnash** [comment]
`prev_nold` is computed exactly (by the previous sweep), so the race-y update could be fine if done using atomics
```
jl_atomic_store_relaxed((_Atomic(uint16_t)*)&page->nold, 
    jl_atomic_load_relaxed((_Atomic(uint16_t)*)&page->nold + 1); // a guaranteed undercount of `nold`
```

**Comment by gbaraldi** [comment]
I guess we might sweep more than necessary in this case then, which is fine, but still less than with this pr where we always sweep?

**Comment by d-netto** [comment]
I believe this would be incorrect since a race on setting the mark-bits in `gc_try_setmark_tag` doesn't imply a race when incrementing `page->nold` in `gc_setmark_pool_`.

Two threads may end up marking the same object twice, but actually calling `gc_setmark_pool_` at different times, in which case `nold` would be larger than it should be even with the use of atomics.

**Comment by gbaraldi** [comment]
This causes quite a big regression in some cases. So it seems it's not worth it .

**Pull request merged**
