### PR TITLE
[release-1.3] Set VERSION to 1.3.0-rc4

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
#33552 maybe? :|

**Comment by KristofferC** [comment]
image

**Comment by KristofferC** [comment]
Hm, I think the commits are in the correct order but perhaps GitHub shows them in time authored order?

**Comment by ararslan** [comment]
Yep looks like it:
```log
commit 6539f1a126d018b43b79ad33f006588400d6aae4 (origin/kc/1.3.0-rc4)
Author: Kristoffer Carlsson <kristoffer.carlsson@chalmers.se>
Date:   Mon Oct 14 12:28:20 2019 +0200

    Set VERSION to 1.3.0-rc4

commit af01696569e603607f4c710546e1a84caeb7c63f
Author: Fredrik Ekre <ekrefredrik@gmail.com>
Date:   Mon Oct 14 19:01:38 2019 +0200

    Update checksums for Zlib.
```

**Review by ararslan — APPROVED** [review]

**Pull request merged**
