### PR TITLE
Remove unnecessary and slow Bidiagonal times Vector fallback

### PR DESCRIPTION
**Pull request by mcognetta**
`Bidiagonal` times `AbstractVector` currently falls back to:

https://github.com/JuliaLang/julia/blob/f552fb2071fb1b2ad66d0ff4602f5ff88acbf3a3/stdlib/LinearAlgebra/src/bidiag.jl#L635

which is unnecessarily slow. Removing this causes it to fallback to the same multiplication that `Tridiagonal` etc uses, which is faster (this can also be improved further for structured matrices).

Some timings:

Current:

```julia
julia> A = Bidiagonal(rand(1000), rand(999), 'U'); x = rand(1000)

julia> @time A*x
  0.014599 seconds (7 allocations: 7.637 MiB)

julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

This PR:

```julia

julia> A = Bidiagonal(rand(1000), rand(999), 'U'); x = rand(1000)

julia> @time A*x
  0.000020 seconds (6 allocations: 16.031 KiB)
```

### CODE REVIEW

**Comment by mcognetta** [comment]
To be honest, it seems like all of these can be removed considering they restrict the eltype of the inputs to be the same.

**Comment by andreasnoack** [comment]
> To be honest, it seems like all of these can be removed considering they restrict the eltype of the inputs to be the same.

Would be great if you try removing all of them.

**Comment by mbauman** [comment]
This looks good to me.  I verified that this is covered by tests:

https://github.com/JuliaLang/julia/blob/a8a567e72b669525dc4d3a38af275fe042f44a42/stdlib/LinearAlgebra/test/bidiag.jl#L231

**Comment by mcognetta** [comment]
I removed the others. I observed similar speedups for the other cases.

**Review by andreasnoack — APPROVED** [review]

**Comment by KristofferC** [comment]
Best PR ever. All green CI and all red diff.

**Comment by mcognetta** [comment]
Can I win a JuliaCon prize?

**Pull request merged**
