### PR TITLE
Security fix for mbedTLS

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Not tested; not sure if this is sufficient to fix (and note README already has outdated >=2.2). See:

https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2017-01

### CODE REVIEW

**Comment by yuyichao** [comment]
Please don't skip CI on every single one (or any) of your PRs.

**Review by yuyichao — CHANGES_REQUESTED** [review]
Don't skip CI!

**Comment by tkelman** [comment]
Ref https://github.com/JuliaLang/julia/pull/19135 for how to do this properly, last time we tried upgrading something was segfaulting. I have a really hard time reading that security advisory page to tell whether or not 2.3.0 is okay on those vulnerabilities.

**Comment by PallHaraldsson** [comment]
Yes, it's unclear that upgrade from 2.3 to 2.4.2 is needed; it seemed to me on first reading of the (brand new) advisory so I wanted to be on the safe side and report.

Even if the CVEs patched is for code made after:

https://github.com/JuliaLang/julia/commit/0418ae521fb3bdb81c8c1a51a566933257e5e242

I'm not sure that part of mbedTLS is used. @yuyichao "Please don't skip CI", good advice.. Someone adviced it to me (I was mostly fixing docs).

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/19689#issuecomment-268903407

**Comment by PallHaraldsson** [comment]
@yuyichao yes, I know happened ones before, and I hopefully will now break the habit, sorry! Unclear if you want me to change this PR, as I'm not sure I can (or need to, maybe this PR can be closed, and I'm not sure either that I can do). I've done [skip ci] (almost) always until now, as it has been ok, so sorry again about the habit.

**Pull request closed without merging**
