### PR TITLE
Build system backports for 1.6

### PR DESCRIPTION
**Pull request by haampie**
- Allow system versions of libwhich and libblastrampoline (#43000)
- Add missing USE_SYSTEM_LIBWHICH initialization (#43014)

Previously included, now dropped:
- Symlink 7z when USE_SYSTEM_P7ZIP (#43005)

### CODE REVIEW

**Review by staticfloat — APPROVED** [review]
Agreed, these all should be backported.  Thanks @haampie!

**Comment by vchuravy** [comment]
@haampie can you rebase onto `backports-release-1.6`?

**Comment by KristofferC** [comment]
@nalimilan had some issue with this.

**Comment by nalimilan** [comment]
Ah yes, thanks for pinging me. I've commented at https://github.com/JuliaLang/julia/pull/43005#issuecomment-983760389. I don't see why that PR should be backported to 1.6. If we do it for this kind of feature, we could do the same for many PRs. What's more, I don't think it's correct in its current implementation.

**Comment by haampie** [comment]
I see @nalimilan's point as I only considered install prefixes other than the system root in 43005, so the 7z commit is dropped.

**Comment by haampie** [comment]
@KristofferC this PR only backported the USE_SYSTEM_LIBWHICH in the end and dropped the p7zip changes. Can that still be added or is that too late now?

**Pull request closed without merging**
