### PR TITLE
Define environment variable `JULIA_NEVER_USE_USE_MADV_FREE` that disa…

### PR DESCRIPTION
**Pull request by kuszmaul**
…bles the

use of `MADV_FREE` in favor of `MADV_DONTUSE` in the garbage collector.

Addresses RAI-15397.

### CODE REVIEW

**Comment by vchuravy** [comment]
Could you explain the rational for this change? References to an internal issue tracker do not help the community at large to understand your change.

**Comment by NHDaly** [comment]
(I think this is a **draft** PR because it's not yet ready for review, and he only put it up as a placeholder for discussion, but yeah Bradley: it's usually best to file an issue in the julia repo first and then link to the issue from your PR, or if you're not ready for that, it would probably be good to at least leave an explanation here about what you're thinking about and why you're opening the PR 👍)

**Comment by gbaraldi** [comment]
Opening a PR is fine, a related issue isn't always necessary (though sometimes very useful to separate problem from solution if there is some contention around either), but context is always nice ;)

**Comment by NHDaly** [comment]
Thanks for filing the issue with context, Kiran: https://github.com/JuliaLang/julia/issues/51086

**Pull request closed without merging**
