### PR TITLE
Default values function arguments vs Python

### PR DESCRIPTION
**Pull request by bkamins**
Julia and Python handle default values of function arguments differently. Julia evaluates them every time the function is called and in python they are evaluated only once when the function is defined. This is an important difference in behavior for people migrating to Julia from Python.

### CODE REVIEW

**Comment by bkamins** [comment]
This is true, but I felt that In "Noteworthy differences from Python" section the explanation should be simple and show the difference from what Python programmer would expect.

Explaining all the mechanics how Julia handles functions in this section would be too complex in my opinion (it is covered in section "Note on Optional and keyword Arguments").

In particular notice that keyword arguments case exhibits similar (but not exactly identical) behavior but is implemented differently as statement `f(;x=rand(),y=x) = x+y` creates only one generic function.

It is worth to mention that R also evaluates its arguments every time the function is called but uses different mechanism to ensure this functionality. In particular this means that:

* in R `f <- function(x=y, y=runif(1)) x+y)` when called as `f()` will return different result every time and is valid;
* Julia would throw error when `f(x=y, y=runif()) = x+y` is called as `f()` unless `y` is defined in outer scope;
* Julia would throw error when `f(;x=y, y=runif()) = x+y` is called as `f()` even if is `y` is defined in outer scope.

**Comment by nalimilan** [comment]
I agree, the "noteworthy differences" section is not supposed to explain how it works, just to highlight possibly surprising behaviors.

**Comment by timholy** [comment]
@bkamins, it's easy to [edit the documentation yourself](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation), please do consider giving it a whirl.

**Comment by bkamins** [comment]
@timholy, what do you suggest that is worth adding? I have already edited the [docs](http://docs.julialang.org/en/latest/manual/noteworthy-differences/). And the difference with R is minimal (probably most R users never consider such corner cases).

**Comment by timholy** [comment]
Sorry, I was reading posts out of context; didn't realize your statement was retrospective, and that this was a PR your wrote. Sorry for the noise.

**Comment by ivarne** [comment]
Backported to `release-0.3` in 50ec1a0, just in case someone reads the 0.3 documentation.

**Pull request merged**
