### PR TITLE
WIP: move Pkg and LibGit2 to stdlib

### PR DESCRIPTION
**Pull request by JeffBezanson**
Do not merge.

This one is interesting. Pkg and LibGit2 have much more code than the other modules I've moved out of Base, and there are some interesting effects. First, changing where in sysimg.jl these are loaded has a large effect on system image size (~20%), build time, and startup time. I suspect there are a lot of method invalidations involved. Second, in the current state of this PR running `make test-libgit2` triggers an `invalid age range update`, so I'm opening this as a bug report and test case.

### CODE REVIEW

**Comment by ararslan** [comment]
As a side note about the stdlib moves, it seems like the Git history isn't being preserved. Would it be possible to do that? I always try to preserve the authorship when I move things into external packages.

**Comment by StefanKarpinski** [comment]
> has a large effect on system image size

Positive or negative effect? I'm assuming negative since, of course.

**Comment by JeffBezanson** [comment]
Yes, of course :)

**Comment by wildart** [comment]
Next step, remove any binary dependency and create a stand alone package manager.

**Comment by iamed2** [comment]
Previous attempt here: https://github.com/JuliaLang/julia/pull/22514

**Comment by JeffBezanson** [comment]
Superseded by other efforts (#24702).

**Comment by KristofferC** [comment]
I totally missed this one.

**Pull request closed without merging**
