### PR TITLE
Change libgit2 to a git-external

### PR DESCRIPTION
**Pull request by tkelman**
note that the tarball checksums changed because of switching from /archive/
to /tarball/ url for downloading, which changes the leading folder name
inside the tarball

### CODE REVIEW

**Comment by tkelman** [comment]
@vtjnash does this look right?

**Comment by vtjnash** [comment]
Lgtm

**Comment by ScottPJones** [comment]
I wonder if this has just broken my ability to build julia?
I'm getting this:
```
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection refused

make[1]: *** [libgit2] Error 128
make: *** [julia-deps] Error 2
```

**Comment by tkelman** [comment]
That just sounds like your connection might be flaky?

**Comment by ScottPJones** [comment]
No, I don't think so, git is working perfectly from the command line... (using https).

**Comment by tkelman** [comment]
What happens if you do, say, `make -C deps distclean-libuv && make -C deps get-libuv` ?

**Comment by ScottPJones** [comment]
```
rm -rf libuv libuv.tar.gz
git clone -q --depth=50 --branch julia-uv0.11.26 git://github.com/JuliaLang/libuv.git libuv
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection refused

make: *** [libuv] Error 128
```

Why is it trying to use the git:: protocol instead of https?

**Comment by ScottPJones** [comment]
(works fine with https::)

**Comment by tkelman** [comment]
Because @vtjnash wrote #10743 that way? `git config --global url."https://".insteadOf git://` should fix it

**Comment by ScottPJones** [comment]
It seems to be ignoring my setting... it already is set to `https://`
```
[remote "JuliaLang"]
	url = https://github.com/JuliaLang/julia.git
	fetch = +refs/heads/*:refs/remotes/JuliaLang/*
```

**Comment by tkelman** [comment]
That's just the remote for this repo, libuv and libgit2 and a few other deps are cloned separately now - you can try building with `NO_GIT = 1` to download them as tarballs instead

**Comment by pao** [comment]
If the machine is in a no-git-protocol zone, using the global-config rewrite (as @tkelman listed) is the preferred option.

**Comment by ScottPJones** [comment]
The issue was, that there *were* not config entries, global or local, that had `git://`, so the rewrite wouldn't help...

**Comment by pao** [comment]
Yes, it will. The X.insteadOf config option changes the URL on the fly, including ones entered at the command line (as when the make system clones libgit2, for instance.)

**Comment by ScottPJones** [comment]
Ah!!!  Thanks so much!  I totally misunderstood @tkelman 's very good advice... I saw the "insteadOf", and thought he meant that I should manual change to `https://` intead of `git://`... Must be the 2 hours of sleep!

**Pull request merged**
