### PR TITLE
add missing exports to deprecated.jl

### PR DESCRIPTION
**Pull request by rened**
I believe this is just an oversight.

### CODE REVIEW

**Comment by IainNZ** [comment]
Not so sure about that: https://github.com/JuliaLang/julia/pull/9495

**Comment by rened** [comment]
Ok, ic. But defining the consts in deprecated and not exporting them does not make much sense, or does it? Remove the consts?

**Comment by jakebolewski** [comment]
They were not exported before being deprecated so this is why the const fallbacks are not exported.

**Comment by rened** [comment]
thanks, sorry for the noise.

**Pull request closed without merging**
