### PR TITLE
release-1.8: Backports for Julia 1.8.1

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #44510 
- [x] #45290 
- [x] #45789 
- [x] #46368 
- [x] #46341 
- [x] #46375 
- [x] #46350 
- [x] #46388 
- [x] #46359 
- [x] #46416 
- [x] #46406 
- [x] #46237 
- [x] #46473 
- [x] #46436 
- [x] #46481 
- [x] #46489 
- [x] #46183 
- [x] #45578 
- [x] #46516 
- [x] #46519 
- [x] #46490 
- [x] #46486 
- [x] #46491 
- [x] #46535 
- [x] #46494 
- [x] #46039 
- [x] #46546 
- [x] #46493 
- [x] #46548 
- [x] #46548 
- [x] #46546 

Need manual backport:
- [ ] #46086 

PRs with backport label:
- [ ] #46373 
- [ ] #45582 <!-- [CompilerSupportLibraries_jll] Upgrade to libraries from GCC 12 -

### CODE REVIEW

**Comment by Moelf** [comment]
and:
- https://github.com/JuliaLang/julia/pull/46375

**Comment by KristofferC** [comment]
Yes, the backport label was not addedti that PR when I made this. Now that it is, it will get picked up.

**Comment by timholy** [comment]
I think #46010 can be removed from your TODO list, see https://github.com/JuliaLang/julia/pull/46010#issuecomment-1226028119

**Comment by oscardssmith** [comment]
Can https://github.com/JuliaLang/julia/pull/46436 get added?

**Comment by KristofferC** [comment]
Is it not?

**Comment by oscardssmith** [comment]
oops, not sure how I missed it.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"], vs_buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"])`

**Comment by DilumAluthge** [comment]
Looks like the Nanosoldier syntax has changed: https://github.com/JuliaCI/Nanosoldier.jl#trigger-syntax-1

**Comment by yuehhua** [comment]
and:

- #46400 

Thanks.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"]), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"]))`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.8", configuration = (buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration=(buildflags=["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46376#issuecomment-1229994885) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c65611a_vs_5544a0f/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["BiGGReactions", "BracedErrors", "Cambrian", "ClusteringGA", "CondaBinDeps", "CrystalInfoFramework", "FilesystemDatastructures", "GLMNet", "GaussBP", "HydrophoneCalibrations", "JWTs", "LatticeDiracOperators", "LogicToolkit", "LokiLogger", "MatrixLMnet", "MetapopulationDynamics", "MultiStochGrad", "NumericalAlgorithms", "OteraEngine", "PartialSvdStoch", "PkgSwaps", "QML", "RheaReactions", "StableTrees"], vs = ":release-1.8", configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],), vs_configuration = (buildflags = ["LLVM_ASSERTIONS=1", "FORCE_ASSERTIONS=1"],))`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/46376#issuecomment-1230556869) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c65611a_vs_5544a0f/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.8")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/46376#issuecomment-1232130787) failed.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-1.8")`

**Comment by KristofferC** [comment]
@vtjnash, any idea what's up with the job failure?

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/46376#issuecomment-1232493316) failed.

**Comment by vtjnash** [comment]
upload was too big https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/43c2ea0_vs_5544a0f/report.md

**Pull request merged**
