### PR TITLE
codegen: implement isdefined_tfunc check more similarly to inference

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by gbaraldi** [comment]
I guess this can supercede https://github.com/JuliaLang/julia/pull/52068?

**Comment by vtjnash** [comment]
Oops, turns out that this optimization is unsound for inference / codegen to attempt since some packages (e.g. NetworkOptions) relies on the non-existence of this optimization that we therefore may need to delete this from inference.

**Comment by oscardssmith** [comment]
>  some packages (e.g. NetworkOptions) relies on the non-existence of this optimization

How can they tell whether this optimization was performed?

**Comment by vtjnash** [comment]
They segfault if the code gets reinferred

**Comment by vtjnash** [comment]
Part of the cleanup here is perhaps worthwhile (merging code paths into a common helper function), but the main change has been removed from inference for correctness reasons in #53750

**Comment by DilumAluthge** [comment]
CI is all green here. @vtjnash Is this good to merge now, or are you still waiting on a review from Valentin and/or Gabriel?

**Comment by vtjnash** [comment]
It is fine now to merge

**Pull request merged**
