### PR TITLE
test/runtests.jl: allow disabling tests requiring network connectivity

### PR DESCRIPTION
**Pull request by wegank**
Supersedes #43217 in an opposite direction: allow disabling the tests that require network connectivity, even if networking is available. This makes it possible, for example, to run tests in an intranet-only environment.

Also, this PR should help packaging Julia in a Nix sandbox: NixOS/nixpkgs#205584

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
If you want to skip certain test sets, regardless of whether or not networking is available, you can just skip them explicitly:

```julia
Base.runtests("all --skip Download LibGit2/online Pkg")
```

**Comment by wegank** [comment]
> If you want to skip certain test sets, regardless of whether or not networking is available, you can just skip them explicitly:
> 
> ```julia
> Base.runtests("all --skip Download LibGit2/online Pkg")
> ```

As https://github.com/NixOS/nixpkgs/pull/205584#issuecomment-1351607287 have mentioned, the test set to skip may depend on the Julia version (for example, TOML on 1.19+). A more universal approach, as in this PR, seems preferable.

**Comment by DilumAluthge** [comment]
We could add some kind of alias of the form `Base.runtests("all --skip internet_required")`. And then `internet_required` would expand to the set of stdlibs that require Internet access for their test suites.

But I don't think that `JULIA_TEST_NETWORKING_AVAILABLE` is the right interface for this.

**Comment by DilumAluthge** [comment]
If I recall correctly, https://github.com/JuliaLang/julia/pull/43217 was just a stop-gap solution until the check described in https://github.com/JuliaLang/julia/pull/43211#issuecomment-982202890 could be added. IIRC, once such a check is added, we can remove the `JULIA_TEST_NETWORKING_AVAILABLE` environment variable.

So it would be best to avoid relying on `JULIA_TEST_NETWORKING_AVAILABLE`.

**Comment by DilumAluthge** [comment]
I haven't actually tested it out yet, but maybe something like this: https://github.com/JuliaLang/julia/pull/47914

**Comment by DilumAluthge** [comment]
Closing in favor of #47914

**Pull request closed without merging**
