### PR TITLE
More verbose Pkg.update() for checked out packages

### PR DESCRIPTION
**Pull request by mbauman**
Just like how "free" packages display which versions they're updating from and to, display the git SHA for checked out packages as they are updated.  Here's a real-life example:

``` txt
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Interpolations master...
INFO: Updating Tuples master...
INFO: Skipping TerminalExtensions (dirty)...
INFO: Updating AxisArrays master...
INFO: Updating Compat master...
INFO: Updating IntSets master...
INFO: Updating HDF5 master...
INFO: Skipping BitSets (dirty)...
INFO: Updating DataArrays master... b5d39c3 => c588781
INFO: Skipping Signals (dirty)...
INFO: Updating KDTrees master...
INFO: Updating FileIO master...
INFO: Skipping SmallDicts (dirty)...
INFO: Updating BinDeps master...
INFO: Updating DataFrames master...
INFO: Updating SIUnits master...
INFO: Updating Homebrew master...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

To be honest, I was totally unaware of how many packages I had that were either dirty or happened to be on a custom branch before I made this change (DataArrays is only updating because I had been on a custom branch until I started printing out the branch names).  This also prints out the before and after SHA if there was a change.

It's a small change, but I have no idea how the Pkg code works, so I'd appreciate a slightly more-thorough-than-usual lookover.  In particular, I don't know if these git commands are available for our lowest-supported Git version, or what the `@recover` macro does.

### CODE REVIEW

**Comment by wildart** [comment]
This will slow down update even more. With libgit2 backend it would be faster. I think we should postpone it. Meanwhile, you could look at `Pkg.status` before doing update.

**Comment by tkelman** [comment]
Can we measure how much slower? I think this is valuable information, and `Pkg.status` is itself really slow.

**Comment by mbauman** [comment]
`INFO: Skipping Pkg (dirty)…` is free.  But getting the branch information and pre/post SHAs involves adding three git calls per package to the existing two.  As I understand it the majority of the time for the slower platforms is in startup of git.  So this could be up to 2.5x slower per checked-out package.

**Comment by jakebolewski** [comment]
closing in favor of #13648

**Pull request closed without merging**
