### PR TITLE
color compilation with red in tracy during recompilation

### PR DESCRIPTION
**Pull request by KristofferC**
This makes them kind of obvious and then you can click on them and see what methods ended up getting recompiled. In the screenshot below, we can see that code loading got recompiled.

image

The red bar to the right is code loading getting recompiled... Again! (this is all during loading of a single package)

### CODE REVIEW

**Comment by IanButterworth** [comment]
Colors have some meaning in ProfileView and the vscode profile canvas etc. Does this match that?

**Comment by IanButterworth** [comment]
Sounds good. If aligning them makes sense it can always happen later

**Comment by topolarity** [comment]
This is a good marker to have, but I want to bikeshed on the color.

I've been wanting to carve out some "color space" for the Julia runtime, so that user-level traces/colors are not drowned out by the built-in runtime trace events. My target is just 1 default "runtime event" color and 1 or 2 "special" runtime event colors, and I'd prefer that those colors be a bit less "loud" than this bold red.

Feel free to take a stab at a new palette (or re-use the existing orange we use for special GC events). The idea is that they should be easy to spot when you're looking for them, but not difficult to ignore otherwise.

Otherwise, I'll play around myself today and see if I can propose an alternative

**Comment by KristofferC** [comment]
I changed to the same color as the GC one now. I don't mind much what color is used, as long as it somewhat sticks out from the reset of the runtime zones.

**Review by topolarity — APPROVED** [review]

**Pull request merged**
