### PR TITLE
Update readme to reflect latest stable version

### PR DESCRIPTION
**Pull request by christiangnrd**

### CODE REVIEW

**Comment by ViralBShah** [comment]
This isn't released yet. 

Is there a way for us to have a git tag called `stable` and `lts` that we update as we go along? That way we don't need to update the README with revery release.

**Comment by jonas-schulze** [comment]
A branch would be better than a tag for this use case.

**Comment by DilumAluthge** [comment]
Yeah. It's not a great idea to treat tags as mutable, even though they technically are.

**Review by vtjnash — CHANGES_REQUESTED** [review]
This needs to be updated by following the `make release-candidate` checklist, so that it doesn't get missed when it is actually released, and not updated ad-hoc here

**Pull request closed without merging**
