### PR TITLE
Fix chol! for uniform scaling, add test

### PR DESCRIPTION
**Pull request by kshyatt**
Changed the function so that its argument structure matches `chol` and added a test

### CODE REVIEW

**Comment by fredrikekre** [comment]
ref https://github.com/JuliaLang/julia/pull/22633/files#r150090533

**Comment by andreasnoack** [comment]
What @fredrikekre said. This method should just be deleted.

**Comment by fredrikekre** [comment]
Reopen this then @andreasnoack ?

**Comment by dkarrasch** [comment]
Seems like this PR became entirely obsolete, there is no occurrence of "chol" in uniformscaling.jl. Can we then close and delete this?

**Comment by kshyatt** [comment]
Cast it into the fire!!!

**Pull request closed without merging**
