### PR TITLE
Emoji REPL completion

### PR DESCRIPTION
**Pull request by jakebolewski**
screen shot 2015-04-01 at 12 48 12 am

screen shot 2015-04-01 at 12 46 58 am

To quote @jiahao:

> These are the voyages of the flagship Julia. Its five-year mission: to explore strange new symbols, to seek out new codepoints and new characters, to boldly go where no language has gone before.

Happy April 1st

### CODE REVIEW

**Comment by simonbyrne** [comment]
Should we also make :100: a `MathConst`?

**Comment by sbromberger** [comment]
As long as we're allowed to [propose PRs that assign math constants to these new symbols](https://github.com/JuliaLang/julia/pull/10612#issuecomment-88243339), I'm all in favor. :+1: 

ETA: damnit. @simonbyrne was quicker on the keyboard.

**Comment by sbromberger** [comment]
although :+1: might be more appropriate as an incrementer function :)

**Comment by jakebolewski** [comment]
```julia
julia> 💯
💯 = 100.0...

julia> fill(💯, (5,5))
5x5 Array{MathConst{:💯},2}:
 💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...
 💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...
 💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...
 💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...
 💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...  💯 = 100.0...
```

**Comment by timholy** [comment]
Love it!

**Comment by sbromberger** [comment]
Defining :+1: as a function appears to hang the REPL :(

**Comment by simonbyrne** [comment]
We actually probably don't want :100: as a MathConst, as all the inequality functions assume that MathConsts are irrational. We could have const :100: =100 though.

**Comment by jakebolewski** [comment]
Obviously just for fun, but it is entertaining enough that it might be worthwhile to have it as an easter-egg.

**Comment by pao** [comment]
Is there a way to add completions at run-time so that `using EmojiCompletions` could be a thing?

**Comment by jakebolewski** [comment]
There might be a way, but the latex substitution claims the convenient  `\<tab>` idiom.

**Comment by jakebolewski** [comment]
@Keno likes emojis.

**Comment by sbromberger** [comment]
man, I just did a build this morning. Now I get to rebuild. Thanks. :)

**Comment by hayd** [comment]
:+1: Emojis are clearly the future.

---

Is the following a problem with my terminal or julia?

If you type, :+1: 123 (without space), it looks fine, once you press return the 1 overlaps the :+1:.
```
julia> 👍123<ENTER>
```
*Perhaps this because the length(":+1:") == 1? (Should it be 2?)*

I also see this if I tab complete two :+1::+1: in a row.

**Comment by jiahao** [comment]
@hayd you've run into the notorious pizza/koala bug. #3721

**Comment by pao** [comment]
> There might be a way, but the latex substitution claims the convenient \<tab> idiom.

Ah, I see. I was hoping that those were themselves runtime extensible. But definitely in the "nice-to-have" category.

**Comment by goretkin** [comment]
Today's XKCD's alt text: http://xkcd.com/1513/

**Pull request merged**
