### PR TITLE
🤖 Bump the NetworkOptions stdlib from 6cea813 to 42a0b5f

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: NetworkOptions
Branch: master
Old commit: 6cea813
New commit: 42a0b5f
Bump invoked by: @StefanKarpinski

```
$ git log --oneline 6cea813..42a0b5f
42a0b5f ca_roots: skip OpenSSL-specific cert files (#18)
```

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Btw, @DilumAluthge, I kicked this off asking for both `Downloads` and `NetworkOptions` to be updated, but it seems like the script only does one these days. Just FYI.

**Comment by StefanKarpinski** [comment]
Here's the link to the run: https://github.com/JuliaLang/BumpStdlibs.jl/runs/3265701265?check_suite_focus=true. You can see that it has NetworkOptions,Downloads but only the former was updated.

**Comment by StefanKarpinski** [comment]
Ah, it did create the PR, it just didn't assign me to it: https://github.com/JuliaLang/julia/pull/41803. Do you do the assignment by hand?

**Comment by DilumAluthge** [comment]
> Ah, it did create the PR, it just didn't assign me to it: #41803. Do you do the assignment by hand?

Yeah I do the assignment by hand. I don't think that the bot has permissions to do assignments.

For security reasons, I don't give the bot any permissions on the Julia repository.

So the bot can't do assignments. But it should still use username-ping you in the pool request.

**Comment by DilumAluthge** [comment]
Although, I suppose that the easiest way to show the list of all bump PRs is to go here: https://github.com/JuliaLang/julia/pulls/DilumAluthgeBot

**Pull request merged**
