### PR TITLE
Update documentation build dependencies

### LINKED ISSUE #54226: Warning in the Building HTML documentation
The following warning appears while building the html documentation on master:

```julia
The active manifest file has dependencies that were resolved with a different julia version (1.11.0-DEV). Unexpected behavior may occur.
```
That can be solved by either updating the Manifest.toml or adding a line of code in /doc/make.jl (line 9).

```julia
using Pkg
Pkg.resolve() # Pkg.update() should also work and would probably be better?
Pkg.instantiate()
```
That should avoid any warning going forward? And need to update the Manifest.toml?

Removing the Manifest is not working on my side probably because of my connection:
```
Error: RequestError: HTTP/1.0 200 OK (Operation too slow. Less than 1 bytes/sec transferred the last 20 seconds)
```

### PR DESCRIPTION
**Pull request by gitboy16**
Fix #54226

### CODE REVIEW

**Comment by fredrikekre** [comment]
No, this is not a good idea. The committed known-to-be-good manifest should be used.

**Comment by gitboy16** [comment]
Can you please re-open the PR so I can amend it? Thank you

**Comment by gitboy16** [comment]
Thank you @fredrikekre . I have updated the Manifest. Let me know if you want me to amend anything else.
Just for my information, does that mean for every new julia version, the Manifest.toml needs to be updated?

**Comment by LilithHafner** [comment]
No only that, in order to receive any bugfixes from any packages the manifest must be updated. I would rather not check in the manifest and instead, specify tight compat bounds (e.g. ~ compat) in the Project.toml file if needed.

That said, this PR LGTM (I haven't checked the hashes, but I believe that Pkg would error if those hashes did not correspond to the listed versions).

**Review by LilithHafner — APPROVED** [review]

**Comment by fredrikekre** [comment]
> No only that, in order to receive any bugfixes from any packages the manifest must be updated. I would rather not check in the manifest and instead, specify tight compat bounds (e.g. ~ compat) in the Project.toml file if needed.

No, this is a textbook example of when the manifest should be committed.

**Comment by tecosaur** [comment]
Thanks for following through on the invitation to contribute in #54226 @gitboy16, and congratulations on your first Julia PR! :tada:

**Comment by LilithHafner** [comment]
*third :)

**Pull request merged**
