### PR TITLE
RFC move SuiteSparse to an external repository

### PR DESCRIPTION
**Pull request by KristofferC**
@ViralBShah has expressed some thoughts on moving SuiteSparse (and later SparseArrays) out into its own repository. This PR takes a stab at that by moving the development of this to https://github.com/JuliaLang/SuiteSparse.jl which is now set up with CI doc building etc.

One thing that I am a bit worried about is that SuiteSparse does a lot of type piracy (adding methods coming from LinearAlgebra onto types coming from SparseArrays). It is therefore very tightly connected to the SparseArray stdlib so moving one of them out might get annoying if changes have to be made in two places at once. In fact, from the way the code is structured now, SuiteSparse shouldn't be a separate package at all, it should be a submodule of SparseArrays. A second thing which is a bit odd is the SuiteSparse_jll stdlib which seems like it should not be in Base if SuiteSparse itself is not in Base.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Would it be better to make it a submodule of SparseArrays? 

Wouldn't `SuiteSparse.jl` as a package end up having a dependency on `SuiteSparse_jll` like other packages? I suppose this wouldn't work well with base given that everything is special there. What if we just moved both of them completely out of stdlib as real Julia packages?

**Comment by ViralBShah** [comment]
Well the new package is already receiving PRs: https://github.com/JuliaLang/SuiteSparse.jl/pull/2

I guess we should move forward with this and see how difficult it is to maintain SuiteSparse.jl as a separate package, especially given the type piracy and what not.

**Comment by KristofferC** [comment]
Alright, I'll try finish this up then.

**Comment by KristofferC** [comment]
I've updated https://github.com/JuliaLang/SuiteSparse.jl with the latest PR. I'll merge this now so there won't be need to sync things again.

**Pull request merged**
