### PR TITLE
define zero-argument function composition

### PR DESCRIPTION
**Pull request by aplavin**
`identity` is the natural neutral element of composition. The zero-arg method makes 
```julia
F1 = ∘(fs...) ∘ ∘(gs...)
F2 = ∘(fs..., gs...)
# now F1 is equivalent to F2
```
to hold always, including empty `fs` or `gs`.

### CODE REVIEW

**Comment by dkarrasch** [comment]
AFAIU, the point is that - depending on the context - users may wish the identity to be "their" identity, not Base's `identity`; like som `LensIdentity`, whatever that is.

**Comment by thofma** [comment]
It is not a question of having a different composition semantics. I don't want to rehash the discussion of #34251. But it is in the end to a large extend the same reason that `+()` and `*()` is not defined. Would you also want to do `+() = 0` (or `+() = false`), because anything that is broken by this has some "different addition" semantics?

**Comment by thofma** [comment]
I don't think any of the original arguments for not having this have been refuted.

**Comment by uniment** [comment]
Good point.

**Comment by adienes** [comment]
>  `identity` is the only natural result for an empty function composition

for `<:Function` types sure. but not all callable (and composably callable) types are `<:Function`

> If some type is incompatible with identity, then it is basically a pun to overload Base.∘ for that type

sounds like a problem with `identity` then. as long as the methods define on `∘` satisfy 
```
(f ∘ g)(args...; kwargs...) = f(g(args...; kwargs...))
```

then that's not a "pun."

I think this has been discussed, decided, and should be closed as "won't change"

**Comment by uniment** [comment]
Hopefully Julia 2.0 will have neutral identity elements for numbers instead of trying to shoehorn `Bool` into that role because C did. That would also free up `Bool` to behave like Hehner proposes to be $\top$ and $\bot$ of the number lattice.

**Pull request closed without merging**
