### PR TITLE
Even more tests for linear algebra special matrices

### PR DESCRIPTION
**Pull request by kshyatt**
The `A_ldiv_B` methods for `Diagonal`s still needed tests. `Givens` needed a bunch of error throwing tests, as did `dot` for ranges.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
You're back! The `replcompletions` failure seems unrelated, so merging this.

**Comment by kshyatt** [comment]
Got busy with research, but the call of testing was so strong!

**Comment by tkelman** [comment]
Did anyone ever figure out what was going wrong with coveralls?

**Comment by kshyatt** [comment]
I emailed @staticfloat but he's apparently quite busy atm. Coveralls per-build info is fine, it's just that the git commit info isn't making it from the buildbot. The coverage badge isn't updated and it's a bit of a pain to find my testing PRs.

**Pull request merged**
