### PR TITLE
 codegen: ensure Bool arithmetic is done in mod-2

### PR DESCRIPTION
**Pull request by vtjnash**
As @stevengj found in #31486, we're doing boolean arithmetic wrong in codegen, and that's causing us to potentially give up lots of performance since we can't vectorize it, and in addition we get wrong answers.

setup:
```julia
julia> xor_(a, b) = Core.Intrinsics.xor_int(a, b);
julia> b = rand(Bool, 150); i = UInt8.(b);
julia> f(a) = reduce(xor, a); g(a) = reduce(!=, a); h(a) = reduce(xor_, a);
julia> using BenchmarkTools
```

before:
```
julia> @btime f(b)
  115.304 ns (0 allocations: 0 bytes)
true

julia> @btime f(i)
  34.677 ns (0 allocations: 0 bytes)
0x01

julia> @btime g(b)
  114.314 ns (0 allocations: 0 bytes)
true

julia> @btime g(i)
  119.157 ns (0 allocations: 0 bytes)
true

julia> @btime h(b)
  33.699 ns (0 allocations: 0 bytes)
true

julia> @btime h(i)
  35.412 ns (0 allocations: 0 bytes)
0x01
```

after:
```
julia> @btime f(b)
  38.064 ns (0 allocations: 0 bytes)
true

julia> @btime f(i)
  34.773 ns (0 allocations: 0 bytes)
0x01

julia> @btime g(b)
  35.565 ns (0 allocations: 0 bytes)
true

julia> @btime g(i)
  118.535 ns (0 allocations: 0 bytes)
true

julia> @btime h(b)
  39.737 ns (0 allocations: 0 bytes)
true

julia> @btime h(i)
  34.269 ns (0 allocations: 0 bytes)
0x01

julia> @btime h(i)
  34.299 ns (0 allocations: 0 bytes)
0x01
```

PS: ignore the first commit, it's just deleting dead code

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, ":master")`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/31503#issuecomment-479102998):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`make -j3 USECCACHE=1`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6bad8ea0084c8dd0d2a4ff9d9147d20dd59091dc/d9f0608_vs_98673b5/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Nanosoldier is currently broken due to the BinaryBuilder changes.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31503#issuecomment-479203435) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/078c632e89f610ed0149cd22adec840ddeee6190/d9f0608_vs_98673b5/report.md). cc @ararslan

**Comment by vtjnash** [comment]
Looks like it's probably a wash, so no major issues created by fixing this, but lets see if it is repeatable: @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/31503#issuecomment-479327971) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1fa11c3d5782d998c183147c6141e64cc1cfb6f0/044d56d_vs_aee211b/report.md). cc @ararslan

**Comment by rfourquet** [comment]
"mod 2" instead of "mod 1" ?

**Pull request merged**
