### PR TITLE
Tests for annotated string/char c-tors

### PR DESCRIPTION
**Pull request by kshyatt**
These don't appear to be tested on Codecov.

### CODE REVIEW

**Comment by kshyatt** [comment]
Sorry, wasn't able to test this locally (`make test-strings` **refused** to build a sysimage on my Fedora laptop), I'll try to resolve the test issues.

**Comment by tecosaur** [comment]
Hi Katherine, thanks for your continued efforts to shore up test coverage!

Would you be able to point me to the particular source that led to these tests? At a glance they don't seem valid to me :confused: 

The `Base.AnnotatedString("hello", :label => 1)` syntax is the original form, but after it was raised that a pair-in-tuple structure was annoying to access elements of, I was asked to change it to a NamedTuple form, and so no longer expect this syntax to work: #55741 (as an aside: I still need to finish backporting these changes to the compat release (as time permits))

I think the first `AnnotatedChar` expression has this issue too, but the second `Base.AnnotatedChar('h', [(1:1, :label, 1)])` includes a region, which doesn't simply apply to `AnnotatedChar`s (they only hold a list of label-value associations).

**Comment by kshyatt** [comment]
Was looking at lines 107 and 113 at https://app.codecov.io/gh/JuliaLang/julia/blob/master/base%2Fstrings%2Fannotated.jl#L107

**Comment by tecosaur** [comment]
Ah, I see. Using plain old tuples (instead of the expected named tuples) is probably what you want then, e.g.

```
AnnotatedString("hey", [(1:3, :attr, '7')])
AnnotatedChar('h', [(:attr, '7')])
```

**Comment by kshyatt** [comment]
Looks like the test works, but uploading the coverage report failed

**Review by inkydragon — APPROVED** [review]

**Pull request merged**
