### PR TITLE
some better type info in Base to improve latency a bit

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by KristofferC** [comment]
`["dates", "string", "Date"]` might be real

**Comment by JeffBezanson** [comment]
Yes, I can reproduce that regression locally. It's hard to see what caused it. It seems to be one of those indirect effects. There is no difference in code_typed, but code_llvm shows that calls to the implementation method (inside the keyword args wrapper) for `string(::Int)` are using `jl_invoke` instead of direct calls.

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks("dates", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/30830#issuecomment-461550559) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/295a0031d39633be396897387d60c5bbaddac6b2/634ee7e_vs_2ecc499/report.md). cc @ararslan

**Pull request merged**
