### PR TITLE
Verbalize definition of isapprox in docstring

### PR DESCRIPTION
**Pull request by mschauer**
Did I take the correct emphasis style for or?

### CODE REVIEW

**Review by oxinabox — COMMENTED** [review]
Can we add a couple of examples while here?
Especially ones with big human friendly numbers like

`isaporox(10, 12; atol=5)`

**Comment by mschauer** [comment]
Not sure if making it "too" easy will be a break with the docstring style, but...

> 7 and 9 have the same absolute distance as 107, 109, namely 2 = |9-7|. Likewise 0.9, 1.0 and 90, 100 have the same relative distance, namely 0.1 = |100-90|/100 = (1.0-0.9)/1.0. Therefore `isapprox(7, 9, atol=2) == true` and `isapprox(90, 100, rtol=0.099) == false`.

**Comment by oxinabox** [comment]
Or even just:
```
julia> isapprox(0.1, 0.15; atol=0.05)
true


julia> isapprox(0.1, 0.15; rtol=0.5)
true

julia> isapprox(0.1, 0.15; rtol=0.34)
true

julia> isapprox(0.1, 0.15; rtol=0.33)
false
```

**Comment by mschauer** [comment]
Taking to points with relative distance `1/3` and do `rtol=0.33`, `rtol=0.34` is a good idea for the example to avoid tricky issues with rounding errors when `rtol` exactly equals the relative distance

**Comment by simeonschaub** [comment]
LGTM

**Pull request merged**
