### PR TITLE
FreeBSD: update build instructions in README

### LINKED ISSUE #29625: build: libgit2 does not detect libssh2 on FreeBSD
I installed a new FreeBSD VM,
and the log from here (https://build.julialang.org/#/builders/67/builds/3/steps/7/logs/stdio)

shew this:
```
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```

and this build got following test error
```julia
Error in testset LibGit2/libgit2:
Test Failed at /usr/home/julia/julia-fbsd-buildbot/worker/freebsdci_test/build/usr/share/julia/stdlib/v1.1/LibGit2/test/libgit2.jl:161
  Expression: findfirst(isequal((LibGit2.Consts).FEATURE_SSH), f) !== nothing
   Evaluated: nothing !== nothing
ERROR: LoadError: Test run finished with errors
in expression starting at /usr/home/julia/julia-fbsd-buildbot/worker/freebsdci_test/build/test/runtests.jl:61
```

Seems that our build script doesn't point the correct path of `libssh2` for `libgit2`?

### PR DESCRIPTION
**Pull request by iblislin**
[ci skip]
fix #29625

### CODE REVIEW

**Comment by fredrikekre** [comment]
This fails CI due to trailing whitespace.

**Comment by StefanKarpinski** [comment]
Why the merge when this was failing CI?

**Comment by iblis17** [comment]
My bad. :man_facepalming: 
will not put `[ci skip]` on README again.

**Comment by StefanKarpinski** [comment]
Oh, I see, it was passing because of the ci skip directive.

**Pull request merged**
