### PR TITLE
remove old cell {} related functions from base.jl

### PR DESCRIPTION
**Pull request by catawbasam**
This is a follow-up to issue #10067
cc: @ivarne 
passes make clean test

### CODE REVIEW

**Comment by ihnorton** [comment]
There is still lowering code in julia-syntax too.

**Comment by ivarne** [comment]
@ihnorton Should I revert? or do you talk about other things that should be cleaned up too?

**Comment by ihnorton** [comment]
I don't think there is a need to revert this, the tests pass. I meant that
there is code in julia-syntax.scm that lowers to cell_1d/2d. There are also
still a bunch of cell_1d references in C code but I didn't track down if
they are still used.

**Comment by ivarne** [comment]
Thanks for the clarification. I just searched the Julia code, and found no references, so I thought it was safe to delete an unexported function.

Now I realised that this might break the deprecation of the `{}` syntax, but that does not seem to be the case, so I guess I was lucky.

**Comment by jakebolewski** [comment]
This change breaks the following code.  As this functionality is deprecated and not removed, I think this commit should be reverted.

```julia
julia> a = (1,2,3)
(1,2,3)

julia> b = (4,5,6)
(4,5,6)

julia> {a...}
WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
julia> {a...}

WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
ERROR: UndefVarError: cell_1d not defined

julia> {a...; b...}
WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
julia> {a...; b...}

WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
ERROR: UndefVarError: cell_1d not defined
```

**Pull request merged**
