### PR TITLE
Backports for 1.10.4

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #54010 
- [x] #54143 
- [x] #54151 
- [x] #54233 
- [x] #54251 
- [x] #54363 
- [x] #54497 
- [x] #53796 
- [x] #54465 
- [x] #54514 

Need manual backport:
- [ ] #52505 
- [ ] #53373 
- [ ] #53815 
- [ ] #53984 
- [ ] #54276 

Contains multiple commits, manual intervention needed:
- [ ] #52854 
- [ ] #53218 
- [ ] #53833 
- [ ] #54303 
- [ ] #52694 

Non-merged PRs with backport label:
- [ ] #54471 
- [ ] #53452 
- [ ] #51479

### CODE REVIEW

**Comment by IanButterworth** [comment]
To get the heapsnapshot fixes in I think these are all needed
- https://github.com/JuliaLang/julia/pull/52618
- https://github.com/JuliaLang/julia/pull/52854
- https://github.com/JuliaLang/julia/pull/53833
- https://github.com/JuliaLang/julia/pull/53984

Which I tried but they're not very clean backports. I think someone familiar with GC would be better suited to handle them.

**Comment by fingolfin** [comment]
It would be great to also get #53815 into 1.10.4. It requires (IMHO straightforward) manual resolution of the merge but it is easy enough, I can provide a PR if needed.

**Comment by KristofferC** [comment]
@N5N3, could you help backport the type intersection PRs that are marked for backport to here (some merge conflicts).

**Comment by N5N3** [comment]
@KristofferC, done.
BTW, it would be good to backport  #53675 and #54545 to 1.10, if the latter get merged, as the free typevar regression shown in #54516 still exists.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54416#issuecomment-2137392749) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/7ebe203_vs_5cf5146/report.html) is available.

**Comment by fingolfin** [comment]
It seems #53815 did not make it in :-(. Any particular reason for that? It    fixed a crash I can't otherwise work around

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/54632

**Pull request merged**
