### PR TITLE
[docs] Add an example to the `Base.prompt` docstring

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Review by logankilpatrick — APPROVED** [review]

**Comment by logankilpatrick** [comment]
@DilumAluthge why does `prompt` need to be prefixed with `base`?

**Comment by DilumAluthge** [comment]
It's not exported.

**Comment by logankilpatrick** [comment]
> I do not think we should export it

Can you add some context as to why? Just for my own understanding :)

**Comment by DilumAluthge** [comment]
It just seems like a very short generic word that doesn't necessarily need to be exported. Plus `Base.prompt` isn't really too long to type.

I don't feel particular strongly though, so if other people really want to export `prompt`, I won't object.

**Comment by logankilpatrick** [comment]
My only argument is to have parity with Python (where you would use `input`) but not sure if that is compelling for other people or not.

**Comment by DilumAluthge** [comment]
If, in the future, we do end up `export`ing `prompt` from `Base`, we would edit this example to change `Base.prompt(` to `prompt(`.

**Comment by IanButterworth** [comment]
Perhaps also add `Base.prompt` to the docs in this PR too?

**Comment by IanButterworth** [comment]
Oh I didn't see https://github.com/JuliaLang/julia/pull/43637

**Comment by DilumAluthge** [comment]
> Perhaps also add `Base.prompt` to the docs in this PR too?

https://github.com/JuliaLang/julia/pull/43637

I should explain my rationale for keeping this PR and https://github.com/JuliaLang/julia/pull/43637 separate. This PR (adding an example to the docstring) doesn't need a lot of discussion (and can be merged pretty quickly) because it doesn't change any guarantees about the public API.

In contrast, https://github.com/JuliaLang/julia/pull/43637 makes `Base.prompt` part of the public API, so I would want other people to chime in and confirm that they agree with the decision to make it part of the public API. So that PR will need more discussion (and maybe a quick run by triage) and will probably be open for a longer period of time.

**Pull request merged**
