### PR TITLE
Remove llvm-muladd pass and move it's functionality to to llvm-simdloop

### LINKED ISSUE #55785: Overzealous `fmul contract` marking on `*` outside of `muladd`?
I think Julia is being overzealous in marking the first `fmul` as `contact`-able here:

```Julia
julia> smat = (0.3759580090201759539070280879968777298927307128906250000000000000, -0.2925452398379911889136906211206223815679550170898437500000000000, -0.8792456187560546698733787707169540226459503173828125000000000000, -0.6857980393775208183271274720027577131986618041992187500000000000, 0.5502662724003037908460100879892706871032714843750000000000000000, -0.4763277008999405315314845665852772071957588195800781250000000000, 0.6231666106584448083793859041179530322551727294921875000000000000, 0.7820641355456769971965513832401484251022338867187500000000000000, 0.0062500602924510650915124188031768426299095153808593750000000000);

julia> svec = (0.5513258229231927654012679340667091310024261474609375000000000000, -0.8283034402416151742443162220297381281852722167968750000000000000, -0.0997659654489912867125767093057220336049795150756835937500000000)
(0.5513258229231928, -0.8283034402416152, -0.09976596544899129)

julia> f3(a, b) = muladd(a[9], b[3], muladd(a[6], b[2], a[3] * b[1]))
f3 (generic function with 1 method)

julia> @code_llvm f3(smat, svec)
```

```llvm
; Function Signature: f3(NTuple{9, Float64}, Tuple{Float64, Float64, Float64})
;  @ REPL[4]:1 within `f3`
define double @julia_f3_1940(ptr nocapture noundef nonnull readonly align 8 dereferenceable(72) %"a::Tuple", ptr nocapture noundef nonnull readonly align 8 dereferenceable(24) %"b::Tuple") #0 {
top:
; ┌ @ tuple.jl:31 within `getindex`
   %"a::Tuple[9]_ptr" = getelementptr inbounds i8, ptr %"a::Tuple", i64 64
   %"b::Tuple[3]_ptr" = getelementptr inbounds i8, ptr %"b::Tuple", i64 16
   %"a::Tuple[6]_ptr" = getelementptr inbounds i8, ptr %"a::Tuple", i64 40
   %"b::Tuple[2]_ptr" = getelementptr inbounds i8, ptr %"b::Tuple", i64 8
   %"a::Tuple[3]_ptr" = getelementptr inbounds i8, ptr %"a::Tuple", i64 16
; └
; ┌ @ float.jl:493 within `*`
   %"a::Tuple[3]_ptr.unbox" = load double, ptr %"a::Tuple[3]_ptr", align 8
   %"b::Tuple.unbox" = load double, ptr %"b::Tuple", align 8
   %0 = fmul contract double %"a::Tuple[3]_ptr.unbox", %"b::Tuple.unbox"
; └
; ┌ @ float.jl:496 within `muladd`
   %"a::Tuple[6]_ptr.unbox" = load double, ptr %"a::Tuple[6]_ptr", align 8
   %"b::Tuple[2]_ptr.unbox" = load double, ptr %"b::Tuple[2]_ptr", align 8
   %1 = fmul contract double %"a::Tuple[6]_ptr.unbox", %"b::Tuple[2]_ptr.unbox"
   %2 = fadd contract double %0, %1
   %"a::Tuple[9]_ptr.unbox" = load double, ptr %"a::Tuple[9]_ptr", align 8
   %"b::Tuple[3]_ptr.unbox" = load double, ptr %"b::Tuple[3]_ptr", align 8
   %3 = fmul contract double %"a::Tuple[9]_ptr.unbox", %"b::Tuple[3]_ptr.unbox"
   %4 = fadd contract double %2, %3
   ret double %4
; └
}
```

Why is that first `%0 = fmul contract`?  That's the `*` I wrote — and it is unexpected that passing that result to `muladd` would induce a contract without `@fastmath`.

We noticed this because having that `*` marked `contract` means that LLVM rearranges this operation on my ARM64 CPU.  Specifically, `f3` gives different answers in a function than the same code does at top-level.

```Julia
julia> f3(smat, svec)
-0.0908304842736846

julia> (a, b) = (smat, svec);

julia> muladd(a[9], b[3], muladd(a[6], b[2], a[3] * b[1]))
-0.09083048427368462

julia> # it's actually doing this:
       muladd(a[9], b[3], muladd(a[3], b[1], a[6] * b[2]))
-0.0908304842736846
```

I see this behavior both on v1.10.5 and today's nightly (1.12.0-DEV.1209 @ 55c40ce52eb).

```
julia> versioninfo()
Julia Version 1.12.0-DEV.1209
Commit 55c40ce52eb (2024-09-16 17:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
```

### PR DESCRIPTION
**Pull request by gbaraldi**
Closes https://github.com/JuliaLang/julia/issues/55785

I'm not sure if we want to backport this like this. Because that removes some functionality (the pass itself). So LLVM.jl and friends might need annoying version code. We can maybe keep the code there and just not run the pass in a backport.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
I am a little hesitant to take a probably perfectly sound pass and move it inside a definitely dangerously unsound pass

**Comment by gbaraldi** [comment]
The muladd pass is not sound. As per the issue.

**Review by vtjnash — APPROVED** [review]
Ah, I see now, the pass muladd is specifically for violating the IR semantics, after checking that the operation should be prohibited, it does it anyways:

https://github.com/JuliaLang/julia/blob/00739173311983479fee3f5f826e4b763872860a/src/llvm-muladd.cpp#L65

Okay, yep, better to keep all of the unsoundness in once place then

**Comment by vchuravy** [comment]
Could we simultaneously write some more tests for this?

**Comment by mbauman** [comment]
It's definitely a huge improvement to constrain this to `@simd`.

But this pass still scares me because of how Julia inlines user functions.  The `@simd` loop over `x += xs[i]*ys[I]` sure feels and looks fma-able.  But what about `x += f(xs[i], ys[i])`?  What about `sum(Base.splat(*), tuple.(xs, conj.(xs)))`?  That last one is particularly interesting because complex `*` _must not contract_, but we're saved because the final operation before the reduction is an add, not a mul.

Surely there's gotta be an example like complex conjugate multiplication that ends with a `mul` and would go wildly awry with `contract`?

**Comment by vtjnash** [comment]
Yes, those are some of the many soundness reasons that this pass shouldn't exist at all, but we are stuck with it for now

**Comment by gbaraldi** [comment]
Yeah `@simd` is a can of worms 😄

**Comment by gbaraldi** [comment]
I'm not sure what tests do we want to add here? I can add a test for the muladd thing. But simdloop has tests to see if it does what it says on the tin

**Comment by giordano** [comment]
I guess we should add a test that `contract` isn't being added outside of `@simd`: https://github.com/JuliaLang/julia/issues/55785#issue-2529456897

**Comment by giordano** [comment]
A simplified example from Matt's report:
```julia
julia> f(a, b, c, d) = muladd(a, b, c * d)
f (generic function with 1 method)

julia> code_llvm(f, NTuple{4,Float64})
```
```llvm
; Function Signature: f(Float64, Float64, Float64, Float64)
;  @ REPL[3]:1 within `f`
define double @julia_f_1416(double %"a::Float64", double %"b::Float64", double %"c::Float64", double %"d::Float64") #0 {
top:
; ┌ @ float.jl:493 within `*`
   %0 = fmul contract double %"c::Float64", %"d::Float64"
; └
; ┌ @ float.jl:496 within `muladd`
   %1 = fmul contract double %"a::Float64", %"b::Float64"
   %2 = fadd contract double %1, %0
   ret double %2
; └
}
```
`%0` shouldn't have `contract` (it doesn't in v1.9)

**Comment by giordano** [comment]
Looks like we only need to run the benchmarks on this one? Whole suite?

**Comment by gbaraldi** [comment]
@nanosoldier `runbenchmarks(ALL  , vs= :master )`

**Comment by gbaraldi** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55802#issuecomment-2375227459) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/9d4e528_vs_6e5e87b/report.md).

**Comment by gbaraldi** [comment]
@maleadt this will probably cause some issues in downstream GPUCompiler.

**Comment by gbaraldi** [comment]
I'm not sure what is the backport plan for this but it needs 1.10 and 1.11

**Comment by KristofferC** [comment]
> 
For backports it would be great if LLVMExtraFPMAddCombineMulAddPass is replaced with a noop, instead of being deleted.


Someone else backport this then.

**Comment by maleadt** [comment]
> Someone else backport this then.

I'll have a look.

**Comment by KristofferC** [comment]
Due to https://github.com/JuliaLang/julia/issues/56312 I will not backport this to 1.12.

**Pull request merged**
