### PR TITLE
add test for pr #10768

### PR DESCRIPTION
**Pull request by dovahcrow**
two tests for randperm(0) and randperm(-1) for #10768 , as per @StefanKarpinski's request

### CODE REVIEW

**Comment by kmsquire** [comment]
Thanks, @doomsplayer.  I think it was more of a simple request than a demand. ;-)

A few quick comments:

1. There's a macro, `@test_throws`, which tests that the function thrown by a function matches what is expected.  It works like, e.g., 

 ```julia
 test_throws BoundsError chr2ind(ss, -1)
 ```
2. It's not really necessary to check the return text of the error (and isn't possible if you use the macro)
3. When ready, can you squash the commits?  Other than keeping a clean commit history, it's also useful when running `git bisect`

Cheers!

**Comment by doomsplayer** [comment]
Oops, I'm a non-native speaker. Using "demand" here may be too strong, lol.

I'll fix the pull request as soon as possible.

**Comment by doomsplayer** [comment]
@kmsquire now everything is ok!

**Comment by kmsquire** [comment]
Looks good!  No worries about the language--I've experienced similar struggles when I try to speak/write other languages.

**Pull request merged**
