### PR TITLE
Allow type-unstable functions in mapslices

### PR DESCRIPTION
**Pull request by ararslan**
Here's my attempt at fixing #26232, which doubles as an attempt to convince someone else to fix it better.

### CODE REVIEW

**Comment by nalimilan** [comment]
I'm afraid the real fix is going to be more complex: we should use the same approach as `map`, i.e. reallocate the array if we encounter a slice with a new type.

**Comment by martinholters** [comment]
Yep, we shouldn't use `return_types` to determine the element type of non-empty containers.

**Comment by mbauman** [comment]
Oh I hate mapslices with a passion.  Let's kill it.

In your use-case, is the inner function returning a scalar or an array?  If it's a scalar, then use `map(f, eachslice(A, dims=d))` — that'll "just work."  If you need support for multiple dims, let's focus our efforts on adding that capability to `eachslice`.

If you're returning an array, though, `map` `eachslice` will return an array of arrays.  You can then concatenate them together yourself, but there's definitely a performance advantage to fusing the two together.  What if we were to internally use a datastructure like `(view(R, :, i) for i in I)` that would expose columns of a matrix as though they were single elements?  And then used `map!`?  That's not quite right, but I'd like to pursue something along these lines to pave the way towards a more consistent, reimagined version of this nonscalar application of `mapslices`.

**Comment by ararslan** [comment]
See, my plan of getting someone else to fix it better is already working 😄

**Comment by ararslan** [comment]
I will not be the one to fix it better. Hopefully someone else will. :)

**Pull request closed without merging**
