### PR TITLE
Fix #12509 (LLVM SVN API changes)

### LINKED ISSUE #12509: llvm-svn build broken
Ubuntu 14.04
I can compile julia directly, but when I tried to compile it using some special specifications. I got some error. 

Following the specification of Cxx.jl https://github.com/Keno/Cxx.jl
I made a `Make.user` file with following content:
```
override LLDB_VER=master
override LLVM_VER=svn
override LLVM_ASSERTIONS=1
override BUILD_LLVM_CLANG=1
override BUILD_LLDB=1
override USE_LLVM_SHLIB=1
override LLDB_DISABLE_PYTHON=1
```
I got the following errors: 
```
CC src/flisp/string.o
    CC src/flisp/equalhash.o
    CC src/flisp/table.o
disasm.cpp: In function ‘void jl_dump_asm_internal(uintptr_t, size_t, size_t, const llvm::object::ObjectFile*, llvm::raw_ostream&)’:
disasm.cpp:314:83: warning: ‘void llvm::MCObjectFileInfo::InitMCObjectFileInfo(llvm::StringRef, llvm::Reloc::Model, llvm::CodeModel::Model, llvm::MCContext&)’ is deprecated (declared at /usr/people/jingpeng/libs/julia/usr/include/llvm/MC/MCObjectFileInfo.h:192) [-Wdeprecated-declarations]
     MOFI->InitMCObjectFileInfo(TripleName, Reloc::Default, CodeModel::Default, Ctx);
                                                                                   ^
    CC src/flisp/iostream.o
    CC src/flisp/julia_extensions.o
codegen.cpp: In function ‘llvm::Function* emit_function(jl_lambda_info_t*)’:
codegen.cpp:4128:43: error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’
             varinfo.dinfo = ctx.dbuilder->createLocalVariable(
                                           ^
codegen.cpp:4129:17: error: ‘DW_TAG_arg_variable’ is not a member of ‘llvm::dwarf’
                 llvm::dwarf::DW_TAG_arg_variable,    // Tag
                 ^
codegen.cpp:4141:56: error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’
             ctx.vars[ctx.vaName].dinfo = ctx.dbuilder->createLocalVariable(
                                                        ^
codegen.cpp:4142:17: error: ‘DW_TAG_arg_variable’ is not a member of ‘llvm::dwarf’
                 llvm::dwarf::DW_TAG_arg_variable,    // Tag
                 ^
codegen.cpp:4157:43: error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’
             varinfo.dinfo = ctx.dbuilder->createLocalVariable(

codegen.cpp:4158:17: error: ‘DW_TAG_auto_variable’ is not a member of ‘llvm::dwarf’
                 llvm::dwarf::DW_TAG_auto_variable,    // Tag
                 ^
codegen.cpp:4174:43: error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’
             varinfo.dinfo = ctx.dbuilder->createLocalVariable(
                                           ^
codegen.cpp:4175:17: error: ‘DW_TAG_auto_variable’ is not a member of ‘llvm::dwarf’
                 llvm::dwarf::DW_TAG_auto_variable,    // Tag
                 ^
    CC src/flisp/flmain.o
codegen.cpp: In function ‘void init_julia_llvm_env(llvm::Module*)’:
codegen.cpp:5323:47: error: ‘createBasicAliasAnalysisPass’ was not declared in this scope
         FPM->add(createBasicAliasAnalysisPass());
                                               ^
make[1]: *** [codegen.o] Error 1
make[1]: *** Waiting for unfinished jobs....
    LINK src/flisp/libflisp.a
    LINK src/flisp/flisp
make: *** [julia-src-release] Error 2
```

any info is appreciated.

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by vtjnash** [comment]
it's too bad you couldn't test this locally against llvm3.3.....(shameless plug for #12463)

**Comment by ihnorton** [comment]
Updated to build against 3.3.

**Comment by Keno** [comment]
Thanks @ihnorton, I was gonna get to that eventually, but this makes it easier :P.

**Comment by StefanKarpinski** [comment]
CI passes. Can this be merged?

**Comment by ihnorton** [comment]
(I squashed the change to avoid a failing commit in the history)

**Pull request merged**
