### PR TITLE
show methods for SharedArray

### LINKED ISSUE #19219: SharedArray: Segfault displaying a locally unmapped SharedArray. Also map shared array segments on master when created from a worker on localhost.
I've been having all sorts of issues managing my Arrays across processes, but here's a bug I stumbled upon in the process. It appears that when I have created a SharedArray on a certain process, and then try to assign it within a different process the underlying data isn't copied. The assignment _appears_ to work, but when I __access__ the data it causes a SegFault. Here's some sample code:

```
test_dict = Dict()

addprocs(1)

@everywhere function make_array()
  a = convert(SharedArray,rand((100,100)))
  @spawnat(1, save_array(a))
end

function save_array(a)
  test_dict[1] = a
end

@sync @spawnat(2, make_array())

println(keys(test_dict))

println(test_dict[1])
```

Interestingly, `keys(test_dict)` shows the correct keys. If you change `SharedArray` to `Array` the code works fine.

Here's the backtrace (using Julia 0.5.0):

```
signal (11): Segmentation fault: 11
while loading sharedarray_crash.jl, in expression starting on line 18
_getindex at ./abstractarray.jl:786 [inlined]
getindex at ./abstractarray.jl:752
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1392 [inlined]
jl_f__apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/builtins.c:547
isassigned at ./abstractarray.jl:186
print_matrix_repr at ./show.jl:1567
unknown function (ip: 0x3220bd546)
#showarray#330 at ./show.jl:1611
unknown function (ip: 0x3220bad0d)
print at ./strings/io.jl:8
unknown function (ip: 0x3220ba646)
print at ./strings/io.jl:19
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
println at ./coreio.jl:5
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
do_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:66
eval at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:558
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20125 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
process_options at ./client.jl:262
_start at ./client.jl:318
jlcall__start_21452 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
true_main at julia (unknown line)
main at julia (unknown line)
Allocations: 4220563 (Pool: 4219608; Big: 955); GC: 5
terminated by signal SIGSEGV (Address boundary error)
```

### PR DESCRIPTION
**Pull request by amitmurthy**
closes #19219

### CODE REVIEW

**Comment by amitmurthy** [comment]
Thanks @KristofferC for helping with this.

**Comment by amitmurthy** [comment]
Display is now like this:
```
julia> s=remotecall_fetch(()->SharedArray(Int, (5,5);pids=procs()), 2)
5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
mapped as a 5x5 SharedArray{Int64,2}


julia> show(s)
[0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0]
julia> s=remotecall_fetch(()->SharedArray(Int, (5,5)), 2)
5x5 SharedArray{Int64,2}: <unmapped on node 1>


julia> show(s)
5x5 SharedArray{Int64,2}: <unmapped on node 1>
```

If the shared array is created from a worker, and `pids` keyword argument is unspecified, it is not mapped on the master.

**Comment by amitmurthy** [comment]
On second thoughts, I have updated this PR to retrieve the shared array from a node mapping the array and display locally. Now it displays the same whether it is mapped locally or not.

```
julia> s=remotecall_fetch(()->SharedArray(Int, (2,2); pids=[2,3]), 2)
2×2 SharedArray{Int64,2}:
 0  0
 0  0

julia> SharedArray(Int, (2,2); pids=procs())
2×2 SharedArray{Int64,2}:
 0  0
 0  0

julia> SharedArray(Int, (2,2))
2×2 SharedArray{Int64,2}:
 0  0
 0  0
```

**Comment by amitmurthy** [comment]
OSX error is unrelated. Will squash and merge tomorrow.

**Comment by tkelman** [comment]
this needs tests

**Pull request merged**
