### PR TITLE
Update LLVM build to 14.0.6+2

### LINKED ISSUE #48020: Backtrace source info lost in new compiled package image?
Working on a locally developed package where I have an error during my `__init__` function:

```julia
julia> using Flate, Test, Flate.GoTypes
[ Info: Precompiling Flate [9093563c-7325-43a3-bc6a-59ea82c1fd16]
ERROR: InitError: UndefVarError: `min` not defined
Stacktrace:
 [1] init(h::Flate.HuffmanDecoder, lengths::Flate.GoTypes.Go.Slice{Int64})
   @ Flate ~/.julia/compiled/v1.10/Flate/dVx3G_ADVEb.dylib:-1
during initialization of module Flate
```

With the problem being `@ Flate ~/.julia/compiled/v1.10/Flate/dVx3G_ADVEb.dylib:-1` where I don't have a file + line of where the error is happening. Can produce the local package setup if that's helpful.

### LINKED ISSUE #48057: julia 1.9.0-beta2 fails to build from source on macOS
We are seeing the build failure on Homebrew CI at https://github.com/Homebrew/homebrew-core/pull/119456
The error seems to be `lld: error: LC_DYLD_INFO_ONLY not found`.

```
Sysimage built. Summary:
Base ────────  15.284967 seconds 41.4134%
Stdlibs ─────  21.622479 seconds 58.5843%
Total ───────  36.908299 seconds
Warning: git information unavailable; versioning information limited
 cd /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/base && if ! JULIA_BINDIR=/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/bin WINEPATH="/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/bin;$WINEPATH" JULIA_NUM_THREADS=1  /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/bin/julia -O3 -C "generic;cortex-a57;thunderx2t99;armv8.2-a,crypto,fullfp16,lse,rdm" --output-o /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/julia/sys-o.a.tmp  --startup-file=no --warn-overwrite=yes --sysimage /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/julia/sys.ji /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl 1; then echo '*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***'; false; fi 
lld: error: LC_DYLD_INFO_ONLY not found in /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/libjulia.dylib
lld: error: LC_DYLD_INFO_ONLY not found in /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/libjulia-internal.dylib
ERROR: failed process: Process(setenv(`/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/tools/lld -flavor darwin -arch arm64 -undefined dynamic_lookup -platform_version macos 12.6 12.3 '' -dylib -o /private/tmp/jl_kzKcXi/compiled/v1.9/jl_eltPtw -all_load /private/tmp/jl_kzKcXi/compiled/v1.9/jl_YcrnFt '' -L/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib -L/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/julia -L/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib -ljulia -ljulia-internal`,["MFLAGS=- --jobserver-fds=3,4 -j", "PATH=/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/tools:/opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/brotli/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/libidn2/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/openldap/bin:/opt/homebrew/opt/rtmpdump/bin:/opt/homebrew/opt/lz4/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/zstd/bin:/opt/homebrew/opt/curl/bin:/opt/homebrew/opt/gcc/bin:/opt/homebrew/opt/libgit2/bin:/opt/homebrew/opt/mbedtls@2/bin:/opt/homebrew/opt/p7zip/bin:/opt/homebrew/opt/pcre2/bin:/opt/homebrew/opt/metis/bin:/opt/homebrew/opt/suite-sparse/bin:/usr/bin:/bin:/usr/sbin:/sbin", "CXX=clang++ -mmacosx-version-min=12", "USE_SYSTEM_ZLIB=1", "HOMEBREW_USER_AGENT_CURL=Homebrew/3.6.16-97-ge76c55e (Macintosh; arm64 Mac OS X 12.6) curl/7.79.1", "HOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/brew", "HOMEBREW_PRODUCT=Homebrew", "BUILDROOT=/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2", "MAKEFLAGS= --jobserver-fds=3,4 -j -- TAGGED_RELEASE_BANNER=Built\\ by\\ Homebrew\\ (v1.9.0-beta2) JULIA_CPU_TARGET=generic;cortex-a57;thunderx2t99;armv8.2-a,crypto,fullfp16,lse,rdm MACOSX_VERSION_MIN=12 LOCALBASE=/opt/homebrew PYTHON=python3 USE_BLAS64=0 LIBLAPACKNAME=libopenblas LIBLAPACK=-lopenblas LIBBLASNAME=libopenblas LIBBLAS=-lopenblas USE_SYSTEM_P7ZIP=1 USE_SYSTEM_ZLIB=1 USE_SYSTEM_PATCHELF=1 USE_SYSTEM_LIBGIT2=1 USE_SYSTEM_CURL=1 USE_SYSTEM_NGHTTP2=1 USE_SYSTEM_LIBSSH2=1 USE_SYSTEM_MBEDTLS=1 USE_SYSTEM_UTF8PROC=1 USE_SYSTEM_LIBSUITESPARSE=1 USE_SYSTEM_MPFR=1 USE_SYSTEM_GMP=1 USE_SYSTEM_LAPACK=1 USE_SYSTEM_BLAS=1 USE_SYSTEM_OPENLIBM=1 USE_SYSTEM_PCRE=1 USE_SYSTEM_CSL=1 sysconfdir=/opt/homebrew/etc prefix=/opt/homebrew/Cellar/julia/1.9.0-beta2 USE_BINARYBUILDER=0 VERBOSE=1", "MAKEOVERRIDES=\${-*-command-variables-*-}"  …  "HOMEBREW_GITHUB_PACKAGES_AUTH=***", "ZERO_AR_DATE=1", "HOMEBREW_ANALYTICS_IDS=UA-76679469-1", "USE_SYSTEM_PCRE=1", "HOMEBREW_LIBRARY_PATHS=/opt/homebrew/opt/openssl@1.1/lib:/opt/homebrew/opt/openldap/lib:/opt/homebrew/opt/curl/lib:/opt/homebrew/opt/mbedtls@2/lib:/opt/homebrew/opt/openblas/lib:/opt/homebrew/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries", "JULIA_CPU_TARGET=generic;cortex-a57;thunderx2t99;armv8.2-a,crypto,fullfp16,lse,rdm", "HOMEBREW_ARCHFLAGS=", "USE_BINARYBUILDER=0", "HOMEBREW_GIT_CONFIG_FILE=/opt/homebrew/.git/config", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:565 [inlined]
 [2] run(::Cmd, ::Base.DevNull, ::Vararg{Any}; wait::Bool)
   @ Base ./process.jl:480
 [3] run
   @ ./process.jl:477 [inlined]
 [4] link_image (repeats 2 times)
   @ ./linking.jl:144 [inlined]
 [5] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2055
 [6] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:2016
 [7] top-level scope
   @ none:3
ERROR: LoadError: failed process: Process(`/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/bin/julia -O0 --sysimage /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/julia/sys.ji --trace-compile=/private/tmp/jl_kzKcXi/jl_ilK1exWvIN --startup-file=no -Cnative -e 'pushfirst!(DEPOT_PATH, "/private/tmp/jl_kzKcXi");
Base.PRECOMPILE_TRACE_COMPILE[] = "/private/tmp/jl_kzKcXi/jl_WX45ybgvab";
Base.compilecache(Base.PkgId("__PackagePrecompilationStatementModule"), "/private/tmp/jl_kzKcXi/__PackagePrecompilationStatementModule/src/__PackagePrecompilationStatementModule.jl")
# NOTE: these were moved to the end of Base.jl. TODO: move back here.
# # Used by Revise & its dependencies
# while true  # force inference
# delete!(push!(Set{Module}(), Base), Main)
# m = first(methods(+))
# delete!(push!(Set{Method}(), m), m)
# empty!(Set())
# push!(push!(Set{Union{GlobalRef,Symbol}}(), :two), GlobalRef(Base, :two))
# (setindex!(Dict{String,Base.PkgId}(), Base.PkgId(Base), "file.jl"))["file.jl"]
# (setindex!(Dict{Symbol,Vector{Int}}(), [1], :two))[:two]
# (setindex!(Dict{Base.PkgId,String}(), "file.jl", Base.PkgId(Base)))[Base.PkgId(Base)]
# (setindex!(Dict{Union{GlobalRef,Symbol}, Vector{Int}}(), [1], :two))[:two]
# (setindex!(IdDict{Type, Union{Missing, Vector{Tuple{LineNumberNode, Expr}}}}(), missing, Int))[Int]
# Dict{Symbol, Union{Nothing, Bool, Symbol}}(:one => false)[:one]
# Dict(Base => [:(1+1)])[Base]
# Dict(:one => [1])[:one]
# Dict("abc" => Set())["abc"]
# pushfirst!([], sum)
# get(Base.pkgorigins, Base.PkgId(Base), nothing)
# sort!([1,2,3])
# unique!([1,2,3])
# cumsum([1,2,3])
# append!(Int[], BitSet())
# isempty(BitSet())
# delete!(BitSet([1,2]), 3)
# deleteat!(Int32[1,2,3], [1,3])
# deleteat!(Any[1,2,3], [1,3])
# Core.svec(1, 2) == Core.svec(3, 4)
# # copy(Core.Compiler.retrieve_code_info(Core.Compiler.specialize_method(which(+, (Int, Int)), [Int, Int], Core.svec())))
# any(t->t[1].line > 1, [(LineNumberNode(2,:none),:(1+1))])
# break   # end force inference
# end
using Artifacts, Base.BinaryPlatforms, Libdl
artifacts_toml = abspath(joinpath(Sys.STDLIB, "Artifacts", "test", "Artifacts.toml"))
artifact_hash("HelloWorldC", artifacts_toml)
oldpwd = pwd(); cd(dirname(artifacts_toml))
macroexpand(Main, :(@artifact_str("HelloWorldC")))
cd(oldpwd)
artifacts = Artifacts.load_artifacts_toml(artifacts_toml)
platforms = [Artifacts.unpack_platform(e, "HelloWorldC", artifacts_toml) for e in artifacts["HelloWorldC"]]
best_platform = select_platform(Dict(p => triplet(p) for p in platforms))
dlopen("libjulia", RTLD_LAZY | RTLD_DEEPBIND)

'`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:480
  [3] run
    @ ./process.jl:477 [inlined]
  [4] (::Main.anonymous.var"#1#5"{Set{String}, String})(prec_path::String)
    @ Main.anonymous /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl:274
  [5] mktempdir(fn::Main.anonymous.var"#1#5"{Set{String}, String}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:760
  [6] mktempdir (repeats 2 times)
    @ ./file.jl:756 [inlined]
  [7] generate_precompile_statements()
    @ Main.anonymous /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl:256
  [8] top-level scope
    @ /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl:431
  [9] eval(m::Module, e::Any)
    @ Core ./boot.jl:370
 [10] top-level scope
    @ /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl:10
in expression starting at /private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/contrib/generate_precompile.jl:7
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[2]: *** [/private/tmp/julia-20221231-64074-1neh5ig/julia-1.9.0-beta2/usr/lib/julia/sys-o.a] Error 1
make[1]: *** [julia-sysimg-release] Error 2
make: *** [install] Error 2
```

Possible related links:
- https://leanprover-community.github.io/archive/stream/270676-lean4/topic/ld64.2Elld.20dynamic.20link.20errors.20on.20MacOS.html
- https://github.com/llvm/llvm-project/issues/54550
- https://github.com/llvm/llvm-project/commit/94e0f8e001002b828c42048f383806295e7abbb2

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes #48020 and fixes #48057

Maybe also #48499

### CODE REVIEW

**Comment by giordano** [comment]
Checksums are not right?

**Comment by giordano** [comment]
It doesn't seem to fix #48020 for me, I still see the broken stacktrace.

**Comment by gbaraldi** [comment]
I do get the correct error here. Maybe add a test?

**Comment by giordano** [comment]
```
julia> using Cuba
ERROR: InitError: This is an error inside __init__
Stacktrace:
  [1] error
    @ ~/.julia/compiled/v1.10/Cuba/UN24D_YmJXR.dylib:-1
  [2] __init__()
    @ Cuba ~/.julia/compiled/v1.10/Cuba/UN24D_YmJXR.dylib:-1
  [3] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1070
  [4] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1014
  [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1416
  [6] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1693
  [7] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1570
  [8] macro expansion
    @ ./loading.jl:1558 [inlined]
  [9] macro expansion
    @ ./lock.jl:267 [inlined]
 [10] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1521
during initialization of module Cuba

julia> versioninfo()
Julia Version 1.10.0-DEV.436
Commit 3341a02f76* (2023-02-05 20:15 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by giordano** [comment]
And I still get the same on a completely fresh clone of Julia, to avoid caching issues (but I did run `make cleanall` before compiling in my usual repo).  I have macOS 12.6, in case that makes any difference.

**Comment by vchuravy** [comment]
`make -C deps reinstall-llvm`?

**Comment by giordano** [comment]
That didn't change anything.  Not that I was expecting anything else since I _just_ cloned this repository into a new directory and did a complete rebuild of julia without any pre-existing cache 🙂

**Comment by gbaraldi** [comment]
For reference this fixes it in Macos13 but not on 12.6

**Comment by vchuravy** [comment]
@nanosoldier `runtests()`

**Comment by vchuravy** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48544#issuecomment-1421327080) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
PkgEval is a bit unstable due to an OS upgrade, so let's try again:

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/48544#issuecomment-1422079622) failed. Consult the server logs for more details (cc @maleadt).

**Comment by maleadt** [comment]
And again:

@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/48544#issuecomment-1422091353) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3341a02_vs_0231c22/report.html).

**Comment by oscardssmith** [comment]
@vchuravy when trying to build with local LLVM, this gives me 
```
make USE_BINARYBUILDER_LLVM=0 -j
fatal: couldn't find remote ref julia-14.0.6-2
fatal: couldn't find remote ref remotes/origin/julia-14.0.6-2
make[1]: *** [~/julia/deps/llvm.mk:11:~/julia/deps/srccache/llvm/source-extracted] Error 128
make: *** [Makefile:75: julia-deps] Error 2
```
Any idea what's going on?

**Comment by stahta01** [comment]
> I think we might be missing a tag on our llvm branch @vchuravy

Correct the tag is missing or the version was supposed to be julia-14.0.6-1 

```
git fetch origin julia-14.0.6-2
fatal: couldn't find remote ref julia-14.0.6-2
```
```
git fetch origin julia-14.0.6-1
From https://github.com/JuliaLang/llvm-project
 * tag                         julia-14.0.6-1 -> FETCH_HEAD
```

**Comment by vchuravy** [comment]
Sorry pushed the tag.

**Comment by DilumAluthge** [comment]
@vchuravy Can you update the following source checksum?

```
ERROR: The working directory is dirty.
--
  | Output of git status:
  | HEAD detached at 6cbcee9cb05
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  |  
  | deps/checksums/llvm-julia-14.0.6-2.tar.gz/
  |  
  | nothing added to commit but untracked files present (use "git add" to track)
  | 🚨 Error: The command exited with status 1
```

**Pull request merged**
