### PR TITLE
World counter type fix

### PR DESCRIPTION
**Pull request by c42f**
The world age counter is `size_t` on the C side (eg, in `_jl_method_instance_t`) which is always unsigned, but set to `jl_long_type` (`Int`) on the julia side.  This seems dangerous because we use `typemax(UInt)` as an upper bound for the world age in various places in C but sometimes read these in julia, which I assume could result in the julia side seeing `max_world` as `typemin(Int)`, eg, here

https://github.com/JuliaLang/julia/blob/1216e5f60cd2b23e29856b5227399ab0f3abef76/base/inference.jl#L3044

Unfortunately the fix here moves a couple of type definitions back into C to make this work on both 32 and 64 bit. We could avoid that by making the world age an `Int` instead, but I thought I'd keep this as non-intrusive as possible.

Ref: https://github.com/JuliaLang/julia/issues/23981 (the change here is not a fix for that issue, merely fixing an oddity I noticed while in the process of debugging).

### CODE REVIEW

**Comment by vtjnash** [comment]
> but sometimes read these in julia

[citation needed]

**Comment by c42f** [comment]
Well it's certainly a face<-palm moment finding `max_world` doing a reinterpret inside reflection.jl, as I was just dumping `linfo.max_world` out directly during debugging.  Unsure whether to close this PR or not, I feel having the "wrong" types is quite confusing but other than that there's nothing really wrong here.

**Comment by Keno** [comment]
Sounds like this wasn't actually needed. Re-open if there's something here.

**Comment by c42f** [comment]
Yes, there's nothing broken here. It's just confusing to newcomers that the world counter on the julia side is `Int` rather than `UInt` in the core data structures.

**Comment by timholy** [comment]
I've been bitten by this too and I agree seems confusing. I guess this has to be balanced against the bootstrap-related issues, though.

**Comment by StefanKarpinski** [comment]
Why not just arrange for this field to appear in Julia as `UInt` instead of `Int`?

**Comment by c42f** [comment]
> Why not just arrange for this field to appear in Julia as UInt instead of Int

That's what this PR does.  The tradeoff was that the `UInt` definition needed to be moved into C.

**Comment by StefanKarpinski** [comment]
Ah, I see. Not worth it then.

**Pull request closed without merging**
