### PR TITLE
S2maki/rational io

### PR DESCRIPTION
**Pull request by keith-mason-conning**
Add ability to read/write Rational scalars to IO.  Return the correct number of bytes written to IO when writing a Complex.

### CODE REVIEW

**Comment by hayd** [comment]
Hmmm, the fact that write returns the bytes written to IO appears not to be documented (in the [docstring](http://julia.readthedocs.org/en/latest/stdlib/io-network/#Base.write) or in the [docs](http://julia.readthedocs.org/en/latest/manual/networking-and-streams/#basic-stream-i-o)).

These would probably be clearer as:

    write(s, real(z), imag(z))

(although IMO convention is to use io rather than s here), this handles the + already.

**Comment by s2maki** [comment]
Correct, the documentation doesn't mention it.  However, most instances of `write` do return the number of bytes written, and it is a common thing to do in many languages.  I would prefer that it either return something useful, or return nothing.  Returning an incorrect number of bytes is just confusing.

The `write(s, x, y)` style may optimize better as well.

`s` was already used for the IO stream here, so I didn't think it needed changing.  If there is a newer convention to use `io`, this would be a good time to update it.

**Comment by hayd** [comment]
+1 to all you said. I think documenting (and testing, this definitely could do with tests!) this behaviour is a good idea.

**Comment by hayd** [comment]
(tests for write are in tests/iobuffer.jl and the write docstring is in base/docs/helpdb.jl)

**Comment by hayd** [comment]
Looks good to me, thanks! But please could you [squash](http://julia.readthedocs.org/en/latest/manual/packages/#squashing-and-rebasing) these commits into one?

**Comment by s2maki** [comment]
squashed

**Comment by hayd** [comment]
Thanks!

I'm going to add the backport pending tag, as this seems a very minor change (half bug-fix, half enhancement). Will see what @tkelman thinks...

**Pull request merged**
