### PR TITLE
Annotate function arguments with sext/zext

### PR DESCRIPTION
**Pull request by vchuravy**
https://bugs.llvm.org/show_bug.cgi?id=30451#c11 pointed out that we
need to annotate the parameters of functions with `sext`/`zext` so that
the backend can use the right semantics when promoting from a narrower type
to a register type. We do this for ccall (x-ref: #978) already, but it seems
like we need to do this generally.

Does anybody know if there are other places I might need to add this?

### CODE REVIEW

**Comment by vtjnash** [comment]
Sounds like an LLVM bug in the PPC backend. It's okay for it to use anyext in the target lowering only because the bits are undef. But the PPC backend codegen is treating them as if they were defined (e.g. missing a trunc & sext before the atomicrmw to legalize the register content)

**Comment by Keno** [comment]
I concur with @vtjnash's analysis.

**Comment by Keno** [comment]
Doesn't mean that we shouldn't do this also though. Would probably save a few unnecessary instructions in a few places.

**Comment by vchuravy** [comment]
@nemanjai do you have any comments?

**Comment by vchuravy** [comment]
> Doesn't mean that we shouldn't do this also though.

Good to merge then?

**Comment by nemanjai** [comment]
LGTM.

**Comment by Keno** [comment]
The PowerPC backend should still be fixed independently. Frankly, I'd prefer for that to happen first before we merge this, since otherwise we risk hiding the bug here. There's nothing preventing a signed comparison with an unsigned type, which would exhibit the exact same symptoms, but with this PR applied the bug is hidden.

**Comment by vtjnash** [comment]
I think we could write a test to show that case too, by passing in a UInt16 and then reinterpreting it as Int16 before the atomic op. But likely easier to show with an llvm unit test.

**Comment by Keno** [comment]
Sure, if @vchuravy wants to add that test, I'm happy to merge this ;).

**Comment by vchuravy** [comment]
I will merge this once CI is green. Upstream PR for the PPC backend is https://reviews.llvm.org/D94058

**Comment by vchuravy** [comment]
backported in https://github.com/JuliaLang/julia/pull/39160

**Pull request merged**
