### PR TITLE
Fix a bug in `stack`'s DimensionMismatch error message

### PR DESCRIPTION
**Pull request by mcabbott**
`stack` does not require that the inner iterator defines `axes`, but the code to assemble an error message assumed this.

Found here: https://discourse.julialang.org/t/reduce-hcat-is-type-unstable/112800/3

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
LGTM

**Comment by fingolfin** [comment]
Sounds like something we could/should backport to 1.11 and 1.10

**Comment by jishnub** [comment]
Test failures look unrelated, so this should be good to merge

**Comment by giordano** [comment]
Test failures are #55240 and #55235

**Pull request merged**
