### PR TITLE
Optimized arithmetic methods for strided triangular matrices

### PR DESCRIPTION
**Pull request by jishnub**
This uses broadcasting for operations like `A::UpperTriangular + B::UpperTriangular` in case the parents are `StridedMatrix`es. Looping only over the triangular part is usually faster for large matrices, where presumably memory is the bottleneck.

Some performance comparisons, using
```julia
julia> U = UpperTriangular(rand(1000,1000));

julia> U1 = UnitUpperTriangular(rand(size(U)...));
```
| Operation | master | PR |
| --------------- | ---------- | ----- |
|`-U` |`1.011 ms (3 allocations: 7.63 MiB)` |`559.680 μs (3 allocations: 7.63 MiB)` |
|`U + U`/`U - U` |`971.740 μs (3 allocations: 7.63 MiB)` | `560.063 μs (3 allocations: 7.63 MiB)` |
|`U + U1`/`U - U1` |`3.014 ms (9 allocations: 22.89 MiB)` | `944.772 μs (3 allocations: 7.63 MiB)` |
|`U1 + U1` |`4.509 ms (12 allocations: 30.52 MiB)` | `1.687 ms (3 allocations: 7.63 MiB)` |
|`U1 - U1` |`3.357 ms (9 allocations: 22.89 MiB)` | `1.763 ms (3 allocations: 7.63 MiB)` |

I've retained the existing methods as fallback, in case there's current code that works without broadcasting.

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]
LGTM

**Comment by jishnub** [comment]
Although this PR improves performance and resolves several issues, I don't really like the hacky nature of the new methods that are specifically working around bugs with using a partly initialized `A.data`. However, perhaps there is existing code that works correctly without broadcasting, so we may need to retain the general methods that forward the arithmetic operations to the parent.

**Comment by dkarrasch** [comment]
Ready to go? I still like it. 😉

**Comment by jishnub** [comment]
Looks good to me. Perhaps we should update the branch to ensure that the tests are passing? Unfortunately my computer has broken down, so progress has stalled

**Comment by jishnub** [comment]
Test failures appear unrelated, so should be good

**Pull request merged**
