### PR TITLE
fix spawn test for case insensitive file systems

### PR DESCRIPTION
**Pull request by jakebolewski**

### CODE REVIEW

**Comment by tkelman** [comment]
Can you provide some context, what were the conditions under which this test was failing?

**Comment by jakebolewski** [comment]
I'm having a hard time reproducing this particular error, so I guess I'll close for now.

**Comment by jakebolewski** [comment]
I just ran into this again

@tkelman the issue is that pwd respects what casing of the folder name you cd into.

On OSX I have `~/Julia/julia`

If I cd into the julia folder with
`cd ~/Julia/julia` then `pwd` returns `/Users/jake/Julia/julia`

however if I cd into the directory with
`cd ~/julia/julia` then `pwd` returns `/Users/jake/julia/julia`

so depending on what casing I give to the folder name when calling `cd` into the test folder, the tests will pass or fail.

**Comment by tkelman** [comment]
And that ends up different between `setenv(cmd; dir="..")` vs `sh -c "cd .. && pwd -P"` ? Fair enough. Case insensitive filesystems are so awful.

**Comment by StefanKarpinski** [comment]
> Case insensitive filesystems are so awful.

They are literally the worst.

**Comment by jakebolewski** [comment]
I think we should export `samefile`. It seems useful if people are going to write correct cross platform code.

**Comment by tkelman** [comment]
#9436

**Comment by tkelman** [comment]
Uh, this fails on both Travis and AppVeyor. Would've been good to at least wait for it to pass... https://travis-ci.org/JuliaLang/julia/jobs/66301708

**Comment by tkelman** [comment]
Fixed by c94629c444e72ba5586eedc8a6a88ac9453f68d6 - the trailing newline was making the `ispath` fail.

**Comment by jakebolewski** [comment]
oops, thanks

**Comment by tkelman** [comment]
`samefile` got a little smarter last month. Before that it would've always returned true if neither input exists, including probably in this case of not dropping the trailing `\n`.

**Comment by tkelman** [comment]
Damn, I need to change this again. On Windows, `sh` is going to return posix-style paths that are not valid according to `ispath`.

**Pull request merged**
