### PR TITLE
Refactor java benchmark to remove duplicated code.

### PR DESCRIPTION
**Pull request by ryanhamilton**
Refactor java benchmark to remove duplicated code.
Also added header comment to make benchmark purpose clear.
File was mix of tabs and spaces, replaced all with tabs.

### CODE REVIEW

**Comment by ryanhamilton** [comment]
"Successful" running on windows: 
Note File break is due to previous issue.
```
>mvn compile exec:java
...
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ javaBenchmarks ---
javaPure,fib,0.127773
javaPure,parse_int,0.956501
javaPure,mandel,0.325333
javaPure,quicksort,1.102234
javaPure,pi_sum,47.165159
javaPure,rand_mat_stat,35.513701
javaPure,rand_mat_mul,1201.615994
javaPure,sinc_sum,0.189350
java.io.FileNotFoundException: \dev\null (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at PerfPure.printfd(PerfPure.java:148)
```

**Comment by tkelman** [comment]
> File was mix of tabs and spaces, replaced all with tabs.

Could you go the other way around? We use spaces for our Julia and C coding conventions, may as well do the same for code in other languages in this repo.

**Comment by ryanhamilton** [comment]
@tkelman spaced out

**Comment by StefanKarpinski** [comment]
Thanks! This looks good to me. Maybe @aviks should take a quick look as our local Java pro?

**Comment by ViralBShah** [comment]
Ping @aviks

**Comment by ViralBShah** [comment]
The Java version of mandel doesn't seem to be creating the complex array - it seems to be summing up everything inline, which gives it a performance edge. Hope I am not missing something.

Perhaps not related to this PR, but would be nice to fix it up.

**Comment by ViralBShah** [comment]
See #13729 and #13673

**Comment by ryanhamilton** [comment]
Chasing up on this to see if we can get it merged?

**Comment by ViralBShah** [comment]
Just checking if you can fix the Java benchmark of Mandel as discussed in the linked issues. If you would prefer to keep this PR to just refactoring, could you squash the commits?

Just want to mention that the mandel benchmark in Java has a huge advantage over Julia and others, the way it is right now.

**Comment by ryanhamilton** [comment]
commits squashed.

**Comment by aviks** [comment]
Thanks! LGTM.

**Pull request merged**
