### PR TITLE
Threads tests

### PR DESCRIPTION
**Pull request by bramtayl**
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/threadingconstructs.jl#L86)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/threadingconstructs.jl#L90)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/threadingconstructs.jl#L99)

### CODE REVIEW

**Comment by bramtayl** [comment]
CI failure unrelated?

**Comment by dkarrasch** [comment]
I noticed you include the entire the exact error message string in the `@test_throws`, but isn't this a bit overly specific? To me it looks like we're testing/"guaranteeing" too much.

**Comment by bramtayl** [comment]
Sure I can see that. Happy to change it back to `ArgumentError`.

**Comment by bramtayl** [comment]
On the other hand, spelling out the error message is a good way to test whether it is correct, especially because its easy to make interpolation errors, e.g. `"$typeof(x)"` instead of `"$(typeof(x))"`

**Comment by dkarrasch** [comment]
It may depend, I agree. My comment was more of general kind, proposing to test the full error message sparsely, not always.

**Comment by bramtayl** [comment]
Let me know if you want me rebase this

**Pull request closed without merging**
