### PR TITLE
add define flag for experimenting with OrcJIT support

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by tkelman** [comment]
lgtm

**Comment by jakebolewski** [comment]
I see this also fixes @Keno comment.  @ihnorton

**Comment by ViralBShah** [comment]
Should we be merging this in a feature freeze? Perhaps I missed some discussion somewhere.

**Comment by jakebolewski** [comment]
It fixes a bug. There are no exposed features here.

**Comment by ViralBShah** [comment]
Ok. Would be nice to have a pointer to the bug. The commit didn't suggest what was being fixed and looked like it was to experiment with OrcJIT support.

**Comment by tkelman** [comment]
ref https://github.com/JuliaLang/julia/commit/7bf34490dd90aaa7329b56f5689ea1cf57a83500#commitcomment-13103413

the defines for orcjit are all commented out, but yeah the bugfix and the new defines could have been separate commits

**Comment by JeffBezanson** [comment]
> the bugfix and the new defines could have been separate commits

Yes!!

> *No description provided.*

Not the optimal amount of description.

**Comment by carnaval** [comment]
we should start naming those JIT_1 ... JIT_N, they will probably make a new api in a couple of releases

**Comment by vtjnash** [comment]
>  the bugfix and the new defines could have been separate commits

This ran into an assertion failure inside OrcJIT. I was not aware of Keno's comment or that it affected any other JIT.

>    No description provided.

Not much more to say.

> We should start naming those JIT_1 ... JIT_N, they will probably make a new api in a couple of releases

Indeed. This is actually the OrcMCJIT, so it might be good to try one of the four actual OrcJIT examples extracted from the tutorial: https://llvm.org/svn/llvm-project/llvm/trunk/examples/Kaleidoscope/Orc/

**Pull request merged**
