### PR TITLE
support line number offset in parsing

### PR DESCRIPTION
**Pull request by simeonschaub**
This adds an extra keyword argument `lineno` to `Meta.parseatom` and
`Meta.parseall`, which causes the emitted `LineNumberNode`s to start at
the given line number instead.

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Review by c42f — COMMENTED** [review]
The code looks nice here; it's very consistent with the other parsing-related code and you've managed to plumb it very neatly through all the layers of FFI :-)

I'm curious about the use case for this. How will external code supply the initial line number reliably? Even that's not 100% trivial, with any of `\r`, `\r\n` or `\n` being acceptable as newlines.

I guess this will be most useful for line numbers in string macros? For that use case I foresee some problems with triple quoted strings having newlines removed in the deindenting preprocessing stage which the macro can't detect. For example the following are seen the same way by the macro:

```julia
julia> dump(:(x"""hi"""))
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Symbol @x_str
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[2]
    3: String "hi"

julia> dump(:(x"""
       hi"""))
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Symbol @x_str
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[3]
    3: String "hi"
```

**Comment by c42f** [comment]
> I agree it's unfortunate that there's no way of knowing exactly to which line number a certain position inside a string macro translates to.

I guess we could tweak the parser to fix this (a separate PR). The idea would be to tweak the `LineNumberNode` attached to custom string macros so that it always corresponds to the line of the first character which is passed to the string macro, rather than the line of the string macro's name.

**Review by c42f — APPROVED** [review]

**Comment by simeonschaub** [comment]
> I guess we could tweak the parser to fix this (a separate PR). The idea would be to tweak the LineNumberNode attached to custom string macros so that it always corresponds to the line of the first character which is passed to the string macro, rather than the line of the string macro's name.

I think that's a great idea! I'll look into that.

**Comment by fredrikekre** [comment]
Nice!

> I'm curious about the use case for this.

Here is one example, [JuliaDocs/Documenter.jl#1634](https://github.com/JuliaDocs/Documenter.jl/pull/1634), where we currently update all line numbers with an offset after parsing the expression.

**Pull request merged**
