### PR TITLE
implement faster issubset for CartesianIndices{N}

### LINKED ISSUE #41598: Specialised `issubset` for `CartesianIndices`
It seems like there is currently no specialised implementation of `issubset` for `CartesianIndices`, while there is one for `AbstractUnitRange`. This means that what could be a constant-time task (check if lower/upper bounds of potential subset are greater/less than lower/upper bounds of potential superset) instead checks every value individually and even allocates.

I think something like this could solve this issue quite easily:
```julia
function issubset(l::CartesianIndices{N, <: NTuple{N, AbstractUnitRange{Int}}}, r::CartesianIndices{N, <: NTuple{N, AbstractUnitRange{Int}}}) where N
    all(issubset.(l.indices, r.indices))
end
```

### PR DESCRIPTION
**Pull request by xili-h**

### CODE REVIEW

**Comment by Seelengrab** [comment]
Do you have some benchmarks showing a performance improvement?

**Comment by xili-h** [comment]
> Do you have some benchmarks showing a performance improvement?

image

**Comment by xili-h** [comment]
For 1D, it is also faster. 
image
image

**Comment by LilithHafner** [comment]
Thanks for looking into this, @xili-h! This is a good specialization to have.

This clearly has higher performance than the generic fallback, especially because the indices themselves have O(1) subset checking.

However, there's a correctness problem: if the first argument is empty, then it is always a subset, even if some of its indices are not subsets because there are no elements to witness that axis being larger:

```julia-repl
julia> a = CartesianIndices((0, 1))
CartesianIndices((0, 1))

julia> b = CartesianIndices((1,0))
CartesianIndices((1, 0))

julia> issubset(a, b)
true

julia> _issubset(a::CartesianIndices{N}, b::CartesianIndices{N}) where N =
           all(map(issubset, a.indices, b.indices))
_issubset (generic function with 2 methods)

julia> _issubset(a,b)
false

julia> _issubset2(a::CartesianIndices{N}, b::CartesianIndices{N}) where N =
           isempty(a) || all(map(issubset, a.indices, b.indices))
_issubset2 (generic function with 1 method)

julia> _issubset2(a,b)
true
```

As an aside, I prefer if you paste results as text rather than screenshots because that makes it easier for folks to copy your code and reproduce it locally.

**Comment by xili-h** [comment]
> Thanks for looking into this, @xili-h! This is a good specialization to have.
> 
> This clearly has higher performance than the generic fallback, especially because the indices themselves have O(1) subset checking.
> 
> However, there's a correctness problem: if the first argument is empty, then it is always a subset, even if some of its indices are not subsets because there are no elements to witness that axis being larger:
> 
> ```julia-console
> julia> a = CartesianIndices((0, 1))
> CartesianIndices((0, 1))
> 
> julia> b = CartesianIndices((1,0))
> CartesianIndices((1, 0))
> 
> julia> issubset(a, b)
> true
> 
> julia> _issubset(a::CartesianIndices{N}, b::CartesianIndices{N}) where N =
>            all(map(issubset, a.indices, b.indices))
> _issubset (generic function with 2 methods)
> 
> julia> _issubset(a,b)
> false
> 
> julia> _issubset2(a::CartesianIndices{N}, b::CartesianIndices{N}) where N =
>            isempty(a) || all(map(issubset, a.indices, b.indices))
> _issubset2 (generic function with 1 method)
> 
> julia> _issubset2(a,b)
> true
> ```
> 
> As an aside, I prefer if you paste results as text rather than screenshots because that makes it easier for folks to copy your code and reproduce it locally.

Thank @LilithHafner. I have fix the problem base on your suggestion. I will paste results as text next time.

**Comment by LilithHafner** [comment]
Thanks!

**Pull request merged**
