### PR TITLE
Add more documentation to sleep

### PR DESCRIPTION
**Pull request by johnmyleswhite**
Document sub-millisecond alternatives and pros/cons of both options

### CODE REVIEW

**Comment by ufechner7** [comment]
You write: "On some Linux systems, it is possible to sleep at
sub-millisecond resolution using `Libc.systemsleep`"
This is way too pessimistic.
On Windows you can achieve a resolution of 0.001 ms and on Linux (all modern Linux systems, not some) a resolution o
1 to 10 ns.

**Comment by johnmyleswhite** [comment]
I would like to see some references before strengthening the claims here. We can add them into the documentation itself.

**Review by LilithHafner — COMMENTED** [review]
I, too, am skeptical of @ufechner7's claims of 1-10 ns. It's certainly possible to merge this with weak claims now and strengthen the claims later.

The shortest delay used by testing right now is 4ms, and there is no verification of actual time slept. If we can get high resolution systemsleep tests to pass on all tier 1 systems then I would be happy to advertise high resolution in the docstring.

**Comment by vtjnash** [comment]
This isn't quite true as written, as the minimum timeout possible (for systemsleep) on Windows really is 1ms. (actually, Windows may have broken that lately so it is quite a bit worse now there https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/)

**Pull request closed without merging**
