### PR TITLE
lpad, rpad: use character cound instead of textwidth [fix #25016]

### LINKED ISSUE #25016: lpad, rpad use textwidth/char count incoherently
Here's a slightly cleaned up version of `lpad`:
```jl
function lpad(s::AbstractString, n::Integer, p::AbstractString=" ")
    m = n - textwidth(s)
    m ≤ 0 && return s
    l = textwidth(p)
    q, r = divrem(m, l)
    string(p^q, first(p, r), s)
end
```
The quotient and remainder are computed in terms of `textwidth`, while the remainder is then used to select a number of characters, not a width of text. We should either revert the change I made in https://github.com/JuliaLang/julia/commit/8be4acc0190ead6b512253460f3e6b17f1e3d796, or compute the number of characters for fractional padding by taking as many leading characters as fit into the allowed text width.

### PR DESCRIPTION
**Pull request by StefanKarpinski**
The general principle here is that we should avoid having behavior in Base that depends on which version of Unicode you're using. It's fine for an external package to provide versions of lpad and rpad which use textwidth and thereby depend on Unicode details, but the functions in Base should not depend on these.

There still a number of places in Base where there are uses of `Unicode.whatever` but they are uses that seem pretty unlikely to change in future Unicode versions, e.g. `Unicode.isascii` (obviously not going to change), `Unicode.isspace` (unlikely to change), and `Unicode.isnumeric` (might change, but not super likely). `Unicode.textwidth` on the other hand, is actually not fully specified in the Unicode standard and is very likely to change in the future; hence this change.

### CODE REVIEW

**Comment by TotalVerb** [comment]
Aren't these functions used in practice to format things for display in the terminal? It seems really weird to not use the proper text width.

**Comment by StefanKarpinski** [comment]
Depends: we've had complaints in the opposite direction as well. As I pointed out in the issue this closes, we already weren't handling the textwidth case correctly. To handle this fully correctly, you probably need to consider graphemes and not just code points.

**Comment by nalimilan** [comment]
In practice people are likely to use this with width-1 characters, but if we're unsure we could move the function to `Unicode`.

**Comment by StefanKarpinski** [comment]
I think that would be the other alternative: move this to `Unicode`. I do think that in practice it doesn't matter much since it's generally used with very simple padding strings.

**Comment by StefanKarpinski** [comment]
@vtjnash's argument here is: textwidth is just a bad, generally broken way to do this, and number of code points is often better in practice. If you *really* want to get this right, there are better ways to do it. Note that `textwidth` is *not* standardized in any way and is bound to be wrong. Terminal UI packages are the right place to detect your terminal and use the right text widths for it.

**Pull request merged**
