### PR TITLE
fix and add doctest for eigs and svds

### PR DESCRIPTION
**Pull request by fredrikekre**
- add doctests for eigs and svds
- fix a note-block
- include an `Example` headline which I missed in https://github.com/JuliaLang/julia/pull/20338

### CODE REVIEW

**Review by kshyatt — APPROVED** [review]
We've had problems before with doctests where the nearly-zero floating point numbers changed from run to run. Is there any way to fix that here? Is it likely to be a problem?

**Comment by fredrikekre** [comment]
> We've had problems before with doctests where the nearly-zero floating point numbers changed from run to run. Is there any way to fix that here? Is it likely to be a problem?

Perhaps we should only show the eigenvalues then?

**Comment by KristofferC** [comment]
Or "convert" the small values to zero

**Comment by fredrikekre** [comment]
They are not even the same from run to run (not just the small values, but the sign of the eigenvectors differ as well).
I will update and just show the eigenvalues :)

```julia
julia> A = speye(4, 4); B = spdiagm(1:4);

julia> λ, ϕ = eigs(A, B, nev = 2); ϕ
4×2 Array{Float64,2}:
 -1.0           0.0        
 -7.66227e-17   0.707107   
  5.55112e-17  -5.55112e-17
 -2.77556e-17  -6.93889e-17

julia> λ, ϕ = eigs(A, B, nev = 2); ϕ
4×2 Array{Float64,2}:
 -1.0           0.0        
 -9.59662e-17  -0.707107   
  6.93889e-18   1.38778e-17
  0.0          -5.55112e-17

julia> λ, ϕ = eigs(A, B, nev = 2); ϕ
4×2 Array{Float64,2}:
  1.0           0.0        
 -7.57843e-18   0.707107   
 -4.16334e-17   1.38778e-16
  0.0          -2.22045e-16
```

**Comment by kshyatt** [comment]
Awesome, thanks for fixing this @fredrikekre.

**Comment by fredrikekre** [comment]
I was sure this doctest actually passed though.

**Comment by fredrikekre** [comment]
Hmmm they did pass... Turns out you get the same result (even the small values) the first time you run the example:

```julia
julia> A = speye(4, 4); B = spdiagm(1:4);

julia> λ, ϕ = eigs(A, B, nev = 2); ϕ
4×2 Array{Float64,2}:
 -1.0          -5.55112e-17
  7.43262e-17  -0.707107   
  0.0           5.55112e-17
  0.0           0.0        

julia> # restart the session

julia> A = speye(4, 4); B = spdiagm(1:4);

julia> λ, ϕ = eigs(A, B, nev = 2); ϕ
4×2 Array{Float64,2}:
 -1.0          -5.55112e-17
  7.43262e-17  -0.707107   
  0.0           5.55112e-17
  0.0           0.0
```

**Comment by andreasnoack** [comment]
The initial vector is random but the state is probably the same every time the tests are run. To make it deterministic, you could do `eigs(A, v0 = ones(size(A, 1)))` but it might be a bit misleading because most often it shouldn't be necessary to set the initial vector.

**Comment by fredrikekre** [comment]
I opted to just show the eigenvalues in the example, I think that might serve the purpose good enough?

**Pull request merged**
