### PR TITLE
Change output of dump(T)

### LINKED ISSUE #24812: dump(T) should not print a subtype tree
> dump [v]: Show every part of the representation of a value.

```jl
julia> dump(AbstractString)
AbstractString
  RevString{T<:AbstractString}
  Base.String = String
  SubString{T<:AbstractString}
  Base.SubstitutionString{T<:AbstractString}
  String
```

Printing a tree of all the subtypes of a type is not what it says on the tin. Dump should not do this – there should be a dedicated function that does this instead, such as the one proposed in #24741. Triaging just for getting rid of the current printing behavior. Adding the dedicated function can be done any time.

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #24812

This commit removes the specialized function for DataType. The following is the behavior after this patch

```julia
./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.3187 (2017-12-26 16:45 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1a6e34bb1b* (0 days old master)
|__/                   |  x86_64-apple-darwin17.3.0

julia> dump(AbstractString)
AbstractString <: Any

julia> dump(Number)
Number <: Any

julia> dump(Int64)
Int64 <: Signed

julia> struct MyStruct
                  x
                  y
              end

julia> dump(MyStruct)
MyStruct <: Any
  x::Any
  y::Any

julia> struct MyTypedStruct
                  x::String
                  y::Int
              end

julia> dump(MyTypedStruct)
MyTypedStruct <: Any
  x::String
  y::Int64

julia> dump(MyTypedStruct("Hello", 1))
MyTypedStruct
  x: String "Hello"
  y: Int64 1
```

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
Well, that was easier than I thought :)

**Review by StefanKarpinski — CHANGES_REQUESTED** [review]
Seems to fail a bunch of show tests, however.

**Comment by kdheepak** [comment]
@StefanKarpinski I made the requested changes to [test/show.jl](https://github.com/JuliaLang/julia/pull/25275/commits/c1ac3f7b6befb94ad303c07a19e5d194aaae4891). I also ran `make test` locally to confirm that the changes don't break any tests.

```
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
Base64 (3)                |    3.54  |  0.05  |  1.4 | 95.67      | 172.19
CRC32c (4)                |    4.43  |  0.14  |  3.2 | 110.85     | 182.73
...
show (7)                  |   62.05  |  1.26  |  2.0 | 908.29     | 765.73
...
Test Summary: |     Pass  Broken     Total
  Overall     | 26598954  328326  26927280
    SUCCESS
```

Funnily, now the Travis builds seems to be not working. I guess someone would have to restart the [build on Travis](https://travis-ci.org/JuliaLang/julia/builds/322103024). It seems to be building fine on the other CI services.

**Comment by kdheepak** [comment]
The tests pass everywhere except Travis. Can someone restart the builds on Travis? Alternatively, I can also rebase onto latest master and trigger all builds, if that is preferred.

**Comment by StefanKarpinski** [comment]
Travis seems to be having trouble installing anything on Linux; those tests are redundant with Circle CI, anyway, so this is good to go. Thanks for tackling this!

**Comment by Sacha0** [comment]
Much thanks and welcome @kdheepak! :)

**Comment by kdheepak** [comment]
Awesome! And thanks :)

**Pull request merged**
