### PR TITLE
I love # Example

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]
LGTM

**Comment by fredrikekre** [comment]
Just a thought: I wonder if we should use "##" instead, since "Example" is a subheading to the function signature (which seems to render like "#")? Take a look at e.g. https://docs.julialang.org/en/latest/stdlib/linalg/#Base.LinAlg.dot

**Comment by KristofferC** [comment]
The function signature have a bit of backdrop though. The whole block is also surrounded with the square. In my opinion it looks ok but I don't know how the `##` alternative would look.

**Comment by fredrikekre** [comment]
There is also the rendering in the REPL to consider. Here is *my* REPL<sup>[since there are many like it<sup>but this one is mine</sup>](https://github.com/KristofferC/OhMyREPL_JuliaCon2017)</sup> and rendered documentation with 1-4 #'s (turns out my suggestion wont matter for the rendered docs anyway, sorry for getting off topic from the PR):
screen shot 2017-06-25 at 05 08 04
screen shot 2017-06-25 at 05 13 21

Personally, I think that in the REPL the function signature (which essentially is the header of the docstring) is way too anonymous compared to the "Example" header.

**Comment by tkelman** [comment]
We should standardize on whether or not there's a blank line before the ` ``` ` (I'd prefer not), and write these conventions down in the docs and/contributing guidelines

**Pull request merged**
