### PR TITLE
RFC: deprecate RopeString

### PR DESCRIPTION
**Pull request by JeffBezanson**
While `RevString` and `RepString` see a small amount of use in Base, `RopeString` doesn't seem to be used at all. I think we should deprecate it in 0.4, then maybe move it to examples.

### CODE REVIEW

**Comment by ArchRobison** [comment]
Deprecating it seems reasonable to me.  Ropes have always seemed like a cool idea, but I've never used them in real code.  I suspect that cache effects on modern architectures make them less interesting than they once were.

**Comment by ScottPJones** [comment]
:clap: :+1:

**Comment by StefanKarpinski** [comment]
+1, although it's interesting that this was concurrent with suggesting a potential [`ConcatString` type](https://github.com/JuliaLang/julia/pull/11686#issuecomment-125280220).

**Comment by JeffBezanson** [comment]
I didn't exactly "suggest" a ConcatString type; in fact I described it as "not appealing".

**Comment by StefanKarpinski** [comment]
Right, "brought up" then.

**Comment by ivarne** [comment]
I understand the desire to move quickly, but as this doesn't fix anything urgent, I'd appreciate at least 24 hours between opening the PR and merging. That would give our global community a (theoretical) chance to raise reasonable objections.

PS: I'll retract my comment if the 0.4 feature freeze is imminent, so that this really would have slowed things down if it had waited longer. It seems like a pretty safe change.

**Comment by ScottPJones** [comment]
I actually had this in a previous PR, but Tony wouldn't let me do it :grinning:

**Comment by tkelman** [comment]
Deprecation is fine, your previous PR flat-out deleted it from what I remember.

**Comment by ScottPJones** [comment]
Yes, and I would have moved it to a Package as you'd suggested, but just put it back in.

**Pull request merged**
