### PR TITLE
Add Dates as a test dependency to SparseArrays.

### PR DESCRIPTION
**Pull request by fredrikekre**
Add Dates as a test dependency to SparseArrays, missed in #30228.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by ViralBShah** [comment]
Do we need this on 1.0 also?

**Comment by fredrikekre** [comment]
Not unless #30228 is also backported.

**Comment by ViralBShah** [comment]
I think we should backport it.

**Comment by ararslan** [comment]
That can't be backport to 1.0, as it's labeled a minor change.

**Comment by ararslan** [comment]
It's also already been backported to 1.1.0

**Pull request merged**
