### PR TITLE
put Logging back in default sysimage

### LINKED ISSUE #51493: Fallback Logger used during startup.jl
I guess removing REPL from the sysimage has caused the logger that's loaded during startup.jl to appear to be the fallback logger.
Note no color and the source line under info, which usually doesn't show.

Screenshot 2023-09-28 at 12 10 45 PM

### LINKED ISSUE #52075: ConsoleLogger not active in the REPL
`Logging.__init__` replaces the global logger: https://github.com/JuliaLang/julia/blob/1327dfec807fa00782311f02d095b8e37ea55f2a/stdlib/Logging/src/Logging.jl#L93-L95 Before  #51399 this was more or less impossible to notice since `Logging.__init__` was run when loading the sysimg. However, now this isn't the case anymore. This means that
1. The colorless `SimpleLogger` is used by default in the REPL
2. `using Logging` replaces the logger, which might be a logger a user has already configured

```
julia> @info "Where are my colors?" logtype = typeof(Base.global_logger())
┌ Info: Where are my colors?
│   logtype = Base.CoreLogging.SimpleLogger
└ @ Main REPL[1]:1

julia> using Logging

julia> @info "Thanks for the colors, but you stole my logger..." logtype = typeof(Base.global_logger())
┌ Info: Thanks for the colors, but you stole my logger...
└   logtype = ConsoleLogger
```
image

Not sure what the best fix is, but probably `REPL` should depend on `Logging` and setup the logger while the REPL initializes.

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #51493, fixes #52075

### CODE REVIEW

**Comment by KristofferC** [comment]
And now StyledStrings are in there as well. That feels like something people will really start relying on. @tecosaur, wasn't the plan to move the styled string rendering code into Base (which would allow Consologger to also be moved into Base. Alternatively the use of StyledStrings in logging could be reverted.

**Comment by JeffBezanson** [comment]
Yes, one option is to move ConsoleLogger to base and merge it with SimpleLogger. Then it would be nice if it can avoid using StyledStrings, but I'm not sure that's possible without sacrificing functionality people want.

**Comment by IanButterworth** [comment]
Could we add a class of excised stdlibs that are pkgimages that are loaded immediately after the sysimage, before startup.jl, but after the active project is set, and there could be a flag to disable it. 
That way they can still be upgradable and avoidable if people want.

**Comment by tecosaur** [comment]
> @tecosaur, wasn't the plan to move the styled string rendering code into Base

The (inconclusive) discussion on Triage partially recorded in Slack is this: https://julialang.slack.com/archives/C67TUQBG9/p1708007625965089

For posterity, I'll copy over the first (and most relevant) message here before it gets eaten by the slack-hole:

> 1. We always load StyledStrings (in it's current form) as part of startup, unless you specifically build a sysimage/executable where you've opted-out. We keep the `print(::IO, ::AnnotatedString)` / `show(::IO, MIME"text/plain", ::AnnotatedString)` methods defined in StyledStrings (similar to LinearAlgebra).
1.1: We can introduce a class of stdlibs that are loaded immediately after the stdlibs (e.g. Logging, LinearAlgebra?)
1.2: These stdlibs can be baked into the distributed sysimage (but we now have upgradible stdlibs!)
> 2. We move the core "how to print an AnnotatedString with the styling info as ANSI escape sequences" functionality into Base, the StyledStrings stdlib contains "the other stuff" (load user customisations, convenience functions).

I don't really have a horse in this race, so long as we don't go down the "let's not use StyledStrings for stuff in Base/not-REPL stdlibs" path, since I have yet more hopes for using it to enhance other aspects like error messages (if it's somehow possible, I'd love to be able to use `JuliaSyntaxHighlighting` with some error messages/stacktraces, see also https://julialang.slack.com/archives/C67TUQBG9/p1709307800994979).

**Comment by JeffBezanson** [comment]
I'm fine with any of that, but I want to avoid doing significant development work / adding features in order to fix a regression. For 1.11, it looks to me like we need to put Logging back where it was and re-try moving it out when we have everything sorted to make that possible.

**Comment by IanButterworth** [comment]
Is this mergeable or does the StyledStrings consideration require changes?

**Comment by LilithHafner** [comment]
Adding to milestone to avoid logging UI regression.

**Comment by JeffBezanson** [comment]
`StyledStrings.__init__` relies on DEPOT_PATH being non-empty, but we have an explicit test for that case. Should the init code just check for that and do nothing?

**Comment by KristofferC** [comment]
There's been talk for months now about how the rendering of StyledStrings has to be moved into Base if it wants to style things in Base and the same applies here since the default logging of Base should be "nice" but nothing happens. So I will just revert the StyledString usage in Logging, move ConsoleLogger.jl into Base so this is finally dealt with.

**Comment by tecosaur** [comment]
> StyledStrings.__init__ relies on DEPOT_PATH being non-empty...

Thanks to Kristoffer, this is now tracked as https://github.com/JuliaLang/StyledStrings.jl/issues/58

> There's been talk for months now about how the rendering of StyledStrings has to be moved into Base if it wants to style things in Base and the same applies here since the default logging of Base should be "nice" but nothing happens

This is an interpretation of events that differs from mine, as I'm still under the impression that there were [~3 options put forward to consider](https://github.com/JuliaLang/julia/pull/53660#issuecomment-1986718062), and I don't have strong opinions on them and so have been waiting for one to be picked.

I'm not too fussed, but if/when the new `HelpfulErrors` stdlib mentioned briefly in the second last triage call gets off the ground, that will be a repeat of the `Logging` situation, except with "just revert the use of AnnotatedStrings for styling" being less straightforward.

For a bit more context (as I recall, at least), Triage suggested that in this case that it could potentially have StyledStrings as a dep, and be loaded in interactive sessions and possibly by the compiler for nicer error messages.

**Comment by KristofferC** [comment]
> I'm not too fussed, but if/when the new HelpfulErrors stdlib mentioned

>  Triage suggested that in this case that it could potentially have StyledStrings as a dep, and be loaded in interactive sessions and possibly by the compiler for nicer error messages.

This would not be an stdlib. It would just be something that Base can do. And that would require the same as here, being able to render styled strings from Base.

**Comment by tecosaur** [comment]
> What I am saying is exactly point 2 there?

I may just be misinterpreting — I read your comment as saying that's the only way forward.

> This would not be an stdlib. It would just be something that Base can do.

My "a potential new stdlib" comment is from when I popped into a recent triage meeting and basically asked "here's some functionality I think could be worth sorting on, what do you think and where should it go?" and the preliminary answer I got was "make it a new stdlib".

**Comment by KristofferC** [comment]
> I read your comment as saying that's the only way forward.

Yes, the other ones don't make sense. 


> the preliminary answer I got was "make it a new stdlib".

Well, that's just wrong... Error messages is a Base feature, it doesn't make sense for a "HelpfulErrors" stdlib. Either it would be a normal Base feature if it is stable and "good" enough, or it would be a separate package.

**Comment by KristofferC** [comment]
ConsoleLogging got put into Base.

**Comment by LilithHafner** [comment]
I concur with traige's position that HelpfulErrorMessages should be a stdlib, not in Base. Exceptions and try/catch should be a part of Base, basic error messages should also imo be a part of base, but fancy helpful errors that try to provide insightful advice need not be. They can and imo should pirate base methods or hook into error hint API for this. HelpfulErrorMessages should be loaded by default in the REPL and when invoking julia from the command line.

**Comment by KristofferC** [comment]
> try/catch should be a part of Base,

What? 

> They can and imo should pirate base methods
 
This would be terrible for latency. 

> hook into error hint API for this. 

Yes, the existing error hint API sits there ready for contributions.

**Comment by tecosaur** [comment]
Should we move this tangent into a dedicated issue/elsewhere?

Anyway, my takeaway was that `Base` itself could just define and throw specialised error types, with nice `showerror` methods in `HelpfulErrors`. This is technically type piracy, but it's invalidations that cause latency, not piracy, no?

**Pull request closed without merging**
