### PR TITLE
updated fix for #19892 (FFTW threads initialization)

### LINKED ISSUE #21163: After merging #21127, planning a FFT takes much longer
After merging #21127, there is a large performance regression when planning a FFT, this is particularly evident with the slow `FFTW.MEASURE` flag.

On commit https://github.com/JuliaLang/julia/commit/d6945480ce3ce8a7c4b57a0b1e2cb121c43ccb27 (parent of the merge commit):
```julia
julia> FFTW.set_num_threads(4)

julia> v = Vector{Complex{Float64}}(nextpow2(100000));

julia> @time plan_fft(v, flags = FFTW.MEASURE);
  3.354884 seconds (334.41 k allocations: 17.760 MiB, 0.19% gc time)

julia> v = Vector{Complex{Float64}}(nextpow2(400000));

julia> @time plan_fft(v, flags = FFTW.MEASURE);
  2.556090 seconds (334.40 k allocations: 23.737 MiB, 0.23% gc time)
```

On commit https://github.com/JuliaLang/julia/commit/0b8c5ed626da3987ac6063c5b9f7a654decfb559 (merge commit of #21127):
```julia
julia> FFTW.set_num_threads(4)

julia> v = Vector{Complex{Float64}}(nextpow2(100000));

julia> @time plan_fft(v, flags = FFTW.MEASURE);
 38.807557 seconds (334.40 k allocations: 17.735 MiB, 0.02% gc time)

julia> v = Vector{Complex{Float64}}(nextpow2(400000));

julia> @time plan_fft(v, flags = FFTW.MEASURE);
210.785749 seconds (380 allocations: 8.021 MiB, 0.01% gc time)
```

### PR DESCRIPTION
**Pull request by stevengj**
initialize FFTW threads the first time the planner is called (I tried to be clever in #21127, but it incorrectly prevented threads from being used at all).  Fixes #21163

### CODE REVIEW

**Comment by tkelman** [comment]
are there any simple benchmarks that could be added that would have caught this?

**Comment by giordano** [comment]
@tkelman I'm not sure.  I spotted the problem by performing benchmarks of a package of mines, but the regression was easily noticeable only in the first run (compilation) of `plan_fft`: the whole benchmark was taking way too much to run, but the times measured by `@benchmark` weren't that bad.

**Comment by stevengj** [comment]
We could check for the use of threads by:
```jl
julia> FFTW.set_num_threads(2)

julia> contains(string(plan_fft(Array{Complex128}(1<<14), flags = FFTW.ESTIMATE)), "dft-thr")
true
```

**Comment by stevengj** [comment]
Pushed a test.

**Comment by giordano** [comment]
Is it normal that the plan changes with this patch?

On https://github.com/JuliaLang/julia/commit/d6945480ce3ce8a7c4b57a0b1e2cb121c43ccb27:
```julia
julia> plan_rfft(randn(10^5,1), flags = FFTW.MEASURE)
FFTW real-to-complex plan for 100000×1 array of Float64
(rdft2-ct-dit/16
  (hc2c-direct-16/60/0 "hc2cfdftv_16_avx"
    (rdft2-r2hc-direct-16 "r2cf_16")
    (rdft2-r2hc01-direct-16 "r2cfII_16"))
  (dft-thr-vrank>=1-x4/1
    (dft-vrank>=1-x2/1
      (dft-ct-dit/25
        (dftw-direct-25/96 "t1fv_25_avx")
        (dft-vrank>=1-x25/1
          (dft-ct-dit/25
            (dftw-direct-25/192 "t2fv_25_avx")
            (dft-direct-10-x25 "n1fv_10_avx")))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/25
        (dftw-direct-25/96 "t1fv_25_avx")
        (dft-vrank>=1-x25/1
          (dft-ct-dit/25
            (dftw-direct-25/192 "t2fv_25_avx")
            (dft-direct-10-x25 "n1fv_10_avx")))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/25
        (dftw-direct-25/96 "t1fv_25_avx")
        (dft-vrank>=1-x25/1
          (dft-ct-dit/25
            (dftw-direct-25/192 "t2fv_25_avx")
            (dft-direct-10-x25 "n1fv_10_avx")))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/25
        (dftw-direct-25/96 "t1fv_25_avx")
        (dft-vrank>=1-x25/1
          (dft-ct-dit/25
            (dftw-direct-25/192 "t2fv_25_avx")
            (dft-direct-10-x25 "n1fv_10_avx")))))))
```

On https://github.com/stevengj/julia/tree/fftwfix2
```julia
julia> plan_rfft(randn(10^5,1), flags = FFTW.MEASURE)
FFTW real-to-complex plan for 100000×1 array of Float64
(rdft2-ct-dit/16
  (hc2c-direct-16/60/0 "hc2cfdftv_16_avx"
    (rdft2-r2hc-direct-16 "r2cf_16")
    (rdft2-r2hc01-direct-16 "r2cfII_16"))
  (dft-thr-vrank>=1-x4/1
    (dft-vrank>=1-x2/1
      (dft-ct-dit/5
        (dftw-direct-5/16 "t1fv_5_avx")
        (dft-vrank>=1-x5/1
          (dft-ct-dit/5
            (dftw-direct-5/8 "t3fv_5_avx")
            (dft-vrank>=1-x5/1
              (dft-ct-dit/25
                (dftw-direct-25/96 "t1fv_25_avx")
                (dft-direct-10-x25 "n1fv_10_avx")))))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/5
        (dftw-direct-5/16 "t1fv_5_avx")
        (dft-vrank>=1-x5/1
          (dft-ct-dit/5
            (dftw-direct-5/8 "t3fv_5_avx")
            (dft-vrank>=1-x5/1
              (dft-ct-dit/25
                (dftw-direct-25/96 "t1fv_25_avx")
                (dft-direct-10-x25 "n1fv_10_avx")))))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/5
        (dftw-direct-5/16 "t1fv_5_avx")
        (dft-vrank>=1-x5/1
          (dft-ct-dit/5
            (dftw-direct-5/8 "t3fv_5_avx")
            (dft-vrank>=1-x5/1
              (dft-ct-dit/25
                (dftw-direct-25/96 "t1fv_25_avx")
                (dft-direct-10-x25 "n1fv_10_avx")))))))
    (dft-vrank>=1-x2/1
      (dft-ct-dit/5
        (dftw-direct-5/16 "t1fv_5_avx")
        (dft-vrank>=1-x5/1
          (dft-ct-dit/5
            (dftw-direct-5/8 "t3fv_5_avx")
            (dft-vrank>=1-x5/1
              (dft-ct-dit/25
                (dftw-direct-25/96 "t1fv_25_avx")
                (dft-direct-10-x25 "n1fv_10_avx")))))))))
```

**Comment by stevengj** [comment]
@giordano, the `MEASURE` plan creation is non-deterministic (it depends on runtime measurements), and it is normal for it to vary from run to run because there are many possible algorithms with similar performance.

**Comment by JeffBezanson** [comment]
Ready to merge?

**Comment by nalimilan** [comment]
@stevengj Any idea why the new test would fail with FFTW 3.3.3 (CentOS 7)? Is that expected?

**Comment by stevengj** [comment]
@nalimilan, yes, `fftw_sprint_plan` wasn't available in FFTW 3.3.3.  (For bureaucratic reasons, FFTW doesn't follow semver.)  Hence `show` of a plan in FFTW 3.3.3 [doesn't actually show the plan contents](https://github.com/JuliaLang/julia/blob/ceb06740e307a8b2d43f3480efaa33311a90f021/base/fft/FFTW.jl#L306) and the test will fail..

So, the test should only run if `FFTW.version ≥ v"3.3.4"`.

**Pull request merged**
