### PR TITLE
Update noteworthy-differences.md

### PR DESCRIPTION
**Pull request by jerzybrzoska**
On the lack of optional prompt in Julia's readline(), when compared with Python's input().

### CODE REVIEW

**Comment by ViralBShah** [comment]
I personally would not consider this high up enough to make it to noteworthy differences. The list is not meant to be comprehensive, but will let others chime in.

**Comment by StefanKarpinski** [comment]
Agree. This seems very in the weeds and unlikely to help most people coming from Python.

**Comment by ericphanson** [comment]
There is also `Base.prompt` (which has a docstring but does not seem to be in the manual).

**Comment by ViralBShah** [comment]
@jerzybrzoska Sorry - not the best welcome as a new contributor, but sometimes many of us who are here tend to write short comments to be efficient with time. Thanks for opening the PR - it is often a first step to more contributions!

**Comment by StefanKarpinski** [comment]
Yes, sorry if my comment seems brusque. Proposed improvements are always appreciated, even if not merged.

**Comment by jerzybrzoska** [comment]
> Yes, sorry if my comment seems brusque. Proposed improvements are always appreciated, even if not merged.

It is not brusque. All is well.  I am aware that, when learning a langauge, I tend to pay more attention than other coders to taking input and managing output. It's just my way of doing things.

**Pull request closed without merging**
