### PR TITLE
make RTLD_LOCAL the default for dlopen on both Mac and Linux 

### LINKED ISSUE #11322: dlopen RTLD_LOCAL default not respected on OSX
the documentation and code state that dlopen in julia defaults to RTLD_LOCAL, but on mac, it seems that the defaults is RTLD_GLOBAL per https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html

implemented by @stevengj in 27fab368 and noted while doing code review on #11307

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #11322.

### CODE REVIEW

**Comment by vtjnash** [comment]
this has an unexpected repercussion when used on libraries linked with `ld -flat_namespace`:
```
julia> Libdl.dlopen("/opt/local/lib/libglib-2.0")
Ptr{Void} @0x00007f8f85140e00

julia> Libdl.dlopen("/opt/local/lib/libpango-1.0")
dlerror loading '/opt/local/lib/libpango-1.0': dlopen(/opt/local/lib/libpango-1.0.dylib, 5): Symbol not found: _g_ascii_table
  Referenced from: /opt/local/lib/libpango-1.0.dylib
  Expected in: flat namespace
 in /opt/local/lib/libpango-1.0.dylib
ERROR: could not load library /opt/local/lib/libpango-1.0
 in dlopen at libdl.jl:35
```

but it works fine with homebrew (note the TWOLEVEL attribute):
```
/opt/brew/lib/libgtk-3.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    39       3264   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
~/Documents/no-backup/julia$ otool -hv /opt/local/lib/libgtk-3.dylib 
/opt/local/lib/libgtk-3.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    31       3840 DYLDLINK NO_REEXPORTED_DYLIBS
````

i'm not sure why there is a difference, but it seems the problem flag (`-Wl,-flat_namespace`) can get added by autoconf.

also, fwiw, it apparently can even break an individual library on its own:
```
julia> Libdl.dlopen("/opt/local/lib/libgtk-3")
Ptr{Void} @0x00007ff02c05f6d0

julia> using Gtk
dyld: lazy symbol binding failed: Symbol not found: _gtk_widget_get_type
  Referenced from: /opt/local/lib/libgtk-3.dylib
  Expected in: flat namespace

dyld: Symbol not found: _gtk_widget_get_type
  Referenced from: /opt/local/lib/libgtk-3.dylib
  Expected in: flat namespace

Trace/BPT trap: 5
~/Documents/no-backup/julia$ nm /opt/local/lib/libgtk-3.dylib | grep _gtk_widget_get_type
000000000027d600 T _gtk_widget_get_type
000000000055d210 s _gtk_widget_get_type.accessibility_info
000000000055d228 s _gtk_widget_get_type.buildable_info
000000000055d1c8 s _gtk_widget_get_type.widget_info
0000000000562ff0 b _gtk_widget_get_type.widget_type
```

**Comment by stevengj** [comment]
Should we try `RTLD_GLOBAL` if `RTLD_LOCAL` fails and the default was requested?

**Comment by vtjnash** [comment]
it may not have been particularly clear from that example, but loading one library (in this case `libglib-2.0`) with `RTLD_LOCAL` permanently broke any library that was depending on that library with the `-flat_namespace` flag (in this case `libpango-1.0`). even attempting to later load those libraries with `RTLD_GLOBAL` didn't help fix it.

i think we should just go back to the previous/default behavior, and fix the documentation to note that we follow the platform defaults.

**Comment by stevengj** [comment]
Okay; feel free to revert this commit.

**Pull request merged**
