### PR TITLE
Enable fixup-libgfortran on Linux

### PR DESCRIPTION
**Pull request by staticfloat**
See https://github.com/JuliaLang/julia/issues/8397 for more detail.

@crayxt @tkelman Could you try this out and make sure it works for you?

### CODE REVIEW

**Comment by tkelman** [comment]
Crap, this broke packages with compiled Fortran dependencies: ```ERROR: could not load module /home/travis/.julia/v0.4/OptimizationServices/deps/usr/lib/libOS.so: /home/travis/julia/bin/../lib/julia/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/travis/.julia/v0.4/OptimizationServices/deps/usr/lib/libcoinmumps.so.1)```

@staticfloat, are the buildbots using a modern version of gfortran? Bundling libgfortran like this has put us into Matlab-like territory of causing incompatibility between our binaries (which always have the bundled gcc libs dlopen'ed) and any libraries built by system compilers.

**Comment by staticfloat** [comment]
Sigh.  It looks like the devtoolset distributed by CERN doesn't ship dynamic libraries of `libgfortran`, only static ones, so we've been getting the old and busted GCC 4.1 `libgfortran` all this time.  I'm going to try the following to see what the best method is:

I'll spin up a CentOS 6 machine so that I can install `devtoolset-3`, see if that ships a dynamic copy of `libgfortran`, and see if I can frankenpaste it onto my CentOS 5 machines.  If I can, I'll give the library to you and see if it "just works".  Failing that, I'll try just plain building the julia `.tar.gz` on CentOS 6 and see if _that_ works.  If it does, we might have to take a poll of users that use old versions and build our generic binaries on CentOS 6 instead.  Failing that, I'll see if I can figure out how to generate the dynamic `libgfortran.so.3` file from `libgfortran.a`, but I'm not optimistic that this is going to be easy to do by hand.

**Comment by tkelman** [comment]
Thanks for checking.

> so we've been getting the old and busted GCC 4.1 `libgfortran` all this time

Oh, so even more like Matlab then, but not intentionally :-P

> Failing that, I'll see if I can figure out how to generate the dynamic `libgfortran.so.3` file from `libgfortran.a`, but I'm not optimistic that this is going to be easy to do by hand.

That will depend on whether or not it was compiled with `-fPIC`, among other complications. If the devtoolset's static libgfortran was compiled with -fPIC, then maybe we should actually be trying to statically link at least base Julia's dependencies against it. OTOH not supporting CentOS 5 any more is probably a simpler choice.

**Comment by tkelman** [comment]
Bump. @staticfloat any additional info here?

**Comment by staticfloat** [comment]
I have confirmed `devtoolset-3` still does not ship a newer libgfortran, and Scientific Linux 6 only ships with gcc 4.4, which doesn't have `GFORTRAN_1.4` ABIs.

**Comment by tkelman** [comment]
Thanks! But crap, so what do we do about this? Is the devtoolset capable of statically linking libgfortran into a shared library? This requires that it was compiled with `-fPIC`, I'm not sure of an easier way to find out than doing something like this: https://github.com/coin-or/Ipopt/blob/a3c4bd8971a300d2f5213caf9719b339ddb8ebfd/Ipopt/contrib/MatlabInterface/MatlabInterface.site#L63-L94

**Comment by tkelman** [comment]
Or could the devtoolset people be convinced to ship a shared libgfortran? I wonder how often they release new versions... @nalimilan any suggestions?

**Comment by nalimilan** [comment]
I have no idea, except that AFAIK the devtoolset is a repackaged version of the one RedHat releases, and they will likely be very conservative about what they ship given that they offer long-term support to their customers.

**Comment by ViralBShah** [comment]
`-static-libgfortran` and `-static-libgcc` would have been ideal, but that does not do the same for libquadmath (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46539).

**Comment by tkelman** [comment]
Yeah, that flag doesn't work on Linux with GCC > 4.5 due to libquadmath. I don't think any of the libraries we use actually do any quad-precision operations though. So if we explicitly link against the full path of `libgfortran.a` via `gfortran -print-file-name=libgfortran.a`, it can be made to work. It depends on whether the static libgfortran was compiled with -fPIC. If it wasn't, we need to compile our own libgfortran. At that point shipping it vs statically linking it might not make much difference.

**Comment by tkelman** [comment]
Fired up a docker container of CentOS 5 and tried out devtoolset-2 on it. There is a `opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgfortran_nonshared.a` that was compiled with -fPIC, and the `libgfortran.so` that they provide is actually a linker script to link against that in addition to the old lousy system libgfortran shared library. They do something similar for libstdc++, and I'm sure they have their reasons, but unfortunately it's unusable for us. I tried moving `libgfortran_nonshared.a` in place of `libgfortran.a` and adding `-static-libgfortran` to `FC`, which actually works on my tiny test example, but it does not contain `_gfortran_st_write` and several other required functions that would be needed to link openBLAS against it.

**Comment by tkelman** [comment]
I have an idea that might allow us to fix this without needing to build our own GCC. @staticfloat can you try the following on the Centos 5 buildbot?
```
scl enable devtoolset-2 bash
gfortran -shared -Wl,--whole-archive /opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgfortran_nonshared.a -Wl,--no-whole-archive -o libgfortran_nonshared.so
mv libgfortran_nonshared.so /opt/rh/devtoolset-2/root/usr/lib/gcc/x86_64-redhat-linux/4.8.2
```

Then if you rebuild openspecfun, openblas, and arpack, the devtoolset linker script should result in a shared-library dependency on this `libgfortran_nonshared.so`, which we can then copy to `usr/lib` and the `make dist` tarball - probably only in the buildbot code, since this file won't exist for most people.

We'll need to test the resulting tarballs, but I think this might give us the newer libgfortran ABI's.

**Comment by staticfloat** [comment]
Unfortunately, I don't think this works _quiiiiiite_ right:

```
$ nm libgfortran_nonshared.so | grep GFORTRAN
         U _gfortran_cpu_time_10@@GFORTRAN_1.0
         U _gfortran_flush_i4@@GFORTRAN_1.0
         U _gfortran_ftell@@GFORTRAN_1.0
         U _gfortran_os_error@@GFORTRAN_1.0
         U _gfortran_random_r10@@GFORTRAN_1.0
         U _gfortran_runtime_error@@GFORTRAN_1.0
         U _gfortran_size0@@GFORTRAN_1.0
         U _gfortran_stop_numeric@@GFORTRAN_1.0
         U _gfortran_transfer_array@@GFORTRAN_1.0
         U _gfortran_transfer_character@@GFORTRAN_1.0
         U _gfortran_transfer_character_wide@@GFORTRAN_1.1
         U _gfortran_transfer_complex@@GFORTRAN_1.0
         U _gfortran_transfer_integer@@GFORTRAN_1.0
         U _gfortran_transfer_logical@@GFORTRAN_1.0
         U _gfortran_transfer_real@@GFORTRAN_1.0
         U __iso_c_binding_c_f_pointer@@GFORTRAN_1.0
```

So we're still not getting `@@GFORTRAN_1.4` like we want.  Perhaps we can find a non-devtoolset version of gcc/gfortran we can install?  I think the HipHopVM guys have one, I'll have to try it out.  Ironic how we're trying to install the latest and greatest on the oldest and worst.  ;)

**Comment by tkelman** [comment]
I'd be surprised if development tooling for a PHP VM went to extra lengths to include Fortran support...

If we can't find something pre-packaged that will work, GCC isn't all that hard to compile ourselves. Just a bit time consuming.

**Comment by tkelman** [comment]
BUMP! We need to fix this. Like, before our next release. Which should be in about a week.

**Comment by staticfloat** [comment]
I'm currently trying to build GCC manually.  We'll see where this takes us.

**Comment by tkelman** [comment]
Fantastic, thank you. Be sure to specify `--enable-languages=c,c++,fortran` since gfortran is non-default

**Comment by staticfloat** [comment]
Alright, I compiled GCC 4.8 on the buildbots, then built `dist` tarballs using that built GCC.  I'm a _little_ worried that this is going to stop these binaries from working on older machines, but we'll need to see if that is actually the case.  If it is a problem, is shipping `libstdc++.so` and friends alongside Julia too much?  I don't know.

[32-bit](https://julianightlies.s3.amazonaws.com/bin/linux/x86/tmp/julia-820aabeec6-Linux-i686.tar.gz)
[64-bit](https://julianightlies.s3.amazonaws.com/bin/linux/x64/tmp/julia-820aabeec6-Linux-x86_64.tar.gz)

**Comment by tkelman** [comment]
403 forbidden

**Comment by staticfloat** [comment]
Whoopsies.  Fixed.

**Comment by tkelman** [comment]
Your intuition was right. In a docker container of centos 5:
```
[root@d2853f083d24 julia-820aabeec6]# bin/julia
bin/julia: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by /home/julia-820aabeec6/bin/../lib/julia/libjulia.so)
bin/julia: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /home/julia-820aabeec6/bin/../lib/julia/libjulia.so)
bin/julia: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/julia-820aabeec6/bin/../lib/julia/libjulia.so)
```

We're already bundling libgfortran, I don't think adding libstdc++ to that would be so bad. The alternative would be to try hacking things to link statically, which would require a different compilation of GCC using `--with-pic`. I would've said to to do that earlier, but I think there can be potential performance implications of the binaries built that way. I'd rather ship a shared, default-configuration libstdc++ than try to statically link libstdc++ into every other shared library that we ship that needs it.

**Comment by staticfloat** [comment]
Yes, I had tried to generate a "static compiler", but ran into some issues.  Those issues later turned out to be because I wasn't including `<prefix>/lib64` on my 64-bit machine, so I think I could do that as well, but I'll try bundling `libstdc++` first.  Here's the file, if you plop that into `<julia_prefix>/lib/julia`, does it "just work"?

[32-bit libstdc++](https://julianightlies.s3.amazonaws.com/bin/linux/x86/tmp/libstdc%2B%2B.so)
[64-bit libstdc++](https://julianightlies.s3.amazonaws.com/bin/linux/x64/tmp/libstdc%2B%2B.so)

**Comment by tkelman** [comment]
Have to save it to `libstdc++.so.6`, but Julia starts. Running the tests now. I get an odd warning but I don't know if it matters:
```
/sbin/ldconfig: Can't open cache file /etc/ld.so.cache
: No such file or directory
```

**Comment by tkelman** [comment]
Oh right, the spawn test fails if you don't have `perl` installed, the only thing I had added from an empty `centos:5` container was `wget`. Everything else from `Base.runtests()` looks fine on 64 bit. 32 bit is harder for me to test, better to use vm's/vagrant instead of docker for testing anything that isn't 64-bit linux.

I'll try using these binaries for the problematic package with Fortran dependencies on Travis and see how it looks.

**Comment by tkelman** [comment]
Worked perfectly!!! Didn't need to worry about libstdc++ on Travis, Ubuntu 12.04 is apparently good enough. https://api.travis-ci.org/jobs/49236855/log.txt?deansi=true

So do we add libstdc++.so.6 to this script, switch the buildbots to use your new compiler, and call this fixed?

**Comment by staticfloat** [comment]
To demystify the `libstdc++` thing, it looks like it's just tied directly to the version of GCC that it's shipped with.  In other words, if ubuntu 12.04 ships with gcc 4.8 by default, it should "just work".  If it ships with 4.7, then it should "just work" as long as the ABI of whatever functions we try to use hasn't changed between 4.7 and 4.8.

**Comment by tkelman** [comment]
12.04 ships with 4.6. They don't break the ABI on every minor version, just some of them.

**Comment by staticfloat** [comment]
Furthermore, I believe the ABI is set on a per-function basis.

**Pull request merged**
