### PR TITLE
Add Float16 to supported x86 processors (#46499)

### PR DESCRIPTION
**Pull request by BioTurboNick**
Reopening #51700

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by rbvermaa** [comment]
There still seem to be an issue with Float16 on this branch:
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.3 (2023-10-14)
 _/ |\__'_|_|_|\__'_|  |  float16-sapphirerapids/a639fab579 (fork: 3196 commits, 788 days)
|__/                   |

julia> Float16(2.0)
Float16(0.0)

julia> versioninfo()
Julia Version 1.9.3
Commit a639fab579 (2023-10-14 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-unknown-linux-gnu)
  CPU: 8 × Intel(R) Xeon(R) Platinum 8488C
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, sapphirerapids)
  Threads: 1 on 8 virtual cores
Environment:
  LD_FOR_TARGET = ld
```

**Comment by vchuravy** [comment]
Could you test if backporting #51666 fixes that?

**Comment by fingolfin** [comment]
What's the status of this PR? Is the issue @rbvermaa reported still there? Is anyone working on it?

**Comment by BioTurboNick** [comment]
As far as I understand it, a solution pretty much has been identified - Float16 instructions probably need to be turned off on Sapphire Rapids with 1.9. So I think we should look for that to be done once the devs prioritize the next point release of 1.9.

**Pull request closed without merging**
