### PR TITLE
Explain multiline method signature inter-line character alignment reqs. in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Sacha0**
Addresses #17005. Best!

### CODE REVIEW

**Comment by kshyatt** [comment]
Sadly hit by a whitespace issue. Can you fix & rebase? This is a very helpful thing to note.

**Comment by Sacha0** [comment]
> Sadly hit by a whitespace issue. Can you fix & rebase?

Thanks for catching that! Fixed and rebased. Best!

**Comment by ivarne** [comment]
Bump!

(eg, this seems ready to merge, but I don't know the docsystem well enough to verify that the text is correct)

**Comment by MichaelHatherly** [comment]
Wording LGTM, thanks @Sacha0.

The second code block's language should be `rst` rather than `julia` though.

**Comment by Sacha0** [comment]
> The second code block's language should be rst rather than julia though.

Good catch! Fixed. Thanks for the bump and review!

**Comment by Sacha0** [comment]
Thanks all!

**Pull request merged**
