### PR TITLE
refactor message_handler_loop

### PR DESCRIPTION
**Pull request by amitmurthy**
This PR refactors code in message_handler_loop. Looks a bit cleaner with dispatching on `Val{msg}`.
Also a minor cleanup of `process_messages`.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I don't know if it matters in practice, but I suspect this would be slower due to extra time taken constructing the Val type and dispatching on it. A series of `if` statements comparing pointers is very efficient by comparison.

**Comment by amitmurthy** [comment]
```
julia> function foo(x)
           if x==:a
               return :a
           elseif x==:b
               return :b
           elseif x==:c
               return :c
           elseif x==:d
               return :d
           elseif x==:e
               return :e
           elseif x==:f
               return :f
           elseif x==:g
               return :g
           elseif x==:h
               return :h
           end    
       end;

julia> bar(::Type{Val{:a}}) = :a;

julia> bar(::Type{Val{:b}}) = :b;

julia> bar(::Type{Val{:c}}) = :c;

julia> bar(::Type{Val{:d}}) = :d;

julia> bar(::Type{Val{:e}}) = :e;

julia> bar(::Type{Val{:f}}) = :f;

julia> bar(::Type{Val{:g}}) = :g;

julia> bar(::Type{Val{:h}}) = :h;

julia> function testfoo(n)
           @time for i in 1:10^n
               for x in [:a, :b, :c, :d, :e, :f, :g, :h]
                 foo(x)
               end
           end
       end;

julia> function testbar(n)
           @time for i in 1:10^n
               for x in [:a, :b, :c, :d, :e, :f, :g, :h]
                   bar(Val{x})
               end
           end
       end;

julia> testfoo(1);
   2.480 microseconds (10 allocations: 1280 bytes)

julia> testbar(1);
   1.880 milliseconds (779 allocations: 62056 bytes)

julia> testfoo(6);
  91.991 milliseconds (1000 k allocations: 122 MB, 6.84% gc time)

julia> testbar(6);
   1.353 seconds      (1000 k allocations: 122 MB, 0.22% gc time)
```

The numbers are for 800 million invocations. It is slower, but in the overall scheme of things should not affect us much.

I would still like to go ahead with this because
a) it is easier on the eyes
b) it is a small step with making the entire low level message layer modular, including supporting user defined messages. This is a bit out in the future and is yet to be designed.

**Comment by JeffBezanson** [comment]
> including supporting user defined messages

In that case, we might be better off defining a type for each message, so we can write `function handle_msg(m::CallMsg, r, w)`, which looks much nicer and also eliminates the manual `deserialize` calls.

**Comment by jakebolewski** [comment]
Having custom message types was more in line with what I had in mind.

**Comment by amitmurthy** [comment]
Makes sense. I'll change it.

**Comment by amitmurthy** [comment]
Done. Will merge this in a while if there are no issues.

**Pull request merged**
