### PR TITLE
Accept string interpolation as doc string

### PR DESCRIPTION
**Pull request by yuyichao**
Fix up #12502 

Tests comes later.

Ref https://github.com/JuliaLang/julia/commit/8fe236b5635e92ffea1271d71c05988dee0cf782#commitcomment-12672394

@MichaelHatherly

### CODE REVIEW

**Comment by yuyichao** [comment]
Tests added.

**Comment by yuyichao** [comment]
@tkelman Any idea why the second commit of this PR doesn't trigger a travis-ci/pr ? The last travis-pr is the build for the first commit of this PR. Not sure if any other pr's got updated after this one.

**Comment by tkelman** [comment]
Dunno. Best guess is a webhook transmission failure, but Travis shows up under the legacy "Services" panel instead of the other webhooks, so I can't check delivery status or try to resend.

**Comment by yuyichao** [comment]
I see. There is now a new PR build queued so probably something random failed for this one......

**Comment by MichaelHatherly** [comment]
Thanks @yuyichao!

**Pull request merged**
