### PR TITLE
apply_by_to_key keyword for searchsorted

### PR DESCRIPTION
**Pull request by StephenVavasis**
This update to ordering.jl and sort.jl adds a new keyword apply_by_to_key to the searchsorted family of functions and
and insorted.  This commit address an issue that trips up many users: the
"by" keyword is unexpectedly applied to the search key.  This makes
the functions particularly awkward if the "by" function extracts part
of a larger object.  This patch is meant to address issue https://github.com/JuliaLang/julia/issues/9429 as
well as repeats including https://github.com/JuliaLang/julia/issues/33997 and https://github.com/JuliaLang/julia/pull/35418

### CODE REVIEW

**Comment by jmichel7** [comment]
OK, by not just `apply_by` for the keyword? It is clear that the `by` function is applied in any case to the vector to be searched,
so `apply_by=false` would mean do not apply it to the object being searched.

**Comment by DNF2** [comment]
Instead of having to use two keywords, one of them really long, how about a different keyword that is only applied to the collection? Maybe `in`, or something else concise?

(If there's even a single underscore in a name I tend to think there must be better way to phrase it;) `in` isn't great, I know, it's ok if the function is `first` or `last`, maybe, but there must be something concise.

**Comment by StephenVavasis** [comment]
I will close this PR myself because I just realized that the core team has already rejected another PR, namely https://github.com/JuliaLang/julia/pull/35418, that also fixes the issue.  I would like to urge the core team to find a solution to this problem if 35418 is unsatisfactory.

**Comment by jmichel7** [comment]
Le Wed, Dec 22, 2021 at 06:22:30PM -0800, StephenVavasis a écrit :
> I will close this PR myself because I just realized that the core team has already rejected another PR, namely https://github.com/JuliaLang/julia/pull/35418, that also fixes the issue.  I would like to urge the core team to find a solution to this problem if 35418 is unsatisfactory. 

35418 was proposing a different (less direct, in my mind) solution. Perhaps
they would not see in the same light your proposed solution (I feel choosing
well the keyword name is important here).
------------------------------------------------------------------------------
Jean MICHEL, Groupes et representations, IMJ-PRG UMR7586 tel.(33)157279144
Bureau 639 Bat. Sophie Germain Case 7012 - 75205 PARIS Cedex 13

**Pull request closed without merging**
