### PR TITLE
Make ScopedValue public

### PR DESCRIPTION
**Pull request by lgoettgens**
Motivated by https://github.com/JuliaLang/julia/issues/52535#issuecomment-1991439510
Follow-up to https://github.com/JuliaLang/julia/pull/53004

This should be backported to 1.11 imo.

cc @vchuravy @KristofferC @sgaure

### CODE REVIEW

**Comment by CameronBieganek** [comment]
#53628 has been merged, which I think addresses the ambiguity that led to this PR. #53628 contains some documentation improvements that, among other things, should make it more clear that the `Base.ScopedValues` module follows the same pattern as the `Base.Iterators` module: If you want to use `with`, then you would do either `ScopedValues.with` or `using Base.ScopedValues` (or `using Base.ScopedValues: with`, etc).

**Comment by lgoettgens** [comment]
Bump. Is this something we wanna have or should this get closed?

**Comment by CameronBieganek** [comment]
> I believe `using Base.<some submodule>` is rare, and it seems invasive. Are there exceptions where you are accessing non-public API? I at least think (then) we need a list of modules that you can and should do such for. [Or it this taken care of by "public" rather than "export", for all methods in such modules? Is a module ok to use in full or in part?]

It might not be super common in practice, but it's perfectly valid to do `using Base.Iterators` (or `using .Iterators`). It's also perfectly valid to do `using Base.ScopedValues`. Submodules need to have their own `export` and `public` declarations for the symbols within the submodules.

However, I think we probably do need to add `public` declarations in `Base` for both the `Iterators` submodule and the `ScopedValues` submodule, which I commented on [here](https://github.com/JuliaLang/julia/issues/51335#issuecomment-2125147434).

> Is this something we wanna have or should this get closed?

In my opinion, this PR should be closed. The recommend approach is to use qualified names, like `ScopedValues.with`, or to bring the names into scope with `using`, e.g.

```julia
using Base.ScopedValues
```

or

```julia
using Base.ScopedValues: with
```

However, you could modify the PR title and make the change in this PR the addition of `Iterators` and `ScopedValues` to the `public` list.

🙂

**Comment by CameronBieganek** [comment]
Actually, the `Iterators` module is already on the Base `export` list, which I didn't quite realize at first. I just opened a PR to add the `ScopedValues` module to the Base export list: #54556.

**Pull request closed without merging**
