### PR TITLE
Sockets: handle ECANCELED result from connect

### PR DESCRIPTION
**Pull request by vtjnash**
We were previously asserting that this couldn't happen

### CODE REVIEW

**Comment by samoconnor** [comment]
Do you have any interest in merging HTTP.jl's connect timeout into stdlib/Sockets?
https://github.com/JuliaWeb/HTTP.jl/blob/master/src/ConnectionPool.jl#L513
It seems like a generally useful thing.

**Comment by jebej** [comment]
Having a user configurable connection (and read) timeout would be useful for working with scientific instruments over tcp.

**Comment by vtjnash** [comment]
I've usually wanted to avoid adding ad-hoc timeouts and instead just ensure that the API provides a handle that you can `close` to cancel the request when the user no longer needs the result. UI responsiveness should be handled by using background tasks anyways, not timeouts.

**Comment by jebej** [comment]
Using background tasks is fine for full fledged applications, but when interactively running code it seems overcomplicated. I work in a lab, and would like to switch to Julia for instrument control, but the lack of timeout means any mistake (with configuration or command) locks Julia into a infinite wait.

**Comment by vtjnash** [comment]
We attempt to return interactive control if you hit `^C`. I assume that I'd be just as unlikely to think to type set a timeout first as to not make a mistake...

**Comment by StefanKarpinski** [comment]
I agree with @vtjnash here – timeouts are a really bad solution to this. What you really want is to be able to cancel network operations from the top level. That's hard to do but it's the right way to do this.

**Comment by jebej** [comment]
Yes, currently `ctrl-c` doesn't work, at least on windows. Is there an issue open for this?

**Comment by vtjnash** [comment]
Ah, of course, windows – I think that functionality is lacking in proper support from the OS there. We can probably add work-arounds, there's just limited time in the day to implement and test all of the workarounds required for that platform.

**Pull request merged**
