### PR TITLE
Revert "add readline(::AbstractCmd)"

### PR DESCRIPTION
**Pull request by Keno**
This broke the buildbots. Reverts JuliaLang/julia#34927.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
How did this cause win64 to fail?

**Comment by Keno** [comment]
The test keeps a BusyBox command running and doesn't wait for it to exit. On win64 we delete BusyBox at the end of that testset which fails if the command is still running.

**Comment by bicycle1885** [comment]
Ah, so we need to terminate the process before returning the line string.

**Comment by Keno** [comment]
Yes, that would be one valid solution (which I think would be ok).

**Pull request merged**
