### PR TITLE
Prefer https

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Isn't HTTPS safer in case of man-in-the-middle attacks? And should be prefferred in all cases I see HTTP used? At least here (confirmed file is available either way).

Some counterpoint I can think of is, if HTTPS breaks, you don't get the file that way (you'll get an exception and know?). I'm not sure it's a good reason here to avoid HTTPS, even with this only for a test. Seems the alternative is the testing infrastructure could be compromised.

**Comment by PallHaraldsson** [comment]
I looked for other cases: https://github.com/JuliaLang/julia/search?q=http&unscoped_q=http

And there are http://httpbin.org/ip (doesn't seem important).

And for an image search for "apartheid wall in palestine"...:

http://images.search.yahoo.com/images/view?back=http%3A%2F%2Fus.yhs4.search.yahoo.com%2Fyhs%2Fsearch%3Fei%3DUTF-8%26p%3Dapartheid%2Bwall%2Bin%2Bpalestine%26type%3Dgrvydef%26param1%3D1%26param2%3Dsid%253Db01676f9c26355f014f8a9db87545d61%2526b%253DChrome%2526ip%253D71.163.72.113%2526p%253Dgroovorio%2526x%253DAC811262A746D3CD%2526dt%253DS940%2526f%253D7%2526a%253Dgrv_tuto1_14_30%26hsimp%3Dyhs-fullyhosted_003%26hspart%3Dironsource&w=588&h=387&imgurl=occupiedpalestine.files.wordpress.com%2F2012%2F08%2F5-peeking-through-the-wall.jpg%3Fw%3D588%26h%3D387&rurl=http%3A%2F%2Fwww.stopdebezetting.com%2Fwereldpers%2Fcompare-the-berlin-wall-vs-israel-s-apartheid-wall-in-palestine.html&size=49.0KB&name=...+%3Cb%3EApartheid+wall+in+Palestine%3C%2Fb%3E...+%7C+Or+you+go+peeking+through+the+%3Cb%3Ewall%3C%2Fb%3E&p=apartheid+wall+in+palestine&oid=50754b363ca991060b276aba291113cc&fr2=&fr=&tt=...+%3Cb%3EApartheid+wall+in+Palestine%3C%2Fb%3E...+%7C+Or+you+go+peeking+through+the+%3Cb%3Ewall%3C%2Fb%3E&b=0&ni=21&no=4&ts=&tab=organic&sigr=13evdtqdq&sigb=19k7nsjvb&sigi=12o2la1db&sigt=12lia2m0j&sign=12lia2m0j&.crumb=.yUtKgFI6DE&hsimp=yhs-fullyhosted_003&hspart=ironsource

**Comment by staticfloat** [comment]
Keeping the `httpbin` stuff to HTTP actually serves a purpose; we _want_ these to be interceptable so that we can debug them when things go wrong.  :)

If you want to add changes for the Vagrantfile, I'll be happy to take a look at that too.

**Review by staticfloat — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Should we have a checksum for the `busybox.exe` download then? Otherwise we're executing arbitrary code provided by a potential MITM attacker.

**Comment by staticfloat** [comment]
That executable can change at any time; it's not versioned.   We should probably host our own version, add a checksum, and use that URL instead (with HTTPS).

**Comment by PallHaraldsson** [comment]
I changed all three but only confirmed links for other two not: http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20150916.tar.xz

**Comment by staticfloat** [comment]
This looks good to me for now, it's clearly an improvement.  We should move toward versioned, hash-checked downloads for pretty much everything, I'll open an issue to track that independent of this PR.

**Review by staticfloat — APPROVED** [review]

**Comment by PallHaraldsson** [comment]
With my seemingly trivial change passing on Linux, I believe the macOS CI fail is a false alarm, for something entirely unrelated and this PR should just be merged:

```
failed to clone from https://github.com/JuliaLang/Example.jl.git, error: GitError(Code:ERROR, Class:Net, curl error: Could not resolve host: github.com 

[..]

Error in testset Pkg/pkg:
Test Failed at /private/tmp/julia/share/julia/stdlib/v1.2/Pkg/test/pkg.jl:187
  Expression: ((Pkg.API).__installed())[TEST_PKG.name] == old_v
   Evaluated: v"0.5.1" == v"0.3.3"
ERROR: LoadError: Test run finished with errors
in expression starting at /private/tmp/julia/share/julia/test/runtests.jl:61
The command "if [ $(echo "$FILES_CHANGED" | grep -cv '^doc/') -gt 0 ]; then /tmp/julia/bin/julia --check-bounds=yes runtests.jl $TESTSTORUN && /tmp/julia/bin/julia --check-bounds=yes runtests.jl LibGit2/online Pkg/pkg download; fi" exited with 1.
```

**Comment by PallHaraldsson** [comment]
Bump. Just merge as CI false alarm "Probably a temporary connection problem"?

**Comment by staticfloat** [comment]
Yep.  Thanks!

**Pull request merged**
