### PR TITLE
impose stricter and earlier validation on ccall/cfunction types

### LINKED ISSUE #43636: Segfault in LLVM when attempting to compile a `ccall` that returns `Core.MethodInstance`
Here's a simple ccall that succeeds if you indicate the return type is `Any`, but fails if you specify the return type as `Core.MethodInstance`:
```julia
julia> foo(x,y) = 1; foo(2,3)
1

julia> mi = methods(foo).ms[1].specializations[1]
MethodInstance for foo(::Int64, ::Int64)

julia> ccall(:jl_typeof, Any, (Any,), mi)
Core.MethodInstance

julia> ccall(:jl_typeof, Core.MethodInstance, (Any,), mi)

signal (11): Segmentation fault: 11
in expression starting at REPL[6]:1
_ZNK4llvm10AllocaInst14isStaticAllocaEv at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
LocalScan at /Users/nathandaly/src/julia/src/llvm-late-gc-lowering.cpp:1475
runOnFunction at /Users/nathandaly/src/julia/src/llvm-late-gc-lowering.cpp:2675
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
operator() at /Users/nathandaly/src/j
[...]
```
I'm not sure why.

Here's another example that shows that it crashes in LLVM codegen when _compiling_ the ccall, not when performing it, since it crashes before encountering the `UndefVarError` or the `dlsym` error:
```julia
julia> ccall(:nonexistant, typeof(+), (Int,), garbagevariablename)
ERROR: UndefVarError: garbagevariablename not defined
Stacktrace:
 [1] top-level scope
   @ ./REPL[2]:1

julia> struct MyType end

julia> ccall(:nonexistant, MyType, (Int,), garbagevariablename)
ERROR: UndefVarError: garbagevariablename not defined
Stacktrace:
 [1] top-level scope
   @ ./REPL[4]:1

julia> ccall(:nonexistant, Core.MethodInstance, (Int,), garbagevariablename)

signal (11): Segmentation fault: 11
in expression starting at REPL[5]:1
_ZNK4llvm10AllocaInst14isStaticAllocaEv at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
LocalScan at /Users/nathandaly/src/julia/src/llvm-late-gc-lowering.cpp:1475
runOnFunction at /Users/nathandaly/src/julia/src/llvm-late-gc-lowering.cpp:2675
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
operator() at /Users/nathandaly/src/julia/src/jitlayers.cpp:0
_ZN4llvm3orc14IRCompileLayer4emitENSt3__110unique_ptrINS0_29MaterializationResponsibilityENS2_14default_deleteIS4_EEEENS0_16ThreadSafeModuleE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc31BasicIRLayerMaterializationUnit11materializeENSt3__110unique_ptrINS0_29MaterializationResponsibilityENS2_14default_deleteIS4_EEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession26materializeOnCurrentThreadENSt3__110unique_ptrINS0_19MaterializationUnitENS2_14default_deleteIS4_EEEENS3_INS0_29MaterializationResponsibilityENS5_IS8_EEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZNSt3__110__function6__funcIPFvNS_10unique_ptrIN4llvm3orc19MaterializationUnitENS_14default_deleteIS5_EEEENS2_INS4_29MaterializationResponsibilityENS6_IS9_EEEEENS_9allocatorISD_EESC_EclEOS8_OSB_ at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession22dispatchOutstandingMUsEv at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession17OL_completeLookupENSt3__110unique_ptrINS0_21InProgressLookupStateENS2_14default_deleteIS4_EEEENS2_10shared_ptrINS0_23AsynchronousSymbolQueryEEENS2_8functionIFvRKNS_8DenseMapIPNS0_8JITDylibENS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISG_EEEENSH_ISE_EENS_6detail12DenseMapPairISE_SJ_EEEEEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc25InProgressFullLookupState8completeENSt3__110unique_ptrINS0_21InProgressLookupStateENS2_14default_deleteIS4_EEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession19OL_applyQueryPhase1ENSt3__110unique_ptrINS0_21InProgressLookupStateENS2_14default_deleteIS4_EEEENS_5ErrorE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS0_10LookupKindERKNSt3__16vectorINS3_4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEEENS3_9allocatorIS9_EEEENS0_15SymbolLookupSetENS0_11SymbolStateENS_15unique_functionIFvNS_8ExpectedINS_8DenseMapINS0_15SymbolStringPtrENS_18JITEvaluatedSymbolENS_12DenseMapInfoISK_EENS_6detail12DenseMapPairISK_SL_EEEEEEEEENS3_8functionIFvRKNSJ_IS7_NS_8DenseSetISK_SN_EENSM_IS7_EENSP_IS7_SX_EEEEEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKNSt3__16vectorINS2_4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEEENS2_9allocatorIS8_EEEERKNS0_15SymbolLookupSetENS0_10LookupKindENS0_11SymbolStateENS2_8functionIFvRKNS_8DenseMapIS6_NS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISM_EEEENSN_IS6_EENS_6detail12DenseMapPairIS6_SP_EEEEEEE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKNSt3__16vectorINS2_4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEEENS2_9allocatorIS8_EEEENS0_15SymbolStringPtrENS0_11SymbolStateE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS0_15SymbolStringPtrENS0_11SymbolStateE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS_8ArrayRefIPNS0_8JITDylibEEENS_9StringRefENS0_11SymbolStateE at /Users/nathandaly/src/julia/usr/lib/libLLVM.dylib (unknown line)
addModule at /Users/nathandaly/src/julia/src/jitlayers.cpp:723
jl_add_to_ee at /Users/nathandaly/src/julia/src/jitlayers.cpp:982 [inlined]
jl_add_to_ee at /Users/nathandaly/src/julia/src/jitlayers.cpp:1026
jl_add_to_ee at /Users/nathandaly/src/julia/src/jitlayers.cpp:1048 [inlined]
_jl_compile_codeinst at /Users/nathandaly/src/julia/src/jitlayers.cpp:136
jl_generate_fptr_impl at /Users/nathandaly/src/julia/src/jitlayers.cpp:314
jl_compile_method_internal at /Users/nathandaly/src/julia/src/gf.c:2020
_jl_invoke at /Users/nathandaly/src/julia/src/gf.c:2296 [inlined]
ijl_invoke at /Users/nathandaly/src/julia/src/gf.c:2311
jl_toplevel_eval_flex at /Users/nathandaly/src/julia/src/toplevel.c:879
jl_toplevel_eval_flex at /Users/nathandaly/src/julia/src/toplevel.c:832
ijl_toplevel_eval at /Users/nathandaly/src/julia/src/toplevel.c:897 [inlined]
ijl_toplevel_eval_in at /Users/nathandaly/src/julia/src/toplevel.c:947
eval at ./boot.jl:368 [inlined]
eval_user_input at /Users/nathandaly/src/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
repl_backend_loop at /Users/nathandaly/src/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
start_repl_backend at /Users/nathandaly/src/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
#run_repl#47 at /Users/nathandaly/src/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
run_repl at /Users/nathandaly/src/julia/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:356
jfptr_run_repl_53988 at /Users/nathandaly/src/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/src/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/nathandaly/src/julia/src/gf.c:2486
#934 at ./client.jl:403
jfptr_YY.934_36091 at /Users/nathandaly/src/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/src/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/nathandaly/src/julia/src/gf.c:2486
jl_apply at /Users/nathandaly/src/julia/src/./julia.h:1790 [inlined]
jl_f__call_latest at /Users/nathandaly/src/julia/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:731 [inlined]
invokelatest at ./essentials.jl:729 [inlined]
run_main_repl at ./client.jl:388
exec_options at ./client.jl:318
_start at ./client.jl:506
jfptr__start_24340 at /Users/nathandaly/src/julia/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/src/julia/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/nathandaly/src/julia/src/gf.c:2486
jl_apply at /Users/nathandaly/src/julia/src/./julia.h:1790 [inlined]
true_main at /Users/nathandaly/src/julia/src/jlapi.c:562
jl_repl_entrypoint at /Users/nathandaly/src/julia/src/jlapi.c:706
Allocations: 893761 (Pool: 893433; Big: 328); GC: 1
```

### PR DESCRIPTION
**Pull request by vtjnash**
Closes #43636

### CODE REVIEW

**Review by NHDaly — APPROVED** [review]
Cool, thanks Jameson! The changes seem sane to me, although i'm pretty unfamiliar with this code. The tests definitely seem reasonable. Thanks for making the change! 👍

**Comment by fingolfin** [comment]
This seems to have broken several packages that worked well so far. I am just wondering if that's intentional? From reading the issue, it sounded to me as if this was mostly there to fix things that would have crashed before, but in our case, we had a `ccall` with return value `Function`, and it worked perfectly fine so far. Now it is rejected. Is that as intended? If so, perhaps it deserves a mention in some NEWS item or whatever, because it'll break existing working code?

**Comment by vtjnash** [comment]
`Function` seems like a mildly odd choice for a return type there, where using `Any` agrees better with the `ccall` argument used to create it. You are right that it was intentional, and that it is more strict now than necessary. We have had the alternative also of `Ref{Function}` for a long time for promising "this returns a valid julia pointer to something that I promise is a subtype of Function".

**Comment by andreasnoack** [comment]
I've bisected this PR as the cause of an error similar to https://discourse.julialang.org/t/package-compiler-errors-with-system-image-too-large-message/85849. With version 1.7.x of Julia, our system image is about 1.1GB but after this PR, it fails with the `system image too large` error.

**Pull request merged**
