### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bwignall**
Should be non-semantic. Some are in "patch" files; please let me know if these need to be reverted.

Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos, with https://github.com/bwignall/typochecker to help automate the checking.

### CODE REVIEW

**Review by ViralBShah — COMMENTED** [review]
All look good to me!

**Comment by fredrikekre** [comment]
Since the patch files are taken verbatim from upstream (I assume) it does not seem necessary to update those.

**Comment by bwignall** [comment]
@fredrikekre , I will revert those momentarily.

**Review by StefanKarpinski — APPROVED** [review]
Thanks for the type fixes!

**Pull request merged**
