### PR TITLE
[release-0.4] more backports

### PR DESCRIPTION
**Pull request by tkelman**
~~The fact that we're backporting almost everything might be a sign that we branched too early, but whatever.~~ Will run packageevaluator here too just for kicks.

### CODE REVIEW

**Comment by ivarne** [comment]
I also just pushed 324a21c4baf404beb40947 which needs to be backported. Kind of scary experience to work with comandline git on windows.

**Comment by tkelman** [comment]
Hm, these might be down to package changes or other factors but deserve looking into:
```
tkelman@ygdesk:~/github/PackageEvaluator.jl/scripts$ diff -u b23b11a370/summary f2dc24e376/summary
--- b23b11a370/summary  2015-09-14 09:08:16.348503305 -0700
+++ f2dc24e376/summary  2015-09-14 09:08:23.900503586 -0700
@@ -19,7 +19,7 @@
 nightly/Arduino.json
 "not_possible"
 nightly/ArgParse.json
-"tests_pass"
+"tests_fail"
 nightly/ArrayViews.json
 "tests_pass"
 nightly/Arrowhead.json
@@ -31,7 +31,7 @@
 nightly/AudioIO.json
 "tests_fail"
 nightly/Augur.json
-"tests_pass"
+"tests_fail"
 nightly/AutoHashEquals.json
 "tests_pass"
 nightly/Autoreload.json
@@ -201,7 +201,7 @@
 nightly/CRC32.json
 "tests_pass"
 nightly/CRC.json
-"tests_pass"
+"tests_fail"
 nightly/CRF.json
 "tests_pass"
 nightly/CrossDecomposition.json
@@ -321,7 +321,7 @@
 nightly/Elliptic.json
 "tests_pass"
 nightly/Elly.json
-"tests_pass"
+"tests_fail"
 nightly/EmpiricalRisks.json
 "tests_pass"
 nightly/Equations.json
@@ -544,6 +544,8 @@
 "tests_pass"
 nightly/ImageView.json
 "tests_fail"
+nightly/Immerse.json
+"tests_fail"
 nightly/ImmutableArrays.json
 "tests_pass"
 nightly/ImplicitEquations.json
@@ -751,7 +753,7 @@
 nightly/MarketTechnicals.json
 "tests_fail"
 nightly/Match.json
-"tests_fail"
+"tests_pass"
 nightly/Mathematica.json
 "not_possible"
 nightly/MathProgBase.json
@@ -981,7 +983,7 @@
 nightly/Pipe.json
 "tests_pass"
 nightly/Playground.json
-"tests_pass"
+"tests_fail"
 nightly/Plotly.json
 "tests_fail"
 nightly/PLX.json
@@ -1097,7 +1099,7 @@
 nightly/Roots.json
 "tests_pass"
 nightly/RouletteWheels.json
-"tests_fail"
+"tests_pass"
 nightly/RudeOil.json
 "not_possible"
 nightly/RunTests.json
```

**Comment by tkelman** [comment]
All of the newly introduced failures are due to https://github.com/JuliaLang/julia/commit/3b43bd856b4d132d7aacba59ae2e1e0b181fb958#diff-7904f4ddd9158030529e0ed5ee8707eeR668

cc @carlobaldassi @tinybike @andrewcooke @tanmaykm @Rory-Finnegan

**Comment by IainNZ** [comment]
Wow PkgEval doing useful things!

**Comment by KristofferC** [comment]
Someone just had to start using it properly :)

**Comment by tkelman** [comment]
I am an enormous fan of identifying problems before they become issues, rather than after. It's just a few clicks and a bunch of CPU hours to do this. With better hardware and a little bit of code we'll work on automating this more.

**Comment by JeffBezanson** [comment]
Does this mean that e.g. ArgParse calls `require`? It doesn't seem to. What am I missing?

**Comment by tkelman** [comment]
It would appear so? Here's the full PackageEvaluator output for them: https://gist.github.com/ac754dbd54db3dc102e8 (might want to clone locally and pretty-print that with jq or JSON.jl)

**Comment by mbauman** [comment]
ArgParse just needs a new tag to include https://github.com/carlobaldassi/ArgParse.jl/commit/78dc47982987de457a2e638bfb3f4305675a4634

**Comment by JeffBezanson** [comment]
Ok I'll try to deprecate `require` more gently.

**Comment by tkelman** [comment]
About to update this with another round, but here are intermediate results from the more-gentle `require` deprecation:
```diff

--- b23b11a370/summary  2015-09-14 09:08:16.348503305 -0700
+++ 5fd1844fb5/summary  2015-09-15 15:38:23.612616105 -0700
@@ -31,7 +31,7 @@
 nightly/AudioIO.json
 "tests_fail"
 nightly/Augur.json
-"tests_pass"
+"tests_fail"
 nightly/AutoHashEquals.json
 "tests_pass"
 nightly/Autoreload.json
@@ -544,6 +544,8 @@
 "tests_pass"
 nightly/ImageView.json
 "tests_fail"
+nightly/Immerse.json
+"tests_fail"
 nightly/ImmutableArrays.json
 "tests_pass"
 nightly/ImplicitEquations.json
@@ -751,7 +753,7 @@
 nightly/MarketTechnicals.json
 "tests_fail"
 nightly/Match.json
-"tests_fail"
+"tests_pass"
 nightly/Mathematica.json
 "not_possible"
 nightly/MathProgBase.json
@@ -891,7 +893,7 @@
 nightly/NLreg.json
 "tests_fail"
 nightly/NLsolve.json
-"tests_pass"
+"tests_fail"
 nightly/NMEA.json
 "tests_pass"
 nightly/NMF.json
@@ -1097,7 +1099,7 @@
 nightly/Roots.json
 "tests_pass"
 nightly/RouletteWheels.json
-"tests_fail"
+"tests_pass"
 nightly/RudeOil.json
 "not_possible"
 nightly/RunTests.json
@@ -1133,7 +1135,7 @@
 nightly/Shannon.json
 "tests_fail"
 nightly/Shapefile.json
-"no_tests"
+"tests_pass"
 nightly/ShapeModels.json
 "tests_pass"
 nightly/Showoff.json
@@ -1277,7 +1279,7 @@
 nightly/TimeModels.json
 "tests_fail"
 nightly/TimeSeries.json
-"tests_fail"
+"tests_pass"
 nightly/Timestamps.json
 "tests_fail"
 nightly/TimeZones.json
@@ -1288,8 +1290,6 @@
 "tests_pass"
 nightly/TopicModels.json
 "no_tests"
-nightly/TrafficAssignment.json
-"tests_fail"
 nightly/Twitter.json
 "not_possible"
 nightly/TypeCheck.json
```

Augur.jl is still broken but now because of ```LoadError: use `include` instead of `reload` to load source files```. NLSolve had what looks like a convergence failure: `Running tests:\n * 2by2.jl\nERROR: LoadError: LoadError: AssertionError: converged(r)` though that may be intermittent c.f. https://github.com/EconForge/NLsolve.jl/issues/18. TrafficAssignment apparently didn't run because of what looked like a temporary connection problem at 4am last night.

**Comment by JeffBezanson** [comment]
That might be ok. I really don't think packages should call `reload`.

**Comment by tkelman** [comment]
I'm going to merge this now because I think moving ccalltest caused some issues on appveyor. Will report the currently running pkgeval results for https://github.com/JuliaLang/julia/commit/d4701378cdc990fd73837b9e272017553c72866f when they're finished.

**Comment by tkelman** [comment]
Whoops, something in here broke `doc/genstdlib.jl`, it's writing an empty file into `doc/stdlib/c.rst` for me. Bisecting now, we'll have to fix this before cutting RC2.

**Comment by tkelman** [comment]
I was going to say we should cut RC2 today, but a lot of things broke here:
```
--- b23b11a370/summary  2015-09-14 09:08:16.348503305 -0700
+++ d4701378cd/summary  2015-09-16 13:11:28.615495656 -0700
@@ -31,7 +31,7 @@
 nightly/AudioIO.json
 "tests_fail"
 nightly/Augur.json
-"tests_pass"
+"tests_fail"
 nightly/AutoHashEquals.json
 "tests_pass"
 nightly/Autoreload.json
@@ -59,7 +59,7 @@
 nightly/Bezier.json
 "tests_pass"
 nightly/BinDeps.json
-"tests_pass"
+"tests_fail"
 nightly/BiomolecularStructures.json
 "tests_fail"
 nightly/BioSeq.json
@@ -79,13 +79,13 @@
 nightly/Bokeh.json
 "tests_fail"
 nightly/Boltzmann.json
-"tests_pass"
-nightly/Bootstrap.json
 "tests_fail"
+nightly/Bootstrap.json
+"tests_pass"
 nightly/BoundingBoxes.json
 "tests_pass"
 nightly/Brim.json
-"tests_pass"
+"tests_fail"
 nightly/Brownian.json
 "tests_fail"
 nightly/BSplines.json
@@ -95,7 +95,7 @@
 nightly/BusinessDays.json
 "tests_pass"
 nightly/Cairo.json
-"tests_pass"
+"tests_fail"
 nightly/Calculus.json
 "tests_pass"
 nightly/Calendar.json
@@ -109,7 +109,7 @@
 nightly/CauseMap.json
 "tests_fail"
 nightly/Cbc.json
-"tests_pass"
+"tests_fail"
 nightly/CellularAutomata.json
 "tests_pass"
 nightly/ChainedVectors.json
@@ -135,7 +135,7 @@
 nightly/Cliffords.json
 "tests_pass"
 nightly/Clp.json
-"tests_pass"
+"tests_fail"
 nightly/Clustering.json
 "tests_pass"
 nightly/ClusterManagers.json
@@ -144,12 +144,14 @@
 "tests_pass"
 nightly/CodeTools.json
 "tests_fail"
+nightly/CoinOptServices.json
+"tests_fail"
 nightly/ColorBrewer.json
 "tests_pass"
 nightly/Color.json
 "tests_pass"
 nightly/Colors.json
-"tests_pass"
+"tests_fail"
 nightly/ColorTypes.json
 "tests_pass"
 nightly/ColorVectorSpace.json
@@ -163,7 +165,7 @@
 nightly/CompilerOptions.json
 "tests_pass"
 nightly/Compose.json
-"tests_pass"
+"tests_fail"
 nightly/CompressedSensing.json
 "tests_pass"
 nightly/Conda.json
@@ -187,11 +189,11 @@
 nightly/Cosmology.json
 "tests_pass"
 nightly/CovarianceMatrices.json
-"tests_fail"
+"tests_pass"
 nightly/CoverageBase.json
 "tests_pass"
 nightly/Coverage.json
-"tests_pass"
+"tests_fail"
 nightly/CPLEX.json
 "not_possible"
 nightly/Cpp.json
@@ -259,7 +261,7 @@
 nightly/DICOM.json
 "no_tests"
 nightly/DictFiles.json
-"tests_pass"
+"tests_fail"
 nightly/DictUtils.json
 "no_tests"
 nightly/Dierckx.json
@@ -309,11 +311,11 @@
 nightly/Dynare.json
 "tests_fail"
 nightly/EcologicalNetwork.json
-"tests_pass"
+"tests_fail"
 nightly/EconDatasets.json
 "tests_fail"
 nightly/ECOS.json
-"tests_pass"
+"tests_fail"
 nightly/ElasticFDA.json
 "tests_fail"
 nightly/ELF.json
@@ -339,7 +341,7 @@
 nightly/Example.json
 "tests_pass"
 nightly/ExcelReaders.json
-"tests_pass"
+"tests_fail"
 nightly/Expect.json
 "not_possible"
 nightly/ExpressionUtils.json
@@ -347,13 +349,13 @@
 nightly/ExtremelyRandomizedTrees.json
 "tests_pass"
 nightly/FaceDatasets.json
-"tests_pass"
+"tests_fail"
 nightly/FactCheck.json
 "tests_pass"
 nightly/FactorModels.json
-"tests_fail"
-nightly/Faker.json
 "tests_pass"
+nightly/Faker.json
+"tests_fail"
 nightly/FastaIO.json
 "tests_fail"
 nightly/FastAnonymous.json
@@ -369,7 +371,7 @@
 nightly/FiniteStateMachine.json
 "tests_pass"
 nightly/FITSIO.json
-"tests_pass"
+"tests_fail"
 nightly/FixedEffectModels.json
 "tests_fail"
 nightly/FixedPointNumbers.json
@@ -379,7 +381,7 @@
 nightly/Fixtures.json
 "no_tests"
 nightly/FLANN.json
-"tests_pass"
+"tests_fail"
 nightly/Fontconfig.json
 "tests_pass"
 nightly/Formatting.json
@@ -399,7 +401,7 @@
 nightly/FunctionalUtils.json
 "no_tests"
 nightly/Gadfly.json
-"tests_pass"
+"tests_fail"
 nightly/GARCH.json
 "tests_fail"
 nightly/Gaston.json
@@ -415,7 +417,7 @@
 nightly/GeoInterface.json
 "tests_pass"
 nightly/GeoIP.json
-"tests_pass"
+"tests_fail"
 nightly/GeoJSON.json
 "tests_pass"
 nightly/GeometricalPredicates.json
@@ -429,11 +431,11 @@
 nightly/GetC.json
 "no_tests"
 nightly/Gettext.json
-"tests_pass"
+"tests_fail"
 nightly/GibbsSeaWater.json
 "tests_pass"
 nightly/GitHub.json
-"tests_pass"
+"tests_fail"
 nightly/GLAbstraction.json
 "not_possible"
 nightly/GLFW.json
@@ -445,9 +447,9 @@
 nightly/Glob.json
 "tests_fail"
 nightly/GLPK.json
-"tests_pass"
+"tests_fail"
 nightly/GLPKMathProgInterface.json
-"tests_pass"
+"tests_fail"
 nightly/GLPlot.json
 "not_possible"
 nightly/GLText.json
@@ -457,7 +459,7 @@
 nightly/GLWindow.json
 "not_possible"
 nightly/GnuTLS.json
-"tests_pass"
+"tests_fail"
 nightly/GoogleCharts.json
 "tests_fail"
 nightly/GradientBoost.json
@@ -467,7 +469,7 @@
 nightly/Graphics.json
 "tests_pass"
 nightly/GraphLayout.json
-"tests_fail"
+"tests_pass"
 nightly/GraphMatrices.json
 "tests_pass"
 nightly/Graphs.json
@@ -479,11 +481,11 @@
 nightly/Grid.json
 "tests_pass"
 nightly/GR.json
-"tests_pass"
+"tests_fail"
 nightly/GSL.json
 "tests_fail"
 nightly/Gtk.json
-"tests_pass"
+"tests_fail"
 nightly/GtkUtilities.json
 "tests_fail"
 nightly/Gumbo.json
@@ -495,7 +497,7 @@
 nightly/Hadamard.json
 "tests_fail"
 nightly/HDF5.json
-"tests_pass"
+"tests_fail"
 nightly/HDFS.json
 "no_tests"
 nightly/Helpme.json
@@ -507,7 +509,7 @@
 nightly/Hiccup.json
 "tests_pass"
 nightly/Hinton.json
-"tests_fail"
+"tests_pass"
 nightly/Homebrew.json
 "not_possible"
 nightly/HopfieldNets.json
@@ -517,11 +519,13 @@
 nightly/HttpCommon.json
 "tests_pass"
 nightly/HttpParser.json
-"tests_pass"
+"tests_fail"
 nightly/HttpServer.json
-"tests_pass"
+"tests_fail"
 nightly/Humanize.json
 "tests_pass"
+nightly/Hwloc.json
+"tests_fail"
 nightly/HyperDualNumbers.json
 "tests_pass"
 nightly/HyperLogLog.json
@@ -539,11 +543,13 @@
 nightly/IJuliaPortrayals.json
 "tests_pass"
 nightly/ImageQuilting.json
-"tests_pass"
+"tests_fail"
 nightly/Images.json
-"tests_pass"
+"tests_fail"
 nightly/ImageView.json
 "tests_fail"
+nightly/Immerse.json
+"tests_fail"
 nightly/ImmutableArrays.json
 "tests_pass"
 nightly/ImplicitEquations.json
@@ -553,7 +559,7 @@
 nightly/IndexedArrays.json
 "tests_pass"
 nightly/InformedDifferentialEvolution.json
-"tests_pass"
+"tests_fail"
 nightly/IniFile.json
 "no_tests"
 nightly/InplaceOps.json
@@ -577,7 +583,7 @@
 nightly/IPNets.json
 "tests_pass"
 nightly/Ipopt.json
-"tests_pass"
+"tests_fail"
 nightly/IPPCore.json
 "no_tests"
 nightly/IPPDSP.json
@@ -597,7 +603,7 @@
 nightly/Jacobi.json
 "tests_pass"
 nightly/Jags.json
-"tests_pass"
+"tests_fail"
 nightly/JavaCall.json
 "tests_pass"
 nightly/JDBC.json
@@ -607,11 +613,11 @@
 nightly/Jewel.json
 "tests_fail"
 nightly/JFVM.json
-"tests_pass"
+"tests_fail"
 nightly/JLDArchives.json
 "tests_fail"
 nightly/JLD.json
-"tests_pass"
+"tests_fail"
 nightly/JointMoments.json
 "tests_pass"
 nightly/JPLEphemeris.json
@@ -621,7 +627,7 @@
 nightly/JudyDicts.json
 "no_tests"
 nightly/JuliaFEM.json
-"tests_pass"
+"tests_fail"
 nightly/JuliaParser.json
 "tests_fail"
 nightly/JulieTest.json
@@ -629,11 +635,11 @@
 nightly/Jumos.json
 "tests_fail"
 nightly/JuMPChance.json
-"tests_pass"
+"tests_fail"
 nightly/JuMPeR.json
-"tests_pass"
+"tests_fail"
 nightly/JuMP.json
-"tests_pass"
+"tests_fail"
 nightly/JWAS.json
 "tests_pass"
 nightly/KDTrees.json
@@ -661,7 +667,7 @@
 nightly/Lasso.json
 "tests_fail"
 nightly/LaTeX.json
-"tests_pass"
+"tests_fail"
 nightly/LaTeXStrings.json
 "tests_pass"
 nightly/Lazy.json
@@ -677,13 +683,13 @@
 nightly/Lexicon.json
 "tests_pass"
 nightly/LibBSON.json
-"tests_pass"
+"tests_fail"
 nightly/LibCURL.json
 "no_tests"
 nightly/LibExpat.json
 "tests_fail"
 nightly/LibGEOS.json
-"tests_pass"
+"tests_fail"
 nightly/LibGit2.json
 "tests_fail"
 nightly/LIBSVM.json
@@ -709,7 +715,7 @@
 nightly/LLLplus.json
 "tests_pass"
 nightly/LMDB.json
-"tests_pass"
+"tests_fail"
 nightly/LNR.json
 "tests_pass"
 nightly/Loess.json
@@ -733,13 +739,13 @@
 nightly/Lumberjack.json
 "tests_fail"
 nightly/Lumira.json
-"tests_fail"
+"tests_pass"
 nightly/MachineLearning.json
 "tests_fail"
 nightly/MacroTools.json
 "tests_pass"
 nightly/Mamba.json
-"tests_pass"
+"tests_fail"
 nightly/ManifoldLearning.json
 "tests_pass"
 nightly/MapLight.json
@@ -749,15 +755,15 @@
 nightly/MarketData.json
 "tests_pass"
 nightly/MarketTechnicals.json
-"tests_fail"
+"tests_pass"
 nightly/Match.json
-"tests_fail"
+"tests_pass"
 nightly/Mathematica.json
 "not_possible"
 nightly/MathProgBase.json
 "tests_fail"
 nightly/MAT.json
-"tests_pass"
+"tests_fail"
 nightly/MATLABCluster.json
 "not_possible"
 nightly/MatlabCompat.json
@@ -765,13 +771,13 @@
 nightly/MATLAB.json
 "not_possible"
 nightly/MatpowerCases.json
-"tests_pass"
+"tests_fail"
 nightly/MatrixDepot.json
 "tests_pass"
 nightly/MatrixMarket.json
 "tests_pass"
 nightly/MbedTLS.json
-"tests_pass"
+"tests_fail"
 nightly/MCMC.json
 "no_tests"
 nightly/MDCT.json
@@ -779,13 +785,13 @@
 nightly/MDPs.json
 "tests_fail"
 nightly/MeCab.json
-"tests_pass"
+"tests_fail"
 nightly/Meddle.json
 "no_tests"
 nightly/Media.json
 "tests_pass"
 nightly/MelGeneralizedCepstrums.json
-"tests_pass"
+"tests_fail"
 nightly/Memcache.json
 "not_possible"
 nightly/Memoize.json
@@ -797,11 +803,11 @@
 nightly/MessageUtils.json
 "tests_fail"
 nightly/MetadataTools.json
-"tests_pass"
+"tests_fail"
 nightly/MetaTools.json
 "no_tests"
 nightly/Metis.json
-"tests_pass"
+"tests_fail"
 nightly/MFCC.json
 "no_tests"
 nightly/Millboard.json
@@ -819,7 +825,7 @@
 nightly/MNIST.json
 "no_tests"
 nightly/Mocha.json
-"tests_pass"
+"tests_fail"
 nightly/ModernGL.json
 "not_possible"
 nightly/MolecularDynamics.json
@@ -857,7 +863,7 @@
 nightly/MutableStrings.json
 "no_tests"
 nightly/Mux.json
-"tests_pass"
+"tests_fail"
 nightly/NaiveBayes.json
 "tests_pass"
 nightly/NamedArrays.json
@@ -875,7 +881,7 @@
 nightly/NetCDF.json
 "tests_fail"
 nightly/Nettle.json
-"tests_pass"
+"tests_fail"
 nightly/NeuralynxNCS.json
 "tests_pass"
 nightly/NFFT.json
@@ -887,7 +893,7 @@
 nightly/NIfTI.json
 "tests_fail"
 nightly/NLopt.json
-"tests_pass"
+"tests_fail"
 nightly/NLreg.json
 "tests_fail"
 nightly/NLsolve.json
@@ -905,7 +911,7 @@
 nightly/NURBS.json
 "tests_fail"
 nightly/OAuth.json
-"tests_pass"
+"tests_fail"
 nightly/OCCA.json
 "tests_fail"
 nightly/ODBC.json
@@ -935,7 +941,7 @@
 nightly/Options.json
 "tests_fail"
 nightly/Orchestra.json
-"tests_pass"
+"tests_fail"
 nightly/OSC.json
 "tests_fail"
 nightly/OSXNotifier.json
@@ -967,7 +973,7 @@
 nightly/Permutations.json
 "tests_pass"
 nightly/PGFPlots.json
-"tests_pass"
+"tests_fail"
 nightly/PGM.json
 "tests_pass"
 nightly/Phylogenetics.json
@@ -984,6 +990,8 @@
 "tests_pass"
 nightly/Plotly.json
 "tests_fail"
+nightly/Plots.json
+"tests_fail"
 nightly/PLX.json
 "tests_fail"
 nightly/PolarFact.json
@@ -997,7 +1005,7 @@
 nightly/PowerSeries.json
 "tests_pass"
 nightly/ProfileView.json
-"tests_pass"
+"tests_fail"
 nightly/ProgressMeter.json
 "tests_pass"
 nightly/ProjectiveDictionaryPairLearning.json
@@ -1017,7 +1025,7 @@
 nightly/PValueAdjust.json
 "tests_pass"
 nightly/PyCall.json
-"tests_pass"
+"tests_fail"
 nightly/PyLexYacc.json
 "not_possible"
 nightly/PyPlot.json
@@ -1069,7 +1077,7 @@
 nightly/REPLCompletions.json
 "not_possible"
 nightly/Requests.json
-"tests_pass"
+"tests_fail"
 nightly/Requires.json
 "tests_pass"
 nightly/Resampling.json
@@ -1079,11 +1087,11 @@
 nightly/ReverseDiffOverload.json
 "no_tests"
 nightly/ReverseDiffSource.json
-"tests_fail"
-nightly/ReverseDiffSparse.json
 "tests_pass"
+nightly/ReverseDiffSparse.json
+"tests_fail"
 nightly/Rif.json
-"tests_pass"
+"tests_fail"
 nightly/RLEVectors.json
 "tests_pass"
 nightly/RNGTest.json
@@ -1097,7 +1105,7 @@
 nightly/Roots.json
 "tests_pass"
 nightly/RouletteWheels.json
-"tests_fail"
+"tests_pass"
 nightly/RudeOil.json
 "not_possible"
 nightly/RunTests.json
@@ -1109,7 +1117,7 @@
 nightly/SaveREPL.json
 "tests_pass"
 nightly/SCS.json
-"tests_pass"
+"tests_fail"
 nightly/SDE.json
 "tests_fail"
 nightly/SDL.json
@@ -1121,7 +1129,7 @@
 nightly/SerialLib.json
 "no_tests"
 nightly/SerialPorts.json
-"tests_pass"
+"tests_fail"
 nightly/SFML.json
 "tests_pass"
 nightly/SGDOptim.json
@@ -1133,9 +1141,9 @@
 nightly/Shannon.json
 "tests_fail"
 nightly/Shapefile.json
-"no_tests"
-nightly/ShapeModels.json
 "tests_pass"
+nightly/ShapeModels.json
+"tests_fail"
 nightly/Showoff.json
 "tests_pass"
 nightly/ShowSet.json
@@ -1171,7 +1179,7 @@
 nightly/SnFFT.json
 "tests_pass"
 nightly/Sobol.json
-"tests_pass"
+"tests_fail"
 nightly/Sodium.json
 "not_possible"
 nightly/SoftConfidenceWeighted.json
@@ -1179,7 +1187,7 @@
 nightly/SolveDSGE.json
 "no_tests"
 nightly/SortingAlgorithms.json
-"tests_pass"
+"tests_fail"
 nightly/Soundex.json
 "no_tests"
 nightly/Sparklines.json
@@ -1195,7 +1203,7 @@
 nightly/StackedNets.json
 "tests_pass"
 nightly/Stan.json
-"tests_pass"
+"tests_fail"
 nightly/StatsBase.json
 "tests_pass"
 nightly/StatsdClient.json
@@ -1221,9 +1229,9 @@
 nightly/Sundials.json
 "tests_fail"
 nightly/SunlightAPIs.json
-"tests_pass"
+"tests_fail"
 nightly/SVM.json
-"tests_pass"
+"tests_fail"
 nightly/SVMLightLoader.json
 "tests_pass"
 nightly/Switch.json
@@ -1233,7 +1241,7 @@
 nightly/Synchrony.json
 "tests_fail"
 nightly/SynthesisFilters.json
-"tests_pass"
+"tests_fail"
 nightly/SystemImageBuilder.json
 "not_possible"
 nightly/Taro.json
@@ -1251,7 +1259,7 @@
 nightly/TermWin.json
 "tests_fail"
 nightly/TestImages.json
-"tests_pass"
+"tests_fail"
 nightly/TexExtensions.json
 "tests_pass"
 nightly/TextAnalysis.json
@@ -1277,7 +1285,7 @@
 nightly/TimeModels.json
 "tests_fail"
 nightly/TimeSeries.json
-"tests_fail"
+"tests_pass"
 nightly/Timestamps.json
 "tests_fail"
 nightly/TimeZones.json
@@ -1333,7 +1341,7 @@
 nightly/Voting.json
 "tests_pass"
 nightly/VStatistic.json
-"tests_pass"
+"tests_fail"
 nightly/Wallace.json
 "no_tests"
 nightly/Watcher.json
@@ -1349,7 +1357,7 @@
 nightly/Weave.json
 "tests_fail"
 nightly/WebSockets.json
-"tests_pass"
+"tests_fail"
 nightly/WinRPM.json
 "no_tests"
 nightly/Winston.json
@@ -1359,7 +1367,7 @@
 nightly/WorldBankData.json
 "tests_pass"
 nightly/WORLD.json
-"tests_pass"
+"tests_fail"
 nightly/WriteVTK.json
 "tests_pass"
 nightly/XClipboard.json
@@ -1375,7 +1383,7 @@
 nightly/Yelp.json
 "tests_fail"
 nightly/Yeppp.json
-"tests_pass"
+"tests_fail"
 nightly/YT.json
 "not_possible"
 nightly/ZChop.json
@@ -1385,6 +1393,6 @@
 nightly/Zlib.json
 "no_tests"
 nightly/ZMQ.json
-"tests_pass"
+"tests_fail"
 nightly/ZVSimulator.json
 "no_tests"
```

Could use some help looking into these.

**Comment by yuyichao** [comment]
`ZMQ` seems to be fine here. Are these by any chance related to the deprecation warnings?

**Comment by tkelman** [comment]
There are lots of those but I would hope not? Many seem to be down to `LoadError: auto_unbox: unable to determine argument type`

**Comment by tkelman** [comment]
Bisect blames 27b5d9af268b837a0c9c09ea991fa04da7de5b7c. `Pkg.build("ZMQ")` can reproduce this for me. You may not be seeing it if you have your local depwarn fix branch of BinDeps checked out?

**Comment by yuyichao** [comment]
Yep, I do have the bindeps fixed version installed, which is the reason for my suspicion

**Comment by tkelman** [comment]
On master of Compat and `yyc/0.4-string` of BinDeps the error goes away. What's going on here?

**Comment by yuyichao** [comment]
Seems that the deprecated binding is not constant?

```jl
julia> f() = Uint
f (generic function with 1 method)

julia> f2() = UInt
f2 (generic function with 1 method)

julia> @code_warntype f()
Variables:

Body:
  begin  # none, line 1:
      return Main.Uint
  end::Any

julia> @code_warntype f2()
Variables:

Body:
  begin  # none, line 1:
      return Main.UInt
  end::Type{UInt64}
```

**Comment by tkelman** [comment]
Yeah looks like 27b5d9af268b837a0c9c09ea991fa04da7de5b7c does remove the `const` from the deprecated bindings. Ouch at how breaking that apparently is. @JeffBezanson can that be put back easily in the `@deprecated_binding` macro?

**Comment by JeffBezanson** [comment]
Oops. Yes, the assignment expression in `deprecate binding` should be wrapped in `Expr(:const, ...)`.

**Pull request merged**
