### PR TITLE
update common_symbols

### PR DESCRIPTION
**Pull request by JeffBezanson**
Shaves about 400k off the system image.

### CODE REVIEW

**Comment by oscardssmith** [comment]
What is the logic behind the reordering?

**Comment by KristofferC** [comment]
I think it is sorted by the count.

**Comment by JeffBezanson** [comment]
Correct. Probably would be good to sort the list in the usual order though; I can add that.

**Comment by oscardssmith** [comment]
It's probably orthogonal, but would it be worth making it so we automatically use the best ordering without having to edit the file when the counts change?

**Comment by JeffBezanson** [comment]
Yes that would be great, it's just a bit of a bother since we'd have to compute the counts and then re-encode each method body while saving a system image.

**Review by KristofferC — APPROVED** [review]

**Pull request merged**
