### PR TITLE
new DFT api

### PR DESCRIPTION
**Pull request by yuyichao**
This is a pure rebase of https://github.com/JuliaLang/julia/pull/12087. The plan is described in https://github.com/JuliaLang/julia/pull/12087#issuecomment-121634342 .

This PR is only for rebasing and getting a full CI run. Will merge after that.

### CODE REVIEW

**Comment by yuyichao** [comment]
I know the AppVeyor has to fail just before I want to merge it. No matter how many times it has passed in a row before that....

So we've got a new pattern in the windows CI failure?

```
ERROR: syntax: invalid escape sequence
jl_uv_writecb() ERROR: broken pipe EPIPE
```

**Comment by ViralBShah** [comment]
Is it ok to ignore appveyor then?

**Comment by yuyichao** [comment]
I'm tempting.

**Comment by yuyichao** [comment]
Looking at the AppVeyor history, it's not like that the freeze hasn't happen on recent commits before this PR so I think I'm going to merge this and give Tony an hour or two to stop me.....

**Comment by tkelman** [comment]
Looks like you restarted it, where was the freeze occurring? If it was the spawn test, yes that still happens intermittently, but it's best to restart the run if the queue's not too long to verify that it's not some new failure mode.

**Comment by yuyichao** [comment]
@tkelman Yes it was freezing after printing the error message I pasted above in the `spawn` test.

**Comment by tkelman** [comment]
Though judging by your comment in #12144 that may have actually been an unrelated warning

**Comment by yuyichao** [comment]
The warning first appears after #12144 and I think is unrelated.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/12144#issuecomment-122535519

**Comment by esd100** [comment]
I'm just curious if you guys have heard of the extended DFT (http://arxiv.org/abs/1303.2033)? After perusing his thesis summary, it sounds like we should be moving toward this type of more accurate math and away from the approximations we would make to reduce total flops or increase the speed of the calculation. It only makes sense in light of the fact that the speed of processors increases by orders of magnitude every few years.

**Comment by pao** [comment]
@esd100 Note that this issue is just about updating the API for the existing functionality, and not adding new DFT features. Even then, that's an open-ended question better suited for mailing list discussion.

**Pull request merged**
