### PR TITLE
add rand(::Type{<:Pair})

### PR DESCRIPTION
**Pull request by rfourquet**
This adds e.g. `rand(Pair{Int,Int})` producing a random pair of `Int`.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do we want this or should we close?

**Comment by rfourquet** [comment]
I still think this is useful and unambiguous as to what this should do. I find this is somewhat similar to #50251 (`rand` for tuple types, which I had actually also planned to implement if this PR `rand(::Type{<:Pair})` was accepted), and I think the decision to merge or not should be the same for both.

**Comment by ViralBShah** [comment]
May I suggest getting them both rebased and marked for triage to consider?

**Comment by rfourquet** [comment]
Now that #50251 is merged, I will also merge this one, as `rand(Tuple{X, Y})` is so similar to `rand(Pair{X, Y})`.

**Comment by fingolfin** [comment]
I believe this broke `RandomExtensions.jl`, see https://github.com/JuliaRandom/RandomExtensions.jl/issues/17

**Pull request merged**
