### PR TITLE
mach: use signal kqueue instead of sigwait

### PR DESCRIPTION
**Pull request by vtjnash**
this may help avoid getting spurious sigwait (InterruptException) notifications

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Probably helps performance too, no?

**Comment by vtjnash** [comment]
probably not

**Comment by StefanKarpinski** [comment]
:sadface:

**Comment by vtjnash** [comment]
> POSIX.1 specifies that the dispositions of any signals that are ignored or set to the default are left unchanged

hm, we're going to have to workaround that before merging

**Comment by iblis17** [comment]
After this PR merged,
All master builds and PR builds failed:
e.g. https://freebsdci.julialang.org/#/builders/1/builds/8043

**Comment by iblis17** [comment]
List of recent builds: https://freebsdci.julialang.org/#/builders/1

**Comment by StefanKarpinski** [comment]
@vtjnash, did you rerun CI across the board before merging this ten months later?

**Pull request merged**
