### PR TITLE
Sets coverage.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Add test for `Base.rehash!(s::Set{T})`.

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Ref: [julia-dev](https://groups.google.com/forum/#!topic/julia-dev/LF7jo1QjWvA)

**Comment by JeffBezanson** [comment]
Thanks for helping with test coverage!

Honestly I'm not sure why there is a `rehash!` method for Set. Maybe we should just remove it?

**Comment by Ismael-VC** [comment]
You are welcome!

I've red about hashing and it's use in associative arrays, but honestly I don't know if
 `Base.rehash!(s::Set{T})` is really useful or not.

 I just want to change those red lines to green at coveralls. :smile:

**Comment by Ismael-VC** [comment]
What I understood was that `rehash!` is issued every time a `Set` grows or shrinks, but since a `Dict` is used internally, it seems to me that that would call [`rehash!(d::Dict{K, V}, newsz)`](https://github.com/JuliaLang/julia/blob/master/base/dict.jl#L606), so I think you are right.

* [cpp reference](http://www.cplusplus.com/reference/unordered_set/unordered_set/rehash/) seems to also have something like this defined for sets. So perhaps there is indeed a use case?

**Comment by Ismael-VC** [comment]
@StefanKarpinski do we actually need `Base.rehash!(s::Set{T})`?, see: https://github.com/JuliaLang/julia/pull/11795#issuecomment-113863210

**Comment by StefanKarpinski** [comment]
No idea. Did I introduce it?

**Comment by StefanKarpinski** [comment]
Oh, wrong ping.

**Comment by yuyichao** [comment]
@StefanKarpinski To be fair, it was `@`ing you in the original version.

**Comment by Ismael-VC** [comment]
It was my mistake, I looked at git blame, and misread by one line the name of the author:

* https://github.com/JuliaLang/julia/blame/master/base/set.jl#L39

Which is why I changed it back. So it seems Steven never got the ping. 

@stevengj could you please give us some insight on this method when yo have the chance?

I'm sorry for the noise.

cheers

**Comment by yuyichao** [comment]
@Ismael-VC That is actually still not the right commit this https://github.com/JuliaLang/julia/commit/e8d47e477dfdce195d5f10e8a5f5b5f271c053e3 is the commit it was introduced and it was by @JeffBezanson .

**Comment by yuyichao** [comment]
Sorry I was also wrong. It was https://github.com/JuliaLang/julia/commit/e7ce4cba44fa3b508fd50e0c3d03f6bc5a7a5032 by @timholy

**Comment by Ismael-VC** [comment]
> Add convenience calls for rehashing

> This is relevant particularly to precompilation, which requires
that any module global dicts get rehashed by the __init__
function.

I think this still stands then.

**Comment by stevengj** [comment]
Yes, it was for precompilation.

**Comment by Ismael-VC** [comment]
Ok! then, is the test good as it is?

**Comment by stevengj** [comment]
I suppose so; I guess there's no way to test `rehash!` without digging into the `Set` internals.

**Comment by StefanKarpinski** [comment]
Bump. Should we go ahead with this?

**Comment by tkelman** [comment]
Looks like this introduced a non-deterministic failure, see #11890. Happens sometimes, so not a big deal, we'll work out what's best to do here while hopefully keeping this method covered for correctness if we can.

**Comment by tkelman** [comment]
should be fixed by https://github.com/JuliaLang/julia/pull/11892

**Pull request merged**
