### PR TITLE
use muladd in horner macro

### PR DESCRIPTION
**Pull request by simonbyrne**
Polynomials should now be able to take advantage of `fma` operations when available (cf. #9840).

cc: @stevengj, @eschnett

### CODE REVIEW

**Comment by ivarne** [comment]
Test failiure:
```
ERROR: LoadError: LoadError: test error in expression: @evalpoly 2 3 4 5 6 == 3 + 2 * (4 + 2 * (5 + 2 * 6)) == @evalpoly 2 + 0im 3 4 5 6
muladd not defined for Int64
while loading math.jl, in expression starting on line 327
while loading /tmp/julia/share/julia/test/runtests.jl, in expression starting on line 42
```
Should we have a default fallback for `muladd(::Number, ::Number, ::Number)`?

**Comment by simonbyrne** [comment]
Yes, there should be a fallback.

**Comment by eschnett** [comment]
The line
```
muladd{T<:Number}(x::T, y::T, z::T) = no_op_err("muladd", T)
```
in `promotion.cl` should instead read
```
muladd{T<:Number}(x::T, y::T, z::T) = x*y+z
```

**Comment by eschnett** [comment]
I have opened #9882 that also adds test cases for `muladd`.

**Comment by stevengj** [comment]
Shouldn't we also use it in `@evalpoly`, which also has multiply-accumulate operations on real operands?  (Except that it has both `$ai * tt + $b` and `$(esc(p[i])) - s * $ai`, where the latter is an `fnma` operation.  Just `muladd` is not enough.)

**Comment by simonbyrne** [comment]
Ah, good point: I forgot about `@evalpoly`.

**Pull request merged**
