### PR TITLE
Bump OpenBLAS_jll to `v0.3.13+5`

### PR DESCRIPTION
**Pull request by staticfloat**
This should fix the illegal instruction errors older processors are
running into.

### CODE REVIEW

**Comment by sethaxen** [comment]
I can confirm that for me this fixes the error in #40361

**Comment by ViralBShah** [comment]
should also regenerate the checksums.

**Comment by staticfloat** [comment]
Who is in charge of these docstrings that are broken?

**Comment by KristofferC** [comment]
> Who is in charge of these docstrings that are broken?

The change in the PR probably changed the result so I guess you will have to update them?

**Comment by ViralBShah** [comment]
The docstrings breakage is really weird. The patch in openblas 0.3.13+4 addressed this and passed there.

@pablosanjose can you take a look?

**Pull request merged**
