### PR TITLE
Benchmark 0.5 vs 0.6 [do not merge]

### PR DESCRIPTION
**Pull request by KristofferC**
Thought it would be a good time to start checking the performance vs 0.5. Easiest to have this in a branch since AFAIK there is no way to run a benchmark between two commits from an issue.

vs 0.5.1:

@nanosoldier `runbenchmarks(ALL, vs = "@6445c82d0060dbe82b88436f0f4371a4ee64d918")`

Note to self, but [ci skip] on the commit for the rebases to come.

### CODE REVIEW

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/20947) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/aee96ad2822bef035f2a1d771d3f5da046f0ece3/9225708_vs_6445c82/report.md). cc @jrevels

**Comment by KristofferC** [comment]
Not bad.

Summary of stuff that got slower:

### Arrays:

* `["array","index",("sumcolon","1.0:1.0:100000.0")]`
* `["array","index",("sumeach_view","BitArray{2}")]`
* `["array","index",("sumlinear_view","BitArray{2}")]`
* `["array","index",("sumrange","1.0:1.0:100000.0")]`
* Some of the concatenations.

### Date accessors in general

For example: `["dates","accessor","millisecond"]`

### Factorizations

For example: `["linalg","factorization",("eig","Matrix",256)]`

### `div` with BigNumbers

### Parallell remotecall

For example `["parallel","remotecall",("identity",2)]`

### Sorting in general

For example `["sort","insertionsort",("sort forwards","ascending")]`

### Sparse indexing

For example `["sparse","index",("spmat","col","array",10)]`

### Other

* `["problem","laplacian","laplace_sparse_matvec"]`
* `["misc","bitshift",("UInt32","UInt32")]`
* `["shootout","revcomp"]`

**Comment by jebej** [comment]
Is it possible to test against 0.4 as well?

**Comment by KristofferC** [comment]
Should be, let's try it!

**Comment by KristofferC** [comment]
vs v0.4.7:

@nanosoldier `runbenchmarks(ALL, vs = "@ae26b25d43317d7dd3ca05f60b70677aab9c0e08")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/20947#issuecomment-285461536):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/56fde8a755eb98c723192e1097c80bb1af1728f7/8a65d50_vs_ae26b25/report.md)
cc @jrevels

**Comment by tkelman** [comment]
probably need an older copy of the saved data for 0.4

**Comment by KristofferC** [comment]
Eeh what? I just rebased this branch and force pushed to it...?

**Comment by yuyichao** [comment]
There's no more commit to merge on this anymore.

**Pull request closed without merging**
