### PR TITLE
Avoid inlining setindex!(::Array, ::Any, ::AbstractVector)

### PR DESCRIPTION
**Pull request by nalimilan**
`@_propagate_inbounds_meta` forces inlining, which may not be desirable
for such complex functions. To avoid this, define a wrapper which will be
inlined, and which will call either the safe or the unsafe method.

Follows a suggestion by @simonster at https://github.com/JuliaLang/julia/pull/20910#issuecomment-287754138. Unfortunately, this makes the code significantly more complex; maybe there's a way to make this slightly cleaner.

FWIW, it turns out that the compiler decides to inline `_unsafe_setindex!` when `@inbounds` is passed, but `_safe_setindex!` remains as a function call.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
What is the impact of this change?

**Comment by nalimilan** [comment]
> What is the impact of this change?

In terms of? The idea is to avoid always inlining `setindex!`, which was the case since #20910.

**Comment by JeffBezanson** [comment]
I mean, why do I care? What is the benefit?

**Comment by nalimilan** [comment]
Well, just like for any relatively large function, inlining makes the code bigger and it's not necessarily a win in terms of performance, so better leave the compiler heuristics decide what to do. I guess you'd better ask @simonster. :-)

**Comment by nalimilan** [comment]
The CI failure is quite obscure and comes from `BitArray`. All tests pass, but the error happens in `make docs`. It can be reproduced with:
```julia
x = ["a"]
x[.!trues(1)]
```
This in turns comes from the fact that `find(.!trues(1))` unexpectedly returns `fill(0, 32)`.

**Comment by nalimilan** [comment]
I've tracked down the failure to the `_broadcast!` specialization for `BitArray`, and most probably to the `dumpbitcache` function it calls. This is very likely due to this known issue: https://github.com/JuliaLang/julia/issues/20065#issuecomment-274153333

**Comment by mbauman** [comment]
This generally seems like the right thing to do — we do something similar for the generic versions in multidimensional.jl.  It's a little unfortunate that it's so complicated and is an exact duplication of that functionality, but I imagine the comment about it being required for bootstrap is still true.

**Comment by mbauman** [comment]
Interestingly, I cannot reproduce that failure on a 9-day old master (a17b1ae on westmere & macOS)

**Comment by nalimilan** [comment]
> It's a little unfortunate that it's so complicated and is an exact duplication of that functionality, but I imagine the comment about it being required for bootstrap is still true.

I've just tried removing them, and indeed bootstrap fails.

> Interestingly, I cannot reproduce that failure on a 9-day old master (a17b1ae on westmere & macOS).

You mean, with the patch from this PR applied? Else it doesn't happen. For some reason, this PR triggers the existing bug in more cases than previously.

**Comment by mbauman** [comment]
> You mean, with the patch from this PR applied? Else it doesn't happen. For some reason, this PR triggers the existing bug in more cases than previously.

Doh, of course.  Sorry for the noise.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21401#issuecomment-294531764) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1760e1b1fec338b12a880d8a48b4b32366e44dc2/518a23a_vs_934e0e3/report.md). cc @jrevels

**Comment by mbauman** [comment]
Is this still relevant after #22210?

**Comment by nalimilan** [comment]
I guess so, since this PR is about avoiding forced inlining, which will allow the compiler to decide whether it's best to inline or not.

**Comment by timholy** [comment]
#22210 didn't, in the end, remove any of the `@inline` annotations in Base. Benchmarks suggest that the vast majority could now be removed, however. I don't have time to tackle this myself, but if someone want to try this the approach I'd recommend is:
- locally build two separate installations of Julia, one for reference (master) and one for the PR
- disable the `@inline` macros in your PR branch (you can rebase branch `teh/disable_inline_macros`)
- run the benchmark suite on both branches and then look for regressions, see https://github.com/JuliaCI/BaseBenchmarks.jl
- go through and delete all the inline annotations from things that don't show up as regressions, re-enable the `@inline` macros
- rerun the Benchmarks and resolve any remaining regressions

**Pull request closed without merging**
