### PR TITLE
added offset to pointer

### PR DESCRIPTION
**Pull request by matbesancon**
Tackles https://github.com/JuliaLang/julia/issues/43056

### CODE REVIEW

**Comment by matbesancon** [comment]
Still haven't figured out a good test for this, apart from the pointer value?

**Comment by matbesancon** [comment]
oh and the test still fails

**Comment by oscardssmith** [comment]
Why do we want this?

**Comment by KristofferC** [comment]
To fix the bug in https://github.com/JuliaLang/julia/issues/43056 (also linked to in this PR).

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/issues/43056 turned out to be invalid

**Pull request closed without merging**
