### PR TITLE
add default keyword constructor for immutables

### PR DESCRIPTION
**Pull request by nolta**
Implements #5333.

### CODE REVIEW

**Comment by mauro3** [comment]
Allowing default values, at least with the obvious syntax, would be a breaking change:
```julia
julia> immutable A
       a=5
       b::Int
       end

julia> names(A)
1-element Array{Symbol,1}:
 :b

julia> immutable B
       a=5
       b::Int
       B() = new(a)
       end

julia> B()
B(5)
```
Although, presumably this feature is not used a lot.  So, I'm all for defaults as well.

**Comment by tkelman** [comment]
Multiple times I have thought default values would work, gotten briefly confused, then frustrated that they don't. Constructors for big types with lots of fields are pretty messy to keep track of at the moment.

**Comment by skariel** [comment]
+1, is this for 0.4, is only the segfault gating?

**Comment by tpapp** [comment]
Is there a chance of having this in 0.4? Sorry for bumping, just thought I would ask since there is no milestone for the PR.

**Comment by tkelman** [comment]
We haven't seen much of @nolta lately. Someone who wants this should try adopting the PR, rebasing and submitting anew.

**Comment by nolta** [comment]
Rebased.

**Comment by damiendr** [comment]
I'd really like to use this feature, but it does not seem to be in the current `master`. I'm not quite sure what the status is after reading the above; is there a stable-ish branch in which it works?

**Comment by mauro3** [comment]
Until this gets merged have a look at https://github.com/mauro3/Parameters.jl.  It should do all of this and more.  Please file an issue with Parameters.jl if something is missing.

**Comment by damiendr** [comment]
@mauro3 Thanks, that looks interesting. My use case is in a hot inner loop though.

**Comment by mauro3** [comment]
Keyword functions are currently not very performant.  I suspect that this PR suffers from that as well.  So you probably have to use the non-keyword constructors for a little longer.  Also, depending you your use-case this may help: https://github.com/StephenVavasis/Modifyfield.jl

**Comment by StefanKarpinski** [comment]
@JeffBezanson's objection to this is that this generates a huge number of methods, which is a lot of overhead for a feature that is only wanted sometimes. My objection was why this only applies to immutables rather than mutables as well. A number of ad hoc implementations of this exist in the package ecosystem, however, so some standard solution seems warranted.

**Comment by StefanKarpinski** [comment]
Also, would be obviated by the feature of putting an immutable in a `Ref` and "mutating" it.

**Comment by tkelman** [comment]
Perhaps we promote one of the package implementations of this to an installed-by-default stdlib? This functionality could cut down a lot of boilerplate in large types for some of the library bindings we have in Base, but most of those should be moved to stdlib modules anyway so adding other stdlib dependencies to them would be okay.

**Comment by mauro3** [comment]
One of them: https://github.com/mauro3/Parameters.jl.

**Comment by StefanKarpinski** [comment]
Is this really necessarily 2.0 or can this be added in a non-breaking way in a 1.x release?

**Comment by gbaraldi** [comment]
Do we want this in base, this seems very much what https://github.com/JuliaObjects/Accessors.jl seems to do.

**Comment by vtjnash** [comment]
Base now has `@kwdef`, which I guess pretty much replaces this

**Pull request closed without merging**
