### PR TITLE
Rename internal reduced_dims->reduced_indices to reflect new output type

### PR DESCRIPTION
**Pull request by timholy**
This may also make backporting to julia-0.5 safer. Ref https://github.com/JuliaLang/julia/pull/19100#issuecomment-256087668.

### CODE REVIEW

**Comment by timholy** [comment]
I've verified that this gives a deprecation warning (rather than error) even in cases where it was getting called as `Base.reduced_dims(A, region)`, so this should be safer than what we have now.

**Comment by timholy** [comment]
Any comments, or should I hit merge?

**Comment by tkelman** [comment]
This appears to have caused a new failure with BlackBoxOptim.jl http://pkg.julialang.org/logs/BlackBoxOptim_0.6.log

```
MethodError: no method matching reduced_dims(::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}, ::Int64)
Closest candidates are:
  reduced_dims(!Matched::Tuple{}, ::Int64) at deprecated.jl:1042
  reduced_dims(!Matched::Tuple{}, ::Any) at deprecated.jl:1045
  reduced_dims(!Matched::Tuple{Vararg{Int64,N}}, ::Any) at deprecated.jl:1047
  ...
 in reduced_dims(::Tuple{Int64,Int64}, ::Int64) at ./deprecated.jl:1048
 in wsum(::Array{Float64,2}, ::Array{Float64,1}, ::Int64) at /home/vagrant/.julia/v0.6/StatsBase/src/weights.jl:240
 in tell!(::BlackBoxOptim.DXNESOpt{Float64,BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}, ::Array{BlackBoxOptim.Candidate{Float64},1}) at /home/vagrant/.julia/v0.6/BlackBoxOptim/src/dx_nes.jl:107
 in run!(::BlackBoxOptim.OptRunController{BlackBoxOptim.DXNESOpt{Float64,BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}},BlackBoxOptim.ProblemEvaluator{Float64,Float64,BlackBoxOptim.TopListArchive{Float64,BlackBoxOptim.ScalarFitnessScheme{true}},BlackBoxOptim.FunctionBasedProblem{BlackBoxOptim.ScalarFitnessScheme{true},BlackBoxOptim.RangePerDimSearchSpace,Void}}}) at /home/vagrant/.julia/v0.6/BlackBoxOptim/src/opt_controller.jl:280
 in run!(::BlackBoxOptim.OptController{BlackBoxOptim.DXNESOpt{Float64,BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}},BlackBoxOptim.FunctionBasedProblem{BlackBoxOptim.ScalarFitnessScheme{true},BlackBoxOptim.RangePerDimSearchSpace,Void}}) at /home/vagrant/.julia/v0.6/BlackBoxOptim/src/opt_controller.jl:410
 in (::##2862#2867{#rosenbrock#2864,#schaffer1#2865})() at /home/vagrant/.julia/v0.6/BlackBoxOptim/test/test_tracing.jl:12
 in context(::##2862#2867{#rosenbrock#2864,#schaffer1#2865}, ::String) at /home/vagrant/.julia/v0.6/FactCheck/src/FactCheck.jl:475
 in (::##2861#2866{#rosenbrock#2864,#schaffer1#2865})() at /home/vagrant/.julia/v0.6/BlackBoxOptim/test/test_tracing.jl:7
 in context(::##2861#2866{#rosenbrock#2864,#schaffer1#2865}, ::String) at /home/vagrant/.julia/v0.6/FactCheck/src/FactCheck.jl:475
 in facts(::##2860#2863, ::String) at /home/vagrant/.julia/v0.6/FactCheck/src/FactCheck.jl:449
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in macro expansion; at /home/vagrant/.julia/v0.6/BlackBoxOptim/test/runtests.jl:41 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
 in process_options(::Base.JLOptions) at ./client.jl:271
 in _start() at ./client.jl:335
while loading /home/vagrant/.julia/v0.6/BlackBoxOptim/test/test_tracing.jl, in expression starting on line 1
while loading /home/vagrant/.julia/v0.6/BlackBoxOptim/test/runtests.jl, in expression starting on line 40
```

**Comment by timholy** [comment]
Ugh. So much for nonbreaking. Fix coming, and to atone I'll also submit a `StatsBase` PR to fix the deprecation warnings (once my fix to julia base merges).

**Pull request merged**
