### PR TITLE
Allows the results of `mapfoldr` to be inferred on tuples.

### PR DESCRIPTION
**Pull request by tpapp**
This solution was [suggested](https://discourse.julialang.org/t/mapfoldr-and-inference-on-tuple/28657/2) by @tkf.

### CODE REVIEW

**Review by stevengj — APPROVED** [review]

**Comment by tpapp** [comment]
Could this be merged?

**Comment by StefanKarpinski** [comment]
Bump. I'm inclined to just merge this and revert if anyone starts shouting.

**Comment by tkf** [comment]
> I'm inclined to just merge this and revert if anyone starts shouting.

I didn't want to be the one to start shouting but I think it might be better to undo this API change before 1.4. See: #34732

**Comment by tpapp** [comment]
It would be great if the PR reverting this could preserve the functionality, ie allow `mapfoldr` to be inferred.

**Comment by tkf** [comment]
#34732 passes the test you added.

**Pull request merged**
