### PR TITLE
[release-0.6] final backports for 0.6.0

### PR DESCRIPTION
**Pull request by tkelman**
- [x] pkgeval
- [x] @nanosoldier `runbenchmarks(ALL, vs = ":release-0.6")` vs rc3
- [x] fix appveyor
- [ ] build:dog:

#jlbuild !nuke
```
Base.runtests()
Base.runtests("pkg libgit2-online download")
```

### CODE REVIEW

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/a93d4a49946ef227d1c7cc36432fd615facaedff

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/a93d4a49946ef227d1c7cc36432fd615facaedff

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/eafaae7a3a6724940dc24e652fc2aeff0a207ec9

I will edit this comment as the build jobs complete.

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/fe65eb478205dcdc9870bcf51de180533c4d84c8

I will edit this comment as the build jobs complete.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-0.6")` vs rc3

**Comment by jlbuild** [comment]
Got it, building https://github.com/JuliaLang/julia/commit/fe65eb478205dcdc9870bcf51de180533c4d84c8

I will edit this comment as the build jobs complete.

**Comment by tkelman** [comment]
@staticfloat something's bugged about your comment listener - why aren't you using the same code as Nanosoldier for that?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22398) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/43228bb2406f8ea3fd887e6b65ce8556849602ef/d853641_vs_ad290e9/report.md). cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22398#issuecomment-309186736) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c017680ce7be1dfff9f4b9afc60abec6fb60a1cc/cb5eb30_vs_ad290e9/report.md). cc @jrevels

**Comment by tkelman** [comment]
Can anyone reproduce the osx travis failure from https://travis-ci.org/JuliaLang/julia/jobs/243890261 locally?

**Comment by tkelman** [comment]
pkgeval results: https://gist.github.com/884ea61bca336f6850a8746b240e5ea7
2 regressions worth looking into and bisecting, CategoricalArrays (cc @nalimilan) and ReverseDiff (cc @jrevels)

**Comment by tkelman** [comment]
@JeffBezanson 25d8c3a00948a90a582cfa918b5660f6426870f5 (backport of #22343) broke CategoricalArrays - will probably revert and re-run pkgeval for now unless anyone has any immediate ideas (@vtjnash @yuyichao maybe?)

**Comment by tkelman** [comment]
comparing the same commit on release julia vs debug julia, the situation looks much better than https://github.com/JuliaLang/julia/issues/22158#issuecomment-307664012 (though note that the commits that fixed this may have been the ones responsible for the ReverseDiff and CategoricalArrays regressions), down to single-digit number of assertion failures

https://gist.github.com/5d223c7e5cb7620514b072ef752ad9b5

**Comment by tkelman** [comment]
bisect results point to the exact same commit as breaking ReverseDiff

**Comment by tkelman** [comment]
both CategoricalArrays and ReverseDiff are also broken on master of Julia, FWIW

**Comment by timholy** [comment]
I'm not sure reverting the specificity fix is the right plan here. It should be asked whether ReverseDiff is currently depending on broken method specificity; if so, it would be far better to address by fixing the package. (If you back this out, then you'll bring back segfaults in Gtk, for example.)

**Comment by nalimilan** [comment]
Regarding CategoricalArrays, the problem is that `convert{S, R}(::Type{CategoricalPool{S, R}}, pool::CategoricalPool)` is considered as more specific than `convert{T, R}(::Type{CategoricalPool{T, R}}, pool::CategoricalPool{T, R})`. Even if I define `convert{T, R, V}(::Type{CategoricalPool{T, R, V}}, pool::CategoricalPool{T, R, V})`, the first method is used.

**Comment by tkelman** [comment]
I'll leave the commit in if anyone can get fixes merged and tagged in both packages in the next ~12 hrs. Otherwise it'll wait until 0.6.1 (assuming those packages can be fixed by then).

**Comment by timholy** [comment]
@nalimilan,

> the problem is that convert{S, R}(::Type{CategoricalPool{S, R}}, pool::CategoricalPool) is considered as more specific than convert{T, R}(::Type{CategoricalPool{T, R}}, pool::CategoricalPool{T, R}).

That's weird. That's not what I get if I just make something up:
```julia
julia> immutable CategoricalPool{T,R}
           x::T
           y::R
       end

julia> Base.convert(::Type{CategoricalPool{T,R}}, pool::CategoricalPool{T,R}) where {T, R} = pool

julia> Base.convert(::Type{CategoricalPool{T,R}}, pool::CategoricalPool) where {T, R} = CategoricalPool{T,R}(pool.x, pool.y)

julia> mths = collect(methods(convert));

julia> filter(m->(Base.unwrap_unionall(m.sig).parameters[3]) <: CategoricalPool, mths)
2-element Array{Any,1}:
 convert(::Type{CategoricalPool{T,R}}, pool::CategoricalPool{T,R}) where {T, R} in Main at REPL[3]:1
 convert(::Type{CategoricalPool{T,R}}, pool::CategoricalPool) where {T, R} in Main at REPL[4]:1     
```

**Comment by timholy** [comment]
Oh wait, sorry, that was a different specificity fix than I was thinking it was. Testing now.

**Comment by timholy** [comment]
https://github.com/JuliaData/CategoricalArrays.jl/pull/71

I am skeptical that I can fix ReverseDiff; might need @jrevels.

**Comment by tkelman** [comment]
took out the reversion since https://github.com/JuliaDiff/ReverseDiff.jl/pull/75 should fix ReverseDiff

**Comment by KristofferC** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/513 would be nice to get in.

**Comment by tkelman** [comment]
would be, if it were ready. can wait until 0.6.1

**Comment by jebej** [comment]
What about #22183 / #21693? This bug will silently give a wrong result when adding sparse matrices...

**Comment by StefanKarpinski** [comment]
When someone (you, maybe?) fixes it, it will go into 0.6.1, which can happen any time we want (no need to wait a full month if there are significant bug fixes like this).

**Comment by jebej** [comment]
I understand. Hopefully most people won't run into this.

**Comment by staticfloat** [comment]
> @staticfloat something's bugged about your comment listener - why aren't you using the same code as Nanosoldier for that?

In large part I am, I'm using `GitHub.jl`, but I want to listen for more than just plain comments (e.g. I want to respond to opened issues, etc...) and I hadn't properly filtered out things like labeling issues, so if you had put a `@jlbuild` within the original issue text, then labeled/unlabeled an issue, the buildog would go mad.  I've fixed this now to be much more strict (only the `created` and `opened` actions will be listened to now) so hopefully that will be much more tolerable.

**Pull request merged**
