### PR TITLE
use 5 chars for loading slugs

### PR DESCRIPTION
**Pull request by KristofferC**
Will require a `pkg> gc` to clean up all old packages and will require a reinstall of them.

Fixes https://github.com/JuliaLang/julia/issues/27577

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
The thing I was thinking of doing was looking for any prefix of the "full slug" and using any prefix that exists, which would allow smoothly changing from 4 to 6 or even higher while still picking up older ones.

**Comment by KristofferC** [comment]
That's s possible way to avoid people having to reinstall things.

**Comment by KristofferC** [comment]
Bump, do you want to finish this @StefanKarpinski. Would be nice to not have https://github.com/JuliaLang/julia/issues/27577 in RC.

**Comment by StefanKarpinski** [comment]
Yes, but I think we should do 5-char slugs because the 6th digit is pretty much garbage since 62^6 = 56,800,235,584 is much larger than 2^32 = 4,294,967,29 and we're using CRC32 to generate slugs. I think we can just skip doing anything fancy here since `pkg> gc` will clean up the old slugs.

**Comment by KristofferC** [comment]
The only problem is that it will force everyone to reinstall and rebuild their packages. So create it is easy enough to look for the 4 char path first, I would suggest we do that.

**Comment by StefanKarpinski** [comment]
> So create it is easy enough to look for the 4 char path first, I would suggest we do that.

It's kind of a pain and I've got too many other things I gotta get done 😐

**Comment by KristofferC** [comment]
I'll try do it then. The time to do it is likely less than answering all the discourse posts about where their packages went.

**Comment by KristofferC** [comment]
@StefanKarpinski I fixed it but there are hard-coded 4 char slug paths in the tests (e.g. `test/depot/packages/Foo/I05Q/src/Foo.jl`). Could you regenerate those (they needed to be regenerated even if we didn't keep the fallback to 4 chars).

**Review by StefanKarpinski — APPROVED** [review]

**Comment by KristofferC** [comment]
Wait, how did this pass? It failed locally due to precompilation paths in `test`...

**Comment by StefanKarpinski** [comment]
Does the merge commit with master work?

**Comment by StefanKarpinski** [comment]
Oh, you put `[ci skip]` in the commit message 😂

**Comment by StefanKarpinski** [comment]
I'll fix those paths.

**Comment by KristofferC** [comment]
Oh yeah! Because I knew it would fail :D

**Comment by StefanKarpinski** [comment]
Hilarious... Glad we figured that out 😹

**Pull request merged**
