### PR TITLE
Test libcurl update

### PR DESCRIPTION
**Pull request by vchuravy**
To test https://github.com/JuliaWeb/LibCURL.jl/pull/95

### CODE REVIEW

**Comment by vchuravy** [comment]
I assume there will be an auto-update?

**Comment by StefanKarpinski** [comment]
@DilumAluthge?

**Comment by DilumAluthge** [comment]
I didn't put BumpStdlibs on a cron b/c I wasn't sure if that was desirable.

To trigger a bump you just go to https://juliapackaging.github.io/BumpStdlibs.jl/dev/usage/ and follow the steps.

Anyway I just triggered the bump; should open a PR soon.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/38651

**Pull request closed without merging**
