### PR TITLE
Use a gensym to store doc metadata

### PR DESCRIPTION
**Pull request by MikeInnes**
Proposed fix for #11974. Would a constant symbol like `__META__` buy us anything over this approach?

### CODE REVIEW

**Comment by ScottPJones** [comment]
Could you use `__META__` instead of `META'`? (but otherwise keep it like you have)
Calling something blah prime is something that mathematicians would get, but not general programmers, and the use of a single quote in an identifier is sure to leave some people scratching their heads.

**Comment by one-more-minute** [comment]
Possibly, but this is very much an implementation detail that people in general aren't going to look at.

The name of the actual meta dict in your module is going to be called something like `##META#2538`, which is equally likely to make the general programmer scratch their head if they come across it (as with many other implementation details). But we're not really optimising for programmer surprise here because it's not user-level.

**Comment by one-more-minute** [comment]
(In fact, we sort of are optimising for user surprise here – it's as surprising as is reasonably possible exactly so that people *don't* come across it by accident).

**Comment by MichaelHatherly** [comment]
(Whoops, totally forgot to go and implement this after opening #11974... sorry about that.)

Re: using a ``gensym`` rather than just an underscored name change, +1.

**Comment by ScottPJones** [comment]
>Possibly, but this is very much an implementation detail that people in general aren't going to look at.

Well, I saw it, and scratched my head!   Is the META' name not saved anywhere then?
I still think not using single quotes in identifiers is a good thing.

**Comment by StefanKarpinski** [comment]
How about we just call the constant in every module `__META__` instead of doing the gensym thing. I'd prefer to know what the name is and have it be a reserved name (i.e. of the form `__xxx__`).

**Comment by one-more-minute** [comment]
Sure, I'm completely OK with that too.

**Comment by ScottPJones** [comment]
I hope you do keep the meta function, that is precisely what's being talked about elsewhere, as being more Julian than accessing a field.

**Comment by one-more-minute** [comment]
Done in 4fc9bb63deed183d3124581445f1f3522a04dc47

**Comment by MichaelHatherly** [comment]
What should the official interface for getting at the metadata be then? ``Docs.meta(MyMod)`` or ``MyMod.__META__``?

**Pull request merged**
