### PR TITLE
Improve error when generated function is not pure

### PR DESCRIPTION
**Pull request by nalimilan**
I hadn't realized that this included generators so it could help others.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
Need to fix the test, but SGTM

**Comment by nalimilan** [comment]
Damn, I should have know that even seemingly trivial changes require running the tests... :-D

(CI doctest failure looks unrelated.)

**Review by Sacha0 — APPROVED** [review]

**Comment by vtjnash** [comment]
This likely should have been squashed on merge (and fix the commit message), since the intermediate commits do not build

**Comment by nalimilan** [comment]
That's what I did, didn't I? :-/

**Comment by vtjnash** [comment]
Ah, sorry, yes you did. My apologies. I wish Github would show status descriptions more accurately

**Pull request merged**
