### PR TITLE
Use `require(pkgid, ...)` instead of relative require

### LINKED ISSUE #29234: Julia fails to launch when stdin is a TCP Socket
I've tried to run Julia with `blaunch` (a tool to run parallel tasks on a cluster which uses [Spectrum LSF](https://www.ibm.com/us-en/marketplace/hpc-workload-management)).

When trying this, I run in to this error before any of my code can run:
```
fatal: error thrown and no exception handler available.
InitError(mod=:Base, error=ArgumentError(msg="Package Sockets not found in current path:
- Run `Pkg.add("Sockets")` to install the Sockets package.
"))
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:246
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:577
require at ./loading.jl:817
init_stdio at ./stream.jl:237
jfptr_init_stdio_4446.clone_1 at /julia/lib/julia/sys.so (unknown line)
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
reinit_stdio at ./libuv.jl:120
__init__ at ./sysimg.jl:470
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1536 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linux64/build/src/toplevel.c:90
_julia_init at /buildworker/worker/package_linux64/build/src/init.c:811
julia_init__threading at /buildworker/worker/package_linux64/build/src/task.c:302
main at /buildworker/worker/package_linux64/build/ui/repl.c:227
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at /julia/bin/julia (unknown line)
```

I tracked it down to the function `init_stdio` where the Sockets module is loaded. But at this point the LOAD_PATH and DEPOT_PATH haven't been set, so the module is not found.

In order to fix this, I have modified `__init__()` in `base/sysimg.jl` to initialise the LOAD_PATH and DEPOT_PATH before initialising IO.

I'm not sure if this is the best way to fix this, so I haven't done a merge request yet.

### PR DESCRIPTION
**Pull request by vchuravy**
Should fix #29234 and supersedes #29252

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
add test that `JULIA_PROJECT= ./julia -p 1` works?

**Comment by bjarthur** [comment]
how about a 1.0.x label?  would be really nice to have this in 1.0.2.  thanks!

**Comment by vchuravy** [comment]
Does anyone have a good test for this? `JULIA_PROJECT= ./julia -p 1` is not sufficient, and my attempts launching through ssh didn't suffice either. Maybe @jameshclrk or @bjarthur?

**Comment by vchuravy** [comment]
The error here seems unrelated, but also quite odd on both Win32 and Linux32 we are getting an error the BigInt is an undefined variable.

```
record_backtrace at /cygdrive/c/projects/julia/src\task.c:217
jl_throw at /cygdrive/c/projects/julia/src\task.c:410
jl_undefined_var_error at /cygdrive/c/projects/julia/src\rtutils.c:129
jl_get_binding_or_error at /cygdrive/c/projects/julia/src\module.c:290
div at .\int.jl:774
tryparse_internal at .\parse.jl:110
#parse#330 at .\parse.jl:225
unknown function (ip: 0762F579)
jl_fptr_trampoline at /cygdrive/c/projects/julia/src\gf.c:1843
jl_apply_generic at /cygdrive/c/projects/julia/src\gf.c:2198 [inlined]
jl_apply at /cygdrive/c/projects/julia/src\julia.h:1560 [inlined]
jl_invoke at /cygdrive/c/projects/julia/src\gf.c:56
parse at .\parse.jl:225
unknown function (ip: 0762F263)
jl_fptr_trampoline at /cygdrive/c/projects/julia/src\gf.c:1843
jl_apply_generic at /cygdrive/c/projects/julia/src\gf.c:2198
@uint128_str at .\int.jl:575
jl_fptr_args at /cygdrive/c/projects/julia/src\gf.c:1853
jl_fptr_trampoline at /cygdrive/c/projects/julia/src\gf.c:1843
jl_invoke_julia_macro at /cygdrive/c/projects/julia/src\ast.c:1030
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1092
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_expand_macros at /cygdrive/c/projects/julia/src\ast.c:1135
jl_parse_eval_all at /cygdrive/c/projects/julia/src\ast.c:865
jl_load at /cygdrive/c/projects/julia/src\toplevel.c:834 [inlined]
jl_load_ at /cygdrive/c/projects/julia/src\toplevel.c:841
jl_get_ptls_states at /cygdrive/c/projects/julia/src\threading.c:131
include at .\sysimg.jl:36
jl_fptr_args at /cygdrive/c/projects/julia/src\gf.c:1853
jl_apply_generic at /cygdrive/c/projects/julia/src\gf.c:2198
do_call at /cygdrive/c/projects/julia/src\interpreter.c:323
eval_value at /cygdrive/c/projects/julia/src\interpreter.c:411
eval_stmt_value at /cygdrive/c/projects/julia/src\interpreter.c:362 [inlined]
eval_body at /cygdrive/c/projects/julia/src\interpreter.c:754
jl_interpret_toplevel_thunk_callback at /cygdrive/c/projects/julia/src\interpreter.c:880
unknown function (ip: FFFFFFFE)
unknown function (ip: 0352FA2F)
unknown function (ip: FFFFFFFF)
jl_interpret_toplevel_thunk at /cygdrive/c/projects/julia/src\interpreter.c:889
jl_toplevel_eval_flex at /cygdrive/c/projects/julia/src\toplevel.c:772
jl_eval_module_expr at /cygdrive/c/projects/julia/src\toplevel.c:180
jl_toplevel_eval_flex at /cygdrive/c/projects/julia/src\toplevel.c:610
jl_parse_eval_all at /cygdrive/c/projects/julia/src\ast.c:881
jl_load at /cygdrive/c/projects/julia/src\toplevel.c:834
exec_program at /cygdrive/c/projects/julia/ui\repl.c:36
true_main at /cygdrive/c/projects/julia/ui\repl.c:124
wmain at /cygdrive/c/projects/julia/ui\repl.c:233
__tmainCRTStartup at /usr/src/debug/mingw64-i686-runtime-5.0.4-1/crt\crtexe.c:329
BaseThreadInitThunk at C:\windows\SYSTEM32\KERNEL32.DLL (unknown line)
RtlInitializeExceptionChain at C:\windows\SYSTEM32\ntdll.dll (unknown line)
RtlInitializeExceptionChain at C:\windows\SYSTEM32\ntdll.dll (unknown line)
LoadError("sysimg.jl", 330, LoadError("stream.jl", 219, LoadError("<macrocall>", 0, UndefVarError(:BigInt))))
```

**Comment by jameshclrk** [comment]
This is the most minimal test case I've found to trigger the missing Sockets package bug.

```bash
$ nc -l 12345 &
$ exec 3<>/dev/tcp/localhost/12345
$ ./julia <&3
```
julia 1.0.0 and 1.0.1 crash and with this pull request they don't crash.

However, if/when julia successfully initialises, the program will wait for input from the port nc is listening on. To work around this I came up with:

```bash
$ timeout 5 nc -l 12345 &
$ exec 3<>/dev/tcp/localhost/12345
$ ./julia <&3
```

I'm not sure of your test environment, but this needs a netcat implementation, timeout (in coreutils) and bash compiled with "--enable-net-redirections".

**Comment by bjarthur** [comment]
a colleague wants to switch from matlab to julia precisely because of the latter's advertised ability to distribute remote jobs on a cluster.   am i really going to have to tell him "that julia 1.0 does not support remote jobs yet.  you'll have to either use 0.6.4, or compile julia yourself after having cherry picked this commit." ?

**Comment by vchuravy** [comment]
@bjarthur Comments like this are not productive, and do not make it more likely for me or someone else to do something.

@jameshclrk Thanks!

```bash
timeout 5 nc -l 12345 &
exec 3<>/dev/tcp/localhost/12345
./julia -e "exit()" -i <&3
```

Seems to do what I want.  I was trying to make `run(pipeline(`julia -e "exit()" -i`, stdin=TCPSocket()))` work but I get a `EINVAL` from that. @vtjnash Do you have an idea how to write this in pure Julia? I should note that the scipt above requires obenbsd netcat, and gnu netcat doesn't work, so I am hesitant to add a new dependency for this test.

**Comment by vtjnash** [comment]
`TCPSocket()` -- you need to initialize this socket (perhaps use `uv_socketpair`)

**Comment by bjarthur** [comment]
sorry.  i could've worded that better.  but i thought it would be good for the core developers to know the feedback i'm getting about the 1.0 release.  i get tired of having to explain that in julia-land, 1.0 just means a feature freeze, and not that everything works.  people just don't get it, because nothing else works that way.

at any rate, thanks for working on this.  it's way beyond my familiarity with base.  i look forward to introducing this colleague to julia once it lands.

**Comment by jameshclrk** [comment]
> `run(pipeline(`julia -e "exit()" -i`, stdin=TCPSocket()))`

You got it! If you call TCPSocket() with delay=false, it causes the crash.

```
julia> run(pipeline(`julia -e "exit()" -i`, stdin=TCPSocket(delay=false)))
fatal: error thrown and no exception handler available.
InitError(mod=:Base, error=ArgumentError(msg="Package Sockets not found in current path:
- Run `Pkg.add("Sockets")` to install the Sockets package.
"))
...
```

**Comment by vchuravy** [comment]
Ok, this should be good to go and I will merge once CI is green.

**Pull request merged**
