### PR TITLE
WIP: Staged functions

### PR DESCRIPTION
**Pull request by Keno**
This is my work in progress for staged functions (#7311). It almost works, but there's a few things left to discuss. 
- [ ] Syntax: @StefanKarpinski hates `stagedfunction foo(); end`. @JeffBezanson proposed `staged foo(); end`, though there's the question if we want to reserve that keyword
- [ ] Caching. E.g. consider the following:

```
julia> stagedfunction foo(a,b)
       println(a,b)
       :(a+b)
       end

julia> foo(1,2)
Int64Int64
3

julia> foo(1,2)
3

julia> bar() = foo(1,2)
bar (generic function with 1 method)

julia> bar()
Int64Int64
Int64Int64
3

julia> bar()
3

julia> baz() = foo(1,2)
baz (generic function with 1 method)

julia> baz()
Int64Int64
Int64Int64
3
```

Hopefully calling the staged function that many times can be avoided. In any case, this point isn't critical. 
- [x] Staged functions throwing errors. I'm not handling this yet. In the runtime case this mostly works already, but for type inference we need to intercept and return Any/NF.
- [ ] Documentation

Thanks to @timholy and @jakebolewski for hacking on this with me on Saturday.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Why not document it with the current name, and then just update the documentation with the name change? I think a lot of people want to use staged functions and learn about them (on master), but going through the issues is a bit cumbersome for many.

**Comment by aviks** [comment]
>Why not document it with the current name, and then just update the documentation with the name change

I realise this is more work, and I am in no position to help, but I (an I'm sure many others) would really appreciate something on those lines. Maybe a even a gist with some docs and examples?

**Comment by timholy** [comment]
I also confess some reluctance before #8504 gets fixed---it's a nasty problem, and it's holding even me back from using stagedfunctions more pervasively.

But, let's go for it and see what happens. If nothing else it might be more incentive to at least get some discussion about [my proposed fix](https://github.com/JuliaLang/julia/issues/8504#issuecomment-64091974).

**Comment by tonyhffong** [comment]
I wonder if we should treat function-typed argument differently in a stagedfunction. When testing types, we most likely want to do `method_exists` or even `code_typed` to see if the function supports the input/output signature in the staging phase. Having just `Function` at this stage isn't that helpful.

**Comment by timholy** [comment]
It's an interesting idea. Can you expand on your goal, why checking the signature during staging is better than just trying it and seeing what error you get?

But one point is that in principle your suggestion could provide a mechanism for "function-valued argument inlining" (#3440 and perhaps #1864).

**Comment by tonyhffong** [comment]
I'm playing with the idea of Functors and Monads using Traits.jl and notice the ideas are not trivial. (PR# https://github.com/mauro3/Traits.jl/pull/4#issuecomment-69162484). I was trying to see if I can generate associated types with the package. Let's take Functor. A Functor must support a fmap function. In Haskell it imposes that `fmap :: (a->b) -> f a -> f b`. So we would write something like this:
```julia
using Traits

immutable FuncFullSig{TI, TO}
    f::Function
end

@traitdef Functor{X{Y}} begin
    fmap( FuncFullSig{Y,Z}, X{Y} ) -> X{Z}
end
```
So when we do
```julia
a = Float64[1.0,2.0] # assume we assert Array is a Functor
b = fmap( FuncFullSig{Float64,Float64}( sin ), a ) # b should be provably Array{Float64}
```
It would do away with many boilerplate codes, as many types are just Functors in disguise (Nullable, Associative{K}, DataArray, etc.) . But writing `FuncFullSig` is a bit cumbersome. It would be really nice, when we do just
`b = fmap( sin, c )`,
an intermediate step happens that does this
* ask if  `typeof(c)` is a Functor? (already do-able now with Traits.jl)
* if so, check if the method `sin( x::T )` exists? (`T` is the Functor parameter of `typeof(c)`)
* (bonus) provide type inference info that b must be a Functor of the result type

Ideally, all these would be better done only once per (Function, ArgTypes...) tuple, or the performance penalty would be massive. Stagedfunction would be an interesting place to put it, but
we are in a strange place right now, when we only know the types of arguments but not the signatures of function arguments, a challenge that is a by-product of julia's multiple-dispatch feature. (Ironically, multiple-dispatch is exactly what makes Traits.jl work.)

**Pull request merged**
