### PR TITLE
Set default for USE_BLAS64 to 0 when using non MKL system BLAS

### LINKED ISSUE #10457: Change default setting to `USE_BLAS64=0` when `USE_SYSTEM_BLAS==1`
Building Julia 0.3.6 from the latest release tarball with `USE_SYSTEM_BLAS=1` and `USE_SYSTEM_LAPACK=1` (among others) the test do not pass:

~~~~ 
   JULIA test/all
	From worker 3:	     * linalg2
	From worker 5:	     * linalg4
	From worker 2:	     * linalg1
	From worker 6:	     * linalg/cholmod
	From worker 7:	     * linalg/umfpack
	From worker 9:	     * keywordargs
	From worker 4:	     * linalg3
	From worker 8:	     * core
	From worker 6:	     * numbers
	From worker 9:	     * strings
exception on 4: ERROR: argument is not a permutation
 in invperm at ./combinatorics.jl:177
 in A_ldiv_B! at ./linalg/factorization.jl:413
 in A_ldiv_B! at ./linalg/factorization.jl:417
 in \ at ./linalg/factorization.jl:484
 in \ at ./linalg/dense.jl:417
 in anonymous at ./no file:9
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg3.jl, in expression starting on line 4
exception on 7: ERROR: assertion failed: |det(lua) - det(full(A))| <= 1.4210854715202004e-10
  det(lua) = 114.00000000000003
  det(full(A)) = -114.0
  difference = 228.00000000000003 > 1.4210854715202004e-10
 in error at ./error.jl:22
 in test_approx_eq at ./test.jl:109
 in anonymous at ./no file:22
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg/umfpack.jl, in expression starting on line 13
exception on 5: ERROR: ArgumentError("invalid argument #4294967296 to LAPACK call")
 in trtrs! at ./linalg/lapack.jl:1954
 in A_ldiv_B! at ./linalg/triangular.jl:47
 in \ at ./linalg/triangular.jl:49
 in \ at ./linalg/dense.jl:415
 in anonymous at ./no file:46
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg4.jl, in expression starting on line 29
exception on 2: ERROR: BoundsError()
 in ipiv2perm at ./linalg/lu.jl:87
 in getindex at ./linalg/lu.jl:99
 in cond at ./linalg/lu.jl:151
 in cond at ./linalg/dense.jl:451
 in anonymous at ./no file:12
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg1.jl, in expression starting on line 9
exception on 3: ERROR: assertion failed: |det(T) - det(F)| <= 0.0095367431640625
  det(T) = 8.618331
  det(F) = 0.0
  difference = 8.618331 > 0.0095367431640625
 in error at ./error.jl:22
 in test_approx_eq at ./test.jl:109
 in anonymous at ./no file:78
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg2.jl, in expression starting on line 22
ERROR: BoundsError()
 in anonymous at ./task.jl:1367
while loading linalg1.jl, in expression starting on line 9
while loading /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/runtests.jl, in expression starting on line 39

	From worker 3:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 8:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 5:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 4:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 2:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 6:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 9:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 7:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
~~~~

When I also pass `USE_ATLAS=1` as well as `ATLAS_LIBDIR=/path/to/atlas/lib` and `ATLAS_OBJ_SOURCE=/path/to/atlas/lib/libsatlas.so` I get different failures:

~~~
    JULIA test/all
	From worker 6:	     * linalg/cholmod
	From worker 7:	     * linalg/umfpack
	From worker 5:	     * linalg4
	From worker 2:	     * linalg1
	From worker 4:	     * linalg3
	From worker 3:	     * linalg2
	From worker 9:	     * keywordargs
	From worker 8:	     * core
	From worker 6:	     * numbers
	From worker 9:	     * strings
	From worker 7:	     * collections
	From worker 8:	     * hashing
	From worker 9:	     * remote
	From worker 9:	     * iobuffer
	From worker 9:	     * arrayops
	From worker 8:	     * reduce
	From worker 8:	     * reducedim
	From worker 7:	     * simdloop
	From worker 7:	     * blas
exception on 7: ERROR: test failed: all(BLAS.gemm('N','T',I4,I4) .== I4)
 in error at ./error.jl:21
 in default_handler at ./test.jl:19
 in do_test at ./test.jl:39
 in anonymous at ./no file:50
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading blas.jl, in expression starting on line 3
exception on 2: ERROR: LAPACKException(5)
 in ggev! at ./linalg/lapack.jl:1380
 in eigfact! at ./linalg/factorization.jl:643
 in eigfact at ./linalg/factorization.jl:646
 in anonymous at ./no file:166
 in runtests at /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/testdefs.jl:6
 in anonymous at ./multi.jl:855
 in run_work_thunk at ./multi.jl:621
 in anonymous at ./task.jl:855
while loading linalg1.jl, in expression starting on line 25
ERROR: LAPACKException(5)
 in anonymous at ./task.jl:1367
while loading linalg1.jl, in expression starting on line 25
while loading /buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/test/runtests.jl, in expression starting on line 39

	From worker 8:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 5:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 7:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 2:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 4:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 3:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 6:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
	From worker 9:	/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
/buildtmp/nix-build-julia-0.3.6.drv-4/julia-0.3/usr/bin/../lib/julia/sys.ji
Makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:424: recipe for target 'test' failed
make: *** [test] Error 2
~~~~

I'm not sure if it is related, but in order to make the ccall mechanism work for the system libraries I build against I have patched `./src/ccall.cpp` to contain static entries in `sonameMap` for the following libraries:

~~~
libc
libpcre
libmpfr
libblas
liblapack
libgmp
libopenlibm
libopenspecfun
libfftw3
~~~

(See https://github.com/JuliaLang/julia/issues/10246 for a discussion on why this is necessary.)

### LINKED ISSUE #11417: compilation bug in cholfact
Hi all,
I run the following code, the error appears randomly.

```
julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: ArgumentError("invalid argument #4294967296 to LAPACK call")
 in potrf! at linalg/lapack.jl:1743
 in cholfact! at linalg/factorization.jl:37
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: PosDefException(4294967296)
 in cholfact! at linalg/factorization.jl:38
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: PosDefException(139689516335104)
 in cholfact! at linalg/factorization.jl:38
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

```

### PR DESCRIPTION
**Pull request by tkelman**
fixes #10457, fixes #11417

### CODE REVIEW

**Comment by tkelman** [comment]
cc @ViralBShah @andreasnoack @nalimilan

**Comment by nalimilan** [comment]
Sounds like a good idea to me, even though it makes the rules more complex.

I'm not clear about whether `?=` is needed instead of plain `=` in that place, as `Make.inc` contains both. I guess you know what you're doing...

**Comment by tkelman** [comment]
`?=` only sets the variable if it hasn't been set previously, either in `Make.user` or on the command line. This just means `override` is not required if someone wants to set this to a non-default value (like me on AppVeyor, where I actually mean the ILP64 libopenblas.dll taken from a nightly binary rather than a conventional USE_SYSTEM_BLAS)

**Comment by nalimilan** [comment]
Yeah, but environment variables have precedence over anything you may set in your Makefile. So as I understand it `?=` only makes a difference if it was set in another Makefile, i.e. Make.user. Maybe we'd better re-include it at the end, so that all variables can be overridden.

**Comment by tkelman** [comment]
It is sort of a mess right now in terms of which variables do or do not require using `override` to set in `Make.user`. I don't really want to break anyone's existing setup here, except for the handful of people who might be setting `USE_SYSTEM_BLAS=1` and using an ILP64 blas, which except in the case of MKL (as accounted for here) is not a configuration that I'd consider to be common.

**Comment by andreasnoack** [comment]
I don't know the best way to write this in a Makefile, but I think the change is right. It appears that all system provided BLASes and LAPACKSs are lp64.

**Pull request merged**
