### PR TITLE
RFC: Separate function to extract a Pkg name from a URL

### PR DESCRIPTION
**Pull request by ghost**
Makes it possible to access this feature as a consenting adult, as discussed in #9004.

### CODE REVIEW

**Comment by quinnj** [comment]
Seems like something more relevant for [PkgDev.jl](https://github.com/JuliaLang/PkgDev.jl)

**Comment by wildart** [comment]
Not quite, `Pkg.clone` needs to determine package name from url.

**Comment by wildart** [comment]
I like `Pkg.guessname` name, and whole thing should be moved to `pkg.jl`

**Comment by ararslan** [comment]
This PR is no longer relevant, as the package manager has been completely redesigned. See [its separate repo](https://github.com/JuliaLang/Pkg.jl) for introducing new features.

**Pull request closed without merging**
