### PR TITLE
add missing exports

### PR DESCRIPTION
**Pull request by rened**
The following are mentioned in the docs but are missing exports (and none of them are marked with "Not exported" in the docs): 

``` jl
default, Instant, UTInstant, EnvHash, 
hist!, hist2d!, subtypetree, function_module, 
function_name, munmap, setopt, 
unsafe_trunc, blascopy!, with_handler
```

### CODE REVIEW

**Comment by rened** [comment]
Can we pick the simple ones (please advise) and open independent issues for the others?
My guess:
Simply oversights: `Instant, UTInstant, hist!, hist2d!, subtypetree,  munmap, blascopy!`
Should these be exported at all: `default, EnvHash, unsafe_trunc, with_handler`
Naming: `default, function_module, function_name, setopt, with_handler`
Note that this is not about exporting all into `Base`, but in the respective module (blascopy -> BLAS, with_handler -> Base.Test), just like the respectively neighboring functions which are documented *and* exported.
The alternative is always to mark some as "(not exported)", for consistency.

**Comment by quinnj** [comment]
Yeah, `default` is definitely not meant to be exported from Base, let alone the Dates module. It's the same reason `format` isn't exported from Dates; for some names that are overly broad or generic, it helps to require the module name as qualification.

With regards to `Instant`, I'm mainly uncomfortable because there isn't really a well thought out, defined, or vetted interface for `Instant`s yet and I'd hate to change something down the road and be in danger of breaking more things.

**Comment by JeffBezanson** [comment]
@jiahao What the hell does that label mean?

**Comment by jiahao** [comment]
looks like a bikeshed...?

**Comment by mbauman** [comment]
How well supported are the 🚲🏠 emojis (which are different from GitHub's :bike: :house:)?  Let's bike shed the bike shed label!

**Comment by rened** [comment]
Ouch, getting a specifically created label like this even hurts a little ;-)  For the record, my only aim is consistency between manual and actual user experience - I leave the internal bikeshedding up to you guys ;-)

**Comment by StefanKarpinski** [comment]
@rened, forcing us to reconcile the inconsistency is very good – thanks for doing it! The main issue here is not your but the fault of these parts of the standard library not being as well polished yet as they should be.

**Comment by JeffBezanson** [comment]
Yeah, I don't like the label. I'm going to delete it.

**Comment by JeffBezanson** [comment]
I really want to keep exported names to a minimum. Some comments:

- `EnvHash` - is a singleton and almost always used via `ENV`, so very rarely needed.
- `subtypetree` - pretty useless, and as far as I can tell not used anywhere
- `function_module` - could maybe be useful, but not used anywhere that I can tell
- `mmap` and `munmap` (though `mmap` is already exported) I don't think we need to export functions this low-level. In fact I'd like to see more function like this moved into a `Base.C` or `Base.Libc`.

**Comment by JeffBezanson** [comment]
I'm going to commit my own version of this.

**Comment by ivarne** [comment]
Searching METADATA registred packages, I found that`Base.function_module` is used in [Church.jl](https://github.com/LaurenceA/Church.jl/blob/16628b4b5a4c541d884427513dffd6843ddab6b4/src/Church.jl#L116) for some macro magic.

**Pull request closed without merging**
