### PR TITLE
store the path to where a package got loaded

### LINKED ISSUE #33210: pathof(::Module) doesn't show the path where the module actually got imported from
```
julia> using Example

julia> pathof(Example)
"/Users/kristoffer/.julia/packages/Example/aqsx3/src/Example.jl"

(v1.2) pkg> add Example@0.5.1
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
  [7876af07] ↓ Example v0.5.3 ⇒ v0.5.1
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [7876af07] ↓ Example v0.5.3 ⇒ v0.5.1

julia> pathof(Example)
"/Users/kristoffer/.julia/packages/Example/kH44X/src/Example.jl"
```

I would have thought `pathof` should point to the path as it was when the module was imported. Not the file that would have been used if the module was not imported but got imported right now.

### PR DESCRIPTION
**Pull request by KristofferC**
And use it in `pkgdir`

Fixes https://github.com/JuliaLang/julia/issues/33210

### CODE REVIEW

**Review by timholy — APPROVED** [review]

**Comment by timholy** [comment]
So cool! Is #35663 next?

**Comment by KristofferC** [comment]
What behavior do you want there? A warning when the package would have gotten loaded from a different place than if it was not already loaded?

**Comment by timholy** [comment]
Personally, I want an error---don't let the user change environments.

**Comment by KristofferC** [comment]
Storing the path here is an improvement but it isn't really perfect. For example, if I make a sysimage, send it to a friend and he uses it, loads the same version of a package that is in the sysimage, that will have a different path, but it is stil the same package version. What we should store is probably more akin to "how this package got loaded". And there are a few ways a package can get loaded:

- by `git-tree-sha1`
- by explicit path
- by implicit path due to the folder being in `LOAD_PATH` (how stdlibs are loaded).

In the case above, the same `git-tree-sha1` would be used so even if the absolute paths is resolved differently, it is still not a problem.

**Comment by timholy** [comment]
Seems like this must have missed a case:
```julia
julia> using JuliaInterpreter

julia> pathof(JuliaInterpreter)
"/home/tim/.julia/packages/JuliaInterpreter/muncv/src/JuliaInterpreter.jl"

julia> exit()
tim@diva:~/.julia/dev/Revise$ julia-master --startup-file=no -q
julia> using Revise

julia> using JuliaInterpreter

julia> pathof(JuliaInterpreter)

julia>
```

**Comment by KristofferC** [comment]
Thanks, will look at it.

**Pull request merged**
