### PR TITLE
test REPL package completion if package is already imported

### PR DESCRIPTION
**Pull request by simeonschaub**
Followup to @vtjnash's comment in https://github.com/JuliaLang/julia/pull/36506#discussion_r449968312. At least passes for me locally.

### CODE REVIEW

**Comment by simeonschaub** [comment]
@vtjnash Are you still interested in this?

**Comment by vtjnash** [comment]
Ah, this seems good. But why does it pass here if it fails when the module name is Main?

**Comment by simeonschaub** [comment]
@twhitehead's comment in https://github.com/JuliaLang/julia/issues/32377#issuecomment-591632192 seems to attribute it to there actually being two REPL modules in Main, but I have no clue how that's even possible.

**Comment by twhitehead** [comment]
Not two REPL modules in Main. Just two completions for REPL.

The one being the expected one from the test. The other being due to runtests.jl having imported REPL.

**Pull request merged**
