### PR TITLE
add partially-applied versions of ∋, ∉, ∌, occursin

### PR DESCRIPTION
**Pull request by JeffBezanson**
`in(x)` is really useful, but sometimes I want this for the other argument. E.g.
```
julia> findall(∋(0), [-1:1, 1:10, -2:20])
2-element Vector{Int64}:
 1
 3
```
for finding ranges that contain 0. It's not great that this requires unicode --- is there another name for this already? If not, should we add one?

### CODE REVIEW

**Comment by KristofferC** [comment]
`ni`!

**Comment by Keno** [comment]
`inleft`?

**Comment by StefanKarpinski** [comment]
I actually like calling it `ni` 😬

**Comment by JeffBezanson** [comment]
Other languages may try to reference it, but WE ARE THE DEVS WHO SAY "NI"!

**Comment by mcabbott** [comment]
There is `findall(contains('a'), ["cat", "dog", "zebra"])` but only for strings. For which `findall(in("cat"), 'a':'e')` works but `occursin("cat")` does not.

**Comment by JeffBezanson** [comment]
Yeah we should also add `occursin(x)`.

**Comment by nickrobinson251** [comment]
> we should also add occursin(x).

I think [this criteria](https://github.com/JuliaLang/julia/issues/33193#issuecomment-529211017) is the reason we don't have `occursin(x)` (and one of the motivations for adding the argument-flipped `contains` function was that it fit the criteria for having a partially-applied one-arg method).

**Comment by StefanKarpinski** [comment]
These definitions would both fit the criteria:

* `occursin(haystack)` would be `needle -> occursin(needle, haystack)`
* `contains(needle)` would be `haystack -> contains(haystack, needle)`.

**Comment by jw3126** [comment]
> `ni`!

We should add more pythonic then python to the greed of julia.

**Comment by stevengj** [comment]
Needs docs and/or NEWS?

**Comment by JeffBezanson** [comment]
Added all the things.

**Comment by nickrobinson251** [comment]
oh... it's really gonna be called `ni` 😆 I don't want to bikeshed this too much, but it does seem a bit funny... since it's not a word. Maybe that's fine, because in practice `∋` will probably be used instead, and this is just for when an ascii name is required for some reason? 

I didn't want to raise a naming question with an alternative suggestion, so... How about `has`? e.g. `has([1, 2, 3], 2)`, `any(has(0), (-1:1, 1:3))`? it's still very short, basically another word for `contains`, probably fine to claim as name (i've never seen a `has` function before), and i think consistent enough with functions names with a `has*` prefix, like `haskey`, `hasvalue` etc. 

(I don't feel strongly, so don't hold up the PR over this if everyone else is in favour of `ni` ...as i say, i doubt `ni` will appear in too many codebases, even if `∋` gets wider use)

**Comment by stevengj** [comment]
`ni` is cute, but it's not a great antonym for `in` — it would be pretty confusing to most people if they saw that appearing in code.  And since it's not infix, it's not really symmetrical with `in` (and we can't make it infix because that would involve introducing a breaking new keyword).

**Comment by oxinabox** [comment]
We could always say the ASCII form is `xs->in(x,xs)`
Like we do for *not in*, and used to do for *compose*

**Comment by JeffBezanson** [comment]
Ok, I don't insist on `ni`. `has` is ok, or I could just delete `ni` for now to get the rest of this in.

**Comment by StefanKarpinski** [comment]
> or I could just delete `ni` for now to get the rest of this in.

Let's just do that for now and open a separate issue for whether we need an ASCII name for `∋`.

**Pull request merged**
