### PR TITLE
Support `eltype`s without zero in `_rmul_or_fill!`

### PR DESCRIPTION
**Pull request by jishnub**
This uses `rmul!` instead of `fill!(C, zero(eltype(C)))` if `eltype(C)` doesn't have a zero. This is useful for block matrices.
The following works after this:
```julia
julia> D = Diagonal(fill(ones(2,2), 2))
2×2 Diagonal{Matrix{Float64}, Vector{Matrix{Float64}}}:
 [1.0 1.0; 1.0 1.0]          ⋅         
         ⋅           [1.0 1.0; 1.0 1.0]

julia> LinearAlgebra._rmul_or_fill!(D, 0)
2×2 Diagonal{Matrix{Float64}, Vector{Matrix{Float64}}}:
 [0.0 0.0; 0.0 0.0]          ⋅         
         ⋅           [0.0 0.0; 0.0 0.0]
```

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]

**Comment by jishnub** [comment]
This doesn't seem correct, as we should not access the destination for `beta == 0`.

**Comment by dkarrasch** [comment]
Wait, I thought this function is just to avoid multiplication in the `beta==0` case?

**Comment by jishnub** [comment]
Yes, it is. Unfortunately, I don't think there's a way to fill the destination without accessing the elements if the eltype doesn't have a zero.

**Comment by dkarrasch** [comment]
That sounds to me like the usage is unsound, not your proposed change here, no?

**Pull request closed without merging**
