### PR TITLE
fix gc collection interval logic

### PR DESCRIPTION
**Pull request by vtjnash**
We had previously prevented full collections for the first collection,
forgotten to reset counters for gc_sweep_always_full, and caused resets
of other counter heuristics even when not heuristically driven.

### CODE REVIEW

**Comment by Keno** [comment]
Also cc @chflood, who's currently looking at the gc code and might have comments.

**Review by maleadt — APPROVED** [review]
I'm not familiar with the code, but LGTM in principle.

**Comment by chflood** [comment]
I don't yet have a deep understanding of how the Julia GC heuristics work, but to the best of my understanding this patch is fine.

**Review by NHDaly — COMMENTED** [review]
Sorry for my delay. Thanks for fixing this! It seems right to me, too, though i am similarly unfamiliar with the (difficult) GC code 👍

**Pull request merged**
