### PR TITLE
Update functions.rst

### PR DESCRIPTION
**Pull request by dshurick**
Fixing a typo: `the` --> `to

### CODE REVIEW

**Comment by ivarne** [comment]
Why did you close the PR?

**Comment by dshurick** [comment]
Sorry, I didn't know whether I was following protocol so I wanted to undo my PR and do more research before contributing.

**Comment by yuyichao** [comment]
One possible issue is that this should be opened against master first (or in additional to) unless it is fixed there already.

**Comment by dshurick** [comment]
I am closing this PR as I have replicated the change in another PR against master.

**Pull request merged**
