### PR TITLE
docs: fix example for `sort` and add new doctest

### PR DESCRIPTION
**Pull request by rapus95**

### CODE REVIEW

**Review by inkydragon — APPROVED** [review]
Maybe we can make the comment into doctest as well.

```jl
julia> sort(0:3, by=x->x-2, order=Base.Order.By(abs))
4-element Vector{Int64}:
 2
 1
 3
 0

julia> ans == sort(0:3, by=x->abs(x-2))
true
```
Or
```jl
julia> sort(0:3, by=x->x-2, order=Base.Order.By(abs))
4-element Vector{Int64}:
 2
 1
 3
 0

julia> sort(0:3, by=x->x-2, order=Base.Order.By(abs)) == sort(0:3, by=x->abs(x-2))
true
```

**Comment by ViralBShah** [comment]
Looks good - would be great to get the other doctest in also as suggested.

**Comment by rapus95** [comment]
never created a doctest before, I'll try to look into it in a few hours, all pointers and hints/tips welcome

**Review by sijow — APPROVED** [review]
Agreed it would be nice to have the version in comment tested by the doctest.

@rapus95 the whole Markdown code block in this comment, with all these examples, is one big doctest. It should just be a matter of replacing a part of the code block with another, exactly as proposed by @inkydragon .  Then to test the doctest locally you can compile Julia and run the test command as described in CONTRIBUTING.md.

**Comment by rapus95** [comment]
I added the 2nd proposal (which doesn't use `ans`). Please take a look and merge if nothing else to add :)

**Review by inkydragon — APPROVED** [review]

**Pull request merged**
