### PR TITLE
Add fast path for merge with Dicts

### LINKED ISSUE #22519: Add specialized merge(::Dict, ...) ?
Seems like using `copy` in place of the first internal `merge!` is a winner. Seems worth it even when copy causes the `Dict` to be rehashed. Any reason not to?

Quick benchmarks:
```julia
julia> using BenchmarkTools

julia> mymerge(d1::Dict, d2::Dict) = merge!(copy(d1), d2)
mymerge (generic function with 1 method)

julia> d1 = Dict(i => i for i in 1:10000);

julia> d2 = Dict(i => i + 2 for i in 1:1)
Dict{Int64,Int64} with 1 entry:
  1 => 3

julia> e1 = @benchmark merge($d1, $d2)
BenchmarkTools.Trial: 
  memory estimate:  364.64 KiB
  allocs estimate:  24
  --------------
  minimum time:     461.857 μs (0.00% GC)
  median time:      472.524 μs (0.00% GC)
  mean time:        569.531 μs (6.31% GC)
  maximum time:     7.441 ms (0.00% GC)
  --------------
  samples:          8748
  evals/sample:     1

julia> e2 = @benchmark mymerge($d1, $d2)
BenchmarkTools.Trial: 
  memory estimate:  272.38 KiB
  allocs estimate:  7
  --------------
  minimum time:     17.242 μs (0.00% GC)
  median time:      22.934 μs (0.00% GC)
  mean time:        48.464 μs (49.14% GC)
  maximum time:     2.478 ms (93.50% GC)
  --------------
  samples:          10000
  evals/sample:     1
julia> ratio(median(e2), median(e1))
BenchmarkTools.TrialRatio: 
  time:             0.048536159009912726
  gctime:           1.0
  memory:           0.7469683335475854
  allocs:           0.2916666666666667

julia> judge(median(e2), median(e1))
BenchmarkTools.TrialJudgement: 
  time:   -95.15% => improvement (5.00% tolerance)
  memory: -25.30% => improvement (1.00% tolerance)

julia> function delcopy(d)
           dd1=copy(d)
           for i in 1:500
               delete!(dd1, i)
           end
           @assert dd1.ndel == 500
           return dd1
       end
delcopy (generic function with 1 method)

julia> e1 = @benchmark merge(dd1, $d2) setup=(dd1=delcopy($d1))
BenchmarkTools.Trial: 
  memory estimate:  364.64 KiB
  allocs estimate:  24
  --------------
  minimum time:     445.034 μs (0.00% GC)
  median time:      452.754 μs (0.00% GC)
  mean time:        506.000 μs (7.04% GC)
  maximum time:     3.386 ms (79.21% GC)
  --------------
  samples:          8760
  evals/sample:     1

julia> e2 = @benchmark mymerge(dd1, $d2) setup=(dd1=delcopy($d1))
BenchmarkTools.Trial: 
  memory estimate:  544.67 KiB
  allocs estimate:  13
  --------------
  minimum time:     235.221 μs (0.00% GC)
  median time:      245.309 μs (0.00% GC)
  mean time:        297.607 μs (14.50% GC)
  maximum time:     4.205 ms (61.20% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> ratio(median(e2), median(e1))
BenchmarkTools.TrialRatio: 
  time:             0.5418140977219417
  gctime:           1.0
  memory:           1.4937224150490638
  allocs:           0.5416666666666666

julia> judge(median(e2), median(e1))
BenchmarkTools.TrialJudgement: 
  time:   -45.82% => improvement (5.00% tolerance)
  memory: +49.37% => regression (1.00% tolerance)
```

### PR DESCRIPTION
**Pull request by garborg**
A hair slower if length(Dict) == 1, faster generally.
Closes #22519

### CODE REVIEW

**Comment by KristofferC** [comment]
Any benchmarks to share?

**Comment by garborg** [comment]
Can do when I get home tonight. The quick benchmark in #22519 shows best-case improvements.
With respect to the first argument, it's marginally faster for dicts with 3 elements, over an order of magnitude for dicts of 1000 elements. Speedup dampened when copy rehashes the dict argument, but then I guess you get that cleanup for free. 

Methodology-wise, I saw no slowdown vs a specialized method restricted to known, shared key and value types.

**Comment by nalimilan** [comment]
There's already an `emptymergedict` function. Couldn't you add a specialized method for it?

**Comment by garborg** [comment]
Exactly, `emptymergedict` seemed like a misnomer. Is making both `mergedict`, with an `empty` or `fill` keyword argument, what you're suggesting, more or less?

**Comment by nalimilan** [comment]
Actually I think I'd suggest merging `emptymergedict` and your `mergedict` into a single function (maybe with a different name, since none of them seems very explicit about what they do), without a keyword argument. Indeed it seems `emptymergedict` could have the same behavior as `mergedict`, i.e. return a new dict of the right type with the contents of the first `Associative` argument.

**Comment by garborg** [comment]
Good call. Once I went to combine helper functions, I realized all three previous paths were covered by well by either `Dict{K,V}(d)` or `associative_with_eltype`.

Timings confused me benchmarking, though. I tried a few variations before I realized the noise was just a matter of whether or not BenchmarkTools inlined the `merge` function being tested. The functions not being inlined weren't necessarily the ones I would have guessed. Timings look as expected after forcing inlining.

I assume that's just an artifact of the benchmarking and I don't want to force `merge` to be inlined.

[timings w/ & w/o inlining here](https://gist.github.com/garborg/6ce3eb8ccfcde9f5aca6abd9f5df14d8).

**Comment by tkelman** [comment]
That looks pretty simple. Dunno if any existing benchmarks would cover this, if not might be worth adding some new ones to BaseBenchmarks to track it. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/22737#issuecomment-314973920) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d0cd02e52b7dc8cf24400130db5f3f45884a584b/7b9b08c_vs_7c31c41/report.md). cc @ararslan

**Comment by garborg** [comment]
I'd be happy to add a benchmark or two, but I'm still a little confused about the interaction between BenchmarkTools and inlining from that benchmarking script: i.e. I needed to force inlining in benchmarking to see the comparison I expected, and I didn't think merge was something you'd force inlining on.

**Review by Sacha0 — APPROVED** [review]
superficially lgtm :).

**Comment by tkelman** [comment]
we should probably rename the existing benchmark label to needs-benchmark rather than adding a new near-duplicate one, since that's most of what it's been used for

**Comment by StefanKarpinski** [comment]
It was unclear to me that this was what the `benchmark` label was for.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/13893#issuecomment-155824957

**Comment by StefanKarpinski** [comment]
Ah, yes, how could I have missed that one-line comment from two years ago. I've renamed the label to make its meaning clear without ancient comment spelunking.

**Review by nalimilan — APPROVED** [review]
Looks good to me too. I wish we could find an even more explicit name, but without using a full sentence that doesn't sound possible. :-)

**Comment by KristofferC** [comment]
> I needed to force inlining in benchmarking to see the comparison I expected, and I didn't think merge was something you'd force inlining on.

Here, `merge` just hands over to `merge!` and thus a bunch of splatting so it is possible the inlining avoids the splatting penalty. If the benchmarks are better with forced inlining, I would keep it.

**Comment by KristofferC** [comment]
I don't see any difference between explicit inlining or not anymore. Will rerun CI and merge if green.

**Pull request merged**
