### PR TITLE
Update Go benchmarks to use the gonum suite

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
Updates mainly to the two matrix benchmarks, though a couple of other minor fixes. I left the current algorithm for timing and testing functions, thinking it would be easiest to integrate with the current setup. Go does have its own testing/benchmarking set that could be switched to in the future.

Benchmarks: OS X 10.10.5, 2.7 Ghz Intel Core i7. OpenBLAS installation as of this week. 
Old:
````
brendan:~/Documents/mygo/src/juliabench$ go run orig.go 
go,fib,0.041908
go,parse_int,0.307543
go,mandel,0.184255
go,quicksort,0.30707900000000005
go,pi_sum,35.73283
go,rand_mat_stat,133.611151
go,rand_mat_mul,1355.0587739999999
````
New:
````
brendan:~/Documents/mygo/src/juliabench/take2/orig$ go run new.go 
go,fib,0.042093000000000005
go,parse_int,0.301092
go,mandel,0.18418400000000001
go,quicksort,0.31516900000000003
go,pi_sum,19.677399
go,rand_mat_stat,18.360594000000003
go,rand_mat_mul,95.816635
````

And if we use Go-backed matrix operations instead of BLAS backed matrix operations
````
brendan:~/Documents/mygo/src/juliabench/take2/orig$ go run new.go 
go,fib,0.054677
go,parse_int,0.395098
go,mandel,0.20145000000000002
go,quicksort,0.34608
go,pi_sum,19.722858000000002
go,rand_mat_stat,33.853094999999996
go,rand_mat_mul,203.79812400000003
````

**Comment by jiahao** [comment]
Thanks for the fixes. I admit that I don't really speak Go and had no idea if what I was writing for `randmatmul` and `randmatstat` were idiomatic.

**Comment by btracey** [comment]
It's fine. Thanks for putting in the effort to include them in the first place. gonum has come a long way since they were originally written.

How do I search for julia functions? For example, if I wanted to find what the "hex" function actually does? Similarly, how does one search for the .'* operator? Searching Google for "julia ".'*" "  doesn't get very far.

**Comment by ivarne** [comment]
documentation and `methods(*)`

**Comment by StefanKarpinski** [comment]
To be more explicit about doc search this:

http://docs.julialang.org/en/release-0.3/stdlib/numbers/?highlight=hex#Base.hex

**Comment by tkelman** [comment]
Though that particular example of `.'*` lowers to `At_mul_B` which I think we're all hoping to simplify and get rid of via transpose types, so it wouldn't surprise me if it's a little underdocumented.

**Comment by btracey** [comment]
Do I need to do anything else to get this PR ready? This is my first contribution to the Julia project, so apologies if I do not understand the proper protocol.

**Comment by tkelman** [comment]
I think we just need to double check that we can build and run it on the same machine as the rest of the benchmarks. Thanks for modernizing these.

**Comment by jiahao** [comment]
I was able to run the new tests on our benchmark machine.

Here are the new and old Go tests side by side with all the others:

<table class="benchmarks">
<colgroup>
<col class="name"></col>
<col class="relative" span="12"></col>
</colgroup>
<thead>
<tr><td></td><th class="system">Fortran</th><th class="system">Julia</th><th class="system">Python</th><th class="system">R</th><th class="system">Matlab</th><th class="system">Octave</th><th class="system">Mathe-matica</th><th class="system">JavaScript</th><th class="system">Go (new)</th><th class="system">Go (old)</th><th class="system">LuaJIT</th><th class="system">Java</th></tr>
<tr><td></td><td class="version">gcc </td><td class="version">0.5.0-dev
</td><td class="version">2.7.9
</td><td class="version">3.1.2
</td><td class="version">R2014a
</td><td class="version">3.8.2
</td><td class="version">10.2.0
</td><td class="version">V8 3.28.71.19
</td><td class="version">go1.3.3
</td><td class="version">go1.3.3
</td><td class="version">gsl-shell 2.3.1
</td><td class="version">1.8.0_45
</td></tr>
</thead>
<tbody>
<tr><th>fib</th><td class="data">0.55</td><td class="data">1.67</td><td class="data">62.76</td><td class="data">442.96</td><td class="data">3442.39</td><td class="data">7075.36</td><td class="data">97.35</td><td class="data">2.71</td><td class="data">1.83</td><td class="data">1.71</td><td class="data">1.57</td><td class="data">2.20</td></tr>
<tr><th>parse_int</th><td class="data">4.41</td><td class="data">1.42</td><td class="data">12.40</td><td class="data">49.30</td><td class="data">1527.25</td><td class="data">8837.14</td><td class="data">14.74</td><td class="data">5.81</td><td class="data">3.17</td><td class="data">3.09</td><td class="data">5.60</td><td class="data">3.31</td></tr>
<tr><th>quicksort</th><td class="data">1.24</td><td class="data">1.09</td><td class="data">30.16</td><td class="data">229.87</td><td class="data">52.79</td><td class="data">1730.60</td><td class="data">39.16</td><td class="data">2.58</td><td class="data">0.98</td><td class="data">1.01</td><td class="data">2.50</td><td class="data">2.47</td></tr>
<tr><th>mandel</th><td class="data">0.85</td><td class="data">0.82</td><td class="data">13.47</td><td class="data">52.48</td><td class="data">59.08</td><td class="data">443.90</td><td class="data">5.16</td><td class="data">0.69</td><td class="data">1.14</td><td class="data">1.14</td><td class="data">0.69</td><td class="data">1.41</td></tr>
<tr><th>pi_sum</th><td class="data">1.00</td><td class="data">1.00</td><td class="data">14.25</td><td class="data">15.04</td><td class="data">1.28</td><td class="data">282.64</td><td class="data">1.69</td><td class="data">1.00</td><td class="data">1.00</td><td class="data">1.32</td><td class="data">1.00</td><td class="data">1.00</td></tr>
<tr><th>rand_mat_stat</th><td class="data">1.31</td><td class="data">1.75</td><td class="data">16.83</td><td class="data">17.03</td><td class="data">10.31</td><td class="data">36.87</td><td class="data">5.61</td><td class="data">2.30</td><td class="data">2.90</td><td class="data">9.82</td><td class="data">3.35</td><td class="data">3.95</td></tr>
<tr><th>rand_mat_mul</th><td class="data">2.97</td><td class="data">0.90</td><td class="data">0.98</td><td class="data">5.63</td><td class="data">0.97</td><td class="data">0.98</td><td class="data">1.01</td><td class="data">13.13</td><td class="data">1.27</td><td class="data">10.03</td><td class="data">0.96</td><td class="data">2.05</td></tr>
</tbody>
</table>

**Comment by jiahao** [comment]
Cherry-picked and squashed as 4fab72b on #13219 

Thanks again for the updated tests.

**Comment by tkelman** [comment]
We still want to merge this to master too, right?

**Comment by jiahao** [comment]
Yes but it's cleaner to port #13219 back to master than to redo this.

**Comment by ViralBShah** [comment]
I assume that somehow BLAS is being used somewhere in the new Go implementation, given the speedup on the random matrix tests. Nice!

**Comment by jiahao** [comment]
Yes, `gonum` now has BLAS wrappers, and the test numbers were run with the same version of OpenBLAS for Go and Julia.

**Comment by btracey** [comment]
We also have a pure Go BLAS implementation as well. On my machine BLAS is roughly 2x faster (a combination of bounds checking and vectorization)

**Pull request closed without merging**
