### PR TITLE
Deprecate isnumber() in favor of isnumeric()

### PR DESCRIPTION
**Pull request by nalimilan**
Consistent with Python and Rust (but not Go), and less easy to confuse with `isdigit()`. Improve documentation to make confusion less easy.

Also fix a few uses where `isdigit()` is more appropriate than `isnumber()`.

(This function would better not exist at all... 😄 )

### CODE REVIEW

**Comment by stevengj** [comment]
I thought the consensus in #14347 would be to move these functions into a stdlib package?  Seems better to do any renaming at that point.   Otherwise, you force people to update for deprecations twice in the 0.7 cycle.

**Review by StefanKarpinski — APPROVED** [review]
Sure, it's clearly a better name.

**Comment by StefanKarpinski** [comment]
Yes, I was planning on doing the stdlib thing next.

**Comment by nalimilan** [comment]
Closing in favor of https://github.com/JuliaLang/julia/pull/25021.

**Pull request closed without merging**
