### PR TITLE
Try to disable the AV debug build to save some time on windows

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by KristofferC** [comment]
`make install` builds both I think?

**Comment by ViralBShah** [comment]
It is still building debug.

**Comment by ViralBShah** [comment]
Ah just saw your message @KristofferC. Let's see if this goes through.

**Comment by ViralBShah** [comment]
Not completely unexpected, but a lot more effort is needed to turn off debug builds.

**Pull request closed without merging**
