### PR TITLE
give more context to error when parsing REQUIRE files

### LINKED ISSUE #12395: Uninformative error message on invalid REQUIRES file
```
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: invalid requires entry for julia: julia 0.3 - 0.5
 in error at ./error.jl:21
 in call at pkg/reqs.jl:29
 in read at pkg/reqs.jl:61
 in open at ./iostream.jl:114
 in parse at ./pkg/reqs.jl:101
 in requires_dict at pkg/read.jl:135
 in fixed at ./pkg/read.jl:154
 in update at ./pkg/entry.jl:289
 in anonymous at pkg/dir.jl:31
 in cd at ./file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

In this case, the invalid REQUIRE file was in NumericExtensions, which I had checked out (lindahua/NumericExtensions.jl#60). But it would be nice if this error message actually reported what package was problematic.

### PR DESCRIPTION
**Pull request by jakebolewski**
before:

``` julia
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: invalid requires entry for julia: julia 0.3 - 0.5
 in error at ./error.jl:21
 in call at pkg/reqs.jl:29
 in read at pkg/reqs.jl:61
 in open at ./iostream.jl:114
 in parse at ./pkg/reqs.jl:101
 in requires_dict at pkg/read.jl:135
 in fixed at ./pkg/read.jl:154
 in update at ./pkg/entry.jl:289
 in anonymous at pkg/dir.jl:31
 in cd at ./file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

with this change:

``` julia
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: parsing REQUIRE entry for package "NumericExtensions"
invalid requires entry for julia: julia 0.3 - 0.5
 in error at ./error.jl:21
 in call at pkg/reqs.jl:29
 in read at pkg/reqs.jl:61
 in open at ./iostream.jl:114
 in parse at ./pkg/reqs.jl:101
 in requires_dict at pkg/read.jl:135
 in fixed at ./pkg/read.jl:154
 in update at ./pkg/entry.jl:289
 in anonymous at pkg/dir.jl:31
 in cd at ./file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

closes #12395

### CODE REVIEW

**Comment by tkelman** [comment]
+1

**Comment by wildart** [comment]
:+1:

**Comment by pkofod** [comment]
+1 : A lot more informative than the old message.

**Comment by simonster** [comment]
Is this still needed?

**Comment by tkelman** [comment]
the current error handling isn't very informative here, so yes

**Comment by KristofferC** [comment]
Obsolete with the new package manager, if still applicable needs to be reopened against Pkg.jl

**Pull request closed without merging**
