### PR TITLE
auto completion for true and false

### LINKED ISSUE #14101: `true` and `false` missing in autocompletion
I might be missing something but it seems that `true` and `false` are missing from the autocompletion list. This happens both in REPL and in IJulia. I've also seen this locally on master and on 0.3.12 and 0.4 on juliabox.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #14101

### CODE REVIEW

**Comment by tkelman** [comment]
are these tested?

**Comment by yuyichao** [comment]
They are now =)

**Comment by hayd** [comment]
Should this be backported?

**Comment by yuyichao** [comment]
I think this should be safe to backport.

**Pull request merged**
