### PR TITLE
Fix `make -C doc linkcheck` by updating redirecting links in docs

### PR DESCRIPTION
**Pull request by tkelman**
Upgrades to a newer sphinx to deal with getting some latin-1 back from valgrind's docs, and ignores the other remaining 2 problematic ones - the kde bug page is returning empty, and https://www.appveyor.com is returning 403: Forbidden. cc @FeodorFitsner any idea why it would do that using the Sphinx doc generator's link-checking feature?

All but ~~the last commit~~ https://github.com/JuliaLang/julia/pull/17862/commits/5f95c4f5f2faf3ae0665da1609a2f8aae87becd5 should be backported to release-0.5. (and some version of the first 3 should be backported to release-0.4)

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Can you elaborate more on "https://www.appveyor.com is returning 403: Forbidden"?

**Comment by tkelman** [comment]
If I run `make -C doc linkcheck` in Cygwin (MSYS2 should also work I think, I'll try to point to a reproduction that runs easily on appveyor) without including this fix, part of the output looks like
```
(line  768) ok        https://travis-ci.org
(line  768) broken    http://appveyor.com - HTTP Error 403: Forbidden
(line  584) redirect  http://git-scm.com/book/en/v2/Git-Branching-Rebasing - permanently to https://git-scm.com/book/en/v2/Git-Branching-Rebasing
```

I've tried various combinations of http://appveyor.com, https://appveyor.com, http://www.appveyor.com, or https://www.appveyor.com and they all give the 403 when it's Sphinx doing the checking.

**Comment by tkelman** [comment]
reproduction that runs on appveyor: https://ci.appveyor.com/project/tkelman/julia/build/1.0.935/job/59fokak758mx63w7#L373

(running from https://github.com/tkelman/julia/tree/tk/linkcheck-repro)

This may be specific to the way in which Sphinx does its http requests to check links. We hopefully won't be using Sphinx here for all that much longer so I don't think we should worry too much about it, but this is something that other projects using Sphinx for their documentation (seems pretty much standard among Python projects) might hit too.

**Comment by FeodorFitsner** [comment]
Why is it trying to access www.appveyor.com in the first place? Is it only www.appveyor.com that shows this behaviour? Have you tried checking with Fiddler what's being sent/received exactly?

**Comment by Keno** [comment]
I believe it's checking that there are no dead links in our documentation and we link to appveyor.

**Comment by tkelman** [comment]
I'm not familiar with Fiddler, could look into it. appveyor.com or its various permutations is the only link we have that is giving a 403, though some others are returning empty or other unexpected behavior.

**Comment by tkelman** [comment]
@FeodorFitsner I bet it's related to this:
```
$ curl -I https://www.appveyor.com
HTTP/1.1 403 Forbidden
Content-Length: 58
Content-Type: text/html
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=46c0fa21167230cbfc302a6038ac68eafe1e4fe5ef6687ab433b1c1c782c500b;Path=/;Domain=www.appveyor.com
Date: Tue, 09 Aug 2016 21:34:26 GMT
```

**Comment by FeodorFitsner** [comment]
Interesting, what was the request then (including headers)?

**Comment by tkelman** [comment]
```
       -I, --head
              (HTTP/FTP/FILE) Fetch the HTTP-header only! HTTP-servers feature the com‐
              mand HEAD which this uses to get nothing but the header  of  a  document.
```

**Comment by FeodorFitsner** [comment]
OK, looks like HEAD requests are disabled on www.appveyor.com?

**Comment by tkelman** [comment]
Seems like. I'm not sure if I can change Sphinx's behavior here, or if it's not worth worrying about.

**Comment by tkelman** [comment]
Oh actually it looks like Sphinx fixed this in https://github.com/sphinx-doc/sphinx/pull/2389 but haven't released it yet.

**Pull request merged**
