### PR TITLE
give more informative socket errors, add some missing tests

### PR DESCRIPTION
**Pull request by jakebolewski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
:+1:

**Comment by tkelman** [comment]
This LGTM. It's certainly not related to this PR, but the AppVeyor build here https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.2272/job/99mu224bfvhrsd90 is an example of a recent failure mode on win64. It's timing out, but not due to a freeze in building the system image or running one of the first few tests. There's a major performance regression somewhere, look at how much longer than usual the linalg, dsp, fft, etc tests are taking.

**Comment by amitmurthy** [comment]
I went ahead and merged https://github.com/JuliaLang/julia/pull/10086 which had a similar unrelated error.

I would tend to think that something is wrong with Appveyor's infrastructure - we are not getting enough CPU cycles. Even the first linalg test didn't complete in the above case - https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.2271/job/dktlm0ytp6ca3ihu

**Comment by tkelman** [comment]
We've been seeing that failure mode where it freezes during the system image or on the first couple tests all along, intermittently. Since that type of failure never happens with the 32-bit Julia build I don't think it's AppVeyor's fault, it's something about the combination of AppVeyor and Win64 Julia (related to #7942 perhaps). You can hover over the line numbers and see that the build only takes about 10 minutes, the remaining 30 minutes it's frozen while trying to run the tests.

The new failure mode of just taking forever is not unique to AppVeyor, I've seen it recently on OSX Travis too. Opened #10094 for it, since it seems to be a performance regression that doesn't occur every time.

**Pull request merged**
