### PR TITLE
Allow opting out of `PartialOpaque` support via `Expr(:opaque_closure, ...)`

### PR DESCRIPTION
**Pull request by topolarity**
This can be useful for when an OpaqueClosure is desired, e.g., as an invalidation barrier or when you know it passes through an inference barrier naturally (in my case, a mutable type).

This is intentionally left undocumented for now.

### CODE REVIEW

**Comment by Keno** [comment]
I think at that point you might be beyond `@opaque` and should just generate the `Expr(:opaque_closure)` directly.

**Comment by topolarity** [comment]
> I think at that point you might be beyond `@opaque` and should just generate the `Expr(:opaque_closure)` directly.

Do you mean generating the IR for the closure by hand?

**Comment by Keno** [comment]
> Do you mean generating the IR for the closure by hand?

@eval $(Expr(:opaque_closure))

**Comment by topolarity** [comment]
Oh, you mean keeping the lowering changes but not changing the macro - yeah, that's fine by me

**Comment by Keno** [comment]
Yes

**Comment by topolarity** [comment]
@Keno OK to merge?

**Pull request merged**
