### PR TITLE
Bump OpenBLAS yet again

### PR DESCRIPTION
**Pull request by Keno**
The previous patch I had was incomplete.

### CODE REVIEW

**Comment by ViralBShah** [comment]
The number of files these things touch is a bit insane!

**Comment by Keno** [comment]
yeah, each checksum is a separate file because that's easy to check in a shell script, but we should probably do something more intelligent here, like have a tab-separated file like
```
OpenBlas+8 sha512 abcd...
OpenBlas+8 sha3 abcd...
```
Shouldn't be too bad to handle with standard unix tools.

**Comment by ViralBShah** [comment]
wouldn't standard unix tools break on windows?

**Comment by Keno** [comment]
No, our build system already depends on them, so we assume their presence on windows (either through cygwin or msys).

**Comment by PallHaraldsson** [comment]
Is there a reason to not go to the latest version (now 0.3.9)? Possibly this change was in the pipeline for a long time. I however see e.g. in latest version:

* Fixed cpu autodetection of Goldmont+, Cannon Lake and Ice Lake
and
* Improved speed of the AVX512 GEMM3M kernel on SkylakeX

**Pull request merged**
