### PR TITLE
Insert hardcoded backlinks to stdlib doc pages

### PR DESCRIPTION
**Pull request by LilithHafner**
This is #48814 times 25. It solves most of but not all of #50035.

To quote @mortenpi from https://github.com/JuliaLang/julia/pull/48814#pullrequestreview-1318913770

> Seems like a reasonable workaround for now, but should be removed once we have a proper fix.

I ran this code to generate the diff:
```julia
function insert_edit_link(source, target)
    prefix = """
    ```@meta
    EditURL = "$target"
    ```

    """
    contents = read(source, String)
    startswith(contents, prefix) && return
    occursin("EditURL", contents) && throw("\"EditURL\" already exists in $source")
    write(source, prefix * contents)
end

haslocaldocs(stdlib) = isfile("stdlib/$stdlib/docs/src/index.md")
isjll(stdlib) = endswith(stdlib, "_jll")

function go()
    stdlibs = filter!(!isjll, first.(values(Pkg.Types.get_last_stdlibs(VERSION))))
    localstdlibs = filter(haslocaldocs, stdlibs)
    for stdlib in localstdlibs
        insert_edit_link("stdlib/$stdlib/docs/src/index.md", "https://github.com/JuliaLang/julia/blob/master/stdlib/$stdlib/docs/src/index.md")
    end
    println("TODO: $(filter(!haslocaldocs, stdlibs))")
end

go()
# TODO: ["ArgTools", "SparseArrays", "NetworkOptions", "Downloads", "LibCURL", "SuiteSparse", "Pkg", "Tar", "SHA"]
```

### CODE REVIEW

**Comment by LilithHafner** [comment]
This and the 7 PRs that I just linked to it fix https://github.com/JuliaLang/julia/issues/50035.

While it is unfortunate to hardcode these URLs, hardcoding canonical URLs in a project that spans many repos seems like a reasonable use of hardcoding. Also, it is unacceptable to have these links broken because it is uninviting to potential new contributors.

<details>
<summary>The final code I used is</summary>

```julia
function insert_edit_link(source, target)
    prefix = """
    ```@meta
    EditURL = "$target"
    ```

    """
    contents = read(source, String)
    startswith(contents, prefix) && return
    occursin("EditURL", contents) && throw("\"EditURL\" already exists in $source")
    write(source, prefix * contents)
end

haslocaldocs(stdlib) = isfile("stdlib/$stdlib/docs/src/index.md")
isjll(stdlib) = endswith(stdlib, "_jll")

function go()
    stdlibs = filter!(!isjll, first.(values(Pkg.Types.get_last_stdlibs(VERSION))))
    for stdlib in filter(haslocaldocs, stdlibs)
        insert_edit_link("stdlib/$stdlib/docs/src/index.md", "https://github.com/JuliaLang/julia/blob/master/stdlib/$stdlib/docs/src/index.md")
    end
    println("TODO: $(filter(!haslocaldocs, stdlibs))")
end

go()
# TODO: ["ArgTools", "SparseArrays", "NetworkOptions", "Downloads", "LibCURL", "SuiteSparse", "Pkg", "Tar", "SHA"]

for stdlib in ["ArgTools", "SparseArrays", "NetworkOptions", "Downloads", "LibCURL", "Tar", "SHA"]
    git_url = split(collect(readlines("stdlib/$stdlib.version"))[3], " := ")[2]
    target = "../../dev/_$stdlib"
    isdir(target) || run(`git clone $git_url $target`)
    cd(target) do
        insert_edit_link("docs/src/index.md", "$(splitext(git_url)[1])/blob/master/docs/src/index.md")
        run(`git checkout -b lh/hardcode-backlinks`)
        run(`git commit docs/src/index.md -m "Hardcode doc edit backlink"`)
    end
end
```

I created the actual pull requests by hand.

</details>

**Comment by fredrikekre** [comment]
I believe all of this will be fixed by https://github.com/JuliaLang/julia/pull/47105, cc @mortenpi

**Comment by LilithHafner** [comment]
That would be lovely! Though I'm having trouble finding a recently merged PR to Doccumetner.jl that would fix this.

**Comment by fredrikekre** [comment]
See references under "The handling of remote repository (e.g. GitHub) URLs has been overhauled" in Documenters changelog.

**Comment by mortenpi** [comment]
> I believe all of this will be fixed by #47105, cc @mortenpi

Yes. This specific issue was the major motivation of the remote link overhaul.

#47105 _is_ running into some trouble with our CI setup though that needs to be debugged. I'll try to get to it this week, but if someone else beats me to it, that would make me very happy :slightly_smiling_face: 

I would suggest closing the standard library PRs before they get merged and reverting the SHA.jl one though.

**Comment by LilithHafner** [comment]
Thanks for making a better and more general fix than this! I was going to hack it because these links have been broken for a long time, but I'd much rather see it fixed in Documenter.jl. Thanks! I'll make a PR to revert the SHA one once https://github.com/JuliaLang/julia/pull/47105 merges.

**Comment by LilithHafner** [comment]
Three months have passed and the issue keeps on getting reported, I'm going to merge this as a stopgap if nobody objects. We can always revert it later

cc @fredrikekre @mortenpi

**Comment by mortenpi** [comment]
I guess it makes sense to have the workaround for now. There's a WIP "proper" fix in https://github.com/JuliaDocs/Documenter.jl/pull/2372, but it's still not fully working (inviting a review there, to figure out why that is), and I can't really promise a timeline.

**Pull request merged**
