### PR TITLE
Allow both EAUTH and ERROR for bad URL test in LibGit2 tests.

### PR DESCRIPTION
**Pull request by fredrikekre**
See https://github.com/JuliaLang/julia/pull/32219#issuecomment-500075737

### CODE REVIEW

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
Actually, I think it's the other line (or maybe both)

**Comment by fredrikekre** [comment]
Failures now seem to be on https://github.com/JuliaLang/julia/pull/32268/files#diff-e6061806c77edc60566965a63145f5a4R71 though. I think we always get a GitError though, so the line you refered to is fine I think?

**Comment by Keno** [comment]
My point is that this is not the line that the referenced PR changed

**Comment by fredrikekre** [comment]
:man_facepalming:

**Comment by KristofferC** [comment]
Backporting since this happens on CI for 1.2-RC2.

**Pull request merged**
