### PR TITLE
cherry-pick of more bugfixes from fixing #265

### PR DESCRIPTION
**Pull request by vtjnash**
this is a backport of additional fixes I had made to avoid segfaults on my #265-fix branch (#17057)

### CODE REVIEW

**Comment by tkelman** [comment]
Are there tests for any of these?

**Comment by tkelman** [comment]
Also it would be preferable if we could use the term "backport" to mean exactly one thing - if the target branch is still master and the PR they come from hasn't been merged yet, then this is different from what we use the "backport pending" labels to track. Better to call this cherry pick or something distinct so it doesn't look related to release tracking.

**Comment by vtjnash** [comment]
bump

**Comment by tkelman** [comment]
This doesn't cherry-pick cleanly on release-0.5. If these are fixing anything important, please open a PR against tk/backports-0.5.1.

**Comment by StefanKarpinski** [comment]
Since #265 wasn't fixed on 0.5, I would imagine this is not relevant?

**Comment by tkelman** [comment]
this is a confusingly named pr, it's miscellaneous bugfixes that jameson did while working on 265, but split out to a separate branch here

**Comment by vtjnash** [comment]
Right. This is split out because it wasn't #265-related, even though they were developed during that PR

**Pull request merged**
