### PR TITLE
RFC: Patch openblas to add 64_ suffix when using 64 bit ints

### PR DESCRIPTION
**Pull request by tkelman**
~~Not done yet, but I think~~ I've got part 2 of https://github.com/JuliaLang/julia/issues/4923#issuecomment-54724314 mostly finished - when 1 & 3 are completed this should close JuliaLang/julia#4923. I still need to add the install steps, license link, etc for `objconv` on OSX which should be fairly short, and the Julia macro in base to account for the renamed functions. See https://github.com/JuliaLang/julia/pull/8734#issuecomment-59978800 for instructions on how to properly test this

### CODE REVIEW

**Comment by andreasnoack** [comment]
@tkelman I think this is wrongly appending the `LAPACKE` symbols with `_`. The `LAPACKE` symbols are part of the C API so they shouldn't have an underscore and they don't have before the renaming.

**Comment by tkelman** [comment]
That was intentional. The suffixes are on everything exported from the library. https://github.com/JuliaLang/julia/issues/4923#issuecomment-54724314

The ABI compatibility collisions are just as likely to happen here with a system-blas-provided LAPACKE, which will conventionally be built with 32 bit ints.

**Comment by andreasnoack** [comment]
But the suffix should only be `64` for the `LAPACKE` symbols not `64_`.

**Comment by tkelman** [comment]
I don't think the underscore matters enough to complicate the implementation of the renaming or the call-site code to use a suffix that depends whether or not the API is mimicking Fortran. Using a uniform `64_` suffix everywhere was far simpler, and though it looks a little strange for C functions, is it really an issue?

**Comment by andreasnoack** [comment]
Nevermind. I mistakenly thought the wrong suffix made it problematic to use the `LAPACKE` symbols with different LAPACKs, but since `blasfunc` also appends everything with `64_` it's not the case.

**Comment by tkelman** [comment]
We already use a few cblas api's for complex dot (ref #8062) and those have been working fine, I don't think LAPACKE would be any different. If it's package code, then checking if `blas_vendor() == :openblas64` should make this not too complicated to handle.

**Comment by stevengj** [comment]
In stevengj/PyCall.jl#65 we are still having troubles with conflicts between numpy and Julia's openblas.

Maybe we should also rename `libopenblas.so` to make sure that numpy (and other libraries) doesn't confuse it for the regular libopenblas?

**Comment by staticfloat** [comment]
Python shouldn't be finding Julia's `openblas`, unless one of two things are happning:

* Environment variables from Julia are leaking into Python; causing Python's `dlopen()` to find the `openblas.so` we've sneaked away into Julia's private library directory

* The python process is actually embedded within Julia and is not loading `openblas.so` at all, but is instead using the symbols already present in the Julia processes namespace.

For the first option, I would think that appropriate manipulation of `ENV` would solve the issue.  For the second, I'm not sure what we can do.  I don't really know `PyCall` very well, so I'm just speculating here.

**Comment by stevengj** [comment]
@staticfloat, since `libpython` is loaded within the running Julia process, surely it sees the same environment variables as `julia`?

PyCall isn't doing anything too special here.  It just loads `libpython`, and then `libpython` loads numpy and numpy somehow loads openblas.   I'm not sure how numpy actually decides how to load blas/lapack.

**Comment by stevengj** [comment]
See also stevengj/PyPlot.jl#140 for a similar-looking error.

**Comment by staticfloat** [comment]
Is this error easily reproducible?  Either of the two things above could be happening in this case.  The reason `libpython` is freaking out when trying to load `libopenblas` is because it's finding the wrong `libopenblas` because of something it's inherited from the Julia process.  We may be able to manipulate the `ENV` dict before loading `libpython`, or pass the proper flags to `dlopen()` when starting up `libpython` to insulate it from the Julia process.

**Comment by stevengj** [comment]
Unfortunately, I've never seen this error myself; it seems to mainly happen on Ubuntu, which I'm not running.    What in the `ENV` would be causing problems?

**Comment by tkelman** [comment]
Im not opposed to renaming it but that will have some fiddly consequences for some downstream packages that need to link to it.

**Comment by staticfloat** [comment]
After thinking about it a bit, reading a [bit of reference material](https://wiki.debian.org/RpathIssue), and looking over Julia source code again, I'm pretty confident that what's happening is that `numpy` isn't finding `libopenblas.so` at all, since a `libopenblas.so` is already loaded into the process space.  So nothing we do here short of unmapping `libopenblas.so` before loading `PyCall` is going to work, and that's crazy talk.

We should probably entertain the notion of renaming the library.  Since most packaged versions of `libopenblas.so` don't have the 64 bit naming like we have with Julia-built openblas, this shouldn't be too much work on package managers.  @tkelman what difficulties do you foresee?

**Comment by stevengj** [comment]
@tkelman, I can't find any Julia packages that contain the string `libopenblas`, so it doesn't seem like any of them `ccall` it directly if that's what you're worried about.

**Comment by tkelman** [comment]
I meant for julia packages like scs.jl that link against julia's ilp64 openblas at pkg.build time. I dont think there are too many of these. cc @mlubin

**Comment by stevengj** [comment]
Oh, I see, you are worried about packages that build external libraries and link it to Julia's openblas.

**Comment by mlubin** [comment]
I don't see anything in SCS.jl that explicitly depends on the name of the openblas library.

**Comment by stevengj** [comment]
SCS only mentions it in a comment for how they build their Windows binaries:
```
# Windows binaries built in Cygwin as follows:                                  
# CFLAGS="-DDLONG -DCOPYAMATRIX -DLAPACK_LIB_FOUND -DCTRLC=1 -DBLAS64 -DBLASSUF\
FIX=_64_" LDFLAGS="-L$HOME/julia/usr/bin -lopenblas" make CC=x86_64-w64-mingw32\
-gcc out/libscsdir.dll                                                          
# mv out bin64                                                                  
# make clean                                                                    
# CFLAGS="-DDLONG -DCOPYAMATRIX -DLAPACK_LIB_FOUND -DCTRLC=1" LDFLAGS="-L$HOME/\
julia32/usr/bin -lopenblas" make CC=i686-w64-mingw32-gcc out/libscsdir.dll      
# mv out bin32                                                                  
```
But SCS is the only package I've found so far that does anything like this.

**Comment by staticfloat** [comment]
I remember; `SCS.jl` used to explicitly link to `libopenblas.so`, but then we realized we didn't need to do so, we can just leave the OpenBLAS functions undefined in the `.so` and leave it up to the dynamic linker to supply them to the `SCS` binary at link-time because they already exist within the Julia processes' namespace.

**Comment by staticfloat** [comment]
So in a sense, with `SCS.jl`, we are taking advantage of the very problem we are faced with in the `numpy` case.

**Comment by tkelman** [comment]
Yeah looks like in that case i'd just need to rebuild new windows binaries since the windows linker doesnt allow undefined symbols

**Comment by staticfloat** [comment]
This gives me an idea; if we don't want to rename `libopenblas.so`, we can probably dynamically generate stub functions (in julia!) that are exported and callable by `numpy`, thinking that it's using a non-64bit interface.  As amazingly cool as that would be, it's probably more trouble than it's worth.

**Comment by tkelman** [comment]
For blas that wouldnt be bad but anything in lapack with integer pivot vectors would be more work

**Comment by nalimilan** [comment]
FWIW, in Fedora, the ILP64 OpenBLAS is called `libopenblas64.so` (unfortunately, it doesn't add the `64` suffix to symbols). This sounds right to me, since the ABI is incompatible with the "standard" `libopenblas.so`.

**Comment by stevengj** [comment]
@nalimilan, this means that we shouldn't use `libopenblas64` either, because that also has a different ABI.   

We should just use `libopenblas_julia`, to make sure there are no accidental name collisions with distro choices.

**Comment by tkelman** [comment]
Out of curiousity is it marked as conflicting with the lp64 package? Or just user beware, better not try to use both in same app?

**Comment by nalimilan** [comment]
No, it doesn't conflict. That would be even more impractical since you wouldn't be able to install it if you have at least one app using the LP64 version.

But I don't think the whole issue has really been thoroughly considered. Maybe we could get the symbols to be renamed if we could find some agreement with upstream about what's the right solution.

**Comment by stevengj** [comment]
The whole point is that this is a private copy of the libopenblas library for use in Julia, whose ABI is unlikely to match that installed by a distro or expected by any other library we might link in.  Why shouldn't we name it whatever we want?

**Comment by tkelman** [comment]
I'd recommend you try to do so before it accumulates too many dependents.

**Comment by tkelman** [comment]
We can name it whatever we want but there are libraries (elemental.jl will also need to handle this) that are capable of using our custom abi version. So it should be a sane and predictable name and we should try not to change it any more often than we have to. Once should be fine.

**Comment by nalimilan** [comment]
Yes, let's avoid repeating the previous discussion. :-)

I agree it's not an issue if it's private, but if the same convention was used in Fedora as in Julia, I would be able to use the ILP64 OpenBLAS in my RPM package without risking any conflicts, which would be nice. If all distributions chose the same convention, more projects could easily use ILP64. OTC, if two distributions use a different one, it will never happen, which could also hurt Julia in cases where you'd like calls to an external library to support large arrays.

I've filed an issue at https://github.com/JuliaLang/julia/issues/4923.

**Comment by nalimilan** [comment]
For the record, Fedora and EPEL now ship with an additional ILP64 OpenBLAS package built with the `64_` suffix, and Julia has just started using it.

**Comment by eschnett** [comment]
Do they actually use a suffix of `64_` (and not `_64`)? For example, Julia's OpenBLAS library is called `libopenblas64_.dylib` on my system, which is quite a strange name to choose. (Putting the underscore before the `64` or omitting the underscore would be more natural.)

I understand the idea that the mangled 32-bit names already end with an underscore on most systems, so adding `64_` to the mangled name seems natural, although adding `_64` to the un-mangled name might have made more sense (since it allows calling the 64-bit functions from Fortran, which might not be possible if the Fortran compiler uses a non-underscore naming convention). I also understand that that's a non-issue on Linux, or with gcc, or for Julia.

I want to create a build recipe for a 64-bit OpenBlas for Spack <https://github.com/LLNL/spack>, and I'd like to stick with the "standard", hence my question: What underscore name mangling and what library names do Fedore and EPEL use? Is the library called `libopenblas64_.so`, and does `nm` list a function called `_dgemm_64_`?

**Comment by tkelman** [comment]
See https://github.com/JuliaLang/julia/issues/4923#issuecomment-59646241. Adding a uniform suffix at the end of all symbols was done for simplicity's sake. The combination of Julia and OpenBLAS appears to be the first widespread open source example of using ILP64 BLAS and LAPACK, so we are pretty much making up our own convention here. Given how much more widespread gfortran is than any other modern Fortran compiler, I don't think we should worry much about other Fortran name mangling conventions until someone seriously wants to build Julia with such a compiler. (`ifort` on Windows will need this, but since that's likely to be used with MKL we aren't in control of the symbol names there.)

Renaming the BLAS/LAPACK symbols does make it slightly harder to switch between LP64 and ILP64 for a pure Fortran application where it might be as simple as `-fdefault-integer-8` otherwise. I think imposing a bit more trouble on the increasingly rare case of pure Fortran applications is worth clearing up the name collisions and ensuing segfaults from trying to load separate LP64 and ILP64 library versions simultaneously.

**Comment by eschnett** [comment]
@tkelman I completely agree that the symbols need to have a different name; everything else just leads to confusion and segfaults. It's also not really "slightly harder to switch" -- all that's missing are the respective interface declarations for Fortran...

**Pull request merged**
