### PR TITLE
rename String => AbstractString

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This seems like a pretty big improvement in the intention of the `AbstractString` type. It also clears the path for using the `String` name for the standard string type, i.e. a future replacement for both `ASCIIString` and `UTF8String`.

### CODE REVIEW

**Comment by stevengj** [comment]
I have to say that after a couple of months of this I'm really not enjoying typing `AbstractString` all over the place, nor am I enjoying explaining it to newbies.   I would much prefer @ivarne's suggestion of keeping `String` abstract and using `Str` for a future unified UTF-8/ASCII type, analogous to `Integer` and `Int`.

Can we revisit this choice?  (It reminds me of the array+scalar thing in #5810.)

**Comment by nalimilan** [comment]
`Integer` vs. `Int` is IMHO one of the most confusing details about types, so I'm not in favor of introducing another similar subtlety. I think this is different from the array+scalar issue, as here there's a clear possibility of mistakes, with people using `String` instead of `Str` and not getting the specialized code they expect.

**Comment by stevengj** [comment]
@nalimilan, making several similar naming choices arguably *reduces* confusion.  Unless you are proposing to rename `Integer` to `AbstractInteger` (ugh), it seems better to have *more* parallels to this rather than making `Integer` the exception, so that the distinction has a better chance of sinking in.

The problem I have is that it is easy to remember to write `f(s::String) = ...` for any function that is supposed to work with arbitrary strings, and hard to remember (and harder to type) `f(s::AbstractString)`.   (There is the same problem with arrays: most code that operates on `Array` should really be for `AbstractArray`, but even experienced Julia programmers often forget to type the `Abstract`.   Adding *more* names like this does not seem an improvement.)

**Comment by nalimilan** [comment]
Currently you cannot be consistent with both the `Integer`/`Int` and `AbstractArray`/`Array` pairs. I could make the same argument against your proposal: do you think we should rename `Array` to `Arr`? :-p

So the consistency argument can only hold if we choose one rule and stick to it... I think this discussion already started somewhere, though I don't remember on which issue/PR.

**Comment by stevengj** [comment]
@nalimilan, the point is that the consistency argument works both ways, so basically it cancels out.

What remains is that:

* shorter is better (as long as it is recognizable: `Arr` fails this test, unfortunately).
* types are most commonly specified in function arguments, where accidental overtyping is worse than accidental undertyping

**Pull request merged**
