### PR TITLE
Fill out linalg tests

### PR DESCRIPTION
**Pull request by kshyatt**
I found a bug in taking the inverse of an `Eigen` which is hopefully fixed now. I also added tests to get some of `base/linalg` to 100% coverage.

### CODE REVIEW

**Comment by andreasnoack** [comment]
A long lived one. I made that error in March 2013. We should (again) consider saving the symmetric and general eigensolutions as separate types. It is a shame to invert the vectors when you know that the problem is symmetric, but that is for another pr. Thanks for fixing this.

**Comment by kshyatt** [comment]
Looks like I got hit by the AppVeyor timeout. Everyone ok with this change?

**Comment by ViralBShah** [comment]
Nice find. I think given its passing on travis, should be good to merge.

**Comment by kshyatt** [comment]
But, but, https://github.com/JuliaLang/julia/pull/12086#issuecomment-120238293.

Also I think this PR really demonstrates the value of getting files to 100% coverage, considering `base/linag/eigen.jl` had only 5 lines untested and yet this little :bug: was hiding in there.

**Comment by StefanKarpinski** [comment]
Figuring out how to get to 100% coverage is definitely something we should do.

**Comment by tkelman** [comment]
restarted, passing now

agreed with @andreasnoack that symmetric/hermitian eigenproblems should probably be a different type than nonsymmetric some day

**Pull request merged**
