### PR TITLE
Remove MSVC and ICC stuff in the build system.

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by vchuravy** [comment]
@barche seems to embed Julia with MSVC? https://github.com/JuliaLang/julia/pull/42255#issuecomment-933594279
Bart do you need to build Julia with MSVC as well?

**Comment by vchuravy** [comment]
> Does anyone know if the ICC/IFORT stuff works?

No clue, also I wonder if it matters since https://software.intel.com/content/www/us/en/develop/blogs/adoption-of-llvm-complete-icx.html

**Comment by ViralBShah** [comment]
icc/ifortran are quite problematic: https://github.com/JuliaLang/julia/issues/35241#issuecomment-673998692

**Comment by barche** [comment]
> @barche seems to embed Julia with MSVC? [#42255 (comment)](https://github.com/JuliaLang/julia/pull/42255#issuecomment-933594279)
> Bart do you need to build Julia with MSVC as well?

No, there is no need to build Julia with MSVC to use MSVC for embedding. I don't really do this embedding myself, but it comes up from time to time when people try to build libcxxwrap-julia with MSVC. Since this PR only changes build system files from Julia, it will have no impact for CxxWrap.

**Comment by giordano** [comment]
> No, there is no need to build Julia with MSVC to use MSVC for embedding.

I thought that embedding in MSVC would require having built Julia with the same standard C++ library.

**Comment by barche** [comment]
> I thought that embedding in MSVC would require having built Julia with the same standard C++ library.

Because the interface is C, this is not required (and I have never attempted it). There are corner cases, however, the most obvious one being that you can't allocate in the MSVC code and free in Julia and vice-versa. So this is not as robust as the BinaryBuilder solution, but useful for local development or for interfacing with libraries that only build with MSVC.

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
