### PR TITLE
[release-1.6] Update the checksums for libuv

### PR DESCRIPTION
**Pull request by DilumAluthge**
Here is the script used to generate this pull request:

```
cd $(mktemp -d)
git clone git@github.com:JuliaLang/julia.git
cd julia
git checkout release-1.6
git checkout -B dpa/1.6-refresh-libuv-checksums
make -f contrib/refresh_checksums.mk libuv
git add -A
git commit -m "[release-1.6] Update the checksums for libuv"
git push -f origin dpa/1.6-refresh-libuv-checksums
```

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Thank you!

**Comment by ararslan** [comment]
Actually, sorry to ask this but could we make this a PR against master then backport the commit to 1.6? Seems the checksums are similarly incorrect on master.

**Comment by DilumAluthge** [comment]
I think the checksums are actually correct on `master`. When I run `make -f contrib/refresh_checksums.mk libuv` on `master`, there are no changes.

**Comment by ararslan** [comment]
>  think the checksums are actually correct on master.

I think these are the old ones: https://github.com/JuliaLang/julia/blob/master/deps/checksums/libuv#L33-L34

**Comment by DilumAluthge** [comment]
I think those are actually the correct ones for master, though

**Comment by DilumAluthge** [comment]
An easy way to verify is to do `make USE_BINARYBUILDER=0` and then check that the working directory is clean.

Actually, we have once-daily scheduled Buildkite build that does a `make USE_BINARYBUILDER=0` build off of the latest version of the `master` branch. If you look at the logs for a recent build of that (https://buildkite.com/julialang/julia-master-scheduled/builds/334#28d32674-d15e-48c1-8638-fdf9e0c91850), you'll see that the working directory is clean.

**Comment by ararslan** [comment]
This took me a lot more thinking than I think was warranted but I've finally managed to un-confuse myself. You're right, this only needs to be applied to release-1.6.

**Comment by DilumAluthge** [comment]
I only checked master. Is release-1.7 good, or does it need to be updated?

**Comment by ararslan** [comment]
1.7 is good.

**Pull request merged**
