### PR TITLE
RFC: remove i18n

### PR DESCRIPTION
**Pull request by KristofferC**
This file has not been relevantly touched in over 5 years, it also seems completely unused. I'm guessing it has to do with localization but it seems just like bitrot at this point? Ok to delete?

### CODE REVIEW

**Comment by KristofferC** [comment]
@ararslan why does this need news? These are unexported, undocumented functions, that doesn't do anything. Adding news for this would just clutter the news file.

**Comment by StefanKarpinski** [comment]
Not to mention that this stuff literally does not do anything.

**Comment by ararslan** [comment]
>  why does this need news?

In this off chance someone somewhere wondered why it suddenly disappeared. It's entirely possible that someone's code is calling `Base.I18n.locale()`.

**Comment by StefanKarpinski** [comment]
¯\\\_(ツ)\_/¯

**Comment by KristofferC** [comment]
Wouldn't they just write `"" ` instead?

**Comment by quinnj** [comment]
turns out AMQPClient.jl was using this, but yeah, it was just checking if `isempty(Base.I18n.locale())`, so...........pretty easy fix. 😆

**Comment by vtjnash** [comment]
Apparently, it's just have a rough life: https://github.com/JuliaLang/julia/commit/33b32fce5509132b1b811cb744559b64782a0449

**Pull request merged**
