### PR TITLE
Backports release 1.10.5

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #51351 
- [x] #52678 
- [x] #54201 
- [x] #54605 
- [x] #54634 
- [x] #54635 
- [x] #54645 
- [x] #54671 
- [x] #54672 
- [x] #54704 
- [x] #54713 
- [x] #54781 
- [x] #54837 
- [x] #54815 
- [x] #55141 
- [x] #55178 
- [x] #55197 
- [x] #55209 
- [x] #55203 
- [x] #54769 
- [x] #54791 
- [x] #55070 
- [x] #54624 
- [x] #54690 
- [x] #55084 

Need manual backport:
- [ ] #52505 
- [ ] #53373 
- [ ] #53984 
- [ ] #54276 
- [ ] #54669 
- [ ] #54871 

Contains multiple commits, manual intervention needed:
- [ ] #52854 
- [ ] #53218 
- [ ] #53833 
- [ ] #54303 
- [ ] #52694 
- [ ] #54737 
- [ ] #54738 
- [ ] #55052 

Non-merged PRs with backport label:
- [ ] #55220 
- [ ] #55169 
- [ ] #55013 
- [ ] #51479 
- [ ] #50813 
- [ ] #50157 
- [ ] #41244

### CODE REVIEW

**Comment by wsmoses** [comment]
@KristofferC any ETA on a release? We've gotten a bunch of issues recently that seem to be related to the GC fix here

**Comment by KristofferC** [comment]
Anyone know what's up with https://buildkite.com/julialang/julia-release-1-dot-10/builds/340#0190e455-5507-4427-99fb-76a77ad5b4c9

```
C:/workdir/src/jl_uv.c: In function 'walk_print_cb':
C:/workdir/src/jl_uv.c:44:12: error: assignment to 'uv_os_fd_t' {aka 'void *'} from 'uv_pid_t' {aka 'int'} makes pointer from integer without a cast [-Wint-conversion]
   44 |         fd = uv_process_get_pid((uv_process_t*)h);
      |  
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54851#issuecomment-2248095381) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/884c71e_vs_48d4fd4/report.html) is available.

**Comment by KristofferC** [comment]
Nanosoldier looks ok.

**Comment by KristofferC** [comment]
I don't know why the Windows build do not succeed.

**Comment by KristofferC** [comment]
Now

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./codegen.o: in function `add_named_global':
C:/workdir/src/codegen.cpp:507:(.text+0x271f7): undefined reference to `__imp___stack_chk_guard'
```

**Comment by giordano** [comment]
Last error is
```
 g++ -m64  -shared  -L/c/workdir/usr/lib/julia -L/c/workdir/usr/lib -L/c/workdir/usr/bin -o /c/workdir/usr/lib/julia/sys.dll -Wl,--whole-archive /c/workdir/usr/lib/julia/sys-o.a -Wl,--no-whole-archive -ljulia-internal -ljulia $([ WINNT = WINNT ] && echo '' -lssp --disable-auto-import --disable-runtime-pseudo-reloc)
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#1.o): in function `round':
./float.jl:396:(.text+0x2e42): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x2e6f): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x516ea): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x52f12): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x52f5b): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0xe1a04): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0xe1aed): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x1227cc): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#2.o): in function `round':
./float.jl:393:(.text+0x89bb): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x77e45): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x1424e9): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#3.o): in function `round':
./float.jl:396:(.text+0x18ecf): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x40123): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x4016a): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x401d1): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0xba321): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#3.o):./float.jl:396: more undefined references to `rint' follow
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#3.o): in function `round':
./float.jl:393:(.text+0xba424): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#4.o): in function `round':
./float.jl:393:(.text+0x3552d): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:396:(.text+0x14746c): undefined reference to `rint'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#5.o): in function `round':
./float.jl:393:(.text+0x27a2): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x819d): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x81e6): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./float.jl:393:(.text+0x8231): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#6.o): in function `round':
./float.jl:393:(.text+0x5dd12): undefined reference to `trunc'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/workdir/usr/lib/julia/sys-o.a(text#6.o):./float.jl:393: more undefined references to `trunc' follow
collect2.exe: error: ld returned 1 exit status
```
which was probably addressed by #53672.

**Comment by KristofferC** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54851#issuecomment-2280269214) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/report.html) is available.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["EulerAngles", "JuliaInterpreter", "SubSIt", "AesKeywrapNettle", "Bonobo", "ArnoldiMethodTransformations", "BundledWebResources", "Pyehtim", "Dynesty", "SmallCouplingDynamicCavity", "BaytesOptim", "RiskMeasures", "DECAES", "MeshIntegrals", "OptimizationBase"])`

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/54851#issuecomment-2282204867) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/report.html) is available.

**Comment by KristofferC** [comment]
These look a bit weird:




-------------

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/ArnoldiMethodTransformations.primary.log

```
  Got exception outside of a @test
  TypeError: in <:, expected Type, got Vararg
  Stacktrace:
    [1] #s11#5
      @ ~/.julia/packages/StaticArrays/DBECI/src/util.jl:20 [inlined]
    [2] var"#s11#5"(T::Any, ::Any, ::Any)
      @ StaticArrays ./none:0
    [3] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
      @ Core ./boot.jl:602
    [4] macro expansion
      @ ~/.julia/packages/StaticArrays/DBECI/src/SMatrix.jl:35 [inlined]
    [5] SArray
      @ ~/.julia/packages/StaticArrays/DBECI/src/SMatrix.jl:32 [inlined]
    [6] swap12!(R::Matrix{Float64}, i::Int64, Q::Matrix{Float64})
      @ ArnoldiMethod ~/.julia/packages/ArnoldiMethod/5fDBS/src/schursort.jl:403
    [7] swap!
      @ ~/.julia/packages/ArnoldiMethod/5fDBS/src/schursort.jl:479 [inlined]
    [8] rotate_right!(R::Matrix{Float64}, from::Int64, to::Int64, Q::Matrix{Float64})
      @ ArnoldiMethod ~/.julia/packages/ArnoldiMethod/5fDBS/src/schursort.jl:27
    [9] partition_schur_three_way!(R::Matrix{Float64}, Q::Matrix{Float64}, groups::Vector{Int64})
      @ ArnoldiMethod ~/.julia/packages/ArnoldiMethod/5fDBS/src/run.jl:348
```

----------------

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/RiskMeasures.primary.log

```
ERM: Error During Test at /home/pkgeval/.julia/packages/RiskMeasures/WtuMO/test/runtests.jl:14
  Test threw exception
  Expression: isapprox(ERM(x̃, 0.0), ERM(x̃, 1.0e-5); atol = 0.001)
  UndefVarError: `ERM` not defined
  Stacktrace:
   [1] macro expansion
     @ /opt/julia/share/julia/stdlib/v1.10/Test/src/Test.jl:669 [inlined]
   [2] macro expansion
     @ ~/.julia/packages/RiskMeasures/WtuMO/test/runtests.jl:14 [inlined]
   [3] macro expansion
     @ /opt/julia/share/julia/stdlib/v1.10/Test/src/Test.jl:1577 [inlined]
   [4] top-level scope
     @ ~/.julia/packages/RiskMeasures/WtuMO/test/runtests.jl:10
```

------------

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/SmallCouplingDynamicCavity.primary.log


```
inferenceSIscheme: Error During Test at /home/pkgeval/.julia/packages/SmallCouplingDynamicCavity/IJlmV/test/testSI.jl:80
  Got exception outside of a @test
  MethodError: no method matching run_SCDC(::EpidemicModel{SI, SimpleGraph{Int64}}, ::typeof(obsprob), ::Float64, ::Vector{Int64}, ::Float64, ::Vector{Float64}; μ_cutoff::Float64)
  
  Closest candidates are:
    run_SCDC(::EpidemicModel{TI, TG}, ::Function, ::Float64, !Matched::Int64, ::Float64, !Matched::Float64; μ_cutoff, n_iter_nc, damp_nc, callback) where {TI<:SmallCouplingDynamicCavity.InfectionModel, TG<:(Union{Vector{<:AbstractGraph}, var"#s20"} where var"#s20"<:AbstractGraph)}
     @ SmallCouplingDynamicCavity ~/.julia/packages/SmallCouplingDynamicCavity/7Ac4A/src/message_passing_func.jl:227
```

--------------

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/b4b1646_vs_48d4fd4/AesKeywrapNettle.primary.log

```
     Testing AesKeywrapNettle

Testing failed after 1.3s

ERROR: LoadError: expected package `AesKeywrapNettle [d0ff3c94]` to exist at path `/home/pkgeval/.julia/packages/AesKeywrapNettle/iVg1c`
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /opt/julia/share/julia/stdlib/v1.10/Pkg/src/Types.jl:70
  [2] collect_fixed!(env::Pkg.Types.EnvCache, pkgs::Vector{Pkg.Types.PackageSpec}, names::Dict{UUID, String})
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:312
  [3] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:377
  [4] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, level::Pkg.Types.UpgradeLevel; skip_writing_project::Bool, preserve::Nothing)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1537
  [5] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, preserve::Nothing, update_registry::Bool, skip_writing_project::Bool, kwargs::@Kwargs{io::Base.DevNull})
    @ Pkg.API /opt/julia/share/julia/stdlib/v1.10/Pkg/src/API.jl:351
```

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AesKeywrapNettle", "ArnoldiMethodTransformations", "RiskMeasures", "Bonobo", "SmallCouplingDynamicCavity", "JuliaInterpreter", "SubSIt"])`

**Pull request merged**
