### PR TITLE
create UUIDs stdlib package

### LINKED ISSUE #25590: what to do with UUID?
Once https://github.com/JuliaLang/julia/pull/25455 is merged, we'll depend on UUIDs in Base, so the type definition and basic methods have to be moved back out of Random. Should we have a `UUIDs` stdlib package and add methods for the other ways of generating UUIDs, but leave the type definition in Base for internal use? We already have working code for UUID versions 1, 3, 4 & 5 and version 2 seems to be pretty marginal, so we have pretty complete UUID support already, it could just stand to be wrapped up a little more nicely.

### PR DESCRIPTION
**Pull request by JeffBezanson**
closes #25590

### CODE REVIEW

**Comment by vtjnash** [comment]
Looking at the PR, this seems like too much code division. I think we should just keep these couple of functions in Random.

**Review by StefanKarpinski — APPROVED** [review]

**Comment by JeffBezanson** [comment]
But nothing else in Random has to do with UUIDs, and nothing in UUIDs has to do with random number generation (it's only a user of it). I don't see why those would need to be grouped together.

**Comment by StefanKarpinski** [comment]
Also, this is going to end up being a package that implements all five UUID generation methods and therefore depends on SHA and MD5 (which will be, as [discussed](#25590), moved into stdlib). Presumably one doesn't want Random to gratuitously depend on those packages at that point.

**Comment by oxinabox** [comment]
Shall a new issue be created: "Add UUID-XYZ functionality to stdlib",
with move SHA.jl and MD5.jl as subtasks?

**Comment by StefanKarpinski** [comment]
Sure. I would make the tasks "UUID: add uuid3", etc.

**Pull request merged**
