### PR TITLE
boost multiplication of sparse with strided and vice versa

### LINKED ISSUE #32172: SparseMatrixCSC multiplied by Adjoint
The implementation of matrix multiplication `A * B` is incomplete when one of the matrices is of the type `SparseMatrixCSC` and the other one is of the type `Adjoint` or `Transpose`.

```julia
julia> A = sprandn(10000, 10000, .0001);

julia> B = randn(10000, 2);

julia> C = randn(2, 10000);
```
Matrices `B` and `C'`are of the same size. But there is a huge difference in performance when multiplying them with `A`.

```julia
julia> @benchmark A * B
BenchmarkTools.Trial: 
  memory estimate:  156.33 KiB
  allocs estimate:  2
  --------------
  minimum time:     131.769 μs (0.00% GC)
  median time:      197.825 μs (0.00% GC)
  mean time:        214.868 μs (8.74% GC)
  maximum time:     31.917 ms (99.32% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark A * C'
BenchmarkTools.Trial: 
  memory estimate:  156.67 KiB
  allocs estimate:  9
  --------------
  minimum time:     481.587 ms (0.00% GC)
  median time:      482.608 ms (0.00% GC)
  mean time:        483.716 ms (0.00% GC)
  maximum time:     489.008 ms (0.00% GC)
  --------------
  samples:          11
  evals/sample:     1


```
When `A` is multiplied by `C'`, a dense matrix multiplication is computed.
```julia
julia> @which A * C'
*(A::AbstractArray{T,2} where T, B::AbstractArray{T,2} where T) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:141

```
An easy but probably inefficient fix will be adding the following methods.
```julia
*(A::SparseMatrixCSC{TA,S}, x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}) where {TA,S,Tx} = A * copy(x)
*(A::Adjoint{<:Any,SparseMatrixCSC{TA,S}}, x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}) where {TA,S,Tx} = (x'A')'
*(x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}, A::SparseMatrixCSC{TA,S}) where {TA,S,Tx} = (A'x')'
*(x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}, A::Adjoint{<:Any,SparseMatrixCSC{TA,S}}) where {TA,S,Tx} = (A'x')'
```
These four methods utilize existing methods and implement `A * C'`, `A' * C'`, `B' * A` and `B' * A'` respectively. The same needs to be done to fix `Transpose`.

```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

```

### PR DESCRIPTION
**Pull request by dkarrasch**
This intends to close #32172.

Currently, we're missing a couple of multiplication methods for sparse with strided matrices, both ways.

### CODE REVIEW

**Comment by lanqingy** [comment]
Here are two issues I noticed. Both are related to left multiplying a sparse matrix by a dense matrix.

The first one is in these two functions.
https://github.com/dkarrasch/julia/blob/471e74f5697a666fc233b2a896aab6871c31c067/stdlib/SparseArrays/src/linalg.jl#L131-L144
The matrix `C` is not initialized. In other methods of `mul!`, this is done by setting `β` to be zero. Here, there used to be a line which called `zeros` but was removed in one of the commits.

The other issue is that we still need these two multiplications, where either the adjoint or transpose of the sparse matrix is multiplied on the left by a dense matrix.
```
function mul!(C::StridedVecOrMat, X::AdjOrTransStridedMatrix, A::Adjoint{<:Any, <:SparseMatrixCSC})
```
```
function mul!(C::StridedVecOrMat, X::AdjOrTransStridedMatrix, A::Transpose{<:Any, <:SparseMatrixCSC})
```

**Comment by dkarrasch** [comment]
@lanqingy, thank you very much. I got lost towards the end of the day, as I was only seeing multiplications. 😄 I was aware of the missing methods for `Adjoint/Transpose`, but didn't have the power to add them also. The other comment was also very helpful, I totally lost the whole alpha-beta-thing out of sight.

**Comment by dkarrasch** [comment]
CI failures appear to be unrelated, even though it looks horrible. When I find the time, I'll try to find out whether we need additional tests. We need to make sure that it's really these methods that handle sparse*strided and strided*sparse.

There is no new functionality here, so I assume there exist some tests that would at least partially cover these multiplications. Also, these multiplications used to work before, they just fell back on generic methods. Does that qualify for backports?

**Comment by dkarrasch** [comment]
AFAICT, there are tons of multiplication tests, including with strided matrices. Can we review (and merge) this and then check coverage if there are some tests missing?

**Comment by ViralBShah** [comment]
Pinging @andreasnoack for review.

**Comment by jebej** [comment]
Is coverage not working right now? (to check that tests do cover these changes)

**Comment by dkarrasch** [comment]
I don't know how to trigger coverage tests...

**Comment by ViralBShah** [comment]
I did a quick eyeballing of tests and seemed like they were covered. But perhaps work checking for sure.

**Pull request merged**
