### PR TITLE
WIP: dates-io coverage

### PR DESCRIPTION
**Pull request by Ismael-VC**
Test show representation of Date/DateTime.

Refs: 
- https://coveralls.io/builds/2869755/source?filename=base%2Fdates%2Fio.jl#L16
- https://coveralls.io/builds/2869755/source?filename=base%2Fdates%2Fio.jl#L24

[av skip]

### CODE REVIEW

**Comment by tkelman** [comment]
Nice, thanks for the PR - if you think this is ready to run against the CI, adding tests is not a good candidate for putting `[ci skip]` - we want to ensure the newly added tests pass on all platforms before we merge this.

**Comment by Ismael-VC** [comment]
@tkelman thanks I know, but I haven't finished yet, I'm looking at this line of code in the tests:

* https://coveralls.io/builds/2869755/source?filename=base%2Fdates%2Fio.jl#L186

This method is still left untested: 

* `format(y::AbstractArray{DateTime},df::DateFormat=ISODateTimeFormat)` 

A few lines above there is another similar method that is already covered according to CoverAlls, but I can't find the test that exercises it:

* `format(y::AbstractArray{Date},df::DateFormat=ISODateFormat)`

I want to copy cat this test in order to test the former method, but I think the latter is being called indirectly, do you have any idea of what is going on?

I don´t see any test that uses an `AbstractArray{Date}`. :confused:

I meant to activate the tests and change `WIP` for `RFC` after I figure this out.

**Comment by Ismael-VC** [comment]
Its just that i don't want to disrupt others workflow, and I've been screwing up a bit here and there, but I'm also learning fast how to avoid this.

**Comment by tkelman** [comment]
Cool, okay, that actually makes sense then. Just wanted to be sure.

Pinging @quinnj who should be able to answer your test coverage question on Dates.

**Comment by quinnj** [comment]
This is kind of dumb to do tests since it's not really testing anything (show is defined in terms of string). It's probably better to eliminate one or the other method; what's the latest protocol here for a type? If I define `string` or `show` do I automatically get the other?

**Comment by Ismael-VC** [comment]
@quinnj I'll change the tests, instead of testing for both `string` and `show`, I'll test just for `show` (which calls `string`), this way I think we can have everything covered without redundancy.

**Comment by quinnj** [comment]
Closed in lieu of #16915

**Pull request closed without merging**
