### PR TITLE
fix #29059, unnecessary warning in precompile for `eval` in `__init__`

### LINKED ISSUE #29059: eval in __init__ causes incorrect precompilation warning
Noticed in a couple of packages since precompile is on by default. Setup:
```julia
using Pkg
A = joinpath(pwd(), "PackageA");
B = joinpath(pwd(), "PackageB");
Pkg.generate.(["PackageA", "PackageB"]);
Pkg.activate(A);
Pkg.develop(PackageSpec(path = B));
Pkg.activate();
Pkg.develop([PackageSpec(path = A), PackageSpec(path = B)]);
write(joinpath(A, "src", "PackageA.jl"), "module PackageA\nusing PackageB\nend");
write(joinpath(B, "src", "PackageB.jl"), "module PackageB\n__init__() = eval(:(b() = 1))\nend");
```
and then
```julia
julia> using PackageA
[ Info: Precompiling PackageA [578a9956-b149-11e8-3635-0b7267ab0bb3]
WARNING: eval from module PackageB to PackageA:    
Expr(:call, :b) = Expr(:block, #= Symbol("/home/fredrik/PackageB/src/PackageB.jl"):2 =#, 1)
  ** incremental compilation may be broken for this module **
```

See e.g. https://github.com/JuliaDocs/Documenter.jl/issues/806

### PR DESCRIPTION
**Pull request by JeffBezanson**
Load-time `eval` into a different module is not allowed, since its results can't be tracked and saved. Init-time and run-time `eval` *are* allowed. `__init__` methods are the only code expected to run during precompilation that are not "load time" code. So technically, the eval warning could be disabled at init-time. We don't have a good way to do that though, so instead I chose to set current_module to `X` while running `X.__init__`. That at least allows `X` to eval into itself, which is the most sensible case.

Incidentally, I believe this warning is the only remaining use for the `current_module` stuff. I'll make a separate PR to remove unnecessary setting/resetting of it.

I also made a slight change to the logic controlling when to run `__init__` methods. Previously we did it (1) after loading a precompiled module, or (2) once we are back outside of any module. E.g. these modules:
```
module PackageA
using PackageB
println(PackageB.inited)
end

module PackageB
inited = false
__init__() = (global inited = true)
end
```
used to print `true` in precompiled mode, but `false` in `--compiled-modules=no` mode. The change makes it always print `true`, by considering any full package to be sufficiently "top level".

fixes #29059

### CODE REVIEW

**Review by vtjnash — CHANGES_REQUESTED** [review]
No, this will allow code to run that is exactly the bad pattern it's designed to detect.

The `current_module` handling everywhere is supposed to go away with eventual deprecation cleanup (to be replaced with a scan through `jl_module_init_order` to implement this warning, and I think it will also drop some of the other try/catch functions that wrap `eval`)

**Comment by JeffBezanson** [comment]
> this will allow code to run that is exactly the bad pattern it's designed to detect

Example?

> to be replaced with a scan through jl_module_init_order

Is the idea to disallow eval into a module after it has had `__init__` called?

**Comment by vtjnash** [comment]
The idea is to detect calls to `eval` for which we won't be able to handle the result. The `jl_module_init_order` does essentially contain that information (of which modules have had `__init__` called), but I think that's more driven by common intent than definition.

**Comment by JeffBezanson** [comment]
> The idea is to detect calls to eval for which we won't be able to handle the result.

Certainly, but we need a more practical definition than that --- for example there's nothing wrong with `eval(mod, 2)` but it's too complicated to try to specify why that's ok but other evals aren't.

Just to make sure we're on the same page, is the code in the original issue intended to be valid?

**Comment by vtjnash** [comment]
No, that’s specifically the example this is here to catch

Yes, there’s nothing wrong with that. We just make the observation that you don’t need eval for doing permitted actions, so while we could attempt to write a classifier (like we have for pure), it’s unnecessary.

**Comment by JeffBezanson** [comment]
Superseded by #29483

**Pull request closed without merging**
