### PR TITLE
Rename ENV variable `JULIA_USE_NEW_PARSER` -> `JULIA_USE_FLISP_PARSER`

### LINKED ISSUE #50470: Rename the ENV variable `JULIA_USE_NEW_PARSER` to something more verbose and less time-sensitive
I find the `JULIA_USE_NEW_PARSER` environment variable name ambiguous.

https://github.com/JuliaLang/julia/blob/d60f9b3b47ee585cc1d8a836bb0d7acab81a9b6e/base/Base.jl#L607

What is new now it won't be new in a few months... So the variable name is doomed to become obsolete.

Why not something like `JULIA_USE_PRE_v1p10_PARSER` or something along those lines: more verbose, and less time-sensitive.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #50470

### CODE REVIEW

**Comment by carstenbauer** [comment]
LGTM.

**Comment by matthias314** [comment]
Should this have a "backport 1.10" label? The PR puts this change under the v1.10 section of HISTORY.md, but it has not been applied to the release-1.10 or backports-release-1.10 branch.

**Comment by oscardssmith** [comment]
good point.

**Comment by matthias314** [comment]
And should this new environment variable be mentioned in doc/src/manual/environment-variables.md ? There is nothing so far. not even under the previous name.

**Comment by KristofferC** [comment]
Was pushed to `release-1.10` in https://github.com/JuliaLang/julia/pull/50849 so removing label.

**Pull request merged**
