### PR TITLE
fix output of getaddrinfo in networking and streams

### PR DESCRIPTION
**Pull request by musm**
fix output of getaddrinfo in networking and streams documentation for v0.5.

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @musm! Thanks for this - I see this is just an example, and *not* a doctest. Do you think you could convert it to a doctest (is this a reasonable thing to do, @tkelman?) so that if the output syntax changes in the future, it'll be easier to catch?

**Comment by tkelman** [comment]
The output looks like it might depend on your location. I get
```
julia> getaddrinfo("google.com")
ip"216.58.192.14"
```

**Comment by musm** [comment]
That's expected it depends on the dns server it pings. The syntax more importantly was wrong.

@kshyatt  How do I convert to a doctest?

**Comment by kshyatt** [comment]
Hmm, if the output is going to change depending on where the docs are built it's probably not worth the effort. Nevermind! For next time, check out http://docs.julialang.org/en/latest/manual/documentation/

**Pull request merged**
