### PR TITLE
[Pkg]: Bump Pkg to fix JLLs on MacOS

### PR DESCRIPTION
**Pull request by staticfloat**
We had made a slight change to BinaryPlatform triplets that caused old
JLLs to break.  This change to Pkg maintains backwards compatibility
when using `Pkg.BinaryPlatforms`, while `Base.BinaryPlatforms` is free
to continue improving things for the future.

### CODE REVIEW

**Comment by fredrikekre** [comment]
image

**Comment by staticfloat** [comment]
X-ref: https://github.com/JuliaLang/Pkg.jl/pull/2046

**Comment by ianshmean** [comment]
Eh? `Pkg` _is_ imported into `utils.jl`..
```
  UndefVarError: Pkg not defined
  Stacktrace:
    [1] temp_pkg_dir(fn::Main.Test43Main_Pkg_resolve.ResolveTest.var"#1#3"; rm::Bool)
      @ Main.Test43Main_Pkg_resolve.ResolveTest.Utils /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.6/Pkg/test/utils.jl:81
```

**Comment by KristofferC** [comment]
I thought the error was that it was trying to load Pkg the package but this looks like some kind of scope error.. Probably good to try figure it out properly.

**Comment by staticfloat** [comment]
When I run `make test-Pkg`, I get:

```
$ make JULIA_PRECOMPILE=0 test-Pkg
    JULIA test/Pkg                                                
Test    (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)                                             
Pkg/resolve  (1) |        started at 2020-09-28T06:19:52.047
WARNING: could not import Test81Main_Pkg_resolve.Pkg into ResolveTest                              
WARNING: could not import ResolveTest.Pkg into ResolveUtils
```

So I think the `Test81Main_Pkg_resolve` module must be screwing something up.

**Comment by KristofferC** [comment]
Ah, I think https://github.com/JuliaLang/Pkg.jl/blob/b8ea6e546ef5e9414f0197ef8af56f8a698f7ed8/test/resolve.jl#L4 assumes that we are not running the file directly but that it is included in `runtests.jl` and that we grab the `Pkg` defined at https://github.com/JuliaLang/Pkg.jl/blob/b8ea6e546ef5e9414f0197ef8af56f8a698f7ed8/test/runtests.jl#L5.

**Comment by KristofferC** [comment]
I pushed an update to Pkg that should have fixed the test error.

**Pull request merged**
