### PR TITLE
add_license_to_files_jl

### PR DESCRIPTION
**Pull request by peter1000**
https://github.com/JuliaLang/julia/pull/11073#issuecomment-98090053

https://github.com/JuliaLang/julia/issues/11023

### CODE REVIEW

**Comment by tkelman** [comment]
Would be easier to keep track of this if you would force push to the same branch so we can keep the discussion for the same change within the same PR...

Anyway I missed `../src/ccall.cpp` the first time through, that should not be an exception, it should have the normal header. The `abi_*` files get included into it, that's all the comment there is describing.

**Comment by tkelman** [comment]
`../src/support/utf8.c` should also be added to skipfiles

**Comment by peter1000** [comment]
> I actually meant I'd like to see them as separate commits within the same PR

Seems I misunderstood you: anyway I updated this PR with your suggestions

* `../src/support/utf8.c` should also be added to skipfiles
* Anyway I missed `../src/ccall.cpp` the first time through, that should not be an exception, it should have the normal header.

**Comment by tkelman** [comment]
Seems people are okay with doing things this way. It only adds headers to Julia, C, C++, and bash files, but that's a pretty good start. I'll probably merge this and #11023 then do a little manual fixup (add ui/repl.c, and tweak base/special/trig.jl and base/linalg/givens.jl a little bit) unless someone speaks up and says not to.

**Comment by peter1000** [comment]
> that's a pretty good start

I think so nearly 500 files licensed to julia ;)

**Comment by tkelman** [comment]
Oh, and of course, thanks @peter1000 for your contribution!

**Comment by peter1000** [comment]
was a good experience - thanks for all your help and input.

**Pull request merged**
