### PR TITLE
For %d printf specifier and AbstractFloat, print as %0f

### PR DESCRIPTION
**Pull request by quinnj**
Alternative fix to #37554. As Jameson noted on that PR, the type
instability made the code pretty ugly and slow. An alternative solution
is to switch the `%d` format specifier to `%0f`, i.e. a fixed precision
of 0 for `AbstractFloat` arguments. The code here is indeed much cleaner
and more performant: several times faster than old Printf.

### CODE REVIEW

**Comment by quinnj** [comment]
FreeBSD failure looks unrelated

**Comment by StefanKarpinski** [comment]
FWIW, the concept in the original code was that the format specifier only act as directions for how to format the value and have no effect on how to interpret it as a type since, unlike C, we already know that. Thus, writing `%d` means "print this number with no trailing digits" i.e. what `%0f` does. So 👍.

**Comment by quinnj** [comment]
Yeah, once I went back to the old Printf code and realized they were just doing `%0f`, I realized that was a way simpler solution than trying to do the covert/coerce dance to integer.

**Comment by StefanKarpinski** [comment]
It's also why I ultimately think that printf is a bad UI for a dynamic language: it's designed for C where the specifier has to encode both what the type of the argument is _and_ how to format it. In Julia, we only need to express the formatting part, which can be done more easily than what printf requires.

**Comment by StefanKarpinski** [comment]
In 2.0 I'd very much like to kick Printf out of stdlibs and replace it with something better and simpler.

**Pull request merged**
