### PR TITLE
WIP: cat for vectors, vcat for matrices & arrays

### PR DESCRIPTION
**Pull request by felixrehren**
[*this is a very unfinished pull request*. I considered making an issue based on [the discourse thread about semicolons](https://discourse.julialang.org/t/whats-the-meaning-of-the-array-syntax/938), wanted to contribute, started making changes, realised how many ramifications this change has, realised that I can't build julia on my machine, and almost scrapped it. It's now a PR 1) to raise the issue, 2) in case someone else wants to improve on this, 3) to sit here until I can finish it.]

Suggestion part-implemented but not tested here:
* add methods to `cat` to concatenate vectors
* change `vcat` to always return an array of dim at least 2 (in particular, `vcat` of vectors is a `1xn` matrix)

Implications:
* the semicolon operator `;` now always returns a matrix, for consistency
* it's easier to instantiate `1xn` matrices
* lots of instances of using `vcat` to concatenate vectors into another vector should be changed to `cat`

Motivation:
* [commas do vectors, semicolons and spaces concatenate and produce matrices](https://discourse.julialang.org/t/whats-the-meaning-of-the-array-syntax/938) or higher-dimensionals
* consistency in separating vectors and matrices

I would really welcome any comments, advice, or anyone taking this further. (One thing I would definitely change in future is try to modify several files in a single commit...) If someone has a beginner's guide to contributing to core, that would be great. Hope this PR is ok

### CODE REVIEW

**Comment by tkelman** [comment]
Welcome!

> If someone has a beginner's guide to contributing to core, that would be great.

I'd recommend checking out http://kshyatt.github.io/2016/01/28/firstpr.html and CONTRIBUTING.md.

Looks like there's already a conflict in the tests here. There's a new "resolve conflicts" github feature that may help for that, does the submitter of a PR see that button?

**Comment by pabloferz** [comment]
I'd say it would be better to open an issue for this and once there is a consensus reached of the expected behavior, then open a PR.

**Comment by felixrehren** [comment]
Perfect, thanks. @kshyatt's guide looks really helpful, but the page ends abruptly with a "Welp. Something went wrong here!" for me :/

The resolve conflicts button is available, but it never actually computes = there is no output to see.

I'll open an issue.

**Comment by brenhinkeller** [comment]
It looks like this can be closed for now in favor of the aforementioned issue (esp. given the current no-breaking-changes-until-maybe-2.0-someday state of Julia), but anyone who wants to pick up the torch should feel free to reopen if they find it would be useful to do so.

**Pull request closed without merging**
