### PR TITLE
feature freeze master for 0.6-pre

### PR DESCRIPTION
**Pull request by tkelman**
change VERSION from 0.6-dev to 0.6-pre.alpha (VERSION needs to stay monotonically increasing over time)

whoever clicks merge on this, please do squash merge and I'll tag the result

### CODE REVIEW

**Comment by H-225** [comment]
Please check on #20596 before merging this. >)

**Comment by tkelman** [comment]
that seems like a primarily interactive output change and unlikely to change the behavior of any code?

**Comment by H-225** [comment]
I wasn't aware such things were not counted. My mistake. :-)

**Comment by StefanKarpinski** [comment]
Anything that won't break people's code is ok to change. That includes interactive output and fixing bugs.

**Comment by H-225** [comment]
Makes sense.

**Comment by tkelman** [comment]
note that https://github.com/JuliaLang/julia/pull/20783 is a bit breaking, any packages extending pow may notice that

**Comment by StefanKarpinski** [comment]
Yes, but no one is using it yet and that's effectively a bug fix, albeit a fix to buggy performance.

**Comment by tkelman** [comment]
it's definitely being used https://github.com/ajkeller34/Unitful.jl/commit/0762a70a03250f518156335dc2389557fe1ee263

**Comment by ajkeller34** [comment]
For what it's worth, I can adjust to changes if #20783 is merged, plus I need to add some methods I forgot anyhow.

**Comment by KristofferC** [comment]
image

**Pull request merged**
