### PR TITLE
Clarify documentation of anonymous functions

### PR DESCRIPTION
**Pull request by sijow**
The example used previously is a bit confusing: the do-block syntax is introduced only later on the page, and the anonymous function simply calls `time` so it's actually useless (`time` could be passed to `get` as-is).

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
The `time` function gives a different value depending on when it is called, so it was a reasonable choice here. Using `rand` might be clearer, however. There's no need for a matrix, you could just use `rand()` to get a single random value. I also think that using `get!` might be better than `get` since it stores the value for later. While you're clarifying, it might be worth comparing the behavior of `get!(dict, key, rand())` with the behavior of `get!(()->rand(), dict, key)`.

**Comment by knuesel** [comment]
Good point on `get!`. I would rather keep `rand(3,3)` (or something else than a bare `rand()` because this is in the anonymous function section. That's also why I didn't like `time`: the example doesn't make much sense when you could just write `get(time, dict, key)` with no anonymous function at all.

**Comment by StefanKarpinski** [comment]
Ah, I see what you were saying about time—the issue is that it is itself a zero-argument function. Didn't get that before. How about `rand(0:9)` instead, to generate a random digit each time? That needs arguments and only generates a single value.

**Comment by knuesel** [comment]
I'll have to think a bit more about a good example to compare `get!(f, dict, key)` vs `get!(dict, key, f())`. In simple one-liners they do the same, for example `get!(dict, key, rand(0:9))` does produce a different result each time it's run. I guess the functional form is typically needed when the whole thing is itself in a function and the initializer is received as parameter. But showing two versions of  such an outer function seems like a big addition to the doc for a small point. I'll  try to find a more concise way to make the point.

**Comment by knuesel** [comment]
I pushed a new version that removes all references to `get` or `get!`: I think it only distracts from the real point here...

(It took me some time to realize that `get!(f, dict, key)` and `get!(dict, key, default_value)` are completely interchangeable: the former can always be replaced with `get!(dict, key, f())`, so the purpose of `get!(f, dict, key)` is just to enable the `do` block syntax, as the documentation says. And `do` blocks are documented much later on this page.)

**Comment by knuesel** [comment]
@vtjnash ah right, and it can also make a difference when it's expensive to create the default value, as `get!(f, dict, key` will do it only if necessary.

It still seems fine to me to leave this out of the doc on anonymous functions but I'm happy to put back something about `get!` if you want.

**Pull request merged**
