### PR TITLE
Update noteworthy-differences.rst

### PR DESCRIPTION
**Pull request by EricForgy**
I read on the users group
- https://groups.google.com/d/msg/julia-users/hmoUivSoYdE/r7ytyqa-AgAJ

that Julia uses geometric expansion, which happened to be relevant to some code I'm working on (first Julia project yay!). Coincidentally, I had just read this note about differences with Matlab and thought a link would be helpful/interesting.

Thanks.

### CODE REVIEW

**Comment by malmaud** [comment]
Do you have a reference for what exactly Matlab's strategy is? Does it just always allocate exactly as much as necessary for storing the requests number of items?

**Comment by EricForgy** [comment]
I don't know, but I found this in the Matlab docs:

* [Preallocating arrays](http://www.mathworks.com/help/matlab/math/resizing-and-reshaping-matrices.html#f1-88760)

which doesn't say a whole lot accept that performance will be bad if you append elements in a loop and suggests to pre-allocate.

I just found this same question on StackOverflow:

* [http://stackoverflow.com/questions/32766449/how-does-matlab-handle-dynamic-array-allocation](http://stackoverflow.com/questions/32766449/how-does-matlab-handle-dynamic-array-allocation)

Again, not too helpful but hints that they may be working to improve this.

As a quick test:

## Matlab

    >> tic; t = []; n = 10^8; for i = 1:n t(end+1) = i; end; toc
    Elapsed time is 21.384642 seconds.

## Julia

    julia> function test()
       t = Int64[]
       for i = 1:10^8
       append!(t,Int64[i])
       end
       end
    test (generic function with 1 method)

    julia> test()

    julia> @time test()
    5.306053 seconds (200.00 M allocations: 8.949 GB, 5.06% gc time)

I'm just learning Julia so that may be a horrible comparison, but gives some idea I hope.

**Comment by MichaelHatherly** [comment]
@EricForgy, would using `push!` in that example be a more accurate comparison?

```julia
julia> function test()
           t = Int[]
           for i = 1:10^8
               push!(t, i)
           end
           t
       end
test (generic function with 1 method)

julia> @time test();
  0.906074 seconds (2.04 k allocations: 800.195 MB, 14.31% gc time)

julia> @time test();
  0.966186 seconds (46 allocations: 800.094 MB, 4.51% gc time)
```

(Either way it's doing better than Matlab.)

**Comment by EricForgy** [comment]
That's awesome. Thanks Michael. push! will also speed up my code :)

**Comment by Keno** [comment]
I considered rebasing this, but then I came to the conclusion that I don't like this particular point here. What strategy arrays use for growing is somewhat irrelevant (and we're not particularly committed to anyway - other than that it should be fast). E.g. in the future the compiler might automatically pre-determine the number of `push!` in a loop and automatically pre-allocate the array. This kind of detail can go into the documentation for `push!` or the devdocs somewhere, but it seems to detailed to go here.

**Pull request closed without merging**
