### PR TITLE
[release-0.4] pending backports for final RC

### PR DESCRIPTION
**Pull request by tkelman**
hopefully final, anyway

### CODE REVIEW

**Comment by tkelman** [comment]
```diff
--- 035d559015/summary  2015-09-27 23:00:04.286518673 -0400
+++ fef1fb825c/summary  2015-09-30 10:05:56.065284571 -0400
@@ -6,6 +6,8 @@
 "tests_fail"
 nightly/AmplNLWriter.json
 "tests_fail"
+nightly/AndorSIF.json
+"tests_fail"
 nightly/AnsiColor.json
 "tests_pass"
 nightly/AppConf.json
@@ -73,7 +75,7 @@
 nightly/Blink.json
 "tests_pass"
 nightly/Blocks.json
-"tests_pass"
+"tests_fail"
 nightly/BloomFilters.json
 "tests_fail"
 nightly/Blosc.json
@@ -228,6 +230,8 @@
 "not_possible"
 nightly/CUFFT.json
 "not_possible"
+nightly/CURAND.json
+"tests_fail"
 nightly/Curl.json
 "no_tests"
 nightly/CurveFit.json
@@ -363,7 +367,7 @@
 nightly/Faker.json
 "tests_pass"
 nightly/FastaIO.json
-"tests_fail"
+"tests_pass"
 nightly/FastAnonymous.json
 "tests_pass"
 nightly/FastArrayOps.json
@@ -372,6 +376,8 @@
 "tests_pass"
 nightly/FileFind.json
 "no_tests"
+nightly/FileIO.json
+"tests_pass"
 nightly/FinancialMarkets.json
 "tests_fail"
 nightly/FiniteStateMachine.json
@@ -409,7 +415,7 @@
 nightly/FunctionalUtils.json
 "no_tests"
 nightly/Gadfly.json
-"tests_pass"
+"tests_fail"
 nightly/GARCH.json
 "tests_fail"
 nightly/Gaston.json
@@ -550,11 +556,15 @@
 "not_possible"
 nightly/IJuliaPortrayals.json
 "tests_pass"
+nightly/ImageMagick.json
+"tests_pass"
 nightly/ImageQuilting.json
 "tests_pass"
 nightly/Images.json
 "tests_pass"
 nightly/ImageView.json
+"tests_pass"
+nightly/ImagineFormat.json
 "tests_fail"
 nightly/Immerse.json
 "tests_fail"
@@ -821,7 +831,7 @@
 nightly/MFCC.json
 "tests_pass"
 nightly/MIDI.json
-"tests_fail"
+"tests_pass"
 nightly/Millboard.json
 "tests_pass"
 nightly/MinimalPerfectHashes.json
@@ -875,7 +885,7 @@
 nightly/MutableStrings.json
 "no_tests"
 nightly/Mux.json
-"tests_pass"
+"tests_fail"
 nightly/NaiveBayes.json
 "tests_pass"
 nightly/NamedArrays.json
@@ -894,6 +904,8 @@
 "not_possible"
 nightly/NetCDF.json
 "tests_fail"
+nightly/Netpbm.json
+"tests_pass"
 nightly/Nettle.json
 "tests_pass"
 nightly/NeuralynxNCS.json
@@ -911,13 +923,15 @@
 nightly/NLreg.json
 "tests_fail"
 nightly/NLsolve.json
-"tests_pass"
+"tests_fail"
 nightly/NMEA.json
 "tests_pass"
 nightly/NMF.json
 "no_tests"
 nightly/NPZ.json
 "no_tests"
+nightly/NRRD.json
+"tests_fail"
 nightly/NullableArrays.json
 "tests_pass"
 nightly/NumericExtensions.json
@@ -1056,6 +1070,8 @@
 "tests_pass"
 nightly/QuantEcon.json
 "tests_fail"
+nightly/QuartzImageIO.json
+"tests_fail"
 nightly/Quaternions.json
 "tests_pass"
 nightly/QuickCheck.json
@@ -1148,8 +1164,6 @@
 "tests_fail"
 nightly/SemidefiniteProgramming.json
 "not_possible"
-nightly/SerialLib.json
-"no_tests"
 nightly/SerialPorts.json
 "tests_pass"
 nightly/SFML.json
@@ -1223,7 +1237,7 @@
 nightly/SpecialMatrices.json
 "tests_pass"
 nightly/SPTK.json
-"tests_fail"
+"tests_pass"
 nightly/SQLite.json
 "tests_fail"
 nightly/StackedNets.json
@@ -1317,7 +1331,7 @@
 nightly/TimeZones.json
 "tests_pass"
 nightly/Tk.json
-"tests_fail"
+"tests_pass"
 nightly/TOML.json
 "tests_pass"
 nightly/TopicModels.json
@@ -1385,11 +1399,11 @@
 nightly/Weave.json
 "tests_fail"
 nightly/WebSockets.json
-"tests_pass"
+"tests_fail"
 nightly/WinRPM.json
 "no_tests"
 nightly/Winston.json
-"tests_fail"
+"tests_pass"
 nightly/WoodburyMatrices.json
 "tests_pass"
 nightly/WordNet.json
@@ -1419,7 +1433,7 @@
 nightly/ZChop.json
 "tests_pass"
 nightly/ZipFile.json
-"tests_pass"
+"tests_fail"
 nightly/Zlib.json
 "tests_pass"
 nightly/ZMQ.json
```

https://gist.github.com/aae9eec4cd222657f717

Gadfly is a timeout and NLsolve's tests fail half the time, Blocks looks like a real issue though: ```MethodError: `eof` has no method matching eof(::Base.FS.File)```

Mux and WebSockets failed due to `UndefVarError: UVServer not defined` in HttpServer. HttpServer itself was failing before, but due to an MbedTLS certificate problem.

ZipFile was: ```ERROR: LoadError: test error in expression: ascii(read(dir.files[1],@compat(UInt8),length(s1))) == s1
MethodError: `convert` has no method matching convert(::Type{ASCIIString}, ::Void)```

So fixing #12975 with the IO refactoring from #12839 would come at the cost of breaking several packages.

**Comment by malmaud** [comment]
All Mux and WebSockets need to do is replace `UVServer` with `TCPServer`

**Comment by tkelman** [comment]
They're failing indirectly due to HttpServer which you fixed a few days ago but needs to be tagged.

That leaves Blocks and ZipFile. Help appreciated in debugging those.

**Comment by tanmaykm** [comment]
@tkelman https://github.com/JuliaParallel/Blocks.jl/pull/17 should fix Blocks

**Comment by JeffBezanson** [comment]
d09545be63296a96b0b7507366dfb646b8b6066c should also be backported.

**Comment by tkelman** [comment]
Still getting the buildbots back up after a failure. In the meantime, @fhs is not responding very actively about ZipFile, but that package is used by 4 or 5 others. Would be a little unfortunate to break the package right before a release. Though it's also broken on nightlies for similar reasons, if anyone wants to help look into it.

**Comment by tkelman** [comment]
We're in pretty good shape. https://gist.github.com/anonymous/2d48b86e683caaf5bb0b

GeoIP passes locally so I think it was a corrupted zip download. NLsolve is same convergence thing. TimeSeries is a new failure but I think it's a package precompilation issue since there were a bunch of tags of related packages recently, and the same problem happens using rc3. cc @milktrader on that

Merging, will tag rc4 today if nothing urgent comes up.

**Comment by milktrader** [comment]
Is there a test log that I can inspect with TimeSeries? Tests are passing locally, but on rc1. There are some deprecation warnings [here in the latest Travis test](https://travis-ci.org/JuliaStats/TimeSeries.jl/builds/83308468)

**Comment by tkelman** [comment]
check TimeSeries.json in the gist I linked to above. Messy to read raw, I recommend using JSON.jl to pretty print it.

**Pull request merged**
