### PR TITLE
Update libosxunwind to v0.0.5

### PR DESCRIPTION
**Pull request by ararslan**
Works for me on High Sierra. Stefan, could you try out this branch on Mojave?

### CODE REVIEW

**Comment by staticfloat** [comment]
I had to flip a conditional, but I think this is good to go now.  This compiled on my 10.14 machine as well as my 10.11 machine, so I think we're good to go.

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
> I had to flip a conditional

What do you mean? Did you amend the actual v0.0.5 release of libosxunwind?

**Comment by staticfloat** [comment]
Yes: https://github.com/JuliaLang/libosxunwind/commit/4dcf6377b90c61bb8aa8070ebf39c8bf4dde2ea1

**Comment by StefanKarpinski** [comment]
Does the request for review mean that I should try building this commit to make sure it works?

**Comment by ararslan** [comment]
Yes please

**Comment by ararslan** [comment]
Though Elliot said he did a 10.14 build and it worked, so you don't have to

**Comment by StefanKarpinski** [comment]
Happy to give it a try to make sure I don't end up not being able to build master again :)

**Comment by StefanKarpinski** [comment]
Build just fine for me too.

**Comment by ararslan** [comment]
Perfect, thanks!

**Pull request merged**
