### PR TITLE
Make llvmunwind depend on llvm

### LINKED ISSUE #45379: Source build: llvmunwind should be compiled after llvm
This was first reported in a comment in this PR: https://github.com/JuliaLang/julia/pull/45189#issuecomment-1117868670
I'm creating its own issue, now that the PR is merged.

I'm building from master source on macOS (`make USE_BINARYBUILDER=0 VERBOSE=1 CFLAGS='-Wno-implicit-function-declaration'`; CFLAGS is there to avoid this other bug: https://github.com/JuliaLang/julia/issues/45200)

I get:

```
mkdir -p scratch/llvmunwind-12.0.1/
cd scratch/llvmunwind-12.0.1/ && \
	cmake /private/tmp/julia/deps/srccache/llvmunwind-12.0.1/ -DCMAKE_INSTALL_PREFIX:PATH=/private/tmp/julia/usr -DCMAKE_PREFIX_PATH=/private/tmp/julia/usr -DCMAKE_INSTALL_LIBDIR=/private/tmp/julia/usr/lib -DCMAKE_INSTALL_BINDIR=/private/tmp/julia/usr/bin -DLIB_INSTALL_DIR=/private/tmp/julia/usr/lib -DCMAKE_MACOSX_RPATH=1 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER="$(which clang)" -DCMAKE_C_COMPILER_ARG1="-mmacosx-version-min=11.0" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_COMPILER_ARG1="-mmacosx-version-min=11.0" -DCMAKE_LINKER="$(which ld)" -DCMAKE_AR="$(which ar)" -DCMAKE_RANLIB="$(which ranlib)" -DCMAKE_BUILD_TYPE=MinSizeRel -DLIBUNWIND_ENABLE_PEDANTIC=OFF -DLLVM_CONFIG_PATH=/private/tmp/julia/usr/tools/llvm-config
Re-run cmake no build system arguments
-- Found LLVM_CONFIG_PATH as /private/tmp/julia/usr/tools/llvm-config
-- /private/tmp/julia/usr/tools/llvm-config --includedir --prefix --src-root
CMake Error at CMakeLists.txt:39 (message):
  llvm-config failed with status No such file or directory


-- Configuring incomplete, errors occurred!
See also "/tmp/julia/deps/scratch/llvmunwind-12.0.1/CMakeFiles/CMakeOutput.log".
See also "/tmp/julia/deps/scratch/llvmunwind-12.0.1/CMakeFiles/CMakeError.log".
make[1]: *** [scratch/llvmunwind-12.0.1/build-configured] Error 1
```

because it's trying to build llvmunwind before it's built llvm, and therefore `llvm-config` cannot be found. There needs to be something in the makefiles that enforces that, and there isn't.

### PR DESCRIPTION
**Pull request by fxcoudert**
Fixes https://github.com/JuliaLang/julia/issues/45379

### CODE REVIEW

**Review by giordano — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Comment by vchuravy** [comment]
Our LLVMunwind is trailing our LLVM version so this now tightly couples them. We should upgrade LLVMUnwind to match the LLVM version first.

**Comment by giordano** [comment]
> Our LLVMunwind is trailing our LLVM version so this now tightly couples them. We should upgrade LLVMUnwind to match the LLVM version first.

Isn't that orthogonal to this PR?  This is about the order with which we have to build the various dependencies.

**Comment by fxcoudert** [comment]
This enforces the right build order, in the case where both are built from source. It just fixes the build, but does not change the versions used or couple them any more than they already are.

**Comment by vchuravy** [comment]
What I am saying is that linking LLVMUnwind12 against LLVM13 may not work. 

We use a standalone built of LLVMUnwind https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LLVMLibUnwind/common.jl

**Comment by vchuravy** [comment]
Ah I see it just adds an ordering? But why is that necessary? These two libraries should be independent of each other

**Comment by fxcoudert** [comment]
They're not, because later:

```
LLVMUNWIND_OPTS := $(CMAKE_COMMON) -DCMAKE_BUILD_TYPE=MinSizeRel -DLIBUNWIND_ENABLE_PEDANTIC=OFF -DLLVM_CONFIG_PATH=$(build_depsbindir)/llvm-config
```

**Comment by vchuravy** [comment]
Can you build without setting the llvm-config path?

**Comment by fxcoudert** [comment]
If I remove `LLVM_CONFIG_PATH` entirely, it gives this warning:

```
CMake Warning at CMakeLists.txt:65 (message):
  UNSUPPORTED LIBUNWIND CONFIGURATION DETECTED: llvm-config not found and
  LLVM_MAIN_SRC_DIR not defined.  Reconfigure with
  -DLLVM_CONFIG=path/to/llvm-config or -DLLVM_PATH=path/to/llvm-source-root.


CMake Warning at CMakeLists.txt:76 (message):
  Not found:
```

but otherwise appears to build without trouble.

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by fxcoudert** [comment]
One test failure in `tester_linuxaarch64`. 

```
Error in testset InteractiveUtils:
Error During Test at none:1
  Got exception outside of a @test
  ProcessExitedException(6)
  Stacktrace:
    [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
      @ Base ./task.jl:881
    [2] wait()
      @ Base ./task.jl:945
    [3] wait(c::Base.GenericCondition{ReentrantLock})
      @ Base ./condition.jl:124
    [4] take_buffered(c::Channel{Any})
      @ Base ./channels.jl:416
    [5] take!(c::Channel{Any})
      @ Base ./channels.jl:410
    [6] take!(::Distributed.RemoteValue)
      @ Distributed /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:726
    [7] remotecall_fetch(::Function, ::Distributed.Worker, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, UInt128, Tuple{Symbol}, NamedTuple{(:seed,), Tuple{UInt128}}})
      @ Distributed /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:461
    [8] remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, UInt128, Tuple{Symbol}, NamedTuple{(:seed,), Tuple{UInt128}}})
      @ Distributed /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:492
    [9] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/test/runtests.jl:260 [inlined]
   [10] (::var"#45#57"{Vector{Task}, var"#print_testworker_errored#53"{ReentrantLock, Int64, Int64}, var"#print_testworker_stats#51"{ReentrantLock, Int64, Int64, Int64, Int64, Int64, Int64}, Vector{Any}, Dict{String, DateTime}})()
      @ Main ./task.jl:494
```

**Comment by fxcoudert** [comment]
The same error is showing in an unrelated PR on freebsd64: https://github.com/JuliaLang/julia/pull/45435
I think it's fluke, and the PR is ready to be merged.

**Comment by ViralBShah** [comment]
@vchuravy merge?

**Comment by fxcoudert** [comment]
This is needed for source builds to work on macOS. Could it be merged, and possibly backported to 1.8 before release?

**Comment by ViralBShah** [comment]
I'm merging this since it should really not be an issue.

**Comment by vchuravy** [comment]
As I said before I think this is wrong. Our builds of LLVMUnwind and LLVM proper are NOT linked. So the use of `llvm-config` is definitely wrong. 

I don't know what the right solution is. My preferred solution is to build LLVMUnwind as part of LLVM so that these issues do not arise. But as the situation is this is a "pseudo"-fix. I do not have a Mac. @vtjnash this seems more in your wheel house.

**Comment by ViralBShah** [comment]
If it is ok, this helps us get past the current build failure on macs from source? In the meanwhile, can we separately open an issue to build LLVMUnwind the right way?

**Comment by DilumAluthge** [comment]
Pinging @ararslan and @omus, since they've done the most work on LLVMUnwind in Yggdrasil.

**Comment by ViralBShah** [comment]
Just a note that @vtjnash approved this PR.

**Pull request merged**
