### PR TITLE
Rename rank one up- and downdate functions for Cholesky to rank(up/down)date

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by jiahao** [comment]
I don't really like having the `rank` prefix because it is a property of the quantity you do the up/down-date with and is not essential to the idea of a up/down-date. In principle there is nothing stopping you from computing a up/down-date with a low rank matrix.

**Comment by timholy** [comment]
`updateAAt!`?

**Comment by andreasnoack** [comment]
@jiahao I think it's pretty standard terminology for this operation, e.g. http://www.netlib.org/lapack/explore-html/d7/d15/group__double__blas__level2.html#ga35ca25bb135cd7bfdd5d6190b1aa4d07.

@timholy I don't like the name. I consider myself in a process of removing the `A`s (and `B`s) from Julia.

**Comment by jiahao** [comment]
@andreasnoack I don't see how the LAPACK page you linked to substantiates this operation being called a "rank update". If anything, the documentation clearly describes a "rank 1" operation (the 1 is missing from the function name) and the notion of update is not described in the main documentation (only in the description of the arguments).

Again, my point is that the phrase "rank update" is meaningless. "rank 1" is the modifier to "update"; "rank" itself cannot meaningfully describe any kind of update. That's why functions like "syrk" have the k - they are to describe operations dealing with  "symmetric rank-k" (the k cannot be omitted and still be a meaningful English phrase.

How about `cholupdate!` and `choldowndate!`? I don't like them as much as `down/update!(::Cholesky)`, but I think we have to give the genericity issue a concession (at least, until `Base.update!` exists).

**Comment by jiahao** [comment]
I would even consider `ranknupdate!` less ugly than `rankupdate!`.

**Comment by andreasnoack** [comment]
The `k` versus `1` is in the signature here.

**Comment by jiahao** [comment]
But that's exactly my point regarding the name `rankupdate`, vs `ranknupdate` or `rank1update`.

**Comment by andreasnoack** [comment]
After offline discussions, we have settled (locally) for `lowrank(up/down)date`. It's a bit long, but I prefer a slightly long name to a cryptic name with abbreviations.

**Pull request merged**
