### PR TITLE
Delete BBEditTextWrangler-julia.plist

### PR DESCRIPTION
**Pull request by tkelman**
ref https://groups.google.com/forum/#!topic/julia-users/sQ5Atvjicxw and discussion in #16613 

We can move it to its own repo if people are still using it. For now it seems like no one is?

### CODE REVIEW

**Comment by ViralBShah** [comment]
Why not move all the editor modes to an EditorModes repo even otherwise?

**Comment by tkelman** [comment]
If nobody's using it and nobody wants to maintain it, doesn't seem worth the trouble.

**Comment by femtotrader** [comment]
I'm also in favor of creating a new repository and put this file into.
Maybe you prefer to have a separate organization for this.

**Comment by femtotrader** [comment]
Thanks @tkelman for creating JuliaEditorSupport organization https://github.com/JuliaEditorSupport/
Should we have a repository per editor or just one repository ?

**Comment by tkelman** [comment]
I guess one repository for "miscellaneous editors" if they would otherwise just be one or two files each, organized within folders inside that repo? Vim and Emacs modes are already separate repos, but it's probably not worth the hassle for the others. Especially if multiple of them are xml-based, then there might be some common scripts you could write for autogenerating and updating them all.

**Comment by femtotrader** [comment]
ok so what repository name now  ?

- `EditorModes` like @ViralBShah suggested or
- `JuliaEditorSupport` like org name

Any other ideas ?

**Comment by femtotrader** [comment]
About generating XML files, Python have a great library (in my opinion) to create XML file named yattag http://www.yattag.org/ It's based on context managers. Unfortunately I'm not sure this concept exists in Julia so creating XML file using "raw" method will probably be necessary. An other approach may be to use a template library like http://jinja.pocoo.org/ but is there a kind of template library in Julia ?

**Comment by IainNZ** [comment]
https://github.com/jverzani/Mustache.jl is quite nice

**Comment by femtotrader** [comment]
`BBEditTextWrangler-julia.plist` is now available at

https://github.com/JuliaEditorSupport/JuliaEditorSupport

**Comment by tkelman** [comment]
Great, thanks! We could add a link to that repo from somewhere, maybe contrib/README.md if people are looking for where that file went.

**Pull request merged**
