### PR TITLE
WIP: replace some characters in the symbol for ccall library names that can n cause the linker to fail on Windows

### PR DESCRIPTION
**Pull request by KristofferC**
Ref: https://github.com/JuliaLang/PackageCompiler.jl/issues/365

Just getting the build bots to run this so I can get an executable to try this with.

### CODE REVIEW

**Comment by KristofferC** [comment]
This fixes the MWE I have for this issue.

**Comment by vtjnash** [comment]
The `-` is already on our blacklist (https://github.com/JuliaLang/julia/blob/master/src/aotcompile.cpp#L191), but this is possibly an llvm bug with `.drectve` emission (documentation for this linker flag suggests using quotes around it, but emitLinkerFlagsForGlobalCOFF omits them)

**Comment by KristofferC** [comment]
Thanks, so can something like this PR be used to workaround the upstream issue or what would be the best way forward?

**Comment by vtjnash** [comment]
Make a commit to LLVM (https://reviews.llvm.org or with `arc diff`) and add the patch here to Julia

**Pull request closed without merging**
