### PR TITLE
Revert "do not intentionally suppress errors in precompile script from being reported or failing the result"

### LINKED ISSUE #56063: big startup time regression with v1.11 release
There was a regression between the last release candidate and the release:

```none
$ hyperfine './julia-1.10.5/bin/julia --startup-file=no -e "1+1"'
Benchmark 1: ./julia-1.10.5/bin/julia --startup-file=no -e "1+1"
  Time (mean ± σ):     160.0 ms ±   0.9 ms    [User: 77.7 ms, System: 84.9 ms]
  Range (min … max):   158.2 ms … 161.3 ms    18 runs
 
$ hyperfine './julia-1.11.0-rc4/bin/julia --startup-file=no -e "1+1"'
Benchmark 1: ./julia-1.11.0-rc4/bin/julia --startup-file=no -e "1+1"
  Time (mean ± σ):     126.1 ms ±   1.6 ms    [User: 61.7 ms, System: 63.3 ms]
  Range (min … max):   122.8 ms … 128.6 ms    23 runs
 
$ hyperfine './julia-1.11.0/bin/julia --startup-file=no -e "1+1"'
Benchmark 1: ./julia-1.11.0/bin/julia --startup-file=no -e "1+1"
  Time (mean ± σ):     304.6 ms ±   4.4 ms    [User: 528.1 ms, System: 84.3 ms]
  Range (min … max):   300.0 ms … 315.1 ms    10 runs
```

Maybe because of this additional required compilation:

```none
$ ./julia-1.11.0-rc4/bin/julia --startup-file=no -e "1+1" --trace-compile=stderr
$ ./julia-1.11.0/bin/julia --startup-file=no -e "1+1" --trace-compile=stderr
precompile(Tuple{Base.var"#759#760"{Task}})
```

Version info:

```none
Julia Version 1.11.0
Commit 501a4f25c2b (2024-10-07 11:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 4
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

### PR DESCRIPTION
**Pull request by KristofferC**
Reverts JuliaLang/julia#55909

Fixes https://github.com/JuliaLang/julia/issues/56063. Caused a 3x startup regression in 1.11.0.

### CODE REVIEW

**Comment by giordano** [comment]
> Fixes #56063.

That's still an issue on `master` for v1.12, isn't it?

**Comment by nsajko** [comment]
The regression doesn't seem to exist on master, though, just on v1.11:

```none
$ hyperfine './nightly_normal/julia-ecf41b18cc/bin/julia --startup-file=no -e "1+1"'
Benchmark 1: ./nightly_normal/julia-ecf41b18cc/bin/julia --startup-file=no -e "1+1"
  Time (mean ± σ):     139.6 ms ±   0.8 ms    [User: 71.1 ms, System: 66.8 ms]
  Range (min … max):   138.2 ms … 141.6 ms    21 runs
```

`--trace-compile=stderr` also doesn't produce any output for startup on nightly.

**Comment by IanButterworth** [comment]
Does anyone happen to see the issue with that PR?

**Comment by vtjnash** [comment]
This should be against the backport branch, not master, since it doesn't affect master

**Comment by KristofferC** [comment]
I just pushed the commit to the backport branch.

**Comment by topolarity** [comment]
Did we ever figure out why this was causing issues on 1.11? Seems pretty mysterious

**Comment by DilumAluthge** [comment]
> I just pushed the commit to the backport branch.

Per https://github.com/JuliaLang/julia/pull/56069#issuecomment-2404686329, I am assuming that we no longer need the backport label on this PR?

**Pull request closed without merging**
