### PR TITLE
Add `Base.LineEdit.get_current_state()` to get current REPL state

### PR DESCRIPTION
**Pull request by staticfloat**
This implements @ihnorton's suggestion for https://github.com/JuliaLang/julia/issues/13356, hopefully pushing forward on our ability to hack REPL outputting in a more reliable way.  This adds an (unexported) function `Base.LineEdit.get_current_state()` that returns the current REPL state.

### CODE REVIEW

**Comment by rfourquet** [comment]
I have wanted this functionality for a while, thanks! but As we can already get a hold on `Base.active_repl`, why not make an `state::MIState` object a member of `LineEditREPL` ? I think this would be cleaner (rather than having another global variable), although I'm not certain it's possible or wanted.

**Comment by staticfloat** [comment]
Hmmm, yes, that does seem cleaner to me as well.  Any objections?  @ihnorton I assume that would work well for your use case?

**Comment by ihnorton** [comment]
I think so -- it's more @davidanthoff's use case (I was just golfing and haven't looked at this since, but glad it was a useful lead).

**Comment by staticfloat** [comment]
@rfourquet I would be happy to review a PR if you want to submit one.  Just ping me via @staticfloat

**Comment by rfourquet** [comment]
No problem will do!

**Pull request closed without merging**
