### PR TITLE
fix collect on stateful iterators

### LINKED ISSUE #42168: Problematic interaction between Stateful and map
When trying the following code:
```julia
v = split("abcd", "")
it = Iterators.Stateful(Iterators.map(identity, v))
popfirst!(it)
popfirst!(it)
collect(Iterators.take(it, 2))
```
in Julia 1.6.2 and 1.7.0-beta4:
```julia
signal (11): Segmentation fault
in expression starting at none:0
jl_gc_pool_alloc at /buildworker/worker/package_linux64/build/src/gc.c:1211
jl_gc_alloc_ at /buildworker/worker/package_linux64/build/src/julia_internal.h:336 [inlined]
jl_gc_alloc at /buildworker/worker/package_linux64/build/src/gc.c:3278
jl_gc_alloc_buf at /buildworker/worker/package_linux64/build/src/julia_internal.h:370 [inlined]
[...]
```

whereas in Julia 1.8.0-DEV.486 a simple error (still not the right answer):
```julia
ERROR: BoundsError: attempt to access 1-element Vector{SubString{String}} at index [2]
Stacktrace:
 [1] setindex!
   @ ./array.jl:946 [inlined]
 [2] collect_to!
   @ ./array.jl:829 [inlined]
 [3] collect_to_with_first!
   @ ./array.jl:803 [inlined]
 [4] _collect(c::UnitRange{Int64}, itr::Base.Iterators.Take{Base.Iterators.Stateful{Base.Generator{Vector{SubString{String}}, typeof(identity)}, Union{Nothing, Tuple{SubString{String}, Int64}}}}, #unused#::Base.EltypeUnknown, isz::Base.HasLength)
   @ Base ./array.jl:797
 [5] collect(itr::Base.Iterators.Take{Base.Iterators.Stateful{Base.Generator{Vector{SubString{String}}, typeof(identity)}, Union{Nothing, Tuple{SubString{String}, Int64}}}})
   @ Base ./array.jl:694
 [6] top-level scope
   @ REPL[4]:1
```

Might be related to #35530 and #41919

### PR DESCRIPTION
**Pull request by vtjnash**
Generalization of #41919
Fixes #42168

Needed to also fix some ssair code, which was unnecessarily relying on inference recursively, and led to some other fixes.

### CODE REVIEW

**Comment by bramtayl** [comment]
This seems to have broken `Unzip.jl`. Is the type assert really necessary?

```
julia> using Unzip

julia> function unstable(x)
           if x == 2
               (x, x + 0.0, x, x + 0.0)
           else
               (x, x + 0.0)
           end
       end
unstable (generic function with 1 method)

julia> unzip(Iterators.map(unstable, 1:3))
ERROR: TypeError: in typeassert, expected AbstractVector{<:Tuple{Int64, Float64, Vararg{Real}}}, got a value of type Unzip.Rows{Tuple{Int64, Float64, Union{Missing, Int64}, Union{Missing, Float64}}, 1, Tuple{Vector{Int64}, Vector{Float64}, Vector{Union{Missing, Int64}}, Vector{Union{Missing, Float64}}}}
Stacktrace:
 [1] _collect(c::Unzip.Rows{Tuple{}, 1, Tuple{}}, itr::Base.Generator{UnitRange{Int64}, typeof(unstable)}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
   @ Base .\array.jl:754
 [2] unzip(rows::Base.Generator{UnitRange{Int64}, typeof(unstable)})
   @ Unzip C:\Users\brand\.julia\dev\Unzip\src\Unzip.jl:282
 [3] top-level scope
   @ REPL[14]:1
```

**Comment by vtjnash** [comment]
It looks like Unzip has a bug where it accidentally tries to return a `Missing` value in the result, where no such value existed initially?

**Comment by bramtayl** [comment]
Nope, that's not a bug, it's a choice. Unzip will fill in missing for iterators of differently sized tuples:

```
unzip([(1, 'a'), (2,), (3, 'b')] = ([1, 2, 3], [1, missing, 'b'])
```

I found this while rewriting, so this is no longer an issue, but.

**Comment by vtjnash** [comment]
zip is expected to truncate to the shortest input

**Comment by bramtayl** [comment]
Hmm, well, I guess that implies that zip could never provide tuples of different sizes, so unzipping tuples of different sizes is undefined...I could error here, which would make the code a lot simpler but also less fun. As of now, I have my own version of the collect method, without a type assert, that will error for empty iterators if I can't guess the column types. https://github.com/bramtayl/Unzip.jl/blob/c239114b4b7faf71dab924c1832a11eaa0312d22/src/Unzip.jl#L317

**Pull request merged**
