### PR TITLE
Fix reinterpret performance

### LINKED ISSUE #25014: Performance concerns with ReinterpretArray
Ref https://discourse.julialang.org/t/big-overhead-with-the-new-lazy-reshape-reinterpret/7635

### PR DESCRIPTION
**Pull request by Keno**
This fixes #25014 by making it more obvious what's going on to LLVM.
Instead of a memcpy loop, we use a new intrinsic that puts an actual
llvm.memcpy into the IR, which is enough for LLVM to fold everything
away. In the benchmark from #25014, we still see some regressions from
0.6, but that is because it needs to dereference through the pointers
in the reinterpret and reshape wrappers. In any real code, that
dereferencing should be loop-invariantly moved out of the inner loop.

### CODE REVIEW

**Comment by vtjnash** [comment]
Glad to see this works. Can we just transparently make this he implementation of `ccall(:memcpy)` (it looks like we don’t need the extra alignment argument right now)

**Comment by Keno** [comment]
> Can we just transparently make this he implementation of ccall(:memcpy)

Ok, let's do it that way. We can always add the aligned version if we need it later.

**Comment by Keno** [comment]
> Does this make the alignment workaround [...] fast

Probably

**Comment by StefanKarpinski** [comment]
This seems eligible for 1.0.1, right?

**Comment by Keno** [comment]
Yes, already has the backport label.

**Pull request merged**
