### PR TITLE
use jl_gc_alloc inside jl_alloc_string

### PR DESCRIPTION
**Pull request by d-netto**

### CODE REVIEW

**Comment by d-netto** [comment]
Want to note that technically this PR causes a bit of change of behavior in the allocation profiler.

`sz` is larger than `len` by `sizeof(size_t) + 1`, so we're technically reporting 9 extra bytes each String in this PR on 64-bit machines.

**Comment by kpamnany** [comment]
> `sz` is larger than `len` by `sizeof(size_t) + 1`, so we're technically reporting 9 extra bytes for each String in this PR on 64-bit machines.

These bytes are actually allocated though, so from that perspective, this is improving the accuracy? Or do I misunderstand?

**Comment by d-netto** [comment]
Yes, given that these bytes are actually allocated, then I think we should count them (and that would improve accuracy from that perspective indeed).

But there might be a reason which I don't know yet for why len was being reported in the profiler, so waiting for folks to chime in.

**Comment by d-netto** [comment]
Bump?

**Pull request merged**
