### PR TITLE
define jl_value_t* in llvmcall to be i8**

### PR DESCRIPTION
**Pull request by vtjnash**
when calling the llvm parser, it will unique any type definition, making it impossible to use `jl_value_t*`.
avoid that by defining `jl_value_t*` to be handled as `i8**`

@Keno I realize this will probably break Cxx.jl, since there you are emitting `Function*` objects directly, but this seemed to be necessary to make it possible to pass `Any` to an llvmcall as a string.

### CODE REVIEW

**Comment by Keno** [comment]
I have some thoughts on fixing this in LLVM proper, but this seems OK otherwise. Do hold off on merging though.

**Comment by vtjnash** [comment]
is llvm actually interested in "fixing" this? I agree that the change is small, but I found multiple questions to the dev list when they first introduced this change (including proposed patches), but none of them got a response. in some ways, i think it's nice not to depend on the magic string "jl_value_t", but to instead have something stable like "i8**".

plus, since pointer types are going away in soon enough in llvm, i'm not sure if it's worth trying to drive any changes into llvm for this anyways and instead just go with something simple that works on any version of llvm.

**Comment by vtjnash** [comment]
Can you talk more about the disadvantages of just defining julia values as getting passed as generic pointers (i8**) instead of an unusable symbol? Is this something that might cause support issues or are there other potential downsides?

**Comment by vtjnash** [comment]
i guess i'll merge this tomorrow if there are no comments forthcoming

**Pull request closed without merging**
