### PR TITLE
Add to documentation of two-argument atan

### PR DESCRIPTION
**Pull request by ambyld**
Fix agrees with the listed reference and the function behavior.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Well, not really... there are a couple of interpretations one could use here:

a. Since pi isn't exactly representable in floating point, then the result has to be in the open interval (-pi,pi).

b. Alternatively, you could view it as "what is the value it would be before rounding", and then since IEEE arithmetic supports signed 0, and [for various complicated but mathematically elegant reasons](https://people.freebsd.org/~das/kahan86branch.pdf), `atan(-0.0,x)` is defined to be `-pi` when `x < 0`, we would have [-pi,pi]. It would be good to have this noted in the docs.

c. Or, one could ask what would happen if both the result and pi were rounded, then you would have:
```
julia> -Float64(pi) == atan(-0.0,-1.0)
true
```
which again would lead to [-pi,pi].

**Comment by ambyld** [comment]
Sure, pi isn't representable in floating point, but the point of this fix is to answer the question of whether atan(0,1) = pi or atan(0,1) = -pi (or whichever floating point numbers are closest to pi and -pi) without having to test it manually.

Mathematically both cannot be true, which is why the reference https://en.wikipedia.org/wiki/Atan2 chooses (-pi,pi] as the image of atan2. And indeed atan(0,1) = pi in Julia.

**Comment by ambyld** [comment]
Interesting, I didn't realize `-Float64(pi) == atan(-0.0,-1.0)`. Thank you for the reference - there is much more to this than I expected.

**Comment by simonbyrne** [comment]
At some point we should document all the branch cut behavior, but this is clearly an improvement.

**Pull request merged**
