### PR TITLE
WIP: Backports for Julia 1.5-beta-1

### LINKED ISSUE #35782: WeakKeyDict c-tor for Pairs is broken due to missing sizehint!
MWE:
```julia
julia> A = [1]; B = [2]; C = [3];

julia> WeakKeyDict{typeof(A), Int64}(Pair(A, 1), Pair(B, 2), Pair(C, 3))
hi
ERROR: MethodError: no method matching sizehint!(::WeakKeyDict{Array{Int64,1},Int64}, ::Int64)
Closest candidates are:
  sizehint!(::Array{T,1} where T, ::Integer) at array.jl:1092
  sizehint!(::IdDict, ::Any) at iddict.jl:59
  sizehint!(::Base.IdSet, ::Any) at idset.jl:23
  ...
Stacktrace:
 [1] WeakKeyDict{Array{Int64,1},Int64}(::Pair{Array{Int64,1},Int64}, ::Vararg{Pair{Array{Int64,1},Int64},N} where N) at ./weakkeydict.jl:45
 [2] top-level scope at REPL[2]:1
```

this is happening in [this](https://github.com/JuliaLang/julia/blob/master/base/weakkeydict.jl#L42) constructor which is currently [untested](https://codecov.io/gh/julialang/julia/src/master/base/weakkeydict.jl#L42).

### LINKED ISSUE #35793: assertion failure in codegen with union of singletons
```
julia> struct X
       x::Union{Nothing,Missing}
       end

julia> X(nothing)
julia: /home/jeff/src/julia/src/cgutils.cpp:705: llvm::Type* _julia_struct_to_llvm(jl_codegen_params_t*, jl_value_t*, jl_unionall_t*, bool*, bool): Assertion `NumATy > 0' failed.
```

The assertion is new in 1.5. It looks to me like the assertion can possibly just be removed, but I'm not sure. cc @vtjnash

### LINKED ISSUE #35937: Erroring when inside a thread in a distributed process causes MethodError
Running this on Julia 1.3, 1.4, and a 1.6 Nightly from last week 
```julia
using Distributed
addprocs(2)
@everywhere using Base.Threads

pmap(1:2) do i
    @threads for i in 1:10
        error()
    end
end
```
gets this error
```
➜ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

julia> using Distributed

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @everywhere using Base.Threads

julia> pmap(1:2) do i
           @threads for i in 1:10
               error()
           end
       end

ERROR: On worker 2:
TaskFailedException:

wait at ./task.jl:267
macro expansion at ./threadingconstructs.jl:69 [inlined]
#3 at ./REPL[5]:2
#104 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:294
run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:79
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:294 [inlined]
#103 at ./task.jl:358
Stacktrace:
 [1] (::Base.var"#726#728")(::Task) at ./asyncmap.jl:178
 [2] foreach(::Base.var"#726#728", ::Array{Any,1}) at ./abstractarray.jl:1919
 [3] maptwice(::Function, ::Channel{Any}, ::Array{Any,1}, ::UnitRange{Int64}) at ./asyncmap.jl:178
 [4] wrap_n_exec_twice(::Channel{Any}, ::Array{Any,1}, ::Distributed.var"#204#207"{WorkerPool}, ::Function, ::UnitRange{Int64}) at ./asyncmap.jl:154
 [5] async_usemap(::Distributed.var"#188#190"{Distributed.var"#188#189#191"{WorkerPool,var"#3#4"}}, ::UnitRange{Int64}; ntasks::Function, batch_size::Nothing) at ./asyncmap.jl:103
 [6] #asyncmap#710 at ./asyncmap.jl:81 [inlined]
 [7] pmap(::Function, ::WorkerPool, ::UnitRange{Int64}; distributed::Bool, batch_size::Int64, on_error::Nothing, retry_delays::Array{Any,1}, retry_check::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/pmap.jl:126
 [8] pmap(::Function, ::WorkerPool, ::UnitRange{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/pmap.jl:101
 [9] pmap(::Function, ::UnitRange{Int64}; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/pmap.jl:156
 [10] pmap(::Function, ::UnitRange{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/pmap.jl:156
 [11] top-level scope at REPL[5]:1
SYSTEM (REPL): showing an error caused an error
ERROR: MethodError: no method matching show_backtrace(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Nothing)
Closest candidates are:
  show_backtrace(::IO, ::Array{Any,1}) at errorshow.jl:637
  show_backtrace(::IO, ::Array{T,1} where T) at errorshow.jl:608
Stacktrace:
 [1] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ErrorException, ::Nothing; backtrace::Bool) at ./errorshow.jl:79
 [2] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::ErrorException, ::Nothing) at ./errorshow.jl:74
 [3] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::TaskFailedException) at ./task.jl:76
 [4] (::Base.var"#649#650"{TaskFailedException})(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}) at ./errorshow.jl:76
 [5] with_output_color(::Function, ::Symbol, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}; bold::Bool) at ./util.jl:385
 [6] with_output_color(::Function, ::Symbol, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}) at ./util.jl:383
 [7] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::TaskFailedException, ::Array{Any,1}; backtrace::Bool) at ./errorshow.jl:75
 [8] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::CapturedException) at ./task.jl:25
 [9] showerror(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::RemoteException) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:57
 [10] (::Base.var"#649#650"{RemoteException})(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}) at ./errorshow.jl:76
 [11] with_output_color(::Function, ::Symbol, ::IOContext{REPL.Terminals.TTYTerminal}; bold::Bool) at ./util.jl:385
 [12] with_output_color(::Function, ::Symbol, ::IOContext{REPL.Terminals.TTYTerminal}) at ./util.jl:383
 [13] showerror(::IOContext{REPL.Terminals.TTYTerminal}, ::RemoteException, ::Array{Base.StackTraces.StackFrame,1}; backtrace::Bool) at ./errorshow.jl:75
 [14] show_exception_stack(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Any,1}) at ./errorshow.jl:705
 [15] display_error(::IOContext{REPL.Terminals.TTYTerminal}, ::Array{Any,1}) at ./client.jl:104
 [16] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [17] invokelatest at ./essentials.jl:711 [inlined]
 [18] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:156
 [19] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
 [20] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
 [21] (::REPL.var"#53#62")(::Any, ::Any, ::Vararg{Any,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:997
 [22] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [23] invokelatest at ./essentials.jl:711 [inlined]
 [24] (::REPL.LineEdit.var"#22#23"{REPL.var"#53#62",String})(::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:1364
 [25] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2446
 [26] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2349
 [27] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
 [28] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
 [29] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [30] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [31] invokelatest at ./essentials.jl:711 [inlined]
 [32] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [33] exec_options(::Base.JLOptions) at ./client.jl:305
 [34] _start() at ./client.jl:484

julia> 
```

The error 
```
ERROR: MethodError: no method matching show_backtrace(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Nothing)
```
with the following stack trace eats up a lot of the logs and makes it harder to parse the real issue. 

Found the same problem here https://github.com/JunoLab/Juno.jl/issues/572

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #35783 - Fix bad c-tor for WeakKeyDict. Fix #35782
- [x] #35758 - Have matrix square root account for Rii=Rjj=0 to prevent NaN values
- [x] #35807 - Add a note to sharedarrays documentation.
- [x] #35812 - fix #35793, assertion failure with union of singletons
- [x] #35821 - Fix evalpoly docstring
- [x] #35869 - Bump Statistics stdlib module
- [x] #35874 - bump Pkg version
- [x] #35871 - Fix ImmutableDict(:a => 1, :a => 2)[:a]
- [x] #35802 - More robust installation of BugReporting package.
- [x] #35900 - Fix codegen for sizeof for arrays with non-power-of-2 types
- [x] #35965 - fix some 1.5 compatibility issues
- [x] #35943 - fix #35937, serializing TaskFailedException in Distributed
- [x] #35979 - Bump Zlib BB release to `v1.2.11+10` which enables `-O3` optimisation
- [x] #35843 - Implement reduce_empty(op, Union{})
- [x] #35957 - Expose some additional LLVM APIs.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/35846#issuecomment-627136566) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/710afb54a2597ae82d0db6aae29bda91a525fe14/d8b3739_vs_ef4fe83/report.md). cc @ararslan

**Comment by KristofferC** [comment]
Some stuff to look at:

```
["array", "reductions", "(\"mean\", \"Float64\")"] | 1.08 (5%) ❌ | Inf (1%) ❌
["array", "reductions", "(\"mean\", \"Int64\")"] | 8.12 (5%) ❌ | Inf (1%) ❌

["io", "array_limit", "(\"display\", \"Array{Float64,2}(10000, 10000)\")"] | 3.13 (5%) ❌ | 0.99 (1%) ✅
["io", "array_limit", "(\"display\", \"Array{Float64,2}(100000000, 1)\")"] | 3.55 (5%) ❌ | 1.05 (1%) ❌
["io", "serialization", "(\"deserialize\", \"Vector{String}\")"] | 2.36 (5%) ❌ | 2.05 (1%) ❌
["io", "serialization", "(\"serialize\", \"Vector{String}\")"] | 3.08 (5%) ❌ | 2.23 (1%) ❌

["sparse", "index", "(\"spmat\", \"splogical\", 10)"] | 2.90 (30%) ❌ | 0.77 (1%) ✅
["sparse", "index", "(\"spmat\", \"splogical\", 100)"] | 97.14 (30%) ❌ | 0.77 (1%) ✅
["sparse", "index", "(\"spmat\", \"splogical\", 1000)"] | 2.88 (30%) ❌ | 0.87


["sparse", "matmul", "(\"A_mul_B\", \"dense 50x5, sparse 5x50 -> dense 50x50\")"] | 1.64 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"dense 50x50, sparse 50x50 -> dense 50x50\")"] | 1.55 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"dense 5x5, sparse 5x500 -> dense 5x500\")"] | 1.67 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"dense 5x50, sparse 50x500 -> dense 5x500\")"] | 1.70 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"dense 5x500, sparse 500x50 -> dense 5x50\")"] | 1.53 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"dense 5x500, sparse 500x500 -> dense 5x500\")"] | 1.64 (30%) ❌ | 1.00 (1%)
["sparse", "matmul", "(\"A_mul_B\", \"sparse 50x500, dense 500x5 -> dense 50x5\")"] | 1.36 (30%) ❌ | 1.00 (1%)

["sparse", "sparse solves", "square system (lu), vector rhs"] | 1.87 (5%) ❌ | 1.71 (1%) ❌
["sparse", "transpose", "(\"adjoint!\", (20000, 10000))"] | 1.00 (30%) | 4.00 (1%) ❌
["sparse", "transpose", "(\"adjoint!\", (20000, 20000))"] | 1.00 (30%) | 4.00 (1%) ❌
["sparse", "transpose", "(\"adjoint!\", (600, 400))"] | 1.01 (30%) | 4.00 (1%) ❌
["sparse", "transpose", "(\"adjoint!\", (600, 600))"] | 1.00 (30%) | 4.00 (1%) ❌
```

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35846#issuecomment-627136444) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/463af6b0fc72dc8500d0bdf4b620c66159588fb6/pkgeval/by_hash/8babf99_vs_ef4fe83/report.md). cc @maleadt

**Comment by KristofferC** [comment]
I ran PkgEval with the wrong base branch so results here are not 100% accurate (although it should be pretty close because not much have happened on master since branching).

**Comment by maleadt** [comment]
Let's rerun to be sure (and stress-test some PkgEval changes):

@nanosoldier `runtests(ALL, vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35846#issuecomment-628162186) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/5ce06f6a3900f1088e9e3a4e60dac173258e36ee/pkgeval/by_hash/8babf99_vs_ef4fe83/report.md). cc @maleadt

**Comment by KristofferC** [comment]
The PkgEval result is extermely noisy now due to all changes in the RNG streams (https://github.com/JuliaLang/julia/pull/32208, https://github.com/JuliaLang/julia/pull/33721, https://github.com/JuliaLang/julia/pull/35078, https://github.com/JuliaLang/julia/pull/29240).

This are the packages that failed the previous PkgEval but I filtered out all packages that failed in one of the PkgEvals for the RNG changes to at least be able start looking  at stuff that are less likely to just be reliance on RNG streams in test.

@nanosoldier `runtests(["AMRVW", "AdvancedHMC", "ApproxFun", "ApproxFunFourier", "ApproxFunRational", "ApproxFunSingularities", "ArrayLayouts", "AutoPreallocation", "AxisIndices", "AxisKeys", "BangBang", "BenchmarkCI", "BlockArrays", "Bridge", "BrkgaMpIpr", "CBindingGen", "ChainRulesCore", "Chemfiles", "ClinicalTrialUtilities", "ColorVectorSpace", "ComponentArrays", "ContinuumArrays", "CorticalSpectralTemporalResponses", "CoverageCore", "CoverageTools", "CurveProximityQueries", "DataAssim", "DataStructures", "DependencyWalker", "DiffEqBayes", "DiffEqParamEstim", "DimensionalData", "DistributedArrays", "Diversity", "Documenter", "DynamicAxisWarping", "DynamicGrids", "FIGlet", "FastIOBuffers", "FillArrays", "FunctionOperators", "FunctionalCollections", "FunctionalTables", "GEMPIC", "GeometryTypes", "Gtk", "GtkReactive", "HomotopyContinuation", "IMFData", "ImageInTerminal", "ImageSegmentation", "ImageView", "InfiniteArrays", "IntervalArithmetic", "JLD2", "JSONSchema", "JuliaVariables", "KrigingModel", "LazyArrays", "LazyStack", "Lerche", "LibGEOS", "LikelihoodProfiler", "LinearMapsAA", "LiveServer", "MIToS", "MicroCoverage", "MultiplesOfPi", "Nabla", "NiLangCore", "OceanGrids", "OpenEphysLoader", "OrthogonalPolynomialsQuasi", "OscillatoryIntegrals", "Pajarito", "PassiveTracerFlows", "PkgBenchmark", "PlotUtils", "Plots", "Pluto", "Polymake", "PowerDynSolve", "PredictMD", "PredictMDFull", "QuadraticToBinary", "QuantumOpticsBase", "QuasiArrays", "RecursiveArrayTools", "RiemannHilbert", "RigidBodyDynamics", "Simulate", "SingularIntegralEquations", "SingularSpectrumAnalysis", "SolverTraces", "SparseGaussianProcesses", "StaticArrays", "StaticNumbers", "StrBase", "StrRegex", "TaylorIntegration", "TensorKitManifolds", "ThreadTools", "ThreePhasePowerModels", "TikzQTrees", "Tracker", "Turf", "TypedPolynomials", "VarStructs", "Wrangling", "XLSXasJSON", "ArchGDAL", "AugmentedGaussianProcesses", "CUDAatomics", "CancerSeqSim", "CompScienceMeshes", "Crayons", "DynamicGridsGtk", "DynamicGridsInteract", "ExprRules", "FEMBase", "FEMBasis", "Fatou", "FieldMetadata", "GtkUtilities", "HybridArrays", "Immerse", "InspectDR", "KnetOnnx", "LegibleLambdas", "LocalRegistry", "MCHammer", "MLStyle", "Manifolds", "Manopt", "Maxvol", "Miletus", "NTFk", "NTNk", "NarrativeTest", "OhMyQSIM", "Persa", "PhysicsInformedML", "Poltergeist", "ProfileView", "RevealedPreferences", "RoMEPlotting", "SimpleGF2", "StructuralInheritance", "TrajectoryOptimization", "TuringModels", "TwoFAST", "VerTeX", "VideoIO", "Winston", "BloomFilters", "Hyperopt", "QuartetNetworkGoodnessFit", "ReinforcementLearningZoo", "DRIPs", "DirectGaussianSimulation", "Gridap", "ImageInpainting", "PowerModels", "StratiGraphics", "DataFlow", "EfficientGlobalOptimization", "ExtensibleUnions", "FastJet", "MbedTLS", "OptionalArgChecks"], vs=":release-1.4")`

**Comment by KristofferC** [comment]
For people pushing commits to this branch (@ViralBShah), please make sure the original PR has a backport label, that you use `cherry-pick -x` and that you update the first post with the PR.

**Comment by ViralBShah** [comment]
I merged a PR and only later realized it went onto this branch. It would be fine to revert it and do the right thing.

However what is the right way to do this? Since this updated NEWS on master but here the update was to be made in HISTORY.

**Comment by KristofferC** [comment]
If it is a commit that  wasn't merged into master then just mergint he PR into here (like what was done) makes sense, I didn't notice that was the case. Could perhaps just add a note to the top post so that everything that gets put in is accounted for.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35846#issuecomment-630071311) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/18bb6d85b20e25f1a9f2f312963f4b8b4fe7082e/pkgeval/by_hash/a340bf1_vs_3c50b7f/report.md). cc @maleadt

**Comment by KristofferC** [comment]
There are so many PkgEval "regressions" here that I think it would be useful to merge this, and release a 1.5-beta to make it easier for the community in help testing / fixing packages.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AMRVW", "AdvancedHMC", "ApproxFun", "ApproxFunFourier", "ApproxFunRational", "ApproxFunSingularities", "ArchGDAL", "ArrayLayouts", "AugmentedGaussianProcesses", "AutoPreallocation", "AxisIndices", "AxisKeys", "BangBang", "BenchmarkCI", "BlockArrays", "BloomFilters", "Bridge", "CBindingGen", "CUDAatomics", "CancerSeqSim", "ChainRulesCore", "Chemfiles", "ClinicalTrialUtilities", "ColorVectorSpace", "CompScienceMeshes", "ComponentArrays", "ContinuumArrays", "CoverageCore", "CoverageTools", "CurveProximityQueries", "DRIPs", "DataAssim", "DataFlow", "DimensionalData", "DirectGaussianSimulation", "DistributedArrays", "Diversity", "Documenter", "DynamicGrids", "DynamicGridsGtk", "DynamicGridsInteract", "EfficientGlobalOptimization", "ExprRules", "ExtensibleUnions", "FEMBase", "FEMBasis", "FIGlet", "FastIOBuffers", "FastJet", "FieldMetadata", "FillArrays", "FunctionalCollections", "FunctionalTables", "GeometryTypes", "Gtk", "GtkReactive", "GtkUtilities", "HomotopyContinuation", "HybridArrays", "ImageInpainting", "ImageView", "Immerse", "InfiniteArrays", "InspectDR", "IntervalArithmetic", "JLD2", "JSONSchema", "JuliaVariables", "KnetOnnx", "KrigingModel", "LazyArrays", "LazyStack", "LegibleLambdas", "Lerche", "LibGEOS", "LinearMapsAA", "LocalRegistry", "MCHammer", "MIToS", "MLStyle", "Manifolds", "Manopt", "Maxvol", "MbedTLS", "MicroCoverage", "Miletus", "MultiplesOfPi", "NTFk", "NTNk", "Nabla", "NarrativeTest", "NiLangCore", "OceanGrids", "OhMyQSIM", "OpenEphysLoader", "OptionalArgChecks", "OrthogonalPolynomialsQuasi", "OscillatoryIntegrals", "Pajarito", "PassiveTracerFlows", "Persa", "PhysicsInformedML", "PkgBenchmark", "PlotUtils", "Plots", "Poltergeist", "Polymake", "PowerDynSolve", "PredictMD", "PredictMDFull", "ProfileView", "QuantumOpticsBase", "QuartetNetworkGoodnessFit", "QuasiArrays", "RecursiveArrayTools", "RevealedPreferences", "RiemannHilbert", "RigidBodyDynamics", "RoMEPlotting", "SimpleGF2", "SingularIntegralEquations", "SingularSpectrumAnalysis", "StaticArrays", "StaticNumbers", "StrBase", "StrRegex", "StratiGraphics", "StructuralInheritance", "TaylorIntegration", "TensorKitManifolds", "ThreadTools", "ThreePhasePowerModels", "TikzQTrees", "TrajectoryOptimization", "Turf", "TuringModels", "TwoFAST", "VarStructs", "VerTeX", "Winston", "Wrangling", "XLSXasJSON"], vs = ":release-1.4")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35846#issuecomment-633821836) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/report.md). cc @maleadt

**Pull request merged**
