### PR TITLE
multiplication of sparse triangular matrices #35609 #35610 #35642

### LINKED ISSUE #719: Multiplying triangular sparse matrix with sparse matrix fails to return sparse matrix
Multiplying an `UpperTriangular{SparseMatrixCSC}` with a `SparseMatrixCSC` should return a sparse matrix. It returns a dense matrix as of version 1.2.
Computational effort should be approximately 1/2 of sparse multiplication of SparseMatrixCSC.

```
julia> VERSION
v"1.4.1" # same for v"1.2.0"
julia> X = UpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> typeof(X * Y)
Array{Float64,2}
```
With version 1, we have the same error as in JuliaLang/julia#35609
```
julia> VERSION
v"1.0.5"
julia> X = UnitUpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> X * Y;
ERROR: MethodError: no method matching lmul!(::UnitUpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}, ::SparseMatrixCSC{Float64,Int64})
```

### LINKED ISSUE #721: Multiply sparse matrix or triangular sparse matrix with sparse vector fails or is inconsistent
We observed the following behavior in `v1.4.0`/`v1.5.-DEV`. The situation is not better in older versions.
I would like to make all the products work and all return the type `SparseVector` as multiplication with a `SparseMatrixCSC` does.
```
julia> N = 50;
julia> A = (sprand(N, N, 10/N));
julia> U = UpperTriangular(A);
julia> L = LowerTriangular(A);
julia> x = sprand(N, 10/N); # SparseVector
julia> y = view(A,:,40);  # SparseColumnView
julia> z = view(x, :); # View on sparse vector

julia> for M in (A, U, L), v in (x, y, z)
           try
               println( typeof(M * v) )
           catch
               println(typeof(M), " * ", typeof(v), " failed")
           end
       end

SparseVector{Float64,Int64}
SparseVector{Float64,Int64}
SparseVector{Float64,Int64}

Array{Float64,1} 

UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseMatrixCSC{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},false} failed

UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseVector{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}}},false} failed

Array{Float64,1}

LowerTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseMatrixCSC{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},false} failed

LowerTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseVector{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}}},false} failed
```

### LINKED ISSUE #35609: Unable to multiply two triangular sparse matrices
Multiplying two `UpperTriangular{SparseMatrixCSC}` and friends should return a matrix of the same type.
Computational effort should be approximately 1/4 of sparse multiplication of `SparseMatrixCSC`.

It throws a `Method Error` instead.

```
julia> X = UpperTriangular(sprand(100, 100, 10*1e-2));

julia> X * X
ERROR: MethodError: no method matching lmul!(::UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}, ::SparseMatrixCSC{Float64,Int64})
  ...
Stacktrace:
 [1] *(::UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}, ::UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}) at /home/crusius/julia-1.0.5/share/julia/stdlib/v1.0/LinearAlgebra/src/triangular.jl:1627
```

### LINKED ISSUE #35610: Multiplying triangular sparse matrix with sparse matrix fails to return sparse matrix
Multiplying an `UpperTriangular{SparseMatrixCSC}` with a `SparseMatrixCSC` should return a sparse matrix. It returns a dense matrix as of version 1.2.
Computational effort should be approximately 1/2 of sparse multiplication of SparseMatrixCSC.

```
julia> VERSION
v"1.4.1" # same for v"1.2.0"
julia> X = UpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> typeof(X * Y)
Array{Float64,2}
```
With version 1, we have the same error as in #35609
```
julia> VERSION
v"1.0.5"
julia> X = UnitUpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> X * Y;
ERROR: MethodError: no method matching lmul!(::UnitUpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}, ::SparseMatrixCSC{Float64,Int64})
```

### LINKED ISSUE #35642: Multiply sparse matrix or triangular sparse matrix with sparse vector fails or is inconsistent
We observed the following behavior in `v1.4.0`/`v1.5.-DEV`. The situation is not better in older versions.
I would like to make all the products work and all return the type `SparseVector` as multiplication with a `SparseMatrixCSC` does.
```
julia> N = 50;
julia> A = (sprand(N, N, 10/N));
julia> U = UpperTriangular(A);
julia> L = LowerTriangular(A);
julia> x = sprand(N, 10/N); # SparseVector
julia> y = view(A,:,40);  # SparseColumnView
julia> z = view(x, :); # View on sparse vector

julia> for M in (A, U, L), v in (x, y, z)
           try
               println( typeof(M * v) )
           catch
               println(typeof(M), " * ", typeof(v), " failed")
           end
       end

SparseVector{Float64,Int64}
SparseVector{Float64,Int64}
SparseVector{Float64,Int64}

Array{Float64,1} 

UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseMatrixCSC{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},false} failed

UpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseVector{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}}},false} failed

Array{Float64,1}

LowerTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseMatrixCSC{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},false} failed

LowerTriangular{Float64,SparseMatrixCSC{Float64,Int64}} * SubArray{Float64,1,SparseVector{Float64,Int64},Tuple{Base.Slice{Base.OneTo{Int64}}},false} failed
```

### PR DESCRIPTION
**Pull request by KlausC**
Fixes JuliaLang/julia#35609 
Fixes JuliaLang/LinearAlgebra.jl#719 
Fixes JuliaLang/LinearAlgebra.jl#721 
Multiplying a sparse triangular matrix with a sparse matrix now is possible.
The result type is a triangular sparse matrix or a sparse matrix.
Multiplying a sparse triangular matrix with a sparse vector now yields a sparse vector.

### CODE REVIEW

**Comment by KlausC** [comment]
bump

**Comment by KlausC** [comment]
@dkarrasch , is there a chance that somebody reviews this PR?

**Comment by StefanKarpinski** [comment]
It would be great to get this reviewed. I'm afraid I'm not really qualified though.

**Review by dkarrasch — APPROVED** [review]
LGTM, very impressive work. It took me quite a while to figure out all the `nnz`, `nonzeros` etc for the different views and all that. I think it would be really helpful to explicitly test them with a hand-written sparse matrix/vector à la `sparse(I, J, V, 10, 10)` or `sparsevec(I, V)`. In case anyone comes back and reviews this code again, having such a small example would help to understand quicker what the expected outcome should be.

**Comment by KlausC** [comment]
Shall I add test cases?

**Comment by dkarrasch** [comment]
> Shall I add test cases?

That would be fantastic, yes.

**Comment by KlausC** [comment]
forgetmenot

**Pull request merged**
