### PR TITLE
support for Unicode 12

### PR DESCRIPTION
**Pull request by stevengj**
By bumping to utf8proc 2.3.

### CODE REVIEW

**Comment by stevengj** [comment]
CI has been broken for a while, so it is difficult to submit PRs — are you guys planning to delay the feature freeze?

**Comment by stevengj** [comment]
Linux Travis failure is #31605

**Review by StefanKarpinski — APPROVED** [review]

**Comment by stevengj** [comment]
@StefanKarpinski, go ahead and merge when you think it is appropriate?

**Comment by fredrikekre** [comment]
Looks like this changed `textwidth('❤')` from 2 to 1 and broke some doctests.

**Pull request merged**
