### PR TITLE
RFC: Fix #12074 and #12094

### LINKED ISSUE #12074: Inconsistent support for array operations with TimeType/Period values
Support for adding/subtracting `TimeType` and `Period` values in arrays or ranges is fairly hit-or-miss right now. The default array operator implementations + promotion seems to handle some operations but not others, and there's explicit broadcasting functionality ([here](https://github.com/JuliaLang/julia/blob/master/base/dates/arithmetic.jl#L69)) for adding/subtracting a `Period` from an `AbstractArray{TimeType}`, but it would be nice to have more general / consistent functionality.

**Some things that work:**

```julia
julia> [Date(2009,1,1), Date(2009,1,2),Date(2009,1,3)] - [Day(3), Day(5), Day(7)]
3-element Array{Base.Dates.AbstractTime,1}:
 2008-12-29
 2008-12-28
 2008-12-27
```

```julia
julia> [Day(1), Day(2), Day(3)] + [Day(1), Day(2), Day(3)]
3-element Array{Base.Dates.Day,1}:
 2 days
 4 days
 6 days
```

**Some things that don't:**

```julia
julia> (Date(2010,1,1):Month(1):Date(2011,1,1)) - (Date(2009,1,1):Month(1):Date(2010,1,1))
ERROR: MethodError: `convert` has no method matching convert(::Type{Base.Dates.Day}, ::Base.Dates.CompoundPeriod)
This may have arisen from a call to the constructor Base.Dates.Day(...),
since type constructors fall back to convert methods.
```

```julia
julia> [Day(1), Day(2), Day(3)] + [Month(1), Month(2), Month(3)]
ERROR: MethodError: `convert` has no method matching convert(::Type{Base.Dates.DatePeriod}, ::Base.Dates.CompoundPeriod)
This may have arisen from a call to the constructor Base.Dates.DatePeriod(...),
since type constructors fall back to convert methods.
```

### PR DESCRIPTION
**Pull request by GordStephen**
This resolves #12074 and #12094 by cleaning up and completing https://github.com/JuliaLang/julia/pull/12084.

Implements:
- Subtraction between TimeType arrays
- Addition/subtraction between Period/CompoundPeriod arrays
- Addtion/subtraction between TimeType and Period/CompoundPeriod arrays
- Broadcasting of scalar TimeType/Period/CompoundPeriod addition/subtraction over TimeType/Period/CompoundPeriod arrays
- Tests for all of the above

### CODE REVIEW

**Comment by tkelman** [comment]
cc @quinnj

**Comment by quinnj** [comment]
Thanks @GordStephen for digging into this and ironing out the details here. Also thanks for the good # of tests. If you're interested in taking a crack at improving the Dates parsing code, I'm sure @jiahao would appreciate it (there should be a few open issues); I'm always happen to recruit people to work on Dates stuff.

**Comment by jiahao** [comment]
Always appreciate more work on `Dates`.

Unfortunately this PR introduced a very large number of ambiguity warnings downstream. For example:

```jl
julia> using DataFrames
Warning: New definition 
    +(AbstractArray, DataArrays.DataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:326
is ambiguous with: 
    +(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:90.
To fix, define 
    +(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, DataArrays.DataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    +(AbstractArray, DataArrays.AbstractDataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    +(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:90.
To fix, define 
    +(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(Base.Range, DataArrays.DataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:326
is ambiguous with: 
    -(Base.Range{#T<:Base.Dates.TimeType}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:104.
To fix, define 
    -(Base.Range{#T<:Base.Dates.TimeType}, DataArrays.DataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.DataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:326
is ambiguous with: 
    -(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:90.
To fix, define 
    -(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, DataArrays.DataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.DataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:326
is ambiguous with: 
    -(Base.Range{#T<:Base.Dates.TimeType}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:104.
To fix, define 
    -(Base.Range{#T<:Base.Dates.TimeType}, DataArrays.DataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.DataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:326
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:105.
To fix, define 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, DataArrays.DataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(DataArrays.AbstractDataArray, Base.Range) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, Base.Range{#T<:Base.Dates.TimeType}) at dates/arithmetic.jl:103.
To fix, define 
    -(DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any}, Base.Range{#T<:Base.Dates.TimeType})
before the new definition.
Warning: New definition 
    -(Base.Range, DataArrays.AbstractDataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(Base.Range{#T<:Base.Dates.TimeType}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:104.
To fix, define 
    -(Base.Range{#T<:Base.Dates.TimeType}, DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(DataArrays.AbstractDataArray, AbstractArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, Base.Range{#T<:Base.Dates.TimeType}) at dates/arithmetic.jl:103.
To fix, define 
    -(DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any}, Base.Range{#T<:Base.Dates.TimeType})
before the new definition.
Warning: New definition 
    -(DataArrays.AbstractDataArray, AbstractArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}) at dates/arithmetic.jl:88.
To fix, define 
    -(DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any}, Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}})
before the new definition.
Warning: New definition 
    -(DataArrays.AbstractDataArray, AbstractArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:105.
To fix, define 
    -(DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.AbstractDataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:90.
To fix, define 
    -(Union{DenseArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any}, Base.SubArray{#P<:Union{Base.Dates.CompoundPeriod, Base.Dates.Period}, N<:Any, A<:DenseArray, I<:Tuple{Vararg{Union{Int64, Base.Range{Int64}, Base.Colon}}}, LD<:Any}}, DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.AbstractDataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(Base.Range{#T<:Base.Dates.TimeType}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:104.
To fix, define 
    -(Base.Range{#T<:Base.Dates.TimeType}, DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
Warning: New definition 
    -(AbstractArray, DataArrays.AbstractDataArray) at /Users/jiahao/.julia/v0.4/DataArrays/src/operators.jl:349
is ambiguous with: 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, AbstractArray{#T<:Base.Dates.TimeType, N<:Any}) at dates/arithmetic.jl:105.
To fix, define 
    -(AbstractArray{#T<:Base.Dates.TimeType, N<:Any}, DataArrays.AbstractDataArray{#T<:Base.Dates.TimeType, N<:Any})
before the new definition.
```

**Comment by GordStephen** [comment]
Yikes! Well, I guess the good news is that the errors all seem to trace back to just two method definitions (lines 326/349 in DataArrays/src/operators.jl). I'll go open an issue at DataArrays and see what I can do about it - or do you think there's something that could be done on this end to reduce the impact more generally?

**Comment by timholy** [comment]
The deprecations also affect Images.

I wonder if it's worth at least a little time seeing if we can fix this more generally. Assuming you don't want to make a `Dates.TimeType` into a subtype of `Number`, I wonder if we should introduce an `AbstractScalar` type? And then we could generalize the definitions in `arraymath.jl`, delete the time-specific methods, and then package authors only have one place they have to worry about in terms of ambiguities.

**Comment by GordStephen** [comment]
I like the sound of that - one thing to watch for would be the fact that `TimeType`/`Period`/`CompoundPeriod` operations often produce results that are typed differently than their operands, which I've found to be tricky to deal with very generally. But a general solution would definitely be preferable - right now defining date array methods is like fighting some sort of hydra - fixing one ambiguity usually creates a bunch more!

**Comment by timholy** [comment]
After working on this for a few hours, I don't think we can have a generic fix without addressing #8027. The specific place this comes up in Dates is in adding a `CompoundPeriod` to a `Period`, which involves concatenation and hence should promote two `Period`s to `Period`; however, falling back on generic `AbstractArray` operations for `A+b` leads one to wish for a promotion rule that selects `CompoundPeriod`.

Now here's my provocative question: is the current slew of ambiguity warnings in packages worth the benefit of this PR? Or should we revert it?

**Comment by GordStephen** [comment]
@timholy, thanks for all the work to try to fix the underlying issues here! Maybe the solution for now is to move the functionality into a standalone module, so the few who need it right now (maybe just me?) can have it without causing broader package issues.

**Comment by timholy** [comment]
Let's hold out for a bit more and see whether #12292 wraps up soon. Certainly it would be great to support the operations you've supported.

If the answer on #12292 is "just can't fix this now," I confess I like your solution. I hate the idea of backing out excellent work, _especially_ from a new contributor. But to me it seems like the only workable choice. Your flexibility gains a big :100: from me, and I hope to see you around more!

**Comment by GordStephen** [comment]
Ok, sounds good!

**Pull request merged**
