### PR TITLE
Update strings.md

### PR DESCRIPTION
**Pull request by mmsbrggr**

### CODE REVIEW

**Review by mgkuhn — CHANGES_REQUESTED** [review]
Even shorter:
> Thus we have `length(s) ≤ lastindex(s)`,

([Show, don't tell](https://en.wikipedia.org/wiki/Show,_don%27t_tell))

**Comment by ViralBShah** [comment]
The extra words here actually are a bit clearer, if longer.

**Comment by mmsbrggr** [comment]
@ViralBShah The issue is not the extra words but the fact that `length(s) <= lastindex(s)` is not an "identity" as written in the text but an inequality.

I am just learning Julia and noticed the mistake when reading the documentation and wanted to quickly fix it. Sorry if I am causing any inconvenience.

**Comment by StefanKarpinski** [comment]
You could change "identity" to "invariant" instead.

**Comment by mmsbrggr** [comment]
@StefanKarpinski also fine. Originally I changed it from "identity" to "inequality". @mgkuhn requested me to remove the words altogether as it's shorter.

**Comment by ViralBShah** [comment]
@mmsbrggr Definitely not causing any inconvenience. It is always great to have new contributors. @StefanKarpinski Should we merge?

**Comment by kshyatt** [comment]
Bump -- can we merge this?

**Pull request merged**
