### PR TITLE
make radical operators juxtaposable

### LINKED ISSUE #40094: 2√2 does not work
Surprised to find the following doesn't work:

```julia
julia> 2√2
ERROR: syntax: extra token "√" after end of expression
```

(while `2sqrt(2)` does).

### PR DESCRIPTION
**Pull request by bicycle1885**
This allows juxtaposition with radical operators such as `2√3`, `x√x`, `4∛-3`, and so on. I believe radical operators are never used as an infix binary operator so it will be safe to allow this syntax unlike other prefix unary operators (e.g., `+`, `-`, etc.).

Closes #40094.

### CODE REVIEW

**Review by JeffBezanson — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Just need to remove the explicit test for this not working, then LGTM :)

**Comment by bicycle1885** [comment]
Thank you. Fixed.

**Comment by JeffBezanson** [comment]
Oh, I guess this could use a NEWS item.

**Comment by bicycle1885** [comment]
Ready? Ready?

**Pull request merged**
