### PR TITLE
Implement `x in Type`

### PR DESCRIPTION
**Pull request by eschnett**
See https://github.com/JuliaLang/julia/issues/55150.

### CODE REVIEW

**Comment by mikmoore** [comment]
The method defined in this PR is applied excessively compared to what it is actually "correct" for. The issue seems to suggest that `in(0.5, Float64)` should be `true`, but it will not be by the proposed implementation.

It would seem that an implementation like
```julia
in(x, ::Type{T}) where T
  return try
    convert(T, x) == x
  catch _
    false
  end
end
```
is closer to the desired semantic, although I would say this is a bad implementation also (the `try/catch` is a nonstarter, I would say).

**Comment by jakobnissen** [comment]
I disagree with the semantics here: That is simply not what `in` means. If `5 in Int` should be true, then that would imply `Int` is some iterable container.
Here is the docstring of `in` - it is plainly a different, incompatible meaning with the sense that `in` is being used here:
```
in(item, collection) -> Bool
  ∈(item, collection) -> Bool

  Determine whether an item is in the given collection, in the sense that it is == to one of the
  values generated by iterating over the collection.
```

**Comment by DilumAluthge** [comment]
I agree that we shouldn't use the name `in` for this.

**Comment by mbauman** [comment]
Let's refocus the discussion in #55150 to figure out what this might look like.

**Pull request closed without merging**
