### PR TITLE
Escape jl_atexit_hook first _

### PR DESCRIPTION
**Pull request by blegat**
The two underscores [are treated as italic markup](https://docs.julialang.org/en/v1/devdocs/init/#jl*atexit*hook()-1) and escaping one avoids this issue.

### CODE REVIEW

**Comment by KristofferC** [comment]
Perhaps 

```
`jl_atexit_hook()`
```

`

**Comment by blegat** [comment]
You mean changing that for every title that is the name of a function or only for this one ?

**Comment by fredrikekre** [comment]
> You mean changing that for every title that is the name of a function or only for this one ?

Everyone IMO.

**Review by fredrikekre — APPROVED** [review]
Thanks!

**Pull request merged**
