### PR TITLE
remove the use of String's len field (introduced in #22133)

### PR DESCRIPTION
**Pull request by rfourquet**
The `len` field has been removed in 2b47865a7e9b84345b9fbdeb687e4e097701153c.
I assume here that `jl_alloc_string` (called by `_string_n`) reserves one char more for `\0` that some library will insert, as far as I can understand its code (it seems `len+1` bytes are allocated, where `len` is the requested size, the last byte being zeroed).

### CODE REVIEW

**Review by yuyichao — DISMISSED** [review]
Strings shouldn't be mutated like this. Use `StringVector` instead.

**Comment by timholy** [comment]
I went ahead and canceled a bunch of CI runs on AppVeyor and Travis, since nothing will pass until this gets through.

**Comment by JeffBezanson** [comment]
This must mean there are no tests for this function? Could you add some?

**Comment by JeffBezanson** [comment]
I see, I guess there are tests. I didn't realize this code changed so recently.

**Comment by rfourquet** [comment]
> Strings shouldn't be mutated like this.

 I thougth this was the purpose of `_string_n` (it's used like this in "serialize.jl" and "strings/string.jl", as far as I can tell...)

**Comment by rfourquet** [comment]
replaced `_string_n` by `StringVector`

**Comment by timholy** [comment]
@rfourquet, thanks for taking the lead on this. These kinds of "distributed errors" aren't anyone's fault and are unavoidable when changes are happening at a rate that exceeds individual-human bandwidth. Having someone who takes ownership and deals with it so quickly is simply priceless.

**Pull request merged**
