### PR TITLE
access Cmd elements as an array of strings

### PR DESCRIPTION
**Pull request by stevengj**
Currently, a `Cmd` is a rather opaque object: there is no way to "look inside" it without accessing undocumented fields of the `Cmd` object.  I ran into this recently when I wanted a function of a `Cmd` to do something different depending on the program being executed.

As a first step, this PR allows you to iterate and index a `Cmd` object as if it were an array of strings, e.g.:
```jl
julia> collect(`echo "foo bar"`)
2-element Array{String,1}:
 "echo"   
 "foo bar"

julia> `echo "foo bar"`[2]
"foo bar"
```
(This is just a thin wrapper around `cmd.exec`.)

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
LGTM. I've considered doing this a number of times.

**Comment by tkelman** [comment]
Useful, but we are in feature freeze.

**Comment by StefanKarpinski** [comment]
Sure. We should probably branch after beta so that we can start merging features. The 1.0 release cycle will be very short already.

**Comment by tkelman** [comment]
Depends at what point waiting to merge features becomes more trouble than backporting all bugfixes. We have enough bugfixes continuing that I don't think we're there yet.

**Comment by StefanKarpinski** [comment]
We can also make bug fixes on the release branch and merged them forward to master.

**Comment by stevengj** [comment]
Now that there is a release-0.6 branch, can this be merged into master?

**Comment by stevengj** [comment]
merge?

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
