### PR TITLE
Add tests for logs of subnormals

### PR DESCRIPTION
**Pull request by kshyatt**
These branches for `log` weren't tested. Checked the results against WA.

### CODE REVIEW

**Comment by kshyatt** [comment]
Test failure is a timeout

**Comment by oscardssmith** [comment]
This is a good test in theory, but I have a few issues with it in practice. The first is that the default `rtol` for  `≈` is `sqrt(eps(T))` which is much bigger than the `2eps(T)` we probably want for scalar functions. The second issue is that since this only tests a single value, it is reasonably likely that a mostly good `log` implementation will get this value correct by chance. A more thorough test would be to take 1000 equally spaced subnormals, and perform a test like `isapprox(T(log(widen(x))), log(x), rtol=2*eps(x) `

**Comment by kshyatt** [comment]
That's a good point, I'll add a more thorough test of various values and tighten the bounds

**Comment by oscardssmith** [comment]
Also while I'm making suggestions, any chance you could add `log2` and `log10` tests here? It will be nice (especially since https://github.com/JuliaLang/julia/pull/39556 will hopefully be changing the implementation of `log2` and `log10`)

**Comment by kshyatt** [comment]
Alright, done! Look good to you, @oscardssmith ?

**Review by oscardssmith — APPROVED** [review]
Approved assuming tests pass.

**Pull request merged**
