### PR TITLE
Protect shared JIT variables from being modified unsafely

### PR DESCRIPTION
**Pull request by pchintalapudi**
~~Depends on #44912~~ Depends on #45016 to fix the macos segfaults

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by vtjnash** [comment]
seems related?
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
  |  
  | signal (6): Abort trap: 6
  | in expression starting at none:0
  |  
  | signal (11): Segmentation fault: 11
  | in expression starting at none:0
  | threads                                   (1) \|         failed at 2022-04-12T03:35:31.109
 
```

**Comment by pchintalapudi** [comment]
The pthread documentation suggests that this is caused by attempting to operate on an uninitialized mutex, which could probably happen during setup or teardown (I think the mutex should be initialized once the constructor of EE finishes). Is adding an initialized boolean flag that we assert on every operation too expensive to detect such errors?

**Comment by vtjnash** [comment]
I don't think you can solve race conditions by adding more data races. Oft times, I simply try to leak the memory to avoid cleanup problems, if that is the issue here.

**Comment by pchintalapudi** [comment]
@vtjnash Looks like the macos mutex errors are fixed, does this look good to merge as-is?

**Pull request merged**
