### PR TITLE
Make shell mode sticky

### PR DESCRIPTION
**Pull request by MasonProtter**
Currently, the shell mode is not sticky and returns to the regular repl mode each time a command is entered. In my experience, this is rarely the behaviour I want. 

I realize this probably would have been much better to do during 0.7 but I figured I should at least *propose* the change, especially since this is technically a breaking change in the standard library, not Base.

### CODE REVIEW

**Comment by chriscoey** [comment]
This would be nice. Pkg mode is sticky (and backspace on empty line returns to regular repl) so shell mode intuitively should be similar.

**Comment by StefanKarpinski** [comment]
I'd prefer this as well but people have some strong feelings about this.

**Comment by MasonProtter** [comment]
I'd definitely like to hear the arguments both ways.

**Comment by MasonProtter** [comment]
For posterity: It was mentioned on Slack that perhaps an option that may serve as a better compromise is to have `;` enter the standard, non-sticky shell mode and have `;;` as to command to enter its sticky cousin.

**Comment by bicycle1885** [comment]
This will supersedes my obsolete pull request (#19340).

**Comment by MasonProtter** [comment]
It looks like with the current infrastructure, changing shell mode to sticky requires the stdlib to be rebuilt to have any effect, so perhaps options such as the stickyness of repl modes could be supplied as options in `Make.user`?

**Comment by kescobo** [comment]
> I'd prefer this as well but people have some strong feelings about this.

Which people are those? Doesn't seem like anyone commenting here has objections - would it be worth flagging some people that do (or have)? Found what seems like a relevant discussion from @bicycle1885 's link: #6320

**Comment by matbesancon** [comment]
I would prefer to have sticky as default, but `;;` allows this without breaking any code

**Comment by MasonProtter** [comment]
Making it sticky wouldn't break anyone's code, only their workflow since this is a repl change.

**Comment by musm** [comment]
Fixed in #38646

**Pull request closed without merging**
