### PR TITLE
Element wise operators for Tuples

### PR DESCRIPTION
**Pull request by iagobaapellaniz**
Since map is a good function for tuples, I think that element wise operators should be included on future releases. 

PS, It is my first commit ever to any repository.

### CODE REVIEW

**Comment by hayd** [comment]
> It is my first commit ever to any repository.

Good work! It gets much easier after the first one.

That said, I'm not sure about this change:
```
julia> (1, [2, 3], 4) .+ 3
(4,[5,6],7)
```
Seems a bit weird/surprising to me. I'm not sure these operations make sense (but perhaps others have another opinion). See also #8450 maybe.

Should the reverse be defined? i.e. 3 .+ (1, 2).

Or should this only on number tuples:

    .+(t::Tuple{Vararg{Number}}, p::Number) = map(.+,t,tuple(fill(p,1,length(t))...))

I'm not sure this always makes sense either though.

---

Aside: It's always a good idea is to add tests for any new feature or bug fix you put forward - in fact a PR most likely won't get in without them! That way it won't be removed/regress in the future, as that'd get caught by the test suite. (I'll append something to that effect in https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md.)

**Comment by iagoba** [comment]
Hey! Thank you for the comments. I'll take a look how to add tests. And yes, probably it make sense to restrict this behaviour to number tuples.

> My personal issue was with kron(A, B) tensor products. I'm a physicist and when I've a single matrix describing a system It's just fine. On the other hand when I have several systems I need to do kron(A,B), and some times the size of b is correlated to de size of A.

So those new methods I use them for tensor product spaces, kron(A,B)

```B = fill(<whatever>, size(A).^4)```

Just to mention that here the size of B is correlated with the size of A. The old way to do that could be

```B = fill(<whatever>, [size(A)...].^4...)```

That way I have 4 times bigger system in B than A.

**Comment by hayd** [comment]
I think this change will be controversial and I *suspect* it's come up before (but can't find an issue)... If no-one else comments here please post a message on [julia-dev](https://groups.google.com/forum/#!forum/julia-dev).

**Comment by hayd** [comment]
@i-apellaniz Did you post a julia-dev issue? (I couldn't find it.) Was the consensus no?

**Comment by i-apellaniz** [comment]
I didn't post it. And now I think on how tuples work, my point of view is that we shouldn't have any method to apply element wise. 

In my particular approach I would prefer to have the outcome of `size(::AbstractArray)` as a vector from the beginning.

Anyway I'll post it soon and see what's the discussion.

**Pull request closed without merging**
