### PR TITLE
[release-0.5] front-end improvements [performance]

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by tkelman** [comment]
I should note that several dozen packages started failing on pkgeval in the last few days due to what look like inference regressions. Nobody merge this until those failures have been bisected.

**Comment by vtjnash** [comment]
Good call. Do you have a link to the log and sha1?

**Comment by tkelman** [comment]
on planes all day today, but see the 0.6 results on https://pkg.julialang.org/pulse.html

**Comment by vtjnash** [comment]
those should be fixed by adding #19509 here. but will wait for tonight's pkgeval run to confirm that covered all of them.

**Comment by tkelman** [comment]
That's unlikely to make it into tonight's run, the buildbots have to finish building binaries and it can take longer than half an hour to do that.

**Comment by tkelman** [comment]
needs a non-trivial rebase against tk/backports-0.5.2

**Pull request closed without merging**
