### PR TITLE
Make LU factorization work for more types

### PR DESCRIPTION
**Pull request by blegat**
When determining the element type need, `lufact` does the following
https://github.com/JuliaLang/julia/blob/1a870b466d83068fad9f280cc1f8e65a108cb6bc/stdlib/LinearAlgebra/src/lu.jl#L180
However LU factorization also multiplies elements of type `T` together and sum them together.
If the type `T` is not invariant under multiplication and/or addition, `lufact` does work, see https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/69.
Note the strong similary between this PR and https://github.com/JuliaLang/julia/pull/18218 which did a similar change but to matrix multiplication.

### CODE REVIEW

**Review by andreasnoack — APPROVED** [review]
👍 Minor detail but maybe we should call it something like `rationalop` since it would probably be the right operation for all triangular-triangular factorizations.

**Comment by fredrikekre** [comment]
Better as something like
```julia
lutype(T) = (zero(T)*zero(T) + zero(T)*zero(T)) / (one(T)*one(T) + one(T)*one(T))
```
or is it OK to rely on `promote_op`?

**Comment by blegat** [comment]
> we should call it something like `rationalop` since it would probably be the right operation for all triangular-triangular factorizations

Agreed, I have renamed it

> is it OK to rely on `promote_op` ?

I have assumed that it was ok since matrix product relies on it

https://github.com/JuliaLang/julia/blob/4ed46378d43f36302ed664a9975df71abb171dec/stdlib/LinearAlgebra/src/matmul.jl#L123-L124

but you think otherwise, I can change, let me know :)

**Comment by martinholters** [comment]
User of `promote_op` should be avoided if possible. Ceterum censeo `promote_op` esse delendam.

**Comment by andreasnoack** [comment]
> User of `promote_op` should be avoided if possible.

The price of using instances through `zero(T)` and `one(T)` here is that it might fail for types where these don't exist. That was the issue for matrix multiplication so it could also happen here although it probably is less likely.

@blegat After thinking a little more about this, I think we might be able to compute the type in an even better way here. This was discussed in https://github.com/JuliaLang/julia/issues/7623 and actually, the issue isn't completely fixed. The problem is that `L` is unitless while `U` has units but they'd have to be stored in the same array. I think something like
```julia
UT = typeof(zero(T) - oneunit(T)/oneunit(T)*oneunit(T))
LT = typeof(oneunit(T)/oneunit(T))
S = promote_type(T, UT, LT)
```
should be correct. In most cases it should just collapse to a single type and for unitful elements, it should provide the right union.

**Comment by blegat** [comment]
@andreasnoack I have updated the PR based on your idea. The code now also works for quantities with units (tested with Unitful)

**Pull request merged**
