### PR TITLE
Backports for julia 1.9.0-beta3

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #47763 
- [x] #47946 
- [x] #47986 
- [x] #48033 
- [x] #48027 
- [x] #48036 
- [x] #48064 
- [x] #48120 
- [x] #48054 
- [x] #48131 
- [x] #48134 
- [x] #47973 
- [x] #48102 
- [x] #48168 
- [x] #48185 
- [x] #48152 
- [x] #48137 
- [x] #48241 
- [x] #48254 
- [x] #48247 
- [x] #48248 
- [x] #48160 
- [x] #48038 
- [x] #48268 
- [x] #48179 
- [x] #48246 
- [x] #48029 
- [x] #48135 
- [x] #48158 
- [x] #47778 
- [x] #47675 

Non-merged PRs with backport label:
- [ ] #48291 
- [ ] #48279 
- [ ] #48278 
- [ ] #48215 
- [ ] #48183 
- [ ] #48051 
- [ ] #48050 
- [ ] #47676 
- [ ] #47636 
- [ ] #47615

### CODE REVIEW

**Comment by vchuravy** [comment]
?beta3

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/commit/7daffeecb8cff8e09065bf69271ff27ce9221da3#commitcomment-94761138 seems to have a more failures than the last run so let's run against the last run with the packages that failed.

@nanosoldier `runtests(["Observables", "MethodAnalysis", "KeywordSearch", "PowerSpectra", "ChainedFixes", "QuasiArrays", "BiodiversityObservationNetworks", "Tapestree", "Web3", "PowerModels", "SortingAlgorithms", "JumpProcesses", "CameraModels", "SortingLab", "DataConvenience", "ECharts", "FlexiGroups", "LinearMapsAA", "OnlineStatsBase", "LuaCall", "StaticMPI", "RandomVariables", "Cthulhu", "StaticTools", "StaticCompiler", "Hashpipe", "DynamicBoundsBase", "Agents", "AlgebraOfGraphics", "JWAS", "LongDatasetSort", "AtomicStructure", "ParetoSmooth", "CodeInfoTools", "CartesianJoin", "PBWDeformations", "HarmonicOrthogonalPolynomials", "MadNLPKrylov", "SpectralDistances", "SlidingDistancesBase", "Wasmtime", "FlashWeave", "EquivalentCircuits", "DifferentiableFactorizations", "QuantumStateDistributions", "ConstraintProgrammingExtensions", "Kahuna", "ReinforcementLearningCore", "QML", "PlasmaEquilibriumToolkit", "Symbolics", "FiniteStateProjection", "Distributions", "SeaPearl", "NaiveGAflux", "PosteriorPlots", "QuickPOMDPs", "ComponentArrays", "Faust", "KeyedDistributions", "RadialBasisFunctionModels", "DiscreteMarkovChains", "PuiseuxPolynomials", "Pluto", "RRRMC", "LiterateTest", "Kriging", "Pathogen", "Pidfile", "TightBindingApproximation", "MadNLP", "ClassicalOrthogonalPolynomials", "LazySets", "MadNLPPardiso", "HOHQMesh", "NonlinearEigenproblems", "PDMats", "AeroMDAO", "AKNS", "DynamicNLPModels", "XXhash", "Yota", "StochasticAD", "ConcurrentCollections", "ControlSystemIdentification", "FractionalDiffEq", "ModelWrappers", "LatinHypercubeSampling", "SubSIt", "JuliaVariables", "Grader", "LessUnitful", "ComoniconGUI", "PDSampler", "BenchPerfConfigSweeps", "Dagger", "LaurentPolynomials", "Libtask", "ParameterTests", "GAP", "Recommenders", "LogDensityProblemsAD", "ReactiveDynamics", "SpinGlassEngine", "LCIO", "SparseExtra", "MatrixPolynomials", "ParallelStencil", "P4est", "Terminators", "ReportMetrics", "LassoPlot", "PlutoHooks", "KernelGradients", "TensorToolbox", "EquilibriumMeasures", "Optimization", "GraphMatFun", "ContinuumArrays", "Diagonalizations", "DiscreteDifferentialGeometry", "FastJet", "AbstractPPL", "IndirectTrajOpt", "DiscreteChoiceModels", "PDFIO", "Trixi2Vtk", "KroneckerProducts", "PDMatsExtras", "WiltonInts84", "Profile", "DLMReader", "Try", "SeisNoise", "FileWatching", "ForneyLab", "CurricularAnalytics", "RandomizedPreconditioners", "GFlops", "Gadfly", "JuliennedArrays", "PeriodicSchurDecompositions", "NeuralAttentionlib", "ManifoldsBase", "DataKnots", "ControlSystems", "PartitionedArrays", "AtlasRobot", "Cassette", "MultivariateOrthogonalPolynomials", "CompactBases", "Deductive", "Avalon", "QuantumCumulants", "TimeseriesPrediction", "Jute", "ConcurrentUtils", "ITensorGaussianMPS", "WaspNet", "SemiclassicalOrthogonalPolynomials", "SpinDoctor", "Tracker", "GeoDataFrames", "DataStructures", "SingularIntegralEquations", "PDELib", "FastaLoader", "OscillatoryIntegrals", "BlockBandedMatrices", "CompilerPluginTools", "RectiGrids", "ReachabilityAnalysis", "DisjointCliqueCover", "MPSKit", "FullNetworkSystems", "PDENLPModels", "SBMLToolkit", "FilesystemDatastructures", "MPIMapReduce", "MeasureBase", "PlutoVista", "LocalPackageServer", "DiffEqBase", "ApproximateGPs", "CBOOCall", "FastVision", "JSBSim", "BifurcationInference", "AlgorithmicRecourseDynamics", "Jolab", "SBML", "FSimZoo", "ClimaAtmos", "LazyInverses", "SyncBarriers", "AIControl", "ContinuousTimePolicyGradients", "MeshViz", "AdvancedHMC", "PhasedArray", "VoronoiFVMDiffEq", "MadNLPMumps", "StatisticalGraphics", "PolynomialRoots", "BenchmarkConfigSweeps", "DiffEqOperators", "EnsembleKalmanProcesses", "PhyloCoalSimulations", "Kwonly", "ControlSystemsBase", "FluxArchitectures", "BaytesDiff", "JLLPrefixes", "CoulombIntegrals", "Alicorn", "ExprTools", "Documenter", "FastGroupBy", "jlpkg", "RecursiveArrayTools", "PrettyPrinting", "Probably", "Anasol", "GradientRobustMultiPhysics", "ONNX", "MatchCore", "GPUCompiler", "PreludeDicts", "ProbNumDiffEq", "UpdateJulia", "Laplacians", "EndpointRanges", "NPCFs", "InMemoryDatasets", "NonconvexMetaheuristics", "Gtk4", "FundamentalsNumericalComputation", "AxisSets", "Bijectors", "PlugFlowReactor", "QuantumStateBase", "TestFunctionRunner", "ArrayInterface", "NamedDims", "Replay", "Fenrir", "OptimKit", "Healpix", "DocumentFunction", "Umlaut", "SciMLBenchmarks", "Bennu", "SnoopPrecompile", "Scheduling", "AxisKeys", "PowerSystemsUnits", "Enzyme", "GenericArpack", "LazyArrays", "Revise", "CrystalNets", "NTNk", "PackageCompiler"], vs = "@258fa32495354eb532170b171f5898b660e9be67")`

**Comment by maleadt** [comment]
Restarting after a PkgEval hotfix:

@nanosoldier `runtests(["Observables", "MethodAnalysis", "KeywordSearch", "PowerSpectra", "ChainedFixes", "QuasiArrays", "BiodiversityObservationNetworks", "Tapestree", "Web3", "PowerModels", "SortingAlgorithms", "JumpProcesses", "CameraModels", "SortingLab", "DataConvenience", "ECharts", "FlexiGroups", "LinearMapsAA", "OnlineStatsBase", "LuaCall", "StaticMPI", "RandomVariables", "Cthulhu", "StaticTools", "StaticCompiler", "Hashpipe", "DynamicBoundsBase", "Agents", "AlgebraOfGraphics", "JWAS", "LongDatasetSort", "AtomicStructure", "ParetoSmooth", "CodeInfoTools", "CartesianJoin", "PBWDeformations", "HarmonicOrthogonalPolynomials", "MadNLPKrylov", "SpectralDistances", "SlidingDistancesBase", "Wasmtime", "FlashWeave", "EquivalentCircuits", "DifferentiableFactorizations", "QuantumStateDistributions", "ConstraintProgrammingExtensions", "Kahuna", "ReinforcementLearningCore", "QML", "PlasmaEquilibriumToolkit", "Symbolics", "FiniteStateProjection", "Distributions", "SeaPearl", "NaiveGAflux", "PosteriorPlots", "QuickPOMDPs", "ComponentArrays", "Faust", "KeyedDistributions", "RadialBasisFunctionModels", "DiscreteMarkovChains", "PuiseuxPolynomials", "Pluto", "RRRMC", "LiterateTest", "Kriging", "Pathogen", "Pidfile", "TightBindingApproximation", "MadNLP", "ClassicalOrthogonalPolynomials", "LazySets", "MadNLPPardiso", "HOHQMesh", "NonlinearEigenproblems", "PDMats", "AeroMDAO", "AKNS", "DynamicNLPModels", "XXhash", "Yota", "StochasticAD", "ConcurrentCollections", "ControlSystemIdentification", "FractionalDiffEq", "ModelWrappers", "LatinHypercubeSampling", "SubSIt", "JuliaVariables", "Grader", "LessUnitful", "ComoniconGUI", "PDSampler", "BenchPerfConfigSweeps", "Dagger", "LaurentPolynomials", "Libtask", "ParameterTests", "GAP", "Recommenders", "LogDensityProblemsAD", "ReactiveDynamics", "SpinGlassEngine", "LCIO", "SparseExtra", "MatrixPolynomials", "ParallelStencil", "P4est", "Terminators", "ReportMetrics", "LassoPlot", "PlutoHooks", "KernelGradients", "TensorToolbox", "EquilibriumMeasures", "Optimization", "GraphMatFun", "ContinuumArrays", "Diagonalizations", "DiscreteDifferentialGeometry", "FastJet", "AbstractPPL", "IndirectTrajOpt", "DiscreteChoiceModels", "PDFIO", "Trixi2Vtk", "KroneckerProducts", "PDMatsExtras", "WiltonInts84", "Profile", "DLMReader", "Try", "SeisNoise", "FileWatching", "ForneyLab", "CurricularAnalytics", "RandomizedPreconditioners", "GFlops", "Gadfly", "JuliennedArrays", "PeriodicSchurDecompositions", "NeuralAttentionlib", "ManifoldsBase", "DataKnots", "ControlSystems", "PartitionedArrays", "AtlasRobot", "Cassette", "MultivariateOrthogonalPolynomials", "CompactBases", "Deductive", "Avalon", "QuantumCumulants", "TimeseriesPrediction", "Jute", "ConcurrentUtils", "ITensorGaussianMPS", "WaspNet", "SemiclassicalOrthogonalPolynomials", "SpinDoctor", "Tracker", "GeoDataFrames", "DataStructures", "SingularIntegralEquations", "PDELib", "FastaLoader", "OscillatoryIntegrals", "BlockBandedMatrices", "CompilerPluginTools", "RectiGrids", "ReachabilityAnalysis", "DisjointCliqueCover", "MPSKit", "FullNetworkSystems", "PDENLPModels", "SBMLToolkit", "FilesystemDatastructures", "MPIMapReduce", "MeasureBase", "PlutoVista", "LocalPackageServer", "DiffEqBase", "ApproximateGPs", "CBOOCall", "FastVision", "JSBSim", "BifurcationInference", "AlgorithmicRecourseDynamics", "Jolab", "SBML", "FSimZoo", "ClimaAtmos", "LazyInverses", "SyncBarriers", "AIControl", "ContinuousTimePolicyGradients", "MeshViz", "AdvancedHMC", "PhasedArray", "VoronoiFVMDiffEq", "MadNLPMumps", "StatisticalGraphics", "PolynomialRoots", "BenchmarkConfigSweeps", "DiffEqOperators", "EnsembleKalmanProcesses", "PhyloCoalSimulations", "Kwonly", "ControlSystemsBase", "FluxArchitectures", "BaytesDiff", "JLLPrefixes", "CoulombIntegrals", "Alicorn", "ExprTools", "Documenter", "FastGroupBy", "jlpkg", "RecursiveArrayTools", "PrettyPrinting", "Probably", "Anasol", "GradientRobustMultiPhysics", "ONNX", "MatchCore", "GPUCompiler", "PreludeDicts", "ProbNumDiffEq", "UpdateJulia", "Laplacians", "EndpointRanges", "NPCFs", "InMemoryDatasets", "NonconvexMetaheuristics", "Gtk4", "FundamentalsNumericalComputation", "AxisSets", "Bijectors", "PlugFlowReactor", "QuantumStateBase", "TestFunctionRunner", "ArrayInterface", "NamedDims", "Replay", "Fenrir", "OptimKit", "Healpix", "DocumentFunction", "Umlaut", "SciMLBenchmarks", "Bennu", "SnoopPrecompile", "Scheduling", "AxisKeys", "PowerSystemsUnits", "Enzyme", "GenericArpack", "LazyArrays", "Revise", "CrystalNets", "NTNk", "PackageCompiler"], vs = "@258fa32495354eb532170b171f5898b660e9be67")`

**Comment by maleadt** [comment]
Restarting after a PkgEval hotfix:

@nanosoldier `runtests(["Observables", "MethodAnalysis", "KeywordSearch", "PowerSpectra", "ChainedFixes", "QuasiArrays", "BiodiversityObservationNetworks", "Tapestree", "Web3", "PowerModels", "SortingAlgorithms", "JumpProcesses", "CameraModels", "SortingLab", "DataConvenience", "ECharts", "FlexiGroups", "LinearMapsAA", "OnlineStatsBase", "LuaCall", "StaticMPI", "RandomVariables", "Cthulhu", "StaticTools", "StaticCompiler", "Hashpipe", "DynamicBoundsBase", "Agents", "AlgebraOfGraphics", "JWAS", "LongDatasetSort", "AtomicStructure", "ParetoSmooth", "CodeInfoTools", "CartesianJoin", "PBWDeformations", "HarmonicOrthogonalPolynomials", "MadNLPKrylov", "SpectralDistances", "SlidingDistancesBase", "Wasmtime", "FlashWeave", "EquivalentCircuits", "DifferentiableFactorizations", "QuantumStateDistributions", "ConstraintProgrammingExtensions", "Kahuna", "ReinforcementLearningCore", "QML", "PlasmaEquilibriumToolkit", "Symbolics", "FiniteStateProjection", "Distributions", "SeaPearl", "NaiveGAflux", "PosteriorPlots", "QuickPOMDPs", "ComponentArrays", "Faust", "KeyedDistributions", "RadialBasisFunctionModels", "DiscreteMarkovChains", "PuiseuxPolynomials", "Pluto", "RRRMC", "LiterateTest", "Kriging", "Pathogen", "Pidfile", "TightBindingApproximation", "MadNLP", "ClassicalOrthogonalPolynomials", "LazySets", "MadNLPPardiso", "HOHQMesh", "NonlinearEigenproblems", "PDMats", "AeroMDAO", "AKNS", "DynamicNLPModels", "XXhash", "Yota", "StochasticAD", "ConcurrentCollections", "ControlSystemIdentification", "FractionalDiffEq", "ModelWrappers", "LatinHypercubeSampling", "SubSIt", "JuliaVariables", "Grader", "LessUnitful", "ComoniconGUI", "PDSampler", "BenchPerfConfigSweeps", "Dagger", "LaurentPolynomials", "Libtask", "ParameterTests", "GAP", "Recommenders", "LogDensityProblemsAD", "ReactiveDynamics", "SpinGlassEngine", "LCIO", "SparseExtra", "MatrixPolynomials", "ParallelStencil", "P4est", "Terminators", "ReportMetrics", "LassoPlot", "PlutoHooks", "KernelGradients", "TensorToolbox", "EquilibriumMeasures", "Optimization", "GraphMatFun", "ContinuumArrays", "Diagonalizations", "DiscreteDifferentialGeometry", "FastJet", "AbstractPPL", "IndirectTrajOpt", "DiscreteChoiceModels", "PDFIO", "Trixi2Vtk", "KroneckerProducts", "PDMatsExtras", "WiltonInts84", "Profile", "DLMReader", "Try", "SeisNoise", "FileWatching", "ForneyLab", "CurricularAnalytics", "RandomizedPreconditioners", "GFlops", "Gadfly", "JuliennedArrays", "PeriodicSchurDecompositions", "NeuralAttentionlib", "ManifoldsBase", "DataKnots", "ControlSystems", "PartitionedArrays", "AtlasRobot", "Cassette", "MultivariateOrthogonalPolynomials", "CompactBases", "Deductive", "Avalon", "QuantumCumulants", "TimeseriesPrediction", "Jute", "ConcurrentUtils", "ITensorGaussianMPS", "WaspNet", "SemiclassicalOrthogonalPolynomials", "SpinDoctor", "Tracker", "GeoDataFrames", "DataStructures", "SingularIntegralEquations", "PDELib", "FastaLoader", "OscillatoryIntegrals", "BlockBandedMatrices", "CompilerPluginTools", "RectiGrids", "ReachabilityAnalysis", "DisjointCliqueCover", "MPSKit", "FullNetworkSystems", "PDENLPModels", "SBMLToolkit", "FilesystemDatastructures", "MPIMapReduce", "MeasureBase", "PlutoVista", "LocalPackageServer", "DiffEqBase", "ApproximateGPs", "CBOOCall", "FastVision", "JSBSim", "BifurcationInference", "AlgorithmicRecourseDynamics", "Jolab", "SBML", "FSimZoo", "ClimaAtmos", "LazyInverses", "SyncBarriers", "AIControl", "ContinuousTimePolicyGradients", "MeshViz", "AdvancedHMC", "PhasedArray", "VoronoiFVMDiffEq", "MadNLPMumps", "StatisticalGraphics", "PolynomialRoots", "BenchmarkConfigSweeps", "DiffEqOperators", "EnsembleKalmanProcesses", "PhyloCoalSimulations", "Kwonly", "ControlSystemsBase", "FluxArchitectures", "BaytesDiff", "JLLPrefixes", "CoulombIntegrals", "Alicorn", "ExprTools", "Documenter", "FastGroupBy", "jlpkg", "RecursiveArrayTools", "PrettyPrinting", "Probably", "Anasol", "GradientRobustMultiPhysics", "ONNX", "MatchCore", "GPUCompiler", "PreludeDicts", "ProbNumDiffEq", "UpdateJulia", "Laplacians", "EndpointRanges", "NPCFs", "InMemoryDatasets", "NonconvexMetaheuristics", "Gtk4", "FundamentalsNumericalComputation", "AxisSets", "Bijectors", "PlugFlowReactor", "QuantumStateBase", "TestFunctionRunner", "ArrayInterface", "NamedDims", "Replay", "Fenrir", "OptimKit", "Healpix", "DocumentFunction", "Umlaut", "SciMLBenchmarks", "Bennu", "SnoopPrecompile", "Scheduling", "AxisKeys", "PowerSystemsUnits", "Enzyme", "GenericArpack", "LazyArrays", "Revise", "CrystalNets", "NTNk", "PackageCompiler"], vs = "@258fa32495354eb532170b171f5898b660e9be67")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/48075#issuecomment-1368792669) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/05c8182_vs_258fa32/report.html).

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("sort", vs=":release-1.8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/48075#issuecomment-1369831630) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/3fde757_vs_00177eb/report.md).

**Comment by maleadt** [comment]
Pushed some more fixes; if we're doing a backport we could as well make it better. This also fixed 1.9 compatibility.

**Pull request merged**
