### PR TITLE
[WIP] Add jl_start_tracking_dispatches / jl_finish_tracking_dispatches

### PR DESCRIPTION
**Pull request by NHDaly**
Allow users to track all _dynamic dispatches_ that occur when tracking is enabled.

This can be useful for debugging, such as to understand where your code has type-instabilities that lead to a dispatch.

It will also be used by StagedFunctions.jl (and ideally base Generated functions) to cheaply record the set of MethodInstances that need to have backedges set to the generated function. Merging this into https://github.com/JuliaLang/julia/pull/32774 should be enough to fix all the tests! :)

There is an example of this working, in the StagedFunctions package, here:
https://github.com/NHDaly/StagedFunctions.jl/pull/9

### CODE REVIEW

**Comment by Keno** [comment]
I'm a little worried about adding extra instructions in a path that's this hot, even with the unlikely annotation. If it's just for debugging I would have suggested a patch point, but sounds like you're imagining a case where generated functions would turn this on automatically?

**Comment by NHDaly** [comment]
For completeness, I was trying to measure how much of an impact this would have, but I haven't found a benchmark that actually spends a lot of cpu in `jl_invoke`. I thought something like this might, but it looks like it's only spending `2.5%` of time in `jl_invoke` according to the Profile:

```julia
r(n) = n == 0 ? 0 : Core._apply(r, n-1)

using PProf, Profile

@profile r(1) # warmup r() and profile

Profile.clear()
@profile for _ in 1:1000; r(1000); end

pprof(from_c=true)
```

This is showing 2.3% cpu actually in the invoke frame (_after_ this change):
Screen Shot 2019-11-06 at 5 06 23 PM

Can you recommend a better micro-benchmark that would make invoke hotter?

And/or, is there a different spot i could put this check that would catch "all dynamic dispatches"?

**Comment by NHDaly** [comment]
(I bumped it up to more like 3% - 5% when i added more methods to r, to avoid it somehow inlining and avoiding the dispatch.)

**Comment by vtjnash** [comment]
Usually just something like `Base.inferencebarrier(==)(1, 1)`

On my machine, this takes about 11.4 nanoseconds, which is probably about 36 cycles or 650 flops (2.7GHz base frequency, `BLAS.set_num_threads(1); time * peakflops()`)

**Comment by vtjnash** [comment]
replaced by --trace-dispatch

**Pull request closed without merging**
