### PR TITLE
Compiler.jl: use `Base.[all|any]` instead of `Compiler`'s own versions

### PR DESCRIPTION
**Pull request by aviatesk**
The current `Compiler` defines its own versions of `all` and `any`, which are separate generic functions from `Base.[all|any]`: https://github.com/JuliaLang/julia/blob/2ed1a411e0a080f3107e75bb65105a15a0533a90/Compiler/src/utilities.jl#L15-L32

On the other hand, at the point where `Base.Compiler` is bootstrapped, only a subset of `Base.[all|any]` are defined, specifically those related to `Tuple`:
https://github.com/JuliaLang/julia/blob/2ed1a411e0a080f3107e75bb65105a15a0533a90/base/tuple.jl#L657-L668. Consequently, in the type inference world, functions like `Base.all(::Generator)` are unavailable. If `Base.Compiler` attempts to perform operations such as `::BitSet ⊆ ::BitSet` (which internally uses `Base.[all|any]`), a world age error occurs (while `Compiler.[all|any]` can handle these operations, `::BitSet ⊆ ::BitSet` uses `Base.[all|any]`, leading to this issue)

To resolve this problem, this commit removes the custom `Compiler` versions of `[all|any]` and switches to using the Base versions.

~~One concern is that the previous `Compiler` versions of `[all|any]` utilized `@nospecialize`. However, since this was introduced a long time ago, I believe it does not cause any issues in the current implementation of the Compiler.~~
EDIT: One concern is that the previous `Compiler` versions of `[all|any]`
utilized `@nospecialize`. That annotation was introduced a long time ago
to prevent over-specialization, but it is questionable whether it is
still effective with the current compiler implementation. The results of
the nanosoldier benchmarks conducted below also seem to confirm that
the `@nospecialize`s are no longer necessary for those functions.

### CODE REVIEW

**Comment by vtjnash** [comment]
Looks like it isn't making bootstrapping too much worse from CI measurements, so this SGTM. We've changed and improved the recursion heuristics quite a bit, so this is probably not likely to trigger bootstrapping problems, and probably going to generate better code to run.

@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/56851#issuecomment-2549109918) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c9acb49_vs_35729d9/report.md).

**Comment by vtjnash** [comment]
Seems like it was measured slower, but might be good to find out why to see if something was wrong, or if it was just a fluke measurement?
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/56851#issuecomment-2550208662) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/b46933b_vs_3774014/report.md).

**Review by vtjnash — APPROVED** [review]

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/56851#issuecomment-2552695314) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/f87f7d6_vs_03017db/report.md).

**Pull request merged**
