### PR TITLE
Remove 0.4 deprecations

### PR DESCRIPTION
**Pull request by tkelman**
not including the deprecated syntax in the parser, ref parts of #13054 which could be rebased

### CODE REVIEW

**Comment by tkelman** [comment]
Any objections to doing this now? We haven't quite hit feature freeze but we're getting close. Someone who's written in scheme more recently than 2003 should clean up the parser deprecations that were introduced for 0.4.

**Comment by IainNZ** [comment]
Should be fun to watch PkgEval!

**Comment by tkelman** [comment]
Good thing we have that running on a nightly cron job then :wink:

**Comment by tkelman** [comment]
Surprising number of packages still using `int` or `Uint` - http://pkg.julialang.org/pulse.html (made a bit worse by the coin-or servers being down for maintenance this weekend, so anything depending on Cbc or Ipopt failed)

**Pull request merged**
