### PR TITLE
release: backport #43347

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by aviatesk** [comment]
Very complicated backport... Let's see.

**Comment by johnnychen94** [comment]
> Maybe can we just wait for v1.8 for fixing this regression?

For the specific original issue https://github.com/JuliaImages/Images.jl/issues/992 our plan is to replace ImageMagick with a better JPEG wrapper so it is okay from JuliaImages' side not having this backported.

**Comment by aviatesk** [comment]
Then I'm leaning towards not merging this PR.

**Comment by DilumAluthge** [comment]
I misclicked the "assign self" link, sorry!

**Pull request closed without merging**
