### PR TITLE
give IR forms for defining types valid linear structure

### LINKED ISSUE #35416: Bug while typing recursive struct definition with UnionAll in type
I'm pretty sure this is a bug in the julia subtyping within recursive structs, which I encountered when making a small change to someone else's code:

They currently had their `Node` parameterized to accept any subtype of the _value_ type `V`, but didn't allow subtyped _keys_. So i tried to fix this by changing `K` to `<:K`, but as you'll see below that somehow breaks julia's ability to define the type! 😱 

```julia
julia> module M
       struct Tip end

       struct Node{T,K,X}
         size::Int64
         left::T
         key::K
         value::X
         right::T
       end

       struct AVL{K,V}
         avl:: Union{Tip,Node{AVL{K,V},K,<:V}}  # Works okay with just one subtype
       end

       end # module
WARNING: replacing module M.
Main.M

julia> module M
       struct Tip end

       struct Node{T,K,X}
         size::Int64
         left::T
         key::K
         value::X
         right::T
       end

       struct AVL{K,V}
         avl:: Union{Tip,Node{AVL{K,V},<:K,<:V}}  # Breaks with two subtypes! 😱
       end

       end # module
WARNING: replacing module M.
ERROR: UndefVarError: AVL not defined
Stacktrace:
 [1] top-level scope at REPL[22]:12
 [2] eval(::Module, ::Any) at ./boot.jl:331
 [3] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/daly/builds/julia-1.4/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [4] run_backend(::REPL.REPLBackend) at /Users/daly/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [5] top-level scope at none:0
```

I tried many variants of that definition, including things like `Node{AVL{K,V}, S,T} where {S<:K, T<:V}` and other things, but they all fail with the same error.

Thanks! :)

### PR DESCRIPTION
**Pull request by JeffBezanson**
The type-defining IR forms (`struct_type` etc.) are currently very special: they violate the usual linear structure rules for IR, and evaluate their arguments in a non-standard way intertwined with some global effects. This PR tries to clean that up, removing the special cases and hopefully eventually leading to fixing #33183.

The new type-defining process here is broken into three steps at the IR level:
1. Create a new partially-initialized type object and bind it to a local variable.
2. Evaluate the supertype expression and set it.
3. Evaluate and set field types, fix up partial types.
4. Assign the type globally, doing the special check for valid redefinitions.

Uses only function calls (unfortunately requiring several new builtins though).

fixes #35416

### CODE REVIEW

**Comment by JeffBezanson** [comment]
It seems to me that if we break everything down into simpler forms, JuliaInterpreter can continue to work unmodified, which would certainly be a plus.

**Comment by timholy** [comment]
Since you asked about JuliaInterpreter, the changes were relatively minor (though not entirely trivial to track down):

- https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/389 and specifically https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/389/commits/77660f50f3343eb5fc77ce9cc14b601560a2d19a
- https://github.com/JuliaDebug/LoweredCodeUtils.jl/pull/28
- https://github.com/timholy/Revise.jl/pull/473

We'd noticed the former differences in lowering, and even had to handle them specially to make sure a performance optimization didn't trigger errors. So I'm supportive of this change.

**Comment by NHDaly** [comment]
Hooray! Thanks Jeff! Awesome. :)

**Comment by o314** [comment]
Currently, eg. in Julia v1.5.2 it still remains a mention to those expr in

```lsp
    (define (check-top-level e)
      (define (head-to-text h)
        (case h
          ((abstract_type)  "\"abstract type\"")
          ((primitive_type) "\"primitive type\"")
          ((struct_type)    "\"struct\"")
          ((method)         "method definition")
          (else             (string "\"" h "\""))))
```

@ https://github.com/JuliaLang/julia/blob/v1.5.2/src/julia-syntax.scm#L3786-L3790

I don't know if it is voluntary (for backward compat or something else), or an omission

**Pull request merged**
