### PR TITLE
Remove Markdown.jl

### PR DESCRIPTION
**Pull request by MikeInnes**
I never understood why people thought the parser and doc system was so completely tied to the Markdown parser, or why getting rid of Markdown was so urgent – until I tried out this branch. The build was ten times faster, we beat Fortran on all the benchmarks, and a unicorn apparated to type the commit message for me.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
LOL

**Comment by tkelman** [comment]
Yes yes, very funny. More seriously though, the consequences here would be documentation displays in plain text by default? Last issue where you specifically said to compare with-markdown vs plaintext output, the only difference I saw was a little bit of bold and color.

> I never understood why people thought the parser and doc system was so completely tied to the Markdown parser

Because they were added in the same PR, then sat around for 6 months without anyone trying to use them in base?

**Comment by ScottPJones** [comment]
:cry: Now, after I converted all our documentation from doxygen/Markdown to pure Markdown?
Please tell me it ain't so!

**Comment by JeffBezanson** [comment]
I don't think it's necessary to make this change now. First priority should just be to get docs working really well. If we want, this code can be moved out later as part of #5155.

**Comment by ViralBShah** [comment]
+1 to @JeffBezanson. We should focus on a first class documentation experience for now, and worry about refactoring once some of the other bits settle down.

**Comment by StefanKarpinski** [comment]
100% agreed.

**Comment by one-more-minute** [comment]
Well hey, I don't mind; a worse repl experience will make Juno look good ;)

More seriously, I definitely agree that making things work really well first, and optimising later, is a good approach.

**Pull request closed without merging**
