### PR TITLE
Include --export-dynamic in julia-config ldflags on FreeBSD

### LINKED ISSUE #31045: Embedding test failures on FreeBSD CI
Examples:
* https://build.julialang.org/#/builders/68/builds/2700
* https://build.julialang.org/#/builders/68/builds/2702

Looking over the recent builds in https://build.julialang.org/#/builders/68, it appears this is only happening on the FreeBSD 12.0 worker, not the 11.2 worker.

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #31045

### CODE REVIEW

**Comment by ararslan** [comment]
This does not fix the linked issue, but it seems like a worthwhile change regardless. @staticfloat, thoughts?

**Comment by iblis17** [comment]
```diff
diff --git a/test/embedding/Makefile b/test/embedding/Makefile
index df31c3735c..e7a23affff 100644
--- a/test/embedding/Makefile
+++ b/test/embedding/Makefile
@@ -45,8 +45,8 @@ $(BIN)/LocalModule.jl: $(SRCDIR)/LocalModule.jl
        cp $< $@
 endif
 
-check: $(BIN)/embedding$(EXE) $(BIN)/LocalModule.jl
-       $(JULIA) --depwarn=error $(SRCDIR)/embedding-test.jl $<
+check: | clean $(BIN)/embedding$(EXE) $(BIN)/LocalModule.jl
+       $(JULIA) --depwarn=error $(SRCDIR)/embedding-test.jl $(word 2,$|)
        @echo SUCCESS
 
 clean:
```

**Comment by ararslan** [comment]
It turns out that patch isn't needed, you just have to make sure you don't have an old binary lying around that wasn't built with this flag.

**Comment by ararslan** [comment]
This has been open over 20 days without request for changes, it's a tiny diff, and it fixes the linked issue, so #yolo

**Pull request merged**
