### PR TITLE
[GHA] Explicitly install Julia for whitespace workflow

### PR DESCRIPTION
**Pull request by giordano**
So far we relied on the fact that Julia comes in the default Ubuntu images on GitHub Actions runners, but this may change in the future (although there's apparently no plan in this direction for the time being).  To make the workflow more future-proof, we now explicitly install Julia using a dedicated workflow.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by giordano** [comment]
```

julia-actions/setup-julia@9b79636afcfb07ab02c256cede01fe2db6ba808c is not allowed to be used in JuliaLang/julia. Actions in this workflow must be: within a repository owned by JuliaLang or matching the following: citation-file-format/cffconvert-github-action@*, yogevbd/enforce-label-action@*, crate-ci/typos@*, actions/checkout@*.
```

**Comment by DilumAluthge** [comment]
Ah, yes I can fix that. One second.

**Comment by DilumAluthge** [comment]
Alright I fixed the allowlist. Now let's retry the job.

**Comment by DilumAluthge** [comment]
Okay, looks to be working now.

**Pull request merged**
