### PR TITLE
[doc/PDF] improvements to TOC style of the PDF manual

### PR DESCRIPTION
**Pull request by inkydragon**
Override latex writeheader to use our custom preamble.

## Changes:
+ Show only "part&chapter" in TOC
+ Use compact line spacing in TOC
+ Increase the spacing between chapter numbers and chapter names

xref: #35495

> - [x] Present lesser levels of subchapters in the TOC (It is almost 20 pages right now)
> - [x] The spacing for chapter numbers in the TOC is not sufficient

## Output
 14p  v.s. 3p
image
image

Output PDF: [doc-pdf-toc+compact-style+efac0d7794.pdf](https://drive.google.com/file/d/1aWNcs2UH-hD-QZamYTulHpfSv9jnHMVH/view?usp=sharing)

## fast PDF build

These changes affect only the TOC.
So you can compile only the TOC and ignore the rest of the document, which will speed up the compilation significantly!

Clone my [en-toc](https://github.com/inkydragon/Julia-LaTeX-doc/tree/en-toc) branch, and [build](https://github.com/inkydragon/Julia-LaTeX-doc/tree/en-toc#build).

### CODE REVIEW

**Comment by ViralBShah** [comment]
@fredrikekre Does this look good to you?

**Comment by fredrikekre** [comment]
Can this be incorporated in Documenter instead?

**Comment by inkydragon** [comment]
It is definitely possible. But I doubt that this custom style will work for all documents that use Documenter.
Later, I'll also add a custom cover for Julia's document, which undoubtedly doesn't fit in Documenter.

Documenter may provide a more flexible way to customize the preamble of a document.
Maybe Documenter could accept a keyword argument specifying the path to a custom `preamble.tex` and use its contents in place of the existing preamble .

**Comment by ViralBShah** [comment]
@fredrikekre Is adding this to Documenter significant effort? Since we have a PR that fixes known issues, would it be ok to merge this and then try to have Documenter implement these as convenient? Perhaps a Documenter issue should be opened up for necessary features.

**Comment by inkydragon** [comment]
Some new idea

```julia
function Documenter.Writers.LaTeXWriter.writeheader(io::IO, doc::Documenter.Documents.Document)
    custom = joinpath(doc.user.root, doc.user.source, "assets", "custom.sty")
    isfile(custom) ? cp(custom, "custom.sty"; force = true) : touch("custom.sty")
    custom = joinpath(doc.user.root, doc.user.source, "assets", "preamble.tex")
    isfile(custom) ? cp(custom, "preamble.tex"; force = true) : touch("preamble.tex") # TODO: Use the default preamble
    preamble =
        """
        \\newcommand{\\DocMainTitle}{$(doc.user.sitename)}
        \\newcommand{\\DocVersion}{$(get(ENV, "TRAVIS_TAG", ""))}
        \\newcommand{\\DocAuthors}{$(doc.user.authors)}

        % ---- Insert custom preamble
        \\input{preamble.tex}
        """
    _println(io, preamble)
end
```

This short `preamble` passed some variables to TeX.
Users can fully customize preamble by adding their own `preamble.tex`.


I'll clean up the `writeheader` implementation first, and then present the new custom preamble API proposal in JuliaDocs/Documenter.jl#1746 for discussion.

**Comment by inkydragon** [comment]
@ViralBShah Do we need a CI for building PDF?
The existing CI `doctest_linux64` seems to test only the HTML build.

**Comment by fredrikekre** [comment]
I mean, since this PR just overrides functions in Documenter, why not move the overrides there?

**Comment by inkydragon** [comment]
Yes, this pr overrides the Documenter function, mainly to make some changes to TOC style.
I'm not quite sure if this change should be applied to the upstream Documenter, so that all Documenter-based documents are styled the same way.

What this pr actually does is customize the TeX document style generated by Documenter. Maybe this pr can be merged into Documenter, but not all customization changes are necessary to sync upstream. 
I'm also going to add Julia's logo to the first page of the document next, so changes like that are no need to merge into Documenter as well.

The main issues here are that Documenter does not currently provide a way to customize the preamble. 
The solution I propose is to use the contents of `preamble.tex` as a preamble if it exists.
I may open a separate pr in Documenter.jl later.

**Comment by fredrikekre** [comment]
I mean, it seems like these are improvements that would be useful for everyone building pdf docs with Documenter, no?

**Comment by inkydragon** [comment]
I'm not sure, julia manual is a little bit special.

The manual has so many chapters (116) that by showing only the chapter names, the TOC is as long as any other TOC that shows both chapter and section names.

I also reduced the line spacing of the TOC to further reduce the length of the TOC.

Anyway, I opened new pr JuliaDocs/Documenter.jl#1750.

**Comment by jebej** [comment]
Agreed that this shouldn't go for all documents, and, for what it's worth, I prefer the old style despite the extreme length.

**Comment by inkydragon** [comment]
It looks like `git rebase master` messed up the commit log.

I'll open a new pr.

**Comment by inkydragon** [comment]
This pr will be replace by: (Merged) https://github.com/JuliaDocs/Documenter.jl/pull/1750 + (Merged) https://github.com/JuliaDocs/Documenter.jl/pull/1785 + https://github.com/JuliaDocs/Documenter.jl/pull/1788

**Pull request closed without merging**
