### PR TITLE
Fix small nits in multiversioning

### PR DESCRIPTION
**Pull request by gbaraldi**
The recent changes to the multiversioning pass had a couple small bugs.
@pchintalapudi

### CODE REVIEW

**Comment by giordano** [comment]
> had a couple small bugs.

Can add tests? 🙂

**Comment by gbaraldi** [comment]
I'm not sure how I would test that we clone functions correctly when building the sysimg 😄.

**Comment by vchuravy** [comment]
Build a mini sysimage and disassemble the output?

**Review by vchuravy — APPROVED** [review]

**Comment by KristofferC** [comment]
@vchuravy, merge?

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
Did we backport https://github.com/JuliaLang/julia/pull/43327?

**Comment by KristofferC** [comment]
I think that was too old for my backport script to consider it. I will try with that one

**Pull request merged**
