### PR TITLE
Add missing colon getindex method for AbstractString

### LINKED ISSUE #17624: Missing getindex method for `String`
```julia
julia> str = "abc"
"abc"

julia> str[1]
'a'

julia> str[1:2]
"ab"

julia> str[:]
ERROR: MethodError: no method matching getindex(::String, ::Colon)
```

### PR DESCRIPTION
**Pull request by jakebolewski**
closes #17624

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Any clue why CI isn't running on this?

**Comment by jakebolewski** [comment]
¯\_(ツ)_/¯

**Comment by StefanKarpinski** [comment]
@tkelman?

**Comment by tkelman** [comment]
missing a left arm there jake. webhooks have been flaky lately, not sure why

**Comment by StefanKarpinski** [comment]
There. I fixed the left arm.

**Comment by ararslan** [comment]
The biceps need escaping as well.

**Pull request merged**
