### PR TITLE
Add vectorized mod2pi

### PR DESCRIPTION
**Pull request by eford**

### CODE REVIEW

**Comment by eford** [comment]
I understand the Julia automated testing system.  
If you want a test, you could add
@test_approx_eq maximum(abs(mod2pi(testCases[:,1]).-testCases[:,2])) 0.0
to the end of 
julia/test/mod2pi.jl

**Comment by stevengj** [comment]
Now that `map` is fast, hoping to move away from vectorizing all the functions, and just have a general syntax like `.mod2pi(x)` for broadcasting.   See #8450

**Comment by eford** [comment]
I definitely like making map faster, but that proposed syntax for
broadcasting functions strikes me as  ugly and prone to creating bugs due
to confusing syntax.
At one point Julia prided itself in allowing syntax like 2func(x).
Which makes 2.func(x) ambiguous or at least confusing to humans.


On Fri, Apr 8, 2016 at 4:49 PM, Steven G. Johnson <notifications@github.com>
wrote:

> Now that map is fast, hoping to move away from vectorizing all the
> functions, and just have a general syntax like .mod2pi(x) for
> broadcasting. See #8450 <https://github.com/JuliaLang/julia/issues/8450>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julia/pull/15797#issuecomment-207599854>
>



-- 
Eric Ford
Professor of Astronomy & Astrophysics
Center for Exoplanets & Habitable Worlds
Center for Astrostatistics
Institute for CyberScience
Penn State Astrobiology Research Center
Pennsylvania State University

**Comment by nalimilan** [comment]
The proposed syntax is actually `func.(x)`, not not `.func(x)`.

Anyway, I think the question is: are other similar functions vectorized or not? Arbitrarily vectorizing some functions and not others isn't a very good solution.

**Comment by ViralBShah** [comment]
Yes, at this point, we want to have some syntax for vectorization and discourage addition of more vectorized operations.

**Comment by eford** [comment]
Personally, I'm not convinced that the choice of syntax is wise.  I was
happy with having a simple macro to vectorize functions that one wanted
vectorized.  If we need a naming convention, I think I'd rather have
something like func_vec, rather than an obscure "." syntax that's easy to
overlook.  But if that's the worst thing about julia, then I'll get over
it.  I definitely appreciate the work of the julia developers.

On Mon, Apr 11, 2016 at 6:37 AM, Viral B. Shah <notifications@github.com>
wrote:

> Yes, at this point, we want to have some syntax for vectorization and
> discourage addition of more vectorized operations.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julia/pull/15797#issuecomment-208276977>
>



-- 
Eric Ford
Professor of Astronomy & Astrophysics
Center for Exoplanets & Habitable Worlds
Center for Astrostatistics
Institute for CyberScience
Penn State Astrobiology Research Center
Pennsylvania State University

**Comment by nalimilan** [comment]
@eford That issue has been discussed a lot already. See the other issue for arguments.

**Comment by tkelman** [comment]
closing, given #15032

**Pull request closed without merging**
