### PR TITLE
optimized (and ordered) IdSet code

### PR DESCRIPTION
**Pull request by vtjnash**
We have had this smallintset code around for a while for internal purposes, though it was not quite fully general purpose (it didn't have pop). We also have around this tiny global_roots_table (about 1500 entries after building the sysig). This saves about 50% of the space for storing that table. It also optimizes all other IdSet code to not be an inefficient mutable wrapper around an IdDict, but instead be an ordered (by first insertion) set type of its own.

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(!"scalar" && !"union", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/52114#issuecomment-1806183767) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/d20506c_vs_8944a22/report.md).

**Comment by JeffBezanson** [comment]
Are IdDict and IdSet represented in the benchmarks?

**Comment by vtjnash** [comment]
IdDict probably is, but is not affected by this PR. IdSet is probably not

**Comment by stevengj** [comment]
Are we thinking of exporting `IdSet` at some point?

**Pull request merged**
