### PR TITLE
Missing tests for LQ mult methods

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by kshyatt** [comment]
IDK what's up with OSX but is this ok otherwise?

**Review by andreasnoack — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Looks like a checksum mismatch for curl... weird. I restarted it.

**Comment by tkelman** [comment]
back up the logs when you restart jobs on travis.

**Comment by StefanKarpinski** [comment]
> back up the logs when you restart jobs on travis.

For the amount of time that's been spent complaining about this, we could easily have an automatic job to backup logs to S3.

**Comment by tkelman** [comment]
it takes 5 seconds and 2 clicks to do, if you would just remember to do it. copy the raw log url, curl pipe that to the gist cli gem, done. a log scraping bot would take me several days to get running. you're welcome to do it if you want me to stop telling you to remember to do this. you're the only person who seems to be incapable of it.

**Comment by kshyatt** [comment]
@tkelman are you ok with me merging this?

**Comment by tkelman** [comment]
we have no idea what caused that failure, and it's not something we've seen before

**Pull request merged**
