### PR TITLE
Allow long-form `--debug-info` option

### PR DESCRIPTION
**Pull request by eschnett**
The Julia executable allows long-form options (e.g. `--optimize`) for almost all options. Noticeably missing is a long-form option for `-g`, and this somehow rubs me the wrong way.

This PR adds long-form options for the two missing cases, `--debug` and `--interactive`.

### CODE REVIEW

**Review by vchuravy — DISMISSED** [review]

**Comment by PallHaraldsson** [comment]
I've never used debug, i.e. -g, but I would like a debug option with some specific other changes, so maybe hold on on --debug? I see -d isn't used, not sure why -g was chosen, was it intentional to not conflict with a later --debug (and -d) option?

**Comment by KristofferC** [comment]
Yes, imo we should save `--debug` for a Julia debug option, e.g. https://github.com/JuliaLang/julia/pull/37874

**Comment by eschnett** [comment]
The option is likely called `-g` because this is the commonly used option name used by Fortran/C/C++ compilers, probably because `-d` and `-D` were already taken there. That's probably also the reason that the optimization level is set via an upper case `-O`.

**Comment by eschnett** [comment]
I renamed the option to `--debuginfo`.

**Comment by eschnett** [comment]
@KristofferC Do you approve if the long name of the `-g` option is `--debuginfo`?

**Comment by StefanKarpinski** [comment]
I think `--debug-info` would be more in line with other options.

**Pull request merged**
