### PR TITLE
Add latex mappings for subscript `<` and `>`

### PR DESCRIPTION
**Pull request by MilesCranmer**
Adds new latex mappings `\_<` => `˱` and similar for `>` to complement the existing `\_=`, `\_+`, `\_-`. Useful for describing set indices in a variable name like `x˱ᵢ` (renders poorly on GitHub but looks fine in the REPL).

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Maybe we should also add these as identifier-start-chars as we did for subscript parens?

**Comment by MilesCranmer** [comment]
What file would that be? I can add it

**Comment by inkydragon** [comment]
https://github.com/JuliaLang/julia/blob/63188d58c094a82f4b8e48cc39014800f7920b8f/src/flisp/julia_extensions.c#L67

https://github.com/JuliaLang/julia/blob/63188d58c094a82f4b8e48cc39014800f7920b8f/src/flisp/julia_extensions.c#L111-L113
```
julia> [ Char(u) for u in 0x208a:0x208e ]
5-element Vector{Char}:
 '₊': Unicode U+208A (category Sm: Symbol, math)
 '₋': Unicode U+208B (category Sm: Symbol, math)
 '₌': Unicode U+208C (category Sm: Symbol, math)
 '₍': Unicode U+208D (category Ps: Punctuation, open)
 '₎': Unicode U+208E (category Pe: Punctuation, close)
```

> Name:	MODIFIER LETTER LOW LEFT ARROWHEAD
> Block:	Spacing Modifier Letters
> Category:	Symbol, Modifier [Sk]
> https://www.fileformat.info/info/unicode/char/02f1/index.htm

```
julia> '˱'
'˱': Unicode U+02F1 (category Sk: Symbol, modifier)

julia> '˲'
'˲': Unicode U+02F2 (category Sk: Symbol, modifier)
```

NOTE: The two characters are not subscripts from the category, but are spacing-adjusted characters.

**Comment by MilesCranmer** [comment]
It doesn’t look like it’s available in that block: https://www.fileformat.info/info/unicode/block/superscripts_and_subscripts/list.htm. Not quite sure the terminology though.

**Review by tecosaur — APPROVED** [review]

**Comment by tecosaur** [comment]
This looks pretty non-controversial, so I'll go ahead and merge this.

Supporting these as identifier-start-chars seems like something a little more involved, so how about we address it in a subsequent PR?

(Aside: JuliaSyntax will need to be updated too, no?)

**Pull request merged**
