### PR TITLE
consolidate some of the parsing code

### PR DESCRIPTION
**Pull request by KristofferC**
```
@code_typed Base.tryparse_internal(Int8, "0x23", 1, 3, 10, true)
```

goes from 582 basic blocks to 441.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks("parse", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29879#issuecomment-435254080) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/df4204cdd9a586dcf013a973afee698dc7df973c/7f5e2f6_vs_05fb47d/report.md). cc @ararslan

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("parse", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/29879#issuecomment-484818800) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/be09d5bb78d991d913bbd4e6aef58ce5fa3bfa53/7f0374d_vs_c0c6f96/report.md). cc @ararslan

**Pull request closed without merging**
