### PR TITLE
removes euler.jl

### PR DESCRIPTION
**Pull request by vchuravy**
Project Euler asks not to distribute solution to the problems and we
don't depend on the tests in there.

cc @kshyatt

### CODE REVIEW

**Comment by simonbyrne** [comment]
@StefanKarpinski you added these originally: thoughts?

**Comment by StefanKarpinski** [comment]
Sure, as long as it doesn't affect coverage too much.

**Comment by TotalVerb** [comment]
Before we hit merge, `euler.jl` seemed to be the only file that failed when I broke array comparison.

**Comment by StefanKarpinski** [comment]
How about we just rename this to `test/puzzles.jl` instead and remove the answers in the comments?

**Pull request closed without merging**
