### PR TITLE
Avoid potential ambiguities for `[h/v/hv]cat` in packages

### LINKED ISSUE #158: Clash between hvcat in LinearAlgebra/src/uniformscaling.jl and LinearMaps/src/blockmap.jl
I finished the transition of linear operators defined in the [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl) package from LinearOperators- to LinearMaps-based implementation and uploaded the new version of the package. The tests run well on the current Julia version (I assume 1.6.2), but lead to errors on the Nighly version. A typical error is generated by the line

`S = schur([A  -G; -Q  -copy(A')])`

in a Riccati equation solver. Here `G` and `Q` are UniformScalings and A is a square matrix. The error message is:

```
Continuous Riccati equation (Float64, n = 30, m = 10): Error During Test at /home/runner/work/MatrixEquations.jl/MatrixEquations.jl/test/test_riccati.jl:52
  Got exception outside of a @test
  MethodError: hvcat(::Tuple{Int64, Int64}, ::Matrix{Float64}, ::Matrix{Float64}, ::LinearAlgebra.UniformScaling{Float64}, ::Matrix{Float64}) is ambiguous. Candidates:
    hvcat(rows::Tuple{Vararg{Int64}}, A::Union{Number, LinearAlgebra.UniformScaling, AbstractVecOrMat}...) in LinearAlgebra at /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:428
    hvcat(rows::Tuple{Vararg{Int64}}, As::Union{LinearAlgebra.UniformScaling, LinearMaps.LinearMap, AbstractVecOrMat}...) in LinearMaps at /home/runner/.julia/packages/LinearMaps/r6i00/src/blockmap.jl:172
  Possible fix, define
    hvcat(::Tuple{Vararg{Int64}}, ::Vararg{Union{LinearAlgebra.UniformScaling, AbstractVecOrMat}})
```

I encountered similar issues with the LinearOperator package (from which I transited to LM) and the authors managed somehow to restrain the promotion of their hvcat.  I wonder if this is also possible with LM. I also wonder what is the cause of the changed behaviour from version 1.6.2 to the nightly version.

### PR DESCRIPTION
**Pull request by dkarrasch**
#41394 has changed the method signature in concatenation functions involving `UniformScaling`s. This triggers method ambiguities for matrix-related packages, including `LinearMaps.jl` (see https://github.com/Jutho/LinearMaps.jl/issues/158). This PR resolves the ambiguity at the root.

Closes https://github.com/Jutho/LinearMaps.jl/issues/158.

### CODE REVIEW

**Comment by pablosanjose** [comment]
Friendly bump [I need this! :-)]

**Comment by chriscoey** [comment]
I do too 🙂

**Comment by andreasvarga** [comment]
This would be very helpful for me too. See my last [succesfull tests](https://github.com/andreasvarga/DescriptorSystems.jl/runs/3200604429) with [DescriptorSystems](https://github.com/andreasvarga/DescriptorSystems.jl) with Julia 1.6 and the [174 failed tests](https://github.com/andreasvarga/DescriptorSystems.jl/runs/3200604468) with Julia 1.7 due to the `[h/v/hv]cat` issue.

**Comment by KristofferC** [comment]
Seems like this would be useful to people and is unlikely to have any real issues so I would say to just merge this.

**Comment by dkarrasch** [comment]
The issue is that the PR causing the ambiguity (#41394) has introduced heavy latency problems, so I think triage needs to discuss/decide whether we want to go forward merging this or go backward and revert #41394.

**Comment by DilumAluthge** [comment]
I'm removing the `merge me` label so that this can be discussed at the next triage call.

On a separate note, I restarted the two failing CI jobs, just so we can see if CI passes on this PR.

**Comment by DilumAluthge** [comment]
Actually, I'll add the `merge me` label back.

If triage decides to revert #41394, but this PR has already been merged, presumably we can just revert this PR first and then revert #41394 (or revert them both in a single PR).

**Comment by sostock** [comment]
Closes #41912.

**Comment by JeffBezanson** [comment]
If this PR resolves the problem, I'm happy, but if anybody knows a remaining reason to revert #41394 speak up.

**Pull request merged**
