### PR TITLE
precompile abspath, normpath for UTF8String for a startup speedup

### PR DESCRIPTION
**Pull request by amitmurthy**
While tinkering with https://github.com/JuliaLang/julia/pull/11520, I added 

```
        clock_t start_t, end_t;
        start_t = clock();
        f = emit_function(li);
        end_t = clock();
        jl_printf(JL_STDERR, "%f milliseconds for emitting %s \n", (((double)(end_t - start_t)) * 1000) / CLOCKS_PER_SEC, li->name->name);
```

to `to_function` and surprisingly the functions with the longest times listed were `abspath` - 80 to 120 ms and `normpath` -70 to 100 ms

So I decided to add definitions with `UTF8String` for both `normpath` and `abspath` to `precompile.jl` and time startup.

This is what I get:
## master

```
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.152s
user    0m0.164s
sys     0m0.356s
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.136s
user    0m0.148s
sys     0m0.200s
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.143s
user    0m0.148s
sys     0m0.364s
```
## This PR

```
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.099s
user    0m0.080s
sys     0m0.088s
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.109s
user    0m0.088s
sys     0m0.112s
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.100s
user    0m0.096s
sys     0m0.068s
amitm@amitm-macbookpro:~/Work/julia/julia$ time julia -e 0

real    0m0.096s
user    0m0.092s
sys     0m0.060s
```

I don't understand the rationale for the speedup, but it seems real.

### CODE REVIEW

**Comment by KristofferC** [comment]
On Linux:

#### Master
```
kristoffer@kristoffer-MS-7673:~$ time julia-0.4  -e 0

real    0m0.124s
user    0m0.105s
sys 0m0.070s
kristoffer@kristoffer-MS-7673:~$ time julia-0.4  -e 0
```

### PR 
```
kristoffer@kristoffer-MS-7673:~/julia$ time julia-0.4  -e 0

real    0m0.098s
user    0m0.069s
sys 0m0.048s
kristoffer@kristoffer-MS-7673:~/julia$ time julia-0.4  -e 0
```

Interestingly enough, this is what I get on a 16 days old commit:

```
kristoffer@kristoffer-MS-7673:~/julia$ time julia-0.4  -e 0

real    0m0.080s
user    0m0.068s
sys 0m0.038s
```

So something has slowed it down quite a lot (+50%) recently.

**Comment by StefanKarpinski** [comment]
Nice speedup! It's typical that a pass needs to be made over the precompiles to tweak them for a new Julia version. Should certainly be done before we release 0.4.

**Comment by tkelman** [comment]
Nice little improvement. I wonder what happened over the last 16 days though.

**Comment by KristofferC** [comment]
I can try to locate where this happened a bit more specifically (assuming it isn't many incremental bits).

**Comment by StefanKarpinski** [comment]
One obvious change is all of @mbauman's recently merged work. I would guess that might change what needs to be precompiled somewhat.

**Comment by KristofferC** [comment]
That's what I thought at first, but I don't notice any difference before and after that merge. Bisecting atm.

**Comment by KristofferC** [comment]
Bisecting points to this: https://github.com/JuliaLang/julia/commit/469f69902d873d8d832ae564c1b0b782a0251f3b

Before (best)

```
real    0m0.086s
user    0m0.070s
sys 0m0.043s
```


After (best)

```
real    0m0.113s
user    0m0.097s
sys 0m0.032s
```

**Comment by StefanKarpinski** [comment]
cc: @vtjnash

**Comment by StefanKarpinski** [comment]
Should the precompile instructions that were moved into the earlier bootstrapping phase be redone in the later bootstrapping phase as well?

**Comment by vtjnash** [comment]
No harm in trying.

It might be from the increase (duplication) in code or the reduction in methods that are getting run (compiled) from Base

**Comment by KristofferC** [comment]
Should any effort be spent on tracking down the startup time regression in https://github.com/JuliaLang/julia/commit/469f69902d873d8d832ae564c1b0b782a0251f3b or is it fine to just let it be?

**Comment by tkelman** [comment]
> Should any effort be spent on tracking down the startup time regression

I'd interpret the "No harm in trying" as a yes, there are probably some tweaks that could be made to get that back.

**Pull request merged**
