### PR TITLE
Delete chol!(UniformScaling, uplo)

### PR DESCRIPTION
**Pull request by andreasnoack**
Supersedes https://github.com/JuliaLang/julia/pull/24541

### CODE REVIEW

**Comment by fredrikekre** [comment]
Technically does not need a deprecation since it was introduced post 0.6

**Comment by fredrikekre** [comment]
We also need to deal with https://github.com/JuliaLang/Compat.jl/blob/fbd9cb245a89af2c6d3eea0f1622729a14709163/src/Compat.jl#L551

**Comment by mschauer** [comment]
My comment from #22633: 

The function `chol!` is a *chainable modifying array function* and should do the right thing to immutable arrays. If `!`-versions of chainable array functions are defined for immutable arrays, then  `f!(g!(h!(copy(A()))))` is a good way to write efficient and generic code which works for immutables and mutables (here `!` allows `f`, `g`, `h` to use the copy of `A` as workspace where appropriate). In the same fashion, `copy` pushes through immutables and is defined for `UniformScaling`s. 

@fredrikekre asked me about this yesterday.

**Comment by andreasnoack** [comment]
Are there any real work use cases? It didn't look like you were using this version in Bridge.jl.

**Comment by mschauer** [comment]
Correct, I am not in immediate need of this. But the real work case was provided by yourself: `_chol!` is used heavily. Only that `_chol!` for technical reasons has in addition to "gracefully treating immutables" also a deferred  error treatment. Nevertheless a vanilla implementation of a generic cholesky factorization would use `chol!` and not `chol` in the lower level.

**Comment by andreasnoack** [comment]
> Nevertheless a vanilla implementation of a generic cholesky factorization would use `chol!`

Unfortunately, I think it would have to use `LinAlg._chol!` because of the way we handle failures/exceptions, i.e. `chol`/`chol!` throws because you'd otherwise get invalid results when it failed while `cholfact`/`cholfact!` only throws if a failed factorization is used.

**Comment by andreasnoack** [comment]
@mschauer Do you still consider this method useful? If so then let's just keep it.

**Comment by mschauer** [comment]
Yes, thank you!

**Pull request closed without merging**
