### PR TITLE
Create beta.jl

### PR DESCRIPTION
**Pull request by cossio**
Added incomplete beta function and its logarithm to Base.

### CODE REVIEW

**Comment by cossio** [comment]
This implementation is based on a continued fraction expansion from the Numerical Recipes.

**Comment by cossio** [comment]
I want to improve it (I use this myself), so any comments appreciated.

**Comment by kmsquire** [comment]
Hi @cossio, thank you for the contribution.  Unfortunately, the Numerical Recipes license forbids source code implementations from being distributed in source form (see http://numerical.recipes/licenses/redistribute.html), so we won't be able to include this implementation in Julia.

**Comment by cossio** [comment]
@kmsquire This does not copy the numerical recipes code. Note that the numerical recipes code computes the incomplete Beta function. I modified this to compute the logarithm of the incomplete beta function, which required (in my judgement), a substantial rewrite. I only reference to Numerical Recipes for an explanation, but the code is definitely not a copy. But I leave it to your judgement.

**Comment by StefanKarpinski** [comment]
Unfortunately, that almost certainly qualifies as a derived work, meaning we cannot use it. Legal stuff is quite annoying, but unfortunately also important to be careful about.

**Pull request closed without merging**
