### PR TITLE
release-1.7: Set VERSION to 1.7.0-beta2

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/41256#issuecomment-864004698

**Comment by KristofferC** [comment]
Doesn't seem crucial for the beta?

**Comment by DilumAluthge** [comment]
> Doesn't seem crucial for the beta, or?

Not at all. I just wanted to mention it in case you were wondering why Buildkite was failing on this PR.

**Comment by KristofferC** [comment]
Alright thanks :)

**Pull request merged**
