### PR TITLE
Base.windowserror function to encapsulate Windows errors in SystemErrors

### PR DESCRIPTION
**Pull request by stevengj**
While working on #30611, I noticed a need for a function like `systemerror` but for Windows errors that use `GetLastError()` instead of `errno`, in order to:

* Delay the cost of creating the formatted error string (with `Libc.FormatMessage`) until the error is actually displayed (if ever).
* Still use a `SystemError` exception type, so that the exception type is consistent across platforms.  (The fact that it is a Windows exception is stored in the `extrainfo` field.)
* Encapsulate a common pattern to shorten the code.

Along the way, I found and fixed a bunch of apparent bugs — functions that were calling `systemerror` after Windows API calls that don't set `errno`.  (These would have thrown a `SystemError` exception with `errorshow` function that confusingly prints "no error" or similar as the error message.)

The resulting `Base.windowserror` function is not exported.

### CODE REVIEW

**Comment by stevengj** [comment]
Yay, green CI!

**Comment by stevengj** [comment]
@tkelman, @StefanKarpinski, good to merge?

**Comment by stevengj** [comment]
Note that libuv has a `uv_translate_sys_error` function that translates a Windows error code like `ERROR_NOACCESS` into a libuv error code like `UV_EACCES`.  If there is another function to translate libuv error codes into `errno` error codes, we might use this to set the `errnum` field of the `SystemError` to a useful value in `windowserror`, in case any caller wants to make use of this in a `catch` block.

**Comment by StefanKarpinski** [comment]
I guess my only question is whether this needs to be a separate function from `systemerror` or if we can just have a single function that plays both roles by looking at `GetLastError` and `errno` but it seems like there may be no way of doing that and one needs to know which one each Windows API call sets and correspondingly which of `systemerror` and `windowserror` one needs to call.

**Comment by stevengj** [comment]
I think they need to be separate functions, because whether you call `GetLastError` or `errno` depends on the preceding `ccall`.   (Windows API calls generally need `GetLastError` and POSIX calls need `errno`.)

**Review by StefanKarpinski — APPROVED** [review]

**Pull request merged**
