### PR TITLE
plotting a line requires a start and an end point

### PR DESCRIPTION
**Pull request by hexxt-git**
to plot a line you need a start point (x1, y1) and an end point (x2, y2). just one is not enough.

### CODE REVIEW

**Comment by Krastanov** [comment]
This seems a bit nitpicky given that it is fairly common convention that x and y are arrays of points :) You can find quotes like that in the documentation of all R, python, javascript, and julia plotting libraries. E.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html

**Comment by bramtayl** [comment]
We could just say that x and y are arrays of coordinates then?

**Comment by bramtayl** [comment]
And maybe call x and y `X` and `Y` or `xs` and `ys`

**Comment by KristofferC** [comment]
I think it is fine to use `x` and `y` here. Using the `x1, y1, x2, y2` adds a fair bit of noise and the point here is just to talk about keywords, not about a particular `plot` function.

**Pull request closed without merging**
