### PR TITLE
[release-0.4] backports for RC3

### PR DESCRIPTION
**Pull request by tkelman**
Anything other than #13269 left that's release-blocking?

### CODE REVIEW

**Comment by tkelman** [comment]
Lots of failures: https://gist.github.com/29d6c5c392aacd660acd

```diff
tkelman@davinci:~/PackageEvaluator.jl/scripts$ diff -u d8930a01ac/summary 0cb06e4922/summary
--- d8930a01ac/summary  2015-09-23 17:09:29.988711243 -0700
+++ 0cb06e4922/summary  2015-09-24 12:44:55.994078212 -0700
@@ -3,7 +3,7 @@
 nightly/ActiveAppearanceModels.json
 "tests_fail"
 nightly/AffineTransforms.json
-"tests_pass"
+"tests_fail"
 nightly/AmplNLWriter.json
 "tests_fail"
 nightly/AnsiColor.json
@@ -197,7 +197,7 @@
 nightly/CoverageBase.json
 "tests_pass"
 nightly/Coverage.json
-"tests_pass"
+"tests_fail"
 nightly/CPLEX.json
 "not_possible"
 nightly/Cpp.json
@@ -289,7 +289,7 @@
 nightly/DistributedArrays.json
 "tests_pass"
 nightly/Distributions.json
-"tests_fail"
+"tests_pass"
 nightly/Diversity.json
 "tests_fail"
 nightly/Docile.json
@@ -409,7 +409,7 @@
 nightly/FunctionalUtils.json
 "no_tests"
 nightly/Gadfly.json
-"tests_pass"
+"tests_fail"
 nightly/GARCH.json
 "tests_fail"
 nightly/Gaston.json
@@ -425,7 +425,7 @@
 nightly/GeoInterface.json
 "tests_pass"
 nightly/GeoIP.json
-"tests_pass"
+"tests_fail"
 nightly/GeoJSON.json
 "tests_pass"
 nightly/GeometricalPredicates.json
@@ -443,7 +443,7 @@
 nightly/GibbsSeaWater.json
 "tests_pass"
 nightly/GitHub.json
-"tests_pass"
+"tests_fail"
 nightly/GLAbstraction.json
 "not_possible"
 nightly/GLFW.json
@@ -529,7 +529,7 @@
 nightly/HttpParser.json
 "tests_pass"
 nightly/HttpServer.json
-"tests_pass"
+"tests_fail"
 nightly/Humanize.json
 "tests_pass"
 nightly/Hwloc.json
@@ -631,7 +631,7 @@
 nightly/JPLEphemeris.json
 "no_tests"
 nightly/JSON.json
-"tests_fail"
+"tests_pass"
 nightly/JudyDicts.json
 "no_tests"
 nightly/JuliaFEM.json
@@ -683,7 +683,7 @@
 nightly/LazySequences.json
 "no_tests"
 nightly/Lens.json
-"tests_fail"
+"tests_pass"
 nightly/LevelDB.json
 "tests_fail"
 nightly/Levenshtein.json
@@ -693,9 +693,9 @@
 nightly/LibBSON.json
 "tests_pass"
 nightly/LibCURL.json
-"no_tests"
-nightly/LibExpat.json
 "tests_fail"
+nightly/LibExpat.json
+"tests_pass"
 nightly/LibGEOS.json
 "tests_pass"
 nightly/LibGit2.json
@@ -755,7 +755,7 @@
 nightly/MacroTools.json
 "tests_pass"
 nightly/Mamba.json
-"tests_pass"
+"tests_fail"
 nightly/ManifoldLearning.json
 "tests_pass"
 nightly/MapLight.json
@@ -787,7 +787,7 @@
 nightly/MatrixMarket.json
 "tests_pass"
 nightly/MbedTLS.json
-"tests_pass"
+"tests_fail"
 nightly/MCMC.json
 "no_tests"
 nightly/MDCT.json
@@ -813,13 +813,15 @@
 nightly/MessageUtils.json
 "tests_fail"
 nightly/MetadataTools.json
-"tests_pass"
+"tests_fail"
 nightly/MetaTools.json
 "no_tests"
 nightly/Metis.json
 "tests_pass"
 nightly/MFCC.json
 "tests_pass"
+nightly/MIDI.json
+"tests_fail"
 nightly/Millboard.json
 "tests_pass"
 nightly/MinimalPerfectHashes.json
@@ -833,7 +835,7 @@
 nightly/MLKernels.json
 "tests_fail"
 nightly/MNIST.json
-"no_tests"
+"tests_pass"
 nightly/Mocha.json
 "tests_pass"
 nightly/ModernGL.json
@@ -873,7 +875,7 @@
 nightly/MutableStrings.json
 "no_tests"
 nightly/Mux.json
-"tests_pass"
+"tests_fail"
 nightly/NaiveBayes.json
 "tests_pass"
 nightly/NamedArrays.json
@@ -923,7 +925,7 @@
 nightly/NURBS.json
 "tests_fail"
 nightly/OAuth.json
-"tests_pass"
+"tests_fail"
 nightly/OCCA.json
 "tests_fail"
 nightly/ODBC.json
@@ -960,6 +962,8 @@
 "tests_pass"
 nightly/PAINTER.json
 "tests_fail"
+nightly/PairwiseListMatrices.json
+"tests_pass"
 nightly/Pandas.json
 "not_possible"
 nightly/ParallelSparseMatMul.json
@@ -1015,7 +1019,7 @@
 nightly/Polynomial.json
 "no_tests"
 nightly/Polynomials.json
-"no_tests"
+"tests_pass"
 nightly/PowerSeries.json
 "tests_pass"
 nightly/ProfileView.json
@@ -1091,7 +1095,7 @@
 nightly/REPLCompletions.json
 "not_possible"
 nightly/Requests.json
-"tests_pass"
+"tests_fail"
 nightly/Requires.json
 "tests_pass"
 nightly/Resampling.json
@@ -1127,7 +1131,7 @@
 nightly/RunTests.json
 "tests_fail"
 nightly/SALSA.json
-"tests_pass"
+"tests_fail"
 nightly/Sampling.json
 "tests_fail"
 nightly/SaveREPL.json
@@ -1247,9 +1251,9 @@
 nightly/Sundials.json
 "tests_fail"
 nightly/SunlightAPIs.json
-"tests_pass"
+"tests_fail"
 nightly/SVM.json
-"tests_pass"
+"tests_fail"
 nightly/SVMLightLoader.json
 "tests_pass"
 nightly/Switch.json
@@ -1375,7 +1379,7 @@
 nightly/Weave.json
 "tests_fail"
 nightly/WebSockets.json
-"tests_pass"
+"tests_fail"
 nightly/WinRPM.json
 "no_tests"
 nightly/Winston.json
```

AffineTransforms: `ERROR: LoadError: module Images not found in current path; removed orphaned cache file /home/vagrant/.julia/lib/v0.4/Images.ji`

Coverage, GeoIP, GitHub, MbedTLS, MetadataTools, Mux, OAuth, Requests, SunlightAPIs, WebSockets: build problems with MbedTLS, maybe download issues?

Gadfly, SALSA: timeout due to deprecations

Mamba: `LoadError: Install Cairo to use the PDF backend. You may need to delete your cache files (usually in ~/.julia/lib/v0.4) afterwards.`

SVM: `LoadError: module StatsBase not found in current path; removed orphaned cache file /home/vagrant/.julia/lib/v0.4/StatsBase.ji`

So all dependency issues.

**Comment by JeffBezanson** [comment]
STOP THE PRESSES: https://github.com/JuliaLang/julia/commit/7bf34490dd90aaa7329b56f5689ea1cf57a83500#commitcomment-13427046

**Comment by tkelman** [comment]
ack, though test trouble on osx? http://buildbot.e.ip.saba.us:8010/builders/build_osx10.9-x64/builds/932/steps/shell_2/logs/stdio

**Comment by GunnarFarneback** [comment]
Would #13315 qualify for RC3?

**Comment by tkelman** [comment]
If it gets reviewed and merged to master in time for me to do a pkgeval run that includes it as a potential backport, maybe. We're about a day overdue and I'm going to be cutting rc3 very soon if no one tells me otherwise.

**Comment by tkelman** [comment]
https://gist.github.com/anonymous/b1caa482a838cf9f66ac

only new failure there is nlsolve which has been intermittent. merging and tagging.

**Pull request merged**
