### PR TITLE
inference: apply tmerge limit elementwise to the Union

### PR DESCRIPTION
**Pull request by vtjnash**
This allows forming larger unions, as long as each element in the Union is both relatively distinct and relatively simple. For example:

    tmerge(Base.BitSigned, Nothing) == Union{Nothing, Int128, Int16, Int32, Int64, Int8}
    tmerge(Tuple{Base.BitSigned, Int}, Nothing) == Union{Nothing, Tuple{Any, Int64}}
    tmerge(AbstractVector{Int}, Vector) == AbstractVector
    tmerge(AbstractVector{Int}, Array) == AbstractArray

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
@nanosoldier `runtests()`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/50927#issuecomment-1717739983) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/6b81d40_vs_572fa50/report.md).

**Comment by vtjnash** [comment]
Seems that this will eliminate an allocation in sparse matmul, but otherwise does not change anything.

**Comment by gbaraldi** [comment]
Doesn't seem to have any regressions in inference so I guess it's still worth

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/50927#issuecomment-1718276185) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/550281a_vs_832e46d/report.html) is available.

**Comment by JeffBezanson** [comment]
> ```
> tmerge(AbstractVector{Int}, Vector) == AbstractArray
> ```

Can this be `AbstractVector`?

**Review by JeffBezanson — APPROVED** [review]

**Comment by vtjnash** [comment]
Yeah, that was changed in a later version of the PR at Oscar's insistence, and updated in the commit messages but not the PR text. Initially I didn't have the tname_intersection function returning the intersection, so it couldn't match up the parameters.

**Pull request merged**
