### PR TITLE
Update build_sysimg.jl for new --output-ji/--output-o changes

### LINKED ISSUE #11933: build_sysimg broken after #11640
Building recently from master (5444813fb8997b22cfa7ac78438d2f4798341152) produces a `sys.so` but no `sys.ji`. While the resulting binary will run from the command prompt, curiously it doesn't run properly when loaded via `node-julia`, which complains 

    System image file "/usr/local/lib/julia/sys.ji" not found

Attempting to build it manually fails also

    julia> build_sysimg(default_sysimg_path, "x86-64", force=true)
    INFO: Building inference0.o...
    /usr/local/bin/julia -C x86-64 --build /usr/local/bin/../lib/julia/inference0 coreimg.jl
    julia: unknown option `--build`
    ERROR: failed process: Process(`/usr/local/bin/julia -C x86-64 --build /usr/local/bin/../lib/julia/inference0 coreimg.jl`, ProcessExited(1)) [1]
     in run at ./process.jl:490
     in anonymous at /usr/local/share/julia/build_sysimg.jl:55
     in cd at ./file.jl:22
     in build_sysimg at /usr/local/share/julia/build_sysimg.jl:27
     in build_sysimg at /usr/local/share/julia/build_sysimg.jl:12

### PR DESCRIPTION
**Pull request by staticfloat**
Should fix #11933

### CODE REVIEW

**Comment by JeffBezanson** [comment]
It looks like a large and useful part of this is finding and invoking the linker. In that case, I suspect this is only needed for building DLLs, so we can remove `--output-ji`.

**Comment by tkelman** [comment]
especially with #11954 which I think is a nicer solution than carrying around the `ji` file

**Comment by staticfloat** [comment]
Perhaps we should be more intelligent about which we choose, since on
platforms without linkers we can still make .ji files. So we can check for
the linker first, then emit only .o or only .ji?

**Comment by tkelman** [comment]
Should we merge this for now, or try to make it fancier first?

**Comment by staticfloat** [comment]
I'm AFK for the next week, so feel free to make decisions without me. :)

**Comment by kshyatt** [comment]
Does this mean we're going to get nightlies back?

**Comment by tkelman** [comment]
This file's in contrib and has nothing to do with the nightlies. According to status.julialang.org the nightlies should be fine? Coverage nightlies need https://github.com/staticfloat/julia-buildbot/pull/21 and possibly other fixes.

**Comment by kshyatt** [comment]
Today I learned! Thanks for the explanation.

**Comment by tkelman** [comment]
Any time, always happy to explain anything that I know the answer to.

**Pull request merged**
