### PR TITLE
fix docstring for alignment

### PR DESCRIPTION
**Pull request by goropikari**
`alignment`needs `io`.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
To pick up context options like compact and typeinfo I believe.

**Comment by StefanKarpinski** [comment]
Ah, I see. That makes sense.

**Comment by ViralBShah** [comment]
This is nice to merge in. I realize these didn't get caught since they are not `jldoctest`s. @goropikari Is that something you would still be able to add to this one?

**Comment by ViralBShah** [comment]
Actually I'll merge and open a separate issue to make these doctests.

**Pull request merged**
