### PR TITLE
Revise tests for `test/abstractarray.jl`

### PR DESCRIPTION
**Pull request by davidagold**
This is a small follow up PR to https://github.com/JuliaLang/julia/pull/12086; its purpose is to incorporate the suggestions from @tkelman, @ScottPJones and @mbauman that arose after the original PR was merged. 

Revisions include:
-Add token type for dispatching test methods to help avoid potential method signature clashes
-Beef up `test_in_bounds` (the test I included in the previous PR was pretty lame in retrospect.)
-Revise `test_vcat_depwarn` not to throw deprecation warnings to STDERR while running tests.

### CODE REVIEW

**Comment by tkelman** [comment]
Looks good, thanks.

**Comment by kshyatt** [comment]
Nice, thanks for doing this @davidagold!

**Comment by davidagold** [comment]
@kshyatt you're very welcome!

@tkelman Thank you for merging -- any word on why master is failing on Travis?

**Comment by tkelman** [comment]
```
julia: dump.c:1025: jl_deserialize_value: Assertion `bp' failed.
/home/travis/build.sh: line 41: 25223 Aborted                 /tmp/julia/bin/julia -e 'versioninfo()'
```

That happens intermittently and has been seen a few other times before, probably unrelated. Don't think we have a separate issue for it but we should, especially if anyone can come up with a repeatable way to trigger it locally.

**Comment by davidagold** [comment]
If it's not too long a story, what exactly does that ```Assertion `bp' failed``` mean?

**Comment by tkelman** [comment]
I don't know what that code is doing, but clicking the blame button and looking at https://github.com/JuliaLang/julia/blame/17bebe5f6ada25dfae894a73cabd3e618ac5b9e8/src/dump.c says it was last modified in ca7c4c82217a564144c1491850ae0d611b75c114 by @vtjnash. He might have a better idea what could cause that to fail.

**Comment by davidagold** [comment]
Gotcha. Thank you for the info!

**Comment by vtjnash** [comment]
i believe i have fixed all possible situations where that could happen in the various dump.c enhancements in PR #8745. the error means that the serializer encoded an object as a "back-reference" to a previously deserialized object, except that the previous object hadn't actually been constructed yet.

**Pull request merged**
