### PR TITLE
Allow pushing to vector after 3-arg ldiv!

### LINKED ISSUE #583: `resize!` failure after using ldiv! on v1.0
MWE:

```julia
using LinearAlgebra
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lu(W)
  ldiv!(vec(w),luw,v)
  resize!(v,3)
end
resizer()
```

The `resize!` fails because of the view on `v` which is built internally. Patching with

```julia
function LinearAlgebra.ldiv!(Y::AbstractVecOrMat, A::Factorization, B::AbstractVecOrMat)
    @assert !LinearAlgebra.has_offset_axes(Y, B)
    m, n = size(A, 1), size(A, 2)
    if m > n
        ldiv!(A, B)
        return copyto!(Y, B)
    else
        return ldiv!(A, copyto!(Y, B))
    end
end
```

fixes the issue. Note that this is a regression from v0.6 where

```julia
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lufact(W)
  A_ldiv_B!(w,luw,v)
  resize!(v,3)
end
resizer()
```

works.

Is that viewless version fine? Should I PR it? I don't really understand what supporting using only part of `B` is for. For reference the dispatch is

https://github.com/JuliaLang/julia/blob/f104ea4ec352519de76e52bf65ea7b3ed2dc6155/stdlib/LinearAlgebra/src/factorization.jl#L98-L108

Why not generally use `B`?

### LINKED ISSUE #897: Cannot push to a vector after applying a 3-arg ldiv!
```julia
using LinearAlgebra
u = rand(2)
A = rand(2,2)
b = rand(2)

push!(b,3.0) # works
u = rand(3)
A = rand(3,3)
ldiv!(u,lu(A),b)

push!(b,4.0) # Error: cannot resize array with shared data
```

_Originally posted by @ChrisRackauckas in https://github.com/JuliaLang/julia/issues/33143#issuecomment-999020297_

### LINKED ISSUE #29852: `resize!` failure after using ldiv! on v1.0
MWE:

```julia
using LinearAlgebra
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lu(W)
  ldiv!(vec(w),luw,v)
  resize!(v,3)
end
resizer()
```

The `resize!` fails because of the view on `v` which is built internally. Patching with

```julia
function LinearAlgebra.ldiv!(Y::AbstractVecOrMat, A::Factorization, B::AbstractVecOrMat)
    @assert !LinearAlgebra.has_offset_axes(Y, B)
    m, n = size(A, 1), size(A, 2)
    if m > n
        ldiv!(A, B)
        return copyto!(Y, B)
    else
        return ldiv!(A, copyto!(Y, B))
    end
end
```

fixes the issue. Note that this is a regression from v0.6 where

```julia
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lufact(W)
  A_ldiv_B!(w,luw,v)
  resize!(v,3)
end
resizer()
```

works.

Is that viewless version fine? Should I PR it? I don't really understand what supporting using only part of `B` is for. For reference the dispatch is

https://github.com/JuliaLang/julia/blob/f104ea4ec352519de76e52bf65ea7b3ed2dc6155/stdlib/LinearAlgebra/src/factorization.jl#L98-L108

Why not generally use `B`?

### LINKED ISSUE #43507: Cannot push to a vector after applying a 3-arg ldiv!
```julia
using LinearAlgebra
u = rand(2)
A = rand(2,2)
b = rand(2)

push!(b,3.0) # works
u = rand(3)
A = rand(3,3)
ldiv!(u,lu(A),b)

push!(b,4.0) # Error: cannot resize array with shared data
```

_Originally posted by @ChrisRackauckas in https://github.com/JuliaLang/julia/issues/33143#issuecomment-999020297_

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes JuliaLang/LinearAlgebra.jl#897. Fixes JuliaLang/LinearAlgebra.jl#583.

### CODE REVIEW

**Comment by oscardssmith** [comment]
This doesn't seem like a good fix. It fixes the specific problem, but doesn't do anything to address the more general problem which is that you can't resize a `Vector` if it ever has been `view`ed, even if none of those `view`s exist.

**Comment by simonbyrne** [comment]
Sure, but that's a much more general issue. This solves a specific concrete issue that causes problems elsewhere (https://github.com/SciML/LinearSolve.jl/pull/81)

**Comment by oscardssmith** [comment]
In that case, can you add a `TODO` to this to say it's safe to remove once the general issue is solved?

**Comment by simonbyrne** [comment]
Is there a big problem to having separate methods? It does make it simpler, and avoids intermediate views

**Comment by dkarrasch** [comment]
In the failing test (which fails for Julia v1.6+), the untouched matrix-method in the `m <= n` branch copies to the wrong place: `Y` is 3x3, `B` is 2x3 and `copyto!` (in the new line 136) copies along linear indices. It should perhaps read as:
```julia
function ldiv!(Y::AbstractMatrix, A::Factorization, B::AbstractMatrix)
    require_one_based_indexing(Y, B)
    m, n = size(A, 1), size(A, 2)
    if m > n
        Bc = copy(B)
        ldiv!(A, Bc)
        return copyto!(Y, view(Bc, 1:n, :))
    else
        copyto!(view(Y, 1:m, :), view(B, 1:m, :))
        return ldiv!(A, Y)
    end
end
```
At least with this change the failing test fails no more. Not sure if we need more size checks here, actually.

**Comment by dkarrasch** [comment]
Backporting to v1.6 requires special care due to the `ColumnNorm()` argument...

**Comment by simonbyrne** [comment]
Thanks @dkarrasch!

> Backporting to v1.6 requires special care due to the `ColumnNorm()` argument...

I think changing it to `Val(true)` should work.

**Comment by dkarrasch** [comment]
Shall we just merge or rebase before merging?

**Pull request merged**
