### PR TITLE
Insert eager calls to `finalize` for otherwise-dead finalizeable objects

### PR DESCRIPTION
**Pull request by jpsamaroo**
Finalizers are a great way to defer the freeing side of memory management until some later point; however, they can have unpredictable behavior when the data that they free is not fully known to the GC (e.g. GPU allocations, or distributed references). This can result in behavior like out-of-memory situations, excessive memory usage, and sometimes more costly freeing behavior (in the event that locks need to be taken).

This seems like a bad situation, but there is a silver lining: some code patterns which allocate such objects don't actually need the allocations to stick around very long, and the lifetime of the object could (in theory) be statically determined by the compiler. Thankfully, with the ongoing work of integrating EscapeAnalysis.jl into the optimizer, we can use the generated escape information to improve this situation.

This PR uses escape info from EA to determine when an object has an attached finalizer, and when its lifetime is provably finite (i.e. the object does not escape the analyzed scope). For such objects, we can insert an early call to `finalize(obj)` at the end of `obj`'s lifetime, which will allow the object's finalizer to be enqueued for execution immediately, minimizing how long finalizeable object stay live in the GC.

### CODE REVIEW

**Review by aviatesk — COMMENTED** [review]
I rebased `avi/EASROA`. Maybe rebasing this branch against it would fix the build error?

**Comment by jpsamaroo** [comment]
Latest push post-rebase still spams `UndefRefError()` in `adce_pass!`

**Comment by jpsamaroo** [comment]
Per discussion: the issue here is probably that we don't check that the `return` dominates the allocation passed to `finalize`, so we'll need to query the domtree as well.

This change will also potentially cause extended lifetimes for some allocations, but that's apparently a general issue that needs resolving.

**Comment by jpsamaroo** [comment]
We're now factoring in dominance information (hopefully correctly), which appears to have fixed the errors!

**Comment by yuyichao** [comment]
Note that calling `finalize` is expensive since it's not designed to be used this way. This is especially in code that uses finalizer a lot, which seems to be what this is targetting. In another word, this transformation will make your code run slower if it didn't run out of memory.

If you can prove that the object has only known finalizers, and you know what those are, you should be able to call the finalizer directly without going through the normal GC logic. If you can't prove that exception won't occur, which you probably won't be able to prove at this level, you can just set a flag in the GC to tell it to not run any currently registered finalizers (`finalize` may need to check this flag as well). If that's too much code to generate, you can simply add a new C API to pass in the finalizer directly so that you can skip the scan of the finalizer list and have that C API set appropriate flags for the GC.

Also, as I've said many time before, it is fairly easy to effectively let the GC know about these object. In most cases all what you need to do is to call `GC.gc()` when your allocation/file opening failed.

**Comment by AriMKatz** [comment]
@chflood any thoughts on this?

**Comment by jpsamaroo** [comment]
@yuyichao while I do agree with that being the long-term goal for many usages, the counter-argument against directly calling the finalizer thunk is that users may not have written their finalizers such that they can be safely called in the same scope as the allocation (for example, if the finalizer takes a non-reentrant lock that is already held in the allocation scope). For now, the goal is to let the GC know (through any means) as soon as possible that the allocation is dead and that its finalizers may run.

> you can simply add a new C API to pass in the finalizer directly so that you can skip the scan of the finalizer list and have that C API set appropriate flags for the GC.

I agree with adding this fast-path; would it be reasonable to punt that to a future PR, or do you want to see that done here before this is considered for merge? I would like to avoid sinking too much time on the extra complexity right now, since (IMO) the core of this PR is simple and easily understood.

**Comment by jpsamaroo** [comment]
I've gotten this working on basic functions, and added support for inserting `finalize` before `throw`:

```julia
function g(cond, x)
  r = Ref{Any}()
  finalizer(r) do _r
  end
  r[] = x
  if cond
    error("Lol")
    return r[]
  end
  return r
end
```

initially looks like

```
2  1 ─ %1 = %new(Base.RefValue{Any})::Base.RefValue{Any}                                                                                                      │╻╷ Ref
3  │   %2 = %new(Main.:(var"#13#14"))::Core.Const(var"#13#14"())                                                                                              │
   │   %3 = $(Expr(:foreigncall, :(:jl_get_ptls_states), Ptr{Nothing}, svec(), 0, :(:ccall)))::Ptr{Nothing}                                                   │╻  finalizer
   │        $(Expr(:foreigncall, :(:jl_gc_add_finalizer_th), Nothing, svec(Ptr{Nothing}, Any, Any), 0, :(:ccall), :(%3), :(%1), :(%2), :(%3)))::Nothing       ││
5  │        Base.setfield!(%1, :x, _3)::String                                                                                                                │╻╷ setindex!
6  └──      goto #3 if not _2                                                                                                                                 │
7  2 ─      invoke Main.error("Lol"::String)::Union{}                                                                                                         │
   └──      unreachable                                                                                                                                       │
10 3 ─      return %1
```

and with this pass, becomes

```
2  1 ─ %1  = %new(Base.RefValue{Any})::Base.RefValue{Any}                                                                                                     │╻╷ Ref
3  │   %2  = %new(Main.:(var"#13#14"))::Core.Const(var"#13#14"())                                                                                             │
   │   %3  = $(Expr(:foreigncall, :(:jl_get_ptls_states), Ptr{Nothing}, svec(), 0, :(:ccall)))::Ptr{Nothing}                                                  │╻  finalizer
   │         $(Expr(:foreigncall, :(:jl_gc_add_finalizer_th), Nothing, svec(Ptr{Nothing}, Any, Any), 0, :(:ccall), :(%3), :(%1), :(%2), :(%3)))::Nothing      ││
5  │         Base.setfield!(%1, :x, _3)::String                                                                                                               │╻╷ setindex!
6  └──       goto #3 if not _2                                                                                                                                │
7  2 ─ %10 = $(Expr(:foreigncall, :(:jl_get_current_task), Ref{Task}, svec(), 0, :(:ccall)))::Ref{Task}                                                       │
   │         $(Expr(:foreigncall, :(:jl_finalize_th), Nothing, svec(Any, Any), 0, :(:ccall), :(%10), :(%1)))::Nothing
   │         invoke Main.error("Lol"::String)::Union{}
   └──       unreachable                                                                                                                                      │
10 3 ─       return %1
```

I've updated the core logic with some debugging statements to help me figure out why this isn't working in certain cases (specifically, we're failing bootstrap right now); they will be removed once the code is functioning correctly.

If anyone has ideas for what I'm doing wrong, I would appreciate any feedback :slightly_smiling_face:

**Comment by maleadt** [comment]
> the counter-argument against directly calling the finalizer thunk is that users may not have written their finalizers such that they can be safely called in the same scope as the allocation (for example, if the finalizer takes a non-reentrant lock that is already held in the allocation scope).

FWIW, for CUDA.jl it'd be advantageous to free in the same scope, because IIUC that means using the same task, which has the effect that memory operations can be ordered against the task-local stream. If they get executed in the finalizer's task, that means using a global stream and ordering against all streams.

Are packages currently doing such resource handling in finalizers, given we don't have https://github.com/JuliaLang/julia/issues/35689?

**Comment by jpsamaroo** [comment]
> Are packages currently doing such resource handling in finalizers, given we don't have https://github.com/JuliaLang/julia/issues/35689?

Yes, MemPool.jl is using a global non-reentrant lock (taken from CUDAdrv/CUDAnative originally), which is taken during allocation, and during finalization. I wouldn't mind changing it to a regular `ReentrantLock` if this is considered to be an unsupported pattern (I'm not sure if it really needs to be non-reentrant anymore, now that we disable finalizers while taking locks; @krynju).

**Comment by chflood** [comment]
In principal I love the idea of escape analysis stack allocating objects that go away without garbage collector intervention however objects with finalizers pose special issues that I don't fully understand.

I'm still learning Julia so please indulge my questions.  Does Julia have a rule about finalizers running exactly once like Java does?  Can a finalizer bring an object back to life by stashing it somewhere?  My concern is that the GC might accidentally run a finalizer again on a zombie object.

There are also memory model issues in Java as detailed [here](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.32.4630&rep=rep1&type=pdf) which may or may not be applicable to Julia.   If you run the finalizer without some sort of memory barrier is it possible that instructions may be reordered in incorrect ways?  GC provides that memory barrier.

**Comment by jpsamaroo** [comment]
It appears to me that the current implementation of `finalize` ends up calling all finalizers for the object directly (instead of queuing them for later), meaning that finalizers must be safe to execute immediately in allocation scope if this pass calls `finalize`. Is this something that we want to assume for finalizers? Or do we want to assume that finalizers must be executed outside of allocation scope, and thus change the approach in this PR to using a delayed approach?

**Comment by yuyichao** [comment]
> I agree with adding this fast-path; would it be reasonable to punt that to a future PR, or do you want to see that done here before this is considered for merge?

C api should be fairly straightforward as well. The issue with the pr as is is that it will introduce regression.

> Can a finalizer bring an object back to life by stashing it somewhere?

yes.

> My concern is that the GC might accidentally run a finalizer again on a zombie object.

no that is not supposed to happen, each finalizer will run only once. It is removed from the list before being called.

> Is this something that we want to assume for finalizers? 

not just that, finalizer can run at any time that a gc can run. There were proposals about running hem on separate thread but it is not done and still have issues regarding gc triggered on the finalizer thread.

**Comment by jpsamaroo** [comment]
Abandoned in favor of #45272

**Pull request closed without merging**
