### PR TITLE
Ignore line number node when counting expressions for inlining

### LINKED ISSUE #13551: Broken inlining
Seems that inlining is broken on the current master.

Tested using the [test script](https://github.com/yuyichao/explore/blob/3805e1694be12efad8eda621baf25f1a16f167dc/julia/simd_complex/test.jl) for https://github.com/JuliaLang/julia/pull/13286 .

For bad commit, the `code_typed` clearly shows that many simple functions are not inlined.

Bisected to a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9
```
a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9 is the first bad commit
commit a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Wed Oct 7 16:35:53 2015 -0400

    preserve inline line numbers during inlining

:040000 040000 d51f01700bc9077c02bb204a541e6746967a4617 423dc659aee3291be27807b8f0f23cab918241d1 M        base
```

Bisect log
```
git bisect start
# bad: [af71b86edde26e607fc95fd8a8e73075ef675745] Do not pass RTLD_DEEPIND to dlopen in asan mode
git bisect bad af71b86edde26e607fc95fd8a8e73075ef675745
# good: [b5bebf2b05f63ad11f19a252cff2244a719337e8] Merge pull request #13453 from matthieugomez/patch-1
git bisect good b5bebf2b05f63ad11f19a252cff2244a719337e8
# bad: [646ea37c810c0f6e8c099b3d7f1c45f96b66fe6d] Merge pull request #13491 from JuliaLang/jn/lineno_fixes
git bisect bad 646ea37c810c0f6e8c099b3d7f1c45f96b66fe6d
# good: [930e6b55327c6caf60d0eae4d71ffdf43e55fbae] set a min target architecture of pentium4 to require support for sse2 and _mm_pause
git bisect good 930e6b55327c6caf60d0eae4d71ffdf43e55fbae
# good: [fb4b161ece65a6e48451f97aa2bfd0ba986b2709] Merge pull request #13478 from wildart/fix-13375
git bisect good fb4b161ece65a6e48451f97aa2bfd0ba986b2709
# good: [0d923f917d2269f25b9173ca56c9fce06542ed33] Merge pull request #13489 from KristofferC/kc/amulbdoc
git bisect good 0d923f917d2269f25b9173ca56c9fce06542ed33
# bad: [af81d6c7fe09f57ab268ccd731bc2d2f4aee9a95] fix #922 (wrong line numbers in error expressions) and remove old hacks around this issue
git bisect bad af81d6c7fe09f57ab268ccd731bc2d2f4aee9a95
# bad: [a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9] preserve inline line numbers during inlining
git bisect bad a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9
# first bad commit: [a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9] preserve inline line numbers during inlining
```

Noticed that this is already caught by @andreasnoack in the [commit comment](https://github.com/JuliaLang/julia/commit/a33cd07f8a0fe2dd4ef3fecf809add2bb2a493c9#commitcomment-13687800) after the bisect. I decided to post it anyway since there doesn't seems to be an issue for it yet.

cc @vtjnash

### PR DESCRIPTION
**Pull request by yuyichao**
Feels a little like a band-aid but I think this is the right logic.

Fix #13551.

### CODE REVIEW

**Comment by yuyichao** [comment]
CI failure is https://github.com/JuliaLang/julia/issues/11553 ....

**Comment by yuyichao** [comment]
CI restarted.

Also cc @vtjnash, could you have a look at this please?

**Comment by vtjnash** [comment]
it looks fine, although in general, it would be nice to be reducing the inlining threshold as that should result in slightly reduced compile times. this is likely only addressing a particular symptom of a different problem, not the actual problem.

**Comment by yuyichao** [comment]
> this is likely only addressing a particular symptom of a different problem, not the actual problem.

Hmm. I don't think I quite understand what you mean. This should only revert the inlining threshold to the old value and that's AFAIK the problem. Or do you mean that the change in inlining threshold shouldn't have such a big effect?

For the test code I had above, one of the biggest problem is that `*(::Complex{Float32}, ::Complex{Float32})` isn't inlined. Just looking at the function body, before the line number node filter change, the function body only has one expression. After the change, the function body has 20 expressions of which 19 are line numbers from random files (`complex.jl`, `float.jl`, `essentials.jl` to name a few). I'd be shocked if this alone is not enough to cause the problem

> it looks fine, although in general, it would be nice to be reducing the inlining threshold as that should result in slightly reduced compile times.

Agree if we have a way to change that locally (for SIMD) and if non-inlined function don't have a huge performance penalty because of spatting (gc frame and boxing).

**Comment by yuyichao** [comment]
> I'd be shocked if this alone is not enough to cause the problem

On the other hand, I would totally agree if the "actual problem" you meant is the duplicated line numbers in the function body. (only one of them would be useful anyway and they takes a lot of memory to store)

**Comment by yuyichao** [comment]
Should we at least also try to filter out the excessive line number node? On one hand they might be useful to construct a more complete backtrace (need to extend the debug info to do that) but on the other hand, they are not really accurate either. Even the current one can still be really confusing sometimes. For example, in the following code (put `f` and `g` in different functions can show this better),

```
f(x) = 1 ÷ x
g(x) = 1
@noinline k(x, y) = (x, y)
l(x) = k(f(x), g(x))

l(0)
```

Although the error is clearly thrown from `f(x)`, the backtrace will show that it's inlined from `g` because `g` is inlined later and therefore overrides the debug info from `f`.

**Comment by vtjnash** [comment]
ok, it sounds like we should put back the line number filter, but now only remove nodes that don't match the file-name/line-numbers of the original function. or we would need to make our line number handling look more like the llvm DlInfo nodes, with explicit tracking of scope on each one.

**Comment by yuyichao** [comment]
I guess that would help but it will probably still effectively reduce the inlining threshold by up to a factor of 2?

**Comment by vtjnash** [comment]
it can be done in addition to this PR. the threshold computation is roughly 6 lines with an average of 16 nodes per line.

**Comment by yuyichao** [comment]
Thanks for the comments.

> it can be done in addition to this PR

I'll take this as OK to merge. I've been carrying this patch in the my julia version and for the few benchmarks I've run, it seems that the performance is back to where it should be. Will merge some sometime tomorrow if there's no objections.

**Comment by tkelman** [comment]
If #13491 is going to be backported, then this should be too.

**Pull request merged**
