### PR TITLE
WIP: Backports 1.6-beta

### LINKED ISSUE #38491: abspath bug for relative directories
A bit of an edge case, but noticed this when looking at https://github.com/JuliaLang/julia/issues/23646 

Assume the current directory is `C:\Users\Mus\x`
```
julia> abspath("C:x")
"C:\\Users\\Mus\\x"  # correct


julia> abspath("X:x")
"X:x"  # should be "X:\x"
```

### LINKED ISSUE #38888: Inner constructor type constraint fails with UndefVarError in iteration
Consider the following bit of code:

```julia
struct MyStruct{T}
    x::T
    function MyStruct(x::S) where S<:Int
        new{S}(x)
    end
end
n = 3
# MyStruct(n) # works if you uncomment this line
[MyStruct(n) for i=1:3]
```
This will fail with an `UndefVarError: S not defined`. Once this error is thrown, it is not possible to construct `MyStruct` anymore. However, when restarting Julia constructing an instance of `MyStruct` in global scope works. If you then execute the list comprehension it also works.
Note that the same happens if you use a function instead of the list comprehension, inside of which `MyStruct(n)` is called, so I guess it's related to scoping.

A simple workaround is to relax the type constraint, e.g. `S<:Integer` works as expected. Still, it's strange that the list comprehension works when `MyStruct` is constructed in global scope before.

Version info:
```julia
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs.
- [x] #38804 - Switch back to LLVM ORC v2, take two
- [x] #38899 - fix #38888, pessimistic sparam inference with concrete upper bound
- [x] #38954 - minor inferrability tweak for `manifest_deps_get`
- [x] #38950 - Repair jl_init.
- [x] #38960 - [Artifacts] Note the platform we're looking for in our error message
- [x] #38975 - Assert that _artifact_str returns a String
- [x] #38958 - Construct constant LLVMPtr correctly
- [x] #38980 - Fix trampoline on PPC
- [x] #38496 - Update the AST docs on `nothing` `:method` expressions
- [x] #38800 - [loader] Must invalidate `.o` files when `VERSION` changes
- [x] #38962 - Source tarballs should contain `StdlibArtifacts.toml` files 
- [x] #38933 - Carry MBedTLS patch that works around CMake 3.18.2 bug.
- [x] #38942 - win: Set correct folder permissions after folder creation
- [x] #38938 - Fix symbol trampolines for OSX and export `jl_n_threads`
- [x] #39038 - [libuv] Bump to include `DELETE` win ACL patch
- [x] #39097 - Bump Documenter to 0.26.1
- [x] #39009  - Improve consistency of SONAME usage, fix debug installation 
- [x] #37741 - Fixes for non-Int based lengths
- [x] #39052  - Various fixes to trampolines for embedding on Windows 
- [x] #35539 - Test suite tweaks for rr
- [x] #37723 -  Fix cross-compilation of libjulia 
- [x] #38915 - Measure compile time only when using time macros pt.2: handling when code under test throws
- [x] #39112 - fix Meta.partially_inline! again 

Non-merged PRs with backport label:
- [ ] #38981 - Fix #38491: fix an abspath() edge case on Windows
- [ ] #38775 - [Make] remove BINARYBUILDER_LLVM_ASSERTS and use LLVM_ASSERTIONS instead
- [ ] #38405 - Make Distributed.jl `Worker` struct thread-safe.

### CODE REVIEW

**Comment by musm** [comment]
Note there was a discussion whether https://github.com/JuliaLang/julia/pull/38804 should be backported or not, but generally seemed like a good decision to go ahead with it to minimize the difficulty of backported bugfixes in the future. Wanted to note that here in case it is decided against.

**Comment by Sacha0** [comment]
Backport for #38933: https://github.com/JuliaLang/julia/pull/38968

**Comment by Sacha0** [comment]
Backport for #38962: https://github.com/JuliaLang/julia/pull/38969

**Comment by Sacha0** [comment]
tester_linuxaarch64 failure:
```
Error in testset REPL:
Error During Test at /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:21
  Got exception outside of a @test
  LoadError: LoadError: "hard kill repl test"
  Stacktrace:
    [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
      @ Base ./task.jl:705
    [2] wait
      @ ./task.jl:764 [inlined]
    [3] wait(c::Condition)
      @ Base ./condition.jl:106
    [4] (::Main.Test21Main_REPL.REPLTests.var"#18#23")(stdin_write::Base.PipeEndpoint, stdout_read::Base.PipeEndpoint, repl::REPL.LineEditREPL)
      @ Main.Test21Main_REPL.REPLTests /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/repl.jl:109
    [5] fake_repl(f::Any; options::REPL.Options)
      @ Main.Test21Main_REPL.REPLTests /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/repl.jl:54
    [6] top-level scope
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/repl.jl:93
    [7] include(mod::Module, _path::String)
      @ Base ./Base.jl:386
    [8] include(x::String)
      @ Main.Test21Main_REPL.REPLTests /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/runtests.jl:3
    [9] top-level scope
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/runtests.jl:4
   [10] include
      @ ./Base.jl:386 [inlined]
   [11] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:24 [inlined]
   [12] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1147 [inlined]
   [13] macro expansion
      @ /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:23 [inlined]
   [14] macro expansion
      @ ./timing.jl:354 [inlined]
   [15] runtests(name::String, path::String, isolate::Bool; seed::UInt128)
      @ Main /buildworker/worker/tester_linuxaarch64/build/share/julia/test/testdefs.jl:21
   [16] (::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:278
   [17] run_work_thunk(thunk::Distributed.var"#106#108"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:63
   [18] macro expansion
      @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:278 [inlined]
   [19] (::Distributed.var"#105#107"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed ./task.jl:406
  in expression starting at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/repl.jl:93
  in expression starting at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.6/REPL/test/runtests.jl:3
```
Is that one known?

**Comment by Sacha0** [comment]
tester_macos64 failures appear to be network failures in the Download tests ("could not connect to server while..." and such).

**Comment by Sacha0** [comment]
> Is that one known?

Looks like: https://github.com/JuliaLang/julia/issues/38996#issuecomment-751166975

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/38949#issuecomment-751521726):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`/home/nanosoldier/workdir/jl_9BfKFF/julia -e 'VERSION >= v"0.7.0-DEV.3656" && using Pkg; Pkg.update()'`, ProcessExited(1)) [1]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/b399cb88a078a6cfc899aef2de0acf8c402b208f/benchmark/by_hash/a12c53f_vs_ebcc603/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38949#issuecomment-751521696) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/b2484a7_vs_ebcc603/report.md). cc @maleadt

**Comment by rai-nhdaly** [comment]
The `tester_linux32` build seems to have failed due to a problem with the `rr_jll` artifact (which gets installed during the build?):
https://build.julialang.org/#/builders/4/builds/7464/steps/5/logs/stdio
```julia
  Activating new environment at `/tmp/jl_qS2Pew/Project.toml`
    Updating registry at `~/.julia/registries/General`
   Resolving package versions...
Updating `/tmp/jl_qS2Pew/Project.toml`
  [e86bdf43] + rr_jll v5.4.1+5
Updating `/tmp/jl_qS2Pew/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.1.3
  [3576fdfd] + capnproto_jll v0.7.0+1
  [e86bdf43] + rr_jll v5.4.1+5
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
Precompiling project...
  ��� Zlib_jll
  ��� MbedTLS_jll
  ��� CompilerSupportLibraries_jll
  ��� JLLWrappers
  ��� LibSSH2_jll
  ��� capnproto_jll
  ��� rr_jll
7 dependencies successfully precompiled in 4 seconds
   Resolving package versions...
Updating `/tmp/jl_qS2Pew/Project.toml`
  [3161d3a3] + Zstd_jll v1.4.5+2
Updating `/tmp/jl_qS2Pew/Manifest.toml`
  [3161d3a3] + Zstd_jll v1.4.5+2
Precompiling project...
  ��� Zstd_jll
1 dependency successfully precompiled in 1 seconds (7 already precompiled)
ERROR: LoadError: UndefVarError: rr not defined
Stacktrace:
 [1] getproperty
   @ ./Base.jl:26 [inlined]
 [2] rr
   @ /buildworker/worker/tester_linux32/build/rr_capture.jl:24 [inlined]
 [3] (::var"#1#7")(dir::String)
   @ Main /buildworker/worker/tester_linux32/build/rr_capture.jl:25
 [4] mktempdir(fn::var"#1#7", parent::String; prefix::String)
   @ Base.Filesystem ./file.jl:729
 [5] mktempdir(fn::Function, parent::String)
   @ Base.Filesystem ./file.jl:727
 [6] top-level scope
   @ /buildworker/worker/tester_linux32/build/rr_capture.jl:17
in expression starting at /buildworker/worker/tester_linux32/build/rr_capture.jl:17
```

Here's the line that's failing, complaining that `rr_jll.rr` is not defined:
https://github.com/JuliaCI/julia-buildbot/blob/658e7bebd01be0e05a6cd5f6ce4d7171e0e8776b/commands/rr_capture.jl#L24

```julia
    rr(func) = Base.invokelatest(rr_jll.rr, func; adjust_LIBPATH=false)
```

**Comment by KristofferC** [comment]
I think that should be fixed by now.

**Comment by rai-nhdaly** [comment]
Oh good! :) Thanks. So we just need to wait for the next build? Or is it possible to retry the build or something?

**Comment by musm** [comment]
Could we backport https://github.com/JuliaLang/julia/commit/684d5fc7b15c762d50fb907c72cc01c68230a4d6 ?

**Comment by ianshmean** [comment]
https://github.com/JuliaLang/julia/pull/38915 is now approved

**Comment by simeonschaub** [comment]
I don't want to hold this up, but any chance I could still sneak https://github.com/JuliaLang/julia/pull/39112 into the beta? I am fairly confident that will give us a working Cassette again, which will probably fix quite a few packages.

**Pull request merged**
