### PR TITLE
kron for sparse vectors

### PR DESCRIPTION
**Pull request by jebej**
I'm guessing we probably want this in base so I'm putting this here for comments.

~Needs tests.~

### CODE REVIEW

**Comment by jebej** [comment]
any comments on whether this is desired and if this is the right way to do it?

**Comment by tkelman** [comment]
Seems reasonable (modulo #22733 behavior with non-finite elements), but looks like there are ambiguities that will need to be resolved

**Comment by jebej** [comment]
I can't tell what the ambiguity is here, would you mind explaining?

**Comment by nalimilan** [comment]
Sorry for the delay. Do not hesitate to bump the PR if you don't get a reply after a few days.

The failure of the `ambiguous` test means that some methods are ambiguous. Unfortunately the log isn't very explicit, but by running the test locally I could find that changing the signature of the two last methods to:
```
kron(A::AbstractVector, B::SparseVector{Tv, Ti}) where {Tv, Ti} = ...
kron(A::SparseVector{Tv, Ti}, B::AbstractVector) where {Tv, Ti} = ...
```
fixes the problem. This sounds like a bug in the ambiguity detection algorithm to me, but waiting for somebody to confirm this better add the type parameters to work around the problem.

**Comment by jebej** [comment]
I'll fix this today. Any ideas for tests? Should I just make a few examples with hardcoded vectors?

**Comment by jebej** [comment]
The kron tests for sparse matrices relied on the dense implementation, so I just did the same thing here.

**Review by andreasnoack — APPROVED** [review]

**Comment by andreasnoack** [comment]
@jebej Is this good to go?

**Comment by jebej** [comment]
yes, this can be merged.

**Pull request merged**
