### PR TITLE
Fix interaction between try/catch elision and scope handling

### PR DESCRIPTION
**Pull request by Keno**
Currently, our try/catch elision code does not look at whether the EnterNode has a scope, and just deletes it, if it can prove the contents nothrow. This is obviously problematic, so this fixes that case up to instead set the catch dest to 0 in that case (along with support in the rest of the system to ignore such catch dests for the purpose of renaming). The idea is that a later pass could use the notasklocalstate effect to delete this after appropriate verification, but this is not implemented. Additionally, this currently bails on folding current_scope inside such try/catch regions - for such regions we cannot use the CFG to determine the extent of the try/catch region. A proper treatment of this would probably be to just treat this as a single value mutable - but again this is not implemented. The primary purpose of this patch is to ensure correctness.

### CODE REVIEW

**Review by aviatesk — COMMENTED** [review]
The implementation LGTM.

> Additionally, this currently bails on folding
> current_scope inside such try/catch regions - for such regions
> we cannot use the CFG to determine the extent of the try/catch
> region.

Rather than using 0 as a special token, I'm thinking we could wrap the original `catch_dest` in a data structure that can be recognized from the C-side, such as `QuoteNode`. This would allow the system to overlook it while still utilizing the original `catch_dest` information within CFG computation, enabling effective folding of `current_scope`? However, this may not be a critical issue, so perhaps we would want to set it aside as future work.

**Comment by Keno** [comment]
I thought about it, but we don't infer the catch block at all if we can tell that the try block is nothrow, so we'd be retaining a block (or possibly multiple) that were not inferred. We could probably do some CFG surgery to insert a fake new catch dest block that branches to any :leave instructions, but that doesn't seem great either. The current CFG-based current-scope folding relies on the structure of the try/catch-lowering that we happen to produce (in particular no code between the :leave and the branch to the common exit block), but there isn't really anything that would enforce this invariant on the IR, so I think taking the time to write a proper solution for this is worth it regardless.

**Comment by aviatesk** [comment]
Apparently, this PR is triggering a test failure in Pkg.jl and an internal error in the scopedvalues test.
Example failed CI log: https://buildkite.com/julialang/julia-master/builds/31320#018c81cf-a26e-4446-9f8f-b54218c7a293

**Comment by Keno** [comment]
Will take a look. Clearly some interaction with something else that happened on master.

**Comment by Keno** [comment]
Alright, found it. PR incoming.

**Comment by aviatesk** [comment]
Thanks.

**Pull request merged**
