### PR TITLE
[PPC] Remove Julia address-spaces before machine codegen

### LINKED ISSUE #45019: Cant generate julia-1.8.0-beta3 on powerpc (ppc64le) in LLVM generation
Trying to `make` julia-1.8.0-beta3 from source (`julia-1.8.0-beta3-full.tar.gz`) on PowerPC (ppc64le), I get the following error
```
Sysimage built. Summary:
Total ─────── 103.591980 seconds
Base: ───────  41.754413 seconds 40.3066%
Stdlibs: ────  61.835644 seconds 59.6915%
Warning: git information unavailable; versioning information limited
    JULIA usr/lib/julia/sys-o.a
Generating REPL precompile statements... 40/40
Executing precompile statements... 2016/2061
Precompilation complete. Summary:
Total ─────── 180.627899 seconds
Generation ── 133.111079 seconds 73.6935%
Execution ───  47.516820 seconds 26.3065%
Intrinsic has incorrect argument type!
void ({} addrspace(10)*)* @llvm.ppc.cfence.p10sl_s
Intrinsic has incorrect argument type!
void ({} addrspace(10)*)* @llvm.ppc.cfence.p10sl_s
in function julia_put_buffered_59286
LLVM ERROR: Broken function found, compilation aborted!

signal (6): Aborted
in expression starting at none:0
gsignal at /lib64/power9/libc.so.6 (unknown line)
abort at /lib64/power9/libc.so.6 (unknown line)
_ZN4llvm18report_fatal_errorERKNS_5TwineEb at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm18report_fatal_errorEPKcb at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN12_GLOBAL__N_118VerifierLegacyPass13runOnFunctionERN4llvm8FunctionE at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/../lib/libLLVM-13jl.so (unknown line)
operator() at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/src/aotcompile.cpp:541 [inlined]
jl_dump_native_impl at /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/src/aotcompile.cpp:552
Allocations: 163850041 (Pool: 163771637; Big: 78404); GC: 133
/bin/sh: line 1: 1532746 Aborted                 (core dumped) JULIA_BINDIR=/m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin WINEPATH="/m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin;$WINEPATH" JULIA_NUM_THREADS=1 /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/bin/julia -O3 -C "native" --output-o /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/lib/julia/sys-o.a.tmp --startup-file=no --warn-overwrite=yes --sysimage /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/lib/julia/sys.ji /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/contrib/generate_precompile.jl 1
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [sysimage.mk:89: /m100/home/userexternal/jdavid00/j180b3/julia-1.8.0-beta3/usr/lib/julia/sys-o.a] Error 1
make: *** [Makefile:88: julia-sysimg-release] Error 2

real    15m42.891s
user    12m46.399s
sys     2m27.137s
```
Seeing *** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. *** , I tried it both without any success, same error each time.

I am stuck, as I could generate previous version without trouble, cf.
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635* (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (powerpc64le-unknown-linux-gnu)
  CPU: POWER9, altivec supported
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, pwr9)
Environment:
  JULIA_HDF5_LIBRARY_PATH = /cineca/prod/opt/libraries/hdf5/1.10.6/gnu--8.4.0/lib
  JULIA_EDITOR = vi

```
I also tried with latest (julia-1.9.0-dev) version (github cloned), it also errors in LLVM, but slightly differently
```
Sysimage built. Summary:
Total ───────  98.499731 seconds
Base: ───────  38.779036 seconds 39.3697%
Stdlibs: ────  59.718697 seconds 60.6283%
    JULIA usr/lib/julia/sys-o.a
Generating REPL precompile statements... 40/40
Executing precompile statements... 1888/1919
Precompilation complete. Summary:
Total ─────── 162.544161 seconds
Generation ── 120.498513 seconds 74.1328%
Execution ───  42.045648 seconds 25.8672%
Intrinsic has incorrect argument type!
void ({} addrspace(10)*)* @llvm.ppc.cfence.p10sl_s
Intrinsic has incorrect argument type!
void ({} addrspace(10)*)* @llvm.ppc.cfence.p10sl_s
in function julia_put_buffered_32809
LLVM ERROR: Broken function found, compilation aborted!

signal (6): Aborted
in expression starting at none:0
gsignal at /lib64/power9/libc.so.6 (unknown line)
abort at /lib64/power9/libc.so.6 (unknown line)
_ZN4llvm18report_fatal_errorERKNS_5TwineEb at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm18report_fatal_errorEPKcb at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN12_GLOBAL__N_118VerifierLegacyPass13runOnFunctionERN4llvm8FunctionE at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
operator() at /m100/home/userexternal/jdavid00/jlatest/julia/src/aotcompile.cpp:545 [inlined]
jl_dump_native_impl at /m100/home/userexternal/jdavid00/jlatest/julia/src/aotcompile.cpp:556
Allocations: 115905935 (Pool: 115818693; Big: 87242); GC: 153
/bin/sh: line 1: 86592 Aborted                 (core dumped) JULIA_BINDIR=/m100/home/userexternal/jdavid00/jlatest/julia/usr/bin WINEPATH="/m100/home/userexternal/jdavid00/jlatest/julia/usr/bin;$WINEPATH" JULIA_NUM_THREADS=1 /m100/home/userexternal/jdavid00/jlatest/julia/usr/bin/julia -O3 -C "native" --output-o /m100/home/userexternal/jdavid00/jlatest/julia/usr/lib/julia/sys-o.a.tmp --startup-file=no --warn-overwrite=yes --sysimage /m100/home/userexternal/jdavid00/jlatest/julia/usr/lib/julia/sys.ji /m100/home/userexternal/jdavid00/jlatest/julia/contrib/generate_precompile.jl 1
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [sysimage.mk:89: /m100/home/userexternal/jdavid00/jlatest/julia/usr/lib/julia/sys-o.a] Error 1
make: *** [Makefile:88: julia-sysimg-release] Error 2

real    19m59.439s
user    12m45.828s
sys     2m25.043s
```

### PR DESCRIPTION
**Pull request by vchuravy**
Might fix #45019

### CODE REVIEW

**Comment by staticfloat** [comment]
Looks like progress!  We're now failing on some float16 functions, I think.

https://buildkite.com/julialang/julia-buildkite/builds/571#01812575-c314-4cda-940b-8c96075ef79a/361-2629

```
float.jl
JIT session error: Symbols not found: [ __gnu_f2h_ieee, __gnu_h2f_ieee ]
Failure value returned from cantFail wrapped call
Failed to materialize symbols: { (JuliaOJIT, { julia_Float16_2934, jfptr_Float16_2935 }) }
UNREACHABLE executed at /cache/build/default-ppcbot2-0/julialang/julia-buildkite/usr/include/llvm/Support/Error.h:782!
```

**Comment by staticfloat** [comment]
Alright, I've got your PR here set to pull https://github.com/JuliaCI/julia-buildkite/pull/119 as its CI configuration; so you can push things to this branch and it will only test on ppc64le-linux-gnu and x86_64-linux-gnu for now.

**Comment by vchuravy** [comment]
So we are still generating:

```
Executing precompile statements... 1438/1919
Intrinsic has incorrect argument type!
void ({} addrspace(10)*)* @llvm.ppc.cfence.p10sl_s
```

:/

**Comment by vchuravy** [comment]
Huh. Address space 0 is also not allowed?

void ({}*)* @llvm.ppc.cfence.p0sl_s

**Comment by vchuravy** [comment]
x-ref #45249  and #45644

**Comment by giordano** [comment]
Is this PR superseded by #45755 or it's relevant anyway?

**Pull request closed without merging**
