### PR TITLE
workaround for a dict access from a finalizer bug for 0.4

### PR DESCRIPTION
**Pull request by amitmurthy**
same workaround as https://github.com/JuliaLang/julia/pull/14456 for 0.4

### CODE REVIEW

**Comment by tkelman** [comment]
The `cherry-pick -x` cross reference would be useful next time.

Not sure what's wrong on appveyor right now. I prefer running PkgEval before merging backports to 0.4 but I guess we can do this on its own first.

**Comment by amitmurthy** [comment]
Does cherry-pick work if there are merge conflicts? Or would you rather deal with it at merge time?

**Comment by tkelman** [comment]
cherry-pick puts you in the same merge-conflict-resolution state as a merge or a rebase would. It's not too big a deal, just good for cross-referencing when going through the branch history.

**Comment by amitmurthy** [comment]
Added a comment and rebased. Will merge once all green.

**Comment by tkelman** [comment]
Is there any need for this to be on release-0.4 immediately? If not, I'd rather leave this open longer to allow for PackageEvaluator to at least run with the equivalent change present on nightlies.

**Comment by amitmurthy** [comment]
No issues. Will leave it open. This closes https://github.com/JuliaLang/julia/issues/14295

Will just label it as backport-pending, so that it is not missed out.

**Comment by tkelman** [comment]
I'm about to start running pkgeval for 0.4.3, so I reserve the right to revert this if it turns out to cause any issues. Hopefully it won't.

**Pull request merged**
