### PR TITLE
[libjulia-codegen] export `jl_jit_total_bytes`

### LINKED ISSUE #43077: Base.jit_total_bytes broken
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.984 (2021-11-14)
 _/ |\__'_|_|_|\__'_|  |  Commit 81315807a5 (0 days old master)
|__/                   |

julia> Base.jit_total_bytes()
ERROR: could not load symbol "jl_jit_total_bytes":
dlsym(RTLD_DEFAULT, jl_jit_total_bytes): symbol not found
Stacktrace:
 [1] jit_total_bytes()
   @ Base ./timing.jl:85
 [2] top-level scope
   @ REPL[1]:1
```
Possibly another casualty of https://github.com/JuliaLang/julia/pull/41936? Best!

### PR DESCRIPTION
**Pull request by inkydragon**
fix #43077 

~~Is this function part of the julia API?~~
~~Should I add a test for it?~~

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Yes, I guess we might as well have at least a simple test like `@test Base.jit_total_bytes() >= 0`.

**Review by JeffBezanson — APPROVED** [review]

**Review by vtjnash — APPROVED** [review]

**Review by Sacha0 — APPROVED** [review]
Thanks @inkydragon! :)

**Comment by oscardssmith** [comment]
does this need a backport?

**Comment by inkydragon** [comment]
In 1.6.3 & 1.7.0-rc3, `Base.jit_total_bytes()` works fine.

**Pull request merged**
