### PR TITLE
Bump Statistics stdlib version

### LINKED ISSUE #202: Cannot compute median
MWE:
```julia
using Statistics
median( [1.2μm,1.4μm,1.8μm] )
ERROR: MethodError: no method matching middle(::Unitful.Quantity{Float64,𝐋,Unitful.FreeUnits{(μm,),𝐋,nothing}})
```

### PR DESCRIPTION
**Pull request by tlnagy**
Adds support for computing the median of Unitful numbers to `Statistics.jl`, fixes https://github.com/PainterQubits/Unitful.jl/issues/202

Bump @nalimilan (ref https://github.com/JuliaLang/Statistics.jl/pull/28)

### CODE REVIEW

**Review by nalimilan — APPROVED** [review]

**Comment by tlnagy** [comment]
bump

**Comment by nalimilan** [comment]
CI failures look unrelated.

**Comment by tlnagy** [comment]
Thanks! Will this make it into the 1.6 release?

**Comment by KristofferC** [comment]
yes

**Pull request merged**
