### PR TITLE
More tests for arrayops!

### PR DESCRIPTION
**Pull request by kshyatt**
My heart yearns to see `arrays.jl` switch from yellow to green on Coveralls. Added tests for a bunch of untested `throws`, some untested methods on `Array{Bool}`, and in-place `{c}transpose` between vectors and matrices.

### CODE REVIEW

**Comment by timholy** [comment]
@kshyatt, I'd offer you a paintbrush, but I see you've found a better way to make such color changes anyway.

**Comment by kshyatt** [comment]
@timholy I'm actually extremely bad at art so this is really my only hope of achieving pretty colours

**Comment by ViralBShah** [comment]
I love the increased test coverage. Is the coverage now accurate enough to add to README.md?

**Comment by ViralBShah** [comment]
@kshyatt I just gave you commit access. With that you can create branches on JuliaLang itself, and it will be a little bit easier as you make PRs and more of the yellows into greens.

**Comment by kshyatt** [comment]
@ViralBShah I think the test coverage is now accurate. There are a bunch of files in `pkg` that have no tests at all but from what I can see in `base` the tests look accurate. It might be worth putting a pro-tip in the README that Coveralls lets you view 50-100 files per page, because otherwise you have to click a lot. Also, thanks a lot!

**Pull request merged**
