### PR TITLE
bump Pkg version

### PR DESCRIPTION
**Pull request by KristofferC**
Contains the removal of the old artifacts code.

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by fredrikekre** [comment]
See #37592

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37602#issuecomment-693230656) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/441f3aea03f301d264a22ad9a5b0964761ead4ec/pkgeval/by_hash/832e104_vs_bfa7261/report.md). cc @maleadt

**Comment by fredrikekre** [comment]
@staticfloat the packages that failed in the report above looks like they need the same treatment as PackageCompiler.

**Pull request closed without merging**
