### PR TITLE
Link to `sort!` in the docs of `searchsorted*`

### PR DESCRIPTION
**Pull request by jishnub**
The keyword arguments are explained in `sort!`, and it would be good to know where to look. Also, I've added an example of how to use the `by` keyword argument in each case.

### CODE REVIEW

**Comment by jmichel7** [comment]
The examples of `searchsorted` with a function `by` are misleading. The fact is that contrary to intuition the function `by` is applied to the second argument. In the call
`searchsortedlast([1=>"one", 2=>"two", 4=>"four"], 3, by=first)`
it works because `first(3)==3`. But the call 
`searchsortedlast([:a=>"one", :b=>"two", :d=>"four"], :c, by=first)`
would not work. The proper second argument should be a pair like `:c=>0`.

**Comment by jishnub** [comment]
Thanks! That's a good catch. I've updated the examples now

**Review by LilithHafner — APPROVED** [review]
@knuesel has included very similar changes in #48387, but I prefer your example usage with `first` over @knuesel's example of `abs` because I think `first` is more likely to be used in practice.

I'd still like to hear @knuesel's thoughts on this.

**Comment by jishnub** [comment]
Ah, I had missed that PR. Since that is more comprehensive, perhaps this can be closed in favor of that after a decision on the example has been taken

**Comment by knuesel** [comment]
I also like @jishnub's example. Maybe we can merge this already and I'll remove the `abs` example when I update my draft PR?

**Pull request merged**
