### PR TITLE
Attempt at fixing #33413, crash with `cglobal(dlsym(...))`

### PR DESCRIPTION
**Pull request by jmert**
This is my attempt at fixing #33413.

I got around to investigating lowering by comparing the lowered form of similar functions using either `ccall` or `cglobal`. For instance, with `ccall` the `dlsym` expression is lowered to a series of calls (`%7`–`%9`) with the result fed back into the `:foreigncall`:

```julia
julia> function ccall_example()
           libh = Libdl.dlopen("libccalltest")
           return ccall(Libdl.dlsym(libh, :ctest), Complex{Int}, (Complex{Int},), 0+0im)
       end
ccall_example (generic function with 1 method)

julia> @code_lowered ccall_example()
CodeInfo(
1 ─ %1  = Libdl.dlopen
│         libh = (%1)("libccalltest")
│   %3  = Core.apply_type(Main.Complex, Main.Int)
│   %4  = 0 * Main.im
│   %5  = 0 + %4
│   %6  = Base.cconvert(%3, %5)
│   %7  = Libdl.dlsym
│   %8  = libh
│   %9  = (%7)(%8, :ctest)
│   %10 = Core.apply_type(Main.Complex, Main.Int)
│   %11 = Base.unsafe_convert(%10, %6)
│   %12 = $(Expr(:foreigncall, :(%9), Complex{Int64}, svec(Complex{Int64}), 0, :(:ccall), :(%11), :(%6)))
└──       return %12
)
```
whereas a similar `cglobal` function leaves the `dlsym` expression within the `cglobal` call:
```julia
julia> function cglobal_example()
           libh = Libdl.dlopen(libccalltest)
           return cglobal(Libdl.dlsym(libh, :global_var), Cint)
       end
cglobal_example (generic function with 1 method)

julia> @code_lowered cglobal_example()
CodeInfo(
1 ─ %1 = Libdl.dlopen
│        libh = (%1)(Main.libccalltest)
│   %3 = Main.cglobal(Libdl.dlsym(libh, :global_var), Main.Cint)
└──      return %3
)
```

By just grepping through the scheme files, I found a place where the `ccall` arguments appeared to be manipulated and duplicated the logic into the `cglobal` case a couple of lines later. (My scheme knowledge is nearly non-existent, so I arrived at the given solution through some trial and error, quick google searches, and pattern matching of surrounding code :grimacing: ) 

With this change to lowering, the `cglobal_example()` instead lowers to:
```julia
julia> @code_lowered cglobal_example()
CodeInfo(
1 ─ %1 = Libdl.dlopen
│        libh = (%1)(Main.libccalltest)
│   %3 = Libdl.dlsym
│   %4 = libh
│   %5 = (%3)(%4, :global_var)
│   %6 = Main.cglobal(%5, Main.Cint)
└──      return %6
)
```
where now lines `%3`–`%5` look a lot more like the lowered `ccall` form shown above.

There also didn't seem to be very many tests of `cglobal` in the tests, so I added several variations to try to just cover more cases.

### CODE REVIEW

**Comment by jmert** [comment]
The aarch64 jobs looks like it failed in the REPL with maybe some sort of hang.

The FreeBSD job did fail in the ccall test suite, but did so [here](https://github.com/JuliaLang/julia/blob/8987f7ac6d284cb512d336279a74b5414c635757/test/ccall.jl#L1722) when converting a C-string to `String`. My interpretation of the error is that the preceding `swprintf` actually failed and returned a length of `-1`, which I suppose could be broken by something I inadvertently changed, though that'd be unfortunate given it passed almost everywhere else (and I'm not setup to work interactively/debug on any non-Linux environment).

**Comment by musm** [comment]
@JeffBezanson would you like to review this or suggest someone who could ?

**Comment by musm** [comment]
maybe rebase to see if the freebsd failure is fixed (which it looks lit was on master)?

**Comment by fingolfin** [comment]
The macos failure looks unrelated? Maybe rebase or close&reopen to rerun tests?

**Comment by jmert** [comment]
Reminder bump.

**Comment by musm** [comment]
Who'd be good to review this ?

**Comment by jmert** [comment]
> Who'd be good to review this ?

@simeonschaub has a number of recent commits to `julia-syntax.scm` if JeffBezanson is otherwise occupied.

**Comment by vtjnash** [comment]
Part of this seems like an accidental feature (inherited from ccall) that we should probably change into an error, but this is likely needed anyways for handling some of the other cases

**Comment by musm** [comment]
If I understand what you are saying, do you mean that `ccall` should actually error when its first argument is a `dlsym` ?

**Comment by vtjnash** [comment]
yeah, it is a strange way to write an identity / convert function

**Pull request merged**
