### PR TITLE
Move 0.7 NEWS to HISTORY and add OldPkg moving out of repo to NEWS.

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
https://github.com/JuliaArchive/OldPkg.jl

**Comment by garrison** [comment]
Once this is merged, against what branch should pull requests to improve 0.7 NEWS be opened?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/tree/release-0.7 I think

**Comment by waldyrious** [comment]
It's unfortunate that the `NEWS.md` in the v1.0.0 tag does not contain at least a note to clarify why it doesn't list any changes other than the OldPkg one, and make it explicit that it effectively marks the stabilization of v0.7.

Could at least the [release page for 1.0.0](https://github.com/JuliaLang/julia/releases/tag/v1.0.0) be edited to point to v0.7's `NEWS.md` instead of (or at least in addition to) this nearly empty file? That would help make things less puzzling for historical reference. cc @ararslan.

(Note: this came up in the context of the [PR to add Julia to the endoflife.date project](https://github.com/endoflife-date/endoflife.date/pull/6645))

**Comment by ararslan** [comment]
Sure, I added an additional link to the 0.7 NEWS.md in the 1.0 release description.

**Pull request merged**
