### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by karajan9**

### CODE REVIEW

**Comment by sostock** [comment]
This is not a typo, “iff” is mathematical slang for “if and only if”.

Of course, we could still replace it by “if and only if” (I don’t know how widespread “iff” is outside of math, some users might not know it).

**Comment by KristofferC** [comment]
Probably worth to spell it out.

**Comment by karajan9** [comment]
Well, you have one data point right here, I thought it was a typo when I saw it. Then again, I'm a physicist 😉

**Comment by ViralBShah** [comment]
`iff` is pretty standard I thought, but no harm in spelling it out.

**Pull request merged**
