### PR TITLE
Remove quadgk and friends from Base

### PR DESCRIPTION
**Pull request by ararslan**
This PR removes `quadgk` as well as the `Base.QuadGK` submodule, now that [QuadGK.jl is its own registered package](https://github.com/JuliaLang/METADATA.jl/pull/7402). The approach taken here is mirrored after the approach taken for removing the primality functions.

cc @stevengj and @tkelman

### CODE REVIEW

**Comment by ararslan** [comment]
If I recall, @vtjnash had expressed concern over not having `quadgk` available to test inference. Let me know if there are any suitable substitutes that can be used in the tests. Alternatively, I've allowed edits from maintainers, so any maintainer is free to add replacement test code here as they see fit.

**Comment by tkelman** [comment]
The package will get tested nightly on PkgEval. I don't think I've ever seen the quadgk test fail myself, but maybe that only happens early in big inference refactorings. Since those are relatively rare, we should make it easier to run PkgEval on-demand for that kind of PR, like we do with nanosoldier for benchmarking. There's some work underway to make that possible.

**Comment by vtjnash** [comment]
> The package will get tested nightly on PkgEval. I don't think I've ever seen the quadgk test fail myself, but maybe that only happens early in big inference refactorings

It tests one aspect of convergence speed. Without specific tuning in inference, this code can take anywhere from several days (or weeks?) to infer, vs. computing the same answer in a fraction of a second.

**Review by tkelman — APPROVED** [review]

**Comment by jarvist** [comment]
On 0.5 I was `using` QuadGK and everything was hunky dory, but then,
```
julia> using QuadGK
julia> quadgk
WARNING: both QuadGK and Base export "quadgk"; uses of it in module Main must be qualified
ERROR: UndefVarError: quadgk not defined
```

Fixed by importing the quadgk function explicitly.
```
julia> import QuadGK.quadgk
julia> quadgk
quadgk (generic function with 3 methods)
```

Just thought I'd leave this here as a quick fix for anyone else who suddenly had their code break on 0.5 -> 0.6!

Some kind of guidance in the error message would be useful, particularly if these errors will become the new normal as core Julia slims down.

**Comment by ararslan** [comment]
Hey @jarvist, thanks for the report. Issues with particular packages should be reported on the package's repo. If you could open an issue at https://github.com/JuliaMath/QuadGK.jl, that would be great.

**Comment by jarvist** [comment]
OK, can do - but I think the key issue is that the deprecation warning:
```
julia> quadgk()
ERROR: quadgk() has been moved to the package QuadGK.jl.
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `using QuadGK`.
```
Is misleading, as:
```
julia> using QuadGK

julia> quadgk()
WARNING: both QuadGK and Base export "quadgk"; uses of it in module Main must be qualified
ERROR: UndefVarError: quadgk not defined
```
I assume that's because it's clashing with the deprecation warning itself?

**Comment by ararslan** [comment]
The handling of the exporting is an issue with the package.

**Comment by JeffBezanson** [comment]
Yes it looks like it's clashing with the deprecation definition. Unfortunate, but we can probably only fix this completely when the deprecation is removed.

**Comment by stevengj** [comment]
The deprecation message could be changed to:
```
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `import QuadGK: quadgk`.
```

**Pull request merged**
