### PR TITLE
Remove NEWS.md from the PDF of the manual

### PR DESCRIPTION
**Pull request by ViralBShah**
This removes the NEWS.md link at the bottom of the first page of the
manual. Given that we link to it prominently on top of the page, I
feel this is ok.

This will remove Section II of the PDF manual, where the release notes
take 15 pages (because ofthe way markdown gets converted to PDF).

Partial fix for #35495

### CODE REVIEW

**Comment by KristofferC** [comment]
Won't this break the link to the release notes in the html version=

**Comment by ViralBShah** [comment]
My understanding is that it won't generate the link to the release notes at the bottom of the page, but we still have the link to release notes on the top.

**Comment by ViralBShah** [comment]
Verified. With this commit, the link at the bottom goes to "Getting Started" instead of "NEWS".

**Comment by ViralBShah** [comment]
I'll merge this tomorrow unless there are objections.

**Comment by ViralBShah** [comment]
How often does the 1.6-Dev documentation on docs.julialang.org get generated/updated? The pdf there has a date of May 8.

**Comment by KristofferC** [comment]
This removed the NEWS section from the manual when you click release notes:

image

Pretty much what I meant with https://github.com/JuliaLang/julia/pull/36312#issuecomment-644874314.

**Comment by ViralBShah** [comment]
Please explain what you found misleading in the PR title. What more does it do than what it said?

I didn't realize the NEWS showed up in the menu - that's not how I understood your comment.  That UI is quite strange - but anyways, I can add that back.

**Comment by KristofferC** [comment]
It seems like it changes some headings in the PDF now as well.

**Comment by ViralBShah** [comment]
If something is wrong, let me know and I'll fix it in the PR I make to reinstate the release notes in the html version.

**Comment by KristofferC** [comment]
The pdf on the latest docs (if it has updated) looks like:

image

I don't know if it looked like that before?

**Comment by ViralBShah** [comment]
Where are you looking for the PDF on the latest docs?

**Comment by KristofferC** [comment]
Did it look fine on your local version?

**Comment by ViralBShah** [comment]
I think it did. But I am building again to see what happens.

**Comment by ViralBShah** [comment]
Before, there were 20 pages of Release notes, because of the way Markdown gets converted into latex. This removes the release notes from the PDF version, and merges the Introduction into the manual.

**Comment by ViralBShah** [comment]
I think you have an old PDF. This is what it looks locally.
Screen Shot 2020-06-17 at 4 42 34 PM

**Comment by KristofferC** [comment]
Yeah, I just got the one from the website which I guess hasn't updated.

**Comment by ViralBShah** [comment]
Right - it has the date of May 8, 2020. Something seems to have broken somewhere a while ago.

**Comment by ViralBShah** [comment]
The reason you see all those sections empty is because the NEWS file was probably empty after we branched.

**Comment by ViralBShah** [comment]
I wonder if `article` would be better than the `memoir` latex documentclass which is what Documenter is using.

**Comment by ViralBShah** [comment]
Follow-up PR https://github.com/JuliaLang/julia/pull/36333

**Pull request merged**
