### PR TITLE
Steps toward building Fedora ARM RPM

### PR DESCRIPTION
**Pull request by nalimilan**
Here are two patches I needed to apply to build Julia on Fedora armv7hl. The build still fails during bootstrap, though: https://kojipkgs.fedoraproject.org//work/tasks/26/9290026/build.log

The first patch implies that for some people patchelf will be built, while the system's version was used previously. It's a small tool, though, and it's the only dependency which is taken from the system by default. We could keep the current auto-detection behavior, but it wouldn't play well with `USE_SYSTEM_PATCHELF`. We could also have a `BUILD_PATCHELF` variable instead, but that's not consistent with other dependencies...

### CODE REVIEW

**Comment by tkelman** [comment]
+1

**Comment by nalimilan** [comment]
OK to merge?

**Comment by ViralBShah** [comment]
Go for it.

**Comment by ViralBShah** [comment]
We should also get rid of ARM.inc, and have ARM related code in the general Make scripts. The build process is largely sorted out, and lots of people are trying out ARM. The ARM related stuff is also quite small.

**Pull request merged**
