### PR TITLE
enable abstract interpreter to constant prop even if method source is generated

### PR DESCRIPTION
**Pull request by jrevels**
I made this change entirely because @vtjnash dreamed that he had already made me make this change, and was surprised to find that this was not the case in his wakeful reality

### CODE REVIEW

**Comment by Keno** [comment]
> I made this change entirely because @vtjnash dreamed that he had already made me make this change, and was surprised to find that this was not the case in his wakeful reality

More common than you think. I dreamed last night that @yuyichao had left a review comment on my #28251 PR asking for an LLVM-level test case of the new feature, but that comment is nowhere to be found.

**Comment by vtjnash** [comment]
Maybe it's a good thing it hadn't translated into reality. I'm really not sure that this is a good idea.

**Comment by jrevels** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by vtjnash** [comment]
we might want to do this if the Method spoofing bit is set in the CodeInfo, but we'll revisit that when we run into it

**Pull request closed without merging**
