### PR TITLE
Upgrade LLVM to 13.0.1

### PR DESCRIPTION
**Pull request by vchuravy**
https://github.com/llvm/llvm-project/compare/llvmorg-13.0.1...JuliaLang:julia-13.0.1-0

### CODE REVIEW

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44135#issuecomment-1036805190) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/a4e2cfb_vs_4409a1b/report.html).

**Comment by DilumAluthge** [comment]
@nanosoldier `runtests(["ExactOptimalTransport", "GaussBP", "GeometryPrimitives", "InformationGeometry", "InteractBase", "Juniper", "NonconvexMultistart", "Optim", "PathWeightSampling", "PowerSimulations", "Probably", "Reactive", "ScanImageTiffReader", "StateSpaceModels", "TensorKit", "TensorToolbox", "WavePropBase"], vs = ":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44135#issuecomment-1037071114) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/a4e2cfb_vs_0a91e71/report.html).

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/44135#issuecomment-1037326914) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/a5146e3_vs_4c101a1/report.md).

**Pull request merged**
