### PR TITLE
fix #30679, call correct method for `invoke` calls in `jl_invoke` fallback

### LINKED ISSUE #30679: StackOverflowError when creating RemoteChannels
I have noticed some strange behavior with RemoteChannel in 1.0.3, that did not occur for me in 1.0.2. I think I have identified a MWE. The following works:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 5)
```
However, if I import some module before the struct definition, the following happens:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> using JuMP

julia> @everywhere struct A end

julia> RemoteChannel(()->Channel{A}(1), 2)
ERROR: StackOverflowError:
deserialize(::Distributed.ClusterSerializer{Sockets.TCPSocket}, ::Type{RemoteChannel{Channel{A}}}) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:310 (repeats 100 times)
Stacktrace:
 [1] #remotecall_fetch#149(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:379
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:371
 [3] #remotecall_fetch#152(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function, ::Int64, ::Function, ::Vararg{Any,N} where N) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406
 [4] remotecall_fetch at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:406 [inlined]
 [5] RemoteChannel(::Function, ::Int64) at /usr/share/julia/stdlib/v1.0/Distributed/src/remotecall.jl:108
 [6] top-level scope at none:0
```
The error repeats consistently after consecutive attempts of `RemoteChannel(()->Channel{A}(1), 2)`, but if I run some code snippet involving the `A` type on the second node I can suddenly create channels again:
```julia
julia> @fetchfrom 2 A()
A()

julia> RemoteChannel(()->Channel{A}(1), 2)
RemoteChannel{Channel{A}}(2, 1, 16)
```
The error does not occur after any model import. For example, `MacroTools`, `Statistics` or seemingly any standard library does not lead to this error. Other large modules that I have tried that does lead to the error are `Plots` and `Distributions`. I have not found any common denominator between model imports that cause this error. My version info:
```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
fixes #30679

**Comment by Keno** [comment]
Can we concoct a test?

**Review by vtjnash — APPROVED** [review]

**Comment by JeffBezanson** [comment]
Test added.

**Comment by KristofferC** [comment]
Needs manual backport to 1.0.4 https://github.com/JuliaLang/julia/pull/30954

**Pull request merged**
