### PR TITLE
Print LLVM module when verification fails

### PR DESCRIPTION
**Pull request by pchintalapudi**
This should hopefully make it easier to identify why a particular piece of LLVM IR fails the verifier, and give more contextual clues as to the nature of the verification failure.

### CODE REVIEW

**Comment by inkydragon** [comment]
The error in analyzegc looks relevant:
https://buildkite.com/julialang/julia-master/builds/25942#01895d3e-b3fc-4405-9273-00114232c1a6/868-1313
```
/cache/build/default-amdci4-3/julialang/julia-master/src/jitlayers.cpp:1220:25: error: Calling potential safepoint as SimpleFunctionCall from function annotated JL_NOTSAFEPOINT [julia.GCChecker]
                assert(!verifyLLVMIR(M));
```

**Review by maleadt — APPROVED** [review]
LGTM

**Comment by pchintalapudi** [comment]
Theoretically `--print-on-crash` is supposed to be more helpful here, but iirc @gbaraldi had some issues with it.

**Comment by gbaraldi** [comment]
I think it didn't work at all for what I was trying to do :)

**Comment by vtjnash** [comment]
I didn't know about that. Looks like it landed at the end of 2021. That design seems extremely expensive, relatively to what I was proposing (useful enough, but essentially the same as print-before-all, while my proposal is entirely free), and won't handle large modules (like ours). The large modules issue was fixed in May by https://github.com/llvm/llvm-project/commit/eb9ba243722454c186134fc83449ce69906603ae. But we cannot enable LLVM's signal handlers. However, since LLVM now has this similar functionality, perhaps LLVM would be interested in having it do the printing when the verifier fails, like I wanted to propose.

**Pull request merged**
