### PR TITLE
Change some instances of literal `0` to `zero`/`iszero` in `SparseArrays`

### PR DESCRIPTION
**Pull request by mcognetta**
This PR changes a few more instances of literal `0`'s to the more appropriate `zero` or `iszero` method for when the eltype of the SparseArray cannot be compared directly with `0`.

See also #42536 for a recent issue related to this.

### CODE REVIEW

**Comment by andreasnoack** [comment]
I'm in favor of this but do see https://github.com/JuliaLang/julia/issues/30573 and the references linked in that issue.

**Comment by mcognetta** [comment]
Thanks for the references. I'll keep it in mind for future stuff.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42549#issuecomment-939237629) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/72489d7_vs_a0504ab/report.md).

**Comment by mcognetta** [comment]
@andreasnoack I think the empty ones are tests which have become inactive.

Among the ones under `Package has test failures` none seem to be related to this change.

**Comment by maleadt** [comment]
The logs shouldn't be empty though. I'll create an issue and have a look later on (or let me know when it needs to be resolved for this PR to make progress).

**Comment by mcognetta** [comment]
A very gentle bump.

**Review by stevengj — APPROVED** [review]

**Comment by andreasnoack** [comment]
This should now be moved to https://github.com/JuliaLang/SparseArrays.jl, right?

**Comment by KristofferC** [comment]
Nah, until the switch has actually happened, I think it is best to continue here.

**Comment by DilumAluthge** [comment]
We have moved the SparseArrays stdlib to an external repository.

Please open this PR against that repository: https://github.com/JuliaLang/SparseArrays.jl

Thank you!

**Pull request closed without merging**
