### PR TITLE
Some indices generalizations for linalg/generic

### PR DESCRIPTION
**Pull request by timholy**
This was also the occasion for #18031, but this version just keeps compatibility with what we currently have.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Can you explain this a little more? Is `length(AbstractArray)` deprecated in favor `_length(AbstractArray)`? Should `length` and/or `_length` not be used with `AbstractArray`s anymore?

**Comment by timholy** [comment]
Just for julia 0.5. See http://docs.julialang.org/en/latest/devdocs/offset-arrays/.

**Comment by andreasnoack** [comment]
I see. In the documentation, your suggestion is to use `length(linearindices(A))` instead of `length(A)` so would it make sense to use it here? Is the idea that in the future, when the code base has had some time to adjust to the new `AbtractArray` interface, `length` can again be used for extracting the number of elements in an array? If you stay with the `_length`, I think it makes sense to explain it in a comment.

**Comment by timholy** [comment]
It's equivalent, see how [`linearindices`](https://github.com/JuliaLang/julia/blob/99ef1f8e1794910d00ba07580a9820fae75ffb28/base/abstractarray.jl#L87) and [`_length`](https://github.com/JuliaLang/julia/blob/99ef1f8e1794910d00ba07580a9820fae75ffb28/base/abstractarray.jl#L121) are implemented. I guess the thing I like about `_length` is that it's search-and-replaceable and even `@deprecate`able (in case packages start calling it directly, though I'd strongly prefer if they just internally defined `_length(a) = length(linearindices(a))`.

I can add a comment if you like. Perhaps at the `using Base: _length` statement?

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18032#issuecomment-240036226) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6c12253b0bc36fc61f125e63ca3ef136e7aa7664/27b14c0_vs_62615c3/report.md). cc @jrevels

**Comment by andreasnoack** [comment]
I know but I think it would be useful with a comment such that, in the future, we'll know why we are using a non-exported and non-documented function to compute the number of elements in an array.

**Comment by timholy** [comment]
It's already there now, do you like it? Or should I move it somewhere else?

**Comment by andreasnoack** [comment]
I see. Thanks. I looked in the wrong file. It was something like that I had in mind.

**Comment by timholy** [comment]
Feel free to suggest further changes, or if none perhaps we can merge.

**Pull request merged**
