### PR TITLE
Only compute effect-free once

### PR DESCRIPTION
**Pull request by Keno**
At the moment, whenever a statement becomes unused the compiler
tries to determine whether that statement is effect free and
may thus be removed. This is wasteful, because effect-freeness
should be computable only from type information. This PR moves
that computation to the start of the IRCode construction phase
and caches the result in the flags array. Ideally, I'd like to
just propagate these kinds of flags interprocedurally during
inference, but I'd like to do this one step at a time.

### CODE REVIEW

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/33753#issuecomment-549095501) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9991301c88511ed06dabab898c5cf7e5ad0a16d8/6a0089f_vs_c7e4b99/report.md). cc @ararslan

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/33753#issuecomment-549209515) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/547bca485ae7eff5c454731018eff8e5bf746cf2/6d03339_vs_5294219/report.md). cc @ararslan

**Comment by vtjnash** [comment]
Makes sense to cache this analysis. For the NFCI parts of this PR (to pass around flags correctly), I recently wrote a branch to investigate handling an "Instruction" as a unit, with a goal of reducing the duplicate code for this sort of copy/update/set logic: https://github.com/JuliaLang/julia/compare/master...vtjnash:jn/opt-simplify. It should be fully functional and has been tested to generally optimize to the same operations we do now, though it's been languishing for a bit now.

**Comment by Keno** [comment]
I think a refactoring like probably makes sense regardless, but I'd like to get this in regardless. My plan here is to back out some of the more forward looking changes that are unused in this PR (like the `nothrow` field and the the distinction between the various IR flags) and then do those as a separate PR later once I actually put up the functionality that needs it. That way, we should be able to merge this reasonably quickly and get the perf benefit.

**Comment by vtjnash** [comment]
Sure, but should perhaps still be split between NFCI and changes? The other branch is also essentially done, and I'd like to get feedback on it.

FWIW, these bits are already semi-reserved (https://github.com/JuliaLang/julia/blob/d5d4c695b751b19d24602b80473d018bca5407a7/src/julia.h#L254-L257), so we need to think about whether we want to fit this into the remaining couple of bits or change the field also (duplicate it or grow it).

**Comment by Keno** [comment]
I think we should probably clear the effect_free bits when we serialize a CodeInfo to disk to avoid committing to a meaning for now.

**Comment by JeffBezanson** [comment]
Does this also need to be changed in dump.c and staticdata.c?

**Comment by Keno** [comment]
I guess the question is a question of how committed we are to cross version stability here. The problem with the `Serialization` format is that people store flux models with that that they need to load across versions, so we're trying hard to avoid breaking it. I don't think we have the same problems with .ji and sysimg files and we can just bump the serialization format version number on those if we decide to change the meaning of those flags.

**Comment by vtjnash** [comment]
Replaced by #40066

**Pull request closed without merging**
