### PR TITLE
lattice: fix minor lattice issues

### PR DESCRIPTION
**Pull request by aviatesk**
I found some lattice issues when implementing `MustAlias` under the new extendable lattice system in another PR.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47570#issuecomment-1314678521) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/3783e92_vs_d0559c1/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47570#issuecomment-1314720874) failed.

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/47570#issuecomment-1314726908) failed.

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47570#issuecomment-1314736115) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/6f5aeb5_vs_18e7f40/report.md).

**Pull request merged**
