### PR TITLE
[release-0.4, RFC] backports for 0.4.1

### PR DESCRIPTION
**Pull request by tkelman**
:steam_locomotive:

### CODE REVIEW

**Comment by tkelman** [comment]
Current omissions out of issues that have, or might soon have, the backport pending tag on them:

- [ ] #12429, I think there are some RST length-of-underline cleanups needed here
- [ ] #13299, would like confirmation first whether the fix should be backported
- [ ] #13491, caused a noticeable perf regression - partially fixed by
- [ ] #13553, not sure if it makes sense without the former
- [ ] #13803, caused some package breakage

**Comment by tkelman** [comment]
PackageEvaluator worked without any trouble here: https://gist.github.com/c5334204e9d611fe95ff

The BinDeps tests should work again after https://github.com/JuliaLang/BinDeps.jl/pull/185 is merged and tagged, due to running `deps/build.jl` in a separate process now (#13506).

FixedPointNumbers looked like a freeze, cc @timholy - would that maybe be fixed by #13803?

LibCURL failed on 0.4.0  with an `http_code` 503 instead of 200, I suspect that's an intermittent connection issue.

QuantEcon gives
```
running for /home/vagrant/.julia/v0.4/QuantEcon/test/test_lqnash.jl
ERROR: LoadError: LoadError: MethodError: `__LQ#17__` has no method matching __LQ#17__(::Int64, ::Type{Void}, ::Array{Float64,0}, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Float64,1}, ::Float64)
Closest candidates are:
  __LQ#17__(::Union{Array{T,N},T}, !Matched::Union{Int64,Void}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T}, ::Union{Array{T,N},T})
 in LQ at /home/vagrant/.julia/v0.4/QuantEcon/src/lqcontrol.jl:140
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from /home/vagrant/.julia/v0.4/QuantEcon/test/runtests.jl:30
 in anonymous at no file:0
 in anonymous at multi.jl:1341
 in run_work_thunk at multi.jl:646
 in run_work_thunk at multi.jl:655
 in anonymous at task.jl:58
while loading /home/vagrant/.julia/v0.4/QuantEcon/test/test_lqnash.jl, in expression starting on line 27
 in wait_ref at multi.jl:786
 in call_on_owner at multi.jl:778
 in wait at multi.jl:793
 in sync_end at ./task.jl:400
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/QuantEcon/test/runtests.jl, in expression starting on line 422
```
cc @spencerlyon2 any ideas what this is?

**Comment by spencerlyon2** [comment]
Yeah that one is a method error I fixed yesterday

Does PackageEvaluator run tests from tagged releases or the master branch.

**Comment by tkelman** [comment]
tagged releases

**Comment by spencerlyon2** [comment]
I'll tag a new patch with the bug fix later today unless anyone beats me to
it (feel free to tag if you want). Current master is good to go with
passing tests.

// Spencer

**Comment by tkelman** [comment]
So backports are intended not to be breaking, but here's the bisect log for the current tagged release of QuantEcon:

```
70018be2da560a75fb0712fef3f74c8db7a439bd is the first bad commit
commit 70018be2da560a75fb0712fef3f74c8db7a439bd
Author: Amit Murthy <amit.murthy@gmail.com>
Date:   Fri Oct 23 19:48:02 2015 +0530

    propagate errors on wait(::RemoteRef) and remotecall_wait

    (cherry picked from commit a2e7cf4ed0bc2b3ce2754b5ff9db8369835345cb)
    ref #13744

:040000 040000 e1fb72b40f50ed7d0f78fdc07ab911be7d973a17 9a8753dee538de8db924a8c98ca9e3333759cdc4 M      base
:040000 040000 fc98d1350ae3c5f329461c26055b91ceec97aa63 c80e7032f3db02d050a2b6c4588df80462ed831e M      test

real    3m7.903s
user    3m41.458s
sys     0m22.281s
tkelman@nanosoldier4:~/Julia/julia-0.4$ git bisect log
git bisect start
# good: [085a98501759b95569563ce46cf9360f4030b57a] Fix generic axpy! for vector element types without commutative multiplication, e.g. quaternions.
git bisect good 085a98501759b95569563ce46cf9360f4030b57a
# bad: [116a6cee2bed8405f0bb5828f6e187ad3160c605] Regen docs and update line numbers in doctest
git bisect bad 116a6cee2bed8405f0bb5828f6e187ad3160c605
# bad: [a3f7c1fb6069c1814eaaa8f250c6ecd07ce53750] Bump openblas to v0.2.15
git bisect bad a3f7c1fb6069c1814eaaa8f250c6ecd07ce53750
# good: [fce7beba598e50bb2e14905d276569d94537769a] Fix #13610, long compilation time for Date(::Day, ::Month, ::Year)
git bisect good fce7beba598e50bb2e14905d276569d94537769a
# good: [b6b590d38266fa7953209890f87e5de3e5396fe2] make sure Pkg.build process uses same paths as parent process (see #13506)
git bisect good b6b590d38266fa7953209890f87e5de3e5396fe2
# good: [d5e154c8d9a050fcf2c3c351fa6275f7dd3b0291] Loosen some signatures in lapack.jl form Matrix to StridedMatrix and test that least squares works for SubMatrix
git bisect good d5e154c8d9a050fcf2c3c351fa6275f7dd3b0291
# bad: [70018be2da560a75fb0712fef3f74c8db7a439bd] propagate errors on wait(::RemoteRef) and remotecall_wait
git bisect bad 70018be2da560a75fb0712fef3f74c8db7a439bd
# good: [4b5626da90a661468844833829d2924fd761960d] fix #13605, update calling-c manual chapter for cconvert changes
git bisect good 4b5626da90a661468844833829d2924fd761960d
# first bad commit: [70018be2da560a75fb0712fef3f74c8db7a439bd] propagate errors on wait(::RemoteRef) and remotecall_wait
```

Was this actually a case of the error being present on Julia 0.4.0 but not propagated correctly due to not having 70018be2da560a75fb0712fef3f74c8db7a439bd (ref #13730)?

**Comment by tkelman** [comment]
Ah, I think FixedPointNumbers just runs its tests really slowly when inlining is off? ref https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/28. Maybe running `Pkg.test("FixedPointNumbers", coverage=false)` would be noticeably faster.

**Comment by timholy** [comment]
Yes, the FixedPointNumbers tests take a very long time with or without inlining (but especially without).

**Comment by tkelman** [comment]
Alright, I'm pretty happy with this - https://gist.github.com/59fcb8044eebf556bdac

That re-run started before my BinDeps tag got merged, and Images, NLSolve, and Taro all have intermittent issues. I would appreciate input and other opinions on the items in the list above: https://github.com/JuliaLang/julia/pull/13834#issuecomment-152697870

**Comment by timholy** [comment]
The Images failure looks due to a specific instance of random numbers. I'll have to investigate and likely change that test, but for your purposes you can ignore that particular error.

**Comment by timholy** [comment]
For your benefit, justifications for #13803 include: it's necessary for https://github.com/JuliaOpt/JuMP.jl/pull/604 and would allow operations like
```jl
using SIUnits.ShortUnits
A = [1m 2m; -1m 5m]
v = [3m,-1m]
A*v
```
to become type-stable (currently [it returns a non-leaftype](https://github.com/Keno/SIUnits.jl/blob/9ce64b99c8c52b7665ea203c5de406527ee94b95/src/SIUnits.jl#L128-L131) as a mechanism to circumvent what would otherwise be an error). That said, I also recognize the risk. As I stated elsewhere, since I'm obviously biased I would prefer to defer to others in making the decision about whether to include it.

The patch list looks delicious, very much looking forward to 0.4.1 even if nothing else gets added.

**Comment by hiccup7** [comment]
Now that OpenBLAS v0.2.15 has been merged to the master branch, I vote for including it in the backports for 0.4.1.  I am assuming that the OpenBLAS API stayed the same.  Many bugs and performance issues have been fixed in the 7 months since the last OpenBLAS release, and they include showstoppers for me in using Julia.

**Comment by tkelman** [comment]
Scroll up, it's already here https://github.com/JuliaLang/julia/commit/a3f7c1fb6069c1814eaaa8f250c6ecd07ce53750

Though when I ran the microbenchmarks it did look like randmatstat got about 15% slower, which mighy be attributable to the new version of openblas?

**Comment by tkelman** [comment]
I was wrong to blame openblas, it was actually 1fc2d8e95c9dc1c516a376feeb66399e50a27381 that was responsible for the 15% slowdown in rand_mat_stat.

DataArrays has still not been tagged to work with #13803. I could be convinced to maybe pull #13491 and #13553 in here if perf and PackageEvaluator look okay on them, but unless someone argues for them I'm inclined to leave them until the next point release.

**Comment by hiccup7** [comment]
@tkelman - thanks for the clarification.

**Comment by jakebolewski** [comment]
Is there a rough ETA on the next tagged bugfix, some students are asking about it in @alanedelman's class.

**Comment by tkelman** [comment]
This weekend probably. Asked for input and opinions above and have yet to get any other than from Tim.




On Wed, Nov 4, 2015 at 11:14 AM -0800, "Jake Bolewski" <notifications@github.com> wrote:
Is there a rough ETA on the next tagged bugfix, some students are asking about it in @alanedelman's class.

---

**Comment by tkelman** [comment]
https://gist.github.com/c4ae8dfc79bdc2111f7e

Most of the failures are either intermittent things I've seen before, or odd issues that only happened on the 0.4.0 baseline run where some unrelated package gives something like `LoadError: module Graphics not found in current path; removed orphaned cache file /home/vagrant/.julia/lib/v0.4/Graphics.ji`.

Will merge and tag shortly unless anyone wants to advocate that anything remaining on the checklist in the first comment is must-do-now.

**Pull request merged**
