### PR TITLE
Silence compiler warnings

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]
maybe these compilers should just be smarter

**Comment by vchuravy** [comment]
> maybe these compilers should just be smarter

The sufficiently smart compiler does not exist.

**Comment by ararslan** [comment]
I haven't seen FreeBSD tests pass in quite a while now. Is it possible that this actually fixed them? o_O

**Comment by ararslan** [comment]
The answer, my friends, is no.

**Pull request merged**
