### PR TITLE
Re-enable soft scope doctests

### LINKED ISSUE #34567: revert #34566 once doctests support soft scope
https://github.com/JuliaLang/julia/pull/34566 should be reverted once the doctests behave the same way as the REPL.

### PR DESCRIPTION
**Pull request by mortenpi**
Updates Documenter and reverts #34566 (disabled doctests for soft scope examples) to close #34567.

Did not test locally, so should definitely wait to see if the doctest CI passes before merging.

cc @fredrikekre @StefanKarpinski

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Not sure what to make of the failure.

**Comment by fredrikekre** [comment]
Looks like `@deprecate` (maybe output of macros in general?) changed on Julia master:

Julia v1.4-rc1:
```
julia> @deprecate old(x) new(x)
old (generic function with 1 method)

julia>
```
Julia master (51f1710d7eac046de2ba4cc580ceb030e37f57a7)
```
julia> @deprecate old(x) new(x)

julia>
```

**Comment by fredrikekre** [comment]
Passes on master though, maybe https://github.com/JuliaDocs/Documenter.jl/blob/18722b71fef301f655d07479803b35898b58acab/src/DocTests.jl#L214-L218 was not enough? Looks like the return expression changes somehow?

**Comment by fredrikekre** [comment]
Maybe its the `:block` expr?
```
julia> dump(Meta.parse(s))
Expr
  head: Symbol macrocall
  args: Array{Any}((4,))
    1: Symbol @deprecate
    2: LineNumberNode
      line: Int64 1
      file: Symbol none
    3: Expr
      head: Symbol call
      args: Array{Any}((2,))
        1: Symbol old
        2: Symbol x
    4: Expr
      head: Symbol call
      args: Array{Any}((2,))
        1: Symbol new
        2: Symbol x

julia> dump(REPL.softscope!(Meta.parse(s)))
Expr
  head: Symbol block
  args: Array{Any}((2,))
    1: Expr
      head: Symbol softscope
      args: Array{Any}((1,))
        1: Bool true
    2: Expr
      head: Symbol macrocall
      args: Array{Any}((4,))
        1: Symbol @deprecate
        2: LineNumberNode
          line: Int64 1
          file: Symbol none
        3: Expr
          head: Symbol call
          args: Array{Any}((2,))
            1: Symbol old
            2: Symbol x
        4: Expr
          head: Symbol call
          args: Array{Any}((2,))
            1: Symbol new
            2: Symbol x
```

**Comment by StefanKarpinski** [comment]
@JeffBezanson ^

**Comment by mortenpi** [comment]
I "fixed" the doctests for `@deprecate`, so they now correspond to the real REPL output, even if that output is not what is intended. So, assuming the tests still pass, we could merge this and fix `@deprecate` together with its doctests in a follow-up PR.

**Pull request merged**
