### PR TITLE
Remove default value 50 from linspace and logspace `n` arguments

### LINKED ISSUE #24794: Linspace defaults the `n` parameter to 50
I was surprised when I found that Julia's `linspace` function uses the number 50 as the default argument for the number of steps:

```julia
linspace(start, stop, n=50)
```

Discussion on Slack indicated that this behavior comes from [SciPy](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linspace.html), but that it should probably be dropped for 0.7.

### PR DESCRIPTION
**Pull request by yurivish**
Fixes #24794.

### CODE REVIEW

**Review by andreasnoack — COMMENTED** [review]
Thanks for doing this. You should add deprecation methods for versions without `n` specified.

**Comment by yurivish** [comment]
@andreasnoack Done. This is my first pull request with deprecations; let me know if I've done anything wrong. :)

**Review by andreasnoack — APPROVED** [review]

**Review by fredrikekre — APPROVED** [review]
Should be mentioned in the deprecation section in `NEWS.md` as well.

**Comment by timholy** [comment]
Awesome, thanks.

One more: tests [here](https://github.com/JuliaLang/julia/blob/ab03fc017d5fe0dfd492966a57c07dd1dc486ad2/test/ranges.jl#L1142) and [here](https://github.com/JuliaLang/julia/blob/ab03fc017d5fe0dfd492966a57c07dd1dc486ad2/test/ranges.jl#L1195-L1198) will emit deprecation warnings unless changed. You should locally `make test-ranges` to check that they pass without warning.

**Comment by yurivish** [comment]
@timholy Sorry, I'm having some trouble building Julia from source locally in order to run tests and don't have time to debug right now. I've pushed test changes I think are appropriate but don't have the ability to run `make test-ranges` to make sure they're right.

**Comment by timholy** [comment]
The travis log looks good (no warnings), so I think this can be merged once CI completes.

**Comment by fredrikekre** [comment]
> The travis log looks good (no warnings), so I think this can be merged once CI completes.

AFAIK we run with `--depwarn=error` on CI, so it shouldn't even pass if something has not been updated.

**Pull request merged**
