### PR TITLE
Add some tests for "fixed by LLVM upgrade" issues

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by Keno** [comment]
:+1: Thank you!

**Comment by tkelman** [comment]
not sure whether these will all work on windows, let's see what appveyor says

**Comment by tkelman** [comment]
Did I mess something up in transcribing the test for #9222? I'm getting an illegal instruction on windows:
```
$ gdb -q --args /home/Tony/julia/usr/bin/julia-debug.exe ./runtests.jl core && echo ok
Reading symbols from /home/Tony/julia/usr/bin/julia-debug.exe...done.
(gdb) r
Starting program: /home/Tony/julia/usr/bin/julia-debug.exe ./runtests.jl core
[New Thread 9060.0xb60]
[New Thread 9060.0x2634]
[New Thread 9060.0x19ec]
[New Thread 9060.0xfc]
[New Thread 9060.0x720]
[New Thread 9060.0x610]
[New Thread 9060.0x2b4c]
[New Thread 9060.0x1858]
[New Thread 9060.0x984]
[New Thread 9060.0x18f8]
[New Thread 9060.0x1500]
[New Thread 9060.0x2b98]
     * [New Thread 9060.0x1e44]
core
Program received signal SIGILL, Illegal instruction.
0x0000000324c71a73 in julia_foo9222_3380 ()
    at C:\cygwin64\home\Tony\julia\test\core.jl:3671
3671        SimpleTest9222(0.0, mu_actual, nu_actual, v0, 0.0, [1.0,1.0], 0.5, 5.0, 20.0)
(gdb) bt
#0  0x0000000324c71a73 in julia_foo9222_3380 ()
    at C:\cygwin64\home\Tony\julia\test\core.jl:3671
#1  0x0000000324c71a98 in jlcall_foo9222_3380 ()
#2  0x000000006ea1efe4 in jl_apply (f=0x106ff5730, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#3  0x000000006ea2324f in jl_trampoline (F=0x106ff5730, args=0x0, nargs=0)
    at /home/Tony/julia/src/builtins.c:1036
#4  0x000000006ea10731 in jl_apply (f=0x106ff5730, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#5  0x000000006ea1741b in jl_apply_generic (F=0x106ff5250, args=0x0, nargs=0)
    at /home/Tony/julia/src/gf.c:1946
#6  0x0000000324c7003b in julia_anonymous_3379 () at test.jl:208
#7  0x000000006ea1efe4 in jl_apply (f=0x106ff55d0, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#8  0x000000006ea2324f in jl_trampoline (F=0x106ff55d0, args=0x0, nargs=0)
    at /home/Tony/julia/src/builtins.c:1036
#9  0x000000031f7bc49f in julia_do_test_throws_1382 () at test.jl:217
#10 0x000000006ea10731 in jl_apply (f=0x108440970, args=0xd7d9b8, nargs=4)
    at /home/Tony/julia/src/julia.h:1391
#11 0x000000006ea17314 in jl_apply_generic (F=0x103e0b4d0, args=0xd7d9b8, nargs=4)
    at /home/Tony/julia/src/gf.c:1922
#12 0x000000006ea295c1 in jl_apply (f=0x103e0b4d0, args=0xd7d9b8, nargs=4)
    at /home/Tony/julia/src/julia.h:1391
#13 0x000000006ea29b61 in do_call (f=0x103e0b4d0, args=0x106945bd8, nargs=4, eval0=0x0,
    locals=0x0, nl=0, ngensym=0) at /home/Tony/julia/src/interpreter.c:65
#14 0x000000006ea2a7d4 in eval (e=0x106ff5510, locals=0x0, nl=0, ngensym=0)
    at /home/Tony/julia/src/interpreter.c:214
#15 0x000000006ea297f8 in jl_interpret_toplevel_expr (e=0x106ff5510)
    at /home/Tony/julia/src/interpreter.c:25
#16 0x000000006ea485da in jl_toplevel_eval_flex (e=0x106ff5390, fast=1)
    at /home/Tony/julia/src/toplevel.c:531
#17 0x000000006ea488aa in jl_parse_eval_all (
    fname=0x107b0f4e0 "C:\\cygwin64\\home\\Tony\\julia\\test\\core.jl", len=40,
    ctx=0x31e55f830) at /home/Tony/julia/src/toplevel.c:581
#18 0x000000006ea48b21 in jl_load (
    fname=0x107b0f4e0 "C:\\cygwin64\\home\\Tony\\julia\\test\\core.jl", len=40)
    at /home/Tony/julia/src/toplevel.c:622
#19 0x000000006ea48ba5 in jl_load_ (str=0x106d17e60)
    at /home/Tony/julia/src/toplevel.c:630
#20 0x000000031f04f024 in julia_include_739 (fname=0x106c9f370) at boot.jl:262
---Type <return> to continue, or q <return> to quit---
#21 0x000000006ea10731 in jl_apply (f=0x1034449b0, args=0xd7e6b8, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#22 0x000000006ea17314 in jl_apply_generic (F=0x1034446f0, args=0xd7e6b8, nargs=1)
    at /home/Tony/julia/src/gf.c:1922
#23 0x000000031f040602 in julia_include_from_node1_721 () at loading.jl:401
#24 0x000000006ea10731 in jl_apply (f=0x1053faff0, args=0xd7e8e8, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#25 0x000000006ea17314 in jl_apply_generic (F=0x1053faa70, args=0xd7e8e8, nargs=1)
    at /home/Tony/julia/src/gf.c:1922
#26 0x000000031f7394b4 in runtests () at util.jl:179
#27 julia_runtests_1233 () at C:\cygwin64\home\Tony\julia\test\testdefs.jl:7
#28 0x000000031f739a97 in jlcall_runtests_1233 ()
#29 0x000000006ea1efe4 in jl_apply (f=0x106bf3cb0, args=0xd7ebb8, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#30 0x000000006ea2324f in jl_trampoline (F=0x106bf3cb0, args=0xd7ebb8, nargs=1)
    at /home/Tony/julia/src/builtins.c:1036
#31 0x000000006ea10731 in jl_apply (f=0x106bf3cb0, args=0xd7ebb8, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#32 0x000000006ea1741b in jl_apply_generic (F=0x106584cb0, args=0xd7ebb8, nargs=1)
    at /home/Tony/julia/src/gf.c:1946
#33 0x000000031f720074 in julia_anonymous_1226 (t=<optimized out>)
    at C:\cygwin64\home\Tony\julia\test\runtests.jl:36
#34 0x000000006ea1efe4 in jl_apply (f=0x106b095f0, args=0xd7ed40, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#35 0x000000006ea2324f in jl_trampoline (F=0x106b095f0, args=0xd7ed40, nargs=1)
    at /home/Tony/julia/src/builtins.c:1036
#36 0x000000006ea1efe4 in jl_apply (f=0x106b095f0, args=0xd7ed40, nargs=1)
    at /home/Tony/julia/src/julia.h:1391
#37 0x000000006ea21006 in jl_f_apply (F=0x0, args=0xd7ee88, nargs=2)
    at /home/Tony/julia/src/builtins.c:505
#38 0x000000031f70f0a9 in julia_anonymous_1225 () at multi.jl:753
#39 0x000000006ea1efe4 in jl_apply (f=0x106bf3af0, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#40 0x000000006ea2324f in jl_trampoline (F=0x106bf3af0, args=0x0, nargs=0)
    at /home/Tony/julia/src/builtins.c:1036
#41 0x000000031f2941c2 in julia_run_work_thunk_1156 () at multi.jl:714
#42 0x000000031f70d0ce in julia_remotecall_fetch_1223 () at multi.jl:787
#43 0x000000006ea1efe4 in jl_apply (f=0x106bf08d0, args=0xd7f440, nargs=3)
    at /home/Tony/julia/src/julia.h:1391
#44 0x000000006ea2324f in jl_trampoline (F=0x106bf08d0, args=0xd7f440, nargs=3)
---Type <return> to continue, or q <return> to quit---
    at /home/Tony/julia/src/builtins.c:1036
#45 0x000000006ea10731 in jl_apply (f=0x106bf08d0, args=0xd7f440, nargs=3)
    at /home/Tony/julia/src/julia.h:1391
#46 0x000000006ea1741b in jl_apply_generic (F=0x1053fadb0, args=0xd7f440, nargs=3)
    at /home/Tony/julia/src/gf.c:1946
#47 0x000000006ea1efe4 in jl_apply (f=0x1053fadb0, args=0xd7f440, nargs=3)
    at /home/Tony/julia/src/julia.h:1391
#48 0x000000006ea21006 in jl_f_apply (F=0x0, args=0xd7f5a8, nargs=3)
    at /home/Tony/julia/src/builtins.c:505
#49 0x000000031f70c10a in julia_remotecall_fetch_1222 (id=<optimized out>)
    at multi.jl:803
#50 0x000000006ea1efe4 in jl_apply (f=0x106b097d0, args=0xd7f9c8, nargs=3)
    at /home/Tony/julia/src/julia.h:1391
#51 0x000000006ea2324f in jl_trampoline (F=0x106b097d0, args=0xd7f9c8, nargs=3)
    at /home/Tony/julia/src/builtins.c:1036
#52 0x000000006ea10731 in jl_apply (f=0x106b097d0, args=0xd7f9c8, nargs=3)
    at /home/Tony/julia/src/julia.h:1391
#53 0x000000006ea1741b in jl_apply_generic (F=0x1053fadb0, args=0xd7f9c8, nargs=3)
    at /home/Tony/julia/src/gf.c:1946
#54 0x000000031f7022d2 in anonymous () at C:\cygwin64\home\Tony\julia\test/runtests.jl:36
#55 julia_anonymous_1212 () at task.jl:435
#56 0x000000006ea1efe4 in jl_apply (f=0x106a04c90, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#57 0x000000006ea2324f in jl_trampoline (F=0x106a04c90, args=0x0, nargs=0)
    at /home/Tony/julia/src/builtins.c:1036
#58 0x000000006ea35946 in jl_apply (f=0x106a04c90, args=0x0, nargs=0)
    at /home/Tony/julia/src/julia.h:1391
#59 0x000000006ea36213 in start_task () at /home/Tony/julia/src/task.c:246
#60 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

(I'm pretty sure that's the first time I've seen julia source info inside gdb, nice)

**Comment by yuyichao** [comment]
`disassemble $pc` ?

**Comment by tkelman** [comment]
https://gist.github.com/cf1f56a56ec59689e542

**Comment by yuyichao** [comment]
Wierd, seems that the function that shouldn't return actually returns?......

**Comment by tkelman** [comment]
So whose bug is this anyway?
<sub>where everything's made up and the points don't matter</sub>

**Comment by yuyichao** [comment]
Maybe checking the llvm and native code for both the outer and inner functions? I assume the type inference correctl identified that the function doesn't return but might also worth check that....

**Comment by vtjnash** [comment]
moved fix for #9222 to #14745

should we make these tests conditional on `Base.libllvm_version`?

**Comment by tkelman** [comment]
Good idea, done for the one that didn't already have an llvm 3.3 workaround in place somewhere else.

**Pull request merged**
