### PR TITLE
regenerate precompile statements

### PR DESCRIPTION
**Pull request by KristofferC**
I also made a script in `contrib` that makes it a bit easier to generate the `precompile.jl` from `precompiles.txt`. This script can also merge new methods into the existing `precompile.jl` which seems useful if you just want to make a run to add some statments without having to rerun all the old stuff. I'm not sure if the whole `PrecompileStagingArea` module thing makes sense, but it was the easiest way to do it without putting new names into `Main`.

We should also probably have a script that deletes methods that fail to precompile but that can be done later.

There seem to be a bit fewer statements here than before. Not sure exactly what was run last time it was generated. With the new merge functionality, it is pretty easy to incrementally add more though.

Ref https://github.com/JuliaLang/julia/issues/24666 but not closing because we should do this again closer to release.

### CODE REVIEW

**Comment by KristofferC** [comment]
If no one opposes this I will merge in a day or two. Would be nice to have this in place when Pkg3 is moved in because it has a much better experience with precompile statements.

**Comment by StefanKarpinski** [comment]
Why wait? What possible objection would anyone have?

**Comment by KristofferC** [comment]
People migth have comments on the whole `fixup_precompile.jl` script. I'll do some measurements like sysimg size, startup time etc and check this PR vs master.

**Comment by KristofferC** [comment]
Master:

```
Precompile DataFrames: 87 sec
Load DataFrames:  3.759690 seconds 

time ./julia -e '1+1'
0.87s user 0.21s system 148% cpu 0.728 total
```

PR:

```
Precompile DataFrames: 66 sec
Load DataFrames: 3.14 sec

time ./julia -e '1+1'
0.32s user 0.13s system 136% cpu 0.330 total
```

**Comment by KristofferC** [comment]
Ok then, this should be trivial to revert if there is a problem, so no big risk.

**Pull request merged**
