### PR TITLE
Improve consistency of SONAME usage, fix debug installation

### PR DESCRIPTION
**Pull request by staticfloat**
SONAME and RPATH inconsistency resulted in `julia`/`julia-debug`
occasionally being unable to find `libjulia.so`, due to
`libjulia-internal` not having the right RPATH set (it was set to
`$ORIGIN:$ORIGIN/julia`, when it now needs to be set to
`$ORIGIN:$ORIGIN/..`).  Use `patchelf` to address this during `make
install`.

We also want to use the SONAME of e.g. `libjulia` as much as possible,
so as to avoid searching the filesystem for libraries that are already
opened.

Also fix a few bugs in building `julia-debug`.

### CODE REVIEW

**Comment by staticfloat** [comment]
@GunnarFarneback see if this fixes the issues you were having with `dlopen("libjulia")`.

**Comment by KristofferC** [comment]
Should be backported?

**Comment by GunnarFarneback** [comment]
Yes, this solves the problem noted in https://github.com/JuliaLang/julia/pull/38950#issuecomment-748679872 on Ubuntu.

**Comment by vtjnash** [comment]
I don't know if this covers all of the dlopen cases, but looks like it should help many cases.

**Comment by GunnarFarneback** [comment]
This(*) solved the macos failure for the DynamicallyLoadedEmbedding tests on nightly. Windows still remains broken though, https://github.com/GunnarFarneback/DynamicallyLoadedEmbedding.jl/runs/1616727928.

(*) Or possibly some other PR of the last few days, but I guess this is the most likely one.

**Pull request merged**
