### PR TITLE
loading tests: oops, delete temp file

### PR DESCRIPTION
**Pull request by StefanKarpinski**
Fix silly mistake: remember to delete the tempfile that the project file parsings tests create.

### CODE REVIEW

**Comment by KristofferC** [comment]
Could use the `mktemp()` pattern?

**Comment by StefanKarpinski** [comment]
I tried that first but I need to close and reopen the same file name repeatedly which that function doesn't support in any obvious way.

**Comment by garrison** [comment]
> close and reopen the same file name repeatedly

I typically use `mktempdir` in this case, and put my temporary file in the resulting directory...

**Comment by StefanKarpinski** [comment]
I suppose that would be another way to do it.

**Pull request merged**
