### PR TITLE
Optimize compute_live_ins in optimizer hotpath

### PR DESCRIPTION
**Pull request by LilithHafner**
This is my first time touching the compiler, so I'd appreciate a careful review!

I'm assuming that `defs` and `uses` are disjoint and increasing and that `block_for_inst` is a nondecreasing function.

This is motivated by my belief that almost all uses of `sort` can be replaced with more performant alternatives.

### CODE REVIEW

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46508#issuecomment-1229665365) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/0fbd33e_vs_5316549/report.md).

**Comment by JeffBezanson** [comment]
Any noticeable compile time improvements from this?

**Comment by LilithHafner** [comment]
None that I know of. Perhaps this was not really a bottleneck.

**Comment by thofma** [comment]
A bisect shows that this broke Hecke. Here is an example for the backtrace: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-09/22/Hecke.primary.log
(Do not be deceived by the "successful" at the end.)

Should I open a separate issue?

**Pull request merged**
