### PR TITLE
Add a test that reproduces the reported issue to #17399

### PR DESCRIPTION
**Pull request by tkelman**
@wildart I got impatient, please review. The first few times I tried, `LibGit2.add!` did not seem to work, but now it's apparently okay.

The first 2 commits here are the same as https://github.com/JuliaLang/julia/pull/17399, just rebased. The third commit adds a test that reproduces the actual issue, meaning it fails if you run the new test without your changes to base here.

### CODE REVIEW

**Comment by wildart** [comment]
Commit is done into the checked out repo `Example3`, but it should be to the remote branch of `Example`.

But mine is better :wink:, I just pushed #17399.

**Comment by tkelman** [comment]
> Commit is done into the checked out repo `Example3`, but it should be to the remote branch of `Example`.

No, the issue is a `WARNING: Cannot perform fast-forward merge.` because the local commits on the pre-checkout package conflict with the checked-out branch.

**Comment by tkelman** [comment]
Let's just do both.

**Comment by wildart** [comment]
In it can't fast-forward merge, it a trouble. The branch is going to be created but never positioned correctly.

**Comment by tkelman** [comment]
It really shouldn't be doing a merge at all, we asked it to do a checkout.

**Comment by wildart** [comment]
Problem is that `git checkout` is not just checkout particular branch or commit. It's much more. And, when you checkout a remote branch, you want to FF merge changes on that branch.

**Comment by tkelman** [comment]
I'm going to merge this one, since it tests more scenarios.

**Pull request merged**
