### PR TITLE
less jl_get_global reflection

### PR DESCRIPTION
**Pull request by vtjnash**
The remaining ones I see are
 - `Base.stdout`
 - `Base.DL_LOAD_PATH`
 - `Core._parse`
 - `Base._atexit`
 - `Base._postoutput`
 - `Core.ARGS`
 - `Base._start`
 - `Base.Libc.Libdl.dlopen`
 - `Base.task_done_hook`
 - `Base.wait`
 - `Base.CoreLogging.logmsg_shim`
 - `__init__`
 - `Base.register_root_module`
 - `Base.loaded_modules_array`
 - `Base.__toplevel__`
 - `Base.require`
 - aspects of staticdata.c/staticdata_utils.c/precompile.c

(of these, the `Base.register_root_module` / `Base.loaded_modules_array` should probably be moved to C still, since it is a thread-safety issue / data-race / deadlock risk right now)

### CODE REVIEW

**Comment by inkydragon** [comment]
This pr removes some export functions from julia.h, maybe it's worth adding a NEWS?

**Comment by vtjnash** [comment]
We don't have a stable API promise for C code, including exports, so I don't think there is anything NEWS-worthy here; we change exports on every release and that is just what should be expected.

**Comment by gbaraldi** [comment]
Isn't the yeild thing important if someone is embedding julia?

**Comment by vtjnash** [comment]
They probably shouldn't call `yield` either, since that is highly sus even if you aren't embedding Julia and just writing "regular" code

**Comment by PallHaraldsson** [comment]
@vtjnash, Can even just `jl_stdout_obj` be added back in for 1.11.2? It broke an R interop package (why PkgEvel didn't catch it):

https://github.com/Non-Contradiction/JuliaCall/pull/237#issuecomment-2429261294

It's "used" there, but not even in reality, so the easy fix is there, but requires a new merge, and maintainer absent...

**Pull request merged**
