### PR TITLE
WIP: Sparse CSR Matrices

### PR DESCRIPTION
**Pull request by tanmaykm**
This would introduce Sparse CSR matrix data type.
- `SparseMatrixCSC` and `SparseMatrixCSR` implement `CompressedSparseMatrix` 
- `CompressedSparseMatrix` is `AbstractSparseMatrix` and parameterized with the constants `CSC` or `CSR` ~~a `CompressedSparseType` (`CSC` or `CSR`)~~
- made the existing CSC matrix methods generic wherever possible to be used on `CompressedSparseMatrix` by working on the abstraction of compressed and uncompressed dimension.

All the linalg methods and a few matrix methods are yet to be implemented for CSR. This does not break any existing APIs. In brief, the API changes are:
- There is a `SparseMatrixCSR` constructor, similar to the one for CSC. 
- The `sparse` constructor and methods like `spzeros`, `sprand` can now optionally take a keyword argument `format` that can either be `CSC` (default) or `CSR`. ~~`CSR` or `CSC` as the first parameter.~~
- The `sparse` constructor now has a variant that takes a sparse store (`CompressedSparseStore` or a `TripletSparseStore`) specifying the data. This seemed to be a good uniform way to overload the `sparse` constructor for different data formats.
  ~~\- Methods like `spzeros`, `sprand` take a keyword argument `format` that can either be `CSC` (default) or `CSR`.~~

Would appreciate feedbacks and whether this is in the right direction.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I am closing this, since we really should do this in a package.

**Comment by tkelman** [comment]
@ViralBShah @tanmaykm should we create a https://github.com/JuliaSparse/SparseMatrices.jl package for working on alternate sparse formats, CSR, COO, etc? I have some work where I'll want to use an array-of-sparse-columns format, might be good to put that part somewhere it could be more broadly used.

**Comment by ViralBShah** [comment]
Good idea. Let's do it. We should change the interfaces in base to make it easier to add more formats as packages.

**Comment by spencerlyon2** [comment]
What's the status on this?

I realized that I could really use a CSR format for an application I am working on

**Comment by mlubin** [comment]
Doesn't look like the code was ever moved into a package.

**Comment by spencerlyon2** [comment]
I'm happy to pull the code out  into a package. 

Any objections?

**Comment by tkelman** [comment]
Nope. Just sent you an invite to join JuliaSparse. Good to do it there for easier collaboration.

**Comment by spencerlyon2** [comment]
Great,  thanks. I'll make a SparseCSR.jl over there and start pulling factoring the code out

**Comment by spencerlyon2** [comment]
So I'm looking at this now. Given how many changes were made to base here, I don't see a clean way to provide CSR in package without duplicating a lot of what we have for CSC in base.

We might consider cleansing this PR so that all the generalizations to the algorithms that "made room" for CSR remain, but the actual implementation of CSR gets farmed out to another package. With the right abstraction we could "make room" for COO, BSR, or others to be implemented in another package. 

Has anyone put serious thought into how this abstraction might look?

**Comment by tkelman** [comment]
I've thought a fair amount about the abstraction, and a direction I've started looking into has been basing more of the internal implementation on an `eachstored` iteration protocol for sparse matrices. So far my prototypes are really immature, the performance isn't very good and it's nowhere near being base-worthy. And this has more to do with the internals of how the various operations are implemented, rather than the user-facing API for interacting with different formats.

While a new more minimal reorganization PR could be started to make the base interfaces more easily extensible, I don't think we have time to get anything significant into base before 0.4, considering we're about to declare a feature freeze. So if you're in a hurry to build some functionality you can use, the most immediate approach would be to just live with duplicating code at first.

For design adjustments to base for 0.5 or later, we could start thinking about what we'd like the design to look like. That early design brainstorming work probably doesn't have to happen on this repo's issue tracker or as PR's just yet.

**Comment by spencerlyon2** [comment]
That's great. Maybe we can start working from what you have already started.

Totally agree that we shouldn't try to get anything related to this into 0.4 -- bring on the feature freeze! I actually think the array themed 0.5 is a good target aim for to get at least parts of this in.

Also agree we should have design discussions elsewhere. Should we create a new repo in JuilaSparse and have it serve as a playground/discussion area as we think this through?

**Comment by tkelman** [comment]
Sure. We could either make it a "meta" repo just for discussion like some other organizations have, or a stub package with the intent of growing it into something functional. Since I think the abstraction-design goal is more ambitious than just extending to CSR, might want a more generic name like SparseMatrices.jl or SparseArrays.jl (would possibly conflict with #12323) or SparseIterators.jl or ...

**Pull request closed without merging**
