### PR TITLE
REPL: ask for confirmation before exiting with ^D

### PR DESCRIPTION
**Pull request by rfourquet**
As `^D` is easy to type by mistake, in particular as it's also the binding to delete a character, let's ask for confirmation when it's pressed:
```julia
julia> Type ^D again to exit.

julia>
```
This is customizable via `REPL.Options.confirm_exit`.

(this was made easy to implement thanks the first commit in #24725, where the REPL state records the last "action" and can recognize when it's repeated; note that the `key_repeats` variable was not enough, as `^D` does two things, so the REPL would exit directly if the 1st `^D` deletes a character and the 2nd requests exit).

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by iblis17** [comment]
ci freezing seems related. There is no `repl` testsuit report in the log.

**Comment by rfourquet** [comment]
> ci freezing seems related

Indeed thanks, I had forgotten that `^D` was used in repl tests to exit "fake" REPLs. Hopefully fixed now.

**Comment by rfourquet** [comment]
CI failures are now unrelated. Thank you both for review and comment!

**Comment by rfourquet** [comment]
For those not liking this change, it can be disabled by:
```julia
atreplinit() do repl
    repl.options = Base.REPL.Options(confirm_exit=false)
end
```
I think it makes sense to have it enabled by default, in particular for beginners not used to having "Ctrl-D" exit a shell.

**Comment by fredrikekre** [comment]
This is incredibly annoying, can we turn it off by default? :stuck_out_tongue:

**Comment by KristofferC** [comment]
Yeah, I've closed my terminal window multiple times now. +1 for off by default.

**Comment by rfourquet** [comment]
I dunno... IPython for example asks for confirmation, and I was happy with that a couple of times when it was my research environment, to not "loose" by accident my current work. For me there is a difference between "developper mode", where indeed I restart often and exit-confirmation is rather annoying, but in "real-word work mode" I can have a REPL open for quite some time, and it's rather annoying to exit accidentally. It's even easy to set-up two modes for example where an environment variable determines `confirm_exit`. I would tend to think people wanting to disable `confirm_exit` are the most likely to find this github page (or the doc when it becomes documented); on the other hand users who are not julia developpers will most likely never hear about this feature if it's disabled by default. So my vote is to follow IPython's example here, but let's see if more feedback comes about it, or if triage makes a call.

**Comment by vtjnash** [comment]
minor issues?
```sh
 $ TERM=dumb ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.2712 (2017-11-30 17:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 93fc492* (0 days old master)
|__/                   |  x86_64-linux-gnu

WARNING: Terminal not fully functional
type BasicREPL has no field options
julia> ^D
$ 
```

**Comment by rfourquet** [comment]
> minor issues?

Good catch, I updated the snippet above using `atreplinit`, with a test to check that the `repl` has `options`.

**Comment by fredrikekre** [comment]
One more plea to turn this off by default - is no one else annoyed by this? I accidentally close my repl way more often with this. For various reasons I run with `--startup-file=no` quite often so this caught me off guard once again. Also, I assume
```diff
diff --git a/base/repl/REPL.jl b/base/repl/REPL.jl
index 233c6bb..1349243 100644
--- a/base/repl/REPL.jl
+++ b/base/repl/REPL.jl
@@ -255,7 +255,7 @@ Options(;
         hascolor = true,
         extra_keymap = AnyDict[],
         backspace_align = true, backspace_adjust = backspace_align,
-        confirm_exit = true) =
+        confirm_exit = false) =
             Options(hascolor, extra_keymap, backspace_align, backspace_adjust, confirm_exit)
 
 ## LineEditREPL ##
```
is all I need to turn this off, rather than the full commit?

**Comment by ararslan** [comment]
Yes, I also find this incredibly annoying.

**Comment by rfourquet** [comment]
So I did a bit of digging concerning IPython's default and found this (small) [discussion](https://mail.scipy.org/pipermail/ipython-user/2008-July/005635.html) on one of their list, which don't bring much more new points than what has been already said here, except what I was about to say anyway, so we seem to repeat history :stuck_out_tongue:  (I even didn't know IPython's option and ours had the same name)
So I wanted to stress that usually, exiting the REPL is not the most recurrent task in a session, so having "^d^d" as a binding for exit doesn't strike me as particularly annoying or long to type. I concede that the message itself can be annoying (in particular if that feels like "are you sure you want to do what you ask me to do"), maybe this can be improved by printing less lines (or printing nothing at all?).

> I accidentally close my repl way more often with this.

I don't understand how this happen? I also have to use `--startup-file=no` quite often, but I think it concerns a very small minority of users; so for this case, we could either have an environment variable, or disable automatically `confirm_exit` when `--startup-file=no` ? that last one feels a bit too hacky though. But for example in Emacs, I also don't like the default experience (at all) with the equivalent "emacs -q", but I understand it's to make it as beginner-friendly as possible. 

> is all I need to turn this off, rather than the full commit?

Correct.
If Julia was only for its developpers, `confirm_exit=false` could be very well be a better default, but I'm questioning what would be a good default for the community at large (and have clearly no personal investment in this decision). I don't know a good way to gauge that (discourse?), so thought following IPython was a sane choice. I volunteer for implementing improvements here, but there is no evidence enough yet for me that the default must be changed (I won't fight someone else's PR though).

**Comment by fredrikekre** [comment]
> >     I accidentally close my repl way more often with this.
> I don't understand how this happen?

Yea I dunno, but I'm telling you it happens. I guess something like this happens: `Ctrl+D` -> `"Type ^D again to exit."` -> Brain: "Oh, I need to press twice to exit" -> `Ctrl+D+D` -> exit terminal. And I don't seem to be alone in this https://github.com/JuliaLang/julia/pull/24816#issuecomment-348296100

> So I wanted to stress that usually, exiting the REPL is not the most recurrent task in a session, so having "^d^d" as a binding for exit doesn't strike me as particularly annoying or long to type.

When pressing `Ctrl+D` the ratio between me wanting to exit the REPL to me pressing it by accident is essentially infinite. It 's not like you press `Ctrl+D` by accident.

**Comment by rfourquet** [comment]
> Yea I dunno, but I'm telling you it happens. 

I wasn't doubting your experience! but I thought you were talking about the Julia REPL, not the terminal window, so was curious what pattern made this happen.

> It 's not like you press Ctrl+D by accident.

It happens (rarely in Julia) for me, for example because "^D" is also "delete char", or because it's close to "^R". In by bash settings, I have `IGNOREEOF=1`, which does the same (confirm exit), and it happens all the time that I press ^D by accident there.

**Comment by Keno** [comment]
Please revert this change. Julia is not the only program in regular use that does not exit with the simple press of ^D. It's extremely irritating.

**Comment by Keno** [comment]
Or rather change the default.

**Comment by rfourquet** [comment]
So I very well understood that some some of you don't want the feature, and it was noted that the current implementation doesn't allow to have it off with "--startup-file=no", which could be fixed. Besides this, it would be great to hear arguments in favor of changing the default to "off". My reasons were that it's more discoverable if "on" by default, and the system I was using instead of Julia in the past (IPython) made this choice. For example, do you expect that the majority of users will be annoyed, or irritated, by this?

**Comment by ararslan** [comment]
| REPL | Closes with one ^D |
| :----: | :------: |
| APL (Dyalog) | Yes |
| APL (ngn) | Yes |
| IPython | **No** |
| Julia | **No** |
| Lisp (Clojure) | Yes |
| Lisp (FemtoLisp) | Yes |
| Lisp (SBCL) | Yes |
| Octave | Yes |
| Python 2 | Yes |
| Python 3 | Yes |
| R | Yes |
| Ruby (IRB) | Yes |
| Ruby (Pry) | Yes |
| Rust (rusti) | Yes |
| Scheme (icyc) | Yes |

Note in particular the disconnect between the Python REPL and IPython. It seems like if we want to provide something like this, it could be through IJulia or whatever rather than the stock Julia REPL.

**Comment by vtjnash** [comment]
By contrast though, I could extend this table with an extra column "has a good REPL", and that covers only IPython and Julia (to be fair, I haven't used several of them and only just tried them out quickly to verify that they have something equivalent to the barebones readline functionality)

**Comment by c42f** [comment]
Personally I find the new behavior incredibly irritating and it's caused me to close terminals by mistake several times. I think the problem is simple inconsistency with REPLs from other languages, especially the shell. So at a purely personal level, I'd love to revert this.

On the other hand people who are compiling 0.7 multiple times daily (ie, probably everyone here) are hardly representative of the average user who's just lost the data in their complex long running session.

Perhaps we should ask for broader feedback on discourse
* "Do you commonly quit julia by mistake and loose a session which is hard to reconstruct?"
* "Do you disable the ipython exit confirmation?"

**Comment by rfourquet** [comment]
We could indeed ask on Discourse, but it's a bit unusual, in particular for such a small feature. Also, is it complying with the purpose of Discourse? 

Also, seeing such strong negative feedback vehemently expressed ("extreme irritation", "incredible annoyance" vs. just "I don't like it so I disable it"), I wonder whether we should take the risk to let other people go through intense emotions like that (that said, I didn't notice such problem in IPython, so as Chris said, it's possibe that the average user would not be bothered on average.)

**Comment by innerlee** [comment]
The first thing after my install of ipython is to create a profile file to diable the exit confirmation :P

**Pull request merged**
