### PR TITLE
Check freshness of doc/stdlib on Travis

### PR DESCRIPTION
**Pull request by martinholters**
Will be obsoleted by #18588 but hopefully is useful until then by catching the common mistake of modifying docstrings and not updating the corresponding RST files.

### CODE REVIEW

**Comment by martinholters** [comment]
The error this has found immediately has been fixed in 38a63bd4 (https://github.com/JuliaLang/julia/commit/38a63bd473710c841fc3e812e3c953ab23750a3e#diff-1b93b2bd585f1eb42df445590f059fdcR1643).

**Comment by tkelman** [comment]
It's a little too easy to miss why the build failed here. Should probably terminate the job immediately and not run the tests when this happens.

**Comment by martinholters** [comment]
Hm, I couldn't find a way to make Travis terminate the job. Doing this test last might be a viable alternative.

**Comment by tkelman** [comment]
Waiting until the very end to run this is going to eat up a lot of CI time. Simple, not especially elegant workaround would be to touch a file as a flag if this check succeeds, and skip running the tests to save CI time (but still flag the build as a failure) if it's not present.

**Comment by martinholters** [comment]
I had something like that using an environment variable, similar to `test $STDLIBDOCCHECK_RESULT || ...` in front of the test runner, but the output was still so noisy that the actual output of the stdlib doc test was easy to miss. However, doing something like that and producing clearly visible output at the end might work. Will try next...

**Comment by martinholters** [comment]
Comments on the current status?

**Comment by kshyatt** [comment]
Bumping.

**Comment by martinholters** [comment]
Bump.

**Comment by tkelman** [comment]
I think https://github.com/JuliaLang/julia/pull/18588 is close enough to merging that this is soon to be made obsolete. This yml file is already pretty complicated and hard to read as is.

**Comment by martinholters** [comment]
Fair enough. I'll leave this open for now in case some unexpected problem comes up in #18588.

**Comment by martinholters** [comment]
Superseded by #18588.

**Pull request closed without merging**
