### PR TITLE
add an inductive range check elimination pass

### PR DESCRIPTION
**Pull request by pchintalapudi**
As stated in #42521, using `@inbounds` to denote areas where bounds checks are necessary is dangerous.  LLVM provides an InductiveRangeCheckElimination pass which can extract some bounds checks which are known to be safe.

Godbolt Links:
```
@noinline function f!(ys, xs)
                       for i in eachindex(ys, xs)
                         x = xs[i]
                         if -0.5 < x < 0.5
                           ys[i] = 2*x
                         end
                      end
              end
```
Original: https://godbolt.org/z/YY3WrYThh
With `@inbounds`: https://godbolt.org/z/cEW9GTsT3
Original+IRCE: https://godbolt.org/z/j1YndbzrE

The pass makes the control flow graph a little messier than `@inbounds `does, but does allow vectorization that is not allowable when bounds checks are present.

### CODE REVIEW

**Comment by vchuravy** [comment]
Nice! Could you time the passes during sysimage compilation? So that we can see how much additional time this takes.

**Comment by pchintalapudi** [comment]
> 
> 
> Nice! Could you time the passes during sysimage compilation? So that we can see how much additional time this takes.

Core.Compiler: 45.6049 seconds
Base  ───────────── 23.928286 seconds
ArgTools  ─────────  4.344550 seconds
Artifacts  ────────  0.106307 seconds
Base64  ───────────  0.106040 seconds
CRC32c  ───────────  0.007023 seconds
FileWatching  ─────  0.098718 seconds
Libdl  ────────────  0.001533 seconds
Logging  ──────────  0.036474 seconds
Mmap  ─────────────  0.083878 seconds
NetworkOptions  ───  0.094496 seconds
SHA  ──────────────  0.187798 seconds
Serialization  ────  0.288951 seconds
Sockets  ──────────  0.335865 seconds
Unicode  ──────────  0.007169 seconds
DelimitedFiles  ───  0.103579 seconds
LinearAlgebra  ────  7.549069 seconds
Markdown  ─────────  0.824861 seconds
Printf  ───────────  0.267628 seconds
Random  ───────────  1.139277 seconds
Tar  ──────────────  0.275640 seconds
Dates  ────────────  1.595620 seconds
Distributed  ──────  0.787926 seconds
Future  ───────────  0.004703 seconds
InteractiveUtils  ─  0.526222 seconds
LibGit2  ──────────  1.342156 seconds
Profile  ──────────  0.271113 seconds
SparseArrays  ─────  2.652343 seconds
UUIDs  ────────────  0.015049 seconds
REPL  ─────────────  3.619972 seconds
SharedArrays  ─────  0.520581 seconds
Statistics  ───────  0.193729 seconds
SuiteSparse  ──────  1.590027 seconds
TOML  ─────────────  0.068915 seconds
Test  ─────────────  0.296838 seconds
LibCURL  ──────────  0.415338 seconds
Downloads  ────────  0.385399 seconds
Pkg  ──────────────  4.512018 seconds
LazyArtifacts  ────  0.001587 seconds
Stdlibs total  ──── 34.670334 seconds
Sysimage built. Summary:
Total ───────  58.600201 seconds
Base: ───────  23.928286 seconds 40.8331%
Stdlibs: ────  34.670334 seconds 59.1642%

Generating REPL precompile statements... 31/31
Executing precompile statements... 1221/1253
Precompilation complete. Summary:
Total ─────── 100.895169 seconds
Generation ──  76.441509 seconds 75.7633%
Execution ───  24.453660 seconds 24.2367%

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/42573#issuecomment-939395180) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/ebef173_vs_bbe9375/report.md).

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/NanosoldierReports/tree/master/benchmark/by_hash/125170e_vs_1389c2f/report.md

**Pull request merged**
