### PR TITLE
do checkout before changing HEAD

### PR DESCRIPTION
**Pull request by simonbyrne**
According to the libgit2 docs, we should call `git_checkout_*` _before_ changing the HEAD ref. This is generally not a big problem as Pkg does a `force` checkout (which is probably not a good idea either, but that's for another day), except in a few edge cases.

Fixes both #17610 and #18420. Unfortunately, I have no idea how to test this.

### CODE REVIEW

**Comment by tkelman** [comment]
maybe we should try to create a test repo that hits one of those corner cases with permissions or file types changing?

**Comment by simonbyrne** [comment]
I guess, but is there a way to do it so that it works across all platforms?

**Comment by tkelman** [comment]
I don't think these issues were a problem on all platforms though. I'll have to test if they occur at all on Windows.

**Comment by simonbyrne** [comment]
Given the changes to LibGit2, a backport will need to be a bit different. Do you want me to put together another PR?

**Comment by tkelman** [comment]
let's see if/when 0.5.2 ends up being necessary before spending time on it, if non-trivial

**Comment by simonbyrne** [comment]
added a test.

**Review by tkelman — APPROVED** [review]
yay, thank you!

**Comment by tkelman** [comment]
What would the backport version of this look like?

**Comment by simonbyrne** [comment]
I guess just changing the order of `checkout_tree` and `GitReference`. Try the [`sb/libgit2/mads-backport`](https://github.com/JuliaLang/julia/tree/sb/libgit2/mads-backport) branch (I haven't tested it yet)

**Comment by tkelman** [comment]
Very nice, thank you, that does appear to fix the issue on 0.5. Will add the `cherry-pick -x` cross-reference and run that through PkgEval when I prepare 0.5.2.

**Pull request merged**
