### PR TITLE
Remove code coverage as a resource

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by kshyatt** [comment]
Could we not change this to link to codecov instead? Or is the idea that the badge in the README is enough?

**Comment by musm** [comment]
My idea was that the badge in the README is enough.

Plus is code coverage really a resource, didn't make sense to me.

**Comment by StefanKarpinski** [comment]
I often forget that badges are clickable and often scroll past them as visual noise (cool, lots of green!). They're also not searchable, so someone looking for coverage info could easily miss them. I agree, however, that coverage isn't really a resource. How about adding a new "Repo analysis and metrics" section with links to coverage, test results, maybe GitHub pulse, etc.? It can also explain the badges.

**Comment by musm** [comment]
Maybe someone else wants to takeover. I'm not too concerned with the current state. Closing in favor or a better PR.

**Pull request closed without merging**
