### PR TITLE
include the doc strings of `.=`, `.`, `->`, `::` into the docs

### PR DESCRIPTION
**Pull request by nsajko**

### CODE REVIEW

**Comment by nsajko** [comment]
I didn't yet check that this works as intended, will check the CI artifacts.

**Comment by nsajko** [comment]
Looking at the documentation PDF produced by CI, all four entries are successfully included into the *Keywords* subsection. Follow up PRs will add some cross-references.

**Comment by Seelengrab** [comment]
If this fixes https://github.com/JuliaLang/julia/issues/36290, it'd be good to link the two here :)

**Comment by nsajko** [comment]
This PR includes the doc string for `::` into the docs, but I don't know if that will make the search functionality be able to find `::`. I guess we'll find out when this is merged.

**Comment by Seelengrab** [comment]
Good point - I'm subscribed to this PR, so I'll check once it's merged. If it's fixed, I'll close #36290.

**Comment by nsajko** [comment]
ping

**Comment by nsajko** [comment]
ping

**Review by fatteneder — APPROVED** [review]

**Comment by Seelengrab** [comment]
It took a while until I remembered this, but it seems like this PR didn't fix `::` being unfindable in the docs.

**Comment by nsajko** [comment]
Well the doc string is here: https://docs.julialang.org/en/v1.12-dev/base/base/#::

**Comment by Seelengrab** [comment]
Yes, it's probably some issue with the filtering happening in JS... Not sure how much we can do about it, though I think there is an issue in Documenter.jl about this too.

**Pull request merged**
