### PR TITLE
precompile: do better union split and concrete compilation search

### PR DESCRIPTION
**Pull request by vtjnash**
This fixes some bugs that prevent compile-all from working correctly at all, and uses more of it for normal compile. Increases sysimg size from about 140 to 170 MB of data and 11 to 15 MB of code

### CODE REVIEW

**Comment by KristofferC** [comment]
The sysimage size is quite significant... There are no benchmarks and no tests that justify this yet, so adding those might make it more palatable.

**Comment by vtjnash** [comment]
I have some thoughts about improving system image size, but they don't involve being worse at choosing what code to compile as we are without this PR

**Comment by topolarity** [comment]
I'm inclined to agree with @vtjnash - this isn't really a policy change on what code to keep as much as it's a bugfix for all the code we weren't intending to delete / not compile

I think it's probably worth taking the hit to have a coherent caching policy

**Comment by nsajko** [comment]
This seems to be causing an `Unreachable reached` error: #56910

**Pull request merged**
