### PR TITLE
Doc some string parsing macros

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by strickek** [comment]
#27949 also cover this topic

**Comment by kshyatt** [comment]
@strickek thank you for pointing that PR out. Since those tests pass and it's more comprehensive, let's focus on getting that in a state to merge!

**Comment by StefanKarpinski** [comment]
FWIW, I think this PR is more complete for the macros that it covers and the other PR is a bit iffy for the other two macros (I had review comments on both), so I'd rather merge this now and then the other one can resolve the conflicts and include the best of both when it's ready.

**Comment by kshyatt** [comment]
Ah ok, reopen it then if you like

**Comment by StefanKarpinski** [comment]
Can't, there's a different PR on the same branch!

**Comment by KristofferC** [comment]
This PR should use the string macro syntax though `big"` etc.

**Comment by kshyatt** [comment]
@KristofferC I can show both?

**Pull request closed without merging**
