### PR TITLE
Backports for 1.7.3

### LINKED ISSUE #43411: Wrapping NamedTuple in struct is no longer bitstype in 1.7
cf brief discussion on [discourse](https://discourse.julialang.org/t/struct-wrapping-namedtuple-is-not-isbits-depending-on-how-it-is-defined/72965/9) 

This bug(?) occurs on 1.7 but not on 1.6: 

```Julia
struct Wrapper{SYMS, TT}
   x::NamedTuple{SYMS, TT}
end
randnt() = Wrapper((a = randn(), b = rand(), c = rand(1:5), d = randn(SVector{3, Float64})))
X = randnt()
@allocated randnt()  # 64
isbits(X)   # false
isbits(X.x)   # true 
```

But if the wrapper is defined differently then the `isbits == true` is recovered:
```Julia
struct Wrapper1{NT} 
   x::NT
end
randnt1() = Wrapper1((a = randn(), b = rand(), c = rand(1:5), d = randn(SVector{3, Float64})))
X1 = randnt1()
@allocated randnt1() # 0 
isbits(X1) # true
isbits(X1.x) # true
```
Because of this, it is easy enough to produce a work-around, but it feels like that shouldn't be necessary and the behaviour described above should not occur?

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```
(built from source)

### LINKED ISSUE #43921: Product iterator is not zipped properly
When zipping with a product iterator with no arguments (which produces only one output, the empty tuple), it seems the check for zip completion does not handle this case:
```
julia> for (z,) in zip(Iterators.product())
       @show z
       end
z = ()
ERROR: ArgumentError: tuple must be non-empty
Stacktrace:
 [1] first(#unused#::Tuple{})
   @ Base ./tuple.jl:140
 [2] _pisdone
   @ ./iterators.jl:1005 [inlined]
 [3] isdone
   @ ./iterators.jl:1012 [inlined]
 [4] _zip_isdone(is::Tuple{Base.Iterators.ProductIterator{Tuple{}}}, ss::Tuple{Tuple{Bool}})
   @ Base.Iterators ./iterators.jl:379
 [5] _zip_iterate_all
   @ ./iterators.jl:348 [inlined]
 [6] iterate
   @ ./iterators.jl:341 [inlined]
 [7] top-level scope
   @ ./REPL[79]:2
```

`versioninfo()` output:
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = vim
```
EDIT: `zip([()])` works fine though:
```
julia> for (z,) in zip([()])
       @show z
       end
z = ()

julia> 
```

### LINKED ISSUE #43960: wrong evaluation order for splatted args in `ref` expression
This was pointed out on slack:

```julia
julia> Meta.@lower a[f(x), g(y)...]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = g(y)
│   %2 = f(x)
│   %3 = Core.tuple(a, %2)
│   %4 = Core._apply_iterate(Base.iterate, Base.getindex, %3, %1)
└──      return %4
))))
```

I don't see any reason why `g(y)` should be evaluated before `f(x)`, so this can probably be considered a bug in lowering.

### LINKED ISSUE #44013: Evaluation order in LHS struct destructuring
Consider:
```
julia> struct Foo
          x
          f
       end

julia> f = Foo(1, 2)
Foo(1, 2)
```
we have:
```
julia> (; x, f) = f
2
```
but
```
julia> (; f, x) = f
ERROR: type Int64 has no field x
Stacktrace:
 [1] getproperty(x::Int64, f::Symbol)
   @ Base ./Base.jl:38
 [2] top-level scope
   @ REPL[6]:1
```
Also in the first case, the overall return is the new value of `f`, but I believe it would be more consistent to return the old value of f. I think the syntax should work in phases, where it collects all the values into ssa values and only then applies the updates.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #43426 
- [x] #43962 
- [x] #44020 
- [x] #44026 
- [x] #44004 
- [x] #44024 
- [x] #43571 
- [x] #44134 
- [x] #44060 
- [x] #44192 
- [x] #44196 
- [x] #43940 
- [x] #44212 
- [x] #44219 
- [x] #44078 
- [x] #44194 
- [x] #44265 
- [x] #44311 
- [x] #44305 
- [x] #44262 
- [x] #43291 
- [x] #44453 
- [x] #44464 
- [x] #44487 
- [x] #44629 
- [x] #44676 
- [x] #44770 
- [x] #44797 
- [x] #44972 
- [x] #44976 
- [x]  #43993 
- [x] #44810 
- [x] #44956 

Need manual backport:
- [ ] #44781 

Contains multiple commits, manual intervention needed:
- [ ] #43347 
- [ ] #43856 
- [ ] #44252 
- [ ] #44727 
- [ ] #43510 

Non-merged PRs with backport label:
- [ ] #43947 <!-- Fix isdone for empty product iterators, fixes #43921 --

### CODE REVIEW

**Comment by sostock** [comment]
#41513 and #42054 should be backported as well.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(!"scalar", vs=":release-1.7")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/44189#issuecomment-1102706708) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/623e70c_vs_857b62d/report.md).

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44189#issuecomment-1102705533) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6e5b031_vs_857b62d/report.html).

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ADNLPModels", "AssociativeArrays", "BestApproximation", "CalibrateEDMF", "Causal", "CrystalInfoFramework", "ExponentialUtilities", "FlashWeave", "Groebner", "HomotopyContinuation", "ITensorGaussianMPS", "ITensorVisualizationBase", "Infernal", "IntensityScans", "IntervalTrees", "KeplerTools", "MPSToolkit", "NumericalAlgorithms", "OrbitalTrajectories", "PProf", "Pfam", "Probably", "ProgressiveHedging", "QXTns", "QXTools", "RuntimeGeneratedFunctions", "SLEEFPirates", "SimpleBufferStream", "TensorNetworkCodes", "YaoQX"], vs = ":release-1.7")`

**Comment by giordano** [comment]
Can #44671 also be included here? :slightly_smiling_face:

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["ADNLPModels", "AssociativeArrays", "BestApproximation", "CalibrateEDMF", "Causal", "CrystalInfoFramework", "ExponentialUtilities", "FlashWeave", "Groebner", "HomotopyContinuation", "ITensorGaussianMPS", "ITensorVisualizationBase", "Infernal", "IntensityScans", "IntervalTrees", "KeplerTools", "MPSToolkit", "NumericalAlgorithms", "OrbitalTrajectories", "PProf", "Pfam", "Probably", "ProgressiveHedging", "QXTns", "QXTools", "RuntimeGeneratedFunctions", "SLEEFPirates", "SimpleBufferStream", "TensorNetworkCodes", "YaoQX"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44189#issuecomment-1105340343) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ccf7816_vs_857b62d/report.html).

**Comment by KristofferC** [comment]
Failure for BestApproximation is a bugfix from https://github.com/JuliaLang/julia/pull/44676 which makes the package test fail.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["AssociativeArrays", "BestApproximation", "HomotopyContinuation", "ITensorGaussianMPS", "ITensorVisualizationBase", "MPSToolkit", "NumericalAlgorithms", "QXTns", "QXTools", "TensorNetworkCodes", "YaoQX"], vs = ":release-1.7")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/44189#issuecomment-1105676045) has completed - possible new issues were detected. A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/86e06d3_vs_857b62d/report.html).

**Comment by DilumAluthge** [comment]
@staticfloat Will we need to turn on all of the buildbots for Kristoffer and Alex to be able to get binaries for this release?

**Comment by staticfloat** [comment]
Yes, I believe so.

**Pull request merged**
