### PR TITLE
Revert "Deprecate DevNull, STDIN, STDOUT, and STDERR to lowercase"

### PR DESCRIPTION
**Pull request by ararslan**
This reverts PR #25959. Lowercasing these identifiers conflicts with the statistical meaning of `stderr`, i.e. the standard error. This is defined in StatsBase and widely used.

### CODE REVIEW

**Comment by iamed2** [comment]
Can we just not export them? 

`stderr` search on Google waits until the 3rd page to show the statistical meaning. The next use was on page 7.

**Comment by StefanKarpinski** [comment]
`IO.stderr`, `IO.devnull`, etc. would be pretty good imo but `IO` is already a type so we either need a different name or some more name shuffling...

**Comment by KristofferC** [comment]
https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.sem.html

**Comment by iamed2** [comment]
Python puts them in `sys`, maybe `Base.Sys.stderr`?

**Comment by StefanKarpinski** [comment]
Sure, that would be a good place for them.

**Comment by JeffBezanson** [comment]
These seem much more important than most of the `Sys` module --- you need the standard error stream far more often than you need to know e.g. which model of CPU you have.

**Comment by StefanKarpinski** [comment]
The idea behind putting them in `Sys` is not because they're less important but to avoid taking a name that is commonly used in statistics.

**Comment by JeffBezanson** [comment]
I really don't think they fit in that module though. Everything else in `Sys` is basically hardware and OS reflection, nothing like critical I/O functionality.

**Comment by iamed2** [comment]
Has anyone felt the desire for an IO-related module for other reasons? Maybe it would be useful for other things.

**Comment by mbauman** [comment]
```julia
julia> Base.getproperty(::Type{IO}, s::Symbol) = s == :stdout ? Base.stdout : s == :stderr ? Base.stderr : throw(ArgumentError())

julia> IO.stderr
Base.TTY(RawFD(0x0000000f) open, 0 bytes waiting)

julia> show(IO.stderr, "HAHAHA")
"HAHAHA"
```

**Comment by JeffBezanson** [comment]
:sweat_smile:

**Comment by nalimilan** [comment]
> https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.sem.html

> Note that the SciPy stats.stderr function was deprecated in favor of stats.sem.  sem  is pretty short, but it doesn't seem terrible to do some sort of  renaming in StatsBase.   I suppose it makes the deprecation process more  painful, however. (From https://github.com/JuliaLang/julia/pull/25959#issuecomment-376656552)


@KristofferC @stevengj That's a different thing. `stderr` in StatsBase returns the standard error of the model coefficients, not of the mean. So it's more general (and could be used in other contexts than modeling). A possible name would be `se`, but it's quite short. `ste` would be consistent with `std`, but it's less standard.

**Comment by KristofferC** [comment]
`ste` sounds good.

**Comment by stevengj** [comment]
The stdio streams are used a lot more than the standard error function, so it doesn't seem crazy that the latter should be the ones to be renamed.  There are lots of reasonable options, e.g. you could just use `stderror` — lengthening it seems preferable to shortening it to an inscrutable abbreviation like `se`.

**Pull request closed without merging**
