### PR TITLE
Thread sleep/wakeup

### PR DESCRIPTION
**Pull request by kpamnany**
Logic is implemented (and mostly tested in C partr) but not yet hooked into the threads' run loops.

### CODE REVIEW

**Comment by kpamnany** [comment]
Doh. I'll fix those errors.

**Comment by JeffBezanson** [comment]
With this, we should be able to remove the `_threadedregion` variable, and rewrite `jl_threading_run` in julia simply by spawning tasks.

**Comment by JeffBezanson** [comment]
Here is a branch/commit to illustrate the next step:
https://github.com/JuliaLang/julia/commit/5fe357af3e29e2e004ea4609276a546bdcd0dce8
There I have added the straw man API `@par * ...` to schedule code with the shared queue and `@par n ...` to schedule code on a specific thread.
It also allows the code here to at least compile by removing the old cruft.

**Comment by JeffBezanson** [comment]
Replaced by #32029.

**Pull request closed without merging**
