### PR TITLE
Fix #10222.

### LINKED ISSUE #10222: Unrecognized input on insert key after arrow-up
This is just a small bug i stumbled upon by accident. 
Going through the REPL history with the arrow-up key and pressing the insert key 
results in
```julia 
julia> 1
1
(#--- pressing arrow-up once followed by the insert key---#)
julia> 1ERROR: Unrecognized input
 in error at error.jl:19
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1565
 in run_interface at ./LineEdit.jl:1538
 in run_frontend at ./REPL.jl:828
 in run_repl at ./REPL.jl:157
 in _start at ./client.jl:445
```
and being send back to the shell.

My julia version is:
```julia 
julia> versioninfo()
Julia Version 0.4.0-dev+3164
Commit d615d3e (2015-02-06 16:44 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I tried this in zsh and bash.

### PR DESCRIPTION
**Pull request by blakejohnson**
Add terminal mode changes to `escape_defaults`. Catches things like pressing the
insert key on some terminal emulators.

@flpf please confirm that this fixes the reported issue.

### CODE REVIEW

**Comment by flpf** [comment]
Applying this patch fixes the error in ```st```. Doing the same in ```gnome-terminal``` still gives me an error:
```julia 
julia> 1
1
julia> 1ERROR: Unrecognized input
 in error at error.jl:19
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1576
 in run_interface at ./LineEdit.jl:1549
 in run_frontend at ./REPL.jl:828
 in run_repl at ./REPL.jl:157
 in _start at ./client.jl:455
```
The char sequence for the ```insert``` key is ```[2~```.

**Comment by blakejohnson** [comment]
@flpf thanks for testing. I didn't catch that we don't grab `\e[2~`, either. I cannot find documentation on that particular escape code anywhere, so it is bizarre that gnome-terminal uses it.

**Comment by flpf** [comment]
Mmh, curious. If I do a ```C-v```+```insert``` in ```st``` it prints out the same 
char sequence. 
I've tried this with ```zsh``` and ```bash``` (with and without  ```tmux```) in ```st```,```gnome-terminal``` and ```xterm``` all printing the same sequence ```^[[2~``` (```^[``` being the ```Control-V``` combination). 
But only a julia session in ```st``` seems to catch the ```insert``` key correctly, all others 
quit with the above error message. 
Is there a gettable way to debug this for me? I haven't had time to really dive into julias core functions but maybe I should do it now to let you know what is going on under the hood.

**Comment by blakejohnson** [comment]
@flpf I found some docs on that escape code. Turns out it is standard VT220. I have another fix ready, but I am preparing a proper test.

**Comment by flpf** [comment]
OK. Let me now if there is anything I can do to help.

**Comment by blakejohnson** [comment]
@flpf ok, could you test again?

**Comment by flpf** [comment]
Rebuilding...

**Comment by blakejohnson** [comment]
Lovely, I seem to have broken the test suite.

**Comment by flpf** [comment]
But on the bright side I can report that the patch seems to be working here. No more errors in ```gnome-terminal``` or ```xterm```.

**Comment by blakejohnson** [comment]
@Keno do you have any insight into how my couple lines of additional test code on `test/repl.jl` could have broken the test suite? If I comment them out, the rest of this PR is fine.

**Comment by blakejohnson** [comment]
@Keno never mind... appears you can't leave data dangling in a `Pipe`.

**Comment by blakejohnson** [comment]
I don't know what to make of the conflicting travis reports. Shall I proceed to just merge this?

**Comment by Keno** [comment]
I restarted Travis. If it's green after, go ahead and merge.

**Comment by ivarne** [comment]
Travis was green.

**Pull request merged**
