### PR TITLE
RFC: Fix Contributing.md

### PR DESCRIPTION
**Pull request by Agnik7**
This PR is with respect to issue #51556 

The work is still in progress in this PR

### CODE REVIEW

**Comment by jakobnissen** [comment]
You can mark your PR as a draft PR when it's still WIP - this way, other developers know not to review it before it's ready

**Comment by Agnik7** [comment]
Requesting for review by the maintainers. Thanks!!!

**Comment by KristofferC** [comment]
Most of these do not look like clear improvements and are mostly stylistic choices.

**Comment by ViralBShah** [comment]
In my opinion, these changes are not necessarily making it better. My preference is to leave things as they are.

**Pull request closed without merging**
