### PR TITLE
RFC: Make dlopen return a DLHandle object instead of a raw pointer

### PR DESCRIPTION
**Pull request by garrison**
Currently, the `dlopen` family of functions return raw pointers.  Unfortunately, this means that if `dlopen` is called without an accompanying call to `dlclose`, memory (a struct the size of two pointers) will be leaked upon each call.

This pull request modifies `dlopen` to return a `DLHandle` object, which itself contains a pointer.  A finalizer is added for this object so that the memory is always unallocated, even if `dlclose` is not called.

Admittedly this is an incredibly small memory leak, but fixing it ~~seems to require some API breakage at some point~~ seems to require a slight change in API.  Hence, I am bringing it up now and looking for feedback on the solution.  ~~One thing to note: the current pull request **will** break `BinDeps`, though I am sure it could be modified to accommodate this change.  I don't expect this is worth doing before 0.4 though.~~  The latest version of this pull request works with BinDeps without modification.

(BTW, when combined with #10856, fixing this will reduce the number of "definite" memory leaks when running `julia -e ""` to zero!)

### CODE REVIEW

**Comment by ScottPJones** [comment]
Nice :+1:

**Comment by yuyichao** [comment]
Is it impossible to just register the finalizer on the `Ptr` object? IIRC the finalizer is not bind to a type but an instance.

Also, can a symbol obtained with `dlsym` still be used after `dlclose` is called?

**Comment by yuyichao** [comment]
http://stackoverflow.com/questions/26131102/is-it-safe-to-call-dlclose-after-dlsym

**Comment by ScottPJones** [comment]
@yuyichao The experts need to speak on this, but I read that finalizer behavior is undefined on bitstypes... and Ptr{} is a bitstype, so that won't work AFAIK.

**Comment by yuyichao** [comment]
Ahh. That makes sense. The concern of closing the library while the library is in use still holds though...

**Comment by ScottPJones** [comment]
@yuyichao Yes, I don't think you can while you still have any pointers into it... so you'd need to copy the symbols into Julia's memory before closing... (people do it anyway, and just are lucky that the OS hadn't *yet* reclaimed the memory and overwritten it)

**Comment by ihnorton** [comment]
Couldn't we store a list of handles and just dlclose them all on exit? Seems like that would make valgrind happy.

**Comment by ScottPJones** [comment]
Wouldn't that mean though that the handles couldn't be garbage collected until exit?
Maybe if the handles are wrapped like this, the finalizer for the handle could remove the raw pointer from the set of handles to be dlclosed on exit? (you store just the raw pointer into the set, not the handle).

**Comment by garrison** [comment]
@yuyichao The finalizer actually does not call `dlclose` for the reason you point out; instead it simply frees the memory used for the handle (a struct of `uv_lib_t`).

@ihnorton If the goal is simply to make valgrind happy, that is an alternative that would work.  But if somebody were naive enough to call `dlopen` in a function that gets called repeatedly, the memory use would increase throughout execution of the program, so while not technically "leaked" would have the same result of increased memory usage.

**Comment by ihnorton** [comment]
@garrison I think that goes in the `Don't do stupid stuff: we won't optimize that.` section of the manual!

I do wonder if we could make this non-breaking with a `convert` or two (ideally hooked in to `@deprecate`).

(cc @vtjnash @staticfloat)

**Comment by wildart** [comment]
> But if somebody were naive enough to call dlopen in a function that gets called repeatedly

From [Murphy's laws site](http://www.murphys-laws.com/): When designing a program to handle all possible dumb errors, nature creates a dumber user.

**Comment by staticfloat** [comment]
Why does this have to break `BinDeps`?  I think we should be able to engineer this in such a way that the types being returned by `dlopen()` and being passed into `dlclose()`, `dlsym()`, etc... don't matter and the behavior of the underlying objects is the same.

From the changes you've got listed here, I don't see why this would break `BinDeps`, but I could be overlooking something.  Could you show how the breakage manifests itself?

**Comment by garrison** [comment]
@staticfloat BinDeps currently makes some [pretty serious assumptions](https://github.com/JuliaLang/BinDeps.jl/blob/0ff7ad492955bca87155f62511ac37d662616de3/src/dependencies.jl#L512-L516) about what a `handle` looks like.  This should probably be cleaned up regardless.

**Comment by garrison** [comment]
Perhaps I overstated when I said this change requires API breakage.  Code that uses `dlopen` etc in a normal way does not need to break.  But code that makes detailed assumptions about the inner workings of `dlopen` *will* break, and at the moment that happens to include BinDeps.

**Comment by wildart** [comment]
I think it should be `jl_unload_dynamic_library` that correctly frees memory and closes handle. So, you would not need to do it separately through a finalizer and then an explicit call of `uv_dlclose`. What if somebody decides manually unload library? I would appreciate manual resource management to finalizers, see #11207. I wouldn't go in a such length to automate simple opening/closing file routing. BTW, there is `atexit` function after all.

**Comment by garrison** [comment]
This pull request does not call `dlclose` in the finalizer.  It simply frees the allocated memory when the handle is garbage collected (unless `dlclose` was already called explicitly).

**Comment by wildart** [comment]
Why would you do this separately: free memory allocated for the pointer and close resource at the pointer?

**Comment by garrison** [comment]
@wildart sorry, I don't understand what you are suggesting.

**Comment by wildart** [comment]
You created additional wrapper resource in Julia, which could be substituted by simple call of C function.

**Comment by garrison** [comment]
The goal is to prevent the object returned by `dlopen` from leaking memory if `dlclose` is never called.  I don't see how what you suggest accomplishes this.  Also, if `dlclose` is not called, there are good reasons **not** to close the handle (see [here](https://github.com/JuliaLang/julia/pull/11293#issuecomment-102613610) and [here](https://github.com/JuliaLang/julia/issues/10938#issuecomment-95001415)).

**Comment by wildart** [comment]
I would not try to substitute bad programming habits (not releasing system resources) with unreliable techniques (finalizers). The example with `openmp` is perfect. You do not need to repeatedly load and unload DLL that takes a lot of time to initialize global variables. Instead, it should be loaded at the beginning of the execution and released at the end.

**Comment by garrison** [comment]
> and released at the end.

Actually, the better strategy is never to release it.

**Comment by wildart** [comment]
Then there going to be memory leak, because it is not only DLL handle but as well memory for `uv_lib_t` structure.

**Comment by garrison** [comment]
The DLL handle (as returned by uv's call to C's `dlopen`) never needs to be explicitly freed.  The `uv_lib_t` should be freed, which is precisely what this pull request accomplishes.

**Comment by wildart** [comment]
I just want to point that finalizers are not reliable facility. From point of `dlopen` to GC event, that will call finalizer, could take some time, if ever. In this case, the resource not going to be freed.

BTW, there are many programming languages that provide automatic memory management, but none of them are able to automate system resource handling. So, why try to do that? Let's be carefull with system resources, as it should be, and not rely on any automation.

**Comment by garrison** [comment]
OK, I have an updated version of this pull request.  I left the old API that used raw pointers, so BinDeps is no longer broken by this change.  (We can deprecate this API at some point in the future.)  I also tested BinDeps pretty thoroughly to make sure everything still works.

**Comment by tkelman** [comment]
Are we sure there was consensus on this one? Please keep a very close eye on PkgEvaluator results for the next few days.

**Comment by yuyichao** [comment]
What's the plan for `jl_exe_handle` and `jl_dl_handle`?
They can be loaded with `cglobal` and are still the raw handle.

**Comment by stevengj** [comment]
So what do you pass to `ccall`?  The `DLHandle` or the raw pointer, or either one?

**Comment by stevengj** [comment]
In general, please don't merge PRs that are missing documentation.

**Comment by garrison** [comment]
Sorry, I was in retrospect too eager to push the merge button for my first time.  At the moment `ccall` still expects the raw pointer.  I am unsure the best way to handle this.

**Comment by staticfloat** [comment]
Can we create another `ccall` method that expects a `DLHandle`?

**Comment by yuyichao** [comment]
Also `cglobal`. It probably requires moving this to C and if the old interface is to be deprecated, all the interfaces that is currently exposing a `libuv` handle need to return a `DLHandle`.

**Comment by garrison** [comment]
I see the use of `cglobal` in PyCall, but I'm having a hard time finding a place where a dlhandle/pointer is passed to directly to `ccall` (without going through `dlsym` first).

In my opinion it should be no surprise that `cglobal` returns a raw pointer, not a wrapped `DLHandle` object.

**Comment by yuyichao** [comment]
What I meant was not making `cglobal` returning a `DLHandle` object (since it is usally not a handle), rather to make `jl_dl_handle` and `jl_exe_handle` a `DLHandle` if you were to deprecate the methods that accept raw pointers.

**Comment by ihnorton** [comment]
@garrison if you don't get a response on a PR you want to merge, the (unwritten) convention -- especially for a fairly deep change like this -- is to say something like "Will merge tomorrow, barring any objections".

**Comment by garrison** [comment]
@ihnorton, Thanks, duly noted.

**Comment by vtjnash** [comment]
Can I ask for this to be reverted? 

It caused unnecessary breakage (https://github.com/JuliaLang/Gtk.jl/issues/151) and I'm still not clear on what issue it solved. (The issue above seems to say that an invalid usage of dlopen withou dlclose also causes a valgrind wanting, so his PR silences valgrind in a complicated way)

**Comment by tkelman** [comment]
Given the breakage vs the seemingly small benefit, I'm +1 on reverting for now. We should be able to satisfy valgrind in some other way that doesn't break packages which currently depend on implementation details of `Libdl`. Though it is enlightening to identify in what way packages are doing so, so we can tweak the API going forward.

**Comment by garrison** [comment]
We will also need to revert stevengj/PyCall.jl#144.

I think it makes a lot of sense for the "opaque handle" returned by `dlopen` to be an object, not a raw pointer.  This will put it in line with various other julia API's, including files, sockets, etc.  So I think the terms of the debate should really be in terms of what API makes the most sense, with the memory leak being a secondary consideration (even though it is what got me thinking in this direction).

I had checked the package pulse but mistakenly did not recognize the Gtk failure as being due to this.  Sorry about that.

Reverting for now is fine by me.

**Comment by yuyichao** [comment]
Reverting my pycall.jl PR is totally fine (and easy to do)

**Comment by StefanKarpinski** [comment]
+1 for returning objects instead of bare pointers. @vtjnash, how come the issues with Gtk can't be fixed? This seems like a pretty straightforward change to adjust to – in the worst case you can replace `dlopen(lib)` calls with `dlopen(lib).ptr`. Let's not cause unnecessary flapping in the libraries that have *already* adjusted to this change.

On the other hand, this should have been discussed more extensively before merging.  Also, could we backport this change to 0.3 in Compat?

**Comment by yuyichao** [comment]
`dlopen().ptr` won't work because the pointer will be freed by GC

**Comment by StefanKarpinski** [comment]
Yeah, sorry, just realized that. I guess you need to save the pointer somewhere by assigning to a global. The only case where I can see that being a problem, however, is if you open a *lot* of libraries – in which case this was a legitimate memory leak. @vtjnash, can say a little more about why this can't be worked around in Gtk.jl?

Regarding backporting in Compat, it should be pretty straightforward to define `DLHandle` there and all its methods and then replace `dlopen` calls in the `@compat` macro with calls to the version provided by Compat.

**Comment by garrison** [comment]
I think making `DLHandle` an alias to `Ptr` (or `Ptr{Void}` perhaps) for old versions in `Compat`, and then using `DLHandle` in Gtk.jl and others where `Ptr` is currently used would fix all known breakage.

**Comment by vtjnash** [comment]
> +1 for returning objects instead of bare pointers

Why?

What problem does this solve that we need to allocate twice as many objects for the GC to track and 3 times as many bytes to track the dlopen handle? True that it is small relative to the size to the actual dlopen, but that still doesn't explain why it is needed.

**Comment by StefanKarpinski** [comment]
Because dlopen acquires a resource which ought to be released when the program is done using it. For that kind of pattern, we consistently use mutable objects with finalizers. We do that with file handles. We do it with regular expressions. We do it with BigInts. We do it with BigFloats. Give any other example of a resource that we just represent with a bare pointer. Objecting to an extra object and a few dozen bytes of overhead for an entire *shared library* is kind of absurd. If the overhead is acceptable for file handles, then it's acceptable for shared libraries.

**Comment by vtjnash** [comment]
Ok, that sounds valid, but that's also not what this PR does. This only frees the pointer to the overhead and does not unload the actual resource.

**Comment by JeffBezanson** [comment]
I'd also prefer to revert this. It's silly to go to all this trouble and fussing around to free 2 words. For example, could we instead allocate the handle as a julia object in the first place instead of with malloc? Then you wouldn't need a finalizer.

**Comment by ihnorton** [comment]
If we [stop using `uv_lib_t`](https://github.com/JuliaLang/julia/pull/11488#issuecomment-107914702) then a handle might not be necessary at all. `uv_lib_t` basically exists return error messages, which won't be necessary if we are handling errors directly.

**Pull request merged**
