### PR TITLE
Test one-line pass through for CachingPool

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by amitmurthy** [comment]
What is the need for this?

**Comment by kshyatt** [comment]
Missed line in coverage in `workerpool.jl`

**Comment by amitmurthy** [comment]
Which line? This is not the correct way to initialize a `CachingPool`...

**Comment by kshyatt** [comment]
https://codecov.io/gh/JuliaLang/julia/src/bb8a8018d5d749fae40ecf9901b7a186d7cf46ed/base/workerpool.jl#L266

**Comment by amitmurthy** [comment]
Now I don't remember why I put that constructor in. I think we should just remove it....

**Comment by kshyatt** [comment]
😆  well in that case, I can change this PR to remove that line!

**Comment by amitmurthy** [comment]
Thanks.

**Pull request merged**
