### PR TITLE
Updated Juno documentation shortcut

### PR DESCRIPTION
**Pull request by erihe251**

### CODE REVIEW

**Comment by tkelman** [comment]
We prefer making pull requests against master, not the release branch. Changing the base branch kind of made a mess there, sorry.

**Comment by erihe251** [comment]
@tkelman Wow, sorry for that! Clicked the "Edit on GitHub" link in the documentation and assumed it went to the right place.

**Comment by tkelman** [comment]
could you either rebase this branch or open a new copy against master? the edit button on github does the right thing if you start from looking at master, but readthedocs defaults to editing whatever version you're looking at. if we move off of readthedocs then whatever "edit on github" functionality the replacement has should suggest checking master first to confirm if the change applies there.

**Comment by erihe251** [comment]
Rebased. One quick fix would be to default docs.julialang.org to "latest", but I guess that's undesirable for other reasons.

**Comment by tkelman** [comment]
Is this correct on all platforms?

**Comment by erihe251** [comment]
Yes, taking C to mean cmd on OSX it should be the same on all platforms according to the julia-client atom keymap file.

Am 7. September 2016 05:36:16 MESZ, schrieb Tony Kelman <notifications@github.com>:
>Is this correct on all platforms?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JuliaLang/julia/pull/18333#issuecomment-245165760

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
