### PR TITLE
Privatise the annotations API, for StyledStrings

### PR DESCRIPTION
**Pull request by tecosaur**
This is a counterpart to a modification to the StyledStrings stdlib (https://github.com/JuliaLang/StyledStrings.jl/pull/81) that together shift the annotated API from being part of Base's API to part of the StyledStrings API.

This is done to open the door to some of these types/function potentially being implemented in StyledStrings directly, without breaking any public API.

### CODE REVIEW

**Comment by tecosaur** [comment]
If we go ahead with this, yes.

**Comment by LilithHafner** [comment]
CI is failing but the API change LGTM

**Comment by tecosaur** [comment]
To make CI happy I might need to merge the StyledStrings PR and include a bump: the failing components is docs generation which contains `Base.Annotated...` references from the current StyledStrings version.

**Comment by KristofferC** [comment]
Yes, this should be merged so StyledStrings need to be updated

**Comment by LilithHafner** [comment]
This will be breaking if it merges after the 1.11 release. Adding it to the milestone.

**Comment by tecosaur** [comment]
For those that haven't looked at the linked PR and are wondering what the holdup is, it's me figuring out how to make Documenter happy with this relocation/change.

**Comment by tecosaur** [comment]
I think this is no longer needed with no solution for the documented difficulties in sight, and #55845 merged.

All that remains is for a `StyledStrings` bump to happen after https://github.com/JuliaLang/StyledStrings.jl/pull/81 is merged (which I'll do shortly if there are no issues raised with it).

**Comment by DilumAluthge** [comment]
This PR was closed without being merged. Therefore, I will remove the backport labels.

**Pull request closed without merging**
