### PR TITLE
more reliable extraction of information from typeinfo

### PR DESCRIPTION
**Pull request by rfourquet**
This contains two commits:
1) the initial choice of using `Any` to mean that no information is provided via typeinfo was unfortunate, leading to some ambiguities and difficulty to reason (the comments were "full of weasel words and warnings that it is not correct in certain cases!", in Stefan's words); so we use `nothing` instead;
2) we used a system such that if we know via typeinfo that e.g. `typeinfo = AbstractVector{Integer}` is printed, and we get a `Vector{Integer}`, we will know that `Integer` is already printed in the context. But the implementation was very brittle: we were just taking `eltype(typeinfo)` to compute this. But this fails in some cases because `eltype(x)`  defaults to `Any`, for example `typeinfo = Vector`. This makes a difference in an example like `Vector[Any[1]]`. Hence here we don't take blindly `eltype` anymore, only for collections with known eltype (e.g. `AbstractArray{T} where T`).

Note: for 1), I hesitated to use `Union{}` instead of `nothing`, as it's a bit annoying to have to test first `typeinfo !== nothing` before `x isa typeinfo`, as `isa` errors out when `typeinfo == nothing`. But this doesn't seem so clean to use `Union{}`, thoughts?

### CODE REVIEW

**Comment by rfourquet** [comment]
This was all green but there is a small conflict now... shall I rebase this to get it merged, or does this need more time/discussions?

**Comment by rfourquet** [comment]
If no objection, I will merge this tomorrow. It fixes two problems and makes the typeinfo system more robust overall.

**Comment by JeffBezanson** [comment]
Ok.

**Comment by JeffBezanson** [comment]
> The problem we had was coming from the fact that we used eltype in the implementation of typeinfo_eltype

This is worrying --- now `typeinfo_eltype` basically re-implements `eltype` for arrays, sets, and dicts. Calling eltype would be better, so that the implementation is done by those types themselves. Could you explain more on why this is needed?

**Comment by JeffBezanson** [comment]
Using `HasEltype` might also be an option here.

**Comment by JeffBezanson** [comment]
Interesting failure on travis. I'm seeing if it reproduces locally.

**Comment by JeffBezanson** [comment]
...and it doesn't. :(

**Comment by rfourquet** [comment]
I couln't either reproduce the failure locally... The same error seems to have happened in two distinct tests on the two travis machines.
Should I re-push to restart travis CI ? Is it fine to merge as is?

**Comment by rfourquet** [comment]
So I'm gonna merge as this is now non-breaking and just fixes bugs.

**Pull request merged**
