### PR TITLE
Use OpenBLAS with updated NUM_THREADS to fix #43008 

### LINKED ISSUE #43008: 1.7.0-rc2: StackOverflowError with complex-valued matrix exp
On macos, using version `1.7.0-rc2`, julia just shows `StackOverflowError` with no other info when taking the matrix exp with a ~ 300x300 complex-valued matrix. Minimum example:

```
using LinearAlgebra

n = 300
m = rand(ComplexF64, n, n);
mex = exp(m);
```

Alro ran with `--startup-file=no` to make sure it's not some clash with other packages.

Screen Shot 2021-11-08 at 5 52 35 PM

my `versioninfo()`:

```
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_MATHLINK = /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework
  JULIA_MATHKERNEL = /Applications/Mathematica.app/Contents/MacOS/MathKernel
```

Same code runs fine with `Version 1.6.3 (2021-09-23)`.

Hardware: Macbook pro (intel) with 16 GB ram, activity monitor shows low memory usage. 

In addition, the same code sometimes gives `ERROR: LoadError: ReadOnlyMemoryError()`, not sure how to reproduce that one...

Thanks!

### PR DESCRIPTION
**Pull request by daviehh**
Tested locally, the OpenBLAS built with 3cc8b0f45c5f39e22373233b4ad65a84834c57be [link1](https://github.com/JuliaPackaging/Yggdrasil/pull/3766), [link2](https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/commit/d73a7f6dcacdabd84d561b05a1c1cfa96dc76347) should fix the StackOverflowError  https://github.com/JuliaLang/LinearAlgebra.jl/issues/886

Following an earlier comment https://github.com/JuliaLang/julia/pull/43013, this PR not a new version of openblas so should be fine now? Possibly need the 1.7 tag since matrix exp is quite important and is now somewhat broken in 1.7.0-rc2. Thanks!

### CODE REVIEW

**Comment by ViralBShah** [comment]
This PR also increases the NUM_THREADS to 512, which has been reasonably tested on master by now, but should be tested much more widely. Since a broken matrix exponential is quite bad, we may want another RC if we want to merge this PR. Otherwise we could also wait to have this in 1.7.1.

**Comment by ViralBShah** [comment]
What is the resolution here?

**Comment by ViralBShah** [comment]
We need to get this into 1.7 rc4. I don't see it on `release-1.7` - so what do we need to do? Was this PR prepared incorrectly?

**Comment by DilumAluthge** [comment]
I think this PR was automatically closed by GitHub because the base (target) branch was deleted.

**Comment by ViralBShah** [comment]
Should this have a `backport 1.7` label on it?

**Comment by DilumAluthge** [comment]
@daviehh Can you rebase this PR on the latest version of the `JuliaLang/julia:backports-release-1.7`?

**Comment by daviehh** [comment]
@DilumAluthge thanks, now just updated against the latest `backports-release-1.7` branch.

**Comment by jaakkor2** [comment]
This PR fixes https://github.com/JuliaSIMD/LoopVectorization.jl/issues/364 on 1.7-branch.  On master (1.8)-branch https://github.com/JuliaLang/julia/pull/42708 fixed it.

Reason unbeknownst to me.

**Pull request closed without merging**
