### PR TITLE
Bump openlibm to v0.7.4.

### LINKED ISSUE #39462: Segmentation fault: fesetenv at libopenlibm resurfaces in aarch64
_Encountered this bug while using CUDA.jl but @maleadt confirms it as julia bug on slack_

**`c = a .+ b` failed. Both a and b are small cuda arrays.**

```
signal (11): Segmentation fault
in expression starting at REPL[4]:1
**fesetenv at ./julia-1.6.0-beta1/bin/../lib/julia/libopenlibm.so (unknown line)**
unknown function (ip: 0x7f2049e7cf)
Allocations: 44366399 (Pool: 44353014; Big: 13385); GC: 49
Segmentation fault (core dumped)
```

Reproducible on aarch64 platform, NVIDIA AGX hardware.

**Fails in Julia:**
- 1.6.0 beta aarch64 prebuilt version; 
- aarch64 nightly build version;
- git source build on aarch64

**Other details:**

- CUDA : v2.6.1 installed through package manager.

@maleadt also confirms its relation to #38427; Suggested reopening the issue.

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaLang/julia/issues/39462, https://github.com/JuliaLang/julia/issues/38427

### CODE REVIEW

**Comment by maleadt** [comment]
aarch64 is the hard kill repl test failure.

**Comment by fredrikekre** [comment]
Why are some checksums not replaced?

**Comment by maleadt** [comment]
Hm, something must have gone wrong there. Fixed now.

**Comment by KristofferC** [comment]
Could have been squashed.

**Comment by maleadt** [comment]
> Could have been squashed.

There was only a single commit in here?

**Comment by KristofferC** [comment]
I meant no need to create a merge commit. Oh well, does t really matter.

**Pull request merged**
