### PR TITLE
move `clipboard` to InteractiveUtils

### PR DESCRIPTION
**Pull request by JeffBezanson**
This seems like an odd thing to have in Base.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
Nice, I'm surprised this didn't go when InteractiveUtils was initially separated. Unfortunate that our only test for the clipboard functionality is Windows-specific.

Needs a NEWS entry, but other than that LGTM.

**Comment by JeffBezanson** [comment]
I actually don't know why that test is restricted to windows. It works on my linux system FWIW.

**Comment by StefanKarpinski** [comment]
Try removing the condition and see if the PR passes CI everywhere?

**Comment by JeffBezanson** [comment]
Ah, of course. Linux CI doesn't have the necessary stuff installed. We can at least extend the test to mac os though.

**Pull request merged**
