### PR TITLE
Implemented strides for AbstractArray subtypes

### LINKED ISSUE #29705: `strides` missing methods for various  AbstractArray subtypes
Seems like some simple methods are missing for `strides` function
```
julia> strides(randn(5,5)')
ERROR: MethodError: no method matching strides(::LinearAlgebra.Adjoint{Float64,Array{Float64,2}})

```

similarily
```
julia> strides(transpose(randn(5,5))
```
and also other basic subtypes of `AbstractArray` such as `Diagonal` etc.

### PR DESCRIPTION
**Pull request by raghav9-97**
Fixes #29705

### CODE REVIEW

**Comment by mbauman** [comment]
Thanks for the contribution! We should probably make the documentation of `strides` a bit more clear — it doesn't give you the multipliers you need to compute a linear index, but rather it defines how to find a given location _in memory_ as an _offset_ from a base pointer.

This means, that, for example `strides(view(rand(10), 1:2:10)') should be `(1, 2)` and not `(1,1)`.  It also means that we cannot support `strides` on `Diagonal` as its memory layout does not conform to the StridedArray interface.

See https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-strided-arrays-1 for a bit more detail — but probably still not quite enough.

**Review by mbauman — CHANGES_REQUESTED** [review]
Define `strides(::AdjOrTrans)` in terms of the strides of its parent, and remove the strides definition for Diagonal

**Comment by raghav9-97** [comment]
If i am correctly understanding strides ```strides(rand(3,5))`` should generate (1,3) and ```strides(rand(3,5)')``` will generate (1,5)?

**Comment by mbauman** [comment]
It's even simpler than that — you just want to reverse the strides of the parent.  Oh my, now that I write that out, it's sounding very familiar to me…

Yup, shucks.  https://github.com/JuliaLang/julia/pull/29135.  I have a really bad habit of submitting PRs and then forgetting all about them.

**Comment by raghav9-97** [comment]
@mbauman Haha!! You've already implemented it way before than me?Should I continue working on this?

**Comment by ViralBShah** [comment]
@mbauman Should we merge your old PR, or should @raghav9-97 prepare this one to be merged?

**Pull request closed without merging**
