### PR TITLE
RFC: Macro for delegating methods to the fields of a composite type

### PR DESCRIPTION
**Pull request by johnmyleswhite**
As discussed long ago on the mailing list (https://groups.google.com/d/msg/julia-dev/MV7lYRgAcB0/s6_RMeHLpEYJ), I've created a simple `@delegate` macro that allows one to delegate methods to the fields of a composite types. An example is shown below in which a new container type can delegate methods like `size` and `length` to an array contained inside of it:

```
type MyContainer
    elems::Array
end

importall Base

@delegate MyContainer.elems [size, length]

x = MyContainer([1, 2, 3, 4])

size(x)
length(x)
```

Right now, this only supports functions for which the first argument is the field which delegated methods need. Before we merge this, I think we'll want to find a clean generalization.

### CODE REVIEW

**Comment by benninkrs** [comment]
Sorry to revisit a closed issue, but can anyone say what the status of this is? As far as I can tell, the language features that were envisioned to support delegation (namely the ability to subtype functions and overload `call` for these functions, see #1470) have not been implemented.

**Comment by Ismael-VC** [comment]
@quinnj could we reopen this PR?

**Comment by Ismael-VC** [comment]
Something like this I mean:

```julia
using Base.Meta: quot

macro delegate(source::Expr, targets::Expr)
    source.head ≠ :. && error("syntax: expected `Foo.bar` form")
    targets.head ≠ :vect && error("syntax: expected vector of function names")

    type_name = source.args[1]
    field_name = source.args[2].value
    func_names = targets.args
    n = length(func_names)
    block = Expr(:block)

    for func_name in func_names
        expr = quote
            function $func_name(a::$type_name, args...)
                $func_name(a.$field_name, args...)
            end
        end

        push!(block.args, expr)
    end
    return esc(block)
end

macro delegate(source::Expr, target::Symbol)
    source.head ≠ :. && error("syntax: expected `Foo.bar` form")

    type_name = source.args[1]
    field_name = source.args[2].value

    :($target(a::$type_name, args...) = $target(a.$field_name, args...)) |> esc
end
```

I'd just need the syntax you guys expect in all corner cases, to implement it. Julia 1.0 is on the horizon and I really think we should make composition via delegation, easier, more julian.

**Comment by StefanKarpinski** [comment]
Feature freeze for 1.0 is [December 15th](https://discourse.julialang.org/t/1-0-feature-freeze-dec-15th/7209), so we're not adding any more features to the release at this point without very significant justification. However, new features can be added in 1.x versions as long as they don't break older code.

**Pull request closed without merging**
