### PR TITLE
Unrevert #34347 and bump Pkg to a version that is compatible with it

### LINKED ISSUE #34317: enable color output whenever stdout is a TTY
Running e.g. `./julia -e '@warn "foo"'` there is no color output unless `--color=yes` is passed. That makes sense when stdout is redirected, but arguably color should be the default when stdout is a TTY.
(Originally reported on slack.)

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes https://github.com/JuliaLang/julia/issues/34317

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Would be great to get a PkgEval on this, right?

@maleadt

**Comment by KristofferC** [comment]
Not really. Why? I tested that `Pkg.test` isn't broken here.

**Comment by maleadt** [comment]
No need to run all the tests though, as this broke all packages:
@nanosoldier `runtests(["Example"], vs = ":master")`

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["Example"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/35390#issuecomment-610822343) has completed - no new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/59810c1e673dccbac5890b4467e7b563ccd56d1a/pkgeval/by_hash/4a2d63d_vs_7daa424/report.md). cc @maleadt

**Comment by KristofferC** [comment]
> We could make this more backwards compatible by keeping have_color as a boolean with roughly the meaning it had before, and using a new name for the 3-valued variable we use internally.

Let's get his back in since quite a lot of time was spent on reviewing and fixing up the original PR and then we can add the extra backwards compat later if we think it is needed (perhaps from a full PkgEval at some point).

**Pull request merged**
