### PR TITLE
Revert "upgrade libuv to v2-1.42.0" and revert "add stream shutdown and support half-duplex operation" 

### PR DESCRIPTION
**Pull request by DilumAluthge**
The first commit reverts JuliaLang/julia#41710

The second commit reverts JuliaLang/julia#40783 by way of JuliaLang/julia#41808

Only the first commit should be backported to `release-1.7`.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Before merging this PR, we should make sure that:
1. FreeBSD CI (both packager and tester) is passing
2. The FreeBSD CI jobs ran on the FreeBSD 11 workers (workers that end in `amdci6_1`, `amdci6_2`, or `amdci6_3`)

**Comment by ararslan** [comment]
I believe FreeBSD will need https://github.com/JuliaLang/julia/pull/41808 in order to pass tests.

**Comment by ararslan** [comment]
Seems Linux x86 is failing with the same error. I've changed the base branch of the aforementioned PR to be this PR, so merging that will include the changes here.

**Comment by DilumAluthge** [comment]
This is no longer necessary, as we are going to drop support for FreeBSD 11.

For the Sockets revert, see https://github.com/JuliaLang/julia/pull/41850

**Pull request closed without merging**
