### PR TITLE
improve return-type reflections of opaque closure

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by Keno** [comment]
It's not necessarily clear which of the two answers is more precise. We probably should typeintersect them (which is essentially what the implicit typeassert that we codegen does in the type domain).

**Comment by aviatesk** [comment]
How can we specify return type of OC though? E.g. following code doesn't work:
```julia
julia> oc = let foo::Int = 42
           oc = Base.Experimental.@opaque function (a,)::Float64
               sin(a) + cos(a)
           end
       end
ERROR: syntax: ambiguous signature in function definition. Try adding a comma if this is a 1-argument anonymous function.
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by Keno** [comment]
I don't know whether we exposed it in the macro, but the underlying feature has lower and upper bounds for allowable return types and the non-macro use cases do rely on that functionality.

**Comment by aviatesk** [comment]
I see.

**Review by Keno — APPROVED** [review]

**Pull request merged**
