### PR TITLE
set default blas num threads to Sys.CPU_THREADS / 2 in absence of OPENBLAS_NUM_THREADS

### LINKED ISSUE #915: eigen is 20% slower on 1.8-beta and nightly than 1.7 release
I'm not sure what has been changed, but it seems `eigen` has a performance regression, also didn't find other issue mentioning this

on 1.7.2

```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 7 samples with 1 evaluation.
 Range (min … max):  767.383 ms … 783.423 ms  ┊ GC (min … max): 0.00% … 0.04%
 Time  (median):     774.151 ms               ┊ GC (median):    0.04%
 Time  (mean ± σ):   774.743 ms ±   5.491 ms  ┊ GC (mean ± σ):  0.02% ± 0.02%

  █           █    █       █    █                █            █
  █▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  767 ms           Histogram: frequency by time          783 ms <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

on 1.8-beta1

```julia
julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 24 virtual cores

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.067 s …   1.109 s  ┊ GC (min … max): 0.04% … 0.04%
 Time  (median):     1.095 s              ┊ GC (median):    0.04%
 Time  (mean ± σ):   1.089 s ± 17.117 ms  ┊ GC (mean ± σ):  0.02% ± 0.02%

  █         █                           █   █             █
  █▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.07 s         Histogram: frequency by time        1.11 s <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

on master branch

```julia
julia> versioninfo()
Julia Version 1.9.0-DEV.118
Commit 15b5df4633 (2022-03-02 18:30 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 24 virtual cores

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.126 s …   1.164 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.134 s              ┊ GC (median):    0.04%
 Time  (mean ± σ):   1.139 s ± 15.033 ms  ┊ GC (mean ± σ):  0.03% ± 0.02%

  █     █     █          █                                █
  █▁▁▁▁▁█▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.13 s         Histogram: frequency by time        1.16 s <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

### LINKED ISSUE #44449: eigen is 20% slower on 1.8-beta and nightly than 1.7 release
I'm not sure what has been changed, but it seems `eigen` has a performance regression, also didn't find other issue mentioning this

on 1.7.2

```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 7 samples with 1 evaluation.
 Range (min … max):  767.383 ms … 783.423 ms  ┊ GC (min … max): 0.00% … 0.04%
 Time  (median):     774.151 ms               ┊ GC (median):    0.04%
 Time  (mean ± σ):   774.743 ms ±   5.491 ms  ┊ GC (mean ± σ):  0.02% ± 0.02%

  █           █    █       █    █                █            █
  █▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  767 ms           Histogram: frequency by time          783 ms <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

on 1.8-beta1

```julia
julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 24 virtual cores

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.067 s …   1.109 s  ┊ GC (min … max): 0.04% … 0.04%
 Time  (median):     1.095 s              ┊ GC (median):    0.04%
 Time  (mean ± σ):   1.089 s ± 17.117 ms  ┊ GC (mean ± σ):  0.02% ± 0.02%

  █         █                           █   █             █
  █▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.07 s         Histogram: frequency by time        1.11 s <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

on master branch

```julia
julia> versioninfo()
Julia Version 1.9.0-DEV.118
Commit 15b5df4633 (2022-03-02 18:30 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 24 virtual cores

julia> using LinearAlgebra, BenchmarkTools

julia> M = rand(1000, 1000);

julia> @benchmark eigen($M)
BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.126 s …   1.164 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.134 s              ┊ GC (median):    0.04%
 Time  (mean ± σ):   1.139 s ± 15.033 ms  ┊ GC (mean ± σ):  0.03% ± 0.02%

  █     █     █          █                                █
  █▁▁▁▁▁█▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.13 s         Histogram: frequency by time        1.16 s <

 Memory estimate: 31.58 MiB, allocs estimate: 21.
```

### PR DESCRIPTION
**Pull request by Moelf**
fix  JuliaLang/LinearAlgebra.jl#915

### CODE REVIEW

**Comment by Moelf** [comment]
>Maybe the right thing is to let you set any number explicitly as JULIA_NUM_THREADS, but if you don't specify then cap at 8 by default like we did before? 

is `OPENBLAS_NUM_THREADS` still the ENV variable we want to use moving forward?

**Comment by ViralBShah** [comment]
How about instead setting `(Sys.CPU_THREADS/2)`?

**Comment by ViralBShah** [comment]
This needs to not be tied to JULIA_NUM_THREADS, because even in single-threaded Julia, you may still want multi-threaded BLAS.

**Comment by Moelf** [comment]
yeah this is not tied to `JULIA_NUM_THREADS`. I'm just unsure what @JeffBezanson 's comment was saying, I *think he was saying do something "like" what we do with `JULIA_NUM_THREADS`, not actually using it for BLAS number of threads

**Comment by ViralBShah** [comment]
The problem with Julia threading defaults (`-t auto`) is that it also picks the hyperthreaded and not the physical cores.

**Comment by Moelf** [comment]
yes. Well, this PR only sets  `OPENBLAS_NUM_THREADS` to `8` when it's not set by the user.

I always wanted `-t auto` to set # of threads to # of physical cores but alas.

**Comment by ViralBShah** [comment]
Right, but that setting is almost always wrong - like on my laptop where I have only 2 physical and 4 hyperthreaded cores, it will pick 8. And on a big machine where we have more CPUs, it will pick too few. That's why my preference is just Julia's reported cores divided by 2.

Would be great to have @chriselrod and @staticfloat chime in.

**Comment by Moelf** [comment]
reusing:
https://github.com/JuliaLang/julia/blob/a5438f997e7c84529b829721c8b1dff5440872f5/stdlib/LinearAlgebra/src/blas.jl#L109

**Comment by ViralBShah** [comment]
I think we should we do this directly through the `BLAS.set_num_threads()` API and that `LinearAlgebra.__init__()` is the right place to do it.

**Comment by Moelf** [comment]
like this?

**Comment by chriselrod** [comment]
> 

I think that's fine.

But with Apple M1 and Intel Alder Lake, we're going to have more and more cases where this is suboptimal.

**Comment by ViralBShah** [comment]
There needs to be (or already exists) a separate issue for doing feature detection in Julia for all packages to use.

**Review by ViralBShah — APPROVED** [review]

**Review by chriselrod — APPROVED** [review]
> There needs to be (or already exists) a separate issue for doing feature detection in Julia for all packages to use.

Yeah, no reason not to do this until then.

**Comment by ViralBShah** [comment]
I'm merging this so that it gives us time to experiment and see how it is working out.

**Pull request merged**
