### PR TITLE
Constructor for SharedMatrix and SharedVector

### LINKED ISSUE #28131: Interfaces for SharedVector and SharedMatrix
I think it is better to have interfaces for ``SharedVector`` and ``SharedMatrix`` as below.
```
v1 = SharedVector{Float64}( 4 );
v2 = SharedVector( rand(4) ) ;
m1 = SharedMatrix[Float64}(4, 4);
m2 = SharedMatrix( rand(4, 4) ) ;
```
I wanted to add these interfaces.
So, I created code like below.
```
SharedVector(A::DenseVector) = SharedArray(A)
SharedMatrix(A::DenseMatrix) = SharedMatrix(A)

SharedVector{T}(m::Integer; kwargs...) where {T} = SharedArray{T}(m; kwargs...)
SharedMatrix{T}(m::Integer, n::Integer; kwargs...) where {T} = SharedArray{T}(m, n; kwargs...)
```
The first two lines work well.
However, the other two lines do not work, occurring an StackOverFlowError.

What is the problem?
Or is there a way to implement the below interfaces which take a dimension and type.

### PR DESCRIPTION
**Pull request by ryonghyun**
I implemented the constructor of ``SharedMatrix`` and ``SharedVector`` type.
These types are the alias of ``SharedArray`` type.
This will fix #28131.

### CODE REVIEW

**Comment by kshyatt** [comment]
Hi @usefulhyun, thanks for making the PR and welcome to Julia! We've had a busy few weeks trying to get the RC out and I'm sorry your work slipped through the cracks. Hopefully someone can review it soon.

**Review by andreasnoack — CHANGES_REQUESTED** [review]
Looks good to me but please add some tests. At some point, we might need to adjust the constructors to take a `undef` argument but that is a separate issue.

**Comment by usefulhyun** [comment]
Thank you for your review.
I wrote this 6 month ago. So, I do not remember correctly now.
I guess the Julia has changed a lot.
As a result, the following code rather creates error, which works well before.
```julia
SharedVector{T}(m::Integer; kwargs...) where {T} = SharedArray{T}((m,); kwargs...)
SharedMatrix{T}(m::Integer, n::Integer; kwargs...) where {T} = SharedArray{T}((m, n); kwargs...)
```
So I have removed the above code and added some tests.

**Comment by andreasnoack** [comment]
Tests are failing because of trailing white space.

**Comment by usefulhyun** [comment]
I have removed white space and added test cases.

**Review by andreasnoack — APPROVED** [review]

**Pull request merged**
