### PR TITLE
add check for invalid state in `_growend!` slow-path

### PR DESCRIPTION
**Pull request by oscardssmith**
This only triggers in cases where the user has done something pretty bad (e.g. modified the size incorrectly, or calling `push!` from multiple threads on the same vector without a lock). I'm very unsure if `ConcurrencyViolationError` is the right error to throw here, but I think most of the time, that is going to be the cause. This check is in the slow path because adding extra checks here is basically free (since it will run rarely, and will be batched with O(n) work to copy everything over). I also only included it for `growend!` and not the other grow functions because almost all users doing bad things in a multithreaded context are likely only `push!` ing rather than inserting at the front or arbitrary locations.

### CODE REVIEW

**Comment by KristofferC** [comment]
Is there something special at exactly this point? Presumably there are many places that use these fields so what is so exceptional that this should be added right here?

**Comment by oscardssmith** [comment]
There aren't that many places that use these fields (there were none prior to 1.11 since the fields didn't exist). This sort of check also is only beneficial before modifications to the fields, of which there are fewer use cases. It would be possible to add this to `_growbeg!`, `_growat!`, `_deletebeg!`, `_deleteend`, and `_deleteat!`, but this PR only added it to `_growend!` since that is by far the most commonly used (especially by places like the compiler that are especially likely to be incorrectly used in multi-threading (including by the compiler).

**Comment by KristofferC** [comment]
> There aren't that many places that use these fields (there were none prior to 1.11 since the fields didn't exist).

Yes, heh, I meant in the new array code.

Seems at least reasonable to have it in `growbeg` (`pushfirst!`) which is also used in the compiler if this is in fact useful.

**Comment by oscardssmith** [comment]
fair enough. Added.

**Comment by oscardssmith** [comment]
I think this is now ready to go.

**Pull request merged**
