### PR TITLE
Make `broadcastable` treat `Char` like `Number`

### PR DESCRIPTION
**Pull request by matthias314**
This is my very first PR, so I hope I'm doing things right. It's motivated by a thread on Discourse, see [here](https://discourse.julialang.org/t/char-and-broadcastable/61221). stevengj suggested that I file this issue on GitHub.

Starting point is the observation that `Char` seems to be the only plain-bits type for which `broadcastable` calls `collect` (the default method, meant for collecting iterables). stevengj mentioned on Discourse that `Char` once was a subtype of `Number`, so maybe it was just forgotten to align the treatment for `Char` with `Number` when `Char` ceased to be a subtype. This PR proposes to make this alignment.

 It turns out that it's not enough to define `broadcastable(x::Char) = x` (same method as for `Number`). One also needs `getindex(x, CartesianIndex())`, which is not defined for `Char` (maybe again an omission). If one adds this, then everything seems to work. The entire test suite runs without problems. I've also added a test for the `getindex` call mentioned above. Note that there is already a `@testset "broadcasting of Char"` in `test/char.jl`.

### CODE REVIEW

**Comment by stevengj** [comment]
In particular, note that `Char` is already indexable and acts like a 0-dimensional container:
```jl
julia> ndims('x')
0

julia> 'x'[] == 'x'
true
```
so I think we should have a `(::Char)[CartesianIndex()]` method anyway for consistency.  And once we have that, there should be no need to `collect` for broadcasting.

**Comment by stevengj** [comment]
Do we already have test coverage for broadcast operations with `Char`?  e.g. `'x' .* ['y', 'z']` or similar?

**Comment by matthias314** [comment]
> Do we already have test coverage for broadcast operations with `Char`?

I believe that currently the only test is `@test identity.('a') == 'a'` in `test/char.jl`. It fails if one only changes `broadcastable` without the new method for `getindex`.

**Comment by stevengj** [comment]
Would be good to add another test, just to be safe.

**Comment by matthias314** [comment]
> Would be good to add another test

done

**Review by simeonschaub — APPROVED** [review]
Great first PR!

**Comment by jtrakk** [comment]
For me it's unintuitive that Char is a container. I would think indexability is mostly a historical artifact from its early origins as an Int, and it would be better to clean up the interface by removing the containerness in 2.0 rather than leaning into it by adding more containery features. What do you think?

**Comment by JeffBezanson** [comment]
That comes up from time to time. It really is convenient to be able to treat a scalar like a 0-d array sometimes, so removing the methods strikes me as overly pedantic.

**Comment by jtrakk** [comment]
> It really is convenient to be able to treat a scalar like a 0-d array sometimes

Agreed, but having some things and not others be arraylike complicates the semantics (what is an atom vs a collection? is this like APL or not?). We can have an answer that's clear and flexible: treating scalars as atoms by default but `Ref(x)` allows treating them as arrays.

**Comment by matthias314** [comment]
The tester_linux32 check failed. Is there anything I am supposed to do? I don't see how the problem is related to my PR.

**Comment by simeonschaub** [comment]
Yes, that failure can safely be ignored here.
I think this is a nice consistency improvement regardless of whether or not we want to make numbers non-indexable some time in the far future. Will merge later today if there are no further objections.

**Comment by stevengj** [comment]
Shouldn't this have been `AbstractChar`, not `Char`?  The methods for `getindex` etcetera are for `AbstractChar`.

**Pull request merged**
