### PR TITLE
Remove stale contrib files

### PR DESCRIPTION
**Pull request by musm**
fixup-libstdc++ isn't being used anymore as well, is BB perhaps using this or is it also safe to remove?

### CODE REVIEW

**Comment by staticfloat** [comment]
Let's not remove it just yet; I may need it in 1.7.  If not, we can remove it then.

**Review by staticfloat — APPROVED** [review]

**Comment by musm** [comment]
Win 32 failure looks odd

**Comment by staticfloat** [comment]
It's a network failure, don't worry too much about it.

**Comment by garrison** [comment]
Why was `valgrind-julia.supp` deemed to be stale?  It is still referenced in [the Valgrind devdocs](https://docs.julialang.org/en/v1/devdocs/valgrind/).

**Comment by garrison** [comment]
I have opened a PR that brings back (an updated version of) `valgrind-julia.supp`.  Feel free to chime in there (#43319) if you would prefer that this file go away permanently.

**Pull request merged**
