### PR TITLE
bump NetworkOptions (fix #38429)

### LINKED ISSUE #38429: Downloads.jl downloading is broken on Windows, errors when trying to read cert file
https://build.julialang.org/#/builders/61/builds/5568/steps/5/logs/stdio

``` 
Error in testset spawn:
Error During Test at C:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\testdefs.jl:21
  Got exception outside of a @test
  LoadError: Error reading ca cert file C:\buildbot\worker\package_win32\build\usr\share\julia\cert.pem - mbedTLS: (-0x3E00) PK - Read/write of file failed while requesting https://cache.julialang.org/https://frippery.org/files/busybox/busybox.exe
  Stacktrace:
    [1] (::Downloads.var"#9#17"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Nothing, Bool, Bool, String, Int32, Bool, Bool})(easy::Downloads.Curl.Easy)
      @ Downloads C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:333
    [2] with_handle(f::Downloads.var"#9#17"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Nothing, Bool, Bool, String, Int32, Bool, Bool}, handle::Downloads.Curl.Easy)
      @ Downloads.Curl C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Curl\Curl.jl:51
    [3] #8
      @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:284 [inlined]
    [4] arg_write(f::Downloads.var"#8#16"{Base.DevNull, Nothing, Vector{Pair{String, String}}, Nothing, Bool, Bool, String, Int32, Bool, Bool}, arg::IOStream)
      @ ArgTools C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:112
    [5] #7
      @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:283 [inlined]
    [6] arg_read
      @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:61 [inlined]
    [7] request(url::String; input::Nothing, output::IOStream, method::Nothing, headers::Vector{Pair{String, String}}, progress::Nothing, verbose::Bool, throw::Bool, downloader::Nothing)
      @ Downloads C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:282
    [8] #3
      @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:199 [inlined]
    [9] open(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Nothing, Bool, Nothing, String}, args::String; kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:write,), Tuple{Bool}}})
      @ Base .\io.jl:330
   [10] arg_write(f::Function, arg::String)
      @ ArgTools C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:86
   [11] #download#2
      @ C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:198 [inlined]
   [12] download(url::String, output::String)
      @ Downloads C:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:198
   [13] top-level scope
      @ C:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\spawn.jl:24
...
```

maybe https://github.com/JuliaLang/julia/pull/38413?

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I'm pretty sure this PR didn't break the analyze-gc CI step.

**Comment by vchuravy** [comment]
> I'm pretty sure this PR didn't break the analyze-gc CI step.

No you didn't. Just fixed the buildbot script.

**Comment by vchuravy** [comment]
I kicked the Win32 build it got stock (old log here https://build.julialang.org/#/builders/61/builds/5582)

**Comment by StefanKarpinski** [comment]
Looking promising that this fixes that issue. There's still the mystery of why it didn't trigger a CI failure in the original PR: the NetworkOptions test suite did verify that `BUNDLED_CA_ROOTS` is a path, which should not have been the case since it was using the build-time path, not the run-time path. Best working theory so far is @fredrikekre's suggestion that the NetworkOptions tests ran early enough on the same machine that the package step ran on that the build-time CA root bundle hadn't yet been deleted. Perhaps @staticfloat knows if that's a possibility.

**Comment by staticfloat** [comment]
No, none of the tests get run on the same build machine as the test machine explicitly so we do catch issues like this.

**Comment by StefanKarpinski** [comment]
> No, none of the tests get run on the same build machine as the test machine explicitly so we do catch issues like this.

But we didn't: [this PR](https://github.com/JuliaLang/julia/pull/38413) passed CI with the new NetworkOptions. We ran the NetworkOptions tests and they passed, including checking that the build-time constant `BUNDLED_CA_ROOTS` existed as a path. How did that happen?

**Comment by staticfloat** [comment]
I can download https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.6/julia-19b59a124c-linux64.tar.gz, run that `julia` and run `Base.runtests("NetworkOptions")` and it passes:

```
$ ./bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1480 (2020-11-12)
 _/ |\__'_|_|_|\__'_|  |  refs/pull/38413/merge/19b59a124c (fork: 1 commits, 1 day)
|__/                   |

julia> Base.runtests("NetworkOptions")
Test       (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
NetworkOptions  (1) |        started at 2020-11-13T20:13:06.669
NetworkOptions  (1) |     1.13 |   0.02 |  1.9 |     127.42 |   285.30

Test Summary: | Pass  Total
  Overall     | 3401   3401
    SUCCESS

julia> using NetworkOptions

julia> NetworkOptions.BUNDLED_CA_ROOTS
"/buildworker/worker/package_linux64/build/usr/share/julia/cert.pem"

julia> isfile(NetworkOptions.BUNDLED_CA_ROOTS)
false
```

So something is wrong in the tests, I would guess.

**Comment by StefanKarpinski** [comment]
It's expected to work on Linux (I added a new test that will fail along with my fix), but it should fail on Windows or macOS due to these lines:

https://github.com/JuliaLang/NetworkOptions.jl/blob/9b248a8c2f1f5bb80467ab222b21469079cc9ad3/test/runtests.jl#L7-L15

```jl
@test ca_roots_path() isa String
@test ispath(ca_roots_path())
if Sys.iswindows() || Sys.isapple()
    @test ca_roots_path() == BUNDLED_CA_ROOTS
    @test ca_roots() === nothing
else
    @test ca_roots_path() != BUNDLED_CA_ROOTS
    @test ca_roots() == ca_roots_path()
end
```
On Windows and macOS we check these two facts:

* `@test ispath(ca_roots_path())`
* `@test ca_roots_path() == BUNDLED_CA_ROOTS`

Obviously that implies `ispath(BUNDLED_CA_ROOTS)` which seems like it shouldn't be true. That equality isn't true on Linux or FreeBSD, so I added an explicit test for `isfile(bundled_ca_roots())`, but I'm still concerned about why this wasn't caught. What's the download link for the macOS version of that nightly?

**Comment by staticfloat** [comment]
The macOS buildbot had permissions troubles removing the previous version of Julia, so I wonder if it ended up running an older version.  That's a chilling possibility.  Downloading the linked version https://s3.amazonaws.com/julialangnightlies/assert_pretesting/mac/x64/1.6/julia-19b59a124c-mac64.dmg does indeed fail the test on my machine.

The windows ones still pass though.  You can download [the `.exe`](https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x64/1.6/julia-19b59a124c-win64.exe) or [the `.tar.gz`](https://s3.amazonaws.com/julialangnightlies/assert_pretesting/winnt/x64/1.6/julia-19b59a124c-win64.tar.gz) and check for yourself, if you like.

**Pull request merged**
