### PR TITLE
move ntoh hton & co. to Sockets stdlib

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
Is it obvious that these should live in `Sockets`? I only ever use these functions for dealing with files on disk and it will look kinda weird with `using Sockets` for code that doesn't use any actual sockets functionality.

**Comment by KristofferC** [comment]
Python: https://docs.python.org/3/library/socket.html (`sockets` module)
Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms740069(v=vs.85).aspx (`Winsock2.h` header file)

**Comment by GlenHertz** [comment]
I guess from an OS/comp-sci point of view they belong with sockets but from a technical computing point of view I've only used them when reading binary files in a cross-platform way.  I would rather have Julia group them for the purpose of technical computing.

**Comment by KristofferC** [comment]
> I would rather have Julia group them for the purpose of technical computing.

What does that mean? How would you do that in practice?

**Comment by Keno** [comment]
For file formats, I'd recommend a proper binary I/O package with builtin endianness support.

**Comment by GlenHertz** [comment]
Yeah, nevermind. "n" means network so they should go in sockets. Maybe similar functions would go in a binary file io package for doing common bit twiddling operations.

**Comment by stevengj** [comment]
I think that byte-swapping routines should just remain in Base until/unless there is a clearly better place to put them.    I agree with @GunnarFarneback that their utility extends far beyond sockets so it doesn't make sense to me put them there.

Nor are the other arguments for moving things out of base very applicable here.  Name conflicts with `hton` seem unlikely, and also API changes or upgrades don't seem like much of a concern.

The fact that Python and Windows put them there is probably a historical artifact, like the name "network order" for "bigendian".   Linux and MacOS put them in into `<arpa/inet.h>` header file, but we wouldn't put them into an [ARPANET](https://en.wikipedia.org/wiki/ARPANET) package either.

**Pull request closed without merging**
