### PR TITLE
WIP: Chocolatey package for windows

### PR DESCRIPTION
**Pull request by davidanthoff**
This is a first cut at support for a [chocolatey](http://chocolatey.org/) package for julia. Not ready to be merged, there are still some open questions.
# Background

[Chocolatey](http://chocolatey.org/) is a package manager for Windows that seems to be the most popular one right now. Currently one downloads the client software from their site and then can use the command line to easily install and update software from the chocolatey gallery (i.e. `cinst julia` once this PR is done). Microsoft recently released a [preview of Powershell 5](http://blogs.technet.com/b/windowsserver/archive/2014/04/03/windows-management-framework-v5-preview.aspx) that includes client bits for chocolatey. They are on the record that this will be part of the next Windows release, so at that point one should be able to just open a command prompt on Windows and install something like julia with one command (`Install-Package julia`).
# Use
## To build a chocolatey package
- Go to contrib/windows/chocolatey
- call `make`

You have a package, that is pretty much all. You can create packages for older commits/versions by passing in make variables.
## To install chocolatey package

Assuming chocoatey is installed:
- Go to the directory with the nupkg file
- Call `cinst julia -source <currentDir>`. To install a prerelease version add `-pre`
- To update the installed julia version do `cup julia`, again use `-pre` to also use prerelease versions
# Open questions
- If the julia devs like this, it should really become part of the regular build process and nightly prerelease versions should each have a package like this, they should be auto-uploaded to chocolatey.org etc. I think especially for people on nightly builds this could be handy, `cup julia -pre` should for example be enough to update to the latest nightly build with this.
- This PR essentially works as follows: the chocolatey package has an install script, that script downloads the binary installer and then calls it in silent mode. An alternative would be that this install script downloads the binaries packaged as a zip file and unpacks them to a location, and then does anything else required as well. I would prefer the later (i.e. not to call the installer, but have everything in the chocolatey install script), but it would require that the julia nightly build creates zip files of the binaries in addition to the installer exe and uploades them to amazon etc. If the core devs like this whole approach, we might want to change over.
- I think currently if one updates the chocolatey package with `cup julia` it does NOT first uninstall the previous version and then install the new one. I'm not really happy with that, but if we would opt for the option to use packaged zip files instead of the installer exe, I know how to make updates "clean"
- the nuspec file has some fields that need text/names, I was not sure what to use, would be great if the core devs could provide that
- The package needs a link to the julia license. I link to github right now, but it would be nice to have a more permanent link (that could just redirect) like http://julialang.org/license
- chocolatey needs a build #. I create one now by using the seconds since 1970, which kind of works, but it would probably be better to actually assign proper build # in some nightly script, keep track of them etc The build number needs to be present as the fourth part of the version.
- The script is hard-coded to 0.3 releases. Things would be easier if the URL for binaries had less parts that need to be adjusted with version number info, or if I would know how to do even basic string manipulation within a makefile...

There are probably other things, but for now it would be good to get some feedback.

### CODE REVIEW

**Comment by tkelman** [comment]
Closing given https://chocolatey.org/packages/Julia and https://github.com/FlorianRappl/Chocolatey-Julia exist now. Doesn't look like this needs to exist within this repo.

**Comment by davidanthoff** [comment]
@tkelman , agreed that this can be closed. The core problem with chocolatey is that it doesn't have any notions of upgrades. The package you link to also doesn't solve this problem, it is just hard-coded to install julia 0.4.2.

For my own use I now have a PowerShell module that exports a command called ``update-julia``. It essentially maintains two julia "channels": the latest stable and the latest nightly channel. ``update-julia`` updates both to the latest available binary, and then adds aliases called ``julia`` and ``juliadev`` to any powershell session to start those. The whole thing is pretty handy and at some point I might make that available if others are also interested in it. Certainly doesn't have to live int he main julia repo.

**Comment by tkelman** [comment]
Sounds pretty neat, especially if it could be combined in the same repo as a similar interface sh implementation of the same thing for other platforms.

**Comment by ferventcoder** [comment]
>  The core problem with chocolatey is that it doesn't have any notions of upgrades.

I'm confused by this statement. Are you stating that the package itself doesn't have a notion of upgrades? Chocolatey itself has a great notion of upgrades, but like other package managers it requires new versions of packages.

**Comment by davidanthoff** [comment]
@ferventcoder That might have changed in the meantime. When I last looked (admittedly quite a while ago), upgrading packages essentially led to them being installed side by side, and I was also not able to find any script that might be triggered in a package during an update. All of that might have changed in the meantime, so I should have been more careful with my statement.

**Comment by ferventcoder** [comment]
Yes, it must have been awhile ago - March 2015 (last year) we released 0.9.9, which was a complete rewrite, much faster, more stable, and yes, much better at being a package manager. 

chocolateyInstall.ps1 always triggered during both install and upgrade and for 0.910 we've added a before modify script that runs prior to upgrade and uninstall in addition to the other scripts. Since we've always run a powershell script during upgrades, I'm not sure exactly what you meant by it doesn't upgrade well. 

Since the install scripts are usually for when you need to download resources b/c of no redist rights (for public packages) and for wrapping installers/zips, if you put the software directly in the package (this is how choco works best), it handles upgrades and uninstalls quite intelligently.

It already handles zips well for upgrades.

For installers, it relies on the package maintainer's scripts and the native installers themselves to handle upgrades, which most native installers do quite well. And that has been there for quite awhile (years), so you may excuse my confusion by your statements.

The only thing 0.9.8x and below didn't handle well was the packages themselves in upgrade scenarios. But that has been resolved by 0.9.9+.

HTH

**Pull request closed without merging**
