### PR TITLE
deprecate `const` on local variables, which used to be ignored

### PR DESCRIPTION
**Pull request by JeffBezanson**
part of #5148

### CODE REVIEW

**Review by Sacha0 — COMMENTED** [review]
The Travis macOS failure suggests that something in
```julia
let
     local MatOrNot, my_func, M
     MatOrNot{T} = Union{AbstractMatrix{T}, Vector{Union{}}}
     my_func(A::MatOrNot{T}, B::MatOrNot{T}, C::MatOrNot{T}) where {T<:Real} = 0
     M = [ 2. 1. ; 1. 1. ]
     @test my_func(Union{}[], M, M) == 0
 end
```
from test/core.jl (around line 849) triggers the depwarn. Perhaps the `MatOrNot{T} = Union{...}`?

**Comment by tkelman** [comment]
add a todo note in deprecated.jl so this gets removed at the right time?

**Comment by StefanKarpinski** [comment]
Technically, since the behavior of that would change if local const was enforced (in that you would cease to be able to reassign the name), so I guess the only real choice in this PR is to change it.

**Comment by JeffBezanson** [comment]
I think we're fine here. Both `f() = ...` and `t{} = ...` now create `const` bindings only in global scope. Function definitions have always worked this way:

```
julia> f() = 0
f (generic function with 1 method)

julia> f = 1
ERROR: invalid redefinition of constant f

julia> function g()
         h() = 0
         h = 1
       end
g (generic function with 1 method)

julia> g()
1
```

**Pull request merged**
