### PR TITLE
Backport of #11773

### PR DESCRIPTION
**Pull request by yuyichao**
This should be pure bug fixing and non-breaking.

This is the first time I do a backport PR so hopefully I've got it right ....................

### CODE REVIEW

**Comment by yuyichao** [comment]
Actually seems that `backport pending` is not the right label for this?

**Comment by yuyichao** [comment]
Anyone has any idea what's the error in `travis-ci/pr`? Doesn't seems to be related and I don't know anything about 0.3....

**Comment by tkelman** [comment]
`MatrixIllConditionedException("")` probably a numerical tolerances issue in umfpack that is hopefully fixed on master but hasn't been backported yet

**Comment by tkelman** [comment]
Backport pending label is good for PR's against release-0.3, helps prevent losing track of things. Best to wait a couple days with the fix on master to be positive, but I think this should be okay. @JeffBezanson can you confirm this should be safe to backport (merge) in a couple days if we don't see any issues?

**Comment by yuyichao** [comment]
Having a `NULL` here is almost a guaranteed SegFault althought it shouldn't hurt to be more careful.

**Pull request merged**
