### PR TITLE
Fixing comma

### PR DESCRIPTION
**Pull request by sam0410**
This is for issue #29958 
Locally, after this change, comma is printed the way it should be (note the comma after `persists`).

solved

Also, I am not sure if the build here is failing because of my changes, if yes, could someone tell me what is wrong?

### CODE REVIEW

**Comment by staticfloat** [comment]
Yes, I believe your changes are causing the build failures.  The build failure is:

```
/bin/sh: 1: Syntax error: Unterminated quoted string
make[2]: *** [/home/travis/build/JuliaLang/julia/usr/lib/julia/sys-o.a] Error 2
```

**Comment by staticfloat** [comment]
Notice how in the second instance of `$(COMMA)`, all the other variables use double dollar signs.  This is because it's inside of a `define` which requires the second level of quoting.  So you need to keep the double dollar signs for the second instance.

**Comment by sam0410** [comment]
I get it now @staticfloat. Thankyou for your review. I added the change.

**Comment by stevengj** [comment]
Why are we using a `COMMA` variable here anyway?

**Comment by staticfloat** [comment]
https://github.com/JuliaLang/julia/commit/8e9e68c21d8d8d2aae24b0d8eb7ed31984445ce7#commitcomment-9328783

**Comment by sam0410** [comment]
Hi @staticfloat , the build is failing because of something related to 32 bit issue, not anything related to my code. So, is this PR ready to be merged ?

**Pull request merged**
