### PR TITLE
Check the box in the platform table that says we have FreeBSD CI

### PR DESCRIPTION
**Pull request by ararslan**
Thanks to the valiant efforts of @iblis17.

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]
:tada:

**Comment by ararslan** [comment]
Should probably check with whoever cares about the PowerPC binaries. Is the buildbot fixable?

**Comment by ararslan** [comment]
Okay, PowerPC has been demoted.

**Comment by tkelman** [comment]
> Is the buildbot fixable?

I've never been able to successfully ssh in to that buildbot.

**Pull request merged**
