### PR TITLE
optimizer: lower inline cost threshold

### PR DESCRIPTION
**Pull request by vtjnash**
It was probably too high.

I have a pet theory that since the new optimizer does a better job, there's no longer as much easy work for LLVM to do, resulting in more actual work being done (e.g. more than intended before).

### CODE REVIEW

**Comment by Keno** [comment]
We'll also want to adjust it dynamically at union split sites as we discussed at some point.

**Comment by vtjnash** [comment]
That's already implemented – this just sets the upper bound (union-sites should be something strictly less than this, maybe `min(30, this_const / n_split * 3 / 2)`)

**Comment by KristofferC** [comment]
Would really be nice to have Nanosoldier working for this.

**Comment by JeffBezanson** [comment]
I thought we were inlining a bit too much?

**Comment by Keno** [comment]
> I thought we were inlining a bit too much?

Yes, this makes it inline less.

**Comment by JeffBezanson** [comment]
Oh, right. Good :)

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/27337#issuecomment-393667820):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/39dabf128d2c130d3d68895934ea12807c7b2268/c6467fc_vs_22590d5/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Tried something else. @nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
> ERROR: LoadError: ArgumentError: Module JSON not found in current path.

Something Pkg3 related? (assuming you didn't already fix this)

**Comment by ararslan** [comment]
Yeah I just added that, should hopefully work now.

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/27337#issuecomment-393703179):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -e su nanosoldier -- -c ./benchscript.sh`, ProcessExited(1)) [1]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/fffaa349f19ddea88c79a34ce5090ee59fd5c574/ef3dd14_vs_8b3849e/report.md)
cc @ararslan

**Comment by ararslan** [comment]
Well that's an interesting error.

**Comment by vtjnash** [comment]
> ERROR: LoadError: std has been moved to the package StatsBase.jl.
Run `Pkg.add("StatsBase")` to install it, restart Julia,
and then run `using StatsBase` to load it.

But also, there's a bug in the new optimizer (being detected by the verifier) @Keno.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27337#issuecomment-396488898) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/44c695d229b1a1920bfa126e175a113a90a62c65/62b93bb_vs_83ce7ba/report.md). cc @ararslan

**Comment by vtjnash** [comment]
Broadcast and skipmissing might need some extra inlining help, but those results looked quite good

**Comment by KristofferC** [comment]
Why close?

**Comment by vtjnash** [comment]
I don't think I'll have time to analyze the nanosoldier results.

**Comment by ViralBShah** [comment]
Why not leave it open in case someone else can take a look?

**Pull request closed without merging**
