### PR TITLE
inlining lambdas

### PR DESCRIPTION
**Pull request by vtjnash**
this enables inference to inline lambdas and thunks, just like it was already able to do for generic functions

(hint: diff is more clear if you add `?w=1` to the link)

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I think this is kind of a waste of time given #13412.

**Comment by vtjnash** [comment]
i thought the closure redesign was still keeping the distinction between anonymous functions and generic functions? This does not address closures at all (which I assume will be addressed by #13412), but covers the minor modifications necessary to handle anonymous functions as well as generic functions.

**Comment by carnaval** [comment]
I think anonymous function will simply be lowered to gensymed generic functions

**Comment by vtjnash** [comment]
A closure is lowered to a new gensymed type, with the code being added to the `call` generic function. However, the LambdaStaticData (aka anonymous function) is still separate from the MethodSorter (aka generic function).

**Comment by JeffBezanson** [comment]
Well, while LambdaStaticData and MethodTable are still separate types, the former is not used to represent anonymous functions. They no longer occur in ASTs except inside method definitions at the top level. And while call overloading is used now, this is temporary since it cannot really work with the new design.

**Pull request merged**
