### PR TITLE
More tests for Bidiagonal

### PR DESCRIPTION
**Pull request by kshyatt**
Checked with `@which` that these should call the appropriate `mul!` functions.

Had to invent my sketchy type to check this path of `transpose`.

### CODE REVIEW

**Review by dkarrasch — COMMENTED** [review]
The first part looks great. For the second part, I guess you want to have an eltype that is not a number. Not that I mind your type, but why not use 2x2 matrices? You could construct the "ground truth" for the transpose then as
```julia
Bidiagonal(transpose.(a), transpose.(b), :L)
```
if I'm not mistaken.

**Comment by kshyatt** [comment]
Tried that, didn't work bc the `zero` method failed.

**Comment by dkarrasch** [comment]
I see. No, it's not a bug, it's because the usual `Array`s don't have a size, so it would be unclear what the "zero element" of that should be. So I guess this is good then.

**Comment by kshyatt** [comment]
Yay. Can you press the approve button and I'll merge after CI passes?

**Review by dkarrasch — APPROVED** [review]

**Pull request merged**
