### PR TITLE
add rref from RowEchelon.jl

### PR DESCRIPTION
**Pull request by pranshumalik14**
Adding `rref` into LinearAlgebra. Currently under draft to get build and coverage updates.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Out of curiosity, why does this need to go into the LinearAlgebra stdlib? If it is currently working fine in a package, wouldn't it be better to just keep it in a package?

**Comment by pranshumalik14** [comment]
The package RowEchelon.jl is waiting to be integrated into the family of standard linalg operations. It is a handy function, often used to check hand calculations. Issue #9804 has a long discussion about it. There is also an option to put this into GenericLinearAlgebra.jl ([#17](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/17)). I am open to receive any feedback on where this would fit better because I also see that `rank` is being deprecated and to be moved somewhere else. If a plan for this is finalized somewhere, I would be happy to go over it and work on this accordingly.

**Comment by DilumAluthge** [comment]
I would rather add this to GenericLinearAlgebra.jl than to a stdlib. It's much easier to develop, improve, and release code in packages than stdlibs, because stdlibs are constrained by the development and release cycle of the Julia language.

**Comment by pranshumalik14** [comment]
Mhmm, that makes sense! My only fear at the moment is that GenericLinearAlgebra.jl has type piracy breaking things in many packages; my understanding of [this topic](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/71) is limited, but yeah I agree with you. It is more practical to have it there. Hopefully, this piracy issue gets resolved soon so that GLA is more amenable to be used in packages in the future.

**Pull request closed without merging**
