### PR TITLE
Filter out non-directories from stdlibs in runtests/choosetests

### LINKED ISSUE #27467: Base.runtests() fails due to lack of tests for .DS_Store
I haven't made any changes to installed Julia files, and yet:

```
julia> Base.runtests()
ERROR: LoadError: did not find test files for the following tests: .DS_Store
Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] top-level scope at /Users/jgoldfar/Public/julia/usr/share/julia/test/runtests.jl:37
 [3] include at ./boot.jl:314 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1071
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:267
 [7] _start() at ./client.jl:427
in expression starting at /Users/jgoldfar/Public/julia/usr/share/julia/test/runtests.jl:37
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.7.0-alpha.0
Commit 22590d529d (2018-05-31 00:07 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

Apparently, something in `choosetests.jl` is picking up the .DS_Store file. I'm looking into fixing this (admittedly minor) issue...

### PR DESCRIPTION
**Pull request by jgoldfar**
Thanks to @KristofferC for pointing me directly to the troublesome line!

Should close #27467

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by jgoldfar** [comment]
Is there a reason this choosetests logic for finding stdlibs is separate (apparently) from the way it is done by the code loading mechanism?

**Comment by StefanKarpinski** [comment]
They didn't used to live in the same repo, now that they do, consolidation might be called for.

**Comment by fredrikekre** [comment]
Something seem weird here:
```
ERROR: LoadError: did not find test files for the following tests: LibGit2/online, OldPkg/pkg, Pkg/pkg
Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] top-level scope at /tmp/julia/share/julia/test/runtests.jl:37
 [3] include at ./boot.jl:314 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1071
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:267
 [7] _start() at ./client.jl:427
in expression starting at /tmp/julia/share/julia/test/runtests.jl:37
```
Happens on all workers.

**Comment by jgoldfar** [comment]
Thanks for the fix!

**Pull request merged**
