### PR TITLE
Update and load styledstrings

### PR DESCRIPTION
**Pull request by tecosaur**
This has some value by itself, but mainly serves as a prerequisite for #51811, #51816, and #51829, along with two other PRs that have yet to be made.

### CODE REVIEW

**Comment by LilithHafner** [comment]
CI fails because of https://github.com/JuliaLang/StyledStrings.jl/issues/8

**Comment by LilithHafner** [comment]
Triage is happy with letting REPL depend StyledStrings.jl

**Comment by tecosaur** [comment]
Ok, the problem seems to be this:
```
Pkg                                               (3) |         failed at 2023-11-08T23:46:57.570
Error During Test at /cache/build/tester-amdci4-9/julialang/julia-master/julia-db6dc6445f/share/julia/stdlib/v1.11/Pkg/test/new.jl:3007
  Got exception outside of a @test
  Unsatisfiable requirements detected for package StyledStrings [f489334b]:
   StyledStrings [f489334b] log:
   ├─StyledStrings [f489334b] has no known versions!
   └─found to have no compatible versions left with REPL [3fa0cd96]
     └─REPL [3fa0cd96] log:
       ├─possible versions are: 1.11.0 or uninstalled
```

I only find this confusing though, if someone could weigh in that would be much appreciated :pray:.

**Comment by vtjnash** [comment]
I think Pkg has some special internal list of stdlibs, as otherwise it needs to go find them in General, and I don't think it seems to be registered there

**Comment by KristofferC** [comment]
> I think Pkg has some special internal list of stdlibs, as otherwise it needs to go find them in General, and I don't think it seems to be registered there

Hm, Pkg looks these up at runtime by looking in the stdlib folder so it should find them. I'll try figure out what is going on..

**Comment by tecosaur** [comment]
Thanks Kristoffer :)

**Comment by KristofferC** [comment]
Okay, the tests that error is within the "historical stdlib" stuff that I do not really know much about. Maybe @staticfloat knows what needs to be done here. It is possible it needs to be added to https://github.com/JuliaPackaging/HistoricalStdlibVersions.jl/blob/3eccb253cd154d56c0efd75d2315b459725addf9/src/version_map.jl#L1515 (which might be what Jameson meant) .

**Comment by staticfloat** [comment]
I pushed a new commit to that repo; it's supposed to have a bot that auto-opens new PRs I think, but it doesn't seem to be working.

**Comment by tecosaur** [comment]
I've tried updating the branch in the hope that the "historical stdlib" issue has been fixed in the background. I guess I'll find out if this is the case or not from CI.

**Comment by tecosaur** [comment]
Still seems like the same issue is occurring

```
Pkg                                               (2) |         failed at 2023-12-28T04:20:31.766
Error During Test at /cache/build/tester-amdci4-8/julialang/julia-master/julia-8d848dde20/share/julia/stdlib/v1.11/Pkg/test/new.jl:3027
  Got exception outside of a @test
  Unsatisfiable requirements detected for package StyledStrings [f489334b]:
   StyledStrings [f489334b] log:
   ├─StyledStrings [f489334b] has no known versions!
   └─found to have no compatible versions left with REPL [3fa0cd96]
     └─REPL [3fa0cd96] log:
       ├─possible versions are: 1.11.0 or uninstalled
```

**Comment by tecosaur** [comment]
I can't see how I can solve this myself, so if @KristofferC or @staticfloat could spare this some more attention, that would be much appreciated.

**Comment by KristofferC** [comment]
https://github.com/JuliaPackaging/HistoricalStdlibVersions.jl/pull/17 pushed a new commit but a new version for this was never registered. I will try bump the version and register it and we can rerun CI here and see what happens.

**Comment by tecosaur** [comment]
Thanks, Kristoffer. I just took a look at the CI for the commit you pushed and I see the same error (`StyledStrings [f489334b] has no known versions!`) in the `buildkite/julia-master` task. Am I correct in guessing that you pushed that commit after the new version was registered?

**Comment by tecosaur** [comment]
If I could give this a gentle bump once more, with the PRs blocked by this in particular it would be very good if this could be worked out.

**Comment by vchuravy** [comment]
So the version with StyledStrings was registered https://github.com/JuliaRegistries/General/pull/97838

Is Pkg using the right version of HistoricalStdlibVersions?

**Comment by KristofferC** [comment]
It should install it here https://github.com/JuliaLang/Pkg.jl/blob/b13bd2ddf6049865ddd8f7984bc9aa2790c14d21/test/runtests.jl#L42-L47.

But I don't see anything about it getting installed in the log.

**Comment by KristofferC** [comment]
I confirm this is an issue even with the latest HistoricalStdlibVersions.

However, I think this is a bug with the implementation in Pkg of the whole `julia_version` thing. In order to properly implement this feature we need to know the dependencies of the stdlibs for every Julia version, not only what packages are stdlibs. What happens now is that we call `Pkg.add(...; julia_version=v"1.5")` which will read in the stdlibs from v1.5 but the dependencies of (in this case) REPL is still read from its project file which includes StyledStrings which was not an stdlib in v1.5.

I would suggest disabling this Pkg test for now since it is unfortunate to block this on a Pkg bug.

**Comment by tecosaur** [comment]
Now that #53138 is merged, this should be mergeable without any CI issues :slightly_smiling_face:

**Comment by tecosaur** [comment]
CI hasn't quite finished yet, but so far I'm seeing:
- A `Downloads` error
- More `Downloads` errors
- A `strings/basic` error that will need to be fixed in `StyledStrings`

#### The `strings/basic` error

```
julia> Base.return_types(write, (IO, AbstractString))
5-element Vector{Any}:
 Int64
 Int64
 Int64
 Int64
 Int64

julia> using StyledStrings

julia> Base.return_types(write, (IO, AbstractString))
6-element Vector{Any}:
 Int64
 Int64
 Int64
 Any
 Int64
 Int64
```

I'll have a look at the `write` methods it defines and push a fix shortly.

**Comment by tecosaur** [comment]
Ok, at this point it seems like all the CI has run other than the Adress Sanitised/gnuassert builds.

I'm not seeing any non-spurious errors other than a `Error: Error setting up bootstrap` issue with the Mingw32 builds, which I'm pretty sure has nothing to do with this PR.

**Comment by tecosaur** [comment]
Alrighty, all the tests have finished now, and it looks all clear to me!

**Comment by tecosaur** [comment]
I'm so glad to see this merged, thanks to those who helped work out what was going on here and fix it!

**Pull request merged**
