### PR TITLE
optimize and fix map/broadcast over Adjoint/Transpose vectors

### LINKED ISSUE #492: eliminate temporary in map/broadcast over Adjoint/Tranpose-wrapped vectors
Leaving this breadcrumb to https://github.com/JuliaLang/julia/pull/25083#discussion_r157332474 so that I do not forget to incorporate `@timholy`'s great optimization suggestion. Best!

### LINKED ISSUE #25134: eliminate temporary in map/broadcast over Adjoint/Tranpose-wrapped vectors
Leaving this breadcrumb to https://github.com/JuliaLang/julia/pull/25083#discussion_r157332474 so that I do not forget to incorporate `@timholy`'s great optimization suggestion. Best!

### PR DESCRIPTION
**Pull request by Sacha0**
This pull request implements the optimization @timholy suggested in https://github.com/JuliaLang/julia/pull/25083#discussion_r157302172 (hence closes JuliaLang/LinearAlgebra.jl#492) and fixes the inference issue @martinholters caught in https://github.com/JuliaLang/julia/pull/25083#issuecomment-353031641. Thanks and best!

### CODE REVIEW

**Comment by timholy** [comment]
I didn't consciously intend to hit merge here (just a reflex after checking that the CI errors were unrelated...), sorry about that. But hopefully there are no bad consequences.

**Comment by iblis17** [comment]
master build failed after this merged: https://freebsdci.julialang.org/#/builders/1/builds/5712
I don't think CI error is unrelated.

**Comment by timholy** [comment]
I just pushed a revert, 5fcd0d9e69252dc0c4005061ba161b95d21424bd. Sorry about that.

**Comment by Sacha0** [comment]
Thanks nonetheless @timholy! :)

**Pull request merged**
