### PR TITLE
Define isfinite(::Irrational) = true

### PR DESCRIPTION
**Pull request by waldyrious**
As suggested in https://github.com/JuliaLang/julia/issues/7994#issuecomment-52536837
and https://groups.google.com/d/msg/julia-dev/BV0ssqKTmgc/8Itm_yLhVwsJ

### CODE REVIEW

**Comment by jiahao** [comment]
This is not true in general. You can construct "infinite rationals" like

```jl
julia> 1//0
1//0
```

**Comment by simonbyrne** [comment]
Could you add a test as well (I realise it's trivial, but good practice nonetheless).

**Comment by waldyrious** [comment]
Sure. I only didn't do it cause I wasn't exactly sure where to put it. Somewhere around [here](https://github.com/JuliaLang/julia/blob/375cdc33a5f5d06b977d7870bf171328417a2e77/test/numbers.jl#L496-L505), I suppose?

**Comment by simonbyrne** [comment]
That seems like an appropriate place.

**Comment by waldyrious** [comment]
@simonbyrne done :)

**Pull request merged**
