### PR TITLE
Fix #18577, remove generated function `broadcast_tup`

### LINKED ISSUE #18577: broadcast test failure
New `broadcast` test failure on master, specifically on
```julia
julia> versioninfo()
Julia Version 0.6.0-dev.693
Commit 2193638* (2016-09-18 19:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.5.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```
Also evident in logs from #18566, #18571, #18575, and #18576. Perhaps caused by an interaction between #16986 and some change merged after #16986's last CI run? The failure (locally):
```julia
julia> Base.runtests("broadcast")
     * broadcast            Error During Test
  Test threw an exception of type ErrorException
  Expression: broadcast(+,1.0,(0,-2.0)) == (1.0,-1.0)
  type #+ has no field contents
   in #35 at ./broadcast.jl:260 [inlined]
   in _ntuple at ./tuple.jl:101 [inlined]
   in ntuple(::Base.Broadcast.##35#36, ::Type{Val{2}}) at ./tuple.jl:94
   in macro expansion at ./broadcast.jl:260 [inlined]
   in broadcast_tup(::Base.#+, ::Tuple{Float64,Tuple{Int64,Float64}}, ::Type{Val{2}}, ::Int64) at ./broadcast.jl:259
   in broadcast_c(::Function, ::Type{Tuple}, ::Float64, ::Vararg{Any,N}) at ./broadcast.jl:269
   in broadcast(::Function, ::Float64, ::Tuple{Int64,Float64}) at ./broadcast.jl:340
   in include_from_node1(::String) at ./loading.jl:541
   in include_from_node1(::String) at /Users/sacha/pkg/julia/usr/lib/julia/sys.dylib:?
   in macro expansion at ./util.jl:232 [inlined]
   in runtests(::String) at /Users/sacha/pkg/julia/usr/share/julia/test/testdefs.jl:7
   in (::Base.##594#595{#runtests,Tuple{String},Array{Any,1}})() at ./multi.jl:1034
   in run_work_thunk(::Base.##594#595{#runtests,Tuple{String},Array{Any,1}}, ::Bool) at ./multi.jl:1005
   in #remotecall_fetch#599(::Array{Any,1}, ::Function, ::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1059
   in remotecall_fetch(::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1059
   in #remotecall_fetch#603(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1084
   in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1084
   in macro expansion at /Users/sacha/pkg/julia/usr/share/julia/test/runtests.jl:44 [inlined]
   in (::##15#22{Array{Any,1},UInt64})() at ./task.jl:363
ERROR: LoadError: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Error) at ./test.jl:397
 in do_test(::Base.Test.Threw, ::Expr) at ./test.jl:281
 in include_from_node1(::String) at ./loading.jl:541
 in include_from_node1(::String) at /Users/sacha/pkg/julia/usr/lib/julia/sys.dylib:?
 in macro expansion at ./util.jl:232 [inlined]
 in runtests(::String) at /Users/sacha/pkg/julia/usr/share/julia/test/testdefs.jl:7
 in (::Base.##594#595{#runtests,Tuple{String},Array{Any,1}})() at ./multi.jl:1034
 in run_work_thunk(::Base.##594#595{#runtests,Tuple{String},Array{Any,1}}, ::Bool) at ./multi.jl:1005
 in #remotecall_fetch#599(::Array{Any,1}, ::Function, ::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1059
 in remotecall_fetch(::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1059
 in #remotecall_fetch#603(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1084
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1084
 in macro expansion at /Users/sacha/pkg/julia/usr/share/julia/test/runtests.jl:44 [inlined]
 in (::##15#22{Array{Any,1},UInt64})() at ./task.jl:363
while loading /Users/sacha/pkg/julia/usr/share/julia/test/broadcast.jl, in expression starting on line 337
 in #remotecall_fetch#599(::Array{Any,1}, ::Function, ::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1060
 in remotecall_fetch(::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1059
 in #remotecall_fetch#603(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1084
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1084
 in macro expansion at /Users/sacha/pkg/julia/usr/share/julia/test/runtests.jl:44 [inlined]
 in (::##15#22{Array{Any,1},UInt64})() at ./task.jl:363
 in sync_end() at ./task.jl:314
 in macro expansion at ./task.jl:330 [inlined]
 in (::##11#18)() at /Users/sacha/pkg/julia/usr/share/julia/test/runtests.jl:36
 in cd(::##11#18, ::String) at ./file.jl:69
 in include_from_node1(::String) at ./loading.jl:541
 in include_from_node1(::String) at /Users/sacha/pkg/julia/usr/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:326
 in _start() at /Users/sacha/pkg/julia/usr/lib/julia/sys.dylib:?
while loading /Users/sacha/pkg/julia/usr/share/julia/test/runtests.jl, in expression starting on line 26
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.6.0-dev.693
Commit 2193638* (2016-09-18 19:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.5.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

 in runtests(::String, ::Int64) at ./interactiveutil.jl:652
 in runtests(::String) at ./interactiveutil.jl:641
```
cc @pabloferz. Best!

### PR DESCRIPTION
**Pull request by p-zubieta**

### CODE REVIEW

**Comment by martinholters** [comment]
This seems to work:
```Julia
@generated function broadcast_tup{AT,nargs,n}(f, As::AT, ::Type{Val{nargs}}, ::Type{Val{n}})
    Expr(:tuple, (Expr(:call, :f, (:(_broadcast_getindex(As[$i], $k)) for i=1:nargs)...) for k=1:n)...)
end
```
along with a changed call from `broadcast_c` to give the last parameter as a `Val`, too. I'm not claiming this is the best solution, but at least it seems to be _a_ solution.

**Comment by martinholters** [comment]
IIUC, `broadcast_c(f, ::Type{Tuple}, As...)` is only called when all arguments `As` are `Tuple`s or scalars. Then it might be worth to completely rewrite it to be inferable, but let's first try to fix the present issue ASAP in this PR.

**Comment by pabloferz** [comment]
@martinholters I updated with your version for now until we find a valid and more efficient way of fixing this. By the way, at one moment I had `Val{n}` in #16986, but lost it somewhere between rebases.

**Comment by pabloferz** [comment]
@vtjnash Do you have a better suggestion for fixing this?

**Comment by vtjnash** [comment]
The non-generated version is also probably much more efficient:

```julia
function broadcast_tup(f, As, n)
    return (f((_broadcast_getindex(A, k) for A in As)...) for k = 1:n)...)
end
```

**Comment by pabloferz** [comment]
Removing the generated function seems the best option as this case wasn't inferable anyway (PR already updated accordingly).

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
