### PR TITLE
rename module Random.dSFMT -> Random.DSFMT

### PR DESCRIPTION
**Pull request by rfourquet**
I think this was the only module in base/stdlib not following the naming convention for capitalization. I think the "SFMT" part should remain upper-case as these are initials for "SIMD-oriented Fast Mersenne Twister" (the "d" in "dSFMT" is for "Double precision", which is in lower-case in http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/)

### CODE REVIEW

**Comment by ViralBShah** [comment]
Or perhaps drop the D?

**Review by StefanKarpinski — APPROVED** [review]

**Review by ararslan — APPROVED** [review]

**Comment by rfourquet** [comment]
> Or perhaps drop the D?

I also thought about that, but "DSFT" is also the name another (very related) lib, so this could be confusing. But I guess it doesn't really matter for this internal module, and I will update to `DSFM` if you prefer.

**Comment by StefanKarpinski** [comment]
If you drop the `D` wouldn't that make the name `SFMT`?

**Comment by simonbyrne** [comment]
Maybe `@deprecate_binding`?

**Comment by rfourquet** [comment]
> If you drop the D wouldn't that make the name SFMT?

Ah right, I must have been quite tired :blush:

**Comment by vtjnash** [comment]
If we want an initial capital, maybe LibdSFMT?

**Comment by ViralBShah** [comment]
SFMT is the name of the single precision version. But we don't need the D, since we could use dispatch.

**Comment by ViralBShah** [comment]
Coming to think of it, maybe just capitalize the D and move on.

**Comment by rfourquet** [comment]
> SFMT is the name of the single precision version

IIRC, SFMT produces natively 32 bits (and also 64?), i.e it's more directly suitable if you need to generate integers. But I don't think we will ever have SFMT wrapped in base/stdlib (I made tests a while ago, which didn't seem to give an advantage to SFMT compared to our current solution for producing integers).

**Comment by rfourquet** [comment]
Added NEWS.md and `@deprecate_binding`.

**Pull request merged**
