### PR TITLE
CI (Buildkite): include the short commit hash in the artifact filename

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by staticfloat** [comment]
Can we just use the same name that [Julia itself would use](https://github.com/JuliaLang/julia/blob/e6e79f7ab4549ab4d6ffbad22038ebfce1368f93/Make.inc#L906)? We can use “make print-JULIA_BINARYDIST_FILENAME” to figure it out.

**Comment by DilumAluthge** [comment]
> Can we just use the same name that [Julia itself would use](https://github.com/JuliaLang/julia/blob/e6e79f7ab4549ab4d6ffbad22038ebfce1368f93/Make.inc#L906)? We can use “make print-JULIA_BINARYDIST_FILENAME” to figure it out.

Sure, that's easy to do when uploading the artifact from the `package` builder.

But when we download the artifact from a different builder (e.g. the `tester` builder), we don't have `make` or the Julia source code. So we need to be able to construct the name of the artifact on the `tester` builder without running `make`.

**Comment by staticfloat** [comment]
I’m pretty sure we can use wildcards when downloading artifacts.

**Comment by DilumAluthge** [comment]
Looks like the `make print-JULIA_BINARYDIST_FILENAME` approach is working correctly.

**Pull request merged**
