### PR TITLE
Only parse legal ISO 8601 YYYY dates, and YY optionally, also adding typo-guard

### PR DESCRIPTION
**Pull request by PallHaraldsson**
Completes part B. of #52348

I believe this is the user-facing API for parsing, and then best place to change this. I'm only aiming for that, for conformance with the standard. People can still construct arbitrary Dates and DateTimes, And actually parse. I didn't change parse itself. Wasn't sure if it's the best place to change. [I also want deserialization to work for any data out there.]

This is NOT defined as a breaking change, since the parsing conforms to a standard [EDIT: intentionally allows now fewer years, plus YY], and allowing more was then a bug for the API, if you define it according to the ISO standard.

This shouldn't break working code, though it may get an error thrown for e.g. <s>0, 0000</s>, 1582 or <s>90</s> as a years, which is a good thing, likely typos. Can be supported in a different PR with +1582, <s>+90</s>, +999999 etc. parsed. But that needs not hold off merging on master.

If people do not disagree with NOT parsing year 0 (the year that DOES NOT exist), this can be backported to 1.10.

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
> This not only adds that additional restriction to the ISO 8601 dateformat

No, it _requires_ the restriction (by default in the standard). And I'm mainly working on that. I'm doing an exception for yy-mm-dd format. I think we should actually deprecate that. It now gives a 0-99 year and you need to add Year(1900) yourself... Other languages do that for you.

**Comment by PallHaraldsson** [comment]
I've been looking at the input/parsing for now, but looking ahead to the output, I see in tests:

```
    @test string(Dates.Date(1, 1, 1)) == "0001-01-01" # January 1st, 1 AD/CE
    @test sprint(show, Dates.Date(1, 1, 1)) == "Dates.Date(\"0001-01-01\")"
    @test string(Dates.Date(0, 12, 31)) == "0000-12-31" # December 31, 1 BC/BCE
```

The last date doesn't actually exist, and actually neither the first in the (non-proleptic) calendar. So we shouldn't output, at least to a data-file, or send through protocols (also usually do not need to).

I'm thinking could we allow storing such proleptic (non-default option), and allow `@show` but disallow when:

println(Dates.Date(1, 1, 1))
ERROR: By default printing ISO dates only is allowed, per the standard, use alternative method.

I'm not sure what it could or should be, `string(Dates.Date(1, 1, 1), proleptic=true)`?

I could see this would be annoying. It could be done by storing proleptic status in the date itself, stealing one bit, or with a different type PData...

but 
3.1415929203539825

**Comment by PallHaraldsson** [comment]
This is seemingly finally done without failing any Dates tests, in case people want to review, comment, including on my typo-guard I came up with.

Note also I see for the first time, apparently unrelated to my code, this failure, in "pending" test that seems though done:
````
abstractarray                                     (5) |         failed at 2023-12-12T08:33:31.977
ProcessExitedException(5)
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:935
  [2] wait()
    @ Base ./task.jl:999
  [3] wait(c::Base.GenericCondition{ReentrantLock}; first::Bool)
    @ Base ./condition.jl:130
  [4] wait
    @ Base ./condition.jl:125 [inlined]
  [5] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:477
  [6] take!(c::Channel{Any})
    @ Base ./channels.jl:471
  [7] take!(::Distributed.RemoteValue)
    @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/remotecall.jl:726
  [8] remotecall_fetch(::Function, ::Distributed.Worker, ::String, ::Vararg{String}; kwargs::@Kwargs{seed::UInt128})
    @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/remotecall.jl:461
  [9] remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{String}; kwargs::@Kwargs{seed::UInt128})
    @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/remotecall.jl:492
 [10] (::var"#37#47"{Vector{Task}, var"#print_testworker_errored#43"{ReentrantLock, Int64, Int64}, var"#print_testworker_stats#41"{ReentrantLock, Int64, Int64, Int64, Int64, Int64, Int64}, Vector{Any}, Dict{String, DateTime}})()
    @ Main /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/test/runtests.jl:258
Worker 5 terminated.
gmpUnhandled Task ERROR: EOFError: read end of file
Stacktrace:
 [1] (::Base.var"#wait_locked#797")(s::TCPSocket, buf::IOBuffer, nb::Int64)
   @ Base ./stream.jl:947
 [2] unsafe_read(s::TCPSocket, p::Ptr{UInt8}, nb::UInt64)
   @ Base ./stream.jl:955
 [3] unsafe_read
   @ ./io.jl:870 [inlined]
 [4] unsafe_read(s::TCPSocket, p::Base.RefValue{NTuple{4, Int64}}, n::Int64)
   @ Base ./io.jl:869
 [5] read!
   @ ./io.jl:874 [inlined]
 [6] deserialize_hdr_raw
   @ /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/messages.jl:167 [inlined]
 [7] message_handler_loop(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/process_messages.jl:172
 [8] process_tcp_streams(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/process_messages.jl:133
 [9] (::Distributed.var"#103#104"{TCPSocket, TCPSocket, Bool})()
   @ Distributed /cache/build/default-armageddon-3/julialang/julia-master/julia-b8293286fe/share/julia/stdlib/v1.11/Distributed/src/process_messages.jl:121
```

**Comment by PallHaraldsson** [comment]
Can we get this merged ASAP on master, since 1.11 is far away of even an RC. This is conservative enough that no PkgEval should be needed, I want to see if people like this change and anyone discovers a real-world problem on master. If not this could be backported to 1.10. Could also be undone at any time, or add disallowing YY years by default... I backed out of doing that for now.

**Comment by mbauman** [comment]
This is _still_ breaking.  Even the simple `Date("1700")` fails.  Even if it weren't, I'm not convinced about the motivation. There's a well-defined meaning to how these dates are parsed and they do have a valid representation, even for the "invalid" years.

The standard itself says:

> By **mutual agreement** of the partners in information interchange, it is permitted to expand the component identifying the calendar year, which is otherwise limited to four digits.
> [...]
> Values in the range [0000] through [1582] shall only be used by **mutual agreement** of the partners in information interchange.

How is a Julia programmer meant to enter into that "mutual agreement" if the constructor errors on their behalf?

**Comment by PallHaraldsson** [comment]
It actually needs to be breaking to conform to the ISO standard; and needs more breaking ideally, I was now aiming to be only "technically breaking". Jeff, and I recall you want YY to stop working without adding 19 or 20 prefix. Plus, it's only breaking the rules according to semver when 1.11 released, it doesn't apply to unreleased. I'll promise to work on this more, or you can just revert before release.

The standard is on A. Gregorian (non-proleptic) and B. proleptic variant, what we _incorrectly_ support. And I'm proposing C. a typo-guard.

So what's the motivation, what led me to this? At first I was only aiming for A.

Then you can't parse yy-mm-dd with the default yyyy-mm-dd format. I backed out of disallowing it, not because I think it should be done, but because it's complex, more than I wanted to do myself right now. And I would have to drop some test and still keep -2 digit yy in some formats, such as mm-dd-yy, but in a different way ideally. So it always needs to be breaking.

So I allowed for two holes, the standard one, plus for yy, for now.

Along the way, I thought since I'm not following the standard strictly anyway, could I do option C as default? I think many data scientist would like it rejecting some dates entered with typos.

The standard bans B. proleptic as the default, but it's not clear it requires A. the full year range back to 1538 as a default. Reflecting on this I think I would still do that. But up to 9999 isn't terribly useful.

Then you need a non-default option to opt into the standard, A.

>How is a Julia programmer meant to enter into that "mutual agreement" if the constructor errors on their behalf?

You can use the default constructor, construct any Date[Time]. I don't think the standard actually requires you to parse any B. proleptic, it's just that if you DO opt into that mutual agreement, you must do it correctly and we don't. If I recall this would work:

Date("1700", dateformat"y-mm-dd")

This is actually a bad example:
julia> Date("1700")
1700-01-01

The standard has yyyy-mm format if I recall without date, and yyyy I think too for just a year (even yy for just the century), and us adding -01-01, as implied, is probably a bug.

**Comment by mbauman** [comment]
It's really hard to understand what's changing here.  In short, I think it's this:

* Disallows years outside of 1800-2099 with `Date` and `DateTime` constructors or with the default dateformat if the dateformat specifies a two-digit `yy`
* Disallows years outside of 0-99 and 1582-9999 for `Date` (and `DateTime`) constructors with all dateformats.
* Does not change `parse(::Type{Date}, ::String, ...)`

Is that correct? A succinct message like the above is far easier to evaluate.

**Comment by PallHaraldsson** [comment]
What would help get this merged? I could add some docs, for as is and/or change.

This fixes #50981 at least when parsing, and would also if strictly following the standard (i.e. without the typo-guard I came up with and no one asked for).

This is currently marked "breaking", but that does not apply if I only limit according to the standard, yes the typo-guard went further. I could drop it, though I would rather want this merged on master as is, and see about it before release. I don't think people would even notice, well or thank in case it catches actual typos...

**Comment by PallHaraldsson** [comment]
I would like this merged one way or another, preferably as is, even better not accept YY, which is also illegal, another bug vs the standard.

So since this fixes a bug, can it be merged, needs it be before the feature freeze, or ok after? Is there anything I can do to change this today to get this merged? Like just limit to 1583-9999 (meaning dropping the type-guard...)?

**Comment by mbauman** [comment]
I'm sorry, but I do not find the goal here compelling.  I don't believe the existing behavior is a bug; the ISO standard does explicitly allow such "out-of-spec" dates.  https://github.com/JuliaLang/julia/pull/52351#issuecomment-1852452901

**Comment by vtjnash** [comment]
As this is marked a breaking change, we cannot merge it in a point release.

**Comment by PallHaraldsson** [comment]
>I don't believe the existing behavior is a bug; the ISO standard does explicitly allow such "out-of-spec" dates.

It doesn't expect as you quote;
>Values in the range [0000] through [1582] shall only be used by _mutual agreement_ of the partners in information interchange.

So it seems you're saying simply by using Julia (i.e. its default) you assume mutual agreement of "the partners", while that is backwards. You want those years excluded by default (if not it's a bug), and a way to opt into allowing (which is possible with my change).

**Comment by mbauman** [comment]
There's absolutely nothing in the standard that says that only years 1800-2099 should be representable.  Breaking this is just plain broken.

Julia explicitly allows years in 0-1582 and it is documented it as such — it's documentation that this PR changes.  Changing that is a breaking change.  Yes, it's only one half of the ISO's "mutual agreement", but it's a documented part that folks are trusting. And constructing dates is only the beginning of any Julia program.  If the dates are constructable, programmers can subsequently add their own constraints.

**Pull request closed without merging**
