### PR TITLE
fix #17354, expand `Tuple{Vararg{Any,2}}` on construction

### LINKED ISSUE #17354: Arrays changes broke JuMP
```jl
using JuMP
m = Model()
@variable(m, tri_3[(i,j)=[(i,i+2) for i in 1:5],k=i:j])
```
gives
```
ERROR: UndefRefError: access to undefined reference
 in copy!(::Base.LinearFast, ::Array{Tuple{Vararg{Any,2}},1}, ::Base.LinearFast, ::Array{Tuple{Any,Any},1}) at ./abstractarray.jl:412
 in rehash!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::Int64) at ./dict.jl:483
 in _setindex!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::JuMP.Variable, ::Tuple{Tuple{Int64,Int64},Int64}, ::Int64) at ./dict.jl:606
 in setindex!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::JuMP.Variable, ::Tuple{Tuple{Int64,Int64},Int64}) at ./dict.jl:626
 in setindex!(::JuMP.JuMPDict{JuMP.Variable,2}, ::JuMP.Variable, ::Tuple{Int64,Int64}, ::Int64) at /home/mlubin/.julia/v0.5/JuMP/src/JuMPContainer.jl:49
 in macro expansion; at /home/mlubin/.julia/v0.5/JuMP/src/macros.jl:137 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

This seems to have been broken for quite a while but I haven't been using 0.5. I can spend a bit more time to generate a pure julia error case, but opening this in case the issue is obvious.
CC @IainNZ @joehuchette @tkelman @timholy 

Version:
```
julia> versioninfo()
Julia Version 0.5.0-dev+5247
Commit dad6836 (2016-07-09 01:29 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@timholy Is this ok? `f(x::Vararg{Any,3})` now gets expanded to `f(x, ?, ?)` but everything seems to work otherwise. Maybe I should just adjust the method showing code.

**Comment by timholy** [comment]
Thanks for tackling this! It seems fine to me; given that instantiation evidently works with non-leaftypes, it doesn't seem to make much sense to limit it to leaftypes. I'd be fine with it if this ends up requiring adjustment in the show code, or even in the result of that test (as long as the signature was "findable" from the output).

I hadn't gotten around to debugging this issue myself yet, but one thing that puzzled me is why `Vararg{Any,2}` wasn't being treated as identical to `Tuple{Any,Any}` for the purposes of dispatch. If memory serves (and it may not), at one point in the development of #11242 I had the two being treated "identically" _without_ introducing any kind of instantiation: perhaps the only test in the entire suite I had to comment out was [this one](https://github.com/JuliaLang/julia/blob/f8d67f7521287d9325e91fd2142dad5f222e6eaf/test/core.jl#L2246), and trying to get that to pass, esp. given my limited understanding of how `ccall` works, led me to introduce instantiation. (Obviously, the codegen specialization issue that @vtjnash fixed for me also required instantiation, so clearly it has major benefits.) But I guess one risk of having introduced instantiation is that it becomes harder to detect regressions or limitations in type-equivalence.

I almost wonder if we want to put instantiation under some kind of flag that we can change via a `ccall`, and have a section of `test/core.jl` that turns it off?

**Comment by vtjnash** [comment]
this also should fix https://github.com/JuliaLang/julia/issues/16618

**Comment by JeffBezanson** [comment]
Fixed the showing issue, and found what seems to be an unused function to boot.

@timholy you're right we could/should probably do more to fix this from the other end, but for now I think this is a reasonable defensive fix.

**Pull request merged**
