### PR TITLE
Use llvm-dsymutil on recent-enough LLVM

### PR DESCRIPTION
**Pull request by Keno**
Darwin's dsymutil has bugs that can make it annoying to debug julia on OS X. LLVM ships with its own version of dsymutil, which for LLVM >= 3.8 is mature enough to be usable and more stable. On those versions of LLVM, prefer llvm-dsymutil over the system one.

### CODE REVIEW

**Comment by vtjnash** [comment]
you can't reliably get LLVM_VER in Make.inc

**Comment by Keno** [comment]
We already rely on it in other places in this Makefile. If we can't rely on it, those need to change too. However, I thought we always included versions before Make.inc.

**Comment by vtjnash** [comment]
The other usage (https://github.com/JuliaLang/julia/blob/master/Make.inc#L361-L363) doesn't actually work correctly, but it doesn't matter since it's redundant with llvm-config's own output. 

The best workaround I could manage is:
https://github.com/JuliaLang/julia/blob/jn/makefile_o/Make.inc#L653-L654
but you have to really careful copying that, since this only works after llvm-config exists -- and that is known to be true only because the result of that macro is only used when calling llvm-config.

**Comment by Keno** [comment]
This is not relevant anymore. The dsymutil that comes with OS X these days is just llvm-dsymutil.

**Pull request closed without merging**
