### PR TITLE
speed up resolve-scopes lowering pass

### PR DESCRIPTION
**Pull request by JeffBezanson**
Use a table to avoid each symbol lookup being O(n) in the scope nesting depth.

Usually scopes are not nested too deep, but our `let` is actually `let*`, so each variable also introduces a new scope, so long lists of let-bound variables can be a problem.

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by oscardssmith** [comment]
@Keno  what type of tests do you want? Tests that the result is correct, or that the performance is good?

**Comment by Keno** [comment]
Tests that the performance is reasonable would be good.

**Comment by oscardssmith** [comment]
Given that this is "only" a quadratic speedup, that test seems like it will be kind of brittle... Did you have something in mind?

**Comment by Keno** [comment]
If we can't reliably separate the fixed and broken cases using timing, I guess putting it on nanosolider would be reasonable.

**Comment by oscardssmith** [comment]
Is this good to merge now that we have a benchmark PR?

**Pull request merged**
