### PR TITLE
Change `for i=1:length(A)` to `for i in eachindex(A)`

### PR DESCRIPTION
**Pull request by timholy**
PSA: when writing algorithms with potentially-multidimensional `AbstractArray`s, please write `for i in eachindex(A)` rather than `for i = 1:length(A)` whenever you don't have some reason to insist that `i` be an integer.

This fixes performance problems for many operations (see https://github.com/JuliaLang/julia/issues/1168#issuecomment-93804453).

There are a few outstanding issues, some of which arise when trying to use one index for two different arrays in circumstances in which we have not previously required the shapes to match:
- [ ] `map!`, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/abstractarray.jl#L1300 and https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/abstractarray.jl#L1337
- [ ] logical indexing, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L332, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L408, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L422
- [ ] `ccopy!`, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L1421

and others of which pertain to returning an index to the user (should we return `CartesianIndex`es?)
- [ ] `find`, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L1150 and https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L1164
- [ ] `findin`, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L1271

and finally others where we may want to change the algorithm:
- [ ] `cummin/min/cummax/max`, https://github.com/JuliaLang/julia/blob/ef062117bab19959a6905b1bb6d7963b42dddea4/base/array.jl#L1558

### CODE REVIEW

**Comment by pao** [comment]
This sounds like it should be a mailing list post, and an addition to the MATLAB differences list (not sure what other languages this is relevant for)? Should use of `eachindex()` in user code targeting v0.4 be considered the default?

**Comment by lindahua** [comment]
+1

A benchmark that shows the speed improvement + documentation of underlying functions (e.g. ``linear indexing``) would be great!

**Comment by timholy** [comment]
`eachindex` is old news, and you can find benchmarks in various issues (#8432, #8501, #9329, #10507). This PR was just tackling the overdue issue of making more algorithms use it.

@lindahua, to catch you up: `eachindex` does linear indexing when it is fast (if the trait `linearindexing(A) == LinearFast()`), and cartesian indexing when not. So you can get the best of both worlds that way.

Yes, I agree that more needs to be done to advertise this.

**Comment by mbauman** [comment]
Documentation in #10859.

**Comment by pao** [comment]
> eachindex is old news

> Yes, I agree that more needs to be done to advertise this.

The team as a whole spends more time being awesome than I have time to keep up with the awesomeness, and I suspect I'm trying harder than the average Julia user. Thanks for highlighting the relevant issues for me.

**Comment by IainNZ** [comment]
Documentation commit: https://github.com/JuliaLang/julia/commit/9b4f2123d22d662c16cba46d46c091f19aba8bf3

I also didn't know this was a function for Mortal Men to use in their code, assumed it was just for the Elvish-kings under the Base.sky and Dwarf-lords in their Base.halls of Base.stone.

**Comment by milktrader** [comment]
Thanks for the PSA!

**Comment by pao** [comment]
> I also didn't know this was a function for Mortal Men to use in their code, assumed it was just for the Elvish-kings under the Base.sky and Dwarf-lords in their Base.halls of Base.stone.

You're from New Zealand. Doesn't that count? (Also, it's morning here, and you've added substantially to my enjoyment of it. Thank you.)

Would it make sense for something along the lines of "you probably want to use this everywhere you're currently using the range `1:length(A)` for iteration over an array" to be made explicit in that documentation? Otherwise it's not obvious that you'd want to use it.

**Comment by timholy** [comment]
It seems we should probably add something to the manual chapter on arrays.

**Comment by timholy** [comment]
This already needs rebasing. While I'm at it, what do people think about some of the TODO items above? 
For the three categories:
- Haven't previously been insisting on matching sizes: we could try adding those constraints and see what breaks, unless there are objections
- Returning an index to the user: I think the big decision is whether we have a `sub2ind` that works on `CartesianIndex` (and hence return an integer), or if we should return an array of `CartesianIndex`es.
- Changing the algorithm: that can be done next time someone complains about their performance, I don't see any reason to tackle that now :smile:

**Comment by mbauman** [comment]
Man, those are all tough decisions.  The choice to make `eachindex` return either an integer *or* a CartesianIndex is a step towards putting Cartesian indices into user's hands more often (whether they realize it or not).  But in that case, it seems more obvious that the returned element is specifically for *indexing*.  There are lots of use-cases for find… and I can only see that causing trouble.  Especially since it's generally an anti-pattern to index directly from the results of find; you should just be using the logical index instead.

Logical indexing feels like we're still doing it wrong.  But I'm not sure how to make it better.  See also https://github.com/JuliaLang/julia/pull/10065#issuecomment-93853097.

But I agree on punting the algorithm changes to another day, perhaps with a comment in the code about how it could be written better.

**Comment by timholy** [comment]
I agree that changing `find` semantics seems to be asking for trouble. One option would be `find{T}(::Type{T}, A)` and have `T` default to `Int`; people who want the cartesian version could use `find(CartesianIndex, A)`.

I can rebase this and merge it, and leave hard decisions for another day :smile:.

**Comment by kmsquire** [comment]
> One option would be `find{T}(::Type{T}, A)` and have `T` default to `Int`; people who want the cartesian version could use `find(CartesianIndex, A)`.

+1 -- this is really nice... although I'd love to have a shorter name for `CartesianIndex`.

**Comment by timholy** [comment]
I realized that my proposal for `find(CartesianIndex, A)` is basically what `findn` does, except the latter returns a tuple of `Vector{Int}` indexes. So we should probably have one or the other but not both.

**Comment by timholy** [comment]
As requested by @pao, mailing-list post is [here](https://groups.google.com/d/msg/julia-users/CF_Iphgt2Wo/V-b31-6oxSkJ).

**Comment by tkelman** [comment]
That bitarray segfault on appveyor is worrying... https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.3946/job/ius9kwerpcskfbi8

More recent builds have passed though, so maybe it's just a case of #9176?

**Comment by timholy** [comment]
The earlier version of this passed on all 3 platforms, and all I did was fix a tiny merge conflict that had nothing to do with BitArrays. So I wasn't worried about this being the cause.

**Pull request merged**
