### PR TITLE
performance tweak to `Random.shuffle!`

### PR DESCRIPTION
**Pull request by tlcz**
a little performance tweak to shuffle!

### CODE REVIEW

**Comment by oscardssmith** [comment]
this isn't valid for abstractarray. can you not put a checkbounds above the loop to deal with this?

**Comment by tolcz** [comment]
hi, do you mean as it is in `randperm`?
```julia
function randperm!(r::AbstractRNG, a::Array{<:Integer})
    n = length(a)
    @assert n <= Int64(2)^52
    n == 0 && return a
    a[1] = 1
    mask = 3
    @inbounds for i = 2:n
        j = 1 + rand(r, ltm52(i, mask))
        if i != j # a[i] is undef (and could be #undef)
            a[i] = a[j]
        end
        a[j] = i
        i == 1+mask && (mask = 2mask + 1)
    end
    return a
end
```

**Comment by tolcz** [comment]
oh, silly me
I was not aware of the recent commit  2d4d096c599cb92fc2ea2a107693ac1293edcadc which did what I intended. My much older commit 19955d88a5237b35dfe0b8de3cf7899b0a71f176 became obsolete.
```
commit 19955d88a5237b35dfe0b8de3cf7899b0a71f176
Author: Tomasz Olczak <tolczak@gmail.com>
Date:   Mon Jan 23 18:02:05 2023 +0100

    performance tweak to shuffle!
```

**Comment by tolcz** [comment]
fixed by 2d4d096c599cb92fc2ea2a107693ac1293edcadc

**Pull request closed without merging**
