### PR TITLE
More missing permuteddims tests

### PR DESCRIPTION
**Pull request by bramtayl**
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/permuteddimsarray.jl#L198)
[Uncovered](https://codecov.io/gh/JuliaLang/julia/src/master/base/permuteddimsarray.jl#L202)

### CODE REVIEW

**Comment by bramtayl** [comment]
CI failure unrelated?

**Comment by kshyatt** [comment]
Looks like this doctest was failing all over the place ...

**Comment by kshyatt** [comment]
@bramtayl do you want me to close and reopen to rerun ci and see if that fixes things? Or rebase onto latest master?

**Comment by bramtayl** [comment]
Sure either would be great!

**Comment by bramtayl** [comment]
Let me know if you want me rebase this

**Pull request closed without merging**
