### PR TITLE
remove LocalProcess and ProcessGroup from exports

### PR DESCRIPTION
**Pull request by amitmurthy**
These two types are only used internally and not part of any public interface.

The concept of a process group has not yet been detailed out or implemented in Base - it is just a placeholder for a possible future implementation.

### CODE REVIEW

**Comment by kshyatt** [comment]
So once this is merged, I should close my PR to doc `ProcessGroup`, right? 👍

**Comment by tkelman** [comment]
This is a really odd thing to merge during a feature freeze.

**Comment by amitmurthy** [comment]
It is code cleanup. Not addition/deletion of features.

**Comment by tkelman** [comment]
It would break any code that used these.

**Comment by amitmurthy** [comment]
The exports were a relic from the initial implementation of parallel. They are not used outside of Base. Keeping them in exports.jl were an oversight all this time. Mostly because they were in the section "exported types" and not in the section under "multi processing"

**Pull request merged**
