### PR TITLE
Fix for OSX spawn test

### PR DESCRIPTION
**Pull request by quinnj**
Ran into this several times while running the tests about a million times so far for https://github.com/JuliaLang/julia/pull/22441. I don't think this is related to https://github.com/JuliaLang/julia/issues/17626, but one could always hope, right?

### CODE REVIEW

**Review by vtjnash — APPROVED** [review]

**Comment by iblis17** [comment]
Not sure it's related or not, I found a way to make ```success(`true`)``` insane.

1. borrow a MBA from my classmate :p 
2. test.jl
```julia
using Base.Test

for i in 1:10000  # just a large number
  println(i)
  @test success(`true`)
end
```
yes, we need `@test` to trigger crashing/freezing. no idea why single `success` works fine.
3. `julia test.jl`
4. hold your `Crtl+t`, keep sending SIGINFO
5. sometimes you got segmentation fault; sometimes the program freezed, only `kill -9` can stop it.

**Comment by vtjnash** [comment]
@iblis17 looks unrelated. I ran your code in my debugger and found the issue is that Apple's libunwind does not conform to its specification (its `unw_init_local` allocates memory, but is documented to not allocate memory)

**Comment by iblis17** [comment]
@vtjnash :-o file it as another issue?

**Comment by vtjnash** [comment]
Should be a radar, but I'm not very active about getting those submitted.

**Pull request merged**
