### PR TITLE
Skip certain tests when running as root, fix #15683

### LINKED ISSUE #15683: Expected SystemError during `read` test.
This happens deterministically:

```julia
root@server1 ~ # julia-dev
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3329 (2016-03-29 22:27 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a5f2c7a (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Base.runtests("read")
     * read                 Test Failed
  Expression: open(f)
    Expected: SystemError
  No exception thrown
ERROR: LoadError: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at ./test.jl:322
 in do_test_throws(::Base.Test.Returned, ::Expr, ::Type{T}) at ./test.jl:256
 [inlined code] from ./test.jl:133
 in (::##29#43)(::ASCIIString) at /root/julia-dev/usr/share/julia/test/read.jl:421
 in mktempdir(::##29#43, ::ASCIIString) at ./file.jl:272
 in mktempdir(::Any) at ./file.jl:270
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::UTF8String) at ./loading.jl:417
 [inlined code] from ./util.jl:179
 in runtests(::UTF8String) at /root/julia-dev/usr/share/julia/test/testdefs.jl:7
 in run_work_thunk(::Base.##243#244{##16#24,Tuple{UTF8String}}, ::Bool) at ./multi.jl:744
 in remotecall_fetch(::Any, ::LocalProcess, ::UTF8String, ::Vararg{UTF8String}) at ./multi.jl:815
 in remotecall_fetch(::Any, ::Int64, ::UTF8String, ::Vararg{UTF8String}) at ./multi.jl:831
 [inlined code] from /root/julia-dev/usr/share/julia/test/runtests.jl:36
 in (::##15#23{Array{Any,1}})() at ./task.jl:308
while loading /root/julia-dev/usr/share/julia/test/read.jl, in expression starting on line 3
 in remotecall_fetch(::Any, ::LocalProcess, ::UTF8String, ::Vararg{UTF8String}) at ./multi.jl:816
 in remotecall_fetch(::Any, ::Int64, ::UTF8String, ::Vararg{UTF8String}) at ./multi.jl:831
 [inlined code] from /root/julia-dev/usr/share/julia/test/runtests.jl:36
 in (::##15#23{Array{Any,1}})() at ./task.jl:308
 in sync_end() at ./task.jl:274
 [inlined code] from ./task.jl:283
 in (::##11#19)() at /root/julia-dev/usr/share/julia/test/runtests.jl:31
 in cd(::##11#19, ::ASCIIString) at ./file.jl:48
 in include(::ASCIIString) at ./boot.jl:234
 in include_from_node1(::UTF8String) at ./loading.jl:417
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /root/julia-dev/usr/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.0-dev+3329
Commit a5f2c7a (2016-03-29 22:27 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, westmere)

 in error(::ASCIIString) at ./error.jl:21
 in runtests(::ASCIIString, ::Int64) at ./interactiveutil.jl:422
 in runtests(::ASCIIString) at ./interactiveutil.jl:411
 in eval(::Module, ::Any) at ./boot.jl:237
```

This is the relevant line:

* https://github.com/JuliaLang/julia/blob/master/test/read.jl#L421

Comment in the code reads:

> msvcrt _wchmod documentation states that all files are readable,
> so we don't test that it correctly set the umask on windows

### PR DESCRIPTION
**Pull request by tkelman**
docker containers are probably the only place you should ever be doing this

edit: or for testing `chown`

### CODE REVIEW

**Comment by tkelman** [comment]
cc @Ismael-VC I tested this in an opensuse docker container, want to give this branch a try on your setup?

**Comment by vtjnash** [comment]
docker documentation says not to run as root inside: https://docs.docker.com/engine/security/security/

can we just fail early and remove these untested tests?

**Comment by tkelman** [comment]
The vast majority of dockerfiles don't do that unfortunately. While that would be a good idea, I don't see this PR as being harmful. We could remove the only-runs-as-root branch of these if you feel strongly about it.

**Comment by nalimilan** [comment]
+1

Even if the tests aren't run most of the time, they could still allow somebody to detect breakage, and in any case they don't hurt. Having not-run tests is not the same as having untested code paths.

**Comment by vtjnash** [comment]
we should at least print an error "chmod tests skipped due to running tests as root (not recommended)"

**Comment by vtjnash** [comment]
> Though there's no way to test that chown works properly without being root

it can be tested for chgrp behavior and functionality

**Comment by tkelman** [comment]
warning added.

osx travis timed out due to an llvm bottle download failure, restarted
```
Error: Failed to download resource "llvm37-julia"

Download failed: https://juliabottles.s3.amazonaws.com/llvm37-julia-3.7.1_1.mavericks.bottle.3.tar.gz

Warning: Bottle installation failed: building from source.
```

**Pull request merged**
