### PR TITLE
WIP: change getfield lowering and call overloaded version

### PR DESCRIPTION
**Pull request by ihnorton**
Here is an attempt to implement getfield overloading, for #1974.

### CODE REVIEW

**Comment by stevengj** [comment]
Any chance of resurrecting this?

**Comment by ihnorton** [comment]
Ok, I'll have another go at this.

**Comment by stevengj** [comment]
Awesome, thanks for rebasing.

**Comment by stevengj** [comment]
@JeffBezanson and @ihnorton, what are the major remaining issues with this?

**Comment by ihnorton** [comment]
Not really ready for review. I have more local work that fixed most of the inference issues (I think). But I'm stuck in bootstrap purgatory now.

**Comment by stevengj** [comment]
Any timeline for resurrecting this?

**Comment by yuyichao** [comment]
Just to state the reason I like `getfield` overload before I forgot about it since I didn't find it explicitly mentioned anywhere in the thread (although I might just have missed it). I've also talked about it with @carnaval a while ago.

I think `getfield` overload is a nice way to avoid name clashing of object properties with local variables by having per-object namespace.

For example, I would like to have a type/object for an optical transition, which has many properties (frequency `freq`, angular frequency `omega`, wavelength `lambda`, line width `gamma` etc). I don't want to store everything in the structure since they are not independent and are not always all needed. I also don't want to write a global function for each of them since they would collide with one of my local variables very easily unless I make the name really long. Having the method names bind to the object would be the best solution to this problem I can think of.

> Any timeline for resurrecting this?

Probably after `0.4` is released?

**Comment by ihnorton** [comment]
Will open a new PR if I get further in the future.

**Comment by stevengj** [comment]
Would be great to see a PR on this for 0.5.

**Comment by yuyichao** [comment]
I just rebased this on the current master at [yyc/ovldot](https://github.com/JuliaLang/julia/tree/yyc/ovldot) although I won't necessarily have time to push this further anytime soon either......

**Comment by stevengj** [comment]
Can you or @ihnorton open a new PR with that?   It's easier to discuss a PR than a branch.

**Pull request closed without merging**
