### PR TITLE
Correct Julia/Python slicing comparison

### PR DESCRIPTION
**Pull request by cscherrer**

### CODE REVIEW

**Review by KristofferC — DISMISSED** [review]

**Comment by anderson15** [comment]
It seems like whether or not this is a beneficial change depends on if one wants to also illustrate the zero-indexing of Python versus the one-indexing of Julia. If so, then I think the original version was correct.

**Review by Keno — CHANGES_REQUESTED** [review]
As noted, there's zero indexing in python (though perhaps an additional parenthetical would serve well here).

**Comment by cscherrer** [comment]
Oops, good catch. I too make mistake, and I use Python a lot. Zero/one indexing so easily conflates with the half-open interval thing, makes this surprisingly tricky to reason about in one step.

**Comment by mbauman** [comment]
Gosh, that is hilariously hard to understand.  Sorry I missed this while it was still open — I'd say an improvement here would still be valuable.  Maybe: "To select the second and third values from `a`, use `a[2:3]` in Julia instead of Python's `a[1:3]`.

**Comment by cscherrer** [comment]
How about something like

"Python indexing is 0-based and uses half-open intervals, while Julia
indexing is 1-based and uses closed intervals. So for example, say
`x=['a','b','c','d']` (valid in both languages). Then (Python) `x[1:3] ==
['b','c']` but (Julia) `x[1:3] == ['a','b','c']`"

**Comment by cscherrer** [comment]
How about something like "Python indexing is 0-based and uses half-open intervals, while Julia indexing is 1-based and uses closed intervals. So for example, say `x=['a','b','c','d']` (valid in both languages). Then (Python) `x[1:3] == ['b','c']` but (Julia) `x[1:3] == ['a','b','c']`"

**Comment by mbauman** [comment]
Yes, that's great. For consistency, we try to list Julia's behaviors first and the others' behaviors second.

**Comment by ViralBShah** [comment]
I feel the original was fine, and am closing this. Please reopen if we can improve.

**Pull request closed without merging**
