### PR TITLE
Separate initialization from computation in matmul (fixes #10616)

### LINKED ISSUE #10616: generic matmul depends on zero
Currently generic matmul uses `zero(eltype(a))` to fill the initial output array with zero values. When defining a new numeric type, this can be annoying (you may not have defined a `zero` method yet), but there are also real-world case where this causes matmul to fail, such as when you have an `Any` array that just happens to contain numbers that you want to multiply:

``` jl
julia> A = convert(Array{Any}, rand(3,4))
3x4 Array{Any,2}:
 0.994922  0.18993   0.826601  0.82501
 0.10378   0.937165  0.753685  0.321605
 0.269249  0.678925  0.749532  0.305874

julia> A*rand(4)
ERROR: MethodError: `zero` has no method matching zero(::Type{Any})
 in generic_matvecmul! at linalg/matmul.jl:319
 in * at linalg/matmul.jl:74
```

On the one hand, you really want this to be a `Float64` matrix for performance. But on the other hand, this really ought to work in any case.

### PR DESCRIPTION
**Pull request by timholy**
This also makes the computation cumulative, which might occasionally be useful in its own right.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Does this change the visible behavior of in-place matmul? I agree that accumulating into `C` may be a better general way to expose this, but I'm concerned that people may allocate uninitialized matrices and pass them in as the first argument, thus producing garbage results.

**Comment by andreasnoack** [comment]
I think this is better handled in terms of supporting `α` and `β` in general for matrix multiplications and then follow BLAS' convention that if `β=0` then `β*C[i,j]=0` whatever `C[i,j]` includes. For user defined types it is probably also more natural to define `*` than `fill!`.

I can try to finalize my branch with this. I think, it is mainly lagging complete testing.

**Comment by timholy** [comment]
@StefanKarpinski, all `A_mul_B!`-style calls zero the output; it's only if you directly call `generic_matmatmul!` that you get the different behavior. (That function is not exported.)

@andreasnoack, I'd be happy to defer to you on this one, if your branch fixes this problem. One thing I'll ask about: if `C` contains uninitialized memory, then `C[i,j]` happens to be `Inf` or `NaN`, then `0*C[i,j]` doesn't yield 0. So it's not entirely obvious to me that relying on arithmetic automatically solves the problem.

**Comment by andreasnoack** [comment]
@timholy What I meant with "whatever `C[i,j] includes" was that BLAS doesn't follow IEEE here. See line 249 of http://www.netlib.org/lapack/explore-html/dc/da8/dgemv_8f_source.html In that way you don't have to care about initialization of your arrays before multiplication.

**Comment by timholy** [comment]
Got it, thanks for clarifying. But of course, `generic_matmatmul!` doesn't call BLAS, so we'd have to do the same thing ourselves.

However, I'll close this in deference to your efforts.

**Comment by andreasnoack** [comment]
Yes. I'll add that functionality to the generic multiplication methods as well.

**Pull request closed without merging**
