### PR TITLE
Update libunwind tarball

### PR DESCRIPTION
**Pull request by yuyichao**
Include musl fix and move to Amazon S3

### CODE REVIEW

**Comment by tkelman** [comment]
LGTM. Wonder how long upstream will take to respond,

Isn't the apple version of libunwind part of llvm now? Can it build and do what we need on Linux? Would be more actively maintained from that upstream...

**Comment by yuyichao** [comment]
I've just found [this post](http://lists.nongnu.org/archive/html/libunwind-devel/2016-01/msg00002.html) and one of the libunwind maintainer said that,

> To make libunwind usable in a malloc tracer, people generally
> implement their own dl_iterate_phdr() that doesn't call malloc.
> libunwind-1.1 is old and I've not been able to devote enough time to
> libunwind to make a new release.

so it doesn't look too promising.... =(

I was also wondering what's the state of the [llvm libunwind](https://github.com/llvm-mirror/libunwind). I don't see too much architecture dependent stuff in it so I'm not so sure if it has all what we need...

**Comment by nalimilan** [comment]
For those not subscribed to the thread and who didn't go there to read it, the maintainer has made a 1.2-rc1 tarball here: http://download.savannah.gnu.org/releases/libunwind/libunwind-1.2-rc1.tar.gz Am I right that we can switch to it?

**Comment by yuyichao** [comment]
Yeah I was following that thread and is hoping that we can use the final 1.2 tarball soon...

**Pull request merged**
