### PR TITLE
Add functions nparams, getparam to access type parameters

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by yuyichao** [comment]
IIRC, the type inference cannot handle this yet. Would be nice to fix that before we encourage people to use this instead of using sth like `get_second_param_for_T{A,B}(::Type{T{A,B}}) = B` to get the specific type parameter they want.

Ref https://github.com/JuliaLang/julia/issues/10880

**Comment by vtjnash** [comment]
when would you use this? a type parameter only has meaning when it is extracted from a particular abstract type.

**Comment by yuyichao** [comment]
@vtjnash Do you mean that when there's `abstract A{T1,T2}` and `type B{T} <: A{K{T},V{T}} end` it is usually more useful to obtain `T1`/`T2` from a instantiation of `B`?

I think I've seen a few cases where getting the type parameter of a concrete type is useful. Mostly when the type parameter of the concrete type is some values to be specialized on, similar to getting the value from a `Val`.

**Comment by vtjnash** [comment]
i mean that B.parameters[1] has no meaning without context

**Comment by mauro3** [comment]
I do need to access the parameters of `Tuple{}` but maybe that should be special-cased, as explored by @mbauman's https://github.com/mbauman/Tuples.jl.

**Comment by eschnett** [comment]
Accessing parameters of a tuple is already possible, because one can access the types of an object's fields via `fieldtype`. For a tuple, these two happen to be identical.

**Comment by vtjnash** [comment]
For Tuple, this is a duplicate of https://github.com/JuliaLang/julia/pull/11547. See discussion there.

For this in general, see my conclusion at https://groups.google.com/d/msg/julia-users/d-HQdYEDjbc/jr_s_ar-AgAJ for not wanting to encourage this usage.

**Pull request closed without merging**
