### PR TITLE
faster rand(::MersenneTwister, ::Union{[U]Int{8,16,32},Bool})

### PR DESCRIPTION
**Pull request by rfourquet**
Now that generating scalar Float64 values (i.e. 52 random bits) is even faster,
it becomes faster to just generate such values and make small integers out of
them, rather than saving entropy bits with using the integer cache.

I tested on two different machines, the observed speed-up ranges from 15% to 40%.

### CODE REVIEW

**Comment by vtjnash** [comment]
IIUC, this changes the random number stream? We should make sure to run nanosoldier on this to have an idea of which tests that’ll affect.

**Comment by rfourquet** [comment]
> this changes the random number stream?

Yes.

@nanosoldier `runbenchmarks("random", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/25277#issuecomment-354293140) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/89ca132b63adac15306c46afc74ae17b17174000/79d11c3_vs_1238bad/report.md). cc @ararslan

**Comment by rfourquet** [comment]
It's funny: Nanosoldier shows two improvements, which are consequences of the change here (for `ComplexF32` and `Complex{UInt32}`), but not the most direct improvements for the small integer types.

**Comment by vtjnash** [comment]
I mean we should run it on all tests. Some of them are sensitive to the numbers themselves, so we will want to know which changes in the next daily are “noise”.

**Comment by rfourquet** [comment]
Ah right, got it! 
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/25277#issuecomment-354314400) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/43806d7b94d0ea35e50900e7c61ea7371b4df270/79d11c3_vs_1238bad/report.md). cc @ararslan

**Comment by rfourquet** [comment]
Freebsd CI failure is a timeout.

**Pull request merged**
