### PR TITLE
Add 'ndims' and 'size(t)' for tuples.

### PR DESCRIPTION
**Pull request by m-j-w**
Implements suggestions made in #21095.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
I would not say `size` is part of the iterable interface. Something can be iterable without having a multi-dimensional structure. I'm undecided on whether these definitions make sense, but they certainly aren't justified only by tuples being iterable.

**Comment by m-j-w** [comment]
Suppose you write a function that takes some indexible container of n dimensions, and follow the recently introduced general indexing pattern. Then this works nicely with arrays. Without the proposed `size` definition, however, it doesn't work for tuples 'out-of-the-box' although it could. In general, there's nothing special about a tuples. They're just a heterogeneous one-dimensional container of fixed length.
Most if not all other functions that are somewhat associated with iterating and indexing are implemented for tuples, that is `length`, `first`, `eachindex`, `eltype`, even `size(t, n)`. Just not those two which would make tuples adhere to same general indexing interfaces as arrays do. The addition of the two would only make it explicit that a tuple is one-dimensional.
A particular use case is when an `NTuple{N,VecElement{T}}` is to replace an `Array{T,D}` and vice versa.
The proposed additions would simplify such a transition in that it is then in more cases unnecessary to differentiate between arrays and tuples.

**Comment by vtjnash** [comment]
As Jeff said, `Tuple` is not an array-like entity. Filling in some arbitrary type-parameter constraints doesn't really justify stating that.

**Comment by m-j-w** [comment]
Conceptually, I would indeed consider `Vector{Any}` and a `Tuple` to be alike.
And I believe mathematically there's also a connection http://mathworld.wolfram.com/n-Tuple.html.
So I tend to believe my claim not to be completely unjustified.

**Comment by JKrehl** [comment]
@m-j-w 
They are not alike, a `Tuple` is not `Any`-typed but statically for every element, besides being immutable. This is a computational difference but one more important than the mathematical similarity.

Especially in light of the immutability algorithms defined for `Vectors` should not be simply transferrable to `Tuples`.

**Comment by nalimilan** [comment]
OTOH it seems inconsistent to implement `size(t, 1)` but not `size(t)`.

**Comment by JeffBezanson** [comment]
That's a good point. This `size` method is very old; it's possible it was never really needed but was never revisited.

**Comment by nalimilan** [comment]
Indeed [`size` is not required](http://docs.julialang.org/en/stable/manual/interfaces/#iteration) for `HasLength` iterators.

**Comment by andyferris** [comment]
Yes, `Tuple` definitely seems to be a `HasLength` iterator but not a `HasShape` iterator (unless we want to imply *anything* that has `length` gets to inherit `size(x) = (length(x),)` unless overridden - but that seems to detract from the *raison d'être* of `HasShape`).

**Comment by m-j-w** [comment]
I agree that tuples might not require the full multidimensional array interface, although I believe are more common interface would be beneficial. But that's a different story.
Solving the inconsistency with `size(::Tuple, x)` by removing it would be the opposite of this PR and requires deprecation beforehand.

Thus, I propose to close this PR.

**Comment by jebej** [comment]
I would vote for implementing `size(t::Tuple)`. It can be useful when . broadcasting over an array with a function that takes two argument, but where the second argument should not be broadcast over. It avoids creating an unneeded array:

```julia
somefunction.(somearray, [somesecondarg])
```

**Pull request closed without merging**
