### PR TITLE
Fix mod1, fld1 issues.

### PR DESCRIPTION
**Pull request by GunnarFarneback**
This fixes the mod1 and fld1 inconsistencies noted in #20355. Potentially this can cause performance regressions since it removes the "efficient version for integers" in favor of more correct results. New tests are added.

### CODE REVIEW

**Comment by simonbyrne** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/25588#issuecomment-358101391) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/565139fd1283bd623d90c9119c1cdf797c9e805c/02db793_vs_aea9155/report.md). cc @ararslan

**Comment by GunnarFarneback** [comment]
The only actual uses I can find of `mod1` and `fld1` in base and stdlib are three lines in the REPL code, so the performance regressions seem likely to be noise only.

The definition of `mod1(x, y)` and `fld1(x, y)` for negative `y` could possibly be debated (and I don't have a strong opinion) but the tests follow the documentation for `mod1` and the implied consistency rule from the last example of the `fld1` documentation.

**Comment by eschnett** [comment]
To my knowledge, the main reason why `fld1` and `mod1` are in the standard library is to deal with the 1-based array indexing. Thus what happens for a negative second argument isn't too important, and probably wasn't well-defined in the beginning.

This property is important, as it allows "converting" between one-dimensional and multi-dimensional arrays:
```
julia> for i in 1:7
             println("$i => $(fld1(i, 3)) $(mod1(i, 3))")
       end
1 => 1 1
2 => 1 2
3 => 1 3
4 => 2 1
5 => 2 2
6 => 2 3
7 => 3 1
```

What happens for a negative second argument should probably be defined by analogy and by looking at what `fld` and `mod` do, in addition to using common sense and ensuring good performance. I don't think it's worth sacrificing performance to achieve elegance here.

Array-heavy code (as is e.g. found in `CartesianIndices`) will probably do the `fld`/`mod` equivalent after converting to 0-based indexing. In fact implementing `fld1` and `mod1` by converting to 0-based indexing is probably the fastest way to go, and I suggest to do that, and to use it as definition. The general implementation and the documentation should be updated afterwards.

If using `fld1` and `mod1` for converting between one-dimensional and multi-dimensional arrays is slower than manually converting to 0-based indexing, then we can't really recommend these functions for doing so.

**Comment by GunnarFarneback** [comment]
Agreed about the purpose of `fld1/mod1`. If you mean using the current definitions for integers in all cases it looks like `mod1(x, y)` for negative `y` produces a result in the `[y+2, 1]` range and `fld1(x, y) = 1 - fld1(x - 1, -y)` for negative `y`. This doesn't seem very attractive to document. Can we just say that they are undefined, or give a domain error or something, instead?

**Comment by GunnarFarneback** [comment]
A note on speed: The two competing definitions of `mod1`
```
(m = mod(x, y); ifelse(m == 0, y, m))  # Real
mod(x + y - T(1), y) + T(1)            # Integer
```
seem to have the same speed, or possibly slightly faster for the former. Taking into account that the latter can overflow for large `x` and `y` (e.g. `mod1(Int8(127), Int8(3))` gives incorrect result), as well as having slightly less attractive behavior for negative `y`, the former definition is a clear winner, at least in isolation.

For `fld1` the story is different. There we have three contenders:
```
m = mod(x, y); fld(x - m, y)       # Current definition for Real
fld(x + y - T(1), y)               # Current definition for Integer
m = mod1(x, y); fld(x + y - m, y)  # Definition in this PR
```
The first one doesn't give correct results even for positive integers, so it is not an option. The second one seems to be about twice as fast as the third and those are both similarly sensitive to overflow.

**Comment by GunnarFarneback** [comment]
I'm starting to believe that speed is a red herring. All the `mod` and `fld` variants boil down to calls to the `rem` or `div` intrinsics, with necessary corrections for signs and offsets, and the majority of the time is spent in the intrinsics. Moreover, the implementation of `fld` for signed integers,
```
function fld(x::T, y::T) where T<:Integer
    d = div(x, y)
    return d - (signbit(x ⊻ y) & (d * y != x))
end
```
can with a minor tweak be adapted to compute an `fld1` as
```
function fld1(x::T, y::T) where T<:Integer
    d = div(x, y)
    return d + (!signbit(x ⊻ y) & (d * y != x))
end
```
Admittedly I'm benchmarking this as a few percent slower than `fld(x + y - T(1), y)`, and I really don't know why, but I think this would be worth getting a sensible behavior for negative `y` (i.e. matching the current documentation and the tests in this PR) as well as avoiding overflow issues.

**Comment by GunnarFarneback** [comment]
I added the integer specialization of `fld1` from the previous comment and extended the testing with values near typemin and typemax, as well as some non-integers for floats and rationals.

**Comment by StefanKarpinski** [comment]
Win32 failure is the usual. CircleCI seems to be consistently failing these days.

**Pull request merged**
