### PR TITLE
[`master` branch] CI (Buildkite): remove the `.buildkite` folder

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request was automatically generated using the following script:

```
declare -a arr=("master" "release-1.6" "release-1.7" "release-1.8")
for BASE_BRANCH in "${arr[@]}"
do
    echo "BASE_BRANCH: ${BASE_BRANCH:?}"
    cd $(mktemp -d)
    git clone git@github.com:JuliaLang/julia.git
    cd julia
    git checkout ${BASE_BRANCH:?}
    git checkout -B dpa/remove-buildkite-folder-${BASE_BRANCH:?}
    rm -rf .buildkite
    rm -rf .buildkite-external-version
    echo "main" > .buildkite-external-version
    git add -A
    git commit -m "[\`${BASE_BRANCH:?}\` branch] CI (Buildkite): remove the \`.buildkite\` folder"
    git push -f origin dpa/remove-buildkite-folder-${BASE_BRANCH:?}
    cd ..
done
```

### CODE REVIEW

**Comment by aviatesk** [comment]
I think we also want to:
- remove `CODEOWNER` stuff
- migrate issues
?

**Comment by giordano** [comment]
I thought that having the CI setup in this repository was one of the requirements set out by #37341, am I missing something?

**Comment by staticfloat** [comment]
Our new plan is to have essentially "git submodules", where the traffic of development is hidden from the main repository, but we're still tying the main repository and the CI configuration together via source control.

**Comment by aviatesk** [comment]
I'm not sure this is discussed already somewhere, but I wonder if there is any parts in `.buildkite` where it hardcodes references to something unsolidified about `julia` repository. E.g. I remember that a part of `.buildkite` one day listed up file names in `base/compiler` (, which I'm not sure if it holds true these days). And this kind of hardcoding will require us to work on two different PRs in parallel so that changes made for `julia` repository are updated with buildkite.

**Comment by DilumAluthge** [comment]
We'll have a file named `buildkite.version` in the `JuliaLang/julia` repository. Normally, the contents of that file will look something like this:

```
$ cat buildkite.version
buildkite-1.6
```

This would basically say that the `release-1.6` branch of the `JuliaLang/julia` repository is tracking the `buildkite-1.6` branch of the `JuliaCI/julia-buildkite` repository.

However, if we need to pin to a specific commit, we can do that instead.

```
$ cat buildkite.version
full_commit_hash
```


This would basically say that the `release-1.6` branch of the `JuliaLang/julia` repository is pinned to the `full_commit_hash` commit in the `JuliaCI/julia-buildkite` repository.

**Comment by DilumAluthge** [comment]
@staticfloat We'll need to edit the web UI for the `julia-master` pipeline so that it has the correct contents. Once that is done, I'll rebase this PR, and then it will be good to go.

**Comment by staticfloat** [comment]
Done

**Comment by DilumAluthge** [comment]
@staticfloat @brenhinkeller See the Buildkite failure.

**Comment by DilumAluthge** [comment]
Did I give the wrong name for the file containing the branch or commit? I named it `buildkite.version`. If this is not correct, let me know, and I'll update the PR with the correct name.

**Comment by staticfloat** [comment]
It should be called `.buildkite-external-version`

**Comment by DilumAluthge** [comment]
Hmmmm. I've fixed the file name, but I'm still seeing an error.

**Comment by DilumAluthge** [comment]
```
fatal: ambiguous argument '.buildkite-external-version': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
🚨 Error: The plugin external-buildkite post-checkout hook exited with status 128
```

**Comment by DilumAluthge** [comment]
```
Check that the working directory is clean
ERROR: The working directory is dirty.
Output of git status:
HEAD detached at b7261dd8061
Untracked files:
  (use "git add <file>..." to include in what will be committed)
 
	.buildkite/
 
nothing added to commit but untracked files present (use "git add" to track)
🚨 Error: The command exited with status 1
```

**Comment by DilumAluthge** [comment]
@staticfloat I'm going to edit the `.gitignore` file for this repository (the `JuliaLang/julia` repostory) to add the following line:

```
.buildkite/
```

Does that sound reasonable to you?

**Comment by DilumAluthge** [comment]
🥷

**Review by staticfloat — APPROVED** [review]
Let's do it!

**Pull request merged**
