### PR TITLE
fix #30653, call `malloc_trim` sometimes

### LINKED ISSUE #30653: Memory leak with function redefinition
This code takes less than a minute to fill the 64GB of my Linux machine:

```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

julia> for i in 1:100
           @eval function foo()
               [fill(1.0, 2_000_000) for _ in 1:100]
               nothing
           end
           @time @eval foo()
           # GC.gc()   # uncomment this line to fix the issue
       end
```

EDIT: simplified code

### PR DESCRIPTION
**Pull request by JeffBezanson**
This works around what seems to be a glibc bug. Fixes #30653 

@cstjean See if this fixes your original case.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/32428#issuecomment-506204434) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/3caa3b3769f45aa0628223f091eab4f365bf98ff/5e6eaff_vs_fa766bc/report.md). cc @ararslan

**Comment by ViralBShah** [comment]
If this is an issue on only certain versions of glibc, is it worthwhile to apply this fix only if the user is using a glibc version that's bad?

**Comment by JeffBezanson** [comment]
I don't think so; with this change we'll only call malloc_trim if there's significant heap growth so it shouldn't take much time. And I don't want to bother tracking down which versions are affected.

**Comment by cstjean** [comment]
I'm seeing some fairly large `trim` difference for my code. I create temporaries which grow usage to 11GB. Then GC brings me down to ~4GB. Then explicitly calling `malloc_trim` gets me another 2GB.

```julia
julia> memory_usage() / 1.e9
4.618551296

julia> GC.gc()

julia> memory_usage() / 1.e9
4.61774848

julia> malloc_trim()  # the ccall
1

julia> memory_usage() / 1.e9
2.462871552
```

I guess that's to be expected given this PR? It's not a problem for us at the moment. I assume that it will be trimmed automatically eventually...

**Pull request merged**
