### PR TITLE
Fixes max, min and minmax when comparing zeros with different signs

### PR DESCRIPTION
**Pull request by lbenet**
This fix assures that `max(-0.0,0.0) === max(0.0,-0.0)`, and similarly for the other functions. This fix follows the same ideas of #8968

### CODE REVIEW

**Comment by lbenet** [comment]
@StefanKarpinski Sorry, I just noticed that a stupid trailing empty space was causing that the tests were not passing. Travis' tests passed, but AppVeyor didn't; I think the problem is unrelated.

**Comment by StefanKarpinski** [comment]
Thanks for the fix and for sticking with it, @lbenet.

**Comment by ViralBShah** [comment]
It would have been nice to squash the commits. Nice fix in any case @lbenet

**Comment by StefanKarpinski** [comment]
Yeah, sorry about that. I didn't notice the messy history until after merging at which point it was too late.

**Comment by lbenet** [comment]
Sorry about the messy history. Next time I'll be cleaner :-)

**Pull request merged**
