### PR TITLE
[backports-release-1.11] 1.11 Profiling threading fix backports

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/julia/issues/56327

- https://github.com/JuliaLang/julia/pull/55622
- https://github.com/JuliaLang/julia/pull/55704

~Needs checking on a linux machine with more than one thread.~ Confirmed fix. https://github.com/JuliaLang/julia/pull/56358#issuecomment-2440273110

### CODE REVIEW

**Comment by gdalle** [comment]
What should the tests look like? The profiling result is not exactly empty, it does have a few (trivial) things in the flame graph, so what would be a good criterion for a test that would fail in the current state of things?

**Comment by IanButterworth** [comment]
I'm guessing that if you start with -t8 and do `Profile.print(groupby=:thread)` on 1.11.1 you only get 1 thread, but here you get all threads?

**Comment by IanButterworth** [comment]
I checked on a linux x86 machine with `-t8` and it does appear fixed here.

On 1.11.1 only the first thread appears to be sampled.
```
$ julia +1.11 -t8
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> function profile_test(n)
                  for i = 1:n
                      A = randn(100,100,20)
                      m = maximum(A)
                      Am = mapslices(sum, A; dims=2)
                      B = A[:,:,5]
                      Bsort = mapslices(sort, B; dims=1)
                      b = rand(100)
                      C = B.*b
                  end
              end
profile_test (generic function with 1 method)

julia> using Profile

julia> @profile profile_test(2)

julia> Profile.clear(); @profile profile_test(1000)

julia> Profile.print(groupby=:thread)
Overhead ╎ [+additional indent] Count File:Line; Function
=========================================================
Thread 1 Total snapshots: 781. Utilization: 100%
   ╎781 @Base/client.jl:541; _start()
   ╎ 781 @Base/client.jl:567; repl_main
   ╎  781 @Base/client.jl:430; run_main_repl(interactive::Bool, quiet::Bool, banner::Symbol, history_file::Bool, color_set::Bool)
... etc.

┌ Warning: There were no samples collected in one or more groups.
│ This may be due to idle threads, or you may need to run your
│ program longer (perhaps by running it multiple times),
│ or adjust the delay between samples with `Profile.init()`.
└ @ Profile ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/Profile/src/Profile.jl:1240
```

On this PR all are sampled.
```
$ ./julia --start=no -t8
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-27)
 _/ |\__'_|_|_|\__'_|  |  ib/1.11_profile_backports/0495045cc1* (fork: 487 commits, 254 days)
|__/                   |

...

julia> Profile.print(groupby=:thread)
Overhead ╎ [+additional indent] Count File:Line; Function
=========================================================
Thread 1 Total snapshots: 582. Utilization: 100%
   ╎582 @Base/client.jl:541; _start()
   ╎ 582 @Base/client.jl:567; repl_main
   ╎  582 @Base/client.jl:430; run_main_repl(interactive::Bool, quiet::Bool, banner::Symbol, history_file::Bool, color_set::Bool)
... etc.

Thread 2 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 3 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 4 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 5 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 6 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 7 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 8 Total snapshots: 582. Utilization: 0%
   ╎582 @Base/task.jl:694; task_done_hook(t::Task)
   ╎ 582 @Base/task.jl:1021; wait()
581╎  582 @Base/task.jl:1012; poptask(W::Base.IntrusiveLinkedListSynchronized{Task})

Thread 9 Total snapshots: 582. Utilization: 100%

Thread 10 Total snapshots: 582. Utilization: 100%

Thread 11 Total snapshots: 582. Utilization: 100%

┌ Warning: There were no samples collected in one or more groups.
│ This may be due to idle threads, or you may need to run your
│ program longer (perhaps by running it multiple times),
│ or adjust the delay between samples with `Profile.init()`.
└ @ Profile ~/Documents/GitHub/julia/usr/share/julia/stdlib/v1.11/Profile/src/Profile.jl:1240

```

**Comment by vtjnash** [comment]
SGTM

**Pull request merged**
