### PR TITLE
deprecate `iseltype`

### PR DESCRIPTION
**Pull request by JeffBezanson**
This function seems pretty useless.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
How did that even get introduced?

**Comment by pao** [comment]
Formerly known as `isela()`. Renamed as part of a mass rename in https://github.com/JuliaLang/julia/commit/9db107148bd85502253ca2868a6fadf9ac716e39. `isela()` introduced in its parent, https://github.com/JuliaLang/julia/commit/ba4df47fe17e9c2f12454d3b91bfe4d3fdf83de0 as part of an abstraction of a bunch of `is` functions. cc @simonbyrne

**Comment by pao** [comment]
(That CC was probably not needed, I did just see that this was introduced That Long Ago. Probably made perfect sense at the time.)

**Comment by StefanKarpinski** [comment]
Interesting. The original version for arrays was less trivial, but that had already been excised.

**Comment by simonbyrne** [comment]
I guess I wrote this before I knew about the <: operator. +1

**Comment by pao** [comment]
Did this get done elsewhere?

**Comment by Keno** [comment]
https://github.com/JuliaLang/julia/commit/94d35891b7d93503ae8a94b622451acf90f787ab

**Comment by pao** [comment]
Thanks.

**Comment by tkelman** [comment]
looks like it may have been a tiny conflict at the end of `deprecated.jl`, CI was green here so manual conflict-fix and push to master makes perfect sense

**Comment by pao** [comment]
Wasn't worried about it, just like to see resolutions stated explicitly.

**Pull request closed without merging**
