### PR TITLE
Update types.rst

### PR DESCRIPTION
**Pull request by gdevanla**
Fix a minor typo

### CODE REVIEW

**Comment by jakebolewski** [comment]
Thanks!

**Comment by tkelman** [comment]
According to the section below, I think this is incorrect, the behavior of get with a default matches what was originally stated - the default value is returned when the firat input is null.

**Comment by johnmyleswhite** [comment]
This is the opposite of what we do.

**Comment by jakebolewski** [comment]
I think this can be worded differently to make it clearer.  Reading it quickly isolation kind of conflates (in my mind) a `Nullable` returning type T when the value is `!== nothing`.

**Comment by johnmyleswhite** [comment]
If that's confusing, I would use the phrase "null value" instead of "missing value".

**Comment by jakebolewski** [comment]
I think that would be better.

**Pull request merged**
