### PR TITLE
"All Objects" exception isless for complex numbers

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by fredrikekre** [comment]
What are you trying to accomplish here?

**Comment by PallHaraldsson** [comment]
Just have it documented that generic isn't absolute, maybe some beginners will not know about non-total order of complex numbers.

Also:

I get (assuming since I'm on 0.5):
```
julia> Nullable(1.0) < Nullable(2.0)
ERROR: MethodError: no method matching isless(::Nullable{Float64}, ::Nullable{Float64})
 in <(::Nullable{Float64}, ::Nullable{Float64}) at ./operators.jl:63
```

assuming it will work, hopefully also (not clear from the docs):
```
julia> Nullable(1.0) < 2.0
ERROR: MethodError: no method matching isless(::Nullable{Float64}, ::Float64)
Closest candidates are:
  isless(::Float64, ::Float64) at float.jl:283
  isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
  isless(::Real, ::AbstractFloat) at operators.jl:41
  ...
 in <(::Nullable{Float64}, ::Float64) at ./operators.jl:63
```

**Comment by KristofferC** [comment]
This is not the place to put these kinds of notes.

Anyway, did you render this locally and see that the generated HTML looks good?

**Comment by PallHaraldsson** [comment]
"Anyway, did you render this locally and see that the generated HTML looks good?"

No sorry.. you mean I broke the HTML? I just see it at:
https://github.com/PallHaraldsson/julia/blob/5791dad6b0bee9ecc69f449d22469b9bfe1fee4c/doc/src/stdlib/base.md

Feel free to close this, and/or tell me where/if this applies.

**Comment by KristofferC** [comment]
That is not the generated HTML. Please read https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation if you want to contribute to the documentation.

**Comment by PallHaraldsson** [comment]
I'm sorry if I broke `make docs`

This just looked like a text file.. and I'm new to the Docs and Markdown, so I'm guessing [skip ci] didn't apply as this is really source code. If this was actually a comment then no harm..:

https://stackoverflow.com/questions/4823468/comments-in-markdown

I thought this was a correct place to put this, maybe this is too much trivia to put anywhere.

**Comment by KristofferC** [comment]
Also, [CI skip] need to be in the commit message.

**Pull request closed without merging**
