### PR TITLE
Align worker output after prefix "From worker"

### PR DESCRIPTION
**Pull request by GregPlowman**
Alignment of output from workers is orderly for worker ids up to 99. For worker ids >100, the output line is positioned at the next tab stop (misaligned). The current behavior seems to be a function of the length of the text "From worker" in combination with the length of the worker id.  

Proposed change is to replace hard tab "\t" with 6 spaces. This is the simplest change I can think of without resorting to `@printf` or similar, but would like to hear other suggestions.

This code below simulates the change in worker output. 

```
f1(ident, line) = println("\tFrom worker $(ident):\t$line")
f2(ident, line) = println("      From worker $(ident):\t$line")
```
```
for ident in (1,10,100,1000)
    f1(ident, "This is worker $ident")
end
        From worker 1:  This is worker 1
        From worker 10: This is worker 10
        From worker 100:        This is worker 100
        From worker 1000:       This is worker 1000
```

```
for ident in (1,10,100,1000)
    f2(ident, "This is worker $ident")
end
      From worker 1:    This is worker 1
      From worker 10:   This is worker 10
      From worker 100:  This is worker 100
      From worker 1000: This is worker 1000
```

### CODE REVIEW

**Review by amitmurthy — APPROVED** [review]
LGTM

**Comment by fredrikekre** [comment]
Some places that needs updating too:
https://github.com/JuliaLang/julia/blob/682717024f0aecc70e521efc212cf1f815ee9708/examples/clustermanager/0mq/ZMQCM.jl#L278
https://github.com/JuliaLang/julia/blob/682717024f0aecc70e521efc212cf1f815ee9708/examples/clustermanager/simple/UnixDomainCM.jl#L86
https://github.com/JuliaLang/julia/blob/682717024f0aecc70e521efc212cf1f815ee9708/test/runtests.jl#L122
But most importantly:
https://github.com/JuliaLang/julia/blob/682717024f0aecc70e521efc212cf1f815ee9708/examples/embedding/embedding-test.jl#L27
which is the reason for the test failures.

**Comment by GregPlowman** [comment]
Thanks Fredrik!
I've updated the other files.

But now there's a conflict in `test/runtests.jl`
I don't know how to fix this. Can I just edit my branch to match changes since it was last synced?

**Comment by KristofferC** [comment]
You can either get the latest master and then run `git rebase master` on this branch and fix up the merge conflict you will get. Or you can fix it online by clicking the button "Resolve conflicts" and fix it up to look good.

**Comment by GregPlowman** [comment]
Thanks Kristoffer.
Files updated and conflict resolved.

**Comment by fredrikekre** [comment]
Unrelated failures.

**Pull request merged**
