### PR TITLE
adjust addr from COFFObjectFile

### PR DESCRIPTION
**Pull request by vchuravy**
LLVM 3.9 changed the definition of `getSectionAddress` and `getSymbolAddress` for `llvm::object::COFFObjectFile` to return `Addr + BaseAddr` (see https://github.com/llvm-mirror/llvm/blob/de903c28a709dcbb24f2ac06f606024060efc0c8/lib/Object/COFFObjectFile.cpp#L273). So we have to subtract the `BaseAddr` in order to correctly calculate the symbol size.

`COFFObjectFile` get's automatically selected according to the file system (see https://github.com/llvm-mirror/llvm/blob/c018e3b3038be0ecf72417c1f3788d7db643b221/lib/Object/ObjectFile.cpp#L74) and I was originally thinking of changing it to `ELFObjectFile`, but that turned out to be more involved.

cc: @vtjnash for review.
cc: @tkelman this fixes the last test failure I am observing for Win64 && LLVM 3.9

### CODE REVIEW

**Comment by vtjnash** [comment]
Would we get the same effect by removing the slide offset calculation from debuginfo.cpp?

If not, this should at least first check if the type is coff (rather than using macro conditionals), since this code path is filetype-specific, not os-conditional.

**Comment by vchuravy** [comment]
Addressed review comments, adjusted LLVM bounds to include 3.8, rebased and tested under Win64 LLVM 3.8.0 and 3.9.0.

**Comment by StefanKarpinski** [comment]
@vtjnash – bump

**Comment by vchuravy** [comment]
@vtjnash I haven't manage to check your suggestion to adjust the offset outside the function. If I find a minute tonight or tomorrow evening I will give it a go.

**Pull request closed without merging**
