### PR TITLE
give Pkg repl mode tips when interactive

### PR DESCRIPTION
**Pull request by IanButterworth**
Pkg counterpart https://github.com/JuliaLang/Pkg.jl/pull/3854

### CODE REVIEW

**Review by Keno — APPROVED** [review]

**Comment by Keno** [comment]
That said, I think we may want a hint for when somebody literally types the string "pkg>" into the julia repl to tell them how to enter the pkg prompt.

**Comment by IanButterworth** [comment]
Makes sense. Issue opened here https://github.com/JuliaLang/JuliaSyntax.jl/issues/427

**Comment by Keno** [comment]
I don't think it needs to be in the parser. I think the repl frontend can literally just do a strcmp since it's repl specific

**Comment by IanButterworth** [comment]
Ok. I did have an attempt here https://github.com/JuliaLang/julia/pull/53829 but it doesn't work yet.

**Comment by KristofferC** [comment]
FWIW, I personally like the "API versions" more, it won't be obvious for everyone they can copy paste the `pkg>` output. However, for suggestions in errors that originate from a Pkg command we can chose the version based on if the Pkg command was done using the REPL or API mode.

**Pull request closed without merging**
