### PR TITLE
temp work-around for 32-bit inference failure (#29923)

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by KristofferC** [comment]
`@test_broken`?

**Comment by KlausC** [comment]
Shouldn't `if Sys.WORD_SIZE == 64 || S === Int128` be `if !(Sys.WORD_SIZE == 64 || S === Int128)` ?

**Comment by StefanKarpinski** [comment]
Yes, it should. I had the logic inverted previously and only half fixed it!

**Comment by KristofferC** [comment]
> Possibly but it's been a week with all 32-bit CI failing, which is not acceptable. 

Agreed, this is probably for the best to not waste everyones time looking at CI logs.

**Comment by JeffBezanson** [comment]
I agree we should temporarily disable this. We don't know how to fix this. It has come up before and we've never fully figured it out, so there's no estimate of how long it will take to fix.

**Comment by martinholters** [comment]
Alternatively, we keep the test and do 
```diff
--- a/base/int.jl
+++ b/base/int.jl
@@ -775,7 +775,7 @@ if Core.sizeof(Int) == 4
         return Int128(rem(BigInt(x), BigInt(y)))
     end
     function rem(x::UInt128, y::UInt128)
-        return UInt128(rem(BigInt(x), BigInt(y)))
+        return UInt128(rem(BigInt(x), BigInt(y)))::UInt128
     end
 
     function mod(x::Int128, y::Int128)
```
Here, I'd like to point out that (on 32bit systems), we have two definitions in `int.jl` which for operations on `UInt128` go via `BigInt`:
https://github.com/JuliaLang/julia/blob/e209c3d0e90d9b5c8c9cb9abe01443677c998050/base/int.jl#L770-L772
https://github.com/JuliaLang/julia/blob/e209c3d0e90d9b5c8c9cb9abe01443677c998050/base/int.jl#L777-L779
So by adding the type assertion to the second one, too, we then have covered "all" of them. Therefore, one may hope for these test failures not to show up again. It is still more of a work-around than a fix, though.

**Comment by martinholters** [comment]
Even though I'm experimenting with an alternative over in #30050, I'm in favour of merging this ASAP to get CI back up and then investigate further.

**Comment by fredrikekre** [comment]
Unrelated (?) Profile test failure on AV 32-bit.

**Comment by musm** [comment]
all green 👍

**Pull request merged**
