### PR TITLE
More SubArray tests

### PR DESCRIPTION
**Pull request by kshyatt**
Following @andreasnoack, I tried widening the tests to use `SubArrays` as well.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Great. Thanks for continuing this.

(I think there is a white space issue in the PR.)

**Comment by kshyatt** [comment]
Hopefully that fixed the whitespace

**Comment by vtjnash** [comment]
i hope you don't mind that I rebased on master & pushed to restart CI. I think the appveyor tests should pass now.

**Comment by kshyatt** [comment]
Thanks! *fingers crossed*

**Comment by tkelman** [comment]
That wasn't necessary, they did pass in https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.13330

**Comment by timholy** [comment]
LGTM. Nice that these pass with so few changes to `base/`.

**Comment by kshyatt** [comment]
Tests have passed and it's been a day sans complaints - I am going to merge :)

**Pull request merged**
