### PR TITLE
[LLVM] upgrade to LLVM 11

### PR DESCRIPTION
**Pull request by vchuravy**
Based on LLVM 11-rc5. Still some patch maintenance to do.

TODO:
- [x] D75072

### CODE REVIEW

**Comment by vchuravy** [comment]
@keno & @vtjnash The x86 Linux failure is peculiar:

What I observed is that we want to perfom a ccall to `jl_alloc_array_1d`, but instead jump into the middle off `jl_alloc_array_3d`.
Dumping the LLVM module IR shows that we embed the correct pointer. Running with `--debug=dyld` and dissasembling the object file before and after relocations. Shows that we changed from the correct address to a wrongly offset address. 

As an example: The emitted `e815028ef7` changes to `e8b1d9590c`. `ntoh(0x15028ef7) == 0xf78e0215` which is the location we want and IIUC opcode `e8` correctly `0xeb342994 + ntoh(0xb1d9590c) == 0xf78e0345`, which is consistent with us jumping past `jl_alloc_array_1d` and landing in the middle of `jl_alloc_array_3d`.

Looking at RuntimeDyld: (different binary so address are different)

```
=> 0xeae8698f <+271>:   call   0xf7724335 <jl_alloc_array_3d+106> 
b RuntimeDyldELF.cpp:935 if RE.Offset == 272

resolveRelocation -> Addend: 0xf7724331

(rr) p/x &(RE.Addend)
(rr) w *0x5916a704
(rr) rc
> addRelocationForSymbol
> RECopy.Addend += SymInfo.getOffset();

b processRelocationRef
(rr) rc
in processRelocationRef: L1210

Value.SymbolName == ""
Value.Addend == 0
Offset == 272

in processRelocationRef: L1772
Value.Addend == 0xf7724205


(rr) disas jl_alloc_array_1d                                                                   
Dump of assembler code for function jl_alloc_array_1d:
   0xf7724209 <+0>:     endbr32 
   0xf772420d <+4>:     push   %ebp
   0xf772420e <+5>:     mov    %esp,%ebp
```

1. `SymbolName` will be the empty string
  - As an absolute symbol  it can have 0x0, but https://github.com/llvm/llvm-project/blame/176249bd6732a8044d457092ed932768724a6f06/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L1199 fixes that to `""`. 
2. We will call `processSimpleRelocation` https://github.com/llvm/llvm-project/blame/176249bd6732a8044d457092ed932768724a6f06/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L990 and that only checks if `SymbolName` is `0x0`.
3.  `addRelocationForSymbol`  https://github.com/llvm/llvm-project/blob/176249bd6732a8044d457092ed932768724a6f06/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp#L936 comes in and will fudge the address.

The peculiar thing is that this behavior is positively old. @keno you touched  some of this code so maybe you have a in insight what the correct behaviour should be? Right now it is unclear to me what changed between LLVM 10 and LLVM 11.

Checking in https://github.com/llvm/llvm-project/blob/176249bd6732a8044d457092ed932768724a6f06/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp#L930 for `SymbolName.empty()` let's me compile Julia, but makes me wonder why the empty symbol is in the `GlobalSymbolTable`.

**Comment by vchuravy** [comment]
ready to land

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/37842#issuecomment-707359323):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`sudo cset shield -c 1,2,3,4 -k on`, ProcessExited(2)) [2]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e0344f5e5c3453807a4649fa190a3bd40ccceb99/by_hash/50c0429_vs_ebc63b9/report.md)
cc @christopher-dG

**Comment by christopher-dG** [comment]
Oops, forgot to restart the server after I merged my fix.

@nanosoldier runbenchmarks(ALL, vs = ":master")

**Comment by christopher-dG** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

oops

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/37842#issuecomment-707359612) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/e5580ad732b3ecb8f2c0819d9af77b1f106a7bf7/pkgeval/by_hash/9563180_vs_ebc63b9/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/37842#issuecomment-707399121) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/21d444a950a052db8f220a3050eac6c998c4cbfc/by_hash/3525155_vs_f9ee161/report.md). cc @christopher-dG

**Comment by KristofferC** [comment]
Looks like the commit doesn't exist.

**Comment by maleadt** [comment]
Probably https://github.com/JuliaCI/BaseBenchmarkReports/blob/21d444a950a052db8f220a3050eac6c998c4cbfc/benchmark/by_hash/3525155_vs_f9ee161/report.md -- there was a merge which confused Nanosoldier.jl.

**Comment by KristofferC** [comment]
```

["misc", "afoldl", "Int"] | 13.18 (5%) ❌ | 1.00 (1%)

["array", "index", "(\"sumcartesian_view\", \"BitMatrix\")"] | 2.18 (50%) ❌ | 1.00 (1%)


```

might be interesting

**Pull request merged**
