### PR TITLE
🤖 [master] Bump the LinearAlgebra stdlib from 56d561c to 1137b4c

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: LinearAlgebra
URL: https://github.com/JuliaLang/LinearAlgebra.jl.git
Stdlib branch: master
Julia branch: master
Old commit: 56d561c
New commit: 1137b4c
Julia version: 1.12.0-DEV
LinearAlgebra version: 1.11.0(Does not match)
Bump invoked by: @DilumAluthge
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaLang/LinearAlgebra.jl/compare/56d561c22e1ab8e0421160edbdd42f3f194ecfa8...1137b4c7fa8297cef17c4ae0982d7d89d4ab7dd8

```
$ git log --oneline 56d561c..1137b4c
1137b4c Port structured opnorm changes from main julia PR (#1138)
ade3654 port bitarray tests to LinearAlgebra.jl (#1148)
130b94a Fix documentation bug in QR docstring (#1145)
128518e setup coverage (#1144)
15f7e32 ci: add linux-i686 (#1142)
b6f87af Fallback `newindex` method with a `BandIndex` (#1143)
d1e267f bring back [l/r]mul! shortcuts for (kn)own triangular types (#1137)
5cdeb46 don't refer to internal variable names in gemv exceptions (#1141)
4a3dbf8 un-revert "Simplify some views of Adjoint matrices" (#1122)
7b34d81 [CI] Install DependaBot (#1115)
f567112 Port structured opnorm changes from main julia PR Originally written by mcognetta
d406524 implements a `rank(::SVD)` method and adds unit tests. fixes #1126 (#1127)
f13f940 faster implementation of rank(::QRPivoted) fixes #1128 (#1129)
8ab7e09 Merge pull request #1132 from JuliaLang/jishnub/qr_ldiv_R_cache
85919e6 Merge pull request #1108 from JuliaLang/jishnub/tri_muldiv_stride
195e678 Cache and reuse `R` in adjoint `QR` `ldiv!`
cd0da66 Update comments LAPACK -> BLAS
b3ec55f Fix argument name in stride
d3a9a3e Non-contiguous matrices in triangular mul and div
aecb714 Reduce number of test combinations in test/triangular.jl (#1123)
62e45d1 Update .github/dependabot.yml
ff78c38 use an explicit file extension when creating sysimage (#1119)
43b541e try use updated windows compilers in PackageCompiler (#1120)
c00cb77 [CI] Install DependaBot
b285b1c Update LICENSE (#1113)
7efc3ba remove REPL from custom sysimage (#1112)
b7f82ec add a README
```

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I'm not sure if things are ready to go over in the LinearAlgebra repo, so I'll convert this to draft for now, just to prevent accidentally clicking merge.

**Comment by ViralBShah** [comment]
I think it is ok to merge.

**Comment by inkydragon** [comment]
Ready to go?

**Comment by DilumAluthge** [comment]
@KristofferC Any objection to merging this PR?

**Pull request merged**
