### PR TITLE
Add at-doc support for bitstypes.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
cc: @one-more-minute

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
@one-more-minute currently we're storing the *value* of constants rather than their actual names. Was this intended behaviour? If we have two documented constants with the same value then we loose one.

```
julia> @doc "A" const A = 1
1

julia> @doc "B" const B = 1
1

julia> Main.META
ObjectIdDict with 2 entries:
  #= circular reference =# => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["Document…
  1                        => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["B"])],Di…
```

**Comment by MichaelHatherly** [comment]
The third commit stores constants by ``Symbol`` instead. Might be a little less surprising for users:

```
julia> @doc "A" const A = 1

julia> @doc "B" const B = 1

julia> Main.META
ObjectIdDict with 3 entries:
  :A                       => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["A"])],Di…
  #= circular reference =# => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["Document…
  :B                       => Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["B"])],Di…
```

**Comment by one-more-minute** [comment]
This looks good but let's go back on the third commit for now.

The doc system looks over all META entries for metadata, so this is going to mean that you can't document to things called `A` in different modules. It's definitely a nice idea but we need a more fine-grained approach (I have something in mind that I think will work well).

**Comment by MichaelHatherly** [comment]
Removed that third commit since it was making docstring lookup for constants troublesome.

**Comment by MichaelHatherly** [comment]
What good timing :)

**Comment by one-more-minute** [comment]
Ha, well I think that's the fastest response to feedback that I've ever had :) Thanks!

**Comment by MichaelHatherly** [comment]
> so this is going to mean that you can't document to things called ``A`` in different modules

Yeah, realised that shortly after pushing. Currently we have this though:

```
julia> module A

       @doc "A" const X = 1

       end

julia> module B

       @doc "B" const Y = 1

       end

help?> A.X
  A

help?> B.Y
  A
```

Probably even more confusing behaviour, but, yes, storing as a symbol wasn't much of an improvement.

**Pull request merged**
