### PR TITLE
Get rid of the tricks to avoid overflow in the AbstractUnitRange iterator

### LINKED ISSUE #26586: Improving iteration performance of ranges of small integer types
Julia currently supports iterating over the _full_ range of representable integers
````
for i = typemin(T):typemax(T) ... end
````
when `T` is a 'small' integer type `Union{Int8,UInt8,Int16,UInt16,Int32,UInt32}`. The overflow problem is solved by conversion to `Int`.

However, there is a very large overhead due to conversion of `Int` to `T` in each iteration. Take for example these two functions which imho should have the same performance:

```julia
function copy_via_iterator!(x::AbstractVector{T}, r::UnitRange{T}) where {T}
    @inbounds for (i_large, i_small) = enumerate(r)
        x[i_large] = i_small
    end
    x
end

function copy_via_loop!(x::AbstractVector{T}, r::UnitRange{T}) where {T}
    value = r.start
    @inbounds for i = 1 : length(r)
        x[i] = value
        value += T(1)
    end
    x
end
```

Benchmarks (iterator vs loop resp):
- Int8: 75ns vs 5.0ns with `r = Int8(-128) : Int8(127)`
- Int32: 8.2μs vs 3.1μs with `r = Int32(1) : Int32(50_000)`
- Int64: 8.8μs vs 8.8μs with `r = Int64(1) : Int64(50_000)`

One way to fix this problem is to keep track of two indices, one of type `Int` and one of type `T`. Something along the lines of:

```julia
import Base: start, next, done

struct MyUnitRange{T}
    start::T
    stop::T
end

const SmallIntT = Union{Int32, Int16, Int8} # and others...

struct SmallIntState{T<:SmallIntT}
    idx_small::T
    idx_large::Int
    stop::Int
end

# Int
start(r::MyUnitRange{T}) where {T} = r.start
next(r::MyUnitRange{T}, i) where {T} = i, i + one(T)
done(r::MyUnitRange{T}, i) where {T} = i == r.stop + one(T)

# Small integer types
function start(r::MyUnitRange{<:SmallIntT})
    SmallIntState(r.start, Int(r.start), Int(r.stop))
end

function next(r::MyUnitRange{T}, state::SmallIntState{T}) where {T} 
    state.idx_small, SmallIntState(state.idx_small + T(1), state.idx_large + 1, state.stop)
end

function done(r::MyUnitRange{T}, state::SmallIntState{T}) where {T} 
    state.idx_large == state.stop + 1
end
```

Same benchmarks with this implementation:
- Int8: 5.0ns :tada:
- Int32: 3.5μs :tada:

---

Finally I'm wondering why we don't treat Int32 the same way as Int64. Should all iterations with `UnitRange{Int32}` have this overhead cause we support the very exceptional case of iterating over the range `Int32(-2147483648):Int32(2147483647)`?

### PR DESCRIPTION
**Pull request by haampie**
Thanks to the new iterator protocol we can now iterate over a unit range in the number type of its elements, without having to worry about overflow :). Fixes #26586.

Previously iterating over say `typemin(Int8) : typemax(Int8)` was done by using an `Int` internally which was converted to an `Int8` each iteration. Now we can just iterate with `Int8`.

Something similar can probably be done for `StepRange`, but that would  be another pr.

### CODE REVIEW

**Comment by KristofferC** [comment]
Just to check, there are tests for e.g. iterating

```
typemin(Int8) : typemax(Int8)
```

?

**Comment by haampie** [comment]
Yes: https://github.com/JuliaLang/julia/blob/master/test/ranges.jl#L421-L426 :)

**Comment by haampie** [comment]
Test failures seem unrelated (libgit, distributed), ranges tests are green everywhere :)

**Comment by StefanKarpinski** [comment]
Who would be good to review this?

**Review by Keno — APPROVED** [review]
Yep, that's how this is supposed to work :)

**Comment by Keno** [comment]
Let's run nanosoldier though, since LLVM is sensitive to how ranges are lowered:
@nanosoldier runbenchmarks(ALL, vs = ":master")

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27147#issuecomment-390303012) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d972df7173a4416c9aaa7c821f70a5bcd328eb36/29cc0df_vs_b5c0cb0/report.md). cc @ararslan

**Pull request merged**
