### PR TITLE
gc-ext: only sweep unmarked objects

### PR DESCRIPTION
**Pull request by vtjnash**
This prior conditional was a fixed constant branch on `!(v | 1)`, which was always true, since the pointer is never tagged by gc, so this seems more like the intent?

@fingolfin @rbehrends from #28368

### CODE REVIEW

**Comment by chflood** [comment]
I'm not up on how foreign objects are treated, but in general not sweeping marked objects seems like a good idea.

**Comment by fingolfin** [comment]
I don't recall what the rationale for `gc_ptr_tag(v, 1)` was, and really @rbehrends wrote most of that code; but your analysis sounds right, and I definitely agree that we don't want to sweep marked objects. In fact sweeping marked objects likely would lead to crashes... But right now objects that may need sweeping are rarely if ever used in our code which would explain why we didn't notice such crashes.

**Comment by rbehrends** [comment]
The change looks correct to me, too, yes. The reason why we probably didn't see crashes in GAP is that the only place where this may actually be used is the HPC-GAP code and some weak pointer code in the baseline GAP GC, neither of which is enabled in the Julia integration.

**Comment by fingolfin** [comment]
It is also used by the Semigroups package these days, but again we don't use that by default.

**Pull request merged**
