### PR TITLE
Prevent download on windows picking up rogue curl executable

### PR DESCRIPTION
**Pull request by musm**
Checking if this is the cause of recent failures on buildbots

### CODE REVIEW

**Comment by musm** [comment]
Looks like this fixes things although I wonder where it's finding that extra curl executable from

**Review by vtjnash — APPROVED** [review]
(of the first commit, anyhow)

**Comment by musm** [comment]
I see what's happening:  The download function ends up picking up `C:\\cygwin\\bin\\curl.exe` 
and for some reason this is leading to the weird escaping?

**Comment by musm** [comment]
I think cygwin needs to be updated on the build bots.  

Testing locally, the curl version provided by cygwin works fine

**Pull request merged**
