### PR TITLE
Reenable test of condition number estimates of sparse matrices

### LINKED ISSUE #301: cond (and normestinv) return not consistent values
Sorry for the bad phrasing of the title.
The following reproduces a test case at line 1102 test/sparsedir/sparse.jl, which fails with PR JuliaLang/julia#14772:

```
julia> srand(5)
       Ac = sprandn(20,20,.5) + im* sprandn(20, 20,.5)
       cond(Ac,1) - cond(full(Ac),1)
30.262691632830524

julia> length(Set([Base.SparseArrays.normestinv(Ac) for x in 1:50]))
3
```

### LINKED ISSUE #14778: cond (and normestinv) return not consistent values
Sorry for the bad phrasing of the title.
The following reproduces a test case at line 1102 test/sparsedir/sparse.jl, which fails with PR #14772:
```
julia> srand(5)
       Ac = sprandn(20,20,.5) + im* sprandn(20, 20,.5)
       cond(Ac,1) - cond(full(Ac),1)
30.262691632830524

julia> length(Set([Base.SparseArrays.normestinv(Ac) for x in 1:50]))
3
```

### PR DESCRIPTION
**Pull request by andreasnoack**
and adjust the tolerance. Fixes JuliaLang/LinearAlgebra.jl#301

### CODE REVIEW

**Comment by jiahao** [comment]
:+1:

**Comment by tkelman** [comment]
if these are scalars, why the backslash?

**Comment by andreasnoack** [comment]
Because the denominator is to the left.

**Comment by tkelman** [comment]
reads kinda funny and backwards that way when things are scalars

**Comment by StefanKarpinski** [comment]
Left and right division are different even for scalars when multiplication is not commutative.

**Comment by tkelman** [comment]
Good point, though that's not the case here?

**Pull request merged**
