### PR TITLE
Alternative to writing our own FMA to deal with old glibc

### PR DESCRIPTION
**Pull request by simonbyrne**
See discussion in #26434.

### CODE REVIEW

**Comment by ViralBShah** [comment]
cc @oscardssmith

**Comment by oscardssmith** [comment]
since I've already seen libm implementations that just return the wrong results, and we already have pretty good fma emulation in Base (as of 23 hours ago), I don't see a benefit to this.

**Comment by ViralBShah** [comment]
@simonbyrne since we have an implementation that is passing everywhere (well everywhere except some win64s), should we close this?

**Comment by simonbyrne** [comment]
Yes, I didn't @oscardssmith had already done it. Yes, that makes way more sense.

**Pull request closed without merging**
