### PR TITLE
Variable size field descriptors for 0.4

### PR DESCRIPTION
**Pull request by yuyichao**
This is the rebase of https://github.com/JuliaLang/julia/pull/13147 on 0.4. There are conflicts with the codegen rewrite so I decided to open a new PR against 0.4.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
What's with the build failures around `libccalltest`? Then on 64-bit appveyor there's a worrying crash.

**Comment by yuyichao** [comment]
I'll check this evening but I think none of the two AppVeyor failures are new....

**Comment by yuyichao** [comment]
Did anyone restart the build? I didn't see any `libccalltest` failures on either travis or appveyor. I've restarted the AppVeyor (also rebased the one for master to trigger a rebuild) to see if the error appears again.

**Comment by JeffBezanson** [comment]
Yes, I don't think it's related to this but it seems to have happened a couple times. Wondering if anyone has any insights.

**Comment by yuyichao** [comment]
Hmm seems that it is reproducable on this branch? @tkelman Can you reproduce it locally (i.e. attach gdb on it)? I can try to compile it on my virtual machine but it is going to take a long time.

**Comment by tkelman** [comment]
[posted in wrong issue originally, sorry, I was building on this branch]

Had trouble reproducing locally. This reminds me though that I should adjust appveyor on release-0.4 to download the release-0.4 binaries instead of nightlies. I think that should only matter for deps though.

**Comment by yuyichao** [comment]
Ahh. So the Segfault (which is the one I have seen a few time before and would like to reliably reproduce) only appears in the first AppVeyor run. The `libccalltest` libdl test is reliably failing though. Not sure what is causing it (might it have sth to do with the recent change of where/how the ccall test library is compiled/installed?)

**Comment by tkelman** [comment]
> might it have sth to do with the recent change of where/how the ccall test library is compiled/installed?

Yeah it might, since the backport of that change isn't merged yet. I just pushed a change here to use 0.4-latest binaries instead of nightly on appveyor, let's see if that makes a difference.

**Comment by yuyichao** [comment]
@vtjnash 's trick for saving 32bits in the type structure is also backported on this branch now.

**Comment by yuyichao** [comment]
I was actually expecting #13147 to be merged first to test it more on the master branch first ;-p....

**Pull request merged**
