### PR TITLE
Fix @time and @timev

### PR DESCRIPTION
**Pull request by yuyichao**
Before (notice the "0 allocations" and negative "allocated" along with mulitple allocation counts that does not agree..),

``` julia
julia> type B
       a::NTuple{1000, Int64}
       B() = new()
       end

julia> f() = @timev (B(); gc())
f (generic function with 1 method)

julia> f()
  25.287 milliseconds (0 allocations: 8032 bytes, 99.99% gc time)
elapsed time:    25286704 nanoseconds
gc time:         25283689
bytes allocated: 8032
allocated:       -19411315
total allocated: 19419347
pause:           2
full sweep:      1
```

After,

``` julia
julia> type B
       a::NTuple{1000, Int64}
       B() = new()
       end

julia> f() = @timev (B(); gc())
f (generic function with 1 method)

julia> f()
  23.669 milliseconds (1 allocation: 8032 bytes, 99.99% gc time)
elapsed time (ns): 23669243
gc time (ns):      23666560
bytes allocated:   8032
non-pool GC allocs:1
GC pauses:         1
full collections:  1
```

### CODE REVIEW

**Comment by yuyichao** [comment]
Just noticed that more things are broken for the `@time` and `@timev` macros.... Fixing now....

**Comment by dpsanders** [comment]
Maybe rename timev to time_verbose?

**Comment by ScottPJones** [comment]
Nice fixes, this was my first foray into the GC code, sorry I left any bugs!

**Comment by yuyichao** [comment]
@dpsanders This PR is just to fix the broken logic so I don't want to rename it in this PR.

I also don't think `@timev` is a bad enough name for the (minor) breakage caused by the renaming either.

**Pull request merged**
