### PR TITLE
Use IndexStyle in `diagind` to optionally return a range of `CartesianIndex`es

### PR DESCRIPTION
**Pull request by jishnub**
This change was the main motivation behind #50457. After this, `diagind` may return a `StepRangeLen` of `CartesianIndex`es if the array uses Cartesian indexing. This may speed up indexing operations, as there is no linear to Cartesian conversion necessary. The PR might be mildly breaking if someone is explicitly expecting integers, but `diagind` is not documented to necessarily return a range of integers.

With this,
```julia
julia> D = Diagonal(1:4);

julia> diagind(D)
StepRangeLen(CartesianIndex(1, 1), CartesianIndex(1, 1), 4)
```
Performance comparison:
```julia
julia> D = Diagonal(1:20);

julia> @btime $D[diagind($D)];
  128.395 ns (2 allocations: 224 bytes) # master
  71.083 ns (2 allocations: 224 bytes) # PR

julia> @btime mul!($(Diagonal(zeros(40))), 2.0, I);
  116.291 ns (0 allocations: 0 bytes) # master
  38.149 ns (0 allocations: 0 bytes) # PR
```

Example where the performance might become worse:
```julia
julia> D = Diagonal(1:20); M = Matrix(D);

julia> @btime $M[diagind($D)];
  59.699 ns (2 allocations: 224 bytes) # master
  73.517 ns (2 allocations: 224 bytes) # PR
```
In such cases, the performance hit should not be severe, as Cartesian to linear conversions are faster than the other way.

### CODE REVIEW

**Review by dkarrasch — APPROVED** [review]
LGTM. I think it's more important to have `diagind` to be performing well in the case when it's constructed from the matrix to be applied to when reading/writing.

**Comment by jishnub** [comment]
Probably we should add a NEWS entry?

**Comment by jishnub** [comment]
On second thoughts, it's perhaps unnecessary, as it's unlikely to require changes on the user's part

**Comment by palday** [comment]
@dkarrasch I think this does need NEWS even if the return type of `diagind` was never documented because it breaks certain operations that worked previously.

On 1.9:
```julia
julia> D = Diagonal(1:4);

julia> all(in(diagind(D)), collect(diagind(D)))
true
```

After this PR:
```julia
julia> D = Diagonal(1:4);

julia> all(in(diagind(D)), collect(diagind(D)))
ERROR: MethodError: no method matching /(::CartesianIndex{2}, ::CartesianIndex{2})
Stacktrace:
 [1] _in_range
   @ ./range.jl:1412 [inlined]
 [2] in
   @ ./range.jl:1418 [inlined]
 [3] Fix2
   @ ./operators.jl:1143 [inlined]
 [4] _all(f::Base.Fix2{typeof(in), StepRangeLen{…}}, itr::Vector{CartesianIndex{…}}, ::Colon)
   @ Base ./reduce.jl:1310
 [5] all(f::Function, a::Vector{CartesianIndex{2}}; dims::Function)
   @ Base ./reducedim.jl:1031
 [6] top-level scope
   @ REPL[3]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> 1 in diagind(D)
false
```

Checking whether an integer index is within the set of diagonal indices is something that a reasonable package may want to do -- and it's something we did in MixedModels.jl.

cc @dmbates

**Comment by jishnub** [comment]
I wonder if `diagind` should accept an `IndexStyle`, and optionally return an integer range for Cartesian arrays? A non-breaking approach might be to return integer ranges by default, and change `LinearAlgebra` to use `CartesianIndex` ranges where applicable.

**Comment by jishnub** [comment]
This has indeed broken other packages such as `BandedMatrices.jl` that were expecting `diagind` to return an `OrdinalRange{Int,Int}`. I would suggest reverting to the original behavior, with an option to choose whether to return `CartesianIndex`es. If this seems reasonable, I'll submit a PR

**Pull request merged**
