### PR TITLE
[release-0.4, RFC] backports for 0.4.6

### PR DESCRIPTION
**Pull request by tkelman**
This is way overdue, primarily because of code signing issues with the windows binaries, ref https://groups.google.com/forum/#!topic/julia-dev/YipJ-uRF-5Q. That issue is still not resolved, but I'm preparing this in the hopes that we can resolve it soon. Worst case we'll put out unsigned binaries that trigger security warnings if need be.

~~Still have a few more commits left to get in here, once it's ready as far as I'm concerned~~ I'll run PkgEval as usual. Speak up if you have bug fixes, doc revisions, simple test additions, or similar that haven't been tagged with the backport pending label yet.

### CODE REVIEW

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@2ac304dfba75fad148d4070ef4f8a2e400c305bb")`

**Comment by nalimilan** [comment]
RPM build went fine.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16980#issuecomment-226716415) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1e15091a0db97758f86dbc5dcfe0a26a5976e2c4/323dfc6_vs_2ac304d/report.md). cc @jrevels

**Comment by KristofferC** [comment]
Let's try again 

@nanosoldier `runbenchmarks(ALL, vs="@2ac304dfba75fad148d4070ef4f8a2e400c305bb")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16980#issuecomment-226762235) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/edcf386a8fb8632469bc7c346930981a3fb98dc3/4896d64_vs_2ac304d/report.md). cc @jrevels

**Comment by omus** [comment]
@tkelman I would like it if #13500 was backported. Since it didn't quite backport cleanly I resolved the conflicts in this PR: #16992

**Comment by tkelman** [comment]
My baseline had a few more failures than it should have because of some recent package tags breaking one another even on 0.4.5, but at least the difference in test statuses between 0.4.5 and 081c049 was only Reactive, which has flaky tests:
```diff
--- 0.4.5.summary       2016-06-18 01:36:27.223835107 -0400
+++ 081c049d28.summary  2016-06-18 02:04:02.675352815 -0400
@@ -756,7 +756,7 @@
 RDatasets.json "tests_pass"
 RDF.json "tests_fail"
 RdRand.json "not_possible"
-Reactive.json "tests_fail"
+Reactive.json "tests_pass"
 React.json "no_tests"
 ReadWriteLocks.json "tests_pass"
 RecipesBase.json "tests_pass"
```

**Comment by tkelman** [comment]
I'm having trouble reproducing this apparent failure in RingArrays: https://gist.githubusercontent.com/anonymous/23bd9ed5ab27b94f395371e63a4e5853/raw/5ab1a790b43a017b774c76848bfcc563b16d7393/RingArrays.json
```diff
ary 2c7288e5ec.summary
--- 0.4.5.summary       2016-06-18 10:21:05.455273707 -0400
+++ 2c7288e5ec.summary  2016-06-18 10:21:34.010793046 -0400
@@ -45,7 +45,7 @@
 BayesianDataFusion.json "tests_pass"
 BayesNets.json "tests_pass"
 BDF.json "tests_pass"
-Benchmark.json "tests_fail"
+Benchmark.json "tests_pass"
 BenchmarkLite.json "no_tests"
 BenchmarkTools.json "tests_pass"
 BEncode.json "tests_pass"
@@ -778,7 +778,7 @@
 ReverseDiffSource.json "tests_pass"
 ReverseDiffSparse.json "tests_pass"
 Rif.json "tests_pass"
-RingArrays.json "tests_pass"
+RingArrays.json "tests_fail"
 RingBuffers.json "tests_pass"
 RLEVectors.json "tests_pass"
 RNGTest.json "tests_pass"
```


Could use some assistance or opinions on what to do about these regressions. I've triggered a bunch of nanosoldier comparisons vs 0.4.5 at various points more recently on release-0.4 and within this branch, but I'm not sure what to make of it all.

**Comment by tkelman** [comment]
Yichao must have seen https://github.com/JuliaLang/julia/commit/03db8fcf597e59472337cddf87f2f4a5c2e623a5 on a fetch, but looks like reverting one commt here fixes the worst regressions. Unless the numbers are unreliable for some other reason.

**Comment by tkelman** [comment]
What would make sorting forwards slower but reverse faster? And indexing tuples looks quite a bit slower, and I can't make sense of what caused it. Need a judgement call from someone on whether or not that's an acceptable regression for a patch release.

@nanosoldier `runbenchmarks(ALL, vs="@2ac304dfba75fad148d4070ef4f8a2e400c305bb")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16980#issuecomment-226986755) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2caec29cd6ff2a2e29d20c1fb99f952a332631f6/37a70a5_vs_2ac304d/report.md). cc @jrevels

**Comment by tkelman** [comment]
Blas got slower than https://github.com/JuliaCI/BaseBenchmarkReports/blob/beeb8bd2b9e8b604db86fd7033fe728659c52aa9/03db8fc_vs_2ac304d/report.md despite only being different by a trivial doc commit? My confidence in nanosoldier is not high right now.

**Comment by KristofferC** [comment]
Blas has consistently been a bit noisy but for the rest it has seemed quite good recently. I could try look at stuff locally if you have some commits you suspect are be bad.

**Comment by tkelman** [comment]
definition of insanity here...
@nanosoldier `runbenchmarks(ALL, vs="@2ac304dfba75fad148d4070ef4f8a2e400c305bb")`

**Comment by mauro3** [comment]
If not done yet, could #16999 still be back-ported?

**Comment by tkelman** [comment]
That's way too recent, I'd rather hold off on that one and wrap this up.

**Comment by mauro3** [comment]
Ok, no worries. (Could you add the backport label though?)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/16980#issuecomment-226995502) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/ce2a670f159a9f462fac0718b8f93e71ce54496f/37a70a5_vs_2ac304d/report.md). cc @jrevels

**Comment by tkelman** [comment]
This is kind of all over the place, I think I'll merge and tag this so we can hopefully get binaries up before I need to get on a plane.

**Comment by KristofferC** [comment]
I checked the sorting and could not reproduce the `forward` vs `reverse` discrepancy.

**Comment by tkelman** [comment]
Great, perfect time for the Mac buildbot to break. @staticfloat your help is required, I still am unable to log into that buildbot (I can log into the host, but not the VM). https://build.julialang.org/builders/build_osx10.9-x64/builds/1111/steps/shell_1/logs/stdio
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build/openspecfun-e4df5ae16af1bb4d28729a2fb5a8c2f3a49cf7ad/ ARCH="x86_64" CC="clang -stdlib=libc++ -mmacosx-version-min=10.7 -march=core2 -integrated-as -m64" FC="gfortran -mmacosx-version-min=10.7 -march=core2 -Wa,-q -m64" AR="ar" OS="Darwin" USECLANG=1 USEGCC=0 FFLAGS="-O2 -fPIC" CFLAGS="-I/usr/local/include -O3 -std=c99" USE_OPENLIBM=1 DESTDIR="" prefix=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr bindir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/tools libdir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/lib shlibdir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/lib libexecdir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/libexec datarootdir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/share includedir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/include sysconfdir=/Users/osx/buildbot/slave/build_osx10_9-x64/build/usr/etc O=
gfortran -mmacosx-version-min=10.7 -march=core2 -Wa,-q -m64 -O2 -fPIC  -fPIC -c amos/d1mach.f -o amos/d1mach.f.o
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/gcc/6.1.0/libexec/gcc/x86_64-apple-darwin13.4.0/6.1.0/f951
  Reason: image not found
gfortran: internal compiler error: Trace/BPT trap: 5 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew/issues> for instructions.
make[2]: *** [amos/d1mach.f.o] Error 4
make[1]: *** [build/openspecfun-e4df5ae16af1bb4d28729a2fb5a8c2f3a49cf7ad/libopenspecfun.dylib] Error 2
make: *** [julia-deps] Error 2
```

**Comment by staticfloat** [comment]
Mmmm, yeah, might have been leftovers from the `gcc` upgrade recently, although I'm not entirely sure why `libisl` wouldn't have been updated while `gcc` was.

**Pull request merged**
