### PR TITLE
Trace of a Hermitian matrix returns real value.

### PR DESCRIPTION
**Pull request by mpf**
The trace of a Hermitian matrix is necessarily real valued.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Coming to think of it, I think we should have had a loop here, and not extracted the diagonal vector. This is what we do for trace in the real case.

**Comment by StefanKarpinski** [comment]
You also may want to convert to real instead of just taking the real part, since that would verify that the imaginary part is actuay zero.

**Comment by andreasnoack** [comment]
@mpf Thanks. An easy way of avoiding the temporary that @ViralBShah metioned is to use the fall back `trace` method for the underlying buffer and then convert that to real, e.g. `real(trace(A.data))`.

@StefanKarpinski Right now we check for real diagonal on construction so it shouldn't be a problem. However, right now we are too strict, e.g.
```jl
julia> A = complex(randn(4,4), randn(4,4));
Hermitian(A*diagm(randn(4))*A');     
ERROR: ArgumentError: Cannot construct Hermitian from matrix with nonreal diagonals  
 in call at linalg/symmetric.jl:16                                                   
 in call at linalg/symmetric.jl:14
```

**Comment by mpf** [comment]
@andreasnoack Thanks for the suggestion to use the underlying trace method. Will do.

**Pull request merged**
