### PR TITLE
Automatically choose a correct `fma` implementation at run time

### LINKED ISSUE #9847: test/numbers.jl fails on 32-bit platform
```
$ make test-numbers
    JULIA test/numbers
     * numbers             exception on 1: ERROR: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in runtests at /usr/local/src/julia/julia/test/testdefs.jl:66
 in anonymous at multi.jl:642
 in run_work_thunk at multi.jl:603
 in remotecall_fetch at multi.jl:676
 in remotecall_fetch at multi.jl:691
 in anonymous at task.jl:1614
while loading numbers.jl, in expression starting on line 318
ERROR: LoadError: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in runtests at /usr/local/src/julia/julia/test/testdefs.jl:66
 in anonymous at multi.jl:642
 in run_work_thunk at multi.jl:603
 in remotecall_fetch at multi.jl:676
 in remotecall_fetch at multi.jl:691
 in anonymous at task.jl:1614
while loading numbers.jl, in expression starting on line 318
while loading /usr/local/src/julia/julia/test/runtests.jl, in expression starting on line 42

make[1]: *** [numbers] Error 1
make: *** [test-numbers] Error 2
[Rick@steelers julia]$ ./julia -e 'versioninfo()'
Julia Version 0.4.0-dev+2824
Commit 6bc53e6* (2015-01-19 20:14 UTC)
Platform Info:
  System: Linux (i686-redhat-linux)
  CPU: Genuine Intel(R) CPU           T2250  @ 1.73GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Banias)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Interestingly ...
```
$ ../julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2824 (2015-01-19 20:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6bc53e6* (0 days old master)
|__/                   |  i686-redhat-linux

julia> repr(0.1 + 0.2)
"0.30000000000000004"

julia> include("testdefs.jl")
2-element Array{Union(UTF8String,ASCIIString),1}:
 "/usr/local/src/julia/julia/usr/local/share/julia/site/v0.4"
 "/usr/local/src/julia/julia/usr/share/julia/site/v0.4"      

julia> repr(0.1 + 0.2)
"0.30000000000000004"

julia> include("numbers.jl")
ERROR: LoadError: test failed: ("0.3" != "0.3")
 in expression: repr(0.1 + 0.2) != "0.3"
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
while loading /usr/local/src/julia/julia/test/numbers.jl, in expression starting on line 318

julia> repr(0.1 + 0.2)
"0.3"

```

### LINKED ISSUE #9890: `fma` calls the system libm, not Julia's openlibm
I am tracking down a test failure where `fma` returns a wrong result. This is a 64-bit Intel Linux system with glibc 2.12 installed.

`code_native` tells me that `fma` expands to a libcall on this system (as should be), and also tells me the address of this `fma` function, but without giving it a name. `/proc/*/maps` tells me that this address is part of a range where `/lib64/libm-2.12.so` is mapped. That is, Julia's `fma` call goes to the system libm, not to Julia's openlibm.

The reason is that we expand Julia's `fma` to an LLVM intrinsic, and the libcall is then generated by LLVM since there is no `fma` machine instruction available. LLVM chooses to call `libm`.

I suggest to check whether the system has an `fma` instruction when expanding Julia's `fma` function, and if not, expanding it to a call to `openlibm` instead of an LLVM intrinsic. This requires #9855 to be available.

This issue may be related to #9847.

### PR DESCRIPTION
**Pull request by eschnett**
Fixes #9890. May fix #9847.

### CODE REVIEW

**Comment by nalimilan** [comment]
Do you have an idea about what's broken in the system libm? Or any simple C code to reproduce the bug? It would be nice to report this upstream too.

**Comment by eschnett** [comment]
The broken system libm is from glibc 2.12, several years out of date (from 2010). Newer versions of glibc are fine (I tested 2.19).

I have a simple example that reproduces the problem; in fact, this is what is used at run time to check `fma`. Since this is just a function call, it could be easily converted to C where it should break as well. However, since this is already fixed upstream, there's nothing we can do except avoid broken installations.

We could presumably write a configure test, detect this a Julia build time, and pass in a flag to the run-time library. This would be considerably more complex than the current method. The current method is also "obviously correct", as it is guaranteed to check that `fma` implementation that Julia actually uses, instead of second-guessing this at configuration time.

**Comment by nalimilan** [comment]
OK, great to know that it's been fixed upstream. I'm fine with the detection code.

**Comment by staticfloat** [comment]
I agree this is better than a build-time test, as what with us shipping binaries and such, build-time environment can vary quite a bit from the run-time environment.  Note that this doesn't quite solve #9847 for me, but I think that's a separate issue, so that shouldn't hold this up.

**Comment by tkelman** [comment]
Looks good to me, thanks for the fix.

I'll reopen #9847 in a second, given E's report that this doesn't quite fix it.

**Comment by rickhg12hs** [comment]
Unfortunately, this generates a bootstrap error on my 32-bit Linux.
```
constants.jl
error during bootstrap: LoadError(at "sysimg.jl" line 268: LoadError(at "constants.jl" line 52: ErrorException("assertion failed: float32(π) == float32(big(π))")))
make[1]: *** [/usr/local/src/julia/julia/usr/lib/julia/sys0.o] Error 1
make: *** [release] Error 2
```

**Comment by tkelman** [comment]
Damn, thanks for testing. This should maybe be reverted if no one has a quick fix.

**Comment by rickhg12hs** [comment]
Beats me why the `fma` edits would affect the constant conversions ... on a 32-bit system.

Who's the constant conversion expert?  8-)

**Comment by eschnett** [comment]
You could remove the respective `@asserts` to complete the bootstrap, and then output `float32(pi)`, `big(pi)`, and `float32(big(pi))`. That would give a further pointer as to what is going wrong.

**Comment by rickhg12hs** [comment]
Building now ...

**Comment by eschnett** [comment]
There's a problem with the system `fma` on some 32-bit Linux systems, as it changes the rounding mode (see #9847). This could affect conversions. My patch above checks whether `fma` works by calling it, which could corrupt the rounding mode.

**Comment by rickhg12hs** [comment]
... still building.

Wondering if you `set_rounding` after your `fma` tests if all might be good. ???

**Comment by eschnett** [comment]
Yes, saving and restoring the rounding mode may help -- but it doesn't help for #9847; apparently there are two rounding modes for 32-bit systems.

**Comment by rickhg12hs** [comment]
Well, the original `assert` was correct ...
```
$ ./julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2879 (2015-01-24 04:02 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4ff8145* (0 days old master)
|__/                   |  i686-redhat-linux

julia> float32(pi)
3.1415925f0

julia> big(pi)
3.141592653589793238462643383279502884197169399375105820974944592307816406286198e+00 with 256 bits of precision

julia> float32(big(pi))
3.1415927f0

julia> float32(pi) |> num2hex
"40490fda"

julia> float32(big(pi)) |> num2hex
"40490fdb"

julia> get_rounding(Float32)
Base.Rounding.RoundingMode{:Nearest}()

julia> set_rounding(Float32, RoundNearest)
0

julia> float32(big(pi))
3.1415927f0

julia> float32(pi)
3.1415925f0

julia> set_rounding(Float64, RoundNearest)
0

julia> float32(pi)
3.1415925f0

julia> float32(big(pi))
3.1415927f0

julia> set_rounding(BigFloat, RoundNearest)
0

julia> float32(pi)
3.1415925f0

julia> float32(big(pi))
3.1415927f0

```
Based on previous tests, I don't believe `get_rounding`, but `set_rounding` didn't seem to fix things.

**Comment by eschnett** [comment]
What glibc version do you have installed?

**Comment by vtjnash** [comment]
> I agree this is better than a build-time test, as what with us shipping binaries and such, build-time environment can vary quite a bit from the run-time environment. Note that this doesn't quite solve #9847 for me, but I think that's a separate issue, so that shouldn't hold this up.

i'm not sure I follow. this is PR is a build-time test

**Comment by rickhg12hs** [comment]
```
$ ldd ./julia 
	linux-gate.so.1 =>  (0xb7785000)
	libjulia.so => not found
	libdl.so.2 => /lib/libdl.so.2 (0x434e6000)
	librt.so.1 => /lib/librt.so.1 (0x43541000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x434ed000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0x4361e000)
	libm.so.6 => /lib/libm.so.6 (0x434a1000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x43522000)
	libc.so.6 => /lib/libc.so.6 (0x432e1000)
	/lib/ld-linux.so.2 (0x432be000)
$ /lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.3 20140624 (Red Hat 4.8.3-1).
Compiled on a Linux 3.14.17 system on 2014-08-28.
Available extensions:
	The C stubs add-on version 2.1.2.
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
	RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by eschnett** [comment]
I'm looking at (one of) the `fma` implementations in glibc. It sets the rounding mode to `FE_TOWARDZERO`, but doesn't to set it back.

**Comment by tkelman** [comment]
> i'm not sure I follow. this PR is a build-time test

D'oh, right, yeah this ends up making the decision at system image build time, doesn't it.

If these instructions are going to be buggy in a lot of places, we might have to make them explicitly opt-in somehow. Or move the check to some `__init__` method where it will truly be run-time.

**Comment by simonbyrne** [comment]
I guess the easiest option is to add a call to `set_rounding` after a problematic `fma` has been detected.

**Comment by eschnett** [comment]
`set_rounding` doesn't seem to work reliably on 32-bit Linux systems. See #9847; this is also mentioned in glibc's documentation.

We may have to disable LLVM's `fma` intrinsic for the time being, and only use it when we know the hardware has an `fma` instruction. Instead, we should be using openlibm's `fma` function.

**Comment by eschnett** [comment]
I don't have easy access to a 32-bit Linux system for testing. Could someone test whether the `set_rounding` idea works?

**Comment by staticfloat** [comment]
@eschnett this seems to have an effect:

```
julia> 0.1 + 0.2
0.30000000000000004

julia> fma(1.0,1.0,1.0)
2.0

julia> 0.1 + 0.2
0.3

julia> set_rounding(Float64, RoundNearest)
0

julia> 0.1 + 0.2
0.30000000000000004

julia> versioninfo()
Julia Version 0.4.0-dev+2893
Commit 427417a (2015-01-24 21:24 UTC)
Platform Info:
  System: Linux (i686-linux-gnu)
  CPU: Intel Xeon E312xx (Sandy Bridge)
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by eschnett** [comment]
Can you add `set_rounding(Float32, RoundNearest)` and `set_rounding(Float64, RoundNearest)` and the end of the code block introduced by this patch? Does this fix your bootstrap?

**Comment by staticfloat** [comment]
I had to do:
```
Rounding.set_rounding_raw(Float32, Rounding.JL_FE_TONEAREST)
Rounding.set_rounding_raw(Float64, Rounding.JL_FE_TONEAREST)
```

Because if I didn't, I got "function undefined" errors when using `set_rounding()` due to `to_fenv()` not being defined.  This is kind of weird since `to_fenv()` is most definitely defined, but it's defined inside of the `Rounding` module, and I think the module subsystem is in kind of a weird state at this point.  But by adding those two lines, things seem to work just fine.  Bootstrap finishes, although `make testall` still fails with the `repr(0.1 + 0.2) != 0.3` test.

**Comment by eschnett** [comment]
Was this `repr` failure present before, or was this also introduced by this change?

**Comment by staticfloat** [comment]
The `repr` failure is the same as https://github.com/JuliaLang/julia/issues/9847, where we believe it is due to `set_rounding()` not being called after every `fma()` invocation.

**Comment by eschnett** [comment]
I checked openlibm's `fma`, and it seems correct, whereas glibc's `fma` seems incorrect. The patch here switches the code to use openlibm's `fma` all the time, except when initializing the library. Thus I don't understand what is going on.

The best explanation I've heard is that `get_rounding` is not working correctly on 32-bit Linux systems. This would mean that restoring the original rounding mode via `set_rounding` would fail. We could forcefully call `set_rounding(:Nearest)` after every call to `fma`.

**Comment by staticfloat** [comment]
On Ubuntu 14.04 32-bit, I'm using glibc 2.19.  Your tests pass, but the rounding mode still gets clobbered:

```
julia> 0.1 + 0.2
0.30000000000000004

julia> Base.fma_llvm(1.0000305f0, 1.0000305f0, -1.0f0) == 6.103609f-5
true

julia> Base.fma_llvm(1.0000000009313226, 1.0000000009313226, -1.0) == 1.8626451500983188e-9
true

julia> 0.1 + 0.2
0.3
```

**Comment by simonbyrne** [comment]
@staticfloat If this is still a problem with glibc, then we should probably file the bug upstream.

**Pull request merged**
