### PR TITLE
fix undef var in conversion in rounding modes in MPFR

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by martinholters** [comment]
Worth a test?

**Review by simonbyrne — APPROVED** [review]

**Comment by simonbyrne** [comment]
(the change was only in 1.1, so doesn't need to be backported before that)

**Comment by simonbyrne** [comment]
I'm also not sure how one could test this. I guess use `reinterpret` to create an enum with an invalid value?

**Comment by martinholters** [comment]
Yes, something like this:
```julia
bad_rounding_mode = reinterpret(Base.MPFR.MPFRRoundingMode, Int32(42))
@test_throws ArgumentError convert(RoundingMode,  bad_rounding_mode)
```
Doing the `reinterpret` outside `@test_throws` has the advantage that the test doesn't pass accidentally in case the `reinterpret` throws an `ArgumentError`.

**Comment by KristofferC** [comment]
It seems really weird to have to do something like reinterpreting to an invalid enum to test something. In fact, it can be determined deterministically that the error path cannot happen. So I can change it to just `error("this should not happen")` if you want to.

**Comment by martinholters** [comment]
Yes, I was wondering the same. It's more an assertion then an `ArgumentError`.

**Comment by KristofferC** [comment]
Since this is unreachable code but more correct unreachable code, I'll just merge it.

**Pull request merged**
