### PR TITLE
Fix LaTeX completions of Greek variants, add \frakI and \frakR

### PR DESCRIPTION
**Pull request by sijow**
### Missing completions

This PR fixes two holes in the `\frak...` alphabet:

`\frakI`: same as `\Im`
`\frakR`: same as `\Re`

(Reference: https://www.unicode.org/charts/PDF/U1D400.pdf page 10.)

This is similar to how `\euler` is also mapped to `\scre` and `\planck` is also mapped to `\ith`.

Note that this leads to a change in the suggested completions:

```
help?> ℜℑ
"ℜℑ" can be typed by \Re<tab>\Im<tab>
```

becomes

```
help?> ℜℑ
"ℜℑ" can be typed by \frakR<tab>\frakI<tab>
```

Currently the reverse mapping is a bit random when there are several completions for one symbol, see: https://github.com/JuliaLang/julia/blob/6cff73f43ebef43d766dce29652b77ff756aa008/stdlib/REPL/src/docview.jl#L335 If this is deemed a problem, maybe it would make sense to add an explicit reverse mapping for ambiguous cases?

### Bad completions

Julia uses `\varphi` for the loopy variant of phi, and `\varepsilon` for the curly variant of epsilon (same as LaTeX). However Julia is not consistent with the style variants (italic, bold, sans...) of these letters:

```
help?> ϕ𝜙𝛟𝞍𝝓𝟇
"ϕ𝜙𝛟𝞍𝝓𝟇" can be typed by \phi<tab>\itvarphi<tab>\bfphi<tab>\bsansvarphi<tab>\bivarphi<tab>\bisansvarphi<tab>

help?> ϵ𝜖𝛜𝞊𝝐𝟄
"ϵ𝜖𝛜𝞊𝝐𝟄" can be typed by \epsilon<tab>\itvarepsilon<tab>\bfvarepsilon<tab>\bsansvarepsilon<tab>\bivarepsilon<tab>\bisansvarepsilon<tab>
```

This PR fixes the commands of the style variants.

#### Phi superscripts

This one might be more controversial.

Unicode distinguishes three variants of lowercase phi:

* [U+03d5](https://unicode.org/charts/PDF/U0370.pdf) = "Greek phi symbol" = `\phi` in Julia and LaTeX
* [U+03c6](https://unicode.org/charts/PDF/U0370.pdf) = "Greek small letter phi" = `\varphi` in Julia and LaTeX
* [U+0278](https://unicode.org/charts/PDF/U0250.pdf) = "Latin small letter phi" = `\ltphi`, a phonetic symbol that looks like a `\phi` with small serifs

Based on these characters, Unicode defines two superscript phi letters:

* [U+1d60](https://unicode.org/charts/PDF/U1D00.pdf): modifier letter small Greek phi, based on "Greek phi symbol"
* [U+1db2](https://unicode.org/charts/PDF/U1D80.pdf): modifier letter small phi, based on "Latin small letter phi"

The first one is straightforward: it's like `\phi` but as superscript. Julia maps it to `\^phi` as expected.

The second one is problematic: it's a superscript version of `\ltphi`, yet Julia maps it to `\^Phi`.

This PR fixes it by remapping U+1db2 to `\^ltphi`. It's not as discoverable, but the current completion is misleading: a font could correctly implement `\^Phi` as something that doesn't really look like a superscript `\Phi`. And a future Unicode version might add a real superscript `\Phi`.

Note: the situation is similar to U+1d4b = `\^epsilon`: that Unicode character is actually a superscript version of the "Latin small letter open e" (rather thn "Greek small letter epsilon"). But it's different because Julia doesn't have `\ltepsilon` or `\openepsilon`, and Julia actually normalizes the "Latin" and "Greek" letters in this case (which is reasonable, they really look the same), see https://github.com/JuliaLang/julia/issues/14751.

### CODE REVIEW

**Comment by stevengj** [comment]
It would be good to manually fix the REPL help dictionary in cases like this where there are multiple possible tab-completion options.

**Comment by knuesel** [comment]
I've added a canonical mapping for ambiguous cases (in `latex_symbols.jl` rather than `docview.jl` to keep all the mapping specifications in one file).

Looking at all the duplicates uncovered a few inconsistencies, so I made a few more changes to the completions suggested by the REPL. I generally chose the shorter option, which is often also the more mathematical meaning (e.g. \implies vs \Longrightarrow).

Duplicates were found with the following commands:

```julia
using REPL
ls = REPL.REPLCompletions.latex_symbols; symbols = values(ls)
duplicates = [v for v in unique(symbols) if count(==(v), symbols) > 1]
[(v, REPL.symbol_latex(v)) => findall(==(v), ls) for v in duplicates]
```

Here is the current list of duplicates (including changes from this PR):

```julia
         ("ℜ", "\\Re") => ["\\Re", "\\frakR"]
  ("⟸", "\\impliedby") => ["\\impliedby", "\\Longleftarrow"], # was \Longleftarrow
         ("ℑ", "\\Im") => ["\\Im", "\\frakI"]
       ("√", "\\sqrt") => ["\\surd", "\\sqrt"]
         ("≥", "\\ge") => ["\\ge", "\\geq"],  # was \geq
       ("♂", "\\male") => ["\\male", "\\mars"], # was \mars
         ("→", "\\to") => ["\\to", "\\rightarrow"], # was \rightarrow
  ("⟧", "\\rrbracket") => ["\\openbracketright", "\\rrbracket"]
     ("♀", "\\female") => ["\\venus", "\\female"]
   ("∅", "\\emptyset") => ["\\varnothing", "\\emptyset"]
       ("…", "\\dots") => ["\\dots", "\\ldots"],  # was \ldots
        ("⊻", "\\xor") => ["\\veebar", "\\xor"]
    ("⟹", "\\implies") => ["\\implies", "\\Longrightarrow"], # was \Longrightarrow
  ("⟦", "\\llbracket") => ["\\llbracket", "\\openbracketleft"], # was \openbracketleft
     ("ℎ", "\\planck") => ["\\ith", "\\planck"]
        ("∇", "\\del") => ["\\del", "\\nabla"], # was \nabla
        ("̶", "\\sout") => ["\\strike", "\\sout"]
 ("ε", "\\varepsilon") => ["\\upepsilon", "\\varepsilon"]
         ("ð", "\\dh") => ["\\eth", "\\dh"]
        ("⟺", "\\iff") => ["\\Longleftrightarrow", "\\iff"]
      ("ℯ", "\\euler") => ["\\scre", "\\euler"]
         ("≤", "\\le") => ["\\le", "\\leq"], # was \leq
```
The left side shows the canonical mapping. Comments show the old one if it was changed by this PR.

The duplicate list also revealed that we had both `\join` and `\Join` for `⨝`. I removed `\Join`.

A test is included to check that a canonical mapping is specified for all ambiguous cases.

**Comment by stevengj** [comment]
I would maybe keep `("…", "\\ldots")` to parallel `\cdots`, but otherwise LGTM.

**Comment by knuesel** [comment]
Wouldn't a user likely prefer to know that the symbol is available as `\dots`? It seems a bit more memorable (and it's shorter of course). On the other hand, one can also argue that `\ldots` is more correct/explicit since in amsmath `\dots` adapts to context so it's not always three dots on the baseline.

Just making sure the case for `\dots` is made properly 😊 I'll happily change it if you still prefer `\ldots`.

**Comment by stevengj** [comment]
`\ldots` seems less confusing to me from a LaTeX perspective.

**Comment by knuesel** [comment]
OK! I've changed the suggestion to `\ldots`.

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
CI failure is apparently unrelated: `LoadError: "hard kill repl test"`?

**Comment by knuesel** [comment]
Yes that looks like https://github.com/JuliaLang/julia/issues/38996.

**Pull request merged**
