### PR TITLE
Remove circleci, old freebsd ci and vagrant (pkgeval) config files

### PR DESCRIPTION
**Pull request by ViralBShah**
With the various recent upgrades to our infrastructure, we no longer use circleci, the old freebsd ci and vagrant (which was used for the old pkgeval).

@staticfloat Is it ok to delete the files in this PR?

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can we also delete `contrib/ackrc` and its README?

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
> Can we also delete contrib/ackrc and its README? If people use it, we should move them to contrib/ack.

I would just move them now.  I'm not sure how useful they are, but this is why we have a `contrib/` directory.

**Comment by musm** [comment]
@ViralBShah  you will also need to remove the section https://github.com/JuliaLang/julia/blob/master/README.md#vagrant

**Comment by ViralBShah** [comment]
I think the README itself needs refactoring. I will take a crack at it.

**Comment by musm** [comment]
Sounds good, but maybe in another PR ?

**Comment by ViralBShah** [comment]
I was planning to do it in this PR, but now that this is merged, @musm do you want to submit the PR? Otherwise I will get to it on sunday.

**Comment by StefanKarpinski** [comment]
> I think the README itself needs refactoring.

It's pretty long. I wonder if it wouldn't be better to give a very high-level list of references to other locations where more detailed documentation of how to do various things can be found.

**Comment by ararslan** [comment]
> I was planning to do it in this PR

My bad, didn't realize that was your intention.

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/pull/31858

**Pull request merged**
