### PR TITLE
RFC: Adds test_broken and test_skip macros

### PR DESCRIPTION
**Pull request by morris25**
`test_broken` and `test_skip` can be used to designate tests that should pass but don't. In an attempt to be noticed by testers they produce a `Broken`result. `test_skip` will simply skip over testing, and `test_broken` will raise an error to alert the user if the test unexpectedly succeeds.

This pull request is a continuation of #15832.

### CODE REVIEW

**Comment by tkelman** [comment]
Other than the test report always displaying the count of how many there were, how is "skip" materially any different than commenting out a test?

**Comment by omus** [comment]
I think the current version `@test_skip` is materially the same as commenting out a test. The main advantage is that the report reminds developers that there is an unfinished test case to deal with.

**Comment by wildart** [comment]
How hard it would be implement skipping of testsets with appropriate reporting?

**Comment by StefanKarpinski** [comment]
Failure is a timeout, might be https://github.com/JuliaLang/julia/issues/17041.

**Comment by tkelman** [comment]
see #17038

**Comment by StefanKarpinski** [comment]
thanks, @tkelman

**Pull request closed without merging**
