### PR TITLE
use virtualenv to install juliadoc

### PR DESCRIPTION
**Pull request by nolta**

### CODE REVIEW

**Comment by tkelman** [comment]
I think I'll want to backport this (and probably also #8479, and 10b64dde2acaa6ea275c2e5c8531a08a91546f95, and 592ec62b4dd9bfb351f162002e825005c8c346b5) before 0.3.5 so we don't have to worry as much about sphinx versions for doc building.

**Comment by staticfloat** [comment]
yes please

**Comment by tkelman** [comment]
Given #9631 I don't think we'll have time to do this backport properly for 0.3.5, so I think this can wait until 0.3.6.

**Comment by tkelman** [comment]
Backported this in 8d864e1299d9c9b698314707082ba1de724e6142 and 7ba74aa6dd47b7c56969f12eabbb28e91eb3418c, along with a bunch more doc-building updates, so at least the double-newlines should be gone now from release-0.3.

**Pull request merged**
