### PR TITLE
speed up `analyze-variables` lowering pass by adding a hash table of variables

### PR DESCRIPTION
**Pull request by JeffBezanson**
Not as dramatic as #43022 but a bit of speedup nonetheless.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("frontend", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/43028#issuecomment-972088864) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/61fdaae_vs_8d5efbb/report.md).

**Comment by KristofferC** [comment]
Should this have shown an improvement in the benchmark?

**Comment by oscardssmith** [comment]
This was a significantly smaller change than the previous issue. It's likely that detecting it in the benchmark would have required way more let variables. IIRC, the use case that inspired this PR had something like 30K nested statements (compared to 2k for the benchmark). As such, I wouldn't be surprised if this change was considered to be within noise.

**Pull request merged**
