### PR TITLE
codegen emit constant data as llvm constants

### LINKED ISSUE #21121: Boxed tuples leaking into generated code
I've got an issue with generating a literal tuple from a macro → generated function, where in some cases the tuple in the AST is a boxed, breaking optimizations and (in my case) resulting in GPU incompatible code due to a literal pointer.

```julia
struct Wrapper
    tuple::NTuple{1,Int}
    Wrapper(tuple::NTuple{1,Int}) = new(tuple)
end

macro wrap(shape)
    return esc(:(generated_wrap(Val{$shape})))
end

function emit_wrap(shape)
    quote
        Base.@_inline_meta
        Wrapper($shape)
    end
end

@generated function generated_wrap{S}(::Type{Val{S}})
    return emit_wrap(S)
end

function kernel()
    wrapped = @wrap((42,))
    if 100 > wrapped.tuple[1]
        ccall("llvm.trap", llvmcall, Void, ())
    end
end
```

```
@code_lowered(kernel()) = CodeInfo(:(begin 
        nothing
        wrapped = (Main.generated_wrap)((Core.apply_type)(Main.Val, (Core.tuple)(42)))
        unless 100 > (Main.getindex)((Core.getfield)(wrapped, :tuple), 1) goto 7
        return $(Expr(:foreigncall, "llvm.trap", Void, svec(), :($(Expr(:llvmcall)))))
        7: 
        return
    end))


@code_typed(kernel()) = CodeInfo(:(begin 
        $(Expr(:inbounds, false))
        SSAValue(1) = (42,)
        $(Expr(:inbounds, :pop))
        unless (Base.slt_int)((Base.getfield)(SSAValue(1), 1)::Int64, 100)::Bool goto 13
        return $(Expr(:foreigncall, "llvm.trap", Void, svec(), :($(Expr(:llvmcall)))))
        13: 
        return
    end))=>Void


@code_llvm(kernel())
    define void @julia_kernel_68524() #0 !dbg !5 {
    top:
      %0 = load i64, i64* inttoptr (i64 140469690037328 to i64*), align 16
      %1 = icmp sgt i64 %0, 99
      br i1 %1, label %L13, label %if
    
    if:                                               ; preds = %top
      call void @llvm.trap()
      unreachable
    
    L13:                                              ; preds = %top
      ret void
    }
```

If instead `generated_wrap` returns e.g. `Wrapper((42,))`,  `code_lowered` is identical but the other two are different:

```
@code_typed(kernel()) = CodeInfo(:(begin
        unless (Base.slt_int)(42, 100)::Bool goto 5
        return $(Expr(:foreigncall, "llvm.trap", Void, svec(), :($(Expr(:llvmcall)))))
        5: 
        return
    end))=>Void


@code_llvm(kernel())
    define void @julia_kernel_68518() #0 !dbg !5 {
    top:
      call void @llvm.trap()
      unreachable
    }
```

On the CPU side, the generated code seems suboptimal but is still correct. On the GPU side however, we can't deal with these literal pointers to CPU memory. That's why I have added a codegenparam `allow_alloc`, which is passed to `static_eval`, but apparently there's other codegen paths that can emit literal pointers... Is this a bug, i.e. should I only expect `static_eval` to perform compile-time allocations and emit references to them, or are there other places that need to be guarded by such a codegenparam?

Bisected to #20853
cc @JeffBezanson, @cfoket

Version info:
```
Julia Version 0.6.0-pre.alpha.206
Commit 90cfb8292c* (2017-03-21 03:12 UTC)
Platform Info:
  OS: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

### PR DESCRIPTION
**Pull request by vtjnash**
this allows llvm to optimize constant data access
fix #21121

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Any effect on sysimg size?

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
Doesn't seem to be significant

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21277#issuecomment-291578201) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9299d98bac8437b71786af62e8fb4ea2c929f996/abfa732_vs_c9ad00a/report.md). cc @jrevels

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21277#issuecomment-291769914) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b69ae97d7fa4c221a482bd0774b9f21892c41712/c49440a_vs_a5b993c/report.md). cc @jrevels

**Comment by ararslan** [comment]
Are the SIMD regressions for a reason similar to that in #21279?

**Comment by vtjnash** [comment]
AFAICT, the generate code is identical and those are just noise. But might as well ask @nanosoldier `runbenchmarks("simd", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21277#issuecomment-291943258) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/df0a73f2097fe90f8d904c876605300bbacecf41/c49440a_vs_a5b993c/report.md). cc @jrevels

**Pull request merged**
