### PR TITLE
read multi-byte integers in one shot

### PR DESCRIPTION
**Pull request by bicycle1885**
This pull request improves the performance of reading multi-byte integers.
The performance gain is especially large for 64-bit integers.

```
Before                      After
------                      -----
UInt16                      UInt16
  83.915 milliseconds         70.105 milliseconds
Int16                       Int16
  77.856 milliseconds         70.525 milliseconds
UInt32                      UInt32
 169.842 milliseconds         69.058 milliseconds
Int32                       Int32
 175.813 milliseconds         77.217 milliseconds
UInt64                      UInt64
 325.072 milliseconds         83.050 milliseconds
Int64                       Int64
 313.216 milliseconds         84.966 milliseconds
```

Benchmark script:

``` julia
function bench{T}(::Type{T}, n)
    f = open(string("tmp", T), "w+")
    x = 12345
    for i in 1:n
        write(f, T(x))
    end
    @time for _ in 1:5
        seekstart(f)
        for i in 1:n
            @assert read(f, T) == x
        end
    end
    close(f)
end

let
    n = 1_000_000
    for T in [UInt16, Int16, UInt32, Int32, UInt64, Int64]
        println(T)
        bench(T, n)
    end
end
```

This is because the original code calls the `ios_getc` function for each reading byte, but the proposed code calls only one function (`jl_ios_get_uint(16|32|64)`) based on the required number of bytes.
https://github.com/JuliaLang/julia/blob/d88dd21e0d5722377bb4fe59e7330d35bae48081/base/io.jl#L109-L115
https://github.com/JuliaLang/julia/blob/d88dd21e0d5722377bb4fe59e7330d35bae48081/base/iostream.jl#L160-L166

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
:+1:

**Comment by StefanKarpinski** [comment]
Wouldn't it be possible to implement this in Julia though?

**Comment by bicycle1885** [comment]
Maybe possible. But I couldn't find a trivial way in Julia. Do you have any suggestions?

**Comment by Keno** [comment]
The right way to do this would be using `Ref`, but that's probably not quite efficient enough yet.

**Comment by bicycle1885** [comment]
Yes, I've tried `Ref` to read an integer into a reference object. But the performance gain is about half of this pull request.

**Comment by tbreloff** [comment]
Quick question... does endianness come into play here?

**Comment by tbreloff** [comment]
Also I'm wondering how this code compares (speed and correctness): 
```
unsafe_load(convert(Ptr{Int64}, pointer(buf, pos))
```

**Comment by carnaval** [comment]
yeah you'd probably want to do a single load for this. By the way, why aren't we using libuv for this ? I think there was an issue about it but can't find it.

**Comment by bicycle1885** [comment]
I don't know, but endianness may be a problem.
The original `read`, if I read correctly,  assumes little-endian serialization: https://github.com/JuliaLang/julia/blob/d88dd21e0d5722377bb4fe59e7330d35bae48081/base/io.jl#L111-L113

**Comment by JeffBezanson** [comment]
@carnaval The libuv file stuff in fs.jl needs to use the buffering logic implemented for AsyncStream, which it doesn't yet.

Re: endianness: I don't believe this change makes the situation worse than it was before.

**Comment by bicycle1885** [comment]
@tbreloff Do you mean directly reading bytes from a buffer? That sounds dangerous and unreliable.

**Comment by tbreloff** [comment]
@bicycle1885 Yes it can be dangerous if you assume little-endian but have a big-endian buffer.  As @JeffBezanson pointed out, we already had this danger.

**Comment by ScottPJones** [comment]
What about reading or writing 1-n bytes of an integer, instead of just 1, 2, 4, or 8?
Like SQLite, I use a data format that treats all numbers in a similar fashion, and I am reading/writing only the 1-8 non-zero bytes of a UInt8/16/32/64 (or positive Int8/16/32/64), or the 1-8 non-0xFF bytes of a negative Int8/16/32/64).  (I have a special marker for 0).
(endian might be an issue for this, because I always want to read/write the values in little-endian format)

**Comment by bicycle1885** [comment]
@ScottPJones That's reasonable. But reading 1-n bytes is about 20-30% slower than reading fixed bytes for 64-bit integers:

```c
DLLEXPORT uint64_t jl_ios_get_nbytes(ios_t *s, const size_t n)
{
    assert(n <= 8);
    uint8_t buf[8];
    size_t ret = ios_readall(s, (char*)buf, n);
    if (ret < n)
        throw_eof_error();
    uint64_t x = 0;
    for (int i = 0; i < n; i++)
        x |= (uint64_t)buf[i] << (i << 3);
    return x;
}
```

Benchmark

```
UInt16
  83.211 milliseconds
Int16
  78.462 milliseconds
UInt32
 102.944 milliseconds
Int32
  97.321 milliseconds
UInt64
 113.700 milliseconds
Int64
 103.456 milliseconds
```

This difference may doe to the lack of loop unrolling optimization. So I've tried the following code and the result was much better:

```c
DLLEXPORT uint64_t jl_ios_get_nbytes(ios_t *s, const size_t n)
{
    assert(n <= 8);
    uint8_t buf[8];
    size_t ret = ios_readall(s, (char*)buf, n);
    if (ret < n)
        throw_eof_error();
    uint64_t x = 0;
    if (n < 4) {
        for (int i = 0; i < n; i++)
            x |= (uint64_t)buf[i] << (i << 3);
    }
    else {
        // expecting loop unrolling optimization
        for (int i = 0; i < 4; i++)
            x |= (uint64_t)buf[i] << (i << 3);
        for (int i = 4; i < n; i++)
            x |= (uint64_t)buf[i] << (i << 3);
    }
    return x;
}
```

Benchmark:

```
UInt16
  78.968 milliseconds
Int16
  78.756 milliseconds
UInt32
  76.675 milliseconds
Int32
  83.210 milliseconds
UInt64
  92.793 milliseconds
Int64
  98.028 milliseconds
```

Should I have to use this code?

**Comment by bicycle1885** [comment]
Now the code is cleaner and the performance improvement is comparable to my first commit.
The three C functions are unified to a C function `jl_ios_get_nbytes(ios_t *s, const size_t n)`.

Benchmark:

```
UInt16
  84.492 milliseconds
Int16
  91.605 milliseconds
UInt32
  75.851 milliseconds
Int32
  82.791 milliseconds
UInt64
  82.631 milliseconds
Int64
  82.132 milliseconds
```

**Pull request merged**
