### PR TITLE
Mark up optimization passes with remarks and debug prints

### PR DESCRIPTION
**Pull request by pchintalapudi**
Remarks and debug prints are typically quite helpful when debugging missed optimizations or regressions, so use LLVM's functionality to provide that in our optimization passes.

### CODE REVIEW

**Comment by pchintalapudi** [comment]
@vtjnash Isn't the gc checker supposed to ignore llvm-* files? Why is it complaining about llvm-alloc-helpers.cpp?

**Comment by vtjnash** [comment]
no, the GC checker does the opposite actually and imposes stricter rules on `llvm-*` files (it marks all contents as JL_NOTSAFEPOINT)

**Comment by pchintalapudi** [comment]
In that case should I just wrap all the remarks with ifndef analyzer?

**Comment by vchuravy** [comment]
We should also add tests for this functionality.

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
