### PR TITLE
release-1.9: Backports for julia 1.9.0-alpha2 / 1.9.0-beta1

### LINKED ISSUE #46778: `precompile` fails to cache code for calls that are not fully specialized (non-concrete signature)
In https://github.com/JuliaLang/julia/pull/46690, I want to deserialize an object on a precompile worker and it is quite important that this is fully precompiled since a lot of precompile workers are spawned and each of these have a separate process and thus they would all need to compile the same code over and over if this isn't the case.

For arbitrary data types, `deserialize` has a function that takes `::DataType` and will not get specialized:

https://github.com/JuliaLang/julia/blob/aae8c484fd4ef9c9d7119e00f5eee679c905e542/stdlib/Serialization/src/Serialization.jl#L1468

As an example workload we can look at the following code

```julia
using Serialization

struct MyStruct
    x::String
end

s = MyStruct("foo")

io = IOBuffer()
serialize(io, s)
seekstart(io)
@time deserialize(io);
```

Running that with `--trace-compile=stderr` the following precompile statements are emitted from the `deserialize` call:

```julia
precompile(Tuple{typeof(Serialization.deserialize), Serialization.Serializer{Base.GenericIOBuffer{Array{UInt8, 1}}}, DataType})
```

However, restarting Julia and executing these before the `deserialize` call we can see that the `precompile` call for the `DataType` fails:

```julia
julia> precompile(Tuple{typeof(Serialization.deserialize), Serialization.Serializer{Base.IOStream}, DataType})
false
```

and the compilation time is still there.

However, if we specialize the function on the data type (as done in https://github.com/JuliaLang/julia/pull/46690/commits/6e0b2dad814b7a6603c47a5d0523591109e99dc0#diff-0fbb91f060d958d93fcf0a101ade4d87b365f3664a409276c591d7faf77acb67) the precompilation statements we get is:

```julia
precompile(Tuple{typeof(Serialization.deserialize), Serialization.Serializer{Base.GenericIOBuffer{Array{UInt8, 1}}}, Type{Main.MyStruct}})
```

the compilation time is then removed:

```julia
julia> @time deserialize(io);
  0.000014 seconds (14 allocations: 1.148 KiB)
```

It would be good if the code that is compiled for signatures that are non-concrete could be cached. They clearly are when you run the code since you don't have to compile it for every call.

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #46844 <!-- Limit initial OpenBLAS thread count -->
- [x] #47259 <!-- fix #46778, `precompile()` for abstract but compileable signatures -->
- [x] #47499 <!-- syntax error with anonfn inside `elseif` and short-circuit op -->
- [x] #47580 <!-- ensure bindings handle write barriers for ty and globalref -->
- [x] #47586 <!-- Improve Intel VTune integration -->
- [x] #47579 <!-- Doc: The default sorting alg. is stable from 1.9 -->
- [x] #47659 <!-- update MPFR -->
- [x] #47657 <!-- Add compat note for `sortperm(x; dims)` -->
- [x] #47589 <!-- Introduces get-lld to fix `make full-source-dist USE_BINARYBUILDER=0` -->
- [x] #47503 <!-- Print the detailed type on heap snapshot -->
- [x] #46825 <!-- Remove typeinfer lock altogether -->
- [x] #47605 <!-- Fix regression in generic_bitcast with Union{} arguments. -->
- [x] #47668 <!-- [Filesystem]: `rm(; recursive=true)` should ignore `UV_EACCES` -->
- [x] #47511 <!-- Fix overflow in pow5 -->
- [x] #47711 <!-- Fix and simplify inference timing logic -->
- [x] #47699 <!-- Fix GCExt test -->
- [x] #47637 <!-- Fix REPL keybinding CTRL-Q for stdlib methods -->
- [x] #47665 <!-- fix 5-arg `mul!` for vectors of vectors -->
- [x] #47666 <!-- Fix nth_methtable tparam of -1 when n==0 -->
- [x] #47739 <!-- Fix generator-invocation legality check for varargs generators -->
- [x] #47707 <!-- Bump libuv. -->
- [x] #47358 <!-- Provider cycleclock() for 32bit ARM targets -->
- [x] #47742 <!-- strengthen setglobal to default to release-consume ordering -->
- [x] #47719 <!-- fix unescaping in `global` expressions -->
- [x] #47383 <!-- Refactor and document sorting dispatch -->
- [x] #47792 <!-- Comment out subtype test that causes hang due to StackOverflowError -->
- [x] #47783 <!-- Prioritize build_dir for generated headers -->
- [x] #47803 <!-- Set `OPENBLAS_NUM_THREADS=1` on local Distributed workers -->
- [x] #47501 <!-- Add native julia fmod -->
- [x] #47220 <!-- Fix libjulia install name and libjulia-internal rpath on OS X -->
- [x] #47695 <!-- Add support for "package extensions" to code loading -->
- [x] #47859 <!-- Fix physical_memory exports. -->
- [x] #47865 <!-- Fix missing GC root in Symbol construction -->
- [x] #47667 <!-- ensure proper handling of sparams for widened compile signatures -->
- [x] #47876 <!-- TOML: print: handle mixed vector of dicts and non-dicts -->
- [x] #47822 <!-- Fixups for #47383 (fixes `runbenchmarks("sort")`) -->
- [x] #47878 <!-- add back wordaround for `Slot objects should not occur in an AST` in Ipython mode -->
- [x] #47889 <!-- Reduce invalidations when loading JuliaData packages -->
- [x] #47813 <!-- intersect: fix a minor soundness issue with supertypes -->
- [x] #47901 <!-- make Ctrl-C during sleeping work better -->
- [x] #47893 <!-- revert promotions of abstract arrays inside other arrays -->
- [x] #47927 <!-- only load extensions once dependencies have finished loading -->
- [x] #47924 <!-- Precompile cache: always add worklist CIs -->
- [x] #47622 <!-- Add bounds check to `Slices` indexing -->
- [x] #47788 <!-- Put back the old QuickSort and PartialQuickSort algorithms -->

Non-merged PRs with backport label:
- [ ] #47829 <!-- Clean closure and task-local-state in jl_finish_task -->
- [ ] #47676 <!-- Use versioned libblastrampoline and GMP -->
- [ ] #47675 <!-- Fix small nits in multiversioning -->
- [ ] #47636 <!-- Reland: Improve performance of global code by emitting fewer atomic barriers. -->
- [ ] #47615 <!-- Allow threadsafe access to buffer of type inference profiling trees -->
- [ ] #47393 <!-- Move safepoint emission to llvm-final-gc-lowering -->

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Alpha1 was already tagged, right? So this would be alpha2/beta1.

**Comment by KristofferC** [comment]
Yeah, just a typo.

**Comment by giordano** [comment]
I don't understand why #46976 is in the list of PRs, https://github.com/JuliaLang/julia/commit/eb708d62f897dfbf0a757aa24c30754a492c6514 is already in [v1.9.0-alpha1](https://github.com/JuliaLang/julia/releases/tag/v1.9.0-alpha1)

**Comment by KristofferC** [comment]
> I don't understand why https://github.com/JuliaLang/julia/pull/46976 is in the list of PRs

Because it still has the label

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47602#issuecomment-1359761049) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/81e7d51_vs_61c0b41/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.9")`

**Comment by KristofferC** [comment]
Some observations:

- Sort slower and allocates a lot more. Probably fixed to some extent by https://github.com/JuliaLang/julia/pull/47946 (@LilithHafner 
- Sparse matmul looks slower across the board. (@dkarrasch)
- `["linalg", "arithmetic", ("-", "Matrix", "Matrix", 1024)]` 2x slower. 
- `["collection", "set operations", ("Set", "Int", "union!", "BitSet")]` started allocating
- `["inference", "abstract interpretation", "many_global_refs"]` got 10x slower (vs 1.8)

**Comment by LilithHafner** [comment]
Note that BaseBenchmarks measures `sort(x; alg=XXX)` but does not measure `sort(x)` so the sorting regressions are worth addressing but should not effect most user code. `sort(x)` is often much faster.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47602#issuecomment-1360943207) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/81e7d51_vs_0540f9d/report.md).

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks("sort", vs = ":release-1.8")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/47602#issuecomment-1361474833) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/81e7d51_vs_61c0b41/report.md).

**Comment by KristofferC** [comment]
Let's do a beta now after CI goes through.

**Comment by oscardssmith** [comment]
We probably should backport https://github.com/JuliaLang/julia/pull/47184 first.

**Comment by KristofferC** [comment]
It's backported already.

**Pull request merged**
