### PR TITLE
Add Mozilla Public License 2.0 for Pkg.generate

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by tkelman** [comment]
This should go to PkgDev.jl, generate is being removed from base.

**Comment by IainNZ** [comment]
(but it is a good idea, its being used for some packages)

**Comment by wildart** [comment]
It could be introduced into 0.4.1.

**Comment by tkelman** [comment]
yes, against release-0.4 this pr would be fine

**Comment by stevengj** [comment]
Why is this a good idea?  Of course, people can use whatever license they want by manually editing their `LICENSE` file, but we shouldn't encourage license proliferation by suggesting more than few licenses, and MPL doesn't offer much that isn't available in the current menu.

**Comment by stevengj** [comment]
See also the discussion in #4908.

**Comment by tkelman** [comment]
MPL is non-viral copyleft, without the C-specific linking language that's in the LGPL. I think it's a good compromise for people who would otherwise use GPL without realizing all the consequences it has.

**Comment by iamed2** [comment]
@stevengj I don't understand the argument against "license proliferation". People don't choose licenses at random, so I don't think including more licenses would cause a massive uptick in the packages released with them. I also don't see any harm in more people using MPLv2.

**Comment by mlubin** [comment]
:+1:  for MPLv2. At worst, it may be attractive for package authors who otherwise would be using GPL.

**Comment by stevengj** [comment]
[License proliferation](http://opensource.org/proliferation) makes free/open-source development more complicated by increasing the number of licenses which need to be understood, and by increasing the complexity of their interactions.  That's why it is better to steer people who are undecided about the choice of license to one of a small number of non-redundant, well-tested, mutually compatible choices.

MPL is such a weak copyleft that it is hardly a copyleft; you might as well use BSD, since if someone wants to make a proprietary fork of your code then all they need to do is to put most of the new code in a separate file.  Hence I don't see the point in recommending it.

(If someone wants to use it, fine; they can always edit their LICENSE file to MPL.  The question here is which licenses we recommend.)

**Comment by mlubin** [comment]
@stevengj, IANAL but a lot of effort went into MPL, both in terms of balancing commercial use with copyleft and maintaining compatibility with other licenses. It's [listed](http://opensource.org/licenses) as one of the 9 popular open source licenses. It's certainly non-redundant, well tested, and compatible with other popular licenses. I agree in principle that license proliferation is a problem, but I don't think this is the right place to draw the line.

**Comment by stevengj** [comment]
@mlubin, the actual history of the MPL is described [here](https://www.safaribooksonline.com/library/view/open-sources/1565925823/ch13s04.html).  It was a spin-off of the NPL, which was created to address a specific business situation for Netscape at the time.

By design, MPL allows you to combine code with code under any other license, including proprietary/closed-source/non-free code, as long as the latter is in a separate file.  It is basically BSD + inconvenience.  I don't think it is a *bad* license, just that it is pointless, regardless of its popularity.

**Comment by StefanKarpinski** [comment]
I wasn't aware of the MPL history but given that I think that @stevengj is right that we should endorse the usage of MPL by having it as a LICENSE option.

**Comment by stevengj** [comment]
Of course, I notice that nowadays `Pkg.generate` lists only MIT, BSD, or ASL.  By the same argument, we should only list MIT, since the other two are effectively redundant.

**Comment by johnmyleswhite** [comment]
I don't think that's an accurate assessment of how many businesses view the relationship between MIT and ASL. The patent clause in the ASL is viewed as essential by some.

**Comment by stevengj** [comment]
Those who view it as essential can always edit the license file.

(Clearly, *we* don't think it is essential, or else we'd be using ASL for Julia.  Are businesses worried about Julia contributors suing them for patent infringement?  Have there ever been any cases of someone distributing MIT or BSD-licensed code and then suing people for patent infringement?  That's what the patent clause is about — protecting people from being tricked by a malicious software author who hypothetically releases MIT-licensed code but secretly retains patent rights.)

**Comment by Rory-Finnegan** [comment]
@stevengj I understand your desire not to have too many licenses people can use, particularly if they introduce potential conflicts between dependencies, however, I don't see how MPL does that. I tend to agree with what several people have mentioned that MPL provides a nice middle ground between LGPL and MIT. I also think MPL2 is a pretty reasonable license to recommend to someone wanting a copy left as it is easier for them to read, understand and apply (over Apache or GPL licenses). 

As an aside, we might want better support for adding custom licenses to Pkg.generate (maybe in a user level license template folder?). This way if people (or companies) have a preferred license they can just add it to Pkg.generate and use it for every package they create.

**Comment by stevengj** [comment]
@Rory-Finnegan, if someone wants a copyleft, then MPL is a bad license to recommend.  It is a copyleft + exceptions so huge that the copyleft restrictions are effectively a minor inconvenience.

**Comment by blakejohnson** [comment]
@stevengj I don't think the holes in MPL are as large as you think they are. Clause 1.10b of MPL2 seems to cover new files.

In any case, I don't understand the opposition to added convenience for popular licenses. Sure, I'd like to avoid promoting copyleft licenses since I find them to be a pain, but the patent thing is very relevant to industrial users.

**Comment by tkelman** [comment]
Anyway, https://github.com/JuliaLang/PkgDev.jl/pull/3 was merged to PkgDev.jl and we'll be removing Pkg.generate from master. If MPL is controversial or not well-liked, we can refrain from backporting it to release-0.4.

**Comment by stevengj** [comment]
@blakejohnson, 1.10b just means that you can't copy an MPL'ed function ("Covered Software") from an old file to a new file without the MPL following it.  As long as you put any *new* code in a new file, you are fine if the new code is proprietary.  This is the *whole point* of the "weaker copyleft" of the MPL: if the MPL extended to *new* code in new files that you linked to the old code, then it would be similar in effect to the GPL.

**Comment by stevengj** [comment]
I'm a little annoyed by JuliaLang/PkgDev.jl#3 getting merged.   PkgDev is also a JuliaLang project.   Doesn't the exact same discussion that occurred here also apply there?

**Comment by blakejohnson** [comment]
@stevengj I guess your point is that people can wrap all their new code in a proprietary library, release the modified MPL source with calls into their proprietary library and still satisfy the MPL. I get that. But programmers are lazy, and so they usually take the easier path of adding functionality in-place. That's been sufficient protection for me on a number of occasions.

In any case, I can't really pretend to champion the MPL. I would strongly suggest keeping ASL in the mix, though. An "implied" patent license with sparse case law support is going to be insufficient for most business legal departments. An explicit patent license is a nice bright line that makes lawyers happy.

**Comment by stevengj** [comment]
@blakejohnson, you don't have to put the new code into a library.  Just in a separate file.  I agree that this can be inconvenient, that's why I said it is basically BSD + inconvenience.  Hence not really a copyleft.

If you think explicit patent licenses are important to businesses, then are you arguing that Julia should switch to ASL?   And yet there are tons of examples of businesses, from Microsoft to Apple, happily using BSD and MIT-licensed code.

**Comment by iamed2** [comment]
@stevengj What we care about at Invenia is modifications/improvements to the code released under the license. Wrappers are fine. We want to allow for use by anyone while ensuring improvements to the specific code we've released are contributed back to the community, and are usable by us.

If you want to encourage other licenses over this one, do that. Have Pkg.generate only suggest licenses you prefer. Not supporting other common open-source licenses will just create annoyance for developers who have already decided to use them, it won't discourage them from using them.

**Comment by stevengj** [comment]
@iamed2, the MPL won't accomplish that.  They just need to put their new functionality into another file, and they don't need to share it with you.

In any case, no one is talking about "not supporting" other licenses.  You can edit the license file to be whatever you want.   The question is which licenses we suggest, which mainly matters for developers who are unsure about their license choice.

**Comment by iamed2** [comment]
@stevengj I don't see that including the license as an option implies suggesting it. The Pkg.generate(::AbstractString) error message can suggest any licenses you prefer, but still support the other licenses as options for the second argument.

**Comment by malmaud** [comment]
What about a compromise: Have `Pkg.generate` accept a wide variety of licenses, but make it clear in the function documentation and manual that it is recommended you one of the 'blessed' ones? If someone is generating a package and doesn't already know what license they want, the documentation is probably an equally instrument to suggest one to them then a technical restriction on license keywords accepted by `Pkg.generate`.

**Comment by iamed2** [comment]
@malmaud I would support that wholeheartedly!

**Comment by stevengj** [comment]
That seems reasonable to me.  (We still shouldn't accept licenses that are positively bad, like the "Artistic" license, although of course we can't stop people from choosing these manually, but an array of popular GPL-compatible free/open-source licenses is fine as long as we clearly recommend an extremely small subset.  I would tend to just recommend MIT as a default choice.)

**Comment by malmaud** [comment]
What about the "Popular Licenses" from http://opensource.org/licenses? +1 on MIT as the recommended choice, given that Julia itself is MIT.

**Comment by stevengj** [comment]
@malmaud, I would strongly urge leaving out the CDL and Eclipse licenses from that list, which are GPL-incompatible and hence fragment the free-software landscape.     I also think it's a bit confusing to include two BSD variants; 2-clause should be enough.   For GPL and LGPL, I would use the "v2 or later" variants, again in the interest of minimizing fragmentation.

**Comment by wildart** [comment]
I strongly disagree that a license choice should be limited. It would be more constructive to provide more licences and better information about them so a user could make an educated decision.

**Comment by stevengj** [comment]
License choice is not limited. You can edit the license file however you like. What we are discussing is the list of licenses that we support adding automatically via Pkg.generate. 

Supporting adding a license automatically is effectively an endorsement, even if we explicitly recommend only one. I emphatically believe that we should endorse only a small set of mutually compatible, well-tested licenses.

**Comment by johnmyleswhite** [comment]
Given the level of disagreement here, I now think the best thing to do is stick with the status quo.

**Comment by wildart** [comment]
A disagreement of @stevengj.

**Comment by johnmyleswhite** [comment]
Well, the notion that we should change the status quo is also an implicit disagreement with the status quo. And we did choose the licenses we offer now precisely for the endorsement reasons that Steven is mentioning. I am skeptical that this thread continuing will benefit the community.

**Comment by wildart** [comment]
I see a limitation when you compare automatic license generation vs manual license editing, especially when this change is reflected in repository history.

**Comment by stevengj** [comment]
@johnmyleswhite, the problem is that we haven't stuck with the status quo.  While we've been discussing this, people have been quietly changing PkgDev, which is where `Pkg.generate` will live starting in 0.5.

@wildart, `git commit --amend` solves that easily.

**Comment by wildart** [comment]
License parameter is required in `Pkg.generate`, so when a developer decides to a create package, it is a deliberate decision when three characters of a particular license label are typed. What if the package generator cannot provide a desirable license option? The generator faults with an error and the package is not created. Moreover, the generator enforces its limited choice of licenses on a person, because there is no option to not include license file. It is a limitation. I do not buy argument that the license can be fixed later, why bother to provide some license at all if it needs to be fixed later. So, this fault in a software functionality can be fixed either by adding more licenses so the developer has a better choice or letting the developer to provide his own license of choice.

In #4908, @IainNZ gave [a statistics on license usage](https://github.com/JuliaLang/julia/issues/4908#issuecomment-46769265). MIT was a predominantly used license. Why? Maybe because documentation suggests the following example: `Pkg.generate("FooBar","MIT")`. I bet many developers followed this example in creation of their first package. I would assume that some violated a licensing law, not deliberately, but because they just followed above example. Those three license characters could have been GPL, and we would have a majority of packages under GPL license. I appreciate knowledge of some community members on software licensing issues. Maybe, some could provide a legal advice, I do not know. Should we go and check every package for a possible license violation? 

I do not think that possibility of some future license violation should be a hindrance for expanding set of available licenses for automatic package template creation, especially when no code exist to violate any license (assuming that `generate` function is mostly used to create an empty packages).

**Comment by nalimilan** [comment]
It looks like we were reaching a consensus, and then the debate heated again. How about this, inspired from the proposal by  @malmaud above:
1) As currently, only a few licenses are shown in the docs for `Pkg.generate`, and we explain why it's better to use them (so that the package is fully compatible with the Julia ecosystem). The current list could be added one or two copyleft licenses (e.g. GPL2+, LGPL2+)
2) The docs also explain that any license listed at http://opensource.org/licenses/category can be specified. Then `Pkg.generate` downloads the license from that page (the URL can be built simply by pasting the license name to http://opensource.org/licenses/).

That way, we have the best of both worlds: no temptation to use dubious licenses when you're unsure, but full freedom when you know what you're going (e.g. porting already licensed code). How does that sound?

**Comment by stevengj** [comment]
@nalimilan, documented symbols for a few "endorsed" mutually compatible licenses (MIT, APL, BSD, MPL, GPL (v2+), LGPL (v2+)) that we install as `LICENSE.md` files with filled-in copyright lines, a recommendation to use MIT if you are unsure, and an option to download other licenses (as `LICENSE.txt`) from `opensource.org` sounds reasonable (the easiest thing to implement would be to just accept any URL that begins with `http://opensource.org/licenses/` and ends with `.txt`, so the user can copy-and-paste the "text-only" URL).

Note that, if you're porting already-licensed code, at minimum you probably have to edit the LICENSE file manually anyway in order to correct the copyright statement (Copyright *author*, *year*).

**Comment by nalimilan** [comment]
Sorry, now that I look at the actual implementation, a small detail makes this not work as I expected: I can't find any repository containing the licenses under the simple .txt form. Parsing the HTML page to extract the text wouldn't be robust.

Another solution is to ask for a file path, or open the default editor and ask the user to paste the license text. Creating the package without any initial license would be practical, but we shouldn't make it easy for people to publish packages without any license.

**Comment by stevengj** [comment]
A file path seems fine too.

**Comment by Rory-Finnegan** [comment]
+1 for adding custom license files from `Pkg.generate` (automated downloading just seems like an extra feature). It would be nice if the file could be copied to a shared folder with a name for future calls to `Pkg.generate`.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/PkgDev.jl/tree/master/res/licenses ?

**Comment by wildart** [comment]
https://developer.github.com/v3/licenses/

**Comment by nalimilan** [comment]
@wildart The list of licenses proposed by GitHub is interesting, but it isn't exhaustive either, so it doesn't help that much IMHO.

**Pull request closed without merging**
