### PR TITLE
Do not put the stdlib path in JULIA_LOAD_PATH when testing or building

### PR DESCRIPTION
**Pull request by KristofferC**
By having the stdlib path in the JULIA_LOAD_PATH when building or testing packages can load stdlibs when that happens without declaring a dependency on them. Moving out stdlibs from Base would then be breaking.

This fixes it, and also adds the needed test-deps to the stdlibs in case someone wants to use Pkg to test stdlibs (one of the Pkg tests does that).

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
This looks good to me. Presumably this still allows `pkg> test` to work for various packages? It's a little weird to have to always put `Test` in the test deps. But treating it specially feels a bit icky as well.

**Comment by StefanKarpinski** [comment]
Maybe if there's no test section at all, we could default to assuming it includes `Test`?

**Comment by KristofferC** [comment]
That seems very arbitrary. We don't e.g. put `using Test` automatically into the `runtests.jl` file if it doesn't exist there already. If the package generator put this automatically, there is nothing you have to change, so I'm not sure what the big deal is. If we want Test to be special it should probably be in Base.

**Comment by KristofferC** [comment]
This doesn't work well yet, there is a problem now when an stdlib wants to use another stdlib which is not part of the dependency graph. Have to take the stdlib deps into account when resolving and print their deps to the manifest.

So don't merge.

**Comment by KristofferC** [comment]
Doesn't have to be in the beta.

**Comment by JeffBezanson** [comment]
What's the status of this? Should it be retriaged?

**Comment by StefanKarpinski** [comment]
We should probably still do this, right, @KristofferC?

**Comment by KristofferC** [comment]
Yes, I'll work on it tomorrow.

**Comment by KristofferC** [comment]
Ok, I fixed this but then I realized this is impossible to fix from Pkgs side. Without `@stdlib` in `LOAD_PATH` code loading will never find the stdlibs since their location doesn't comply with the version slug scheme. And if they are in the `LOAD_PATH`, that means that we can always load them in top-level (which is what test files do).

In other words, there is no way Pkg can allow loading only some stdlibs, it is all or nothing.

**Comment by fredrikekre** [comment]
Can we version them and put symlinks in the slug directories?

**Comment by KristofferC** [comment]
When should that happen? Also, version is not enough, would need to compute the `git-tree-sha` for every stdlib when julia is built. Not hard, but a bit annoying. The bonus with that is that we actually record what `git-tree-sha` was used so we can potentially instantiate a Manifest with stdlibs in the future.

**Comment by KristofferC** [comment]
Ready for review.

What this does is that 

1) It splits up some test helpers to be more specific to reduce the test dependencies the stdlibs have.
2) One can no longer load stdlibs without directly depending on them when testing / building.
3) Point 2) necessitated putting in paths to stdlibs in the temporary Manifest that is generated when testing/building so that code loading can find stdlibs.
4) There are no more "dangling references" in the Manifest. The full dependency graph (including stdlibs and their deps are put in).

**Comment by KristofferC** [comment]
Will put this into a PR from Pkg since things have changed there and this needs to be updated to take that into account.

**Pull request closed without merging**
