### PR TITLE
Don't export Dates.adjust

### LINKED ISSUE #52746: Is `Dates.adjust` supposed to be exported?
Is `Dates.adjust` supposed to be exported? It is exported on released versions but it has no docstring and is not mentioned in the [Dates manual](https://docs.julialang.org/en/v1/stdlib/Dates/).

```jl
adjust(df::Dates.DateFunction, start, step, limit)
adjust(func::Function, start; step, limit)
```

### PR DESCRIPTION
**Pull request by jariji**
```jl
adjust(df::Dates.DateFunction, start, step, limit)
adjust(func::Function, start; step, limit)
```

`Dates.adjust` has been exported for a while, but has no docstring and is not in the manual in 1.10.

I've asked on Slack, [GitHub](https://github.com/JuliaLang/julia/issues/52746), and [Discourse](https://discourse.julialang.org/t/who-uses-dates-adjust/109030) if anybody is using it, and nobody piped up.

Since we're adding docstrings to everything for 1.11, it seems like a good time to remove the `adjust` export.

Resolves https://github.com/JuliaLang/julia/issues/52746.

### CODE REVIEW

**Comment by LilithHafner** [comment]
@nanosoldier `runtests()`

**Comment by LilithHafner** [comment]
This has never been part of the public API because the public API is defined to include only things in the manual.

**Comment by mbauman** [comment]
There is some usage in the ecosystem ([Quantlib](https://github.com/pazzo83/QuantLib.jl/blob/v0.1.1/src/time/schedule.jl#L145), [QDates](https://github.com/antimon2/QDates.jl/blob/v0.3.0/src/adjusters.jl#L47), [OpenSSL](https://github.com/JuliaWeb/OpenSSL.jl/blob/3a20f1950d3e05712959dce85b2c5bf2a43bf21b/src/OpenSSL.jl#L1751), [Miletus](https://github.com/JuliaComputing/Miletus.jl/blob/v1.2.1/src/daycounts.jl#L257), but I think only QuantLib relies upon it being exported.

**Comment by nanosoldier** [comment]
The package evaluation job [you requested](https://github.com/JuliaLang/julia/pull/53027#issuecomment-1910570976) has completed - possible new issues were detected.
The [**full report**](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/1343ad0_vs_d741c24/report.html) is available.

**Comment by LilithHafner** [comment]
Nanosoldier revealed two new failures:

OpenSSL extends and reexports `adjust`. Most of it's usage does not depend on adjust being exported. The only tests that fail are the explicit "does OpenSSL.adjust work" tests, but the tests are failfast so there could be more that fail.

Dates itself fails because it expects the symbol `adjust` to be public & undocumented but this unbreaks that test (this failure should come up this this PR's CI) 

QuantLib did not come up in PkgEval because it is skipped. (no updates since 2020, 3 monthly downloads according to JuliaHub, 0 dependants)

**Review by quinnj — APPROVED** [review]
LGTM assuming we get Dates tests fixed as @LilithHafner mentioned

**Comment by jam-khan** [comment]
I have added docstrings and made changes to runtests.jl for  **adjust**  as part of issue #52725 in PR #52914

**Comment by DilumAluthge** [comment]
This PR broke the `doctest` job in CI.

**Pull request merged**
