### PR TITLE
RFC: Fix behaviour of sqrtm on UpperTriangular matrices

### PR DESCRIPTION
**Pull request by mfasi**
`sqrtm` does not automatically promote the work matrix to a complex type if any of the elements on the diagonal is negative. An example of the issue is

```
A = UpperTriangular([-1 2; 0 3.]); sqrtm(A)
```

### CODE REVIEW

**Comment by andreasnoack** [comment]
Could you also add a test for this?

**Comment by mfasi** [comment]
@andreasnoack Thank you, I added a few tests which should achieve complete line coverage.

**Comment by andreasnoack** [comment]
Thanks. Just a small detail. We are moving towards using `≈` instead of `test_approx_eq` so would you change the tests to something like `@test sqrtm(Atn) |> t->t*t ≈ Atn`.

**Comment by mfasi** [comment]
I tried to use `≈` but it does not seem to be defined. Should I import something in the test file? The symbol I'm using should be `U+2248`

**Comment by andreasnoack** [comment]
which version of Julia are you using?

**Comment by mfasi** [comment]
My current version was:
```
Version 0.4.0-dev+6561 (2015-08-09 23:36 UTC)
Commit 5505cf8* (2 days old master)
```
Now I am rebasing the branch on master, but I doubt things will change -- unless this symbol has been there for less than 2 days. Anyway, it really looks like it's just an issue of mine, the tests aparently work fine on AppVeyor and Travis.

**Comment by yuyichao** [comment]
> unless this symbol has been there for less than 2 days

This is exactly what happend. https://github.com/JuliaLang/julia/pull/12472

**Comment by mfasi** [comment]
@yuyichao Thank you, it works now.

**Comment by andreasnoack** [comment]
Great. Thanks for fixing this.

**Pull request merged**
