### PR TITLE
[CompilerSupportLibraries_jll] Upgrade to v1.0.5

### LINKED ISSUE #48187: Julia 1.8.4, 1.8.5 and 1.9.0-beta3 crash with XGBoost.jl and LIBSVM.jl under Windows 11
I am using LIBSVM.jl v0.8.0, and XGBoost.jl v2.2.0, under Windows 11.

It works fine with Julia 1.8.3:

```
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161 (2022-11-14 20:14 UTC)
Platform Info:
OS: Windows (x86_64-w64-mingw32)
CPU: 16 × Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
Threads: 8 on 16 virtual cores
Environment:
JULIA_EDITOR = code
JULIA_NUM_THREADS = 8
```

But when I uses Julia 1.8.4:

```
julia> versioninfo()
Julia Version 1.8.4
Commit 00177ebc4f (2022-12-23 21:32 UTC)
Platform Info:
OS: Windows (x86_64-w64-mingw32)
CPU: 16 × Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
Threads: 8 on 16 virtual cores
Environment:
JULIA_EDITOR = code
JULIA_NUM_THREADS = 8
```
running any function of LIBSVM.jl or XGBoost.jl kills my Julia session, for instance after doing:
```
using XGBoost
(X, y) = (randn(100,4), randn(100))
```
then the command below;
`bst = xgboost((X, y))`

kills the process and closes directly Julia without any printed error in the terminal.

I created a thread at [Discourse](https://discourse.julialang.org/t/issue-with-xgboost-jl-and-libsvm-jl-when-julia-1-8-4/92396/2) but got no solution. 

I already opened two issues: [https://github.com/JuliaML/LIBSVM.jl/issues/95](https://github.com/JuliaML/LIBSVM.jl/issues/95) and [https://github.com/dmlc/XGBoost.jl/issues/153](https://github.com/dmlc/XGBoost.jl/issues/153). The second raised unexplained error on windows.

Both  LIBSVM.jl and XGBoost.jl  wrap C/C++ code; this may be linked.

Did somebody observe the same problem and know what could happen?

### LINKED ISSUE #48573: Crash calling Gmsh on 1.8.5 and 1.9beta3
I am running Windows 11 and tried:

```
1.8.3
1.8.5
1.9.0-beta3
```

Full versioninfo for 1.9:

'''
Julia Version 1.9.0-beta3
Commit 24204a7344 (2023-01-18 07:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 16 virtual cores
'''

The following snippet works on 1.8.3 and earlier but crashes to the command shell on 1.8.5 and 1.9.0-beta3 (perhaps related to the fix for [https://discourse.julialang.org/t/glmakie-and-plots-fail-to-precompile-under-julia-1-8-4/92087]()?

```
using Gmsh

radius = 1.0
delta = 0.25

s = """
lc = $delta;

Point(1)={0,0,0,lc};
Point(2)={$radius,0,0,lc};
Point(3)={0,$radius,0,lc};
Point(4)={-$radius,0,0,lc};
Point(5)={0,-$radius,0,lc};
Point(6)={0,0,$radius,lc};
Point(7)={0,0,-$radius,lc};

Circle(1)={2,1,3};
Circle(2)={3,1,4};
Circle(3)={4,1,5};
Circle(4)={5,1,2};
Circle(5)={6,1,3};
Circle(6)={3,1,7};
Circle(7)={7,1,5};
Circle(8)={5,1,6};

Line Loop(1)={-1,-6,-7,-4};
Line Loop(2)={1,-5,-8,4};
Line Loop(3)={-2,-3,7,6};
Line Loop(4)={2,3,8,5};

Ruled Surface(1)={1} In Sphere{1};
Ruled Surface(2)={2} In Sphere{1};
Ruled Surface(3)={3} In Sphere{1};
Ruled Surface(4)={4} In Sphere{1};
"""

fn = tempname()
io = open(fn, "w")
try
    print(io, s)
finally
    close(io)
end
fno = fn * ".msh"

gmsh.initialize()
gmsh.option.setNumber("Mesh.MshFileVersion",2)
gmsh.open(fn)
gmsh.model.mesh.generate(2)
gmsh.write(fno)
gmsh.finalize()
```

The crash happens when calling 'generate'. I do not receive any error message or stack when this happens.

### LINKED ISSUE #48907: EXCEPTION_ACCESS_VIOLATION in FastTransforms tests
See the run https://github.com/JuliaApproximation/FastTransforms.jl/actions/runs/4341886418/jobs/7582033357, the error message is:
```julia
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77e352b9 -- RtlGetCurrentServiceSessionId at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
in expression starting at D:\a\FastTransforms.jl\FastTransforms.jl\test\libfasttransformstests.jl:5
RtlGetCurrentServiceSessionId at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlConstructCrossVmMutexPath at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
free at C:\Windows\System32\msvcrt.dll (unknown line)
free_team at /workspace/srcdir/gcc-12.1.0/libgomp\team.c:237 [inlined]
gomp_team_end at /workspace/srcdir/gcc-12.1.0/libgomp\team.c:1005
ft_bfmmf at C:\Users\runneradmin\.julia\artifacts\2f4394502c5b9c9863425335a6140d4bfd02153b\bin\libfasttransforms.dll (unknown line)
* at D:\a\FastTransforms.jl\FastTransforms.jl\src\libfasttransforms.jl:892 [inlined]
test_1d_plans at D:\a\FastTransforms.jl\FastTransforms.jl\test\libfasttransformstests.jl:62
jl_fptr_args at C:/workdir/src\gf.c:2138
_jl_invoke at C:/workdir/src\gf.c:2377 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
jl_apply at C:/workdir/src\julia.h:1843 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:215
eval_stmt_value at C:/workdir/src\interpreter.c:166 [inlined]
eval_body at C:/workdir/src\interpreter.c:594
eval_body at C:/workdir/src\interpreter.c:522
eval_body at C:/workdir/src\interpreter.c:522
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:750
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:906
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:850
ijl_toplevel_eval at C:/workdir/src\toplevel.c:915 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:965
eval at .\boot.jl:368 [inlined]
include_string at .\loading.jl:1428
jl_fptr_args at C:/workdir/src\gf.c:2138
_jl_invoke at C:/workdir/src\gf.c:2358 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
_include at .\loading.jl:1488
include at .\client.jl:476
unknown function (ip: 10660535)
_jl_invoke at C:/workdir/src\gf.c:2358 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
jl_apply at C:/workdir/src\julia.h:1843 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:215
eval_stmt_value at C:/workdir/src\interpreter.c:166 [inlined]
eval_body at C:/workdir/src\interpreter.c:594
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:750
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:906
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:850
ijl_toplevel_eval at C:/workdir/src\toplevel.c:915 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:965
eval at .\boot.jl:368 [inlined]
include_string at .\loading.jl:1428
jl_fptr_args at C:/workdir/src\gf.c:2138
_jl_invoke at C:/workdir/src\gf.c:2358 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
_include at .\loading.jl:1488
include at .\client.jl:476
unknown function (ip: 10660535)
_jl_invoke at C:/workdir/src\gf.c:2377 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
jl_apply at C:/workdir/src\julia.h:1843 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:215
eval_stmt_value at C:/workdir/src\interpreter.c:166 [inlined]
eval_body at C:/workdir/src\interpreter.c:594
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:750
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:906
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:850
ijl_toplevel_eval at C:/workdir/src\toplevel.c:915 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:965
eval at .\boot.jl:368 [inlined]
exec_options at .\client.jl:276
_start at .\client.jl:522
jfptr__start_41558.clone_1 at C:\hostedtoolcache\windows\julia\1.8.5\x86\lib\julia\sys.dll (unknown line)
_jl_invoke at C:/workdir/src\gf.c:2358 [inlined]
ijl_apply_generic at C:/workdir/src\gf.c:2559
jl_apply at C:/workdir/src\julia.h:1843 [inlined]
true_main at C:/workdir/src\jlapi.c:575
jl_repl_entrypoint at C:/workdir/src\jlapi.c:719
jl_load_repl at C:/workdir/cli\loader_lib.c:471
mainCRTStartup at C:/workdir/cli\loader_exe.c:59
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlGetFullPathName_UEx at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlGetFullPathName_UEx at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 94885190 (Pool: 94868039; Big: 17151); GC: 137
ERROR: LoadError: Package FastTransforms errored during testing
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types C:\hostedtoolcache\windows\julia\1.8.5\x86\share\julia\stdlib\v1.8\Pkg\src\Types.jl:67
 [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
   @ Pkg.Operations C:\hostedtoolcache\windows\julia\1.8.5\x86\share\julia\stdlib\v1.8\Pkg\src\Operations.jl:1813
 [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Vector{String}, test_args::Cmd, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool, kwargs::Base.Pairs{Symbol, IOContext{Base.PipeEndpoint}, Tuple{Symbol}, NamedTuple{(:io,), Tuple{IOContext{Base.PipeEndpoint}}}})
   @ Pkg.API C:\hostedtoolcache\windows\julia\1.8.5\x86\share\julia\stdlib\v1.8\Pkg\src\API.jl:434
 [4] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::IOContext{Base.PipeEndpoint}, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:julia_args, :coverage, :force_latest_compatible_version), Tuple{Vector{String}, Bool, Bool}}})
   @ Pkg.API C:\hostedtoolcache\windows\julia\1.8.5\x86\share\julia\stdlib\v1.8\Pkg\src\API.jl:156
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:julia_args, :coverage, :force_latest_compatible_version), Tuple{Vector{String}, Bool, Bool}}})
   @ Pkg.API C:\hostedtoolcache\windows\julia\1.8.5\x86\share\julia\stdlib\v1.8\Pkg\src\API.jl:171
 [6] top-level scope
   @ D:\a\_actions\julia-actions\julia-runtest\latest\test_harness.jl:15
 [7] include(fname::String)
   @ Base.MainInclude .\client.jl:476
 [8] top-level scope
   @ none:1
in expression starting at D:\a\_actions\julia-actions\julia-runtest\latest\test_harness.jl:7
Error: Process completed with exit code 1.
```
The tests error only on Windows latest for Julia v1.8.5, and pass on Linux and macOS (although the other tests on Windows get cancelled because of this error). The previous CI run from 3 months back did run successfully on Windows latest (for Julia v1.8.3 and v1.7), so this appears to be a regression. Unfortunately, I don't have access to a Windows system to look into this.

### PR DESCRIPTION
**Pull request by giordano**
This build includes a fix from GCC 12.2 for a bug in libgomp 12.1 which was causing frequent crashes on Windows in third-party libraries.

Quoting from https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/313

> Ref: https://github.com/JuliaLang/julia/issues/48187.  @jd-foster found that this was due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105745, after applying the patch to our GCC 12.1 build @tylerjthomas9 reported that the new libgomp made tests of `XGBoost.jl` and `LIBSVM.jl` pass.
> 
> Other related issues:
> 
> * https://github.com/darktable-org/darktable/issues/11889
> * https://github.com/msys2/MINGW-packages/issues/11729

Fix #48187, fix #48907, fix #48573.

### CODE REVIEW

**Comment by mkitti** [comment]
What is the test procedure?

**Comment by giordano** [comment]
@mkitti confirmed on slack that with this branch XGBoost doesn't crash and all tests here are green, so I'm going to merge this PR so that people can use again external libraries on Windows, at least on nightly until 1.9.2 is released.

**Comment by simsurace** [comment]
Will this definitely land on 1.9.2? I don't see any tag yet.

**Comment by ViralBShah** [comment]
> Will this definitely land on 1.9.2? I don't see any tag yet.

This PR does have the backport 1.9 label.

**Pull request merged**
