### PR TITLE
Fix doc README link

### PR DESCRIPTION
**Pull request by omus**
A legitimate documentation fix which I'm using to test https://github.com/JuliaLang/julia/pull/27356

### CODE REVIEW

**Comment by fredrikekre** [comment]
I don't think Travis and AV runs unless the base branch is `master` or `release-`

**Comment by omus** [comment]
> I don't think Travis and AV runs unless the base branch is master or release-

Thanks. I missed that. I adjusted #27356 temporarily so I can actually test the new behaviour.

**Comment by omus** [comment]
At this point the changes from #27356 have AppVeyor and Travis CI working as intended. Re-running to test the Circle CI changes.

**Comment by kshyatt** [comment]
Can we re-run CI on this? Is there any reason this can't be merged?

**Comment by omus** [comment]
Thanks for the reminder. I rebased to re-trigger the CI. Should be ready to go.

**Comment by omus** [comment]
I keep forgetting about this PR. I re-checked the link and rebased the changes. Going to merge right away.

**Pull request merged**
