### PR TITLE
Use typed-zero in sign() implementation

### LINKED ISSUE #34914: sign(::Float64) has more complicated Julia IR in v1.3 than v1.2
The typed/optimized IR for `sign(::Float64)` is much more complicated in v1.3 than it was in v1.2. (Despite that, though, LLVM does simplify both down to the same LLVM IR, so I don't suppose there's any real performance issue — it just made reading through a long function a bit harder during debugging of some of my own code since I initially didn't understand where the large floating point constants were coming from.)

```julia
# In v1.2
julia> @code_typed sign(2.0)
CodeInfo(
1 ─ %1  = Base.lt_float(x, 0.0)::Bool
│   %2  = Base.eq_float(x, 0.0)::Bool
│   %3  = Base.and_int(%2, true)::Bool
│   %4  = Base.and_int(%3, false)::Bool
│   %5  = Base.or_int(%1, %4)::Bool
│   %6  = Base.lt_float(0.0, x)::Bool
│   %7  = Base.eq_float(0.0, x)::Bool
│   %8  = Base.and_int(%7, false)::Bool
│   %9  = Base.or_int(%6, %8)::Bool
│   %10 = Base.ifelse(%9, 1.0, x)::Float64
│   %11 = Base.ifelse(%5, -1.0, %10)::Float64
└──       return %11
) => Float64

julia> @code_llvm debuginfo=:none sign(2.0)

define double @julia_sign_16056(double) {
top:
  %1 = fcmp uge double %0, 0.000000e+00
  %2 = fcmp ule double %0, 0.000000e+00
  %3 = select i1 %2, double %0, double 1.000000e+00
  %4 = select i1 %1, double %3, double -1.000000e+00
  ret double %4
}
```

```julia
# In v1.3
julia> @code_typed sign(2.0)                                                                                                                                                                                       
CodeInfo(                                                                                                                                                                                                          
1 ─ %1  = Base.sitofp(Float64, 0)::Float64                                                                                                                                                                         
│   %2  = Base.lt_float(x, %1)::Bool                                                                                                                                                                               
│   %3  = Base.eq_float(x, %1)::Bool                                                                                                                                                                               
│   %4  = Base.lt_float(%1, 9.223372036854776e18)::Bool                                                                                                                                                            
│   %5  = Base.and_int(%3, %4)::Bool                                                                                                                                                                               
│   %6  = Base.fptosi(Int64, %1)::Int64                                                                                                                                                                            
│   %7  = Base.slt_int(%6, 0)::Bool                                                                                                                                                                                
│   %8  = Base.and_int(%5, %7)::Bool                                                                                                                                                                               
│   %9  = Base.or_int(%2, %8)::Bool                                                                                                                                                                                
│   %10 = Base.sitofp(Float64, 0)::Float64                                                                                                                                                                         
│   %11 = Base.lt_float(%10, x)::Bool                                                                                                                                                                              
│   %12 = Base.eq_float(%10, x)::Bool                                                                                                                                                                              
│   %13 = Base.eq_float(%10, 9.223372036854776e18)::Bool                                                                                                                                                           
│   %14 = Base.fptosi(Int64, %10)::Int64                                                                                                                                                                           
│   %15 = Base.slt_int(0, %14)::Bool                                                                                                                                                                               
│   %16 = Base.or_int(%13, %15)::Bool                                                                                                                                                                              
│   %17 = Base.and_int(%12, %16)::Bool                                                                                                                                                                             
│   %18 = Base.or_int(%11, %17)::Bool                                                                                                                                                                              
│   %19 = Base.ifelse(%18, 1.0, x)::Float64
│   %20 = Base.ifelse(%9, -1.0, %19)::Float64
└──       return %20                                
) => Float64                                        

julia> @code_llvm debuginfo=:none sign(2.0)

define double @julia_sign_17326(double) {
top:                                                
  %1 = fcmp uge double %0, 0.000000e+00
  %2 = fcmp ule double %0, 0.000000e+00
  %3 = select i1 %2, double %0, double 1.000000e+00
  %4 = select i1 %1, double %3, double -1.000000e+00 
  ret double %4                                     
}                                                   
```

I'll follow up shortly with a PR which proposes a change that leads to simpler Julia IR.

### PR DESCRIPTION
**Pull request by jmert**
This PR fixes #34914: 
```julia
# With PR
julia> @code_typed sign(2.0)
CodeInfo(
1 ─ %1 = Base.lt_float(x, 0.0)::Bool
│   %2 = Base.lt_float(0.0, x)::Bool
│   %3 = Base.ifelse(%2, 1.0, x)::Float64
│   %4 = Base.ifelse(%1, -1.0, %3)::Float64
└──      return %4
) => Float64

julia> @code_llvm debuginfo=:none sign(2.0)

define double @julia_sign_18479(double) {
top:
  %1 = fcmp uge double %0, 0.000000e+00
  %2 = fcmp ule double %0, 0.000000e+00
  %3 = select i1 %2, double %0, double 1.000000e+00
  %4 = select i1 %1, double %3, double -1.000000e+00
  ret double %4
}
```
Previously, the type mismatch in the comparisons meant that `sign(::Furlong)` from the test helper didn't work, so I've used that as a regression test.

### CODE REVIEW

**Comment by yuyichao** [comment]
How does this affect types where `zero` allocates?

I don't know about `BigFloat` but at least `BigInt` seems to be calling a specialized comparison function when comparing to machine precision numbers (and `BigFloat` could in principle do the same)

**Comment by jmert** [comment]
It looks like you're right for both `BigInt` and `BigFloat` — they end up allocating more. I'm not sure what the right answer is. Presumably it'd be nice to have type stability for comparison of other non-standard number types, but e.g. `Unitful` defines it's own `sign` implementation to avoid comparing unitful and dimensionless number as would happen with `Base`'s current implementation.

**Comment by JeffBezanson** [comment]
Could we add global constants for one and zero BigInts so we don't need to allocate a new one on each call? Harder to do for BigFloat of course due to variable precision.

**Comment by JeffBezanson** [comment]
Then again, BigInt and BigFloat should just have their own implementations of `sign`.

**Comment by jmert** [comment]
Following Jeff's suggestion that `BigInt` and `BigFloat` could both use their own implementations...

The performance of `sign` on my computer with the version on master:
```julia
julia> @btime sign($(big"-3"))
  176.355 ns (8 allocations: 160 bytes)
-1

julia> @btime sign($(big"0"))
  173.466 ns (8 allocations: 160 bytes)
0

julia> @btime sign($(big"3"))
  177.679 ns (8 allocations: 160 bytes)
1

julia> @btime sign($(big"-3.0"))
  218.523 ns (8 allocations: 448 bytes)
-1.0

julia> @btime sign($(big"-0.0"))
  221.188 ns (8 allocations: 448 bytes)
-0.0

julia> @btime sign($(big"0.0"))
  220.473 ns (8 allocations: 448 bytes)
0.0

julia> @btime sign($(big"3.0"))
  224.199 ns (8 allocations: 448 bytes)
1.0
```

Using this PR, which now adds specialized versions of `sign` for both `BigInt` and `BigFloat`:
```julia
julia> @btime sign($(big"-3"))
  90.159 ns (4 allocations: 80 bytes)
-1

julia> @btime sign($(big"0"))
  5.039 ns (0 allocations: 0 bytes)
0

julia> @btime sign($(big"3"))
  47.653 ns (2 allocations: 40 bytes)
1

julia> @btime sign($(big"-3.0"))
  97.525 ns (4 allocations: 224 bytes)
-1.0

julia> @btime sign($(big"-0.0"))
  11.553 ns (0 allocations: 0 bytes)
-0.0

julia> @btime sign($(big"0.0"))
  11.834 ns (0 allocations: 0 bytes)
0.0

julia> @btime sign($(big"3.0"))
  65.026 ns (2 allocations: 112 bytes)
1.0
```

**Comment by jmert** [comment]
Well, the CI errors all look real — I was using `Revise` to test the changes, but upon building locally, I get the same bootstrap error. I'll have to investigate further.

**Comment by jmert** [comment]
Fixed locally, so we'll see if this now passes CI again.

For the record, the issue was that I hadn't imported `Base.sign` before extending the methods, so that caused `Base.sign` to be shadowed within `Base.GMP` and `Base.MPFR`. I'm not sure why Revise was letting me get away with not importing first, so maybe that's a bug that should be reproduced and reported in Revise.

**Comment by jmert** [comment]
Bump.

**Comment by jmert** [comment]
Bump

**Pull request merged**
