### PR TITLE
Change llvmcall ABI representation for Float16

### PR DESCRIPTION
**Pull request by thomasfaingnaert**
When wrapping LLVM intrinsics using `ccall(..., llvmcall, ...)`, `Float16`s are represented as LLVM's `i16` instead of `half`.
This PR changes the representation to `half`, but only for the llvmcall calling convention.
As such, this shouldn't break anything.

Example:
```julia
for T = [Float16, NTuple{2, Float16}, NTuple{2, VecElement{Float16}}]
    @eval foo(x) = ccall("extern foo", llvmcall, $T, ($T,), x)
    code_llvm(foo, Tuple{T})
end
```

Before patch:
```llvm
;  @ REPL[1]:2 within `foo'
define i16 @julia_foo_17018(i16) {
top:
  %1 = call i16 @foo(i16 zeroext %0)
  ret i16 %1
}

;  @ REPL[1]:2 within `foo'
define [2 x i16] @julia_foo_17020([2 x i16] addrspace(11)* nocapture nonnull readonly dereferenceable(4)) {
top:
  %.elt = getelementptr inbounds [2 x i16], [2 x i16] addrspace(11)* %0, i64 0, i64 0
  %.unpack = load i16, i16 addrspace(11)* %.elt, align 2
  %1 = insertvalue [2 x i16] undef, i16 %.unpack, 0
  %.elt3 = getelementptr inbounds [2 x i16], [2 x i16] addrspace(11)* %0, i64 0, i64 1
  %.unpack4 = load i16, i16 addrspace(11)* %.elt3, align 2
  %2 = insertvalue [2 x i16] %1, i16 %.unpack4, 1
  %3 = call [2 x i16] @foo([2 x i16] %2)
  ret [2 x i16] %3
}

;  @ REPL[1]:2 within `foo'
define <2 x i16> @julia_foo_17021(<2 x i16>) {
top:
  %1 = call <2 x i16> @foo(<2 x i16> %0)
  ret <2 x i16> %1
}
```

After patch:
```llvm
;  @ REPL[1]:2 within `foo'
define i16 @julia_foo_16991(i16) {
top:
  %1 = bitcast i16 %0 to half
  %2 = call half @foo(half zeroext %1)
  %3 = bitcast half %2 to i16
  ret i16 %3
}

;  @ REPL[1]:2 within `foo'
define [2 x i16] @julia_foo_16993([2 x i16] addrspace(11)* nocapture nonnull readonly dereferenceable(4)) {
top:
  %.elt = bitcast [2 x i16] addrspace(11)* %0 to half addrspace(11)*
  %.unpack = load half, half addrspace(11)* %.elt, align 2
  %1 = insertvalue [2 x half] undef, half %.unpack, 0
  %.elt3 = getelementptr inbounds [2 x i16], [2 x i16] addrspace(11)* %0, i64 0, i64 1
  %2 = bitcast i16 addrspace(11)* %.elt3 to half addrspace(11)*
  %.unpack4 = load half, half addrspace(11)* %2, align 2
  %3 = insertvalue [2 x half] %1, half %.unpack4, 1
  %4 = call [2 x half] @foo([2 x half] %3)
  %.fca.0.extract = extractvalue [2 x half] %4, 0
  %5 = bitcast half %.fca.0.extract to i16
  %.fca.1.extract = extractvalue [2 x half] %4, 1
  %6 = bitcast half %.fca.1.extract to i16
  %.fca.0.insert = insertvalue [2 x i16] undef, i16 %5, 0
  %.fca.1.insert = insertvalue [2 x i16] %.fca.0.insert, i16 %6, 1
  ret [2 x i16] %.fca.1.insert
}

;  @ REPL[1]:2 within `foo'
define <2 x i16> @julia_foo_16994(<2 x i16>) {
top:
  %1 = bitcast <2 x i16> %0 to <2 x half>
  %2 = call <2 x half> @foo(<2 x half> %1)
  %3 = bitcast <2 x half> %2 to <2 x i16>
  ret <2 x i16> %3
}
```

// cc @maleadt

### CODE REVIEW

**Comment by vchuravy** [comment]
Thank you for this PR. Sadly this will likely run I to the same issue as https://github.com/JuliaLang/julia/pull/26381#issuecomment-371693243 

On LLVM backends that don't support Float16 we can't issue half instructions :/

**Comment by thomasfaingnaert** [comment]
@vchuravy Hmm, that's unfortunate :( I guess I'll revert the implementation of https://github.com/JuliaGPU/CUDAnative.jl/pull/494 back to `Base.llvmcall`, then?

**Comment by maleadt** [comment]
(only gave this a quick look so might have missed something)

> Sadly this will likely run I to the same issue as [#26381 (comment)](https://github.com/JuliaLang/julia/pull/26381#issuecomment-371693243)

I don't think this matters here, because the change is only for `ccall(llvmcall)` which we don't use to implement Float16 functionality with for exactly that reason. It does matter for CUDAnative though, were we do want to use such intrinsics (in GPU-specific code paths). For those intrinsics, this change is a necessity because passing a Float16 as an i16 (per Julia conventions) to intrinsics excepting a half triggers an LLVM assertion.

@vtjnash A while back we discussed another mismatch between how Julia generates code and what LLVM expects, do you still remember what that was (or know of other cases)?

**Comment by vchuravy** [comment]
> For those intrinsics, this change is a necessity because passing a Float16 as an i16 (per Julia conventions) to intrinsics excepting a half triggers an LLVM assertion.

Right, after talking to Tim, I think this should be fine. If you are calling a Float16 LLVM intrinsic on a platform that doesn't support Float16 that's your fault :P 
Makes testing this a bit harder, but adding a end-to-end test in `test/llvmpasses` would be great.

**Comment by vtjnash** [comment]
We talked about pointers, then realized the issue was with using Ptr instead of Ref. We talked about addrspace, which we realized meant  we need attributes.

This SGTM.

**Comment by thomasfaingnaert** [comment]
@vchuravy Added some basic tests. Is this what you had in mind?

**Comment by thomasfaingnaert** [comment]
Hmm, it seems that CI failed twice in a row with this test https://github.com/JuliaLang/julia/blob/f814301bd9503e243276b356d0cdbfcaa5ae0b8a/test/backtrace.jl#L239 on win32. But that test seems totally unrelated to this PR. Is that test known to be flaky, or did I actually break it?

**Review by vchuravy — APPROVED** [review]
known to be flaky #33877

**Pull request merged**
