### PR TITLE
Unbreak cfunction when running in imaging mode with MCJIT

### LINKED ISSUE #12246: Precompilation fails with libuv assertion with MCJIT
I've been trying to precomplie modules, but get stuck on assert in libuv (in the childprocess)
using master julia and bundled libuv version
I tried both `compile(:Gadfly)` and a fresh empty package but with the same error:
```
julia> Base.compile(:Dummy)
julia: src/unix/stream.c:1442: uv_read_start: Assertion `alloc_cb' failed.

signal (6): Aborted
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x7f869d6513a7)
unknown function (ip: 0x7f869d651452)
uv_read_start at /home/bjorn/Programming/julia/deps/libuv/src/unix/stream.c:1441
unknown function (ip: 0x7f86a0246b7b)
unknown function (ip: 0x7f86a0246336)
unknown function (ip: 0x7f86a0246087)
unknown function (ip: 0x7f86a0246013)
jl_apply_generic at /home/bjorn/Programming/julia/src/gf.c:1677
unknown function (ip: 0x7f86a024a08e)
jl_apply at /home/bjorn/Programming/julia/src/julia.h:1271
jl_eh_restore_state at /home/bjorn/Programming/julia/src/julia.h:1357
process_options at ./client.jl:284
_start at ./client.jl:411
unknown function (ip: 0x7f869b5e7b39)
jl_apply_generic at /home/bjorn/Programming/julia/src/gf.c:1679
unknown function (ip: 0x401a67)
unknown function (ip: 0x40166f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x4016b9)
unknown function (ip: (nil))
"/home/bjorn/.julia/lib/v0.4/Dummy.ji"
```

Despite the error, `compile` returns the (nonexistent) cache file without throwing exception ( I think this should be changed as well.) I tried to just run
`./julia --eval "while \!eof(STDIN); eval(Main, deserialize(STDIN)); end" < testser`
where testser just is serialized print statement, which seems to work, but I don't really know what to try next.

### PR DESCRIPTION
**Pull request by bfredl**
fixes #12246 . `Base.compile` needs to run uv callbacks generated by `cfunction` while running in imaging mode, which fails under MCJIT, as the wrapper is generated in a "shadow module". Solution: copy the function to a "real" module like `jl_generate_fptr` does.

### CODE REVIEW

**Comment by vtjnash** [comment]
good find. there needs to be some caching here, however, so we only copy it over once. I think you can first return `jl_ExecutionEngine->getFunctionAddress(llvmf->getName())` if non-NULL, then do the copy and repeat the `getFunctionAddress` call

**Comment by bfredl** [comment]
Updated, so that `jl_ExecutionEngine->getFunctionAddress(llvmf->getName())` is checked first.

**Comment by vtjnash** [comment]
is `nullptr` available on LLVM35? otherwise, this lgtm (travis doesn't test the MCJIT branch anyways)

**Comment by yuyichao** [comment]
No Travis doesn't have C++11 enabled AFAIK.

**Comment by tkelman** [comment]
Is it possible to link against a recent LLVM with a pre-C++11 compiler? There's a toolchain PPA we can get recent more versions of GCC from, we'll see whether Travis is using 14.04 by the time we can start using more recent LLVM by default.

**Comment by Keno** [comment]
LLVM 3.5 requires C++11, so it's fine to use `nullptr` in the MCJIT path.

**Comment by tkelman** [comment]
It requires C++11 to build LLVM, does it require C++11 to link against it if it gets built elsewhere?

**Comment by Keno** [comment]
It requires a C++11 capable standard library.

**Comment by bfredl** [comment]
I suppose it is a matter of running `llvm-config --cxxflags` on a LLVM3.5 system (I have 3.6) and see if it contains `-std=c++11`.  (IIRC llvm doesn't separate "internal" and "external" interfaces that much, so if 3.5 uses c++11 "internally", including it most probably requires it as well.)

**Comment by bfredl** [comment]
I checked and `llvm-config --cxxflags` on LLVM3.5 indeed contains `-std=c++11` so I'd say this is good as is.

**Comment by Keno** [comment]
I can haz precompile!

**Comment by ihnorton** [comment]
For Cxx?

**Comment by Keno** [comment]
No, I haven't worked on that yet, but my julia is constantly on llvm-svn, so I needed this for pre-compilation in general.

**Pull request merged**
