### PR TITLE
don't recommend bad code style with Val{.} in the manual

### PR DESCRIPTION
**Pull request by vtjnash**
ref https://groups.google.com/d/msg/julia-users/3piu9wVLDso/Cgn9AhDdCAAJ

### CODE REVIEW

**Comment by eschnett** [comment]
It seems strange to first give an example, and then tell people to not do it this way, and then say that the example function is a "hodgepodge" and should be implemented differently.

It might be better to explain what the fast and the slow parts in this example are. The function itself that takes a `Val` argument is specialized on that argument, and is fast. However, the caller needs to create a type, which is slow -- much slower than a regular `if` statement.

Maybe the problem with this example is that it is too simple. A short function with a `Bool` argument that is used in an `if` statement doesn't really make much sense.

A better example function would use the `Val` arg as parameter of a type; switching from a regular argument to a `Val` argument then makes the function type-stable and thus potentially much more efficient. In particular if the function contains a loop, this might be a large performance benefit, outweighing the cost of creating a `Val` type in the caller.

```Julia
function kernel{I,N}(::Type{Val{I}}, arr::Vector{NTuple{N,Float64}})
    s = 0.0
    for a in arr
        s += a[I]
    end
    s
end

function elsum(i::Integer, arr::Vector)
    kernel(Val{i}, arr)
end
```

**Comment by yuyichao** [comment]
> However, the caller needs to create a type

This is not the slow part. The slow part is the dynamic dispatch and the compilation

**Comment by eschnett** [comment]
@yuyichao Very good, I learned something. Fortunately that doesn't affect the example I gave.

**Comment by eschnett** [comment]
Maybe a better example kernel would be
```Julia
function kernel{N, T<:Tuple}(::Type{Val{N}}, arr::Vector{T})
    s = zero(fieldtype(T,N))
    for a in arr
        s += a[I]
    end
    s
end

function elsum(i::Integer, arr::Vector)
    kernel(Val{i}, arr)
end

**Comment by vtjnash** [comment]
i'd be happy to delete this section and move it to performance tips under "don't write code this way". there is no case in which the given code in the manual will not behave worse than the conditional, aside from a serious compiler regression. (the same can also be said of your first `kernel` example. the second kernel example isn't correct either although closer – it should be using `eltype` to pair with iteration, the `fieldtype` function is part of the private details of a type)

looking through base, I didn't realize how much `Val{true}` has been getting used to obfuscate various APIs. sigh. I'll try to work on that too.

**Comment by eschnett** [comment]
How do you get the type of the `N`th element of a tuple via `eltype`? For me this just returns `Any`, making the example type-unstable.

**Comment by eschnett** [comment]
I think this section is valuable. Shortening it here (where `Val` is introduced) and moving it to the Performance section makes sense.

I still argue that there should not only be a negative example, but also a positive example of `Val`, i.e. an example where it makes sense. If this example is necessarily somewhat complex, that might not be bad -- it will deter from using `Val{true}` instead of a keyword argument `overwrite::Bool=false` (see `cholfact!`). In fact, `cholfact!` might be a good counterexample, as it's less contrived than the current example.

**Comment by eschnett** [comment]
Regarding `cholfact!`: That's what I said, "a keyword argument `overwrite::Bool=false`", that's what should be used there.

Regarding my example: Of course it's a simplified example. I'm trying to design an example that's both simple, and where `Val` makes sense. `mapreduce` has about the right complexity.

Note that the example is callable with an integer argument `n`. If I define a type instead of using a tuple, I'd have to manually write an extraction routine for each field (those would each be one-liners, of course), and then use an if cascade or a switch statement to go from the integer (or a symbol representing the field name) to the field. That's more code, and it would not be any more efficient. So overall, using indexing into a tuple isn't too bad an idea, and explicitly specializing on the tuple index can improve performance.

**Comment by vtjnash** [comment]
ah sorry, i misunderstood (since that's not what the parameter does for cholfact)

**Comment by tkelman** [comment]
If you're defining types just to use them as flags, you need to also export them and take up namespace for users outside the module to use the API concisely. So `Val` at least reduces the number of exports. The `cholfact!` use case of `Val` would need something like a `Pivoted` and `NotPivoted` type. You could use the output factorization type like `CholeskyPivoted` as a flag, but that might be confusing if you're dispatching on a sparse input which would return a Cholmod factorization type rather than a `CholeskyPivoted` output.

**Comment by timholy** [comment]
Regarding `cholfact`, see discussion in #13668.

**Comment by timholy** [comment]
I agree we should change the manual, but I don't think this is the way to do it. See what you think of #15729.

**Comment by timholy** [comment]
Don't know if you noticed http://docs.julialang.org/en/latest/manual/performance-tips/#the-dangers-of-abusing-multiple-dispatch-aka-more-on-types-with-values-as-parameters, but that (and some of the other material) was intended with you in mind. As always, feel free to edit if you think it doesn't quite hit the mark.

**Pull request closed without merging**
