### PR TITLE
update libuv to latest commit (fixing libuv build on OpenBSD)

### PR DESCRIPTION
**Pull request by semarie**
it is part of on-going work to port julia to OpenBSD.

### CODE REVIEW

**Review by inkydragon — COMMENTED** [review]
`jll` also needs to be updated.
https://github.com/JuliaLang/julia/blob/e9aa43d6b27af4e8434485020c8b0646cc172cf6/stdlib/LibUV_jll/Project.toml#L3

https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/build.md#update-the-version-number-of-a-dependency

**Comment by vtjnash** [comment]
Also need to build on yggy https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/LibUV, but might want to land https://github.com/JuliaLang/libuv/pull/37 also first

**Comment by semarie** [comment]
thanks for the pointer about `jll` and yggy. I will take a look at them.

**Comment by semarie** [comment]
#53822 has updated libuv, so it is fine now.

**Pull request closed without merging**
