### PR TITLE
faster `string(::BigFloat)`, and handle comma decimal separator

### LINKED ISSUE #7167: String from a BigFloat is locale-dependent
After pulling latest source, I get an error in the test at line 356 in mpfr.jl because the decimal separator is comma for `BigFloat`s

```
julia> string(big(1.1))
"1,100000000000000088817841970012523233890533447265625e+00"
```

but

```
julia> string(1.1)
"1.1"
```

I guess this is a continental Europe thing, but I cannot figure out which commit has caused this.

```
julia> versioninfo()
Julia Version 0.3.0-prerelease+3533
Commit b9e4f43* (2014-06-07 01:46 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.2.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P8800  @ 2.66GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fixes #7167. This is a really quick-and-dirty approach, but it might be ok. This function is already slow enough that an extra pass over the data is not significant. I considered checking the decimal separator with `localeconv` first, but that function is not thread-safe so I'm not sure it's worth it.

Before:
```
julia> @btime string($(big(1.0)))
  7.651 μs (29 allocations: 4.82 KiB)
```

after:
```
julia> @btime string($(big(1.0)))
  4.511 μs (20 allocations: 4.57 KiB)
```

(Calling sprintf twice does basically all of the work twice.)

### CODE REVIEW

**Comment by simonbyrne** [comment]
It turns out that the [ps_AF](http://www.localeplanet.com/icu/ps-AF/index.html) uses the [Arabic decimal separator character](https://www.fileformat.info/info/unicode/char/066b/index.htm). This appears to be the only locale using a non period/comma character.

Not sure we want to deal with a with a multibyte separator character (if MPFR even handles it correctly).

**Comment by JeffBezanson** [comment]
Yes, it would be nice to handle that. For anything further it would probably be better to use locale-independent code to begin with. Is is possible to extend the Ryu code to do our own bigfloat printing?

**Comment by simonbyrne** [comment]
>  For anything further it would probably be better to use locale-independent code to begin with. Is is possible to extend the Ryu code to do our own bigfloat printing?

It's probably possible, but it would require a bit of work (we could no longer use lookup tables for instance), and I imagine it would be hard to match performance.

**Comment by JeffBezanson** [comment]
I tried setting my numeric locale to ps_AF and it seems to still use a `.`. Of course, that might be a "bug" that they will fix eventually.

**Pull request merged**
