### PR TITLE
Reland "IO: tie lifetime of handle field to container"

### PR DESCRIPTION
**Pull request by vtjnash**
~~Depends on https://github.com/JuliaLang/julia/pull/44881~~

Reverts https://github.com/JuliaLang/julia/commit/a400a24a5d9e6609740814e4092538feb499ce60 (https://github.com/JuliaLang/julia/pull/43924).

Relands https://github.com/JuliaLang/julia/pull/43218.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
`analyzegc` is failing. Let's rerun to see if it still fails.

**Comment by vtjnash** [comment]
oh, sorry, that was a rebase mistake I had forgotten to fix again

**Comment by DilumAluthge** [comment]
Hmmm. Seeing `REPL` failures on macOS x86_64. I'll retry just that one job to see if the failure is deterministic.

**Comment by vtjnash** [comment]
For safety, rerunning after https://github.com/JuliaLang/julia/pull/44956, though I developed them together, so it should be fine

**Pull request merged**
