### PR TITLE
Add replhook() for REPL customization from juliarc

### PR DESCRIPTION
**Pull request by carlobaldassi**
This brings back a way to customize the REPL by defining and registering hooks in .juliarc.jl.
It does so by exporting a `replhook` function, which works similarly to the `atexit` function. However, it could also be left unexported.
Partially addresses #10779.

I wanted to get some feedback before adding documentation etc.

### CODE REVIEW

**Comment by carlobaldassi** [comment]
Travis failure is unrelated (it's in linalg/symmetric).

**Comment by blakejohnson** [comment]
Seems like a good idea to me.

**Comment by phobon** [comment]
It might be good to keep the name in parallel with `atexit`, as more 'hook' functions might be introduced later. Maybe something like `atreplinit` or `atreplstart`?

**Comment by carlobaldassi** [comment]
@phobon that's a good point, and in fact I wasn't satisfied with the name `replhook`. Either of those you proposed sounds good enough to me.

**Comment by carlobaldassi** [comment]
I went with `atreplinit`.

**Comment by yuyichao** [comment]
Is it possible to import a module to REPL with this patch?

**Comment by yuyichao** [comment]
NVM, I figured that I just need to use `eval` as what I always do before anyway... i.e.

```julia
atreplinit() do repl
    eval(Expr(:using, :Scical))
end
```

**Comment by phobon** [comment]
Module import doesn't have any connection to the REPL. If that code is in your juliarc.jl file, it would do the same thing to just have `using Scical` before the `atreplinit` definition.

The patch was just introduced because now the REPL environment has not yet been created when the juliarc.jl file is first read. So you have to defer any customization of the REPL to a function that will be invoked after it is created.

**Comment by yuyichao** [comment]
My point was that I only want to do this in a interactive session but not when running a script. And this PR helps to achieve just that. (since `isinteractive` returns the wrong value at the time `.juliarc.jl` is sourced.)

**Comment by phobon** [comment]
That issue should probably remain open regarding `isinteractive()` then. Clearly there are other uses for it in the juliarc.jl file besides the REPL.

**Comment by yuyichao** [comment]
Is there a interactive shell that doesn't have REPL?

Also note that the command line option `-i` make `isinteractive()` return `true` in `.juliarc.jl` (AFAIK).

**Comment by phobon** [comment]
I just meant that doing:
```
if isinteractive()
    using Scical
end
```
is probably the better way to get that ability rather than using `eval`

**Comment by yuyichao** [comment]
Well, IMHO, it's not a big issue because there's not loss in function. (And actually I was using a `try` block around it so I had to use `eval` anyway)

Also, I noticed that I can just use `@eval` so the only difference is adding a `@eval` which IMHO is really minor.

**Comment by yuyichao** [comment]
So before I can do (if I don't need `try` ... `catch`)

```
if isinteractive()
    using Scical
end
```

Now I use
```
atreplinit() do repl
    @eval using Scical
end
```

I don't think the difference between the two matters too much.

**Pull request merged**
