### PR TITLE
codegen: mark tbaa information in more places

### PR DESCRIPTION
**Pull request by vtjnash**
The improved TBAA and range information should help LLVM's vectorizor.

### CODE REVIEW

**Comment by Keno** [comment]
I took a brief peek through it and this all looks reasonable. I do still want to stop using tbaa_const in the near future, since that's not LLVM-IPO safe, but this seems like a strict improvement.

**Comment by vtjnash** [comment]
> since that's not LLVM-IPO safe

Yet it is precisely correct, so why would we want to give LLVM less information in order to be able to do an optimization that we don't want to do?

**Comment by Keno** [comment]
> Yet it is precisely correct, so why would we want to give LLVM less information in order to be able to do an optimization that we don't want to do?

Because we do want to sometimes do such optimizations (Celeste did) so we might as well try to express the same information in a way that is semantically correct.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27873#issuecomment-401532054) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/873e7acc4024c2e9f80997f2a792c77e95c8b2a8/5f4743f_vs_0a77e89/report.md). cc @ararslan

**Comment by vtjnash** [comment]
Good - this shows consistent large speed up on the benchmarks where the tbaa was most lacking (union array)

**Pull request merged**
