### PR TITLE
Move specialized isequal definitions to avoid hitting #265

### LINKED ISSUE #18213: Warning for simple Dict on 0.5-rc3
I get the following warning for an (I believe?) innocent Dict:

```jl
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin15.6.0

julia> Dict(1 => rand(2,3), 'c' => "asdf")
WARNING: x::Char == y::Integer is deprecated, use UInt32(x) == y instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in ==(::Char, ::Int64) at ./deprecated.jl:50
 in ht_keyindex2(::Dict{Any,Any}, ::Char) at ./dict.jl:580
 in setindex!(::Dict{Any,Any}, ::String, ::Char) at ./dict.jl:635
 in Dict{Any,Any}(::Tuple{Pair{Int64,Array{Float64,2}},Pair{Char,String}}) at ./dict.jl:349
 in Dict{K,V}(::Pair{Int64,Array{Float64,2}}, ::Pair{Char,String}) at ./dict.jl:380
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/rene/local/julia5/usr/lib/julia/sys.dylib:?
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
while loading no file, in expression starting on line 0
Dict{Any,Any} with 2 entries:
  'c' => "asdf"
  1   => [0.874806 0.180844 0.638005; 0.56545 0.0607152 0.509738]
```

### PR DESCRIPTION
**Pull request by martinholters**
Fixes #18213.

How can I test that something does not give a deprecation warning?

### CODE REVIEW

**Comment by tkelman** [comment]
depwarn=error? we use that on ci. or redirect output and check that?

**Comment by tkelman** [comment]
could still use a test

**Comment by martinholters** [comment]
> depwarn=error? we use that on ci.

We do? Travis log says `/tmp/julia/bin/julia --check-bounds=yes runtests.jl $TESTSTORUN`, similar for AppVeyor. If I do that locally, deprecations don't give an error. Similarly, `make test` ends with SUCCESS despite a deprecation warning. In case I missed something with the CI invocation, I still think it would make sense to have `make test` behave the same.

> or redirect output and check that?

I was kind of hoping there was something like
```Julia
@test_nodep Dict(1 => rand(2,3), 'c' => "asdf")
```
I could use. (Actually running the tests with `--depwarn=error` from the Makefile and on CI would probably be even better.) Will do the redirect for now...

**Comment by tkelman** [comment]
If we run with more than one worker I think that should be happening here: https://github.com/JuliaLang/julia/blob/f95b8b12b128b1ed7de876f9a456d4dff4ec79db/test/runtests.jl#L30

At one point I'm pretty sure that worked and deprecation warnings in the tests did trigger errors on CI, but maybe that stopped working at some point or I'm not remembering correctly?

**Comment by nalimilan** [comment]
Deprecation warnings definitely used to trigger a build failure at some point.

**Comment by martinholters** [comment]
Ah, got it. Since I only changed `test/dict.jl`, I ran `make test-dict` and `julia --check-bounds=yes runtests.jl dict`. For the nested `--depwarn=error` call to occur, at least two test files need to be run. Might be worth fixing eventually, but it's not too urgent.

**Pull request merged**
