### PR TITLE
Update references to LTS from v1.6 to v1.10

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by giordano** [comment]
The only result of using `[skip ci]` is skipping the mandatory checks, making a PR unmergeable.

**Comment by ViralBShah** [comment]
This is just updating the LTS version in CONTRIBUTING.md, which doesn't affect any builds. I think this is ok to merge.

**Comment by giordano** [comment]
> This is just updating the LTS version in CONTRIBUTING.md, which doesn't affect any builds.

What I was trying to say is that technically `[skip ci]` skips only GitHub Actions jobs, not buildkite (don't ask me why) and the github actions jobs are those marked as required to run successfully for a PR to run, if they're skipped there's no merge button at all, with the result that (a) CI time isn't significantly saved, quite the opposite, you'll have to run it twice, and (b) the PR can't be merged even if it was good.

**Comment by giordano** [comment]
@PallHaraldsson also, if it wasn't clear, the problem is your commit message, not the first messageof the PR which is not used by anything.  You have to change your commit to remove `[skip ci]`.  Also, [you've used `[skip ci]` several times](https://github.com/JuliaLang/julia/issues?q=is%3Apr%20author%3APallHaraldsson%20%22skip%20ci%22%20) before, someone might hope you'd have realised by now that `[skip ci]` with buildkite doesn't achieve anything.  Finally, please make the title more meaningful, I still don't know what is unwanted, that's a very strange title.

**Comment by PallHaraldsson** [comment]
>you'd have realised by now that [skip ci] with buildkite doesn't achieve anything.

I didn't, I thought useful for docs, maybe only in the past, but will now stop doing this (I suppose neither helpful in packages).

I meant anything related to 1.6, backporting to it is not wanted. This was supposed to be a minor trivial PR... :) I see from Viral "I think this is ok to merge." Is as is better, to point to 1.10, since LTS, or 1.11? I'm always just using the web interfaced for PRs... so not sure how easy to change but I can change the title at least, to whatever you suggest.

**Comment by giordano** [comment]
> I didn't, I thought useful for docs, maybe only in the past, but will now stop doing this (I suppose neither helpful in packages).

As I said, buildkite just ignores `[skip ci]` and it's used only by GitHub Actions, but we also have required GHA jobs, so we can't skip them at all.  Summary: don't use `[skip ci]`.

> I meant anything related to 1.6, backporting to it is not wanted. This was supposed to be a minor trivial PR... :)

Just write something clear and objective like "update references to LTS from v1.6 to v1.10", don't add needless opinions.

**Pull request merged**
