### PR TITLE
Fix issue 31252 - remote globals not being updated in some cases

### PR DESCRIPTION
**Pull request by amitmurthy**
Fixes issue #31252 .

### CODE REVIEW

**Comment by amitmurthy** [comment]
Bump @JeffBezanson

**Comment by ViralBShah** [comment]
Or perhaps even @vtjnash

**Review by vtjnash — APPROVED** [review]

**Comment by amitmurthy** [comment]
Thanks. Will merge. Closing and reopening to trigger CI.

**Comment by raminammour** [comment]
Will this make it to `v1.2` ?

**Comment by amitmurthy** [comment]
I'll close and reopen once again to trigger CI. The OSX failure appears to be unrelated (errors in package testing) and I don't understand some of the buildbot errors. As I am not current with the release cycle, would appreciate it if someone takes a look after the test run completes and merges.

**Comment by amitmurthy** [comment]
All green other than `buildbot/package_win32`. Will merge today evening if there are no objections.

**Comment by vchuravy** [comment]
@amitmurthy should this be backported to 1.0/1.1?

**Comment by amitmurthy** [comment]
Yes. Have added the labels.

**Pull request merged**
