### PR TITLE
Repair the build of the embedding example.

### PR DESCRIPTION
**Pull request by GunnarFarneback**
Make the embedding example build again. If there are better or more proper ways to do this I'm open for suggestions. Ref #18192. Tested on Linux.

### CODE REVIEW

**Comment by yuyichao** [comment]
This should be conditional on `JULIA_THREADS`.

**Comment by twadleigh** [comment]
FYI, I also needed to add `-std=c99` to the flags to get it to build for me (on Windows).

**Comment by tkelman** [comment]
I think the embedding docs still need updating for the thread flag too

**Comment by GunnarFarneback** [comment]
Closing this in favor of #18447.

**Pull request closed without merging**
