### PR TITLE
added serialization tests

### PR DESCRIPTION
**Pull request by wildart**

### CODE REVIEW

**Comment by jakebolewski** [comment]
@wildart this is great!  Can you force push to this branch or open another PR, something went wrong with Travis here.

**Comment by wildart** [comment]
It seems travis is given up on building julia.

**Comment by timholy** [comment]
I restarted the OSX build, let's see if it gets through this time. The fact that it passed on Linux is encouraging.

Thanks for adding these tests!

**Comment by jakebolewski** [comment]
The OSX builds have been timing out lately, possibly due to #9740?

**Comment by stevengj** [comment]
Great!  Other things to test serialization of:

* Different `String` types: `UTFxxString` for `x` in 8,16,32;  also `RevString` and `SubString` thereof
* `Regex` and `RegexMatch`
* `Set`, `IntSet`, `BitArray`, and `Dict`

**Comment by timholy** [comment]
I should have looked at the message; kicking myself that I didn't. Is it stalling out before it even gets to the tests? I checked this OSX build just now and it's already into the tests, which means it's past what got added in #9740. (I put the new test first rather than last because it's very quick, I figured we'd get fast feedback that way.)

**Comment by jakebolewski** [comment]
No you are right, I thought you were running the tests with the `julia-debug -J sys.ji` but you only running a quick sanity check.

**Comment by wildart** [comment]
@stevengj I tried to cover `base/serialize.jl` with tests. Of course, there are more serializers scattered in different parts of `base`. It shouldn't be a problem to cover them as well.

**Comment by stevengj** [comment]
@wildart, thanks for the clarification.  Actually, I guess  the types I mentioned will be covered by the `serialize(s, x)` method for composite types, so as long as this is tested it will be fine.

**Comment by wildart** [comment]
Even though most of high level serialization routines rely on basic functions from `serialize.jl`, they needed to be tested to ensure consistency.

**Comment by timholy** [comment]
This is green, I don't see any reason not to merge. Thanks again, @wildart.

**Pull request merged**
