### PR TITLE
Fix eltype() and pointer() of Cstring

### LINKED ISSUE #31381: eltype(Cstring) != Cchar
The documentation claims, and my intuition would also suggest, that `eltype(Cstring)` should be `Cchar`. I [originally asked about this on discourse](https://discourse.julialang.org/t/cchar-eltype-cstring/21634), and @StefanKarpinski suggested it's probably just an oversight. Note also that `pointer(Cstring(C_NULL))` returns `Ptr{UInt8}` rather than `Ptr{Cchar}` ie `Ptr{Int8}`.

Note I am on Linux x86_64, and I know `char` can be unsigned on some systems.

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> s = Cstring(C_NULL)
Cstring(0x0000000000000000)

julia> pointer(s)
Ptr{UInt8} @0x0000000000000000

julia> eltype(s)
UInt8

julia> Cchar
Int8

```

### PR DESCRIPTION
**Pull request by nstiurca**
Fixes #31381

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by StefanKarpinski** [comment]
Thanks and Looks good to me. If someone who understands calling conventions and whether this will cause problems could look at this it would be great. cc @vtjnash, @yuyichao

**Review by vtjnash — APPROVED** [review]

**Comment by nstiurca** [comment]
Is this the type of thing that should be backported so as to bring the implementation in line with documentation?

**Comment by StefanKarpinski** [comment]
Debatable. I can mark for triage to discuss whether this is safe to backport or not.

**Comment by Keno** [comment]
Triage says no backport and that this counts as a minor change.

**Comment by StefanKarpinski** [comment]
Should probably have a NEWS entry as well (labeled for such).

**Pull request merged**
