### PR TITLE
Fix double and double! functions being the same

### PR DESCRIPTION
**Pull request by mjgalindo**
Both functions would change the input parameter, defeating the purpose of showing how the style works.

### CODE REVIEW

**Comment by mschauer** [comment]
The example in the manual is written as intended: two possible names for a single function are discussed and `double!` is recommended as the function "modifies its arguments".

**Comment by fredrikekre** [comment]
> Both functions would change the input parameter, defeating the purpose of showing how the style works.

Isn't this the point with the example? To show that for a mutating function we use the `!` convention?

**Comment by mjgalindo** [comment]
Ok, I got the example entirely wrong. I thought it made more sense for it to show the implementation of two versions of the same function, one that changes its parameters and one that doesn't. Fair enough.

**Comment by fredrikekre** [comment]
> Ok, I got the example entirely wrong. I thought it made more sense for it to show the implementation of two versions of the same function, one that changes its parameters and one that doesn't. Fair enough.

I can see that it is confusing, perhaps worth rewriting that example entirely instead. Anyway, thanks for the PR!

**Pull request closed without merging**
