### PR TITLE
add missing clamp function for IOBuffer

### LINKED ISSUE #55279: 3x slow down in string benchmarks due to Fix annotated join with non-concrete eltype iters (#54919)
The `["string", "readuntil", "target length 1"]` and `["string", "readuntil", "target length 2"]` benchmarks got 3x slower recently. I bisected to https://github.com/JuliaLang/julia/commit/462d7f4c4cb2d4a13a1e056b39cb3ea84fb5082d, @tecosaur.

See https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_date/2024-07/26/report.md or https://tealquaternion.camdvr.org/compare.html?start=6b08e80bd1217c5c2eb6c89604c21faa5b2a156f&end=42a8efff5a6b96394a36af541cf8a7a4725632fb&stat=min-wall-time&name=string for the benchmark results

### PR DESCRIPTION
**Pull request by vtjnash**
The `clamp` function was defined in Base.Math, but required to be in Base now, so move it to intfuncs with other similar functions

Fixes #55279

### CODE REVIEW

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("scalar" || "io", vs=":master")`

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks("string" || "io", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/55424#issuecomment-2276912818) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/cafb20c_vs_e7e8768/report.md).

**Comment by nanosoldier** [comment]
[Your job](https://github.com/JuliaLang/julia/pull/55424#issuecomment-2276912732) failed.

**Pull request merged**
