### PR TITLE
Use isempty to check for empty strings

### PR DESCRIPTION
**Pull request by musm**
it's faster to check for empty string using isempty rather than == ""

### CODE REVIEW

**Review by Sacha0 — APPROVED** [review]

**Comment by nalimilan** [comment]
Have you benchmarked this? `==` starts with `a.len == b.len`, so this should be quite fast.

**Comment by musm** [comment]
yes
e.g.
```julia
julia> using BenchmarkTools

julia> x = ""
""

julia> y = ""
""

julia> @benchmark $x == $y
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.526 ns (0.00% GC)
  median time:      6.316 ns (0.00% GC)
  mean time:        6.896 ns (0.00% GC)
  maximum time:     125.139 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> @benchmark isempty($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.578 ns (0.00% GC)
  median time:      1.579 ns (0.00% GC)
  mean time:        1.832 ns (0.00% GC)
  maximum time:     53.292 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

**Comment by nalimilan** [comment]
But what difference does it make when calling the functions you change in this PR? I would guess the overhead would be pretty small, maybe negligible.

Though I guess this PR doesn't hurt either.

**Comment by stevengj** [comment]
👍 Seems like better style, even if the performance impact is negligible.

**Pull request merged**
