### PR TITLE
GC support for stack allocated objects

### PR DESCRIPTION
**Pull request by carnaval**
Only works with copy_stacks for now. The code is not used anywhere in
codegen right now, it can be tested by using (:stknew typ args...)
instead of :new. It is essentially the GC side of #8134 but without the
global alloca stack & unmarking, so @JeffBezanson will probably be happier.

Stack objects are kept marked (+young) permanently and are only scanned
when coming from the owning task.

Note that this is on top of jn/codegen_rewrite under the "no codegen change policy" :-)

cc @vtjnash

### CODE REVIEW

**Comment by carnaval** [comment]
oh and the way I get the current task stack's bounds is kinda gore, I think we have at least the bottom registered somewhere but I didn't feel like going through the whole init thing just yet. I had a look and saw that it looks like we support stacks growing up ?

**Comment by vtjnash** [comment]
> I had a look and saw that it looks like we support stacks growing up ?

the code for that is not really functional, since there is no use case for it

> oh and the way I get the current task stack's bounds is kinda gore,

take a look at gc_mark_task_stack, either on master or https://github.com/JuliaLang/julia/pull/9461/files#diff-31b93f4272eaeede3738531e90317e0cR1499

the stack is either `ta->stkbuf`..`ta->gcstack`..`ta->stkbuf + ta->ssize` (if it is not the current task), or `$rsp`..`jl_pgcstack`..`jl_stackbase` for the current stack (where you can get `$rsp` from taking the address of a variable as you enter `jl_gc_collect`)

**Comment by timholy** [comment]
:+1: (exciting this would help with #14955). Looks like this could use a rebase now that `jn/codegen_rewrite` has been merged.

**Comment by ViralBShah** [comment]
Would this help for #9174 too?

**Pull request closed without merging**
