### PR TITLE
Fix dangling pointer in libuv close callback

### LINKED ISSUE #12992: SegFault in libuv close callback
Reproduced with aggressive GC running the `file` test. To the best of my knowledge what happens is

* A `PollingFileWatcher` (`p`) is created with a libuv `uv_handle_t*` (`handle`).

    After the constructor `p->handle == handle`, `handle->data == p`. This also registered a finalizer `uvfinalize` on `p`.

* User closed `p` (`close(t::Union{FileMonitor, PollingFileWatcher})`)

   * `jl_close_uv` queue `handle` for closing later in `loop->closing_handles`
   * `p->handle` is set to `NULL` by `close`

* The handler `p` gets out of scope and a GC fires

    * Finalizer `uvfinalize` is called. `p->handle` is `NULL` so `disassociate_julia_struct` does nothing, `close` is also called but also does nothing.

* The next GC sweep the memory region

    Now `p` is not valid anymore and `handle->data`, which is still linked in `loop->closing_handles`, is a dangling pointer.

* A dozen of collections later (literally, which makes it very hard to see what's happening in gdb), the libuv event loop decided to close this handle for real, and get an error or segfault (or whatever) depending on what happened to be in the memory region at that point.

Seems to be caused by https://github.com/JuliaLang/julia/commit/94de95e8fe73151f5b83882fc42356bc269bb79f

@vtjnash . This doesn't seem too hard to solve but you probably have a more coherent view about all these callbacks and could fix it in the best way.

### PR DESCRIPTION
**Pull request by yuyichao**
Fix #12992

Calling `close` multiple times seems fine too.

@vtjnash

### CODE REVIEW

**Comment by vtjnash** [comment]
this is wrong. double-closing a stream will cause a libuv assertion error (unless you do it rapidly like you have in the tests)

**Comment by yuyichao** [comment]
Isn't the `jl_uv_close` function makes sure it doesn't happen?

**Comment by vtjnash** [comment]
Ah, right. the close hook will make sure to invalidate the handle and `jl_uv_close` will prevent the double-close from happening. (although this is also why uv_stream objects no longer are managed with an explicit state rather than testing `handle` https://github.com/JuliaLang/julia/blob/5edd47c0574762c3e4b44c8045b3263c4bbac9a4/base/stream.jl#L802)

**Comment by yuyichao** [comment]
I also see another `close` that is [directly calling `jl_close_uv`](https://github.com/JuliaLang/julia/blob/5edd47c0574762c3e4b44c8045b3263c4bbac9a4/base/stream.jl#L594) which is why I think this should be fine. Although is that one missing a `NULL` check after `_uv_hook_close` `NULL` the `handle` pointer?

**Comment by vtjnash** [comment]
yes, in general it would be much better to provide an explicit status and test for that status before doing any of those ccalls. The presence of inconsistency isn't really evidence that it will always work, just that nobody has taken the time to unify and fix the behaviors.

**Pull request merged**
