### PR TITLE
unique now infers element type for Generator

### LINKED ISSUE #20105: unique(itr) doesn't infer types for a generator
Unlike `Set` or `collect`, `unique(itr)` doesn't infer types from the generator.

```
unique(x for x in 1:3)

3-element Array{Any,1}:
 1
 2
 3
```

It should return `Array{Int, 1}`.

### PR DESCRIPTION
**Pull request by colinfang**
Fix #20105

### CODE REVIEW

**Comment by TotalVerb** [comment]
Similar to `map`, if `et` is abstract it's probably best to instead return a `Vector{T}` where `T` is the typejoin. Using `et` directly is acceptable in the empty case.

**Comment by ararslan** [comment]
Since this method shares nearly all of its code with the fallback method above it, it seems to me that the fallback method could simply be made more robust to cases where the element type can't be inferred. Jeff fixed the `sum(::Generator)` case by employing traits; perhaps a similar approach could be used here?

**Comment by pabloferz** [comment]
Here's a way to do this in a way that does not depends upon inference (except for the empty case), which is the desired behavior.

```julia
function unique(g::Generator)
    T = _default_eltype(typeof(g))
    out = Vector{T}()
    seen = Set{T}()
    i = start(g)
    if done(g, i)
        return out
    end
    x, i = next(g, i)
    S = typeof(x)
    if !isleaftype(T)
        T = S
        out = Vector{T}()
        seen = Set{T}()
    end
    push!(seen, x)
    push!(out, x)
    while !done(g,  i)
        x, i = next(g, i)
        S = typeof(x)
        if !(S === T || S <: T)
            T = typejoin(S, T)
            seen = convert(Set{T}, seen)
            out = convert(Vector{T}, out)
        if !in(x, seen)
            push!(seen, x)
            push!(out, x)
        end
    end
    return out
end
```

**Comment by colinfang** [comment]
@TotalVerb @ararslan  Thank you for the advice, it turns out that I don't really know internals of Julia too well. It is a bit frustrating to see a correct implementation of such a simple function takes so many lines of code. I will close my PR, and @pabloferz could instead make a better PR.

**Comment by StefanKarpinski** [comment]
> It is a bit frustrating to see a correct implementation of such a simple function takes so many lines of code.

Functions where this is the case are precisely the ones that are good candidates for inclusion in the standard library. There are a lot of seemingly simple things that are subtly difficult to do correctly. @pabloferz – shouldn't we update the definition of `unique` to your version posted here?

**Comment by pabloferz** [comment]
> shouldn't we update the definition of unique

@StefanKarpinski Yes, the changes are now on #20317

**Pull request closed without merging**
