### PR TITLE
Improve significand performance

### PR DESCRIPTION
**Pull request by musm**
Based on frexp performance improvements. 
Primarily with subnormal branch performance.

### CODE REVIEW

**Comment by musm** [comment]
same as this: https://github.com/JuliaLang/julia/pull/18992
you can test urself

**Comment by musm** [comment]
you can also see `@code_llvm` for improvement in subnormal branch

**Comment by StefanKarpinski** [comment]
Seeing at least one actual comparison is a reasonable request for what is claimed to be a performance improvement. "you can test urself" is not sufficient.

**Comment by musm** [comment]
```julia
julia> using Base: exponent_half, exponent_mask, significand_bits, leading_zeros, exponent_bits, sign_mask,exponent_bias, exponent_one, sign_mask

julia> function _significand{T<:AbstractFloat}(x::T)
           xu = reinterpret(Unsigned, x)
           xs = xu & ~sign_mask(T)
           xs >= exponent_mask(T) && return x # NaN or Inf
           if xs <= (~exponent_mask(T) & ~sign_mask(T)) # x is subnormal
               xs == 0 && return x # +-0
               m = unsigned(leading_zeros(xs) - exponent_bits(T))
               xs <<= m
               xu = xs | (xu & sign_mask(T))
           end
           xu = (xu & ~exponent_mask(T)) | exponent_one(T)
           return reinterpret(T, xu)
       end
_significand (generic function with 1 method)

julia> using BenchmarkTools

julia> @benchmark _significand(realmin(Float64))
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.947 ns (0.00% GC)
  median time:      4.343 ns (0.00% GC)
  mean time:        4.599 ns (0.00% GC)
  maximum time:     61.582 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark significand(realmin(Float64))
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.947 ns (0.00% GC)
  median time:      4.737 ns (0.00% GC)
  mean time:        5.300 ns (0.00% GC)
  maximum time:     196.195 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark _significand(realmin(Float64)/2)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.131 ns (0.00% GC)
  median time:      5.132 ns (0.00% GC)
  mean time:        5.616 ns (0.00% GC)
  maximum time:     140.929 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark significand(realmin(Float64)/2)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.921 ns (0.00% GC)
  median time:      6.711 ns (0.00% GC)
  mean time:        6.797 ns (0.00% GC)
  maximum time:     116.848 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

```

```julia
julia> @code_llvm _significand(2.0)

; Function Attrs: uwtable
define double @julia__significand_72119(double) #0 {
top:
  %1 = bitcast double %0 to i64
  %2 = and i64 %1, 9223372036854775807
  %3 = icmp ult i64 %2, 9218868437227405312
  br i1 %3, label %L, label %if

L:                                                ; preds = %top
  %4 = icmp ugt i64 %2, 4503599627370495
  br i1 %4, label %L2, label %if3

L2:                                               ; preds = %pass, %L
  %xu.0 = phi i64 [ %1, %L ], [ %15, %pass ]
  %5 = and i64 %xu.0, -9218868437227405313
  %6 = or i64 %5, 4607182418800017408
  %7 = bitcast i64 %6 to double
  ret double %7

if:                                               ; preds = %if3, %top
  ret double %0

if3:                                              ; preds = %L
  %8 = icmp eq i64 %2, 0
  br i1 %8, label %if, label %pass

pass:                                             ; preds = %if3
  %9 = call i64 @llvm.ctlz.i64(i64 %2, i1 false)
  %10 = add nsw i64 %9, -11
  %11 = shl i64 %2, %10
  %12 = icmp ugt i64 %10, 63
  %13 = select i1 %12, i64 0, i64 %11
  %14 = and i64 %1, -9223372036854775808
  %15 = or i64 %13, %14
  br label %L2
}

julia> @code_llvm significand(2.0)

; Function Attrs: uwtable
define double @julia_significand_72268(double) #0 {
top:
  %1 = bitcast double %0 to i64
  %2 = and i64 %1, 9218868437227405312
  %3 = icmp eq i64 %2, 0
  br i1 %3, label %if, label %L1

L1:                                               ; preds = %top
  %4 = icmp eq i64 %2, 9218868437227405312
  br i1 %4, label %if3, label %L2

L2:                                               ; preds = %L1, %pass
  %xu.0 = phi i64 [ %1, %L1 ], [ %22, %pass ]
  %5 = and i64 %xu.0, -9218868437227405313
  %6 = or i64 %5, 4607182418800017408
  %7 = bitcast i64 %6 to double
  ret double %7

if:                                               ; preds = %top
  %8 = fcmp une double %0, 0.000000e+00
  br i1 %8, label %pass, label %if3

if3:                                              ; preds = %L1, %if
  ret double %0

pass:                                             ; preds = %if
  %9 = and i64 %1, -9223372036854775808
  %10 = xor i64 %9, %1
  %11 = call i64 @llvm.ctlz.i64(i64 %10, i1 false)
  %12 = add nsw i64 %11, -11
  %13 = icmp ult i64 %11, 11
  %14 = shl i64 %10, %12
  %15 = icmp ugt i64 %12, 63
  %16 = select i1 %15, i64 0, i64 %14
  %17 = sub nsw i64 11, %11
  %18 = lshr i64 %10, %17
  %19 = icmp ugt i64 %17, 63
  %20 = select i1 %19, i64 0, i64 %18
  %21 = select i1 %13, i64 %20, i64 %16
  %22 = xor i64 %21, %9
  br label %L2
}
```

**Comment by simonbyrne** [comment]
Care to add this to BaseBenchmarks?

**Comment by musm** [comment]
To be honest I don't anticipate I have time to do that, so feel free to add any.

**Comment by musm** [comment]
g2g on my end, this is uncontroversial improvement (frexp improvements were already merged)

**Comment by simonbyrne** [comment]
@nanosoldier `runbenchmarks("scalar", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/19484#issuecomment-265574352) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/0c8971d5a5f6d03d10a13bb6e00f02022b19d4fd/c2978f9_vs_07cb7c1/report.md). cc @jrevels

**Comment by simonbyrne** [comment]
Thanks.

**Comment by musm** [comment]
thanks!

**Pull request merged**
