### PR TITLE
Dark and light images for README.md

### PR DESCRIPTION
**Pull request by cormullion**
This PR adds two images to the README.md of this repo, responding to Github dark and light modes. [Github description of the feature here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github#adding-an-image-to-suit-your-visitors).

They should look like this:

Screenshot 2023-04-27 at 17 09 23

In an earlier PR (#39601) a white line was added, but it looked a bit out of balance to me.

(This is a restrained and simple design to keep the file size down...  😂)

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by KristofferC** [comment]
It's very big, no?

**Comment by cormullion** [comment]
> It's very big, no?

39 Kb ? - quite small, especially for me. I think the contributor avatars are bigger ...

**Comment by giordano** [comment]
> but in my dark browser, I still see the white version.

Try to clear the cache, I had the same problem at first.

**Comment by cormullion** [comment]
> to it being big visually

Ah, OK, yes - I just went for social-media-preview size... 🤷‍♂️

I think cacheing may be a thing -  I hope github's code works 😉

**Pull request merged**
