### PR TITLE
Clear the IRBuilder's insertion point after emitting a function

### PR DESCRIPTION
**Pull request by maleadt**
The function might get finalized, invalidating the IP. However, in some cases this invalid IP may get saved and restored, accessing the invalid IP while doing so.

Example code path accessing an invalid IP:
- `jl_cfunction_object`: nested_compile=true, but doesn't change IP
- `gen_cfun_wrapper`
- `jl_compile_linfo`: saves and restores invalid IP

Example code:

``` julia
function foobar()
    return Cint(0)
end

cfunction(foobar, Cint, ())

# compilation of cfunction makes builder.BB point to an invalid BB
# compilation of foobar restores that invalid BB (as per code path explained above)
```

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Thanks, lgtm.

**Comment by tkelman** [comment]
can that code path be tested?

**Comment by maleadt** [comment]
I can add the snippet above to the tests, but we'd still need an ASAN-like builder to detect if it fails.

**Comment by vtjnash** [comment]
I'm hoping we can simply eliminate all globals from codegen in the near future (and wrap almost the whole file inside the class `jl_codectx_t` instead of passing it manually). I think we're pretty close.

**Comment by maleadt** [comment]
Good to know. In the meantime, this gets us a little closer again to passing all tests with ASAN enabled (I'll be pushing some devdocs on how to set it all up, because it has been a bit of a struggle).

**Comment by tkelman** [comment]
If you think this should be backported, do speak up.

**Pull request merged**
