### PR TITLE
Address issparse for specialized matrix types part of #13096

### PR DESCRIPTION
**Pull request by pkofod**
Adds `issparse` methods for specialized matrix types, such that it returns `true` if the matrix they are based on are sparse.

cc @kshyatt

### CODE REVIEW

**Comment by tkelman** [comment]
Looks reasonable. Could you rebase and squash the commits?

**Comment by pkofod** [comment]
Yes, although I seem to have done something wrong :)

**Comment by tkelman** [comment]
Yeah, this shouldn't have the other commit from a different PR in it. If you rebase again but delete the line for that other commit it should fix it.

**Comment by pkofod** [comment]
Sigh, I always mess this rebase-thing up. I need to find a git course :)

When you say "rebase again but delete the line for that other commit" what do you mean by that ? (by the way I seem to have added another commit now.

**Pull request merged**
