### PR TITLE
Absorb vtjnash/Pidfile.jl into FileWatching

### PR DESCRIPTION
**Pull request by IanButterworth**
I took a stab at bringing https://github.com/vtjnash/Pidfile.jl in, as discussed in https://github.com/JuliaLang/Pkg.jl/pull/2732#issuecomment-932680705

FileWatching seemed like a good place for it?

The primary reason is to provide a robust way for Pkg to fix multiprocess races like https://github.com/JuliaLang/Pkg.jl/issues/2746 and https://github.com/JuliaLang/julia/issues/42405

The only changes I made were to fix imports and conform docstring formatting.

cc. @vtjnash

### CODE REVIEW

**Comment by vtjnash** [comment]
Hm, it does make some sense being part of there. But any reason not to keep it separate (with separate issue tracker and such)? There's a script `contrib/new-stdlib.sh` for importing those.

**Comment by IanButterworth** [comment]
I was thinking it was a reasonable fit and keeping the number of stdlibs low seems to be a bit of a goal? Third option, move FileWatching as it is in this PR to an external stdlib?

**Comment by DilumAluthge** [comment]
Are you planning on making Pidfile.jl part of the public API of the FileWatching stdlib? If so, I would recommend making Pidfile an external stdlib instead, similar to Pkg, Downloads, etc. (Normally I wouldn't recommend adding a new stdlib, but the motivation here is to use the code from Pidfile in Pkg, and Pkg cannot have any non-stdlib dependencies.)


On the other hand, if you don't want to make it part of the public API, we could just vendor a copy of the Pidfile.jl code in the Pkg repo.

I would recommend not making it part of the public API, since we really only want to use this for Pkg. That way, in the future, we can make breaking changes (or even remove Pidfile completely) in a non-breaking release of Julia.

**Comment by vtjnash** [comment]
We also very much want to use this for many other code loading places in `Base` and `REPL`.

**Comment by DilumAluthge** [comment]
> We also very much want to use this for many other code loading places in `Base` and `REPL`.

In that case, I'd just make it its own external stdlib like Pkg, Downloads, etc.

Users can then use the BumpStdlibs bot (https://github.com/JuliaLang/BumpStdlibs.jl) to automate updates.

**Comment by KristofferC** [comment]
> In that case, I'd just make it its own external stdlib like Pkg, Downloads, etc.

If we want to use it in Base, why does that make making it an external library a good idea? In my head, it's the opposite.

**Comment by DilumAluthge** [comment]
> > In that case, I'd just make it its own external stdlib like Pkg, Downloads, etc.
> 
> If we want to use it in Base, why does that make making it an external library a good idea? In my head, it's the opposite.

Ohh, I see what you mean. Same as with TOML, where the Base code loading needs to use it.

Okay, so instead of an external library, should we make Pidfile a "vendored" stdlib similar to TOML?

**Comment by DilumAluthge** [comment]
FWIW, the BumpStdlibs.jl bot will eventually be able to update "vendored" stdlibs like TOML.

So we can still use the https://github.com/vtjnash/Pidfile.jl repo as the main development repo, and then sync the files like we do for TOML.

**Comment by KristofferC** [comment]
The TOML thing didn't turn out very well though. So perhaps just keep it completely in the repo? Not sure.

**Comment by DilumAluthge** [comment]
> The TOML thing didn't turn out very well though.

How do you mean?

**Comment by DilumAluthge** [comment]
> So perhaps just keep it completely in the repo?

By this, you mean that we could move the contents of Pidfile.jl into the JuliaLang/julia repo, and then we would archive the https://github.com/vtjnash/Pidfile.jl repo? And then all development (issues, pull requests, etc.) would just happen directly in the JuliaLang/julia repo?

That seems fine to me.

**Comment by IanButterworth** [comment]
If it's going to be used in Base then that sets the requirement that it needs to be in Base, I believe. And nothing else in Base is externally hosted, so it seems like simply putting it in Base in the main repo is the only option?

**Comment by IanButterworth** [comment]
Ok, I'll add it as an external stdlib. But before doing that I guess it should be moved to the JuliaLang org?

**Comment by IanButterworth** [comment]
@vtjnash now that Pidfile 1.3.0 is out, should I revive this and bring everything over? or happy to leave it to you

**Pull request closed without merging**
