### PR TITLE
Add promotion rules for Nullable

### PR DESCRIPTION
**Pull request by nalimilan**
These are consistent with convert().

Cc: @johnmyleswhite

### CODE REVIEW

**Comment by nalimilan** [comment]
AppVeyor failure was https://github.com/JuliaLang/julia/issues/15893, I've restarted it (see log on the other issue).

**Comment by nalimilan** [comment]
No reactions? I'll merge tomorrow if nobody objects.

**Comment by tkelman** [comment]
This seems to be getting in the auto lifting direction? I don't think this should be merged without some discussion and approval from relevant parties that it's the right direction to define these.

**Comment by nalimilan** [comment]
I would say this is largely independent of whether we want auto-lifting or not (though it's clearly a pre-requirement for auto-lifting). This PR simply introduces some consistency. Currently, `convert(Nullable{Int}, 1) === Nullable{Int}(1)`. With this PR, we also have `promote(Nullable{Int}(), 1) === (Nullable{Int}(), Nullable{Int}(1))`.

I don't think we can find any good justification for current situation, in which even `[Nullable(), Nullable(1)]` doesn't create an homogeneous array.

**Comment by tkelman** [comment]
If a Nullable is a kind of container, then that shouldn't produce a homogeneous array since Nullable of Void and Nullable of Int should maybe not be implictly converted, only when asked for? Not sure but would rather check that this is widely wanted.

**Comment by nalimilan** [comment]
> If a Nullable is a kind of container, then that shouldn't produce a homogeneous array since Nullable of Void and Nullable of Int should maybe not be implictly converted, only when asked for? Not sure but would rather check that this is widely wanted.

Note that `Nullable()` doesn't produce a `Nullable{Void}` but a `Nullable{Union{}}`. Of course, the former cannot be promoted to a common type with an `Int`.

**Comment by nalimilan** [comment]
OK, maybe I should explain the situation in which I needed these definitions. I'm writing a function filling an array based on a series of `(index, value)` pairs. In case some indices are missing, I fill the entries with a user-provided default value, which is by default `Nullable()`. With promotion rules from this PR, I can return an array of the appropriate element type: `Nullable` if `default=Nullable()`, or a scalar type which can hold both provided values and the default if not. This sounds like a very natural use of promotion rules to me.

**Comment by nalimilan** [comment]
@johnmyleswhite Could you comment on the opportunity of these promotion rules?

**Comment by nalimilan** [comment]
Bump. These rules are really necessary to port DataFrames to NullableArrays. They allow replacing `@data([1, NA])` with `NullableArray([1, Nullable()])`, instead of using a custom constructor like `NullableArray([1, "NULL"], Int, "NULL")`.

It's unfortunate that this PR is blocked to due the lack of comments from people working on these packages. @tshort maybe?

**Comment by nalimilan** [comment]
Forgot to add @davidgold to the discussion.

**Comment by johnmyleswhite** [comment]
These rules seem alright, but they also seem to push in a very different direction than I believed we had planned on heading since I believe the result of these rules being added is that `1 + Nullable{Int}()` would work if binary addition of nullables were available. Is that true? That seems different from the C# approach we've talked about talking, although it's not clear to me we have any coherent and popular direction for nullability yet.

**Comment by nalimilan** [comment]
No, these promotion rules do not affect arithmetic operations at all, since they rely on `promote_op`. Only https://github.com/JuliaLang/julia/pull/16080 would implement them (and I indeed think we should have the discussion about arithmetic operations there). This PR is really limited to the safe part of promotion.

**Comment by nalimilan** [comment]
@johnmyleswhite So, do you think this is OK?

**Comment by johnmyleswhite** [comment]
Yes, this is fine by me.

**Comment by nalimilan** [comment]
Thanks for the feedback!

**Pull request merged**
