### PR TITLE
Backports for Julia 1.4 RC2

### LINKED ISSUE #34752: Unreachable reached from builtin call to apply_iterate
The following code crashes with an illegal instruction on Julia 1.1+ (bisected to https://github.com/JuliaLang/julia/pull/28955):

```julia
struct a{T}
  b
  c
  function a(c, d...)
    e = length(d)
    e > 1 || error()
    new{Nothing}(d, 42)
  end
end

function h(g)
  g = (d = 42, c = g.c, dontcare = 42)
  a(g...)
end

h(a(42, 42, 42))
```

`@code_warntype`:

```
Variables
  #self#::Core.Compiler.Const(h, false)
  g@_2::a{Nothing}
  g@_3::Union{a{Nothing}, NamedTuple{(:d, :c, :dontcare),_A} where _A<:Tuple}

Body::Union{}
1 ─      (g@_3 = g@_2)
│   %2 = (:d, :c, :dontcare)::Core.Compiler.Const((:d, :c, :dontcare), false)
│   %3 = Core.apply_type(Core.NamedTuple, %2)::Core.Compiler.Const(NamedTuple{(:d, :c, :dontcare),T} where T<:Tuple, false)
│   %4 = Base.getproperty(g@_3::a{Nothing}, :c)::Any
│   %5 = Core.tuple(42, %4, 42)::Core.Compiler.PartialStruct(Tuple{Int64,Any,Int64}, Any[Core.Compiler.Const(42, false), Any, Core.Compiler.Const(42, false)])
│        (g@_3 = (%3)(%5))
│        Core._apply_iterate(Base.iterate, Main.a, g@_3::NamedTuple{(:d, :c, :dontcare),_A} where _A<:Tuple)
└──      Core.Compiler.Const(:(return %7), false)
```

The trap comes from here: https://github.com/JuliaLang/julia/blob/79f31e44087425e552571b6f94da364830b5c113/src/codegen.cpp#L4153-L4155

The call codegen stumbles on is `Expr(:call, Core._apply_iterate, Base.iterate, Main.a, SSAValue(4))`. Probably a dup of some other unreachable reached issue, but it's hard to tell.

### LINKED ISSUE #34826: LLVM assertion failure in core tests
I get this on master with LLVM assertions enabled:

```
Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
core       (1) |        started at 2020-02-20T14:14:10.279
julia: /home/jeff/src/julia/deps/srccache/llvm-9.0.1/lib/IR/Constants.cpp:1005: static llvm::Constant* llvm::ConstantArray::getImpl(llvm::ArrayType*, llvm::ArrayRef<llvm::Constant*>): Assertion `V[i]->getType() == Ty->getElementType() && "Wrong type in array element initializer"' failed.

signal (6): Aborted
in expression starting at /home/jeff/src/julia/test/core.jl:4930
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f0196091399)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN4llvm13ConstantArray7getImplEPNS_9ArrayTypeENS_8ArrayRefIPNS_8ConstantEEE at /home/jeff/src/julia/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm13ConstantArray3getEPNS_9ArrayTypeENS_8ArrayRefIPNS_8ConstantEEE at /home/jeff/src/julia/usr/bin/../lib/libLLVM-9jl.so (unknown line)
julia_const_to_llvm at /home/jeff/src/julia/src/intrinsics.cpp:260
emit_unbox at /home/jeff/src/julia/src/intrinsics.cpp:333
julia_to_native at /usr/include/c++/7/bits/stl_bvector.h:81 [inlined]
emit_a_ccall at /home/jeff/src/julia/src/ccall.cpp:1756
emit_ccall at /home/jeff/src/julia/src/ccall.cpp:1702
emit_expr at /home/jeff/src/julia/src/codegen.cpp:4170
emit_ssaval_assign at /home/jeff/src/julia/src/codegen.cpp:3862
emit_stmtpos at /home/jeff/src/julia/src/codegen.cpp:4056 [inlined]
emit_function at /home/jeff/src/julia/src/codegen.cpp:6665
jl_compile_linfo at /home/jeff/src/julia/src/codegen.cpp:1256
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #34487 - update Documenter version
- [x] #34491 - Fix URLs referencing latest
- [x] #34490 - jl_special_vector_alignment: Remove work-around for old LLVM versions
- [x] #34503 - fix bug in printing of block expressions in ref
- [x] #34504 - fix printing of LineNumberNode in block within ref
- [x] #34509 - Always use Symbol as _group value of log records
- [x] #34402 - Make testall target work with JULIA_BUILD_MODE=debug again.
- [x] #34483 - Merge pull request #34483 from JuliaLang/sf/python_search
- [x] #34546 - Make SuiteSparse wrapper thread safe.
- [x] #34601 - Construct MulAddMul at gemm_wrapper! call sites
- [x] #34573 - make package cache interit permission from source
- [x] #34458 - src/codegen.cpp: fix segfault on `@code_native` with eltype (#34434)
- [x] #34596 - add some helpful type information to Base and REPLCompletions
- [x] #34473 - alignment: subtly change meaning of datatype_align
- [x] #34583 - handle masked_gather in late-gc-lowering
- [x] #34755 - fix #34752, inference bug in varargs with constant prop 
- [x] #34732 - Remove Iterators.reverse(::Tuple) specialization 
- [x] #34754 - ccall: avoid some problematic symbol mangling 
- [x] #34763 - make alignment deal with float32 like float64
- [x] #34807 - partr: Fix deadlock
- [x] #34792 - codegen: fix bad declaration of memcmp stdlib function signature
- [x] #34805 - codegen: fix segfaults with VecElement with union element
- [x] #34806 - Profile: fix indent computation BoundsError
- [x] #34817 - Fix #34316
- [x] #34829 - fix #34826, unwrap VecElement when needed in `julia_const_to_llvm`
- [x] #34770 - Convert range type in `reduced_index`

### CODE REVIEW

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.3")`

**Comment by nanosoldier** [comment]
[Your test job](https://github.com/JuliaLang/julia/pull/34517#issuecomment-578505893) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/9d3dda3cad656b68e0e2bbed9af29c6df0d00e9a/pkgeval/by_hash/b963fac_vs_2e6715c/report.md). cc @maleadt

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.3")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs =":release-1.3")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/34517#issuecomment-582889960) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d52c6da7106c2e77f9c2c0df8f1026dda1f6522c/113211d_vs_2e6715c/report.md). cc @ararslan

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/34517#issuecomment-582794084) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/098a9b9c8007c0068768fd1e84de89a16957e93a/pkgeval/by_hash/4f81f94_vs_2e6715c/report.md). cc @maleadt

**Comment by tkf** [comment]
I'm sorry to make a noise at this late in the RC phase, but I think it might make sense to revert #33235. Please see #34732.

**Comment by staticfloat** [comment]
Actually, looking into this, we don't need to backport #34787.  This branch works just fine with LLVM assertions as-is.  I do find it a little bit weird that you need to set `BINARYBUILDER_LLVM_ASSERT=1`; I kind of feel that makevar should be eliminated and we should just use the value of `LLVM_ASSERT` instead.

**Comment by KristofferC** [comment]
So what do I need to do?

**Comment by staticfloat** [comment]
Nothing; Installing LLVM with asserts via BB is not broken on 1.4.

**Comment by KristofferC** [comment]
This should be good to go ones CI passes.

**Comment by JeffBezanson** [comment]
There is also #34770.

**Comment by KristofferC** [comment]
It is not on the milestone. Why is it a blocker?

**Comment by JeffBezanson** [comment]
Agreed; there is a bug fix there but it doesn't seem super critical.

**Comment by KristofferC** [comment]
Ok, it got merged to put in the commit in that PR that was asked to be backported.

**Pull request merged**
