### PR TITLE
make pending_perm a heap instead of sorted vector in optimizer

### PR DESCRIPTION
**Pull request by LilithHafner**
closes #46512

### CODE REVIEW

**Comment by LilithHafner** [comment]
@nanosoldier `runtests("inference" vs=":master")`

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("inference" vs=":master")`

**Comment by LilithHafner** [comment]
@nanosoldier runbenchmarks("inference", vs=":master")

**Comment by LilithHafner** [comment]
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46586#issuecomment-1234942338) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/7b16aaa_vs_31e4e26/report.md).

**Comment by LilithHafner** [comment]
Bump (c.f. https://github.com/JuliaLang/julia/pull/46679#issuecomment-1266400035). There doesn't seem to be much practical performance impact of this PR, but it is a theoretical improvement and more importantly, it reduces Core's dependency on Sort, which is needed for #46679.

Rerunning the one 7% performance regression
@nanosoldier `runbenchmarks(["inference", "allinference"], vs=":master")`

**Comment by LilithHafner** [comment]
@nanosoldier runbenchmarks(["inference"], vs=":master")

**Comment by LilithHafner** [comment]
Rerunning benchmarks after rebase
@nanosoldier `runbenchmarks(["inference"], vs=":master")`

**Comment by LilithHafner** [comment]
Rerunning benchmarks after rebase
@nanosoldier `runbenchmarks("inference", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/46586#issuecomment-1266552741) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/8384f4d_vs_c609e9a/report.md).

**Comment by oscardssmith** [comment]
I'm merging this today sans objections.

**Pull request merged**
