### PR TITLE
Bump LLVM tarballs on 1.4

### PR DESCRIPTION
**Pull request by staticfloat**
This rebuilds and upgrades the LLVM tarballs on 1.4, backporting some naming changes and such from 1.5, but functionally should be identical.

### CODE REVIEW

**Comment by staticfloat** [comment]
Hmmm, the win32 builder has failed the Distributed and SuiteSparse pretty regularly, despite my attempts to rebuild it.  I'm going to keep trying, but if I can't get it to go through I'm going to call this more than just bad luck.

**Comment by KristofferC** [comment]
I also reran it once with those failures.

**Comment by staticfloat** [comment]
Okay, it's happened enough times now that I think it's a real failure.

We're getting `EXCEPTION_ACCESS_VIOLATION` during the `Distributed` test suite pretty reliably, it seems to be happening in this test:

https://github.com/JuliaLang/julia/blob/4f718ae46432e3745aeb3030202b10fc01b188b1/stdlib/Distributed/test/distributed_exec.jl#L762-L779

We're getting another `EXCEPTION_ACCESS_VIOLATION` in the `SuiteSparse` tests here:

https://github.com/JuliaLang/julia/blob/4f718ae46432e3745aeb3030202b10fc01b188b1/stdlib/SuiteSparse/test/threads.jl#L3-L20

It looks threading related to me; I don't understand why this is failing now.

**Comment by staticfloat** [comment]
I've been unable to narrow this down any further.  I vote we release as-is.

**Comment by KristofferC** [comment]
Okay. Let's merge this, rerun CI on my backport branch, merge that if things look OK and release.

**Pull request merged**
