### PR TITLE
Use versioned UnicodeData.txt URL

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Should fix problems discussed in https://github.com/JuliaLang/julia/pull/18588#discussion_r93816369. @tkelman is there anything I need to do to have juliacache mirror this, or does that happen automatically?

### CODE REVIEW

**Comment by tkelman** [comment]
either use deps/tools/jldownload instead of the download function, or prepend juliacache to the url

**Comment by tkelman** [comment]
If we're going to cache it here, we should probably change https://github.com/JuliaLang/utf8proc/blob/15e1819cdd326639a49481eb105dee242de99104/data/Makefile#L38 to avoid caching it in utf8proc, otherwise we might get the wrong unicode version cached if the two repos ever don't match.

**Comment by tkelman** [comment]
We could also maybe think about adding `doc/deps` to the travis caching, might save a minute or so of cloning metadata on every build? Though we'd have to invalidate the cache if we ever change the unicode version. Could checksum it perhaps, delete and retry on a checksum mismatch?

**Comment by MichaelHatherly** [comment]
> to avoid caching it in utf8proc, otherwise we might get the wrong unicode version cached if the two repos ever don't match.

Would the versions ever not match?

**Comment by tkelman** [comment]
Yes, if we make the change in one place then it won't match until we change it in the other. Even if we change it in both places at the exact same time, you'd need to do so on every branch, and never re-run a commit from before doing that.

**Comment by MichaelHatherly** [comment]
Ok, that makes sense, thanks. So we just need to not cache this file in utf8proc by removing the prefixed `URLCACHE` on that line, should that be done prior to merging this PR?

**Comment by tkelman** [comment]
Could be done after. But we should probably checksum the file here with `jlchecksum` to be sure we're getting the expected content

**Comment by MichaelHatherly** [comment]
(Hopefully I've done that `jlchecksum` correctly, seems to work alright I think...)

**Review by tkelman — APPROVED** [review]

**Comment by stevengj** [comment]
Probably utf8proc should export some API to indicate what Unicode version it supports.

**Pull request merged**
