### PR TITLE
Update Pkg3

### PR DESCRIPTION
**Pull request by KristofferC**
- Fixes looking into `test/REQUIRE` when testing packages.
- Fixes a problem when packages try to load themselves during build time, e.g. `Homebrew`.
- Renames `checkout` to `develop`.
- Allow (unregistered and registered) packages to track branches or certain commits and be added from git repos, e.g:
```
    pkg> add Example#master
    pkg> add Example#c37b675
    pkg> add https://github.com/JuliaLang/Example.jl#master
```
- Allows using REPL commands even if not in a REPL with a string macro `pkg`, e.g. `using Pkg3; pkg"add Example"`. This gives access to the REPL Mode in e.g. IJulia.

Includes https://github.com/JuliaLang/julia/pull/26295 because standard libraries are now recorded in the Manifest and right now this is a but problematic when building the sysimg.

### CODE REVIEW

**Comment by KristofferC** [comment]
Anyone know what to make of the AV test failure? Looks like they timed out at 2h?

**Comment by KristofferC** [comment]
AV i686 timed out but that has happened on other PRs.

**Comment by bicycle1885** [comment]
This error may be related to this change:
```
~/v/julia (master|…) $ julia-dev
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.4515 (2018-03-09 10:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6f2c3699e0* (0 days old master)
|__/                   |  x86_64-apple-darwin16.7.0

pkg> help
[ Info: Pkg3 is still under development, please file issues at `https://github.com/JuliaLang/Pkg3.jl`.
ERROR: UndefVarError: PKG3_IS_PRECOMPILED not defined
Stacktrace:
 [1] print_first_command_header() at /Users/kenta/vendor/julia/usr/share/julia/site/v0.7/Pkg3/src/Pkg3.jl:20
 [2] tokenize(::String) at /Users/kenta/vendor/julia/usr/share/julia/site/v0.7/Pkg3/src/REPLMode.jl:171
 [3] do_cmd(::REPL.LineEditREPL, ::String) at /Users/kenta/vendor/julia/usr/share/julia/site/v0.7/Pkg3/src/REPLMode.jl:218
 [4] (::getfield(Pkg3.REPLMode, Symbol("##8#9")){REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /Users/kenta/vendor/julia/usr/share/julia/site/v0.7/Pkg3/src/REPLMode.jl:754
 [5] top-level scope
```

**Comment by KristofferC** [comment]
Yeah, sorry... Sigh, will fix.

**Pull request merged**
