### PR TITLE
Clarify which are is modified in mul/div.

### PR DESCRIPTION
**Pull request by simonbyrne**
My stab at addressing JuliaLang/LinearAlgebra.jl#338.

### CODE REVIEW

**Comment by mschauer** [comment]
While a legal identifier, `mulA!2(...)` looks to me much like an operation `mulA ! 2`, not like a function name.

**Comment by tkelman** [comment]
Aside from picking exactly what the names should be, I think this is a much better direction than what's on master. Mutating a different argument is a different operation, these shouldn't share the same generic function name when their results are dramatically different.

**Comment by JeffBezanson** [comment]
This is orthogonal to the changes on master. The changes on master affect the transposing part, not the mutation part.

**Comment by tkelman** [comment]
I'm aware. This is an improvement over both master and over release-0.6, though it would need to be rebased for the now-different name on master.

**Pull request closed without merging**
