### PR TITLE
RFC: Added find_extrema, ind_extrema

### PR DESCRIPTION
**Pull request by kmsquire**
Just adding parity:

`findmin/indmin <=> minimum`
`findmax/indmin <=> maximum`
`findextrema/indextrema <=> extrema`

~~It's named `find_extrema` because `findextrema` (and particularly `indextrema`) seemed less readable to me.~~ (Names no longer contain underscores.)

Just checking first if this is wanted.  If so, I'll add docs.  If not, please close.

**Edit: large bikeshedding spreadsheet [here](https://docs.google.com/spreadsheet/ccc?key=0AuYXP8SQ1FDndGxoNzlkYVA3MnhOYTg4TkNMZE52RWc&usp=sharing#gid=0)**

### CODE REVIEW

**Comment by mturok** [comment]
I haven't read through this entire thread, but what do people think about matlab's semantics for max?

http://www.mathworks.com/help/matlab/ref/max.html

Michael

**Comment by mbauman** [comment]
See #4235 for a history of the design.  A more recent discussion is at https://github.com/JuliaLang/julia/issues/9439#issuecomment-67837385.  I (as well as most folks here, I'd imagine) see Matlab's use of `max(A,[],dim)` as a signal to do something entirely different as a substantial wart in the design.  I'm not sure that our current division between `max` and `maximum` is optimal, but I like it a whole lot better.

**Comment by StefanKarpinski** [comment]
The basic issue is that Matlab's `max` function is both a binary operator like `+` and a reducer like `sum`; we ended up separating these two aspects of max into different functions: the binary operator `max` and the reducer `maximum`. I frequently type `max` when I want `maximum` but I do think the clean separation is a good thing.

**Comment by vtjnash** [comment]
It looks like Viral approved this PR already, and the dust has (mostly?) settled on the naming surrounding min/max/minimum/extrema/minmax (e.g. eliminating indmin). So this just needs a rebase.

**Comment by kmsquire** [comment]
Based on the original conversation, I'll rebase and change `findminmax` and `argminmax` back to  `findextrema` and `argextrema`, respectively.

**Comment by StefanKarpinski** [comment]
Yes, that seems consistent.

**Pull request closed without merging**
