### PR TITLE
Updated the assert checking Dict versions

### PR DESCRIPTION
**Pull request by eulerkochy**
Changed the assert in code, to incorporate a check on versions of the Dict

### CODE REVIEW

**Comment by KristofferC** [comment]
What was the reason you closed the previous PR https://github.com/JuliaLang/julia/pull/31097/files (that had the same changes as here)

Please try to keep working on the same PR instead of opening a new one. By reopening a new one the discussion on the earlier one is lost.

**Comment by eulerkochy** [comment]
There were a lot of unwanted commits in that PR. I just tried to submit a 'clean' PR this time! Sorry for the inconvenience!

**Comment by KristofferC** [comment]
You can always update an existing PR no matter how bad you mess it up.

**Comment by vtjnash** [comment]
> vtjnash: this a valid assert or should it be an error?

Is is a valid use of assert. If you follow the logic of the above function, it is logically impossible to happen, without memory corruption (however that could happen during race-y multithreading code—or equivalents such as finalizers and generator functions—hence the assert to kill the program).

**Comment by eulerkochy** [comment]
error thrown is suggestive of such an event, at least it gives a reason why the program will get terminated due to mismatch of `age` of the `Dict`

**Comment by KristofferC** [comment]
Yes but we want this to be an assert to allow it to potentially be removed in the future at some optimization level. That's the point of `@assert` over `error`.

**Comment by KristofferC** [comment]
Closing since the assert is valid (https://github.com/JuliaLang/julia/pull/31110#issuecomment-465226980)

**Pull request closed without merging**
