### PR TITLE
Stray double colon

### PR DESCRIPTION
**Pull request by jgrg**
Prevents doctest formatting of next paragraph.

### CODE REVIEW

**Comment by ivarne** [comment]
CC: @zhmz90 ref: https://github.com/JuliaLang/julia/commit/0a3cf4a64fc8f2d39370f5505939e2cb02c3fbbb.

**Comment by zhmz90** [comment]
Sorry, I didn't notice that double colon before.

**Comment by ivarne** [comment]
@zhmz90 No worries, (none of the reviewers caught the issue either). I just like to crosslink issues when I see something relevant. I just tought you might give this PR a thumbs up/down ?

**Comment by zhmz90** [comment]
@ivarne , This PR LGTM.  Anyway, I should check it after my PR is merged. 
The same errors can be found and fixed via simple text analysis.  I will try to add some code to check this.

**Pull request merged**
