### PR TITLE
increased compiler nospecialization

### PR DESCRIPTION
**Pull request by vtjnash**
Would be nice to more of this automatically (although these methods are tiny and usually inlined, so they don't end up  contributing much)

### CODE REVIEW

**Comment by KristofferC** [comment]
Out of curiosity, how do you measure the effects of these changes?

**Comment by JeffBezanson** [comment]
What's the effect on sysimg size and build time?

**Comment by vtjnash** [comment]
Hard to get statistical certainty since the build takes so long. But pretty small (partially since we filter out these `inlinable` methods when looking for things to precompile as a heuristic, to reduce the penalty of these, partially because we inline them most of the time anyways so we need to end up generating these signatures regardless).

basecompiler.ji : 18768564 bytes to 18695152 bytes

**Comment by vtjnash** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/27308#issuecomment-397036632):
```
NanosoldierError: failed to run benchmarks against comparison commit: failed process: Process(`make -j3`, ProcessExited(2)) [2]
```
Logs and partial data can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/0a5b676a73f93940987573c7abc0574ed389c118/699f1e3_vs_0658a11/report.md)
cc @ararslan

**Comment by vtjnash** [comment]
Not sure what happened there – the curl ./config script failed. @nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/27308#issuecomment-397108484) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e92764d4378008471e99cf30c27ff6ba8a1a2b0e/699f1e3_vs_0658a11/report.md). cc @ararslan

**Pull request merged**
