### PR TITLE
More error throwing tests for LAPACK!

### PR DESCRIPTION
**Pull request by kshyatt**
That's right, it's happening! Hopefully today `lapack.jl` can get to over 80% coverage. I added a bunch of error throwing tests!

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
The test failure was a timeout, but no tests had failed.

**Comment by StefanKarpinski** [comment]
Did someone restart this?

**Comment by tkelman** [comment]
Yeah, I did. We recently turned back on running the tests in parallel on win64 appveyor, and it occasionally does this (#7942). At least the other worker will go on and run the rest of the tests before waiting at parallel. And unlike Travis, AppVeyor does at least keep the old logs around if you find the build in the history.

**Comment by kshyatt** [comment]
Tests passed! Does this look ok to @andreasnoack, @tkelman, and @StefanKarpinski ?

**Comment by tkelman** [comment]
looks great to me

**Comment by andreasnoack** [comment]
Yes. Thanks.

**Comment by kshyatt** [comment]
`lapack.jl` is now officially in the YELLOW! **83%** test coverage. :tada:

**Comment by StefanKarpinski** [comment]
:tada: :balloon: :hatching_chick:

**Pull request merged**
