### PR TITLE
Rename searchsorted* functions to findsorted*

### LINKED ISSUE #24883: What to do with searchsorted* functions
As part of https://github.com/JuliaLang/julia/issues/10593, I have tried to find a way to unify `searchsorted`, `searchsortedfirst` and `searchsortedlast` with the rest of `find*` functions. In [the Search & Find Julep](https://github.com/JuliaLang/Juleps/blob/master/Find.md#particular-cases), I suggested replacing them with `find*` methods dispatching on a `Sorted`/`SortedVector` wrapper which would indicate that the input vector is sorted (see also https://github.com/JuliaCollections/DataStructures.jl/pull/290 for a similar but more powerful type).

For `searchsorted` itself, this plan would work quite well. It could be replaced with `find(equalto(needle), Sorted(haystack))`, which would just call a specialization of `find` which would return a range instead of a `Vector`, while still following the generic `AbstractArray` API.

The situation is more complex for `searchsortedfirst` and `searchsortedlast`. I'll detail the problems for the former, knowing that they are equivalent for the latter.  `searchsortedfirst` returns "the first value in a greater than or equal to x, according to the specified order". With the introduction of the `Sorted` wrapper, the specified order is the one passed when constructing the wrapper, which indicates how the underlying vector is sorted. So far, so good. But what kind of predicate can we use to reflect this order?
- It would be natural to replace `searchsortedfirst(needle, haystack)` with `findfirst(greaterthan(needle), Sorted(haystack))`, but then `greaterthan` cannot have any meaning on its own: it would depend on the order used by `haystack`, and "greater" could even mean "lower" if `rev=true`.
- We could use `findfirst(sortedafter(needle), Sorted(haystack))`, which would better reflect that the predicate has no intrinsic meaning. But then we lose the generality of the syntax: it cannot be used on an unsorted vector to find the first value greater than `x`, which defeats the idea of unifying functions.

Then there are other subtleties, but these are less serious:
- `greaterthan` should actually be `greaterthanorequalto` and `sortedafter` be `sortedatorafter` to accurately reflect the behavior of the function.
- `searchsortedfirst` has an internal variant which allow passing a start and end index indicating the range to be searched, but `findfirst` only accepts a start index. This feature is used by the sparse matrix code. It could be replaced with array views, or we could just have a method which is more flexible than the other `findfirst` methods.
- `searchsortedfirst(x)` returns `length(x)+1` when no match is found, while `findfirst` currently returns `0`, and may well return `nothing` in the future (https://github.com/JuliaLang/Juleps/issues/47). This doesn't sound like an issue, as the caller can easily replace `0` or `nothing` with `length(x)+1` without a significant performance cost if needed.

I would appreciate any help, especially from people who use these functions (I don't). If fixing this in time for 0.7 is too complex, we could unexport these functions (which are needed for sparse matrices), and move them e.g. to SortingAlgorithms.

### PR DESCRIPTION
**Pull request by nalimilan**
The name is consistent with the new API, as `search` no longer exists.
Also swap the two positional arguments for consistency with other functions.

Alternative approach to fix https://github.com/JuliaLang/julia/issues/24883. Replaces https://github.com/JuliaLang/julia/pull/25133, part of https://github.com/JuliaLang/julia/issues/10593.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
One reason I prefer the old names is that they implement "binary search", which is a commonly-recognized term.

**Comment by nalimilan** [comment]
Then they should be called `binarysearch`, not `searchsorted`. There's also the annoyance that the arguments are in reverse order compared with other functions.

**Comment by mschauer** [comment]
`findsorted` suggests the function looks for a sorted (sub-)sequence, if the name is an analogy to `findmax` (finding the maximum), `findlast` (finding the last occurence) etc.

**Comment by nalimilan** [comment]
For triage: the question of the name is somewhat secondary, what concerns me more is the fact that the order of arguments of the `searchsorted*` functions is currently the opposite of the `find*` functions. So there are two decisions to make:
- should we change the order of arguments for consistency
- should we use the occasion to rename the functions too

**Comment by StefanKarpinski** [comment]
My feeling is that we should just leave these alone. If we ever come up with a better coherent API using `find` functions and `SortedVector` types, that would be great, but at that point, we can just introduce that and have these as a legacy API until 2.0 comes around.

**Pull request closed without merging**
