### PR TITLE
deps: Upgrade OpenBLAS to v0.3.23

### PR DESCRIPTION
**Pull request by topolarity**
As requested by ~~@wsmoses~~ @giordano  [on Slack](https://julialang.slack.com/archives/C674ELDNX/p1680822624193059)

### CODE REVIEW

**Comment by wsmoses** [comment]
actually by mose, not me :P

**Comment by topolarity** [comment]
Haha! Sorry about that 😅

**Review by ViralBShah — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@topolarity Can you also update the checksums for the OpenBLAS from-source build?

**Comment by topolarity** [comment]
@DilumAluthge I'll fix that straight away.

Apologies for the oversight, and thanks for the heads up!

**Comment by mzy2240** [comment]
Will this PR backport to 1.9?

**Comment by ViralBShah** [comment]
Not unless there is a good reason. 1.10 is probably not going to take as long as 1.9 though.

**Pull request merged**
