### PR TITLE
add doc for all(p,A,dims) and any(p,A,dims)

### PR DESCRIPTION
**Pull request by PaulSoderlind**
to reducedim.jl

### CODE REVIEW

**Comment by PaulSoderlind** [comment]
This PR suggests documentation of the `all(p,A,dims)` and `any(p,A,dims)` methods.  One of the tests (buildbot/tester_linuxaarch64) fails, but I must admit I do not really know why.

**Comment by Keno** [comment]
Is it worth adding a section somewhere describing how all these `dims` keywords work, particularly in the presence of multiple dimensions, e.g. in `all(rand(Bool, 3, 3, 3); dims=(1,3))`. Maybe we have that somewhere already. If so, we should reference it.

**Comment by PaulSoderlind** [comment]
@Keno A quick look suggests that there is no such section, but someone might know better.

I did, however, notice that also `sum, prod, maximum, minimum` lack documentation of the `f(p,A,,dims)` methods.

**Comment by PaulSoderlind** [comment]
This PR now suggests documentation/examples of `fun(f,A;dims)`  versions of `any, all, sum, prod, maximum` and `minimum.` This just amounts to some more doc strings in `reducedim.jl`.

**Comment by StefanKarpinski** [comment]
Thanks for the doc improvements!

**Pull request merged**
