### PR TITLE
Clarify Cxx.jl. Update calling-c-and-fortran-code.md

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
It's a question, should Cxx.jl be rewritten out of the doc, or explained more here?

**Comment by petvana** [comment]
I'd remove `Cxx.jl` completely ... until it's supported again.

**Comment by ViralBShah** [comment]
Best to remove cxx.jl until we have a maintainer for it.

**Comment by PallHaraldsson** [comment]
Can you backport this to 1.9.0 (I see the docs are out), and maybe to 1.6 LTS, if not 1.7, 1.8?

**Pull request merged**
