### PR TITLE
🤖 [master] Bump the SparseArrays stdlib from 760989e to d99fcfe

### PR DESCRIPTION
**Pull request by DilumAluthgeBot**
Stdlib: SparseArrays
URL: https://github.com/JuliaSparse/SparseArrays.jl.git
Stdlib branch: main
Julia branch: master
Old commit: 760989e
New commit: d99fcfe
Julia version: 1.10.0-DEV
SparseArrays version: 1.10.0
Bump invoked by: @dkarrasch
Powered by: [BumpStdlibs.jl](https://github.com/JuliaLang/BumpStdlibs.jl)

Diff: https://github.com/JuliaSparse/SparseArrays.jl/compare/760989ec650761541deff039efb5b767a051c172...d99fcfed4fdf790057b648c47d7a9d55204213e1

```
$ git log --oneline 760989e..d99fcfe
d99fcfe Install Aqua.jl if necessary during CI (#356)
5d9b27c Test code quality, resolve ambiguities (#355)
c09f0ac Handle SuiteSparse >= 7 (#353)
f22cab0 fix doc spelling, grammar for lu (#352)
cb79e06 Clean up temporary fixes (#348)
195c470 Replace AbstractTriangular by UpperOrLowerTriangular (#329)
d938744 Fix "map does not respect sources index type" (#350) (#351)
38604c3 Fix bug where non-order keyword arguments are passed from `sort!` to `searchsortedfirst` (#335)
0d2d30a Keep `Hermitian(::Sparse) \ SparseArray` throwing (#322)
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Got exception outside of a @test
  | LoadError: ArgumentError: Package Aqua not found in current path.
  | - Run `import Pkg; Pkg.add("Aqua")` to install the Aqua package.
```

**Comment by DilumAluthge** [comment]
Oh I realize the issue. The Pkg.add needs to be done in the exact same job where Aqua is actually used.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaSparse/SparseArrays.jl/pull/357

**Comment by dkarrasch** [comment]
Superseded by #48934. Let's keep fingers crossed!

**Pull request closed without merging**
