### PR TITLE
Revert "Emulated `fma`"

### PR DESCRIPTION
**Pull request by DilumAluthge**
Reverts JuliaLang/julia#42783

This PR broke the `tester_win64` CI job on Buildbot.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I'm going to merge this when CI is passing, because currently every `tester_win64` CI job is failing on master.

**Comment by oscardssmith** [comment]
don't merge this  just merge reverting the added tests.

**Comment by DilumAluthge** [comment]
Can you make a PR?

**Comment by DilumAluthge** [comment]
Alternatively, instead of removing the tests in question, you could just skip them if running on 64-bit Windows.

**Comment by ViralBShah** [comment]
Disabling the tests only on win64 for now seems better.

**Comment by oscardssmith** [comment]
here you go. https://github.com/JuliaLang/julia/pull/42955.

**Comment by DilumAluthge** [comment]
Thank you!!

**Comment by fredrikekre** [comment]
Seems standard to revert the PR. If only the tests are reverted things are still broken...

**Comment by oscardssmith** [comment]
the reasoning behind reverting only the tests is that I think the test uncovered existing broken behavior rather than the pr introducing new breakage.

**Pull request closed without merging**
