### PR TITLE
TOML: print: handle mixed vector of dicts and non-dicts

### LINKED ISSUE #45340: TOML: Dict inside mixed vector produces invalid TOML
```julia
julia> import TOML

julia> d =  Dict("b" => Any[Dict("a" =>  222, "d" => 333)]);

julia> TOML.print(d)
[[b]]
a = 222
d = 333

julia> d =  Dict("b" => Any[111, Dict("a" =>  222, "d" => 333)]);

julia> TOML.print(d)
b = [111, a = 222
d = 333
]
```

This is invalid TOML syntax.

---

It looks like we have code to prevent mixing `Dict`s and other types in a vector, but it only throws an error if the *first* element is a `Dict`:

```julia
julia> d =  Dict("b" => Any[Dict("f" => 000), 111, Dict("a" =>  222, "d" => 333)]);

julia> TOML.print(d)
[[b]]
f = 0
[[b]]
ERROR: array should contain only tables
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] _print(f::Nothing, io::Base.TTY, a::Dict{String, Vector{Any}}, ks::Vector{String}; indent::Int64, first_block::Bool, sorted::Bool, by::Function)
   @ TOML.Internals.Printer /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/TOML/src/print.jl:160
 [3] #print#13
   @ /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/TOML/src/print.jl:168 [inlined]
 [4] print(a::Dict{String, Vector{Any}}; sorted::Bool, by::Function)
   @ TOML.Internals.Printer /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/TOML/src/print.jl:171
 [5] print(a::Dict{String, Vector{Any}})
   @ TOML.Internals.Printer /Applications/Julia-1.7 x86.app/Contents/Resources/julia/share/julia/stdlib/v1.7/TOML/src/print.jl:171
 [6] top-level scope
   @ REPL[7]:1
```

### PR DESCRIPTION
**Pull request by fonsp**
Fix #45340

### CODE REVIEW

**Comment by KristofferC** [comment]
All the tests added here passes for me (using Julia master).

**Comment by vtjnash** [comment]
So are you saying this was already fixed by https://github.com/JuliaLang/TOML.jl/pull/40?

**Comment by fonsp** [comment]
For me, the tests fail locally if I undo my change to `stdlib/TOML/src/print.jl`. I also checked against the Julia 1.9.0-alpha1 binary from julialang.org, where the second test fails. (The PR you linked is [included in 1.9.0-alpha1](https://github.com/JuliaLang/julia/pull/47448), right?)

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-alpha1 (2022-11-15)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> import TOML

julia> TOML.print(Dict("b" => Any[Dict("a" => 222, "d" => 333), 111]))
[[b]]
a = 222
d = 333
[[b]]
ERROR: array should contain only tables
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] print_table(f::Nothing, io::Base.TTY, a::Dict{String, Vector{Any}}, ks::Vector{String}; indent::Int64, first_block::Bool, sorted::Bool, by::Function)
   @ TOML.Internals.Printer ~/julia19/julia-1.9.0-alpha1/share/julia/stdlib/v1.9/TOML/src/print.jl:187
 [3] print_table (repeats 2 times)
   @ ~/julia19/julia-1.9.0-alpha1/share/julia/stdlib/v1.9/TOML/src/print.jl:128 [inlined]
 [4] #print#4
   @ ~/julia19/julia-1.9.0-alpha1/share/julia/stdlib/v1.9/TOML/src/print.jl:200 [inlined]
 [5] print(a::Dict{String, Vector{Any}}; sorted::Bool, by::Function)
   @ TOML.Internals.Printer ~/julia19/julia-1.9.0-alpha1/share/julia/stdlib/v1.9/TOML/src/print.jl:203
 [6] print(a::Dict{String, Vector{Any}})
   @ TOML.Internals.Printer ~/julia19/julia-1.9.0-alpha1/share/julia/stdlib/v1.9/TOML/src/print.jl:203
 [7] top-level scope
   @ REPL[2]:1

```

**Comment by KristofferC** [comment]
I must have messed up something with the copy-pasting then, the first and last work now but the middle still fails on master.

**Comment by fonsp** [comment]
Thanks for the quick merge! Should I make the same PR to TOML.jl?

**Comment by KristofferC** [comment]
Let's keep the development here. TOML.jl should probably be archived.

**Pull request merged**
