### PR TITLE
Unrolling zip for tuples

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
?

**Comment by fredrikekre** [comment]
> ?

Care to elaborate on that?

**Comment by bramtayl** [comment]
Just curious what people think

**Comment by KristofferC** [comment]
Imo it should be limited to small tuples.

```
julia> @time collect(zip((rand(1000)...), (rand(1000)...)));
  3.812658 seconds (4.30 M allocations: 180.623 MiB, 0.84% gc time)
```

**Pull request closed without merging**
