### PR TITLE
Extended compile-on-demand

### PR DESCRIPTION
**Pull request by pchintalapudi**
Just experimenting to see how many architectures we can try to support compile-on-demand for.

### CODE REVIEW

**Comment by gbaraldi** [comment]
On the m1 I get `JIT session error: Symbols not found: [ julia_foo_50 ]` from ` auto ptr = ES.lookup(search, getFunctionName(trampoline));` I imagine JITLink is doing something different here.

**Comment by pchintalapudi** [comment]
> On the m1 I get `JIT session error: Symbols not found: [ julia_foo_50 ]` from ` auto ptr = ES.lookup(search, getFunctionName(trampoline));` I imagine JITLink is doing something different here.

That's interesting, what sequence of commands is being issued to the REPL? JITLink shouldn't be affecting the results, since the latest commit operates only on the JITDylib level.

**Comment by gbaraldi** [comment]
```julia
julia> function foo()
              return 12
              end
foo (generic function with 1 method)

julia> @code_native dump_module=false foo()
JIT session error: Symbols not found: [ julia_foo_50 ]
WARNING: Unable to find function pointer
```

**Comment by gbaraldi** [comment]
Ok,  the tests also pass locally, but yeah it's on the latest commit and I still se that error:
```julia
julia> @code_native dump_module=false foo()
JIT session error: Symbols not found: [ julia_foo_67 ]
WARNING: Unable to find function pointer

julia> versioninfo()
Julia Version 1.9.0-DEV.427
Commit c6634f9c87 (2022-04-25 13:19 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 4
  JULIA_NUM_THREADS = 4
```

**Comment by pchintalapudi** [comment]
Can you build with `FORCE_ASSERTIONS=1`? Maybe it's an asserts/non asserts mismatch.

**Comment by gbaraldi** [comment]
I'm very confused to how the InteractiveUtils tests pass.
Force assertions build:
```julia
julia> Base.runtests(["InteractiveUtils"])
Running parallel tests with:
  nworkers() = 1
  nthreads() = 4
  Sys.CPU_THREADS = 2
  Sys.total_memory() = 16.000 GiB
  Sys.free_memory() = 2.053 GiB

Test         (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
InteractiveUtils  (1) |        started at 2022-04-25T18:05:19.677
InteractiveUtils  (1) |    10.76 |   0.29 |  2.7 |    2440.21 |   544.36

Test Summary: | Pass  Total   Time
  Overall     |  279    279  11.3s
    SUCCESS

julia> function foo()
              x = rand()

              return 12
              end
foo (generic function with 1 method)

julia> @code_native dump_module=false foo()
JIT session error: Symbols not found: [ julia_foo_58 ]
Assertion failed: (fptr != 0), function jl_dump_fptr_asm_impl, file disasm.cpp, line 576.

signal (6): Abort trap: 6
in expression starting at REPL[3]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 1440201 (Pool: 1439311; Big: 890); GC: 2
fish: Job 1, './julia' terminated by signal SIGABRT (Abort)
```

**Pull request closed without merging**
