### PR TITLE
treat CartesianIndex as a broadcast scalar

### LINKED ISSUE #38432: Make `CartesianIndex`s broadcast like scalars?
Following [this](https://discourse.julialang.org/t/tuples-of-cartesianindex-and-broadcasting/50093) Discourse discussion, I'd like to propose to make `CartesianIndex`s broadcast like scalars. That is, since
```julia
julia> 1 .+ (2, 3)
(3, 4)
```
works, so should
```julia
julia> CartesianIndex(1,1) .+ (CartesianIndex(2,2), CartesianIndex(3,3))
```
(which currently errors, but should, in my opinion, result in `(CartesianIndex(3, 3), CartesianIndex(4, 4))`)

### PR DESCRIPTION
**Pull request by stevengj**
Fixes #38432 and #41540.

### CODE REVIEW

**Comment by stevengj** [comment]
CI `Error in testset Downloads` seems to be unrelated.

**Comment by stevengj** [comment]
Ping @mbauman.

**Comment by stevengj** [comment]
Rebased.

**Comment by mbauman** [comment]
I don't think we need triage here — this is pretty unobjectionable.  Let's just do this!

**Review by mbauman — APPROVED** [review]

**Comment by stevengj** [comment]
rebased

**Pull request merged**
