### PR TITLE
Ensure that `collect(::AbstractArray)` always returns an `Array`

### PR DESCRIPTION
**Pull request by timholy**
The docstring specifies that the return type is `Array`, but `similar` isn't guaranteed to return an `Array`. (Exceptions include AxisArrays, OffsetArrays, etc.)

This is both a bugfix and a behavior change. I'll leave it to others to decide whether this can be merged in 0.6.

### CODE REVIEW

**Comment by timholy** [comment]
@tkelman, to determine whether the behavior change would break anything, perhaps we could have a PkgEval run of this? (With regards to merging in 0.6, the "behavior change" situation here is similar to #20720. Though in this case there's a docstring saying how it is supposed to behave, but isn't.)

**Comment by tkelman** [comment]
Sure, fired that off now, should be done later today. Once I have a good place hooked up to run these I should get it set up so we can trigger comparison runs automatically.

**Comment by tkelman** [comment]
https://gist.github.com/21f2c1ad2ea384895b6cffcef1d5d530
ImageCore might just be a too-tight tolerance? And I think ReverseDiff timed out and was terminated on the baseline run.

**Comment by timholy** [comment]
That's awesome. The ImageCore failure was just in benchmarks, not functionality (and the failure is almost certainly noise, this PR should have no impact on that test).

So it seems like this is unlikely to hurt anyone. Unless objections arise, I'd propose we merge this for 0.6.

**Pull request merged**
