### PR TITLE
Fix #10284: Add header_string option to writedlm()

### LINKED ISSUE #10284: Add header option to writedlm() and related
Sometimes we need to attach extra information to the data we're dumping:

``` julia
writecsv("foo.dat", data, header="This is the data...\nMeta info: ...")
```

Currently this is not possible.

### PR DESCRIPTION
**Pull request by juliohm**

### CODE REVIEW

**Comment by juliohm** [comment]
@tkelman is everything ok now?

**Comment by tkelman** [comment]
Yeah, the docs look good. No one responded to https://github.com/JuliaLang/julia/issues/10284#issuecomment-156849487, so it sounds not yet decided whether this keyword should be `header_string` or just `header` ?

**Comment by tanmaykm** [comment]
`header` seems to be the most aggreable option. Let's go with that?

**Comment by juliohm** [comment]
To rename it to `header` we need to change the implementation a bit as it is assuming a type for each option name. I can try do that later, no much time right now. Feel free to contribute.

**Comment by ninjin** [comment]
Sorry to chime in a bit at random and slightly late.  I think `header` would be the preferable name, but more importantly, is there any reason why we would not also want to accept an iterable collection of strings as a `header` argument?

**Comment by juliohm** [comment]
@ninjin what is the usage you have in mind? I don't see demand for an iterable collection here. This is more like a sugar option to make our lives easier:

```julia
open("foo.dat", "w") do f
  write(f, "header string")
  writedlm(f, array)
end
```
versus
```julia
writedlm("foo.dat", array, header_string="header string")
```

**Comment by nalimilan** [comment]
I guess what he had in mind is passing a vector of column names, and having the function join them using the field separator.

**Comment by ninjin** [comment]
@nalimilan: Yes, that is what I had in mind.  I can easily envision a use-case where you want to use the same header multiple times:

    hdr = ("Foo", "Bar", "Baz")
    open("smaller", "w") do f
        writedlm(f, rand(17, 3), header=hdr)
    end
    open("larger", "w") do f
        writedlm(f, rand(4711, 3), header=hdr)
    end

You could argue that the user should use `hdr = join(("Foo", "Bar", "Baz"), sep)`, but I find it far more elegant to handle the separator inside of `writedlm`.

**Comment by juliohm** [comment]
Sorry, I don't have the time to work on this pull request, I will close it so that other people can contribute.

**Pull request closed without merging**
