### PR TITLE
Move discussion about abstract types in fields from FAQ to performances

### PR DESCRIPTION
**Pull request by matthieugomez**
without reorganizing anything else in the performances page [av skip]

### CODE REVIEW

**Comment by matthieugomez** [comment]
The whole point of this pull request is to simply warn against abstract fields in composite type. It's one of the key point to write performant codes in Julia, and it's currently not mentioned there. Why should I do to have this merged?

**Comment by pao** [comment]
The bump is good--this just needs someone to review and agree that it's a good idea to make this change.

**Comment by matthieugomez** [comment]
Thanks!

**Comment by tkelman** [comment]
I believe the underlines need to be the same length as the titles in rst

**Pull request merged**
