### PR TITLE
Docs: Wording cleanup to mathematical-operations.md

### PR DESCRIPTION
**Pull request by NHDaly**
Cleanups as followups to #21338.

### CODE REVIEW

**Comment by NHDaly** [comment]
I'm not sure how to do a follow-up PR?

I branched from the other branch. Will that work okay on your end if you merge the other PR first, or is there some way to mark it in GitHub as depending on the previous PR?

**Comment by ararslan** [comment]
You can simply add commits to your other PR rather than opening a new one.

**Comment by stevengj** [comment]
Or wait until the other PR is merged to do a PR with separate changes.

**Comment by Sacha0** [comment]
Bumping for rebase with #21338 merged. Best!

**Comment by NHDaly** [comment]
rebased!

**Review by tkelman — APPROVED** [review]
lgtm thanks

**Pull request merged**
