### PR TITLE
add keepzeros option in sparse

### PR DESCRIPTION
**Pull request by matthieugomez**
issue #12605

### CODE REVIEW

**Comment by tkelman** [comment]
Please squash the commits here. This could use quite a few more tests, and documentation. This should probably be benchmarked as well to check whether the addition of a keyword argument makes a noticeable difference to the performance of `sparse`. There are some packages, Convex.jl as one example, that spend quite a bit of time calling `sparse` in inner loops.

**Comment by ViralBShah** [comment]
I would like to hold this till 0.5, and not want to do it this late.

There is the obvious issue here that the moment you do some other sparse matrix operation that uses this matrix, the zeros will get squeezed out in the result. Once 0.4 is done, I would like to revisit the design issues with stored zeros.

**Comment by matthieugomez** [comment]
Again, I'm perfectly fine with manipulating internals using only rowvals zrange and nonzeros afterwards to get an efficient code & keep the zeros. I then use some matrix multiplication / division. These operations keep the structural zeros right?

**Comment by ViralBShah** [comment]
Not at the moment.

**Comment by mlubin** [comment]
This is a really important and useful feature to have, but I agree that it's past the window for getting into 0.4.

**Comment by ViralBShah** [comment]
@tkelman What do you think we should do here?

**Comment by tkelman** [comment]
Gradually move away from matlab's approach to stored zeros and more towards a scipy design. A keyword argument might not be the best way to accomplish this though.

**Comment by ViralBShah** [comment]
Ok - perhaps the hybrid is not a great approach. Let's just do that slowly and hopefully by the 0.5 release.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/14798 covers this and a bit more, so closing. Sorry this didn't go in as-is @matthieugomez.

**Comment by matthieugomez** [comment]
Thanks!

**Pull request closed without merging**
