### PR TITLE
add `div` functions for BigFloats

### PR DESCRIPTION
**Pull request by simonbyrne**
As we can directly control the rounding mode, this is fairly straightforward.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Okay, not sure what's going on with appveyor here.

**Comment by quinnj** [comment]
Same thing I just saw on the mmap PR; 32-bit works fine, 64-bit times out.

**Comment by tkelman** [comment]
#11818 which I just merged a mitigation for, but the complete fix probably requires getting to the bottom of #7942 (Jameson might be close)

**Comment by simonbyrne** [comment]
Any objections to merging this?

**Pull request merged**
