### PR TITLE
Include latest 7zip version  v18.05

### PR DESCRIPTION
**Pull request by musm**
Current version is 16.04 (from ~2 years ago)
Bump it up to the latest version available

See changelog for improvements https://www.7-zip.org/history.txt

### CODE REVIEW

**Comment by musm** [comment]
restarting for av

**Comment by musm** [comment]
any objections?

**Comment by PallHaraldsson** [comment]
>any objections?

Seems ok, except I notices http:// used. Why not https:// ? This link redirects to such, but not all; and even though it does, it seems like a candidate for-man-in-the-middle attack.

There seems to be no preference to NOT use https:// as I see such a link in the makefile.

I checked, and all of the http links work as https too (at least currently); except for the one in a comment that doesn't work either way...

**Comment by musm** [comment]
Thanks for the feedback. I prefer we make a wholesale change in a separate PR to use https for downloads.

**Comment by musm** [comment]
merge ?

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
thank you @StefanKarpinski

**Pull request merged**
