### PR TITLE
deprecate precedence of `&` and `|`. for #5187

### PR DESCRIPTION
**Pull request by JeffBezanson**
This will allow us to change the precedence of these operators.

This change is certainly unnatural for bit twiddling; writing `x & mask == 0` you definitely expect `&` to happen first. We do more bit masking in Base than I expected.

What should we do about `⊻`? Here it still has `+` precedence, but it seems a bit odd for it to have wildly different precedence than `&` and `|`.

### CODE REVIEW

**Comment by vtjnash** [comment]
> What should we do about...

It seems this PR partially also introduces support for detecting "ambiguous precedence"? I think I'm vaguely in favor of just requiring parens around some of the other combinations of operations (I'm mainly thinking of combinations of bitwise and arithmetic operators here, like `a + b << c`).

**Comment by Sacha0** [comment]
One of the things that https://github.com/JuliaLang/julia/pull/25180 taught me is that defensive parens seem the rule rather than the exception, so I am vaguely with `@vtjnash` :).

**Comment by JeffBezanson** [comment]
Yes, after this experience I agree we should have ambiguous precedence errors and maybe some cases of non-transitive precedence.

**Comment by ararslan** [comment]
Precedence change aside, I just want to point out how much clearer I think the code looks with parentheses for these operations. :+1:

**Comment by JeffBezanson** [comment]
Triage prefers `.&&` and `.||` for the original desired application of this, which can be added later non-breaking.

We *also* would like to have ambiguous precedence errors at some point in the future, but it seems a bit half-assed to only add this for `&` and `|` right now. Can be added during 1.x by having the warnings off by default and opt-in until 2.0.

**Comment by fredrikekre** [comment]
The added parenthesis helps with visual parsing IMO, worth merging that?

**Pull request closed without merging**
