### PR TITLE
Extend description of allowed `@fastmath` transformations

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by kshyatt** [comment]
Bumping this.

**Comment by ViralBShah** [comment]
I think this should be ok to merge. @eschnett Can you revise if necessary?

**Comment by eschnett** [comment]
@ViralBShah I haven't looked at this in some time. I don't know whether LLVM changed in the mean time or not.

**Comment by ViralBShah** [comment]
Perhaps @chriselrod is more familiar with some of these things nowadays. Or @YingboMa.

**Comment by chriselrod** [comment]
Should we link the [https://llvm.org/docs/LangRef.html#fast-math-flags](LLVM fast-math docs)?
It may make sense to give warnings of examples how it can cause incorrect results (e.g. Kahan summation), or decrease performance:
```julia
julia> function vdiv!(x, y, a)
           inva = inv(a)
           @inbounds for i ∈ eachindex(x, y)
               x[i] = y[i] * inva
           end
           x
       end
vdiv! (generic function with 1 method)

julia> function vdiv_fast!(x, y, a)
           @fastmath inva = inv(a)
           @inbounds for i ∈ eachindex(x, y)
               @fastmath x[i] = y[i] * inva
           end
           x
       end
vdiv_fast! (generic function with 1 method)

julia> using BenchmarkTools

julia> y = rand(200); x1 = similar(y); x2 = similar(y); a = 1.6;

julia> @benchmark vdiv!($x1, $y, $a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     14.653 ns (0.00% GC)
  median time:      14.674 ns (0.00% GC)
  mean time:        14.694 ns (0.00% GC)
  maximum time:     42.988 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     998

julia> @benchmark vdiv_fast!($x2, $y, $a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     103.906 ns (0.00% GC)
  median time:      104.202 ns (0.00% GC)
  mean time:        104.319 ns (0.00% GC)
  maximum time:     130.912 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     937

julia> x1 ≈ x2
true
```

**Comment by ViralBShah** [comment]
Currently this is just comments for the fastmath.jl file. It makes sense to add that link as it would help people looking at this code. The examples seem like they would be nice to add to the relevant documentation sections.

**Comment by ViralBShah** [comment]
Here's the LLVM fastmath flags reference: https://llvm.org/docs/LangRef.html#fast-math-flags

**Pull request merged**
