### PR TITLE
ulimit the max open pipes during testing

### LINKED ISSUE #19132: test for fd exhaustion fails if ulimit is configured to allow too many open file descriptors
Added in #17824. As @yuyichao noted in https://github.com/JuliaLang/julia/commit/3cfd1e418b65e5dfb41c40b7a7b4016b814a43d6#commitcomment-18549600, the test should probably set the ulimit first so that FD exhaustion is guaranteed. cc @vtjnash

### PR DESCRIPTION
**Pull request by vtjnash**
fix #19132 

it seems that travis may suddenly have changed the default ulimit here, so the test is now failing on their default configuration

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like this doesn't fix the spawn testset issue on Travis?

**Comment by tkelman** [comment]
travis doesn't run the tests via the makefile

**Comment by vtjnash** [comment]
@tkelman looks like this is going to pass all the tests. merge when it does?

Appveyor link, since it seems to be missing from the PR, is https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.7908

**Comment by ararslan** [comment]
The tests are passing on Linux, but the OS X build stalled while upgrading Homebrew. However, the `spawn` tests are now failing on Windows.

**Comment by tkelman** [comment]
can this be done in runtests.jl or test/spawn.jl? this will still fail Base.runtests("spawn")

**Pull request merged**
