### PR TITLE
streams: disable half-duplex operation support

### LINKED ISSUE #41942: Sockets test fail on FreeBSD 12
It seems https://github.com/JuliaLang/julia/pull/40783 broke one of the Sockets tests on FreeBSD 12: https://github.com/JuliaLang/julia/blob/0224c42bce6daec1b5580b8a8a6b43f9437d2cee/stdlib/Sockets/test/runtests.jl#L524

Following along the steps taken in the tests,
```julia
p = Pipe()
Base.link_pipe!(p)
write(p, "hello")
read(p, Char)
read(p, Char)
@async begin
    write(p, "w")
    while p.out.status != Base.StatusOpen
        yield()
    end
    close(p.in)
end
readuntil(p, 'w')
eof(p)
```
you'll get `true` from the final EOF check on any platform. However, `p.out.status` is `Base.StatusEOF` on FreeBSD with and `Base.StatusClosed` on macOS. Prior to #40783, `p.out.status` was `Base.StatusClosed` on both platforms.

### PR DESCRIPTION
**Pull request by vtjnash**
Replaces #42004
Replaces #41983
Fixes #41942
Refs #40783

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Let's see how https://github.com/JuliaLang/BumpStdlibs.jl/pull/55 fares.

**Review by DilumAluthge — APPROVED** [review]
This fixes the hangs on Linux x86_64. See e.g. https://github.com/JuliaLang/BumpStdlibs.jl/pull/55

**Comment by ararslan** [comment]
Confirmed that this indeed fixes the FreeBSD Sockets tests. (CI has been in sufficiently poor shape that I'm not sure we would have been able to tell without checking manually.) Thanks!

**Review by ararslan — APPROVED** [review]
❤️

**Pull request merged**
