### PR TITLE
Clarify non-Unicode Korean tests

### PR DESCRIPTION
**Pull request by staticfloat**
This is the recommended locale by Arch Linux, so let's look for it as
well

### CODE REVIEW

**Comment by staticfloat** [comment]
This, combined with a rootfs image bump including the bits from https://github.com/JuliaCI/rootfs-images/pull/208 will help us to silence CI warnings such as https://buildkite.com/julialang/julia-master/builds/13227#01819c05-81fc-4bd9-bb58-7f7872193d6c/560-843

**Comment by vtjnash** [comment]
This would sort of defeat the comment there which says not to use Unicode here

**Comment by staticfloat** [comment]
I was confused by that comment, because the output of our tests seems to be identical across every korean locale I can find:

```
julia> korloc = ["ko_KR.UTF-8", "ko_KR.EUC-KR", "ko_KR.CP949", "ko_KR.949", "Korean_Korea.949"]
       withlocales(korloc) do locale
           s = Libc.strftime(0.0)
           @info(locale, s, bytes2hex(sha256(s)))
       end
┌ Info: ko_KR.UTF-8
│   s = "1970년 01월 01일 (목) 오전 12시 00분 00초"
└   bytes2hex(sha256(s)) = "d0117d51da3a9a0953e0b504207190950c3d664688743a103c95584148f99092"
┌ Info: ko_KR.EUC-KR
│   s = "1970년 01월 01일 (목) 오전 12시 00분 00초"
└   bytes2hex(sha256(s)) = "d0117d51da3a9a0953e0b504207190950c3d664688743a103c95584148f99092"
┌ Info: ko_KR.cp949
│   s = "1970년 01월 01일 (목) 오전 12시 00분 00초"
└   bytes2hex(sha256(s)) = "d0117d51da3a9a0953e0b504207190950c3d664688743a103c95584148f99092"
```

This was generated with a `locale.gen` that I made that looks like the following:
```
ko_KR.EUC-KR EUC-KR
ko_KR.UTF-8 UTF-8
ko_KR.cp949 CP949
```

If we're wanting to test codepoint output that is explicitly not UTF-8, I think we need a different test, because these all output the exact same UTF-8.

**Comment by staticfloat** [comment]
Alright, I've switched this PR to instead clarify some things and adds tests (where appropriate) to ensure that we don't just get `en_US.UTF-8` back.  I've also [updated the Linux testers](https://github.com/JuliaCI/julia-buildkite/commit/ecb55fbcc1f0dc7a41b1793dd781712aa12eedc1) to use the [new rootfs images](https://github.com/JuliaCI/rootfs-images/commit/1571a26f1141d452f534ed716965544106e74c3a#diff-cc4ef2642e382fe22379884f3c9abb8bcaf13c267b84eaa262f416b52abd3615R26-R29) that include `ko_KR.EUC-KR` baked in.  We should see the linux testers now no longer print the warning that these tests are being skipped.

**Comment by staticfloat** [comment]
Confirmed working.  Compare the previous `master` build:

https://buildkite.com/julialang/julia-master/builds/13308#0181ad71-e4f7-4efe-be37-0d90aa7357c3/568-842

Versus this build:

https://buildkite.com/julialang/julia-master/builds/13325#0181b08b-f047-42c0-a3c3-500d6f325827/564-838

**Comment by staticfloat** [comment]
@vtjnash Does this look better now?  Thanks for helping me to understand the purpose behind this test.  I've done my best to encode that in comments in the source as well.

**Review by vtjnash — APPROVED** [review]

**Pull request merged**
