### PR TITLE
fix loading of top level packages

### PR DESCRIPTION
**Pull request by KristofferC**
@StefanKarpinski likely knows how to test this better than me.

Comes from loading a project with the content of `Project.toml`:

```
name = "HelloWorld"
uuid = "dbdbde66-2db4-11e8-25a8-2729b3326f29"
```

and file structure in pwd:

```
├── Project.toml
└── src
    └── HelloWorld.jl
```

This used to error.

### CODE REVIEW

**Review by StefanKarpinski — COMMENTED** [review]
This seems correct but feels a bit nasty. I may take a crack at fixing this in a slicker way. But you've verified that this fixes the issue?

**Comment by KristofferC** [comment]
I don't know why it is nasty. It mostly just fixes the bug where `root_name == name && return root_uuid` was in the wrong place (had to be inside a `[` section).

**Comment by StefanKarpinski** [comment]
🤷‍♂️  I just spent a lot of time and thought on making these file parsing routines as clean and minimal as I could so I have some feels about them that I should probably let go of.

**Comment by KristofferC** [comment]
Just do whatever you feel fit here that makes this not nasty as long as it doesn't require having a `[` in the file to load a top level package.

**Comment by StefanKarpinski** [comment]
I think the minimal fix is to change `return false` to `return root_name == name && root_uuid`. However, I want to do some more thorough testing and I found another bug at the same time.

**Comment by KristofferC** [comment]
Yeah, my thought was that we could exit early if we found both the name and a new uuid, so there is no need to go through the whole file.

**Pull request closed without merging**
