### PR TITLE
rand() returns original array type

### PR DESCRIPTION
**Pull request by aplavin**
Eg `rand(StructArray(...), 10)` now returns a structarray.

### CODE REVIEW

**Comment by ViralBShah** [comment]
cc @rfourquet

**Comment by rfourquet** [comment]
Please expand on the motivations for this change. 
I'm a priori mildly against, as so far, for better or worst, we decouple the specification of the sample space from the output container type.

Also, with the proposed change, we would need to think about other types too, like should `rand(Set(1:9), 2)` return a set?

In the meantime, the `RandomExtensions` package has some functions to specify the ouput container type.

**Comment by maleadt** [comment]
> Please expand on the motivations for this change.

It would be useful for GPU packages, which now provide their own, non-exported version of these functions (e.g. `CUDA.rand`). That makes it somewhat harder to write generic code. Similar for functions like `ones`, `zeros`, `fill` (not all of which have an in-place version), etc.

**Comment by ViralBShah** [comment]
cc @rfourquet

**Comment by jakobnissen** [comment]
This is arguably breaking. Currently, we have:
```julia
julia> x = Set(1:3); typeof(rand(x, 1))
Vector{Int64} (alias for Array{Int64, 1})

julia> x = (1,2); typeof(rand(x, 1))
Vector{Int64} (alias for Array{Int64, 1})

julia> x = 1:3; typeof(rand(x, 1))
Vector{Int64} (alias for Array{Int64, 1})

julia> x = Base.OneTo(4); typeof(rand(x, 1))
Vector{Int64} (alias for Array{Int64, 1})

julia> x = falses(10); typeof(rand(x, 1))
Vector{Bool} (alias for Array{Bool, 1})
```

E.g. it always returns `Array`. Even if not breaking for new user-specified types, it would be highly surprising if most Base types returned `Array`, and a few user-defined ones didn't. Also, the documentation specifies:

> Pick a random element or array of random elements [ ... ]

Futhermore, if this PR is merged, it then becomes impossible to simply ask for an `Array` of random values, since that is what `rand` was supposed to do. If this is to go in Base, I would much prefer it be a new method.

**Comment by Seelengrab** [comment]
Triage thinks this should not be in Base - if you already have `rand!` defined for your custom `<: AbstractArray`,  calling that on an existing object is more consistent with the API and how it should be used than extending the contract of `rand`.

**Comment by StefanKarpinski** [comment]
This seems like it would have to be opted into—this wouldn't work for many kinds of arrays so it's a bad default. Even for the array types that it makes sense for like StructArrays, there's a more efficient implementation that samples indices and directly slices the components of the sampled array to directly construct the array of samples.

**Comment by rfourquet** [comment]
Oups, I forgot to press on the "Comment" button few weeks ago:
> Just to clarify, I totally think that it's useful to be able to specify the return type. I'm just not sure conceptually why we should tie the sample space type to the output type. Of course it makes sense in some cases to have both types match, but it's not obvious to me that it should be the default. 

But I agree though that's with the status quo, it's cumbersome to achieve what this PR does generically, whereas if this PR was merged, it would be easy to add a way to specify the output type to get back the current behavior, e.g. like in RandomExtensions.jl : `space = bitrand(10); rand(space, Vector, 99)` will return a `Vector{Bool}`, whereas `rand(rand(Bool, 10), BitVector, 99)` will return a `BitVector`.

> Opted into by package authors? Users? How exactly?

I would say users, but "how" remains to be determined.

**Comment by Seelengrab** [comment]
> What are these array kinds?

> What are some array types that it doesn't make sense?

Well, ranges for one - `rand(1:10, 5)` can't possibly return a range.

> But I agree though that's with the status quo, it's cumbersome to achieve what this PR does generically, whereas if this PR

Why? `rand!` exists, and this is exactly the kind of case it should be used in. Construct the object and fill it, instead of having `rand` construct the object (which it may not know how to do - how an array is constructed is not part of the `AbstractArray` API after all).

**Comment by rfourquet** [comment]
> Why? rand! exists

For the case where you want the `similar` behavior of this PR, you have to do `let x = ...; rand!(similar(x, dims), x); end`, maybe not "cumbersome" but inconvenient enough that you want a dedicated function if you do that repeatedly.

**Comment by rfourquet** [comment]
I will close as there is not enough support for this change, and it would be slightly breaking (e.g. `rand(bitrand(3), 3)` would now return a `BitVector`), so this change can't be done lightly. 

I still agree that some functionality is missing in `Random` to specify return types; for what is proposed here specifically, a dedicated function might later be added, e.g. `randomize(x)` would return an object of the same type and same "characteristics" as `x`, e.g. `randomize(x::BitVector)` would be equivalent to `BitVector(rand(x), length(x))`, while `randomize(x::String)` would be equivalent to `randstring(x, length(x))` and `randomize(x::Int)` equivalent to `rand(Int)`. I'm not sure such function belongs to `Random` though, it might be better off implemented first in a package.

**Pull request closed without merging**
