### PR TITLE
Remove JL_GC_MARKSWEEP option

### PR DESCRIPTION
**Pull request by yuyichao**
1. We don't really need it
2. It doesn't compile anymore and I don't think we should try to keep it

@vtjnash @carnaval

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
+1

**Comment by JeffBezanson** [comment]
Yeah +1

**Comment by vtjnash** [comment]
> We don't really need it

it helped me with porting julia to ppc, until I could figure out why the gc was corrupting memory on that platform

> It doesn't compile anymore and I don't think we should try to keep it

but on the other hand, its generally not much work to patch back it back into a working state

**Comment by JeffBezanson** [comment]
> until I could figure out why the gc was corrupting memory on that platform

What was needed for that, exactly? Would it have been enough just to disable collection?

**Comment by StefanKarpinski** [comment]
Can't you just turn off the GC with `gc_enable(false)` and achieve the same effect?

**Comment by vtjnash** [comment]
i think it may have been enough just turning on MEMDEBUG, but hindsight is 20/40 (since I don't actually remember all the specifics)

**Comment by StefanKarpinski** [comment]
So the question is whether there's anything this remains useful for that we don't have a better approach to, like turning off GC via `gc_enable(false)` or turning on MEMDEBUG.

**Comment by tkelman** [comment]
> hindsight is 20/40 (since I don't actually remember all the specifics)

keep notes, man

**Pull request merged**
