### PR TITLE
Disable startup files in misc. tests that spawn julia_cmd

### PR DESCRIPTION
**Pull request by musm**
Some of these tests were failing for me when running locally since I have a custom startup file.

### CODE REVIEW

**Comment by musm** [comment]
any objections?

**Comment by StefanKarpinski** [comment]
Seems correct to me. Who might be good to review it?

**Review by KristofferC — APPROVED** [review]

**Comment by musm** [comment]
anyone want to restart appveyor, x86 failure looks like a fluke

**Comment by musm** [comment]
merge?

**Pull request merged**
