### PR TITLE
Update modules.md

### PR DESCRIPTION
**Pull request by yig**
The table showing what symbols are available is wrong, according to my tests. I am still learning Julia, so I don't know how to update the "Available for method extension" column.

### CODE REVIEW

**Comment by NHDaly** [comment]
> I am still learning Julia

Hi! I'm happy to hear you're learning julia! :D Hope you're enjoying it!


---

I don't think the table is wrong... Here is an example showing it's behavior:

```julia
julia> import Random: uniform

julia> Random.uniform
ERROR: UndefVarError: Random not defined

julia> uniform
uniform (generic function with 1 method)

julia> using Random: uniform

julia> Random.uniform
ERROR: UndefVarError: Random not defined

julia> uniform
uniform (generic function with 1 method)
```

The only way to reference them through the module as you describe is to explicitly `import Random` or `using Random`. Then the name `Random` becomes available. This allows referencing _any_ member of `Random` through the qualified name:
```julia-repl
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-rc2.0 (2019-01-13)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> import Random

julia> Random.uniform
uniform (generic function with 1 method)

julia> uniform
ERROR: UndefVarError: uniform not defined
```

**Comment by yig** [comment]
Interesting. Say I put my module in a file `MyModule.jl`:

```
module MyModule

export foo

function foo()
    println("foo()")
end

end
```

If I access it via `include("MyModule.jl")` and then use a relative using/import (prefix `MyModule` with a `.` on the `using` or `import` line), then it behaves according to my pull request. If I access it via `push!( LOAD_PATH, "." )` before the `using` or `import` line, then it behaves the way this documentation suggests. Why would they be different?

**Comment by fredrikekre** [comment]
> Why would they be different?

The difference is that the module reference `MyModule` is made available from the `include`, so it is not the `using` statement that brings `MyModule` into scope.

**Comment by yig** [comment]
Ah, that makes sense. Thank you for clearing this up. Sorry about the noise.

**Pull request closed without merging**
