### PR TITLE
bump MPFR to 4.0.2

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by ViralBShah** [comment]
A bit unrelated to this PR, but as we move to BB for all julia deps, will we still need to bump things like this?

**Comment by simonbyrne** [comment]
Probably a question for @staticfloat?

**Comment by staticfloat** [comment]
I don’t think we’re quite to the point of removing building from source as being the default way of getting Julia put together. The BB tarballs are more of a convenience/CI tool than the primary way to
build Julia.

**Comment by StefanKarpinski** [comment]
> The BB tarballs are more of a convenience/CI tool than the primary way to build Julia.

I would actually very much like to switch to using BB tarballs by default. I don't think it will be truly reliable until we have everyone doing it that way. What's the downside? I think I've built LLVM and OpenBLAS and FFTW enough times in my life at this point.

**Comment by staticfloat** [comment]
I think it comes down to an internal bias I have against downloading binary blobs during the build of an opensource project.  But as long as we ensure that a `make FROM_SOURCE=1` or something works, we could definitely have it auto-download tarballs.

**Comment by StefanKarpinski** [comment]
We should definitely keep the build everything option working but we can test that like once a day or only for changes that affect makefiles or the `deps` directory. But there's a lot of people who build from source but that really don't need to build all the deps from source.

**Pull request merged**
