### PR TITLE
Add missing multi-argument map signature for numbers

### LINKED ISSUE #13113: `map` has inconsistent return type for numbers
Numbers behave in Julia like containers with a single element (see `base/numbers.jl`):
```Julia
julia> map(+, 1)
1
```

However:
```Julia
julia> map(+, 1, 2)
1-element Array{Any,1}:
 3
```
The return type is wrong.

I think this is due to a missing `map` signature in `numbers.jl`.

### PR DESCRIPTION
**Pull request by eschnett**
Fixes #13113.

### CODE REVIEW

**Comment by jakebolewski** [comment]
There is no way to do this without writing a generated function?

**Comment by eschnett** [comment]
@jakebolewski As you point out, there is a very easy way to do this without a generated function, namely
```Julia
map(f, x::Number, ys::Number...) = f(x, ys...)
```
I recently wrote many generated functions and got carried away.

**Comment by jakebolewski** [comment]
Resist the urge!!!

**Comment by jakebolewski** [comment]
Something like this might be faster:

```julia
map(f, x::Number) = f(x)
map(f, x::Number, y::Number) = f(x,y)
map(f, x::Number, y1::Number, y2::Number) = f(x,y1,y2)
map(f, x::Number, y1::Number, y2::Number, y3::Number) = f(x,y1,y2,y3)
map(f, x::Number, y1::Number, y2::Number, y3::Number,ys::Number....) = map(f, f(x,y1,y2,y3), ys...)
```

**Comment by eschnett** [comment]
If splatting is actually slower than having separate functions for each number of arguments, then a generated function is the most elegant approach. In your suggestion, there are five boilerplate implementations, and the fifth still suffers from low performance. (Your fifth line is slightly wrong; there should not be a call to `map`.)

What is not elegant is that applying the splat at compile time looks so verbose in a generated function -- one even has to write the call via `Expr`. There really should be a shorter syntax for this, as in
```Julia
@generated map(f, x, ys...) = @earlysplat f(x, ys...)
```

**Comment by JeffBezanson** [comment]
`Expr` is not actually required, because `$(x...)` performs splatting into an expression.

However your

```
map(f, x::Number, ys::Number...) = f(x, ys...)
```

is the best implementation.

**Comment by eschnett** [comment]
@JeffBezanson How do I write a splatted function call without `Expr` -- can you give a complete example? I'm not seeing it.
`:(f(x, ys...))` would splat at run-time;
`:(f(x, $(:ys...)))` would splat a symbol, which doesn't make sense;
`:(f(x, $(ys...)))` would splat the types of `ys`, not the values...

**Comment by yuyichao** [comment]
`f([:(ys[$i]) for i 1:length(ys)])` should work but I agree that the simplest one should be the most friendly to type inference.

**Comment by tkelman** [comment]
This PR was opened against release-0.4. Please reopen against master.

**Pull request closed without merging**
