### PR TITLE
Implement #24353 - Propagate cmd flags in interpolation

### LINKED ISSUE #24353: Interaction of setenv and cmd interpolation
I think interpolating a cmd that had its env set should either raise an error or propagate the environment. Current behavior:

```
julia> c = setenv(`x`, "A"=>true)
setenv(`x`,String["A=true"])

julia> `$c`
`x`
```

### PR DESCRIPTION
**Pull request by Keno**
Too late for 1.2 for which this was originally marked, but nevertheless,
it's a quick change, so might as well get it in now and have it be available
in 1.3.

Fixes #24353

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]
LGTM

**Comment by KristofferC** [comment]
So in ``  `foo $bar` ``, `foo` is considered an "interpolant"?

**Comment by StefanKarpinski** [comment]
I would consider the value of `bar` to be an interpolant, `foo` is a literal term in the command.

**Comment by Keno** [comment]
Yeah, the news entry wasn't worded correctly

**Comment by KristofferC** [comment]
The error message is worded in the same way.

**Comment by Keno** [comment]
Let's fix it :)

**Pull request merged**
