### PR TITLE
Type-stabilize broadcast over tuples and scalars

### PR DESCRIPTION
**Pull request by p-zubieta**

### CODE REVIEW

**Comment by pabloferz** [comment]
The only problem with this would be the codegen for large tuples, but that should be fixed on the `ntuple` end anyway.

**Review by Sacha0 — APPROVED** [review]
@pabloferz, this change looks great! Addressing the potential code blowup issue in `ntuple` sounds like a good plan if possible; perhaps something like the `Any16` trick for `map` over tuples would serve?

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by Sacha0** [comment]
Ref. https://github.com/JuliaLang/julia/pull/20817#issuecomment-284664667, which this change might address by using `ntuple(..., Val{N})` rather than `ntuple(..., n)`.

**Comment by pabloferz** [comment]
Seems like `@nanosoldier` cannot be triggered from a review summary.

@nanosoldier `runbenchmarks(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/21331#issuecomment-292756446) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/1ec7eb1f451ada67d0996fdfb049ec46c8e3b595/b8a9ed1_vs_965c938/report.md). cc @jrevels

**Comment by Sacha0** [comment]
The sole possible regression nanosoldier identified is almost certainly noise. Cheers!

**Pull request merged**
