### PR TITLE
inference: some NFC refactoring on `type_annotate!`

### PR DESCRIPTION
**Pull request by aviatesk**
@nanosoldier `runbenchmarks("array" || "sparse" || "inference" || "problem", vs=":master")`

### CODE REVIEW

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/45273):
```
NanosoldierError: failed to run benchmarks against primary commit: TaskFailedException

    nested task error: failed process: Process(setenv(`sudo -n -u nanosoldier-worker -- make -j3 --output-sync=target JULIA_PRECOMPILE=0`; dir="/nanosoldier/workdir/jl_WLSe6w/julia"), ProcessExited(2)) [2]
    
    Stacktrace:
     [1] pipeline_error
       @ ./process.jl:525 [inlined]
     [2] #run#648
       @ ./process.jl:440
     [3] run
       @ ./process.jl:438 [inlined]
     [4] build_julia!
       @ /nanosoldier/Nanosoldier.jl/src/build.jl:104
     [5] build_benchmarksjulia!
       @ /nanosoldier/Nanosoldier.jl/src/jobs/BenchmarkJob.jl:302
     [6] #19
       @ ./task.jl:411
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/98a756b_vs_c7e7a5d/report.md)

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("array" || "sparse" || "inference" || "problem", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45273#issuecomment-1123334081) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/ee5738c_vs_c7e7a5d/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runbenchmarks("sparse", vs=":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/45273#issuecomment-1123693399) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/112648e_vs_14232f4/report.md).

**Comment by aviatesk** [comment]
@nanosoldier `runtests(["LoopVectorization", "RecursiveFactorization"], vs = ":master")`

**Pull request merged**
