### PR TITLE
[WIP/RFC] More tests for Pkg

### PR DESCRIPTION
**Pull request by kshyatt**
Added some new tests to create a "fake" clone of `METADATA`, make a new package, `register`, `tag`, and `publish` it. `publish` must fail since `METADATA` isn't a GitHub repo, but I'm unsure how exactly to test the error throw (it's a `CompositeException`).

### CODE REVIEW

**Comment by kshyatt** [comment]
`register` was working on my local machine, but is failing on Travis. Failing with a `ERROR: LoadError: LoadError("/tmp/julia/share/julia/test/pkg.jl",170,ErrorException("SimpleFakePackage: no URL configured"))`

**Comment by kshyatt** [comment]
@tkelman any hints for what I've done wrong?

**Comment by tkelman** [comment]
It might be missing a remote or something? Really not sure.

**Comment by kshyatt** [comment]
But then why does it work locally? Hm.

**Comment by wildart** [comment]
`remote/origin` need to be set for the package repo.

**Comment by kshyatt** [comment]
So I should set some fake URL for this?

**Comment by wildart** [comment]
For this particular test fake URL will work. But, If you want to test `checkout` and `publish`, locally stored repository can be used to push into.

**Comment by kshyatt** [comment]
Great! Thanks for the help :). I'll update the PR.

**Comment by wildart** [comment]
@kshyatt I hate to mention, but these test become obsolete and would require rewrite when we switch on `libgit2`-supported package manager. I would recommended to postpone effort until we get the new package manager into `nightly` builds.

**Comment by kshyatt** [comment]
Do you have an ETA on the switch? If it's more than a month away and I can get these small tests done it might be worth it to me.

**Comment by tkelman** [comment]
As soon as we branch for 0.4 and open master back up for 0.5-dev breaking changes. Hopefully that won't be more than another couple weeks, give or take a bit.

**Comment by kshyatt** [comment]
In that case I'll leave this be.

**Pull request closed without merging**
