### PR TITLE
enable LLVM'S AMDGPU backend

### PR DESCRIPTION
**Pull request by vchuravy**
First step of mmany to also support AMD GPUs.
My current plan is for develop to mimick CUDAnative.jl with the actual compiler being developed outside of base.
Nevertheless it would be great if we could ship with the AMDGPU backend enabled for 1.0.

### CODE REVIEW

**Comment by vchuravy** [comment]
How do I trigger a rebuild of the LLVM cache?

**Comment by ViralBShah** [comment]
Cc @staticfloat

**Comment by staticfloat** [comment]
My guess is that you add a step to `.travis.yml` to delete `$TRAVIS_BUILD_DIR/deps/scratch/llvm-whatever` before you begin your build, but I don't actually know.  @ararslan do you know?

**Comment by ararslan** [comment]
Sorry, I have no idea. The Travis docs seem to say you can clear the cache in the UI: https://docs.travis-ci.com/user/caching/#Clearing-Caches. Though I imagine that will clear everything, not just LLVM.

**Comment by yuyichao** [comment]
You can also add time stamp file as the  dependency of the configure of llvm.

**Comment by JeffBezanson** [comment]
If this is done in time it can be in 1.0, but won't block it.

**Comment by vchuravy** [comment]
This pretty much all that is needed, given that it builds everywhere.

**Comment by maleadt** [comment]
What's the increase in `libLLVM`'s size like?

**Comment by vchuravy** [comment]
### Before enabling AMDGPU
```
du -skh usr/lib
437M

43M libLLVM-3.9.so
```

### After enabling AMDGPU
```
du -skh usr/lib
458M

47M libLLVM-3.9.so
```

**Comment by vchuravy** [comment]
If nobody has any other concerns I will merge this tomorrow.

**Pull request merged**
