### PR TITLE
Provide sparse matrix contructors that convert types efficiently

### LINKED ISSUE #38209: Sparse hvcat with adjoints is very slow (orders of magnitude)
I find that `hvcat` with sparse matrices is orders of magnitude slower than expected when adjoints of sparse matrices are involved. Here is an example:
```Julia
julia> using LinearAlgebra

julia> using SparseArrays

julia> n0 = 100000;

julia> n1 = 200000;

julia> N0 = spzeros(Bool, n0, n0);

julia> d = Int8.(sprand(Bool, n1, n0, 1/(n0*n1)));

julia> # δ = Float64.(sprand(Bool, n0, n1, 1/(n0*n1)));
       δ = Float64.(d)';

julia> E1 = Diagonal(ones(Bool, n1));

julia> @time [N0 δ; d -E1];
 82.412894 seconds (176 allocations: 28.276 MiB)
```

When I replace the definition of `δ` by the one that does not involve an adjoint, the calculation is much faster:
```Julia
julia> δ = Float64.(sprand(Bool, n0, n1, 1/(n0*n1)));

julia> @time [N0 δ; d -E1];
  0.068553 seconds (2.40 M allocations: 193.794 MiB)
```

I aborted one such very slow calculation, and found that `typed_hvcat` calls `setindex!`. If this is indeed the case, then this explains why this is very slow. Sparse matrices need to be constructed by calling `sparse` for efficiency.

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/JuliaLang/julia/issues/38209.

### CODE REVIEW

**Comment by oscardssmith** [comment]
It seems to me like we could go for a more generic approach to this fix, where we have 1 constructor for all matrices they just iterates over and fills nnz values.

**Comment by eschnett** [comment]
@oscardssmith How do you iterate over the non-zero values? These constructors take (bi-,tri-)diagonal matrices as input. Is there a generic way to iterate over their nonzero values?

**Comment by eschnett** [comment]
Test failures are unrealated.

**Comment by oscardssmith** [comment]
Never mind on this. I thought this was a generic interface we had, but we only have it for `SparseMatrix` and `SparseVector`. IMO we should add methods to `findnz` as it would be a really useful generic interface, but that's definitely out of scope for this PR.

**Pull request merged**
