### PR TITLE
Fix ccall return value boxing on ARM/AArch64

### PR DESCRIPTION
**Pull request by yuyichao**
We previously rely on the extra allocation from the GC to keep the stores inbounds.
This is broken by the allocation optimization since the stack allocation will only have
the requested bytes and not more.

### CODE REVIEW

**Comment by vtjnash** [comment]
Seems like this should be using our llvm_type_rewrite so it doesn't inhibit llvm optimizations.

**Comment by yuyichao** [comment]
We are only storing the value so as long as the size is smaller or the same we don't care what type it actually is so unconditionally going through `llvm_type_rewrite` is unnecessary and can generate extra code.

As long as we are doing this only when there's a size mismatch (i.e. what this PR is doing), it is exactly the same as `llvm_type_rewrite`. I didn't use it since most of the useful logic from the function is already here to check the size....

**Comment by yuyichao** [comment]
Actually I missed the trunc case in `llvm_type_rewrite` so I guess I can do that. It doesn't actually matter for the real code though since the type we have here always have an aggregate....

**Comment by vtjnash** [comment]
Ah, didn't realize this was just for structs. (In which case, I think `llvm_type_rewrite` should be doing the same as this code?) Anyways, this is probably fine, was just considering opportunities for consolidating code.

**Comment by yuyichao** [comment]
FWIW, I think this can share code better with `memcpy` (the only use of the value is storing anyway). I didn't do it since I don't want to have conflict with https://github.com/JuliaLang/julia/pull/23352 but maybe I should just rebase on it.....

**Pull request merged**
