### PR TITLE
Bump llvm version required for Power and backport bugfix.

### PR DESCRIPTION
**Pull request by vchuravy**
This backports a fix for #18555. The patch does not apply cleanly to LLVM 3.8 so I bumped the required version for Power support. I will try and nominate this patch as a backport to 3.9.1. 

cc: @ViralBShah

### CODE REVIEW

**Comment by tkelman** [comment]
add the checksums for llvm 3.9.0

**Comment by tkelman** [comment]
This will raise minimum cmake version to 3.4.3 on power right? I'm guessing cmake doesn't provide convenient binaries for power, did you build cmake from source or use a really new distro?

**Comment by vchuravy** [comment]
Yes I compiled CMake and CMake doen's provide binaries for power as far as I can tell.

The tests still fail:
```
    JULIA test/threads
     * threads              Warning: threaded loop executed in order
Test Failed
  Expression: x[] == m
   Evaluated: 0 == -5000
ERROR: LoadError: LoadError: There was an error during testing
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Fail) at ./test.jl:397
 in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:281
 in test_threaded_atomic_minmax(::Int16, ::Int16) at /home/valentin/julia/test/threads.jl:56
```

I put the llvm ir and `code_native` here https://gist.github.com/vchuravy/ba27d29870e49df5f640ff0b5aa635c3 if anybody is interested

**Comment by tkelman** [comment]
Or do any of the recent-cmake PPA's support power? I was planning on writing a `contrib/download_cmake.sh` script once we upgrade to LLVM 3.9 for the sake of Linux x86 and amd64 (it's easy enough to get from homebrew and cygwin elsewhere), but maybe with exotic architectures should we think about writing a makefile to automate building cmake ourselves?

**Comment by vchuravy** [comment]
I think we should probably deal with CMake like with any other dependency. If in doubt download it and build it ourselves :)

**Comment by tkelman** [comment]
Build-only dependencies have generally gotten a bit different treatment if they're easy enough to get binaries for good-enough versions, like gmake and gfortran.

**Comment by vchuravy** [comment]
added the checksums.

**Review by tkelman — APPROVED** [review]
lgtm. did 3.9 include D14260?

**Comment by tkelman** [comment]
@staticfloat @ViralBShah what version of cmake is on the power buildbot? It's running ubuntu 14.04 right, do we need to build a newer version to keep nightlies working there?

**Comment by vchuravy** [comment]
@tkelman I think it is in 3.9.0

```
[valentin@ibm-power2 llvm-svn]$ git log --grep=D14260
commit 1ca1fcaa5b4c75a65a202badfd5df8240a36ca0f
Author: Arch D. Robison <arch.robison@intel.com>
Date:   Mon Apr 25 22:22:39 2016 +0000

    Optimize store of "bitcast" from vector to aggregate.
    
[valentin@ibm-power2 llvm-svn]$ git branch --contains 1ca1fca
  master
* release_39
```

**Comment by staticfloat** [comment]
Yeah, we're going to need to build a new cmake on pretty much everything.

```
$ ansible julia_buildslaves -m shell -a 'export PATH=$PATH:/usr/local/bin && cmake --version 2>/dev/null | head -1' -i ./hosts

buildslave_osx10.10-x64 | SUCCESS | rc=0 >>
cmake version 3.6.1

buildslave_osx10.11-x64 | SUCCESS | rc=0 >>
cmake version 3.6.1

buildslave_osx10.9-x64 | SUCCESS | rc=0 >>
cmake version 3.6.1

buildslave_ubuntu14.04-x86 | SUCCESS | rc=0 >>
cmake version 2.8.12.2

buildslave_ubuntu14.04-x64 | SUCCESS | rc=0 >>
cmake version 2.8.12.2

buildslave_centos5.11-x86 | SUCCESS | rc=0 >>
cmake version 2.6-patch 4

buildslave_centos5.11-x64 | SUCCESS | rc=0 >>
cmake version 2.6-patch 4

buildslave_centos7.1-x64 | SUCCESS | rc=0 >>
cmake version 2.8.11

buildslave_centos6.7-x64 | SUCCESS | rc=0 >>
cmake version 2.8.12.2

buildslave_ubuntu14.04-armv7l | SUCCESS | rc=0 >>
cmake version 2.8.12.2

buildslave_centos7.2-ppc64le | SUCCESS | rc=0 >>
cmake version 2.8.11

buildslave_win6.2-x86 | SUCCESS | rc=0 >>
cmake version 3.3.2

buildslave_win6.2-x64 | SUCCESS | rc=0 >>
cmake version 3.3.2
```

I'll do this once the buildbot reconfig window opens, after 0.5.0 final is built.

**Comment by tkelman** [comment]
I'm the cmake maintainer on cygwin and uploaded 3.6.2 there recently. When you next upgrade cygwin packages please be very careful to **not** upgrade the mingw gcc cross-compilers to 5.4 though, we need to keep those held back to 4.9 until we have a solution for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77333

**Comment by ViralBShah** [comment]
Would this address all threading issues on power at least as far as the tests go?

**Comment by vchuravy** [comment]
The last two commits work around an upstream issue and all tests pass now.

**Comment by ViralBShah** [comment]
Should we backport this for 0.5?

**Comment by ViralBShah** [comment]
Once CI completes, let's merge this. Marking as a backport candidate.

**Comment by ViralBShah** [comment]
I didn't realize that the old `cmake` will break the buildbot. Should we revert, or just fix the cmake? I am happy to help fix the cmake immediately for the build environment.

**Comment by ViralBShah** [comment]
I just built cmake for myself. If we build it in the buildbot account and add it to the PATH, will that suffice? If somone can DM me the password to the account, I will do it. Seems like it should be easy enough to fix up.

**Comment by staticfloat** [comment]
@ViralBShah which buildbot are you referring to?  We were planning on upgrading `cmake` after all our 0.5.0 and 0.4.7 binaries are built and verified working.

**Comment by ViralBShah** [comment]
The power one.

**Comment by staticfloat** [comment]
Ah, we specifically upgraded `cmake` on the ppc64le buildbot, so no worries.  :)

**Comment by ViralBShah** [comment]
Ok - great! Thanks.

**Comment by vchuravy** [comment]
@tkelman to backport this I would open a PR against `release-0.5`?

**Comment by tkelman** [comment]
See the steps at #17418. Does that need to be done now or can it wait until we run pkgeval for 0.5.1?

**Comment by vchuravy** [comment]
It can wait till 0.5.1 in my opinion. Ping me when you want to backport it
and I can prepare it.

**Pull request merged**
