### PR TITLE
bump libuv commit

### PR DESCRIPTION
**Pull request by vtjnash**
fixes UV_HANDLE_EMULATE_IOCP handling for Windows pipes, closing #11727

### CODE REVIEW

**Comment by tkelman** [comment]
> closing #11727

Needs test.

**Review by tkelman — CHANGES_REQUESTED** [review]
update checksums

**Comment by vtjnash** [comment]
Will test when it is submitted upstream.

**Comment by tkelman** [comment]
please add a julia level integration test to verify the consequence we encountered

**Pull request merged**
