### PR TITLE
Fix LLVM 3.7 reflection test

### PR DESCRIPTION
**Pull request by Keno**
This seemed to be the easiest way to fix that, but I'm not sure if it's correct. @vtjnash @eschnett ?

### CODE REVIEW

**Comment by tkelman** [comment]
which issue? what's the failure?

**Comment by Keno** [comment]
https://github.com/JuliaLang/julia/commit/030ba865c3551fbc72a03dce83defc48c5047bf4#commitcomment-14805330

**Comment by vtjnash** [comment]
looks fine to me. it doesn't look like we use the value from `setVariableValue` (or really the object itself for that matter)?

**Comment by eschnett** [comment]
I have not yet reproduced the failure. However, things continue to work for me with the fix, so it looks good.

**Pull request merged**
