### PR TITLE
Improvements to contrib/julia-mode.el (Emacs mode)

### PR DESCRIPTION
**Pull request by Clemens-H**
Add functions to execute Julia code in Terminal.app on Mac OS X.

Improve font lock.

Function julia-documentation based on ESS’s Julia mode plus fix.

Set comment-add to 1.

Add key bindings.

Add logic for auto-mode-alist.

### CODE REVIEW

**Comment by tkelman** [comment]
@Wilfred should this be resurrected and rebased, or closed?

**Comment by Wilfred** [comment]
> Font-locking and syntax definitions were addressed by @Wilfred, but I would have to check line by line with the latest version.
> 
> The main outstanding part is executing code in a terminal.

This PR now only offers OS X Terminal specific code. I think it belongs in a separate package rather than julia-mode itself. I'd close it.

**Comment by tkelman** [comment]
OK thanks. Separate emacs package, you mean? So someone can publish this (or equivalent) code independently and it'll be just as easy to use through some emacs package registry?

**Comment by Wilfred** [comment]
Yep. Just create a `julia-os-x.el` file in a new github repo and add it to [MELPA](https://github.com/milkypostman/melpa). It's then easy for anyone to install.

**Comment by Clemens-H** [comment]
I am the author of the commit/patch and the OS X specific code.  I believe I should be the one who distributes it.

**Comment by pao** [comment]
Sounds great--if you do this, please make a PR to mention the OS X-specific package at the end of Julia's README, in the "Editor and Terminal Setup" section.

**Comment by Clemens-H** [comment]
Ok, I'll look into this in the next couple of days.

**Pull request closed without merging**
