### PR TITLE
lowering: Revert undefined global outlining

### PR DESCRIPTION
**Pull request by Keno**
This partially reverts #51970, once again allowing throwing GlobalRefs in value position for `CodeInfo`, (but not `IRCode`). The primary motivation for this reversal is that after binding partition the throwiness of a global is world-age dependent and we do not want to have lowering be world-age dependent, because that would require us to rewrite the lowered code upon invalidation (#56649).

With respect to the original motivation for this change (being able to use the statement flag in inference), we retain the property that the statement flags apply only to the optimizer version of the statement (i.e. with the GlobalRefs moved out). The only place in inference where we were not doing this, we can rely on `exct` instead. This does assume that `exct` is precise, but we've done a lot of work on that in the past year, so hopefully we can rely on that now.

The revert is partial, because we go in the opposite direction in a few places: For `GotoIfNot` cond and `EnterNode` scope operands, we just forbid any `GlobalRef` entirely. Constants are rare in these, so no need to burden inference with the possibility of handling these. We do however, keep (and add appropriate handling code) for GlobalRef arguments to `ReturnNode` to make sure that trivial code remains one statement.

### CODE REVIEW

**Comment by vtjnash** [comment]
What is the reason not to just ban them entirely except if the optimizer proved them no throw and added an optimizer edge?

**Comment by Keno** [comment]
If GlobalRef were entirely disallowed in value position, we would blow up the size of lowered code by a significant factor. At 2-3x.

**Comment by vtjnash** [comment]
That seems to imply that most statements contain 2-3 globals (and probably more), which seems unlikely. I tried deleting this lowering complication entirely, and the system image changed by an insignificant amount (1MB or 0.6%), which seems easily recoverable by making the compression design a lot better once only SSAValue is allowed as immediate values.
```
vtjnash@deepsea4:~/julia$ git diff
diff --git a/src/ast.c b/src/ast.c
index 474c0661f52..5ae5ba0af79 100644
--- a/src/ast.c
+++ b/src/ast.c
@@ -288,7 +288,7 @@ static jl_value_t *scm_to_julia_(fl_context_t *fl_ctx, value_t e, jl_module_t *m
 
 static const builtinspec_t julia_flisp_ast_ext[] = {
     { "defined-julia-global", fl_defined_julia_global }, // TODO: can we kill this safepoint
-    { "nothrow-julia-global", fl_nothrow_julia_global },
+    //{ "nothrow-julia-global", fl_nothrow_julia_global },
     { "current-julia-module-counter", fl_module_unique_name },
     { "julia-scalar?", fl_julia_scalar },
     { NULL, NULL }
```

```
$ size -A usr/lib/julia/sys.so | grep ldata
.ldata                158870928 => 159737216
$ du -sh usr/share/julia/compiled/v1.12/
254M => 271M
```

**Comment by Keno** [comment]
Alright, if we're happy to bite the size increase, I can put up that PR instead.

**Comment by Keno** [comment]
Closing in favor of #56746

**Pull request closed without merging**
