### PR TITLE
remove trim option to fkeep! and related functions

### LINKED ISSUE #32967: `droptol!` for SparseVector with `trim=false` does not work as expected
The method `droptol!` for SparseVector with `trim=false` only modifies the first found entry within the specified tolerance:
```julia
julia> using SparseArrays

julia> v = sparsevec([1, 3, 7, 8, 11], [1., 0.001, 0.001, 3., 0.001])
11-element SparseVector{Float64,Int64} with 5 stored entries:
  [1 ]  =  1.0
  [3 ]  =  0.001
  [7 ]  =  0.001
  [8 ]  =  3.0
  [11]  =  0.001

julia> droptol!(v, 0.1, trim=false)
11-element SparseVector{Float64,Int64} with 5 stored entries:
  [1 ]  =  1.0
  [8 ]  =  3.0
  [7 ]  =  0.001
  [8 ]  =  3.0
  [11]  =  0.001
```
Also note that value at index `8` gets listed twice in the output.

Here is the output that I would have expected:
```julia
11-element SparseVector{Float64,Int64} with 2 stored entries:
  [1 ]  =  1.0
  [8 ]  =  3.0
```

It seems to work correctly for sparse matrices:
```julia
julia> v = sparsevec([1, 3, 7, 8, 11], [1., 0.001, 0.001, 3., 0.001])
11-element SparseVector{Float64,Int64} with 5 stored entries:
  [1 ]  =  1.0
  [3 ]  =  0.001
  [7 ]  =  0.001
  [8 ]  =  3.0
  [11]  =  0.001

julia> A = SparseMatrixCSC(v)
11×1 SparseMatrixCSC{Float64,Int64} with 5 stored entries:
  [1 , 1]  =  1.0
  [3 , 1]  =  0.001
  [7 , 1]  =  0.001
  [8 , 1]  =  3.0
  [11, 1]  =  0.001

julia> droptol!(A, 0.1, trim=false)
11×1 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 1]  =  1.0
  [8, 1]  =  3.0
```

I am on the current master branch, but the same problem occurs on Julia 1.1.1.
```julia
julia> versioninfo()
Julia Version 1.4.0-DEV.12
Commit e106a42123 (2019-08-19 21:54 UTC)
```

### PR DESCRIPTION
**Pull request by KristofferC**
After https://github.com/JuliaLang/julia/pull/31724, the whole `trim` thing doesn't make sense since it is producing SparseArrays that are invalid according to our consistency checks.
Therefore, just remove the `trim` option.

AFAIU, we are also trying to move away from having an uninitialized "tail" in the different internal vectors as well.

Fixes https://github.com/JuliaLang/julia/issues/32967

### CODE REVIEW

**Comment by KristofferC** [comment]
Triage because it is a bit unclear what to do here.

This is clearly breaking but the pr #31724 documents that the matrices generated by `trim=false` are invalid so I guess we should fix that... So should we put in a deprecation warning then..? But we don't want deprecations in 1.x etc.

**Comment by KristofferC** [comment]
Triage: Check how much this is used in practice, and decide something based on that.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL; vs=":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/32972#issuecomment-587455244) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/1cf3925c5912ec201b27ffd9bd70f7f1d67b2a1b/pkgeval/by_hash/fac0eb6_vs_e36fe95/report.md). cc @maleadt

**Comment by KristofferC** [comment]
PkgEval looks clean, added a NEWS entry, will merge in a while unless I hear something.

**Pull request merged**
