### PR TITLE
fix #14564, segfault in object_id of svec with NULL elements

### LINKED ISSUE #14564: Segfault on `object_id(Tuple.name.cache)`
https://gist.github.com/jamii/5f61f95cdff463977f57 segfaults on both Julia 0.4.2 and master as of 2016-01-05.

Under LLDB:
```
Process 17708 stopped
* thread #1: tid = 17708, 0x00007ffff6e85283 libjulia.so`jl_object_id + 3, name = 'julia', stop reason = invalid address (fault address: 0xfffffffffffffff8)
    frame #0: 0x00007ffff6e85283 libjulia.so`jl_object_id + 3
-> 0x7ffff6e85283 <jl_object_id+3>: movq   -0x8(%rdi), %rdi
   0x7ffff6e85287 <jl_object_id+7>: andq   $-0x10, %rdi
   0x7ffff6e8528b <jl_object_id+11>: jmp    0x7ffff6e85630            ; ???
   0x7ffff6e85290 <???>: pushq  %rbp
(lldb) bt
* thread #1: tid = 17708, 0x00007ffff6e85283 libjulia.so`jl_object_id + 3, name = 'julia', stop reason = invalid address (fault address: 0xfffffffffffffff8)
  * frame #0: 0x00007ffff6e85283 libjulia.so`jl_object_id + 3
    frame #1: 0x00007ffff6e858c6 libjulia.so`??? + 662
    frame #2: 0x00007ffff6e85a2e libjulia.so`jl_eqtable_get + 78
    frame #3: 0x00007ffff7e6f2e5
    frame #4: 0x00007ffff7e6ef37
    frame #5: 0x00007ffff7e6ee93
    frame #6: 0x00007ffff6e7a7e5 libjulia.so`jl_apply_generic + 469
    frame #7: 0x00007ffff6ed2833 libjulia.so`??? + 211
    frame #8: 0x00007ffff6ed1bbb libjulia.so`??? + 3115
    frame #9: 0x00007ffff6ee79bb libjulia.so`??? + 443
    frame #10: 0x00007ffff6ee8125 libjulia.so`??? + 613
    frame #11: 0x00007ffff6ee7d65 libjulia.so`??? + 1381
    frame #12: 0x00007ffff6ee86dc libjulia.so`??? + 364
    frame #13: 0x00007ffff6ee88e4 libjulia.so`jl_load + 116
    frame #14: 0x00007ffff38387e0 sys.so`julia_include_696 + 64 at boot.jl:261
    frame #15: 0x00007ffff6e7a71b libjulia.so`jl_apply_generic + 267
    frame #16: 0x00007ffff3a18b89 sys.so`julia_include_from_node1_19478 + 393 at loading.jl:304
    frame #17: 0x00007ffff6e7a71b libjulia.so`jl_apply_generic + 267
    frame #18: 0x00007ffff3a0c8e5 sys.so`julia_process_options_19090 + 3637 at client.jl:280
    frame #19: 0x00007ffff3a0ad70 sys.so`julia__start_19089 + 800 at client.jl:378
    frame #20: 0x00007ffff3a0baa9 sys.so`jlcall__start_19089 + 9
    frame #21: 0x00007ffff6e7a71b libjulia.so`jl_apply_generic + 267
    frame #22: 0x0000000000401b87 julia`true_main [inlined] jl_apply(nargs=<unavailable>, args=<unavailable>, f=<unavailable>) + 247 at julia.h:1325
    frame #23: 0x0000000000401b7e julia`true_main(argc=1, argv=0x00007fffffffe290) + 238 at repl.c:491
    frame #24: 0x000000000040174f julia`main(argc=1, argv=0x00007fffffffe290) + 79 at repl.c:595
    frame #25: 0x00007ffff67dba40 libc.so.6`__libc_start_main + 240
    frame #26: 0x0000000000401799 julia`_start + 41
```

### PR DESCRIPTION
**Pull request by JeffBezanson**

### CODE REVIEW

**Comment by Keno** [comment]
`jl_egal` is pretty hot, I think it's worth running the benchmarks:

`runbenchmarks(ALL, vs = "JuliaLang/julia:master")`

**Comment by JeffBezanson** [comment]
How fast do you want the wrong answer? ;)

**Comment by Keno** [comment]
I was watching a talk by Sussman yesterday where he said "Correctness doesn't matter" ;)

**Comment by JeffBezanson** [comment]
I do see a bit of slowdown in the subarray test, from ~300 to ~380 seconds locally. Hard to believe a couple pointer comparisons could have that effect. We need to deal with #14556.

**Comment by JeffBezanson** [comment]
Updated with a more minimal fix.

**Pull request merged**
