### PR TITLE
Warn that @inbounds is dangerous

### PR DESCRIPTION
**Pull request by LilithHafner**
Seeing that the example usage in the documentation used to expose unsafe memory access (and I believe still does in the stable version) makes me think this warning is necessary.

### CODE REVIEW

**Review by timholy — COMMENTED** [review]
This is also mentioned in https://docs.julialang.org/en/v1/devdocs/offset-arrays/#Things-to-watch-out-for, but it doesn't hurt here.

**Review by timholy — COMMENTED** [review]
LGTM, possibly pending a link to OffsetArrays

**Comment by LilithHafner** [comment]
@timholy thanks for your thoughtful and kind feedback! LGTM too now.

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
Ah you will need to place a url for the reference to OffsetArray. See the docs CI:

```
��� Warning: no doc found for reference '[`OffsetArrays`](@ref)' in src/devdocs/boundscheck.md.
��� @ Documenter.CrossReferences /buildworker/worker/doctest_linux64/build/doc/deps/packages/Documenter/f5jts/src/CrossReferences.jl:160
```

**Comment by LilithHafner** [comment]
Coolbeans, thanks! I'm waiting for my local `make docs` to finish and then I'll do a normal push.

**Comment by vchuravy** [comment]
@LilithHafner thank you for your contribution!

**Comment by LilithHafner** [comment]
@vchuravy thank you for your advice!

**Pull request merged**
