### PR TITLE
Even MORE tests for svd and symmetric

### PR DESCRIPTION
**Pull request by kshyatt**
Generalized svd didn't have a few of its methods tested. `expm` wasn't tested for `Symmetric`s and `logm` wasn't tested for posdef `Hermitian`s.

### CODE REVIEW

**Comment by kshyatt** [comment]
Getting killed on OSX! Error bounds.

**Comment by andreasnoack** [comment]
Easy fix: use `@test arg1 ≈ arg2` instead of `@test_approx_eq arg1 arg2`. I thought they were equivalent, but it appears that `≈` has a different tollerance that makes this test pass.

**Comment by kshyatt** [comment]
Thanks for the tip, @andreasnoack! Ok to merge?

**Comment by andreasnoack** [comment]
I think we'd like to transition to the `≈` version now so it would be great if you could change the other lines to that version as well. Besides that I think it is ready for merge.

**Comment by kshyatt** [comment]
Ok, will do and then press the pretty button!

**Pull request merged**
