### PR TITLE
[LLVM] Update to LLVM 12

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by staticfloat** [comment]
There shouldn't be an `Artifacts.toml`. There can be an `StdlibArtifacts.toml`, but that should not be checked in; it gets downloaded from GitHub at build time.

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-839319590) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/d986e49_vs_d6c092d/report.md). cc @maleadt

**Comment by chriselrod** [comment]
All the failures I looked at originated from VectorizationBase.jl or SIMD.jl not removing `experimental` with LLVM 12:
`llvm.experimental.vector.reduce.v2.fadd.v4f64`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-839319468) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/2285502_vs_d6c092d/report.md). cc @christopher-dG

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
> All the failures I looked at originated from VectorizationBase.jl or SIMD.jl not removing `experimental` and `v2` with LLVM 12:
> `llvm.experimental.vector.reduce.v2.fadd.v4f64`
> EDIT:
> VectorizationBase.jl: [JuliaSIMD/VectorizationBase.jl@441988f](https://github.com/JuliaSIMD/VectorizationBase.jl/commit/441988f5035283fa216ac58157cc97692baf3f8c)
> SIMD.jl: [eschnett/SIMD.jl#86](https://github.com/eschnett/SIMD.jl/pull/86)

Thanks @chriselrod! Once the SIMD.jl one has been merged and tagged we can rerun PkgEval.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-839880250) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/cd660ad_vs_d6c092d/report.md). cc @christopher-dG

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vtjnash** [comment]
Wow, that's truly horrendous. How did you manage to make even basic things like `+` and `sin` that much slower?

**Comment by vchuravy** [comment]
> How did you manage

Hey now! How did *they* manage to make everything slower. 

I fixed the 30000x regression, that seemed to be a missing pass and we will see what impact that has elsewhere.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-840144905) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c0b95ac_vs_d6c092d/report.md). cc @christopher-dG

**Comment by vchuravy** [comment]
Ok, this is looking much better. Still some regression but they are all in the normal range. I will look at a few of the larger ones.

@staticfloat this is now blocked on getting python3 on the build it's.

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by vchuravy** [comment]
@DilumAluthge any ideas why buildkite didn't get triggered automatically? There was a webhook triggered.

Manually: https://buildkite.com/julialang/julia/builds/200

**Comment by DilumAluthge** [comment]
Hmmm. I checked the settings and everything looked correct. Can you try pushing a new commit to this branch?

**Comment by DilumAluthge** [comment]
Or maybe rebase on master?

**Comment by DilumAluthge** [comment]
@vchuravy I pushed a new commit to this branch, and it looks like Buildkite got triggered?

I think I figured out the problem. We had enabled the "skip builds for existing commits and branches" option. So if Buildkite thinks it has already run a job for a commit or branch, it won't trigger a new one. I have unchecked that option, which I think was the source of the problem.

**Comment by DilumAluthge** [comment]
Yeah I think the "triggered by webhook" text means that it is working correctly now.

462BCC26-097F-420C-9255-DFBF5705A9F2

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-844639226) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/9593fb5_vs_d93a1c8/report.md). cc @maleadt

**Comment by maleadt** [comment]
Lots of tests became inactive during package installation, presumably when downloading artifacts? It seems unrelated to the upgrade, because lots of tests became inactive on the reference build too. Let's retry those:

@nanosoldier `runtests(["AIBECS", "AIControl", "AccurateArithmetic", "AcuteML", "AdvancedHMC", "AlgebraicPetri", "ApproxFunBase", "BLASBenchmarksCPU", "BPFnative", "BasicBSpline", "Bio3DView", "BioEnergeticFoodWebs", "Bootstrap", "BranchAndBound", "BridgeDiffEq", "CBinding", "CBindingGen", "CacheVariables", "CellMLToolkit", "ChooseOptimizer", "ClusterValidityIndices", "Concorde", "ConstrainedRootSolvers", "Controlz", "Curve25519", "DASSL", "Dianli", "DiffEqJump", "DifferentialEquations", "DirectConvolution", "EMIRT", "EmpiricalModeDecomposition", "EvoDynamics", "Ferrite", "FinEtools", "FinEtoolsDeforLinear", "FinEtoolsVoxelMesher", "FiniteDiff", "FiniteHorizonValueIteration", "FlashWeave", "Folds", "GPUCompiler", "GXBeam", "Gen", "GeneticScreens", "Glowe", "GradientRobustMultiPhysics", "GuessworkQuantumSideInfo", "HCIToolbox", "Hecke", "HomotopyContinuation", "HydroRefStations", "IMFData", "ImageAxes", "ImageContainers", "ImageInpainting", "InteractiveDynamics", "InverseIsing", "JuliaGrid", "Kahuna", "Khepri", "LLVM", "LatticeRules", "LiveServer", "LocalApproximationValueIteration", "LoopVectorization", "LowLevelParticleFilters", "MPSGE", "MPSKit", "MakieTeX", "MarketData", "Materials", "Meshing", "Mixtape", "ModelParameters", "MortalityTables", "MyAwesomePackage", "NMRTools", "NRRD", "NaNStatistics", "NamedColors", "NeXLUncertainties", "NeidArchive", "NestedSamplers", "NumericalAlgorithms", "ODEInterfaceDiffEq", "OceanGrids", "OceanographyCruises", "Octavian", "OpenQuantumBase", "P4est", "PLCTag", "PencilArrays", "Petri", "PetroleumModels", "PlotPlants", "Pluto", "PolygonInbounds", "PowerSimulations", "PowerSystemCaseBuilder", "ProfileVega", "ProximalAlgorithms", "Pseudoseq", "Pseudospectra", "QuartetNetworkGoodnessFit", "RSDeltaSigmaPort", "Reactive", "RecursiveFactorization", "RegularizedLeastSquares", "Relief", "Ripserer", "RungeKutta", "SASLib", "SIMD", "SegmentIntersections", "SimSpin", "SimulatedNeuralMoments", "SimulationLogs", "SineFit", "SlidingDistancesBase", "SparseRegression", "SpatialJackknife", "SphericalFourierBesselDecompositions", "SpineBasedRecordLinkage", "SqState", "StanMamba", "StateSpaceReconstruction", "Stipple", "SymSpellChecker", "TSVD", "TensorCast", "Tensors", "Tracking", "Tullio", "VectorizationBase", "VectorizedRNG", "VideoIO", "WorldOceanAtlasTools", "ZygoteRules", "jInv", "Alexya", "Alpine", "AnimalBreedingTools", "BATBase", "BLIS", "BSplineKit", "Basins", "Batsrus", "BenchmarkProfiles", "BioMakie", "BioServices", "CSFML", "CalibrationTests", "CausalInference", "Circuitscape", "ClimateBase", "ClimateTasks", "CombinedParsers", "CorrectMatch", "CumulantsUpdates", "Deconvolution", "DeformableBodies", "DensityRatioEstimation", "DiffEqFinancial", "EnhancedGJK", "ExactPredicates", "FactoredValueMCTS", "FastMarching", "FastTransforms", "FileTrees", "Firefly", "GLPK", "GPARs", "GR", "GadJet", "GenomeGraphs", "GeoDataFrames", "GlobalSensitivity", "GridapPardiso", "GtkObservables", "IntervalMatrices", "JSOSolvers", "JetPackDSP", "JetPackTransforms", "KLDivergences", "KrigingEstimators", "LRMoE", "LaplacianOpt", "LightOSM", "LineSearches", "LsqFit", "MLJClusteringInterface", "MLJScientificTypes", "Mellan", "NLsolve", "NaiveBayes", "NeXLCore", "NeuroFormats", "NonlinearSolve", "NonsmoothOptim", "OutlierDetectionData", "PDELib", "PDSampler", "POMDPXFiles", "ParameterizedFunctions", "PersistenceDiagrams", "Pitchjx", "Plots", "PointBasedValueIteration", "PointProcessInference", "PolaronPathIntegrals", "PolyhedralRelaxations", "PowerSimulationsDynamics", "PredictMDFull", "ProximalOperators", "QML", "QXContexts", "ROCKernels", "Reel", "Robotlib", "SCIP", "SPICE", "ScHoLP", "ShapML", "Simulate", "SolidStateDetectors", "Spectra", "StableDQMC", "StatsDiscretizations", "TableWidgets", "TensorKitManifolds", "TheNumberLine", "TimeSeries", "TreesHeaps", "UAParser", "Vega", "Wflow"], vs = ":master")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-844857512) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8114f7a_vs_79ee2b4/report.md). cc @maleadt

**Comment by maleadt** [comment]
LLVM.jl just needs a tag: https://github.com/maleadt/LLVM.jl/pull/229.

**Comment by chriselrod** [comment]
Fixed in VectorizationBase: https://github.com/JuliaRegistries/General/pull/37133

**Comment by vchuravy** [comment]
@nanosoldier `runtests(["OpenQuantumBase", "LiveServer", "CBinding", "LLVM", "VectorizationBase"])`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
If these come back clean I am inclined to merge this tomorrow.

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-845546587) has completed - possible issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8ae50e0/report.md). cc @maleadt

**Comment by chriselrod** [comment]
> Active lane mask fixed in VectorizationBase and tagged: [JuliaRegistries/General#37133](https://github.com/JuliaRegistries/General/pull/37133)

Ugh, now actually fixed.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-845546747) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/c13f74b_vs_9117b4d/report.md). cc @christopher-dG

**Comment by KristofferC** [comment]
The `["union", "array", ("perf_simplecopy", "Bool", 1)]` and company might be relevant (4x regression).

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@8ae50e0cea280e5cc7310a648c280e90c592ed04")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846050633):
```
NanosoldierError: failed to run benchmarks against primary commit: TaskFailedException:
failed process: Process(setenv(`make -j7 --output-sync=target JULIA_PRECOMPILE=0`; dir="/run/media/system/data/nanosoldier/workdir/jl_mEYQNG"), ProcessExited(2)) [2]

pipeline_error at ./process.jl:525 [inlined]
#run#596 at ./process.jl:440
run at ./process.jl:438 [inlined]
build_julia! at /run/media/system/data/nanosoldier/Nanosoldier.jl/src/build.jl:93
build_benchmarksjulia! at /run/media/system/data/nanosoldier/Nanosoldier.jl/src/jobs/BenchmarkJob.jl:299
#17 at ./task.jl:356
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/db531ad_vs_ef67353/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846052068):
```
NanosoldierError: failed to run benchmarks against primary commit: TaskFailedException:
failed process: Process(setenv(`make -j7 --output-sync=target JULIA_PRECOMPILE=0`; dir="/run/media/system/data/nanosoldier/workdir/jl_O9zJ7H"), ProcessExited(2)) [2]

pipeline_error at ./process.jl:525 [inlined]
#run#596 at ./process.jl:440
run at ./process.jl:438 [inlined]
build_julia! at /run/media/system/data/nanosoldier/Nanosoldier.jl/src/build.jl:93
build_benchmarksjulia! at /run/media/system/data/nanosoldier/Nanosoldier.jl/src/jobs/BenchmarkJob.jl:299
#17 at ./task.jl:356
```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/db531ad_vs_8ae50e0/report.md)
cc @christopher-dG

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":master")`

**Comment by vchuravy** [comment]
@nanosoldier `runbenchmarks(ALL, vs="@8ae50e0cea280e5cc7310a648c280e90c592ed04")`

**Comment by vchuravy** [comment]
@nanosoldier `runtests(ALL, vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846098319) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4198cea_vs_ef67353/report.md). cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846143605) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8539c1a_vs_d730fd3/report.md). cc @maleadt

**Comment by DilumAluthge** [comment]
> [Your package evaluation job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846143605) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/8539c1a_vs_d730fd3/report.md). cc @maleadt

@chriselrod The Tullio failures here seem to be coming from LoopVectorization and/or VectorizationBase? E.g.:

```
new arrays: Error During Test at /home/pkgeval/.julia/packages/Tullio/IHd6P/test/parsing.jl:4
  Got exception outside of a @test
  llvmcall only supports intrinsic calls
  Stacktrace:
    [1] macro expansion
      @ ~/.julia/packages/VectorizationBase/xil1r/src/llvm_intrin/intrin_funcs.jl:292 [inlined]
    [2] vsum
      @ ~/.julia/packages/VectorizationBase/xil1r/src/llvm_intrin/intrin_funcs.jl:292 [inlined]
    [3] vsum
      @ ~/.julia/packages/VectorizationBase/xil1r/src/llvm_intrin/intrin_funcs.jl:269 [inlined]
    [4] reduced_add
      @ ~/.julia/packages/VectorizationBase/xil1r/src/llvm_intrin/intrin_funcs.jl:319 [inlined]
```

**Comment by chriselrod** [comment]
> @chriselrod The Tullio failures here seem to be coming from LoopVectorization and/or VectorizationBase? E.g.:

So, Tullio tests:
```julia
 [3d5dd08c] VectorizationBase v0.15.7
```
RegularizedLeastSquares tests:
```julia
  [3d5dd08c] + VectorizationBase v0.19.39
```
They should be on VectorizationBase 0.20.10.

ApproximateManifoldProducts had
```julia
  [3d5dd08c] VectorizationBase v0.20.10

Basic 3D multiply and cross dimension covariance test...: Error During Test at /home/pkgeval/.julia/packages/ApproxManifoldProducts/BhS8C/test/testBasicManiProduct.jl:26
  Got exception outside of a @test
  DomainError with -7.426431436168918e300:
  log will only return a complex result if called with a complex argument. Try log(Complex(x)).
  Stacktrace:
    [1] throw_complex_domainerror(f::Symbol, x::Float64)
      @ Base.Math ./math.jl:33
```
So maybe that's related.

BPFNative had:
```julia
  [929cbde3] + LLVM v3.7.1

empty: Error During Test at /home/pkgeval/.julia/packages/BPFnative/LpXdL/test/runtests.jl:27
  Got exception outside of a @test
  MethodError: no method matching LLVM.ConstantArray(::LLVM.IntegerType, ::Vector{UInt8})
  Closest candidates are:
    LLVM.ConstantArray(::LLVM.LLVMType) at /home/pkgeval/.julia/packages/LLVM/1GCWB/src/core/value/constant.jl:136
    LLVM.ConstantArray(::LLVM.LLVMType, !Matched::AbstractArray{T, N}) where {T<:LLVM.Constant, N} at /home/pkgeval/.julia/packages/LLVM/1GCWB/src/core/value/constant.jl:136
  Stacktrace:
    [1] finish_module!(job::GPUCompiler.CompilerJob{GPUCompiler.BPFCompilerTarget, BPFnative.BPFCompilerParams}, mod::LLVM.Module)
      @ GPUCompiler ~/.julia/packages/GPUCompiler/AdCnd/src/bpf.jl:54
    [2] emit_asm(job::GPUCompiler.CompilerJob, ir::LLVM.Module, kernel::LLVM.Function; strip::Bool, validate::Bool, format::LLVM.API.LLVMCodeGenFileType)
      @ GPUCompiler ~/.julia/packages/GPUCompiler/AdCnd/src/driver.jl:283
    [3] codegen(output::Symbol, job::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool)
      @ GPUCompiler ~/.julia/packages/GPUCompiler/AdCnd/src/driver.jl:76
    [4] compile(target::Symbol, job::GPUCompiler.CompilerJob; libraries::Bool, deferred_codegen::Bool, optimize::Bool, strip::Bool, validate::Bool, only_entry::Bool)
      @ GPUCompiler ~/.julia/packages/GPUCompiler/AdCnd/src/driver.jl:39
    [5] bpffunction_compile(source::GPUCompiler.FunctionSpec{var"#kernel#1", Tuple{Int64}}; format::Symbol, license::String, prog_section::String, btf::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ BPFnative ~/.julia/packages/BPFnative/LpXdL/src/compiler.jl:47
    [6] check_cache(cache::Dict{UInt64, Any}, compiler::Any, linker::Any, spec::GPUCompiler.FunctionSpec{var"#kernel#1", Tuple{Int64}}, prekey::UInt64; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:format, :license, :btf), Tuple{Symbol, String, Bool}}})
```

**Comment by chriselrod** [comment]
@eschnett Can we get a new release for SIMD.jl? It [crashes on the latest release](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/8539c1a_vs_d730fd3/SIMD.1.7.0-DEV-55d0e0eeae.log):
```julia
JIT session error: Symbols not found: [ llvm.experimental.vector.reduce.v2.fadd.v4f64 ]
Failure value returned from cantFail wrapped call
Failed to materialize symbols: { (JuliaOJIT, { jfptr_sum_353, julia_sum_352 }) }
UNREACHABLE executed at /workspace/srcdir/usr/include/llvm/Support/Error.h:749!
```
but should be fine on master.

**Comment by vchuravy** [comment]
To look at:

ID | time ratio | memory ratio
-- | -- | --
["array", "accumulate", ("accumulate!", "Int")] | 2.53 (5%) | 1.00 (1%)
["array", "bool", "boolarray_true_load!"] | 2.73 (5%) | 1.00 (1%)
["array", "comprehension", ("collect", "Vector{Float64}")] | 3.36 (5%) | 1.00 (1%)
["array", "comprehension", ("comprehension_collect", "Vector{Float64}")] | 3.04 (5%) | 1.00 (1%)
["linalg", "arithmetic", ("cumsum!", "Int32", 1024)] | 2.00 (45%) | 1.00 (1%)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/40774#issuecomment-846098765) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/4c323cb_vs_8ae50e0/report.md). cc @christopher-dG

**Comment by eschnett** [comment]
Released SIMD 3.3.1.

**Comment by vchuravy** [comment]
I will look at the remaining performance regressions over the next week.

**Pull request merged**
