### PR TITLE
Deprecate ntuple(::Integer, ::Function)

### PR DESCRIPTION
**Pull request by timholy**
I think we should do this now, because someday we may want to duck-type the function argument (FastAnonymous or otherwise). But we need one release cycle of deprecation first.

More controversially, I also added an inferrable variant of `ntuple`. It's based on `Val` and `@generated` functions, the latter of which is the likely source of controversy. I separated this into a separate commit so that it can be easily dropped, if necessary.

### CODE REVIEW

**Comment by timholy** [comment]
Since little controversy seems to have been stirred up, and approval for the general idea was given in #9961, merging.

**Comment by romanShekhtman** [comment]
Since ntuple got deprecated, I think someone should modify the ndgrid.jl file in the examples directory.
The following is the current output:

```
julia> include("ndgrid.jl")
meshgrid (generic function with 3 methods)

julia> a = ndgrid(1:3,1:4,1:2);
WARNING: ntuple(n::Integer,f::Function) is deprecated, use ntuple(f,n) instead.
 in depwarn at ./deprecated.jl:62
 in ntuple at deprecated.jl:49
 in ndgrid at /home/roman/julia/julia/examples/ndgrid.jl:21
while loading no file, in expression starting on line 0

julia> versioninfo()
Julia Version 0.4.0-dev+5203
Commit 7e4f148* (2015-06-04 17:16 UTC)
```

**Comment by timholy** [comment]
Fixed in 85e3fe0339e08d52c17193cca598d7018bca8de3. If you noticed this because you use `ndgrid`, consider contributing a test for it (in `test/examples.jl`), as otherwise problems like this will go unnoticed by developers.

**Comment by tkelman** [comment]
Hm. Why didn't https://github.com/JuliaLang/julia/blob/85e3fe0339e08d52c17193cca598d7018bca8de3/test/examples.jl#L23 show this warning?

**Comment by romanShekhtman** [comment]
@tkelman  In the examples.jl, the call to ndgrid was 2 AbstractVectors.  The warning would only appear if the call has 3 or more of them.

**Pull request merged**
