### PR TITLE
`unsafe_load` -> `@inbounds codeunit`

### PR DESCRIPTION
**Pull request by Keno**
Addresses post-commit review in #23562.

### CODE REVIEW

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks("string")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23582#issuecomment-327040286) has completed - successfully executed benchmarks. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/e501952e6465771ed9cb001d2919711d48ad74e2/b33286e/report.md). cc @ararslan

**Review by vtjnash — APPROVED** [review]

**Comment by Keno** [comment]
@nanosoldier `runbenchmarks("string", vs = ":master")`

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/23582#issuecomment-327068733) has completed - no performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/4a9c66ee1e8326ec43e06e4a0a97614cf7a848ee/6792a15_vs_10ae1b9/report.md). cc @ararslan

**Pull request merged**
