### PR TITLE
[WIP] SparseVector

### PR DESCRIPTION
**Pull request by lindahua**
This is based on the discussion in #11324. This PR remains WIP, and it is doing the following:
- [x] Add the `SparseVector` type.
- [x] Add methods of the `SparseVector` type.
- [ ] Add methods that interact with both `SparseMatrix` and `SparseVector`. 
- [ ] Add relevant linear algebraic methods.
- [ ] Add a complete test suite.
- [ ] Add documentation.

### CODE REVIEW

**Comment by ViralBShah** [comment]
We will also need methods for `AbstractMatrix` and `SparseVector`. It would be nice to have some ways to iterate over both sparse matrices and vectors with the same API.

**Comment by mlubin** [comment]
As @StefanKarpinski suggested, let's make sure we have complete code coverage for this.

**Comment by lindahua** [comment]
Depending on the decision in #11408

**Comment by lindahua** [comment]
The last commit of this PR passed tests (as shown by Travis-ci). The appveyor issue is unrelated. Of course, more tests are to be added.

**Comment by tkelman** [comment]
The AppVeyor failure is not unrelated. I can reproduce it by running `make testall1` locally on this branch, even on 64-bit Linux. It's most likely some dumb variable name conflict.

**Comment by lindahua** [comment]
Note: I am now working towards the NIPS 2015 submission deadline on June 6. Will resume the efforts here afterwards.

**Comment by tkelman** [comment]
Thanks for the update Dahua. Good luck with your submission.

**Comment by tkelman** [comment]
#11583 would be good to address here, once you get back to this.

**Comment by ViralBShah** [comment]
@lindahua Do you think we can do this in the next couple of weeks - which would make it possible to include in 0.4?

**Comment by lindahua** [comment]
I don't think I can have much time coding Julia in the coming month, as I have to kick start some new research projects. However, this is not a very difficult tasks, and I wish people interested in this PR can continue the efforts ...

**Comment by lindahua** [comment]
I am now resuming the efforts on this.

**Comment by tkelman** [comment]
I have a cleaned-up branch of this at https://github.com/JuliaLang/julia/tree/tk/sparsevec that you should start from, that at least passes tests. It doesn't address the unchecked items in the list up top though.

**Comment by lindahua** [comment]
Thanks, I will look into that.

**Comment by lindahua** [comment]
This PR is going to change the semantics of several functions (*e.g.* `sparsevec` will return an instance of `SparseVector` instead of `SparseMatrixCSC`) and may possibly break some client codes. Given that we are now very late in the 0.4 cycle, I think it is better to make this happen post-0.4.

Also, many more functions are being implemented, tested, and tuned in the SparseVectors package. 

I am closing this, and will make another PR, when:
- Julia 0.4 is released
- The package `SparseVectors` already implements all the functions needed to be transferred to the Base.

**Comment by tkelman** [comment]
How do you plan on making the SparseVectors package correctly implement things that are currently buggy in base? Non-exported replacements like `SparseVectors.sparsevec` ?

**Comment by lindahua** [comment]
I am now adding `sparsevector` to the package, which plays a similar role as `sparsevec` but returns a `SparseVector` instance. This function will be renamed to `sparsevec` when transferred to the Base.

**Comment by tkelman** [comment]
Sounds reasonable. Will the package try to change base's indexing rules, returning a SparseVector from columns slicing of a SparseMatrixCSC? I think that's the biggest most important change here that would be worth the possible breakage no matter when we decide to do it, but may as well do this right instead of rushing it.

**Comment by lindahua** [comment]
Sure, will explore the slicing stuff as next major step in the package development.

Currently, we have ``view(A, :, i)`` that returns a `SparseVectorView` instance when ``A`` is a sparse matrix and ``i`` is an integer. But will of course do more later.

**Comment by mbauman** [comment]
Hearty bump!

Any chance this could be revisited in the near future?  Missing a real vector makes indexing into sparse matrices wonky.  And it only gets stranger if we drop scalar dimensions — because then `S[1,:]` becomes… a 1-column matrix?

**Comment by lindahua** [comment]
I figure maybe I have to say that I probably won't be able to find enough time to push forward this PR before mid November. 

The SparseVectors package has been quite stable. Anyone who are willing to push forward this please feel free to make a PR based on the whole / part / or none of that package.

**Pull request closed without merging**
