### PR TITLE
add support for split debuginfo files

### LINKED ISSUE #17854: Support split debug info on linux
This may not useful for sysimg (and possibly libjulia) since backtrace test can fail without the split info installed but could be useful for external libraries since some distributions build them that way.

### PR DESCRIPTION
**Pull request by vtjnash**
There seem to be a few variations on the tools and arguments
available for creating split debuginfo files.
I used the following:

objcopy --only-keep-debug libjulia.so libjulia.so.debug
strip -g libjulia.so
objcopy --add-gnu-debuglink=libjulia.so.debug libjulia.so

fix https://github.com/JuliaLang/julia/issues/17854

### CODE REVIEW

**Comment by tkelman** [comment]
can we test this via libccalltest?

**Comment by yuyichao** [comment]
Ref https://www.sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html, which specifies the gdb search order (which is hopefully the order distros follows) as well as the build-id method. I'm not sure what each distros uses (Arch use `/usr/lib/debug` as the global debug info directory and provide files for both methods). We probably need to implement those to fully support distro packages after this PR is merged.

**Comment by Keno** [comment]
Yes, `/usr/lib/debug` is the standard path across distros.

**Comment by vtjnash** [comment]
ok, added support for all of the path options for debug-link. I didn't add support for `build-id` yet, but that'll be easy enough when we need it.

**Pull request merged**
