### PR TITLE
Tests for A^p for (secretly) Hermitian and diagonal

### PR DESCRIPTION
**Pull request by kshyatt**
A few branches in `dense.jl` were missed.

### CODE REVIEW

**Comment by kshyatt** [comment]
Should be compatible with #22923

**Review by fredrikekre — APPROVED** [review]
Seems like all the tests from line 551 to 628 could be done with a loop, but doesn't really matter.

**Comment by fredrikekre** [comment]
Lets restart CI after #22923 just in case

**Comment by fredrikekre** [comment]
We are now hitting this:
```julia
julia> A = complex.(rand(2,2), rand(2,2));

julia> sqrtm(Symmetric(A))
ERROR: MethodError: no method matching sqrtm(::Symmetric{Complex{Float64},Array{Complex{Float64},2}})
```

I am confused why we did not hit that code path with the tests in #22923

**Comment by kshyatt** [comment]
Good call rerunning CI!

**Comment by fredrikekre** [comment]
superseded by #23158

**Pull request closed without merging**
