### PR TITLE
Remove nonstandard header sys/sysctl.h

### PR DESCRIPTION
**Pull request by ghost**
This header prevents me from building Julia on musl libc.

```
/home/alba/julia/src/sys.c:16:24: fatal error: sys/sysctl.h: No such file or directory
compilation terminated.
Makefile:94: recipe for target 'sys.o' failed
make[1]: *** [sys.o] Error 1
```

If I remove it from julia/src/sys.c then it works.

Why is sys/sysctl.h needed in first place? I cannot find it in POSIX.

### CODE REVIEW

**Comment by tkelman** [comment]
Blame says https://github.com/albap/julia/commit/5733c5149c69ea5375e381b38bc21c67258e9c5e, there are still a few places we use `sysconf` or `sysctl` in this file. Let's see if deleting the include makes it through CI.

**Comment by yuyichao** [comment]
Looks like this is a [FreeBSD function](https://www.freebsd.org/cgi/man.cgi?sysctl%283%29) which GLibc also provide. The fallback is another non-standard `sysconf(_SC_NPROCESSORS_ONLN)`. Since these are all gaurded in `#ifdef`'s, I doubt this will break compilation but it can silently makes cpu cores detection stop working.

**Comment by albap** [comment]
So you suggest something like this?
```
#ifdef __GLIBC__ || __FreeBSD__
 #include <sys/sysctl.h>
#endif
```
Or is the current commit fine?

**Comment by tkelman** [comment]
Putting it behind an `#if defined(__GLIBC__) || defined(_OS_FREEBSD_) || defined(_OS_DARWIN_)` would probably be safer than just deleting it. Breaking core count detection on FreeBSD would be unfortunate, we don't have FreeBSD CI or buildbots or any other easy way of testing there that I know of.

**Comment by albap** [comment]
But keeping unneeded headers isn't good either, unless really necessary.
I think @EdSchouten can help us here :)

**Comment by yuyichao** [comment]
`libuv` provide `uv_cpu_info` for this so we can probably use that instead instead. The bsd/darwin/linux code path looks fine. However, the windows version only uses our "fallback method" the other method on windows was added in https://github.com/JuliaLang/julia/commit/2962bdee4c2292ef84d4327b58a7a3056046e795#diff-76299f46e9007f8bcb548dd2036ceeb6L182 and there was previously some discussion about core count without hyperthreading. Is that what this method for? @Keno

**Comment by EdSchouten** [comment]
On FreeBSD it should also be possible to use `_SC_NPROCESSORS_ONLN`. A way to write this without too much ifdef mess would be:

```
#include <unistd.h>
#ifndef _SC_NPROCESSORS_ONLN
#include <sys/sysctl.h>
#endif

...
{
#ifdef _SC_NPROCESSORS_ONLN
    // Call sysconf().
#else
    // Call sysctl().
#endif
}
```

**Comment by albap** [comment]
Why hasn't this been merged?
sys/sysctl.h is not defined by POSIX, isn't portable, and prevents people on musl libc systems to compile Julia.

**Comment by yuyichao** [comment]
As mentioned above, this introduces changes in which codepath is compiled. (note that being able to compile without the header doesn't mean the header is not used). We can probably use the libuv wrapper for this one, at least on non-windows maybe.

**Comment by StefanKarpinski** [comment]
There was a question above for @Keno which wasn't answered about libuv.

**Comment by albap** [comment]
@Keno can answer the question about libuv?

**Comment by Keno** [comment]
The fallback method does not know how to properly cope with processor groups, so is incorrect on high-core-count machines. I don't remember how hyper threading affects either.

**Comment by yuyichao** [comment]
I guess a safe option is to use the current method on windows and libuv everywhere else?

**Comment by Keno** [comment]
probably, yes

**Pull request closed without merging**
