### PR TITLE
fix #38386, macro defining empty function with escaped name

### LINKED ISSUE #38386: defining empty function with escaped name in macro does not work
When I try to define an empty generic function from within a macro using an escaped name I get a 'malformed expression' error. Doing exactly the same thing but with a function with an empty argument list works.

```Julia
julia> macro Bla()
       fname = :myfun
       :(function $(esc(fname)) end)
       end
@Bla (macro with 1 method)

julia> @Bla
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at REPL[8]:1

julia> macro Bla()
       fname = :myfun
       :(function $(esc(fname))() end)
       end
@Bla (macro with 1 method)

julia> @Bla
myfun (generic function with 1 method)
```

### PR DESCRIPTION
**Pull request by JeffBezanson**
fix #38386

### CODE REVIEW

**Comment by simeonschaub** [comment]
Would it make sense to backport this?

**Comment by KristofferC** [comment]
To what?

**Comment by simeonschaub** [comment]
1.5, or is there even going to be a 1.5.4 release?

**Comment by KristofferC** [comment]
Ah, 1.5. Can add a backport label in case.

**Pull request merged**
