### PR TITLE
Disable `DL_LOAD_PATH` prepending for `@`-paths on Darwin

### PR DESCRIPTION
**Pull request by staticfloat**
Many thanks to Randy Rucker from Apple for pointing out that we were
technically relying on undefined behavior in `dyld` for loading things
via `jl_dlopen("@loader_path/@rpath/libfoo.dylib")`, due to the
composition of `dlopen("@rpath/libfoo.dylib")` in our Julia code, and
the `DL_LOAD_PATH` prepending we do in `jl_load_dynamic_library()`.

This PR uses a slightly modified version of a patch emailed to me by
Randy, and should solve
https://github.com/JuliaLang/Downloads.jl/issues/149 on macOS Monterey
where the undefined behavior in `dyld` has changed.

### CODE REVIEW

**Comment by staticfloat** [comment]
Confirmed to fix https://github.com/JuliaLang/Downloads.jl/issues/149

**Comment by vtjnash** [comment]
Why is this code trying to handle full paths (with `/`) in them anyways?

Also, seems like we have special handling here for `@executable_path` that is now getting dropped on macOS?

**Comment by vtjnash** [comment]
I don't understand why this code is combining `a/b` with `Dl_LOAD_PATH`, and not just when given `b`. It is common for the shell, for example, to only search if given only a name and not a path.

**Comment by staticfloat** [comment]
Aha, I see what you mean.  Yeah, that's not necessarily useful.

I think we can probably refactor this to be a three-step process:

1) Translate `@executable_path/`-style modnames to an absolute path.
2) Do `abspath` and `is_atpath` detection (the latter still macOS-only)
3) Enter `DL_LOAD_PATH` loop.

This way, we'll have consistent handling across platforms as much as possible, and we cut down on unnecessary `jl_load_dynamic_library()` calls.

**Comment by staticfloat** [comment]
Looking into this a bit deeper, I see that we are actually transforming the entries of `DL_LOAD_PATH`, not `modname`.  E.g. we are allowing for `DL_LOAD_PATH` to contain `@executable_path/../lib/`, and then prepend it to all entries.

I had forgotten that that was how I designed this, and I'm not at all sure that this is precisely what we want.  I don't think we're actively using this feature yet, so we can still change it if we want to.  This was done to serve [these changes](https://github.com/JuliaLang/julia/commit/d347b470103919fd667a6818b6ac20b41fb2c823#diff-552535418914ef7bb1ebe851ebb5bdd5c1485570a1b4c24ffa42a8d90aa972deR183-R188) from my JLL stdlibs PR, where I wanted to get `Base` able to `dlopen("libpcre2-8")` when that file lived in some very specific location.  Looking back on it now, my gut says that the "right" way to do this would be for us to `dlopen("@executable_path/../whatever")`, but the reason we aren't doing that is because we just do `ccall)` without any explicit `dlopen()` on `libpcre` [due to us needing `libpcre` so early on](https://github.com/JuliaLang/julia/commit/d347b470103919fd667a6818b6ac20b41fb2c823#diff-dd5344d755b4d6c10dfd049583ff3b3ebd4c5c38007eced4628d420627dcd4fcR6-R10) that we don't have access to niceties like `joinpath()`.  We could, of course, hardcode a specific `dlopen()` instead.  I'm undecided.

**Pull request merged**
